### ISSUE TITLE
 Going to prev block instead just one line up

### ISSUE THREAD

**Issue by kelegorm** [typora/typora-issues#10]
I have this text:
> This is a first paragraph. Words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words
> ~/*empty line*/~
> This is a third paragraph. And we have empty line above. Words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words, words

If cursor stand on some word (not first line in paragraph) in third paragraph and I press 'up' key, it goes to empty line before paragraph. But if I add any chart into empty line - cursor moves properly.

**Comment by abnerlee** [comment]
Fixed in v0.9.6.8
