### ISSUE TITLE
Indent problem

### ISSUE THREAD

**Issue by tsingwong** [typora/typora-issues#1009]
Machine: Mac OS  10.12.6 
Version: 0.9.9.10.9 (0.9.9.10.9)

 first  indent is 4 space
![image](https://user-images.githubusercontent.com/16622888/32214174-fde61fd2-bdeb-11e7-8a1e-c3291b49a0b6.png)

when enter the bracket, indent change to 2 space

![image](https://user-images.githubusercontent.com/16622888/32214381-a7eeb980-bdec-11e7-95ca-8450584ba8fb.png)

I want to set default indent to 4 space.

My English is very poor, I hope you can understand and help me~

Thanks!

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/498
