### ISSUE TITLE
Bug: Inserting a link with existing text highlights one fewer character

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#101]
If you highlight some text while having a URL in your clipboard, the app helpfully creates the link and highlights the URL portion. However, it always highlights one fewer character. So if you forget about the helpful behavior and paste in the URL again, the URL is wrong because the last character is actually doubled.

This happens both when the link wraps to another line and not, see screenshots.

<img width="293" alt="bug-multiline" src="https://cloud.githubusercontent.com/assets/1819485/13898722/2628a7ce-edb1-11e5-9b84-7bbef63d8f13.png">
<img width="178" alt="bug-singleline" src="https://cloud.githubusercontent.com/assets/1819485/13898723/274c5dc6-edb1-11e5-8a46-8edea775fc52.png">

**Comment by abnerlee** [comment]
fixed in new version
