### ISSUE TITLE
file name disappearing when saving in File tree view

### ISSUE THREAD

**Issue by bodaz** [typora/typora-issues#1010]
Typora version: Version 0.9.9.10.9 (0.9.9.10.9)
OS version: MacOS High Sierra version 10.13 (17A405)

When saving a file named "01-introduction.md", the file name disappears in the file tree view. This bug does not occur for other files strangely. 

As shown in this gif, the change happens when I pressed cmd+s:
![typora-bug](https://user-images.githubusercontent.com/6238558/32216745-b1d6ea54-be1d-11e7-857b-a1a9be71f2ed.gif)

**Comment by bodaz** [comment]
When this happened again, I recorded the steps to reproduce this error:

![screen shot 2017-11-01 at 11 46 11](https://user-images.githubusercontent.com/6238558/32273416-516d2344-befa-11e7-90df-33a20563df1a.png)

Open Folder
When dialogue window opened, create a new folder, say "test"

![screen shot 2017-11-01 at 11 48 19](https://user-images.githubusercontent.com/6238558/32273496-98c79ef4-befa-11e7-9839-141553627a37.png)

We are in this screen of a new empty document within the "test" folder

Save the document, say "one.md", don't see it on the File tree view immediately

Refresh folder

![screen shot 2017-11-01 at 11 49 59](https://user-images.githubusercontent.com/6238558/32273574-d1c4c1f0-befa-11e7-8feb-92cc69a48079.png)

The document is there, try save document again and the described glitch happens

**Comment by amrangaye** [comment]
I am also facing this exact same problem on OSX - as soon as I save the file in question disappears from both Library and File Tree view. I'm on 0.9.9.10.9 (0.9.9.10.9) as well.  

Thanks.

**Comment by mkos** [comment]
I'm experiencing same issue. Interesting thing is that I have tried saving a lot of files in the directory, and only a smart part of them has this problem. I tried different sorting shemes (newest on top, alphabetical), same issue. Also it's the same for File List and Tree View view.

In one trial, I saw following behavior, maybe this will give you some clues: I have a file called `posa.md`. After hitting `Cmd+s`, for a second a file called `posa~.md` appeared and then almost instantly disappeared in the same manner as other files disappear from File view. Assuming that this is some cache, or working copy of a file, I'd suspect scenario where there is no working copy of a file and File View is trying to filter out too much.

**Comment by petarov** [comment]
I've got the same situation with typora `0.9.9.11.2` and macOS `10.13.3 Beta`.

There are two files in my folder - `scene_01.md` and `scene_01-1.md`. When I make some changes and save `scene_01.md` it disappears from the Files view.

**Comment by abnerlee** [comment]
I still never met this.

So, what's your option in System Preference -> General of following?
![snip20180102_1](https://user-images.githubusercontent.com/1621242/34475200-c3784680-efc4-11e7-860f-e0b8da6b38b8.png)

Do you use SSD or not SSD?

Do you have other apps open or editing the same file?

**Comment by mkos** [comment]
Thanks @abnerlee for looking into this. I have "Ask to keep..." option disabled, but enabling it doesn't help. Second option is enabled. I have SSD (Macbook Pro, 10.11.6) and I'm using Typora within Dropbox folder only. I don't have other apps open and accessing these files.

**Comment by abnerlee** [comment]
I can reproduce in one way

1. Open Typora, and it will have a blank page where new notes can be written
2. Click the + sign on the SideBar to add a new notes, with name “Note”. But do not click on it, remain the text editor at current blank page
3. Write something on the black page, and save it to the same location of the “Note” in step 2, and replace it

So if you do not save and replace the existing file (step 3), will this bug happens?

**Comment by abnerlee** [comment]
Add extra check for file replacement. Should be fixed in v0.9.9.12

Please reopen this if it still occur.

**Comment by mkos** [comment]
I did a few tests and it seems it works ok right now.

**Comment by petarov** [comment]
@abnerlee It looks good on my side as well. Thank you!
