### ISSUE TITLE
Detect modifications made outside of Typora then prompt to apply or maintain origin

### ISSUE THREAD

**Issue by wangkaibule** [typora/typora-issues#1011]
One must-have feature that is absent in Typora.

**Comment by AlexPasternak** [comment]
But why are you using anything but Typora to modify MD files?! :-) Kidding, obviously it happens with source control and other reasons.

**Comment by wangkaibule** [comment]
Typora is a really excellent MD writer & reader when someone use it to create a Markdown file from nothing or append some new content at the end of a existing file, and that enables me to use Typora a lot to do some text creation job without any distraction from detailed formatting. However, when I have to edit some text in the middle of a MD file, Typora is no more than a notepad. So I have to use another more capable editor such as VIM to move around the file or do some complex batch jobs then come back to Typora to make sure everything is correct (that's right, I'm bad at recognizing those dashes and indents in pure MD files, otherwise, I would not use Typora at all).

Also, I'd like to sync a MD file with multiple device and edit it on, then I wish I can rush back to my PC and continue the editing with Typora immediately without close already opened Typora instance, look around for my file then open it again.

I've already noticed current version of Typora is able to detect a file was edited and mark that file as "unsaved", so it is actually very close to implement the "reload" feature I've proposed here. I think this is a must-have feature for one becoming a decent text editor (try not to argue with me by comparing with notepad or MS Word).

**Comment by abnerlee** [comment]
What's your OS/Typora version?

This is already supported, if no changes in Typora, it will be reloaded immediately, if has changes, a dialog will pop up to ask whether to reload from the disk or keep changes in Typora

**Comment by wangkaibule** [comment]
Uh... yes it is. Confirmed that Typora can reload file automatically in version 0.9.38 but without any prompt. I'm using Windows 10.

**Comment by abnerlee** [comment]
> Uh... yes it is. Confirmed that Typora can reload file automatically in version 0.9.38 but without any prompt. I'm using Windows 10.

Do you have **unsaved** change in Typora?

**Comment by wangkaibule** [comment]
I see, Typora will ask me to choose a version when there is a proning writing conflict, that should be enough. Thanks for your explanation and the excellent work 😃 .

**Comment by wangkaibule** [comment]
This auto reload function seems not working after I modify the md file with VIM, please verify.

**Comment by abnerlee** [comment]
#1401 #1953
