### ISSUE TITLE
Cannot automatic numbering when the article is little long

### ISSUE THREAD

**Issue by XingwenZhang** [typora/typora-issues#1012]
Version: Mac 0.9.9.10.9 

This problem exists from the previous version to the updated version. 
When the article is long, the automatic numbering has some bugs.
For example, 
1. headline1
    1. sub1
    2. sub2
2. headline2

when input 2.headline2, it often occurs cannot input comma, period and has no response to return key. This problem occurs very very often. Nearly every time, plz fix this bug asap.

**Comment by abnerlee** [comment]
should be fixed in newest version
