### ISSUE TITLE
Form alignment in non - English cases

### ISSUE THREAD

**Issue by chenwq3** [typora/typora-issues#1013]
Hello!

First of all, thanks for Typora, that helps me a lot when I writing diary and others.

The version Typora (for Windows): version 0.9.38(beta).

When you create a table with Typora, It will try to align each column with spaces, which does a great job in English. But when it comes to non-English, Typora seems to treat a non-English characters as one English alpha.

![capture](https://user-images.githubusercontent.com/25943138/32256922-0bf4fac4-beed-11e7-8780-9beae1e3fd18.PNG)

I know in some cases, a non-English character width takes more than two alpha characters. It may be very tricky to determine how width of some non-English characters. But before a solution come out.
A workaround solution, treating a non-English characters as two alpha char, may be acceptable, if that not introduce other issues.

Just a thought, hope you consider it.

Best Regards,
Weiqi Chen.

**Comment by abnerlee** [comment]
Fixed in new version
