### ISSUE TITLE
Unable to save files to Google Drive File Stream

### ISSUE THREAD

**Issue by mrdanbrooks** [typora/typora-issues#1015]
Typora fails to save files to Google Drive File stream on OSX. It can save successfully to normal file system, but cannot create a new file on Google Drive, or move an existiing file to Google Drive. The built in "TextEdit" app has no problem doing either of these actions. _Interestingly, Typora CAN successfully "duplicate" an existing file on Google Drive and then change the name as a work around to generating a new file on Google Drive_.

The following error message shows up when you try to save a new file to Google Drive:
`Typora[301]: libcoreservices: __create_or_fix_relative_directory: 940: __dirhelper_create_relative returned (os/kern) failure`

- macOS 10.12.6
- Google Drive File Stream 25.1.76.2046

**Comment by mrdanbrooks** [comment]
New information (not sure if it is related, but seemed likely enough to include).

When I was able to successfully save the file to the main file system, it added a `?` to the beginning of the filename I typed in (e.g. `?nameityped.md`). In Finder, it shows up as just the name I typed in, but using the `ls` command in terminal the file shows the `?` at the beginning.

**Comment by abnerlee** [comment]
Tested OK on Google Drive Backup & Sync service.

Don't have G Suite to install Google Drive File stream, so I cannot reproduce this on Google Drive File stream.

Please try capture more logs, or contact Google Drive for support.

**Comment by adreasnow** [comment]
For other people having this issue, Google Drive File Stream requires full disk access for typora to be able to save to it.
