### ISSUE TITLE
[toc] on github

### ISSUE THREAD

**Issue by johntiger1** [typora/typora-issues#1016]
I would like the [toc] you see on typora to have an option to generate the Markdown markup so that it will render on github.  

I saw several issues regarding this; has this been addressed/fixed natively in Typora (or with use of a Typora plugin)?

https://github.com/typora/typora-issues/issues/369
https://github.com/Riverscapes/champ-transformation-tool/issues/4

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/169
