### ISSUE TITLE
Suggestion of the way adjusting the size of images

### ISSUE THREAD

**Issue by chenwq3** [typora/typora-issues#1018]
Hi, 

In typora, you can adjust the size of images by using `<img>` label with attributes `width` etc. . But is there a more elegant way? for example:

```md
![This is a pic.](https://typora.io/img/new/inline.png){:height="300px" width="400px"}
```

It would be nice to have that feature. 
Hope you consider it when you're not busy :grin:.

Best Regards,
Weiqi Chen.

**Comment by abnerlee** [comment]
We are less likely to introduce this syntax since it cannot be supported by other markdown editors/parsers.
