### ISSUE TITLE
0.9.38 broke new line in table feature

### ISSUE THREAD

**Issue by rileal** [typora/typora-issues#1019]
I version 0.9.37 I used shift+enter to get a new line in a table. In 0.9.38 it doesn't work and "<br />" string appears.

In the changelog it says "1. Support `<br/>` tag in live rendering."

Is there any way to go back to 0.9.37 until this bug is fixed?

**Comment by abnerlee** [comment]
`shift+enter` is to create new line inside table or outside table (like in paragraph)
`ctrl+return` is used to create new block in current container, e.g: new row in table, or new paragraph in current list item.

In previous versions, `shift+enter` in table is a fallback of `ctrl+enter`.

So, please `ctrl+enter` for new table row.
