### ISSUE TITLE
Treat section of file as literal?

### ISSUE THREAD

**Issue by johntiger1** [typora/typora-issues#1020]
Is there any way to treat an entire section of a file as literal? i.e. do not interpret *, etc. as markup. Essentially, what I am looking for is a way to backslash escape the entire section. Thanks

**Comment by vassudanagunta** [comment]
Not sure, but you can check the [CommonMark](spec.commonmark.org) spec, which Typora follows.

**Comment by abnerlee** [comment]
@johntiger1 there's no syntax to escape a range of texts in markdown, you could use code block instead
