### ISSUE TITLE
Remember "Files" opened directory and expand state

### ISSUE THREAD

**Issue by rafi** [typora/typora-issues#1022]
I find it un-friendly when I need to select the last opened directory every-time I open Typora, and it would be fantastic if it remembered the collapse/expand state of each sub-directory.

**Comment by matchavez** [comment]
Absolutely agree.

**Comment by benjaminsaljooghi** [comment]
Agree. +1

**Comment by OttoVanluchene** [comment]
+1

**Comment by anjia0532** [comment]
+1

**Comment by VitorHP** [comment]
+1

**Comment by aldoKelvianto** [comment]
+1

**Comment by kecaiwu** [comment]
+11

**Comment by jyim6** [comment]
+1

**Comment by HADB** [comment]
+1

**Comment by EddieRietz** [comment]
+1

**Comment by Silentorchestra** [comment]
+1

**Comment by RishiSpeets** [comment]
+1

**Comment by ouweiya** [comment]
+1

**Comment by renestalder** [comment]
Giving another push for this. That would be really great.
Apart from that, keep up the good work.

**Comment by mesquaredinc** [comment]
+1

**Comment by abnerlee** [comment]
Can be set in preference panel.

Expand state is not supported though

**Comment by anjia0532** [comment]
![snipaste20180502_160519](https://user-images.githubusercontent.com/15098916/39512209-a5f0faa0-4e22-11e8-80b3-8543f8680ab3.png)

yes,it worked. thanks for your job.
