### ISSUE TITLE
Provide an interface to Babelmark for testing

### ISSUE THREAD

**Issue by Crissov** [typora/typora-issues#1023]
I'm not sure whether your markdown parser is custom-build or relies on an external library. #315 #369 If it is your own, it would be nice to host an instance of it online and [register it](https://github.com/babelmark/babelmark-registry) with [Babelmark 3](https://babelmark.github.io/) or [register it](https://johnmacfarlane.net/babelmark2/faq.html#how-can-i-add-my-markdown-implementation-to-babelmark-2) with [Babelmark 2](https://johnmacfarlane.net/babelmark2/) or both.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/369
