### ISSUE TITLE
Hide `<br>` when block or table cell does not have focus.

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1026]
`<br>`, `</br>` and `<br/>` are visibly ugly, and especially in table cells prevent displaying the tables as they would look once rendered in HTML.

I suggest they be hidden unless the paragraph or table cell has focus, similar to how regular Markdown markup characters are hidden when not in focus.

Perhaps this should be applied to most or all other embedded HTML? Or should this be handled with custom CSS?

**Comment by vr8hub** [comment]
I would say they should be interpreted rather than hidden. See my #1367.

**Comment by vassudanagunta** [comment]
By "hide" i meant the markup, not the effect. Typora already renders (interprets) the effect (newline).

**Comment by abnerlee** [comment]
Option added under `Edit` -> `Whitespace and Line Break` from menu

**Comment by lukejanicke** [comment]
That option is effective and neat. I’m glad to have found it. But I wonder, would it be possible to have the cursor positioned on the new line where text is to be entered. The cursor sits at the end of `<br />` after you press SHIFT + ENTER until you type a new character, and then everything jumps down to the next line, where it should be. It is ever so slightly misleading.

**Comment by szjiajin** [comment]
Although <br/> can be hidden but it is occupying the space even when it is hidden. Do you think this needs to be modified? Thank you
![image](https://user-images.githubusercontent.com/13881003/67368143-638d6600-f5a9-11e9-9a0c-fe75357c3636.png)

**Comment by vassudanagunta** [comment]
@abnerlee That is occupies space is a serious issue because it affects column width. The main reason people add manual line breaks in table content is to limit the width of the column, but then Typora undermines that effort by making the column wider to show the `</br>`

**Comment by vassudanagunta** [comment]
@abnerlee Should I create a new issue for what @szjiajin describes, or will you re-open this issue?

If you are not convinced of the need, I can produce more screenshots of how it makes table cells both look bad and hard to edit.

**Comment by abnerlee** [comment]
It is already fixed for what @szjiajin describes, could you try newer versions?

**Comment by vassudanagunta** [comment]
Sweet! Sorry, I somehow missed the new setting. Thank you!
