### ISSUE TITLE
resize window cause images to blur/unclear ...

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#103]
pls see this gif for details, thanks.

![untitled](https://cloud.githubusercontent.com/assets/10832544/14224957/92c66e60-f8e3-11e5-9ce5-0eea1a6ca5c6.gif)

**Comment by abnerlee** [comment]
@leewi9 if you export as HTML, open in Safari and resize the page, would images become blur ?

**Comment by leewi9** [comment]
Hi, if export to HTML, it works fine and will not blur.

  

regards,

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On May 7 2016, at 10:11 am, AbnerLee &lt;notifications@github.com&gt; wrote:  

> [@leewi9](https://github.com/leewi9) if you export as HTML, open in Safari
and resize the page, would images become blur ?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/typora
/typora-issues/issues/103#issuecomment-217599150)![](https://github.com/notifi
cations/beacon/AKVKoJRFqBmgivxMnIUFh8PFB-Qw5XBTks5p-_TkgaJpZM4H-N3_.gif)

**Comment by abnerlee** [comment]
still met this bug?
