### ISSUE TITLE
can't write after code segment with bullet points

### ISSUE THREAD

**Issue by hjliag** [typora/typora-issues#1033]
if i make a bullet point and use ``` <enter> to write a code segment,
then in the next bullet point, when i tab one bullet point, i can't write!!
i'm using OS X and typora is latest version

![screen shot 2017-11-07 at 10 48 45 pm](https://user-images.githubusercontent.com/18301182/32496835-f05e4664-c40d-11e7-88de-59ceaab70022.png)
can't write here!!!

to write : 
![screen shot 2017-11-07 at 10 49 02 pm](https://user-images.githubusercontent.com/18301182/32496831-eb05a1d0-c40d-11e7-9c64-c0f186b81e7a.png)
then press tab
![screen shot 2017-11-07 at 10 48 34 pm](https://user-images.githubusercontent.com/18301182/32496875-0ab2abae-c40e-11e7-8917-2c981848e7bd.png)

should write like this!!

**Comment by abnerlee** [comment]
Fixed in new release
