### ISSUE TITLE
It's not appear after canceling double screen 

### ISSUE THREAD

**Issue by fangchaooo** [typora/typora-issues#1034]
**environment** : win10-x64
**screen** : A acer laptop screen ， A  Samsung screen

step：
1.  Open typora in laptop
2.  Link to an other screen and put software to it.
3.  Canceling Samsung screen ， open typora on laptop

except：
find typora on laptop

In fact：
There are not typora on laptop screen， but the process show it running。Link to screen, it's showing

**Comment by abnerlee** [comment]
typora version?

**Comment by fangchaooo** [comment]
0.9.37(beta)

**Comment by abnerlee** [comment]
Please update to latest version (v0.9.38)
