### ISSUE TITLE
Redundant semicolon after '&' while exporting to PDF

### ISSUE THREAD

**Issue by Charles-Neil** [typora/typora-issues#1035]
It's a tiny issue I discovered while using typora. When I typed the text below in typora and exported to PDF there is a redundant ```;``` after the ```&``` within the code block.
![issue](https://user-images.githubusercontent.com/23690914/32545588-24fa819a-c4b7-11e7-9682-30c3014d989f.png)

Here is the output:
![iss](https://user-images.githubusercontent.com/23690914/32545631-46017efc-c4b7-11e7-9cdc-8764d693a0a1.png)

OS: Ubuntu 16.04
typora version: 0.9.38

**Comment by lyfadvance** [comment]
besides ,when use <,> ,it has the same problem as &

**Comment by KunalSarkar** [comment]
Facing the same issue. Also, this is happening only when using ``` inline. If we use ``` on a new line then this is not happening.

**Comment by DimLight1998** [comment]
Same issue when using `'` or `"` .

**Comment by abnerlee** [comment]
fixed in new release
