### ISSUE TITLE
Cursor shows in code block when exported to html.

### ISSUE THREAD

**Issue by Drbelfast** [typora/typora-issues#104]
Exporting md to html when cursor was focused in code block will keep the cursor showing, which does not happen when in pdf.
<img width="790" alt="screen shot 2016-04-02 at 6 43 31 pm" src="https://cloud.githubusercontent.com/assets/6468832/14230243/7c4b56e4-f903-11e5-8bf5-1f320a59e36e.png">

Support drag md file into editor to open the file?

**Comment by abnerlee** [comment]
fixed in new version
