### ISSUE TITLE
Create new file in selected sub-directory using a template filename

### ISSUE THREAD

**Issue by mrmotallebi** [typora/typora-issues#1043]
Similar to QOwnNotes, I was wondering if you could add the feature to:

* Create the new file in the current expanded (sub-) directory.
* Name the file using a template, such as `note-%yyyyMMDDHH:mm%` so when creating a new file, it gets such a name (and is added as header to the content).

Thanks.

**Comment by abnerlee** [comment]
May be covered by https://github.com/typora/typora-issues/issues/863
