### ISSUE TITLE
Tag auto-completion breaks hr-functionality

### ISSUE THREAD

**Issue by hellerphilipp** [typora/typora-issues#1044]
Hey guys,

since it would be a way faster way to preview/see changes to your document, I would personally really welcome the addition of a previewing mode similar to GitHub gist.

Currently, in order to see a text bold (or italic), you need to close the tags like this:
`**bold text here**`

But while you're writing, it would be really nice if the text would be styled while still working on it, so it would also appear bold in the editor while just looking like this:
`**bold tex...`

Not necessarily needed, but I think it would be a really nice feature :)

Best regards,
Philipp 

***

EDIT: Turning on auto-pairing solves the initial problem, but adds a new one. With auto-pair for markdown elements enabled, you can't use `***` to hr anymore.

**Comment by hellerphilipp** [comment]
Wow thanks! At this point I'm sorry for this. Was disabled for any reason.

**Comment by hellerphilipp** [comment]
@AlexPasternak

**Comment by hellerphilipp** [comment]
@AlexPasternak noticed the issue again. When having tag auto-completion enabled, you can't do vertical lines using
`***`
anymore, because the Editor interprets the first two stars as a beginning of a bold text.
Of course I could use the source mode or write
`---`
instead, but I don't think that this is the ultimate solution.

**Comment by abnerlee** [comment]
Tried in Github, seems we should interrupt `****` as hr, so we can still use `****` as hr.

You could input `***` bt `Del` key instead of backspace key. or backspace on the 4th `*`.
For others, I think it would be the expected behavior and maybe side effect of the autopair mode,

***

> But while you're writing, it would be really nice if the text would be styled while still working on it, so it would also appear bold in the editor while just looking like this:
**bold tex...

I'm not quite understand this, you will still need to input the close `**` right?

**Comment by hellerphilipp** [comment]
> You could input *** bt Del key instead of backspace key. or backspace on the 4th *.
works, but is just a workaround. Maybe an "expected" side effect, but I think you should make it as easy to users as possible (e.g. if they start writing `***`, without "closing" the first star and then press return, the 4th star should be removed/ignored. (there are probably better solutions out there)

> I'm not quite understand this, you will still need to input the close ** right?
What I meant is that the editor could *preview* formatting before the stars are closed (similar to how it's handled in source mode), but this was just a suggestion. Enabling auto-pairing kinda solved it, but atted the other problem mentioned above.

**Comment by AlexPasternak** [comment]
For what he's requesting, you can check our MD apps like https://laverna.cc/app/ When you type **blah there, blah already shows up bold.

Seemingly related bug here, when using auto-complete tags:

- If I type **, completed to ****, then Down Arrow, I get a horizontal line
- If I type **, completed to ****, then End, then Enter, the text disappears entirely

For latter, this cannot be edited or fixed then, without going into Source Code mode. You basically bolded empty space, I guess.

![2017-11-15 16 39 48](https://user-images.githubusercontent.com/1819485/32861764-c3142360-ca23-11e7-912d-e317d34324bc.gif)

**Comment by abnerlee** [comment]
Autocomplete won't break `<hr/>` now ,since `****` will also be parsed as `<hr/>`
