### ISSUE TITLE
Update MathJax and mhchem

### ISSUE THREAD

**Issue by mhchem** [typora/typora-issues#1045]
It would be great if you could update the included versions of MathJax and mhchem.

**Comment by abnerlee** [comment]
I'm closing this since we may got update request every time MathJax release a new version. Please tell us the problem with current Mathjax instead.

**Comment by mhchem** [comment]
I am the author of the mhchem extension.
It seems that you are using an mhchem version that is more than a year old. You can enable a newer version with `mhchem: { legacy: false }`. As MathJax decided to separate the extensions more from the core, the `legacy: false` version was frozen and the newest version is distributed independently from MathJax. You will find the code at cdnjs or GitHub. ([Manual](https://mhchem.github.io/MathJax-mhchem/)) If I can assist you in any way, please tell me.

**Comment by mhchem** [comment]
It seems you still use the legacy version of mhchem. I strongly encourage you to set `mhchem: { legacy: false }` or, even better, use the newest version of the extension.

**Comment by abnerlee** [comment]
Yes, `mhchem: { legacy: false }` should be added. I will update on next version

**Comment by abnerlee** [comment]
Fixed in new release
