### ISSUE TITLE
Download servers may be at limit

### ISSUE THREAD

**Issue by mhchem** [typora/typora-issues#1046]
I needed several attempts to download the installation file at https://typora.io/#windows. 5 times or so, I got a slow download that ended with a "file incomplete" error from Chrome. It worked in the end.

**Comment by abnerlee** [comment]
Where's your location? It may be a network issue not a server limitation since I can download it sucessfully

**Comment by mhchem** [comment]
I am located in Germany with a bandwidth of 200 Mb/s. I just re-tested. I could download https://typora.io/windows/typora-setup-x64.exe with 2.5 MB/s (20 Mb/s). 1 of 10 test runs ended in (File incomplete). Yesterday, the ratio was more like 1:9 instead of 9:1.

**Comment by tylerhou** [comment]
Having the same issue trying to download the Mac version. I live in San Francisco with a bandwidth of ~500mb/s.

**Comment by abnerlee** [comment]
I out-scaled the server and updated the code following https://stackoverflow.com/questions/26106399/node-js-express-js-very-slow-serving-static-files how about try again later to see if it fixed?

**Comment by tylerhou** [comment]
Looks good! Thank you!

**Comment by mhchem** [comment]
Looks good. Downloads with double the speed now without any fails.
