### ISSUE TITLE
Windows 10 and secondary monitor

### ISSUE THREAD

**Issue by mhchem** [typora/typora-issues#1048]
I use Windows 10. When I close Typora on my secondary monitor and restart it again, it does not open at the exact same position, but is moved party out of screen. It can even be completely off-screen with no way to bring it back into view by using the mouse.

**Comment by mhchem** [comment]
Possibly a duplicate of #938

**Comment by abnerlee** [comment]
Typora version?

**Comment by mhchem** [comment]
version 0.9.38(beta)

**Comment by abnerlee** [comment]
I see, seems duplicate with #938
