### ISSUE TITLE
Sidebar doesn't work in source mode [mac]

### ISSUE THREAD

**Issue by hellerphilipp** [typora/typora-issues#1050]
When I'm in source mode and press the touchbar button to open the sidebar, it just doesn't open.

**Comment by abnerlee** [comment]
Source code mode does not support sidebar.

Source code mode are designed for temporary modification, so we do not want to spent too much time on this.

**Comment by hellerphilipp** [comment]
I use source mode all of the time :D

**Comment by vassudanagunta** [comment]
@hellerphilipp then most other Markdown editors would be better for you than Typora. In those you spend you time mostly in source mode, and give you a preview mode that you occasionally look at to see how the Markdown renders. 

Typora is only one that I know of that is the opposite of that. The only WYSIWYG Markdown text editor where you only occasionally go into a source view. So I'm with @abnerlee. Let's keep Typora special. We have enough of the other kind of editor.

**Comment by hitzhangjie** [comment]
When I want to ask this question just now, I think why typora behaves different with others, for example MWEB. MWeb cmd+r to toggle source code and render mode, it also supports others mode to split the workspace into left editor and right renderer.
Then I realizes typora is designed much better than MWEB. During actual editing process, we focus on content and render quality, what you get is what you see, typora behaves like this, simple and powerful.
I like MWEB, I also like typora. But keeping sidebar working as focus mode and typewriter mode, it would be much better and acceptable for other users.
