### ISSUE TITLE
typora get slow when the file size become 20k

### ISSUE THREAD

**Issue by xujingyi46** [typora/typora-issues#1051]
Hi, I got a problem that typora get slow when the file size become 20k.
my hardware is not bad:
CPU:  I5-6200
Memory: 8G
SSD
so how can I get through this problem ? with some configuraiton?

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/58

What's your OS, BTW?

**Comment by xujingyi46** [comment]
thanks for replying.
os on my machine is Win10
I have trid some methods following:
1. Update typora to the latest release
2. Update my graphic driver, and make typora use the independent graphic card rather than CPU graphic
3. close the spelling check in typora

but it doesn't work, typora still get slow when word count> 3000.
