### ISSUE TITLE
Equation references doesn't work in HTML/PDF export

### ISSUE THREAD

**Issue by gandalfsaxe** [typora/typora-issues#1054]
Hi,

If I have inline math / math block, .e.g.:

```
$$
e = mc^2
\label{test}
$$
```

then I can reference it later using `\ref{test}` or `\eqref{test}` inside inline math / math block.

However these links from \ref and \eqref` doesn't work when exporting:
* **HTML:** Makes the equation number clickable, but you're not taken to the equation when clicking it. So it seems to be aware that there should be a link here, but the link doesn't work.
* **PDF:** Equation number is not even made clickable, it doesn't work at all.

Can this be fixed?

**Comment by abnerlee** [comment]
should be fixed

**Comment by thenewera-ru** [comment]
> Math equation numbering/labelling and refererence? careteditor/issues#567

Still, doesn't worl. Typora version Version 1.0.5 (6032)
