### ISSUE TITLE
Fail to open save file dialogue removing one of drives

### ISSUE THREAD

**Issue by illava** [typora/typora-issues#1055]
I Used to save file in drive D. Now it is under repair (detached). Typora didn't show save file dialogue and I'm unable to save my doc in drive C.

**Comment by abnerlee** [comment]
Typora and OS version?

**Comment by illava** [comment]
Typora 0.9.38(beta)
Windows 10 Pro 1703 15063.726 64-bit

**Comment by illava** [comment]
The problem is still after reinstalling.

**Comment by illava** [comment]
I noticed it is still able to save file by Ctrl-s command. Only fail opening save file dialogue.

**Comment by abnerlee** [comment]
Does this issue still exist on current version?
