### ISSUE TITLE
Instability when working on a folder on a network drive

### ISSUE THREAD

**Issue by bordplate** [typora/typora-issues#1058]
Operating System: `Windows 10 Enterprise v. 1703 - Build 15063.674 - 64-bit`
Typora version: `0.9.38 (beta)`

# Brief
At work our "Documents" folder is redirected to a personal space on a network drive. I'm experiencing high instability with Typora when trying to create a folder and create files in that folder. The same issues arise when trying to work directly on the mapped drive, instead of in the redirected folder.

## Creating a folder
If I try to create a folder, the folder is created as usual, but the entire screen goes blank and only the top "toolbar" shows. The sidebar disappears and the file-edit window is unresponsive to clicks and keyboard strokes. The toolbar at the top still reacts to clicks, but the menu items' actions does not seem to work anymore. 

## Creating or renaming a file
The file itself is renamed and/or created, but Typora does not seem to update it's record, so saving the file no longer works and when trying to move to another file the error message `ENOENT: no such file or directory, open '\\folder-location\Test.md'` shows up even when trying to discar the changes.

**Comment by abnerlee** [comment]
Fixed on new version
