### ISSUE TITLE
Quick open on Windows/Linux

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1060]
Have you considered to make a quick open functionality similar to what we see in [Quiver](http://happenapps.com) and especially [Caret](https://caret.io)? Such that you could open a folder, then quick search, and then type any filename, which it could find with fuzzy search?

Ever better, combining a fuzzy search for files and contents in files (Quiver have this).

**Comment by abnerlee** [comment]
Quick open is already supported on macOS,

Search file content is duplicated with some other issues

**Comment by GandalfSaxe** [comment]
Ah yes my mistake, I somehow overlooked it.

And yes I see, searching file contents is discussed here: https://github.com/typora/typora-issues/issues/651
