### ISSUE TITLE
Add an option to hide menu bar on Linux

### ISSUE THREAD

**Issue by belenos** [typora/typora-issues#1061]
Please consider adding an option to hide the menu bar on Linux and to show it by pressing the Alt key — like Abricotine does.

![screenshot from 2017-11-21 05-39-21](https://user-images.githubusercontent.com/1954831/33062736-1a296656-ce7f-11e7-9aa4-a40b50a6397b.png)

I'm using Ubuntu 17.10 / Gnome Shell.

**Comment by abnerlee** [comment]
It can be set in Preference Panel -> Advanced Settings. (update to our latest version first)
