### ISSUE TITLE
Inside words, numbers between undercores are italic, letters are not.

### ISSUE THREAD

**Issue by dnav** [typora/typora-issues#1063]
Typora version: 0.9.38
OS: Windows 10 Pro 1709 64-bit

```markdown
MY_FIRST_MACRO
```
 is displayed as MY_FIRST_MACRO whereas
```markdown
MY_23_MACRO
```
is displayed as MY*23*MACRO.

Great product otherwise.

**Comment by abnerlee** [comment]
Fixed in new release
