### ISSUE TITLE
Source Code Mode does not visualize # marks in ``` code correctly 

### ISSUE THREAD

**Issue by feliksik** [typora/typora-issues#1064]
code  escaped with \`\`\`, like this: 

``` 
# this is a comment
this is code 
```
is not visualized correctly in the Source Code Mode, messing up the notion of what \`\`\` markers are starting/stopping code sections, and thus the entire document layout. The layout thinks the comment is a header, like so: 

# this is a comment 

Running 0.9.9.10.9 (beta)

**Comment by abnerlee** [comment]
In my testing 

```
# this is a comment
this is code 
```

renders correctly in source code mode, is its context related? If possible, could you provide a screenshot so we can see what's wrong?
