### ISSUE TITLE
Add "Save as..."

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1066]
Hi,

I'd really like a File->Save As... feature. It's especially confusing that Cmd+Shift+S is mapped to Duplicate, going against the convention of 99% of all apps out there.

**Comment by vassudanagunta** [comment]
@GandalfSaxe Typora is following the conventions for macOS. You must be on a different OS?

**Comment by GandalfSaxe** [comment]
Hmm yes fair enough. I am actually on macOS, but I must've used apps that mostly have Cmd+Shift+S as "Save as...", but I can see now that it's actually Cmd+Shift+Opt+S that is "Save as...", so it's good. My bad!
