### ISSUE TITLE
Quotation style

### ISSUE THREAD

**Issue by eddiee91** [typora/typora-issues#1068]
I have a proble in Typora. As in my language the quotation marks are not "abc", but rather „abc”, I can not use them, as there is no way to specify what type to use. 
I must mention that in the OS (Mac OS) it is specified that it should use smart quotes („abc”).

Thank you!

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1028 and https://github.com/typora/typora-issues/issues/137
