### ISSUE TITLE
Typora not working anymore on Ubuntu 17.10

### ISSUE THREAD

**Issue by bugsysop** [typora/typora-issues#1069]
When i click on app's icon nothing happening...

Tried then to load from terminal, the app is not loaded, and have this error message:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
```
Tried after du run with `sudo`: the app is running fine, but with same error message in terminal...

**Comment by abnerlee** [comment]
Could you check https://github.com/typora/typora-issues/issues/1027 just try reboot.

about error message Failed to load module "canberra-gtk-module", not sure if it can be ignored or not, but you could try install "canberra-gtk-module" by `sudo apt-get install libcanberra-gtk-module`

**Comment by bugsysop** [comment]
Yes this command solved the _error message_ but not the fact that Typoran is not running normaly: no graphical mode (clic on icon) and only in terminal with `sudo`...

**Comment by abnerlee** [comment]
@bugsysop What's the error message in terminal if you run without `sudo` ?

**Comment by bugsysop** [comment]
@abnerlee 
No message ! Just nothing happening...

I solved the problem removing the Typora directory in my Home:

```
sudo rm -fr .config/Typora
```

After, all worked like a charm
