### ISSUE TITLE
Having issues with saving and opening [0.9.0] [Windows]

### ISSUE THREAD

**Issue by vkbansal** [typora/typora-issues#107]
Having issues with saving files on a usb drive. I lost my work due to this.

After save, It goes in a loop of "reload from disk" and at the end saves a 0kb file.

Later, I copied some other file from usb drive to HDD and now it refuses to open it. 

Always a blank file is opened.

**Comment by abnerlee** [comment]
> After save, It goes in a loop of "reload from disk" and at the end saves a 0kb file.
That would be a bug related to external disk. Really sorry for that.

> Later, I copied some other file from usb drive to HDD and now it refuses to open it.
If possible, would you send the files typora won't open to <hi@typora.io>, maybe it is related to its encoding, but we are not sure about the reason

**Comment by abnerlee** [comment]
shoule be fixed in new release
