### ISSUE TITLE
Feature suggestion: Inline SVG drawing support

### ISSUE THREAD

**Issue by samuell** [typora/typora-issues#1070]
Hi and thanks for such an awesome markdown wysiwyg tool! 

I'm starting to use it as my main note taking tool, together with a bunch of simple scripts to manage markdown files with git, and also merge into epub notebooks with pandoc (https://github.com/samuell/mdnote).

One thing that would make typora into a viable alternative to something like onenote, for tablet/digitizer/stylus use, would be if it was possible to include quick drawings, saved as SVG (as separate files, or inline if possible), in markdown documents.

## Suggested way of working

Imagining it could work like this:

1. Click to insert new drawing, which would insert a small drawing area, as wide as the text, and in ca 10:15 landscape orientation
2. Enable simple drawing with a stylus or the mouse
3. Click on a "Finish" button to freeze the drawing into view-only mode

Having the drawing in an open format like SVG, should make it possible to keep the drawing tool simple, while allowing to script up more advanced workflows from externally, like path-to-text etc.

**Comment by abnerlee** [comment]
As a markdown editor, we are less likely to include this. 

But we have plans to include quick drawing function in our future note-taking tool.
