### ISSUE TITLE
Anchor opcode appears in Outline column

### ISSUE THREAD

**Issue by Philippe91** [typora/typora-issues#1071]
Let's say I have this in the raw text:

```
Hello {#nc_hello}
=====
```

Then in the Outline column, this will appear:

**Hello {#nc_hello}**

instead of simply:

**Hello**

**Comment by abnerlee** [comment]
We do not support 
```
Hello {#nc_hello}
=====
```

I will move this issue to https://github.com/typora/typora-issues/issues/1072
