### ISSUE TITLE
Support custom Anchor

### ISSUE THREAD

**Issue by Philippe91** [typora/typora-issues#1072]
I see that anchors are supported, and can be edited, if they already exist. Both at the call and target points. Good!
But why not having a friendly way to create them, as it is possible with URL links (for example).
At least, I did not find a way but switching to the raw text mode.

**Comment by leter** [comment]
hi, I use there code did not work in version 0.9.33
```
## Header 1

this is a [link](#header-1) to "Header 1"
```

can  you try it?

**Comment by abnerlee** [comment]
@leter 
It is working in my test. Please use ctrl+click for open hyperlink. And try update Typora to latest version

**Comment by leter** [comment]
@abnerlee  thanks, I have figured out the problem, the cause is version too lower.

**Comment by abnerlee** [comment]
Now `<a name='anchor'></a>` can be used as custom anchor
