### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by jodumont** [typora/typora-issues#1075]
Hi;
I tried your apps on Mac and it's do the job I need.

Now I try to install it on my Linux and it's not working.

1st at this page : https://typora.io/#linux
you have a typo  >> or, download **bonary** file x64 x86 ... 
2nd on the same page the instruction diff than these one : http://support.typora.io/Typora-on-Linux/

So, I know I'm using a derived of Debian which make it harder to use PPA but usually I point to artful, zesty or xenial and I don't have issue.

so basically I imported you're key from ubuntu, this is work fine
then when I try to add the repository it result on something like
deb http://ppa.launchpad.net///typora.io ./linux//ubuntu artful main

so wondering why you're project seems don't exist on https://launchpad.net/typora.io
after I tried different variation of this source list and sadly all of them respond 403 Forbidden like if you're project was really not on launchpad.

deb http://ppa.launchpad.net/typora.io ./linux/ubuntu artful main
deb http://ppa.launchpad.net/typora.io ubuntu zesty main
deb http://ppa.launchpad.net///typora.io ./linux/ubuntu zesty main
deb http://ppa.launchpad.net///typora.io ubuntu zesty main
deb http://ppa.launchpad.net///typora.io ./linux//ubuntu xenial main 

**So my question is:**
it is possible to have a plain typora.list file ?

Regards!

Jonathan

**Comment by abnerlee** [comment]
> you have a typo >> or, download bonary file x64 x86 ...

Thanks we will fix the typo.

> so wondering why you're project seems don't exist on https://launchpad.net/typora.io

We do not put Typora into launchpad since typora is not open sourced.

You could follow http://support.typora.io/Typora-on-Linux/ for installation. Debian is supported, you could use apt-get for installation
