### ISSUE TITLE
Link Reference does not present itself as clickable

### ISSUE THREAD

**Issue by mrdanbrooks** [typora/typora-issues#1076]
```
[InLine Link](http://www.google.com)
[Reference Link][Google]

[Google]: http://www.google.com
```
I would expect both of these links to present me with the option to "Open Link", but only the inline style link currently does this.

**Comment by GandalfSaxe** [comment]
You can always Cmd+Click all all types of links to open them.

I don't see how they differ. How do you get an "Open link" option with the inline link style?

**Comment by abnerlee** [comment]
> I would expect both of these links to present me with the option to "Open Link"

Do you mean there's no "Open Link" option in context menu for link reference?

----
You could use Cmd+Click for workaround

**Comment by abnerlee** [comment]
should be fixed already
