### ISSUE TITLE
Bug: All undo history is deleted when toggling "Source Code Mode"

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1079]
All undo history is gone when toggling View->Source Code Mode.

**Comment by abnerlee** [comment]
"Source Code Mode" is designed for temporary modification, it does not contain undo recorded in hybrid mode.  It is also very hard to support since source code moed does not maintain any AST like the hybrid mode do.

**Comment by GandalfSaxe** [comment]
Ah yes, I mistakenly thought that the undo history was gone if you switch to "Source Code Mode" and then back, but it's actually preserved. In fact it seems like both modes simply have their own undo history, except "Source Code Mode" history is lost if you switch back and forth.

As long as you know not to work in source code mode more tha "quickly in and out", then it's no problem.
