### ISSUE TITLE
Non-breaking space only after two spaces

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#108]
Still issues at getting a nbsp character. It seems that it only works in pairs; only the second nbsp counts, as indicated by `·` in the following:

> 1x space
> 2x ·space
> 3x · space
> 4x · ·space

This is done by hitting `alt+space` a number of times (in OSX) and the text in Typora is then copied to TextMate where I can see the hidden characters.

**Comment by waahto** [comment]
...actually, it does this when the user hits the space bar normally, not even using the modifier keys. So this isn't related to the fix I though it was (in 0.9.9.0);
> 7. Fix a bug that typora will eat and replace non-breaking space.

**Comment by abnerlee** [comment]
Could you try input some whitespace, the switch to source code mode and copy to TextMate?

Or input some whitespace, save file and the open with TextMate, would nbps still be there?

**Comment by waahto** [comment]
No luck there. Just to be clear, the preferred behaviour would be to take `alt+space` and just sticking it as  a [unicode character](http://www.fileformat.info/info/unicode/char/00a0/index.htm) in the file.

**Comment by abnerlee** [comment]
> ...actually, it does this when the user hits the space bar normally, not even using the modifier keys. So this isn't related to the fix I though it was (in 0.9.9.0);

Do you mean if user hit space bar normally twice, the second white space will become nbps? 

Actually, I tested in my local, but nbps can be input and preserved well.

**Comment by abnerlee** [comment]
Hi, Could you check this?

1. check "Enable Debugging" from help menu
2. right click on writing area and click "Inspect Element" from context menu, which will pop up a dev tool.
3. In the "Elements" tab of the dev tool, click the dom `div#write` and in the right side, select "styles", and check if the css for `#write`. the `white-space` property should be `pre-wrap`

If it is not `pre-wrap`, then `nbps` or `\t` is not correctly support now~ Sorry for that

**Comment by abnerlee** [comment]
in HTML, `nbps` represents normal white space, Non-breaking space is not supported. So, it will be hard for us to support Non-breaking space since Typora and markdown is HTML based
