### ISSUE TITLE
image cannot be in center in html/pdf

### ISSUE THREAD

**Issue by hgt312** [typora/typora-issues#1080]
Windows 64 bit version 0.9.38

**Comment by abnerlee** [comment]
`<center>![img](https://www.computerhope.com/issues/pictures/html.jpg)</center>`

**Comment by hgt312** [comment]
is this a bug？

**Comment by abnerlee** [comment]
No, you could use `<center>![img](https://www.computerhope.com/issues/pictures/html.jpg)</center>` to center image in exported HTML/PDF

**Comment by vassudanagunta** [comment]
@hgt312 Why did you think this might be a bug? I'm curious from a UX and user expectations design perspective.

**Comment by hgt312** [comment]
@vassudanagunta I think it is a bug. In editor, it is in center, so in pdf/html, it should be in center,too. 
And it is obvious that in center is better and more beautiful.

**Comment by abnerlee** [comment]
> In editor, it is in center, so in pdf/html, it should be in center,too.

In this case, it is a bug, we will check this.
