### ISSUE TITLE
Quoting code leads to code syntax highlighting for the remainder of the file in the source code

### ISSUE THREAD

**Issue by Eisbrenner** [typora/typora-issues#1082]
Hej there!

After adding a quoted code, i.e. 

```
> ```
> some code
> ```
```

the syntax highlighting for Typora is messed up when viewing the source code. Everything after the initial "```" is displayed as if it were code. Note that the normal/rendered view is perfectly fine.

General info
Typora: v1.7.9
OS: Ubuntu 16.04

Best,
Ezra

Edit: It seems I have the same behavior with Vim, so Typora may use some system highlighting which is broken for me?

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/314

**Comment by abnerlee** [comment]
> Edit: It seems I have the same behavior with Vim, so Typora may use some system highlighting which is broken for me?

We do not use system highlighting, but syntax highlight in source code mode and vim is provided by 3rd party lib, then may contain same mirror bugs like this
