### ISSUE TITLE
fail to update in China

### ISSUE THREAD

**Issue by exitNA** [typora/typora-issues#1083]
hi, I fail to update in China, even can't visit the https://typora.io/ website, any one who can help me, thanks

**Comment by abnerlee** [comment]
It's off the topic.

**Comment by abnerlee** [comment]
and I tested in http://ce.cloud.360.cn/task it is not blocked in most cities in China

**Comment by exitNA** [comment]
yes, i have tried  http://typora.io, it is also not working.

**Comment by abnerlee** [comment]
try set DNS to 8.8.8.8?
