### ISSUE TITLE
Files in the opened folder disappear after renaming. 

### ISSUE THREAD

**Issue by divanodestiny** [typora/typora-issues#1084]
When i open a folder and rename a `.md` file,  it can't be seen in the side bar until i re-open the app.

**Comment by abnerlee** [comment]
what's the file extension, Typora will only list markdown files.

**Comment by divanodestiny** [comment]
e... the file has no extension. it seems that the file is special. it can be recognize by preview and the file is listed while i just open the folder with Typora.
