### ISSUE TITLE
Ctrl+Clicking an internal link does not work in Source Code Mode. 

### ISSUE THREAD

**Issue by dillonreese** [typora/typora-issues#1085]
Ctrl+Clicking an internal link while Source Code mode is enabled will not follow the internal link. Disabling Source Code mode allows the Internal Link to function correctly. 

Syntax used for internal link: `[text to display](#link-location)`

**Comment by abnerlee** [comment]
source code mode is designed for only temp modification, so open link function is not provided in source code mode.
