### ISSUE TITLE
 bold font failed on Gothic theme in Chinese.

### ISSUE THREAD

**Issue by livc** [typora/typora-issues#1086]
sentence: 流通性与收益率呈典型的\*\*负相关\*\*。\*\*23汉字3\*\* ，汉字。

fail in Gothic theme.
<img width="431" alt="screen shot" src="https://user-images.githubusercontent.com/11692045/33792928-4869ab9e-dce8-11e7-8ae9-5d4f2017a7de.png">

work in GitHub theme.
<img width="410" alt="screen shot 1" src="https://user-images.githubusercontent.com/11692045/33792934-633b04ea-dce8-11e7-8e71-6b8e71e20ddf.png">

macos 10.13.2 typora Version 0.9.9.10.9 (0.9.9.10.9)

**Comment by abnerlee** [comment]
Fixed in new release.

**Comment by livc** [comment]
Hi, I think this bug isn't fixed in 0.9.9.11.2 ?

**Comment by livc** [comment]
@abnerlee Could you pls check that?

**Comment by abnerlee** [comment]
fixed in new release
