### ISSUE TITLE
Export to PDF produces a flat table of contents

### ISSUE THREAD

**Issue by patmaddox** [typora/typora-issues#1089]
OS X 10.10.5, Typora 0.9.9.10.9

Add a `[TOC]` tag and export as PDF. Open in Preview.app and View->Table of Contents.

**Expected:** The table of contents are nested to match the nested list produced by `[TOC]`.
**Actual:** The table of contents is a flat list.

![typora-toc-bug](https://user-images.githubusercontent.com/1111/33801403-a78f852e-dd17-11e7-81c7-bbe659fbdd38.png)

**Comment by abnerlee** [comment]
Outline in PDF use a tree-like model. Your TOC cannot be exported to outline in PDF correctly. 

"Source Code" and "Images and tables" are children of "Title of Article", which should be in same level, but they are not in same level, so we cannot "nest" them in PDF correctly.

**Comment by abnerlee** [comment]
Use follow 
```
# T
## S
## I
### I
### T
## F
```

should work when export

**Comment by patmaddox** [comment]
Ah, thank you! Is there any documentation on styling / configuring the Table of Contents? In particular, I would like it to exclude the top-level H1 ("Title of the Article"), and number each subheading:

```
1 Source code
2 Images and tables
   2.1 Images
   2.2 Tables
3 Final section
```

**Comment by abnerlee** [comment]
You could follow http://support.typora.io/Auto-Numbering/ (see its last line)

And add 

```css
.md-toc-h1 {display:none}
```

to hide the H1
