### ISSUE TITLE
code block default fold behavior/setting

### ISSUE THREAD

**Issue by fzh890523** [typora/typora-issues#1090]
Hi:

When I'm using markdown to write post with many code blocks, I get annoyed by the blocks which make the actual content difficult to read.
I wanna know whether typora can provide a global setting indicating that the default behavior of code blocks is folding or unfolding.  And if that can be specified per code block using a grammar like  "```java:folding" it will be more appreciated.

Thank you!

**Comment by fzh890523** [comment]
In order to be compatible with standard markdown grammar, maybe the style below is better:
```java
# typora: folding

class A {
}
```

**Comment by abnerlee** [comment]
For compatible, I think following will be better
~~~
```java {.folding}
class A {
}
```
~~~

since `#` will be rendered as comment or headings, depends on the target language.

**Comment by triptec** [comment]
I'm also looking for a way to fold snippets, writing technical propositions with a lot of json payloads makes it a pain to read =(

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/499
