### ISSUE TITLE
UI lags when changing the typora window size

### ISSUE THREAD

**Issue by siyuanxu** [typora/typora-issues#1093]
Great markdown editor, but I found something anoying with recent release.
When I change the typora window size, the action brings signaficante UI lag.
I have recorded a gif to show the ui lag, and this happens every time I try to change the window size

![typora-ui-lag](https://user-images.githubusercontent.com/28590841/33867751-be1693c2-df39-11e7-8728-07d0807d58dc.gif)

typora version 0.9.38(beta)
windows 10 pro version 1709

**Comment by abnerlee** [comment]
Closing this since this can be merged into other performance improvement issue.
