### ISSUE TITLE
Pandoc newer version gives worse conversion

### ISSUE THREAD

**Issue by wujastyk** [typora/typora-issues#1094]
I'm using Linux Mint 18.3, Cinnamon version.
The standard Debian repository version of Pandoc is 1.16.02.  Importing a docx file containing open- and close- quotes preserves the curly quotes (and correctly exports them to LaTeX).  E.g., docx-md-tex:  “triple salt” ->“triple salt”  -> ``triple salt''. 

I tried updating Pandoc to the latest version, 2.0.4.  Typora's import now produced vertical quotes, without left-ness and right-ness: "triple-salt".  Exporting from within Typora produces the same non-curly quotes.

But making a LaTeX file using Pandoc 2.0.4 from the command-line, independently of Typora, does the right things.     Also, running Pandoc 2.0.4 externally on Typora's saved non-curly .md file does the right thing, producing curly quotes in the LaTeX (unexpectedly).

Other infelicities:
Input docx: en dash
Typora with 1.16.02: -- , exports to LaTeX as --
Typora with 2.0.4: -- , exports to LaTeX as -\\/-

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1451
