### ISSUE TITLE
Export Styles

### ISSUE THREAD

**Issue by robmuh** [typora/typora-issues#1099]
I could swear that the export once embedded all the style information into the page rather than including these href links (which obviously do not transport with the file).

![screen shot 2017-12-13 at 10 49 14 pm](https://user-images.githubusercontent.com/3749067/33974749-1fa8003e-e058-11e7-9c2a-2bd58b4df3c1.png)

As it stands I have to export without styles and add my own style sheet or opt for PDF. Did something change?

**Comment by abnerlee** [comment]
It's a newly introduced bug, we will fix it asap

**Comment by abnerlee** [comment]
fixed in new updates.

**Comment by robmuh** [comment]
![screen shot 2017-12-14 at 9 01 59 am](https://user-images.githubusercontent.com/3749067/33995928-7c0436b8-e0ad-11e7-8244-13990a89d0ee.png)

Newer than this?

**Comment by abnerlee** [comment]
Yes
