### ISSUE TITLE
Save fails on webdav

### ISSUE THREAD

**Issue by gingerlilys** [typora/typora-issues#1100]
OS : Debian 9
Typora : 0.9.38

I tried to use typora to edit my .md files on my nextcloud server via webdav : 
*  *create new file* and then *save as* works
* *save as* works
* *save* fails : `Save File Failed!
Error: ENOTSUP: operation not supported on socket, open '/run/user/1000/gvfs/dav:host=cloud.owncube.com,ssl=true,user=elisabeth,prefix=%2Fremote.php%2Fwebdav/Notes/FonePad Unlock.md'`

If I edit my notes with another app (eg. Gedit) it works perfectly (new, save as, save)

**Comment by abnerlee** [comment]
merge to https://github.com/typora/typora-issues/issues/1058

PS: Could you confirm it in v0.9.41?

**Comment by gingerlilys** [comment]
Yes, the bug is still in v0.9.41.
