### ISSUE TITLE
Cannot render < kbd> < /kbd> tag.

### ISSUE THREAD

**Issue by wangwenx190** [typora/typora-issues#1101]
Typora cannot render < kbd> < /kbd> (I am sorry I have to add one space in front of "kbd" and "/kbd" otherwise it will be recognized as a keyboard key) tag while GitHub the website can.
Win10(16299.125) + Typora 0.9.40(beta)

Typora:
![typora](https://user-images.githubusercontent.com/17877450/33983781-5f1fda6e-e0f0-11e7-8375-fe2776cebda0.PNG)
GitHub:
![github](https://user-images.githubusercontent.com/17877450/33983791-65f62b4a-e0f0-11e7-9288-5b77e65dc2f0.PNG)

**Comment by abnerlee** [comment]
merge with https://github.com/typora/typora-issues/issues/705
