### ISSUE TITLE
Split view could not apply 

### ISSUE THREAD

**Issue by 0dd** [typora/typora-issues#1102]
Press and hold the green button did not apply the split view

**Comment by 0dd** [comment]
mac OS 10.13.2 (17C88)
Typora Version 0.9.9.11.1 (0.9.9.11.1)

**Comment by abnerlee** [comment]
fixed in v0.9.9.12

**Comment by Foadsf** [comment]
Does Typora have a split screen with live preview like [Qilin editor](https://github.com/qilin-editor/qilin-app)? Sometimes it is very useful.
