### ISSUE TITLE
Link in auto-update notes not clickable

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#1103]
When I click the "strict mode" link in the attached screenshot repeatedly, nothing happened. I'm not sure whether this is standard in auto-update notes, or whether it's something particular about Typora's handling of auto-update. I can't remember other times when such notes in other apps had working links.

Right-clicking the link I was able to copy http://support.typora.io/Strict-Mode/ and paste it into my browser, but one would expect to be able to click the link directly.

<img width="264" alt="screen shot 2017-12-14 at 8 55 06 am" src="https://user-images.githubusercontent.com/1819485/33995712-cfd86a12-e0ac-11e7-8342-ffb0269eb69d.png">

**Comment by abnerlee** [comment]
It is handled by https://sparkle-project.org/ 

Maybe link is not supported.
