### ISSUE TITLE
MathJax equations are rendered incorrectly when exported to docx file

### ISSUE THREAD

**Issue by ruiyuanlu** [typora/typora-issues#1104]
There are 2 problems I've met when I tried to export md file to docx file.
1. The MathJax equations are just output as plain strings if they are surrounded by label <u></u>, for example:
<u>I want to output a equations here $\chi=d \times t$ </u>
typora will underline and output the string above without render the equation inside the label.

2. The MathJax equations have no numbering.

typora: 0.9.38(beta)
sys: Win 10 professional

**Comment by abnerlee** [comment]
pandoc version? Is this caused by https://github.com/typora/typora-issues/issues/1094 ?

**Comment by ruiyuanlu** [comment]
The version of pandoc is 2.0.4.

**Comment by abnerlee** [comment]
for $\chi=d \times t$ 

This is caused by https://github.com/jgm/pandoc/issues/4251

The MathJax equations have no numbering.

> The MathJax equations have no numbering.

duplicate with https://github.com/typora/typora-issues/issues/696
