### ISSUE TITLE
Add an option for the frenquency of autosaving

### ISSUE THREAD

**Issue by Sweetyshadow** [typora/typora-issues#1105]
Today I write my homework for 2 hours, but I shut down my computer without saving it. When I switch on my computer again, I found my homework not saved. So I think you can add an option for users to determine how often a document should be autosaved.

**Comment by abnerlee** [comment]
Please refer http://support.typora.io/Auto-Save/
http://support.typora.io/Version-Control/

Auto-save requires you to save file on disk or open existing file first, or else typora will not know to where it should write content to, it still Typora will save your content on the backup file.
