### ISSUE TITLE
Support nomnoml for diagrams (see nomnoml.com)

### ISSUE THREAD

**Issue by 42sol-eu** [typora/typora-issues#1106]
Like mermaid nomnoml is a textbased diagramming processor.
I like its very sleekness and the great design.

it is javascript based and should not be hard to integrate.

- sourcecode: https://github.com/skanaar/nomnoml
- electron.io: integration: https://github.com/dqisme/nomnoml-app

integration would be like the mermaid module (code fence with nomnoml)

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1138
