### ISSUE TITLE
Where do I set the desired font? None of the json or css files seem to work.

### ISSUE THREAD

**Issue by JoeUX** [typora/typora-issues#1108]
**Windows 10 Pro 1709, 64-bit
Typora 0.9.41**

I can't get Typora to use my preferred font. The docs say to edit `base.user.css`, but I can't find that file anywhere in the `AppData/Roaming/Typora` or the `Program Files/Typora` directories. Is that file name obsolete now?

I edited `night.css` both in the AppData and Program Files directories (it appears in both). This is my syntax:

```CSS
body {
  font-family: "Noto Serif";
}
```
In some cases, I saw Raleway in the CSS, and replaced it with Noto Serif.

I also edited the json config files with this font, and still nothing changed.

(I have Noto Serif installed locally on my machine. It's a Google font.)

**Comment by abnerlee** [comment]
`base.user.css` should be put under "theme folder", which can be opened from preference panel
