### ISSUE TITLE
sometimes strange gap between letters after export to pdf

### ISSUE THREAD

**Issue by rflgrt** [typora/typora-issues#1109]
When using the github theme in some instances there occurs a strange gap between letters after export to pdf:

```
### Vergleichsoperatoren
```
results in an unexpected gap between the letters r and a
![auswahl_002](https://user-images.githubusercontent.com/22128842/34079262-98cc19a8-e32a-11e7-950e-8b2b58b1044f.png)

Typora for Linux: V 0.9.40
running on Ubuntu Xenial 16.04 (LTS)

**Comment by abnerlee** [comment]
Use github theme, right?

**Comment by rflgrt** [comment]
Thats right. It only occurs when using the github theme and only when exporting to pdf

**Comment by abnerlee** [comment]
Seems good on Windows.

@rflgrt If you export to HTML first, and then open & print using Chrome, will this happen?
