### ISSUE TITLE
there is something wrong in win10

### ISSUE THREAD

**Issue by youtsea** [typora/typora-issues#1110]
when open the app, some area is black...

![bug](https://user-images.githubusercontent.com/9941834/34079696-8fe1624c-e36d-11e7-8b48-7f01a50f98a6.PNG)

**Comment by abnerlee** [comment]
Is it same with https://github.com/electron/electron/issues/10863 ?

Have you try reboot the PC, reinstall Typora," Installing [slightly newer WHQL driver from NVIDIA](http://www.nvidia.com/download/driverResults.aspx/112591/en-us) ", " Run as Administrator" asthe post suggest?

**Comment by youtsea** [comment]
@abnerlee After installing **342.01-quadro-desktop-notebook-win10-64bit-international-whql.exe**, it's working.Thank you.
