### ISSUE TITLE
dual screen issue

### ISSUE THREAD

**Issue by jacquen** [typora/typora-issues#1112]
I had laptop with external monitor, when I closed my Typora editor (not in maximum mode) in external monitor and disconnect from external scree, I couldn't open it again on my laptop screen, it always go to external screen. 
I think this is bug of this software. please help

**Comment by abnerlee** [comment]
What's your OS/Typora version ?

**Comment by jacquen** [comment]
WIN 7

**Comment by abnerlee** [comment]
Typora version ?

**Comment by jacquen** [comment]
0.9.41(beta)

**Comment by jacquen** [comment]
Any update?

**Comment by abnerlee** [comment]
relates https://github.com/mawie81/electron-window-state/issues/17
https://github.com/mawie81/electron-window-state/issues/1

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/938
