### ISSUE TITLE
provide option to not number items in ordered lists

### ISSUE THREAD

**Issue by olets** [typora/typora-issues#1114]
Markdown lets you write ordered lists with all `1.`s

```
1. Outputs as "1."
1. Outputs as "2."
```

If you write that in Typora's md view and then switch to the tend view, the source gets rewritten to match what you see rendered

```
1. …
2. …
```

I would really love to be able to turn that off, and keep the source the way I wrote it

**Comment by abnerlee** [comment]
Fixed in new release already.

duplicate with https://github.com/typora/typora-issues/issues/1188
