### ISSUE TITLE
Show arrows like -> or => as Unicode (e.g. → or ⇨)

### ISSUE THREAD

**Issue by brmdv** [typora/typora-issues#1115]
I like to use Typora for my note-taking. While making notes, I often use pseudo-arrow symbols, like `-->`, but they look out of place in Typora's otherwise slick-looking layout. It would be nice if they were displayed as their [Unicode alternatives](https://unicode-table.com/en/sets/arrows-symbols/) in normal mode. 

I am aware that it is possible to insert arrows using the emoji functionality, e.g. `:arrow_right:`  becomes :arrow_right: , but then the source code is not easy-to-read anymore, which is an important goal of Markdown, and the reason I like it for my cross-platform note-taking.

**Comment by abnerlee** [comment]
I will merge this into https://github.com/typora/typora-issues/issues/291

**Comment by LuigiTheHunter** [comment]
I like the idea!
