### ISSUE TITLE
Add support for base64 encoded images

### ISSUE THREAD

**Issue by joejoe87577** [typora/typora-issues#1116]
The editor already displays base64 encoded images. But the UI does not have an option for this.

Markdown supports images with
`![Hello World](data:image/png;base64,xxx)`
It would be nice to enable this option for copy and pasting images into the md file. Or for embeding all images into the file.
This would make it easier to share the file for editing.

Thanks

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/88
