### ISSUE TITLE
Can not reload the change triggered by other editor.

### ISSUE THREAD

**Issue by yunnysunny** [typora/typora-issues#1117]
When the makrdown opened by typora was modified by other editor, typora could not reload the change. And the worse is that , typora make the current edited document read only.

**Comment by abnerlee** [comment]
This should already be supported -> https://github.com/typora/typora-issues/issues/165

Could you tell me your OS/Typora version? Did you put your file on local disk or net drive? Which external editor did you use to modify the file?

**Comment by yunnysunny** [comment]
I use the version of 0.9.38 on Win10.
When some modification triggered by other editor( I do a git revert command), the typora will show a dialog to let you reload the change. But after the reload typora treat the current document as unsaved. Then if another change from other editor triggers( I do a git pull command), it will  the dialog to tell you save the current change, but in fact, there is no modification made by typora and the document is read only now , you just can not save it.

![save](https://user-images.githubusercontent.com/734818/34316748-bf0d3c80-e7d7-11e7-8545-9ea1674f1dcb.png)

**Comment by abnerlee** [comment]
> there is no modification made by typora and the document is read only now , you just can not save it.

I'm not quite understand about this since Typora does not support readonly. So what will happen if you click save in Typora? And when will the dialog above popup? When you trying to close Typora?

**Comment by yunnysunny** [comment]
Typora may deal with the changes from other editors. But I wonder if you have considered the changes made by git command. When you run `git pull` and there are some changes form remote repository , then the dialog will show.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/894
