### ISSUE TITLE
sudo apt-get update W: Conflicting distribution https://typora.io:443 linux/ InRelease (expected linux/ but got )

### ISSUE THREAD

**Issue by stepaniuk** [typora/typora-issues#1118]
Ubuntu 17.10 x64

`$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE`
`$ sudo add-apt-repository 'deb http://typora.io linux/'`
`$ sudo apt-get update`

Get:7 https://typora.io:443 linux/ InRelease [758 B]                           
Get:23 http://security.ubuntu.com/ubuntu artful-security/main amd64 DEP-11 Metadata [204 B]
Get:24 http://security.ubuntu.com/ubuntu artful-security/universe amd64 DEP-11 Metadata [10.2 kB]
Get:25 https://typora.io:443 linux/ Packages [3,582 B]             
Fetched 877 kB in 2s (313 kB/s)
Reading package lists... Done
W: Conflicting distribution: https://typora.io:443 linux/ InRelease (expected linux/ but got )

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/706

Now all warning are gone on my ubuntu, so I cannot confirm this now.
