### ISSUE TITLE
CPU usage issue

### ISSUE THREAD

**Issue by vreality64** [typora/typora-issues#1119]
### situation
![typora cpu usage issue](https://user-images.githubusercontent.com/886706/34286479-415610d6-e724-11e7-998c-4b47060ed35e.png)
- when open typora, it use cpu resources upto ~90%
- It occurs from program execution to termination.

### env
<img src="https://user-images.githubusercontent.com/886706/34286546-a7a2a78c-e724-11e7-8697-e164d9154260.png" width="50%">

**Comment by abnerlee** [comment]
merge to https://github.com/typora/typora-issues/issues/68 and https://github.com/typora/typora-issues/issues/58
