### ISSUE TITLE
File content disappeared after saving (Mac OS)

### ISSUE THREAD

**Issue by supersuraccoon** [typora/typora-issues#112]
### Enviroment
- Mac OS => 10.11.1
- typora => 0.9.9.0

### What I did
I'm writing a long article and then I found something unusual:

- The outline only shows part of the whole article
- The scroll action become little bit slow

So I saved the article and closed typora. (PS. I always save the file from time to time while writing)

### The trouble
After saving the file I found the size of it decreases from **over 50KB to 5KB**!!!

Then I tried to open it in typora and I found the **almost 85% of the content are gone** !!!

BTW, the part of the content still alive are the part that shown in the `outline view` before I save the file.

Not sure what I happened but I think I need to report this.

I love typora but this happening really gave me a big blow.

Hope you guys can looking into this, thanks. (If you need the file, I can send it to you.)

**Comment by abnerlee** [comment]
Sorry for this bug.

Could you send the file to <hi@typora.io>, and  maybe the file of the previous version before last saving from TimeMachine

**Comment by abnerlee** [comment]
> The outline only shows part of the whole article

I think this is related to the bug.
And maybe it is cased by some modification, so if you would recall some of your modifications and found a way to re-produce it, that will be much helpful.

Again, sorry for that~

**Comment by supersuraccoon** [comment]
After trying several times I am now able to re-produce 100%.

I've attached a video on how to do it along with a sample markdown file here.

Hope this can be fixed ASAP ...

( PS. I did not enable the TimeMachine for my Mac so ...... )

[typora_issues_112.zip](https://github.com/typora/typora-issues/files/204149/typora_issues_112.zip)

**Comment by abnerlee** [comment]
Thanks for your report,
Fixed in new version.
