### ISSUE TITLE
Ctrl+B / Ctrl+I twice in multiple cells (table)

### ISSUE THREAD

**Issue by gustavosotnas** [typora/typora-issues#1120]
This GIF below shows a unexpected behavior when I press Ctrl+B / Ctrl+I twice with more than one cell selected.

![screenshot_1](https://user-images.githubusercontent.com/9777954/34304134-8a423360-e71f-11e7-931b-6460868712e2.gif)

**Comment by abnerlee** [comment]
fixed in v0.9.42
