### ISSUE TITLE
typora crashed and cannot be used normally any more.

### ISSUE THREAD

**Issue by Michael-Xuke** [typora/typora-issues#1123]
hey,guys.I'm a typora user from China.once my typora was crashed, which caused my computer crashed too.after restarting my computer,I found typora was no more functional.I could not even open it .the window of typora never showed up.just like picture below.you can see there is a typora window opened,but I just can not open it ,let alone use it to type something.I reinstall it many times ,but it still don't work. I even tried to download the newest version from the typora official website and installed it ,but the issue is still on.
does anyone meet the same issue like me ?
can anyone help me out to solve issue? thanks

![image](https://user-images.githubusercontent.com/32660828/34331403-709590b2-e961-11e7-80b9-59a5589531e9.png)

**Comment by abnerlee** [comment]
I have replied in email, so I will close it here. 
may relates https://github.com/typora/typora-issues/issues/938
