### ISSUE TITLE
linke refrence can  not be displayed in the html (export to html)

### ISSUE THREAD

**Issue by leter** [typora/typora-issues#1125]
**before export in md**

![tim 20171226105432](https://user-images.githubusercontent.com/13078495/34345614-53d7c772-ea2b-11e7-8d59-1c204d41496c.png)

**after export in html**
![tim 20171226105655](https://user-images.githubusercontent.com/13078495/34345675-bc979e68-ea2b-11e7-9389-c7efd6b5cd19.png)

**Comment by abnerlee** [comment]
Link reference is not for display. You could try in Github: 

```
This is text

[this is link reference]: http://github.com "title"
```

is rendered as

This is text

[this is link reference]: http://github.com "title"
