### ISSUE TITLE
Typora key bind not working (minimal example)

### ISSUE THREAD

**Issue by johntiger1** [typora/typora-issues#1126]
See photo. Running on Windows 10. 
![typora key bind bug](https://user-images.githubusercontent.com/14852840/34346665-1b401f3a-e9c8-11e7-84be-7bfeae513d3d.png)

**Comment by abnerlee** [comment]
should be `Ctrl+K`

**Comment by johntiger1** [comment]
Thanks, I actually tried that before and it didn't work, but now it does...
