### ISSUE TITLE
Multiple {align} in {array}: "Erroneous nesting of equation structures"

### ISSUE THREAD

**Issue by ruiyuanlu** [typora/typora-issues#1128]
Hi there, I want to use the following code to format my equations in `array` block.
```latex 
$$
\begin{array}{c|l}
steps&\text{functions} \\ \hline
   1&\begin{align} 
    s(x) &= (x+1)^2 \\
          &= x^2+2x+1
    \end{align} \\ \hline
\end{array}
$$
```
The output is:
![image](https://user-images.githubusercontent.com/16774189/34389674-0ea16e50-eb76-11e7-9535-61728aeab3ef.png)

If I just use the `align` block once, everything looks fine, but I got the error message **"Erroneous nesting of equation structures"** when I tried to use more `align` blocks to format multiple equations in one `array`  block. 

All the code is shown as follows:
```latex
$$
\begin{array}{c|l}
steps&\text{functions} \\ \hline
   1&\begin{align} 
    s(x) &= (x+1)^2 \\
          &= x^2+2x+1
    \end{align} \\ \hline

2& \text{Let } s(x)' \text{ denote the derivative of } s(x): \\
   &\begin{align} 
    s(x)' &= ((x+1)^2)' \\
           &= 2x+2
    \end{align} \\ \hline
\end{array}
$$
```
The error message is:
![image](https://user-images.githubusercontent.com/16774189/34389424-7f695546-eb74-11e7-9f16-2a2d63340679.png)

I expected the output of 2nd `align` block to be:
![image](https://user-images.githubusercontent.com/16774189/34389810-d0f2678e-eb76-11e7-8532-79338bd9ee58.png)

What can I do?
Version info: typora-0.9.41(beta); sys-win 10 professional; pandoc-2.0.5;

**Comment by abnerlee** [comment]
I tried in https://www.mathjax.org/#demo

```
$$
\begin{array}{c|l}
steps&\text{functions} \\ \hline
   1&\begin{align} 
    s(x) &= (x+1)^2 \\
          &= x^2+2x+1
    \end{align} \\ \hline
\end{array}
$$
```
This works


```
$$
\begin{array}{c|l}
steps&\text{functions} \\ \hline
   1&\begin{align} 
    s(x) &= (x+1)^2 \\
          &= x^2+2x+1
    \end{align} \\ \hline

2& \text{Let } s(x)' \text{ denote the derivative of } s(x): \\
   &\begin{align} 
    s(x)' &= ((x+1)^2)' \\
           &= 2x+2
    \end{align} \\ \hline
\end{array}
$$
```

This does not work.

So it is either not supported by mathjax, or there are some error on the tex code.

I reported to mathJax -> https://github.com/mathjax/MathJax/issues/1892

**Comment by ruiyuanlu** [comment]
Thx very much. It helps a lot.
