### ISSUE TITLE
Backspace misbehaviour (and empty file typability)

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#113]
Type "this is a test" and start backspacing it. When you're down to "this is a t" the next keypress takes away the 't' and the preceding whitespace[1]. If you start deleting from the middle, but before a whitespace, the last deletion of the letter in the word also deletes the whitespace that is on the right side of the cursor[2]. This seems like a new bug in 0.9.9.x.

When you backspace the whole line (in my example), and delete the first character, the cursor moves one line up and what you type no longer appears in the program. Switching to source code mode and back or reopening the file fixes this.

```
[1]
   "this is a test"
-> "this is a t"
-> "this is a"  actual result
-> "this is a " wanted result

[2]
   "this is a test"
-> "this i a test"
-> "this a test"  actual result
-> "this  a test" wanted result
```

**Comment by abnerlee** [comment]
Still facing this bug?

It seems I cannot reproduce it on my Mac.

So, if you still met this bug, did you use any IME?

**Comment by waahto** [comment]
That's unexpected. I use Finnish keyboard but I just tried US international and generic English while restarting Typora in between. And yes, the bug persists. And to be clear, the double backspace issue is not fixable by reopening the file or other gimmicks.

**Comment by abnerlee** [comment]
Hi,

I got the problem.
I'm guessing you're using:

``` css
#write {
   white-space: initial;
}
```

or something else. But currently only `pre-wrap` is supported since typora haven't add logics to support whitespace under "wrapped" styles. Change it back to `pre-wrap` should solve the problem.
