### ISSUE TITLE
GitBook support.

### ISSUE THREAD

**Issue by Maxithi** [typora/typora-issues#1132]
I would love to see Typora support the [GitBook](https://github.com/GitbookIO/gitbook) structure. We have parts of the views with the Tree View and Outline View.

**Comment by abnerlee** [comment]
> I would love to see Typora support the GitBook structure

structure means data structure or UI  structure?

**Comment by Maxithi** [comment]
> structure means data structure or UI structure?

I mean displaying the sections like in the GitBook UI.

![GitBook](https://camo.githubusercontent.com/c1b6c55fca8e171120ce1fd73afcee699cc2a98f/68747470733a2f2f7261772e6769746875622e636f6d2f476974626f6f6b494f2f676974626f6f6b2f6d61737465722f707265766965772e706e67)

Typora is way more user-friendly than the GitBook Client. Their only advantage is that they have a view showing your book structure (and not directory structure).

**Comment by abnerlee** [comment]
List Files in sidebar is already supported in Typora
