### ISSUE TITLE
Proselint support

### ISSUE THREAD

**Issue by shreyasminocha** [typora/typora-issues#1133]
I would love to see support for the [proselint tool](//proselint.com). This feature could use the proselint cli tool. Would this be possible in the near future?

**Comment by abnerlee** [comment]
The website seems down (tested in https://www.uptrends.com/tools/uptime)

**Comment by abnerlee** [comment]
OK https://github.com/amperser/proselint is available.

**Comment by szepeviktor** [comment]
It is http://proselint.com/

**Comment by abnerlee** [comment]
merge into #1316
