### ISSUE TITLE
内联公式不支持分段函数

### ISSUE THREAD

**Issue by strongliu110** [typora/typora-issues#1136]
如下，采用公式块时支持分段函数，而内联公式不支持分段函数？
\[ f(n) =
  \begin{cases}
    n/2       & \quad \text{if } n \text{ is even}\\
    -(n+1)/2  & \quad \text{if } n \text{ is odd}
  \end{cases}
\]

**Comment by abnerlee** [comment]
Currently we do not support multiple lines of inline math.

Merge this into https://github.com/typora/typora-issues/issues/90
