### ISSUE TITLE
flowchart.js renders incomplete diagram

### ISSUE THREAD

**Issue by xuxiabb** [typora/typora-issues#1137]
![typora_bug](https://user-images.githubusercontent.com/7539234/34473380-d3980e96-efac-11e7-9283-580ce2b8623d.png)
![flowchartjs](https://user-images.githubusercontent.com/7539234/34473417-354f9e56-efad-11e7-8e7f-0b5ba4705a00.png)

```
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
e=>end

st->op->cond
cond(yes)->e
cond(no)->op
```

在Typora中只能显示部分图像，在flowchart.js网站中显示是正常的。
Windows 10 64位 Typora 0.9.41

**Comment by xuxiabb** [comment]
```
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
e=>end

st->op->cond
cond(yes)->e
cond(no)->op
```



在Typora中只能显示部分图像，在flowchart.js网站显示是正常的。
Windows 10 64位 Typora 0.9.41

**Comment by abnerlee** [comment]
我试了一下没能复现。能再具体说明一下吗？

比如拷贝flowchart内容到Typora后显示不全，还是打开已有文件时显示不全？

**Comment by xuxiabb** [comment]
无论是拷贝、打开都出现一样的错误。
我本机是Windows 10 64位，试了Typora 0.9.41 64位跟32位版，都出现一样的问题

**Comment by xuxiabb** [comment]
我试着添加了下参数，结果出现了这样的效果。
![snipaste_2018-01-02_12-13-43](https://user-images.githubusercontent.com/7539234/34474179-710c61fa-efb6-11e7-9580-31088b929827.png)
![snipaste_2018-01-02_12-13-58](https://user-images.githubusercontent.com/7539234/34474180-7149fa7e-efb6-11e7-8471-dc04ec8fea2c.png)

**Comment by abnerlee** [comment]
Confirmed, I can reproduce this error if I set line endings as CRLF in preference panel.

**Comment by abnerlee** [comment]
fixed in v0.9.42
