### ISSUE TITLE
nothing to see when open .md file with typora 

### ISSUE THREAD

**Issue by LjessonS** [typora/typora-issues#1139]
I'm a fans of typora, and now having been used typora for serveral months. But recently I don't know why I open my old xxx.md file with typora and wait for hours, it still shows me with a totally blank space, even the menu bar don't work. I tried to install or reinstall or restart my win10 system, it still doesn't work. I like typora, and hope the author to fix this bug. THX.

**Comment by abnerlee** [comment]
same with https://github.com/typora/typora-issues/issues/1110?

**Comment by LjessonS** [comment]
Sorry to late reply, I tried to install 342.01-quadro-desktop-notebook-win10-64bit-international-whql.exe mentioned in the link and add --disable-gpu argument, and after that also tried to update my windows system driver, but my computer still can't install it. I don't know what to do.

hope my computer configuration will give you some helpful information to fix this bug. Thank you very much! I really like typora.
Radeon 软件版本 - 17.12.1
Radeon 软件版本 - Adrenalin
Windows 版本 - Windows 10 (64 bit)
系统内存 - 16 GB
CPU 类型 - Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by abnerlee** [comment]
I see,

So only the mentioned md file cannot be opened, or all *.md files cannot be opened? If you just open Typora (without open any *.md files), does the menubar work?

If possible, could you send us the typora.log from C:\Users\{username}\AppData\Roaming\Typora?

If you try open C:\Users\{username}\AppData\Roaming\Typora, and then start Typora, will that work?

**Comment by LjessonS** [comment]
Thanks very very much for the quick reply! 

It's all *.md file cannot work(you can see just a whole blank space, menu bar can see, but can not use) when open with typora. Also, when just open Typora, menubar cannot work.

I don't know how to find your email address. forgive to just put it below:


INFO 2018-1-3 10:57:33  ------------------start------------------
INFO 2018-1-3 10:57:33  addRecentDocument
INFO 2018-1-3 10:57:33  D:\software\windows\Typora\resources\app\locales\zh-Hans.lproj\Menu.json
ERROR 2018-1-3 10:57:34  render process is killed? false
ERROR 2018-1-3 10:57:34  { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: [ 'file:///D:/software/windows/Typora/resources/app//window.html' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Object],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        'new-window': [Function],
        crashed: [Function],
        'render-view-deleted': [Function: listener] },
     _eventsCount: 18,
     _maxListeners: 0,
     browserWindowOptions: 
      { x: 976,
        y: 478,
        width: 797,
        height: 664,
        minWidth: 100,
        minHeight: 100,
        frame: true,
        disableAutoHideCursor: false,
        backgroundColor: '#FFFFFF',
        webPreferences: [Object],
        autoHideMenuBar: false,
        show: true,
        fullscreen: null } } }
INFO 2018-1-3 10:57:55  problem with request: connect ETIMEDOUT 172.217.25.14:80
INFO 2018-1-3 10:58:53  addRecentDocument
INFO 2018-1-3 10:58:57  addRecentDocument
ERROR 2018-1-3 10:58:58  render process is killed? false
ERROR 2018-1-3 10:58:58  { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: [ 'file:///D:/software/windows/Typora/resources/app//window.html' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Object],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        'new-window': [Function],
        crashed: [Function],
        'render-view-deleted': [Function: listener] },
     _eventsCount: 18,
     _maxListeners: 0,
     browserWindowOptions: 
      { x: 1006,
        y: 448,
        width: 797,
        height: 664,
        minWidth: 100,
        minHeight: 100,
        frame: true,
        disableAutoHideCursor: false,
        backgroundColor: '#FFFFFF',
        webPreferences: [Object],
        autoHideMenuBar: false,
        show: true,
        fullscreen: false } } }
INFO 2018-1-3 11:00:04  ------------------quiting------------------
INFO 2018-1-3 11:03:53  ------------------start------------------
INFO 2018-1-3 11:03:53  addRecentDocument
INFO 2018-1-3 11:03:53  D:\software\windows\Typora\resources\app\locales\zh-Hans.lproj\Menu.json
ERROR 2018-1-3 11:03:54  render process is killed? false
ERROR 2018-1-3 11:03:54  { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: [ 'file:///D:/software/windows/Typora/resources/app//window.html' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Object],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        'new-window': [Function],
        crashed: [Function],
        'render-view-deleted': [Function: listener] },
     _eventsCount: 18,
     _maxListeners: 0,
     browserWindowOptions: 
      { x: 976,
        y: 478,
        width: 797,
        height: 664,
        minWidth: 100,
        minHeight: 100,
        frame: true,
        disableAutoHideCursor: false,
        backgroundColor: '#FFFFFF',
        webPreferences: [Object],
        autoHideMenuBar: false,
        show: true,
        fullscreen: null } } }
INFO 2018-1-3 11:04:01  ------------------quiting------------------

**Comment by abnerlee** [comment]
I see, so will remove  C:\Users{username}\AppData\Roaming\Typora help?

> and now having been used typora for serveral months. But recently I don't know why I open my old xxx.md file with typora and wait for hours

So Typora was able to work, not now does not work right? What have you done before typora stop working? Update OS or Typora?

And have you try "Run as Administrator" as mentioned in https://github.com/electron/electron/issues/10863?

**Comment by LjessonS** [comment]
sorry to make you misunderstood my explanation. 

> and now having been used typora for serveral months. But recently I don't know why I open my old xxx.md file with typora and wait for hours

I mentioned it just to explain that open typora for hours can't make it work. It just leave a blank space even without mouse cursor and so can not write anything. Really sorry. I have tried "Run as Administrator" yet, and it also doesn't work. I think I have tried anything  I could do to make it work(download X32, X64, newest version, old version; delete typora registered list one by one). And it just not work any more.  

> What have you done before typora stop working? Update OS or Typora?

I think the first time when Typora not work(may be four weeks ago), was the time when it prompt me to update then I choose to lately update it. And then it became blank, can not edit, and also can not update. I don't know whether I updated OS or Typora. My OS cannot update now, and  I don't know why. Thank you for the kind reply.

**Comment by LjessonS** [comment]
I just came up with an idea that since I can not use typora on windows, I can still use it in my vmvare-ubuntu systems. ^_^

**Comment by abnerlee** [comment]
@LjessonS Are your situation same with https://github.com/electron/electron/issues/10863?
(Using Windows 10 16299.19 (Fall Creators Update), using NVIDIA drivers) ?

If so, then it maybe a Electron bug, we can fix after Electron updates its Chromium version

**Comment by LjessonS** [comment]
I'm don't quite understand the relation between Electron and typora. Is it a tool live in windows system to develop typora? If so, I think it might be. 
Now though it made a little trouble for me to use typora in Linux, I will always keep paying my attention to your next typora version. Thanks for your hard work.

**Comment by LjessonS** [comment]
@abnerlee I find you have update two versions for windows users, but this bug still not fixed. Menu bar comes back, but every one of it can not work, no response when clipped, and cursor is still disapeared.

Below is the typora.log file:

INFO 2018-2-11 09:10:49  overwriteThemeFolder
INFO 2018-2-11 09:10:49  cannot parse user config, use the default one
INFO 2018-2-11 09:10:49  ------------------start------------------
INFO 2018-2-11 09:10:49  C:\Program Files\Typora\resources\app\locales\zh-Hans.lproj\Menu.json
ERROR 2018-2-11 09:10:51  render process is killed? false
ERROR 2018-2-11 09:10:51  { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: [ 'file:///C:/Program%20Files/Typora/resources/app//window.html' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Object],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        'new-window': [Function],
        crashed: [Function],
        'render-view-deleted': [Function: listener] },
     _eventsCount: 18,
     _maxListeners: 0,
     browserWindowOptions: 
      { x: undefined,
        y: undefined,
        width: 800,
        height: 600,
        minWidth: 400,
        minHeight: 400,
        frame: true,
        disableAutoHideCursor: false,
        backgroundColor: undefined,
        webPreferences: [Object],
        autoHideMenuBar: undefined,
        show: true,
        fullscreen: null } } }
INFO 2018-2-11 09:11:12  problem with request: connect ETIMEDOUT 172.217.31.238:80
INFO 2018-2-11 09:11:46  window.File && (function (){document.body.classList.toggle("show-footer")})();

**Comment by LjessonS** [comment]
@abnerlee this bug has been fixed in my windows 10 system, thank you very very very much! I really like typora!!!

**Comment by pidada** [comment]
the same question: I have used typora for several months.but some days ago ,it suddenly cannot work and when I open the .md file ,it shows nothing.  

please do me a favor! it`s a agent thing

**Comment by pidada** [comment]
the same question: I have used typora for several months.but some days ago ,it suddenly cannot work and when I open the .md file ,it shows nothing.

please do me a favor! it`s a agent thing! My OS is mac air

**Comment by DutchPete** [comment]
@pidada : mac air is not an OS, it is a piece of hardware, a computer. I also use Typora on a MacBook Air, and the macOS  version is 10.14.6 Mojave. Incidentally, I have not encountered the file opening problem.

**Comment by abnerlee** [comment]
@pidada  same with #2972?

**Comment by TonyBarganski** [comment]
I'm having the same issue on Ubuntu 20.04 with Typora 0.11.13-1.

Log Extract:

INFO 10/20/2021, 10:16:24 AM  [Power] resume
INFO 10/20/2021, 10:16:26 AM  [RenderProcess 1][Log] [powerMonitor] resume
INFO 10/20/2021, 1:22:03 PM  got argv [typora /path/to/some/file.md] from secondary instance
INFO 10/20/2021, 1:22:03 PM  added recovery 5 null undefined (0)
INFO 10/20/2021, 1:22:03 PM  [focus] 5
INFO 10/20/2021, 1:22:03 PM  synced recovery
INFO 10/20/2021, 1:22:03 PM  secondary instance would exit
INFO 10/20/2021, 1:22:04 PM  handle document.loadInitData
INFO 10/20/2021, 1:22:04 PM  [RenderProcess 6][Log] getContent
INFO 10/20/2021, 1:22:04 PM  added recovery 5 undefined undefined (0)
INFO 10/20/2021, 1:22:04 PM  synced recovery
INFO 10/20/2021, 1:22:05 PM  [RenderProcess 6][Log] onBecomeActive
INFO 10/20/2021, 1:22:05 PM  [RenderProcess 6][Log] File.activeWindow = true

**Comment by TonyBarganski** [comment]
Installing typora version 0.11.8-1 makes the problem go away.
