### ISSUE TITLE
Adding a Zoom feature?

### ISSUE THREAD

**Issue by xxf1995** [typora/typora-issues#114]
It would be nice to have a zoom feature! (better if controllable thru multi-touch)

**Comment by prefersC** [comment]
You can achieve something similar by adding the following to the style sheet of your theme. This code changes the font size when the window resizes. It worked for my bad eyes.

html { 
	font-size: 30px; 
}
@media screen and (max-width: 2240px) {
	html { font-size: 28px; }
}
@media screen and (max-width: 1920px) {
	html { font-size: 26px; }
}
@media screen and (max-width: 1600px){
	html { font-size: 24px; }
}

and so on...

If you set the size directly elsewhere in the style sheet, this may not work.

**Comment by fgimian** [comment]
+1 also Cmd + and Cmd - support please 😄

**Comment by abnerlee** [comment]
Added for Windows version, since the DPI is messy on Windows for different diaplays, but I wonder if it is needed for Mac, I think change font size should be enough already for macOS.

**Comment by filipgoc** [comment]
Another vote for Mac. Depending on the doc, sometimes it's useful to zoom in and out impromptu! Coming from text editors, this is a frustrating omission.

**Comment by aakhundov** [comment]
One more vote for Mac.

**Comment by abnerlee** [comment]
refer https://github.com/typora/typora-issues/issues/603

**Comment by fmagno** [comment]
+1

**Comment by Neonbe** [comment]
+1
