### ISSUE TITLE
Allow default to img option to allow for easier resizing

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#1140]
Since use of img tag in Typora [allows for resizing](http://support.typora.io/Resize-Image/), whereas the standard ![ syntax doesn't, would it be possible to add another option to default to this? Changing to img from standard dragged in image is cumbersome, and typically most screenshots are too large for display, yet you want to retain the whole detail for possible printing.

The default syntax would import as `<img src="/some/my.jpeg" style="zoom:100%" />` and user could then change the zoom, either manually, or (ideally!) by dragging the handle on the image to resize proportionately. E.g., I may prefer 1st screenshot below vs. the default dragged in one:

<img width="854" alt="untitled 2" src="https://user-images.githubusercontent.com/1819485/34507480-5dff4548-f004-11e7-953a-26dc26627ef5.png">

I didn't see another request for this, but apologies in advance if it's a dupe.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1059?

**Comment by AlexPasternak** [comment]
For anyone interested, I made a Keyboard Maestro macro for now as a workaround. This converts the highlighted image into HTML syntax, shrinking down to 90% by default. Good old KM, a fix for just about anything.

<img width="391" alt="screen shot 2018-01-27 at 12 56 30 pm" src="https://user-images.githubusercontent.com/1819485/35474819-a1eb3aee-0361-11e8-8021-71898e791196.png">

[Typora > Convert to Image.kmmacros.zip](https://github.com/typora/typora-issues/files/1670367/Typora.Convert.to.Image.kmmacros.zip)
