### ISSUE TITLE
White sidebar can not be removed

### ISSUE THREAD

**Issue by Vosang** [typora/typora-issues#1141]
The Residual sidebar can not be removed. Even close the application，it does not work!.
<img width="400" alt="typora-issue" src="https://user-images.githubusercontent.com/9197923/34514739-cacba50e-f0a9-11e7-8a68-440068534c18.png">

**Comment by abnerlee** [comment]
The Window/View is managed by macOS, when a program is quit, window should be closed.

So this may not be Typora's bug, maybe the system's
