### ISSUE TITLE
Rendering bug with bolds and italic encapsulate

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1142]
The chunk:
> support of *offline (real-world) **human activities***.

is rendered as: 
> ![image](https://user-images.githubusercontent.com/996001/34577162-48bad876-f191-11e7-8b11-5db5350194ee.png)

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/213

**Comment by abnerlee** [comment]
Fixed in new release
