### ISSUE TITLE
Bug with loosing position in the document (jumping to the beginning)

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1143]
It is happening in many scenarios, but here is one:

1. click on a heading in the outline (you got positioned inside the text)
2. press the Mac Command button
3. BINGO! :( You get to the top of the document

Similar situation when you switch between tabs (CTRL+TAB) with different documents, constantly positioning to the top, painful if you are copying between tabs

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/921
