### ISSUE TITLE
Openning new document with active system tabs should open document within the window

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1146]
It would make much more sense to open the new document as an additional tab if tabs are enabled for the window.

Anyway if one wants it in a separate window, there is a system support for migrating tab in a separate window, and vice versa is much harder

**Comment by amitbha** [comment]
When open files in the same folder, it's more convenient to open them in tabs than separate windows.

**Comment by vassudanagunta** [comment]
I'm not sure what you mean by "system tabs", but I believe this is already covered by this proposal: #1000.

**Comment by abnerlee** [comment]
merge in https://github.com/typora/typora-issues/issues/1000
