### ISSUE TITLE
Footnotes bug with pasting in links (after some text is typed)

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1147]
When I (manually) create a new foot note at the bottom of the document:

> `[^elbulli]: `

and I want to paste in link it is working fine 

> `[^elbulli]: https://en.wikipedia.org/wiki/ElBulli`

UNTIL i have already typed some of text

> `[^elbulli]: For more details please check `

**Comment by abnerlee** [comment]
Thanks for the report.

You mean you cannot paste link if the footnote already contains some text? I cannot reproduce this followed by this instruction.

Could you provide more detail steps to reproduce this bug? and what's your OS/Typora version BTW.
