### ISSUE TITLE
customized shortcut in conf.user.json for "Code Fences" does not work

### ISSUE THREAD

**Issue by gbuntu127** [typora/typora-issues#1148]
Linux: 
```
System:    Kernel: 4.4.0-104-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7
           Distro: Linux Mint 18 Sarah
```

Typora version: `0.9.41 (beta)`

Customized shortcut for "**Code Fences**" in conf.user.json does not work. Customized shortcuts for some other menu items work well.
  
Related Bug in [#653](https://github.com/typora/typora-issues/issues/653)

**Comment by abnerlee** [comment]
What is the shortcut key you assigned?

**Comment by gbuntu127** [comment]
Found the problem, missing one comma in one of the lines in the config, the config was not loaded.
Sorry for the mistake, please close this bug
