### ISSUE TITLE
Korean characters word counting failure.

### ISSUE THREAD

**Issue by EcmaXp** [typora/typora-issues#1149]
non latin characters word counting has problem.
actually selected sentence has only 2 words.

hello, world!
안녕, 세상아!

![image](https://user-images.githubusercontent.com/21021916/34647288-9e79118c-f3c2-11e7-8716-1594a7d831db.png)

**Comment by abnerlee** [comment]
Does Korean use whitespace to split words in a sentence?

**Comment by EcmaXp** [comment]
Yes. you can confirm in [Word Counter](https://wordcounter.net/character-count)

**Comment by abnerlee** [comment]
fixed in new release
