### ISSUE TITLE
Diagrams prevent ePub export under macOS

### ISSUE THREAD

**Issue by 1nsaner** [typora/typora-issues#1150]
Hi!
I wanted to report a bug when exporting a Markdown document in ePub.
Everything works fine in the first place but when I add a Mermaid graph (no problem with a sequenceDiagram), Typora does not export any file despite the dialog box.
Note that I don't have this problem with PDF and HTML formats.

(Typora 0.9.9.9.11.2, macOS 10.13.2)

Thank you in advance!

**Comment by abnerlee** [comment]
@1nsaner Hi, could you send us <hi@typora> a sample *.md file that can reproduce this bug?

**Comment by abnerlee** [comment]
should be fixed in new release
