### ISSUE TITLE
Typora on Chocolatey.org as a package

### ISSUE THREAD

**Issue by ladislavsulc** [typora/typora-issues#1151]
Hello,

any chance of putting Typora on Chocolatey as a package for an easy WIN install?

https://chocolatey.org/packages

Thank you.

**Comment by Lumb-Chul** [comment]
I agree. However it seems that to host a proprietary project on https://chocolatey.org/ would require the dev to pay $96 a year. I would say its up to the dev at that point. Perhaps a good reason to go open source? Probably not.

**Comment by AlexPasternak** [comment]
I'm familiar with Chocolatey, but barely ever used it on Windows. I didn't realize installing a one-time app that then auto-updates going forward was such a hassle that it needed an "easy" way to do it.

**Comment by ladislavsulc** [comment]
Many people use it to take care of their packages (programs) - you can easily update them in "terminal" or when you have a new installation, you don't need to go to each website -> download -> install. You just do ```choco install <package names>``` and you are good to go. Saves a lot of time.

**Comment by ladislavsulc** [comment]
I also want to add that it is another platform where your product can get recognition (for example when someone searches ```choco search markdown editor``` - you would pop up. Just a suggestion. Do as you will.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1457
