### ISSUE TITLE
Ctrl+Z is not right work (in table)

### ISSUE THREAD

**Issue by vidon** [typora/typora-issues#1152]
In the table , When I enter Ctrl + Z ，typora will delete some words that I typed early.
英语不好，如果不准确，请看懂中文的朋友帮忙翻译下。
在表格里面，当我按下Ctrl+Z 想要撤回上一步的操作的时候，却删掉了早期输入的一些内容，而且没有发现有什么规律。

**Comment by abnerlee** [comment]
Typora版本?

怎么复现？

**Comment by vidon** [comment]
0.9.41，windows10，都是中文环境，在表格里面输入一部分内容，例如输入10行，每行输入一些内容，输入到最后一行的时候按Ctrl+z，5-8行以及10行的内容会同时消失，但是9行的却没有消失，甚至我删除最后一行的时候（删除行），前面的内容也会消失。

**Comment by vidon** [comment]
就算是纯文字的时候按Ctrl+Z回退的内容也不确定有多少，有时候2个字有时候是10多个字，完全掌握不到规律。

**Comment by abnerlee** [comment]
what's your IME?

**Comment by vidon** [comment]
搜狗拼音输入法。8.8版本。
我又测试了下win10自带的拼音输入法，的确就没有发现那个问题，用搜狗拼音就有。
这算是软件不兼容还是输入法不兼容？

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/172

Need tests using Sougo Input

**Comment by abnerlee** [comment]
caused by #172 

Fixed in new release (tested by Baidu IME)
