### ISSUE TITLE
Smooth Scrolling issue with touchpad

### ISSUE THREAD

**Issue by liyz15** [typora/typora-issues#1153]
Win 10 1709, Surface Pro 4, Typora 0.9.41. It seems to be an electron bug.

VScode has the same bug here: https://github.com/Microsoft/vscode/issues/13612, which is still unsolved for 1 year. But bpasero made an insiders build to solve it.

**Comment by liyz15** [comment]
Great work, by the way. Best markdown editor ever.

**Comment by abnerlee** [comment]
Would be fixed by https://github.com/electron/electron/pull/12117

**Comment by abnerlee** [comment]
Should be fixed in new release
