### ISSUE TITLE
Updates overwrite window.html, resetting MathJax configuration

### ISSUE THREAD

**Issue by dzackgarza** [typora/typora-issues#1155]
In order to add Macros and aliases to be used in MathJax, there are at least a few people that edit window.html to modify the MathJax.Hub.Config({}) call.

Any time Typora is updated, however, this file is overwritten and reset, which breaks every document that used those Macros in math mode.

Is it possible to move this script to another file that is never touched or overwritten? Or perhaps there is a way to pull in a custom MathJax config file, such as what's described here? http://docs.mathjax.org/en/latest/configuration.html#using-a-local-configuration-file-with-a-cdn

(Note: I've not had any luck getting this to work.)

**Comment by abnerlee** [comment]
If we support https://github.com/typora/typora-issues/issues/100, we will support more configurations as possible
