### ISSUE TITLE
Shortcut reference link labels would be nice. Much cleaner raw source.

### ISSUE THREAD

**Issue by robmuh** [typora/typora-issues#1158]
According to the [GFM Spec], The following is valid in GFM:

```markdown
I would like [some] thing here.

[some]: https://google.com
```
I would like [some] thing here. This makes the raw markdown text particularly clean.

[some]: https://google.com
[gfm spec]: https://github.github.com/gfm/#shortcut-reference-link

**Comment by AlexPasternak** [comment]
Or you could just render normal inline links like Bear on macOS does, where URL is still inline, but has a nice inline icon that you can click to see/edit actual URL. Still 100% valid MD.

<img width="346" alt="screen shot 2018-01-11 at 9 28 43 pm" src="https://user-images.githubusercontent.com/1819485/34857000-76bc02b0-f716-11e7-8b2c-7f3dd4219496.png">

**Comment by robmuh** [comment]
Yeah that is not a solution .

**Comment by AlexPasternak** [comment]
Maybe not to the proposal of meeting this particular spec, but to question of how to avoid having long URLs inline that hurt readability, while still allowing you to add/edit them and maintain 100% valid Markdown, I don't see why not. Anyway, not to hijack the thread, obviously you're requesting reference link labels.

**Comment by robmuh** [comment]
I do really appreciate the offer of help. I actually am just hoping to get a true WSIWYG editor that actually fulfills the GFM standard. I seriously doubt my dream will ever be fulfilling by a close-source project. But one can hope.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/985

**Comment by Crissov** [comment]
This is a duplicate of #744 not of #985, unless you consider #985 a superset of #744 and therefore want to close #744.

**Comment by abnerlee** [comment]
yes, duplicate of #744
