### ISSUE TITLE
allow resizing sidebar

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#116]
![snip20160413_1](https://cloud.githubusercontent.com/assets/10832544/14483529/685fc6ae-017a-11e6-9575-6cca2687f4c0.png)

**Comment by leewi9** [comment]
@abnerlee also I'll be appreciate it vary much if you can make it also collapsable on the left side.

<img width="115" alt="2016-04-16 19 01 02" src="https://cloud.githubusercontent.com/assets/10832544/14580622/afd27832-0405-11e6-9699-7a8638f6fee1.png">

**Comment by leewi9** [comment]
Any update?

**Comment by ngbrown** [comment]
The sidebar (at least on the left) now (v0.9.42) appears to support resizing, but it's conflicting with actually scrolling with the mouse pointer as I reported in #1178.

**Comment by abnerlee** [comment]
supported in latest version. but with bugs for #1178
