### ISSUE TITLE
file 'Packages.gz' missing in ubuntu repository

### ISSUE THREAD

**Issue by panzerballett** [typora/typora-issues#1160]
hello!

i like your editor very much! that's why i wanted to include it on our internal ubuntu mirror. i use [`apt-mirror`](https://apt-mirror.github.io/) in order to download the new `.deb`s from the internet.

unfortunately your repository is missing a `Packages.gz` file (it does have the `Packages` file though). `apt-mirror` is unable to handle the extracted version of that file. would it be possible for you to `gzip` that file on your repository?

**Comment by abnerlee** [comment]
What's your Ubuntu version?

Haven't try apt-mirror, but I can install via apt-get without the `Packages.gz` file

**Comment by panzerballett** [comment]
oh, sorry, i should have been more precise...

indeed: installing  with `apt` works fine for me (on all my ubuntu 16.04 machines). it's just `apt-mirror` that crashes. maybe i should report to them and not to you?

thanks for your response!

**Comment by abnerlee** [comment]
So what's your command and error output?

I will try on my Ubuntu

**Comment by abnerlee** [comment]
added

**Comment by panzerballett** [comment]
indeed `apt-mirror` works now! thanks a lot!
