### ISSUE TITLE
version 0.9.41(windows) - The usage of CPU tends to be very high when I edit my text

### ISSUE THREAD

**Issue by Newamber** [typora/typora-issues#1162]
The usage of CPU can be rise to 40%~50% when I start editing my text and reduce to normal level instead

Now Typora ofen  tends to get choppy

以前的版本没有这个问题，如今一编辑文本，软件就很容易假死一会，这时候它的CPU占用率飙升至50%或者更多，然后不管它，又会降下来  😢

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/654

How large is your file?

**Comment by Newamber** [comment]
4~6KB
