### ISSUE TITLE
Provide option not to convert footnotes into numbers when export

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1163]
I think that translation from named footnotes 

`here it is[^named-note]`
and
`[^named-note]: bla, bla`

into `here it is[1]` not fine, considering the semantic importance of name that we usually encode in the name.

Can you provide at least both options?

**Comment by abnerlee** [comment]
I just refer to other markdown engines/parses that supports footnote, they will convert them into numbers.

> Can you provide at least both options?
This should be possible.

**Comment by mprinc** [comment]
If I understood you, you are using 3rd party parser; i guess it is still possible to "fix" it somehow, at least recover in generated HTML, by matching numbers in HTML with orders in MD

**Comment by abnerlee** [comment]
I'm close this since it is not a common request.
And we still don't get the purpose for this change
