### ISSUE TITLE
No option to remove learned words from dictionary

### ISSUE THREAD

**Issue by valzi** [typora/typora-issues#1165]
I accidentally added a misspelled word. How do I fix this?

**Comment by abnerlee** [comment]
For macOS, please refer https://www.google.com.sg/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjy7PKF1tvYAhWGjJQKHTuYAT0QFggmMAA&url=https%3A%2F%2Fwww.howtogeek.com%2F245523%2Fhow-to-remove-a-word-you-added-to-the-dictionary-on-mac-os-x%2F&usg=AOvVaw0bsKsc9fWuUcWGMJAR35lJ

For Windows10/8, please refer https://www.windowscentral.com/how-edit-custom-spell-check-dictionary-windows-10

**Comment by Gariiii** [comment]
Is there a way to remove it from a Linux Ubuntu 18.04 LTS? Have unsuccessfully searched the *.dic files through the system.

**Comment by abnerlee** [comment]
supported already

**Comment by valzi** [comment]
Thanks

**Comment by stanstrup** [comment]
On windows I found it in: `C:\Users\[USER]\AppData\Roaming\Typora\dictionaries\user-dict.json`

**Comment by Zoetic-Zephyr** [comment]
@stanstrup has the right solution for Windows users.
