### ISSUE TITLE
picture file path

### ISSUE THREAD

**Issue by Philippe91** [typora/typora-issues#1167]
When dropping a picture from the the file explorer, the file is correctly displayed in Typora. However, the path stored in the .md file is using \ separators rather than /
Eg. c:\test\piano.png
and not
c:/test/piano.png
This causes the pictures not to be viewable by most other MD viewers.

Moreover, using relative file paths rather than absolute paths would be better.

**Comment by abnerlee** [comment]
We support relative path, please see http://support.typora.io/Images/#use-relative-path

>  However, the path stored in the .md file is using \ separators rather than /

on Windows, the file path is using \ instead of /, so I do not think there's some wrong for following this rule.

**Comment by Philippe91** [comment]
Thanks for the hint on the relative path option. Fortunately, this relative path is using / and not \
which is necessary for portability.
