### ISSUE TITLE
mermaid gantt is not correct

### ISSUE THREAD

**Issue by takakawa** [typora/typora-issues#1168]
Mermaid gantt charts render strangly.
![pic](https://ws2.sinaimg.cn/large/006tNc79ly1fnk4bxt85dj31kw0liwi2.jpg)

**Comment by abnerlee** [comment]
duplicte with https://github.com/typora/typora-issues/issues/1053

Did you resize your window after input the gantt ?

**Comment by cnshijin** [comment]
How to resize the window? I have the same problem on the 0.9.9.50 release, and the OS is windows 7. Thank you!
