### ISSUE TITLE
how to setup pandoc path

### ISSUE THREAD

**Issue by chandlersong** [typora/typora-issues#1169]
pandoc -version can work well. but Typora still report cant pandoc.  Can I change some configuration to tell  Typora where pandoc is? 

Because I can't install software . I install Typora in another pc and copy it to the first pc. and it can work well. and I download pandoc and set the pandoc into the path.  and I can run pandoc --version well

the pc is windows7 32bit.

**Comment by abnerlee** [comment]
Is pandoc in your PATH? And try restart Typora after installation of pandoc.

**Comment by chandlersong** [comment]
yeah， the pandoc is in my path. 
and pandoc -version can work well.

**Comment by abnerlee** [comment]
After you add it into PATH, have you try restart Typora?

> is there any position I can let Typora to find pandoc where I set? if not, Could add this feature?
No, but we can add this feature

**Comment by chandlersong** [comment]
yes， I have。 and I've tried to restart PC. but it still can't work.

and thank you for add this feature in the future.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1451

**Comment by mimi3421** [comment]
Typora search for pandoc.exe in PATH and the path the editing md file located in.
