### ISSUE TITLE
Resize Table button/widget deletes data without warning

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1170]
## problem
1. The widget for resizing a table graphically indicates the current number of columns **but not rows**. See screenshot below.
2. The widget's `▢ x ▢ ` fields always shows `1` for rows, not the number of current rows. See screenshot below. See also #1124.
3. If you shrink the table so that a non-empy row or column does not fit, Typora **silently deletes** them, along with all their content.

![untitled](https://user-images.githubusercontent.com/2830093/35168857-81db9cf6-fd28-11e7-9e7e-afa217c88fda.png)

## workaround
Manually count the rows and columns with non-empty cells before resizing, or trial and error using Undo. Both of these are error prone especially when the table is large. One may not notice a non-empty row or column being deleted. 

### If keeping the current widget

1. The widget should indicate the current size.
2. Ideally the widget should also indicate the non-empty size (exclude empty rows on the bottom and empty columns on the right). For example, it could do that with a different shade, or by putting dots in the cells of the widget.
3. Both the column and row fields should be initialized with the current table size. 
4. When the table size is reduced such that non-empty cells will be deleted, get user confirmation before doing so.

### A better solution
Ditch the widget and introduce the ability to resize by dragging the right or bottom edge of the actual table, with live feedback so that the user can visually see what is happening.

See also #344 for other ideas.

**Comment by abnerlee** [comment]
> The widget's ▢ x ▢ fields always shows 1 for rows, not the number of current rows. See screenshot below. See also #1124.

This is a bug. We will fix this in next version up. (#1124)

> If you shrink the table so that a non-empy row or column does not fit, Typora silently deletes them, along with all their content.

We allow this since user can undo this operation. So providing a fast modification without confirm is ok in my mind if this can be undo.

Suggestion will be considered in https://github.com/typora/typora-issues/issues/1088. 

For telling users about columns/rows with data will be removed, we can also show warning on live resize, or highlight cells of current table with a different color in the resize panel.
