### ISSUE TITLE
Smart formatting - Quotation marks

### ISSUE THREAD

**Issue by sumnermic** [typora/typora-issues#1171]
Hello,

Missing Feature: Smart formatting of quotation marks/apostrophe.
Left single quotation mark: `‘`
Right single quotation mark / apostrophe: `’`
Left Double quotation mark: `“`
Right double quotation mark: `”`

A typographer's nightmare is to not properly use `‘`, `’`, `“`, `”`. I moved over to Typora because it's amazing, although it lacked this feature which made me filter down through the different markdown editors out there.

Sadly GitHub itself isn't supporting this yet... but I know Typora is better! 💯

**Comment by abnerlee** [comment]
part of https://github.com/typora/typora-issues/issues/137 and https://github.com/typora/typora-issues/issues/291
