### ISSUE TITLE
Translation issue in update modal

### ISSUE THREAD

**Issue by szepeviktor** [typora/typora-issues#1173]
![kep](https://user-images.githubusercontent.com/952007/35192493-137b9ee2-fe94-11e7-8150-0b3303831457.png)

Could it be that the Hungarian translation has this (Poedit) incorrectly?

**Comment by szepeviktor** [comment]
https://github.com/vslavik/winsparkle/blob/master/translations/hu.po#L67-L69

**Comment by abnerlee** [comment]
Fixed in new version. New version of WinSparkle is used.
