### ISSUE TITLE
Change modified time on every save?

### ISSUE THREAD

**Issue by Kokxer** [typora/typora-issues#1175]
I found that seems typora only change the **modified time** property of file on program exit. Upon every modify and save, this property does not change. This breaks some tools' "auto reload" feature since they use this property to monitor the change of file. For example jekyll's _auto-watch_.

 Could typora change **modified time** on every save?

**Comment by abnerlee** [comment]
Typora/OS version ?

**Comment by Kokxer** [comment]
version 0.9.41(beta) on windows.

**Comment by abnerlee** [comment]
fixed in v0.9.42

**Comment by Kokxer** [comment]
It works. Thanks you.
