### ISSUE TITLE
Notes over sequence diagram are transparent

### ISSUE THREAD

**Issue by PritschetW** [typora/typora-issues#1176]
I'm using the sequence diagram. There I have some "Note over ...". But this nodes are drawn transparent. So the vertical line goes through the note.
In the examples of js-sequence (https://bramp.github.io/js-sequence-diagrams/) this notes have a backround.
Is ist possible to change it?

![nodes-over-transparent](https://user-images.githubusercontent.com/35721414/35263152-f39ba7d6-0017-11e8-965c-5d69dc37ddc1.png)

Many thanx and best regards
  Wolfgang

**Comment by abnerlee** [comment]
Fixed in new release
