### ISSUE TITLE
Launching Typora creates Untitled document. Can this be disabled?

### ISSUE THREAD

**Issue by jaredmeakin** [typora/typora-issues#1177]
When launching Typora I often want to open an existing document—not create a new one.

Is there a way to disable the "Untitled" document that gets created whenever I launch Typora?

My current workflow is **Launch Typora** > **CMD + Shift + O** > **Type filename**. Then I have to go back and close the "Untitled" document which I don't need.

**Comment by vassudanagunta** [comment]
Typical workflow for most OSes is open the app to start a new doc, or directly open an existing doc to work on that. Why not set Typora as your default Markdown editor and do that?

**Comment by abnerlee** [comment]
We will do like this:

If you use quick open to open a file, and if current window is an "Untitied" without any modification, instead of open the file in new window, we will open it in current window and discard the "Untitled" document since it is not modified.

**Comment by abnerlee** [comment]
> If you use quick open to open a file, and if current window is an "Untitled" document without any modification, instead of opening the file in new window, we will open it in current window and discard the "Untitled" document since it is not modified.

This is supported in new release
