### ISSUE TITLE
Vertical scroll bar in outline/articles/file view Sidebar is not selectable in Windows

### ISSUE THREAD

**Issue by ngbrown** [typora/typora-issues#1178]
In Windows 10 and Typora v0.9.42. The vertical scroll bar in the side bar can not be clicked on to be moved with the mouse.  Instead the mouse grabs the splitter and shows vertical dashed lines.  There should be a way to do both the splitter and move the scroll bar with the mouse (no trackpad or mouse wheel).

**Comment by abnerlee** [comment]
Fixed in new release
