### ISSUE TITLE
Typora, superscript of more than one character is not supported inside a Math block

### ISSUE THREAD

**Issue by Jecs9** [typora/typora-issues#1179]
When I want to have a superscript of more than one characters inside a math block the "Missing superscript or subscript argument" error appears, if I do the same in a paragraph it works properly

$$
y= x^(a+b)^
$$

x^(a+b)^

**Comment by cben** [comment]
Try `x^{a+b}`, I believ inside math blocks you use LaTeX syntax, while `^...^` is an independent markdown extension.

**Comment by abnerlee** [comment]
@cben is corrected, inside `$..$` only LaTeX/TeX command is supported. `^..^` is a markdown extension with no relationship with LaTeX/TeX

**Comment by anniezhi** [comment]
What about subscript? Does anyone know how to add subscript in a math block? Is ~...~ supported by Typora?
