### ISSUE TITLE
Add page breaks and header/footer/page number

### ISSUE THREAD

**Issue by NeedsAdjustment** [typora/typora-issues#118]
Native support for page breaks would be _great_. At the moment I'm using:
`<div style="page-break-after: always;"></div>` as a workaround every time I need one, but I imagine actual support wouldn't be too hard to add in?

The header/footer issue is a little more tricky. I'm not sure how to html that, but I think it depends on the pdf/html compiler that Typora uses?

**Comment by abnerlee** [comment]
For page breaks. In typora, theres no `pages`. After exporting PDF, there will be pages, but `<div style="page-break-after: always;"></div> ` should work in exported PDFs.

header/footer seems also a future for exported PDFs, maybe we can add option in printing/exporting dialog to handle this

**Comment by retsyo** [comment]
how can we use ` <div style="page-break-after: always;"></div> ` in typora workspace?

**Comment by MicheleLevorato** [comment]
I'm used to add the following row:
`@media print {
    h1 {page-break-before: always;}
}`
in Typora\resources\app\style\base.css

**Comment by kcpr** [comment]
You can also add the following in specific file:
`<style>h1 { page-break-before: always; }</style>`. 
Unfortunately, If You start Your document from `h1`, You will get blank page at the begging though.

Another solution is to combine both options, adding `<style>.line-break { page-break-after: always; }</style>` at the begging of the document and `<p class='line-break'/>` every time You want to have a line break.

**Comment by abnerlee** [comment]
For macOS, there's an option to break page for each `h1` section when printing.

For other OS, currently, using CSS suggested by @MicheleLevorato  and @kcpr could be a workaround

**Comment by orschiro** [comment]
Can this become a menu entry such as `Insert > Page Break` which inserts the HTML line of code at the cursor position?

**Comment by lloyd094** [comment]
I'd love this option - to have a toggle somewhere that makes these documents printable. It's a gorgeous program and makes great looking papers, but the inability to print pages makes it tough.

**Comment by lloyd094** [comment]
After doing some research into CSS, I found a simple trick for an instant page break:

Wherever in Typora where you need a new page, add the line: `<div class="page-break"></div>`.

Seems to be working for me anyways.

**Comment by Crissov** [comment]
For [manual page breaks](https://drafts.csswg.org/css-break-3/#breaking-controls) (i.e. not before headings), you should be able to repurpose horizontal lines, i.e. `<hr>` in HTML and `----`, `____` or `****` in Markdown.

```` css
hr {page-break-after: always; break-after: page; height: 0.01em}
````

**Comment by haribo256** [comment]
Any idea on whether this is being considered? and what priority it is?

This is the one feature that would sincerely help when handing over our beautiful Markdown documents over to non-Markdown people via the export.

**Comment by banderlog** [comment]
All this dances with custom css styles for such basic thing as a pagebreak are look like a bicycle full of crutches.
It is a very nice markdown software and pagebreake insertion shouldn’t be harder, for user,  than table insertion. But at this moment it is)

**Comment by ArmanUV** [comment]
@Crissov 

I tried adding the `hr` CSS to my base.user.css in the themes folder but it did not make any difference. 
I am using 0.9.9.12.5 on mac. Any ideas?

**Comment by mrclrchtr** [comment]
http://support.typora.io/Page-Breaks/

**Comment by banderlog** [comment]
Yes, it works. But, let's imagine, that I have a long document with plots and tables and text. And I do not want to page-break after each #h1. 

Maybe, sometimes, I want page break after certain #h2 or after dome plots (not all). And I want to see such places before pdf compilation, as long as it is WYSIWYG editor.  
Or, at least, do such stuff as in other editors -- insert LaTeX's `\pagebreak`, at the minimum it is just one word. Instead, I must every time mess with css styles. Not cool.

**Comment by Crissov** [comment]
Well, I suggested to use `hr` for manual page breaks. You can also suggest preferred page break opportunities for headings etc.

**Comment by MicheleLevorato** [comment]
>  I suggested to use `hr `for manual page breaks
It looks way more semantically appropriate than `H1`. This option has my vote.

**Comment by j3ffwilcox** [comment]
+1 for header and foot support for export.  This is really the only missing feature keeping me from switching our doc system to use Typora.  We need to be able to produce PDFs with a boilerplate footer for document release and there really isn't any way to do that at the moment.  

We use Word today, but having a documentation flow that plays nice with text repositories like Git is a huge win.  There are a few other small missing features that are nice to have, but this one little feature is really standing in the way unfortunately.

**Comment by Epandudev** [comment]
Just follow the below table structure.No need to write more css this works in all browsers include.this is working for me lets try.If you want to add page numbers you can add but it works only in firefox.
<table class="report_container_Mh" cellpadding="4" cellspacing="0" width="790" align="center" background="" style="word-break: break-word">
    
    
    <thead class="report_header_Mh">
      <tr>
        <th class=""> <div class="header_info_Mh"> </div>
        </th>
      </tr>
    </thead>
     
    
    
    <tbody class="report_content_Mh">
      <tr>
        <td class="report_content-cell_Mh"><div class="main_Mh">
            <table border="0" cellpadding="2" cellspacing="0" width="790" align="center" style="margin: auto">
              <tbody>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              	<tr><td>
              		Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
              	</td></tr>
              </tbody>
            </table>
          </div></td>
      </tr>
    </tbody>
     
    
    
    <tfoot class="report_footer_Mh">
      <tr>
        
      </tr>
          <div class="footer-container">
        <div class="footer-widget">
            <b>FooBar Company Name</b>
        </div>
        <div class="text-align-right">
            <span class="page"></span>/<span class="topage"></span>
        </div>
    </div>
    
    
    
  </table>

<style>
thead.report_header_Mh {
		display: table-header-group;
	}
	tfoot.report_footer_Mh {
		display: table-footer-group;
	}
	table.print > tbody > tr {
		page-break-inside: avoid;
	}
	tabel.report_container_Mh {
		page-break-after: always;
		overflow: clip
	}

/*For page numbers it works add these properties in print media*/
	.report_footer_counter_Mh:after{
		  	counter-increment: Page  ;
content: "Page " counter(Page);
		   text-align: right;
    z-index: 20px;
	  }	
</style>

**Comment by marksugar** [comment]
When I was writing a large-scale article, I also encountered such troubles. However, time has passed so long, it seems that this issue has not made much progress. If you can, in addition to the question here, can add a watermark function!

Thanks

**Comment by jiuxiaxixi** [comment]
> For page breaks. In typora, theres no `pages`. After exporting PDF, there will be pages, but `<div style="page-break-after: always;"></div>` should work in exported PDFs.
> 
> header/footer seems also a future for exported PDFs, maybe we can add option in printing/exporting dialog to handle this

is that support now?

**Comment by abnerlee** [comment]
supported as https://support.typora.io/Export/#header--footer

**Comment by knennigtri** [comment]
Is there an easy way to target header/footer created with a yaml file now? This would be nice to move the header footer/footer left/right and changing the font. 
Is there a class name we can use?
