### ISSUE TITLE
0.9.42 on Windows: Main window doesn't show up

### ISSUE THREAD

**Issue by shsssc** [typora/typora-issues#1185]
I just updated to 0.9.42. When I open the program, its icon shows in the task bar. But the window doesn't actually show up. I could see the Window in task view of windows 10. 

I tried to use keyboard shortcuts to change the location of the window, which didn't work. So I think it's a bug in the program. Also this issue showed right after I upgraded

**Comment by abnerlee** [comment]
could you send us <hi@typora.io> log file C:\Users\{username}\AppData\Roaming\Typora\typora.log and C:\Users\{username}\AppData\Roaming\Typora\window-state.json file ?

And then try remove C:\Users\{username}\AppData\Roaming\Typora\window-state.json the restart Typora

**Comment by shsssc** [comment]
Sent the files by email.
I fixed the issue by removing window-state.json file.
Thank you very much.
