### ISSUE TITLE
Please stop "correcting" my markdown numbering in Typora

### ISSUE THREAD

**Issue by KirkMunro** [typora/typora-issues#1188]
Using 1-dot numbering (1. for all numbered lists) in markdown is a best practice, for many reasons:

1. It allows reordering of list items to be done in __any__ markdown editor, without having to manually renumber the lists.
1. It makes for better file diffs in source control tools (only new items show up in a list, vs changes on all lines if you insert a step in your list.

Why then does Typora try to "prettify" my markdown by replacing my best practice work with forced, strict numbering? The default behavior should be to use 1-dot numbering in the markdown that is created by this tool (when you hit enter after a numbered list and it automatically continues the numbering). The current behavior (using explicit numbering) should be an option.

If you're not in agreement with adhering to the best practice, you at least need to make it optional.

Also, some general feedback:

I like Typora, a lot, and I have been promoting it heavily because I really like the integrated WYSIWYG experience it offers over other markdown editors that use a split view. I'm sharing this feedback because I would like Typora to succeed; however, it **must** encourage and follow markdown best practices, so that the content it produces work well _everywhere else that markdown is used_ (GitHub or other source control systems being a big one, but there are many, many other places that markdown is being used beyond GitHub).

This behavior (and any attempts to prettify markdown that shouldn't be prettified), the optional strict behavior for GFM support (things like spaces after ATX headers isn't GFM-specific -- it's from the CommonMark standard, so it shouldn't be promoted as strict/optional), the cutesy table rendering _including justification in the markdown that makes modification of such things anywhere but in Typora a huge chore_ (I can't believe you do that) are absolute showstoppers that you should seriously consider correcting.

**Any non-standard, Typora-specific formatting of the markdown content itself must be optional. Otherwise, Typora will be a tool that can only be used within Teams who are 100% committed to using Typora to create and maintain markdown documentation, and that's going to be a really, really hard sell. I can only justify recommending Typora to team members if it does not get in the way of the rest of the tools that we use, and the markdown prettifying it does today is 100% in the way of everything else. If you don't understand this, please, let's discuss it, because I'd hate to see this otherwise really well designed tool go to waste.**

**Comment by AlexPasternak** [comment]
I think basically you're railing against using specific numbers in ordered lists, but this has been part of MD spec from the beginning: https://daringfireball.net/projects/markdown/syntax#list

While 1. syntax is also fine, not using it isn't non-standard, or somehow violating any specs, as far as I understand it. In a WYSIWYG editor, auto-incrementing a numbered list seems like pretty friendly behavior.

I would also argue that when you insert an item, and subsequent list item numbers change, that *is* something I want to see in the diff, because an item that used to be 2nd is now 3rd. But I can also see it being a matter of personal preference.

**Comment by vassudanagunta** [comment]
I am unable to use Typora to edit the docs of at least one open source project I contribute to because it renumbers all the ordered lists in the source. That project ([Hugo](gohugo.io), a pretty big deal project), follow exactly the best practice that @KirkMunro describes for exactly the reasons he gives. 

So yes, this should be a configurable `auto-renumber ordered lists` option. It's fine if it defaults to TRUE.

**Comment by vassudanagunta** [comment]
I also agree with the last two paragraphs. It goes hand-in-hand with #369, and failure will prevent Typora's adoption in more serious contexts where multiple people using heterogenous tools are involved.

**Comment by KirkMunro** [comment]
@AlexPasternak I didn't mean to imply that using explicit numbering in ordered lists in markdown is non-standard. What is non-standard is that Typora will take any markdown file that is opened within it that has automatic (1-dot) numbering and silently replace that numbering with explicit (1., 2., 3., etc.) numbering. Automatic numbering is definitely the best practice though, so I feel Typora needs to:

1. Choose a default numbering scheme for new ordered lists (automatic or explicit -- I believe it should go with automatic since that is a best practice worth following).
1. Allow users to change the default numbering scheme for new ordered lists to their personal preference.
1. Adhere to the numbering scheme that is used on an ordered list when adding items to that list (i.e. if I'm editing a document that uses 1., 2., 3., and I add an item, it should be added with 4.; similarly, if the list I'm modifying uses 1., 1., 1. and I add an item, it should be added with 1). 
1. Under no circumstance should Typora silently change an entire document to one numbering scheme or the other like it does now, unless I tell it to do so. All automatic, silent modification of markdown documents needs to be removed from this editor.

**Comment by vassudanagunta** [comment]
> unless I tell it to do so.

It would be useful to have a 'Normalize Markdown` menu that retroactively applies your default choices for numbering scheme and the other items in `Syntax Preference`. A preference could also be added to `Auto-normalize Markdown`, which would result in Typora's current behavior.

**Comment by AlexPasternak** [comment]
@KirkMunro, thanks for the explanation, now I understand much better. 100% agreed in this case, similar to your other posted issue about tables. I don't like when touching a line affects a bunch of other unrelated lines in an editor, that's for sure.

E.g., Visual Studio has settings for how to treat newlines in documents. It can either always convert to your preference, or keep whatever is currently existing in the file. We need something similar here for MD style.

**Comment by abnerlee** [comment]
Fixed in new release.

**Comment by KirkMunro** [comment]
Thank you @abnerlee. One minor issue with this fix: If you create a new ordered list in the hybrid editor, with the option turned on for 1-dot numbering, Typora inserts two spaces following the 1. instead of just one. Why insert the extra, unneeded space in this case?

**Comment by vassudanagunta** [comment]
@KirkMunro, check your `Indent Size on Save` setting. Somehow mine got switched to 3 instead of Auto (even though the example widget showed auto). You might have to switch it to something and back to Auto to get it to do Auto. If this works for you, maybe need to report this as a bug.

**Comment by KirkMunro** [comment]
@vassudanagunta Ok, so that's not my issue, but by pointing out that setting you highlighted why I'm seeing what I'm seeing, so thank you.

In my opinion, "indent size" is the size of the indent, and nothing more. For example, I have my indent size in Typora set to 4. With that, I expect any nested content that gets indented to be indented 4 spaces. I do not expect that indent size will also apply a hanging indent of 4 as well in the raw markdown that is generated. Hanging indentation is about prettifying output, and only matters in rendered content. It doesn't matter in raw markdown. Indentation does matter in raw markdown, because it creates parent/child relationships between items.

I'll have to log a separate enhancement request to see if @abnerlee can break these out and offer a hanging indentation option for people who want prettified markdown.

**Comment by KirkMunro** [comment]
Logged new issue: #1217.
