### ISSUE TITLE
Subscript/Superscript

### ISSUE THREAD

**Issue by NeedsAdjustment** [typora/typora-issues#119]
Sorry for forgetting to mention this earlier, but subscript/superscript without `<sub></sub>` etc would also be really great. I know this is *sort of* covered by the LATEX integration, but for simple things like CO**2** emissions and 1**st** anniversary... well.

**Comment by abnerlee** [comment]
Well, you could also enable these two syntax from preference panel.

superscript -> `1^st^`

subscript -> `CO~2~`
