### ISSUE TITLE
Text in Mermaid flowcharts is hard to read in Night theme

### ISSUE THREAD

**Issue by oxguy3** [typora/typora-issues#1190]
It seems that Mermaid mostly uses its own color scheme for flowcharts (i.e. rather than using the theme's color scheme), but it _does_ use the theme's text color. This mostly looks fine, but on the Night theme, it makes the text very difficult to read:

<img width="890" alt="screen shot 2018-01-26 at 5 44 02 pm" src="https://user-images.githubusercontent.com/796881/35463940-45353d9a-02c1-11e8-9754-77e44a56e111.png">

Poking around in Mermaid.js, it [looks like](https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js#L437) it just uses the font family and color that's applied to the SVG element. You could just make the font color for Mermaid SVGs black, regardless of what theme is applied, and that would fix the issue. i.e.:

```css
.mermaid svg {
    color: black;
}
```

Alternatively, if you want to customize how flowcharts look for each theme, you could inject a `classDef default` line into the end of every flowchart diagram before initializing Mermaid. [More info on Default Classes](https://mermaidjs.github.io/flowchart.html#default-class).

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by abnerlee** [comment]
Should be fixed in new release.
