### ISSUE TITLE
Newlines stripped on paste from Flash

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#1193]
When pasting in text sometimes, Typora strips newlines for some reason, resulting in text that is all combined. This requires manual fixing, which is undesirable and time consuming.

![2018-01-27 13 18 21](https://user-images.githubusercontent.com/1819485/35475006-f809d5fe-0364-11e8-9efd-9ee29467c147.gif)

It happens very quickly in this repro GIF, so it might be hard to catch, but initially things look fine, then Typora "corrects" the lines to be all joined for some reason.

<img width="350" alt="screen shot 2018-01-27 at 1 22 32 pm" src="https://user-images.githubusercontent.com/1819485/35475015-2706152a-0365-11e8-843d-6e4646dc51ad.png">

For comparison, TextMate treats this text correctly. For my workaround, I end up having to paste plain text into TM, then copy and paste *that* into Typora.

<img width="383" alt="screen shot 2018-01-27 at 1 23 22 pm" src="https://user-images.githubusercontent.com/1819485/35475022-4787578c-0365-11e8-83be-569f92dd6013.png">

**Comment by abnerlee** [comment]
@AlexPasternak HI, you closed this, it means this is not an issue?

**Comment by AlexPasternak** [comment]
That was by accident, it's definitely a reproducible issue for me.

**Comment by abnerlee** [comment]
So, could you send us (<hi@typora.io>) the url or file that you copied from?

And What's your Typora/OS version?

**Comment by AlexPasternak** [comment]
@abnerlee It's text copied from a private training site, so I can't provide the URL. I was going to provide the raw file as an attachment, but like I said above, when I paste into another file, that can't be used to repro the issue, as Typora opens that one OK. I thought providing raw summary above (using `cat -e`) would be enough info. For version, it's latest Typora on macOS 10.13.2.

**Comment by abnerlee** [comment]
@AlexPasternak I see, how about shift+cmd+v ? And it is copied from HTML, right?

**Comment by AlexPasternak** [comment]
Copied from a Flash training player actually. But again, pasting this exact text into TextEdit or TextMate results in 8 lines.

No difference if you use paste as plain text:
![2018-01-29 08 06 21](https://user-images.githubusercontent.com/1819485/35511920-d5cd62ae-04cb-11e8-9c19-dc328aacd35a.gif)

**Comment by abnerlee** [comment]
Could you try paste following in plain text into Typora? In my test it works well
```
aaa
bbb
ccc
```

**Comment by AlexPasternak** [comment]
This actually pastes as source code into Typora, because of its formatting. I don't think pasting this from a browser is going to repro the issue. Do you notice how Typora reformats pasted in text in the original repro GIF at the top? Is there something that processes text right after paste?

The only other thing I can think of is attaching raw files. Here is comparison of paste into vim vs. paste into Typora.

<img width="636" alt="screen shot 2018-01-29 at 9 18 39 am" src="https://user-images.githubusercontent.com/1819485/35514891-ad99d240-04d5-11e8-89c3-8233cd4ec227.png">

[vimout.txt](https://github.com/typora/typora-issues/files/1673843/vimout.txt)

[typoraout.md.txt](https://github.com/typora/typora-issues/files/1673844/typoraout.md.txt)

**Comment by abnerlee** [comment]
Can you reproduce this by paste text in vimout.txt into Typora?

**Comment by AlexPasternak** [comment]
No, I can only repro when pasting from Flash. Good news, however, I finally found a public example you should be able to use.

1. Access http://condor.depaul.edu/sjost/hci430/flash-examples/swf/greeter4.swf
1. Type "Test" as Name and click Show Greeting button
1. Copy resulting greeting text, 2 lines
1. Paste into Typora, this wraps to a single line, same behavior

For the rest of the OS, btw, there is no visible behavior in rendering. Here's another comparison of rendering by Paste app, a clipboard manager with previews.

<img width="885" alt="screen shot 2018-01-29 at 10 00 38 am" src="https://user-images.githubusercontent.com/1819485/35517482-92f07e10-04dc-11e8-8252-3b42dc50af67.png">

**Comment by abnerlee** [comment]
@AlexPasternak I just remembered that I got a similar bug report from one user, which I failed to reproduce. The common thing is "Firefox".

So this may relates to Firefox instead of Flash. Could you check https://gitlab.com/gitlab-org/gitlab-ce/issues/24334 and confirm the bug in that link can also be reproduce when paste into Typora? 

Thanks. If so we will test in Firefox on macOS instead.

**Comment by AlexPasternak** [comment]
Sorry, I don't think it's the same issue. When I copy content of the [sample issue file](https://gitlab.com/issue-reproduce/line-breaks-copy/blob/master/test.js), it pastes relatively OK into Typora.

<img width="437" alt="screen shot 2018-01-29 at 3 01 50 pm" src="https://user-images.githubusercontent.com/1819485/35531613-7acb27c6-0505-11e8-9ca4-327a44847b63.png">

I am on FF, but it's it's v58, which is much newer than the Gitlab issue. I also reproduced the issue using my .swf link above via Safari, so it's not browser-specific.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/1413

**Comment by AlexPasternak** [comment]
Same exact behavior on 0.9.9.15 when using my greeter4.swf steps above. You can see 2 lines for a split second when you paste, then it wraps to a single line.

**Comment by abnerlee** [comment]
merge into #1502
