### ISSUE TITLE
Change the autosave folder

### ISSUE THREAD

**Issue by 04fsnape** [typora/typora-issues#1194]
I like the fact that Typora comes with an autosave feature, but I was wondering if it would be possible to change the folder that it autosaves to? I would like to be able to change it to autosave to my OneDrive folder since I write notes on both my desktop and my laptop.

Thanks.

**Comment by abnerlee** [comment]
Hi, 

"autosave" is done on the original file.

We have one folder for auto-backup, which content will be saved there very a few minutes, but it is for backup and is not readable for human.

**Comment by 04fsnape** [comment]
@abnerlee By default it saves .md files in the AppData/Roaming/Typora/draftsRecover. These files are in plain text. How can I change the folder? The way I got to this is through the "Recover Unsaved Drafts" button in Preferences.

**Comment by abnerlee** [comment]
Yes, it is in `AppData/Roaming/Typora/draftsRecover`, but that is temporary or backup files, it is not used for syncing purpose. I think user should sync their working folders instead.

May I know more about the reason that you change the folder?

**Comment by 04fsnape** [comment]
@abnerlee I work from two computers so if I'm working on a document and I forget to save it then I would like to be able to access the autosaved .md file from my other computer. I would do this by changing the autosave file to a folder in my OneDrive.
