### ISSUE TITLE
Autocorrect before I finish typing the word

### ISSUE THREAD

**Issue by 04fsnape** [typora/typora-issues#1195]
I would like to be able to use the autocorrect feature, but it REALLY annoys me that the word is underlined in red before I have even finished typing the word. For example, if I am typing the word "example", and I have only typed "examp" but I have not used a space to finish the word, it tells me the word I am typing is incorrect. If you could change it so that the underline only appears once you have pressed the spacebar, indicating that you have finished the word. The ability to change the colour of the underline would be nice too.

**Comment by abnerlee** [comment]
What's your OS version?

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/983

**Comment by 04fsnape** [comment]
@abnerlee It may be a duplicate but I don't see any actual solution to the problem being presented. It seems as though people have been having this issue since 2016. Are you planning on fixing it?

**Comment by 04fsnape** [comment]
@abnerlee I'm running up to date Windows 10

**Comment by 04fsnape** [comment]
@abnerlee Hello?

**Comment by abnerlee** [comment]
It is not fixed, see https://github.com/typora/typora-issues/issues/214
