### ISSUE TITLE
Can't change the colour of the highlight

### ISSUE THREAD

**Issue by 04fsnape** [typora/typora-issues#1196]
So I am using my own custom dark theme and I really like being able to highlight stuff, but unfortunately the yellow highlight really doesn't work with my colour scheme and makes it very uncomfortable to read. Perhaps you can already do this (please tell me if so), but if not - could you add a feature which allows me to change its colour, and the colour of the text being highlighted? I am referring to the optional ==highlight== feature.

Thanks.

**Comment by abnerlee** [comment]
you should add CSS in your custom dark theme

**Comment by abnerlee** [comment]
#204
