### ISSUE TITLE
Inline displaystyle math

### ISSUE THREAD

**Issue by reflectionalist** [typora/typora-issues#1197]
Typora used to have a nice feature that `$$\frac{2}{3}$$` gives `displaystyle` math equivalent to `$\displaystyle \frac{2}{3}$` inline.  @abnerlee , if you remember, I once mentioned this (unfortunately I can not recall the occasion).  My guess then was Typora translates into block instead of inline math.  You accredited it to how Typora parses `$$...$$` or something like that.  Unfortunately, I find the feature is gone in recent versions of Typora.  I can not remember since which version.  But it is not there in version 0.9.41 and 0.9.42.  I am on an Arch Linux x86-64 build.  I'd call this feature back.  Writing `$\displaystyle \frac{2}{3}$` is really too much.

**Comment by shreevatsa** [comment]
It would be great to have the default TeX behaviour, of getting inline (non-displaystyle) math with `$...$`, and display math with `$$ ... $$`. Right now, typing `\displaystyle` manually is a bit too much of an annoyance, as @reflectionalist said.

**Comment by abnerlee** [comment]
Use
```
$$
block
$$
```
for display math. We do not support writing inline math in display style.

**Comment by reflectionalist** [comment]
> Use
> 
> ```
> $$
> block
> $$
> ```
> for display math. We do not support writing inline math in display style.

Yes, hence I am requesting for this feature.
