### ISSUE TITLE
Checking document spelling with the keyboard shortcut crashes.

### ISSUE THREAD

**Issue by ghost** [typora/typora-issues#1198]
# Environment
* MacBook Pro 2017
* macOS High Sierra 10.13.2
* Typora 0.9.9.12 (0.9.9.12)

# Steps to Reproduce
1. Open a folder containing `*.md` files from `File > Open...`.
2. Switch to the *File Tree view*.
3. Click on a `*.md` file without clicking in the editor afterwards. There is no active cursor nor focus on the document and the `Edit > Spelling and Grammar > Check Document Now` menu is greyed-out.
3. Use the greyed-out `Edit > Spelling and Grammar > Check Document Now` menu's `⌘;` shortcut.

# Current Behaviour
The window freezes showing the default loading pointer and needs to be force-quitted from the `System` menu.

# Expected behaviour
The shortcut shouldn't trigger as `Check Document Now` is greyed-out.

# Enhancement
Allow `Check Document Now` and `Show Spelling And Grammar` to be executed without having to focus on a document after opening it.

**Comment by abnerlee** [comment]
still happen in latest version?
