### ISSUE TITLE
FlowChart and SequenceChart

### ISSUE THREAD

**Issue by surpmillet** [typora/typora-issues#12]
have you ever thought about to add FlowChart and SequenceChart in your roadmap?

**Comment by abnerlee** [comment]
In recent update plans, no.

I think drag/drop is most easy and fast way to create charts. Current markdown syntax for FlowChart/SequenceChart is too geek. However, if I integrate FlowChart/SequenceChart in typora's way, in other words, providing easy-to-use user interface for creating/modifying charts, it will be too much work.

Besides, I'm not sure how many users would write FlowChart/SequenceChart in markdown.

**Comment by devjie** [comment]
+1 for this Feature.

**Comment by augustblizzard** [comment]
+1 me too

**Comment by vassudanagunta** [comment]
I agree that adding FlowChart/SequenceChart go against Typora's mission of being "a truly minimal markdown editor". But if you decide to do it, take a look at [WebSequenceDiagrams](https://www.websequencediagrams.com). It uses a very simple plain text syntax that is the Markdown of sequence diagrams! Amazingly simple and intuitive. Almost natural language. 

[They even support embedding](https://www.websequencediagrams.com/embedding.html) if it makes more sense than replicating the functionality natively within Typora.  Looks like there is an open source clone: [JS Sequence Diagrams](https://bramp.github.io/js-sequence-diagrams/).

Some other plain text diagram tools I found:
- [PlantText](http://www.planttext.com/planttext)
- [yUML](http://yuml.me/diagram/scruffy/class/samples)
- [David Bushong's shaky diagrams](http://shaky.github.bushong.net)

I haven't found one for flow charts, but good chance one exists, or a tweak of yUML might be enough.

**Comment by smallx** [comment]
-1

**Comment by LongshengDu** [comment]
:+1: I think FlowChart feature would be great. Simple one like `flowchart.js` with Preview is enough.

**Comment by coolgoose85** [comment]
+1 Also look at this 
https://marxi.co

#### Flow charts
```flow
st=>start: Start
e=>end
op=>operation: My Operation
cond=>condition: Yes or No?

st->op->cond
cond(yes)->e
cond(no)->op
```
#### Sequence diagrams 
```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!

**Comment by markchou** [comment]
+1

**Comment by abnerlee** [comment]
Supported in new version -> http://support.typora.io/Draw-Diagrams-With-Markdown/

**Comment by AlexPasternak** [comment]
@abnerlee, I'm just curious, why is support for these features opt-in via Preferences? Is it just to avoid extra processing? I.e., someone is unlikely to type in ​```flow by accident, so why not just always process and support this, vs. requiring someone to check the checkbox first in Preferences (which also requires a restart)?

**Comment by abnerlee** [comment]
flow, sequence and mermaid will be available as auto-complete candidate when user input "```". so user may still create charts (by accident) without knowing how to write a chart if these features are enabled by default.

**Comment by AlexPasternak** [comment]
Isn't that like arguing that Java should be opt-in via Preferences because someone could accidentally type in ```java without knowing how to code in Java? 😊 But OK.

**Comment by pakirby1** [comment]
Unable to get diagrams to work:

I have this:

```sequence
Title: Here is a title
A->B: Normal line
B-->C: Dashed line
C->>D: Open arrow
D-->>A: Dashed open arrow

Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```
and I get the following error:

[Sequence]Parse error on line 1:
```sequenceTitle: Here is a ti
-----------^
Expecting ',', 'LINE', 'DOTLINE', 'MESSAGE', got 'NL'

**Comment by xlicz** [comment]
+1, same error.

**Comment by jleaders** [comment]
This works and I don't know why. I also don't know why Window Cleaning is repeated

\```sequence
Title: Here is a title
MultiIndustry->Window Cleaning: Multi
MultiIndustry->Landscaping:
MultiIndustry->Refrigerator Repair:
\```

**Comment by Spritan** [comment]
I am having some problems with flow chart
```flow
st=>start: Start
op1=>operation: Sum=0
cond=>condition: More cards in Pile 1?
op2=>operation: pick a card X from pile 1
op3=>operation: Move X to pile 2
op4=>operation: Add CardX's Maths Score To Sum
e=>end

st->op1->cond
cond(no)->e
cond(yes)->op2->op3->op4->cond
```
my output
![image](https://user-images.githubusercontent.com/47718224/95683003-35fc5b00-0c06-11eb-8db0-a8dc5d4f3b97.png)
my desired output
![image](https://user-images.githubusercontent.com/47718224/95683023-4ca2b200-0c06-11eb-8765-86ac95e39ee6.png)
