### ISSUE TITLE
URLs are broken with commas or exclamatory, etc

### ISSUE THREAD

**Issue by abarke** [typora/typora-issues#1201]
The following link is broken in Typora, however in Notepad++ this is not the case. Please change it so it doesn't break the link.

Link Example
http://example.com/api/products?search=categoryAttr.keyword:Commodities,partner.name:Thiel

Typora Example
![typora](https://user-images.githubusercontent.com/34715541/35503906-c52eeede-04e1-11e8-9166-1c3cc576d9f5.PNG)

Notepad++ Example
![notepad](https://user-images.githubusercontent.com/34715541/35503911-c97fe7fe-04e1-11e8-878c-1b51076b5df0.PNG)

**Comment by abnerlee** [comment]
Should be fixed in new release.
