### ISSUE TITLE
Typora export as pdf makes Latex look bold and blurry

### ISSUE THREAD

**Issue by Topicaleks** [typora/typora-issues#1203]
![screenshot from 2018-01-29 17-10-17](https://user-images.githubusercontent.com/35730227/35524999-81d5e90c-0523-11e8-8c7e-418f9faf6430.png)

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/594

If you export to HTML, then print it using Chrome, does the output also looks poorly?

**Comment by Topicaleks** [comment]
Looks actually a little better, still bold though... tried different themes, but still bold text.
