### ISSUE TITLE
Support mediawiki-texvc extension for math

### ISSUE THREAD

**Issue by xxf1995** [typora/typora-issues#1204]
Latex symbol $\textvisiblespace$ cannot be rendered

**Comment by abnerlee** [comment]
Supported in new release

**Comment by abnerlee** [comment]
see https://github.com/mathjax/MathJax-docs/blob/v3.1-latest/input/tex/extensions/mediawiki-texvc.rst

It may be unsupported for some time after we upgrade to MathJax v3

relates #3731
