### ISSUE TITLE
ol type detective

### ISSUE THREAD

**Issue by zyyedi** [typora/typora-issues#1205]
Is is possible to auto-detect the type of ol list?
for example: 
if i type: "1.", press enter
it will do:
1.
2.
3.
if i type: "a"
it will do:
a.
b.
c.

**Comment by abnerlee** [comment]
a.
b.
c. 

is not the standard markdown syntax. Maybe become one option in future.

---
close this for duplicated with https://github.com/typora/typora-issues/issues/755
