### ISSUE TITLE
Menu refresh broken

### ISSUE THREAD

**Issue by codingforfun** [typora/typora-issues#1206]
The menu is broken.
The checkmarks in the menu do not represent the real state of the application. 
As an example check the attached screenshot. As you can see Typora is in FocusMode, but this isn't reflected by a checkmark in the menu. Same applies for TypeWriter mode, StatusBar visibility etc. 

![Screenshot](https://user-images.githubusercontent.com/1388003/35557781-77975790-05a6-11e8-819c-d56d8cb5bbee.png)

I noticed, that the menu seams to get updated/refreshed when switching  SourceCodeMode back and forth. Maybe this hint helps to solve the issue.

--- 
Ubuntu 16.04 
Typora 0.9.42

**Comment by abnerlee** [comment]
may relates: https://github.com/electron/electron/issues/10845

**Comment by abnerlee** [comment]
Fixed in new version
