### ISSUE TITLE
Mouse selection and Delete/Backspace not working for Task List Items

### ISSUE THREAD

**Issue by dooof** [typora/typora-issues#1208]
The Delete / Backspace keys are not working properly for task list items.

1.  Select all or part of the task list item using the mouse.  Make sure the selection includes the end of the line.
2.  Click the Delete or Backspace key.  Instead of deleting the selection, it just gets unselected.

This problem only appears to happen when selecting using the mouse, and when the selection includes the end of the line (which unfortunately is typical when trying to delete the entire line).

I also noticed it is impossible to select multiple task list items using the mouse.  I can do this with the keyboard.  Not sure if the two problems are related.

I'm using 0.9.42 on Windows.

**Comment by abnerlee** [comment]
We will fix this in next version up.

**Comment by abnerlee** [comment]
Fixed in new release
