### ISSUE TITLE
how to change comment color in code ?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#121]
<img width="867" alt="2016-04-17 20 17 49" src="https://cloud.githubusercontent.com/assets/10832544/14586887/7f6af99c-04d9-11e6-9b2e-4a8998294ff1.png">

**Comment by waahto** [comment]
The HTML looks like this:
```HTML
<pre>
    <span>
         <span class="cm-comment">/* Remember the Alamo */</span>
    </span
</pre>
```
The class `cm-comment`is defined in `codemirror.css`, but you can probably override it your theme file — at least by using the `!important`;

```CSS
.cm-comment { color: green !important; }
```

**Comment by leewi9** [comment]
Thanks it works!

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 18 2016, at 1:13 pm, waahto &lt;notifications@github.com&gt; wrote:  

> The HTML looks like this:

>  
>  
>     <pre>

>         <span>

>              <span class="cm-comment">/* Remember the Alamo */</span>

>         </span

>     </pre>

>

> The class cm-commentis defined in codemirror.css, but you can probably
override it your theme file — at least by using the !important;

>  
>  
>     .cm-comment { color: green !important; }

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/typora
/typora-issues/issues/121#issuecomment-211205537)![](https://github.com/notifi
cations/beacon/AKVKoEFZS-JrOmMFVz3psldhw_RFoEZnks5p4xL7gaJpZM4IJJnK.gif)

**Comment by abnerlee** [comment]
We will post a document of custom theme in near future
