### ISSUE TITLE
Data loss bugs exacerbated by auto-save!

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1213]
I am working on a long piece, and I was doing some cut-and-pasting and Typora started behaving all funky. A whole section disappeared. I knew it was Typora funkiness as opposed to my user error because when Typora Undo and Redo commands were not symmetrical. When I used Undo to get my text back, it didn't come back. I went back multiple undoes to no avail. But then I did redoes and then it appeared. I don't know how to reproduce this behavior. **But this isn't my point.** 

What is more important is that Typora was autosaving this whole time. I manually save my work to checkpoint known good states of my doc. Now Typora was getting all wonky, with serious content loss, and it was overwriting my known good states!  

This is totally unacceptable! I'm pretty sure it even violates normal macOs expectations. A macOS app is supposed to save it's state somewhere, distinguishing between autosaves and manual saves, so that from the `File` menu I can always `Revert To` `Last Save Version` or `Last Opened Version`. In other words it respects my manual saves, even if I quit the app (without a manual save) and reopen it. I just confirmed this behavior in TextEdit. 

I think it critically important that Typora respect manual saves and not replace them. The last manual save must be kept around somewhere (whatever is the macOs norm).

**Comment by abnerlee** [comment]
I don't think typora will replace manual save states, this may still be bugs about undo/redo.

If the section has been saved before, could you find them in from `Revert To` menu items?

**Comment by vassudanagunta** [comment]
I was emotional when I wrote this (data loss!) so sorry. 

Yes, I'm sure there are undo/redo bugs, as I've encountered them before, but I've never worried about it because I always thought I could go to my last manually save. But in this case it wasn't there. 

No console logs for Typora. Nope, I only use Typora as my markdown editor.  (It's the best)

Don't worry about it. I just lost a paragraph and I rewrote it. Maybe in my going back and forth in undo/redo messed up the Revert option. It's ok. If Typora is already doing the right thing re saves, then that's great. I'm sure you're working on the the undo/redo bugs so again, no worries :)

**Comment by vassudanagunta** [comment]
And I just learned something. I always assumed the Versions option in the Revert menu was time machine, so I didn't bother looking in this case because I don't have auto Time Machine enabled. But macOs saves every few minutes on local disk. I found my lost paragraph. This is great! Thanks for replying so fast. All is good :)
