### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1215]
Hi, there are some problems which may improve the experience if fixed.

1.If I input inline math($), bold(**) and so on, Typora will automatically change the style if then inputting an English character. But when you input Chinese character, it cannot automatically change, unless you type a space, which is eqaul to inputting an "English" character.
![qq 20180204215400](https://user-images.githubusercontent.com/33177912/35778194-ecbd80be-09f5-11e8-86da-77ed91924534.png)
![qq 20180204215322](https://user-images.githubusercontent.com/33177912/35778190-d6a9a05a-09f5-11e8-8804-c468abf576ea.png)

(after type a space, which is the right face)
![qq 20180204215857](https://user-images.githubusercontent.com/33177912/35778248-9f3125ac-09f6-11e8-8c56-7c5ee16e2754.png)

2.When export it to pdf, the tabs are almost deleted.
![qq 20180204215613](https://user-images.githubusercontent.com/33177912/35778231-5f6f61ae-09f6-11e8-8b04-f733bbcfd4d0.png)
![qq 20180204215649](https://user-images.githubusercontent.com/33177912/35778232-60f4639e-09f6-11e8-99e9-4d1188998095.png)
![qq 20180204215708](https://user-images.githubusercontent.com/33177912/35778233-61e8b912-09f6-11e8-8e49-96c70aebf811.png)
(the first is in Typora, the rest are in PDF)
Maybe this is a bug.

3.improve for "quote"
![qq 20180204220226](https://user-images.githubusercontent.com/33177912/35778283-26bfd1e4-09f7-11e8-9e84-0864118dfa73.png)
How to input an Enter between the two?
If I type an Enter directly:
![qq 20180204220234](https://user-images.githubusercontent.com/33177912/35778291-40cfd4f8-09f7-11e8-8877-872e94c42cf2.png)
If I press the ↓:
![qq 20180204220357](https://user-images.githubusercontent.com/33177912/35778300-5a18d4aa-09f7-11e8-97a7-5eee88bb29e6.png)

Maybe “quote” need Ctrl + Enter just like math block.

4.(see the pictures)
![qq 20180204220643](https://user-images.githubusercontent.com/33177912/35778328-c4105888-09f7-11e8-9ac2-45eec33b12e8.png)

![qq 20180204220708](https://user-images.githubusercontent.com/33177912/35778331-c61ec98e-09f7-11e8-9e8e-71b927ae328e.png)

The first is in Typora and the latter in PDF's contents.
Maybe the incompetibility need to be deleted in PDF.

----------

Typora is a great one. I hope more bug fix can make it better and better. Thanks for your check. :)

**Comment by abnerlee** [comment]
> 1

https://github.com/typora/typora-issues/issues/172

> 2

Markdown does not keep space when export, please use `\ ` to represent ` `. For easier editing, we will keep the whitespace as it is on editing mode.

> 3

Similar to other rich editor you could input enter twice.

> 4

Bookmark in PDF is only plain text. If it is footnote, we can remove it in future updates
