### ISSUE TITLE
Symantec EndPoint Protection detects the latest version as Malware

### ISSUE THREAD

**Issue by praveenscience** [typora/typora-issues#1216]
Hey guys, this is definitely an awesome software. I tried installing in my corporate machine (and well, I had to face some bad situation with our Local Tech Support team) and I got this warning! Can this be checked, please? I am using Windows 10 and Symantec Endpoint Protection.

![image](https://user-images.githubusercontent.com/1830380/35798338-616a438e-0a5a-11e8-8c91-3d1617a1a298.png)

Some details from the report:

* **File Name:** typora-setup-x64.exe
* **Risk Name:** WS.Reputation.1
* **Hash:** 8A19A04B865319A50C264F377B56B69BB670A4B897F645CC0984402DE9B4D65F
* **File Size:** 45289192
* **Category:** Malware » Insight Network Threat

I am also attaching the CSV report along with this issue too. Let me know what I should do? I am already using it by disabling my anti-virus in my personal laptop. 😄

Full Report: [Typora-Symantec.xlsx](https://github.com/typora/typora-issues/files/1694604/Typora-Symantec.xlsx)

**Comment by praveenscience** [comment]
Also, I did check with [**Virus Total**](https://www.virustotal.com/en/file/8a19a04b865319a50c264f377b56b69bb670a4b897f645cc0984402de9b4d65f/analysis/1517824858/), but couldn't find any anomalies.

**Comment by abnerlee** [comment]
see https://www.virustotal.com/en/file/8a19a04b865319a50c264f377b56b69bb670a4b897f645cc0984402de9b4d65f/analysis/

You should contact with Symantec EndPoint Protection whenever you have doubts on the scan result. They will check the result and update their db or logic.
