### ISSUE TITLE
Handle indentation and hanging indentation options separately

### ISSUE THREAD

**Issue by KirkMunro** [typora/typora-issues#1217]
As mentioned [here](1188#issuecomment-363901424), hanging indentation and indentation options should be handled separately in Typora.

Today Typora has an **Indent Size on Save** option that can be used to configure how Typora handles indentation. When set to a specific value, Typora does the following:

* automatically applies an indent of the specified number of characters in size to the raw markdown when content is tab indented;
* automatically applies a hanging indent of the specified number of characters in size to the raw markdown used to define lists (ordered and unordered);

I would greatly prefer if these were separate options.

The former is about how markdown renders in places like GitHub, or in Visual Studio Code, or other locations where the Monaco editor is being used. It is necessary in raw markdown to create parent/child relationships between items so that they render properly.

The latter is about prettification of raw markdown, and has no effect over how content is rendered. It is only necessary if you want prettified raw markdown generated behind content you enter into Typora.

Please consider separating these two options from one another so that raw markdown prettification can be disabled unless they want to use it.

**Comment by abnerlee** [comment]
We will change to one whitespace indentation for the later case, as the default option, for example, if indent size if 4:

```markdown
- list
    - sub list

1. list
    2. sub list
```

Because most users use pattern `- `, instead of `-   ` even when the indent size for his/her code is 4.
And after we fix #643, the prefix of a task list will be too long (e.g. `-   [x] a task`) if we keep the old way.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by abnerlee** [comment]
relates: https://github.com/typora/typora-issues/issues/643
https://github.com/typora/typora-issues/issues/1233
