### ISSUE TITLE
Optionally include suffix in ATX headings

### ISSUE THREAD

**Issue by Crissov** [typora/typora-issues#1218]
Each ATX-style heading needs a mandatory prefix of 1 through 6 hash signs `#` (followed by whitespace #329), but they also support an optional suffix of the same kind. Both affixes should use the same number of characters. Typora should offer this style as a third option in _Preferences > Syntax Preference > Heading Style_. 

Variable-width Setext underlines #434 may become a fourth option.

(Aside: I'm proposing to amend CommonMark to [support infostrings for ATX headings](https://github.com/commonmark/CommonMark/issues/500). This would need to be handled eventually.)

**Comment by abnerlee** [comment]
Supported in new release
