### ISSUE TITLE
paged media margins

### ISSUE THREAD

**Issue by bkroggel** [typora/typora-issues#122]
Tried to add some bigger margins on the top of each pdf exported page. As far as I know 

```
@media print {
    @page {
        margin-top: 25mm;
    }
}
```

should do the trick.
Unfortunately that doesn't seem to work out well.
Any recommendations how I could change the margins of paged media?

**Comment by abnerlee** [comment]
yes, this should work

**Comment by waahto** [comment]
Are you sure `@media print` is applied at all? Is `export = @media print`?

**Comment by abnerlee** [comment]
Yes, for windows version, export to PDF will apply `@meida print`, for Mac version I need to confirm, but I think `@meida print` is applied, if not, then it's another bug. 

But currently page `margin` is pre-defined, so the css won't work,  and we will deal with this later.

**Comment by bkroggel** [comment]
Export to PDF will apply `@media print` on the Mac version as well. Works totally like expected.

**Comment by abnerlee** [comment]
> Export to PDF will apply @media print on the Mac version as well. Works totally like expected.

So is this OK to close it if it works as expected?
