### ISSUE TITLE
Fail to export png/jpeg

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1220]
It will export an empty png or jpeg file.
![qq 20180209142015](https://user-images.githubusercontent.com/33177912/36014373-62f22436-0da4-11e8-9631-70ea66edcfc3.png)

**Comment by abnerlee** [comment]
Hi, if possible, could you send us(hi@typora.io) the sample *.md file?

**Comment by abnerlee** [comment]
Fixed in new release
