### ISSUE TITLE
Error default file name when saving new note in source mode

### ISSUE THREAD

**Issue by eugeneyp** [typora/typora-issues#1221]
**Environment**
Windows 10 64-bit
Typora 0.9.44

**Steps to reproduce:**
1. File -> New
2. Toggle into Source Mode
3. Type "Test Header" followed by an Enter
4. File -> Save as
5. Click Save

See error popup:
> Test Header
> .md
> The file name is not valid.

This does not happen when not in source mode.

**Comment by abnerlee** [comment]
Fixed in new release
