### ISSUE TITLE
Add Issue label for `GFM compliance bug`

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1222]
A `GFM compliance bug` issue label would make it easy to see count and list of issues related to Typora's compliance with the GFM spec. This would be greatly useful for prioritization as well as for users to have visibility of Typora's current level of GFM spec compliance. It will be the most effective way to address #369.

I also suggest adding  a couple of people as collaborators to this repo to help you triage issues. People who know the GFM spec. I'd volunteer, and perhaps @Crissov as he too participates in the [development of the CommonMark spec](https://talk.commonmark.org/t/welcome-to-commonmark-discussion/8?u=vas).

**Comment by abnerlee** [comment]
Added two labels for core markdown part (follow GFM) and extended syntax part.

**Comment by abnerlee** [comment]
Yes, it also covers
