### ISSUE TITLE
Fail to center the equation in PDF

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1224]
In PDF, if the equation is too long, Typora will help to make it smaller. But it won't be at the center.

![qq 20180211111259](https://user-images.githubusercontent.com/33177912/36069049-2e4032ee-0f1d-11e8-988e-d91fcf7b7634.png)

**Comment by abnerlee** [comment]
Hi, please send us <hi@typora.io> the sample md file, and what is your Typora/OS version?

**Comment by abnerlee** [comment]
Please reopen this if it still happens in new release
