### ISSUE TITLE
Problem about math in titles

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1225]
If there are an inline math in titles, it won't be outputed correctly when I launch Typora, until typing in the title or changing them. After I type in the title, the problem disappears.
![qq 20180211192315](https://user-images.githubusercontent.com/33177912/36072816-87e09296-0f61-11e8-91a5-6a6548e25d54.png)

Typora 0.9.44
Windows 10 1709 (16299.214)

**Comment by abnerlee** [comment]
Fixed in new release
