### ISSUE TITLE
Language support for Windows Command Prompt (cmd)

### ISSUE THREAD

**Issue by aiingstan** [typora/typora-issues#1226]
I know there is support for `powershell`, but its syntax is a little different from the one of `cmd`. Is there any language suit for `cmd` or any plan to support it?
I've already read the [official supported language list](http://support.typora.io/Code-Fences-Language-Support/), maybe I missed something from there

**Comment by abnerlee** [comment]
Added basic support in new version.

The better support requires CodeMirror support syntax highlight for cmd
