### ISSUE TITLE
Currently selected title is missing from Outline

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1228]
If I am on a line containing title it will disappear from the outline on the left.
The problem is i cannot figure out sometimes where I am anymore (since the section i am is bolded in the outline, except when is missing :) ), and in additional pain with it is in connection with the bug where the text/focus jumping (mostly to the top, and sometimes to the bottom, as already mentioned in other issues)

**Comment by abnerlee** [comment]
What's your Typora version?

**Comment by mprinc** [comment]
Version 0.9.9.12.5 (0.9.9.12.5)

**Comment by abnerlee** [comment]
I cannot make title gone from outline by editing it, if possible, could you send us <hi@typora.io> the sample *.md file and tell us editing which line the title will gone?
