### ISSUE TITLE
macOS CLI support

### ISSUE THREAD

**Issue by nrlquaker** [typora/typora-issues#1229]
Is it possible to add CLI support for macOS?
To be able to open files from command line: `typora /path/to/file.md`
Currently its possible to do:
`/Applications/Typora.app/Contents/MacOS/Typora /path/to/file.md`
but every time using this command new instance of the program opens.
And its not convenient to type full path every time instead of just program name.

**Comment by abnerlee** [comment]
see http://support.typora.io/Use-Typora-From-Shell-or-cmd/
