### ISSUE TITLE
Save window state when closing tabs

### ISSUE THREAD

**Issue by nrlquaker** [typora/typora-issues#1230]
Steps to reproduce:
1. maximize typora window (alt + green button).
2. close typora, open typora - state is saved.
3. Open 2 documents to tabs to appear.
4. Close one tab to tabs to disappear.

Actual result:
Window resizes in height. Height is less for tabs height.

Expected result:
Window stays maximized.

OS: macOS

**Comment by abnerlee** [comment]
should be fixed in new release
