### ISSUE TITLE
Link to header in different local file?

### ISSUE THREAD

**Issue by acccd** [typora/typora-issues#1231]
I tried `[Link](./localfile.md#anchor)`, doesn't work. It only opens the localfile but not scrolled to the anchor. Please help

**Comment by uctdkj** [comment]
What is the correct format for how to open a file and navigate to an anchor point?

**Comment by FreedomFoolt** [comment]
Will this feature be available in the future?

**Comment by abnerlee** [comment]
should be fixed in 1.1
