### ISSUE TITLE
Nested task lists are too indented for GitHub

### ISSUE THREAD

**Issue by darobin** [typora/typora-issues#1233]
Nested task lists make use of six-space indent:

```md
* [ ] Do whatever
      * [ ] Nested thing
```

GitHub thinks it's too indented to be a list and treats it all as if it were just one paragraph, markup and all. If I trim the indent to two spaces, it works as expected.

I tried toggling the list options, the strict option, etc. but it still seems to produce six-indents.

**Comment by vassudanagunta** [comment]
What’s the GFM spec say?

**Comment by abnerlee** [comment]
Tested in this textarea, seams following is correct:

```
* [ ] Do whatever
  * [ ] Nested thing
```

The indent is too much

**Comment by vassudanagunta** [comment]
From my quick read of the GFM spec (https://github.github.com/gfm/#list-items), it looks like Typora is fine and GitHub (or whatever part of GitHub @darobin you are experiencing this) is in the wrong.

**Comment by darobin** [comment]
The GFM spec isn't a model of clarity, but looking at [example 241](https://github.github.com/gfm/#example-241) and the text that precedes it, it would seem that indenting four spaces beyond the start of the list item content (and even for task items my understanding is that the content starts after the space that follows the list marker and not after the task marker) is _precisely_ the way in which one includes a `pre` in a list item.

Testing it here

```markdown
* [ ] One
  * [x] Two
```
* [ ] One
  * [x] Two

versus

```markdown
* [ ] One
      * [x] Two
```
* [ ] One
      * [x] Two

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/643

**Comment by abnerlee** [comment]
Fixed in new release
