### ISSUE TITLE
Outline view improvements

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1234]
The Outline panel is really useful. But it has some quirks that undermine this usefulness. 

## default collapsed state, even with a single H1
Typora's outline defaults to collapsed every time the doc is opened. This is not great if you have a single H1 as the title of the document with H2s as the sections. The outline panel just shows the one H1, with the whole panel below it blank. You have to click on the H1 *every* time you open the document just to see the section titles. 
   
Many people write documents with a single H1 at the top level, both because it is *the* title of the document, and because it is consistent with HTLM best practices.   

Possible solutions:

1. default to first level expanded (not all levels)
2. user configurable default
3. "smart" default: some heuristic to decide how much to expand or collapse the outline by default. For example if the outline panel is mostly empty, expand one level. If it is still mostly empty, expand one more level.
4. auto-expand to track cursor position/scroll (see below). 
5. remember expand/collapse state across doc closing/openings. While this may be desirable, it is harder to implement than the other choices, and you really still need to do one of the other choices anyway so that the first time a document is opened the outline is in a useful expand state. 

## cursor/scroll tracking doesn't work well when outline is collapsed. 

The cursor/scroll tracking in the outline panel is really really useful. It helps you keep track of where you are when editing or reading a long document. But if the cursor is over a section that is collapse, the outline doesn't show you where you are. 

There are really just two options to fix this:

- Highlight the parent heading that is visible in the outline. So if the cursor is in an H3 section but the H3 heading is not visible since its parent H2 is collapsed, highlight the H2. If the H2 isn't visible, highlight its parent, the H1. 
- auto-expand/collapse the outline as the cursor moves so that the heading of the current section is *always* visible.

**Comment by vassudanagunta** [comment]
For default collapse/expand outline state, I prefer `#3` and `#4`. Do `#2` only if too many people don't like 3 and 4. 

For cursor/scroll tracking, I prefer the auto-expand/collapse option. It's really annoying to have to take your fingers off the keyboard to the trackpad/mouse just to see where you are at. Having to do so greatly defeats the purpose of the tracking.

**Comment by vr8hub** [comment]
I prefer #2. I *always* prefer #2; give the user the ability to do what they want, and you don't have to worry about whether they like #3 or #4 or #18. :)

But in addition to a default (or maybe instead, but I would prefer in addition), I would like to see options on the View Menu for changing the outline level. At the very least, there should be Expand All and Collapse All options. I would also include menu items for at least levels 1-3. (I would stick them all on an Outline Level sub-menu, so that it's only one additional item on the View menu.)

**Comment by mikenoethiger** [comment]
You can change between collapsable or expanded outline in Settings/Appearance/Left Sidebar

**Comment by vassudanagunta** [comment]
@mikenoethiger, you misunderstand this issue. It is not about turning collapsibility on or off, it is about how a collapsible outline should be displayed by default when you open a document, and how it tracks your current position in the document.

**Comment by abnerlee** [comment]
currently "#H1" is already expanded by default
