### ISSUE TITLE
The "cut" doesn't work

### ISSUE THREAD

**Issue by dreamchaser123** [typora/typora-issues#1235]
Dear sir, when I  copy sth to typora, there's nothing wrong. But if I cut sth, it totally doesn't work.No matter from another doc or inside the doc, it'll just cut nothing while the left-top button "Edit"  flash a blue light.Thank you~

**Comment by abnerlee** [comment]
Typora/OS version and how to reproduce?

**Comment by dreamchaser123** [comment]
Both are the latest version.Just use "cut", and it didn't respond.But right now it can work again.
