### ISSUE TITLE
Copy/pasting via keyboard shortcuts behaves differently depending on the type of paragraph it takes place

### ISSUE THREAD

**Issue by gutoandreollo** [typora/typora-issues#1236]
## Issue:
When doing cursor movements for copy/pasting, the behaviour of the pasted text changes depending on if it's inside or outside a code block, when it should be consistent.

## Reproduction:
Starting from a document with this Markdown source code:

    this is paragraph one

    this is paragraph two

    this is paragraph three

    this is paragraph four
    
    ---
    
    this is line one
    this is line two
    this is line three
    this is line four
    
    ---
    
    ```
    code block line one
    code block line two
    code block line three
    code block line four
    ```

On "Normal mode" (not "Source code mode"), for each of the three sections above, place your cursor in the beginning of the second line of text, and press the following keys: `[Shift]+[down]`, `[Cmd]+[x]`, `[down]`, `[Cmd]+[v]`. This is what results (source code) of doing so in each section:

### Separate paragraphs:

    this is paragraph one

    this is paragraph three

    this is paragraph two

    this is paragraph four

### Multiple lines in the same block:

    this is line one
    this is line threethis is line two
    this is line four

### Within a code block: 

    ```
    code block line one
    code block line three
    code block line two
    
    code block line four
    ```

**Comment by abnerlee** [comment]
seems fixed in my test
