### ISSUE TITLE
File location lost (and erroneous modified state) after network connection is restored (0.9.44)

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#1239]
When editing remote files (samba over spotty vpn), it sometimes occurs that while I'm away from my desk, the network connection is lost and then comes back later.

If this happens, when I come back to my desk and switch to a Typora window the file will show a modified status in the title bar, even though no modification has actually occurred, and the file is present with the same contents.  Trying to save the file will pop up a My Documents directory, instead of the directory where the file actually is.

My current workaround is to reopen the file from the Windows taskbar jump list, if the file was recently opened, and then to close/discard the previous Typora window, but this loses the undo/redo history.  (Trying to actually browse to the file again in Typora's save dialog is a bit of a non-starter, as the file paths I'm working on are very deeply nested.  I also have to double-check to make sure whether I have _actually_ modified anything or not, to avoid possible data loss.)

It would be nice if Typora did not permanently lose the file's directory location, and it would be even better if it just went back to normal (and not show a false "modified" status) when the network connection comes back up.  (That is, if a file appears again at that location with the old timestamp and current contents, turn back off the modified flag.  And if the directory being monitored stops existing, periodically check for it to come back.)

**Comment by abnerlee** [comment]
Should be fixed in new release.

We follow sublime's spec. File to be write to original location when saving. But if the netdriver is disconnect when saving, a saving dialog will still be popped up.
