### ISSUE TITLE
How to auto number the "outline"

### ISSUE THREAD

**Issue by flyisland** [typora/typora-issues#1241]
Hi all, I now could autonumbering the headings in the body by following [Auto Numbering for Headings](http://support.typora.io/Auto-Numbering/), but not be able to do the same for the outline.

I do create the `base.user.css` file with the raw content from <https://pastebin.com/NYugSbXk>, but nothing happened in the outline. Even I added the following snip into the `base.user.css` file, the second level header is still there in the outline!

```css
.md-toc-h2 {
    display: none;
}
```

So how to auto number the "outline", thanks!

![image](https://user-images.githubusercontent.com/547085/36348232-03538714-14a6-11e8-9cf9-99fe0f368c0c.png)

**Comment by vision-ken** [comment]
+1

**Comment by geosmart** [comment]
+1

**Comment by vision-ken** [comment]
It works! thank you very much!

**Comment by flyisland** [comment]
@abnerlee it works!
