### ISSUE TITLE
Fish syntax support

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#1242]
I can do

```bash
function foo
    echo "hey"
end
```

but I cannot do

```fish
function foo
    echo "hey"
end
```

meaning: there is no syntax highlighting for "fish", but there is for "bash". This is quite a popular shell and it would be really cool if it could be supported.

https://fishshell.com

Cheers and thanks for the great tool! :wink:

**Comment by abnerlee** [comment]
We will support this after codemirror supports `fish` mode. 

Please check https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list for more detail
