### ISSUE TITLE
How to customize shortcut keymap

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#1244]

**Comment by abnerlee** [comment]
see http://support.typora.io/Custom-Key-Binding/

**Comment by Eskander88** [comment]
link don't work!

And I have trouble with assigning shortcut for `Copy File Path`.

Why don't work this instruction: `"Copy File Path": "Ctrl+Shift+Q"` in `C:\Users\%username%\AppData\Roaming\Typora\conf\conf.user.json`? I had error in the syntax?

**Comment by abnerlee** [comment]
https://support.typora.io/Shortcut-Keys/

---

Only items from main menu is supported to assign shortcut keys

**Comment by Eskander88** [comment]
I know about this link. It's don't solve problem. Did you try the examples?

**Comment by abnerlee** [comment]
> Only items from main menu is supported to assign shortcut keys

**Comment by Eskander88** [comment]
This behavior can be upgraded.

**Comment by msksk** [comment]
supporting numpad keys?

**Comment by msksk** [comment]
supporting numpad keys?

**Comment by martyfmelb** [comment]
For those who want keyboard-accessible zoom bindings via the numpad:

```
  "keyBinding": {
    ...
    "Zoom In": "Ctrl+NumAdd",
    "Zoom Out": "Ctrl+NumSub",
    "Actual Size": "Ctrl+Num0"
  },
```

I couldn't find any documentation on this, so I tried throwing guess at the wall until "Num0" worked, then I found "NumAdd", then Googled those two, to eventually discover the actual documentation for the keyboard shortcuts feature (of the Electron software framework).

The full spec for valid key combinations can be found here:
[Electron Accelerators](https://github.com/electron/electron/blob/main/docs/api/accelerator.md)

**Comment by hsandt** [comment]
Looks like command names don't take namespace into account, so File > Export > PDF is just called "PDF". Convenient, but it won't be so if Typora adds more commands later that start with a different sub-menu and end with the same final name (such as Set Default Export Type > PDF). For now at least, I can quickly export repeatedly to PDF (for some reason, on Linux, Ctrl+Alt+P won't work but Ctrl+Shift+P works).
