### ISSUE TITLE
Separate document into pages 

### ISSUE THREAD

**Issue by abdullaahi140** [typora/typora-issues#1245]
Can we have the document separated into pages as an option? Table of Contents could then have headings with their corresponding pages. 

Thanks

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/824 ?

**Comment by abdullaahi140** [comment]
No not really. I meant like how Microsoft Word can have separate content into A4 pages. Each page could then have a page number. These numbers could be referenced into Table of Contents. Right now Typora just has one long continuous page in every document. Could we be able to separate into different pages of different sizes like A1, A2, A3, A4, A4, US Letter etc. ?

![Pages](https://user-images.githubusercontent.com/28843151/36376470-1d0d59f8-156b-11e8-9bcc-442c4e2b417f.png)

![TOC](https://user-images.githubusercontent.com/28843151/36376501-355ef6ec-156b-11e8-85aa-6d00d97857ef.png)

**Comment by fuzzy76** [comment]
Since this isn't really a duplicate, can we have a reopen or a "not gonna happen" on this? :)

As far as I can tell, this is about being able to have page numbers in the TOC.

**Comment by i-Zaak** [comment]
The multiple pages are useful not only for TOC -- paginated multiple column view would also simplify visual navigation of long documents.

**Comment by fuzzy76** [comment]
I doubt that would be feasible. Markdown does not have pages. How your document is paginated depends on what you export it as. Something that is on page 37 when exported to docx might be on another page when exported to pdf, because the exports have their own peculiarities.

**Comment by abnerlee** [comment]
> Since this isn't really a duplicate, can we have a reopen or a "not gonna happen" on this? :)

We don't have plans for "pagination", unless you export the document. We uses HTML/CSS and browser for content layout, but it is a totally new and complex task to support content rendering in pages by our own logic. So we won't consider it in near future.
