### ISSUE TITLE
Why not to use PlantUML?

### ISSUE THREAD

**Issue by edoelas** [typora/typora-issues#1246]
Hi, I would like to know why typora has not implemented PlantUML in order to draw schemes instead of 3 different libraries. Plant UML is style configurable and have more diagrams (and with more options) than mermaid, flowchard and sequence together. Why? Is it too hard? 
Thanks.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1138

**Comment by LastRitter** [comment]
+1
