### ISSUE TITLE
Words seperated when md translate to pdf

### ISSUE THREAD

**Issue by geo-mlin** [typora/typora-issues#1249]
When I export to pdf, I find the words are spitted, something like earthquakes turns to earthquak es, Could you help me to fix it?
By the way, why the pdf by typora is very different to that translated by pandoc?
Thanks!

**Comment by abnerlee** [comment]
@geo-mlin Hi, what's your OS/Typora version and what theme do you use.

Also, could you send us <hi@typora.io> a sample file that can reproduce this?

**Comment by abnerlee** [comment]
Fixed in new version
