### ISSUE TITLE
how to customize img width and height?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#1252]
`![0207ADA6-304C-4472-B836-AA29DEAED38F](../img/0207ADA6-304C-4472-B836-AA29DEAED38F.png =400x)` seems not working

Ref: https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/249
and support.typora.io/Images/
