### ISSUE TITLE
Task list items should always start unchecked

### ISSUE THREAD

**Issue by asherber** [typora/typora-issues#1253]
Using Typora 0.9.44. Let's say I have a task list:

![image](https://user-images.githubusercontent.com/5248041/36433477-99bec3be-162a-11e8-9cd3-05890aafff13.png)

If I hit return after Thing 2, Typora correctly gives me a new unchecked item.

![image](https://user-images.githubusercontent.com/5248041/36433515-b2e42794-162a-11e8-9ed5-3dbd32d9be43.png)

 But let's say I complete Thing 1:

![image](https://user-images.githubusercontent.com/5248041/36433546-c16618ea-162a-11e8-8a84-fd6600b55e4f.png)

And now I need to add 1a, so I put my cursor after Thing 1 and hit return. Typora currently gives me a new item which is already in the checked state.

![image](https://user-images.githubusercontent.com/5248041/36433572-cd395cae-162a-11e8-8ce8-55cf9c637f13.png)

Whenever Typora auto-creates a new task list item, it should always start in an unchecked state.

**Comment by AlexPasternak** [comment]
This is a duplicate, and of a very recent and already open issue. I would suggest searching for existing issues first.

https://github.com/typora/typora-issues/issues/1238

**Comment by asherber** [comment]
My bad, sorry. I was multitasking and forgot to search.
