### ISSUE TITLE
why always scroll to outline title from the top?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#1254]

**Comment by abnerlee** [comment]
Could you add more descriptions? The scroll seems work well in my test.

**Comment by leewi9** [comment]
@abnerlee sorry commander, please check this 

![image](https://user-images.githubusercontent.com/10832544/36772615-dfd23644-1c90-11e8-87e7-ecdaebb66599.png)

**Comment by abnerlee** [comment]
Fixed in new release
