### ISSUE TITLE
Relative URLs are being opened as absolute URLs (0.9.44)

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#1257]
If you have a relative URL e.g. `[foo](foo.md)` and the target file does not exist, Typora launches the URL in a browser.  This is incorrect behavior, since 'foo.md' is not a domain name, and even if it were, this would be inconsistent with browser behavior for the rendered HTML.  (Which would be to display a 404 unless the target file existed.)

If a URL does not begin with a scheme, then it is relative.  If the file referred to by the relative path doesn't exist, then the user should receive an error instead of converting it into a broken absolute URL.  (Which could have other unintended results besides just a browser error message; e.g. causing someone to load malware from a squatted .md domain!)

These issues of course apply to other file types as well, not just .md.  As previously mentioned in other issues, browsers interpret links without a scheme as *relative* to the current URL, so a link like `[foo](foo.com)` will *always* break in generated HTML, so Typora interpreting this as if it meant `http://foo.com` will only keep people from finding out that their link is broken until later.

**Comment by abnerlee** [comment]
Should be fixed in new release.
