### ISSUE TITLE
Future code editing enhancement

### ISSUE THREAD

**Issue by prefersC** [typora/typora-issues#126]
I could envision using Typora as a primary programming editor. Opening a file with an obvious code extension, could place Typora in something similar to code mode, but more like assumed ticks or something, and then inside comment blocks, it could allow markdown. It would make pretty comment blocks, if nothing else.

Forgive me if somebody already made this suggestion.

**Comment by abnerlee** [comment]
Thanks for the feedback. But I think this user case is too narrow.

Mostly user would open source code file with more professional code editor or IDE, and typora is a markdown editor which **only** handlers markdown better than them, however, markdown features seem not to be the primary concerns for users when opening other code extensions.

Besides, comments written in markdown only contains very simple markdown syntax like link, bold, emphasis, raw markdown is pretty readable in this case and pro source code editor may link the comments to functions/parameters, so Typora may not be needed.

**Comment by prefersC** [comment]
you’re right. i doubt i’d dump vim for fancy comments.
