### ISSUE TITLE
OSX - recovering window tabs

### ISSUE THREAD

**Issue by mprinc** [typora/typora-issues#1260]
After quitting and restarting Typora it loses organization of tabs inside the windows.

Tabs/windows are not Typora supported, but OSX native support, but I am sure there is an API to capture them and recover on restart?

Thnaks

**Comment by mprinc** [comment]
It would be also nice to organize in the Window menu tabs in windows, it would be much easier to switch to particular window/tab

![image](https://user-images.githubusercontent.com/996001/36641792-d18724ba-1a46-11e8-8267-482bcdf3649d.png)

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1230
