### ISSUE TITLE
Text frozen for custom IME

### ISSUE THREAD

**Issue by sicilian-lizard** [typora/typora-issues#1263]
Edit: Issue happening again in recent versions (0.9.9.20.3 (1879)).

Sometimes, entered text is frozen, and you can't do anything to it, neither delete, nor cut, copy, not even saving. This is so in the recent releases (0.9.9.11.2, and 0.9.9.11). (maybe related to the IME thing?)

Also I'd like to take the chance to thank Abner. Great work!

**Comment by abnerlee** [comment]
> maybe related to the IME thing?

So did you use any IME, if so, which IME did you use?

**Comment by abnerlee** [comment]
We updated IME support in latest update, could you confirm if this bug is fixed or not in latest version

**Comment by sicilian-lizard** [comment]
The problem is still there.

**Comment by abnerlee** [comment]
If possible, could you send the IME you use to us <hi@typora>? 

I cannot confirm this with some native IME (like Chinese IME) on macOS.

**Comment by sicilian-lizard** [comment]
I'd love to but I believe you won't be able to type with it, at least not long enough to reproduce the issue, as it is not general pinyin or something like wabi so it will require quite some effort to learn.

I will try to figure out how to effectively reproduce the issue - at the moment, it seems rather "random".

**Comment by abnerlee** [comment]
Or does it happens in some specific type of blocks? Like task list, table cell, etc

**Comment by sicilian-lizard** [comment]
No, I don't use other types of blocks that much, only basic paragraph editing, and this happens only in the versions since 0.9.9.11.2.

**Comment by sicilian-lizard** [comment]
More info: when the text freezes, I saved and reopened the file, and I see in it the code for the characters I intended to input, not the characters themselves. Does this help?

**Comment by abnerlee** [comment]
We updated our IME support, please check again on new release

**Comment by sicilian-lizard** [comment]
Will do, thanks!

Happy laboring on labor day!

**Comment by sicilian-lizard** [comment]
IME is working properly.

But sometimes the first letters of a new document freeze (Typora does not accept new inputs, including "delete"). Opening IME at such circumstances usually takes it back to life.

**Comment by sicilian-lizard** [comment]
Seems the issue was solved in the lastest versions.

**Comment by sicilian-lizard** [comment]
Problem solved.

**Comment by sicilian-lizard** [comment]
Problem occurred again, or might not have been solved.

**Comment by sicilian-lizard** [comment]
This happens quite often, but I can't reproduce it.

It seems to me that Typora at a certain point saved the inline text (code before converting to characters), before the conversion/confirmation, and not the text in the text area. I hop you know what I am talking about.

**Comment by sicilian-lizard** [comment]
Now I can reproduce this:

1. Type something (with an IME that comes with the OS), don't commit, meaning, leave the candidate window shown;
2. Leave the computer as such for some time (till Typora auto saves?)
3. Try typing something again, and commit.
4. Try deleting the characters you just typed with backspace. The can't be deleted.
5. Try saving the document and opening it you will find Typora saved the code, and not anything you typed/commited (after the autosave?).

This can be reproduced with the latest version Version 0.9.9.21.1 (1913), on macOs Majove.

**Comment by abnerlee** [comment]
Could you try 0.9.9.22?

**Comment by sicilian-lizard** [comment]
Will do that, thanks!

**Comment by sicilian-lizard** [comment]
Problem solved. I am very happy to close this.
