### ISSUE TITLE
Open Folder in Unibody

### ISSUE THREAD

**Issue by sheldonhull** [typora/typora-issues#1264]
If I'm missing something that is there, please educate me :-) 
As a newer user, I've been exploring relying on typora more for markdown documentation. However, a few of the differences between Unibody and system native on windows makes me flip back to the native to find opens that seem to be missing or difficult to find. 

For instance, I couldn't find anyway to open a folder as a workspace in Unibody mode. I also opened `Files` sidebar, and right clicked and couldn't get any option to open folder.

For improvements. Consider: 
1. Open Folder in Unibody open options. 
2. Right click on files sidebar option to "open folder" as workspace, or maybe like vscode recently added "add folder to workspace" to allow more files to show up in the sidebar. 

Keep up the great work. I plan on blogging on this great find soon. It's beautiful!

**Comment by abnerlee** [comment]
Fixed in new release.

"Open" button in Unibody style can select folders.

**Comment by sheldonhull** [comment]
You rock. I'm really enjoying using this and plan on a blog post soon. If I can get it right I think I'll use for Jekyll writing pretty easily
