### ISSUE TITLE
Files List - Windows Feedback for Improvement

### ISSUE THREAD

**Issue by sheldonhull** [typora/typora-issues#1265]
I like the lines preview for some folders as I can see the content, however, when I'm working on a documentation project, it makes it difficult to navigate/sort through. It would be cool if there was an option to toggle text line preview and otherwise, show just the folder and file names in an intended tree like Caret, Vscode and other due. It's a bit easier to organize a documentation project this way for me personally. 

For example:
![image](https://user-images.githubusercontent.com/3526320/36682926-f00f82ba-1ae1-11e8-83a7-d2d75368af77.png)

With caret i see a listing like this: 
![image](https://user-images.githubusercontent.com/3526320/36683041-2f873fa0-1ae2-11e8-83c2-0cc55caebe79.png)

In comparison I have to sort through the much more verbose list of Typora. Not complaining, just saying the option to provide text might be considered as option to toggle it or see a traditional tree of files. 

![image](https://user-images.githubusercontent.com/3526320/36683137-6ca4b12e-1ae2-11e8-8785-cfa3ebc91151.png)

**Comment by abnerlee** [comment]
We provided a tree mode which you can trigger from menu, or tree icon in bottom
