### ISSUE TITLE
How to open files as tabs on macOS?

### ISSUE THREAD

**Issue by searene** [typora/typora-issues#1266]
I'm using MacOS Sierra, and I heard that opening files as tabs are supported in the os. But how do I do it? When I open a file in Typora, it just opens a new window instead of a tab.

**Comment by AlexPasternak** [comment]
Asked before, please search for closed issues first. E.g., https://github.com/typora/typora-issues/issues/979

**Comment by searene** [comment]
@AlexPasternak It works, thanks!
