### ISSUE TITLE
how about a Typora ICO?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#1267]
create a ERC20 based token called TyporaCoin, sell tokens to all supporters, users can get discount by TyporaCoin

**Comment by AlexPasternak** [comment]
Some background for newbs like me:

* https://support.exodus.io/article/108-what-is-an-erc20-token
* https://blockonomi.com/erc-20-token-guide/

**Comment by abnerlee** [comment]
Looks interesting, but ICO...
