### ISSUE TITLE
Support for more text types in math preview, e.g. \textsc{}

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1269]
Hi,

Could you consider supporting more text styles in the math block preview? See this:

![image](https://user-images.githubusercontent.com/12127864/36757840-d6d1907c-1c12-11e8-9cba-cc3ae34b1cb6.png)

This is how it looks after converting to PDF via pandoc latexpdf:

![image](https://user-images.githubusercontent.com/12127864/36757903-0449cb50-1c13-11e8-9231-9cb235558935.png)

**Comment by abnerlee** [comment]
Math Block use mathjax, and Math Block is used to display math, not for advanced typesetting, so it is OK for not supporting all LaTeX commands that only use for styling texts.

You could post new issues for https://www.mathjax.org/ to make it supports `\textsc`.

Also workaround:

$$
\def\sc#1{\dosc#1\csod}
\def\dosc#1#2\csod{{\rm #1{\small #2}}}
\sc{SMALL} \ 
\sc{CAPS}
$$

**Comment by GandalfSaxe** [comment]
For reference, here is their workaround:

https://github.com/mathjax/MathJax/issues/1940#issuecomment-370381249

These def will not be shown of the Typora preview, and only have to be there once in some math block, and will make it work for the rest of the document.

**Comment by GandalfSaxe** [comment]
..except the code above will give an error when converted with pandoc. The two \def lines have to be in it's own math block for some reason.

If anybody knows why, or if there's a way to keep it all on one math block, I'd be interested to know.

**Comment by GandalfSaxe** [comment]
@abnerlee Is there any other way to change the Mathjax definitions than writing \def's in a mathblock in the document?

**Comment by abnerlee** [comment]
This will be discussed in https://github.com/typora/typora-issues/issues/100

**Comment by abnerlee** [comment]
@GandalfSaxe The above seems working for me:

e.g:
```
\def\sc#1{\dosc#1\csod}
\def\dosc#1#2\csod{{\rm #1{\small #2}}}

\begin{aligned}
\sc{SMALL} \\ 
\sc{CAPS}
\end{aligned}
```

Could you post the LaTeX code that does not work?

**Comment by GandalfSaxe** [comment]
That works for me too. Thanks.

**Comment by GandalfSaxe** [comment]
Ugh never mind. It works fine inside Typora, but when I try to convert to pandoc, it gives the following error:

```
! Illegal parameter number in definition of \sc.
<to be read again>
                   1
l.102 \def\dosc\#1\#2\csod{{\rm #1

pandoc: Error producing PDF
```
