### ISSUE TITLE
Installation Error libconf-2.so.4

### ISSUE THREAD

**Issue by sagnikb** [typora/typora-issues#1270]
I followed the instructions for installing Typora on Ubuntu 17.10, and after going through all the steps, Typora refuses to open. On attempting to run it via command-line, I get the following error:

`typora: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1268

**Comment by abnerlee** [comment]
Try install `libgconf-2.so.4` first
