### ISSUE TITLE
A bug about symbol "#" in source code mode 

### ISSUE THREAD

**Issue by bescks** [typora/typora-issues#1273]
The comment symbol "#" in a code block(python) is considered as Heading 1
<img width="461" alt="screen shot 2018-03-01 at 16 21 09" src="https://user-images.githubusercontent.com/28510750/36852666-957b7a2e-1d6c-11e8-8ae5-68032d6f2d20.png">

**Comment by abnerlee** [comment]
What's your Typora version? Seems I cannot reproduce this in my local.

**Comment by bescks** [comment]
Mac OS 10.13.3, Version 0.9.9.12.5
Well, seems like it is caused by another code block.
The first code block in the following screenshot  has indent. So typora fails to parse "```" in the beginning of the third code block.
<img width="468" alt="screen shot 2018-03-02 at 13 11 35" src="https://user-images.githubusercontent.com/28510750/36898695-337bdf98-1e1c-11e8-9edb-a33ab30c983e.png">

**Comment by abnerlee** [comment]
merge into #314
