### ISSUE TITLE
Shortcut for task list

### ISSUE THREAD

**Issue by mavlutovr** [typora/typora-issues#1274]
Hi!
How can I set shortcut for "Task List"?
I know about conf.user.json, but I dont know, what I can write for solve this.

**Comment by bescks** [comment]
Well，you can make it just through mac os setting
System Preference → Keyboard → Shortcut → App Shortcuts → click button “+” 

<img width="228" alt="screen shot 2018-03-02 at 15 34 21" src="https://user-images.githubusercontent.com/28510750/36903872-3f60547a-1e2f-11e8-8be4-3bf507c715ea.png">

like the above picture shows, input "Task Lisk" into Menu Title and set shortcut you preferred 
Actually, you can do in this way for all kinds of shortcuts in all apps.

**Comment by mavlutovr** [comment]
Well, it's good :)
But, how can I do it on Ubuntu?

**Comment by abnerlee** [comment]
see http://support.typora.io/Custom-Key-Binding/

**Comment by longhaiqwe** [comment]
@abnerlee The webpage is no longer available.

**Comment by longhaiqwe** [comment]
oh, maybe it's changed to https://support.typora.io/Shortcut-Keys/

**Comment by RitaZ-A** [comment]
try this:
-[ ] and add return
