### ISSUE TITLE
Avoid adding unicode characters to fenced code blocks

### ISSUE THREAD

**Issue by hyphz** [typora/typora-issues#1275]
I have discovered that Typora will add unicode characters, such as non-breaking or zero-width spaces, to text within fenced code blocks.

Since fenced code blocks would commonly be cut and pasted into text editors or programming tools, this is extremely inconvenient, as the invisible unicode characters will break most compilers and cause errors or alerts in many IDEs.

Could the system please avoid inserting unicode formatting characters within code blocks?

**Comment by abnerlee** [comment]
Examples when zero-width spaces will be inserted?
