### ISSUE TITLE
Feature: Hash Tags / Symlinks System

### ISSUE THREAD

**Issue by devcline** [typora/typora-issues#1276]
I red about this [reply](https://github.com/typora/typora-issues/issues/525#issuecomment-368585630) and really loved the idea about symlinking a paragraphs or even the files . Instead close, search and open , you can click and view. Is it even possible ?

Thanks

**Comment by vassudanagunta** [comment]
@devcline Follow/star [Markaround](https://github.com/Markaround/markaround)... I'm going to try and push for this via a standard :)
