### ISSUE TITLE
Shortcut to reorder list items and tasks

### ISSUE THREAD

**Issue by Tonvdpol** [typora/typora-issues#1278]
I would like to propose a shortcut to reorder list items and tasks.

The idea is to place the cursor in the line and then to be able to move the line up with **Command-up** (on the Mac) and down with **Command-down**.

This makes it more easy to move finished tasks to the bottom of the list.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/151

**Comment by vassudanagunta** [comment]
Something as rare and context specific as re-ordering table rows should never take such an important keyboard shortcut as CMD-up/down. This combo is already used by nearly all apps for some type of scrolling behavior. It should stay that way.
