### ISSUE TITLE
Abbreviations support

### ISSUE THREAD

**Issue by reflog** [typora/typora-issues#128]
Any chance for acronyms/abbreviations support? Like: http://talk.commonmark.org/t/abbreviations-and-acronyms/890

**Comment by abnerlee** [comment]
```
The <abbr title="Hyper Text Markup Language">HTML</abbr> specification is maintained by the W3C.
```

Is already supported in new release

**Comment by abnerlee** [comment]
#2448

**Comment by nsrosenqvist** [comment]
@abnerlee There's a syntax for abbreviations in [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#abbr) but there is no syntax highlighting for it in Typora. Would you consider adding it?

**Comment by abnerlee** [comment]
#2448 lists syntax for other "uncommon" markdown specs, since they are not in widely used, we will consider them **after ** v1.0
