### ISSUE TITLE
Unable to enter the web site -- https://typora.io/

### ISSUE THREAD

**Issue by wangrui97** [typora/typora-issues#1281]

**Comment by wangrui97** [comment]
![image](https://user-images.githubusercontent.com/25810228/37012044-a4241576-212d-11e8-92cc-d8bf88447ef3.png)

**Comment by abnerlee** [comment]
Maybe an issue for your IPS.

checked in https://www.uptrends.com/tools/uptime, the site is not down

![image](https://user-images.githubusercontent.com/1621242/37012336-239b99b8-212f-11e8-895e-e33f90446df1.png)

**Comment by wangrui97** [comment]
@abnerlee  thanks! It works out.It's my duty. 💇
