### ISSUE TITLE
Bug: Additional \ when inserting {{ variables with | }} inside Table (Jekyll Tag)

### ISSUE THREAD

**Issue by flikteoh** [typora/typora-issues#1282]
<img width="620" alt="screen shot 2018-03-06 at 14 40 49" src="https://user-images.githubusercontent.com/1472065/37017716-95e228d0-214c-11e8-9bc3-56e2e64a8f40.png">

Typora source code mode when inserting {{ tag | example }} inside table cell.

An additional "\\" was automatically added, thus generating errors in Jekyll site generation.

**Comment by abnerlee** [comment]
Table and Liquid  are not standard markdown syntax.

In table header "|" shouldn't appear, or else it will be parsed as cell splitter, so Typora will auto escape "|" in table cells. A possible workaround is to save the modification insource code mode.

But this do bring a problem for Jekyll users when they use such syntax in table. So we will consider how to avoid this

**Comment by flikteoh** [comment]
Noted that. Thanks for the prompt respond.

**Comment by vassudanagunta** [comment]
@flikteoh I am not the developer, but @abnerlee is. So he decides whether or not to grant your wish, not me! I’m just pointing out the nature of your wish. 

My only ask of Abner is Typora always support pure GFM without compromise. *Optional* extensions on top are great, though preferably per #1223. In this case #1223 can’t be satisfied but so many people use Jekyll so maybe it is worth making an exception.

@abnerlee maybe you can provide a user configurable way to set `custom extension delimiters`. So in this case Jekyll users could add `{{` and `}}`. Typora would not modify or parse anything between the `open` and `close` delimiter, treating it as plain text not part of the markdown. If you like this idea I can open an issue describing it more.

**Comment by abnerlee** [comment]
@vassudanagunta Sure.

For jekyll case, it seems it will use both `{{ site.baseurl }}` and `{% post_url /subdir/2010-07-21-name-of-post %}`

**Comment by flikteoh** [comment]
@vassudanagunta Thanks for the heads up.
Additional supports for different static-site-generators would be awesome for different use cases.

However I seem to have missed out that the "|" is used throughout table for markdown source. Which seems to be why Typora escaped it automatically as pointed out by @abnerlee 

If there'll be support for that it'll be great for us, the Jekyll users. If there isn't, it still seems fine for me as we could also rework on our plugins to use `{% tag { key: data, key2: data} %}` instead.

It would seem too much trouble for @abnerlee if I was the only few with such use cases. Totally understood.

**Comment by vassudanagunta** [comment]
@flikteoh Did you see my idea? #1288

**Comment by flikteoh** [comment]
@vassudanagunta Yes I did. Was just saying if Typora has support for that, it'll definitely be great.
