### ISSUE TITLE
Typora gets really slow when file gets large

### ISSUE THREAD

**Issue by xxf1995** [typora/typora-issues#1285]
Typora gets really slow when a markdown file gets really large. 
I am taking notes with Typora. The markdown file has about 3k words  and lots of Latex math expression and now it's getting really slow to type.
Typing Maths formula in Latex gets particularly slow.

**Comment by xxf1995** [comment]
System is macOS 10.13.3 (17D102)
![image](https://user-images.githubusercontent.com/8936233/37107608-6109acec-21fa-11e8-9676-3eff7d3ae3bc.png)

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/68

**Comment by abnerlee** [comment]
@xxf1995 Hi, if possible, could you send the sample file to <hi@typora.io> for us to check?

**Comment by xxf1995** [comment]
@abnerlee Sure!
[Archive.zip](https://github.com/typora/typora-issues/files/1795024/Archive.zip)

**Comment by Minderer** [comment]
@abnerlee  Why is this closed? The problem still exists.

**Comment by Denly** [comment]
Hi, this is a paid user who really loves Typora. I got the same issue here. For larger files, it is so slow to a point that can't be used. My file is mixed with English, Image, Mandarin. I tried other Markdown editors that don't have this issue. Hope this can be resolved. Thanks!

**Comment by Amelioratede** [comment]
mine as well

**Comment by TheMTtakeover** [comment]
Also having this issue

**Comment by rkingery** [comment]
Also having this issue. It seems to be directly related to using a lot of math expressions. When documents full of math get longer than say 2-3 pages things slow down considerably. I've found no way to fix this other than force quit and relaunch, which only sometimes works, and only for a few minutes.

**Comment by poult-lab** [comment]
Me too, I am encountering this problem now as well. Can anyone recommend another editors which don't have this issue?

**Comment by TheMTtakeover** [comment]
@poult-lab obsidian seems to handle large files much better but I still prefer the UI and workflow of typora

**Comment by poult-lab** [comment]
> @poult-lab obsidian seems to handle large files much better but I still prefer the UI and workflow of typora

Hello friend, I don't why the obsidian is not working on my Ubuntu system.

**Comment by zichenzhang04** [comment]
I encountered the same issue :(

**Comment by thb584Git** [comment]
Same here (Win10)
Loved Typora so far, but now a file with 22k words (no math, just multiple links, code, an local pictures). The interface is that slow I googled for "Typora slow interface" and ended here. Not the answer I hoped. :( 
Deativated spell check seems to help to some degree but is not a solution.

**Comment by Rubrasum** [comment]
I cannot believe I paid for a markdown editor and it has problems somehow.

**Comment by Rubrasum** [comment]
~~I am experiencing the same issue. Editing is very slow. My file is 11380 words.~~
Very embarrassing. I was on version 1.7 but have updated to latest 1.10. Not seeing the problem at all. Very sorry to disturb you. 
╏ , ͡° ╭ ͟ʖ╮ ͡° , ╏
