### ISSUE TITLE
Clipboard issues

### ISSUE THREAD

**Issue by joakimc** [typora/typora-issues#1286]
I can't describe this issue properly as it's difficult to reproduce. However one way to reproduce this is to do the following:

1. Paste this into Typora:

```
some text

> Something quoted.

some text
```

2. Select the quoted text.

3. Press Ctrl ^ (Ctrl Shift ¨ on my Norwegian keyboard)

Result: Selected text is lost, both from Typora and its undo history.

https://imgur.com/an2yiTx

Sometimes the text is still present in source code mode, but not visible in live preview.

It seems to happen due to other actions too, however I haven't been able to pinpoint these.

**Comment by joakimc** [comment]
Typora 0.9.9.12.5
OSX El Capitan 10.11.6

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by pconrad-fb** [comment]
I have the same issue, Linux, Typora 1.0.3, just lost some very important notes.
