### ISSUE TITLE
Key bindings with unicode characters do not work (0.9.44)

### ISSUE THREAD

**Issue by MikeWW** [typora/typora-issues#1287]
When setting custom key bindings via conf.user.json this works:
`  "keyBinding": {
    "Code Fences": "Ctrl+Shift+l"
  },
`
but this does not:
`  "keyBinding": {
    "Code Fences": "Ctrl+Shift+ä"
  },
`
and neither does
`  "keyBinding": {
    "Code Fences": "Ctrl+Shift+\u00e4"
  },
`

I ensured that the conf file was saved as UTF8 with no BOM and Typora was restarted after the conf file was saved.

Typora 0.9.44
Windows 10
Swedish keyboard, English display language.

( Many thanks for an excellent editor :-) )

**Comment by abnerlee** [comment]
unicode characters may not supported, you may use ascii key instead, for example `"Ctrl+Shift+Alt+a`
