### ISSUE TITLE
Justification and font size are not WYSIWYG when exporting

### ISSUE THREAD

**Issue by neo-anderson** [typora/typora-issues#1292]
Hi, big fan of Typora here! Amazing work!

When I export to PDF, fonts look bold and blurry. I read in an earlier solution that the best way to export is to export to HTML and use Chrome/Safari to export to PDF (Not working in Firefox for some reason).

Although it looks sharp when exported this way, the fonts are larger and the justification is wonky. For example, more words fit into Typora's live preview (smaller font) and this affects the number of lines, the way big words/urls in the text are split, etc.

In some cases, it's even worse. If there are not enough words to fill the line, the exported pdf contains sentences like this -
<pre>Hello         this          is            an              example.       Not          enough           
words.to.fill.the.above.line.com/some-big-url-in-this-line. Hope that helps.</pre>

Is it possible to get a WYSIWYG export? I'm testing with Github theme.

Thank you

**Comment by abnerlee** [comment]
Seems OK in my test,

What's your Typora/OS version? Could you give us a sample file or code snip?

Which theme do you use, did you add any custom CSS?

**Comment by abnerlee** [comment]
may relates: https://github.com/typora/typora-issues/issues/1249

**Comment by neo-anderson** [comment]
I downloaded writing.css theme. I customized it a lil bit. Other than that, I haven't changed anything. I tested with unmodified Github theme too.
Typora 0.9.9.13.4
MacOS Sierra 10.12.6

Github Theme (Inside Typora)
<img width="1147" alt="github theme inside typora" src="https://user-images.githubusercontent.com/7310004/37382154-7aa7a4ac-26fe-11e8-9c1e-1b0f32030513.png">

Github Theme (PDF Export from Chrome)
<img width="941" alt="github theme pdf export from chrome" src="https://user-images.githubusercontent.com/7310004/37382153-7a8e04e8-26fe-11e8-8a2f-6c9cc088971d.png">

Writing Theme (Inside Typora)
<img width="880" alt="writing theme inside typora" src="https://user-images.githubusercontent.com/7310004/37382157-7ad9847c-26fe-11e8-9331-1f6b013ce1ce.png">

Writing Theme (PDF Export from Chrome)
<img width="939" alt="writing theme pdf export from chrome" src="https://user-images.githubusercontent.com/7310004/37382155-7ac284fc-26fe-11e8-93dd-9720086faaf9.png">

Source Markdown
[Test.md.txt](https://github.com/typora/typora-issues/files/1809492/Test.md.txt)

**Comment by neo-anderson** [comment]
And check this justification and spacing issue.

Inside Typora
<img width="739" alt="justification inside typora" src="https://user-images.githubusercontent.com/7310004/37382935-d7ddd296-2702-11e8-975e-fe76e549cffe.png">

PDF Export. Check the last line
<img width="886" alt="justification pdf export from chrome" src="https://user-images.githubusercontent.com/7310004/37382934-d7c66f70-2702-11e8-8009-edeb602d9fee.png">

Source MD
[Test.md.txt](https://github.com/typora/typora-issues/files/1809554/Test.md.txt)

**Comment by neo-anderson** [comment]
I just realized that in the last two screenshots, the text is slightly different. But hope it's clear from the images what the issue is. Do you need more info?

**Comment by abnerlee** [comment]
I see, PDF export for Typora on macOS is backed by webkit/Safari

So what's your Safari version? Have you update Safari to latest version? I cannot reproduce this 

If you export to HTML, then print in Safari, can it be prevented?

Also, we added the options for whitespace/line break in preference panel in 0.9.9.14, please choose "preserve whitespace and line break when export" in preference panel.

**Comment by abnerlee** [comment]
OK, I found some related bug

**Comment by abnerlee** [comment]
Fix long link in export in new release.

For line break, it should be configured as "Preserve whitespace and single line break" in preference panel

**Comment by neo-anderson** [comment]
It worked. Thanks a lot :)
