### ISSUE TITLE
Safari harmed by using Typora

### ISSUE THREAD

**Issue by cbertelli** [typora/typora-issues#1294]
It seems strange, but after opening Typora on MacOS, my links on Safari do not work anymore, I need to right-click (or ctrl-click) them to open the contextual menu.
This is especially true for Gmail and Google apps. Should I blame Electron?

**Comment by abnerlee** [comment]
Typora won't have the ability/permission to change settings of Safari. 

Maybe this https://discussions.apple.com/thread/7540607 will help

**Comment by cbertelli** [comment]
You are obviously right. I don't think Typora does change settings, I just observe a reproducible behaviour, maybe tied to my old system (MacOS 10.9) and consequently old browser, but this is not a "settings problem"; if I restart Safari this behaviour disappears, if I start Typora I get it again. Maybe it's not Typora, probably Electron has something more to do with it, another maybe unrelated symptom is that I still get menu item that don't work the first time and obey the second call... Anyway thank you for the suggestion about Safari, it's a useful thread.
