### ISSUE TITLE
Download Image to Folder

### ISSUE THREAD

**Issue by vanhelmont** [typora/typora-issues#1295]
Hello,

I'm trying to use an URL to show the image, but I want to download the URL's image to a local folder.

Por example,

I'm with a text with some imagens, like https://www.google.com.br/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png.
And I expecting the image of the URL automatic download to a folder in my local machine, preference with the same name as original.

I already read about local images to move to a folder, but nothing about remote URL, have some clue or trick?

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/875
