### ISSUE TITLE
First line margins

### ISSUE THREAD

**Issue by szepeviktor** [typora/typora-issues#1297]
Hello!

Could you square up the marked distance of the first line? The vertical one could match the horizontal.

![1st-line-square](https://user-images.githubusercontent.com/952007/37254034-e857db50-2539-11e8-984d-670b65331880.png)

**Comment by Fastidious** [comment]
I believe that is driven by the CSS theme used. Simply modify or create a theme that does it.

**Comment by szepeviktor** [comment]
After reporting the issue I've tried with no avail.

**Comment by abnerlee** [comment]
This requires CSS modification, see http://support.typora.io/Add-Custom-CSS/

**Comment by szepeviktor** [comment]
@abnerlee Thank you.
I've tried to adjust `body, #write` etc. but was not able to shrink that distance.
Could you help?

**Comment by Fastidious** [comment]
@szepeviktor the theme you modified, did you pick it as selected one?

**Comment by szepeviktor** [comment]
Sorry.
DevTools are available with <kbd>F12;/kbd>
