### ISSUE TITLE
Scrollbar automatically jumps back to the top of the document

### ISSUE THREAD

**Issue by MarkWithall** [typora/typora-issues#1299]
If I leave Typora open but unused for a while in Source Code Mode (I haven't tried in normal mode), the scrollbar will eventually jump back to the top of the document.

Version 0.9.44 running on Windows 10 Pro

**Comment by MarkWithall** [comment]
Looking around a bit, it is possible this coincides with the autosave timer.

**Comment by abnerlee** [comment]
Please check new updates, it should be fixed.

BTW, do you write files on a network drive or on local disk?

**Comment by MarkWithall** [comment]
Thanks. In the case I was testing, it was to a network drive.
