### ISSUE TITLE
Support image references with width/height attributes

### ISSUE THREAD

**Issue by kontrafiktion** [typora/typora-issues#13]
I would love to see images references:

```
 ![devtest-context][]
 ...
 [devtest-context]: devtest-context.png width=396px height=57px
```

this would allow me to add width/height attributes for images (for multimarkdown)

**Comment by marten-seemann** [comment]
+1

**Comment by anandgraves** [comment]
+1

**Comment by pgolebiowski** [comment]
+1, though not sure if the syntax above is best. Also, using `%` instead of `px` could also be sometimes helpful.

**Comment by abnerlee** [comment]
#249

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/249
