### ISSUE TITLE
Images with file names containing apostrophe characters do not load consistently 

### ISSUE THREAD

**Issue by prefersC** [typora/typora-issues#130]
Can force image to load briefly by switching path setting

**Comment by tartyphoenix** [comment]
it's not the problem of typora, the image is just a url. 
maybe you can use picture storage service for your .md file, or you can export your file in pdf type.
unless Typora maintain a File System itself, but i think it will betray the essence of Typora.

**Comment by abnerlee** [comment]
It is typora's bug when handling image url contains quotes, we will fix it in next version up.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by tartyphoenix** [comment]
## when i change mode to source code mode, it will be all white
like[](http://7xr5hb.com5.z0.glb.clouddn.com/blank.png)

**Comment by abnerlee** [comment]
@tartyphoenix that is a serious bug. Sorry for that

Could you open the click "enable debug" from menu bar, then right click writing area, click "Inspect Elements" and switch to "console" tab and send the console log to me <hi@typora>

Aslo. would you switch to "Elements" Tab, select the html dom and copy/paste to me?

If possible, could you tell me how to reproduce it, like which operation did you do? any clues are welcomed. Thanks for your feedback.

**Comment by tartyphoenix** [comment]
@abnerlee i am not sure about the situation.
once Typora push the update for me, and i accept it, but i interrupt the downloading. 
then it happens , even i update it manually.
but now it have been settled, when i download a new one.
I hope you got what i say, i am a coder from china, i just read, can not express fluently

**Comment by abnerlee** [comment]
@tartyphoenix Thanks for your info.

So it happens during your update process, and not happened again after you download a new one, am I correct.

> I hope you got what i say, i am a coder from china, i just read, can not express fluently

If you feel it uncomfortable to express your ideas in English, please feel free to contact us via Email(<hi@typora.io>), we also speak Chinese :)
