### ISSUE TITLE
Typora hangs when inserting a line break before a table

### ISSUE THREAD

**Issue by Aiesnow** [typora/typora-issues#1300]
Hey, I think this bug causes a memory leak because typora becomes unresponsive while memory usage is rocketing. It happens on windows 10 with typora 0.9.44.

To reproduce the bug, the cursor needs to be to the left of the entire table, then press enter.

**Comment by abnerlee** [comment]
Fixed the *hangs* in latest version.

And move caret in that position is not allowed
