### ISSUE TITLE
Error when I attpemted to export to epub

### ISSUE THREAD

**Issue by byDave251** [typora/typora-issues#1301]
When I try to export to epub and my document have online images then shows messege: "Export failed. Failed to export to ... couldn't read native.

**Comment by abnerlee** [comment]
Could you send us <hi@typora.io> a sample *.md file ?

**Comment by byDave251** [comment]
@abnerlee You can see example here (I don't want to send you a e-mail): https://bydave.net/elektronika/Bipol%c3%a1rn%c3%ad%20tranzistory.md

**Comment by kaze12** [comment]
I am having the same issue, though with Media Wiki.
