### ISSUE TITLE
Typora insert image didn't after upgrade to 0.945

### ISSUE THREAD

**Issue by jacquen** [typora/typora-issues#1302]
Hi, Support

I upgrade my  Typora to ver 0.945 on windows 7, but seems insert image doesn't work as before, if I paste image directly into MD file, it didn't show anything in MD file after paste, but image file saved into folder as I point to. When I try to insert image from menu it doesn't work as normal (show me the link info). 

Please  help, thanks.

**Comment by abnerlee** [comment]
Copy/Paste does not work, but drag and drop works?

**Comment by jacquen** [comment]
Thanks quick responding, this need be fixed.

**Comment by abnerlee** [comment]
We will fix this soon

**Comment by abnerlee** [comment]
Please check updates for v0.9.46
