### ISSUE TITLE
Problems with new `Insert Images` option

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1303]
This new option (#875) is much needed (thank you), but it has some problems. The first one is a serious problem.

1. The new behavior is good for web images, but is **bad for local images**:
    - It unnecessarily duplicates local image files already in the folder or subfolder of the Markdown file. Such local images should not be copied. 
    - It makes it harder to share images across Markdown docs. Every drag and drop of a local image results in a new copy.
    - There is no way to turn off the rules for local images.
    - BUG: It duplicates files already copied per the rules. 
        - For example, set it to `Copy image to ./assert`, drag a web image to a Markdown file, then drag the image in the `./assert` folder to the Markdown file. There will now be two images in the `./assert` folder.
        - This bug would automatically be fixed by *Desired Behavior for Local Images* below.

    Please see *Desired Behavior for Local Images* below.
2. `./` (same folder) should be a rule option. 
3. Should be "asset" not "assert". 
4. I don't see any difference whether `Also apply above rules for online images` is checked or unchecked. The rules are applied to images dragged from remote web pages always. Maybe I don't understand what this option is? Please see _Desired Option Settings_ below.

### Desired Behavior for Local Images

1. If the dragged or pasted image is already in the **same folder** as the Markdown file, it should use that image and **should not** copy the image according to these rules. 
2. If the dragged or pasted image is already in a **sub folder** the Markdown file's folder, it should use that image and **should not** copy the image according to these rules. 
3. If the dragged image is in any other local folder, the rules for local image insertion should be followed (see below).

### Desired Option Settings

To configure image insertion, Typora currently has one `Images Insert` rules drop-down + `Also apply above rules for online images` in Preferences, and  `Edit → Image Tools → When Insert Local Images` in the menu.

It would be simpler, more flexible and easier to understand by replacing the above with just **two separate** `Image Insertion` rules drop-downs for local and web images:

Local image rule choices (above *Desired Behavior for Local Images* always applies):

- `Link to existing image`
- `Copy image to same folder`
- `Copy image to front-matter specified folder`
- `Copy image to "asset" subfolder`
- `Copy image to <filename>.asset subfolder`
- `Upload image to iPic`

Web image rule choices:

- `Link to web image`
- `Copy image to same folder`
- `Copy image to front-matter specified folder`
- `Copy image to "asset" subfolder`
- `Copy image to <filename>.asset subfolder`
- `Upload image to iPic`

I am not sure about the utility of `Save pasted images in temp folder if needed`. Why would anyone choose this?

**Comment by abnerlee** [comment]
`Save pasted images in temp folder if needed` is the default action, it will use the old typora logic.

Only when users paste a image content into the file, Typora will try to save the image file.

**Comment by vassudanagunta** [comment]
But why would anyone ever choose for it to be in a temp folder?

**Comment by AlexPasternak** [comment]
Agree that temp folder is the most likely place to lose images, that looks like a dangerous option for users who would expect their images to persist long-term.

I came into this thread to ask why the folder was called "assert", but @vassudanagunta has already beaten me to it:
> Should be "asset" not "assert".

The other typo is in "automatically" in settings.

<img width="303" alt="screen shot 2018-03-13 at 10 42 02 am" src="https://user-images.githubusercontent.com/1819485/37348717-35fff370-26ab-11e8-9116-73f4b316ba44.png">

**Comment by abnerlee** [comment]
Main issue here are fixed in v0.9.9.13.6, please check update.

Includes:
- Fix typo of `assets`.
- Rephrase from "Save pasted images in temp folder if needed" to "No special action" as default value, to avoid user's confusing.
- Fix bug image will be copied again when insert image from target folder.
- Add options to decide whether local images should be copied or not.

Therefore, I will close this issue here. Please open new issues or other related bugs/requirements.

**Comment by AlexPasternak** [comment]
@abnerlee You closed this issue, but the other typo I mentioned was not fixed in the latest. See screenshot above, where "automatically" is misspelled.

**Comment by yifengyou** [comment]
I need the function to save image into specific folder not assets !!! fix this,please.

**Comment by BlkPingu** [comment]
I wish iPic was abandoned completely and Imgur would be used as standard image host.
There is no reason to pay 10$/year for iPic to "allow" us to use a free image host.
All there is to it is to add an image host to Typora with a login field. Can't be that hard.
