### ISSUE TITLE
IME - wrong candidate window position

### ISSUE THREAD

**Issue by sicilian-lizard** [typora/typora-issues#1304]
When typing near the end of a line and the original code (say, pinyin) begin to wrap to the next line, the candidate window does not appear right below the code, but one extra line below the starting position of the original code, and sometimes several lines below, and may jump up and down if you continue to type (when non-alpha code is present, in some IMEs).

This can be reproduced using the system provided Pinyin IME, but it won't happen to TextEdit, Notes, MS Word, Scrivener, CotEditor, so I guess it might be a Typora issue.

**Comment by abnerlee** [comment]
It is still be a little bit hard to understand this issue, if possible, could you provide a screenshot or screencast?

**Comment by sicilian-lizard** [comment]
Fixed. Thanks.
