### ISSUE TITLE
Direct-select heading levels no longer work from menu/shortcut (0.9.46 on Win x64)

### ISSUE THREAD

**Issue by repentsinner** [typora/typora-issues#1306]
Hi Abner, I'm seeing some strange heading manipulation behavior in the latest Typora 0.9.46 on Windows 10 x64 build 17115.

Directly selecting a heading from the menu or using a key shortcut doesn't seem to work; directly editing markdown syntax does, as does `increase` and `decrease` level relative adjustments. Other formatting such as **bold** or *emphasis* still seems fine from the menu/shortcut. This worked in 0.9.xx (possibly 0.9.44?) earlier today, but I auto-updated to 0.9.46 and the change seems to correlate with the update. I'm not sure how to roll back to an earlier build to confirm, the [build history](https://typora.io/dev_release.html) seems a little out of date?

Let me know if there's anything else I can do to help you repro or isolate.

See the following screencast:

![typora select multiple heading](https://user-images.githubusercontent.com/4462072/37362502-9650c310-26b2-11e8-91e9-f6a46aa8577a.gif)

Thanks for considering!

**Comment by abnerlee** [comment]
We will fix this soon

**Comment by abnerlee** [comment]
Should be fixed. Please check new updates or re-download latest version from our website
