### ISSUE TITLE
Failed to Copy Image to Target Folder - Download timeout

### ISSUE THREAD

**Issue by liquidblasted** [typora/typora-issues#1308]
Ver. 0.9.46(beta)

1) Select any option other than "No special action" in Image Insert in Preferences;
2) All 3 checkboxes on;
3) Select and copy some text with picture from any website and paste it to Typora;
4) Getting an error: Failed to Copy Image to Target Folder. Download timeout

Reproduced in Win10 x64 with Chrome, Edge, IE browsers

**Comment by abnerlee** [comment]
Could you provide an URL of image?

Where did the *.md file locates? Does Typora has write access to that folder? Could you also provide the path of the *.md file?

**Comment by liquidblasted** [comment]
Hi, I realised that this error happens ONLY if you copy-paste pictures with Text (like when you want to save an article from web), not only 1 picture itself. 
When you copy just one pic from the web - it shows you the dialog where to copy image (btw there is a small typo, pls see in attach)), and it's downloading OK.

![2018-03-14 12_52_48-clipboard](https://user-images.githubusercontent.com/3716019/37395173-a9d30900-2786-11e8-95d2-4b348f5c4923.png)


I can reproduce the error on 2 different PCs, for the example:

e:\1\2.md (2.md created with Typora, full access to directory)

It happens with any website, for example, you can try to select some text together with pics from this article:
https://www.techradar.com/how-to/how-to-install-a-vpn-on-amazon-fire-tv-and-fire-tv-stick

and copy-paste it.

**Comment by abnerlee** [comment]
Should be fixed. Please check new updates or re-download latest version from our website

**Comment by liquidblasted** [comment]
I confirm it works now. Thanks a lot!
