### ISSUE TITLE
Error: invalid argument, fstat

### ISSUE THREAD

**Issue by Geliv** [typora/typora-issues#1309]
After updating the typora, I encountered the following error. How to solve this?? Many of my files cannot be opened 😭

![image](https://user-images.githubusercontent.com/20089973/37393518-44a8d9b2-27ac-11e8-868a-c94f2242e6de.png)

System: Windows 10
Typora: 0.9.46

**Comment by Geliv** [comment]
PS: The files are synced with Onedrive.

**Comment by abnerlee** [comment]
Relates https://github.com/typora/typora-issues/issues/972

Seems to be a regression bug for electron

**Comment by Geliv** [comment]
@abnerlee Many thanks to your reply. Any quick fix for this??

**Comment by abnerlee** [comment]
see https://github.com/electron/electron/issues/11570

Need wait for Electron's next update. 

See https://github.com/Microsoft/vscode/issues/27285#issuecomment-309270189 for hot fix on your side

**Comment by Geliv** [comment]
Disabling the "Files on demand" feature may introduce other problems, for instance, I don't want some of the files stored on the desktop be synced to my laptop again. So the best for me now is rolling back to the version 0.9.44 until the problem is fixed. 

Looking forward to the fix!

**Comment by abnerlee** [comment]
We updated Electron which should fix this bug

**Comment by Geliv** [comment]
Many thanks!! I updated typora, the problem is indeed fixed.
