### ISSUE TITLE
Footnotes & HTML exports

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#131]
Footnotes are semantically incorrect when exporting to HTML

**markdown**

``` markdown
This is explained in [^footnote].
Extra info in [^here].

[^footnote]: Explanation
[^here]: Elaboration
```

**HTML**

``` html
<p>This is explained in <sup><a href='#dfref-footnote1' name='ref-footnote1'>1</a></sup>.</p>
<p>Extra info in <sup><a href='#dfref-here2' name='ref-here2'>2</a></sup>.</p>

<div class='footnotes-area'>
    <hr>
    <div class='footnote-line'>
        <span class='md-fn-count'>1</span> Explanation<a name='dfref-footnote1' href='#ref-footnote1' title='back to document' class='reversefootnote' id="dfref-footnote1">↩</a>
    </div>
    <div class='footnote-line'>
        <span class='md-fn-count'>2</span> Elaboration<a name='dfref-here2' href='#ref-here2' title='back to document' class='reversefootnote' id="dfref-here2">↩</a>
    </div>
</div>
```

There's a **bug** when using "Copy as HTML" — footnotes don't get wrapped in `<div class='footnotes-area'>`

**Issues**
- Extra horizontal rule
- No rel attributes
- Semantically messed up footnote list.

**Target:**

``` html
<p>This is explained in <sup><a href='#fn-1' id="rfn-1" rel='footnote'>1</a></sup>.</p>
<p>Extra info up there <sup><a href='#fn-2' id="rfn-2" rel='footnote'>2</a></sup>.</p>

<ol class='footnotes'>
    <li id="fn-1"><p>Explanation</p><a href="#rfn-1" rel="footnote">&#8617;</a></li>
    <li id="fn-2"><p>Elaboration</p><a href="#rfn-2" rel="footnote">&#8617;</a></li>
</ol>
```

**Reasons**
1. Much smoother markup!
2. `rel='footnote`is semantically correct and it makes possible to target footnotes in CSS : `sup a[rel="footnote"] {}`
3. This is now distinguishable from a non-footnote link that someone might want to add to `sup`.
4. Using an ordered list is semantically correct way to display the footnotes. It takes less markup and provides a handy way to target the link using `#id`. Because the footnote can span many lines, it's best to target the _beginning_ of the footnote, rather than the "go back" symbol at the end.
5. Using paragraphs in the footnotes because footnotes can contain multiple paragraphs.
6. Using `&#8617;` over the unicode symbol might be preferred(?)

**Comment by abnerlee** [comment]
may conflicts with https://github.com/typora/typora-issues/issues/1163

**Comment by abnerlee** [comment]
Close since we now support custom scripts and css to format footnotes as you want, and making footnotes `<li>` would let it be affected by the CSS style for `<li>` in current theme.
