### ISSUE TITLE
Unsolved problem about math equations in [TOC]

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1312]
I found that although the equations will be showed in a correct way in the content when launching Typora, there is still some abnormal forms in exported PDF:

![2](https://user-images.githubusercontent.com/33177912/37407901-de16971e-27d5-11e8-88f0-a2fa206cc0f7.png)

I exported this PDF when I see the content showed correctly, but the \$ didn't disappear.

Typora: 0.9.46
Windows: Windows 10 1709 (16299.309)

**Comment by abnerlee** [comment]
Should be fixed in new release
