### ISSUE TITLE
Task list items incorrectly marked after upgrade to 0.9.46

### ISSUE THREAD

**Issue by smattingly** [typora/typora-issues#1315]
After upgrading to 0.9.46, typora renders some task list items marked (checked), contrary to the file contents. See the discrepancies marked in red below.
![bad](https://user-images.githubusercontent.com/21227171/37410635-6a30f366-2777-11e8-998d-2503cebffc22.png)

The following image (different PC, same file, synced through Dropbox) shows that the problem did not appear in 0.9.44.
![good](https://user-images.githubusercontent.com/21227171/37410864-de64c12c-2777-11e8-9c53-b90d35afe21d.png)

**Comment by abnerlee** [comment]
Should be fixed. Please check new updates or re-download latest version from our website
