### ISSUE TITLE
synchronize folder with online driver or GitHub-like online repositories

### ISSUE THREAD

**Issue by ahban** [typora/typora-issues#1318]
Dear all,
I am using `Typora` to make notes. I hope I can see my notes when I am not in the front of my computer. Is that possible to add a function to update all markdown files in an opened folder to an online driver, such as  [Google Drive](https://drive.google.com) ,  [Baidu Pan](https://pan.baidu.com/) for people in China, personal GitHub repository, etc. 

For example, add an item in the right-click menu, say `update to server`. And we can manually add some commands for this item. As an example, 
```
git add .
git commit -a -m "update"
git push
```

Also, when `Typora` exits, the opened folder will be automatically updated.

Regards, 
Ben

**Comment by abnerlee** [comment]
close for above reasons.

For data syncing, you could use sync service that can sync files automatically, like Google Drive or Dropbox. Typora can work them with without extra configurations.

Custom context menu can be considered if we start to support #162 or more publish options, but that may not be planned in near future.
