### ISSUE TITLE
Typora adding indentation to code fences in lists

### ISSUE THREAD

**Issue by jhildenbiddle** [typora/typora-issues#132]
I've noticed a recurring issue where Typora indents text within code fences that are nested inside of lists. For example, this content in markdown:

1. Some text

   ```scss
   @import "path/to/file";
   ```

Will be turned into this unintentionally:

1. Some text

   ```scss
     @import "path/to/file";
   ```

It's a visual nuisance most of the time but a becomes a show-stopper when documenting code that relies on indentation such as Stylus or CoffeeScript. The behavior is inconsistent but occurs often enough that it has repeatedly caused issues when updated README files to GitHub and NPM. The only way to address the issue so far is to edit the file manually in another application.

This issue appears to have been introduces within the last two releases (I'm currently on 0.9.9.2.1). I'm not certain of this though since the behavior is inconsistent. Perhaps I was just lucky with other documents.

Thanks!

**Comment by abnerlee** [comment]
Hi, could you post markdown source code contains the list item with indented code blocks, so we can re-produce the bug from your snippet ?

**Comment by jhildenbiddle** [comment]
Sure thing. Raw source is here: 

https://raw.githubusercontent.com/jhildenbiddle/vertical-rhythm-reset/master/README.md

I created this README in Typora but I had to manually fix the extra indentation added by Typora with Sublime Text before pushing to GitHub.

To reproduce the issue:

1. Copy the source from the URL above.
2. Open Typora and switch to "Source Code Mode"
3. Paste the source into Typora
4. Notice the additional two spaces inserted at line 59 (for a total of five)
5. Strangely, notice that the list items that follow (2&3) were indented the same way but are do not have extra spaces added.

Manually removing the extra spaces and saving the file still results in the source containing the extra spaces. You can confirm this by making the adjustment and then viewing the markdown source in another app.

Hope this helps.  Let me know if there's more I can do on my end to track down the issue.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by jhildenbiddle** [comment]
Thanks for the fast turnaround, @abnerlee !
