### ISSUE TITLE
Enter Newly Created File Upon Creation

### ISSUE THREAD

**Issue by sheldonhull** [typora/typora-issues#1321]
If a user clicks to create new file from the folder view, and names the new file, upon hitting enter/changing focus to save the file it should open up in the window.

**Comment by abnerlee** [comment]
Now, it will enter newly created file if current document is an empty un-edit document

**Comment by sheldonhull** [comment]
I've not had a ton of time to write in a dedicated editor like this (been using prose for jekyll blogging lately due to time), but man I love this so far. Hopefully, when I get time I can write up more about for others, but in the meantime, just wanted to say keep up the great work!
