### ISSUE TITLE
Auto-Complete quotes behavior adjustment suggestions

### ISSUE THREAD

**Issue by sheldonhull** [typora/typora-issues#1323]
If I'm at the end of a word with whitespace following my cursor, typing `"` or "'" should not create a quote pair. 

This results in: `typing example'` next word turning into `typing example'' next word`
Instead I suggest: 

## if cursor at end of word
`typing example'`  does not autoclose quotes - results in `typing example' next word`

## if selection highlighted (bracket represents selection)
`[typing example] next word`  upon press of quote would encapsulate the selected text in quotes resulting in `'typing example' next word`
This behavior is what vscode and sublime-text typically do and provides a smooth editing experience when editing previous written text.

**Comment by abnerlee** [comment]
> If I'm at the end of a word with whitespace following my cursor, typing " or "'" should not create a quote pair.
> [typing example] next word upon press of quote would encapsulate the selected text in quotes resulting in

This is our current spec, what's your Typora version?
