### ISSUE TITLE
Scroll to cursor position when moving it

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1324]
Sometimes you need to refer to something elsewhere in the document, but then come quickly back to where the cursor is to continue writing. In most editors, this is usually achieved the easiest by simply moving the curser a little with one of the arrow keys. Unfortunately, Typora doesn't automatically scroll unto the curser position when it's moved.

Perhaps you could look into this?

**Comment by abnerlee** [comment]
On which OS?

**Comment by GandalfSaxe** [comment]
macOS. But actually now trying again, it does scroll to the cursor position. Perhaps it was a one-time bug.

I can just close this one now and comment again if it ever happens again.
