### ISSUE TITLE
Auto-pair should work with backtick (grave accent)

### ISSUE THREAD

**Issue by tucknology** [typora/typora-issues#1326]
In Markdown, the backtick or grave accent (`) is used for inline code. I use it a lot. 

Here's an example using the backtick for inline code:

---

In C++ you can write `x = x + 1;` or `x++;` and they both do the same thing.

---

It would be great if auto-pair would work with the backtick the same way it works with quotes ""  parenthesis () and square brackets [ ] already. To be clear, I'd like to type some words, then highlight them, then touch the ` key, and the backticks would automatically appear on both sides of the highlighted text.

**Comment by abnerlee** [comment]
You could enable "auto pair markdown characters" in preference panel

**Comment by tucknology** [comment]
Hi @abnerlee thanks for your reply.

I think you might consider allowing this to be controlled by "Auto pair brackets and quotes" instead of "auto pair common markdown syntax".  

Personally, I have "auto pair common markdown syntax" disabled because of #844, that's why I'm running into trouble.
