### ISSUE TITLE
Font size affected by total screen resolution

### ISSUE THREAD

**Issue by rjeady** [typora/typora-issues#133]
I sometimes switch between using a single 1440p resolution monitor, and two monitors (side-by-side) where the second has a resolution of 1080p.

I've observed that Typora makes the font size much larger when both monitors are connected. I'm assume it detects my total resolution being very large, supposes I have a very large high-dpi screen, and attempts to support this by zooming in.

This is totally incorrect behaviour and is quite frustrating. Can it be fixed?

**Comment by rjeady** [comment]
I de-minified the code and found where you try to determine a zoom factor from the monitor size. This clearly doesn't work very well for multiple active monitors. Can't you just provide a custom zoom setting instead?

**Comment by FelixHerz** [comment]
I face the same behaviour using three monitors.

**Comment by abnerlee** [comment]
Can this still be reproduce in our latest version? Please reopen this if it still exists.
