### ISSUE TITLE
Window positions itself on second screen without second screen attached

### ISSUE THREAD

**Issue by MelleDijkstra** [typora/typora-issues#1332]
**Specifications:**
OS: Windows 10
Typora version: 0.9.47 (beta)

**Issue:**
The window positions starts in a (previous setup) second monitor, however, this may be an issue of windows.

**Reconstruct:**
1. Start the application and move it to a second monitor
2. Go into hibernate mode
3. Disconnect the second monitor
4. Start windows again from hibernation

![525f743f-d537-4ae6-932c-ea4083113341](https://user-images.githubusercontent.com/8669499/37565742-e5c06a68-2aae-11e8-922e-7580059c06a4.gif)

**Comment by abnerlee** [comment]
From your screencast, the second screen seems not correctly disattached. 

The opened app on this screen would have highlight/shadow in taskbar.
