### ISSUE TITLE
Upgrade mermaid

### ISSUE THREAD

**Issue by renegare** [typora/typora-issues#1334]
Hi,

Is there a road map or any plans to upgrade the version of mermaidjs in your application. You are currently using v6. I looked into how to possibly upgrade it to v8 (which is possible ;) but not released yet: https://github.com/knsv/mermaid/issues/642) but would be obviously better if this is something you guys could do.

The main reason for this request is because the mermaid v6 has a missing feature in their gnatt charts which allows one to format the x-axis. `axisFormat %d . %m`.

This is the resolved issue / commit that I am after: https://github.com/knsv/mermaid/pull/624

Your thoughts would be greatly appreciated. If there is an interim solution I would be grateful too.

Best,

M.

**Comment by abnerlee** [comment]
updated to v8.0.8 rc6 in latest release
