### ISSUE TITLE
Focus mode, different text-colors and CSS

### ISSUE THREAD

**Issue by admin-teametry** [typora/typora-issues#1336]
Hello,

I read the explanation about CSS on focus mode.
and I want to distinguish the text-color between normal text and blockquote i.e. How to do that? 
With this

```
 .md-focus,
  .md-focus-container {
    /* for text in current focused block */
    color: #111;
  }
```
all text get this color and overwrites my color setting without focus mode, but I want the same colors in every mode.
I'm thankful for any hint :-)

Andreas

**Comment by abnerlee** [comment]
`.md-focus` will be put to current line
`.md-focus-container` will be put to current blockquotes or list item or table row. `.md-focus-container`  contains `.md-focus`, so strictly,  `.md-focus` is the current focused block.

For your request, please try
 .md-focus {
    // normal text in focus
  }

blockquote .md-focus {
 // blockquote text in focus
}
