### ISSUE TITLE
Ctrl right arrow sends cursor to the end of the document rather than end of paragraph

### ISSUE THREAD

**Issue by DaegL** [typora/typora-issues#1338]
When I use the combination of ctrl right arrow towards the end of a paragraph (second to last word), it sends my cursor to the end of the document instead of the end of the paragraph. I had to scroll up every time I do that.

Any idea how to fix it? Thanks!

I'm on Windows 10

**Comment by abnerlee** [comment]
Tested in v0.9.49, seems already fixed.
