### ISSUE TITLE
Multi-line code fencing in a list.

### ISSUE THREAD

**Issue by joirn-pettersen** [typora/typora-issues#1340]
In Typora, it's really awkward to create a list with code fencing.
An example:
````markdown
1. blah blah blah
   ```java
   System.out.println("blah blah blah");
   ```
2. blah blah
````
If you type '1. blah blah blah', and press enter, it creates a new item in the list. If you then type '[BACKTICK][BACKTICK][BACKTICK]' and add press enter it creates a code fence with item number two, e.g. '2. [BACKTICK][BACKTICK][BACKTICK]'. This is alright, except now if you want to remove '2.', you can't. Typora doesn't let you select '2.', so you have to go into the code to edit it.

**Comment by abnerlee** [comment]
You could use up/down key to leave the code block.

Or what's your expected method to move to `2.` ?
