### ISSUE TITLE
Saving not work

### ISSUE THREAD

**Issue by pp2moonbird** [typora/typora-issues#1342]
Press `ctrl + s` to save the file and then close close file.

Reopen the file but all the changes are not saved.

**Comment by abnerlee** [comment]
Typora/OS version? Where is the save location, on local disk or in network driver.

Could you send logs to us <hi@typora.io> http://support.typora.io/Report-Bugs/#Logs ?

Any specific ways to reproduce this?

**Comment by abnerlee** [comment]
Thanks for the quick reply

Could you send logs to us hi@typora.io http://support.typora.io/Report-Bugs/#Logs ?

**Comment by pp2moonbird** [comment]
after checking the log file, found a few errors:

```
ERROR 2018/3/21 下午5:38:48  [RenderProcess 1][Error] fs write failed
ERROR 2018/3/21 下午5:39:15  [RenderProcess 1][Error] fs write failed
ERROR 2018/3/21 下午5:41:13  [RenderProcess 1][Error] fs write failed
```

**Comment by abnerlee** [comment]
Will Typora show something like "save failed"?

Where is the save location, on local disk or in network driver?

**Comment by pp2moonbird** [comment]
no message showing "save failed".

the file is store on local disk.

**Comment by abnerlee** [comment]
Could you send logs to us hi@typora.io http://support.typora.io/Report-Bugs/#Logs ?

**Comment by abnerlee** [comment]
Should be fixed in new release

And if error happens, Typora will tell you when save failed and prevent window from being closed.
