### ISSUE TITLE
Mermaid flowchart bug?

### ISSUE THREAD

**Issue by MalteBartels** [typora/typora-issues#1343]
In mermaid flowchart diagrams, dotted lines are not working correctly.
```mermaid
graph LR;
A-.->B;
```
`A-.->B;` should produce a dotted line between A and B, but there is just a regular line. 

Am I using it wrong or is it an issue?

**Comment by ronfromkwon** [comment]
I have the same problem: edge formatting does not seem to work: `-.->` does not produce a dashed line with an arrowhead,  `===` does not produce a thick line.
Also it is not possible to add any markup within a node (for example `eg[<b>bold</b><br/><tt>examle</tt>]` should display as 
<b>bold</b>
<tt>example</tt>

These work correctly in the online editor (https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbmVnWzxiPmJvbGQ8L2I-PGJyLz48dHQ-ZXhhbWxlPC90dD5dIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRhcmsifX0)

**Comment by abnerlee** [comment]
Fixed in new release
