### ISSUE TITLE
Printing:  cryptic caracter

### ISSUE THREAD

**Issue by regexgit** [typora/typora-issues#1344]
Windows 10, typora 0.9.47

Substring "fi" (lowercase) tranformed in cryptic caracter at printing.

Example for 
```
#Files
config.json
#Set of files
```
![img_20180321_0003](https://user-images.githubusercontent.com/37620014/37707302-00bc617c-2d03-11e8-9929-812b62146bc9.jpg)

**Comment by bschuth-alphce** [comment]
Just confirming that this is in fact a defect, I'm reproducing it constantly.

**Comment by abnerlee** [comment]
Do you use default printer or 3rd part printer?

see https://github.com/typora/typora-issues/issues/1441

**Comment by regexgit** [comment]
Direct local printing on Canon MG66000
Just install 0.9.49:  fixed, printing OK

**Comment by regexgit** [comment]
I spoke too quickly, on another document there are plenty of anomalies, in addition to the cryptic characters there are lines and words that disappear.

The only way to print is to go through an export pdf.
