### ISSUE TITLE
Custom Style of Flowchart doesn't work

### ISSUE THREAD

**Issue by pdcxs** [typora/typora-issues#1345]
I tried this in typora:
```mermaid
graph TD
	root("a")-->|Action A|step11("b");
	root-->|Action B|step12("c")
	step12-->step21("d")
	step12-->|Action B|step22("e")
	step22-->step31("f")
	step31-->|Action A|step41("g")	
	step41-->|...|step61("h")

classDef node fill:#9f6,stroke:#333,stroke-width:2px;
```

But it doesn't work.

The same code works well on the mermaid online editor:
![tim 20180321222531](https://user-images.githubusercontent.com/3760797/37715380-da1f5ad4-2d56-11e8-8f19-ab47e1903559.png)

In typora, it looks as following:
![tim 20180321222531](https://user-images.githubusercontent.com/3760797/37715440-fd832c80-2d56-11e8-9f31-16accda0ec0f.png)

**Comment by abnerlee** [comment]
Fixed in new release
