### ISSUE TITLE
[Feature Request] Configurable image path, Doc library management

### ISSUE THREAD

**Issue by imageslr** [typora/typora-issues#1346]
Hello, I am a severe markdown user. I love typora and its UI, but it will be greater if has following features:

1. Configurable image path. Now typora has four options for image, including "{$filename}.assets".  If can set the path with variable, such as "{$filename}.images", "media/{$filename}.images", it would be wonderful.

2. Doc library management. Every time I close the window and reopen, I have to choose my file again. Could typora remember my doc library and restore my work space?

Thank you.

**Comment by abnerlee** [comment]
> Configurable image path. Now typora has four options for image, including "{$filename}.assets". If can set the path with variable, such as "{$filename}.images", "media/{$filename}.images", it would be wonderful.

You could use YAML to set image path, or from menubar `Edit` -> `Image Tools` -> `When insert images` -> `Copy yo folder..` to set path per file.

> Doc library management. Every time I close the window and reopen, I have to choose my file again. Could typora remember my doc library and restore my work space?

We have plans for this. This request should be duplicated with existing issues

**Comment by JohnWalkerx** [comment]
I've searched for the same feature to configure the image path.
In my case, the app I use on iOS (Notebooks) puts images in `./NBImages`. 

> You could use YAML to set image path, or from menubar `Edit` -> `Image Tools` -> `When insert images` -> `Copy yo folder..` to set path per file.

With YAML `typora-copy-images-to: ./NBImages` it works fine.
But 
- I have to set this for every (new) file. Not so comfortable.
- most other editors doesn't support YAML and show/export it

But it would be so useful to apply it as a general setting.
e.g. a textinput field in settings to set a custom name for the directory.

**Comment by abnerlee** [comment]
> Doc library management. Every time I close the window and reopen, I have to choose my file again. Could typora remember my doc library and restore my work space?

This is supported in new versions.

> 1. Configurable image path. 

merge to https://github.com/typora/typora-issues/issues/1471, since the later one is an independent request

**Comment by imageslr** [comment]
Thank you @abnerlee !

**Comment by cuiwm** [comment]
install hexo-typora-image firstly, add meta fileld: typora-copy-images-to: {{title}}  in {{title}}.md, it works fine
