### ISSUE TITLE
Separate FrontMatter from the content

### ISSUE THREAD

**Issue by daveaglick** [typora/typora-issues#135]
Since so many static site generators (including Jekyll) have the concept of FrontMatter (metadata that's separated from the Markdown by a delimiter), it would be great to treat the FrontMatter separately from the content. Even if it’s just showing FrontMatter in the Source Code Mode (or even better, as raw text). Right now it’s awkward to switch between the two.

(Sent this as an email, but just found this issues list so I'm copying here)

**Comment by abnerlee** [comment]
Display FrontMatter from a separated panel will make it not so convenient to edit and new users may feel difficult to understand the logic between this panel and the markdown source.

Besides, I couldn't found much merits by doing this, unlike static site generators, typora doesn't have better knowledge to analyze FrontMatter, even it is displayed separately, it will still be treated as plain text
