### ISSUE TITLE
Print with Default Theme - Need to change the default theme

### ISSUE THREAD

**Issue by githubusersb** [typora/typora-issues#1350]
Somewhere the default theme for printing is setup as Github. Need an option to change the default printing theme so that dark theme document can be exported to PDF using the selected default theme.

**Comment by abnerlee** [comment]
This is a current workaround. Merge into https://github.com/typora/typora-issues/issues/1248 since the laster one is key solution

**Comment by githubusersb** [comment]
Hi,

Could not understand why this is closed.
What is the way of changing default theme?

Thanks,
Sudipta

**Comment by abnerlee** [comment]
No, but shouldn't we print using the current theme?

**Comment by githubusersb** [comment]
Yes. But when the theme has dark background, it is throwing a confirmation
popup for printing with default theme. When I say Yes, then it prints using
github theme, always.

I want to change that default theme from github to something else.

Thanks,
Sudipta

**Comment by abnerlee** [comment]
So it should be fixed by  #1248

**Comment by githubusersb** [comment]
Where is the solution for that issue?
