### ISSUE TITLE
base64 image use variable will disappear after export pdf

### ISSUE THREAD

**Issue by fcying** [typora/typora-issues#1354]
I tested two ways to insert a base64 image
```
![bbb](data:image/jpg;base64,/9j/4A...

![aaa][image1]
[image1]:data:image/jpg;base64,/9j/4...
```
When I use typora preview, two images can be seen.
![image](https://user-images.githubusercontent.com/106934/38026430-a11b4906-32be-11e8-85e1-25bd1cc2a917.png)

When I export to pdf, only `bbb image` can be seen.
![image](https://user-images.githubusercontent.com/106934/38026450-b57f1ee0-32be-11e8-87d0-9e59882ef94d.png)

typora version: 0.9.47(beta) windows

[test.md.txt](https://github.com/typora/typora-issues/files/1854401/test.md.txt)

**Comment by abnerlee** [comment]
tested in 0.9.48
Should be fixed
