### ISSUE TITLE
Enhancement: colorful Emoji

### ISSUE THREAD

**Issue by chenwq3** [typora/typora-issues#1357]
Typora does support emoji, but it's not colorful.

for example:
:smile: in typora: ![smile](https://user-images.githubusercontent.com/25943138/38018205-cd9ec01a-32a6-11e8-9fe8-a9c52d394704.png)

:smile: in github: 😄

If export it info a pdf, it's show "![smile](https://user-images.githubusercontent.com/25943138/38018205-cd9ec01a-32a6-11e8-9fe8-a9c52d394704.png)" is ok. But when it in typora, colorful might be better, more vivid.

**Comment by abnerlee** [comment]
Emoji in Github is using pictures, while Emoji in Typora is a unicode char, different font may render it differently.

For colorful emoji on windows, you may refer to
https://answers.microsoft.com/en-us/windows/forum/windows_7-start/color-emojifont-support-on-windows-7/8010df8b-c628-4d2d-8cad-24b7bec8c444
or
https://superuser.com/questions/1062418/how-do-i-replace-windows-10s-emoji

**Comment by chenwq3** [comment]
With input method(chinese), I can type colorful emoji.

![emojis](https://user-images.githubusercontent.com/25943138/38064934-4381ab26-3333-11e8-8582-c75f4be9d1ec.gif)

I saved that document, and open it with notepad++ with UTF-8 encoding, 
![emojis](https://user-images.githubusercontent.com/25943138/38064982-7c7d3652-3333-11e8-9e82-b30b6f789d4c.png)

I don't know how typora show a utf-8 character as 😄 , but not for `:smile:`.

Is it worthwhile to continue to "dig" that up?

( behavior in linux is not been test. )

**Comment by abnerlee** [comment]
Which IME did you use?

**Comment by chenwq3** [comment]
> Which IME did you use?

Microsoft Pinyin

Below information shows how you install it on Windows 10:

1. Goto settting `Region & language`, click `Add a language`,  then `Chinese (Simplified)`, then `Chinese (Simpified, China)`
2. Wait for it finished, go back to page of "Region & language", You can see `中文(中华人民共和国)`, click it , it will shows  "Options" button. Then click `Add a keyboard`, click `Microsoft Pinyin`

**Don't set it as Display language**

![qq 20180329155210](https://user-images.githubusercontent.com/25943138/38076763-2e0a95d8-3369-11e8-82ae-abc5abb0eb57.png)


After finishing installation. ` Windows Logo + Space` to switch chinese language.
like this ![qq 20180329155452](https://user-images.githubusercontent.com/25943138/38076864-95bdcefc-3369-11e8-9d35-b2a6199a71aa.png).

If it shows "英" ![qq 20180329155501](https://user-images.githubusercontent.com/25943138/38076887-a52f59d2-3369-11e8-9299-a96e9936253b.png), you need to press Shift key to swich "中" to type chinese.

Here is some pinyin to type emoji
 - `haha` for 😄
- `ku` for 😭
- `hua` for ❀
- `gou` for 🐶

**Comment by chenwq3** [comment]
Also here:

![qq 20180402101336](https://user-images.githubusercontent.com/25943138/38180356-91fecbc0-365e-11e8-993a-7b04702a0fc2.png)

**Comment by abnerlee** [comment]
Seems recent update of Windows already support colorful emoji, we will use its default colored emoji

**Comment by abnerlee** [comment]
Fixed in new release.

If anyone want go back to monocolor emoji, he can set in advanced settings.

**Comment by chenwq3** [comment]
God speed.

**Comment by Julianoe** [comment]
How can we get the colorful emojis on Linux Ubuntu then? :1st_place_medal:

**Comment by uggyuggy** [comment]
Hi, 

I had first the same problem with black and white emoji in some (not all) apps on my Linux Mint (Ubuntu)

![image](https://user-images.githubusercontent.com/1720008/86535959-4e145e00-bee4-11ea-907c-ee33de843f75.png)


I followed instructions on https://victor.kropp.name/blog/emoji-on-linux/  then after restarted Typora all was OK

![image](https://user-images.githubusercontent.com/1720008/86535836-6b94f800-bee3-11ea-9edf-7576d0d0a2b4.png)

If pushed to Github, this is also fine

![image](https://user-images.githubusercontent.com/1720008/86536087-2b367980-bee5-11ea-8145-24643e0038d3.png)



For the record:

apt install fonts-noto-color-emoji
create a file `~/.config/fontconfig/fonts.conf`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```
fc-cache -f -v
