### ISSUE TITLE
source code mode bug: same sequential number

### ISSUE THREAD

**Issue by sisypheansss** [typora/typora-issues#1358]
In source code mode,  the sequential number is always the same as first one.
![image](https://user-images.githubusercontent.com/20226048/38029905-b2d9eb2e-32c9-11e8-8524-56b82082727e.png)
This happens only in source code mode, and when switching back, the sequential number is correct.

**Comment by AlexPasternak** [comment]
How is that an issue? Source code mode is basically raw mode, and that's what actual MD is for a numbered list. You can explicitly number list, or you can put 1. for all items, and rendered MD will convert them into actual numbers.

**Comment by abnerlee** [comment]
Fixed in new release
