### ISSUE TITLE
Documents not saving/Issues with OneDrive

### ISSUE THREAD

**Issue by mikeymop** [typora/typora-issues#1359]
I am not sure if something changed in the recent update to `0.9.47` however it has started having issues with OneDrive.

In previous versions I was able to edit, save and open files on OneDrive on Windows 10. Since updating to this new version, it appears to save the files however if you close and reopen them you will get an error message:

![image](https://user-images.githubusercontent.com/4002969/38032667-34c969ba-326c-11e8-8545-8bbf8f2d014d.png)

Closing Typora will ask if I want to save (I hit discard so as not to overwrite). I can open the same file in Sublime text and my data will be there, however, I made several edits in Typora it will have only saved the _first_ save I did.

I lost a pretty large document because I was unaware that Typora actually wasn't saving. Was something changed with file handling or text i/o streams in the previous update?

**Comment by dyxcloud** [comment]
Encountered the same problem, when open the file in onedrive folder, will report this error.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1309

We will fix this in next version up, or you may follow the hotfix in https://github.com/Microsoft/vscode/issues/27285#issuecomment-309270189
