### ISSUE TITLE
Bug with nested/indented list content

### ISSUE THREAD

**Issue by daveaglick** [typora/typora-issues#136]
There appears to be a bug with nested/indented list content, possibly relating to code fencing (I'm using the Windows version). It looks like nested/indented content is invisible both in the rendered view and in the source code view. Here's a screenshot:

![2016-04-21_10h50_12](https://cloud.githubusercontent.com/assets/1020407/14713419/0eaaa40e-07af-11e6-81b3-77fa80747ac2.png)

The file used here is https://raw.githubusercontent.com/Wyamio/Wyam.Web/6827979e9a8f38cf5d8b0ea5314b8caa62bb099e/Input/getting-started/io.md

**Comment by abnerlee** [comment]
Thanks for the report, seems to be a critical bug, we will fix it asap.

**Comment by daveaglick** [comment]
:thumbsup:

**Comment by abnerlee** [comment]
fixed in new release
