### ISSUE TITLE
[0.9.47] Dragging an image into the doc mismatches the img tag

### ISSUE THREAD

**Issue by mikeymop** [typora/typora-issues#1360]
If I were to drag `abcdefg.jpg` into the document the resulting image tag will look like this:
```
[bcdef](./.../abcdefg.jpg)
````

It seems typora is clipping off the start and finish of the file name when naming the image tag. This doesn't break functionality but I noticed this regression since the last build.

![image](https://user-images.githubusercontent.com/4002969/38091487-b3f93842-3333-11e8-995c-1421bbbd856b.png)

**Comment by abnerlee** [comment]
Typora version?

**Comment by mikeymop** [comment]
Sorry! I updated the title with the version.

**Comment by abnerlee** [comment]
Fixed in new release
