### ISSUE TITLE
Make outline more useful — allow sections to be moved

### ISSUE THREAD

**Issue by vr8hub** [typora/typora-issues#1364]
The outline is a great idea, but I would like to see it become even more useful.

For documents with large outlines, it would be really useful to be able to move sections of the document around in the outline itself. Instead of having to highlight maybe a page or two or ten of text to move something, you could just click and drag on the H1 (or H2 or whatever) and drag it to where you wanted it to be. Ideally we could highlight multiple (contiguous) sections of the outline and drag them all, but even being able to do one would be very helpful.

**Comment by abnerlee** [comment]
duplicate with existing issues

**Comment by vr8hub** [comment]
Duplicate of what existing issue? I searched for "outline" in the open issues before posting this, and didn't see one discussing it.

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/916

**Comment by vr8hub** [comment]
No, my fault. I just didn't go back far enough. Thanks for the pointer.
