### ISSUE TITLE
Display sidebar in outline mode

### ISSUE THREAD

**Issue by vr8hub** [typora/typora-issues#1365]
Typora .9.9.13.6 on OSX 10.12.6.

Why does the sidebar not display in source code mode? Having the outline there especially (but files as well) is just as useful (or more) when in source code mode than not.

Please leave the sidebar open all the time (if we have it toggled on).

**Comment by abnerlee** [comment]
We do not want to enable all function on source code mode.

Source coed mode is designed for temporary usage when users want to see the raw source. In most cases, the default hybrid view should meet user's requirements.

**Comment by vr8hub** [comment]
It doesn't meet the user's requirements. Hence the request.

There's no reason not to leave the sidebar enabled — you have to work to *disable* it when it's already displayed. It's less work for the program to leave it displayed, and it's more useful for the user.
