### ISSUE TITLE
Tables in WYSIWYG mode should be auto-sized, not full-width

### ISSUE THREAD

**Issue by vr8hub** [typora/typora-issues#1368]
Typora .9.9.13.6 on OSX 10.12.6.

Tables always render full-width in Typora, which they don't do in any other Markdown editor I use (or have used). I have a lot of documents that just have two or three column tables, and those tables are typically only a quarter or so of the horizontal width of the page, but Typora always renders them full-width, meaning a two-column table has columns that are 3+ inches wide. That's … ugly. :)

They should render auto-sized, i.e. only display the width necessary to contain the widest text in the column.

**Comment by abnerlee** [comment]
I see, 

It is a preference of styling, we allow users to override this by add 
```css
table {
width: auto;
}
```
following http://support.typora.io/Add-Custom-CSS/

We will also provide some themes using auto-sized tables.

**Comment by vr8hub** [comment]
> On Apr 2, 2018, at 3:07 AM, AbnerLee <notifications@github.com> wrote:
> 
> I see,
> 
> It is a preference of styling, we allow users to override this by add
> 
> table {
> width: auto;
> }
> following http://support.typora.io/Add-Custom-CSS/ <http://support.typora.io/Add-Custom-CSS/>
> We will also provide some themes using auto-sized tables.
> 

First, I would suggest that be the default. It's what most other MD editors (and non-MD editors, for that matter.)

Second, what themes? I tried probably a half-dozen themes or more looking to see if there was something I could do, and I couldn't find one.

Thanks for the heads up!

**Comment by jszgz** [comment]
> I see,
> 
> It is a preference of styling, we allow users to override this by add
> 
> ```css
> table {
> width: auto;
> }
> ```
> 
> following http://support.typora.io/Add-Custom-CSS/
> 
> We will also provide some themes using auto-sized tables.

not work

**Comment by jszgz** [comment]
> I see,
> 
> It is a preference of styling, we allow users to override this by add
> 
> ```css
> table {
> width: auto;
> }
> ```
> 
> following http://support.typora.io/Add-Custom-CSS/
> 
> We will also provide some themes using auto-sized tables.

It doesn't work
