### ISSUE TITLE
Smart quotes should only be in output (including WYSIWYG mode), not source

### ISSUE THREAD

**Issue by vr8hub** [typora/typora-issues#1369]
Part of the point of Markdown is plain-ASCII text files. As such, quotes in the raw text should always be straight single/double quotes (' and "), not smart quotes. But it's 2018, and typography (normally) demands smart quotes in our output.

Thus, Typora should only substitute smart quotes in the output (including WYSIWYG), but store straight quotes. When I go into source code mode (and view the raw file from a text editor or the command-line or whatever), the quotes should all be straight. (IOW, I don't want smart quotes in my raw file.) But visibly in Typora, and in whatever export happens (copy HTML, export, etc.), the quotes should be smart.

Same thing for dashes — the raw source should retain the double-dashes, it's only the output (including WYSIWYG) that should show the em-dash.

(Typora appears to get its implementation design for this from LightPaper, as the Substitution menu position and dialog are identical. LightPaper gets this wrong; it's one of the (several) reasons I no longer use LP. None of the other MD editors I have [MacDown, Multi-Markdown, Byword; Marked 2 isn't an editor, but it has options to display typographical quotes for straight quotes in the text] do this, for obvious reasons — Markdown is about straight-ASCII text files.)

**Comment by abnerlee** [comment]
Relates https://github.com/typora/typora-issues/issues/137

Merge into https://github.com/typora/typora-issues/issues/291 Since smartyPants support is not implemented yet, so for now, behavior of macOS's default behavior is applied for those options

**Comment by vr8hub** [comment]
OK, thanks. That's been open for a year-and-a-half, so it would appear to not have much priority. That's a deal-killer for me. Markdown files simply can't have non-ASCII text in them. I'll check back in from time to time; I really like the whole idea of Typora, it just needs work in the implementation.
