### ISSUE TITLE
Source Code Mode adding extra space between tabs and "```"

### ISSUE THREAD

**Issue by Shdwfx** [typora/typora-issues#1372]
Hello, 

 I am using Typora for writing some doc for mkdocs with Materials.

I am using Admonition and super fences together. so i wrote following:

??? note "Example"

	For disable API:
	
	​``` xml linenums="1"
	<WebController enabled="false">
	    <Address>192.168.10.168</Address>
	    <Port>10097</Port>
	    <ConfigUpdate enabled="false" />
	    <MaxQueryInterval>1 week</MaxQueryInterval>
	</WebController>
	​```

I am saving document and exiting source code mode. When switch back to source code mode again and Typora adds extra space after the tab. I highlighted extra space below.

![space](https://user-images.githubusercontent.com/17083700/38162792-701f3cb6-34f0-11e8-8c97-1e417fff5d91.PNG)

Sorry for poor English. 

	​

**Comment by abnerlee** [comment]
Fixed in new release
