### ISSUE TITLE
code fence issue

### ISSUE THREAD

**Issue by jacquen** [typora/typora-issues#1374]
Hi, Support

I had a problem within souce code fence, I will get extra ``` pair when I have more than 3 empty line between source code, is this a bug of software or somethig I need pay attention
![image_2018-04-03_14-34-31](https://user-images.githubusercontent.com/2107576/38233160-28432ce6-374c-11e8-9206-f16b1fe46be4.png)
![image_2018-04-03_14-34-38](https://user-images.githubusercontent.com/2107576/38233165-2acc06b8-374c-11e8-8108-e685673c2e5a.png)

**Comment by abnerlee** [comment]
Sorry, I'm not quite understand your issue.

From your content
![](https://user-images.githubusercontent.com/2107576/38233160-28432ce6-374c-11e8-9206-f16b1fe46be4.png)

You inputted ` ``` `, so in source code mode, ` ``` ` is shown.

**Comment by jacquen** [comment]
hi, Abnerlee

the second ``` show in red square is generate by system, not input by me. Not sure why system will generate extra ```

**Comment by jacquen** [comment]
the second \``` show in red square is generate by system, not input by me. Not sure why system will generate extra \```

**Comment by jacquen** [comment]
maybe it considering extra space as \```

**Comment by abnerlee** [comment]
@jacquen Thanks for the explanation.

could you provide the markdown source that system will generate extra ``` ?

**Comment by jacquen** [comment]
[Multicast.zip](https://github.com/typora/typora-issues/files/1874046/Multicast.zip)
Hi, Team

I upload MD file, hope you will get to know the problem. Thanks

**Comment by abnerlee** [comment]
Should be fixed already
