### ISSUE TITLE
Pointer in Theme menu does not change whern you change theme

### ISSUE THREAD

**Issue by GreatBahram** [typora/typora-issues#1377]
Hello
I've used Typora on my GNU/Linux systems since 2016 and I'm satisfied with that. There is a problem when you change the theme on Ubuntu, the theme changed but the pointer in Theme menu still refers to the first one (Github!).

Thanks a lot Typora team

**Comment by abnerlee** [comment]
Typora version?

menu item status not change even after you reopen the menu?

**Comment by GreatBahram** [comment]
It was on 0.9.37 after update it's OK.
