### ISSUE TITLE
Paste function issue

### ISSUE THREAD

**Issue by akriuchk** [typora/typora-issues#1383]
Hello,

After last update to 0.9.9.14 version on MacOS I have next issue:
Typora ver.: 0.9.9.14
OSX: 10.12.6

Steps to reproduce:
1. Copy any text from same document or other program
2. Switch to opened document in Typora
3. Use shortcut CMD+V or Edit->Paste

ER: Text from clipboard pasted
AR: Nothing pasted

Thank you.

**Comment by abnerlee** [comment]
> Copy any text from same document or other program

You mean copy from ANY program?

**Comment by akriuchk** [comment]
@abnerlee
Exactly, tried from IntelliJ Idea, safari - nothing pasted, but state of document changed to “edited”

**Comment by akriuchk** [comment]
@abnerlee 
Restarted notebook and issue vanished...
