### ISSUE TITLE
Inserting a footnote inserts ZERO WIDTH SPACE character

### ISSUE THREAD

**Issue by somelinguist** [typora/typora-issues#139]
Inserting a footnote with the menu/shortcut inserts Unicode Character 'ZERO WIDTH SPACE' (U+200B) following ^ in the reference marker. It can't be deleted without editing the source.

As a result, trying to insert a corresponding reference in the text produces, "Need to define the reference footnote 1 with syntax [^1]: www.example.com".

If I edit the source and delete the ZERO WIDTH SPACE character, then everything is fine.

I'm using version 0.9.4 on Windows.

**Comment by zhanghaoyu1993** [comment]
I have the same problem too, I'm using version 0.9.5 on Windows.

**Comment by abnerlee** [comment]
fixed in new version
