### ISSUE TITLE
Failed to change the style of codes inside the fences

### ISSUE THREAD

**Issue by Bertie97** [typora/typora-issues#1391]
It happens that I need to self-design colors for codes in code-fences. (e.g. I need comments red to attract more attention) 
However, changing the style of class .cm-comment in css makes no difference. 
`.cm-comment {color: #f00;}`

I'm wondering if this could be done in the current version of Typora and if it should be doing well, what has happened. 
P.S. If it is what should be happening, please at least consider adding this feature to the app.

**Comment by abnerlee** [comment]
see http://support.typora.io/Code-Block-Styles/

**Comment by Bertie97** [comment]
Sorry for my carelessness and Thanks!
