### ISSUE TITLE
Syntax highlighting for pseudo codes and Algorithm

### ISSUE THREAD

**Issue by vndsrswt** [typora/typora-issues#1396]
Syntax highlighting for pseudo codes and Algorithm in code fences

**Comment by cprieto** [comment]
Maybe we can use this? https://gist.github.com/neochief/c58931a40f3a4dd0036b20d60d0b77ed if not (for any reason) I can take a look and write a package for pseudocode (in the same way the Elixir mode is distributed).

**Comment by abnerlee** [comment]
Supported in new release

**Comment by Wilder13** [comment]
Since I could add my own reserved words, I want you to highlight them for me.
