### ISSUE TITLE
Tooltip missing for H1 and H2

### ISSUE THREAD

**Issue by g3blv** [typora/typora-issues#1397]
For headings H3, H4 and so on there is small tooltip on the left side of the heading that show the heading level. It is very helpful but it seems like it is missing for H1 and H2.
![screenshot from 2018-04-08 17 11 34](https://user-images.githubusercontent.com/2023139/38469189-ef492612-3b50-11e8-856a-1bddc2119de6.png)

Typora: 0.9.48
Ubuntu: 16.04

**Comment by abnerlee** [comment]
H1 and H2 are clear even without tooltips.

If you know CSS, you could add tooltips for H1 and H2 following http://support.typora.io/Add-Custom-CSS/

**Comment by g3blv** [comment]
Sorry @abnerlee I don't quite understand your reply. 

Is it designed to not show the heading level on the left side of the heading for heading level 1 and 2 but it will show it for all other heading levels? If that is the case what is the logic behind not showing it for heading level 1 and 2?
