### ISSUE TITLE
exported PDF with chaotic code block

### ISSUE THREAD

**Issue by Honghe** [typora/typora-issues#1399]
# env:
* Ubuntu 16.04.4
* Typora 0.9.48

source:
![image](https://user-images.githubusercontent.com/1092722/38490827-b9d0c680-3c1c-11e8-9396-4f4e84ca8f25.png)

exported PDF
![image](https://user-images.githubusercontent.com/1092722/38490809-b062d822-3c1c-11e8-8ec2-511a65862996.png)

**Comment by abnerlee** [comment]
The code block is too wide to display in the exported page without line wrap.

You could wait for support https://github.com/typora/typora-issues/issues/998
Or remove unneeded char
