### ISSUE TITLE
images should default to relative paths

### ISSUE THREAD

**Issue by kontrafiktion** [typora/typora-issues#14]
When dragging images from the local file system, the generated path is always absolute, even if the images is in the same folder or a sub folder.
That makes it difficult to collaborate

**Comment by abnerlee** [comment]
Yes, from next version, drag&drop image from same or sub folder will use relative path by default.
And user can make drag image using relative path by default from preference panel.

**Comment by abnerlee** [comment]
Fixed in v0.9.7.4
