### ISSUE TITLE
0.9.48 Does not save if file contents haven't changed

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#1402]
As of 0.9.48 I can no longer force a file to be saved if its contents are the same as they were when the last save occurred.  It appears that Typora changes the file modification date but does not rewrite the file contents?

**Comment by abnerlee** [comment]
I think Typora will do the rewriting.

Or, can any bug be produced from this?

**Comment by pjeby** [comment]
I'm actually no longer able to reproduce this behavior, but in retrospect I think that this might actually have been an instance of #1445 before I knew what was going on with that.  That is, the file was actually saving in a deferred fashion in such a way as to make me think it had something to do with whether the file contents changed.  So, I'm closing this in favor of #1445, sorry for the noise.
