### ISSUE TITLE
Some inline formulas are not displayed when exported

### ISSUE THREAD

**Issue by CsatiZoltan** [typora/typora-issues#1403]
In certain cases, LaTeX formulas (simple ones like $\mathbf{U}$) are displayed in Typora but are not rendered in either html or pdf mode See two of these glitches highlighted in yellow. On the right we have Typora, at the bottom left the html opened in Firefox and at the top left the pdf file.

![latexexport](https://user-images.githubusercontent.com/12742890/38512005-3acd0d0e-3c2a-11e8-938f-16e62d402110.PNG)

I didn't forget to place the dollar signs and I also tried *Edit -> Math Tools -> Refresh All Math Expressions*. Moreover I saved the .md file before exporting.

I use the latest version of Typora (ver. 0.9.48) on Windows 7.

**Comment by abnerlee** [comment]
@CsatiZoltan Thanks for the report.

Could you attach the sample *.md file or send it to us (<hi@typora.io>) ?

**Comment by CsatiZoltan** [comment]
It's here (I modified its extension so that I can upload):

[Speeding up element mass matrix calculations.txt](https://github.com/typora/typora-issues/files/1893694/Speeding.up.element.mass.matrix.calculations.txt)

**Comment by abnerlee** [comment]
Seems OK by exporting your attachment. Could you confirm this again?

**Comment by CsatiZoltan** [comment]
Strange, now it works for me too. Sometimes it happens that when I forget one of the $ signs, and putting it later, Typora has a hard time to recognise it as math input.

**Comment by abnerlee** [comment]
@CsatiZoltan Di you use nay IME when input the $ mark?

**Comment by CsatiZoltan** [comment]
What is IME?

**Comment by abnerlee** [comment]
input method engine

**Comment by CsatiZoltan** [comment]
No, I use Hungarian keyboard. But the text I wrote was purely English.
