### ISSUE TITLE
GitHub theme != GitHub theme

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#1404]
Sorry for being a little bit harsh, I very much appreciate your work on Typora, but IMHO your replicate of the GitHub theme is moderately beautiful. Would it be possible to use the original GitHub CSS files?

**Comment by abnerlee** [comment]
Yes, GitHub theme is not this GitHub theme.

We will not prepare the original GitHub CSS, you could follow

If you have CSS knowledge, you could do this using https://github.com/sindresorhus/github-markdown-css, following http://theme.typora.io/doc/
