### ISSUE TITLE
Can typora markdown rendering work in the browser?

### ISSUE THREAD

**Issue by raymestalez** [typora/typora-issues#1406]
I would love to use typora's markdown rendering in my app (and I'd be happy to purchase a premium license to do that). Do you think that could be possible?

**Comment by abnerlee** [comment]
For the time being, we will focus on the desktop version.

**Comment by std4453** [comment]
lgtm, since the app is electron-based, I suppose porting it to the browser wouldn't be THAT difficult? Any plans on this?
