### ISSUE TITLE
RESTful and local content providers

### ISSUE THREAD

**Issue by ernichechelski** [typora/typora-issues#1407]
# RESTful and local content providers

## Overview
I would like to propose a very useful scheme or idea for external extensions without involving too many internal developers.

## Use case

Let's consider a situation when the user wants to place custom quotes from external REST service by using markdown-like syntax.

## Syntax proposal
```
!![](www.localhost.com:8080/example_endpoint)
```
for example
### Request for service
```
!![](http://example.qutheory.io/json)
```
will execute request and get a response and render following value as simple text (I just found simple GET endpoint which returns simple json, but it is also possible to just return plain text so will be very useful):

{"array":[0,1,2,3],"dict":{"lang":"Swift","name":"Vapor"},"number":123,"string":"test"}

### Embedding existing markdown files:
```
!![](about.md)
```
will read `about.md` content and embed in current document.

## Protocol considerations

If some endpoint returns map, that value can be used for some kind of autocompletion.
For example (with imaginary urls):
```markdown
!![](www.thebestbook.com/api/books)
```
Will return map with id's and title with readable format.
For example
```json
{
"1" : "Mark Bergzucker - Sharing info with anyone." ,
"2" : "Albert Zweistein - Most advanced physics." 
}
```

So according to response possible value is `1` and `Mark Bergzucker - Sharing info with anyone.` text should be displayed for user.

```markdown
!![](www.thebestbook.com/api/books/1/chapters)
```
will return for example
```json
{
"1" : "Introduction" ,
"2" : "Summary" 
}
```
And so on.

## Advantages
- This extension could be working as offline is this selected service is running on a local machine, and also could be more extensible with more complex protocols with returning data.

- The very powerful mechanism for merging smaller documents to greater ones.

- Create the market for content providers in style of themes

- Very flexible technology stack (Every restful service will fit requirements. Spring Boot, Vapor, .NET Core, Node.js and so on).

## Things to consider:
  - [ ] Defined protocol to provide some kind of autocompletion and data model.
  - [ ] Lifetime synchronization with Typora application (Autostart and auto turning off of content provider service).
- [ ] Possibility of use different HTTP methods.

**Comment by mlopezgva** [comment]
This is very interesting.

I've made a little ticket -> markdown converter at job, a tool to create a document by extracting data from our ticket module (title, issuer, request, attendants, gantt diagram with its history and "main comments" from engineers, developers and client).

It's almost as described. I would like to get the script's response to create semi-automated documents, filling the rest (development comments, testing checklist etc.) by hand.

**Comment by abnerlee** [comment]
#2448
