### ISSUE TITLE
[Feature Request] Wavedrom Support - To write digital timing diagram

### ISSUE THREAD

**Issue by chenwq3** [typora/typora-issues#1410]
Hi, Thank you for developing typora and provide it for everybody in beta.

I think it would be better that typora support wavedrom.
Here is it's github project :https://github.com/drom/wavedrom

Here are examples:

![](https://user-images.githubusercontent.com/25943138/38665404-e467820e-3e6e-11e8-9675-09e412c1e146.png)

![qq 20180412163222](https://user-images.githubusercontent.com/25943138/38665487-187f2b6e-3e6f-11e8-9fc4-10f619db5a9d.png)

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1138
