### ISSUE TITLE
Add ignore option for unknown words

### ISSUE THREAD

**Issue by GreatBahram** [typora/typora-issues#1412]
Hello 
I think it would be better if there was any option for ignoring unknown word in addition to `Learn spelling`. 

Thanks

![ignore](https://user-images.githubusercontent.com/14103831/38671844-b7b4cc7e-3e61-11e8-9c60-4449153cd76b.png)

**Comment by abnerlee** [comment]
You could disable spell check in preference panel

**Comment by GreatBahram** [comment]
But I want spell checking and ignore unknown word at the same time.

**Comment by abnerlee** [comment]
you mean learn spell without save?
