### ISSUE TITLE
[LaTeX] Can typota add "chemfig" package support?

### ISSUE THREAD

**Issue by imByteCat** [typora/typora-issues#1417]
I tested typora, it supports the "mhchem" package (`$\ce{...}$`), but sometimes I need to write the equation of organic chemistry and need to use the "chemfig" package, can you help me?😂

**Comment by abnerlee** [comment]
Typora only supports a subset of LaTeX covers Math Equations by MathJax.

**Comment by HaoZeke** [comment]
That doesn't sound right as the pdf generation is driven by pandoc which has full support for all TeX packages.

**Comment by capravictoriae** [comment]
I believe this can be done by adding an extension to MathJax like this:

```html
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({ tex2jax: { inlineMath: [ ['$','$'], ["\\(","\\)"] ], displayMath: [ ['$$','$$'], ["\\[","\\]"] ], processEscapes: true },TeX: { extensions: ["mhchem.js"] } });
  </script>
```

Typora is already using various extensions with Mathjax this way.

See [this example](https://codepen.io/josdea/pen/eBdYpo), or [this](https://mhchem.github.io/MathJax-mhchem/)

The way I achieve this (not a solution) is by converting LaTeX to a SVG figure in my local machine, and then just including the SVG figures. This is for the looks as it doesn't allow to quickly change the render.

**Comment by gandalfsaxe** [comment]
@capravictoriae Why do you convert LaTeX conde to SVG if MathJax can be extended to include `mhchem` and `chemfig`?

Also, where does the code snippet go? Even after reading MathJax's [own documentation](http://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options) on this, it's still not clear to me :)

**Comment by HaoZeke** [comment]
>  Also, where does the code snippet go? Even after reading MathJax's own documentation on this, it's still not clear to me :)

@gandalfsaxe the code goes anywhere on the site, as long as it is loaded after MathJax. Typically you might load MathJax in `head` and this code snippet and all others at the end of `body`.

**Comment by capravictoriae** [comment]
It is a bit hacky but the way I do this is editing the `window.html` file you find in typora instalation. For me (linux) this is in `/usr/share/typora/resources/app/windows.html`.
There you will find the `Tex: {extensions:...` thing, you add the mhchem.js and works. This is for Typora, if you are doing for MathJax in a web then its what @HaoZeke said.

I do the SVG thing for performance reasons when loading big documents. It is faster, but very inconvenient.

**Comment by gandalfsaxe** [comment]
Thanks. I've looked around and I cannot find a `window.html` anywhere on Mac :/

@abnerlee How do you apply MathJax extensions on the Mac version of Typora? This may be worth including in the official documentation for people who want to use the very \ common extensions of `mhchem` and `siunit` - or perhaps even include them. The list of maintained 3rd party MathJax extension is very short anyway: https://github.com/mathjax/MathJax-third-party-extensions

**Comment by abnerlee** [comment]
`mhchem` is already included by auto-load used packages.

This issue is about the LaTeX chemfig package, not about mhchem

**Comment by gandalfsaxe** [comment]
I see. The reason I wrote in this issue was because I'm really interested in support for the `siunitx` package, which is also on the short list of third party MathJax extensions above. I thought I could do it myself, but I'll make a separate issue then: #1569

**Comment by abnerlee** [comment]
Typora does not have plans to support native LaTeX packages, for mathjax support, please refer: https://github.com/mathjax/MathJax/issues/554

**Comment by freezingSummer** [comment]
> Thanks. I've looked around and I cannot find a `window.html` anywhere on Mac :/
> 
> @abnerlee How do you apply MathJax extensions on the Mac version of Typora? This may be worth including in the official documentation for people who want to use the very \ common extensions of `mhchem` and `siunit` - or perhaps even include them. The list of maintained 3rd party MathJax extension is very short anyway: https://github.com/mathjax/MathJax-third-party-extensions

Hi, @gandalfsaxe, I think it is `/Applications/Typora.app/Contents/Resources/TypeMark/index.html` on Mac. I am trying to include commutative diagrams in typora, provided by `xyjax` extension to MathJax.
