### ISSUE TITLE
Add file chooser for links

### ISSUE THREAD

**Issue by LBroe** [typora/typora-issues#1418]
We already have a file chooser when inserting images, the same thing for links would be appreciated.

**Comment by vassudanagunta** [comment]
For links, auto-completion would be even better (no dialogue, all with keyboard). e.g. if you start typing a local link (does not start with URL scheme such as http://) it will offer auto completion suggestions based on all file names in or below a certain folder. But which folder? The root of the tree view?

**Comment by LBroe** [comment]
@vassudanagunta I think a combination would be best, preferably with configuration options for the staring directory. For now, I thought of just repeating the same feature from inserting images to inserting links, as it is already implemented and should not be difficult to copy.

**Comment by frankgerhardt** [comment]
Not having auto-completion for entering links is the single most missing feature of Typora for me.

**Comment by frankgerhardt** [comment]
You wouldn't believe how much pain I have when making a link to a new file. In `2018.markdown` I have `[2018b](2018b.markdown)` as a link to a new file. Creating this new file with this link is not working in so many ways. PLEASE, PLEASE, PLEASE fix that.

**Comment by dushige** [comment]
Looking forward to supporting "URL Schemes"

**Comment by abnerlee** [comment]
merge into #2663
