### ISSUE TITLE
Text disappear in source code mode

### ISSUE THREAD

**Issue by nisiyama** [typora/typora-issues#1419]
- problem

Inputted text disapper in source code mode with following sequences:

1. input following text to typora

![fig](https://user-images.githubusercontent.com/5814404/38774868-a2fae5e6-40ac-11e8-9a66-a25a11be14f4.png)

2. change to source code mode

3. texts in block quote do not show as follows

![fig2](https://user-images.githubusercontent.com/5814404/38774897-4ec452fe-40ad-11e8-8141-09cd1caeaaa7.png)

- environment

  - Typora: ver 0.9.9.14 (MacOSX)

**Comment by abnerlee** [comment]
@nisiyama Cannot reproduce this.

Could you provide more detail steps to for this. Also, what's your macOS version?

**Comment by nisiyama** [comment]
@abnerlee macOS version is 10.13.4 (High Sierra).
Step to reproduce in my environment is as follows.

1. open new window (command-N)
2. input following key sequences 
```
- item1<CR><DEL>```<CR>line1<CR>line2<command-/>
```

**Comment by abnerlee** [comment]
Still seems OK
@nisiyama Did you use any IME or special keyboard layout when input this ?

**Comment by nisiyama** [comment]
@abnerlee Sorry for my late reply.
Yes,  I use Japanese IME.
I noticed that inputing code block (```) with IME seems to cause the problem.
