### ISSUE TITLE
Internationalizing the User Interface 

### ISSUE THREAD

**Issue by doveccl** [typora/typora-issues#142]
I found app-zh.json in this folder, but it' s incomplete.

Will typora support more languages in the future?

**Comment by abnerlee** [comment]
Yes, currently only US English is available, and we only plan to support other languages after 1.0 release.

**Comment by montogeek** [comment]
I can help translating the interface to Spanish, also, I will pay for this!

**Comment by EMLVIRUS** [comment]
Hey. I can help with Zh-CN locale, but how indeed as I can't find a contribution guideline.

**Comment by abnerlee** [comment]
@EMLVIRUS Thanks for the help, the multi-language is not fully supported in code level yet. So we didn't prepare a contribution guideline. We plan to support multi-language around v1.0

**Comment by starise** [comment]
<3 Typora. I'm here for the italian localization when things will be ready!

**Comment by starise** [comment]
❤ Typora. I'm here for the italian localization when things will be ready!

**Comment by abnerlee** [comment]
See -> https://github.com/typora/Typora-i18n

We supports Internationalization now

**Comment by sngreen** [comment]
Hi, is there English language interface? I see there is a *pak file in locales, but how does one change to it? - It always comes back with whatever language was there first (or perhaps system language) - no way to change?
