### ISSUE TITLE
[Feature Request] Hide menubar

### ISSUE THREAD

**Issue by ziggy42** [typora/typora-issues#1420]
Typora could look better on GNOME:
![screenshot from 2018-04-15 18-57-06](https://user-images.githubusercontent.com/4258550/38780984-ea557c26-40de-11e8-95eb-b17c71888559.png)

Many of the major electron apps (Slack, VSCode) have the ability to hide the menubar pressing `ALT`, would be great to have it in Typora too.

**Comment by abnerlee** [comment]
Can be set in advanced setting in preference panel
