### ISSUE TITLE
A button to save the modified figure directly to the original figure file

### ISSUE THREAD

**Issue by lingliugithub** [typora/typora-issues#1428]
Hi, 
After I paste a figure from an existing file and use the Annotation tool to add something on the figure, can I directly save the modified version? Every time I have to click "save as" to locate the file in the Windows Explorer and replace the existing file. 
Is it possible to add a button or an option to directly save a figure?

Thanks!

**Comment by abnerlee** [comment]
What is the Annotation tool, does it provide "save" button?

If the modification/save is provided by Annotation tool, shouldn't it be handled by the annocation tool?
