### ISSUE TITLE
Soft line breaks are not honoured when exporting to pdf 

### ISSUE THREAD

**Issue by stewartknapman** [typora/typora-issues#1430]
Soft line breaks are not honoured when exporting to pdf: https://monosnap.com/file/JFDLQimVrerMtt5q5MmnA5pYgm8Zjo

**Comment by abnerlee** [comment]
See settings in `Markdown` section in preference panel

**Comment by ArtDan** [comment]
Thank you, solved my problem.

However, would it not be more intuitive to match the WYSIWYG view and therefore choose `preserve whitespace and single line break` as default value?

**Comment by abnerlee** [comment]
We changed to it as default value for new installations. For users who upgrade from an order version, we use the OLD default value for backward compatibility. It is addressed in another issue
