### ISSUE TITLE
Failing access to a shared files in smb drive

### ISSUE THREAD

**Issue by wkwkw** [typora/typora-issues#1432]
* OS: Ubuntu 16.0.4
* Typora version: 0.9.48

First access to a shared file in smb drive after system boot fails all time.
(With some message like: "Could not open the file /some/path/aaa.md" )

To open the file, I have to access the smb drive in file viewer first.
I can open any files in the drive after that.

Not a critical issue but is inconvenient behavior.

Thanks.

**Comment by abnerlee** [comment]
> (With some message like: "Could not open the file /some/path/aaa.md" )

**Comment by abnerlee** [comment]
> (With some message like: "Could not open the file /some/path/aaa.md" )

**Comment by abnerlee** [comment]
> (With some message like: "Could not open the file /some/path/aaa.md" )

This is caused by network drive not connected.

Typora does not handle connections to network driver (Typora did not implement smb protocol and does not want to handle password validation for network driver)
