### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by strivebo** [typora/typora-issues#1434]
I open the software for a period of time, then appear a image which show the stop work. PS: The platform I use is win7 64 bits. 

 ![](http://p35l3ejfq.bkt.clouddn.com/222.jpg)

**Comment by abnerlee** [comment]
Typora version?

And could you send log from C:\Users\{username}\AppData\Roaming\Typora\typora.log to hi@typora.io ?

**Comment by strivebo** [comment]
ok...The typora version I use is 0.9.48(beta).Then, aha...I had send the typora.log to <hi@typora.io> just now. @abnerlee

**Comment by abnerlee** [comment]
Please check new updates, and reopen this if it is still not fixed
