### ISSUE TITLE
Relationship with Marktext?

### ISSUE THREAD

**Issue by simon-mo** [typora/typora-issues#1435]
Loved typora, long-time user. Thank you so much Abner!

What's the relationship between https://github.com/marktext/marktext and this project? They look extremely similar....

**Comment by abnerlee** [comment]
you could refer to their early commit https://github.com/marktext/marktext/commit/3c7864ee896af33eb83f57e0363635b0c3e8fea0#diff-04c6e90faac2675aa89e2176d2eec7d8
