### ISSUE TITLE
broken because I open a large file

### ISSUE THREAD

**Issue by lee5214** [typora/typora-issues#1443]
Using macOS, tried to open a 12mb json file
The application stopped responding, have to force quite. Re-open or re-install didn't fix, as soon as I open it, it tries to load the previous files, which makes it not responding anymore.

Anyone knows how to change the setting to clear the history so that it won't load the large file anymore.

I think it's necessary to put a limitation or at least some warning so that new users like me wouldn't loose their unsaved files.

**Comment by abnerlee** [comment]
It is a problem.

For hot fix, you could using tools like AppCleaner to search and remove `plist` file of Typora

**Comment by lee5214** [comment]
get it done with the help of AppCleaner
thx
