### ISSUE TITLE
a bug for formatting inline code and tab

### ISSUE THREAD

**Issue by iLouisHan** [typora/typora-issues#1446]
When there is a tab in front of Chinese, the block of code immediately following will be cover in the previous Chinese.
Just like this
![image](https://user-images.githubusercontent.com/38677806/39296898-b6b7e7ca-4974-11e8-8931-6acbdd420a59.png)

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by iLouisHan** [comment]
Typora 0.9.48

**Comment by abnerlee** [comment]
Seems OK in my test
@iLouisHan  Did you modified the theme css? And could you attach the sample md file?

**Comment by iLouisHan** [comment]
@abnerlee 
i didn't modifed the theme css. 
[just test.zip](https://github.com/typora/typora-issues/files/1957150/just.test.zip)
the theme i used was "github".
![image](https://user-images.githubusercontent.com/38677806/39390544-a5d59006-4ac8-11e8-9392-f9db026fe974.png)
![image](https://user-images.githubusercontent.com/38677806/39390546-ad3eb340-4ac8-11e8-82e0-d71d7734c8c5.png)

**Comment by abnerlee** [comment]
Fixed in new release
