### ISSUE TITLE
typroa does not run on ubuntu 18.04 (bionic)

### ISSUE THREAD

**Issue by panzerballett** [typora/typora-issues#1447]
i installed typora today on a brand-new ubuntu 18.04. on startup it crashes with the message

```
$ typora 
typora: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
the fix is simple:

`$ sudo apt install libgconf-2-4 `

but maybe this should go into the requirements and be installed  automatically?

**Comment by abnerlee** [comment]
> `$ sudo apt install libgconf-2-4`

Yes, this can fix. Newer version of Ubuntu already contains it.
