### ISSUE TITLE
why toc tag can not generate GitHub table of content

### ISSUE THREAD

**Issue by kedup** [typora/typora-issues#1448]
![ga p jehf z ct1z9 fk6](https://user-images.githubusercontent.com/12842978/39345750-d6b2b4c6-4a1c-11e8-871e-d0995fd8f60d.png)

the toc tag shown in github

**Comment by abnerlee** [comment]
`[TOC]` is not supported in Github

Relates https://github.com/typora/typora-issues/issues/169
https://github.com/typora/typora-issues/issues/1202
