### ISSUE TITLE
Wrong behaviour of brackets in math mode?

### ISSUE THREAD

**Issue by truefalsename** [typora/typora-issues#145]
Hi,

so, I found out why I was bothering you with brackets. 
In text mode, inline math mode and full math mode, brackets wrap around the text once you select some text and type in a bracket. However, this is not the case when the preview box is active. In particular, if I type $$ something $$ then brackets wrap around selected test. Differently, if you trigger the preview box with $$ + return and then write something there, typing in a bracket will simply replace the selected text.

**Comment by abnerlee** [comment]
Yes, should be our bug

**Comment by abnerlee** [comment]
fixed in new version
