### ISSUE TITLE
The option for hiding image storage folders in the tree view.

### ISSUE THREAD

**Issue by gening** [typora/typora-issues#1452]
If the folder ends with the suffix specified in the default image storage option, it will be hidden under the tree view of files

**Comment by rnsdft** [comment]
Great idea ! 
I use -a shortcut key, and have too much .assets folders.

**Comment by abnerlee** [comment]
We don't provide options to hide folders, we do not want turn Typora into any IDE

**Comment by rnsdft** [comment]
If this is still actual, I did this using CSS
.file-library-node.file-tree-node[data-path$=".assets"] { display: none; }

**Comment by sahilrajput03** [comment]
Thanks to you guys for automatically hidinng folders which start with . at start.
Thats easter egg.!
