### ISSUE TITLE
No file dialog shown when export html with Mermaid Diagram

### ISSUE THREAD

**Issue by raytangRT** [typora/typora-issues#1455]
Typora version: 0.9.48(beta)

Sample .md file

```
```Mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts<br/>prevail...
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good! <> ```
```

No File Dialog shown
![no file dialog show](https://user-images.githubusercontent.com/30689714/39417514-4fb4b560-4c87-11e8-83b9-45bbf2dc04e0.gif)

Diagram not rendering

![diagram not rendering](https://user-images.githubusercontent.com/30689714/39417515-510cd8e8-4c87-11e8-9ea4-9df6e722fe72.gif)

**Comment by abnerlee** [comment]
should be fixed in new release
