### ISSUE TITLE
Typora Flatpak

### ISSUE THREAD

**Issue by danieldk** [typora/typora-issues#1456]
I have created an experimental Flatpak for Typora, mostly for personal use. This is related to  #583, but that issue is about AppImages.

https://github.com/danieldk/typora-flatpak

Todo:

* Support x86_32.
* Look at what files can be removed from the Flatpak.

You can build the Flatpak with:

flatpak-builder typora eu.danieldk.Typora.json --force-clean

Or build + do a user install with:
flatpak-builder --install typora eu.danieldk.Typora.json --force-clean --user

After that, Typora should be added to your favorite XDG-compliant desktop.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1457
