### ISSUE TITLE
The ampersand character & is not correctly encoded in urls

### ISSUE THREAD

**Issue by vocaviking** [typora/typora-issues#1458]
Hi,
I'm linking to files on my hard disk, which have an ampersand in their name.
For example: `./path/name with spaces & ampersand`.
This would be correctly linked with: `[Name](./path/name%20with%20spaces%20%26%20ampersand)`
However, this is not interpreted correctly by Typora.
At the moment you can use: `[Name](./path/name%20with%20spaces%20&amp;%20ampersand)`
But for some reason, the escape characters accumulate over time, so you get: `[Name](./path/name%20with%20spaces%20&amp;amp;amp;%20ampersand)`

**Comment by abnerlee** [comment]
Typora version?

**Comment by abnerlee** [comment]
Fixed in new release
