### ISSUE TITLE
Type lowercase equations in the code view, render the remaining text as italic

### ISSUE THREAD

**Issue by vocaviking** [typora/typora-issues#1459]
Hi,
If you go into the code view and type something like:
```Look at my nice equation: $x*0=0$ Do you like it?```
Then the text after the `_` is rendered as italic, even though it is not formatted that way.

**Comment by abnerlee** [comment]
Cannot reproduce this. What's you Typora version?

**Comment by vocaviking** [comment]
It's version 0.9.49 
And... it seems like I got the character wrong. `*` is a problem:
![screenshot](https://user-images.githubusercontent.com/11911990/39522383-4e35f578-4e12-11e8-984c-23655dc45429.png)

**Comment by abnerlee** [comment]
merge into #1638
