### ISSUE TITLE
Regression: File:New fails on multiple macOS desktops

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1464]
If I have multiple desktops, say A, B, C and D, and Typora has open windows on A and C, Typora's `File:New` or `⌘N` fails to do anything when on desktop B  and D.

**Comment by vassudanagunta** [comment]
`New Window` works. `New Tab` is grayed out, but that makes sense since no Typora window has focus when on B and D.  

`New` and `⌘N` does nothing, even on other desktop. They only work when I am looking at a desktop with an open Typora window. But even that's not always true: I just tried `New Window` (which works), but even now, with a Typora window on the desktop, `⌘N` still does nothing. If I switch to a desktop with an existing Typora window, `⌘N` will open a new doc for each time I press it. 

I didn't find a Typora log in Console.app.

**Comment by abnerlee** [comment]
So when `⌘N` does not work, there's no window focused, right?

If you focus on any Typora window, will `⌘N` work?

**Comment by vassudanagunta** [comment]
How does one focus on a Typora Window when there are no open Typora windows on the desktop? I am giving the Typora app focus (as evident in the menu bar) and then pressing `⌘N`. Or I choose `File:New` from the menu, in which case Typora obviously has focus. Neither works in 0.9.9.15.2. They both used to work as expected. Rebooting my Mac didn't help.

**Comment by vassudanagunta** [comment]
>> So when ⌘N does not work, there's no window focused, right?
>
> How does one focus on a Typora Window when there are no open Typora windows on the desktop?

@abnerlee Correction: ⌘N/New fails to work even if I have Typora window focused:

1. I switch to the desktop where I can create new Typora documents.
2. Create a new doc
3. Move it to the desktop where ⌘N/New it doesn't work.
4. Try ⌘N or File:New while this document has focus, and nothing happens. 
5. At the moment ⌘N and File:New only works on one desktop.
5. A note about the "working" desktop: It is the desktop that Typora opens all my open documents after I restart my computer or restart Typora. That seems to be another bug: If I remember correctly, Typora used to remember which desktop each open document belongs to, restoring them to the proper one on restart. It's not doing that now.

Have you been able to reproduce this?

**Comment by abnerlee** [comment]
Not yet, I don't know how to show Typora's menu without any focused window on other desktops..

On my macOS, it seems it will show menu of "Finder" if I switch too a new desktop without Typora's window opened.

**Comment by vassudanagunta** [comment]
> I don't know how to show Typora's menu without any focused windows on other desktops.

I thought you were a Mac user, @abnerlee! ⌘-Tab!

Whenever I have to write something, on whatever desktop I'm on, I ⌘-Tab to Typora and then ⌘N to get a blank document. I don't want to switch to a desktop with existing Typora windows because what I want to write is related to the project on the current desktop. 

I just realized that maybe you have `Mission Control:When switching to an application, switch to a Space with open windows for the application` enabled in System Preferences. You need to turn it off to repro the issue.

Can I download the previous version or two of Typora? One, this bug is really impacting my productivity, and two, it will help you isolate when the bug was introduced.

**Comment by abnerlee** [comment]
I see, I will check follow the steps.

History Release -> https://typora.io/dev_release.html

**Comment by vassudanagunta** [comment]
I reverted to 0.9.9.14 and the problem is gone / works perfectly.

**Comment by abnerlee** [comment]
Fixed in new release
