### ISSUE TITLE
when text is a URL the strike won't work 

### ISSUE THREAD

**Issue by Nify** [typora/typora-issues#1466]
Typora version:0.9.49(beta X64) 
OS:window10  /amd64
***
when text is a URL ,such as `https://typora.io`.
use the `~~URL~~` to strike this URL will don't work,it will be 
![screenshot0](https://user-images.githubusercontent.com/5094723/39557024-3bc8da04-4eb7-11e8-89d9-d1b45f9af374.png)

if one  more `~` add at end ,it will be
![screenshot1](https://user-images.githubusercontent.com/5094723/39557129-e4c432fc-4eb7-11e8-9a1f-ebd51cecbab7.png) 
it format a strikethrough text,but change into a wrong text that excess of one `~`.
***
This bug has appeared since the previous version.

**Comment by abnerlee** [comment]
Fixed in new release
