### ISSUE TITLE
Can't edit code block after update Typora

### ISSUE THREAD

**Issue by GreatBahram** [typora/typora-issues#1467]
After update Typora, I am able to edit code block as before, what I mean is that, there is any cursor in code block but outside code block everything is OK. I tried to edit by using keyboad and that does not work too.

`Typora Version`: `0.9.49-1`
`OS`:`Linux`

Thanks

**Comment by abnerlee** [comment]
What's the highlight language of your code block? Will it work if you change to default (empty) language for the code block?

**Comment by GreatBahram** [comment]
It does not matter, only it works fine for empty language, I've tested it for Python,JSON,Shell and etc . 
Mine was JSON by the way.

**Comment by abnerlee** [comment]
Fixed in 0.9.50

**Comment by GreatBahram** [comment]
That's right. I've tested it.
