### ISSUE TITLE
New file using right hand click menu from OSX Launcher Bar Icon

### ISSUE THREAD

**Issue by mrdanbrooks** [typora/typora-issues#1468]
Notepad, MacVim, and basically every other editor I have allows you to create a new file by right clicking on the app icon in the launcher bar and selecting "New File" or "New Window" from the menu. 

It would be great if Typora had this feature too. 

![newdoc](https://user-images.githubusercontent.com/5226494/39603336-fce60700-4ef5-11e8-8730-dd52694fb8f9.jpeg)

**Comment by AlexPasternak** [comment]
Sure, great idea. Here's Bear, FWIW:

<img width="172" alt="bear" src="https://user-images.githubusercontent.com/1819485/39607390-c1d3621c-4f08-11e8-9fa3-4333002ba839.png">

And TextMate, both of which have it:

<img width="333" alt="textmate" src="https://user-images.githubusercontent.com/1819485/39607394-c7c96680-4f08-11e8-85a7-cbc363b56c72.png">

**Comment by abnerlee** [comment]
Supported in new release
