### ISSUE TITLE
Pair autocompletion should happen adjacent to any non-whitespace

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#147]
When adding quotes, brackets or parenthesis around already typed text, pair autocompletion should now be triggered. For example, Say the following is already in your document:

    She said, That's what he said!

If I add a quotation marks before `That`, the right thing happens (no pair autocompletion). But when I type one after `said!`, I end up with the following:

    "She said, That's what he said!""
 
This was partially fixed in version 0.9.9.0, which is why the right thing happened for the first quotation mark above.

**Comment by vassudanagunta** [comment]
Found another situation where this bug manifests: Typing a bracket or parenthesis to the left of the first character in a paragraph. For example, given the following text:

`This paragraph is an editorial note, so needs to be put in square brackets.`

When I type "[" to the left of the word "This", the result is:

`[]This paragraph is an editorial note, so needs to be put in square brackets.`

**Comment by abnerlee** [comment]
should be fixed. Same behavior as sublime

**Comment by vassudanagunta** [comment]
Confirmed same behavior as Sublime and Atom, including the behavior when typing a quote immediately following punctuation, such as after the exclamation point at the end of a sentence as in my first example above.

But if Typora's intent is to be used for writing English or another human language as opposed to writing code (the purpose of Sublime and Atom), a quotation mark should not be auto-paired when typed adjacent to ANY text, including punctuation. It's not critical to fix this, but for writers this will be a common annoyance when pasting in a quote from another source and then adding quotation marks to either end of the quote.
