### ISSUE TITLE
Add page-break-after: avoid for headlines in PDF export.

### ISSUE THREAD

**Issue by timrosskamp** [typora/typora-issues#1472]
I love Typora. It's amazing for writing.

Exporting PDFs is also a straight forward process, but there's an issue that occurs alot when exporting PDF's. There are headings at the end of the page, witch are related to the content on the next page, witch is a really bad thing for printing out pages.

An approach to making this better is to add `page-break-after: avoid` to the heading, but this css rule is currently not implemented in any browser renderer.

**Comment by abnerlee** [comment]
Close since it is not an CSS issue, while Typora could only use CSS to control page break when printing

**Comment by abnerlee** [comment]
should be fixed in new release as a default behavior.

No need to set "page-break-after:avoid" now
