### ISSUE TITLE
Auto-name conflicted for saved pictures from the internet

### ISSUE THREAD

**Issue by Darleey** [typora/typora-issues#1473]
If several unnamed(or hard to identify) pictures were downloaded from the internet in one(or less) second ,the current rule of renaming pictures would get the pictures' names conflicted ( Different original pics will appear as the same one ).

eg. https://mp.weixin.qq.com/s/g0VV2oq7bg4-l8jWt9_zdQ   
You may meet the same problem if you can visit the page at express speed.

**Comment by abnerlee** [comment]
@Darleey Typora/OS version?

And what's your config about images in Typora?

**Comment by Darleey** [comment]
@abnerlee 
Typora 0.9.51
Windows 10 1803
`Copy image to ./${filename}.assets`

**Comment by abnerlee** [comment]
Seems unable to reproduce in new versions
