### ISSUE TITLE
Loss of data, file size becomes 0kb

### ISSUE THREAD

**Issue by tongtie** [typora/typora-issues#1474]
Typora version： 0.9.29
OS： windows 10
When I turn off the computer, I usually save the file. But when it opened today, it found that the content was gone and the file size became 0kb：

![image](https://user-images.githubusercontent.com/2959046/39679241-bd24288e-51cc-11e8-9544-5747bda030d2.png)

Typora/draftsRecover：
![image](https://user-images.githubusercontent.com/2959046/39679256-f98d247e-51cc-11e8-9ffc-0076a22afb0d.png)

**Comment by abnerlee** [comment]
version 0.9.29 is too old, please check updates
