### ISSUE TITLE
Resized images do not reflect size change in view

### ISSUE THREAD

**Issue by joeyhkim** [typora/typora-issues#1475]
According to [this](https://support.typora.io/Resize-Image/) link, images can be resized using the html tag \<img width=50%>.

These resized images show up as full size in the view instead of resizing. Viewing the markdown through a viewer online such as Github or GitLab shows the images resizing properly. 

The images DO show up as resizing properly in the view if you use the style attribute, but GitLab doesn't support this attribute.

**Comment by abnerlee** [comment]
@joeyhkim  What is the exact syntax/source code you were using?

And which theme did you use?

**Comment by joeyhkim** [comment]
Hi,
I am using the GitHub style. Using different styles does not appear to fix the issue.
I've posted some sample code on GitHub here demonstrating the issue:
[https://github.com/joeyhkim/TyporaBugDemo](https://github.com/joeyhkim/TyporaBugDemo)

**Comment by abnerlee** [comment]
Fixed in new release
