### ISSUE TITLE
Typora treats international characters incorrectly as word boundaries

### ISSUE THREAD

**Issue by torfason** [typora/typora-issues#1476]
When double clicking a word that contains international characters, only the first part of the word is selected. 

#### Reproduction:

* Create a new markdown document in Typora.
* Add a word containing international characters, such as "Encyclopædia"
* Double-click the front half of the word

#### Expected and actual behavior:

* Expected behavior:
  * The whole word should be selected
* Actual behavior:
  * Only the front part of the word ("Encyclop") is selected, and the second part ("ædia") is not

#### Typora version:
* Version 0.9.9.15.3 (0.9.9.15.3)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by torfason** [comment]
Fix confirmed :-)
