### ISSUE TITLE
Table resize widget: moving pointer to edit text fields changes values

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1478]
The table resize widget has very useful text fields for changing the dimensions of the table. But if one moves the mouse pointer directly from the button that calls up the widget to the fields, the values in the fields get changed because one passes over the graphical sizing interface. One has to make sure to move the pointer around that part to get to the field to, for example, add a column or row by incrementing a field by one. 

Once solution is to move the text fields to the top. But perhaps the best solution is for both the graphical sizing interface and the text fields to revert to the current size of the table when the mouse pointer leaves it.

**Comment by abnerlee** [comment]
Fixed in new release
