### ISSUE TITLE
Default filename logic fails in the presence of YAML front matter  

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#148]
Normally Typora automatically uses the first paragraph as the default filename when saving a file. But if there is YAML front matter (i.e. at the beginning of the doc), the default filename is simply a "-".  

YAML front matter or any other metadata should be ignore by the default filename logic.

**Comment by abnerlee** [comment]
should be fixed

**Comment by vassudanagunta** [comment]
confirmed! thanks.
