### ISSUE TITLE
Save without asking when switch files on side panel

### ISSUE THREAD

**Issue by tridc** [typora/typora-issues#1480]
I'm facing an issue with this feature on Typora 0.9.9.15.3 (MacOS Sierra)
After turning it on, restarting typora, opening preferences again and found that option was unchecked. Auto save feature still works fine but sometimes it doesn't.
On Mac settings, I keep Ask to keep changes when closing documents checked

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by tridc** [comment]
For latest version, this feature doesn't work properly.
I edit file and try to switch file in a small amount of time (a few second), it works. But if I leave editted state for a longer time then switching, it shows a save dialog
