### ISSUE TITLE
Mac OS keyboard shortcuts in tables inconsistent

### ISSUE THREAD

**Issue by tektrip-biggles** [typora/typora-issues#1481]
On Mac OS, the keyboard shortcuts ⌘ ← and ⌘ →  move the cursor to the start and end of a line. These work fine in Typora. In tables, these move the cursor to the start and end of the cell, which also makes sense.

Normally, ⌘ ⇧ ← and ⌘ ⇧ →  perform the same action while highlighting any text between the start and end cursor positions. Normally in Typora this works as expects, other than in tables, where the ⇧ modifier seems to be ignored.

Since replacing the existing text within a cell is a very common and oft-repeated task, a quick ⌘ ← then ⌘ ⇧ →  to do this would be a significant productivity improvement.

Many thanks for creating an excellent product, by the way!

**Comment by abnerlee** [comment]
>On Mac OS, the keyboard shortcuts ⌘ ← and ⌘ → move the cursor to the start and end of a line. These work fine in Typora. In tables, these move the cursor to the start and end of the cell

This should be the spec on macOS, it is same in notes.app

> Normally, ⌘ ⇧ ← and ⌘ ⇧ → perform the same action while highlighting any text between the start and end cursor positions. Normally in Typora this works as expects, other than in tables, where the ⇧ modifier seems to be ignored.

Fixed in new release
