### ISSUE TITLE
Got two scroll bar in the source code mode

### ISSUE THREAD

**Issue by Jacky-88** [typora/typora-issues#1482]
Version: 0.9.50 beta
OS: Windows 10.
![image](https://user-images.githubusercontent.com/29943110/39864515-675d027e-547c-11e8-984a-4dbf343709c1.png)
When I entered the Source code mode I got **two scroll bar**...
And the scroll function is just buggy.
While using mouse to drag the scroll bar , the whole page will back to where it started scroll...
Fix it soon please! : )
Thank you for providing such an awesome app!

**Comment by abnerlee** [comment]
What theme do you use? Could you attach or send us (<hi@typora>) the sample md file that can reproduce this bug?

**Comment by Jacky-88** [comment]
The theme is *Whitey*.
MD file has attached.

**Comment by abnerlee** [comment]
Fixed in new release
