### ISSUE TITLE
Cannot apply »Ignore whitespace and single line break« on Windows

### ISSUE THREAD

**Issue by mruessler** [typora/typora-issues#1483]
When I go to the options and set [Whitespace / Line Break] [When Writing] to »Ignore whitespace and single line break«, the change is not saved. After closing and reopening, »Preserve whitespace and single line break« is applied again. It works for [Export / Print].
I am using 0.9.50(beta) on Windows 10.

**Comment by joonro** [comment]
I have the same issue - at least I can change it in `Edit` -> `Whitespace and Line Breaks` menu.

**Comment by abnerlee** [comment]
Fixed in new release
