### ISSUE TITLE
Format not applied when there is a line break

### ISSUE THREAD

**Issue by bob6664569** [typora/typora-issues#1484]
this markdown:
```markdown
**Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi 
pharetra quam nec posuere accumsan.**
```

renders as 
```
**Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pharetra quam nec posuere accumsan.**
```
even when disabling `Preserve sequential whitespace and single line break`

**Comment by GreatBahram** [comment]
Yeah, that's true, 
when you have line break, you should select via mouse and then bold them and it will renders as follows:
```
**Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi** 
**pharetra quam nec posuere accumsan.**
```
As you can see, it's like there are two different line, actually markodwn don't care about break line. I think it's OK. I can't see any problem here

**Comment by vassudanagunta** [comment]
Please check the [GFM spec](https://github.github.com/gfm/) to see if your desired behavior is legit Markdown. If not, Typora is already doing the right thing.

**Comment by Zegnat** [comment]
> Please check the GFM spec to see if your desired behavior is legit Markdown.

As far as I can see, the described behaviour is that of [example 395](https://github.github.com/gfm/#example-395). This shows that [soft line breaks](https://github.github.com/gfm/#soft-line-breaks) are accepted within [emphasis and strong emphasis](https://github.github.com/gfm/#emphasis-and-strong-emphasis). If Typora is not allowing the soft line break, that is not in accordance with the spec.

**Comment by PhelypeOleinik** [comment]
> Please check the GFM spec to see if your desired behavior is legit Markdown.

Resurrecting this issue, it looks like Typora does not allow soft breaks, neither for emphasis ([example 395](https://github.github.com/gfm/#example-395) as Zegnat pointed out) nor for block comments ([example 146](https://github.github.com/gfm/#example-146)), as reported in issue [#1289](https://github.com/typora/typora-issues/issues/1289).

---
Besides, this:
```
a<!-- hello
world -->b
```
renders as:

> ab

here at GitHub, and at StackExchange (the ones I tested). But Typora doesn't seem to understand this :/

**Comment by abnerlee** [comment]
Followed the CommonMark spec in new release
