### ISSUE TITLE
Open file in current tab

### ISSUE THREAD

**Issue by capravictoriae** [typora/typora-issues#1485]
When searching and opening a file with the <kbd>Ctrl</kbd> + <kbd>P</kbd> option, this opens the file in a new tab/window (depending on OS). 
Is there an option to open the searched file in the current tab in a more minimalistic way? I mean, just having one file opened at a time? This is the behaviour you get when you just click in a different file in the Tree View for example. The difference is you search the file through the <kbd>Ctrl</kbd> + <kbd>P</kbd> dialog.

Related #1000

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1000
