### ISSUE TITLE
Can't open typora window on win10 1803

### ISSUE THREAD

**Issue by Dinghow** [typora/typora-issues#1487]
After I open typora, I can see it on my task bar and task manager,and if I press ALT+tab,I can see the thumbnail of typora too.But I can't switch to its window,and can't open muti-desktop of windows10.

![](http://ouluvpd0z.bkt.clouddn.com/%E6%97%A0%E6%A0%87%E9%A2%98.png)
![](http://ouluvpd0z.bkt.clouddn.com/%E6%97%A0%E6%A0%87%E9%A2%981.png)

**Comment by abnerlee** [comment]
Typora version?

**Comment by Dinghow** [comment]
@abnerlee 0.9.50,and I found if I open two typora,the latter is all right,just the former has that problem

**Comment by abnerlee** [comment]
Try close the Typora window and reopen again? Can it be solved?

And could you send `C:\Users\{username}\AppData\Roaming\Typora\typora.log` to us (<hi@typora.io>)

Best Regards

**Comment by Dinghow** [comment]
Thx very much.After I restarted my computer,this problem was solved.I think that may be due to win10 1803 version,I will roll-back to 1709.
