### ISSUE TITLE
a possible alternative http://www.bear-writer.com/

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#1488]
The author of Typora didn't willing to open source which could speed up the dev much faster, nor being able to make it a quite perfect commercial product. So finally the rival comes...

**Comment by abnerlee** [comment]
Typora is a general-purpose Markdown editor, not a note-taking app.

We do have plans for making a note-taking app, but that is not named as "Typora"

**Comment by vassudanagunta** [comment]
_Bear_ is not open source, stores all you writing in its own database not on the file system (so you can't sync across devices unless you pay $15 per year, not access your work with other tools unless you manually export from the database each time), and a bunch of other limitations. 

@leewi9 , stop being a jerk. You've made your desire known before, and the answer was given: Typora will not be open source. If you only want to use open source, then go find some and use it. Stop trolling @abnerlee and the Typora user community.   

Your posts aren't intended to help other people. Your intent is only to bully @abnerlee, and to just be a entitled jerk. I'd be so much in favor of @abnerlee banning you from this repo again.

**Comment by Leelddd** [comment]
@abnerlee is there any progress with note-taking app?
