### ISSUE TITLE
希望可以设置标题和文件名同步

### ISSUE THREAD

**Issue by cooper1x** [typora/typora-issues#1489]
当文件新创建的时候，另存为的标题默认是和一级标题一致的。
所以希望当一级标题修改时，能够同时改变文件名。这样就不用修改两次了。

**Comment by cooper1x** [comment]
另外，在typora侧边栏新建文件的时候，希望保存后能再正文中添加一个一级标题。这些不一定是默认就这样，可以让用户手动开启「同步正文一级标题和文件名」的功能。

**Comment by cooper1x** [comment]
听说typora作者是中国人，所以就用中文了，不便之处还请见谅。

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/935
