### ISSUE TITLE
Default filename should not include Markdown markup

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#149]
Normally Typora automatically uses the first paragraph as the default filename when saving a file. If the first paragraph is "The story of my life", it very conveniently suggests `The story of my life.md` as the default filename when I save the new file. 

But if the first line is "#The story of my life" (i.e. a Markdown heading), it suggests `#The story of my life.md`. Few people would want the `#` to be part of the filename.

**Comment by abnerlee** [comment]
Hi, @vassudanagunta I checked in lastet version, but if first line is a markdown heading, typora would only suggest its heading content without the `#` mark. So I think this bug may not exist, could you confirm it ?

**Comment by vassudanagunta** [comment]
I tested all of the following individually and they all passed:

```
# test title

#test title

## test title

##test title

#### test title

*test title*

**test title**
```

In all cases the suggested file name was the same as the rendered text, not the raw markdown, which is perfect.

Thank you!
