### ISSUE TITLE
Could not upload picture which is including Chinese character in os x

### ISSUE THREAD

**Issue by bjzhang** [typora/typora-issues#1490]
Hi,

I am new for Typora. It is a cool software for markdown. Meanwhile I found that I could not upload picture through iPic if the picture name includes Chinese. Typora say: The file isn't accessable. If I rename it to English, it could upload through iPic.

I am not sure is an issue in Typora or iPic. 

Thanks

**Comment by abnerlee** [comment]
Fixed in new release
