### ISSUE TITLE
Strange Empty Code Line in PDF

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1492]
Typora version: 0.9.50
Windows version: Windows 10 1803(17134.48)

![qq 20180513235757](https://user-images.githubusercontent.com/33177912/39969105-ca99579a-5709-11e8-97cc-4a3153a43bf3.png)

![qq 20180513235811](https://user-images.githubusercontent.com/33177912/39969107-ccec403e-5709-11e8-890d-6dafb8d7c3e8.png)

![qq 20180514000047](https://user-images.githubusercontent.com/33177912/39969111-dfd1b8dc-5709-11e8-8312-506375fa507b.png)

I have tested and it turns out that **every** code block will have an empty line at the top (you can try a "hello world"). Some will have one at the bottom(fig. 3), but I have't found out the condition which will cause one at the bottom. Maybe I can attach a sample file (iff you need).

**Comment by abnerlee** [comment]
Please attach the sample. And which Theme did you use?

**Comment by abnerlee** [comment]
Fixed in new release
