### ISSUE TITLE
Problem about code blocks at the end of the file

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1493]
If I open the file which contains codes at the end of the file, that block won’t be highlighted. The only solution is that I change the end of the file.

But this problem won’t happen if there are other stuffs at the end of the file, even a return can prevent it.

Typora version: 0.9.50

Windows version: Windows 10 1803(17134.48)

**Comment by UnnamedOrange** [comment]
Maybe I need a direct email link to attach the sample......In fact I posted this issue to hi@typora.io a few days ago, but I haven't received any reply.

**Comment by abnerlee** [comment]
Hi, i found it, seems it got filtered by mistake.

**Comment by abnerlee** [comment]
Fixed in new release
