### ISSUE TITLE
Wrong appearance with bold/footmark/math/etc. elements

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1494]
![qq 20180514004351](https://user-images.githubusercontent.com/33177912/39969553-2663ec42-5710-11e8-9dd3-e508bea4cd42.png)
![qq 20180514004422](https://user-images.githubusercontent.com/33177912/39969554-272155fc-5710-11e8-8bec-fc70c442284a.png)
![qq 20180514004433](https://user-images.githubusercontent.com/33177912/39969555-27bad42a-5710-11e8-8247-2dbd95ff1c13.png)
![qq 20180514004517](https://user-images.githubusercontent.com/33177912/39969556-285a99c4-5710-11e8-920b-6da4d786a306.png)

I don't recognize the reasons why this happened, but it did.

You can reply to me so that I can reply to attach the sample:)

Typora: 0.9.50
Windows: Windows 10 1803(17134.48)

**Comment by UnnamedOrange** [comment]
At first I thought the problem may be about the footmarks, but fig. 4 stopped my this thought.

**Comment by abnerlee** [comment]
seems duplicate with https://github.com/typora/typora-issues/issues/1446

Current workaround is to use whitespace instead of tab on line starting

**Comment by abnerlee** [comment]
Also, could you send us the sample md file ? (hi@typora.io)
