### ISSUE TITLE
AppleSpell in IME mode

### ISSUE THREAD

**Issue by sicilian-lizard** [typora/typora-issues#1495]
It seems to me the AppleSpell is working hard when an IME is on, this seems unnecessary.

Spell-checking is good for the text in the document, but usually not useful to the code for the IME candidates, say,  checking the code "shanghai" before you commit to the document the characters "上海“ ”伤害“ is usually unnecessary.

**Comment by abnerlee** [comment]
Typora won't decide the timing for spell checking, this seems a system behavior

**Comment by sicilian-lizard** [comment]
OK, thanks for the info, but:

AppleSpell CPU usage when typing code in IME in CotEditor, Notes, etc, is 0.0%.

In Typora, AppleSpell CPU usage can go all the way up when the input code in IME gets long, too high to be ignored, maybe.

**Comment by abnerlee** [comment]
Only happens when you using IME?

**Comment by sicilian-lizard** [comment]
It happens with/without the IME, only I thought it's unnecessary when typing code in IME.

BTW, Applespell CPU usage is 82% in Typora, 0% in CotEditor and Notes, when typing randomly fast, with/without using IME.
