### ISSUE TITLE
Win32: Update fetches x64 binaries

### ISSUE THREAD

**Issue by GoLangsam** [typora/typora-issues#1496]
I'm on `Win7 32-bit` (for historic reasons) and using your integrated Update checker I fetched and installed.

Upon attempt to relaunch `Win7` blocks execution of `Typora.exe` telling:
"The version ... not compatible ... x86 or x64 ..., and then contact the software publisher"

Note: I've already encountered this in a prev. version, but forgot to report.

"Workaround" is to download and install full version afresh.

**Comment by abnerlee** [comment]
Should be fixed

**Comment by GoLangsam** [comment]
Happy to confirm @abnerlee latest Update :+1: :ok: - :bowing_man:
