### ISSUE TITLE
Cannot use inline LaTex after upgrading (0.9.51-1,Linux)

### ISSUE THREAD

**Issue by OmmyZhang** [typora/typora-issues#1497]
![2018-05-15 14-02-49](https://user-images.githubusercontent.com/17777309/40039385-ce9709a6-5848-11e8-882c-5eefb7385d7a.png)

before upgrading(pdf):
![2018-05-15 14-06-14](https://user-images.githubusercontent.com/17777309/40039541-5a3d2efe-5849-11e8-9df5-ec757e97999c.png)

now(pdf):
![2018-05-15 14-06-26](https://user-images.githubusercontent.com/17777309/40039556-63dd1c12-5849-11e8-839a-94c1c0c1d532.png)

**Comment by OmmyZhang** [comment]
@abnerlee  thx~

**Comment by Martin1024** [comment]
So how to modify the preference config file in detail?
