### ISSUE TITLE
Double click and formatting

### ISSUE THREAD

**Issue by heyoni** [typora/typora-issues#1499]
Hello all,

First of all, I want to say typora is an amazing program...you guys made me defect from bear-writer (which is really nice). I have a minor issue I wanted to report.

Basically if I double click to select a line of text, then use a keyboard shortcut to format it, it formats the line properly, but also adds a set of the same format tags to the next line below. The set of format tags on the second line are all at the beginning and don't surround any text and as far as I can tell, this happens when bolding a line (ctrl-b on debian).

Let me know if there's anything else I can do to help you reproduce it.

Thanks.

**Comment by GreatBahram** [comment]
Hi @heyoni 
I'm using Typora on ubuntu, and I didn't get this issue, I mean it works fine for me. When I select a line and try to format it by using keyboard shortcut it works like a charm and it didn't format below or above line at all.
Can explain this issue more or show it and please specify the version you used.
Thanks

**Comment by heyoni** [comment]
Are you selecting the entire line by double-clicking it? What happens when you do that is it selects the newline character at the end too which causes the formatting to be applied to both lines.

**Comment by GreatBahram** [comment]
Yes, you're right. That's certainly a bug

**Comment by abnerlee** [comment]
Fixed in new release
