### ISSUE TITLE
Drag and Drop Images from web

### ISSUE THREAD

**Issue by rahuldave** [typora/typora-issues#15]
One can drag and drop images from files. It works beautifully.

I'd like to drag and drop images from web. This will be a killer feature to take notes. 

Currently I capture image URL and use it in markdown, which works, but doing this for various media will make for a very interactive set of notes.

**Comment by xxf1995** [comment]
Yeah. It would be great!!

**Comment by abnerlee** [comment]
Drag & drop to insert images from web works fine with Typora and Chrome. 

Or do you mean other browsers no work or this feature has bug?
