### ISSUE TITLE
Inline math is not turned on by default after 0.9.51 update

### ISSUE THREAD

**Issue by kwon0408** [typora/typora-issues#1500]
I was surprised when opening documents written with previous versions of Typora, and all the inline math formulas were shown as raw codes like `$4 \times 4$`. Later I found that there is an option in *Preferences*, but it was turned off after update.

Is this just a bug, or intended to be a new policy?

**Comment by abnerlee** [comment]
We changed inline-math for opt-out to opt-in, so enable it in preference panel explicitly is needed
