### ISSUE TITLE
space / line break issue when pasting text copied from/to firefox

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#1502]
When copying blocks of text from web pages, Typora will seemingly randomly insert extra spaces between words. Looking at the HTML code of the web pages I copied from, there is no space.

For example, copying this paragraph from [https://github.com/typora/typora-issues](https://github.com/typora/typora-issues):

> Typora is commercial software (not open source), but is free during beta. Typora on GitHub supports collaboration between its developer, Abner Lee, and its user community, providing a place to transparently report issues, collect feedback and discuss future direction. It also provides open source resources for user customization of themes.

When pasting into Typora, an extra space in inserted between **and** and **discuss** and between **for** and **user**. 

![image](https://user-images.githubusercontent.com/19582721/40187689-1c3c7cb2-59c6-11e8-9804-da37d1dc51db.png)

Pasting that same text into another editor (e.g., Notepad++) does not add those spaces. Viewing the source code in Typora simply shows there are two spaces; there's not extraneous code.

I can repeat this from many websites and using any Typora theme. I'm using Typora 0.9.51 on Windows 10.

**Comment by GreatBahram** [comment]
This is not true on Linux.

**Comment by xebico** [comment]
More info: It appears to happen every 70 characters.

**Comment by abnerlee** [comment]
This works fine in my test -- paste will results two paragraph, not quite like your screenshot.

@xebico Which browser did you use ?

**Comment by xebico** [comment]
I'm using the latest Firefox -- 60.0.1. And what d'ya know, it doesn't happen in Chrome. I never suspected it could be the browser. Duh!

**Comment by coiby** [comment]
In my case, copy the paragraph from https://github.com/typora/typora-issues opened by firefox:

> Typora is commercial software (not open source), but is free during beta. Typora on GitHub supports collaboration between its developer, Abner Lee, and its user community, providing a place to transparently report issues, collect feedback and discuss future direction. It also provides open source resources for user customization of themes.

becomes

![image](https://user-images.githubusercontent.com/1511656/52785581-46f07400-3093-11e9-8ac9-60c1f2e95d7e.png)
i.e., an extra newline instead of an extra space is inserted between **and** and **discuss** and between **for** and **user**

**Comment by xebico** [comment]
Yeah, I'm still having the problem with both Firefox and Thunderbird (which isn't a surprise). 
Even odder, if I try to search for two spaces and replace them with one space, Typora doesn't find any. (If I paste from Typora into Notepad, though, Notepad _does_ find the two spaces.)

This _only_ happens with Typora. Pasting from Firefox/T'bird into any other program doesn't add those extra spaces.

So yeah, something is definitely wonky.

**Comment by abnerlee** [comment]
I have tried with Firefox, but seems not reproducible any more

**Comment by xebico** [comment]
Honest and for true, it's still happening with the latest version of both Typora and Firefox! Here's a snippet from the New York Times. Every 70 characters Typora adds an extra space. I'm not crazy — honest! :)

![1-nyt](https://user-images.githubusercontent.com/19582721/80968581-34707080-8de6-11ea-8847-8952f6047f1c.jpg)
![2-typora](https://user-images.githubusercontent.com/19582721/80968584-35a19d80-8de6-11ea-9961-a3ea9012b300.jpg)
![3-typora](https://user-images.githubusercontent.com/19582721/80968590-376b6100-8de6-11ea-9ee0-62f4ac7773ff.jpg)

**Comment by abnerlee** [comment]
So, the extra line break are gone. While extra spaces are still there?

**Comment by xebico** [comment]
I never had a problem with line breaks — it was always just an extra space every 70 characters. And yep, those extra spaces keep showing up. Crazy, huh?

**Comment by maaldheefee** [comment]
I've the same issue. Only with Firefox and only when pasting with formatting. But if I paste as plain text, no extra spaces are inserted.

**Comment by maaldheefee** [comment]
I checked the clipboard with [clipview](http://www.peterbuettner.de/develop/tools/clipview/)

![image](https://user-images.githubusercontent.com/16198035/88569018-46fbee00-d053-11ea-8714-74c9476a6ddc.png)

Firefox breaks the lines so there's a space and end of line character.

Here's the same thing copied from Edge.

![image](https://user-images.githubusercontent.com/16198035/88568886-0f8d4180-d053-11ea-835d-7cc115db4ca8.png)
