### ISSUE TITLE
Minor typos in Preferences

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#1505]
Preferences continues to have some minor typos and mistakes that should get cleaned up for eventual 1.0 release.

<img width="563" alt="screen shot 2018-05-18 at 10 19 17 am" src="https://user-images.githubusercontent.com/1819485/40239937-69eb1cec-5a85-11e8-9f14-d83bd7959124.png">

* Should read: "... when last window *is closed*"
* "overwritten" should be "overridden"
* Tooltip should mention real name of option and its place in sysprefs, so I believe full should read: "This option may be overridden by "Close windows when quitting an app" in System Preferences > General".

![screen shot 2018-05-18 at 10 25 31 am](https://user-images.githubusercontent.com/1819485/40240294-40773f02-5a86-11e8-9b43-89d78337d4fa.png)

- As mentioned before, "apply ... for" is unidiomatic. Top options should read "Only apply to quotes ...". "menu bar" is also typically two words in en-US (see https://en.wikipedia.org/wiki/Menu_bar).
- "Pretty indentation" does not need its second word capitalized. It's also not clear what this option does and I always expect the little preview next to it to be updated when this bullet is toggled, but nothing happens.
- For images, also "apply ... to", or if you really want to keep for, use "Use" instead. E.g., "Use above rules for local images"
- Markdown should be capitalized
- Keyboard shortcuts are traditionally shown with capital letters, e.g., <img width="58" alt="image" src="https://user-images.githubusercontent.com/1819485/40240468-9e419592-5a86-11e8-8b24-bc63a0f4a46e.png">
- Last option sentence does not need period at the end

**Comment by abnerlee** [comment]
Fixed in new release
