### ISSUE TITLE
Inline math not working

### ISSUE THREAD

**Issue by cupofcalculus** [typora/typora-issues#1507]
I type '$' and hit the Esc key, but no preview comes up.  Even when I use the example from the Markdown Reference page on your site, $\lim_{x \to \infty} \exp(-x) = 0$, it doesn't convert to TeX properly.  I've tried uninstalling, reboot, and reinstalling Typora, and still doesn't work.  I even tried opening up old typora files that used to be converted to TeX correctly, but now no longer do.

The math block still works, but inline math doesn't.

**Comment by abnerlee** [comment]
We changed inline math from opt-out to opt-in, so please enable it in preferences panel explicitly.

**Comment by abnerlee** [comment]
Inline math is considered as an advanced feature, by default, $ is should just mean "dollar" sign.

We also don't want power users to use Typora even without opening preference panel, we hide settings/features there.

**Comment by zianhu7** [comment]
I have the exact same issue - I turn on Inline Math under Format (linux), yet it still does not compile to TeX upon input. I have upgraded to the newest version, but this issue still persists. Another interesting behavior is that the Inline Math option disappears after I select it under the Format dropdown.

**Comment by abnerlee** [comment]
#1915

**Comment by abnerlee** [comment]
#1497

**Comment by abnerlee** [comment]
#1506

**Comment by ElenoreChang** [comment]
> We changed inline math from opt-out to opt-in, so please enable it in preferences panel explicitly.

From the product level, some tips on the UI would be convenient so that users like us would know that it's a new feature instead of a bug.

**Comment by JiYou** [comment]
Try this 

![image](https://user-images.githubusercontent.com/448253/91955664-20a62e00-ed36-11ea-9cc4-4c6dc7991764.png)

**Comment by Darel13712** [comment]
This issue is old but I couldn't figure out why my math does not work. Worst decision ever, guys.

**Comment by abnerlee** [comment]
@Darel13712 newer bug is in #4040

But please check updates again, we just fixed it

**Comment by BruceZu** [comment]
fxxking issue. without it enabled why I use the typora.

**Comment by nosarthur** [comment]
I cannot pick the inline math checkbox 

1.6.0-dev
<img width="393" alt="image" src="https://user-images.githubusercontent.com/22625224/234381133-775166d9-24a5-4989-a72d-3fab2a3c4fb9.png">

**Comment by abnerlee** [comment]
@nosarthur fixed in 1.6.1-dev

**Comment by thomasw-mitutoyo-ctl** [comment]
Inline math was also not working in version 1.7.6.
Upgrading to 1.9.5 helped.
