### ISSUE TITLE
DevTools for Mac

### ISSUE THREAD

**Issue by lukejanicke** [typora/typora-issues#1508]
Is it possible to enable DevTools for Mac? I know some other Electron apps on Mac have DevTools enabled. I want to develop some themes on my Mac but it’s really slow without DevTools.

**Comment by abnerlee** [comment]
Yes. 

1. enable `debug mode` from `Help` menu
2. click "Inspect Elements" from context menu.

**Comment by d2iq-shadowbq** [comment]
The standard HOTKEY for DevTool bars does not work, you just get a chime.
