### ISSUE TITLE
Inline math not working

### ISSUE THREAD

**Issue by ZeframLou** [typora/typora-issues#1510]
After upgrading to 0.9.51, inline math simply stopped working. Math blocks are still good. Problem persists after reinstalling.

OS: Windows 10 Home 1709 64 bit

**Comment by abnerlee** [comment]
please search the existing closed issues

**Comment by abnerlee** [comment]
#1507

**Comment by abnerlee** [comment]
#1506

**Comment by abnerlee** [comment]
#1497
