### ISSUE TITLE
Failed to install Typora on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by ZayneHuang** [typora/typora-issues#1511]
According to the instruction by [https://typora.io/#linux](url), after typing the command `sudo add-apt-repository 'deb https://typora.io/linux ./'`, there are errors as following:

> Ign:8 https://typora.io/linux ./ InRelease                                   
> Err:9 https://typora.io/linux ./ Release    
>   Could not handshake: The TLS connection was non-properly terminated. [IP: 108.61.207.230 443]
> Reading package lists... Done               
> E: The repository 'https://typora.io/linux ./ Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

Great thanks for helping!!

**Comment by abnerlee** [comment]
> Could not handshake: The TLS connection was non-properly terminated. 

This is a network issue.

Please confirm you could access to `https://typora.io`, and then try again
