### ISSUE TITLE
URLs with '~' or '@' not parsed correctly

### ISSUE THREAD

**Issue by dooof** [typora/typora-issues#1515]
URLs containing  the character ~ or @ are not parsed correctly.  In the case of '~' it seems to be dependent on how many levels down it is.  Examples:
www.google.com   (works correctly)
www.google.com/abc  (works correctly)
www.google.com/~abc  (works correctly)
www.google.com/abc/~abc  (doesn't work properly)
www.google.com/abc@abc.com  (doesn't work properly)

As a workaround, I can surround the URL with < >, but this is often a pain when copying and pasting URLs into my doc.

**Comment by abnerlee** [comment]
Fixed in new release
