### ISSUE TITLE
Freeze in Nautilus

### ISSUE THREAD

**Issue by sebszyller** [typora/typora-issues#1516]
9/10 times Typora freezes the whole system when I try to open a new folder. As soon as I open the file browser it hangs. The behaviour is present on clean install of Ubuntu 18.04 (technically officially supported) and on Fedora 28 (via binary) so minimum reproducible case is easy to get.

**Comment by TheMesoria** [comment]
Negative on that. Could not reproduce - might already be fixed, or your own software problem.

Tested on:
Ubuntu:
- 17.10.1
- 18.04

**Comment by con-f-use** [comment]
I have the same problem on 18.04.

**Comment by NanerLee** [comment]
I have the same problem on 18.04.

I can reproduce this case by:
1. open typora
2. select Files in the view of Files and Outline
3. select Open Folder ... and select Open Folder ... in locations
then it will popup a nautilus window and the system will freeze

what's more , if i select Open Folder in File menu, it will work well

**Comment by abnerlee** [comment]
#1756
