### ISSUE TITLE
Multiple-line math blocks

### ISSUE THREAD

**Issue by shreevatsa** [typora/typora-issues#1517]
In most places (e.g. math.stackexchange.com or GitHub pages with MathJax enabled) if I type mathematics across multiple lines, it just works:

```
$$\begin{align}
(a+b)^2 &= (a + b)(a + b) \\
&= a^2 + ab + ba + b^2 \\
&= a^2 + 2ab + b^2
\end{align}$$
```
but in Typora, I have to either type it all on one line, as
```
$$\begin{align}(a+b)^2 &= (a + b)(a + b) \\&= a^2 + ab + ba + b^2 \\&= a^2 + 2ab + b^2\end{align}$$
```
or put up with it not being rendered (and look at the rendered output wherever I'm ultimately going to use the `.md` file I've created with Typora).  Screenshot, with input on one line twice and then text on multiple lines:

<img width="770" alt="screen shot 2018-05-25 at 09 03 43" src="https://user-images.githubusercontent.com/767530/40554446-94db1e50-5ffa-11e8-90b5-c7d198159ab4.png">

Could Typora simply handle the multi-line math blocks?

FWIW, this is the MathJax config I'm using on GitHub pages (though it may be old/obsolete, and in any case irrelevant to Typora):
```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>
<script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```

**Comment by abnerlee** [comment]
It is supported in this way
```
$$
\begin{align}
(a+b)^2 &= (a + b)(a + b) \\
&= a^2 + ab + ba + b^2 \\
&= a^2 + 2ab + b^2
\end{align}
$$
```

Merge to #90

**Comment by shreevatsa** [comment]
That works for me, thank you!

**Comment by gandalfsaxe** [comment]
This doesn't work if you convert the source code directly with pandoc. I don't suppose there is a solution to that?

**Comment by gandalfsaxe** [comment]
Opened a separate issue here https://github.com/typora/typora-issues/issues/1582
