### ISSUE TITLE
Unable to convert existing text to a code block (surround with code fences)

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#152]
If I have existing text, I should be able to highlight it and select `Code Fences` from the `Paragraph` menu and have the highlighted text wrapped in code fences, just as I can select some text and select `Code` from the `Format` menu and have the text wrapped by back-ticks. 

Currently trying to do so results in an empty code block being created above the selected text. One has to cut and past the text into the code block.

**Comment by lukasberns** [comment]
This seems to be working in the version I have (0.9.9.10.9)

**Comment by abnerlee** [comment]
Yes, the feature has been added
