### ISSUE TITLE
Auto escape local path when insert image

### ISSUE THREAD

**Issue by xterat** [typora/typora-issues#1520]
> Typora version: 0.9.9.15.3
> OS: macOS 10.13.4

I find that the markdown file I create with Typora is incompatible with other markdown editors in terms of image file path. The  situation occurs when the image file path contain blanks.
When I drag a image file into Typora, it parse the image as
```
![Screen Shot 2018-05-17 at 15.41.29](Screen Shot 2018-05-17 at 15.41.29.png)
```
However, if I use other markdown editors(VS Code on MacOS, 1Writer on iOS) to open it, the image can't be parsed correctly. 
The correct image file path should be:
```
![Screen Shot 2018-05-17 at 15.41.29](Screen%20Shot%202018-05-17%20at%2015.41.29.png)
```
That is, replace blanks in the image file path with "%20".

Thank you for developing such a wonderful markdown editor!

**Comment by abnerlee** [comment]
relates #2198

**Comment by abnerlee** [comment]
this is supported as a option
