### ISSUE TITLE
Hybrid editing for Links never exits overwrite mode

### ISSUE THREAD

**Issue by PixelPartner** [typora/typora-issues#1521]
When in WYSIWYG / hybrid editing mode, both the `[]` and the `()` part cannot be properly edited. There's always a full character selected that will then be replaced. No inserting possible, only replacing and deleting.
My only work around is to switch to source edit mode and back again. 

I'm on Windows 8.1

**Comment by abnerlee** [comment]
This works fine in my test. Both click and use left/right key will put caret to the position where you could do inserting.

Could you tell me your Typora version, and steps to trigger "a full character selected that will then be replaced"?
