### ISSUE TITLE
Line break (windows x64 version)

### ISSUE THREAD

**Issue by masetto** [typora/typora-issues#1522]
Hello,
I have this markdown code (I use always source code):
```
line 1  
line 2  
line 3  
line 4  
```
Each line end with two blank space. But if I export to PDF only the first line break is rendered.

I have problems with pdf export also: Typora always export the current markdown...I don't know how to explain

**Comment by abnerlee** [comment]
There's some configuration in preferences panel, see https://support.typora.io/Line-Break/ for detail
