### ISSUE TITLE
image load failed

### ISSUE THREAD

**Issue by vision-ken** [typora/typora-issues#1525]
image load failed while image without a extension, eg:

```
![abc](https://user-gold-cdn.xitu.io/2018/1/26/16133167da8e4cb3?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)
```

![abc](https://user-gold-cdn.xitu.io/2018/1/26/16133167da8e4cb3?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)

**Comment by abnerlee** [comment]
Works fine in my testing, what's your Typora/OS version?

**Comment by CityHunterDHY** [comment]
> Works fine in my testing, what's your Typora/OS version?

![](https://jaeger.itscoder.com/assets/img/studio_tips/16-completestatement.gif)
macOs 10.14.1
typora 0.9.9.19.4

**Comment by CityHunterDHY** [comment]
> > Works fine in my testing, what's your Typora/OS version?
> 
> ![](https://camo.githubusercontent.com/acb8bd2b87c8f6df86b998f71204290c2f22b0ae/68747470733a2f2f6a61656765722e697473636f6465722e636f6d2f6173736574732f696d672f73747564696f5f746970732f31362d636f6d706c65746573746174656d656e742e676966)
> macOs 10.14.1
> typora 0.9.9.19.4

https://jaeger.itscoder.com/assets/img/studio_tips/30-analyzestacktrace.gif

**Comment by vision-ken** [comment]
typora: 0.9.9.19.4 (1355)
OS: mac os hign sierra(10.13.6)

**Comment by vision-ken** [comment]
your image work fine
```
https://camo.githubusercontent.com/acb8bd2b87c8f6df86b998f71204290c2f22b0ae/68747470733a2f2f6a61656765722e697473636f6465722e636f6d2f6173736574732f696d672f73747564696f5f746970732f31362d636f6d706c65746573746174656d656e742e676966
```
but this still break(but fine in browser:
```
https://user-gold-cdn.xitu.io/2018/1/26/16133167da8e4cb3?imageView2/0/w/1280/h/960/format/webp/ignore-error/1
```

**Comment by CityHunterDHY** [comment]
> @CityHunterDHY
> your image work fine
> 
> ```
> https://camo.githubusercontent.com/acb8bd2b87c8f6df86b998f71204290c2f22b0ae/68747470733a2f2f6a61656765722e697473636f6465722e636f6d2f6173736574732f696d672f73747564696f5f746970732f31362d636f6d706c65746573746174656d656e742e676966
> ```
> but this still break(but fine in browser):
> 
> ```
> https://user-gold-cdn.xitu.io/2018/1/26/16133167da8e4cb3?imageView2/0/w/1280/h/960/format/webp/ignore-error/1
> ```

this url is translated by github,the original url is "https://jaeger.itscoder.com/assets/img/studio_tips/30-analyzestacktrace.gif"

**Comment by dulm** [comment]
https://camo.githubusercontent.com/8f4b905318aa76651992b17e6f16f9e37314dc6b/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323031382f312f32362f313631333331363764613865346362333f696d61676556696577322f302f772f313238302f682f3936302f666f726d61742f776562702f69676e6f72652d6572726f722f31

this pic is also not show in my typora.    mac 0.9.9.24.2

**Comment by abnerlee** [comment]
#526
