### ISSUE TITLE
Not able to select text on MacOS 10.9 with version 0.9.9.16

### ISSUE THREAD

**Issue by cbertelli** [typora/typora-issues#1527]
As per the title, I'm not able either dragging with the mouse or with shift-arrow on the keyboard.

**Comment by cbertelli** [comment]
If I select with edit->Select All it seems to do nothing, but when copying I can paste in another markdown document.

**Comment by cbertelli** [comment]
The same with the arrow, the cursor do not move but things are selected. Not very practical...

**Comment by abnerlee** [comment]
Fixed in new release
