### ISSUE TITLE
about image problem(typora 0.9.52)

### ISSUE THREAD

**Issue by Yehnn** [typora/typora-issues#1530]
- typora version: 0.9.52
- system: win10

there are some proble:

+ Problems always occur when using `copy image to`
+ I suggest that  the image link in the document can choose not to change to the local path when saving an image to the local.
+ I suggest to can save the document's pictures to the local with one click, and each picture is named after the document's picture description.

Thank you for providing such a awesome application!

**Comment by luisspuerto** [comment]
I think it's linked? https://github.com/typora/typora-issues/issues/1550

**Comment by abnerlee** [comment]
Currently user can select image and choose copy it to local with one click. I think it is enough for most cases.
