### ISSUE TITLE
preview html elements

### ISSUE THREAD

**Issue by imagecser** [typora/typora-issues#1531]
Typora is good performing preview markdown elements.
However, html elements don't work well.
e.g.
![image](https://user-images.githubusercontent.com/22855893/40719135-09072e74-6445-11e8-96e6-0ec7afd9ef75.png)
I hope that **Typora** can preview html elements **instantly**.
just like:
![image](https://user-images.githubusercontent.com/22855893/40719187-4987f80c-6445-11e8-83e9-31132e7deafb.png)
Thanks!

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/909
