### ISSUE TITLE
Smart Dash converts to wrong type of dash

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#1534]
When Smart Dash is on, it converts two hyphens into an en dash, but it should be the longer _em_ dash.

**Comment by abnerlee** [comment]
three hyphens will be converted to em dash.

**Comment by andreizorila** [comment]
The problem is that in many languages, we need the em dash for starting every dialogue line. So it would be quite nice to type only two -- every time you want to start a dialogue, instead of typing --- characters. A lot of editors support either this (2 -- for em dash, or custom auto-replacements)

**Comment by abnerlee** [comment]
> The problem is that in many languages, we need the em dash for starting every dialogue line.

In that case, this seems to be a i18n issue, do we should do this in some languages without any extra settings like "(2 -- for em dash, or custom auto-replacements)"?

> A lot of editors support either this (2 -- for em dash, or custom auto-replacements)

Custom auto-replacements can be covered by #3021

**Comment by abnerlee** [comment]
Supported as an option in preferences panel

**Comment by andreizorila** [comment]
Thank you. Now, this editor becomes the best editor for writing fiction. :)
