### ISSUE TITLE
Inline math error when enabling "indent first line of paragraphs"

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#1535]
![tim 20180601170256](https://user-images.githubusercontent.com/33177912/40832321-a7f68a7e-65bd-11e8-84a7-be4ca27bcc3a.png)

This problem happens in every inline math.

Typora: 0.9.53
Windows: 1803(17134.81)

**Comment by abnerlee** [comment]
Fixed in new release
