### ISSUE TITLE
Couldn't export to latex file

### ISSUE THREAD

**Issue by g3org3** [typora/typora-issues#1537]
<img width="778" alt="screen shot 2018-06-04 at 1 57 18 pm" src="https://user-images.githubusercontent.com/2175676/40916228-4765e8f0-67ff-11e8-83c7-31e0c6ffc972.png">
And nothing happened . . .

**Comment by abnerlee** [comment]
What's your Typora/Pandoc version?

Could you send us (hi@typora.io), or attach the sample *.md file?

**Comment by g3org3** [comment]
Typora 0.9.9.16.2 is currently the newest version available.

**Comment by g3org3** [comment]
`
# Variables

| Property           | Example value    | Description |
| ------------------ | ---------------- | ----------- |
| vm.host.num_cpus   | 4                | -           |
| vm.host.mem_size   | "512GB"          | -           |
| vm.host.num_cpus   | 4                | -           |
| vm.host.mem_size   | "512 MB"         | -           |
| vm.host.disk_size  | "10 GB"          | -           |
| vm.os.version      | 14.0             | -           |
| -                  | -                | -           |
| network.ip_version | 4                | -           |
| network.cidr       | "192.168.0.0/24" | -           |
| network.start_ip   | "192.168.0.50"   | -           |
| network.end_ip     | "192.168.0.200"  | -           |
| network.gateway_ip | "192.168.0.1"    | -           |
| -                  | -                | -           |
| cp.ip_address      | "10.100.0.105"   | -           |
| cp.port            | 30000            | -           |
| -                  | -                | -           |
| vnf.attr.address   | 10.100.0.105     | -           |
| vnf.attr.port      | 4000             | -           |



| Alias    | Tosca type                  | Description |
| -------- | --------------------------- | ----------- |
| vm       |                             | -           |
| network  |                             | -           |
| cp       |                             | -           |
| vnf      |                             | -           |
| fp       |                             | -           |

`

**Comment by abnerlee** [comment]
Seems OK in my testing

@g3org3 What's your pandoc version? Can other format, like word, be able to export successfully?

**Comment by g3org3** [comment]
6/5/18 10:23:55.200 PM Typora[36756]: use mock NSTouchBar
6/5/18 10:23:55.443 PM Typora[36756]: Layout still needs update after calling -[NSView layout].  NSView or one of its superclasses may have overridden -layout without calling super. Or, something may have dirtied layout in the middle of updating it.  Both are programming errors in Cocoa Autolayout.  The former is pretty likely to arise if some pre-Cocoa Autolayout class had a method called layout, but it should be fixed.
6/5/18 10:23:55.457 PM Typora[36756]: Started app
6/5/18 10:23:55.457 PM Typora[36756]: current version: 0.9.9.16.2
6/5/18 10:23:55.457 PM Typora[36756]: forceUpdateTheme: 0
6/5/18 10:23:55.457 PM Typora[36756]: init theme folder : 1
6/5/18 10:23:55.601 PM Typora[36756]: *** WARNING: Method convertPointToBase: in class NSView is deprecated on 10.7 and later. It should not be used in new applications.

**Comment by g3org3** [comment]
6/5/18 10:24:54.319 PM Typora[36756]: find pandoc path Now using node v4.2.0 (npm v2.14.7)
6/5/18 10:24:54.320 PM Typora[36756]: An uncaught exception was raised
6/5/18 10:24:54.320 PM Typora[36756]: launch path not accessible
6/5/18 10:24:54.339 PM Typora[36756]: (
	0   CoreFoundation                      0x00007fff99ca2452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff849bff7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff99d0949d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff85e9407b -[NSConcreteTask launchWithDictionary:] + 476
	4   Typora                              0x000000010f0ad872 -[PandocBridge runPandocWithArg:error:] + 55
	5   Typora                              0x000000010f0ad902 -[PandocBridge runPandocWithArgAndReturnString:] + 25
	6   Typora                              0x000000010f0adbc3 -[PandocBridge detectPandocPath] + 634
	7   Typora                              0x000000010f0af2d9 -[PandocBridge validatePandocInstall] + 38
	8   Typora                              0x000000010f0b5628 -[TyWindowController(Export) exportWithPandoc:] + 671
	9   libsystem_trace.dylib               0x00007fff8799507a _os_activity_initiate + 75
	10  AppKit                              0x00007fff8c187dbd -[NSApplication sendAction:to:from:] + 460
	11  AppKit                              0x00007fff8c187b57 -[NSMenuItem _corePerformAction] + 336
	12  AppKit                              0x00007fff8c1878b7 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	13  libsystem_trace.dylib               0x00007fff8799507a _os_activity_initiate + 75
	14  AppKit                              0x00007fff8c219e54 -[NSMenu performActionForItemAtIndex:] + 131
	15  AppKit                              0x00007fff8c219dc7 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	16  AppKit                              0x00007fff8c219c1f -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	17  AppKit                              0x00007fff8c0befd9 NSSLMMenuEventHandler + 708
	18  HIToolbox                           0x00007fff947197be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
	19  HIToolbox                           0x00007fff94718c48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
	20  HIToolbox                           0x00007fff9472e9e6 SendEventToEventTarget + 40
	21  HIToolbox                           0x00007fff9477899a _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	22  HIToolbox                           0x00007fff947a3d5b SendMenuCommandWithContextAndModifiers + 59
	23  HIToolbox                           0x00007fff947a3d0c SendMenuItemSelectedEvent + 188
	24  HIToolbox                           0x00007fff947a3be8 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	25  HIToolbox                           0x00007fff947a4596 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 711
	26  HIToolbox                           0x00007fff947a4230 _HandleMenuSelection2 + 460
	27  AppKit                              0x00007fff8c0aa0fa _NSHandleCarbonMenuEvent + 277
	28  AppKit                              0x00007fff8bf1f13d _DPSNextEvent + 1906
	29  AppKit                              0x00007fff8bf1e226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	30  AppKit                              0x00007fff8bf12d80 -[NSApplication run] + 682
	31  AppKit                              0x00007fff8bedc368 NSApplicationMain + 1176
	32  libdyld.dylib                       0x00007fff847045ad start + 1
)

**Comment by g3org3** [comment]
I am able to export PDF but not word or latex

**Comment by abnerlee** [comment]
I see. We should popup error dialog in this case.

Export to Latex requires Pandoc to be installed. Could you try install it referring https://support.typora.io/Install-and-Use-Pandoc/

and then restart Typora?

**Comment by abnerlee** [comment]
Added more check about pandoc installations in new release. So I will close this issue

**Comment by yc-zzh** [comment]
couldn't read navie. I can't export PDF with pandoc

**Comment by abnerlee** [comment]
> couldn't read navie. I can't export PDF with pandoc
this is #3697
