### ISSUE TITLE
The typesetting was chaotic after opening the document

### ISSUE THREAD

**Issue by Glaxy-Auditore** [typora/typora-issues#1539]
In particular, the reference format, each time the file is reopened, Format will disappear.(I uploaded a document that appeared in bug...)XD 

![tim 20180605232851](https://user-images.githubusercontent.com/17985933/41036747-a4718656-69c3-11e8-853c-79a7e6b250a4.png)
![2](https://user-images.githubusercontent.com/17985933/41036749-a8d40516-69c3-11e8-87ba-b525e454ad97.png)
![tim 20180605232911](https://user-images.githubusercontent.com/17985933/41036753-abec4ba0-69c3-11e8-8c30-daeee8140013.png)
![tim 20180605232948](https://user-images.githubusercontent.com/17985933/41036757-aeec7d48-69c3-11e8-97d4-2970af4abc0d.png)

**Comment by abnerlee** [comment]
@Glaxy-Auditore possible to attach or send us (hi@typora) the sample *.md file ?

**Comment by Glaxy-Auditore** [comment]
You can open it with other software first，And then look at 12 and 27 lines of code formatting，Finally, open it with Typora，You can see that the formatting of 12 and 27 lines is confusing in Typora，You can refer to the pictures I submitted at Issues。

Issues page address：https://github.com/typora/typora-issues/issues/1539

From:
Glaxy-Auditore

________________________________
发件人: AbnerLee <notifications@github.com>
发送时间: Wednesday, June 6, 2018 10:08:41 PM
收件人: typora/typora-issues
抄送: Ash; Mention
主题: Re: [typora/typora-issues] The typesetting was chaotic after opening the document (#1539)


@Glaxy-Auditore<https://github.com/Glaxy-Auditore> possible to attach or send us (hi@typora) the sample *.md file ?

―

**Comment by Glaxy-Auditore** [comment]
[sampleMD.zip](https://github.com/typora/typora-issues/files/2079906/sampleMD.zip)

**Comment by abnerlee** [comment]
Fixed in new release
