### ISSUE TITLE
Insert chinese style period 。 immediately after a fence `` the period will disappeared.

### ISSUE THREAD

**Issue by zhanghaoyu1993** [typora/typora-issues#154]
When input a fence in the end of a sentence and a chinese style period **immediately** after it, the period will disappear and cannot be previewed.Like this :
```markdown
`你好`。
```

When there is a blank space in the middle, everything is ok.Or I can type some word after the period and delete them all.But it seems they are not the right( or convenient) way.
`Windows` & `Typora-0.9`

**Comment by abnerlee** [comment]
1. Is "。" mark disappeared or rendered using same style like "`" ? In my test, it is the later case.
2. After you press return after `` `你好`。`` will  "。"  come back? In my test, the "。" is not gone and is stylized correctly

**Comment by abnerlee** [comment]
close until more info added

**Comment by smallx** [comment]
Oh, my god! This problem is similar to #172 . I realized it was really bug. I will give a comment in #172 later.
