### ISSUE TITLE
Indented fenced code blocks do not close properly in source mode

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#1542]
When indenting a code block (e.g. to be part of a list) like this:

~~~markdown
* Something

  ```sh
  # code here
  ```

* This line (and everything after it) is interpreted as code in source mode,
  even though the code block was properly closed and renders correctly
  in the normal edit mode.
~~~

Basically, the source code mode correctly recognizes the start of the indented block, but not the end.

**Comment by abnerlee** [comment]
Merge into https://github.com/typora/typora-issues/issues/1638 since there are same issue
