### ISSUE TITLE
Strange behavior with fenced code blocks

### ISSUE THREAD

**Issue by luisspuerto** [typora/typora-issues#1545]
I just notice a strange behavior when I'm about to type a fenced code block. 

![behaviour](http://g.recordit.co/36T30ne994.gif)

If I type too fast and I don't wait or hit blank space key to complete the three backticks ` ``` ` the codeblock mess up. Even the backticks begin to multiply like crazy in some cases and I just can stop the behavior if I switch to the source code mode and delete them from there.

**Comment by abnerlee** [comment]
@luisspuerto 

Did you use any IME to input the "`" mark?

What's your OS/Typora version?

**Comment by luisspuerto** [comment]
IME? 

macOS 10.13.5 y Typora 0.9.9.16.2

**Comment by abnerlee** [comment]
Or which Keyboard layout did you ues?

I notice there is an "_" when you input "`", how does that happen?

**Comment by luisspuerto** [comment]
Spanish layout... 

I don't know how... it happens always in typora or any other app with "`". I think it's normal.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by luisspuerto** [comment]
Thanks for the update! 👍
