### ISSUE TITLE
Code block spacing broken when Typora is opened and not wide enough

### ISSUE THREAD

**Issue by ndbeals** [typora/typora-issues#1546]
Just noticed this bug, when you open a markdown file in Typora and Typora isn't wide enough. It appears that when you re-size Typora to be wide enough, it doesn't re-calculate the layout of code blocks, you have to close and re-open the file to update the layout.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/850796/41163674-52d9930c-6b07-11e8-8c62-fdd2a91be52d.png)

And here's what it should look like. I can get it to render correctly by resizing the Typora window, then opening another file through the "Files" menu on the left, then re-opening the original. Here's what it should look like:
![image](https://user-images.githubusercontent.com/850796/41163916-f44dbd9e-6b07-11e8-9ada-48fdb2f3888b.png)

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by ndbeals** [comment]
Typora Version: 0.9.53

OS: Windows 7 Enterprise SP1

**Comment by abnerlee** [comment]
Fixed in new release
