### ISSUE TITLE
flowchart.js parallel object appears to not work

### ISSUE THREAD

**Issue by maccident** [typora/typora-issues#1547]
Typora canot render the example on flowchart.js until the 'parallel' object is removed.

Using flowchart.js' example renders a flowchart stacked upon itself and unreadable.

to recreate in Typora:

```flow
[then paste]

st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...
para=>parallel: parallel tasks

st->op1->cond
cond(yes)->io->e
cond(no)->para
para(path1, bottom)->sub1(right)->op1
para(path2, top)->op1

**Comment by ZenRay** [comment]
It can render in the version 0.9.9.16.2 on Mac

**Comment by orinbai** [comment]
I have the same problem on ubuntu 16.04 LTS

**Comment by horngyih** [comment]
Also doesn't work on Windows version 0.9.58

**Comment by jonkru** [comment]
I have the same issue. 'parallel' object doesn't work on Windows version 0.9.58

**Comment by discjockeydom** [comment]
This is also broken on Version 0.9.9.18.1 (1088) for OSX.

**Comment by SevenGuns** [comment]
me too

**Comment by N-Upchurch** [comment]
I'm having this issue on Windows 10. Syntax highlighting does not work on parallel object either.

**Comment by nightan42643** [comment]
I have the same issue on Windows version 0.9.65. T.T

**Comment by nightan42643** [comment]
![image](https://user-images.githubusercontent.com/38649296/53217144-e87a5580-3691-11e9-99ea-da428b4ab235.png)

**Comment by abnerlee** [comment]
fixed in new release

**Comment by craneLi** [comment]
not fixed yet in the newest version
