### ISSUE TITLE
Links in superscript

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1549]
I'd be great to have links working in superscript, i.e.
`Some text^(source)[URL]^.`

Right now, the superscript breaks the markdown hyperlink.

**Comment by abnerlee** [comment]
`^^` is not standard Markdown syntax, and I checked other Markdown editors that supports `^^`, it seems Markdown inside is also not parse. 

I feel OK to let `^^` only supports plain text.

AN alternative option is to use `<sup>[alt](url)</sup>` instead, which is supported in latest release
