### ISSUE TITLE
Using label in equation will get the error "Label '***' multiply defined"

### ISSUE THREAD

**Issue by pdcxs** [typora/typora-issues#155]
I insert an equation as following:
$$
\label{fact}n!=\prod_{i=1}^n i \tag{1}
$$

It displayed correctly at first time. But when I modified it again, it threw an error:
**Label 'fact' multiply defined**

Is there any way to fix it?
Thanks a lot.

**Comment by pdcxs** [comment]
PS: I use 0.9.5 (beta) windows version.

**Comment by abnerlee** [comment]
#48

**Comment by abnerlee** [comment]
`\label` works fine in blocked math in latest version.

**Comment by wangkaibule** [comment]
It seems broken again in version 0.9.29, please check!

My test file
```markdown
\begin{equation}\label{eq:planeeq} \tag{1} a_nx_n+a_{n-1}x_{n-1}+ \dots + a_1x_1+a_0=0 \end{equation}
```

**Comment by abnerlee** [comment]
Should ready be fixed in newest version
