### ISSUE TITLE
"Copy image to" is not working properly with images with blank spaces in the name

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#1550]
Hi! 

Thanks for provide such a wonderful app, first of all. 

I've been testing the function "Copy image to", which I think is a wonderful idea and it's not working properly when the origin, or target, name of the image has a blank space in the name. I think the problem is the app adds `%20` instead of the space and either the app or the system doesn't recognize as the same name as the original picture. 

![screen shot 2018-06-09 at 16 48 00](https://user-images.githubusercontent.com/22882880/41192354-05e4d5a8-6c05-11e8-8d4e-0128e91498db.png)
![screen shot 2018-06-09 at 16 47 39](https://user-images.githubusercontent.com/22882880/41192355-0b51b9b6-6c05-11e8-8c21-24b00040fa9b.png)
![screen shot 2018-06-09 at 16 47 45](https://user-images.githubusercontent.com/22882880/41192356-0d481ad0-6c05-11e8-8221-eae23484b16f.png)

**Comment by MaluNoPeleke** [comment]
When I tried it on MacOS Mojave it copied images with a blank to the specified folder with the problem of converting blank to %20 in the file name on the disk and that is the reason why they are not being displayed:

Status quo: "Screen Shot.png" copied locally by Typora as "Screen%20Shot.png" and referenced as ![img](assets/Screen%20Shot.png) -> not found, you have to remove manually the "%20" from file name.
Expected: "Screen Shot.png" copied locally by Typora as "Screen Shot.png" and referenced as ![img](assets/Screen%20Shot.png) -> no manual work necessary, should work out of the box.

**Comment by zsh-89** [comment]
here is another case:  If I have **a note with space chars in the name**, for example `my note.md`, then I insert a picture by pressing `ctrl+v`, the inserted image is like `![image-20190211004655126](my note.assets/image-20190211004655126.png)`. This can only be correctly displayed in Typora, not in other markdown render engine (for example, Github). The correct one should be `![image-20190211004655126](my%20note.assets/image-20190211004655126.png)`.

**Comment by abnerlee** [comment]
relates #2198 #1520

**Comment by abnerlee** [comment]
The bug should be fixed in new release, please reopen if it still happen
