### ISSUE TITLE
More kramdown support? 

### ISSUE THREAD

**Issue by luisspuerto** [typora/typora-issues#1552]
Hey! 

Do you plan to add more kramdown support to typora? it would be great to have some basic utility classes could be use to change the text. 

Thanks a lot for the wonderful app!

**Comment by abnerlee** [comment]
We do not have plans to fully support kramdown.

So which feature/spec will be supported or not is decided case-by-case.

**Comment by luisspuerto** [comment]
Thanks a lot for the answer! it would be great if typora had the ability to become a fully Jekyll editor. 😃

**Comment by gsiolas** [comment]
Do you plan to add at least some kramdown features? At least add an option for _target="blank" on links. Right now it [does not look very nice](https://imgur.com/JDo9ezz.png), it's a pitty for such a great-looking editor.

Thanks, we love Typora!

**Comment by wujastyk** [comment]
I too am starting to use Typora for Jekyll editing and I'd like kramdown too.  Today, for example, I'm using 

descriptive
:    lists of items.

Many thanks,
Dominik
