### ISSUE TITLE
Site certificate expired: theme.typora.io

### ISSUE THREAD

**Issue by AgyarJanos** [typora/typora-issues#1553]
Happens, but I figured you should know. 

I saw you were using nginx and LetsEncrypt. If it helps, I avoid this issue on my servers by adding the following line to crontab. You could probably schedule this too.

0 1 * * 1 /usr/sbin/service nginx stop && letsencrypt renew && /usr/sbin/service nginx start

**Comment by abnerlee** [comment]
Fixed
