### ISSUE TITLE
markdown syntax tags not editable on "heading" element after it's been styled

### ISSUE THREAD

**Issue by ZaLiTHkA** [typora/typora-issues#1554]
first off, I must say that I love what you've got so far.. Typora is absolutely beautiful, I didn't think it was possible to enjoy markdown *even more* than I already did. 👍 however, my favourite point in MD is the ability to do everything with the keyboard; and in that sense, Typora doesn't quite "check every box" so to speak.

in general, special formatting tags can be edited when the cursor is in the formatted string, but this is not the case with all formatting, specifically on "headings". I understand that heading levels can be changed in the context menu (when in doubt, right click), but the fact that the *markdown tag* itself can't be changed *from the keyboard* after styling is more than a little annoying.

**Comment by ZaLiTHkA** [comment]
I was going to add this to the main description, but it's only related to the issue at hand, not part of it.. so on a related note:

at first I thought this same issue applied to things such as lists and quotes, until I moved my cursor to the start of a line and hit "backspace". but because the actual "markdown" character is no longer visible at this point, that part was very unclear.

would it be possible to keep the actual text content of the editor window as "raw markdown", simply applying the relevant styling points to the text in question? naturally this just wouldn't work some elements (e.g.: links and images), but for things like emphasis, bold, headings, lists, etc. it would be nice to see `## My Heading` still with the leading `##` tag, but the *whole line* styled as a level 2 heading. similarly, still seeing the `*` symbols around an emphasised word would be nice.

...or would it be better create a new issue for this styling-specific stuff?

**Comment by abnerlee** [comment]
We have the option "Display source for simple blocks" in preference panel. Please enable it.

**Comment by ZaLiTHkA** [comment]
wow. awesome attitude.

thanks for clarifying that, I'll find something else to use then.
