### ISSUE TITLE
Can not fit the touchbar

### ISSUE THREAD

**Issue by yuanjingsong** [typora/typora-issues#1555]
device: MacBook pro 13' with touchbar
os: MacOS 10.13.4
version: 0.9.9.10.3
When i use the touchbar to select a level for a paragraph. The candidate box doesn't fit the touch bar height having a little offset above the middle.

**Comment by abnerlee** [comment]
Please upgrade Typora

**Comment by yuanjingsong** [comment]
thanks! bro
