### ISSUE TITLE
Expand/collapse all items in outline?

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1556]
Is there a way to collapse / expand all items in the outline?
Sometimes the outline seems to collapse itself, so I often have to expand a lot of the headers.

**Implementation proposal:**
pressing left/right arrow to expand/collapse outline items after selection.
I.e. expanding/collapsing all could be achieved simply by pressing ⌘A, → and ⌘A, ← in the outline.

Right now single clicking on an outline item directly navigates to that header, but only if you click on the text itself, not if you click in the same row "box" but outside the header text. This I see two options:

1. Require double click / selection twice in outline to navigate.
2. Perhaps better: Keep current navigation on single click, but arrow election without navigation of a header row in the outline is selecting either with the arrow keys or the row box is clicked but outside the text itself.

**Comment by abnerlee** [comment]
We do not want to add extra buttons for these feature. In your case, seems turning off "collapsible outline panel" good be a good option
