### ISSUE TITLE
Error exporting pdf style

### ISSUE THREAD

**Issue by Chasers9527** [typora/typora-issues#1559]
when i use themes : 'Solarized ' or 'Solarized Dark ' , and  export html | pdf 

![image](https://user-images.githubusercontent.com/16145443/41339977-d14b5c1e-6f28-11e8-88ab-0a316d25185b.png)
![image](https://user-images.githubusercontent.com/16145443/41339999-e4239e32-6f28-11e8-92bb-87b23d8b6b2e.png)

html image can't load
![image](https://user-images.githubusercontent.com/16145443/41340059-09640a24-6f29-11e8-82b4-a4e4c0296ad3.png)

**Comment by abnerlee** [comment]
How about built-in themes, like `night` or `newsprint` ?

About HTML image, if possible, could you send us the sample *.md file that image cannot be exported?

**Comment by Chasers9527** [comment]
@abnerlee 
OS :
![image](https://user-images.githubusercontent.com/16145443/41341145-98053616-6f2b-11e8-9eb9-6cb06a9e80f2.png)

`night` is ok.  `Solarized` or `Solarized Dark` is error


image is local image .. html and images is not  one directory。。。it isn't error
