### ISSUE TITLE
Strange cursor behaviour with headings

### ISSUE THREAD

**Issue by MarkWithall** [typora/typora-issues#1560]
Given the following:

```markdown
#### A Rather Long Heading Name
Some content
```

Placing the cursor at the beginning of the second line ("Some content"), then pressing the up arrow moves the cursor to the right 5 characters (to after the four # characters and the space). Moving down remains indented by 5 characters. Moving up again indents a further 4 characters. Down remains indented by 9. Up indents by another 3 characters. And so on.

To me, it feels like the initial up is fine (putting the cursor after the 4 # characters and space) but down should put the cursor back to the beginning of the line again and up should put it back after the #.

_Version: 0.9.53(beta) on Windows 10 Pro (all patches applied as of the time of posting)._

**Comment by abnerlee** [comment]
Merge into https://github.com/typora/typora-issues/issues/1164
