### ISSUE TITLE
Math align

### ISSUE THREAD

**Issue by Zhaolooloo** [typora/typora-issues#1564]
When I use $$ $$ to build equation block, the equation always show in the middle of the lines and with equation index.
How can i move it to the left of the lines and without equiation index?
$$
\begin{equation}
\begin{cases}
f(x)=\frac{1}{12} \cdot x \quad g(x) = \frac{1}{24} \cdot x, & x<12 \\
f(x)=1 \quad g(x) = \frac{1}{8} \cdot x - 1, & 12 \le x < 16 \\
f(x)=1 \quad g(x) = 1, & x \ge 16
\end{cases}
\end{equation}
$$

**Comment by Zhaolooloo** [comment]
I can achive this by use $, but it is hard to read...
![image](https://user-images.githubusercontent.com/30585891/41528129-c5e974e0-731b-11e8-8bf4-304acbf3358e.png)

**Comment by Zhaolooloo** [comment]
code is like this:
![image](https://user-images.githubusercontent.com/30585891/41528211-0333c210-731c-11e8-94df-3358e6fa510f.png)

**Comment by abnerlee** [comment]
Use "$" for inline math.

Block math ($$ + return key) will be aligned center by default. To change this behavior, CSS knowledge is required. You may follow https://support.typora.io/Add-Custom-CSS/ to apply custom CSS.

**Comment by eduardohorta** [comment]
On macOS Catalina with Typora Version 0.9.9.35 (4693):
1. download **xalign.js** from [https://github.com/AmerMathSoc/mathjax-xalign](https://github.com/AmerMathSoc/mathjax-xalign)
2. copy the above file to folder **/Applications/Typora.app/Contents/Resources/TypeMark/lib/MathJax/**
3. open the file **index.html** from folder **/Applications/Typora.app/Contents/Resources/TypeMark** with a text editor
4. in the above file search for
`extensions: ["tex2jax.js", "toMathML.js"],`
  and substitute it by
`extensions: ["tex2jax.js", "toMathML.js", "xalign.js"],`
5. Here is a minimal working example that will have equations left-aligned:
`$$
\begin{xxalignat}1
& x=x\\
& y=y
\end{xxalignat}
$$`

**Comment by shinokada** [comment]
@eduardohorta 
It is not working.
![image](https://user-images.githubusercontent.com/147320/95164910-e83ab980-07e5-11eb-989e-1ff1891ba68c.png)

**Comment by eduardohorta** [comment]
@shinokada I ran into the same issue a while after implementing the solution suggested above. I think it stopped working after I updated to Typora Version 0.9.9.35.2 (4715). Here's a less elegant way to achieve left alignment:

```
$$
\begin{array}{rcl}
f(x) & = &x &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
\end{array}
$$
```

**Comment by eduardohorta** [comment]
@shinokada I ran into the same issue a while after implementing the solution suggested above. I think it stopped working after I updated to Typora Version 0.9.9.35.2 (4715). Here's a less elegant way to achieve left alignment:

```
$$
\begin{array}{rcl}
f(x) & = &x &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
\end{array}
$$
```

**Comment by shinokada** [comment]
I used a single `$` to align left.

```
$X \sim N(2.13+12.4 \cdot 0.4^2 +0.3^2) \implies X \sim N(38, 0.73)\\ 
P(X \le 40)\approx 0.997$
```

![image](https://user-images.githubusercontent.com/147320/95187286-f1d41980-0805-11eb-8550-b376d7586e4c.png)

**Comment by JXproject** [comment]
In 'index.html', you may add `displayAlign: "left"` to make everything align to the left by default.
```html
MathJax.Hub.Config({
    ...
    displayAlign: "left"
    ...
});
```

**Comment by VKBobyr** [comment]
> It seems the 'xalign.js' no longer works for now.
> 
> I found a work around for make everything align left by default:
> 
> * In 'index.html', you may add `displayAlign: "left"`
> 
> ```
> MathJax.Hub.Config({
>     ...
>     displayAlign: "left",
>     ...
> });
> ```

Could somebody please specify where `index.html` is located
