### ISSUE TITLE
Support for `siunitx` LaTeX package / MathJax extension

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1569]
I'd really like to have support for this package in the live preview: https://ctan.org/tex-archive/macros/latex/contrib/siunitx?lang=de

It's currently one of the [few maintained](https://github.com/mathjax/MathJax-third-party-extensions) MathJax extensions: https://github.com/burnpanck/MathJax-siunitx

I realized from #1417 that it's not currently possible to make MathJax extensions for Typora yourself, hence this issue.

**Comment by edelmanjm** [comment]
Okay, I read through some of the linked issues, but I'm still confused. Is the hold up simply on updating MathJax? Are we waiting for a new plugin system? Can a temporary workaround be reached by building typora for source?

**Comment by GandalfSaxe** [comment]
I'm not too sure either. I think Typora could benefit from shipping with an extended version of MathJax including the `siunitx`, `mhchem` and `physics` packages from the [list](https://github.com/mathjax/MathJax-third-party-extensions) above. Would provide a lot of extra power for science / engineer users.

**Comment by abnerlee** [comment]
https://github.com/mathjax/MathJax/issues/447

**Comment by abnerlee** [comment]
Those [few maintained](https://github.com/mathjax/MathJax-third-party-extensions) MathJax extensions looks very old, we do not have plans to support them.

Consider  #100 as an equivalent

**Comment by dj-zhou** [comment]
#100 is equivalent but there is no solution.
