### ISSUE TITLE
Using smart punctuation with "convert on input" results in two strange behaviors

### ISSUE THREAD

**Issue by chuckmasterson** [typora/typora-issues#1572]
I upgraded my Typora recently and was delighted to find there's now support for curly quotes as I type! But in writing I've discovered at least two glitches with it:

- When I start a quote by typing <kbd>"</kbd>, I correctly get `“`. But then if I change my mind and backspace it, do a little editing, and start the quote again, I get `”`. The algorithm seems unwilling to give me `“` twice in a row. “You should be *closing* a quote now,” it seems to say, “I already *gave* you an opening quote. Finish that one first.”
- Inside an unclosed asterisk (or underscore, or double-tilde, or probably more), typing <kbd>'</kbd> inside a contraction always gets me `‘`. For example: <kbd>The *U.S.S. Enterprise's . . .</kbd> → `*The U.S.S. Enterprise‘s . . .`. I have to backspace the opening single quote and type <kbd>'</kbd> again to get `’`, which it then willingly gives me, perhaps because it thinks I’m closing a single-quoted quote that I began when I typed <kbd>'</kbd> the first time. But strangely, if I *don’t* backspace the `‘`, I keep getting more `‘`s: `*The ship‘s captain‘s log‘s dating system is dubious . . .` If I let AutoPair put a closing asterisk after my cursor none of this happens, but I find that asterisk distracting, so I turned AutoPair off.

**Comment by abnerlee** [comment]
@chuckmasterson on macOS or Windows?

**Comment by abnerlee** [comment]
Fixed in new release
