### ISSUE TITLE
Image Previews : Path relative to Selected Folder 

### ISSUE THREAD

**Issue by peeweek** [typora/typora-issues#1573]
Currently, image paths works either relatively to the folder where the md file is located, or absolute.

Github wiki enables shortening URLs for links and images so instead of having 

```![Image](https://raw.githubusercontent.com/wiki/user/repo/Path/To/image.png)```

we can use 

```![Image](Path/To/image.png)```

Problem is, we cannot define the root folder for accessing these images for preview, instead we see broken links.

Would it be possible, if the Open Folder has been called, to add a root search path for these images so the search happens also from this custom root folder?

**Comment by abnerlee** [comment]
This can be set from `Edit` -> `Image Tools` -> `Use Image Root Path` from menu bar

**Comment by eryajf** [comment]
Hello, I am trying to ask this question. I didn't expect to have an answer, but I did not find a configuration that can define the root of the image in my current version. The version I am using now is 0.9.72 under Windows.

**Comment by johanhelsing** [comment]
Found it under `Format` -> `Image` -> `Use Image Root Path...`

That adds the config to the front matter of the current file...

```markdown
---
typora-root-url: ..
---
```

Just wondering: is it possible to configure it on a per workspace/folder level so I don't have to add it to every individual file?
