### ISSUE TITLE
Pseudocode with inline-math

### ISSUE THREAD

**Issue by sbuschjaeger** [typora/typora-issues#1575]
Hi!

I would like to write pseudocode in typora including some math symbols. In the best-case scenario I would like to use a code-fence (e.g. with pseudo-code syntax highlighting as already supported) and also render inline math in the code-fence. However, this does not seem to be supported at the moment? 

Are there any workarounds / ideas how to get a (pseudo) code environment + inline math rendering in typora?

Best

**Comment by Starxyz** [comment]
I met the same problem as yours.

**Comment by abnerlee** [comment]
Code block only renders plain text with proper syntax highlight, so math or image or other format will not be supported inside code block.

A workaround would be write pseudocode without code block, like using a numbered list.
