### ISSUE TITLE
Don't break live preview of displaymath ($$...$$) when adding {#labels} 

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1576]
The live preview of displaymath requires either:
 ```latex
$$...$$
```
or
```latex
$$
...
$$
```

But it breaks if there is anything else on the line such as:
```latex
$$...$$ {#somelabel}
```
or
```latex
$$ {#somelabel}
...
$$
```

which is a syntax that translates into LaTeX labels with pandoc filter [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref).

Could you have the equation preview not break when this label is added?

Actually `pandoc-crossref` figure labels already play nice with images, in the sense that in:
```markdown
![](image.png) {#somelabel}
, the `{#somelabel}` label don't break the live preview of the image.

**Comment by gandalfsaxe** [comment]
Ok so this syntax actually worked in the sense that it didn't break the live preview:

```markdown
$$ {#somelabel}
...
$$
```

Of course it would be nice with some consistency, e.g. that both equation and figure labels of the form `{#...}` are all either hidden or shown (as mentioned, currently figure labels are hidden from live preview, but equation labels are shown), but at least there is a workaround for now. I'd suggest, if not adding an option to show/hide them, then to show them all.

**Comment by gandalfsaxe** [comment]
No wait, it's actually as bad as I feared first. While the syntax above doesn't break the current equation preview, it does break the next:

Source without labels:
```markdown
Test 1:

$$
e=mc^2
$$

Test 2:
$$
e=mc^4
$$

Bla bla...
```

Typora live preview:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/12127864/41820266-4d24ef18-77cf-11e8-95a0-a406e1945c87.png">


Source with labels:
```markdown
Test 1:

$$
e=mc^2
$$ {#eq:test1}

Test 2:
$$
e=mc^4
$$ {#eq:test2}

Bla bla...
```

Typora live preview:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/12127864/41820273-729b2604-77cf-11e8-8744-93798843b4a9.png">


So again, if you could simply not break the live preview from having a pattern of `{...}` on the same line as opening or closing $$ if a math block, that would be so great.

**Comment by gandalfsaxe** [comment]
Luckily we now have a [solution](https://github.com/lierdakil/pandoc-crossref/issues/183) from `pandoc-crossref` since he now made the math labels work also after a line break, so now the following works:

```markdown
Works:
$$a+b=c$$
{#eq:name1}

Also works:
$$
a+b=c
$$
{#eq:name2}
```

However it would still be nice if Typora ignored the `{...}` in this notation:

```markdown
$$
a+b=c
$$ {#eq:name}
```
Then the user could choose between hiding the labels by putting them on the same line as `$$` or showing them by putting them on the next line.

**Comment by abnerlee** [comment]
Supported in new release

**Comment by GandalfSaxe** [comment]
What exactly is supported?

If I do:

```latex
$$
a+b=c
$$
```

it works, but this does not:

```latex
$$
a+b=c
$$ {#eq:name}
```

**Comment by GandalfSaxe** [comment]
Ah sorry it did work, I wasn't on the latest update 👍 

Speaking of which, what could be the reason for the "Check for Updates" to be greyed out?
<img width="222" alt="image" src="https://user-images.githubusercontent.com/12127864/44355274-76d80980-a4ac-11e8-966a-160ff2bc0bd0.png">
Now I just updated manually, and it works.
