### ISSUE TITLE
supporting spoiler tags

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1577]
Is there a plugin that supports markdown with a spoiler tag?

When I text:
```
<details>
  <summary>Click to expand</summary>
  Spoiler!
</details>
or 
[spoiler] Spoiler [/spoiler]
```
Nothing is happening. But if I export the my file to **.html**, then the spoiler will work in the saved file. How? It's unfair. 😌

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/399
