### ISSUE TITLE
Sort by name does not appear to sort by name

### ISSUE THREAD

**Issue by ryankurte** [typora/typora-issues#1578]
When "sort by name" is selected (highlighted blue) files in the file-list reshuffle but remain unsorted.
Tested on Windows10 and OSX with file names in the form of `YYYY-mm-dd-name.md`

**Comment by abnerlee** [comment]
Could you attach a screenshot, or send it to us (hi@typora) in private?

Could you confirm "Group by Folder" is not selected?

**Comment by ryankurte** [comment]
Have sent a screenshot via email, and group by folder is not selected (plus all documents are in the same folder).

**Comment by abnerlee** [comment]
Should be fixed in new release
