### ISSUE TITLE
Missing Typewriter Mode keyboard shortcut in newest versions

### ISSUE THREAD

**Issue by abdallahYashir** [typora/typora-issues#1579]
In previous versions, by selecting _CTRL + SHIFT + T_, Typora toggled the **Typewriter Mode**. In the **view** menu, it also had the shortcut displayed.

However, in latest versions, the shortcut has been disabled.

I find this Mode useful especially when writing long paragraphs. The shortcut was productive and convenient as I could shift from Typewriter mode to normal mode with the keyboard alone. Now I have to shift the option using the mouse every time.

![typora](https://user-images.githubusercontent.com/1567363/41818156-bb7002fc-77b9-11e8-8168-ed678ce06f27.png)

I am grateful if the keyboard shortcut could be added back. Thank you.

**Comment by abnerlee** [comment]
Please refer https://support.typora.io/Custom-Key-Binding/
before we assign it a new default shortcut key
