### ISSUE TITLE
Have `\begin{align}` trigger display math live preview, just like $$ does

### ISSUE THREAD

**Issue by gandalfsaxe** [typora/typora-issues#1582]
Currently, typora supports align by doing:

```markdown
$$
\begin{align}
...
\end{align}
$$
```

However this will not render when not exporting using File -> Export, but instead converting to `.tex` or `.pdf` using pandoc.

Therefore I suggest that having:

```markdown
\begin{align}
...
\end{align}
```

by itself should *also* trigger a live preview, just like $$ does.

**Comment by abnerlee** [comment]
included by https://github.com/typora/typora-issues/issues/63
