### ISSUE TITLE
Typora doesn't support Python ellipsis syntax

### ISSUE THREAD

**Issue by houluy** [typora/typora-issues#1583]
I recently found that typora doesn't support Python ellipsis syntax. When encountered, the following lines will not auto indented, and no syntax highlighted either.

```python
def func(): ... # valid syntax in Python
    class A: ... # this line become colorless and unindented
```
My typora version: version 0.9.53 (beta) on Windows 10 with Whitey theme. 
![_20180625173951](https://user-images.githubusercontent.com/11565649/41842962-cdc4ba34-789e-11e8-8cc6-61658599d211.png)

**Comment by Soaku** [comment]
Are you sure?

```
>>> def func(): ...
...     class A: ...
    
  File "<input>", line 2
    class A: ...
    ^
IndentationError: unexpected indent
```
Here, you are filling both the inline and block part of the `def`, which is not a valid syntax. Maybe you meant
```
def func(): ...
class A: ...
```
without the indent?

**Comment by houluy** [comment]
Sorry I didn't explain clear.  
The **valid syntax in Python** is as you mentioned
![ellipsis](https://user-images.githubusercontent.com/11565649/41906231-ee3ddb02-796f-11e8-98fc-3c6de27fb036.png)
(The above figure comes from Sublime Text.)
However, **this syntax cannot be recognized in Typora,** 
![typora](https://user-images.githubusercontent.com/11565649/41906366-44be3d8c-7970-11e8-800d-f473d1cdb57b.png)
(This one comes from Typora.)
The `class` keyword is not highlighted, because I think _typora doesn't treat the ellipsis as valid Python syntax yet._
I'm not sure if I've made myself clear this time.

**Comment by abnerlee** [comment]
It requires upstream support from Codemirror, you could try their syntax highlighting here -> https://codemirror.net/mode/python/

So please open an issue on CodeMirror project, and Typora will follow after CodeMirror supports this.
