### ISSUE TITLE
add supporting unicode symbols by number or mnemocode (HTML entity)

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1586]
It would be great to add support for entering Unicode characters by mnemonic or number code, e.g:
`&#0153` => `™`
`&#0169` => `©`
`&#0174` => `®`
etc.

**Comment by AlexPasternak** [comment]
If you're on macOS, this seems like one of the hardest possible ways to do this. Opt-2 for ™ or Opr-R for ® are much easier. 

https://fsymbols.com/computer/trademark/

**Comment by Eskander88** [comment]
sorry, I didn't just mean only these symbols. I'm talking about Unicode characters in General.

**Comment by abnerlee** [comment]
`&#0153;` seems not work in Gtihub: &#0153;

But `&#0153;` is valid in commonMark, I feel OK to support this.

**Comment by Piping** [comment]
how about this `<shortcut><number>` to produce the characters? 
The number can be \x for hex, digits for base10

**Comment by abnerlee** [comment]
Fixed in new release
