### ISSUE TITLE
"Export to" option only works for PDF and HTML on Mac OSX

### ISSUE THREAD

**Issue by anandgraves** [typora/typora-issues#159]
This doesn't work for a new unsaved file or an existing file.
The following options don't work:
* Word (.docx)
* OpenOffice
* RTF
* Epub
* LaTeX
* Media Wiki

This is on Mac OSX 10.11.4.

**Comment by abnerlee** [comment]
The recent known bug for export to other type formats is using pandoc older than 1.16 or use inline math.

So @anandgraves try update Pandoc (>= 1.16) first. If you use pandoc later than 1.16 and you do not use inline math, but the article still cannot be exported, then it is a new bug, could you send a sample "*.md" file to <hi@typora.io> in this case ?

**Comment by anandgraves** [comment]
Hi @abnerlee 
I previously didn't have Pandoc installed.
Now I've installed the latest version:
```
$ pandoc --version
pandoc 1.17.0.2
```

Unfortunately, the export options (other than pdf and html) still don't work.

**Comment by abnerlee** [comment]
@anandgraves would you send a sample *.md file to us(<hi@typora.io>) ?

**Comment by anandgraves** [comment]
@abnerlee I will send a sample `.md` file to you, but in my case it doesn't matter which `.md` file I use.

**Comment by abnerlee** [comment]
@anandgraves I can export to docx from your md file, so, yes, it is not related with which `.md` file you use.

So if there any error message when you do exporting?

**Comment by anandgraves** [comment]
@abnerlee No, I don't get any visible error message when exporting. The only thing visually is that `File`, next to Typora at the top menu, is blue for a second when exporting.

**Comment by abnerlee** [comment]
OK, then could you check help->debug mode from menu, then click "Inspect Element" from context menu, do exporting and paste or send the log from the console tab of the devtools.

Also, could you open Console.app and search "typora" and send filtered log to us?

**Comment by anandgraves** [comment]
Ok, I've send the log info.
Unfortunately I don't receive an error message in the console tab.
I sent an email with the console info when a file is being opened.

Where can I find the Console.app?
Is this in the Package Contents (context menu > Show Package Contents)? I checked there and couldn't find it.

**Comment by abnerlee** [comment]
@anandgraves You could search "Console" from spotlight or luanchpad. It's a part of OS X system.

**Comment by abnerlee** [comment]
Should be fixed in new version
