### ISSUE TITLE
add supporting a clickable reference to local file (protocol file:///)

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1592]
Typora support link for protocol `http://` and open reference. 
But reference like as `file:///C:\web\index.html` is not opened.

**Comment by vassudanagunta** [comment]
It's not needed. You can simply us `[anchor text](C:\web\index.html)`.

Even better, you can use relative links such as `[anchor text](subfolder/index.md)`, consistent with how GitHub and other Markdown renderers support links to resources or other Markdown files.

**Comment by Eskander88** [comment]
and I found other trouble with this, typed: [link to local files but can not open folder ](https://github.com/typora/typora-issues/issues/1596)

**Comment by abnerlee** [comment]
Fixed in new release
