### ISSUE TITLE
Allow for pandoc syntax fenced code attributes without breaking syntax highlighting

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1593]
When converting with pandoc, it's possible to give the code fence some attributes. For example it's possible to add line numbers starting from an arbitrary number using the syntax:

````
``` {.python .numberLines startFrom="100"}
# first code line
# second code line
# third code line
```
````

However this breaks the syntax highlighting colors of the code in Typora.

## short term fix
As a start, I'd be happy just to have Typora ignore all the options in the braces, but at least keep the syntax highlighting intact. In other words instead of only allowing code fences to begin with ```` ```{python} ````, then also allow ```` ```{.python OPTIONS} ```` while ignoring the options and just extracting `.python` as the code language.

## long term feature request
It' be great if Typora could conform to pandocs protocol and actually show line numbers starting from 100 in the live preview of the code above.

**Comment by abnerlee** [comment]
merge to https://github.com/typora/typora-issues/issues/918

**Comment by abnerlee** [comment]
Fixed in new release
