### ISSUE TITLE
VLOOK - an enhanced plug-in for HTML files exported by Typora

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#1594]
HOME: [https://github.com/MadMaxChow/VLOOK](https://github.com/MadMaxChow/VLOOK)

VLOOK™ is an enhanced plug-in for HTML files exported by Typora, including themes and toolkits:

Theme style: Based on CSS production, provide enhanced and rich format details for the Markdown file and exported HTML file edited by Typora to support more complex document layout and visual presentation requirements;
Toolbox: Based on JQuery production, provide convenient chapters, picture navigation, and in-page and external link check and optimization for exported HTML.

VLOOK™是针对Typora导出的HTML文件的增强插件，包括主题样式和工具箱两个部分：

主题样式：基于CSS制作，为Typora编辑的Markdown文件和导出的HTML文件提供强化、丰富的格式细节，以支持更为复杂的文档排版和视觉呈现要求；
工具箱：基于JQuery制作，为导出的HTML提供便捷的章节、图片导航，以及页内、外部链接检查与优化等特性。

**Comment by abnerlee** [comment]
now added in our document: https://support.typora.io/Export/#example-export-using-vlook
