### ISSUE TITLE
Right Clicking on Text Crashes app Every Time

### ISSUE THREAD

**Issue by OstlerDev** [typora/typora-issues#1595]
Hello! First off, thank you for the great app you have been creating.

I have however been running into an issue where if I right click on any text, it will hang the application and crash the macOS `Dock`, requiring the use of the `killall Dock` command to regain control of the Computer to allow you to Force Quit the app.

OSX Version: 10.13.4
Typora Version: 0.9.9.16.2 (Latest)

Steps to Reproduce the issue:
1. Open new Document
2. Write any bit of text
3. Right click on that text
4. Entire editor hangs, Dock and Top Taskbar are also unresponsive

Hope this is able to get resolved quickly!
Sky Young

**Comment by abnerlee** [comment]
@OstlerDev I'm not able to reproduce this.

Could you provide us a sample text that will crash Typora on right click?
Will select text and right click crash on other apps, like Safari?
What's your system language?

**Comment by OstlerDev** [comment]
I was unable to get it reproduced as well, it must be fixed.
