### ISSUE TITLE
link to local files but can not open folder

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1596]
I use reference to local files into ***.md**-file. Hyperlink can open files on local PC by click.
```markdown
[It link don't work D:\www\localhost\ ](D:\www\localhost\)
```
But it doesn't work for links to folder.
```markdown
[It link work D:\www\localhost\index.php ](D:\www\localhost\index.php)
```

Alert massage:
![default](https://user-images.githubusercontent.com/24587938/42182428-db087944-7e46-11e8-9dd2-b94a764a3301.png)

```
tried: Windows 10 x64, Typora 0.9.53 (beta)
```

**Comment by vassudanagunta** [comment]
Typora isn't an IDE. The author has stated that many times. It only handles links that are natural for text documents and web pages. For example, many if not most web browsers usually don't links to local folders.

**Comment by Eskander88** [comment]
So, what? Do you think this not good? This is just one idea for greater compatibility with other software.

**Comment by abnerlee** [comment]
Fixed in new release
