### ISSUE TITLE
How to use system theme (GTK+) for Typora on Linux

### ISSUE THREAD

**Issue by coiby** [typora/typora-issues#1598]
Hi,

Before upgrading, typora used system theme (GTK+, use_system=true),
![screenshot from 2018-07-03 08 33 06](https://user-images.githubusercontent.com/1511656/42194581-379df638-7ea7-11e8-85ac-f911fd9ca363.png)

However, after upgrading from 0.9.38 to 0.9.53, it uses the classic theme (use_theme=false),
![screenshot from 2018-07-03 09 54 45](https://user-images.githubusercontent.com/1511656/42194560-2438cfaa-7ea7-11e8-9c63-e83766627e55.png)

Is there a way to tell typora to use system theme which is supported by Chrome?
![screenshot from 2018-07-03 09 57 21](https://user-images.githubusercontent.com/1511656/42194655-8ec23bf4-7ea7-11e8-8ff2-0f8691148672.png)

Thank you!

**Comment by abnerlee** [comment]
may relates https://github.com/electron/electron/issues/765
