### ISSUE TITLE
html entities in inline code blocks are shown as symbols

### ISSUE THREAD

**Issue by somaGFX** [typora/typora-issues#160]
so, if you want to have the "code" of an html entity for example `&phone;` you get also the symbol of the phone &phone;  &nbsp;and not the text.

Maybe it should be fixed that the html entities never get rendered inside the code blocks like between the normal backticks nor the tripple backticks.

OS: Mac OS X 10.11.3

reproduce: just go in any document hit the backtick, type a html entity, hit the next backtick et voilá there it is a symbol inside the code block. Tried to make the inline code block first and copyed the text `&phone;` or `&hearts;` or any other entity but nothing helps.

**Comment by abnerlee** [comment]
fixed in version
