### ISSUE TITLE
How to stop auto capitalizing?

### ISSUE THREAD

**Issue by WTIFS** [typora/typora-issues#1601]

**Comment by abnerlee** [comment]
https://www.howtogeek.com/276158/how-to-turn-on-auto-capitalization-and-auto-periods-in-macos-sierra/

**Comment by WTIFS** [comment]
I never realized that it's the problem of Mac. Sorry and thanks!

**Comment by gujunhk** [comment]
Apple executives always think that they are smarter than anyone else in the world.
