### ISSUE TITLE
Pasting the picture makes typra unresponsive

### ISSUE THREAD

**Issue by asins** [typora/typora-issues#1604]
**Settings**
In my settings, I turned on the ability to paste images.
![image](https://user-images.githubusercontent.com/898354/42309081-32280788-806a-11e8-8d27-ca1d3c7b6459.png)

**Reproduce the problem step:**
1. Open this url in browser: https://imgsa.baidu.com/baike/pic/item/5ab5c9ea15ce36d31cce310c33f33a87e850b1c0.jpg
2. Right click inside the image to select copy image
3. Enter the Typora editing area and press Cmd+v to paste the picture. At this time, Typora will be stuck, waiting for about one minute will be displayed: !\[img\]\(https://imgsa.baidu.com/baike/pic/item/5ab5c9ea15ce36d31cce310c33f33a87e850b1c0.jpg)
![image](https://user-images.githubusercontent.com/898354/42310350-c94fe1fa-806d-11e8-94d4-0c71c5642e92.png)
![image](https://user-images.githubusercontent.com/898354/42311648-eeb52b6e-8070-11e8-846d-42e4f1d74de7.png)
4. Then press Cmd+v again to paste the image and download the image to the assets directory and display : !\[img\]\(assets/5ab5c9ea15ce36d31cce310c33f33a87e850b1c0-20180705160406003.jpg)

**Problems:**
1. The software interface is deadlocked. It is too unfriendly. Is it possible to separate the download task from a process and not affect the operation of the main interface.
2. The image download should not take a minute. I will display it in less than one second when I open it in the browser.
3. I feel that the software has been stuck for up to one minute because the download function has been unresponsive and the code expires and automatically exits.

**Comment by vassudanagunta** [comment]
I also have had the beachball when copy-pasting from some web pages. I have to force-quit Typora when this happens.

**Comment by asins** [comment]
@vassudanagunta Yes, forced to exit Typora again after opening the picture did not finish pasting.

**Comment by vertesy** [comment]
👍  Typora freezes upon drag-n-dropping an image from the web to the assets folder. Works for local files.

**Comment by abnerlee** [comment]
Fixed in new release
