### ISSUE TITLE
pasting HTML failed

### ISSUE THREAD

**Issue by gds12345** [typora/typora-issues#1605]
A long HTML page cannot be copied to typora.
Nothing happened when I pasted it. But can be pasted into Microsoft Word

**Comment by abnerlee** [comment]
From which URL/content?

**Comment by gds12345** [comment]
I selected half of the content on the page. except the directory and header.
http://www.mybatis.org/mybatis-3/zh/sqlmap-xml.html

**Comment by gds12345** [comment]
begin
![image](https://user-images.githubusercontent.com/30205371/42377160-ac644684-8154-11e8-8d54-db2d4bd500c3.png)
end
![image](https://user-images.githubusercontent.com/30205371/42377246-17dcbcc0-8155-11e8-8bbd-536bb1011c7d.png)
more than half

**Comment by ShixiangWang** [comment]
I encounter a same bug.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by ShixiangWang** [comment]
thanks @abnerlee  :+1:
