### ISSUE TITLE
Pasting italic text from Typora into Safari fails

### ISSUE THREAD

**Issue by torfason** [typora/typora-issues#1606]
This is a pretty specific bug but I thought I'd report it anyway. The issue is that when one pastes ***multiple (or at least whole) paragraphs*** from Typora into ***rich text fields*** of web sites (tested with Gmail compose window and Google Docs), using the ***Safari*** browser, the space between the italic words and the words around it is deleted. All of the bold-italic conditions seem to be required:

 * The bug does not appear when only pasting a subset of one paragraph
 * The bug does not appear in Chrome or when pasting into Word
 * It does not appear in pure text fields such as the GitHub issue field

### Reproduction

Enter the following text in Typora:

```
This is a test of how *italic text* is pasted into other applications.

The issue only occurs when when multiple paragraphs are pasted at the same time.
```

In the regular view mode, copy the text and then paste it into a rich text field in Safari. It appears as:

> This is a test of how*italic text*is pasted into other applications.
> 
> The issue only occurs when when multiple paragraphs are pasted at the same time.

Note how the phrase "how*italic text*is" has been squashed together.

I realize this is probably not high priority as is, but if this is an issue that can appear in other contexts as well it may be worth looking at. In my case, the workaround seems to be to use Chrome whenever I need to paste from Typora into a Web-based rich text field.

**Comment by abnerlee** [comment]
I tried Safari + Gmail, but not able to reproduce this.

Could you tell me your OS/Safari version?
