### ISSUE TITLE
Output for JIRA syntax

### ISSUE THREAD

**Issue by prputnam** [typora/typora-issues#1611]
It would be great if Typora had an output mode for [JIRA syntax](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all). Converting from Markdown to JIRA's syntax is 1:1, just with a different tag/symbol set. The tool [J2M](https://j2m.fokkezb.nl/) provides a handy way to convert between the two, but it would be great to have this functionality within Typora.

**Comment by abnerlee** [comment]
supported via https://support.typora.io/Export/#other-formats-using-pandoc

**Comment by danielestevez** [comment]
The format needed for the custom export should be
`pandoc -f markdown -t jira ${currentPath} -s -o ${outputPath}`
