### ISSUE TITLE
copy to clipboard from block of code by click CTRL + LMB

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1613]
Copying and pasting is the often operations. It would be great to add a feature to quickly copy from \`\`\``somecode`  \`\`\` to the clipboard.
For example: by press `CTRL` key and click `Left Mouse Button` on some **code block** or **area**

**Comment by abnerlee** [comment]
I think Typora should follow the the standard way for copy and paste -- select some text and press Ctrl+C

CTRL + LMB for copy is inconsistent with other apps.
