### ISSUE TITLE
Execute command or script from Typora UI

### ISSUE THREAD

**Issue by Essive** [typora/typora-issues#1615]
I would like to have the feature to execute a command line or script directly from the Typora UI without having a terminal window open and switching to run a command. Sometimes after I save my .md files I run specific scripts or run git commands to upload it to GitHub. It would be nice to have something like an Atom plug-in that can use a keystroke like cmd-I or cmd-E and run it.  Thanks.

**Comment by abnerlee** [comment]
We don't have plans for this feature.
