### ISSUE TITLE
How to assign hot key bindings and detect target command

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1618]
I don't known how to assign shortcut key for command of application in 

`%appdata%\Typora\conf\conf.user.json`.

Because I have locale on not english language. How find the list with commands of **Typora**

```
tried: Windows 10 x64, Typora 0.9.53 (beta)
```

**Comment by abnerlee** [comment]
You could use the non-English language menu item title directly. Or switch to English interface from preferences panel first.
