### ISSUE TITLE
Aligning LaTeX Equations in the centre

### ISSUE THREAD

**Issue by beta-decay** [typora/typora-issues#1619]
Hey, I was wondering whether it would be possible to have an option to centre-align displayed equations as is the norm for LaTeX equations. For example, in TeX Studio, an equation is rendered as:

![A centre-aligned equation](https://snag.gy/RfHE6v.jpg)

But in Typora, the same is rendered as:

![A left-aligned equation](https://snag.gy/ZwC3W9.jpg)

It's a small thing, but I think having the option will make documents look nicer.

Apart from that, everything's great!

**Comment by abnerlee** [comment]
Use math block: input "$$" and press "Return", e.g:

```
$$
math
$$
```

`$$math$$` is rendered as inline math

**Comment by beta-decay** [comment]
Huh, that's odd. Thanks anyway
