### ISSUE TITLE
pasted images from clipboard aren't as copied

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [typora/typora-issues#1621]
When I do a *copy screenshot to clipboard* command in iOS and paste it into Typora, the saved & inserted image is changed:

**When pasted into typora**
![image](https://user-images.githubusercontent.com/8518288/42726692-33c5735a-875e-11e8-8056-c266c1718f34.png)

**When pasted into this issue**
![image](https://user-images.githubusercontent.com/8518288/42726688-15575276-875e-11e8-9683-914eff534b34.png)

Is this expected behavior?

- macOS High Sierra 10.13.5
- Typora 9.9.16.2

**Comment by abnerlee** [comment]
I cannot reproduce this, do you have more detailed steps for this?

**Comment by ConstantinoSchillebeeckx** [comment]
Sure, hopefully this helps, the command used to copy the screen shot is `command` + `control` + `shift` + `4`:
![1](https://user-images.githubusercontent.com/8518288/42734194-82200d38-8805-11e8-8eb1-e777a2701891.gif)

**Comment by ConstantinoSchillebeeckx** [comment]
> Could you try open the image location after paste, and check whether the image display good or grayed out.

The image in the saved location (./assets) is also grayed out.

>Does typora works good if you paste other images (like copy image in browser) from clipboard

Yes, that works as expected.

> Which typora theme did you use, did you use any custom CSS?

I'm using the base Github theme. I did use customized CSS, however I reproduced the same issue after removing the custom CSS. For reference, here is the CSS:
```css
#write {
    max-width: 1200px; /*adjust writing area position*/
}

mark {
    color: rgb(138, 109, 59);
    background-color: #fcf8e3;
}

```

**Comment by abnerlee** [comment]
Could you try if Typora v0.9.9.19 has fixed this or not.

Please reopen this if it still happens. Currently I never met such bug
