### ISSUE TITLE
The application consumes resources in the background as a working application?

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1622]
I minimized the application to the taskbar. And I don't use it. But I noticed that my computer resources are being consumed. And saw that Typora periodically rises in line as the process that consumes the most CPU. Sometimes application is be on even first place in rating. 

![default](https://user-images.githubusercontent.com/24587938/42728076-eadc1434-87ba-11e8-9fbc-f9c2b2db6da8.png)

What processes do Typora in the background? In github is often said that Typora it's not IDE, but any IDE or text editors do not consume so many resources. Especially when they do not work or minimized to the taskbar panel. What is might be going on?

**Comment by abnerlee** [comment]
I don't think minimize a program will make it stop running, therefore the program is still running. It will continue load the image you use in your .md file, save or backup the content based on your setting, load content and monitor changes in opened folder if file sidebar are opened to keep the sidebar/content updated to disk, etc.

You could just wait for some time and CPU usage will back to 0%.

**Comment by Eskander88** [comment]
> You could just wait for some time and CPU usage will back to 0%.

This is not happening
