### ISSUE TITLE
Not support automatic numbering and quote for math equations

### ISSUE THREAD

**Issue by kokerf** [typora/typora-issues#1623]
hi! there are some issues I found in typora about math equation. I hope typora will support some useful latex expression for math.

- when I use ```\begin{equation}\end{equation}```expression in typroa, it can not automatic numbering the equations(as well as ```eqnarray```).
![](http://ovh6xh9r0.bkt.clouddn.com/github/issue/typora_issue2.png)

- the expression ```\eqref{}``` can not render the number of equation which I labeled before by ```\label{}```.

![](http://ovh6xh9r0.bkt.clouddn.com/github/issue/typora_issue1.png)

however thoese expressions is supported by [cmd-markdown](https://www.zybuluo.com/mdeditor) and [马克飞象](https://maxiang.io/). I hope typora will do better!

**Comment by abnerlee** [comment]
You need either specify `\tag` or enable auto numbering for math in preference panel

**Comment by kokerf** [comment]
@abnerlee Thanks! I perfer to use the auto numbering.
However, when I enable the auto numbering, there still some errors occurred.

- When I use `\begin{split}\end{split}`  the auto numbering is invalid.
- The auto numbering will number all the equations, ignore the command `equation` or `eqnarray`

the following codes are the cases:

```
#### case 1
$$
\begin{split}
x^2&=y+1\\&=y+1
\end{split}\label{one}
$$
reference : $\eqref{one}$

#### case 2
$$
x^2=y+1=y+1\label{two}
$$
reference : $\eqref{two}$
```

**Comment by abnerlee** [comment]
I think `\begin{equation}` should be used for `\label{}` syntax.

You could use the following:
```
#### case 1

$$
\begin{equation}
\begin{split}
x^2&=y+1\\&=y+1
\end{split}
\end{equation}\label{one}
$$
reference : $\eqref{one}$
```

**Comment by abnerlee** [comment]
Could you share the example ? In my testing, CMD also display `(???)`

![snip20180727_1](https://user-images.githubusercontent.com/1621242/43324218-229eca9e-91e6-11e8-9afb-ce08b6683a32.png)

**Comment by knifelees3** [comment]
> I think `\begin{equation}` should be used for `\label{}` syntax.
> 
> You could use the following:
> 
> ```
> #### case 1
> 
> $$
> \begin{equation}
> \begin{split}
> x^2&=y+1\\&=y+1
> \end{split}
> \end{equation}\label{one}
> $$
> reference : $\eqref{one}$
> ```

This is really helpful for me. I have search a lot for how to cite the equations in Typora
