### ISSUE TITLE
Ubuntu 16.04 does not have glibc 2.27 yet

### ISSUE THREAD

**Issue by Misairu-G** [typora/typora-issues#1624]
I was trying version 0.9.53 in Ubuntu 16.04, and found I cannot open typora from terminal with a message `typora: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found (required by libffmpeg.so)`. 

Seems like the libffmpeg.so that bundle with typora require the newest version of glibc. However 16.04 only have glibc 2.23 for now.

**Comment by abnerlee** [comment]
try install glibc by `apt-get install`

**Comment by SrealZ** [comment]
You may need to update your system to Ubuntu 18.04 which include GLIBC_2.27 version in libm.so
