### ISSUE TITLE
Failed pdf export from MarkDown

### ISSUE THREAD

**Issue by PaQwecy** [typora/typora-issues#1625]
Hi

I use a windows OS and I just started learning to use MarkDown on R.
I notice that the pdf files I generate on R are not displayed in typora.
Is there any help you can give me?

Thanks!

**Comment by abnerlee** [comment]
> I notice that the pdf files I generate on R are not displayed in typora.

Typora cannot open/display PDF file, it only supports Markdown and plain text file

**Comment by PaQwecy** [comment]
Thanks for the response AbnerLee.
Perhaps, I didn't explain the problem clearly.
What I mean is this: I run a script on R in MarkDown and I open the .md file in typora. 
Problem is all graphs I save as PDF in R.Markdown do not show in the .md file when I open it in typora. I'm new to this. Hope this clearly outlined my problem.
Thanks for the help.

**Comment by abnerlee** [comment]
Thanks for the explanation

do you mean https://github.com/typora/typora-issues/issues/704? Is it supported by R Markdown?
