### ISSUE TITLE
Cannot use Full angle parenthesis in link address.

### ISSUE THREAD

**Issue by LazyKnightX** [typora/typora-issues#1628]
`![img](files/Foo（Bar）/preview.gif)`
`[file](files/Foo【Bar】/file.xxx)`

will be rendered as

`![img](files/Foo(Bar)/preview.gif)`
`[file](files/Foo[Bar]/file.xxx)`

when I press "enter" in WYSIWYG mode.

Currently, I could fix it in source code mode, but this should be a bug.

* Version: 0.9.53 (beta)
* System: Windows 7 sp1

**Comment by abnerlee** [comment]
Please unselect Edit -> Smart Punctuation -> "Remap Unicode Punctuation on Parse" from menu
