### ISSUE TITLE
Ubuntu repo key is no longer availabe

### ISSUE THREAD

**Issue by miguelcarax** [typora/typora-issues#1629]
Shell blocks while adding the key 

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE`

And it fails at installing

```
: GPG error: https://typora.io/linux ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
W: The repository 'https://typora.io/linux ./ InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by abnerlee** [comment]
The key is still on key server

http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xBA300B7755AFCFAE

Please do `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE` first, if it fails, paste its failure message.

**Comment by MaxIndu** [comment]
There is following error message indicating that the signature coudn't be verified. 

```
Err:11 https://typora.io/linux ./ InRelease                                                                            
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
```
To resolve that issue add the key as follows,
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BA300B7755AFCFAE
```

**Comment by hsandt** [comment]
I did the keyserver command and it seems to have worked:

> Executing: /tmp/apt-key-gpghome.NYKikmgNTS/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BA300B7755AFCFAE
gpg: key BA300B7755AFCFAE: public key "Abner Lee <abner@typora.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1

but on next sudo apt update I get the same error again... I contacted Typora support (in fact, I was reporting an unrelated bug, they asked me to upgrade Typora, but this error got in my way, so I'm reporting that instead now)

**Comment by hsandt** [comment]
OK, so I was following https://support.typora.io/Typora-on-Linux/ alternative method to setup the source manually. Using the standard method with `apt-key add` and `add-apt-repository` works fine. I had no warning on my Ubuntu 20.04, so maybe this older method is still worth trying with this version.
