### ISSUE TITLE
The scroll bar breaks sub-pixel font rendering

### ISSUE THREAD

**Issue by wdhwg001** [typora/typora-issues#1630]
I notice that when the content is longer than the window size, the scroll bar will appear and the subpixel font rendering will not work properly.
Reproduce:
![image](https://user-images.githubusercontent.com/8943519/42947065-0e6e28f0-8b9f-11e8-823e-e882027333c9.png)
And then resize the window to make the scroll bar appears:
![image](https://user-images.githubusercontent.com/8943519/42947147-44a1c2ec-8b9f-11e8-914e-635e5c591f7c.png)
The theme I use is the default 'github' theme, and changing to another theme won't help.

When I'm using a standard DPI screen, if the text is rendered in gray-scale mode instead of sub-pixel mode, the text will be extremely blurry, especially for some Chinese characters.

**Comment by abnerlee** [comment]
We updated to newer version of Chromium in last update, which may improved the text rendering logic.

But Chromium on Windows seems does not provide options for `font-smooth`
