### ISSUE TITLE
Auto-Correct words on Windows/Linux

### ISSUE THREAD

**Issue by diomed** [typora/typora-issues#1631]
CAps happen.

could you please integrate some kind of fix for this?

**Comment by AlexPasternak** [comment]
What platform are you on? Because on macOS this is fixed automatically for you, in any text editor.

![2018-07-19 13 14 21](https://user-images.githubusercontent.com/1819485/42959148-c19c122e-8b55-11e8-9261-1d764aa13d80.gif)

**Comment by diomed** [comment]
yeah, should have mentioned : I'm on Windows 10

**Comment by abnerlee** [comment]
#1293

**Comment by dtrichter** [comment]
+1  I would love to have autocorrect in my favorite editor - Typora!

@abnerlee I'm not sure this is a duplicate of #1293.  The request here is to enable autocorrect for misspelled words - (as @AlexPasternak showed)  However, #1293 seems to me to be more directed at autocompletion which is similar, but perhaps different enough to merit a separate issue?  I could certainly be wrong! :D
