### ISSUE TITLE
Diagrams > Mermaid > How to specify "curve" : "basis"

### ISSUE THREAD

**Issue by kbsizer** [typora/typora-issues#1632]
Using the online Mermaid editor (https://mermaidjs.github.io/mermaid-live-editor), I can specify smooth curved connector lines as follows:

```javascript
{    "theme" : "default",
     "flowchart" : { "curve" : "basis" }
}
```
But I can't find a place or a way of specifying this within Typora.  Would be happy with a place to put it in CSS theme file or embedding (à la style directive) in the diagram definition itself.

Apologies in advance if this is the wrong place for this question / feature request.

**Comment by abnerlee** [comment]
It is not supported yet.

I will merge this into https://github.com/typora/typora-issues/issues/374 since they are similar requests

**Comment by Albert-King** [comment]
> It is not supported yet.
> 
> I will merge this into #374 since they are similar requests

sir, I would try modifying flowchart curves with the code ":root {--mermaid-flowchart-curve: linear; }",which comes from illustrations at the bottom in https://support.typora.io/Draw-Diagrams-With-Markdown/#flowcharts-1, but it's not work anyway,of course I viewed #374 ,even try importing mermaid.js into Typora\resources\app\window.html, unfortunately，I can't custom the style of curve. I would appreciate it if you give me favor

**Comment by abnerlee** [comment]
Did you follow https://support.typora.io/Add-Custom-CSS/?

**Comment by Albert-King** [comment]
> Did you follow https://support.typora.io/Add-Custom-CSS/?

Sorry for taking so long to reply, because i add a script in Typora\resources\app\window.html,  which allow me to load local mermaid.js, so that my changes is not worked.
also appricate @marcnischan very much

**Comment by joeri-juramento** [comment]
Alternative inline fix:

Add `%%{init: { "flowchart": { "curve": "basis" } } }%%` just onder mermaid, like:

```
```mermaid
%%{init: { "flowchart": { "curve": "basis" } } }%%
graph LR;
A-->B
...
```
