### ISSUE TITLE
How to change the font size & width of the export image?

### ISSUE THREAD

**Issue by ProteinPig** [typora/typora-issues#1633]
When I export a PNG file, it always 650px width, and i don't find a way to change the size of the font.
I try to change it in theme css file, but nothing changed.
So, is there a way to do that?

**Comment by liuquanqing** [comment]
the same question，hope to  solve it

**Comment by techbless** [comment]
How about exporting as HTML and converting it to image?
converted HTML has sufficient width.

It works fine for me.

**Comment by DreamWaterFound** [comment]
Looking forward to adding this feature, which will make Typoria even better. Thank you for your work :rose:

**Comment by abnerlee** [comment]
supported
