### ISSUE TITLE
Parsing HTML tag <a> incorrect

### ISSUE THREAD

**Issue by othree** [typora/typora-issues#1634]
Hi I found this issue when trying to insert an HTML code snippet from wikimedia commons

```html
<a title="By Thorin Oakenshield II [CC BY-SA 4.0 
 (https://creativecommons.org/licenses/by-sa/4.0
)], from Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:%D0%9A%D0%B0%D1%80%D1%82%D0%B0_%D0%9E%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA%D0%BE%D0%B9_%D0%93%D0%BE%D1%80%D1%8B_.jpg"><img width="512" alt="Карта Одинокой Горы " src="https://upload.wikimedia.org/wikipedia/commons/b/b3/%D0%9A%D0%B0%D1%80%D1%82%D0%B0_%D0%9E%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA%D0%BE%D0%B9_%D0%93%D0%BE%D1%80%D1%8B_.jpg"></a>
```

I think the value of the `href` caused the issue.
If I remove `_.jpg`. It works correctly.

The resource: <https://commons.wikimedia.org/wiki/File:%D0%9A%D0%B0%D1%80%D1%82%D0%B0_%D0%9E%D0%B4%D0%B8%D0%BD%D0%BE%D0%BA%D0%BE%D0%B9_%D0%93%D0%BE%D1%80%D1%8B_.jpg>

**Comment by abnerlee** [comment]
caused by https://github.com/typora/typora-issues/issues/1484
merge into that issue.
