### ISSUE TITLE
new bug concerning overwriting selected characters?

### ISSUE THREAD

**Issue by truefalsename** [typora/typora-issues#164]
Hi, I noticed a strange behaviour of Typora concerning the substitution of highlighted characters. If i select some letters in a word for instance and then type in another words to replace them, the new word is effectively inserted two or three characters on the right of the original location. This happens also in math mode, at least within single dollars. For instance, starting from 'we neglected', I selected the 'e' in 'we' and typed in an 'f'; the result was 'w nfeglected'. 

As we are here, it could be also nice if Typora supported  looking words up in the dictionary, on OSX, which you usually can do by tapping with 3 fingers or force-clicking.

**Comment by abnerlee** [comment]
> If i select some letters in a word for instance and then type in another words to replace them, the new word is effectively inserted two or three characters on the right of the original location.

It seems I cannot reproduce this bug for now, did you use non-English keyboard or IME?

> As we are here, it could be also nice if Typora supported looking words up in the dictionary, on OSX, which you usually can do by tapping with 3 fingers or force-clicking.

duplicate with #47

**Comment by truefalsename** [comment]
IME = ? I used standard US keyboard.

**Comment by truefalsename** [comment]
Hello, even with the newest version I am still experiencing this annoying bug. It seems that once you overwrite or cancel some selected text the cursor jumps forward of some spaces.
[bug.zip](https://github.com/typora/typora-issues/files/345797/bug.zip)
I am attaching a video of the problem, which seem to show up only when parts of a word are involved. At the beginning I overwrote the whole "probability" word and everything was fine. However, when I selected parts of the word the cursor jumped forward. Each time, after overwriting a part of the word, I undo and notice that the scope of the cursor does not match the original position

**Comment by abnerlee** [comment]
@truefalsename still have this bug?

**Comment by truefalsename** [comment]
ye, it shows up from time to time while editing heavy documents filled with formulas and tables.

**Comment by abnerlee** [comment]
Maybe related to inline math. Could you attach a sample "*.md" snip which would trigger this bug?

**Comment by truefalsename** [comment]
Could be: I believe that when the bug shows up the rendering of math in general slows down. Restarting Typora usually does the trick for a while though. Atm I am not sure about which file I was editing when the bug showed up lat time, will attach a notebook as soon as the bug shows up again.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/25
