### ISSUE TITLE
How to properly escape dollar sign in latex and markdown table

### ISSUE THREAD

**Issue by yihengli** [typora/typora-issues#1642]
Recently I noticed the $ dollar sign cannot be properly escaped if it's wrapped inside a latex formula which is inside a markdown style table

## Example

```
### No Inner dollar

| $ 1 \times 2 $ | $ 3 \cdot 1 $ |
| ----- | ------ |
| 2  |  3 |

### Escape with `$`

| $$ 1 \times 2$ $$ | $$ 3$ \cdot 1 $$ |
| ----- | ------ |
| 2  |  3 |


### Try to escape with `\`

| $ 1 \times 2\$ $ | $ 3\$ \cdot 1 $ |
| ----- | ------ |
| 2  |  3 |

### Try to escape with `span`

| $ 1 \times 2<span>$<span> $ | $ 3<span>$<span> \cdot 1 $ |
| ----- | ------ |
| 2  |  3 |

```

## Actual Result

![1](https://user-images.githubusercontent.com/13440386/43306207-3de9835a-912f-11e8-9479-648711e87b7d.png)

## Expectation

Only the `$$` sign successfully escapes the inner `$` sign. I am not sure if the failure of `\` inside table is one of the designs of Typora markdown syntax. As this is not consistent with other popular markdown editor, such as jupyter notebook, it will be appreciated to know how to make the format consistent

## Appendix (jupyter)

![2](https://user-images.githubusercontent.com/13440386/43306444-fd40f83c-912f-11e8-9189-3064cd5c65ca.png)

**Comment by abnerlee** [comment]
Should be able to escape with `\`

**Comment by abnerlee** [comment]
Fixed in new release
