### ISSUE TITLE
Using Typora + Hexo

### ISSUE THREAD

**Issue by yezige** [typora/typora-issues#1643]
When using Typora to generate Hexo's _posts file, there are some inconveniences in the location of the image generation. I hope to put the image in the "file" folder of the same level as _posts, and create a folder with the post name, based on my disgusting Requirements, I hope the author can provide an advanced method for configuring the main path of the image (set in conf.user.json).

**Comment by abnerlee** [comment]
You mean https://support.typora.io/Images/#relative-path-to-certain-folder?

**Comment by yezige** [comment]
Sorry, this can only solve the problem of the relative path of the image display. The image is still placed in the _posts directory, and it can't solve the problem that the image is automatically stored in the "file" directory.

**Comment by abnerlee** [comment]
https://support.typora.io/Images/#copy-image-files-to-target-folder-when-insert-local-image and 
 https://github.com/typora/typora-issues/issues/1471?

**Comment by yezige** [comment]
Yes, my question is the same as 1471
