### ISSUE TITLE
Provide a roadmap 

### ISSUE THREAD

**Issue by frankgerhardt** [typora/typora-issues#1645]
Here http://abnerlee.github.io/typora/2015/03/11/why-typora/ we see that Typora is in the making since March 2015. 
- When will the final, commercial version will be released?
- What will be the price?
- What are the next beta releases towards 1.0 and what features will they have?
- What are the planned releases after 1.0 and what features will they have?

I really like Typora but it sort of looks stuck somewhere. I would really like to pay for a good 1.0 release and get beyond the beta annoyances like  #1418. On Twitter I don't see many updates, on Github the same. The issues project seems to be active though. Please don't let your users in the dark! Let us know where Typora is going, and when.

**Comment by AlexPasternak** [comment]
From my standpoint, it's certainly fine as a 1.0 product now, so I don't understand the long delay to release. It's not in beta shape, and every software will have a few bugs left. Current state should be released as 1.0 very soon, then start updating and iterating on other features, like the "jump to header" recently requested.

**Comment by abnerlee** [comment]
Close since we do not have plans of providing a public roadmap

**Comment by szepeviktor** [comment]
Note that not providing a roadmap generates uncertainty.
