### ISSUE TITLE
PageUp/PageDown keys don't move caret past images

### ISSUE THREAD

**Issue by dooof** [typora/typora-issues#1649]
The PageDown key correctly moves the text caret to the current screenful of text you are on.  However, as soon as you pass by an image, the caret gets stuck at the image.  You can continue to PageDown, but the caret never moves past the image.  Typing or pressing an arrow key takes you back to the image.

PageUp works the same way.

Version 0.9.53
Win 10

I previously logged an issue about PageUp/PageDown and closed it thinking it was fixed, but I didn't realize that the problem only occurs when there are images.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by dooof** [comment]
Tested with 0.9.56 and problem still occurs.

**Comment by abnerlee** [comment]
part of #1164
