### ISSUE TITLE
update after file changed on disk

### ISSUE THREAD

**Issue by willwhitney** [typora/typora-issues#165]
Some other applications (e.g. iA Writer) immediately update the contents of the editor when it's changed on disk, but Typora gives the message "File content is changed by external applications. Reload content?"

Seamlessly updating the text would better support workflows involving git, Dropbox, or iCloud.

Love the app so far, and I look forward to its future!

**Comment by eevilspock** [comment]
I would say the dialog should only appear if the content has both changed in Typora and on disk, in which case the user should get a choice.

**Comment by abnerlee** [comment]
@willwhitney this dialog is supposed to show only when you have unsaved content in Typora. 

Did you saw such dialog when you saved contents in typora then modified with other apps or open with typora then modified with other apps?

**Comment by willwhitney** [comment]
This happened after opening an iCloud Drive file with Typora, then editing
it on another device.

**Comment by abnerlee** [comment]
Fixed in new version.

Content will be refreshed automatically when there's no unsaved changes in typora, and a dialog will show whether to load new content or not when there is unsaved changes in typora
