### ISSUE TITLE
No save dialog

### ISSUE THREAD

**Issue by N-Upchurch** [typora/typora-issues#1650]
When selecting "Save As," or when selecting "Save" when attempting to exit an unsaved document, no save dialog appears. 

* Windows 10, Build 17728

**Comment by abnerlee** [comment]
@N-Upchurch Is there any detailed steps which I could reproduce this bug?

**Comment by N-Upchurch** [comment]
I was attempting to record a gif to show you, but the issue seems to have resolved itself. No idea what was going on there.

**Comment by N-Upchurch** [comment]
Issue present gain. See below. 
![halpsimple](https://user-images.githubusercontent.com/8893713/44226601-254f1800-a156-11e8-8dc5-8175dd201228.gif)

**Comment by N-Upchurch** [comment]
The issue occurred after putting PC in sleep mode with an unsaved typora document open. When the PC exited sleep mode, the save dialog no longer appeared. Restarting the PC restored save functionality.

**Comment by abnerlee** [comment]
Fixed a bug which may cause this in 0.9.58. Please reopen this if it still happens
