### ISSUE TITLE
Can I add another platform in typora?

### ISSUE THREAD

**Issue by uglykidney** [typora/typora-issues#1652]
The most part of typora that  really attracted to me is gather many API from awesome third party platform like pandoc, mermaid, js flow and sometime i want more feature from other html platform. I have to export in html and switch to IDE that I use for writing html. with this method It's ok but if i want to add into it like pandoc or mermaid .Do you have some solution or suggestion for this case.

**Comment by abnerlee** [comment]
We would cover this in https://github.com/typora/typora-issues/issues/1451

Also, since Markdown is file based, you could always use command line to export the *.md file
