### ISSUE TITLE
List keyboard shortcuts within documentation

### ISSUE THREAD

**Issue by LexiconCode** [typora/typora-issues#1655]
While the keyboard shortcuts are clearly laid out menu they need to be represented as a table within "Quickstart". This allows users to reference the shortcuts without navigating through menus. Use cases such as shortcuts to be printed off or put in a separate window for reference.

https://github.com/typora/typora-issues/issues/167

**Comment by abnerlee** [comment]
see https://support.typora.io/Shortcut-Keys/
