### ISSUE TITLE
Support for Markdown presentations & related bug in quote hotkey

### ISSUE THREAD

**Issue by vertesy** [typora/typora-issues#1656]
## Making presentations in Markdown

Markdown is quickly evolving in its scope use, one which is **making presentations**, or slides directly from your .md file. This way of creating 100's of slides for teaching spared me tremendous amounts of time.

#### The syntax of presentation-markdown

The syntax of "presentation-markdown" contains a few (and yet ill defined) features, such as the 

- `> -` for bulletpoints showing up one after another. 
- {width=200px} extension for image links
- code snippets for e.g. 2-column layout

It is not clear (to me) if  "presentation-markdown" (lack of a better name) will always be part of markdown, and when the syntax gets solid (not even solid for markdown itself).

Yet, it is a very useful application of markdown language that might worth the support of Typora. 

#### Software

There are dedicated editors like: [Slidium](https://www.neomobili.com/products/slidium-markdown-presentation/), [Deckset](https://www.deckset.com/), and RStudio's `knitr` package, but it would be great if Typora would have some minimal support for it (not to mention a preview or WYSWYG  feature)

#### Support in Typora

As an example, I often need to convert simple (or ordered) lists to sequentially appearing lists (`>` as above), but adding the `>` sign manually is cumbersome.

There is `Cmd+alt+Q`, but it  adds the `>` at the wrong place: From `- My point` I get  `- > My point` instead of `>- My point` (This is a generic-markdown bug).

A bugfix, and Support for some other features would be truly great.

**Comment by abnerlee** [comment]
seems duplicate with https://github.com/typora/typora-issues/issues/89

About the bug, yes, `> - My point` seems more reasonable

**Comment by vertesy** [comment]
Thanks for checking on it! 

I have seen #89, but I did nee it covering my point, which is:

- There is existing syntax to make presentations from markdown
- This syntax is recognized by [Pandoc ](http://pandoc.org/MANUAL.html#producing-slide-shows-with-pandoc) or a slight variant by [Rmarkdown's knitr
package](https://rmarkdown.rstudio.com/lesson-11.html).
- This use of Markdown concerns a large set of users (many people give presentations)
- and it would be great to have **_syntax support_** and *snippet hotkeys*  from Typora
-  Export can be handled by pandoc, and WYSIWYG viewer would be just a cool extra

**Comment by wamserma** [comment]
Regarding the prsentation support: Slidium and Deckset are afaik Mac-only, so this is clearly a point for Typora. A common use case is to quickly whip up a mix of agenda and presentation with RMarkdown (ioslides, knitr) and use this for a brainstorming session. However, the workflow is a bit of a drag then, as one needs to recompile after each edit. This is where Typora can really shine as you can quickly switch between source and presentation (and even have in-place editing).

**Comment by Geliv** [comment]
+1 for the presentation mode! 

If typora has the presentation mode, there's no need for me to first export `md` to `doc` then copy paragraphs with equations to `ppt`, which will be a great convenience. 

Actually a basic support will be great already, such as using `---` to create a new slide just like the `Marp` app. 

![image](https://user-images.githubusercontent.com/20089973/48454842-e6cc0680-e7f3-11e8-8adb-a087cc69f563.png)

Really hoping this could be a possible feature in some later updates!

**Comment by swissmanu** [comment]
+1 for a collaboration with @marp-team

https://twitter.com/swissmanu/status/1131136577462263809

**Comment by abnerlee** [comment]
#89

**Comment by abnerlee** [comment]
I don't think syntax support is needed unless we make it a tool that supports markdown presentation. But markdown presentation is out-of-scope for Typora.
