### ISSUE TITLE
The mac edition doesn's support inline math 

### ISSUE THREAD

**Issue by Dinghow** [typora/typora-issues#1662]
Just like its markdown reference file shows( typora version :0.9.9.16.2(beta))
![](http://ouluvpd0z.bkt.clouddn.com/typora_issue1)
The inline math formulas don't display as that on windows.

**Comment by abnerlee** [comment]
Please enable it in settings

**Comment by Dinghow** [comment]
@abnerlee 噗，献丑了(･_･;

**Comment by abnerlee** [comment]
#1507

**Comment by abnerlee** [comment]
#1507 
#1510
