### ISSUE TITLE
Can't run Typora on Archlinux

### ISSUE THREAD

**Issue by iPeven** [typora/typora-issues#1663]
When I run Typora in terminal, the error is below:
[1]    970 segmentation fault (core dumped)  typora

**Comment by abnerlee** [comment]
We don't have Archlinux to check this issue, But May relates https://github.com/electron/electron/issues/11234

And please include more details, like the log, Linux/Kernel version, GPU driver, etc.
And please try re-install the lasted version

**Comment by iPeven** [comment]
I have fixed it up, Typora can't run with Archlinux is because I upgraded the glibc to 2.28.1, after I downgraded it to 2.27-3,  Typora was able to work again!

**Comment by abnerlee** [comment]
seems same with https://github.com/typora/typora-issues/issues/1671

**Comment by iPeven** [comment]
It only seems happen with glibc2.28-1,  glibc2.28-4 is ok
