### ISSUE TITLE
have a keymap list

### ISSUE THREAD

**Issue by Zeroto521** [typora/typora-issues#1664]
hi~
I think it is a time to have a keymap list.

> I have searched for google & typora home page. 
No any useful docstring. _(:3」∠)_

Anyway it is not a better way to know about keymap by checking **typora toolbar**.

**Comment by abnerlee** [comment]
dup https://github.com/typora/typora-issues/issues/1655

**Comment by Zeroto521** [comment]
Thanks.
Maybe I could write a keymay by markdown table style, when I use typora.
So have any place for me to _pull request_ ?

**Comment by abnerlee** [comment]
Yes, -> https://github.com/typora/wiki-website
