### ISSUE TITLE
missing LeftPadding in mermaid gantt

### ISSUE THREAD

**Issue by jindaxia** [typora/typora-issues#1665]
I noticed the gantt on original mermaidAPI has a 75 left padding like 
![image](https://user-images.githubusercontent.com/587992/43876374-4c558db0-9bc7-11e8-85b6-52e9deba4dcc.png)

but in typora the padding is set to 0 
![image](https://user-images.githubusercontent.com/587992/43876426-916a6948-9bc7-11e8-9f8e-2fce8e2d9528.png)

I have to edit \resources\app\app\window\frame.js manually to resolve this

So , IS there a method to override this setting with  conf.*.js

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/374

**Comment by abnerlee** [comment]
will be fixed with #2142
