### ISSUE TITLE
Caret navigation disappears when I edit long files

### ISSUE THREAD

**Issue by marbel82** [typora/typora-issues#1668]
I don't see the caret navigation (keyboard cursor) when I edit the source code.
Sometimes it appears at the end of the line or when I switch styles. But after a while it breaks down again and I don't see the caret.

I attach a sample file.
I'm using Typora for Windows version 0.9.53(beta)
[typora-caret-bug.zip](https://github.com/typora/typora-issues/files/2273513/typora-caret-bug.zip)

**Comment by abnerlee** [comment]
Merge into https://github.com/typora/typora-issues/issues/1164
