### ISSUE TITLE
[Feature] Add terminal / cmd feature in typora

### ISSUE THREAD

**Issue by satyakresna** [typora/typora-issues#1669]
Hi there, usually I'm using markdown for create some article and push it to github repository. Is it possible to add feature or quick command (e.g ```ctrl + ~```) in Typora to show terminal in Typora App? Maybe the interaface looks like VS. Code.

<img width="1440" alt="screen shot 2018-08-10 at 5 32 22 am" src="https://user-images.githubusercontent.com/11099186/43927095-ef5ef0e0-9c5e-11e8-9e1d-eeb242b8ae17.png">

Thanks.

**Comment by abnerlee** [comment]
We don't have plans for this.
