### ISSUE TITLE
where to get a list of all hot keys?

### ISSUE THREAD

**Issue by stickgoal** [typora/typora-issues#167]
I searched the website and github and your blog,but find no hot key reference.Could it be in help page of typora?

**Comment by abnerlee** [comment]
Hot keys contains three parts:

1. Listed in Help->Quick Start from menu bar.

2. In menu, there are hotkeys in the right side of the menu item (Switch to Native Windows style form preference panel if you're using Typora for Win).

3. Hot keys following platform rules.
    For example, on Windows `Ctrl`+`Backspace` would delete characters till word start, on Mac `Shift`+`Up` would move cursor up and select all texts between this cursor position and last cursor position. For mac part, you could refer to <http://guides.macrumors.com/Keyboard_shortcuts> (section *Shortcuts Common to Most Applications* and section *Text Shortcuts*), for Windows part, maybe this -- <http://www.howtogeek.com/115664/42-text-editing-keyboard-shortcuts-that-work-almost-everywhere/> (I cannot found a good article to lists shortcut keys on Windows).
    If there's a hot key rule for text editing on Windows/Mac, but not work for typora, then it is a bug and please feel free to report to this.

Those should be all supported hot keys.

**Comment by stickgoal** [comment]
Thanks a lot  for your reply.The second part just what I want.
I happened to find the `ctrl+shift+O`  could open outline panel when I in unibody style of windows.Before that I never see a markdown editor with a outline panel.So I just wanna to know is there any other magic things .That's why I post this question.
BTW,It's a wonderful app,I have switch my default md editor from markdownpad to typroa.Thanks for your job!

**Comment by AlexPasternak** [comment]
I can't believe it hasn't been mentioned, but for viewing hot keys in Mac apps, the free CheatSheet app is the best way to go.

https://www.mediaatelier.com/CheatSheet/
