### ISSUE TITLE
Issue with Footnotes

### ISSUE THREAD

**Issue by BrianHung** [typora/typora-issues#1678]
I'm noticing two issues concerning footnotes in Typora. 

For reference, this is `Version 0.9.9.16.2 (0.9.9.16.2)` for `MacOS`. 

1. Unable to paste anything in a non-empty footnote. After entering a few characters, I am unable to paste any text after that point. This issue has been previously brought up here #1147.

2. Display-math in a footnote. When you try to input display-math by using $$, and then export the file to an image or an html, the display math block is above the whole footnote section.

For example,

<img width="500" alt="footnote" src="https://user-images.githubusercontent.com/15721634/44009884-b28ff4dc-9e63-11e8-9d02-b37428a391a9.png">

This, however, may be more with an issue with pandoc since I also encounter the error by using that as well.

**Comment by abnerlee** [comment]
@BrianHung Hi, could you send us (hi@typora) a sample me file that can reproduce the 2nd issue?

**Comment by BrianHung** [comment]
Just sent it.

**Comment by abnerlee** [comment]
> Display-math in a footnote. When you try to input display-math by using $$, and then export the file to an image or an html, the display math block is above the whole footnote section.

**Comment by abnerlee** [comment]
For the 1st issue, I will reopen https://github.com/typora/typora-issues/issues/1147 instead
