### ISSUE TITLE
Please add Heading 6  for list when preview 

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#168]
It seems Typora only support Heading 1 - Heading 5 when preview, but sometimes I found it's not enough, could you please add Heading 6 in preview, thanks.

**Comment by abnerlee** [comment]
`###### header6` is already supported.

New version add missing shortcut key support for `h6` (`cmd+6` or `ctrl+alt+6`)

**Comment by leewi9** [comment]
My typora version is 0.9.9.4, but it seems I still can not use `cmd+6`.

**Comment by abnerlee** [comment]
Should be fixed in new version
