### ISSUE TITLE
Add ability to sort file tree

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#1680]
Unless I'm missing something (entirely possible), there's no way to sort the file tree; the default in either list view or tree view seems to be descending alphabetical. 

I would love the option to reverse that because I name my documents by date (e.g., 2018-08-14_whatever.md).

**Comment by tenbob** [comment]
Thanks - the latest version v0.9.71 includes this as a new feature. The file list can be sorted in decending or ascending order. This is great, but there's still a snag. Like the OP, I name my files by date. So I can bring the latest files to the top. 

But they are not **right** at the top. Above them are all the subfolder names. So the files I want to access are still off the screen. The folder names are mostly irrelevant anyway. They just contain the image assets belonging to various other files. 

How about an extra check box near the sorting buttons to include/exclude folder names from the list.

**Comment by abnerlee** [comment]
reverse sort has been supported in lastest version.

**Comment by abnerlee** [comment]
Custom ordering goes to #3655

**Comment by 1999FordFocus** [comment]
+1
