### ISSUE TITLE
sluggish typing responsiveness even in moderately sized files (6kb) files 

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1682]
I've been experiencing this recently, but not 100% sure. Just want to post and see if other experience this too.  This is the very first time I've experienced sluggishness, so I think this is new/distinct from the issues I note below.

It is more pronounced in very large and complex files (lots of nested lists) but it's significant (painful even!) on even moderately sized files like the one I'm editing now (6kb, 900 words). 

It's definitely Typora not my computer because I can switch to another app (e.g. Safari typing where I am this) and typing will be very responsive) and then back to Typora where it is sluggish, sometimes to the point it makes editing difficult (on larger files, perhaps those with more formatting like many nested lists). I'll try an pin down the conditions that make it sluggish and report back here.

I'm on macOS High Sierra 10.13.6. 

I created a new issue since #68 is about "very long files". #200 is about Windows. Not yet sure this is a case of #58.

**Comment by abnerlee** [comment]
This is about performance optimization.

merge into #58 #68
