### ISSUE TITLE
support autonumber in sequence

### ISSUE THREAD

**Issue by zhanyr** [typora/typora-issues#1686]
![image](https://user-images.githubusercontent.com/12031033/44246705-29407000-a212-11e8-8352-b0f1c3b5662b.png)

**Comment by abnerlee** [comment]
`autonumber` is not supported by https://github.com/bramp/js-sequence-diagrams which Typora use for rendering diagrams. 

Please post issue there for new syntax support in js-sequence-diagrams

**Comment by abnerlee** [comment]
`autonumber` is not supported by https://github.com/bramp/js-sequence-diagrams which Typora use for rendering diagrams. 

Please post issue there for new syntax support in js-sequence-diagrams

**Comment by zhanyr** [comment]
ok, thanks.
