### ISSUE TITLE
Selecting the inner-text of a <u> tag causes you to select the <u> tag, making the user have to manually select the inner-text of the underline tag to apply formatting.

### ISSUE THREAD

**Issue by ghost** [typora/typora-issues#1687]
Minor Issue but definitely affecting my work-style and performance.

**Edit: Woops. Happens with bolding too. Guessing its not really a bug but with the header options it never happens. You can close this issue if you don't believe its needed.**

**Comment by abnerlee** [comment]
should be ok now
