### ISSUE TITLE
Github theme issue, and theme folder corruption by 0.9.9.54 update

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#1688]
Updating to the newest version broke the Github theme for me, specifically the formatting of code blocks.  Code blocks became really hard to read because the previous font settings are gone.  The font family used to be `Consolas, "Liberation Mono", Courier, monospace` but now it is just `monospace`, which results in hard to read code blocks, at least on Windows 7.

Further compounding the problem, the installer unconditionally copies `themes` to `old-themes`, *overwriting the backup* if the update is uninstalled and re-installed.

I was lucky enough to figure out the issue was with the stylesheet and find the old copy (and made a copy of it) before reinstalling the update (which I had uninstalled in an attempt to fix what seemed at first like mysterious font breakage).  The updater should not copy everything to a single "old themes" directory (since this guarantees lost backups if reinstalled) but instead use a different backup directory each time, or check whether the files need to be backed up or are the same as what is being installed.

**Comment by abnerlee** [comment]
The built-in theme will be updated after version up. 

User themes/CSS are written separately, like `base.user.css` or `github.user.css` (https://support.typora.io/Add-Custom-CSS/)

**Comment by pjeby** [comment]
I'm not talking about a user theme; I'm saying the built-in theme changed font family in this release, making code blocks much less legible than they were before, and that it was hard to recover from this issue because installing an older version (and even uninstalling Typora completely) didn't restore the old theme.
