### ISSUE TITLE
Export to GFM / markdown extra / other markdown spec (math, toc, sups, subs and dels)

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#169]
``` markdown
*Regular* **markdown** doesn't support ^these^ or ~these~ or even ~~these~~.
```

Typora displays this as

> _Regular_ **markdown** doesn't support <sup>these</sup> or <sub>these</sub> or even <del>these</del>.

These things makes my days so much easier. But alas, this markup is quite special and, for example, Wordpress has no support for this (no plugins either). There should be an option "Copy as markdown extra" which would provide this to the clipboard:

> *Regular\* **markdown*\* doesn't support <sup>these</sup> or <sub>these</sub> or even <del>these</del>.

This is something one can easily inject to a blog post, another editor, github etc.

**Comment by abnerlee** [comment]
Thanks for the suggestion.

For Mac only temp workflow:

1. hold `option` key and click Menu->File->Export->Native
2. Save the exported `.native` file somewhere.
3. use Pandoc to convert it to markdown. (`pandoc xx.native -t markdown_phpextra -o yy.md`)

**Comment by waahto** [comment]
Thanks for the suggestion, yourself :) Seems that you only need to make two buttons for that — export and copy.

**Comment by Lasamar** [comment]
Hi, sorry to reopen this but It is possible to have the same functionality in debian distribution too?

**Comment by rose00** [comment]
Suggestion:  Support one or more "copy as" commands which pipe the result through `pandoc -fgfm -tsomething` before handing it to the keyboard.  Also support one or more "paste as" commands which do the same in reverse.  Also support one or more "save as" and "open as" commands that also use a pandoc filter.  In the case of file read and write, maybe allow the file extension to play a role.  If this were built as a way to manage calls to pandoc at the edges of typora, then some of the pressure for supplying plugins might go away.

A deluxe treatment of this might include a way to configure any number of named markdown variants, each corresponding to a selection of pandoc settings.  Settings could be managed using a properties file, and/or a dialog pane.  Standard pre-configured variants would be those supported directly by pandoc: markdown_strict, markdown_phpextra, markdown_mmd, gfm (native for typora), markdown (all of pandoc's extensions), html.

That way typora could open files for reading (if not editing), with some help from the user.

**Comment by abnerlee** [comment]
If it is for export, then it is partially supported as https://support.typora.io/Markdown-Export/
