### ISSUE TITLE
Javascript element is being removed

### ISSUE THREAD

**Issue by ksurya** [typora/typora-issues#1691]
I'm adding the following element to a markdown file, but its not getting saved.
`<script async src="https://www.googletagmanager.com/gtag/js"></script>`

**Comment by abnerlee** [comment]
How to reproduce this?

**Comment by ksurya** [comment]
Typora Version 0.9.9.17

1. Open a markdown file with Monospace Dark theme
2. Add the below snippet (not as a code snippet)
3. Save the file
4. Reopen the file, the first line in the snippet will be missing

```
<script async src="https://www.googletagmanager.com/gtag/js"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-xxx-x');
</script>
```

**Comment by abnerlee** [comment]
Please check new updates
