### ISSUE TITLE
Problem with symbol '&' in reference-style links

### ISSUE THREAD

**Issue by tswwe** [typora/typora-issues#1692]
According to the [document of Typora](https://support.typora.io/Markdown-Reference/), you can create a reference-style link in Typora just like this:
```
This is [an example][id] reference-style link.
[id]: http://example.com/pages?id=1&no=1  "Optional Title Here"
```
However, if the url in the [id] line contains symbol '&' like it is shown in the example above, there comes a problem that can be triggered by this step: Move your cursor onto other line and left click, then move it back to the [id] line and left click. You can find the url of [id] line changed after this step:
```
[id]: http://example.com/pages?id=1&amp;no=1  "Optional Title Here"
```
And if you repeat the step and keep changing your focus between lines, you may finally get this:
```
[id]: http://example.com/pages?id=1&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;no=1  "Optional Title Here"
```
The problem doesn't exist in a inline-style link, but I do hope it can be fixed because sometimes reference-style links are useful.

**Comment by abnerlee** [comment]
Please check new updates

**Comment by tswwe** [comment]
Thank you. Now everything goes well.
