### ISSUE TITLE
pasting HTML bad

### ISSUE THREAD

**Issue by ShixiangWang** [typora/typora-issues#1693]
I use the newest version of typora.

When I copy content of <https://www.shixiangwang.top/post/high-level-oop-two/> to typora. The code block render badly.

![image](https://user-images.githubusercontent.com/25057508/44323066-de795f00-a482-11e8-83fd-5df90a8045cc.png)

![image](https://user-images.githubusercontent.com/25057508/44323068-dfaa8c00-a482-11e8-9e7f-730fb5ffcb1a.png)

all code blocks have the problem.

![image](https://user-images.githubusercontent.com/25057508/44323100-010b7800-a483-11e8-9588-3e9fe676076c.png)

multiple line code become one line. How should I fix it?

**Comment by vassudanagunta** [comment]
I get these weird cut and paste problems a lot, and usually they are solved by using `Edit:Paste as Plain Text`. Maybe Typora should be smarter, or maybe it can't. But in any case, the user can try both forms of paste to see what works.

**Comment by abnerlee** [comment]
Please check new updates
