### ISSUE TITLE
Shortcut for images is unavailable

### ISSUE THREAD

**Issue by Roger-WIN** [typora/typora-issues#1694]
Unable to use the shortcut "Ctrl+Shift+I" to insert images. Instead, it will open the Developer Tool of Chromium.
![typora_2018-08-20_14-36-13](https://user-images.githubusercontent.com/25821208/44323919-6f056e80-a486-11e8-90c0-26a61e4f6abc.png)
Inserting images from the context menu works well.

Version: Typora 0.9.54 for Windows.
This bug does not exist in the previous version.

**Comment by abnerlee** [comment]
Please check new updates
