### ISSUE TITLE
Typora is Great!

### ISSUE THREAD

**Issue by noio** [typora/typora-issues#1697]
This might not be the perfect channel for this, but I just wanted to let you know how much I enjoy using Typora. Such a simple tool has improved the way I work by so much. I used to keep notebooks and todo list on different online platforms, moving around whenever a new "feature of the day" was announced and losing my old stuff to vendor lock-in. Now, I keep to do lists and logs together in a single file that's pleasant to edit. I discovered that a simple nested to do list is all I need. Typora's attractive styling makes it fun to leave daily log entries and to browse through them, and I have faith I will be able to do so for the foreseable future, because they're written in an open format that is just stored on my disk. 

Please keep up the great work, I can't wait to start paying for this software.

🙏

**Comment by alidhillon** [comment]
I just love typora.
