### ISSUE TITLE
Changes to files in iCloud are not preserved

### ISSUE THREAD

**Issue by ksurya** [typora/typora-issues#1698]
I have all markdown files in iCloud Drive that I open with Typora. Let's say there is a 10KB markdown file to which some changes were made. If I moved to another file for writing and return the former one, I notice the latest changes in the former are not preserved.

Let's say there is a file `hello.md`. Sometimes I notice `~hello.md` in the tree while saving `hello.md`. 

I guess changes meant to persist are lost while icloud syncs. I don't know a good way to keep my markdown files in sync and use Typora. It surely is frustrating to rewrite lost changes all the time.

**Comment by abnerlee** [comment]
How to reproduce this?

>  If I moved to another file for writing and return the former one

Do you mean open new files using Typora, and then switch back to the original Typora window?
