### ISSUE TITLE
Titlebar render darken when open multiple tabs

### ISSUE THREAD

**Issue by viko16** [typora/typora-issues#1699]
![4](https://user-images.githubusercontent.com/5064777/44378390-a4b46100-a533-11e8-9ec7-46c5639a9e6c.gif)

- System: macOS 10.13.6
- Typora Version:  0.9.9.17
- Theme: [Scribble](https://theme.typora.io/theme/Scribble/)

When i open multiple tabs, the macOS titlebar and tabs turn darken. Is it any render bug ?

Default theme is ok, it reappears under the scribble theme.

**Comment by abnerlee** [comment]
Please check new updates
