### ISSUE TITLE
enable paste image from clipboard

### ISSUE THREAD

**Issue by thinker007** [typora/typora-issues#17]
support paste image from clipboard

**Comment by kadmonj** [comment]
+1 for that!

**Comment by yetty** [comment]
+1 

This is a reason why I am still stuck on OneNote.

**Comment by pitibalrog** [comment]
+1 
I'm used to this functionnality in Zim and hope have it on Typora soon

**Comment by zhenglaizhang** [comment]
+1
This will definitely be one killer feature among the markdown editors

**Comment by smallx** [comment]
+1
I like. In fact, there are two case:
- the clipboard contains the path of image file
- the clipboard contains the content of image

**Comment by sinakes** [comment]
+1

**Comment by abnerlee** [comment]
see http://support.typora.io/Images/
