### ISSUE TITLE
Critical bug: content loss

### ISSUE THREAD

**Issue by smallx** [typora/typora-issues#170]
I am very sad to say that Typora has a **critical bug** which can lead to content loss.

When I was writing, I found the "Outline" displayed incorrectly suddenly. So, I close the file and then open it. However, I found something lost. I am very sad :-(

Here is some information: **version 0.9.5 for Windows**.

**Comment by abnerlee** [comment]
Any chance to reproduce the bug?
or what operations did you involves? like make lists, copy/paste, anything is OK.

**Comment by smallx** [comment]
I have found history writing in "draftsRecover" folder. But I also think it is a bug, because all content is saved before closing file.

**Comment by smallx** [comment]
I'm not sure what caused it. Perhaps copy/paste, toggle to markdown source code, "Ctrl+B" to strong text, "Ctrl+Z".
I am sorry for my bad English.

**Comment by leewi9** [comment]
To be frank I've experienced this a few times, seems happen when cut/paste.

Now I put a word 'END' at the end of the file to be a flag, when it's there I know this is no problem, when it disappears I know something bad happens.


2016年5月25日 +0800 23:59 smallx<notifications@github.com>，写道：

**Comment by abnerlee** [comment]
Thanks, to narrow down the problem. What kind of block does the cut/paste involves? like cut form list, paste to blockquote, etc.. Or nay more info is welcomed

**Comment by abnerlee** [comment]
Thanks, I can reproduce it now, It is a critical bug so I'll fix this asap

**Comment by smallx** [comment]
Thanks very much. I want to know what caused it?

Fix it and Typora is better :-) :100:

**Comment by abnerlee** [comment]
I can reproduce it by selecting two paragraph, press ctrl+x and then paste into a middle of another paragraph, then press undo, then press redo...

**Comment by smallx** [comment]
:+1: :+1: :+1:

**Comment by smallx** [comment]
The key to the problem is to paste multiple paragraphs into one paragraph and then undo. Has nothing to do with copy or cut, and has nothing to do with the middle or the end of the paragraph.

**Comment by abnerlee** [comment]
@smallx, Yes, it's a bug in generating undo command when do pasting.

**Comment by abnerlee** [comment]
Fixed in new version
