### ISSUE TITLE
Cursor auto jump to the top when typing Command + s in macOS Sierra with Typora 0.9.9.17

### ISSUE THREAD

**Issue by houluy** [typora/typora-issues#1701]
I just updated Typora to  0.9.9.17 on my mac and I found something strange. When I hit the command+s to save the file, **if the cursor is inside a code block**, it will jump to the very start of the file. I think this might be a small bug but really annoying.

Reproduce:

1. Typora 0.9.9.17 on macOS;
2. Insert anything as the title;
3. Typing ```python and ENTER to enter the code block;
4. Write some code, and press Command+s to save;
5. The cursor will run to the start position of this file.

**Comment by abnerlee** [comment]
Please check new updates
