### ISSUE TITLE
Redo shortcut changed, broke menu item

### ISSUE THREAD

**Issue by jameskirkwood** [typora/typora-issues#1702]
Current version: 0.9.9.17 (0.9.54)

Redo has changed to Cmd+Y in a recent update. The redo menu item still indicates the shortcut Cmd+Shift+Z, but is permanently disabled (grey), so without knowledge of Cmd+Y (which is not idiomatic for macOS), it would appear that it is impossible to perform the action.

The correct shortcut is Cmd+Shift+Z.

**Comment by abnerlee** [comment]
Please check new updates
