### ISSUE TITLE
Cannot close the Typewriter Mode.

### ISSUE THREAD

**Issue by qlngy** [typora/typora-issues#1706]
The checkbox of Typewriter Mode just cannot uncheck. I dont know why.
When I re-open the setting, it was automatically checked.

**Comment by qlngy** [comment]
https://github.com/typora/typora-issues/issues/1706#issuecomment-414984811
Yeah.Could you teach me any trick to disable this mode? So annoying.

**Comment by qlngy** [comment]
Yeah. Could you teach me some trick to disable this? So annoying. Thanks.

**Comment by abnerlee** [comment]
The new update should have fixed this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qlngy** [comment]
Allright. I re-installed and that bug seemed fixed.
