### ISSUE TITLE
Relative links to directories

### ISSUE THREAD

**Issue by krystophny** [typora/typora-issues#1708]
According to the closed issues #1592 and #1596 links to files and directories work now. What is however not working are **relative** links to directories, e.g. on Linux 0.9.55 beta

`[Link](path/to/dir/)`

gives an error message 

> Cannot open location /full/path/to/dir, do you mean https://path/do/dir/ ? Learn More… 

However

`[Link](/full/path/to/dir/)`

is working without problems.

**Comment by abnerlee** [comment]
Should be fixed in new release
