### ISSUE TITLE
Issue #1649 closed but not fixed in 0.9.56

### ISSUE THREAD

**Issue by dooof** [typora/typora-issues#1709]
I tested Issue [#1649](https://github.com/typora/typora-issues/issues/1649) with version 0.9.56 on Win 10 and the problem is still not fixed.

**Comment by dooof** [comment]
I did some more experimentation.  Looks like the issue has improved, however there are cases where it still occurs.  It looks like if I PageDown/PageUp and the image is at the very top of the screen (partially scrolled off and partially visible) then the caret doesn't adjust (even if I continue to PageDown).

**Comment by abnerlee** [comment]
reopened #1649
