### ISSUE TITLE
After installing beta 0.9.6, Windows reports malware

### ISSUE THREAD

**Issue by somelinguist** [typora/typora-issues#171]
I just installed version 0.9.6, and Windows started reporting it had found malware during the install as well as after. I hadn't seen this using version 0.9.5 or before. All downloaded from the link at http://www.typora.io/#windows

Here is the it reported:

Detected item: Trojan:Win32/Gatrid.E!cl
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:E:\Downloads\typora-setup.exe
file:C:\Program Files (x86)\Typora\bin\typora.exe
file:C:\Program Files (x86)\Typora\bin\is-2B8V7.tmp

**Comment by smallx** [comment]
It's no problem in my favourite Windows 8 64bit(Chinese version). 😃

**Comment by abnerlee** [comment]
@somelinguist which windows version could report this ?

**Comment by abnerlee** [comment]
@somelinguist btw, could you try download from the `https` link? 
<https://www.typora.io/#windows>

**Comment by smallx** [comment]
@abnerlee Why I can't download the **latest** version in https://www.typora.io/#windows or http://www.typora.io/#windows ?

**Comment by abnerlee** [comment]
@smallx so you mean you install Typora 0.9.6 from auto update (<https://www.typora.io/windows/typora-update0527.exe>), but windows reports some file from typora are malware?

And which windows version/anti-virus software did you use ?

**Comment by smallx** [comment]
@abnerlee I do not have this problem. Just is @somelinguist , not me. :smiley:

**Comment by abnerlee** [comment]
The misreport may be caused by runtime unpack. This is fixed in v0.9.7

**Comment by somelinguist** [comment]
Sorry, didn't see the request for more info until this morning. Thanks for the fix!

**Comment by smallx** [comment]
Haha, I will go to bed. Good morning to you, good night to me.

**Comment by abnerlee** [comment]
For solid reference: https://analysis.avira.com/en/status?uniqueid=NTVxcJfDFXNGOMI4r4y9QQfZ5PkQ67LN&incidentid=2044019
