### ISSUE TITLE
Exporting PDF, 'ghost' table, Academic Theme

### ISSUE THREAD

**Issue by Lewih** [typora/typora-issues#1710]
Hi Pals! 
I have an issue in exporting a pdf with Academic Theme: I get a different result than expected.
Other themes work smoothly.
I use Italian template keyboard.
System: Mac OS High Sierra 10.13.6
Typora: Latest 0.9.9.17.4

While editing in Typora:
<img width="608" alt="schermata 2018-08-22 alle 18 38 37" src="https://user-images.githubusercontent.com/37453252/44477416-dfed8780-a63a-11e8-8344-e59a08149c94.png">

PDF exported file:
<img width="432" alt="schermata 2018-08-22 alle 18 39 53" src="https://user-images.githubusercontent.com/37453252/44477417-e4b23b80-a63a-11e8-8a03-0e01fcfb0078.png">

**Comment by abnerlee** [comment]
this is a bug of the academic theme. I updated the theme, please redownload it theme css.
