### ISSUE TITLE
issue when export to image

### ISSUE THREAD

**Issue by AntonyLee** [typora/typora-issues#1712]
version: 0.9.56(beta)
issue: when export md to image, typora always shows exporting but no files export to dest folder.
![image](https://user-images.githubusercontent.com/1336185/44504208-0f4cd480-a6cd-11e8-9171-47b5b4d640ca.png)

**Comment by AntonyLee** [comment]
when i export different docs or using different theme, it's the same

**Comment by abnerlee** [comment]
Exporting image may cost much time (depends on your file content/size), could you wait for some time and see if the toaster will disappear after export finished

**Comment by AntonyLee** [comment]
I tried wait for 1hr and still showing the same toaster.
And the test doc only has several characters, the size won't be the problem.

And I also tried install this version on a new computer, then I met the same problem.

I love typora and exporting to image feature is very useful on mobile phone. 
Thanks for you response

**Comment by abnerlee** [comment]
Fixed in 0.9.57
