### ISSUE TITLE
Fail to open markdown file with blank space in file path.

### ISSUE THREAD

**Issue by amitbha** [typora/typora-issues#1713]
System: Archlinux
Typora: 0.9.54 (beta)

Fail to load file when there is blank space in file path.
![fs-18-08-23 13 05](https://user-images.githubusercontent.com/4060625/44505757-af0e6080-a6d5-11e8-86c3-10a8a9cff73e.png)

**Comment by abnerlee** [comment]
How did you open the file? Double click or launch from Terminal?

**Comment by abnerlee** [comment]
The exception is throw from fs module. Could you send us (<hi@typora.io>) the log following https://support.typora.io/Report-Bugs#logs

Does the file exists at the given path?

**Comment by amitbha** [comment]
> INFO 2018/8/26 7:43:31  ------------------start------------------
INFO 2018/8/26 7:43:31  typora version: 0.9.56
INFO 2018/8/26 7:43:31  addRecentDocument
INFO 2018/8/26 7:43:37  ------------------quit------------------

The file can be opened with other editor, and older version of typora.

**Comment by abnerlee** [comment]
@amitbha Could you open the file successfully from terminal using "typora /tmp/download/WeChat Files/Files/index.md" ?
And how about "vi /tmp/download/WeChat Files/Files/index.md"?

**Comment by amitbha** [comment]
I've updated typora from 0.9.54 (beta) to 0.9.56 (beta), the problem is gone.
Thank you very much!
