### ISSUE TITLE
class diagram by mermaid cannot be rendered properly

### ISSUE THREAD

**Issue by hitzhangjie** [typora/typora-issues#1714]
Please look the screenshot below:

![image](https://user-images.githubusercontent.com/3725760/44507770-64ddad00-a6de-11e8-96b3-b46807bb09b8.png)

**Comment by hitzhangjie** [comment]
can we support plantuml, it's powrerful and stable.

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/803

about plantuml, see https://github.com/typora/typora-issues/issues/1138
