### ISSUE TITLE
typora-setup-x64.exe is blocked by Windows Defender SmartScreen on Windows 10 Pro 1803

### ISSUE THREAD

**Issue by 517qf** [typora/typora-issues#1715]
I get a screen that reads "Windows proteced your PC. Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk." and there is only a button "Don't run".

I know that as an author you can't control how anti virus classifies your app. But maybe there are some steps/modifications you can do to avoid such a scarry warning which stops people like me from using it. My idea is "better save than sorry" even though I know that I can check how other AV rate your app on virustotal.

I can install other programs from unknown authors without problems. 

I refer to the version with this sha256sum: 90B419C9C23F7A21AC2AEAD30DFEDEE0C772454D0287E99BA3254F3B8738E4AE

**Comment by abnerlee** [comment]
Downloading from our website and using https would ensure the *.exe is built from us, so sha256sum checked is optional.

---

I think the SmartScreen will show if the .exe are downloaded from web. 

Buying a "Standard Code Signing Certificate" recognized by Microsoft may avoid this (which also depends on users setting). 

But we cannot do that in short term, but signing with a trusted cert is planned in future.

**Comment by zwep** [comment]
I want to vote for a re-open. I have just tried to download it from the website and run it... still gets blocked. Using Windows 10 and https via Firefox browser

**Comment by abnerlee** [comment]
it is duplicate with #1801
