### ISSUE TITLE
Buttons in Preferences do not work

### ISSUE THREAD

**Issue by dixonge** [typora/typora-issues#1717]
Kubuntu 18.04 (snap install)
Typora 0.9.44(beta)

In File > Preference only one of the four buttons works, mostly:

1. Open Theme Folder - does nothing
2. Recover Unsaved Drafts - does nothing
3. Open Advanced Settings - does nothing
4. Reset Advanced Settings - produces a 'confirm' box - if you press OK the box disappears and you are back in the main editor window. The preference pane is gone.

**Comment by abnerlee** [comment]
Have you try `apt-install` typora? I cannot reproduce this, so it may caused by the unofficial snap install.

**Comment by abnerlee** [comment]
And could you find & send us (<hi@typora.io>) Typora.log under `~/.config/Typora` ?

**Comment by dixonge** [comment]
apt-install updates me to version 0.9.56(beta) - and the menu fonts are all normal now! The preference buttons all open the file manager which is the expected behavior. I don't think this was an issue with snap sandboxing as I was having the same issue when installed in --classic mode, so I guess it was the older version or just something missing in the unofficial snap package. There was nothing on Snapcraft to indicate that this was an unofficial version...

I uninstalled the snap package before seeing your request for the log. If the log was there, it is gone now.
