### ISSUE TITLE
Getting slow and too bulky?

### ISSUE THREAD

**Issue by royfrancis** [typora/typora-issues#1719]
Typora is an amazing markdown editor and my favourite so far. But lately I feel like it's turning into a massive software. It takes several minutes to open and there is an update almost every frikking day! Photoshop seems to open in the same time as Typora. Lately, I have started to use SublimeText when I need to quickly open a markdown file. And it is open and ready in a fraction of the time taken by Typora. I feel like typora also seems to be using a lot more resources than a text editor should. 

I am not sure what is being added to it all the time, but I think you should probably have a light, fast and responsive **TyporaLite** edition. Is it just me or does anyone else experience this?

Running 0.9.56 on Windows 10.

**Comment by AlexPasternak** [comment]
This might be environmental. I have no slow startup issues, even when resuming working on a previous MD document. The comparison with something like Photoshop seems particularly bizarre.

Yes, there have been several updates over the past weeks, but they've been to fix bugs, so I'm not really going to complain. I think they're 10MB downloads every time? Which is pretty much a drop in the bucket.

**Comment by amitbha** [comment]
Maybe a quick-view mode is suitable, when a edit-mode is fully featured.

**Comment by DutchPete** [comment]
I agree with @royfrancis entirely.

**Comment by abnerlee** [comment]
duplicate with other issues about performance

**Comment by crjase** [comment]
not gonna lie, it takes a bit of time to open when I want to quickly edit something. I'd be good if there was a quick-view mode where I can just open it as fast as window's default notepad and start writing some notes.

**Comment by EganSolo** [comment]
I'm editing a file that is now 128kb. That's right kbs. Yet if feels as if I'm editing a file that is 128Megs. Typora moves with fits and starts. While typing, it freezes for several seconds. It's no longer enjoyable.

Found a temporary fix: Run Typora as administrator seems to fix the slowness but I'm not sure why.
