### ISSUE TITLE
Bugs relates to Chinese IME

### ISSUE THREAD

**Issue by smallx** [typora/typora-issues#172]
Hello, I find a small bug in rendering **inline** styles. This bug does not appear in English, but will appear in Chinese (maybe there are other languages). Chinese is usually a word followed by a word, there is no space between the middle. Bug as shown below (**not only** inline code block):

![default](https://cloud.githubusercontent.com/assets/16517035/15628375/e699f56e-2531-11e6-9b14-b3fa1a06f6ce.gif)

There is no problem in English (spaces have been removed):
![default](https://cloud.githubusercontent.com/assets/16517035/15628372/d9a0de36-2531-11e6-9b4b-da2f1bd16bd2.gif)

**To solve it**, I think inline-block should be rendered immediately whenever it loses focus.

Here is the information:
**Typora 0.9.6 for Windows**.

Here is the test data:

```
`Typora`是一个`Markdown`编辑器，我喜欢它。
`Typora`IsA`Markdown`EditorAndILikeIt.
```

Thanks!

**Comment by abnerlee** [comment]
Hi:

It seems working with Windows7 and Bing IME, so would you tell me your windows version and which Chinese IME (its official website) you use ?

**Comment by smallx** [comment]
- windows 8 64bit
- 百度输入法(Baidu IME): http://shurufa.baidu.com/

**Comment by smallx** [comment]
I will test it using Bing IME later. Thanks.

**Comment by smallx** [comment]
Yes, Bing IME **works well**. In addition,  if I paste "编辑器" after `Markdown`, it also **works well**. And then, I test it using the following IME:

- 搜狗输入法(Sougou IME, http://pinyin.sogou.com/): **works well**
- QQ输入法(QQ IME, http://qq.pinyin.cn/): **works well**

So, it may be the problem of Baidu IME, not Typora.

**Comment by smallx** [comment]
I have feedback this problem to Baidu IME developers.

Close it now?

**Comment by smallx** [comment]
It is similar to #154 . I realized it was really bug.

For the following text:
```
`Typora`是一个`Markdown`我喜欢它。
```

When I input `。` after `\`Markdown\`` using Microsoft Chinese IME, above problem appears.

Sorry, I think you can re open this issue or #154 .

**Comment by UnnamedOrange** [comment]
Unfortunately, this problem happens on my computer with [Sogou IME](https://pinyin.sogou.com/) as well.
Windows 10 1709(16299.214)

**Comment by poerin** [comment]
This problem also occurred when I use QQ IME. Will it be related to the character set?

**Comment by abnerlee** [comment]
Fixed in new release
