### ISSUE TITLE
Three hotkeys are invalid

### ISSUE THREAD

**Issue by Zeroto521** [typora/typora-issues#1720]
1. Ctrl + J
    > invalid

2. Ctrl + -/=
    > Only useful to no word heading. When use this hotkey to make heading with words, that heading level just become 6.

3. Ctrl + Shift + 0
    > invalid

**Comment by abnerlee** [comment]
What's your Operation System?

It seems OK in my test (win 10)

**Comment by Zeroto521** [comment]
> win10 1803
1. Ctrl + J
![j](https://user-images.githubusercontent.com/25895405/44563020-e1c85f80-a78e-11e8-844d-42fca954edda.gif)
2. Ctrl + -/=
![-](https://user-images.githubusercontent.com/25895405/44563023-eb51c780-a78e-11e8-8f05-8c15237fa914.gif)

**Comment by abnerlee** [comment]
Fixed 

`Ctrl + -/=` and `Ctrl + Shift + 0` in 0.9.57

`ctrl+J` will ensure the caret is in visible area, or else scroll to the caret position. So from your screencast, ctrl+j is working
