### ISSUE TITLE
Exoprt Doc Not Work

### ISSUE THREAD

**Issue by wxitcode** [typora/typora-issues#1721]
I have used the export function before.

Typora version: **0.9.9.17.4**
Operating System: **macOS High Sierra 10.13.6**
Pandoc version: **2.2.3.2** (install with `brew install pandoc`)

I had try reinstall pandoc, but just not work.
Typora can't find pandoc, or other reasons?

<center>
<img src="https://user-images.githubusercontent.com/37947163/44566789-0548d580-a7a2-11e8-974b-b62cfee983f5.png" width="50%" />
</center>

**Comment by abnerlee** [comment]
Please try on v0.9.9.17.5

**Comment by wxitcode** [comment]
I just tried it on v0.9.9.17.5, but still can't work. Still prompted "Require Pandoc to Continue...". The console output is below.

![image](https://user-images.githubusercontent.com/37947163/44954785-ac341c80-aeda-11e8-905f-463cd5af8353.png)

**Comment by abnerlee** [comment]
What's your system local/language?

Does your terminal use UTF-8 encode or something else?

**Comment by wxitcode** [comment]
English
``` bash
➜  ~ echo $LANG
en_US.UTF-8
```

**Comment by wxitcode** [comment]
United States  English 
``` bash
➜  ~ echo $LANG
en_US.UTF-8
```

**Comment by wxitcode** [comment]
It works on Version 0.9.9.19.1 (1301).

**Comment by abnerlee** [comment]
relates #1386
