### ISSUE TITLE
Feature request: fix width of Files/Outline pane

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#1722]
It would be useful to be able to set the width of the files/outline pane, AND leave it fixed at the set width. Right now, after fixing the width maually, when Typora is closed and reopened, the width is back to default.

Ideally I would like to set the width on a per file basis.

**Comment by abnerlee** [comment]
Sounds like a bug, what's your Typora/OS version ?

**Comment by DutchPete** [comment]
Abner, any idea if it is a bug or if it would need to be a new feature?

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by DutchPete** [comment]
Thanks Abner :+1:
