### ISSUE TITLE
The problem about copying a formula

### ISSUE THREAD

**Issue by BalanceUhen** [typora/typora-issues#1723]
Once I use the `copy to MS Wrod` option,like the image below,
![image](https://user-images.githubusercontent.com/21274779/44585875-537cc980-a7e0-11e8-96a2-a5a1d7bd60c2.png)
I got
![image](https://user-images.githubusercontent.com/21274779/44585951-96d73800-a7e0-11e8-90b5-5dc3e12ec9eb.png)
When I use the `copy as MathML` option,I *also* got
![image](https://user-images.githubusercontent.com/21274779/44585996-c1c18c00-a7e0-11e8-8c0c-14486be9123c.png)
What is the difference between the two options?

**Comment by abnerlee** [comment]
This is a bug.

In 0.9.57, `copy into MS Word` can work
