### ISSUE TITLE
Incorrect titlebar text color when --bg-color is black

### ISSUE THREAD

**Issue by madebyollin** [typora/typora-issues#1726]
**Version:** 
* Typora 0.9.9.17.4 (0.9.9.17.4) 
* macOS High Sierra 10.13.6

**Steps to Reproduce:**

0. Make sure the window style is set to Seamless in Typora > Preferences
1. Open the default Night Theme's `night.css` (as an example)
2. Change `--bg-color:  #363B40;` to `--bg-color:  #000000;` in `:root`.
3. Switch to the Night Theme and watch the titlebar / filename text disappear.

**Expected:** text color for filename in titlebar should be white.
**Actual:** text color is black (and therefore unreadable).
**Cause:** The problem occurs with `--bg-color:  #000000;` but _not_ with `--bg-color:  #000001;`. This suggests that the bug could be caused by interpreting a black `bg-color` as falsy/unset. I suspect this is a recent regression, since I've been using a pure-black `bg-color` for several versions now and hadn't observed the problem until this week.

**Screenshots:**
<img width="587" alt="screen shot 2018-08-25 at 12 20 30" src="https://user-images.githubusercontent.com/8733615/44621786-65528100-a861-11e8-9c6a-e18ad958505f.png">
<img width="587" alt="screen shot 2018-08-25 at 12 21 14" src="https://user-images.githubusercontent.com/8733615/44621785-65528100-a861-11e8-8f5c-705df1f4f9bb.png">

**Comment by abnerlee** [comment]
Fixed in new release
