### ISSUE TITLE
perference > markdown > syntax perf > ordered list (cant figure out, tell the diff between the two options 1.2.3 1.1.1)

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#1727]
perference > markdown > syntax perf > ordered list 

(cant figure out, tell the diff between the two options 

- 1.2.3 
- 1.1.1

tried googling etc etc etc

if it's not very helpful useful, just remove

it's very confusing

'pretty indentation' also is very unclear but figured it out eventually

---

in pref, settings, there should be a 'horizontional line' before each major section like 'markdown'

here's the settings changes made upon fresh re-isntall: (**they should be default**)

view > zoom out 1x

hide status bar

no collapsible outline cos it opens with sections hidden

syntax sup > highlight on

strict mode off (needs restart, paper uses this)

smart coverts on

convert on input = immediate (in source code)

whitespace line breaks > print export > preserve

auto pair off (for dates like '18)

ctrl c > do not copy md source

no pretty indent

on launch > restore last closed files & folders

save recover > auto save

**Comment by abnerlee** [comment]
Both 
```
1. 
2. 
3.
```
and
```
1. 
1. 
1. 
```
will be rendered as 
```
1. 
2.
3.
```
in markdown.

This setting is to tell Typora whether to generate Markdown source code for order listed using pattern "1. 2. 3" or using "1. 1. 2".

---

Options are designed to be configured by users. We are not going to change their default value

**Comment by SolveAllProblemsRightNow** [comment]
using 

"1. 2. 3" 

or

"1. 1. 2".

if it looks the end in the end, what diff does it make?

if it makes a significant diff to the end user, then this could be made clearer in the prefs

liek the other things mentioned
