### ISSUE TITLE
highlighting multiple lines of text, then pressing 'tab', doesnt indent like with every single other software/app out there (single biggest thing i've been hating)

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#1728]
highlighting multiple lines of text

doesnt indent 

like with every single other software/app out there 

(single biggest thing i've been hating)

**Comment by abnerlee** [comment]
Indent by tab is available for lists.

In markdown, indent will convert plain text to code blocks, which seems unusual that pressing Tab will change text styles.

**Comment by SolveAllProblemsRightNow** [comment]
so markdown problem, that's terrible, no way to fix?
