### ISSUE TITLE
Link to a file on Q-drive: can be closed - see reasons given

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#1731]
I have a folder that contains the file consists of 3 separate words (e.g. word1 word2 word3), as does the name of the file with the extension .pdf, and is located on a Veracrypt drive,  the Q-drive in my case. 

What is the syntax to make a link to that file? Of course the drive needs to be mounted for the link to work, but what is the link syntax?

**Comment by DutchPete** [comment]
This issue can be closed. The reason I raised it is because, I believe, there is an error here, [Link to local files](https://support.typora.io/Links/), where it says [Readme4](file:///User/root/Docs/Readme1.md).
I followed your instructions but they did not work. Experimenting a bit a established where the error was.

The bit file:/// is wrong, the whole syntax should read [Readme4](drive:\path to filename.extension)
Note:
1. file: is replaced by drive:
2. the drive can be a real drive or a mounted virtual drive
3. there are no forward slashes only back-slashes
4. there are not 3 slashes
5. the path can be to any extension type, not just to md extensions.

If you agree please alter the webpage.

**Comment by abnerlee** [comment]
There's no `drive:` on macOS/Linux, so Readme4 is valid on those OS. Readme4 are about using "absolute path", on some os, the "drive:" is included in "absolute path"

**Comment by DutchPete** [comment]
OK, then it would be useful to make that clear on your webpage.

**Comment by abnerlee** [comment]
Yes, we could add such examples
