### ISSUE TITLE
Multi-level Lists: numbered lists mess up, text vanish.

### ISSUE THREAD

**Issue by sicilian-lizard** [typora/typora-issues#1734]
When I work with a multi-list (around 180 top-level (most with url links), 4-7 sub-level), ordering becomes a mess: empty lines I can't delete, lines I can't delete, list lines I didn't create, and large chunk of text just vanished when I hit the delete key to delete one letter, twice!

Just create a multi-level list, select all and copy and paste it in some other text editor, one can see the list is not the same.

**Comment by abnerlee** [comment]
@sicilian-lizard What's your Typora/OS version?

Possible to send us the sample *.md file? (<hi@typora.io>)

**Comment by sicilian-lizard** [comment]
Sent. Thanks!

**Comment by sicilian-lizard** [comment]
I always use the latest version. Both Typora and macOS.

**Comment by sicilian-lizard** [comment]
In Version 0.9.9.17.5 (0.9.9.17.5), when I hit Return to produce another sublist item, it still give me empty lines I can't delete, and when copy and paste in other app, the pasted is different from the selected an copied text in Typora. Also, the list looks weird when the .md file is opened in a text editor.

On macOS High Sierra.

**Comment by abnerlee** [comment]
which Chinese IME do you use?
