### ISSUE TITLE
segmentation fault on Ubuntu 18.10 'proposed'

### ISSUE THREAD

**Issue by cgoise** [typora/typora-issues#1735]
Hi,

in Ubuntu 18.10 (the 'proposed' repo enabled) typora segfaults on start since a few days.

There is no further information, because Typora crashes even before it writes to ~/.config/Typora/typora.log. The only output is 'Segmentation fault' on the command line.

Other electron apps are not affected. It might be worthwhile to look into this issue.

**Comment by abnerlee** [comment]
Were you using glibc 2.28 (same issue as https://github.com/electron/electron/issues/13972) ?

**Comment by cgoise** [comment]
Indeed, I'm using glibc 2.28, so its the same issue.
