### ISSUE TITLE
Links are broken in latest release

### ISSUE THREAD

**Issue by allohakdan** [typora/typora-issues#1737]
Links seem to be broken in the latest release. 

Previously, given the example below
```
[new issue](https://github.com/typora/typora-issues/issues/new)
```
I could right click on the works "new issue", select "open link", and the link would open in my browser. In the same way, I could open another markdown file using the example below
```
[notes](/Volumes/mydisk/mynotes.md)
```

This worked in the last version of Typora, but seem not to work now in 0.9.9.17.4. I'm using OSX Sierra (10.12.6).

**Comment by abnerlee** [comment]
Fixed in new release
