### ISSUE TITLE
Latex inline fraction don't render.

### ISSUE THREAD

**Issue by douglasprodocimo** [typora/typora-issues#1738]
In line math e.g $ a = 2b $ don't renders after creation, but render after editing a math block $$ .. $$ on the same document.

to reproduce bug:
1 - create new file.
2 - add inline math e.g. $ a + b = c $
3 - add math block e.g.
$$
a * b = d
$$
4. click out of the math block to render both maths.

**Comment by abnerlee** [comment]
Please enable inline math from preferences panel.

**Comment by abnerlee** [comment]
#1507

**Comment by abnerlee** [comment]
#1662

**Comment by abnerlee** [comment]
#1510
#1506
