### ISSUE TITLE
image align doesn't work after upgrade to laest version

### ISSUE THREAD

**Issue by jacquen** [typora/typora-issues#1739]
Hi, Support

I added image align code in user define CSS template, it works before, but after I upgrade to latest version, seems it stop working, any idea? Thanks

 I use win7 and Typora version is 0.9.56

CSS code:
*********************************************
.md-line .md-image:only-child{
    text-align: inherit;
}

**Comment by abnerlee** [comment]
use 
```
p .md-image:only-child{
text-align: inherit;
}
```
