### ISSUE TITLE
Toggling between Files view & Outline view - a bug?

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#1741]
I use CTRL+Shift+1 and CTRL+Shift+3 to toggle between the 2 views. When I start in File 1 with the Outline view in the left panel, then toggle to the the Files view, select another file (File 2), toggle to the Outline view, then toggle back to the Files view (still in File 2), select File 1, toggle to the Outline view, the latter states the the view is empty.

When I close Typora, then reopen it with File 1, then the Outline is there as before.

**Comment by abnerlee** [comment]
Should be fixed in 0.9.57
