### ISSUE TITLE
Image URL not parsed correctly

### ISSUE THREAD

**Issue by FlandiaYingman** [typora/typora-issues#1746]
I'm using a image from a website URL, the URL is `http://latex.codecogs.com/png.latex? x^{n}= \begin{cases} x(x^{2})^{\frac{n-1}{2}}, & \mbox{if } n \mbox{ is odd.}\\ (x^{2})^{\frac{n}{2}}, & \mbox{if } n \mbox{ is even.}\\ \end{cases}`, and the correct image should be like ![png](https://user-images.githubusercontent.com/9929037/44841597-53fce080-ac76-11e8-88c2-5e3965d99dea.png) that. But Typora shows it like ![30-08-2018 17-02-32](https://user-images.githubusercontent.com/9929037/44841692-8b6b8d00-ac76-11e8-93bc-d5fbcc91145b.png), it may changes all `\` into `/`.

**Comment by FlandiaYingman** [comment]
@abnerlee 
I don't know whether or not this image is a valid markdown image, but it still cannot shows correctly with the <img> tag, and when I exported the markdown document into a html document, it shows correctly

**Comment by abnerlee** [comment]
So how you write in Typora?

using <img src="http://latex.codecogs.com/png.latex? x^{n}= \begin{cases} x(x^{2})^{\frac{n-1}{2}}, & \mbox{if } n \mbox{ is odd.}\\ (x^{2})^{\frac{n}{2}}, & \mbox{if } n \mbox{ is even.}\\ \end{cases}" /> or something else ?

**Comment by FlandiaYingman** [comment]
@abnerlee Exactly, I'm using just like you said.

**Comment by abnerlee** [comment]
Fixed in new release
