### ISSUE TITLE
Source Code Mode weird presentation of combined bold & italics

### ISSUE THREAD

**Issue by hvdijk** [typora/typora-issues#1747]
Typora 0.9.56 on Windows.

When Source Code Mode is enabled, when text is marked both bold and italics (`***test***`), the display of the asterisks indicates that this is interpreted as

<pre>
***test***
^^         start bold
  ^        start italics
       ^^  end bold
         ^ end italics
</pre>

This just looks weird. Asterisks 1-5 are displayed in bold, asterisks 3-6 are displayed in italics, to give <b>\*\*<i>\*test\*\*</i></b><i>\*</i>. I would expect either <b><i>\*\*\*test\*\*\*</i></b> (all asterisks bold & italics) or <b>\*\*<i>\*test\*</i>\*\*</b> (all asterisks bold, third and fourth asterisks italics). The distinction is hard to see in the font used here on Github, but much clearer in Typora.

This could have been just weird but technically correct, but it doesn't look like it is: the similar `**t*es**t*` is displayed as <b>\*\*t<i>\*es\*\*</i></b><i>t\*</i>, but turning off Source Code Mode shows this kind of nesting is not permitted: it shows as <b>t\*es</b>t\*</b>.

**Comment by abnerlee** [comment]
put into #1638
