### ISSUE TITLE
Hide dotfiles

### ISSUE THREAD

**Issue by Bamieh** [typora/typora-issues#1749]
Looking at the tree view of the project, it shows files/folders starting with `.`.
All dot(.) files are hidden by default, and i also believe this should be the default in typora as well.

![image](https://user-images.githubusercontent.com/6191849/44849552-23f81200-ac63-11e8-98b7-f82184a51c6a.png)

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by Bamieh** [comment]
@abnerlee 
OS: macOS High Sierra 10.13.4
Typora: Version 0.9.9.17.5 (0.9.9.17.5)

**Comment by abnerlee** [comment]
should be fixed already
