### ISSUE TITLE
please add shortcut for highlight

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#175]
eg.  `==` highlight

could i suggest it be `command + shift + h` ?

thanks.

**Comment by leewi9** [comment]
also let us choose highlight color, now there's only one color, which is a very shining yellow.

**Comment by AlexPasternak** [comment]
Agree both of these would be useful, and the proposed keyboard shortcut is logical & unused.

**Comment by abnerlee** [comment]
For hot fix on macOS, you could open preference panel of Mac System. And assign shortcut keys in Preference->Keyboard->Shortcuts->App Shortcuts

**Comment by AlexPasternak** [comment]
But that's only for items that appear in the menus, and Highlight is not a menu command. Neither in Format nor anywhere else.

**Comment by abnerlee** [comment]
@AlexPasternak, yes you are correct...

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by AlexPasternak** [comment]
I was writing a post about how this was not working, but then realized I had Cmd-Shift-H assigned to another menu bar app, and it was eating the keys. So, nice fix!

**Comment by joshuapinter** [comment]
For other landing here and wondering why highlight is not working for you, two things to check: 

**1. You need to enable this in the Preferences > Markdown panel.**
![screenshot 2018-03-25 12 40 05](https://user-images.githubusercontent.com/180819/37878659-aa2d2678-3029-11e8-9a2a-bc5c803594a9.png)

**2. You need to restart after you enable it for it to take affect.**

Then it works perfectly.
