### ISSUE TITLE
Package in official debian (ubuntu) repositories

### ISSUE THREAD

**Issue by kravemir** [typora/typora-issues#1750]
I would like to install typora, but I don't like to really bother add-in 3rd party dependencies, or downloading from websites.

Have you considered to create official debian (ubuntu) package?

I know, release cycle is slow, but I (and probably many others) don't live on edge, don't need latest features, and so on,...

**Comment by abnerlee** [comment]
<https://typora.io/#linux> show the official Debain/Ubuntu package

**Comment by kravemir** [comment]
@abnerlee, yes, there's official Debian/Ubuntu package. I meant, upload a package to official Debian/Ubuntu package repositories.
