### ISSUE TITLE
Fail to parse markdown file.

### ISSUE THREAD

**Issue by amitbha** [typora/typora-issues#1752]
System: archlinux
Typora: 0.9.56 (beta)

Description:
I use browser extension to save web pages as markdown file. But typora failed to open some files when the  file contained the contents like below:
```
[Link to somewhere](javascript:void(0);)
```
I have to delete these contents with other text editor, then can open them with typora.

**Comment by abnerlee** [comment]
Could you try update to v0.9.57?

**Comment by amitbha** [comment]
fixed in 0.9.57.
