### ISSUE TITLE
BUG, constant problem of update not auto-closing typora

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#1755]
1. when you open typora 
1. and you have your draft up
1. when update popup shows up
2. and it installs
1. then it says to auto-close app
1. i pick that but it never works once
1. always have to manually close

have no idea what's going on

win10

**Comment by SolveAllProblemsRightNow** [comment]
it's still doing it, what it says:

---

error

setup was unable to auto...

click retry to...

---

maybe it's cos there's multiple windows, but im very sure it does the same thing when there's one

also pretty sure it does the same thing when there's no file/doc open

hasnt ever auto-updated once, always have to manually close and update

**Comment by abnerlee** [comment]
#873

**Comment by SolveAllProblemsRightNow** [comment]
these are 2 distinct problems
