### ISSUE TITLE
screen freezing when want to choose a default folder

### ISSUE THREAD

**Issue by stefan38** [typora/typora-issues#1756]
The screen is freezing when want to choose a default folder using Typora 0.9.57 under Xubuntu 18.04.

**Comment by Thalos12** [comment]
I encountered this problem. Clicking on "Open folder" in the lower left part of the editor the folder selection window appears but nothing can be selected. Moreover, even clicking outside of this window has no effect (does not close the window and no action can be performed). Only pressing the Esc key closes the windows and returns everything to normal.

**Comment by vkbo** [comment]
Same error on Debian Buster (testing) with 0.9.58.
Key shortcuts work. I can `ctrl+L` to type a path, but cannot actually select it.

**Comment by abnerlee** [comment]
Are you using GTK? (https://github.com/electron/electron/issues/12302)

or relates https://github.com/electron/electron/issues/9942

**Comment by PsiACE** [comment]
> Are you using GTK? ([electron/electron#12302](https://github.com/electron/electron/issues/12302))
> 
> or relates [electron/electron#9942](https://github.com/electron/electron/issues/9942)

Yes, I use GTK3，here is a list of the packages and versions I currently use：
typora 0.9.58-3
gtk3 3.24.1+8+g220f77d8c1-1
electron 2.0.11-1

**Comment by PsiACE** [comment]
I don’t know what happened, but it works now.

**Comment by abnerlee** [comment]
Please reopen if it still happens on 0.9.60/Ubuntu
