### ISSUE TITLE
How do you display a div element?

### ISSUE THREAD

**Issue by OnlineVagrant** [typora/typora-issues#1758]
I'm trying to display a div tag element but it won't work. How do I go about doing this?
![capture](https://user-images.githubusercontent.com/39413259/44954428-4f077f00-ae78-11e8-9216-f94db86f025e.JPG)

**Comment by abnerlee** [comment]
For now empty line are not supported inside HTML blocks, you could use

```
<div>
some text here.
</div>
```

**Comment by OnlineVagrant** [comment]
Thank you.

**Comment by OnlineVagrant** [comment]
Just tried it bot it doesn't work 
![capture](https://user-images.githubusercontent.com/39413259/44992303-3b8a1000-af6d-11e8-9d72-1913347d3b86.JPG)

Am I doing something incorrectly?

**Comment by abnerlee** [comment]
What's your version?

**Comment by OnlineVagrant** [comment]
I'm using version 0.9.57(beta)

**Comment by abnerlee** [comment]
Could you attach or send us (<hi@typora.io>) a sample file that HTML content is not rendered?

**Comment by OnlineVagrant** [comment]
I put everything in one line and this is what it looks like 
![1](https://user-images.githubusercontent.com/39413259/45189187-2a136300-b20e-11e8-943f-d8981565deee.JPG)

however once I press enter it looks like this
![2](https://user-images.githubusercontent.com/39413259/45189203-37305200-b20e-11e8-900f-19002c53ce81.JPG)

Is this normal behaviour?
Do you still need the file? 

How  I think it should look ( this was not done using typora)
![capture](https://user-images.githubusercontent.com/39413259/45189244-68108700-b20e-11e8-89aa-4e18f2f415f0.JPG)

**Comment by abnerlee** [comment]
@OnlineVagrant It's not excepted, seems to be a bug.

But I cannot reproduce this, could you attach the sample file please ?
