### ISSUE TITLE
Export HTML with several files and relative .md links

### ISSUE THREAD

**Issue by fnolly** [typora/typora-issues#1759]
Exporting HTML does not export all other .md files and does not replace the links.

My project :
toctree.md
chapter_one.md
chapter_two.md

Exporting the toctree.md, where there are links to chapters one and two, generates one html file where links are the .md files.

**Comment by abnerlee** [comment]
Typora won't change links when export.

Maybe you're looking for #824

**Comment by vassudanagunta** [comment]
@fnolly what you want to do is use Typora as a Markdown editor and another tool to publish your assembly of pages. See [my comment here](https://github.com/typora/typora-issues/issues/824#issuecomment-418176112).
