### ISSUE TITLE
Open md file(app window) on default screen

### ISSUE THREAD

**Issue by zttt** [typora/typora-issues#176]
<img width="376" alt="aaa" src="https://cloud.githubusercontent.com/assets/8820946/15764440/8480bd24-295d-11e6-887b-21d05b27483a.png">

I'm using an external display. When I opens a file it always goes to the left display and I have to drag it to the main display. 
It seems sometimes it will remember which screen it was on and opens it there, but most of the time it doesn't. Not sure if this is related. 

But users will expect that new files(first time open) will open on the default display.

Is it possible to fix this? thanks.

**Comment by abnerlee** [comment]
Typora should able able to remember last window's position. Could you try move typora to default screen, then close it, and see if newly opened typora window can remember that position or not?

**Comment by zttt** [comment]
So the window's position is based on the app, instead of file.

In the current mechanism, if I have a file(only one) opened on the left display, and then opens another, it always opened on the left display.

Perhaps a better way to do this is to check which display is currently active and opens it there. Or just always open it on the default screen, considering that Typora is a multi-windows app.

**Comment by abnerlee** [comment]
This should be fixed in v0.9.38, please reopen this, if the bug still exists
