### ISSUE TITLE
Error in making table of content

### ISSUE THREAD

**Issue by apsrcreatix** [typora/typora-issues#1761]
Visually the table of content is there but when we are looking at the code side then there is no table of content markdown code and just simply written [TOC]. When I am uploading the MD file to Github it's showing [TOC] written instead of an actual table of content. 
Please let me know if I am raising a wrong issue or lagging in any steps for a table of content creation.
Thanks 🙂.
![screenshot from 2018-09-04 17-13-23](https://user-images.githubusercontent.com/24192742/45029317-e847b880-b065-11e8-92f4-ca9826402be5.png)
![screenshot from 2018-09-04 17-13-27](https://user-images.githubusercontent.com/24192742/45029318-e8e04f00-b065-11e8-8ffe-70e59f68302e.png)

**Comment by abnerlee** [comment]
GFM actually does not support `[TOC]`, it is actually an extended markdown syntax used by Typora and a few other apps.

This will be discussed in #1202

Also relates #169
