### ISSUE TITLE
About markdown source code mode

### ISSUE THREAD

**Issue by chusuchen** [typora/typora-issues#1763]
typora version : 0.9.57(beta)
windows 10 version : 17134.288
if I use "\_{}",the following words will be italic,but if I just use "\_",it will not happen.
![tim 20180905182346](https://user-images.githubusercontent.com/32267065/45087991-49d95700-b13a-11e8-847c-9cafca6127ec.jpg)
like this,the first "x\_abcd" is italic,but the second is not.
the italic word is ugly!

**Comment by abnerlee** [comment]
merge into 1638
