### ISSUE TITLE
Skipping h1 header

### ISSUE THREAD

**Issue by tlsdmstn56** [typora/typora-issues#1766]
Hello 

I am really enjoying editing my markdown file with Typora :).

I usually h1 header as the title of documents so Typora will be better for me if it has option to skip h1 header. 

I could change themes/base.user.css not to auto-numbering h1 header but I could not remove from outline in sidebar.

Thank you for your hard working :)

**Comment by abnerlee** [comment]
You could use 
```
.outline-h1:first-child > div {
    display: none;
}
```
