### ISSUE TITLE
Copy does not preserve source

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#1769]
If you select text in Typora and cut or copy it, then paste it in another program (or even into another Typora window), the original source is not kept.  In particular, code blocks are converted to `` ``` `` blocks, even if they were previously `~~~` blocks or even indented blocks.  (This leads to problems when working with tools that handle them differently, or projects that have coding standards for these things.)

Using different Copy commands (i.e. Copy vs Copy as Markdown), or changing the "Copy Markdown source as plain text" option does not help: you can either get changed formatting, or no formatting at all.

Currently, it appears the only way to do a source-preserving copy is to do it from source code mode.  (Which can be really inconvenient when doing things like extracting certain parts of a document to another file, as switching to source mode doesn't always preserve the cursor position and source mode lacks an outline view or navigation.)

**Comment by abnerlee** [comment]
You could change the "Copy Markdown source as plain text" option.

It will put both the source code (as plain text )and rendered text (as rich text or HTML) into clipboard.

If the app you paste into accepts HTML or rich style text, the rendered content will be paste, or else source code will be pasted. 

So pasting into code or plain text editors like sublime, the markdown source code will be pasted.
For some app, you could also force the other apps to only use plain text in clipboard, in word, for example, is to select "Keep Text Only" when paste.

**Comment by pjeby** [comment]
As I stated, changing that option **doesn't help**.  The problem is that if you have markdown like this:

```markdown
This is a test.

    Indented source.
```

It is copied and pasted as *this*:

~~~markdown
This is a test.

```
Indented source.
```
~~~

**Comment by abnerlee** [comment]
should be fixed
