### ISSUE TITLE
Typora 0.9.9 for Windows is detected as Trojan by Windows Defender

### ISSUE THREAD

**Issue by wyf88** [typora/typora-issues#177]
The suspected file is C:\Program Files (x86)\Typora\bin\typora.exe, and the type is Trojan:Win32/Fethar.B!cl

While I believe this is a false alarm, maybe you should check it out to see the reason.

**Comment by zhihengwang** [comment]
the installation file is detected as Trojan by microsoft security essentials

**Comment by abnerlee** [comment]
Windows version?

------

This time, I tested before the release:
https://www.virustotal.com/en/file/97c92da569a845ced21751ed13c9a6c7990ecfdaaecad73ef1c559bdd22ff32f/analysis/

and reports to 360 for their results. From the report, the "Microsoft" already passed it.

**Comment by zhihengwang** [comment]
I upgraded  the typora to version 0.9.6 last week , both typora-setup.exe and typora.exe were detected as Trojan this morning. so I install current version(0.9.9), now it is OK.

**Comment by wyf88** [comment]
0.9.6 was fine for me. I got notified by Windows Defender after I upgraded to 0.9.9.

**Comment by smallx** [comment]
360, haha. I have never used it and I won't use it forever.

**Comment by abnerlee** [comment]
> Windows version?

@wyf88 Sorry, I mean which Windows OS version did you use?

**Comment by wyf88** [comment]
@abnerlee Oh I forgot to mention. I'm using Windows 10 x64.

**Comment by abnerlee** [comment]
@wyf88 It seems my Windows Defender on windows 10 64bit won't report it as a malware when I execute a scan on typora's installation folder. 
Have you try "Update" in "Windows Defender" ?

**Comment by wyf88** [comment]
@abnerlee I have. What is strange is that I can still run Typora successfully. Maybe Microsoft has updated the virus database. Let's close the issue for now.

**Comment by abnerlee** [comment]
@wyf88 `C:\Program Files (x86)\Typora\bin\typora.exe` is launched when you use double click to open an existing *.md file, so please also check whether you could successfully open *.md file from Explorer or not.

**Comment by wyf88** [comment]
@abnerlee Yes, no problem.
