### ISSUE TITLE
Sentence with latex code unexpected changed after re-open the md file

### ISSUE THREAD

**Issue by Wangwj98** [typora/typora-issues#1770]
I'm using Typora to write my Calculus notes. I found that **the sentences with latex code in quote block**  will unexpectedly changed into source code with code block after reopening it.
**Below is an example:**
![image](https://user-images.githubusercontent.com/38370513/45253975-33353900-b3a2-11e8-8efe-098bab5a1468.png)

**Another example in my note:**

![image](https://user-images.githubusercontent.com/38370513/45253979-46480900-b3a2-11e8-9b37-b3e7cc05989a.png)

NOTE: version: 0.9.57 for linux

**Comment by Wangwj98** [comment]
AbnerLee <notifications@github.com> 于2018年9月10日周一 上午12:21写道：

**Comment by Wangwj98** [comment]
@abnerlee Already sent.

**Comment by Wangwj98** [comment]
@abnerlee This is bug is really bad.
It is not the kind of bug that always occurs at a certain condition.
 Given the same condition, the bug may occur or may not.

**Comment by abnerlee** [comment]
Fixed in new release
