### ISSUE TITLE
Support for other Lightweight Markup formats like AsciiDoctor, Markua, etc.

### ISSUE THREAD

**Issue by sirinath** [typora/typora-issues#1771]
Is it possible to support other Lightweight Markup formats like  [AsciiDoctor](https://asciidoctor.org/), [Markua](http://markua.com/), etc.

**Comment by vassudanagunta** [comment]
Typora is a ***Markdown***-based editor.  AsciiDoctor has zero relevance.

**Comment by sirinath** [comment]
This is very similar to MD.

**Comment by vassudanagunta** [comment]
So are many things. Typora is still far from perfect at handling Markdown (see the open issues, and there are many issues that aren't even submitted), so supporting another format before it nails Markdown would be its doom.

**Comment by sirinath** [comment]
Just an idea. You could make the formats plugable (like Notepad++.). Then different people may be also to work on each format they are interested in. Going open source might help the cause.

**Comment by abnerlee** [comment]
We don't have plans to other markup languages. If you want to use them inside Markdown, please follow #162 instead

**Comment by Foadsf** [comment]
This could actually be a great feature to consider.  Vanila MarkDown as I have addressee [here ](https://www.reddit.com/r/writing/comments/b0ywcw/free_markdown_editors_with_live_preview_for/) lacks many features required for professional documentation. Especially the `include` option which is only available in MultiMarkDown and not implemented in any of the FOSS editors neither GitHub at the moment.

**Comment by jcornaz** [comment]
>We don't have plans to other markup languages

Very sad.

I agree with @Foadsf, in the context of professional documentation, Markdown is way too limited.

**Comment by vassudanagunta** [comment]
>> We don't have plans to other markup languages
>
> Very sad.

That's like showing up on a Python IDE board and being sad because it doesn't support Rust.

**Comment by jcornaz** [comment]
> That's like being sad that a Java IDE doesn't support Python development.

First of all, I do have support for Python in my Java IDE...

Then  the comparison is not fair, because java and python have nothing in common. A fair comparison would be: "it is as sad as java IDE not supporting other JVM languages".

But definitely, I'll never use a Java IDE if I cannot write Kotlin code.

**Comment by Foadsf** [comment]
@jcornaz Since I left this comment here, I was enlightened about the fact that Typora is not Free software. So I'm switching away. I found out that Both Visual Studio Code and Atom have AsciiDoc Live Preview. So far they seem great and do the job for me.

**Comment by rafa2000** [comment]
I really like the overall sweetness of Typora as a seamless Markdown editor, including its handling of math. A would totally love it if the supported Markdown was AsciiDoctor. The handling of tables in AsciiDoctor is infinitely superior. I use it inside VSC with live preview. It almost has everything, except it doesn't show Math (Latex). So I'm a lost all the time, go for smart tables with VSC, or Latex rendition with Typora?
