### ISSUE TITLE
Cannot edit after a list

### ISSUE THREAD

**Issue by yangqinj** [typora/typora-issues#1781]
I wanna start a new first-level item after a second-level item, i.e., 
```
+ First item1
 - second item 1
 - second item 2
+ Second item2    // start a new first-level item
```
When I type '+', it doest not become a dark dot. Besides, I cannot delete "+" and even the "Second item2". And it doesn't work if I press 'Enter'. Thus I have to add the second first-level before "+ FIrst item1".

I use macos OS X EI Capitan and typora with version 0.9.9.17.5 (0.9.9.17.5).

**Comment by abnerlee** [comment]
Should be fixed in new release
