### ISSUE TITLE
Support for Mermaid UML Class Diagram

### ISSUE THREAD

**Issue by xceci** [typora/typora-issues#1782]
It seems that Mermaid already supported class diagram (although it's still in experimental)
https://github.com/knsv/mermaid

I'm wondering if Typora has any plan to support it, since class diagram is a highly desired feature.

**Comment by abnerlee** [comment]
We don't support is as it is experimental and lack of documents.

Maybe you can use it in Typora, but it is still buggy. Relates #1661
