### ISSUE TITLE
Pdf Export shows Scrollbar

### ISSUE THREAD

**Issue by arorar** [typora/typora-issues#1784]
I am trying to export a file with the following markdown to pdf

Here is a labeled equation:

$$
x+1\over\sqrt{1-x^2}\label{ref1}
$$

This is a referece : $\ref{ref1}$

It is the same as the example provided on the support page. However, the exported pdf shows equations with horizontal scroll bars and also does not show the equation numbers. I am on windows 10 and using Typora 0.9.58 (beta)

**Comment by Far117** [comment]
I can confirm that this is still an issue for the Linux edition, version 0.9.60.

**Comment by abnerlee** [comment]
merge into #1646
