### ISSUE TITLE
[windows] support control+shift+home/end

### ISSUE THREAD

**Issue by rossipedia** [typora/typora-issues#179]
<kbd>Control</kbd>+<kbd>Home</kbd> and <kbd>Control</kbd>+<kbd>End</kbd> are typically used in editors on Windows to navigate to the beginning and end of a document, respectively. It would be awesome if the Windows version of Typora supported those shortcuts as well.

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by rossipedia** [comment]
Would it be much more difficult to support <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>Home</kbd> and <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>End</kbd> as well?

Absolutely love the app! Thanks so much for all your work!

**Comment by abnerlee** [comment]
fixed in new version
