### ISSUE TITLE
Files are not opened in Version 0.9.9.18 (1047) (Mac OS El Capitan version: 10.11.6)

### ISSUE THREAD

**Issue by Gonzalo2310** [typora/typora-issues#1791]
The file opens but does not show me the content.
I tried a few and it's the same in all of them.

**Comment by Gonzalo2310** [comment]
The file opens but does not show me the content.
I tried a few and it's the same in all of them.

**Comment by abnerlee** [comment]
#1779 We will fix this in next version up asap

**Comment by Gonzalo2310** [comment]
thx
