### ISSUE TITLE
UX - fullscreen should stay fullscreen. when you open typora when its already set to fullscreen, it's not fullscreen, and has that 'grey title bar' at top. you have to re-fullscreen it again

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#1795]
UX, fullscreen should stay fullscreen.

when you open typora when its already set to fullscreen, 

it's not fullscreen, and has that 'grey title bar' at top. 

you have to re-fullscreen it again

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by SolveAllProblemsRightNow** [comment]
all of them every single version so far is like that

**Comment by SolveAllProblemsRightNow** [comment]
why this close for?

this is probelm

open

**Comment by abnerlee** [comment]
fixed in new release

**Comment by thurrott** [comment]
It's 2024, and this is still broken. Typora does not remember its size or window state (maximized/windowed) on launch in Windows 11.
