### ISSUE TITLE
Inline math blocks not getting updated on edit

### ISSUE THREAD

**Issue by cvzakharchenko** [typora/typora-issues#1797]
OS: Linux 4.14.69-1-MANJARO x86_64
Typora version: 0.9.57 (beta) (https://typora.io/linux/typora_0.9.57_amd64.deb)

When i try to insert new text into existing math block it works fine, except when the insertion take place right after opening $. But if there is space after opening $, everything fine again. Details on the gif below.

![final](https://user-images.githubusercontent.com/6278349/45596907-49f41500-b9cc-11e8-9bc0-10b43bb8038c.gif)

To make things worse, "Refresh all Math Expressions" just deletes all unrendered text in equations.

**Comment by abnerlee** [comment]
Please update Typora to v0.9.58
