### ISSUE TITLE
Is the tab bar gone? 

### ISSUE THREAD

**Issue by dwaltrip** [typora/typora-issues#1799]
First off, thanks for creating Typora. It is an amazing tool.

However, the tab bar, which is one of my favorite features, seems to have gone missing (or I simply don't know how to find it anymore).

By tab bar, I mean the ability to have multiple files open at once in a single window, as separate tabs. I used to be able to press "cmd + t", which would create a new tab. This doesn't work anymore. I also don't see any options related to the tab bar in the "view" menu.

This happened right after I upgraded to 0.9.9.18.1 on MacOS (which is the latest version). I checked the changelog, and I don't see any mention of the tab bar.

Any guidance would be appreciated. Thanks!

**Comment by abnerlee** [comment]
@dwaltrip what's your system language?

**Comment by dwaltrip** [comment]
I've changed the language setting to English, and also restarted my computer (there was a note about restarting below the language setting), but it hasn't brought back the tabs.

Here are 2 screenshots of the preferences screen and the view menu:
<img width="497" alt="typora -- preferences" src="https://user-images.githubusercontent.com/3523411/45765252-76d14380-bbe9-11e8-869e-78703e56838d.png">
<img width="310" alt="typora -- view menu" src="https://user-images.githubusercontent.com/3523411/45765282-8486c900-bbe9-11e8-8d36-98312071cf99.png">

Should I try uninstalling and reinstalling?

**Comment by abnerlee** [comment]
What's your macOS version?
What's your System's language setting?

Is there view -> show tab bar for TextEdit.app ?

**Comment by dwaltrip** [comment]
**What's your macOS version?**
`Version 10.11.6 (15G1217)`

**What's your System's language setting?**
English.

**Is there view -> show tab bar for TextEdit.app?**
No, there isn't!
My other computer does have the "view -> show tab bar" option for TextEdit (and tabs are working in Typora as well). It is macOS version 10.12.6.

**Comment by abnerlee** [comment]
Tab for Typora also requires macOS >= 10.12

**Comment by dwaltrip** [comment]
Doh! I didn't realize that was the case, thanks for your patience.
