### ISSUE TITLE
Very strange behaviour about the outline panel on the left

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#180]
It's so weird that the outline will automatically swing back every time, heading locating not accurate, please check the gif for detail.

It's really affecting my productivity and If you could please repair it and release a new version asap. Thanks.

![untitled](https://cloud.githubusercontent.com/assets/10832544/15800065/73ccb9a6-2aa2-11e6-9a5e-001cc1ae2412.gif)

**Comment by leewi9** [comment]
Please release a new version fixing this bug as soon as possible, because if not we I have to reverse back to previous version, which is very bad feeling. I'm a update-crazier.

**Comment by abnerlee** [comment]
Should be fixed in new version
