### ISSUE TITLE
Closing inline math expressions moves the caret back when it shouldn't.

### ISSUE THREAD

**Issue by eth-p** [typora/typora-issues#1803]
This affects Typora for macOS Version 0.9.9.18.1 (1088), but did not affect the previous version.

When closing inline math expressions, the caret moves back to the end of the math block after it's rendered. If you type quickly (e.g. taking notes in lectures), it ends up fragmenting the sentence and  lowering productivity.

**Example:**  
The `|` character represents the caret.

```
The value of $x|
The value of $x$ is e|
The value of $x$| is e            <-- After Typora renders the math block.
The value of $x$qual to| is e     <-- Sentence is messed up.
```

**Demonstration Video:**  
https://youtu.be/y0cfnJlUQgk

**Comment by abnerlee** [comment]
Fixed in new release
