### ISSUE TITLE
Black bar appears on the tab 

### ISSUE THREAD

**Issue by cn-src** [typora/typora-issues#1810]
Appears when creating a new tab using shortcut(command + T).

macos: 10.13.6 (17G65)
version: 0.9.9.18.1 (1088)
<img width="1276" alt="jietu20180919-173248 2x" src="https://user-images.githubusercontent.com/8263180/45744956-5c6f8800-bc32-11e8-9c7e-3462a109e927.png">

**Comment by abnerlee** [comment]
Please reopen this if it still happens after update Typora,
