### ISSUE TITLE
Incorrect path name when saving assets

### ISSUE THREAD

**Issue by RobWalker** [typora/typora-issues#1811]
This behaviour looks to have broken in a recent build, it was working before.

On a Windows box I have *Images Insert* set to `Copy images to ./${filename}.assets`:

![image](https://user-images.githubusercontent.com/736849/45759193-61faad00-bbf5-11e8-84b1-7b588d281627.png)

* Open a file, eg. README.md
* (Probably optional) Edit and save it
* Open another file, eg A/B.md
* Copy and paste and image from the clipboard into this document.

**Expected behavour**
The image should be saved as A/B.assets/something.png

**Actual behavour**
The filename given to the image still uses README.md as the base filename, and not B.md

![image](https://user-images.githubusercontent.com/736849/45759302-9f5f3a80-bbf5-11e8-873f-a75e822865d8.png)

**Comment by reposkeeper** [comment]
+1 Mac OSX has same problem. All auto copy options are not work(copy to a incorrect path).

**Comment by ziyoushouhuzhe** [comment]
Mac Mojave has the same problem. Only the first file when you open typora get correct path.

**Comment by abnerlee** [comment]
Fixed in new release
