### ISSUE TITLE
Cursor jumping while rendering mathjax

### ISSUE THREAD

**Issue by asberk** [typora/typora-issues#1813]
Typing the first dollar sign enters you into math mode, you type your math, you insert a second dollar sign and keep typing at your usual pace. Unexpectedly, the rendering of the mathjax makes the cursor jump back inside the dollar sign environment, thereby inserting the new text in a place where it doesn't belong. For example, the desired behaviour is to obtain `...$N$ in ...` [like so](https://i.imgur.com/QIdl8Pm.png), but [this happens](https://i.imgur.com/s7VzGKU.png) instead and must be fixed by backtracking and fidgeting with the text again.

Please let me know if there's any other information I can provide.

**Comment by abnerlee** [comment]
duplicate with #1803
