### ISSUE TITLE
Set background color to pure white?

### ISSUE THREAD

**Issue by jflycn** [typora/typora-issues#1814]
I tried to change the background color to pure white by using the following code in all the themes except "night":

```
html, body, content, #write{
    background: #FFFFFF;
}
```

However, the background color is always gray, which makes my eyes uncomfortable.

Is there anyway to set the background color to pure white?

**Comment by abnerlee** [comment]
see https://support.typora.io/Backgound/

BTW, the default theme including Github already use `#FFF` as background.

**Comment by jflycn** [comment]
Sorry. It is because of my monitor... I thought it is grey. It is actually white.
