### ISSUE TITLE
Keyboard "cursor up" navigation seems to be broken

### ISSUE THREAD

**Issue by mbartosch** [typora/typora-issues#1817]
When using "cursor up" between sections (e. g. between bullet points or paragraphs) it seems that the cursor is frequently placed at the end of the line of the previous paragraph.
This is particularly inconvenient when the cursor was at the beginning of the line before moving up, e. g. in a bullet point list.
This was on Mac OS X, Typora version 0.9.9.18.1 (1088)

**Comment by abnerlee** [comment]
merge into #1164
