### ISSUE TITLE
Aligning/ Centering Mathematical Expressions and Headings

### ISSUE THREAD

**Issue by Bunkersmasher** [typora/typora-issues#1818]
I'm creating a complete summary of 11th and 12th grade HL math. 

Anyways, I'm having some issues with alignment. I want to align and push both 'I)' and 'II)' (picture below) to the left while also keeping the rest of the expression on the right--how can I do so? 

And is there any way possible I can center headings? Thank you in advance.

![image](https://user-images.githubusercontent.com/43452623/45842305-9f0d8f00-bd1c-11e8-96b5-cffa5fd27f14.png)

Here is my code:
`$$
\begin{align*}
\sqrt{-8+6i}&=x+yi \\
-8+6i &= x^2-y^2 +2xyi \\ \\
\textbf{I)}
-8 &= x^2 + y^2 \\
\textbf{II) }
6 &= 2xy \\
\end{align*}
$$`

**Comment by abnerlee** [comment]
Sorry, I'm not good at LaTeX, 

I'm not sure how to align using LaTeX, maybe you could google about it.
