### ISSUE TITLE
Paste in math will be not available

### ISSUE THREAD

**Issue by FlandiaYingman** [typora/typora-issues#1819]
Like this, i have a math:
`$n=0,$`
It shows correctly. If i paste something into it:
`$n=0,(ctrl+v)m=1$`
The math is not available, the real time rendering stops, the font will turn into normal.

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by FlandiaYingman** [comment]
@abnerlee 
Windows 10, Typora 0.9.58(beta)

**Comment by abnerlee** [comment]
Fixed in new release
