### ISSUE TITLE
A bug in processing lists nested in quote.

### ISSUE THREAD

**Issue by smallx** [typora/typora-issues#182]
Hi. I'm transforming my text file to markdown file. I find a bug in processing lists nested in quote.

For example, I have some text as follow:
![1](https://cloud.githubusercontent.com/assets/16517035/15842411/69e55afc-2c8b-11e6-868f-9d0ada800d1e.png)
`Tab` is transformed to 3 `Space` by Typora automatically when I paste it into it:
![2](https://cloud.githubusercontent.com/assets/16517035/15842497/19429d7a-2c8c-11e6-80bf-7164176ee322.png)
It is shown normally as follow:
![3](https://cloud.githubusercontent.com/assets/16517035/15842645/91aaf8e2-2c8d-11e6-8ab4-73db2fb3ffce.png)
However, 3 `Space` is transformed to 1 `Space` by Typora automatically when I save and re open markdown file:
![4](https://cloud.githubusercontent.com/assets/16517035/15842899/c073839a-2c8f-11e6-8559-95acb0b43c70.png)
So, some thing is bad as follow:
![5](https://cloud.githubusercontent.com/assets/16517035/15842900/c0c2c720-2c8f-11e6-8028-7a85934de6aa.png)

Some information:
- Typora 0.9.8
- Windows 8 x64

Test text:
```
> - Hi, good morning!
>
><Tab>Morning!
>
> - nice to meet you!
>
><Tab>nice to meet you too!
```

Thanks.

**Comment by abnerlee** [comment]
Should be fixed in new version
