### ISSUE TITLE
Wrong formate on windows

### ISSUE THREAD

**Issue by lonelyma1021** [typora/typora-issues#1824]
I use typora across windows and linux. I get right formate when using typora-linux, but get wrong formate when open the same file on windows. eg. Typing  `#Some Title`  on typora-linux, I got a title, as I excepted. but when I open it on windows, I just got a normal text "#Some Title". I have to type a space between "#" and "Some". Can u fix that, make the software have the same behavior on linux and windows?

**Comment by abnerlee** [comment]
You have different setting about "Strict Mode" in Typora's preference panel. Please undify the settings.
