### ISSUE TITLE
Request: Separated Smart punctuation "convert on..." for dashes and quotes

### ISSUE THREAD

**Issue by vpontin** [typora/typora-issues#1825]
Well, sometimes i want only "convert on input" for dashes (to add em and en dashes without much hassle), but only want "convert on rendering" for quotes (because at least in my locale the curly quotes causes bugs in some software).

Since i mainly use Typora for writing (not for much technical manuals and such) i think this would be a nice addition.

**Comment by abnerlee** [comment]
We don't want to separate them since I don't think it is needed for most users.

In your case, why not just use "convert on rendering"?

**Comment by vpontin** [comment]
Well, i paste the text as rich text after writing (to transfer to a fanfic website), so if i put everything to convert on rendering the dashes (em and en) will be copied as double hyphens. If i put convert on input the curly dashes are copied alongside, and this causes some issues with the websites i put my texts.

While i agree this is a secondhand feature, would be a compromise for users who want the dashes on input but the straight quotes.
