### ISSUE TITLE
EPERM on Documents folder

### ISSUE THREAD

**Issue by dmlane** [typora/typora-issues#1826]
Hi - I've just upgraded to the latest version and typora can open but can no longer save files to my Documents folder, I'm running the latest update of Windows 10 Pro.

**Comment by abnerlee** [comment]
"EPERM" means no write privilege. Please make sure current user group has write access to your documents folder.

You could refer: 
https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/give-permissions-to-files-and-folders-in-windows/78ee562c-a21f-4a32-8691-73aac1415373?auth=1

If you still have issues, please provide more details, like error message, etc.
