### ISSUE TITLE
copying LaTeX code

### ISSUE THREAD

**Issue by neuwirthe** [typora/typora-issues#1828]
MacOS 10.13.6, Typora 0.9.9.18 (1047)
When copying and pasting LaTeX code, orange things happen: 

```
$$
\begin{align}   
& 2+4+8+16+32 \\
- (1+{} & 2+4+8+16) \\
\end{align}
$$
```

becomes

```
$$
xxxxxxxxxx \begin{align}   & 2+4+8+16+32 \\- (1+{} & 2+4+8+16) \\\end{align}
$$
```

Can this be avoided or repaired?

**Comment by abnerlee** [comment]
How to reproduce this?

How about 0.9.9.18.1 ?
