### ISSUE TITLE
Add menu option for text highlights

### ISSUE THREAD

**Issue by dbogdanov** [typora/typora-issues#1831]
Add Format menu option for ```<mark>Marked text</mark>``` for highlighting text.

**Comment by abnerlee** [comment]
`<mark>` is not common in Markdown that need a menu item. And we already have one menu item for "highlight" (==).

`<mark>`, and other styles, such as `<s>`, `<span style="color:red">`, etc can be supported via configurable menu items or text snippets, we would consider it in future updates. 

You could use 3rd party tools such as Typinator for now.
