### ISSUE TITLE
【Suggestion】wish to support html script function

### ISSUE THREAD

**Issue by thinkycx** [typora/typora-issues#1832]
Hello, wish to support html script function in order to use code in gist.github.com.For example:
<script src="https://gist.github.com/thinkycx/0b65ea9a0b7a3e76051e77824702d2c8.js"></script>

**Comment by abnerlee** [comment]
We don't support custom scripts for security reason.

But gist is already supported, You could use `<script src="https://gist.github.com/thinkycx/0b65ea9a0b7a3e76051e77824702d2c8.js"></script>` in Typora

**Comment by thinkycx** [comment]
@abnerlee  Hello, I have used the script in typora. However it doesn't work. After I paste it in typora, it displays nothing.

typora version 0.9.9.18.1 (1088)

![image](https://user-images.githubusercontent.com/13138128/46523755-4fe96180-c8b9-11e8-9261-073f1ecba919.png)
After I press ENTER, it disappears.
![image](https://user-images.githubusercontent.com/13138128/46523784-5ed01400-c8b9-11e8-899c-b47876198232.png)

**Comment by abnerlee** [comment]
Yes, we only allow a few "scripts". We would consider add whitelist for users to add their own scripts in future.
