### ISSUE TITLE
Find and Replace problem

### ISSUE THREAD

**Issue by neuwirthe** [typora/typora-issues#1834]
MacOS 10.13.6 Typora version 0.9.9.18 (1047)
Find and Replace does not work.
I can enter the font term and the replace term on top of then window,
and the buttons react when the cursor is moved on top of the buttons,
but click on the buttons (All or Replace) does not produce any action.

**Comment by abnerlee** [comment]
How about 0.9.9.18.1? 

I cannot reproduce this on latest version.

So is there detailed steps to reproduce this? including which term did you input, which button is clicked, what's the text content, etc.
