### ISSUE TITLE
Update changes config folder - settings seem to be gone

### ISSUE THREAD

**Issue by codiflow** [typora/typora-issues#1836]
I'm using **Manjaro Linux** and after updating Typora through pacman from the AUR the config path changed without any information. The log entry from the pacman script is as follows:

```
[2018-10-04 08:31] [ALPM] upgraded typora (0.9.58-1 -> 0.9.58-2)
```

Before it was `/home/USERNAME/.config/Typora/` and after the update it changed to `/home/USERNAME/.config/Electron/` **automatically**. I recognized it because my themes were gone.

I think the install script should check whether there is a folder present at the old location moving it automatically to the new location.

**Comment by abnerlee** [comment]
The configure folder for Typora should be `/home/USERNAME/.config/Typora/`, and there should not be two versions of `0.9.58`.

You could refer https://support.typora.io/Typora-on-Linux/ for install Typora on Linux. The `AUR` package is not maintained by us officially, so we did not know what the install scripts do.
