### ISSUE TITLE
All macOS custom key bindings ignored

### ISSUE THREAD

**Issue by tpierzina** [typora/typora-issues#1837]
Version 0.9.9.18.1 (1088)
macOS 10.13.6

All key binding are simply ignored. I've tried:
- mapping menu items with and without an existing hotkey
- using several obscure combinations of keys and modifiers
- confirmed that existing and new bindings work correctly in other apps

**Comment by AlexPasternak** [comment]
FWIW, I'm on the same macOS, but not seeing this issue because use Keyboard Maestro to remap functions. This allows me to cloud sync keyboard settings between systems, which is not possible when you just remap them through the clunky OS-based SysPrefs approach.

<img width="365" alt="screen shot 2018-10-04 at 3 46 51 pm" src="https://user-images.githubusercontent.com/1819485/46499036-07fd0880-c7ed-11e8-8d17-682db07b7bbe.png">

**Comment by tpierzina** [comment]
I should have added, KM also ignores Typora (or vice versa I suppose). Like you I prefer KM but when it failed I tried native. No luck.

**Comment by abnerlee** [comment]
Did you follow https://support.typora.io/Custom-Key-Binding/ ? The custom key binding is support by OS not by Typora's logic, so it shouldn't be typora's issue. Does custom key binding on other apps, like Safari work?

Also, could you list which menu item, how you bind the custom key shortcuts, and which shortcut keys are you assigned to.

**Comment by tpierzina** [comment]
I should have been more specific.
- Yes, I followed that support page (which, as you pointed out, is just the basic macOS process).
- Custom key binding on Finder, Sublime Text 3, iTerm2 and BeyonCompare all work fine. Likely others as well.
- I bound the shortcuts the way you bind shortcuts. Not sure I understand the question. I was trying to modify the Ordered and Unordered Lists hotkeys to ⌘⇧& and ⌘*. I made certain the new hotkey was not already in use (like ⇧⌃⌥⌘U), and I also tried on a menu item that did not have a shortcut (File/Rename...).

As noted in the discussion, I also use Keyboard Maestro and its hotkey triggers work for other apps but not Typora.

I'm on a different Mac than before (when they were working) so I'll try it there over the weekend.

I agree that this is 99.9% an Apple issue. But you may be able to work around it if we figure out the right incantation,

**Comment by abnerlee** [comment]
@tpierzina 

> I bound the shortcuts the way you bind shortcuts. Not sure I understand the question. I was trying to modify the Ordered and Unordered Lists hotkeys to ⌘⇧& and ⌘*. I made certain the new hotkey was not already in use (like ⇧⌃⌥⌘U), and I also tried on a menu item that did not have a shortcut (File/Rename...).

In my testing, you cannot bind to ⌘⇧& but only ⌘⇧7 if you use English (US) keyboard, so did you use other like of keyboard layout?

About `Rename...` it should be `Rename…` (not three dot).

And after your set the shortcut keys, did the shortcut key get updated in Typora's menu (right side of the targeting menu item)?
