### ISSUE TITLE
Enhanced Table inline cell formats

### ISSUE THREAD

**Issue by marcus-tmamtv** [typora/typora-issues#1839]
Hi guys,

It would be great if you can enhance the current table cell inline format support.

- Support of different inline format styles (orderd list etc) in table cell (example see below)

thanks
Marcus

<img width="413" alt="sample" src="https://user-images.githubusercontent.com/28784057/46533327-81a3fd80-c8a4-11e8-8439-7c282be50f73.png">

**Comment by abnerlee** [comment]
ordered list is not inline level, it is block level. And we cannot support this using Markdown.

**Comment by marcus-tmamtv** [comment]
ok thanks for fast feedback

**Comment by marcus-tmamtv** [comment]
**Added new request:**
- Support of inline breaks in cells if you copy an html table from web with line breaks. (current 
incell workarround doesn't work for copied web tables ... if there are line breaks included)
