### ISSUE TITLE
Default Code Block to Previously Used Language

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#184]
In a document with many code blocks (fences), setting the language for each one quickly gets tedious. But the syntax highlighting continues to make it worthwhile.

Could there be an option to default to the last used language from the same document? The first one would be blank, then you pick Java, then the next one is Java by default, which of course you could change. (For minimalism, this could even be the default behavior)

**Comment by abnerlee** [comment]
Hi,

"```" is used to create a code fences without any language specific. 

"```java" can be used to create a code fences with language highlight of java.

So, I think it is already easy to create code fences with syntax highlight of Java.

**Comment by AlexPasternak** [comment]
I wish this was asked to be clarified before it was closed. Maybe it's easy to create _one_ code fence with Java, but not several dozen. The point is that in a document that deals with a particular language, whether C++ or Scala, you're not likely to be changing languages from one code fence to another.

I typically use the keyboard shortcut to create fences, because it's much faster than typing the starting sequence. Typing out the language name each time is not the same thing as what I was proposing.

Try typing out a Markdown article, book, or notes where code fences are all for Javascript, using keyboard shortcut to insert the fence, and then I think my suggestion of assuming you're still talking about the same language as a few lines above will make sense.

**Comment by abnerlee** [comment]
Hi,

I understand what you mean, but "```" is only the syntax to create a code block without any language specific. I mean, if a language is set after users input "```", it could confuse users, since in all markdown editors that syntax refers to a normal code block, so I don't think your solution is a good approach.

But, how about let auto-complete suggest your latest language, when you input "```"?

**Comment by AlexPasternak** [comment]
Well again I'm not typing the ` char sequence, where I can see adding text that you didn't type would be confusing. I'm loving and using the code fence keyboard shortcut to insert it instead.

Could just the keyboard shortcut default this behavior? Or at least show the last one as the default when you click in the language selection list? But I still think just defaulting to the last one in this case is the most helpful, and the user can clear or change it if it's wrong (e.g., I'm typing a Web dev article and this code block is JavaScript instead of HTML).

**Comment by AlexPasternak** [comment]
Despite the previous "wontfix" label here, this has been added in 1.6!! It took almost 7 years but we finally got there. Thank you @abnerlee, this will still be very useful going forward.
