### ISSUE TITLE
PDF export shows wrong creation and last edit time

### ISSUE THREAD

**Issue by GiantCrocodile** [typora/typora-issues#1840]
When I export to PDF my PDF file states that it has been created and last time edited 2 hours after it has been generated.

Example:
I generate the file on 4 pm.
File says it was generated at 6 pm.

Is this some wrong timezone considered at generation issue?

**Comment by abnerlee** [comment]
What's your Typora/OS version?

**Comment by GiantCrocodile** [comment]
Typora 0.9.58 (beta), Win 10

**Comment by abnerlee** [comment]
Fixed in new release
