### ISSUE TITLE
How to specify author and title for exported PDF?

### ISSUE THREAD

**Issue by GiantCrocodile** [typora/typora-issues#1841]
I didn't find any way to specify the author and title when I export to PDF format. Is there any way? If not, I suggest this as a feature like pandoc already supports. At the moment both fields are empty in the PDF.

**Comment by EdOverflow** [comment]
You can do this by selecting `Paragraph > YAML Front Matter` and adding the following to your document in Typora:

```
author: EdOverflow
title: Example Title
```

![image](https://user-images.githubusercontent.com/18099289/46583713-4f88cc00-ca5b-11e8-878c-051909e3a3af.png)

**Comment by GiantCrocodile** [comment]
Thanks @EdOverflow! I suspected it to be somewhere and being related to YAML Front Matter but I didn't find the option in the menu nor a how to. This did work as expected.

For someone who has the same issue, see this: https://support.typora.io/Markdown-Reference/#yaml-front-matter
