### ISSUE TITLE
Feature: Music Notation (ABC/LilyPond)

### ISSUE THREAD

**Issue by pedro-psb** [typora/typora-issues#1844]
I lack technical expertise to contribute, but if it helps I made a breafly research on the subject.

LaTex seem to currently support two main methods to render scores, one with ABC and other Lilypond.
https://martin-thoma.com/how-to-write-music-with-latex/

Particularly I like lilypond. They have this project of integrating with external platforms called lilybook:
http://lilypond.org/doc/v2.18/Documentation/usage/integrating-music-and-text

I think it would be of much value to musicians.

**Comment by abnerlee** [comment]
Would be part of #162
