### ISSUE TITLE
Suggestion Double line break to Paragraph break customizability

### ISSUE THREAD

**Issue by Thunder33345** [typora/typora-issues#1845]
sidenote: sorry for the very indescriptive title i know nothing better to call them

basically as of right now you can newline without paragraph by using "shift+enter", and new paragraph by using "enter"

i would like to suggest an option to:
enter will result in a newline WITHOUT a new paragraph(as equivalent of shift+enter)
enter on a EMPTY NEW LINE(aka double tap enter) will result in a new paragraph(as equivalent of using enter)

while using shift enter when i want to continue the same paragraph works, this would be a nice quality of life improvement for me, thanks

**Comment by abnerlee** [comment]
duplicate with #37
