### ISSUE TITLE
Math equations does not refresh sometimes

### ISSUE THREAD

**Issue by BalanceUhen** [typora/typora-issues#1848]
![image](https://user-images.githubusercontent.com/21274779/46612199-6eae5900-cb42-11e8-8a6e-dc8b2c60f3c1.png)

If write a math equation in lists(by pressing `ctrl+enter` and using `$$`
and then move the cursor to the start of the line,and type enter:
![image](https://user-images.githubusercontent.com/21274779/46612452-23487a80-cb43-11e8-9dbc-f9cce95670d3.png)

![image](https://user-images.githubusercontent.com/21274779/46612483-3e1aef00-cb43-11e8-8af7-f1716bfb8845.png)
Then the math equation become *texts*, and after a few seconds the situation does not change.
I have tried *serveal* times.

![image](https://user-images.githubusercontent.com/21274779/46612599-9c47d200-cb43-11e8-8992-123f9c9f31d7.png)
If I select the math equation (or other things that will *refresh* the page), the appearance will become *normal*.

[Youtube video one](https://youtu.be/5fTc93dh2vk)
[Youtube video two](https://youtu.be/gAjRnKU7s4g)
The video was taken by windows game bar,and has a 30 seconds limit.
These videos showed how the stranger thing happened.

Typora version: 0.9.9.58 (beta) 12, Sep, 2018
OS: Windows 10

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by abnerlee** [comment]
relates #2420
