### ISSUE TITLE
Please support macOS 10.14 "Dark mode"

### ISSUE THREAD

**Issue by singularitti** [typora/typora-issues#1850]
Now that macOS 10.14 Mojave has been released, many apps have already supported its all-new [Dark mode](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/), I am curious about when is Typora going to support it.

The Dark mode includes, but not limited to (I will use Terminal.app as an example), a dark title bar:
<img width="637" alt="bar" src="https://user-images.githubusercontent.com/25192197/46678690-2bd89980-cbb3-11e8-8ce2-01e4d56d44a0.png">

and a dark settings panel, etc.
<img width="780" alt="panel" src="https://user-images.githubusercontent.com/25192197/46678734-4a3e9500-cbb3-11e8-9bff-0aa148e3fdc4.png">

**Comment by abnerlee** [comment]
We are going to support it from next version up.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by singularitti** [comment]
Thank you so much!

**Comment by BrandoZhang** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/23352923/47573649-6b073880-d970-11e8-95c5-ade78fe73bda.png">
On macOS MojaveIn dark mode, version 0.9.9.19 (1296) cannot display the title (it is white by default).
