### ISSUE TITLE
Pack Windows application code into app.asar to improve startup and installation speed

### ISSUE THREAD

**Issue by nanoant** [typora/typora-issues#1852]
This is my first issue report for Typora. First of all let me thank you for such a marvelous piece of software.

I would like to suggest to pack `C:\Program Files\Typora\resources\app` into `app.asar`, same as it is done with `electron.asar`. I expect this will make installation and application startup much faster since windows IO for *3,108 Files, 442 Folders* (taken from installation stats) is a pity, especially if some antivirus is running in background.

### More info on the subject:
1. https://electronjs.org/docs/tutorial/application-distribution
2. https://github.com/electron-userland/electron-builder/issues/428

**Comment by abnerlee** [comment]
Packed some of it for quicker installation.
