### ISSUE TITLE
How to set text align center or right? How to set picture align left,center,or right,and the size of picture?

### ISSUE THREAD

**Issue by keepgoodfeeling** [typora/typora-issues#1854]
how to set text align center or right?
How to set picture align left,center,or right,and the size of picture?

**Comment by abnerlee** [comment]
`<div style="text-align:right">right</div>`

**Comment by adamgranthendry** [comment]
@abnerlee This kills all your previous Markdown formatting though

@keepgoodfeeling If you want to make this change global, I recommend editing paragraph (`p`) of `C:\Program Files\Typora\resources\app\style\base.css` to include

```
text-align: justify;
```
