### ISSUE TITLE
Can't export to PDF: Export Failed (UnknownErrorException: bad XRef entry)

### ISSUE THREAD

**Issue by zaroth** [typora/typora-issues#1856]
Fresh install, version 0.9.58 (beta) x64 on Windows 7 Professional x64. No Pandoc installed.

Wanted to try Typora out, created a test file and tried a test PDF export via File menu. Result below:

![error image](https://user-images.githubusercontent.com/840021/46807592-94b64200-cd6a-11e8-84af-9c245ee7e19c.png)

What I tried:

- restarting Windows (didn't work)
- deleting AppData folder and restarting app (didn't work)
- reinstalling 32-bit version of the app (didn't work)
- installing Typora on a colleague's computer (Win10) - it worked.

**Comment by zaroth** [comment]
Update: I reinstalled my machine with Windows 10 and I got the same error as on Windows 7. It was a nearly-fresh install, with just a few applications installed from Ninite. So possibly it's some interaction with other apps/libraries...?

**Comment by abnerlee** [comment]
If you open DevTool from `View` menu, and do the export, are there any errors in the console of the DevTool ?

**Comment by zaroth** [comment]
Update on this issue: it disappeared after Windows 10 got upgraded to the build 17134.285. On the previous version (which was 16xxx something I think) it persisted and could be reproduced every time without fail though.
