### ISSUE TITLE
No text margin to screen on mobile

### ISSUE THREAD

**Issue by bgalvao** [typora/typora-issues#1857]
I understand that Typora's html export is desktop oriented and that it probably is up to me to fix it for my own purposes, but I think it was worth pointing out here.
The text margin on mobile is pretty much non-existent. Other details:

- I'm using the newsprint theme here.
- Firefox browser on Android

![photo_2018-10-11_15-15-55](https://user-images.githubusercontent.com/17158288/46810563-dfcf5580-cd68-11e8-8205-6456510fb4de.jpg)

**Comment by abnerlee** [comment]
Fixed in new release
