### ISSUE TITLE
Spellchecker treats smart quote as word separator

### ISSUE THREAD

**Issue by iafisher** [typora/typora-issues#1858]
To reproduce:
- Turn on spellcheck.
- Turn on smart quotes and type a contraction like "hasn't" or "didn't", or else copy-paste this example: `hasn’t`. The word will be marked as mispelled.

Since the smart quote is treated as a word separator, you cannot add the whole contraction to the dictionary, only each part individual. That is not desirable because it will cause isolated occurrences of `hasn`, `didn` etc. to not be marked as mispelled.

OS version: Ubuntu 18.04
Typora version: 0.9.53 (beta)

Thank you!

**Comment by abnerlee** [comment]
#1891 is more discussed.
