### ISSUE TITLE
"Smart Quotes" (with "Convert on Input" on) and "Auto pair brackets and quotes" conflict

### ISSUE THREAD

**Issue by dahjelle** [typora/typora-issues#1860]
I have a problem with the “Smart Quotes” (with “Convert on Input” on) setting and the “Auto pair brackets and quotes” setting also on. It appears that the “overwrite” feature of the second quote doesn’t recognize the smart quote, so I end up writing two closing quotes.

![quotes](https://user-images.githubusercontent.com/156557/46830492-620a4a80-cd66-11e8-8e89-488b36cc15f9.gif)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by dahjelle** [comment]
Great! Thank you!!!!
