### ISSUE TITLE
😟 Typora appears to be getting less stable, more quirky, less performant

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1861]
Typora use to be rock-solid even though it had some bugs and incomplete Markdown support. In the past year a lot of fancy new features have been, and it seems that those have come at the expense of reliability and performance.

1. **Typing responsiveness**: For a text editor, this has to be a top priority. Typora now very frequently lags when I type. I have to stop typing so it can catch up.  Sometimes I can actually watch individual characters appear one by one. Pretty serious!

2. **Quirky behavior**:  For example, I was editing the end of a list, trying to delete the empty last item and close the list, and instead Typora pasted a copy of the prior item. This has happened a few times, in separate docs. Typora has long had quirky list editing behavior, and it seems to be getting worse, not better. Very frequently I have to go into source code mode to make something happen (like close a list).  

Normally I would just file a bug, but these sort of quirks and performance issues are common enough but unpredictable enough that it makes filing bug reports difficult. More importantly, it makes me lose confidence in how Typora is built under the covers... I'm worried that all the new features are being piled on and Typora's architecture or data model is becoming more and more spaghetti-like, undermining reliability. 

I yearn for a rock-solid WYSIWYG Markdown editor first of all. All the fancy features should be added to that without undermining it.

Just my 3¢.  Does anybody else feel the same?

**Comment by TomJansen** [comment]
Yes. With the latest build, lagging has become a serious problem. Can't even type one sentence in one go. And I have a pretty beefy laptop so that is not the problem.

**Comment by abnerlee** [comment]
@TomJansen The laggy is fixed in latest build, please try upgrade.

**Comment by vassudanagunta** [comment]
Thanks for improving the performance and stability @abnerlee !
