### ISSUE TITLE
Export to PDF exports outdated content from source mode

### ISSUE THREAD

**Issue by wamserma** [typora/typora-issues#1863]
OS: Win 7, 64bit
Typora: 0.9.58 (beta)

Reproduce:
1. Open new document in typora.
2. Enter `foo`.
3. Save as `foo.md`.
4. File -> Export to PDF, check PDF file.
5. In Typora, hit `Ctrl + #`
6. Add `# bar` on top of document
7. Hit `Ctrl + S` to save.
8. File -> Export to PDF, check PDF file.

Result: Heading `bar` is missing from PDF, but PDF has been updated according to timestamps.
Expected Result: Heading and Text show up in PDF.

Note: can be reproduced with any text. After switching back to WYSIWYG-mode export is fine.

**Comment by wamserma** [comment]
still reproducible with Typora: 0.9.65 (beta)

**Comment by abnerlee** [comment]
should be fixed already
