### ISSUE TITLE
Problem with uploading theme to Typora

### ISSUE THREAD

**Issue by 1nf0t3ch** [typora/typora-issues#1864]
I can't seem to upload the theme "lostkeys"

After opening the Theme Folder, I tried to move the contents across, but they refused to do so ie the 2 css files & lostkeys folder.

I am using macOS Mojave.

What am I doing wrong?

**Comment by abnerlee** [comment]
> After opening the Theme Folder, I tried to move the contents across, but they refused to do so ie the 2 css files & lostkeys folder.

You mean you cannot move files in macOS? It is not related to Typora, please refer 

<https://www.google.com.hk/search?safe=strict&ei=9mfBW6CMD4GR8gXD7YOQCA&q=+macOS+cannot+move+files&oq=+macOS+cannot+move+files&gs_l=psy-ab.3..33i160k1.6664.11208.0.11376.21.18.0.3.3.0.441.1980.5j5j2j0j1.13.0....0...1c.1.64.psy-ab..5.14.1798...0j0i67k1j0i131i67k1j0i7i30k1j0i12k1j0i10k1j0i13k1j0i30k1j0i8i30k1j0i8i10i30k1j0i10i30k1.0.iiWeRqPywQk>
