### ISSUE TITLE
an issue with copy math into MS Word (Windows).

### ISSUE THREAD

**Issue by views63** [typora/typora-issues#1869]
e.g.
![default](https://user-images.githubusercontent.com/175116/46963959-8e60f680-d0d9-11e8-962c-38f82276e6a8.png)
![default](https://user-images.githubusercontent.com/175116/46964003-acc6f200-d0d9-11e8-8dd7-455fe0559c29.png)
the mathematical formula split two part in word

**Comment by abnerlee** [comment]
seems not a bug.

Don't use `$\int_a^b f(x) x$`, use `$\int_a^b{f(x) x}$` to group the math correctly

**Comment by views63** [comment]
>Don't use $\int_a^b f(x) x$, use $\int_a^b{f(x) x}$ to group the math correctly
in latex $\int_a^b f(x) x$ is not problem,  can make it better in typora?
