### ISSUE TITLE
Ubuntu18.04 cannot input Chinese using ibus input method

### ISSUE THREAD

**Issue by SunnyMosquito** [typora/typora-issues#1872]

**Comment by abnerlee** [comment]
Typora and iBus version?

**Comment by specloli** [comment]
for me the typora is good with chinese, please check the permission

**Comment by specloli** [comment]
for me the typora is good with chinese, please check the permission

**Comment by SunnyMosquito** [comment]
sorry,I originally installed the snap version of the ubuntu store, it is not the official version, I just used the version installed by apt-get to use
