### ISSUE TITLE
Inserting image bug

### ISSUE THREAD

**Issue by Wangwj98** [typora/typora-issues#1873]
Suppose my current opening file is **dirctory1/mk1.md**. 
Then I switch to anther file called **directory2/mk2.md** and paste an image called **img.jpg** here.
Typora will copy my image to **directory1/mk1.assets** but not **directory2/mk2.assets**.

Of course, if I now re-open **mk2.md**, then paste the image, everything is fine. But doing this every time is ridiculous.

**Comment by DHclly** [comment]
I also find this bug. this is very serious。

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1811

Will be fixed in next version up
