### ISSUE TITLE
Soft page breaks are lost when exporting to PDF

### ISSUE THREAD

**Issue by lucidBrot** [typora/typora-issues#1874]
![edit](https://user-images.githubusercontent.com/4920691/47031612-82744380-d170-11e8-94f5-6213c6f6e564.png)
![render](https://user-images.githubusercontent.com/4920691/47031613-82744380-d170-11e8-9cbb-598105bf21e4.png)
[Bug.md.txt](https://github.com/typora/typora-issues/files/2484003/Bug.md.txt)
[Bug.pdf](https://github.com/typora/typora-issues/files/2484000/Bug.pdf)

There is a soft newline after the comma, and a hard newline after the first sentence's dot. 
You can see in the image how it looks in typora preview - this is what I expect to see in the exported PDF again. But there, the soft newline is completely ignored.  

version 0.9.58 (beta)
Typora for Windows / Linux
Win 10 64-bit Pro

**Comment by abnerlee** [comment]
Whether to preserve soft break or not is configured in preference panel

**Comment by lucidBrot** [comment]
Thanks! 
Even now, I almost didn't find it since I was looking for an "Export" heading. For future visitors: The setting is almost in the middle of the preferences page, and it's title is "Whitespace / Line Break"

![pref](https://user-images.githubusercontent.com/4920691/47135392-5069fb00-d2b0-11e8-9ede-ae46f85b6c46.png)

@abnerlee Did I change something or is it the default setting that the two options (When Writing vs Export/Print) are not both the same? If they aren't, it might be worth changing the default such that you get what you see when you export.
