### ISSUE TITLE
Elastic Tabstops Feature Request

### ISSUE THREAD

**Issue by martzell** [typora/typora-issues#1876]
Elastic Tabstops are great. The most natural way to insert tables. Try it out with https://multimarkdown.com/composer4/

Tables are what tabstops exist for; original. http://nickgravgaard.com/elastic-tabstops/ describes the implementation with code.

Any plans to include it in the Typora editor?

**Comment by abnerlee** [comment]
We are less likely to support this since Tables are auto aligned in HTML in preview mode.
