### ISSUE TITLE
[Need Help] Nested Lists Indentation

### ISSUE THREAD

**Issue by yanzhang0219** [typora/typora-issues#1877]
I set the indent size to 4 spaces without pretty indentation, shown below:

![image](https://user-images.githubusercontent.com/11582667/47077116-1962ef00-d1b5-11e8-9ee3-739c326292fe.png)

And then I restart Typora to test it, but the nested list is still indented to 2 spaces, not 4 spaces, shown below:

![image](https://user-images.githubusercontent.com/11582667/47077252-63e46b80-d1b5-11e8-85c9-4585faa54185.png)

Then I set the pretty indentation, the indentation becomes 4 spaces but correspondingly the number of spaces following the list marker becomes 3 spaces, not 1 space, shown below:

![image](https://user-images.githubusercontent.com/11582667/47077834-afe3e000-d1b6-11e8-8fba-f16fce504086.png)

I am wondering how to set the indention to 4 spaces but the number of spaces following the list marker is still 1 space? 

My purpose is to make .md file can be compatible with most markdown processor so that on my iPhone, I can use some other App like 1Writer to open this .md file with a correct render. Because most markdown processors treat a sublist as it is indented further 4 spaces. 

Thank you very much.

**Comment by yanzhang0219** [comment]
@abnerlee Please help~~~ Many thanks.

**Comment by yanzhang0219** [comment]
@abnerlee

**Comment by abnerlee** [comment]
The option should be 4 space indent without the pretty option.

This looks like a bug ~

**Comment by yanzhang0219** [comment]
@abnerlee Okay. Thank you. Looking forward to your release to fix it up.

**Comment by abnerlee** [comment]
should be fixed in new release
