### ISSUE TITLE
paragra before a code block automatically render as another code block

### ISSUE THREAD

**Issue by yangqinj** [typora/typora-issues#1878]
The paragraph text just before a code block below it is automatically rendered as another code block when reopen the markdown file.

text in a graph
```
code block
```

The "text in a graph" is automatically rendered as a code block. (There is no blank line between them)
```
text in a graph
```
```
code block
```

**Comment by abnerlee** [comment]
I'm not able to reproduce this. Could you provide Typora version and sample *.md file that are rendered in correctly?
