### ISSUE TITLE
Edit tables more easily / Move text more easily

### ISSUE THREAD

**Issue by martzell** [typora/typora-issues#1879]
Currently we can move a table row or column with ctrl cmd arrow key (there is some quirk it beeps on my Mac). This should also work with  paragraphs and especially useful for list entries. Left/right should decrease/increase indentation.

There is no easy way to insert a column without Apple Touch Bar. alt cmd arrow key could insert a row or column before or next.

Try it in Mac app: Texts.

I've found only now the table menu in the context menu. Unfortunately the keyboard shortcuts I've set in Mac System Preferences » Keyboard does not work. Please think about adding these commands to the menu bar.

That the resize table ui is also themed – with serif font and hanging numbers – looks a little bit strange.

**Comment by vidavidorra** [comment]
+1 for keyboard shortcuts to move around items in lists especially.

**Comment by abnerlee** [comment]
merge into #1088 and #2376
