### ISSUE TITLE
Hey,could you upload the release package to the ubuntu snap store

### ISSUE THREAD

**Issue by specloli** [typora/typora-issues#1880]
I am a ubuntu user and the official repository is too slow for me . I want  the auto upgrade feature too .
if the package is in the snap store , it will be great

**Comment by abnerlee** [comment]
duplicate with #1457

**Comment by skewty** [comment]
I believe this is unofficial (and it has some issues) but: https://snapcraft.io/typora-alanzanattadev

**Comment by skewty** [comment]
SNAP seems preferred over FlatPak because it supports more than just GUI apps (example SystemD services).

(Examples: JetBrains PyCharm, Spotify, PlexMediaServer, NextCloud, VisualStudioCode, VLC, Remmina, ...)
