### ISSUE TITLE
the disappeared [TOC]

### ISSUE THREAD

**Issue by BalanceUhen** [typora/typora-issues#1882]
Once I typed `[TOC]`, I typed a extra `]` by mistaken,like the image below:
![image](https://user-images.githubusercontent.com/21274779/47128413-a4320f80-d2c3-11e8-907b-13a1ba6f3b81.png)

Then if I pressed enter between the two `]`, I would get the `[TOC]` disappeared.
![image](https://user-images.githubusercontent.com/21274779/47128479-e8251480-d2c3-11e8-8df0-081f7e275548.png)

I have repeated several times.

Typora Version: 0.9.58
OS version: Windows 10

**Comment by abnerlee** [comment]
Fixed in new release
