### ISSUE TITLE
incorrect rephrasing of image captions

### ISSUE THREAD

**Issue by LionSR** [typora/typora-issues#1886]
When I incorporate latex code in image captions, for example:
`
![corresponds to $|-1\rangle$, $|0\rangle$ and $|+1\rangle$ in spin-1.](fig/un.pdf){#fig:unary width=45%},
`
sometimes when I save and reopen the markdown file, the $$ will be deleted automatically. The above line becomes:
`
![corresponds to |-1\rangle, |0\rangle and |+1\rangle in spin-1.](fig/un.pdf){#fig:unary width=45%},
`

This bug is extremely troublesome because I have to add $$ every time.

**Comment by abnerlee** [comment]
I cannot reproduce it, could you provide more details, and is the image in a table or something?

**Comment by LionSR** [comment]
Sorry for being too occupied to post a minimal example here. This issue do exisit.
For the following code:

```markdown
![The Einstein equation E=mc^2](figs/todo.pdf){#fig:QGM width=45%}

The probability distribution of a generative model can be modeled by $p_{\mathbf \theta}$. In training (or learning) phase, we determine parameters of the generative model from training
$$
D(p_{\mathcal D}||p_{\mathbf{\theta}})=-\sum_{\mathbf v}p_{\mathcal D}(\mathbf v)\log\left(\frac{p_{\mathcal D}(\mathbf v)}{p_{\mathbf \theta}(\mathbf v)}\right)
$$
```

![](https://ws1.sinaimg.cn/large/006tNbRwgy1fx53b49w9ij316y0hawn4.jpg)

First we render it. Note the equation in the caption got rendered as well as the equation in the text.

![](https://ws1.sinaimg.cn/large/006tNbRwgy1fx53b3sz57j30yq0ragua.jpg)

Then we switch back to source mode. The $$ pair in the caption got deleted automatically.

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fx53b30px8j314u0gqth2.jpg)

**Comment by abnerlee** [comment]
This should be ready fixed, could you check again?
