### ISSUE TITLE
Highlight formatter is not working on Mac

### ISSUE THREAD

**Issue by dineshbhagat** [typora/typora-issues#1888]
I used Typora version: Version 0.9.9.18.1 (1088)
on 
mac: MacOS High Sierra Version 10.13.6

I tried to format String as below
Select Text, choose Format option -> Highlight

If I check in source code mode, typora adds ==text-to-be-highlighted== but its not working as you can check in the following image.
I referred StackOverflow suggestion and added \<mark>text-to-be-highlighted\</mark>, this worked fine. Please check 'Yellow' color text in following image.

Text:

Notice: monitorenter and \<mark>monitorexit\</mark>, its ==scope== of synchronized ~~block~~

In source code mode

<img width="897" alt="screen shot 2018-10-22 at 3 43 31 pm" src="https://user-images.githubusercontent.com/3823705/47287895-71648000-d611-11e8-80c9-baacf116cf06.png">

In preview mode

<img width="892" alt="screen shot 2018-10-22 at 3 43 18 pm" src="https://user-images.githubusercontent.com/3823705/47287896-71fd1680-d611-11e8-9567-adc547b83da0.png">

Text Highlight solution from [SO](https://stackoverflow.com/a/36039773/2987755)

**Comment by abnerlee** [comment]
We will hide "highlight" menu, if highlight syntax (== ==) it not enabled in preferences panel.
