### ISSUE TITLE
Latex export not working

### ISSUE THREAD

**Issue by IanJermyn** [typora/typora-issues#189]
Export to all formats other than Latex opens a Save window, produces good results. Export to Latex does not even open a Save window. This is true for trivial files and for more complex documents. Are there constraints on the markdown for this export to work?  

Windows 7, Typora version 0.9.9

**Comment by abnerlee** [comment]
I cannot reproduce this one,

Possible to send us (<hi@typora.io>) a sample file that cannot be exported as LaTeX ?

**Comment by abnerlee** [comment]
fixed
