### ISSUE TITLE
Word count is counting contractions as two words

### ISSUE THREAD

**Issue by jessicashortt** [typora/typora-issues#1891]
On OS X, (English) word count is noticeably off and that's because it's counting a contraction like **don't** as two words.

**Typora**
<img width="857" alt="typora" src="https://user-images.githubusercontent.com/4721441/47436999-071d1e00-d77e-11e8-85a4-3edb258a20ad.png">

**Byword**
<img width="792" alt="byword" src="https://user-images.githubusercontent.com/4721441/47437003-097f7800-d77e-11e8-81c8-dd0ff6c49338.png">

**Word**
<img width="853" alt="word" src="https://user-images.githubusercontent.com/4721441/47437010-0f755900-d77e-11e8-8d09-66baa8de8270.png">

**Pages**
<img width="1019" alt="pages" src="https://user-images.githubusercontent.com/4721441/47437018-1308e000-d77e-11e8-9c22-34edb5f826b4.png">

**Comment by AlexPasternak** [comment]
All I have to say is 't 't 's 've 't 't. And you say those aren't real words!

**Comment by jessicashortt** [comment]
It's a problem with the apostrophe counting it as two because it's the same with possessive nouns (**cat's** is counted as two words and that is definitely one). I think because all tools count it as one, that is the standard. A contraction is basically defined as two words made into one and should be treated as one

**Comment by abnerlee** [comment]
should be fixed
