### ISSUE TITLE
Typora can not open .md files under ubuntu

### ISSUE THREAD

**Issue by sudoyang** [typora/typora-issues#1892]
After the most recent upgrade, I tried to double click .md files to open them but failed. Typora just pops up and then shuts down automatically very fast. I am running Ubuntu 16.04 and the Typora version is 0.9.59. Btw, just to open Typora itself is perfectly fine.

**Comment by gbegin** [comment]
Running Ubuntu 14.04,  Typora version is 0.9.59. Same behaviour when right-clicking and  Open with Typora.

**Comment by abnerlee** [comment]
Can confirm this, use `sudo typora xxx.md` also works file. 

Very strange bug. We will fix it in next version up asap.

**Comment by abnerlee** [comment]
We pushed a fix release on v0.9.60
