### ISSUE TITLE
Spell check fails when a word contains an accented letter

### ISSUE THREAD

**Issue by martin-grand** [typora/typora-issues#1895]
I think it's an encoding issue. I have tried the Hungarian spell check, and every word that contains at least one accented letter is underlined.

**Comment by abnerlee** [comment]
What's your operation system, could you give a sample md file or content in Hungarian?

**Comment by martin-grand** [comment]
I think the main problem is in the encoding because this file has a lot of character what the Hungarian language is not containing. For example "Ăźvegfal" is wrong, the correct one is "Üvegfal", so the accented letters like Ü is written like "Ăź". I have found a correct encoded original file here: https://sourceforge.net/p/apertium/svn/48853/tree/incubator/apertium-hun/dev/hu_HU.dic

**Comment by abnerlee** [comment]
I see, so if you download the  hu_HU.dic and hu_HU.u8.aff from https://sourceforge.net/p/apertium/svn/48853/tree/incubator/apertium-hun/dev, then rename hu_HU.u8.aff to hu_HU.aff, and them put them to C:\Users\{username}\AppData\Roaming\Typora\dictionaries\ would it be fixed?

**Comment by abnerlee** [comment]
using https://sourceforge.net/p/apertium/svn/48853/tree/incubator/apertium-hun/dev in our dictoinaries site now.
