### ISSUE TITLE
Exiting display math messes up inline math

### ISSUE THREAD

**Issue by cakeflyer** [typora/typora-issues#1896]
After editing some displaymath ($$) and exiting the environment, random chunks of inline math get repeated or just disappear. A workaround is to select all and copy paste - then the math renders properly. 

example:
![ss 2018-10-25 at 11 12 44](https://user-images.githubusercontent.com/8405636/47510810-7d6b6e80-d8ab-11e8-91b3-5805bc139a14.png)

_Windows 10 Home, Typora 0.9.59_

**Comment by abnerlee** [comment]
Possible to attach or send us (<hi@typora.io>) the sample file ?

**Comment by cakeflyer** [comment]
it's just a rendering issue, the text doesn't actually get repeated in the file though it appears like it does - interesting to note is that closing and opening the file makes it go away, and you can't replicate it by entering then exiting the previous display math environments - you have to continue typing new stuff and new environments before it happens (i can't seem to get it to happen consistently, but i've experienced it many times)

also, there's this thing where it repeats more and more over time (e.g. in the first line in the image above, there are 5 'A's that render, though when the bug first occurs, there are only 2, then 3, etc.)



[gramian.zip](https://github.com/typora/typora-issues/files/2517198/gramian.zip)

**Comment by abnerlee** [comment]
We pushed a fix release on v0.9.60
