### ISSUE TITLE
Typora 0.9.59-1 not working under Ubuntu 14.04

### ISSUE THREAD

**Issue by gbegin** [typora/typora-issues#1897]
After the most recent upgrade to version 0.9.59, under Ubuntu 14.04, nothing gets drawn in Typora's window. Whatever was in the background when the window is opened remains there. With a different installation of the same version on a 32 -bit machine under Ubuntu 16.04, everything seems normal.

**Comment by abnerlee** [comment]
#1892

**Comment by gbegin** [comment]
The problem is still there with 0.9.60
