### ISSUE TITLE
Error occured when new file.

### ISSUE THREAD

**Issue by smartBun** [typora/typora-issues#1899]
1. Right click and new file.(aaa.md)
2. A dialog will pop up.(Error. ENOENT: no such file or directory. open "C:\\****\Untitled.md")
3. Click confirm button. There is a new file named Untitled.md was created. And you can see it in the file list, but aaa.md does not create.
4. Refresh the file list.  aaa.md will show in the file list. But the edit window still Untitled.md,
5. Click the aaa.md.  A confirm dialog will popup.
6. Click abondon. Typora will show nothing. You can not see the file list and edit panel. Even, you can not see the close, minimum, maximum button.

**Comment by fandean** [comment]
+1
> version  0.9.59(beta)
Windows 10 64 Bit

**Comment by abnerlee** [comment]
We pushed a fix in 0.9.60
