### ISSUE TITLE
Please fix undo and redo.

### ISSUE THREAD

**Issue by smallx** [typora/typora-issues#190]
If I undo and then redo, sometimes part of the content will be lost. I think undo and redo should be like `Stack`(FIFO).

Please fix it. Thanks.

**Typora 0.9.8 for Windows**

**Comment by vassudanagunta** [comment]
Don't you mean "fix" undo/redo? What you describe sounds like a serious bug.

**Comment by smallx** [comment]
Yep, I have changed the title. I'm looking forward to fix it. :smiley:

**Comment by abnerlee** [comment]
@samllx: could you write down some steps to reproduce the content lost ?

**Comment by smallx** [comment]
Yep, I tested also in Typora 0.9.10 for Windows, I find that usually happen in **Chinese**.

As the following picture, there are 3 problems:
- sometimes can not undo.
- sometimes can not redo.
- undo so many steps.

![default](https://cloud.githubusercontent.com/assets/16517035/16066666/e29a8eb0-32e7-11e6-873e-bf2cbc9ee775.gif)

**Comment by abnerlee** [comment]
@smallx What's your OS version and IME ?

**Comment by smallx** [comment]
@abnerlee 

- Windows 8 x64
- Baidu IME(http://shurufa.baidu.com/)

I just found something that surprised me. In fact, this problem is related to #172 .
When I use Microsoft Chinese IME, there are no the above problems. But there are still problems for punctuation(`，` and `。` and so on). See the following picture:
![default](https://cloud.githubusercontent.com/assets/16517035/16067583/7f86760a-32f0-11e6-8881-ad65bf4fed0c.gif)

**Comment by abnerlee** [comment]
#172

**Comment by abnerlee** [comment]
merge this into https://github.com/typora/typora-issues/issues/172
