### ISSUE TITLE
Windows 0.9.59(beta) UI semi-hangs for some md files

### ISSUE THREAD

**Issue by dukhat2259** [typora/typora-issues#1900]
I have tested on three md files. Two of those hangs some internal logic in Typora.
1. Open Typora and select About or Preferences in the menu -> Works as expected
2. In menu recent files open good-file.md
3. Select About or Preferences in the menu -> Works as expected
4. In menu recent files open bad-file1.md
5. New window pops up. Title says bad-file1.md. Window is blank. About, Preferences or most other menu items do absolutely nothing.

**Comment by abnerlee** [comment]
We pushed a fix release on v0.9.60
