### ISSUE TITLE
c++ template indent problem 

### ISSUE THREAD

**Issue by selaselah** [typora/typora-issues#1901]
typora version: 0.9.9.19
OS: macOS mojave
in code block, indent of a normal function is correct. for example:
```cpp
int foo() {//<- type enter
  //<-  cursor will indent with spaces
}
```

normal template are corrent too
```cpp
template<typename T>
int foo() {//<- type enter
  //<- cursor here
}
```

buf if the underscore in the templated, all indent is wrong. eg1:
```cpp
template<tpyename T_I>
int foo() { //<- type enter
//<- wrong cursor
}
```

and worse, the wrong indent will impact inner code block. eg2:
before hit enter
```cpp
template<typename T_I>
int foo() {//<- type enter
  if (bar) { /*cursor*/ } // wrong indent, then type spaces and statements
}
```
after hit enter, inner indent impacted
```cpp
template<typename T_I>
int foo() {
if (bar) { //<- after hit enter, heading spaces are auto removed
//<- cursor here, the `if` statements's indent are also impacted.
}
}

**Comment by abnerlee** [comment]
e.g.1 is fixed, e.g.2 is not, but "inner indent impacted" won't happen

So I'm closing since Typora is not a code editor, such issue does not cause too much trouble.
