### ISSUE TITLE
Being asked for access to kCountlyStoredDeviceIDKey in Keychain after start of 0.9.9.19

### ISSUE THREAD

**Issue by kontrafiktion** [typora/typora-issues#1902]
After installing the latest version, I get asked to allow Typora access to kCountlyStoredDeviceIDKey.
After some googling (https://github.com/Countly/countly-sdk-ios) I assume this is harmless, but it would be better with some explanation before being asked to allow access to a value in the keychain that – at first look – does not seem to have anything to do with Typora

**Comment by abnerlee** [comment]
We didn't notice this behavior for countly-sdk. We will remove it in next version up.

For now, just deny the access to keychain is fine
