### ISSUE TITLE
A invisible equation

### ISSUE THREAD

**Issue by BalanceUhen** [typora/typora-issues#1904]
Once I had finished typing a letter in inline math style,like the image below:
![image](https://user-images.githubusercontent.com/21274779/47566997-e9a7aa00-d95f-11e8-99da-1639d6c2fa20.png)
then I moved the cursor two letters right, and I found the letter became invisible 😰 , like this image below:
![image](https://user-images.githubusercontent.com/21274779/47567105-33909000-d960-11e8-8bd9-34387b3d1d6a.png)
Things became normal after typora restarted.

Typora Version: 0.9.59
OS version: Windows 10

**Comment by abnerlee** [comment]
We pushed a fix release on v0.9.60
