### ISSUE TITLE
Cursor position arrive the beginning of the line incorrectly 

### ISSUE THREAD

**Issue by myuanz** [typora/typora-issues#1905]
When I write something behind `$P_1和P_2$`, the cursor will arrive the beginning of the line, I found this bug. It did not happen in the previous version.  

According to my test, the error only happens if `\$\w_\d[\u4e00-\u9fa5]\w_\d\$` in this line, maybe there are other methods can touch off this bug, but I am too lazy to find.

```
Win10 1803  
0.9.59
```
![demo2](https://user-images.githubusercontent.com/25359546/47568397-95062e00-d963-11e8-9799-00a4b457d3c2.gif)

**Comment by abnerlee** [comment]
We pushed a fix release on v0.9.60
