### ISSUE TITLE
Newly created document not displayed in Typora file structure

### ISSUE THREAD

**Issue by nolindom** [typora/typora-issues#1906]
This was working properly with previous release. The actual installed version is 0.9.59(beta).

When I create a new document from within Typora File structure, I get asked to provide a name for it. 

When done, the name which apprears in the Typora structure is "Untitled.md".

If I click the file it gives an error (because the file has really been renamed in disk)

If I want to see the new file in Typora file structure, I need to either close the app or use the "Refresh Folder" option at bottom of panel.

I'm on French Windows 7.

Thanks.

**Comment by abnerlee** [comment]
We pushed a fix release on v0.9.60

**Comment by nolindom** [comment]
Great! Thank you!
