### ISSUE TITLE
Typewriter Mode [F9] can't be off

### ISSUE THREAD

**Issue by JARVIS-AI** [typora/typora-issues#1907]
**OS** : macOS High Sierra 10.13.6
**App version** : Version 0.9.9.19.1 (1301)
**Hardware** : Mac Book Pro 2018 TouchBar

First thanks for the great godlike markdown app
Then
Just 10 minute ago I updated Typora the last version, from previous version
And for testing all things I click on `view > typewriter mode [f9]`

and when there is a notification bar on the Typora said that the option is on
when i click it again the typewriter mode can't be off / even test with shortcut F9 button but not work
and even when i quite the app and again open it the typewriter mode is on

Exit and open again not work
reset not work

Something wrong i think

if I'm wrong, you can delete this issue
but for me i'm sure these is something wrong.

Thanks in Advance

**Comment by JARVIS-AI** [comment]
**Update**
Typewriter going to off by reinstalling but after that again the issue appear.

**Comment by abnerlee** [comment]
> when i click it again the typewriter mode can't be off / even test with shortcut F9 button but not work

Do you mean typewriter mode cannot be turned off or the notification cannot be turned off? (you bug report reminds me an UX issue that turn off typewriter mode does not close the notification automatically.)

You could try click menu `view > typewriter mode` to toggle typewriter mode. When the menu item is unchecked, typewriter mode is turned off, and restart will not show the notification either

**Comment by JARVIS-AI** [comment]
No not notification,
Btw
In after reinstalling again the typewriter mode check icon not be appear even when is enabled 
the previous bug is about the typewriter mode can't be off and option is not work even when i click it
but now that bug is gone and typewriter mode is working well but check icon and notification is not work anymore 
I think its UX Issue in mac menu bar that check icon is not appear ?

**Comment by JARVIS-AI** [comment]
Its worth to see this

![bug](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Bugs/Typora/typora-bug.gif)
