### ISSUE TITLE
Add automatic direction changer in processor

### ISSUE THREAD

**Issue by JARVIS-AI** [typora/typora-issues#1908]
I'm going to add a javascript script that when a user type English the writing process will be ``LTR``
and when user writing arabic/persian/other rtl languages the writing mode process will be ``RTL`` automatically

I've done the CSS Trick but it's useful for only rtl languages and if you select the rtl theme then is not useful for english anymore and you must change the them again

Ive write a simple script to automation this trick with single theme but need to add script somewhere
to process this

Can you help me ?
Thanks

------
**Update**

And ive read this issue too but I think that is different 
https://github.com/typora/typora-issues/issues/388

**Comment by abnerlee** [comment]
It is not supported, maybe we could allow empty line and markdown syntax in HTML block, so user would be able to use `<div dir='rtl'>` and `</div>` to wrap RTL content.

Anyway, this is a duplicate issue with #1696
