### ISSUE TITLE
Cannot display title in MacOS Mojave Dark Mode

### ISSUE THREAD

**Issue by BrandoZhang** [typora/typora-issues#1909]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/23352923/47614916-85f9ba00-dae2-11e8-88f9-15662b4f24f5.png">

On macOS MojaveIn dark mode, version 0.9.9.19 (1301) cannot display the title (it is white by default). And it is hard to see the icons on the top right.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/23352923/47614932-d1ac6380-dae2-11e8-9615-9d3e3d79b4b1.png">

It seems that only `Night Theme` works in Dark Mode?

**Comment by abnerlee** [comment]
Which theme did you use in picture 1?

Can restart Typora help?

**Comment by BrandoZhang** [comment]
> Which theme did you use in picture 1?
> 
> Can restart Typora help?

As I said, all the themes with white background (so `Night Theme` is the only one that innocent) have this problem, which include `Academic`, `GitHub`, `Gothic`, `Newsprint`, `PixyII`, `Vue` and `Whitey`.

Unfortunately, restart Typora dosen't help anything.

Thanks for your rapid response.

**Comment by abnerlee** [comment]
Fixed in new release
