### ISSUE TITLE
How to do internal links?

### ISSUE THREAD

**Issue by FelixHerz** [typora/typora-issues#191]
I am wondering how internal links are made in typora.

I tried

```markdown
[Database](#the-database)
## The database
```

I also tried
```markdown
[Database](#the-database)
## The database <a id="the-database"></a>
```

Neither of them worked.

**Comment by FelixHerz** [comment]
https://gist.github.com/asabaylus/3071099

**Comment by abnerlee** [comment]
``` markdown
[Database](#the-database)
## The database
```

This is the correct way, if not working, then it is a bug

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by OmarElsheikh1** [comment]
[Name that will appear](#The section name you want to link this to)

> **Important:** Use **Ctrl+Click** to use it

**EX**
`[JSON](#What is JSON)`

![1](https://github.com/typora/typora-issues/assets/115443056/c4e5bede-e868-48a8-8868-7b5fe1cfbce2)
![2](https://github.com/typora/typora-issues/assets/115443056/3f28d2a1-e48c-4e16-bc1d-fc106866930e)
![3](https://github.com/typora/typora-issues/assets/115443056/99133faf-47fb-4b59-ba3f-08eee65bc291)
