### ISSUE TITLE
Customize table cells width

### ISSUE THREAD

**Issue by itsmysterybox** [typora/typora-issues#1913]
I'm creating a theme for Typora. I'm trying to customize table cells width. I can define `max-width` for table. But can I define any such property for specific cells?

Now, all the cells are equally distributed. Can I give custom width to specific cells or there could be a new built-in feature for **resizing table cells** with handles?

**Comment by abnerlee** [comment]
We don't have plans for "resizing table cells", it is not supported by Markdown.

About resize table cells by CSS, 

According to the [definition of max-width](http://www.w3.org/TR/CSS21/visudet.html#propdef-max-width) in the CSS 2.1 spec, “the effect of 'min-width' and 'max-width' on tables, inline tables, table cells, table columns, and column groups is undefined.” So you cannot directly set max-width on a td element. (from <https://stackoverflow.com/questions/8465385/how-can-i-set-the-max-width-of-a-table-cell-using-percentages>)

There should be other workarounds, but I'm not sure about your specific styling requirements.
