### ISSUE TITLE
Links to images

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#1914]
Since updating to version 0.9.60 I find that regularly a link to an image initially renders the image, but then, for some unknown reason, it reverts to the link syntax. If I put my cursor on the syntax and press enter then the image is returned. But this can revert back to the syntax.

**Comment by abnerlee** [comment]
what is "a link to an image", is it something like `[![img](src)](href)` ? 

It will show the link syntax when caret is inside it, which is correct.

So would you provide more details like the expected output and actual one?
