### ISSUE TITLE
math formatting doesn't work, menu is hidden unless cursor is over it

### ISSUE THREAD

**Issue by fanxilsa** [typora/typora-issues#1915]
typora version: 0.9.60 (beta)
OS: ubuntu 18.10 

The math formatting with $ doesn't seem to work, and the menu is also hidden unless the cursor hovers over the area. Screenshot is attached.

![screenshot from 2018-10-30 06-58-54](https://user-images.githubusercontent.com/44587278/47676674-5d241280-dc11-11e8-9e5a-3ba24b43b58d.png)
![screenshot from 2018-10-30 06-59-01](https://user-images.githubusercontent.com/44587278/47676682-5f866c80-dc11-11e8-8eb7-e89820f3d341.png)

**Comment by abnerlee** [comment]
Please enable inline math in preferences panel.

**Comment by fanxilsa** [comment]
Thanks, that fixed it. However, the other problem still persists. The menu doesn't appear at all unless I hover my cursor above it.

**Comment by abnerlee** [comment]
#1738

**Comment by abnerlee** [comment]
#1662

**Comment by abnerlee** [comment]
#1510
#1507

**Comment by abnerlee** [comment]
#1506
