### ISSUE TITLE
Scrolling during code fence language selection does not scroll combo box

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#192]
If you're in the language picker for a code fence (which I have to be often since my improvement suggestion got rejected :-) ), which is typically shown _below_ the fence, and you scroll the document, e.g., with the mouse wheel, the language combo box picker stays where it is while the rest of the document travels. This looks like a visual bug:

<img width="413" alt="capture" src="https://cloud.githubusercontent.com/assets/1819485/16094274/76d282e8-330d-11e6-966b-ece082163e6e.png">

Expected behavior would be either to scroll the picker with the document, or to close the picker.

**Comment by abnerlee** [comment]
Should be fixed in new version
