### ISSUE TITLE
Unable to start indented list

### ISSUE THREAD

**Issue by unisons** [typora/typora-issues#1922]
* Level-0 A
* Level-0 B
  * Level-1 A

| dkfjkjas  | adklfjlkjasd |
| --------- | ------------ |
| asdklfjkj | dsf          |

  * Level-1 B

"Level-1 B" line should be indented, I think. Because there is spaces before `*`.
Actually I am not sure it is not possible in markdown syntax. But it seems to be working.

**Comment by abnerlee** [comment]
the output is same with github
