### ISSUE TITLE
Menu invisible on Linux

### ISSUE THREAD

**Issue by fanxilsa** [typora/typora-issues#1923]
OS: Ubuntu 18.10
Typora version: 0.9.60

Screenshot is attached below. EDIT: Actually, there is a faint outline of the words, but I'm not sure if this was intended.

![screenshot from 2018-10-30 18-12-55](https://user-images.githubusercontent.com/44587278/47701945-9db27900-dc6f-11e8-9c6c-df5ad640fd46.png)

_Originally posted by @fanxilsa in https://github.com/typora/typora-issues/issues/1915#issuecomment-434194502_

**Comment by abnerlee** [comment]
caused by https://github.com/electron/electron/issues/15194

**Comment by Wangwj98** [comment]
Totally same problem on Manjaro 18.01.
There is another bug; after you typed some words in a new opened typora window, the window cannot be closed and cannot be found in system monitor unless you save the file.

**Comment by wxk6b1203** [comment]
I think you should update from upstream dependency. Thank you!
![default](https://user-images.githubusercontent.com/8924149/49417647-8ceaab00-f7b9-11e8-839c-d759221c1a8b.png)

**Comment by cabreraalex** [comment]
I'm having the same issue on newest install of Typora

**Comment by vdegove** [comment]
I confirm this in Ubuntu 18.04. I'm using the Ubuntu community-theme for my desktop.

**Comment by Wangwj98** [comment]
Well, this issue has been open about 2 months.
The bug has actually been fixed by `electron group`, but not yet added to any stable release yet, at least not in the current newest release `electron  3.0.10-1`. 
see #15878.

**Comment by joshcangit** [comment]
I wouldn't consider this a bug, more of a visual glitch. So this issue will be solved once the fix is available right?

**Comment by abnerlee** [comment]
Should be fixed in new release

**Comment by joshcangit** [comment]
Yes, I can confirm that this is fixed.
![new typora](https://user-images.githubusercontent.com/33022160/51026742-278f9400-1587-11e9-91d0-e35a666737c3.png)
