### ISSUE TITLE
Cannot resize the page

### ISSUE THREAD

**Issue by Wangwj98** [typora/typora-issues#1924]
I remember that I can resize the whole page with `ctrl + '+' or '-'` and `ctrl + wheel`(maybe?) in Typora.
**But now this feature has gone.**
What the  `ctrl + '+' or '-'` does right now is to change the level of headings.
This is weird!!!
Is there any way I can resize the whole page?

**Comment by abnerlee** [comment]
You could resize from `view` menu, and can check shortcut key there
