### ISSUE TITLE
Wrong word count for bullet and numbered lists

### ISSUE THREAD

**Issue by dramforever** [typora/typora-issues#1926]
Typora, when given these three documents, produces word count of 5, 15 and 25 respectively, while apparently there are only 5 words in each document:

```markdown
w1 w2 w3 w4 w5
```

```markdown
- w1 w2 w3 w4 w5
```

```markdown
- - w1 w2 w3 w4 w5
```

Replacing bullet lists with numbered lists (`s/-/1./`) gives identical counts.

Observation: If you do 'select all' on the third document, Typora reports '5/25 words' selected. So I think this is specific to whole-document word counting.

---

Version: 0.9.60

**Comment by tbowan** [comment]
Encountered same problem here with typora 0.9.60. Every bullet list adds several words.

Using "ctrl + a" (i.e. select all) produce two number the first one of them being more accurate.

**Comment by dajare** [comment]
This must explain the discrepancies I have been noticing when I export my `*.md` files from Typora to ODT format. LibreOffice gives a VERY different word count, and I was going to report it, but it looks like this is the same bug.

In my case, the running total that Typora reports is hugely inflated, although when I "select all" the **selection** count tallies (close enough) with the number that LibreOffice reports:

### Typora report:

![typora](https://i.imgur.com/3LAWZjz.png)

### LibO report (same text, copy/pasted):

![libo](https://i.imgur.com/f4LhSi0.png)

I do make generous use of bulletted and numbered lists, although I hadn't noticed a correlation between lists and the inflated word-count.

**Comment by abnerlee** [comment]
Fixed in new release
