### ISSUE TITLE
Support Catalog Specimens

### ISSUE THREAD

**Issue by MaluNoPeleke** [typora/typora-issues#1927]
I would like to use Typora as an editor for [Catalog](https://www.catalog.style/).
This works pretty well for normal markdown things (font formatting) but when it comes to some more complex things (tables, images etc.) Catalog uses specific [specimens](https://docs.catalog.style/specimens) for this.
Is it somehow possible to make use of it automatically with Typora without enabling source mode all the time?

**Comment by abnerlee** [comment]
You could input specimens in Typora' normal mode without switching to source mode. 
For native support, may relates #162
