### ISSUE TITLE
give some sort of feedback when saving

### ISSUE THREAD

**Issue by livia-b** [typora/typora-issues#193]
I am trying typora 0.9.10 on Windows and I am quite impressed. It would be nice to have some sort of feddback when pressing the save button, as it is  now the pressing the button is just the same as hovering with the mouse (and the open button is still highlighted) and it's not clear if the saving was successful

I hope the screenshot explains better:

![savebutton](https://cloud.githubusercontent.com/assets/2368524/16112836/87f28e22-33b9-11e6-9e22-820e6498ae37.png)

**Comment by abnerlee** [comment]
Fixed in new verion
