### ISSUE TITLE
Unable to open folders

### ISSUE THREAD

**Issue by irgendwr** [typora/typora-issues#1932]
Typora version: 0.9.60 (beta)
OS: Manjaro (Linux/Arch) 18.0.0, Kernel: 4.19.0

The "open-folder" dialog partially freezes (I'm unable to use the mouse).
I'm unable to open folders, even without the dialog; every time I try to the following error appears in the Developer Console:

> ELECTRON_ASAR.js:166 Uncaught Error: The module '/usr/share/typora/node_modules/pathwatcher/build/Release/pathwatcher.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 64. This version of Node.js requires
> NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
>     at Object.Module._extensions..node (module.js:671:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:504:12)
>     at Function.Module._load (module.js:496:3)
>     at Module.require (module.js:586:17)
>     at Module.require (file:///usr/share/typora//window.html:234:25)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/share/typora/node_modules.asar/pathwatcher/lib/main.js:4:13)
>     at Object.<anonymous> (/usr/share/typora/node_modules.asar/pathwatcher/lib/main.js:266:4)
>     at Object.<anonymous> (/usr/share/typora/node_modules.asar/pathwatcher/lib/main.js:268:3)
>     at Module._compile (module.js:642:30)
>     at Object.Module._extensions..js (module.js:653:10)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:504:12)
>     at Function.Module._load (module.js:496:3)
>     at Module.require (module.js:586:17)
>     at Module.require (file:///usr/share/typora//window.html:234:25)
>     at require (internal/module.js:11:18)
>     at n.end (file:///usr/share/typora//app/window/frame.js:1:349308)
>     at n.onRootChanged (file:///usr/share/typora//app/window/frame.js:1:349905)
>     at n.setMountFolder (file:///usr/share/typora//app/window/frame.js:1:350287)
>     at <anonymous>:2:60
>     at EventEmitter.electron.ipcRenderer.on (/usr/lib/electron/resources/electron.asar/renderer/web-frame-init.js:36:30)
>     at emitMany (events.js:147:13)
>     at EventEmitter.emit (events.js:224:7)

**Comment by abnerlee** [comment]
see #1897

Please follow https://support.typora.io/Typora-on-Linux/ to download the binary build for Typora
