### ISSUE TITLE
Cannot display inline styles

### ISSUE THREAD

**Issue by chrt** [typora/typora-issues#1933]
> Markdown tags for inline styles, such as `**` will be hidden or displayed smartly.

There are 5 themes by default: Github, Newsprint, Night, Pixyll, Whitey.

However, expect for Night and Whitey, tags for inline styles will be hidden but cannot be displayed.

My OS is Ubuntu, and I installed from `apt-get`. The version is 0.9.60 (beta).

Thank you!

**Comment by abnerlee** [comment]
>  tags for inline styles will be hidden but cannot be displayed.

Could you provide an example?
