### ISSUE TITLE
Failed to render in same cases

### ISSUE THREAD

**Issue by IsaacXen** [typora/typora-issues#1934]
The Following markdowns:

```markdown
_**Note:** `sum(_:_:)` returns the sum of two given parameters._

***Note:** `sum(_:_:)` returns the sum of two given parameters.*

_`https://` means HTTP over TLS, with a `:` before `//`, not `_`._
```

can not be rendered properly.

I'm expecting something like this:

```html
<em><strong>Note:</strong> <code>sum(_:_:)</code> returns the sum of two parameters.</em>

<em><code>https://</code> means HTTP over TLS, with a <code>:</code> before <code>//</code> , not <code>_</code></em>
```

But here's how it looks like in Typora

<img width="458" alt="screen shot 2018-11-02 at 23 03 13" src="https://user-images.githubusercontent.com/16833681/47923158-a4e9b900-def3-11e8-9c0d-dff73717638b.png">

Sadly, if you tried

<img width="459" alt="screen shot 2018-11-02 at 23 04 18" src="https://user-images.githubusercontent.com/16833681/47923219-c185f100-def3-11e8-8402-9c532e317d4d.png">

to escape the underscore in the inline code, which did help in some way, failed to escape itself within the inline code.

---

macOS 10.14
Typora 0.9.9.19.1

**Comment by abnerlee** [comment]
merge into #1789
