### ISSUE TITLE
Menus aren't visible.

### ISSUE THREAD

**Issue by kojp** [typora/typora-issues#1935]
I use typora 0.9.60-1 on Manjaro Linux Cinnamon(17.1.12).
The titles of menus aren't visible because the color of its letters and background are almost the same.
![typora1](https://user-images.githubusercontent.com/44724640/47951461-868fc600-dfa4-11e8-8d21-853c23c043d8.png)

But only when typola loses focus, the letters are visible.
![typora2](https://user-images.githubusercontent.com/44724640/47951728-0ec39a80-dfa8-11e8-8080-77094bbf0db3.png)

If some css code  for custom theme makes the letters always visible, what code can it?

**Comment by abnerlee** [comment]
#1923
