### ISSUE TITLE
More natural Typewriter Mode

### ISSUE THREAD

**Issue by martzell** [typora/typora-issues#1936]
(\*)When reaching top or bottom of the view by keyboard or search navigation the view should scroll so the cursor is in the middle of the screen. As long as navigation is continued by keyboard or search the cursor should stay in the center and the content should scroll. When you reach to the mouse and place the textcursor by click there should no automatic scroll happen.\*

This is so natural it should system wide default behaviour, especially for single line text fields and lists very handy. Special Typewriter Mode is not needed.

**Comment by martzell** [comment]
Did you understand my feature request and what do you think about this more natural way of automatic scroll while navigating by keyboard?

Currently it is annoying that in typewriter mode the content scrolls away from the point you clicked.

**Comment by abnerlee** [comment]
There's an option in preferences panel to enable automatic scroll while navigating by keyboard (Up/Down key) when typewrite mode is no, and I think the option is enabled by default.

**Comment by martzell** [comment]
Lacking documentation: What does Typewriter mode do when `Preferences » Editor » Always keep caret in middle of screen when typewriter mode is enabled` is unchecked?

Duplicated options in Preferences vs. Menu Bar which can both be enabled contradicting: `Edit » Whitespace and Line Breaks » Preserve Single Line Breaks` vs. `Preferences » Editor » When writing: Ignore whitespace and single line`.

Enhancement request: Could you imagine what I described in my first comment here? I will try other words: **Don't scroll away the content when clicking with the mouse.** Automatic scroll only with keyboard navigation.

**Comment by abnerlee** [comment]
> Don't scroll away the content when clicking with the mouse. 
Uncheck `Preferences » Editor » Always keep caret in middle of screen when typewriter mode is enabled` will do this, which only scrolls on user input
