### ISSUE TITLE
Line breaks less confusing

### ISSUE THREAD

**Issue by martzell** [typora/typora-issues#1937]
Bug: \<br /> and shift return (1 newline character in source) is shown as a space in WYSIWYM (or do you call it hybrid view?) at beginning of new line.

Workaround: shift return than \<br />. But \<br /> can be shown like \<br <br />/><br /> Which is not so nice.

Better: Shift return should insert a visible markdown line break in plain text: back slash \ and newline character, see CommonMark, or \<br /> and newline character. In hybrid view just one line break symbol at end of line should shown and could selectable and should never break in WYSIWYG view.

**Comment by abnerlee** [comment]
Line break in Markdown is confusing.

Shift+Return insert "\n" is best default behavior. Other actions are advanced settings for `Shift+Return`.
They are duplicate with https://github.com/typora/typora-issues/issues/37#issuecomment-373907044

**Comment by vassudanagunta** [comment]
@martzell you may want to add to #1317.  If you can, state it terms of principles and then how Typora doesn't meet them or could do better.

**Comment by martzell** [comment]
Bug: Newline is shown as space in front of next line

**Comment by martzell** [comment]
Sorry, if i'm using it wrong. I'm new to GitHub issue system. Please provide me information how to file issues correctly.

**Comment by abnerlee** [comment]
> Bug: Newline is shown as space in front of next line

Would you provide more details on this?

**Comment by martzell** [comment]
![image](https://user-images.githubusercontent.com/29772424/48278901-335bbe80-e44f-11e8-9071-e97cc627083a.png)
```
Here comes a source code line break after `<br />` <br />
and then there is a space to much in Hybrid view at beginning of this line.

Workaround: Put the source code line break before`<br />`
<br />then everything is fine. All neatly aligned.
```
