### ISSUE TITLE
Left-align math blocks

### ISSUE THREAD

**Issue by CreeperLava** [typora/typora-issues#1938]
It would be nice to have an option to automatically left align all math blocks. The option could be document specific. Here's what I have to write to get this effect, I don't think there's an easier way : 

```
\begin{align*}
& a = b
& b = c
\end{align*}
```

**Comment by abnerlee** [comment]
We may not provide extra settings for math alignment since it is a low priority feature.

**Comment by eduardohorta** [comment]
A working example on macOS Catalina: [https://github.com/typora/typora-issues/issues/1564#issuecomment-691047922](https://github.com/typora/typora-issues/issues/1564#issuecomment-691047922)
