### ISSUE TITLE
Adding stray whitespace to lists, losing nested structure

### ISSUE THREAD

**Issue by JZacharyG** [typora/typora-issues#194]
I've been noticing Typora modifying or breaking lists recently.  Nested lists will sometimes

1. lose their indentation,
2. have lots of extra whitespace added at the beginning of a line (between the '-' and the text), or
3. have blank lines added between items.

Seems to happen when switching in and out of source mode?

**Comment by abnerlee** [comment]
It is a bug and we will fix it ASAP

**Comment by abnerlee** [comment]
Should be fixed in new version
