### ISSUE TITLE
A problem to preview image

### ISSUE THREAD

**Issue by Jaceyli** [typora/typora-issues#1941]
I found that an extra "/" in image url was generated when copying image in typora, like `![](**/**1.png)`.
But the image turned out to be not found on website generated by Hexo.

typora-copy-images-to: filename/
typora-root-url: filename/

How can I preview the image, as well as it can be showed on website?
Thank you for any help.

Typora Version 0.9.9.19.1 (1301)
macOS Mojave Version 10.14.1

**Comment by abnerlee** [comment]
I cannot understand your issue, for 

> How can I preview the image, as well as it can be showed on website?

You could refer https://github.com/typora/wiki-website as an example. Its image can be previewed and also visible on website
