### ISSUE TITLE
Codeblocks takes emoji name as language after using :emoji: 

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#1942]
Since a gif is better than anything else

![2018-11-05 07 04 54](https://user-images.githubusercontent.com/22882880/47979028-8806de80-e0c9-11e8-8976-f593141c2f9e.gif)

It's not the worse, but it's quite annoying. As you can see in the gif the behavior happens when you use the arrows to select the language and/or the emoji. It's like they were mixed up.

**Comment by abnerlee** [comment]
Should be fixed in new release
