### ISSUE TITLE
Can't escape '$' with '\' in table now?

### ISSUE THREAD

**Issue by scruel** [typora/typora-issues#1944]
If I try to use some symbols in table, I may write code like this:

![beee4f9f76888051ae70aac0d98d7fb9](https://user-images.githubusercontent.com/16933298/48013010-4d9b5100-e15e-11e8-984c-a7cf9ecf94bb.jpg)

It seems using escape was ok, cause I want to display the symbol word ‘$’, but then going back to the view model, I got this:

![498a483edd9d12ccb27caec3fa9e7ea9](https://user-images.githubusercontent.com/16933298/48013041-63107b00-e15e-11e8-8514-7daed480eecb.jpg)

How can I got such weird result! So what’s wrong?

Note: To reproduce this exception, may need to try to save and restart, then open the document, Thx!

 
System Environment: Win10 Pro 1803
Typora Version: 0.9.60(beta)

Relative Code:
```
| Size in $feet^2$ ($x$) | Price (\$) in 1000's($y$) |
| ---------------------- | ------------------------- |
| 2104                   | 460                       |
| 1416                   | 232                       |
| 1534                   | 315                       |
| 852                    | 178                       |
| ...                    | ...                       |
```

**Comment by scruel** [comment]
Update:
this bug appeared after version 0.9.9.53 (beta)(not include).

**Comment by abnerlee** [comment]
Should be fixed in new release
