### ISSUE TITLE
UX, when you open a new typora, you cant start typing, cos typo doesnt auto-highlight itself

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#1945]
~~~

**Comment by abnerlee** [comment]
Please provide more necessary info

**Comment by SolveAllProblemsRightNow** [comment]
1.  open a new typora, 

2. start typing

3. you cant type, 

4. cos typo doesnt auto-highlight itself

seems like it's fixed now yea?

how i do delete my own post on github?
