### ISSUE TITLE
macOS Typora treats folder with name "*.txt" as supported bundle format

### ISSUE THREAD

**Issue by kzhui125** [typora/typora-issues#1946]
Mac OS Mojave 10.14

1. create a folder (folder name: test.txt)
2. Double click this folder, Typora shows up.

How to I open the folder using Finder?

**Comment by abnerlee** [comment]
I don't think macOS/finder would open folder in any external app.

**Comment by kzhui125** [comment]
So this may be a Mac OS bug?

**Comment by kzhui125** [comment]
@abnerlee 
I think this is a Typora bug.

**Comment by abnerlee** [comment]
> MacOS/Finder allow opening folders in external apps, such as *.workflow folder.

This is a bug, right?

**Comment by kzhui125** [comment]
@abnerlee this is not a bug.

Applications in mac (such as Typora.app Siri.app) are also folders.

```
cd /Applications
ls -l
open Siri.app
```

ls -l you can see "drwxr", d means directory.

**Comment by kzhui125** [comment]
![2018-11-07 21 45 29](https://user-images.githubusercontent.com/11925432/48134987-9d9d2380-e2d6-11e8-87ae-e0d318429bdc.gif)


@abnerlee now test.txt is considered as a bundle.

<img width="384" alt="2018-11-07 9 48 20" src="https://user-images.githubusercontent.com/11925432/48135094-e05efb80-e2d6-11e8-8218-7a88ce88d71a.png">

**Comment by abnerlee** [comment]
Fixed in new release, please upgrade to later version.

You may also need to unregister Typora as viewer of *.txt bunder by change the default app for *.txt folder.
