### ISSUE TITLE
inline Latex fine in Typora, but bad in pdf

### ISSUE THREAD

**Issue by walaa-a** [typora/typora-issues#1947]
inline Latex equations look good in preview in Typora, but are not always compiled when exported to pdf. This behavior is inconsistent

**Comment by IInatas** [comment]
Hi,
I use *Typora 0.9.60 (beta)* and I have the same problem under *KDE neon (base is Ubuntu Bionic)*, using *pandoc 2.3.1 - compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.2*

In my case the bug is persistent, so I always get a faulty PDF file.
Does some knows a work around, for example using pandoc directly ?

**Comment by teimy** [comment]
Hi, same problem. Typora 0.9.60 (beta), Xubuntu 18.04, inconsistent.
I have no idea what is pandoc, so in my case it shouldn't be connected with this probably.

**Comment by VicaYang** [comment]
Same problem, I am waiting for the new release for at least one month. Every time I have to check my pdf and manually cut/paste some formula to make it render correctly, which is quite annoying.   
Typora 0.9.60
pandoc.exe 2.1.3 Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2
Window 10 1803

**Comment by Roenbaeck** [comment]
Typora Version 0.9.9.19.4 (1355) on macOS Mojave 10.14.2 (18C54) has the same issue. Inline math is shown uncompiled in the PDF, along with the dollar signs.

**Comment by VicaYang** [comment]
@abnerlee 
Finally! I got a reproducible example! 
1. Type $1$$2$
2. 'LEFT' 'LEFT' 'BACKSPACE' 'BACKSPACE' to remove 2$ in middle
3 Type , 
4. Render to pdf then you got a pdf with content $1,2$

Here is a git demo. This bug has tortured me for more than two months!!! I sincerely hope it could be solved soon.
![5c34b0ba66044](https://user-images.githubusercontent.com/22126501/50836107-5e9d5400-1393-11e9-8757-42c63af695a4.gif)

**Comment by abnerlee** [comment]
Should be fixed in new release
