### ISSUE TITLE
Update Mermaid to Version 8.0.0-rc.8

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#1948]
The current version of Mermaid generates large spaces above and below Mermaid rendered flowcharts, sometimes resulting in a page or more of empty space. Apparently version 8.0.0-rc.8 solves this issue.

See: [FlowChart - large space between text and the image #754](https://github.com/knsv/mermaid/issues/754#issue-377778132)

**Comment by abnerlee** [comment]
#1966
