### ISSUE TITLE
can't support <img src = ... > well  on Ubuntu 17.10

### ISSUE THREAD

**Issue by amlloc** [typora/typora-issues#1949]
1. can't support `<img src = ... >` to resize the image again on Ubuntu 17.10 
2.can't show the image when I export md to pdf, but `![](/root/imge.jpg)` could work.

**Comment by abnerlee** [comment]
Typora version?

**Comment by amlloc** [comment]
> Typora version?

Sorry, I forget.
The version is 0.9.60(beta)

**Comment by abnerlee** [comment]
Could you provide a full example of `<img src = ... >`? And the bug is 1. cannot resize 2. cannot be exported? I mean it still renders well in Typora?

**Comment by amlloc** [comment]
for example : `<img src = res/154.png width = "100" height = "100">`
1. the image can't be resize
2. when I export md to pdf, it will show like below (in *pdf*):
![image](https://user-images.githubusercontent.com/18588524/48386593-722e9480-e72d-11e8-9e8c-ec87dadc1cc0.png)
3. but if I insert image by  `![](res/154.png)` instead of  `<img src = res/154.png width = "100" height = "100">`,  it will show  well in *pdf*.

**Comment by abnerlee** [comment]
Fixed in new release
