### ISSUE TITLE
Exported pdf with Japanese problem.

### ISSUE THREAD

**Issue by aristotll** [typora/typora-issues#195]
![image](https://cloud.githubusercontent.com/assets/13341544/16235162/71076f10-3806-11e6-8803-b04f80422c8b.png)

As showed above, the character and kana are kind weird... 

For example: Node.jsの真価は
の and は are different from 真価.

**Comment by aristotll** [comment]
I use the latest beta version of Windows.

**Comment by abnerlee** [comment]
So when editing in typora, の and は are same with 真価? or they are different even before printing out?

**Comment by aristotll** [comment]
Before exporting, Typora works fine.

![image](https://cloud.githubusercontent.com/assets/13341544/16237371/b91c0e48-380e-11e6-9321-3a8dfa94ff97.png)

**Comment by abnerlee** [comment]
Will this -> http://qiita.com/kouichi-c-nakamura/items/45947bcbc954ea611593 fix the issue?

And if possible, could you send us (<hi@typora.io>) the sample *.md file and exported PDF file?

**Comment by abnerlee** [comment]
It's long time since last discussion, please reopen this if the bug still exists in our latest update
