### ISSUE TITLE
[Bug] Typora Randomly Changes Plain Text as Code Blocks

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#1950]
_I neglected to get screenshots of this issue, because I was in a panic, but I will describe the issue._

For some reason, Typora has been changing random plain text areas to code blocks - this has happened to two of my documents so far (in the past few days), and it creates major issues because they are all outline-formatted (mass amounts of `<ol>`). And just to put it out there, this is not theme specific - it happens on any theme.

The problem is, Typora isn't changing the actual "source," it's changing the "display." What I mean by this is: when you go into "source mode" in Typora, nothing looks different. There are no code block indications (```), and there's nothing else to tip you off. But in the standard WYSIWYG mode, it displays as a code block.

Can this be an important issue, considering it's breaking a major feature - the WYSIWYG part?

**Comment by lloyd094** [comment]
Never mind, it just did it again. Here are screenshots:

**WYSIWYG:**
![wysiwyg view](https://user-images.githubusercontent.com/22482891/48218449-c22ce600-e33e-11e8-8eda-ddb1158e6435.jpg)



**Source Code Mode:**
![source code mode](https://user-images.githubusercontent.com/22482891/48218464-c8bb5d80-e33e-11e8-9f65-f8cc1b0efca4.jpg)


One of the things I fixed earlier on was several pages long before the code ended.

**Comment by abnerlee** [comment]
1. Please upgrade to latest version, or provide Typora version and steps to reproduce this.
2. Text with tab or 4 white space indent is code block in Markdown, so it is not bug if the text is inputted in source code mode or from origin file.

**Comment by lloyd094** [comment]
Hey there,

1. I am currently on the latest version of Typora (0.9.60), but I don't know how to reproduce it the problem. everything looks correct when I edit in the WYSIWYG part, but if I reopen the document later on, it has a chance of changing to the code block.

2. If I have a tab space before, does that mean Typora will sometimes think it is a code block instead of what it originally shows when I first create it? If so, that's on me (I have been going through ordered lists and hitting backspace prior to a blockquote to hide the number visually, but perhaps this makes Typora think I intended a code block?).

Let me know if I can give you more info - additionally, you can always look at the markdown file I emailed you yesterday, as that is one of the documents that I'm having this issue with.

Thanks for the help!

**Comment by abnerlee** [comment]
If you do indent in WYSIWYG mode, Typora will insert non-width whitespace to prevent it from being recognized and code block. 

So if you only edit in WYSIWYG mode, but text change to code block, then it is a bug. Please reopen the issue in this case.

**Comment by lloyd094** [comment]
Do you need me to open a new issue for this, or are you able to re-open the case?

**Comment by abnerlee** [comment]
@lloyd094 Hi, I'm unable to reproduce this on my own, do you mind to tell me how you input the indented list in WYSIWYG mode and then it becomes code block?

**Comment by abnerlee** [comment]
Known patterns are already fixed, please comment / reopen this when it still happens in newest version
