### ISSUE TITLE
More compact table layout

### ISSUE THREAD

**Issue by pauljurczak** [typora/typora-issues#1951]
Currently the tables are formatted with very wide columns even when only single characters are used for title and data, unnecessarily forcing the table to exceed page width. Other markdown engine produce narrower columns. Here is the example:

| Name                  | GS | HDR  | DR [bit] | Pixel size [um] | Size  | Resolution  | Mp   | FPS  | Notes |
| --------------------- | -- | ---- | -------- | --------------- | ----- | ----------- | ---- | ---- | ----- |
| Sony IMX174  | Y  |      | 12.1     | 5.86            | 1/1.2 | 1920x1200 | 2.3  | 162  |       |
| Sony IMX249  | Y  |      | 12.1     | 5.86            | 1/1.2 | 1920x1200 | 2.3  | 30   |       |

which is rendered by Typora as:

![typora](https://user-images.githubusercontent.com/4933032/48298779-4aff6b00-e480-11e8-9516-0a921502ddd2.png)

**Comment by DutchPete** [comment]
I second this - I also noticed exactly the same.
BTW, in your example above it seems to me the 2 tables should be inverted.

**Comment by pauljurczak** [comment]
@DutchPete What do you mean by inverted? The top table is rendered by GitHub, the bottom one is rendered by Typora.

**Comment by DutchPete** [comment]
> 
> 
> @DutchPete What do you mean by inverted? The top table is rendered by GitHub, the bottom one is rendered by Typora.

Thanks for reconfirming that the bottom one is rendered by Typora. Your examples as shown actually weaken your case because the lower one is more compact. Having said that, I reconfirm my support for your initial comments. In my view you should choose a better example to support your case.

**Comment by pauljurczak** [comment]
> Your examples as shown actually weaken your case because the lower one is more compact.

That's interesting. My browser shows just the opposite: the top table width is 94% of the bottom one. Regardless of that, GitHub renderer makes much better width choices for narrow columns.

**Comment by DutchPete** [comment]
> That's interesting. My browser shows just the opposite: the top table width is 94% of the bottom one. Regardless of that, GitHub renderer makes much better width choices for narrow columns.

OK, then leave it at that. The main thing is that we agree on, and I support you with this issue.

**Comment by abnerlee** [comment]
Fixed in new release. 

You could do custom CSS if you prefer more compact or loose table layout.
