### ISSUE TITLE
Incorrect Cmd-Shift selection behaviour 

### ISSUE THREAD

**Issue by oshev** [typora/typora-issues#1952]
In Typora for Mac OS. Having an md file open, inside the editor, press Cmd-Shift-Down. This this select the text from the cursor to the end of the file. Now, keep Shift but release Cmd and Down. Still, keeping Shift pressed click Up-Up-Up. The selection will move at the beginning of the text, not at the end as it is in all other editors. 

This is a very annoying bug which makes Cmd-Shift-Down hard to use. Please, fix it.

**Comment by abnerlee** [comment]
merge to #1164
