### ISSUE TITLE
the typora can not detect the file  content changed by git

### ISSUE THREAD

**Issue by DHclly** [typora/typora-issues#1953]
last night , I merge text content by git , but the typora do not detect the file content is changed by git .
I open the **auto save** , and I edit a lot of file , then I do not found the typora override the new content of file , I just found it now , I think it is serious 。 I test the nodepad++ , it can detected the file content is changed , it will tip me need to reload the file , but typora not , and auto save ,then cause the others people content is dissapear。

for example，I create a file the open by notepad++ and typora，the content only have one line
![image](https://user-images.githubusercontent.com/11781439/48309359-5dc68c80-e5b3-11e8-82df-6d2e41100395.png)

the I revert by git , now I have the new content 
![image](https://user-images.githubusercontent.com/11781439/48309372-a54d1880-e5b3-11e8-92e7-a99bc58fa341.png)

I turn to notepad++,it tip me to reload.
![image](https://user-images.githubusercontent.com/11781439/48309385-c6156e00-e5b3-11e8-98a6-eb7c631f3dc7.png)

I turn to typora , it happend nothing 
![image](https://user-images.githubusercontent.com/11781439/48309393-f4934900-e5b3-11e8-96e6-ba573b4002c7.png)

if I do not found this change , I just save the new content edit by typora,and  the content of revert by git is deleted !
![image](https://user-images.githubusercontent.com/11781439/48309404-55228600-e5b4-11e8-9a47-38512491fcdd.png)

**Comment by abnerlee** [comment]
Typora version?

And will Typora detect content change if you edit the file by other apps like notepad?

**Comment by DHclly** [comment]
Thank you for your reply.

the version is typora for windows/linux 0.9.60(beta) , the os is windows 10 professional . 

and typora will detect content change by 3rd app ，except git .

I make a test , when I revert the git commit , the **visual studio code** 、**atom** 、**notepadPlusPlus** will react the change of content , the **microsoft notepad** and **typora** not。

**Comment by abnerlee** [comment]
should be fixed in new release
