### ISSUE TITLE
from *.md export to docx error

### ISSUE THREAD

**Issue by yakoye** [typora/typora-issues#1954]
typora has a error：
1. When exporting from *.md format to *.docx format, the underline will be lost.
2. In addition, in the exported docx text, the table has no border。
Please see the attached picture for details.
typora ：version 0.9.60（beta）in Windows 10，x86_64
pandoc： version2.4 windows 10，x86_64

![snipaste_2018-11-12_10-05-50](https://user-images.githubusercontent.com/16289151/48322531-05e75e80-e663-11e8-995f-516061cd2e5c.png)

 I hope you can solve it.

**Comment by yakoye** [comment]
In addition, in the exported docx text, the table has no border。

**Comment by abnerlee** [comment]
fixed in new version
