### ISSUE TITLE
Child lists automatically change into code fences.

### ISSUE THREAD

**Issue by ricecakebear** [typora/typora-issues#1956]
Hey guys. I came across a problem that when I did some editing in "Source code mode" and exited, some child lists might change into code fences, which I wasn't editing at all, like the one of list item 17. 
![typora bug 0](https://user-images.githubusercontent.com/44994232/48397652-622caa00-e759-11e8-8eed-90267d403ba4.jpg)
So I checked it back in "Source code mode" and found out that the indentation of this child list increased by 3.
![typora bug 1](https://user-images.githubusercontent.com/44994232/48398114-d025a100-e75a-11e8-8c0d-880b2b805cb8.jpg)
I'm not sure if I did some illegal operation that caused this problem. I did edit "max-width" of "#write" in newsprint.css from "40em" to "90em".
This problem is really annoying, since I don't know when some of them will go back to code fences and I have to edit them back one by one.
Help please.

**Comment by abnerlee** [comment]
What's your typora version?
What's your setting of "Indent Size on save" in preferences panel?

**Comment by ricecakebear** [comment]
> What's your typora version?
> What's your setting of "Indent Size on save" in preferences panel?

Mine's version is 0.9.60(beta). "Indent Size on save" is set to 2.

**Comment by abnerlee** [comment]
merge to #1950
