### ISSUE TITLE
Double clicking a word selects trailing whitespace

### ISSUE THREAD

**Issue by Gruntfuggly** [typora/typora-issues#1957]
Double clicking a word to select it also selects any trailing spaces after it. Depending on the font, with a single space this is not always obvious.

Is this intentional behaviour? I've not seen it in other editors.

Typically I double click a word to replace it and if I'm not careful I forget to retype the space.

**Comment by AlexPasternak** [comment]
Can you specify your platform and version? I couldn't reproduce this. I do see double-click _initially_ selecting trailing whitespace, but then it changes it to just select the word itself.

![2018-11-13 13 19 53](https://user-images.githubusercontent.com/1819485/48434129-e75a9380-e746-11e8-937f-1b257c2fa95b.gif)

Are there certain conditions only where this happens?

**Comment by abnerlee** [comment]
Please provide OS info. On Windows, it is not bug.

**Comment by Gruntfuggly** [comment]
Yes, this is windows. Can you explain why it's not a bug? Is there a way I can prevent it?

**Comment by abnerlee** [comment]
It is a spec on Windows, you could try double click on Edge or wordpad.exe for other native applications on Windows.
