### ISSUE TITLE
[Feature request] Tree structure in outline pane

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#1959]
NOTE: *There is a typo in the title: "outline" should be replaced by "Files"*

At the top of the **Files** pane only 1 folder is shown: the folder from which the current note is taken.
Request: to show subfolders of that folder too, and make them collapsible/expandable so as to get a hierarchical tree.

**Comment by abnerlee** [comment]
you can expand it by clicking it.

**Comment by DutchPete** [comment]
> 
> 
> you can expand it by clicking it.

1. Clicking on it doe snot do anything. It is permanently expanded.
2. The request is not for expand/collapse, it is for a hieracrchical tree.

If this request is not acceptable please tell me, but don't close it without addressing the main request.

**Comment by abnerlee** [comment]
> 2. The request is not for expand/collapse, it is for a hierarchical tree.

Sorry, I cannot understand what your request is. If you switch File Tree view, it is a tree structure.

**Comment by DutchPete** [comment]
Here too I apologise sincerely :-((  You are right of course, I will test things out better before I open an issue again. I am happy and ever more impressed with Typora, which is why I have been recommending it to others too. When are you going to start charging for Typora?

One last question relating to this: is there a limited to how many subfolders can be shown in the tree?
