### ISSUE TITLE
Increase max file size limit

### ISSUE THREAD

**Issue by rp-karanth** [typora/typora-issues#1961]
I have a very good system with good specs, but Typora isnt opening a 1.78 MB file. It is giving this error: `The file is too large to render in Typora` . The version I am using is 0.9.60(beta). Is this a deliberate lock on size. The file I am using contains thousands of couplet verses and fist line is has line break (two spaces) at end of line, but second line is succeeded by two newlines . Please help.

**Comment by abnerlee** [comment]
Typora now have size limit of supported files. 1.78MB are books with hundreds of pages. Better to split it down based on characters or topics.

**Comment by oshev** [comment]
I have a file which is only 1MB size and I get the same error. Just yesterday I was able to open it but after adding several paragraphs, Typora refuse to edit it anymore. I didn't notice any performance issues with this file so far. I don't understand what is the purpose of this limitation. You may warn the user but, please, let us decide when not to use Typora and switch to anything else.

**Comment by abnerlee** [comment]
I will increase the limit to 2MB in next version up.

The purpose is to stop Typora from unresponsive because of parsing & rendering huge data.

**Comment by Thunder33345** [comment]
maybe having a manual config overwrite for users who dont mind it??

**Comment by oshev** [comment]
Thank you @abnerlee! This would help. Probably, 2MB is more reasonable limit. I also like the idea of @Thunder33345 - it could be an advanced parameter, the kind of parameter which goes under "change it at your own risk" warning.

**Comment by abnerlee** [comment]
Changed size limit to 2mb in new version

**Comment by oshev** [comment]
Works, thank you so much!

**Comment by Sparsa** [comment]
It will be really nice if you allow us to set the maximum size of the file as mentioned by @Thunder33345 here.

**Comment by tsbertalan** [comment]
Since it seems that #88 is actually implemented, and all three of the image-inserting methods seem to support base64-encoded PNG (`<img src="data:image/png;base64,DATA">`, `![CAPTION](data:image/png;base64,DATA]`, and `![CAPTION][1] ... [1]: data:image/png;base64,DATA` all render images in Typora for me, with the last making for the most readable code), it's now easy to make files above this limit by including a few images at the bottom. Is it at all practical to raise the file size limit for such documents?

**Comment by sharpe5** [comment]
I was trying to export a Markdown file to PDF using Typora, but it failed as the Markdown size was 3MB. 

I wasn't worried about unresponsiveness for editing, as only wanted to view! I also have a high-spec PC that could effortlessly render a file size that was 100x as large.

Please add an advanced option to override the maximum file size.

**Comment by Neitent** [comment]
>>Please add an advanced option to override the maximum file size.
A new option would be nice. Or just ask if user still wants to open a big file.

Now it's quite strange behavior. To work with 2MB file I need to open it in a plain text editor and then paste it in Typora. And it renders just fine

**Comment by sharpe5** [comment]
I love Typora, but I simply cannot use it as most of the files I open are larger than 1MB. This is the singular most important usability issue that is preventing it from gaining wider acceptance. My machine is fast enough to handle it, please let me choose.

**Comment by Toparvion** [comment]
@abnerlee , sorry for repeating the already proposed idea, but could you please consider providing a way for us (end users) to set up the maximum size of supported files, even at the expense of possibly degrading opening time (i.e. at our own risk)?

**Comment by miloofcroton** [comment]
This is pretty much a non-starter for me, like @sharpe5 said. Custom file limits must be implemented if I'm going to give the app another try and consider purchasing the license.

**Comment by TXC-ALON** [comment]
@abnerlee , I really have some notes with markdown which are bigger than 2mb, and i don't want to split them.i have a 64g-memory PC but i can't open a 5mb file on the typora.
Can you providing a wayto custom file limits ? i just want the Directory functionality of markdown and the global search is not important for me.
l love your software and purchasing the license . hope to get your reply.

**Comment by omar-hanafy** [comment]
Is there any update on this? Should we still adhere to the 2 MB maximum, or is there an option for customizing the limits?

**Comment by terablade2001** [comment]
I just got an auto-generated analysis report MD file of ~5.7MB (which also links to many images outside of it of ~200MB). And realized that Typora limits makes it impossible to review it. I can see that for 600KB MD reports (with 35MB linked images) it need ~525MB of RAM. I guess I have over-enough RAM, and good H/W, to open a 6MB MD file. Is there any way to by-pass this limit and let the user adjust the maximum size / RAM on his own? ❗ 

I just open it in VSCode Editor and it's working fine (but without the useful/required outline feature of Typora for easy reviewing of so many data) - except from a ~20 sec initial delay to load it in memory!

Please consider adding an option for the user to set manually on his own limitations preferences and risks. 🙏

**Comment by wfstratton** [comment]
I hope this thread stays current because I would really like to use Typora but the file size limit is a killer.

**Comment by daviddelven** [comment]
Indeed. The current file size limit is a killer. Any so-called professional workflow will end up with files larger than 5, 10, 20 or 50mb text files. Otherwise... the end-user target will remain in a niche...

**Comment by sunshaoce** [comment]
This article provides a workaround: https://dev.to/l1u7/fixing-the-file-is-too-large-to-render-in-typora-by-increasing-the-file-size-limit-hnc

**Comment by p0rkchop** [comment]
I can't find a way to achieve the same workaround on Mac. I can render multi-mb files just fine in the preview on VS Code, but it's clunky. I also understand that the stylesheet rendering creates significant overhead, I ran into this and corrected for it making my own themes, but at a minimum let people override this.
