### ISSUE TITLE
Wrong word count for new blank documents in 0.9.9.19.4

### ISSUE THREAD

**Issue by claytonrcarter** [typora/typora-issues#1962]
Just upgraded to 0.9.9.19.4 (1355) and noticed that new documents have a word count of 1000. (Line count is 1 and character is 0, both of which are correct.)

Steps to reproduce:
1. Open Typora
2. Open a new, blank document
2. Click "0 words" in the title bar
3. Observe: "1000 Words"

Typing a single character and deleting it correctly updates the word count to 1 and then back to 0.

Thanks!

**Comment by abnerlee** [comment]
Fixed in new release
