### ISSUE TITLE
Line Breaks mishandled

### ISSUE THREAD

**Issue by GiovanH** [typora/typora-issues#1963]
Inserting a line break with Shift+Enter seems to insert a line break properly in the editor. However, when exported, it renders as one line, without a line break.

Inspecting the source code reveals that Shift+Enter does *not* add two spaces after the line, as is proper markdown. Ergo the render is correct, and the live editor is wrong.

Proposed solution: Ensure that Shift+Enter inserts spaces and then a newline.

**Comment by abnerlee** [comment]
duplicate with other issues.

Also, there are options for how to handler line break in live preview and export in preferences panel
