### ISSUE TITLE
Add "Command Menu" for fuzzy searching commands and actions

### ISSUE THREAD

**Issue by blorenz** [typora/typora-issues#1969]
It would be helpful to have a devtools-type Command Menu Instead of having to commit all keyboard shortcuts to memory. A single keyboard shortcut could provide a fuzzy search and filter of actions instead of having to navigate to the Menus with the mouse. 

https://developers.google.com/web/tools/chrome-devtools/ui#command-menu

**Comment by abnerlee** [comment]
duplicate with 1512
