### ISSUE TITLE
Increasing spaces after bullet with each save

### ISSUE THREAD

**Issue by snungd** [typora/typora-issues#197]
Steps to reproduce:
1. Create file with external editor with following contents - 4 spaces indent
```
* item 1
* item 2
    * subitem 1
    * subitem 2
* item 3
* item 4
```
2. Open the file in Typora
3. Save file several times (just add some chars every time somewhere)
4. Resulting file has redundant spaces after asterisk
```
*     item 1               
*     item 2
      * subitem 1
      * subitem 2
*     item 3
*     item 4
```

Side note: amount of spaces added with each save seems to be associated with option Preferences | Editor | Indent size on Saving.

**Comment by abnerlee** [comment]
Updated a new release to fix this critical bug
