### ISSUE TITLE
No/limited support for embedded SVG

### ISSUE THREAD

**Issue by machonky** [typora/typora-issues#1970]
First off - Very impressed with Typeora. Very clean design and implementation.

I found the following limitation:
While writing MD I frequently will put raw SVG content in the MD file knowing that as this is converted to HTML, the SVG will remain, thus embedding the image in the document. Typora appears to render the raw SVG text, instead of rendering the image.

**Comment by abnerlee** [comment]
SVG is supported, e.g:

```
# header

<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
  <circle cx="100" cy="50" r="40" stroke="black"
  stroke-width="2" fill="red" />
</svg>

aaa
```
