### ISSUE TITLE
[Ubuntu 14.04 ] typora: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by typora)

### ISSUE THREAD

**Issue by gerrylj** [typora/typora-issues#1971]
**System:** 
Linux 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Install:** 
 2000  sudo add-apt-repository 'deb https://typora.io/linux ./'
 2001  sudo apt-get update
 2002  wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
 2003  sudo apt-get update
 2004  sudo apt-get install typora

**Problem:**
after typing typora in terminal, there is a black screen , and the error log as follow:
#typora
typora: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by typora)
/usr/share/typora/Typora: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/share/typora/Typora)

# ls -la /lib/x86_64-linux-gnu/libdbus-1.so.3
lrwxrwxrwx 1 root root 18 Dec  7  2016 /lib/x86_64-linux-gnu/libdbus-1.so.3 -> libdbus-1.so.3.7.6

how to resolve this ?

**Comment by abnerlee** [comment]
Please try install or update libdbus

Refer: https://stackoverflow.com/questions/137773/what-does-the-no-version-information-available-error-from-linux-dynamic-linker

**Comment by gerrylj** [comment]
I have install libdbus-1.so.3 -> libdbus-1.so.3.7.6 , please tell me what is the minimum version ?

**Comment by LionsLi** [comment]
I have suffered the same problem,have you solved this issue?

**Comment by Lakkanna** [comment]
you need to specify operation system, example in _.travis.yml_ **os: osx**, similar thing you need to do for typora configuration. i think this will help.
