### ISSUE TITLE
Search typing issue #1005

### ISSUE THREAD

**Issue by xPea** [typora/typora-issues#1973]
#1005 is closed, but it's not at all solved. I work in a relatively big document (300kb) and as soon as start typing into the search bar typora stucks at the 3rd char. If I type `ab` everything is fine, but as soon as I type `abs` it stucks for about 7 seconds, so after 7 seconds I got the first search result...
I'm using 0.9.60 at Ubuntu 16.04.

I assume I'm not the only one, so please comment or press thumbs up.

**Comment by diomed** [comment]
I experience same problems under Windows 10

**Comment by abnerlee** [comment]
@diomed Also in large file or normal file?

**Comment by diomed** [comment]
larger file I guess. [180 kb]

**Comment by abnerlee** [comment]
merge into #2107
