### ISSUE TITLE
Unable to save read-only file in windows, vscode is able to do and is a good example.

### ISSUE THREAD

**Issue by jinchou** [typora/typora-issues#1977]
## typera
![image](https://user-images.githubusercontent.com/29190635/48886579-719da880-ee67-11e8-8119-9b178e460f6f.png)
![image](https://user-images.githubusercontent.com/29190635/48886606-8ed27700-ee67-11e8-920b-94fb9283e4ff.png)

## VSCode
![image](https://user-images.githubusercontent.com/29190635/48886673-ce995e80-ee67-11e8-8bcc-ccc2a9adff1e.png)

Add the support to read-only file will be a very good choice.
It's convenient and we don't have to cancel the read-only attribute to the file manually.

**Comment by abnerlee** [comment]
#1826

**Comment by abnerlee** [comment]
Added option for "save-as" in new version. 

"read-only" means the file should not be edited, so we do not provide "Overwrite" option for now.
