### ISSUE TITLE
display all files in the sidebar.

### ISSUE THREAD

**Issue by scruel** [typora/typora-issues#1978]
Currently, Typora only displays .md files in the sidebar without any further opinions to change it.
![image](https://user-images.githubusercontent.com/16933298/48912843-a59dbb80-eeb1-11e8-8eb6-170e16622e0f.png)

![image](https://user-images.githubusercontent.com/16933298/48912858-b77f5e80-eeb1-11e8-859c-b134f4ebf961.png)

**Comment by abnerlee** [comment]
duplicate
