### ISSUE TITLE
Hide scroll bar in outline panel.

### ISSUE THREAD

**Issue by smallx** [typora/typora-issues#198]
It will be more becautiful to hide scroll bar in outline panel(like previous version of Typora). Thanks.
![baidushurufa_2016-6-22_0-42-18](https://cloud.githubusercontent.com/assets/16517035/16238379/e73fff10-3812-11e6-8f76-a76854470f0e.png)

**Comment by abnerlee** [comment]
Fixed in 0.9.12

**Comment by smallx** [comment]
I am very excited. Thank you very much. :100:
