### ISSUE TITLE
math block markers should be on same line to be compatable with stackexchange

### ISSUE THREAD

**Issue by wm2015email** [typora/typora-issues#1982]
I think the developers should fix this one since stackexchange is a really popular website that uses markdown.  

stackexchange (And everybody else for that matter) lets you "fence off" math equation with the $$ markers on the same line as the math equation, however, typera requires separate lines for "$$" marker...  therefore, all of the markdown on math.stackexchange.com is 100% incompatible out of the box...  Personally, I really hate that typera does this... its a pain in the neck to put $$ one line before and one line after each math equation... white space inbetween looks 100% better... also, I would like to click edit in math.stackexchange.com, swipe some of my markdown that I posted to the website, and keep it backed up as a markdown document on my computer that I can open with typera without major modification to the $$ markers by adding CR-LF everywhere in the doc to make typera happy, and stackexchanged messed up and angry because it hates CR-LF before the $$ marker...

**Comment by abnerlee** [comment]
We don't have plans to change this.

But you could turn on inline math in preference panel to enable rendering "$$ \Alpha \Omega $$"
