### ISSUE TITLE
input cursor is jumped

### ISSUE THREAD

**Issue by hjwjw** [typora/typora-issues#1985]
This editor is really good! But there is a problem: I added the front matter to a new blank file. When I move the cursor out of the front matter input text, the first word (Chinese) will automatically jump to Front matter. I think the description may not be clear, it would be more intuitive to make a gif. 

System environment: Windows 10
typora version:  #0.9.60(beta)
input ：QQ five stroke input method

![typora_bug](https://user-images.githubusercontent.com/17232182/49126906-6d0e3f80-f300-11e8-9f03-1a5f7ce0fcc4.gif)

**Comment by abnerlee** [comment]
use #3318 since it has a more detailed title
