### ISSUE TITLE
Indentation replaced with non-width whitespace

### ISSUE THREAD

**Issue by MPSinclair** [typora/typora-issues#1987]
I noticed that when I indent fenced code blocks in Source mode and switch back to the WYSIWYG editor, the indentations are replaced with non-width whitespace characters. This breaks the code blocks. Are there any preferences that can be used to toggle this behavior off?

<img width="338" alt="image" src="https://user-images.githubusercontent.com/198060/49201152-96f15180-f354-11e8-8f5c-e3f1ce1f1cea.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/198060/49201155-9f498c80-f354-11e8-88b8-3efb3a793ec9.png">

**Comment by MPSinclair** [comment]
After doing a bit more searching, it appears to be similar to [this issue](https://github.com/typora/typora-issues/issues/1372).

**Comment by abnerlee** [comment]
indent before code fences would lead to unexpected behaviors, e.g:

line with indent
	```javascript
	aaa
	bbb
	```
	
without indent
```javascript
aaa
bbb
```

**Comment by abnerlee** [comment]
used same spec as Github in new release
