### ISSUE TITLE
[Feature Request] Add other cursor styles

### ISSUE THREAD

**Issue by Zauberklavier** [typora/typora-issues#1989]
I think the blinking line is distracting and ugly 😞🤢👎  I'd love if there was a way to disable the blinking and use a block or a cone style cursor. There used to be one like that in Caret before they removed it. It's still on the screenshot on their home page. Please add this! 🙏 🙏 🙏 

Shamelessly linking the home page of (currently dead broken) competition: https://caret.io

**Comment by abnerlee** [comment]
duplicate with #1454
