### ISSUE TITLE
Wrong interpretation of bullets in list while mixed with fenced code blocks

### ISSUE THREAD

**Issue by snungd** [typora/typora-issues#199]
Steps to reproduce:
1. Create following file with external editor
    * remove #s from example below (needed to put markdown into markdown)
    * fenced code block need to start at column 0
```
* item 1
* item 2
    * subitem 1
#```python
test = ['uno', 'dos', 'tres']
#```
    * subitem 2
* item 3
* item 4 
```
2. Open in Typora - `subitem 2` will be interpreted as code block instead bullet list continuation due to its indentation.

Workaround:
indent fenced code block to level of `subitem 2` - works OK

**Comment by abnerlee** [comment]
Hi, I confirmed that the behavior is same with commonmark (<http://spec.commonmark.org/dingus/>) and Github. **`subitem 2` is interpreted as code block**

So, I think the "correct" markdown you want should be 

~~~ markdown
* item 1
* item 2
    * subitem 1
    ```python
    test = ['uno', 'dos', 'tres']
    ```
    * subitem 2
* item 3
* item 4 
~~~

And the markdown above should work fine in all markdown parsers.

**Comment by snungd** [comment]
I think my issue was opposite: assuming that markdown was created by hand or in some MD editor that does not follow CommonMark, Typora will not handle it properly.

I have lot of MD files that I edit with Vim and then convert them with python-markdown to HTML which parses them correctly.

I won't insist on fixing this, but it might be confusing to users as I was confused. Especially if (like me) someone is using Typora and other editor (in my case I use also Linux box with Vim MD setup) interchangeably.
