### ISSUE TITLE
Unable to discard changes to the document

### ISSUE THREAD

**Issue by ljylin** [typora/typora-issues#1991]
Turn off Typora after changing the document, the discard button does not work, Typoa does not close, I can only choose to save or kill the process.

- OS: CentOS Linux release 7.5.1804 (Core)
- Kernel version: 3.10.0-862.el7.x86_64
- Typora version: 0.9.60(beta)
- KDE: 4.14.8

**Comment by abnerlee** [comment]
Please reopen if this exists in new version
