### ISSUE TITLE
Suggestions on tabs option

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#1997]
Refer to the issue https://github.com/typora/typora-issues/issues/979, The current workaround does not work for me, because the change of system preferences in Dock will break all other apps' correct behaviors. Can we have something like `vim -p file1 file2` or `mvim -p file1 file2` ? Thanks a lot.

**Comment by abnerlee** [comment]
duplicate with #1000

**Comment by sgon00** [comment]
@abnerlee hi, I read that issue, I don't think it's duplicated. I want a command line argument because I use terminal only. That issue is all about UI and clicks. Thanks.

**Comment by abnerlee** [comment]
I see, will merge into #1999

**Comment by sgon00** [comment]
@abnerlee thank you very much. 👍
