### ISSUE TITLE
Typora crashed when clicking export to PDF

### ISSUE THREAD

**Issue by Dinghow** [typora/typora-issues#1998]
My typora version is 0.9.9.19.4(macOS), sometimes when I click the `export` to PDF, typora will crash, not every time. And here is the error message:
![](https://s1.ax1x.com/2018/12/02/FK9kod.png)

**Comment by abnerlee** [comment]
Possible to send us (<hi@typora.io>) the sample *.md file and the crash message?

**Comment by Dinghow** [comment]
I will send you the next time I meet this problem

**Comment by Dinghow** [comment]
@abnerlee I've met the problem again, the file and error message have been sent to your email.

**Comment by abnerlee** [comment]
Please reopen this if this still happens in new release
