### ISSUE TITLE
Design better icon for typora

### ISSUE THREAD

**Issue by RayPS** [typora/typora-issues#2]
![large](https://cloud.githubusercontent.com/assets/1941540/9440954/bda59b34-4aa5-11e5-8a12-77e4a7d6cfb5.png)
[Typora.icns](https://dl.dropboxusercontent.com/u/35409265/Typora.icns)

**Comment by abnerlee** [comment]
Could you give me more details? Like where did you get this icns ? In my mac `Typora.app/Contents/Resources/icons.icns` is not like this

**Comment by Fastidious** [comment]
@abnerlee I think he is offering the .icns for you to use it on the application.

**Comment by abnerlee** [comment]
@Fastidious so, which one do you think is better?

**Comment by Fastidious** [comment]
@abnerlee I think the one he is suggesting looks better. There are some questions I would like answered:

- Where did he get it from?
- Is he offering/donating it to the project, because he made it himself?
- Is he giving you the rights to use it?

Those are important questions, considering Typora will be a commercial product.

**Comment by RayPS** [comment]
@abnerlee @Fastidious 
Sorry i forgot to add the `enhancement` label to the issue, not good at using Github yet.
This is my re-design of Typora's app icon, i replaced every icon of my fav apps ([i did a lot before](https://dribbble.com/Ray_Design/projects/225602-APP-ICON-REDESIGN)), i would like to contribute to this project, i'm using Typora everyday.

**Comment by Fastidious** [comment]
@RayPS 👍🏻

**Comment by abnerlee** [comment]
@RayPS Thanks for your work. we do need a re-design of typora's app icon and icon for *.md files associated with typora, so it is very welcomed if you or someone else could work on that, and I'll pay if your icon is chosen.  

But currently, to be honest, I still like the original icon more. But if you got some ideas, please tell me!

**Comment by abnerlee** [comment]
Alternative icon by Adam ZD:

<img width="256" alt="typora" src="https://cloud.githubusercontent.com/assets/1621242/13075876/6af67fce-d4e9-11e5-9ba0-20226c057893.png">

[Download](https://github.com/typora/typora-issues/files/132408/Typora.icns.zip)

I'm not good at design, so I will find some designers to re-design typora's icon in future. Anyone has the idea for new icon is welcomed to contact us or comment under this issue.

**Comment by pgolebiowski** [comment]
@abnerlee I like very much the icon that you have right now. It is minimalistic and that's what I love 😄

**Comment by vassudanagunta** [comment]
I like @RayPS's icon... It's cleaner.

**Comment by yougotwill** [comment]
Minimal Circle Icon Alternative:

![typora icon](https://user-images.githubusercontent.com/14887287/30934615-6c7feb18-a3ce-11e7-86d2-fadd3cd1a080.png)

[Download](https://github.com/typora/typora-issues/files/1338545/Typora.icns.zip)


P.S. I really love this app, keep up the good work 👍

**Comment by zonovo** [comment]
This is my version of the Typora macOS replacement icon: https://www.dropbox.com/s/9fryewwok5onnuq/Typora-macOS-Icon-1024.zip?dl=0
![typora-macos-icon-1024-preview](https://user-images.githubusercontent.com/58424/34628841-d4a64946-f2a0-11e7-8aa0-6acd47d977e5.png)

**Comment by AlexPasternak** [comment]
Ooh, I like it quite a bit. To use it, do you have to change some plist to point to this new file, or just replace the previous icons.icns file in the package with the one in the zip?

**Comment by abnerlee** [comment]
also https://github.com/numixproject/numix-core/pull/4174

**Comment by vassudanagunta** [comment]
@abnerlee While the proposed numixproject icon is beautiful, Typora's beauty is that it writes Markdown, but keeps it hidden. That bold hashmark in the icon gives the opposite impression. Just my 2¢ :)

**Comment by sirpooya** [comment]
@abnerlee @Fastidious
Is Typora going to be commercial?
I've got some ideas for redesigning Preferences panel & the app icon & I want to contribute.

**Comment by sirpooya** [comment]
@abnerlee @Fastidious
Is Typora going to be commercial?
I've got some ideas for redesigning Preferences panel & the app icon & I would like to contribute.

**Comment by abnerlee** [comment]
@sirpooya 
Yes.

> I've got some ideas for redesigning Preferences panel & the app icon & I would like to contribute.

Go ahead, or contact us via <hi@typora.io>

**Comment by nanoant** [comment]
@zonovo Great icon. I just customized my Dock, and it looks IMHO much better.
<img width="81" alt="image" src="https://user-images.githubusercontent.com/103067/54089807-41720b00-436d-11e9-8cdb-ec711e449191.png">

**Comment by jlarmstrongiv** [comment]
I customized Typora’s app icon a while back—specifically, I inverted the colors to match dark mode.  Just another option to think about 🙂

**Comment by alethal** [comment]
![writing_notes_ico](https://user-images.githubusercontent.com/8648882/81734113-df68d600-9447-11ea-867f-717c19e01565.png)

**Comment by fabian-st** [comment]
> Minimal Circle Icon Alternative:
> 
> ![typora icon](https://user-images.githubusercontent.com/14887287/30934615-6c7feb18-a3ce-11e7-86d2-fadd3cd1a080.png)
> 
> [Download](https://github.com/typora/typora-issues/files/1338545/Typora.icns.zip)
> 
> P.S. I really love this app, keep up the good work 👍

Thanks, this was exactly what I was looking for!

**Comment by singularitti** [comment]
What about these 4:

![icons_approved_1605538826349_Typora_Alt_1-1 (dragged)](https://user-images.githubusercontent.com/25192197/99878568-57247400-2bd4-11eb-91fe-13b7e1f41e42.JPG)
![typora](https://user-images.githubusercontent.com/25192197/99878545-30fed400-2bd4-11eb-853a-b13c9f0c16e8.JPG)
![icons_approved_1604884518665_typora_Alt-1 (dragged)](https://user-images.githubusercontent.com/25192197/99878579-7cb17d80-2bd4-11eb-9052-9e9978039036.JPG)
<img width="512" alt="icons_approved_1605534590656_Typora_Alt-1 (dragged)" src="https://user-images.githubusercontent.com/25192197/99878585-90f57a80-2bd4-11eb-9ab2-408de597adaa.png">

They are from [here](https://macosicons.com/).
![macosicons](https://user-images.githubusercontent.com/25192197/99878596-a074c380-2bd4-11eb-800a-ae67d8fe31bf.png)

**Comment by fabian-st** [comment]
> What about these 4 (I prefere the 2nd or the 3rd)?
> 
> 
> 
> ![icons_approved_1605538826349_Typora_Alt_1-1 (dragged)](https://user-images.githubusercontent.com/25192197/99878568-57247400-2bd4-11eb-91fe-13b7e1f41e42.JPG)
> 
> ![typora](https://user-images.githubusercontent.com/25192197/99878545-30fed400-2bd4-11eb-853a-b13c9f0c16e8.JPG)
> 
> ![icons_approved_1604884518665_typora_Alt-1 (dragged)](https://user-images.githubusercontent.com/25192197/99878579-7cb17d80-2bd4-11eb-9052-9e9978039036.JPG)
> 
> <img width="512" alt="icons_approved_1605534590656_Typora_Alt-1 (dragged)" src="https://user-images.githubusercontent.com/25192197/99878585-90f57a80-2bd4-11eb-9ab2-408de597adaa.png">
> 
> 
> 
> They are from [here](https://macosicons.com/).
> 
> ![image](https://user-images.githubusercontent.com/25192197/99878606-c00bec00-2bd4-11eb-86bb-4c8e9c09b6eb.png)
> 
> 
> 
> 

I'd love to see the letter design of the second one together with the background & drop shadow effect of number one.

**Comment by s-valent** [comment]
I didn't really like any of new Big Sur icon suggestions, so I made slightly different variant.
Unfortunately, I didn't manage to keep the multiple sheets detail as it exists now, I feel like it doesn't work well with other icons.

![Typora](https://user-images.githubusercontent.com/46625993/103468772-ae8a3800-4d6d-11eb-95db-c2c2b37a3ac1.png)


[Typora.icns.zip](https://github.com/typora/typora-issues/files/5761004/Typora.icns.zip)

**Comment by s-valent** [comment]
It could also be something like this

![Typora](https://user-images.githubusercontent.com/46625993/103476425-7531e680-4dc6-11eb-9a52-576552e13e0f.png)

[Typora.icns.zip](https://github.com/typora/typora-issues/files/5761463/Typora.icns.zip)

**Comment by s-valent** [comment]
Assuming the last one is better, the document icon placeholder could be something like this
<img width="128" src="https://user-images.githubusercontent.com/46625993/103586959-47988a80-4ef7-11eb-9b62-81719f69ca91.png">
[file.icns.zip](https://github.com/typora/typora-issues/files/5767120/file.icns.zip)

Any thoughts, @abnerlee?

**Comment by abnerlee** [comment]
I'm closing this.

But you can still post your designs here
