### ISSUE TITLE
The equations are incorrectly scaled under high DPI on windows.

### ISSUE THREAD

**Issue by be5invis** [typora/typora-issues#20]
![image](https://cloud.githubusercontent.com/assets/240091/12032205/9d67aae2-ae50-11e5-985d-4cba6a2785eb.png)

![image](https://cloud.githubusercontent.com/assets/240091/12032234/fe9ec4da-ae50-11e5-87b2-77fd3057d520.png)
![image](https://cloud.githubusercontent.com/assets/240091/12032377/a2adaaa4-ae52-11e5-82d5-bc6ae8bed704.png)

My monitor is Dell P2715K under 3840x2160, while DPI 200% is used.
(btw. it's TeX, not Tex).

**Comment by abnerlee** [comment]
I think it is fixed in latest windows version, if not, please re-open this issue
