### ISSUE TITLE
In-line math support with \( \)

### ISSUE THREAD

**Issue by KENNYSOFT** [typora/typora-issues#2000]
As single dollar symbol ($) is commonly used in normal paragraphs, sometimes the un-wanted text is treated as math block. Like below.

```
The first year's budget is $10k, and the next years is $20k.
```
![image](https://user-images.githubusercontent.com/6624567/49375436-9d623d80-f747-11e8-8062-9f5014d20462.png)

I know that I can escape with `\$`, but it's more likely to use the dollar sign in a normal paragraph than for math block.

So please add support syntax for MathJax uses, like `\(` and `\)`. Thank you.

**Comment by abnerlee** [comment]
#63

**Comment by KENNYSOFT** [comment]
👍
