### ISSUE TITLE
Window is opened outside of desktop region

### ISSUE THREAD

**Issue by JaviCervera** [typora/typora-issues#2001]
I am running Typora 0.9.60 on Windows 10. My laptop (a ThinkPad T470) is usually connected to an external monitor that is used as the secondary display, where Typora used to be opened. Now I am travelling and not using the external monitor, and when I open Typora, the window is not shown. If I click the application icon on the taskbar, I see how the window minimizes to the taskbar from outside the desktop area, but I have not been able to move it within the screen bounds (right clicking on the taskbar and selecting "Cascade windows" does not work).

**Comment by abnerlee** [comment]
#1981
