### ISSUE TITLE
Links to files should open in the same window, not a new one

### ISSUE THREAD

**Issue by mbartelsm** [typora/typora-issues#2002]
Right now, clicking on a link to another .md document opens, but clicking on a file on the sidebar opens it on the same window, this is inconsistent behavior that is a little jarring. Additionally, initing a new window takes a fair bit of time and bloats the system, causing usability issues. This is especially the case when the software is used to edit documentation, wikis, blogs and other document systems that rely heavily on interlinking within the same platform.

I would suggest making the default behavior for relative .md links to open in the same window, just as is the behavior for sidebar links. Adding an option to change this would be ideal to allow for a wider range of use cases.

**Comment by abnerlee** [comment]
#1000
