### ISSUE TITLE
Feature request: Adding new table rows on Tab key

### ISSUE THREAD

**Issue by asherber** [typora/typora-issues#2009]
It would be nice if Typora handled adding rows to tables the way Word does: If I'm in the last column of the last row of a table, and I hit <kbd>Tab</kbd>, then add a new row to the table and move the cursor to the first column in that row.

**Comment by Leon99** [comment]
OneNote and some other editors do it as well. Very useful and intuitive.

**Comment by fzhzhy** [comment]
when table is long, this function will be very useful, to avoid to find the menu to add one row.

**Comment by AlexPasternak** [comment]
I take this for granted in tools like [Confluence](https://confluence.atlassian.com/doc/tables-136463.html), which has first class table editing. I couldn't imagine life without that there, and I must just not do too many tables in MD to not have noticed lack of this sooner.

**Comment by fzhzhy** [comment]
I reallize that ctl+enter will add one row, but didn't find way to add column yet. just F.Y.I

**Comment by abnerlee** [comment]
fixed in new release
