### ISSUE TITLE
The code is missing

### ISSUE THREAD

**Issue by EdwinZhangyc** [typora/typora-issues#2010]
windows version 0.9.60
I am writing the development document, window switch, part of the code block content lost, unable to restore
![image](https://user-images.githubusercontent.com/32889416/49634958-2d9ace00-fa39-11e8-8605-cc780f0dd0ef.png)
![image](https://user-images.githubusercontent.com/32889416/49634996-44412500-fa39-11e8-8b81-80bba59dd89e.png)

**Comment by zycInitGitHub** [comment]
> windows version 0.9.60 
I am writing the development document, window switch, part of the code block content lost, can not be retrieved

> ![image](https://user-images.githubusercontent.com/32889416/49634958-2d9ace00-fa39-11e8-8605-cc780f0dd0ef.png)
> ![image](https://user-images.githubusercontent.com/32889416/49634996-44412500-fa39-11e8-8b81-80bba59dd89e.png)

**Comment by necan** [comment]
This bug exists for a long time since it has never been fixed.

**Comment by zycInitGitHub** [comment]
Thank you for your reply
| |
zhang
|
|
zyc_wyzh@163.com
|
签名由网易邮箱大师定制
On 12/21/2018 17:30，玄虚<notifications@github.com> wrote：

This bug exists for a long time since it has never been fixed.

**Comment by abnerlee** [comment]
try update Typora
