### ISSUE TITLE
The Smart Numbering in a Figure Caption

### ISSUE THREAD

**Issue by GRGSIBERIA** [typora/typora-issues#2014]
References to #379 

I need to implement the smart numbering in a caption.
For example,

```md
![Fig. $$\label{test}$$ Caption of the Figure](./assets/test.png)

Fig. $$\ref{test}$$ is a figure.
```

This is not smart, but it's like LaTeX.
I need to implement the smart numbering.
Users selects an option in ["Fig", "Figure", "図" (means a figure), ..., Users customizes].

```md
![Figure caption sample $$\label{test}$$](./assets/test.png)

$$\ref{test}$$ is a figure.
```

```html
<figure>
    <img src="./assets/test.png" alt="図 1. Figure caption sample" />
    <figcaption><bold>図 1.</bold> Figure caption sample<figcaption>
<figure>
```

But, an inline math for numbering in the caption confuses the inline math system for other outline math labels, maybe.
If I implement to insert numbering in a figure reference, shown below.

```md
![^{test} Caption of the Figure](./assets/test.png)

[^{test}] is a figure.
```

I know Typora implements footnotes.
I think that override the footnotes function to the auto numbering.

Do you use "{", "}" in footnotes?
Is this smart?

**Comment by abnerlee** [comment]
Blocked by #379, since firstly Figure Caption should be supported somehow. But both variable and caption does not exist in most Markdown implements.

**Comment by GRGSIBERIA** [comment]
That's right. It was a proposal that not in the specification of Markdown. But, I've surprised that a footnote  included in the specification of Markdown. I thought footnotes are spreading out civilially. I thought interesting. Thanks.
