### ISSUE TITLE
Issues with text expansion (PhraseExpress)

### ISSUE THREAD

**Issue by Noweeks** [typora/typora-issues#2015]
Same issue as [#520](https://github.com/typora/typora-issues/issues/520) and [#1875](https://github.com/typora/typora-issues/issues/1875), but I'm experiencing problems with PhraseExpress, specifically. Text expansion does work, but the first character of the auto text isn't removed. For example, if the auto text is _c~_, and becomes _Ç_ when typed, Typora displays it as _cÇ_. Only occurs in WYSIWYG editor, not in source code mode.

**Comment by abnerlee** [comment]
merge into #1875
