### ISSUE TITLE
How to highlight syntax assembly code in code block?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#202]
![](http://7xj3js.com1.z0.glb.clouddn.com/%E6%88%AA%E5%9B%BE%202016-06-24%2014%E6%97%B651%E5%88%8649%E7%A7%92.png)

**Comment by leewi9** [comment]
It's a critical bug to me. I'll appreciate it very much if you can work it out. @abnerlee

**Comment by abnerlee** [comment]
#196
