### ISSUE TITLE
the size of chinese text in latex are too little with '\frac' 

### ISSUE THREAD

**Issue by scruel** [typora/typora-issues#2021]
here is the sample for description:

![image](https://user-images.githubusercontent.com/16933298/49788832-58e92a00-fd65-11e8-8554-6a44de28c91d.png)
-----
![image](https://user-images.githubusercontent.com/16933298/49788838-5dadde00-fd65-11e8-87df-b6817ff667ce.png)

Code:
`$优先权 = \frac{等待时间+要求服务时间}{要求服务时间}$`

**Comment by abnerlee** [comment]
Use block math in this case
