### ISSUE TITLE
Suggestion: Copy as semantic text

### ISSUE THREAD

**Issue by joakimc** [typora/typora-issues#2022]
It'd be plain awesome if we could copy the text without the theme styling, _but with the semantic structure retained_. I believe this would be similar to pasting the text into TextEdit on a Mac and copying it – which strips the Typora theme styling, so you can paste it into Google Docs or similar without the need for a cleanup.

**Comment by abnerlee** [comment]
supported in new release

**Comment by tsbertalan** [comment]
> supported in new release

Which particular feature supports this? (Personally, I'm interested in making _Edit > Copy Without Theme Styling_ the default for Ctrl+C.)

**Comment by abnerlee** [comment]
Edit > Copy Without Theme Styling
