### ISSUE TITLE
Ctrl+S to save, click close button a pop-up dialog box will appear unless wait for 5 seconds

### ISSUE THREAD

**Issue by shwofox** [typora/typora-issues#2026]
after Ctrl + S save my file, typora should be can close immediately when click close button，not wait for 5 seconds

**Comment by abnerlee** [comment]
Are you editing files from network location?

Typora can close after save operation finished.

**Comment by shwofox** [comment]
![tim 20181214101043](https://user-images.githubusercontent.com/4198276/49979152-b4473200-ff88-11e8-93d0-3c6ca7bd0823.png)

**Comment by abnerlee** [comment]
Are you editing files from network location?

**Comment by shwofox** [comment]
no, my computer OS is win10, I just input a simple text like '111' into the file on the desktop.

**Comment by abnerlee** [comment]
Please reopen this if it still happens in 0.9.62
