### ISSUE TITLE
Features requested.

### ISSUE THREAD

**Issue by aristotll** [typora/typora-issues#203]
- Auto load when the file is modified elsewhere( now there is a prompt, and I have to click "yes" every time) . Maybe configurations are needed?
- Auto save, this is a feature that many text editors  have.
- Shortcuts configurations.

Maybe typora does not need to have these enable default, but if I can use these features after configurations.

Thanks a lot.

**Comment by fabianffrank** [comment]
+1 for shortcut config

**Comment by MicheleLevorato** [comment]
- page breaks when creating a pdf

**Comment by abnerlee** [comment]
page breaks when creating a pdf > https://github.com/typora/typora-issues/issues/118

Other seems already supported
