### ISSUE TITLE
[Feature request] Add a diff view or git integration

### ISSUE THREAD

**Issue by nheeren** [typora/typora-issues#2031]
I often use Typora to write documentation for my git repositories. Therefore it would be great if it would embed in that workflow (even better). 

One thing that came to my mind was a diff view, meaning that Typora would color highlight sections that have changed e.g. since the last save. Or, even better, it would be awesome if Typora would be able to understand if a markdown file is part of a git repository and then allow diff views compared to the latest (or an arbitrary) commit. 

Curious to hear what you think.

**Comment by Thunder33345** [comment]
git integration would be nice and useful for me,
begin able to revert and know what i did/change previously would allow me to document changes easier
but this is getting close to the "IDE" terrority, not sure if typora should even consider investing in adding git workflow

**Comment by nheeren** [comment]
Good point. However, I would argue that version control tools can be considered valuable for power users. I use typora for more and more things, such as writing publications or books.

I would be happy with even some rudimentary support that allows me to compare my file with the one that my co-worker sent me.

**Comment by abnerlee** [comment]
Typora only supports markdown/plain text file. But git supports all kinds of files, it won't be a good git differ if only text file are supported. We also do not want to spend too much time on this, which is already supported by other git GUIs very well.

**Comment by Thunder33345** [comment]
what if just doing it for markdown+plain because this is what typora meant for anyways
and yeah all other format wont be supported, optionally though rendered as plain text diff view

>it won't be a good git differ if only text file are supported.

i agree with nheeren that even just markdown support is good enough for powerusers editing documents etc

**Comment by bytesandnibbles** [comment]
Here too, the majority of the markdown documents I work with are usually part of a git repo. Making easy to commit changes would be fantastic!

**Comment by ajaxsys** [comment]
I need to open VSCode or terminal & typora same time.
Really sad for this issue be closed.

**Comment by tejasvi** [comment]
IMO, implementing git diff would be too much to ask for a md editor. I have tested Typora for a short while and it has decent support for monitoring external changes to the file. So, using git in parallel shouldn't be an issue. What would be great is a diff view for the changes against the _saved file_. I have opened #4190 regarding that.
