### ISSUE TITLE
Public key

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2032]
I am using Linux Mint at the mo, and when I try to update via the Terminal I get the following message for Typora:
```
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
W: The repository 'https://typora.io/linux ./ InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE
W: The repository 'https://typora.io/linux ./ InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
```
Any chance to get this fixed?

**Comment by abnerlee** [comment]
```shell
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
# add Typora's repository
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update
# install typora
sudo apt-get install typora
```

**Comment by DutchPete** [comment]
Thank you.

**Comment by DutchPete** [comment]
I was not sure what your answer meant, but I assumed that it answered my question and that the key was not an issue anymore.
Today I tried to add your repository to Ubuntu 18.04 using the steps described above, but the feedback was that there is public key, so I could install Typora that way and keep it up-to-date that way.
So I downloaded the tarball and am using Typora as a standalone app, but that is far from ideal.
Please look at the key issue again.
