### ISSUE TITLE
[Console show error]"GET ~/themes/base.user.css 0 ()"[Window]

### ISSUE THREAD

**Issue by ZainChen** [typora/typora-issues#2033]
Console show:
```cpp
GET file:///C:/Users/Administrator/AppData/Roaming/Typora/themes/base.user.css 0 ()
GET file:///C:/Users/Administrator/AppData/Roaming/Typora/themes/github.user.css 0 ()
GET file:///C:/Users/Administrator/AppData/Roaming/Typora/themes/base.user.css 0 ()
```
All "./themes/*.user.css" files failed to get.
Need to be manually added to "./themes/".

**Comment by ZainChen** [comment]
second question:
Select [Unibody], open the Typora process, and click on Themes for the first time.
Console show:
"GET file:///D:/Software/Install/NoGreenInstall/Typora/resources/app//lib/bootstrape/css/bootstrap.css 0 ()"
Need to be manually added to "lib/bootstrape/css/bootstrap.css".

**Comment by ZainChen** [comment]
second question:
Select [Unibody], open the Typora process, and click on Themes for the first time.
Console show:
`GET file:///D:/Software/Install/NoGreenInstall/Typora/resources/app//lib/bootstrape/css/bootstrap.css 0 ()"`
Need to be manually added to "lib/bootstrape/css/bootstrap.css".

**Comment by ZainChen** [comment]
second question:
Select [Unibody], open the Typora process, and click on Themes for the first time.
Console show:
```cpp
"GET file:///D:/Software/Install/NoGreenInstall/Typora/resources/app//lib/bootstrape/css/bootstrap.css 0 ()"
```
Need to be manually added to "lib/bootstrape/css/bootstrap.css".

**Comment by abnerlee** [comment]
No. Network error can be ignored.
