### ISSUE TITLE
When I use ctrl+v to insert images, there are two images in it.

### ISSUE THREAD

**Issue by thinkycx** [typora/typora-issues#2035]
Here is my typora image settings:
![image](https://user-images.githubusercontent.com/13138128/50203508-b7815a00-039c-11e9-89dd-8fa2c21fac11.png)

When I insert the picture, in typora:
![image](https://user-images.githubusercontent.com/13138128/50204033-683c2900-039e-11e9-9601-9b0934cc69b3.png)

In the folder, there are two in it and they are the same:
![image](https://user-images.githubusercontent.com/13138128/50204069-7db15300-039e-11e9-90c8-e37505365b51.png)

**Comment by zszhere** [comment]
i have the same question when i use the osx's screenshot tool,the img folder appears two same img files with different filename.
but when i copy file from other folder,this question doesn't appears.

**Comment by zszhere** [comment]
like this:
![image](https://user-images.githubusercontent.com/12715675/50232926-3ef6b980-03ed-11e9-84e4-0ef19344b69b.png)

**Comment by abnerlee** [comment]
#2028
