### ISSUE TITLE
Changing theme in Theme menu does not change the theme

### ISSUE THREAD

**Issue by jtoumey** [typora/typora-issues#2038]
First, thanks for your work on this great piece of software.

_Windows version_: Windows10 v1803
_Typora version_: 0.9.60 (fresh install)

Changing the theme in the _Themes_ menu does not actually change the UI theme. When I select one of the other options (e.g., `newsprint`), the UI theme remains as the default `github` theme. This default theme persists after restarting Typora. 

I've reinstalled after deleting all local settings and I still encounter the issue.

**Comment by jtoumey** [comment]
@abnerlee, Thanks for the response. 

* When switching themes, I do notice errors in the console: 
```
GET https://win.user.global/users$/jtoumey/AppData/Roaming/Typora/themes/github.css 0 ()
attr | @ | frame.js:1
-- | -- | --
  | j | @ | frame.js:1
  | attr | @ | frame.js:1
  | setTheme | @ | frame.js:1
  | (anonymous) | @ | VM289:1
  | (anonymous) | @ | VM289:1
  | electron.ipcRenderer.on | @ | C:\Program Files\Typ…eb-frame-init.js:36
  | emit | @ | events.js:182
GET https://win.user.global/users$/jtoumey/AppData/Roaming/Typora/themes/base.user.css 0 ()
setTheme | @ | frame.js:1
-- | -- | --
  | (anonymous) | @ | VM289:1
  | (anonymous) | @ | VM289:1
  | electron.ipcRenderer.on | @ | C:\Program Files\Typ…eb-frame-init.js:36
  | emit | @ | events.js:182
GET https://win.user.global/users$/jtoumey/AppData/Roaming/Typora/themes/github.user.css 0 ()
setTheme | @ | frame.js:1
-- | -- | --
  | (anonymous) | @ | VM289:1
  | (anonymous) | @ | VM289:1
  | electron.ipcRenderer.on | @ | C:\Program Files\Typ…eb-frame-init.js:36
  | emit | @ | events.js:182
```
* CSS themes do exist. When I click _Open Theme Folder*, I see the six default themes (*.css files and folders)

**Comment by abnerlee** [comment]
What is `https://win.user.global` ? are you keeping your personal data on a network position?

**Comment by jtoumey** [comment]
Themes are stored on a network user profile. Is this not preferred? Should I store them elsewhere?

**Comment by abnerlee** [comment]
From the log, Typora cannot load `https://win.user.global/users$/jtoumey/AppData/Roaming/Typora/themes/github.user.css` successfully. 

I cannot reproduce this issue since I do not know how to put user profile into `https://win.user.global/users$/jtoumey`
