### ISSUE TITLE
u200b instead of tab

### ISSUE THREAD

**Issue by aschbacd** [typora/typora-issues#2039]
Dear typora team,

why does typora always insert \u200b before a tab?
I'm using mkdocs to create a static page out of my markdown files, but mkdocs can't interpret <200b> as white space. Would it be possible to leave tabs as they are instead of replacing them with u200b tags?

Best regards

Dominik Aschbacher

**Comment by abnerlee** [comment]
You cannot insert a tab before a paragraph, Markdown will interrupt it as code block.
