### ISSUE TITLE
vmatrix can't be represented in DOCX in the right way

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#2041]

**Comment by retsyo** [comment]
I am using Typora 0.9.60(beta) on win7 64 bits. For the equation
```
$$
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0 \\
\end{vmatrix}
$$
```

as the attached images said, the exported PDF does well, but DOCX has a too short vertical line which is expected to meet the red line

![docx](https://user-images.githubusercontent.com/7960913/50389427-2aa41b00-0765-11e9-8c09-96f6de67e65c.png)
![pdf](https://user-images.githubusercontent.com/7960913/50389428-2b3cb180-0765-11e9-8043-8a7321786888.png)

**Comment by abnerlee** [comment]
#2105
