### ISSUE TITLE
The document has been saved, the code is missing when opened it again.

### ISSUE THREAD

**Issue by 1581052236** [typora/typora-issues#2044]
os: windows 10
version: 0.9.60

typora.log：

`INFO 2018/12/26 下午8:34:04  [ 'F:\\Soft\\Typora\\Typora.exe',
  'F:\\python\\0.md' ]
DEBUG 2018/12/26 下午8:34:04  app.openFile
INFO 2018/12/26 下午8:34:04  add Recent Document
INFO 2018/12/26 下午8:34:04  secondary instance would exit
INFO 2018/12/26 下午8:34:37  ------------------quit------------------
DEBUG 2018/12/26 下午8:34:49  init Sentry
DEBUG 2018/12/26 下午8:34:49  init Countly
INFO 2018/12/26 下午8:34:49  ------------------start------------------
INFO 2018/12/26 下午8:34:49  typora version: 0.9.60
DEBUG 2018/12/26 下午8:34:49  [ 'F:\\Typora\\Typora.exe',
  'F:\\python\\1.md' ]
DEBUG 2018/12/26 下午8:34:49  app.openFile
INFO 2018/12/26 下午8:34:49  addRecentDocument
DEBUG 2018/12/26 下午8:34:49  F:\Typora\resources\app\locales\zh-Hans.lproj\Menu.json
ERROR 2018/12/26 下午8:34:49  (node:5228) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by abnerlee** [comment]
same with #2010?

**Comment by 1581052236** [comment]
> same with #2010?

yes
