### ISSUE TITLE
Line breaks is not worked in list when output to html, pdf, etc.

### ISSUE THREAD

**Issue by abc1236762** [typora/typora-issues#2045]
I already set `Whitespace / Line Break` to `Preserve ...` both in Preference.
![default](https://user-images.githubusercontent.com/11353779/50447001-33f2da80-0953-11e9-816f-70b24a456134.png)

Line Breaks is worked fine on typora, but when output to html, Line Breaks not worked in list.
![default](https://user-images.githubusercontent.com/11353779/50446925-a31bff00-0952-11e9-8e11-c43b4786bfe9.png)
Also happened on output to pdf.

**Comment by abnerlee** [comment]
#2005
