### ISSUE TITLE
copy file content to typora, images copied to assets/*.png, but not change the syntax ![...](...)

### ISSUE THREAD

**Issue by hitzhangjie** [typora/typora-issues#2047]
copy file content to typora, images copied to assets/*.png, but not change the syntax ![...](...) in file content. If I delete old pictures referenced, this markdown image reference will be broken.

**Comment by abnerlee** [comment]
version?

**Comment by hitzhangjie** [comment]
Version 0.9.9.19.4 (1355)
Local image

**Comment by azhenge** [comment]
0.9.9.22 (1979) fixed
