### ISSUE TITLE
Export to PDF font-size issue

### ISSUE THREAD

**Issue by Penguinmarco** [typora/typora-issues#2048]
Can someone please tell me where I'm going wrong. Could not find the answer in forum, the answers suggest it should be possible but it doesn't seem to work.

When exporting to PDF. The font size does not alter from the default. I've changed the CSS which alters and displays correctly in the Typora UI. But when I export to PDF the font size is not replicated.

```
html {
    font-size: 11px;
}
```

```
@media print {
    html {
        font-size: 11px;
    }
    table,
    pre {
        page-break-inside: avoid;
    }
    pre {
        word-wrap: break-word;
    }
}
```
Windows 7, Typora 9.60 (BETA)

**Comment by abnerlee** [comment]
Could you provide the font-size of exported PDF?

**Comment by Whadup** [comment]
I have the same issue. If I activate the dev-mode and look at my document in typora with "force print media style", all the fonts have the right font size, e.g. h1 has 14 pt. When I export it to pdf, everything becomes huge, I think the pdf has at least font-size of 20pt.
