### ISSUE TITLE
Menu bar color

### ISSUE THREAD

**Issue by joshcangit** [typora/typora-issues#2050]
**Issue with UI not really a bug report**
May be related to Issue #1912.
Menu bar background color is `#333333` while text color is `#111111`.
Although the text is visible, it is kind of unclear.
![screenshot typora](https://user-images.githubusercontent.com/33022160/50555074-39d41d00-0cbf-11e9-98bd-af675271d9c8.png)
**Feature request**
I suggest to have a dark background of `#333333` with text color of `#eeeeee`.
If possible, maybe have options for the menu bar such as . . .
- [ ] Light
> background-color: #eeeeee;
color: #111111;
- [ ] Dark
> background-color: #333333;
color: #eeeeee;
_Can't actually put in radio buttons here._

**Comment by abnerlee** [comment]
#1923
