### ISSUE TITLE
Crashes when exporting pdfs and randomly adding blank line after tabbed latex cell

### ISSUE THREAD

**Issue by LHS1998** [typora/typora-issues#2056]
Device: Mac Book Pro 2017, 13-inch
System: 10.13.4 (17E199)
Typora: 0.9.9.19.4 (1355)
Theme: Academic
The application will definitely crash while exporting pdf if the ignore blank lines and continuous spaces is checked. It randomly crashes when this function is not on.
Also, when restarted there will be randomly blank lines after any latex cell which is after a list. You delete them, save and reopen, these lines appears after other cells. 
And when a list in the list is added or added some html cell, the highlight in the source code mode is totally a mess.
A sample file is attached. All rights of this file is reserved.
[3 土中的应力.zip](https://github.com/typora/typora-issues/files/2726848/3.zip)

**Comment by abnerlee** [comment]
#1998
