### ISSUE TITLE
Sometimes impossible to undo bullet on item

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#2057]
This issue regularly gets me and is extremely annoying. The only fix I'm aware of is to use source code mode to manually fix the markup.

Example steps (though happens at other times)

1. Create some items in a list
1. Shift-Enter to add line break
1. Decide want the item to not be a part of the list - can't

In repro GIF, it's impossible to get item C to not be a part of the bulleted list. 

- Hitting Enter just makes more bullets.
- Hitting Backspace always appends it to the previous bullet.
- Toggling unordered list from menu makes entire list not be bulleted, not just the current item

Hitting Enter at the start of such item should escape the bulleted list and put item C at the same level as item D.

![2019-01-04 10 49 14](https://user-images.githubusercontent.com/1819485/50697011-0bcc4100-100f-11e9-8402-903809832794.gif)

**Comment by abnerlee** [comment]
use `shift+tab`, this may relates #1958

**Comment by AlexPasternak** [comment]
I knew there was a related issue, but couldn't find it before posting this. 

Shift-Tab is good to know, but unintuitive and non-standard, so I hope this gets actually fixed before 1.0 release or soon after. This is much more basic editor functionality than something like "find in files".
