### ISSUE TITLE
typo fix @ typora.io

### ISSUE THREAD

**Issue by sadikkuzu** [typora/typora-issues#2059]
There are some typos in web ui:

pref**e**rence in Code Fences

![](https://i.ibb.co/DRkNjcr/2019-01-04-23-08-45-Typora-a-markdown-editor-markdown-reader.png)

and flowchar**t**.js in Diagrams 

![](https://i.ibb.co/6rgc6Zm/2019-01-04-23-13-43-Typora-a-markdown-editor-markdown-reader.png)

**Comment by abnerlee** [comment]
fixed
