### ISSUE TITLE
flow diagram can't use `end`

### ISSUE THREAD

**Issue by fcying** [typora/typora-issues#2061]
version 0.9.60(beta)

```flow
st=>start: start
st2=>start: start2
op=>operation: my op
ed=>end:end
st->op->ed
```
result:  I can't see `end`
![image](https://user-images.githubusercontent.com/106934/50757748-44804a80-129b-11e9-8e5d-c6b091fd8c09.png)

If I use two `start`, It can work
```flow
st=>start: start
st2=>start: start2
op=>operation: my op
ed=>end:end
st->op->st2
```
![image](https://user-images.githubusercontent.com/106934/50757798-6083ec00-129b-11e9-8baf-02c06f91f213.png)

**Comment by abnerlee** [comment]
Please report to flowchart.js

You could try on https://flowchart.js.org/
