### ISSUE TITLE
Main website domain not connecting

### ISSUE THREAD

**Issue by diego-codes** [typora/typora-issues#2066]
I tried installing Typora today on my new laptop. First with homebrew, then manually via the website (https://typora.io/). Both failed because the website server is not establishing a connection.

The theme (https://theme.typora.io/) subdomain still works however.

**Comment by Alexilmarranen** [comment]
Confirm this issue on Debian.

**Comment by abnerlee** [comment]
cannot confirm this on https://www.uptrends.com/tools/uptime

**Comment by Alexilmarranen** [comment]
IP address (159.65.68.0) was blocked by Roskomnadzor in Russia.
http://blocklist.rkn.gov.ru

**Comment by abnerlee** [comment]
using ip 68.183.160.241 now, should solve "being blocked by Roskomnadzor"
