### ISSUE TITLE
Code fences not matching GitHub

### ISSUE THREAD

**Issue by fulldecent** [typora/typora-issues#2068]
Duplicate of https://github.com/typora/typora-issues/issues/2067#event-2062293872

---

This is a specimen which is rendered differently in GitHub and Typora.

---

The actual code:

<img width="419" alt="screen shot 2019-01-09 at 2 42 49 am" src="https://user-images.githubusercontent.com/382183/50884230-44c23800-13b8-11e9-839b-4c95fce30e6b.png">

---

Rendering in Typora:

<img width="515" alt="screen shot 2019-01-09 at 2 43 11 am" src="https://user-images.githubusercontent.com/382183/50884246-51469080-13b8-11e9-8b5b-ab7610242d46.png">

---

Rendering in GitHub (in issues or in the the viewer for like README.md:

<img width="776" alt="screen shot 2019-01-09 at 2 43 56 am" src="https://user-images.githubusercontent.com/382183/50884276-6fac8c00-13b8-11e9-8338-3a48b707cd7a.png">

**Comment by abnerlee** [comment]
How is 
```
- [ ] This is
       ``` json
       'a test'
       ```
```
being generated in Typora?

**Comment by fulldecent** [comment]
I cannot reproduce creating that file in Typora. Because I have used Typora for a long time and don't remember which versions I have used to edit the file.

And of course, regardless, it is possible to open such a file if found in the wild.

**Comment by fulldecent** [comment]
Here is such a file in the wild. It looks great in Typora but it is broken in GitHub.

https://github.com/fulldecent/swift4-module-template/blob/ce77f775d72e76c7e626f4bb81ec957ee0bb812b/Recipe.md

**Comment by fulldecent** [comment]
Closing. There have been lots of changes. Will reopen if applicable to a later version.
