### ISSUE TITLE
matrix renders wrongly

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#2071]
the new release fixed the problem I posted in https://github.com/typora/typora-issues/issues/2042#issuecomment-452780333

However, for the same math matrix code,
```
Here is the exported PDF
$$
\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0 \\
\end{vmatrix}
$$
```
renders a different result.

**Comment by retsyo** [comment]
sorry, I don't what is the problem with my net, I can't attach a image here. In a word, the `&` symbol are rendered as `amp;`

**Comment by abnerlee** [comment]
In exported docx or in Typora?

**Comment by abnerlee** [comment]
Please try update again, we pushed a new fix
