### ISSUE TITLE
cursor in code block is hard to fix some scope to copy content 

### ISSUE THREAD

**Issue by BruceZu** [typora/typora-issues#2072]
e.g. 
```java

many lines

```
I want to copy some lines or a few block in a line from the code block and find the cursor is hard to select the content in it. 
The same issue can be seen in other type code block e.g. xml block.

**Comment by abnerlee** [comment]
possible to provide more details?

such as Typora/OS version, is the cursor selection not working in code block or another issues?

**Comment by BruceZu** [comment]
the version is 0.9.61(beta)
OS: 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

It is hard to select scope in the code block with cursor + mouse left key. 
THANK YOU!

**Comment by BruceZu** [comment]
any progress now? 
it is very easy to retrigger this issue by input some code ,e.g. 
```java
int a=1;
int b=2;
int c=1;
int d=1;
int e=1;
int f=1;
```
then when you try to copy some lines in the code block you will find the area will tremble and make it hard to select some area in the code block.

**Comment by abnerlee** [comment]
Please try with the latest version
