### ISSUE TITLE
inline equation changes to $undefined$

### ISSUE THREAD

**Issue by davethehacker** [typora/typora-issues#2073]
In the new Version 0.9.61 (Windows), inline equations randomly change to $undefined$ whenever I interact with one of them. This seems not to happen with block equations.

[Typora video.zip](https://github.com/typora/typora-issues/files/2744946/Typora.video.zip)

**Comment by abnerlee** [comment]
Please check new update, just pushed a fix

**Comment by davethehacker** [comment]
that was quick! I can confirm, the bug is fixed. Thank's a lot!
