### ISSUE TITLE
Theme folder has multiple different themes, but the menu doesn't list it

### ISSUE THREAD

**Issue by devkapupara** [typora/typora-issues#2076]
Thank you for this awesome app. Been looking for something like this for a long time that has LaTeX support and also multiple programming languages. I have encountered a strange bug where although the theme folder contains the default themes and I added a minimalism theme, the menu doesn't list it. It only presents me with two options, Open Theme Folder and Get Themes. I have attached the screenshot below. Am I doing something wrong or will this get fixed in future release, since the Mac version is still in beta?
<img width="817" alt="screen shot 2019-01-11 at 3 13 18 am" src="https://user-images.githubusercontent.com/28474117/51030610-df547f80-154e-11e9-92b9-09d76180b844.png">

**Comment by abnerlee** [comment]
"Theme" menu will load themes on typora start, so please try restart Typora.

**Comment by devkapupara** [comment]
I restarted it several times, even restarted the system, but still doesn't show up.

**Comment by devkapupara** [comment]
Never mind, I uninstalled and installed Typora again and the Themes option was there. I think updating Typora broke that feature.
