### ISSUE TITLE
Math blocks fail to render when exited from.

### ISSUE THREAD

**Issue by eth-p** [typora/typora-issues#2078]
**Version:** Typora Mac 0.9.9.20.1 (1862)
**Demonstration:** https://youtu.be/0dBSGIJeRZ8
**Reproduction:**

1. Create a new document in Typora.
3. Create a new math block `$$`.
4. Enter math.
5. Exit math block (clicking, arrow keys, or Command+Enter)

**Expected Behaviour:** The math block is immediately rendered.
**Actual Behaviour:** The math block doesn't render until something above it is changed.

**Comment by abnerlee** [comment]
It is fixed in v0.9.9.20.2 since it is a blocking issue.
