### ISSUE TITLE
Crash while restoring from full screen

### ISSUE THREAD

**Issue by erickgirard** [typora/typora-issues#208]
**OS:** Windows Server 2012
**Typora version:** Latest (the one downloaded on the website)

**To reproduce :**  
- Start typora, type some text.
- Press F11 to go full screen
- Press F11 again to restore from full screen

**The following error will occur:**
![image](https://cloud.githubusercontent.com/assets/1326286/16459985/332872aa-3df3-11e6-8224-a0d2fcada681.png)

_Note that also the menu bar will disapear._
![image](https://cloud.githubusercontent.com/assets/1326286/16460116/e03e4bd6-3df3-11e6-9f0b-f56d14e1d766.png)

Note also that if you click on the application icon on the top left of the window, the whole application will freeze (can't type, can't move window, can't even quit or interact with the application menu) until the window lose focus (click somewhere else, any other application window or similar)
![image](https://cloud.githubusercontent.com/assets/1326286/16460171/2ae7d04e-3df4-11e6-9dc9-539f35974dd5.png)

**Comment by abnerlee** [comment]
Should be fixed already
