### ISSUE TITLE
show current fold full path info, etc

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2080]
when open multi folders, you can't easily tell the current file which folder it belongs to, there is no any indicator or label, my suggestion is this:

![image](https://user-images.githubusercontent.com/10832544/51071948-4039a000-1694-11e9-9741-be0184c4b288.png)

off course you can come up with better idea, anyway, this is quite urgent, so please better it asap.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by leewi9** [comment]
@abnerlee tried the newest mac version but didn't see the update, could you check again?

**Comment by abnerlee** [comment]
It shows on mouse hover
