### ISSUE TITLE
Installation of typora on linuxmint 19.1 fails

### ISSUE THREAD

**Issue by merlinuwe** [typora/typora-issues#2081]
I cannot install typora on linuxmint 19.1. Following the instructions for debian/ubuntu at [Typora on Linux](https://support.typora.io/Typora-on-Linux/)
gives me
```
uwe@lenovo[~]{1}: $ sudo add-apt-repository 'deb https://typora.io linux ./'
Fehlerhafte Eingabe, Paketquelle nicht hinzugefügt.

What can I do to install typora on linuxmint 19.1?


```

**Comment by abnerlee** [comment]
I don't know what "Fehlerhafte Eingabe, Paketquelle nicht hinzugefügt." mean.

Please check https://support.typora.io/Typora-on-Linux/

**Comment by merlinuwe** [comment]
Incorrect entry, package source not added.

Says google translate.
