### ISSUE TITLE
Delete line break not working, backspace does

### ISSUE THREAD

**Issue by maiklindner** [typora/typora-issues#2082]
related: #1607
version: 0.9.62 (beta), Windows 10

I'm not quite shure how to reproduce this. Deleting line breaks in render view is often not possible with the delete key. Going to next line and delete the line break with the backspace key works. 

I have a large file with 70k word and here I can reproduce it by typing - (minus) somewhere in a paragraph then adding a line break. Now if I try to delete the linebreak with delete key (cursor behind the minus and before the line break) it doesn't work. Nothing happens. I have to move to the next line and hit backspace.

In source mode it looks all the same, I can't see any difference.

**Comment by abnerlee** [comment]
Please try update
