### ISSUE TITLE
big display problem on mac

### ISSUE THREAD

**Issue by Abneco** [typora/typora-issues#2085]
When a markdown file is opened on my mac with typora (file created on typora windows), the characters display this transforms into a Chinese character (regardless of the theme used), if I open the file with another text editor it works normally.

all my markdown files that are read with typora its impacted

if I add a line and save with typora, I open the file with another text program the Chinese characters remain except for the new line add.

![image](https://user-images.githubusercontent.com/29584029/51089889-8f570200-1774-11e9-93c6-92fd422a08f0.png)

Typora Version 0.9.9.20.3 (1879) I don't know if it's related only to this version
macOS Mojave 10.14.2

I uninstalled and completely reinstalled typora it still doesn't work...

**Comment by abnerlee** [comment]
Is this about https://github.com/typora/typora-issues/issues/1337 ?
