### ISSUE TITLE
The theme and configuration will be reset each time you restart PC

### ISSUE THREAD

**Issue by imbadark** [typora/typora-issues#2089]
## System environments
- OS: Win10 RS4
- Typora Version: 0.9.62(beta) 64bit
- Frequency: Each time (After the computer reboots)

## Problem Description
As the title says, under the latest version of typora, whenever I change the default theme (such as whitey) and some configuration items, the next time I restart my computer, I will reset them after I turn on Typora. It’s frustrating to reconfigure them every day after the computer reboots . I looked at the various caches and configuration files in the directory but failed. (also checked F12(console))

If you need any log files or know if there is any good way to solve this problem, please reply to me, I will try my best to solve it with you. Thank you very much, I wish typora better and better.

Then there is a supplementary question, why does typora reset the previous configuration file or theme after each update, and then need to manually replace it in the history theme, feel that it should read a user-defined folder first, avoiding each time Update reconfiguration, and sometimes historical topics are reset

**Comment by abnerlee** [comment]
Will the theme be reset by exit and restart Typora?

**Comment by abnerlee** [comment]
The issue would be some folders are reset after you restart your PC.

**Comment by imbadark** [comment]
> The issue would be that some folders are reset after you restart your PC. It is not related to Typora.

Although this is true, the system version has not changed, only the latest version will be like this. Is there any way to help lock the file or see whom modified it?  
THX ~

**Comment by abnerlee** [comment]
The app data for Typora are stored `C:\Users\{username}\AppData\Roaming\Typora`, you could check whether the files in the folder will be reset or not after restart. You could also try remove the folder, restart, then start Typora.
