### ISSUE TITLE
My imaginary feature about handwriting support.

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#209]
Hi team,

There is one feature I've been thinking for several times, it might sound unreliable, however, if you could make it work, I'm sure Typora will become the most powerful note-taking app.

The thing is I've been thinking to buy this pen tablet  (http://www.wacom.com/en-us/products/pen-tablets) to take notes on my Mac, according to some guides, I can use this pen tablet with the OneNote, and some other apps. But, if I use OneNote or whatever other apps, and if I want to bring the notes into Typora, I have to export the notes to some kind of images, then import the jpg by its url to render it on Typora, which is the way Markdown deal with images.

The procedures above are too complicated, so that my idea is, can Typora provide a way which can let me directly pen-tablet notes on Typora? Is there some js can do this? or some other way?

By the way, I came up with this idea partly due to the weak support for tables\shapes\etc by Markdown, sometimes I find it too difficult to draw something, then I just want to write by hand.

thanks & best regards

**Comment by abnerlee** [comment]
Thanks for the suggestions.

Firstly, Typora should become a prefect markdown editor,
Then, Typora should improve its support for touch screen.

And, that will be the goal for Typora 1.x

After that, we will consider more amazing features, like handwriting support, for note-taking or knowledge management purpose, but maybe in another product.
