### ISSUE TITLE
Ordered list -> copy ordered list get error serial number when input all serial number

### ISSUE THREAD

**Issue by HJava** [typora/typora-issues#2090]
My Computer ：
![image](https://user-images.githubusercontent.com/3412268/51161629-18358100-18ce-11e9-96a8-4093d73a16af.png)

Typora Version and Config：
![image](https://user-images.githubusercontent.com/3412268/51161971-6e56f400-18cf-11e9-807c-9e57efa4bffc.png)
![image](https://user-images.githubusercontent.com/3412268/51162394-ee318e00-18d0-11e9-8c51-99b9ee1f711e.png)

Bug：
![bug](https://user-images.githubusercontent.com/3412268/51162464-38b30a80-18d1-11e9-8ff4-dc7176e28c21.gif)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by HJava** [comment]
Version:0.9.9.21.1 (1913) is ok
