### ISSUE TITLE
Sluggish performance in Source Code Mode or while adding newlines.

### ISSUE THREAD

**Issue by JadedTuna** [typora/typora-issues#2091]
Entering Source Code Mode in an empty file results in very sluggish typing experience. Characters take over a second to appear and do so in chunks. Interestingly enough, Typora starts using 50%+ of the CPU, but the CPU stays at a low frequency (as if the task is not considered important?).

As a matter of fact, typing in the normal mode is just slightly sluggish too. Pressing and holding Return (i.e. adding lots of newlines) results in the same kind of slowdown (the editor just hangs, and then adds several new lines at once). CPU does not boost in this situation either.

Specs:
Typora: 0.9.62 (beta)
Typora theme: Newsprint (same story with all the other themes)
Machine: ThinkPad x280
CPU: Intel(R) Core(TM) i5-8350U CPU
Memory: 16 GB (approx 14 GB free while testing)
Kernel: 4.15.0-43-generic
OS: Xubuntu 18.04

**Comment by abnerlee** [comment]
> Entering Source Code Mode in an empty file results in very sluggish typing experience.

You mean type even in an empty file is sluggish? Did you use any IME or non-English Keyboard?

**Comment by JadedTuna** [comment]
> You mean type even in an empty file is sluggish?
That's exactly what I mean.
> Did you use any IME or non-English Keyboard?
Nope, I am using a standard English (US) keyboard.

**Comment by JadedTuna** [comment]
Just updated Typora to version 0.9.64 (beta), no changes to performance.

**Comment by abnerlee** [comment]
Merge into #68. but I still failed to reproduce this.

Is https://codemirror.net/mode/gfm/ slow using Chrome on your Linux?
