### ISSUE TITLE
Wrong CTA on Install Language Support

### ISSUE THREAD

**Issue by dajvido** [typora/typora-issues#2092]
System: Windows 10 Version 10.0.17134 Build 17134 (up to date)
Typora version: 0.9.62 (up to date)

Steps:
- Click on Spell Check in the bottom bar
- Choose some non English language
- The pop up of not installed language show up on top
- The installation button open wiki on Line Break: https://support.typora.io/Line-Break/
- The selector (on the right on the button) shows something, but it's hidden under the editor section (the recording below).

![screencast-2019-01-15](https://user-images.githubusercontent.com/2753817/51210166-fd80fd80-1909-11e9-88b6-deae9ad6ca44.gif)

I have restarted the app few times, every time exactly the same behaviour.

**Comment by abnerlee** [comment]
fixed in new release
