### ISSUE TITLE
Subscript, superscript, text highlight & underline

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#2094]
Hey! 

Since the main markdown engine for Jekyll doesn't implement yet [subscript, superscript](https://github.com/gettalong/kramdown/issues/41) and text [highlight](https://github.com/gettalong/kramdown/issues/559) would be great if there were an option to change the markup of those markdown tags to hmtl tags (`<sub>subscript</sub>`, `<sup>superscript</sup>` and `<mark>highlight</mark>`) so can be used with a shortcut. 😃 

Could be possible to implement underline in an optional and similar way? I mean with the markdown markup `__underline__` or the html tag `<u>underline</u>` so can be easily implemented with a shortcut. 😃 I mean optional, because `__underline__` will conflict with commonmark.

**Comment by abnerlee** [comment]
#1433

**Comment by luispuerto** [comment]
>#1433

@abnerlee sorry I don't really understand why is #1433 is the same thing...

**Comment by abnerlee** [comment]
Allow user to switch between `<sub>subscript</sub>` and `^subscript^` , etc
