### ISSUE TITLE
[Feature Request] Add option to show source files like ("GIST"/Snippets-mode)

### ISSUE THREAD

**Issue by blurayne** [typora/typora-issues#2097]
I use Typora for Snippets/Tutorial-Management like GIST and find it quiet comfortable. I realised with the latest update that only md files do show up in the filetree sidebar. It would be nice to add an option to show all files again.

- File List
  - Show source files (whitelist)
  - Ignore dotfiles (blacklist)

- Source files (should be configurable and defautl to ".js, .go, .php")

Also "search sources" should be added as toggle into the file-search.

Source code highlighting would also be fine if you open source files.

**Comment by abnerlee** [comment]
#1753
