### ISSUE TITLE
Characters 'fl' are viewed as a Single Character. Is this on Purpose?

### ISSUE THREAD

**Issue by Joseph-Tortorelli** [typora/typora-issues#2099]
# Characters 'fl' are viewed as a Single Character

**OS:** Windows 10 Education 1809 64-Bit

**Typora Version:** 0.9.62

---

This is quite an odd bug. I found the bug while typing in 'flaw'. For some reason, typing 'fl' in Typora is marked as a single character (atleast to the typing cursor, or whatever its called). This seems to be for anything with 'fl' in it. You can try using the arrow keys to go back and it does in fact go back which you can prove by using the enter bar to create the 'l' on a second line. However, it is visually indicated as being after the 'l'.

Is this done on purpose?

**Comment by abnerlee** [comment]
No, it may relates to the font you use. (https://en.wikipedia.org/wiki/Typographic_ligature)

If so, 
You could try using different theme/font, check if your current system locale or keyboard layout is US English or not, or see if it happens in source code mode or not.

**Comment by Joseph-Tortorelli** [comment]
I installed Typora using Choco and that may be important to note. Let me play around with the fonts and see if anything changes.

It also occurs with 'fi'. Odd.

**Comment by abnerlee** [comment]
You could add custom css: `body {font-variant-ligatures: no-common-ligatures;}`, currently I'm not able to reproduce this.
