### ISSUE TITLE
Sometimes the inline math formula is shown as plain LaTeX code

### ISSUE THREAD

**Issue by wyf88** [typora/typora-issues#21]
Sometimes after I edit an existing LaTeX code between $$...$$, it remains as plain LaTeX code rather than math formula even after I move the cursor out of that chunk of LaTeX code. I have also encountered a case where all the $$...$$ are shown as LaTeX code. The only solution I found is to close the document and open it again.

**Comment by wyf88** [comment]
Not only for $$...$$, but also for $...$ too. For example: 
$\boldsymbol{\xi}_i \sim N(\mathbf 0, \boldsymbol{\Phi})$.
The bug does not show up every time, but it is quite often.

**Comment by abnerlee** [comment]
Hi, Thanks for your bug report.

Which version of Typora do you use ?
And this bug will occur occasionally after editing the inline LaTeX code, am I correct ?

**Comment by wyf88** [comment]
Hi, thanks for your reply! I'm using 0.9.8 os OS X. 
Yes, it is more likely to occur after editing the inline LaTeX code.

**Comment by truefalsename** [comment]
Hi, today I experience this bug too. I am running Version 0.9.9.1 and found out that it is enough to edit the inline formulas (I added a space after the first $) that weren't display properly in the exported pdf to solve the problem.

**Comment by abnerlee** [comment]
still exist in current version ?

**Comment by truefalsename** [comment]
Will let you know, it didn't happen all the times.

**Comment by abnerlee** [comment]
@truefalsename Do you mean sometimes it still happen on 0.9.9.x ?

**Comment by truefalsename** [comment]
It happened to me only once while running v 0.9.9.1. With newer versions everything worked well so far.

**Comment by abnerlee** [comment]
should be fixed after 0.9.9.2

Closed until new bug report

**Comment by wyf88** [comment]
Unfortunately, the bug can show up in the latest version occasionally.

**Comment by abnerlee** [comment]
still happening?

**Comment by truefalsename** [comment]
So far so good, here.
