### ISSUE TITLE
Typora menu items (not titles) are not visible

### ISSUE THREAD

**Issue by wambiditu** [typora/typora-issues#2104]
I tried this with 0.9.60 and 0.9.62, on Lubuntu 18.04.1 LTS for i386.  The OS was only recently installed, and I think Firefox (edit: and GIMP and Python) is the only other software installed beyond the default.  This menu problem happens only on Typora.

While the Edit and Paragraph menus are OK, the others like File and Help, and many of the submenus, are just all black.

![2019-01-19-021252](https://user-images.githubusercontent.com/24891895/51423555-231f3880-1b90-11e9-99e8-7a397737ac7e.jpg)

**Comment by abnerlee** [comment]
Are you installed Typora by `apt-get`, does binary file of Typora (https://typora.io/linux/Typora-linux-ia32.tar.gz) work correctly?

**Comment by wambiditu** [comment]
I think I installed Typora by apt-get from the typora linux repository.  When I run Typora and select the last item in the Help menu, it says I have version 0.9.64(beta).

I tried the download you suggested, and it shows the same menu problem.  It also says it is the same version from the Help menu (although the text in the version file says it is v3.0.14).

**Comment by abnerlee** [comment]
Would you try https://github.com/typora/typora-issues/issues/2171 to disable the GPU acceleration ?

**Comment by wambiditu** [comment]
I created the file /etc/X11/xorg.conf.d/90-disable-gpu.conf

    Section "Extensions"
        Option "DRI2" "Disable"
        Option "GLX" "Disable"
    EndSection

It does disable GLX.  It does not disable DRI2.  (DRI3 seems not present).  After log in, I am presented with some sort of system error, which it appears I can safely ignore.

The menus in Typora work perfectly after this change.  I do not use a lot of graphics-heavy applications on this machine, so I suspect I will not need to change this setting back.

**Comment by abnerlee** [comment]
You could try https://github.com/typora/typora-issues/issues/2171#issuecomment-462331780 to didable GPU only for Typora

**Comment by wambiditu** [comment]
Thank you!  I overlooked that.  

I removed the conf file, and edited the line near the end of the user JSON file to read "flags": [["disable-gpu"]] and that also works, without the system error.

Is there a chance that future Typora releases will default to disabled GPU (or try to guess whether GPU should be disabled)?
