### ISSUE TITLE
Typewriter mode setting not to automatically position cursor in middle of screen not honored

### ISSUE THREAD

**Issue by techczech** [typora/typora-issues#2105]
Even when I uncheck the option to keep caret in the middle of the screen:
![image](https://user-images.githubusercontent.com/904715/51425810-f3e0e980-1bd8-11e9-9f31-6badd06169d0.png)
The cursor always jumps to the middle of the screen when I try typing. This is not particularly ergonomic on a laptop plus it makes editing when still in typewriter mode awkward because the screen jumps around without warning.

**Comment by abnerlee** [comment]
You could turn on/off typewriter mode under `view` menu. There is a notification about this logic.
Preferences there are not on/off typewriter mode, but configures the behavior when typewriter mode is enabled
