### ISSUE TITLE
Typora locks up when searching content in large file

### ISSUE THREAD

**Issue by davinci0428** [typora/typora-issues#2107]
Typora locks up when I bring up the document search form using ctrl-f and then I type one or two characters in the search field. Then I have to close and restart Typora to even use it. It happens every time I try to search the document and it happens on Win 10 PC at work and my Win PC at home. It started to happen after I installed the latest update ( 0.9.62 (beta) ). Please fix this!

**Comment by abnerlee** [comment]
@davinci0428 Possible to send us the sample md file and search keywords? (<hi@typora.io>)?

**Comment by KanesYang** [comment]
Met the same issue, a MD file with 29608 words. Latest version on Windows

**Comment by xuuexu** [comment]
Same issue, about 20000 words. latest version on macOS

**Comment by davinci0428** [comment]
Sorry, the md file is full of proprietary information. But it appears the
bug is file size related. I just opened a small file (less than 300 words)
and the search function works fine. No lock-up. The file I've been having
the problem with has over 13,000 worlds. I see that the other respondents
mention large files too.

**Comment by kureus** [comment]
I can confirm I am also experiencing this issue on 0.9.9.21.1. Roughly 9k words. Typora locks up as the first character being entered is immediately searched upon. Once this first search is complete the rest of the search term I type is rendered on screen and the subsequent narrower searches appear to complete more quickly as you might expect

@abnerlee This issue appears to be agnostic of the text present, and purely about text length Opening a new file in typora and copying in approx 10k words of Lorem Ispum from https://www.lipsum.com and then searching lorem replicates the problem i describe, at least on my machine.

**Comment by luckytoilet** [comment]
I'm experiencing this issue too.

Steps to reproduce:

1. Create document with the word "abc" 10000 times.
2. Search for "abc".
3. Typora takes 100% CPU and stops responding.

On my computer, there is noticeable lag with as few as 50 "abc", and hangs completely with 1000 "abc". By comparison, Word and Vim have no problem with 10000 "abc".

**Comment by vassudanagunta** [comment]
@abnerlee seems like it is locking up while initializing live search suggestions / auto completion.

**Comment by abnerlee** [comment]
fixed "3\. stops responding" in new release
