### ISSUE TITLE
Wrong list formatting in quote

### ISSUE THREAD

**Issue by Songkeys** [typora/typora-issues#2108]
Version: `Version 0.9.9.20.3 (1879)`.

The list indents are missing in quote.

![md code](https://user-images.githubusercontent.com/22665058/51445446-d60ca500-1cfc-11e9-9a9f-48b9fcccf093.png)

![md view](https://user-images.githubusercontent.com/22665058/51445448-e1f86700-1cfc-11e9-985e-8ce34a76fdbc.png)

**Comment by abnerlee** [comment]
Fixed in new release
