### ISSUE TITLE
Backspace/Delete or even Cursor doesn't work

### ISSUE THREAD

**Issue by aoozdemir** [typora/typora-issues#211]
I'm on Windows 10 and not sure what causes this, but, in the middle of a writing, it locks itself. Cant delete/backspace or even click. 

`version 0.9.12 (beta)`

I'm testing various situations and trying to find what causes. Does anyone have the same problem?

**Comment by aoozdemir** [comment]
This hasn't been an issue since then.

**Comment by PlayMa256** [comment]
Im using the version 0.9.17 and this is happening with me, some random times, but still.
