### ISSUE TITLE
Auto generate some red dot.

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2112]
when type 4space and some word, the line will add a dot at the begin of the line. what's this and how to config get rid of it.
When it is in normal sentence  and normal mode, it will be not visable. 
When it is in normal sentence  and src mode, it will be visable. 

When it is in code  block ```   ```  and normal mode, it will be visable. 

<img width="386" alt="wechat1162386d37a2a7f1fc7f5ab456908f05" src="https://user-images.githubusercontent.com/1228446/51513682-15470d00-1e47-11e9-915e-9cff6a63a596.png">
<img width="626" alt="wechat08672d5456dc196d8261c1b7fb9606b3" src="https://user-images.githubusercontent.com/1228446/51513694-1bd58480-1e47-11e9-8ab1-87d2f1ebba1c.png">

**Comment by abnerlee** [comment]
4 space will convert the paragraph into code blocks. So a non-width whitespace will be inserted to keep the 4 space indentation. non-width whitespace in source code is rendered as red dot.
