### ISSUE TITLE
big base64 image can't not be displayed

### ISSUE THREAD

**Issue by fcying** [typora/typora-issues#2113]
I test two image, image1(29kb) can be displayed, image2(97kb) can't be displayed.

use `![1]()`

version: 0.9.6.2(beta)

[test.zip](https://github.com/typora/typora-issues/files/2781387/test.zip)

**Comment by abnerlee** [comment]
Typora won't use Markdown to render line that is too long for performance concerns.

I'll merge this into #88 since it is part of base64 support request
