### ISSUE TITLE
Mac shortcut for source mode?

### ISSUE THREAD

**Issue by fuzzy76** [typora/typora-issues#2116]
I see mentioned in other issues that at least Linux has a keyboard shortcut for source mode, but the Mac version doesn't. I know I can add manually from system settings, but it seems odd to be missing (it's one of the menu functions I use most).

**Comment by abnerlee** [comment]
Source code mode is designed for temporary modification, so we do not have plans to bring all features under normal mode into source code mode

**Comment by fuzzy76** [comment]
Aha! The forward slash (/) is on top of the 7 key on norwegian layout, which means command+/ is equal to command+shift+7 which is normally a shortcut for help search. I just disabled that in the system settings, and the shortcut reappeared (it was gone from the menu) and works! :)
