### ISSUE TITLE
emoji suggestions fail to show

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#2117]
Hey!

As you can see in the gifs below sometimes the emoji suggestion fail to show up when you type `:` and they don't show again until you close the document and open it again. The bug usually is trigger if you mistype or type a black space and then you delete. But not always seems to display the same behavior.  

![2019-01-22 15 19 12](https://user-images.githubusercontent.com/22882880/51538252-7c6dbd00-1e59-11e9-95e8-69e71bdecaff.gif)

![2019-01-22 15 26 11](https://user-images.githubusercontent.com/22882880/51538529-3402cf00-1e5a-11e9-8559-f8610e625e23.gif)

**Comment by luispuerto** [comment]
just to update a little bit... although 0.9.9.23 "Remove options for emoji autocomplete, it is now enabled by default." this bug still present 😞

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen

**Comment by luispuerto** [comment]
it's true that seems that it isn't happening... but now the caret is not longer in in the end of the line... even if you put it. When you hit enter, take part of the precedent word to the new line.

**Comment by luispuerto** [comment]
Also quotes —double, single ... and perhaps other punctuation— fail to show...

**Comment by abnerlee** [comment]
@luispuerto Could you fire a new issue?

**Comment by abnerlee** [comment]
@luispuerto could you fire a new issue?

**Comment by luispuerto** [comment]
I did in here #2417
