### ISSUE TITLE
File cannot be saved

### ISSUE THREAD

**Issue by Tomotoes** [typora/typora-issues#2118]
### Environment
OS: Windows 10 Profession 1803
Version : latest version

### Problem
1. Every time I press ' Ctrl + S 

this sign
![image](https://user-images.githubusercontent.com/32236122/51587237-1e091300-1f1b-11e9-84a4-91648f29fc9a.png)
won't go away and always show.

2. Then when I quit or select a different file, it will appear
![image](https://user-images.githubusercontent.com/32236122/51587266-38db8780-1f1b-11e9-890a-69a988958a54.png)

**Click ' Save ' Invalid, only click ' Discard '**

3. When I execute ' Save as ', I get an error
![image](https://user-images.githubusercontent.com/32236122/51587310-5c9ecd80-1f1b-11e9-8cbc-93b4f9a82096.png)

**Comment by Tomotoes** [comment]
![image](https://user-images.githubusercontent.com/32236122/51587593-3c234300-1f1c-11e9-8eae-f265b2489ae2.png)

**Comment by Tomotoes** [comment]
Information displayed in the console:
![image](https://user-images.githubusercontent.com/32236122/51588215-6413a600-1f1e-11e9-8c72-6944cc612c3c.png)

**Comment by Tomotoes** [comment]
When click ' Save As ', the information that is displayed:
![image](https://user-images.githubusercontent.com/32236122/51588282-a0470680-1f1e-11e9-8b45-57bae570b61d.png)

**Comment by Tomotoes** [comment]
Strangely enough, when I switch files that I can't save to another directory and then move back, Typora can save the file properly.

**Comment by abnerlee** [comment]
Does Typora have privilege to save the file? The file or folder may be set as READONLY

**Comment by Tomotoes** [comment]
> Does Typora have privilege to save the file? The file or folder may be set as READONLY

Well, it's really doubtful that just now I've set Typora to run mode for administrators, and it doesn't seem to be a problem anymore. Thank you so much :smile:
