### ISSUE TITLE
GFM compliance bug with emphasis and strong emphasis

### ISSUE THREAD

**Issue by SardineFish** [typora/typora-issues#2120]
In GFM Spec chapter 6.4 [https://github.github.com/gfm/#emphasis-and-strong-emphasis](https://github.github.com/gfm/#emphasis-and-strong-emphasis) The Rule 1 about emphasis and strong emphasis, and [Example 345](https://github.github.com/gfm/#example-345), [Example 372](https://github.github.com/gfm/#example-372)

`a**"foo"**` should be rendered as `<p>a**&quot;foo&quot;**</p>` : <p>a**&quot;foo&quot;**</p>
but in Typora, it is rendered as `<p>a**&quot;foo&quot;**</p>` : <p>a<strong>&quot;foo&quot;</strong></p>

**Comment by abnerlee** [comment]
similar / duplicate with #1789
