### ISSUE TITLE
Feature request: Ship with more practical themes

### ISSUE THREAD

**Issue by Yournished** [typora/typora-issues#2122]
The default themes Typora comes with aren't very good. They look very pretty, but have too much stylistic cruft that makes them hard to read and work with.

There are a handful of minimal themes, including the default, but all have the problem of text being too large. It is simply not practical for editing sizable documents (and if a document is small, what's the use of headings?) due to the size of the captions and the text. The ability to make user-defined themes is nice, but the location is obscure and the format is confusing. Really there should be a simple GUI theme editor, but I realize that may take a lot of work to implement. Until then, please add themes with more compact, minimal design that are suitable for longer documents.

For examples of themes with better readability, see Wikipedia default or motherfuckingwebsite.com

**Comment by abnerlee** [comment]
I think current theme is readable, motherfuckingwebsite.com is something I don't want to read.

Size of font can be adjusted in preference panel without dealing with CSS, but default theme use similar font size with motherfuckingwebsite

**Comment by abnerlee** [comment]
> I couldn't find this. Where exactly is it? Also, what about making only the headings smaller?

I update our doc for this https://support.typora.io/Custom-Font/#change-font-size, for other advanced tweeks, it will be covered by #2106

> Also, too long document should be avoid if readability is in high priority.

If we want do more to help users write high readability documents, Typora should be able to remind users, in some way, that the document he writing it too long. I would think that this is more effective than let users taking times tweak styles specific for long content, the later does not sounds like a key solution to us.

**Comment by Yournished** [comment]
>You could provide more details on this

What details would you like? I can make some screenshots of what I consider a more readable theme. I'd love to contribute actual CSS as well but last I checked the syntax for themes was very complicated.

>  I just updated our doc

Thanks for the pointer! It was pretty hard to find on my computer. Might I suggest making the font size in the standard units of pt rather than px?

> If we want do more to help users write high readability documents

I was under the impression that Typora's main use is to allow users to edit Markdown documents in a convenient environment with WYSIWYG features. All this time I've been recommending it to my friends and colleagues for their own general writing needs, but I was not aware that Typora was actually an educational program for people learning how to write. Perhaps I wasn't paying attention to the website. Sounds like I better not recommend unless someone explicitly asks for help learning to write better?

>that the document he writing it too long

Who is the judge of what document is too long? Is it you?

>more effective than let users taking times tweak styles specific for long content

This doesn't make much sense to me. Letting users customize visual style is completely separate than any reminders about readability. The whole point of Markdown is that the author defines semantic features, and how those are rendered is left to each reader and the software they choose to use. The effective solution for what you mention could be, for example, a new menu item like "Readability" under "View" that displays a dialog saying things like "the document is too long, consider breaking it up" for users who want automatic feedback on their writing style.

Being able to customize visual style is about letting users configure the software in the way they want. Ordinarily this is not so crucial if pre-existing themes are good, but I think in this case they are not very good. All suffer from the problem of not using a high readability Serif font, having headers be too big, and having too much vertical spacing.
