### ISSUE TITLE
Osx download button broken

### ISSUE THREAD

**Issue by borisrorsvort** [typora/typora-issues#2123]
On the public website, the download button is broken

**Comment by abnerlee** [comment]
see https://support.mozilla.org/zh-CN/questions/1028544

You may need let firefox ALLOW to download dmg file

**Comment by borisrorsvort** [comment]
I dont have issues downloading dmgs in general. It’s just I think the html that is wrong, you cant put links in buttons...
![typora a markdown editor markdown reader 2019-01-24 10-46-31](https://user-images.githubusercontent.com/39081/51669782-75fc5400-1fc5-11e9-8ca0-4a3bec13fd45.png)

**Comment by abnerlee** [comment]
Yes, it's our bug. https://stackoverflow.com/questions/17253410/link-inside-a-button-not-working-in-firefox

**Comment by borisrorsvort** [comment]
@abnerlee btw congratz for the app ! Looking forward to pay for it one day 👍

**Comment by abnerlee** [comment]
Fixed
