### ISSUE TITLE
Export Theme Selection

### ISSUE THREAD

**Issue by sheldonhull** [typora/typora-issues#2125]
I use a dark theme for editing, but when I export I need to export as the normal color for others to read. Can you make an option to select the desired theme to use when exporting content, so that it is not tied to the editor theme being used?

I've seen some related issues, but most seemed to focus on pandoc related themes.

**Comment by sheldonhull** [comment]
Just following up. This applies to the clipboard as well. I use dark theme, but when I copy into outlook or other tool the header colors are not easily seen as they are gray/white instead of a darker black color. This requires me to switch to light theme, copy and then switch back to dark if I want to make the typora contents readable.

**Comment by sheldonhull** [comment]
Still having this issue. I use dark mode, but then copying into outlook makes all the normal text colors very light and hard to see. I'd like the ability to set a copy default theme for rich text pasting.

**Comment by abnerlee** [comment]
https://support.typora.io/Export/#theme-1

**Comment by wibbuffey** [comment]
> Please note that on Windows / Linux version, only light themes are supported for PDF Export, as well as for print.

I'm having this issue on macOS too. Is this a problem with the docs or with Typora?

**Comment by bush911** [comment]
I know very little about coding, if I wanted to add this color as my PDF background,  what are the full codes I need to add to my theme.css?  
> #f3f2ee
