### ISSUE TITLE
Feature request: export documents to multiple image files

### ISSUE THREAD

**Issue by stefan38** [typora/typora-issues#2127]
I like to save web articles as web images and the possibility to export the markdown documents to multiple image files would be very useful for me. If a document is large then the output image file will have extremely big height. If the content of the source document could be fragmented, the output image files could be smaller and easier to view in various applications. This way I also could view the image articles on my Android phone and on Google Photos much easier.

**Comment by abnerlee** [comment]
We are less likely to support this, since this is a very rare request, and "pagination" is better supported on PDF format.

If you are looking for read it on Mobile, export as HTML, or PDF (#998), or use Markdown editor on Android would be the solution.
