### ISSUE TITLE
Ability to manually sort the sidebar

### ISSUE THREAD

**Issue by nicholas-johnson** [typora/typora-issues#2128]
I use alphabetized filenames for the chapters in my novel, for example:

```
001_chaptername.md
002_chaptername.md
```

This works, but it makes version control difficult if I have to change the order of the chapters, since changing the order means changing a lot of filenames.

It would be cool to have some sort of optional project.json in which I could specify the order of files. For me, this would put Typora on a par with Scrivener. 

An MVP could just have a single, manually edited project.json file that is used if it is present.

Typora is awesome BTW. The editing environment is superb. The best markdown editor out there.

**Comment by abnerlee** [comment]
#1680
