### ISSUE TITLE
Bold inside of Italic nesting problem

### ISSUE THREAD

**Issue by aoozdemir** [typora/typora-issues#213]
Normally, when you type `This *can be **nested** like* so.`, it should look like this;

> ![screenshot_73](https://cloud.githubusercontent.com/assets/6544741/16657910/e872ff0c-446c-11e6-9068-0346e73df8cb.png)

But in the editor, and also on github (weird), it looks like this. 

> This *can be **nested** like* so.
> ![screenshot_74](https://cloud.githubusercontent.com/assets/6544741/16658012/61cceb92-446d-11e6-99cd-285b48aebc7b.png)

**Comment by abnerlee** [comment]
Fixed in new verion
