### ISSUE TITLE
Graphical issue in Typora 0.9.9.21 sidebar

### ISSUE THREAD

**Issue by HealthyPear** [typora/typora-issues#2130]
<img width="706" alt="screen shot 2019-01-25 at 19 35 02" src="https://user-images.githubusercontent.com/17836610/51765736-e6e06080-20d8-11e9-9194-631831220c26.png">

**Comment by abnerlee** [comment]
What's your macOS version?

**Comment by abnerlee** [comment]
Fixed in style issue on order version of macOS, please try check updates again

**Comment by HealthyPear** [comment]
All good, thanks!
