### ISSUE TITLE
Auto-save on app focus loss

### ISSUE THREAD

**Issue by willismorse** [typora/typora-issues#2133]
Please consider adding support for automatic save and restore as Typora loses and regains app focus:
* auto-save the current document whenever Typora loses focus as the current app
* automatically detect and load of changes to the current document when Typora regains focus

Visual Studio Code and Jetbrains products both do a nice job of this. Using multiple editors simultaneously is a common workflow in development, where you might use Visual Studio Code, Typora and perhaps another specialized editor to simultaneously work on a collection of markdown documents.

Autosave would also solve a different use case where you work on a markdown document in multiple computers in a shared document repository with automatic sync, such as Dropbox or OneDrive. Many times I have worked in Typora at home, forgotten to explicitly save, and then gotten to work and found that Dropbox contains an outdated copy of the document. This gets into an ugly case of manual version reconciliation if I make changes at work. This is generally not a problem that happens with Visual Studio Code: I believe Visual Studio Code is autosaving when the computer goes to sleep, as many times I have seen my changes appear at work without switching applications before leaving home.

**Comment by abnerlee** [comment]
see https://support.typora.io/Auto-Save/
