### ISSUE TITLE
New Focus Mode: header sections

### ISSUE THREAD

**Issue by willismorse** [typora/typora-issues#2134]
Please consider adding an additional focus mode: Header section. This would apply the standard Typora "focus mode" visual appearance to a selected header and all text underneath it, and visually de-emphasize everything outside that section.

Being able to apply focus to header sections from within the Outline, instead of the main text editor, would be even more convenient.

The motivation is that I work on long documents with large numbers of nested header sections, and I often spend considerable time authoring and editing at the section level. Being able to concentrate my attention on a particular section is a significant workflow enhancement.

**Comment by abnerlee** [comment]
relates #499
merge into #1570
