### ISSUE TITLE
Contents of .git folder showing in articles view

### ISSUE THREAD

**Issue by mjclemente** [typora/typora-issues#2135]
I'm seeing this after upgrading to Version 0.9.9.21.1 (1913) running MacOS Mojave 10.14.2.

In the left sidebar, the `master` and `head` files in the .git folder are showing. See below:

![image](https://user-images.githubusercontent.com/5348419/51805152-0fcb3780-2238-11e9-9c76-2a8dbfdae9a5.png)

**Comment by Fastidious** [comment]
@mjclemente that wasn't happening before? As far I remember, Typora will show the contents of the directory you open. What do you see on `File List` (instead of `Tree View`)?

**Comment by mjclemente** [comment]
Ok, a few clarifications:

- The .git files do not appear when I first open the folder.
- They appear after only after I do a commit in the directory.
- They only appear in Article view - they're not present in the File Tree view.
- It may not be new to this build; given that it only happens after a commit, I may have just missed it in the earlier build. At the time I opened the issue I had only been using Typora for a few days.

I can reproduce it, so if you need I can create a screen capture demonstrating it.

**Comment by abnerlee** [comment]
should be fixed in new release
