### ISSUE TITLE
Source Code Mode Highlight do not consistent with the preview

### ISSUE THREAD

**Issue by tan-wei** [typora/typora-issues#2137]
version: 0.9.64
OS: Windows 10

The syntax highlight in source code mode of the code below is 
`## Chapter 2. Getting Started
1. Basic CMake Usage and Syntax
   ```cmake
   command(args...)
   ```
2. Running CMake form Command Line
   - ```
     cmake -DCACHE_VAR:TYPE=VALUE ...
     ```
   - ```
     cmake --build <dir> [options [-- [native-options]]]
     ```
     Options:
       * `<dir>` Project binary directory to be built
       * `--target <tgt>` Build `<tgt>` instead of default targets
       * `--config <cfg>` For multi-configuration tools, choose `<cfg>`
       * `--clean-first` Build target `clean` first, then build
       * `--` Pass remaining options to the native tool

## Chapter 3. Key Concepts
`

![source code](https://user-images.githubusercontent.com/28227509/51811399-b1f62880-22e7-11e9-8fe8-f48b989aba5f.png)

The preview is：
![preview](https://user-images.githubusercontent.com/28227509/51811410-b91d3680-22e7-11e9-96e5-bb453a9e8200.png)

It seems that the syntax after `cmake` block is not closed correctly.

**Comment by abnerlee** [comment]
#1638
