### ISSUE TITLE
Feature suggestion: Keyboard shortcut time stamp

### ISSUE THREAD

**Issue by Ni-Ar** [typora/typora-issues#2139]
It'd be cool to have a `cntrl + T` or similar to automatically print current time.
Same thing for today's date with `cntrl + D`.
Thanks!

**Comment by abnerlee** [comment]
#1052

**Comment by AlexPasternak** [comment]
See my comment in the linked issue, @Ni-Ar. I do this every day with Keyboard Maestro, but really almost any text expander app will do this basic functionality.

**Comment by thob** [comment]
there might be a solution for this with Typora plugins see https://github.com/typora-community-plugin/typora-plugin-note-snippets
