### ISSUE TITLE
No updates on Linux

### ISSUE THREAD

**Issue by farzadmf** [typora/typora-issues#2140]
Hi,

I have a quick question: on my Windows machine, I see Typora being updated (and I'm using Chocolatey), and my version on Windows is now `0.9.64`, but on Linux (Ubuntu) is still `0.9.60`.

I have used the "official" instructions to install on Ubuntu, so I was wondering whether I need to do something to get the updates or the Linux package is not up to date with the Windows one?

Thank you for this great product

**Comment by abnerlee** [comment]
Update on Linux is handled by ubuntu system, via `apt-get` related command
