### ISSUE TITLE
New bug in "Copy as HTML Code"

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#2141]
Starting with version 0.9.9.20 (0.9.61), copying as HTML code appears to remove the line breaks. That means when pasting the code I get one big chunk of text. 

The top is what pasting from previous versions looked like. The bottom is what the current version produces:

![image](https://user-images.githubusercontent.com/19582721/51843954-18784800-22e2-11e9-8a4c-6397b07eb9a5.png)

**Comment by abnerlee** [comment]
Try check updates again?

**Comment by xebico** [comment]
You are a gentleman and a scholar. Thank you!
