### ISSUE TITLE
Mermaid gantt not rendering correctly

### ISSUE THREAD

**Issue by aalvesdasilva** [typora/typora-issues#2142]
The Mermaid gantt diagram are not rendering correctly, using Typora version 0.9.64 (Beta) on Windows 10. The section name overlap with date of the tasks regardless of the length of the text.
Here's a little test code:
```mermaid
gantt
dateFormat YYYY-MM-DD
section S1
T1: 2014-01-01, 9d
section S2
T2: 2014-01-11, 9d
section S3
T3: 2014-01-02, 9d
```
The gantt diagram looks like this in Typora:
![image](https://user-images.githubusercontent.com/29492648/51973263-1d213580-2475-11e9-9bd3-05238ba5bc34.png)

Using Mermaid Live Editor it it renders like this:

![image](https://user-images.githubusercontent.com/29492648/51974092-0a0f6500-2477-11e9-922d-68b78cad3883.png)

I also have problems with the dimensions of the diagrams produced using mermaid when I export to e.g. pdf, but this may be related to what is causing this problem.

**Comment by abnerlee** [comment]
should be fixed
