### ISSUE TITLE
Broken footnotes on export to PDF or HTML since update 0.9.9.21 (beta)

### ISSUE THREAD

**Issue by mklilley** [typora/typora-issues#2143]
Hi,

Totally in love with Typora so thanks for taking the time to create such a great piece of software.

Today I noticed a bug with footnotes when you export to PDF or HTML which wasn't present before 2019/01/24.

The footnote numbering gets messed up as soon as you have one referenced inside a bullet point.

Steps to reproduce bug:
1 - Create a md file with the following content
```
test[^a]

- test2[^b]
- test3[^c]

test4[^d]

test5[^e]

test6[^f]

footnotes

[^a]: Test
[^b]: Test2
[^c]: Test3
[^d]: Test4
[^e]: Test5
[^f]: Test6

```
2 - Export to HTML 

You end up with this
![screenshot 2019-01-30 at 17 02 57](https://user-images.githubusercontent.com/7937044/51998684-01d41b80-24b1-11e9-8fcd-392bfcdb7a36.png)
3 - Remove the list so that your md looks like this
```
test[^a]

test2[^b]

test3[^c]

test4[^d]

test5[^e]

test6[^f]

footnotes

[^a]: Test
[^b]: Test2
[^c]: Test3
[^d]: Test4
[^e]: Test5
[^f]: Test6

```
and all is well again as shown below
![screenshot 2019-01-30 at 17 05 39](https://user-images.githubusercontent.com/7937044/51998827-4cee2e80-24b1-11e9-8ac1-dbb569d64cda.png)

**Comment by mklilley** [comment]
Forgot to say that I'm running this in Mac OS Mojave using Typora 0.9.9.21.1 (beta)

**Comment by liuzhenqi77** [comment]
Same on Windows 10 using Typora 0.9.9.64 (beta), please fix asap!

**Comment by liuzhenqi77** [comment]
Also, it would be nice if HTML export could show the tooltip of footnote contents on hovering over, like that rendered in Typora.

**Comment by abnerlee** [comment]
should be fixed
