### ISSUE TITLE
If multiple documents are open, the UI forgets which ones have been edited

### ISSUE THREAD

**Issue by ricardoalcocer** [typora/typora-issues#2144]
If you open a document on the sidebar, the titlebar says "edited" when changes have been made.

If you open a second document, that one hasn't been edited.  However, if you go back to the previous one, the "edited" on the titlebar has disappeared.

**Comment by ricardoalcocer** [comment]
Version 0.9.9.21.1 (1913)

**Comment by Fastidious** [comment]
This can be replicated, it is a valid issue. Occurring to me under macOS `10.14.2 (18C54)`, Typora `0.9.9.21.1 (1913)`

**Comment by abnerlee** [comment]
You will need to enable "Ask to keep changes when closing documents" following https://support.typora.io/Auto-Save/ or the modification are already saved.

**Comment by abnerlee** [comment]
You will need to enable "Ask to keep changes when closing documents" following https://support.typora.io/Auto-Save/ or the modification are already saved.
