### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2145]
Today I discovered the syntax that Typora can render: what a joy and it is impressive indeed. I did not realise how impressive until I looked at a site listing all the Github flavoured emojis. And although I have not tried them all, those I tried did work in Typora.

Not all Typora users will be familiar with the emoji side of Typora, and probably don't know the syntax, so as a suggestion it might be useful to add a link to a site with the full list, because in the section "emoji" you only mention ":smile:".

**Comment by Fastidious** [comment]
@DutchPete if you [do this](https://support.typora.io/Markdown-Reference/#emoji-happy):

> Emoji :happy:
Input emoji with syntax :smile:.
> 
> User can trigger auto-complete suggestions for emoji by pressing ESC key, or trigger it automatically after enabling it on preference panel. Also, inputting UTF-8 emoji characters directly is also supported by going to Edit -> Emoji & Symbols in the menu bar.

What do you get?

**Comment by DutchPete** [comment]
@Fastidious thanks for replying, although I am not sure why you did because I did not ask for help, I merely made a suggestion.

As for enabling emojis with the ESC, I don't understand how that works, I tried it but see no difference with auto trigger, which is what I have Typora set to.
In the menu bar (I am on Linux) there is nothing about emojis.

Like I said, I don't have a problem with emojis, I would just like others to be able to enjoy them too. For a full list of them I use [cheat sheet](https://www.webfx.com/tools/emoji-cheat-sheet/)

**Comment by Fastidious** [comment]
@DutchPete I am trying to figure out if you can already do what you are suggesting. I can, for example, but it might be platform specific (I use macOS).

Yes, there are [plenty](https://emoji.muan.co/) of [cheat](https://www.emojicopy.com/) sheets [online](https://emojipedia.org/). Maybe the best of them could be referenced to on [Typora Support](https://support.typora.io), which is already referenced to on the application's help menu.

**Comment by DutchPete** [comment]
@Fastidious yes, I can also do what I suggested. I do appreciate the 3 sites you referenced :+1:  :clap:  :joy:

**Comment by abnerlee** [comment]
> so as a suggestion it might be useful to add a link to a site with the full list, because in the section

There are auto suggestions for emojis (input `:` + any alphabet), is that not enough? Also, you could input Emoji using system IMEs/functions (https://www.imore.com/how-to-use-emoji-on-your-mac, https://www.pcworld.com/article/3223429/windows/windows-10-how-to-type-emoji-on-your-pc.html)

**Comment by DutchPete** [comment]
Abner, please do not regard my suggestion as a negative criticism; I can assure you that I am in love with Typora and keep telling people about it on forums and elsewhere. As far as I am concerned it really is the best, nicest markdown editor around. FYI, I recently switched from Windows to Linux, and the 1st non-listed program I installed was ..... you guessed it: Typora.

To answer your question: the auto-suggestions are very useful indeed, but sometimes it is useful to have a full list of all of them. Having said that, I realise that an interested user can search on internet her/himself and find what they are looking for, which is what I did.

You did well to close this thread as it is now an unnecessary distraction for you.

**Comment by abnerlee** [comment]
@DutchPete I'm not considering it as criticism, but just want to know is "autocomplete" function not enough for users, who does not know all available emojis, to input emojis he/she what?

**Comment by DutchPete** [comment]
After more than 1 year of using Typora I stumbled upon the emoji feature by accident. That is probably an oversight on my side, but even when I found it I did not realise the list of emojis was so big *and* that Typora supports so many of them.

The idea behind my suggestion was to make sure that users are well aware of this feature and how much it offers, I would like users to fully appreciate all Typora has to offer.

**Comment by markhu** [comment]
related to issue #1357

**Comment by DutchPete** [comment]
> related to issue #1357

Thanks for you input markhu. I checked out that issue, and 1 thing that interests me is the coloured emojis in Linux. I have switched from Windows to Linux Mint and wonder if you know if there is a way to get the emojis rendered in colour in Typora.

**Comment by markhu** [comment]
So far, I've only used Typora under two OSes: Windows 10, and Ubuntu 18.04.2 --and both have color emoji/icons :sweat_smile: The thing I'm curious about is how to find a list of which ones Typora supports. For instance :mountain: works in Linus, but not in Windows.

**Comment by DutchPete** [comment]
> So far, I've only used Typora under two OSes: Windows 10, and Ubuntu 18.04.2 --and both have color emoji/icons sweat_smile for me.
That's interesting: Linux Mint 19.1 - my version - is based on Ubuntu 18.04. I wonder if it has anything to do with XFCE (my version), Mate, or Cinnamon.

> The thing I'm curious about is how to find a list of which ones Typora supports. For instance mountain works in Linux, but not in Windows.
I once wondered about that too, but then I found that Typora supports such a broad range of emojis that it covers more than my needs :smile: You could open another issue about it to ask Abner.

**Comment by DutchPete** [comment]
@markhu  according to Abner the colour has to do with the font type. Emojis render in colour in my browser but not in Typora. As far as I can see it is not possible to change the font type in Typora, only the font size. So it must be the system font type that is important.

What is your default font type in Ubuntu 18.04? On Linux Mint 19.1 it is Noto Sans.
