### ISSUE TITLE
pandoc unrecognized option --pdf-engine=xelatex'

### ISSUE THREAD

**Issue by tsbertalan** [typora/typora-issues#2146]
On Ubuntu 18.04, with latest apt-installed pandoc, I get `unrecognized option --pdf-engine=xelatex'` when trying to export to .tex. I find I can solve this error by replacing "pdf-engine" with "latex-engine" in /usr/share/typora/resources/app/app/window/frame.js

**Comment by abnerlee** [comment]
What's the pandoc version?

**Comment by R2RT** [comment]
I had the same issue. It was changed from `latex-engine` to `pdf-engine` in pandoc 1.20. @tsbertalan just install newer pandoc, as one served by `apt` is really old.

```
pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/r2rt/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by abnerlee** [comment]
fixed in new release
