### ISSUE TITLE
Feature Request: Auto-Refresh File Tree

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2153]
I've noticed that if I create a new folder or file outside of Typora via Terminal or through other means, the file tree doesn't automatically refresh to update the changes. Instead, I have to manually go to the bottom of the file tree and press "Refresh Folder". It would put my mind at ease if this was built-in as it is with other editors. If not, at least allow us to map "Refresh Folder" to a keymap so it can be easily triggered.

![image](https://user-images.githubusercontent.com/12269792/52109684-f291c280-25c3-11e9-850b-88eea5679553.png)

System: macOS
Version: 10.14.2
Typora version: 0.9.9.21.1 (1913)

Besides that, I'm very very pleased with the editor experience. Keep up the great work!

**Comment by abnerlee** [comment]
This is auto-refreshed.

Please provide ways to reproduce this issue.

**Comment by justnealpatel** [comment]
Here is how I managed to replicate this issue:
- Open a custom folder with several subfolders created within (I have a Typora folder with 8 subfolders and some of those folders have subfolders as well)
- Open Terminal and `cd` into Typora folder
- Create new directory by using `mkdir` when no file is opened on Typora (should be blank slate in file view but should still see the custom Typora folder opened in the file tree
- From this, my test folder wasn't updating
- On a second try, the first level folder was updating when I tried creating a folder within the Typora folder but when I tried creating a file within that new folder, the file tree wasn't updating nor did creating a subfolder within that new folder update within the file tree.

**Comment by sushirod** [comment]
Same issue happened with me on Linux Debian Cinnamon. Same procedure:
* Opened terminal;
* Mkdir;
* Back to typora window and it wasn't there;
* Reopened typora window and it was there.
