### ISSUE TITLE
Not all Math Blocks are shown

### ISSUE THREAD

**Issue by TobiasScheinert** [typora/typora-issues#2156]
Hi,
I'm using the Math Block or LaTeX feature of typora. But not all blocks are shown (see the pictures). 

![typora_math_block_1](https://user-images.githubusercontent.com/14364560/52164277-071ea980-26ef-11e9-8ee8-94a308c834b9.PNG)
![typora_math_block_2](https://user-images.githubusercontent.com/14364560/52164279-09810380-26ef-11e9-9fef-f55fa1afffa0.PNG)

I'm using version `0.9.64` (shown in the ui under help -> about), `0.9.9.64` if I follow [https://typora.io/windows/dev_release.html](https://typora.io/windows/dev_release.html). Why this inconsistency? As OS I'm running Windows 10 (Build 17763.292). If you move the cursor around you may able to see all the blocks, or even all other combinations, depending of your cursor way.

Any ideas? If you need anything further from me, don't hesitate to ask ;-)

Greeting Tobias

**Comment by abnerlee** [comment]
How is this be reproduced? 

First input in source code mode, then switch to normal mode, or something else?

**Comment by TobiasScheinert** [comment]
> How is this be reproduced?
> First input in source code mode, then switch to normal mode, or something else?

yes, exactly. For example I add a second/third formula and switch from code mode to normal mode, and not all of the formulas are shown.

Greeting Tobias

**Comment by abnerlee** [comment]
fixed in new release
