### ISSUE TITLE
Fail to export some HTML blocks

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#2157]
As I am not familiar with HTML at all, so I can't describe how and why. I'm just to attach the result and the source.

What I expect and is correctly shown in Typora:

![tim 20190202223605](https://user-images.githubusercontent.com/33177912/52165401-57235d80-273b-11e9-8eb8-a82f2cd8c0ca.png)

What it is in exported file(PDF, HTML as well as image):

![tim 20190202223538](https://user-images.githubusercontent.com/33177912/52165403-5be81180-273b-11e9-92ce-6149d46082b5.png)

Source:  [作文的辩证思维.zip](https://github.com/typora/typora-issues/files/2824507/default.zip)

**Comment by UnnamedOrange** [comment]
The code I use:

```
<div style="display:inline;float:left;">自身正直，才敢去度量别人。</div><div style="display:inline;float:right;">总以自身标准去衡量别人。</div>
```

**Comment by abnerlee** [comment]
The attachment is not found, could you upload it again or just email us <hi@typora.io>?
