### ISSUE TITLE
Configure MathJax font

### ISSUE THREAD

**Issue by cprieto** [typora/typora-issues#2158]
It will be great to add a configuration setting for MathJax font selection. This can be changed in MathJax but I can't see a place in the themes or in the configuration settings to set the same option.

**Comment by abnerlee** [comment]
We do not have this option. We only embed one Mathjax font to reduce the "size" of Mathjax

**Comment by mcesar-rlacruz** [comment]
Hi again,

I still vote for this. The default TeX font is of the didone class and, as such, has a strong contrast between thick and thin lines, ball terminals and, in this font in particular, many letters with quite distinctive shapes and an overall "light" look. Any (La)TeX document using the Computer Modern font (the TeX font) is easily discernible from others, even for newcomers. It's not easy to blend this font with others (Google fonts offers quite a few examples of didone fonts, and the available ones use to exist in a single style —not even in italic or bold—. Of the safe web and MS core fonts, only Georgia classifies as didone, but it is much darker and less contrasted than CM, so they do not blend nicely.)

Enabling the other MathJax fonts will allow a wider selection of body fonts and a better blending.

All the remaining fonts in MathJax weight less than 10 MB that shrink to less than 3 when compressed. I think this is not a big issue now.

Thanks & regards.
