### ISSUE TITLE
several buttons in preference don't do anything (open theme folder, open advanced settings, recover unsaved drafts)

### ISSUE THREAD

**Issue by ukscone** [typora/typora-issues#2159]
Typora 0.9.64(beta)
ChromeOS 72 (Linux/Crostini/Debian)

The Open Theme Folder, Open Advanced Settings & Recover Drafts buttons don't do anything at all. Other items that would also bring up a file manager work as expected and buttons other than the 3 listed in the Preference window  also work as expected.

**Comment by abnerlee** [comment]
ChromeOS is not supported. 

See https://github.com/electron/electron/issues/12712

**Comment by ukscone** [comment]
that's actually not true. since the introduction of crostini (linux containers) for chromebooks towards the end of last year (well after the above electron issue) electron apps do work e.g. VSCode,... Also it's just three buttons that open directories that are not working, everything else seems to be fine including other things that open directories but hey ho

**Comment by abnerlee** [comment]
is `xdg-open` command available/installed? Please try install it.

reference: https://github.com/electron/electron/issues/7176

**Comment by ukscone** [comment]
I actually found out a couple of days ago there is a problem with xdg-open in crostini which now I know that you use xdg-open for those 3 buttons explains why it's not currently working. 

Will just have to wait to see if they "fix" it or not.

thanks

reference: https://www.reddit.com/r/Crostini/comments/aoauc2/jupyter_lab_in_crostini/

**Comment by ukscone** [comment]
just a quick update. it now sort of works in crostini on a chromebook. (fix was made in chromeos/crostini on March 3rd so should be in chromeos v73+) if you have VSCode also installed it opens the directory in that otherwise you get the directory opened in a browser tab. of course in a browser tab it's not much use but at least it does do something semi-sane. everything else seems fine
