### ISSUE TITLE
Image refresh problem

### ISSUE THREAD

**Issue by malimingwq** [typora/typora-issues#2160]
In the process of using typora, I found a problem that made me feel a little uncomfortable. After I inserted the picture a in my article, I found that I was not satisfied with this picture. I changed the picture a to the picture. b (picture a and picture b have the same name), but the picture in the article has not changed.
Typora version: 0.9.9.64 (beta)
OS: Windows 10

**Comment by malimingwq** [comment]
@abnerlee

**Comment by abnerlee** [comment]
If you rename image file, you will need to update the reference in Markdown file as well.
If you edit the image file, it will be refreshed automatically when the Typora window get focused again.

**Comment by alanzchen** [comment]
This is not working on Mac Version 0.9.9.25.3 (2897). 

@abnerlee 
> If you edit the image file, it will be refreshed automatically when the Typora window get focused again.
