### ISSUE TITLE
Screen shows on wrong monitor on launching Typora

### ISSUE THREAD

**Issue by domusW** [typora/typora-issues#2161]
In a two-monitor setup, when I launch Typora, it shows up on the wrong monitor (not the main one). It doesn't seem to remember screen location between sessions.

Version 0.9.64 on Windows 10 64

**Comment by abnerlee** [comment]
Typora will remember last closed position, or launch from existing window.

Could you provide more details like how to judge one open position is correct or not

**Comment by domusW** [comment]
To be more precise: this only seems to happen when the Typora window is **maximized**. When I open Typora, it opens on the wrong monitor. I then drag it to the correct monitor and make sure the window is maximized. I then close Typora. When I open Typora again, it opens once more on the wrong monitor.

When I don't maximize the window, the correct monitor is remembered.

**Comment by francis59** [comment]
Hi, @domusW @abnerlee , I also have a dual monitors setup (a laptop + a monitor),  and after I went back to 0.9.60 (beta) , the problem solved, it can remember it's previous location no matter it was maximized or not.

**Comment by jwfx** [comment]
Same issue with 0.9.65 on win10 x64

Window position is only retained when the Typora window is not maximized

**Comment by abnerlee** [comment]
"maximize" is in #2255, the issue about default maximized window position is fixed
