### ISSUE TITLE
LaTeX rendering as copyable image vs XML? 

### ISSUE THREAD

**Issue by elizhenning** [typora/typora-issues#2162]
(possible duplicate of [Math copy as HTML/image in Math block doesn't work](https://github.com/typora/typora-issues/issues/542))

I would like to copy rendered output (either from Typora directly or from HTML export) into Evernote. However, the rendered LaTeX SVG disappears when I paste. It seems to work fine with mixed text/SVG from Wikipedia, for example the display equations in the first paragraph of [https://en.wikipedia.org/wiki/Tensor_product](https://en.wikipedia.org/wiki/Tensor_product)
I don't actually understand what's going on and I have no idea if this request is technically reasonable.

Thanks for doing such a great job with Typora.

**Comment by abnerlee** [comment]
Math in https://en.wikipedia.org/wiki/Tensor_product are `<img>`, not `<svg>`. Evernote may not support "svg" tag. (see https://discussion.evernote.com/topic/25009-request-svg-support/)

We do not have plans to change the LaTeX rendering format globally, so this may be related to #304

**Comment by kbauer** [comment]
I came across this issue also in several other places. In particular I have the use-cases:

  - Pasting to JIRA
  - Pasting to Thunderbird.

In both cases using bitmap images (e.g. png) encoded as `data:` URIs would work.

By creating a custom Pandoc-to-HTML converted with the `--standalone` option, inlining works for linked images, but I could not find an option for converting the equations to images. `--gladtex` might  work, if I could find `gladtex` somewhere.
