### ISSUE TITLE
Allow mermaid configuration

### ISSUE THREAD

**Issue by nickshoe** [typora/typora-issues#2163]
That would allow to adjust rendering "issue", like the one presented in the screenshot.

![mermaid-render](https://user-images.githubusercontent.com/32668766/52265581-b39d9d00-2934-11e9-85f4-7b8525d6c50e.jpg)

A fast implementation idea could be allowing the user to specify the `mermaid` [config object](https://mermaidjs.github.io/sequenceDiagram.html#configuration) somewhere in `conf.user.json`:
```
/** For advanced users. */
{
  "defaultFontFamily": {
    ...
  },
  ...,
  "mermaid": {
    "sequenceConfig": {
      "diagramMarginX": 50,
      "diagramMarginY": 10,
      "boxTextMargin": 5,
      "noteMargin": 10,
      "messageMargin": 35,
      "mirrorActors": true
    }
  }
}
```

**Comment by abnerlee** [comment]
#374
