### ISSUE TITLE
Whitespace not replaced by %20 when importing images

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#2164]
When importing images Typora uploads it to .assets directory which is great. But when open the md file in another markdown editor no image will be shown. When in replace whitespaces in image path with %20 the image will be shown. 
I tried with iA writer on iOS and MacOS and marked2 on Mac OS. With Typora on Mac the image will be shown. 

Seems to spec issue since image links with whitespaces needs to be url encoded.

**Comment by Fastidious** [comment]
@Acidham that isn't Typora's fault. You name the images, just make sure you do not have spaces in their names. As you said, Typora renders them fine, regardless. If you want them more "universally" compliant, name them as I recommended above accordingly.

**Comment by Acidham** [comment]
@Fastidious I believe it is not about fault or no fault it is about to improve the Typora's experience. Usually I tend to use whitespaces as many other users are doing. Changing my thousands of files by removing the whitespace seems ridiculous to me just to make it compliant with Typora's implementation.  I believe running str.replace(' ','%20') when drag and trop files into Typora would be easier at least when Typora import the files into .assets directory and add md link to the document.

**Comment by Fastidious** [comment]
@Acidham Typora has no problems with spaces, that's what I said. It seems the other programs are the ones who can't render files with spaces on their names.

**Comment by Acidham** [comment]
@Fastidious Ok thats a true observation but on iOS I have to use other MD editors. So, it would be great to get whitespace to %20 into Typora.

**Comment by Fastidious** [comment]
@Acidham I certainly don't want my files to be renamed by Typora. Specially, I don't want spurious `%20` on their names, so this has my request has my 👎.

**Comment by Acidham** [comment]
@Fastidious Configurable would be an option...

**Comment by Fastidious** [comment]
> but on iOS I have to use other MD editors. So, it would be great to get whitespace to %20 into Typora.
@Acidham, the solution is to image files *without* spaces.

**Comment by Acidham** [comment]
I reached out to the devs of MD editor on macOS and got following answer:

> The original Markdown script, and many of the modern commonly used Markdown standards (like CommonMark) don’t support image URLs without percent encoding. As such, we’re not planning to support images without URL encoding.

**Comment by Fastidious** [comment]
@Acidham it is not the URL we are talking about here, it is the name of the image itself. I mean, don't get me wrong, if @abnerlee wants to do what you are requesting, he is the developer, not me. About percent encoding, images URLs can be used without it. This:

```![Test](https://example.com/test-image.png)```

is valid on markdown, without a need to do any percent encoding. If images URLs where not supported without percent encoding under markdown, it would have to be typed:

```![Test](https%3A%2F%2Fexample.com%2Ftest-image.png)```

**Comment by Acidham** [comment]
@Fastidious ok let us agree on that I understand your workaround, there is not need to explain it over and over again.

Let me describe my usecase better where not url encoding whitespaces produce problems in other MD editors than Typora:

1. I configured Typora to copy images added to the MD file: "Copy Image to ./$(filename).assets"
2. I am creating a note with filename "test with images.md" 
3. drag&drop an image with filename "screenshot123.png"
4. Typora copies the file to: "test with images.assets/screenshot123.png"

As you can see the folder is also not encoded. And I know, based on your explanations, that I need to prevent whitespaces in MD files as well. So generally I need to prevent whitespaces in images and md filenames when I would like to view and edit the file in another MD editor.

From my perspective this is kind of big limitations when using Typora.

**Comment by abnerlee** [comment]
#1520
