### ISSUE TITLE
background images in div/span

### ISSUE THREAD

**Issue by rgwilliamson** [typora/typora-issues#2167]
Hi 
this is potentially user error - but I am trying to create a header page for my document with the following html snippet.

`<div style="background-image: url('document_firstpage.jpg'); page-break-after: always;">TEST</div>`

i know the div is being picked up since the page break is being processes.  I have tried background-image and background to no avail.

Does Typora support background images within a div/span?

**Comment by Fastidious** [comment]
@rgwilliamson See [HTML Support in Typora](https://support.typora.io/HTML/) to see what's supported.

**Comment by abnerlee** [comment]
You could use
```
<div style="background-image: url('image_path.jpg'); page-break-after: always;">
TEST
</div>
```

But `image_path.jpg` should be a absolute path. We currently do not have plans, or it is in low priority to support parse relative path inside `CSS`
