### ISSUE TITLE
Intelligent Parsing of URLs via Keywords

### ISSUE THREAD

**Issue by vinayhegde1990** [typora/typora-issues#2168]
Typora Version: **0.9.9.21.1 (1913)**
macOS **10.13.6**

When we paste any URL in a Markdown file, it'd be nice to have some logic that either parses key words from it or retrieves the webpage's heading so that enclosing in [] will be easier.

For e.g: if we paste https://coderwall.com/p/4yz8dq/determine-os-x-version-from-the-command-line in a markdown file, 

It should parse it as **[Determine OS X version from the command line]** which is the heading of the webpage as well as the title of the article that can be clicked to open the pasted URL.

Please let me know if anymore information is needed.

**Comment by Fastidious** [comment]
@vinayhegde1990 how do you propose such approach would handle the use of Typora on a non-connected computer?

**Comment by vinayhegde1990** [comment]
@Fastidious - this could be resolved in a way similar to how Google Keep stores data locally when notes are edited offline & syncs on detecting an internet connection.

**Comment by abnerlee** [comment]
merge into #2415
