### ISSUE TITLE
"^" inside inline math

### ISSUE THREAD

**Issue by AidanDai** [typora/typora-issues#217]
typora 确实是个好产品，我用 Markdown 以来感觉最好的产品了，感谢你们团队的付出

但是今天我在写论文时发现这样的问题，如下

```
$ F ~y~ =  0.67 × D ~max~  ^1.5^ $
```
这样会报错
![image](https://cloud.githubusercontent.com/assets/11514661/16719580/b6bac1ee-475e-11e6-98d9-49eedb564011.png)

```
$ F ~y~ =  0.67 × D ~max~  ^1.5 $
```

效果是这样的：
![image](https://cloud.githubusercontent.com/assets/11514661/16719498/a01f8268-475d-11e6-9f6b-ae6b0141ac36.png)

**Comment by abnerlee** [comment]
`F ~y~ =  0.67 × D ~max~  ^1.5^ ` is not valid in TeX, `F ~y~ =  0.67 × D ~max~  ^1.5` is valid

**Comment by AidanDai** [comment]
thanks
