### ISSUE TITLE
Menu artifacts on Linux

### ISSUE THREAD

**Issue by werner-lehmann** [typora/typora-issues#2171]
On Kubuntu 18.10 and Typora 0.9.64 the main menu dropdowns are garbled. See https://i.imgur.com/ZSs4LgX.png. There are also other rendering artifacts on dialogs (preferences, about). The main window and the editor itself are not affected. Maybe #2104 is related although the described effect is different.

I installed Visual Studio Code to check the same with a different Electron based application, and it is not affected. This may be related to hardware acceleration since I have seen before that switching to software rendering in the compositor "fixed" it. This was a few days ago. However, the GPU is pretty standard: Intel integrated graphics HD 630. Right now that workaround does not work but I wouldn't want to do this on a permanent basis anyway. Maybe there is some switch to turn off hardware acceleration?

**Comment by skewty** [comment]
I noticed some rendering issues when I used this [SNAP package](https://snapcraft.io/typora-alanzanattadev).  Did you install by DEB?

**Comment by werner-lehmann** [comment]
I am using the ppa. No snaps if I can help it.

**Comment by abnerlee** [comment]
Please use `apt-get` way to install Typora if you did not install typora in this way.

Please try the binary version of Typora (https://typora.io/linux/Typora-linux-ia32.tar.gz or https://typora.io/linux/Typora-linux-x64.tar.gz)

Also, it may relates to your GPU, try click "Open Advanced Settings" in Typora's preferences panel, and then add/set
```json
{
   "flags": [["disable-gpu"]]
}
```
to disable GPU when launch Typora

**Comment by werner-lehmann** [comment]
"disable-gpu" did the trick. Thanks :)
