### ISSUE TITLE
Options to set reading speed

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#2172]
hi! 

What is the average reading speed of typora users? I have a document with 4248 words and typora estimates that can be read in 11 minutes. 

![screen shot 2019-02-11 at 18 37 56](https://user-images.githubusercontent.com/22882880/52578168-5752e580-2e2c-11e9-817c-10b9fe00ca40.png)

4248 / 11 = **386.18 words per minute.** 

>Many resources indicate that the average reading speed of **most adults is around 200 to 250 words per minute**. College students, probably because they must practice reading, move that **pace up a notch to around 300 words per minute**. To put this into perspective we can turn to public speaking and the comparison of the rate of speaking and the rate at which people can comprehend the spoken word.
>
>An experienced public speaker will deliver his or her message at a rate of about 160 words per minute. It is possible to speak more rapidly, but it is recommended that readers for recorded books speak at around this pace because it is comfortable for most listeners. However, some speakers – such as auctioneers – can speak at a rate of up to 400 words per minute. By comparison, we form thoughts at around 1000 – 3000 words per minute, which gives the average listener lots of time to wool-gather, plan menus, and argue with the speaker.

Source: https://www.irisreading.com/what-is-the-average-reading-speed/

I don't know about you... but I usually like to be conservative when I set the reading speed and usually set around 250wpm because it's the average mental reading speed of most people. 

>Mental readers generally read at approximately 250 words per minute. Auditory readers read at approximately 450 words per minute. Visual readers read at approximately 700 words per minute. Proficient readers are able to read 280 - 310 wpm without compromising comprehension

Source: https://en.wikipedia.org/wiki/Speed_reading#Types_of_reading

Where can we change the reading speed?

**Comment by abnerlee** [comment]
It's already supported

**Comment by luispuerto** [comment]
Where?
