### ISSUE TITLE
Style changes when export to PDF

### ISSUE THREAD

**Issue by arfaWong** [typora/typora-issues#2173]
Source in typora
![source](https://user-images.githubusercontent.com/8801749/52622323-87f65600-2ee4-11e9-9696-0c7bb1664958.png)

Export to pdf
![pdf](https://user-images.githubusercontent.com/8801749/52622331-8b89dd00-2ee4-11e9-8b70-4e7d97de62a8.png)

Export to pdf using the customize theme by changing several color in github.css file.
version 0.9.64(beta) Windows 10.

**Comment by abnerlee** [comment]
This may caused by the "json" language for the code fences not saved yet, you could first blue the "input" element, then do export again
