### ISSUE TITLE
Not possible to open a file with typora on GDOCS

### ISSUE THREAD

**Issue by khidr** [typora/typora-issues#2174]
I have several typora files on gdocs. I can open the ones that I create using typora, but as soon as some else edits them online in Gdocs with another editor, typora is no longer in the list of files as an "edit with" option

**Comment by abnerlee** [comment]
Registered file types are *.md, *.markdown, *.mkd, *.mdown, *.text, *.txt, etc. For other file formats, you could click "select other programs" and the select Typora.

**Comment by khidr** [comment]
Hi Abner,

Thanks for responding..That's the funny thing: the files all have a .md
extension and are in very straightforward simple markdown format. Still,
google doesn't recognise them as markdown..and does not suggest typora as
editor.
Gert




*___________________________________________*

 *Van Esveldstraat 87 *

*3572KL Utrecht*

*tel: 0681607741*

__________________________________

============================

   -
      - Ik schrijf regelmatige nieuwe muziek, die varieert van dance
      tot bezonken meditatief. Je kunt die muziek beluisteren op Soundcloud:
      The song that never was
      <https://soundcloud.com/khidr/the-song-that-never-was-final-version>
      A song for Imogen Heap. I've learned a lot just from getting the
      harmonisation the automation and the mix right. I choose to separate all
      vocal tracks into parts belonging to verses and the interludes and created
      different harmonies for each part of the song trying not to lose the
      overall harmonic unity.
      I 've added a small amount chorus and to the leading voice to soften
      it up a bit. I've worked on this track for several weeks but it was worth
      every minute of it.
      -

      Requiem for La Grande Guerre <https://soundcloud.com/khidr/war5>
      With this music, I tried to express the chaos and violence of war in
      the trenches. Halfway through you'll hear a mutilated version of the
      opening chorus
      of the Mattheus Passion by Bach and some hopeless cries "Wo hin"
      (Where to go? Whither?)
      Created on a modular system using Mutable Instruments Tides, Braids,
      Plaits, and Befaco, HSTA sequencers
      - Inner Ear Exploration
      <https://soundcloud.com/khidr/rising-from-silence>
      A composition I created using my modular system. It can never be
      repeated or reconstructed as you always have to dismantle the patch to be
      able to create something new.
      - MatrixBrute Sol <https://soundcloud.com/khidr/matrixbrute-solo-2>o
      The Matrixbrute is huge analogue synthesizer with a modulation matrix
      that enables you to connect its parts.
   - Endless Piano <https://soundcloud.com/khidr/endless-piano>
      Endless pleasantly meandering piano music.







ᐧ

**Comment by abnerlee** [comment]
> google doesn't recognise them as markdown

The file associate is registered into Windows, not google, I don't know how online apps choose local apps for editing, maybe only other online app is supported by GDoc
