### ISSUE TITLE
The exported PDF with Academic theme is broken when TOC was included

### ISSUE THREAD

**Issue by Yubyf** [typora/typora-issues#2177]
The error is same as #1563. Preview.app and Chrome shows normal.
![image](https://user-images.githubusercontent.com/1712837/52692754-bb49eb00-2f9f-11e9-9410-735ba8d2968f.png)

Typora version: 0.9.9.21.1(1913)
Acrobat Reader DC version: 2019.010.20091
Mac OS version: 10.14.3 (18D109)

**Comment by abnerlee** [comment]
Please provide a sample md file.

**Comment by Yubyf** [comment]
> Please provide a sample md file.

@abnerlee Here is my markdown example file and exported broken pdf.
⤵️
[md-example.zip](https://github.com/typora/typora-issues/files/2863175/md-example.zip)

**Comment by abnerlee** [comment]
Fixed in new release
