### ISSUE TITLE
The mermaid render issue

### ISSUE THREAD

**Issue by capvor** [typora/typora-issues#2178]
![image](https://user-images.githubusercontent.com/16610170/52703837-35876900-2fba-11e9-9e8e-d3f03d1ca85c.png)
_Drawing sequence diagrams using mermaid is not adjust when the text is too long like sequence._

_Next is the source code_
![image](https://user-images.githubusercontent.com/16610170/52704085-c0686380-2fba-11e9-9eb5-04b0fa137bf2.png)

**Comment by abnerlee** [comment]
See https://github.com/knsv/mermaid/issues/710

merge into #1661

**Comment by abnerlee** [comment]
should be fixed in 1.4.4
