### ISSUE TITLE
Cursor locked when deleting/backspace inline list 

### ISSUE THREAD

**Issue by X-43A** [typora/typora-issues#2179]
OS X 10.14.3 (18D42)
Typora Version 0.9.9.21.1 (1913)
Here's a video of the bug:

![typora_bug](https://user-images.githubusercontent.com/13090588/52712716-55546800-2f8d-11e9-8f6e-dc16de079089.gif)

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by X-43A** [comment]
@abnerlee 
I updated my first comment

**Comment by BruceZu** [comment]
Hi X-43A,
The https://user-images.githubusercontent.com/13090588/52712716-55546800-2f8d-11e9-8f6e-dc16de079089.gif looks wonderful. 
May I know how you make it?
Thank you!
Bruce

**Comment by X-43A** [comment]
@BruceZu 
> Hi X-43A,
> The https://user-images.githubusercontent.com/13090588/52712716-55546800-2f8d-11e9-8f6e-dc16de079089.gif looks wonderful.
> May I know how you make it?
Yes
> Thank you!
Thank you
> Bruce
I'm not sure which part you want to know so here's all of it:
1. I opened the keyboard viewer which shows which keys I'm pressing on my physical keyboard ([How to open Virtual keyboard on OS X](https://apple.stackexchange.com/questions/303710/onscreen-keyboard-for-mac-os-sierra));
2. Then I placed it on top of the app Typora as you can see in the gif;
3.Finally I just recorded the selected part with the new app screenshot (you can use quicktime as well) and converted the video (mp4) to a .gif online.

Hope this helps

**Comment by abnerlee** [comment]
fixed in new release
