### ISSUE TITLE
transparency on body tag in theme doesn't work

### ISSUE THREAD

**Issue by ujwaljain** [typora/typora-issues#218]
Hi,

I was trying to make typora window translucent by setting background color with some transparency. However, if you set transparent background css property on body tag, it shows some other window.
<img width="860" alt="screen shot 2016-07-11 at 4 14 22 pm" src="https://cloud.githubusercontent.com/assets/3633874/16749995/33ca7d86-4783-11e6-8dc8-44c8361a56b1.png">

**Comment by abnerlee** [comment]
The window itself cannot be translucent.

But it is possible to set a background image and make writing area transparent, for details, please refer:

http://support.typora.io/Backgound/
