### ISSUE TITLE
sidebar sometimes replaces characters with HTML Codes

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#2181]
If a heading contains a link, the link text is HTML escaped in the sidebar (certain characters are replaced with their HTML codes. The heading displays correctly in the document pane.

You can reproduce this by putting the following in a Markdown document and showing the outline view in the sidebar:

```
## [This'll be ugly & unreadable in the sidebar](https://commonkarma.org)
```

This heading will appear as follows in the sidebar: `This&#39;ll be ugly &amp; unreadable in the sidebar`

**Comment by abnerlee** [comment]
fixed in new release
