### ISSUE TITLE
Math equation is incorrectly exported to word

### ISSUE THREAD

**Issue by bifeng** [typora/typora-issues#2182]
I already read the old relate issues, but my problem is different.

System environment:
Typora 0.9.64
Windows 10

The equation in markdown:
```
$$
\begin{align*}
parse(s) &= \arg \max_{y \in \cal{Y}(s)} score_{global} (s,y) \\
score_{global}(s,y) &= \sum_{(h,m) \in y} score_{local}\phi(s,h,m)
\end{align*}
$$
```
```
$$\hat{y} = \arg \max_{y \in \cal{Y}} f(w,y)$$
```

The  equation export to word can't display, but just show the equation source code.

**Comment by abnerlee** [comment]
Typora uses Pandoc for "export to docx" function. If it is not supported by Pandoc, it will not work in Typora as well.

You could try use plain `pandoc` command to convert the sample markdown file into docx, and the math are not exported correctly, you may open an issue on Pandoc's Github
