### ISSUE TITLE
Wrong feedback channel promoted?

### ISSUE THREAD

**Issue by jcayzac** [typora/typora-issues#2185]
In Typora 0.9.9.21.1, the feedback menu opens `mailto:hi@typora.io`. I sent multiple messages there that never got any answer. Since the _real_ feedback channel is the issue tracker of this repo, it should open https://github.com/typora/typora-issues instead I think…

**Comment by abnerlee** [comment]
<hi@typora.io> is valid, if you did not get feedback in time (it may get filtered by spam, or we were too busy to miss it), please send mail again, or contact us by other channels, like in Github Issue.
