### ISSUE TITLE
Math blocks not rendering without text insertion cursor navigating

### ISSUE THREAD

**Issue by 0xff07** [typora/typora-issues#2187]
Sometimes math  blocks isn’t rendered unless text insertion cursor goes through the block:

![output](https://user-images.githubusercontent.com/17983661/52899090-fa3aa380-3220-11e9-9e11-31b11f3479bc.gif)

Here is the sample *.md file:
 
[example.zip](https://github.com/typora/typora-issues/files/2871844/example.zip)

Version of Typora is 0.9.9.21.1 (up-to-date when this is posted)

**Comment by abnerlee** [comment]
#2156
