### ISSUE TITLE
align* math block does not number equation

### ISSUE THREAD

**Issue by EvilPictureBook** [typora/typora-issues#2188]
Using \being{align*} does not number the equation at all (beta 0.9.64, win64)

For example, this will produce no equation number:

```
\begin{align*}
y(x) &= x^2\\
&= 5\\
& = z
\end{align*}
```

But it does work like this:
```
\begin{align}
\begin{split}
y(x) &= x^2\\
&= 5\\
& = z
\end{split}
\end{align}
```

Regular align environment will number each line as expected:
```
\begin{align}
y(x) &= x^2\\
&= 5\\
& = z
\end{align}
```

**Comment by abnerlee** [comment]
I'm not good at LaTeX, but I think this behavior is same with https://www.overleaf.com/learn/latex/Aligning_equations_with_amsmath

A cause is https://github.com/mathjax/MathJax/issues/2120

**Comment by EvilPictureBook** [comment]
You're right @abnerlee. Thank you for pointing that out.
