### ISSUE TITLE
Cross-Referencing doesn't work

### ISSUE THREAD

**Issue by aoozdemir** [typora/typora-issues#219]
When you cross reference a title and click on it, it doesn't jump to the named header.

**Comment by abnerlee** [comment]
How you do cross reference? (I mean the markdown syntax).

Have you try #191 ?

**Comment by aoozdemir** [comment]
So yeah, I found the problem. 

This is working.
```
[JSON-P](#the-nitty-gritty-of-json-p)
# the nitty gritty of json-p
```

This isn't, but should.
```
[JSON-P](#the-nitty-gritty-of-json-p)
# the *nitty* gritty of json-p
```

In order to make the late work link has to be like `#the-*nitty*-gritty-of-json-p`.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/1072

seems `*` should be ignored, test: https://gist.github.com/abnerlee/46a1cb3b48ec5f972dac609768be3c5c#the-nitty-gritty-of-json-p

**Comment by abnerlee** [comment]
Should be fixed in new release.

We could add auto-complete feature when creating inner link to prevent this in future updates

**Comment by akhildanturti** [comment]
how to use inline  cross reference in Typora inside the document

**Comment by abnerlee** [comment]
what do you mean by "inline cross reference" ?
