### ISSUE TITLE
Custom file descriptions for the files sidebar

### ISSUE THREAD

**Issue by christopher-wilson** [typora/typora-issues#2190]
In the files sidebar, each file has the filename and the first text in the file. It would be useful if we could display an alternative, maybe a pull it from the description tag in the YAML frontmatter.

**Comment by abnerlee** [comment]
Currently `title|subtitle|overview|summary|description|excerpt` in YAML will be used in file list as file descriptions. It is already supported.

**Comment by christopher-wilson** [comment]
Great. I can get it to work now. 

2 Questions:
1. Is it possible to get this in docs. Can't find any reference to this or the keys.
2. Is it possible to specify which keys are used? It seems to use the first two in order, regardless of which they are.

**Comment by abnerlee** [comment]
> 2\. Is it possible to specify which keys are used?

Ni, we do not want to support this. Proper description should be "guessed" from the document, we do not want to keep too much options.
