### ISSUE TITLE
[Feature Request]: Custom new file support

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2191]
I really enjoy using this, but something that would make it far more usable would be enhancing the support for creating new files. Not sure if you've used "Advanced File" extension on VSCode (https://marketplace.visualstudio.com/items?itemName=patbenatar.advanced-new-file) but it would be extremely useful for creating files in very nested directories without ever having to take hands off the keyboard and also saves time in creating files in nested directories (right now, you have to open up folders until you see the one you want).

Thanks for all your work.

**Comment by abnerlee** [comment]
Requires #1512 first.
