### ISSUE TITLE
Search score sort and improvements

### ISSUE THREAD

**Issue by tongphe** [typora/typora-issues#2192]
Hi,

Firstly, I want to say thanks for wonderful markdown application.

I used Zim wiki before and has been moving to Typora as my note taking, I have some suggestions for current search operations:

**Search score sorting**
Can you please add or have an option to sort the search results descending by score. For example: file has keyword in filename will score +5, N occurrences inside the file will be +N 

![image](https://user-images.githubusercontent.com/8666498/52930001-4a2c7e00-3379-11e9-805a-a521a951ae25.png)

**Quick open file in tab**
I know we have quick open file feature, but it should more convenient to open the first result with Enter key and inside the same window/tab

**History shortcut**
Can you implement a shortcut to move back/forward last opened files in the same window/tab, by using Option + left/right key (Macos for example). I search a lot and sometime just want to move around between the notes I have opened

Thanks,

**Comment by abnerlee** [comment]
We would consider sorting on search result as low priority since we currently did not find the case that one target search result is difficult to found from result list, but we will move path match in "topper" position. 

> Quick open file in tab
merge into #1000

> History shortcut
merge into #1154
