### ISSUE TITLE
BUG, when copy markdown text from typora to discord, spacing is not kept

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#2193]
when copy markdown text from typora

to discord 

spacing is not kept

what basically is going on here?

**Comment by abnerlee** [comment]
Some (most ) Markdown rendering engine will ignore continuous whitespaces, you could escape them by adding `\` before whitespace or use `&nbsp;`. 

see https://support.typora.io/Line-Break/

**Comment by SolveAllProblemsRightNow** [comment]
have found when transferring to 

* onenote
* google docs

all the line spacing is not kept also
and many other problems, lots of things not being copied right

im sure happens across all softwares

when other software transfers into typo
* pretty clean
* loses some number formmating, mostly ok

so it's not jsut 'some (most ) Markdown rendering engine'
im sure that's it's ALOT of softwares

doesnt seem worthwhile to make a markdown app unless all these kinds of probelms are fixed

i've lessen my usage of typo overall
am only just gonna keept a few things in there mainly for drafting 
long-term, unsure

**Comment by SolveAllProblemsRightNow** [comment]
is typo using some rare unknown markdown or soemthing?

how could even other markdown engines be copying it wrong???

**Comment by abnerlee** [comment]
> all the line spacing is not kept also

possible to provide any examples?
