### ISSUE TITLE
Bug: Delete or Undo image in the document doesn't deleting the image file.

### ISSUE THREAD

**Issue by magi44ken** [typora/typora-issues#2194]
If you delete the image from your document or paste an image and then undo it, it doesn't delete the image file from the drive. It only remove it from the document itself.

Reproduction Deleting an Image

1. Paste an image to the document.
2. Select the image from the document and delete it.

Reproduction Undo an image

1. Paste an image to the document
2. Undo it by CTRL+Z

**Comment by abnerlee** [comment]
merge into #2198

**Comment by jiacheng-0** [comment]
Is this fixed in Typora 0.11 beta? Thank you!
