### ISSUE TITLE
Inline math shortcut (Ctrl+M) focusing outside delimiters

### ISSUE THREAD

**Issue by Wunderdog** [typora/typora-issues#2195]
Please refer to the linked video clip:

https://media.giphy.com/media/2sXFz8j5KBf6J7EVSQ/giphy.gif

![img](https://media.giphy.com/media/2sXFz8j5KBf6J7EVSQ/giphy.gif)

When I use the Ctrl + M shortcut for inline Latex the cursor moves outside of the dollar delimiters.
I tried restarting and refreshing the latex, but the issue persists.
This is new in the recent update.

Typora **Version 0.9.9.22** on **OSX**

**Comment by abnerlee** [comment]
fixed in new release
