### ISSUE TITLE
Outline jumps to top when I click on a sub-item below the screen

### ISSUE THREAD

**Issue by zendai** [typora/typora-issues#2197]
Version: 0.9.65 (beta)
OS: Windows 10

This is specific to this version of Typora, since I've never experienced this before, only since I upgraded this morning to version 0.9.65 (beta).

Description:
I have a fairly long document, and I use the H tags very often to describe sections also I enjoy the Outline on the left sidebar. I use that to navigate in my document, I just click on one of the items there, and the document scrolls to that section immediately.

Since my document is long, the Outline window is also longer than a screen so I have to scroll it. When I click on an item in the Outline which is below the initial screen (in other words, I had to scroll up the Outline to find the section I was looking for), even though the document scrolls there, but the Outline window jumps up to the top. This is a bug I assume, as the Outline window should stay there, as most likely I'll edit that area. As it jumps top now, I have to scroll down again in the Outline window, which is annoying.

Update:

I tried to reproduce the bug and I realized that this is most likely a feature. The reason why the Outline jumps to the top since when I select a sub-item, both the sub-item and the topmost (H1) elements are highlighted, and the Outline jumps to the topmost element. In my case, that's the top of the Outline.

I believe this is not a bug but a feature. Still, for longer documents, where the sub-item is far from the topmost item is very annoying, as my Outline window, which I use for navigation will scroll away from the sub-item area that I'm writing.

Can we make this feature optional? Once I click on an element in the Outline window, I would prefer to have that element positioned in the middle, rather than the topmost element positioned to the top.

Reproduce the bug/feature:
- Download 1.txt
- rename it to 1.md (GitHub doesn't allow me to attach .md)
- open the doc in Typora
- open the Outline sidebar
- search for CLICK THIS
- click there
- see as the Outline sidebar scrolls to the topmost item (H1) and you won't see CLICK THIS anymore in the Outline

[1.txt](https://github.com/typora/typora-issues/files/2878903/1.txt)

Thank you,
sendai

**Comment by zendai** [comment]
Also, just found out that the same happens when I just scroll down in my document, the Outline will jump to the topmost H1. This makes Outline useless for larger documents where the outline is longer than a screen. I believe the Outline should move the current sub-item to the middle, or at least the current sub-item should be visible on the Outline.

Is there a way I can downgrade my Typora to the previous version?

**Comment by zendai** [comment]
So, it's fine to highlight both the current H and the topmost H, but the positioning should be focusing on the current H, not the topmost H.

**Comment by abnerlee** [comment]
It's a bug only happens to document that contains duplicate Headers. I think it also exists on older version of Typora.

History build: https://typora.io/windows/dev_release.html

**Comment by zendai** [comment]
Thank you!

**Comment by abnerlee** [comment]
fixed in new release
