### ISSUE TITLE
The end of an indended fenced code block in an numbered list is ignored in Code Mode

### ISSUE THREAD

**Issue by daenenk** [typora/typora-issues#2199]
Let's take the example of https://gist.github.com/clintel/1155906

Makdown syntax

`````
1. This is a numbered list.
2. I'm going to include a fenced code block as part of this bullet:

    ```
    Code
    More Code
    ```

3. We can put fenced code blocks inside nested bullets, too.
`````

Rendered

---
1. This is a numbered list.
2. I'm going to include a fenced code block as part of this bullet:

    ```
    Code
    More Code
    ```

3. We can put fenced code blocks inside nested bullets, too.
---

The rendering by Typora (Version 0.9.9.21.1 (1913) on macOS 10.14.3 (18D109)) is correct, but the style applied in the **Code Source Mode**, seems to follow other logic. In the latter, the code clock does not end at the second line with three back-ticks; the code clock style is further applied up to the end of the document.

**Comment by daenenk** [comment]
I tried all 6 default themes; same behavior related to the described issue.

**Comment by daenenk** [comment]
Same behavior on Typora Version 0.9.9.22 (1979)

**Comment by abnerlee** [comment]
merge into #1638
