### ISSUE TITLE
Link with # sign

### ISSUE THREAD

**Issue by aoozdemir** [typora/typora-issues#220]
When cross-referencing (#219) or adding link to something with an **id** tag, inserting a `#` sign, turn the line automatically to a header.

**Comment by abnerlee** [comment]
How do you use the "#" sign? # at the beginning of a line is the syntax for heading

**Comment by aoozdemir** [comment]
I know :smile: I thought I was clear, sorry. It doesn't have to be a link though. When you want to type intentionally `#3`, it turns the line to a header. 

![zb2btknfo9](https://cloud.githubusercontent.com/assets/6544741/16773294/1a8167bc-4860-11e6-937b-efb9c2ffe7c2.gif)

**Comment by abnerlee** [comment]
Hi, what kind of keyboard or IME did you use.

ctrl+3 will make a `<h3>`, I guess you pressed that shortcut key when inputing the mark "#"

**Comment by aoozdemir** [comment]
Yup :+1: That's what is happening here. Tried with an UK keyboard, it works. Is there any way we can override the keybindings? A keymap file like Atom's.
