### ISSUE TITLE
[Feature Request] ASCII Art Support such as Ascidia

### ISSUE THREAD

**Issue by TonyBarganski** [typora/typora-issues#2201]
Since moving to markdown as my primary workflow, I find myself drawing a lot of ascii-art network/application diagrams. I prefer them to the boring, boated and expensive Visio stencils.

Ascidia turns them into  prettier raster and vector graphic formats. 

```text
               O     
              -|-  -.
              / \   | 
              User  | Request
                    V
 Foobar         +--------+       .------.
  Layer         |  Acme  |       '------'
- - - - - - +   | Widget |<----->|      |
   .----.   ;   +--------+       |      |
  | do-  |  ;       |            '------'
  |  dad |--^--<|---+            Database
   '----'   ;
            ;
```
Into:-

![](https://camo.githubusercontent.com/959d5e7fbdd2a57f3908985fe008f8376fc1c410/68747470733a2f2f7261772e6769746875622e636f6d2f4672696d6b726f6e2f417363696469612f6d61737465722f726d2d696d616765732f6578616d706c652e706e67)

**Comment by abnerlee** [comment]
merge into #1138
