### ISSUE TITLE
Second header followed by a code block corrupts format and brings in redundant blank characters

### ISSUE THREAD

**Issue by ActiveVolcano** [typora/typora-issues#2205]
1. Enter markdown text in source code mode:
![origin](https://user-images.githubusercontent.com/9970779/53061454-abc72680-34f8-11e9-8707-1f08ecfda42e.png)

2. Exit source code mode and then format is corrupted:
![corrupts_format](https://user-images.githubusercontent.com/9970779/53061455-abc72680-34f8-11e9-856a-ce8761ed65b5.png)

3. Enter source code mode again and find that redundant blank characters are brought in automaticly:
![brings_in_redundant_blank_characters](https://user-images.githubusercontent.com/9970779/53061458-ac5fbd00-34f8-11e9-9814-5eb40aeaf6ef.png)

4. Tested with Typora version 0.9.65 (beta) + Windows 10 x64 version 10.0.17134.590. Markdown text lists below:

v1
==
```bash
whoami
````

v2
==
```bash
id
````

**Comment by abnerlee** [comment]
fixed in new release
