### ISSUE TITLE
Bug report: Look Up doesn't work on macOS

### ISSUE THREAD

**Issue by sayomelu** [typora/typora-issues#2206]
The macOS Look Up doesn’t work on any text format.
(macOS: 10.14.3  Typora:  0.9.9.22)
![screen shot 2019-02-19 at 12 30 52](https://user-images.githubusercontent.com/16492117/53065567-25fea780-3507-11e9-9ffd-696601b7873c.png)
![screen shot 2019-02-19 at 12 30 57](https://user-images.githubusercontent.com/16492117/53065574-2e56e280-3507-11e9-9f1f-f5c8dcb2a738.png)

**Comment by abnerlee** [comment]
Cannot reproduce this one, could you try restart Typora or macOS?

**Comment by sayomelu** [comment]
Restarted both, still cannot work

**Comment by AlexPasternak** [comment]
FWIW, works fine for me in same Typora version on macOS 10.13.6

<img width="395" alt="image" src="https://user-images.githubusercontent.com/1819485/53419480-f852ac00-39a7-11e9-9a95-68152852d4bf.png">
