### ISSUE TITLE
Bug report: Scroll bar on Night Theme

### ISSUE THREAD

**Issue by sayo-melu** [typora/typora-issues#2207]
The white scroll bar on the Night Theme looks annoying at night.
<img width="243" alt="screen shot 2019-02-03 at 17 55 13" src="https://user-images.githubusercontent.com/16492117/53065827-47ac5e80-3508-11e9-8806-e4c060b47511.png">
I think it should be display in dark like the other dark mode app. (macOS Mail) 
<img width="240" alt="screen shot 2019-02-03 at 17 56 16" src="https://user-images.githubusercontent.com/16492117/53065838-4da23f80-3508-11e9-9403-118082ae57f1.png">

**Comment by abnerlee** [comment]
A hot fix is to select "Show scrollbar only when scroll" in System Preferences -> General. This would take us some time to solve this

**Comment by sayomelu** [comment]
It may shows in black occasionally, but the scrollbar should be in white.
<img width="608" alt="screen shot 2019-02-20 at 17 16 48" src="https://user-images.githubusercontent.com/16492117/53080300-50665a00-3533-11e9-9d14-df0458df5684.png">

**Comment by zhanggang807** [comment]
pay attention

**Comment by Newt0n** [comment]
> A hot fix is to select "Show scrollbar only when scroll" in System Preferences -> General. This would take us some time to solve this

Any fix plan on this issue? Still presents in **0.9.9.23.4**

**Comment by abnerlee** [comment]
fixed
