### ISSUE TITLE
feature request: more clear tree view and outline by indention line

### ISSUE THREAD

**Issue by BrambleXu** [typora/typora-issues#2208]
It would be great to add indention line in both **tree view** and **outline view**, which more clear to see. 

![30715549-160c7ad2-9f17-11e7-9de7-ee380076e6dd](https://user-images.githubusercontent.com/10768193/53093236-3e4be200-355a-11e9-8c8b-fdb962b5d00d.png)

https://github.com/Microsoft/vscode/issues/17777#issuecomment-331261278

**Comment by abnerlee** [comment]
We will consider this as low priority.
