### ISSUE TITLE
Small problem with azerty keyboard shortcuts

### ISSUE THREAD

**Issue by TheAthenA714** [typora/typora-issues#221]
Hi everyone !

Just discovered typora, loving it so far, but there's a little annoyance when you use an [azerty keyboard](http://static.commentcamarche.net/ccm.net/faq/images/0-Vuskup12-azerty-s-.png). If you want to type an open bracket ([)  you have to press the AltGr key along with the number 5 key (at least on windows). The problem is Typora interprets this as the shortcut for heading 5 and doesn't type the bracket. I have to press AltGr+5 again to actually get the bracket.

Which means every time I want to include a link in my text, typora changes the paragraph to heading 5 and I have to manually revert that change. Nothing major, but still something that could be changed, maybe by letting the user use a different key for shortcuts (I could live with ctrl+1-5 for headings), or even better yet : fully rebindable shortcuts.

**Comment by dbalbright** [comment]
I'd have to agree on rebindable shortcuts. Even with a standard US keyboard layout, the CTRL-Shift-` (backtick) to markdown in-line code is like performing in the finger Olympics. I know that the backtick is the markdown character and it's intuitive but it isn't ergonomically friendly. I say this as someone making a lot of technical notes and documentation where I have to contort my hand more often than a Russian gymnast.

**Comment by abnerlee** [comment]
see http://support.typora.io/Custom-Key-Binding/
