### ISSUE TITLE
⌘+A doesn't select all text

### ISSUE THREAD

**Issue by sicilian-lizard** [typora/typora-issues#2210]
At a certain point, ⌘+A doesn't select all text, but only a paragraph, there is nothing but pure text.

When I try to save, the "save" button is grayed out.

macOS Majove, Typora Version 0.9.9.22 (1979).

**Comment by abnerlee** [comment]
Could you provide more details or steps for us to reproduce it?

**Comment by sicilian-lizard** [comment]
I can't reproduce it, yet. It's new to me in Version 0.9.9.22 (1979), after the IME problem was fixed.

I'll get back to this once I can reproduce it.

Yes, "save" button in the File menu.

**Comment by sicilian-lizard** [comment]
I guess it has something to do with the "Select Styled Scope" menu command, but I can't reproduce the problem.

Sometimes when I have two paragraphs, with the caret in the second, ⌘+A selects the first paragraph, not the whole text, not the second paragraph.

**Comment by sicilian-lizard** [comment]
By the way, this is new to Version 0.9.9.22 (1979), when the IME issue I reported was fixed.

**Comment by abnerlee** [comment]
Closing this since this may not be reproduced

**Comment by sicilian-lizard** [comment]
Can't be reproduced reliably but I am seeing this many times a day.

⌘+A selects only the first paragraph when there are more than one, 'delete' also delete the selected paragraph.

**Comment by sicilian-lizard** [comment]
I suggest you reopen this issue, as it happens very often when I have multiple paragraphs.

**Comment by seamusdemora** [comment]
FWIW, I have never seen this. I have written *many* multi-paragraph documents, often having several of them open in tabs in the same window. I use ⌘+A frequently in these documents, and it's always worked as expected. Not disputing anything - just sayin'.
