### ISSUE TITLE
Multi-Displayers encounter a problem

### ISSUE THREAD

**Issue by sixtar** [typora/typora-issues#2215]
英文有限,直接中文说啦~~
系统版本: win10 x64
程序版本: 0.9.64
多个显示器情况下,比如我把Typora拖到显示器2(扩展),此时如果取消显示器2的扩展,程序的窗口不会回到显示器1(主显示器),而是不知道跑哪去了...只有手动杀掉程序后再打开才会恢复.

**Comment by abnerlee** [comment]
Cannot reproduce this one
