### ISSUE TITLE
【建议】Windows版自动对本地连接进行处理

### ISSUE THREAD

**Issue by cooper1x** [typora/typora-issues#2216]
比方说`E:\`这个，希望可以自动转成`E:\\`或者`E:/`。

原因是js会对反斜杠进行转义，这样导致nodejs程序获取内容的时候会问题，拿不到完整的字符串。

使用场景是通过工具实现对本地图片进行图床上传，并且替换为线上地址。

解决的是无网络情况下本地写作插入图片后，有网络环境图片链接转线上地址的问题。

希望可以考虑一下。

**Comment by abnerlee** [comment]
merge into #1520
