### ISSUE TITLE
Rename image file by right-clicking on it

### ISSUE THREAD

**Issue by pidgeon777** [typora/typora-issues#2218]
Let's suppose an image defined as follows in Typora:

`![img_name](assets/img_name.jpg)`

Behaviour like the following would be really appreciated: right click on the image preview, choose "Rename" option, then a prompt appears asking for the new filename. Let's suppose it gets set to `new_name`, thus all references in Typora documents would also be updated as follows:

`![new_name](assets/new_name.jpg)`

with a rename also occurring to the originally linked image file.

**Comment by abnerlee** [comment]
merge into #2242

**Comment by pidgeon777** [comment]
Any news? This is an almost essential feature to have, in my opinion.

**Comment by donRumata03** [comment]
Totally agree with @pidgeon777: it takes to much time to rename inserted images and references to them by hands because it's disgusting.
