### ISSUE TITLE
[bug] sometimes replacing text will be failed 

### ISSUE THREAD

**Issue by thinkycx** [typora/typora-issues#2219]
steps:
1. open a md file and CTRL+SHIFT+F 
2. input and replace `![Alt text](./` to `![Alt text](/absolute/` : success
3. choose another md file in the same folder and enter CTRL+SHIFT+F 
4. click replace and it doesn't work
![image](https://user-images.githubusercontent.com/13138128/53283057-741be100-377b-11e9-8785-bf76daf54d1a.png)

**Comment by abnerlee** [comment]
fixed in new release
