### ISSUE TITLE
Indenting bullet should not indent subbullets as well

### ISSUE THREAD

**Issue by snungd** [typora/typora-issues#222]
Reproduction steps:

1. create markdown file:
```markdown
* one
* <cursor_here>two
    * three
    * four
* five
```
2. place cursor in position pointed out above and press Tab
3. bullet will be indented but subbullets will be indented as well resulting in markdown

```markdown
* one
    * two
          * three
          * four
* five
```

instead expected

```markdown
* one
    * two
    * three
    * four
* five
```

Note that the same behavior is observed for dedenting bullets with Shift-Tab.

This behavior is different than most of the text editors, where Tab indents only bullet under cursor. This is confusing at least, in many cases inconvenient, forcing to dedent manually subbullets.

One of the options would be to keep current behavior with eg. `Ctrl-Tab` since it might be useful in some cases.

**Comment by AlexPasternak** [comment]
FWIW, confirmed that Word functions as described in Expected behavior.

**Comment by vassudanagunta** [comment]
Agreed that expected behavior should be consistent with other popular tools when it comes to generic functionality such as this. 

Most popular editors support both behaviors. To Indent multiple lines while also retaining the hierarchy, one usually selects multiple lines and presses `tab`.

**Comment by abnerlee** [comment]
Fixed in new verion

**Comment by vassudanagunta** [comment]
Works great! Indenting/outdenting multiple lines works as expected even when the first or last bullet is only partially selected. Great work!
