### ISSUE TITLE
[need] Could I see pictures with left and right keyboard?

### ISSUE THREAD

**Issue by thinkycx** [typora/typora-issues#2220]
Nice work.

When insert some pictures in typora, could I see image by double click on it and see it largely.
And then can see the next image with right keyboard?

For example: https://www.anquanke.com/post/id/171488
![image](https://user-images.githubusercontent.com/13138128/53283573-83069180-3783-11e9-8bd0-4654417275fe.png)

I think it will be more usable to people.

**Comment by abnerlee** [comment]
merge into #2242
