### ISSUE TITLE
[Bug] \label{} and \ref{} doesn't work

### ISSUE THREAD

**Issue by Raverstern** [typora/typora-issues#2221]
The cross reference of math blocks doesn't work, even for the example provided on the [support page](https://support.typora.io/Math/#cross-reference).

**Source code:** (just copy-paste the example)
![screenshot from 2019-02-23 12-23-07](https://user-images.githubusercontent.com/8509855/53285830-e1247c00-3765-11e9-9553-6978712ebfb1.png)

**After rendering:**
![screenshot from 2019-02-23 12-20-43](https://user-images.githubusercontent.com/8509855/53285834-f0a3c500-3765-11e9-95ea-703096371e91.png)

**OS version:** Ubuntu 16.04
**Typora version:** 0.9.65(beta)

---

**Update**: I got the cross reference after turning on the "Auto Numbering Math Equations". Is that the prerequisite of referring the equations? However on the support page "Cross Reference" appears prior to "Auto Numbering"...

**Comment by abnerlee** [comment]
You could either use a `\tag` to specify a number/tag or enable auto-numbering, then `\ref` will know which text to show
