### ISSUE TITLE
Night theme problem with numbers in headings

### ISSUE THREAD

**Issue by bchmura** [typora/typora-issues#2223]
When using numbers in a heading in the Night theme, things do not appear correctly.  This applies to at least heading 1-4

- 1,2,0 are the same height as lowercase letters,  
- 3,4,5,7,9 are probably the right height but descend below the line.
- 6,8 do appear correctly.

![typora_night_theme_number_problem](https://user-images.githubusercontent.com/12405750/53304687-494a8f00-3846-11e9-984f-2ed9b62fa919.png)

This has been in the past several releases for me on Windows, last verified as a problem on 0.9.65.  I am running in US-EN (if that matters).

I don't believe I have messed with them at all.  I don't know CSS enough to really try to solve it.

EDIT: Also seen on multiple computers.  Windows 10

**Comment by abnerlee** [comment]
You could add custom CSS:
```css
h1, h2, h3, h4, h5 {
font-variant-numeric: tabular-nums;
}
```

following https://support.typora.io/Add-Custom-CSS/

**Comment by bchmura** [comment]
Thanks!
