### ISSUE TITLE
Preserve UNIX hard linked file

### ISSUE THREAD

**Issue by mutecamel** [typora/typora-issues#2224]
I some times create hard links in my project directory to allow multiple files pointing to a same file inode, so that any change of any one file will be reflected simultaneously to all hard linked files. For example,
```
$ cat subject1/file.md
hello

$ ln subject1/file.md subject2/file.md

$ cat subject2/file.md
hello

$ echo "hello again" >> subject2/file.md

$ cat subject2/file.md
hello
hello again

$ cat subject1/file.md
hello
hello again
```

But if I edit `subject2/file.md` with typora, the hard link breaks, `subject1/file.md` won't change with `subject2/file.md`. They become two independent file inodes. It seems typora **deletes** the `subject2/file.md` (the hard linked one) first, and then **creates** a new `subject2/file.md` (not hard linked) instead, rather than **open** `subject2/file.md` first and then **flush/write** the modified content/buffer.

I like typora as a markdown editor very much and hope to integrate it into my workflow. Will you lovely guys address this issue and fix it? Thanks a lot!

**Comment by mutecamel** [comment]
OS version: OS X 10.14.3
Typora version: 0.9.9.22 (1979)

**Comment by abnerlee** [comment]
Typora does not interpret the "save" logic, it is handled by the OS, so features like "save in place", "version control" will be enabled. 

TextEdit.app also has the same behavior.

**Comment by aidan-gibson** [comment]
bobby is correct, this should be reopened and resolved when possible. Typora breaking hard links is extremely unfortunate and seems like a trivial fix.
