### ISSUE TITLE
Window position with multiple monitors

### ISSUE THREAD

**Issue by PsCustomObject** [typora/typora-issues#2225]
Hello, 

using Typora version 0.9.65 for Windows with a multi monitor setup, apparently when closing and re-opening the application monitor position is not remembered and it opens up on a random monitor (of the three I have) sometimes with application being off screen

This is similar to what was described and fixed in #938 but for me issue is happening when computer is connected to docking station.

**Comment by vassudanagunta** [comment]
@abnerlee does fixing this and #1804 together make sense?

**Comment by abnerlee** [comment]
still happens in newer versions?

**Comment by PsCustomObject** [comment]
Well since reporting the issue I have changed working setup but have to admit I did not notice the issue when working with an external monitor with any of the recent builds.

**Comment by VictorS8** [comment]
I don't know, if it helps, but on my pc which I work with 2 monitors, the app always show where I last closed it and with the lenght and width as same as before!

I'm using lastest version of Typora

**Comment by abnerlee** [comment]
should be fixed in 1.8.6
