### ISSUE TITLE
Exporting to .docx

### ISSUE THREAD

**Issue by Fastidious** [typora/typora-issues#2228]
Using `Version 0.9.9.22 (1979)`. While using a simple markdown file (a few headers, bulleted lists, and pre-formatted text) and trying to export it to Word, it will crash the application. Running Typora under Mojave `10.14.2 (18C54)`.

**Comment by abnerlee** [comment]
Possible to provide or send us (<hi@typora.io>) a sample *md file?

**Comment by Fastidious** [comment]
@abnerlee email sent.
