### ISSUE TITLE
Mac gantt overlapping

### ISSUE THREAD

**Issue by fangyuan-liao** [typora/typora-issues#2229]
Hello,
    I met this problem that Gantt section name was overlapped with timeline on Mac OS 10.14.
<img width="1204" alt="screen shot 2019-02-27 at 21 24 14" src="https://user-images.githubusercontent.com/41479301/53490075-1fa79700-3ad6-11e9-8d14-bc1ff90779e5.png">
<img width="817" alt="screen shot 2019-02-27 at 21 24 25" src="https://user-images.githubusercontent.com/41479301/53490079-2209f100-3ad6-11e9-851e-d4a1ec08c629.png">
    May I know how to solve this problem?
    Thank you!

**Comment by jlnbdt** [comment]
Hi,

Same problem here on Windows 10.
(already mentioned [here](https://github.com/typora/typora-issues/issues/2142))

**Comment by abnerlee** [comment]
#2142
