### ISSUE TITLE
How to do internal links on MacOS?

### ISSUE THREAD

**Issue by fangyuan-liao** [typora/typora-issues#2230]
Hello, 
   I met the same problem as #191 on MacOS.
   Is this a bug for the Mac version?

``` markdown
[Database](#the-database)
## The database
```

This is the correct way, if not working, then it is a bug

_Originally posted by @abnerlee in https://github.com/typora/typora-issues/issues/191#issuecomment-226143906_

**Comment by abnerlee** [comment]
What's your Typora version?

**Comment by fangyuan-liao** [comment]
> What's your Typora version?
Hello, sorry for the late reply.
Version 0.9.9.22 (1979)

**Comment by abnerlee** [comment]
I cannot reproduce this, could you provide demo files or screencast?

**Comment by fangyuan-liao** [comment]
> I cannot reproduce this, could you provide demo files or screencast is possible?

Here is my markdown demo
```
[create an anchor](#anchors-in-markdown) 
.......
<span id="anchors-in-markdown"> jump to here</span>
```

Before I click this internal link, it looks like this.
<img width="176" alt="screen shot 2019-03-08 at 21 57 17" src="https://user-images.githubusercontent.com/41479301/54029856-3d1ee400-41ed-11e9-86a7-8a57e93e1bb1.png">
After I clicked this internal link, it looks like this without jumping.
<img width="365" alt="screen shot 2019-03-08 at 21 57 24" src="https://user-images.githubusercontent.com/41479301/54029868-4314c500-41ed-11e9-85b8-a4e55752e1cc.png">

Sorry for my bad explanation.

**Comment by SallyWY** [comment]
I have met the same problem as you.

**Comment by adlwawh** [comment]
Me too, guys

**Comment by abnerlee** [comment]
please check http://support.typora.io/Links/#internal-links
