### ISSUE TITLE
File duplicated in file browser after case-change rename

### ISSUE THREAD

**Issue by geetduggal** [typora/typora-issues#2231]
If I have a file name called, for example 'Slip Box.md' and I right click on it, and rename it to "Slip box.md', both files appear in the browser until a new browser is opened.

Thanks for all your great work on this tool!

**Comment by belonHan** [comment]
I renamed a directory , and then  the directory disappeared with the inner files, and I can't find it anywhere.
> version 0.9.65 (beta)

**Comment by tylerlmz1** [comment]
I sometimes encounter this problem too, pressing 
More>Refresh Folder 
will also do the same job

**Comment by abnerlee** [comment]
fixed in new release
