### ISSUE TITLE
Bug in Type Writer Mode and Export to PDF

### ISSUE THREAD

**Issue by aldoKelvianto** [typora/typora-issues#2233]
I lost my entire work after doing the following:

1. Use Type Writer mode
2. Typing until around > 800 characters / multiple pages
3. Save
4. Export to PDF
5. Realize the only part that get exported is the first pages character (around 150-200 chars) 
6. I disable Type Writer mode (Maybe its because Type Writer Mode) 
7. Export to PDF
8. Still not exporting the whole content
9. The document is only shown the first 150-200 characters, all other text is gone.
10. I tried to undo, reopen, anything. The text is gone.

Its really frustrating because I can't find the text I type before, not even a cache. So I have to retype the whole thing again..
Please help to fix the issue. 
Thanks.

**Comment by abnerlee** [comment]
Typora version?
