### ISSUE TITLE
How to show the title below the image?

### ISSUE THREAD

**Issue by SallyWY** [typora/typora-issues#2238]
I would like to add a title below the image I've added in the markdown file
When I type like this, it doesn't show anything below the image as a title. The only thing shows up is the image.

Thanks for your support.

![Data Science](http://sudeep.co/images/post_images/2018-02-09-Understanding-the-Data-Science-Lifecycle/chart.png)

**Comment by abnerlee** [comment]
Use `<figure>`:
```html
<figure>
  <img src="pic_trulli.jpg" alt="Trulli" style="width:100%">
  <figcaption>Fig.1 - Trulli, Puglia, Italy.</figcaption>
</figure>
```

or wait for #249

**Comment by zdaiot** [comment]
@abnerlee 
When converting picture syntax, you can add an option to convert it to `< figure> and <caption>` form.
