### ISSUE TITLE
Github -> GitHub

### ISSUE THREAD

**Issue by fulldecent** [typora/typora-issues#2239]
The word "Github" is styled wrong. The preferred version is "GitHub".

**Comment by AlexPasternak** [comment]
Where specifically are you talking about? Just the theme name or elsewhere also? I feel like this is a dupe with another issue, but can't find it just now, as it's a very hard to search for term here :-)

**Comment by fulldecent** [comment]
Just the theme name

**Comment by abnerlee** [comment]
The theme name is "Github", not using the word "GtiHub".
