### ISSUE TITLE
[Feature request] Add support for MDX format

### ISSUE THREAD

**Issue by MaluNoPeleke** [typora/typora-issues#2241]
Please add support for MDX format and syntax: https://mdxjs.com/

**Comment by abnerlee** [comment]
#2448

**Comment by kud** [comment]
Yes please!

**Comment by slavakurilyak** [comment]
Any updates on this?

**Comment by cukabeka** [comment]
Wouldn't this already be achieved by just parsing MDX the same way as MD files? At least it would help very much if there was an option to render other extensions the same like MD. To me, that's a different functionality than #2448

**Comment by jalu14** [comment]
Any update? Already able to open .mdx and they render well but there is a lack of detection on the folder tree

**Comment by jovezhong** [comment]
Many of of us are using docuasaurus for documentations and in the new v3 version, mdx extension is recommended, but Typora won't show them in the folder view

https://docusaurus.io/docs/migration/v3#using-the-mdx-extension

Please re-open this

**Comment by flashtheman** [comment]
How is it still not possible to open .mdx files? I mean, it doesn't need jsx features. It just needs to open them as markdown.

**Comment by ml4** [comment]
Hi I'd like to chime in here as well - Typora would sell more licences if mdx support was added.

**Comment by jake-rigby** [comment]
Yep, WTF Typora?

**Comment by bostrowski** [comment]
+1

**Comment by jovezhong** [comment]
A side note, I no longer use Typora for markdown editing. As a co-founder in a startup company, I use code editors, such as https://zed.dev or VS Code with AI, which can generate quite nice markdown documentation after I type a few key words, they also do auto-format on save.
