### ISSUE TITLE
Change width of source code area

### ISSUE THREAD

**Issue by schultzter** [typora/typora-issues#2243]
I found the instructions on changes the width of the _writing_ area, https://support.typora.io/Width-of-Writing-Area/

But how do I change the width of the source code area?

I want to maximize them both so I can use all the screen real estate I have.

Thanks,

**Comment by xp44mm** [comment]
i have same wants!

**Comment by abnerlee** [comment]
updated the doc https://support.typora.io/Width-of-Writing-Area/
