### ISSUE TITLE
Footnote indentation format

### ISSUE THREAD

**Issue by liuzhenqi77** [typora/typora-issues#2244]
I noticed that the indentation for footnotes was changed, and I was wondering what is the reason/issue related to the change. 

Originally, there is no indentation for footnote texts and it was already clear from the font type and boldness differences. Currently, the indentation added to the texts make it look chaotic when the footnote labels have different lengths.

**Current**

![image](https://user-images.githubusercontent.com/7530936/54054602-a9332500-41b8-11e9-8d4f-80f7f0d4838a.png)

**Original & Desired**

Without the text block indentation.

_working with 0.9.65(beta) on Ubuntu_

**Comment by abnerlee** [comment]
fixed in new release
