### ISSUE TITLE
Auto pair on MacOS does not operate

### ISSUE THREAD

**Issue by seamusdemora** [typora/typora-issues#2245]
I've not used Typora in a few weeks, but recently began a flurry of new activity. Auto pair seems to have quit working! I've reviewed the setting, and I think they're correct, yet auto pair doesn't work for brackets, for quotes or for common markdown syntax. 

My mac is on "Mojave", 10.14.3, and Typora is current AFAIK, ver 0.9.9.22.

**Comment by abnerlee** [comment]
#2214

**Comment by seamusdemora** [comment]
Oops! sorry :)
