### ISSUE TITLE
log

### ISSUE THREAD

**Issue by hitanvil** [typora/typora-issues#2246]

**Comment by hitanvil** [comment]
I need input an equation for log with base 2. The input is $log_2N$. Its preview is correct as below:
![image](https://user-images.githubusercontent.com/18505154/54081514-bd5f4b00-42ba-11e9-8269-70d5454de185.png)
But its inline display is totally wrong:
![image](https://user-images.githubusercontent.com/18505154/54081528-d2d47500-42ba-11e9-8990-52dc0101f9e3.png)

Thanks.

**Comment by abnerlee** [comment]
version?

**Comment by hitanvil** [comment]
0.9.65(beta). Thanks.
