### ISSUE TITLE
Unable to type anything or view a file in Typora after updating to 0.9.9.22

### ISSUE THREAD

**Issue by IdlePhysicist** [typora/typora-issues#2249]
As the title states, I updated to 0.9.9.22 today and now I am unable to use Typora. I am running on OSX 10.10.5. 

Please see screenshot below. I am unable to provide steps to reproduce, since all I did was update and open the app.

![Screen Shot 2019-03-10 at 19 56 38](https://user-images.githubusercontent.com/20644761/54095798-aed26b80-436e-11e9-90ea-f4b0cab0d17f.png)

Many Thanks

**Comment by abnerlee** [comment]
Can reinstall Typora solve this? If not:

1. Follow https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac
2. Click `Develop` -> `[your mac name]` -> `Typora-app -- index.html` from menubar, and see what error message there is?

**Comment by IdlePhysicist** [comment]
I have tried reinstalling Typora several times, both from Homebrew and the .dmg from the website, to no avail.

```
<html>
    <head></head>
    <body></body>
</html>
```
Is the all that is seen in the elements tab. ` Typora-app -- index.html` is not an option...

![Screen Shot 2019-03-13 at 14 11 29](https://user-images.githubusercontent.com/20644761/54312000-706dc400-459b-11e9-9214-8838d01e8996.png)

![Screen Shot 2019-03-13 at 14 18 24](https://user-images.githubusercontent.com/20644761/54312014-75327800-459b-11e9-80d4-41c69f8a0b07.png)

**Comment by abnerlee** [comment]
Try with the newer version?

And do you have firewall or proxy app that may block Typora's request to load its HTML ?

**Comment by IdlePhysicist** [comment]
I have tried again with v0.9.9.23.2 and there is no change. Typora worked before I updated to v0.9.9.22 a week ago, from v0.9.9.21.1 (if I recall correctly). I do not use a proxy app, and my firewall is not blocking Typora.

**Comment by IdlePhysicist** [comment]
**Update:** I have updated to v0.9.9.23.4 and Typora is still non-functional. I use it at work on a newer machine and I have no complaints but at home it is a different story.

**Comment by abnerlee** [comment]
> my firewall is not blocking Typora

**Comment by abnerlee** [comment]
Close this since we are no longer support 10.10.
