### ISSUE TITLE
Links to local files don't convert to PDF

### ISSUE THREAD

**Issue by jlc-christie** [typora/typora-issues#2250]
Hi, 

When referencing a local file (see example), the link works in Typora, but when exporting to PDF the link points to `http://typora-app/some.log` and thus opens your default web browser and attempts to navigate there and obviously fails. 

```markdown
# Example
Click [here](some.log) to see a log file that was created. 
```

Maybe a simple regex could be used to determine if the link starts with `http://`, if it is, proceed as normal, if not, use `file://` instead? I noticed that it handles in-document links fine, so maybe there is already a similar mechanism implemented? 

Also, issue #1054 relates to links incorrectly outputting to HTML/PDF, so maybe that could be done in the same fix. 

Thanks,
James

--EDIT--
Forgot to mention, unlike #1054, this **does** work as expected when exporting to HTML.

**Comment by Hologos** [comment]
+1

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
