### ISSUE TITLE
Different image naming rules in MacOS and Win?

### ISSUE THREAD

**Issue by qianyeLC** [typora/typora-issues#2251]
I am using Typora both in MacOS and Windows, and when pasting a image from clipboard, image will be auto named copied to a path such as  "./assets/12345.jpg" in Windows. 

While in MacOS this path is different like "./assets/image-12345.jpg". 

Is this a by design or just some kind of difference.

**Comment by abnerlee** [comment]
They are auto generated image names, it didn't mean anything. 

Does it cause any issue?

**Comment by qianyeLC** [comment]
When editting a .md file alternately in Win and MacOS，it leaves 2 kinds of image names in ./assets. 

Just a minor confusion for me but I think naming in a uniform rule may be better.

**Comment by abnerlee** [comment]
This is already unified in newer version
