### ISSUE TITLE
Folder renaming causes folder to disappear

### ISSUE THREAD

**Issue by tylerlmz1** [typora/typora-issues#2252]
in Typora, renaming a folder to have a different letter case (upper case/lower case), will cause the whole folder to disappear, both from typora and file explorer

for example,
renaming a folder called "Typora"  to  "typora", will cause the folder to disappear

the folder did not go into recycle bin, it just vanishes

**Comment by tylerlmz1** [comment]
Some additional info:
- Newest typora version
- Windows 10

**Comment by tylerlmz1** [comment]
<img width="958" alt="typora file rename bug prompt" src="https://user-images.githubusercontent.com/18716055/54124551-b14fc680-443d-11e9-9f2d-e7d6dcf7b4dc.png">

doing the same kind of rename to **files** instead, will show up this prompt, not able to rename the file

**Comment by abnerlee** [comment]
fixed in new release
