### ISSUE TITLE
Ctrl+N (macOS Cmd+N) creates a new window instead of new file

### ISSUE THREAD

**Issue by nanoant** [typora/typora-issues#2253]
I am using Typora now as multi-platform note-taking app with notes kept in dedicated folder. The problem is that <kbd>Ctrl</kbd>+<kbd>N</kbd> (macOS <kbd>Cmd</kbd>+<kbd>N</kbd>) is doing exactly the same for me as New Window <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>. The desired behavior is to what bottom left `+` on file list does, but this is not the case.
Looks like a bug to me - tested both on Windows and Mac.

Moreover additional annoyance on macOS is that it seems when I do `+` new file (via file list) the file is created, but it does not get open for editing. This works as expected on Windows though.

**Comment by vassudanagunta** [comment]
@nanoant take a look at #1000.

**Comment by abnerlee** [comment]
duplicate with #1000
