### ISSUE TITLE
Make Table Parsing GFM-compatible

### ISSUE THREAD

**Issue by loilo** [typora/typora-issues#2254]
> This is a replica of #2149 which I think should be revisited. I added some prior art below.
> I mainly opened this as a new issue because nobody reads comments in closed issues.

Typora struggles with rendering tables when they're not exactly formatted as expected.

The following should render as a table, which it does not:

```markdown
| abc | defghi |
:-: | -----------:
bar | baz
```

Table rows without leading or trailing pipes are explicitely allowed by the GFM spec ([which the example above is actually taken from](https://github.github.com/gfm/#example-192)). They're also supported by popular markdown parsers like [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20abc%20%7C%20defghi%20%7C%5Cn%3A-%3A%20%7C%20-----------%3A%5Cnbar%20%7C%20baz%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) or [marked](https://marked.js.org/demo/?text=%7C%20abc%20%7C%20defghi%20%7C%0A%3A-%3A%20%7C%20-----------%3A%0Abar%20%7C%20baz&options=%7B%0A%20%20%22gfm%22%3A%20true%2C%0A%20%20%22tables%22%3A%20true%0A%7D&version=master).

This shows a gap between Typora and GFM which would be great to see fixed. 🙂 

---

Obligatory disclaimer: Thanks for the great work on Typora, it makes writing markdown really enojoyable! ❤️

**Comment by CapinWinky** [comment]
To add to this, I'm trying Typora as a possible way for less tech-savvy people to view my extensive markdown documentation and when I open that documentation in Typora, NONE of my tables are rendered. It seems Typora requires the opening and closing pipe on every line. Even after adding the opening and closing pipe, many of my tables don't render until I remove tab characters from the alignment row.

**Comment by abnerlee** [comment]
should be fixed
