### ISSUE TITLE
typora can't remember the original display it was on after maximized.

### ISSUE THREAD

**Issue by francis59** [typora/typora-issues#2255]
**Software**
0.9.65 (beta)，Windows 10 Pro, Version 1809, Build 17763.316

**Hardware**
dual-display setup:
  - a laptop(1080p) + a 27-inch dell display(2k), both 125% scaling
  - the 27-inch dell display is the main display
  - in "Start > Settings > System > Display", the "Multiple displays" is set to "Extend these displays"

**Steps to reproduce**

on my main display (dell)
  1. open a markdown document with typora
  2. maximize the typora window, then close typora window
  3. open that markdown document with typora again

**Expect:**
the typora window show on my main display (dell), and maximized, as same as before it was closed.
**Actual:**
the typora window was shown on my laptop display, and maximized.

and after I went back to 0.9.60 (beta) , the problem solved, it can remember the previous display it was on, no matter it was maximized or not.

**Comment by abnerlee** [comment]
#2225
