### ISSUE TITLE
Search and replace bug with spaces

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#2256]
There's something odd about searching and replacing, especially when spaces are involved. Typora doesn't seem to recognize spaces.

- If I search on something like "dragonfly " and want to replace it with blank text, it removes the word dragonfly but not the trailing space.

- If I search on two spaces in a row and try to replace them with a single space, it doesn't find any examples (even when there are plenty in the text). 

I also see that it can't replace a single letter, or a single letter with a space after it. So searching for "s" or "s " finds nothing, even when there are plenty of examples in the text.

Finally (and I can't give an example), there are times when I try to search and replace that includes a space, and Typora will turn single spaces into two spaces. It's as if _search_ can't find spaces, but _replace_ can.

(I don't know if this ties into the fact that pasting from Firefox into Typora adds an extra space every 80 or so characters, but there's definitely something weird going on with spaces!)

**Comment by jendas1** [comment]
Faced the similar problem. Searching for character and a space, space is ignored so I can't e.g. search for "# " hash followed by space to find & decrement headers.

**Comment by abnerlee** [comment]
spaces is now respected in new version

**Comment by stbischoff** [comment]
I want to search and replace some spaces, but I'm not able to.

I want to replace four spaces with only one, but Typora (0.9.70) is not able to find those 4 spaces!?

Any ideas?

**Comment by xebico** [comment]
The newer versions still don't appear to respect spaces, at least in terms of search and replace. It's not just with pasted text; when I manually add several spaces to a paragraph, search and replace doesn't find them. 

If I paste that same text into Notepad++, that program will find them. So I don't think it's an issue with hidden characters. 

I've attached a simple file with a paragraph I cut and pasted from an e-mail in Thunderbird. You'll see all the extra spaces, but search and replace does not. (Sorry I had to zip it, but Github won't let me paste a Markdown file.)

And I still haven't figured out why Typora adds all those extra spaces to text pasted from Firefox or Thunderbird....

[spacing-example.zip](https://github.com/typora/typora-issues/files/3325345/spacing-example.zip)

**Comment by stbischoff** [comment]
> The newer versions still don't appear to respect spaces, at least in terms of search and replace. It's not just with pasted text; when I manually add several spaces to a paragraph, search and replace doesn't find them.
> 
> If I paste that same text into Notepad++, that program will find them. So I don't think it's an issue with hidden characters.
> 
> I've attached a simple file with a paragraph I cut and pasted from an e-mail in Thunderbird. You'll see all the extra spaces, but search and replace does not. (Sorry I had to zip it, but Github won't let me paste a Markdown file.)
> 
> And I still haven't figured out why Typora adds all those extra spaces to text pasted from Firefox or Thunderbird....
> 
> [spacing-example.zip](https://github.com/typora/typora-issues/files/3325345/spacing-example.zip)

Just a smill thing from my side. I also have extra spaces when pasting a text from Microsoft One Note. I don't have them pasting into Notepad++ or other applications...
