### ISSUE TITLE
View:  display word/character count

### ISSUE THREAD

**Issue by jlarmstrongiv** [typora/typora-issues#2258]
I would love an option to keep the word count or character count at the top of the page instead of only on hover.  

In addition, it would be wonderful to automatically switch the count at the top to selected words or characters when text is selected.  EDIT:  It looks like this feature is already implemented, the UI just disappears on occasion (I would love the option to have it sticky under view in the menu bar). 

Thank you for all the hard work you put into Typora! 🙂

**Comment by AlexPasternak** [comment]
I like the "select text to get its word count" suggestion, though that's definitely a nice-to-have feature only. Btw, if you're looking for alternatives in the meantime, TextMate has this in its Text bundle as "Statistics for Selection".

**Comment by abnerlee** [comment]
It's already supported

**Comment by jlarmstrongiv** [comment]
I checked view options and the menu bar; I didn’t think to check preferences.  My bad.  

Thank you 👍
