### ISSUE TITLE
Could not detect pandoc installed by chocolatey

### ISSUE THREAD

**Issue by chirsz-ever** [typora/typora-issues#2259]
Thanks for this great editor. I use 64-bit Typora on  64-bit Windows 7, and I installed pandoc 2.7 by chocolatey. Pandoc could be used in cmd shell and powershell successly, and `D:\Softwares\Chocolatey\bin` where `pandoc.exe` located is in `Path`. But when I try to export a makefile document to .docx, Typora tells me "Need to install pandoc to continue ...".
Could you fix this problem or instruct me how to make it work?

**Comment by abnerlee** [comment]
Have you try restart Typora?

Does pandoc and Typora are both 64bit? #2040

**Comment by chirsz-ever** [comment]
After update to the new version, it works well. Thanks a lot.
