### ISSUE TITLE
When the title to use Chinese, TOC does not display properly

### ISSUE THREAD

**Issue by likfe** [typora/typora-issues#226]
copy this to typora-0.9.9.5.1 for mac

```
[TOC]


# This is H1 `H1`

## This is H2 `h2`

###### This is H6 `<h6>`



When use Chinese:



# 第一级标题 `<h1>` 
## 第二级标题 `<h2>` 
###### 第六级标题 `<h6>` 
```

This is the rendering 
![4bc990f9-b107-4e03-b77a-0b41f43c6d5c](https://cloud.githubusercontent.com/assets/7094014/16908033/e6c46a74-4cfa-11e6-8ba8-2444c0873a83.png)

**Comment by abnerlee** [comment]
Fixed in new version
