### ISSUE TITLE
Menu bar is not useable after `autoHideMenuBar` is set to true

### ISSUE THREAD

**Issue by gstraymond** [typora/typora-issues#2260]
After enabling the option `autoHideMenuBar` in the `conf.user.json`, the menu bar is correctly hidden after restarting typora.

Clicking `alt` will open the menu, but when I try to interact with it, the menu disappears instantly.

So I can't interact anymore with the menu when this option is enabled. BTW, shortcuts like `ALT + F` to open the the File menu doesn't work either.

```
typora:  0.9.65-1
OS:      archlinux - Linux dellxps 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux
```

**Comment by abnerlee** [comment]
Based on Electron's document, the menu is invisible unless you press ALT.

About `ALT+F`, it is in #798

**Comment by gstraymond** [comment]
> Based on Electron's document, the menu is invisible unless you press ALT.
This is what I describe first "After enabling the option autoHideMenuBar in the conf.user.json, the menu bar is correctly hidden after restarting typora. Clicking alt will open the menu" 

The problem is here *but when I try to interact with it, the menu disappears instantly.*

**Comment by gstraymond** [comment]
I did further tests on my machines, since I have updated typora to `0.9.68`.

It's not working just after typora has been launched:
- menu appears when pressing ALT and menu disappears when the mouse is hover the menu

BUT if I change the focus on another windows and get back to typora, its working: menu appears when pressing ALT and I can browse the menu with my mouse.

So I don't know if the bug is still related to typora or to my tiling manager `i3 version 4.16.1 (2019-01-27)`

**Comment by osted** [comment]
Strange, I have similar problem - after I hit Alt, menu shortcut letters become underlined, but I can only navigate up / down in one menu. Left and right arrows do not work and neither does ESC to move focus back to text entry.

Funny thing is, that for me this only happens if I have:

```
"autoHideMenuBar": false,
```

in conf.user.json

**Comment by abnerlee** [comment]
>  Strange, I have similar problem - after I hit Alt, menu shortcut letters become underlined, but I can only navigate up / down in one menu. Left and right arrows do not work and neither does ESC to move focus back to text entry.

see #2854

**Comment by osted** [comment]
Unfortunately I still have the same issue :( 

Currently running 0.9.78 (beta) and once I open menu (drop down) I can only navigate up and down. To change from Edit to Paragraph, I first have to press Alt or ESC to close the menu. This is improvement from previous versions, since before not even Alt or ESC would close menus, but it is still different than regular windows apps.

**Comment by abnerlee** [comment]
> To change from Edit to Paragraph, I first have to press Alt or ESC to close the menu. 

What the expect behavior here, do you mean press "Alt+P" to open Paragraph menu?

**Comment by osted** [comment]
I would expect to be able to move from one drop down menu to the other using right / left arrows.

For example in Notepad, if you:

1. Press Alt+E (Edit menu opens)
3. Press right arrow (Format menu opens)
4. Press right arrow again (View menu opens)

In Typora:

1. Press Alt+P (Paragraph menu opens)
2. Press right arrow - nothing happens
3. Press left arrow - nothing happens
4. Press ESC or ALT - paragraph menu now closes
5. I can press other ALT combinations to open other menus.

**Comment by vinliao** [comment]
I still have this problem. After enabling the `autoHideMenubar` the menu bar doesn't show up at all when I click alt.
