### ISSUE TITLE
Reveal in Finder crashes Typora

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#2261]
Typora: Version 0.9.9.22 (1979)
macOS: 10.14.3

When right click on an image in md document and choose Reveal in Finder Typora crashes and is not showing image in folder. 

I enabled Copy image to ./$filename.assets

**Comment by abnerlee** [comment]
could you provide examples?

**Comment by Acidham** [comment]
Attached zip with an md file and assets folder.

1) first right click on image and Reveal fin Finder is opening Finder but shows Recents or something but not the Assets file in folder
2) second right click → Crashes Typora
[Archive.zip](https://github.com/typora/typora-issues/files/2973865/Archive.zip)
