### ISSUE TITLE
<span style="text-align:justify;display:block"> is not being rendered correctly

### ISSUE THREAD

**Issue by Foadsf** [typora/typora-issues#2262]
From [here ](https://stackoverflow.com/questions/29368902/how-can-i-wrap-my-markdown-in-an-html-div/50974387#50974387) I can use the HTML tag `<span style="text-align:justify;display:block"> ... </span>`  to include markdown inside the HTML tags. The reason is that I want my text to be aligned-justified. This can be rendered on Visual Studio Code side preview. However Typora can't Render it properly. for example:

```
<div style="text-align:justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  **Tincidunt** augue interdum velit euismod in pellentesque. Quam nulla porttitor massa id neque. Amet massa vitae tortor condimentum lacinia. Pharetra diam sit amet nisl. Molestie a iaculis at erat pellentesque adipiscing commodo elit.</div>
```

is justified correctly (but ignores MarkDown). and also

```
<span style='color:red'>This is red</span>
```

renders as expected with red. But

```
<span style="text-align:justify; display:block">Vitae suscipit tellus mauris a diam maecenas. Egestas diam in arcu cursus euismod quis. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Enim sit amet venenatis urna cursus eget. Eu facilisis sed odio morbi quis commodo odio aenean. Duis ut diam quam nulla porttitor massa. </span>
```

doesn't respecter the styling for alignment justification. I would appreciate if you could help me know what is the problem and how it can be resolved.

**Comment by abnerlee** [comment]
We don't allow `display` change for inline components

**Comment by Foadsf** [comment]
@abnerlee So how can I have a justify-alligned MarkDown  paragraph in Typora?

**Comment by abnerlee** [comment]
use 

```
<div style="text-align:justify">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  **Tincidunt** augue interdum velit euismod in pellentesque. Quam nulla porttitor massa id neque. Amet massa vitae tortor condimentum lacinia. Pharetra diam sit amet nisl. Molestie a iaculis at erat pellentesque adipiscing commodo elit.
</div>
```

but requires #1939 

(I see in Github the `**Tincidunt**` is also not rendered)

<div style="text-align:justify">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  **Tincidunt** augue interdum velit euismod in pellentesque. Quam nulla porttitor massa id neque. Amet massa vitae tortor condimentum lacinia. Pharetra diam sit amet nisl. Molestie a iaculis at erat pellentesque adipiscing commodo elit.
</div>

---
or custom your CSS file http://support.typora.io/Add-Custom-CSS/

**Comment by Foadsf** [comment]
@abnerlee The `<div>` tag does not render the MarkDown syntax correctly. I had to switch to AsciiDoc for several reasons, including this and what I have explained [here](https://www.reddit.com/r/writing/comments/b0ywcw/free_markdown_editors_with_live_preview_for/).  [This is the final result](https://gist.github.com/Foadsf/44fe9b5e2bcb02b22392adf6d8f7a871). It would be great if I could have all this with MarkDown in the first place.

**Comment by timeagotemperate** [comment]
@Foadsf https://electrondemographic.github.io/pgnYQEAs6MMlYDQe60gxpi66bmGT4T/
