### ISSUE TITLE
URL will not be opened in Browser (0.9.9.23 (2256))

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#2266]
`CMD` + Click on a Link will usually open the link in the Browser. With latest updated of Typora, Typora does not open the Link anymore

**Comment by rowdenw** [comment]
I experience the same on macOS Mojave 10.14.3, typora Version 0.9.9.23 (2256) beta, for any URL. In addition, link to an MD file in the same directory fails as well. The latest update seems to have introduced a bug in link-following.

**Comment by abnerlee** [comment]
Fixed in new release, please check for updates.

**Comment by Acidham** [comment]
fixed in latest version thx!
