### ISSUE TITLE
Subscript shortcut working in Version 0.9.9.23 (2256)

### ISSUE THREAD

**Issue by fliptanedo** [typora/typora-issues#2267]
Since updating to Version 0.9.9.23 (2256), the use of `~` for subscript does not work. 

In Typora > Preferences > Markdown, I have inline math, subscript, and superscript checked. Both the inline math and superscript work. Previously, subscript worked, but it now doesn't work:

```
A~a~ does not produce the same thing as A<sub>a</sub>
``` 

The result should be A<sub>a</sub>. 

I am using macOS. And have restarted Typora multiple times.

**Comment by abnerlee** [comment]
Fixed in new release, please check for updates.
