### ISSUE TITLE
incorrect indent for code block inside ul

### ISSUE THREAD

**Issue by proclaim** [typora/typora-issues#2269]
indent is not quite aligned if the code block's line is without line break
![indent-issue](https://user-images.githubusercontent.com/2252778/54406812-85229700-4716-11e9-80f4-5d0ad9d92bb6.jpg)

**Comment by abnerlee** [comment]
could you provide sample markdown?

**Comment by proclaim** [comment]
sure, here's the code in "source mode"



1. asdoijasdfa

2. ```
   Executing (default): SELECT `id`, `event_type`, `event_message_proto`, `token`, `state`, `event_target_id`, `created_at`, `updated_at` FROM `event_logs` AS `event_log` WHERE `event_log`.`state` = 'pending' ORDER BY `event_log`.`created_at` ASC LIMIT 100;
   ```

3. sdfasdf

**Comment by abnerlee** [comment]
fixed in new release.

Syntax highlight in source code mode is in #1638
