### ISSUE TITLE
Embedded HTML

### ISSUE THREAD

**Issue by yoyoworkout** [typora/typora-issues#227]

**Comment by kylejung** [comment]
+1

**Comment by lewisl** [comment]
Why did you close this?  Multimarkdown is required to support html tags.  That's the spec.  You don't get to pick and choose. That's the spec.  This is important.  The case:  when working with Jupiter notebook (formerly known as IPython notebook) nbconvert can export as markdown.  Tables are always generated using <table> blah, blah...  </table>.  This is a major use case for researchers, a reasonable part of your limited market.

**Comment by jken2012** [comment]
Users are badly in need of the feature on embed elements of <table>, <tr>, <td rowspan...>, <td colspan...>.  This is what we honestly expect for so long.

**Comment by bellemere** [comment]
that's why I choose macdown finally

**Comment by leonard-seydoux** [comment]
Indeed, Typora is a very useful tool with good-quality interface, but I had to switch to Macdown since we cannot use more html tags in Typora. I personally create interactive figures in html with `Bokeh`, and having the possibility to embed them with the `<iframe>` tag would be of high interest.

**Comment by tomer-ben-david** [comment]
in addition if i add a gist it would be great if it could be expanded, currently I just see the reference to the gist, is it related to iframe support? (this is what I see when I add a gist) <script src="https://gist.github.com/tomer-ben-david/7c3495ae903bb083b290ec9a69bdaffe.js"></script>

**Comment by vassudanagunta** [comment]
Typora's is committed to supporting [GitHub Flavored Markdown](https://github.github.com/gfm/) and CommonMark (the former is a strict superset of the latter). Here are their specs for [HTML blocks](https://github.github.com/gfm/#html-blocks) and [inline HTML](https://github.github.com/gfm/#raw-html) support, which Typora should follow.

More reason to prioritize #369.

**Comment by abnerlee** [comment]
We supports HTML, not in live rendering mode, though.

I will support some common/simple HTML tag in live rendering mode, but not fully, or else we are building a HTML editor, then

**Comment by richblack** [comment]
Temporarily you can insert inline LATEX, it can change text color.
`$\textcolor{colorName}{Text to be colored}$`
[You can find LATEX color names here](http://latexcolor.com/)
LATEX also supports HEX and RGB color expressions.

**Comment by abnerlee** [comment]
Supported in new release

**Comment by mmagdyy** [comment]
@abnerlee Is the new version available for Linux? 
The binaries seem to be outdated: https://typora.io/#linux
