### ISSUE TITLE
Cannot open location abc.md, do you mean https://abc.com

### ISSUE THREAD

**Issue by normantian** [typora/typora-issues#2270]
When I upgrade typora 0.9.9.23 (0.9.66) beta, it always show Error “Cannot open location abc.md, do you mean https://abc.com ?” shows when I trying to open the link.

**Comment by normantian** [comment]
Before upgrade, I use 0.9.9.22 this function is OK.

**Comment by rowdenw** [comment]
I experience the same on macOS Mojave 10.14.3, typora Version 0.9.9.23 (2256) beta, for any link to an MD file in the same directory. In addition, URLs fail to launch.

**Comment by abnerlee** [comment]
Fixed in new release, please check for updates.
