### ISSUE TITLE
Keybindings issues - ctrl-n/p != arrow down/up

### ISSUE THREAD

**Issue by beorn** [typora/typora-issues#2272]
On MacOS 10.14.3, Typora 0.9.9.22

I’ve noticed that ctrl-p doesn’t behave as arrow-up, and ctrl-n doesn’t behave as arrow-down (ctrl-f/b works as expected, though)?  These work the same in all other apps.  They’re emacs keybindings.

Specifically, if I have empty lines, ctrl-p/n will skip over them, whereas arrow up/down does not.

**Comment by abnerlee** [comment]
#1161
