### ISSUE TITLE
Links to word/file/folder aren't possible via drag & drop

### ISSUE THREAD

**Issue by myn-user** [typora/typora-issues#2274]
Hi,
when I drag a word-file to typora, the program "import" the text of the word file into Typora, but I am only want the link.
Would it be possible, that a user can choose if the program import the text or create a link?

**Comment by Hologos** [comment]
+1

**Comment by phoenixwu** [comment]
+1

**Comment by skleber** [comment]
+1

**Comment by congmingyige** [comment]
That's truly very important. Also, sometimes HTML links can not drag into Typora.

**Comment by abnerlee** [comment]
supported in https://support.typora.io/What's-New-1.6#files-section-in-preferences-panel
