### ISSUE TITLE
Bug of pandoc version dectection

### ISSUE THREAD

**Issue by chenxu2048** [typora/typora-issues#2276]
+ OS version: Windows 10 Pro 1809 17763.316
+ Typora version: 0.9.66(beta)
+ Pandoc version: 2.7.1

Procedure:
1. Install typora via chocolatey
> choco install typora -ia '\DIR "C:\Program Files\Typora"'
2. Install pandoc via chocolatey
> choco install pandoc
3. Open typora and export file as docx. It says that "Require Pandoc to Continue...".

**I thought this may be a bug in the file at app/window/frame.js**

![image](https://user-images.githubusercontent.com/15109893/54434918-4ae2e500-476a-11e9-967a-fc3a22afa192.png)

```js
i.stdout.toString("utf8").split(/\r|\n|\r\n/)[0]).match(/[\d.]+/)
```
In code fragment, a regex ``/[\d.]+/`` is used to match the pandoc version information. However, the output of command ``pandoc --version`` is:

![image](https://user-images.githubusercontent.com/15109893/54435054-98f7e880-476a-11e9-9b27-80925f2591b2.png)

**No version information but '.' in "pandoc.exe" is matched**. Hence, Typora could not address this problem and read a wrong version.

**Comment by abnerlee** [comment]
Fixed in new release, please check for updates.
