### ISSUE TITLE
Permanently loosing text passages

### ISSUE THREAD

**Issue by nickbe** [typora/typora-issues#2277]
When switching between wsywig and source because you have to correct mistakes that typora makes - means a constant loss of text. 

I just deleted some spaces in source mode tonight and later I noticed that the lower half of my text was gone.

Very.... very annoying

**Comment by abnerlee** [comment]
version info?

**Comment by nickbe** [comment]
Latest 9.66

**Comment by nickbe** [comment]
btw. it would be nice to know how much you plan to charge for typora, once it's finished.

**Comment by abnerlee** [comment]
Any details/examples that can reproduce this?

**Comment by nickbe** [comment]
Only thing I can say is that I changed to sourcemode because I couldn't get rid of some formatting issue and some times later I noticed that I couldn't scroll further down my text because 90% was gone.

**Comment by nickbe** [comment]
Is there a way to make the undo buffers any bigger?

**Comment by vassudanagunta** [comment]
> changed to sourcemode because I couldn't get rid of some formatting issue 

@abnerlee I have to do this often, most often when working with lists. Is there an open issue for that already?

**Comment by abnerlee** [comment]
@vassudanagunta No opened ones. Are you seeing this in recent versions?

**Comment by vassudanagunta** [comment]
@abnerlee Yes. It almost always has to do with lists. Recently there was something that happened more than once with non-list formatting. Can't remember exactly. I don't create an issue because (1) they impossible to reproduce, arising from program state not content state (2) they are spurious and annoying but can get around with source mode.

Once in a while I've experienced the data loss behavior (though not sure if same a described in this issue). But I've always caught it early enough that Undo  saves me. Undo itself has sometimes been unreliable, but lately it seems more solid.

**Comment by lrhn** [comment]
I had a similar issue happen to me once, likely on 0.9.66. Was writing, switched to source mode, switched back, and was missing the latter half of my document. There was no undo.
Only happened once, so I can't say what triggered it.

**Comment by nickbe** [comment]
Happened 3 times here.  Also without any clue as to what caused the problem...

**Comment by FracKenA** [comment]
Version 9.7.7

Working on Document, Noticed that the Side Panel had not added my most recent header, I was about 350 words into it. Switched to Source view to look and see what was wrong. As soon as source view opened. Almost half of my doc was gone.

**Comment by jsteenkamp** [comment]
I had the same issue but unable to reproduce - Version 0.9.9.30.1 (3794) macOS. I went back to revisions but they all showed the same which was also strange. Was bad as I did not know a section had vanished, exported to PDF and distributed to team. Love Typora and my goto editor but my confidence has been dented.

**Comment by callimero** [comment]
Do you save to a networked Folder?

**Comment by nickbe** [comment]
No. Just local drives. Still the same bug. On sever occasions I've lost the bigger part of a document 😞 
I'm still hoping for the best though. If you play around with source view, tab, enter, ctrl-enter, tables, cuts and pastes long enough you will stumble upon some strange text behaviour or loss of text almost every time. And although it's hard to reproduce the steps, all I can say is that as a document gets more and more complex and large there's some strange behaviour almost every time.

**Comment by abnerlee** [comment]
How about v0.10.11?

**Comment by abnerlee** [comment]
relates #4415
