### ISSUE TITLE
Can not paste as plain text

### ISSUE THREAD

**Issue by SallyWY** [typora/typora-issues#2279]
Based on the updated version of 'Version 0.9.9.23 (2256)' I got on 20190315.
On macOS, the shortcut of 'paste as plain text' is 'command + shift +V'. 
But after today's update, I can no longer use this shortcut.
Also, the function of 'Paste as Plain Text' doesn't seem to work anymore.
Thanks!

**Comment by abnerlee** [comment]
Cannot reproduce this, could you provide more details?

**Comment by SallyWY** [comment]
![Screen Shot 2019-03-15 at 3 57 35 PM](https://user-images.githubusercontent.com/25224937/54461370-b1690280-476c-11e9-8acf-f77e721d34a1.png)

As the picture above shows, I would like to "Paste as Plain Text" the text with a hyperlink.
But it seems the shortcut "Command + shift +V" for macOS doesn't work.

**Comment by SallyWY** [comment]
![Screen Shot 2019-03-15 at 3 57 35 PM](https://user-images.githubusercontent.com/25224937/54461459-e8d7af00-476c-11e9-9dc5-2ac8d549dfcf.png)

As the picture above shows, I would like to "Paste as Plain Text" the text with a hyperlink.
But it seems the shortcut "Command + shift +V" for macOS doesn't work.
This shortcut and function worked great before I update Typora today. It suddenly went wrong this morning when I update Typora to the latest version.

Thx!
