### ISSUE TITLE
0.9.66 Windows - Export HTML non functional

### ISSUE THREAD

**Issue by rkeir** [typora/typora-issues#2280]
Just updated to 0.9.66 on Windows. Export to HTML (`File -> Export -> HTML`) does not offer a file-save dialog. Thus, the feature appears to be non-functional.

FYI - Exporting to `HTML without styles` does still work, however.

**Comment by sviatoslav-lebediev** [comment]
I have the same problem with the 0.9.9.23 version and MacOs Mojave. Typora shows an export to HTML dialog when I click export - it crashes.

**Comment by Prooffreader** [comment]
Same exact issue on 0.9.66 on Linux

**Comment by abnerlee** [comment]
Fixed in new release, please check for updates.

**Comment by rkeir** [comment]
Confirmed working in new release. Thanks!

**Comment by Prooffreader** [comment]
Also confirmed on Linux, great turnaround, thank you.
