### ISSUE TITLE
line breaks behaves weird in table cells

### ISSUE THREAD

**Issue by fuzzy76** [typora/typora-issues#2281]
shift-enter in a table cell inserts <br />, but typora renders the tag in addition to breaking the line.

Related: #33 (it was reported there, but after the original, slightly different issue, was closed)

![Skjermbilde 2019-03-15 kl  15 59 33](https://user-images.githubusercontent.com/218995/54440757-9e8a0a00-473b-11e9-8ef8-a50986895ad2.png)

**Comment by abnerlee** [comment]
Hide/show `<br/>` from "Edit" -> "Whitespace and Line Break" menu
