### ISSUE TITLE
Support the other language on the global search (e.g., Korean)

### ISSUE THREAD

**Issue by Agile-yun** [typora/typora-issues#2282]
I love the global search function, but it only supports English. 
On the Mac OS X, when I just find the Korean using Cmd + F, it can find the korean text, but I use the global search using Cmd + Shift + F, it cannot find the korean text.

Can you support the other language on the global search?
I attached captured image to show this problem. Like 3rd and 4th images, local search of korean is possible, but the global search of korean does not operate. 

![2019-03-16_10-55-42](https://user-images.githubusercontent.com/28855331/54469382-93d28200-47da-11e9-9f6b-92106de20fae.jpeg)

![2019-03-16_10-56-46](https://user-images.githubusercontent.com/28855331/54469390-a9e04280-47da-11e9-9d69-e48c05bb5d16.jpeg)

![image](https://user-images.githubusercontent.com/28855331/54469363-67b70100-47da-11e9-875d-287813255f70.png)

![2019-03-16_10-57-09](https://user-images.githubusercontent.com/28855331/54469371-78677700-47da-11e9-8d88-170d6c981453.jpeg)

**Comment by LauraCardea** [comment]
I have the same problem with German words containing diacritics. It would be great, if that was fixed!

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by simpsonys** [comment]
> should be fixed in new release

I found still this problem has been occured in windows version. 
is this fix only included in MAC version ?
