### ISSUE TITLE
Chinese punctuation marks convert to English punctuation marks.

### ISSUE THREAD

**Issue by SakigamiYang** [typora/typora-issues#2283]
I tried many punctuation marks. Brakets and quotations will be converted into half-wide punctuations.
e.g. （）【】「」“” etc.

OS：macOS（Mojave）
Typora version: 0.9.9.23 (2256)
Input software: Sogou input (a production made by a chinese company named Sogou.)

**Comment by abnerlee** [comment]
check options under `Edit` -> `Substitutions` -> `Remap...`

**Comment by SakigamiYang** [comment]
@abnerlee 
> check options under `Edit` -> `Substitutions` -> `Remap...`

I had checked this option before asking this question and surely I am not a fool.
I haven't used any user-defined mapping.
I just think that an editor should keep what user had input in default case, shouldn't it?

Thx for giving me the suggestion to solve the problem.
But it's a little bit arbitrary that close an issue without seeing whether others can solve their problems with your own suggestions.

**Comment by abnerlee** [comment]
The option should be unchecked.

see http://support.typora.io/SmartyPants/

**Comment by xu-kai-xu** [comment]
I use Typora (version 0.9.83 beta) on windows and i meet the same problem. I can not find the settings `Edit ` -> `Substitutions` -> `Remap...`. I can not input Chinese quotations. I also attached the file i used to test the quotations. Thanks for your help.
[English quotation.md.txt](https://github.com/typora/typora-issues/files/4051878/English.quotation.md.txt)

**Comment by abnerlee** [comment]
@xu-kai-xu In your attached file, `“中文的引号”` is using the Chinese quotations

**Comment by xu-kai-xu** [comment]
`"english quotations", english quotations", english quotations"`
`“中文的引号”，“中文的引号”，“中文的引号”`

Thank you. @abnerlee , So the difference is just the shape of the quotations. Is that rignt?

But in Chinese convention, each quotation should take the place just as a character, e.g., the following picture shows:
![TIM截图20200120163218](https://user-images.githubusercontent.com/44153643/72710631-7f050e80-3ba2-11ea-9e94-6828a33d8958.png)

which means Chinese quotations should be treated as a full-width character.

In markdown, the two quotations just look different in their shapes, they both belong to half-width character.

**Comment by abnerlee** [comment]
The "shape" depends on which font you use, like in my screen, the quotes you use looks like:

<img width="497" alt="Screen Shot 2020-01-27 at 17 45 08" src="https://user-images.githubusercontent.com/1621242/73164357-c6544780-412c-11ea-8247-1e9c5a563e81.png">

But they are still the same quotes in your screenshot. If you want some char be rendered differently, you could try change a theme or change the font.

**Comment by xu-kai-xu** [comment]
OK, thanks a lot for your help.
