### ISSUE TITLE
html chart 

### ISSUE THREAD

**Issue by Layty** [typora/typora-issues#2284]
Table display  show  one more empty lines like that 
![AVgcuQ.png](https://s2.ax1x.com/2019/03/16/AVgcuQ.png)
code is that
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>123</td>
			<td>222</td>
		</tr>
		<tr>
			<td colspan="2">111222<br />
			555<br />
			666<br />
			888<br />
			999</td>
		</tr>
		<tr>
			<td>222</td>
			<td>111</td>
		</tr>
	</tbody>
</table>
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>123</td>
			<td>222</td>
		</tr>
		<tr>
			<td colspan="2">111222<br />
			555<br />
			666<br />
			888<br />
			999</td>
		</tr>
		<tr>
			<td>222</td>
			<td>111</td>
		</tr>
	</tbody>
</table>

we need to change 
```
  <table border="1" cellpadding="1" cellspacing="1" style="width:500px"> 
   <tbody> 
    <tr> 
     <td>123</td> 
     <td>222</td> 
    </tr> 
    <tr> 
     <td colspan="2">111222<br /> 555<br /> 666<br /> 888<br /> 999</td> 
    </tr> 
    <tr> 
     <td>222</td> 
     <td>111</td> 
    </tr> 
   </tbody> 
  </table>
```

 <table border="1" cellpadding="1" cellspacing="1" style="width:500px"> 
   <tbody> 
    <tr> 
     <td>123</td> 
     <td>222</td> 
    </tr> 
    <tr> 
     <td colspan="2">111222<br /> 555<br /> 666<br /> 888<br /> 999</td> 
    </tr> 
    <tr> 
     <td>222</td> 
     <td>111</td> 
    </tr> 
   </tbody> 
  </table>

you can see both of them works well on github

**Comment by abnerlee** [comment]
Fixed in new release, please check for updates.
