### ISSUE TITLE
'Cut' doesn't work in Windows if Shift+Del is pressed

### ISSUE THREAD

**Issue by kudryashov** [typora/typora-issues#2285]
This looks similar to #39, however with a different shortcut.

Windows 10 (version 1809), Typora 0.9.67. 

I'm accustomed to using Shift+Del to cut text - this shortcut works in virtually every application I use - IDEs, text editors, office applications, web browsers etc. However in Typora the shortcut just deletes the text and doesn't place it into the clipboard. 

This is somewhat distracting as it breaks the usual flow - you cut something and then later on try to paste it somewhere else and then you discover that the text had been just deleted.

**Comment by abnerlee** [comment]
fixed in new release
