### ISSUE TITLE
Typora can not sort files in Version 0.9.9.23.2 (2270)

### ISSUE THREAD

**Issue by PeterDing** [typora/typora-issues#2288]
The `Sort by ...` functions break when I click any one of them and the files' list shows nothing.

My environment is:

```
Mac OS X 10.14.2
Typora 0.9.9.23.2 (2270)
```

Screenshots are following.

<img width="541" alt="Screen Shot 2019-03-17 at 7 01 01 AM" src="https://user-images.githubusercontent.com/670690/54482782-b9679600-4883-11e9-8b2c-8b360eff7396.png">
<img width="541" alt="Screen Shot 2019-03-17 at 7 01 27 AM" src="https://user-images.githubusercontent.com/670690/54482783-bbc9f000-4883-11e9-92e0-a7ee4aa3a14f.png">
<img width="541" alt="Screen Shot 2019-03-17 at 7 01 37 AM" src="https://user-images.githubusercontent.com/670690/54482785-bd93b380-4883-11e9-9c51-9783d91103c9.png">

**Comment by abnerlee** [comment]
can this be reproduced?

**Comment by abnerlee** [comment]
fixed in new release
