### ISSUE TITLE
Clicking on outline entry jumps to top rather than to item's header

### ISSUE THREAD

**Issue by i-blis** [typora/typora-issues#2291]
Version: 0.9.9.23.2 (beta)
OS: MacOS 10.13.4

Clicking on an entry in the outline doesn't jump to the given header but rather to the top of the document. I noticed this in the previous beta version and thought it might be a regression bug, but it appears not to have been fixed by the last regression bug fix (0.9.9.23.2).

A similar issue on Windows seems to have been fixed not long ago : [Outline jumps to top when I click on a sub-item below the screen](https://github.com/typora/typora-issues/issues/2197)

Thanks in advance, Typora is amazing.

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
