### ISSUE TITLE
Why I get repeated character when input the table in Chinese.

### ISSUE THREAD

**Issue by C1erman** [typora/typora-issues#2292]
At first time I thought it was caused by the theme, and then I found out it wasn't. 
The frequency is not very high, but it bothers me.
In the table, when I want to fill in  "中文", I always get  "z中文 ".
In Chinese pinyin，"中文" is “zhongwen”. So I got an extra "z".

**Comment by C1erman** [comment]
version 0.9.66 (beta)
System Win 10

**Comment by abnerlee** [comment]
possibly duplicate with #3077
