### ISSUE TITLE
Failed to Copy Image to Target Folder Issue - KO

### ISSUE THREAD

**Issue by MangKyu** [typora/typora-issues#2293]
At first, My Operating System is Windows 10 Education.
I usually copy images through snipping tools which of short-cut is shift + windows + s.
After image is copied to my clipboard and if I paste it to typora, image file is saved in directory like below.
C:\Users\Mang\AppData\Roaming\Typora\typora-user-images\1552829971018.png
Everything is fine for now, but if I clicked "Copy Image To..." and try to save image file,
I got "Failed to Copy Image to Target Folder." with no such file or directory, lstat 'C:\Users\Mang\AppData\Roaming\Typora\typora-user-images\1552829971018.png' but file is exists

![image](https://user-images.githubusercontent.com/17094600/54492414-b8794780-4909-11e9-9ac4-d04d1451a92e.png)

**Comment by abnerlee** [comment]
fixed in new release
