### ISSUE TITLE
Links with '_' dont get resolved/redered properly

### ISSUE THREAD

**Issue by thezaza101** [typora/typora-issues#2294]
Links with an underscore seems to get split. While it isn't the norm for links to have a _ in them, some YouTube videos do.

I.e.:
https://www.youtube.com/watch?v=_bhahBlah

Typora only resolves "https://www.youtube.com/watch?v" and the rest is plain text

Typora version 0.9.67, Windows 10.

**Comment by FSXAC** [comment]
I think it's because pasting the link directly to your text is not a CommonMark standard.

You can either put it inside `<>` tags like
`<https://www.youtube.com/watch?v=_bhahBlah>`

or use the link syntax.

`[https://www.youtube.com/watch?v=_bhahBlah](https://www.youtube.com/watch?v=_bhahBlah)`

**Comment by abnerlee** [comment]
merge into #1590
