### ISSUE TITLE
Trying to add Romanian language for spellcheck

### ISSUE THREAD

**Issue by ctanas** [typora/typora-issues#2298]
Windows language is set to English, but Romanian language pack is downloaded. I've put the Romanian hunspell dictionaries in {typora-user-folder}\dictionaries. Still, ro_RO is unavailable for the spellcheck and I'm not receiving “Install dictionary file only for Typora“ notification either (spell check is set on Auto Detect Language). Any hints? What am I doing wrong?

**Comment by abnerlee** [comment]
we only support languages in https://github.com/typora/Typora-i18n

**Comment by stanstrup** [comment]
This means there is no way to install hunspell dictionaries or something else without translating the whole interface?

**Comment by abnerlee** [comment]
We will list all supported languages in our interface for users to choose for spellcheck. So user cannot choose any language not exists in that list.

I understand your requirement, but it is not a common request. We will consider it in future

**Comment by stanstrup** [comment]
I understand you cannot support all possible languages in the GUI. But what confuses me is that you seem to be using Hunspell dictionaries which already exist in many languages but they cannot be used directly from Hunspell? Personally I am looking for Danish spellcheck.

**Comment by abnerlee** [comment]
They are "Hunspell dictionari**es**", and using Hunspell requires Typora to dict of which language should be loaded, auto detect languages may work. But we also allow users to choose the spellcheck language in our GUI, so, for new languages we must put it in our "spellcheck list" then user can choose it.

**Comment by sngreen** [comment]
But how does one change the interface language? - in settings I set to English (as an example), which tells me it will be changed to after restart, and no, it restarts with whatever language was there before. Is there some configuration file that should/could be used instead?
