### ISSUE TITLE
Creating new file on Windows network disk shows Untitled.md and new file

### ISSUE THREAD

**Issue by elentirmo** [typora/typora-issues#2300]
Typora version 0.9.9.67 on Windows

After creating a new file, the file tree shows both the `Untitled.md` and the new file. When I click `Untitled.md`, Typora shows the error "Failed to load file (ENOENT: no such file or directory)". The tree then reloads and the `Untitled.md` file is gone.

Even though #1906 is fixed, the issue still seems to occur when the directory is on a Windows network disk (a file share mounted on a drive letter).

**Comment by banjerluke** [comment]
This is also true for directory junctions ("symlinks") as well, it seems.

**Comment by elentirmo** [comment]
Seems to be fixed in 0.9.68. That was fast work!
