### ISSUE TITLE
Printing a file results in unreadable characters

### ISSUE THREAD

**Issue by benwhi** [typora/typora-issues#2302]
Printing directly from Typora, either to a local printer or a PDF, results in unreadable characters. I haven't checked if it's to do with the theme (I have Pixyll applied). Copying the file contents and pasting into a word document works correctly (as does copying and pasting elsewhere) and the file prints fine. Language: English. Typora 0.9.67, Windows 10 x64.

**Comment by abnerlee** [comment]
>  results in unreadable characters

what kind of unreadable characters?
