### ISSUE TITLE
Incorrectly indent of list item

### ISSUE THREAD

**Issue by wiwiwa** [typora/typora-issues#2306]
The following markdown source code is not displayed correctly.
```markdown
* [ ] A
  * B
    * C
      * D
```

The line `D` is not indented correctly. If file is edited, the source code of line `D` is also incorrectly indented.

Typora version: 0.9.9.23.2 (2270)
OS: macOS 10.14.3

**Comment by abnerlee** [comment]
should be fixed in new release
