### ISSUE TITLE
Status Bar toggles all instances of typora

### ISSUE THREAD

**Issue by missescher** [typora/typora-issues#2308]
Minor. Using latest (0.9.68). Only a problem for multiple application instances.

When I have multiple Typora's open, if I toggle the status bar, all instances of Typora will toggle the status bar whether it's already on or off (whereas the rest of the View options only seem to affect one instance).

Wouldn't be an issue, but weirdness can occur if I do this:
1. Open first instance of typora--status bar is on by default
2. Switch off status bar in first instance
3. Open second instance of typora--status bar in this instance is on by default and in first instance status bar is still off
4. Switch off status bar in second instance
5. Now in the second instance my status bar is off but in the first instance the status bar is back on.

If I click the status bar off in the first instance again, the bar will switch off in the first instance and back on in the second instance and so on. Have to close instances to get them back in sync.

(Overall, really enjoying the software, guys.)

**Comment by abnerlee** [comment]
The status bar can be not synchronized technically, but I don't see any merits doing so, what's your user case for this behavior?

**Comment by missescher** [comment]
I use multiple instances if I'm working across multiple folders of files (each folder usually representing some kind of distinct 'project' that I jump between frequently enough), or files that are in different locations for whatever reason. I can be working on one thing, then have a thought about another unrelated thing and want to open another typora to keep my concerns separate, not lose my place etc. Then the status bar gets out of whack.

If hiding the status bar in one instance hid it in every instance, that would be understandable. If hiding the status bar in one instance only affected _that_ instance, that would be understandable too. But when I hide the status bar in one instance it should definitely not become unhidden in all the other instances. That makes no sense. It seemed like a bug to me so I thought I'd let you know (despite the fact that it is obviously a very small issue).

Also the menu ends up lying to you--says it's showing the status bar but it's not:

![image](https://user-images.githubusercontent.com/12252439/56114251-a8559600-5fa3-11e9-877f-ef3491ece77a.png)

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
