### ISSUE TITLE
Table border is missing

### ISSUE THREAD

**Issue by xlicz** [typora/typora-issues#2309]
The markdown source I write is:

![image](https://user-images.githubusercontent.com/4654912/54735610-1f388280-4be2-11e9-8f47-e132aec86389.png)

What Typora display is:
![image](https://user-images.githubusercontent.com/4654912/54735638-42fbc880-4be2-11e9-8266-0bf40fbd0c91.png)

The table border is missing.

OS version: Ubuntu 16.04

Typora version: 0.9.68

Detailed steps to reproduce the bug: Just create a table in any Markdown file.

**Comment by abnerlee** [comment]
Will switch theme, then switch it back solve the issue?

**Comment by xlicz** [comment]
Thanks, this does work!

Notice for others: remove and reinstall again doesn't work.

**Comment by xlicz** [comment]
Excuse me for reopening this issue. When I reboot my computer, the problem happens again, and I have to do the same thing again, I think we need a permanent fix.

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
