### ISSUE TITLE
Spell check not work for spanish on Windows 7

### ISSUE THREAD

**Issue by AdrianMadu** [typora/typora-issues#2315]
Download dictionary dont work for windows 7. When I click on "Install dictionary" Typora download dictionary but after Typora ask me for download again.

I use spanish dictionary but I think dont work for all languages.

I recorded a gif:

![GIF](https://media.giphy.com/media/wHBFGeaWfd8Q9bPqPh/giphy.gif)

On .\Roaming\Typora\dictionaries I have es.dic and es.aff files.

Version 0.9.68

**Comment by abnerlee** [comment]
I cannot reproduce this one, could you try rerestart Typora, and does other language works?
