### ISSUE TITLE
About Pdf export

### ISSUE THREAD

**Issue by mysmlz** [typora/typora-issues#2317]
This is the code I wrote.

```
[![xml proposal order](images/xml-proposal-order-1553236583496.png)](https://github.com/mybatis/mybatipse/blob/master/screen/xml-proposal-order.png)
```
When I export PDF in preview mode(small),It pops up the following error:
![image](https://user-images.githubusercontent.com/38951157/54806068-e5d04780-4cb3-11e9-95a3-efc878a30b7e.png)
But,in code mode,It succeeded.
![image](https://user-images.githubusercontent.com/38951157/54806139-1c0dc700-4cb4-11e9-9ef4-4beff28d68c8.png)
And,in source code mode,It succeeded too.
**I hope you will solve this bug as soon as possible.**

**Comment by abnerlee** [comment]
possible to send us <hi@typora.io> the sample md file? I can export in preview mode without error using `[![xml proposal order](images/xml-proposal-order-1553236583496.png)](https://github.com/mybatis/mybatipse/blob/master/screen/xml-proposal-order.png)`

Also, what's your Typora version?

**Comment by mysmlz** [comment]
0.9.68

**Comment by hodanli** [comment]
i have the same issues for %50 percent of the time. it is hit or miss.

**Comment by abnerlee** [comment]
still happens for latest version?

**Comment by mysmlz** [comment]
It didn't seem to happen. I tested it several times and there was no problem.
v 0.9.98
