### ISSUE TITLE
Incorrect cursor when editing inline math chunk

### ISSUE THREAD

**Issue by VicaYang** [typora/typora-issues#2318]
![bug1](https://user-images.githubusercontent.com/22126501/54817576-43738c80-4cd2-11e9-8c73-17deec3e9920.gif)

**Comment by VicaYang** [comment]
Forget to mention, Version 0.9.68(beta) on windows

**Comment by VicaYang** [comment]
@abnerlee

**Comment by abnerlee** [comment]
If they are related or can be grouped, then group them, otherwise, one issue for one bug

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
