### ISSUE TITLE
In the Table Editing help, shortcuts are wrong

### ISSUE THREAD

**Issue by phillijw** [typora/typora-issues#2319]
It says Shift+Command/Ctrl+L will delete current table row but that is not true. It just toggles the visibility of the sidebar.

Can we just get shortcuts listed on the context menus themselves? Opening the help docs to remember how to delete a table row is not exactly a great experience. Not to mention the docs are wrong. I've probably wasted hours over the course of re-looking up these shortcuts over the time I've been using typora.

**Comment by doneykoo** [comment]
Agree. It is quite a struggle that I have to look for the website to show me the shortcuts.
There should be a quick and instant one to call features. Like in Sublime Text or VSCode we can use 'Ctrl + Shift + P'.

And, the latest help doc shows the shortcut as "Delete Row (in table)  Ctrl + Shift + Backspace".
However it does not work for me either. No response at all. 
(Typora version 0.9.72 beta, Windows 10)


> 
> 
> It says Shift+Command/Ctrl+L will delete current table row but that is not true. It just toggles the visibility of the sidebar.
> 
> Can we just get shortcuts listed on the context menus themselves? Opening the help docs to remember how to delete a table row is not exactly a great experience. Not to mention the docs are wrong. I've probably wasted hours over the course of re-looking up these shortcuts over the time I've been using typora.

**Comment by abnerlee** [comment]
Table operations are now available on menubar contains linked shortcuts, and you could set custom shortcuts
