### ISSUE TITLE
mermaid graph of typora 0.9.9.23 doesn't work

### ISSUE THREAD

**Issue by accc-y1** [typora/typora-issues#2320]
Typora 0.9.9.23 on Mac doesn't render mermaid graph (it just shows raw mermaid description).
It work again by downgrading to 0.9.9.22.

**Comment by abnerlee** [comment]
please enable diagrams feature in preferences panel

**Comment by tsuixh** [comment]
@accc-y1 I met the same issue on Windows 10, version 0.9.86 beta
