### ISSUE TITLE
Typora allows illegal file/folder name to be created

### ISSUE THREAD

**Issue by tylerlmz1** [typora/typora-issues#2321]
- Windows 10
- Newest typora version (0.9.68)

creating a folder named `$_.` is not allowed in Windows, 

when creating it in file explorer, Windows will omit the dot automatically, resulting in it being named `$_`

but creating it in Typora, somehow will make it go through, causing the folder to be named `$_.` , that can be seen in file explorer and powershell(doing `ls` in the path will return that folder in the list), but cannot be manipulated(can't delete, can't copy, etc)

**Comment by tylerlmz1** [comment]
When trying to delete the folder, Windows pops up such a prompt (I censored the file path is in image for privacy concerns)

<img width="343" alt="432423fdsa" src="https://user-images.githubusercontent.com/18716055/54864649-08865d00-4d95-11e9-8a6e-b26e8974d9e2.png">

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen

**Comment by tylerlmz1** [comment]
tried it just now, it is fixed! wow

thanks so much!
