### ISSUE TITLE
(re-)naming leads to `Rename Failed`

### ISSUE THREAD

**Issue by tzekid** [typora/typora-issues#2322]
When renaming (or sometimes simply naming a new file) I get the following `Rename Failed` error, where I have to hit OK two or three times before it doesn't show up anymore.

Example: I renamed a file from `society.md` to `projects.md`. `projects.md` did **not** exist in the folder prior to renaming the file. 
![image](https://user-images.githubusercontent.com/6037154/54868312-8b0a1f00-4d8b-11e9-8032-50f4b7d09689.png)

Some info:
> Installed Typora through the `typora` aur package.
Typora: version 0.9.68 (beta)
OS: Manjaro Linux x86_64
Kernel: 5.0.3-1-MANJARO
DE: Xfce

**Comment by abnerlee** [comment]
should be fixed in latest version.
