### ISSUE TITLE
0.9.68 (Beta) - Bug with disabling Paragraph/Quote feature

### ISSUE THREAD

**Issue by BonDradman** [typora/typora-issues#2328]
Marked a paragraph as a quote, and then exported to Word.  Upon reviewing in Word, noticed that the font was smaller but no other way to differentiate that this was a "quote".  

Given that it did not sufficiently look different, either in Typora or in Word, I tried to disable it but was unable to remove the tagging for a quotation.  

The only way I could have the paragraph revert to normal was to "cut" it and paste into Word.  From Word, it was copied back into Typora and this removed the tagging.  However, in the process lost my tagging for ordered lists.

Lastly - if the bug for disabling is fixed, then for the "quote" feature to be useful, it needs to be visually differentiated either with font or other style formats.  This should also be carried into any export to apps like Word to make it visible that the paragraph is visually different from a normal paragraph.

**Comment by abnerlee** [comment]
currently choose theme for exported docx file is not supported, this is a part of #1451
