### ISSUE TITLE
几个建议：1、增加账号登陆,同步笔记  2、或者可以登陆GitHub账号，同步在GitHub里   如果这样就大卖，就会有非常非常多的人用

### ISSUE THREAD

**Issue by ethanbing** [typora/typora-issues#2329]

**Comment by predominant** [comment]
This is suggesting that there be a github login to sync notes/documents with Github, and that if this is done, many people will be happy.

**Comment by JasonJunJun** [comment]
I think you can use gist to achieve what you want.

**Comment by abnerlee** [comment]
Typora is designed as an editor, we do not have those plans on the "Typora" app
