### ISSUE TITLE
Quote did not show appropriately.

### ISSUE THREAD

**Issue by GitZinc** [typora/typora-issues#2332]
![quote](https://user-images.githubusercontent.com/25785964/54982225-48dc1a00-4fe5-11e9-93a2-b53a390f958f.png)
![quote2](https://user-images.githubusercontent.com/25785964/54982231-4e396480-4fe5-11e9-93dd-27d7c6c31e16.png)

**Comment by GitZinc** [comment]
It did not become grey after I use ">" to quote a block of word.

**Comment by abnerlee** [comment]
For hot fix, please try switch themes

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
