### ISSUE TITLE
Unable to Tab in Latest Update in Code Block

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2337]
After installing the latest update (0.9.9.23.4 (2293)), I am unable to tab in a code block with the python language. I can tab, but it does absolutely nothing. This seems like a bug. I also just tested this in an empty code block with no language selected (plain text).

I am using macOS Mojave 10.14.2

**Comment by terrenceliu** [comment]
I'm having the same problem. I can't tab to indent inside code block. 

I'm using macOS High Sierra 10.13.6. Typora version: (Version 0.9.9.23.4 (2293))

**Comment by justnealpatel** [comment]
Has there been any update on this? @abnerlee

**Comment by abnerlee** [comment]
@justnealpatel Possible to give some example or more details? It works fine in my test

**Comment by justnealpatel** [comment]
I mean, I just opened up a new code block. I've attached a recording that shows me trying to tab in a code block. It seems like it's indenting, but it's not actually visually indenting meaning that, when I try to backspace, it deletes those tabs but doesn't show them. 
[TabBug.mov.zip](https://github.com/typora/typora-issues/files/3081960/TabBug.mov.zip)

**Comment by abnerlee** [comment]
I can see the bug from your video, but I stilled failed to reproduce it on my own.

Could you tell me which theme did you use? What's your keyboard layout, does Tab key works outside code block or in source code mode?

**Comment by justnealpatel** [comment]
I am using the Dropbox theme. Tabbing does work outside code blocks. But when I try to tab in source code mode, it does the same thing as the video, but when I go back into normal mode, the tabs show. So it doesn't work in source code mode or code blocks or math blocks.

**Comment by abnerlee** [comment]
@justnealpatel So how about the default Github theme?

**Comment by justnealpatel** [comment]
@abnerlee still the same issue persists.

**Comment by fuweichin** [comment]
+1 Not an option to indent with Tab in Code Blocks, Preferences.

To indent the code correctly, I have to copy the code to code editor, fix its indentation and then paste it back, what a pain!

Is it by design, or sort of compromise to drop Tab-indentation support in code blocks? let us know or fix it as soon as possible!

**Comment by abnerlee** [comment]
still happens in latest version?

relates #579

**Comment by kid21z** [comment]
![2023-06-06_00006](https://github.com/typora/typora-issues/assets/39520770/37cd3ed1-40da-447a-a661-f4f2bdf69e82)
我期望按下tab后得到是 四个空格而不是--->|
