### ISSUE TITLE
Code fences broken somewhere between version 0.9.65 and 0.9.68

### ISSUE THREAD

**Issue by raymondlaw** [typora/typora-issues#2338]
Was on the latest version and my code fences stopped working properly, no dark grey border around code (same for inline code fences)

Kept downgrading until I hit 0.9.65 which brought them back.

Running Typora for x64 on Windows 7.

**Comment by abnerlee** [comment]
same with #2309 ?

could you try https://github.com/typora/typora-issues/issues/2309#issuecomment-475528256
