### ISSUE TITLE
The Requirements for gobal proxy configuration 

### ISSUE THREAD

**Issue by shuzf** [typora/typora-issues#2339]
The requirements for global proxy configuration are very useful when downloading http/https resources.

**Comment by abnerlee** [comment]
We don't have plans for this ( as an editor ), but I think Typora will follow your system's overall network setting

**Comment by shuzf** [comment]
> We don't have plans for this ( as an editor ), but I think Typora will follow your system's overall network setting

When downloading resources from internet by network such as  png/jpeg/gif etc,because of some special access,which will be forbidden,so global network proxy configuration are useful in typora.
if so that, it will adapt to more scenes,woudn't that be better?

**Comment by abnerlee** [comment]
Yes, but Typora will follow your system's overall network setting, so providing self maintained proxy is in low priority.
