### ISSUE TITLE
exported PDFs don't render footnotes correctly

### ISSUE THREAD

**Issue by willwhitney** [typora/typora-issues#234]
If I have the following markdown:

```md
Here are a few examples from a GAN trained on 128x128 images from the ImageNet dataset[^improving_gans]:
```

it displays like this in Typora:

<img width="1067" alt="screen shot 2016-07-24 at 7 07 33 pm" src="https://cloud.githubusercontent.com/assets/597829/17087185/17fe1a96-51d2-11e6-8c63-1df8e14245d0.png">

but the exported PDF looks like this: 

<img width="637" alt="screen shot 2016-07-24 at 7 09 31 pm" src="https://cloud.githubusercontent.com/assets/597829/17087190/297fc9c2-51d2-11e6-99a1-097ad1a9979e.png">

**Comment by willwhitney** [comment]
Figured it out — apparently underscores break footnotes during export, but Typora renders the footnote as if it works.

**Comment by abnerlee** [comment]
fixed in new version
