### ISSUE TITLE
Proposal to add Mint install instructions

### ISSUE THREAD

**Issue by wiserweb** [typora/typora-issues#2340]
Just ran into an installation issue on Mint 19.1.

Somewhat cryptic error is given when using this command `sudo add-apt-repository 'deb https://typora.io/linux ./'` 

`error 'Malformed input, repository not added'`

Put that in search engine and got this link, https://github.com/typora/typora-issues/issues/2065

The method to install on Mint is to issue the following command to add the repo. The rest is the same.

`echo -e "\ndeb https://typora.io/linux ./" | sudo tee -a /etc/apt/sources.list`

This is all fine for people that can hack at it for a while but it would be really nice to have agnostic install instructions that work across all Debian-based distros or simply provide an alternative method for Mint in the beautiful official install instructions.

Thanks!

**Comment by ClocxHD** [comment]
I also ran into the same issue on Mint 19.1.

Thanks for the solution!

**Comment by abnerlee** [comment]
It's updated on http://support.typora.io/Typora-on-Linux/
