### ISSUE TITLE
how to have easy centering?

### ISSUE THREAD

**Issue by diomed** [typora/typora-issues#2341]
![Screenshot_28](https://user-images.githubusercontent.com/72777/55107593-fcbad380-50d1-11e9-9db8-5f62a9e62a5d.png)

like this above.
this is easy to achieve in Word just by hitting tab few times,
but currently impossible in Typora. Could there be done something
about it?
I really need this for songs, and poems.

**Comment by Freakwill** [comment]
create a customer css

**Comment by diomed** [comment]
@Freakwill care to show me how to do this? coz I tried but did not succeed

**Comment by abnerlee** [comment]
There's no "easy" ways to achieve this in markdown
