### ISSUE TITLE
link-use iframe src file content can not all displayed in pdf file

### ISSUE THREAD

**Issue by wxqanl** [typora/typora-issues#2343]
Typora 0.9.9.23 (0.9.66) beta

<iframe srrc='aaa.txt'   />

After Load aaa.txt, in  the TypeWritter Mode, the txt file content can view in strolling panel,
But Export to PDF, the file can not show up the content normally.

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
