### ISSUE TITLE
Pasting from Word does not preserve formatting

### ISSUE THREAD

**Issue by jonas-sk** [typora/typora-issues#2344]
This is especially obvious when one copies over lists from word. 
This

- Test
  - Test1
  - Test2
    - Test3
- Test4

is converted into the following when pasting:

·        Test

o   Test1

o   Test2

§  Test3

·        Test4

I believe this is partially Word's fault but I think it would be great if Typora could implement a workaround as Word is still the most popular word processor

**Comment by abnerlee** [comment]
On which OS? Does paste from Word to http://mikaelharsjo.github.io/content-editable/components/content-editable/demo.html able to keep the style?
