### ISSUE TITLE
Not properly synchronizing documents when using multiple windows

### ISSUE THREAD

**Issue by jonas-sk** [typora/typora-issues#2345]
Just now I almost lost 3 days worth of notes (luckily Google Drive didn't sync today yet, so I could recover the notes from yesterday and only lost today) because of some weird behavior by Typora: 

When I have document open, which I saved in this state state to the disk, and I load up the same document in a second window (to, e.g. compare something at the beginning with something at the end) it sometimes loads up a much older state of that document. When you now accidentally save (or autosave does that for you), you will lose your progress. I think in a recent update you tried to sync-up multiple views of the same document, so one doesn't have to reload the document to see new changes but it seems to have gone awry.

(In the above case, something also seems to have gone wrong with either the save or the autosave function as I am 100% sure I saved multiple times manually with the * behind the name having disappeared before and after the incident. Yet the date displayed on the file was one from yesterday but opening that file in Sublime Text it showed the state from three days ago.)

**Comment by jonas-sk** [comment]
It just happened again. i was mainly editing in the first window when I copied something in the second window and tried to delete a empty bullet point on the last line when suddenly almost everything was deleted with "undo" not working. When I closed the window, fearing it would synchronize, of course it was saved (thanks autosave). Luckily I could copy everything over to Sublime before the windows synced-up (though formatting is fucked). I turned off autosave, hoping this issue doesn't arise anymore

**Comment by jonas-sk** [comment]
Adding more info: At a later point I was suddenly unable to search in the document. When I wanted to restart Typora I noticed that the file was only 1KB and practically empty. Checking with Sublime Text and switching to Source Mode in my window showed an empty file (except two nested bullet points), despite the fact that Typora showed a whole document and indicated it was saved. Even copying it over and restarting Typora, then saving it, didn't help. I noticed that the mistake seemed to be somewhere in the first half as, suspecting it might be the length (6508 words), I split the document in two files and only the first half didn't save. I didn't find a solution to this problem and am currently looking at other editors (autosave was off btw)

**Comment by jonas-sk** [comment]
Windows. I am also not sure how this is an enhancement and not a bug? That behavior wasn't the case before, where the windows would simply stay unsynchronized. But now the two windows show some major issues synchronizing, leading to substantial data loss.

**Comment by abnerlee** [comment]
should be fixed in latest version, please reopen if it still exists
