### ISSUE TITLE
Feature request: auto outline numbering

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2346]
Numbering headers and subheaders greatly improves the readability and structure of a text. Currently one has to insert numbers manually to headers and subheaders. This becomes complicated and time-consuming when one inserts a new header between headers that have already been numbered.

Request: allow automatic numbering of headers and subheaders.

**Comment by abnerlee** [comment]
#1241

**Comment by DutchPete** [comment]
Many thanks @abnerlee 
Might be an idea to add to the features on the Typora home web site.
