### ISSUE TITLE
V0.9.68(beta)-Window the images added by <img src="./img/1.png"> aren’t shown in the PDF being exported

### ISSUE THREAD

**Issue by MaxChanger** [typora/typora-issues#2348]
I found that the way I used `<img src = "img/12.png" width='30%' />`, when I exported it to PDF, the picture didn't show up, but it worked int typora.

And then, if i used  `<img src = "C:\Users\***\Desktop\img\1.png" width='30%' />` or `![](./img/1.png)` , when I exported it to PDF, it can display normally.

How should I solve this problem?

![image](https://user-images.githubusercontent.com/35401968/55228116-4d5a3a00-5254-11e9-82d4-7527fd4aa87b.png)
![image](https://user-images.githubusercontent.com/35401968/55228130-56e3a200-5254-11e9-8209-633f7ba41018.png)
![image](https://user-images.githubusercontent.com/35401968/55228161-6cf16280-5254-11e9-90dc-2c38e6bd2f7b.png)

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
