### ISSUE TITLE
[BUG] Internal link with dots or dashes

### ISSUE THREAD

**Issue by dabro666** [typora/typora-issues#2349]
When using dots or dashes for header elements and set the internal link to those headers you can not jump to the target.
But in table of contents which has all the links to those headers, jumping works.

```markdown
## Chapter 1
## Chapter 1.1

[Chapter 1](#chapter-1)
[Chapter 1.1](#chapter-11)
```

**Comment by dabro666** [comment]
This is actual for Windows x64 release. Typora version 0.9.68.
Today I will check this behaviour in Mac version.

**Comment by dabro666** [comment]
Also the same bahaviour for ampersand or braces:
```markdown
## Chapter A & B
## Chapter (text A)

[Chapter A & B](#chapter-a-b)
[Chapter (text A)](#chapter-text-a)
```

**Comment by abnerlee** [comment]
should be fixed in latest version, please reopen if it still exists
