### ISSUE TITLE
Concerned about dataloss bug

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#2352]
**I don't know if this is a Typora bug, or user error on my part.** But it really feels like a bug, and it could be related to #2345. If it is a bug it is serious, so I feel compelled to report it even though I'm not sure. 

I opened I file I created and worked on yesterday, and it was empty except for a blank H1. Source looked like this:

```
# 
```

Where was all the content?!?! I went to the file in the finder. Its size was 1k. So I used the Finder to duplicate it:

![Screen Shot 2019-03-31 at 1 34 59 PM](https://user-images.githubusercontent.com/2830093/55292825-40a52580-53bd-11e9-9d9c-703c9ded41df.png)

When I opened the copy, all the content was there! 

I went back to the original, closed and reopened it, and still it was empty. I saw that `Edit : Undo` was not grayed out, so I tried it. Some content came back, but only a third. I did some more undo, and the content progressively disappeared until it was empty. Redo would bring it back to the one third point.

Finally I tried `Revert to... : Last Opened` and the contents came back, identically to the copy. It's clear that Typora isn't showing what's in the file, but "unsaved" document state. 

I did some tests and the ONLY way I could have done this accidentally is one of the following:
1. Highlight the entire doc and accidentally pressed `#`.
2. Put the cursor at the very end of the doc, or accidentally hold down the delete until everything is deleted, but let go of the delete right before it deletes the `#`.
3. Have a `#` at the end of the doc, have the cursor just *before* the `#`, and accidentally hold down the delete key until everything before it is deleted

...*AND THEN* close the doc without noticing that I'm closing a doc with all its content gone.

None of those seem likely, gut it is possible, I guess. But then I chose `Revert too... : Browse all versions...` to see if the version history has any clues, it showed the last version as blank and dates it 1:36pm (which is when I opened it about 30 minutes ago), and the version before that is timestamped 2:16am (corresponding to the timestamp Finder shows above) with *all* the content. There are no intermediate versions. 

It appears to me that Typora did something buggy on document open. I hope I am wrong because this makes me worry that I've lost work that I've done in other documents and I won't even know.  

I captured Typora logging of opening both the original and copy of the file before I used `Revert to... : Last Opened`. I don't think there's anything useful in there, but I can send it to you if you want it.

**Comment by abnerlee** [comment]
@vassudanagunta Thanks for the detail, please send us (hi@typora) the log if possible. We will handle soon it since it seems serious. 

Also, what's your settings in following red rect?
<img width="780" alt="Screen Shot 2019-04-03 at 21 59 03" src="https://user-images.githubusercontent.com/1621242/55484902-f097be80-565b-11e9-9fe1-7e66372862f9.png">

**Comment by vassudanagunta** [comment]
@abnerlee 

Logs sent. 

![Screen Shot 2019-04-03 at 11 35 30 AM](https://user-images.githubusercontent.com/2830093/55492072-97e90700-5604-11e9-9a27-8f219fd08a06.png)

I thought about this problem a little more. Before I wasn't sure it was a bug, but now I'm more sure it is: What Typora shows should always be synced with what's in the file system. The Markdown files *do not belong* to Typora, and users will Typically open them in other tools, not just Typora.

**Comment by vassudanagunta** [comment]
@abnerlee 

I thought about this problem a little more. Before I wasn't sure it was a bug, but now I'm more sure it is.

Can you confirm that this should be Typora's behavior:
-  When the "Ask to keep changes" is *not checked*, Typora will autosave directly to the file. Thus the file should look the same as it looks in Typora to any other software opening the file.
- When the "Ask to keep changes" is *checked*, Typora autosaves the edited version to it's own temporary space, and only writes to the original file when the file is explicitly saved or when the file is closed and the user chooses to keep changes.

Is that correct?

**Comment by jonas-sk** [comment]
I experienced the same problem, along with some synchronization bugs between multiple windows (see #2345). My settings look like this: 

![grafik](https://user-images.githubusercontent.com/7535016/55553673-20d57080-56e1-11e9-8a8a-d844eb883417.png)

(I unticked "autosave" after it started appearing and now also unticked the second box)

**Comment by abnerlee** [comment]
@vassudanagunta 

They both will "autosave directly to the file", but when the "Ask to keep changes" is checked, user can discard this changes (revert the file to last open or explicitly saved status) on the save dialog.

**Comment by vassudanagunta** [comment]
@abnerlee 

So no matter the settings, autosave always happens and other apps will immediately see the autosaved changes?

In that case, what I experiences was most definitely a bug.

**Comment by abnerlee** [comment]
> So no matter the settings, autosave always happens and other apps will immediately see the autosaved changes?

The auto save has a timmer, or happens on window blur (the timing is controlled by the system), so maybe not *immediately*, but should be close. But dataloss should be a bug anyway.

**Comment by abnerlee** [comment]
put to #3107 since this thread is too old
