### ISSUE TITLE
Links to local files in OSX don't open properly

### ISSUE THREAD

**Issue by mrdanbrooks** [typora/typora-issues#2355]
I have had no trouble opening links to local files (in OSX) until the latest Typora update (0.9.9.23.4).

Previously, right clicking and selecting "open link" on a link such as 

```
[notes](/Users/myusername/Documents/notes.md) 
```

would cause a new Typora window to open with the appropriate file. Or if the link was to a PDF, it would open in preview, etc... This is what I would call the expected behavior.

In the latest version (running OSX Sierra 10.12.6), the clicking open link always trys to open in the browser. This works fine for website links, but for local files, ``typora-app`` gets prefixed to the link text (e.g. ``typora-app/Users/myusername/Documents/notes.md``) and that is what shows up in the browser URL bar. 

It is worth noting that I have found a workaround. By adding ``file://`` to the beginning of local file paths, the expected behavior I described above returns. For example

```
[notes](file:///Users/myusername/Documents/notes.md) 
```

opens a new Typora window with the appropriate file, and applying the same technique to the path of a pdf document causes things to open in preview again. 

I would simply not expect to have to add ``file://`` to the beginning of local files in order for them to open correctly.

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
