### ISSUE TITLE
[feature] Adding musical ABC notation

### ISSUE THREAD

**Issue by frankois** [typora/typora-issues#2356]
I was wondering if there was any plan to support ABC notation in Typora? This is used to display musical sheets which look like the following :

```abc
X:1
T:Speed the Plough
M:4/4
C:Trad.
K:G
|:GABc dedB|dedB dedB|c2ec B2dB|c2A2 A2BA|
GABc dedB|dedB dedB|c2ec B2dB|A2F2 G4:|
|:g2gf gdBd|g2f2 e2d2|c2ec B2dB|c2A2 A2df|
g2gf g2Bd|g2f2 e2d2|c2ec B2dB|A2F2 G4:|
```

![Screenshot 2019-04-01 17 23 52](https://user-images.githubusercontent.com/4917492/55344830-b937df00-54ae-11e9-8508-7bc05d1f1d81.png)

As an example, it is already supported by HackMD :
https://hackmd.io/features?abc#Abc

More information about this format :
http://abcnotation.com/learn

**Comment by abnerlee** [comment]
#1138

**Comment by JamesChenX** [comment]
I have developed a "plugin" for this feature and it works fine most time

Env: Typora:0.9.93，windows10, abcjs-v6.0.0-beta.14

Snapshot:
![image](https://user-images.githubusercontent.com/44962329/90302060-3ca47580-ded6-11ea-9c44-12dea63e379a.png)

Steps:
1. download https://github.com/paulrosen/abcjs/blob/master/dist/abcjs-basic.js
2. Move "abcjs-basic.js" to the dir "resources\app\app\window" of Typora (e.g. C:\Program Files\Typora\resources\app\app\window)
3. download and unzip the "[abc.zip](https://github.com/typora/typora-issues/files/5077967/abc.zip)". And move the file "abc.js" to the same folder.
![image](https://user-images.githubusercontent.com/44962329/90302193-17643700-ded7-11ea-8277-3db8de0c1637.png)
4. Open C:\Program Files\Typora\resources\app\window.html in any text editor.
5. Replace the last line
`}</script><script src="./lib.asar/pdf/pdf-designer.min.js" defer="defer" async></script><script src="./lib.asar/pdf/pdf.min.js" defer="defer" async></body></html>`
by
`}</script><script src="./lib.asar/pdf/pdf-designer.min.js" defer="defer" async></script><script src="./lib.asar/pdf/pdf.min.js" defer="defer" async></script><script src="./app/window/abcjs-basic.js"></script><script src="./app/window/abc.js"></script></body></html>`
6. Open Typora. Done.
