### ISSUE TITLE
Maximize, minimize and close the button display is not normal

### ISSUE THREAD

**Issue by malimingwq** [typora/typora-issues#2359]
Maximize, minimize and close the button display is not normal，Menu bar disappears
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190402162913968.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21hbGltaW5nd3E=,size_16,color_FFFFFF,t_70)
conf: window10 x64 Home, typora 0.9.68 (beta)
@abnerlee

**Comment by abnerlee** [comment]
Cannot reproduce this one, any more details?

**Comment by abnerlee** [comment]
They are hidden in fullscreen mode, hover on title will show them
