### ISSUE TITLE
code block seems not to work well

### ISSUE THREAD

**Issue by guanxudong** [typora/typora-issues#236]
this is a paragraph.

    this is a pre.

this a paragraph too.

The code above can not work well.
Typora: 0.9.9.6
OS:  OS X 10.11.6

**Comment by abnerlee** [comment]
Code block with tab or 4 whitespace indentation currently only works when opening existing markdown file or pasted markdown source code.

When writing in Typora's hybrid editing view, "```" is used to create code fences
