### ISSUE TITLE
Can't remove blockquotes from unwanted areas

### ISSUE THREAD

**Issue by mcoromac** [typora/typora-issues#2360]
Hello, 
When I create a blockquote, type, and do a line break Typora automatically inserts a > in front of every line that follows, thus I need to either erase the whole block and do it all over again or copy and paste the text on a Notepad remove all the unwanted > and paste it again on Typora. 

Is there a solution to this? 

I'm using Typora 0.9.68 Beta on Windows 10

**Comment by abnerlee** [comment]
We currently don't provide options to omit ">" for blockquotes.

May be a part of #1433
