### ISSUE TITLE
copy and paste in code block

### ISSUE THREAD

**Issue by Mshuyan** [typora/typora-issues#2361]
i want to copy a word in code block,like this
![image](https://user-images.githubusercontent.com/38898915/55468246-8c620400-5635-11e9-8a81-960a38480709.png)
but i get this 
![image](https://user-images.githubusercontent.com/38898915/55468333-c0d5c000-5635-11e9-8bd4-897faf489931.png)
i just want to copy one word,but copied the content  from the selected word to the end of the file. how to solve it

**Comment by whysakura** [comment]
so am i

**Comment by Mshuyan** [comment]
Version 0.9.9.24 solved this problem,thank the author
