### ISSUE TITLE
the problem of picture loading

### ISSUE THREAD

**Issue by guqinglei123** [typora/typora-issues#2362]

**Comment by guqinglei123** [comment]
when i use OmniMarkupPreviewer that is the plug-in module of sublime  to previewer  a markdown file . i can see the picture. 
![image](https://user-images.githubusercontent.com/25784213/55534872-0fdc2d80-56e8-11e9-8df5-0f525e509adb.png)

but when i open this file by Typora. this picture don't load.the web of picture is
https://www.evernote.com/shard/s542/res/5465ec1c-ee31-4aed-952b-5ba767bc20e4/ScreenClip.png. I don't know this reason.
![image](https://user-images.githubusercontent.com/25784213/55534915-2a160b80-56e8-11e9-8f81-5f49c95c090c.png)

**Comment by abnerlee** [comment]
Typora cannot access https://www.evernote.com/shard/s542/res/5465ec1c-ee31-4aed-952b-5ba767bc20e4/ScreenClip.png

The url may requires login, but Typora shouldn't access your browser's cookie for security reason.
