### ISSUE TITLE
Improve Application Frame For Windows

### ISSUE THREAD

**Issue by J-Cake** [typora/typora-issues#2363]
I see that the window button icons have been custom made for the windows version, but this is not necessary. Windows has a preset icon font that contains basic icons used throughout windows. It's called `Segoe MDL2 Assets` and the characters are `` (Minimise, E921), `` (Maximise, E922), `` (Restore, E923) and `` (Close, E8BB)

Please excuse me if the characters are in incorrect order, but on windows, consider using these instead of the icons currently in use. 

For an optimal font size, I would suggest `10px` and each button's standard width is `46px`, Height is `32px`. Colours for hover are:

* minimise, maximise, restore: `rgba(255,255,255,0.2)`
* close: `#E81123`

**Comment by abnerlee** [comment]
It's a good information but it only supports Window 10, which brings more work for windows 7/8
