### ISSUE TITLE
Opening Recent Folder on Mac OSX opens 2 windows

### ISSUE THREAD

**Issue by phosphotungstic** [typora/typora-issues#2364]
Whenever I go to File -> Open Recent -> <foldername> from just one Typora window, 2 identical windows get open. Not a huge deal but kind of annoying closing one every time.

**Comment by abnerlee** [comment]
I failed to reproduce this one. What's your Typora version and any details / preconditions to reproduce this?

**Comment by Matt-Interneuron** [comment]
I am also seeing this.

I am running macOS Mojave 10.14.4 and I've just upgraded to Typora Version 0.9.9.24.6 (2400). The previous two versions had this issue also, although I am not sure what build they were.

How I can reproduce it:

1. Launch Typora
2. Goto File > Open Recent > Select recently used folder

As per the original issue, Typora opens the folder structure in the existing window and a new window.

**Comment by seamusdemora** [comment]
I don't see that behavior on my Mac (10.14.4), Typora Version 0.9.9.24.2 (2386)

When I start Typora, all the previous files that were open in tabs are re-opened. If I do `File, Open, Recent...` I get one new window with a single tab with the selected file.

**Comment by seamusdemora** [comment]
Just upgraded Typora to Version 0.9.9.24.6 (2400), repeated above, same result (only one window).
