### ISSUE TITLE
Math blocks not rendering in any case

### ISSUE THREAD

**Issue by oscardp96** [typora/typora-issues#2365]
Since the last update, math blocks are not rendering at all, and inline math only renders when exported to PDF. I can't find a way to make it work again. I am on MacOS Mojave, using version 0.9.9.23.4.

**Comment by abnerlee** [comment]
Could you send us (<hi@typora.io>) one sample file?

**Comment by oscardp96** [comment]
Sorry, I don't know what happened, but now it is working properly, without any update or anything like that. Excuse me for the trouble

**Comment by abnerlee** [comment]
#2399
