### ISSUE TITLE
Auto-detect/linking of emails doesn't work for international TLDs

### ISSUE THREAD

**Issue by sendotsh** [typora/typora-issues#2366]
I noticed emails with subdomains has been fixed (#1829) but if the domain ends in anything other than .com/.net/.org it still doesn't work.

Eg .com.au, .co.uk, .jp, etc.

![typoraemails](https://user-images.githubusercontent.com/46561474/55613602-db936a80-57d6-11e9-8746-2ee681333bb9.png)

**Comment by abnerlee** [comment]
Please use `mailto:` for email address, or use auto link `<hello@example.jp>`.
We want to exclude files name like icon@2x.jpg, and since the "auto" convert cannot be cancelled, we feel OK to apply a more strict rule

**Comment by abnerlee** [comment]
should be fixed in latest version
