### ISSUE TITLE
Menu items in different font size

### ISSUE THREAD

**Issue by foxnadir** [typora/typora-issues#2368]
Menus have different item font sizes. Can you please make them the same size?

**Comment by abnerlee** [comment]
Which menu? What OS?

**Comment by foxnadir** [comment]
![Font](https://user-images.githubusercontent.com/37429534/55799480-51f3dd80-5af3-11e9-8830-1b7028db3f5b.png)
Windows 10 OS.
This Menu Window has 7 (Wow!) different fonts in it. Why?
Look at some design books or smth...

Make them less different: No need to use such more

**Comment by abnerlee** [comment]
Only left panel part is "Menu"

**Comment by foxnadir** [comment]
> Only left panel part is "Menu"

So what? Maybe you think so, but the problem with fonts still here

**Comment by abnerlee** [comment]
We plan to not  change this

**Comment by foxnadir** [comment]
Excellent! This is how you react to a criticism
