### ISSUE TITLE
Diagrams don't seem to work (for me)

### ISSUE THREAD

**Issue by zinoff** [typora/typora-issues#2369]
When pasting the sample from the website and exporting (PDF, HTML), nothing happens, other than exporting the text of the sample. I am running Version 0.9.9.23.4 (2293) on Mojave 10.14.4 (18E226) - Pandoc is installed.

​```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
​```

**Comment by abnerlee** [comment]
should be enabled in preferences panel first

**Comment by AlexPasternak** [comment]
Just to note, a lot of issues get resolved as "enable in Preferences first". Have you thought of detecting & prompting the user to remind them if they want to turn on a feature? I also don't know why not have all this stuff enabled in the first place, it's not the very specific syntax of diagramming is going to conflict with something else by default.

**Comment by zinoff** [comment]
The preference was enabled and it didn't work (and it still doesn't work). Could it be something else?
