### ISSUE TITLE
Down arrow indicator in file title overlaps file name

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#237]
Regardless of window size or document chosen, the down arrow symbol that allows fast rename of a file or to add tags to it, is badly placed. Compare below with Preview, where the arrow is correctly padded away from the file title.

<img width="519" alt="title" src="https://cloud.githubusercontent.com/assets/1819485/17108448/92f36ce4-5261-11e6-908d-bb64fa8d7735.png">

In other cases, a black line seems to go through the document title.

<img width="519" alt="title2" src="https://cloud.githubusercontent.com/assets/1819485/17108528/f971bb38-5261-11e6-9e40-e0f8bd34667c.png">

**Comment by vassudanagunta** [comment]
On my system the down arrow is padded exactly the same as it is on Apple's TextEdit.

**Comment by abnerlee** [comment]
@AlexPasternak, Currently the seamless window for dark theme is not fully supported (which is written in preference panel on the `?` icon).

**Comment by AlexPasternak** [comment]
I've seen that comment before, but now understand what that means, thanks (wish Prefs would explain what "seamless mode" actually is, not a common macOS term for me).

**Comment by abnerlee** [comment]
Should be fixed already
