### ISSUE TITLE
How to backstick backstick ending code?

### ISSUE THREAD

**Issue by xp44mm** [typora/typora-issues#2370]
hello! the $` represent a regex replacement. how to backstick it? 

`$``

``$```

`$\``

``$` ``

**Comment by abnerlee** [comment]
```
`` $` ``
<code>$`</code>
```

Is it not well supported in Markdown, use `<code>` would be recommended for this case

**Comment by xp44mm** [comment]
```markdown
* <code>$`</code>
  Substitutes the portion of the source string up to the match.

* `$'`
  Substitutes the portion of the source string that follows the match.
```
i test:
![x](https://user-images.githubusercontent.com/10087796/55765029-6e1a5f00-5aa0-11e9-851d-b9cc20fba485.GIF)
