### ISSUE TITLE
Enhancement: Add Font Color Hot Key

### ISSUE THREAD

**Issue by binbibi** [typora/typora-issues#2371]
now in typora, if I want change font color,i must type \<font color = red\> test \</font\>,can you add a hot key,it auto type \<font color = \>  \</font\>, and i just type color and text,that will be more convenient, thx

**Comment by abnerlee** [comment]
use things like TextExpander or https://www.techradar.com/how-to/computing/apple/how-to-use-text-shortcuts-on-mac-1308652 for this case.
