### ISSUE TITLE
F# String Literals highlight error

### ISSUE THREAD

**Issue by xp44mm** [typora/typora-issues#2372]
the different forms for writing F# string literals:
```F#
let norm = "Humpty Dumpty"
let path = "c:\\Program \"Files"
let verbatim = @"\""i'm sorry"
let triple = """I "like" you"""
```
the varbatim string literal and the triple quote string literal highlight error!

**Comment by abnerlee** [comment]
https://github.com/codemirror/CodeMirror/issues/5851
