### ISSUE TITLE
A few typos in DO NOT ADD FILES HERE.md

### ISSUE THREAD

**Issue by SillySam** [typora/typora-issues#2377]
The file located in the root directory `DO NOT ADD FILES HERE.md` contains a few simple typos.

- The text inside is: _This folder will be replace / removed during update / **unisntall**. Do not write **yourr** files here._

- It should be: _This folder will be replaced and/or removed during an update or uninstall. Do not write your files here._

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
