### ISSUE TITLE
TOC display error when searching for word exist in TOC (Bug)

### ISSUE THREAD

**Issue by Williams-Ren** [typora/typora-issues#2378]
![image](https://user-images.githubusercontent.com/45218090/55692587-24684080-59dc-11e9-87b3-1fd9f34ff76b.png)
![image](https://user-images.githubusercontent.com/45218090/55692591-2d591200-59dc-11e9-8a5e-9c92aab5f93d.png)
![image](https://user-images.githubusercontent.com/45218090/55692602-3ea21e80-59dc-11e9-9a41-f4256a2308f8.png)
The TOC seems have some error when I searched for some words exist in TOC

**Comment by abnerlee** [comment]
I  cannot understand this issue, what's the expect behavior?

**Comment by Williams-Ren** [comment]
@abnerlee In the third picture, it displays the TOC correctly, But as what can you see in the first two pictures, Hy, dr, o, l, ogic are spread into different lines. This bug will appear when I used cytl+f to search hydrologic.

**Comment by abnerlee** [comment]
should be fixed in new release, search will skip [TOC] as it is generated content, and is unable to replace

**Comment by Williams-Ren** [comment]
thanks
