### ISSUE TITLE
support img tag attribute

### ISSUE THREAD

**Issue by itviewer** [typora/typora-issues#2379]
just like github
`<img src="https://cdn.rawgit.com/msoeken/alice/master/alice.svg" width="64" height="64" align="left" style="margin-right: 12pt" />`

should like this 
<img src="https://cdn.rawgit.com/msoeken/alice/master/alice.svg" width="64" height="64" align="left" style="margin-right: 12pt" />

**Comment by JieJiSS** [comment]
Like this?
![image](https://user-images.githubusercontent.com/24671280/56075312-ea8ba580-5df2-11e9-924b-14f981383170.png)

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
