### ISSUE TITLE
TAB Character in Nested List Not Displayed in Source Code Mode when Indent Size on Save is Set to Tab

### ISSUE THREAD

**Issue by g4x86** [typora/typora-issues#2380]
First according to the original specification of Markdown syntax by Daring Fireball, Tab is a legitimate character for indenting nested lists, equivalent to 4 space characters.

Now try the following steps to recreate the bug:

1) Go to the Editor tab of the Preferences dialog and set the option of Indent Size on Save to Tab.

2) Create a new Markdown file and type in any nested lists by using the menu: Paragraph -> List Indentation -> Indent / Outdent.

3) Select the Source Code Mode in View menu and move the cursor to any nested lines, and all leading Tab characters can be displayed correctly.

4) Now save the new Markdown document, close Typora program, and launch it again.

5) Open the Markdown document just created and select the Source Code Mode from the View menu. Now, when cursor is moved to the nested lines, all leading Tab characters are NOT displayed, though they are actually still there (tested by using arrow keys to move cursor but the cursor doesn't change its position until the arrow key are hit by the number of Tab characters).

This bug can be reproduced reliably in the latest Typora version 0.9.9.23.4 (2293) with the Github theme on macOS Mojave 10.14.4.

Note: when the option of Indent Size on Save is set to any other values, e.g. Auto, 1 space, 2 spaces, 4 spaces, 8 spaces, the leading Tab characters can always be displayed correctly in nested lists when viewed in Source Code Mode.

This bug seems not present on the latest Linux version of Typora (0.9.68 beta) in RHEL 7.6. However the Linux version has its own bug regarding using Tab in nested list:

Even with the option of Indent Size on Save is set to Tab, Typora will replace some Tab characters in nested list to space characters n an existing Markdown document that uses Tab as the leading characters in nested lists. This seems to be a program bug definitely.

Many other popular Markdown software use Tab as the default character for nested list. Hope this bug can be fixed soon, so that users can use Tab in nested list and produce more compatible Markdown documents.

Many thanks!
Granville

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen

**Comment by g4x86** [comment]
I've just upgraded Typora for Mac to the latest 9.9.24.6 and found this bug is still there. I also found that, by setting the option of Indent Size on Save in Editor preference to anything other than Tab, the Tab character can be displayed in Source Code Mode. If set to Tab, all Tab characters are invisible. This is also true when using different themes. So this bug seems kind of hard to get ride of.

**Comment by coffee-and-genomics** [comment]
Still having this issue.

**Comment by squidmark** [comment]
+1

**Comment by abnerlee** [comment]
Close as I cannot see this bug in latest version now.
