### ISSUE TITLE
file navigator and open folder has weird response

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2381]
Sometimes when i rename a file say  1.md , it did renamed it to 2.md, but also show error message like :  could not find 1.md

and when i move a file to another folder, also not stable

byw, what are you going to do with so many opened issues, what's the plan next? giving the long resistance to opensource i highly worried about the prospect of such a wonderful product.

**Comment by abnerlee** [comment]
relates #2322

should be fixed in latest version
