### ISSUE TITLE
Incremental search leaves visual clutter inside code ranges.

### ISSUE THREAD

**Issue by lrhn** [typora/typora-issues#2382]
If my text contains code like `` `thing.stuff()` `` and I do a search (ctrl-f) for `thing`, writing each letter individually and letting the display update between keypresses, then it leaves visual clutter where the letters `i` `n` and `g` look like individual adjacent code blocks with their own padding and border. Removing a letter and writing it again will add more empty blocks wrapping the letter.

This only appears to affects the *first* word of a the code, there is no effect searching for `stuff` in the above case.

I have not noticed this effect before updating to 0.9.68 on Windows.

The code is unchanged, it's only the rendering which shows artifacts of the search highlighting. Switching to source and back (ctrl-/) does not fix it.
Any edit done in the code block will remove the visual error. A select-all, ctrl-\, ctrl-u will reformat everything.

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen
