### ISSUE TITLE
decrease whitespace between list items and increase white space between paragraphs?

### ISSUE THREAD

**Issue by imthenachoman** [typora/typora-issues#2384]
How can I:

- decrease the amount of white space between list items
- increase the amount of white space between paragraphs

**Comment by abnerlee** [comment]
It's a style preference.

http://support.typora.io/Add-Custom-CSS/

**Comment by imthenachoman** [comment]
Is there any reference documentation for CSS selectors to use to achieve various goals? Debugging CSS for such a complex code can have un-desirable results -- some that are not immediately apparent.

**Comment by abnerlee** [comment]
You could use http://support.typora.io/Add-Custom-CSS/#debug-css which helps you inspect elements

**Comment by imthenachoman** [comment]
Understood. Thank you. I will look through it. Debugging someone else's CSS code can be difficult and result in un-desirable results. Just an idea but it might be helpful if the documentation had the selectors to use for common UI elements like paragraphs, list item lines, code blocks, the list outline items on the left outline, etc... Just an idea to make it easier for users.

**Comment by abnerlee** [comment]
here's common selector: http://theme.typora.io/doc/Write-Custom-Theme/

**Comment by imthenachoman** [comment]
@abnerlee That is very helpful. Thank you so much!
