### ISSUE TITLE
Export as HTML not working when inserting script tag

### ISSUE THREAD

**Issue by victorponz** [typora/typora-issues#2385]
Hi.
On version 0.9.68 (Ubuntu 17), when I insert a script tag (for instance, embedding a gist) the Export to HTML option does not work.

The same occurs if you insert a video tag with opening and closing tags, so I suppose that the problem is in the closing tag, because if you remove it you can export as HTML.

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen

**Comment by victorponz** [comment]
In version 0.9.70 works. Thanks
