### ISSUE TITLE
Diagrams - suggested update to documentation

### ISSUE THREAD

**Issue by zinoff** [typora/typora-issues#2387]
The Diagram functionality documentation at http://support.typora.io/Draw-Diagrams-With-Markdown/  is partially wrong and partially incomplete. 

In order for the diagram to render you need to change the language from the default **gfm** to the one of the diagrams, respectively **flow, sequence** and **mermaid**. This is written nowhere in the documentation.

The mermaid examples will not render as ''' and %% are not supported.

**Comment by abnerlee** [comment]
flow, sequence and mermaid is written in the doc, search "```flow", etc

and see https://github.com/knsv/mermaid/issues/47#issuecomment-430809892
