### ISSUE TITLE
Table of Content using {:toc}?

### ISSUE THREAD

**Issue by FSXAC** [typora/typora-issues#2389]
I noticed that using all three of the following Markdown resolves correctly to a table of contents in Typora (0.9.68).

```gfm
[toc]
```

```gfm
- toc
{:toc}
```

```gfm
{:toc}
```

The latter two resembles Kramdown. So are there other instances of these `{: ... }` in Typora? It seems like there isn't any documentation on this as well.

**Comment by abnerlee** [comment]
#1202
