### ISSUE TITLE
Rotating backwards through windows (with command-tilde / command-shift-back-tick) doesn't work

### ISSUE THREAD

**Issue by andyfleming** [typora/typora-issues#2390]
<kbd>command</kbd> + <kbd>\`</kbd> rotates through file windows in a forward direction, but <kbd>command</kbd> + <kbd>~</kbd> / <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>\`</kbd> does not rotate through windows in a backwards direction like most applications do.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by andyfleming** [comment]
Perfect, thanks!
