### ISSUE TITLE
Git-friendly theme structure

### ISSUE THREAD

**Issue by andyfleming** [typora/typora-issues#2393]
Right now themes are structured as a CSS file that can optionally have other directories or files it references, but it would be nice for each theme to live in its own directory in the themes folder.

The reason why that would be better is so that themes could be directly cloned directly into the themes directory.

Before:
```
github/400.woff
github/400i.woff
github.css
```

After:
```
github/400.woff
github/400i.woff
github/github.css
```

------

Specifically, for my personal use case, I am developing a theme and I want to be able to commit my changes and pull those changes on a second computer without having to move around files every time.

**Comment by abnerlee** [comment]
In most case a theme is just a CSS file, like this `/github.css`, having other assets such as font, images will not be the common case.

For quicker debug/develop purpose, you could use "@import" in the root *.css file

**Comment by andyfleming** [comment]
That's fair and I did think of that work around.

I only mentioned this alternative structure since it didn't seem like there was a disadvantage other than the work to implement it.

Also, anecdotal, but, most of the themes I've download came with additional files.
