### ISSUE TITLE
Command line option for opening file at end

### ISSUE THREAD

**Issue by kevinvanderpol** [typora/typora-issues#2394]
I am using Typora for manual log files, which are typically appended to rather than read top-to-bottom. Some command line switch which opens the file and scrolls down to the end of the file would be convenient and "feel smooth" for these workflows.

Think of manual log files where people have to append to the log and some script that opens an editor so they can append to the log. It would be nice to have the script call "typora --scroll=bottom myfile.md" or similar so people can quickly append and continue the script.

**Comment by abnerlee** [comment]
merge into #1999
