### ISSUE TITLE
Can't change hotkey "Save As..."

### ISSUE THREAD

**Issue by Andersonfeng** [typora/typora-issues#2395]
The setting in my configure is as follows
I want to cancel the "Save As..." hotkey
``` 
"keyBinding": {
    // for example: 
    // "Always on Top": "Ctrl+Shift+P"    
    "Save As": "",
    "Save As.": "",
    "Save As..": "",
    "Save As...": "",
    "Save As*": ""    
  },
```
But the "Save As..." hotkey is still "Ctrl+Shift+S"
![image](https://user-images.githubusercontent.com/13361365/56022968-6cba9200-5d3f-11e9-9cd9-9829e9b643b0.png)

Do I configure wrong?

**Comment by abnerlee** [comment]
Cancel shortcut key is not supported yet

**Comment by Andersonfeng** [comment]
> Cancel shortcut key is not supported yet

But I try cancel other shortcut key successfully...
Even if not supported cancel it , how I change the "Save As" hotkey ?

**Comment by Andersonfeng** [comment]
> "Save As…"
Thanks for reply.
With your help I've already cancel the shortcut key.
As you see, my config "Save As..." is not the same with "Save As…" lol
![image](https://user-images.githubusercontent.com/13361365/56142002-7d356b80-5fd0-11e9-80dc-87865d61c47e.png)
