### ISSUE TITLE
 custom-ordering of the 'files/notes': just to make sure, is there really no way for a custom-ordering of the 'files/notes' on the left?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [typora/typora-issues#2398]
- cant drag drop the files/notes to the relevant/helpful place/order for example

if not this is incredibly limiting,

and then can only have very few files/notes in this software

**Comment by abnerlee** [comment]
#1680

**Comment by aboode95** [comment]
I don't think custom order of files and reverse sort (as stated in #1680) are the same thing.

Lets say, I have A, B, C files and want to drag B before A so that the files look like B,A,C. I don't see any options to do this.
