### ISSUE TITLE
Crash when writing html image tag in Preview mode

### ISSUE THREAD

**Issue by cschmatzler** [typora/typora-issues#240]
## Description
When using an HTML image tag instead of the Markdown image syntax (to, for example, add style or change dimensions), Typora crashes.
## Expected Behavior
Writing HTML in non-Source Code Mode should not crash the program.
## Actual Behavior
Typora crashes
## Steps to reproduce
1. Open a new markdown file
2. Write an image tag like `<img src="images/test.png" width="200px" />`  

Typora crashes when opening the quote after `width=`

## Environment
- Windows 7 SP1
- Typora 0.9.14

**Comment by abnerlee** [comment]
Hi:

I have difficulty to reproduce this one. So I want to confirm something.

1. If you copy and paste `<img src="images/test.png" width="200px" />`, will typora crash.
2. Do you enable/disable the auto complete for pared `"`.
3. What's your keyboard layout (is it US English) and did you use any IME?

**Comment by abnerlee** [comment]
Fixed in new version
