### ISSUE TITLE
Possible "Auto math numbering" performance issue

### ISSUE THREAD

**Issue by ivan-silva** [typora/typora-issues#2400]
Good morning,

while editing a file of ~1600 lines, very rich in math formulas creation of a new math block takes about 7 seconds. 
Without _auto math numbering_ is pretty instantaneous.

I suggest a possible performance bug in that algorithm.

Kind regards,
Ivan

**Comment by abnerlee** [comment]
We use `MathJax` for math rendering, which is slow, auto-numbering takes more time based on its logic.

Merge into #68
