### ISSUE TITLE
Feature request: multi-line code block and linebreak support in table cells

### ISSUE THREAD

**Issue by AlienKevin** [typora/typora-issues#2402]
Currently, Typora can only support inline code and single line text. So when I paste in large chunks of code, for example, their formatting and syntax highlighting are all lost. In addition, every time I hit <kbd>enter</kbd> to try to insert a newline in the cell, it skips to the next row. For now, I have to hit <kbd>space</kbd> many times in order to format the content of a cell. I would like Typora to add in **multi-line code fence and multi-line text support** so that tables can be more organized and appealing.

Here's a screenshot of the problem I encountered. The code block is especially messy without proper linebreaks and syntax highlighting.

![image](https://user-images.githubusercontent.com/22850071/56092003-89acad80-5e84-11e9-931d-e878e550d744.png)

**Comment by abnerlee** [comment]
It's not supported by Markdown, you may need to use `<table>` and write raw HTML.

**Comment by abnerlee** [comment]
#2666
