### ISSUE TITLE
Diagrams not available

### ISSUE THREAD

**Issue by tmanderson** [typora/typora-issues#2404]
Hello, since the last update I have not been able to create diagrams in any of my documents. If I try typing <code>```flo</code> I do not get any completion for `flow`.

The same goes for `mermaid`, `sequence` and all other diagram options that have previously been available.

In short, I cannot create any diagrams within Typora since the last update.

**Comment by abnerlee** [comment]
Please enable it from preferences panel

**Comment by tmanderson** [comment]
Oh, wow – I totally missed that the first time around. Thanks!
