### ISSUE TITLE
strange display math size in exported pdf

### ISSUE THREAD

**Issue by 111116** [typora/typora-issues#2405]
Math equations look great in Typora preview. But **some** of them are extremely large in exported pdf. Note that this never happens to inline math.
Typora version: 0.9.9.23 (2256) on macOS 10.14.2
<img width="922" alt="image" src="https://user-images.githubusercontent.com/19388588/56145839-a3aad500-5fd7-11e9-8219-f648aa5d29b3.png">

**Comment by abnerlee** [comment]
Possible to provide the sample md file for us to check?

**Comment by 111116** [comment]
Example:

```markdown
inline formula $E=mc^2$
$$
E = mc^2
$$
```

in exported PDF the second formula is much bigger.

Typora Version 0.9.9.24 (2369)
MacOS 10.14.2 (x86_64-apple-darwin18.2.0)
pandoc 2.3.1 Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.1, skylighting 0.7.3

Let me know if you need more information.

**Comment by abnerlee** [comment]
should be fixed in latest version
