### ISSUE TITLE
Can I set the "Image Insert" mode for different files?

### ISSUE THREAD

**Issue by liutianyan** [typora/typora-issues#2406]
in preferences panel, we can set like this http://support.typora.io/Images/

but maybe this md file ,i need upload image file to web server
and other file, i would like to copy images to given folder

now, i am switching between those files.

**Comment by abnerlee** [comment]
Yes, see http://support.typora.io/Images/#when-insert-local-image

**Comment by liutianyan** [comment]
> Yes, see http://support.typora.io/Images/#when-insert-local-image

I got it ,tks
