### ISSUE TITLE
Up/down arrow on scroll bar

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2407]
I am using the Linux version 0.9.68, and would like to know if there is a way to get up/down arrows on the scroll bar.

**Comment by abnerlee** [comment]
We do not provide such detailed options, you may refer:
http://support.typora.io/Add-Custom-CSS/
https://stackoverflow.com/questions/16761611/adding-arrows-to-scrollbar

**Comment by DutchPete** [comment]
Thanks Abner, that works. The only problem is that the down arrow is next to the *Word count* box, and when you try to click on the down arrow you effectively click on the *Word count* box. It is not possible to click on the down arrow, even though it is visible.
Is there any way to shift the *Word count* box to e.g. the bottom right hand corner?

**Comment by abnerlee** [comment]
I got your point, it is actaully covered by the status bar, not word count box

You could modify the css
```
.ty-footer {
  right: 18px !important;
}
```
To leave areas for the scroll bar.

**Comment by DutchPete** [comment]
Thanks for coming back on that Abner, that does the trick :-))
