### ISSUE TITLE
Shortcut Key of "Preference"

### ISSUE THREAD

**Issue by ScutLion45** [typora/typora-issues#2408]
1. It seems that the shortcut key of **Preference** is unmodifiable (default `Ctrl/Command+Comma`) even if I modify it in the `conf.user.json`;
2. In my Windows host, there exists a bug of this shortcut key of **Preference**: if I open Typora without having any Typora document opened, then I press `Ctrl + ,` and it works and the Preference widget appears; however, if now I turn to another application (for example, my Website Browser) and then go back, the shortcut `Ctrl + ,` key doesn't work anymore! I think that maybe a bug :-| and hope it can be fixed.

**Comment by abnerlee** [comment]
should be fixed
