### ISSUE TITLE
Export HTML without styles breaks anchors

### ISSUE THREAD

**Issue by tig567899** [typora/typora-issues#2409]
Exporting a file as HTML without styles does not make internal anchors correctly - heading ids are missing from headings, and `<a>` tags to those headings appear to not work correctly.

**Comment by tig567899** [comment]
Suppose I make a md file like this:
![image](https://user-images.githubusercontent.com/17097380/56315794-a700a680-6126-11e9-906c-707968ad4b9c.png)
I attempt to export this to an html file without styles:

![image](https://user-images.githubusercontent.com/17097380/56315928-0a8ad400-6127-11e9-91fc-cfffa2853d8d.png)

The header has no id and hence the internal link is broken.

**Comment by abnerlee** [comment]
should be fixed in latest version
