### ISSUE TITLE
Exporting to PDF with blank content

### ISSUE THREAD

**Issue by guisense** [typora/typora-issues#2411]
**OS: Windows 10 
Typora: 0.9.68**

When I export my .md as pdf, it worked. but with no content，it was totally blank .  And , the size of pdf file was always 2KB 
I have tried with only one word in .md , or with asserts/xx,png linked in .md . Both were failed.
Then I tried to switch to another computer (still windows 10) , after intalled typora and typed words in md, it seems to get the same result.
By the way ,  it works perfectly in my mac.  : )

Sorry i cant upload any picture here with strict company policy :(

**Comment by guisense** [comment]
> Which theme do you use and possible to provide a sample *.md file?

I use `Github` theme , i cant upload any files with this computer. But I can point that even I just type `Hello world` into .md file, it will get the same 

I have noticed that the typora on windows10 has the option `reopen with encoding`, I have tried open .md file with `auto` or `utf-8` , doesnt work again.

I love typora , and want to recommend my collegues to use typora , sharing files with beautiful markdown writing experience. I will be grateful if this problem is solved

**Comment by abnerlee** [comment]
@guisense do you have any firewall or apps that will interrupt the process that Typora reads or write local files?

**Comment by guisense** [comment]
> @guisense do you have any firewall or apps that will interrupt the process that Typora reads or write local files?

I see, the security software must be the key,  *DLP* and *Trend micro officescan*. I have no right to change the softwares' setting, let alone shut down them. Thanks very much for your time , I love typora, I may change to export  *.html or *.png instead, with office computer.

Thanks again.

**Comment by Williams-Ren** [comment]
@abnerlee I met the same problem and I have turned off all the security software except windows defender which I don't think have an effect on this. All my pictures just go directly blank. See the picture:

![Uploading Snipaste_2019-06-03_21-11-16.png…]()
![Snipaste_2019-06-03_21-11-25](https://user-images.githubusercontent.com/45218090/58804824-58ab5680-8645-11e9-87e7-b7e081cf1779.png)

**Comment by Williams-Ren** [comment]
![Snipaste_2019-06-03_21-11-04](https://user-images.githubusercontent.com/45218090/58804939-97411100-8645-11e9-9ed0-b291dd4691e3.png)
![Snipaste_2019-06-03_21-11-16](https://user-images.githubusercontent.com/45218090/58804953-a031e280-8645-11e9-93fe-0895b0b49dfb.png)
