### ISSUE TITLE
Colour emojis in Linux Mint 19.1 XFCE

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2413]
Emojis has been covered in a number of other issues, but not this one. Linux Mint 19 is based on Ubuntu 18.04. @markhu in [this thread](https://github.com/typora/typora-issues/issues/2145#issuecomment-484225438) says that Typora emojis on Ubuntu 18.04 are in colour.

Is there any reason why they are in colour in Ubuntu and not in Mint? Can I add anything to my css file to make them appear in colour?

**Comment by abnerlee** [comment]
Emojis are rendered as unicode char, it depends on whether your font contains colorful emoji or not.

Just like I type "A", but different font may render the glyph differently

**Comment by DutchPete** [comment]
@abnerlee sorry for the late reply, the last sentence of your reply did not show in the Github email I received so I was not aware of it. I just happen to open this web page now and noticed it.

Anyway, many thanks for your suggestion, that's exactly what I was looking for, and it works.

**Comment by ccshao** [comment]
@DutchPete May I ask what is the setting to show colour emoij in linux mint? I am using the Cinnamon edtion.  Thanks!

**Comment by DutchPete** [comment]
@ccshao : this is quite a while ago, and I cannot remember what it was that made me say "it works".

I think what you need to do is
Menu > Markdown > Markdown-it Options and make sure Emoji is ticked.

If that does not do the trick I can attach my customised css file here.

**Comment by ccshao** [comment]
Actually I am not sure about the `Menu > Markdown > Markdown-it Options`, there is no "Menu", or do you mean the Preferences? I didn't find options for Emoji there. 

Could I have a look at the css file? I have tried  different theme (github, dropbox, etc) but none of them shows color emoji.

**Comment by DutchPete** [comment]
@ccshao : you should get to know the menu, it is important. If you open VNote, at the top of your screen there are 5 words:
File, Edit, View, Markdown, Help.

If you click on the 4<sup>th</sup> one, Markdown, you'll see `Markdown-it Options`.

Have a look and tick off what I said before. Let me know how it goes.

**Comment by ccshao** [comment]
Emm, **VNote**. But we are in the issue of **Typora**...

**Comment by DutchPete** [comment]
@ccshao : oops, what a blunder. My sincere apology. But my comment still goes:
this is quite a while ago, and I cannot remember what it was that made me say "it works". Here is my base.user.css file, which I have had to save as a .txt file in order to be able to attach it:


[base.user.txt](https://github.com/typora/typora-issues/files/4318811/base.user.txt)

**Comment by ccshao** [comment]
Thanks for the css file, I installed the theme, unfortunately it didn't work in my side (typora 0.9.86, linux).

**Comment by DutchPete** [comment]
@ccshao : I now remember now that the only font I found that works is called something like *Noto Emoji* or something similar.

The problem is that although the emojis are in colour the text of the document is awful: very drawn out, very ugly. You should try it, and I am almost sure you'll revert back to your original font. I reverted back, which is why 1 year later I could not remember the reason for my answer to @abnerlee  and still seeing black & white emojis in Typora on my Linux machine. I should have recorded all that here.

In October last year I switched to Mac for different reasons, and the emojis in Typora are coloured, I did not have to change any fonts. Moreover, Typora for Mac supports tabs, the Linux and Windows versions don't.

I hope I have helped a bit with this, although in a longwinded way, for which I want to apologise again.

It would be useful for others to record your experience with the special font, if you are going to try it.

**Comment by DutchPete** [comment]
@ccshao : you have not posted any further comments/replies, which I understand from your point of view, I probably would be the same.

I do want to repeat that I am sincerely sorry for the misunderstanding from my side and did not intend to make you lose your time nor to put you on the wrong track.

**Comment by ccshao** [comment]
@DutchPete Sorry for the late reply, it was night in Germany locale time. By no means I want to be rude to your kind help ...

I feel the black/white and samll size Emoji in mint has something to do with the system setting, as Emoji is colorful in Ubutun, from which mint is bulit. Anyway, Typora is still on beta and hopefully this issue could be resolved.

**Comment by DutchPete** [comment]
@ccshao thanks for your reply, that sets my mind at peace. Phew!

At the time I had the same question as you: why can emojis be in colour on Ubuntu and not on Mint, which is based on Ubuntu?

Fortunately I don't have that problem anymore as I now use Typora on a Mac, and the emojis are coloured as expected, and there are no strange effects on the text.

BTW, I don't know if Typora will ever come out of beta seeing that it has been in beta for some 3 years I think. Anyway, that is not important.
