### ISSUE TITLE
Issue with installation on Fedora

### ISSUE THREAD

**Issue by dbc2201** [typora/typora-issues#2414]
I had been using Typora for all of my typing needs on my Ubuntu installation and it worked like a charm! But recently, I had moved to a Fedora installation (ver 29) and I am having trouble with installing it on my machine.  
There seems to be no mention of installation steps for an RPM-based machine for Typora on the [official website](https://typora.io/).  
I had tried downloading the x86 version and creating a desktop entry for that by placing it in the /opt folder but that does not seem to work.

**Comment by abnerlee** [comment]
#1457
