### ISSUE TITLE
Can't use character ' after letters

### ISSUE THREAD

**Issue by thebrucecgit** [typora/typora-issues#2416]
I think it might be just me, but this seemingly trivial bug is occurring on my device. (Mac 10.14.4 Beta). 

I can't actually type `it's`. Seriously, I can't. When I try to do that it just gives me `its`. I realise that I can't actually type `'` after any letter. It's fine when there's a space or a new line in front of it. 

I need to disabled "Auto pair brackets and quotes" in the settings. 

I'm using Version 0.9.9.24 (2369)

Thank you

**Comment by rsilvestre** [comment]
+1

**Comment by abnerlee** [comment]
should be fixed on 0.9.9.24.1
