### ISSUE TITLE
几个建议：增加百度云下载、发布到WordPress、增加图床服务

### ISSUE THREAD

**Issue by shenjianxin** [typora/typora-issues#242]
几个个建议：

- 能否增加国内下载链接，我所在的研究所国际流量1元/Mb，为了给老板节省经费能否增加百度云的下载，也能增加其他国内用户的下载速度。
- 能否增加一键发布到WordPress、印象笔记等服务器的功能
- 能否增加对七牛云存储等图床的支持

谢谢啦！

**Comment by abnerlee** [comment]
> 能否增加国内下载链接，我所在的研究所国际流量1元/Mb，为了给老板节省经费能否增加百度云的下载，也能增加其他国内用户的下载速度。

You can download at home

> 能否增加一键发布到WordPress、印象笔记等服务器的功能

WordPress is possible, but we do not have plans for evernote. Publish function is not in high priority.

> 能否增加对七牛云存储等图床的支持

We are planning to improve the workflow related with images, including cloud service support for updating / storing images.
