### ISSUE TITLE
LaTeX doesn't update consistently

### ISSUE THREAD

**Issue by b2550** [typora/typora-issues#2420]
Sometimes when using inline LaTeX, the preview will show what I typed but when I move outside the `$` it doesn't update the rendered output to match my changes. I can only get it to update by typing directly after the last `$`.

Version 0.9.9.24 (2369)

**Comment by irgendwr** [comment]
I've noticed this too, especially after copy&pasting.

Example:

![latex_preview_bug](https://user-images.githubusercontent.com/17804578/57251143-64592c80-7049-11e9-8a5e-4b395371ac9c.gif)

**Comment by justnealpatel** [comment]
I keep getting this issue as well on the latest version currently: Typora Beta 0.9.9.30.1

This happens quite often to me as well. I have to fix it by repeatedly deleting the ending `$` and re-inserting it and after several tries it finally renders. Any idea on how to fix this @abnerlee ?

**Comment by abnerlee** [comment]
should be fixed
