### ISSUE TITLE
New task above existing task

### ISSUE THREAD

**Issue by masonlr** [typora/typora-issues#2421]
I'm trying to insert a task above an existing task. I've seen #1238 and (duplicate) #1253, but don't think this case below is covered. 

Open for debate, but would it make more sense for the original task "Foo" to remain checked, rather than becoming unchecked?

![typora](https://user-images.githubusercontent.com/5828176/56432177-5de65900-62c4-11e9-9dc2-27c9059d7fc3.gif)

**To reproduce:**

1. Starting point:

```
- [x] <cursor>Foo
```

2. Press enter.

**Expected outcome:**

```
- [ ] <cursor>
- [x] Foo
```

or even

```
- [ ] 
- [x] <cursor>Foo
```

**Actual outcome:**

```
- [x] 
- [ ] <cursor>Foo
```

**Comment by abnerlee** [comment]
Yeah, that make sense

**Comment by abnerlee** [comment]
should be fixed in latest version
