### ISSUE TITLE
Mermaid diagram cropped in pdf export on Linux (Again)

### ISSUE THREAD

**Issue by ProgramFan** [typora/typora-issues#2423]
When exporting documents with large mermaid diagrams to pdf, the resultant pdf file crops the diagram with a horizontal scrolling bar, instead of shrinking the diagram to fit the page width. It only happens on Linux (possibly on Windows). macOS is OK.

## Example Markdown

```mermaid
graph LR
A[kkkkkkk]
A-->DDDDDDD
DDDDDDD-->EEEEEEE
EEEEEEE-->FFFFFFF
FFFFFFF-->GG
GG-->HH
HH-->II
II-->JJJJJ
JJJJJ-->KKKKK
```

PDF on Linux:
<img width="933" alt="图片" src="https://user-images.githubusercontent.com/32396/56450062-87e75c00-6354-11e9-94e4-f7aa89f2c140.png">

PDF on macOS:
<img width="933" alt="图片" src="https://user-images.githubusercontent.com/32396/56450086-b2d1b000-6354-11e9-902f-fb5abfe55da6.png">

## Typora Version

This happens with Typora 0.9.65 all the way to the latest 0.9.69. I don't know whether it happens on older Typora. On the version I tested, the macOS version works as expected but the Linux version has the above bug.

**Comment by ProgramFan** [comment]
The theme I am using is github.

This bug seems to be addressed before in #1884, but comes out again.

**Comment by Zachu** [comment]
I can reproduce it with Typora 0.9.70(beta)

**Comment by abnerlee** [comment]
should be fixed in latest version
