### ISSUE TITLE
Custom replacement variables in paths

### ISSUE THREAD

**Issue by mfitzp** [typora/typora-issues#2425]
Hello! I'm using Pelican (Python static site generator) to generate site and would like to use Typora to write the markdown files. In Pelican images are referenced using a {static} variable insert, which is used to identify static files and handle re-writing of URLs during output.

An example URL would look like this —

\![Image here]({static}/path/to/image.jpg)

It would be very handy if Typora supported "variable" replacement in paths, so for example in the configuration it was possible to specify that {static} == a given path.

I could see this being useful to reference files for other use cases too (e.g. keeping files in a specific folder somewhere).

**Comment by abnerlee** [comment]
can be covered with #4191
