### ISSUE TITLE
Bug when selecting text

### ISSUE THREAD

**Issue by Williams-Ren** [typora/typora-issues#2426]
![image](https://user-images.githubusercontent.com/45218090/56469293-87d98000-646a-11e9-8273-83ff26107ca0.png)
![image](https://user-images.githubusercontent.com/45218090/56469296-9a53b980-646a-11e9-8ae6-bbe575fc8c4e.png)
As you can see in the two pictures, there are two black rectangles making no sense. That will sometimes appear after I select more than two lines of text. It will flicker for a while and then disappear for no reason. This is not a very important but very annoying bug. the frequency of its flicker is equal to the frequency of flicker of the cursor. I hope this clue will be helpful.
Apologize for my poor English.

**Comment by Williams-Ren** [comment]
BTW, the yellowish color is due to another application

**Comment by abnerlee** [comment]
still happens in latest version?

**Comment by abnerlee** [comment]
relates #4086

**Comment by Williams-Ren** [comment]
No, it has been fixed in someway. Thank you for updating it!
