### ISSUE TITLE
Only show emoji like 😄 but not 😄:smile: when editing

### ISSUE THREAD

**Issue by AlienKevin** [typora/typora-issues#2427]
# Current behavior
Currently, when the cursor is placed after an emoji like `😄`, the name of the emoji automatically appears `😄:smile:`. 
# Problems 
I understand that this function is similar to other styles like bold, italic, or headers which shows the wrappers when clicked. However, since most people use emojis as pure text, I feel it's more natural to just render them as a normal letter or character, similar to how Typora displays non-English characters like 笑. Showing :name: after emojis make normal text editing a painful process because when you try to delete an emoji, its :name: appears and I have to select the whole word to delete a single emoji. The auto expansion of emoji names become a greater issue when the name is very long. Like `🌐:globe_with_meridians`.
# Proposed Solution
Input emojis using :name: but render them just like normal text characters and do not expand their names.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/1313

merge into #1317
