### ISSUE TITLE
image not show 

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2429]
1. https://ws2.sinaimg.cn/large/007EIIJlgy1g1arbyq4pbj30m80dldgq.jpg
can show

1. https://wx3.sinaimg.cn/large/007EIIJlgy1g1arb3tfq0j30m80f8758.jpg
https://pic1.zhimg.com/80/v2-9f2e403fb7784ba65d17e41ff51e008b_hd.jpg
can not show when set as default,   can show when set as download to local filname.assert .

mac 10.13.1 
typora 0.9.9.24.2

**Comment by abnerlee** [comment]
https://wx3.sinaimg.cn/large/007EIIJlgy1g1arb3tfq0j30m80f8758.jpg is not accessible
