### ISSUE TITLE
imag load fail.

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2430]
this imag can't show in typora

![640-20190423142130030](https://user-images.githubusercontent.com/1228446/56559316-da827b80-65d3-11e9-8491-adf61dba32e6.png)

mac 10.13.1
typora 0.9.9.24.2

**Comment by cshishaliu** [comment]
I got this problem too, and this is so annoying!!!

**Comment by abnerlee** [comment]
#2439
