### ISSUE TITLE
couldn't delete file in the sidebar

### ISSUE THREAD

**Issue by gnwd** [typora/typora-issues#2432]
[vokoscreen-2019-04-23_17-08-06.m4v.zip](https://github.com/typora/typora-issues/files/3106815/vokoscreen-2019-04-23_17-08-06.m4v.zip)

**Comment by gnwd** [comment]
[Uploading vokoscreen-2019-04-23_17-08-06.m4v.zip…]()

**Comment by abnerlee** [comment]
In latest version, we will show dialog for perimate delete if move to trash failed
