### ISSUE TITLE
Typora from tar ball

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2437]
I might change to a different Linux distro (MX?) from the one I am on now (Mint). MX does not support PPA, so I might then have to download the tarball. That is not a problem, but I would just like to ask if one gets automatic updates, i.e.can one set Typora then to check for updates e.g. each time the app is opened?

**Comment by abnerlee** [comment]
See http://support.typora.io/Typora-on-Linux/ for tar ball

relates #1457

> can one set Typora then to check for updates 

We don't support this on Linux, since linux has its on install/update system.

**Comment by DutchPete** [comment]
So that means that if I use Typora froma tar ball, i.e. as a portable/standalone app, and I want to have a newer version I have to download the new tar ball and use that, correct?

**Comment by abnerlee** [comment]
@DutchPete Yes

**Comment by DutchPete** [comment]
OK, thanks, clear. Issue can be closed.
