### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by Michael-Luxus** [typora/typora-issues#2438]
Hello, Typora is really really a nice project. Congrats! however, a developper realy need those missing commands :

- shortcut for move line or selected group of line up
- shortcut for move line or selected group of line down
- shortcut for add next line under current line (kind of: Ctrl + Enter)
- shortcut for add next line above current line (kind of: Ctrl + Shift + Enter)
- shortcut for delete the entire line
- shortcut for default Ctrl + C to copy the entire line if nothing is selected
- shortcut for default Ctrl + X to cut the entire line if nothing is selected
- shortcut for add cursor under current cursor line position
- shortcut for add cursor above current cursor line position
- shortcut for add and select identical words as we press again and again the command
- possibility of multi-cursor outside of code area (yeah, it is useful)

Please consider implementing them in the future version. Without them, users lose precious time editing.. Thank you!

**Comment by abnerlee** [comment]
duplicate with existing issues
