### ISSUE TITLE
img can't show

### ISSUE THREAD

**Issue by HermanZzz** [typora/typora-issues#2439]
img inserts by iPic can't show in Typora, but can show in others like MWeb.

such as 'https://ws4.sinaimg.cn/large/006tNc79ly1g25r4ic2cyj30x00eywgl.jpg'.
![image](https://user-images.githubusercontent.com/8086434/56791520-d3f53d80-6839-11e9-93cd-a39299a7f48c.png)

Version 0.9.9.24.2 (2386)
MacOS 10.14.4

**Comment by itcook** [comment]
same problem, the tip shows 'image load failed'

**Comment by X-thon** [comment]
I have same problem, it is troublesome, always show "image load failed".
But i use Mweb to open the md doc, the image can display normally.

**Comment by Codeprh** [comment]
same problem, the tip shows 'image load failed'

**Comment by fengbeibei** [comment]
Same problem，all other image url works except the ipic url using sinaimg.cn.
macos: 10.14.4
typora:  0.9.9.24.2 (2386)

**Comment by abnerlee** [comment]
should be fixed

**Comment by abnerlee** [comment]
sinaimg.cn is not a image reference site, it may turn off the support at any time. So we just you to use other image online storage service.
