### ISSUE TITLE
[Feature Request] fenced divs and bracketed spans

### ISSUE THREAD

**Issue by CxRes** [typora/typora-issues#2441]
I would like to request syntax extension for fenced divs and bracketed spans as supported by [Pandoc](https://pandoc.org/MANUAL.html#divs-and-spans). 

This should be relatively easy to add as Typora already allows custom HTML blocks. This extension will allow one to enter the same thing in a more markdown-y way.

On a related note, is it possible to contribute extensions somehow?

**Comment by abnerlee** [comment]
#2448

**Comment by fyemath** [comment]
For revealjs slide and powerpoint, Pandoc's fenced divs seems necessary for adding incremental/nonincremental slides, or notes. So far, I couldn't figure out a resolution.
