### ISSUE TITLE
Normalize Unicode

### ISSUE THREAD

**Issue by Crissov** [typora/typora-issues#2443]
I am writing a lot of simple math and technical texts about characters in Typora, so I am using a couple of named HTML entity references that I know by heart and some hexadecimal codes for characters that I am writing about and hence already looked up. Some other non-ASCII characters are readily available on my keyboard and are required for at least one language I am writing in as we ll as for proper typography.

Following up on #1586, it would be great if Typora would offer a way to **normalize the various ways to input Unicode characters** in Markdown through HTML grandfathering:

- Named character references: `&auml;` (`&auml` without trailing semicolon supported in some cases)
- Decimal character references: `&#228;`
- Hexadecimal character references: `&#x00E4;`, `&#xe4;` etc.
- Plain character: `ä`

The default should be to store all characters directly as Unicode if UTF-8 (or another UTF) is used as the file encoding (as it should be).

Going one step further, Typora should offer to apply **full Unicode normalization**: NFC (_composed_), NFD (_decomposed_), NFKC or NFKD (K = _compatibility_).

- `a&#776;`, `&#97;&#776;` (U+0308 Combining Diaeresis)
- `a&#x308;`, `&#x61;&#x308` etc.
- `ä`

**Comment by Crissov** [comment]
PS: Emoji short-codes like `:beer:` for :beer: should also be normalized to Unicode.

**Comment by abnerlee** [comment]
relates #1433 #2427

I will put into #1316

**Comment by Crissov** [comment]
Yes, #1316 makes sense as a collective issue.

**Comment by Crissov** [comment]
It would also be nice if advanced users could edit and amend the lists and expansions of HTML entities, Emoji shortcodes and SmartyPants punctuation. This does not need to be in the GUI, JSON files would suffice.
