### ISSUE TITLE
Allow to create new file when link target does not exist

### ISSUE THREAD

**Issue by jhereth** [typora/typora-issues#2444]
Having a link like `[text](nonexisting.md)` and Cmd-clicking on it gives the response "Cannot open location `nonexisting.md`, do you mean https://nonenxisting.md?".

Additionally, the option to create the file `nonexisting.md` and open it in typora could be provided.

This would greatly ease the user flow creating linked documents.

**Comment by abnerlee** [comment]
should be fixed in 1.1
