### ISSUE TITLE
$$ always reverted to $ in headings

### ISSUE THREAD

**Issue by phizaz** [typora/typora-issues#2449]
I write markdown to be used with Mathjax latex. Usually, `$$` is a default escape character. 

I could use `$$` to define an inline math block in Typora without any problem. However, using this with headings doesn't seem to work. I could see in the code view that `$$` always gets converted back to `$`. This would be misunderstood by Mathjax and not rendered. 

I think converting `$$` back to `$` is not an intended behavior because this doesn't happen with normal text.

**Comment by abnerlee** [comment]
What's your Typora version and how to reproduce this, could you share more details

**Comment by phizaz** [comment]
@abnerlee 
Typora version: 0.9.70 (beta)
**How to reproduce:**
try: `# $$x=10$$` 
![image](https://user-images.githubusercontent.com/451667/56873256-4729ca00-6a5b-11e9-9878-ce32503b6d6e.png)
Enter, then go to code view:
![image](https://user-images.githubusercontent.com/451667/56873267-5f99e480-6a5b-11e9-80da-85374c4506da.png)
You see `$$` becomes `$`.

**Comment by abnerlee** [comment]
should be fixed in latest version
