### ISSUE TITLE
How change the style of HTML export?

### ISSUE THREAD

**Issue by UltimateRandom** [typora/typora-issues#245]
I'm using a dark theme but when i export to HTML is white, there is a way to change the html export theme?

Also this tip is only for IOS right?
"Cmd+Shift+O can be used to quickly open files from recent used files or context folder. "

**Comment by UltimateRandom** [comment]
The html style can be changed crating a file called **base.user.css** in AppData\Roaming\Typora\themes.
I read typora documentation and haven't found this, if i'm right this tip should be included in the wiki/documentation, i actually downloaded Atom + MD Plugins for making the HTML files because i didn't know i could do it in typora (and far more easy). 
Anyway this program is awesome, the best MD editor/viewer by FAR.

**Comment by vassudanagunta** [comment]
The user documentation has an open source repo: https://github.com/typora/wiki-website. If you think there should be a page for something, make a pull request. :)
