### ISSUE TITLE
bug messy code when use with version 0.9.70

### ISSUE THREAD

**Issue by chndev** [typora/typora-issues#2451]
sometimes my file  occur messy code  when use typora.
<img width="436" alt="搜狗截图20190429103337" src="https://user-images.githubusercontent.com/49592223/56874134-6d0a9b00-6a6a-11e9-8902-8bad78f94998.png">

**Comment by abnerlee** [comment]
Try `File` -> `Reopen with Encode`. Also, possible to send us <hi@typora.io> the sample file ?
