### ISSUE TITLE
Line Break options have inconsistent defaults

### ISSUE THREAD

**Issue by neubland** [typora/typora-issues#2452]
Right now, by default Typora displays in WYSIWYG mode with soft line breaks preserved as line breaks. By default, when exporting/printing, soft line breaks are ignored.

There is a problem with these defaults:
1) What you see is not what you get when exporting. This is always true to some extent, but line breaks are essential to the structure of the document.
2) The behavior is confusing to users who don't know about this being a result of the default settings. They don't have a reason to believe that this "flaw" in exporting is due to a specific setting. Other issues stating that there is some kind of issue with line breaks are proof to this.

Proposal: The default for line breaks in WYSIWYG and export/print should be the same, achieving consistency.

**Comment by vassudanagunta** [comment]
@neubland I totally agree. I've been trying hard to get @abnerlee to recognize that WYSIWYG should be a priority. See #1317, for one example.

**Comment by abnerlee** [comment]
Fixed in latest version (for new users)
