### ISSUE TITLE
Layout error in export message

### ISSUE THREAD

**Issue by alexanderjulmer** [typora/typora-issues#2454]
When a document is exported, Typora shows a message at the top of the window. If system language is set to German the translation of "Open in Finder" seems to be longer than the button and therefor runs into the "Close" button (see screenshot).
<img width="986" alt="Bildschirmfoto 2019-04-30 um 10 10 30" src="https://user-images.githubusercontent.com/10468332/56948531-adcce780-6b30-11e9-9e7c-d30b901fa03c.png">

Ps: The translation is incomplete. "Export operation finished successfully" literally translates to "Exportoperation erfolgreich abgeschlossen" or simply "Export erfolgreich" ("export successful")

**Comment by abnerlee** [comment]
Could you provide your Typora / OS version and which theme are you using?

**Comment by alexanderjulmer** [comment]
Sure, sorry about that.

I am using OSX 10.14.4 (18E226) and Typora Version 0.9.9.24 (2369) with the Github Theme.

**Comment by abnerlee** [comment]
should be fixed in latest version
