### ISSUE TITLE
Implement emoji parser for unsupported platforms.

### ISSUE THREAD

**Issue by dmxt** [typora/typora-issues#2455]
Emojis are unsupported natively on Windows 7, 8 and Linux distros. We either see emoji as tofu or black/white polyfill: 
![image](https://user-images.githubusercontent.com/3248782/56964487-48c1c380-6b29-11e9-8b3f-0de2ba48604f.png)

Some of us installed [SVGinOT emoji font](https://github.com/eosrei/twemoji-color-fon) to solve some of the emojis issues across the system like on Gecko browser, Adobe software, etc. 

In this case, Tyrora uses the gecko engine and Gecko doesn't support SVGinOT fonts. I fixed this on Chromium by using a 3rd party extension which parse and replace unicodes with image or SVG based emojis, but it's not relevent since Tyrora is a stand-alone webviewer and I don't know how to "port" an extension to Electron app or implement parser libraries to it.

I think the solution is implementing some sort of emoji parser, which detects unsupported emoji Unicode and replaces it with an image or SVG in their library. Couple parser emoji libraries are [listed here](https://github.com/iamcal/emoji-data#libraries-which-use-this-data).

On top of it, we could even add a Javascript based picker for unsupported systems like [wdt-emoji-bundle](https://ned.im/wdt-emoji-bundle/) or various [picker alternatives](https://github.com/search?q=emoji-picker) that trigger by click or a keyboard shortcut.

If there's any way to add it by theme stylesheet, please tell me about it! Otherwise, please implement it for us, the people on unsupported operating system. ❤️

**Comment by abnerlee** [comment]
see instructions on #2413

This should be fixed on system level. So we don't have plans to "hack" for it.

**Comment by dmxt** [comment]
@abnerlee 	GNU/Linux distros and Windows 8, Windows 7 and older do not support emoji natively. Many heavily populated sites including GitHub, Twitter, all social media I know, etc all have their own emoji fallback written to support Linux and Windows 8 or older.
