### ISSUE TITLE
Function to sort tables

### ISSUE THREAD

**Issue by schultzter** [typora/typora-issues#2456]
Provide the ability to sort the rows of a table based on the contents of a column. Either by right clicking a column and choosing Ascending or Descending in the pop-up; or in the right-hand table menu have a Sort item with a Ascending/Descending toggle and the list of columns (using the header row).

Sorting the table would actually sort the underlying contents, not just the presentation, so that sorts persist across sessions.

Sorting is character-based, Typora should not try to determine the data type.

**Comment by abnerlee** [comment]
#1088
