### ISSUE TITLE
Images not showing on cell-phone app

### ISSUE THREAD

**Issue by itsAftab** [typora/typora-issues#2457]
When i open a document with screen-shoots and images on my cell-phone, the images are not showing up. I get a path instead (see the screen dump). I have tried multiple Markdown apps but the result is the same.
![image](https://user-images.githubusercontent.com/45290523/56968859-3618b000-6b64-11e9-833e-f62267c026e8.png)
I have put the application under <u>/Users/<my username>/My Applications</u> because i dont have admin rights on my Mac.

**Comment by abnerlee** [comment]
The image path is on your Macbook and not available on your mobile. 

You may need to sync the images between Macbook and mobile as well.
