### ISSUE TITLE
(A bug?) Some code blocks are not highlighted in a long document.

### ISSUE THREAD

**Issue by ocrinz** [typora/typora-issues#2458]
I'm using Typora 0.9.68 beta and came across an issue.

When I opened a very long markdown file in Typora and (without looking through it) exported it as a PDF file, I found that only the code blocks of the first few pages were highlighted, and the rest were not highlighted at all. However, as long as I looked through it from beginning to end before exporting it, then the code blocks in the exported PDF file were correctly highlighted.

I tried a few times and always got the same result (as said above).

I think this is a bug of Typora, and I hope someone can fix it. Thanks.

**Comment by abnerlee** [comment]
Possible to send us (<hi@typora.io>) a sample md file?

**Comment by ocrinz** [comment]
> Possible to send us ([hi@typora.io](mailto:hi@typora.io)) a sample md file?

OK. I'll send my md file (blutrex@gmail.com).

**Comment by abnerlee** [comment]
should be fixed in latest version
