### ISSUE TITLE
[Feature request] Pasting image from clipboard convert to jpeg image format

### ISSUE THREAD

**Issue by syedsameerali** [typora/typora-issues#2459]
In my note taking workflow I often paste images captured using snipping software such as the Windows Snipping tool or Greenshot. When I paste the image from the clipboard, Typora saves the image to the specified image directory as a .png file. 

Since the notes I write with Typora are initialized as a git repository, I find the .png format to be of a much larger file size compared to the jpeg format. Considering the use of git repositories, I find that jpeg would be a better choice in situations where disk space is a concern.  

It would be nice to allow the user to specify which image format the image is saved as, and if jpeg is the preferred choice, to allow the user to control the jpeg quality.

<details closed>
<summary>Current behavior with .png format</summary>
<br>

![example-image-path-fromat](https://user-images.githubusercontent.com/42515946/57011220-180d8700-6c1a-11e9-892c-cdcca6b33205.jpg)
</details>

<details closed>
<summary>Concept Mock-up</summary>
<br>

![design-concept](https://user-images.githubusercontent.com/42515946/57011323-90744800-6c1a-11e9-97e2-02756385d5bc.jpg)
</details>

With much appreciation and thanks,

Sam

**Comment by abnerlee** [comment]
Merge into #2242.
