### ISSUE TITLE
How to make math block align left? 

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2461]
found this https://github.com/mathjax/mathjax-docs/wiki/MathML-alignment-Left-or-Right

but i don't know where to configure, only can modify the css file

**Comment by abnerlee** [comment]
It's not supported, you may watch https://github.com/mathjax/MathJax/issues/1075

**Comment by eduardohorta** [comment]
A working example on macOS Catalina: [https://github.com/typora/typora-issues/issues/1564#issuecomment-691047922](https://github.com/typora/typora-issues/issues/1564#issuecomment-691047922)
