### ISSUE TITLE
Upper🔠 and lower🔡 case more distinguishable in code fences and math blocks

### ISSUE THREAD

**Issue by AlienKevin** [typora/typora-issues#2462]
# Problems
**Currently, the font used in code fences and math blocks make some upper and lower case versions of a letter very hard to distinguish from each other. Letters like "x", "w", "v", "o", "k", "z", and "s" have lower and upper case that are too alike and hard to decipher.**
![image](https://user-images.githubusercontent.com/22850071/57018221-95bc9d00-6bf0-11e9-9374-60c72f5aa4b0.png)

# Solution
Change or modify the current font in code fences and math blocks to use something like this:
![image](https://user-images.githubusercontent.com/22850071/57018431-8a1da600-6bf1-11e9-843d-f533b8787779.png)
I notice the fonts used by Typora are similar to the ones used in VS Code and Sublime Text 3, but the capital letters in Typora are not as *tall* as the ones in other editors, making them hard to distinguish.

**Comment by abnerlee** [comment]
please refer http://support.typora.io/Add-Custom-CSS and http://support.typora.io/Custom-Font/
