### ISSUE TITLE
Shift-enter after paragraph jumps the view

### ISSUE THREAD

**Issue by Zikoat** [typora/typora-issues#2463]
OS Version: Windows 10 Education 10.0.17763 Build 17763
Typora version: 0.9.70

Reproduce:
New file
Enable typewriter mode
paste full page of text (eg. [lipsum](https://www.lipsum.com/feed/html))
move cursor to after the last character of a paragraph
press shift-enter. the page jumps down
enter a character. the page jumps back up again

the page jumps more based on how long the paragraph is. if the paragraph spans a whole page, the cursor cant be seen after i have pressed shift-enter. this happens on all themes

this does not happen if i move the cursor *before* the last character of a paragraph, and press shift-enter

**Comment by abnerlee** [comment]
should be fixed in latest version
