### ISSUE TITLE
drag-n-drop Typora icon from window title should insert a link

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#2464]
The screen recording below speaks for itself.  The following should have been inserted:

```
[doc two](../relative-path/doc two.md)
```

![screen-record](https://user-images.githubusercontent.com/2830093/57042999-4bf5a600-6c34-11e9-8d92-c9883d6aa1c1.gif)

**Comment by vassudanagunta** [comment]
This is related to #1612, #1754 and #2415.

@abnerlee Ideally rather than fixing all of these issues piecemeal, wouldn't it be better to solve the general case cut-n-paste / drag-n-drop, taking advantage of all the metadata the OS supplies, and do the smart thing (i.e. a proper Markdown link with the right link text)?

**Comment by abnerlee** [comment]
#2274

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by vassudanagunta** [comment]
Would you consider reopening this considering https://github.com/typora/typora-issues/issues/1612#issuecomment-541821028?

I remember that when you first fixed this issue, it did not include `file extension` in the `title`.
