### ISSUE TITLE
Cursor jumps to end of paragraph

### ISSUE THREAD

**Issue by missescher** [typora/typora-issues#2468]
In latest v0.9.70

(A small one.) 

When I click near the end of a line (circled section) the cursor briefly jumps to the end of the line I clicked on, but then jumps down to the end of the paragraph after a split second. 

![image](https://user-images.githubusercontent.com/12252439/57174886-ad15b780-6e88-11e9-9a56-8e53ee44313b.png)

Given that when I hover over this section, the cursor is styled as the text cursor, the behaviour I expect from a click is for my blinking cursor to go to the end of the line I clicked near and stay there happily.

Also: behaviour described above is mirrored when I click in the space before the line, to the left of the text, the cursor will jump to the start of the paragraph

**Comment by abnerlee** [comment]
should be fixed in latest version
