### ISSUE TITLE
Image orientation problem

### ISSUE THREAD

**Issue by kropkamalpakropka** [typora/typora-issues#2469]
I have an issue with photos, that I took with my camera/smartphone. Whenever photo was taken vertically and I want to attach it, it is shown in a note in horizontal position, even though in folder view it is shown vertically. Any ideas how to fix it?

edit: I work on windows 8, newest Typora version

**Comment by abnerlee** [comment]
This may be a upstream of Chromium. refer https://stackoverflow.com/questions/42401203/chrome-image-exif-orienation-issue

Anyway, `<img src=”your image” style=”transform:rotate(90deg);” /> ` is supported in latest version, so you could use it to rotate images.

For auto detection, I will merge into #1059
