### ISSUE TITLE
Cannot open preferences

### ISSUE THREAD

**Issue by athenashavoc** [typora/typora-issues#2471]
Win10 - 0.9.70(beta)

Selecting Preferences from the menu or using keyboard shortcut does nothing. The system seems to hang for a moment then the program just stops responding. I can close the window and restart the program and use it normally so long as I don't access Preferences.

This had happened to me before.  So far I've tried:
- removing the 'Typora' folder from AppData
- opening New file and trying both the keyboard shortcut(ctrl+,) and selecting from the menu.
- uninstall/reinstall and trying all of the above again.

It had been working until recently, perhaps within the last month? I don't remember exactly when i last changed preferences. I've included the log file since it was asked for last time.

[typora.log](https://github.com/typora/typora-issues/files/3145010/typora.log)

**Comment by AmaiKinono** [comment]
I can confirm this. I am using Typora 0.9.70 on Linux and "preferences" doesn't show up when clicking it. Here's the log:

when startup:
```
INFO 6/1/2019, 3:49:42 PM  ------------------start------------------
INFO 6/1/2019, 3:49:42 PM  typora version: 0.9.70
DEBUG 6/1/2019, 3:49:42 PM  [ '/usr/share/typora/Typora' ]
DEBUG 6/1/2019, 3:49:42 PM  /usr/share/typora/resources/app/locales/Base.lproj/Menu.json
ERROR 6/1/2019, 3:49:42 PM  (node:2493) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
DEBUG 6/1/2019, 3:49:42 PM  [ 'github.css',
  'newsprint.css',
  'night.css',
  'pixyll.css',
  'whitey.css' ]
DEBUG 6/1/2019, 3:49:42 PM  app.openFile
```

when clicking "preferences":
```
ERROR 6/1/2019, 3:50:12 PM  [RenderProcess 1][Error] TypeError: Cannot read property '0' of null
    at Object.v [as validatePandocInstall] (file:///usr/share/typora/resources/app//app/window/frame.js:1:1062438)
    at m.prepPreferencePanel (file:///usr/share/typora/resources/app//app/window/frame.js:1:1297403)
    at Object.p.showPreferencePanel (file:///usr/share/typora/resources/app//app/window/frame.js:1:639502)
    at <anonymous>:1:61
    at EventEmitter.electron.ipcRenderer.on (/usr/share/typora/resources/electron.asar/renderer/web-frame-init.js:36:30)
    at EventEmitter.emit (events.js:182:13)
```

**Comment by abnerlee** [comment]
should be fixed in latest version
