### ISSUE TITLE
Inline code blocks with dollar signs should not be changed by Typora

### ISSUE THREAD

**Issue by N0rbert** [typora/typora-issues#2472]
**Steps to reproduce** - create markdown document with the following contents:

```
# Inline code block with dollars (`$...$`)

# Inline code block with double dollars (`$$...$$`)

## Inline code block with dollars (`$...$`)

## Inline code block with double dollars (`$$...$$`)

### Inline code block with dollars (`$...$`)

### Inline code block with double dollars (`$$...$$`)

#### Inline code block with dollars (`$...$`)

#### Inline code block with double dollars (`$$...$$`)
```

(the syntax is correct - see [commonmark.js rendering](https://spec.commonmark.org/dingus/?text=%23%20Inline%20code%20block%20with%20dollars%20(%60%24...%24%60)%0A%0A%23%20Inline%20code%20block%20with%20double%20dollars%20(%60%24%24...%24%24%60)%0A%0A%23%23%20Inline%20code%20block%20with%20dollars%20(%60%24...%24%60)%0A%0A%23%23%20Inline%20code%20block%20with%20double%20dollars%20(%60%24%24...%24%24%60)%0A%0A%23%23%23%20Inline%20code%20block%20with%20dollars%20(%60%24...%24%60)%0A%0A%23%23%23%20Inline%20code%20block%20with%20double%20dollars%20(%60%24%24...%24%24%60)%0A%0A%23%23%23%23%20Inline%20code%20block%20with%20dollars%20(%60%24...%24%60)%0A%0A%23%23%23%23%20Inline%20code%20block%20with%20double%20dollars%20(%60%24%24...%24%24%60)), also it renders normally in ReText, RStudio, Ghostwriter and many other editors.)

then open this file with Typora 0.9.70 and save without modifications.

**Expected result:** document contents are unchanged.

**Actual result:** document contents changed to

```
# Inline code block with dollars (`$...# )

# Inline code block with double dollars (`$...$`)

## Inline code block with dollars (`$...## )

## Inline code block with double dollars (`$...$`)

### Inline code block with dollars (`$...### )

### Inline code block with double dollars (`$...$`)

#### Inline code block with dollars (`$...#### )

#### Inline code block with double dollars (`$...$`)
```

In the output above all double dollars were changed to single dollar, right backtick removed and replaced with unnecessary `#`s. This is not expected.

**Comment by abnerlee** [comment]
#2449
