### ISSUE TITLE
Deleted file is recreated by Typora!

### ISSUE THREAD

**Issue by gotjek** [typora/typora-issues#2474]
If I delete a file in the explorer, the file disappears from the explorer and the side panel in Typora, great.
But if I click in another file in the side panel in Typora, the deleted file reappears in the side panel and in the explorer with same content than before!

By the way, l love Typora ! It's a wonderful editor I use everyday.

(Windows 10, Typora 0.9.70)

**Comment by abnerlee** [comment]
should be fixed in latest version
