### ISSUE TITLE
Support Markdown Reference-style links

### ISSUE THREAD

**Issue by axelitus** [typora/typora-issues#248]
Currently Typora does not support the use of Reference-style links at the end of the file (see this [README](https://github.com/NorseBlue/Sikker/blob/master/README.md) file for example).

At the moment Typora renders the file like so:
![screenshot 1](https://cloud.githubusercontent.com/assets/732441/17423626/b7225db4-5a81-11e6-95eb-09334c8a7ac0.png)

But it should be displayed like:
![screenshot 2](https://cloud.githubusercontent.com/assets/732441/17423636/ca3b4618-5a81-11e6-86b2-809c48137258.png)

**Comment by abnerlee** [comment]
Fixed in new version

**Comment by axelitus** [comment]
Awesome, I can confirm it works on Typora 0.9.16
![image](https://cloud.githubusercontent.com/assets/732441/17826737/7c8063d6-6639-11e6-937f-1312aaf290d4.png)

One thing though and this is a question (which I'm basing on how GitHub does things and it may not be the "official" Markdown way): Are images supposed to be a block object or are they supposed to flow (on the Typora screenshot it places a line break between images, I know this is an issue that needs to be addressed independently but I noticed it with this one).
