### ISSUE TITLE
Windows 7 64bit 0.9.70 leaks 4K per second working set per window

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2480]
I recently upgraded to Typora 0.9.70 and it leaks memory *continously*, as in, you can watch in Task Manager as the working set (and private working set) for each editor window grows by 4k (minimum) per second, even with all the editor windows minimized.  The only Typora.exe processes not growing at that rate are the main (start) process, and the GPU process.  (The main and GPU process grow at a slower and less regular rate, but still got as high as 2GB last time I killed them.)

Note, by the way, that 4K/sec is the minimum: sometimes the jump is 12K for that second...  and this is with all windows completely idle and minimized!

Currently, my workaround is to kill the main process when the memory consumption gets too high, since at least my windows all get re-opened when I start Typora.

**Comment by abnerlee** [comment]
@pjeby I cannot reproduce it, what theme do you use? And if possible, could you send us <hi@typora.io> the sample file?

**Comment by abnerlee** [comment]
merge into #68

**Comment by pjeby** [comment]
I see continuous memory growth for the renderer process simply on starting Typora with no file or directory open, and minimized.  There is slower growth for the main (no arguments) process, and the GPU process, but the growth of the renderer process's working set is quite steady.

The theme is a variant of an older version of the Github theme, that I modified to have a slightly wider text area.  I do have a fairly large screen size (3 monitors, one of them 2560x1440, the others 1920x1080), but if that were the cause I would think the memory usage would level out.

It seems this may be a common issue with electron apps: https://spectrum.chat/electron/general/debugging-high-memory-usage-in-electron~80057ff2-a51c-427f-b6e1-c297d47baf5b .  So I'm not sure there's anything you can really do about it.

**Comment by abnerlee** [comment]
I don't see this on my PC, but we will upgrade Electron to newer version, which "may" contain performance improvement done by a newer version of Chromium. 

You could also try disable GPU render by add `"flags": [["disable-gpu"]]` in `conf.user.json` (#2051)

**Comment by pjeby** [comment]
Disabling the GPU rendering removes one process from the equation, but otherwise doesn't change anything, unfortunately.
