### ISSUE TITLE
Export as PDF, with night theme, from source code mode doesn't export TOC

### ISSUE THREAD

**Issue by fdbeirao** [typora/typora-issues#2482]
Hi! I'm using Typora 0.9.70 (currently the newest version available). Windows 10 Pro, 64 bits.

To reproduce this issue you need to be using the `Night` theme. Start a new document (no need to save it) file with the following contents:

```
[TOC]

# Chapter 1

# Chapter 2
```

If you are in `Source Code Mode` and you use the menu `File > Export > PDF`, you can observe a warning message telling you that you need to `Print with default theme`. Upon pressing this option, the PDF is exported, but it does **not** contain the table of contents.

On the other hand, if you are not in `Source Code Mode` when you do the same export operation, you can observe the table of contents being correctly output into the PDF.

Cheers and thank you for this awesome piece of software.

**Comment by abnerlee** [comment]
should be fixed in latest version
