### ISSUE TITLE
Prioritize search results

### ISSUE THREAD

**Issue by pfahlstrom** [typora/typora-issues#2484]
It's great that the search function now works, but to be truly usable it should be refined. Right now the results don't seem to be in any particular order—neither alphabetic nor by number of results in each document. My proposal is for the top results to be filenames that include the search term, with the rest of the results listed in order of the most search results per document.

I work for author Brandon Sanderson, and we have an internal universe bible in markdown that has 1800 pages. If I search for the name of a character such as Kaladin, what would be best is for the first result to be the file named Kaladin.md or other files with Kaladin in the filename, and then for the rest of the search results to be listed in order of the most instances that the word Kaladin appears on in the document. Instead, right now our first result is Bowl.md, which talks about the types of bowls used in the books and has his name once. With 1800 pages, there are a lot of search results that include his name, and it takes a long time of scrolling down to reach a relevant article.

Right now we are trying to find the best markdown editor to view the bible in (we previously used WikidPad but it is choking on the number of articles now), and it would be great to be able to use Typora. It is quite a visually pleasing editor. Changing the way search results are displayed in this manner would make it oh so much more usable.

(Also, 1800 files is too many for the Articles view to function, but I don't know what can be done about that.)

**Comment by abnerlee** [comment]
you could use `open quickly` for find file by title, current search function only supports file content search, filename match are provides as supplementary, similar to https://github.com/microsoft/vscode/issues/56757

Aslo. prioritize search means we have to wait all search hits found, then do sorting, then render it out. We currently can only provide simple search functions, advanced search will be considered in future

**Comment by pfahlstrom** [comment]
If sorting would take too long in the initial search, how about options to sort the search results at the end, like there are options at the bottom of the file tree view to sort? Search could be sorted by the same things as the file tree view, plus number of results. The interface could be the same.

Thanks for the quick open suggestion.
