### ISSUE TITLE
with a folder open, doing a 'git pull' in the folder pollutes the sidebar

### ISSUE THREAD

**Issue by burtonrodman** [typora/typora-issues#2489]
I cloned a git repo from Azure DevOps that just had a README.md
I opened Typora for Windows (0.9.70), and did File, Open Folder... and selected the folder that I had just cloned.
I committed a file to the repo from the Azure DevOps website and then executed git pull from the command line.
The Sidebar then had lots of files listed (git artifacts).
I then clicked File, Open Folder again and reselected the folder and then the Sidebar only showed the README.md and my new file.

**Comment by burtonrodman** [comment]
same when you commit and push

**Comment by abnerlee** [comment]
does `git artifacts` mean files under `.git` folder?

**Comment by abnerlee** [comment]
should be fixed in latest version, please reopen if it still exists
