### ISSUE TITLE
latex doesn't work inside html tags.

### ISSUE THREAD

**Issue by peelin** [typora/typora-issues#2491]
Hi, I can't use latex inside html tags. For example,
`<center> The derivative of $x^2$ is $2x$</center>`

Is it possible to add this feature? Or workaround?

**Comment by abnerlee** [comment]
Markdown code inside `<code>` won't be parse (I don;t know why the spec is like this), e.g:

```
<center> The derivative of  **hh** </center>
```

in github

<center> The derivative of **hh** </center>

**Comment by abnerlee** [comment]
#1939
