### ISSUE TITLE
Typora cannot search for/quick open words with non-ascii characters (diacritics)

### ISSUE THREAD

**Issue by dalspok** [typora/typora-issues#2492]
(Global) search in files does not work with non-ascii characters (characters with diacritics) like č ž é ě etc - words with them are not found. The same is true for quick open (command+O) - filenames with words with those characters are not found.

macOS 10.13.6
Typora 0.9.9.24.6

**Comment by abnerlee** [comment]
#2282

**Comment by abnerlee** [comment]
should be fixed. #2282 remains
