### ISSUE TITLE
【Suggestion】Typora cannot deal with folder links on macOS

### ISSUE THREAD

**Issue by thinkycx** [typora/typora-issues#2497]
## env
```
Typora version: latest( 0.9.9.24.6 (2400))
macOS version: latest
```

## problem
1. create a folder with links (right click on folder and create 替身 in Chinese)
![image](https://user-images.githubusercontent.com/13138128/57666347-36b84880-7632-11e9-9543-7eda3f10d1f7.png)

2. open with typora and you will see the links are binary

![image](https://user-images.githubusercontent.com/13138128/57666362-42a40a80-7632-11e9-99cd-65acfedb22b0.png)

3. If I use ln -s to create symbolic links, the typora also failed:

![image](https://user-images.githubusercontent.com/13138128/57666726-9105d900-7633-11e9-8986-e745d37109ac.png)

**Comment by abnerlee** [comment]
#1881
