### ISSUE TITLE
Issues in select and remove texts

### ISSUE THREAD

**Issue by wyf88** [typora/typora-issues#25]
Sometimes when I select some texts and try to delete/replace them, the removed/replaced texts are not what I selected. I guess it is related to inline math too, because this bug occurs more often when the selected texts are near to an inline LaTeX code.

**Comment by abnerlee** [comment]
Hi:

Could you post a snip of your writing including the inline LaTeX for me to test?

**Comment by wyf88** [comment]
Well, the problem is that the bug will not occur after I close my current manuscript and open it on my own Mac. It only occurs after I keep on writing for a while. So I wonder whether it helps at all if I post part (or even the whole) of my writing.

**Comment by wyf88** [comment]
Anyway, here is a sample:
```
For $i = 1, \dotsc, n$, the full conditional distribution of the latent variables $\boldsymbol\omega_i$ is
    
    $$(\boldsymbol\omega_i | \mathbf y_i, \boldsymbol\Lambda_y, \boldsymbol\sigma_y, \mathbf e_{yi}, \boldsymbol\beta_\tau, \boldsymbol\Phi, \sigma_\eta, e_{\eta i}) \sim \mathcal{N}_q(\boldsymbol\mu_i, \boldsymbol\Sigma_i^{*-1}),$$
    
    where $\boldsymbol\Sigma_i^* = \boldsymbol\Sigma_{\omega i}^{-1} + \boldsymbol\Lambda^\mathrm{T} \boldsymbol\Psi_i^{-1} \boldsymbol\Lambda$,
```

**Comment by wyf88** [comment]
After the update, I think this bug becomes more serious. In the past, it only occurs when I select and remove some texts, but now even if I click the mouse to put the cursor behind a word, click backspace, and the cursor jump to somewhere else after the last character of that word is removed. I have to click to mouse again to put the cursor back.

**Comment by abnerlee** [comment]
may duplicate with https://github.com/typora/typora-issues/issues/1199

Seems fixed in recent updates. Please reopen this if it still exists.
