### ISSUE TITLE
[Feature Request] Add a library feature?

### ISSUE THREAD

**Issue by acgood** [typora/typora-issues#2501]
Are there plans to add a Ulysses-like library feature to Typora at some point?

I personally find it really convenient to be able to easily search through all my documents and not have to think about file management very much. I much prefer the writing and reading experience on Typora, but I really do miss Ulysses' library management.

**Comment by abnerlee** [comment]
Typora is a file based editor, it supports working on a folder.

You could try http://support.typora.io/File-Management/#set-default-folder if you don't want to set a working folder every time.
