### ISSUE TITLE
Latex \Omage Render error

### ISSUE THREAD

**Issue by lonelyWaiting** [typora/typora-issues#2504]
i type `$\Omega$`, preview is correct
![Preview](https://user-images.githubusercontent.com/8894664/57839395-38803880-77f9-11e9-80f9-fbe8871b73c2.png)
but render result wrong
![Render Result](https://user-images.githubusercontent.com/8894664/57839474-5d74ab80-77f9-11e9-9a34-7484cc7fff80.png)

if i type a space before or after formula text
![image](https://user-images.githubusercontent.com/8894664/57839647-acbadc00-77f9-11e9-9999-f6dafcc235ab.png)
render result is correct

my editor version is 0.9.70(beta), windows

**Comment by abnerlee** [comment]
I cannot reproduce this. 

Do you use any IME? Or, could you provide steps to reproduce it?

**Comment by abnerlee** [comment]
#2420
