### ISSUE TITLE
Weird character is added when editing equation

### ISSUE THREAD

**Issue by pariterre** [typora/typora-issues#2506]
Hi there,

I was using Typora for writting paper using markdown, it looks very good and is very pleasant to use!
I have a weird bug (maybe a feature?). If I bounce between source code and render while writing inline equations, Typora sometimes (seems random..) adds a character prior to the $ of the equation that I copy-paste here: "​" (please note that there is the actual character between the " " but is not an ASCII character so it doesn't print; in Typora it is shown as a red dot). 

To reproduce the bug, I've created a new file, put Typora in source code mode and typed "$f$ " (please note the space after the second $). Then I clicked on the letter f while still being in source code mode, then swap to rendered mode, then I clicked after the space, and switch back to source code mode. Please note this is not the only way to make this character appears, but seems to be the most consistent. 

I hope my description was clear enough!

Thanks :)

**Comment by abnerlee** [comment]
What's your Typora version?

It should be fixed in latest version #403
