### ISSUE TITLE
Escaped backslash erroneously escaping bold double-asterisk markdown first

### ISSUE THREAD

**Issue by dbalbright** [typora/typora-issues#251]
Not 100% on the Markdown spec but one of these is not working correctly and it's Typora not rendering the way I'd expect. Here I've wanted to bold a Windows directory path with the directory backslash they use under Windows at the end to indicate it as such. I also bold these in my documentation. What ends up happening is the backslash that should be escaped at the end by a preceding backslash at the end is instead escaping the first of a double-asterisk which is supposed to bold the string for the file path. Typora seems to be marking up text from the outside towards in. I've attached a screenshot of both Typora and another in Haroopad, another Markdown editor that renders the text as I was expecting. Again, I'm not 100% that what I expect is according to standard.

![2016-08-06 06_53_36-notes md - typora](https://cloud.githubusercontent.com/assets/1958902/17456591/adcce2f8-5ba2-11e6-9782-0b99fc1e32aa.png)

![2016-08-06 06_53_12-untitled edited](https://cloud.githubusercontent.com/assets/1958902/17456592/adcf2cca-5ba2-11e6-84e0-dffdaa581ee2.png)

**Comment by dbalbright** [comment]
I just saw you may have fixed this in the dev version beta 0.9.9.6.2.

> 1. Fix a bug that `**` is not correctly parsed.

Feel free to close if that is the fix for this.

**Comment by abnerlee** [comment]
Fixed in version
