### ISSUE TITLE
Inline images not working when exported to HTML

### ISSUE THREAD

**Issue by Nodragem** [typora/typora-issues#2510]
Hello,

when I type in typora I get exactly the effect I want, i.e. showing my image in line with the text:
![image](https://user-images.githubusercontent.com/10520249/57925671-f4487300-78a0-11e9-9f32-480b610fbb0f.png)

Unfortunately, it does not look the same at all once exported to HTML (here in opera, but same problem in Firefox):
![image](https://user-images.githubusercontent.com/10520249/57925732-2bb71f80-78a1-11e9-9637-68a4ad4ba5a2.png)

Am I doing something wrong?

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by Nodragem** [comment]
yes indeed :)
