### ISSUE TITLE
HDR compatibility

### ISSUE THREAD

**Issue by truefalsename** [typora/typora-issues#2511]
Hi,

when HDR color is turned on in Windows 10, a blank typora page is displayed in gray rather than white, regardless of the specific style used. I tried a bunch of styles with white background, both standard (like the Github one) and custom made, but the issue persists. 

Something similar used to happen on old versions of chrome when displaying a white page (like a google search for instance) and, I believe, in that case was due to the lack of HDR support in the application itself.

Thanks for your help!

**Comment by abnerlee** [comment]
We updated our Electron/Chromium version, which should supports it.

If not working, try #2051 to disable GPU rendering
