### ISSUE TITLE
bug of math expression

### ISSUE THREAD

**Issue by Freakwill** [typora/typora-issues#2513]
It must be a bug for a long time, never fixed in the releases.
If I try to write (or re-edit) an expression such as `$\beta\geq\alpha$`, it will show a wrong (uncompleted or bad latex command) expression even an error such as `beta>=\al`, before I completed it. After I completed it, it shown the right one, but when I jumped out of the dollar symbol, it shown the wrong one.

It bothered me for a long time.

**Comment by abnerlee** [comment]
same with #2504 ?
