### ISSUE TITLE
remote images do not refresh

### ISSUE THREAD

**Issue by MarcusMoeller** [typora/typora-issues#2514]
Hi all.
I have linked some images in my markdown file, pointing to remote URLs. When the images change, typora does not refresh the images.

I have not checked the option to copy images locally, so it should always use the live version of the online images.

Is there a way to force a refresh of the images? It seems that typora is caching them somewhere.

**Comment by abnerlee** [comment]
There are cache so Typora won't fetch images every time. We don't provide force refresh for now since remote images usually don't change. You could try reopen the file to get it refreshed.

**Comment by MarcusMoeller** [comment]
With that you assume that images never refresh, which is somewhat away from reality. Re-open the file does not help. Manually deleting the cache in .config/Typora works of course.

**Comment by colbster** [comment]
I have embedded graphs that I change all the time. I have to close/open the file every time I want to see the updated graph. It is a pain. I would like a better way to refresh images.

**Comment by michaelrshannon** [comment]
Like @colbster, I'm often embedding Lucidchart images, and it's proving challenging to use as changes to the chart do not update in typora - a force refresh would be useful.

@colbster for now, a workaround is to add a dummy url param to the end of the url - e.g. if your image path is `https://domain.com/image.png` and the Typora cache isn't updating, change your MD to point to `https://domain.com/image.png?timestamp=20190830` (anything after the question will work, but this way it's easy to increment the changes without having to think of a new ending each time). Your image server won't do anything with the characters after the `?`, but Typora will think it's a different path and reload the image.

**Comment by colbster** [comment]
I updated Typora to version 0.9.77 (beta), and it automatically updates my embedded images when the source is updated. Thumbs up from me!

**Comment by shu-ming** [comment]
> There are cache so Typora won't fetch images every time. We don't provide force refresh for now since remote images usually don't change. You could try reopen the file to get it refreshed.

where is the cache location on Mac? thank you

**Comment by jonathanhuston** [comment]
> > There are cache so Typora won't fetch images every time. We don't provide force refresh for now since remote images usually don't change. You could try reopen the file to get it refreshed.
> 
> where is the cache location on Mac? thank you

@shu-ming You should be able to delete ~/Library/Caches/abnerworks.Typora/WebKit (after backing it up) and let Typora rebuild the cache from the new data.

**Comment by NielsHolst** [comment]
I have local images referred to as "../media/figure.png". The document does not update the figure when the PNG file changes. I am using Typora 1.5.8 on Windows 10. The only solution is to close down and re-open Typora. Really, why not just add a menu option to refresh the image cache, like you already have a menu option to refresh the math expressions (and that one works!).
@colby-trash Maybe this works only for remote images?

**Comment by colby-thrash** [comment]
@NielsHolst I am also using Typora 1.5.8 on Windows 10. I just double checked to make sure my images are auto updating with a relative path to a local image and it does.. I looked around in my preferences and did not find a setting for auto refreshing, and I don't remember doing anything special for that functionality. 

I did find a setting that looks like it should update images without having to close Typora:  Format > Image > Reload All Images. That isn't as nice as auto updating. Sorry I don't have anything more helpful. I guess you have confirmation that it _should_ work as you are using it.

**Comment by abnerlee** [comment]
>  I just double checked to make sure my images are auto updating with a relative path to a local image and it does.. 

Your images are local, or remote? For workaround, you can try add different get parameters to your images url, like ?xxx to force reload the images

**Comment by colby-thrash** [comment]
@abnerlee My images are local. I have not used remote images with Typora.  My auto-update with local images is working fine. It sounds like I have the same setup as @NielsHolst, so I'm not sure what is going on with theirs.
