### ISSUE TITLE
HTML render border with <kbd> <img> tags

### ISSUE THREAD

**Issue by djovic** [typora/typora-issues#2518]
Greetings,

First, Typora does a fantastic job of rendering like Github, and much thanks for this wonderful tool!

But there is a minor inconsistency. In Github wiki, we use HTML `kbd` tags around `img` tags to render an image with a border:

```html
<kbd><img src="my-image-url.png"></kbd>
```

This solves the problem of better displaying images that have lots of whitespace, without needing to alter them. It would be great if Typora could do the same. Examples below.

#### Github rendering (native)

Markdown image syntax:

![whitespace-img](https://user-images.githubusercontent.com/4742707/58296490-b491f780-7d88-11e9-86dd-c9b80a57f779.png)

HTML image syntax (i.e. `kbd` `img`):

<kbd><img src="https://user-images.githubusercontent.com/4742707/58296490-b491f780-7d88-11e9-86dd-c9b80a57f779.png"></kbd>

#### Typora rendering (screenshots)

HTML image syntax (i.e. `kbd` `img`):

![kbd-img](https://user-images.githubusercontent.com/4742707/58296740-c6c06580-7d89-11e9-9796-f0e093c19005.png)

Same image, but using Github to show outlines:

<kbd><img src="https://user-images.githubusercontent.com/4742707/58296740-c6c06580-7d89-11e9-9796-f0e093c19005.png"></kbd>

**Comment by abnerlee** [comment]
In github `kbd` has `display:inline-block`, you could add it by http://support.typora.io/Add-Custom-CSS

We don't recommend to use `kbd` for bordering since how it looks depends on the default css of your publish platform.

**Comment by djovic** [comment]
That worked perfectly, thank you!
