### ISSUE TITLE
[FEATURE REQUEST] start on windows boot option, close/minimize to tray option, always on top option, invocation/dismiss hotkey option

### ISSUE THREAD

**Issue by jinchoung** [typora/typora-issues#2520]
I just discovered typora and I think I've found my note taker! Srsly, take my money already!

But while note taking for me is an ever present activity, it is usually not an isolated activity or even the focus. Usually, I'm actually focusing on something else.

So i would love to have typora always be available in the background and ready to come forward at any time for me to jump in and jot a quick note then recede again so I can jump back to what I was doing.

To facilitate this workflow, it would be good to have these features:

- an option to start typora on system boot up (would be really fantastic if it could wait until dropbox finishes updating first tho)
- an option to close/minimize to the tray (on windows - i hate inadvertently closing my notes!)
- ~~an option to have the typora window be "always on top" (if i'm working in maya and taking a note on what i'm doing, i usually don't want the note to obscure what i'm doing)~~ nevermind you already have this feature in VIEW menu! Thank you!!!
- an option for a hotkey combo to bring up typora and dismiss it... a WIN KEY + KEY combo would work well

Thanks for an amazing program. Looking forward to purchasing 1.0!

jin

**Comment by abnerlee** [comment]
> an option to start typora on system boot up

I think this can be configured by Windows https://www.howtogeek.com/208224/how-to-add-programs-files-and-folders-to-system-startup-in-windows-8.1/

For others, we currently don't have plans for tray icon and the global hot key (you may try https://medium.com/better-humans/how-to-setup-your-windows-global-hotkeys-in-10-minutes-becc40ff492), they seems too much for an editor.
