### ISSUE TITLE
[FEATURE REQUEST] FILES button in sidebar should toggle between articles and file tree

### ISSUE THREAD

**Issue by jinchoung** [typora/typora-issues#2521]
it's a small quality of life thing but it would make things just a bit faster than to have to navigate to the dropdown menu. and the hotkey shortcut for these switches are a bit of a fingerful.

thanks

jin

**Comment by abnerlee** [comment]
There are button on bottom side in sidebar to toggle between articles and file tree

**Comment by jinchoung** [comment]
oh cool! thanks!
