### ISSUE TITLE
Files didn't immediately open when clicking the sidebar

### ISSUE THREAD

**Issue by AndyChen2005121** [typora/typora-issues#2523]
Similar to #746; doesn't fix after reinstalling.
> Version: macOS, 0.9.9.24.6 (2400)
![ScreenFlow](https://user-images.githubusercontent.com/22784008/58365399-b4b00580-7ef6-11e9-940e-31f66db07c7a.gif)

**Comment by abnerlee** [comment]
possible to send us <hi@typora.io> a sample file that will not be opened immediately after click on side bar?

**Comment by masonlr** [comment]
I'm seeing this same issue on macOS with Version 0.9.9.24.6 (2400).

**Comment by masonlr** [comment]
To reproduce: 

1. Create two files: `first.md` and `second.md`
2. Open Typora from the terminal using

        open -a Typora .

3. Click on `first.md` in the sidebar. (No content appears.)
4. Click on `second.md` in the sidebar. (Content appears.)
4. Click on `first.md` in the sidebar. (Content appears.)

**Comment by masonlr** [comment]
![typora](https://user-images.githubusercontent.com/5828176/58541343-318ef800-81f3-11e9-8dcc-640c91af1d30.gif)

**Comment by AndyChen2005121** [comment]
@abnerlee this bug occurs to ALL FILES, no matter what.

**Comment by abnerlee** [comment]
seems same bug with #2467

**Comment by abnerlee** [comment]
should be fixed in latest version
