### ISSUE TITLE
[Feature Request] ARM Packages for Linux

### ISSUE THREAD

**Issue by jonathanp0** [typora/typora-issues#2524]
Thanks very much for providing Linux packages!

Currently these packages are only for x86 processors. For users on devices like the Raspberry PI or using the Linux container features on ChromeOS, it would be great if ARM binary packages could be made available via the Linux repository.

**Comment by abnerlee** [comment]
we don't support ARM.

**Comment by OneJaredNewman** [comment]
This is a bummer! Typora is my killer app, would love to use on a Pi or the Chromebook Duet that just came out.

**Comment by ColleSerre** [comment]
Don't worry arm users, with the release of the first ARM MacBook typora should support it soon...

**Comment by aredridel** [comment]
Aw, bummer. Just found this while trying to install it on my raspberry pi 400
