### ISSUE TITLE
bag css flow

### ISSUE THREAD

**Issue by ekhristin** [typora/typora-issues#2526]
Good afternoon, colleagues.
First of all I want to thank the developers, a wonderful job!

I want to draw your attention to the fact that the styles in the code highlighting (in the flow mode) do not quite work as I would like.
when drawing large schemes, large spaces appear above and below the work flow
`st=>start: Передача техники сотруднику
e=>end: Выход
op1=>operation: СТП делает цветовую отметку (желтый цвет заливки), 
о резерве техники в файле MOSFR.xls 

cond=>condition: ОС ?      
op2=>operation: СТП оформляет в 1С Предприятие
накладную на передачу техники
М11-ТН 01.01 (ОС)
и распечатывает ее на бумаге
cond0=>condition: ОС выносное?
cond1=>condition: Первичная
выдача?
op3=>operation: СТП оформляет в 1С Предприятие
накладную на передачу техники
М11-ТН 10.09 (ОМ)
и распечатывает ее на бумаге

op0=>operation: СТП оформляет АКТ
передачи во временное пользования
оборудования пренадлежащего организации
на имя сотрудника 

op4=>operation: СТП оформляет в 1С Предприятие
накладную на передачу техники
М11-ТН МЦ-04 (ОМ)
и распечатывает ее на бумаге

op5=>operation: СТП на основе данных из файла MOSFR.xls
производит установку оборудования сотруднику

op6=>operation: СТП осуществяет сбор подписи ответственных лиц по 
накладной на передачу техники
-сотрудник (которому передается техника)
-Начальник подразделения, управления сотрудника
-МОЛ
-Член коммисии (Начальник Управления делами 
в случает отсутствия его роль замещает
Начальник Информационно аналитического управления
cond2=>condition: Накладная подписана всеми сторонами?
cond3=>condition: повторная выдача ОМ?

op7=>operation: СТП помещает оригинал в папку управления,
в котором числиться сотрудник, 
которому выдали технику
op8=>operation: СТП делает копию накладной на передачу техники
и помещает ее в папку управления,
в котором числиться сотрудник, 
которому выдали технику

op9=>operation: СТП передает оригинал накладной 
в Управление Бухгалтерского учета и отчетности

op10=>operation: СТП делает цветовую отметку (синий цвет заливки), 
о выдачи техники в файле MOSFR.xls 
и настраивает связь между сотрудником и техникой 

st->op1->cond
cond(yes)->op2
cond(no)->cond1(top)
cond1(yes)->op3
cond1(no)->op4

op2->cond0
cond0(no)->op5
cond0(yes,right)->op0->op5

op3->op5
op4->op5
op5->op6->cond2
cond2(yes)->cond3
cond2(no)->op6
cond3(no)->op8->op9->op10
cond3(yes)->op7->op10
op10->e`

**Comment by abnerlee** [comment]
#2536

**Comment by ekhristin** [comment]
What ?

**Comment by ekhristin** [comment]
Ок
