### ISSUE TITLE
Support title in image tag

### ISSUE THREAD

**Issue by clemorphy** [typora/typora-issues#2527]
Hi

Markdown is supposed to support titles when inserting images, like this :
`![Alt text](/path/to/img.jpg "Optional title")`

But Typora doesn't allow to have that space before the first double quote, and that space is needed.

**Comment by BaksiLi** [comment]
Just to add a reference to this issue:
https://www.markdownguide.org/basic-syntax/#images-1

Btw I think this is not supported in GitHub Markdown as well (the optional title is just omitted).

**Comment by abnerlee** [comment]
should be fixed in latest version
