### ISSUE TITLE
Repository not available??

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2529]
Abner, my Linux Update Manager has been giving me this message all day today:
```
Failed to fetch https://typora.io/linux/./InRelease  Connection failed [IP: 104.25.140.36 443]Some index files failed to download. They have been ignored, or old ones used instead.
```
A temporary hiccup?

**Comment by abnerlee** [comment]
It's OK in my test https://www.websiteplanet.com/webtools/down-or-not/?DorN=typora.io
Should be a temporary hiccup, is it working now?

**Comment by DutchPete** [comment]
Sorry Abner, there is no change on my side. The message does not actually say the web site is down, so there must be something else going on?

**Comment by DutchPete** [comment]
Abner, you have not replied to my last comment, but I reiterate today, 2019-05-29, that the issue is still there.

**Comment by abnerlee** [comment]
Can you access https://typora.io ?

**Comment by DutchPete** [comment]
> Can you access https://typora.io ?

No, I cannot.

**Comment by abnerlee** [comment]
what does it return ?

**Comment by DutchPete** [comment]
Nothing, the page remains blank.

**Comment by DutchPete** [comment]
2019-05-30: https://typora.io is accessible again, and my Update Manager (Linux) is showing that everything is up-to-date, so it seems everything is hunky-dory again.
