### ISSUE TITLE
Bug on symbol ` in single code fence

### ISSUE THREAD

**Issue by asnahu** [typora/typora-issues#253]
Like title described, when type like below 

> `ctrl+\``

will gernerate

> `ctrl+``

but in fact i want to generate like

> ctrl+`

the output will not be interpreter correctly on several other online markdown editors too.

**Comment by abnerlee** [comment]
In my testing, that is the way what all markdown editors parses inline code.

Should use "<code>&lt;code&gt;ctrl+`&lt;/code&gt;</code>" in this case.
