### ISSUE TITLE
Global Search doesn't found files without content

### ISSUE THREAD

**Issue by myn-user** [typora/typora-issues#2530]
Hi,

I created a new file in Typora, but did not fill it directly with content. It served as a reminder in the first approach.
A little later I searched for the global search for this file, but the search could not find the file.
Even the quick search could not find the file.

I then found the file via Windows search.
When I filled the file with content (headline, etc.) I could also find you through Typora's search.

Is this normal?

**Comment by abnerlee** [comment]
Is it same as #2492 or you only use English in your filename?

**Comment by myn-user** [comment]
I use German in the filename, but without special letters.
I have tested it with English in the filename. It has the same effect.
If there is no content inside the file Typora doesn't show it in the search result.

**Comment by abnerlee** [comment]
should be fixed in latest version
