### ISSUE TITLE
HTML Comment Syntax not supported

### ISSUE THREAD

**Issue by BaksiLi** [typora/typora-issues#2532]
For example:

``` HTML
<!-- Do not display this at the moment
<img border="0" src="pic_trulli.jpg" alt="Trulli">
-->
```

In GitHub rendered as:

⬇️

⬆️

or in one line as:

```
<!-- This section was removed from this document. -->
```

And you might also want it to support rendering of Markdown Syntax within a HTML tag, see #1939.

Regards.

<sub>btw Typora is an excellent app!</sub>

**Comment by abnerlee** [comment]
It is supported. 

We cannot reproduce it, could you provide more details?

**Comment by BaksiLi** [comment]
```
# Main

## I. Programming

<!-- Originally week 0 -->

### Scratch

```

Can you please try the above text?

<img width="646" alt="Screenshot 2019-06-05 at 00 22 15" src="https://user-images.githubusercontent.com/26314680/58919977-14dd4d80-8728-11e9-8181-8a1c5f18f989.png">

**Comment by BaksiLi** [comment]
> It is supported.
> 
> We cannot reproduce it, could you provide more details?
@abnerlee 
The issue is closed. May I ask you to look for the issue **again**?
Regards

**Comment by abnerlee** [comment]
@BaksiLi 

The `<!-- Originally week 0 -->` is supported and rendered, it will hide on export / print.
