### ISSUE TITLE
How to disable 100% emoji in :100: IPv6 formatting?

### ISSUE THREAD

**Issue by sudoranger** [typora/typora-issues#2533]
I'm trying to write an IPv6 which has the following formatting:

xxxx:xxx:xxx:100::xxxx:xxxx

The editor automatically change the :100: into a red-colored 100% emoji. I'd like to know how to disable this. I tried to paste as plain text but that didn't work.

**Comment by abnerlee** [comment]
It's the same behavior as Github.

You could use `xxxx:xxx:xxx:100:xxxx:xxxx`

**Comment by sudoranger** [comment]
I just encountered this same issue. The "workaround" of putting the offending text in a code block works, but the grey background and monospace font isn't always desired, or even acceptable.

It's not like every time you could ever want to have a colon followed by characters followed by another colon is from terminal output or source code or similarly "code block"-ish text; for example, if I wanted to write h:m:s to indicate hours, minutes, and seconds, in non-code text, that would become hms, with no way to escape it.

Your Suggestion:
`1234:100:1234`

However, as for GitHub markdown syntax. It is possible to escape this emoji using the zero width space character. Go to [this website](https://coolsymbol.com/) and scroll all the way to the bottom of the page, you will see a button to copy the Zero-Width Space (ZWSP) Character.

Before:
1234:100:1234

After:
1234:​100:1234

Unfortunately, this can't be done in Typora. Pasting this character did not escape the rendered emoji as you can see from the above example.

**Comment by sudoranger** [comment]
Any words?

**Comment by abnerlee** [comment]
Using Zero-Width Space (ZWSP) Character seems too tricky to escape :emoji:, it shouldn't be used as an acceptable way for syntax escape

**Comment by martzell** [comment]
I have exactly the same `:100:` shown as :100: emoji problem. If I want emojis I insert them as Unicode characters (ctrl cmd space opens the emoji popup on Mac). It would be really helpful to offer a setting to disable this Markdown Extra feature. Before I came here I first looked in the settings and the documentation how to disable this.

**Comment by sudoranger** [comment]
Sadly, they are not going to do anything about it since this issue is still closed and never re-open. I have since migrated to FromScratch and Simplenote. Those are not markdown editors but if you're looking for some simple note-taking apps, that should do it. Other alternatives worth mentioning are GNU Emacs, Remarkable, Haroopad, ReText, UberWriter, Mark My Words, VIM instant markdown plugin, and if you're using Atom, Brackets, Code, or Sublime they have a markdown plugin for those too.
