### ISSUE TITLE
Switching to source mode deletes blank line between HTML and horizontal rule

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2535]
Paste the following in source code mode:

```markdown
<form>
</form>

---
```

Notice the blank line between `</form>` and the `---`.  Switch to WYSIWYG mode, the line is still there.  Switch back to source mode, and the blank line disappears, corrupting the source code.  To keep this from happening, two blank lines appear to be required between a multi-line HTML block and a horizontal rule.

**Comment by abnerlee** [comment]
should be fixed in latest version
