### ISSUE TITLE
Keyboard navigation - Go to Beginning of the line - bug

### ISSUE THREAD

**Issue by kolnogorov** [typora/typora-issues#2537]
When you click CMD+Left (or Ctrl+Left in Windows) to navigate to the beginning of the line, and when cursor is in Heading line (no matter what, any from H1 to H5), the cursor goes to the very beginning of the file, not the line.

I have Version 0.9.9.24.6 (2400) and macOS 10.14.5.

**Comment by hitzhangjie** [comment]
I tried your mentioned case, press CMD+LEFT while put cursor at headings, it move the cursor to he line beginning as expected.
Same typora version and same macOS version.
Not sure what happened.

**Comment by hitzhangjie** [comment]
Oh, maybe it is caused by some CSS problems, can you switch any theme to verify that?
In my memory, something like that happened before.

**Comment by abnerlee** [comment]
Cannot reproduce this.

Possible to provide more details?
