### ISSUE TITLE
Sync Themes or Choose Different Location for Theme Folder

### ISSUE THREAD

**Issue by spencerclrk** [typora/typora-issues#2539]
Right now the themes do not sync since they are in the `~/Library/Application Support/` directory. 

I am able to use a workaround with a "master" synced folder in iCloud (or Dropbox) and then have each machine use [Hazel](https://www.noodlesoft.com/) rules to sync changes into Application Support.

To be most cross-platform friendly, could we have the ability to choose a different Theme Folder?

**Comment by abnerlee** [comment]
#2353
