### ISSUE TITLE
Please provide preference for which Pandoc to use

### ISSUE THREAD

**Issue by johnblommers** [typora/typora-issues#254]
My system has two versions of Pandoc installed, 

Version 1.12.4.2 sits at /opt/local/bin/pandoc and was installed using MacPorts.
Version 1.17.0.2 sits at /usr/local/bin/pandoc and was installed using the Pandoc installer.

Typora complains about the version so I assume it's finding the copy at /opt/local/bin/pandoc which is how I want it because that is how I setup $PATH.

I would like to be able to instruct Typora which version of Pandoc to use.

**Comment by abnerlee** [comment]
I think it is a mirror case that user would have multiple pandoc installed, or they need to configure which pandoc they use, so we do not have to provide an extra option in preference panel.

Typora will use the one at $PATH, run `pandoc --version` on terminal would return the version number of pandoc which typora used. You could upgrade that if its version number is low.
