### ISSUE TITLE
Figure crossref does not work

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#2540]
Hi,

I've been fiddling with crossref in typora but with no luck. 
The crossref for equations works like a charm. However, the crossref for figures and tables does not work at all. I've tried the following:

![A figure about heat diffusion](assets/cell1.png){#fig:heat}
and in main text:  This is figure $\ref{fig:heat}$

also tried
![A figure about heat diffusion $\label{fig:heat}$](assets/cell1.png)
and in main text:  This is figure $\ref{fig:heat}$

In both cases I get a link with ??? error. I wonder if there is a way where these crossref are fixed. It would be also useful if figure number is generated automatically in a similar manner as equations. 

Please help as I am working on a long document with tens of figures. 

Thanks in advance

**Comment by abnerlee** [comment]
#105
