### ISSUE TITLE
Colorful Emoji in exported PDF

### ISSUE THREAD

**Issue by 3andero** [typora/typora-issues#2547]
It seems that emojis in exported pdf aren't colorful, which is different from the typora editor. Is there any possible solution to this?

**Comment by abnerlee** [comment]
What's your OS ?

It should be a upper steam bug of Webkit/Chrome and current PDF spec  https://forums.adobe.com/thread/2564345

**Comment by 3andero** [comment]
I'm using typora on windows 10.

**Comment by 3andero** [comment]
I'm using typora on windows 10.

**Comment by 3andero** [comment]
I'm using typora on windows 10.
