### ISSUE TITLE
Font when editing in-line math

### ISSUE THREAD

**Issue by jiafengkevinchen** [typora/typora-issues#2549]
Small issue. It seems like when editing inline math with `$a^2$`, typora uses the text font to display the LaTeX code. If one initiates block math with double $, typora opens a minieditor with fixed width LaTeX code which is more aesthetically pleasing. It seems that the inline LaTeX should also be displayed in fixed-width font families both for aesthetics and consistency.
![image](https://user-images.githubusercontent.com/24930289/59124001-8b4a9d00-892c-11e9-8f2c-aa9fbd1d12d8.png)

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by jiafengkevinchen** [comment]
Upgraded, but still appears to have the issue

**Comment by abnerlee** [comment]
should be fixed
