### ISSUE TITLE
Double text when using aText

### ISSUE THREAD

**Issue by harper357** [typora/typora-issues#255]
This is kind of a weird bug, but different things happen when you use the text expander, aText, while viewing source code mode vs normal mode. 

It appears to have a problem when aText expands a return key followed by more text. For example, this is what is expanded (and what i expect) when i type while viewing source code mode:   
![source code mode](https://cloud.githubusercontent.com/assets/3394695/17530861/3b02f0c6-5e2e-11e6-9335-fe010aa3e9e0.png)  
When I expend viewing normal mode:  
![normal mode](https://cloud.githubusercontent.com/assets/3394695/17530874/49f942a6-5e2e-11e6-952d-e8847771c5a5.png)  
And the above's source code:  
![normal mode source](https://cloud.githubusercontent.com/assets/3394695/17530881/56fdc080-5e2e-11e6-9f21-e039039fbb1a.png)  

After playing around with it, it seems to be related to how fast the expander is expanding the text, if I put a 0.2-second delay between the return key and the rest of the text, there is no problem.

There is also no problem when I copy and paste the correct expansion while viewing normal mode.

**Comment by abnerlee** [comment]
Should be fixed in new verison

**Comment by AlbertLei** [comment]
I found similar bugs of using Typora with aText. 

## Session info

```
System: 10.15.3 macOS Catalina
Typora version: 0.9.9.33.2 (4442)
aText version: 2.36.1
```

## Bug Description

I defined `;a` as snippet for `*Answer.*` in aText, and it works well in CotEditor and this GitHub input. In Typora, `;a` expands to `;*Answer.*`, with an additional `;` at beginning. This happens for other snippets as well.  

## More info

- If I use `aa` as snippet for `*Answer.*`, it expands to `a*Answer.*`; If `aaa`, then `aa*Answer.*`.  
- I just started using aText snippets this week. I remembered it worked well on Typora before. Have no idea why this bug appears today...

**Comment by AlbertLei** [comment]
Now I know why this bug happens... I use another input method (Sougou) for Chinese, and the bug appears only when I am still under Sougou input. Everything is fine using the mac native input.
