### ISSUE TITLE
Soruce Code Mode render incorrectly when list contains code block

### ISSUE THREAD

**Issue by chalda-pnuzig** [typora/typora-issues#2550]
After add a code block in a list,  the Source Code Mode displayed incorrectly.
Example:

```
- list 
	```bash
	ls -al
	```

```bash
# this is a comment
\```
```
(I add the last escape for showing the accents)

Editor:
![image](https://user-images.githubusercontent.com/16133710/59191391-b11bb000-8b7f-11e9-95d3-5fca34aae0a4.png)

Source code:
![image](https://user-images.githubusercontent.com/16133710/59191376-a234fd80-8b7f-11e9-9534-ff6912e2607d.png)

**Comment by abnerlee** [comment]
merge into #1638
