### ISSUE TITLE
Add code support for graphql language

### ISSUE THREAD

**Issue by maggot99999** [typora/typora-issues#2551]
Currently, it's not supported in any form or type.

The good example of code support https://github.com/prisma/vscode-graphql:

![image](https://user-images.githubusercontent.com/10854805/59193179-859fc200-8b8d-11e9-8818-ee474114bf2f.png)

**Comment by abnerlee** [comment]
We will support languages supported by CodeMirror, so you could watch https://github.com/codemirror/CodeMirror/issues/4455 for any progress

**Comment by yijia-zhan** [comment]
CodeMirror no longer adds any new modes. @abnerlee Would you consider adding GraphQL support with https://github.com/graphql/graphiql/tree/main/packages/codemirror-graphql#readme?

**Comment by Ambro17** [comment]
First of all thanks for this awesome software! I've always edited markdown on vscode but found the experience cumbersome, now with typora the experience is perfect.
I'm writing an article on graphql so i stumbled upon this missing feature. Is there any way we can help adding it into typora? 

Thank you in advance for the awesome work!

**Comment by mikhailpashkov** [comment]
Hi Typora team and @abnerlee in particular!
For the reason @yijia-zhan mentioned, maybe it is possible to reopen this issue?
Thanks!
