### ISSUE TITLE
How do I enter some characters with automatic escaping as they are?

### ISSUE THREAD

**Issue by hjzCy** [typora/typora-issues#2552]
E.g：

`"description"`
"" seem unable become ``

\&lt; ( Automatically converted to < )
Some markdown editors use <xmp>\&lt;<xmp> to solve them, but they can't be solved in typora.

**Comment by abnerlee** [comment]
use `\` for escape, e.g "\&".

It is a bug that the escape is not working. For hot fix, you could
   disable highlight and subscript support in preferences panel
or
  use `&gt;`

**Comment by abnerlee** [comment]
should be fixed in latest version. use `\&` will input an escaped `&`
