### ISSUE TITLE
Find and replace

### ISSUE THREAD

**Issue by pariterre** [typora/typora-issues#2554]
Hi there,

I just found a small bug when using the find and replace function for multiple occurrences. If the replace doesn't have the same amount of letters than the previous word, after replacing the next find is no longer pointing to the right place. 
Note : this doesn't happen when using the replace all function

Thanks for the good work!

**Comment by abnerlee** [comment]
What's your Typora version ?

**Comment by pariterre** [comment]
0.9.70(beta)
Installed on Ubuntu 18.04

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by abrahaofs** [comment]
Problem also present here in 0.9.70(beta) on openSUSE Leap 15.

An addendum is that after typing inside the replace box, the app stops tracking (not highlighting nor finding other matches through the "find next" and "find previous" button) the targeted text that was typed inside the find box. The workaround is everytime after typing inside the replace box I need to come back to the find box and erase and re-type any arbitrary character.

**Comment by harper357** [comment]
I am having this issue on 0.9.9.27.1 (3305) on macOS. 

If I Search a pattern, but then Replace one at a time, the next instance no longer highlighted. The highlight has "moved" over by the difference in the length of the Search and Replace patterns. If my search pattern is longer than the Replace, the highlight is to the right of where it should be.

Maybe the highlights just need to be shifted by this difference after pressing Replace or Search should get re-run when pressing Replace.

**Comment by abnerlee** [comment]
should be fixed now
