### ISSUE TITLE
Unable to export .md File with picture to PDF file

### ISSUE THREAD

**Issue by Williams-Ren** [typora/typora-issues#2556]
I insert several local pictures by the following code:
   <center>
       <img src="E:\9 作业2019\1 Calculus II\1 Math Project\Figures\Original Model of Cross Section.png">
       <br>
       <div style="border-bottom: 1px solid #d9d9d9;
       display: inline-block;
       color: #999;
       padding: 2px;">Figure 1</div>
   </center>
It works well in Typora, but I don't know why when I was trying to export it to PDF, all the pictures dissappeared.
Can anyone help me?

**Comment by abnerlee** [comment]
What's your Typora version?

**Comment by Williams-Ren** [comment]
it's 0.9.70(beta)

**Comment by abnerlee** [comment]
should be fixed in latest version
