### ISSUE TITLE
\newcommand does not auto loaded when open the file

### ISSUE THREAD

**Issue by VicaYang** [typora/typora-issues#2557]
File content
```
$Z[\i]/(2+\i)\sim \Z_5$
$\newcommand{\i}{\mathrm{i}}$
```

Open the file, the command $\i$ is not recognized correctly until I mannualy refresh all math block.
This should be solved by calling refresh all math block after open the file.

BTW, I want to know if there is a way to save my own command (e.g. $\i$ in this example)? Typora support the sugar likes $\R,\Q,\Z$ so I think this should be the same. How about add an item in the config that user can write his own command and auto loaded them when open the file.

I also want to know if there is a chance that I can join the group and maintain/develop typora? I love this software and I want to contribute to it. If there is a chance, what quality should I have?

**Comment by VicaYang** [comment]
Oh I notice that typora use ``conf.user.json'' so how about add an item on it? such as 
```
"macro": [
"\newcommand{\i}{\mathrm{i}}",
"\newcommand{\P}{\mathbb{P}},
],
```
or more simple
"newcommand map": {
    "\i": "\mathrm{i}",
    "\P": "\mathbb{P}",
}

**Comment by abnerlee** [comment]
use
```
$\newcommand{\i}{\mathrm{i}}$
$Z[\i]/(2+\i)\sim \Z_5$
```

First define it, then use it.


For the second post, same with #100
