### ISSUE TITLE
Add ability to auto save 

### ISSUE THREAD

**Issue by NakWarsi** [typora/typora-issues#2558]
It would be awesome if Auto-Save ability is there.

I know this issue has been raised already but being a very frequent user of editors like nodepad++ I don't actually remember to press Ctrl+S and yesterday I lost A lot of precious work so I thought to raise the issue here.

sorry for reopening the existing Issue

**Comment by VicaYang** [comment]
Preference--System--Save&Recover--Auto Save

**Comment by NakWarsi** [comment]
Thank You very much @VicaYang
