### ISSUE TITLE
How to use slash(/) in windows for images?

### ISSUE THREAD

**Issue by enbandari** [typora/typora-issues#2559]
Platform: Window 10
Typora Version: 0.9.70(beta).. the latest so far.

When I drag&drop  or paste an image into typora, it use back slash for image path.

![image](https://user-images.githubusercontent.com/6336960/59414102-7d48c080-8df3-11e9-9321-b3145c986676.png)

How can I change it to the slashes in path?

**Comment by enbandari** [comment]
I noticed #427 but it seems not work in 0.9.70.

**Comment by VicaYang** [comment]
I think typora should use '/' for all systems..
BTW, This is a slash: '/'. This is back slash '\'

**Comment by enbandari** [comment]
Oh ... I corrected my post. Thanks.

**Comment by christophcemper** [comment]
Platform: Window 10
Typora Version: 0.9.70

Same issue. 

I believe this already worked.

We're editing on Windows also, but target platform needs /

I suggest a checkbox 

[X] Always use forward slashes in image references

with default checked on.

**Comment by christophcemper** [comment]
OK, I *confirm* this already worked and had forward slashes always

![image](https://user-images.githubusercontent.com/12080594/59670809-d0888d80-91bc-11e9-9fc1-1c3ba533f1a0.png)

**Comment by enbandari** [comment]
> OK, I confirm this already worked and had forward slashes always

How did you do that? Can I suppose to have the forward slashes always on windows now with version 0.9.70 ?

**Comment by christophcemper** [comment]
> > OK, I confirm this already worked and had forward slashes always
> 
> How did you do that? Can I suppose to have the forward slashes always on windows now with version 0.9.70 ?

No sorry, I meant to say that it did work BEFORE 0.9.70 and is broken now.

The screenshot above is from content I edited a while ago (not sure which typora version that was)

**Comment by enbandari** [comment]
Oh, I see. So I think I could downgrade for this feature and wait for the fix. Thank you! @christophcemper

**Comment by eryajf** [comment]
> 好的，我_确认_这已经奏效并且总是有正斜杠

I would like to ask how your configuration is written, I define the specified path here, if it is /test will report an error, under Windows system

**Comment by abnerlee** [comment]
seems fixed already
