### ISSUE TITLE
highlight the headings on the left panel

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#256]
After update to the newest version, I found new feature which support code format on the headings on the left panel.

![2016-08-11 15 09 39](https://cloud.githubusercontent.com/assets/10832544/17581023/a505b9d8-5fd5-11e6-98ab-fa8686884104.png)

It's really very convenient and more readable, thanks.

Could you please also make highlight(which is `==xxx==`) available on headings on left panel, thanks.

**Comment by abnerlee** [comment]
Fixed already
