### ISSUE TITLE
Two apostrophes break internal links 

### ISSUE THREAD

**Issue by plgorski** [typora/typora-issues#2560]
Using two apostrophes in a header seems to break internal links:

2 apostrophes; will not jump to the header:
```
#### It's a header's test
[Command + Click](#It's a header's test)
```
1 apostrophe; will jump to the header:
```
#### It's a headers test
[Command + Click](#It's a headers test)
```
Version 0.9.9.24.6 (2400), OSX

**Comment by abnerlee** [comment]
should be fixed in latest version
