### ISSUE TITLE
Page break if h1 alone at the bottom of the page (pdf)

### ISSUE THREAD

**Issue by meaz** [typora/typora-issues#2563]
I've found how to add page breaks thanks to this page: [Page-break](https://support.typora.io/Page-Breaks/)

But I have a problem when exporting to pdf: sometime a title, for example h1, can be left alone at the bottom of the page, the rest of the paragraph being found on the following page.
Here is an example:
![page_break](https://user-images.githubusercontent.com/13604424/59548567-82bc1d00-8f51-11e9-905d-64e3b1aed9d8.png)

How could I set the theme .css file so that if a h1 is followed by an image or a text, a page break is added just before h1?

**Comment by abnerlee** [comment]
you could use `page-break-after` (https://www.w3schools.com/cssref/pr_print_pageba.asp)

**Comment by meaz** [comment]
Thanks @abnerlee 
However, adding 
`  h2 {
    page-break-after: avoid;
  }`
didn't fix the problem... Is there a css code that would make a h2 title to get "sticked" to the image or text that follows it so that it doesn't stay separated from it, the h2 being on the bottom of the page, the text or image in the top of the following page?

**Comment by abnerlee** [comment]
`page-break-after` should work, but may not supported yet. 

See https://stackoverflow.com/questions/34808650/orphan-css-how-avoid-headers-h1-h2-on-bottom-page

So current solution would be "add page breaks manually", or export to docx, then print.

Also, Typora will provide more export options / engines in future.
