### ISSUE TITLE
[Bug] AutoSave failed: draftsRecover overflow?

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#2565]
[Typora 0.9.70, Win 1809]

Yesterday, I spent some hours on writing a document in Typora (several pages long). Unfortunately, my Windows system shut down overnight (low battery) so that all processes were terminated. My document was not yet saved but I was sure Typora would have recovered a draft as usual.

Unfortunately, this was not the case. I looked into my draftsRecover folder and found out that the latest recover was created nearly a month ago, despite I have been using Typora every day in the past weeks. For the case this information is relevant, I usually have opened one or several dozens instances of Typora.

Fortunately, I had the idea to run Recuva -- and discovered that several new files in draftsRecover had been deleted.

Does Typora clean up the recovers automatically? I noticed there where exactly 60 recovers in my folder when I started my PC today. As MD files almost never take large memory space, but maybe contain import user data, I would **strictly** dislike any auto-deletion of draft recovers. If at all, you should at least start deleting the oldest instead of the latest files.

I would appreciate some clarification about the supposed implementation (as someone who is not at all familiar with the Typora source), as well as a fix of the unwanted behavior.

**Comment by abnerlee** [comment]
should be fixed in latest version
