### ISSUE TITLE
Load pic always failed

### ISSUE THREAD

**Issue by wintersnow212** [typora/typora-issues#2569]
Hi,
I started to use Typora this year and i really like it in general. But I found the image load functionality is very unstable. It always broke from time to time and caused lot of trouble to me

I tried several ways, like 1) copy to local folder and use that path 2) upload the pic to my github and copy that image.

I almost break every 3-5 days.

I am wondering if i am doing something wrong or it is typo image functionality issue? I really hope this issue can be resolved. BTW, I am using Version 0.9.9.24.6 (2400) on Mac, but I don't think it is version issue because this almost break very version for me even though I update Typora frequently

**Comment by abnerlee** [comment]
To load remote images, Typora should be allowed to access to them, could you provide examples that image load fails.

Also, may cause by other existing issues reported

**Comment by abnerlee** [comment]
should be fixed in new release
