### ISSUE TITLE
about multi tab feature

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#257]
I was wondering is it possible to add multi tab function to Typora, like below:

<img width="777" alt="2016-08-13 22 54 23" src="https://cloud.githubusercontent.com/assets/10832544/17643863/e63c7eb2-61a8-11e6-9281-d33baf3048d3.png">

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/296 https://github.com/typora/typora-issues/issues/638
