### ISSUE TITLE
Collapsible markdown support

### ISSUE THREAD

**Issue by sukhmeet2390** [typora/typora-issues#2570]
Trying to add collapsible elements using summary  for example 

```
## collapsible markdown?

<details><summary>CLICK ME</summary>
<p>

#### yes, even hidden code blocks!

python
print("hello world!")


</p>
</details>
```

This should ideally make the it collapsible, instead it starts renders the <html> code format. 
Allowing nested formatting should ideally do the trick . 

Sample code block : https://gist.githubusercontent.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f/raw/f774f242feff6bae4a5be7d6c71aa5df2e3fcb0e/README.md

**Comment by abnerlee** [comment]
duplicate with #1581

blocked by #1939
