### ISSUE TITLE
Copy image and automatically change the name of the image

### ISSUE THREAD

**Issue by rk-development** [typora/typora-issues#2577]
Hello,

I am looking for an ability to change the name of the copied online image from original to random hash and being able to set certain amount of characters while renaming. 

For instance when i copy `https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png` it will be copied to the local folder as desired, in my case `.\.mda\googlelogo_color_272x92dp.png`

Everything works perfectly fine, however i would like to achieve change name of the file to random hash mentioned earlier, so the outcome of the copied file would be `.\.mda\XeA6AJTIf9EiZPeqbMXC.png` for 20 chars hash.

Is it possible at all? and if not can it be considered in next updates?

**Comment by abnerlee** [comment]
I will merge into #2612

There are two many naming rules, combination of random number, hash, date, time, etc. Different users want different type of naming rules, so #2612 seems meet all requirements
