### ISSUE TITLE
The exported image is not fully displayed.

### ISSUE THREAD

**Issue by Wcraft233** [typora/typora-issues#2578]
My English is not good, the following content is translated from Chinese by google

When I tried to export an article as an image, I found that the exported image was not all articles. This means that the picture is truncated at the wrong location. Below is an example.
The end of the file should be:
![image](https://user-images.githubusercontent.com/30252123/59860468-743a8f00-93b1-11e9-9057-3ec159bc445a.png)
The end of the exported image:
![image](https://user-images.githubusercontent.com/30252123/59860441-6127bf00-93b1-11e9-8f8c-54f07771c0a6.png)
Original article：
[Original article.zip](https://github.com/typora/typora-issues/files/3311036/Original.article.zip)

OS：Windows 10 1809
typora version：0.9.70

====================
原文
当我尝试将一篇文章导出为image时发现，导出的image并非全部文章。也就是说图片在错误的位置被截断。下面是一个例子。
应该的文件结尾：
![image](https://user-images.githubusercontent.com/30252123/59860468-743a8f00-93b1-11e9-9057-3ec159bc445a.png)
导出的image的结尾：
![image](https://user-images.githubusercontent.com/30252123/59860441-6127bf00-93b1-11e9-8f8c-54f07771c0a6.png)
原始文章：
[Original article.zip](https://github.com/typora/typora-issues/files/3311036/Original.article.zip)

**Comment by abnerlee** [comment]
similar / duplicate with #2422 ?
