### ISSUE TITLE
List Colors when exporting not respected -- Linux

### ISSUE THREAD

**Issue by cosmeao** [typora/typora-issues#2579]
I have the latest version of Typora on Mac and Linux (Ubuntu). On Mac, when exporting, the theme is respected and the bullet is its own color (let's say red) and the text is another (let's say black). However, using the same theme on Linux, when exporting, the bullet and bullet-text are both a single color (let's say red). Is this an issue with Linux?

**Comment by abnerlee** [comment]
which theme do you use?

It may related to the CSS selector
