### ISSUE TITLE
Feature Request - Having a Default Print/Export Theme

### ISSUE THREAD

**Issue by cosmeochoa** [typora/typora-issues#2580]
First, thank you so much for all the work. Typora is great! It has all the features my previous editor did not, ahem ... Bear. As a coder and researcher, built in LaTeX, tables, and custom themes is all amazing!

Now, I noticed it has been brought up before but I was unaware it was a possibility until I installed Typora on my Linux distribution. While using my usual dark theme, I was prompted to select a "light" theme or use the default to export my document. I was hoping this could be an option in the Preferences menu, it would be awesome!

This would be ideal since most of us prefer to write on a dark theme but need to export using a light theme. While I understand that you can switch themes before exporting, this is one additional step that could be avoided with such a feature. Thanks and keep up the great work!

**Comment by abnerlee** [comment]
#2125
