### ISSUE TITLE
[Feature request] Check box to exclude folder names from the file list

### ISSUE THREAD

**Issue by tenbob** [typora/typora-issues#2582]
Thanks - v0.9.71 allows you to sort the file list in decending or ascending order as requested [here](https://github.com/typora/typora-issues/issues/1680?_pjax=%23js-repo-pjax-container#issue-350426993). This is great because I name my files by date and I can now bring the most recent ones to the top. But there's still a snag. They are not **right** at the top because all the subfolder names are above them. So the files I want to access are usually off the screen. 

The folder names are mostly irrelevant anyway. They just contain the image assets belonging to various other files.

My suggestion is to have an extra check box near the sorting buttons to show/exclude folder names from the file list.

**Comment by abnerlee** [comment]
duplicate with #1753
