### ISSUE TITLE
create new file could  do nothing

### ISSUE THREAD

**Issue by DHclly** [typora/typora-issues#2584]
- Typora on Windows 10
- version 0.9.71(beta)

today , I update the typora to newest . then I found when I create a new file , I can not rename this file , the input box is always show , and I can not type anything in md file。I need to reopen typora , then  is ok . but I create another file , it still can not rename , and write anything.

![image](https://user-images.githubusercontent.com/11781439/59891995-eb037680-9409-11e9-9b11-58df37d714d2.png)

**Comment by abnerlee** [comment]
caused by https://github.com/electron/electron/issues/18646

We just released a fixed version
