### ISSUE TITLE
Environment "aligned" prevent numbering with auto numbering enabled

### ISSUE THREAD

**Issue by didGIT2018** [typora/typora-issues#2587]
I've enabled AUTO NUMBERING MATH EQUATION
but auto numbering doesn't work

I'm using Typora  Version 0.9.9.25.2 (2727) on MACOS SIERRA 10.12.6

**Comment by abnerlee** [comment]
Some options would get applied on new window or after restart, have you try that?

**Comment by noisyoscillator** [comment]
I have a similar issue. With auto-numbering enabled, for example, multiline latex expressions  doesn't output any equation numbers. 

$$
\begin{align*}
y = y(x,t) &= A e^{i\theta} \\
&= A (\cos \theta + i \sin \theta) \\
&= A (\cos(kx - \omega t) + i \sin(kx - \omega t)) \\
&= A\cos(kx - \omega t) + i A\sin(kx - \omega t)  \\
&= A\cos \Big(\frac{2\pi}{\lambda}x - \frac{2\pi v}{\lambda} t \Big) + i A\sin \Big(\frac{2\pi}{\lambda}x - \frac{2\pi v}{\lambda} t \Big)  \\
&= A\cos \frac{2\pi}{\lambda} (x - v t) + i A\sin \frac{2\pi}{\lambda} (x - v t)
\end{align*}
$$

doesn't get autonumbered. Ideally what is needed is a single equation number for the whole math block.

On the other hand 
$$
x+1\over\sqrt{1-x^2}
$$
 does output the equation number?

Any idea where I am going wrong ?

While

**Comment by abnerlee** [comment]
https://github.com/mathjax/MathJax/issues/1811

**Comment by stevenchen521** [comment]
Auto numbering works with tag "align". But it's not working under align* and aligned mode. 
Version 0.9.9.29.1 (3563) in Mac OS 10.15

**Comment by abnerlee** [comment]
relates #3388

**Comment by abnerlee** [comment]
`\begin{align*}` will not be auto numbered while `\begin{align}` will.
see http://docs.mathjax.org/en/latest/input/tex/eqnumbers.html?highlight=auto%20numbering

Also fixed in new release
