### ISSUE TITLE
"Find Next" searches from the top instead of current cursor position in 0.9.72

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2589]
This appears to be a regression since 0.9.70?

**Comment by pjeby** [comment]
Also, shift-F3 (i.e. find previous) begins at the first match now, too, instead of at the cursor position.

In source code mode, find next and previous *almost* work correctly: when you hit the keys for them, they initially select nothing, and then a second keystroke will do what it should've done in the first place (i.e., gone to the next or previous match.

**Comment by abnerlee** [comment]
@pjeby You trigger "Find Next" by enter key or mouse click or by other shortcuts?

**Comment by pjeby** [comment]
F3 and Shift-F3; I also tried using the menu.  To be clear, this is when activating these functions without the search bar currently visible.  That is, just clicking someplace in the document and trying to search forward or back, e.g. when making changes to surrounding text that can't be done with search + replace, so I'm trying to search, edit nearby, then find the next occurrence, and trying to search again jumps back to the first match in the document instead of going to the actual next match.

**Comment by vassudanagunta** [comment]
@abnerlee This is also an issue on the Mac. Search disregards current cursor position, unlike every other text and code editor I've used. @pjeby is correct that this bug was introduced not recently but a while back.  

> so I'm trying to search, edit nearby, then find the next occurrence, and trying to search again jumps back to the first match in the document instead of going to the actual next match.

The behavior is worse on the Mac. You can't even resume search at all. #2591

**Comment by abnerlee** [comment]
should be fixed
