### ISSUE TITLE
Find and Replace fails to resume previous search 

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#2591]
Repro:

1. `⌘F`, type a word that appears multiple times in the doc.
   
   The first occurrence from the top is highlighted, disregarding the cursor position (as already reported in #2589)

2. `⌘G`

   The next occurrence is highlighted. Repeated ⌘G correctly cycles through all occurrences endlessly.

3. Click within the doc (e.g. you want to edit one of the occurrences).

4. `⌘G` to resume the search to review/edit the next occurrence.

   **FAILURE**: Typora does not proceed to the next occurrence. The search bar reappears, and the previous search term is still there, but no amount of ⌘G or ⌘F will do anything.
   
   The text in the search bar is highlighted and has focus, so you can replace it without using the mouse (good), but even changing it will not cause search to work. 

   **The only way to get search to work again is to manually click in the search bar, and change at least one character.**

I consider this a serious bug as this is a common usage pattern when making edits in a document. This has been a bug for a while, introduced before the last version (sorry I've been too busy to report it).

**Comment by abnerlee** [comment]
should be fixed
