### ISSUE TITLE
HTML export filled with extra code, especially anchors

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#2593]
I'm guessing this comes from the 0.9.9.25 update, "Use readable anchor link on exported HTML."

Previously, copying plain HTML would give me, well, plain HTML. Now, though, the code is filled with all sorts of extraneous stuff.

Before:
`<h3>Here is my headline</h3>`

Now:
`<h3><a class="md-header-anchor md-print-anchor" href="af://n34" name="header-n34"> </a>Here is my headline</h3>`

Is this intentional? If not, it's a bug. :) If so, is there a setting to turn it off so I can have 'clean' HTML export again?

Thanks!

**Comment by chad-bennett** [comment]
i'm noticing the same problem too. the pattern i'm noticing is that almost every element is wrapped in a span. 

`<p><span>This is text</span><strong><span>strong text</span></strong><span> and that is lot of random spans that I don't need.</span></p>`

running 0.9.72 on windows

**Comment by xebico** [comment]
(whew) Glad Abner labeled this as a bug. I was worried it was an intentional feature, and I use "copy plain HTML" all the time!

**Comment by pjeby** [comment]
Having the same problem.  span span spannity span.  Plus all sorts of other extraneous attributes.  I used to be able to use copy as HTML for a quick export, but no longer.  There are also a bunch of other attributes being added to things, for example an `iframe` ended up with a bunch of things like `allow-forms="false"`.  Doing an HTML export without styles dumps the same things in the export, so now there is *no* way to get a clean HTML export without using another conversion tool.  :-(

**Comment by xebico** [comment]
Just FYI, still occurring with 0.9.73, which I got on 6 August. (I'm not seeing all the "extraneous attributes" pjeby mentioned anymore, just span span span eggs and span.)

**Comment by tig567899** [comment]
I originally reported the internal links being broken on HTML w/o styles in issue #2409, and while I'm glad those are in, I've also noticed that attaching the styles to the HTML w/o styles has no margins. Not sure if it has anything to do with this issue, just my 2 cents.

**Comment by abnerlee** [comment]
should be fixed
