### ISSUE TITLE
Copy mathjax and paste auto add $ or $$

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2595]
When copy rich txt from web.
The pic, the title, the table, is automaticly handled. 
But the mathjax is still not handled. now i can only render as plain src, then add $ manually. 
Hope typora could handle it automaticly, in sentence add $, in single line add $$.

**Comment by lumingdong** [comment]
I need "$...$" and "$$...$$" for the rendering of mathjax.js too, except that I need to appear in the export to HTML(without styles). 
@abnerlee Just need to display "$...$" and "$$...$$"  when copy or export  asHTML(without styles) like:
`<p>Jaccard相似度：</p>
<p>$$w_{uv}=\frac{|N(u) \bigcap N(v)|}{|N(u)\bigcup N(v)|}$$</p>
<p>其中$N(u)$表示用户 $u$ 购买物品的数量， $N(v)$表示用户 $v$ 购买物品的数量，$N(u) \bigcap N(v)$ 表示用户 $u$ 和 $v$ 购买相同物品的数量。</p>`

Now maybe add some options for this:
https://github.com/typora/typora-issues/issues/2638#issue-465593209

**Comment by lumingdong** [comment]
I need "$...$" and "$$...$$" for the rendering of mathjax.js too, except that I need to appear in the export to HTML(without styles).
@abnerlee Just need to display "$...$" and "$$...$$" when copy or export asHTML(without styles) like:
```html
<p>Jaccard相似度：</p>
<p>$$w_{uv}=\frac{|N(u) \bigcap N(v)|}{|N(u)\bigcup N(v)|}$$</p>
<p>其中$N(u)$表示用户 $u$ 购买物品的数量， $N(v)$表示用户 $v$ 购买物品的数量，$N(u) \bigcap N(v)$ 表示用户 $u$ 和 $v$ 购买相同物品的数量。</p>
```
Now maybe add some options for this:

**Comment by abnerlee** [comment]
Cannot get source from compiled MathJax / LaTeX output
