### ISSUE TITLE
Request to integrate viz.js to bypass mermaid hidpi issues

### ISSUE THREAD

**Issue by ProgramFan** [typora/typora-issues#2596]
Mermaid is known to render graphs incorrectly on HIDPI screen while its rendering of sequence diagrams and gantt charts are OK. Since these issues remain open for over a year and there seems no chance of fix them the near future, I suggest typora integrate [viz.js](http://viz-js.com/) to support graphviz.

References:
1. https://github.com/typora/typora-issues/issues/1661
2. https://github.com/knsv/mermaid/issues/645
3. https://github.com/knsv/mermaid/issues/651

**Comment by abnerlee** [comment]
#1138
