### ISSUE TITLE
could you add shortcut keys for renaming file and deleting one or multi table rows? 

### ISSUE THREAD

**Issue by jevislee** [typora/typora-issues#2598]
thanks

**Comment by abnerlee** [comment]
> deleting one or multi table rows

This is duplicate

> renaming file

http://support.typora.io/Shortcut-Keys/

**Comment by benlc** [comment]
Hey @abnerlee, I wasn't able to find an open issue for a file delete hotkey. Not sure if this is possible right now (?) and it doesn't seem to be listed here: https://support.typora.io/Shortcut-Keys/ . Would you be able to point me to the issue # or right documentation?

Thanks

**Comment by abnerlee** [comment]
@benlc It's current not support. 
Do you mean delete current file or delete file on sidebar?

**Comment by benlc** [comment]
Either would be great really
