### ISSUE TITLE
[Request] Typing Sounds

### ISSUE THREAD

**Issue by yadhu** [typora/typora-issues#260]
Typora is the best minimal writing tool. I think it will be a cool feature if there is a typing sound as we type. It will give the writers a sense of working on a real writing machine. We can use sounds from [freesound.org](http://www.freesound.org/people/lonemonk/sounds/53753/)

**Comment by abnerlee** [comment]
You could use 3rd party tool for typing sounds.  

Currently we do not have such plan.
