### ISSUE TITLE
Typora not working with Quick Cursor

### ISSUE THREAD

**Issue by philipgoyal** [typora/typora-issues#2602]
I have set up Typora to work with the application Quick Cursor [1].  This application works by allowing text that is currently being editing in one application (e.g. Mail) to be edited in an editor of ones choice.  

I have set up Typora so that it's available in Quick Cursor's list of editors.  However, although it *receives* text, it does not send anything back to the initial app once its text-editing window is closed.  I've checked this behavior with two different initial apps (Mail and Agenda); I've also checked that Byword (as a text-editor) *does* still behave correctly.

Could you adjust Typora to fix this problem?

Notes:
[1] Quick Cursor is no longer being actively developed (by the developer Jesse Grosjean; jesse@hogbaysoftware.com), but still works fine in Mojave with other editors such as TextWrangler & Byword.

**Comment by abnerlee** [comment]
#2600
