### ISSUE TITLE
Why are you planning to make it a proprietary software in the future ?

### ISSUE THREAD

**Issue by cata0309** [typora/typora-issues#2604]
( I saw free during beta ) How do you give back to the community that opens issues, to the people that help you make Typora better ? I think you might want to make it open source, it would speed up the development process and make it easier, of course.
Open a patreon page or go for Github Sponsors program

**Comment by AlexPasternak** [comment]
This is really redundant and duplicate. Can you please check & use existing threads for this, and stop making top level issues that clutter up and hide actual issues that need to be addressed with the product?
