### ISSUE TITLE
Incorrect Image URL Fragment Identifier Handling (Useful for CSS Image Styling)

### ISSUE THREAD

**Issue by Ziflin** [typora/typora-issues#2605]
In order to style images from markdown, it's helpful to have the URL fragment identifier work properly in Typora. Such as this markdown:
```
![](/images/image.jpg#thumbnail)
```
Typora unfortunately seems to treat the `#` as part of the image filename which breaks the display of the actual image. Using the query operator `?` seems to parse and display properly, so hopefully this is a simple change. I did verify that using `#` parses properly in VS Code and a few other Markdown editors/renderers. **Note:** It does appear that this works property with src URLs that start with `http` or `https` just not relative/local ones.

The idea is then to be able to write a css selector to style the image:
```css
img[src*="#thumbnail"] {
    width:100px;
    height:100px;
}
```

It is apparently also possible to include spaces in the fragment identifier, such that this markdown:
```
![](/images/image.jpg# styleone styletwo)
```

Can be matched in css by both of these selectors (using the `~=` selector):

```css
img[src~="styleone"] { ... }
img[src~="styletwo"] { ... }
```

... which is even more useful.

OS: Windows 10
Typora Version: 0.9.72

**Comment by abnerlee** [comment]
This should be done by #2442 or #249

Currently resize or style is possible by `<img style="**" >` tag

**Comment by abnerlee** [comment]
should be fixed about the "#" in image
