### ISSUE TITLE
Inline Math Block Incorrect Behavior

### ISSUE THREAD

**Issue by Ziflin** [typora/typora-issues#2607]
After enabling Inline Math $...$ processing and restarting, I noticed that my document, which happened to discuss US prices for several things, now rendered incorrectly in Typora. As a simple test, the following is incorrectly handled:
```
This costs $5.21 and that costs $1.23.
```
Typora treats the span between the $'s as a math equation. It was my understanding that inline math blocks were supposed to be ignored if a space was encountered inside them _or_ if there was _not_ a space on the outside of the $'s. Either of these checks would have prevented the above example from being treated as an equation, so I'm assuming this is a bug?

OS: Windows 10
Typora Version: 0.9.72

**Comment by abnerlee** [comment]
Inline math does not ignore whitespace.

You could turn off inline math or use escape `\$`

**Comment by Ziflin** [comment]
Having to turn off the option breaks the compatibility of sharing various Markdown documents if I have to tell coworkers which files should be opened with which options. The `\$` works, but in a document with 20-30 dollar amounts and a few equations this gets annoying very quickly. 

Pandoc claims to require math to follow (https://pandoc.org/MANUAL.html#math):

> Anything between two $ characters will be treated as TeX math. The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, $20,000 and $30,000 **won’t** parse as math.

Which seems to fix this exact issue. It would be nice if Typora would follow a similar convention to allow this to work this way.
