### ISSUE TITLE
Using HTML tags results in glitch where /tag>/tag>/tag>... is inserted whenever character typed

### ISSUE THREAD

**Issue by mitaylor** [typora/typora-issues#2608]
If I type something like \<font color="blue"\> and try to write text before placing the final \</font\> a glitch occurs after the first character is typed where /font> is repeatedly inserted for every subsequent character typed. See example below.

> \<font color="blue"\>k/font\>/font\>/font\>/font\>/font\>/font\>/font\>

This includes trying to go back (e.g. moving the cursor to right after the 'k') to put a closing \< symbol to close the tag.

I assume it is supposed to be some sort of autocomplete to close HTML tags that is currently a bit glitchy. Thanks for any help.

Note: problem does not occur consistently.

**Comment by abnerlee** [comment]
Does this exists on newer versions and how to reproduce it?
