### ISSUE TITLE
export to image doesn't work  0.9.9.25.3

### ISSUE THREAD

**Issue by TinyDurk** [typora/typora-issues#2609]
when I export md to image, it doesn't work.

Version: 0.9.9.25.3
Env: Mac
op: File -> Export -> Image

There is a dialog to ask me where I want to save. But no image in the target dir after I click "save".

**Comment by abnerlee** [comment]
#2590

**Comment by liuliuwen** [comment]
> when I export md to image, it doesn't work.
> 
> Version: 0.9.9.25.3
> Env: Mac
> op: File -> Export -> Image
> 
> There is a dialog to ask me where I want to save. But no image in the target dir after I click "save".

I have the same problem as you.
