### ISSUE TITLE
Feature Request: nested todo lists parent child interaction

### ISSUE THREAD

**Issue by maxpaulus43** [typora/typora-issues#2611]
I think it would be AMAZING if when I make a nested todo list, the parent todo item would automatically get checked when all of it's children are checked. And vice versa; when the parent todo item is checked, all of it's children are checked.

example: here I have a list of food items which I might need for camping
<img width="190" alt="Screen Shot 2019-06-29 at 1 41 09 PM" src="https://user-images.githubusercontent.com/4512696/60389265-bb8ce380-9a73-11e9-9aff-d3acfe6a9f87.png">

If I i click on 'fruits' OR 'food for 3+ days', the whole list will become checked because all the children and grandchildren are checked. Like so:
<img width="186" alt="Screen Shot 2019-06-29 at 1 41 19 PM" src="https://user-images.githubusercontent.com/4512696/60389283-e2e3b080-9a73-11e9-9a41-01bcdc88190b.png">

**Comment by abnerlee** [comment]
We will consider it if more users reports similar requests.
