### ISSUE TITLE
Auto read when external change

### ISSUE THREAD

**Issue by QzCurious** [typora/typora-issues#2614]
Update to 0.9.72-1
Previously (I'm sorry I don't know the version), Typora sliently **auto read** updated content from disk if it has no unsaved content (even no focus). But now, same condition, Typora remain the content and may try to **autosave**. This action is unwanted if I'm switching between git branch.

Please at least make an option for **auto read**.

------------------

OS: 5.1.4-1-MANJARO
Typora version: 0.9.72-1

**Comment by abnerlee** [comment]
#2600
