### ISSUE TITLE
How to colour text

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2619]
This syntax `<span style='color:blue'>BLUE</span>` now requires one to select a language. Not being a coder myself, which language should I select form the drop-down?
GandalfSaxe said to select HTML, but that does not work.

BTW, my OS is Linux Mint 19.1 XFCE

**Comment by DutchPete** [comment]
Abner, can you help me with this issue please?

**Comment by abnerlee** [comment]
If it is a code block, then language select is needed, if it is just HTML, no language select is needed. If you paste content into Typora, please check if you are pasting plain texts or texts wrapped by a code block.

So paste as plain text or type "<span style='color:blue'>BLUE</span>" would work

**Comment by DutchPete** [comment]
OK, clear. Thanks.
