### ISSUE TITLE
How to display recently files with full path on the Docker icon

### ISSUE THREAD

**Issue by ElfSundae** [typora/typora-issues#262]
![qq20160817-0](https://cloud.githubusercontent.com/assets/526008/17730390/15ae7e58-649b-11e6-8295-0c0f7b78a893.png)

From the relative paths, I can not point out which file should be opened.

**Comment by abnerlee** [comment]
This is macOS's default behavior. Maybe difficult to change on our side. I would suggest to report this to Apple
