### ISSUE TITLE
Linux Binary is no longer ELF 64-bit LSB executable

### ISSUE THREAD

**Issue by MarcusMoeller** [typora/typora-issues#2620]
In the 5.0.4 Linux binary package, the Typora application is no longer flagged as ELF 64-bit LSB executable but as Typora: ELF 64-bit LSB shared object. This prevents it from being opened with a filemanager like Thunar.

In version v3.0.14 this was still the case. Not sure about the in-between releases, though.

```
file Typora
Typora: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d9438ec2c1cafc3dd48f1e59462c19e0e21b5a0a, stripped
```

**Comment by MarcusMoeller** [comment]
Old version was:

```
file Typora
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
```

**Comment by abnerlee** [comment]
It is still a executable file, it is a bug of file managers.
See https://github.com/electron/electron/issues/15406
See https://stackoverflow.com/a/55064060 for short answer.

**Comment by dddfddrf8** [comment]
Hh
