### ISSUE TITLE
Global Search doesn't see # (hashtags)

### ISSUE THREAD

**Issue by adamhemzal** [typora/typora-issues#2621]
I use hashtags (for example: #job) for tagging my markdown. But when I try a global search to quickly find my tags Typora couldn't find any hashtags... However if I use @ symbol (for example: @job) it works. For better understanding, take a look at screenshots. 

I use Windows 8.1 and Typora 0.9.72 (beta)

Thank you for this awesome software

![typora-hashtag](https://user-images.githubusercontent.com/22219315/60490936-d9db2500-9ca7-11e9-945f-a78b8fbcb619.jpg)
![typora-hastag-2](https://user-images.githubusercontent.com/22219315/60490937-d9db2500-9ca7-11e9-872b-76dbabc8d0db.jpg)
![typora-hastag-3](https://user-images.githubusercontent.com/22219315/60490938-d9db2500-9ca7-11e9-9dff-10ef3fee5a17.jpg)

**Comment by myn-user** [comment]
Unfortunately, the "#" symbol is not the only symbol not found by the global search. 
For example, these characters are also ignored: *? + - [
Strangely, you could search for it in one of the previous versions.
For example, I searched for open tasks using "- [ ]".

I use Windows 10 and Typora 0.9.72 (beta)

**Comment by abnerlee** [comment]
should be fixed
