### ISSUE TITLE
Can't Navigate Down with Cursor Keys with Scaled Images

### ISSUE THREAD

**Issue by Ziflin** [typora/typora-issues#2624]
Our website articles contain quite a few images, so we tend to place two together on one row. I was able to do this in Typora with a simple custom style sheet:

``` css
img[src*="?half"] {
    width: 50%;
}
```
And then "tag" two images that should be half-width as:
`![](/article-images/test/flower-1.jpg?half)![](/article-images/test/flower-1.jpg?half)`

This looks correct at first as you can see in the recording, but I am unable to use the down-arrow on the keyboard to move through the article. When it reaches the second image and I press down, the cursor jumps back to the top of the page which makes Typora unusable for us. The image tag is also a bit of a problem when the right-image is selected.

I'm not sure if there is a better way to do this _without_ resorting to html and still have image previews work.

Also note that having to use "?" instead of "#" is not ideal and is due to another bug: #2605

![TyporaImageBug](https://user-images.githubusercontent.com/5809860/60605973-796fe480-9d88-11e9-8113-c2fab1467243.gif)

**Comment by abnerlee** [comment]
This should be covered by #1164 #2442
