### ISSUE TITLE
Download .deb package for testing in other distros

### ISSUE THREAD

**Issue by KorraHarraway** [typora/typora-issues#2625]
Hi,

I'm using Typora from the tar ball for Months and I have found some issues.
So, I would like to download the .deb from my distro for conversion testing in order to build a proper .rpm package and test Typora with system level installation in the same way it is installed from the .deb. (The .rpm unofficial RPM project advertised here is simply not working) 

However, I was unable to access the repository, but from a debian based distro.

**Comment by abnerlee** [comment]
The path is available on http://typora.io/linux/Packages last section is the most updated version

Homepage + Filename is the final URL.

Or use the binary file from http://support.typora.io/Typora-on-Linux/
