### ISSUE TITLE
[Ubuntu 14.04 ] typora: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by typora)

### ISSUE THREAD

**Issue by mengtrue** [typora/typora-issues#2626]
I follow Typora site guide to install typora, but on my Ubuntu 14.04, it shows:
[Ubuntu 14.04 ] typora: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by typora)

My ubuntu 14.04 libdbus-1-3 is 1.6.18 and /lib/x86_64-linux-gnu/libdbus-1.so.3.7.6
I think its version is ok.
Plz hlep me. Thanks.

**Comment by abnerlee** [comment]
upper stream bug of https://github.com/electron/electron/issues/16364

workaround is https://github.com/electron/electron/issues/16364#issuecomment-492199424
