### ISSUE TITLE
Missing "Indent first line of paragraph" option

### ISSUE THREAD

**Issue by razjel** [typora/typora-issues#2628]
I see in some old issues that this option is implemented (f.e update note from version 0.9.9.17 (0.9.54) "Fix rendering bugs when Indent first line of paragraph is enabled.") but I can't find it in application. Neither in options nor in advanced settings. It would be lovely to be able to disable it.

system: Win 10
typora: 0.9.72 (beta)

**Comment by abnerlee** [comment]
It's now under `view` menu
