### ISSUE TITLE
refresh math expressions after launch 

### ISSUE THREAD

**Issue by truefalsename** [typora/typora-issues#2629]
Hello,

I am currently on the latest version of typora and on the latest version of Windows 10. I noticed that when I open files with custom latex definitions I need to refresh math expressions via the menu in order for all custom expressions (both in $ and $$ environments) to be properly displayed.

If I don't do that, my custom commands are simply rendered in red and are not evaluated.

Would it be possible to add an option in the preferences to force the refresh of all math objects after a md file is opened?

**Comment by abnerlee** [comment]
MathJax would parse math expressions in order, so have you try put the definition of custom commands before their reference?

**Comment by truefalsename** [comment]
Hello,




Yes, the definitions are always preceding the relative references. At the beginning of each document I create a $$ block and define everything there. 




From: AbnerLee


Sent: Wednesday, July 10, 5:11 PM


Subject: Re: [typora/typora-issues] refresh math expressions after launch  (#2629)


To: typora/typora-issues


Cc: L, Author






MathJax would parse math expressions in order, so have you try put the definition of custom commands before their reference?

**Comment by truefalsename** [comment]
One more clue: custom expression are not rendered properly on opening a document, but their previews (the pullouts that comes out after clicking on an equation) instead are. In spite of that, the equation remain not processed also after I have clicked somewhere else. Only refreshing math expression (or editing them) helps.

**Comment by abnerlee** [comment]
@truefalsename possible to send us one sample file <hi@typora.io> ?

**Comment by truefalsename** [comment]
well, since a couple of days I can't reproduce the issue anymore. I don't think I updated typora, so I have no idea about what was going on. Thanks though, should it happen again I'll append here a sample file.
