### ISSUE TITLE
Export One Page Pdf [ Disable Page Break ]

### ISSUE THREAD

**Issue by NothingFaceX** [typora/typora-issues#2630]
Hi , How can I export my article in just one page pdf like html ?
I tried to use :
```@media print  
{
  * {
    page-break-before: avoid !important;
	page-break-inside : avoid !important;
	page-break-after  : avoid !important;
  }
}```

But no change ....

Is it possible ?

**Comment by chirsz-ever** [comment]
The editor will transform your css code to
```css
break-before: avoid-page !important;
break-inside : avoid-page !important;
break-after  : avoid-page !important;
```
You could learn these properties [here](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Fragmentation).
But these properties is not supported well by chrome, so these code don't work.
 I think it possiblely a sick design of pandoc.

**Comment by abnerlee** [comment]
merge into #998
