### ISSUE TITLE
Nested code renders as a resizable code-block

### ISSUE THREAD

**Issue by chrispetrou** [typora/typora-issues#2631]
Hi! While working on a past jekyll project, I observed that in the parts of nested code-blocks e.g. like the one shown below:

![1](https://user-images.githubusercontent.com/36112975/60746877-38472280-9f8a-11e9-8276-db36c27ea06e.png)

The code renders as:

![2](https://user-images.githubusercontent.com/36112975/60746890-4c8b1f80-9f8a-11e9-8605-9043616901f9.png)

Well there is a space above the code while it shouldn't. Now if I click near this code block the problem gets fixed _for that particular code-block_. Why does that happen?

**System Information:**
**OS:** macOS Mojave, version 10.14.5
**typora version:** Version 0.9.9.25.3 (2897)

Thank you in advance!

**Comment by abnerlee** [comment]
should be fixed
