### ISSUE TITLE
cross referencing doesn't work

### ISSUE THREAD

**Issue by lvliangxiong** [typora/typora-issues#2634]
# cross referencing doesn't work

When I try the example in the support on the official website, it doesn't work.

```
Here is a labeled equation:

$$
x+1\over\sqrt{1-x^2}\label{ref1}
$$

This is a referece : $\ref{ref1}$
```
Please check this.

![](https://user-images.githubusercontent.com/25689191/60763284-bcd99400-a0a3-11e9-8dad-3f12cec1b506.JPG)

**Comment by abnerlee** [comment]
It shows ??? because the target does not have a visible label. 

Either enable auto numbering feature or give target expression a tag label using `\tag{1}`

```
$$
x+1\over\sqrt{1-x^2}\label{ref1}\tag{1}
$$

This is a referece : $\ref{ref1}$
```

see https://meta.mathoverflow.net/a/2922
