### ISSUE TITLE
[Feature Request] (for Mac) Automatic naming of files and automatic selection of the folder

### ISSUE THREAD

**Issue by utotch** [typora/typora-issues#2636]
Hi, I appreciate such an excellent markdown editor.

I'm trying to move from Boostnote to Typora (for Mac).
I prefer many functions in Typora rather than Boostnote, but I hope some features to be improved as a seamless idea processor.

I prefer
* New files are automatically saved in the suitable folder without actively selecting it after
* New files are automatically named and automatically saved without saving operation

In this time, when using Typora for Mac
* I have to save a file
* I have to choose the save location, not before editing it but after editing it
* New files are not saved automatically

This feature forces me extra efforts and miss-operation of losing files could happen.

I post this for the feature request.

**Comment by abnerlee** [comment]
#935
