### ISSUE TITLE
Cursor doesn't go to EOL when press 'End' and formula at the end

### ISSUE THREAD

**Issue by Prurite** [typora/typora-issues#2637]
When I press the 'End' key, I expect the cursor to go to the end of the line. But, when the last character of the line is the formula ( see example below ), the cursor just stops before the formula.

Example:
The line ( in source code )
```
123 $123$
```
And what it looks like in Typora:

![image](https://user-images.githubusercontent.com/44775584/60853365-592fa200-a22e-11e9-9e24-96dc54e56689.png)

When I put my cursor at the beginning of the line then press 'End', the cursor should go to the end of the line, but it stops at the position shown in the picture.

**Comment by Prurite** [comment]
Any one here? thanks

**Comment by abnerlee** [comment]
should be fixed
