### ISSUE TITLE
Miss math block in exported HTML(without styles)

### ISSUE THREAD

**Issue by lumingdong** [typora/typora-issues#2638]
I am a heavily dependent user of Typora. 
Usually use Typora to write blogs. First write an article in Typora and export it asHTML(without styles)，then paste the HTML directly into the WordPress.
There are a lot of mathematical formulas in my article that need to be marked with "$……$" or "$$……$$", The previously exported html files has  "$……$" and "$$……$$" math block marked symbol until I update to the version 0.9.61(windows) .
The new version（after 0.9.9.21 (0.9.63) beta） has no "$……$" and "$$……$$" math block marked symbol after exporting  HTML(without styles), and I found the same problem on the Mac.
I very much hope that you can fix this bug or restore this feature, otherwise I may lose a very perfect writing tool.

**Comment by abnerlee** [comment]
There's no native math in HTML, so "styles" will be used for math blocks.

MathJax or KaTeX is needed to be imported in the HTML code for this case.

The use case for HTML (without styles) is let users to include their own CSS or math rendering engine.

**Comment by abnerlee** [comment]
should be fixed

**Comment by lumingdong** [comment]
> should be fixed. We will copy SVG directly, will add options to copy source (unrendered) math if there are such requests from user.
First of all, thank you very much for fixing the previous bugs, and then I think it is very necessary to add option of copying source (unrendered) math(with “$……$” or "$$……$$") , because on many blogs or some other platforms, they use their server's mathjax.js to render "$...$" and "$ $...$$" to math formulas. SVG can be read directly in html format, but it is not suitable for blogs to render with their own Mathjax.js(Identify the "$……$" and “$$……$$” symbols yourself and render them).

**Comment by lumingdong** [comment]
> should be fixed. We will copy SVG directly, will add options to copy source (unrendered) math if there are such requests from user.

First of all, thank you very much for fixing the previous bugs, and then I think it is very necessary to add option of copying source (unrendered) math(with “$……$” or "$$……$$") , because on many blogs or some other platforms, they use their server's mathjax.js to render "$...$" and "$ $...$$" to math formulas. SVG can be read directly in html format, but it is not suitable for blogs to render with their own Mathjax.js(Identify the "$……$" and “$$……$$” symbols yourself and render them).
