### ISSUE TITLE
Inserting bracket `[` in first position in an unordered list will select the first character.

### ISSUE THREAD

**Issue by jianzhongli** [typora/typora-issues#2639]
Like we have a unordered list:
<img src="https://user-images.githubusercontent.com/5278523/60864457-4204aa80-a256-11e9-99b0-22822b68299e.png" width="400">
And if we insert a bracket character `[` in the first position, typora will select the first following character automatically.
<img src="https://user-images.githubusercontent.com/5278523/60864525-62cd0000-a256-11e9-9619-eae00e266849.png" width="400">

Typora for Mac OS,  Version 0.9.9.25.3 (2897)

**Comment by abnerlee** [comment]
should be fixed
