### ISSUE TITLE
img can show but can't save to local.

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2641]
![img](https://upload-images.jianshu.io/upload_images/4155986-14586a6e6389134b?imageMogr2/auto-orient/strip%7CimageView2/2/w/1000)

https://upload-images.jianshu.io/upload_images/4155986-14586a6e6389134b?imageMogr2/auto-orient/strip%7CimageView2/2/w/1000

cant't auto save to assets; `right click`-> `copy to  xxx.assets`  not work.

**Comment by abnerlee** [comment]
should be fixed
