### ISSUE TITLE
About saving images in relative paths

### ISSUE THREAD

**Issue by eryajf** [typora/typora-issues#2642]
Hello, I have some doubts and thoughts about the picture. Before, my computer and the company's computer were both win systems. Therefore, the defined image save path is an absolute path. As long as the paths of the two hosts are the same, Then the reference to the picture will not be a problem. But now it's updated to the mac system, it seems that this solution does not work, so I only think of a solution using a relative path. However, the current solution provided in the relative path strategy only supports `./`, so the definition of the directory, the only uncomfortable thing is that if an article needs to change the location, the corresponding image can not be loaded, thinking about whether Under the idea of ​​relative path, we can define a directory for uniformly placing pictures, so that on the one hand, it is beautiful and concise. On the other hand, even if the article changes position, the picture reference path is not affected. To put it bluntly, it is to use the relative path of thinking to do the absolute path. I think if Typora gives the concept that the installation directory is the root directory, then I can define a `/typora-pic` in the relative path strategy. The  directory is dedicated to storing images, so that Windows and Mac can be implemented, even on the mobile side. I don't know if this feature is available. I didn't experience it. I still don't have it. I don't know if it is feasible. If so, can I consider adding it in the next update?

**Comment by eryajf** [comment]
[https://github.com/typora/typora-issues/issues/308#issue-179674944](url)

I just saw some good solutions in another problem. In the case of relative paths, I will automatically convert `\` to `/`. This automatic conversion does not seem to take effect in the configuration of the absolute path. Like this: `/D:\龙盘虎踞\Typora\typora-pic\a80-1.gif` and then the middle path is converted to `/`, so that you want to be compatible with mac through absolute path, Windows system , can be achieved, just need to create `/D:/龙盘虎踞/Typora/typora-pic` this directory in the mac, you can, I do not know whether this idea can be adopted.

**Comment by eryajf** [comment]
For this I did an experiment, first create an experiment directory test in Windows, then define the path to store the image as test / pic, then create a document, introduce a picture, and then manually change the path of the picture to match The specification of the mac system, and then throw the whole package into the Linux system, after testing, found that this idea is feasible, the specific effect looks at the rendering of the next to the mac system.

![](https://raw.githubusercontent.com/eryajf/t/master/img/深度截图_选择区域_20190710163610.png)


Based on this situation, I hope that the next version can be added to:
1. If the defined path is an absolute path, then it is also supported to convert `\` to `/`.
2. Another point to note is the need to add a `/` before `D:`.

**Comment by abnerlee** [comment]
#2559

**Comment by abnerlee** [comment]
see http://support.typora.io/Images/

**Comment by eryajf** [comment]
The situation should be different. The host of the official documentation is based on the Mac system, so you can define the save path of the image as `/test/abc`, and if I am on a Windows system, the path can only be `D:\test\abc`, if you want to be compatible between the two systems, it is a bit of a hassle. Later, I found that Windows is compatible with `/` such path identification, so you can create `/D:/test/abc` in both systems. This directory can be used to save images, so the compatibility problem is, Under Windows, such absolute path expression seems to be unsupported. My current practice is to write a small tool. After the document is written, use the tool to change the path.

**Comment by abnerlee** [comment]
We support absolute path in windows `D:/test/abc/...` in Windows, there's no path like `/D:/`

**Comment by eryajf** [comment]
Yes, I can understand what you mean, maybe this is a special requirement of my personal. In order to maintain compatibility between Mac and Windows, I am currently converting by running a shell command, thank you for your patience.

```
sed -i 's/(D:\\龙盘虎踞\\Typora\\typora-pic\\/(\/D:\ /龙盘虎踞\/Typora\/typora-pic\//g' $1"/"$file
```

**Comment by abnerlee** [comment]
About data sync between different devices, currently the recommended workaround is http://support.typora.io/Sync/

Basically, images would be saved somewhere related to the md file, so user can sync the "root" folder. It's not a common way to sync markdown files and the image folders *separately*.

**Comment by eryajf** [comment]
Yes, if you use a relative path, it will be a very simple solution, but I want to avoid the disadvantages of the relative path, so I always insist on using the absolute path.After all, after the relative path, if you change the article name, or the article location, the image will not load.Thank you again for your guidance and thank you for your hard work and making such a wonderful tool.
