### ISSUE TITLE
outline doesn't switch according to the file switch

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2644]
when switch file, it's amazing that the outlines on the left panel refuse to switch accordingly.

It's a crazy bug affects daily life, please manage to repair asap.

**Comment by leewi9** [comment]
@abnerlee urgent

**Comment by abnerlee** [comment]
How to reproduce this?

**Comment by leewi9** [comment]
open multiple file in a folder, each file with some headlines, then try to switch between those files, perhaps you will see.

**Comment by leewi9** [comment]
@abnerlee could you please solve it as soon as you can, it really hurts!

**Comment by abnerlee** [comment]
@leewi9 I still cannot reproduce this. If possible could you take a screencast to us <hi@typora.io>?

**Comment by leewi9** [comment]
@abnerlee https://drive.google.com/open?id=1dqJRlS2jOEM2uDx5IRZ-CjZplYhh8F4W

**Comment by leewi9** [comment]
@abnerlee  any update?

**Comment by abnerlee** [comment]
should be fixed

**Comment by leewi9** [comment]
may I know the reason? @abnerlee
