### ISSUE TITLE
Broken link for old version downloading

### ISSUE THREAD

**Issue by jackwish** [typora/typora-issues#2646]
I have been encountering annoying bugs in recent versions, which removes contents. Actually I was pretty happy with old versions, so I'd like to switch to them.

However, I noticed that downloading links are dead such as:
* `https://typora.io/download/Typora-0.9.9.10.9.dmg`

If it is possible to provide legacy versions? Maybe GitHub can serve them.

**Comment by abnerlee** [comment]
You could try some "later" old versions, versions that are too old are not avaiable
