### ISSUE TITLE
[Feature Request] Xy-pic in MathJax

### ISSUE THREAD

**Issue by utotch** [typora/typora-issues#2647]
I want to write picture (xymatrix) in MathJax.

I think [XyJax](https://github.com/sonoisa/XyJax) is a common solution to use Xy-pic in MathJax.

Since I don't know how to integrate XyJax to typora, I would like to propose the feature request.

**Comment by Masacroso** [comment]
I would like to see this implementation also :D because commutative diagrams are so frequent in many areas of mathematics, and you can't express the same using words or just common mathjax.

**Comment by i-blis** [comment]
XyJax doesn't support MathJax 2.4 or later and Typora currently uses MathJax 2.7.5.

You may want to use the Tikz package to produce image files. LatexIt is good option to quickly and conveniently get vector SVG images and paste them in Typora.

**Comment by abnerlee** [comment]
I'm closing this since the library (MathJax >= 2.7.5) we use does not support Xy-pic. So it is less likely to be supported.

**Comment by Masacroso** [comment]
There is a new version of XyJax that support mathjax 3.1.4+, see here:

https://github.com/sonoisa/XyJax-v3

**Comment by abnerlee** [comment]
relates #3388

**Comment by abnerlee** [comment]
supported
