### ISSUE TITLE
Same theme for separate instances

### ISSUE THREAD

**Issue by ghfardin** [typora/typora-issues#2648]
When I want to change the theme for one instance, all other instances get the same theme, although I want to have multiple themes, that's because I have a modified theme that is RTL, but I can't change the theme for just the one I want, I tried to have multiple executable instances but all of them are pointing to the same home .config/Typora folder, am I missing some option? Is there a way to change the default config folder for the second installed one?

**Comment by abnerlee** [comment]
We don't support this.
