### ISSUE TITLE
[Feature Request] Change the font size of MathJax

### ISSUE THREAD

**Issue by utotch** [typora/typora-issues#2649]
I want to change MathJax font larger since the font is too small in my environment.

Changing the size look impossible at this time as this issue.
https://github.com/typora/typora-issues/issues/2158

I would like to add the feature of changing the font if it is impossible.

**Comment by pengyou200902** [comment]
Need this also. I just found the font size of Latex/markdown formulae is so small.

**Comment by abnerlee** [comment]
There are no such option, but you can use `zoom:120%` in custom css for math
