### ISSUE TITLE
LInks to other md documents not working

### ISSUE THREAD

**Issue by Defossez** [typora/typora-issues#2651]
Hi,

I'm creating one main document (Kind of ToC) where one can click a link and jump from the intro.md to other documents and from those documents back to the intro.md. 
For some reason or another I cannot make links work.
This is how I write them: [Topic 1](Documents\Topic_1.md)
The OS is Windows 10 and the Topic.md is in a folder with sub-folder \Documents

In the Topic.md only Topic 1 is displayed and when clicking on it the path to the sub-document is displayed, but it does not open the sub-document.

Thanks for any hints, ideas,

Regards

**Comment by Defossez** [comment]
The way of writing the link, as given in previous text, `[Topic 1](Documents\TopicOne.md)`
works perfect with Atom and Markdown Preview Enhanced.
Ist the syntax for Typora different? (not following the doc, but ...)

Regards,

**Comment by abnerlee** [comment]
use ctrl+click to open links. Do you press the `ctrl` key?
