### ISSUE TITLE
Outdated link in the page 'Write Custom Theme for Typora'

### ISSUE THREAD

**Issue by chirsz-ever** [typora/typora-issues#2653]
In the page [Write Custom Theme for Typora](https://theme.typora.io/doc/Write-Custom-Theme/), the link to traditional Chinese translation is out of date. The translation is now on [[Note] 如何為 Typora 撰寫客製化樣式](https://pjchender.github.io/2018/04/24/note-%E5%A6%82%E4%BD%95%E7%82%BA-typora-%E6%92%B0%E5%AF%AB%E5%AE%A2%E8%A3%BD%E5%8C%96%E6%A8%A3%E5%BC%8F/).

**Comment by abnerlee** [comment]
updated the link
