### ISSUE TITLE
Where are the Typora preferences stored?

### ISSUE THREAD

**Issue by jeff9315** [typora/typora-issues#2655]
In Windows, where are the Typora preferences stored? I see the advanced options are stored at C:\Users\myusername\AppData\Roaming\Typora\conf\conf.user.json. But I don't see the basic preferences there. I'd like to be able to copy **ALL** my preferences to a new installation.

**Comment by abnerlee** [comment]
Currently in `C:\Users\myusername\AppData\Roaming\Typora\profile.data`.

We may change the location in future, see #2353
