### ISSUE TITLE
Space between outline and writing field

### ISSUE THREAD

**Issue by zewfix** [typora/typora-issues#2658]
A a typora beginner, i'd like to know, if it is possible to get rid of this yellow marked space between the file structure/outline and the writing field? Which custom option do i have to choose to move these parts closer to each other?

![tyspace](https://user-images.githubusercontent.com/53151383/61594964-9cf0b700-abf1-11e9-94a5-32c136a674d8.PNG)

Thanks in advance,

**Comment by abnerlee** [comment]
http://support.typora.io/Width-of-Writing-Area/
