### ISSUE TITLE
Checkboxes inside table

### ISSUE THREAD

**Issue by Cancan68** [typora/typora-issues#2659]
Hi

Wanted to add checkboxes (tasks) into a table, but Typora is ignoring them:
```
##### Table with checkboxes

| Title | Description  |
| ----- | ------------ |
| Row   | blablablabla |
|       | [ ] BDs      |
|       | [X] BDs      |
```

Result in Typora
![image](https://user-images.githubusercontent.com/52736158/61690819-7d10de80-ad2a-11e9-9850-77712a765ff9.png)

Result in Mardown Editor (Nextcloud app)
![image](https://user-images.githubusercontent.com/52736158/61690875-9a45ad00-ad2a-11e9-9350-dd383b64e226.png)

Would it be possible to add this ?

Laurent

**Comment by abnerlee** [comment]
Typora follow GFM for task list, which is 
```
- [ ]
```

currently in table, no block elements are supported, which is a limitation of Markdown

**Comment by abnerlee** [comment]
#2666
