### ISSUE TITLE
typora bug with third party keyboard shortcut application 

### ISSUE THREAD

**Issue by Canorus** [typora/typora-issues#266]
I've uploeaded video to [Youtube.](https://www.youtube.com/watch?v=8qSk0SAE1Rk) 

I'm not sure what's causing this but I think the input is duplicated.

**Comment by abnerlee** [comment]
@Canorus have you checkout the new version? I think the issue with typinator has been fixed

**Comment by Canorus** [comment]
Hi. I've just checked the new version. Most of them were fixed but the one with YAML tag still isn't fixed. It works on Source mode though. Thanks.

**Comment by Canorus** [comment]
@abnerlee Hi. I've figured out what's wrong. My snippet was like below:

---
layout: post
title: {^}
---

On Rich Text mode, Typora automatically converts above syntax to YAML tag and placed the cursor at the last position excluding `---` since it won't be shown on editor window, while Typinator tries to move cursor backward four times anyway, since that's how Typinator works.

So, I think it would be great if Typora had option like 'Typinator compatibility' and behave as if they are actually there before deciding where cursor gets located. Thanks.

**Comment by abnerlee** [comment]
@Canorus I see, but when when the yaml is input or left key is hit, typora cannot know whether it is done by user operation or by Typinator, so I'm not sure how typora could solve the conflicts. 

BTW, would you consider remove the behavior of  "move cursor backward four times" in your Typinator snip?

**Comment by Canorus** [comment]
@abnerlee Oh you're right… there no way you can tell if it was user operation or Typinator… maybe the delay between key inputs can tell since no human being can input that fast with such special characters.

and yes, I did consider removing the behaviour, and probably would atm, or just create another snippet just for Typora(this sounds better, `yamltyp` for example), but just wanted to see everything that worked outside also works on Typora.

**Comment by abnerlee** [comment]
Close  based on the discussion above
