### ISSUE TITLE
Support Draw IO file format.

### ISSUE THREAD

**Issue by rezanid** [typora/typora-issues#2660]
Draw IO has become a popular diagramming tool and it is possible to embded its diagrams within HTML pages. Some popular documentation products like Confluence have builtin support for both embeding Draw IO content and providing drawing experience. The way Draw IO is built, makes it easy for web-based / JS-based products to integrate with its workflow.
I think this integration can be done with minimal code in Typora and from the end-user point of view it can be merecly supporting embeding diagrams similar to how images are inserted within the editor. The only difference is that each diagram can contain more than one page which can be specified as part of the syntaxt. For example: `![My diagram caption](diagrams\my-diagram.drawio#page1)`

**Comment by abnerlee** [comment]
#1138

**Comment by JayRichrd** [comment]
how to use Draw io in typora? please.
