### ISSUE TITLE
[Feature Request] Refreshing Images

### ISSUE THREAD

**Issue by toolchild** [typora/typora-issues#2661]
I use Typora for documentation and planing and it is smooth and fun to use.

I think it would be great to have a Key (F5 or ctrl+f5 or ctrl+shift+f5 or ctrl+shift+r) to refresh the document, reload images. Similiar to a Browser.

I only use local images but I need to close and open Typora again, whenever I change something in the image to see the changes. 
It is irritating and I have the immediate feeling that I am doing something wrong.

Just my honest feedback.

**Comment by abnerlee** [comment]
added into #2242
