### ISSUE TITLE
[Feature Request] Large mermaid editing support (zooming, config of the accepting size))

### ISSUE THREAD

**Issue by utotch** [typora/typora-issues#2665]
I guess editing large mermaid flowchart is prohibited by security reason. https://github.com/typora/typora-issues/issues/2500
https://github.com/typora/typora-issues/issues/2627

But I edit a large flowchart for normal use.

I would like to request the feature below:

## request feature
* accept large flowchart editing (e.g. config of the size of maximum nodes or file)
* zooming interface for the preview area

## request reason
* editing large flowchart is normal usage for me
* I can't suitably zoom the chart both in preview and exported html.

**Comment by abnerlee** [comment]
I think mermaid is not friendly for large content.

But could you provide a sample (<hi@typora.io>)? I will check if it can be rendered without froze the app.
