### ISSUE TITLE
Copy/Paste in Windows leads to Security Issue with Relative Path becoming converted going "outside" up to the "system root"

### ISSUE THREAD

**Issue by christophcemper** [typora/typora-issues#2668]
Copy/Paste in Windows creates relative paths which try to go "outside" up to the "root"
which would cause security issues and render images broken

which 
a) is unnecessary large 
b) breaks whenever deploying on a webhost (security)

When using images with relative paths like

[alt](./something.assets/something.png)

and you copy/paste the whole block with the image

you end up with the 

./something.assets/something.png

being replaced with e.g.

../../../../../../../../../MyDropbox%20(new)/!git/docs/lrt-manual/src/lrt-de/04%20Recover/Link%20Detox/1%20Vorbereitung%20und%20Start/something.assets/something.png

with 

../../../../../../../../../MyDropbox%20(new)/!git/docs/lrt-manual/src/lrt-
de/04%20Recover/Link%20Detox/1%20Vorbereitung%20und%20Start/

being completely wrong and NOT relative.
It actually traverses all the way up to the system root 
and then traverses all the way down to where that file sits

Expected behavior:

Relative paths should only be relative to the file, not to the system root.

Typora Image Settings

![image](https://user-images.githubusercontent.com/12080594/62002484-56292280-b105-11e9-8df5-46e68f0e1a44.png)

Typora version 0.9.72 beta

Windows Version
![image](https://user-images.githubusercontent.com/12080594/62002516-026b0900-b106-11e9-898c-7e1ca5cdbf9e.png)

**Comment by abnerlee** [comment]
I cannot reproduce this, by "copy & paste", do you mean copy from Typora and paste to Typora?

**Comment by christophcemper** [comment]
yes exactly, within the same file, just moving text and images around


Christoph C. Cemper
Founder & CEO

LRT USA (866) 347 3660
LRT Canada (877) 736 7787
LRT UK +44 800 0119736
LRT Austria +43 720 116440

LinkResearchTools
Recover Protect Learn Grow


LinkResearchTools GmbH, Am Langen Felde 12 / Top 1-4, 1220, Vienna, Austria, Europe
Company Reg: FN269754y, HG Wien,  UID / VAT-ID: ATU62127727
Terms & Conditions: lrt.co/terms/pm Privacy: lrt.co/privacy/pm


________________________________

**Comment by christophcemper** [comment]
I created this video here to help you reproduce

https://www.loom.com/share/d8d3d3bdce014c019f041575fa7f02fb

>Also, your folder name is MyDropbox (new) not MyDropbox%20(new), right?

Yes it was. In the video it is different again, but the point is, that the space got converted to %20.

**Comment by abnerlee** [comment]
should be fixed

**Comment by christophcemper** [comment]
Lovely - thanks so much

**Comment by christophcemper** [comment]
Sorry, have to reopen this.

0.9.7.3 just showed the same behavior when copying across files

![image](https://user-images.githubusercontent.com/12080594/62528904-e9690300-b83d-11e9-8a5a-c4b309454f96.png)

**Comment by christophcemper** [comment]
To clarify

It now WORKS when copy/pasting within the same file/folder

It is still DEFECT when copy/pasting between different file/folders

**Comment by christophcemper** [comment]
@abnerlee making sure you see this
