### ISSUE TITLE
[BUG] Export incorrect PDF catalog

### ISSUE THREAD

**Issue by Summving** [typora/typora-issues#2673]
v.0.9.72 beta
windows10 home x64

at Typora:
![图片](https://user-images.githubusercontent.com/23720634/62106889-fb482480-b2d8-11e9-9cae-381cfd8789ff.png)

at exported PDF:
![图片](https://user-images.githubusercontent.com/23720634/62106926-0f8c2180-b2d9-11e9-875b-845695db686e.png)

file: [立创EDA使用教程_2019-07-30-1.md](https://image.easyeda.com/files/%E7%AB%8B%E5%88%9BEDA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B_2019-07-30-1.md)

it looks good at edit screen, but fail at PDF catalog

Thank you

**Comment by Summving** [comment]
Find out the issue, the header has few space
![图片](https://user-images.githubusercontent.com/23720634/62110499-1d45a500-b2e1-11e9-8c69-13228211ad8e.png)

**Comment by abnerlee** [comment]
should be fixed
