### ISSUE TITLE
Find, find and replace do not interact with equations correctly

### ISSUE THREAD

**Issue by brianlandry1e9** [typora/typora-issues#2674]
1. Open new document
2. Enter the following
```
$a=b$

```
Issue 1: Search a and it is found, search b and it is not found
Issue 2: Find replace "a" with "c"
Document is rendered as if it were
```
c

```
However, as expected the document is actually

```
$c=b$

```

Done on "Version 0.9.9.25.3 (2897)" using MacOS Mojave 10.14.6 (18G84)

**Comment by abnerlee** [comment]
relates #2824

**Comment by abnerlee** [comment]
should be fixed
