### ISSUE TITLE
[Feature Request] CTRL+SPACEBAR to get on the other side of autocompleted closing bracket (etc)

### ISSUE THREAD

**Issue by jinchoung** [typora/typora-issues#2675]
this is a non-standard feature for word processors and text editors but i believe it should be universal and i'd like to request this for typora's autocompletion symbols like (), [], {}, "" and whatever others there are.

i love autocompletion for these symbols but it's always needlessly cumbersome to get the cursor on the other side of the final symbol.

the way to do it of course is to use the right arrow button. but this removes your hand from the home row and usually makes me have to look down.

please implement CTRL+SPACEBAR to function like right arrow.

**Comment by abnerlee** [comment]
I don't see any reason for CTRL+SPACEBAR.

Shouldn't press right arrow or the close bracket be quicker than press CTRL+SPACEBAR? 

Is there any other editors work in this way? Basically, we won't let our users learn new non-standard stuff which does not bring enough merits. I'd love to know their reason / senario or bring this.

If you mean cursor to next "possible "editing chunk, I think `tab` is more intuitive for this
