### ISSUE TITLE
[Defect] auto math numbering set the first equation to the largest eq. num

### ISSUE THREAD

**Issue by softyeye** [typora/typora-issues#2676]
Hi all,

First of all, thank you very much for providing the great program to work with.

When "auto numbering for math equations" are enabled and the file is open at first, the number of the very first equation is always the largest eq. number and then started from (1) after that.
E.g., if there are in total 9 equations in the text, the auto-numbering is as follows:
1st eq in the text  (9)
2nd eq in the text (1)
3rd eq in the text  (2)
..
9th eq in the text  (8)

After opening the file, if I click on Edit-Math Tools-Refresh All Math Equations, and then the numbering is fixed as follows:
1st eq in the text  (1)
2nd eq in the text (2)
3rd eq in the text  (3)
..
9th eq in the text  (9)

The issue is that I need to execute "refresh all math" function whenever I open the file again.
Many folks now using this tool have the same problem, so we would appreciate if you could please take a look at the issue.

OS: Windows 10
Ver 0.9.71 and 0.9.72 (beta)

**Comment by abnerlee** [comment]
should be fixed
