### ISSUE TITLE
I can't display the problem again when I encounter the uploaded image.

### ISSUE THREAD

**Issue by Codeprh** [typora/typora-issues#2678]
Hello, it is really sad, I once again encountered a problem with the picture uploaded to the map bed could not be in typora.

My typora uploads are uploaded to the Sina map bed, which can be displayed normally in the Evernote, but cannot be displayed in typora. Please see my attached picture for details. thank.

Secondly, I found a rule, only the image of the url that uploaded the Sina picture with (http://ww4.sinaimg.cn) can be displayed in typora. The url image at the beginning of (http://ww2.sinaimg.cn) and (http://ww3.sinaimg.cn) cannot be displayed.

Thank you for your troubles as soon as possible. Thank you very much, I really like typora. Waiting for your reply. Finally, I wish you good.

My computer system is: mac os 10.14.5
The typora version is: 0.9.9.25.3 (2897)

**Comment by Codeprh** [comment]
help

**Comment by abnerlee** [comment]
Would you attach a real image link that cannot be displayed? I cannot reproduce this one.

And Sina Weibo is not a image bed, it is recommended to chose more stable image web service
