### ISSUE TITLE
[Bug] MSSQL Incorrect Markdown Highlighting

### ISSUE THREAD

**Issue by Avlyssna** [typora/typora-issues#2680]
I'm currently using Windows 10 1903 x64 and Typora 0.9.72. When highlighting MSSQL (TSQL) syntax, the backslash character will incorrectly escape the end quote.

For instance, GitHub will render the following block correctly.
```tsql
DECLARE @DrivePath VARCHAR(100) = 'C:\'
GO
```
However, in Typora, it will mistakenly think I am escaping the single-quote. This will leave `GO` - and all further code until a second single-quote is reached - highlighted as a string.

**Comment by abnerlee** [comment]
From https://dev.mysql.com/doc/refman/8.0/en/string-literals.html, `\'`can be used as escaped quote.
