### ISSUE TITLE
How to set the color of links in a file?

### ISSUE THREAD

**Issue by GoldIce** [typora/typora-issues#2682]
Good afternoon!

Please tell, how to set the color of the created links, through "xxx.user.css"

Interested in two situations: 
1) color of created links;
2) color of created links, when we which the mouse cursor;

**Comment by abnerlee** [comment]
use http://support.typora.io/Add-Custom-CSS/
or `<a style="color:red" href="xxx">yyy</a>`

**Comment by GoldIce** [comment]
You did not understand me correctly
I want to change the default colors that go to the links.
I know what Custom CSS is. I already use it.
Please Tell, how to register these colors in my custom css file.

Interested in two situations:

how set color of created links;
how set color of created links, when we which the mouse cursor;

пт, 2 авг. 2019 г. в 16:18, AbnerLee <notifications@github.com>:

**Comment by abnerlee** [comment]
```
a {
color: #000
}
a:hover {
color: #000
}
```

**Comment by GoldIce** [comment]
**abnerlee**, i checked the option you proposed. Unfortunately, the colors of the Internet links have not changed. Check, please.
