### ISSUE TITLE
[Feature Request] Pull/Push headers up/down in outline view

### ISSUE THREAD

**Issue by Yaojian** [typora/typora-issues#2684]
### Summary

When a header is selected in the outline view, provides a method (such as a context menu or a button) to
* Pull one level up for a header and all its descendant headers
* Push one level down for a header and all its descendant headers

### Example

Suppose we have a doc with header:
```
A
  B
  C
    D
```
for the selected header `C`, `Pull up` will give us:
```
A
  B
C
  D
```
or `Push down` will give us:
```
A
  B
    C
      D
```

**Comment by abnerlee** [comment]
#916
