### ISSUE TITLE
feature request: Add more supported LaTeX equation formats

### ISSUE THREAD

**Issue by N0rbert** [typora/typora-issues#2685]
Many scientific texts contain equations. Currently texts are sometimes written in RMarkdown.

Some texts are books and articles written in [bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations), some of texts are presentations written with [xaringan](https://bookdown.org/yihui/rmarkdown/xaringan.html). 

Below is the feature request to support more LaTeX equation notations such as:

```
Environment `\begin{equation}...\end{equation}`
with auto-numbering:

\begin{equation}
h(z) = \sinh(z)
\end{equation}

---

Environment `\begin{equation}...(\#eq:label)\end{equation}`
with auto-numbering and label (for bookdown):

\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}

---

Environment `\begin{equation}...\label{label}\end{equation}`
with auto-numbering label for xaringan

\begin{equation}
  g\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
\label{binom2}
\end{equation}
```

This functionality is currently exists in other editors

![retext](https://user-images.githubusercontent.com/309456/62375741-98a89000-b547-11e9-9f44-c4b74c5ec578.png)

But it is missed in Typora editor.

In this feature request I ask only for rendering of equations. Auto-numbering is not needed for me. I'll do it in RStudio after knitting of the document.

**Comment by abnerlee** [comment]
#63
