### ISSUE TITLE
NEW VERSION DOES NOT LAUNCH

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2687]
Abner, after clicking on "install updates" when my Update Manager showed a new Typora version, the app does not launch anymore - using Linux Mint - even after a complete shutdown and boot up of the computer.
Please advise.

**Comment by ciihom** [comment]
Typora( version 0.9.73-1) can`t launch in ubuntu 18.04 LTS.

**Comment by ciihom** [comment]
[3380:3380:0803/213502.977006:ERROR:CONSOLE(162)] "Uncaught TypeError: Cannot read property 'usable' of null", source: chrome-search://local-ntp/doodles.js (162)

**Comment by Chris-Bee** [comment]
You can revert to the previous version as mentioned here: https://github.com/typora/typora-issues/issues/2686#issuecomment-517920174

**Comment by abnerlee** [comment]
#2686

**Comment by DutchPete** [comment]
Abner, why have you closed this issue? Reverting to the previous version is useful, but shouldn't version 0.9.73 be pulled? Otherwise more people will hit this wall.
