### ISSUE TITLE
[Bug] Window height decrease after exit fullscreen mode under seamless mode

### ISSUE THREAD

**Issue by grootpiano** [typora/typora-issues#2689]
每次全屏以及退出全屏之后都会短一截..

**Comment by abnerlee** [comment]
OS / Typora version ?

**Comment by Jingshuai** [comment]
> OS / Typora version ?

macOS: 10.14.5
Typora: 0.9.9.25.3 (2897)

Without maximizing the window

**Comment by Jingshuai** [comment]
> > OS / Typora version ?
> 
> macOS: 10.14.5
> Typora: 0.9.9.25.3 (2897)
> 
> Without maximizing the window

Upgrade Typora to "0.9.9.27 (3298)" also have this problem.
But it's ok. I can maximizing the window to avoid this. ^^

**Comment by abnerlee** [comment]
seems just in 0.10.11 in my test
