### ISSUE TITLE
Beta Version 0.9.9.27 (0.9.73) MacOS Mojave 10.14 - Emojis not autocompleting

### ISSUE THREAD

**Issue by ckupetz** [typora/typora-issues#2690]
Emojis are not auto-completing when using ':' with 0.9.9.27 on MacOS 10.14

Steps to replicate:
1. Create a new .md file or open an existing one
2. Type ':' (followed by any letter) into the file

**Comment by abnerlee** [comment]
fixed in 0.9.9.27.1
