### ISSUE TITLE
Code fence editing issues on 0.9.73 Windows 10

### ISSUE THREAD

**Issue by AlienKevin** [typora/typora-issues#2691]
Hi, I just downloaded 0.9.73 on my Windows 10 and ocassionally I can't enter text into code fences. This happens once per minute and is becoming quite annoying. In addition, when I tried to select the whole line from the end of the line, the cursor just pops to the front and refuses to select anything. This also happens when I tried to select from the start of the line.

**Comment by abnerlee** [comment]
which language on you use in code block?

**Comment by AlienKevin** [comment]
no language selected

**Comment by abnerlee** [comment]
seems #2699

**Comment by AlienKevin** [comment]
Is there a way for me to revert back to the previous version before this issue is fixed?
