### ISSUE TITLE
Typora fails to open after update to 9.73 linuxmint 19.2 (tina)

### ISSUE THREAD

**Issue by tyway9** [typora/typora-issues#2694]
I had installed Typora on Linuxmint 19.2 (beta) and it worked fine. After updating Typora to 9.73 it faied to open. In addition Linuxmint has upgraded to 19.2 (tina) but no chage. I uninstalled and reinstalled too.

Any help will be appreciated. You guys are doing a fabuloius job and really enjoy working with Typora. Thanks in advance!

**Comment by abnerlee** [comment]
Input "typora" and press return in terminal, what is the error message?

**Comment by tyway9** [comment]
Sorry! I was not able to log int the past few days. This is the error I am getting:
 $ typora
typora: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory

**Comment by tyway9** [comment]
Thanks I just updated to Typora 9.74-1 and Typora works as good as ever. Kudus to your team and all out there. Amazing job with Typora
