### ISSUE TITLE
I can't use Continuity Camera in Typora Version 0.9.9.27.1 (3305) on Mac

### ISSUE THREAD

**Issue by utotch** [typora/typora-issues#2695]
After upgraded typora to Version 0.9.9.27.1 (3305) on Mac,
I can't use continuity camera which is the function of choosing "Take photo" context menu and directly paste it.

I can use it in the previous version of typora, and I often used it.

in the previous version (below)
![image](https://user-images.githubusercontent.com/834175/62443240-38644a80-b70f-11e9-95c2-c7f435414bf6.png)

I can choose "Take photo" but in Version 0.9.9.27.1 (3305), I can't see the menu.

**Comment by abnerlee** [comment]
continuity camera is moved to "Format" menu.

**Comment by utotch** [comment]
I got it! Thank you very much!
