### ISSUE TITLE
image can't show ! (feelings been hurt)

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2698]
today as I saw the update reminder and jumped to download the latest version(0.9.9.27.2) only to find this feelings-hurt bug, all my images can not show any more!

screenshot:

![image](https://user-images.githubusercontent.com/10832544/62506594-d18c8180-b833-11e9-89a4-ea676d1fb42d.png)

@abnerlee

**Comment by abnerlee** [comment]
fixed
