### ISSUE TITLE
[Bug] Unable to input after using Home key to move to beginning of line in code block

### ISSUE THREAD

**Issue by durianking** [typora/typora-issues#2699]
On and existing code block, on any line, after pressing `Home` key to move the cursor to beginning of of the line, user cannot input any characters.

O/S: Windows 10
version: 0.9.73(beta)

**Comment by MostlyArmless** [comment]
I'm seeing the same thing, also on 0.9.73

**Comment by arekkusudesu** [comment]
Thanks for having a look at this issue. I'm reverting back to 0.9.70 until this is fixed.

**Comment by MostlyArmless** [comment]
I was able to roll back to 0.9.72 and it works fine. Not sure if you can access the installer for that minor build anywhere though.

**Comment by abnerlee** [comment]
fixed
