### ISSUE TITLE
The paragraphs have moved back to the text

### ISSUE THREAD

**Issue by Zyza123** [typora/typora-issues#2700]
Hi, for a few months im writing a book. And today, something just broke. The paragrahs have moved back to text and it looks like it is written in a single string. Now it will take me a lot of time to divide it back, and I'm not sure that something will not break down next time. I dont know the reason why it happened. I closed the app, everything was okay, and another day it looked like this. Is there any option to bring it back? Im hopeless

**Comment by abnerlee** [comment]
Are you use single line break or double line break when adding paragraphs? For single line break, there's option to show / hide it, see http://support.typora.io/Line-Break/ for detail.

If not, it is a bug, you could try recover http://support.typora.io/Version-Control/
Also, could you share your Typora / OS version?

**Comment by Zyza123** [comment]
Now it works :) There was "ignore the single line break etc" and replaced it with preserve. Thanks for help mate :)
