### ISSUE TITLE
How to set the default color of links in a file?

### ISSUE THREAD

**Issue by GoldIce** [typora/typora-issues#2701]
Good day!
abnerlee, i checked the option you proposed. Unfortunately, the colors of the Internet links have not changed. Format of created Internet links: " [name of link] (website address) ". 
Check, please.
a {
color: #000
}

a:hover {
color: #000
}
What other variants are there?

**Comment by abnerlee** [comment]
No other variants.

Such modification requires necessary CSS knowledge, so it is an advanced feature. 
It's OK that link color cannot be configured easily or cannot be configured at all

**Comment by GoldIce** [comment]
So please tell how to register FULLy exactly? As I understand it, the letter “a” is a symbol. In fact, the team has a different name. 
What exactly is the true name of the links in css file?

**Comment by abnerlee** [comment]
only `a`. see https://github.com/typora/typora-default-themes/blob/master/themes/newsprint.css#L145

And use DevTools to find the selector name

> Then for mac users, check enable debug mode from help menu, then click “Inspect Element” from context menu to pop up DevTools.

> For Windows/Linux users, you could pop up the DevTools from Toggle DevTools from view menu.

https://developers.google.com/web/tools/chrome-devtools/
