### ISSUE TITLE
关于注释功能以及快捷键

### ISSUE THREAD

**Issue by lan542662** [typora/typora-issues#2703]
期待后期加入注释快捷键
目前markdown注释是
其他的[]: # "comment" 并不看好，难用，还有其他的注释功能，[^^]: # "comment",官方好像也没个准信。
其实/*这样挺好的，可惜它不支持*/
Thanks for your great job. Dear Lee.

**Comment by abnerlee** [comment]
Markdown support HTML format comment: `<!--comment-->`
