### ISSUE TITLE
增加图片caption

### ISSUE THREAD

**Issue by masterstevelu** [typora/typora-issues#2704]
能否像http://md.aclickall.com/里这样，把markdown中的[]内容作为图片标题渲染成figcaption，万分感谢！

**Comment by abnerlee** [comment]
duplicate

**Comment by masterstevelu** [comment]
> duplicate

请问重复的那个issue在哪儿？

**Comment by abnerlee** [comment]
#379

`[]` 内容是 alt，可能不会变成 caption，caption 可能用#249
