### ISSUE TITLE
Incorrect font-family when exporting to PDF

### ISSUE THREAD

**Issue by 1024th** [typora/typora-issues#2705]
I use this theme when exporting markdown file to PDF: [zh-academic](https://github.com/ZJUGuoShuai/zh-academic)

But the PDF document doesn't have a right style:
![issue](https://user-images.githubusercontent.com/47070449/62694363-c63d7f80-ba06-11e9-84b6-5c6a8b92b370.jpg)

This problem exists since version 0.9.71. In version 0.9.70, I got the correct document (the right one in the picture above).

OS: Windows 10

**Comment by abnerlee** [comment]
Seems already fixed on newer version
