### ISSUE TITLE
Spell checker not working in 0.9.73 Windows

### ISSUE THREAD

**Issue by christophcemper** [typora/typora-issues#2706]
It worked until 0.9.72 and the upgrade broke it - like other things :-( 

![image](https://user-images.githubusercontent.com/12080594/62695859-7dba9d80-b9d7-11e9-9520-9b63a7cd6012.png)

**Comment by christophcemper** [comment]
Downgraded to 0.9.71 (couldn't find the 0.9.72 exe here or in Git https://typora.io/windows/dev_release.html

and there it works like it did before

![image](https://user-images.githubusercontent.com/12080594/62697081-2964ed00-b9da-11e9-902d-b30cb9a9df89.png)

combined with the home/end issue I'm staying at 0.9.71 for now :-(

**Comment by abnerlee** [comment]
Not able to reproduce it, were you using the x64 or ia32 arch of Typora?

**Comment by christophcemper** [comment]
I was using x64

**Comment by subi54** [comment]
Spell check isn't working for me either. On Windows x64 0.9.74 beta.

I figured out the conditions though. If I open up a new document it works but if I make a new file from the sidebar beforehand, it doesn't.

**Comment by christophcemper** [comment]
I went 0.9.75 and changed the default from English to Auto-Detect and vice-versa... 
it appears to work now again, there was some kind of preference not stored that was fixed I believe in this release

**Comment by refactorsaurusrex** [comment]
> I went 0.9.75 and changed the default from English to Auto-Detect and vice-versa...

I just did the same, but the issue is persisting for me. I'm using the x64 version.

**Comment by christophcemper** [comment]
Actually have to revert my statement.

Spell check seems to work better, more often.

However, after some more intensive work, with multiple windows open and a lot of navigation around it is disfunct again 

Still 0.9.75

**Comment by abnerlee** [comment]
Still cannot reproduce it, merge into #214
