### ISSUE TITLE
Copy/Paste in Windows leads to Security Issue with Relative Path becoming converted going "outside" up to the "system root" 

### ISSUE THREAD

**Issue by christophcemper** [typora/typora-issues#2707]
Same problem like in the linked issue.
https://github.com/typora/typora-issues/issues/2668#issuecomment-518591463

The solution in 0.9.73 only seems to have solved it if content was copy/pasted within the same file.

If I copy/pasted between files the same problem persists

**Comment by abnerlee** [comment]
should be fixed on 0.9.75

**Comment by christophcemper** [comment]
Great, upgrading and testing

**Comment by christophcemper** [comment]
Awesome - copy works without breaking paths and also obeys the sub-folder rule, i.e. copies the images to an .assets sub-folder as configured!

thanks so much
