### ISSUE TITLE
Unable to move files

### ISSUE THREAD

**Issue by donnelly41** [typora/typora-issues#2708]
#1006 was supposed to have addressed moving files in the file tree.

I cannot move files with drag and drop.
The highlighting pops up like it wants to move the file, but nothing happens.

I'm running Typora version 3317 on Mac Mojave 10.14.6.

**Comment by justnealpatel** [comment]
Cannot move files either. I think it worked at one point but I think the latest update may have broken it. I am using Typora version 0.9.9.27.2 (3317) on Mojave 10.14.5.

**Comment by dlumma** [comment]
Same here.

**Comment by abnerlee** [comment]
Move file from one Typora window to another, or drag & drop from Finder to Typora?

**Comment by donnelly41** [comment]
Within one Typora window, when trying to drag and drop a file between
directories.

**Comment by dlumma** [comment]
Within one Typora window, when trying to drag and drop a file between directories.

**Comment by abnerlee** [comment]
should be fixed

**Comment by dlumma** [comment]
Works now. Thank you!
