### ISSUE TITLE
[Feature Request] Keep Indentation on Code Block

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2709]
When I am already indented, and I press Enter, I expect the next line to be at that same level of indentation. When I do it with Typora, the next line goes to the beginning of the next line regardless of previous indentation level.

macOS Version: Mojave 10.14.5
Typora Version: 0.9.9.27.2 (3317)

**Comment by abnerlee** [comment]
Cannot reproduce this one, which language do you use?
