### ISSUE TITLE
[Feature Request] History for jumps between anchors

### ISSUE THREAD

**Issue by HighestQuality** [typora/typora-issues#2710]
When working with large documents I often have many anchors, which I use to jump to specific texts. If I'm pretty much at the end of the document and I jump to an anchor which is at the beginning of the document, I have to keep in mind from which anchor I jumped to it.

This is too much for me, as it is especially difficult at many levels. At the latest when I have jumped from the first anchor to the second and then I jump to another third anchor, then I have already forgotten the first anchor. I would like to jump directly from the third anchor to the first anchor again. This could be solved with something like a history which keeps track of the jumps I did.

**Comment by abnerlee** [comment]
#1574
