### ISSUE TITLE
 export to image cause images in markdown show incomplete.

### ISSUE THREAD

**Issue by Ernest-su** [typora/typora-issues#2713]
the flowing markdown export to image cause images in markdown show incomplete.

## 无休止加班的成因

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhUdtj1MHOmcVwSFfYsYO90msA3SrCibykrD2dDJnkZXhWmT2hWmXp24w/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIh8PnRs4hthdtorEzJicpTuh3TR5IqOysRVRR9T7gnibRWlEiaCh4gaowjw/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhOWKlBAcS9QsNBTibQCazj5uicb0T3cKrEaWGvX6WmBLWo4kkSQhx2S0g/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhlszI9gVB1Nsiahf6exFVpWAf0KjNiaSB4Apxe68YHib1bEbia5G2saaukw/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhXtXS0omjDNhiaeH69GXdHWcMLN4CttyiaN0JvOeUSUsq5Q3ykT4WMib9Q/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIh3Kiatyn4HDeMyWB2hazyhQsaHqHU49n61vq60jHfp6JvQRGD1kqsfdg/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhmdHLfiaiaZiaqyYXmEMNq7Rd2fPRwq1icAIRiaOVlKVBicrbt7ibDZ1tHBnOQ/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhlKjAr6JwhKxJa61NK8k7QV7B4S83UeZV0vuQVHWGPiaic5JWIWnFtd0w/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhO0Aj1C8pGpujlF7QR9iav3KYYCL8icsThib1B5uPdDpxrbBMjayb1m6Wg/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhSqBNVTB5mtVrtMdEEFLxJtAdHfYmvltAtz1e8nZb1HXGoXiaGcVJMQQ/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhiaicWaOOrLnuKXUAzCIkLE6b9HgapQVTEZicQMwCvChOwmMQ0mYa6STUA/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhW1otzl2qNtiaIsPT8gPnibKWomUBQibQ8XuoXArZr0rZ9b9dfE2szJEMw/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhjcqb2RicmrHhCia5I0Z2b3ZNWQpZsCeRKs4bkPibib1473m5xxibsPZ5SYQ/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhe6qvOLoibGowB43EtIZbNiaibOko8icTzAjQtSwCzI9Lkp7GTtSZiaqBP5Q/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhJ3fGJupVdJWx6tZJEFNfr62LhmoP5zUmKcetSHxHzT5etZdbPiamdVg/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhgaFmVKM84ARgAy49iahgiccQrMd9PUybtnmcExgicxjhsxqjLwECFtWPQ/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

![img](https://mmbiz.qpic.cn/mmbiz/NVvB3l3e9aFY7WLD0BjuicfnIYlq8TLIhkw8ydKumSMIIvzovBap6D1ibg7xxZIoxGpLElvlfmTrcicYvIDqYamiag/640?tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

this is the export image 

![无休止加班的成因](https://user-images.githubusercontent.com/5917446/62749094-b5841c80-ba8d-11e9-8022-019bcfdf3a93.png)

**Comment by abnerlee** [comment]
possible to send us <hi@typora.io> the sample md file?

Also what's the Typora / OS version and which theme you use?

may duplicate with #2422

**Comment by Ernest-su** [comment]
yes, I belive it's  duplicate with #2422 could it be an library issue （Pandoc）?

**Comment by abnerlee** [comment]
It's not a Pandoc issue. HTML is rendered in webview or chromium, then convert to image. It may cause by Typora cannot get the correct and actually total height of the rendered output.

What's the Typora/ OS version?
