### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2716]
I would like to see what has changed in 0.9.74. Where can I see the changelogs?

**Comment by abnerlee** [comment]
https://typora.io/windows/dev_release.html

**Comment by DutchPete** [comment]
On the basis of the 0.9.74 changelog I would not install 0.9.74 since it is not mentioned that the non-start-up a number of people, incl. myself, experienced with 0.9.73 has been fixed.

But I saw someone's comment saying that with 0.9.74 installed Typora starts up fine again. So I went ahead and installed 0.9.74, and I can confirm Typora starts up fine again.

Should this bug fix not be mentioned in the changelog?
