### ISSUE TITLE
【BUG】Auto change markdown content

### ISSUE THREAD

**Issue by RobertoHuang** [typora/typora-issues#2717]
When I used typora to punch my markdown file and did not make any changes, but the default Typora changed the file content. version:0.9.74 for windows

![image](https://user-images.githubusercontent.com/20842825/62757966-91393780-baaf-11e9-96ab-f99b91a36c16.png)

This happens when I insert the image using html code, it will change the format next.

**Comment by RobertoHuang** [comment]
Although the typora show looks like it hasn't changed, the file content has indeed changed, and it will show an exception in other places. Such as github

**Comment by abnerlee** [comment]
possible to send us <hi@typora.io> the sample md file?

**Comment by RobertoHuang** [comment]
already send
