### ISSUE TITLE
[BUG] CMD-X not cutting text in 0.9.9.27.3

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#2719]
In WYSIWYG mode CMD+X is not cutting text anymore. In Source Code Mode CMD-X is cutting text.

**Comment by stennie** [comment]
I have the same issue with 0.9.9.27.3.

Further details:
 - I'm using Mojave (10.14.6) 
 - in WYSIWYG mode CMD-X does a copy instead of a cut

**Comment by Acidham** [comment]
I can confirm that issue is fixed in version 0.9.9.27.4
