### ISSUE TITLE
UML Support 

### ISSUE THREAD

**Issue by quanken** [typora/typora-issues#272]
When using sequence block, typora not recognize and generating UML graphs as expect

e.g:

```sequence
A->B: 1
B->C: 2
C->B: 3
B->A: 4
A->D: 5
D->C: 6
C->D: 7
D->A: 8
A->B: 9
B->C: 10
C->B: 11
B->A: 12
```

I wish this feature can be scheduled to achieve in future. Anyway, thanks a lot to view this issue.

**Comment by abnerlee** [comment]
#269
