### ISSUE TITLE
CLI: Open existing at line or Heading

### ISSUE THREAD

**Issue by qbert01** [typora/typora-issues#2720]
Hello,
I love this app!
OK, so I was wondering if it would be possible to add a CLI to allow one to open an existing markdown file at a line number and/or at a Heading.

I'm greping for my TAGs and it would be nice to be able to open the file as close to the TAG or Heading as possible.

Example from Notepad++ to open file at line 12
"/path/to/notepadpp.exe -n12"

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1999
