### ISSUE TITLE
Don't display link reference definitions

### ISSUE THREAD

**Issue by asherber** [typora/typora-issues#2723]
```
This is a [reference link][].

Here's another line of text.

[reference link]: http://example.com

And some more text.
```
Displays as:

![image](https://user-images.githubusercontent.com/5248041/62826256-42aa9c80-bb86-11e9-920b-d7029fbc4965.png)

I don't think the link definition (third line) should display. Reference link syntax should produce the same output as inline links.

**Comment by asherber** [comment]
In the meantime, it looks like adding the following CSS to `base.user.css` will hide the link definitions.

```css
.md-def-link {
    display: none;
}
```

**Comment by abnerlee** [comment]
Yes, it can be hide by CSS.

We don't have plans for hiding it
