### ISSUE TITLE
Unexpected Behaviour from Text Navigation through keyboard shortcuts (Cmd-Left & Cmd-Right)

### ISSUE THREAD

**Issue by leonzalion** [typora/typora-issues#2725]
OS version: MacOS Mojave 10.14.4 (18E226)
Typora Version: Version 0.9.9.27.4

Not sure if behaviour is intentional or not, but in most text editors, command-left should bring the insertion point to the start of the line and command-right should bring the insertion point to the end of the line.

As mentioned on [the official Apple Page of Keyboard Shortcuts](https://support.apple.com/en-us/HT201236):

**Command–Left Arrow:** Move the insertion point to the beginning of the current line.
**Command–Right Arrow:** Move the insertion point to the end of the current line.

In Typora, these commands bring you to the start of the paragraph and the end of the paragraph, respectively (similar behaviours apply when shift is pressed down as well). Hope to see a fix (as I use this shortcut quite often :D)!

**Comment by lakinchris** [comment]
I actually quite like this change…

**Comment by leonzalion** [comment]
Well, luckily the shortcut Option-Up and Option-Down perform the same behaviour as you would like, as well as conforming to the official Apple Standards for the document shortcuts. I’m just extremely used to this shortcut moving to the start and end of the line (as it should be) so I struggle with this irregular behaviour.

**Comment by abnerlee** [comment]
should be fixed
