### ISSUE TITLE
Double click on fraction numbers incorrectly left out the fraction

### ISSUE THREAD

**Issue by sicilian-lizard** [typora/typora-issues#2726]
Example: double click on 3.14159 selects only 3, instead of the number, or the fraction.

OS: macOS Mojave 10.14.6
Typora: Version 0.9.9.27.3 (3342)

**Comment by abnerlee** [comment]
relates #1891

**Comment by abnerlee** [comment]
fixed in new release

**Comment by sicilian-lizard** [comment]
Thanks！
