### ISSUE TITLE
功能需求：添加自定义标签的快捷键

### ISSUE THREAD

**Issue by gitforziio** [typora/typora-issues#2729]
希望能够增加这样的功能：就是可以自己设计一个标签的两端，然后选中一个字符串的时候按自定义的快捷键就自动地给字符串包裹上这个标签。
例子：
```
自定义标签前部=“<sub>”
自定义标签后部=“</sub>”
自定义标签快捷键=“cmd+control+b”
```
然后选中`哈哈`，按下快捷键`cmd+control+b`得到的就是`<sub>哈哈</sub>`。

---

或者希望添加插件入口，让用户能够自己制作插件，同时也能扩宽软件的生态。
谢谢！

**Comment by abnerlee** [comment]
#162
