### ISSUE TITLE
Multi line footnotes

### ISSUE THREAD

**Issue by haakonstorm** [typora/typora-issues#2733]
How to add multi-line footnotes, like `bignote` here? --> 

```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

0.9.9.27.4 (3345) on macOS 10.15 Catalina beta

**Comment by ciandorr** [comment]
I have this issue too.  The method of separating paragraphs within a footnote using <br> gives a workaround for footnotes that just include multiple text paragraphs, but it messes up the paragraph indentation, and also does not provide a way of incorporating things like blockquotes inside footnotes, which I find myself needing to do pretty often.

**Comment by kc-li** [comment]
Same problem here! I want to add some formula in the footnote and it is better put in a separate line. I hope Typora would add the function as a 'footnote block' which enables several paragraphs in a footnote!

**Comment by bminer** [comment]
I still see issues with Typora recognizing multi-line footnotes. Can this issue be re-opened?
