### ISSUE TITLE
Incorrect heading anchors in HTML (0.9.74, Windows)

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2734]
When a heading contains a comma (`,`), it is being used as part of the anchor instead of treated as part of a run of punctuation (and reduced to a `-`).  This applies to both generated HTML, and apparently to navigation within the document being edited.

(That is, if you try to open a link within the document that targets the correct (i.e. github-compatible) anchor, it fails.  But if you add in the commas, the link works.)

**Comment by abnerlee** [comment]
should be fixed
