### ISSUE TITLE
The file has been changed by another application.

### ISSUE THREAD

**Issue by dcy10000** [typora/typora-issues#2735]
when I work with onedrive and typora on my Mac.
It always popup this dialog.
![image](https://user-images.githubusercontent.com/26567055/62989275-f14a2800-be79-11e9-9446-e72634e8ba0d.png)

**Comment by abnerlee** [comment]
see https://talk.macpowerusers.com/t/confusing-auto-save-behavior-in-pages-with-onedrive/10373

Typora supports "saveInPlace" and allow macOS to auto save documents.
The save logic is schedule by macOS and performed / valid by macOS

**Comment by fastfading** [comment]
turn off auto save did not solve this issue.  
when you manual save ,  also report this error

**Comment by bumpux** [comment]
> turn off auto save did not solve this issue.
> when you manual save , also report this error

Same here. Mac OS 11.6.  Save not possible in folders/volumes hosted in Google Drive (streamed or synced to disk). Save works fine in other folders

**Comment by dwbruhn** [comment]
I use Typora with OneDrive on Mac OS 10.15.7, and I've just had to resign myself to pressing Return after every save...

**Comment by plt-francesco** [comment]
Same exact behaviour here, version 0.11.11 (5873).

**Comment by Shoothzj** [comment]
same here, Typora: 1.0.2 Macos: 12.0.1

**Comment by MiQieR** [comment]
same here, typora: 0.11.18, macOS: 12.0.1.
It happened in OneDrive downloaded from web. I changed to App Store version and it fixed for a few days, but happens again today.

**Comment by dwbruhn** [comment]
@abnerlee Can we re-open this issue? It seems like there are enough reports to warrant looking into it.

**Comment by Jed-Z** [comment]
Same here. When manually saving in OneDrive dir, there is a chance that the prompt "The file has been changed by another application" will pop up

**Comment by hyacinthus** [comment]
Same issue. With OneDrive.

**Comment by proxy-hatch** [comment]
Same issue with Google Drive. Fixed by copy content to clipboard, close but don't save, and open file again.

Before this process, "save as" and replace old file doesn't work either.

**Comment by rdebeasi** [comment]
I began experiencing this problem after upgrading to macOS Catalina, so I wonder whether the issue might be related to the [new "app access to files" changes](https://support.apple.com/guide/security/controlling-app-access-to-files-secddd1d86a6/web) in that version of macOS.

I was able to work around the problem by clicking "File > Open Recent > Clear Menu" as [described by this article](https://www.macworld.com/article/233799/how-to-fix-the-cannot-be-autosaved-bug-when-saving-documents-in-macos-apps.html), but I'm not sure whether that's a long-term solution.
