### ISSUE TITLE
can quickly open file in current window?

### ISSUE THREAD

**Issue by sidian123** [typora/typora-issues#2736]
By `Ctrl+P`, I can quickly open a file. It'a very usefull and convenient. But, it's better that open file in current file!! So, can you add a option that allow me to do this. Thanks!
`Ctrl+P`快捷键十分好用, 美中不足的是, 文件会在新窗口中打开. 要是能够在当前窗口打开就好了, 作者大大, 你能提供这个功能吗?

**Comment by abnerlee** [comment]
#1000
