### ISSUE TITLE
Single line spacing

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2737]
When I type and press Enter, the cursor skips a line to start the next sentence. I know that at the end of the 1st line I can put **br/** between <> , but I don't want to have to do that each time. Is it possible to change this, so there is no extra line spacing?
In *Preferences*, under *Whitespace / Line Break*, I have set *When writing* to *Preserve sequential whitespace and single line break*. I thought that would do the trick, but it does not.

Typora version 0.9.74

**Comment by sidian123** [comment]
I'm a paragraph

I'm a new paragraph
By a soft line break , you can still in the same paragraph. No `<br/>` , and no extra line spacing.

To do this , you can press `Shift+Enter`

**Comment by DutchPete** [comment]
@sidian123 Thank you, that works!

**Comment by petrux** [comment]
Although, this does't allow to indent the next line, right? This would be useful when writing direct dialogues in fiction/novels.
