### ISSUE TITLE
No theme (not even default) applied on print/export

### ISSUE THREAD

**Issue by brianlandry1e9** [typora/typora-issues#2738]
When printing or exporting there doesn't seem to be any theme applied. Most obviously the font is Times and tables have no borders or nice spacing (see attached pdf).  This occurs when printing to a printer, printing to pdf, or using export to pdf. If the file is exported to html the theme is applied. Uninstalling typora, deleting preferences, restarting the computer and re-installing typora did not fix this problem.

MacOS 10.14.6 (18G87)
Typora 0.9.9.27.4 (3345)
Safari 12.1.2 (14607.3.9)

See attached files
[test.pdf](https://github.com/typora/typora-issues/files/3503841/test.pdf)
[test.md.txt](https://github.com/typora/typora-issues/files/3503842/test.md.txt)

**Comment by ShineUnM** [comment]
I have the same issue on export to pdf, while export to docx via pandoc is ok

**Comment by brianlandry1e9** [comment]
An update on this. I transferred the file located at `/Users/brianlandry/Library/Preferences/abnerworks.Typora.plist` from a machine on which Typora had been installed for a long time and had working print functionality to the new machine that had problems. This fixed the printing issues.

I think this means that fresh installs of Typora have an incorrectly set preference (probably not exposed to the user) that results in no theme being used on print.

**Comment by joshmeads** [comment]
I have the same issue, unfortunately on a fresh install with no access to that plist file.

**Comment by ShineUnM** [comment]
@brianlandry1e9 Would you please share your "right' plist file? I tried to modify this file but it seems like a binary config file :( Thank you so much

**Comment by abnerlee** [comment]
should be fixed
