### ISSUE TITLE
Save stops working after reload due to external change (Windows, 0.9.74)

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2740]
Steps to reproduce:

1. Open a file on a samba share across the internet.  Make some changes, then save.
2. Do something that changes the file on the system where the file lives (e.g. a git checkout, patch apply, run a markdown table of contents builder, etc.)
3. Typora refreshes correctly.
4. Make a change, then try to save -- the dot indicating the file has changed doesn't go away, and the file isn't changed on disk.

At this point, the window is now stuck in this state for several minutes or until closed, and the only reliable way to get the file actually written is to overwrite it with "Save As...".  But the dot stays in place the whole time.  And unfortunately, using "Save As..." actually creates a new issue, because if you leave the file open long enough, the *old* version of the file (that was last saved with regular "Save") suddenly overwrites the newer versions on disk, as if the queued save finally happened but with stale data.

The fact that this takes several minutes and only happens on a Samba+VPN connection is reminiscent of #1445.  In fact, it seems that this is probably just an expansion of the conditions under which #1445 can occur.  Previously, it only occurred when the file panel was opened, but now it can *also* happen when a remote change is made.  This suggests that whatever the recent changes to remote change detection have in common with the file panel display, is the actual culprit for both problems.

Since the problem doesn't exist as long as the file pane is never opened and the file is never changed remotely, the problem isn't with the basic save functionality.  And since the new way of triggering the behavior only came about since I upgraded to 0.9.74 from 0.9.72, the recent changes to remote change detection are most likely involved.

**Comment by abnerlee** [comment]
seems same as #1445

Is your connection slow, or does other app also takes times to write file on your Samba drive?

**Comment by pjeby** [comment]
In order to investigate further, I've tried running `inotifywait -rm .` on the Linux side to observe filesystem activity, and here's what's happening:

* When I save initially, there is a flurry of activity on `.~README.md` and `README.md` (the target file), and the save completes in a few seconds
* But, as soon as I change the file remotely, there is a huge amount of activity from Typora, basically reading *every single subdirectory* underneath the current directory (all 2874 of them), performing directory accesses and checking for directory existence...  and then going back and opening and closing *every file* (all 12000 of them).

This process takes a **considerable** amount of time (like 10+ minutes), and is apparently somehow connected to the delay: trying to save while all this reading is going on results in `.~README.md` being created after a couple minutes, then written to after another few minutes, and then finally moved, completing the save, anywhere from 5 to 8 minutes later.

So, under normal circumstances, the save completes within a second or two, maybe several seconds when things are slow and the file is large.  But, once the file has changed remotely, or if the file pane is opened, it then takes *minutes* for the save to happen, as it competes with the reading (or at least opening) of 12000 or more files.  But once this process is completed, save speed goes back to normal.

So, I was wrong that the process *never* goes back to working properly; it seems I have simply never waited long enough for the reading of the 12000 files to finish (and in most cases where I've run into this problem, the directory trees involved were even bigger).

In any case, this is a lot more specific information: previously, only using the file pane triggered this "read every single file" behavior, but now, a remote change to the file being edited can trigger it, too.  In both cases, however, there is no apparent functional reason for Typora to read every file in every directory, or even check the existence of every nested subdirectory, just to handle a remote file change or display of the file browser (tree mode, not article mode).  I never use article mode, so it should not need to do such deep scanning of the remote system, and definitely not just because there was a remote change to the file.

**Comment by abnerlee** [comment]
Thanks for the information

You have 2874 children, or 2874 children, grant children, or deeper of the current folder?

"read every single file" may caused by `fs.watch` in order to live update side panel when file changes, not sure the file activity is caused by `fs.watch` itself or by Typora trying to update file tree after received change event of root folder (instead of target file). We will checked based on your information

**Comment by pjeby** [comment]
2874 total deeper children; the main directory only has about 12 or 13 subdirectories, but some of them have deep subtrees.

Note that this "read all the files" behavior only happens (as far as I can tell) the **first** time the file is changed outside Typora, and happens where the change is made directly on the remote system or over the network.
