### ISSUE TITLE
Can't disable spell check

### ISSUE THREAD

**Issue by reitnorF** [typora/typora-issues#2741]
I tried to disable spell check in File->Preferences->Editor->Spell Check. Whenever i clicked the "Disable Spell-Check" dropdown menu, it reverts back to "Auto Detect Language".

Then, i just realized that whatever dropdown menu i tried to click, it always revert back to "Auto Detect Language"

![BISkJ30dLk](https://user-images.githubusercontent.com/13418482/63072224-d4325980-bf4c-11e9-8a71-4d608a466880.gif)

**System Specification**
Typora version 0.9.74 (beta) on Windows 7 Ultimate  32 Bit

**Comment by reitnorF** [comment]
Solved...

Just found out that i could turn off spell check properly via Edit->Spell Check..

**Comment by abnerlee** [comment]
#2706
