### ISSUE TITLE
weird problem in linux

### ISSUE THREAD

**Issue by demonlj** [typora/typora-issues#2749]
system: ubuntu 18.04
typora: newest version

problem

-  all text color turn to grey
- some grammar not supported any more (unlike macos): `^2^` `~2~`
![选区_004](https://user-images.githubusercontent.com/1272742/63225732-25b93d80-c206-11e9-90e3-53a09fcd6336.png)
![选区_005](https://user-images.githubusercontent.com/1272742/63225753-5ac59000-c206-11e9-98fc-1d71f5b5ef47.png)

**Comment by abnerlee** [comment]
What's your theme, and could you try change a theme?

> some grammar not supported any more

Some should be enabled in preferences panel

**Comment by demonlj** [comment]
I have tried every theme, including github, night...

btw: after enable in preference panel, grammar problem fixed
