### ISSUE TITLE
latest update (0.9.9.28) breaks Typora theming under MacOS Mojave

### ISSUE THREAD

**Issue by arking7** [typora/typora-issues#2750]
none of the themes works, all turn white, no significant error message in console though.

I have to switch back to Typora-0.9.9.26.4 to make it all work again

<img width="647" alt="image" src="https://user-images.githubusercontent.com/6442118/63235819-b5de9d80-c26d-11e9-8caa-0913ed827bf5.png">

**Comment by abnerlee** [comment]
I cannot reproduce this.  Have you try restart Typora?

**Comment by NachiGithub** [comment]
I am having this issue as well. Restarting doesn't help.

**Comment by abnerlee** [comment]
@NachiGithub did you put Typroa under `/Applications`, also

Is there any file under `~/Library/Application Support/abnerworks.Typora/themes/` ?

**Comment by NachiGithub** [comment]
Yes. Typora is in `/Applications` and I tried a fresh installation with new `~/Library/Application Support/abnerworks.Typora/` folder. Same result.
