### ISSUE TITLE
too slow when drop-down opened file on osx-10.14.2

### ISSUE THREAD

**Issue by xialeizhou** [typora/typora-issues#2751]
versions:
![image](https://user-images.githubusercontent.com/6303773/63235608-c0e4fe00-c26c-11e9-878a-9d5aa8da2056.png)

![image](https://user-images.githubusercontent.com/6303773/63235624-d6f2be80-c26c-11e9-8d8a-d9d227b98878.png)

**Comment by abnerlee** [comment]
how about the latest version?
