### ISSUE TITLE
bold font not working on linux (ubuntu18.04, typora 0.9.75 beta)

### ISSUE THREAD

**Issue by SteinsWesley** [typora/typora-issues#2752]
![image](https://user-images.githubusercontent.com/16361105/63253916-58664300-c2a5-11e9-91eb-06fc271bfc84.png)
I couldn't make the font bold since one day last month. Ctrl+B  makes no difference.
Clean ~/.config/Typora/ path and reinstall  typora can't solve the problem.
Anyone knows why?

**Comment by DutchPete** [comment]
@SteinsWesley : that's strange. I am using Mint 19.2, which is based on Ubuntu 18.04, and have no problem with bold, whether with CTRL+B or a pair of double asterisks. Even b and /b between angled brackets works.

**Comment by SteinsWesley** [comment]
> @SteinsWesley : that's strange. I am using Mint 19.2, which is based on Ubuntu 18.04, and have no problem with bold, whether with CTRL+B or a pair of double asterisks. Even b and /b between angled brackets works.

yeah, I had no problem with bold before, but got into this trouble one day, maybe after a crash. And it seems that the font type also changed.  I cann't find the preference options to correct it.

**Comment by DutchPete** [comment]
@SteinsWesley : in the Preferences there is no way to set the fonts, which would be useful to have, like you indicate.

**Comment by abnerlee** [comment]
#2268
