### ISSUE TITLE
[Bug] Cmd+Click fails on some URLs

### ISSUE THREAD

**Issue by WANGJIEKE** [typora/typora-issues#2753]
OS Version: macOS Mojave 10.14.6
Typora version: 0.9.9.28

Looks like Cmd+click will fail on the URLs with encoded character because it attempts to encode already encoded URLs. Didn't happen in previous version (0.9.9.27.4).

Previous version (0.9.9.27.4)
![before](https://user-images.githubusercontent.com/21030118/63305748-f1449080-c29c-11e9-88d9-a0be73f06db6.gif)

Current version (0.9.9.28)
![after](https://user-images.githubusercontent.com/21030118/63305779-133e1300-c29d-11e9-9128-815acd7debea.gif)

**Comment by winterflags** [comment]
Same issue here. Typora misses the `:` in the URL when CMD+Clicking, although it is literally present in the .md file.

<img width="360" alt="Screenshot 2019-08-31 at 14 19 29" src="https://user-images.githubusercontent.com/14942350/64063871-c4786d80-cbfa-11e9-84c6-dc3429db4ae7.png">

<img width="688" alt="Screenshot 2019-08-31 at 14 19 23" src="https://user-images.githubusercontent.com/14942350/64063872-c7735e00-cbfa-11e9-9486-b03a54582e0b.png">

**Comment by abnerlee** [comment]
should be fixed
