### ISSUE TITLE
suggestion to the file navigation panel

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2754]
So far it is good, but I've got a small piece of suggestion.

Currently it can only show limited text files within the the folder, such as md, txt file, could you please extend it to make image, pdf, etc also visible and available, and when be clicked, like pdf, be opened with system pdf reader/editor, and images be opened with system image viewer.

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/1753
