### ISSUE TITLE
Macbook with touch bar. Suggestions not working properly

### ISSUE THREAD

**Issue by boubouhkarim** [typora/typora-issues#2756]
While writing in Typora, for example If i am writing `Typora is awe` the Touch Bar suggests me `"awe" awesome awesomeness`.

If I tap on the Touch Bar `awesome` I get in Typora **aweawesome** !!

Normally it should replace the **awe** by the word ** awesome** not contact it.

**Comment by AlexPasternak** [comment]
I typically don't use these, but agree that should work. I reproduced and can confirm the issue. Happy to test a fix if one is released.

**Comment by abnerlee** [comment]
should be fixed
