### ISSUE TITLE
Cannot add embedded HTML

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#276]
Hi there! I would like to accomplish a relatively ordinary thing in markdown - include a YouTube video.

```
# Some heading
Some text. See the video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/blahblah" frameborder="0" allowfullscreen></iframe>

Blah blah.
```

Also it would be helpful to have `<img>` tags with parameters (so that a user can for example determine alignment / size).

Please consider adding support for HTML 😄

**Comment by abnerlee** [comment]
#227 

`<img>` tag is already supported
