### ISSUE TITLE
Feature request: Portable Version for windows 

### ISSUE THREAD

**Issue by F3000** [typora/typora-issues#2760]
is it possible to create a version that don’t require admin rights to install ?

**Comment by abnerlee** [comment]
#415

**Comment by F3000** [comment]
This version is in Japanese . Is there an English instruction too ?

**Comment by EmiLithium** [comment]
Another issue with the linked workaround is that it does not stay up to date.

**Comment by PwrSrg** [comment]
I was using a **Portable BETA** for over a year and **LOVED it**!
But now that v1 is out, **it no longer works**. 😖

As soon as there is a **portable version**, you will get my money.
