### ISSUE TITLE
how to bind "Rename current file" in conf.user.json

### ISSUE THREAD

**Issue by christophcemper** [typora/typora-issues#2761]
I am trying to bind F2 to "Rename current file" but I'm not sure which function/menu name to use

It works for other things, but not this

I tried

"Rename File"
"Rename"
"File Rename"

for reference my config

    "Rename File": "F2"
  "keyBinding": {
    // for example:
    // "Always on Top": "Ctrl+Shift+P"
    "Source Code Mode": "F10"
    "Ordered List": "Ctrl+,"
    "Unordered List": "Ctrl+."
    "Rename File": "F2"
  },

**Comment by Weilet** [comment]
According to the [document](http://support.typora.io/Shortcut-Keys/#change-shortcut-keys), you can only set or change shortcut keys for **menu items** in **menu bar** in native window style.
Since `rename` not in the menu bar(It's in sidebar, right?),I don't think it can bind a hotkey

**Comment by abnerlee** [comment]
seems can be covered in #1001
