### ISSUE TITLE
CTRL-K not working on filenames anymore

### ISSUE THREAD

**Issue by christophcemper** [typora/typora-issues#2762]
Version 0.9.75 beta

CTRL-K doesn't complete the link for normal filenames anymore.

Absolute full urls (FQDN) e.g. https://docs.linkresearchtools.com/ work
but not relative path names

It seems like it's doing some kind of "FQDN-URL-Check" before inserting my buffer, which is not desired when doing relative links.

Please revert back to old behavior, or at least let me disable this behavior in user.conf

**Comment by abnerlee** [comment]
should be fixed in new release
