### ISSUE TITLE
Keyboard shortcut (cmd+shift+`) for inline code formatting not working

### ISSUE THREAD

**Issue by theMogget** [typora/typora-issues#2764]
MacOS 10.14.5, Typora v0.9.9.28 (3403)

As far as I can tell, it doesn't work in all the different modes (Focus/Typewriter/normal).

Would be really helpful to have this shortcut working. :)

**Comment by ChaseChoi** [comment]
The shortcut has changed to (control+`).

**Comment by abnerlee** [comment]
Shortcut key was changed. Use http://support.typora.io/Shortcut-Keys/#change-shortcut-keys for customization
