### ISSUE TITLE
Footnote links in pdf not working

### ISSUE THREAD

**Issue by jonaswoehl** [typora/typora-issues#2767]
When exporting a .pdf with footnotes inside it used to be possible to click the footnote inside the continuous text and it would take you right to the footnote rendered at the end of document. With the current 0.9.9.28 (3403) build on MacOS this doesn't seem to be working anymore.

**Comment by abnerlee** [comment]
Cannot reproduce this for now.

Please provide a sample *.md file and reopen this if it still exists
