### ISSUE TITLE
Fast 'typing' - Order of input is not respected

### ISSUE THREAD

**Issue by unblu-kschiess** [typora/typora-issues#2768]
I use macro-software to insert timestamps like this one: (10:23); this works by typing the characters via a virtual keyboard really quickly. The current beta-version of Typora (0.9.9.28 (3403)) will almost never get this right; Here's what I get when hitting my macro button ten times: 

(10:24)(:1024)(:1024)(:1024)(:1024)(:1024)(:1024)(:1024)(:1024)(:1024)

Somehow the order of the input keystrokes is not respected; my timestamps get jumbled up. This happens elsewhere in connection to my macros, but not in other software, so I think it has to do with how cursor is manipulated during key entry.

**Comment by abnerlee** [comment]
Still exist in latest version?
