### ISSUE TITLE
Drag n drop from File Tree to document leads to error and crash

### ISSUE THREAD

**Issue by rezanid** [typora/typora-issues#2769]
When I drag a file from the File Tree to somewhere in the document, the following error message box is displayed and after clicking OK button the application crashes.

![Typoral-dragNdrop-error](https://user-images.githubusercontent.com/14060208/63583124-ab3c4500-c59a-11e9-84c8-52cb130ac779.png)

## Expected behavior
The expected behavior is that, when I release the mouse button, it should generate a hyperlink in the location closest to the mouse pointer. The hyperlink should preferably in the following format for an image or non supported file.
`[file-name](relative-path-to-file-location)`

## How to reproduce
I'm using versoin 0.9.75 (beta) on Windows 10 1803.
1. Open a folder in Typora with a few markdown files in it.
2. Switch a an arbitrary file.
3. Make sure that the File Tree is displayed (Press Ctrl+Shift+3, if not).
4. Drag a file from the File Tree into the content area of the file that you are currently editing.
5. Before you even get the chance to release the mouse button, you will be prompted by the mentioned error message box.
6. If you click on the OK button, the application will crash.

**Comment by abnerlee** [comment]
should be fixed

**Comment by rezanid** [comment]
Yes, I confirm. Thanks a lot!
