### ISSUE TITLE
Word export of multiline cell contains <br /> instead of newline

### ISSUE THREAD

**Issue by QM-OSchwab** [typora/typora-issues#2771]
Hello, 

All is in the title : with version 0.9.75 , when exporting a table with multiline content in word format, the output Word file contains <br /> instead of newline . This is not the case in PDF for example.

**Comment by Nicolapps** [comment]
Related: I don’t know if this is expected behavior, but in the _editor_ (not export), the `<br />` tag is always shown, even when the table is not focused.
<img width="1347" alt="Screenshot" src="https://user-images.githubusercontent.com/7029582/66329850-870cab80-e92f-11e9-9c4d-3966fe63266a.png">

**Comment by abnerlee** [comment]
use #3246 for more detailed description
