### ISSUE TITLE
Suggestion: sidebar shortcut

### ISSUE THREAD

**Issue by mstfelq** [typora/typora-issues#2772]
Dear typora team,
I am really grateful for providing us with such a great and clean-design markdown editor. There are just few things that I strongly wished it was available.

1. Collapsible header sections.

2. Focus on the sidebar, and navigate using arrows ↑↓→←. A shortcut for changing focus on the sidebar would also be suitable.

3. Markdown files tagging system.

**Comment by jgclark** [comment]
I'm not part of Typora team, but thought I'd comment.
1. We have this already: Preferences > Appearance > Left Panel > Collapsible Outline on Left Panel.
2. I can imagine other ways of achieving this, but I agree it would be helpful to have quick keyboard-only navigation between different document sections.
3. Please expand on what you're hoping for. How would it work? What would the benefits be?

**Comment by abnerlee** [comment]
duplicate with #1001
