### ISSUE TITLE
Suggestion: visualization of converted markdown syntax to other formats

### ISSUE THREAD

**Issue by michaelpierrelee** [typora/typora-issues#2773]
Dear Typora maintainers,

As regular Typora user, I often write on Typora and then export to other syntax formats to be integrated, such as dokuwiki, latex, etc. I would suggest to add **an option to visualize a syntax format without the need to export it as a file**, allowing the user to just copy/paste into the system of interest.

More precisely:
- at the bottom, such as "toggle source code mode", an option is available : "toggle syntax format mode";
- the user clicks on it and a drop-down menu appears, with the available syntax formats;
- the user clicks on the syntax format of interest;
- then, the main window displays the source code in the syntax format of interest.

As I read in previous issues that Typora is designed only for markdown render, in this way, there is no need to allow the user to edit the code in "syntax format mode". **Thus, it is only a "pre-visualization tool", such as for printers before printing.** The Typora programmers can also implement it in other ways, such as opening a display window as for the printing pre-visualization, or even a "send to clipboard" as minimal new feature.

**In all cases, a "send syntax format to clipboard" button would be greatly appreciated.**

I know it is possible to modify the syntax preferences. However: 1/ it cannot allow for example a full dokuwiki conversion (or even in latex), 2/ it is quite painful to change it every time when the user wants to export the file (it is faster to copy/paste within a code editor and use find&replace tool).

I think this request would avoid excessive coding work compared to previous issues.

Thank you a lot in advance.
Best regards.

**Comment by abnerlee** [comment]
We don't have plans for this. "Export" may do the job
