### ISSUE TITLE
Feature request : add option to password protect .md files 

### ISSUE THREAD

**Issue by F3000** [typora/typora-issues#2776]
e.g. over TouchID on MacBooks or Password

**Comment by DutchPete** [comment]
You could consider installing a VeraCrypt volume on your hard disk and putting your Typora .md files there.
VeraCrypt is very easy to install and works like a dream. Furthermore, you can also park your other confidential files there, and encryption protection is not dependent on Typora or another app.

**Comment by abnerlee** [comment]
.md file are plain text file, which cannot have passwords.

This feature is a little out-of-scope, but can be done by #622 since TextBundle would be a zip format

**Comment by fiskeren** [comment]
+1 for encryption option

**Comment by ccchan234** [comment]
> .md file are plain text file, which cannot have passwords.
> 
> This feature is a little out-of-scope, but can be done by #622 since TextBundle would be a zip format

hi,

some other programs do and can provide plugin for encrypting .txt/.md.

e.g. notepad plus plus /w plugin nppcrypt 

obsidian, android's markor etc

however if the author would like to use the way of text bundle then it could be a solution

thank you.
