### ISSUE TITLE
Ability to copy text out of Typora as plain unstyled text

### ISSUE THREAD

**Issue by neilcronin** [typora/typora-issues#2779]
There should be a way to copy completely unstyled text out of Typora.  

I want to use Typora as a prose editor outside of rich text editors such as Word or Mail, but I cannot.

There is the "Edit/Copy Without Theme Styling" menu item, but there is no keyboard support for this, and no way to make this the default.

Also, the "Edit/Copy Without Theme Styling" does not copy unstyled text.  It copies the text with what appears to be webkit formatting/styling without any css.  e.g., pasting some text into a blank Word document this way does not paste with the document's insertion point's style, it pastes 12pt Times New Roman, regardless of what the document's style is.

Version 0.9.9.28 (3403)
MacOS 10.14.4 (18E226)

**Comment by DutchPete** [comment]
@neilcronin : you can get to the plain, unformatted text by doing <kbd>Cmd</kbd> + <kbd>/</kbd>. This will put you into the Source Code Mode, and you can copy plain text from there.

**Comment by neilcronin** [comment]
Awesome, can this be a pref so it can be a permanent setting?

I'm not going to use this app if doing this task needs to me to use a weird keyboard shortcut.  I want to type prose in a pretty way, then copy/paste that plain text into a rich text editor such as Mail or Word or Outlook.

I love this app, I just want to be able to get the raw text out of it by default! 

Thank you.

**Comment by DutchPete** [comment]
@neilcronin : what do you mean by a "weird" keyboard shortcut? Is <kbd>Cmd</kbd> + <kbd>/</kbd> weirder than other keyboard shortcuts? A keyboard shortcut usually involves using at least 2 keys.

I don't know if it is possible to have the Source Code Mode (SCM) as a permanent settings, though it seems it is not. But is it such a hassle to just use those 2 keys when you open Typora? It is not like it is a sequence of various shortcuts to get to the SCM.

**Comment by neilcronin** [comment]
I have accessibility issues, and a bad memory, so if this keyboard shortcut is not in the menu or available as a default I will never use this app.

If "treat all documents as text" is not on the roadmap, that's fine.  That just means this app is not for me.

**Comment by DutchPete** [comment]
@neilcronin : this keyboard shortcut IS in the menu under *View*.

**Comment by neilcronin** [comment]
I hear you, I work with two people who use this app as a text editor, and neither of them knew about this.  I didn't know about this either.  We went through the all the menus and prefs to figure out how to get plain text out of this app.  You might want to figure out a better place to put this menu item.

You sound like a jerk by capitalizing and italicizing in this way, it seems like you are verbally attacking me.

If you don't care about this feature, that's fine.

**Comment by DutchPete** [comment]
@neilcronin : allow me to inform you that I am not the dev, but merely a very happy user of this app. I did not attack you in any way, I tried to help you since you seemed to like this app. If you and your team of 2 went through the menu and did not see the shortcut mentioned, that is your problem.

Now, if you have a chip on your shoulder by feeling attacked instead of helped, and as a consequence feel the need to resort to ad hominem attacks and vulgarity, that is also your problem, not mine. I humbly suggest you take some basic education lessons and learn to discuss sensibly.

**Comment by abnerlee** [comment]
Copy will copy both styled and unstyled text in clipboard. When paste, paste unstyled text or "match style" will solve your problems.

BTW, how do you copy text from Chrome / Safari to Word or Mail? it seems a similar issue

**Comment by neilcronin** [comment]
You are right that "copy" from other rich text editors has the same problem.  

Consider adding "Edit/Copy Text" rather than a view option.  

I like Typora as a text editor a lot.  I can't use it if I need to change its display mode in order to copy text out of it.

Thanks.

**Comment by abnerlee** [comment]
It's now added under `Edit` menu
