### ISSUE TITLE
Use ctrl+tab to switch between files 

### ISSUE THREAD

**Issue by eeriksp** [typora/typora-issues#2786]
In many applications including web browsers (e.g. Google Chrome) and IDEs (e.g IntelliJ, VS Code) you can switch between files using `crtl` + `tab`.

I am missing this feature in Typora since I am working on multiple files and scrolling and clicking on file names makes switching very slow.

Would it be possible to add this feature in the future? Or perhaps there already is a solution which I am just not aware of?

**Comment by abnerlee** [comment]
same with #2782?
