### ISSUE TITLE
Zomm Out shortcut missing

### ISSUE THREAD

**Issue by legz** [typora/typora-issues#279]
The "Zoom Out" shortcut seems to be missing or incomplete.
The shortcut visible in the View menu shows "Ctrl+Shift+": the last key of the shortcut is missing. I tried a few ones (eg Ctrl+Shift+-) but none seems to work.

OS version : Windows 7 Pro SP1 64 bits
Typora version: 0.9.16
Reproduction steps:
- Open Typora
- Click on "View"
- Bug : "Zoom Out" shortcut show "Ctrl+Shift+"

**Comment by abnerlee** [comment]
Should work in new versions

**Comment by yakou32** [comment]
Well, unfortunately it seems that it doesn't :(
Zoom In works, but not Zoom Out (using an Azerty keyboard)
Also, I [read ](https://github.com/typora/typora-issues/issues/603 )that Zooming with Mouse Wheel was supposed to be supported with Windows?
