### ISSUE TITLE
"New" from context menu in Start Menu opens last document

### ISSUE THREAD

**Issue by gotjek** [typora/typora-issues#2790]
When I right-click Typora's icon in the Windows' Start Menu, there is a context menu with "New". It doesn't open a new blank file but the last closed document*.
Again : Typora is awesome, thank you for developing it, and for the fast paced releases !

(Typora 0.9.76, Windows 10)

(*) In General Preferences, "On launch" is set to "Restore last closed files and folders".

**Comment by abnerlee** [comment]
should be fixed in new release
