### ISSUE TITLE
Export to HTML adds blank lines to code sections

### ISSUE THREAD

**Issue by LiohMoeller** [typora/typora-issues#2791]
I have exported a document with code blocks to styled HTML. When I try to copy and paste Text from the codeblocks, a blank lines are added, between each line of code.

e.g.

```
su -
for f in $(find /usr/share/icons/Adwaita/ -name folder.png); do \
 ln -sr $f $(dirname $f)/inode-directory.png; \
done
```

leads to the following after copy and pasting:

```
su -

for f in $(find /usr/share/icons/Adwaita/ -name folder.png); do \

 ln -sr $f $(dirname $f)/inode-directory.png; \

done
```

I have created a small makrdown file and a HTML file exported with Typora

test.zip

When I copy the text to a Texteditor (e.g. gedit), it adds a blank line after each line of code. Copy & Paste within Typora works. Not tested with Code as I don't use that program.
[test.zip](https://github.com/typora/typora-issues/files/3570730/test.zip)

Besides that you can try to copy and paste a code block from one of the HTML sites I have created with Typora: https://linuxkurs.ch/kurs/Konfiguration.html
Just pick any of them which has multiple lines.

**Comment by LiohMoeller** [comment]
Any update on that?

**Comment by abnerlee** [comment]
should be fixed

**Comment by LiohMoeller** [comment]
Nope, still the same.

**Comment by abnerlee** [comment]
Can this be reproduce on Chrome?

**Comment by LiohMoeller** [comment]
I have tried Firefox to Gedit.

**Comment by abnerlee** [comment]
So you copy from Firefox to Gedit? This seems a bug of firefox, we can only control copy from Typora to other apps:

https://bugzilla.mozilla.org/show_bug.cgi?id=1273836

**Comment by LiohMoeller** [comment]
Why that? I am exporting to HTML? Why should I use Typora to view the HTML. It also does not work with any other browser btw.

**Comment by abnerlee** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1273836

We cannot control how Firefox put content into the clipboard, and how gedit parse content from clipboard.

However, in our test, Chrome get it correct.

**Comment by 0x3h** [comment]
I have the same issue with restructuredText export, code blocks adds new blank lines, no copy paste stuff just manually typing the code with Typora, the blank lines are just added in the file.rst but inside Typora its all fine! *I'm not sure but I think it did export correctly a couple times at first but then this blank lines issue started to occur.
