### ISSUE TITLE
Page not rendered according to theme / changing theme has no effect

### ISSUE THREAD

**Issue by renauddetry** [typora/typora-issues#2792]
Hello all,

Thanks a lot for Typora - love it.

Unfortunately, I've been experiencing trouble with it for the past couple of weeks. Changing theme (from the Theme menu) has no effect anymore - markdown is always rendered as shown in the image below, with a theme I don't recognize.

I'm only experiencing this problem in my main user account - in other accounts, themes work as expected. I've attempted to delete all account-specific Typora files, including themes, preference file, caches, etc, without success.

Has anyone experienced the same issue?

Thanks!

![Screen Shot 2019-09-03 at 14 29 17](https://user-images.githubusercontent.com/720662/64210115-449b0f00-ce57-11e9-8af5-82ed6a82e8d0.png)

**Comment by LaurentFough** [comment]
I am.
Been trying to debug it as well.
No go.

Which version of Typora are you using?

**Comment by LaurentFough** [comment]
This may be related: (_from Console_)
- - -
`tccd - Susbsystem: com.apple.TCC Category: access [ERROR]`

```console
Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: abnerworks.Typora, PID[16290], auid: 502, euid: 502, binary path: ‘PATH_TO_/Typora.app/Contents/MacOS/Typora'}, REQ:{ID: com.apple.appleeventsd, PID[399], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}`

**Comment by renauddetry** [comment]
Interesting. I'm using the latest version - Version 0.9.9.28.5 (3442)

**Comment by LaurentFough** [comment]
Ditto. Same version.
This started happening a couple of versions back — I thought it was a one-off, as they’ve been a couple of rapid&successive updates.

Still no luck, though.
Will spend some more time debugging that specific error and see where it leads

**Comment by LaurentFough** [comment]
> Interesting. I'm using the latest version - Version 0.9.9.28.5 (3442)

Is your Typora in the `/Applications` folder on the boot partition?
If no try moving it there and see what happens.

… or even to _(`/Users/your_username/Applications`)_`~/Applications` if you still that folder.

**Comment by renauddetry** [comment]
> If no try moving it there and see what happens.

Themes are working again - thanks! Did you figure why the location of the bundle has importance?

**Comment by LaurentFough** [comment]
I think it’s a permissions(access & rights) issues.
Need to do some more digging into all the `com.apple.TCC` stuff

**Comment by abnerlee** [comment]
Duplicate with #2750? 

Please ensure Typora has privilege for `/Users/{username}/Library/Application Support/abnerworks.Typora/themes/`, or just remove `/Users/{username}/Library/Application Support/abnerworks.Typora` and start Typora again, Typora will create the folder
