### ISSUE TITLE
Shift+Direction does not select in inline math mode

### ISSUE THREAD

**Issue by Rojetto** [typora/typora-issues#2793]
Pressing Shift+Left/Right does not select text when editing inline math code ($), it only moves the cursor. Shift+Home/End does work though and Shift+Left/Right also works in display math mode ($$). I'm using Typora 0.9.76

**Comment by Nicolapps** [comment]
I have the exact same issue on macOS (using _Typora 0.9.9.28.5 (3442)_). I would really appreciate this being fixed!

**Comment by abnerlee** [comment]
fixed in new release
