### ISSUE TITLE
Files can't be saved sometimes

### ISSUE THREAD

**Issue by 8bitBelief** [typora/typora-issues#2794]
When I finished writing something, saved and closed the software, when I opened it again, the things I wrote were lost. I tried it several times, sometimes there was no problem, but many times there was a problem, and I didn’t know. How to return to the previous version, this is really terrible, I hope to fix this problem quickly. version：0.9.9.28.4 (3437) Mac

**Comment by abnerlee** [comment]
which operations did you make?

**Comment by bei2love** [comment]
I have the same problem
I just used the title、list、code fences、quotes
![Uploading 1567645914254.jpg…](sample)

**Comment by 8bitBelief** [comment]
I just wrote some text and copied some text from somewhere else.

**Comment by 8bitBelief** [comment]
> which operations did you make?
> 
> for example: make list, diagram, code fences, switched to source code mode, reload file from disk, etc.

i used code fences, just wrote some text and copied some text from somewhere else. i saved by "command + s"  and closted by "command + w"

**Comment by 8bitBelief** [comment]
> which operations did you make?
> 
> for example: make list, diagram, code fences, switched to source code mode, reload file from disk, etc.

I just reproduced this problem. I opened a .md file, used the code fence, wrote some text inside, and then pasted some text under the code fence. Save, close, and open it will cause problems.

**Comment by lele3** [comment]
i have the same problem
i just use the ```javascript

When I finished editing, after saving and exiting, I reopened and the last edited thing disappeared

version: 0.9.9.28.4 (3437)
os: mac

**Comment by Miley927** [comment]
Same problem...

I opened a folder,  and often need to jump around in different files.
When I jump, this file will be saved as the version that was originally opened today.
I have to revert to the historical version. Usually the last version is the one I want.
This is like someone who has mischievously deleted it for you. Too strange!

Finally, I want to say that this problem is very serious. It may affect the promotion of the entire product. Hope that developers can solve it as soon as possible. It's not easy to find a good Markdown software.

version: 0.9.9.28.4 (3437) beta version for preview
os: mac

**Comment by abnerlee** [comment]
@8bitBelief possible to attach or send us a video when this happens? I will fix it once we figured out how to reproduce it.

**Comment by Miley927** [comment]
Hi guys,


I brought a screenshot with the problem description on it. 
Please refer to the attachment for details.
Hope to help!


Miley



At 2019-09-05 15:12:41, "AbnerLee" <notifications@github.com> wrote:


@8bitBelief possible to attach or send us a video when this happens? I will fix it once we figured out how to reproduce it.

**Comment by abnerlee** [comment]
Fixed in new release. Fix upgrade

**Comment by 8bitBelief** [comment]
> Fixed in 0.9.9.28.5 (0.9.77 for Windows/Linux). Try upgrade

Very amazing, can be repaired so quickly, thanks for bringing such excellent tools
