### ISSUE TITLE
0.9.76 New version cannot save file

### ISSUE THREAD

**Issue by Gutdub** [typora/typora-issues#2795]
In the newest version on windows 10, clicking "save" button or "discard" button didn't work. Only the "cancel" button worked. The dialog box just remained there and I had to shutdown the process manually. I tried restarting, running as admin and reinstalling. None of them works. My file isn't read only.

However, after I switched back to 0.9.72 version I can save again. I guess I'll just stay on the old version for now.

**Comment by abnerlee** [comment]
#2794

which operations did you make?

**Comment by Bekon241** [comment]
I have same problem just now licensed app version 1.9.3 on nobora linux.

![Image](https://github.com/user-attachments/assets/3e603f3c-97f4-4272-a3f1-b29074dd02aa)
