### ISSUE TITLE
Repeatable slow-downs while editing text

### ISSUE THREAD

**Issue by philipgoyal** [typora/typora-issues#2796]
I am experiencing repeated slow-downs while editing text running Version 0.9.9.28.4 (3437) with Mac OS X 10.14.6 (18G87).   This issue has persisted for a few weeks now.  Rebooting the machine itself has not fixed the problem.  

Attached is a zip file containing a short video showing the issue.  

The only way I can find to resolve the issue is to quit Typora and restart.  This fixes the problem temporarily, for about 30 minutes. 

I am not experiencing such slowdowns with any other currently-running software.

[Typora edit slow down (4 Sept 2019).mov.zip](https://github.com/typora/typora-issues/files/3575977/Typora.edit.slow.down.4.Sept.2019.mov.zip)

**Comment by philipgoyal** [comment]
Here is a video showing the slow down.  In the left pane, Activity Monitor is running, showing the % CPU that Typora is using.  On the right is a typora window in which I am typing.  As I start to type, the % CPU jumps to 60-80%.  When I stop typing, this drops to a few %.

If I close the window and reopen the file (without actually quitting Typora), the problem resolves itself, only to return within about 30 minutes.

https://www.dropbox.com/s/s37fpm6aq1wkk82/typora%20slow-down%20%2819%20sept%202019%29.mov?dl=0

**Comment by abnerlee** [comment]
merge into #68
