### ISSUE TITLE
Typora is not re-opening all of previous windows when relaunching

### ISSUE THREAD

**Issue by Ken0sis** [typora/typora-issues#2797]
I'm on Typora version 0.9.9.28.5 (3442) and OS is Mac 10.14.5 (18F132).  For my system preferences, I've unchecked "Close windows when quitting an app".  But for some reason, it looks like Typora is actually closing windows whenever I quit it.  Then when I relaunch, sometimes it loads the windows and sometimes it does not (I have to go under File and tell it to reopen last closed windows).  

I organize my files into different windows with specific ordering.  I need these windows to reload in their ordering whenever I relaunch, or else my workspace is kind of lost.  

Anyone else experiencing this issue??

**Comment by Ken0sis** [comment]
@abnerlee You've tagged this item as "Need more info".  Can you please let me know what specific info you need, so I can help solve this problem with you?

**Comment by Ken0sis** [comment]
@abnerlee Here's some extra info that might help:  

- The windows will reopen in the same order at relaunch if I don't have untitled documents (files that are not saves).  
- But if I have untitled documents, then I have to use the "Reopen Closed File" to get back the other files.  However, they are not reopened in the same ordering and windows, so I have to re-arrange.

**Comment by abnerlee** [comment]
I cannot reproduce this, not sure which details are missing

**Comment by abnerlee** [comment]
@Ken0sis 

How many Typora windows are there when you quit Typora?

Does those "untitled" contains "edited" mark before quit?

Did typora crash on quit?

**Comment by Ken0sis** [comment]
@abnerlee Please fix issue #2883.  This issue is not the same as Untitled documents being deleted.

**Comment by Ken0sis** [comment]
@abnerlee I think you're potentially confused about two separate phenomenons, but I'll try to provide the details.

1.  There are two separate issues:  Windows not relaunching in the correct order, and unsaved Untitled documents being deleted when Typora is relaunched.  They are are not necessarily the same thing.  
2.  When Typora is quit and relaunched, I observe both of the above 2 problems even when there is only 4-5 windows.  
3.  Yes, the Untitled documents contain "edited" marks when quitting.

**Comment by Ken0sis** [comment]
@abnerlee I will split this issue clearly into two.  My apologies if my description so far has been confusing.
