### ISSUE TITLE
using dictation on mac deletes previously detected words

### ISSUE THREAD

**Issue by dietoff** [typora/typora-issues#2798]
This seems to be a bug that did not exist in earlier versions:
on mac, start dictation in layout mode and say a few words. the detected words appear underlined. after dictation finished, start it again and continue dictating. the new words will overwrite the words dictated earlier instead of appending. 

A workaround: move the cursor after stopping dictation. But it is still problematic since dictation on mac often starts and stops on its own.

**Comment by AlexPasternak** [comment]
I would bet at least a few coins it's a regression introduced by this fix
https://github.com/typora/typora-issues/issues/2783

**Comment by dietoff** [comment]
my thought as well :) i am a bit focused on assistive typing since i broke my arm ...

**Comment by abnerlee** [comment]
The dictation seems buggy on Webkit

e.g. open http://mikaelharsjo.github.io/content-editable/components/content-editable/demo.html in Safari, then the words insert via dictation will be duplicated.

We will do some hot fix

**Comment by abnerlee** [comment]
fixed in new release

**Comment by dietoff** [comment]
Excellent, thank you!
