### ISSUE TITLE
 Invalid focus mode

### ISSUE THREAD

**Issue by butydrd** [typora/typora-issues#2799]
- version: 0.9.77(beta) Window10
![image](https://user-images.githubusercontent.com/29162393/64381037-e0e63100-d064-11e9-9920-104b6030c50c.png)

Every click the button always show the popup

![image](https://user-images.githubusercontent.com/29162393/64381352-944f2580-d065-11e9-9666-ebb729615ac7.png)

`<body>` dom has no class `on-focus-mode`

![image](https://user-images.githubusercontent.com/29162393/64381561-0a538c80-d066-11e9-90da-1785a79a8ee6.png)

**Comment by abnerlee** [comment]
The button will not check current state.
