### ISSUE TITLE
language check has a bug when checking the italic words

### ISSUE THREAD

**Issue by lj8385174** [typora/typora-issues#28]
I am using the windows version 0.7.6
When checking the italic word, the last letter seems not be accounted:

![image](https://cloud.githubusercontent.com/assets/3823826/12109247/4120b79a-b3bb-11e5-980a-33710896ba68.png)

I am using Windows 10  10586

**Comment by abnerlee** [comment]
Close since there all lots of updates after this. Please reopen this if it still exists
