### ISSUE TITLE
"Actual size" shortcut doesn't work

### ISSUE THREAD

**Issue by legz** [typora/typora-issues#280]
The "Actual size" shortcut doesn't not work. The shortcut visible in the View menu shows "Ctrl+Shift+0" but :  
- This shortcut is similar to the "Focus Mode" shortcut
- Press Ctrl+Shift+0 does nothing

---
OS version: Windows 7 Pro SP1 64 bits
Typora version: 0.9.16
Reproduction steps:
- Open Typora
- Zoom in a few times
- Press Ctrl+Shift+0 -> the view doesn't go back to the actual size.

**Comment by abnerlee** [comment]
fixed in new version
