### ISSUE TITLE
Sort by file name is not welldone

### ISSUE THREAD

**Issue by pengliwds** [typora/typora-issues#2800]
version:0.9.9.28.4 (3437)
systerm:macos mojave 10.14.6

it can not sort as this:
- 1.1
- 1.2
- 1.3
- 1.11

![image](https://user-images.githubusercontent.com/40412310/64395792-063b6500-d08e-11e9-8f39-d2298f17b0ee.png)

**Comment by abnerlee** [comment]
Use "sort naturally".

**Comment by pengliwds** [comment]
> Use "sort naturally".

Not satisfied effect.
This is the [reporsitory](https://github.com/geektime-geekbang/geektime-ELK.git)
`https://github.com/geektime-geekbang/geektime-ELK.git`

![image](https://user-images.githubusercontent.com/40412310/64498683-33834f80-d2e8-11e9-95a4-c0ece8aee2b6.png)

**Comment by abnerlee** [comment]
should be fixed in new release
