### ISSUE TITLE
Typora cannot find pandoc

### ISSUE THREAD

**Issue by tyway9** [typora/typora-issues#2801]
Hi, I am using Ubuntu Mate 19.04 and installed pandoc and all possible packages along with it I even restarted my system to see if the "install pandoc" request goes away. To no avail.

Typora constantly requests for pandoc even after it has been installed. Any suggestion will help. 

Just to add I used the snap software to install typora from ubuntu mate 19.04
Thanks

**Comment by abnerlee** [comment]
should be fixed.

If still cannot find, see https://support.typora.io/Install-and-Use-Pandoc/#config-pandoc-path
