### ISSUE TITLE
Bullet lists make editing cumbersome

### ISSUE THREAD

**Issue by jmcd040** [typora/typora-issues#2803]
Typora 0.9.77 on Windows 10
If I hit return at the end of a bullet list sentence, a new bullet of the same indentation is created. It is very difficult to outdent this. I have to backspace to delete the bullet, then hit shift-tab to outdent. Since all other editors simply outdent with shift-tab, I'm always forgetting this extra step.  It would be more standard to allow shift-tab to outdent.

**Comment by skyblue002** [comment]
Have you tried `ctrl+]` and `ctrl+[` to increase and decrease indentation? I'm using Typora on Linux, so it may not be the same. But, on my menu, `Paragraph > List Indentation` it has two options, one for indenting and one for outdenting a list item. On the menu items, the shortcuts are listed. I checked the shortcuts and they worked for me. This is, indeed, a lot easier than having to deal with backspacing, which I had been doing before.

**Comment by abnerlee** [comment]
duplicated with #1958
