### ISSUE TITLE
Typora Installation Package Identified as Trojan.Detplock in Windows Security

### ISSUE THREAD

**Issue by WXGopher** [typora/typora-issues#2804]
![pic](https://user-images.githubusercontent.com/9498694/64465174-559e8700-d0c8-11e9-8737-ecb6c39d9732.png)

OS: Windows 10 build 1809.
Packaged downloaded from Typora official website.

**Comment by Kuangji** [comment]
Same here. 

Detected by Microsoft Security upon self upgrading as Trojan:Win32/Detplock.

Filename: typora-update-x64-0.9.77.exe
OS: Windows 10 build 1903

**Comment by MisterTeacher** [comment]
I fanced the same error.
Is this error serious?

Filename: typora-update-x64-0.9.77.exe
OS: Windows 10 build 1903
![image](https://user-images.githubusercontent.com/45089019/64469566-54746500-d16f-11e9-9c0f-eedf7bf4268d.png)

**Comment by baileyherbert** [comment]
Possible false positive. Only Windows Defender is detecting it:

https://www.virustotal.com/gui/file/40e0feadd61ab12baf4967456f0c3c44e71ef3122bfca28b334a47966aafe175/detection

**Comment by baileyherbert** [comment]
After updating Windows Defender's definitions via Windows Update, the installer is no longer being detected as Trojan.Detplock from my end. Can anyone else confirm?

**Comment by keebeegee** [comment]
can NOT confirm - running Secuity Intelligence Version 1.301.714.0

**Comment by baileyherbert** [comment]
That's interesting – 1.301.714.0 here too, and it's repeatedly failing to detect the file any further. I've re-downloaded it multiple times and manually scanned. 😕

**Comment by abnerlee** [comment]
It is a false positive, you could found the scan result from other anti-viruses at https://www.virustotal.com/gui/file/40e0feadd61ab12baf4967456f0c3c44e71ef3122bfca28b334a47966aafe175/detection

**Comment by abnerlee** [comment]
Microsoft have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions. 

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures” 
3. Run "MpCmdRun.exe -SignatureUpdate" 

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
