### ISSUE TITLE
Weird code fence shortcut issue

### ISSUE THREAD

**Issue by xDeuiii** [typora/typora-issues#2806]
I'm using a Cooler Master Masterkeys Lite L keyboard connected to my laptop. When I use the shortcut for code fence on the LEFT side of my keyboard (left)Ctrl + (left)Shift + K, it doesn't seem to work, the code fence doesn't appear. But when I use the RIGHT keys on my keyboard for the same shortcut, works just fine. My laptop keyboard also works fine on both sides for the code fence shortcut.

All the 3 left individual keys; Ctrl, Shift, K work fine on the Cooler Master keyboard. Weirdly enough, when I tried other shortcuts on the left side of the keyboard, all worked no problem; 
- ordered list: Ctrl + Shift + [ 
- code: Ctrl + Shift + `
- Heading: Ctrl + 2
- math block: Ctrl + Shift + M

It seems only the code fence shortcut won't work.

What I tried so far:
- Updating Typora, currently on 0.9.77
- Unplugging and plugging the keyboard
- Changing USB ports
- Restarting my laptop

**Comment by abnerlee** [comment]
Sorry, but I cannot help with this one. There's no logic to distinguish left ctrl and right ctrl, and also your laptop keyboards works fine.

Would you try if the same shortcut keys works on other apps or not?
