### ISSUE TITLE
Typora 0.9.77 detected as Trojan by Windows Defender

### ISSUE THREAD

**Issue by daniele-sforza** [typora/typora-issues#2807]
I was upgrading to the latest version today but Windows Defender detected a Trojan in the installer

**Comment by FSXAC** [comment]
Yep same here:

![image](https://user-images.githubusercontent.com/7558835/64481555-7b905e00-d192-11e9-8dac-e5a0c3deac83.png)

Win 10 18362.295

**Comment by xDeuiii** [comment]
I can confirm, same thing here too. I just allowed the app for now

**Comment by lloyd094** [comment]
Can also confirm. I see the same message as the picture shared above.

**Comment by Fr33raNg3r** [comment]
I can confirm.
![image](https://user-images.githubusercontent.com/15374658/64484741-3e3ad780-d249-11e9-80f3-d1c90fa18bc8.png)
Noly typora-update-x64-0905.exe have warning.

**Comment by abnerlee** [comment]
Please update Windows Defender in this way:

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
