### ISSUE TITLE
Windows Defender `Trojan:Win32/Detplock` false positive

### ISSUE THREAD

**Issue by iansannar** [typora/typora-issues#2809]
Today I ran the auto-updater to update from version 0.9.76 to 0.9.77. As soon as the download completed, Windows Defender had a fit, claiming that the update was a trojan called `detplock`.

![image](https://user-images.githubusercontent.com/8443754/64480872-cbb8f180-d18d-11e9-80a1-e000f812a42f.png)

I tried again with the same result. I doubt the update was compromised with malware in any way, but having a false positive is still a big issue for any commercial product since a lot of people unconditionally trust their antivirus.

I am running Windows 10 x64 Version 1903.

**Comment by abnerlee** [comment]
#2807
