### ISSUE TITLE
Better image / asset management

### ISSUE THREAD

**Issue by LukeDefeo** [typora/typora-issues#2814]
My use case is that i want typora to replace Evernote. Basically I have a root typora directory and i place all my notes in subfolders under it. Typora is superior to evernote but i cant figure out the best way to handle images. 

Ive tried various approaches but i think the best is to use a local hidden path for each markdown file:

 `./.assets/${filename}` 

Advantages of this:

1. Doesn't clutter tree view since folder is hidden ( this is huge for me as typora doesnt have any image editing functionality so having all the assets folders in the sidebar goes against its minamal feel)
2. Easy to assets for notes since they are colocated
3. Easy to share notes and assets since they are colocated

Now for the problems:

1. When I move a file (that i created in Typora) from one location to anther it fixes the image src in the markdown rather than moving the image only to a new .assets folder. This probably makes sense in some use cases but here it means that the images wont be in the 'right' location relative to their note after several moves and you lose the advantages
2. I have imported a bunch of notes from evernote via joplins export functionality. This creates the following structure: 

```
/out/
       notes/note1.md
       _assets/123214124.jpg
                   ...

```

Note1.md will have a reference to _assets.  Now if i try to move note1.md to a subfolder it doesnt fix the reference to _assets and the image is broken. It seems that since these images are following a slightly different convention there isnt a way to tell typora to fix the image structure so it conforms to the conventions

In order to support my use case typora would need the following:

1. A way to 'fix image references' This is when you have imported markdown from other sources that have their images referenced in a different way to what the image settings have defined. It would process each local asset reference by copying / moving the file to the local directory and change the image source.  This could be a command you issue at a file level
2. An option in the images settings called something like 'Associate assets with markdown' With this option on any move of a file (in typoras tree view) would move the asset folder along with it. This assumes you have a local asset folder per note of course. Obviously this wont be able to handle changes made to the file system outside of typora but as long as the user uses relative paths it should be ok.

Im open to other options. I realise I could probably implement 1 with a python script but it would be cool if typora has the ability to be more hands on with asset file management

**Comment by abnerlee** [comment]
#2198
