### ISSUE TITLE
View->Actual Size shortcut key doesn't work.

### ISSUE THREAD

**Issue by ChuckM2** [typora/typora-issues#2815]
OS: Win10 64-bit
Typora version 0.9.76 (beta)
In menu, View->Actual Size shortcut key is listed as Ctrl+Shift+0.  However, typing shortcut key Ctrl+Shift+0 doesn't do anything.

**Comment by abnerlee** [comment]
https://github.com/Microsoft/vscode/issues/2585

**Comment by abnerlee** [comment]
Changed to ctrl+shift+9 on Windows since no app can capture ctrl+shift+0, see microsoft/vscode#2585
