### ISSUE TITLE
Support Ctrl+Scroll wheel up/down for zooming like Chrome, Word, and many other apps.

### ISSUE THREAD

**Issue by ChuckM2** [typora/typora-issues#2816]
Request for Windows 10 OS.
Support Ctrl+Scroll wheel up/down for zooming like Chrome browser, MS Word, and many other apps.

**Comment by abnerlee** [comment]
We don't have plans for this

**Comment by gamgamstylep** [comment]
Please reconsider.

**Comment by ChuckM2** [comment]
> Please reconsider.

I'm not a contributor to this project, but I encourage you to file a new issue if you want this feature. I'm not sure the developer will see comments once the issue is closed.
