### ISSUE TITLE
"Reveal in Finder" dosn't work for search results

### ISSUE THREAD

**Issue by 2b** [typora/typora-issues#2818]
Typora: 0.9.9.28.5 (3442)
macOS: 10.14.6 (18G95)

When you try to use "Reveal in Finder" function in popup menu (on right mouse button click)  on search results, nothing happens.

![qs5ZVv](https://user-images.githubusercontent.com/829041/64598375-4b2e0700-d3c0-11e9-80bb-ba24799cf2ca.gif)

**Comment by 2b** [comment]
"Copy File Path" does not appear to be working either.

**Comment by abnerlee** [comment]
should be fixed
