### ISSUE TITLE
Video player not loading local videos

### ISSUE THREAD

**Issue by jediwarrior77** [typora/typora-issues#2819]
I have a manual with many local videos inside Typora. But the videos are not displayed as a thumbnail. There is empty space, then there is a lazy loading effect, then is a white thumbnail and the video does not load at all when I click play button except if I wait 1 minute and then scroll the time bar to activate the video. Something is terribly wrong with the implementation of local video files display inside Typora. This happened either with new version or either after adding more than 30 videos. I remember with few videos when I started it worked fine.

**Comment by abnerlee** [comment]
merge into #2774

What's your OS / Typora version? Which video format / size do you use?
