### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2820]
Hi Abner,

I would like to make a donation as an appreciation of your excellent app, which I use every day. I know you won't charge for it till it gets out of Beta, but you spend an enormous amount of time  to keep improving Typora, and you get nothing in return.

The only thing is that I do not want to use PayPal nor my credit card nor Patreon.
Do you have a European bank account for me to make a donation?
If so, please send me details, incl. the exact name of the account and the IBAN number.

**Comment by AlexPasternak** [comment]
It's a great thought, but personally I'd rather the app get to 1.0 and be a commercial product, not donation-ware.

**Comment by DutchPete** [comment]
@AlexPasternak : I did not infer that Typora should be donation-ware. Typora has been out for quite a while now and has reached a good level of maturity compared with other new markdown editors. So in my view Abner deserves to be rewarded as long as the app is still not out of Beta.

Typora is a good product so Abner is entitled to charge for it. I would not like him to get disinterested for lack of funds. Taking a donation/donations now does not mean at all that he cannot proceed to a commercial product.

**Comment by abnerlee** [comment]
It will be a paid app after v1.0, so there's no donation link / button. 

If you are aware of this and still insist, paypal can send money to anyone with email address. So you could donate to <hi@typora.io> via paypal

**Comment by DutchPete** [comment]
@abnerlee: I am sorry to have "insisted", it was certainly NOT meant as such, so I am somewhat surprised you use this kind of terminology.

Still, I do want to thank you for a good app that I believe is one of the best markdown apps out there. I will not make a donation, I would not like to upset you any further anyway.

I shall wait for v1.0 to pay. My apologies once again to have raised the issue.

**Comment by AlexPasternak** [comment]
@DutchPete re: "somewhat surprised you use this kind of terminology", when conversing online with folks for whom English is a second language, criticizing and taking offense at specific word choice is not something I recommend. Sounds like you're welcome to donate before 1.0 release after all, which is what you were requesting in the first place.

**Comment by DutchPete** [comment]
@AlexPasternak: with a name like Abner Lee it is not obvious that his mother tongue is not English, although some of his phrases made me wonder. But then again, nowadays even some people whose mother tongue is English are bad at spelling or forming phrases.

Having said all that, @abnerlee does tend to use short, staccato phrases which can come across as unpleasant. I never said anything about it, but when someone offers to make a donation he should be a bit more careful with his choice of words, even if English is not his mother tongue. That is just my opinion, FWIW.

And yes, I am welcome to donate before the release of v1.0, and no, his "offer" is not useful because I indicated in my OP that I do not want to use Paypal.

BTW, thanks for giving me your opinion twice in this thread, I would also have managed without ;-)

**Comment by abnerlee** [comment]
Sorry for the unpleasant expression, didn't know "insiste" sounds rude here. Maybe "demand" is a better word in this case?

Well, anyway, I currently don't have European bank account, so maybe waiting for the v1.0 release becomes a better option for now.

**Comment by DutchPete** [comment]
OK Abner, no problem, I'll wait. Once again, thanks for a very good markdown editor, one of the best ones out there, as far as I am concerned.
