### ISSUE TITLE
Tags/Hashtags?

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2821]
Am I correct in saying that Typora does not have a tagging system? If that's correct, is there any intention to introduce one?

**Comment by vassudanagunta** [comment]
See #1393, which should probably have "hashtag" in its title so people can find it.

**Comment by DutchPete** [comment]
@vassudanagunta 
> You should add your opinion directly on that Issue.
>
Done.

**Comment by abnerlee** [comment]
duplicate with #1393
