### ISSUE TITLE
[FEATURE REQUEST]: Find & Replace

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2822]
I have seen and used the Find feature <kbd>CTRL</kbd>+<kbd>F</kbd> is to find a term or terms within the open file, while <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> is find within any of the files in the directory, but I have not found any Replace feature.

Could this be added?

**Comment by abnerlee** [comment]
merge into #2824
