### ISSUE TITLE
"Whole Word" and "Case Sensitive" buttons on the search panel are enormously big.

### ISSUE THREAD

**Issue by sleeplynerd** [typora/typora-issues#2823]
When I press "ctrl+F", a search field shows up along with these two huge pics whose supposed to be small option buttons.
Ubuntu 18.
[Image is shared here](https://ibb.co/wRTCNzf)

**Comment by abnerlee** [comment]
which typora version / theme?

how Typora is installed, via apt-get or other methods?

**Comment by sleeplynerd** [comment]
Via apt-get. But I can't remember the version. However, right now everything works flawless. The issue appears to be fixed with the last upgrade. If it emerges again I will reopen the issue.
