### ISSUE TITLE
Preferences text UI display problem

### ISSUE THREAD

**Issue by WitherZuo** [typora/typora-issues#2827]
### I'm using:  
Typora version: 0.9.77 (Beta)  
Theme: GitHub (Default Theme)  
OS: Windows 10 build 18362.10019  

### Issue:  
In new-designed (or redesigned) preference user-interface, some (or most) **preference item title** can **not align** with its **corresponding preference item**. I try to use custom css to modifiy them but too many things need change.  

### Screenshot:  
Notice the red line:  
![Snipaste_2019-09-15_13-16-04](https://user-images.githubusercontent.com/25317916/64916956-ce829a80-d7bc-11e9-875b-1176c6dd2261.png)
![Snipaste_2019-09-15_13-15-47](https://user-images.githubusercontent.com/25317916/64916957-ce829a80-d7bc-11e9-8e3b-c5e9e2d4102a.png)
![Snipaste_2019-09-15_13-15-27](https://user-images.githubusercontent.com/25317916/64916958-cf1b3100-d7bc-11e9-8d75-fcb016ff5e66.png)
![Snipaste_2019-09-15_13-15-07](https://user-images.githubusercontent.com/25317916/64916959-cf1b3100-d7bc-11e9-89e1-9c9c2fb7f4cd.png)
![Snipaste_2019-09-15_13-14-21](https://user-images.githubusercontent.com/25317916/64916960-cf1b3100-d7bc-11e9-8242-2714a05907ca.png)
![Snipaste_2019-09-15_13-13-47](https://user-images.githubusercontent.com/25317916/64916961-cfb3c780-d7bc-11e9-9b18-40595257af90.png)

**Comment by abnerlee** [comment]
should be fixed
