### ISSUE TITLE
"Find" syntax/terms

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2828]
In the support page I have not found any info about this.
So, to give a few examples, if I type:

* `apples pears` is that treated as "apples and pears" or "apples or pears"?
* are `"apples and pears"` or `john doe` treated as an exact match search? If not, is possible to do an exact match search and what is the syntax for it?
* is there a difference between search options for the opened file, and search options for all the files in the directory?

**Comment by abnerlee** [comment]
#2824
