### ISSUE TITLE
How can I set the width of export PDF

### ISSUE THREAD

**Issue by zhanghedr** [typora/typora-issues#2830]
I am using github theme. I want to change the width of export PDF. Now I am changing github.user.css. But I don't know what css to set. I am using the following css, font-size is working but max-width is not. Please help! Thank you!

`#write {
    max-width: 1000px;
    margin: 0 auto;
    padding: 0px;
    padding-bottom: 100px;
    font-size: 12px;
}`

**Comment by abnerlee** [comment]
#998
