### ISSUE TITLE
EPUB export a mess.  No PDF output options?

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#2833]
The PDF and HTML export in Typora looks great, but the EPUB export is a useless mess.  I tried to use pandoc, but I can not seem to get pandoc to do a correct job of converting to ANY format... there is always some issues; layout garbles, style missing, incorrect margins, etc.  This may simply be my lack of pandoc expertise (so if anyone happens to know the magic pandoc incantations for MD -> PDF, HTML, EPUB or other, please share).

The only way I can get a proper EPUB is to export to HYTML and then import to sigil, then save as EPUB.

I also can't see any way to properly format the PDF for 'book ready', (alternate margins), or defining headers, such as page num, changer name, etc.  Can this be done in the YAML front matter?  If not, that would be an excellent addition.

**Comment by abnerlee** [comment]
Typora does not provide provide epub function, it is done by Pandoc. So you could try https://pandoc.org/epub.html and see if it works. 

> there is always some issues; layout garbles, style missing, incorrect margins, etc. 

we cannot imagine the issue here, please provide more details.


> I also can't see any way to properly format the PDF for 'book ready', (alternate margins), or defining headers, such as page num, changer name, etc. Can this be done in the YAML front matter? If not, that would be an excellent addition.

This is duplicate with other issues.

**Comment by baardev** [comment]
I didn't provide details because I assume the problems were greymatter-related, but I was hoping to discover how Typora calls pandoc, i.e. what the equivalent pandoc command line would be.  The instructions at https://pandoc.org/epub.html do not produce the correct output, but this is probably because my document is different in some way that the example doc (how images are placed, Hebrew and Greek chars, math stuff, etc), but as Typora uses pandoc, then clearly pandoc IS capable of doing it, but it does it very differently than what the pandoc example shows.
