### ISSUE TITLE
Sort Items Alphabetically function for lists, tables, and any other collections

### ISSUE THREAD

**Issue by nanoant** [typora/typora-issues#2835]
Such a function could be applied to any list, ordered, task list, etc. e.g.:
`Edit > Sort Items Alphabetically`
~~~
1. Oranges
2. Apples
3. Berries
~~~
would yield:
~~~
1. Apples
2. Berries
3. Oranges
~~~
This is related to #1088 which includes Table Sort functionality. Maybe this could be combined into single `Edit > Sort Items Alphabetically`.

**Comment by abnerlee** [comment]
Merge into #1088
