### ISSUE TITLE
Spell check sometimes stops working

### ISSUE THREAD

**Issue by ldellisola** [typora/typora-issues#2836]
I have multiple files where Typhora won't do any spell checking even though is enabled. This seems to be random as I may be writing in a file where spell checking works perfectly but when I create a new file, it will be broken for that file.

I use spell checking in Spanish.

**Comment by abnerlee** [comment]
OS?

**Comment by ldellisola** [comment]
I’m running windows 10.

**Comment by abnerlee** [comment]
#2706
