### ISSUE TITLE
Changing theme in Theme menu does not change the theme in 0.9.9.26 later on macOS

### ISSUE THREAD

**Issue by Herbert8** [typora/typora-issues#2839]
macOS Version: 10.14.6
Typora Version: 0.9.9.26 later

Changing the theme in the Themes menu does not actually change the UI theme. When I select one of the other options, the UI theme remains as the default Github theme.

I've reinstalled after deleting all local settings and I still encounter the issue.

**Comment by Herbert8** [comment]
![Console Snapshot](https://user-images.githubusercontent.com/3112923/65317031-966cc480-dbcd-11e9-989f-853273394226.png)

**Comment by Mara-Li** [comment]
Same problem....

**Comment by Herbert8** [comment]
> Same problem....

I thought that only I encountered this problem, but did not expect a lot of people to encounter this problem.

**Comment by arking7** [comment]
Seems like a permission problem, thanks Herbert8  for the find.

I moved abner files to a partition other than the macOS partition, and it worked again.

**Comment by arking7** [comment]
see #2750 for more info

**Comment by Herbert8** [comment]
> Seems like a permission problem, thanks Herbert8 for the find.
> 
> I moved abner files to a partition other than the macOS partition, and it worked again.

I have moved user's Home directory to the other disk partition, and then created a symbol link to macOS partition. Is it caused by this problem?

**Comment by abnerlee** [comment]
Duplicate with #2792? 

Please ensure Typora has privilege for `/Users/{username}/Library/Application Support/abnerworks.Typora/themes/`, or just remove `/Users/{username}/Library/Application Support/abnerworks.Typora` and start Typora again, Typora will create the folder

**Comment by hackzx** [comment]
> Duplicate with #2792?
> 
> Please ensure Typora has privilege for `/Users/{username}/Library/Application Support/abnerworks.Typora/themes/`, or just remove `/Users/{username}/Library/Application Support/abnerworks.Typora` and start Typora again, Typora will create the folder

it's still having the same error.
