### ISSUE TITLE
Bug in lists containing inline math containing '<' or '>'

### ISSUE THREAD

**Issue by JZacharyG** [typora/typora-issues#284]
There seems to be a bug when a math expression contained in a list contains '<' or '>'.
Specifically, when un-indenting a child list item (so that it is changed from being a child to a sibling of the list item containing the offending math), the math seems to no longer be rendered by mathjax.  Inspecting the element, it seems to be of class "inline-math-svg math-jax-preprocess", when it should be of class "inline-math-svg math-jax-postprocess", and also seems to be missing the sibling `<span>` tags which are usually present with inline math.

I have been able to reproduce it with the following source by un-indenting the second line:
``` markdown
- $<$
  - 
```

A screen shot, if it helps.
[TyporaBug.mp4.zip](https://github.com/typora/typora-issues/files/450973/TyporaBug.mp4.zip)

(using Typora version 0.9.9.7.1)

**Comment by abnerlee** [comment]
fixed in new version

**Comment by JZacharyG** [comment]
Thanks for resolving this so quickly!
