### ISSUE TITLE
Asciidoc support?

### ISSUE THREAD

**Issue by jmfayard** [typora/typora-issues#2840]
Hello, Typora seems great and I'm going to give it a try right after I'm done writing this issue. 

--

Would you consider adding support for asciidoc?
https://asciidoctor.org/docs/user-manual/#what-is-asciidoctor

I am well aware that Markdown is currently the de facto standard. Nevertheless it shows its limits really soon, even if most people are not immediatly aware of it. 

I agree with Alan Key that:

> “Simple things should be simple, complex things should be possible.”

Markdown did successfully the first half, but is a total failure for the second. That's why nobody is using a "standard Markdown" (there is not such things) but always start with Markdown and add to it its mutually incompatible extensions. For example we are here on GitHub so we have "GitHub flavored markdown". In a static website generator, you have "markdown plus front-matter". On "pets.com", we would have "Pets flavored markdown". Etc...

Asciidoc on the other hand is as easy as Markdown for the simple things, but scales much better when you need more features. It was originally designed to be a user-friendly alternative to the DocBook XML schema, so you won't probably never feel the need to add your "XXX flavored asciidoc".

More information here:
https://asciidoctor.org/docs/user-manual/#compared-to-markdown

**Comment by abnerlee** [comment]
There are still lots work to do as a markdown editor, so we don't have plans to support other markup format.

**Comment by mengzc** [comment]
It is hoped that support for AsciiDoc, such as exporting files in AsciiDoc format, will be planned.
