### ISSUE TITLE
Cannot delete a note on a mounted drive

### ISSUE THREAD

**Issue by ahanniga** [typora/typora-issues#2841]
The Move to Trash option does not work if the volume that contains the files does not have one. 

<div align=center><img src=https://user-images.githubusercontent.com/28892939/65315272-b2517580-db8f-11e9-951f-9f1e56e61a92.png width=400/></div>

Can a Delete option be added in this case?

**Comment by abnerlee** [comment]
"Delete Permanently" option on the dialog is added when move to trash fails.

**Comment by ahanniga** [comment]
Brilliant @abnerlee, thank you.
