### ISSUE TITLE
Unable to continue math formula if we press the home key or the end key.

### ISSUE THREAD

**Issue by CPPF0rev3r** [typora/typora-issues#2842]
## Steps to reproduce the issue
- Create a new document
- Insert a math formula with `$$`
- When inserting math formula press the `end` key and see what happens.

**Comment by abnerlee** [comment]
I cannot notice anything wrong, what's your Typora / OS version and what happened after you press `end` key?

**Comment by CPPF0rev3r** [comment]
When i press the `end` key I can't continue to write math formula. My os is Windows 10 64bit and the typora version is 0.9.73 beta.

**Comment by abnerlee** [comment]
please try upgrade typora
