### ISSUE TITLE
Cannot resize window from top border in Unibody mode

### ISSUE THREAD

**Issue by iBug** [typora/typora-issues#2844]
I'm running the latest Typora (0.9.73 beta) on Windows 10 v1903 and I enjoy the Unibody view. However, as I'm a frequent side-by-side user, I often close Typora when it's snatched to left / right. This makes the subsequent opening of Typora remember that position and sizing, which makes it that I cannot easily reach the bottom border of the Unibody window when I want to resize it. I have to drag the title bar all the way up while avoiding maximizing the window (Aero Snap), before I could shrink the window from the bottom border, which is now at exactly the top edge of the Task Bar. It could be inferred that if I accidentally extend the window vertically to somewhere larger than my desktop height (1040px for a 1080p screen at 100%), I could lock myself out at such a height and be unable to get the window back (unless I switch to Classic window).

I think it's unintuitive that the window cannot be resized from its top border / top edge. Can this feature be added?

**Comment by xDeuiii** [comment]
I can resize the window just fine doing what you said with Unibody.
Snap Typora to a side with another window next to it (Chrome) --> Close Typora --> Reopen Typora --> Resize by dragging from bottom edge.

Try restarting Explorer if it happens. These things are somewhat common. Sometimes when I watch Youtube full screen on Chrome, the taskbar appears on top, I have to restart Explorer for that.

**Comment by iBug** [comment]
@xDeuiii Yes, while that's a solution, having to drag up from the bottom border is still inconvenient. That's why this PR is entitled as a request to allow resizing from top border.

**Comment by xDeuiii** [comment]
You can resize from the top edge but only from top-right and top-left where the sidebar is and the close buttons. It seems you cannot resize from the top edge directly above the editor. Weird, don't know why they would make it like that

**Comment by abnerlee** [comment]
https://github.com/electron/electron/issues/3022

**Comment by abnerlee** [comment]
should be fixed
