### ISSUE TITLE
Gothic Theme looks bad in cyrillic on windows

### ISSUE THREAD

**Issue by k-bx** [typora/typora-issues#2845]
Hi. I'm using the "save as html" for my blog with a Gothic theme, and turns out it looks pretty bad on default Windows 10 (with Cyrillics at least). I was first reported about this by a user, and now I confirmed it by installing a fresh Win 10 in VirtualBox.

For some reason, the Yu Gothic font looks awful. Here's a screenshot from a reader: https://imgur.com/czyTbgA

Page itself (I'll try to fix it soon by removing Yu Gothic): https://k-bx.github.io/articles/haskell-fall2019-sponsors-open-letter.html

Source of the page: https://github.com/k-bx/k-bx.github.io/blob/master/articles/haskell-fall2019-sponsors-open-letter.md

Not sure on the best way to go here, but just removing Yu Gothic would make things better already. Thank you!

**Comment by abnerlee** [comment]
should be fixed
