### ISSUE TITLE
Ignore html comments in graphical wysiwyg mode.

### ISSUE THREAD

**Issue by gamgamstylep** [typora/typora-issues#2846]
Ignore html comments in graphical wysiwyg mode:

e.g. ![vscode_open_folder2](images/vscode/vscode_open_folder2.png) &lt;!-- .element height=&quot;300px&quot; style=&quot;border: 0; background: None; vertical-align:middle; box-shadow: None;&quot; --&gt;

**Comment by xDeuiii** [comment]
The picture is broken, please edit and re-upload it

**Comment by gamgamstylep** [comment]
[//]: # (![vscode-icon](images/020_vscode_php/vscode_icon.png)    )

**Comment by abnerlee** [comment]
you could hide by let `.md-comment` be `display:none;` following http://support.typora.io/Add-Custom-CSS/ if you have CSS knowledge. Otherwise it is not hideable.
