### ISSUE TITLE
Video not working in folder with "#" as folder name

### ISSUE THREAD

**Issue by xDeuiii** [typora/typora-issues#2848]
I was trying to drag and drop a video (named "gettingInput") from a folder named "C#". The video was not working, only saw the small crossed video icon and file path indicating that its broken. I tried with another video (named "Editor") in a different folder and it works fine.

When I copied "Editor" to the C# folder and tried inserting in Typora, same thing again, doesn't work.

I thought maybe the folder name was causing this issue, so I changed it to "C Sharp". Tried drag and drop again, and now the video works and plays normally.
So I tested with a new folder with different folder name characters, namely the characters on the number row (from 1 to =). Only "#" breaks the video in Typora, no matter what other name there is alongside it, not sure why

**Comment by abnerlee** [comment]
should be fixed

**Comment by abnerlee** [comment]
relates #2850
