### ISSUE TITLE
typora wrongly escapes # to %23 in hyperlink which contains non-ascii chars

### ISSUE THREAD

**Issue by guyingzhao** [typora/typora-issues#2850]
normal case:
`[foo](https://www.foo.com#bar)`->`https://www.foo.com#bar`

error case:
`[foo](https://www.foo.com#中国`]->`https://www.foo.com%23%E4%B8%AD%E5%9B%BD`

In error case, `#` was unexpected escaped to `%23` and would leading to a mistaken url.

**Comment by abnerlee** [comment]
I cannot reproduce this, what's your Typora version?

**Comment by guyingzhao** [comment]
![image](https://user-images.githubusercontent.com/22538408/65736224-e63b1680-e10c-11e9-8220-1739a6b3b375.png)

**Comment by abnerlee** [comment]
should be fixed
