### ISSUE TITLE
typora cannot locate the correct inline title position across docs

### ISSUE THREAD

**Issue by guyingzhao** [typora/typora-issues#2851]
If we have a directory like below:
```shell
$ tree docs
a.md
b.md
```

Then assume that their content is as below:
`a.md`
```markdown
# 1
x
x
x
x
x
x
# 2
x
x
x
x
x
x
# 3
x
x
x
x
x
```

`b.md`
```markdown
Reference for [a3](a.md#3)
```

When we press ctrl+click for `a3` hyperlink in b.md，typroa simply opens a.md and stay at the beginning, and we won't be navigated to `# 3` in a.md.

**Comment by abnerlee** [comment]
#1231
