### ISSUE TITLE
How can I delete the dead space between sidebar and text ?

### ISSUE THREAD

**Issue by F3000** [typora/typora-issues#2852]
Here is an example :

I
![C1617870-6BB7-453A-A077-7A7AD0867D0A](https://user-images.githubusercontent.com/8161283/65491934-513be180-deb0-11e9-9056-c5f9418187f1.jpeg)

**Comment by xDeuiii** [comment]
You need to change the `max-width` CSS for the theme you're using. Example, I'm using the Night theme (which is included with Typora). Go to File --> Preference --> Appearance --> Open Themes Folder.
![themes folder](https://user-images.githubusercontent.com/55028626/65495676-337a7680-dec8-11e9-9b3d-4b237d59ab7f.png)


Once the themes folder is opened, find the CSS file for your theme. In my case, it is Night.
Right click --> Open with --> Notepad (or any other text editor you want)
![css file](https://user-images.githubusercontent.com/55028626/65495694-3a08ee00-dec8-11e9-885a-86b7840fe458.png)



Scroll to find the `#write` section. Change the `max width` to what you want. In your case, change it to 1800px and save. This will remove the space on the left AND right, or more specifically, it increases the width of the editor.
![max width](https://user-images.githubusercontent.com/55028626/65495713-42f9bf80-dec8-11e9-9c0b-691ff51e985e.png)
![final](https://user-images.githubusercontent.com/55028626/65495739-48570a00-dec8-11e9-918b-3b9b7e9948f9.png)
