### ISSUE TITLE
download Typora-0.9.9.26.5 404 Not Found

### ISSUE THREAD

**Issue by llussy** [typora/typora-issues#2853]
When I download the Typora-0.9.9.26.5.dmg via https://typora.io/dev_release.html, display 404. My mac version is 10.12.6.  
    Where is the old version downloaded? thank you very much.
![image](https://user-images.githubusercontent.com/18432966/65493809-2d938e00-dee6-11e9-81fe-2824c77a7951.png)

**Comment by abnerlee** [comment]
`0.9.9.26.5` will no longer be provided. 

I updated the HTML, 0.9.9.26.6 can be downloaded.
