### ISSUE TITLE
Menu action should return keyboard focus back to document

### ISSUE THREAD

**Issue by tgeijten** [typora/typora-issues#2854]
After performing a menu action, the keyboard focus stays on the menu bar instead of returning to the document. After that moment, a mouse action is required to be able to continue editing.

This is true both when the menu bar is accessed by the mouse or the keyboard (via the `alt` key).

The desired behavior would be that after any menu command (or after pressing the `Esc` key when the menu is in focus) the keyboard focus returns to the document, so the user can continue editing immediately.

**Comment by abnerlee** [comment]
can be fix by https://github.com/electron/electron/pull/20019

**Comment by abnerlee** [comment]
should be fixed
