### ISSUE TITLE
Margins of document exported to PDF too wide

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2855]
I have adjusted the width that text covers on the Typora canvas. When I export a document to PDF, the width of the text field is quite narrow, i.e. the margins on the left and the right of the text are too wide.
Is there a way to adjust that?

**Comment by abnerlee** [comment]
#998

**Comment by DutchPete** [comment]
@abnerlee : I tried this, and although it works, there seems to be a minimum default setting somewhere else which stops the css setting to go below. That minimum default setting is still too wide for me. Is there a way to adjust that? Surely the user should have that choice?

**Comment by abnerlee** [comment]
It should be options after #998 is supported
