### ISSUE TITLE
can't rename new file

### ISSUE THREAD

**Issue by brainchild0** [typora/typora-issues#2857]
Currently, after choosing New File in the drop down menu for a directory in the Files tree, the behavior is consistently not what is wanted.  First, the application assigns a default name, usually `Untitled.md`,  and then places the interface in a file renaming mode with the file basename (e.g. `Untitled`) selected.  The behavior so far is ideal.  

Next, however, regardless of what, if anything, is typed, following a timeout of several seconds, a confirmation box appears with text: 

> Rename to "" ?

Instead, of course, the target file name should be the text that is provided, and the operation should occur after the user strikers the enter key. and selections a different focus  No timeout is necessary or desired, and the empty string should not be a target file name, since it was never provided as input, and cannot be a file name in the file system.

__Version:__ 0.9.77 (beta)
__Operating System:__ Linux Mint 19.2 (Desktop Cinnamon 4.2.4)

**Comment by abnerlee** [comment]
Cannot reproduce this. Does this also exists in 0.9.79?

Please reopen if it still exists

**Comment by brainchild0** [comment]
The specific behavior does not reproduce in the newer version. The *New File* feature now does not invoke a state for renaming the file, but rather it immediately creates a file in the file system called `Untitled.md`. While the original bug is not apparent, I would characterize the new behavior as a regression.  Normally a user will want to choose a name for a file other than the default, and will not want a file, even an empty one, with the default name to be persisted.
