### ISSUE TITLE
Jump to previous position while scrolling

### ISSUE THREAD

**Issue by AskeyNil** [typora/typora-issues#2858]
1. Mouse: Logitech MX Master 3
2. OS X: 10.14.6
3. Typora: 0.9.9.28.5 (3442)

It's good to open the window at first. After a period of use, The pulley is  no longer available in the window. The pulley is normal in other software Windows, excluding the possibility of hardware exceptions

**Comment by abnerlee** [comment]
Hi, I'm not sure what do you mean. Could you provide a screenshot or screencast for better explanation?

**Comment by AskeyNil** [comment]
oh, sorry. My English is poor.
When I'm writing a document, I can't scroll the context.
But on other window, I can scroll.

**Comment by abnerlee** [comment]
which theme do you use?

Scroll by scrollbar or mouse scrollwheel, can you scroll via trackpad ?

**Comment by AskeyNil** [comment]
theme: github
Scroll by mouse scrollwheel.
I can't scroll via trackpad.
Now I often scroll to a place, and after a while it will automatically jump back to the previous place.
![](https://i.loli.net/2019/09/29/gNMmcfIdOX4sbUE.gif)

**Comment by AskeyNil** [comment]
The trackpad is the same

**Comment by abnerlee** [comment]
The version is too old now, please reopen or comment if it still happens in latest version.
