### ISSUE TITLE
"Find..." does implicit "Find Next"

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2862]
While the previous problem (where Find Next had to be done twice in order to search) was fixed at least since 0.9.75, the "Find..." function now implicitly does a Find Next operation, moving the cursor from where you were, possibly skipping over what you meant to find.

In other words, suppose you Ctrl-F and type something you want to find.  This works nicely.  But then suppose you want to find a *second* thing, that is different from the first.  When you hit Ctrl-F again, meaning to type that second thing, the cursor immedialy jumps to the next position of the *first* thing you searched for, losing your place.

So, the Find operation should not immediately jump to the next location, even though Find Next *should*.

**Comment by abnerlee** [comment]
"Find..." will select searched result.
And "Find..." will start from current text selection. So this behavior is expected.

**Comment by pjeby** [comment]
It's not what the program did before, and it also makes the "find next" function redundant.

Can there be a "new find" operation, then, to open the find box and clear whatever value was there before, *not* moving the cursor?  TBH I would rather have back the old bug where "find next" had to be done twice, because that was much less inconvenient -- you could work around that by just hitting the key again, but AFAICT there is no workaround for this new issue.

**Comment by abnerlee** [comment]
#2924
