### ISSUE TITLE
Add option to display text length in minutes for speech

### ISSUE THREAD

**Issue by nsrosenqvist** [typora/typora-issues#2864]
Hi! Love the app, great job! I'm using Typora to write many different types of texts. The words counter in the bottom right corner is a really helpful tool and at the moment it can display minutes of read time. I use the app to prepare teachings and would love if it could also display minutes reading it out loud, for speeches or teachings. A quick google search yields that the average person speaks 125-150 words per minute, making a 2500 word text take 20 minutes spoken out loud.

I imagine the implementation changing the label in the dropdown for reading time to also include an eye icon, and this new option showing the time with a mouth icon or another audio related icon.

**Comment by abnerlee** [comment]
I wonder if it is an actual user case. For tech speech, won't you prepare a slides? The "reading time" are for others (reader), while, if the speech time is for you, you may need to try it out to see how much time it takes.

> A quick google search yields that the average person speaks 125-150 words per minute, making a 2500 word text take 20 minutes spoken out loud.

I think a more common feature for supporting this is #2098.

**Comment by nsrosenqvist** [comment]
Slides are most commonly used for tech and business, wedding speeches and sermons are a whole other category where this do makes a lot of sense, and slides don't. I understand that the majority of Typora users are technically inclined and are most likely in the IT industry, but your reasoning with "you may need to try it out to see how much time it takes" would also apply to reading time, since people read at different speeds, and that didn't disqualify the latter for inclusion. I'm fine with it not being implemented but your reasoning doesn't make sense
