### ISSUE TITLE
The ordinal 345 could not be located in the dynamic link library

### ISSUE THREAD

**Issue by tyde7** [typora/typora-issues#2869]
# bug brief
Just cannot start typora_x64 on windows 10. shows 
> The ordinal 345 could not be located in the dynamic link library

# reproduction step
Just download the package from typora.io, download windows x64 installer, install it then launch typora. Then failed.

# information
System: Windows 10 18362.356 (Simplifiled Chinese)

Install packge sha256: 40E0FEADD61AB12BAF4967456F0C3C44E71EF3122BFCA28B334A47966AAFE175

# a temporary solution
Download from https://typora.io/windows/dev_release.html is ok. I use typora-update-x64-0905.exe. SHA256 of this installer is FFDBAA2D82D72B3C68379E63ED49BE132FB7DC497E4C15D5C0ADC6F6E5639F47.

**Comment by abnerlee** [comment]
Try a complete uninstall and reinstall like https://github.com/Microsoft/vscode/issues/25577
