### ISSUE TITLE
Typora not launching in Kali as root

### ISSUE THREAD

**Issue by six2dez** [typora/typora-issues#2871]
I installed Typora as recommended [method](https://support.typora.io/Typora-on-Linux/) in a fresh install Kali Linux 2019.3 as root user. When I tried to launch nothing happends, nor error through desktop launcher or terminal running `typora`, no output. Any way to show logs or something? If Typora is installed as non-root user it launch perfectly.

**Comment by abnerlee** [comment]
Sorry but I cannot help without error log. The log "may" be under `/usr/root/.config/Typora/typora.log`.

If you install as root user, you may not have enough permission if you do not execute it as a root user.
