### ISSUE TITLE
Cannot select text of multiple task list items via keyboard

### ISSUE THREAD

**Issue by JaschaWetzel** [typora/typora-issues#2873]
In version 0.9.77
```
- [ ] asdf
- [ ] qwer
```
Selecting in WYSIWYG view with Shift+Arrows prevents caret from leaving either line, while mouse selection works.

**Comment by abnerlee** [comment]
#2357

**Comment by jgclark** [comment]
Really? Shift+arrow works for me doing multi-line selection.
(Running 0.9.9.x on macOS 10.14.6)

However, when I left or up arrow from the top line of the block, it has strange behaviour. The cursor disappears and up/down scroll the window. I have to click in again to get normal keyboard focus. The same _doesn't_ happen when leaving the block from the bottom.

**Comment by abnerlee** [comment]
Should be fixed

**Comment by JaschaWetzel** [comment]
There is still one case when this happens as described below. This is on Windows, Typora v0.9.83

Start with the following snippet and cursor position indicated below with the pipe symbol '|'.
```
- [ ] check1
- [ ] check2|
```
Using Shift+Left Arrow select "eck2", then press Shift+Up Arrow three times. The third and subsequent times the cursor will not move anymore.

Another situation is selection of entire lines. The start state is as follows.
```
- [ ] check1
- [ ] check2
|
```
Then press Shift+Up Arrow twice. The second time the cursor will not move, but the third time it will. This repeats through the checkbox lines, as if the checkbox itself counts as a separate line. There is no visual feedback that the checkbox was selected, though.

**Comment by abnerlee** [comment]
seems working in my test. Sometimes it seems selection is extended, but actually an invisible `\n` is selected, and keys still working on a second shift+arrow key
