### ISSUE TITLE
Margins export as PDF too big

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2874]
When exporting a document to PDF (I'm on Linux, Typora 0.9.77) the margins on the left and right are too big.
I tried [this](https://developer.mozilla.org/en-US/docs/Web/CSS/@page), and looked at #998, but neither works. There seems to be a default minimum width which cannot be overridden. Is that done by design, or is there a way to overcome this?

**Comment by abnerlee** [comment]
its duplicate with #998

**Comment by DutchPete** [comment]
@abnerlee : like I said above, whatever is suggested in #998 does NOT work.

**Comment by abnerlee** [comment]
it is duplicate with #998, and #998 is still open
