### ISSUE TITLE
Incorrect presentation of the table with images at the page break

### ISSUE THREAD

**Issue by miku76** [typora/typora-issues#2875]
Hi,
I love this editor but I also have some trouble with page brakes on tables with images.
Typora detects the right position for a break of the table but the rendering of the first image from the next page is incorrect.

![2019-09-30_incorrect_page_break](https://user-images.githubusercontent.com/16088486/65904670-33deaa00-e3bf-11e9-887d-194dfeeaf0df.png)

**Comment by abnerlee** [comment]
Could you provide a sample md file? And what is the Typora version?
