### ISSUE TITLE
Multiline math rendering 

### ISSUE THREAD

**Issue by AustenLamacraft** [typora/typora-issues#2876]
This is probably a tricky request and may be a MathJax issue...

I'd love to use Typora live for lecturing or giving talks. As one types in a math block, errors are thrown for unclosed braces, etc. While this is reasonable behaviour, it's a shame to have the whole block disappear when writing a multiline equation if the previous lines are fine. This would make it difficult for anyone following and writing notes, for example.

**Comment by peetteerr** [comment]
You mean inline math, I think. When you gave a unclosed curly bracket, It will stop rendering until you give its pairing bracket. If you use Typora to give talk, this is indeed a trouble.

**Comment by abnerlee** [comment]
should be improved
