### ISSUE TITLE
Unexpected/inconsistent cursor movement strategy

### ISSUE THREAD

**Issue by JaschaWetzel** [typora/typora-issues#2877]
Version 0.9.77
* When positioning the cursor on the _first_ column and moving _upwards_ through paragraphs, headings and/or list items, the cursor jumps between to the first and last columns. It _does_ retain its first column position when moving _downwards_.
* When positioning the cursor on the _last_ column and moving between paragraphs and headings, it does retain its last column position in some cases, jumps to the first or some other position in the next line in other cases or even skips a line in some cases.
* When moving _downwards_ across a short line with fewer characters than the cursor position, the cursor column is correctly restored when moving down further onto a long enough line. It does not do that when moving _upwards_. In this case, the cursor column remains on that of the short line.

**Comment by abnerlee** [comment]
seems duplicate with #1164
