### ISSUE TITLE
Per-document style

### ISSUE THREAD

**Issue by zeroskyx** [typora/typora-issues#2879]
Greetings,

thank you so much for this great application -- Typora is a really awesome program that will surely have a great impact once the beta phase is over.

I do have one suggestion though that would **make Typora even more useful**: when using Typora to create different kinds of documents, you currently have to **manually switch the theme** to reflect different settings per document such as **fonts and general styles**.

It would be awesome if we could either

1. **manually select a document theme** (css) in the yaml-front-matter block such as `style: DocumentStyle.css`, or
1. have Typora **look for a stylesheet** called `<Document>.css` in the same directory (so for `MyDocument.md`, `MyDocument.css` would be included when found as well).

Thanks in advance for considering my request; keep up the great work
-Simon

**Comment by abnerlee** [comment]
same purpose as #2747?

**Comment by macdew** [comment]
The feature to load a <document>.css from the same folder as the .md would be fantastic.  It would save us having to send out manual instructions to everyone who wants to read the file the way it was intended...
