### ISSUE TITLE
format citations to look different than text?

### ISSUE THREAD

**Issue by samuelmehr** [typora/typora-issues#2880]
Hi, I'm using Typora for academic writing so have been using it with Zotero and BibTeX citations. One difficulty is that because Typora doesn't "know" that my citations are any different than the actual text I'm writing, it makes reading my own work kind of awkward before processing the text via `citr` (or some other typesetting system like DocDown).

Here's an example (citations are in square brackets):
<img width="686" alt="Screen Shot 2019-10-03 at 4 23 31 PM" src="https://user-images.githubusercontent.com/41483946/66097275-311bc900-e5fa-11e9-9517-3b27245f7982.png">

Is there some simple CSS to modify so that BibTeX citations like these could automatically be faded out so they're less intrusive?

Could look something like this:
<img width="694" alt="Screen Shot 2019-10-03 at 4 29 14 PM" src="https://user-images.githubusercontent.com/41483946/66097479-02eab900-e5fb-11e9-8bc2-a2d7e65ca5ac.png">

This seems like it should be simpler to set up than my ideal setup, which would have the citations automatically format themselves into whatever citation style the document is set up for — basically doing automatic citation importing like what you get out of RStudio/`citr` when knitting an rmd file in TeX. But that seems a lot more complicated than a few lines of CSS... 😆

**Comment by abnerlee** [comment]
duplicate with #912 #294

**Comment by Lazenca-Li-Qiuqi** [comment]
I wanted something similar, so I ended up building a Typora plugin for local BibTeX/CSL citation workflows.

Besides citation key completion, it can also render Pandoc-style citations with a local `.csl`, so citations no longer have to remain raw text all the time.

Repo: https://github.com/Lazenca-Li-Qiuqi/typora-plugin-bibtex-citation

It’s still focused on local `.bib` + `.csl` workflows, but it may be useful if you want citations to feel more integrated while writing in Typora.
