### ISSUE TITLE
Code Block - Indentation Issues

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2882]
I generally use Python to write code snippets which relies on indentation. When I copy and paste into a code editor such as VSCode, it complains about the indentation (`IndentationError`) even when I using the tab option under editor settings. Do you know of a way to fix this or how this can be resolved?

**Comment by abnerlee** [comment]
What is the indentation after paste, and what it should be?

**Comment by justnealpatel** [comment]
I've actually just come to a new issue when opening Typora: I can't tab in a code block but I can add spaces. This is something that I've just come across and now all my previous indented code is at the wrong level. Have verified this in the Github theme as well and have also tried changing languages.

![image](https://user-images.githubusercontent.com/12269792/66260121-eb890880-e77f-11e9-9707-a7da1a85b004.png)

The lines at the same level as the function declaration (`def`) were not at the same level upon writing and were indented one level further. I suspect that this may have something to do with the issue at hand or it might just be an effect of the fact that I can't tab.

I don't think the indentation is the issue. It's the way the indentation is constructed. The same indentation can be reached with spaces, tabs or a combination. Proof:

Incorrect indentation:
![image](https://user-images.githubusercontent.com/12269792/66260164-8550b580-e780-11e9-9425-5c8a550ecd82.png)

Something to note about the above screenshot:
To fix it, I basically have to move the line with the error up right next to the previous line then press enter and have it indent properly. The lines that gave the same error were all of those in the function. Once I fix the current error, the error basically just moved to the next line. This is what makes me think that the indentation wasn't being properly applied in the Typora code block as it was just a simple copy and paste.

Correct indentation:
![image](https://user-images.githubusercontent.com/12269792/66260198-ff813a00-e780-11e9-826f-45940955e961.png)

As you can see, there is no visual change.

**Comment by abnerlee** [comment]
How you make code fences? using "```" or tab / 4-space indentation ?

Would you attach the markdown source between `Challenge #7` and `#8`?

**Comment by justnealpatel** [comment]
I use the shortcut titled for "Code Fence". Looking through source mode, it uses "```". I have attached the source file: [Notes.md.zip](https://github.com/typora/typora-issues/files/3694796/Notes.md.zip)

**Comment by abnerlee** [comment]
I can insert tab in code blocks in `Challenge #7`, and the file looks like:
<img width="1042" alt="Screen Shot 2019-10-08 at 00 52 39" src="https://user-images.githubusercontent.com/1621242/66331820-f604f700-e965-11e9-8d5b-fd5732e7204a.png">
When I open this. Could you check if your Typora version is latest, or is there any other details missing?

**Comment by justnealpatel** [comment]
Hmm, that's odd. I do have the latest version and this issue only started showing since a few days. Before, it was working fine. 

So I tried doing a fresh reinstall and the issue still persists. So the tab works but it doesn't show in the UI. When I copy an indented block to a code editor, it shows as indented but in the Typora code block, it doesn't reflect in the UI. I'm not sure what caused my editor to stop working, but I will update this if I find something that you can use.

**Comment by justnealpatel** [comment]
I think has to do with #2380.

**Comment by justnealpatel** [comment]
So something strange just happened. I noticed that I've been opening Typora through an Alfred workflow I created, so I tried to just open it manually and open up the right folder manually. This fixed it somehow. Now when I open it the workflow way, it's fixed. I'm not even sure as to what the bug might be.
