### ISSUE TITLE
Losing Untitled files that are supposed to be autosaved on Mac

### ISSUE THREAD

**Issue by Ken0sis** [typora/typora-issues#2883]
**Current setup:**
- Autosave is turned on for my Mac by unchecking "Ask to save changes when closing documents" and "Close windows when quitting an app".
- Mac version 10.14.6
- Typora version 0.9.9.28.5

**Current behavior:**
1. Step 1: Create an untitled file with content.  This file is autosaved, and can be seen in "Library/Autosave Information".  It will reload 90% of the time when I quit and relaunches Typora.  
2. Step 2: A Typora crash is triggered, caused by Mac updating or some other event.
3. Step 3: The untitled file cannot be found.  I cannot relaunch it by going to "Reopen Closed File", and I cannot find it in "Library/Autosave Information".  In fact, all autosaved documents from this folder is deleted.  Sometimes the untiled documents are lost when relaunching, even without a crash

**Expected behavior:**
According to documentation, untitled documents are autosaved and they are supposed to be reloaded when Typora relaunches (given system preferences I described above).  They should not be lost when Typora relaunches, with or without a crash.  

**Other observations**
It seems that the current autosave mechanism is not reliable.  Other apps such as iA Writer will force save into a default folder location (chosen by the user) whenever a new file is created.  Alternatively, other apps save untitled files to "/Library/Containers".

**If more info is needed to resolve this issue, please be specific and I will be happy to provide additional info**

**Comment by abnerlee** [comment]
smae with #2797

**Comment by Ken0sis** [comment]
@abnerlee This is not the same issue as #2797.  This issue is about unsaved Untitled documents being deleted.  The other issue is about documents not opening in the same ordering when relaunched.  The two issue might be related, but they might not be.  

If anything, I would rather fix the issue of Untitled documents being deleted than windows not relaunching correctly.

**Comment by abnerlee** [comment]
should be fixed in latest version
