### ISSUE TITLE
Render / Insert Ordered List Checkboxes

### ISSUE THREAD

**Issue by DarwinJS** [typora/typora-issues#2887]
I just wrote part 1 of an article on why checklists belong in git (https://thenewstack.io/why-human-processed-source-code-belongs-in-git/)

Part 2 will go in depth on how to configure Typora and CopyQ together to enable advanced "DONE" marking. (Both are fully multiplatform and free)

One thing the article has to work around is the inconsistent rendering of ordered lists with checkboxes.

This markdown: `1. [ ] A checklist item` renders on GitLab.com as a numbered bullet followed by a checkbox.  However, typora it renders as just a checkbox - eating up the numbered bullet.

I can force Typora to do it with `1. - [ ] A checklist item` but this seems to establish a sub-list because pressing enter after an existing line formatted this way results in an unnumbered checklist box item under the same numbered item.

I am wondering if these can be reconciled to work the same (so they render the same).  If that is not possible, I wonder if Typora could recognize the second syntax I put above and when I press enter on an existing list item, insert both the number and checkbox on new lines?

I did my best to search and find if there is any statement of how this should work in markdown and commonmark - and I could not find anything.

The value of numbered checkboxes in **complex** DevOps checklists is inestimable - it is one key feature that makes markdown suitable for managing master lists and recording executed lists.

**Comment by DarwinJS** [comment]
This is made more difficult because bullets do not reveal their markdown code when highlighted.  So I have to switch to source view to copy and paste the sequence `1. - [ ] A new checklist item`

**Comment by abnerlee** [comment]
merge into #2448 since it is a new markdown syntax but not in widely supported
