### ISSUE TITLE
Suggestion: Custom blocks

### ISSUE THREAD

**Issue by aluminum1** [typora/typora-issues#2889]
It would be fantastic if Typora could have custom blocks, which the user could then style via CSS. So in mathematics, for instance,

```
--- {Theorem}
For any right-angled triangle, $a^2 + b^2 = c^2$
---
```

would produce a (user-styled) Theorem block, and so on. The syntax could be similar to the code block ``` syntax, or it could be something else. 

Note that it is important that the Markdown is recognized in the above custom blocks - observe the LaTeX inside the example. (Typora doesn't recognize Markdown inside code blocks, which is ok.)

**Comment by abnerlee** [comment]
Custom blocks can be merged into #162

For your requirements, it better to be done via #2442 #1939
