### ISSUE TITLE
Suggestion: Inline drawing support

### ISSUE THREAD

**Issue by aluminum1** [typora/typora-issues#2890]
I think Typora is fantastic! But I would like to echo a feature that has been proposed before ([here](https://github.com/typora/typora-issues/issues/1070#issue-276980863) and [here](https://github.com/typora/typora-issues/issues/209)) - inline drawing support. That is, the ability to construct an SVG image block "on the fly" inside Typora by drawing with a stylus and then inserting the image as an SVG image.

Having read your responses to this suggestion, I just want to clarify two points.

* This is not so much about 'note taking' as 'content production' for the document.
* I think this falls fairly within the remit of a "Markdown editor'. It is simply a convenient way to create an image from inside the editor itself, without leaving the editor and going to a 3rd party drawing program. The end result is included as an `<svg>` block inside the Markdown .md file in the standard way. 

For instance, in the Mac universe, the new PencilKit framework will allow you to have  "insert SVG" functionality (with pen support) with just a few lines of code.

Anyway, many thanks for your excellent program.

**Comment by abnerlee** [comment]
#2493
