### ISSUE TITLE
Typora is not re-opening all of previous windows in the same arrangement when relaunching

### ISSUE THREAD

**Issue by Ken0sis** [typora/typora-issues#2892]
This is in reference to issue #2797.  

**System Config**
- Typora version 0.9.9.28.5 (3442) and OS is Mac 10.14.5 (18F132)
- I have autosave turned on I turn off "close windows when quitting app"

**Current Behavior**

- I usually group my tabs into specific windows so that I can organize my workspace.  When Typora relaunches (either because of crash or quitting), sometimes the windows don't relaunch with the same ordering and arrangement.  Sometimes it will put all the tabs into the same window, OR it might only reopen the Untitled documents and I have to manually open the saved (with titles) documents using "Reopen Closed Files".  
- It seems to happen mostly when I have Untitled (unsaved) documents with the "edited" mark, but it might not be related to having Untitled documents.

**Expected Behavior**

- Both unsaved (untitled) and saved documents should reopen in the same window arrangement and ordering when Typora is relaunched, given my configuration above.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by aisurlfhklajsdfhaaslkdjfh** [comment]
Not sure if this was ever fixed, but this issue still occurs and drives me crazy.

1. Typora > Settings > Files > On Launch = "Restore last closed files and folders"
2. Open some files as tabs within a single window. Take note of the arrangement of tabs.
3. Close Typora (<kbd>⌘</kbd> + <kbd>Q</kbd>)
4. Open Typora
5. The arrangement of tabs (noted in #⁠2) is now different.

Typora 1.7.3 (7006)
macOS 13.5.1 (22G90)
