### ISSUE TITLE
Ctrl+N crashes my computer, but File > "New File" doesn't

### ISSUE THREAD

**Issue by FOSSforlife** [typora/typora-issues#2898]
OS: Manjaro Linux
Installation source: AUR (typora)
Version: 0.9.77 (beta)

Steps to reproduce: press Ctrl+N at any time. Computer immediately freezes.

This is a fairly new issue for me (last 2 or 3 days), but I'm not sure if it's directly related to this version or if it happens in earlier versions too.

Let me know if you need any other details. Not sure how to debug, since the computer crashes every time.

**Comment by abnerlee** [comment]
We updated our electron version, which may fix this. So please try 0.9.78

Also, it may relates AUR since it is not official support, please also try the binary package typora.

**Comment by FOSSforlife** [comment]
Happy to say that I'm not experiencing this problem anymore. It was happening as of about a month ago, and I've since updated the kernel, so I don't know if that was what made a difference.
