### ISSUE TITLE
New Feature: Support Codeblock inside details/summary tag

### ISSUE THREAD

**Issue by HYChou0515** [typora/typora-issues#2899]
Code block inside a details/summary tag need extra empty lines to make it work.
<details>
<summary>my code with empty lines</summary>

```shell
echo hello
```

</details>

Or it will not generate a code block

<details>
<summary>my code with empty lines</summary>
```shell
echo hello
```
</details>

However, 

> @abnerlee in https://github.com/typora/typora-issues/issues/399#issuecomment-414101709
> _it is now supported. Not no empty line inside the HTML Block is allowed._

It would be super great if Typora support such feature.

**Comment by abnerlee** [comment]
will be covered by #1939
