### ISSUE TITLE
bug in enter newline while the end of the file is math equation

### ISSUE THREAD

**Issue by lj8385174** [typora/typora-issues#29]
I can enter a newline while the end of the file is math equation 

Version 0.7.6  in windows 10

**Comment by abnerlee** [comment]
A new paragraph will be inserted when clicking the empty area, and last line is not empty. 

Before clicking, or after deleting that new paragraph, the last empty paragraph does not exists.

Or else, it will be difficult to append new paragraph if last line is math equation or other selectable blocks.

**Comment by abnerlee** [comment]
Maybe typora should remove that temporary empty paragraph when user clicking somewhere else. What do you think?

**Comment by lj8385174** [comment]
@abnerlee Yes, this solution is exactly what I want

**Comment by abnerlee** [comment]
fixed in v0.8.3
