### ISSUE TITLE
Supported Files Not Shown in File Tree

### ISSUE THREAD

**Issue by ginkgomzd** [typora/typora-issues#2900]
The documentation states:
> In file tree mode, currently only folder and files that are supported by Typora (Markdown file, text file, etc) is displayed.

https://support.typora.io/File-Management/

We can gather that "etc.", would include HTML files because HTML support is clearly advertised: https://support.typora.io/HTML/

However, HTML files are hidden in the File Tree.

**Comment by abnerlee** [comment]
I mean we will handle #1753 instead of this issue, since the later can cover this one
