### ISSUE TITLE
Export PDF: "TypeError: Cannot read property 'loadURL' of null"

### ISSUE THREAD

**Issue by vagra** [typora/typora-issues#2906]
In previous versions of Typora I could have been properly exported pdf.

But after today Typora updated to version 0.9.78, When I want to export pdf, Typora report the following error: 
> TypeError: Cannot read property 'loadURL' of null

But as soon as I close the Error dialog, select Export pdf again, this time Typora can normally export a pdf.

In other words, I need to click twice "Export pdf", the first time it will report Error, the second time to export properly.

Windows 10
64bit

**Comment by abnerlee** [comment]
Possible to send us the sample *.md file? I cannot reproduce this

**Comment by vagra** [comment]
this a sample file.

[禅门子弟今犹在.zip](https://github.com/typora/typora-issues/files/3732395/default.zip)

some filles has not this problem.

**Comment by abnerlee** [comment]
I still cannot reproduce this, which Theme did you use?

**Comment by vagra** [comment]
theme: Github , and other. most themes have this problem.

**Comment by abnerlee** [comment]
should be fixed in new release
