### ISSUE TITLE
Folder Search stopped working on Linux

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2907]
Today I upgraded to version 0.9.78, but now Search among all the files in the folder has stopped working.

**Comment by jskierbi** [comment]
Confirmed, it stopped working today for me as well

**Comment by DutchPete** [comment]
@jskierbi : confirmed that it works again after downgrading to 0.9.77-1.
My Linux distro is Mint 19.2.

**Comment by abnerlee** [comment]
fixed in 0.9.79
