### ISSUE TITLE
SmartyPants Support

### ISSUE THREAD

**Issue by CalculusWarrior** [typora/typora-issues#291]
Another project by the creator of MarkDown is called SmartyPants, which provides several typographic quality-of-life improvements:
- Straight quotes ( " and ' ) into “curly” quote HTML entities
- Backticks-style quotes (``like this'') into “curly” quote HTML entities
- Dashes (“--” and “---”) into en- and em-dash entities
- Three consecutive dots (“...”) into an ellipsis entity

It can be seen here: http://daringfireball.net/projects/smartypants/

Will this be implemented into Typora in the near future, either when exporting a document or as one types? It would be a fantastic addition.

**Comment by abnerlee** [comment]
also include https://github.com/typora/typora-issues/issues/668

**Comment by abnerlee** [comment]
relates 
https://github.com/typora/typora-issues/issues/516
https://github.com/typora/typora-issues/issues/137
https://github.com/typora/typora-issues/issues/1028

**Comment by charlesroper** [comment]
I'd be interested in taking a step beyond SmartyPants and having something like Typogrify included as an option. There's a node package that includes both: https://www.npmjs.com/package/typogr

**Comment by abnerlee** [comment]
Supported in new release -> https://support.typora.io/SmartyPants/
