### ISSUE TITLE
Deleting file crashes Typora on Mac

### ISSUE THREAD

**Issue by ipalindromi** [typora/typora-issues#2912]
I am new to Typora, and just discovered that the app crashes almost every time I delete a file. If I go to "Move to trash" in an item in the files outline, the app will hang and never recover. At first I thought this could have to do with the file being in iCloud, but after some testing where the file is doesn't seem to matter.

After force quitting and reopening, the file is deleted, so the crash comes sometime after that. I tried looking at the debug mode, but it crashes before I could see anything interesting there.

**Comment by abnerlee** [comment]
Which is your Typora / OS version? And do you have crash log after crash happens?

**Comment by JellyL** [comment]
Same issue happened to me.
I use the newest Typora version downloaded from official website  0.9.9.29.1 (3563) and MacOS Catalina 10.15 (19A602)
Following are issues I found in my console
错误	15:54:35.155340+0800	kernel	Sandbox: fileproviderd(932) deny(1) file-read-data /Applications/Typora.app
错误	15:54:41.879640+0800	kernel	Sandbox: fileproviderd(932) deny(1) file-read-data /Applications/Typora.app

**Comment by ipalindromi** [comment]
@abnerlee 
The version is 0.9.9.29.1 on MacOs Catalina 10.15 (19A602)

As of 0.9.9.29.2, I can no longer replicate the issue. Unfortunately, I was never able to find any logs that seemed relevant. 

If the issue re-occurs, I will dig deeper and re-open.

**Comment by JellyL** [comment]
@ipalindromi 
This issue still happen on 0.9.9.29.2

**Comment by dan-tee** [comment]
I'm having the same issue. Typora reproducibly hangs when I delete the file that is currently shown in the right hand view. It does not hang when deleting a file that is not in the focus.

MacOS Catalina 10.15.4
Typora 0.9.9.32.1 (4191)

**Comment by dan-tee** [comment]
@abnerlee do you need any additional info for this?

**Comment by abnerlee** [comment]
should be fixed. see #3112
