### ISSUE TITLE
Could not export pdf under the Night theme mode in 0.9.78 version on Windows

### ISSUE THREAD

**Issue by Yuhang-Follheart** [typora/typora-issues#2913]
In 0.9.78 version, When you try to export pdf under the night theme, the File Explorer does not appear correctly。

**Comment by TibboddiT** [comment]
Same issue here, 0.9.78 on debian testing. The file explorer doesn't show up after the warning about dark theme support. It works when selecting a light theme.

**Comment by abnerlee** [comment]
fixed on 0.9.79
