### ISSUE TITLE
Exporting to HTML adds blank lines to code blocks

### ISSUE THREAD

**Issue by LiohMoeller** [typora/typora-issues#2916]
I have exported a document with code blocks to styled HTML. When I try to copy and paste Text from the codeblocks, a blank lines are added, between each line of code.

e.g.

su -
for f in $(find /usr/share/icons/Adwaita/ -name folder.png); do \
 ln -sr $f $(dirname $f)/inode-directory.png; \
done

leads to the following after copy and pasting:

su -

for f in $(find /usr/share/icons/Adwaita/ -name folder.png); do \

 ln -sr $f $(dirname $f)/inode-directory.png; \

done

I have created a small makrdown file and a HTML file exported with Typora

[test.zip](https://github.com/typora/typora-issues/files/3723324/test.zip)

When I copy the text to a Texteditor (e.g. gedit), it adds a blank line after each line of code. Copy & Paste within Typora works.

Besides that you can try to copy and paste a code block from one of the HTML sites I have created with Typora: https://linuxkurs.ch/kurs/Konfiguration.html
Just pick any of them which has multiple lines.

Note: I have already reported the issue two times. One time it has just been closed after 'waiting for feedback' and the other time it has been closed with 'should be fixed now' but it isn't.

**Comment by abnerlee** [comment]
#2791
