### ISSUE TITLE
Crash when switch to full screen mode on MacOS

### ISSUE THREAD

**Issue by F-Que** [typora/typora-issues#2920]
This issue appears after update to version 0.9.9.29.1.
Firstly, I found that the **word counter disappeared** from the right top **after a theme change**. Then, I switch out from full screen mode, the word counter comes back. However, it crushed just when i switch back to full screen mode.
It also crashes when I try to re-switch on the "Always Show Word Count" entry.

**Comment by abnerlee** [comment]
should be fixed
