### ISSUE TITLE
Can't open any file in macOS 10.15 newest version

### ISSUE THREAD

**Issue by Evian-Zhang** [typora/typora-issues#2923]
macOS version: 10.15(19A602)

Typora version: 0.9.9.29.1 (3563)

After taking today's macOS upgrade, Typora can't open any files, or create new files. Every time I open Typora, the window opens normally, but I can't type in any words

**Comment by pithuene** [comment]
I'm having the same issue, updated to macOS Catalina today and when I open a file in Typora it doesn't show any content, I can't write anything and the word count claims the file is empty.

**Comment by TonyWu3027** [comment]
Same issue here but different OS version
Typora version 0.9.9.29.1 (3563)
MacOS version 10.14.3 (18D109)

I can read or write any contents  when I open a file, the word count claims the file is empty as well. But I can open the same file using Sublime

**Comment by Evian-Zhang** [comment]
After taking today's Typora upgrade to 0.9.9.29.2, the issue is still **NOT** resolved.

**Comment by TonyWu3027** [comment]
> After taking today's Typora upgrade to 0.9.9.29.2, the issue is still **NOT** resolved.

Same here. I tried to re-install typora for a few times and tried to upgrade my OS to Catalina, it still fails to function properly. 

MacOS: 10.15 (19A603) (But the problem started to appear on 10.14.3 (18D109))
Typora: 0.9.9.29.2 (3650)

**Comment by abnerlee** [comment]
Still cannot reproduce this one. Please try clean Typora cache / config data via tools like AppCleaner

**Comment by TonyWu3027** [comment]
Solved! Cleaning cache and config did help, thank you!

**Comment by Evian-Zhang** [comment]
> Still cannot reproduce this one. Please try clean Typora cache / config data via tools like AppCleaner

Uninstall Typora and `sudo find / -iname "*typora*" | xargs rm -rf` helps!

**Comment by ZhengchaoJiang** [comment]
Same problem!

**Comment by huangzhenyu** [comment]
Same issues!

**Comment by abnerlee** [comment]
@huangzhenyu @ZhengchaoJiang 
This is not working https://github.com/typora/typora-issues/issues/2923#issuecomment-544967996 ?

**Comment by ZhengchaoJiang** [comment]
This will work, but however, once I changed the settings again, the problem will occur again.

I am not sure which setting cause the problem, since I changed a lot, or any change will cause that.

**Comment by Kirito0512** [comment]
after update macos to 10.15.2, typora can work！！！

**Comment by KhelKim** [comment]
I think when we search in the preference, this bug appears, maybe.

**Comment by RedBlackTreei** [comment]
have same issue too. I have cleaned cache&config files with [app cleaner] but still didn't work.
![image](https://user-images.githubusercontent.com/2232986/143195849-85d7ad69-89f7-45c9-ab51-6066b17f5c94.png)
![image](https://user-images.githubusercontent.com/2232986/143195899-ab9ac51a-ee42-42b5-8150-4c8146743d72.png)
