### ISSUE TITLE
Inconsistencies in search command behaviors between WYSIWYG and Source modes

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2924]
Currently, Find and Find Next behave the same as each other, but *differently* depending on whether you are in WYSIWYG or Source editing.

If you are in source editing, *both* the Find and Find Next commands perform a "Find": that is, they open the search dialog, but do not move the cursor, even if there is an existing search string.

If you are in WYSIWYG, however, Find and Find Next *both* operate as a "Find Next": that is, either shortcut key causes an immediate jump to the next location, if there is an existing search string.

So the behavior is inconsistent between modes, but has redundant behavior between Find and Find Next.  This behavior is self-inconsistent as well as inconsistent with other editors, and with how Typora itself behaved in the past.  ISTM the correct behavior should be:

* "Find" should work the way it currently does in Source editing: that is, it should open the dialog but should not move the cursor until you type something (even if some text is already there)
* "Find Next" should work the way it currently does in WYSIWYG mode: that is, it should open the dialog and move to the next location if there is existing search text

These are two different things that one might want to do, and there are two separate commands, so they should not be duplicates of each other.  Right now, Find only works correctly in Source mode, and Find Next only works correctly in WYSIWYG.

Since both behaviors are both possible and desirable, they should be split between the commands instead of between the modes, so that the two commands act as they do in other programs, and do not change semantics based on the editing mode.

**Comment by abnerlee** [comment]
should be fixed
