### ISSUE TITLE
[BUG] About Typora failed to recognize Dark mode configuration in theme CSS

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#2927]
The VLOOK theme CSS is currently configured with color and dark colors for the color-scheme, with Dark mode enabled in both macOS and Windows.
Only the Windows version of Typora will correctly display the dark color when the VLOOK theme is selected. The macOS version does not. Is this a BUG?

[theme sample](https://github.com/MadMaxChow/VLOOK/blob/master/2-released/theme/vlook-hope.css)

**Comment by abnerlee** [comment]
#2460
