### ISSUE TITLE
Anchors not working in Export to HTML (full)

### ISSUE THREAD

**Issue by rkeir** [typora/typora-issues#2929]
Anchor links do not work in browsers when the output from Typora is exported to HTML [`File -> Export -> HTML`]. Exporting the same document to HTML (without styles) works [`File -> Export -> HTML (without Styles)`]

e.g.

```
This is the top. Click the link below.

[Link](#this-is-the-end)

Add lots more lines in here so we can see whether the link works or not
...

# This is the end

This is some text
```

**Comment by rkeir** [comment]
Bug still present in version 0.9.79 (Windows)

**Comment by abnerlee** [comment]
should be fixed already
