### ISSUE TITLE
Keybinding Problem

### ISSUE THREAD

**Issue by Weilet** [typora/typora-issues#2930]
I try to add a hotkey in advance config:
```json
"keyBinding": {
    "Toggle SideBar": "Alt+1",
    "Always on Top": "Ctrl+Shift+P",
    "Open Folder...": "Ctrl+Shift+O"
},
```

`Toggle SideBar` and `Always on Top` worked well while `Open Folder` didn't work.
Is there anything I did wrong?

**Comment by abnerlee** [comment]
Cannot reproduce this. Does "Ctrl+Shift+O" added right to the menu item "Open Folder..."? Does click that menu item work? What's your Typora / OS version?

**Comment by Weilet** [comment]
**Does "Ctrl+Shift+O" added right to the menu item "Open Folder..."?**
No!
<img width="204" alt="Snipaste_2019-11-05_20-25-59" src="https://user-images.githubusercontent.com/32561597/68207727-850b3a80-000a-11ea-8ab5-150df9ae4f0a.png">

 **Does click that menu item work?**
Yes.

**What's your Typora / OS version?**
- Typora version: 0.9.68(beta)
- OS version: Windows 10 1903

**Comment by abnerlee** [comment]
0.9.68 is too old, please try upgrade Typora
