### ISSUE TITLE
Roadmap of What's Next Suggestion

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2931]
I've really been enjoying using Typora for the past year as it's a lovely editor. One suggestion I have is to maybe create a label of what you're working on for the next update. It seems like the Github open issues count keeps growing and I'm not really sure which features are coming next (features that will impact user experience). I think that it would really help to be able to organize these issues and focus on the prioritized ones as well as let us know what's being worked on. Thanks again for this awesome editor and keep up the great work.

**Comment by AlexPasternak** [comment]
Trello would be a great candidate. Here's Dynalist's roadmap for comparison, which also has a large list of bugs/features/suggestions on its forum.

https://trello.com/b/z0HxDPNo/dynalist-roadmap

**Comment by abnerlee** [comment]
Close for being duplicated with #1645, basically we won't introduce functions that will impact user experience, or those changes will be introduced as one option.

**Comment by justnealpatel** [comment]
Could you elaborate on what you mean by:

> basically we won't introduce functions that will impact user experience

? I'm a little confused on what you mean by that.
