### ISSUE TITLE
no image in exported image

### ISSUE THREAD

**Issue by noscete1psum** [typora/typora-issues#2932]
Hello, when I export the md to image, I found that the image in the md is not showed in the exported image. How should I fix it?
Thanks!

<img width="672" alt="md" src="https://user-images.githubusercontent.com/31724062/67173918-d30d2500-f3f2-11e9-99c0-0860f4471980.png">

<img width="640" alt="Test" src="https://user-images.githubusercontent.com/31724062/67173844-993c1e80-f3f2-11e9-9f69-40a83c051ff5.png">

**Comment by abnerlee** [comment]
Should be fixed
