### ISSUE TITLE
When typora will update to mermaid 8.4

### ISSUE THREAD

**Issue by wiesener** [typora/typora-issues#2935]
As shown in the example the current class diagram is not running in typora. 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/12429559/67214126-7d9b3d00-f41f-11e9-94e5-5fca3faf179b.png">

There is a newer version available on 
https://mermaidjs.github.io/#/
which claims to solve the class diagram issues and introduces statemachines. How can I update to this version?

**Comment by wiesener** [comment]
Is there a already a timeline for this issue?

**Comment by kisshc** [comment]
Is there a already a timeline for this issue?

**Comment by abnerlee** [comment]
Supported in new release
