### ISSUE TITLE
Word count error with contractions

### ISSUE THREAD

**Issue by MikiMarshall** [typora/typora-issues#2936]
Any word with an apostrophe (e.g., can't, Miki's, shouldn't, Ma'hala) count as two words in the word count. But in the real world they only count as one. I've had issues with this repeatedly when submitting work to flash fiction sites. 

They should work the same as contractions (three-year-old = 1 word), which work fine in Typora.

Thanks!

**Comment by abnerlee** [comment]
Those should already be fixed. Which version did you use? #1891

**Comment by MikiMarshall** [comment]
Oh, it seems it stopped updating for me, like it used to. I was still on 0.9.63. 

I had to rerun the wget etc. to get it to update properly. That's odd. It was updating on its own fine before. 

I'm on 0.9.78 now. Contractions count properly now. Thanks!

On October 22, 2019 5:57:56 AM PDT, AbnerLee <notifications@github.com> wrote:
>Those should already be fixed. Which version did you use? #1891
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/typora/typora-issues/issues/2936#issuecomment-544949097

____
Miki Marshall
Vancouver, WA
