### ISSUE TITLE
Startup delay

### ISSUE THREAD

**Issue by MikiMarshall** [typora/typora-issues#2937]
I love Typora. It's the only app that gets markdown right that I know of, and keeps it SIMPLE. That said, lately I've noticed it is taking longer and longer to start up. It used to be nearly instantaneous, but later updates seemed to make it slower and slower (at least on Linux). Now it can take nearly a minute to start.

I'm not sure, but it seems to be related to whether I've had a chance to sign on to the local wifi yet. Is it holding up the startup to check for updates? If so, I really wish it would do that in a different thread in the background. Getting to work is far more important to me than waiting to see if the software is perfectly up to date. Just saying. 

Thanks!  ^_^

**Comment by abnerlee** [comment]
Linux version does not have the check update logics, since they are managed by system.

Which theme do you use? If may be caused by loading web fonts / images if you are using a custom theme.

For other ajax, they are done in async way, and you could remove them by uncheck "send anonymous data" in preferences panel.

**Comment by MikiMarshall** [comment]
It seems that a stalled update was the culprit. I'm still not sure why it stopped updating after v.63, but once I got it going again, the long pause went away.
I'll keep an eye on it from now on, to see if it happens again and figure out why. 

Thanks so much for the replies and help. I'm so happy to see Typora still active, and still resisting feature bloat. Well done! ☺️

Miki

On October 26, 2019 9:06:08 AM PDT, AbnerLee <notifications@github.com> wrote:
>Linux version does not have the check update logics, since they are
>managed by system.
>
>Which theme do you use? If may be caused by loading web fonts / images
>if you are using a custom theme.
>
>For other ajax, they are done in async way, and you could remove them
>by uncheck "send anonymous data" in preferences panel.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/typora/typora-issues/issues/2937#issuecomment-546615847

____
Miki Marshall
Vancouver, WA

**Comment by abnerlee** [comment]
> I'll keep an eye on it from now on, to see if it happens again and figure out why.

Thanks, just reopen this after it happening again.

**Comment by ryanoley** [comment]
Updating OS to Catalina 10.15.5 resolved the issue
