### ISSUE TITLE
lags,stutter and makes high CPU usage frequently after updated to Win10 1903

### ISSUE THREAD

**Issue by Begin2aim** [typora/typora-issues#2938]
I've been using Typora for a long time and it is no doubt the best markdown editor I've ever used.
But after updated my computer to Win10 1903 on Oct 20 (before is 1809 and everything went fine)  Typora lags and stutter  every now and then, especially when typing and scrolling, meanwhile the CPU usage of Typora gets so high about 30% and it's just after Chrome, which makes me hardly work on Typora

the following is my status
CPU i5 8300H,8G RAM
less than 10000 words in a file
2 files opening at the moment
I have reinstalled 0.9.72 0.9.6 versions of Typora and still doesn't work

Could you give any suggestions?

![微信图片_20191022134549](https://user-images.githubusercontent.com/23374713/67261291-9153ab80-f4d2-11e9-833a-a78573bdd5f5.png)

**Comment by morgenman** [comment]
I also noticed this. Idling has considerable CPU usage

**Comment by abnerlee** [comment]
put into #68
