### ISSUE TITLE
Export to PDF doesn't do anything

### ISSUE THREAD

**Issue by stderr-to-devnull** [typora/typora-issues#2939]
To export, I need to use `Print to file` instead. Kubuntu 19.04, Typora 0.9.78

**Comment by abnerlee** [comment]
Which theme do you use?

please send us a sample *.md file and how did you install Typora, does export HTML / image works?

**Comment by JavaCafe01** [comment]
I'm on a dark theme: Night. If I try to export as PDF, I get a message saying that it doesn't support dark theme exporting yet, so I click the button that says `Print with default theme` and nothing happens. However, if I switch to a light theme and do it, it works completely fine.

I'm on Arch Linux running kernel 5.3.7, with Typora 0.9.78(beta)

**Comment by Muream** [comment]
Same thing happens to me on windows 10 with version 0.9.78 (beta)
The `Print with default theme` button doesn't work but if I manually switch to the default theme, it exports just fine.

**Comment by abnerlee** [comment]
should be fixed
