### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by mschroen** [typora/typora-issues#294]
Typora seems not to care for citations, e.g. @Einstein1905 is not syntax-highlighted.  Ofcourse it would be super-great to have Typora interpret this with regards to a .bib file, converting the citation to Einstein et al. (1905), but I understand that this is problematic. However, at least syntax-heiglighting of @Einstein1905 would be great!

**Comment by jackweinbender** [comment]
related: #66

**Comment by rkrug** [comment]
Yes - support of citations would be very useful! #66

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/912

**Comment by AhmedThahir** [comment]
Any updates on this?
