### ISSUE TITLE
Feature: show page border markers

### ISSUE THREAD

**Issue by stderr-to-devnull** [typora/typora-issues#2940]
So I start writing... and writing... and writing... ordered lists, unordered lists, headers, code blocks etc. When I export to PDF, I discover that code blocks, lists etc are broken between two pages. Fine, I use the page break HTML code (why isn't this a righ-click menu option or a button somewhere, remains a mystery), export again, re-check, discover new broken markdown elements between pages, go back, add page break, rinse, repeat.

It would be so much easier if there were visible page border markers in editor so that I know in advance where to place page breaks.

**Comment by abnerlee** [comment]
We don't want to bring pagination into this. Markdown is web / screen based, not page base, and it requires make all export options into view options.

You could use custom css to avoid page break (`page-break-inside`). Currently small code blocks won't be seperate into to pages.

Other workaround would be #1732

**Comment by stderr-to-devnull** [comment]
I already have the custom CSS, what do I write in it exactly, the `page-break-inside`? What is the exact syntax? As I understand from your answer, this will ***only*** prevent code blocks from being broken between pages?

**Comment by abnerlee** [comment]
```
pre {
  page-break-inside: avoid !important;
}
```
