### ISSUE TITLE
internal link is broken on PDF export in version 0.9.78

### ISSUE THREAD

**Issue by changhenry2** [typora/typora-issues#2941]
As title,  internal link is broken after update.
I tested the function in version 0.9.77 is fine.

**Comment by abnerlee** [comment]
Could you provide a sample file?

**Comment by changhenry2** [comment]
Sure, link is [here](https://send.firefox.com/download/74d46f7bb73227eb/#wVHnmm5T3VPpZO-9VWX-VQ)
In [exported PDF file](https://send.firefox.com/download/de1328becd43f414/#NtBaeQk5hW7NceyYHmLOkQ), there is no hyperlink at all.

**Comment by BrandoZhang** [comment]
Version 0.9.9.29.2 (3650)

**Comment by changhenry2** [comment]
Seems be fixed in 0.9.80 (Windows version)

**Comment by mdlockyer** [comment]
I have the same issue on 0.9.81-1 on Linux. 

The following link will not persist when exported to PDF:

```
[some-header](#some-header)
## Some Header <a name="some-header"></a>
```

**Comment by abnerlee** [comment]
should be fixed

**Comment by rishoocplace** [comment]
They are still broken in version 0.9.86 - windows version. Will appreciate if someone can help provide a fix?

**Comment by regomne** [comment]
It is still broken in version 0.9.98 - windows version.

**Comment by uo269450** [comment]
Still broken in version 0.10.9(beta) -  windows version

**Comment by abnerlee** [comment]
Provide a sample file, please

**Comment by MikeLin2018** [comment]
[example.md](https://github.com/typora/typora-issues/files/6475684/example.md)
[example.pdf](https://github.com/typora/typora-issues/files/6475686/example.pdf)

Typora: Version 0.10.9 (5330)
MacOS: Catalina Version 10.15.7

**Comment by MikeLin2018** [comment]
Do we have any update on this issue?

**Comment by abnerlee** [comment]
try 0.10.11 ?

**Comment by MikeLin2018** [comment]
Still observe this issue in version 0.10.11 with the same example. https://github.com/typora/typora-issues/issues/2941#issuecomment-840910125

**Comment by hollowshiroyuki** [comment]
Good evening, the issue is still here in 1.0.3 👋
