### ISSUE TITLE
Pasted URLs always surrounded by extra space, even when not necessary

### ISSUE THREAD

**Issue by nanoant** [typora/typora-issues#2943]
When pasting any link or URL, such as an URL from Chrome or Safari address bar (**not** using `Paste as Clear Text`) Typora will auto-convert the URL to Markdown link. However I noticed that starting from some recent release it always adds some extra leading and trailing space.

Can we please have a way to turn this off. I keep collecting some links in my notes, and this new behavior serves no purpose as I don't need that extra space, e.g. pasting some URL:
1. From this: `1._|` - where `_` is a space and `|` is current caret position,
2. I get this `1.__https://someurl.com/_` - extra space in the font of the URL and extra trailing space.

This is somewhat related, but issue #1502, but I believe the problem I describe is quite new, whereas #1502 is old issue.

**Comment by Ziflin** [comment]
I just noticed this recently as well and was about to post a bug about it. 
If you are adding a link and type:  

`[My Link](<Ctrl+V>)`

You end up with spaces before and after what is pasted inside the URL portion. This actually breaks being able to Ctrl+click any of the links in the edited page as Typora then thinks that the _space_ at the beginning means the URL is a local/relative file.

Having it _not_ add the extra spaces should fix this bug. (I imagine it would also be fine if Typora also trimmed whitespace at the start/end of the URL as well.)

**Comment by jlahijani** [comment]
This is fixed in v0.9.80.

**Comment by nanoant** [comment]
I confirm it has been fixed. Thank you.
