### ISSUE TITLE
(graph with mermaid) the text in the generated image is incomplete

### ISSUE THREAD

**Issue by zhaoleipeng** [typora/typora-issues#2946]
system: macos mojave 10.14.6
typora version: 0.9.9.29.2(3650)

 
![image](https://user-images.githubusercontent.com/15973504/67446145-2c1ec800-f642-11e9-84c5-0041105a64d9.png)

look this picture, the text in the generated image is incomplete. i cannot find any infomation about this.please tell me how to solve it. i have already reinstall it.

**Comment by abnerlee** [comment]
Possible to attach the mermaid source?

**Comment by abnerlee** [comment]
#2947

**Comment by zhaoleipeng** [comment]
good
