### ISSUE TITLE
[Released] VLOOK V9.2 - a plugin for enhancements to HTML files exported by Typora

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#2949]
**VLOOK V9.2 is released~**

GitHub：https://github.com/MadMaxChow/VLOOK
doc：https://madmaxchow.github.io/VLOOK/index.html
Download：https://github.com/MadMaxChow/VLOOK/releases

**Comment by abnerlee** [comment]
added in doc: https://support.typora.io/Export/#example-export-using-vlook
