### ISSUE TITLE
Hashtags in macOS

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2951]
I just copied my notes from Linux to macOS. I have used hashtags (example: #term) in the text. In Windows and Linux such a word is rendered as such, i.e. as #term, whereas in macOS it is rendered as a Header 1. In Windows and Linux a Header consists of a # separated by a **gap** from a term/word/phrase, which, if I am not mistaken, is the Markdown way.

Is this a bug in macOS? If it is not, it means hashtags cannot be used in macOS.

**Comment by vassudanagunta** [comment]
check your Typora settings.

**Comment by DutchPete** [comment]
@vassudanagunta : thanks for your help. That helped, although a hashtag at the beginning of a sentence is still rendered as a heading. That is less serious, but it is different from Linux.

**Comment by abnerlee** [comment]
@DutchPete you should actually enable "strict mode" in preferences panel to prevent "#a" be rendered as `<h1>`

Tga support should refer to #1393

**Comment by DutchPete** [comment]
> @DutchPete you should actually enable "strict mode" in preferences panel to prevent "#a" be rendered as `<h1>`
> 
> Tga support should refer to #1393

@abnerlee : you closed this, but for others who might stumble across this issue I would like to confirm that the "strict mode" does the trick. Thanks @abnerlee.

**Comment by vassudanagunta** [comment]
@DutchPete Sorry, I had meant to say 'enable' strict mode. 😜
