### ISSUE TITLE
plantuml not working with gravizo

### ISSUE THREAD

**Issue by rmcclaincf** [typora/typora-issues#2952]
Running Version 0.9.9.29.2 (3650) on OSX 10.14.6

This markdown does not work:

![blah](https://g.gravizo.com/svg?
@startuml;

component Foo 

@enduml
)

It makes no attempt to render an image.  It seems that dotviz works, but not plantuml.

**Comment by abnerlee** [comment]
Please notice that that markdown also does not work in Github here.

Please remove the line break, it is not a valid image syntax

**Comment by yoyos** [comment]
This syntax should be used and converted correctly by interpreter using gravizo or else ..

```
` ` `plantuml 
(content)
` ` `
```
