### ISSUE TITLE
Custom css page break doen't work.

### ISSUE THREAD

**Issue by sanghyun-park** [typora/typora-issues#2953]
Hello,

Im using version 0.9.79 on Windows.

With my custom css,
```
@media print {
    h1 {
        page-break-before: always;
    }
}
```

`h1` page-break doesn't work on exporting PDF.

But, When i export to HTML first then print from Chrome web browser, it works.

* Reference by http://support.typora.io/Page-Breaks/

**Comment by abnerlee** [comment]
should be fixed
