### ISSUE TITLE
[Suggestion] Is it possible to add lazy-loading feature to typora?

### ISSUE THREAD

**Issue by Landius** [typora/typora-issues#2955]
[https://web.dev/native-lazy-loading](https://web.dev/native-lazy-loading)
It would be really helpful for people that got plenty of pictures in their MD files.
avoid loading unnecessary image, speed up render time, reduces memory usage

**Comment by abnerlee** [comment]
The usage may be quite limited on Typora, in https://web.dev/native-lazy-loading/#image-loading:

> To prevent the surrounding content from reflowing when a lazy-loaded image is downloaded, make sure to add height and width attributes to the <img> element or specify their values directly in an inline style:

While for user's content, Typora cannot predict its size before loading it.

relates #68
