### ISSUE TITLE
Display image on VeraCrypt drive on macOS

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2956]
Mac version 0.9.9.29.1

I have images stored on a VeraCrypt drive. I can link to an image and the Typora file will display the image. When I close the file, then reopen it, the link syntax is still there but the image is not displayed, even though the VeraCrypt drive is open.

On Linux Typora has no problem with this.

**Comment by abnerlee** [comment]
What's your macOS version?

What is the image link look like in Typora? does it starts with `/Volume/`?

**Comment by DutchPete** [comment]
macOS: Mojave 10.14.6
Yes, the image link in Typora starts with `/Volume/`

**Comment by DutchPete** [comment]
I just found out what the issue is: there should not be any gaps in the path. Any gaps should be filled with`%20`.

@abnerlee: any chance to have Typora pick this up and insert `%20` automatically if there are gaps?

**Comment by abnerlee** [comment]
Could you share the full image path or send it to us (hi@typora.io)?

**Comment by abnerlee** [comment]
similar #2995

**Comment by abnerlee** [comment]
Please try 0.9.9.29.2, I cannot reproduce it on newer version.

**Comment by DutchPete** [comment]
@abnerlee : Yep, on the latest version that does not happen.
