### ISSUE TITLE
folder browser and multiple tabs

### ISSUE THREAD

**Issue by jeffreyjohnens** [typora/typora-issues#296]
This is quite easily the best looking markdown editor.
Is it possible to have a folder browser panel on the side and support for multiple tabs.

Thanks for your consideration

**Comment by pravin** [comment]
+1 For the folder view. Often I work with multiple files and it would be so awesome to have a panel like textmate/atom/sublime

**Comment by yfwz100** [comment]
I think it should be implemented as an extension if Typora has the plan for it.

**Comment by vassudanagunta** [comment]
Dupe of #57

**Comment by abnerlee** [comment]
Dupe of #57

And for macOS users, upgrade to macOS sierra, and multi tab is supported.

**Comment by mc90716** [comment]
The typora looks great,and when typora support multi tab,thanks.

**Comment by mhenry1384** [comment]
Not having tab support is more irritating than I would have imagined.
