### ISSUE TITLE
Question: on Mac there is no Save AS

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#2960]
On Linux and Windows there is a `Save As` option for a newly created file, but on Mac there is only `Duplicate`. Any chance to incorporate `Save As`?

**Comment by abnerlee** [comment]
`Save As` is `Duplicate` in macOS, this seems to be the macOS standard, same with TextEditor.app, Pages.app and others

**Comment by AlexPasternak** [comment]
@DutchPete, specifically if you hold the Alt key while accessing the menu, Duplicate changes into Save As... Preview is another app where you can see this standard behavior. I confirmed it's the same in Typora.
