### ISSUE TITLE
Block MathJax in PDF rendered in small size if auto numbering equations

### ISSUE THREAD

**Issue by desperadoshi** [typora/typora-issues#2961]
Block MathJax is rendered in really good status in Typora editor, with auto numbering equations enabled or disabled. And it is also OK in PDF output if the auto numbering equations is disabled. However, if auto numbering equations is enabled, the block MathJax is rendered in so small font size in the PDF output, also in the html output.
Here is a sample md

```
# heading

This is an equation of $u$

$$
u_t = u_{xx}
$$
```

![Good rendering without auto-numbering enabled](https://user-images.githubusercontent.com/9106886/67658313-37e8f200-f994-11e9-86a3-bab279aa5168.jpg)

![Bad rendering with auto-numbering enabled](https://user-images.githubusercontent.com/9106886/67658319-3ae3e280-f994-11e9-8cd5-6e26cd52e9aa.jpg)

Typora version: 0.9.79.
OS: Windows 10.

**Comment by abnerlee** [comment]
put into #3662
