### ISSUE TITLE
An option for displaying file path in the title bar

### ISSUE THREAD

**Issue by 3jins** [typora/typora-issues#2962]
### pain point example
When I open multiple `README.md` files from different projects, it's little bit confusing since all title bars of the windows are just displaying `README.md`.

### improvement proposal
An option for displaying file path in the title bar would make it much more recognizable. So I want an option that can change the window title from like `README.md` to like `C:\Users\3jins\workspace\sample-project\README.md`.

**Comment by abnerlee** [comment]
duplicate with #2184
