### ISSUE TITLE
Possibility to not open side bar on start or to change the default save location

### ISSUE THREAD

**Issue by MetalGearBronya** [typora/typora-issues#2963]
Currently, if the start up option is set to open a new file, the default save location is always Documents in Windows. 
A workaround is to set Typora to start and open an directory, however this will force the side bar to open (even when the folder is empty). This kind of violates the usage of Typora as a minimal writing tool, as people may get distracted by the previous work in the side bar. It also adds to the start up time if the number of file is large. 

Since my primary goal is just to save the time to change the location on each save, it would be really appreciated if we could just change the default saving path when the start up option is to open a new file (the simpliest form). 
It's also a good idea to give an option for not showing the side bar (when opening a dir on start) on start though, due to the benefits listed above. 

Regards.

**Comment by abnerlee** [comment]
We are less likely to provide so detailed option.

But in new version, Typora will remember the sidebar status on launch.
