### ISSUE TITLE
Can not input on macOS 10.15 

### ISSUE THREAD

**Issue by liysky** [typora/typora-issues#2965]
just a blank, doesn't work and doesn't have any response.
It looks like that typora can't read any files.

**Comment by DutchPete** [comment]
Otr it could be that Catalina is screwing up. After all, there have been issues, which Apple released some sort of beta fix for, and are now working on Catalina 10.15.1 as an official stable release.

Why should @abnerlee spend time on something that in all probability is not Typora's issue?

**Comment by liysky** [comment]
> Otr it could be that Catalina is screwing up. After all, there have been issues, which Apple released some sort of beta fix for, and are now working on Catalina 10.15.1 as an official stable release.
> 
> Why should @abnerlee spend time on something that in all probability is not Typora's issue?

Setting it has the Full Disk authorization also doesn't work. 
It was suddenly crashed.  T_T...

**Comment by liysky** [comment]
And it works. I back to the version0.9.9.28.5 (3442).

**Comment by abnerlee** [comment]
see #2923, not knowing why but it works after remove existing config and cache files
