### ISSUE TITLE
indent/unindent with list totally wrong

### ISSUE THREAD

**Issue by hitzhangjie** [typora/typora-issues#2966]
Before I can use `tab` to change indent/unindent level, after upgrade to version 0.9.9.29.2, it works totally different.

I used unordered list, why indent/undent change that to ordered list, pressing `command+]`. Pressing `tab` now only add some spaces in the text, not indent.

**Comment by hitzhangjie** [comment]
The bug is the code take my unordered list as ordered list. That's too bad for writing experience.
Break my article structures.

**Comment by abnerlee** [comment]
In my test, Tab still working for list indentation, could you attach a screencast for the wrong behavior?
