### ISSUE TITLE
CPU Usage Issue Mac Catalina

### ISSUE THREAD

**Issue by Syphixs** [typora/typora-issues#2968]
Since the update 0.9.9.29.2 (3650) my MacBook Pro (15-inch, 2018 / i9 Model) running on Catalina 10.15 gets totally obliterated from Typora. 

![image](https://user-images.githubusercontent.com/33832024/67765282-092e5280-fa4c-11e9-9b1d-67b565f2cb04.png)

**Comment by DutchPete** [comment]
@Syphixs : how about downgrading back to Mojave?

**Comment by abnerlee** [comment]
Does this happen after restart Typora or reboot your OS?

If it still happens frequently, could you provide an sample *.md file to us (hi@typora.io)? and which theme did you use?

**Comment by abnerlee** [comment]
merge into #68
