### ISSUE TITLE
Add support for plantuml diagrams

### ISSUE THREAD

**Issue by lazdmx** [typora/typora-issues#297]
I think it would be very helpful for developers to have [plantuml](http://plantuml.com) syntax/rendering supported just like we have with [js-sequence](https://bramp.github.io/js-sequence-diagrams/).

**Comment by zmlade** [comment]
With plantuml support typora will be the ultimate tech writer tool. 
+1

**Comment by RoRoche** [comment]
+1

**Comment by FelixHerz** [comment]
+1

**Comment by addozhang** [comment]
totally agree

**Comment by zmlade** [comment]
+1

**Comment by maxiee** [comment]
+1s

**Comment by f8ttyc8t** [comment]
Would be nice!

**Comment by edgars-pivovarenoks** [comment]
+1

**Comment by jamescpp** [comment]
can not agree more

**Comment by lazydeer** [comment]
+1

**Comment by linxxx3** [comment]
+1

**Comment by zjiemain** [comment]
emergency need

**Comment by KZhou-ZJU** [comment]
+1

**Comment by jronrun** [comment]
+1

**Comment by idvorkin** [comment]
+plantuml

**Comment by lanshenghai** [comment]
+1

**Comment by MaidenJD** [comment]
+1

**Comment by FlorianRappl** [comment]
I would love that. Even more I would love some extensibility, e.g., provided by a plugin system. Then such feature requests could be solved by the community.

**Comment by DuanSky22** [comment]
+1

**Comment by langheran** [comment]
+1

**Comment by rexzhang** [comment]
+1

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1138

**Comment by tryup** [comment]
+1
