### ISSUE TITLE
crash when open

### ISSUE THREAD

**Issue by conn4575** [typora/typora-issues#2972]
Always blank when I open it
*  OS version: 10.13.6
* Typora version: 0.9.9.29.2

```
默认	20:04:13.229268 +0800	Typora	error on exec js: Error Domain=WKErrorDomain Code=4 "发生了 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'File.editor.undo.hasUndo'), WKJavaScriptExceptionColumnNumber=1206244, WKJavaScriptExceptionSourceURL=file:///Applications/Typora.app/Contents/Resources/TypeMark/app/main.js, NSLocalizedDescription=发生了 JavaScript 异常}
默认	20:04:15.061780 +0800	Typora	callHandler: File.getContent, but webview is loading...
默认	20:04:15.065378 +0800	Typora	error on exec js: Error Domain=WKErrorDomain Code=4 "发生了 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'b.editor.undo.lastRegisteredOperationCommand'), WKJavaScriptExceptionColumnNumber=176113, WKJavaScriptExceptionSourceURL=file:///Applications/Typora.app/Contents/Resources/TypeMark/app/main.js, NSLocalizedDescription=发生了 JavaScript 异常}
默认	20:04:18.079544 +0800	Typora	Removing presenter D72651BB-1E87-4ECB-8F25-0039E7215386
默认	20:04:18.079653 +0800	Typora	Removing presenter D72651BB-1E87-4ECB-8F25-0039E7215386
默认	20:04:18.091404 +0800	Typora	error on exec js: Error Domain=WKErrorDomain Code=4 "发生了 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'File.editor.undo.hasUndo'), WKJavaScriptExceptionColumnNumber=1206244, WKJavaScriptExceptionSourceURL=file:///Applications/Typora.app/Contents/Resources/TypeMark/app/main.js, NSLocalizedDescription=发生了 JavaScript 异常}
```

**Comment by xjf729** [comment]
- MacOS version: 10.15
- Typora version: 0.9.9.29.2

also has this problem

**Comment by leewi9** [comment]
@abnerlee this is a serious problem , can you fix it asap, if you can not, please opensource it.

**Comment by abnerlee** [comment]
Does clear Typora config / cache using 3rd apps like AppCleaner works?

**Comment by PRESIDENT810** [comment]
Same here, blank screen and cannot type anything

**Comment by abnerlee** [comment]
> Does clear Typora config / cache using 3rd apps like AppCleaner works?

Please tell me if it works or not.. Or try #2923

If not resolve, please provide necessary error logs which you can get from Console.app

**Comment by zrfrank** [comment]
My problem is the entire UI is freezed, 
- the editing area is just blank
- no responding when clicked
- no responding when menu bar item is clicked

I've completely uninstalled Typora including files in `/var`, and reinstalled it freshly.
However, the issue persisted.

I believe it's still related to macOS Catalina update.
And I guess there is some problem of the javascript engine while launching.

**Comment by leewi9** [comment]
same here.

pls solve it asap.

**Comment by abnerlee** [comment]
relates #3030 But I never met this.

@zrfrank  have you try use OS 10.15.1, and give Typora "Full Disk Access" in "Security & Privacy, and restart macOS.

If still happens, could enable debug mode in help menu, and see if there are "inspect element" in context menu, click it and grab some console errors.

**Comment by zss0329** [comment]
> Always blank when I open it
> 
> * OS version: 10.13.6
> * Typora version: 0.9.9.30.1
> 
> ```
> 默认	20:04:13.229268 +0800	Typora	error on exec js: Error Domain=WKErrorDomain Code=4 "发生了 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'File.editor.undo.hasUndo'), WKJavaScriptExceptionColumnNumber=1206244, WKJavaScriptExceptionSourceURL=file:///Applications/Typora.app/Contents/Resources/TypeMark/app/main.js, NSLocalizedDescription=发生了 JavaScript 异常}
> 默认	20:04:15.061780 +0800	Typora	callHandler: File.getContent, but webview is loading...
> 默认	20:04:15.065378 +0800	Typora	error on exec js: Error Domain=WKErrorDomain Code=4 "发生了 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'b.editor.undo.lastRegisteredOperationCommand'), WKJavaScriptExceptionColumnNumber=176113, WKJavaScriptExceptionSourceURL=file:///Applications/Typora.app/Contents/Resources/TypeMark/app/main.js, NSLocalizedDescription=发生了 JavaScript 异常}
> 默认	20:04:18.079544 +0800	Typora	Removing presenter D72651BB-1E87-4ECB-8F25-0039E7215386
> 默认	20:04:18.079653 +0800	Typora	Removing presenter D72651BB-1E87-4ECB-8F25-0039E7215386
> 默认	20:04:18.091404 +0800	Typora	error on exec js: Error Domain=WKErrorDomain Code=4 "发生了 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'File.editor.undo.hasUndo'), WKJavaScriptExceptionColumnNumber=1206244, WKJavaScriptExceptionSourceURL=file:///Applications/Typora.app/Contents/Resources/TypeMark/app/main.js, NSLocalizedDescription=发生了 JavaScript 异常}
> ```

I also like this, how to sove it ?

**Comment by zrfrank** [comment]
@abnerlee I've retried full uninstall and reinstall. Once it reinstalled, it worked fine. Until I adjust Typora's preference, then reopen, the app freezes. Could the problem be caused by i/o preference file?

I can enable debug mode from the menu bar, however, the context menu won't show anything besides "insert from iphone or ipad".

I use 10.15.1, while the app itself won't pop up full disk access request. (i could ofc manually give such permission). Generally, I don't understand why you would request such permission, and I am not conformable either to give any app full disk access permission.

**Comment by valicsek** [comment]
Same here. I tried to reinstall it. 
When I open the typora, I cannot type, or open anything at all. If I try to open something (.md) file, it's freezing. 

If you change the theme, it will not reload it.

Mac: Version 10.15.1 (macOS Catalina)
Typora: Version 0.9.9.30.1 (3794)

**Comment by abnerlee** [comment]
updated older macOS support info -> https://support.typora.io/Older-macOS-Support/

unfortunately, 10.13 are no longer supported.
