### ISSUE TITLE
Spell check fails to recognize installed Typora-only dictionary on Windows 10

### ISSUE THREAD

**Issue by michaelpierrelee** [typora/typora-issues#2973]
Dear maintainers, 

This issue seems not rare among Windows 10 users, as noticed on this github but for specific languages (#2315 #2298), and should be considered as an important bug in a daily use of Typora by multi-language users.

The issue is the following:
- the spell check from windows is working fine, but the user wants to change the spell check from "autodetect" to another language, different from the one of his/her OS;
- of course, the errors `spell check (LANGUAGE) is unavailable` and `Dictionary file is missing to enable spellcheck support for LANGUAGE`;
- click on `install dictionary file only for typora`; it installs the language but the errors are still there and the spell check is not enabled for the newly installed software.

I think it comes from a problem to detect internal dictionaries in some configurations and not directly from spell checking which doesn't have issue to recognize OS languages. However, having to change Windows configuration is not a reliable solution.

I noticed:
- on windows 10 for Typora x32 and x64 (v0.9.79 but I have the same problems in previous builds) - with French as default language in my OS, but it was also the case for different languages for other users
- the dictionary files are well downloaded in their directory {typora_user_folder}/dictionaries (.aff and .dic)
- start/restart doesn't solve the issue, neither click on "auto detect" then the language, as suggested by other issues relation to spell check
- I removed {typora_user_folder} after each reinstall 
- all Typora dictionaries are concerned, except the one related to the default language in the OS
- it didn't change anything to download files from dict.typora.io
- no problem in the log file
- computer restart didn't change the problem

Hope you will be able to reproduce the bug.

Thanks

**Comment by abnerlee** [comment]
> click on install dictionary file only for typora; it installs the language but the errors are still there and the spell check is not enabled for the newly installed software.

Which language are you trying to install ?

**Comment by michaelpierrelee** [comment]
Hi,
I tried every language and no one worked, but, as I said, 
However, I just tried on another machine, with the same windows, and there was no bug. I am available to perform some tests.
Thanks

**Comment by abnerlee** [comment]
does this happens in v0.9.87?

relates #214
