### ISSUE TITLE
Configure MathJax

### ISSUE THREAD

**Issue by Atcold** [typora/typora-issues#2974]
MathJax [is configurable](https://docs.mathjax.org/en/v1.0/configuration.html#configuring-mathjax). To do so, one is supposed to edit the `config/MathJax.js` file. Right now I'm able to find only the main `MathJax.js` file. Can you point me to where the config one is supposed to be stored?

# Context

In order to get bold math it is recommended to use `\bm{}`. Currently, in order to have MathJax supporting it one needs to add
```javascript
MathJax.Hub.Config({
  TeX: {
    Macros: {
      bm: ["{\\boldsymbol #1}",1],
    }
  }
}
```
to my MathJax configuration. Any idea where this should be added to?

This is strictly (for me) necessary because
```latex
z = \bm{w}^\top \bm{x} + \bm{b}
```
would become
```latex
z = \boldsymbol{w}^\top \boldsymbol{x} + \boldsymbol{b}
```
which is ridiculous to type.

Additional question: is there autocompletion available for LaTeX?

**Comment by Atcold** [comment]
Cool, figured it out. Maybe this should be added to the documentation.
In order to add LaTeX macro one can edit the `/Applications/Typora.app/Contents/Resources/TypeMark/index.html`.

There one can find the following code block
```javascript
<script type="text/x-mathjax-config" aria-hidden="true" >
  MathJax.Hub.Config({
    skipStartupTypeset: true,
    jax: ["input/TeX", "output/SVG"],
    extensions: ["tex2jax.js", "toMathML.js"],
    TeX: {
      extensions: ["noUndefined.js", "autoload-all.js", "AMSmath.js", "AMSsymbols.js", "mediawiki-texvc.js"],
      mhchem: { legacy: false },
    },
...
```
All you need to do is add your macros in the `TeX` section. For example, to support the `\bm` command and add Real numbers, expectationn and variance, we can do the following.
```javascript
Macros: {
  bm: ['{\\boldsymbol #1}',1],
  R: '\\mathbb{R}',
  E: '\\mathbb{E}',
  V: '\\mathbb{V}',
}
```

**Comment by Atcold** [comment]
Shall we let the users to be able to add any macros via the Typora / Preferences... menu?
Just a text box, where the user can write their MathJax configuration, to be injected later in the `index.html`.

What do you think?

**Comment by abnerlee** [comment]
Modification in index.html will be overwritten after updates.

This should be fixed by #100

**Comment by Atcold** [comment]
@abnerlee, I don't think the issue you linked shows how to add a persistent macro.

**Comment by abnerlee** [comment]
The link is not about "how to add a persistent macro", but a duplicated request

**Comment by Atcold** [comment]
Oh, I misunderstood your

> This should be fixed by #100

Since it is **not** currently fixed.

**Comment by Atcold** [comment]
The latest update broke the hack here suggested.

The alternative is to copy your configuration in every file you edit. For example my file now starts like this:
```Tex
$\LaTeX$ macros: $
\DeclareMathOperator{\sam}{softargmax}
\def \bm#1 {\boldsymbol#1}
\def \R {\mathbb{R}}
\def \E {\mathbb{E}}
\def \V {\mathbb{V}}
$.
```

**Comment by manroygood** [comment]
Hey @Atcold I was able to get most of your hack to index.html to work but not copying the configuration to the top of the individual markdown file file.  It seems as if it recognizes it as code and fences it.

Everything works in the index file except for the operator that you've created "\sam" and that's the one I most want. All I see after I finish writing the latex code is the characters  \sam in red letters.

**Comment by Atcold** [comment]
Hmm... This is how it looks for me, using Version 0.9.9.31.4 (4005).

![Screenshot 2020-01-28 12 03 47](https://user-images.githubusercontent.com/2119355/73286923-690cd480-41c6-11ea-80fb-54a357db6baf.png)
![Screenshot 2020-01-28 12 04 08](https://user-images.githubusercontent.com/2119355/73286929-6c07c500-41c6-11ea-8cee-678d8f143692.png)

Can you share a few screenshots here?

**Comment by manroygood** [comment]
I'm using the same version.

It turns that first part into a highlighted code block, as in this screenshot. None of the definitions work, as seen in this screenshot:

<img width="927" alt="Screen Shot 2020-01-28 at 9 13 28 PM" src="https://user-images.githubusercontent.com/31519627/73322874-992e9480-4213-11ea-8a70-310e6fd9c5a0.png">

**Comment by Atcold** [comment]
Try adding a space after `\sam` and before `t`.
What does it look like?
