### ISSUE TITLE
korean character delete issue

### ISSUE THREAD

**Issue by dohoon19** [typora/typora-issues#2975]
When using Korean, all words until the space bar is entered are blocked with underline. At this time, if I delete a character using backspace, all the blocked characters are deleted. In addition, the position of the cursor also moves to strange places. Please let me know how to solve it.

**Comment by abnerlee** [comment]
Which OS / Typora version? Which IME did you use to input Korean? Possible to send us (<hi@typora.io>) a screencast about your operation?
