### ISSUE TITLE
Cant use ibus on typora

### ISSUE THREAD

**Issue by iceBear67** [typora/typora-issues#2976]
Sys: ArchLinux 5.3.7-arch1-2-ARCH #1 SMP PREEMPT @1572002934 x86_64 GNU/Linux
TyporaVersion: 0.9.79(beta)
Sys&IM Locale: zh_CN.UTF8

I cant use ibus when im typing on typora.
and i also tried using this:
```
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
```
Could u help me?

**Comment by abnerlee** [comment]
https://github.com/flatpak/flatpak/issues/1671
https://github.com/flatpak/flatpak/issues/675

Do you use flatpak? Please try the binary version since flatpak is not official supported.

**Comment by jjangga0214** [comment]
@abnerlee This happens when installed with [the official instruction](https://typora.io/#linux), on 

**Info**: Ubuntu 20.04 with iBus
