### ISSUE TITLE
Changing theme in Theme menu does not change the theme in 0.9.9.26 later on macOS problem still exists

### ISSUE THREAD

**Issue by Herbert8** [typora/typora-issues#2978]
Duplicate with #2792? 

Please ensure Typora has privilege for `/Users/{username}/Library/Application Support/abnerworks.Typora/themes/`, or just remove `/Users/{username}/Library/Application Support/abnerworks.Typora` and start Typora again, Typora will create the folder

_Originally posted by @abnerlee in https://github.com/typora/typora-issues/issues/2839#issuecomment-546675031_

No, your method doesn't work. After you deal with it, the problem still exists. I have tried to create a new user and then open Typora, and I have the same problem, so it should not be the kind of permission problem you said. Please do not rush to close this issue for the time being.

**Comment by abnerlee** [comment]
How about removing all Typora related config and cache using 3rd apps such as AppCleaner, and then restart Typora?

**Comment by Herbert8** [comment]
> How about removing all Typora related config and cache using 3rd apps such as AppCleaner, and then restart Typora?

I have cleaned up with CleanMyMac. And for testing, I created a brand new account to ensure that the account does not contain any old information related to Typora. But the problem still exists.

**Comment by abnerlee** [comment]
@Herbert8 Possible to send us (<hi@typora.io>) a screencast for debug purpose?

**Comment by abnerlee** [comment]
And do you open Typora from `/Applications/Typora.app` ?

**Comment by Herbert8** [comment]
> And do you open Typora from `/Applications/Typora.app` ?

Bug details I have emailed to hi@typora.io, and I also did a detailed description of the problem at https://github.com/typora/typora-issues/issues/2839, but Issue was closed, and the issue Still not solved.

Also, must Typora.app be placed in /Application to run? Looks like it has nothing to do with this.
