### ISSUE TITLE
Source codes for ordered list was wrong

### ISSUE THREAD

**Issue by Tiscs** [typora/typora-issues#298]
Source codes for orderd list will append more number where order is equal or greater then 10.
<img width="710" alt="qq20160922-0 2x" src="https://cloud.githubusercontent.com/assets/2810237/18741694/18b4948e-80e3-11e6-92cc-1f7bb8629406.png">

**Comment by abnerlee** [comment]
Is there any detailed steps to reproduce this bug ?

**Comment by Tiscs** [comment]
I can share my markdown doc which has that problem.


Open "sample.md" in "[sample.zip](https://github.com/typora/typora-issues/files/487012/sample.zip)" with sublime/notepad(or some other text editor), ensure the order number for the eleven item is "11";

Then open it with typora(Mac or Windows application), change view mode to "Source Code Mode", the order number for the eleven item will be changed to "111".

**Comment by abnerlee** [comment]
should be fixed in new version
