### ISSUE TITLE
Choosing custom folder in settings freezes entire system for a few minutes

### ISSUE THREAD

**Issue by wmisha** [typora/typora-issues#2980]
OS: Ubuntu Linux 18.04.3 LTS

One of the features of Typora is the ability to select a custom folder to open at launch. When I select the `Open custom folder` option, a file explorer window pops up to allow choosing the folder interactively. However, at this point both windows as well as the entire desktop is frozen. The mouse can still move but I cannot click anything. I have reproduced this on at least two machines (same OS).

![image](https://user-images.githubusercontent.com/4308710/68062205-1a829380-fcc6-11e9-93f6-9f5160c00cf0.png)

Eventually, after a couple minutes (I may have also needed to launch the task manager), the system suddenly becomes responsive again.

Alternatively, this can be solved by allowing a path to be typed/pasted in rather than opening a new window to select the folder.

**Comment by abnerlee** [comment]
Do you install via `apt-get`? Can open file dialog be opened when you click "File" -> "Open" from menu, and "Open Folder.." from sidebar?

**Comment by alisterburt** [comment]
Hi,
Same issue here, installed via apt-get and can open a folder via file open and open folder no problem! Is there a config file I can edit manually in the meantime?

**Comment by Benny44** [comment]
Same issue here. It seems the mousepad freezes and doesn't have access to the screen any more. The keyboard seems to work, as I can see some tabs using the Alt key.

**Comment by LeBaux** [comment]
This does not appear to be a problem with Manjaro i3. Narrowing down to DE or Ubuntu problem.

**Comment by LinuxOnTheDesktop** [comment]
Datapoint: I don't have the problem on Mint 19.3 x64 Cinnamon, though (1) the dropdown menu (containing 'open new file', 'open custom folder', etc.) got detached, (2) when I open Typora, the custom folder that I selected does not seem, in any fashion, to get opened.

**Comment by abnerlee** [comment]
would be https://github.com/electron/electron/issues/21128

**Comment by abnerlee** [comment]
still happens in latest version?

**Comment by alisterburt** [comment]
I got rid of windows so can’t test unfortunately, hopefully someone else can chime in! Thanks for your efforts :)
