### ISSUE TITLE
Presented Mermaid don't supports hexagon node form 

### ISSUE THREAD

**Issue by askirmas** [typora/typora-issues#2981]
https://mermaidjs.github.io/#/flowchart?id=a-hexagon-node
```mermaid
graph LR
    id1{{This is the text in the box}}
```
https://mermaidjs.github.io/#/flowchart?id=trapezoid
```mermaid
graph TD
    A[/Christmas\]
```
https://mermaidjs.github.io/#/flowchart?id=trapezoid-alt
```mermaid
graph TD
    B[\Go shopping/]
```

**Comment by abnerlee** [comment]
merge into #2935
