### ISSUE TITLE
Is that possible to shorten the markdown syntax for Todo list?

### ISSUE THREAD

**Issue by fatefree24** [typora/typora-issues#2982]
For current version, when adding the to do list, we have to input "- [ ] ".
It's quite long to input when you focus on the article.
It will be great if possible to shorten or customize.

**Comment by DutchPete** [comment]
@fatefree24 : use a text expander, it will help you shorten/customise other parts of your workflow too. There is an excellent cross-platform one, [Espanso](https://espanso.org/), it is free and the dev, Federico Terzi, is very helpful and quick to respond; the community is also very helpful.

**Comment by abnerlee** [comment]
We are less likely to introduce "self-defined" syntax that is not supported by any other Markdown editors.
