### ISSUE TITLE
[BUG]Relative path of files would be changed to Absolute one in Windows version

### ISSUE THREAD

**Issue by huangwb8** [typora/typora-issues#2984]
I use the latest typora(0.9.79) of Windows 64bit version. When I try to output .md as PDF, I found the file of relative path would be changed to absolute one. For example,
```
[GeneSet of hubgenes_kegg.csv](./KEGG/GeneSet of hubgenes_kegg.csv)
```
when in PDF, it would be 
```
[GeneSet of hubgenes_kegg.csv](file://E:/../KEGG/GeneSet of hubgenes_kegg.csv)
```
When click the link, it would download the file instead of opening the file that had been prepared in the local path, which is not appreciated.
Is it a bug? Or I have to change some setting of typora? Thanks~

**Comment by yhkuan** [comment]
I face the same issue with the typora version `0.9.81` on Windows 10.

**Comment by abnerlee** [comment]
I'll merge this topic with #2546
