### ISSUE TITLE
Documents saved in Google Drive are not displayed in the File Tree

### ISSUE THREAD

**Issue by nakashima-y** [typora/typora-issues#2985]
Documents saved in Google Drive are not displayed in the File Tree.
Do I need any settings?

MacOS: Mojave 10.14.6（18G103）
Typora Version: 0.9.9.29.2 (3650)

| GoogleDrive |
| --- |
| ![GoogleDrive](https://user-images.githubusercontent.com/5312646/68081488-13888c00-fe52-11e9-863e-b0eb7478421c.png) | 

| Dropbox |
| --- |
| ![Dropbox](https://user-images.githubusercontent.com/5312646/68081495-3450e180-fe52-11e9-807d-1d034e472a44.png) |

**Comment by abnerlee** [comment]
Are they downloaded on our local disk?

**Comment by nakashima-y** [comment]
Yes. Downloaded.

**Comment by abnerlee** [comment]
In my testing it works just fine.

Do you use `alias` for Google Driver ? #1881
Or could you share the path of your Google Drive folder, also, there should be "Sync" or "Downloaded" icon for Google Drive, just like Dropbox, could you also confirm if you are using the lasted Google Drive app or are you using G suit client?

**Comment by nakashima-y** [comment]
change the folder name from "Google ドライブ" to "Google Drive", Now displayed in the file tree.
Thank you very much.
