### ISSUE TITLE
[Feature] Add multi-level numbers to headers in formatted document

### ISSUE THREAD

**Issue by WilliamStone** [typora/typora-issues#2986]
Hi,

I think Typora is a very good markdown editor, and I use it to read & write many long documents. I often find my self get lost in the document, e.g. it's hard to keep track the content i'm reading in whole document. It gets worse if I constantly modifying the document. When this happens I miss Microsoft Word, since it can automatically add leveled number to section headers.

e.g. in an example document the headers are as follows:

# Chapter 1
### Paragraph 3
# Chapter 2
### Paragraph 3

As it demostrates, when the document is very long, it is hard to tell the place where I'm reading in the document, even if I read nearest header, because it's hard  to remember structure of the document, especially if the document is unfamiliar.
Thus, I wish that the headers can be preceded a leveled number in formatted documents, like the following:

# 1 Chapter 1
### 1.3.3 Paragraph 3
# 2 Chapter 2

**Comment by DutchPete** [comment]
@WilliamStone : install the following in your base.user.css:
for autonumbering of headings in the text https://support.typora.io/Auto-Numbering/
for autonumbering in the outline: https://pastebin.com/XmYgBbaz
for autonumbering of the ToC: https://pastebin.com/NYugSbXk

These were recommended to me by Abner Lee, and they work perfectly in Linux and macOS.

**Comment by AlexPasternak** [comment]
On the [support page](https://support.typora.io/Auto-Numbering/), I would suggest @abnerlee fix

> Auto Numbering Outline panel.
Diable collapsable outline panel from preferences panel

to
> Auto Numbering Outline panel
Disable collapsible outline panel from preferences dialog

It took me a few seconds to understand what "Diable" was supposed to be.
