### ISSUE TITLE
Highlight bold text

### ISSUE THREAD

**Issue by Atcold** [typora/typora-issues#2987]
If I make something `==highlighted==` it looks okay.

<img width="219" alt="Screenshot 2019-11-03 22 24 19" src="https://user-images.githubusercontent.com/2119355/68098091-c378ec00-fe88-11e9-84c0-151c630c4c9c.png">

But if I make it first `**bold**` and then I `==highlight==` it, I get invisible stuff.

<img width="220" alt="Screenshot 2019-11-03 22 24 54" src="https://user-images.githubusercontent.com/2119355/68098100-d986ac80-fe88-11e9-9000-b536c06ad20d.png">

Luckily I can first `==highlight==` it and then `**bold**` it, and everything looks alright.

<img width="226" alt="Screenshot 2019-11-03 22 26 23" src="https://user-images.githubusercontent.com/2119355/68098126-f91dd500-fe88-11e9-92c1-74e8cae4454b.png">

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by Atcold** [comment]
Yup, I do confirm you've fixed it.
Thanks you.
