### ISSUE TITLE
keyBinding - How to add: Paragraph - Task List?

### ISSUE THREAD

**Issue by mavlutovr** [typora/typora-issues#2989]
Hello!

Tell me, please, what can I write to config for make shortcode for Task List?
I think to conf.user.json, to here:

```javascript
  // Custom key binding, which will override the default ones.
  "keyBinding": {
    // for example: 
    "Always on Top": "Ctrl+Shift+P"
  },
```

Like Ctrl+Shift+] for Unordered List.

**Comment by abnerlee** [comment]
Use the name in related menu item.
For detail, please check http://support.typora.io/Shortcut-Keys/

**Comment by mavlutovr** [comment]
@abnerlee thanks :)

It is work:

```javascript
"keyBinding": {
  "Task List": "Ctrl+Shift+T"
},
```
