### ISSUE TITLE
Copy Paste images without having to safe a file

### ISSUE THREAD

**Issue by karpathy** [typora/typora-issues#299]
**Add images with Copy Paste**.
I do a lot of random research brainstorming with Typora and I'd love to quickly capture a part of my screen (on mac this is very easy with CTRL+COMMAND+SHIFT+4) and then paste it into Typora. The file could be created automatically somewhere on the computer, e.g. in the location of the core markdown file, or maybe Desktop by default. I don't care about the name of the file, I just want to really quickly paste it into my file (e.g. Google Docs allows this).

I don't believe this is currently possible. I have to currently save the image somewhere on my disk and then insert it manually. This takes ~10 seconds and I end up doing it quite often. Thank you for your great work on Typora!

**Comment by abnerlee** [comment]
will be fix in #67

**Comment by karpathy** [comment]
For posterity I wanted to mention that this feature was added in a recent release.

The feature requires a specific setup step and I had to follow the instructions here: http://support.typora.io/Images/ under **"Copy image files to target folder when insert local image".**

Thank you to Typora for this awesome feature!!
