### ISSUE TITLE
Sometimes it freezes when just opening a file.

### ISSUE THREAD

**Issue by Kyleinhurricane** [typora/typora-issues#2991]
I can't texting, and none of the buttons works. I have to close it from the taskbar and rerun it.

**Comment by ischoonover** [comment]
This affects me too, but I wouldn't characterize it as a freeze. It only occurs on Linux. When I open a file, the contents are blank, and the menus don't respond. If I click in the contents textarea, the text shows up and the menus work again.

**Comment by abnerlee** [comment]
same with #2937?
