### ISSUE TITLE
Click file in file tree  open file in new tab.

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2992]
Currently when we click new file in file tree, typora open file in current tab.
I hope typora can surpport click new file in file tree, if the file is not open in tab list yet, then open in new tab; or is open in tab yet, then activate the coresponse tab.
Can change the default click behiviour, or add a config option to suport this.

The new behiviour is mose ide's(like pycharm) default bihiviour.

**Comment by abnerlee** [comment]
#1000
