### ISSUE TITLE
windows taskbar recent items is now empty

### ISSUE THREAD

**Issue by ascii78** [typora/typora-issues#2993]
As #2588 jumplist (last used documents) is now empty in windows 10 (10.0.18362.418). 

![image](https://user-images.githubusercontent.com/1138654/68228554-f391cd80-fff5-11e9-9d44-f0a5fb692cfb.png)

jumplist setting is on:

![image](https://user-images.githubusercontent.com/1138654/68228592-00162600-fff6-11e9-9c11-73b265a4753d.png)

**Comment by abnerlee** [comment]
Could you try remove it from taskbar, then open Typora again?

I cannot reproduce this, but there should be "New" task and recent files

**Comment by ascii78** [comment]
Ah, fixed it, unpin, start, then pin again brings back the list. Great editor btw.
