### ISSUE TITLE
Full Text Search not working - Error: spawn rg.exe ENOENT

### ISSUE THREAD

**Issue by wc852** [typora/typora-issues#2994]
When performing full text search, no result is shown. Error message is captured below.

- Windows 7 Professional Service Pack 1 (32-bit)
- Typora version 0.9.79 (beta)

`rg.exe` works properly when running in command prompt. See screenshot below.

```
ERROR 2019/11/6 上午10:27:37  [RenderProcess 2][Error] Error: spawn C:\Program Files\Typora\resources\app\node_modules\vscode-ripgrep\bin\rg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

---

![image](https://user-images.githubusercontent.com/57424833/68263698-8d528c80-0081-11ea-8c8c-2441b931d6e0.png)

![image](https://user-images.githubusercontent.com/57424833/68263066-0224c700-0080-11ea-8bed-4ba1a8eeb713.png)

![image](https://user-images.githubusercontent.com/57424833/68263273-8bd49480-0080-11ea-9b69-4652e67ec391.png)

![image](https://user-images.githubusercontent.com/57424833/68263354-c6d6c800-0080-11ea-9ac9-69fda668f05f.png)

**Comment by abnerlee** [comment]
Is your system 32bit or 64bit?

**Comment by wc852** [comment]
The OS is 32-bit. Windows 7 Professional Service Pack 1 (32-bit). Thanks.

**Comment by abnerlee** [comment]
Fixed in new release
