### ISSUE TITLE
Images beside the document are not loaded when the markdown file is opened from an UNC path.

### ISSUE THREAD

**Issue by cainkellye** [typora/typora-issues#2995]
When we open a markdown file from a shared directory like
`\\someserver.com\MainShare$\Project\Documents\Example\example.md`

the images that are included from the same directory by relative filename are not loaded but shown as simply:
`![](some_illustration.png)`

When it is mapped to a drive, it works as expected.
OS: Windows 10

**Comment by AirQuick** [comment]
When you insert an image whose native UNC path is `\\server.FQDN\share\dir\image.gif`, DevTool has this Network log entry:

```
General
  Request URL: file://server.FQDN/share/dir/image.gif?lastModify=...
  Request Method: GET
  Status Code: 307 Internal Redirect

Response Headers
  Location: https://server.FQDN/share/dir/image.gif?lastModify=...
```


and `typora.log` has this entry:

```
INFO ...  redirect to https://server.FQDN/share/dir/image.gif?lastModify=...
```

Typora seems to have a habit to think of the UNC file URL as `https://`.

**Comment by abnerlee** [comment]
put into #3981
