### ISSUE TITLE
Sometimes Typora freezes and has display problem

### ISSUE THREAD

**Issue by gotjek** [typora/typora-issues#2997]
[See video of the bug here.](https://drive.google.com/file/d/1T--9RLxplUe-eTGm55rQ5DfJBJ2tdzom/view?usp=sharing)

Edit: changing theme doesn't avoid freezes. Seems not to be related with wifi (#2937). Maybe like #2991?

Windows 10
Appeared in Typora 0.9.78, still in 0.9.79

**Comment by abnerlee** [comment]
merge into #3019
