### ISSUE TITLE
Non-breaking space characters randomly inserted in code fences

### ISSUE THREAD

**Issue by genomXplorer** [typora/typora-issues#2998]
Hi everyone,

I have an issue regarding **spaces in code fences**. I am using `Typora 0.9.9.29.2` on a `MacOS Catalina 10.15.1` and I copy my code on a server running on `Ubuntu 18.04.2 LTS`.

I am usually copying code from different web pages and paste it in code fences in Typora. Sometimes, when I copy this code from Typora and paste it in bash on a Linux based server, my line crashes. This line of code is working when I paste it directly from the website or when I paste it in Typora and re-copy it right away and paste it in bash. The issue seems to happen when I re-use the code "later".

To understand what was going on, I `echo` my line and used the command `cat -v` to show non-printing characters in bash. I discovered that Typora, somehow, inserted **non-breaking space character** in my code line which appears as `M-BM-`. Another intriguing observation is that using `echo` and `cat -v` on the very same line of code does not show any issue in bash on my Mac terminal.

Unfortunately, I did not detect any specific pattern for the error apparition. Some of my code is corrupted, while some remains correct.

I would be glad to have your view on this issue and let me know if you have any question.
Thank you in advance.

**Comment by abnerlee** [comment]
Could you attach a sample *.md file that non-breaking space is inserted?

**Comment by genomXplorer** [comment]
Hi @abnerlee,

Please find attached a .md with an example. While the space after `-i` is correct, there is a non-breaking space character after `run_BUSCO.py`.

Thank you. 

[test.md.zip](https://github.com/typora/typora-issues/files/3825421/test.md.zip)

**Comment by abnerlee** [comment]
Can you get the non-breaking space characters when paste into other apps on macOS, such as VSCode, etc?
If it works fine when pasting into other macOS app, the it should be an Ubuntu bug, there's one similar https://askubuntu.com/questions/623743/keyboards-writes-bad-space-characters-in-gnome-terminal
