### ISSUE TITLE
Unable to add " ^ " in math block

### ISSUE THREAD

**Issue by NTC** [typora/typora-issues#3]
Hello,

When I add a math block and I want to put a sum or a product with parameters, the software bug when I type ^ symbol.

Thanks,
Nicolas

**Comment by abnerlee** [comment]
@NTC if possible, would you tell me the whole expression you want to input or expression that trigger this bug?

In my testing, ^ with math block seems to work fine.

![snip20150830_1](https://cloud.githubusercontent.com/assets/1621242/9568002/9fd2be3c-4f70-11e5-8a4d-f07428e5a545.png)

**Comment by NTC** [comment]
I would like to input : \sum_{i=1}^{n} i
I can just enter \sum_{i=1}. When I press ^, I cannot write anything in the math block.
However, if I copy/paste the expression with the ^ , it works.

This issue might be linked to my OS X version : El Capitan (beta 6)

**Comment by abnerlee** [comment]
@NTC In my testing, I can enter `\sum_{i=1}^{n} i`, I will check it in El capitan later ( it may take some time).

**Comment by Fastidious** [comment]
@abnerlee tested on three machines running OS X 10.11. Not a single issue, math blocks worked as expected. I propose closing this one.

**Comment by Fastidious** [comment]
Example:

![untitled](https://cloud.githubusercontent.com/assets/8352292/9689327/5134ded6-5303-11e5-8322-23f839169747.gif)

**Comment by NTC** [comment]
It is very strange but the problem is real...

I think I have find an explanation : 
I'm a french user so I use a french keyboard where the ^ symbol is not a full key unlike english keyboard. It may cause the issue.

**Comment by abnerlee** [comment]
@NTC Thanks for the new info, I will trace this.

**Comment by Fastidious** [comment]
> I'm a french user so I use a french keyboard where the ^ symbol is not a full key unlike english keyboard. 

What do you mean? The "english keyboard" (US keyboard is what I have) does not have a dedicated key for ^, it is shared with the number 6. The French keyboard shares is with one or two other symbols, no?

**Comment by abnerlee** [comment]
@NTC would you check `Help`->`Enable Debugging` from menu bar, then click `Inspect Element` from context menu in typora. In the newly popped up debug window, click `Console`, and then reproduce the bug in typora. If there are **new** Error message in the debug window, could you tell me what are they?

**Comment by NTC** [comment]
No, There is any error message in the debug window. So I believe it's my mac which doesn't love maths in Typora :(

**Comment by creibmoc** [comment]
@NTC @abnerlee I'm also a French Mac user and I have the exact same problem, I can't get "^" to work in math blocks, however it does work in inline math. Copy/paste does work though.

When I type the "^" symbol, nothing shows on screen and if I try to type any other character after this I get the Mac "error" sound. Only thing I can do is backspace/delete.

I tried to open the debug menu to check the console, but there are no errors in the console... This is strange. Also tried opening index.html in chrome and safari to see if the issue comes from the wrapper, but the bug is still there.

**Comment by abnerlee** [comment]
@creibmoc could you tell me which key combination did you use to input "^" symbol ? For example, for US keyboard, I use shift+6 to input "^".

**Comment by creibmoc** [comment]
@abnerlee To input the ^ symbol, I press twice on the key left of the P letter (see image below). First press activates the "wait" state, and second press inputs the character. Here is how it works:

![](https://i.gyazo.com/65af0615ed06c720c7341228e34be38e.gif)

![ht1171_01-wireless_keyboard-001-fr](https://cloud.githubusercontent.com/assets/16068391/11469324/d21acdc6-9755-11e5-9322-330ccd37c71c.png)

Tried to input the character in a code fence, and it worked no problem. Also tried on the autocomplete link you sent, and it also works.

**Comment by abnerlee** [comment]
@creibmoc Thanks, I can reproduce it now.
And it is also fixed in v0.9.7.5, please check update after a few **hours** !

**Comment by creibmoc** [comment]
@abnerlee Thanks for the quick fix! So what was the problem?

**Comment by abnerlee** [comment]
@creibmoc I listened and handler IME events from math block in a wrong way ~
