### ISSUE TITLE
Export to DokuWiki

### ISSUE THREAD

**Issue by eagleofnorth** [typora/typora-issues#3001]
Is it possible to get Typora to export to the DokuWiki format?

Typora documentation says it can _import_ .dokuwiki files but not _export_ to it.

Thanks for all help.

**Comment by eagleofnorth** [comment]
Using pandoc on command line on a Typora file works fine:

`pandoc -f markdown -t dokuwiki typorafile.md >typorafile.dokuwiki`

So I would guess it could be easily built into the Typora export menu?

**Comment by abnerlee** [comment]
https://support.typora.io/Export/#other-wiki-format
