### ISSUE TITLE
ui-controls html in the theme creation .zip is not displaying well

### ISSUE THREAD

**Issue by skyblue002** [typora/typora-issues#3002]
I am trying to create my own theme. I'm using the Typora theme toolkit. The `ui-controls.html` file is not displaying coherently:
![Typora-ui-controls-html](https://user-images.githubusercontent.com/41849249/68383101-fe964c00-0122-11ea-8e21-43d61ed5af22.png)
It's really hard to create a theme when I can't tell where one element on the page ends and the next begins. This, by the way, is what it looks like by default. I haven't edited any `.css` files. I just unzipped the Typora theme toolkit.

I have tried scrolling up/down, resizing the window, and tried this `.html` file in two separate browsers. But, it still won't display well.

I'd really like to finish this theme I'm working on. Does anybody have a fix for this? Is there another version of this file? I can't imagine that it was released like this, so maybe updates to Chrome/Firefox broke the way it displays, somehow.

**Comment by abnerlee** [comment]
This http://support.typora.io/Add-Custom-CSS/#debug-css and https://theme.typora.io/doc/Write-Custom-Theme/#test-in-typora shows how to inspect element in a running Typora instance.

The `ui-controls.html` requires load local resources, the
"If you meet error like [Not allowed to load local resource: file://XXXX] in browser's console, the quickest solution for me is to use tools like httpster or CodeKit to host the web content into localhost." in the https://github.com/typora/typora-theme-toolkit describes your issue.
