### ISSUE TITLE
Outline ends at bottom of screen

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#3006]
I am on macOS 10.14.6 Mojave, Typora 0.9.9.29.2

I have a rather long document with headers and (sub)sub headers. In the Outline pane on the left the last header shown in at the bottom of the screen, even though I have more headers extending beyond that

**Comment by DutchPete** [comment]
Any idea if there is a specific reason why this occurs?

**Comment by abnerlee** [comment]
We haven't seen this kind of error, possible to send us a sample md file?

**Comment by DutchPete** [comment]
@abnerlee : I have only encountered this in 1 file, and it is a file I do not want to share because of the contents. Since you have not encountered it before, I'll leave it at this. Thanks for your offer to help.
