### ISSUE TITLE
Corrupted copy of smart dashes/ellipsis when "convert on rendering"

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#3008]
With smart dashes and smart quotes enabled as "Convert on rendering", copying text containing  `--` or `...` from WYSIWYG mode and pasting to a plain text application results in a hyphen plus mdash, or `..` followed by an ellipsis.

Either the original characters should be copied, or else just the replacement characters.  But what you actually get is the original text with the last character of the symbol replaced by the unicode version, so that  e.g. `...` ends up as  `..…`.  (That's two period characters followed by an ellipsis character).  Similarly, `--` ends up as `-–` (a hyphen character followed by an em dash character).

Note that this corruption happens regardless of whether I "copy as markdown", "copy as HTML Code", or "copy as plain text".

(Honestly, since I am using "Convert on Rendering" rather than "Convert on Input," it seems to me that smart punctuation should be copied in its original form unless copying as HTML code.  As things stand, I can only get the original markdown source by copying from source mode, which is a pain.  Copy As Markdown really ought to preserve the source and not change it in any way.)

**Comment by abnerlee** [comment]
fixed in new release

**Comment by pjeby** [comment]
Thank you!
