### ISSUE TITLE
Source code view and display view are inconsistent

### ISSUE THREAD

**Issue by cjM00N** [typora/typora-issues#3009]
version: latest 0.9.79
I dont know how to describe it ,  Sometimes, when I type, it change lines for no reason, and i cant delete it, but there is nothing in the source code view, left is source code view, right is the display view
![image](https://user-images.githubusercontent.com/21972169/68635503-bbc5e100-0533-11ea-8502-76e3595361dc.png)
This problem has happened many times, Not only in this version

**Comment by abnerlee** [comment]
Are you using Sougo IME?

**Comment by cjM00N** [comment]
@abnerlee yes, I am using Sougo IME? Is this the cause of the problem?

**Comment by abnerlee** [comment]
We confirmed known compatibility issues with Sougo IME, will be fixed in next version up.

**Comment by abnerlee** [comment]
should be fixed in new release
