### ISSUE TITLE
"Open Link" appears twice in right-click menu

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#3010]
In latest Typora Version 0.9.9.29.2, I see "Open Link" twice when right-clicking a link. This is even reproducible in just a simple new MD file with 1 line text, 1 line link.

<img width="422" alt="2019-11-13 10 43 45 AM" src="https://user-images.githubusercontent.com/1819485/68779424-a5d32180-0602-11ea-85d3-ba53967aa05d.png">

macOS 10.14.6.

**Comment by DutchPete** [comment]
I have the same, using the same macOS and Typora version. It is not disturbing, it just looks a bit odd.

**Comment by AlexPasternak** [comment]
Btw, the reason I noticed is that just clicking a link with a mouse does not work anymore. Pretty sure it used to? Even though a link is clickable, underlined, and cursor turns into a hand, clicking it does nothing except to move text I-beam. This is why I have to right-click to get that to happen and noticed this. Should I open a _separate_ issue for links not being clickable or is that a known issue, @abnerlee?

**Comment by abnerlee** [comment]
Fixed in new release.

> clicking a link with a mouse does not work anymore.
