### ISSUE TITLE
Cursor/selection bug

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#3011]
# Steps to reproduce
- Open a Typora window on Windows
- Type the following:
 ```Markdown
 - 123
 - 456
 ```
- Navigate the cursor before the 4
- Press Ctrl + Shift + Right, so `456` is selected
- Press Shift + Left

# Expected behavior
- The selection is reduced to `45`

# Actual behavior
- The selection is cleared and the cursor is moved behind the 3

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by abnerlee** [comment]
#1164
