### ISSUE TITLE
Bug in math colour rendering for dark background

### ISSUE THREAD

**Issue by Atcold** [typora/typora-issues#3012]
MathJax supports coloured math.

![Screenshot 2019-11-13 22 44 40](https://user-images.githubusercontent.com/2119355/68825516-5d4e4f00-0668-11ea-8a5e-b0aa833bfa02.png)

If a dark theme is used, this fails to display.

![Screenshot 2019-11-13 22 45 30](https://user-images.githubusercontent.com/2119355/68825528-693a1100-0668-11ea-90ae-bf3cb3fd1909.png)

Although the preview shows the colour correctly.

![Screenshot 2019-11-13 22 48 45](https://user-images.githubusercontent.com/2119355/68825541-72c37900-0668-11ea-8fc9-d9d25672fe82.png)

Here's a snippet of the code
```tex
Using $\color{red}{Q}Q$ we get
```

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by Atcold** [comment]
Yup, just saw it! Thanks!
