### ISSUE TITLE
The bug in mouse scrolling on mac OS

### ISSUE THREAD

**Issue by nonlinearthink** [typora/typora-issues#3013]
When I used typora, I found that when I wanted to move the mouse, sometimes it would suddenly return to the position before moving, but the touchpad could work well.

I used the MacBook pro and Magic Mouse. I've tried other mouse, but the problem is not solved.

I also use typora on other OS, such as Ubuntu and Windows, without such problems.

**Comment by abnerlee** [comment]
same with #2858?
