### ISSUE TITLE
Unable to insert a poem as footnote.

### ISSUE THREAD

**Issue by rp-karanth** [typora/typora-issues#3015]
When I am trying to insert a poem as footnote, where each line has two trailing spaces as line break second and consecutive lines is not included in footnote.

```{=markdown}
This is a sentence[^1]

[^1]: Roses are red  
Sea is blue
```
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Tcc25jX/footnote.png" alt="footnote" border="0"></a>

Should this be considered as a bug?

**Comment by gotjek** [comment]
I don't know if it's a bug but you can do this:

> This is a sentence[^1]
> [^1]: Roses are red<br>Sea is blue

:smile:

**Comment by abnerlee** [comment]
#2733
