### ISSUE TITLE
Link reference definitions require extra brackets

### ISSUE THREAD

**Issue by OhiraKyou** [typora/typora-issues#3016]
## Versions

Typora 0.9.79 (beta)
Windows 10 64-bit

## Description

[The CommonMark spec for link reference definitions](https://spec.commonmark.org/0.29/#link-reference-definitions) suggests that they should render as links when simply defined within brackets, like this: ```[Link]```.

However, Typora requires extra brackets for the implicit link, like this: ```[Link][]```.

### Source

```
[GitHub]

[GitHub]: https://github.com
```

### GitHub output

[GitHub]

[GitHub]: https://github.com

## Example 2

Changelogs in the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

Live example: https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by abnerlee** [comment]
#985
