### ISSUE TITLE
Maximized Window Hides Windows Taskbar

### ISSUE THREAD

**Issue by machajr1** [typora/typora-issues#3017]
I am using Windows 10 and have my taskbar set to auto-hide.
If you double click on Typora's title bar to maximize the window, it prevents the taskbar from reappearing when you move the mouse to the bottom of the screen. This is not an issue if you don't have the taskbar set to hide, and it doesn't happen if you maximize using the button on the top right.
I am on Typora 0.9.79.

**Comment by abnerlee** [comment]
Do you use seamless window style? similar to https://github.com/electron/electron/issues/9193?

**Comment by machajr1** [comment]
Yes

**Comment by abnerlee** [comment]
possibly already fixed by https://github.com/electron/electron/pull/9167
