### ISSUE TITLE
Disable html blocks ?

### ISSUE THREAD

**Issue by benjaminhoyle** [typora/typora-issues#3018]
I'd like to be able to write in html in Typora without the content automatically being clustered into an html block. This prevents the easy back and forth between a coded and rendered view that I appreciate when using markdown in Typora. Screenshot attached for clarity : can I turn off the dark grey block that automatically appears behind my pseudo-html code (which I'm using for compatibility with a custom script of mine).

Thanks,
Ben

![Capture d’écran 2019-11-14 à 20 10 43](https://user-images.githubusercontent.com/9941245/68889127-9811bf00-071c-11ea-986c-dbc48cd5010c.png)

**Comment by abnerlee** [comment]
Sorry, I cannot understand the requirement, I didn't see any "pseudo-html code" in your screenshot, they seems to be real html code. 

And about "Then this would be a heading", why it would be a heading?
