### ISSUE TITLE
Bullet indentations revert after save and close

### ISSUE THREAD

**Issue by novanleon** [typora/typora-issues#302]
I have a .md file that I created in Typora that contains a list of bullets. When I indent several of the bullets, save the document and reopen it, it reverts the indentation and normalizes all the bullets back to the way they were. If I open the file with a text editor after saving the changes, the indentations are present but somehow they get reverted by Typora when reopening the file.

I've attached screenshots as well as the .md file in question below:

[bullet_bug.zip](https://github.com/typora/typora-issues/files/490595/bullet_bug.zip)

**Comment by abnerlee** [comment]
@novanleon What's your typora version, and how you indent some parts of the list?

**Comment by novanleon** [comment]
This is in version 0.9.18 (beta).

I highlighted the bullets and pressed the Tab key on the keyboard. I also occasionally use Shift+Tab to un-indent bullets but I can't remember if I did that in this case or not.

**Comment by novanleon** [comment]
I don't know if it helps or not, but I was able to fix the issue by doing the following:

1. Open the file in Typora
2. View it in Source Code Mode
3. Delete all of the bullets and preceding spaces for each line item
4. Return to standard view mode
5. Add a bullet to the first line item by typing "*" and pressing space
6. Press the End > Delete > Enter to bullet the next line item
7. Repeat step 6 until all items have bullets
8. Highlight the bullets you want to indent and press Tab
9. Save and close Typora
10. Reopen the file in Typora and everything should save correctly this time

The only substantial change I noticed was the number of spaces before and after the bullet ("*"), but I'm not sure if this has anything to do with it or not. 

deleting all the bullets in question, adding a bullet to the first item in Typora, deleting

**Comment by abnerlee** [comment]
Tested, seems OK on new release
