### ISSUE TITLE
[Suggestion] macOS text transformations

### ISSUE THREAD

**Issue by vronizor** [typora/typora-issues#3020]
Hi all,

I was wondering if you would add a feature I’ve seen in some text editors on Mac. When I right-click on a selected text, I sometimes have the choice to transform the text, either all upper, all lower or capitalize. There are a bunch of other things too (substitutions etc), but Transformation is the one I use the most and think is really handy in many situations. I attached a screenshot from Macdown where the menu is available.

Are there any plans to make this available on Typora?

<img width="394" alt="Screen Shot 2019-10-25 at 17 27 48" src="https://user-images.githubusercontent.com/22742874/68960275-c39db380-07c7-11ea-8187-28007aa3c623.png">

Best

**Comment by abnerlee** [comment]
#1675
