### ISSUE TITLE
Possible a bug for auto-generate LaTex code

### ISSUE THREAD

**Issue by Dylan-H-Wang** [typora/typora-issues#3023]
For example, if I have written a line like `Set the learning rate w`, and I realise that `w` should be in inline LaTex code, so I double click `w` and press `$`, and this will automatically wrap `w` with `$`. 

If I change the content to `\mathbf{w}` and click other places, it cannot generate the code correctly (expect: math bold `w`, but get `\ma` with red colour). It only works if I continue to write something after the LaTex code.

By the way, I am using the Mac version

**Comment by abnerlee** [comment]
Seems fixed in the latest version.
