### ISSUE TITLE
Add a keyboard shortcut to insert check mark 

### ISSUE THREAD

**Issue by Donboscow** [typora/typora-issues#3025]
Please add a keyboard shortcut to insert checklist like Underscore (Ctrl + U)

**Comment by abnerlee** [comment]
http://support.typora.io/Shortcut-Keys/

**Comment by Donboscow** [comment]
there is no keyboard shortcut to insert checklist. @abnerlee

**Comment by abnerlee** [comment]
I mean you can mutually add shortcut following http://support.typora.io/Shortcut-Keys/

**Comment by Donboscow** [comment]
You should set Insert Checklist keyboard shortcut by default like Underscore and other important shortcut. @abnerlee

**Comment by Donboscow** [comment]
To create Underscore we have to press 6 buttons, so we need a keyboard shortcut to insert check mark by default @abnerlee
