### ISSUE TITLE
Context menu with keyboard command lacks information

### ISSUE THREAD

**Issue by jmreiche** [typora/typora-issues#3026]
When I use "Shift+F10" to use the keyboard shortcut for the context menu, then I do not have any options in the "Paragraph" or "Insert" menu - or they are very limited. If I right click with the mouse, then I have the full options.

I think this is related to Linux as I am on Ubuntu 18.04 and also use Typora on Windows and Mac where I have not experienced this bug. I have version 0.9.79(beta) of Typora. 

And just for good measure. Apart from this little annoyance I really love Typora and the simplistic design of it.

![Screenshot from 2019-11-18 20-31-14](https://user-images.githubusercontent.com/6480827/69083855-42eaeb80-0a43-11ea-89db-94dde565cad2.png)
![Screenshot from 2019-11-18 20-35-39](https://user-images.githubusercontent.com/6480827/69083856-42eaeb80-0a43-11ea-9c50-a241f9af43c5.png)

**Comment by abnerlee** [comment]
should be fixed
