### ISSUE TITLE
Typora in Kali as root

### ISSUE THREAD

**Issue by six2dez** [typora/typora-issues#3027]
Typora not start in a Kali as root in a fresh install, it gives an output asking to run Chromium with --no-sandbox flag. 

Actually running `typora --no-sandbox` works.

Issue related: 
https://github.com/typora/typora-issues/issues/2871

This path not exists `/usr/root/.config/Typora/typora.log`, even `/root/.config/Typora/typora.log` not exists until Typora is launched succesfully for first time.

Thanks.

**Comment by abnerlee** [comment]
duplicate with #2581
