### ISSUE TITLE
Performance issues when editing a large file

### ISSUE THREAD

**Issue by geeeeeeeeek** [typora/typora-issues#303]
I'm writing a long article with over 40k Chinese words for now. After I open the document, the experience is smooth and fine. However, every time after I add several thousand words, the insertion of characters begins to slow down and stuck for a delay of 500ms.

**Comment by Fogest** [comment]
I am having a problem with it being delayed on every keystroke on bigger files, but I am wondering if it only gets slow for you after you enter several words in a session and it slowly becomes slower, or if it starts right away being slow with a big document. Trying to see if this is the same issue as me or different.

**Comment by abnerlee** [comment]
#68

**Comment by fonoirs** [comment]
This issue also occurs on my mac pro
I used an earlier version to open the same file and the operation was not slow, but the later updated version was very slow and unusable.
<img width="564" alt="image" src="https://github.com/typora/typora-issues/assets/8768198/8272a984-22e1-43e1-9478-e99efa5549ec">
