### ISSUE TITLE
Cmd+S shows "The file “Documents” couldn’t be opened."

### ISSUE THREAD

**Issue by gtexpanse** [typora/typora-issues#3030]
OS version: macOs Catalina 10.15.1 (19B88)
Typora version: 0.9.9.29.2 (3650)
detailed steps to reproduce the bug:

1. Open Typora and type anything on the new window
2. Type cmd + s to try to save the content
3. Choose the default "Documents" dir that known as /Users/xxx/Documents
4. The alert message shows: "The file “Documents” couldn’t be opened."

I got this issue after upgrade my mac to Catalina 10.15.1, 
it would disappeared after rebooting but will reappear soon
Maybe this console log is helpful.
[errors_save_typora_file.log](https://github.com/typora/typora-issues/files/3867236/errors_save_typora_file.log)

**Comment by brandonserna** [comment]
I'm also running into this with opening previously created markdown files with Typora on Catalina 10.15.1

Subscribed 🍿

**Comment by abnerlee** [comment]
The log shows 
```
System Policy: deny(1) file-read-data /Users/xxxx/Library/Autosave Information/Unsaved Typora Document.md 
```

I didn't met this, but this may be fixed by "right click" Typora.app and click "open" from some posts in internet.
If not working, try https://forums.developer.apple.com/thread/123344, it looks similar

**Comment by brandonserna** [comment]
Thanks @abnerlee for the tips! I tried them but no luck. 

I did get it working again though. I went into System Preferences / Privacy then to the "**Files and Folders**" side tab (I think I checked the box for Typora Documents Folder) and restarted. This was driving me nuts. I feel like I tried everything that normally get apps working on Macs (right click open, sudo contents launch, updating)

OSX: 10.15.1 (19B88)
Typora: 0.9.9.29.2 (3650)

**Comment by wolfcon** [comment]
As I know, maybe a system bug. It will be fine after restarting OS.

**Comment by gtexpanse** [comment]
Hello everyone,thanks for the comments.

**Comment by gtexpanse** [comment]
Hello everyone, thanks for the comments.
I fixed this by adding "Full Disk Access" privacy for Typora again(remove then add again) and it worked well for me in the past week.

But it caused a new problem that I couldn’t delete any files by right-click or typora will be not responding.
It seems that this might be a system bug, so I will close this issue soon.
