### ISSUE TITLE
Is there a way to link a local md file in a Mermaid flowchart?

### ISSUE THREAD

**Issue by GAZ082** [typora/typora-issues#3033]
Is it?

Thanks!

**Comment by abnerlee** [comment]
```mermaid
graph TD; 
  A(Start)-->B(Do some stuff); 
  B(Take some rest)-->C(do more);
  click B "xxx.md" "This is a link"
```

**Comment by GAZ082** [comment]
Thank you @abnerlee but cant navigate to the link once created. I do CTRL + click on the link and nothing. If the file location is wrong Typora tells you so, but in this case nothing.

I tested the link outside the graphic and works. Check the gif.

![foo](https://user-images.githubusercontent.com/100194/69546843-40245500-0f73-11ea-8b56-336d50bfba36.gif)

**Comment by abnerlee** [comment]
Typora version?

**Comment by GAZ082** [comment]
> Typora version?

Windows  0.9.79

**Comment by abnerlee** [comment]
It's working in my test with latest version, so please try version 0.9.81
