### ISSUE TITLE
First character is dropped when using array environment in $$

### ISSUE THREAD

**Issue by Ayase-252** [typora/typora-issues#3034]
As you can see in the following picture, code 
```
$$
\begin{array}
ac
\end{array}
$$
```
is rendered to `c`. The first character `a` is dropped from live preview.

![image](https://user-images.githubusercontent.com/6264033/69304258-f4b03500-0c5a-11ea-89bb-0c440f66b2ac.png)

**Comment by abnerlee** [comment]
I tried on MathJax's demo and got the same result:

<img width="1440" alt="Screen Shot 2020-01-21 at 00 37 36" src="https://user-images.githubusercontent.com/1621242/72743271-4c7d0500-3be6-11ea-8f82-007214df1dd4.png">

----

I know nothing about LaTeX, but based on https://tex.stackexchange.com/questions/166273/begin-array-in-latex, your input is invalid, it should be

```
$$
\begin{array}{l}
ac
\end{array}
$$
```
