### ISSUE TITLE
Please add a feature?

### ISSUE THREAD

**Issue by Ripple-Peng** [typora/typora-issues#3035]
add tags to the file for easy searching, thank u.

**Comment by AlexPasternak** [comment]
@abnerlee closed without a comment, but I think he probably meant to say this is a duplicate of existing issue below. Vote and discuss tags there!

https://github.com/typora/typora-issues/issues/1393

**Comment by Ripple-Peng** [comment]
> @abnerlee closed without a comment, but I think he probably meant to say this is a duplicate of existing issue below. Vote and discuss tags there!
> 
> #1393

yes, this is what i want to say.
