### ISSUE TITLE
Flow does not currectly work?

### ISSUE THREAD

**Issue by Ircon** [typora/typora-issues#3040]
# Version Info
Windows 10 1909
Typora 0.9.79

# State
The code is follow.
```
st=>start: 开始
input=>operation: 输入
isOK=>condition: 输入是否合法
outError=>operation: 输出错误信息
cal=>operation: 计算10进制数字
outAns=>operation: 输出结果

st->input->isOK
isOK(no)->outError
isOK(yes)->cal

outError->input
cal->outAns->input

```

the result.
![res](https://s2.ax1x.com/2019/11/23/MHIkZT.png)

The line which is marked by two red arrows is not good position.

and if you add the code to this.

```
tran=> operation: 转换ASCII
```

and change this line.
**before**
```
cal->outAns->input
```
**after**
```
cal->tran->outAns->input
```
will show......
![show](https://s2.ax1x.com/2019/11/23/MHoutg.png)

the whole code.
```
st=>start: 开始
input=>operation: 输入
isOK=>condition: 输入是否合法
outError=>operation: 输出错误信息
cal=>operation: 计算10进制数字
outAns=>operation: 输出结果
tran=> operation: 转换ASCII
st->input->isOK
isOK(no)->outError
isOK(yes)->cal

outError->input
cal->tran->outAns->input
```

What happen?

**Comment by Ircon** [comment]
Oh,I forget something. I am not good at English.Maybe there are some error in this issue's context.

**Comment by abnerlee** [comment]
duplicate with #2599
caused by https://github.com/adrai/flowchart.js/issues/125

**Comment by Ircon** [comment]
> duplicate with #2599
> caused by [adrai/flowchart.js#125](https://github.com/adrai/flowchart.js/issues/125)

OK,thanks.
