### ISSUE TITLE
Improve Windows open screen UI

### ISSUE THREAD

**Issue by pjonix** [typora/typora-issues#3044]
The right part appears too quickly and the left is just the opposite.

and

The file page is a little too long.

**Comment by abnerlee** [comment]
duplicate with existing issues about open speed

**Comment by pjonix** [comment]
i am satisfied with the open speed, my suggestion is about dynamic effect.
The left part need non linear speed and cut the effect duration to 0.75x，while the right extending to 1.25-1.5x
just a recommendation.
Thx for reply!


------------------ Original ------------------
