### ISSUE TITLE
[feature request] hidden / collapsible notes

### ISSUE THREAD

**Issue by ksandvik** [typora/typora-issues#3049]
Feature request: an option to make notes that are not shown in the main text. This is useful for note taking when writing documents for internal use only.

Examples how to do this in existing markup using various HTML tricks: https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

If possible there's also an option to not export these notes when exporting/publishing Typora Markdown files.

**Comment by rkd-me** [comment]
HTML is already supported in Typora as well as this tag ([see support](https://support.typora.io/HTML/#html-entities))
However from what i have noticed, anything inside of `<details>` tag won't be rendered, markdown for example.

**Comment by ksandvik** [comment]
Hi, yes I was asking for an app menu entry to do it, anyway,  no rendering of the notes is desireable. --Kent

**Comment by abnerlee** [comment]
you mean #1581?

**Comment by ksandvik** [comment]
Yes, but driven by the UI and also hide the notes in the Markdown view itself, and show them on demand such as for editing.
