### ISSUE TITLE
Typora crashes when exporting PDF with some CJK fonts

### ISSUE THREAD

**Issue by kele14x** [typora/typora-issues#3050]
Typora crashes when exporting PDF if a custom CJK fonts is used in theme.

* OS: Windows 10 1709
* Typora: version 0.9.79 (beta)

Steps:
1. Custom theme using *Source Han Serif SC* fonts. The font is installed on windows.
 ```
body {
    font-family: "Source Han Serif SC",Arial,sans-serif;
}
```
2. Open a **.md** file with many Chinese words.
3. Export PDF by: **FIle -> Export -> PDF**
4. Typora says **exporting...** and will crash after some time.

![Capture](https://user-images.githubusercontent.com/4020067/69601161-39b6db80-104e-11ea-9a30-4cb30fee0b7a.PNG)

If I remove the custom fonts in css file, PDF export works well.

If the .md file does not contains many Chinese words (seems < 100). PDF export will work after waiting for some time.

**Comment by abnerlee** [comment]
How about latest version?

**Comment by kele14x** [comment]
Hi,

Thanks for your reply.

I've tested on latest windows release (typora (0.9.89)), and did not found this issue. The export to PDF works fast and normally. 

Great.
