### ISSUE TITLE
[feature request] Non-privilege installer or standalone portable package

### ISSUE THREAD

**Issue by giuliano0** [typora/typora-issues#3053]
It would be nice to have a less privileged install, or a portable tarball, if possible at all.

The reason behind it is that I often work on dumb terminals and I can easily set up cloud sync for my notes but not Typora, which is a bummer :(

**Comment by abnerlee** [comment]
duplicate

**Comment by PwrSrg** [comment]
I was using a **Portable BETA** for over a year and **LOVED it**!
But now that v1 is out, **it no longer works**. 😖

As soon as there is a **portable version**, you will get my money.
