### ISSUE TITLE
Did not export internal links correctly to PDF file

### ISSUE THREAD

**Issue by gioalhaz** [typora/typora-issues#3055]
Hello
If you set internal link like `[My title](#My-title)`, it works in Typora, but do not work in exported PDF file. In fact, there is link in PDF file but does not work.

Here is sample of MD file (sample.txt) and exported PDF (sample.pdf)
[samle.txt](https://github.com/typora/typora-issues/files/3901539/samle.txt)
[samle.pdf](https://github.com/typora/typora-issues/files/3901536/samle.pdf)

Typora version: 0.9.79(beta)
OS: Windows 10

**Comment by abnerlee** [comment]
duplicate
