### ISSUE TITLE
math is not aligned center when exporting HTML without style if using \tag{}

### ISSUE THREAD

**Issue by YohnWang** [typora/typora-issues#3056]
Hello,
when I write math like 
```
$$
e=\lim_{n \rightarrow \infty}(1+\frac{1}{n})^n \tag{1.2}
$$
```
if I export HTML without style[using SVG] ,then math is not aligned center when I open the HTML file.
And without `\tag`,the math is aligned.
I don't know how to solve this problem.
Thanks.

**Comment by yexuesong** [comment]
Why do you need HTML file? want to view formulas on the web?

**Comment by YohnWang** [comment]
I only want to build my blog supporting LATEX math,there are some conflicts between kramdown and typora,so first I tried to export HTML by typora ,but I found this problem.
Now I solve these conflicts with mathjax3 .

**Comment by yexuesong** [comment]
@YohnWang 

Here are some suggestions for you

I recommend using the rstudio math parser, which adjusts line wrapping based on mathjax2.7

`mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML`

- Method-1

What you need to do is wrap your mathematical formula in blackquote
```
# math block
`$$
mathematical formula
$$`

# inline math
`$mathematical formula$`
```
- Method-2
You can also use R Markdown, so you don't need to use backquotes.

Based on [this project](https://github.com/yihui/hugo-ivy), you can improve your blog. Google the relevant articles of [谢益辉](https://yihui.org/), you can get a more detailed introduction.

**If you just record it for yourself**, [坚果云](https://www.jianguoyun.com/) is a free and fast solution.

**Comment by abnerlee** [comment]
CSS is required to do alignment,  HTML without style won't include styles (CSSs).
