### ISSUE TITLE
Drag and Drop images stopped working with v0.9.9.30

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#3057]
macOS 10.15.1

### Steps to reproduce

1. Drag and Drop an image (png or jpg) into Typora MD document
2. image will **not** be imported nor the path to the image will be created

### Expected behavior

1. D&D an image into MD document
2. Typora asks me to import the file or just link the file
3. image will be imported into asset folder and link will be created in MD document 

### Workaround

1. Downgrade Typora to v0.9.9.29.2

**Comment by abnerlee** [comment]
fixed in 0.9.9.30.1
