### ISSUE TITLE
How to change the color of highlighted text

### ISSUE THREAD

**Issue by NewTyporaUser** [typora/typora-issues#3058]
I'm modifying an existing theme to my liking and I would like to know how to change the text's color when highlighted.

My highlight is a very light shade of gray, the background is very, very dark gray, and the text color is a very light shade of gray. When I highlight the text, the highlight and the text are the same color.

How do I make the text color the same color as the background color when highlighted?

**Comment by abnerlee** [comment]
#204
#1196
