### ISSUE TITLE
create pdf through pdflatex with user settings

### ISSUE THREAD

**Issue by rayblender** [typora/typora-issues#306]
Would it be possible to create a pdf through pandoc and pdflatex? 

In the pandoc extension to Microsoft VSCode it is possible to adapt the command to create the pdf via pandoc, for example: 
"--latex-engine=/usr/local/texlive/2016basic/bin/x86_64-darwin/xelatex -N  --variable mainfont=Verdana --variable verdana=nofligs --variable fontsize=10pt --variable papersize=A4 --variable geometry:margin=1in --variable documentclass=article". In MacVIM I use a very similar command: 

noremap <buffer> <Leader>p :! pandoc --latex-engine=/usr/local/texlive/2016basic/bin/x86_64-darwin/xelatex -N  --variable mainfont=Verdana --variable verdana=nofligs --variable fontsize=10pt --variable papersize=A4 --variable geometry:margin=1in --variable documentclass=article % -o  %<.pdf<CR>

Is it possible to access the command in Typora, just like adapting the CSS for export to html?

**Comment by abnerlee** [comment]
Currently no such implementation

But you could export to LaTeX, then compile to PDF using pandoc or LaTeX

**Comment by rayblender** [comment]
I think that the workaround that you propose does not yield the same result. When preparing the final printed product, an iteration between editor and pdf viewer is necessary, for example to add \newpage commands to improve placement of tables and figures. As The export to LaTeX from Typora can not be tweaked unless the relevant commands are always entered in the document, the result from the latex pdflatex conversion is not the same as the pandoc pdflatex conversion. I think that adding this feature could be very simple, just allow to spawn a batchfile or script from within Typora, nothing more. Typora in my view is one of the best markdown editors with a very nice interface. The missing feature however makes me use VS Code again ... nevertheless, congratulations with your application and thank you for offering it as a beta version. 

Yours sincerely, 

Raymond Deleu

Verstuurd vanaf mijn iPhone
