### ISSUE TITLE
In Global Search Other Language does not work except English. 

### ISSUE THREAD

**Issue by simpsonys** [typora/typora-issues#3060]
In Global Search , only English is working , I cannot find the other language txt . 

For example )
I have following text in my document. 
```
Sequenc Diagram . 
- 점선은 ack 다. 
```

Searching "ack" is working. 
Searching "점선" FAILs. 

![image](https://user-images.githubusercontent.com/30182923/69908153-51fc7100-1427-11ea-9aa8-291fb458bdc2.png)

![image](https://user-images.githubusercontent.com/30182923/69908157-5e80c980-1427-11ea-806f-3d9192c9036a.png)

Could you help us to fix this issue ? 

Thanks,

**Comment by abnerlee** [comment]
duplicate
