### ISSUE TITLE
Include option on Windows platform to be able to open files in the same window rather than new one

### ISSUE THREAD

**Issue by rkd-me** [typora/typora-issues#3062]
Hello and have a good day everyone!

Before I start, I want to point out that I am fully aware of #2757 #2736 #2002 and many more as well as infamous #1000, so before this issue gets trashed, please read it at least once!

As many people before me have mentioned, this feature is only available on Apple platform and on Windows we cannot do anything to alter the settings and avoid this behavior.

To understand my use case and struggle please see the screenshot below of how my "wiki/task" virtual desktop looks like:
![image](https://user-images.githubusercontent.com/12505857/69972455-8bada480-1519-11ea-898f-f6505a030410.png)

Now let's assume i want to open the new file via Windows Explorer or via Windows Search and it looks like this:
![image](https://user-images.githubusercontent.com/12505857/69973291-2eb2ee00-151b-11ea-9737-e6ca5ac79d56.png)

This action will open another Window of Typora on top of everything and all I want is to open it in the same Window instead, so i don't need to rearrange the Windows all over again 365 days a year. If such an option is not welcome in Settings, I beg you to at least add it via `config.json`. 
Just to clarify the look after i open any file, see below:
![image](https://user-images.githubusercontent.com/12505857/69973063-c106c200-151a-11ea-9124-1344839379e7.png)

I think this functionality is already in the app, because if we click on the File Tree Pane, it can save and change the file without making new Window.

Please consider it as this is extremely annoying.

**Comment by joyjones** [comment]
@rkd-me  What keyword should I use for this feature in "conf.user.json" please?

**Comment by rkd-me** [comment]
well it's totally up to you, but if i need to recommend one, i would go for `"keepSingleAppInstance": true` or something similar.

**Comment by abnerlee** [comment]
#1000
