### ISSUE TITLE
multiple mermaid class diagram is broken in Typora

### ISSUE THREAD

**Issue by EganSolo** [typora/typora-issues#3063]
See the attached files: an image displaying the bug, and the file where that bug is alive.
Typora version: 0.9.81 (beta)
OS: Windows 10 Pro
Version: 10.0.18362 Build 18362

[mermaid_bug_in_typora.zip](https://github.com/typora/typora-issues/files/3913133/mermaid_bug_in_typora.zip)

**Comment by abnerlee** [comment]
https://github.com/mermaid-js/mermaid/issues/1092

**Comment by abnerlee** [comment]
fixed in new release
