### ISSUE TITLE
[feature request]:  sidebar enhancements

### ISSUE THREAD

**Issue by nicodrome** [typora/typora-issues#3064]
HI,
I would love an equivalent of sidebar enhancements for sublime text, in typora.
At least being able to navigate in directories, and delete, and open etc....

**Comment by nicodrome** [comment]
...and no verification popup windows when renaming a file (there is a possibility to cancel in menu anyway)

**Comment by abnerlee** [comment]
The popup windows will not be popup after you select "don't show this again" in the alert.

Others part seems same with #1753?
