### ISSUE TITLE
[Feature request] Make some shotcut keys for starting a new line when in the middle of a line

### ISSUE THREAD

**Issue by shawyunz** [typora/typora-issues#3067]
Hi,
The reason I wanna do this is that many times I was just editing some words in the middle of the sentence, when I finished, I wonder a shotcut key, like Shift+Enter or Alt+Enter.

It will be working like press "End" and then press "Enter".
I was wondering if this is possible.

Cheers.

**Comment by rkd-me** [comment]
Just press <kbd>⬇</kbd> on the keyboard.

**Comment by shawyunz** [comment]
> Just press ⬇ on the keyboard.
Lol, good point, but not when the sentences were wrapped with multiple lines, and more importantly, press [down] will destroy the typing posture!

**Comment by rkd-me** [comment]
True, it only works for last line.
**AutoHotkey** or **Keyboard Software** is way to go i think..

**Comment by peetteerr** [comment]
**AutoHotkey** will handle it perfectly. I use Capslock+Entry to start a new when my caret is in the middle of a line.

**Comment by abnerlee** [comment]
merge into #3288
