### ISSUE TITLE
[BUG] Does not support comment of class diagrams for Mermaid v8.4?

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#3068]
OS: macOS 10.15.1
Typora: 0.9.9.30.1

The following code cannot be displayed unless the comment line is deleted：
```mermaid
classDiagram
%% This whole line is a comment classDiagram class Shape <<interface>>
class Shape{
    <<interface>>
    noOfVertices
    draw()
}
```

**Comment by abnerlee** [comment]
merge into #1661

`%% This whole line is a comment classDiagram class Shape` seems not valid from https://mermaidjs.github.io/mermaid-live-editor/
