### ISSUE TITLE
The apt-add-repository line for installing on linux doesn't work?

### ISSUE THREAD

**Issue by dflock** [typora/typora-issues#307]
From here, this line:

```
sudo add-apt-repository 'deb https://typora.io linux/'
```

works, but when you do `sudo apt-get update`, you get an error:

```
W: Conflicting distribution: https://typora.io linux/ InRelease (expected linux but got )
```

The `add-apt-repository` line creates this in the `/etc/apt/sources.list` file:

```
deb https://typora.io linux/
# deb-src https://typora.io linux/
```

This is on Ubuntu 14.04.

This is probably simple to fix - where is the `.deb` file? What's the direct download link?

**Comment by dflock** [comment]
OK, so the `.deb` is here: http://typora.io/linux/typora_0.9.19_amd64.deb

**Comment by abnerlee** [comment]
@dflock I have tested on Ubuntu 16.04, that should work.

So, what is your Linux distribution?

And if you use sudo add-apt-repository 'deb http://typora.io linux/' ? (http not https)

Besides, if only "warnings", no "errors", you still should be able to add the repo and install typora.

**Comment by dflock** [comment]
> This is on Ubuntu 14.04

You're correct about the warning vs error thing - I can actually install from the repo, but I get warnings every time apt updates/talks to that repo - either on the command line:

```
W: Conflicting distribution: http://typora.io linux/ InRelease (expected linux but got )
```

or in the GUI (synaptic in this case):

![screenshot_2016-09-28_12-39-36](https://cloud.githubusercontent.com/assets/47756/18929405/31037b96-8579-11e6-8970-9e022bf3bde9.png)

**Comment by brbsix** [comment]
I noticed this behavior also. I was reminded of it when I saw Typora on the HN homepage today. I ended up commenting on it [there](https://news.ycombinator.com/item?id=12648037).

In order to suppress the warning I changed the line to:

    deb https://typora.io/linux ./

**Comment by abnerlee** [comment]
#331

**Comment by abnerlee** [comment]
I tried #331, and seems no warning on my Ubuntu, so I will change that way.

**Comment by 73** [comment]
It is still on the website: https://typora.io/#linux

**Comment by hans** [comment]
Bump, I just ran into this too. (Ping @abnerlee ?)

**Comment by abnerlee** [comment]
@hans Hi, how about 
```
sudo add-apt-repository 'deb https://typora.io ./linux/'
```

or 

```
sudo add-apt-repository 'deb https://typora.io/linux ./'
```

**Comment by gitdeepr** [comment]
W: Conflicting distribution: https://typora.io ./linux/ InRelease (expected ./linux/ but got )
on ubuntu 18.04.

**Comment by gitdeepr** [comment]
Tried both of them none of them works..

**Comment by sebastianmacias** [comment]
I'm also having the same issue on ubuntu 18.04

W: Conflicting distribution: https://typora.io ./linux/ InRelease (expected ./linux/ but got )

**Comment by abnerlee** [comment]
@sebastianmacias Could following work?
```
deb https://typora.io/linux ./
```

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/706

**Comment by leo-wsy** [comment]
Having an issue on Kali Linux. Executed following command:
    # echo "deb https://typora.io/linux ./" > /etc/apt/source.list.d/typora.list ; apt-update ; apt install typora
and apt just threw me an 404 error... However if I changed the string into:
    "deb https://typora.io ./linux/"
everything works well except a warning arguing conflicting distribution. Anyone knows why? orz

**Comment by ericchenkai** [comment]
Try install software-properties-common to get add-apt-repository command work. 
`sudo apt install software-properties-common -y`
