### ISSUE TITLE
[BUG] Crash when nested urly braces in class diagram

### ISSUE THREAD

**Issue by homura** [typora/typora-issues#3071]
Typora version: 
0.9.9.30.1

Scenario:
I want to use the classDiagram to describe rust enum and then it crash

the rust enum like:
```rust
enum Person {
  Name {
    first_name: String,
    last_name: String
  }
}
```

And the mermaid code makes Typora crash 
```
```mermaid
classDiagram

class Person {
  Name {}
}
```
```

**Comment by abnerlee** [comment]
https://github.com/mermaid-js/mermaid/issues/1115

**Comment by abnerlee** [comment]
fixed in new release
