### ISSUE TITLE
French quotes have a bug when opening on a line for second time

### ISSUE THREAD

**Issue by gotjek** [typora/typora-issues#3072]
[Here is a video.](https://drive.google.com/file/d/1uQwfHou78GtKAaHxDLIKTrXor6dkq6Kr/view?usp=sharing)
:)

**Comment by tbowan** [comment]
Same bug here, opening quote is the " one, then write the content and when closing, got the french quote :'(. If I delete it (with backspace) and retype the quote key, I sometimes get the french opening quote (huh ?).

Reproduced with ubuntu 18.04 and windows 10 64bits.

**Comment by abnerlee** [comment]
should be fixed
