### ISSUE TITLE
[Feature Request] Enable manual removing of folder location in side bar

### ISSUE THREAD

**Issue by youngbeen** [typora/typora-issues#3073]
hello there,

In typora, we can toggle in recent locations(folders) in convenient. However, there's not a "delete" icon to remove a location. 
Please consider this request as it's a normal operation when user finds that a location is invalid someday and wants to remove it.

**Comment by brendaw** [comment]
I agree without, @youngbeen. It would be nice to have a "remove location" button to erase just one location from recent history.

By now, I'm dealing with this situation by using the menu option `File > Open Recent > Clear Items` to clear all history and then start reopening the right folders. I know this approach is not the optimal, but it gets the job done. Below has a print for this menu option.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/3674847/84441451-37932380-ac12-11ea-875f-703459c5cc7f.png">

I hope it can help you and others in someway until Typora put this feature in the beta.

**Comment by youngbeen** [comment]
> I agree without, @youngbeen. It would be nice to have a "remove location" button to erase just one location from recent history.
> 
> By now, I'm dealing with this situation by using the menu option `File > Open Recent > Clear Items` to clear all history and then start reopening the right folders. I know this approach is not the optimal, but it gets the job done. Below has a print for this menu option.
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/3674847/84441451-37932380-ac12-11ea-875f-703459c5cc7f.png">
> 
> I hope it can help you and others in someway until Typora put this feature in the beta.

Really appreciate! @brendaw . I am glad to see your guy's plan about this request, it will help a lot indeed :)
