### ISSUE TITLE
Extend Markdown Table of Contents generation to support [[_TOC_]] tag

### ISSUE THREAD

**Issue by CelSeb** [typora/typora-issues#3074]
Currently, it is possible to generate a Table of Contents in Markdown by adding the [TOC] tag but some wiki use [[_TOC_]] like AzDO https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops

**Comment by abnerlee** [comment]
part of #1202
