### ISSUE TITLE
Start a new line after question mark under some conditions

### ISSUE THREAD

**Issue by sktoozaki** [typora/typora-issues#3076]
Hi,
a new line starts after **question mark** both in editor and exported pdf file. It not happens after other symbols.
![image](https://user-images.githubusercontent.com/10172088/70293182-23153f00-181b-11ea-909c-28d45ced5d78.png)

**Comment by abnerlee** [comment]
This is the normal `word-wrap`. e.g:

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx?xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
