### ISSUE TITLE
[BUG]There is still a bug on compatibility with Sougo IME(a Chinese IME)

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3077]
**Operating system: Win 10 64 bit  | Typora version：0.9.81**

New release(.80 or .81) resolved the problem( of compatibility with Sougo IME) to a certain extent( it will not suddenly jump to a new line and become unable to edit). While unfortunately there are still some problems left.

- Sometime after I started a new line and typed some words, the text would be unable to edit and the caret would disappear and no matter how I clicked the words on the end of the new line, the caret wouldn't appear. 
- There is a method to deal with it by clicking the text above the new line, the caret will appear there, and by sending several {down} keystrokes, the caret may move to the new line.
- While this is not a complete solution since what may follow is that I can not instantly render inline math any more unless I press carriage return, and I can not even open math block unless I turn into code mode and type four dollar symbols.

I am sorry, I cannot find a way to reproduce this problem without using Sougo IME since this kind of problem never happen when I use English directly.

**Comment by abnerlee** [comment]
should be fixed above issues in new release.

Please reopen this if new issues with Sougo IME are found
