### ISSUE TITLE
Open Source Typora

### ISSUE THREAD

**Issue by Donboscow** [typora/typora-issues#3079]
Is there any plan to opensource typora?

**Comment by Wimmerer** [comment]
No it is proprietary and planned for eventual release as a paid product last I heard (quite a while back to be honest). There are already several issues discussing this: https://github.com/typora/typora-issues/issues/890

**Comment by AlexPasternak** [comment]
Duplicate of https://github.com/typora/typora-issues/issues/1645. Please search existing issues first before posting.

**Comment by Iron-E** [comment]
I wanted to double check Typora was libre after updating today and being prompted to purchase a license. I have paid for and donate to free software projects, and would love to purchase a \$15 license from you as I have [used Typora for years](https://github.com/Iron-E/nvim-typora), but I won't back proprietary software.

**Comment by candiedoperation** [comment]
Just found out https://github.com/marktext/marktext is an drop-in opensource replacement!
