### ISSUE TITLE
System wide key binding of Ctrl+,

### ISSUE THREAD

**Issue by kapsiR** [typora/typora-issues#3081]
I'm using Visual Studio next to Typora.
If I start Typora, i loose my favorite key mapping for `Ctrl`+`,`, because it's mapped to the Typora preferences. 

Typora v0.9.81
Expected behavior:
 - Do not map the key binding system wide, instead map it within Typora only

**Comment by chgc** [comment]
Facing the same issue here. `Ctr`l + `,` has meaning in Chinese IME. can make it only work in ENG IME mode?

**Comment by abnerlee** [comment]
Before our fix, please follow http://support.typora.io/Shortcut-Keys/#windows--linux to unregister `Ctrl + ,`

**Comment by kapsiR** [comment]
Thanks @abnerlee 
For others, here in a nutshell:

1. Open `File` ⇒ `Preference...` ⇒ `Open Advanced Settings` (Button at the bottom)
2. Add `"Preference...": ""` to the `keyBinding` section to disable `Ctrl`+`,`:
```
  // Custom key binding, which will override the default ones.
  "keyBinding": {
    // for example:
    // "Always on Top": "Ctrl+Shift+P"
    "Preference...": ""
  },
```
3. Close and save the file, restart Typora

**Comment by abnerlee** [comment]
fixed in new release
