### ISSUE TITLE
Text selection background-color will not go lighter than medium gray...

### ISSUE THREAD

**Issue by NewTyporaUser** [typora/typora-issues#3082]
Hi, AbnerLee, I posted before and your input was extremely helpful.

There is another problem. 

When I set the CSS selection pseudo-element "background(-color)" to #f1f1f1. It comes out to medium gray instead of the super-light gray #f1f1f1. 

I used this in my theme css:
::selection {
  background: #f1f1f1;
  color: #101010;
}

The selected text changes color correctly, the selection background color does not.

Here's what happens:
![Typora1_Capture](https://user-images.githubusercontent.com/58363259/70440889-36b1e700-1a61-11ea-9b39-010797e1ff52.PNG)

This is what it should look like (from TEDNpad):
![TEDNotepad_Capture](https://user-images.githubusercontent.com/58363259/70440971-64972b80-1a61-11ea-815a-471e55ce8cad.PNG)

**Comment by abnerlee** [comment]
You could debug CSS from `View` -> `Toggle DevTool` menu.  

Please check if there are other properties overwrite this, also, no properties like opacity, etc.
