### ISSUE TITLE
[feature request] Really need hotkey for switch lines, which is in every code editor plus Quiver.

### ISSUE THREAD

**Issue by FateRiddle** [typora/typora-issues#3083]
What I mean is when you have a list of things, it is very common to change their order, in Quiver(markdown mode) or vscode, the shortcut is Alt + arrow up(down).

This is essentially a hotkey that I find used most common and can't live without, I talked to a lot of coders, and they all feel the same. So please we need this to be implemented in Typora. I love Typora btw.

**Comment by abnerlee** [comment]
#1211
