### ISSUE TITLE
[feature request] Borderless title bar for windows

### ISSUE THREAD

**Issue by chimmhuang** [typora/typora-issues#3084]
This might have a better look . 😃

**Comment by abnerlee** [comment]
You could choose "Unibody" style in preferences panel, this is "Borderless title bar" mean?

**Comment by chimmhuang** [comment]
> You could choose "Unibody" style in preferences panel, this is "Borderless title bar" mean?

You can refer to the latest version of "Visual Studio Code", It integrates the top menu bar with the title bar

**Comment by chimmhuang** [comment]
If you think you can add this suggestion, please reopen this issue 🌞

**Comment by abnerlee** [comment]
Thanks for the suggestion. We don't have plans for this in short term, maybe after v1.0 it will be considered.
