### ISSUE TITLE
[BUG] macOS 10.15.1 Output .docx error

### ISSUE THREAD

**Issue by marcocpt** [typora/typora-issues#3085]
I have installed pandoc, but it still says: "Require Pandoc to Continue ..."
Console output: 
    find pandoc path
    May failed to decode bash output

**Comment by abnerlee** [comment]
duplicate with #2040

**Comment by marcocpt** [comment]
I have installed pandoc correctly
```
$ pandoc -v
pandoc 2.8.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
```
Since 10.15 replaced bash with zsh, I suspect it has something to do with this

**Comment by wangbh0722** [comment]
I've got the same problem!

**Comment by Keldos-Li** [comment]
Same problem!

Did you fix it? And how?
