### ISSUE TITLE
Get lousy code when copying Chinese character from PDF exported by Typora

### ISSUE THREAD

**Issue by yiranyyu** [typora/typora-issues#3086]
I tried to copy some Chinese characters from my PDF file, but get the following characters.

> ƻĸáĎŮáɇû

My Typora version is 0.9.9.30.1 (3794). My operating system is Catalina 10.15.1 and my system language is English.

**Comment by abnerlee** [comment]
Please provide sample *.md file and theme you use.

**Comment by yiranyyu** [comment]
> Please provide sample *.md file and theme you use.

My theme Whitey. sample.md and sample.pdf and my css files can be found at [here](https://drive.google.com/drive/folders/1pqeqImiPYl2oveXBL_AApInXeEZA9wQj?usp=sharing)

**Comment by abnerlee** [comment]
I can confirm this.

For current workaround, please use Github theme

**Comment by abnerlee** [comment]
Mostly fixed. remaining are put into #3290
