### ISSUE TITLE
Freeze when directory name has dot(.) or some character

### ISSUE THREAD

**Issue by devybh** [typora/typora-issues#3088]
hi guys. i'm Korean user.
i love this app, but sometimes it freeze by unknown reason.
today i got one of the reason.

i'm using windows 10 on Korean language.
when i open a markdown file, if the file's directory name has dot('.') or some Chinese character (like '件'), then typora has frozen.

i hope you fix this bug soon.
thank you for your serve.

**Comment by abnerlee** [comment]
Is it same with #3019 ? Does it happen after you use Native window style?
