### ISSUE TITLE
[Feature Request] Allow Sidebar Toggled on the Right Hand Side 

### ISSUE THREAD

**Issue by gigglegrig** [typora/typora-issues#3089]
### Request Detail:
Now Typora alway have it's sidebar, which used to show file tree, outline, etc, on the left hand side.

I think i'd be benefitial to many people who work with wide screen with multiple windows open.

The reason is that with multiple windows on the desktop, Left Hand Side toolbar only make sense if all users would have their typora window opened on the LHS.
But when the typora window is opened on the RHS, the toolbar occupies some unnecessary space.

**Comment by abnerlee** [comment]
relates #1243

**Comment by jgclark** [comment]
I second this request.
Incidentally this is a different suggestion from #1243.
