### ISSUE TITLE
Firefox slows down

### ISSUE THREAD

**Issue by wujastyk** [typora/typora-issues#3091]
Firefox 71 running on Linux Mint/Cinnamon 19.2.  Typora 0.9.81

This has been an issue for me for many months.  When I run Typora and Firefox at the same time, Firefox hangs, or almost hangs, for long periods.

**Comment by abnerlee** [comment]
#68

Will other app be slowed down when using Typora?

**Comment by wujastyk** [comment]
No, as far as I can see it's only Firefox.  I've tried other apps
(randomly), compiled and JDK, but Firefox alone seems to be affected.

**Comment by wujastyk** [comment]
This is still a major problem on my system. I have Firefox open all the time for work, and when I start Typora, Firefox hangs and has to be killed and restarted.  I do not see this behaviour with other apps.

I'm now using Firefox 72.0.1 (64-bit), Linux Mint 19.3 Cinnamon and the latest Typora.

For the present, I have to stop using Typora.  I love the program, so this is very regrettable for me.

If I can help with other diagnostics, let me know.
