### ISSUE TITLE
[Feature Request] Support Expandable Lists

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#3092]
It would be really cool if you could support expandable lists where you can see the functionality [here](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). I think you would just need to make Typora understand the `details` tag as well as the `summary` tag. I assume that these expandable lists would be allowed to be nested as well. Thank you for your hard work!

**Comment by abnerlee** [comment]
duplicate with #1581
