### ISSUE TITLE
[Feature Request] Close empty document on opening one from recent list in App Expose

### ISSUE THREAD

**Issue by woj-tek** [typora/typora-issues#3093]
Steps to reproduce:
* start Typora
* bring up App Expose (preview of all windows, it also lists recent documents)
* select one of the documents from the list at the bottom

What happens:
* The empty document stays open
* The opened document is opened, sometimes in the background

What should happen
* Only new document should be opened/has window

Interestingly enough, this works well when document is selected from the recent menu (File -> Recent)

**Comment by abnerlee** [comment]
should be fixed already.
