### ISSUE TITLE
French typography

### ISSUE THREAD

**Issue by Sensifer** [typora/typora-issues#3095]
Hi there, french writer here.
As a lot of french writer, we would love to use a markdown editor to write novel and long project. Is there a way to add special french typo? Would be absolutely awesome.
Thanks

**Comment by AlexPasternak** [comment]
Are you talking about customizing the dictionary? What platform are you on, because macOS has "Learn Spelling" via right-click and [Windows has it as well](https://www.windowscentral.com/how-edit-custom-spell-check-dictionary-windows-10)
