### ISSUE TITLE
[feature request] change default export path

### ISSUE THREAD

**Issue by CarloLucibello** [typora/typora-issues#3098]
Hi, thanks for this nice software. 

On my Linux system, when exporting a markdown to pdf (or to any other format), the path selector window opens to my home directory instead of the current directory or the previous export's directory. Therefore, each time I have to navigate to the right folder and this is mildly annoying when doing a lot of exports. It would be nice to have this fixed. 

Best,
Carlo

**Comment by abnerlee** [comment]
duplicate with #2650 relates #1614
