### ISSUE TITLE
[feature request] drag to arrange heading and subsequent text

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#3099]
# Why I ask?

We (ok, maybe only me) often re-arrange the text during writing.

# The question

So as the title says, is it possible to do following?

1. select only by heading, then drag it to a new position.
2. now, not only the heading but all the subsequent text and sub-heading are moved to the new position.

# What I thought

Of cause this is more reasonable if

1. we only select the heading in the outliner view
    or
2. the markdown file is rendered as a mind-map diagram, all heading is  treated as the node, then subsequent text is treated as note as [midmup](http://www.mindmup.com) does. Here we drag the node to arrange

**Comment by vassudanagunta** [comment]
Relates to #2375 and #2376.  Typora doesn't currently have any kind of document outline manipulation.

**Comment by abnerlee** [comment]
duplicate with #916
