### ISSUE TITLE
Hitting Cmd + W closes a window without prompt

### ISSUE THREAD

**Issue by pravin** [typora/typora-issues#310]
Closing a window on Mac doesn't prompt whether a modified file should be saved, but closes the window immediately.

Expected result should be a prompt asking "Save file without closing?" with a Yes/No/Cancel option.

**Comment by vassudanagunta** [comment]
Expected result should be consistent with Apple apps (e.g. TextEdit):

![close window save dialogue](https://cloud.githubusercontent.com/assets/2830093/19180493/2f5d052a-8c34-11e6-894c-9a1d211681c6.png)

**Comment by abnerlee** [comment]
You need to enable "Ask to keep changes when close documents" in system preference -> general.

But I do have some misunderstanding on this preference after I check Pages and TextEdit's behavior.

**Comment by abnerlee** [comment]
Fixed in new version
