### ISSUE TITLE
Can expose some options to use in Command ?

### ISSUE THREAD

**Issue by sidian123** [typora/typora-issues#3101]
I have a Blog Website which use and can open Typora to editor my post. The Command I use show below
```shell
typora.exe somefile.md
```
But, I can't pass other options to command, such as 
```shell
typora.exe --headId=23 somefile.md
```
> as shown , I want to open markdown file and locate to any headline.

So, Can you provide this function ?

**Comment by abnerlee** [comment]
duplicate
