### ISSUE TITLE
footnot does not render correctly on win 10 64bits

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#3102]
I am using typora 0.9.81(beta) on win 1064bits. For the following text
```
This is a sentence[^1]

[^1]: Roses are red. Sea is blue
```

the footnote part is expected to be rendered as 
```
1. Roses are red. Sea is blue
```

but in typora, it is actually rendered as
```
[^1]: Roses are red. Sea is blue
```

or is it a bug?

luckly, the exported DOCX and PDF has proper footnote

**Comment by abnerlee** [comment]
what "[^1]: Roses are red. Sea is blue" should be rendered depends on the ordered index of its occurrence , it can be

```
2. Roses are red. Sea is blue
```

even you input "1."

----

Typora will show the original text for easier editing purpose, and "[^" and "]:" will be greyed out
