### ISSUE TITLE
The feedback menu doesn't work

### ISSUE THREAD

**Issue by gongway** [typora/typora-issues#3106]
When clicked the 'feedback' menuitem in 'Help' menu, it opened an empty url in webbrowser.

**Comment by abnerlee** [comment]
Feedback will open a "mailto:hi@typora.io" link, which will open in your default mail client.

It may not working when webbrowser is your default mail client, but it does not do anything. You may refer https://www.timeatlas.com/email-links-chrome-gmail/ to fix your mail protocol handler if your default mail app is Chrome

**Comment by abnerlee** [comment]
relates #2185
