### ISSUE TITLE
Feature request: Terminal shortcut to start Typora

### ISSUE THREAD

**Issue by Zhenye-Na** [typora/typora-issues#3108]
Hey Dev Teams,

I am wondering if we consider whether creating a terminal launching shortcut for **mac OS** users.

Here is a screenshot from MacDown which integrate this kind of functionality in the `Preferences` panel.

<div align="center">
  <img src="https://user-images.githubusercontent.com/32248549/71301985-e25d1000-235a-11ea-9c10-fcb893c156df.png" width="60%">
</div>

***

Append this command to `.bash_profile`:

```sh
alias typora="open -a /Applications/Typora.app"
```

Thanks.

**Comment by abnerlee** [comment]
`open -a typora` is enough.

http://support.typora.io/Use-Typora-From-Shell-or-cmd/
