### ISSUE TITLE
customize underscores (_) behavior 

### ISSUE THREAD

**Issue by Alex-liutao** [typora/typora-issues#311]
can I customize underscores (_) behavior so the stuff between two underscores will not parse as emphasis ? 
I know GFM will ignores underscores in words, but I can't see there is any way to specify Typora parse content in GFM fashion.
and use  backslash to escape is not a very neat workaround to me.

**Comment by abnerlee** [comment]
I think typora follows GFM.

this_is_some_words will not be rendered as emphasis in Typora

**Comment by Alex-liutao** [comment]
you are right, I'm sorry about my mistake.
