### ISSUE TITLE
[Bug] The closing code fence can be shorter than the opening code fence

### ISSUE THREAD

**Issue by Purstal** [typora/typora-issues#3110]
Hello. 
The [CommonMark spec](https://spec.commonmark.org/0.29/#fenced-code-blocks) says:
> The closing code fence must be at least as long as the opening fence

But the current behavior is:
![2019-12-23 16 02 44](https://user-images.githubusercontent.com/8073600/71344695-386dc580-259e-11ea-96a0-64b876be757e.gif)
Which causes:
![2019-12-23 16 00 42](https://user-images.githubusercontent.com/8073600/71344712-43c0f100-259e-11ea-9ee5-63701c7ce195.gif)

OS version: macOS 10.14.4
Typora version: Beta 0.9.9.30.1

**Comment by abnerlee** [comment]
should be fixed
