### ISSUE TITLE
[Feature Request] Is it possible to write flow and mermaid with a split screen left and right instead of up and down?

### ISSUE THREAD

**Issue by 625781186** [typora/typora-issues#3111]
Is it possible to write `flow` and `mermaid` with a split screen left and right instead of up and down?
It is very inconvenient if the text is too long.

![image](https://user-images.githubusercontent.com/30521429/71354602-6c091980-25b7-11ea-8f1e-3761a1aa30f6.png)

![image](https://user-images.githubusercontent.com/30521429/71354914-5c3e0500-25b8-11ea-9885-d1fe6c90f65c.png)

**Comment by 625781186** [comment]
Solve:
![image](https://user-images.githubusercontent.com/30521429/71448823-817b7080-277c-11ea-908c-39ffe405c876.png)

![image](https://user-images.githubusercontent.com/30521429/71448825-89d3ab80-277c-11ea-9a2e-ed426cb161f2.png)

**Comment by 625781186** [comment]
hope add this css.

**Comment by abnerlee** [comment]
#4215 would cover this
