### ISSUE TITLE
Bug? Typora freezes when delete document from the document tree

### ISSUE THREAD

**Issue by loikein** [typora/typora-issues#3112]
So I opened a folder tree in Typora, and tried to delete from inside Typora using the right click-move to trash, but then it freezes every time so that I had to force quit. This may be a bug or it’s just my computer upset by the huge folder…

Would really appreciate any updates or workaround for this! (except for delete documents from Finder, of course 😅)

Typora version: 0.9.9.30.1 (3794)
macOS version: 10.15.2 (19C57)

**Comment by Enmming** [comment]
same problem 
Typora  Version 0.9.9.31.7 (4087)
mac Version 10.15.3 (19D76)

**Comment by Enmming** [comment]
> same problem
> Typora Version 0.9.9.31.7 (4087)
> mac Version 10.15.3 (19D76)

Did some test, seems like typora will freeze when folders are iCloud drive, but ok with my local folders

**Comment by loikein** [comment]
Thank you for your confirmation & test! My folder was in iCloud as well.

**Comment by tcitry** [comment]
same problem...
typora for mac 0.9.9.32.1 (4191)
macOS version 10.15.3 (19D76)

**Comment by tcitry** [comment]
> > same problem
> > Typora Version 0.9.9.31.7 (4087)
> > mac Version 10.15.3 (19D76)
> 
> Did some test, seems like typora will freeze when folders are iCloud drive, but ok with my local folders

Me too, As I test, it freeze in iCloud folders, and ok in local folders.

**Comment by tcitry** [comment]
I tried OneDrive, it is ok. so maybe is only has proble with iCloud.

I Just created a folder in my iCloud folder, and set it as the default folder open in typora. then create a file.md, type somethind and save. Then right-click and delete this file.md in file tree,  first time it successed, second and next every time, it freeze, so I have to force stop typora in Activity Monitor.

**Comment by abnerlee** [comment]
should be fixed. duplicate with #2912

**Comment by loikein** [comment]
Thank you, it is fixed indeed.
