### ISSUE TITLE
Feature request: show non-markdown files

### ISSUE THREAD

**Issue by aroberge** [typora/typora-issues#3114]
Good: I would find it very useful it Typora could show non-markdown files in the list of files. As an example, I'd like to keep small Python files examples, instead of inserting their content in a code block.

Better: It would be even better if Typora could load these files (in read only mode?) to view content as text.  

Best: It would be great if one could link these files and view them inside a document. Something like:
```py
file:hello.py
```
might be shown as
```py
print("Hello world!")
```

Absolute best: if one could also edit these files within Typora, not as code block but as original files.

**Comment by abnerlee** [comment]
duplicate with #1753
