### ISSUE TITLE
after updated version 0.9.82 file can not save

### ISSUE THREAD

**Issue by smileyby** [typora/typora-issues#3115]
![image](https://s2.ax1x.com/2019/12/26/lkDKrn.md.png)

**Comment by abnerlee** [comment]
Sorry for the trouble, this should be fixed, please try check upgrade again

**Comment by onevcat** [comment]
Same issue here after I upgraded to the latest 0.9.9.31.1 (3942) on macOS today. This alert shows sometimes when I try to save the file. (It is a bit annoying, although the file can be saved without a problem, and the alert can be dismissed by tapping the "try recovery" button.)

**Comment by abnerlee** [comment]
@onevcat Are you facing this in source code mode, if so try upgrade again may fix this

**Comment by onevcat** [comment]
Oh, I didn't notice that there is another update. 

Yes. It was in the source code mode.

It seems now saving is working fine in 0.9.9.31.2 (3946).
