### ISSUE TITLE
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/typora.io_linux_._InRelease

### ISSUE THREAD

**Issue by radium0729** [typora/typora-issues#3116]
When I do, sudo apt update, I get this error.

The content of my release file as follows.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Origin: typora.io
Label: Typora
Date: 三, 25 12月 2019 13:34:43 UTC

```
I have no idea why the release date will appear as Chinese characters. I tried to change these words to be Wed and Dec, but it will cause another signature error.

**Comment by RogueScholar** [comment]
I've been experiencing the same difficulties with the Typora repo when using apt for the last three days.

**Comment by Wangxiz** [comment]
I got the same warning when I use
```shell
$ sudo apt update
......
Hit:7 https://typora.io/linux ./ InRelease
......
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/typora.io_linux_._InRelease
```

**Comment by tbowan** [comment]
Same here (ubuntu 18.04)

**Comment by thwaller** [comment]
I am getting the same warning. I have also tried removing the PPA and re-adding, same issue. My specific message is: 
~~~
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/typora.io_linux_._InRelease
~~~

**Comment by abnerlee** [comment]
should be fixed, please try again.
