### ISSUE TITLE
Build for AARCH64

### ISSUE THREAD

**Issue by MagicCrazyMan** [typora/typora-issues#3117]
i want to run Typora on my single-board computer

**Comment by abnerlee** [comment]
It is out of scope for Typora, normally people does not write in single-board computer. Also, Typora for Linux / Windows is based on Electron, which requires enough resources to run a Chrome-like app.

**Comment by MagicCrazyMan** [comment]
i am sorry to reply so late, thanks a lot fot your reply ^^

**Comment by michalsc** [comment]
I would suggest reopenning it. Having an aarch64 port would open typora for e.g. machines such as PinebookPro - this one should be more than capable to run Electron.

**Comment by evantaylor** [comment]
I would love to run this software on my Pinebook Pro.  It's really a great fit. I use this lightweight laptop for python coding (Visual Studio Code, Jupyter Notebooks, etc.).  It can definitely handle Typora, and more aarch64 lightweight laptops are coming (Chromebooks, Linux laptops, etc.).
