### ISSUE TITLE
[Feature Request] Allows Custom quotes

### ISSUE THREAD

**Issue by tbowan** [typora/typora-issues#3118]
Again, thanks a lot for your work. Typora is a very usefull peace of software that I love to use.

My request... When I am writing french text, I often uses quotes. I've setup typora to uses "french quotes" instead of the default ones and (if you does not consider issue #3072), it works as expected.

My problem is that if I want to follow french typography, I must insert unbreakable spaces after the opening quote and before the closing one.

For now, I manually insert `&nbsp;`

I'd love to be able, in the setup screen of typora, to be able to set manually how an opening/closing quote is replaced on input. Let's say that if, along/instead of the selection I was able to enter the string I want to use, It would let me to type `«&nbsp;` and `&nbsp;»` for the opening and closing.

**Comment by abnerlee** [comment]
Just to confirm, you want following quote styles, right?

<img width="146" alt="Screen Shot 2019-12-26 at 23 04 23" src="https://user-images.githubusercontent.com/1621242/71480456-12f9e980-2834-11ea-9606-7ae8470e4087.png">

**Comment by tbowan** [comment]
Yes :-)

I was suggesting to allows to put whatever the user want because some would use the html code, other the `~` char (as in latex) or whatever. But your solution to just add a new possibility in the list answer my need.

thanks a lot :-)

**Comment by abnerlee** [comment]
The smart quotes will also affect the parsing rules, so `~` or html code will not be supported. To map """ to different texts, maybe use tools like TextExpander would be an option.

**Comment by AlexanderSavenkov** [comment]
Also, Russian-style pair of quotes are missing from the preference, they should be «external with some „internal“ quotes». External are there, but I miss the enclosed ones.
