### ISSUE TITLE
Can't delete charters on last line

### ISSUE THREAD

**Issue by februarysea** [typora/typora-issues#3119]
Typora version:0.9.9.31.1 (3942)
mac version: 10.15.1 (19B88)

Hello, I update new version today. Unfortunately I meet some problems. 
1. When I type on the last line it seems like the return key didn't work. 
2. On the last line I can't delete the last two characters and I also can't delete the last line.
3. If i'm in the second line from the bottom and use ⬇️ key, it will create a new line rather than go to the last line.

I try to restart Typora and these problems just disappear. 
Hope these information may help you guys.

**Comment by abnerlee** [comment]
seems duplicate with #1855
