### ISSUE TITLE
Is it open source?

### ISSUE THREAD

**Issue by gnacho** [typora/typora-issues#312]
I'm not sure about if this software is open source.
I'd like to contribute to translations if so.

**Comment by leewi9** [comment]
I assure you that it is not open source.

2016年9月29日 +0800 17:55 Nacho <notifications@github.com>，写道：

**Comment by dujuncheng** [comment]
I would like to support Typora, both financially and with contributions, it is  a great editor for MarkDown writer. Please consider open source it, I believe it will make this software better!

**Comment by jtoaha** [comment]
Yes, please consider open source. I was interested in possibly making a plug-in to make Typora even more useful than it is! Bummer.

**Comment by greatbody** [comment]
You can now purchase this software if you want to help it become better.
Otherwise, just use version below v1.0.
