### ISSUE TITLE
<img src = tag export problem

### ISSUE THREAD

**Issue by virendra531** [typora/typora-issues#3120]
```
<img src=".assets/image-20191224194137269.png" alt="image-20191224194137269" style="zoom:50%;" />
```

when i export this image is not showing.

**Comment by abnerlee** [comment]
Export to which format?

relates #2546

**Comment by virendra531** [comment]
> 
> 
> Export to which format?
> 
> relates #2546

pdf

**Comment by abnerlee** [comment]
So what's your Typora version, what is the path of the md file and the image file?

relates #3140

**Comment by virendra531** [comment]
Image are in `.assets` folder relative to the `.md` file
Typora Version `0.9.83(beta)`

**Comment by YalandHong** [comment]
Strangely, I encountered another problem related to `<img>` tag. Resized images are rendered but in the wrong size in the exported file.
First, I wrote some markdown text like this:
```markdown
# No resizing
![triangle1](./theBridge2.png)
# Resizing
<img src="./theBridge2.png" alt="triangle2" style="zoom:50%;" />
```
Typora cound correctly render the images and properly export to PDF.
![20200520122321](https://user-images.githubusercontent.com/52960068/82409566-a6141400-9aa0-11ea-87f1-2f32777a7ee9.png)

However, when I tried to export to Word file, the image kept its original size. Besides, the name of the image appeared at the bottom, which was not what I expected.
![image](https://user-images.githubusercontent.com/52960068/82409744-ef646380-9aa0-11ea-97fd-9de4e0332a32.png)

I use Typora 0.9.86 and Windows 1903 (OS 18362.720)
I don't know whether it is a bug or can be changed by settings.

**Comment by eliveikis** [comment]
Same problem - image won't show in exported pdf, shows fine within typora:

```html
<div width="5000" style="margin-bottom:30px"><img src="..\..\..\..\Marketing\Company Logo\logo.png" alt="drawing" style="position:absolute;bottom:-12px;" width="82"/><h1><span style="position:absolute;left:100px">Company Name</span></h1></div>
```

**Comment by abnerlee** [comment]
should be fixed
