### ISSUE TITLE
there is a problem when I export as image...

### ISSUE THREAD

**Issue by Qing1023** [typora/typora-issues#3121]
markdown:
![markdown](https://user-images.githubusercontent.com/40571736/71480606-ee524180-2834-11ea-8dc3-e3b0e33574e7.png)
export as image:
![image](https://user-images.githubusercontent.com/40571736/71480621-02963e80-2835-11ea-8e12-758822c05b48.png)
Please help me! Thanks.

**Comment by abnerlee** [comment]
duplicate with #2422
