### ISSUE TITLE
Incorrect unsaved status occurs.

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#3122]
In any saved file, when click a head with the switch "显示当前块元素的 Markdown 源码" on, it goes to an unsaved status. In fact there is not any change.

The same thing sometimes happens when going into a math block. In constrast, there's no such problem for inline math, emph, bold.

**Comment by UnnamedOrange** [comment]
0.9.83(Windows)

**Comment by abnerlee** [comment]
duplicate with #2354
