### ISSUE TITLE
Unable to select fonts in HTML with styles

### ISSUE THREAD

**Issue by zhjs** [typora/typora-issues#3123]
The fonts have not selected status in HTML exported by typora. furthermore, the codes can not rolling in horizontal when the horizontal scroll bar appears.

**Comment by abnerlee** [comment]
> The fonts have not selected status in HTML exported by typora.

HTML is plain text file which cannot embed fonts, for default themes, they will be convert to online font resources, for custom CSS, you could follow the same way as default theme, e.g:

```
@include-when-export url(https://fonts.loli.net/css?family=Open+Sans:400italic,700italic,700,400&subset=latin,latin-ext);
```

which will be converted to 
```css
@include url(https://fonts.loli.net/css?family=Open+Sans:400italic,700italic,700,400&subset=latin,latin-ext);
```

when export.

> furthermore, the codes can not rolling in horizontal when the horizontal scroll bar appears.

could you provide more details about this?
