### ISSUE TITLE
Strange behaviors when Undo for the first time after saving in the Source Mode

### ISSUE THREAD

**Issue by onevcat** [typora/typora-issues#3125]
## What

As title. I also attached a video for this problem. There are two patterns:

1. The text is hidden when performing "Undo" after saving

https://www.dropbox.com/s/i0l4gxdd4y5ikob/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62019-12-2823.25.46.mov?dl=0

2. The file is scrolled to top when performing "Undo" after saving 

https://www.dropbox.com/s/in84dj8fso6cz0p/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62019-12-2823.32.12.mov?dl=0

## Steps

1. Open a file.
2. Switch to the Source Mode.
3. Add some text anywhere.
4. Save the file with Command+S.
5. Perform an Undo with Command+Z.

## Expected

A standard Undo behavior. The added text should be reverted.

## Actual

All text is hidden or the file is scrolled to the top, as the videos above show.

## Environment

- MacBook Pro (15-inch, 2018)
- macOS 10.15.2 (19C57)
- Typora 0.9.9.31.2 (3946) (But I noticed this issue for quite a while, so it also happens in earlier versions.)

## Note

- The issue does not happen unless I do a save before undo. If I perform Undo directly without saving, everything works fine.
- It happens at a 100% rate.
- If I keep doing undo multiple times, it can recover to the normal state.
- In case you want the content in the video, it is here:  https://gist.github.com/onevcat/a7ef0d562d2693b084fc8358bc01f890

**Comment by abnerlee** [comment]
Which IME did you use? 

Able to reproduce it in latest version?

**Comment by onevcat** [comment]
I am using RIME (https://rime.im).

I tried again in the current version 0.9.9.31.4 (4005), it seems it now works fine without this problem.

But now, the saving action in Source Mode is extremely slow and make the UI unresponsive for about 2 or 3 seconds. It happens always for any size of the files. This problem only happens in Source Mode, and in Normal Mode everything is fine. Do you have any idea or what can I do for tracking this issue down?

Thanks!

**Comment by abnerlee** [comment]
> But now, the saving action in Source Mode is extremely slow and make the UI unresponsive for about 2 or 3 seconds. 

It's a bug, we will fix it in next version up.

**Comment by onevcat** [comment]
Both the original issue and the new save hanging are fixed! Thank you!
