### ISSUE TITLE
Strange graphical behavior of search and replace

### ISSUE THREAD

**Issue by SkittlePox** [typora/typora-issues#3126]
Strange graphical behavior of search and replace, see images:
<img width="811" alt="Screen Shot 2019-12-28 at 11 47 05 PM" src="https://user-images.githubusercontent.com/6373521/71552519-b847c580-29cc-11ea-82ca-2319be1cd634.png">
<img width="760" alt="Screen Shot 2019-12-28 at 11 46 47 PM" src="https://user-images.githubusercontent.com/6373521/71552520-b847c580-29cc-11ea-903f-5a98d9d3b4f6.png">
Typora version 0.9.9.28.5 (beta), MacOS Sierra 10.12.6

**Comment by abnerlee** [comment]
The latest version for 10.12 should be 0.9.9.26.7, newer version has already dropped the support for macOS <= 10.12. Could you try 0.9.9.26.x?

https://support.typora.io/Older-macOS-Support/
