### ISSUE TITLE
win10 bug: upper right corner control is invalid

### ISSUE THREAD

**Issue by AnimateXX** [typora/typora-issues#3127]
**[Chinese]:**  
**系统**：win10 home
**问题描述**：每次开机，前面几次打开Typora，均会出现下图所示的页面卡死问题，几个月前的版本貌似不会出现该问题。强制关闭后，再重新打开软件会正常，但有时也需要多次强制关闭再进入才能正常工作。
**问题频率**：始终（第一次打开该软件就会出现该问题）

**[English]:**   
**System**: win10 home
**Problem description**: Each time you turn on Typora the first few times, the page freezes as shown in the figure below. The version a few months ago does not seem to have this problem. After forcibly closing, reopening the software will be normal, but sometimes it will take several times to force close and enter again to work normally.
**Problem frequency**: Always (this problem occurs when you first open the software)
**bug picture**
![2019-12-29_221635](https://user-images.githubusercontent.com/39644421/71557983-0fab6b80-2a89-11ea-8de4-43b81049f098.png)

**Comment by abnerlee** [comment]
duplicate with #3019
