### ISSUE TITLE
[Feature Request] Foldable outline style list & notes

### ISSUE THREAD

**Issue by Donboscow** [typora/typora-issues#3129]
Typora already support all markdown syntax. If we get a new fold able outline style list & notes with custom signs (like other signs # for Heading level 1 ## for Heading level 2) it will be great. 

When we'll put custom sign then typora will show us the fold able **+** sign like in the picture. 

![](https://workflowy.com/media/i/team/team_wf_doc.png)

Then it'll be a more minimalist approach to write and maintain large notes/docs.

If you want to see it live just try out [workflowy.com](https://workflowy.com)

**Comment by abnerlee** [comment]
duplicate with #499
