### ISSUE TITLE
Typos in user interface 

### ISSUE THREAD

**Issue by nevillepark** [typora/typora-issues#313]
Just a few minor corrections.

"Preference" &rarr; "Preferences":

![2016-09-29 18_02_54-greenshot](https://cloud.githubusercontent.com/assets/16054979/18974169/6d56cb4c-866f-11e6-9a08-23234faf3193.png)

"Apperance" &rarr; "Appearance":

![2016-09-29 18_04_59-untitled - typora](https://cloud.githubusercontent.com/assets/16054979/18974168/6d538a36-866f-11e6-8322-7fa19f2346f8.png)

"Unodered list" &rarr; "Unordered list":

![2016-09-29 18_08_36-untitled - typora](https://cloud.githubusercontent.com/assets/16054979/18974237/dec2cc4a-866f-11e6-85fe-0bce5cc419a3.png)

"etc" &rarr; "etc." 

![2016-09-29 18_08_50-untitled - typora](https://cloud.githubusercontent.com/assets/16054979/18974238/dec6540a-866f-11e6-83d1-51e5aa68e273.png)

"More Topics.." &rarr; "More Topics&hellip;" (ellipsis instead of two periods)

![2016-09-29 18_07_58-untitled - typora](https://cloud.githubusercontent.com/assets/16054979/18974239/dec9dbc0-866f-11e6-84b4-f829c4e786f7.png)

**Comment by techtolentino** [comment]
The word `apperance` also shows up here: https://github.com/typora/wiki-website/blob/gh-pages/media/about-themes/Snip20160921_2.png

**Comment by abnerlee** [comment]
fixed typos in 0.9.21
