### ISSUE TITLE
hyperlink lost in exported pdf file 

### ISSUE THREAD

**Issue by luabish** [typora/typora-issues#3131]
hyperlink works fine when editing in typora,while after exporting markdown to pdf,the hyperlink can't be clicked, only showing underline.I added hyperlink using command+k
osx 10.15, Typora Beta 0.9.9.31.2 
[test.pdf](https://github.com/typora/typora-issues/files/4012009/test.pdf)

**Comment by AdaHsu** [comment]
I had the same problem,
OS: 10.15.2（19C57）
Typora: 0.9.9.31.3（3987）

**Comment by abnerlee** [comment]
@luabish @AdaHsu Also possible to provide a sample *.md file for this?

**Comment by luabish** [comment]
@abnerlee  just a simple hyperlink in a md file, like this:
`[link](https://www.baidu.com/)`

**Comment by atxsinn3r** [comment]
Same problem as of today. Version 0.9.9.31.4 (4005). See attachment for example:

[test.pdf](https://github.com/typora/typora-issues/files/4051771/test.pdf)

**Comment by AdaHsu** [comment]
PDF export function looks bad, it export a ugly pdf file.

sample.md:

```
>      <session-config>
>         <session-timeout>20</session-timeout>
>         <cookie-config>
>             ~~<secure>true</secure>~~
>         </cookie-config>
>		==<tracking-mode>COOKIE</tracking-mode>==
>     </session-config>
>
>     <error-page>
>        <error-code>404</error-code>
>        <location>/frontend/common/notfound.jsp</location>
>     </error-page>
```

shown on Typora:

<img width="907" alt="screenshoot" src="https://user-images.githubusercontent.com/924457/72313396-262b0700-36c6-11ea-8a11-398fb008dc5c.png">

but Export as PDF:
[sample.pdf](https://github.com/typora/typora-issues/files/4057278/sample.pdf)

**Comment by abnerlee** [comment]
should be fixed already

**Comment by thenewera-ru** [comment]
@abnerlee 
The same here. Typora version 1.0.5. Mac OS: 10.15.7.

Minimal example of markdown file to reproduce:
[test.md](https://github.com/typora/typora-issues/files/8006775/test.md)
