### ISSUE TITLE
[Bug] Can not open file in search results

### ISSUE THREAD

**Issue by HADB** [typora/typora-issues#3132]
It shows file not exist when I click any file in search results after upgraded to version 0.9.9.31.2 (3946).

<img width="910" alt="QQ20191231-174431@2x" src="https://user-images.githubusercontent.com/1836701/71617256-3be3fb00-2bf5-11ea-92be-5c8ace22cbef.png">

**Comment by simkimsia** [comment]
Same issue. Never happened before until the recent updates

**Comment by Gymchick** [comment]
same here

**Comment by lukakemperle** [comment]
> I went back to v0.9.9.30.1 which is fine.

Same problem here and I would like to downgrade, but can't find a repo with older versions: would you mind to point me in the right direction?

**Comment by jiangleo** [comment]
path normal path is right :/Users/jianghongwei/Documents/project/share/writings/mini-program/Cocos Creator 入门实践.md

path search path is wrong: /Users/jianghongwei/Documents/project/share//Users/jianghongwei/Documents/project/share/writings/mini-program/Cocos Creator 入门实践.md

**Comment by Gymchick** [comment]
> > I went back to v0.9.9.30.1 which is fine.
> 
> Same problem here and I would like to downgrade, but can't find a repo with older versions: would you mind to point me in the right direction?

here it is:  https://www.typora.io/dev_release.html

**Comment by lukakemperle** [comment]
> > > I went back to v0.9.9.30.1 which is fine.
> > 
> > 
> > Same problem here and I would like to downgrade, but can't find a repo with older versions: would you mind to point me in the right direction?
> 
> here it is: https://www.typora.io/dev_release.html

-Thank you, that's what I need 😉️

**Comment by abnerlee** [comment]
fixed in new release
