### ISSUE TITLE
Missing space in Markdown Reference

### ISSUE THREAD

**Issue by PrefixCoder** [typora/typora-issues#3135]
In section **Links**, there is a single space missing in between `http://example.com/` and `"Title"`:
``` markdown
This is [an example](http://example.com/"Title") inline link. (`<p>This is <a href="http://example.com/" title="Title">`)
```
which prevents "Title" from displaying when hovering over "an example".

**Comment by jgclark** [comment]
Have picked this up and will include in an upcoming pull request on the typora/wiki-website repo.

**Comment by abnerlee** [comment]
should be fixed in latest version
