### ISSUE TITLE
A bug that occurs when dealing with complex lists

### ISSUE THREAD

**Issue by 997293** [typora/typora-issues#3136]
Hi there,
嘿你好，

I use Typora to take notes, so I frequently use lists. However, when dealing with complex lists, the list can sometimes get messed up.
我用Typora做笔记，所以经常用到列表功能。但是制作复杂列表时，Typora经常会出现排版错乱。

For example, I frequently get wrongly structured lists similar to the one shown below. In this case, I have to spend tons of time to fix the list.
比如，我经常得到类似于下图中的错误排版。每次我都需要花很长时间来修复我的列表。

![image](https://user-images.githubusercontent.com/59507996/71768014-53044f00-2f4d-11ea-809f-252db29b7122.png)

To create such a buggy list, first, type in the list shown below in WYSIWYG mode.
为了重现这个bug，首先在所见即所得模式下输入以下列表。

![image](https://user-images.githubusercontent.com/59507996/71767951-b93ca200-2f4c-11ea-8326-0a73c83fe071.png)

Then, we get the source code shown below:
然后我们就得到以下源代码：

```
* Level 1

  * Level 2

    * ← Press Backspace here.
    * Level 3
      * Level 4

  * Level 2

    * Level 3

      Level 3
```

Copy the source code and paste it into a new Typora document. (or save and then rename the original document, which leads to the same result.)
复制这段源代码并粘贴到一个新建立的Typora文档里。（或者保存并重命名原来的文档，效果一样。）

Click on the position shown below:
点击图中光标所示位置：

![image](https://user-images.githubusercontent.com/59507996/71767974-fa34b680-2f4c-11ea-871b-cc98fa63682c.png)

Press Backspace key in WYSIWYG mode.
在所见即所得模式下按下退格键。

The output in WYSIWYG mode looks as expected for the moment:
所见即所得模式下的排版效果暂时和预想的一样：

![image](https://user-images.githubusercontent.com/59507996/71767983-0b7dc300-2f4d-11ea-92d1-cc55e8ef4711.png)

But the resulting source code is messed up.
但是源代码错乱了。

```
* Level 1

  * Level 2

    ← Press Backspace here.
  
    * Level 3
    * Level 4
  
* Level 2
  
  * Level 3
  
      Level 3
```

As a result, the output list can be immediately messed up if we, again, copy the source code and paste it into a new document (or save and then rename the current document, the results are the same):
结果是，所见即所得模式下的排版效果也会立刻发生错乱如果我们把以上源代码再次复制到新建立的文档（或者保存并重命名当前文档，效果一样）：

![image](https://user-images.githubusercontent.com/59507996/71768014-53044f00-2f4d-11ea-809f-252db29b7122.png)

I'm not sure if the procedure above is the only mechanism that results in messy lists. However, when taking notes, similar bugs could be pretty common in Typora.
我不确定以上方法是不是导致列表排版错乱的唯一机制，但是用Typora记笔记的时候这种情况真的非常常见。每次都需要用很长时间来修复。我非常喜欢Typora并且之后一定会付费订阅，但是这个bug真的很麻烦。

Thank you! 
感谢！期待你的答复！

**Comment by abnerlee** [comment]
should be fixed
