### ISSUE TITLE
Accented characters rendered incorrectly in Newsprint theme

### ISSUE THREAD

**Issue by luckytoilet** [typora/typora-issues#3138]
The font in the Newsprint theme renders certain accented characters in a weird way where accented characters are smaller, for example Vietnamese:

![image](https://user-images.githubusercontent.com/123435/71785066-458caa80-2fc9-11ea-98fc-40bec898dc45.png)

In the Github theme, it's rendered correctly:

![image](https://user-images.githubusercontent.com/123435/71785074-550bf380-2fc9-11ea-9ebd-85449c6455cc.png)

Typora version: 0.9.82. OS: Windows 10.

**Comment by abnerlee** [comment]
Could you paste the original text for us to test?

**Comment by luckytoilet** [comment]
The original text is:

Tất cả mọi người sinh ra đều được tự do và bình đẳng về nhân phẩm và quyền lợi. Mọi con người đều được tạo hóa ban cho lý trí và lương tâm và cần phải đối xử với nhau trong tình anh em.

Source: https://www.omniglot.com/writing/vietnamese.htm

**Comment by abnerlee** [comment]
@luckytoilet Sorry, which characters is different in Github and Newsprint theme? I cannot see any difference

**Comment by luckytoilet** [comment]
Almost every accented character is affected. The body of the letter should touch the two gray lines (right), but in the Newsprint theme the accented characters are too small (left).

![image](https://user-images.githubusercontent.com/123435/72683589-9f4fa300-3aa6-11ea-991f-5759b430ea39.png)

**Comment by abnerlee** [comment]
The font Newsprint use (https://fonts.google.com/specimen/PT+Serif) does not cover those characters.

Please use Github theme as a workaround.

This issue will be tracked in https://github.com/typora/typora-default-themes/issues/4
