### ISSUE TITLE
Syntax highlight cannot end correctly in source code mode

### ISSUE THREAD

**Issue by jivanpal** [typora/typora-issues#314]
When a code fence is used within a blockquote, and the document is viewed in Source Mode, the styling for code and non-code text switches in the remainder of the document, as in the following minimal example (ignore backslashes, `\`, which have been used here to prevent Github from styling them):

``````
Correctly styled non-code text
\```
Correctly styled code
\```

> Blockquote text
> ```
> Correctly styled code in blockquote
> ```

Incorrectly styled non-code text
\```
Incorrectly styled code
\```
``````

Below is a screenshot of this in action.
![typorabug](https://cloud.githubusercontent.com/assets/8561591/19010256/3ef38824-8775-11e6-9da7-fc1ec7337ebd.png)

This bug does **not** affect the rendering of the text in the regular, non-Source Mode.

**Comment by jivanpal** [comment]
The bug is not present if the offending code fence is not part of the blockquote:
![pic1](https://cloud.githubusercontent.com/assets/8561591/19010314/2137731c-8776-11e6-85bd-41a9cd4eac4d.png)

However, the bug returns when the offending code fence's lines have leading spaces:
![pic2](https://cloud.githubusercontent.com/assets/8561591/19010347/920c907c-8776-11e6-98ab-8d1799a5eb6a.png)

The bug again disappears if this offending code fence is preceded by some non-code text:
![pic3](https://cloud.githubusercontent.com/assets/8561591/19010339/7b46efc2-8776-11e6-8ada-2fa169bc92a7.png)

**Comment by Eisbrenner** [comment]
As noted in #1082 I had similar syntax highlighting errors with Vim, I fixed those for Vim by installing a [GitHub vim-markdown plugin](https://github.com/plasticboy/vim-markdown).
Now, how to tell Typora to use the same syntax highlighting? Or how to fix those highlighting errors otherwise?

Best,
Ezra

**Comment by abnerlee** [comment]
Improved in new release
