### ISSUE TITLE
[Bug?] image upload failed.

### ISSUE THREAD

**Issue by ZhaoYueNing** [typora/typora-issues#3140]
platform:mac version:0.9.9.31.3 (3987)
![image](https://user-images.githubusercontent.com/12961676/71809740-b0161700-30ab-11ea-9f7a-49cdd2b7d30f.png)
I use a relative path to save the image. When I reopen the file, it will prompt that the image fails to load. I need to manually adjust the URL to display it normally (change the URL but keep the content consistent).

**Comment by abnerlee** [comment]
What's the path of your md file and image file?

**Comment by abnerlee** [comment]
duplicate with #2780
