### ISSUE TITLE
sometimes open and can not do anything on Windows 10

### ISSUE THREAD

**Issue by hafeidejiangyou** [typora/typora-issues#3141]
Sometimes on windows 10 I open typora, it like this:
![image](https://user-images.githubusercontent.com/20509019/71814638-00937180-30b8-11ea-9cd5-85638aca078c.png)
and I can not edit or close but to kill it

typora version: 0.9.83(beta)

**Comment by abnerlee** [comment]
duplicate with #3019 ?
