### ISSUE TITLE
[Debian] Can't collapse a category

### ISSUE THREAD

**Issue by Bestulo** [typora/typora-issues#3142]
Screen recording upload:
https://i.imgur.com/aHaf20e.mp4

Debian 9
Typora 0.9.83 (beta)
All themes
Happens sometimes with some directories, not just this one.

**Comment by Coderdude112** [comment]
Are you using HTML?

**Comment by abnerlee** [comment]
Does this still happens in latest version?

**Comment by Coderdude112** [comment]
No, I believe the update after I posted that, it got fixed.
