### ISSUE TITLE
[Feature Request] View/Edit Mode Toggle

### ISSUE THREAD

**Issue by flamewave000** [typora/typora-issues#3144]
It would be really nice to have Typora have a View Mode where the user cannot edit anything but can select text, click links, and maybe? check/uncheck todos. This mode would also hide spelling errors and does not show the text caret. This would be a great mode to have as default when opening a file, and help Typora be more than just an editor but also more of a choice Markdown file viewer. The view could also place a small "Edit" button in the top left/right corner to enter the regular editor mode that we use now.

I typically write all of my professional documentation in Markdown, but I also love to use it for personal things like note writing and homebrew rules writing for board games. It would be really cool to switch to a view mode where I don't risk accidentally changing a document while reading it.

**Comment by flamewave000** [comment]
Also when clicking a link, you would not need to hold the Ctrl key to do so.

**Comment by vassudanagunta** [comment]
See #89, #710 and and the solution in #1317.

**Comment by abnerlee** [comment]
duplicate with #710

**Comment by lovelock** [comment]
https://github.com/tamlok/vnote has a more mature idea on what a Markdown editor should be like. But the implementation is buggy and not that delicacy as Typora.
