### ISSUE TITLE
[BUG] Inserting a checkbox in a new document fails

### ISSUE THREAD

**Issue by zeroskyx** [typora/typora-issues#3147]
**Repro:**

1. Open a new, empty Typora document
2. Enter the following: `- [ ] Text`

**Expected behavior:**

Typora correctly creates a checkbox:

- [ ] Text

**Actual behavior:**

Typora does not recognize the checkbox and renders it as text only:

- ［ ］ Text

**Note:**

Once you hit ENTER after writing the text, Typora continues to believe that you wanted to create a simple list; upon writing `[ ] Something` in this line works:

- ［ ］ Text
- [ ] Something

**Comment by abnerlee** [comment]
> Typora does not recognize the checkbox and renders it as text only:
>- ［ ］ Text

What's your Typora version? and possible to attach a screencast about this?

**Comment by zeroskyx** [comment]
I'm using Typora 0.9.83 on Ubuntu 19.10 64bit. I have attached a small video illustrating the problem.
[Repro.zip](https://github.com/typora/typora-issues/files/4045444/Repro.zip)

Please note that the issue does not occur every time but I haven't been able to figure out why sometimes it works and sometimes it doesn't (about 50:50). Let me know when you need additional input.

Keep up the amazing work!

**Comment by abnerlee** [comment]
Do you use any IME or non-English keyboard layout?

And does it only happens that the beginning of the document?

**Comment by zeroskyx** [comment]
It only ever happens with an empty document; afterwards it always works fine. I'm using a standard US keyboard.

**Comment by abnerlee** [comment]
Could you try latest version and see if it still happens? I am still unable to reproduce this.

**Comment by zeroskyx** [comment]
I haven't had this bug in a while now; maybe it's fixed -- thanks again!
