### ISSUE TITLE
[bug] Spell checker does not recognize non-breaking space "&nbsp;"

### ISSUE THREAD

**Issue by flamewave000** [typora/typora-issues#3148]
Typora's spell checker does not recognize the Non-Breaking Space character as a space. Any words concatenated via the `&nbsp;` character will be shown with a spell check error as it will think it is all one long word. But if you right click the word, it will view them separately.

Rendering with spelling error
![rendering with spelling error](https://user-images.githubusercontent.com/3588046/71910516-0896f400-3140-11ea-8807-73da4eebf9da.png)

Selecting the word
![selecting the word](https://user-images.githubusercontent.com/3588046/71910588-2cf2d080-3140-11ea-93cd-73c76cef7f4c.png)

The Markdown
![the markdown](https://user-images.githubusercontent.com/3588046/71910715-70e5d580-3140-11ea-9ea7-a7a997efe05a.png)

**Comment by abnerlee** [comment]
should be fixed

**Comment by flamewave000** [comment]
I have just checked in the latest version and can confirm it appears fixed. Thanks a bunch!
