### ISSUE TITLE
what markdown engine was typora use ?

### ISSUE THREAD

**Issue by yurenchen000** [typora/typora-issues#315]
the `markdown` and `syntax highlight` worked very well,
if it is possible,  I want to use them into my blog, in order to get the same looks .

( seems base on `atom` ?   found packages in  `resources` folder )

thanks

**Comment by balupton** [comment]
Looked into this today.

The popular Rich Text Editors are

- https://facebook.github.io/draft-js/
- http://prosemirror.net

However, asking about markdown on prosemirror gave this:

- https://discuss.prosemirror.net/t/show-markdown-syntax-in-editor/382?u=balupton

Which provides:

- https://codemirror.net/mode/markdown/
- https://codemirror.net/mode/gfm/index.html

So seems Typora is built off the gfm mode of codemirror - with a lot of enhancements.

**Comment by balupton** [comment]
Enquired about drafts support for markdown over at https://github.com/facebook/draft-js/issues/946

**Comment by balupton** [comment]
found slate today, http://slatejs.org/#/markdown-preview?_k=rnkc07 - it is pretty far along

**Comment by yurenchen000** [comment]
@balupton 
thanks, here is some engine i used

## MarkdownExtraExtended
https://michelf.ca/projects/php-markdown/
php implement
// at first i use this for several month, meet some error, update 2 times, turn to `Parsedown`

## Parsedown
http://parsedown.org
php implement, fast and stable, syntax like `GFM` and support some feature config
// i change to this half year, works fine, still in use 

## RedCloth 
Textile and Markdown Hybrid for Ruby
http://whytheluckystiff.net/ruby/redcloth/
ruby implement, syntax like `GFM`
// i found it from [redmine](http://www.redmine.org/) src, works fine

**Comment by abnerlee** [comment]
Typora use its own markdown engine, and try to be compatible with Github Flavored Markdown. 
You could use `GFM` for blogging. In most case, user can ignore those difference. 

Also see discussion in https://github.com/typora/typora-issues/issues/369

**Comment by wangz19** [comment]
I tried to type equations that work well in typora but not work in Github pages

**Comment by willin** [comment]
how does  typora  calc word count?
