### ISSUE TITLE
Window turns black

### ISSUE THREAD

**Issue by Nyasaki** [typora/typora-issues#3151]
> #### foobar
> 
> -   foobar
>     1.  foobar
>         -   foobar
>             1.  foobar
>             2.  foobar
>             3.  foobar
>                 -   foobar
>                     1.  foobar
>                     2.  <u>__foobar__</u>
>         -   foobar
>             1.  foobar
>             2.  foobar
>             3.  <u>__foobar__</u>
> ```
> These lines are displayed as one in typora
> ```
> ### foobar

upon removing the empty line (text in code block including the block itself) the application window turns black (or white, depending on the theme).
This issue couldnt be fixed by choosing a different theme.

Im using v. 0.9.81 - Windows 10

**Comment by abnerlee** [comment]
#3087
