### ISSUE TITLE
[Feature Retain] Disable using left key(or right key) to exit math block.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3154]
Typora version 0.9.83|OS Win 10

**Retain a feature from the previous version.**

- In the previous version, after editing the math block, when one wants to go out of the block, one has to press the down key to go out of the block rather than the right key, similarly, the up key rather than the left key. This is a humanized design which prevents one from accidentally going out of the block when falsely assuming there is a space is left at the end of the line. This feature is abolished in the recent version, can we restore this feature in future versions?

*This is just my suggestion. Feel free to comment.*

**Comment by abnerlee** [comment]
Math block is same like other paragraph: press right key at the end of paragraph, will goes to next paragraph. It is also the same logic in most text editors.
