### ISSUE TITLE
The font size in appearance setting and the exported PDF

### ISSUE THREAD

**Issue by qqlovekerry** [typora/typora-issues#3157]
Hi,
I am using Typora 0.9.83 (beta) on Ubuntu 18.04LTS.
I encountered  two problems:
1. My previous setting of the `Font Size` in Preferences->Appearance is 30 px in the `Customized` field. However, today when I tried to change the font size, it can not be changed to greater than 24 px any more. Does Typora add a restriction for this?
2. I found the font size of 30 px is big enough for me to read the contents on the screen, but it is too large when I tried to export them to a PDF file. It seems the font size in the exported PDF is determined by the font size set in the Preferences->Appearance, is that possible to set the font size separately for the PDF exported. I did not find an option for this but I think that would be useful.
Any help would be much appreciated!

**Comment by abnerlee** [comment]
> Does Typora add a restriction for this?

Yes, we have a restriction, but you could use "Zoom" feature on a larger screen.

> is that possible to set the font size separately for the PDF exported.

Please check http://support.typora.io/Add-Custom-CSS/ to add a custom CSS, and set font size use media query (`@print`)

**Comment by qqlovekerry** [comment]
Dear @abnerlee ,
Thank very much for your help!
The 'Zoom' feature is very useful. However, I found that the sidebar is zoomed in or out with the main text simultaneously. Is that possible to only zoom the main text? I feel it is better to fix size of the sidebar.

**Comment by abnerlee** [comment]
> I found the font size of 30 px is big enough for me to read the contents on the screen,

In this case, the control text should also be zoomed so that them can be readable on screen, right? In which case do you need to only zoom the main content?

**Comment by qqlovekerry** [comment]
> > I found the font size of 30 px is big enough for me to read the contents on the screen,
> 
> In this case, the control text should also be zoomed so that them can be readable on screen, right? In which case do you need to only zoom the main content?

Hi, Thanks for you reply! 
I think the sidebar is much less often read. Sometimes, the sidebar may also would be hidden. So, I feel maybe a fixed font size is good enough for the fonts in the sidebar.
And I do not quite understand why the font size of the main text is restricted in the new versions. I would prefer the previous version in which the font size can be set to larger ones.
