### ISSUE TITLE
[BUG] Sort by modification date incorrect in file tree view

### ISSUE THREAD

**Issue by luckytoilet** [typora/typora-issues#3158]
Sometimes, when editing multiple markdown files in the same directory, the file tree view shows files in the wrong order.

Scenario: I just saved 1.md. List view correctly shows 1.md first:

<img src="https://user-images.githubusercontent.com/123435/72182836-5028b480-33ba-11ea-9b14-15111b1a2b93.png" width=300px />

But file tree view (incorrectly) shows 2.md first:

<img src="https://user-images.githubusercontent.com/123435/72182847-5880ef80-33ba-11ea-832c-407ff077edcd.png" width=300px />

Steps to reproduce:

1. Turn sort mode to sort by modification date (descending).
2. Open a folder with two markdown files, say 1.md and 2.md. At this point both views have the same order.
3. Modify 2.md and save it.
4. Now, the list view correctly has 2.md first. But the file tree view incorrectly has 1.md first.

Typora version: 0.9.83

**Comment by abnerlee** [comment]
On which OS?

**Comment by luckytoilet** [comment]
Windows 10.

**Comment by pranaykrishen** [comment]
File list does not refresh sorting upon adding a new file or folder. 

Requires Typora app to be restarted, or to toggle sort button in bottom menu.

Typora Version: 0.9.9.32.1 (4191) 
OS: MacOS 10.15.4.

**Comment by abnerlee** [comment]
should be fixed
