### ISSUE TITLE
Main window unresponsive, static cursor with no ability to type, menus not opening and exiting possible only by killing the process

### ISSUE THREAD

**Issue by NixSar** [typora/typora-issues#3159]
Starting Typora results in the main window being unresponsive, a static cursor with no ability to type, menus not opening and exiting only possible by killing the process. I am running Windows 10 Pro 1909 on AMD Vega64 GPU with the newest Radeon drivers (20.1.1) - the issue was present on previous drivers going back about two months.

Looks like this:
![Typora Windows](https://user-images.githubusercontent.com/10364664/72193206-af151a80-3408-11ea-9cf2-ba989c935e48.gif)

It looks to me like an Electron-GPU issue because after starting and killing Typora several times it corrupts the system and causes similar issues in more apps, but it only occurs and starts with Typora and I have plenty of other Electron apps that I use regularly. Chrome also works normally. 

I have tried un/reinstalling, cleaning all Typora folders, and disabling GPU rendering in conf file. No luck.

[typora.log](https://github.com/typora/typora-issues/files/4048622/typora.log)

**Comment by abnerlee** [comment]
Could you try click shift+F12, and see if there are any error log in console?

And would you try start Typora use the default theme (by backup them remove the theme folder), does that work?

**Comment by NixSar** [comment]
Dev Tools window won't open. I've deleted the theme folder and the problem remains. The odd thing is that if I leave Typora open for some minutes (I haven't counted, but it's more than 5) the situation will resolve itself.

**Comment by abnerlee** [comment]
We updated Electron version, please check if it happens again.

**Comment by NixSar** [comment]
> 
> 
> We updated Electron version, please check if it happens again.

It is indeed finally fixed after many, many months 👍  Thanks!
