### ISSUE TITLE
Mathjax numbering (and add refresh menu option and keyboard shortcut)

### ISSUE THREAD

**Issue by kadmonj** [typora/typora-issues#316]
There seem to be a problem with the MathJax engine, which causes a problem in labeling equations (I know there is a previous issue, but I did not find answers)

One possible workaround, as offered by @truefalsename [issue 48](https://github.com/typora/typora-issues/issues/48) is to change '/Applications/Typora.app/Contents/Resources/TypeMark/lib/MathJax-2.6.1/jax/input/TeX/config.js' and change `none` to `all` in the following: 
`equationNumbers:{autoNumber:"none",formatNumber:function(a){return a},formatTag:function(a){return"("+a+")"}`

However, each time an equation is edited it receives a new number. 

In lack of a more *elegant* solution (which perhaps someone could offer), it would be useful to be able to reload the content of the document, and forcing MathJax to reset and re-typeset all the equation without closing and reopening the file. Preferably with a keyboard shortcut and remembering the last view/cursor location.

**Comment by abnerlee** [comment]
> In lack of a more elegant solution (which perhaps someone could offer)

I think we'd better support this from Typora side

**Comment by truefalsename** [comment]
that would be awesome.

**Comment by Horta** [comment]
Typora is a great software and I just started using it for writing academic papers. Would be to able to cross-refer to equation labels.

Is there any donation system associated with Typora to implement specific features? I would be willing to pay for that specific feature to be implemented.

**Comment by abnerlee** [comment]
Add option for Mathjax auto numbering in preference panel.

And the command to refresh all math is available from menu bar

**Comment by GandalfSaxe** [comment]
\ref links to math equations doesn't work when I clock them in exported PDF or HTML, but only in-editor. Any suggestions?

More specifically:
HTML: Equation number is formatted as link, but doesn't take me to the equation.
PDF: Equation number isn't even formatted as a link.

**Comment by Ic3fr0g** [comment]
@gandalfsaxe Works with /eqref.

**Comment by AngieC96** [comment]
To me it doesn't work either \eqref. In the pdf there is no link to the equation, only its number. In Latex the link is generated automatically just by using \label and \eqref.

**Comment by thenewera-ru** [comment]
I've just tested this feature and have to say: it works **_only_** on Windows. On any OS X system - it produces the correct reference (e.g. number of equation) but the reference is **_NOT clickable_**.

Minimal example to reproduce:

```
\begin{equation}\label{eq:r}\tag{3}
R=R(q, C) \mapsto \{d_1, \cdots, d_k | d_j \in C\}
\end{equation}
```

```
When trying to refer to it later on via:
Later on when perfoming evaluation of $R$ $\ref{eq:r}$
```

On OS X produce correct label but NOT clickable. on Windows 10 works perfect.

P.S> @abnerlee any ideas?
