### ISSUE TITLE
[BUG]Sort by file name incorrect in file tree view

### ISSUE THREAD

**Issue by tangyulex** [typora/typora-issues#3161]
version: 0.9.9.31.4 (4005)       mac os

#### file names:
```
1.xxx    2.xxx    ...    10.xxx
```

#### expect:
```
1.xxx
2.xxx
...
10.xxx
```

#### but result:
```
1.xxx
10.xxx
2.xxx
...
```

**Comment by abnerlee** [comment]
This is expected for sort by alphabet order, you could use sort by natural order to sort by natural language.
