### ISSUE TITLE
Tab characters prevent arrow up/down from working in some cases

### ISSUE THREAD

**Issue by saveriomiroddi** [typora/typora-issues#3162]
In some cases, tab characters causes a change of how arrow keys (and End) work. I don't know if that's intentional or not, however, a side effect is that the up/down arrows can stop working.

See the following source snippet:

```markdown
test
`myvar="${var:-value}"`				#
`myvar="${var:-value}"`                #
```

Hex dump:

```
00000000  74 65 73 74 0a 60 6d 79  76 61 72 3d 22 24 7b 76  |test.`myvar="${v|
00000010  61 72 3a 2d 76 61 6c 75  65 7d 22 60 09 09 09 09  |ar:-value}"`....|
00000020  23 0a 60 6d 79 76 61 72  3d 22 24 7b 76 61 72 3a  |#.`myvar="${var:|
00000030  2d 76 61 6c 75 65 7d 22  60 20 20 20 20 20 20 20  |-value}"`       |
00000040  20 20 20 20 20 20 20 20  20 23                    |         #|
```

When positioning the cursor on the blank space in the second line, the up/down array keys (and End) change behavior, and they go to the next `#` character instead. A side effect is that when the cursor key is on the `#` character, such keys don't have any effect.

Although this could be intentional behavior, if the third line is removed from the text above, the arrows works as they regularly do (End instead has still the strange behavior), so it could be a bug.

Playing a little bit with this type of text, I've found other oddities, for example, End works as it normally does if the cursor is immediately after the `myvar="${var:-value}"` text (on the second line)., however, up/down arrow behave oddly:

- from the second line (immediately after the text), Down goes to the `#` of the third line
- from the third line (immediately after the text), Up goes 4 characters (1 tab) to the right of the text on the second line.

**Comment by abnerlee** [comment]
relates #1164

**Comment by abnerlee** [comment]
should be fixed in latest version
