### ISSUE TITLE
[FEATURE REQUEST] Inline footnotes

### ISSUE THREAD

**Issue by DutchPete** [typora/typora-issues#3163]
The footnote status in Typora is, IMO, below par. There is no automatic numbering, so if a new note is put between existing ones the whole numbering sequence is broken. Furthermore, the pop-up when hovering over a number is nice but does not allow one to jump to the actual note, and from the note there is no return arrow.

My request is to support inline footnotes, which means the user does not have to fiddle with numbering, figuring out which is the right sequenced number. It is important to have automatic numbering and a return arrow.

**Comment by jgclark** [comment]
Seconded. I was surprised not to have inline footnotes available. 
Any footnote support is an extension beyond basic Markdown, so why not support both kinds? I standardised years ago on inline footnotes for the same reasons @DutchPete gives.

**Comment by abnerlee** [comment]
#1571

**Comment by abnerlee** [comment]
> Any footnote support is an extension beyond basic Markdown, so why not support both kinds? 

Footnote is a non-standard markdown syntax, but it is still supported by many other Markdown editors / engines, while inline footnotes is not supported by others.

**Comment by DutchPete** [comment]
@abnerlee : so =, what does your last comment mean? Will inline footnotes be added as a new feature or have you abandoned it?

**Comment by blackveen** [comment]
@DutchPete @jgclark @abnerlee This will help you [https://github.com/typora/typora-issues/issues/1571](url) It's a feature, but not live implemented
