### ISSUE TITLE
Scrolldown limit positioning is inconsistent

### ISSUE THREAD

**Issue by saveriomiroddi** [typora/typora-issues#3164]
The positioning of the text respect to the scrolldown limit is inconsistent.

To reproduce:

- fill a few pages with text
- when writing the last line, the last line is very close to the window limit, and it's not possible to scroll down with arrow/page down.
- using the mouse wheel, it's still possible to scroll down a bit, leaving some space between the last line and the window limit; alternatively, scrolling all the way up with Page up, then all the way down with Page down, some space is also left

While this seems trivial, when one uses the full width of the screen, the bottom left `</> Exit Source Code Mode` label partially covers the last line of code; if some space is left instead, there is no superposition.

**Comment by abnerlee** [comment]
Which theme did you use, and possible to provide a sample file or screenshot about this (you could also email to hi@typora.io)?

**Comment by saveriomiroddi** [comment]
So! I'm using the Night theme, modified with 1800px width.

I couldn't reproduce the superposition of the `</> Exit Source Code Mode` with the code, however, I did reproduce the inconsitency between (arrow down/page down) and (mouse scroll down) - see video.

[desktop_recording.zip](https://github.com/typora/typora-issues/files/4150443/desktop_recording.zip)

**Comment by abnerlee** [comment]
The up / down arrow are used for move cursors up / down, not for moving viewport.
