### ISSUE TITLE
Show heading level on github theme

### ISSUE THREAD

**Issue by spirosag** [typora/typora-issues#3165]
Hi,
Would it be possible to show the heading level in the github theme?
Some themes show a dim small icon with the heading level number on the left of the header either when the caret is on the exact line or permanently.

I find it really helpful because as it is in the github theme there is no way of knowing the heading level   (that I know of)

**Comment by spirosag** [comment]
Apparently it does for headings >2.  I was just using a lot of # 2 headings in my last document and thought it was a design change 🤦‍♂️

**Comment by spirosag** [comment]
Apparently it does for headings >2.  I was just using a lot of # 2 headings in my last document and thought it was a design change 🤦‍♂️

**Comment by hsandt** [comment]
This is still an issue to distinguish H1 and H2, how can I customize this? While it does seem obvious by looking at them, I use a theme variant where the different of size between H1 and H2 is not vey big, so it is not obvious.
