### ISSUE TITLE
Text after <br> dropped in mermaid diagrams.

### ISSUE THREAD

**Issue by rowdenw** [typora/typora-issues#3166]
![Screen Shot 2020-01-12 at 17 25 14](https://user-images.githubusercontent.com/12215507/72229073-8ef86f00-3560-11ea-9750-ba548be20c8b.png)

**Comment by abnerlee** [comment]
put into #1661

**Comment by 1263414627** [comment]
The same problem is occured in Typora of 0.9.86

**Comment by 1263414627** [comment]
The same problem  occures in Typora of 0.9.86
