### ISSUE TITLE
Content changed after upgrading

### ISSUE THREAD

**Issue by lingxiankong** [typora/typora-issues#3168]
The same thing happened **several times** for me, especially after upgrading Typora or changing the theme. e.g.  I have a markdown file with the content https://paste.pics/3beaed4b20b8b0cfbcbabf756778a6bb, after upgrading or changing the theme, it may probably be changed to https://paste.pics/56f8a45ca1b83252dc9b450d56c58022.

Hope it could be fixed soon. Thanks for all your hard work, Typora is amazing!

**Comment by lingxiankong** [comment]
Another example I met just now

![image](https://user-images.githubusercontent.com/4410121/72290740-c840f400-36b2-11ea-9899-e98b1f57a44a.png)

changed to:

![image](https://user-images.githubusercontent.com/4410121/72290780-d858d380-36b2-11ea-8df5-e2a4d7d1230b.png)

**Comment by abnerlee** [comment]
I'm not able to reproduce this from your screenshot.

So what's your Typora version, and possible to provide a sample file?  And could you check if the content is modified in source code mode? The screenshot is not Typora.
