### ISSUE TITLE
Can't uncheck "updates automatically"

### ISSUE THREAD

**Issue by fresheneesz** [typora/typora-issues#3169]
On the latest version of Typora, I can't uncheck "Check updates automatically". Clicking does nothing - it remains checked. Please fix

**Comment by abnerlee** [comment]
Should be fixed already

**Comment by vertesy** [comment]
Every 3rd time I open Typora it wants to update. I would also like to un-check updates, but I don't even see this option any more in preferences. Was it removed? (OS X, latest version)

<img width="704" alt="image" src="https://user-images.githubusercontent.com/5101911/102349916-649b0700-3fa4-11eb-8718-38765895ee7c.png">

@abnerlee could you please point me to the solution? Probably I overlooked it.

**Comment by abnerlee** [comment]
The option is shown on the update panel (triggered by Typora -> Check for Updates when there is updates).

But yes, @vertesy we'd better put this into preferences panel as well.

**Comment by abnerlee** [comment]
added in macOS as well
