### ISSUE TITLE
Footnotes compilation

### ISSUE THREAD

**Issue by mlinchitstest** [typora/typora-issues#317]
In Typora, if you type:

```
Sentence. [^footnote1]
Sentence [^footnote1]
Sentence [^footnote2]
Notes:
[^footnote1]: footnote 1
[^footnote2]: footnote 2

```

it will compile with _three_ lines of footnotes. instead I feel it should compile with just _two_ lines and `footnote1` should have _two backlinks after it_ (this is how Stackedit does it). To me that seems cleaner. However, I can see why some might prefer 3 footnotes—perhaps add an optional setting?

**Comment by abnerlee** [comment]
Actually I am considering changing to two backlinks in future updates.

**Comment by abnerlee** [comment]
Fixed already
