### ISSUE TITLE
Copy images into typora,the image url should be the directory which contains the markdown file.

### ISSUE THREAD

**Issue by assmdx** [typora/typora-issues#3171]
When I copy image into typora from clipboard , I got this:
![image](https://user-images.githubusercontent.com/19722693/72251796-57a9c100-3639-11ea-8434-a99ea2f51f6c.png)
However, I hope it be copyed into the directory which contains my markdown file.
So that ,I can directly commit my changes and upload them.

**Comment by abnerlee** [comment]
http://support.typora.io/Images/#use-relative-path
