### ISSUE TITLE
Home/End buttons not working correctly in Source Code Mode

### ISSUE THREAD

**Issue by fresheneesz** [typora/typora-issues#3173]
Home/End buttons were fixed so they correctly went to the beginning/end of the line (and not the beginning of the paragraph) in issue #2693. However, this is still a bug in Source Code Mode.

**Comment by jgclark** [comment]
From looking at your linked issue, I guess this is a Windows-specific request?

On macOS 10.14.6 I get the other behaviour to you: Home/End does BOL/EOL in Source Code Mode, but _not_ in whatever the opposite mode is called.

**Comment by fresheneesz** [comment]
Oh hm. Yes I'm using it on windows 10.

**Comment by christophcemper** [comment]
Yes, I confirm, same problem here in Source Code mode

**Comment by abnerlee** [comment]
Will fix this, but it will still remain a little bug caused by https://github.com/codemirror/CodeMirror/issues/4841

**Comment by abnerlee** [comment]
should be fixed already
