### ISSUE TITLE
[ bug ] Inline math doesn't work -> (Version 0.9.9.31.4 (4005))

### ISSUE THREAD

**Issue by Wunderdog** [typora/typora-issues#3174]
Inline math stopped working with latest update.

Both $<Math>$ doesn't format and ^M result in error beep.

Math block still works with Alt + Cmd + B and $$ + [Enter]

Typora Version 0.9.9.31.4 (4005)

**Comment by abnerlee** [comment]
Please search for existing duplicated issues first

**Comment by abnerlee** [comment]
#2508

**Comment by abnerlee** [comment]
#1507

**Comment by abnerlee** [comment]
#1915

**Comment by abnerlee** [comment]
#1738

**Comment by abnerlee** [comment]
#1510
#1506
#1497
