### ISSUE TITLE
source code mode h1 and h2 small line height cuts off text when selected

### ISSUE THREAD

**Issue by olets** [typora/typora-issues#3177]
In source code mode, the bottom of `#` and `##` text can be cut off when more than one line is selected.

![image](https://user-images.githubusercontent.com/3282350/72558362-83fb5280-3870-11ea-96e4-eee9123316d5.png)

Line height comparison between modes:

rendered|source
---|---
![image](https://user-images.githubusercontent.com/3282350/72558391-937a9b80-3870-11ea-804a-3809f55bf917.png)|![image](https://user-images.githubusercontent.com/3282350/72558472-ba38d200-3870-11ea-91a3-8068f26af335.png)

This is on v0.9.9.31.4

**Comment by abnerlee** [comment]
should be fixed already
