### ISSUE TITLE
Two dollar figures in one line triggers LaTeX unintentionally

### ISSUE THREAD

**Issue by divbzero** [typora/typora-issues#3178]
For example the following Markdown:

```markdown
Please donate $50 to $100 to the non-profit organization.
```

Becomes rendered as:
> Please donate **50to** 100 to the non-profit organization.

Where the bolded section is rendered in LaTeX.

**Comment by divbzero** [comment]
Workaround is adding a backslash (`\`) before each dollar sign:
```markdown
Please donate \$50 to \$100 to the non-profit organization.
```

**Comment by abnerlee** [comment]
We you either use `\` to escape `$`, or disable inline math in preferences panel -> Markdown section

**Comment by abnerlee** [comment]
#1298
