### ISSUE TITLE
Linux repository has no Release file

### ISSUE THREAD

**Issue by marinovdeyan** [typora/typora-issues#3179]
When I update my repositories, bash complains that the Typora repo has no release file.

When I go on the link of the repo, there's a "Not found" text that appears on the webpage.

This is what the terminal spits out:
```
E: The repository 'https://typora.io/linux ./ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by abnerlee** [comment]
I can download the release from 'https://typora.io/linux ./ Release' (which is https://typora.io/linux/ Release)

You could try remove it from apt sources, then do:

```
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
# add Typora's repository
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update
# install typora
sudo apt-get install typora
```

Or download the binary http://support.typora.io/Typora-on-Linux/#other-distributions
