### ISSUE TITLE
Image not found persists if image is created

### ISSUE THREAD

**Issue by swehrwein** [typora/typora-issues#3180]
I'm on Mac OS 10.13.6 using Typora 0.9.9.31.4 (4005).

Steps to reproduce:
1. Enter the markdown code for an embedded image, e.g., `![](img.png)`, where `img.png` does not refer to an existing file.
2. Bring `img.png` into existence.

Expected behavior: the image correctly embeds and shows up inline.
Observed behavior: the icon still indicates the image is not found. This persists even if you re-type the image embed code.
Workaround: closing and re-opening the file causes the image to show up correctly.

**Comment by abnerlee** [comment]
should be fixed in latest version
