### ISSUE TITLE
【HELP! 求救！！】为什么H1-H6的标题带标点符号的都失效了？！

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#3182]
发现新版的TYPORA中，如果H1-H6的标题中带标点符号（如。、，！？《》空格）之类的，导出HTML后，对应的锚点链接的name中的内容，都会将这些标签符号给清了（其中空格变成了减号），所以页的链接都失效。

这是BUG还是故意的设计？

**Comment by abnerlee** [comment]
Markdown and CommonMark does not have a spec for anchor link. 

Based on the test, GFM works in this way: https://stackoverflow.com/a/38507669 (but not documented)

So, there's just no rules to follow.

**Comment by MadMaxChow** [comment]
但在 Typora 编辑时，按下 Command 后再点击这些页面内链时是可以正常跳转的，如果是要遵从规范，那是不是 Typora 在导出 HTML 时可以自动转换一下，要不然这个体验太不好了

**Comment by abnerlee** [comment]
导出 HTML 之后也是点击之后可以正常跳转啊

**Comment by MadMaxChow** [comment]
> 导出 HTML 之后也是点击之后可以正常跳转啊

测试过是不行，例如：

```
这是页内链接[测试](#目标：目录1)

……

# 目标：目录1

```

「目录：目录1」的章节在导出HTML后会变成`<a name="目标目录1">`
你意思是写内链的时候就要写成`[测试](#目标目录1)`？

**Comment by abnerlee** [comment]
> 你意思是写内链的时候就要写成[测试](#目标目录1)？

对

> 测试过是不行，例如：

这个是bug了，我们会修一下

**Comment by MadMaxChow** [comment]
> > 你意思是写内链的时候就要写成[测试](#%E7%9B%AE%E6%A0%87%E7%9B%AE%E5%BD%951)？
> 
> 对
> 
> > 测试过是不行，例如：
> 
> 这个是bug了，我们会修一下

好的，因为对于大多数普通用户来说，是不会考虑，也不太可能注意这么多细节的，尽量用最自然直观的方式来支持，对于用户输入了不符合规范的，Typora 自动识别并转换就好了。
目前我在 VLOOK 的中写了个小补丁来临时解决 Typora 的这个BUG
```javascript
        // 清理内链 href 中「无效」的符号，这个是目前 Typora 导出 HTML 的 BUG 引起的
        let invalidHrefSymbol = " `~!@#$%^&*()_+=[]{}\\|;:'\",.<>?/！…（【】「」：“”，。《》？〈〉『』";
        $("a[href^='#']").each(function () {
            $(this).attr("href", $(this).attr("href").toLowerCase());
            for (let i = 0; i < invalidHrefSymbol.length; i++) {
                let href = $(this).attr("href"),
                    ch = invalidHrefSymbol.substr(i, 1);
                if ($(this).attr("href").indexOf(ch) > -1) {
                    let newStr = (i == 0) ? "-" : "";
                    $(this).attr("href", "#" + href.substring(1, href.length).replaceAll(ch, newStr));
                }
            }
        });
```
