### ISSUE TITLE
Empty line after HTML Block not kept

### ISSUE THREAD

**Issue by asdf2014** [typora/typora-issues#3185]
Before upgrading, Typora will do nothing
```markdown
<center>xxx</center>

### title
```

After upgrading, Typora will delete the blank line. It is unnecessary and will cause 
[Hexo](https://github.com/hexojs/hexo) cannot parse...
```markdown
<center>xxx</center>
### title
```

**Comment by abnerlee** [comment]
should be fixed in latest version
