### ISSUE TITLE
Selection bug when bold and italics combined

### ISSUE THREAD

**Issue by aron-hoogeveen** [typora/typora-issues#3186]
OS version: Windows 10 (version 1809)
Typora version: 0.9.83 (beta)

When using the shortcut `ctrl+b`  and `ctrl+i` together on an selected piece of text and then redoing the italics with `ctrl+i` results in an leftover asterisk (*) in the text.

Example: 
text: example
select text and press `ctrl+b`:  **example**
press `ctrl+i`: ***example*** (note the selection of the third asterisk)
press `ctrl+i`: **example*** (note the leftover asterisk due to the selection in the previous step

**Comment by jgclark** [comment]
FYI macOS 10.14.6 doesn't share the same leftover asterisk at the end, but it does have the same incorrect selection as in step 3 of 4 in the OP.

**Comment by abnerlee** [comment]
#1571

**Comment by abnerlee** [comment]
should be fixed
