### ISSUE TITLE
Odd navigation with Cmd-Left/Right on macOS

### ISSUE THREAD

**Issue by jgclark** [typora/typora-issues#3187]
Pressing ⌘← or ⌘→ in text on a mac should move to start and end of line, as displayed in the viewport. The actual behaviour does this most of the time, but not always.
It's fine on a text line that all fits within the viewport.
But use a text line that wraps over several lines in the viewport, and then it doesn't always work: 
1. Start at the beginning of the line. Press ⌘→ and it jumps to the end of the viewport line, correctly.
2. Type ⌘→ again and it jumps to the end of the **next** viewport line. This is non-standard; in other text editors it stays put.
3. Type ⌘← and it goes to the beginning of the viewport line, correctly.
4. Type ⌘← and it stays put, which is expected.

(Using macOS 10.14.6 with Typora 0.9.9.31.4 (4005) beta. Tried on several themes to same effect.)

Edited to add: I've now tried it on macOS 10.15.2 with same Typora build, and on the **same file** with various themes I get slightly different results:

- ⌘← and ⌘→ now behave as expected in the middle of a long line split over several viewport lines
- but both ⌘← and ⌘→ now go to previous/next line accordingly when moving backward or forward _into a list item or header element_. It does _not_ show this in standard paragraph text.

**Comment by abnerlee** [comment]
should be fixed in latest version
