### ISSUE TITLE
Some HTML problem

### ISSUE THREAD

**Issue by Erimus-Koo** [typora/typora-issues#3189]
# Add space between bold text
In Asian language, there's no space between words. like:
```
正文**重要**正文
```
The normal text is close to the strong one. So I want to add some space between the strong part, make the sentence more readable. Looks like
```
正文 **重要** 正文
```
And some part need attention:
- If the strong part in the middle of a line, add margin on both side of it.
- If the line is starts with a strong part, just add right margin of the strong.

I tried to write a theme.css to do the feature.

# Theme
I've noticed that inline element are wrap with span, I checked the export html, e.g.
```
<li><strong><span>重要</span></strong><span>正文</span>
<strong><span>重要</span></strong><span>正文</span></li>
```
the css is:
```
strong+span {
    color: blue!important;
    margin-left: 10px;
}

span+strong {
    color: green!important;
    margin-left: 10px;
}

p>*:first-child {
    margin-left: 0 !important;
}
```
But this display with some error, because of typora use a `\n` to explain the new line, not `<br>`. So the "strong" of second line, is next to "span". If a `<br>` between them, the selector will work and display will be fine. But a `\n` between them, the selector not works. So the second line's first strong, will has a "margin-left".

And the html look not so good, not new line (I means `\n`) between `li` or `p`, but used to split inline element. A paragraph split in different lines, and different paragraph in one line. That's looks not intuitive enough. 

# Preview is not equal the export html
I add above css in export html, and replace the `\n` with `br`, it looks fine.  
But in typora real time preview, the same css looks different. May the structure of html is different with the output one.

---

# My question
1. Can I have a option, to use `br` instead of `\n` in html?
2. Preview looks different with output html, is that any way to see the source code of real time preview? I want to write the css theme of it.

**Comment by abnerlee** [comment]
http://support.typora.io/Line-Break/ This explains how single line break is rendered in editing mode and after export.

> Can I have a option, to use br instead of \n in html?

To make a "<br>" you could either input a "<br>" or input two whitespace then press return. This is a spec of Markdown.

> Preview looks different with output html, is that any way to see the source code of real time preview? I want to write the css theme of it.

Yes, see http://support.typora.io/Add-Custom-CSS/#debug-css
