### ISSUE TITLE
The Horizontal Bar can cause you to lose your cursor

### ISSUE THREAD

**Issue by SeanPrendi** [typora/typora-issues#3190]
OS Version: Mac OS Catalina 10.15.2
Typora Version: 0.9.9.31.4 (4005)
Steps to reproduce:
Insert a Horizontal Bar
Place cursor in the text above or below the horizontal bar
Move the cursor onto the horizontal bar (up/down)
Move off the horizontal bar with the up or down arrow, and the cursor will be gone

Note: If you move left or right before moving up or down, the cursor appears to be fine.

**Comment by abnerlee** [comment]
should be fixed in latest version
