### ISSUE TITLE
Provides auto-completion

### ISSUE THREAD

**Issue by PotoTan** [typora/typora-issues#3191]
Hope to provide auto-completion for closed symbols

The symbols "", <>, (), ｛｝, [], etc. are often closed. If Typora can provide an auto-completion option, it is turned on by default. When the user enters (auto-completion), this 
Greatly improve user experience

Autocompletion is common in IDEs and some editors (notepad ++)

**Comment by justnealpatel** [comment]
Are you saying to have an option to disable auto-completion? As far as I know, auto-completion works great in Typora and covers all the cases you've mentioned except for `<>`.

**Comment by abnerlee** [comment]
Please turn it on in preferences panel.
