### ISSUE TITLE
The extra blank line after merge two list

### ISSUE THREAD

**Issue by JiapengLi** [typora/typora-issues#3193]
Platform: Windows
Version: 0.9.83(beta) 64bits.

Normally I edit under "render" mode. And sometimes may split list incautiously. After I remove the blank line to merge two list. An extra blank line still kept in the source code. This makes typora unfriendly to other editors. Not sure if this is an issue, or just design on purpose. 

To reproduce:

Format:
![image](https://user-images.githubusercontent.com/3773923/72864029-9e6c7a80-3d0d-11ea-87aa-14ba4b4b1b42.png)

Source code:
```
- 1
- 2
- 3



- a
- b
- c
```

Try to merge the two list in one under editor mode:

![image](https://user-images.githubusercontent.com/3773923/72864089-e095bc00-3d0d-11ea-986b-2a0840468711.png)

Then check source code:
```
- 1
- 2
- 3

- a
- b
- c
```
There is an extra blank line between the two list. And it is not possible to remove the blank line under "render" mode

**Comment by abnerlee** [comment]
You could use extra backspace to make a and 3 in same line, then press return key to split them into different list items.
