### ISSUE TITLE
HTML Tag autocomplete triggered by any key

### ISSUE THREAD

**Issue by FSXAC** [typora/typora-issues#3197]
macOS Catelina (10.15.2) on Typora 0.9.9.31.4 (4005)

Sometimes when using HTML tags inline with MD content (as shown in the gif). After the opening of an HTML tag (`<span>` for example), the first or two is registered as text, however any subsequent key inputs triggers the HTML tag autocomplete (without the `<` instead).

![output](https://user-images.githubusercontent.com/7558835/73019150-e526a700-3dd7-11ea-9216-815b146bb675.gif)

My relevant Typora settings: 
- Editor > "Auto pair brackets and quotes" is turned ON
- Editor > "Auto pair common Markdown syntax" is turned ON
- Markdwon > Syntax support: only "Inline Math" and "Diagrams" is turned ON

Reproduction of this bug is not consistent. There are random times when this would occur every time an HTML tag is used. While other times, there would be no problems.

**Comment by abnerlee** [comment]
Do you use any IME or non-English keyboard layout?

**Comment by FSXAC** [comment]
No, this is the standard Canadian English keyboard in macOS.

**Comment by abnerlee** [comment]
Does this still happen in latest version?

**Comment by FSXAC** [comment]
No longer reproducible on Version 0.9.9.36.2 (4901) with macOS 11.1 (20C69)
