### ISSUE TITLE
Software Stuck opening a little large file with some math equations in Surface pro 4

### ISSUE THREAD

**Issue by lj8385174** [typora/typora-issues#32]
I have a a 6.6 KB large file with approximately 50 equations. The software just stuck when opening it. 

I am using Surface Pro 4  with windows 10 10586.

Maybe it is caused by the high DPI?

**Comment by abnerlee** [comment]
Can you open file with one equation? 

If so, I think it is same with #26

**Comment by lj8385174** [comment]
Yes I can. THX
Hope it be better as soon as possible

**Comment by abnerlee** [comment]
Does typora still runs very slow when opening your 6.6KB file? If so, maybe you could send us a sample file which could  cause the stuck -> hi@typora.io

And does the font size of rendered math looks normal? I may refer to #20 if you met the same issue
