### ISSUE TITLE
Genuine HTML preview?

### ISSUE THREAD

**Issue by mlinchitstest** [typora/typora-issues#320]
The current editor does not really preview documents as they will be rendered in HTML. (does preview HTML code and so on). Is there a possibility that—in addition to "source view" and "default view"—we could also get a third view that will display documents *exactly as they would appear in the compiled html*? (enhancement)

**Comment by abnerlee** [comment]
It should be improved by improving the "default view". Adding new mode will increase the complexity.

**Comment by mlinchitstest** [comment]
I'd disagree. The default mode is perfect for very simple documents, but if you are  doing something more complex it's not necessarily more productive  than raw text. The default view could be improved: currently is won't handle html at all (unless it's images) and it you have multiple footnotes after a word it'll only ''show the first one''—and it will show it as [^name] rather than as integer. Leaving some things as code is probably _better for editing_ than full wysiwyg. 

But adding a full preview should be very simple, since the program already handles export well. For the the user it will certainly be simpler than doing an export just to see what the html looks like. Logically it fits IMO: you have plain text, something more WYSIWYG, and then a full preview. The program's half-hearted rendering of more complex documents is a big downside, at least for me.
