### ISSUE TITLE
[Feature Request] Add shortcut to move current paragraph up or down

### ISSUE THREAD

**Issue by jgclark** [typora/typora-issues#3200]
I'm wanting to switch to Typora from Visual Studio Code. But I'm finding I continually miss one of its tiny little features: being able to move the current paragraph or list item up or down in the text with keyboard shortcuts (e.g. ^⌘↑ and ^⌘↓ on Mac). Please could this be added?

**Comment by abnerlee** [comment]
duplicate with #1211
