### ISSUE TITLE
Chemical formulae using mhchem fails when export to docx

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3201]
Hello,
I am facing a problem converting text containing mhchem codes like this below into docx. The created docx file has mhchem code without being converted at all. Worth noting that exporting into PDF or HTML work just fine. My system is Catalina Macos with properly installed pandoc and basictex.

$$
\ce{C6H5-CHO}
\ce{$A$ ->[\ce{+H2O}] $B$}
\ce{SO4^2- + Ba^2+ -> BaSO4 v}
$$

**Comment by redoxmatlab** [comment]
by the way trying something from mac terminal also fails see below
` $ pandoc -s test.md --mathjax -o test.docx
[WARNING] Could not convert TeX math '
  \ce{C6H5-CHO}
  \ce{$A$ ->[\ce{+H2O}] $B$}
  \ce{SO4^2- + Ba^2+ -> BaSO4 v}
  ', rendering as TeX:
  
     ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace`

**Comment by abnerlee** [comment]
It's not supported because Pandoc or Docx is not supporting it. 

Closing it since there is currently no solution and docx and markdown is not equal. So some style may get lost or changed in import/export.
