### ISSUE TITLE
Typora must learn from vnote: request for similar features

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3202]
Looking for alternatives of Typora, I found vnote (https://github.com/tamlok/vnote). The concept of Vnote is interesting and I do like the app structure. Typora still more pleasant to work with but both apps seems to be competing on the same concept. 

I suggest that Typora developrs check Vnote and consider some of the features there. I like in particulr the ease in additing **captions to Images,** that's very cool!

More than that I love the Notes tab.

**Comment by abnerlee** [comment]
duplicate with #249 #379 #638 and maybe others
