### ISSUE TITLE
[Suggestion] Per document themes ?

### ISSUE THREAD

**Issue by emmanuelito** [typora/typora-issues#3204]
The theme setting affect all opened documents. The re is no reason to use the same theme for all documents, especially if you see themes as a kind of stylesheet.

It would be nice to somehow associate a theme to a document. When you re-open the document later, Typora could try to use the theme associated to the document, if this theme is installed.
The theme information could be saved in a specifically crafted comment of the md file.

**Comment by abnerlee** [comment]
duplicate
