### ISSUE TITLE
Problems when writing text under code block

### ISSUE THREAD

**Issue by BlkPingu** [typora/typora-issues#3205]
I tried to initialise a code block under another code block and the cursor jumped back to the beginning of the previous code block

System: OSX 10.15.2
Typora version: 0.9.9.31.3

I made a video of the bug in action.
https://www.youtube.com/watch?v=kIv8z7JZUu0

**Comment by abnerlee** [comment]
I'm not able to reproduce this. 

So can this be reproduce in 0.9.9.31.4?  and how is the first code block be created, and how did you move cursor to the line under code block?

**Comment by BlkPingu** [comment]
> I'm not able to reproduce this.

I can't reproduce it either and I can't tell anymore. Let's leave this open and wait if somebody else can report this in the future?

 > how did you move cursor to the line under code block?

I can't tell anymore. First and last time yet I had this bug

**Comment by abnerlee** [comment]
Please reopen when this occurs again
