### ISSUE TITLE
Is there a way to not have text centered?

### ISSUE THREAD

**Issue by Atoli** [typora/typora-issues#3206]
I REALLY like typora, but it bothers me the text is on the center by default.

Like this:

https://i.imgur.com/o9Z1F9i.png

There is a space to both sides (the text is centered) instead of being to the left side.

I know there is a sidebar that i can open, but my text moves to the right when do so, keeping the text centered:

https://i.imgur.com/SzV6cKP.png

It's not a big deal, but is there a way to have my text aligned to the left instead of centered?

**Comment by abnerlee** [comment]
You can check http://support.typora.io/Width-of-Writing-Area/ to change the CSS to change layouts of Typora
