### ISSUE TITLE
Export as image crashes

### ISSUE THREAD

**Issue by PotoTan** [typora/typora-issues#3212]
I have no way to export as an image. When I click Export as an image, the save window does not pop up as before, but returns to the editing window. The upper part shows that the export is in progress. I find that the window is frozen and I cannot click any other button. 

If you click randomly, you will be prompted whether typora is not responding, whether to close the program window.

win10 pro 1909
typora 0.9.83 beta

**Comment by abnerlee** [comment]
Is the content large (or embeds many images)? If not, possible to attach a sample file?
