### ISSUE TITLE
beta 0.9.9.31.4, Poor performance on MacOS: Mojave 10.14.3

### ISSUE THREAD

**Issue by AshleyMcVeigh** [typora/typora-issues#3214]
Typora: Beta 0.9.9.31.4 
MacOS: Mojave 10.14.3 (18D42)

When opening a large file the scroll performance is very laggy, switching to source code view completely fixes the issue, Tables seems to have a the largest effect on performance drastically slowing everything down. Opening the same files on my windows machine works fine as expected.

opening activity monitor shows nothing drastic with CPU (5%) or ram (~50mb) usage.

**Comment by abnerlee** [comment]
#68
