### ISSUE TITLE
Spell check does not work in Windows 10 1909

### ISSUE THREAD

**Issue by seyoum** [typora/typora-issues#3216]
**What I am trying to do**:
I am trying to get Norwegian spelling (spell check highlighting) in Typora version 0.9.83

**What I am doing**:
I am following the very vague instructions written [here](https://support.typora.io/Spellcheck/).

**What I expect to happen**:
I expect a red line to appear under the words that I misspell.

**What happens**:
No red underline appears even if I spell something wrong.

**What I have tried to fix the problem**:
I have made sure that all the Windows spelling settings are turned on. 

Here are some screenshots of my settings.

![2020 01 31-16 49 44](https://user-images.githubusercontent.com/15233794/73561800-9b7e3200-4451-11ea-9ec6-4eb96b3fd82c.png)
![2020 01 31-17 33 40](https://user-images.githubusercontent.com/15233794/73561801-9b7e3200-4451-11ea-8ce0-59fff9bf18a4.png)
![2020 01 31-16 50 07](https://user-images.githubusercontent.com/15233794/73562073-442c9180-4452-11ea-80ff-9aa965aa2125.png)

To be honest the spelling in Windows 10 is barely working most of the time. A quick web search would prove that. If there is any other way to get spelling in Typora I would like to know.

**Comment by abnerlee** [comment]
Typora will use the system spellchecker if OS is win 10, so "Windows spelling settings are turned on" may be required. We also updated the document in supporting site.

**Comment by abnerlee** [comment]
relates #214

**Comment by ScribbleGhost** [comment]
Sorry, I am a bit confused here. Did I miss something or have I done everything correct? I am not sure if I comprehended your last reply.

**Comment by abnerlee** [comment]
Sorry, I may wrote the wrong instruction. 

This should be caused by #3128 that unlisted languages in spellchecker panel are not supported
