### ISSUE TITLE
Running Typora causes Firefox to hang 

### ISSUE THREAD

**Issue by wujastyk** [typora/typora-issues#3217]
Linux system:
- Kernel: 5.3.0-28-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
- Mozilla Firefox 72.0.2

I have Firefox open most of the time.  When I start Typora, all my Firefox windows freeze and stay inactive for as long as I wait.  I have to drop to the system level and use the "kill" command to regain control of my system.

**Comment by wujastyk** [comment]
Typora 0.9.84 (beta)
Firefox 73.0.1 (64-bit)
Linux Mint 19.3 with Cinnamon

I discovered that the huge system slowdown happens if I launch Typora **when Firefox is already open**.  If I launch Typora first, and then Firefox, my system behaves normally and I can work using both programs.

Here is a graph of CPU resources at the moment when I launch Typora, with Firefox already open.  There are 8 CPUs and they all max out when Typora starts up:

![Screenshot from 2020-02-25 12-48-51](https://user-images.githubusercontent.com/762246/75282302-1119bb80-57ce-11ea-99e3-9755193acf4f.png)

**Comment by abnerlee** [comment]
Close since it is report for old typora version and didn't receive similar reports from others, and we did not reproduce it and do not have clues for this neither

**Comment by wujastyk** [comment]
I also stopped experiencing the problem.
