### ISSUE TITLE
Empty lines in between  list

### ISSUE THREAD

**Issue by zjopy** [typora/typora-issues#3221]
When you create a list, and put a line without a list item in it, the whole list gets spaced out by one line.

It does not show in Typora, but you can see it in the raw text file. As soon as you view the markup in another editor like GitHub, it looks very bad.

See this picture for better explanation.

<img width="895" alt="double spaced lines" src="https://user-images.githubusercontent.com/33468089/73617238-c5378480-461c-11ea-98b0-7b28834ce167.png">

Typora 0.9.9.31.6 (4047)
macOS 10.15.3 (19D76)

**Comment by abnerlee** [comment]
In markdown, there should be empty line between two paragraphs, and then make the list a "lose" list in markdown.

To create new line, instead of new paragraph, you will need to use shift+return, which will be rendered as new line or as same line based on different markdown rules.
