### ISSUE TITLE
Content blocks for easy inclusion of images (and other files)

### ISSUE THREAD

**Issue by dominikmayer** [typora/typora-issues#3223]
iA Writer introduced [Content Blocks](https://ia.net/writer/support/general/content-blocks) as an easy way to include other files into a document.

With a content block the syntax for including an image is as simple as:

> /ImageName.jpg

This makes documents with many images way more readable.

Any chance of supporting this?

**Comment by abnerlee** [comment]
seems same with #441

**Comment by dominikmayer** [comment]
I don't think it's the same as #441. File transclusion is integrating one (markdown) file into another so that they are rendered as if they were one. No change to the standard rendering engine needed once you have the combined file.

The content blocks on the other hand take non-markdown files like images or CSV files and add support to render them.
