### ISSUE TITLE
Viewing markdown files on the go, images included?

### ISSUE THREAD

**Issue by hschmiedhofer** [typora/typora-issues#3225]
I am storing my markdown-files on Google Drive, where each file has an assets folder containing images that are referenced via relative paths, for instance: 

`![1571236845356](javascript.assets/1571236845356.png)`

Can someone recommend an Android app, that lets me view my markdown files including images (!) on my phone directly from Google Drive?

Is there any other way one could think of, to fully view markdown files produced with typora on the go? Right now i need to convert my files to pdf, which is rather cumbersome.

**Comment by abnerlee** [comment]
Please try upload images http://support.typora.io/Upload-Image/
or find an android app which will load relative images
