### ISSUE TITLE
Data get lost when switching between Preview and Source Code mode

### ISSUE THREAD

**Issue by chiahsien** [typora/typora-issues#323]
### Version

Typora 0.9.97.8
OS X El Capitan 10.11.6
### How to reproduce
1. Open or create a markdown file.
2. Switch between preview and source code mode.
3. Suddenly, when I switch to source code mode, the last few lines are disappeared.
4. Then I switch to preview mode and switch back to source code mode, more last few lines are disappeared.

I can't say that I can reproduce it all the time, but the chance is very high.

**Comment by tcloaa** [comment]
same issue high (missing a few lines).

Can someone fix this issue?

**Comment by inforick** [comment]
Same issue here.
I lost about 10 hours of work during writing the manual of Hive.
And the undo is always disabled after saving.

**Comment by abnerlee** [comment]
see http://support.typora.io/Version-Control/

Mostly should be fixed in recent updates

**Comment by hao-lee** [comment]
Typora version control can't recover my file content. I won't use typora.
