### ISSUE TITLE
DEL key does nothing at end of paragraph

### ISSUE THREAD

**Issue by mocsa** [typora/typora-issues#3230]
How to reproduce on Windows:
- Go to www.lipsum.com
- On the left of the "Generate Lorem Ipsum" button, enter 80000 into the input box and set the radiobutton to "bytes".
- Click on "Generate Lorem Ipsum"
- Copy the whole text to a new Typora file and save it.
- Close Typora
- Open Typora and open your previously saved file.
- Put your cursor at the end of any paragraph.
- Press DEL.
- PROBLEM: Nothing happens. I expect Typora to merge the two paragraphs.
 
It seems that the problem only happens with "bigger" files. Although 80kB is not that big.

If I put my cursor at the beginning of any paragraph and press BACKSPACE then the two paragraphs are merged.

I experience this in version 0.9.83.

**Comment by abnerlee** [comment]
should be fixed
