### ISSUE TITLE
Typora stops working out of nowhere

### ISSUE THREAD

**Issue by demianbrdg** [typora/typora-issues#3233]
I was writing, and several times I had to close Typora because it started to bug, by that I mean the page freezes and I can't work that way. I does bother me a lot, please fix it.
I work in a Mac.

**Comment by Abdillah** [comment]
Mine was when opening a directory, possibly the empty one (but I think it's not always empty when crashed).

**Comment by skaboy71** [comment]
Aaaaaand locking up again.  Can't seem to find anything in logs but program becomes unresponsive.

**Comment by luabish** [comment]
same thing happens when my editting md file contains an image pasted from clipboard……

**Comment by demianbrdg** [comment]
Is this happening because I haven't updated to Catalina? I'm still on Mojave version 10.14.5

**Comment by luabish** [comment]
> Is this happening because I haven't updated to Catalina? I'm still on Mojave version 10.14.5

maybe not.I am on 10.15

**Comment by jayMSL** [comment]
this is happening to me as well!

**Comment by Abdillah** [comment]
Hello, is there a way to get a crash report log?
I think this issue is nowhere if we can't get any error log / trace :(

**Comment by sanketshahc** [comment]
I'm having the same problem!

**Comment by linkot** [comment]
Encountered when pasting images

**Comment by abnerlee** [comment]
"Open folder" is a bug and fixed in latest version. 

About insert images, is lt similar with #3238?

**Comment by demianbrdg** [comment]
Well this happened to me when I was using voice over. But somehow happened when I was just writing too.

**Comment by victor-samson-mo** [comment]
Also experiencing the crash. Happening on a small document - not saved - with only text elements. Unable to repro.

macOS: 10.15.3
Typora: 0.9.9.31.7 (4087)

**Comment by abnerlee** [comment]
should be fixed
