### ISSUE TITLE
linux mint installation error

### ISSUE THREAD

**Issue by gillcar** [typora/typora-issues#3235]
I get this error when installed from Terminal
      
Réception de :11 https://typora.io/linux ./ Packages [7 344 B] 
8 137 o réceptionnés en 1s (7 349 o/s)                         
Lecture des listes de paquets... Fait

**W: Distribution en conflit : https://typora.io ./linux/ InRelease (./linux/ attendu, mais  obtenu)**

and it shows in Apps update manager

![Capture du 2020-02-07 20-50-33](https://user-images.githubusercontent.com/43098156/74077363-57f56c00-49ed-11ea-8b39-45e7d8fdaa9e.png)

**Comment by gillcar** [comment]
OK, I found an old post from 2017 about this problem that was closed last year...

I'm a newbie to Linux, but used to work on computers before I retired 10 years ago, and I always took a warning seriously, so I'm wondering how I should take this???

**Comment by abnerlee** [comment]
see http://support.typora.io/Typora-on-Linux/

**Comment by gillcar** [comment]
Well... ok, it may be closed for you, but it doesn’t mean that it worked for me...
It’s even worse. So let’s call it quit, I’ll just try to get rid of the warnings I have now, even after uninstalling the program. Sorry...
