### ISSUE TITLE
OSX Catalina - Can't display images in Box

### ISSUE THREAD

**Issue by djscholl** [typora/typora-issues#3238]
I'm able to see linked images if I copy-paste them into Typora, which results in them being in `~/Library/Application Support/typora-user-images/`. But any other location I've tried, the image load fails. If I open the same markdown file in intelliJ's markdown viewer I'm able to see the images.

![image](https://user-images.githubusercontent.com/7576829/74094501-ef1efa00-4aa7-11ea-9fea-fc0d214e33af.png)

I'm guessing this is related to Catalina's security settings. Usually there's a popup asking if you're okay with the application getting access to a folder. I haven't seen anything like that for Typora and so far can't find a way to grant access to it since it doesn't show up in the "Files and Folders" section of the Security & Privacy settings.

![image](https://user-images.githubusercontent.com/7576829/74094414-70758d00-4aa6-11ea-8c6e-6b979ff2bf2e.png)

I'm using Version 0.9.9.31.6 (4047)

**Comment by djscholl** [comment]
After digging around a little more, it seems the problem only occurs if I try to use Typhora in my `Box` folder which is syncing to Box. If I use files in other locations I get the prompts as expected to grant access, and then it works fine.

**Comment by egon-niederacher** [comment]
Had the same issues when inserting images from Dropbox, Typora sometimes even hangs and must be killed.

**Comment by abnerlee** [comment]
Would you try give Typora Full Disk Access in preference panel to pass Catalina's security rule? Will this fix the issue?

**Comment by djscholl** [comment]
Should have mentioned - I tried that as well. Doesn't seem to help. I'm thinking it's more than just a permission issue since it works fine in IntelliJ. I also just tried MacDown and it works fine without having to give any special permissions.

**Comment by abnerlee** [comment]
@djscholl could you check the error log (message about load image / resources fail) in console by

1. enable debug mode in help menu
2. click "inspect element" on context menu of right click
3. open "Console" tab?

**Comment by djscholl** [comment]
"Not allowed to load local resource"
![image](https://user-images.githubusercontent.com/7576829/74471721-53eea180-4e66-11ea-9a05-c34c3265934b.png)

**Comment by abnerlee** [comment]
Still seems a privilege bug from the log.  Relates #2697

Unlike IntelliJ ot MacDown, Typora use WKWebview to render the content, whose process is running by the system (out of Typora's control scope).

**Comment by abnerlee** [comment]
@djscholl In my test, images inside hidden folders are refused to be loaded, if you refer an image that is NOT in a hidden folder (which starts with dot in folder name), can it be displayed successfully?

Relates #2697

**Comment by djscholl** [comment]
Hmm no, same problem for me in that case. 
![image](https://user-images.githubusercontent.com/7576829/74547233-6671e500-4f11-11ea-9ee0-9fada45b98ec.png)

**Comment by abnerlee** [comment]
Yes, I can display the images in hidden folder, so maybe it is relates to Box or Dropbox folder.

**Comment by djscholl** [comment]
Right, it works fine if I do this in a folder that isn't syncing to Box.

**Comment by abnerlee** [comment]
Should be fixed now
