### ISSUE TITLE
Change Lines Space

### ISSUE THREAD

**Issue by ZijiaLewisLu** [typora/typora-issues#324]
Hi, Right now Typore sets the space between lines big. Is there a way i can change it?

**Comment by abnerlee** [comment]
By add `line-height` in custom css. (http://support.typora.io/Add-Custom-CSS/)

**Comment by ZijiaLewisLu** [comment]
Sorry, I didn't make myself clear. I mean when hitting enter in normal mode, the typora actually adds two blank lines and moves the cursor to the beginning of the second lines. And in normal mode, there is no way to delete the extra blank line in between.

**Comment by abnerlee** [comment]
Press "Return" for new paragraph. (one blank line)

Press "shift"+"return" for new line. (no blank line)

**Comment by JCWDFCS** [comment]
How to set 'return' for newline

**Comment by abnerlee** [comment]
@JCWDFCS This is not supported, see https://github.com/typora/typora-issues/issues/37
