### ISSUE TITLE
Typora does not download the update

### ISSUE THREAD

**Issue by fredmj** [typora/typora-issues#3240]
Hello there,
I'm using the **great** Typora editor (v0.9.79 beta) for my markdown messages and I finf it really convenient. But there's an issue with the updating process. When executing Typora on Windows 10 (and same on centOS), the application freeze trying(?) downloading the new version.

![image](https://user-images.githubusercontent.com/8500020/74105274-a2492b00-4b5c-11ea-9d7e-2d212c18bf8c.png)

![image](https://user-images.githubusercontent.com/8500020/74105291-c4db4400-4b5c-11ea-83f4-3d5892eeb37b.png)

Seems a doublon of issue [#928](https://github.com/typora/typora-issues/issues/928) and [#873](https://github.com/typora/typora-issues/issues/873).

Is someone have a solution ?

**Comment by abnerlee** [comment]
@fredmj do you have network issue, for example, could you download typora from our website successfully and what's the speed?

**Comment by fredmj** [comment]
@abnerlee no network issue from my side and the _"manual"_ download is working perfectly. My download speed is correct: I'm connected through fiber (FFTH) with reasonably bandwidth quality (downrate 25 mbps/ uprate 50mbps/latency 16ms).

**Comment by abnerlee** [comment]
I added the all size and downloaded size on the progress bar in newer versions.

You could be able to know it is network issue then

**Comment by fredmj** [comment]
thx @abnerlee, correction works for me.

**Comment by sschuldenzucker** [comment]
This is happening to me atm. I'm on 0.9.95 updating to 0.9.96. There's just a status bar that doesn't move. No network issues (fast cable connection) here.

**Comment by akshith6212** [comment]
Same with me here, I'm having 0.9.98 version trying to update to 0.10.6 and the bar is not at all moving. No net work issues and now, I'm trying to download from the website.

**Comment by oshihirii** [comment]
In case it helps anyone else...

I was having issues with this on Windows 10, ie none of the buttons worked in the update screen:  

![typora_doesnt_update](https://user-images.githubusercontent.com/5090307/140257022-37439a51-f181-4a01-a944-071e8c9baf7d.png)

I downloaded and re-installed the package but the issue persisted.  

So I uninstalled from `Add/Remove Programs` and then re-installed again and it has now updated to the latest version.

**Comment by aegonwolf** [comment]
same issue

**Comment by Magickmars** [comment]
I have the same issue, updating from Version 1.9.3, to 1.9.5 o Windows 11

**Comment by shealy2020** [comment]
As MagicKmars reported, status bar frozen when updating from Version 1.9.3, to 1.9.5 on Windows 11. On the other hand, the update on Windows 10 worked without issue.

**Comment by univok** [comment]
Same issue Typora 1.11.5 under Win11 Pro 24H2 26100.4946. Initial install was for one user, without admin rights. The update reminder does nothing but closes itself when you press "Download Update". When using the menu at Preferences >> Settings >> Check Updates button there is a progress bar visible which closes after a short time. Subsequently, the update reminder reappears and the whole thing starts all over again. This problem seems difficult to solve.
