### ISSUE TITLE
apt key update

### ISSUE THREAD

**Issue by songsammy** [typora/typora-issues#3241]
<pre>E: 仓库 “https://typora.io/linux ./ Release” 的签名不再生效。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
root@sam-ThinkPad-Edge-E430:/media/sam/新加卷/ShiquanAPI/test# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
Executing: /tmp/apt-key-gpghome.OGJ6OOjAUl/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
gpg: 密钥 BA300B7755AFCFAE：“Abner Lee &lt;abner@typora.io&gt;” 未改变
gpg: 处理的总数：1
gpg:              未改变：1
</pre>

It tells me that the key is expired.Maybe you should update them.

**Comment by abnerlee** [comment]
I didn't see "expiration" from your error message, it may caused by network issue.

Please refer https://typora.io/#linux to add public key from typora website
