### ISSUE TITLE
<br> line break shows as text in Word export

### ISSUE THREAD

**Issue by martzell** [typora/typora-issues#3246]
Typora documentation says we should use HTML tag line break `<br />`: https://support.typora.io/Line-Break/

This does not work for Word export (but for PDF). I've tested all 4 types of line breaks and 3 types of sequential spaces. Please see the result in the attached screenshot.

Only Markdown line break – space+space+newline – works. For sequential spaces only HTML-Entity `&nbsp;` works. Backslash escape does not work at all, and so is falsely mentioned in the Typora documentation.

Please correct the documentation. Also please think about if recommending to avoid new lines in the documentation is realistic. How do you write a street address or contact block or text block without newline? Two paragraphs?

I think in pandoc markdown exists an extra formatting style, like a markdown list, but without bullets, if I remember correctly lines that begin with | pipe could be rendered like this. A complicated solution because Markdown supports hard wrapped text. Without hard wrapped text a line break could be a line break and 2 line breaks a paragraph.

![Screen Shot 2020-02-11 at 15 44 33](https://user-images.githubusercontent.com/29772424/74248219-86be5b80-4ce7-11ea-8a1a-10fc36706d31.png)

**Comment by abnerlee** [comment]
fixed in new release
