### ISSUE TITLE
No line breaks possible for Word export, <br> showed as text in file.docx

### ISSUE THREAD

**Issue by martzell** [typora/typora-issues#3247]
pandoc markdown solution:  Grid tables (Emacs). https://pandoc.org/MANUAL.html#extension-grid_tables

Best table format would be pure Elastic Tabstops. Without any grid characters like pipe |. Tabstops are original supposed for tables. In TSV (tab-separated values) format even tab and newline characters are possible inside 

```
Simple text	"line
break"	"tab	stop"	"Text with ""quote"" and double""""quote."	
```

|             |               |             |                                      |
| ----------- | ------------- | ----------- | ------------------------------------ |
| Simple text | line<br>break | tab	stop | Text with "quote" and double""quote. |

**Comment by abnerlee** [comment]
duplicate with #1876
