### ISSUE TITLE
The mermaid cannot draw dashed lines in classDiagram

### ISSUE THREAD

**Issue by Cr1ft** [typora/typora-issues#3248]
```mermaid
classDiagram
C .. D
```
The above method  cannot draw dashed lines, only solid lines.i tried it on [mermaid-live](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBwZXJzb257XG4rY2FsbChwaG9uZSlcbn1cblxuY2xhc3MgcGhvbmV7XG4rIFNyaW5nIHhpbmdoYW9cbn1cblxucGVyc29uLi4-cGhvbmVcblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) and found it was ok

**Comment by Cr1ft** [comment]
> ```
> classDiagram
> C .. D
> ```
> 
> The above method cannot draw dashed lines, only solid lines.i tried it on [mermaid-live](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBwZXJzb257XG4rY2FsbChwaG9uZSlcbn1cblxuY2xhc3MgcGhvbmV7XG4rIFNyaW5nIHhpbmdoYW9cbn1cblxucGVyc29uLi4-cGhvbmVcblx0XHRcdFx0XHQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) and found it was ok

My version is 0.9.83

**Comment by abnerlee** [comment]
duplicate with #3215

**Comment by NDK2020** [comment]
is this problem fixed on 2021? I'm using Typora version 0.9.96 and still get this problem.
