### ISSUE TITLE
Dismissing Footnote Previews

### ISSUE THREAD

**Issue by DIWesser** [typora/typora-issues#325]
Footnote previews do not seem to be properly clearing when clicking on a paragraph. This behaviour seems to be act differently depending on the order of the paragraphs clicked on and the number of footnotes that have been moused over.

**Example:**
Paragraph one[^footnote 1]
Paragraph two[^footnote 2a], [^footnote 2b]

If I click on paragraph one then mouse over footnote 2a, I can clear the preview by clicking one paragraph two, but not by clicking on paragraph one.

if I click on paragraph one, mouse over footnote 2a, then footnote 2b, I can clear the preview by clicking on paragraph one, but not by clicking on paragraph two.

**Comment by abnerlee** [comment]
The auto hide behavior for footnote is improved in new version
