### ISSUE TITLE
PDF export (or print) creates page with large gaps between tables and headings

### ISSUE THREAD

**Issue by rlayton6** [typora/typora-issues#3250]
Large gaps (one third of an A4 page) are present between a heading and the start of a table when exporting to PDF, or directly printing.

The attached markdown is a simple page that fits on a single printed A4 page, but adding rows to its table causes it to wrap onto the next page (because of this gap). 

Inconsistent behaviour:
**Removing one row**  from the table, removes the large gap!
**Adding a column** to the table, removes the large gap!

The problem appears in both Windows 10 and Linux (Ubuntu).

Typora version: 0.9.83 (beta)

My system:
Ubuntu 18.04.4 LTS
Linux 4.15.0-76-generic

[test.md.txt](https://github.com/typora/typora-issues/files/4188915/test.md.txt)

[test.pdf](https://github.com/typora/typora-issues/files/4188916/test.pdf)

**Comment by abnerlee** [comment]
I'm not able to reproduce this on 0.9.94, should be fixed already.
