### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sanketshahc** [typora/typora-issues#3251]
There is a MASSIVE memory leak problem that has come up recently....

**Comment by sanketshahc** [comment]
I have a 4000 word document that is taking up 20gb of memory. How does that make sense? Problem persists....

**Comment by oliverproud** [comment]
I am facing this issue also, 7.63GB of memory being used on a single 300-word file.
![image](https://user-images.githubusercontent.com/23120916/74565181-93051b80-4f68-11ea-99d2-0343f39c8753.png)

**Comment by abnerlee** [comment]
merge into #68

@oliverproud @sanketshahc do you open a file contains lots of images, or does the folder contains lots of fils / subfolders?

**Comment by sanketshahc** [comment]
No just text!
No sub folders or anything 
Sanket C. Shah
