### ISSUE TITLE
Line feed on source displays as line break

### ISSUE THREAD

**Issue by terrymorse58** [typora/typora-issues#3252]
Testing Mac OS beta Version 0.9.9.31.6 (4047).

So far, it looks really good. One little issue:

Line feeds in the source document display as hard line breaks, as if there were a <br> tag. This does not match how text is displayed on GitHub, so previewing is not as WYSIWYG as it could be.

Recommend that line feeds within a paragraph should not result in a <br>.

Sample input:

```
This is
a single line
of text with line breaks.

This is a single line of text without line breaks.
```

Typora:

![picture alt](https://terrymorse.com/public/typora-issue.png)

**Comment by abnerlee** [comment]
duplicate with #1963 #1522 #1427 #1874 #233 #1113 #364
