### ISSUE TITLE
Error Occurred while Configurating

### ISSUE THREAD

**Issue by mcdanci** [typora/typora-issues#3253]
This is my first time using Typora, The app looks graceful.

But! When I setting preferences, error occurred, with a screenshot as follow.
![image](https://user-images.githubusercontent.com/12187546/74372848-575a3c80-4e16-11ea-910c-fb45efee2414.png)

**Comment by abnerlee** [comment]
Since we cannot know if your computer has applications that linked to ".json" file type, we will let this button open config folder instead.
