### ISSUE TITLE
全选复制会自动复制成markdown

### ISSUE THREAD

**Issue by si7eka** [typora/typora-issues#3255]
1.非源码编辑模式下
2.CTRL+A选择全部
3.右击-复制
4.在txt中粘贴

粘贴的内容会带有markdown格式的标记符，请问不是不是不太合理
应该是复制文字才对
如果需要为markdown格式 会是 右击--复制/粘贴为--复制为markdown

**Comment by abnerlee** [comment]
please check your preferences
