### ISSUE TITLE
collapse when insert picture 

### ISSUE THREAD

**Issue by findlamp** [typora/typora-issues#3256]
Env: MacOS 10.15.3
version: 0.9.9.31.7
when I insert a picture and not to set the scaling, the software could collapse.

**Comment by abnerlee** [comment]
how did you insert image, by drag & drop, copy file, copy image content or input image path ?

**Comment by findlamp** [comment]
You know, touch the insert picture button on the TouchBar, and select the picture from the menu, that function is awesome. However, after I insert the picture in the file, it allows me to select the different scaling of a picture. If I just ignore it and move the mouse to other places and click, the software will collapse.

**Comment by gromob** [comment]
On MacOSX High Sierra. Drag-drop causes similar issue. Sometimes also when I change the size. Typora does not react. OS still works fine. The fan noise goes up high until I force quit Typora.

**Comment by abnerlee** [comment]
relates #3279

should be fixed in latest verison
