### ISSUE TITLE
Installing updates lose open windows

### ISSUE THREAD

**Issue by fuzzy76** [typora/typora-issues#3257]
Very often I double-click a markdown-file, Typora opens with my file, a update dialog pops up, I choose to install the update, Typora is restarted and instead of my open document I get a blank window. I then have to close the blank window and re-open the document.

Can this be fixed somehow?

**Comment by abnerlee** [comment]
still happens now?

**Comment by fuzzy76** [comment]
I'll let you know once the next update arrives :)

**Comment by fuzzy76** [comment]
No, this still happens. What is supposed to happen?

**Comment by abnerlee** [comment]
On Windows version or macOS one?

**Comment by fuzzy76** [comment]
macOS. Sorry, I should have mentioned that from the start.

**Comment by abnerlee** [comment]
should be fixed in 1.1
