### ISSUE TITLE
Don't have permission to save the file "blah.md" in the foler "myblah" on my GDrive.

### ISSUE THREAD

**Issue by dazdaz** [typora/typora-issues#3258]
I am experiencing the following issue, when saving a file :1st_place_medal: 

"You don't have permission to save the file "blah.md" in the foler "myblah" on my GDrive FileStream.
To view or change permissions, select the item in the Finder and choose File > Get Info"

So... when I goto Finder, review the file perms, my user has rw access to the file and folder named "myblah".

I can use Sublime to create and edit files, just fine.

Specs : OSX 10.15.3 and Typora 0.9.9.31.7

**Comment by dazdaz** [comment]
Solution: Goto Security + Privacy / Full Disk Access and authorize Typopia.

Can someone add this to the docs ?

**Comment by abnerlee** [comment]
please refer https://support.google.com/a/thread/16323129?hl=en

Could you try if TextEditor.app can save file in GDrive or not?
