### ISSUE TITLE
Mail recognition a bit spotty

### ISSUE THREAD

**Issue by fuzzy76** [typora/typora-issues#3259]
In addition to recognise URL's in text, Typora seems to recognise mail addresses as well. But this recognition doesn't works for all country-related TLDs; .co.uk works but .no or .se doesn't. For regular URLs, this is not an issue.

Being a norwegian, I use .no quite a lot. If this won't/can't be fixed, I would like a way to disable the recognition in the preferences.

**Comment by abnerlee** [comment]
This is to avoid filenames, like icon@2x.jpg, so only common ones are covered.

Please use `mailto:` or `<hi@aa.bb>` to write mail address explicitly. 

relates #2366
