### ISSUE TITLE
Table with `code` cell

### ISSUE THREAD

**Issue by kylejung** [typora/typora-issues#326]
If multiple columns have `code` format, not work correctly.

Expected like this...

| Not  | Working | With | Multiple  | Code      |
| ---- | ------- | ---- | --------- | --------- |
| This | `row`   | is   | displayed | correctly |
| This | `row`   | is   | not       | `work`    | 

But displayed...
<img width="817" alt="typora_table_error" src="https://cloud.githubusercontent.com/assets/1503193/19060098/23411012-8a20-11e6-859c-730a7c2d6645.png">

**Comment by abnerlee** [comment]
We will fix this critical bug on next version up soon.

**Comment by abnerlee** [comment]
Fixed in new version
