### ISSUE TITLE
Find should ignore markup in WYSIWYG mode

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#3260]
When in WYSIWYG mode, and given the text:

```
`Find` should ignore markup in [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG)
mode.

Some people like Typora's *Hybrid* mode. Some people dream of an editor
with a true *WYSIWYG* mode. Typora could make everyone happy with a
simple `Display markup under cursor` switch (issue #1317). 😉
```

`Find` "WYSIWYG mode" should match two items.

In other words, `Find` should operate on the rendered text, not the underlying "source code".  **This is how nearly all rich text editors work.**

(When in *source code mode*, `Find` should continue to behave as it does now.)

**Comment by abnerlee** [comment]
Should be an option in #2824
