### ISSUE TITLE
Preference Request: Save on lost focus

### ISSUE THREAD

**Issue by prestonmcgowan** [typora/typora-issues#3261]
Allow for auto-save to persist any changes to an editor when the mouse focus is lost.

Similar to: https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save

**Comment by abnerlee** [comment]
on macOS Typora follows the system spec about "auto-save"

on Linux / Windows, the "auto-save" function is provided, but we don't think it is needed to provide very very detailed option about when and how "auto-save" is trigger. Just enable/disable would be enough
