### ISSUE TITLE
Mermaid errors are hidden

### ISSUE THREAD

**Issue by prestonmcgowan** [typora/typora-issues#3262]
When I had some malformed mermaid diagram text, the error was hidden and the diagram showed a blank diagram.

Example:
Diagram has error (should be a lower case 's')
![image](https://user-images.githubusercontent.com/1315891/74458325-893fc300-4e57-11ea-8a20-7123689e0156.png)

Diagram without error
![image](https://user-images.githubusercontent.com/1315891/74458295-7dec9780-4e57-11ea-8408-ace288526b0b.png)

**Comment by abnerlee** [comment]
relates #1661

**Comment by abnerlee** [comment]
should be fixed
