### ISSUE TITLE
Code Fences conversion to HTML adds extra line after code on Firefox

### ISSUE THREAD

**Issue by KarthikChandy** [typora/typora-issues#3263]
1. Create a MD file with some code. 

E.G.:

> `# Test`

>` ```bash `
>`ls`
>`pwd`
>`uname -a`
>`whoami`
>` ``` `

2. Now convert **File - Export - HTML** 

3. Now open the resulting HTML file.
4. Copy the data in the code fence and paste it into a text editor. It would be:

> `ls`
> 
> `pwd`
> 
> `uname -a`
> 
> `whoami`

Whereas the expected output should be
> `ls`
> `pwd`
> `uname -a`
> `whoami`

Am I doing something incorrectly, or is this a bug?

Thank you,
Karthik

**Comment by abnerlee** [comment]
Are you copy from Firefox?

**Comment by KarthikChandy** [comment]
Yes, that is strange. 
The problem only appears on Firefox. I don't have a problem with Chrome.
Is there anything I can do to fix the issue on Firefox.
Thank you.

**Comment by abnerlee** [comment]
duplicate with #2791
