### ISSUE TITLE
Quotes in urls are missing when opening in browser

### ISSUE THREAD

**Issue by stefnotch** [typora/typora-issues#3265]
When clicking on a link with quotes (`"` or `%22`) to open it in the browser, a link without the quotes will be opened in the browser. 

Example link:
`https://github.com/htblaleonie/htblaleonie.github.io/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22%F0%9F%93%A2+announcement%22+is%3Aissue+`

```markdown
[test](https://github.com/htblaleonie/htblaleonie.github.io/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22%F0%9F%93%A2+announcement%22+is%3Aissue+)
```
Note how no issues have this label, because the quotes are missing in the browser.

**Typora Version:** 0.9.83
**OS:** Windows 10
**Web Browser:** Firefox

**Comment by abnerlee** [comment]
Not able to reproduce this with 0.9.86 and Chrome, may be fixed already

**Comment by stefnotch** [comment]
I can still reproduce this with version 0.9.86 and Chrome. 
Here is a 

[test link](https://github.com/htblaleonie/htblaleonie.github.io/issues?q=label%3A%22%F0%9F%93%A2+announcement%22+is%3Aissue+)

And here is the markdown source code for the test link. 
```markdown
[test link](https://github.com/htblaleonie/htblaleonie.github.io/issues?q=label%3A%22%F0%9F%93%A2+announcement%22+is%3Aissue+)
```
