### ISSUE TITLE
Error triggered under certain circumstances file copy

### ISSUE THREAD

**Issue by SailHe** [typora/typora-issues#3266]
**I'm opening this issue because:**
- **I'll report a bug**
- ~~I'll propose a new feature~~

# Context
    - Operating system: Win10 `1809 x64 2019-11B`
    - typora version: 0.9.83

# Description
The main configuration is as follows
`../assets/${filename}`
like this

![image-20200214222401033](https://user-images.githubusercontent.com/30830174/74541641-f13bf980-4f7c-11ea-83f4-81cc26ca1186.png)

## Reappear
create a test folder and 1, 2, 3 subfolder
cd to folder [3]
create a new markdown file `test.md`  and open it using typora,
then enter in the software

`![img](../..)`

Then trigger a phenomenon

![ty_bug_0001](https://user-images.githubusercontent.com/30830174/74541581-d79ab200-4f7c-11ea-9ca4-3fef18d43f60.gif)

**Warning: Under Windows directory hierarchy too deep to generate extremely difficult to delete!!!**

**Comment by abnerlee** [comment]
should be fixed in 0.9.86

**Comment by abnerlee** [comment]
relates #3317 #3256
