### ISSUE TITLE
the MacOS app in view mode got stuck when the markdown file has too much picture 

### ISSUE THREAD

**Issue by notfresh** [typora/typora-issues#3267]
The "view mode", I created,   means the default mode you can see what you edit and is the opposite of the the source mode .

I got a problem recently, when I insert too many picture in the view mode in a markdown file, 
the app got stuck frequently.  
I used a MacOS system, and the os version is High Sierra, 10.13.6, and the  Typora  version is 0.9.9.31.7.

I havn't update the app if there is new version.  

My system memory has 2GB free space, when the typora got stuck.

**Comment by abnerlee** [comment]
seems a duplication of #3233
