### ISSUE TITLE
HTML fragments render

### ISSUE THREAD

**Issue by guantau** [typora/typora-issues#327]
Hi! Typora is an amazing editor of Markdown. But I've got some trouble. For the reason that Markdown doesn't support setting the image's size, I use HTML fragment "<img />" to control the size of image. So I wonder that if HTML fragments such as "<img />" can be rendered in Typora. Thank you very much!

**Comment by yfwz100** [comment]
It seems that `img` tag has been supported in the latest version of Typora.

**Comment by guantau** [comment]
@yfwz100 Yes, it's great.
