### ISSUE TITLE
Default home directory when Typora opens

### ISSUE THREAD

**Issue by RokuKent** [typora/typora-issues#3270]
Could we have a preference setting for the home directory when Typora starts so any new files saved will be placed in this directory structure by default?

**Comment by abnerlee** [comment]
Yes, you can set this in preferences panel  http://support.typora.io/File-Management/#set-default-folder

**Comment by RokuKent** [comment]
Thanks, that was is, the documentation preference screen is different from the current one but the same settings are there, I just needed to open up the popup to see the options.
