### ISSUE TITLE
Images not copying to custom folder 

### ISSUE THREAD

**Issue by gynet** [typora/typora-issues#3271]
If I copy some web content to the markdown, the images will still using url referencing instead of auto copying to the custom folder as I setup. The behavior seems changed in the recent versions, 
- Browser: Firefox 74
- OS: MacOS
- Using version Version 0.9.9.31.4

**Comment by abnerlee** [comment]
Could you check if you allow this for online images?

**Comment by gynet** [comment]
@abnerlee  the settings allows online images

**Comment by abnerlee** [comment]
Is there any error message when you drop online images into Typora file?

**Comment by gynet** [comment]
@abnerlee there was no error messages, only thing is the image content still using http uri instead of converting to local paths.

**Comment by abnerlee** [comment]
Could you try 0.9.9.32.1?

**Comment by gynet** [comment]
It has the same issue. The image contents copied from browser still use the web urls instead of be converted to the local paths.

**Comment by abnerlee** [comment]
#3284?
