### ISSUE TITLE
Cursor/selection bug (Shift + Left)

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#3274]
# Steps to reproduce
1. Open a Typora window on Windows
2. Type the following:

   ```Markdown
   - 123
   - 456 789
   ```

3. Navigate the cursor before the `4`
4. Press Ctrl + Shift + Right, so `456 ` (with trailing space) is selected
5. Press Shift + Left

# Expected behavior
- The selection is reduced to `456` (without trailing space)

# Actual behavior
- The selection is cleared and the cursor is moved before the `4`

Please note this appears to be closely related to #3011.

**Comment by LinqLover** [comment]
Possibly related to #1164.

**Comment by abnerlee** [comment]
should be fixed in latest version
