### ISSUE TITLE
Big "blank" inoperable space

### ISSUE THREAD

**Issue by luccasklotz** [typora/typora-issues#3275]
Hello all

I have just downloaded Typora and started making notes.
However, I have an issue which is a big, blank inoperable space on the left right next to the siderbar.
I can not manage to use that space to write, is this an issue? is there a way to remove this?

it does not make sense, I have already surfed through the preferences but did not find anything that would remove this.

If I remove the side bar, it continues there, even bigger.

I don't know if this is a windows issue. Hope I can figure it out

![image](https://user-images.githubusercontent.com/54865177/74608637-ae376e80-50c1-11ea-9e6e-028441401f85.png)

**Comment by abnerlee** [comment]
duplicate with #2658
