### ISSUE TITLE
is it possible to offer support for  legends of pictures?

### ISSUE THREAD

**Issue by luabish** [typora/typora-issues#3276]
After adding a picture into my markdown, maybe it's better to write a brief info right under the picture so that readers may easily know what this picture is mainly about.(I supposed this is called legend in word?)

I found that typora uses !()[] to add pictures, which allow us to modify the content between () ,but this content between () will not show itself unless this markdown is being edited.

So I think if typora may add support  for showing the picture's brief info both in markdown preview mode and exported pdf files (maybe more occasions)?

**Comment by abnerlee** [comment]
duplicate with #2957
