### ISSUE TITLE
Accents and other characters in math blocks are not in the correct font size

### ISSUE THREAD

**Issue by Nicolapps** [typora/typora-issues#3278]
Hello,

I noticed that when using accents (but also, some other special characters) in a math block, it appears too big or too small, according to the current zoom level.
 
<img width="500" alt="Screenshot" src="https://user-images.githubusercontent.com/7029582/74645842-f49bd480-5178-11ea-87a2-9e54edf8a804.png">

**Comment by abnerlee** [comment]
which OS? 

relates https://github.com/mathjax/MathJax/issues/764

**Comment by Nicolapps** [comment]
Sorry for not mentioning it, I’m using Typora on macOS.

**Comment by abnerlee** [comment]
It's still different on my macOS, so
- Which macOS/Typora version are you using?
- What's your Typora theme, did you zoom or changed the font size?
- Possible to attach the original text you use for the math block?

**Comment by Nicolapps** [comment]
Typora version: Beta 0.9.9.32.1 (latest)
macOS Version: 10.15.4 Catalina (latest)
Typora theme: the bug is there with all themes, including GitHub

Zoom level: I’m normally using a 16px font size with a 150% or so zoom level, but I was able to reproduce the bug with other zoom levels. It’s interesting to note that the higher the zoom level is, the more disproportionate the letters are (e.g. [400%](
https://user-images.githubusercontent.com/7029582/81218937-48cb8d80-8fdf-11ea-9cc8-94989df9d2a1.png), [67%](https://user-images.githubusercontent.com/7029582/81218970-5719a980-8fdf-11ea-883a-78d59a03ead4.png))

Sample text:
```
$$
\text{évènement},
\frac{\text{produits}}{\text{réactifs}}
$$
```

**Comment by abnerlee** [comment]
Looks fine in my test now

**Comment by Nicolapps** [comment]
Thank you for the fix, it looks much better now. However, it looks like the accented/special characters are a little bit too small compared to the regular letters. For instance, `é` appears smaller than `e`:

<img width="792" alt="Screenshot 2022-01-16 at 19 17 05" src="https://user-images.githubusercontent.com/7029582/149672548-8df0be4f-59f7-4e9a-ae02-0eba941b97d8.png">

Is this normal? Please take note that the appearance is still better with the recent fix, because now even if some characters appear to be too small, their size is always consistent with the zoom level. Previously, zooming in would increase their size disproportionately, and vice versa.

I'm using Typora v1.0.5 on macOS 11.6 Big Sur, with the default theme.
