### ISSUE TITLE
Absence of text align and order list children

### ISSUE THREAD

**Issue by Mumcio** [typora/typora-issues#328]
Order list children could be like:
1. Lorem ipsum
[indent]  1.1. Lorem ipsum
[indent]  1.2. Lorem ipsum
2. Lorem ipsum
[indent]  2.3. Lorem ipsum
[indent]  2.4. Lorem ipsum

Text-align (center, right) it will be good to be in typora.

**Comment by abnerlee** [comment]
Is it supported by any Markdown standards?

If not, we won't support it either
