### ISSUE TITLE
Wrong reference to copied image when containing `(` or `)`

### ISSUE THREAD

**Issue by MrHenning** [typora/typora-issues#3280]
Dear developers, awesome editor first of all :upside_down_face: 

I noticed that on Linux, v0.9.83(beta), when I drag-and-drop and image in the document, everything works as planned, the file is copied to the `.assets` folder as set in the settings.

*Except* if there are *parentheses* in the filename. The file gets copied anyway and the filename set a alternative text, but the reference to the image goes to the original location, *not* to the copied file in `.assets`. Other special characters seem to work fine.

Here, the **second** image is imported as the others, but badly references:
![image](https://user-images.githubusercontent.com/5331081/74724483-9afcde00-523c-11ea-8358-d2dfec3a0a11.png)

![image](https://user-images.githubusercontent.com/5331081/74724598-c2ec4180-523c-11ea-97c8-b295b0af3f44.png)

**Comment by abnerlee** [comment]
relates #1550

**Comment by abnerlee** [comment]
should be fixed
