### ISSUE TITLE
images stored in folders that have names starting with "." are not loaded

### ISSUE THREAD

**Issue by rezanid** [typora/typora-issues#3282]
Imaging the following file and folder structure:

- D:\wiki
- D:\wiki\home.md
- D:\wiki\.images
- D:\wiki\.images\sample.png

If you reference the image in home.md using the following markup, it won't be displayed.
````
This won't work!
![Sample image](.images\sample.png)
````
If I rename the ".images" folder to "images" and modify the reference in home.md to remove the "." it works.
````
This would work!
![Sample image](images\sample.png)
````

Typora Version: 0.9.83
Platform: Windows 10 64bit

**Comment by abnerlee** [comment]
should be fixed
