### ISSUE TITLE
File search functionality does not search inside symlink directories

### ISSUE THREAD

**Issue by eguendelman** [typora/typora-issues#3283]
Assume top level directory `A` with subdirectories `B` and `C`, and `C` is actually a symbolic link to a directory elsewhere on my file system.
If I open Typora in the top-level `A` directory and do a file search, it does not return any results that actually are found inside `C`.  It can only find results from `B`.
Is this expected behavior?  Can it be changed to also search inside symlink directories?
Thanks

**Comment by abnerlee** [comment]
Currently, there's no support for symlink


merge into #1881
