### ISSUE TITLE
Image Copy not working: "Apply above rules to online images"

### ISSUE THREAD

**Issue by gynet** [typora/typora-issues#3284]
Image Copy not working: 

I checked the settings "Apply above rules to online images", if I copy some web content to the editor, the images will still using url referencing instead of auto copying to the custom folder as I setup.  

Drag local file is working as expected. 
    Browser: Firefox 74
    OS: MacOS
    Using version Version 0.9.9.31.4

**Comment by abnerlee** [comment]
Can be reproduced by Chrome / Safari or other browser?

**Comment by T4erg** [comment]
**Reproduced in Chrome**
**Safari is WORK**

OS: MacOX 10.15.3 (19D76)
Browser: Chrome Version 80.0.3987.132 (Official Build) (64-bit)
Using version: Version 0.9.9.32.1 (4191)

**Comment by T4erg** [comment]
When I **restart both Chrome  and Typora**,  online images can save in local files.
