### ISSUE TITLE
export to html question

### ISSUE THREAD

**Issue by Liuzhj** [typora/typora-issues#3286]
![image](https://user-images.githubusercontent.com/14147011/75015662-1e7c3080-54c4-11ea-9fb9-ab33e1d18e88.png)

![image](https://user-images.githubusercontent.com/14147011/75015678-28059880-54c4-11ea-93d5-41555e94bea4.png)

what's wrong with typora? how to fix it ?

**Comment by Liuzhj** [comment]
this code in the html head, i don't  know why ?

this code in `c:\Program Files\Typora\resources\app\app\window\frame.js` also .

```
.typora-export li, .typora-export p, .typora-export, .footnote-line {white-space: normal;}
```

![image](https://user-images.githubusercontent.com/14147011/75015985-e3c6c800-54c4-11ea-952d-b71d641bf94f.png)

**Comment by abnerlee** [comment]
I'm not able to reproduce this, possible to send us (<hi@typora.io>) the sample *.md file?

**Comment by kinoute** [comment]
I have the same issue: Typora by default, when exporting with HTML with style, will incorporate its own style regarding some elements. For example for lists, it will use a class named `.typora-export li` which overrides the `white-space` property on our theme.

That leads to a HTML page with a different `li` style.

**Comment by abnerlee** [comment]
The `white-space` is controlled in Typora's preference panel, if `white-space` in the theme is used, then there will be a bug that the options about "whitespace" in preference panel not work.

You can use `.typora-export li` in your custom CSS to force override this
