### ISSUE TITLE
Change back to type over from insert mode in typora

### ISSUE THREAD

**Issue by Uzay-G** [typora/typora-issues#3287]
Hey I was using typora and noticed that my cursor suddenly turned to insert over typeover mode when I type.

Is there a shortcut to fixe this or is it not possible?
Thanks!

**Comment by abnerlee** [comment]
Press `Insert` key?

**Comment by jmattlandrum** [comment]
Same thing happened to me. I guess I must have accidentally hit the Insert key because pressing it fixed the issue. Just thought I would log it in case others report it.
