### ISSUE TITLE
Don't render #header as a h1 unless there is a space between the "#" and "header"

### ISSUE THREAD

**Issue by ssylvia** [typora/typora-issues#329]
Some other markdown editors allow you tag notes with hashtags.

```
# Hello World

Foo bar.

#tag
```

**Comment by vassudanagunta** [comment]
This request is consistent with [the CommonMark spec](http://spec.commonmark.org/0.25/#atx-headings)s, and Typora is supposed to follow the CommonMark standard. 

But Typora has also been good about opening people's "legacy" markdown files, e.g. for people switching to Typora with a large existing library of markdown files. So perhaps "Require space after ATX #" or "Use strict CommonMark" should be a Preference setting?

**Comment by abnerlee** [comment]
The problem may be many "legacy" markdown files use `#header` not `# header`...

**Comment by ssylvia** [comment]
Yep, a setting would be fine for me. Maybe under markdown preferences, just under header style.

**Comment by abnerlee** [comment]
We added a `strict mode` option in preference panel in newest update, enable it will force Typora to parse markdown more strictly including NOT parse `#headings` as headings.

**Comment by vassudanagunta** [comment]
@ssylvia @abnerlee I'd prefer that the setting was titled "GFM superset

**Comment by ssylvia** [comment]
@abnerlee Just tested and woks as expected. I agree with @vassudanagunta as `strict mode` may not be as intuitive.

**Comment by kareemjeiroudi** [comment]
Not sure if you can add hashtags, but you can for sure skip the header by typing '\' before the '#' like this:
\#HashTag
\#Fluent_Design
#Header
