### ISSUE TITLE
Empty space before mermaid diagram

### ISSUE THREAD

**Issue by Nyasaki** [typora/typora-issues#3295]
Hi, i noticed there is a lot of empty space before a mermaid diagram, which doesnt look that good while editing / exported.
![2020-02-25 07_56_52-Serializing Equipment md - Typora](https://user-images.githubusercontent.com/23500970/75222632-f2eb9580-57a4-11ea-818e-96e04feb6a72.jpg)

**Comment by abnerlee** [comment]
Can you post the mermaid source code?

And what's your theme, if it cannot be reproduce using builtin themes, it may be something wrong with your theme CSS file
