### ISSUE TITLE
Sidebar search doesn't seem to handle special characters correctly

### ISSUE THREAD

**Issue by thunze** [typora/typora-issues#3297]
**OS version:** Windows 10
**Typora version:** 0.9.84

So apparently the search option found in the sidebar of Typora doesn't handle words containing special characters correctly:

![search](https://user-images.githubusercontent.com/22795263/75264029-120f1500-57ef-11ea-9c2c-44c3347a5d15.gif)

This also applies if the "whole word" option is enabled. However other special characters seem to be handled differently. Here are some test cases:

`wörd` as a word in the editor **is not found** if entered in the search field.
The single character `ö` (as a word / separated by spaces) **is not found**.
The single unicode character U+273A (`✺`) as a word **is found**.
`test✺word` as a word (containing unicode character U+273A) however **is not found**.

Hope this helps! :)

**Comment by abnerlee** [comment]
should be fixed in new release
