### ISSUE TITLE
MAC : Failed to copy image to target folder after new update using copy image to custom folder.

### ISSUE THREAD

**Issue by astikanand** [typora/typora-issues#3298]
![typora_issue](https://user-images.githubusercontent.com/8958028/75283209-612d6800-5838-11ea-89a7-fc90188a2839.png)

I have recently updated typora and my image upload setting is "Copy image to custom folder" and "./assets". It was working completely fine but now giving error.

I feel after every update things are getting weird. Coz earlier natural ordering of folder was fine it was taking numericals at first but now it takes alphabetical at start.

Please have a look!

But Thanks a lot to you guys for such a wonderful project !!!!!!

**Comment by haccanri** [comment]
I also have this problem. After I updated to version 0.9.9.32, copying image to target folder always failed. I didn't figure out how to authorize the write access permission to typora. 

I'm happy to update to the newest version all the time but the latest two versions did have serious problems. For version 0.9.9.31.7, the bug that Typora will hang sometimes when click image or article margins drives me crazy. And this time, the important function about image management failed.

Hope you can fix it quickly and improve the software test pipeline. Thank you for the great software and we all hope it can keep the high quality as before and get better and better!

**Comment by abnerlee** [comment]
@haccanri @astikanand 

What's the path of your md file, and what is the image folder path you set in preferences panel?

**Comment by abnerlee** [comment]
We will fix this. 

You could hot fix this by change "folderName" to "./folderName"

**Comment by haccanri** [comment]
> @haccanri @astikanand
> 
> What's the path of your md file, and what is the image folder path you set in preferences panel?

The image folder path I set is "./images", it doesn't work.

Currently I downgrade it to version 0.9.9.31.6, which works well.

**Comment by abnerlee** [comment]
should be fixed in 0.9.9.32.1, could you check if it's working?

**Comment by haccanri** [comment]
> should be fixed in 0.9.9.32.1, could you check if it's working?

It works now. Thanks so much for the quick response.

**Comment by abnerlee** [comment]
relates #3271
