### ISSUE TITLE
Line-break in tables

### ISSUE THREAD

**Issue by zttt** [typora/typora-issues#33]
Currently there is no way to line-break in a table since Typora is ignoring `<br/>`.
Is it possible to support this feature in future release?

**Comment by goto100** [comment]
+1

**Comment by harper357** [comment]
This would be a great enhancement/feature. Atom seems to do this just fine (for example).

**Comment by vassudanagunta** [comment]
Clearly GitHub handles it:

| Fruit  | Vegetable | Grain |
| ------ | --------- | ----- |
| apple  | eggplant  | rice  |
| tomato <br> (not a vegatable!) | spinach   | wheat |
| banana | squash    | oat   |

I confirmed that the above table works in Atom as well.

**Comment by vassudanagunta** [comment]
To be consistent with how Typora supports line-breaks in regular paragraphs, `SHIFT` `RETURN` rather than having to manually enter `<br>` should be supported.

**Comment by goto100** [comment]
It seems typora ignores **all** html in markdown, not only `<br />` in table.

**Comment by vassudanagunta** [comment]
Supporting HTML should be a separate feature request. Typora added line-breaks for regular paragraphs recently (by pressing `SHIFT` `RETURN`, not entering HTML), it simply needs to do the same within tables.

**Comment by leafiy** [comment]
+1

**Comment by alphaqiu** [comment]
![image](https://cloud.githubusercontent.com/assets/1404566/20293445/8e763bb4-ab31-11e6-80ed-0855aace2195.png)
when i pressing SHIFT RETURN, it generate and go to next row. pressing SHIFT RETURN break line not work for me.

**Comment by Jasonx0716** [comment]
+1 better add this feature

**Comment by CarloGiuliano** [comment]
+1 It would be of great help to make the table contents more readable

**Comment by bixb0012** [comment]
+1 If I could add only a single enhancement request for Typora, this might just be it.  Sure, inserting `<br/>` works when printed or exported, but not having actual line breaks within table cells makes for a mess with larger content.

**Comment by ecamy** [comment]
I press shift+return, then add new row, why?

**Comment by abnerlee** [comment]
Table in markdown does not support line break. An acceptable solution os to support and render `<br/>` tag.

**Comment by AlexPasternak** [comment]
In this case it seems like what folks are asking for is a keyboard combination that would insert the br tag. This is something I do very often in tables, and having to manually type it out, or come up with a custom solution for each user, doesn't seem as nice.

**Comment by ecamy** [comment]
I think it's really important for a table. hope add the function in the future. I used typora to write the note from the day before yesterday, it is wonderful for all of us.

**Comment by westfish** [comment]
from Jan 2016 to May 2017, the problem still exists,<br>or shift+enter(windows) is  not worked to break lines in a table

**Comment by nickcorona** [comment]
Problem is still not fixed on Linux. I still have no idea how to start a new line in a table cell.

**Comment by swen624** [comment]
+1

**Comment by Rocking80** [comment]
I also need this feature very much! Since so many users needs this support, why no one take this into action in almost 2 years?!

**Comment by jiangfengming850811** [comment]
+1

**Comment by abnerlee** [comment]
Please use `<br/>` (https://github.com/typora/typora-issues/issues/439)

Or hit shift+return. This is supported now in the last update.

**Comment by cee1** [comment]
os x 0.9.9.12

<br /> not renders to a line-break while exporting to PDF or HTML

**Comment by abnerlee** [comment]
@cee1 will be fixed in https://github.com/typora/typora-issues/issues/1180 soon

**Comment by fulldecent** [comment]
This is in the current released version:

![screen shot 2018-04-17 at 11 27 42 am](https://user-images.githubusercontent.com/382183/38847101-7efcf5da-4232-11e8-9b66-5dc83b6e4cce.png)

![screen shot 2018-04-17 at 11 28 24 am](https://user-images.githubusercontent.com/382183/38847104-81083286-4232-11e8-9821-27e49fd35469.png)

**Comment by mifas** [comment]
How to hide the `<br />` tag from Markdown?

**Comment by Kiiiwiii** [comment]
> How to hide the `<br />` tag from Markdown?

Typora > Preference > Markdown > Visible \<br /> (uncheck)
