### ISSUE TITLE
CSS Styling for Diagrams?

### ISSUE THREAD

**Issue by n3bulous** [typora/typora-issues#330]
I'm finding my sequence diagrams with Mermaid are too wide for printing (e.g. more than 4 actors using the Github theme).  Mermaid can style diagrams with a stylesheet.  What are your thoughts on adding support for some form of scaling similar to how fonts are scaled with em?

Maybe something like:

```
sequenceDiagram
    scale .9
```

or something like `scale fit`? The latter might be difficult...

**Comment by abnerlee** [comment]
Mermaid should be auto fit when print, so I will consider it as a bug.

For zoom mermaid, you could add custom css

```css
.md-diagram-panel {
 zoom: 80%;
}
```

and check http://support.typora.io/Add-Custom-CSS/

**Comment by abnerlee** [comment]
And you should report to <https://github.com/knsv/mermaid> about the `scale` syntax

**Comment by n3bulous** [comment]
What format does Typora use to render the diagram?  Mermaid SVG files scale properly when included as a file.

**Comment by abnerlee** [comment]
> What format does Typora use to render the diagram?

The default one, should be SVG.
