### ISSUE TITLE
Crashes when opened from explorer

### ISSUE THREAD

**Issue by CovalenceSTU** [typora/typora-issues#3300]
After updating to the latest Typora version, the app crashes if i try to open a .md file in Windows Explorer. Typora will open, flash improperly formatted text (which is normal while it loads the theme), go black, flash it several more times, and then crash as soon as the theme correctly loads. Opening the app through the Start menu and then opening the file through the Open dialog works, however.

I have Windows 10 v1909 and Typora 0.9.84 with Night theme.

EDIT: The app now crashes when opened from the Start menu as well, even though it worked the first time.

**Comment by abnerlee** [comment]
@CovalenceSTU Are you open a large file, will open a smaller one also trigger this issue?

**Comment by abnerlee** [comment]
Fixed in 0.9.85

**Comment by CovalenceSTU** [comment]
> @CovalenceSTU Are you open a large file, will open a smaller one also trigger this issue?

I just opened a 2kB file and it worked fine. All my other .md files were about 8kB.
