### ISSUE TITLE
0.9.84 beta upgrade creating large spaces between bullets and spans

### ISSUE THREAD

**Issue by orbisdoc** [typora/typora-issues#3301]
Hi-
I just upgraded. My document has bullet points followed by some spans with texts. It renders as a large space now.

![typoraSpacingFeb2020](https://user-images.githubusercontent.com/50410801/75288070-8f378b80-57e9-11ea-83e6-8549e29e3796.png)

**Comment by abnerlee** [comment]
Possible to send us (<hi@typora.io>) a sample file?

**Comment by orbisdoc** [comment]
file sent

**Comment by abnerlee** [comment]
should be fixed in 0.9.84

**Comment by orbisdoc** [comment]
No. this occurred when I was prompted to upgrade to 0.9.84 that is what I’m running
Thanks,
James

**Comment by orbisdoc** [comment]
Updated to 0.9.85 fixed it.

**Comment by abnerlee** [comment]
> Updated to 0.9.85 fixed it.

Yes, typo ~~0.9.84~~ -> 0.9.85
