### ISSUE TITLE
Inconsistence when there are backquotes in header in 0.9.84 (beta)

### ISSUE THREAD

**Issue by tan-wei** [typora/typora-issues#3303]
For example, the content shows inconsistence in *Source Code Mode* and *Normal Mode*:
```markdown
## Use the `\v` Pattern Switch for Regex Searches
```
![图片](https://user-images.githubusercontent.com/28227509/75308102-76ca7e00-5888-11ea-91de-197c502e4415.png)
![图片](https://user-images.githubusercontent.com/28227509/75308118-7e8a2280-5888-11ea-9883-1087bbd7198c.png)

**Comment by tan-wei** [comment]
Seems that the `\` may cause the error.

**Comment by abnerlee** [comment]
merge into #1638
