### ISSUE TITLE
New version crashed (0.9.84, windows)

### ISSUE THREAD

**Issue by Steven-Shixq** [typora/typora-issues#3304]
The new version of Typora (0.9.84, windows) crashed, does anyone have such a problem?

**Comment by FXWHS** [comment]
(Sorry,I just know a little English)Excause me,sir.When I use Typora(0.9.84)(win8.1 x64),Typora suddenly crash.When I try again ,Typora crash again.I can't solve this problem,could you help me?

chinese:你好，我在使用Typora时，软件突然闪退了，无论我怎么调试软件，软件还是一直闪退，我没法解决这个问题，所以麻烦您排除一下BUG，谢谢！

**Comment by ZhaoWenHao1** [comment]
Hi，bro, so did I, where can I download the old version?
chiness: 老哥，我也是，请问哪里能下载到旧版本吗？

**Comment by abnerlee** [comment]
Fixed in 0.9.85

**Comment by abnerlee** [comment]
#3300
