### ISSUE TITLE
deb repository URL is wrong

### ISSUE THREAD

**Issue by muzikmoe** [typora/typora-issues#331]
URL
 ```
sudo add-apt-repository 'deb https://typora.io linux/'
```
given on the [linux download page](https://www.typora.io/#linux) should be 
```
sudo add-apt-repository 'deb https://typora.io ./linux/'
```
please fix it.

**Comment by abnerlee** [comment]
@muzikmoe 

I'm not familiar about this, so I just try and find the previous one on Ubuntu is working. Do you have any related documents on this issue, or have you failed with the previous one on certain Linux distribution based on Debian?

**Comment by muzikmoe** [comment]
@abnerlee 
The previous URL works now, but yesterday I tried it on Linux Mint 18 cinnamon, it failed, and when changed it to `./linux/`, works.

**Comment by ketzacoatl** [comment]
FWIW, I ran into this on Ubuntu 14.04. When I used the documented install, I hit:

```
ᐅ sudo add-apt-repository 'deb https://typora.io linux/'
...
Reading package lists... Done
W: Conflicting distribution: https://typora.io linux/ InRelease (expected linux but got )
```

.. yet it seems to be partially correct, as it seems apt can at least find the `typora` package: 

```
ᐅ sudo apt-get install typora
Reading package lists... Done
Building dependency tree       
Reading state information... Done
...
The following NEW packages will be installed:
  typora
0 upgraded, 1 newly installed, 0 to remove and 135 not upgraded.
Need to get 35.6 MB of archives.
After this operation, 130 MB of additional disk space will be used.
0% [Working]
E: Failed to fetch https://typora.io/./linux/typora_0.9.20_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

But the error at the end confirms the setup is not 100% correct.

The same thing happens when I use the update suggested in this ticket.

I'm not quite sure what is wrong with the apt hosting, but I would first suspect a change is needed there. Given this, I'd recommend re-opening this ticket, maybe also renaming the ticket to include "ubuntu" or "linux" and "install" in there somewhere (I searched through issue tracker and almost submitted a dup before finding this one by chance).

I'm excited to take typora for a spin, it looks like a really great project!

**Comment by ketzacoatl** [comment]
@abnerlee, I have seen mention that the linux release is tested on Ubuntu. Is those tests run on 14.04 or 16.04, or something else?

**Comment by abnerlee** [comment]
@ketzacoatl honestly I'm new to maintenan a deb repo, could you try `run apt-get update` before install typora.

BTW, I tested only on Ubuntu 16.04

**Comment by ketzacoatl** [comment]
@abnerlee, sorry, my comment was incomplete, the `apt-get update` was where I first saw the errors I noted. I have updated my comment to correct that.

**Comment by ketzacoatl** [comment]
Is it possible to download a binary/executable? I could not find a release. Installing through apt is not working.

**Comment by abnerlee** [comment]
```
W: Conflicting distribution: https://typora.io linux/ InRelease (expected linux but got )
```

It is warning, not error.

```
E: Failed to fetch https://typora.io/./linux/typora_0.9.20_amd64.deb  Hash Sum mismatch
```

it is error when you run `apt-get install typora`. And run "apt-get update" can update the hash sum.

You could also download from `https://typora.io/./linux/typora_0.9.20_amd64.deb` directly

**Comment by americogobbo** [comment]
Is possible to have a link to download the last release as .deb?
The link above doesn't working.
thanks

**Comment by humanfactors** [comment]
What is the cause of this issue? I am still getting:
`W: Conflicting distribution: https://typora.io ./linux/ InRelease (expected ./linux/ but got )`
after having followed the directions on the official site.

**Comment by orschiro** [comment]
@humanfactors I am affected by this as well using the command from the website.

Have you found a solution?

**Comment by vickychijwani** [comment]
I was able to get it working simply by downloading and extracting this tar.gz: https://typora.io/linux/Typora-linux-x64.tar.gz. Found that link [here](http://support.typora.io/Typora-on-Linux/).

**Comment by davidljung** [comment]
Changing the entry in /etc/apt/sources.list to ```deb https://typora.io/linux ./``` fixes it for me.

**Comment by davidljung** [comment]
I think the only way is to ignore the warning, install, then remove the repo from ```/etc/apt/sources.list```.  Then you won't get automatic updates, but can always uncomments it to update manually any time.

**Comment by timschroedernet** [comment]
The warning can be silenced by using `deb https://typora.io/linux ./` in `/etc/apt/sources.list`.

**Comment by xulis** [comment]
https://typora.io/#linux

This page has not been changed
