### ISSUE TITLE
A error occured while installing the newest version. 0.9.85

### ISSUE THREAD

**Issue by daydreaming666** [typora/typora-issues#3310]
The setup program raise an error of access denied.
![图片.png](https://i.loli.net/2020/02/27/c1JTNBuUhZmx4t6.png)

It happens either install or update.

windows 10 enterprise 18363.592

**Comment by abnerlee** [comment]
Could you check if the installer have write access to your install destination?

**Comment by daydreaming666** [comment]
I think it does have write access, because i can install the older version 0.9.83 successfully . The error just happens when i want to update or install the new version. Also tried run the installer as administrator, not works.

**Comment by abnerlee** [comment]
Another cause may be the file / folder is still in use, maybe try quitting / killing Typora before open the installer, or restart the PC.
