### ISSUE TITLE
upload image support url is wrong

### ISSUE THREAD

**Issue by cjM00N** [typora/typora-issues#3311]
Thanks for your effort to support picgo!!!
![](https://img-cjm00n.oss-cn-shenzhen.aliyuncs.com/20200227133245.png)
when I click the url above, I got this url and a `404 not found`
https://support.typora.io/upload-image/
the true url is 
https://support.typora.io/Upload-Image/

and when I copy an image in copyboard to typora, I have to click the upload image option, can I avoid it? 
Thanks again.

**Comment by abnerlee** [comment]
added redirect link for https://support.typora.io/upload-image/

**Comment by lzskyline** [comment]
You can find an example on:
https://www.lzskyline.com/archives/87/
