### ISSUE TITLE
How can I open a *.md file in Windows CMD using Typora directly?

### ISSUE THREAD

**Issue by tanjuntao** [typora/typora-issues#3312]
Hi, I'm using a Windows 10 OS and a CMD prompt, and I want to open a *.md file in any directory using Typora  just the way like Vim.  I have added the `bin` directory to Environmental Variable `Path`, but when I use command like this in CMD:
``` 
typora xxx.md
```
Typora will open a new blank file instead of the opening `xxx.md`.

So can somebody tell me how I can get this problem fixed?

**Comment by abnerlee** [comment]
see #963 and http://support.typora.io/Use-Typora-From-Shell-or-cmd/
