### ISSUE TITLE
Tab title issues

### ISSUE THREAD

**Issue by owl10124** [typora/typora-issues#3314]
When I have multiple tabs open and add a tab with Cmd+T, the tab is added to the right of the current tab, but the title is appended to the **end** of the titles.

For instance, if I am on tab C and Cmd+T:
A B C D --> A B *C* D Untitled, where filename D actually maps to C and Untitled to D.

This effectively causes an off-by-one error between the tab titles and actual documents.

I am on version 0.9.9.31.6 (4047), MacOS Catalina.

**Comment by abnerlee** [comment]
I'm not able to reproduce this, can this be reproducible on 0.9.9.32?

**Comment by owl10124** [comment]
Doesn't occur on .32, thank you.
