### ISSUE TITLE
OS X Catalina: Typora Freezes Indefinitely (2) 

### ISSUE THREAD

**Issue by GindaChen** [typora/typora-issues#3316]
**Typora Version**: 0.9.9.32.1 (4191)
**OS**: macOS Catalina 10.15.3

Same symdrone as #3279. 
I insert a few pictures, and with a certain probability, Typora freezes when save. 
On average 3-5 save will trigger a freeze.
CPU% is not very high (0.6%), and memory usage is low.

**Comment by abnerlee** [comment]
@GindaChen Is it same with #2895 that save panel will never show?

**Comment by GindaChen** [comment]
I haven't try what #2895 described. I can try. So far it is just the normal save that triggers the freeze.

**Comment by dbj** [comment]
I just downloaded the latest Typora (Version 0.9.9.32.1 (4191)) and it hung for a long time upon opening. I took a spindump (attached).  When the spindump was done, Typora had become responsive again.

I'm running macOS 10.15.4 (19E287) Catalina.

[typora_spindump.txt](https://github.com/typora/typora-issues/files/4631702/typora_spindump.txt)

**Comment by abnerlee** [comment]
Does this still happens in latest version?

**Comment by abnerlee** [comment]
And what is your file system, is it same as #3496?
