### ISSUE TITLE
Image folder is put in $HOME instead of `./` folder

### ISSUE THREAD

**Issue by AngieC96** [typora/typora-issues#3317]
I'm using Ubuntu 18.04 Bionic Beaver and in Typora I've set the option:
        Copy image to custom folder
and then I've specified the path `./.images/${filename}`.

But since the new update Typora is no longer putting the folder `.images` in the directory of the `.md` file, it is putting it in the folder `$HOME` (but it always creates an hidden folder `.images` and then inside it another folder called as the file name).

I've especially noticed this behaviour since I was working on a file with some images already put in the right folder, while after the update Typora created a new folder in `$HOME`.

**Comment by ugurbolat** [comment]
have the same issue...

https://github.com/typora/typora-issues/issues/2546#issuecomment-592479949

**Comment by abnerlee** [comment]
Which Typora version 0.9.84 or 0.9.85?

**Comment by AngieC96** [comment]
Yes sorry, I have the version 0.9.85

**Comment by ugurbolat** [comment]
version 0.9.85

**Comment by abnerlee** [comment]
relates #3271

**Comment by LeeReindeer** [comment]
have the same issue on `Copy image to custom folder` version 0.9.85，It copy images to `$HOME` instead of `./` for both local and online images. When download and execute typora binary file manually it'll copy images to the binary file folder.

**Comment by abnerlee** [comment]
should be fixed in 0.9.86

**Comment by AngieC96** [comment]
Yes now it's perfect, thank you really much!
