### ISSUE TITLE
Can't 'Restore last closed file and folders'

### ISSUE THREAD

**Issue by Hdming1994** [typora/typora-issues#3319]
![image](https://user-images.githubusercontent.com/32196979/75625584-6f91d000-5bfa-11ea-9ca4-d8c65ec68ee0.png)

**Can't** '**Restore last closed file and folders**', '**Restore last closed folders**' either.

**Comment by yenson-lau** [comment]
Facing the same issue.

**Comment by abnerlee** [comment]
#3315
