### ISSUE TITLE
Any plan to distribute i686 binaries for Linux? (x86 32bits)

### ISSUE THREAD

**Issue by ryukinix** [typora/typora-issues#332]
I'm using the amd64 version on ArchLinux and really works great. Just need type `yaourt -S typora` and all is done. But unfortunelly I can't use in my another machine whose has a legacy hardware i686 arch... 

Well, I really thinks is wonderful the all principle of Typora and the instantly feedback with all the plugins, mainly the math inline feature (oh man, this is really freaking awesome!!!), but makes me a little sad cannot run in my i686 manjaro :(

Thanks for attention, anyway. Good job for you, guys.

**Comment by abnerlee** [comment]
Typora for Linux/Windows is based on Electron, I do not think they have a i686 build (https://github.com/electron/electron/releases)

And, typora use web technology, so I guess the performance won't be good on legacy hardware :(

**Comment by ryukinix** [comment]
:( sad...
