### ISSUE TITLE
Switch from CodeMirror to another code block formatter

### ISSUE THREAD

**Issue by RokuKent** [typora/typora-issues#3322]
CodeMirror is not extending their language support in their basic setting, see:
https://github.com/codemirror/CodeMirror/issues/6165#issuecomment-593614855

Recommend to switch to another code block formatter that allows adding new language format types to their basic setup.

**Comment by abnerlee** [comment]
It would be a big task, we do not have plans for it.

Also, CodeMirror is open source and supports plugins to extend other language support. Just write new plugins for new languages would be fine
