### ISSUE TITLE
global search does not work issue 

### ISSUE THREAD

**Issue by simpsonys** [typora/typora-issues#3324]
This is report about for windows. 
https://github.com/typora/typora-issues/issues/2282

I think MAC version have fix this issue, But windows version does not fixed. Yet. 

is there any plan to fix this issue in windows version also ?

**Comment by abnerlee** [comment]
Could you provide a sample?

**Comment by abnerlee** [comment]
#3297

**Comment by simpsonys** [comment]
Every Korean Word find in global Search does not work. 

for example ) 검색 , 테스트 and so on.. 

I'm using version 0.9.86(beta) Windows x64 version. 

Thanks,

**Comment by abnerlee** [comment]
merge into #3297

**Comment by edward-leafmill** [comment]
love Typora :)

but, the function to search or replace Korean characters in Ubuntu 18.04 still does not work.

please, check this issue.

Thanks in advance
--
Edward

![typora](https://user-images.githubusercontent.com/5841983/127286983-0d1fde4b-742d-4eba-ae35-265218ccfb5f.png)

**Comment by abnerlee** [comment]
@edward-leafmill you mean in-app search, not global search, right?

Possible to provide examples?

**Comment by edward-leafmill** [comment]
> @edward-leafmill you mean in-app search, not global search, right?
> 
> Possible to provide examples?

Thanks for your reply.

I upload a gif file related to this issue.

When searching with Ctrl+F in the text, if you type Korean on the keyboard and press Enter, the search does not work. However, you can see that previously searched keywords can be searched on the gif

![typora_korean_search_problem](https://user-images.githubusercontent.com/5841983/128988921-7d7118dd-8006-495a-9ce9-dc83d8b3602c.gif)
.
