### ISSUE TITLE
Can we choose which tag to pre-render?

### ISSUE THREAD

**Issue by Kimi-Arthur** [typora/typora-issues#3325]
I see that tags like `<ruby>`, `<span>` are nicely pre-rendered while editing. I sometimes use `<pre>`, which is not. I understand pre-rendering everything may be a problem for user experience. But typora can allow us to choose the tags we want to pre-render, it would be quite nice. Thanks!

**Comment by abnerlee** [comment]
maybe it is #1939 which you are looking for?
