### ISSUE TITLE
Cannot render code blocks between list items correctly in Source Code Mode!

### ISSUE THREAD

**Issue by ypji** [typora/typora-issues#3326]
https://gist.github.com/ypji/b3e5f0bca0ac0a2d94f70dff6c90f8d3

OS Version: Windows 10.0.18363.657
Typora Version: 0.9.86(beta)

![image](https://user-images.githubusercontent.com/15951653/75979925-7d0dc980-5f1c-11ea-84ff-4fd7555617ba.png)

**Comment by abnerlee** [comment]
#1638
