### ISSUE TITLE
PicGo-Core Image Upload uses deprecated API version (v1) 

### ISSUE THREAD

**Issue by rmon-vfer** [typora/typora-issues#3327]
When trying to test the PicGo Upload feature using the `test` feature within the Image section in typora settings. Typora runs the following:
```
@chcp 65001 >nul & cmd /d/s/c C:\Users\ramon\AppData\Roaming\Typora\picgo\win64\picgo.exe u "C:\\Users\\ramon\\AppData\\Local\\Temp/typora-icon2.png" "C:\\Users\\ramon\\AppData\\Local\\Temp/typora-icon.png"
```
Which outputs the following:
```
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming...
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading...
[PicGo WARN]: failed
[PicGo ERROR]: Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.
```
As far as I can tell, the only viable solution would be rewritting the API handler to adapt to the new version.

**Comment by Molunerfinn** [comment]
For now you can use the `picgo-plugin-smms-user` to use the smms v2.

The next version of picgo-core will support smms v2. I don't think this is a problem with typora.

**Comment by Molunerfinn** [comment]
Install and setup [smms-user](https://github.com/xlzy520/picgo-plugin-smms-user) plugin. Please register the smms and get the auth token.
```
npm install picgo -g
picgo install smms-user
picgo set uploader smms-user
```
![image](https://user-images.githubusercontent.com/12621342/76135700-7d18e100-6064-11ea-87cf-372a6436765a.png)

Use the uploader

```
picgo use uploader
```

![image](https://user-images.githubusercontent.com/12621342/76135715-a5084480-6064-11ea-8842-b4798ef15888.png)

Choose `smms-user`

Done.

**Comment by Molunerfinn** [comment]
If you use the `picgo.exe` provide by Typora, you can also use the `install` command.

**Comment by lzskyline** [comment]
https://www.lzskyline.com/archives/87/
