### ISSUE TITLE
Feature Request - Suggestions when linking files

### ISSUE THREAD

**Issue by Nabelsen** [typora/typora-issues#3328]
When creating the link between files` [NAME](FILENAME) `I would be very happy if you could create a drop-down list of suggestion when entering the `FILENAME` for the current folder. It will make the process of creating Zettelkasten notes faster and easier. The possibility to add automatic backlinking could also be a nice feature.

Thanks for your great work so far!

**Comment by abnerlee** [comment]
#2663 #1418
