### ISSUE TITLE
When pasting from Apple Notes: Subheading is not ### but just boldface

### ISSUE THREAD

**Issue by gandalfsaxe** [typora/typora-issues#3329]
Somehow you resolved Title and Headings from Apple Notes to be parsed as `#` and `##` headings when pasting, great! (https://github.com/typora/typora-issues/issues/1065). But the Subheading is now just boldface instead of proper `###` (third level heading. Would be great to have this fixed too!

Apple Notes:
![image](https://user-images.githubusercontent.com/12127864/76013326-053da000-5f18-11ea-8f43-6c2b5cdbfa0d.png)

Pasted into Typora:
![image](https://user-images.githubusercontent.com/12127864/76013337-08389080-5f18-11ea-8eb8-b726c76a08e2.png)

**Comment by abnerlee** [comment]
Apple Notes only provide the styled text not the formated info.

We cannot know if text is header or it is just normal text but bold and larger size. We can guess if the text is h1 or h2 because it is obviously larger, but for h3 it may be larger or smaller or same based on your font settings.
