### ISSUE TITLE
Typora hangs/freezes/crashes upon loading the first time in Windows 10

### ISSUE THREAD

**Issue by scannermobs** [typora/typora-issues#3332]
Since I've had Typora installed, so over the paste couple of versions, I've had a problem where the first time the app loads the window hangs with a non-blinking cursor and no interaction possible (although I don't actually get a message from Windows to say the app has crashed). I can right-click the app on the taskbar and click New which loads a new instance working correctly. From there I right-click the crashed instance and force close it. It happens 90% of the time, and clearly shouldn't be happening.

**Please note**: I don't think this is the electron bug, as the window displays correctly (ie not white or black), and has a cursor, but is totally frozen. Also, it does work correctly once the app is loaded a second time.

Thanks

**Comment by abnerlee** [comment]
#3019?
