### ISSUE TITLE
Can't upload image directly from the clipboard or web

### ISSUE THREAD

**Issue by Decmoe47** [typora/typora-issues#3333]
The images upload service I use is PicGo-Core. There is no problem inserting local images. But if I want to copy the image directly into Typora, or insert web images, the following error will appear.
![image](https://user-images.githubusercontent.com/55980717/76139945-64bebb80-6090-11ea-84d3-248e9033aed2.png)
Especially when I try to upload the web picture manually after the above error occurred, the following error will appear.
![image](https://user-images.githubusercontent.com/55980717/76140477-c5042c00-6095-11ea-9f0c-449f66ca856a.png)

**Comment by abnerlee** [comment]
#3331
