### ISSUE TITLE
Smart quotes don't work on Mac

### ISSUE THREAD

**Issue by hughbiquitous** [typora/typora-issues#3334]
Steps to reproduce:
* Verify "Smart Punctuation" is set to "Convert on Input" (restart if necessary)
* Type `"smart quotes" don't seem to be working`
* **Expected:** `“smart quotes” don‘t seem to be working`
* **Observed:** `"smart quotes" don't seem to be working`

Environment:
* macOS Catalina (10.15.3)
* Typora Beta 0.9.9.32.1 (4191)

Anecdotally, I _feel_ like this has worked before, but I'm not sure.

Screenshot:
![image](https://user-images.githubusercontent.com/67820/76150272-801ccd00-6076-11ea-8811-89b5137d9a3a.png)

**Comment by abnerlee** [comment]
Did you enable "Smart Quote" checkbox?

**Comment by hughbiquitous** [comment]
Ah, it never occurred to me to scroll down. Perhaps a UI feature indicating the property sheet doesn't end with "Smart Dashes"?
