### ISSUE TITLE
software interface disappears in some case

### ISSUE THREAD

**Issue by A-hoy** [typora/typora-issues#3335]
![3](https://user-images.githubusercontent.com/55936555/76157414-9775bc00-6143-11ea-9d1e-c111349380f2.gif)
As you can see above, the preferences interface disappears when i select any drop-down list every time. And it appears again when i minimize the window and restore it（double click it in the taskbar）.

![6](https://user-images.githubusercontent.com/55936555/76157681-07d20c80-6147-11ea-9238-0fa665d5fffd.gif)
Analogously, the editor interface will disappear in some case, the following steps could reproduce the issue:
1. open typora
2. just type anything for later viewing
3. create new window and type something
4. repeat step 3 and now we have 3 windows.
5. switch to the first windows and you will find the editor interface disappear. But if i try to minimize it and restore it, the editor interface will appear.

This issue could appears even if create 2 windows, but not always.

typora version: 0.9.86
os version: Win10 - 32bit (10.0.18363.657)

**Comment by abnerlee** [comment]
please try https://github.com/typora/typora-issues/issues/2051

We will upgrade the Electron base which may help
