### ISSUE TITLE
image upload setting bug

### ISSUE THREAD

**Issue by Purple-CSGO** [typora/typora-issues#3336]
I've tried PicGo(app) int Typora. My PicGo is installed at `C:\Program Files\PicGo\PicGo.exe`. When testing, it shows errors like this:
```
failed to launch PicGo app: Command failed: C:\Program Files\PicGo\PicGo.exe
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

Then I manually add `"` to make it `"C:\Program Files\PicGo\PicGo.exe"`，it works fine. So I guess when typora recall PicGo, a pair of quotes is missed so it comes across an error when FilePath contains space  ` `

**Comment by LitterBrother** [comment]
Thanks your solution:-)

**Comment by abnerlee** [comment]
should be fixed
