### ISSUE TITLE
Auto Numbering for Headings → CSS Problem?

### ISSUE THREAD

**Issue by admin-teametry** [typora/typora-issues#3338]
Hi,

I followed the tipp on the support site: [https://support.typora.io/Auto-Numbering/](url)
For the result. please see the attached screenshot. Anny ideas how to fix this in CSS?

Thanks Andreas

![Screenshot 2020-03-08 at 12 16 43](https://user-images.githubusercontent.com/22169059/76161857-98085580-6137-11ea-9f42-1c81f0e4a86b.png)

**Comment by abnerlee** [comment]
I'm closing since we do not offer detailed help on specific CSS customization request, you could achieve CSS related issue by tweaking the CSS content.

Also, for CSS issue, we cannot get the existing CSS content or dom selector from a screenshot.
