### ISSUE TITLE
Save and Auto-Save silently fails (during pending update 0.9.83-->0.9.85)

### ISSUE THREAD

**Issue by NanashiNoGombe** [typora/typora-issues#3339]
**Running: Typora 0.9.83(beta) on Linux but Typora 0.9.85(beta) installed**

I had inspiration and alt-tabbed into Typora. Under a pre-prepared folder, I created a new file and began writing. I noticed that spellcheck wasn't responding but decided to deal with this later (spellcheck functions if I restart the application for an undetermined amount of time; less than a day).

**Logs reveals that there are no auto-save syncs**. But a manual save I did half-an-hour in registered a sync. The file up until this point was saved. The following 6 hours of work did not sync despite auto-save and manual saves (I manually save every time I start a new section or leave the desk).

**When I hit Ctrl+S, the asterisk prepending the title disappears, despite no save.**

I only discovered this because I had to restart the application to get spellcheck working again as I neared the end of writing. I hit Ctrl-S and checked, double-checked, and triple-checked that the asterisk was gone then hit X to close.

On restart, the previous 6 hours of work was lost with only 30 lines or so saved. I tried recovery, checking drafts, backups, etc. They only contained the same work as the savefile. The work was lost and was never written to file. I checked my hourly filesystem backups to confirm.

Edit: On double-checking the logs, the original file was never saved, even on creation. The small amount that was recovered was from drafts.

_Use Case: I use this as a note-taking application for writing tasks. Creativity comes in bursts and it can be weeks or months between additions but the application is always running and available. I don't close applications or reboot my system unless there is a problem._

**Comment by abnerlee** [comment]
What's your Linux distribution and did you enable "auto-save" on preferences panel?

**Comment by NanashiNoGombe** [comment]
Linux Mint 18.3 Cinnamon

Auto-save is enabled
I have also modified the conf.user.json
"autoSaveTimer" : 1, // Deprecidated, Typora will do auto save automatically. default 3 minutes

The logs show: 
ondragstart //document creation on 24/02/2020
focus & blur //typing for 6 hours on 08/03/2020 (and for a few times on days in between)
switchDocument & addRecentDocument //when referring to other documents
before-quit & will-quit

no lastSync

My last lastSync was on 22/02/2020. Work since then hasn't been saved, and only a small part of one document was available in recovered drafts.

**Comment by abnerlee** [comment]
may relates #3376
