### ISSUE TITLE
Math formulas in exported PDF files unselectable

### ISSUE THREAD

**Issue by jleaves** [typora/typora-issues#3340]
I really enjoy using Typora. It's definitely one of the best Markdown editors on computers, and its math support is really incredible.

One small issue: math formulas in the exported PDF files is not selectable. This is especially frustrating when the paragraph contains a lot of math symbols.

To be more clear, an example. A simple paragraph as follows:

> Suppose there are $N$ balls in a box. $M$ of them are blue, the remaining ones are red.

Then in the exported PDF, "N" and "M" are shown as images, without embedded text. When you select the paragraph in the exported PDF, only the following will be selected:

> Suppose there are balls in a box. of them are blue, the remaining ones are red.

This is really bad when you want to copy and paste the paragraph in the PDF. It would be greate to support the selectablity of math formulas in Typora-exported PDF files.

Version information that may be helpful:  
Typora: 0.9.86  
OS: Windows 10

**Comment by abnerlee** [comment]
#414

We don't support this. It's difficult to represent a math object like \sqrt{b^2} in plain texts
