### ISSUE TITLE
It's quite inconvinient that swicthing from source code mode to normal code makes the cursor locates at the beginning of the current file

### ISSUE THREAD

**Issue by tan-wei** [typora/typora-issues#3341]
It is better that the cursor will locate in the current location instead of the beginning of the file. Just a suggestion. Thanks!

**Comment by tan-wei** [comment]
BTW, the version is `0.9.86 (beta)`.

**Comment by abnerlee** [comment]
should be, how to reproduce this?

**Comment by abnerlee** [comment]
Can confirm this, it is a bug

**Comment by tan-wei** [comment]
Ok. I create a simple gif here:
![Typora Issue](https://user-images.githubusercontent.com/28227509/76695877-766f1700-66bf-11ea-847b-8d46d1565830.gif)

**Comment by abnerlee** [comment]
should be fixed

**Comment by potoo0** [comment]
Still hava this torturous bug.
Every time I paste as plain text or exit source code mode, the view will jump to the top.

gif demo:
- paste_as_plain_text:
  ![paste_as_plain_text](https://user-images.githubusercontent.com/34411681/90218306-031c2d80-de36-11ea-9e63-c005f9d72698.gif)
  - exit_source_code_mode:
  ![exit_source_code_mode](https://user-images.githubusercontent.com/34411681/90218326-16c79400-de36-11ea-968f-31cf712fecca.gif)

**Comment by abnerlee** [comment]
#3696

**Comment by dlvakalucifer** [comment]
Happens also when editing in a table via context menu: `right click` and `Bold` for example
