### ISSUE TITLE
folder for exporting files

### ISSUE THREAD

**Issue by rclUPC** [typora/typora-issues#3342]
Hi, 
In Ubuntu, if a file is opened, edited and then exported (to PDF, for instance), `Typora` open by default the  `HOME` folder. It is quite annoyance then to navigate until the `.md` file folder. It could be convenient if, when exporting, the program offers the same folder where the markdown file is.
By the way, congratulations. I *love* the program.
Regards
Robert

**Comment by abnerlee** [comment]
#407
