### ISSUE TITLE
Feature request: two column layout (or allow full markdown in tables)

### ISSUE THREAD

**Issue by JojoSc** [typora/typora-issues#3349]
Having the option to choose a two column layout would make Typora more suitable to write technical papers. Unfortunately right now the full range of markdown is not support within tables, so it's not possible to work around this at the moment.

**Comment by vassudanagunta** [comment]
Rendering to two columns is a presentation issue, not a content issue. Markdown is about content.

If you are rendering to HTML, you can use CSS to format the output in columns.

**Comment by abnerlee** [comment]
Uhh, I don't think Markdown would support this natively or easily.

**Comment by EugeneTarasenko** [comment]
> Uhh, I don't think Markdown would support this natively or easily.

Notion does support it. Typora could also do it.

**Comment by NorHei** [comment]
A workaround may be using reveal JS for Display and then print whith the browser. 
https://revealjs.com/

If you use paged.js for PDF export , i think it had a Multicolumn option as well.   
https://pagedjs.org/
