### ISSUE TITLE
Bold text inside code fence

### ISSUE THREAD

**Issue by g3blv** [typora/typora-issues#3350]
Is it possible to make text bold or highlight text inside a code fence?
 
I've done some searches and tested below but had no luck.

```
Making text **bold** inside code fence
Making text <b>bold</b> inside code fence
<pre>Making text <b>bold</b> inside code fence</pre>
<mark>Highlight</mark> text inside code fence
```

**Comment by vassudanagunta** [comment]
No it is not. The point of a ***code*** fence is that it is code, not prose. Code by definition is rendered *as-is*, per Markdown spec. (Some Markdown renderers, including Typora, offer *syntax highlighting*, but that is based on the syntax, not manual formatting of any tokens.)

Instead use a `block quote`.

**Comment by AlexPasternak** [comment]
I do agree that sometimes I want both code highlighting _and_ a way to bold or highlight a part of that code to draw your eye to it. Books do that all the time, after all. But I didn't think there was a standard MD way to do it. It'd be helpful, however.

**Comment by vassudanagunta** [comment]
I tried to do a web search for a `syntax highlighter` that supported `highlighting` parts of the code, but that is an impossible web search! 🤪

**Comment by vassudanagunta** [comment]
@AlexPasternak Do books do that *all the time*? In my experience, on the web at least, attention to portions of code is usually made by extracting that portion and showing only them in a targeted `code block`.  As one might do in a [Jupyter notebook](https://nbviewer.jupyter.org/github/gibiansky/IHaskell/blob/master/notebooks/IHaskell.ipynb).

**Comment by AlexPasternak** [comment]
Here's an example from my current [Typescript book on OReilly](https://learning.oreilly.com/library/view/programming-typescript/9781492037644/ch05.html). Very clear that `add` is a new method being discussed after `has`, which already has been.

<img width="708" alt="2020-03-11 9 58 19 AM" src="https://user-images.githubusercontent.com/1819485/76424686-f2dfbe00-637e-11ea-90e6-b5c1a0129190.png">

**Comment by vassudanagunta** [comment]
@AlexPasternak Out of curiosity I looked into OReilly's publishing platform. They support AsciiDoc instead of Markdown. Even AsciiDoc doesn't support this, so [you have to write HTML, which is supported through HTML passthrough blocks](https://docs.atlas.oreilly.com/writing_in_asciidoc.html#code_explanation): 

> ### Inline formatting within code
>
> If you want to use inline formatting in code—in particular, to specify typographical conventions such as bold or italic—you can do so by using an HTML passthrough block (see Passthroughs for an explanation of passthroughs). Here’s the markup to use a passthrough with the HTML element `<pre>`:
> ```
> ++++
> <pre data-type="programlisting">hostname $ <strong>date</strong>
> <em>Sun</em> Apr  1 12:34:56 GMT 1984</pre>
> ++++
> ```

I don't have time to figure out how passthrough blocks are implemented and whether it can be replicated in CommonMark or Typora, though I suspect it involves custom CSS for rendering `<pre>` blocks within inline styles.

**Comment by AlexPasternak** [comment]
Wow, thanks for the investigation on this, @vassudanagunta, nice work. I had no doubt it's a non-standard approach, but wanted to show a real-world example of usage. For Typora this is definitely a "nice to have" feature only, but sometimes you do need to emphasize parts of code, just like in normal text.

**Comment by abnerlee** [comment]
@g3blv 

> Is it possible to make text bold or highlight text inside a code fence?

You can use this for text bold

```
<pre>
Making text <b>bold</b> inside code fence
</pre>
```

or this for highlight text.

~~~
```markdown
Making text **bold** inside code fence
```
~~~



-----

@AlexPasternak
> but sometimes you do need to emphasize parts of code, just like in normal text.

This would be #1349
