### ISSUE TITLE
Closing </pre> HTML Tag in Rendered Output

### ISSUE THREAD

**Issue by joswr1ght** [typora/typora-issues#3356]
On Windows 10 and macOS 10.14.6, a `<pre>` block that has an empty line will produce a rendered `</pre>` tag in the Typora display:

```
$ cat Foo.md
# Test for \<pre\> Render Bug

<pre>
$RECYCLE.BIN
STUFF
Untitled.txt
Wright, Josh

desktop.ini
</pre>

Closing `</pre>` above.
```

![Typora-HTML-Render-Closetag](https://user-images.githubusercontent.com/1318817/76615196-ecc11d00-64f7-11ea-9189-bf441d8276d9.png)

I use `<pre>` tags instead of normal code fences so I can have `<b>` markup inside of the fixed-width terminal output. The content looks like it is rendering properly but the `</pre>` tag should be suppressed in the output.

**Comment by abnerlee** [comment]
#1939
