### ISSUE TITLE
Standarize horizontal rules / lines amount of characters

### ISSUE THREAD

**Issue by Lednerb** [typora/typora-issues#3358]
Writing markdown code a user can simply add a horizontal line by entering some hyphons like this:

```
-------
Horizontal line above and below rendered equally in preview, but not in source code
----
```

Although the amount of hyphons do not matter at all by only viewing the document in typora or in a rendered version, it would be a nice feature that typora will always set horizontal rules in source code for a configurable amount of chars, maybe via an options parameter?

There are some implementations coming to my mind that should be more or less easy to implement:

A. Always use 74 `-` chars (the full width of the source code mode)

Pro (+) / Con (-) : 
`+` Easy to implement
`-`  Increases file size
`-` Maybe unintended changes that an user would not expect

B. Configurable settings to diasble this feature (in my mind it should be enabled by default for producing a consistent source, but I'm also fine with disabled by default) and with an configurable amount of chars (74 as a default to match the full width of the source code mode).

Pro (+) / Con (-):
`+` Creates a configurable way to hold the markdown files consistent
`+` User can enable / disable the behavior 
`+` User can adjust the behavior
`-` Needs some time to implement

-------

Thanks for this great editor!

**Comment by abnerlee** [comment]
Seems a specific issue under #1433
