### ISSUE TITLE
Superscript tag closure issue

### ISSUE THREAD

**Issue by PAGiesting** [typora/typora-issues#3359]
I have encountered a strange behavior while using the subscript tags. In the document where I was taking notes, I want to superscript the minus sign in NV-. I enter the first tag and the minus sign, but when I type < to open the closing tag I get the text /sub> spat out without the <. This happens repeatedly. I opened a new document to test this behavior, and it works normally. I even copied the last paragraph-ish of my notes document into this new file, and found that the tags worked normally. This is way too subtle for me. Probably a very low priority, but it seems likely to be a bug regardless.

I am attaching the .md files mentioned with the .txt extension. The issue is seen at the end of the first file.
[DefectMLproposal-component copy.md.txt](https://github.com/typora/typora-issues/files/4330117/DefectMLproposal-component.copy.md.txt)
[Markdown-test.txt](https://github.com/typora/typora-issues/files/4330120/Markdown-test.txt)

**Comment by abnerlee** [comment]
Could you provide the Typora version / OS info?

**Comment by PAGiesting** [comment]
Mac OS Catalina 10.15.3 on an 11 in mid-2012 MacBook Air
Typora Version 0.9.9.32.1 (4191)

**Comment by abnerlee** [comment]
I'm still not able to reproduce this, possible to attach or send us <hi@typora.io> a screencast?

**Comment by PAGiesting** [comment]
Predictably, I can't reproduce it now either. I kept using the file I submitted where the problem occurred, and now it does not occur there, nor when I download the file I submitted on GitHub and rename it back to its original name. Here is the file where the problem WAS happening with its original name, where you can see all the "/sup>" strings that were spat out when I would type "<" to try to close the tag, but of course now it works the way it should and I have no idea what could have changed. I'll mark the problem as disappeared or whatever the closest equivalent is if I have the authority.

Sincerely,

Paul Giesting
574 386 1482

**Comment by PAGiesting** [comment]
Now I can't reproduce it either. Never mind.
