### ISSUE TITLE
labeling formula

### ISSUE THREAD

**Issue by Cocozss** [typora/typora-issues#3361]
I have encountered a problem that when I was labeling my formula, it's OK at first, but after switching to another md file and return, it would always warn that this label is multiply defined!
1
![image](https://user-images.githubusercontent.com/50159093/76693685-6ac22700-66a4-11ea-8137-44ae3dbb03ca.png)
2(After switching to another file and switch back)
![image](https://user-images.githubusercontent.com/50159093/76693689-7c0b3380-66a4-11ea-9413-727a89a03962.png)

**Comment by Liguobing00** [comment]
I have the same problem here. It would be appreciated if the author can look into it.

**Comment by abnerlee** [comment]
#3043
