### ISSUE TITLE
Error on updating online images

### ISSUE THREAD

**Issue by zyyfriends** [typora/typora-issues#3362]
please look at the screenshots. and the last one is log by picgo.app   It seems caused by character escaping problem
![TIM截图20200315170735](https://user-images.githubusercontent.com/42362178/76698670-cd391880-66e0-11ea-9051-87c573453a29.png)
![TIM截图20200315170842](https://user-images.githubusercontent.com/42362178/76698672-cf9b7280-66e0-11ea-8c8d-1fade06e5f11.png)
![TIM截图20200315170804](https://user-images.githubusercontent.com/42362178/76698674-d1653600-66e0-11ea-9431-171771364c64.png)

**Comment by violetu** [comment]
+1

**Comment by LeonG7** [comment]
Tutorials and error guides:
https://blog.csdn.net/disILLL/article/details/104944710

**Comment by zyyfriends** [comment]
> Tutorials and error guides:
> https://blog.csdn.net/disILLL/article/details/104944710

but my problem is different from his。。。

**Comment by LeonG7** [comment]
> > Tutorials and error guides:
> > https://blog.csdn.net/disILLL/article/details/104944710
> 
> but my problem is different from yours。。。
> you can see I am updating online images , instead of local images。。。

Your Picture bed is too slow, suggest you switch to the other site, such as gitee or github, refer to the blog:https://blog.csdn.net/disILLL/article/details/103962241

**Comment by abnerlee** [comment]
The error is reported from PicGo, it may not support to pass an online url
