### ISSUE TITLE
Can't switch keyboard layout

### ISSUE THREAD

**Issue by Savamoti** [typora/typora-issues#3366]
OS: Debian 10.3
Typora: 0.9.86(beta)

I use 2 keyboard layouts, when I try to switch(ALT+SHIFT) the layout , the menu bar takes focus and I can 't start typing right away. I have to press ALT button again, which is quite annoying.

Can I disable the menu appearance or assign it to a different button?

Enabling "autoHideMenuBar": true in advanced options doesn't help.

**Comment by abnerlee** [comment]
I tried on Windows, and cannot reproduce this. Press Alt will focus on menu bar but, then press shift or tab key will still trigger the global hot key. On Ubuntu Alt + Tab can be used successfully, and I cannot config Alt+Shift on its keyboard setting page.

Does Alt + Tab work on your Debian? And what is your Typora language?

Is it same with https://github.com/electron/electron/issues/17418 that menu get opened on Alt+Shift?

**Comment by Savamoti** [comment]
> I tried on Windows, and cannot reproduce this. Press Alt will focus on menu bar but, then press shift or tab key will still trigger the global hot key. On Ubuntu Alt + Tab can be used successfully, and I cannot config Alt+Shift on its keyboard setting page.

I also can't reproduce this in Windows, but I have problems with Debian (KDE).


> Does Alt + Tab work on your Debian? And what is your Typora language?

Alt + Tab works fine in Debian. I use Russian.

It seems like electron problem.
Some developers have solved the problem on their side.
For example: VScode
[Notable.](https://github.com/notable/notable/issues/557#issuecomment-573894002)
Is it fixable?

**Comment by abnerlee** [comment]
We already used their approach from very early versions?

Do you share the SAME behavior with them (from their report, the menu will be open when pressing Alt+Shift) ?

If you have any of those app, like VS Code, can you do Alt+Shift successfully?

**Comment by Savamoti** [comment]
> Do you share the SAME behavior with them (from their report, the menu will be open when pressing Alt+Shift) ?

In my case, the menu bar takes focus when I press Alt+Shift.
![Peek 2020-03-30 17-12](https://user-images.githubusercontent.com/32238565/77901638-25a81280-72aa-11ea-8e88-625b909f0605.gif)


> If you have any of those app, like VS Code, can you do Alt+Shift successfully?

I have VScode, there is no problem with him. Alt+Shift and Alt+Tab works fine.

**Comment by abnerlee** [comment]
https://github.com/electron/electron/issues/22213

**Comment by Qwicen** [comment]
I have exactly the same behavior on my ubuntu. 
Alt + Shift triggers both Menu Bar focus shortcut and global keyboard language switch instead of just the last one.
So I need to bring the focus back to text filed every time I switch the language, which is very annoying.

Typora: 0.11.8 (beta)
