### ISSUE TITLE
Failed to Copy Image to Local Folder - Download Timeout

### ISSUE THREAD

**Issue by H8to** [typora/typora-issues#3367]
Hi!

## Issue Description
When I paste the following image file:
`https://gblobscdn.gitbook.com/assets%2F-LFEMnER3fywgFHoroYn%2F-LR8vj9yvUH2fK9wIwhu%2F-LR8yMOo0_kRg4tTDKu4%2FScreenshot%20from%202018-11-12%2022-09-43.png?alt=media&token=4b4e6677-499d-42d5-9e63-e003af518c38`

and right-click "Copy to XYZ" or "Copy image to..." the file will not be copied, regardless if I change the name to test.jpg or keep the original name.

Notice, that the file explorer on Linux tries to save the file as:

```
assets%2F-LFEMnER3fywgFHoroYn%2F-LR8vj9yvUH2fK9wIwhu%2F-LR8yMOo0_kRg4tTDKu4%2FScreenshot from 2018-11-12 22-09-43.png?alt=media&token=4b4e6677-499d-42d5-9e63-e003af518c38
```

where `.png?alt=media&token=4b4e6677-499d-42d5-9e63-e003af518c38` is the file extension.

![image](https://user-images.githubusercontent.com/16744267/76780342-2a9a9b80-67ad-11ea-8150-4add03f9408e.png)

## Another location

I get the same error for: `http://sebihaas.de/images/03_Landscape%20&%20Buildings/026-DSC_5529-08_2013.jpg`

I tried the functionality with `Auto escape image URL when insert` on and off.

Let me know how I can help debugging this issue.

Regards
Sebastian

**Comment by abnerlee** [comment]
relates #3280

**Comment by abnerlee** [comment]
should be fixed
