### ISSUE TITLE
outline filter shortcut not found on ubuntu

### ISSUE THREAD

**Issue by hyzgh** [typora/typora-issues#3368]
Recently, I switched my OS from macOS to ubuntu 18.04. I use the filter of outline frequently. I found that I couldn't use a shortcut to use it.
![image](https://user-images.githubusercontent.com/31174102/76963670-58721280-695c-11ea-8e44-6431983cc61b.png)

I remembered that I could use the shortcut on macOS, maybe command + shift + F or ctrl + shift + F. I know the difference between search and filter, I could use both of these shortcuts on macOS, but I could only use the shortcut ctrl + shift + F for search on ubuntu.
![image](https://user-images.githubusercontent.com/31174102/76963798-9707cd00-695c-11ea-97d9-c3a19aaee56c.png)

Is there any way to use a filter shortcut on ubuntu?

**Comment by abnerlee** [comment]
We don't support this. Maybe duplicate with #1591 for its intension.
