### ISSUE TITLE
Some macOS keyboard shortcuts not working between Markdown titles and lists

### ISSUE THREAD

**Issue by kakyoism** [typora/typora-issues#3370]
With my setup:

- Typora: Version 0.9.9.32.1 (4191), 
- macOS: 10.14.6 (18G1012)

the macOS keyboard shortcuts `Ctrl+N / Ctrl+P` (up/down one line) does not work when the cursor is in a title or list. They work elsewhere such as in the body paragraphs.

These commands are part of the macOS-specific text-editing [keyboard shortcuts](https://support.apple.com/en-us/HT201236) to move cursors without moving hands away from the keyboard center area.

```
Control-A: Move to the beginning of the line or paragraph.
Control-E: Move to the end of a line or paragraph.
Control-F: Move one character forward.
Control-B: Move one character backward.
Control-L: Center the cursor or selection in the visible area.
Control-P: Move up one line.
Control-N: Move down one line.
Control-O: Insert a new line after the insertion point.
Control-T: Swap the character behind the insertion point with the character in front of the insertion point.
```

**Comment by abnerlee** [comment]
#1161
