### ISSUE TITLE
Mermaid Flowchart: Text on link is hidden (Windows)

### ISSUE THREAD

**Issue by konsma** [typora/typora-issues#3371]
Hey guys,

on Windows v. 0.9.86 there is a problem with the Mermaid Flow Chart.
I changed nothing on the CSS or manipulate anything on Typora. Nothing, but a fresh install.

There is no 'default gray' background on the link text between the nodes and on html the link text is not completely visible.

On Typora
![Typora](https://user-images.githubusercontent.com/62373770/77043455-dadeee80-69bd-11ea-921a-994833a519fb.png)

HTML output
![html_out](https://user-images.githubusercontent.com/62373770/77043466-e29e9300-69bd-11ea-95fd-948f6896fce3.png)

Thank you!

**Comment by abnerlee** [comment]
merge into #1661

And could you paste the mermaid content in this screenshot?

**Comment by konsma** [comment]
Sure. Here is the mermaid content:
`
graph TD

cond{Condition}
p1[Point 1]
p2[Point 2]

cond --"True"--> p1
cond --"False"--> p2
`

**Comment by abnerlee** [comment]
merge into #1661

**Comment by rnahumaf** [comment]
I have the same issue here. I'm using mermaid with Typora, and...

flowchart TD
    A[Start] --> B{Is it?}
    B -->|Yes| C[OK]
    C --> D[Rethink]
    D --> B
    B ---->|No| E[End]

![image](https://user-images.githubusercontent.com/34604938/158631519-65443a03-d080-4691-a911-4f7f5ab579bb.png)
