### ISSUE TITLE
Bottom scroll bar in File tree view disappear

### ISSUE THREAD

**Issue by etet2007** [typora/typora-issues#3372]
In the File tree view ,the bottom scroll bar will apper when the file name is too long. 
However, when you move your pointer above the scroll bar, the bar disappear.

Version 0.9.9.32.1 (4191)   Mac os.
![图片](https://user-images.githubusercontent.com/12908406/77046326-ba368900-69fd-11ea-9f45-4ba756c70d69.png)
![图片](https://user-images.githubusercontent.com/12908406/77046351-c7ec0e80-69fd-11ea-9607-4c5f6be5cb77.png)

**Comment by abnerlee** [comment]
should be fixed
