### ISSUE TITLE
Typora attempt to mkdir 'C:\Windows\system32\upload'

### ISSUE THREAD

**Issue by pluveto** [typora/typora-issues#3377]
[Window Title]
Error

[Main Instruction]
错误

[Content]
EPERM: operation not permitted, mkdir 'C:\Windows\system32\upload'

[确定]

## To reproduce
Enable `Upload` when insert image.
Copy image to clipboard and paste to typora document.

**Comment by abnerlee** [comment]
#3331

**Comment by Salensoft** [comment]
I got the same problem when I paste screenshot straight to Typora.
![image](https://user-images.githubusercontent.com/40481352/82013318-a1b8b700-96ac-11ea-9e3d-8643e14907d2.png)
And after I manually created an empty folder "upload", the program no longer pops up a dialog but I still cannot paste a photo.
Thanks for your help!

**Comment by DIY-Z** [comment]
I also have the same problem ? 
How to solve it ?
