### ISSUE TITLE
Markdown comments don't line wrap on Linux

### ISSUE THREAD

**Issue by hazel-DO** [typora/typora-issues#338]
What it says on the tin. Long Markdown comments, i.e. `<!-- like this -->`, don't line wrap on Linux. Someone else verified that comments do line wrap correctly on Mac, however.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/10812513/19156272/4c8a2dba-8baf-11e6-8cf6-d7bbbe2dfaf8.png)

I'm running Typora version 0.9.19(beta) with no customization on Ubuntu 16.04.

**Comment by abnerlee** [comment]
@hazel-DO a new version is available, could you confirm if the bug exists on 0.9.20 ?

**Comment by abnerlee** [comment]
seems ok on 0.9.20

**Comment by hazel-DO** [comment]
Confirming it's fixed on 0.9.20. Thanks!
