### ISSUE TITLE
"Search" is not working in symbolic link directories

### ISSUE THREAD

**Issue by myshzzx** [typora/typora-issues#3380]
I create some symbolic linked directories to organize docs from different path, so that I can view them all in the same file tree. But I find the "Search" function does not support symblic link, and I get no result from "Search".

![image](https://user-images.githubusercontent.com/2025090/77245523-14cc2100-6c5a-11ea-85ef-5b1dd3929de3.png)

**Comment by abnerlee** [comment]
#3283
