### ISSUE TITLE
Pop out of syntax markdown?

### ISSUE THREAD

**Issue by snak3codes** [typora/typora-issues#3382]
I want Typora to jump out of the current markdown syntax I am performing on a word.

E.g.: Assume I am typing this in Typora and I make the next word **bolded, <-- when i make this bold with ⌘ + B, the cursor remains inside the ****, I would like it to go out on the right.
I always have to press ⌘ + → to jump out of the two final asterisks.

Any macros or settings I could use to change this behaviour?
Thank you.

**Comment by abnerlee** [comment]
What is the behavior you expect? 

#3288
