### ISSUE TITLE
Spellchecker suggesting useless options to simple misspellings

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#3383]
Typora 0.9.86 (Beta) 
Arch Linux

The spell checker is acting differently.  The recommendation for the misspelled word "Decembee" are Embedder, Decree, Embed, Dissemble. Even more comical, "shoulf" options are  shovelful, ghoulish, houseful, shelf... and no "should"

**Comment by abnerlee** [comment]
relates #214

Are you using EN-US for spellcheck?

**Comment by baardev** [comment]
Yes, sorry, I thought would be obvious by the English words I showed it was presenting:  Embedder, Decree, Embed, Dissemble, Shovelful, Ghoulish, Houseful, Shelf. This is very easy to test yourself.  Just spell check the words "Decembee" and "should." 

Unfortunately, this upgrade bug makes Typora far too inconvenient to use, as I have to cut and paste from Typora to an app that actually can spell check, then cut and paste back.  Why not consider allowing something like Grammarly to work?  As Typora is essentially a browser, it should be fairly easy to integrate and would prove a much more robust solution.

**Comment by baardev** [comment]
I see this was closed, but not sure as you asked me a question but closed it the same day before you received an answer.  Have you (or anyone) replicated this error?

**Comment by abnerlee** [comment]
#3406
