### ISSUE TITLE
Resized Images no longer rendered when creating pdf or word file

### ISSUE THREAD

**Issue by rolfeisenhut** [typora/typora-issues#3384]
Since a few versions, typora no longer renders images when exporting to pdf or work or doing printout.

Version  0.9.86
OS: Windows 10

Regards Rolf

**Comment by abnerlee** [comment]
Is the image url an online address or local file? Did you use relative path? Possible to send us a sample file <hi@typora.io> ?

**Comment by Epi233** [comment]
Hi, I have same question, and what I found is that:
if a image uses markdown grammar, pdf shows currect.
if a image uses html grammar, pdf do not show that image.
all image uses local relative path.

Ver: 0.9.86(beta)
OS: win 10

thanks

**Comment by Epi233** [comment]
And I ask my friend to do the same thing with his macbook,
and everything seems right on mac os.

**Comment by abnerlee** [comment]
duplicate with #3120 ?
