### ISSUE TITLE
How does typora judge whether a image should be center-aligned

### ISSUE THREAD

**Issue by paulzhn** [typora/typora-issues#3385]
![image](https://user-images.githubusercontent.com/8180364/77450208-eef77580-6e2d-11ea-8738-9618f989f590.png)

The code corresponding to the above image is below:
```markdown
    <img src="/path/di2.png" alt="di2" style="zoom:50%;" />

2. Show the properties of $R$

   $R$ is irreflexive, not reflexive; 

   $R$ is asymmetric, antisymmetric, not symmetric.

## Problem 6. Let $A=\{1,2,3\}$. The digraphs of 2 relations are shown as follows. For each digraph, write the matrix of the corresponding relation, and show the properties of it.

(a)

 <img src="/path/image-20200325000335028.png" alt="image-20200325000335028" style="zoom:100%;" />
```

I am confused that why the image above is center-aligned but the below is not. The image-inserting code seems to be similarly. What makes me confused more is that when I generated the html file, it seems like the two image have the same style. So, why could this happen?

**Comment by abnerlee** [comment]
It's defined by CSS, in default themes, only image is the only content in paragraph, then it will be center aligned.

In your case, you could remove the whitespace before image to center align it.
