### ISSUE TITLE
Mermaid flowchart not displaying stadium-shaped node

### ISSUE THREAD

**Issue by yanzhen0610** [typora/typora-issues#3386]
It's not displaying [stadium-shaped node](https://mermaid-js.github.io/mermaid/#/flowchart?id=a-stadium-shaped-node). When I use this syntax, the entire chart is just disappeared(not showing anything).

<pre>
```mermaid
graph LR
    id1([This is the text in the box])
```
</pre>

Version: `0.9.86(beta)`

**Comment by abnerlee** [comment]
can be supported by upgrading mermaid version: #1661
