### ISSUE TITLE
How can I add a line of text to the middle of a file?

### ISSUE THREAD

**Issue by work-2020** [typora/typora-issues#3387]
I'm trying to add a line of text to the middle of a text file in Typora for linux, version 0.9.86. 
+ in the middle of a file, I press the Enter, then there is a empty line.
+ but the cursor does not at the begin of the empty line, it is at the begin of the next line
+ and I could not even move up the cursor to the begin of that empty line

**Comment by abnerlee** [comment]
What's your Linux distribution? Did you use any non-English keyboard layout or IME?

**Comment by abnerlee** [comment]
relates #3192

**Comment by work-2020** [comment]
Dear AbnerLee,

I am github user work-2020. Thank you for your reply！

I use Typora in Kali(XSMP Debian 5.3.9-3kali1 (2019-11-20)) and I failed to install Typora online.
so, I download the bianry file and add it's path to the Environment variables ‘PATH’.
I use  ‘Typora --no-sandbox file’ to edit a file.

By the way, I use Chinese keyboard.

Best wishes.


------------------------------------------------------------------
发件人：AbnerLee <notifications@github.com>
发送时间：2020年3月27日(星期五) 23:22
收件人：typora/typora-issues <typora-issues@noreply.github.com>
抄　送：work-2020 <work_2020@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [typora/typora-issues] How can I add a line of text to the middle of a file? (#3387)

What's your Linux distribution? Did you use any non-English keyboard layout or IME?

**Comment by abnerlee** [comment]
Can this be reproduced when you just type English?

> By the way, I use Chinese keyboard.

Is it ibus pinyin or other IME?
