### ISSUE TITLE
Update MathJaX to v3

### ISSUE THREAD

**Issue by i-blis** [typora/typora-issues#3388]
Would you consider updating MathJax to 3.0, which displays a considerable increase in rendering speed compare to 2.7+ ?

It shouldn't be much effort, it mostly requires a couple of changes to index.html, in particular in order to load tex-chtml-full.js. 

Besides better and faster rendering, the new version also provides more extensions and offers the possibility to dynamically load them through \require.

Thanks in advance.

**Comment by eiis1000** [comment]
This would also do wonders towards solving the four year long-standing and highly active issue #100 with minimal effort! @abnerlee

**Comment by mcesar-rlacruz** [comment]
At least wait until MathJax V3 supports all V2 fonts.

**Comment by jaromir-benes** [comment]
+1

**Comment by abnerlee** [comment]
supported
