### ISSUE TITLE
Jumping to another's section is not working as expected

### ISSUE THREAD

**Issue by Kimi-Arthur** [typora/typora-issues#3389]
So with links like `[some text](#section-title)` Typora can correctly jump to a section in the same file. It can also jump to another file (with a new window, which is not desired but OK).

However, it cannot properly jump to the other file and arrive at the section specified, like `[some other text](../file.md#section-1)`.

**Comment by kokoajin** [comment]
I having the same problem.

**Comment by abnerlee** [comment]
duplicate

**Comment by abnerlee** [comment]
#1231
