### ISSUE TITLE
Set a default code type with ctrl+shift+k in the setting 

### ISSUE THREAD

**Issue by hello007** [typora/typora-issues#3391]
I’ve bean using typora for several months. I want to make a suggestion, when I insert code with ctrl+shift+k, I have to write the code type every time. Can I set a default code type in the setting? Thank you very much!

**Comment by abnerlee** [comment]
#290
#1381

**Comment by hello007** [comment]
When will the issue [#290](https://github.com/typora/typora-issues/issues/290) be closed?
