### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by DrTonyHo** [typora/typora-issues#3392]
macOS Catalina Version 10.15.4 on MacBook Pro (15-inch, 2018)
Typora Version: 0.9.9.32.1 (4191)

When export to word or latex, shows me error but it works to PDF. Files attached

<img width="532" alt="Screen Shot 2020-03-27 at 4 04 36 pm" src="https://user-images.githubusercontent.com/31120264/77723467-a960c580-7044-11ea-8cc9-edced12fc492.png">

**Comment by abnerlee** [comment]
Could you send us (<hi@typora.io>) the failed md file?
