### ISSUE TITLE
General wrapping shortcut system

### ISSUE THREAD

**Issue by Kimi-Arthur** [typora/typora-issues#3393]
I use HTML in markdown files sometimes. Due to its wrapping nature, it's cumbersome to wrap a text in `<span>` or `<ruby>`. It is more cumbersome when you move into/out of an HTML block, as the preview text changes.

It would be great if we can assign a shortcut to say wrap the text with `<span style="color: red"></span>` etc. It's similar to what we have for making it bold, italic etc. But since needs for wrapping with arbitrary HTML tag would be unpredictable, giving the ability to assign shortcuts to any HTML tag wrapping would be the ideal solution.

**Comment by abnerlee** [comment]
#3021 #3354
