### ISSUE TITLE
[help wanted] How to change the colour of the list tag of the unactivated list wrote in focus mode?

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3396]
OS: win 10

----
How can I change the colour of the list tag of the unactivated unordered list wrote in focus mode?
I read the help documents on the topic of focus mode CSS adjustment. And I almost have changed every colour setting in CSS rendering file while none of it works.

**Comment by abnerlee** [comment]
I'm not sure what "list tag" mean, but you can open DevTools to check the CSS selector.

http://support.typora.io/Add-Custom-CSS/#debug-css
