### ISSUE TITLE
typora-root-url does not work for <img>

### ISSUE THREAD

**Issue by DotIN13** [typora/typora-issues#3397]
Path:
```
|----img
|----_post
       |----*.md
```
YAML:
```YAML
typora-root-url: ./
```

HTML tag:
```html
<img src="/img/in-post/post-wodbasics/settings.md.png" alt="Where Is Settings?">
```

The image does not show correctly. It looks like typora does not support setting root path for `<img>` tag.

**Comment by abnerlee** [comment]
Shouldn't you use `typora-root-url: ../` ?

**Comment by DotIN13** [comment]
Ok after I changed back to "../", it worked. But only **after I reopened** my md file. I mean, shouldn't it be updating itself whenever root path changes?
