### ISSUE TITLE
Not to add line-breaks before and after math blocks $$...$$ in the source code

### ISSUE THREAD

**Issue by wyf88** [typora/typora-issues#34]
Like many other people, I'm using Typora to write academic papers in markdown as an alternative to LaTeX, and use pandoc later to convert to LaTeX format. One of the problem with Typora is that, it automatically adds line-breaks before and after every math block $$...$$. Notice that sometimes the math block is in the middle of a sentence, so what happens is that a paragraph is separated into three paragraphs by mistake. While not a big issue in markdown, in LaTeX everything after a blank line is regarded as a new paragraph, so the format and spacing is not correct and I have to manually remove the blank lines before and after it.

I think it would be more reasonable not to add line-breaks automatically in the source code for math blocks $$...$$ unless the user manually do so. It doesn't impact the readability of the markdown source code as well.

**Comment by abnerlee** [comment]
We will fix this in next version up

**Comment by wyf88** [comment]
Glad to hear that, thanks a lot for the prompt reply! 

Meanwhile after I read what I said yesterday I think maybe I didn't make it clear enough. For example, what I want is a single paragraph, just put the formula on a line by itself.
```
Consider the following linear quantile regression model: 
$$Q_\tau(y_i | \mathbf{x}_i) = \mathbf{x}_i^\mathrm{T} \boldsymbol{\beta}_\tau, \quad i = 1, \dotsc, n,$$
where $Q_\tau(y_i | \mathbf{x}_i)$ is the conditional $\tau$-quantile of the response $y_i$ given the independent variables $\mathbf{x}_i$, 
```
But in Typora it automatically becomes 3 paragraphs.
```
Consider the following linear quantile regression model: 

$$Q_\tau(y_i | \mathbf{x}_i) = \mathbf{x}_i^\mathrm{T} \boldsymbol{\beta}_\tau, \quad i = 1, \dotsc, n,$$

where $Q_\tau(y_i | \mathbf{x}_i)$ is the conditional $\tau$-quantile of the response $y_i$ given the independent variables $\mathbf{x}_i$, 
```
I hope this is helpful for people in the same situation like me.

**Comment by abnerlee** [comment]
It is the same thing Typora will fix in next version up. support single line break and trying to avoid re-formatting on markdown source.
