### ISSUE TITLE
Scroll wheel error

### ISSUE THREAD

**Issue by 8128** [typora/typora-issues#3400]
System: MacOS 10.15.4
Mouse: Logitech MX Master 3
Typora: 0.9.9.32.1(4191)

I have two scroll wheels on my logi MX Master 3 and every time I used the scroll wheel for left and right, the up/down scroll wheel will not work anymore. It only happens in Typora so I'm sure it's not my mouse's problem

**Comment by abnerlee** [comment]
Relates #3164

Could you attach (or send us <hi@typora.io>) a screencast about this (since we don't have mouse with two wheels)? 

Does this also happen with trackpad?

**Comment by 8128** [comment]
> Relates #3164
> 
> Could you attach (or send us [hi@typora.io](mailto:hi@typora.io)) a screencast about this (since we don't have mouse with two wheels)?
> 
> Does this also happen with trackpad?

Hi there, I've sent the video to the email above. No, not with trackpad, only happened to my mouse. 

If I scroll left/right using trackpad, then my mouse can still scroll up/down. But if I scroll left/right using mouse, then it cannot scroll up/down anymore.

**Comment by paseaf** [comment]
same. I'm also using an MX Master 3.

**Comment by jr0203** [comment]
I am using a razer deathadder elite, and the scroll button does not seem to work.

**Comment by adreasnow** [comment]
While it's not a fix, nor will it work for everyone, if you're using a Logi mouse, I got around this issue by setting up a custom application profile for Typora in Logi Options, in which the horizontal scroll is disabled. that way, if like me, you accidentally bump the horizontal scroll wheel, it won't disable the vertical one.

Hope it helps somebody 😄

**Comment by kenzheng99** [comment]
Can confirm this is still an issue with Typora 0.9.9.35 (4693), using a MX Master 3 mouse.

**Comment by 1deadpixl** [comment]
Same problem here on Typora v0.9.9.35 and MX Master 3 (F/W v19.01.0015, S/W v8.20.233).

@abnerlee The second (thumb) scroll wheel on the Logitech MX Master 3 activates horizontal scrolling by default. It seems to scroll the entire UI view horizontally in Typora. Please see the attached screen cap: [typora_horizontal_scrolling.mov.zip](https://github.com/typora/typora-issues/files/5177468/typora_horizontal_scrolling.mov.zip)

@adreasnow Thanks for the workaround. Seems to fix the issue for now. I don't really need horizontal scrolling anyway with the lines wrapping, but the vertical scrolling is a must.

**Comment by abnerlee** [comment]
> The second (thumb) scroll wheel on the Logitech MX Master 3 activates horizontal scrolling by default. It seems to scroll the entire UI view horizontally in Typora. 

This is a scroll bounce effect, should be disabled by https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior-x, but not supported by Safari yet (https://bugs.webkit.org/show_bug.cgi?id=176454) I will check workarounds.

But the "original" issue is "every time I used the scroll wheel for left and right, the up/down scroll wheel will not work anymore.", is this still happens?

**Comment by 1deadpixl** [comment]
> But the "original" issue is "every time I used the scroll wheel for left and right, the up/down scroll wheel will not work anymore.", is this still happens?

Yea, on the latest version (v0.9.9.35.2), this is still a problem. If the horizontal scrolling is activated, the scroll bounce effect moves the whole UI horizontally and then vertical scrolling stops working. When the vertical scroll is first activated after scrolling horizontally, there is a slight motion in the vertical direction (like the scroll event worked) but then the scroll wheel immediately stops working. You can see the little jerk in the last second of the screen cap I uploaded.

**Comment by abnerlee** [comment]
The scroll bounce effect should be fixed, after that, does the original bug still exists?

**Comment by kenzheng99** [comment]
Seem to be fixed for me on latest beta v0.9.9.36.2 (4901). Horizontal scrolling no longer has the bouncing effect, and vertical scrolling still works afterward.
