### ISSUE TITLE
 Support different formula delimiters for TeX.

### ISSUE THREAD

**Issue by yxs** [typora/typora-issues#3401]
Just like vscode extension [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) is compatible with [Markdown+Math](https://github.com/goessner/mdmath).

https://github.com/yzhang-gh/vscode-markdown/commit/7d7d9d9fc7d108b0a64477b9a46d130524c61b15

https://github.com/goessner/mdmath#features

**Comment by abnerlee** [comment]
duplicate with #63
