### ISSUE TITLE
laggying when scrolling through images

### ISSUE THREAD

**Issue by ccshao** [typora/typora-issues#3402]
When scrolling down or up  through images, typora shows significiant laggy. 

Interestingly, after setting the zoom level, like 15% or 25%, the situation gets better. Could you kindly looking into the performance of the image embedding? Thanks!

With typora 0.9.9.32.1, macos 10.13.6. Images are interseted in the local folder.  Images typically are 300 ppi.

**Comment by abnerlee** [comment]
#68 #3214
