### ISSUE TITLE
Spellchecker offering useless alternatives to common misspellings (repost)

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#3406]
This post was closed before I could even answer the question, so I am reposting it. It would be helpful to know if anyone can replicate this error?

Typora 0.9.86 (Beta)
Arch Linux
The spell checker is acting differently. The recommendation for the misspelled word "Decembee" are Embedder, Decree, Embed, Dissemble. Even more comical, "shoulf" options are shovelful, ghoulish, houseful, shelf... and no "should"

Response from  abnerlee 
> relates #214
> Are you using EN-US for spellcheck?

No, this is not related to #214, which is "Misspelled words are not always marked."  This is "Bizarre and rare options are offered for common misspelled words."

Yes, sorry, I thought it would be evident by the English words I showed it was presenting: Embedder, Decree, Embed, Dissemble, Shovelful, Ghoulish, Houseful, Shelf. This is very easy to test yourself. Just spell check the words "Decembee" and "shoulf."

Unfortunately, this upgrade bug makes Typora far too inconvenient to use, as I have to cut and paste from Typora to an app that actually can spell check, then cut and paste back. Why not consider allowing something like Grammarly to work? As Typora is essentially a browser, it should be reasonably easy to integrate and would prove a much more robust solution.

**Comment by abnerlee** [comment]
I'm still unable to reproduce this.

What's your Linux distribution? Does Typora's Status bar say it is "en-US"? Did you use custom theme and possible to attach a screenshot about this?

![捕获](https://user-images.githubusercontent.com/1621242/78468954-f92f4300-774e-11ea-88b3-8f7b3b28888d.PNG)

**Comment by baardev** [comment]
OK, my apologies.  It seems the top of the popup box was cropped and the first (and correct) option was off the screen and I did not notice it until seeing your screenshot, so thanks for that.
