### ISSUE TITLE
Strike though in tables

### ISSUE THREAD

**Issue by VegaDeftwing** [typora/typora-issues#3408]
when in source code mode looking at a table
```
| X                 | Y             | Z            |
| --------------- | ------------ | ----------- |
| ~~start        | middle     | end~~    |
```
Shows a strike though all 3 items, but in the 'normal' view it shows the '~~' characters as part of the items.

**Comment by abnerlee** [comment]
A part of #1638

**Comment by VegaDeftwing** [comment]
Im not sure the issuse is actually related to the one you liked?

**Comment by abnerlee** [comment]
The source code mode should render same as the normal mode: shows the '~~' characters as part of the items
