### ISSUE TITLE
Bug: when insert <br> in mermaid node, content disappeared

### ISSUE THREAD

**Issue by lewengo** [typora/typora-issues#3409]
When I insert <br> or <br/> in a node of mermaid code, the content below the br disappeared.
```
graph LR
    id1[This is the<br/> text in the box]
```
![image](https://user-images.githubusercontent.com/1232520/78459803-39120e00-76ee-11ea-824e-53f2ee7e1693.png)

**Comment by abnerlee** [comment]
#3166
