### ISSUE TITLE
Still cannot open .md files by double clicks

### ISSUE THREAD

**Issue by allucinaria** [typora/typora-issues#341]
**Environment:**
- Win 10 Home Edition x64, Version 1607 
- VC++ has been installed from 2008-2015 (x86/x64)

**Typora version:**
 0.9.20 (beta)

**Problem:**
Whenever open a .md file there will be a Alert stating : Cannot fount ../typora.exe

Hope you guys help.

Thanks a lot!

**Comment by abnerlee** [comment]
Have you try uninstall, then reinstall ?

**Comment by allucinaria** [comment]
@abnerlee 
Yup. Tried several times since 0.9.17.
Tried again today with 0.9.20 and still failed, so I put an issue here.

**Comment by abnerlee** [comment]
@allucinaria So can you find the "typora.exe" under `Program Files/Typora/bin` ?

**Comment by allucinaria** [comment]
@abnerlee 
~~Yes. 
I found "typora.exe" under both `Program Files/Typora/bin` and `Program Files/Typora/`.
And I could launch the program by open either of them.~~

**Solved.**
I just ticked the `run as administrator` in the `property/compatibility` tab for `Program Files/Typora/bin/typora.exe`.
**And it worked.**
It doesnt work with  `Program Files/Typora/typora.exe`, however.

Thank you for your illuminative answer !
