### ISSUE TITLE
PageUp goes many pages up to the same spot

### ISSUE THREAD

**Issue by pauljurczak** [typora/typora-issues#3410]
Windows 10, Typora 0.9.86. When I switch between open windows without clicking on the open text, PageDown behaves normally, but PageUp always goes to the same spot. Clicking on the text restores normal behavior.

**Comment by abnerlee** [comment]
It works in my test.

> When I switch between open windows without clicking on the open text

You mean by clicking window title or pressing ctrl+tab? possible to attach or send us <hi@typora.io> a video about this?

**Comment by pauljurczak** [comment]
When I use Alt+Tab to switch between windows.

**Comment by abnerlee** [comment]
Yes, I tried both but seems not reproducible.

So possible to attach or send us <hi@typora.io> a video about this?

**Comment by pauljurczak** [comment]
What video screen capture tool you recommend for Windows 10? I've never used one.

**Comment by pauljurczak** [comment]
What data do you actually need? Is a sequence of screen captures with corresponding sequence of keyboard/mouse events sufficient?

**Comment by abnerlee** [comment]
@pauljurczak Sorry for late. You can try https://www.youtube.com/watch?v=OfPbr1mRDuo for screen record, and just tell us the keyboard/mouse events along with the video is fine
