### ISSUE TITLE
Please reopen #3117 - Typora port to AArch64 linux

### ISSUE THREAD

**Issue by michalsc** [typora/typora-issues#3411]
Please consider reopening #3117. This is not only relevant to single board computers, which may be not powerful enough, but also new AArch64 based powerful machines such as PineBook Pro. This one has more then enough power to run any electron-based app.

**Comment by abnerlee** [comment]
We don't have plans for single-board computer. We don't have the devices for its development / bug fix.

**Comment by longqzh** [comment]
> 
> 
> We don't have plans for single-board computer. We don't have the devices for its development / bug fix.

Your smartphone is the device for development. Just to install termux + termux-desktop :) 
Eletron does support aarch64, so porting may be easier than you expected

**Comment by michalsc** [comment]
> We don't have plans for single-board computer. We don't have the devices for its development / bug fix.

Since Apple has just introduced new Macs with M1 processors I think aarch64 port of Typora is rather inevitable. If you need some support regarding compilation or tests on this processors feel free to contact me or others. I can offer builds/testing on aarch64 linux.
