### ISSUE TITLE
mermaid: bad rendering classDiagram

### ISSUE THREAD

**Issue by LeoCHANGcn** [typora/typora-issues#3412]
With Typora, I get the followinng result:
![image](https://user-images.githubusercontent.com/25730864/78519666-b45ee700-77f6-11ea-8e32-cc5788bfa41a.png)
However, it should be :
![image](https://user-images.githubusercontent.com/25730864/78519732-d8bac380-77f6-11ea-8746-7d35ce248eac.png)

**Comment by abnerlee** [comment]
#1661
