### ISSUE TITLE
Indenting with tab in a list sometimes sends you to the start of the file

### ISSUE THREAD

**Issue by hierophect** [typora/typora-issues#3414]
System is Mac OSX 10.15.4

I've found that occasionally when I'm working on a list, pressing the Tab key to indent a line sends the cursor to the start of the file. The new line is still tabbed correctly when you scroll back down to it. This appears to happen the most frequently after I create a new line in the middle of the list, as opposed to adding to the end of it. 

It isn't 100% reproducible, and once it has happened once for a line, it doesn't occur again in that spot. But it seems pretty common - when I try it on some of the lists on my files, I get it for basically every single line (after which it will stop happening for those lines).

**Comment by abnerlee** [comment]
Does this happen in the latest version?

**Comment by hierophect** [comment]
Yes, just tested it. I wish I could provide more information but it's sporadic and as I mentioned, never happens twice for the same line. I'm having trouble consistently reproducing it in a test file I could send you. Could it be related to line end encoding or something?

**Comment by abnerlee** [comment]
@hierophect possible to send us (<hi@typora.io>) the test file? We will check that.

**Comment by hierophect** [comment]
> @hierophect possible to send us ([hi@typora.io](mailto:hi@typora.io)) the test file? We will check that.
> 
> relates #3553

Sorry, I meant that I'm unable to replicate it consistently in a test file, sorry! Even when I have a file that is saved in a certain state, and then encounter the error and quit without saving, it still doesn't reoccur for that line. So maybe the problem is random and not related to the contents of the file at all?

**Comment by hierophect** [comment]
Just wanted to add to this - I've also noticed that sometimes when I shift-tab in an unordered list, it sends me to the *end* of the file. Again, I'm unable to find a scenario where I can reproduce this 100% of the time, which is frustrating, but it seems like it might be linked to the character inputs for skipping to file start or end somehow?

**Comment by abnerlee** [comment]
still happens?

**Comment by hierophect** [comment]
I haven't noticed it recently, no, so maybe it got fixed in one of the recent patches? Getting a solid repro on it was always my issue, I could never seem to get it to happen in the same place twice. I still occasionally get funny skips to the start or end of a paragraph, but not to the start or the end of the file anymore.
