### ISSUE TITLE
[Bug] New line on hyperlinks

### ISSUE THREAD

**Issue by Klutch27** [typora/typora-issues#3415]
OS Version: 10.15.3
Typora Version: 0.9.9.31.6

How to Reproduce:

1. Create a hyperlink text.

For example: `[Google](https://www.google.com)`

2. Place your cursor all the way to the left on the same line where the hyperlink is.
3. Click enter once.

The cursor will automatically move _inside_ of the first character (open bracket).

I noticed this because whenever I go to the start of the line and click enter twice (to get a new line above) --> It breaks the hyperlink.
<img width="787" alt="Screen Shot 2020-04-06 at 2 58 35 PM" src="https://user-images.githubusercontent.com/49660740/78599627-192a3980-7817-11ea-8698-bb8468503fb8.png">

**Comment by abnerlee** [comment]
duplicate with #2287
