### ISSUE TITLE
Shortcut/bindable keys need to be customizable for the user

### ISSUE THREAD

**Issue by gittyup2018** [typora/typora-issues#3416]
Shortcut keys NEED to be customizable, it is not a feature, it is a deal breaker for me so while your program is pretty cool, it is also semi-useless as I'm not going to learn use your shortcuts.

Also, your internal links example does not work.

When I paste

# This is a title

...
...
...

A [link](#this-is-a-title) to jump towards target header

A box pops up "select a language"

**Comment by abnerlee** [comment]
duplicate with #1244
