### ISSUE TITLE
Mermaid Sub graph Perpetually Painting

### ISSUE THREAD

**Issue by jaredraby** [typora/typora-issues#342]
Love built in mermaid graphing and diagrams, however I've run into issues while trying to use `subgraph`. I've followed the mermaid support example exactly and the preview in Typora just sits at "Painting Diagram" and doesn't exist in exported PDFs.

Here is the link to the Mermaid example code: https://knsv.github.io/mermaid/#subgraphs

The code I'm trying to run is as follows:  

``` mermaid
graph TB
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
```

EDIT: Just wanted to note this is a 64-bit windows system.

**Comment by vertesy** [comment]
This renders correctly for me in Typora version (0.9.9.10.6) on OS X 10.7.
(Typora uses a different default CSS than mermaid itself)

**Comment by abnerlee** [comment]
Also works for me in Windows. Please check if your typora is the latest version. If so, the please reopen this issue,

**Comment by Biglucky** [comment]
I have the same issue now QAQ. My typpora version is the latest version (8.10 (7132))

<img width="1133" alt="image" src="https://github.com/typora/typora-issues/assets/24956216/bbce65bd-1cdb-46e1-a73e-5244ab13d386">

**Comment by Biglucky** [comment]
> I have the same issue now QAQ. My typpora version is the latest version (8.10 (7132))
> 
> <img alt="image" width="1133" src="https://private-user-images.githubusercontent.com/24956216/333952482-bbce65bd-1cdb-46e1-a73e-5244ab13d386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODI5NTgsIm5iZiI6MTcxNjc4MjY1OCwicGF0aCI6Ii8yNDk1NjIxNi8zMzM5NTI0ODItYmJjZTY1YmQtMWNkYi00NmUxLWE3M2UtNTI0NGFiMTNkMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA0MDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmQ3Y2MzYjk0MzhlM2Y4YmJkNTlmODM0ZGFiMWVhNzRmMjQxZTFjMDk1OTcyNjRiOTVhYzViMzg0ZThlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qL1NazvXMyt207TwTxqcrN6cQkD55COKtT0b4K-ez24">

I download the version 1.7.xx,  the bug fixed now 

![image](https://github.com/typora/typora-issues/assets/24956216/ec49dd5b-67fe-4aec-bbe2-546078d760cd)

**Comment by jeau** [comment]
Same issue with Typora Version 1.8.10 (7132) on MacOS 10.15.7 (Catalina)
