### ISSUE TITLE
Feature Request: Document specific themes

### ISSUE THREAD

**Issue by sst2010** [typora/typora-issues#3421]
Hey there. I recently started using Typora with my business account ( **`User ID: sst1999`** ). It is indeed one of the best Markdown editor & tool I've encountered. **Kudos to the whole team !!**

Moving on to my feature request, the themes we select are applied currently at the application level. It would be a great feature to be able to select the themes & associate them with the documents.

It feels like a must-have as well. Any user might be working with different types of documents, requiring different look & feel for each.

**P.S.:** I noticed a similar issue being closed for another similar request [here](https://github.com/typora/typora-issues/issues/3204). It was marked as a duplicate.

Although, I was unable to find the original issue where this request was made. If it does, please share a reference to the same.

Have a great day !! Keep up the good work, guys.

**Comment by ciandorr** [comment]
Agreed, this would be great.  The UI for this could be as simple as having the 'Themes' menu affect only the current window.  To have the theme persist through opening and closing the same document, the theme could be stored in an xattr.

**Comment by abnerlee** [comment]
#488
#2008
