### ISSUE TITLE
Heading identifiers including a colon don't disappear in live editor view

### ISSUE THREAD

**Issue by robwalton** [typora/typora-issues#3423]
Markdown headers may have what Pandoc calls identifiers. In curly braces these are used for internal referencing and for assigning html classes. For example:

    # Heading title {#identifier}

or

    # Heading {#identifier .class .class key=value key=value}

In both these cases the live editor view will correctly hide the part in braces. However If the hashtag contains a colon, for example `{#sec:identifier}` the part in braces is *not* hidden.

Users of Pandoc's popular [pandoc-crossref](http://lierdakil.github.io/pandoc-crossref/) plugin use colons in identifiers all the time.

**Comment by abnerlee** [comment]
`{}` attributes is not supported.

#249
