### ISSUE TITLE
Heading identifiers should not be shown in the outline view

### ISSUE THREAD

**Issue by robwalton** [typora/typora-issues#3424]
Markdown headers may have what Pandoc calls identifiers. In curly braces these are used for internal referencing and for assigning html classes. For example:

    # Heading title {#identifier}

or

    # Heading {#identifier .class .class key=value key=value}

In both these cases the live editor view will correctly hide the part in braces (or make grey while editing). However the part in braces is *not* hidden in the outline view. This is shown in this screenshot:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1565171/78945158-81974600-7ab7-11ea-8fbb-6870639cac4e.png">

**Comment by abnerlee** [comment]
duplicate with #3423
