### ISSUE TITLE
export as docx file, contains math block display problem

### ISSUE THREAD

**Issue by golangscott** [typora/typora-issues#3427]
**when file has some math blocks, and export as docx file, that blocks display problem.**
**typora file math blocks as follow:**
m=(e^{ij\pi}+1)+x^2+y_1+\frac{1}{2}f^{k\frac{3}{4}}+\vec{ab}+\sum{c}+\sum_{n=0}^{100}{a_n}+\int{x}dx

n=\int_{1}^{100}{y}dx+\lim{a+b}+\lim_{n\rightarrow+\infty}+\prod{a}+\prod_{n=1}^{99}b\omega\psi

**docx file display as follow:**
![image](https://user-images.githubusercontent.com/17840910/79044708-47ee4880-7c39-11ea-991d-ce51eecf1e1e.png)

can anybody help me?

**Comment by fparol4** [comment]
Hi @golangscott, i tried and got a normal result i think

![image](https://user-images.githubusercontent.com/47286899/79092124-3fc00700-7d26-11ea-9d4c-83f7f7c5f0eb.png)

maybe you can try to reinstall [pandoc](https://github.com/jgm/pandoc/releases/tag/2.9.2.1)
btw, im running on win10, specify your system please

**Comment by golangscott** [comment]
im running on win10 home version, and the result doc display not well!

**Comment by golangscott** [comment]
and in my personal pc (win10 pro version) the result doc also display not well!

**Comment by golangscott** [comment]
well done, when i uninstall office2007 and install office 2016, the export doc display so well.
