### ISSUE TITLE
Please add a host exclusion option for network image upload

### ISSUE THREAD

**Issue by sevth-developer** [typora/typora-issues#3428]
This is really the best markdown writing software I have used so far, thanks to the author.
But I have a small suggestion, please add a host exclusion option in the network image upload menu. Because when I was writing, when I pasted my picture, when I wanted to change the position of the picture, it was uploaded again.

**Comment by abnerlee** [comment]
> Because when I was writing, when I pasted my picture, when I wanted to change the position of the picture, it was uploaded again.

How you changed the position? I think editing the content won't trigger the re-uploaded.

----

And about "host exclusion", please set in your 3rd app or custom scripts, we don't want to make the configuration too compilcated
