### ISSUE TITLE
Yet Another Problem with Symbol '&' in Reference-style Links

### ISSUE THREAD

**Issue by tswwe** [typora/typora-issues#3429]
This problem/bug exists in the latest release of Typora (for windows x64 0.9.86). It can be reproduced with the following markdown sample:

```
[Text][LinkID]
[LinkID]: https://jq.qq.com/?_wv=1027&k=5tVcZlL
```

Note that the url after `LinkID` contains a symbol `&`.

Now hold <kbd>Ctrl</kbd> and left-click the url string in Line 2, the correct url will be opened:
`https://jq.qq.com/?_wv=1027&k=5tVcZlL`

However, hold <kbd>Ctrl</kbd> and left-click `Text` in Line 1, a wrong url will be opened:
`https://jq.qq.com/?_wv=1027&amp;k=5tVcZlL`

As is showed, the symbol `&` is replaced by `&amp;` in the wrong url.

**Comment by tswwe** [comment]
FYI, I've report an similar issue([#1692](https://github.com/typora/typora-issues/issues/1692)) earlier which is also about symbol '&' and has been fixed. I'm not sure if it has associations with the new one.

**Comment by abnerlee** [comment]
should be fixed
