### ISSUE TITLE
edit css about bg-image,but seems no reaction

### ISSUE THREAD

**Issue by zhu-jl18** [typora/typora-issues#3431]
I edit vue.css by myself,and i want to add a background image.I googled and found to add`css style in content` such as  `content:{-----}`  in the webiste(support.typora.io). But it seems dont work(it ia a method released in 2016),so I export it as html and edit its css.I found to add `body style` worked, but when I start typora ,it dosen`t work. Is there anyone who successed in changing background image and tell me how to da 
![捕获](https://user-images.githubusercontent.com/48956204/79352618-ac2c4780-7f6c-11ea-84c5-eba1038aed6d.PNG)
thanks so much!
```
body {
    background-image: url(/眼镜娘.jpg)!important;
    background-repeat: repeat!important;
   
}
#write {
    margin-top: 24px;
    background-color: rgba(255, 255, 255, 0.68);
    margin-bottom: 24px;
    min-height: calc(100% - 48px);
  }
```

**Comment by zhu-jl18** [comment]
in chorme
![捕获](https://user-images.githubusercontent.com/48956204/79353177-4ab8a880-7f6d-11ea-8671-5f19da56f1d3.PNG)

**Comment by abnerlee** [comment]
You could debug in http://support.typora.io/Add-Custom-CSS/ and confirm the image url is correct relative to css files
