### ISSUE TITLE
image cannot render for relative path in network folders in windows

### ISSUE THREAD

**Issue by shiningbridge** [typora/typora-issues#3433]
e.g. 
* the .md file in \\myserver.com\home\doc\a.md
* image in ./a.assets/image1.png
* `![](./a.assets/image1.png)`

It render perfectly using other editor like VS code with preview plugin.
But broken in Typora. Please help to check. 
Notice for local windows folders it works fine.

**Comment by abnerlee** [comment]
duplicate with #2995
