### ISSUE TITLE
Add case-formatting options.

### ISSUE THREAD

**Issue by lrhn** [typora/typora-issues#3434]
Consider adding case formatting options like "to lower case", "to upper case", "to sentence case" and "to title case", fx to the "Format" menu. It would change the capitalization of the current line or the currently selected text to either all-lower-cased, all-upper-cased, first letter upper-cased or title-cased.

My primary use-case is title casing section titles. Adding just that would be fine .

**Comment by abnerlee** [comment]
#1675)
