### ISSUE TITLE
Mouse selection bug when starting at the beginning of a list item

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#3437]
## Steps to reproduce
1. Open a new Typora window
2. Fill it with the following content:

   ```md
   - foo
   - bar
   ```
3. Click-and-hold the left mouse button over or left from the beginning of the word `foo`
4. Drag the cursor to the end of the word `bar`

## Expected behavior
The selection expands to select both `foo` and `bar`.

## Actual behavior
The selection is limited to the first line; using the mouse it is not possible to select the word `bar`, too, without releasing the mouse button.

## Observations
- Using the following content, it doesn't work either:
   ```md
   - foo
   
   bar
   ```
- Using enumerations (`1. 2. 3.`) instead of listings (`- - - `), the bug does not occur
- If you start the selection right to the first character of `foo`, everything works as expected
- If you start the selection in a previous line (provided that one exists), it works, too
- I could identify a similar bug when making inverse selections, i. e. moving the cursor right-to-left.

**Comment by abnerlee** [comment]
seems can be covered by #2357

Also, possible to provide a screencast since I cannot reproduce this issue?

**Comment by LinqLover** [comment]
Thanks for your answer! I just updated the Steps To Reproduce, can you reproduce it now? Otherwise I will search for a screencasting software ;-)

**Comment by abnerlee** [comment]
@LinqLover Sorry, I still cannot reproduce this.

**Comment by LinqLover** [comment]
Here is a repro recorded in v0.9.96, Win 2004.

![typora-bug-#3437](https://user-images.githubusercontent.com/38782922/101830801-57f65900-3b35-11eb-8370-a2be7eb783c1.gif)
