### ISSUE TITLE
Email freindly copy option with inline CSS

### ISSUE THREAD

**Issue by toger5** [typora/typora-issues#3439]
It is possible to get the exported html from typora which is great. But I cannot find a way to get it nicely formattet to my mail client.

The workaround i currently do:
 - typora: export as html with the css included in the head
 - use juice (a npm package for inlining css) to convert that file into a html with inlined css
 - paste it into my mail client.

What i would like to do:
 - ctrl+a
 - ctrl+shift+c (or any other shortcut for for "copy as HTML with inline css" (or copy as mail...))
 - go to my mail client and press ctrl+v (for that to work the mime type must be set to text/html for the copy buffer by typora)

**Comment by abnerlee** [comment]
Just copy & paste will work

**Comment by toger5** [comment]
Wow!!! Damn how could I have missed that!
This is the best workflow i Could ask for. Sorry for the (in heinseight) stupid Issue.
It is even Inlinign the theme I use!
