### ISSUE TITLE
Allow easier editing of tables in Markdown

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#344]
This TableFlip product has a good idea: http://tableflipapp.com/, visual table creation that converts into Markdown, but buying a dedicated editor (for $18!) for just this one feature seems unnecessary. Perhaps a "lite" version of this functionality can exist in Typora for easier table management?

Incidentally, this product suddenly appeared and is already available for sale. Typora has been around for what seems like a long time, and is yet still not available for sale. It should reach 1.0 and be available to buy soon, as it's a useful product that deserves our $.

**Comment by abnerlee** [comment]
We have add necessary features for table editing, like re-order by drag & drop, etc.

For advanced operation, I will merge into https://github.com/typora/typora-issues/issues/1088

For other operations, #1088 does not mention, you could append to #1088

**Comment by vassudanagunta** [comment]
@abnerlee #1088 was very poorly written. I'd rather you keep this issue open (and close #1088) as Alex is a long time dedicated user and takes the time to write clearly and accurately.

**Comment by abnerlee** [comment]
@vassudanagunta I understand, but this issue is also not clear, it tells us to take a look at tableflipapp, but I'm not sure which function/feature in tableflipapp he wants.

If #1088 is not well written, users would append comments to clarify the features he imagine.
