### ISSUE TITLE
Dark mode support for Windows

### ISSUE THREAD

**Issue by DSlatkin** [typora/typora-issues#3441]
Hi all!

Would love if the app respected Windows dark mode setting. It looks like it already [supports dark mode for Mac](https://support.typora.io/What's-New-0.9.59/), but Windows support may have been waiting on Electron to officially support it, which [happened recently](https://github.com/electron/electron/pull/19217).

Of note: the "Classic" windows style will have the top bar turn black when dark mode for apps is turned on in Windows, but the themes do not update (notably, the default theme) even after restarting Typora.

This is on Typora 0.9.86 beta, Windows 19009.

Thanks so much!

**Comment by abnerlee** [comment]
should be supported
