### ISSUE TITLE
Can't open Theme Folder when ForkLift is the default file manager on macOS

### ISSUE THREAD

**Issue by sunaiwen** [typora/typora-issues#3443]
ForkLift is a Finder-like App that could replace Finder as the default file manager on macOS.

I clicked Open Theme Folder button, Typora just opened ForkLift, and ForkLift just stayed at the last location and didn't jump to the Theme Folder. 

Today is my first time open Typora and I love it! Thanks!

**Comment by abnerlee** [comment]
Typora is using the system API (https://developer.apple.com/documentation/appkit/nsworkspace/1524399-selectfile?language=objc), so it should be ForkLift's bug. But I didn't find may information about which system ForkLift supports and which not.
