### ISSUE TITLE
Internal Links in Typora and VsCode default MarkDown

### ISSUE THREAD

**Issue by IcePigZDB** [typora/typora-issues#3448]
```html 
Anchor:<a name="anchor"></a> Anchor    
Jump:<a href="#anchor">Link to Anchor</a>
```
It works in Typora,but doesn’t work in VsCode default MarkDown.
If i change 'name ' to 'id ',it works only in VsCode default MarkDown .
```html 
Anchor:<a id="anchor"></a> Anchor    
Jump:<a href="#anchor">Link to Anchor</a>
```
Both implements works in GFM,I want to find a General method to achieve internal links in Typora and VsCode,so i come here for help,is there a general method to use ?or some plugins in VsCode may help me ? Thxs .
I have write a simple [test file](https://github.com/IcePigZDB/MarkDownTest/tree/master),it is too long to show here.

**Comment by IcePigZDB** [comment]
I have write some test here ,it seems too long.
# Anchor 1

```html
Anchor1：<a id="anchor1">Anchor1</a>  
Jump1：<a href="#anchor1">Link to Anchor1</a>
```

Anchor1：<a id="anchor1">Anchor1</a>  

# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Jump1：<a href="#anchor1">Link to Anchor1</a>

# Anchor 2
```html
Anchor2：<a name= "anchor2">Anchor2</a>
Jump2：<a href="#anchor2">Link to Anchor2</a>
```

Anchor2：<a name= "anchor2">Anchor2</a>

# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Jump2：<a href="#anchor2">Link to Anchor2</a>

# Anchor 3
```html
Anchor3：<span id="anchor3">Anchor3</span> 
Jump3：<a href="#anchor3">Link to Anchor3</a>
```

Anchor3：<span id="anchor3">Anchor3</span>  

# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Jump3：<a href="#anchor3">Link to Anchor3</a>

# Anchor 4
```html
Anchor4：<span name= "anchor4">Anchor4</span>
Jump4：<a href="#anchor4">Link to Anchor4</a>
```

Anchor4：<span name= "anchor4">Anchor4</span>

# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Jump4：<a href="#anchor4">Link to Anchor4</a>

# Anchor 5
```html
Anchor5：<a id="anchor5">Anchor5</a>
Jump5：[Link to Anchor5](#anchor5)
```

Ancho5r：<a id="anchor5">Anchor5</a>

# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Jump5：[Link to Anchor5](#anchor5)

# Anchor 6
```html
Anchor6：<a name="anchor6">Anchor6</a>
Jump6：[Link to Anchor6](#anchor6)
```

Anchor6：<a name="anchor6">Anchor6</a>
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Jump6：[Link to Anchor6](#anchor6)

# Anchor7
```html
Anchor7： Header :# Anchor7
Jump7：[Link to Anchor7](#Anchor7)
```
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
Anchor7： Header :# Anchor7
Jump7：[Link to Anchor7](#Anchor7)

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by IcePigZDB** [comment]
@abnerlee Thank you，I test on version 0.9.92，`<a id="anchor">Anchor</a>`   is ok .But it seems that `<span id="anchor">Anchor</span>` can not work ,may be you have  your considerations. Thx angin.

**Comment by abnerlee** [comment]
should be fixed

**Comment by IcePigZDB** [comment]
It works ,you guys are very nice ,thank you.
