### ISSUE TITLE
Mathjax inline plus sign '+' sometimes rendered unreadable

### ISSUE THREAD

**Issue by aron-hoogeveen** [typora/typora-issues#3449]
Typora version: 0.9.86
Windows 10 version 1909

There is an issue with inline math where sometimes the plus sign '+' is rendered unreadable and looks more like the minus sign '-'. 
This could be more a mathjax issue than a typora issue, but I do not have enough information on version usage of typora to submit a bug at their Github issue tracker.

![mathjax_hard to read plus sign in inline math](https://user-images.githubusercontent.com/28545476/80276321-554f0c80-86e8-11ea-9063-b9f08f7162f5.PNG)
![Knipsel](https://user-images.githubusercontent.com/28545476/80276402-e7571500-86e8-11ea-8c04-8e5c4c4d305e.PNG)

**Comment by abnerlee** [comment]
It seems a font issue, what's your screen DPI? 
Will zoom out https://www.mathjax.org/#demo makes  "+" sign enough for you?

can be covered by #3475 

relates #3278

**Comment by aron-hoogeveen** [comment]
My DPI is approximately 141.
Zooming in (or out) did resolve the issue.
