### ISSUE TITLE
can't use gif image in macos

### ISSUE THREAD

**Issue by weixiangzhe** [typora/typora-issues#345]
![image](https://cloud.githubusercontent.com/assets/14126445/19218441/a8a1ac98-8e2c-11e6-8822-7967c8ec535a.png)
In window  I could view gif but not in mac

**Comment by abnerlee** [comment]
Does `eslint004.gif` file exists relative the the `*.md` file?

**Comment by weixiangzhe** [comment]
oh sorry. i  had dragged  a gif to typora then path is wrong .I will close this issue
