### ISSUE TITLE
Side by Side Liveview

### ISSUE THREAD

**Issue by matthiasbaldi** [typora/typora-issues#3453]
Hi
I use Typora for a while and I am very happy with it.
But do you plan to have a side by side live view?
Sometimes when I work on wide screens I have enougth space to split the view in two pieces and to write code i.e. in the left half and to see the output on the right.

May there is already an issue for that, but I did not found something like this...
Thx. 👏

**Comment by abnerlee** [comment]
#3184

We don't have plans for this. But you can use two Typora window for same file side by side

**Comment by ovitrif** [comment]
It would be really nice if you add this.
The new Arc browser has the same functionality for websites and it's super awesome when you want to just peek a little into another file.

Are you actually adding any new features to the product? It's making money so ideally it should be extended.
