### ISSUE TITLE
condition display incomplete

### ISSUE THREAD

**Issue by liangfeng093** [typora/typora-issues#3454]
```flow
st=>start: 开始
e=>end: 结束

op1=>operation: 点击登录按钮
io1=>inputoutput: 输入用户名
io2=>inputoutput: 输入用密码
op3=>operation: 请求接口
op4=>operation: 进入home页面
op5=>operation: 本地缓存token
op6=>operation: My Operation2
cond=>condition: UserName is not empty ?
cond1=>condition: PassWord is not empty ?
cond2=>condition: isSuccess
io3=>inputoutput: 弹吐司，提示用户UserName不能为空。
io4=>inputoutput: 弹吐司，提示用户PassWord不能为空。
io5=>inputoutput: 弹出Toast,提示网络异常
io6=>inputoutput: 弹出Toast,提示服务器异常
cond3=>condition: messageCode == 0 ?
cond4=>condition: 正则校验 is phoneNum || email
io7=>inputoutput: 弹出Toast,提示"账号只能使用手机号或者邮箱"

st->io1->io2->op1->cond
cond(no)->io3(top)->io1
cond(yes)->cond1(no)->io4(top)->io2
cond1(yes)->cond4(yes)->op3->cond2(no)->io5->e
cond4(no)->io7
cond2(yes)->cond3(yes)->op5->op4->e
cond3(no)->io6->e

io3@>io1({"stroke":"Red"})
io4@>io2({"stroke":"Red"})
io5@>io1({"stroke":"Red"})
```
In Typora, the content of cond4 is not fully displayed, what should I do to make it complete
Please help me ，thanks！

**Comment by abnerlee** [comment]
I cannot reproduce this. Possible to add a screenshot and what's your Typora version?

**Comment by liangfeng093** [comment]
> 我无法重现。可以添加屏幕截图，您的Typora版本是什么？

![image](https://user-images.githubusercontent.com/25739714/82015142-a54e3d00-96b0-11ea-85ed-00f568a68e39.png)
![image](https://user-images.githubusercontent.com/25739714/82015164-b1d29580-96b0-11ea-8c11-6494ee10da3e.png)

**Comment by abnerlee** [comment]
"flowstate is optional and uses the | operator that specifies extra styling for the node." from  https://github.com/adrai/flowchart.js/blob/master/README.md
