### ISSUE TITLE
Math mode macros sometimes render incorrectly.

### ISSUE THREAD

**Issue by rconnorlawson** [typora/typora-issues#3455]
OS: Ubuntu 16.04
Typora version: 0.9.86

In a large document with lots of math, including some \newcommand and \renewcommand macro definitions at the top of the file (I'm working on my thesis proposal), the results displayed when not editing a math listing are inconsistent with the preview displayed during the edit. The preview is correct; the displayed result is not. Closing and repoening the file resolves the inconsistencies. The issue has the appearance of a render caching bug; see the examples below.

I hesitated to write this issue because I can't produce a minimum working example. It seems like the document has to be both long enough (total quantity of text) and math-y enough (number of equations) for this to appear, but I don't know the threshold. It won't show up on very short documents. Hopefully the examples below are enough, and I can give more feedback if needed.

**Example.** This bug appears most often when changing a macro definition or adding a macro. Consider an existing macro definition `\newcommand{\X}{\mathbb{X}}`. I have many uses of this macro inline in my document, for example `$x \in \X$`. Upon changing the macro definition (e.g. to use `\mathcal` instead of `\mathbb`), issues appear:

1. Existing uses of `\X` do not reflect the update. So `x \in \X` would still render using the old definition of `\X`. This could be a necessary optimization, but it would be nice to automatically update the uses immediately when the macro changes.
2. When editing an existing use of the macro, the displayed result (i.e. while not editing) only updates _if the content of the listing has changed_, while the preview (i.e. during editing) always displays the current definition correctly.

    1.  Consider that I enter math edit mode but **don't** change the text. While editing, the preview will show the new definition. But upon leaving edit mode, the result will still show the old definition.
    2. Consider instead that I enter edit mode and **do** change the text, for example to `y \in \X`. Then both the preview and the result are correct. But if I later change the text back, the incorrect result returns.

**Example 2** A similar behavior happens when defining a macro that was previously undefined, but was already in use in the document. In that case, the result render includes the offending macro text in red. After defining the macro, the same rendering behavior appears as in the first example.

**Comment by abnerlee** [comment]
Does this still occur in latest version?
