### ISSUE TITLE
Create a hint that typora uses its own incompatible flavor of markdown

### ISSUE THREAD

**Issue by f1reflyyyylmao** [typora/typora-issues#3457]
I just tried to render a markdown document created with typora by another student using pandoc in github compatible mode, expecting it to render correctly, because, you know, it says it's github flavored markdown.

I discovered that you seem to not only completely ignore how math works in 'normal' markdown, but you also didn't say anything about that at any point on your website. You should at least write in your documentation that your version isn't compatible with other markdown interpreters.

**Comment by syrte** [comment]
It would be nice if you could share more information, what's the result and what's your expectation, then the author can better help you.
I'm afraid this is a very common problem for any markdown editor. There are too many flavors and details of implementations.

**Comment by f1reflyyyylmao** [comment]
The math mode of typora is incompatible with the rest of the markdown world. The same with diagrams. You advertise that documents created in Typora can be exported to markdown. 
```
$$ \sum_{¡=1}^{n+1}j^2 $$
```
Translates to a display math block in every popular markdown flavor. It doesn't do anything else. It does not support environments. In fact, it doesn't even support line breaks. Typora on the other hand uses the `$$` tags as some kind of combined LaTeX (math mode?) tags and exports it as such. This isn't markdown, so somewhere on the site you should probably write that Typora uses its own flavor or, if applicable, extends some other version. 
The fact that pandoc is mentioned as part of your project makes things even more confusing, since the markdown documents cannot be converted to anything using pandoc, which is the jack-of-all trades markdown tool. My guess here is that you feed the html document that's shown to the user into pandoc directly which would also explain the atricious typesetting, but nevermind that.

**Comment by abnerlee** [comment]
>  You should at least write in your documentation that your version isn't compatible with other markdown interpreters.

For a markdown editor, of course markdown editor A will have incompatible with markdown B, there's no standard one.

```
$$ \sum_{¡=1}^{n+1}j^2 $$
```

is not rendered by Github or by Gitlab Books (which uses <code>```math</code>), actually it is not supported by most of the markdown world. 

There are other issues about different markdown syntax here.

---

But anyway, I will add such hint in our wiki site
