### ISSUE TITLE
Don't treat ' symbol as the single quote in Ukrainian

### ISSUE THREAD

**Issue by viiibe** [typora/typora-issues#3460]
On Ukrainian (Extended) keyboard layout, what's typically the "apostrophe" key (located in the place of tilde) inserts the ``'`` symbol, which is treated as a single quote and thus inserts the opening and the closing quote. 

Is there any way to disable this behavior for Ukrainian specifically? The language doesn't use single quotes at all anyway.

**Comment by abnerlee** [comment]
which OS?

**Comment by katktv** [comment]
Windows 10, update 1909 iirc.

**Comment by viiibe** [comment]
Can replicate the issue on macOS 11.3.1 when using the Ukrainian - PC layout.

**Comment by abnerlee** [comment]
What about other apps like support auto pair quotes and brackets?

**Comment by abnerlee** [comment]
We fixed in macOS

But in Windows / Linux, we cannot know if user currently is typing Ukrainian.

We still wonder how other apps support this.
