### ISSUE TITLE
Some discordance between math rendering and cursor position

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3461]
OS:win10 | Typora Version:0.9.86
The problem(little inconvenience) is very simple: type some inline math, keep the caret in middle of the dollar signs, then press the hotkey for math rendering or click the options tab(The option is called refresh all math expressions). And, yes, math formulae are refreshed correctly but static cursor jumps to the head of the formulas (id est exactly after the first dollar sign). If you wrote a long formula, it's gonna be a laboured situation.

**Comment by abnerlee** [comment]
should be fixed
