### ISSUE TITLE
Some improvement for writing comment in math block

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3462]
OS win10 | Typora version: 0.9.86
![image](https://user-images.githubusercontent.com/46404230/80619065-becb7400-8a76-11ea-8f0b-02d8db814891.png)
Is there any possible way to display the line below the percentage sign as well as that before it?
This probably related to Mathjax, I not sure of it.

**Comment by abnerlee** [comment]
should be fixed
