### ISSUE TITLE
rendering is stuck when there are many pictures 

### ISSUE THREAD

**Issue by HelperInCa** [typora/typora-issues#3463]
Typora Beta 0.9.9.32.1
One of my text contains many pictures(314 lines, 3000+ words). When I switch to this text, rendering is always stuck but others that have 5000+ words(most are characters not pictures) are smooth. I am not familiar with the theory of rendering. Is there any suggestion for me to solve this problem?

**Comment by abnerlee** [comment]
duplicate with #3402

How many pictures are there, and how large one image is?

**Comment by HelperInCa** [comment]
less than 200 pictures, every picture less than 1MB. I will issue in #68.
