### ISSUE TITLE
/bin/bash: picgo: command not found

### ISSUE THREAD

**Issue by zenchen3331** [typora/typora-issues#3464]
不好意思 我的英语很烂 请允许我用中文描述

**当我测试上传图片的时候报错了**

###   【图像】配置信息
![image](https://user-images.githubusercontent.com/23417064/80641175-0b26ac00-8a97-11ea-8c77-a5978f06875b.png)

###   报错信息
`/bin/bash: picgo: command not found`
![image](https://user-images.githubusercontent.com/23417064/80639655-e6313980-8a94-11ea-9f1d-b6e92cb0b22a.png)

### 自我检查
**我的 node 环境和 picgo 配置都没有问题**

![image](https://user-images.githubusercontent.com/23417064/80640797-820f7500-8a96-11ea-967a-85d771854b96.png)

**实际上我成功配置了 PicGo-Core（命令行）上传图片**

![image](https://user-images.githubusercontent.com/23417064/80640907-a8cdab80-8a96-11ea-8f00-dc797947d39b.png)

**但是当我使用管理员权限运行 Typora 的时候**
- sudo 命令启动 Typora
![image](https://user-images.githubusercontent.com/23417064/80642845-b8022880-8a99-11ea-8dd8-3abc3db4f469.png)
- 图片上传成功
![image](https://user-images.githubusercontent.com/23417064/80642820-b0428400-8a99-11ea-9b76-ddbbf2e447f7.png)

### 我知道这并不是 Typora 的问题
能否帮我找出来问题所在
我想知道如何解决这种类似“路径”或者“权限”的问题

其他说明：
- 我只有一个用户 zzzl（管理员）
- 我忘记 npm 和 node 是否是用 sudo 命令安装的了，但 zzzl 有 node 的环境变量的配置，因为我可以成功执行 node -v 。

**Comment by abnerlee** [comment]
可以 用 which node 和 which picgo 找到它们的路径

然后用 custom command 
```
{node-path} {picgo-path} u
```
上传

see
http://support.typora.io/Upload-Image/#custom

**Comment by zenchen3331** [comment]
解决了我的问题。
感谢！

**查找路径**
![image](https://user-images.githubusercontent.com/23417064/81393434-f14e2e80-9152-11ea-83d9-633f4bd46703.png)

**更新配置**
以前我以为环境变量配置的没问题，在终端上执行`picgo u`可以上传成功图片。
就把 Typora 的上传命令配置成了 `picgo u`，现在改成了完整路径 `/usr/local/bin/node /usr/local/bin/picgo u`，立马解决了我的问题。
![image](https://user-images.githubusercontent.com/23417064/81393538-1f337300-9153-11ea-8580-4c5978c15479.png)


**一直以为是权限问题，找的方向错了，使用全路径解决问题。**

**Comment by forlornMWS** [comment]
您好，我也遇到了类似的问题，使用全路径以后仍旧无法上传请问有什么解决方法呢？
![image](https://user-images.githubusercontent.com/48377389/103332757-3dfdc580-4aa6-11eb-9637-3bf08ed2330b.png)
![image](https://user-images.githubusercontent.com/48377389/103332786-64bbfc00-4aa6-11eb-8d9b-39960ba9d8ce.png)
在terminal里直接运行命令是可以成功运行的：
![image](https://user-images.githubusercontent.com/48377389/103332887-cd0add80-4aa6-11eb-8679-17d097cf9298.png)

**Comment by lijiazezju** [comment]
为什么用了这个办法我还是解决不了，我是ubuntu系统

**Comment by forlornMWS** [comment]
你可以重新下载typora试一下，之前我的typora是从snap store里面安装的，自定义命令也没有成功，后来从[官网](https://typora.io/#linux)下载安装以后就可以了

**Comment by abnerlee** [comment]
snap 版本有沙盒的限制 （https://forum.snapcraft.io/t/system-files-request-for-typora-snap-app/28740）

未来会增加关于 snap 限制的描述
