### ISSUE TITLE
SHIFT+UP DOWN Text Selection does not work

### ISSUE THREAD

**Issue by meet-v** [typora/typora-issues#3465]
Hello.

I have started using Typora since a few months. And it works wonderfully.
However, there's a little thing that's bothering me too much - Selection of text using Keyboard.

Take example that below is my text in typora:
`This is a sample text. This is a sample text. This is a sample text. (3)`
`The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. (6)`
`This is for testing the issue. This is for testing the issue. (2)`

Now, if I want to select a particular part of the text - say I want to select from the third quick brown sentence to fifth. To do that, I will first move my cursor to the start of the third quick brown line, which is in second para. Then I will use SHIFT+DOWN ARROW combination to select second and third line, which will select two quick brown sentences, and then use CTRL+SHIFT+RIGHT ARROW to select to the end of fifth quick brown sentence. (This is the case with any text editor, say word or notepad, even here while writing this query, I used the same thing to select text in a particular paragraph.)

However, this doesn't work in Typora.

As soon as I press SHIFT+Any ARROW Key combination, it selects the text, and then the cursor disappears. And none of the keyboard keys work, till I use my mouse to bring back the focus to the paragraph. Result - I can select at max one line using keyboard shortcut.

Now, a workaround - if I select text using LEFT or RIGHT arrow key, it works fine. This issue is only when I use UP or DOWN arrow key to select a chunk of text altogether, which is usually my case.

I have tried to explain the scenario, I hope this is clear.

Please help me with this.

P.s.: I found this bug in Typora, MarkText, and Zettlr.
Is this something relating to Markdown language? Or all three applications have the same bug, just a co-nincidence?

**Comment by abnerlee** [comment]
similar or duplicate with #3192 / #1164
