### ISSUE TITLE
I would love to number diagrams and be able to reference them by their number.

### ISSUE THREAD

**Issue by EganSolo** [typora/typora-issues#3466]
I would like to write this:

```sequence
Title: Flow 1 -- Basic Hellow Flow
Andrew->China: Says Hello
Note right of China: China thinks\nabout it
China-->Andrew: How are you?
Andrew->>China: I am good thanks!
```
As can be seen from [Flow 1] ...

And there would be a feature to renumber all the diagrams and refresh all their references. Is that even possible? On the roadmap? Too nuts to consider?

:)

**Comment by abnerlee** [comment]
should be covered by #105 and #249
