### ISSUE TITLE
per project preferences

### ISSUE THREAD

**Issue by yashaka** [typora/typora-issues#3468]
I would love to be able to specify typora preferences per "project". 

For example I can edit my book markdown files inside the "book folder" and have there corresponding setup:

![image](https://user-images.githubusercontent.com/1961118/80693101-36cb8580-8adb-11ea-8cf1-b68c5fe8e982.png)

But inside my "Documents" folder i would like to have simpler:

![image](https://user-images.githubusercontent.com/1961118/80693242-637f9d00-8adb-11ea-98f8-5482b75f7cd7.png)

**Comment by abnerlee** [comment]
#3109
