### ISSUE TITLE
Can't find option to select themes after installing files to Theme Folder on mac

### ISSUE THREAD

**Issue by wyins** [typora/typora-issues#3469]
I've installed theme files in the theme folder and restarted typora, however I am unable to select any themes from the Appearance tab (it doesn't show up anywhere I can find).
Even the pre-installed default themes do not show up. Hope I'm not just missing where it is, thanks.

![Screen Shot 2020-04-30 at 15 49 58](https://user-images.githubusercontent.com/64599080/80725123-91c0a500-8afa-11ea-97d7-67ee763cbd4b.png)
![Screen Shot 2020-04-30 at 15 50 40](https://user-images.githubusercontent.com/64599080/80725137-9422ff00-8afa-11ea-8525-93c78697fa8e.png)

**Comment by abnerlee** [comment]
The themes are selectable from menu bar, not in preferences panel. Maybe we should add a hint for this.
