### ISSUE TITLE
Incorrect text selection for double click with live rendering

### ISSUE THREAD

**Issue by claytonrcarter** [typora/typora-issues#347]
Live rendering can cause the word and/or line layout to change because non-printing characters are shown, causing a reflow of the text.  This can interfere with text selection while double clicking.

For example, if the mouse is placed at the start of the word "this" in the following snippet:
![pre-click](https://cloud.githubusercontent.com/assets/1420419/19223471/c75b0c4e-8e3e-11e6-8e39-d4fcf1821751.png)

A single click will place the cursor correctly:
![single-click](https://cloud.githubusercontent.com/assets/1420419/19223472/d31d028a-8e3e-11e6-883d-21ee0adf2d7e.png)

But a double click will incorrectly select the preceding word:
![double-click](https://cloud.githubusercontent.com/assets/1420419/19223473/d3269016-8e3e-11e6-97fb-e38cb71d965c.png)
I would have expected "this" to be selected instead.

Similarly, if the reflow causes words to move between lines, unexpected behavior can happen.  For example, before I click on "Painless", a snippet looks like this:
![pre-click](https://cloud.githubusercontent.com/assets/1420419/19223512/cb19c4c8-8e3f-11e6-88dd-71e90f675c3e.png)

After clicking on "Painless", the text reflows onto a second line:
![click](https://cloud.githubusercontent.com/assets/1420419/19223513/cb25a284-8e3f-11e6-9929-f05aff4ecd97.png)

A single click on "deploy" will work as expected: (Note the cursor in "deploy".)
![single-click](https://cloud.githubusercontent.com/assets/1420419/19223514/cb674cca-8e3f-11e6-89ce-5cc0a5cc1d0a.png)

But a double click on "deploy" will select "Package":
![double-click](https://cloud.githubusercontent.com/assets/1420419/19223515/cbbacd0a-8e3f-11e6-88fb-60d6a7f42468.png)
I would have expected "deploy" to be selected.

**Comment by abnerlee** [comment]
A delay is added for single click in new version. So this should be fixed.
