### ISSUE TITLE
[Feature request] fast file navigation with keyboard

### ISSUE THREAD

**Issue by syrte** [typora/typora-issues#3470]
I really love Typora which is an amazing masterpiece. Here I would like to propose a small request to enhance the folder tree sidebar.

I have a folder containing a lot of notes and want to flip over to review the note contents. In the present Typora, it seems that I have to mouse-click the files one by one. FYI, I'm using Linux and a Typora binary release (Typora-linux-x64).
In an ideal case (in my mind), when I clicked a file in the sidebar, the folder tree can retain the focus (or seize the focus back after pressing e.g. ESC if it has lost it), then I can navigate the files with the arrow keys.

Another solution is to make shortcuts for switching to the previous/next files in the folder. Nevertheless, I didn't find related functions in the documentation.

Thank you very much for your consideration.

**Comment by abnerlee** [comment]
#3470 #1001 #3417
