### ISSUE TITLE
Renaming files and folders

### ISSUE THREAD

**Issue by aaronkagan** [typora/typora-issues#3471]
Hi i noticed that when i rename files or folders the change doesn't display until i reload the program.
Have a wonderful day 
Version 0.9.86(beta)

**Comment by abnerlee** [comment]
rename in Explorer or in Typora?

**Comment by aaronkagan** [comment]
In typora 
Warmly,Aaron Kagan 

    On Wednesday, May 6, 2020, 11:15:15 a.m. GMT-4, AbnerLee <notifications@github.com> wrote:  
 
 


rename in Explorer or in Typora?

**Comment by abnerlee** [comment]
should be fixed

**Comment by abnerlee** [comment]
relates #3376
