### ISSUE TITLE
Auto complete frontmatter tags

### ISSUE THREAD

**Issue by crazychenz** [typora/typora-issues#3472]
Related to #1393

#1393 discusses providing the ability to lookup articles based on tags in the content. I would love to see an optional autocomplete suggestion list when trying to determine what tags to add to the content.

My specific use case is Typora either detecting that I am in a frontmatter tags and auto suggesting automatically, or providing a right-click option on a highlighted word or abbreviation and having Typora attempt to suggest similar tags already indexed.

As a developer, I imagine a quickest to market indexing strategy for this specific issue/proposal would be to create an index on the fly when using "Open Folder...". Otherwise, If there is already an effort to index all of the content tags, this feature would compliment that nicely.

**Comment by abnerlee** [comment]
This should be covered by #1393, after all, we will need to provide tag support, then consider improvements about "tags", like auto complete
