### ISSUE TITLE
Search becomes sluggish/unusable with large document

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#3474]
With a large MD, in this case 794KB, the text search within the document becomes non-responsive.  While typing, the interface stalls also.

![image](https://user-images.githubusercontent.com/58857646/80991021-6218e200-8e05-11ea-8587-1555abd01124.png)

**Comment by abnerlee** [comment]
should be improved now, in my test, it is still slow, but won't be non-responsive

**Comment by coinzdude** [comment]
@abnerlee  We split our documentation into sub MD files in a folder which typora handles brilliantly.  Then, from the "Files" view, if you scroll up (which is confusing, I'll log another issue) search seems "instant", and spans all the sub documents.  We have 1.6MB of documentation text.
