### ISSUE TITLE
Outline collapses in toggle source code mode 

### ISSUE THREAD

**Issue by ChroniclerEnigma** [typora/typora-issues#3476]
Hello! I just started using Typora, and so far im really loving it for being able to quickly navigate my work files! I work primarily in personal mangement, long form story writing, and world building organization (wiki) type of stuff. I have all kinds of art files that i leave progression notes on as well, so I'm writing ALOT. My documents become very long form quite easily, and i like to use source code mode to quickly edit, get into the zone, and then preview how it looks by leaving source code mode. I absolutely love this feature. But i have one problem: The document outline disapears. This is very inconvenient for navigating large files, quickly copying and pasting and reordering structure, (which, possibly would be made easier if sections were reorderable via the outline, rather than hard copy pasting, though I'm not in dire need of that,) or character profiles with meticulous subsections for their traits and abilities. 
If this is possible to fix, I would be using typora all the time. I'm switching between ghost writer and typora for this reason only. 
In any case, this is an amazing project, so thank you for your hard work!

**Comment by abnerlee** [comment]
duplicate

**Comment by abnerlee** [comment]
#2522 #2863 #2335 #538
