### ISSUE TITLE
Exporting multiple files in a folder

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3481]
I use Typora for academic purposes and I am enjoying it already. However, I find it ridiculous that Typora is not able to work with projects from a folder. Anyone who uses Markdown for purposes other than creating websites, wants to create a project with a top directory and sub-directories and arrange materials the way he/she requires. At the moment Typora cannot compile or create a single PDF or epub from a single folder, why?
I am aware that this may be a repeat of previous issues including [824](https://github.com/typora/typora-issues/issues/824) but this is totally unacceptable!

I have been able to create a bash file to export multiple files based on this project [https://github.com/wikiti/pandoc-book-template](https://github.com/wikiti/pandoc-book-template) and I do not see why not such simple operation could not be implemented within Typora!

By the way, the https://github.com/Zettlr/Zettlr shines in this area.

**Comment by abnerlee** [comment]
#824
