### ISSUE TITLE
Improve UI for Search in sidebar

### ISSUE THREAD

**Issue by tenbob** [typora/typora-issues#3482]
For me, the user interface to the sidebar Search function is really cumbersome. Maybe I'm missing something, but this is how I access it.

- Hover at the bottom left corner of the screen to reveal the hidden area
- Click the three dots button that appears
- A poup menu appears
- Find the entry for Action>Search and click it
- A search box appears at the opposite corner of the screen, top left
- Type the search words and hit return

This seems a lot of steps and the focus moves about to different parts of the screen.

This is what I would like to see. A small button with a symbol like a magnifying glass. Click it and it expands into a search box. Enter your search terms and go.

I think this should be easy to do without taking up much real estate.

**Comment by tenbob** [comment]
A further thought on the Search UI. Perhaps the main issue is that the Search pane in the sidebar keeps disappearing after you have used it.

As far as I can tell the sidebar can display the following types of content

- Files as a list
- Files as a tree view
- Outline
- Search box with the search results below

The actions to switch between the four types of content are all completely different. 

There is a button to change the file display between list and tree view.

There is a heading at the top of the pane to switch between Files and Outline

There is nothing to make the Search pane appear with a single click. To get the Search pane you have to follow the steps in my OP. Once it is open you can go back to Files by clicking the heading. But then the other heading changes back to Outline, so you can't go back to Search again.

So another way to simplify the UI would be to have a simple button to cycle between all four types of content in the sidebar. This would be much easier to understand.

**Comment by abnerlee** [comment]
We don't want to put too much icons there.

You could use the "search" icon on macOS, shortcut keys or scroll to toggle search panel

**Comment by iwan-uschka** [comment]
Are there any shortcut keys to activate the search in the sidebar?

**Comment by hyzgh** [comment]
![image](https://user-images.githubusercontent.com/31174102/147468461-2105cfab-d6d3-46d6-9761-2b11f336de8f.png)
@abnerlee Is there any shortcut key to activate the search in the sidebar?
