### ISSUE TITLE
find next button presed, and the scroll step was wrong

### ISSUE THREAD

**Issue by lfire** [typora/typora-issues#3483]
1. step 1, type some text in search input, and prese enter to confirm search.

2. step 2, and the prese enter, or click the find next button arrow on the right side.

I found the hilight text can't see on the first screen, if I switch the app to another, and then switch back to typora, and I found the performance will be correct now.

![image](https://user-images.githubusercontent.com/2528719/81241497-020c8080-903d-11ea-9340-be9f7cfeb7bb.png)

![image](https://user-images.githubusercontent.com/2528719/81241506-089af800-903d-11ea-989f-4b281e6d327c.png)

the MD file sample
[git.zip](https://github.com/typora/typora-issues/files/4590094/git.zip)

This problem likes only appear with file use chinese words.

**Comment by abnerlee** [comment]
duplicate with #3533 which have a better description.
