### ISSUE TITLE
Typora software crashes

### ISSUE THREAD

**Issue by Michael18811380328** [typora/typora-issues#3484]
OS version: macOS High Sierra 10.13.4 (17E199)
Typora version: 0.9.9.32.1 (4191) beta version for preview
Reproduce the error: Recently I updated typora to the latest version (about two months ago), and I found that sometimes I edited some markdown files and typora crashed. I tried to restart the Mac or reinstall typora, but this error still exists. I am afraid my markdown file will be damaged when typora crashes, so my file is lost! Can you tell me how to solve this problem? Thank you!

**Comment by abnerlee** [comment]
same error message with #2972?

**Comment by Michael18811380328** [comment]
Thanks

**Comment by Michael18811380328** [comment]
> same error message with #2972?
> 
> Possible to provide the crash log, or steps to reproduce?

Yuèdú#2972 hòu, wǒ fāxiàn wǒ de cuòwù yǔ nàgè cuòwù bùtóng.
Wǒ de wèntí shì: Wǒ kěyǐ chénggōng dǎkāi páiyìn, dànshì biānjí jiàngjià shí, páiyìn túrán bēngkuìle.
57/5000

After reading # 2972, I found that my error was different from that error.
My question is: I can successfully open the typora, but when editing the markdown file, the typora suddenly crashed.
