### ISSUE TITLE
Suggestion:provide API to distinguish saved&unsaved files

### ISSUE THREAD

**Issue by unbadfish** [typora/typora-issues#3486]
Hi!
I think that the program didn't give the usersan eye-catching way to mark off the unsaved files
(i know this program provide a copy of all unsaved files,but my security software often clean them up without my permission:sob:,and i believe that a GREAT number of people have similar experince)
So, I suggest adding an API for the themes to distinguish the saved/unsaved files(also their parent folders)
Maybe you could use a orange circle with a white '!'inside to mark the unsaved files&folders

**Comment by abnerlee** [comment]
I actually didn't receive similar requirements from other users, and how will this solve the issue of "my security software often clean them up without my permission"?

**Comment by unbadfish** [comment]
Ok, that's fine. But I still suggest you add this kind of Api.I know that there is a '*' for the unsaved file in the tittle,but it is not so eye-catching.



---Original---
