### ISSUE TITLE
subscript in heading broken between MacOS Mojave and Catalina

### ISSUE THREAD

**Issue by allohakdan** [typora/typora-issues#3488]
I use math blocks, and subscripts in particular, in headings. 

For example

```
### DO TODAY $_{Urgent/Must}$ 
```

Renders as

<img width="233" alt="Screen Shot 2020-05-08 at 11 31 37 AM" src="https://user-images.githubusercontent.com/119465/81421770-02ca1300-9120-11ea-9dc0-6ae2db7081cf.png">

This was working in Typora 0.9.9.32.1 (4191) running on MacOS Mojave 10.14.6. Using the same version of Typora running non Catalina 10.15.4, the math block no longer renders. 

![2020-05-08](https://user-images.githubusercontent.com/119465/81422257-b501da80-9120-11ea-9aa3-acc88076edb5.png)

**Comment by abnerlee** [comment]
duplicate with #1507
