### ISSUE TITLE
Error while loading shared libraries: libgtk-3.so.0

### ISSUE THREAD

**Issue by ralpha** [typora/typora-issues#3489]
I got this error on Linux Mint 19.1:
```
$ typora 
typora: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```
Even though libgtk-3.0 is installed on my system (with apt).
Tried installing `libgtk-3-dev` but same result.
The file `/usr/lib/x86_64-linux-gnu/libgtk-3.so.0` (link and file) are present on my system.

(used these instructions to install: https://typora.io/#linux )
Version installed (as seen through apt): 0.9.70-1

**Comment by ralpha** [comment]
I just checked my `/usr/share/typora` folder where is was installed and the version file there said: `v3.0.14` and my download from website is `6.1.5`. So is the apt-repo out of date or is it something else? Both folders look very different.
![Screenshot from 2020-05-08 21-02-13](https://user-images.githubusercontent.com/2608639/81439804-3d0ed100-916f-11ea-81c9-847e145af9fb.png)
Left is download from website `Typora-linux-x64.tar.gz` and Right is from apt repo.

**Comment by abnerlee** [comment]
There are instruction on Mint: http://support.typora.io/Typora-on-Linux/

You could use `sudo apt-get update` to update the apt-get, 0.9.70 is not the lastest version
