### ISSUE TITLE
Automatic line break when a header is at the end of a page

### ISSUE THREAD

**Issue by abdellatifLabr** [typora/typora-issues#3490]
I want to know if there's a way to add automatic line break when a header is at the end of a page.
to avoid this case:
![image](https://user-images.githubusercontent.com/17796722/81459047-b4eff200-9195-11ea-886a-96cde2940817.png)

**Comment by abnerlee** [comment]
Possible to attach or send us the sample file?

**Comment by labTifo** [comment]
u can't attach markdown file cuz github doesn't support that.
but there's download link [https://drive.google.com/open?id=1f7BudAy5A3aJ2z5zNq57F98iEsias2z7](https://drive.google.com/open?id=1f7BudAy5A3aJ2z5zNq57F98iEsias2z7)

**Comment by abnerlee** [comment]
duplicate wht #1472

should be fixed in new release
