### ISSUE TITLE
Save / Discard / Cancel dialog not accessible with keyboard (have to use mouse)

### ISSUE THREAD

**Issue by dibr0006** [typora/typora-issues#3494]
![Screenshot3377](https://user-images.githubusercontent.com/7694112/81546475-b8909e00-937a-11ea-933c-b6ffe2ab79ea.png)
Is there any way to interact with the dialog shown in the screenshot **without** using the mouse? When the dialog is shown, the focus is allways in the text.

Version: 0.9.86 (beta)

**Comment by abnerlee** [comment]
duplicate with #656
