### ISSUE TITLE
Search does not reset when new search is started

### ISSUE THREAD

**Issue by pixmin** [typora/typora-issues#3499]
**Problem:**
When I focus a typora document and start a search, often it appends what I type to an old search term, so I have to remove everything in the search field, then type again what I want to find, this is wasting a lot of time.

**Example:**
I press CTRL F to search something (ex: `notation`), Typora founds it, I read what I need, go back to my browser / code editor, do something else. A while later I need to find something in the same typora document, I focus the window, do CTRL F and start typing what I want to find: `foobar` but it won't find it because what is actually happening is that it is appending `foobar` to my old search `notation`, so of course it won't find `notationfoobar`. So I need to reset the search field and type again `foobar`...

**Solution:**
As with Chrome (and I believe most software providing a search functionality) it should at least focus the search field AND preselect the existing text (if there is any) so that I can either start typing my new search (and the old one will be replaced) or I can move the cursor to the right if I want to append to the existing search...

Thanks :)

**Comment by abnerlee** [comment]
In my test, the search input will be selected & focused automatically, what's your Typora version and could you attach a screencast for reproduction?

**Comment by abnerlee** [comment]
relates #3533
