### ISSUE TITLE
PLS add line number in code block

### ISSUE THREAD

**Issue by xxf1995** [typora/typora-issues#35]
Missing line numbers in huge code blocks can be a issue in explaining which line to look at. I believe it is an easy thing to implement but it is quite important :)

**Comment by abnerlee** [comment]
available in preference panel from v0.8.3

**Comment by xxf1995** [comment]
Thx for the update!

**Comment by zshyang** [comment]
What does it mean by preference panel?
Do you mind elaborate that?

**Comment by Alex-Zeyu** [comment]
> What does it mean by preference panel?
> Do you mind elaborate that?

You can set the line numbering in the preference setting.
![WechatIMG5](https://user-images.githubusercontent.com/26573988/88448819-08f4a380-ce74-11ea-8c82-01c34de09aff.png)

**Comment by zshyang** [comment]
Thanks!
