### ISSUE TITLE
App sometimes suddenly crashes without response 

### ISSUE THREAD

**Issue by Neohiro79** [typora/typora-issues#3500]
App sometimes crashes in form of having no " _ | max | X " icons in the windows bar.
You only see three very small cubes, as if there is no font loaded or the wrong iconfont whatever.

When that happens, you cannot "click" in the document or do anything else.

**actual Workaround:**
close and reopen as often as neccessary, till the windows handles appear again.
Sometimes I need to do so three or four times till this happens.

System is Windows 10 -  1909 - and it also happened on those windows versions "before" ...

**Comment by abnerlee** [comment]
#3019
