### ISSUE TITLE
Scroll bar really could be "1 or 2 pixels wider" ...

### ISSUE THREAD

**Issue by Neohiro79** [typora/typora-issues#3501]
I cannot tell how much I missed to grab the scrollbar ...

I love Zenstyle, but full 8 pixels in total, really?

Could you please add at least an option of "widening" the size of the scrollbar to an "extended" version of say 12 or 15 pixels in one of your next versions?

**Comment by abnerlee** [comment]
We don't support too much UI options. You can use http://support.typora.io/Add-Custom-CSS/ to modify it.
