### ISSUE TITLE
Question: How to create a front page? [MacOS, Version 0.9.9.32.1 (4191)]

### ISSUE THREAD

**Issue by keyboardAnt** [typora/typora-issues#3502]
Yeah, OK, I get it. You gonna send me to read [https://jekyllrb.com/docs/front-matter/](https://jekyllrb.com/docs/front-matter/).
But honestly, when I follow the example and try to export to PDF - I don't see any difference (comparing to not writing the `---` block). Most likely I misunderstood something, but I just want to create a front page, and maybe also to free the 1st level heading (H1), such that the title of my file/post won't appear at the TOC, which is a bit ridiculous (cause it's duplicated).

I would appreciate it if you could guide me on what should I look for to make it happen.

Best regards

```
---
title: example
author: me
```

**Comment by abnerlee** [comment]
see https://support.typora.io/Export/#example-add-cover-page

**Comment by NorHei** [comment]
Saw this while working on a similar problem myself. I ended up building on the
basic YAML front matter idea from the original post here and turned it into a
small script that generates a full title/cover page (title, author,
description, date, license, optional cover image) from YAML front matter
fields - it's a bit more involved than the example above, but it's
copy-paste ready if anyone wants to try it:

https://github.com/heimsath-typora/pdf-export-tp-img
