### ISSUE TITLE
space diisplayed before code starting wrapped line

### ISSUE THREAD

**Issue by brainchild0** [typora/typora-issues#3504]
If a paragraph contains a code span, and wrapping is such that the span appears first on a  display line, then Typora displays an extra space character before the span.

This problem appears only to affect buffer display, not actual contents.

In the image, this space is seen between the caret and the word "code". The buffer has only a single space character between the word "some" and the ``` ` ```-character that begins the next word.

Tests were conducted in version 0.9.86.

The [test file](https://gist.github.com/brainchild0/73d6b44bc6dd93d8b3a9334596828d42#file-spacing-md) is posted to a gist.

---

![Screenshot from 2020-05-15 01-36-46](https://user-images.githubusercontent.com/34869175/82015367-959d0d00-964c-11ea-84c8-eb5849030be5.png)

**Comment by abnerlee** [comment]
seems fixed, I'm not able to reproduce it in latest version.
