### ISSUE TITLE
Switch from source code mode to normal mode, view position set to top

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3506]
Hi, I am running `typora 0.9.86-1` at debian 10. I am not sure what is the proper way to call non-source code mode, so I will call it normal mode here.

When switching from normal mode to source code mode, the cursor and view position are both correct. 

When switching from source code mode to normal mode, the cursor position is actually correct, but the view position is set and jump to top. To workaround the view, I have to press LEFT and RIGHT keyboard button to bring the view back to the cursor position. 

I am not sure if this is expected as design, but I am not expected that happens. I expect both view and cursor postions should remain the same. 

Thanks a lot.

**Comment by abnerlee** [comment]
#3341
