### ISSUE TITLE
Unbearably sluggish performance when a folder with files in it is open

### ISSUE THREAD

**Issue by lasselaakkonen-congrid** [typora/typora-issues#3508]
Typora seems to become unbearably sluggish when a folder with files in it is open.

## Reproducing

Using macOS 10.13.6, Typora v0.9.9.32.1 (4191)

- Get 15 paragraphs of text from here https://www.lipsum.com/
- Open a Typora window without opening a folder
- Paste the 15 paragraphs of text there
- *Scrolling the window is smooth, no issues here*

Then

- Open a new Typora window
- Paste the 15 paragraphs of text there
- Open some folder with no files or folders
- *Scrolling the window is smooth, no issues here*
- Open some folder with 10s of subfolders and 10s of files
- **Scrolling the window is unbearably sluggish**
- Open some folder with no files or folders
- **Scrolling is stays unbearably sluggish**

**Comment by abnerlee** [comment]
merge into #68

**Comment by lasselaakkonen-congrid** [comment]
If it happens to make a difference in the issue, as in #3602 I also happen to have a Radeon GPU in my laptop.
