### ISSUE TITLE
Unbearably sluggish performance when using in full screen

### ISSUE THREAD

**Issue by lasselaakkonen** [typora/typora-issues#3509]
Typora seems to become unbearably sluggish when using it in full screen.

This issue might be related to https://github.com/typora/typora-issues/issues/3508

## Reproducing

Using macOS 10.13.6, MBP 15" 2016, 1920x1200 resolution, Typora v0.9.9.32.1 (4191)

- Get 15 paragraphs of text from here https://www.lipsum.com/
- Open a new Typora window
- Open some folder with 10s of subfolders and 10s of files
- Paste the 15 paragraphs of text there
- Make the Typora window full screen size
- **Scrolling the window is unbearably sluggish**
- Make the Typora window less than 33% the width of the screen
- *Scrolling the window is smooth, no issues here*

**Comment by abnerlee** [comment]
merge into #68
