### ISSUE TITLE
Is that possible to add custom syntax highlight in code fence? 

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3510]
Hi, since what I want to support will unlikely be supported in any future, Is that possible to add custom syntax highlighting in code fence easily in typora? Are there any existing ways or workarounds to do this?

I tried many markdown editors, none of them support shell terminal mode. The shell mode here is just bash/sh mode, not really a terminal mode. With terminal mode, I would like to achieve something like

```
$ command arg arg arg    # this is a comment, and this line should follow bash/shell mode except the first $ sign
standard output should in grey color
standard output should in grey color

[dir]$ command arg arg arg    # this line should follow bash/shell mode except the prefix `[dir]$`
standard output should in grey color

[user@host /dir/dir]$ command arg arg
standard output should in grey color

# reboot    # I am a root user and this is a comment
[dir]# reboot
```

I did tweak/workaround this by hacking some config files in other markdown editors. But not sure if I can do it in typora too. 

Btw, I am running in debian linux. 

Thanks a lot.

**Comment by abnerlee** [comment]
Currently it is not supported.

duplicate with #162

**Comment by sgon00** [comment]
I have spent many days on hacking typora to support shell-session (terminal prompt) syntax highlight, but no luck. I tried many markdown editors during these days. 

marktext is open sourced and has all the features I want. I can hack it and build the editor whatever I want and adding new features. The problem of marktext is it is extremely slow. It requires a gaming-powered PC to work with. My current laptop just doesn't fit well. After I can not suffer the slow performance, I tried to hack typora again with no luck again. 

shell-session syntax highlight is a must-to-have feature for me. And I can't beleive any programmers can suffer no such feature with typora.

I am here to just express my depression. Since the issue is already closed, expressing depression doesn't harm anything.

I will keep trying to hack typora today to see if I can make it support shell-session. 

So far, typora is the only one which supports wysiwyg and has a relative performance in Linux. 

Hopefully, I can figure it out. Otherwise, I will have to give up typora.

**Comment by sgon00** [comment]
Here is a screenshot from `marktext` for shell-session syntax highlight *(I hacked its code to support this because it doesn't add this mode from prismjs until now even if it's using prismjs)*:

![Screenshot-5](https://user-images.githubusercontent.com/1555508/82859250-cd5b5d00-9f48-11ea-9744-5681a4c60f5a.png)

If the stdout can be a different color (more gray) than the arguments at the command line will be great. I haven't spent much time on marktext because it's too slow at my laptop. If I finally decide to use marktext, I will hack the `stdout` color for shell-sesson later.

**Comment by abnerlee** [comment]
We use codemirror (https://github.com/codemirror/codemirror which is open source) for syntax highlighting, if you can also write a terminal-prompt mode or "hack" this, we are ahppy to port this into Typora
