### ISSUE TITLE
When moving the cursor up and down without modifying anything, why typora mark the file Edited?

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3511]
Hi, I am running `typora 0.9.86-1` in debian 10. 
In normal mode (non-source-code-mode), when moving the cursor up and down (especailly when there is urls, code fence etc..) without modifying anything, the window status will be changed to EDITED mode, I mean the window title will change from `file.md - Typora` to `file.md* - Typora`.
This is really unexpected. As a programmer, this is not acceptable. The file should not change its status when I just move mouse up and down. 
Thanks a lot.

**Comment by abnerlee** [comment]
duplicate with #2354
