### ISSUE TITLE
the order in md file changed after pictures uploaded

### ISSUE THREAD

**Issue by Soulballad** [typora/typora-issues#3512]
when upload all pictures in a markdown file by "upload all pictures", the order in editor changed after uploaded.
![image](https://user-images.githubusercontent.com/19262272/82149219-2ceea400-9889-11ea-9ebe-6be055101c61.png)

**Comment by abnerlee** [comment]
Typora will use the order output by the upload command.

![2B060808@E5864A54 BF9FE05E](https://user-images.githubusercontent.com/1621242/84573932-07947d80-add6-11ea-9e28-c7c868f62336.jpg)

**Comment by abnerlee** [comment]
https://github.com/PicGo/PicGo-Core/issues/40

**Comment by abnerlee** [comment]
Fixed in PicGo/PicGo-Core#40, Please upgrade your pigo
