### ISSUE TITLE
[Feature Request] Do not change non-existing filename to Untitled when launching from cml such as `typora foo.md`

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3513]
Hi, I am running debian and launch typora a lot from terminal (command line). When I want to create a new file named `foo.md`, what I expect is `typora foo.md` will launch typora app and the title should show `foo.md` with `*` Edited mode. This is what other apps normally do. 
But instead, the current typora behavior is poping up an error message to complain the file does not exist and change the filename/title to `Untitled` after clicking OK to the error message. This causes two more steps to create the file with the right name. 

**The expected steps:** (1) `typora foo.md` (2) Ctrl+s to save the file (3) press Enter to save it as `foo.md`
**The current behavior:** (1) `typora foo.md` (2) Click the OK button for the no file error message (3) Ctrl+s to save the file (4) change the filename `Untitled` to `foo.md` (5) press Enter to save it as `foo.md`. 

Thanks a lot.

**Comment by abnerlee** [comment]
relates #1999 #721

**Comment by abnerlee** [comment]
In my test, expected behavior seems already supported in 0.9.93
