### ISSUE TITLE
URL Escaped links render correctly but broken in WYSIWYG navigation

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#3514]
To reproduce, enter the following into Typora and then ⌘-click to navigate to the link:

```
[try this link](
https://spec.commonmark.org/dingus/?text=%0A%0A%23%20h1%20Heading%0A%23%23%20h2%20Heading%0A%23%23%23%20h3%20Heading%0A%23%23%23%23%20h4%20Heading%0A%23%23%23%23%23%20h5%20Heading%0A%23%23%23%23%23%23%20h6%20Heading%0A)
```

Expected behavior is same as this GitHub rendering of the exact same link: [try this link](
https://spec.commonmark.org/dingus/?text=%0A%0A%23%20h1%20Heading%0A%23%23%20h2%20Heading%0A%23%23%23%20h3%20Heading%0A%23%23%23%23%20h4%20Heading%0A%23%23%23%23%23%20h5%20Heading%0A%23%23%23%23%23%23%20h6%20Heading%0A)

**Comment by abnerlee** [comment]
should be fixed
