### ISSUE TITLE
Typora hangs on launch on windows frequently

### ISSUE THREAD

**Issue by winterdraws** [typora/typora-issues#3516]
Whoops, posted that too early, hence the edit!

Typora frequently hangs on launch with the recent updates on both of my windows machines, including one windows machine that has a completely fresh install.

The menu icons fail to load and the typing caret freezes. I have to close the program and re-open it and hope it launches correctly.

**Comment by TaiXuan91** [comment]
I have the  same issue too and don't know why.

**Comment by abnerlee** [comment]
duplicate with #3019?
