### ISSUE TITLE
Mermaid fails on class names with underscore

### ISSUE THREAD

**Issue by amrtn** [typora/typora-issues#3517]
![image](https://user-images.githubusercontent.com/151747/82320833-3173a380-99d4-11ea-9814-6df2824ce9ef.png)

That code works well in the mermaid live editor (uses mermaidjs 8.5.1): 

![image](https://user-images.githubusercontent.com/151747/82320937-608a1500-99d4-11ea-888c-6eae472b9336.png)

Typora version: 0.9.86

Might be related to #1661

**Comment by abnerlee** [comment]
will be fixed in #1661
