### ISSUE TITLE
mermaid has problem

### ISSUE THREAD

**Issue by yanscnu** [typora/typora-issues#3518]
> graph TB
    subgraph ide1 [ide1_xxxxxx]
    a1
    a2
    end
    subgraph ide2 [ide2_xxxxxx]
    a3
    end
    a1-->a2

The mermaid code is as above.
It's normal at mermaid-live-editor, but not normal at Typora.
At Typora, the subgraph title has been covered.

- mermaid-live-editor

https://mermaid-js.github.io/mermaid-live-editor/
![image](https://user-images.githubusercontent.com/17843186/82325643-22a9e280-9a0e-11ea-9bc8-89b27cdb4891.png)

- Typora

![image](https://user-images.githubusercontent.com/17843186/82325546-0148f680-9a0e-11ea-923e-4a66ebc0bafa.png)

Also, Typora does not support flowchart.
https://mermaid-js.github.io/mermaid/#/flowchart?id=beta-flowcharts
> flowchart TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
    one --> two
    three --> two
    two --> c2

**Comment by yanscnu** [comment]
>graph TB
	subgraph server1[192.168.152.128]
	s1_canal[canal]
	end
	subgraph server2[192.168.152.129]
	s2_mysql[mysql:3306]
	end
	s1_canal --> s2_mysql

I change the code like above("subgraph server1 [192.168.152.128]" to  "subgraph server1[192.168.152.128]"), It's normal at Typora.

**Comment by abnerlee** [comment]
will be fixed in #1661
