### ISSUE TITLE
Typora can't detect pandoc though successfully installed

### ISSUE THREAD

**Issue by fightingwing** [typora/typora-issues#3519]
Hi all,
Can you help me with the issue that Typora can't detect the pandoc installed.
My OSX is Catalina<10.15.4>, Typora is <Version 0.9.9.32.1 (4191)>, and pandoc is 2.9.2.1. I used "brew install" to install the pandoc and cask brew to install the Typora. And I'm sure that the pandoc is in my Path, as I can even use it in the shell. But the Typora just can't detect the pandoc. I've tried to uninstall an reinstall the Typora and pandoc for several times. It really troubled me as I really fancy the great Typora. Can anyone else help me with this? Thanks so much in advance!
> One thing I don't know if it's worthy mentioning (though I don't think it would be problem) is that I installed Anaconda3, which contains pandoc already. So when I activate the base environment, I would find a different version of pandoc,2.2.3.2. Two two pandoc has different user data directory.

<img width="564" alt="image" src="https://user-images.githubusercontent.com/63919596/82383802-74f6fd80-9a26-11ea-987c-e9d3632cee79.png">

**Comment by abnerlee** [comment]
duplicate with #2040

**Comment by Keldos-Li** [comment]
Have you fixed that? I am still so troubled with the latest release...

**Comment by fightingwing** [comment]
Nope, I didn’t find the solution. It’s really annoying. I hope it could be debugged in later release.
