### ISSUE TITLE
How to collapse/uncollapse outlines on then left panel?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#352]
![image](https://cloud.githubusercontent.com/assets/10832544/19357040/68ed94c6-91a2-11e6-8f8c-fb7e260f1bf4.png)

**Comment by abnerlee** [comment]
Such option added in new version

**Comment by leewi9** [comment]
Amazing!!! Thanks a lot!

**Comment by leewi9** [comment]
Can you hide the arrow if it does not have any childs?

![image](https://cloud.githubusercontent.com/assets/10832544/19462449/4e0f3b20-951f-11e6-9450-87c8a9cbb2c8.png)

**Comment by leewi9** [comment]
and could you please prevent the outline from redrawing in some operations like breaking new line, `Ctrl+S` etc,  it will lose the original location and it's not convenient in the middle of the work.

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by qtbluesky** [comment]
@leewi9 
Outline里面的折叠功能怎么用的？
另外还想请教下怎么在正文里面使用折叠功能？

**Comment by leewi9** [comment]
font{
        line-height: 1.5;
    }


    
you can turn it on in the preference.



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年06月15日 17:45，Tian<notifications@github.com> 写道： 


@leewi9
Outline里面的折叠功能怎么用的？
另外还想请教下怎么在正文里面使用折叠功能？

**Comment by qtbluesky** [comment]
@leewi9 many thanks!
