### ISSUE TITLE
Tab name, window name and filename do not always match

### ISSUE THREAD

**Issue by TraceyC77** [typora/typora-issues#3520]
**Summary**
When multiple file are open in multiple tabs within the same Typora window, at some point The wrong filename is shown in the window and in the tab compared to the file in the viewer

OS version:  MacOS Catalina 10.15.4
Typora version:  0.9.9.32.1 (4191)

**Settings**
There's a setting to always open new windows in tabs in MacOS, I have this enabled. (This doesn't seem to affect Typora, just mentioning for completeness. Typora opens files in new tabs regardless of this setting)
    Finder - Preferences - Open folder in tabs instead of new windows
Typora Window Style - Classic

**Steps to Reproduce**
* Open a folder in the sidebar that has 3 or more files
* Open each file in a "new window" which will open them in tabs (right click filename, Open in New Window)
* Switch between the files in the viewer by clicking on the tab for the file

**Expected Behavior**
The filename highlighted on the left matches the filename in the tab title & window title. The contents in the viewer match the file you selected

**Actual Behavior**
* The file highlighted on the left is for a *different* file than the one selected by tab.
* The contents match the filename in the tab title
* The window title matches the file highlighted on the left, but is *not* the same as the tab title & file being viewed

![typora1](https://user-images.githubusercontent.com/10402612/82468817-dea7f380-9a88-11ea-81a2-1f002209b1c2.png)

![typora2](https://user-images.githubusercontent.com/10402612/82468812-de0f5d00-9a88-11ea-9761-5478f199a3d8.png)

![typora3](https://user-images.githubusercontent.com/10402612/82468808-dd76c680-9a88-11ea-865d-52b324c8f663.png)

I'm happy to answer any questions or provide additional detail

**Comment by leowill01** [comment]
Been having this issue for a while and still having it on v0.9.9.35.2 (4715) on macOS 11.0.1

**Comment by abnerlee** [comment]
Does this still happens in 0.9.9.36.2?

**Comment by leowill01** [comment]
@abnerlee I for one cannot intentionally replicate it, but I will keep an eye out for it while working this week and let you know.

**Comment by TraceyC77** [comment]
@abnerlee  I updated Typora to 0.9.9.36.2 today. I tested again by opening and closing various documents. I am no longer able to reproduce the bug.

**Comment by leowill01** [comment]
I have not seen the bug since updating to 0.9.9.36.2.

**Comment by abnerlee** [comment]
should be fixed
