### ISSUE TITLE
Click a local markdown file link should not open a new typora instance when the file is already opened

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3525]
Hi, in debian, for example, when I have opened two markdown files in typora: `file1.md` and `file2.md`. 
In `file1.md`, it has a link `[file2.md](file2.md)`. By ctrl clicking the link, what I expect is the active window should be switched to the existing `file2.md` typora instance. 
But the current behavior is opening a duplicated `file2.md` typora instance.
Thanks.

**Comment by abnerlee** [comment]
#1251

**Comment by sgon00** [comment]
I disagree this issue is duplicated to the issue mentioned above. Maybe I didn't express clearly in English. I am not talking about the same window/tab at all. I am talking about changing active window. By changing active window, I mean `Alt +Tab` in Linux/Windows, `Cmd + Tab` in Mac. I have added a comment to #1000. It seems all issues go to that one. Thanks.
