### ISSUE TITLE
Ctrl+O to open an already opened file should switch to that window

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3526]
Hi, in debian, for example, I have two typora instances opened: `file1.md` and `file2.md`. 
When I am editing `file1.md` and use `Ctrl + O` to open `file2.md`, what I expect is the window should be switched to the existing `file2.md` window. 
But the current behavior is the active window will be remained in `file1.md` unchanged.
Thanks.

**Comment by abnerlee** [comment]
duplicate

**Comment by sgon00** [comment]
I disagree this issue is duplicated to the issue mentioned above. Maybe I didn't express clearly in English. I am not talking about the same window/tab at all. I am talking about changing active window. By changing active window, I mean `Alt +Tab` in Linux/Windows, `Cmd + Tab` in Mac. I have added a comment to #1000. It seems all issues go to that one. Thanks.

**Comment by mbartelsm** [comment]
Everything window or tab related is merged into that monster issue that hasn't had an update in years
