### ISSUE TITLE
Some typora instances will display empty content randomly in debian

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3527]
Hi, I am not sure how to reproduce this. I am running debian. 
I have many apps and windows opened. There are many typora window instances too. 
When I switch between them and open new typora instances and click links etc..., sometimes, the typora window of some files will show an empty content UI. Clicking on the empty body, nothing will happen. I can bring this instance back by refreshing the instance with fullscreen toggle. So if I press `F11` twice, the problem will be gone. 
Since I don't find a certain pattern how to reproduce it, devs can decide whether this is a bug or should be simply closed. 
Thanks.

**Comment by abnerlee** [comment]
Only the writing part is empty, or the whole window content (include, status bar, side bar, etc) are all empty?

**Comment by sgon00** [comment]
@abnerlee Only the writting part is empty. I just met the problem again. It happens here multiple times a day. *(It's a low RAM laptop (4GB) and swap is not empty. Not sure if it's anything to do with the RAM.)*. I just realized I can bring the writting part back not only with F11, but also resizing the window size will do too. Thanks a lot for your time.

**Comment by abnerlee** [comment]
relates #3671 #3606

would you try https://github.com/typora/typora-issues/issues/3606#issuecomment-656990560?
