### ISSUE TITLE
How to nest \textbf and \textit in Latex?

### ISSUE THREAD

**Issue by asdfang** [typora/typora-issues#3528]
Trying a workaround to get [musical dynamics](https://tex.stackexchange.com/questions/111788/how-to-typeset-music-dynamics-within-normal-text), I would like to do this:
```
\newcommand{\muskern}{\kern-.15ex }
\newcommand{\sfz}{\textnormal{\textbf{\textit{s\muskern f\muskern z}}}}
```
But,
`$\textbf{\textit{hello}}$`:
![image](https://user-images.githubusercontent.com/15959191/82595353-4e39e380-9b5a-11ea-8b9f-a6d1d37eacbb.png)
and
`$\textit{\textbf{hello}}$`:
![image](https://user-images.githubusercontent.com/15959191/82595406-5db92c80-9b5a-11ea-8489-bd79ff1dd450.png)

**Comment by abnerlee** [comment]
Our inline math are designed for math not a full set of LaTeX, 

And this seems not supported by MathJax.
See https://github.com/mathjax/MathJax/issues/243
