### ISSUE TITLE
【Bug Report】cannot use PicGo upload image

### ISSUE THREAD

**Issue by cooper1x** [typora/typora-issues#3529]
Information about PicGo
System: windows 10 2004 x64
picgo: 2.3.0-beta

Reproduce the problem
image
![image](https://user-images.githubusercontent.com/9080789/82692759-dae7bd00-9c92-11ea-98a9-b523869b2a13.png)

I am able to verify in typora, but the actual upload will not work.

Always prompt this error:
![image](https://user-images.githubusercontent.com/9080789/82692781-e5a25200-9c92-11ea-9def-fd1a774f98be.png)

Service testing is ok, but the software is still not available.

**Comment by abnerlee** [comment]
Still exist in 0.9.90?

should be fixed in new release
