### ISSUE TITLE
"Copy Images To..." dialogue keeps opening every time before uploading images

### ISSUE THREAD

**Issue by BillChen2K** [typora/typora-issues#3530]
I use uPic to upload local images. After upgrading to Typora 0.9.9.33, every time I paste a image, this dialogue shows up. No matter I click the Cancel or Create Folder button, it won't actually create a folder. Instead the image is then uploaded as usual and the link rewritten.

![image](https://user-images.githubusercontent.com/11037722/82693408-120a9e00-9c94-11ea-891b-bed1486337e6.png)

Besides this is a blank markdown file and contains no YAML front matter. Here's my global settings:
![image](https://user-images.githubusercontent.com/11037722/82693627-72014480-9c94-11ea-9e6d-9be222344eac.png)

Bit of annoying, hope it can be fixed.

**Comment by abnerlee** [comment]
released a fix
