### ISSUE TITLE
Title of open folder need to be  implemented

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3532]
When you have a multiple of open projects  with each tab has an open folder, it is very difficult to distinguish between these projects, unless one's select any of these tabs.

I wish to suggest, that the title on the top of the window reflects the title of the open folder rather than the open MD file. 

Another suggestion, maybe difficult to implement, is that the title of each tab reflects the title of the open project (i.e. folder). But once that tab is activated the title changes to the selected MD file from the file tree.

![image](https://user-images.githubusercontent.com/5421420/82721766-4c863200-9cb8-11ea-9a30-38f0b6e92478.png)

**Comment by abnerlee** [comment]
duplicate with #2962
