### ISSUE TITLE
Search does not scroll correctly when the match is in a code block

### ISSUE THREAD

**Issue by lucidBrot** [typora/typora-issues#3533]
I have a large file consisting of text interspersed with code blocks. When I use CTRL+F to search for something and then step through the search results using ENTER or the GUI Down-Arrow Button, the matches within code blocks are highlighted correctly (black background, white text) but are not visible on my screen until I scroll down one tick of my mouse wheel.

Searching matches backwards by using the GUI Up-Arrow Button seems to jump correctly.
![typora_search](https://user-images.githubusercontent.com/4920691/82730490-72cfc000-9d00-11ea-8bb9-c69c96615024.gif)

I'm currently on Win10 Typora `version 0.9.87 (beta)`, but I noticed this also on older versions.

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> the sample md file?

**Comment by lucidBrot** [comment]
@abnerlee I have sent a mail with subject "Re: [typora/typora-issues] Search does not scroll correctly when the match is in a code block (#3533)" 👍

**Comment by abnerlee** [comment]
should be fixed in new release
