### ISSUE TITLE
File Tree being automatically opened

### ISSUE THREAD

**Issue by junyilou** [typora/typora-issues#3535]
I recently updated to Typora 0.9.9.33 (4415) on my Mac, and after I updated, every time Typora opens, it shows the file tree on the left, I don’t want that and I have to disable it on the top menu bar every single time I open Typora. I dig through the preference settings and found nothing, is there a way to disable it? Thanks.
<img width="1004" alt="截屏2020-05-24 下午12 36 31" src="https://user-images.githubusercontent.com/15688661/82745825-34e3a200-9dbb-11ea-931f-f79deebdf9d5.png">
(Tried email to hi @ Typora.io but the email server rejected)

**Comment by abnerlee** [comment]
duplicate with #3531. A new fix has been released. Please try check update again
