### ISSUE TITLE
Help wanted: Change caret colour in math block.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3537]
OS:win10 | TyporaVersion:0.9.87

---
My caret colour in code fences shows black and, due to my theme, it is very hard to distinguish as you can see in the following two pictures.
![image-20200524004708207](https://user-images.githubusercontent.com/46404230/82746656-c7d50a00-9dc4-11ea-93dc-a86855d67e4d.png)
![image-20200524004834025](https://user-images.githubusercontent.com/46404230/82746658-c99ecd80-9dc4-11ea-9bfa-45839b1da0a0.png)
And I had tried my best to figure out how to change it as you can see in the next picture(I had little knowledge about CSS). 
![image-20200524004657503](https://user-images.githubusercontent.com/46404230/82746689-27cbb080-9dc5-11ea-98a8-12d5ec10a336.png)
Sadly I failed even though I changed the colour of the caret in otherwhere.
![image-20200524004942519](https://user-images.githubusercontent.com/46404230/82746693-3914bd00-9dc5-11ea-9a75-d7ccff8fafe8.png)

So by the end, I come here for some help.

**Comment by peetteerr** [comment]
Oh, the new version(.88) seems to have already changed the caret colour to white in math block, which is a great help thanks. But I still want to ask is there any possible way to set the colour by myself.

**Comment by abnerlee** [comment]
I believe `.CodeMirror-cursor`  is used, for example: https://github.com/graphql/graphiql/issues/545
