### ISSUE TITLE
Where is the CodeMirror code and how typora calls it?

### ISSUE THREAD

**Issue by sgon00** [typora/typora-issues#3538]
Hi, I would like to hack codemirror syntax highlight with new language support (or write a plugin to codemirror). How can I do that? I haven't figured out how typora calls codemirror. Where is the `codemirror.js` and `mode/` directory? Thanks a lot for your help.

**Comment by abnerlee** [comment]
We currently does not support this. may duplicate with #3510

**Comment by sgon00** [comment]
@abnerlee can you please provide some information instead of simply closing it as a duplicated issue? Typora uses CodeMirror, so it must call it somewhere. Can you please just tell me which file and directory has the code? I can hack the code by myself. Thanks a lot.
