### ISSUE TITLE
Image align behavior is not consistent

### ISSUE THREAD

**Issue by xiao03** [typora/typora-issues#3539]
I just updated 0.9.9.33.2 on macOS Catalina 10.15.4. I'm using GitHub Theme and did not make any changes to it.

I insert two images in my blog by drag and drop but their behavior is not consistent. The first is aligned to the left, and the second is aligned at the center. Please check the attachments for how it looks like. The second image in the picture is as large as it appears and does not have blank or invisible spaces.  I tried to add `vertical-align: left` to the second image and `vertical-align: middle` to the first but nothing happens. 

Another thing to mention is that Typora helps me create the asset folder when I inserted the first picture. The following pictures (the second, the third, and so on) I inserted would be aligned at the center, which is expected. 

I also want to know how to align my pictures to left. I'm not familiar with HTML and how it works in Typora so please pardon me if this is a trivial question.

<img width="1023" alt="Screen Shot 2020-05-25 at 10 05 06" src="https://user-images.githubusercontent.com/43306518/82820542-67030b80-9e70-11ea-81dd-fb03e15181ec.png">
<img width="998" alt="Screen Shot 2020-05-25 at 10 05 13" src="https://user-images.githubusercontent.com/43306518/82820544-67030b80-9e70-11ea-8b29-bef8c2624046.png">

**Comment by abnerlee** [comment]
If one paragraph only contains one image (and no other texts), the image will be aligned center. But you can change this by custom CSS.

Also, `vertical-align` is "vertical".
