### ISSUE TITLE
accidentally monospaced source after end of indented code block

### ISSUE THREAD

**Issue by aryairani** [typora/typora-issues#3541]
Version 0.9.9.33.2 (4442) 

Notice that after the indented code block, all the text is rendered monospace:

![image](https://user-images.githubusercontent.com/538571/82828256-a33d6880-9e7e-11ea-8373-16170454a996.png)

but in the rendered display, you can see that it correctly understood the bounds of the indented code block:

![image](https://user-images.githubusercontent.com/538571/82828218-8ef96b80-9e7e-11ea-87d3-0d3ff7cca4f4.png)

Here is a shorter example that reproduces the issue:

    1. Here is my list!

      ```c
      const char[] = "here is my indented block";
      ```

    2. Why is this line monospaced in Source Code Mode?

Thanks for your work, Typora is already the best of its kind!

**Comment by aryairani** [comment]
A clue: The Source Code Mode renderer doesn't seem to recognize the closing \`\`\` unless it is in Column 1.  If the ending ``` is outdented to the first column, then Source Code Mode renders the rest of the document correctly, but switching back to normal mode adds the perceived missing closed fence, and you end up with:

    1. Here is my list!

      ```c
      const char[] = "here is my indented block";
      ```
    ```
    2. Why is this line monospaced in Source Code Mode?

and all the badness that comes along with that.

**Comment by abnerlee** [comment]
duplicate with #1638
