### ISSUE TITLE
Can not Open Image Location

### ISSUE THREAD

**Issue by adahbingee** [typora/typora-issues#3542]
click menu text do nothing

windows 10

version 0.9.89(beta)

![image](https://user-images.githubusercontent.com/2985536/82848627-ff5bc780-9f26-11ea-92b3-9f3508a519bb.png)

**Comment by abnerlee** [comment]
caused by https://github.com/electron/electron/issues/11617

**Comment by abnerlee** [comment]
should be fixed in new release
