### ISSUE TITLE
open typora could not show/type anythings

### ISSUE THREAD

**Issue by onewesong** [typora/typora-issues#3544]
![image](https://user-images.githubusercontent.com/17920822/82880365-e7109a80-9f70-11ea-9275-d3cf55140d06.png)

reinstall still the same, anybody know how to solve it?

**Comment by aron-hoogeveen** [comment]
> For bug reports, please provide your OS version, Typora version, and if possible, detailed steps to reproduce the bug.

**Comment by PgBiel** [comment]
Same happened to me after updating to latest version (0.9.9.33.2, from 0.9.9.31.4 I think) 
(By the way, if anyone here has a link to said older version, that'd be very helpful - the links on the website lead to "Not Found")

OS version: MacOS 10.13 (High Sierra)
Typora version: 0.9.9.33.2

Steps to reproduce:
1. Open Typora
2. Try to type anything, open any file etc

Expected result: Text appears
Actual result: Nothing happens, no text displays when opening files etc.

I tried reinstalling, cleaning cache etc., to no avail.

**Comment by onewesong** [comment]
I roll back typora by using time machine. And it work fine again.

**Comment by abnerlee** [comment]
@onewesong @PgBiel Are you on 10.13.1? We received reports from those macOS versions.

But I cannot reproduce this on my 10.13.4 VM

**Comment by PgBiel** [comment]
The issue occurred with my 10.13.0 Mac. Using another Mac with 10.13.6 seems to work

**Comment by adamharms** [comment]
Also having this issue with 10.13.3

**Comment by onewesong** [comment]
> @onewesong @PgBiel Are you on 10.13.1? We received reports from those macOS versions.
> 
> But I cannot reproduce this on my 10.13.4 VM

my version is 10.13.3

**Comment by abnerlee** [comment]
I currently don't have 10.13.x <= 10.13.3, don't know how to degrade my 10.13.4 VM image...

**Comment by abnerlee** [comment]
Cannot find a 10.13.0 installer, seems only 10.13.6 is avaible (https://discussions.apple.com/thread/8654779)

**Comment by v-dale** [comment]
> @onewesong @PgBiel Are you on 10.13.1? We received reports from those macOS versions.
> 
> But I cannot reproduce this on my 10.13.4 VM

Yes, I have 10.13.1

**Comment by abnerlee** [comment]
We updated our older macOS support info -> https://support.typora.io/Older-macOS-Support/
