### ISSUE TITLE
Auto scrolldown when math block preview goes out of view

### ISSUE THREAD

**Issue by aron-hoogeveen** [typora/typora-issues#3545]
Enhancement request:
Scroll the preview of the math block into view when it goes out of view. 
My current workflow when working on math blocks near the bottom of the screen:

1. Insert mathblock <kbd>$$</kbd>+<kbd>ENTER</kbd>
2. Type multiple lines of code into the math block
3. Cursor reaches bottom of screen upon which only the typing box is scrolled into view
4. Scroll down until the preview is fully into view
5. Resume typing

It would be nice if the preview was also scrolled into view. However, one should take into account that a user could also type a lot of lines inside a mathblock. When that happens the cursor should get preference over the preview block

**Comment by peetteerr** [comment]
having a greater padding-bottom(400px) may be of some help.

**Comment by abnerlee** [comment]
should be fixed in new release
