### ISSUE TITLE
Fail to clear format of multi-line selection in lists/tables

### ISSUE THREAD

**Issue by 111116** [typora/typora-issues#3547]
### Verison
Typora Version 0.9.9.32.1 (4191)
MacOS 10.14.2

### Way to reproduce
1. Make a list or table or something
2. Bold some words
3. Select multiple lines, clear format (cmd+\\), you'll see the words become regular
4. Switch to source code mode, the words are still bold
5. Alternatively, save and reopen the document, the words are still bold

**Comment by 111116** [comment]
The workaround I found is to select all, cut and paste, in WYSIWYG mode after clearing format.

**Comment by abnerlee** [comment]
should be fixed in new release
