### ISSUE TITLE
ERROR: No valid printers available

### ISSUE THREAD

**Issue by stevenov** [typora/typora-issues#3549]
When I try and print, I get an error that no valid printers are available. This started earlier this week. I'm on Linux 0.9.89 (beta). I've also noticed that exporting to RTF puts the file name at the top of the document, which seems like new behavior.

This is on Ubuntu GNOME 16.04, btw.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by stevenov** [comment]
Still seeing this in 0.9.92.

**Comment by abnerlee** [comment]
> Still seeing the printing error in 0.9.92.

So what is the error message?

**Comment by stevenov** [comment]
Error. No valid printers available.

![image](https://user-images.githubusercontent.com/5796196/87701285-b88b9080-c765-11ea-90d8-8241b289c6db.png)

**Comment by abnerlee** [comment]
relates https://github.com/electron/electron/issues/24664

**Comment by rlayton6** [comment]
This has been broken for several releases.

Typora version: 0.9.96 (beta)
Linux: Ubuntu 18.04.5 LTS

```
$ sudo cat /etc/cups/printers.conf
# Printer configuration file for CUPS v2.2.7
<Printer HL2170W>
UUID urn:uuid:f374bf11-*
Info HL2170W
MakeModel Brother HL2170W for CUPS
DeviceURI socket://172.*.*.*
State Idle
StateTime 1601283077
ConfigTime 1550296785
Type 8392708
Accepting Yes
Shared Yes
JobSheets none none
QuotaPeriod 0
PageLimit 0
KLimit 0
OpPolicy default
ErrorPolicy retry-job
Attribute marker-colors \#000000,#000000
Attribute marker-levels -1,8
Attribute marker-names Black Toner Cartridge,Drum Unit
Attribute marker-types toner,opc
Attribute marker-change-time 1601283077
</Printer>
```
_Some data obscured._

**Comment by abnerlee** [comment]
Newer discussion is in #3744
