### ISSUE TITLE
Evernote compatibility: HTML pasted into Evernote has issues

### ISSUE THREAD

**Issue by nonbeing** [typora/typora-issues#355]
Typora is fantastic but my main use case is to use it as a Markdown-editor for Evernote. My workflow will be to enter Markdown into Typora, and then copy+paste the entire rendered-HTML into Evernote.

The problem is that fenced-code blocks do not paste into Evernote properly - please see [this screenshot](http://i.imgur.com/DvMvPom.png):
![Typora->Evernote Issue](http://i.imgur.com/DvMvPom.png)

As you can see, all the code falls out of the rectangle in Evernote.

I have tried the same workflow with another Markdown editor I sometimes use (MacDown) and it works perfectly. The rendered HTML pastes correctly into Evernote.

This is the only issue with an otherwise-perfect Markdown Editor and I would happily purchase Typora if this issue was fixed.

I am on a Macbook Pro, Retina 13", Early 2015 using Sierra (10.12). I am using Evernote 6.9.2
Tested with Typora 0.9.9.8

Thanks for making Typora - I have been searching for this kind of MD editor for years!

**Comment by GeromeRen** [comment]
Same issue happen to me. Any plan to fix this or any advise on this?

**Comment by nonbeing** [comment]
Any update on this? This bug still occurs in the latest build (0.9.9.8.5) :(

**Comment by AlexPasternak** [comment]
Now that I'm using Evernote more, I have to say that fixing this and the other Evernote bug also have value for me. Although this is a pretty specialized use case.

**Comment by yihengli** [comment]
So far https://maxiang.io/ is the best md editor that I found for evernote.
I understand that typora is not originally designed for evernote and I would rather live with the current copy and paste for evernote. But this code fence defect really pains. :(

**Comment by nonbeing** [comment]
Yeah, I found that [MacDown](https://macdown.uranusjr.com/), a free and [open-source](https://github.com/MacDownApp/macdown) Markdown editor for Mac scratches my itch perfectly. I like Typora's concept and UI better, and I would gladly purchase Typora (if it went on sale), but for my Evernote use-case, MacDown wins hands-down every day of the week.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by nonbeing** [comment]
Tested this with Typora 0.9.9.9.2 and I am able to paste into Evernote without any issues now! This is awesome! WooHoo! Typora is the BEST MD editor ever! Thank you so much @abnerlee ^_^

**Comment by bit3125** [comment]
I still have the problem T_T
