### ISSUE TITLE
View jumps to top of file after closing source code mode or on right click

### ISSUE THREAD

**Issue by pablotheissen** [typora/typora-issues#3553]
Version: 0.9.89(beta) @ Windows 10

After closing the source code mode the the view of the document jumps to the top while the cursor stays at the correct position (where I just edited somthing in source code mode).

The same thing happens after using spelling correction via right click and selecting an entry.

**Comment by abnerlee** [comment]
@pablotheissen which theme did you use?

Possible to send us a sample file and screencast for us to reproduce this bug?

**Comment by pablotheissen** [comment]
I'm using the Github Theme with slight CSS modifications.

I had this happen in all documents (with/without images, with/without math, etc.), but I don't know how to reproduce it at will. After some time using typora it starts happening and then it happens every time I toggle source code mode or use spelling correction. It only stops after restarting Typora.

I'll continue using Typora until it happens again and then create a screencast. If there is any other type of debugging I can enable to help you guys, please let me know.

**Comment by abnerlee** [comment]
should be fixed in new release
