### ISSUE TITLE
Copy and Copy as Markdown got same results when I turn off the default copy behavior

### ISSUE THREAD

**Issue by phith0n** [typora/typora-issues#3554]
Hi, My Typora version is "Version 0.9.9.33.2 (4442) on OSX".

Step to reproduce this bug:

1. settings dialog -> Editor ->  Default Copy Behavior -> Turn off the "Copy Markdown source as plain text"
2. Open a file which contains an image
3. Right-click the image, there is two types of copy selection: **Copy** and **Copy as Markdown**:

![image](https://user-images.githubusercontent.com/5711185/83109764-8ad68380-a0f4-11ea-8ff1-c01e43a6a62e.png)

4. Clicks these two buttons, but I got the same result: `![image-20190729201756456](assets/duktape/image-20190729201756456-4402676.png)`

For my understanding, **Copy** means to copy the rich text HTML result, and **Copy as Markdown** means to copy the Markdown text plain, so my expected result is:

- **Copy as Markdown**: I get `![image-20190729201756456](assets/duktape/image-20190729201756456-4402676.png)`
- **Copy**: I get the image itself, and I could paste it to another position, like other Markdown editor.

**Comment by abnerlee** [comment]
#4476
