### ISSUE TITLE
Italic formatting is not applied

### ISSUE THREAD

**Issue by Kamile66** [typora/typora-issues#3555]
Hello, everyone,

first of all I must praise Typora: It's a great tool for editing MD files, we use this tool often.

Therefore we have sadly noticed after the last update that the formatting to italics is not applied in "bigger" files...

I have a sample file attached: [recorder-test-all-terminated-ptah.txt](https://github.com/typora/typora-issues/files/4695723/recorder-test-all-terminated-ptah.txt)
You can see it in the second chapter of "Notes":
The timestamp should be shown in italics, but unfortunately it is not.

![grafik](https://user-images.githubusercontent.com/66072273/83145878-c58ceb80-a0f5-11ea-84a3-595c86df47ac.png)

As already mentioned, this has worked perfectly so far and we were otherwise perfectly happy 😊

Could you please have a look at it?

Thanks a lot.
_
Typora Version: 0.9.89 (beta)
OS version: Windows 10 Pro, 1909

Best Regards

Kamile Demirel
Software development

ProDevelop GmbH
www.prodevelop.de

**Comment by abnerlee** [comment]
For performance concerns, Typora won't parse inline styles once a paragraph become too long. (all your `1) *2020-05-28 14:32:53*: Erschaffe dies` sentences are rendered in one `<p>` element based on Markdown's spec).

In your txt file, I think it is acceptable.
