### ISSUE TITLE
URL Encoding when exporting PDFs (MacOS)

### ISSUE THREAD

**Issue by itssmutnuri** [typora/typora-issues#3556]
Encountered an issue where a URL character `#` is encoded to its ASCII form `%23` 

For: 
`[Example Link](https://source.android.com/security/apksigning#schemes)`

On exporting this to a PDF, 

Expected Result: URL leads to `https://source.android.com/security/apksigning#schemes`

Reality: URL encoded, leads instead to the broken link `https://source.android.com/security/apksigning%23schemes`

Same repeats when using the `<a>` tag.

Is this expected? Is there anyway to prevent this from happening?

**Comment by abnerlee** [comment]
duplicate with #3435
