### ISSUE TITLE
Shortcut Key for View “Source Code Mode” does not work

### ISSUE THREAD

**Issue by robhubi** [typora/typora-issues#3557]
## My System
Win10 Pro 64 bit, German
Typora 0.9.89 (beta), Language=English (changed from German after installation)

## Description
The keyboard shortcut "ctrl+/" does not work. Note: on the german keyboard I have to press "shift+7" to get "/".
Then I tried to reassign this keyboard shortcut - with limited success.

## Steps to Reproduce
1.	Open Typora, check View shortcuts
 ![grafik](https://user-images.githubusercontent.com/38103976/83201840-b08c7880-a146-11ea-9f94-8f143f394dd2.png)
2.	Open explorer:  File/Preferences/ Advanced Settings
3.	Open and edit “conf.user.json”
4.	Insert "Source Code Mode": "Ctrl+<" 
![grafik](https://user-images.githubusercontent.com/38103976/83201919-da459f80-a146-11ea-8847-91265e3a10ad.png)
5.	Save and restart Typora
6.	Check View shortcuts
![grafik](https://user-images.githubusercontent.com/38103976/83202028-02350300-a147-11ea-8b0b-2af2c8c14188.png)
7.	"Strg+Umschalttaste+Komma" works!

## Actual Result
Defined keyboard shortcut and working keyboard shortcut do not match.

## Expected Result
Defined shortcut and working shortcut match.

**Comment by abnerlee** [comment]
The solution maybe to assign another working shortcuts, does 'ctrl+-' works (in german keyboard - is / in English keyboard, right)?

I wonder if there are other apps which also allows 'ctrl+/' in German Keyboard.

**Comment by robhubi** [comment]
No, the shortcut "ctrl+-" does not work.
I also tried cntrl+shift+-, now the font in the menus of typora is almost unreadably small. How can I get it back to normal?

**Comment by abnerlee** [comment]
Can `ctrl+/`be used in other apps?

But sure if `ctrl+/` is a valid shortcut for german keyboard

**Comment by robhubi** [comment]
Snagit allows me to set the hotkeys by selection. As a key, it always seems to understand its primary character. So always key "1", but never "!" (SHIFT+1).

Test 1 in Snagit:
CNTRL+SHIFT+7 works (SHIFT+7 = / on German keyboard)

Test 2 in Snagit:
The "/" key is selectable in Snagit.
CNTRL+/ does not work with any key combination.

**Comment by abnerlee** [comment]
so will set as `ctrl+shift+7` in “conf.user.json” work?

**Comment by robhubi** [comment]
Yes, `ctrl+shift+7` in “conf.user.json” works.

**Comment by robhubi** [comment]
Sorry, wrong button

**Comment by abnerlee** [comment]
So "/" is not supported in German keyboard, please use "shift+7" instead.

**Comment by ghost** [comment]
With a **German** keyboard layout, in my case the shortcut ```<Ctrl>+</>``` for ```Source Code Mode``` is mapped to ```<Strg>+<#>```; both on **KDE Linux** & **Windows**.
