### ISSUE TITLE
Mermaid stateDiagram description cannot be visualize when using the Night theme

### ISSUE THREAD

**Issue by renanglichio** [typora/typora-issues#3558]
The font color is white, so it cannot be visualized.

![image](https://user-images.githubusercontent.com/62083803/83215845-d5163e00-a1a2-11ea-834a-b115c95c55e5.png)

If I change the theme, it's ok:
![image](https://user-images.githubusercontent.com/62083803/83215904-f4ad6680-a1a2-11ea-9e13-9431446dc64b.png)

**Comment by abnerlee** [comment]
Please attach the text / code for your mermaid diagram

**Comment by renanglichio** [comment]
Here is a example:
```
stateDiagram
	s1 : This is a state description
	[*] --> s1
	s1 --> [*]
```

The state description font does not contrast with the background:

![image](https://user-images.githubusercontent.com/62083803/83365515-7b508680-a3e3-11ea-9493-f1391d0efdb3.png)

**Comment by abnerlee** [comment]
should be fixed in new release
