### ISSUE TITLE
Invalid 'Date' entry when updating apt-get

### ISSUE THREAD

**Issue by alobaid** [typora/typora-issues#356]
When trying to use apt-get update I get
`W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/typora.io_._linux_InRelease`
the Date entry is 
`Date: Thu, 06 Oct 2016 21:22:35 +0800`
which looks fine to me :)

**Comment by mcg** [comment]
Same issue on Ubuntu 16.10. The date does appear to be valid for Debian rules, but based on the other release files on my system I think you need to convert it to UTC, with something like 
`Time.now.utc.strftime("%a, %d %b %Y %H:%M:%S UTC")`

**Comment by abnerlee** [comment]
changed to "%a, %d %b %Y %H:%M:%S UTC", but not sure if it would work since I do not have wuch error on my Ubuntu 16.10

**Comment by mcg** [comment]
This has fixed the issue for me. Thanks!
