### ISSUE TITLE
Typora copied whole /home directory instead of just image from webpage

### ISSUE THREAD

**Issue by pconrad-fb** [typora/typora-issues#3560]
1. I went to https://www.cloudwards.net/dropbox-vs-box/
2. I copied some paragraphs from section 4, Security, including an image
3. Typora copied my entire /home directory into the .assets folder

I do want to be able to copy images into the .assets directory.
I don't want my entire home directory copied.

Version 0.9.89
Ubuntu 18.04.4 LTS

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by pconrad-fb** [comment]
Awesome!

Peter
