### ISSUE TITLE
Emojis as UTF-8 characters are rendering differently on startup, depending on the leading emoji

### ISSUE THREAD

**Issue by thomas-esau** [typora/typora-issues#3562]
Hello, I discovered unexpected behaviour on startup, when I have this particular red circle emoji: ⭕️ as the leading character in my textfile.

Normally, I would expect colourized emojis like this:

![1](https://user-images.githubusercontent.com/46598525/83307520-30791800-a205-11ea-85bd-b9882f68c616.PNG)

But when I have the red circle as leading character, save and reopen the textfile, it switches to black and white emojis like this:

![2](https://user-images.githubusercontent.com/46598525/83307802-beed9980-a205-11ea-8f63-df53c0c90e8b.PNG)

This happens inside of codeblocks as well, when the red circle is placed anywhere inside the block:

![3](https://user-images.githubusercontent.com/46598525/83307974-1db31300-a206-11ea-92c9-31a939678257.PNG)

This issue doesn't apply to syntax based emojis.

**Comment by abnerlee** [comment]
Possible to attach or post the *.md source?

**Comment by thomas-esau** [comment]
[md_testfiles.zip](https://github.com/typora/typora-issues/files/4716291/md_testfiles.zip)

**Comment by abnerlee** [comment]
Fixed in new release
