### ISSUE TITLE
toggle buttons need more contrast or CSS styling options

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#3563]
I use a an off-white background to reduce strain on my eyes. The problem is (see screenshot at bottom) that it is nearly impossible to see the state of toggle buttons. It's actually not that clear in the normal white background anyway. 

I tried customizing the theme CSS to fix this, but the following CSS variables mentioned in the Typora documentation don't do anything:

```
   --primary-color: #428bca; /* color of primary buttons */
   --primary-btn-border-color: #285e8e;
   --primary-btn-text-color: #fff;
```

I couldn't find any other CSS rules or classes that might work instead.

![Screen Shot 2020-05-29 at 11 46 43 AM](https://user-images.githubusercontent.com/2830093/83309902-74095d00-a1d8-11ea-9663-d189cb9000df.png)

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by vassudanagunta** [comment]
thanks @abnerlee, but it doesn't seem to be any better. `Version 0.9.9.34.2 (4509)`:

![Screen Shot 2020-07-25](https://user-images.githubusercontent.com/2830093/88462769-dc448a00-ce7b-11ea-9cf5-ea504339825f.png)

Could you use **CSS invert filter** or some other approach that will automatically work choose a color that is high contrast with the background?

I would appreciate this issue being reopened please.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by vassudanagunta** [comment]
@abnerlee Thanks for trying again. Sadly not any better at all. Notice how macOS reverses the colors of the word/char count -- that approach works much better.

![button contrast](https://user-images.githubusercontent.com/2830093/91656628-40b0c580-ea88-11ea-9d7c-53a00f71b15a.gif)

The end of the video shows it is the latest Typora release. 

I've also enclosed my 
[base.user.css](https://github.com/typora/typora-issues/files/5146628/base.user.css.txt).

**Comment by abnerlee** [comment]
Sorry, is this the "Newsprint" theme? We fixed the color in built-in themes.

If not, you can add 
```css
.searchpanel-search-option-btn.active {
background: #777;
color: white;
}
```
in your custom css
