### ISSUE TITLE
Rendering problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by pauljurczak** [typora/typora-issues#3564]
Here is a short example, which renders correctly on Windows 10, but badly on Ubuntu 18.04 with the newest version of Typora. The problem is caused by lack of space after `#` in headers.

```
[TOC]

#To do

##List

- If high performance is necessary, focus on DPC++ instead of other OpenCL based solutions.

## Open source contribution

- Add missing functions in JuliaImages (Borders, Boundaries, Filling)
- Add a native file chooser dialog to Julia on Windows (XAML and C++/RT or NanoGUI.jl)
- Better margin trim by processing the rendered page image in off screen buffer
```

![Screenshot from 2020-05-30 20-16-34](https://user-images.githubusercontent.com/4933032/83343057-1a299580-a2b3-11ea-8bef-9e12354be363.png)

**Comment by abnerlee** [comment]
You will need to put space after # when strict mode is enabled.

http://support.typora.io/Strict-Mode/
