### ISSUE TITLE
Typora removes a blank line before --- at the start of a file, and that is *bad*

### ISSUE THREAD

**Issue by villares** [typora/typora-issues#3567]
### My System

Typora 0.9.89 on Linux (also seen on Mac OS)

### Description

I'm not sure how to reproduce this, but quite often Typora will remove a blank line before a ruler instruction  `---` when at the start of a markdown document. And **that breaks the Jekyll build in GitHub Pages** so it is very annoying.

```
[space]
---

... more stuff 
```

becomes

```
---

... more stuff 
```
Please find a way to avoid doing this!

**Comment by abnerlee** [comment]
should be fixed in new release
