### ISSUE TITLE
Customize tabs style

### ISSUE THREAD

**Issue by kinoute** [typora/typora-issues#3568]
Hello there,

Great app! While making my first theme, I struggle to find a way to stylize the tabs system on macOS, despite digging into the source codes of other themes. Any hints?

![Capture d’écran 2020-06-01 à 15 53 18](https://user-images.githubusercontent.com/623763/83415828-0c455300-a420-11ea-9ade-8fa07a581ab6.png)

I would like to change the background-color of the inactive tabs as well as the "+" button.

Thanks!

**Comment by abnerlee** [comment]
They are built-in by macOS, like menu or context menu, Typora does not support stylize them
