### ISSUE TITLE
One Clcik Publish / Jekyll Support

### ISSUE THREAD

**Issue by sreevisakh** [typora/typora-issues#357]
I use typora to publish to my github pages, I would like a single click publish function which add & commit & push with a single button

**Comment by abnerlee** [comment]
seems unnecessary. `git commit -am "..." && git push` is enough. And for cases like conflicts, one button ins not enough

**Comment by pburrows** [comment]
Even a "run command" option where the user has to enter their own command that needs to be run would be great. A knowledgeable user could set up the command, and then the non-technical users could just click the button.

**Comment by jwenjian** [comment]
> Even a "run command" option where the user has to enter their own command that needs to be run would be great. A knowledgeable user could set up the command, and then the non-technical users could just click the button.

And pass the whole markdown content(or absolute path of current file) as the command argument would be very helpful.

And hope "run command" option can be mapping to a shortcut, like `Ctrl` + `R`?
