### ISSUE TITLE
Special characters "_" or "-" in mermaid classDiagram

### ISSUE THREAD

**Issue by pastorpflores** [typora/typora-issues#3572]
Using typora 0.9.89 I can't render a mermaid classDiagram with names such as:

```
classDiagram
func_name --> sub_func
```
Output: 

ERROR: [Mermaid] Parse error on line 2:
classDiagramfunc_name --> sub_func
-------------------^
Expecting 'NEWLINE', 'EOF', 'LABEL', 'STRUCT_START', 'ANNOTATION_END', 'STR', 'AGGREGATION', 'EXTENSION', 'COMPOSITION', 'DEPENDENCY', 'LINE', 'DOTTED_LINE', 'UNICODE_TEXT', 'NUM', 'ALPHA', got 'PUNCTUATION'

I think this is related to the mermaid version in Typora. Trying this diagram in a mermaid 8.5.1 editor I have no issues rendering it.

I'm aware of issue #1661, but I'm not sure of which version of mermaid does Typora use, or if I can update it independently from typora. Can I update it manually?

Thank you!

**Comment by abnerlee** [comment]
Typora is using `8.4.0`, so this may be fixed after we upgrade our mermaid version
