### ISSUE TITLE
Export .md to .docx doesn't properly do underlines

### ISSUE THREAD

**Issue by StripedMonkey** [typora/typora-issues#3574]
If you have an underlined word or phrase in a markdown (using the <u>underlined text</u> syntax) the exported .docx correctly underlines the text but keeps the `<u>` and `</u>` in the text
Example:
[Underlined.docx](https://github.com/typora/typora-issues/files/4722851/Underlined.docx)

(GH doesn't allow md files to be uploaded for some dumb reason, so extension was changed to txt)
[Underlined.md.txt](https://github.com/typora/typora-issues/files/4722853/Underlined.md.txt)

**Comment by abnerlee** [comment]
fixed in new release
