### ISSUE TITLE
Issue with changing list type when there is a math block in it.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3575]
OS:win10|Typora:0.9.89(beta)

----
Both using the hotkey and using the option tabs can produce this problem. When I trying to convert the list type from an ordered list to an unordered list where I have inserted a math block, the math rendering will disappear. I just recorded my screen so you can see it by yourself(I use my hotkey there, but same for option tabs).
![aa](https://user-images.githubusercontent.com/46404230/83666668-de1e6980-a5ff-11ea-9ff5-7b16339e1766.gif)

**Comment by abnerlee** [comment]
should be fixed in new release
