### ISSUE TITLE
Improvement for the logic of the list changing control for the list where inserted a math block.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3576]
OS:Win10|Typora:0.9.89

----
When there is already a list style and you click the option called ordered[or unordered] list, you definitely want to change its type or remove the style from the document. For the ordinary list(where there is no math block in the list except for some words in it), this is the case it is. But when it comes to the list where there is a math block in it, It will add a new list even if it is in the **first line** of all list.

![momyd-8d24q](https://user-images.githubusercontent.com/46404230/83670508-df529500-a605-11ea-9bd8-b4eb38e0ae07.gif)

**Comment by abnerlee** [comment]
should be fixed
