### ISSUE TITLE
An issue for writing a list where embeded a math block.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3577]
Win10|0.9.89 
When you move your caret out of a math block that embedded in a list. Specifically, pressing your down key when you finish the math editing. And since you are still in a list, the odds are you are going to create another list item. Then the trouble occurs that err... your words typed after it were not wrapped with `<p></p>`
![xqkmf-mpy8c](https://user-images.githubusercontent.com/46404230/83673152-fd21f900-a609-11ea-8a53-9c7811bd6552.gif)

![image](https://user-images.githubusercontent.com/46404230/83675314-5f2f2e00-a60b-11ea-83fc-fb52364547fc.png)

**Comment by peetteerr** [comment]
And I am quite confused with when it will automatically trigger a new list item when moving out of a math block embedded already in a list. I suggest we can cancel this probabilistic feature so no more question mentioned above any more.

**Comment by abnerlee** [comment]
should be fixed
