### ISSUE TITLE
How to set the (relative) width and height of an image?

### ISSUE THREAD

**Issue by flangel** [typora/typora-issues#358]
Hi,

awesome editor. How do I set the (relative) width and height of an image inserted by using markup?

Thanks a lot in advance
Frank

**Comment by abnerlee** [comment]
Currently, raw html is supported.

`<img src="..." height="100px" />`

or 

`<img src="..." style="zoom:50%">`

**Comment by abnerlee** [comment]
For other markdown syntax -> 249
