### ISSUE TITLE
An issue in writing inline math.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3580]
win10|.89

----
The problem is that what you type after the dollar sign may sometime be trapped in the "md-before md-meta" label, or put it in another way, do not goes to the right label wrapping latex code. For what condition to be meet this trouble may occur I still haven't a clue yet.
![image](https://user-images.githubusercontent.com/46404230/83751001-b92a0500-a698-11ea-85a0-8a9fac01510f.png)

**Comment by abnerlee** [comment]
did you use any IME? And is there a way to reproduce this?

**Comment by peetteerr** [comment]
@abnerlee  Somehow, It occurs when you move the caret to the head of the line after having typed a string of words.
![cef1a061-4ec0-4a0d-a6d6-269812b42f0a](https://user-images.githubusercontent.com/46404230/84514774-26274580-acfe-11ea-9840-b8d87862cca5.gif)

**Comment by abnerlee** [comment]
should be fixed
