### ISSUE TITLE
[feature suggest]new list indentaion control

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3581]
win10|.89

---
- For list's (right)indention there is already an option for indenting *one list item*. It is a really great design. But I would like to know is it possible to also add a new option for indenting not only a single line(or level) where your caret in but also all sublist following it. So this kind of indentation won't break the list structure if you just want to add one new list level prior to all existing list level(otherwise you have to indent one by one manually to retain the previous list structure)
- This is very useful for me personally so feel free to comment.

**Comment by abnerlee** [comment]
You can select a range and indent
