### ISSUE TITLE
Crashes when minimizing window

### ISSUE THREAD

**Issue by CovalenceSTU** [typora/typora-issues#3582]
OS: Windows 10 Home 1909
Typora version: v0.9.89

When I have multiple Typora windows open (4+) and minimize one, everything except the menubar disappears when I bring it back into focus. The window also won't respond to setting changes although the menus work; if I change the theme it will change for all other windows except that one.

Other things such as the About screen do not work white it is glitched as well.

![image of glitch](https://user-images.githubusercontent.com/45858927/83800466-5286f600-a65c-11ea-8bae-01b4660bd649.png)

UPDATE: It sometimes happens with <4 windows as well. Minimizing and bringing the window back also sometimes brings it back.

**Comment by abnerlee** [comment]
can resize window fix this?

**Comment by abnerlee** [comment]
may relates https://github.com/electron/electron/issues/22670

**Comment by abnerlee** [comment]
should be fixed in new release
