### ISSUE TITLE
Image load failed when using gitee url.

### ISSUE THREAD

**Issue by chen1mingCuc** [typora/typora-issues#3583]
I downloaded PicGo app, and set gitee as my pic-bed.

Everything went well the first time i drag the pictures in Typora. Pictures were shown and uploaded successfuly.

but the second time i opened Typora, i can't see the pictures.
![image](https://user-images.githubusercontent.com/64313759/83835096-7ad92800-a722-11ea-8114-043a21b44afc.png)

then i check the PicGo app, i can't open the albums. but the pictures online are shown well.
![image](https://user-images.githubusercontent.com/64313759/83835186-af4ce400-a722-11ea-8535-0576eeb3d1b6.png)

i don't know what to do to fix it. is there some bugs? 

ps : i open another .md file, and the pictures shown well, including online and local ones.
is there something wrong with gitee and PicGo app?

**Comment by abnerlee** [comment]
Does gitee requires "login" to access the image?

**Comment by Guoshiqi0830** [comment]
I have the same issue, the only difference is that I'm using github as my figure bed.
Here's my image url.

https://raw.githubusercontent.com/Guoshiqi0830/FigureBed/master/img/image-20200328203018422.png

I can open it in chrome, but I can't load it with typora.
My typora version is 0.9.89 and my operation system is windows 10.

**Comment by chen1mingCuc** [comment]
Well, after changing the Image Uploader to `PicGo-Core(command line)` and using sm.ms token instead, the issue solved.
