### ISSUE TITLE
Additional Spell check disappears after every restart of app

### ISSUE THREAD

**Issue by cichy1173** [typora/typora-issues#3584]
Hey. I am using KDE Neon OS. I have really big issue. When I turn on Typora and install polish spell check it works fine. But when i turn off Typora and restart it, this spell check disappears and I have to install it again.

You can watch video below. 
https://u.pcloud.link/publink/show?code=XZuer6kZpYxV7VkoOdLvqSTq6gTPGHYVW7ck

**Comment by RistoJu** [comment]
Same here. After the latest update (0.9.89) additional spellcheck is flagged as not installed, and cannot be used. Once installed it works fine until the app restart, and it whines again. Debian 10.4 - XFCE

**Comment by cichy1173** [comment]
> Same here. After the latest update (0.9.89) additional spellcheck is flagged as not installed, and cannot be used. Once installed it works fine until the app restart, and it whines again. Debian 10.4 - XFCE

So We can assume that it is a real problem. On my Windows machine I didnt make any update (typora 09.83) and all works fine

**Comment by abnerlee** [comment]
Can you see `pl.aff` and `pl.dic` under `%appdata/Typora/dictionaries`? you can find `%appdata/Typora/themes` folder by click "open themes" button in preferences settings.

And if there are error logs related to spellcheck (http://support.typora.io/Get-Logs/), please also attach them

**Comment by cichy1173** [comment]
> Can you see `pl.aff` and `pl.dic` under `%appdata/Typora/dictionaries`? you can find `%appdata/Typora/themes` folder by click "open themes" button in preferences settings.
> 
> And if there are error logs related to spellcheck (http://support.typora.io/Get-Logs/), please also attach them

Ok. I checked all of that. files pl.aff and pl.dic exsist in this folder. This is how it looks when i use typora with installed spellcheck
![Zaznaczenie_010](https://user-images.githubusercontent.com/32648503/84173262-57451300-aa7d-11ea-8af6-88e25e076a4e.png)
When i turn off Typora this files still exsist in this folder but when I turn on Typora and I want to use polish spellcheck it wants me to install this files again. Hitting install just overwriting pl.dic and pl.aff in this folder. 

![Zaznaczenie_011](https://user-images.githubusercontent.com/32648503/84173460-9a9f8180-aa7d-11ea-9f3a-917ada27afaf.png)

But I think it can be related to polish. I installed spanish spellcheck and after Typora restart all works just fine and app doesnt ask me for reinstalling spanish spellcheck.

**Comment by pelid** [comment]
Same problem on Ubuntu 18.04. Every launch Typora install russian dictionary newly. It`s annoying.

```
$ ls -1 ~/.config/Typora/dictionaries
en_GB.aff
en_GB.dic
en_US.aff
en_US.dic
ru.aff
ru.dic
ru-LICENSE
user-dict.json
```

**Comment by sagischwarz** [comment]
I have the same problem using Typora `0.9.89` on Arch Linux with German dictionaries. The problem did not exist in the previous version `0.9.86`.

**Comment by cichy1173** [comment]
> I have the same problem using Typora `0.9.89` on Arch Linux with German dictionaries. The problem did not exist in the previous version `0.9.86`.

Ok, so We can say it's Linux-related issue in Typora 0.9.89

**Comment by nermaloids** [comment]
I have the same problem with the English UK dictionary `0.9.89` on Elementary Hera

**Comment by kevquirk** [comment]
+1 same problem with UK dictionary on 0.9.92(beta) on Pop!_OS (Ubuntu 20.04 base).

**Comment by cichy1173** [comment]
So it's really big issue. Fix would be nice :)

**Comment by MikeHofmann** [comment]
+1 with de dictionary using 0.9.93(beta) under Ubuntu 20.04.1 LTS

**Comment by cichy1173** [comment]
Updated Typora but still problem exists.

**Comment by stefan2904** [comment]
Same problem with Typora 0.9.96 on Ubuntu 19.10 with EN-US (default spellcheck language). 

---

test text:

![image](https://user-images.githubusercontent.com/527767/96263346-2fcdfc00-0fc3-11eb-8a10-9b724bb53d9e.png)

nothing highlighted although spellcheck is enabled

![image](https://user-images.githubusercontent.com/527767/96263261-17f67800-0fc3-11eb-83fe-8d3f43a2d243.png)

spellcheck files are there

![image](https://user-images.githubusercontent.com/527767/96264901-0dd57900-0fc5-11eb-9443-5054c11784e4.png)


→ lets install the files again

![image](https://user-images.githubusercontent.com/527767/96263299-22b10d00-0fc3-11eb-87c7-8346fa9b4c40.png)

→ spellchecks works now:

![image](https://user-images.githubusercontent.com/527767/96263769-ad920780-0fc3-11eb-8e19-62faeb44a0f2.png)


nothing concerning this in `typora.log`, btw

**Comment by stefan2904** [comment]
btw, there are multiple `dictionaries` folders in my typora home, maybe there is an issue with capitalization in your code? (filenames are case-sensitive on linux, while they are not on Windows.)

![image](https://user-images.githubusercontent.com/527767/96266567-12029600-0fc7-11eb-88d1-361f300a1473.png)

**Comment by stefan2904** [comment]
ok I think I figured it out, when I start tracing before opening a file, I see this:

```strace
24846 openat(AT_FDCWD, "/usr/share/typora/resources/app/node_modules.asar/spellchecker/vendor/hunspell_dictionaries/en_US.dic", O_RDONLY <unfinished ...>
```

which is a file that does not exist? 

`node_modules.asar` is a file, not a directory. maybe you mean `node_modules` instead?

if so, `/usr/share/typora/resources/app/node_modules/spellchecker/vendor/hunspell_dictionaries` exists and contains some dictionaries, but apparently not the ones installed in the step above -- I think those are the spellcheckers that are part of the typora package itself. 

---

for tracing, I used: 
`ps aux | grep -i typora | awk '{print"-p " $2}' | xargs sudo strace -o /tmp/typora-strace.log -f`

**Comment by pbentkowski** [comment]
I have the same problem with the Polish dictionary missing every time I re-start Typora. I run version 0.9.96 (beta) on Ubuntu 20.04 LTS. However, when I run it like this:
```
sudo typora --no-sandbox
```
And then the Polish dictionary works fine. 
I have it also in `/usr/share/typora/resources/app/node_modules/spellchecker/vendor/hunspell_dictionaries/` - I don't know if it's related.

**Comment by pbentkowski** [comment]
OK... I think I've got it... at least a hack. 

What I did:
1. From LibreOffice repo https://github.com/LibreOffice/dictionaries I've downloaded all the dictionaries.
2. With _sudo_ I copied _pl_PL.dic_ and _pl_PL.aff_ to Typora's default dictionaries directory. 
```Bash
cd /usr/share/typora/resources/app/node_modules/spellchecker/vendor/hunspell_dictionaries
sudo cp ~/Downloads/dictionaries-master/pl_PL/pl_PL.* .
sudo chmod 777 pl_PL.*
```
3. Removed user's Typora configs: `rm ~/.config/Typora/` and (re)started Typora.
4. It asked me to install the Polish dictionary, but ones and never more. You have to wait a couple of seconds before Typora recognises the language and underlines misspelt words.

**Comment by stefan2904** [comment]
Thanks for the hint, pbentkowski. Unfortunately that did not work for me ...

I still need to "install" a dictionary after opening a file, each time ...

**Comment by agenttux** [comment]
has there been a fix yet for this issue? I have this on Ubuntu 20 as well

**Comment by cichy1173** [comment]
> has there been a fix yet for this issue? I have this on Ubuntu 20 as well

We don't have a good solution for this. I left Typora for Mark Text app

**Comment by VegaDeftwing** [comment]
bumping this issue, as it has been an issue for me for a long time as well. Arch Linux, Typora 9.98 from the AUR

**Comment by thwaller** [comment]
I also have this issue. I use Ubuntu 18.04.5 and Typora 0.9.98(beta). I install EN-US and it is gone every time I restart the application.

**Comment by Jaaaarne** [comment]
Same issue on Fedora 33, Typora 0.9.98 with Russian dictionary. A bit annoying, tbh.

**Comment by abnerlee** [comment]
relates #214

**Comment by llsaboya** [comment]
Same think in 0.10.11 in Pop OS and Solus OS.

**Comment by MarcoDuiker** [comment]
Same issue here with dutch (nl) under Ubuntu 16.04.

**Comment by pbentkowski** [comment]
> Same issue here with dutch (nl) under Ubuntu 16.04 on Typora 0.11.16

Well.... my Typora installation is in version 1.0.2 (since 1.0.0 Typora costs money) and it seems to solve the issue on Ubuntu 20.04.

**Comment by aproposnix** [comment]
Happy New Year everyone :) 

For me, the only dictionary I cannot keep installed is the American English one. I need to reinstall it every time. 
However, If I pick the GB English, it persists through restarts. 

Would love to see a fix for this issue. 

OS: Ubuntu 20.04 
Typora v 1.0.3

**Comment by jamestevans-uk** [comment]
I've updated Typora from V1.0.4 to V1.1.2. (Licensed)
Dictionary download no longer happens on every restart and en_GB spell check is immediately available.

Here en_US was always available, en_GB was requested on each restart. The en_GB files were available alongside en_US in the ~/.config/Typora/typora-dictionaries directory. 
        
        Ubuntu 20.4.3 LTS 
        Ubuntu-1 5.4.0-100-generic #113 - kernel upgraded at same time as Typora.

I've spent several hours chasing this so happy to report this result.

**Comment by RockwoodOnt** [comment]
Typora for Linux 0.11.18 beta

I think I found the culprit. 

If to delete the  folder `/home/user/.config/Typora/Local Storage` before launching `typora`, it doesn't ask for downloading a dictionary that is already downloaded. But prior to that the dictionaries should be copied to `/usr/share/typora/resources/node_modules/spellchecker/vendor/hunspell_dictionaries` with permissions `-rwxrwxrwx 1 root root`.

So

```
rm -rf /home/user/.config/Typora/Local Storage
typora /home/user/file.md
```

Spell check icon in the status bar flashes with a check mark, then switches to `EN-US`, or `EN-GB` or whatever, `Auto Detect Language` get disabled while staying marked and a red underline  for misspelled words doesn't show up but the dictionaries while switching don't ask for downloading. And then the spell checker starts working OK with the red underline and spelling suggestions in the right mouse click menu.

On the second launch without deleting `home/user/.config/Typora/Local Storage` downloading starts all over again.

**Comment by gungorenu** [comment]
I have similar issue and I have a workaround, and perhaps the reason as above mentioned. I have windows system though.

Windows 10 x64, Typora 1.1.3

- If I open Typora by double clicking on a md file then the spellcheck goes missing (the underlined errors), like others mentioned. I click on language selection (DE) then asks me to download the files, which I already have them. if I opt to download then spelling works.
- if I open Typora with "admin rights" and then open file (from recent files for example), everything works perfectly (spellcheck works from beginning and switching to a different language and then switching back to DE works perfectly).
- if I open Typora first (without admin rights) and then navigate to the file using folder structure on left panel then everything works perfectly.
- I set Typora to run in admin mode by right clicking on Typora.exe. Same problem occurs as above (double click on file scenario)
- I open the md file using command line like `C:\Program Files\Typora\Typora.exe c:\test.md` and still same errors as above (this is same with double clicking on a file anyway). it does not matter if console is started as administrator.

so in my case opening a file with parameter does not work but if I navigate through Typora then everything works. Files have full rights and I am admin on machine. it does not seem to be a permission issue but it is about how typora starts (with parameter or without).

I had 0.9.96 version, or sth like that and everything was working there.

I do not know why the behavior matters if I double click on a file to open md file but not through Typora menu

**Comment by RockwoodOnt** [comment]
> I do not know why the behavior matters if I double click on a file to open md file but not through Typora menu

As I said, Typora has a folder `Local Storage` containing some kind of a database `leveldb` with binary files. On windows the path is `C:\Users\UserName\AppData\Roaming\Typora\Local Storage`. I didn't try Typora on Windows but I think its behavior is pretty much the same.

At first run Typora remembers the settings and then doesn't let change them. From my experience on Linux it was even funny when running as user Typora wants to download EN-GB but when running as root EN-GB was fine but EN-US wanted to be downloaded. I discovered if to delete `Local Storage' before starting Typora the folder gets recreated with different settings or environment and runs OK until you decide to change something. It won't let you until you delete the folder `Local Storage'.

**Comment by gungorenu** [comment]
I am not sure if these are related, maybe they are. for me deleting the local storage means Typora shall not remember which file has which language as spellcheck, I do not know if it means something else.

in my local the DE locale file is not in `typora/resources/node_modules/spellchecker/vendor/hunspell_dictionaries`. there is only en_US, by default I guess. I tried with different locales now but no, these locales are not copied there. I never needed to copy something here and typora does not copy either obviously, in working case for me.

now I realized another thing (and also maybe why I have a working case)
- Typora has an option on what to do on Launch. if I select open new file or restore files, then the working case for me also does not work anymore. I use the open folder option here and then it works.

**Comment by abnerlee** [comment]
Hi, If you use Typora 1.1.x, open DevTool from View -> Toggle DevTool from menubar and input following in the console, will it return object or null?

```js
File.editor.spellChecker.spellCheckFactory.getSpellChecker("DE");
```

And what about

```js
File.editor.spellChecker.spellCheckFactory.getSpellChecker("DE", true);
```

**Comment by gungorenu** [comment]
hi, for me both calls return an object (definitely not null) in my case. but still DE spellcheck cannot be found and asks me to download it again.

> Hi, If you use Typora 1.1.x, open DevTool from View -> Toggle DevTool from menubar and input following in the console, will it return object or null?
> 
> ```js
> File.editor.spellChecker.spellCheckFactory.getSpellChecker("DE");
> ```
> 
> And what about
> 
> ```js
> File.editor.spellChecker.spellCheckFactory.getSpellChecker("DE", true);
> ```
