### ISSUE TITLE
 Emphasis and Strong effect not work on chinese characters

### ISSUE THREAD

**Issue by adamhj** [typora/typora-issues#3586]
It seems the same issue has been submitted but was not well described (#820)

I get same issue here, when I try to add  Emphasis or Strong effect in typora to a piece of text, chinese characters in it does not apply bold or italic style correctly

example:
![image](https://user-images.githubusercontent.com/1115256/83941797-e43f6080-a820-11ea-9114-9b8ce6d0ec2a.png)

or source code:
![image](https://user-images.githubusercontent.com/1115256/83941806-edc8c880-a820-11ea-9f0e-f372c1dba103.png)

alpha character and numbers works correctly, but chinese charaters 

while these all work on github
> abcdefg1234567中文测试
> *abcdefg1234567中文测试*
> **abcdefg1234567中文测试**

---

It seems that this is a theme issue, when the theme is Github, Newsprint, Whitey,  emphasis and strong not work at all on chinese characters. In Night theme, Strong applies highlight style on chinese characters, though bold/italic is still missing. Only Pixyll theme works with no problem on chinese characters with emphasis or strong effect

Ttypora version number is 0.9.89(x64), Windows 7.

**Comment by adamhj** [comment]
I found that I can fix this by change the font family in the theme's css style file, appending a font that support chinese character as the last fallback, but I'm wondering that can typora support apply bold/italic effect directly when all font family in the style file are absence and it falls back to the default system font?

**Comment by abnerlee** [comment]
should be fixed
