### ISSUE TITLE
End command do not work properly in shrinked window.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3587]
Win10|Typora.89

---
- <kbd>End </kbd>  keystroke in math block will not move the caret to the end of the line when you docked window in one side of the screen.  The position that the caret moves to depends on the size of the window i.e. the wider the window is the closer it gets to the rear of the line. And particularly when you toggle full-screen mode such problem won't occur.

**Comment by peetteerr** [comment]
Oh, It is still possible to occur even in full-screen mode.
![cfe94067-93bc-4dad-a56d-3c4a66c90dbf](https://user-images.githubusercontent.com/46404230/84379778-f4887e80-ac18-11ea-9ad2-506427c9e368.gif)

**Comment by abnerlee** [comment]
should be fixed in new release
