### ISSUE TITLE
YAML frontmatter no longer instantaneously updated in Files list view

### ISSUE THREAD

**Issue by bencarp** [typora/typora-issues#3589]
Since the latest update, changing name and description tags in yaml and then saving the file doesn't update the preview in the Files tab anymore. After restarting typora, the front matter is read and displayed correctly.

### Steps for reproduction
- Files side bar appearance: Articles (List View)
- Create a new file or edit an existing file's front matter
- Upon saving (manually), the preview in the Files bar is never updated

OS: Debian GNU/Linux 11 (Bullseye, Testing)
Version: 0.9.89(beta)

**Comment by abnerlee** [comment]
should be fixed in new release
