### ISSUE TITLE
Case sensitivity issue with filenames on Windows (0.9.21)

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#359]
If a file is opened using other than its canonical name (e.g. you open `A.md` as `a.md`) via command line or links, it is not recognized as being an already-open file, so a new window is opened for it, instead of changing focus to the existing window.

(During my testing, I actually managed to get three different versions of the same file open (via different case invocations of different parts of the filename), but oddly one of the windows includes a full absolute path in the title bar; I'm not sure how that happened, though, since I never invoked it with a full file path.)

**Comment by pjeby** [comment]
Interestingly, saving the file from one of the three open windows actually caused *all three* windows to prompt to reload due to an external change of the file.  :)

**Comment by abnerlee** [comment]
Should be fixed in new version
