### ISSUE TITLE
Cannot open themes folder

### ISSUE THREAD

**Issue by Hanyuze-iu** [typora/typora-issues#3590]
![Uploading image.png…]()
这怎么解决呢？

**Comment by Hanyuze-iu** [comment]
![image](https://user-images.githubusercontent.com/62991927/84110902-551c8d80-aa58-11ea-911d-16338c39ebb7.png)

**Comment by abnerlee** [comment]
may relates https://github.com/electron/electron/issues/11617

**Comment by abnerlee** [comment]
I cannot reproduce this.

Looks like a system issue, https://answers.microsoft.com/zh-hans/windows/forum/all/win10/d671ab03-ac19-468d-a452-093e77e40f5e may help
