### ISSUE TITLE
New feature suggestion - support for linter plugins

### ISSUE THREAD

**Issue by Tjianke** [typora/typora-issues#3592]
New feature : linter plugin to lint to typo or formatting issue

take this pic for example, if there is a lint plugin to separate Chinese character and ASCII characters by one space automatically, then it would be very efficient

<img width="130" alt="image" src="https://user-images.githubusercontent.com/34013484/84129862-16e19700-aa75-11ea-97e3-b1bb61d9b616.png">

**Comment by abnerlee** [comment]
put into #1316
