### ISSUE TITLE
Still insufficient control over PDF export margins, paddings etc.

### ISSUE THREAD

**Issue by JoeChip96** [typora/typora-issues#3593]
I came to Typora because it combines a small footprint with great Wysiwyg optics and rendering of HTML inline code with a pleasing result when exporting to PDF. But even though this has been requested for years, there is still insufficient support for formatting the PDF output, especially when it comes to margins, paddings and content which is supposed to span a whole page (book-cover images, e.g.)
The developer regularily points to issue [#998](https://github.com/typora/typora-issues/issues/998) from october 2017- but there still are no definitive solutions, since the PDF export always creates unwanted borders and paddings which obviously one can't get rid of by simply using CSS overrides. I need full control over margins, paddings etc. - and if there IS a solution for this already it should be included into the support.typora page

**Comment by abnerlee** [comment]
duplicate with #998 

It's now not supported yet
