### ISSUE TITLE
Use standalone parser - Compatibility reasons

### ISSUE THREAD

**Issue by J-Cake** [typora/typora-issues#3595]
I've written in markdown for a while now and I've come to love it more than anything. I use it to write websites etc and Typora makes this even easier. I only have one issue with it - When I write more complex documents, rendering them in websites requires me to thoroughly analyse the contents of the document and install all necessary plugins for markdown parsers such as `markdown-it` which often have different compatibility systems with certain markdown features. A good example is the superscript plugin that comes with Typora. The plugin does not support nested markdown however `markdown-it-sup` does. In order to get consistent results, I nee to use the HTML tags for superscript, which just goes against the whole point of markdown. Instead I suggest separating the parser (the bit that translates the actual markdown into HTML) to preferably a separate executable or script and using that throughout the program, where using it would only require interfacing with another process or importing a library. Either way, this would be the best way to ensure consistency between preview in Typora and correct rendering outside of it.

**Comment by abnerlee** [comment]
markdown-it use the md content as input, we can't let the parser to re-parse and re-render the whole document each time after user types, and you will open un-trust documents contains raw HTML content . There will be performance cost and security concerns
