### ISSUE TITLE
hyperlink seperator

### ISSUE THREAD

**Issue by mintAqrua** [typora/typora-issues#3598]
When I drag a file from left side to an opening editing file, a hyperlink will be created and it's great. But it uses '\\' instead of ‘/’ as seperator. I undertand it is a system thing, and some program like vscode only accepts '\\'. But since github only accepts ‘/’, will you consider add a button for that in setting?

**Comment by abnerlee** [comment]
Added in #2415

**Comment by gizmhail** [comment]
I think the problem is still currently here, and it is a problem when we edit a set of page locally before pushing them to something like github, with a web navigation expected, and hence "/" instead of "\".
