### ISSUE TITLE
Auto-saved files are not reopened after crash

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#3600]
For a few weeks, after Typora has crashed, it does not correctly reopen all previously opened documents. Documents that already had been saved to disk are opened correctly, but for each yet unsaved document, only an empty window with the plain title "Typora" appears. However, I can find the missing files in the `draftsRecover` folder.

**Comment by abnerlee** [comment]
What's your Typora version and OS?

**Comment by LinqLover** [comment]
Version 0.9.89(beta) (Why do I have a beta version installed? ^^) and Win 2004.

**Comment by LinqLover** [comment]
In some cases, Typora also displays the correct file title, but the window's contents do not load. I can see the menu, but I don't see any text and I cannot type into that window. Is this a separate bug?

**Comment by LinqLover** [comment]
I just saw the same issue in a totally different situation: All my windows' contents disappeared after toggling "Show Desktop" in the taskbar (Windows) twice. I can use the menu, but I cannot see or copy the text. So probably ~"File Management" is the wrong category ...

**Comment by abnerlee** [comment]
so are those **two** issues that you find Typora window with total empty content, and clicking it has no responding?

If so, does "resize" the window, or minimize then recover bring the content back?

**Comment by LinqLover** [comment]
Sorry for the late feedback.

> so are those **two** issues that you find Typora window with total empty content, and clicking it has no responding?

Issue 1 refers to the window UI being dead. Issue 2 refers to files that have been auto-saved but not been reopened after a crash.

I could just reproduce issue 1 on my machine! All I need to do is to find any of my open Typora windows, minimize it, and after a few seconds, restore it. Suddenly it looses its context and does not react to further inputs:

![Typora dead (#3600)](https://user-images.githubusercontent.com/38782922/86131425-ede97a80-bae5-11ea-9e93-c2d59d3a5ea1.gif)

> If so, does "resize" the window, or minimize then recover bring the content back?

No.

> Is this same with #3527?

I'm not sure about this. Toggling fullscreen twice does **not** bring back my windows' contents, and differently to @sgon00, not only the writing part is empty, but all dialog windows are lost, too. On the other hand, I can still show menus, as shown in the screencast.

Please let me know if I can provide further information.

**Comment by abnerlee** [comment]
duplicate with #3582
