### ISSUE TITLE
Feature Request: Do not force the navigation pane to be enabled when opening folders on windows

### ISSUE THREAD

**Issue by fresheneesz** [typora/typora-issues#3601]
On windows, if you ctrl-click a link that opens a directory, the folder window opens with the navigation pane open. If I then close that window, every time I open a folder in the system after that, it has an annoying navigation pane. This has been a HUGE pain for me, since in order to avoid this, every time I open a directory with Typora I need to go to view, turn off the navigation pane, and then use the window or close it. 

Please just use the default window settings instead of forcing view settings.

**Comment by abnerlee** [comment]
open file will use the previous sidebar effects.
open folder will show the side panel, because "Folder" cannot be edited, the way to "read" a folder is to display its contents. So I think it make sense.

So would you explain your expected behavior, and why should Typora do that?

**Comment by fresheneesz** [comment]
> open file will use the previous sidebar effects.

I'm not sure what you mean by "previous sidebar effects". When I open a folder, it always has the navigation pane open, even tho none of my other folders have a navigation pane - so I don't think it is respecting the previous sidebar effects.

> "Folder" cannot be edited

I don't know what you mean here. Could you clarify?

> the way to "read" a folder is to display its contents

I also don't know what you mean. I certainly agree that opening a folder displays its contents, and that is what's intended. What I think should be fixed is that [the "navigation pane"](https://www.tenforums.com/tutorials/35310-show-hide-navigation-pane-file-explorer-windows-10-a.html) should respect the options you have configured for the rest of your folders. For me, I do not want the navigation pane of the folder to be open. 

> So would you explain your expected behavior, and why should Typora do that?

I believe I explained that in my original post. Could you please point out to me what you don't understand about my original explanation?

**Comment by abnerlee** [comment]
> For me, I do not want the navigation pane of the folder to be open.

In that case, a blank window will be displayed when opening a folder, I don't think user can understand that this is not a bug but a folder has been opened.

**Comment by fresheneesz** [comment]
> a blank window will be displayed when opening a folder,

What? Why? Why would the window be blank? It should just open up the directory you want to open *without* the navigation pane. Maybe you aren't understanding what I mean by that.

Right now I'm getting this, with the nav pane on the left:

![navpane](https://user-images.githubusercontent.com/149531/88190950-c4f16c80-cbef-11ea-8f41-5251983481a6.jpg)

I want to see this, with no nav pane:

![nonavpane](https://user-images.githubusercontent.com/149531/88191013-d470b580-cbef-11ea-9c2f-6ca444400f2d.jpg)

**Comment by abnerlee** [comment]
So I may misunderstood your requirement,

When open a folder, you want to see Typora display the folder content in main writing area?

**Comment by fresheneesz** [comment]
No, I'm not asking that Typora display folder contents in some custom way inside the app. I just want it to open a normal windows folder window in whatever way I have configured as my default. I don't want it adding the nav pane when my folders aren't configured to show the nav pane.

**Comment by abnerlee** [comment]
> What? Why? Why would the window be blank? 
> No, I'm not asking that Typora display folder contents in some custom way inside the app.

If the navi bar is not open, what will the window display, instead of a blank one?

**Comment by fresheneesz** [comment]
What don't you understand about the screenshots I posted? The one without the navi bar is certainly not blank.
