### ISSUE TITLE
Terrible lags with Radeon GPU on macOS

### ISSUE THREAD

**Issue by Nico-Salamone** [typora/typora-issues#3602]
Typora is very laggy/slow on my MacBook Pro using a Radeon GPU when I open the sidebar (file tree). It only occurs on Markdown files located in a "large" folder (just including a few files).

[This video](https://www.dropbox.com/s/p0hbr5no4u6zc7k/typora_lag_issue.mp4?dl=0) shows this issue (take a look the GPU usage in the menu bar). As you can see, the first file named `test.md` is in a folder containing some files (48 files in this case) and the second one named `test_in_empty_folder.md` is, as its name suggests, in an empty folder. Typora is only slow on `test.md`.

This issue only occurs when my discrete graphics card (Radeon Pro 560) is active, not with the integrated GPU (Intel GPU).

Specifications:
- MacBook Pro 2017 15-inch (i7-7920HQ 3.1GHz, Radeon Pro 560 4Gb)
- macOS High Sierra 10.13.6
- Typora 0.9.9.33.2 (4442)

**Comment by abnerlee** [comment]
seems same as #3508
