### ISSUE TITLE
Right click in tree view on a file -> delete -> can't click on dialog

### ISSUE THREAD

**Issue by roorco** [typora/typora-issues#3603]
I'm on a linux system. As in the title, if I right click on one element in the tree file view and I try to delete file it, i can't click on OK or Cancel, I need to use the keyboard, Tab+Enter.
Moreover if I create a new file, Typora doesn't wait to rename untitled file, but dialog appears to confirm the first letter I wrote as new name. As above, in this dialog  can't click on Ok or cancel, need to use keyboard.

**Comment by roorco** [comment]
Hi, it doesn't seem the same problem as #3605 because the system doesn't become irresponsive, in my case it seems that for the Confirm delete dialog created by the right click on sidebar the system do not accept mouse click, but only keyboard input.

Another misbehavior, probably not connected, is renaming a new file: 
* right click > create new file > click on "Untitled" for renaming the file but the software do not wait for input, then I need to right click on the new file for renaming it .

**Comment by abnerlee** [comment]
should be fixed
