### ISSUE TITLE
Black blocks appear when scrolling

### ISSUE THREAD

**Issue by GenericUK** [typora/typora-issues#3606]
Hi,

OS: Linux Lubuntu 18.04 LTS

Ever since I've used Typora on this OS I get black blocks that randomly appear on some files after scrolling. I can't recreate what causes it but can only think it is some sort of graphic issue with my setup as no one else seems to have reported it. If anyone has any Idea what I can do to fix it or if it is something that is a bug. It doesn't happen on any other programs. Screenshot attached.

Thanks
Mark

![screenshot-typora](https://user-images.githubusercontent.com/1609873/84576571-a8227780-adad-11ea-9513-30111f39886a.png)

**Comment by abnerlee** [comment]
Updated Electron version which may fix this.

If not please try disable GPU by https://github.com/typora/typora-issues/issues/2051#issuecomment-450661753 or upgrade your GPU driver
