### ISSUE TITLE
Crash on update or install windows 64 version

### ISSUE THREAD

**Issue by Th3D0c** [typora/typora-issues#3607]
When trying to update or install fresh Typora for Windows 64bit version the installer crash with the error :
_Access Violation at address 777F9F0A in module ntdll.dll Read of adress 8140458B_

Previous version was working fine.

**Comment by abnerlee** [comment]
I didn't receive similar report from other users, and I cannot reproduce this either.

Please try 
https://answers.microsoft.com/en-us/windows/forum/all/app-crash-with-ntdlldll/9aa59f80-99a1-4f3c-b2f0-7eb72df05b2a
or
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/error-access-violation-at-address-7783e70a-in/8dfce455-1cf9-4e77-9f9a-1ce889a9ec07
