### ISSUE TITLE
"Open Theme Folder" button doesn't work (Windows 10)

### ISSUE THREAD

**Issue by ligz08** [typora/typora-issues#3608]
## Typora version
0.9.89

## OS
Windows 10 Pro, Version 10.0.18363 Build 18363

## Repro steps
In Typora, go to Menu --> Themes --> click "Open Theme Folder" --> nothing happens

**Comment by peetteerr** [comment]
+1

**Comment by shanehoey** [comment]
I can recreate this on w10 when the Window Style is "UniBody" only.  
If the Window Style is Classic I can open theme folder fine.
Let me know if you want more info

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by ligz08** [comment]
Fix confirmed on version 0.9.92. Thank you, folks!
