### ISSUE TITLE
[Bug] Source code mode confused by Export command

### ISSUE THREAD

**Issue by scooby** [typora/typora-issues#3611]
Hi, thanks for Typora.

### Severity

Cosmetic.

### Steps to reproduce

1. Create a new document and enter a few words of text.
2. Select View / Source code mode.
3. Select File / Export / PDF.
4. Note that the document visibly switches to normal mode.
5. Save dialog appears, and document exports normally.

### Expected behavior

Either:
* Preferably, the document should return to source code mode after export.
* Or, the document’s “source code mode” tag should correctly reflect the mode it’s in.

### Observed behavior

6. The source code mode tag is still present, but document is in normal mode.
7. Select View / Source code mode.
8. The document is now in source code mode, but the source code mode tag is hidden.

### Workaround

1. Save and close the document.
2. Reopen the document.

**Comment by abnerlee** [comment]
Fixed the button behavior in new release
