### ISSUE TITLE
Suggestion: Copying images from Typora

### ISSUE THREAD

**Issue by brandonseverin** [typora/typora-issues#3615]
The ability to copy an image from Typora so that when I click paste in a different application, I get the actual image rather than the markdown syntax please?

At the moment when I want to copy an image from Typora I search through my local images directory, this can take a while to find the right one.

**Comment by H8to** [comment]
As a workaround you may take a screenshot from the screenshot :stuck_out_tongue_winking_eye: 
`Greenshot` for Windows
`Flameshot` for Linux
This kind of works at the moment, but anyway I'd also appreciate a native solution :pray:

**Comment by abnerlee** [comment]
supported in new release

**Comment by H8to** [comment]
Hey @abnerlee 
Thanks for the first shot on this issue. 
I noticed however, that the format that is posted into the clipboard is not "an image".

Usually images that are in the clipboard have the format img/png or anything like this.
(CopyQ shows the content):
![image](https://user-images.githubusercontent.com/16744267/92944720-a2900880-f454-11ea-9926-562e816c70e2.png)

The way you export images is HTML though:
![image](https://user-images.githubusercontent.com/16744267/92944875-d3703d80-f454-11ea-92cd-044b0ecaf5ab.png)

This is incompatible with other software and also, if you copy it back into Typora, you will end up in having the absolute path as reference, which might not the goal.

I'd suggest to export the image as img/png e.g. and reimport it like you do already with all image data that comes in that format.

Hope that feedback is relevant to you. :)

**Comment by abnerlee** [comment]
Do you use "Copy Image" in menu or context menu?

**Comment by H8to** [comment]
Yes, that's the new button that I use. I'll try different snapshot tools and will report if there are differences. Maybe it's more complicated depending on the first source the image came from.

**Comment by H8to** [comment]
Sorry for the delay. I tried the following test case:

Copy an image from a website and paste it into the editor. Copy it back from there and the result will be both image/png + html:
![image](https://user-images.githubusercontent.com/16744267/95441651-aed78a80-095a-11eb-9f0a-a8e54f062701.png)

Doing screenshots just from the clipboard will result in only html being copied from the editor:
![image](https://user-images.githubusercontent.com/16744267/95441800-dcbccf00-095a-11eb-93e2-ceff08f05dfb.png)

**Comment by brandonseverin** [comment]
Could there be a way to copy an image as well as text at the same time? If I highlight text and an image, only the text copies. Thanks for resolving the copy image issue previously. Much appreciated.

**Comment by jonas-sk** [comment]
Same here! Using "Copy Image" or marking a bunch of text, which includes an image, doesn't work
