### ISSUE TITLE
Text highlighting does not export to latex

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3616]
Hi,

I find the ==key== highlighting of inline text very useful. Unfortunately, when exporting markdown to PDF via pandoc, this highlighting color is lost and the highlighted text in Typora becomes surrounded by the ==XXXX== characters. Could you please advise me on how to export Md to PDF properly while keeping my original highlighted text?

Thanks

**Comment by redoxmatlab** [comment]
I've solved this issue of the non-required '==' by writing a simple bash code which removes the '==' string before converting the document to PDF.  Still interested in how to keep text highlighted in the output file.

**Comment by abnerlee** [comment]
Is this issue about "export to latex" (in title) or "export to pdf" (in issue content)?

I think export to LaTeX in Typora have limited support for the `highlight` expression.
