### ISSUE TITLE
add support of links to headers in local md files i.e. [link](file1.md#header-2)

### ISSUE THREAD

**Issue by Krovatkin** [typora/typora-issues#3617]
First off, let me thank you for such a beautiful and feature-rich md editor!
I've been a **very happy** user of Typora for over a year now and Typora the best editing experience out of all the other editors I've tried!

One feature I come to miss more and more as I'm adopting the *Zettelkasten* note-taking method is to be able to link to headers in other local markdown files, which makes it much easier to build a context around a particular note.
I have tried inserting links `[link](file1.md#header-2)`. While Typora opens the right file, it does **not** scroll to the right header.

Could you please consider adding this feature or if is this something that has already been on your radar or maybe am I just using the wrong syntax? 

Thank you!

Versions:
```
Version 0.9.9.33.2 (4442)
MacOS Mojave: 10.14.6
```

**Comment by abnerlee** [comment]
duplicate with #2568
