### ISSUE TITLE
Mermaid linkStyle Not Working Correctly

### ISSUE THREAD

**Issue by langiole** [typora/typora-issues#3619]
The mermaid graph I want to render:
![Screen Shot 2020-06-18 at 9 51 02 AM](https://user-images.githubusercontent.com/14906622/85028587-44030900-b149-11ea-94b2-ebd2012697cc.png)

How Typora renders it:
![Screen Shot 2020-06-18 at 9 51 46 AM](https://user-images.githubusercontent.com/14906622/85028635-541ae880-b149-11ea-8d1a-2835ecba2122.png)

The code for the graph:
```
graph LR
A("Perception") --> |convert|B("Representation")
C("Perform Algorithmus / analyze") --> B
linkStyle default color:#f00
```

```
Typora Version: Version 0.9.9.33.2 (4442)
Mac Version: 10.15.4
```

**Comment by abnerlee** [comment]
see #1661
