### ISSUE TITLE
Add a defaut language option for code fence

### ISSUE THREAD

**Issue by shadeofgod** [typora/typora-issues#362]
hey just started to use typora to write something recently and when insert code fence I have to set the language manually every single time so the code highlighter could work.
so for me that means every time I have to type "javas"  then select javascript in the drop down menu.

for most of the programmer we always use the most common language in our article or blog. 

like c for c programmers, javascript for web developer and so on and since I didn't find a way to set it as defaut so I thought if we could have a setting option for this that would be much appreciated.

**Comment by AlexPasternak** [comment]
I suggested this a long time ago, please search existing issues first.

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/290
