### ISSUE TITLE
Bug: Quick Open matching algorithm fails on longer words

### ISSUE THREAD

**Issue by clozach** [typora/typora-issues#3620]
When typing words longer than 5 or 6 characters, Quick Open stops matching past a certain point. Here are a couple screen captures to demonstrate the issue.

**Steps to reproduce (example 1)**
* Type "histor"
→ As expected, files match containing words like "history" and "historical"
* Add an `i`: "histori"
→ Expected: Results filter out files with "history" but retain those with "historical"
→ Actual: No files matched

![Screen Recording 2020-06-18 at 15 31 09](https://user-images.githubusercontent.com/124952/85079189-07500580-b17b-11ea-85e7-ea4a9c3705dc.gif)

**Steps to reproduce (example 2)**
* Type "lower"
→ As expected, files match containing words like "flower" and "lowers" and "lowering"
* Add an `i`: "loweri" (or add "s" or prepend "f")
→ Expected: Results filter out files with "flower" and "lowers", but retain those with "lowering"
→ Actual: No files matched

![Untitled](https://user-images.githubusercontent.com/124952/85079706-55193d80-b17c-11ea-9686-0d638bdeb155.gif)

**Comment by abnerlee** [comment]
Is it on macOS? Are you searching among a large folder?

**Comment by abnerlee** [comment]
should be fixed in new release
