### ISSUE TITLE
How to center table in CSS theme?

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3622]
Hi,
I am interested in setting the width of table to say 80% but at the same time to keep the whole table centred vertically. My trial below did not work, any thoughts?

`table {
     width: 80%;
    margin: 0 auto;
    word-break: initial;
    border-collapse: collapse;
}`

**Comment by abnerlee** [comment]
```css
width: 80%;
margin: auto !important;
```

**Comment by redoxmatlab** [comment]
Thanks. But, adding this line to any of the default CSS does not work
`table{
      width: 80%;
    margin: auto !important;
}`

The table in typora still aligned to left! Thoughts?

thanks

**Comment by abnerlee** [comment]
Sorry, there seems a small issues for the default CSS, which I added `margin: 0 !important;` on `figure>table`, so

```css
figure > table {
    width: 80%;
    margin: auto !important;
}
```

This should work.


The default `0 !important` seems not needed...

**Comment by redoxmatlab** [comment]
Fantastic! Works like a charm. Thank you.
