### ISSUE TITLE
Bug: abbreviations ending with dot labeled as missing a dot

### ISSUE THREAD

**Issue by DzerardWho** [typora/typora-issues#3623]
When using for example polish dictionary, abbreviations which require to end with a dot are labeled as missing said dot by spell check, even if there is a dot.
![T1gWvmplag](https://user-images.githubusercontent.com/22153463/85199464-1ad0ad00-b2f0-11ea-9a52-a190e730b096.gif)

**Comment by abnerlee** [comment]
duplicate with #3440
