### ISSUE TITLE
Will Typora works with \usepackage in code?

### ISSUE THREAD

**Issue by YuankaiZhu** [typora/typora-issues#3627]
I wonder will Typora works with \usepackage in code block when we input latex so that Typora can do more work for us? Right now, it seems we cannot use packages excluded in build-in packages in Typora.

**Comment by abnerlee** [comment]
Typora does not support `\usepackage`, it is not a LaTeX editor, Typora uses LaTeX only to support Math expressions.

But #100 may be supported in future.
