### ISSUE TITLE
mermaid link text is not behavioring right

### ISSUE THREAD

**Issue by JellyZhang** [typora/typora-issues#3628]
![image](https://user-images.githubusercontent.com/34066678/85220994-be9a8580-b3e2-11ea-9d33-18f539471259.png)
As shown in the pic, the line covers the letter 'd', which he shouldnot.
This happens after i updated my typora(mac) to 0.9.9.33.2, I think some updates causes this.

**Comment by dan-tee** [comment]
I'm having the same issue where the edge label does not get a background color for text protection. The issue occurs across all standard themes. I'm also on typora(mac) to 0.9.9.33.2.

**Comment by abnerlee** [comment]
similar with #3619

Fixed in new release
