### ISSUE TITLE
Issue with words selection using Shift+Left key

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3629]
OS: Win10 Typora: .89

----
Using <kbd>Shift</kbd>+<kbd>Left</kbd>(or <kbd>Right</kbd>) to select words between the inline math and the normal text will cause the caret move to an improper place.
To be more specific, in selection when the caret moves into the inline math from the normal text(i.e. the moment selecting "$") the caret will immediately move to the rear of the string having been selected.

----
To reproduce or locate this bug U can follow:
- writing an inline math formula followed by some normal text
- moving the caret to the end of the line
- pressing  <kbd>Left</kbd> several time to go into the math block with <kbd>Shift</kbd> held down

---
![6a9d13ba-8d24-4eb8-8b63-2d0b55d1057f](https://user-images.githubusercontent.com/46404230/85224280-b26ef200-b3fb-11ea-8c89-8f7e05663a53.gif)

**Comment by peetteerr** [comment]
There are lots of seemingly related issues. For example, having selected some text stretching across the normal text and the inline math and then pressing <kbd>Backspace</kbd> the same kind of problem would occur that the caret will move back abnormally.
![a1d128ed-c6ae-4d82-91fb-6f7a9da35000](https://user-images.githubusercontent.com/46404230/85224965-5f4b6e00-b400-11ea-982d-e74aebc66379.gif)

-----
There is also something a little bit weird that above issue will occur in a different condition depending on <kbd>Ctrl </kbd>+<kbd> Left</kbd>or simply <kbd> Left</kbd> is used to move the caret when holding <kbd>Shift </kbd> down. While this may be just some trivial stuff so forgive me for not going into its detail.

**Comment by abnerlee** [comment]
should be fixed
