### ISSUE TITLE
backticks and ${} linted as error in JavaScript Fenced Code Blocks 

### ISSUE THREAD

**Issue by schulzf** [typora/typora-issues#3630]
For exemple:

```javascript
let greeting = `Hello ${name}, welcome to Mars`;
```
gets linted as error.

![image](https://user-images.githubusercontent.com/56260943/85229048-6746e600-b3df-11ea-8cd7-e5e57a4c4aa4.png)

**Comment by abnerlee** [comment]
It's orange, is not "error".

You could follow http://support.typora.io/Code-Block-Styles/ to customize the syntax highlight styles
