### ISSUE TITLE
Issue with deleting list item using backspace

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3631]
OS: Win10 TyporaVersion: .89

----
Normally, when using `Backspace` to delete a list item(tag) whose level is greater than two, it is going to be
![414d2aad-4811-4225-b047-e191d5f5c67f](https://user-images.githubusercontent.com/46404230/85273595-5e721500-b4b0-11ea-9b9f-1ccd99cd6261.gif)

----
But when followed by an inline math block, the caret will automatically move to the back of the inline math
![9cf36990-9a34-4135-b5ae-64f616d14078](https://user-images.githubusercontent.com/46404230/85273474-3aaecf00-b4b0-11ea-801b-c5dbabd680d1.gif)

**Comment by abnerlee** [comment]
should be fixed
