### ISSUE TITLE
Add an option to use authentic fonts.googleapis.com instead of fonts.loli.net when exporting to HTML

### ISSUE THREAD

**Issue by BirkhoffLee** [typora/typora-issues#3632]
The title says it all. Having the option would be good, at least harmless. Anyhow thanks for the app. Nice work!

**Comment by BirkhoffLee** [comment]
Never mind, it's in the CSS code. :)

**Comment by jamesmurdza** [comment]
Why not change it to a different CDN? Apparently, pages that resources fonts.loli.net are hit with a warning from some antivirus softwares.
