### ISSUE TITLE
image load failed when the file name is chinese and copy&paste directly

### ISSUE THREAD

**Issue by whitoad** [typora/typora-issues#3634]
when i upload an image from computer, it ca not be loaded.

i reinstalled typora. can't be solved.

it just show like this.

![微信图片_20200624205145](https://user-images.githubusercontent.com/22836144/85559706-8a31fe00-b65c-11ea-8b6e-c87fcd379b9b.png)

help me please.

**Comment by abnerlee** [comment]
What's your Typora version?

And try to reopen the file with `File` -> `Reopen with Encode` ?

**Comment by whitoad** [comment]
> What's your Typora version?
> 
> And try to reopen the file with `File` -> `Reopen with Encode` ?

Hi, thank you for your reply.

The version is 0.9.89(beta). I didn't have this problem before, it just suddenly change into like that.all my files have this problem.

But i found maybe because my image file name has some chinese simplified characters. when i deleted these charaters, the image can load sucessfully. 

But the problem still exists, chage all my images' file name is crazy.I tried 'reopen with encode', choose some diffenent encodes——it did not works.

**Comment by whitoad** [comment]
> What's your Typora version?
> 
> And try to reopen the file with `File` -> `Reopen with Encode` ?

hi today i found how this bug happens.

when the image file name is english, all the things go well:

![侧睡](https://user-images.githubusercontent.com/22836144/85992768-ed8aaa00-ba27-11ea-8aef-db87f6eff172.gif)

but when the image file name is chinese, the "image load failed" happens.

![侧睡2](https://user-images.githubusercontent.com/22836144/85992843-0d21d280-ba28-11ea-9924-e55bbb379d1c.gif)

**Comment by abnerlee** [comment]
relates https://github.com/electron/electron/issues/12141

**Comment by abnerlee** [comment]
should be fixed in new release
