### ISSUE TITLE
Typora not working on Docker

### ISSUE THREAD

**Issue by fjandrad** [typora/typora-issues#3636]
First of all, I love typora thanks for the work you have done. I want to extend its use and adding it to a docker image that others will use might help with that.

## Setup Description
I build a docker image of ubuntu 18.04 on top of which I install typora.
### Command for installing typora with dependencies
```
RUN wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add - &&\
 add-apt-repository 'deb https://typora.io/linux ./' &&\
 apt-get update &&\
 apt-get install -y --no-install-recommends \
     libgtk-3-0 \
     libxss1 \
     typora \
     &&\
rm -rf /var/lib/apt/lists/*
```
Installation seems to be fine, but when I try to open it from the built image I get an error message with a core dumped.

## Error message
The error message that I get is
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap (core dumped)
```
I do not understand why typora would need this functionality and also how to make it work with Docker. Please help

**Comment by abnerlee** [comment]
see https://stackoverflow.com/questions/59087200/google-chrome-failed-to-move-to-new-namespace

or https://github.com/jessfraz/dockerfiles/issues/65

You can add "--no-sandbox" as launch arguments for Typora >= 0.9.92
