### ISSUE TITLE
Content loss when Change the path of note !!! 

### ISSUE THREAD

**Issue by xpuoxford** [typora/typora-issues#3638]
I've run into this situation for a few times. In the beginning, I thought I might have forgotten to save the file before closing it. However, there is a window popping out and I paid extra attention to " save the changes". When I start a new note, it was in my main folder. Every time I created a folder and move an existing note into that folder, 50/50 chance the content will disappear! It also happened when I kept editing the moved note, and next time I reopened it, the content disappears.

**Comment by abnerlee** [comment]
What's your OS and typora version?

Did the folder connected with a sync service (like iCloud, etc)?

If it is 50/50 chance, then could you send us a screencast about this? Since we cannot reproduce this.

**Comment by xpuoxford** [comment]
> What's your OS and typora version?
> 
> Did the folder connected with a sync service (like iCloud, etc)?
> 
> If it is 50/50 chance, then could you send us a screencast about this? Since we cannot reproduce this.

Hi ~ it's macOS Mojave 10.14.6; I have observed it closely recently, and I found the problem happens in the following two situations:

(1) use the shortcut to save the md file while tying (for me, I am used to saving frequently by 'command + s'  ). So when I quit the typora window, there is no warning for saving the file anymore. I also used shortcut to quit like 'command + Q'. Then, when I reopen the content lost. but when I use  'command + W' to quit, sometimes the content was still there.

(2) When I reopened one markdown file, there was no content in typora window (looks like a totally new markdown). So I thought my content has already lost (and if I did make any changes to the file now, e.g. trying to retype something and save, the content is permanently lost), however, if I open the file with another editor, say sublime, the content is still there. This happens especially when the file was moved into another folder; and as said before, this happens 50/50. (For example, the first screenshot is 'no-content-in-typora-window'; but the second screenshot shows the content of the same file is there, I can open it with another editor)

Hope my words explain the situation to you. Thanks : )
 
<img width="663" alt="Screenshot 2020-07-01 at 15 30 54" src="https://user-images.githubusercontent.com/44842781/86256338-205faa00-bbb0-11ea-8282-1589dcc04da1.png">

<img width="671" alt="Screenshot 2020-07-01 at 15 31 12" src="https://user-images.githubusercontent.com/44842781/86256232-f908dd00-bbaf-11ea-963e-e7bb037d0573.png">

**Comment by abnerlee** [comment]
@xpuoxford Thanks for the explanation. 

So 

- "(1) use the shortcut to save the md file while tying" this is after you "created a folder and move an existing note into that folder" or nothing related to "change path"?
- What's your settings in
   ![](http://support.typora.io/media/auto-save/general.png) ?
- "Reopen" means double click the file in finder, right?

**Comment by abnerlee** [comment]
If possible, could you send us <hi@typora.io> a screencast about this. This is a critical bug, but we still unable to reproduce it.

**Comment by abnerlee** [comment]
@xpuoxford  any updates?

**Comment by xpuoxford** [comment]
> @xpuoxford any updates?

Hi sorry a little busy recently. I have re-installed Typora. Since then, I found it I re-click one file from Typoral file list, then the content will show up again. I will send you the pic to email asap.

**Comment by abnerlee** [comment]
should be improved in latest version
