### ISSUE TITLE
SwiftUI Code Highlighting in Fenced Code Blocks

### ISSUE THREAD

**Issue by bemental** [typora/typora-issues#3639]
SwiftUI is not currently a supported language for code highlighting in fenced code blocks.

Would love to see SwiftUI added as an option when available.

**Comment by abnerlee** [comment]
Is `SwiftUI` a language? 

You should use `swift` for this.

**Comment by bemental** [comment]
SwiftUI has additional syntax that is not include in the current Swift code syntax highlighting. 

And yes, SwiftUI is a separate language syntax than Swift.
