### ISSUE TITLE
MermaidJS out of date ? 

### ISSUE THREAD

**Issue by petterostergren** [typora/typora-issues#3642]
Hey, 

I have noticed that several mermaid-js graph style (such as flowchart, erDiagram)  isn't working in addition to minor glitches such as using a `<br>` within a "circular node" isn't patch in the typora application. 

Here's an example with the code from mermaid-js live editor in addition to a screen grab from typora (v0.9.89 beta) running `Github` theme 

![image](https://user-images.githubusercontent.com/9515726/85932214-552ae300-b8ca-11ea-8bbc-038aed9f281d.png)

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEJcbiAgIDEoNWNjIGNtcCA9PSAyPGJyPjVkMCBqbmUgNjIzKSAtLT4gMih0ZXh0KSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

**Comment by HandOfGod94** [comment]
Same for me as well. I tried using database node shape. But didn't work.

```mermaid
graph LR;
	A[(Database)]-->B(Application)
```

[MermaidLiveEditor Preview](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG5cdEFbKERhdGFiYXNlKV0tLT5CKEFwcGxpY2F0aW9uKSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

It was failing with error in typora.

```
ERROR: [Mermaid] Parse error on line 2:
graph LR;    A[(Database)]-->B(Appl
---------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'subgraph', 'end', 'TAGEND', '--', '==', 'STR', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'PCT', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'PS'
````

**Comment by abnerlee** [comment]
duplicate with #1661
