### ISSUE TITLE
Support symbolic/hard link files.

### ISSUE THREAD

**Issue by Konfido** [typora/typora-issues#3643]
- Versions: MacOS 10.15.5, Typora 0.9.9.33.2 (4442)
- Issues:
  1. Crash happens when you switch between the original and the hard link files. 
      - File `foo_1.md` is created by the command of  `ln A/foo.md B/foo_1.md`
      - ![load_pic](https://user-images.githubusercontent.com/25447610/85939331-096a4f00-b947-11ea-9d1b-d016c5ce6f2e.gif)

  2. Can't save symbolic link files.
      - I've noticed #969 mentioned it's a fixed issue, but it seems this bug arises again.
      - File `foo_2.md` is created by the command of `ln -s /Users/xxx/test/A/foo.md B/foo_2.md`
      - ![load_pic](https://user-images.githubusercontent.com/25447610/85939522-d1fca200-b948-11ea-87f6-4077096e9f91.gif)

**Comment by abnerlee** [comment]
duplicate with #1881
