### ISSUE TITLE
Very slow to close

### ISSUE THREAD

**Issue by duzhen1996** [typora/typora-issues#3644]
After the software is opened for a period of time, the speed of closing the software is very slow

MacOS 10.15.5
Macbook pro15 Mid 2015

**Comment by abnerlee** [comment]
Did you close window with "untitled" content? 

Usually the `SaveFileDialog` may be slow to show up from any app.

**Comment by duzhen1996** [comment]
Thanks for your reply. The window is not with "untitled" content. The closed file has been saved before closing.
And this phenomenon only appear when I use a newer version. In 0.9.9.16.2, this does not happend.

**Comment by duzhen1996** [comment]
I love 0.9.9.16.2

**Comment by abnerlee** [comment]
Is this same with #3496?

**Comment by duzhen1996** [comment]
Same phenomenon, but my file system is APFS

**Comment by duzhen1996** [comment]
I suggest the reason is low CPU speed. I replace old silicone grease and this phenomenon disappear. What a surprise.
