### ISSUE TITLE
MermaidJS autoNumber not turned on

### ISSUE THREAD

**Issue by damageboy** [typora/typora-issues#3645]
Hi,
It would be wonderful if we could have mermaidjs auto numbering turned on by default:

https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers

It is not entirely clear to me if the issue is the version of mermaidjs used, or the way it is spun up.

At any rate, reference for sample of mermaid + sequence + autoNumber:
https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICBhdXRvTnVtYmVyXG5cdEFsaWNlLT4-K0pvaG46IEhlbGxvIEpvaG4sIGhvdyBhcmUgeW91P1xuXHRBbGljZS0-PitKb2huOiBKb2huLCBjYW4geW91IGhlYXIgbWU_XG5cdEpvaG4tLT4-LUFsaWNlOiBIaSBBbGljZSwgSSBjYW4gaGVhciB5b3UhXG5cdEpvaG4tLT4-LUFsaWNlOiBJIGZlZWwgZ3JlYXQhXG5cdFx0XHRcdFx0IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0

**Comment by abnerlee** [comment]
A part of #374
