### ISSUE TITLE
"image load failed" when the image file name is chinese, and copy&paste directly

### ISSUE THREAD

**Issue by whitoad** [typora/typora-issues#3646]
It might be a bug.

The version is 0.9.89.

That's how it happens:

when the image file name is english, you use "ctrl+C"&"ctrl+V",and all the things go well:

![侧睡](https://user-images.githubusercontent.com/22836144/85992768-ed8aaa00-ba27-11ea-8aef-db87f6eff172.gif)

but when the image file name is chinese, and you want to use "ctrl+C"&"ctrl+V" to paste the picture,the "image load failed" happens.

![侧睡2](https://user-images.githubusercontent.com/22836144/85992843-0d21d280-ba28-11ea-9924-e55bbb379d1c.gif)

use drag or other way to upload images has no this problem.

![侧睡3](https://user-images.githubusercontent.com/22836144/85994525-7efb1b80-ba2a-11ea-96b7-9e40544374f7.gif)

**Comment by abnerlee** [comment]
duplicate with #3634 ?
