### ISSUE TITLE
Linux version numbers and changelog

### ISSUE THREAD

**Issue by syco** [typora/typora-issues#3647]
Hi,
related to [Provide other installation packages #1457](https://github.com/typora/typora-issues/issues/1457),
I'm a little confused with the version numbers and the change log in [Change Log + History Builds](https://typora.io/dev_release.html)

It appears the linux version doesn't follow the same release cycle of the other versions.
So I was wondering, if you could provide a change log for linux it would be helpful in order to keep the flatpak updated.

Also, are you interested in publishing the app in flathub as 'io.typora.flatpak'?
If you are not interested, but are ok with me doing it please let me know.
The guys over in flathub are very helpful and I can easily push it and keep it updated (provided I can monitor a changelog to know when a new tarball is released).

Thanks

**Comment by abnerlee** [comment]
change log for Linux / Windows is at https://typora.io/windows/dev_release.html

We would unify version numbers on macOS and other OS after v1.0.0

I don't have the manhour to maintain flatpak for now, it is OK if you want help.

> The guys over in flathub are very helpful and I can easily push it and keep it updated (provided I can monitor a changelog to know when a new tarball is released).

So what I should do to keep this process running automatically?

**Comment by syco** [comment]
Thanks, for the info..

The process to publish on flathub is all managed through github.
You'd need to fork a specific branch from flathub, add your content, and then open a pull request.
When they review it and and confirm it's working they add it to the autobuild process.
Any subsequent push to that repo triggers a build and is then published.
It's all outlined in this article [https://github.com/flathub/flathub/wiki/App-Submission](https://github.com/flathub/flathub/wiki/App-Submission)

I've already published an app on flathub and I used the same template for typora, so it should be accepted fairly easily.
You can see all required files at [https://github.com/syco/io.typora.flatpak](https://github.com/syco/io.typora.flatpak)

The only think I can see as a possible problem is that the tar.gz file you publish doesn't contain the version number, and when it changes the build process is still valid, but the sha256 is not.

One neat thing is that when flathub publish a new app they don't publish it from your personal account, they instead open a flathub/typora branch, copy all files there, and then they give you commit privileges to it.

So because this would not reside in my github, I could push it for you and follow updates until you have time to reclaim the branch from flathub.

**Comment by abnerlee** [comment]
I see, we can include the version number in tar.gz from next version up.

**Comment by abnerlee** [comment]
Now https://typora.io/linux/Typora-linux-x64-0.9.90.tar.gz is avaible, the version number is now attached.

**Comment by syco** [comment]
Hi,

All tar.gz files appear to be corrupted
![image](https://user-images.githubusercontent.com/54575/87285319-4a3d9880-c4ef-11ea-8a5b-9a6c0a92f64d.png)

I tried with the old one without the version number and with version numbers 90, 91, and 92. I can't untar any of them.

**Comment by abnerlee** [comment]
I re-update the tar file, which should be working now. 

Please use https://typora.io/linux/Typora-linux-x64-0.9.92.tar.gz, I removed 90 since the are old and its tar is not workable anyway.
