### ISSUE TITLE
Autohotkey doesn't work on Windows

### ISSUE THREAD

**Issue by licht1stein** [typora/typora-issues#3648]
Typora seems to be completely blocking AutoHotKey on Windows 10.

**Comment by abnerlee** [comment]
Could you provide more details?

**Comment by Guillaume-Garrigos** [comment]
I just happened to have installed AutoHotkey yesterday and it works as intended with Typora. 

More details about my config:
Windows 10 Pro, version 1903 (10/2019)
Typora v 0.9.65
