### ISSUE TITLE
Mouse wheel doesn't work after using typora for a while.

### ISSUE THREAD

**Issue by HelperInCa** [typora/typora-issues#3650]
MacBook Pro (16-inch, 2019) v10.15.5
Typora v0.9.9.33.2

I can not scroll with the Mouse wheel. But the scroll bar on the right side still works. And the mouse wheel works well after restarting the Typora.

**Comment by abnerlee** [comment]
duplicate with #3400?

**Comment by HelperInCa** [comment]
Not really. Logitech Mouse.
