### ISSUE TITLE
[Feature Request] Code Fences syntax highlighting language default to last selected language. 

### ISSUE THREAD

**Issue by ohnohno** [typora/typora-issues#3651]
Currently, I specify the syntax highlighting for each individual code fence, which breaks up my workflow somewhat. I would find it useful if Typora remembered which language I used last. 

Perhaps the default could be global or document specific at change of user setting. This would be especially good for my use case, since I'm flitting between one document where all the code fences are Python,  and another where they're all SQL.

**Comment by abnerlee** [comment]
We don't have plans for this.

Maybe #290 would be a better choice
