### ISSUE TITLE
[Italian Keyboard Issue] [Suggestion] Customizable shortcut please!

### ISSUE THREAD

**Issue by PsykeDady** [typora/typora-issues#3654]
italian keyboard doesn't have the ` key, so i can't use shortcut for code format. 
i think that should be better to have a fully customizable shortcut map, so every user can define own shortcut based on own keyboard setting.

sorry for bad english ...and thanks for this wonderful software!

**Comment by abnerlee** [comment]
see http://support.typora.io/Shortcut-Keys/
