### ISSUE TITLE
Export md to HTML self contained images 

### ISSUE THREAD

**Issue by Ken0sis** [typora/typora-issues#3656]
This is to re-open issue #926, that was closed.  The issue is about how to preserve images in a SINGLE html file when exporting markdown file, so it is not the same as issue #88, which is about embedding images into markdown in general.  

The current method of embedding images into markdown by pointing to images stored in a separate folder is NOT the issue.  The problem is users want to have a SINGLE page export of the markdown text along with images.  The single file could be a self contained HTML or some other format, but it should be universally readable and preserves the styles generated from Typora.  This would exclude options like exporting to Word document format.  

This highly desired to make it easier to manage individual documents, because people want to manage documents not assets of the documents.

**Comment by Shen897** [comment]
I was about to open new issue regard this. 

Exporting self-contained HTML is a good way to have a portable self-contained file on all devices without the need to fetch images from remote server or another folder, also it's good when you are in an environment without internet or want to send a research/document/notes to a friend in a single self-contained HTML file (Not everyone knows the awesomeness of  Markdown or uses it).

### It's not like #926 or #88
- We don't need to alter/hack the standard of Typora's Markdown or add non-Markdown ways of doing things
- It's work only when export Markdown  into HTML and it's relativity easy and supported by HTML and any software that render HTML as far as I know.

### What we need:

Add an option to embed images inside the exported HTML upon exporting it.  An option to tick, so we don't alter the standard way of normal linking and only when the user prefer to embed the images.  
From what I know we can achieve this by embedding images within the HTML file using base64 encoding

**Comment by henshin** [comment]
This would be great, it would allow people to share specific notes with others by providing a self-contained HTML pages. 
Typora already supports the embedded images, but doesn't provide a way of doing this automatically.
For example, you can use the following markdown in Typora to show an embedded image:
```
![test image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```
However, from an export standpoint, this could be a bit tricky to implement. Typora would have to:
- read the image provided in the path
- convert the binary data to Base64
- identify the image type (PNG, JPEG, GIF, etc)
- replace the path with `data:image/(type),base64,(imagedata)`

Or maybe there are already libraries which handle this. Not sure.

**Comment by phcournede** [comment]
Hi,

It would indeed be great to have the capacity to export a self-contained HTML document (as it actually works for pdf).

The drag and drop utility is really nice, but it's a shame not to be able to export simply what we see locally.

**Comment by aloboa** [comment]
Is this feature going to be implemented?

**Comment by mikedeskevich** [comment]
+1 on this!

I would love a way to send a single HTML file to a colleague with styles and images all embedded.  I typically use PDF for this, but sometimes I don't want the page breaks.

**Comment by NorHei** [comment]
Why not learn from Java and simply put the whole document into a simple .zip container as with .jar files. all Images kept in original size and its perfectly portable. You can even add the style, so it looks exact like its designed. 
And with compression its even smaller, inline images tend to be really big. 
 
@589421 you can turn off the page breaks in Settings if i remember correct.

**Comment by aloboa** [comment]
You can always do that if you want, but I prefer a self-contained html file. For example, to upload it to a web site.
RStudio does this via pandoc for computing notebooks since years ago and it is very conveniently used by thousands of people.

**Comment by mikedeskevich** [comment]
Yes, for me a zipped folder with all of the artifacts is totally sufficient.  But it's not something I can easily share with a colleague or a customer.  A simple email with "what do you think of this draft?" and an html attachment for them to read is ideal.  I'm looking for ease of reading and sharing.

**Comment by gholm** [comment]
> @abnerlee

Alternatively, implementing a quick solution to upload the images on imgur (or similar) instead of local, like [Flameshot](https://github.com/flameshot-org/flameshot) does, could also work in some cases. I would be happy with that.

**Comment by abnerlee** [comment]
Currently you should be able to add `Run command` option to run custom script to upload or convert images into base64

**Comment by aloboa** [comment]
Why is exporting an md document from Typora as standalone html not possible if it is so simple
with RStudio? It looks just as a matter of using the appropriate pandoc optiions...
https://www.dropbox.com/s/l6afxnwqfa7cpjh/StandaloneHTML_RStudio.jpeg?dl=0

**Comment by Ken0sis** [comment]
I know this is currently a low priority issue for abnerlee, but it's really cumbersome to have a backup of documents with images (or other assets) in Typora. 

Export to PDF:  You can't easily edit the pdf afterward, and you lost access to the original image.
Creating zip folder: This doesn't produce a standalone self-contained file, and it makes file management harder.

I understand this a problem with markdown in general, but it does make it harder to securely backup markdown notes (that have embedded images) and "take them with you".  There are many competing markdown editors out there, and if Typora has a more graceful way to back up notes with assets, then it would add to the list of killer, differentiating features that Typora already has.

**Comment by gholm** [comment]
In my case, there isn't much of a difference between running a custom script to upload or convert images into base64 or manually uploading images to an image hosting service and then embedding them into the HTML document.

I wonder if the approach taken by [SingleFileZ]([SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ)) can be of any use for this. Basically, exporting an archive with everything included.

**Comment by abnerlee** [comment]
put into #88

**Comment by aloboa** [comment]
Completed? Is it possible to export an md file to an HTML file with self-contained images? Since what version? How?

**Comment by aloboa** [comment]
> Yes, for me a zipped folder with all of the artifacts is totally sufficient. But it's not something I can easily share with a colleague or a customer. A simple email with "what do you think of this draft?" and an html attachment for them to read is ideal. I'm looking for ease of reading and sharing.
> 
> Edit: I did do this as a work-around for now. It requires yaml frontmatter for pandoc to be happy with the title. But for my purposes it's sufficient. It would be nice to have this as a built-in type so that it would be easier to select the css for the theme.
> 

@mikedeskevich: Thanks. I've been able to apply your workaround. It took me a while because I did not know I had to create the new option from the Pandoc template. The only important thing I miss is that I cannot generate a lateral TOC. I can add the --toc option to the extra Arguments, but not toc_float. Also, adding this at the beginning of the md file has no effect:
```
output: 
  html_document: 
    output:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
      theme: united
      highlight: tango
```
As a minor point, it seems --self-contained is deprecated and that --embed-resources --standalone must be used now.
I cannot believe these options cannot be added within the regular Typora, though.

**Comment by arcqiufeng** [comment]
I changed to MPE plugin of vscode when I want to export md to html and embed image files to html.

It will be great if typora can support the feature itself.

My export yaml. I got it in: https://shd101wyy.github.io/markdown-preview-enhanced/#/html

``` yaml
---
html:
  embed_local_images: true
  embed_svg: true
  offline: false
  toc: true
print_background: false
export_on_save:
  html: true
---
```

**Comment by baberle** [comment]
I was able to create a script that seems to do the trick.

![image](https://github.com/typora/typora-issues/assets/77088315/528c2252-9208-4fcd-8b8a-3d7d59c1fe56)

```python
import base64
import re
import os

def encode_images_to_base64(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as md_file:
        html_content = md_file.read()

    # Find all image tags in the markdown content
    img_pattern = r'<img[^>]*\ssrc="([^"]+)"[^>]*>'
    image_tags = re.findall(img_pattern, html_content)

    for image_path in image_tags:
        # Check if the image path is relative or absolute
        if not os.path.isabs(image_path):
            image_path = os.path.join(os.path.dirname(input_file), image_path)

        if os.path.exists(image_path):
            with open(image_path, 'rb') as image_file:
                # Encode the image content to base64
                image_base64 = base64.b64encode(image_file.read()).decode('utf-8')

                # Replace the image path with the base64 encoded content in the markdown content
                html_content = html_content.replace(image_path, f'data:image/png;base64,{image_base64}')

    # Write the updated markdown content to the output file
    with open(output_file, 'w', encoding='utf-8') as html_file:
        html_file.write(html_content)

if __name__ == "__main__":
    import sys
    input_md_file = sys.argv[1]
    output_html_file = sys.argv[2]

    encode_images_to_base64(input_md_file, output_html_file)
```

**Comment by pfrap** [comment]
Hi @baberle , not able to make it work, can you help me with more detail?
Thank you

I write this command:
python img_to_base64.py "${outhputPath}" "${outputPath}"

and get this:

Command failed: python img_to_base64.py "${outhputPath}" "C:\Users\pietr\Documents\STADATA\GitHub\cv\README.html"
Traceback (most recent call last):
  File "C:\Users\pietr\Documents\STADATA\GitHub\cv\img_to_base64.py", line 35, in <module>
    encode_images_to_base64(input_md_file, output_html_file)
  File "C:\Users\pietr\Documents\STADATA\GitHub\cv\img_to_base64.py", line 6, in encode_images_to_base64
    with open(input_file, 'r', encoding='utf-8') as md_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '${outhputPath}'

**Comment by arcqiufeng** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '${outhputPath}'

Because you spelled the word wrong. The correct spelling is: `outputPath`, not `outhputPath`

**Comment by arcqiufeng** [comment]
BTW, the Python solution is truly remarkable and secure. Here's another solution you might find helpful:
https://meta.appinn.net/t/topic/25788

**Comment by pfrap** [comment]
Thanks for feedback @arcqiufeng.
Now it gives me success message but images are still not embedded in html.
![image](https://github.com/typora/typora-issues/assets/124562706/09c2b182-e3ff-416f-b09e-7e3b6b8c3084)

I tested part of the code in notebook and the images get actually embedded while writing html file, don't know why it is not working as a run command through typora.

I've got python 3.12 installed.
Anything I should check further?

**Comment by pfrap** [comment]
UPDATE:
Actually made it work changing pathstyle.

``` html
from this:
<img src="./graphics/script_etl_grey.png" alt="Immagine html">

to this:
<img src="C:\Users\pietr\Documents\STADATA\GitHub\cv\graphics\script_etl_grey.png" alt="Immagine html">
```
Thanks a lot, wonderful script!

**Comment by aloboa** [comment]
@pfrap Do not understand. Where are you defining img src?
Do not see that in the script by baberle

**Comment by pfrap** [comment]
I'll make a recap of what worked for me.

Setup:
* Windows user
* Writing markdown in VS Code for Github account
* Using Typora for printing and exporting html with custom themes

In VS Code Markdown with relative path I usually do this to insert images:

``` md
Markdown sintax with relative path:
![Image](./relative_path/image.png)

or

Html tag inside of Markdown document:
<img src="./relative_path/image.png" alt="Image">

They behave exactly the same.
```
VS Code uses **forward slash "/"** for relative path in order to work when published in Github, and **that was the issue to me**: the script is not building the image path correctly using that path format.

In order to convert to html correctly and keeping the usual way of doing markdown in VS Code (Github) I added these lines to the script.

``` python
def encode_images_to_base64(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as md_file:
        html_content = md_file.read()

    img_pattern = r'<img[^>]*\ssrc="([^"]+)"[^>]*>'
    image_tags = re.findall(img_pattern, html_content)

    for image_path in image_tags:

        """New lines from here"""
        image_path_temp=image_path #Added line: separate markdown relative path from new image path
        image_path=image_path.replace("./","\\") #Added line: replace forward slash with backslash
        image_path=image_path.replace("/","\\") #Added line: replace forward slash with backslash
        prefix=r"C:\Users\pietr\Documents\STADATA\GitHub\cv"#Added line: insert your custom image path
        image_path=prefix+image_path #Added line: build image complete path
         """New lines stop here"""

        if not os.path.isabs(image_path):
            image_path = os.path.join(os.path.dirname(input_file), image_path)
        if os.path.exists(image_path):
            with open(image_path, 'rb') as image_file:
                
                image_base64 = base64.b64encode(image_file.read()).decode('utf-8')

                """Modified lines here below"""
                html_content = html_content.replace(image_path_temp, f'data:image/png;base64,{image_base64}') #Use: image_path_temp

    with open(output_file, 'w', encoding='utf-8') as html_file:
        html_file.write(html_content)
``` 

Check comments on script above to see what I modified for my personal situation.
Another solution is to use absolute (raw) path, but then as a downside the markdown file is not rendering on GitHub.
Hope it's clear somehow.

**Comment by aputla** [comment]
I used a combination of Typora and Chrome (with extension) to generate HTML with inline images (base64 encoded). Here are the steps:
1. Use Typora to export the markdown file to HTML.
2. Open the HTML file in Chrome.
3. Install this extension on Chrome: **SingleFile** (Once installed, update extension settings to allow reading local files).
4. Use the extension, to convert the page to a single file.

**Comment by aloboa** [comment]
@aputla Thanks, this is a workable solution. But, considering such a solution exists, I cannot understand why this feature is not directly implemented in Typora.
