### ISSUE TITLE
Image with html tag <img>  exported to pdf and html  are not the same what looks like in typora

### ISSUE THREAD

**Issue by nigangkaka** [typora/typora-issues#3658]
I  need to embed some images which are very large. So i have to use html tag <img> to resize it to fit the document.

But after exporting the .md to pdf or html , the text below the images moves to the right of the images.

### It looks  normal in Typora:
![OK](https://user-images.githubusercontent.com/13623477/86368225-867f2680-bcaf-11ea-8432-a310c02d0141.png)

### It looks werid in exported pdf:
![fail](https://user-images.githubusercontent.com/13623477/86368236-897a1700-bcaf-11ea-9c8d-188cfd719cee.png)

The markdown code ：

```markdown
Text above the  image

<img src="image/image-20200630151947935.png" alt="image-20200630151947935"  align="left" height="500" style="zoom:95%;" />



Text below the image
```

Typora version: 0.9.89
Host : Windows 10 home edition

**Comment by abnerlee** [comment]
should be fixed in new release
