### ISSUE TITLE
Math blocks cause gaps and become smaller in exported PDF

### ISSUE THREAD

**Issue by thepavand** [typora/typora-issues#3662]
I use typora to write a lot of equations and when exported to PDF, some of the equations look quite small, and some others leave large spaces above them. It looks quite ugly. I am attaching a screenshote.

<img width="910" alt="Screenshot 2020-07-05 at 2 21 34 AM" src="https://user-images.githubusercontent.com/11594958/86520820-42825200-be66-11ea-89e9-991ce13770e5.png">

Attaching pdf.
[Goldenfeld.pdf](https://github.com/typora/typora-issues/files/4873954/Goldenfeld.pdf)

**Comment by samtalki** [comment]
any resolution on this or thoughts on potential contributions I could make to fix this? essentially makes typora completely unusable IMO

**Comment by abnerlee** [comment]
relates #3388

**Comment by abnerlee** [comment]
should be fixed
