### ISSUE TITLE
The second "*" in "* text `code*` *" cannot be escaped

### ISSUE THREAD

**Issue by CCComma** [typora/typora-issues#3663]
**environment:**
- os: win10
- version: 0.9.89(beta)

**problem:**
The second "\*" in "\* text \`code*\` \*" will be paired with the first "\*".
![image](https://user-images.githubusercontent.com/35870347/86526230-ecdc9280-bec3-11ea-9d1f-5b9516a1ec21.png)
->
![image](https://user-images.githubusercontent.com/35870347/86526006-f9132080-bec0-11ea-90d4-bad50e5425a3.png)

**Comment by abnerlee** [comment]
should be fixed
