### ISSUE TITLE
Can't search rightly in Open Quickly?

### ISSUE THREAD

**Issue by vactiger** [typora/typora-issues#3665]
I have a file called `CSS.md`. 

If I type "c", `CSS.md` will show in File Results.
![image](https://user-images.githubusercontent.com/49655153/86645872-5d44fa00-c011-11ea-8228-2ec178727d1d.png)

But if I type "cs" or "css" or "CSS.md", I can't see it.
![image](https://user-images.githubusercontent.com/49655153/86644799-6e413b80-c010-11ea-8d8b-41719e0b17b7.png)

My OS is Windows 10 version 1909, Typora version is 0.9.89.

This is normal? Thank you.

**Comment by abnerlee** [comment]
relates #3620

**Comment by abnerlee** [comment]
duplicate with #3620
