### ISSUE TITLE
No printer dialogue

### ISSUE THREAD

**Issue by Ant-on-Hu** [typora/typora-issues#3666]
I want to open the file>printer... - dialogue to select the right printer, there is no dialogue, but one of my printers start to print immediately. This is not the right behaviour I think. There should be a printer-dialogue to select the wanted printer and maby printoptions, like doublesited print, ...

**Comment by GaiLiu** [comment]
Me2. The printer dialogue do not show up either in Win 7 or Ubuntu 18 LTS. But it worked fine before the update to the latest edition 0.9.89

**Comment by abnerlee** [comment]
duplicate with #3549
