### ISSUE TITLE
Saving not defaulting to .md

### ISSUE THREAD

**Issue by LordFlashmeow** [typora/typora-issues#367]
Version 0.9.21
Platform: Win 10 Pro x64

Currently the `Save as type` option in the save menu has no option for Markdown (`.md`), so I have to type it in every time I make a new file, otherwise it saves without an extension and I have to rename it manually. 

It would be great if that could get fixed, for convenience's sake.
![problem](https://cloud.githubusercontent.com/assets/18580297/19585228/8fb5da8e-96ff-11e6-99c2-ef1d45382dec.jpg)

**Comment by abnerlee** [comment]
should be fixed in new release
