### ISSUE TITLE
Unable to modify font size(Too small) in macOS Catalina 10.15.5

### ISSUE THREAD

**Issue by gusye1234** [typora/typora-issues#3670]
My system is macOS Catalina 10.15.5. And my typora's version is 0.9.9.33.2, as below: 
<img width="289" alt="Screen Shot 2020-07-08 at 11 20 24" src="https://user-images.githubusercontent.com/34829253/86871570-1a684c80-c10d-11ea-841e-bc8828bdb234.png">
My problem is, it seems that all fonts are much smaller than ever before.
If I use the **Auto** option in **Font Size** preference, it looks like:
<img width="1440" alt="Screen Shot 2020-07-08 at 11 19 24" src="https://user-images.githubusercontent.com/34829253/86871806-8fd41d00-c10d-11ea-85ed-85d95bd599b8.png">
If I change the font size to maximum(24 px) in **Font Size** preference, it looks like:
<img width="1440" alt="Screen Shot 2020-07-08 at 11 19 15" src="https://user-images.githubusercontent.com/34829253/86871871-aed2af00-c10d-11ea-8134-dbf7b0931dcb.png">
I have tried to reinstall typora, or deleted all the custom themes, didnt work.

**Comment by abnerlee** [comment]
did you "zoomed" Typora's interface?

**Comment by gusye1234** [comment]
Well, I have tried to "re-zoom", but it still looks small.
I believed that's my problem since I downloaded the previous version, and didn't get any better.
I'm very curious how this could happen, did I unexpectedly set anything?

**Comment by abnerlee** [comment]
Could you confirm if it is in "Actual Size" under `View` menu?
