### ISSUE TITLE
Windows 10 updated to 1909 and now Typora is blank

### ISSUE THREAD

**Issue by Asimov500** [typora/typora-issues#3671]
I use Typora on my Lenovo T520 laptop. After the windows 10 update Typora opens, but is completely blank.
Even if I double click on previously working md files the window opens blank.

The typora logo is in the top lefthand of the screen, but there is no menu and I cannot see anything.

I have previously been using typora for months without problems.

**Comment by Asimov500** [comment]
I have two graphics cards in my laptop. So I forced the program to use integrated graphics and now it works.
If it uses my nvidia card it comes up blank. This was fine until I updated windows.

At least I can use Typora again now. I was worried because I have started using it as my main note taking program.

**Comment by abnerlee** [comment]
relates #3582

We just updated electron version, which may fix this.

**Comment by Asimov500** [comment]
How do I get hold of the latest version. When I had the problem I uninstalled it and downloaded the latest version off the page, but I had the same problem. I use Typora to write all my scripts now, because it is really nice on the eye for reading, and I can still read in notepad if for some reason Typora failed if you know what I mean.

**Comment by abnerlee** [comment]
@Asimov500 you mean you are already on 0.9.90?
