### ISSUE TITLE
image load failed when upload file to cloud

### ISSUE THREAD

**Issue by jwbecalm** [typora/typora-issues#3675]
typora version: 版本0.9.9.33.2 (4442)

image upload to GitHub is successful but after upload, the image can not preview in the editor, and it hints "image load failed"

**Comment by jwbecalm** [comment]
And I try to "when I insert a picture, copy the picture to a ./${filename}.assets,  and use the relative path, 
when I paste the picture and choose to upload all local pictures,  after upload successfully, the picture in the editor is gone.

**Comment by jwbecalm** [comment]
I can find the picture  in the directory ./${filename}.assets

**Comment by abnerlee** [comment]
Can you download the image from the url after upload using wget or other tools?

**Comment by jwbecalm** [comment]
I can find the file in the GitHub repo:
https://github.com/jwbecalm/pic_for_write/tree/master/img

but when I copy the whole link to a web browser, it hints 404: Not Found
![image-20200709184442618](https://raw.githubusercontent.com/jwbecalm/pic_for_write_master/img/image-20200709184442618.png)

**Comment by jwbecalm** [comment]
is it my setting for PicoGo wrong?

**Comment by jwbecalm** [comment]
sorry click close, please continue to help me

**Comment by jwbecalm** [comment]
it seems OK now, I try to delete all text in typora, and try again, it works now.
a picture can upload to the cloud successful and can show in Typora normal, 
and also when I copy the whole link to the web, it can see the image:
https://raw.githubusercontent.com/jwbecalm/pic_for_write/master/img/image-20200710075905193.png

I know the issue, I configure wrong for the domain, it should be:
https://raw.githubusercontent.com/jwbecalm/pic_for_write/master

**Comment by jwbecalm** [comment]
now, it closed..thank u for bother you

**Comment by jwbecalm** [comment]
now the img can show in the GitHub:
https://raw.githubusercontent.com/jwbecalm/pic_for_write/master/img/image-20200710162554586.png

but in the typora, after uploading to GitHub, there's no picture showing in the editor
![image](https://user-images.githubusercontent.com/28593268/87211242-26415200-c34b-11ea-8965-8ab8b06aac77.png)

and I go to the relative dir in my computer,  the img is there in the ./${filename}.assets

**Comment by abnerlee** [comment]
I can see the image using `![](https://raw.githubusercontent.com/jwbecalm/pic_for_write/master/img/image-20200710162554586.png)` in my test.

Did you wait sometime for Typora to load it?

Did you check if you have proxy set, or Typora is able to load the image without any network issues.

**Comment by jwbecalm** [comment]
I mean when the img is in local, it's oK for typora as follows
![image](https://user-images.githubusercontent.com/28593268/87216331-5ef42200-c371-11ea-8baf-9827ed67f348.png)

but after I click format ---image-- upload all image, typora hints upload successfully, but int the typora edtor, the image is gone as follows:
![image](https://user-images.githubusercontent.com/28593268/87216368-a4b0ea80-c371-11ea-902e-a5870e727b95.png)

at this time, I also can see the image in github:
https://raw.githubusercontent.com/jwbecalm/pic_for_write/master/img/image-20200711082907928.png

**Comment by mightyjoe781** [comment]
I m facing the same problem as well files uploaded as assets render properly on local, but same files when uploaded on github show errors.

**Comment by mightyjoe781** [comment]
Ok got it error was  that Typora can load relative path names even though they have spaces or not but this doesn't work on github

**Comment by abnerlee** [comment]
> Ok got it error was that Typora can load relative path names even though they have spaces or not but this doesn't work on github

I see, it is #1520

**Comment by jwbecalm** [comment]
please tell me how to solve it?  I can see the image from github url, what you mean spaces?
I have no spaces in my local path

**Comment by mightyjoe781** [comment]
By spaces i meant the folder with name "Abner Lee" -This is not detected by GIthub Repo but Typora Detects it
Advice- Use underscore format
specify path with forward slash " /" (See URL Above) rather than using windows default backward slash "\"

**Comment by jwbecalm** [comment]
it's confusing, my relative dir have no space, and I also specify path with  /, 
for example, typora hint "image load failed". you can see below url have no spaces, no / 
![image-20200723135634361](https://raw.githubusercontent.com/jwbecalm/pic_for_write/master/img/image-20200723135634361.png)

**Comment by mightyjoe781** [comment]
Can u please provide more information with little more details. Like what u trying to do.
In the meantime check this small repo out it helped me a lot.
https://github.com/mightyjoe781/relative-image-url.

**Comment by abnerlee** [comment]
I can load "![image-20200723135634361](https://raw.githubusercontent.com/jwbecalm/pic_for_write/master/img/image-20200723135634361.png)" in my test, can you access the image without any proxy?

**Comment by mightyjoe781** [comment]
Yes image is visible without any proxy in my case!

**Comment by abnerlee** [comment]
Please try open "Sources" tabs in DevTools (which you can open from "Inspect Element" in context menu after you enable debug mode in `help` menu), and see if the image is loaded success or not, and see if its url is correct or not.

Or, you can open "Network" tags in DevTools first, then input images in Typora, and see the error in console or network tab
