### ISSUE TITLE
Inline latex math does not get rendered in Linux version, but works on windows

### ISSUE THREAD

**Issue by benelot** [typora/typora-issues#3676]
When I write a simple inline latex math (i.e. something like $e = m c^2$, it does not resolve it but stays in its unrendered version. Math segments work just fine.

So again:

This does not work: $e = m c^2$
This does not work $$e=m c^2$$
This does work:
$$
\begin{align}
e &= m c ^2\\\\
\text{or not} e &= m c^2\\\\
\end{align}
$$

In the windows version, all of this works.

Just checked if I have the newest typora version, and it says I do (typora is already the newest version (0.9.89-1).

**Comment by abnerlee** [comment]
#3242

**Comment by benelot** [comment]
Oh sorry, I searched for the issue but weirdly did not find it

**Comment by benelot** [comment]
Btw, it works in Windows10 in my case, but not in Linux, that is different from the others.

**Comment by benelot** [comment]
@abnerlee Which one is the open issue that I am a duplicate to? I only found closed issues. Here it does not show up if I am correct:https://github.com/typora/typora-issues/issues?q=is%3Aissue+is%3Aopen+inline+math because this is a different thing:https://github.com/typora/typora-issues/issues/3580. Maybe the open issue needs a better name to not cause any duplicatesin the future.

**Comment by abnerlee** [comment]
It's not a open issue.

see

#3174
#2508
#1507
#1915
#1738
#1510
#1506
#1497

**Comment by benelot** [comment]
> please check if it is enabled in preferences panel.
#3174

**Comment by michaelaye** [comment]
This is a correct and non-duplicate issue:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/69774/94983419-e9c36380-04ff-11eb-81e1-189ec8e5197e.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/69774/94983448-1a0b0200-0500-11eb-9e73-d1999cdc483b.png">


Version 0.9.96 (beta) on Kubuntu 20.04
