### ISSUE TITLE
Size issue with math block containing \tag when exporting to PDF

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [typora/typora-issues#3677]
Hi,

It seems there is a bug with the PDF export : mathblocks are not displayed with the same font size whether they contain a tag or no. Here by "tag" I mean the Latex macro `\tag{foo}` which allows to give custom names to equations, usually displayed as `(foo)`.

When a math block contains a tag, the font for the block is way smaller after the export (within Typora they seem to have the same size). Below is a minimal .md example, and I attach the corresponding .pdf: [github.pdf](https://github.com/typora/typora-issues/files/4898000/github.pdf)

```
with tag
$$
e^x \tag{foo}
$$
without tag
$$
e^x
$$
```

The bug happens independently of the Theme I am using.

Config:
Typora 0.9.65
Windows 10

**Comment by abnerlee** [comment]
seems duplicate with #3662
