### ISSUE TITLE
support pasting Rich Text

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#368]
Typora has a `Paste as Plain Text` command, which implies that the normal paste command pastes Rich Text. It does in fact work that way when copy-n-pasting from one Typora document to another. But if I copy-n-paste from TextEdit or other editors that supports Rich Text, only plain text makes it into Typora. 

It works in the other direction: I can copy out of Typora and paste the Rich Text into TextEdit and most other editors. In other words Typora has halfway support for Rich Text. Rich Text is a first class clipboard data type on both macOS and Windows, so I think it should be expected that Typora, which is essentially a Markdown-based rich text editor, support it fully, at least as much as its flavor of Markdown supports.

**Comment by abnerlee** [comment]
Most styles from rich text is supported when paste from clipboard now.
