### ISSUE TITLE
Syntax highlighting error after indented code block

### ISSUE THREAD

**Issue by tobx** [typora/typora-issues#3681]
Hi,

I am currently using Typora 0.9.9.34 (4498) on macOS Catalina 10.15.5.

In _Source Mode_ the syntax highlighting breaks after a code block in a list.

See the following minimal example: 

````markdown
1. List

   ```
   code
   ```

# Heading
````

Here in _Source Mode_ `# Heading`is not correctly formatted.

**Comment by abnerlee** [comment]
duplictae with #3541
