### ISSUE TITLE
Failed to load resource：net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by hahaha28** [typora/typora-issues#3682]
Windows10，when i open typora, the console show 
`Failed to load resource: net::ERR_FILE_NOT_FOUND`
`typora://userData\themes\base.user.css:1`
and some theme style can't display correctly.
> i switch to Administrator account has the same problem, so this is no a permission problem

**Comment by hahaha28** [comment]
Typora 0.9.89
win10 professional edition 18363

**Comment by abnerlee** [comment]
This does not affect
