### ISSUE TITLE
Error while Installing Typora

### ISSUE THREAD

**Issue by paolopan83** [typora/typora-issues#3685]
This error message was displayed, anyway, after a few seconds, the install process goes on.

Happens on both 32 and 64 bit version for Windows

---------------------------
Error
---------------------------
ShellExecuteEx failed; code 299.

Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
---------------------------
OK   
---------------------------

**Comment by Shen897** [comment]
The problem from `Inno Setup` and if you google the error message you will see multiple encounter with the same message.
Try: 

- Temporarily disable your AV software
- Run the installer as Administrator
