### ISSUE TITLE
bug: while exporting pdf in typora  v0.9.90, but sucessfully in in typora  v0.9.86.

### ISSUE THREAD

**Issue by juejian** [typora/typora-issues#3686]
my operate system is windows10 64bit.

the **same markdown file** exports two competely **different pdf files** in competely **same configuration** . eg:

 **markdown file:** 

![image](https://user-images.githubusercontent.com/12257223/87221567-89f56a80-c39f-11ea-8a58-05d1fc11337b.png)

 **in typora v0.9.86 ,exported pdf:** 
included bookmarks and local images.

![image](https://user-images.githubusercontent.com/12257223/87221573-937ed280-c39f-11ea-8555-681b3e2b1472.png)

**in typora v0.9.90 ,exported pdf:** 
not have bookmarks and local images, moreover, the text of outline used `[toc]` to generate can't newline.

![image](https://user-images.githubusercontent.com/12257223/87221580-aabdc000-c39f-11ea-8c99-599c36e0fa20.png)

**Comment by abnerlee** [comment]
Sorry for the trouble, we released a new version which fixed this.

**Comment by stm-at-esd** [comment]
Well I want to confirm this problem for Linux too. I'll wait for the new release show up in the package repository.
So far I'm fine with the 0.9.89 version.

Thanks for all your effort. This is a great piece of software and I like how easy it is to export to the target formats and the output quality is also very good without much effort on the user's side.

Best regards,
    Stefan

---
\$: lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
