### ISSUE TITLE
0.9.91 failed to export in PDF、HTML、HTML（without style） format

### ISSUE THREAD

**Issue by Han-Orz** [typora/typora-issues#3687]
PDF, HTML and HTML (without) cannot be exported properly in the all-in-one window style after upgrade. style), the display information is saved as XX.md instead of XX.pdf when exported, and in the classic window style Everything is normal.
![28周 md - Typora 165947](https://user-images.githubusercontent.com/49109378/87242669-6dba0200-c461-11ea-9e05-c0fb57396ef7.png)
![保存 165934](https://user-images.githubusercontent.com/49109378/87242671-6f83c580-c461-11ea-876b-8e90a5a3b083.png)

I don't know the English term for window style, it in Settings - Appearance - Window Style.

The export of docx, EPUB and other formats is normal.

**Comment by abnerlee** [comment]
Fixed in 0.9.92, please try upgrade again, or switch to "native window" style
