### ISSUE TITLE
PicGo.app image uploader with Traditional Chinese translation of Typora?

### ISSUE THREAD

**Issue by vactiger** [typora/typora-issues#3689]
Can I set PicGo.app as image uploader when I use Traditional Chinese translation of Typora?

Thank you.

**Comment by abnerlee** [comment]
PicGo seems only be localized in Simplified Chinese, so we don't support this in other locals.

But if you selected PicGo in Simplified Chinese, after switch to Traditional Chinese, it will still be avaiable
