### ISSUE TITLE
failed to copy online images to local fold

### ISSUE THREAD

**Issue by lunyang** [typora/typora-issues#3690]
can not copy online images to local fold when insert images

**Comment by abnerlee** [comment]
Could you provide more details?

**Comment by lunyang** [comment]
**I want to copy images to custom folder, but it didnot work for me.**
![image](https://user-images.githubusercontent.com/11520127/87246165-19714b00-c47e-11ea-879e-078215804b8d.png)

**My settings:**
![image](https://user-images.githubusercontent.com/11520127/87246173-2db54800-c47e-11ea-8aff-3936e66477f3.png)
![image](https://user-images.githubusercontent.com/11520127/87246191-51788e00-c47e-11ea-83a4-b8969f00b9d1.png)

**Comment by liuhao326** [comment]
It works well for me, but I got another issue:

When I paste text contains many lines like `![epub_27651657_630](https://res.weread.qq.com/wrepub/epub_27651657_630)` （an imgage of markdown）,"Apply above rules to online images"can't work well.Specifically,some images copyed successfully to the folder,and there are still many other images can't copy to it.I found this issue by markdown text in this file:

[test.txt](https://github.com/typora/typora-issues/files/4912199/test.txt)

**Comment by rsyqvthv** [comment]
I have same issue with @lunyang in beta 0.9.92

drag a image from his post to a md file in c:\desktop, it generate this:

```
![image](https://user-images.githubusercontent.com/11520127/87246165-19714b00-c47e-11ea-879e-078215804b8d.png)
```

right click image, choose copy to filename.assets, it popup up a notice with a bell icon: 

> Failed to copy image to target folder. Failed to copy image .ENOENT: no such file or directory, stat
> 'c:\desktop\https:\user-images.githubusercontent.com\11520127\87246165-19714b00-c47e-11ea-879e-078215804b8d.png'

seems Typora tried to download image from related local folder, not from the url.

**Comment by abnerlee** [comment]
please reopen if it still exists in 0.9.96
