### ISSUE TITLE
Typora v0.9.9.34 - Selection of hyphenated words in footnotes misbehaves when using a pointer device

### ISSUE THREAD

**Issue by odkr** [typora/typora-issues#3691]
# Steps to reproduce

1. Create a document with a footnote that contains a hyphenated word:

```markdown
[^Footnote]: A hyphenated-word.
```

2. Double click on either part of the hyphenated word. This selects that part of the word, but *not* the word as a whole.

3. Use the pointer device to expand the selection to cover the word as a whole.

4. Let go of the button.

The selection then 'jumps' so that only the first part of the word is selected.

# Expected behaviour

The whole word remains selected.

Not that this is a particularly severe issue, but still ;-).

**Comment by abnerlee** [comment]
Current spec is same with other apps, like TextEditor.app, Chome, etc

**Comment by odkr** [comment]
I don’t get it. I haven’t expereniced this behaviour in any other application. I just tried with TextEditor.app and I cannot reproduce it there.

**Comment by abnerlee** [comment]
Sorry, I misunderstood your bug report...

**Comment by abnerlee** [comment]
should be fixed

**Comment by odkr** [comment]
Thanks!
