### ISSUE TITLE
Version 0.9.90 Linux breaks the "Download images to local assets directory"

### ISSUE THREAD

**Issue by christophcemper** [typora/typora-issues#3693]
When I copy/paste an image from a website it usually download and puts it into the asset folder.

With Version 0.9.90 Linux this functionality is broken and Typora seems to handle it like a local file.

![image](https://user-images.githubusercontent.com/12080594/87253704-9cde6c80-c47d-11ea-8d07-6114a7d2fc5d.png)

**Comment by christophcemper** [comment]
I stepped back to typora_0.9.89_amd64.deb and it works again as usual

**Comment by abnerlee** [comment]
duplicate with #3690?
