### ISSUE TITLE
Preference setting is still English when selecting Simplified Chinese

### ISSUE THREAD

**Issue by goalidea** [typora/typora-issues#3695]
version: 0.9.9.34.1 (4500)

**Comment by xsvlz** [comment]
It's strange that the language in Preference is Simplified Chinese just several minutes ago, but when I restart typora, it turned to be English. By the way, my OS version is macOS 10.15.5 / 10.15.6

**Comment by goalidea** [comment]
you may be upgraded typora, I remember that before version 0.9.9.34 having no bug

**Comment by goalidea** [comment]
version 0.9.9.34.2 fix this bug
