### ISSUE TITLE
Incorrect italics rendering in Source Code Mode due to underscores in math blocks

### ISSUE THREAD

**Issue by benburk** [typora/typora-issues#3699]
### Steps
1. Open markdown file containing `lorem ipsum $f_\theta$ lorem ipsum $f_\theta$ lorem ipsum`
2. Enable Source Code Mode (View -> Source Code Mode)

### Outcome
The text between the underscores is incorrectly rendered as italics.

### Expected
The text should not be rendered as italics.

**Comment by abnerlee** [comment]
a part of #1638
