### ISSUE TITLE
Code spans in table cell

### ISSUE THREAD

**Issue by infensus** [typora/typora-issues#370]
If a table cell begins with code span containing a pipe, the pipe inside will get escaped.

Example:

```
| test             | test   |
| ---------------- | ------ |
| abc `this|works` | ok     |
| `this|breaks`    | not ok |
```

Saving file or switching between normal and source code mode will escape pipe inside the code span:

```
| `this\|breaks`   | not ok |
```

Close & reopen the file:

```
| `thisbreaks`    | not ok |
```

Version: 0.9.21 (beta)
OS: Windows 10

**Comment by abnerlee** [comment]
Should be fixed in new version
