### ISSUE TITLE
[Feature Request] "Open Quickly" to open file in the same window without changing base folder

### ISSUE THREAD

**Issue by shadyabhi** [typora/typora-issues#3704]
Loving Typora so far :) 

It would be nice to have a feature to quickly open a file in the existing window instead of creating a new window with new base folder for the newly selected file in "Open Quickly". 

For example:- 

```
➤ tree wiki
wiki
├── a
│   ├── a.md
│   └── b
│       └── b.md
└── outer.md

2 directories, 3 files
```
and my base folder is `wiki`.

Proposed workflow:- 

* Assume that I'm currently viewing `outer.md` with base folder configured as `wiki`. 
* Hit `Open Quickly` to open `b.md`.
* Typora opens `b.md` in existing window without changing base folder to `wiki`.

**Comment by abnerlee** [comment]
duplicate with #2736, relates #1883
