### ISSUE TITLE
Feature Request: please make the full file path visible somewhere obvious in Typora

### ISSUE THREAD

**Issue by jeacott1** [typora/typora-issues#3705]
Most editors show the full path of the file they have open, and as such when a user has 6 README.md files open its obvious which one is saving where. - is there an option I cant find in Typora already? 
I see a list of files in the 'Files' sidebar - which I rarely have open, and I have to hover and wait to see the path. 
can we get an option for a full path in the titlebar? it would be really helpful.

Cheers

**Comment by abnerlee** [comment]
#2184
