### ISSUE TITLE
How to use Latex "physics" package?

### ISSUE THREAD

**Issue by entropyincreases** [typora/typora-issues#3706]
I often need to type things like Dirac notation (bra-ket notation). In Latex, it is supported by the "physics" package. I read in
http://docs.mathjax.org/en/latest/input/tex/macros/index.html#j it is supported by mathjax but not autoloaded.??
Is there a way to use this package in typora? Or simply is it possible to just use the dirac notation in typora??

**Comment by ycwang427** [comment]
For using the bra-ket notation in Typora, it works for me to add this at the beginning of the file:
```
$$
\def\bra#1{\left\langle#1\right|}
\def\ket#1{\left|#1\right\rangle}
\def\braket#1#2{\left\langle#1\mid#2\right\rangle}
$$
```

**Comment by abnerlee** [comment]
relates #3388

**Comment by abnerlee** [comment]
supported
