### ISSUE TITLE
Equation in read-only file don't exit edit mode

### ISSUE THREAD

**Issue by 111116** [typora/typora-issues#3707]
Normally when I click on an equation, I can edit its source code and see the preview in a black box. When I click anywhere else, the equation should return to a normal state (only showing rendered equation, no black box hovering).
Now when I open a read-only file and click on an equation, the black box and the source code won't go away as I click anywhere else. This only happens when the file has no write permission.
### version
Typora Version 0.9.9.34 (4498)
macOS 10.14.6 (18G103)

**Comment by abnerlee** [comment]
should be fixed
