### ISSUE TITLE
lets Typora portable?

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#371]
On my Win7, Typora always copy everything under "E:\greensoft\editor\Typora\resources\app\style\themes" to "C:\Users\MYUSERNAME\AppData\Roaming\Typora\themes\". Yes, "C:\Users\MYUSERNAME\AppData\Roaming" is the place to store and search user's data, but this will let "E:\greensoft\editor\Typora\resources\app\style\themes" duplicate

So my question or a feature request is: if local  "E:\greensoft\editor\Typora\resources\app\style\themes" exists, just use it

Thanks

**Comment by Netsaver** [comment]
I also like this feature request.
In order to make it fully operative, it would be needed to:
- add the path for _local pandoc installation_, allowing relative path also
- add the path for _local mathjax installation_, allowing relative path also

Thanks

**Comment by wyf88** [comment]
+1
This can be very useful for using Typora on a PC where administrative privilege is not available.

**Comment by LeBaux** [comment]
Also useful if you want to keep the whole thing in dropbox (or any other cloud) for simple sync.

**Comment by sergeevabc** [comment]
Is there anything we could do to accelerate the implementation of this task?

**Comment by abnerlee** [comment]
We are less likely to provide a portable, since it requires extra work but with high priority

**Comment by cosmicdan** [comment]
I'm really sorry to hear that this isn't on the road map, I have to consider whether it will be worth buying at all without a portable mode when I can currently use Ghostwriter for free (albeit with some missing features that make Typora great). 

Hope it's reconsidered one day, though I doubt it - most commercial software don't allow portable versions for obvious reasons.

**Comment by fuckup1337** [comment]
the fix the installer... or use other locations other tools can do that as well....

**Comment by gandalfsaxe** [comment]
[Caret.io](https://caret.io) installs just fine in user folders, so it doesn't need admin rights. Typora should be able to do the same easily.

**Comment by heartnn** [comment]
In Windows, I write a cmd for portable use.

```
@echo off

if "%1" == "h" goto begin
mshta vbscript:createobject("wscript.shell").run("%~nx0 h",0)(window.close)&&exit
:begin

if not exist "%CD%\Profile\AppData\Roaming" mkdir "%CD%\Profile\AppData\Roaming"
if not exist "%CD%\Notes" mkdir "%CD%\Notes"
REM if not exist "%CD%\Profile\AppData\Local\Temp" mkdir "%CD%\Profile\AppData\Local\Temp"
set USERPROFILE=%CD%\profile
set APPDATA=%CD%\Profile\AppData
REM set TEMP=%CD%\Profile\AppData\Local\Temp
REM set TMP=%CD%\Profile\AppData\Local\Temp
if not exist "%CD%\Notes" goto message
goto start

:message
echo PORTABLE Typora
echo -------------------------------
echo Please point path in Typora:  T:\
echo.
pause 

:start
subst T: .\Notes
start /wait App\Typora.exe
subst T: /D
```

**Comment by lingliugithub** [comment]
one vote for the portable version of Typora!

**Comment by Firef0x** [comment]
You can try this if you want: [Markdown Editor Typora 32/64 bit v0.9.51 Portable version - PortableAppK](https://portableappk.com/portable-typora/)

**Comment by cosmicdan** [comment]
Yeah, that looks safe and legitimate!

Typora will be paid software once it comes out of beta, and that site is already illegally redistributing the software. I wonder what else they're doing illegally in there?

On 7 Dec 2018, Fernando Gilberto Pereira da Silva <notifications@github.com> wrote:
>You can try this if you want: [Markdown Editor Typora 32/64 bit v0.9.51
>Portable version -
>PortableAppK](https://portableappk.com/portable-typora/)

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by EmiLithium** [comment]
> In Windows, I write a cmd for portable use.
> put typora folder to "App" and drop this cmd file with it.

I know this is a dumb question, but what do you mean by "drop this cmd file with it"? Do you have that script saved as a text file and then copy-paste it into the terminal/powershell after saving the Typora install file into App? Or do you actually save that script as an .exe and run it from the terminal, and then run the Typora install file?

**Comment by zeroskyx** [comment]
A tangible workaround is to manually extract Typora from the installer using the following steps without requiring any admin privileges:

1. Download the latest Windows installer from [the official Typora site](https://typora.io/#windows) and save it in some directory
1. Download the [Inno Setup Unpacker](http://innounp.sourceforge.net/) from SourceForge (the most-recent version is `innounp049.rar` on [this directory](https://sourceforge.net/projects/innounp/files/innounp/innounp%200.49/)) and extract `innounp.exe` from the archive into the same directory as earlier
1. Open a command line in that directory and execute the following command: `innounp.exe -x typora-setup-x64.exe` (or `typora-setup-x86.exe` for the 32bit version)
1. Move all the contents from the newly-created folder `{app}` to any directory you want to *install* Typora into
1. Launch `Typora.exe` from within that directory
1. Enjoy!

**Comment by abnerlee** [comment]
Currently the new installer would not require any administrator privilege.

**Comment by PwrSrg** [comment]
I was using a **Portable BETA** for over a year and **LOVED it**!
But now that v1 is out, **it no longer works**. 😖

As soon as there is a **portable version**, you will get my money.
