### ISSUE TITLE
0.9.92 PDF export does not trigger

### ISSUE THREAD

**Issue by Voltra** [typora/typora-issues#3710]
**Environment:** Windows 10 (Unibody or Default)
**Version:** 0.9.92
**Use case:** Exporting to PDF
**Details:**
  * Editing Markdown works as expected
  * I can click on export
  * Popup shows up to select where to save the file
  * Once the output is set, nothing happens

**Expected:** Save in progress followed by file saved successfully
**NB:** HTML exports work properly

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> or attach the md file that cannot be exported as PDF?

**Comment by philobrain** [comment]
I am in a similar boat. Export to PDF prompted me to install pandoc, which was weird. Installed pandoc and now the export takes me to a save dialog trying to save file as a .md. When I hit save or change to .pdf and save, the result is the same: typora dialog appears saying, "Unknown output format defined." Cannot attach .md file because it is business related.

**Comment by abnerlee** [comment]
@philobrain did you try 0.9.92?

**Comment by Voltra** [comment]
Sorry for the late reply, I'm afraid it cannot export any markdown to PDF, I just tested with a blank file and a file containing very minimal text (`aze`).

**Comment by corgile** [comment]
same for me. all exports work fine but pdf not

**Comment by Voltra** [comment]
On a fresh installation of windows, it prompt me with [this error dialog](https://prnt.sc/tsay1m)

**Comment by myxingkong** [comment]
I had the same problem, but when I tried to add a printer, the problem was solved.

**Comment by corgile** [comment]
> I had the same problem, but when I tried to add a printer, the problem was solved.

sorry, what do you mean by "add a printer" ? and how to do that? please share 😋

**Comment by corgile** [comment]
#3766 Solved, works for me.

**Comment by Voltra** [comment]
Sadly using any service that uses port 80 (e.g. apache) will not allow you to use the print spooler (as it depends on the HTTP servcie that also want to occupy the port 80)

**Comment by abnerlee** [comment]
May relates
https://github.com/electron/electron/issues/24456
https://github.com/electron/electron/issues/22695
https://github.com/electron/electron/issues/24734

**Comment by Voltra** [comment]
What worked for me on my fresh windows installation : Enabling (and settings to automatically start) the `Printer Extensions and Notifications` service (`Extension et notifications des imprimantes` for French installation of Windows). I'll test that on my work PC and see if it fixes the problem.

**Comment by myxingkong** [comment]
https://www.youtube.com/watch?v=NZ09xgU0G-o

**Comment by Voltra** [comment]
On my work station I had to do a little more work (since the HTTP service has been previously disabled to allow Apache and WAMP to execute properly). Thankfully I found this [answer](https://superuser.com/a/1368235) to the question: https://superuser.com/questions/1059068/no-http-service-windows-10

**Comment by abnerlee** [comment]
We also upgrade electron version on 0.9.94, please confirm if it is fixed or not.

If not, see #3766 for the workaround.
