### ISSUE TITLE
wrong url returned after uploading image

### ISSUE THREAD

**Issue by Bennett561** [typora/typora-issues#3711]
The image is uploaded successfully, but the url returned is wrong..
have to modify the url manually every time, it's a struggle..

an example:
after uploading, the url is
D:/Program%20Files/Typora/picbed562.oss-cn-shanghai.aliyuncs.com/img/20200717213003.png
actually, it should be
https://picbed562.oss-cn-shanghai.aliyuncs.com/img/20200717213003.png

How can i fix this?

**Comment by abnerlee** [comment]
What is the url returned by the image uploader ?

**Comment by Bennett561** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you, I found the reason, the returned url does not start with http, after modification, it works now.
        
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
——————研究生上海交通大学机械与动力工程学院工业工程与管理系Department of Industrial Engineering and ManagementSchool of Mechanical Engineering,Shanghai Jiao Tong UniversityEmail: bennett_tri@sjtu.edu.cn



        
    
     

    On 7/21/2020 22:02，AbnerLee<notifications@github.com> wrote： 



What is the url returned by the image uploader (not typora) ?
