### ISSUE TITLE
Bug -In Ubuntu 20.04 For zoom-out the number pad's minus (-) does not work for the Keyboard shortcut Ctrl + Shift + -

### ISSUE THREAD

**Issue by rohan-paul** [typora/typora-issues#3712]
I am using Ubuntu 20.04

Bug - For zoom-out the number pad's minus (-) does not work for the Keyboard shortcut Ctrl + Shift + -

Only if I do this combination by selecting the "-" key from the top horizontal bar of the Keyboard does this keyboard shortcut work.

**Comment by abnerlee** [comment]
relates
https://github.com/electron/electron/issues/3332
https://github.com/brave/browser-laptop/issues/4815

What is your Typora version?
