### ISSUE TITLE
How to activate/open the message sequence number function of the mermaid sequence diagram in Typora

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#3713]
I recently found that on the mermaid official page, I saw that the style of the message header was added to the style of their example, as shown below:

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggud64pigqj315w0u0q7o.jpg)

How is this implemented in Typora? I tried exporting without this effect?

I found that the message style in his example will have the marker-start="url(#sequencenumber)" attribute, but manually added to Typora export can see the same effect, but there is no corresponding serial number.

**Comment by MadMaxChow** [comment]
It is found that the official website does not display this serial number every time. For example, directly accessing this address will not display:
https://mermaid-js.github.io/mermaid/#/sequenceDiagram

After opening this page, click on the menu on the left: **Getting started > Examples > Basic** sequence diagram.
Then click the following: **Diagrams > Sequence diagram** page, this page will display the corresponding sequence number.

**Comment by abnerlee** [comment]
duplicate with #3645
