### ISSUE TITLE
typora doesnt work when upload multiple local pics with my own script 

### ISSUE THREAD

**Issue by xxh422735676** [typora/typora-issues#3714]
I wrote a JS script using  sm.ms api to upload my pics and change filename at once.
My script passes the upload test built in typora and it works when I type on a markdown file.
But when I use my script to upload all pics at once ( 5 pics ) in one of my old markdown file, it exited with a error.
Also it will freeze when I try to upload more than 10pics ,only 4-6 pics could be uploaded to the server and  the animation of uploading will never end unless you close the whole process entirely.
[github-issue1](https://i.loli.net/2020/07/18/78c6IAdknUrXG3F.png)
typora version is 0.9..89(beta) running on windows 10
Here is my code:
```
// nodejs 发送smms
//var responses=[]
var date = new Date()
var args=process.argv.splice(2)
var filename
var request = require('request');
var fs = require('fs');
console.log("\nUpload Success:\n")
args.forEach(function(element,index){
    if(index==0){
        filename=String(element)+String(date.getMonth()+1)+"-"+String(date.getDate())+"-"+String(date.getHours())+":"+String(date.getMinutes())+":"+String(date.getSeconds());
    }
    else{
        ups(String(element),filename)
    }
});


function ups(file,filename){
    var options = {
      'method': 'POST',
      'url': 'https://sm.ms/api/v2/upload',
      'headers': {
        'Authorization': 'xxx',
      },
      formData: {
        'smfile': {
          'value': fs.createReadStream(file),
          'options': {
            'filename': filename+Math.round(Math.random()*100),
            'contentType': null
          }
        }
      }
    };
    request(options, function (error, response) {
      if (error) throw new Error(error);
      var reg = new RegExp("\\\\","g");
      var res = response.body.replace(reg,"");
      // console.log(res+"\n")
      var obj = res.split("\"")
      obj.forEach(function(element,index){
        if(element.includes("images")||element.includes("url")){
          console.log(obj[index+2])
        }
      });
      
    });
    
}


```
I hope you can point out why typora fail to parse the result.
It will be better if you can give an example about how typora parse those links. Thank you very much.

**Comment by abnerlee** [comment]
You could try run your script in terminal
```shell
node xxx.js image1.png image2.png image3.png ...
```
And see if it can print 
```
https://xxxxx/image1.png
https://xxxxx/image2.png
https://xxxxx/image3.png
...
```
in terminal or not.

---
You can also open DevTools from `View` menu, and see `stderr` which Typora will print into console.

**Comment by xxh422735676** [comment]
The script actually did out put urls, you can see the pic link I have uploaded  above.
I paste it here https://i.loli.net/2020/07/18/78c6IAdknUrXG3F.png.
The error msg indicates the uploading process to my picpool was successful but somehow typora couldnt recognize them(with more than 5 urls).

**Comment by abnerlee** [comment]
but from your screenshot, your script only print 5 urls, which mismatch your local images to upload

**Comment by abnerlee** [comment]
Maybe caused by https://stackoverflow.com/questions/21188815/stdout-of-node-js-child-process-exec-is-cut-short

We can try its approach in future updates
