### ISSUE TITLE
[Feature Request]Would you have any plan to support wayland for linux platform?

### ISSUE THREAD

**Issue by Me7426** [typora/typora-issues#3715]

**Comment by abnerlee** [comment]
Sorry, we don't have plans for wayland.

**Comment by hypergig** [comment]
@abnerlee now that chrome 87 is stable and includes native [wayland support](https://blogs.igalia.com/msisov/2020/11/20/chrome-chromium-on-wayland-the-waylandification-project/), is it just a matter of using the latest electron libs and compiling typora with a few other flags to add the support? Honest question, I never built an electron app before... 

If so, that seems like hanging fruit :green_apple:

**Comment by abnerlee** [comment]
relates #4000
