### ISSUE TITLE
Latest Win Typora not offered by Update or website

### ISSUE THREAD

**Issue by narration-sd** [typora/typora-issues#3719]
The problem just re-reported with mouse cursor sticking on first line (https://github.com/typora/typora-issues/issues/3718) is serious enough that I went looking for a better release.

I found:

- there is indeed a later Windows release: 0.9.94 (from 0.9.92  that I have)
- but if you ask for About | Updates, only 0.9.92 is still offered
- downloading directly from website, still only 0.9.92 arrives
- there is a good list of Change Notes, but no way to download any of their executables

In this case, actually my first thought was to download a previous version, tell you where the cursor problem began,
but none of those are made available. So that's a second thing to consider from this issue, thanks.

**Comment by abnerlee** [comment]
latest version is 0.9.92 not 0.9.94

previous version are in https://typora.io/windows/dev_release.html
