### ISSUE TITLE
"Auto Numbering for Headings" does not appear in exported documanet

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#372]
I found that http://support.typora.io/Auto-Numbering/ only display the number in Typora, but not in exported PDF/HTML/... Is there any workaround? Thanks

**Comment by abnerlee** [comment]
I updated the doc, the new CSS snip should work

**Comment by GarenXie1** [comment]
I found that http://support.typora.io/Auto-Numbering/ only display the number in Typora, 
but not in exported PDF/HTML/... Is there any workaround? Thanks

**Comment by GarenXie1** [comment]
haven’t seen a solution for PDF export bookmarks without auto numbers. Why close this ticket ?
