### ISSUE TITLE
When editing under tag, the cursor jumps back to tag

### ISSUE THREAD

**Issue by xianzheTM** [typora/typora-issues#3720]
1. Edit an MD file for the hexo. 
2. The file begins as follows:
```
---
title: Title
date: 2020-07-17 17:26:05
tags: spring
---
```
3. Use Win10 **Chinese input method** to edit the next line of tag
4. Trigger the bug
![bug](https://user-images.githubusercontent.com/25103583/87905094-59de5380-ca92-11ea-8b15-c4b9f605c093.gif)
> English input method will not trigger
> It only triggers a bug once

**Comment by abnerlee** [comment]
duplicate with #3318
