### ISSUE TITLE
Ctrl + F Filter display bug

### ISSUE THREAD

**Issue by Thophile** [typora/typora-issues#3721]
Hi,
**First I love Typora ! thanks for your work !**
I just noticed that icon for filters in Ctrl + f mode are too big  *(i guess ?)*
I'm on Win 10 x64 latest version if it can help :) 

![bug typora](https://user-images.githubusercontent.com/44491166/87930272-0ebf4300-ca88-11ea-973d-0a32e809946f.jpg)

**Comment by abnerlee** [comment]
What's your version?

duplicate with #2823
