### ISSUE TITLE
PicGo-Core (command line)  Test Uploader Failed

### ISSUE THREAD

**Issue by WWMLee** [typora/typora-issues#3722]
OS :Window 10 19041.388
Typora Version:0.9.92
![image](https://user-images.githubusercontent.com/6763003/88005671-7a62e800-cb3c-11ea-8a4e-437aa2d74473.png)

"window.Setting.userDataPath" is a function,used as a property.

**Comment by eastynchen** [comment]
Same. PicGo-Core (command line).

```
{
  "picBed": {
    "current": "gitee",
    "gitee": {
      "owner": "",
      "repo": "abc/abc",
      "branch": "images",
      "token": "000...",
      "path": "autoupload",
      "customPath": "yearMonth",
      "customUrl": ""
    },
    "uploader": "gitee",
    "transformer": "path"
  },
  "picgoPlugins": {
    "picgo-plugin-gitee-uploader": true,
    "picgo-plugin-gitee": true
  }
}
```

**Comment by WWMLee** [comment]
可以中文交流？&nbsp;

WWMLee（李俊）
QQ：104887722
微信：WWMLee


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "eastynchen"<notifications@github.com&gt;; 
发送时间: 2020年8月25日(星期二) 晚上6:08
收件人: "typora/typora-issues"<typora-issues@noreply.github.com&gt;; 
抄送: "WWMLee"<WWMLee@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [typora/typora-issues] PicGo-Core (command line)  Test Uploader Failed (#3722)





 
Same. PicGo-Core (command line).
 {   "picBed": {     "current": "gitee",     "gitee": {       "owner": "",       "repo": "abc/abc",       "branch": "images",       "token": "000...",       "path": "autoupload",       "customPath": "yearMonth",       "customUrl": ""     },     "uploader": "gitee",     "transformer": "path"   },   "picgoPlugins": {     "picgo-plugin-gitee-uploader": true,     "picgo-plugin-gitee": true   } }  
&mdash;

**Comment by abnerlee** [comment]
should be fixed
