### ISSUE TITLE
"Copy As HTML Code" not working

### ISSUE THREAD

**Issue by kevquirk** [typora/typora-issues#3724]
When I write a document in markdown, I was expecting the "Copy as HTML code" option to put the plan HTML from the markdown file into my clipboard, but nothing happens - the clipboard remains blank.

Typora version - 0.0.92 (beta)
OS - Pop!_OS (based on Ubuntu 20.04)

Is this a known issue, and is there a fix for this behaviour?

**Comment by kevquirk** [comment]
Note - the equivalent option works in Ghostwriter on the same machine.

**Comment by abnerlee** [comment]
@kevquirk You are using `"Copy as HTML code"` on which kind of content, just text, or images, or.. ?

**Comment by kevquirk** [comment]
I’m using copy as html on plain markdown.

So for example...

`# This is a title

This is some text, **but this is bold**.`

I would expect the above to be placed on the clipboard as html with all the correct markup. But nothing gets added to me clipboard.

**Comment by kevquirk** [comment]
I've been doing more testing with everything from a single line of text, to whole markdown documents with formatting and images. Nothing works. Whenever I click `Copy as HTML code` from the `Edit` menu, nothing is added to my machine's clipboard.

**Comment by kevquirk** [comment]
Oh my goodness, I've figured it out...I'm such an idiot!

I stupidly assumed that selecting the option to `Copy as HTML code` it would copy the entire document, so I didn't have anything selected. I tried `CTRL+A` first and it worked fine.

Please ignore me, I'm clearly an idiot. :smile:
