### ISSUE TITLE
"image load failed" for online picture

### ISSUE THREAD

**Issue by Jared66** [typora/typora-issues#3725]
- **Typora version**: 0.9.92(beta)
- **System**: Windows 10 professional 
- **Issure**: 
  - When I insert an online picture, it can't be loaded. although I can visit the picture through the url in the chrome.
  - When I put the picture in a local direcotry, and use the local path, it work well.
- **Online picture url**: `https://4vector.com/i/free-vector-cc-design_048551_cc-design.png`
----
![1](https://user-images.githubusercontent.com/63780946/88065473-3523d200-cb9f-11ea-93ce-df3a8174156f.png)
----
----
![2](https://user-images.githubusercontent.com/63780946/88065458-31904b00-cb9f-11ea-83cb-c02a7f7044c6.png)
----
----
![3](https://user-images.githubusercontent.com/63780946/88066721-aadc6d80-cba0-11ea-8ccc-3b236337608b.png)

**Comment by abnerlee** [comment]
Do you use proxy, or does a proxy is needed to load the image?

**Comment by Jared66** [comment]
> Do you use proxy, or does a proxy is needed to load the image?

No, I didn't use the proxy. I can visit the picture through chrome without any proxy.

**Comment by zhaoqingqing** [comment]
@Jared66 How did you solve it ？

**Comment by Mark-bbl** [comment]
I have same problem, I successfully upload img on github but it failed in loading in Typora.

**Comment by GodLei902** [comment]
I have same problem。(灬ꈍ ꈍ灬)

**Comment by kbore** [comment]
@qisnzo same problem, how did you solve the problem? it seems you closed the issue. 
thks

**Comment by ro0ki4** [comment]
the same with me

**Comment by ro0ki4** [comment]
> the same...

I solved it now, check if your repository is private. obvious,pictures from private repo cant be displayed. make your repo public
