### ISSUE TITLE
Latex processing broken

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#3729]
All my latex type appears as "Math Processing Error" when I upgraded to 0.9.92.  Previous 0.9.86 (beta) worked OK.

For example, what was  `$ab=c, bc=d$`   now appears as `$[Math Processing Error]ab=c, bc=d$`, but when the tag is expanded, the mouseover preview is correct.

Systems specs
Arch/Manjaro (Linux 5.6.12-1-MANJARO)
Typora 0.9.92
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.6.12-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6300U CPU @ 2.40GHz
Memory: 15.0 GiB of RAM

**Comment by baardev** [comment]
Odd... the 0.9.92 binary version does not have this issue, only the one on the Arch repo

**Comment by abnerlee** [comment]
We don't have an official Arch repo, so I'm not sure how the install script is written. 

Please try clean and install the arch version, or use the binary version.
