### ISSUE TITLE
Cannot update to version 0.9.93 in kubuntu 20.04

### ISSUE THREAD

**Issue by Masacroso** [typora/typora-issues#3735]
When I try to update typora from 0.9.92 to 0.9.93 in kubuntu 20.04 I get an error saying that the expected file size is different from the file size in the server, so it doesn't get updated.

**Comment by yummymath** [comment]
me too, it doesn't get updated in ubuntu 20.04 LTS

**Comment by apoole7** [comment]
and another

**Comment by yanhuacuo** [comment]
It doesn't get update to the version 0.9.93 in Ubuntu20.04 LTS

**Comment by 98wb** [comment]
Upgrade failed ! Ubuntu20.04 LTS

**Comment by Glovecc** [comment]
This issue also exists on elementary OS 5.1.6
![image](https://user-images.githubusercontent.com/39382699/88452476-9d213380-ce91-11ea-9783-cfe915e12bea.png)

**Comment by seamusdemora** [comment]
Ubuntu 20.04:
$ sudo apt-get install typora
[sudo] password for seamus: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  gir1.2-gnomekeyring-1.0 libgnome-keyring0
The following NEW packages will be installed:
  typora
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 67.0 MB of archives.
After this operation, 234 MB of additional disk space will be used.
Get:1 https://typora.io/linux ./ typora 0.9.93-1 [67.0 MB]
Err:1 https://typora.io/linux ./ typora 0.9.93-1
  File has unexpected size (63733760 != 66961132). Mirror sync in progress? [IP: 2606:4700:20::ac43:6152 443]
  Hashes of expected file:
   - SHA256:86c753fbb6d81afe5a31785a0998e206e7ce92e23f026c107fd9ce0a830fc2c3
   - SHA1:dabc4d2630134ed424a49f2714cb487a8de284e5 [weak]
   - MD5Sum:57fc5c16557ad455f3151d39eddabd49 [weak]
   - Filesize:66961132 [weak]
E: Failed to fetch https://typora.io/linux/linux/typora_0.9.93_amd64.deb  File has unexpected size (63733760 != 66961132). Mirror sync in progress? [IP: 2606:4700:20::ac43:6152 443]
   Hashes of expected file:
    - SHA256:86c753fbb6d81afe5a31785a0998e206e7ce92e23f026c107fd9ce0a830fc2c3
    - SHA1:dabc4d2630134ed424a49f2714cb487a8de284e5 [weak]
    - MD5Sum:57fc5c16557ad455f3151d39eddabd49 [weak]
    - Filesize:66961132 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by CsatiZoltan** [comment]
Same error on Ubuntu 18.04. What I tried (in vain):
- `sudo apt clean`
- removed typora and tried to install it by downloading directly from https://typora.io/linux/linux/typora_0.9.93_amd64.deb. Then `sudo dpkg -i typora_0.9.93_amd64.deb` results in
```bash
Selecting previously unselected package typora.
(Reading database ... 310162 files and directories currently installed.)
Preparing to unpack typora_0.9.93_amd64.deb ...
Unpacking typora (0.9.93-1) ...
dpkg-deb (subprocess): cannot copy archive member from 'typora_0.9.93_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive typora_0.9.93_amd64.deb (--install):
 cannot copy extracted data for './usr/share/typora/resources.pak' to '/usr/share/typora/resources.pak.dpkg-new': unexpected end of file or stream
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 typora_0.9.93_amd64.deb
```

**Comment by tingtaoxiaozhu** [comment]
> Ubuntu 20.04:
> $ sudo apt-get install typora
> [sudo] password for seamus:
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Suggested packages:
> gir1.2-gnomekeyring-1.0 libgnome-keyring0
> The following NEW packages will be installed:
> typora
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 67.0 MB of archives.
> After this operation, 234 MB of additional disk space will be used.
> Get:1 https://typora.io/linux ./ typora 0.9.93-1 [67.0 MB]
> Err:1 https://typora.io/linux ./ typora 0.9.93-1
> File has unexpected size (63733760 != 66961132). Mirror sync in progress? [IP: 2606:4700:20::ac43:6152 443]
> Hashes of expected file:
> 
> * SHA256:86c753fbb6d81afe5a31785a0998e206e7ce92e23f026c107fd9ce0a830fc2c3
> * SHA1:dabc4d2630134ed424a49f2714cb487a8de284e5 [weak]
> * MD5Sum:57fc5c16557ad455f3151d39eddabd49 [weak]
> * Filesize:66961132 [weak]
>   E: Failed to fetch https://typora.io/linux/linux/typora_0.9.93_amd64.deb  File has unexpected size (63733760 != 66961132). Mirror sync in progress? [IP: 2606:4700:20::ac43:6152 443]
>   Hashes of expected file:
>   - SHA256:86c753fbb6d81afe5a31785a0998e206e7ce92e23f026c107fd9ce0a830fc2c3
>   - SHA1:dabc4d2630134ed424a49f2714cb487a8de284e5 [weak]
>   - MD5Sum:57fc5c16557ad455f3151d39eddabd49 [weak]
>   - Filesize:66961132 [weak]
>   E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Me too，Ubuntu20.04 LTS Upgrade failed

**Comment by thomascrha** [comment]
If you are like me and need a version with out updating download this and install
http://typora.io/linux/typora_0.9.92_amd64.deb

**Comment by CsatiZoltan** [comment]
@thomascrha I get the same error as for https://typora.io/linux/linux/typora_0.9.93_amd64.deb.

**Comment by thomascrha** [comment]
Yeah it seems like a heap are corrupted - Thats with versions `typora_0.9.93_amd64.deb` `typora_0.9.92_amd64.deb` `typora_0.9.89_amd64.deb` - https://typora.io/linux/linux/typora_0.9.86_amd64.deb seems to be all good though.

```
➜  Downloads sudo dpkg -i typora_0.9.86_amd64.deb
(Reading database ... 221344 files and directories currently installed.)
Preparing to unpack typora_0.9.86_amd64.deb ...
Unpacking typora (0.9.86-1) ...
Setting up typora (0.9.86-1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```

**Comment by CsatiZoltan** [comment]
@thomascrha Thanks, 0.9.96 works. But how come Typora worked until 0.9.92 via the auto-update, while now even the direct links to the .deb files are faulty? I would have expected that the older versions are not influenced by the error in the latest version (0.9.93).

**Comment by thomascrha** [comment]
I have no idea - but it seems the debs are corrupted - I'd say something went wrong in there pipeline/website when upgrading to 93 and some files went bad.

**Comment by MetalGearBronya** [comment]
Seems some error had occurred during the upload of binary to source, maybe we should refer this to the developer @abnerlee

**Comment by 98wb** [comment]
> Seems some error had occurred during the upload of binary to source, maybe we should refer this to the developer @abnerlee

what should we do ?

**Comment by Masacroso** [comment]
I updated now, it seems that the developer fixed the issue.
