### ISSUE TITLE
tar.gz 0.9.93 corrupted

### ISSUE THREAD

**Issue by syco** [typora/typora-issues#3736]
Hi,
latest version cannot be extracted:

![image](https://user-images.githubusercontent.com/54575/88455837-c54c6a80-ce70-11ea-94b2-200b76d5a678.png)

**Comment by alk3mist** [comment]
I got problem with latest version using `apt upgrade` on Ubuntu

**Comment by CsatiZoltan** [comment]
See #3735.

**Comment by syco** [comment]
This issue is not related to the deb package or ubuntu.
The upload process probably corrupted both the same way.
But I need the tar.gz binary file to work, not the debian/ubuntu package.

**Comment by CsatiZoltan** [comment]
Sorry, I mixed it up because I also tried with the .tar.gz file and it failed for me too.

**Comment by syco** [comment]
I see this has been fixed. Thanks.
