### ISSUE TITLE
format becomes disordered after a time

### ISSUE THREAD

**Issue by lfp1024** [typora/typora-issues#3738]
ubuntu 18.04

version: 0.9.92 (previous versions also has this problem)

i am sorry, my english is poor, but i need to report this issue. i like typora

1. i use unordered list to write my note, like this 

   - index.js
     - function
       - conditions

   it looks very beautiful and logical, but after a time, it becomes 

   - index.js

   - function
   - conditions

   can not show logic about my note. looks bad.

2. i use lots of  \```js code \``` to write code in my note, like this 
   the first condion is:

   ```js 
   code1 
   ```

   the second condion is:

    ```js 
    code2 
    ```

   it looks very good, but after a time, it becomes
   the first condion is:

    ```js
    code1
    the second condion is:
    ```

    ```js
   
    ```

   code2 

> 'after a time' means, i run typora all day, during this period，switch between different applications(brower and vscode) and lock screen by win + l , when i read my note at night, i found format becomes disordered.

**Comment by CsatiZoltan** [comment]
@lfp1024 I would give a try to the source code mode (lower left corner, `</>` icon). Does your problem still persist?

**Comment by lfp1024** [comment]
@CsatiZoltan when the problem1 and 2 above present, i toggled source code mode and found markdown grammer was wrong,  i must modify grammer to recover original format. i do not  like to write note with markdown grammer directly in source code mode, so i do not know whether the problem1 and 2 still persist in souce code mode, maybe i would try. thanks for your reply :)

**Comment by CsatiZoltan** [comment]
@lfp1024
> i do not like to write note with markdown grammer directly in source code mode

I understand it, but this is a way to figure out where the problem lies. Then you have more details to report to the developer.

**Comment by lfp1024** [comment]
@CsatiZoltan ok, i will try to find the reason, thx :)
