### ISSUE TITLE
About batch upload of pictures in disorder

### ISSUE THREAD

**Issue by 0clickjacking0** [typora/typora-issues#3739]
typora version: 0.9.9.34 (4498)
os version: macos10.15

When I click to upload all pictures, all pictures can be uploaded successfully, but the order of pictures is wrong, the first picture may be displayed at the end, I hope the developer can solve this problem, thank you!

![image-20200727163448519](http://images.xianyu123.club/20200727163448.png)

**Comment by abnerlee** [comment]
#3512
