### ISSUE TITLE
Copy Shuffles rows

### ISSUE THREAD

**Issue by gilstr** [typora/typora-issues#3741]
If I copy a document with code block within, and then paste it to another application - all rows after the code block appears in reverse order.

For example:

Copy the doc:

Line 1
Line 2
```java
some code```
Line 3
Line 4

Paste yields the following:

Line 1
Line 2
some code
Line 4
Line 3

**Comment by abnerlee** [comment]
I tried copy from Typora and paste into Chrome, which seems working fine.

Could you provide more details? like a screencast, and what target application are you pasting into, does paste into other applications, like Chrome, Word, etc has such problem?

**Comment by gilstr** [comment]
With chrome it just omits the last lines.
