### ISSUE TITLE
[Suggestion] Themable title bar

### ISSUE THREAD

**Issue by Thophile** [typora/typora-issues#3742]
Everything is mostly in the title

You could add a custom title bar (the one OS specific with actions) that could follow the typora theme.

Mostly with darker themes the native window titlebar look awful so having your own is imo a good thing. Fairly easy to do with electron as a frameless app does not loose features like aero snap you just have to  set frame option to false and implement the themable aspect and the 3 buttons that trigger windows actions , i've done it in the past if it may help see below

```js
    document.getElementById('minimize').addEventListener('click', (e) => {
        e.preventDefault()
        var window = remote.getCurrentWindow();
        window.minimize();
    })

    document.getElementById('maximize').addEventListener('click', (e) => {
        e.preventDefault()
        var window = remote.getCurrentWindow();
        if (!window.isMaximized()) {
            window.maximize();
        } else {
            window.unmaximize();
        }
    })

    document.getElementById('close').addEventListener('click', (e) => {
        e.preventDefault()
        var window = remote.getCurrentWindow();
        window.close();

    })
```

**Comment by abnerlee** [comment]
We supported frameless window in Windows, if it is what you're looking for
