### ISSUE TITLE
Problem with PT-BR spell check

### ISSUE THREAD

**Issue by phaalonso** [typora/typora-issues#3743]
Hi, I am a Brazilian and love to use typora to make annotations. I am using typora on a Ubuntu 20.04 and noticed some problems with spellcheck in PT-BR language. Worlds that have some type of special characters like `áãâ` aren't receiving correct word suggestions. For example the correct way to spell is `tolerância`, but when trying to see the suggestions of the spellcheckers when I write `tolerancia` it only suggest `toleraria, intolerante, ancilenteria, cianoferrato`. But `ancilenteria, cianoferrato`are words that don't have the slightest relation with `tolerância`and it doesn't have `tolerância` in the suggestions. 
When directly writing `tolerância` in the text its affirm that is the correct word.
So I assume that is some type of error in the spell check that are blocking the spelling accents.

**Comment by abnerlee** [comment]
#3337
