### ISSUE TITLE
Export PDF doesn't work

### ISSUE THREAD

**Issue by corgile** [typora/typora-issues#3745]
## Version:

![image](https://user-images.githubusercontent.com/48396880/88749048-0f8d5e80-d185-11ea-94b7-3f74bafe8979.png)

## I clicked File -> Export -> PDF, And Save it to the Desktop:

![image](https://user-images.githubusercontent.com/48396880/88749165-4bc0bf00-d185-11ea-962c-dc616a51a6a8.png)

## And a weird thining, no PDF is generated in the Desktop folder

![image](https://user-images.githubusercontent.com/48396880/88749812-adcdf400-d186-11ea-8bba-a5657ac728ab.png)

## Here is the most recent log

![image](https://user-images.githubusercontent.com/48396880/88749699-6fd0d000-d186-11ea-8bf5-c95bdba4f8c4.png)

**Comment by Voltra** [comment]
See related #3710

**Comment by corgile** [comment]
> See related #3710

i went #3710 , but there is no solution for this

**Comment by abnerlee** [comment]
same with #3710 ?

**Comment by abnerlee** [comment]
can empty or small markdown file be exported successfully?
Is there any error log in DevTools -> Console tab during the export process? (I can toggle devtools from menu bar -> view -> toggle DevTools)

**Comment by corgile** [comment]
totally&nbsp;same，i'll&nbsp;check&nbsp;&nbsp;the&nbsp;devtool&nbsp;as&nbsp;you&nbsp;suggested&nbsp;and&nbsp;report&nbsp;useful&nbsp;feedbacks&nbsp;to&nbsp;you&nbsp;if&nbsp;any
这是一个辣鸡



---Original---

**Comment by corgile** [comment]
no, nothing

**Comment by corgile** [comment]
> can empty or small markdown file be exported successfully?
> Is there any error log in DevTools -> Console tab during the export process? (I can toggle devtools from menu bar -> view -> toggle DevTools)


# no, nothing

![image](https://user-images.githubusercontent.com/48396880/89136123-a7fc5800-d564-11ea-8307-a0b717f853c6.png)
