### ISSUE TITLE
Mermaid sequence diagram render weirdly when participants names are long 

### ISSUE THREAD

**Issue by jianzhongli** [typora/typora-issues#3746]
### Environment

Typora Version: `Version 0.9.9.34.2 (4509)`
OS Version: `macOS Mojave 10.14.4 (18E2034)`

### Reproduction Example

```mermaid
sequenceDiagram
SomeReallyLongClass ->> AnotherReallyLongClass: dosomething()
activate AnotherReallyLongClass
deactivate AnotherReallyLongClass
```

Noted that the gray rectangle is not properly aligned.

![image](https://user-images.githubusercontent.com/5278523/88753019-d0174000-d18d-11ea-83cb-b11029be5b5c.png)

**Comment by sirlanda** [comment]
Same problem on Ubuntu.
The diagram renders perfectly in [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor).
The 
`sequenceDiagram
    UEM->>+ PEUF_very_long: uv(ell, ua)
    PEUF_very_long ->>- UEM: uve`
renders perfectly, but adding characters to the second participant breaks the diagram.
It might be that this length fits in the default size.

**Comment by abnerlee** [comment]
@jianzhongli Did you try mermaid live editor using Safari? I think it is still a upstream bug of mermaid, since the rendering is not perfect under Safari.

Add to #1661 and close this one.
