### ISSUE TITLE
Auto pair even when unchecked in preferences

### ISSUE THREAD

**Issue by jordgoff** [typora/typora-issues#3752]
I've unchecked "Auto pair brackets and quotes" in the preferences, but they keep auto pairing. I've tried setting the preference, quitting and restarting, but nothing seems to work.

**Comment by abnerlee** [comment]
We cannot reproduce this.

What's your Typora version and what is your operation system?

And did you use any IME?

**Comment by jordgoff** [comment]
I'm on Mac OS 10.15.6, using Typora Version 0.9.9.34.2 (4509). No IME. 

It happens in source mode, so this line is what I get when I type an unpaired single bracket or quote: ()""{}[]''

Thanks!

**Comment by abnerlee** [comment]
should be fixed in new release
