### ISSUE TITLE
In blockquote inline math is incorrectly interpreted as displayed math and instant rendering box appears in wrong position.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#3754]
*OS: Win10 |TyporaVersion:0.9.93*

----

![ae8fcd04-6168-41a5-846c-dfb8f837189a](https://user-images.githubusercontent.com/46404230/89105368-05a07f80-d453-11ea-8289-82d6bbf18df6.gif)

**Comment by abnerlee** [comment]
Which theme did you use?

What is the operation to move blockquote up in this screencast?

**Comment by peetteerr** [comment]
[night.zip](https://github.com/typora/typora-issues/files/5036160/night.zip)
[base.user.zip](https://github.com/typora/typora-issues/files/5036161/base.user.zip)
I use an old version of night theme and my base user.css, those were attached above.
I slid my finger on Synaptics Touchpad to move the blockquote up.
I believe that operation is irrelevant for there is no correlation between the occurrence of the problem and the screen move operation. Sorry for recording a special case producing some unnecessary ambiguity.

**Comment by abnerlee** [comment]
This seems a issue with your CSS, for example:
```
#write blockquote * {
    color: #686049;
    width: 830px; 
}
```

And I cannot reproduce this in built-in themes without base.user.css
