### ISSUE TITLE
failed to export from .md to tex / word file when tables are included

### ISSUE THREAD

**Issue by gelottho** [typora/typora-issues#3755]
Hi, 

It seems I have some problem to export in .tex files my documents as soon as a table is made in my .md file.
Pandoc is installed and work properly for any files without a table included, with the following statement :

_- Failed to export to ... couldn't read native_

I can export in .tex and words when table are not included, can't when they are.

Many thanks for your help

**Comment by abnerlee** [comment]
duplicate with #3734

**Comment by gsuberland** [comment]
@abnerlee You appear to have closed both tickets as duplicates of each other. This bug still exists.
