### ISSUE TITLE
Zooming on picture NOT working

### ISSUE THREAD

**Issue by Water3000** [typora/typora-issues#3758]
I try right-clicking a picture and zooming it to 150%, but it still looks the same size (in editor) as 100%, same happens on 200%.
Is this a local problem or bug?

**Comment by abnerlee** [comment]
images also has a max-width (same as paragraph) property.

**Comment by dannydarvish** [comment]
I am having the same issue as OP. This seems like a bug.

**Comment by akarasulu** [comment]
@abnerlee how about giving it just a little effort to solve the issue? The zoom feature does not work for me either. I'm on macOS Big Sur 11.7.2 with Typora Version 1.4.8 (6558). How about a descent response to paying customers this time?
