### ISSUE TITLE
Some math subscript notation interpreted as starting emphasis in source code mode

### ISSUE THREAD

**Issue by zmoon92** [typora/typora-issues#3759]
`_` inside an inline math expression `$...$` is sometimes incorrectly detected as starting emphasis for formatting in source code mode.

## Example

Renders fine
![example rendered](https://user-images.githubusercontent.com/15079414/89220226-3097ea00-d59f-11ea-8abb-a42060f72d96.png)

But confusion in source code view
![example source code view](https://user-images.githubusercontent.com/15079414/89220241-355c9e00-d59f-11ea-8bc3-f61a528bbd86.png)

This example used Typora v0.9.93.

**Comment by abnerlee** [comment]
duplicate with #1459

**Comment by zmoon92** [comment]
and already in https://github.com/typora/typora-issues/issues/1638
sorry I didn't check the existing issues thoroughly enough
