### ISSUE TITLE
Heading prompt next to heading text obscured by margin

### ISSUE THREAD

**Issue by altairmn** [typora/typora-issues#376]
I'm using Ubuntu 14.04 LTS. After updating to 0.9.21 (beta), I encountered this bug. It is described below along with screenshots:

When the cursor is on any of the heading lines, then the heading category (h<i>) appears to the left of the heading. In the latest update, this prompt is obscured by the invisible margins. I'm using the newsprint theme.

Screenshots:

![h3](http://i.imgur.com/tOcaGva.png)

![h4](http://i.imgur.com/re1qc0f.png)

**Comment by abnerlee** [comment]
Should be fixed already
