### ISSUE TITLE
typora error

### ISSUE THREAD

**Issue by penetrater** [typora/typora-issues#3761]
var spawn = require('child_process').exec;
 // Hexo 3
hexo.on('new', function(data){
	spawn('typora '+data.path);
});

after cmd：hexo new ”demo“
typora No response

typora v0.9.93
ubuntu20

but Use gedit instead of typora
var spawn = require('child_process').exec;
 // Hexo 3
hexo.on('new', function(data){
	spawn('gedit '+data.path);
});
gedit success
Please solve this problem as soon as possible.
Thank you very much.

**Comment by abnerlee** [comment]
duplicate with #3513
