### ISSUE TITLE
The file created by editing hexo with typeora does not respond.

### ISSUE THREAD

**Issue by penetrater** [typora/typora-issues#3762]
typora v0.9.93
ubuntu20

Create a JS file in the hexo directory：
hexo/scipt/js file
`var spawn = require('child_process').exec;
// Hexo 3
hexo.on('new', function(data){
spawn('typora '+data.path);
});`

after cmd：sudo hexo new ”demo“
typora No response.
The file created by editing hexo with typeora does not respond. Instead of using typeora to create a new file.
1.The new file is created by hexo.
2.typora no response.

but use gedit instead of typora
`var spawn = require('child_process').exec;
// Hexo 3
hexo.on('new', function(data){
spawn('gedit '+data.path);
});`
gedit success

Please solve this problem as soon as possible.
Thank you very much.

**Comment by abnerlee** [comment]
Did you try "typora ${path}" in command line? what will be the error message?

And what is the error message of `spawn('typora '+data.path)` ?

And it should be `spawn('typora', [data.path])` based on http://nodejs.cn/api/child_process.html#child_process_child_process_spawn_command_args_options?

also duplicate with #3761

**Comment by penetrater** [comment]
In the beginning, `spawn('typora', [data.path])`  or `spawn('gedit', [data.path])`，both No response，so I changed the code，than gedit can response，but typora no response.

Typora cannot run as root.
or，There are too many permissions problems in Ubuntu. I have given up building blogs in the Ubuntu system.
I'm sorry I can't give you any more information.
I will use hexo under win system，There are not so many problems in Win10 system.

**Comment by penetrater** [comment]
Thank you again for your sincere response.

**Comment by abnerlee** [comment]
Is there any error message if you do "typora xxx.md" in terminal, currently there's no error message provide to find the issue

**Comment by penetrater** [comment]
yes,sudo typora xxx.md，error is `xxx.c cannot run as root.`“xxxxx   ---no-sandbox”
but sudo typora xxx.md --no-sandbox，There are still mistakes.
sorry,I've already uninstalled the Ubuntu 20 system.
It is difficult to solve the problem of cooperation between hexo and typora in the short term（in ubuntu20）.
