### ISSUE TITLE
What can I do for show taskd header in TOC?

### ISSUE THREAD

**Issue by mavlutovr** [typora/typora-issues#3763]
## Example of code

```markdown
## Header 1

- [ ] ## Header 2. Can I see the header in TOC?

## Header 3
```

## Screenshot

![](https://i.imgur.com/3qv26Em.png)

**Comment by abnerlee** [comment]
Headings in outline will exclude headings in list and blockquote, just "root" level of headings are included.


We don't know how to "properly" handle headings in list level, because in list like

```markdown
- # H1
   - # H1
- ## H2
```

from the list intention, the level seems like
```
H1
--H1
H2
```

from the heading levels, it is 
```
H1
H1
---H2
```

Basically, if user put headings in list, then the list itself would represents the levels & orders, so why still need to put those headings in outline panel?

**Comment by mavlutovr** [comment]
I have a work-file with some tasks. For example:

```markdown
## - [ ] Project 1 - Fix.....

- [ ] Step 1
- [ ] Step 2
- [ ] Step N

## - [ ] Project 2 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N

## - [ ] Project 3 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N

## - [x] Project 4 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N

## - [ ] Project 5 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N
```

Also I made a script, that move ready-made blocks (checked headers ##) to archive-folder for autoclean the file.
It is convenient for me to use one file, where I can write anything fast.

And sometimes I try to find a section by header in the file from left panel. It will be more comfortable.

**Comment by abnerlee** [comment]
But in my test 
```
## - [ ] Project 1 - Fix.....

- [ ] Step 1
- [ ] Step 2
- [ ] Step N
```

is supported, `## - [ ] Project 1 - Fix` is still heading, not a task list.

**Comment by mavlutovr** [comment]
Sorry, I confused.

This is correct:

```markdown
- [ ] ## Project 1 - Fix.....

- [ ] Step 1
- [ ] Step 2
- [ ] Step N


- [ ] ## Project 2 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N


- [ ] ## Project 3 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N


- [x] ## Project 4 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N


- [ ] ## Project 5 - Make...

- [ ] Step 1
- [ ] Step 2
- [ ] Step N
```

**Comment by abnerlee** [comment]
close as #3890 describe this better
