### ISSUE TITLE
Error when opening a second file on the same drive from secondary instance

### ISSUE THREAD

**Issue by arthurjosse** [typora/typora-issues#3764]
Typora 0.9.92
Windows 10

1. Open a markdown file on a drive
2. Open another markdown file on the same drive

→ The second file is opened but this error message pops up:

![Typora_Aquhht4MJD](https://user-images.githubusercontent.com/37088908/89404385-2bab7580-d71a-11ea-8d61-b09f4c9066db.png)

The log:

INFO 8/5/2020, 12:35:20 PM  ------------------start------------------
INFO 8/5/2020, 12:35:20 PM  typora version: 0.9.92
DEBUG 8/5/2020, 12:35:20 PM  [
  'C:\\Program Files\\Typora\\Typora.exe',
  'D:\\Photos\\Bordel\\selection.md'
]
DEBUG 8/5/2020, 12:35:20 PM  app.openFile
INFO 8/5/2020, 12:35:20 PM  addRecentDocument
INFO 8/5/2020, 12:35:21 PM  [Raven] instanceKey = 
INFO 8/5/2020, 12:35:21 PM  [Raven] userId = 
INFO 8/5/2020, 12:35:21 PM  [focus] 1
DEBUG 8/5/2020, 12:35:24 PM  checkForUpdates https://typora.io/windows/dev_release_64.json
INFO 8/5/2020, 12:37:06 PM  [blur] 1
INFO 8/5/2020, 12:37:09 PM  [focus] 1
INFO 8/5/2020, 12:37:10 PM  [blur] 1
INFO 8/5/2020, 12:37:15 PM  got argv [C:\Program Files\Typora\Typora.exe --allow-file-access-from-files D:\Photos\selection\notes.md] from secondary instance
DEBUG 8/5/2020, 12:37:15 PM  app.openFile
INFO 8/5/2020, 12:37:15 PM  addRecentDocument
INFO 8/5/2020, 12:37:15 PM  [focus] 2
INFO 8/5/2020, 12:37:15 PM  [blur] 2
INFO 8/5/2020, 12:37:16 PM  [focus] 2
INFO 8/5/2020, 12:37:16 PM  [blur] 2

**Comment by abnerlee** [comment]
should be fixed in new release
