### ISSUE TITLE
Headings should not be the last paragraph on a page:

### ISSUE THREAD

**Issue by knennigtri** [typora/typora-issues#3765]
I'm using the code snippet below to avoid having headers as the last paragraph on my outputted PDF. I have tried many different iterations of this but I cannot seem to get it to work. The heading (h3 in this case) continues to be at the bottom of the page (rather than starting on a new page).

```
@media print, (overflow-block: paged) or (overflow-block: optional-paged)
{
 /* Headings should not be the last paragraph on a page: */
  h1, h2, h3, h4, h5, h6
  {
    page-break-after: avoid;
  }
}
```

**Comment by abnerlee** [comment]
Duplicate with #1472

You may try https://stackoverflow.com/a/53742871

We will check if it is fine to just embed such CSS
