### ISSUE TITLE
[Solved]  Exporting PDF succeed after activating these three services: 

### ISSUE THREAD

**Issue by corgile** [typora/typora-issues#3766]
> TIP: press PRI in short time and it will be located

![image](https://user-images.githubusercontent.com/48396880/89485245-f151df00-d7d2-11ea-9ef4-d9927a690a09.png)

**Comment by corgile** [comment]
In fact , just Print Spooler is enough.

**Comment by QQabby** [comment]
I have the same problems on Windows 10, I solved the problem ，Just add a printer to the computer and install some drivers automatically，then try it success.

**Comment by Mojito-hub** [comment]
I have done according to the course to open Print Spooler, but it seems can't work!

**Comment by knicond** [comment]
> In fact , just Print Spooler is enough.

I could export as docx,but failed PDF.

**Comment by xinlong-yang** [comment]
> > In fact , just Print Spooler is enough.
> 
> I could export as docx,but failed PDF.

have you solved this problem?

**Comment by knicond** [comment]
> > > In fact , just Print Spooler is enough.
> > 
> > 
> > I could export as docx,but failed PDF.
> 
> have you solved this problem?
But I could export as docx then export to PDF in docx.

**Comment by knicond** [comment]
> > > In fact , just Print Spooler is enough.
> > 
> > 
> > I could export as docx,but failed PDF.
> 
> have you solved this problem?
I have tried Print Spooler,no use.
