### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by arthurjosse** [typora/typora-issues#3770]
Windows 10
Typora 0.9.92

Nothing happens when I'm using `Ctrl+Shift+[` to insert an ordered list while using `Ctrl+Shift+]` gives me an ordered list instead of an unordered list ¯\_(ツ)_/¯

I have edited my conf.user.json as shown below but it's still not working
```
"keyBinding": {
	"Ordered List": "Ctrl+Shift+["
	"Unordered List": "Ctrl+Shift+]"
 }
```

**Comment by arthurjosse** [comment]
It may be a limitation of Electron with non-QWERTY language layout. Appalling if that's the case.

**Comment by abnerlee** [comment]
Could you try "Ctrl+Shift+[" equivalent on your keyboard layout, for example, if you need to press Alt+B to input [, then use "Ctrl+Shift+Alt+B", also,please try ctrl/shift on different side.

If still no luck, please tell us your keyboard layout.
