### ISSUE TITLE
Font becomes blurry over time when using Fusion 360

### ISSUE THREAD

**Issue by dtrichter** [typora/typora-issues#3771]
In the most recent build I have noticed that the fonts will frequently be come 'blurry' ~~when I'm using both Typora and Fusion 360 - a 3d CAD software from Autodesk.  It is very easy to produce if you have both of these programs.  I simply move my mouse between F360 and Typora without clicking and the font begins to erode~~.

~~At first I thought this may be a video card issue, but this same thing does not happen when rendering text or websites in Chrome.  Thus I am placing the issue here in hopes that someone will be able to help me.~~

I often use Typora to keep running notes on a 2nd monitor, so it is not at all unusual to be reading these notes without returning focus to the window.  

**OS Version:** Window 10 Pro Build 10.0.19041
**Typora Version:** 0.9.93 (most recent as of this posting)
**Typora Theme:** GitHub @ 100% Zoom

**Comment by dtrichter** [comment]
In my post above I stated that when using Fusion 360 this was easy to reproduce - which is true.  Since then I have noticed a similar issue with alternating between Typora and Google Chrome.  This was more difficult to produce.  I would perform normal browsing for several minutes only to notice that the font became blurry.  This occurred several times within a 3-4 hour period.

**Comment by abnerlee** [comment]
> Since then I have noticed a similar issue with alternating between Typora and Google Chrome.

**Comment by dtrichter** [comment]
@abnerlee The font becomes blurry in Typora when I alternate using Typora and Chrome.

I have also seen this when alternating focus between Typora and Excel.  It seems likely that my first post regarding this issue when alternating between Typora and Fusion 360 may have been a red herring.

**Comment by dtrichter** [comment]
Here are a couple of screenshots I was finally able to capture of the behavior


![Capture](https://user-images.githubusercontent.com/68116736/90191994-d9e89800-dd76-11ea-8d3e-611eed49bbf0.PNG)


![Capture2](https://user-images.githubusercontent.com/68116736/90191995-da812e80-dd76-11ea-8c53-444e1e89993a.PNG)

**Comment by abnerlee** [comment]
We upgraded chromium version, does this still happens?

**Comment by dtrichter** [comment]
@abnerlee - unfortunately no. :(

Since my last post here, I have run Typora alongside both Solidworks and Fusion360 on 3 other windows machines.  In all cases, I occasionally find this issue to persist.

**Comment by abnerlee** [comment]
what about 1.4.4?

**Comment by dtrichter** [comment]
I am not able to access the computer on which this was originally reported, and so cannot fully verify that the issue is fixed.  However, I tested this again with both SolidWorks and Fusion 360 and was not able to reproduce the problem.  Thank you for your continued attention.
