### ISSUE TITLE
What's a good way to handle a workspace with hundreds of files?

### ISSUE THREAD

**Issue by Bestulo** [typora/typora-issues#3772]
I have multiple kinds of trouble with my workspace. I use it mainly for blogging. I have a few folders about ideas, analysis, collection of information, and more folders for writing partials, summaries, finals, essays, etc.

* One of my problems is that to edit, I have to navigate a lot to find the right folder to put my text. I can lose my train of thoughts while doing this.
* Another problem is finding the last note I edited. That's cool on Evernote and other similar editors, but since Typora is filesystem/filetree and the normal file editor can't handle too many files, I have to resort to normal file explorer to see which folder has last edited, etc., and I end up simply not doing that (I end up creating more files instead of editing ones I edited before, and I can't make use of my work properly).
* All my folders have to be in one macro folder, so that I can synchronize it properly with Dropbox or Drive or whichever cloud software I use. This makes it so I have dozens of folders. I regularly organize and push first level folders to second or third level, trying to minimize the effect of the disorder, but it's still chaotic, inefficient and it kills my desire to work.

One way I've started to use to combat this is to make all new files root level and leave them there until I'm in the mood to organize, and then I put them in the right folder. This is not efficient at all. Another thought I've had is I could create even fewer folders, organized by type of writing, and instead of topical/thematic divisions, have logical separations/kind-of-writing. But I'm not sure this will solve the problem at all.

Do any of you guys have a solution for this problem? How do you deal with several books' worth of notes?

**Comment by abnerlee** [comment]
can be covered by #2126 and other topics

**Comment by Bestulo** [comment]
I don't see the relationship between that and this. He's asking to allow opening multiple files at the same time, and watching multiple folders on the same workspace.

I'm asking about strategies to manage large workspaces with hundreds or thousands of files, which makes navigation problematic.
