### ISSUE TITLE
[Feature Request]： customize outer javascript file or link

### ISSUE THREAD

**Issue by corgile** [typora/typora-issues#3773]
## why?

for this makes typora pluggable and meets the different needs of different users

e.g.  If I want to insert some chart like below, so I can add a link into typora settings and then typora will be able to render beautiful charts without modifying its source code

Once JavaScript is allowed to be customized, both the software and the user experience will be greatly improved

![image](https://user-images.githubusercontent.com/48396880/89705344-22770e80-d98f-11ea-909d-82b18bc15d9e.png)
> from [Here](https://g2plot.antv.vision/en/examples/bar/basic)

**Comment by corgile** [comment]
### Now that dynamically import/change css(theme) is supported, then why not js too😋

**Comment by corgile** [comment]
If so, I think this: #3227 will be satisfied easily

**Comment by abnerlee** [comment]
duplicate with #162
