### ISSUE TITLE
[UI Improvement] Suggested words

### ISSUE THREAD

**Issue by Tinydile** [typora/typora-issues#3778]
Hello, I am happy if you could implement the following:
Title: "List suggested words possibly miss-spelled" below under "Learn Spelling" and "Search with Google"

Reason: Currently the suggested words are displayed above of "Learn Spelling" and the number of suggested words are variant (zero or many). It makes difficult to choose "Learn Spelling". We have many terminology which listed in Typora in default (obviously) so I would like to add words without find that button.

![image](https://user-images.githubusercontent.com/15231831/89969298-fca08100-dc90-11ea-9390-6df7e747565c.png)

**Comment by abnerlee** [comment]
Typora follows the spec of macOS and Windows app for this. Like 

![](https://www.groovypost.com/wp-content/uploads/2013/03/Alt-F7.png)
