### ISSUE TITLE
[Feature Request] Copy an Image to Clipboard

### ISSUE THREAD

**Issue by H8to** [typora/typora-issues#3779]
Hey!

I use Typora as my Cherrytree Replacement, as it fits very good and does not slow down on large libraries of text.

A feature I am missing is the functionality to copy images back to the clipboard.
I often temporarily paste edited Flameshot screenshots from the clipboard into Typora in order to copy them later on to paste it into my LaTeX files in Atom. This is currently not possible as Typora only copies the file name or full markdown link but not the picture data.

I'd love to see `ctrl+shift+c` or a customizable shortcut for this feature.

:1st_place_medal:

**Comment by abnerlee** [comment]
#3615
