### ISSUE TITLE
"Auto Numbering for Headings" does not appear in exported document correctly yet

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#378]
I have reported this as https://github.com/typora/typora-issues/issues/372, which supplied an updated solution. Thank you. 

However 
1. the autonum appears in exported PDF/HTML, but not DOCX/RTF
2. Even in exported PDF, the bookmark does not have the num. In other words, only the autonum appears only in the text

Maybe this will be hard or impossible to fix since markdown is not for complex text writing.

**Comment by retsyo** [comment]
[toc] and outline does not render autonum too

**Comment by abnerlee** [comment]
"Auto Numbering for Headings" in the wiki page is a style, not a part of text content itself. Current export option for docx/rtf does not include the css style.

For docx, this would help -> https://support.office.com/en-us/article/Number-your-headings-ce24e028-4cb4-4d4a-bf25-fb2c61fc6585

And we will update the doc add support for [toc] part.
