### ISSUE TITLE
"Emoji & Symbols" in the menu bar is absent

### ISSUE THREAD

**Issue by barro350** [typora/typora-issues#3780]
OS: Windows 10 (2004)
Typora version: 0.9.93

The official markdown reference (https://support.typora.io/Markdown-Reference/#emoji-happy) suggests that I can type Unicode characters for emojis:

> Entering UTF-8 emoji characters directly is also supported by going to Edit -> Emoji & Symbols in the menu bar.

However, on my desktop I can't find `Emoji & Symbols` in the menu.

![image](https://user-images.githubusercontent.com/69441424/90023631-e88b6c80-dcee-11ea-8406-7f3a68066143.png)

https://github.com/typora/typora-issues/issues/2145#issuecomment-461899754 suggests that `Emoji & Symbols` is absent in Linux as well. Is this supported only on MacOS?

---

Edit:
Also, it would be great if there is a feature converting emoji expressions to Unicode characters, for example, `​:x:​` to ❌ and `:heavy_check_mark:​` to ✔️. This would make tables containing long emoji names neater when we open a Markdown file in a plain text editor like Notepad.

**Comment by sekhar989** [comment]
Any update on this?
![Screenshot_2021-02-11_21-50-05](https://user-images.githubusercontent.com/19548050/107665729-bc5ba300-6cb3-11eb-9b4d-da3abb417075.png)

OS: Xubuntu

**Comment by abnerlee** [comment]
added on Windows.

For linux, there's currently no native support about emoji panel

**Comment by tholonia** [comment]
OK, it's 2024 now.  Is there still no support for emojis on linux?
