### ISSUE TITLE
Cannot click of Iframe embedding 

### ISSUE THREAD

**Issue by TommasoBendinelli** [typora/typora-issues#3782]
So I have Typora document with following DrawIO: 

<iframe frameborder="0" style="width:100%;height:493px;" src="https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1#RzZZvb9owEMY%2FDS%2BHQkJSeDko7SbRriqTNl4ack28ObnIOJDs0%2B9CLuQfRa20ir2JfI%2FPse%2F3xI4HzjzK7rVIwgf0QQ1sy88Gzu3Atqdjj56FkJeC605LIdDSL6VRLazkH2DRYjWVPuxaiQZRGZm0xS3GMWxNSxNa46Gd9oKqPWsiAugJq61QffWH9E1YqhP7pta%2FgAzCauaRx%2FVFokrmSnah8PHQkJzFwJlrRFO2omwOqmBXcSnH3b3Se1qYhti8ZcC3TZqtH9Lke75UM%2FurDO%2Bk94nfshcq5YJ5sSavCIBPQDhEbUIMMBZqUaszjWnsQzGNRVGds0RMSByR%2BAuMydldkRokKTSR4t5%2BKbyuHaZ6CxfW7%2FAnIXQA5kLeuMwramlMwKDuASMwOqcEDUoYuW%2BbL%2FgbCk55NWZqMOl3UL8KZGKr85%2FF%2BKFbhWt%2B3TG4zVpRztHHm%2BP%2BV%2BY4vS3xNFyTcGxbI8uibeYpqme20dQKitbT8LGT0fVXKTqxCh8PoTSwSsSR3IHOzDduhT1oA9lFPtzruFwCH7l2tZ5DfYCNqlMpbBxeE%2BuDkI57SJcNpPYZoMsGUPfKPE%2F%2FIubpTK%2FN0%2B3xfG7wnE7OAH2ugXoiKiDFm11yBHR1wG4X8OTagL0zgB8rtB1SVKRpI9kZjb9hjgo1KTHGBcYXqVRHEkoGMYVbQgekzwpkku4en7kjkr6vXvOg%2FUP4FzbYbsuG8U3fhukZF%2Bz3u0BhffE59jVuj87iLw%3D%3D"></iframe>

I would like to click on the pencil that redirects me to another link in the browser. But it seems that it does not work. In Chrome instead I can click on the pencil with no issue.

To replicate just copy this code into a Typora document and try to click on the pencil.

**Comment by abnerlee** [comment]
The `iframe` is a sandbox, which does not support popups from js inside the iframe for security reason.  
So opening new window caused by iframe is not supported

**Comment by TommasoBendinelli** [comment]
But why does this work if I embed the iframe into an html page? Is there any workaround?
