### ISSUE TITLE
source code mode unpredicted cursor and screen movement

### ISSUE THREAD

**Issue by snail123815** [typora/typora-issues#3785]
Typora version: 0.9.9.34.2 (4509)
It already happens tracing back some older versions.

When you are in source code mode, the last line of the file cannot be selected. The editor scroll back automatically.

A gif showing typing in the last line and click
![type and click](https://user-images.githubusercontent.com/9590933/90311978-f31d5000-df00-11ea-8eef-cd19bdf63c69.gif)

A gif showing the selection doesn't work as expected as well
![selection](https://user-images.githubusercontent.com/9590933/90311997-18aa5980-df01-11ea-88a1-32b6483d2964.gif)

**Comment by abnerlee** [comment]
should be fixed
