### ISSUE TITLE
Cannot make a table with a single row

### ISSUE THREAD

**Issue by barro350** [typora/typora-issues#3786]
According to the GitHub Flavored Markdown Spec (<https://github.github.com/gfm/#example-205>),

```
| abc | def |
| --- | --- |
```

should be rendered to

| abc | def |
| --- | --- |

i.e., a table consisting of a single header row and no data rows.

However, in Typora, this table is not rendered properly.

**Comment by abnerlee** [comment]
This seems new in GFM

**Comment by abnerlee** [comment]
relates #2254

**Comment by abnerlee** [comment]
fixed in new release
