### ISSUE TITLE
How to cancel the auto scrolling during mouse hover on scrolling bar

### ISSUE THREAD

**Issue by muzihuoyubai** [typora/typora-issues#3787]
when mouse hover on the right scrolling bar, the position will change to the mouse  hovering

Environments
Mac OS 10.14.6
Typora 0.9.9.34.2 (4509) (beta)

**Comment by muzihuoyubai** [comment]
Environments
Mac OS 10.14.6
Typora 0.9.9.34.2 (4509) (beta)

**Comment by abnerlee** [comment]
Could you provide a screencast? I'm not able to reproduce this.
