### ISSUE TITLE
Adding line numbers

### ISSUE THREAD

**Issue by SESAgger** [typora/typora-issues#3788]
Hi guys,
So, I'm aware that there's a very nice guide on how to add custom css, but I can't make it work (probably user error), so I'll try here:

How do I add line numbers on all themes? Not just in code blocks, but globally.

I've tried inserting 
.CodeMirror-linenumber {
    visibility: visible
}
several different places with no luck, but honestly, I have no idea where I should do it.

**Comment by abnerlee** [comment]
it is currently not supported

**Comment by metal450** [comment]
Is there a reason why this was closed?  Just trying out Typora for the first time, & I was trying to enable line numbers (not just in codeblocks, but universally - as I had in ReText & KWrite). I only found this issue, which seems not to have been resolved, but was closed....?
