### ISSUE TITLE
Pandoc command line

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#3789]
I read that Pandoc renders the PDF better than the direct export.
The exported PDFs use a very light font that is almost grey (even if printed in B/W) and math fonts such as fractions are so thin that fractions are dotted when printed in A5.

Therefore I tried to use pandoc directly but math is not converted.
What is the Pandoc command line equivalent to export a Typora document to pdf?

TIA

**Comment by abnerlee** [comment]
Please refer https://pandoc.org/MANUAL.html#math

from Pandoc's manual, the tex_math_dollars extension should be enabled

**Comment by raffaeler** [comment]
@abnerlee Yes, that is what I did but it didn't work
```
pandoc test.md -f markdown+tex_math_dollars  -s -o test.pdf
Error producing PDF.
! Undefined control sequence.
l.82 ...mata \(z\) converge con ROC \(1<|z|<\infin
```
Could you please write down a command line that understand the Typora format and works with math?
After that I should be able to manage if there is some problem on the pandoc side.

Thanks

**Comment by raffaeler** [comment]
Input document:
```
# Test title

This is an inline math $\omega_n$ inside a paragraph.

While this other:
$$
\int_{n=-\infin}^{+\infin} x dx
$$
is formula in a separate paragraph.
```

Command line (one of the many I tried):
```
pandoc test.md -f gfm+tex_math_dollars --mathjax -s -o test.pdf
```

Output:
```
Error producing PDF.
! Undefined control sequence.
l.61 \int_{n=-\infin
```

@abnerlee I just need a valid **command line** that is **equivalent to File -> Export -> PDF in Typora**.

Thank you very much

**Comment by abnerlee** [comment]
> @abnerlee I just need a valid command line that is equivalent to File -> Export -> PDF in Typora.

Sorry, currently, there's no such command, but we would support custom Pandoc exports in future release.
