### ISSUE TITLE
support captions for figures

### ISSUE THREAD

**Issue by alperyilmaz** [typora/typora-issues#379]
Already mentioned within #90 but still wanted to mention separately. It would be nice to have figure captions underneath the image. The caption should be taken from link name between square brackets.

```
![Figure 1. Figure caption sample](images/figure1.png)
```

should be converted into "**Figure 1.** Figure caption sample".  And, I'm guessing this should be done by replacing `<img>` with `<figure>` in html.

```
<figure>
    <img src="images/figure1.png" alt="" />
    <figcaption><bold>Figure 1.</bold> Figure caption sample<figcaption>
<figure>
```

**Comment by RobertGoulding** [comment]
This would be a great enhancement - especially as I'm working on a document with many figures at the moment, and need to cross-ref etc.

**Comment by christofs** [comment]
+1

**Comment by InsidiousMind** [comment]
+1

**Comment by GandalfSaxe** [comment]
+1

**Comment by mylogicniche** [comment]
+1

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/249

**Comment by Topicaleks** [comment]
I know it sounds a little old-school but use tables.

**Comment by elec3647** [comment]
@Topicaleks thats what I do.

**Comment by dorukhansergin** [comment]
+1

**Comment by bdsoha** [comment]
+1

**Comment by nheeren** [comment]
> I know it sounds a little old-school but use tables.

@Topicaleks can you elaborate?

**Comment by masterstevelu** [comment]
I don't find a solution for this issue now. Does anybody have any idea? Is `pandoc` a workaround?

**Comment by SilverWx** [comment]
We need caption !

**Comment by latsami** [comment]
Several people have developed custom markdown extensions to implement <figure> and <figcaption>. The syntax is based on the definition lists which I find quite logical.

An example of a python-markdown extension for this: https://github.com/aleray/markdown-figures

Would it be possible to add this to the markdown syntax Typora uses?

**Comment by tennr** [comment]
+1 
came here to add and saw it's been on request for over 10 years.  :(

**Comment by Bilallbayrakdar** [comment]
+1

**Comment by ZureTz** [comment]
+1

**Comment by xpatronum** [comment]
+1

**Comment by karlvoigt** [comment]
+1
