### ISSUE TITLE
Ctrl/Cmd + f should _always_ select existing text in the search bar

### ISSUE THREAD

**Issue by Coda-Coda** [typora/typora-issues#3790]
Minor issue.

In the following scenario:
1. Open the document
2. Ctrl/Cmd + f and type some text
3. Read the search result and scroll (but do not click within the document)
4. User realises they would like to search for something else
5. Ctrl/Cmd + f

Now, the originally typed text is _not_ selected so it is easy for the user to make the mistake of typing their new query which ends up appended to the original query rather than replacing it.

Desired behaviour: Ctrl/Cmd + f should _always_ select existing text in the search bar (so that typing replaces the existing text). This would match the behaviour of most other editors. Note that this is the behaviour of Typora if the user clicks within the document before searching again, this issue is just present if the user only scrolls between searches.

(Typora 0.9.9.33.2 (4442))

**Comment by abnerlee** [comment]
should be fixed

**Comment by Coda-Coda** [comment]
Perfect, thank you!!
