### ISSUE TITLE
Safari starts when I view a file with a local image

### ISSUE THREAD

**Issue by ddulaney** [typora/typora-issues#3791]
Some of my `.md` files reference local images. The images are rendered properly, but Typora opens Safari every time. Is there any way to disable this? My default browser in the MacOS preferences is Chrome, but ideally no browsers would open. Thanks!

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> the sample *.md file? and what is your Typora version?

**Comment by ddulaney** [comment]
Hi @abnerlee, yep I just sent an email with the example *.md file as well as the image it references. I'm using Typora version `0.9.9.34.2 (4509)`. Thanks!

**Comment by abnerlee** [comment]
I'm still not able to reproduce this. What's your md file path look like? Does this happens in 0.9.9.35.2, if so, possible to send us <hi@typora.io> a screencast as well? Thanks in advance

**Comment by ddulaney** [comment]
> What's your md file path look like?

```
$ pwd
/Users/ddulaney/Documents/Typora

$ ls
Example With Image.md		Example Without Image.md	image-20200819115443230.png
```

> Does this happens in 0.9.9.35.2

Yeah, I'm currently running `Version 0.9.9.35.2 (4715)`.

>  possible to send us hi@typora.io a screencast as well?

Done.

**Comment by abnerlee** [comment]
Does this happens in 0.9.9.36.2? since we cannot reproduce this issue.

**Comment by ddulaney** [comment]
Hey @abnerlee, the issue seems to be fixed now! Feel free to close this issue. Thanks!

**Comment by abnerlee** [comment]
Hmm, actually we didn't do anything, may just be a system bug~

**Comment by abnerlee** [comment]
Hi, @ddulaney do you still meet error like #4641 ?

**Comment by ddulaney** [comment]
Hey @abnerlee. Nope, I haven't seen this issue since we closed it in December.

**Comment by braincs** [comment]
I came across the same issue. My typroa version is 0.10.6 (5297). would you mind share your solution please? It's quite bothering me a lot. 

> Hey @abnerlee, the issue seems to be fixed now! Feel free to close this issue. Thanks!

**Comment by ddulaney** [comment]
Hmm sorry @braincs, I don't think I did anything on my end. It just stopped happening. 🫤
