### ISSUE TITLE
Math Plus Sign is sometimes displayed differently

### ISSUE THREAD

**Issue by lucidBrot** [typora/typora-issues#3795]
Please note how in the below image in the second bullet point, some plus signs are barely readable while others are displayed as expected.

![image](https://user-images.githubusercontent.com/4920691/90636428-dea3c500-e22a-11ea-86de-8e1925f7f9ce.png)

This difference is already visible in the preview:
![image](https://user-images.githubusercontent.com/4920691/90636477-f0856800-e22a-11ea-9664-ae1acb723b59.png)

It does not seem to have to do with spacing around the `+` and also not with whether the surrounding characters are numbers or letters.

The complete source of that file is
```markdown
$\phi(pq) = (p-1)(q-1) = pq - q - p +1 = n+1-(p+q)$


```

Further testing makes it seem like it has to do with the kind of letter that precedes the plus sign. Which is very weird. See the last two lines here:
![image](https://user-images.githubusercontent.com/4920691/90636967-a8b31080-e22b-11ea-928a-271b3580b4ec.png)
The source of this screenshot is
```markdown
$\phi(pq) = (p-1)(q-1) = pq - q - p +1 = n+1-(p+q)$

$(p+q)$

$(p+1)$

$(n+1)$

$n+1$

$n+1-(p+q)$

$= n+1-(p+q)$

$=+1$

$= +1$

$= n+1$

$= p+1$

```

### Version
`version 0.9.93 (beta)` on Windows 10

### Expected Behaviour
Display the plus sign in the better readable version at all times.

### Other Notes
It seems to me like the `1` is sometimes of a different width, but that could also be imagined and is not relevant.

**Comment by lucidBrot** [comment]
On linux `version 0.9.93 (beta)`, everything looks like it should:
![image](https://user-images.githubusercontent.com/4920691/90637818-c46ae680-e22c-11ea-8206-5370194cbae7.png)

**Comment by abnerlee** [comment]
duplicate with #3449

**Comment by lucidBrot** [comment]
Thanks for finding the duplicate! But that duplicate is closed since May - so why is the problem still there?

You mentioned
> It seems a font issue, what's your screen DPI?
> Will zoom out https://www.mathjax.org/#demo makes "+" sign enough for you?

But that demo looks correct in my browser no matter how much I zoom. And I can't find any "zoom" settings in the preferences - where would they be?
