### ISSUE TITLE
Changing zoom level on images with no spacing between causes incorrect selection and modification

### ISSUE THREAD

**Issue by jaxfrank** [typora/typora-issues#3798]
When I right click the second image and change the zoom level both images become selected and zoom level is changed incorrectly. I have placed the before and after files below. 

Before:

Welcome to Typora!

***

## This is only a test

* [test.md](test.md) 
* 

This is a **desktop** app!

<img src="home.assets/latest" alt="Turret | WARFRAME Wiki | Fandom" /><img src="home.assets/220px-Maille-Braize-canon.jpg" alt="Gun turret - Wikipedia"  />

After:

Welcome to Typora!

***

## This is only a test

* [test.md](test.md) 
* 

This is a **desktop** app!

<img src="home.assets/latest" alt="Turret | WARFRAME Wiki | Fandom" style="zoom:33%;"  /><img src="home.assets/220px-Maille-Braize-canon.jpg" alt="Gun turret - Wikipedia" /><img src="home.assets/latest" alt="Turret | WARFRAME Wiki | Fandom" style="zoom:33%;"  /><img src="home.assets/220px-Maille-Braize-canon.jpg" alt="Gun turret - Wikipedia" />

**Comment by abnerlee** [comment]
should be fixed in new release
