### ISSUE TITLE
Home/End confusing behaviour

### ISSUE THREAD

**Issue by andreasciamanna** [typora/typora-issues#3799]
I'm using an extended keyboard (the one with the NumPad).

In all editors, IDE and anywhere I can write text, the End key moves the cursor at the end of the line.
Similarly, Home moves at the end of the line.

Nothing like that happens with Typora.

Home and End keys move respectively to the top and end of the file.
They behave exactly like the PageUp/PageDown keys.

Can this be fixed?

I'm so used to these keys that I keep making mistakes when using Typora.

**Comment by abnerlee** [comment]
In my test the home/end key behavior in TextEditor.app or XCode.app or Chome.app, I think that is the default behavior for macOS apps, could you confirm if it is same in your TextEditor.app?

**Comment by abnerlee** [comment]
relates #3152

**Comment by andreasciamanna** [comment]
To be clear, I'm talking about these keys:  
![image](https://user-images.githubusercontent.com/181780/91137856-040f5380-e6af-11ea-9720-721eb5820061.png)

Or, in the Italian layout (which is the one I own):  
![image](https://user-images.githubusercontent.com/181780/91138048-23a67c00-e6af-11ea-8eae-f3233af0f9e7.png)

To answer your question, TextEdit is the only editor I never use :)

I've just tried though, and `Home`/`End` and `Page Up`/`Page Down` only work as pagination keys, and only if the text is long enough to justify their use.

I've even tried with xCode, and I get the same behaviour as in TextEdit.

When using other editors (e.g. Atom, but also IDEs such as IntelliJ IDEA):
- `Home`/`End` move the cursor at the beginning and end of the current line respectively
- `Page Up`/`Page Down` move the cursor at the beginning and end of the file respectively

I think an editor like Typora can use these keys better than macOS does.  
More precisely, it could use them for the purpose they were born, which is the one used by most of the editors out there.

#3152, though most likely related, doesn't cover [keyboards with numeric keypad](https://www.apple.com/shop/product/MQ052LL/A/magic-keyboard-with-numeric-keypad-us-english-silver) (which also include the keys in my screenshot).  
Most likely it's because these keyboard layouts, even if produced and sold by Apple, are not very common anymore, especially when it comes to Mac.  
And yet, some users prefer this layout and buy these keyboards to make their life easier.

At least, as long as the software they use supports them.

**Comment by KubaO** [comment]
Apple standard behavior is for Home and End to move to beginning and end of the document. Some software, trying to be "helpful", breaks this behavior. On Mac, start/end-of-line requires the use of a modifier and becomes second nature. Personally, when I'm on Mac, I expect ⌘→ and ⌘← to do this job, and it's baffling when an application behaves otherwise.

Maybe, somehow, people use Macs and don't know about this platform-specific convention? MacOS is not a PC. Just because Home and End do something on Windows, doesn't mean they must do the same on Mac :)

**Comment by andreasciamanna** [comment]
The wrongest statement in your lecture is this one: "On Mac, start/end-of-line requires the use of a modifier combo and becomes second nature of anyone seriously using the platform.".

You are assuming who works on a Mac, never works on Linux or Windows. And you assume the other way around also applies.
That's far from the thruth.
Yes there are people who stick to one platform and never move from there.

Personally, I wrote code for products which run on web servers. Any web server, in any OS.
I Mac, Linux and sometimes, Windows machines.
Having to get userd to different shortcuts for the same action, depending on the OS, is Impossible and time consuming.
Not even giving the possibility to at least customize these shortcuts, means to me you are not interested in your users, but probably in something else which isn't clear to me yet.

Is not a problem.
I liked
