### ISSUE TITLE
Feature request: import and export as pandoc markdown and AST

### ISSUE THREAD

**Issue by ickc** [typora/typora-issues#380]
From the [FAQ](http://support.typora.io/Install-and-Use-Pandoc/):

> ## Which file types can be imported or exported by typora ?
> 
> Import supports file with extesion: .docx, .latex, .tex, .ltx, .rst, .rest, .org, .wiki, .dokuwiki, .textile, .opml, .epub.
> 
> Export supports file formats of: HTML, PDF (these two does not need typora), Docx, odt, rtf, Epub, LaTeX, Media Wiki.
> 
> Pandoc should support more file types which typora did not integrate, detailed info is here.
> ## What’s the difference between exporting by typora and exporting by using pandoc from command line ?
> 
> Exporting by typora is also powered by Pandoc, yet typora will not convert directly from markdown to target file type, instead, it converts to an inner format pandoc can read and then write as target file type, so, in detail:
> 
> If you run pandoc from command line, then you need to specify its markdown parser from (pandoc Markdown, CommonMark, PHP Markdown Extra, GitHub-Flavored Markdown), while exporting using typora, typora will pass its inner AST to pandoc for file conversion. In other words, the format of blocks or inline elements in exported output will always be consistent as what you see in typora and exported HTML/PDF. Yet, the styling maybe different.
> Some markdown syntax invented by pandoc Markdown, like citations, are not supported when you exporting from typora, since only markdown syntax typora support will be correctly exported. But we may support more extended markdown syntax in future.
> If you use typora for exporting, then[TOC] will be correctly exported for all file types. Highlight and underline will be supported for LaTeX, rtf, Epub, wiki formats and sometimes Docx. Yet, they are only supported for HTML based file formats in raw Pandoc. Other block and inline elements is basically both supported by raw pandoc and typora+pandoc.

This is indeed a very interesting design, probably because of GPL. Anyway, personally, the only reason I cannot use Typora is because I use pandoc markdown.

Typora is interesting to me exactly because it uses the pandoc's AST hence can have a tight integration with pandoc. But then the markdown typora uses is not exactly pandoc's markdown. I don't know exactly how much different the syntax are, but from the quote above, it seems there's no official support that typora's markdown output can be parsed successfully by pandoc.

Hence, a feature request: may be you should provide both an import and export option for pandoc markdown. And in addition to that, probably an import and export option to the AST is useful as well. This way, typora user do not need to worry about portability.

By the way, I think there's a typo: `HTML, PDF (these two does not need typora)` should read `HTML, PDF (these two does not need pandoc)`.

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/169

we do support export to pandoc native on macOS, by open export menu with `command` key pressesd
