### ISSUE TITLE
Page numbers on pdf export

### ISSUE THREAD

**Issue by khakhalin** [typora/typora-issues#3803]
I am trying to modify the [paper theme](https://theme.typora.io/theme/paper/), trying to make it look maximally latex-style (hoping to bypass latex altogether for short papers), and somehow I cannot make page numbers to work.

I added a `@media print {...` clause, and it definitely works, as I can use it to change page size, fine-tune margins, and those rules for introducing or avoiding breaks before and after h2 titles (by default the current version of `paper` theme starts each h2 from a new page that was too much for me). So by itself, the `@media print {...` clause definitely gets implemented.

However when I try to follow advice on adding page numbers in CSS (like [this one](https://www.w3.org/Style/2013/paged-media-tasks) for example), it just gets ignored. I type something like that:

```css
      @page {
		@top-right {
			content: "Page " counter(page) " of " counter(pages);
			border-bottom: .25pt solid #666;
		}
		
		size: letter;
		margin: 1in .5in 1in .5in;
	}
```

The `size` part gets parsed (the page size changes), and so does the `margin`, but the `@top-right{...` clause seems to be ignored. At least I couldn't make it produce anything - a static text, a border, a different `margin` - nothing. I tried to specify `@page:left` and `@page:right` separately, as some manuals suggest, but it also didn't change anything. I tried to add a bottom page number instead of top. I tried to make margins of the page and of the `@top-right` element larger or smaller - nothing.

Is it a different version of css? Or any other ideas how to fix it?

Alternatively, if you know a theme that _definitely adds_ page numbers on PDF export, could you please tell me the name? I could try to hack it towards the latex paper aesthetics, instead of going the other way around...

Thanks!!

Info on versions: Windows 10, version for windows, 0.9.93

**Comment by abnerlee** [comment]
> Does it mean that there's no workaround for automated page numbers yet, even a painful one?

Currently yes, but we will support that
