### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by jpmv27** [typora/typora-issues#3806]
Using Typora 0.9.93 on Windows 10.0.18363.

Please refer to attached demo.md file (renamed to demo.md.txt for upload).

Issue 1:
Let's say I have the file open as per issue1.png and the cursor is positioned
to the left of the 's' in "seventeen". If I now move the cursor down (with the
down arrow), the cursor disappears and no scrolling happens.

Issue 2:
Now let's say I have the same file open as per issue2-before.png and the
cursor is positioned to the left of the 'n' in "nineteen". If I move the cursor
down, the cursor disappears and the file scrolls UP, per issue2-after.png.

This is very disconcerting and makes it challenging to navigate through
a long list.

[demo.md.txt](https://github.com/typora/typora-issues/files/5114139/demo.md.txt)
![issue1](https://user-images.githubusercontent.com/1688977/90981661-6130cb00-e530-11ea-9183-ecb7aea2d4dc.png)
![issue2-after](https://user-images.githubusercontent.com/1688977/90981662-61c96180-e530-11ea-85be-18db2cd084b4.png)
![issue2-before](https://user-images.githubusercontent.com/1688977/90981663-61c96180-e530-11ea-85d0-cf5793ce8b6d.png)

**Comment by abnerlee** [comment]
should be fixed

**Comment by jpmv27** [comment]
Fix confirmed in 0.9.95. Thanks!
