### ISSUE TITLE
Picgo-core upload command error

### ISSUE THREAD

**Issue by Raikyou** [typora/typora-issues#3807]
typora 0.9.93(beta)
OS windows10 1909

When I tried the test uploader in image following the Picgo-core(command-line) instruction,  it turns out  `@chcp 65001 >nul & cmd /d/s/c function(){return p}\picgo\win64\picgo.exe u`. Seeking for other's result, it should be the picgo path instead of `function(){return p}` here. I installed picgo from typora downloading and config it well.
![image](https://user-images.githubusercontent.com/13917879/91106905-85aeb380-e6a6-11ea-8e42-e8af89e23ebb.png)
![image](https://user-images.githubusercontent.com/13917879/91107250-66645600-e6a7-11ea-9be2-2f1d28defbbe.png)

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by YioEagle** [comment]
I met this problem too. I update my Typora to 0.9.96 and this issue have been solved.
