### ISSUE TITLE
Incorrect rendering of static methods in Mermaid class diagrams

### ISSUE THREAD

**Issue by fortym2** [typora/typora-issues#3808]
Static methods (`$` at the end) in Mermaid class diagrams are not underlined when there is a parameter with type.

```mermaid
classDiagram

class RendersGood {
	+method()
	+staticMethod()$ 
}

class RendersBad {
	+method()
	+staticMethod(param: int)$ 
}
```

This is a comparison between Typora and [Mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor/).

|Typora|Mermaid live editor|
|---|---|
|![typora](https://user-images.githubusercontent.com/30431538/91157455-a4707280-e6c5-11ea-9438-d74193184997.png)|![mermaid](https://user-images.githubusercontent.com/30431538/91157548-c1a54100-e6c5-11ea-8671-44a663239c1f.png)|

Probably related to #1661.

**Comment by abnerlee** [comment]
should be fixed
