### ISSUE TITLE
mermaid chart shows abnormal

### ISSUE THREAD

**Issue by Paul-Deng** [typora/typora-issues#3810]
![image](https://user-images.githubusercontent.com/29682349/91275354-9fd5b800-e7b2-11ea-9c8a-393157179953.png)

Sorry, The last word can't show normally

**Comment by jklm264** [comment]
I am currently having the same problem on Mac only; version 0.9.34.2. This issue affects all types of graphs LR, TD, etc.

**Comment by hysencn** [comment]
Chinese is showing a lot of problems, the last two versions are the same.
<img width="300" alt="Screenshot 2020-09-02 at 8 27 56 PM" src="https://user-images.githubusercontent.com/60783595/91981446-7214e400-ed5b-11ea-81a2-3e09d2a2c05b.png">

**Comment by jklm264** [comment]
Hi there @abnerlee, you closed this issue as well as the link issue however a fix has not been implemented yet to my knowledge.

For those wanting a partial workaround, you can just add `<space>.` to the end of each label. However, this only fixes the width issue. If you have a character that goes below the line (e.g. a `y`) it will still be cut off.

**Comment by YatesyTea** [comment]
Hi @abnerlee , thank you for your hard work on this app and patience with large amounts of requests.

Have had inconsistent behaviour with this on Windows 10, Typora ver 0.9.96

It's managed to render when I activate typewriter mode, focus mode, and copied the mermaid contents into and existing code fence, then set the language.
However the issue of the bottom parts of characters that go below a line on lined paper is still there.
I will test further to see which part is causing this to try and aid the issue later on today.

![image](https://user-images.githubusercontent.com/39750168/100360443-dd83f000-2ff0-11eb-9506-9885ed76e6e0.png)

Thanks,
YatesyTea

**Comment by abnerlee** [comment]
should be fixed
