### ISSUE TITLE
Right click on image can't work well

### ISSUE THREAD

**Issue by liuhao326** [typora/typora-issues#3812]
version 0. 9. 93 (beta)

Right click menu on image can't work well when I selected some texts, especially when I selected the image text like `<img src="book_pic/epub_30181978_94" style="zoom:67%;" />` or `![pic](book_pic/epub_30181978_94)`.

Specifically, when I right-click on another image after zooming an image by right-click, right click menu will disappear after appearing for a short time. 

You can test by file below. 

[test.zip](https://github.com/typora/typora-issues/files/5130426/test.zip)

 It doesn't always happen, so need to test it more than a few times.

**Comment by abnerlee** [comment]
should be fixed
