### ISSUE TITLE
Cannot edit and save files mapped with symlink 

### ISSUE THREAD

**Issue by manasmbellani** [typora/typora-issues#3813]
I am using `v0.9.9.34.2 (4509)` of Typora on Mac OS X `10.15.6 (19G2021)`. I have created a symlink to an existing local .md file on the disk, and I am attempting to edit the .md file by opening it in Typora through the symlink. 

While I can open the file with latest contents, I get the following error when I edit, and attempt to save it.: -
```
The document couldn't be saved. The file does not exist.
```

The .md file does not get my editions.

**Comment by manasmbellani** [comment]
This is similar to issue #3643 , although I am getting a slightly different error provided above.

**Comment by abnerlee** [comment]
symbolic files are not supported yet, tracking in #3643
