### ISSUE TITLE
Image won't show up with "." on looooooong path

### ISSUE THREAD

**Issue by huangzesen** [typora/typora-issues#3814]
Images with following path have issues showing up:
on MacOS version 0.9.9.29.2

 ! [] (/Users/huangzesen/Downloads/newtests/fast_mode/va2cs_05/90/figure/BU/xcut/000.png) will show up
 ! [] (/Users/huangzesen/Downloads/newtests/fast_mode/va2cs_0.5/90/figure/BU/xcut/000.png) will NOT show up

This issue can NOT be reproduced using short path like:
 ! [] (/Users/huangzesen/a.b/000.png)
 ! [] (/Users/huangzesen/ab/000.png)
Both shows up

**Comment by abnerlee** [comment]
Would you try with 0.9.9.35.2? Since I'm not able to reproduce this issue
