### ISSUE TITLE
Search bar partially hidden when multiple tabs are opened. 

### ISSUE THREAD

**Issue by LazaroFilm** [typora/typora-issues#3816]
version 0.9.9.35
typing cmd+F to get the search bar, but it is partially hidden by the tabs if you have multiple documents opened in one window. 

<img width="961" alt="Screen Shot 2020-08-29 at 3 15 18 PM" src="https://user-images.githubusercontent.com/18351100/91644501-8f1f7f00-ea0a-11ea-9d6c-46a8a2535716.png">

**Comment by abnerlee** [comment]
should be fixed
