### ISSUE TITLE
Filter "" when creating folder for images

### ISSUE THREAD

**Issue by SneakBug8** [typora/typora-issues#3819]
When you copy-paste image to the file with setting of autocopy to folder with the name of the file, could Typora possibly filter out " and ' from folder name cuz later it can't load images from path with "" in them. But the markdown file with "" in name works perfectly. For example if you have file '"Donald Trump" interview.md' it would place images in folder 'Donald Trump interview', not '"Donald Trump" interview' so it would fail to load an image a second later.

**Comment by abnerlee** [comment]
Which OS and Typora version? It works on macOS in my test
