### ISSUE TITLE
Keyboard Shortcut For Export

### ISSUE THREAD

**Issue by examinedliving** [typora/typora-issues#382]
I wouldn't mind creating this myself, but after digging through the source code, I couldn't find any clear list of shortcut commands that were available.

**Point blank:**  Is there a command that can be applied to a keyboard shortcut that will allow exporting the file  in a certain format ( I'm looking for unstyled html)?  What is it?  If not - can we have one of those?

I found `exportHTMLPlain` in `/resources/app/app/window/frames.js` but the file was too big for me to figure  out if that could be referenced from a bindable command; and when I tried `exportHTMLPlain` as the command, nothing happened.

**Comment by abnerlee** [comment]
see http://support.typora.io/Custom-Key-Binding/

**Comment by examinedliving** [comment]
This doesn't seem to answer my question.  What is the command to bind the keystroke to?  Is it `File Export HTML (Without Styles)"?  I've tried a number of variations, and nothing works.

**Comment by abnerlee** [comment]
It is the name of the menu item. like "File Export HTML (Without Styles)"

**Comment by examinedliving** [comment]
@abnerlee It doesn't seem to work.  Windows 7 64 bit.  Typora 9.21

**Comment by vertesy** [comment]
@abnerlee Maybe provide the exact example on the support page - I guess most people want a hotkey for export

You can use the image below

<img width="670" alt="screen shot 2017-09-14 at 17 58 23" src="https://user-images.githubusercontent.com/5101911/30440277-5e9284dc-9976-11e7-94b7-7b9e6093ebae.png">



@abnerlee Also there is a typo on that page "always" -> Always
`Then Command+Shift+P will be the shortcut key for menu command “always On Top”`

@examinedliving Works on OS X El Caprtain, Version  (0.9.9.10.6)

**Comment by Mpic** [comment]
> 
> 
> @abnerlee Maybe provide the exact example on the support page - I guess most people want a hotkey for export
> 
> You can use the image below
> 
> <img alt="screen shot 2017-09-14 at 17 58 23" width="670" src="https://user-images.githubusercontent.com/5101911/30440277-5e9284dc-9976-11e7-94b7-7b9e6093ebae.png">
> 
> @abnerlee Also there is a typo on that page "always" -> Always
> `Then Command+Shift+P will be the shortcut key for menu command “always On Top”`
> 
> @examinedliving Works on OS X El Caprtain, Version (0.9.9.10.6)

Does not work on Windows : I tried  
```json
"keyBinding": {
    // for example: 
    // "Always on Top": "Ctrl+Shift+P"
    "PDF": "Ctrl+Shift+E"
  }
```

**Comment by amshuo** [comment]
> > @abnerlee Maybe provide the exact example on the support page - I guess most people want a hotkey for export
> > You can use the image below
> > <img alt="screen shot 2017-09-14 at 17 58 23" width="670" src="https://user-images.githubusercontent.com/5101911/30440277-5e9284dc-9976-11e7-94b7-7b9e6093ebae.png">
> > @abnerlee Also there is a typo on that page "always" -> Always
> > `Then Command+Shift+P will be the shortcut key for menu command “always On Top”`
> > @examinedliving Works on OS X El Caprtain, Version (0.9.9.10.6)
> 
> Does not work on Windows : I tried
> 
> ```
> "keyBinding": {
>     // for example: 
>     // "Always on Top": "Ctrl+Shift+P"
>     "PDF": "Ctrl+Shift+E"
>   }
> ```

when you run in windows, it is just key conflict. 
try below ↓↓↓

```json
"keyBinding": {
     // for example: 
     // "Always on Top": "Ctrl+Shift+P"
     "PDF": "Alt+Ctrl+Shift+E"
}
```

my typora version is 0.10.11(beta)
