### ISSUE TITLE
With folder view, Outline does not populate

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#3820]
Would it be possible to get Outline view to work with a folder open?
![image](https://user-images.githubusercontent.com/58857646/91739743-5acdcf00-eb80-11ea-8e43-4fcf1d61ad53.png)

Here, Files view works well:

![image](https://user-images.githubusercontent.com/58857646/91739812-6d480880-eb80-11ea-8b9c-9554640d4275.png)

**Comment by abnerlee** [comment]
Outline only works for file, not for folder

**Comment by coinzdude** [comment]
@abnerlee Could I make this a feature request?
