### ISSUE TITLE
UX/UI confusion for global search

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#3821]
With the folder view, it's not obvious that wheel-mouse scroll up will expose the global search.  Can this be made permanent, or dismissable with a checkbox defaulting to always open?

Before wheel-mouse scroll up

![image](https://user-images.githubusercontent.com/58857646/91739982-abddc300-eb80-11ea-8330-e98f43d1008a.png)

After scroll up

![image](https://user-images.githubusercontent.com/58857646/91740010-b5672b00-eb80-11ea-8f42-1aaa1a012638.png)

**Comment by abnerlee** [comment]
It's not hidden in "scroll-up", there are menus to open "global search".
