### ISSUE TITLE
Ubuntu copy image error

### ISSUE THREAD

**Issue by ma-1ming** [typora/typora-issues#3823]
![image](https://user-images.githubusercontent.com/40572247/91927683-bb8a1280-ed0c-11ea-9384-b75b65b3d493.png)
Different pictures are saved the same！
![image](https://user-images.githubusercontent.com/40572247/91927755-e6746680-ed0c-11ea-807e-d4ecdf616eab.png)

**Comment by abnerlee** [comment]
Could you provide steps to reproduce?
