### ISSUE TITLE
East Asian (Chinese)text display error

### ISSUE THREAD

**Issue by hysencn** [typora/typora-issues#3825]
In typora, when you select a piece of Chinese text, the cursor does not appear between two characters, 
but in the character itself.  
I changed the default theme for all the official ones, same problem.

See the diagram below.
<img width="300" alt="Screenshot 2020-09-02 at 8 27 56 PM" src="https://user-images.githubusercontent.com/60783595/91981063-d7b4a080-ed5a-11ea-9af1-97d7cccf0b2f.png">

**Comment by abnerlee** [comment]
What's the OS / Typora version? Which theme did you use, and how to reproduce this?
