### ISSUE TITLE
How can i set 'shift+tab' like vscode

### ISSUE THREAD

**Issue by JohanChane** [typora/typora-issues#3826]
When i moved my txt note to typora, it is too hard for me keeping them aligned.

for example:

```
the text is:
    a line
    	a line
            a line
    a line
    	a line
                
typora 'shift+tab':
*type tab first*
a line
a line
a line
a line
a line
        
vscode 'shift+tab':
*type tab first*
a line
a line
    a line
a line
a line
    	
*type tab secondly*
a line
a line
    a line
a line
a line
```

**Comment by abnerlee** [comment]
"Tab" in markdown will change the text into code block. So supporting Tab / Shift + Tab is actually making users to switch between paragraph and code block, which is quite confusing.
