### ISSUE TITLE
Spell check error for Latin abbreviations like "e.g."

### ISSUE THREAD

**Issue by ycwang427** [typora/typora-issues#3828]
A minor problem: Typora seems not to recognize abbreviations like "e.g.". 
![image](https://user-images.githubusercontent.com/53824424/92101059-258ae080-ee0f-11ea-97bf-9fec42482d1f.png)
And it wants to replace things like "e.g" to "e.g.", and the original "e.g." becomes "e.g..", and "e.g...", etc.
![image](https://user-images.githubusercontent.com/53824424/92101458-bcf03380-ee0f-11ea-8493-f01f705abd5d.png)
![image](https://user-images.githubusercontent.com/53824424/92101847-4d2e7880-ee10-11ea-9806-e8eef98654eb.png)

**Comment by abnerlee** [comment]
#3440
