### ISSUE TITLE
LaTeX Cross Referencing Colour

### ISSUE THREAD

**Issue by Maselko** [typora/typora-issues#3829]
Version 0.9.9.35

Is it possible to change the colours of `$\label{}$`? At the moment it is in the colour of `#0000FF` and it would be lovely if you can change the default colour to be the same as the link colour. Also, the link is still a bit laggy...

As you can see on the pic below, it is quite difficult to read.

<img width="640" alt="Zrzut ekranu 2020-09-3 o 12 35 45" src="https://user-images.githubusercontent.com/47721906/92110048-0164da80-ede2-11ea-9f8d-f8d5e25231af.png">

**Comment by abnerlee** [comment]
should be fixed
