### ISSUE TITLE
Source mode formatting buggy after a quote block with display math

### ISSUE THREAD

**Issue by kenzheng99** [typora/typora-issues#3831]
Noticed an issue with the source mode syntax highlighting/formatting after adding a quote block with a nested math block within. In source mode, all lines after the quote block are formatted in blue monospace font (like in a code block), even though I don't have any code blocks in my document. Display mode looks fine to me. 

Display Mode:
![Screen Shot 2020-09-03 at 3 09 00 PM](https://user-images.githubusercontent.com/6669891/92156772-7abaf800-edf7-11ea-84b0-b0bfe8f96020.png)

Source Mode:
![Screen Shot 2020-09-03 at 3 14 00 PM](https://user-images.githubusercontent.com/6669891/92157258-2d8b5600-edf8-11ea-91ab-5f397b3c3a4d.png)

I'm pretty new to Typora and Markdown in general, so please let me know if this is an issue with my markdown and not with Typora!

Specs:
macOS version 10.15.5
Typora beta version 0.9.9.35 (4693)

**Comment by abnerlee** [comment]
#1638
