### ISSUE TITLE
[Feature]：Support copy online images which is in HTML element to local fold

### ISSUE THREAD

**Issue by liuhao326** [typora/typora-issues#3835]
After choosing "Copy image to custom folder", I found it will not copy online images to local fold when I paste text like `<img src="https://res.weread.qq.com/wrepub/epub_22987517_224" alt=""/>`, so can support copy online images which is in HTML element  to local fold?

**Comment by abnerlee** [comment]
do you enable that for online images?

**Comment by liuhao326** [comment]
Yes, I enabled the choice "Apply above rules to online images", and it doesn't work.

![image](https://user-images.githubusercontent.com/51501079/92746536-f3045900-f3b5-11ea-8b90-a3c69ff50f96.png)
