### ISSUE TITLE
JavaScript error on opening a file under Windows

### ISSUE THREAD

**Issue by rpopov** [typora/typora-issues#3836]
version: 0.9.95 (beta)
OS: Windows 10, 64bit

I have a markdown file opened. In Windows Explorer I double clicked another .md file to open it. The following error message appeared:
![image](https://user-images.githubusercontent.com/7579924/92309660-227b2600-efb0-11ea-914e-bd86ce57a2af.png)

Note: there were no such errors with the previous versions. This seems to be some new behavior or regression.

**Comment by arthurjosse** [comment]
Exactly the same for me.

**Comment by bigginhill** [comment]
And me

**Comment by gcs303** [comment]
I get the same error dialog with 0.9.96 (beta) but I also got another dialog instead for one of the double-clicks, so maybe they are related:
![UncaughtException](https://user-images.githubusercontent.com/40226143/101364613-c5259800-3870-11eb-803b-9c473334f1f2.png)
It seems Typora also thinks it should go into a "write" mode, but a double-click means to open for "read" by default.

**Comment by abnerlee** [comment]
Does this still happens in latest version?
