### ISSUE TITLE
Color leakage when export md to pdf files

### ISSUE THREAD

**Issue by ifsheldon** [typora/typora-issues#3837]
My typora version is 0.9.95(beta)
And my in-use theme is [misty v1.0 alpha 2](https://github.com/etigerstudio/typora-misty-theme/releases/tag/v1.0-alpha.2).
When I edit my md files, everything seems perfect, but when I export md files to pdf files, color leakage of h2 headers happens. 
To reproduce this issue is easy, type this in typora using the misty theme and export it as pdf file.
```markdown
# h1

## h2

some contents

some contents

some contents
```
We'll see the color of the vertical bar of the h2 header will exceed the boundary and leak to contents below.
Weird is that exporting to html files seems perfect, but after opening the html file in Chrome and use `print` of Chrome to convert the html file to pdf, the converted pdf shows the same leakage issue.

**Comment by abnerlee** [comment]
should be fixed
