### ISSUE TITLE
when I screenshot in wechat runing on linux wine , I can't paste it into typora #946

### ISSUE THREAD

**Issue by peiyuefeng** [typora/typora-issues#3838]
I refered the issue: https://github.com/typora/typora-issues/issues/946,  but it cant resolve my problem.

the key is :
screenshot in wechat (running on wine on linux)

i suspect it's the problem of image format in clipboard,  
https://github.com/typora/typora-issues/issues/720 

but when i use wechat to save image, it's always use jpg, not webP.

thanks for help.
typora is good tool to help me a lot.

**Comment by abnerlee** [comment]
Do you have extra setting about insert images?
Does screenshot in other app outside wine works?
