### ISSUE TITLE
Batch Export or Expose command line tool to export md files

### ISSUE THREAD

**Issue by xiesp** [typora/typora-issues#3839]
i really hope that Typora supports one of the following

1. Batch export all md files under a directory
2. Expose CLI exporting  tools to Users

Yes this issue is basically the same as #824, and i have read that issue and tried the methods listed there,however,none of methods worked for me.Since my md files contans lots of mathjax formulas(and may be other reasons),so after spent two days i got nothing.

then i googled and found a method in https://stackoverflow.com/questions/14899283/converting-multiple-markdown-files-with-links-to-pdf, and i tried it ,here is what i entered

```
cat *.md > all.md 
```
and i gained :

![image](https://user-images.githubusercontent.com/13922181/92447570-fa770700-f1e9-11ea-8239-f5a148a4ff1b.png)

yes , the `all.md`'s size iis 1,295kb, and use typora open it require more then 20 minutes....worse than this, after waiting 20 minutes,i clicked `export` and Typora reported `export error` without other messages...(exporting single md file was successful)

The last way  i tried is to use pandoc .Pandoc was already installed,so i intalled MikTex, and used the following commands to export

```
pandoc all.md -o result.pdf --from markdown  -V CJKmainfont="PingFang SC" --pdf-engine=xelatex
```
but there are so many problems,including fonts problem and mathjax formulas,two of the formulas problems are 

```
1:! Package amsmath Error: \begin{aligned} allowed only in math mode.
2:! LaTeX Error: Command \ttfamily invalid in math mode.
```
and more.

---

Finally i realize that somethings different between munally using pandoc to export and using Typora to export,then i read the `Install and use Pandoc`  from typora's Help Menu and found the following:

```
...while exporting using typora, typora will pass its inner AST to pandoc for file conversion......
```

then i found a latex template in [here](https://github.com/Wandmalfarbe/pandoc-latex-template) and used the following command:

```
pandoc all.md -o result.pdf --from markdown  -V CJKmainfont="PingFang SC" --pdf-engine=xelatex --template eisvogel --listings
```

but it did not  work either.

---

thanks for watching my issue,i really do not have any other method and feel despaired,could you please supports one of the features i listed in the top of this issues,or provides any  feasible solutions for me .Thanks...

**Comment by abnerlee** [comment]
duplicate with #824
