### ISSUE TITLE
PDF export breaks internal link

### ISSUE THREAD

**Issue by vlorcy** [typora/typora-issues#384]
When inserting an internal link in a document, I am able to follow the link using cmd+click in the Typora window. They work fine when exporting to HTML. However, when exporting to PDF the internal links are broken.

I tried using both following syntax, neither seems to be working:

`# top`
`[link to top](#top)`

`<a name="top"></a>`
`<a href="#top">link to top</a>`

OS: OS X El Capitan 10.11.6
Version: 0.9.9.8.2 (beta)

**Comment by WWWXXX222** [comment]
Same here with version 0.9.9.8.2.

**Comment by duncanmapes** [comment]
This is a problem for me too. Please fix ASAP 👍

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by duncanmapes** [comment]
which version exactly?

**Comment by abnerlee** [comment]
v0.9.9.8.4

**Comment by WWWXXX222** [comment]
Thanks a lot for your work.

**Comment by duncanmapes** [comment]
thanks

**Comment by onury** [comment]
This seems to be broken in version 0.9.9.25.3 (2897)

**Comment by danthegoodman1** [comment]
Still broken

**Comment by NicolasPedro** [comment]
I use the latest version which Typora says is Version 0.9.9.28 (3403)
The links still don't work when I export a PDF.

**Comment by LiukDiihMrau** [comment]
Some problem. And I wanna know how to create a non-header internal link?
<span id="jump">any text</span>
[jump to my text](#jump)
would not work (except exporting to HTML).

**Comment by frego** [comment]
This is still the case with version 0.9.9.29.2.

**Comment by abnerlee** [comment]
#2941

**Comment by tomchon** [comment]
This is a problem for me with Version 0.11.5 (5648) , "#" will be escaped to "%23"
Please fix ASAP 👍
