### ISSUE TITLE
Bullet point bug

### ISSUE THREAD

**Issue by Coderdude112** [typora/typora-issues#3840]
After updating to the latest version of Typora (9.0.95) I noticed that Typora keeps resetting bullet points. Also, I am using Typora on Windows. 
Here is what it should look like:
![What the bullet points should be](https://user-images.githubusercontent.com/47407549/92667415-1b625980-f2c9-11ea-9ac7-fe6da1ec7cc0.png)
But after a little while this is what Typora shows:
![Incorrecy bullet points](https://user-images.githubusercontent.com/47407549/92667416-1bfaf000-f2c9-11ea-84bd-056af49c45ad.png)

Please let me know if you need more information. Thanks

**Comment by abnerlee** [comment]
Possible to send us the sample file that will be rendered as img2 after opening it?

**Comment by Coderdude112** [comment]
Are you asking me to attach the file or export it as an image?

**Comment by Coderdude112** [comment]
There is also a bug sometimes when trying to fix them. Didn't know how to explain it so I took a video. Check out this [Bullet point bug.zip](https://github.com/typora/typora-issues/files/5234493/Bullet.point.bug.zip).

Thanks

**Comment by abnerlee** [comment]
Sorry for late reply.

> Are you asking me to attach the file

The file would be helpful

> There is also a bug sometimes when trying to fix them. 

Also, could you provide the file for this bug? (<hi@typora.io>)

And does they happen in 0.9.96?

**Comment by Coderdude112** [comment]
> And does they happen in 0.9.96?
I haven't observed this bug in 0.9.96 but will comment on this post if it does. 
I have also emailed the file that had the bug to [hi@typora.io](mailto:hi@typora.io)
