### ISSUE TITLE
Option to define image markdown/markup syntax on add or upload

### ISSUE THREAD

**Issue by shane-nike** [typora/typora-issues#3842]
First, thanks for a wonderful piece of software. I use Typora daily and it's a joy to use.

I have a couple of use cases for which one would require a new feature of Typora:

1. I use Typora to edit README.md as part of a project in which I'd like to keep the current behavior of rendering a markdown image and copy the image to a relative folder.
2. I use Typora to edit blog posts for which I'd like to change the behavior of how the image is rendered.

Based on the existence of a property in frontmatter (in the case of a blog post), I'd like to define a template or path to a template to render the image as shown below. This enables me to use Typora in both use cases outlined in 1 and 2 above without needing to change preferences when switching usage context (README.md versus blog post).

For 2 above, the behavior I'd like is the following:
* Drag and drop a local image to the document in Typora.
* The image gets uploaded to a 3rd party service which is nicely handled by the option to run a custom script in the preferences.
* The rendered markup (not markdown in this case), would look something like the following:

```
<figure>
  <img src="/path/to/image">
  <figurecaption>some caption</figurecaption>
</figure>
```

I'm happy to provide more clarity or answers to follow-up questions.

**Comment by abnerlee** [comment]
I think the image "template" can be covered by #1433, also relates #249
