### ISSUE TITLE
Export feature creates file with just a blank page

### ISSUE THREAD

**Issue by domi-dot-exe** [typora/typora-issues#3844]
Hi, I'm using Typora Version 0.9.9.35 (4693) with GitHub theme, on MacOs Mojave 10.14.6. 
Every time I try to export a document, usually it's just text plus some latex (both inline and block) Typora returns a 1 white page pdf file (also  for html), even tho my file has more than 2000 words so should be longer than 1 page.. 
It worked flawlessly with older versions. 
Hope you'll get the change to fix it. 
Thanks

**Comment by abnerlee** [comment]
Does this still happens for latest version? If so, could you send us <hi@typora.io> a sample file?
