### ISSUE TITLE
Bug on Chinese Heading & Bold Text

### ISSUE THREAD

**Issue by KnowsCount** [typora/typora-issues#3845]
- [x] Newest version (Typora Beta 0.9.9.35.2)

---

Cheers for solving the pdf export issues with third party themes... For once I thought it was problem with my code. However There is a small problem with pdf in this newest version, alas.
It is with Chinese. Everything is currently okay with English, but when it comes to bolded text & heading text, it becomes something like this below: 
![img](https://ftp.bmp.ovh/imgs/2020/09/953a0cd62a64c1d6.png)

would you please solve this if you can in the next version of Typora? Cheers!

**Comment by abnerlee** [comment]
Which theme did you use, and what's your macOS version?

Does this happens for built-in themes?

Usually this happens for Chinese bold font missing

**Comment by KnowsCount** [comment]
O - then this would make sense. I am using a self-developed theme.
