### ISSUE TITLE
Bug: After edited and saved file, Typora can open but cann't display this file

### ISSUE THREAD

**Issue by bigbot123** [typora/typora-issues#3846]
# Version
Typora for Windows 0.9.95，also discover in 0.9.93, and still found in 0.9.96

# Problem
No matter what you input,  then save file and close Typora, and open the file again, Typora can open but cann't display this file. 
The phenomenon is Typora window is open, but nothing is display. And you can see the context after `Ctrl+/` in `source code mode`, it means **typora can read this file, but cann't render it.**

Use the *File comparison software* to find the different between the source file and the edited file, I found a UTF-8 char (and this char in Hexadecimal is `20` )  was insert to the context autoly and randomly. When backspace all discordant char which is auto insert, Typora can render the file again.

> Hope to find the reason and solve it, I truly love Typora and use it to write all my notes. But now, I afraid to use it cause of this problem.

> [source file](https://cloud.189.cn/t/RrQrmevYbyyy)  (access code:8jy1)

**Comment by abnerlee** [comment]
Hi, I can open and render the attached source file, possible to provide the file that cannot be rendered?

**Comment by bigbot123** [comment]
> Hi, I can open and render the attached source file, possible to provide the file that cannot be rendered?
here is the edited file, thank you very much @abnerlee 
[edited file](https://cloud.189.cn/t/ba67nqEfye6f)（访问码：s6bn）

**Comment by abnerlee** [comment]
should be fixed
