### ISSUE TITLE
Asterisk in code incorrectly closes italic block.

### ISSUE THREAD

**Issue by tsbertalan** [typora/typora-issues#3847]
If I type

    We have `2*2` apples.

It renders correctly as

We have `2*2` apples.

But if I type
  
    *We have `2*2` apples.*

It doesn't render as GitHub renders it (also, grep [here](https://daringfireball.net/projects/markdown/syntax) for "literal asterisk") as

*We have `2*2` apples.*

but instead the italics stops after the first 2, the multiplication asterisk disappears, and the backticks and true italic-closing asterisk are rendered directly. Something like

*We have \`2*2\` apples.*

If you escape as

    *We have `2\*2` apples.*

it no longer terminates the italic block, but both the backslash and the asterisk are rendered as code.

A workaround is to type

    *We have `2`&ast;`2` apples.*

but this breaks what should be one code block into two, which is visually noticeable.

**Comment by abnerlee** [comment]
duplicate with #3663
