### ISSUE TITLE
Inconsistent display font for math

### ISSUE THREAD

**Issue by andmoreduro** [typora/typora-issues#3848]
Symbols like \oint \oiint \oiiint are not consistent with \int \iint \iiint

Here a simple example:
![mathDisplay](https://user-images.githubusercontent.com/71203480/93023417-74293f00-f5b4-11ea-8c96-cc444941b855.png)

Instead of that, I would expect to see something like this (https://www.tuhh.de/MathJax/test/sample-dynamic.html):
![normalDisplay](https://user-images.githubusercontent.com/71203480/93023508-1ba67180-f5b5-11ea-9be1-fb359a7bbdd1.png)

This problem appears to be attached to typora itself because I tried on a Linux machine and the same happens. I don't know if this has a solution but I am happy to hear a workaround.

This is important for consistency.

**Comment by abnerlee** [comment]
In my test \oiint \oiiint is not supported by mathjax

https://github.com/mathjax/MathJax/issues/566

they seems to be supported by extensions -> https://github.com/mathjax/MathJax/pull/1810

**Comment by abnerlee** [comment]
put into #3278

**Comment by oeoa** [comment]
typora's mathjax version is too old, so it doesn't support `\oint`
