### ISSUE TITLE
Whitey's H2 border is misplaced on PDF export

### ISSUE THREAD

**Issue by jonpoveda** [typora/typora-issues#3849]
Whitey's H2 border is misplaced on PDF export, overlaying any text there.

![typora-issue-whitey](https://user-images.githubusercontent.com/16905939/93201951-2f3b0f00-f752-11ea-9c05-2879690951cd.png)

Manjaro Linux (arch)
Typora 0.9.95(beta) 
Theme: Whitey (built-in)

Proposed PR: https://github.com/typora/typora-default-themes/pull/8

**Comment by abnerlee** [comment]
Should be fixed in 0.9.96, could you confirm it please?

**Comment by jonpoveda** [comment]
Fix confirmed!
