### ISSUE TITLE
Dark mode theme does not change automatically when system dark mode status changes

### ISSUE THREAD

**Issue by tony1ee** [typora/typora-issues#3851]
Only quitting and restarting Typora can force Typora to load the correct theme.

**Comment by abnerlee** [comment]
should be fixed.

What's your Typora / OS version?

**Comment by tony1ee** [comment]
> What's your Typora / OS version?
 I am using version 0.9.9.35.2 (4715)

Funny this cannot be reproduced ever since I post the issue but it did exist before.
 I guess one-time issue maybe? Sorry for the confusion.
