### ISSUE TITLE
File size limit to Typora/MathML?

### ISSUE THREAD

**Issue by tholonia** [typora/typora-issues#3852]
My document is 794,824 bytes. I notice that typora successfully loads at doc sizes of (about) 768100 bytes or smaller, but anything larger will cause the [Math Processing Error].  

If there a way I can increase the size of the file I am loading? Can I tweak MathML somehow? or have I hit the limit in size?

95% of the time, when I start Typora (and wait 1m14s on a 3Gh, 12GB RAM w/ SSD running ARCH Linux), it gives me [Math Processing Error].  I have nothing else running, so it is not a memory limit issue. This appeared with v9.85 but continues up until now at v9.96 (and all the version in between). The error message makes no sense given that SOMETIMES (like 1 in 20 times) it works.  However, if I have less than 6 GB free, it ALWAYS fails. Typically I have 9 GB free. Also, the doc has about 205 images totaling 105MB, is that matters.

I have read bug reports about search having problems in larger files, but I have to problem there (slow, but works fine).

The typora log files reports...

```
INFO 9/16/2020, 10:28:05 PM  ------------------start------------------
INFO 9/16/2020, 10:28:05 PM  typora version: 0.9.96
DEBUG 9/16/2020, 10:28:05 PM  [
  '/opt/typora/bin_0.9.96/Typora-linux-x64/Typora',
  'Latest/THOLONIA_THE_BOOK.md'
]
DEBUG 9/16/2020, 10:28:05 PM  app.openFile
INFO 9/16/2020, 10:28:05 PM  addRecentDocument
INFO 9/16/2020, 10:28:05 PM  [Raven] instanceKey = 2df91243-03b2-4595-a41a-e3d0a97c546e
INFO 9/16/2020, 10:28:05 PM  [Raven] userId = 5371a635-42d8-40ff-a4a2-b9e80eeac904
INFO 9/16/2020, 10:28:05 PM  [focus] 1
INFO 9/16/2020, 10:28:34 PM  [blur] 1
INFO 9/16/2020, 10:28:35 PM  [RenderProcess 1][Error] TypeError: Cannot read property 'mbase' of undefined
    at file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/extensions/toMathML.js?V=2.7.5:19:156
    at Function.execute (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:3015)
    at e (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:2678)
    at n.Execute (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:6017)
    at Object.loadComplete (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:13562)
    at Object.loadTimeout (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:13737)
    at Function.execute (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:3015)
    at e (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//lib.asar/MathJax/MathJax.js:1:2678)
    at r (file:///opt/typora/bin_0.9.96/Typora-linux-x64/resources/app//app/window/frame.js:1:661853)
```

and console of Typora shows... (doubt this is related, but it's an error nevertheless.  I can't see inside lib.asar to check if they exist)

```
DevTools failed to load SourceMap: Could not load content for file:///usr/share/typora/resources/app/lib.asar/pdf/pdf-lib.min.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/typora/resources/app/node_modules.asar/pathwatcher/node_modules/underscore/underscore.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/app/window/frame.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/lib/codemirror/mode.min.js.map: 
```
This issue is the same whether I use the downloaded binary or the one in the ARCH repo (I'm running ARCH Linux).

This is the same issue as https://github.com/typora/typora-issues/issues/1504  (but that was closed with no reply)

Also, I share the following unrelated issues, just as feedback:

- When I go to General->Advanced Settings, a Firefox debug console pops up with a URL to file:///home/jw/.config/Typora/conf/conf.user.json, and the error:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
I deleted the first line "/** Advanced Editing **/" and then I get the error:
```
SyntaxError: JSON.parse: expected double-quoted property name at line 3 column 23 of the JSON data
```
I just deleted all the comments, and it came up without error.

- When I do spellcheck, I have to download and install the dictionary every time.

Thank you,
p.s. I love Typora. It's as close to the perfect editor as I have ever used!

**Comment by tholonia** [comment]
update: running typora with the argument "--no-sandbox" seems to help.

**Comment by tholonia** [comment]
update: --no-sandbox seems it have a MINIMAL effect (80% fail rather than 95%), and over 768k search doesn't work at all.

**Comment by tholonia** [comment]
update: Running Edit->Math Tools->Refresh All Math Expressions will remove the [Math Processing Error].

**Comment by abnerlee** [comment]
Hi, possible to send us (<hi@typora.io>) a sample file that has [Math Processing Error] error?
