### ISSUE TITLE
Images in unified project folder

### ISSUE THREAD

**Issue by redoxmatlab** [typora/typora-issues#3859]
Dear colleagues,
I am using typora in writing materials within a project containing several subfolder. I am finding it irritating that images end up in several subfolders rather than in a unified folder under the root project. I hope this feature will be implemented soon!

Many thanks.

**Comment by abnerlee** [comment]
You can make the image folder pointing a unified folder. 
http://support.typora.io/Images/#copy-image-files-to-target-folder-when-inserting-local-image

**Comment by redoxmatlab** [comment]
Thank you. Yes, this works but it means that I have to redefine the custom folder for each project. I am looking for something global. Something like 'images' folder in the root directory, no matter which project I am working on. I hope this makes some sense!

**Comment by abnerlee** [comment]
This may be hard to understand as a "global setting", if your file structure is "A/B/C/d.md", then when open folder "A", A is root, while open "C", C becomes root, which may easily cause troubles.

Maybe #3109 would be the option
