### ISSUE TITLE
Typora load remote image failed!

### ISSUE THREAD

**Issue by ClearLoving** [typora/typora-issues#3860]
I have uploaded a picture to github, I found that the picture can't be loaded successfully if the picture **_exceeds 1M_** in size

How to fix this problem?

```
My operation system: MacOS 10.15.6
typora version: 0.9.9.35.2 (4715)
```

**Comment by abnerlee** [comment]
Typora does not have such limit (< 1M)

But please check your network / proxy since loading 1M image may take time.
Also, please check if you can only / load the image (> 1M) using that url.
