### ISSUE TITLE
Export to PDF behavior: should file export with dark mode theme?

### ISSUE THREAD

**Issue by tony1ee** [typora/typora-issues#3861]
I configured Typora to change to a dark mode theme when system dark mode is enabled, when I export file while Typora is in dark mode theme, the exported file will also be in dark mode. 

Personally I expect a normal theme file export even in dark mode, since people who read it won't expect a dark mode document. Currently I have to switch back to normal theme, do the export and then re-enable auto dark mode switching.

Would appreciate if a toggle or something else for this, please consider this, thank you.

**Comment by abnerlee** [comment]
relates #2125

What's your OS and which dark mode theme did you use?

**Comment by tony1ee** [comment]
macOS Catalina 10.15.6
I use this **Github Dark Theme for Typora** from [Sayrus](https://github.com/Sayrus)/[typora-github-dark](https://github.com/Sayrus/typora-github-dark) with slight tweak for the font location.
Cheers.

**Comment by abnerlee** [comment]
duplicate with #2125
