### ISSUE TITLE
"etc." keeps getting flagged as incorrectly spelled 

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#3862]
Anywhere I have "etc" in my text, Typora underlines it and suggests I replace it with "etc." even if it's _already_ followed by a full stop:

![image](https://user-images.githubusercontent.com/177243/93719795-ba911780-fb39-11ea-8cbd-0d753ae2ed58.png)

Accepting the correction just means I now have `etc..` and then `etc...` ad infinitum, which is pretty silly =)

(using the UK English dictionary, but this doesn't feel like it's so much "word match" related as "parser" related, where it does not treat punctuation as being part of words, which is most certainly the case for abbreviations like `etc.`, `no.` etc)

**Comment by abnerlee** [comment]
duplicate with #3828
