### ISSUE TITLE
Ask to load unknown extensions as text files (or add a list of known extensions to load as plain text)

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#3864]
The Grammarly app does not have special parsing for `.md`, `.tex`. etc. right now, and that's fine, but it also _refuses to load them at all_ and that's not fine: it already knows how to load `.txt` which means there is no reason to reject plain text formats. 

Please add an option that goes "this is an unknown file type, load as plain text file? [Yes] [No]", or even a setting where folks can list the extensions that should be loaded as plain text, so that authors can load their files without Grammarly forcing them to rename them. Grammarly's supposed to help writers, not make things frustrating =)

The basic "load as text?" shouldn't take more than an hour to add in given that you already support `.txt`, and that you already check file extensions at load time: this is a genuinely super low hanging fruit with huge payoff, and is so small you can even release a patch update for the desktop app on the same day, so that everyone can finally use Grammarly for their Markdown/LaTeX/etc files.

And of course, having Grammarly incorrectly flag things on occasion because it doesn't know what is normal English and what is markdown/tex/etc syntax  _is fine as long as we don't have to rename files_ (having to rename 20+ files just so they can be grammar-checked and then having to rename them all back again when done is a flipping nuisance, and the opposite of the great experience you want people to have with Grammarly)

**Comment by abnerlee** [comment]
Is this issue sent for Typora or for Grammarly?

**Comment by Pomax** [comment]
that's a very good point, why did that end up in this repo?

**Comment by Pomax** [comment]
(feel free to delete this issue, as it doesn't actually belong here in the slightest)
