### ISSUE TITLE
bugs in source code mode when indent code fence in list

### ISSUE THREAD

**Issue by Behemoth-s** [typora/typora-issues#3866]
It seems that in source code mode if a code fence under a list is indented, all text afer will be identified as code. 
Here is an example
```
# Header1

## header2

test

1. aaaaa
dasddasfas


# Header

## dasd

```
the original view
![image](https://user-images.githubusercontent.com/13926242/93837065-657b1000-fcb7-11ea-8e34-99add5ccab03.png)
if code fence is indented
![image](https://user-images.githubusercontent.com/13926242/93836920-db32ac00-fcb6-11ea-9df5-cd81a918737d.png)
if code fence is not under a list
![image](https://user-images.githubusercontent.com/13926242/93837172-bb4fb800-fcb7-11ea-9d87-23d483b34000.png)
This problem seems only in source code mode.

**Comment by abnerlee** [comment]
#1638
