### ISSUE TITLE
macOS no markdown document icon after setting Typora to default app

### ISSUE THREAD

**Issue by johnnybarrels** [typora/typora-issues#3867]
After setting Typora to the default application for all Markdown documents, Markdown files open in Typora fine, but I am still getting the default (plain text) icon for these files in Finder:

<img width="144" alt="Screen Shot 2020-09-22 at 6 10 31 pm" src="https://user-images.githubusercontent.com/49610004/93869816-ead5e300-fcfe-11ea-9532-77882a84d755.png">

I have had Typora set as the default Markdown app for a few months, and as such there have been multiple restarts (to reset icon cache) since then. I have also changed other file types' default applications since, and observed their icons change.

Checking Typora.app/Contents/Resources/ I notice that the `file.icns` file is in there:

<img width="436" alt="Screen Shot 2020-09-22 at 6 14 36 pm" src="https://user-images.githubusercontent.com/49610004/93870245-7b142800-fcff-11ea-8088-2edff79eff94.png">

and in Typora.app/Contents/Info.plist, this icon file appears to be selected for Markdown files:

<img width="350" alt="Screen Shot 2020-09-22 at 6 17 16 pm" src="https://user-images.githubusercontent.com/49610004/93870464-db0ace80-fcff-11ea-874e-4362961cdc81.png">

but still I have the default plain text icon for all markdown files?

Any ideas?
(btw thanks so much for the app its incredible)

macOS Catalina 10.15.6
Typora 0.9.9.35.2

**Comment by abnerlee** [comment]
You can **disable** the option to use icon preview, and use the icon instead.

https://discussions.apple.com/thread/8392666

**Comment by johnnybarrels** [comment]
Not a fix? This is a global option that disables icon previews for all file types, meaning I would then lose icon previews for images and video etc.
Not to mention, it didn't work anyway :( The way I understand it, icon preview does not apply to text files. I have other apps that open CSVs for example, and that app's CSV icon displays in Finder (with icon preview on).

**Comment by abnerlee** [comment]
If the option is enabled, macOS will use the file thumbnail instead of file icon.

> Not to mention, it didn't work anyway

You mean still blank? Does change view (press command+1) in finder work?
