### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Adrian-Yan16** [typora/typora-issues#3869]
in this situation,i use an unordered list in an ordered list.at the end of the unordered list,if i click 'enter' ,if appears the next point,i click 'enter' again,it doesn't disappear,but show a space line

![1600846474(1)](https://user-images.githubusercontent.com/54240566/93981249-4e6d1880-fdb2-11ea-8071-63c47ae747b9.jpg)

**Comment by abnerlee** [comment]
Is there a whitespace after the cursor location where you press "enter"?

And this should be fixed in latest verison
