### ISSUE TITLE
Ghostwriter vs. Typora

### ISSUE THREAD

**Issue by orschiro** [typora/typora-issues#387]
Asked out of curiosity and to get your view, how do [Ghostwriter](https://github.com/wereturtle/ghostwriter) and Typora.io compare?

**Comment by AlexPasternak** [comment]
Perhaps you can download both and do your own research? It's also not an "issue" to be opened. For starters, Ghostwriter uses the traditional write/preview model, whereas Typora's preview is the document you're working on. Oh, and there's no Mac version of Ghostwriter, it seems. So, just minor differences  :-)

**Comment by orschiro** [comment]
Thanks, Alex!

Maybe we can do something like this:
https://en.wikipedia.org/wiki/User:Orschiro/sandbox

**Comment by vassudanagunta** [comment]
@orschiro If you do such a table, here's one for iOS editors you can borrow ideas from: http://brettterpstra.com/ios-text-editors/. It is a very popular table referenced by many sites and reviews.

**Comment by orschiro** [comment]
Wow, this is extensive. Thanks for sharing!

I might draw some inspiration from. :-)

**Comment by vassudanagunta** [comment]
Personally I'd put it on GitHub instead of Wikipedia so that people can add to it via pull request. You could use GitHub Pages, a Gist, or the README.md of a repo. You could put the data in a CSV, which gets rendered into the page.

**Comment by orschiro** [comment]
- People can also add to the table on Wikipedia, no?
   - Could you help me set-up such a page if you find it superior?

**Comment by vassudanagunta** [comment]
Actually I'm not sure what's superior. If you expect many non coder to contribute, Wikipedia might be better. But if coders are the type that are likely to care and help, then GitHub would be better. Question: Does Wikipedia support such comparison tables, or will the page get removed as inappropriate for an encyclopedia? Are there existing example of such comparison tables already on Wikipedia?

**Comment by orschiro** [comment]
- I think our audience for such a table are writers and authors. Not
   necessarily coders. Thus my choice is Wikipedia.
   - Yes, there are good examples of these tables:
   https://en.wikipedia.org/wiki/Comparison_of_wiki_software

**Comment by vassudanagunta** [comment]
@orschiro Then I think you're right. Go with Wikipedia. I look forward to seeing it, and will contribute anything I know. If you get it looking serious enough, you will be able to get the authors of the various editors to add their own to it.

**Comment by orschiro** [comment]
Thanks, Vas!

I will continue with the table as I come across new editors or features.
