### ISSUE TITLE
【bug】auto delete selected text

### ISSUE THREAD

**Issue by ijesonchen** [typora/typora-issues#3870]
With no reason, it will auto delete ANY seleted text.
os: win10 1903
typora: 0.9.96

When editing a md file, it suddenly delted the seleted text. Then I tried ctrl+z to redo, but the recovered text is seletect by default, and then be delted immediately. I have no change to retore my text, or copy it.
It happened some times yeas ago. I'm not sure what the reason it is.

**Comment by abnerlee** [comment]
Did you use any IME, and how to reproduce this bug?
