### ISSUE TITLE
Screen rolls up to the beginning of a document when editing text in a table via context menu

### ISSUE THREAD

**Issue by dlvakalucifer** [typora/typora-issues#3871]
For example: You select a word in a column of  a table and `right click` the selected text. After that you choose `Bold` as the desired formatting option. Text gets bold and screen rolls all the way up.

Greetings :-)

**Comment by cbono** [comment]
Experiencing the same issue; seems to have been introduced in v0.9.90. For reference, I'm using the x64 Windows flavor.

**Comment by abnerlee** [comment]
duplicate with #3696
