### ISSUE TITLE
Adding LaTeX physics package for braket notation?

### ISSUE THREAD

**Issue by Hazarre** [typora/typora-issues#3872]
Hi, 

Since Typora is backed by MathJax, and MathJax supports the braket notation [here](http://docs.mathjax.org/en/latest/input/tex/extensions/physics.html), I believe there is a way to enable the LaTex Physics package to work on typora. 

I love Typora as a CS and Physics student, and I really hope that I could type up the braket notation with it. I referred to a similar issue [here](https://github.com/typora/typora-issues/issues/2974) and several online resources, but I can't quite figure out the syntax for loading the physics package in LateX. 

The [MathJax doc](http://docs.mathjax.org/en/latest/input/tex/extensions/physics.html) has a way of importing the physics package, but I don't know how to put it into my config code for Typora in the ```window.html``` file.

My current default MathJax configuration looks like: 
```javascipt
MathJax.Hub.Config({
			messageStyle: "none",
			skipStartupTypeset: true,
			jax: ["input/TeX", "output/SVG"],
			extensions: ["tex2jax.js", "toMathML.js"],
			TeX: {
				extensions: ["noUndefined.js", "autoload-all.js", "AMSmath.js", "AMSsymbols.js", "mediawiki-texvc.js"],
				mhchem: { legacy: false }
			},
			SVG: {
				useGlobalCache: false,
				merrorStyle: {
					fontSize:"90%", color:"red", background:"",
      				border: "1px solid red", padding:"2px"
				},
				scale: 100, 
				minScaleAdjust: 80,
				blacker: 0,
				matchFontHeight: false,
				undefinedFamily: "STIXGeneral, 'PingFang SC', serif"
			},
			showProcessingMessages: false,
			tex2jax: {
				displayMath: [['$$\n', '\n$$'], ['$$\r\n', '\r\n$$']],
				inlineMath: [ ['$','$'], ['$$', '$$']],
				processEscapes: true,
				preview: "none",
				skipTags: ["script","noscript","style","textarea","pre","code", "span"],
				processClass: "md-inline-math|inline-math-export-jax"
			},
			menuSettings: {
				inTabOrder: false
			},
			showMathMenu: false,
			positionToHash: false
		});
```

**Comment by abnerlee** [comment]
duplicate with #3706
