### ISSUE TITLE
Auto completion for Math LaTeX.

### ISSUE THREAD

**Issue by kxxt** [typora/typora-issues#3873]
It would be nice if typora has a feature that when I type LaTeX between $$ , it can provide auto completion for LaTeX commands such as `\frac` , `\rightarrow`.
For example , when I typed `\fr` ,it would pop up a list containing `\frac` and if I choose it , it would automatically add `{}{}` after the `\frac`.

**Comment by kxxt** [comment]
I know you may think this duplicate with #756 , but I think it is OK as the auto completion is limited to math environment.

**Comment by abnerlee** [comment]
duplicate with #2988
