### ISSUE TITLE
[New Feature] Can features like Emmet syntax be supported?

### ISSUE THREAD

**Issue by heicks** [typora/typora-issues#3874]
-----
E.g:
> #3 + `Tab` => ###
> #4 + `Tab` => ####
> #5 + `Tab` => #####

upgrade:
> `#3this is a line title +'Tab' `=>> ### this is a line title

// `#` Too many symbols, too tired to press :(

Other emmets also have pictures and tables. The `-` `|` of the table is too troublesome. How can I optimize it?

#3 For example about link
`[]()` => `TODO://`

#3 tables:
// TODO://
I’m not sure how to use the symbols `-` `|` to optimize the table and make it shorter without losing too many times. Do you have any good ideas?,

If you use double `||` instead of a `|` table border vertical line or a column, add spaces on the left and right sides `<space>||<space>`
So double `--` represents a row,
But this double `--` has a bug (the original md syntax has too many `---------`),
Then if there are spaces on the left and right sides of  `<space>--<space> `, is this way better?

**Comment by abnerlee** [comment]
can be covered by #3021
