### ISSUE TITLE
zoom CSS property is not supported in Firefox

### ISSUE THREAD

**Issue by mikelei8291** [typora/typora-issues#3876]
The CSS style that Typora uses for resizing images is not supported in Firefox:

https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
https://bugzil.la/390936

It seems that this is not a standard CSS property so Firefox decided to not implement, even though all the other major brands have implemented this feature.

**Comment by abnerlee** [comment]
Yes, if you also need to work under Firefox, you will have to specify the image width or height.

We currently does not have any better solution for this.

relates #2242
