### ISSUE TITLE
Option to reverse new line and new paragraph shortcut

### ISSUE THREAD

**Issue by this-josh** [typora/typora-issues#3877]
Currently *Enter* provides a new paragraph and *Shift + Enter* provides a new line. Often when writing in Typora I wish the functionality could be swapped; *Enter* for a new line and *Shift + Enter* for a new paragraph. Reference to the current functionality can be seen on the [Typora Shortcut Keys page](http://support.typora.io/Shortcut-Keys/#edit).

**Comment by abnerlee** [comment]
duplicate with #1845
