### ISSUE TITLE
Right-click "Open Link" double-escapes already-escaped URLs with escaped slashes

### ISSUE THREAD

**Issue by zachriggle** [typora/typora-issues#3882]
Consider the following Markdown document:

```md
This is a [link](https://example.com/?at=refs%2Fheads%2Fmaster
```

Right-clicking the link in Typora will navigate instead to `https://example.com/?at=refs%252Fheads%252Fmaster`

It looks like it's double-escaping the percents, rather than taking the URL as-is.

**Comment by abnerlee** [comment]
relates #2850

**Comment by abnerlee** [comment]
relates #3514

**Comment by abnerlee** [comment]
should be fixed
