### ISSUE TITLE
source mode fixed width font

### ISSUE THREAD

**Issue by y0y0z** [typora/typora-issues#3885]
came across https://github.com/typora/typora-issues/issues/437 and followed the documentation. yet, couldn't figure out how can i make the source mode used a fixed width font, since it is hard to have edit tables (and more) when non-fixed width font is used.

is it possible to set source mode to use a fixed width font globally?
if so, then please share how.

**Comment by abnerlee** [comment]
I updated http://support.typora.io/Custom-Font/

You can follow it to give source code mode a fixed width font.

**Comment by y0y0z** [comment]
@abnerlee:

> I updated http://support.typora.io/Custom-Font/
> 
> You can follow it to give source code mode a fixed width font.

**THANK YOU**. indeed solved my  issue
