### ISSUE TITLE
\boldsymbol faild to render in certain equations

### ISSUE THREAD

**Issue by sirlis** [typora/typora-issues#3886]
see image below

![无标题](https://user-images.githubusercontent.com/12960298/94804156-ef944880-041c-11eb-9859-fa1d679f0682.png)

however, both equations can be rendered in the latest VSCode, as follows

![无标题1](https://user-images.githubusercontent.com/12960298/94804475-71847180-041d-11eb-9058-e4e97ade709a.png)

**Comment by abnerlee** [comment]
should use `\boldsymbol{text}`.

Relates #3388

**Comment by sirlis** [comment]
> should use `\boldsymbol{text}`.
> 
> Relates #3388

however the correctly rendered equation use '\boldsymbol' text instead of '\boldsymbol{text}', I think this could be widely applied in many other equations like '\partial text' and '\hat text'. All work well in VSCode and github pages.
