### ISSUE TITLE
[Improvement] Search should be able to ignore markdown syntax

### ISSUE THREAD

**Issue by 0x7969** [typora/typora-issues#3887]
Hi together,
when searching for words that are partly formatted, the search won't find them. For example, if you had `example *word*` in a document, it is not found when searching for "example word". You would have to include the asterisks. Maybe it's possible for the search to go through the files a second time after stripping them of all markdown syntax or something similar.

Thanks in advance, really love Typora!

Best
y

**Comment by abnerlee** [comment]
duplicate with #3260
