### ISSUE TITLE
[Improvement] Hide .assets subdirectories

### ISSUE THREAD

**Issue by jozefliska** [typora/typora-issues#3888]
Hi,
It could be great if files tree left panel not showing subdirectories ending on `.assets` because typically it does not contain markdown files, but only images or other files which no need showing in the tree - see image below.
![image](https://user-images.githubusercontent.com/16937671/94907243-23648200-04a0-11eb-929d-b666d5331d19.png)
On the image it is no so bad, but when I will more than 5-10 `.assets` subdirectories then it will be worse.

An alternative solution could be some option for hiding empty directories.

Otherwise thank you for the great product!

**Comment by henshin** [comment]
Agree with this. Would be nice to have an option to hide these.
My workaround was to configure Typora to name the image directories to something starting with a dot, for example: `.images.assets`. This will not show on the directory tree.

**Comment by abnerlee** [comment]
duplicate with #2183
