### ISSUE TITLE
Images are not displayed when working on network-drive

### ISSUE THREAD

**Issue by siwidmer** [typora/typora-issues#3889]
In my report, the linked images are not displayed. There is only a mouse-over-hint "image load failed". As soons as I copy the document and the assets to my local harddrive, everything is working fine and the images are correctly displayed.

I opened the markdown-file also with Visual Studio Code: The images are correctly loaded. Is this a know issue? I didn't find anything about this.

**Comment by abnerlee** [comment]
Is this same with #2995, or same with #1881? What's your OS, what is your etwork-drive, and and there any more details?

**Comment by siwidmer** [comment]
It is the same issue as #2995 . We are working on Windows 10. I use the settings, where Typora is copying all images to a local/relative "assets"-folder.

**Comment by siwidmer** [comment]
Why do you close this and the other issue without solving them?
