### ISSUE TITLE
"Linux" button downloads the MacOS version typora_latest.zip

### ISSUE THREAD

**Issue by Rhialto** [typora/typora-issues#389]
If I am on http://www.typora.io/#download and I click on the "Linux" box, I get a download of typora_latest.zip with the MacOS version in it, not a Linux version.

**Comment by abnerlee** [comment]
seems OK on my testing

**Comment by Rhialto** [comment]
Sorry, stl doesn't work for me.

Do you perchance allow this unsafe thing called "javascript"? I'm using NoScript to protect myself from drive-by hackings being foisted on me from random untrusted websites.

HINT: A *link* that requires javascript to work???? That is *insane*.

**Comment by AlexPasternak** [comment]
You gotta love the Internet. That post is just a classic.

I'm guessing NoScript probably breaks a lot of things online. Having this installed would probably be a good thing to mention in the beginning when you're opening issues about something online not working. But if your interest is rather wasting a developer's time, this is a good way to go about it.

HINT: If you consider a site untrusted, don't try to download software from it.

**Comment by Rhialto** [comment]
I'd say that requiring javascript for stuff that HTML has supported out of the box since day one is insane. And who said I wouldn't use a sandbox for trying out said software?
