### ISSUE TITLE
[Improvement] List items that are headings should show in Outline

### ISSUE THREAD

**Issue by niche-n** [typora/typora-issues#3890]
I can see some arguments against implementing this, but I personally would find this feature useful. 

Thanks for all your hard work, typora is great

**Comment by abnerlee** [comment]
We don't have plans for this, the list itself can show sort of heretical structure.

And the structure of lists can be contrast with headers inside it.

e.g:
```
- ## H2
   - # H1 but sub list of H2
```

I think #499 may be your purpose.
