### ISSUE TITLE
base.user.css => Source mode => Text size not working

### ISSUE THREAD

**Issue by Merrit** [typora/typora-issues#3891]
I created the css file `~/.config/Typora/themes/base.user.css`

I have inspected the elements, and in DevTools I can change the font size under the :root property.

I have tried populating the `base.user.css`:

```
#typora-source .CodeMirror-line {
  font-size: 18px;
} 
```

I have tried several variations, like `.CodeMirror`, `.CodeMirror*`, `:root` but none seem to actually affect the font size.

**Comment by abnerlee** [comment]
You can add `!important` after `font-size: 18px`

And restart Typora to apply new css rules
