### ISSUE TITLE
Emojis in headings disappear when exported to PDF

### ISSUE THREAD

**Issue by RilicTheFox** [typora/typora-issues#3893]
Upon exporting a document to PDF, emojis that were selected using the markdown-github method (between ::) appear in paragraphs but do not appear in headings. Instead, they show up as a unicode character that cannot be displayed from within the PDF viewport, but can be seen as normal text when a PDF viewer lists the headings in the contents panel (e.g. Okular).

**Comment by abnerlee** [comment]
What is your OS/typora theme? And please provide a sample md file that emojis missing after export.

**Comment by RilicTheFox** [comment]
I'm using Artix Linux with all required pandoc dependencies. I'm using the default GitHub theme to write and export to PDF.
[Attached here](https://github.com/typora/typora-issues/files/5378657/Sample.zip) is a markdown file with an emoji in the heading and a sample export I generated. I hope this helps!

**Comment by abnerlee** [comment]
Still unable to reproduce it, what's your Typora version?

**Comment by RilicTheFox** [comment]
0.9.96.
On further investigation, it seems that it's to do with how the fonts are working on my system.
Windows produces a file with emojis that are black and outlined that also work in the headings, while my Linux system uses coloured emoji that don't appear in the heading.
Is there any reason this could be, and is there a way I could fix it?

Example of Windows export [here.](https://github.com/typora/typora-issues/files/5407698/Windows.Export.Sample.zip)

**Comment by abnerlee** [comment]
Older windows does not have font for colorful emoji, see https://github.com/typora/typora-issues/issues/1357

And please check your advanced setting,  whether `"monocolorEmoji": false` is configured `true` or `false` (default). And on windows,if you use font "Segoe UI Symbol", it is also not colored.
