### ISSUE TITLE
Drag-and-Drop Checklist Reordering

### ISSUE THREAD

**Issue by chris2fr** [typora/typora-issues#3896]
NOW : List items can be reordered by selecting the line cutting and pasting elsewhere.

WHY SUB-OPTIMAL? : It is a lengthy process. The cutting and pasting also has undesired side-effects usually on the previous or next lines.

VISION : Click on the checkbox, hold, maybe a faint three-line icon appears on the left of the checkbox, I drag up and down, even outside the list elsewhere or to another list, the checkbox items is magically integrated and elsewhere.

# TEST CASES

All test scenarios assume initial test data context.

## Test Data

Paragraph with a couple of word is here. List One is below.

- [ ] Check Item 1.1
- [ ] Check Item 1.2
  - [ ] Check Item 1.2.1
  - [ ] Check Item 1.2.2
- [ ] Check Item 1.3

Another paragraph before list 2 is here.

- [ ]  Check Item 2.1
- [ ]  Check Item 2.2
- [ ]  Check Item 2.3

Another paragraph after list two is here.

## Test Scenario 1

Drag 2.3 above 2.2

## Test Scenario 2

Drag 1.2.1 so that it becomes a 1.1.1 position

## Test Scenario 3

Drag 1.2.1 below the third paragraph so that it becomes an additional list, but indented.

## Test Scenario 4

Drag 1.2 below 1.3 and notice that 1.2.1 and 1.2.2 stay under 1.2 in the 1.3 position.

## Test Scenario 5

Drag 1.2 below 2.2 and notice that 1.2.1 and 1.2.2 are still under 1.2.

# General Case 

## Other Types of Lists

This might be applicable to ordered lists and unordered lists.

## Titles

This may be applicable to other types of titles.

**Comment by chris2fr** [comment]
I am so wiered out! This seems to work on the GitHub Renderer! MIND BLOWN 
PAFF
POOF
EXPLOSION
... does github share this code?

**Comment by felipesere** [comment]
I want this too. There is another issue here somewhere that proposes some keyboard shortcuts too

**Comment by abnerlee** [comment]
can be covered in #151 and #2376
