### ISSUE TITLE
Unibody for Linux

### ISSUE THREAD

**Issue by rataman098** [typora/typora-issues#3897]
Is there any way to turn on Unibody mode on Linux? For some reason, the menu doesn't appear on my setup (UbuntuDDE 20.10 Beta), so I'm unable to export or access the rest of menu options. Also, it would be great if we also had the option to turn on uniwindow as in Windows.

**Comment by abnerlee** [comment]
We don't have plans for this. "Unibody" is modern Windows style which does not fit in Linux whose visual style is unknown
