### ISSUE TITLE
Strange selection with arrows behavior on Mac

### ISSUE THREAD

**Issue by thejonan** [typora/typora-issues#3898]
Hello and thank you very much for this awesome product!

There is a bit strange behavior when selecting with `Shift` key on Mac:
1. Press `Shift + Command + →` selects everything to the end of the line. That's expected.
2. While keeping the `Shift` key pressed, trying to "shrink" the selection by using `←`, actually moves the beginning of the selection, i.e. "expanding it".

It looks like that in step [1], even though the selection was moved to the end of the line, the cursor had not. It also resembles an old Mac selection behavior. If that is the case - it'll be great if we can configure it.

Thanks a lot!

**Comment by abnerlee** [comment]
put into #1164

**Comment by thejonan** [comment]
Thanks!
