### ISSUE TITLE
Improve Windows open screen UI

### ISSUE THREAD

**Issue by sguergachi** [typora/typora-issues#390]
The open screen on Windows could use some love.

![capture](https://cloud.githubusercontent.com/assets/615386/19812857/3ecda816-9d05-11e6-9e29-b44dd776be4e.PNG)

First of all, I don't understand why the Open and Import sections need to take up so much vertical space when there are no items under each. Second, why is Recent documents placed at the very bottom, when it's likely the area you would likely use the most (I open or import once, I reopen docs I'm working on multiple times). Finally there's a bug where the "..." button isn't positioned properly.

**Comment by abnerlee** [comment]
Close since CSS has already been changed.
