### ISSUE TITLE
Collapsible regions issues

### ISSUE THREAD

**Issue by brunovacare** [typora/typora-issues#3900]
Hi, 
collapsible regions like the code below do not work on Typora:

# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

There is a detail explanation about it here: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by abnerlee** [comment]
duplicate with #3899
