### ISSUE TITLE
Tab / Shift+Tab to indent/unindent list item in source code mode

### ISSUE THREAD

**Issue by m00nlygreat** [typora/typora-issues#3901]
Hello! thanks to your nice work

I want it to indent / unindent the list item when I hit the tab/shift+tab on source code mode

just like Typora's normal wysiwig view of typora and StackEdit

**Comment by abnerlee** [comment]
We don't have plans for this, or this will be in low priority. 

Source code mode will be designed as temp workaround, its functionality will be in low priority.

**Comment by m00nlygreat** [comment]
Thanks for the reply. I appreciate your decision😌
