### ISSUE TITLE
mouseover scrollbar jumps focus to mouse position

### ISSUE THREAD

**Issue by hieu6** [typora/typora-issues#3903]
mouseover scrollbar jumps focus to mouse position

this happened while i was highlighting a long article within typora with Typewriter mode on. 
(this wasn't happening in prior use of typora/typewriter mode). 
it also wasn't jumping to focus to where i last left off, but jumping directly to where my mouse would be hovering. 

example: 
https://imgur.com/a/SLYs8w1 
in gif, i am not clicking and dragging, just mousing over scrollbar area.

- turned off typewriter mode, restarted typora, and issue seems to be resolved.

minor annoyance, hope this is helpful!

macbook Air (2017)
macOS Catalina
v. 10.15.7

Typora 
v. 0.9.9.35.2 (4715)
beta version for preview

**Comment by abnerlee** [comment]
I see, possible to send us <hi@typora.io> the sample *.md file as well?
