### ISSUE TITLE
Inline math doesn't work in .rmd file

### ISSUE THREAD

**Issue by bakaburg1** [typora/typora-issues#3905]
Hello, I wanted to try typora out, coming from Rstudio. But even if typora can read .rmd files, inline math is not recognized, even after forcing math evaluation in the edit menu. I can add math blocks though.

I don't know if this was a clear decision or a unintended behaviour.

Thanks

**Comment by abnerlee** [comment]
duplicate with #1510

**Comment by bakaburg1** [comment]
Just to be sure that we are on the same page, I did opted-in in the options. The referenced issues were all about this, but this is not my specific case.

**Comment by abnerlee** [comment]
Then how to reproduce this? In my test inline math is working in rmd file.

**Comment by bakaburg1** [comment]
Ok, shameful by me, but I tried again and now it works... I really don't know what happened. Sorry
