### ISSUE TITLE
Typora doesn't work properly with windows account alias name, paths are trying to reach alias username

### ISSUE THREAD

**Issue by dennysq** [typora/typora-issues#3907]
I have a computer with the username "Pc". everything worked perfectly until I changed my username account to "Dennys". As a result, export PDF has an error and also when I copy an image using relative paths, the image is not creating.

Please notice that even though I changed my username in windows. USER_HOME remains the same , that is C:/Users/Pc

**Comment by abnerlee** [comment]
Does `C:/Users/Pc` also exist?
