### ISSUE TITLE
[linux] Install Language Support when opening Typora 

### ISSUE THREAD

**Issue by himmorth** [typora/typora-issues#3908]
The **Install Language Support** dialogue always shows up whenever I'm opening Typora. It disrupts my workflow because I always have to download and install the language support despite having the dictionary file already in './config'. Any help would be greatly appreciated, Thanks!

![**Install Language Support**](https://user-images.githubusercontent.com/70275189/95541636-684f6200-0a26-11eb-9f55-f874057485e7.png)

**Comment by cichy1173** [comment]
https://github.com/typora/typora-issues/issues/3584
