### ISSUE TITLE
Override the max file size limit in typora

### ISSUE THREAD

**Issue by ajitgoel** [typora/typora-issues#3909]
I have a Pc with 32 GB RAM, but Typora isnt opening a 5 MB file. It is giving this error: The file is too large to render in Typora . Is there a way I can override the max file size limit in typora? Mark text opens the same file without any issues. Please help.

**Comment by abnerlee** [comment]
duplicate with #1961

You are editing a 5MB file? It is a ebook, or just document

**Comment by raghudinkavijaykumar** [comment]
Markdown files with embedded images easily go over 5MB. (Not created in typora, rather html/doc to md converted files)

**Comment by 943203155** [comment]
> Markdown files with embedded images easily go over 5MB. (Not created in typora, rather html/doc to md converted files)

markdown file is just a text file, so embedded images are just some addresses. they will not take much space

**Comment by Kobe972** [comment]
> > Markdown files with embedded images easily go over 5MB. (Not created in typora, rather html/doc to md converted files)
> 
> markdown file is just a text file, so embedded images are just some addresses. they will not take much space

No. Some images are embedded using base64.
