### ISSUE TITLE
Typora remove links in the beginning of a line when I press return

### ISSUE THREAD

**Issue by hypercube-software** [typora/typora-issues#3911]
I'm currently writing a big markdown file (6800 words) and sometimes something really creepy happen with Typora:
I have a link starting at the beginning of the line. I go in the middle of the line and hit return to split it.
Suddenly, the entire link goes away. I mean the link and the text of the link.

For instance I have this:

```
# chapter
[This](https://typora.io/) is a link to Typora website. click on it.
```

Then I have this:

```
# chapter
is a link to Typora website. 
click on it.
```

I don't know the cause of this, I can't reproduce it with certainty.

**Comment by abnerlee** [comment]
still happens under 0.10.11?
