### ISSUE TITLE
Where is "Theme Folder"?

### ISSUE THREAD

**Issue by kovacm** [typora/typora-issues#3912]
I can not find in Typora documentation location of (path to) Theme Folder.

https://support.typora.io/About-Themes/
https://theme.typora.io/doc/
https://theme.typora.io/doc/Install-Theme/
...

On every page above, only suggestion is "Open preference panel from File → Preference from menubar, then click “Open Theme Folder”" - problem is that I am using ForkLift as Finder replacement (addition) and for some reason Typora won't open "Theme folder" location in ForkLift when I click on button "Open Theme Folder".

More about ForkLift as Finder replacement: https://binarynights.com/manual (at bottom "Default File Viewer").

Can you add path of "Theme folder" in documentation beside suggestion to click on "Open Theme Folder"?

Thank you.

**Comment by abnerlee** [comment]
updated the doc
