### ISSUE TITLE
pciture is not correctly included in exported pdf/doc file

### ISSUE THREAD

**Issue by bensenq** [typora/typora-issues#3914]
When open a markdown file on a non-local disk(like shared folder from other computer), the exported doc file does not contain picture in original markdown file. After copying file and related data into local directory, all is fine.

Platform: Windows 10
Version: 0.9.89

**Comment by bensenq** [comment]
mardown file and picture file are both on a shared folder imported from remote disk. picture path is relative to the local dir.

**Comment by abnerlee** [comment]
put into #3981
