### ISSUE TITLE
Bug: "File -> New" opens a new file in a new window instead of just a new file. (Windows)

### ISSUE THREAD

**Issue by mwesten** [typora/typora-issues#3918]
Version: 0.9.96(beta) for Windows (Windows 10)

When pressing CTRL+N or selecting the menu-item "File..." -> "New", a blank new file is created in a NEW window.
You would expect to check if the current document needed saving and if not, just replace the current document with a blank one in the same window.

Running in "Classic mode".

**Comment by abnerlee** [comment]
duplicate with #3879
