### ISSUE TITLE
Bugs in Linux (maximize button and not opening files correctly)

### ISSUE THREAD

**Issue by UltimateRandom** [typora/typora-issues#392]
I noticed these bugs in linux (using Lubuntu 16.04 x64)
- Using Unibody style: When the window is maximized the maximize button needs to be pressed twice
- In PCmanFM when i open an MD file with typora the program opens but not the file (I didn't test with other FM but i doubt the problem is PCmanFM)

**Comment by abnerlee** [comment]
@UltimateRandom How you enabled the Unibody style? The option is not supported in Linux, so it should be hidden in preferences panel

**Comment by UltimateRandom** [comment]
@abnerlee It's not hidden in my case, it's available in preferences just like in windows

**Comment by abnerlee** [comment]
We hide the `unibody` style on Linux in lastet version since it is Windows-like, not native on Linux

**Comment by UltimateRandom** [comment]
Why? it was cool, the only problem was the enlarge button but most of us just double click on the top :/
