### ISSUE TITLE
Failed to export pdf because of memory exhaust 

### ISSUE THREAD

**Issue by sosilent** [typora/typora-issues#3924]
Exporting Chinese pdf caused systemd-coredump running and failed to export.

Environments:
archlinux: 5.8.14
cpu: Intel(R) Core(TM) i7-4790K CPU
mem: 24g

ver: 0.9.95(beta)

**Comment by abnerlee** [comment]
could you provide simple md file?

**Comment by sosilent** [comment]
u can download the exmple.md by [example.md:](https://pan.baidu.com/s/1QvaJWB2TZP9gRzjNjs0LQQ) pwd: ngg3

**Comment by abnerlee** [comment]
Is there any error message? I've tried, but the PDF can be exported successfully.

**Comment by sosilent** [comment]
no special message, except "INFO 10/26/2020, 12:03:26 PM  [RenderProcess 1][Log] export PDF to *.pdf" in typora.log, with memory exhaust and the computer crash.

do you run Typora on Linux?

**Comment by abnerlee** [comment]
Did you use large images, if so, it may be duplicated with #2121

**Comment by sosilent** [comment]
now i upgraded typora to ver 0.9.96(beta),  and still failed to export pdf, but without memory exhaust and system crash. 
the largest image of the md doccument is 33.7KB, and i don't think it is the issue.

In fact, i can export some documents as pdf. The difference is the demo document is bigger than the one which can be exported.

the log:
INFO 12/14/2020, 12:41:23 PM  ------------------start------------------
INFO 12/14/2020, 12:41:23 PM  typora version: 0.9.96
DEBUG 12/14/2020, 12:41:23 PM  [ '/usr/share/typora/Typora' ]
INFO 12/14/2020, 12:41:23 PM  [Raven] instanceKey = 2b416980-f661-4bcb-a6c7-eb8d551dbc80
DEBUG 12/14/2020, 12:41:23 PM  app.openFile
INFO 12/14/2020, 12:41:23 PM  [Raven] userId = 6b7e8a05-e53f-4f61-be4e-4fa3c31f3b2a
INFO 12/14/2020, 12:41:23 PM  [focus] 1
INFO 12/14/2020, 12:41:25 PM  [blur] 1
INFO 12/14/2020, 12:41:36 PM  [focus] 1
INFO 12/14/2020, 12:41:36 PM  [blur] 1
DEBUG 12/14/2020, 12:41:36 PM  false
INFO 12/14/2020, 12:41:36 PM  addRecentDocument
INFO 12/14/2020, 12:41:39 PM  [focus] 1
INFO 12/14/2020, 12:41:55 PM  load file [/tmp/1607920913505-0.21763338712212255.html] for PDF export
INFO 12/14/2020, 12:41:55 PM  [blur] 1
INFO 12/14/2020, 12:41:56 PM  generate print window with id 2
INFO 12/14/2020, 12:41:57 PM  [focus] 1
INFO 12/14/2020, 12:41:58 PM  [RenderProcess 1][Log] export PDF to /home/lzhang/ramdisk/example.pdf
INFO 12/14/2020, 12:42:00 PM  [blur] 1
INFO 12/14/2020, 12:42:11 PM  [focus] 1
INFO 12/14/2020, 12:42:14 PM  [blur] 1
ERROR 12/14/2020, 12:42:16 PM  [Error: Failed to generate PDF]
INFO 12/14/2020, 12:42:27 PM  [focus] 1
INFO 12/14/2020, 12:42:30 PM  [blur] 1
INFO 12/14/2020, 12:42:47 PM  [focus] 1
DEBUG 12/14/2020, 12:42:47 PM  app.openFile
INFO 12/14/2020, 12:42:47 PM  addRecentDocument
INFO 12/14/2020, 12:42:47 PM  [blur] 1
INFO 12/14/2020, 12:42:47 PM  [focus] 3
INFO 12/14/2020, 12:43:06 PM  load file [/tmp/1607920985096-0.37752996047853293.html] for PDF export
INFO 12/14/2020, 12:43:06 PM  [blur] 3
INFO 12/14/2020, 12:43:07 PM  generate print window with id 4
ERROR 12/14/2020, 12:43:10 PM  [Error: Failed to generate PDF]
INFO 12/14/2020, 12:43:13 PM  [focus] 3
INFO 12/14/2020, 12:43:13 PM  [RenderProcess 3][Log] export PDF to /home/lzhang/ramdisk/IDS服务接口文档.pdf
INFO 12/14/2020, 12:43:13 PM  [blur] 3
INFO 12/14/2020, 12:43:46 PM  [focus] 3
INFO 12/14/2020, 12:44:03 PM  load file [/tmp/1607921041839-0.733850293822865.html] for PDF export
INFO 12/14/2020, 12:44:03 PM  [blur] 3
INFO 12/14/2020, 12:44:04 PM  generate print window with id 5
INFO 12/14/2020, 12:44:06 PM  [focus] 3
INFO 12/14/2020, 12:44:06 PM  [RenderProcess 3][Log] export PDF to /home/lzhang/ramdisk/IDS服务接口文档.pdf
ERROR 12/14/2020, 12:44:07 PM  [Error: Failed to generate PDF]
INFO 12/14/2020, 12:44:07 PM  [blur] 3
INFO 12/14/2020, 12:44:57 PM  [focus] 3
INFO 12/14/2020, 12:45:05 PM  [blur] 3
INFO 12/14/2020, 12:45:26 PM  [focus] 3
INFO 12/14/2020, 12:45:29 PM  [blur] 3

**Comment by abnerlee** [comment]
How many images did you use? Possible to send us <hi@typora.io> a sample md file?

**Comment by sosilent** [comment]
@abnerlee hi, i have sent an email to hi@typora.io. please check.

**Comment by sosilent** [comment]
I found that the logs said "ERROR 12/14/2020, 12:44:07 PM [Error: Failed to generate PDF]".
The main problem is probably caused by pdf geneeration task.
