### ISSUE TITLE
Services are not displayed in context menu when multiple lines selected

### ISSUE THREAD

**Issue by vik17ag** [typora/typora-issues#3926]
When multiple lines selected - 

![image](https://user-images.githubusercontent.com/14138472/96537801-c39a1380-12b4-11eb-9726-d90f19ef55af.png)

When single line selected - 

![image](https://user-images.githubusercontent.com/14138472/96537842-d9a7d400-12b4-11eb-876e-d5a6689e7128.png)

**Comment by abnerlee** [comment]
should be fixed
