### ISSUE TITLE
Spaces removed between checkboxes and text when I open the file

### ISSUE THREAD

**Issue by taiar** [typora/typora-issues#3927]
I am using Typora as a todo list manager. When I'm going to write a list, I do it like this

```
- [ ] Item 1
- [ ] Item 2
```

and it looks like this:

![image](https://user-images.githubusercontent.com/13353/96583127-9ea4a100-12b2-11eb-9fa9-6765c6f500c9.png)

however, when I close this file saving its contents and then reopen it, the spaces between the checkboxes and the text of the list is gone:

![image](https://user-images.githubusercontent.com/13353/96583083-8e8cc180-12b2-11eb-987d-851e94e40990.png)

I'm using Windows 10 and Typora 0.9.96.

Thank you!

**Comment by abnerlee** [comment]
Seems not Typora's built-in themes, could you try use built-in themes and see if it still happens?

**Comment by taiar** [comment]
This is the solarized light which ships with Typora, IDK if that is
built-in but I have not installed nothing new. Just selected from the
available ones after the installation.

Em dom, 8 de nov de 2020 06:03, AbnerLee <notifications@github.com>
escreveu:
