### ISSUE TITLE
[Feature request] Count words/files in whole directory

### ISSUE THREAD

**Issue by Bestulo** [typora/typora-issues#3929]
I would like for there to be a dialogue that allowed to see the word/document count in a whole directory. The code for this is simple and it would be great help. I currently do it with bash commands. I could write you a nodejs solution if it helped you to implement it.

**Comment by abnerlee** [comment]
It will be difficult to config which documents should be included. Typora can read text files, which does not need to be documents in markdown formats.

Anyway, put into #1783
