### ISSUE TITLE
mermaid flowcharts to surport  set edges to and from subgraphs

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#3930]
This feature will decrease the use of draw.io  for many case.

https://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/flowchart.html#beta-flowcharts

With the graphtype flowcharts it is also possible to set edges to and from subgraphs as in the graph below.
```mermaid
flowchart TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
    one --> two
    three --> two
    two --> c2
```

**Comment by abnerlee** [comment]
In my test it is working. but have same issue with #3810 on text display
