### ISSUE TITLE
download jpg cause an error

### ISSUE THREAD

**Issue by frustreated** [typora/typora-issues#3931]
as the above
go to url of 
https://cloud.tencent.com/developer/article/1664752
copy content (the content should consist of picures ) and paste to typora
error will popup

![image](https://user-images.githubusercontent.com/5463104/96693641-0f82b080-13ba-11eb-8a0a-e6d357301d5c.png)

**Comment by abnerlee** [comment]
The server will deny access to target images from other domains, so Typora cannot load the image without knowing which referer the server is accpeted.
