### ISSUE TITLE
Too short menu items width 

### ISSUE THREAD

**Issue by entrealist** [typora/typora-issues#3932]
OS: Ubuntu 20.04
Display: 12" 1366 x 768
Typora version: first noticed in 0.9.86 beta or earlier, now updated to 0.9.96 beta, the bug is still observable. Installed using  https://typora.io/#linux instructions
The bug does not affect usage but it's getting annoying. Can't reproduce in a snap version, but snap version Typora doesn't share the same config with repo installed.

![Screenshot_from_2020-10-21_13-21-32](https://user-images.githubusercontent.com/6422220/96708403-de968180-13a1-11eb-8f7b-7bcc87f0ed39.png)

**Comment by abnerlee** [comment]
What about Chrome?

Or can you try default linux theme or menu font? We didn't set any width about menu items, they are default.
