### ISSUE TITLE
Typora got stuck when opening some .md files

### ISSUE THREAD

**Issue by MetaT1an** [typora/typora-issues#3933]
Sometimes when I try to open some .md files with Typora **for the first time**, the file can be normally opened and the content is correctly displayed. However, the graphic interface is with no responding, the tool window bar is missing, the software seems to get stuck. What I can do is to force it closed and reopen the file.

After reopening, things return to normal. I can edit, browse the menu as usual, but when I turn to another file, the same problem will arise with a subtle probability again.

The issue confused me only apears in my machines with Windows OS.

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> a sample file?
