### ISSUE TITLE
export to github compatible markdown

### ISSUE THREAD

**Issue by jvanmelckebeke** [typora/typora-issues#3934]
One of the awesome features in Typora is the possibility to create of diagrams easily 
(e.g. using mermaid code fences, among others).

A downside of this feature is that these diagrams are not compatible with the github flavoured markdown, this issue is also addressed in [the support page for diagrams](https://support.typora.io/Draw-Diagrams-With-Markdown/) and a possible workaround is to manually create an image for each diagram and replace the code fence with the image.

However, I think it would be very handy if there was an export function ( export to gfm ) specifically to do this task.
Using this export function Typora replaces all non-native gfm code blocks by images generated from the rendering.

These images could be possibly saved to `./<name-of-the-source-file>.assets/<some-identifier-for-the-diagram>.png` (similar to when you paste a raw image into typora).

I know it could sound counter intuitive that you would be going from markdown to markdown ( from an extended markdown typora uses to the github markdown), but it could be very handy for a lot of cases.

**Comment by jvanmelckebeke** [comment]
I also want to add that this export to _gfm_ will not be possible always: 

I think it would be a waste of storage if you would convert `<span style='color:red'>some text</span>` to a dedicated image 
(I would suggest you just skip the surrounding html tags so only `some text` will be in the gfm md file)

**Comment by abnerlee** [comment]
duplicate with #169
