### ISSUE TITLE
a problem about Spell Check

### ISSUE THREAD

**Issue by Realzhazha** [typora/typora-issues#3935]
The Spell Check will show an error when checking "i.e.", "e.g.", "Mr. “ and so on.
It will suggest I should and a dot, but after I add the dot, it will still be flagging this.
![image](https://user-images.githubusercontent.com/35806568/96807262-b0b84800-1448-11eb-94da-77f38b1187f5.png)

**Comment by abnerlee** [comment]
duplicate with #3828
