### ISSUE TITLE
interaction bug with ^O

### ISSUE THREAD

**Issue by marc-shapiro** [typora/typora-issues#3936]
The shortcut "control-O" (letter O) normally makes space for a new paragraph while continuing to edit the current paragraph.  Technically, it opens a new line and leaves the cursor in place, at the end of the current line (the new line is below the cursor).  

However in Typora "control-O" behaves exactly like "newline", i.e., it opens a new line and advances the cursor to the new line.

This is inconsistent (and useless, since newline already does that).

Environment: Typora Version 0.9.9.35.2 (4715) on MacOS 10.13.6

**Comment by abnerlee** [comment]
should be fixed
