### ISSUE TITLE
Syntax highlighting in Source code mode continues past end block when indented

### ISSUE THREAD

**Issue by sn1kketysnake** [typora/typora-issues#3937]
Version: 0.9.96(beta)

Markdown source with issue:
~~~
# Header 1

## Header 2

Some code here:
```c
printf("hello world!\n");
```

Some text here. Looking good.

Some more code here indented:
* List some code
  ```c
  printf("hello again world!\n");
  ```

printf("hello world!\n"); Uh oh I'm still highlighted like I'm writing in C!
~~~

How it looks in Typora in source code mode. See at the bottom the syntax highlighting continues after the code block ends:
![image](https://user-images.githubusercontent.com/1899292/96940291-f6026700-1494-11eb-9e39-e5beba996f85.png)

However, the rendered mode looks fine:
![image](https://user-images.githubusercontent.com/1899292/96940309-fef33880-1494-11eb-9f9b-38d35baa9b6e.png)

**Comment by abnerlee** [comment]
duplicate with #1638
