### ISSUE TITLE
Can't Page Down out of "select a language" box after code

### ISSUE THREAD

**Issue by LazaroFilm** [typora/typora-issues#3938]
To reproduce the issue, place the cursor inside a `select a language` box, then press **[page up]** (ERROR: the window goes up but the cursor is still stuck in the `select a language` box. Then **[page down]** (ERROR: the cursor is still stuck inside the box)

Also, the `select a language` box should be at the top, right after the first ` ``` ` (three back ticks) since it's where you write it when typing the `md` code, not at the bottom.

**Comment by abnerlee** [comment]
should be fixed
