### ISSUE TITLE
adding new indented line in list after line containing emoji breaks positioning

### ISSUE THREAD

**Issue by Incblob** [typora/typora-issues#3940]
The is a pretty specific bug :P
to replicate:

```
- something:
  shift+enter works
  still works
  :smile: no longer works
  *broken*
```
sometimes even in source code mode, the positioning of the cursor breaks when adding an indented line (shift+enter) after an indented line containing an emoji. You have to manually add the two spaces to get out of the broken positioning.

**Comment by abnerlee** [comment]
should be fixed
