### ISSUE TITLE
Can't render dashed lines/arrows in Mermaid class diagrams

### ISSUE THREAD

**Issue by Summer-Shen** [typora/typora-issues#3942]
Was trying to render a mermaid diagram and wasn't able to produce dashed lines. A screenshot:
<img width="612" alt="screenshot" src="https://user-images.githubusercontent.com/44917537/97102179-68b25300-16de-11eb-9b0d-dd8c79a2da2f.png">
Thanks for your attention.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/1661#issuecomment-657400347
