### ISSUE TITLE
Version 0.9.96 keeps full screen all the time on windows10

### ISSUE THREAD

**Issue by Miley927** [typora/typora-issues#3943]
Hi guys,

Recently I found my typora(version 0.9.96) keeps full screen all the time, which behaves and results in

- have no icon buttons on the right-top corner. It's really hard for me to use a software without maximize, minimize and close buttons on windows. 

- window's task bar is also hidden by the full screen mode, so that I can't switch to any other software installed in my computer.

Hope to improve user experience.
![Screenshot 2020-10-26 100855](https://user-images.githubusercontent.com/42561248/97127185-e3797d80-1773-11eb-9c15-d771f6c36206.png)

**Comment by abnerlee** [comment]
Please press F11 to exit Fullscreen mode.
