### ISSUE TITLE
Weird spacing of equation blocks while printing/exporting to PDF

### ISSUE THREAD

**Issue by TomLiu2016** [typora/typora-issues#3944]
When export the Markdown document to pdf, there are some extra spacing before equations blocks, which looks like this:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/20353163/97253778-02f7c100-17db-11eb-9199-e66bf2826110.png">

This does not appear in the Typora window - the Markdown document itself looks completely fine:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/20353163/97253992-6eda2980-17db-11eb-9523-97652d78cb35.png">

This wastes lots of space when I want to print the document out. I'm using the newest version of Typora 0.9.9.35.2 (4715) and the newest beta version of MacOS (macOS Big Sur beta 11), but this issue has been there for more than one year.

**Comment by abnerlee** [comment]
duplicate with #3662
