### ISSUE TITLE
Support "~" in image path (expand to $HOME automatically)

### ISSUE THREAD

**Issue by aur3l14no** [typora/typora-issues#3945]
When I open older markdown files with typora, I find that all the images whose path contains "~" are broken.

I hope typora can automatically expand "~" to $HOME automatically.

Many thanks!

**Comment by abnerlee** [comment]
"~" is a valid folder name, at least on macOS. Also there's no such rule in common markdown syntax, so we do not have plan for this, unless similar feedbacks are received from more users.
