### ISSUE TITLE
File menu anchoring issues

### ISSUE THREAD

**Issue by sandeshakya** [typora/typora-issues#3950]
Currently in version 0.9.96(beta) on Windows 10. I have a dual monitor setup with one screen at 100% scale, and another at 125%. Opening the file menu in the 125% scale monitor places the menu out of screen.
![image](https://user-images.githubusercontent.com/35713511/97454126-08006180-18fc-11eb-8b8e-8a566b750504.png)

**Comment by abnerlee** [comment]
Is this reproducible after reboot or restart Typora / PC?

**Comment by abnerlee** [comment]
still happens in 0.11?
