### ISSUE TITLE
cannot locate the path of theme folder with Path Finder

### ISSUE THREAD

**Issue by Freakwill** [typora/typora-issues#3951]
I use Path Finder, when I press the button 'Open Theme Folder', the Path Finder will be opened not showing the path of the theme folder. So I cannot find the folder.

PS: in macOS, installed by homebrew

**Comment by abnerlee** [comment]
Typora use the standard cocoa library to open files in Finder. So this should be a issue on Path Folder side.

**Comment by Freakwill** [comment]
> Typora use the standard cocoa library to open files in Finder. So this should be a issue on Path Folder side.

Thank you. But what is the path of the theme folder (if installed by brewhome)?
