### ISSUE TITLE
[Enhancement] May be adding a separator to the outline view will be better?

### ISSUE THREAD

**Issue by ScottCTD** [typora/typora-issues#3952]
The outline without separator is just like the pic following which is little bit confusing and not easy to check.
![image](https://user-images.githubusercontent.com/35100768/97549354-40db2c00-1a0b-11eb-9ffc-4d3b27e45deb.png)

But what if the outline looks like this?
![image](https://user-images.githubusercontent.com/35100768/97549530-7718ab80-1a0b-11eb-814f-5e38ac1c1bff.png)
It's clearer to my opinion. (sorry for my bad drawing)

the separator of H1 can be darker than that of the H2

Thanks for responding!

**Comment by abnerlee** [comment]
We don't have plans for this as we think current design is clean enough (unless we received more user feedbacks about this). But since you can customize the CSS, I believe you can modify the indetent or border as you want.
