### ISSUE TITLE
Add "outline-active" class to outer div instead of inner span

### ISSUE THREAD

**Issue by kris7453** [typora/typora-issues#3953]
It is hard to style background of active outline item when additional active class is placed in inner span instead of outer div wrapper.

```html
<div class="outline-item">
<span class="outline-expander"></span>
<span class="outline-label outline-active" data-ref="n2">Lorem ipsum</span>
</div>
```

**OS version:** Windows 10 Home 2004
**Typora version:** 0.9.95 (beta)

**Comment by abnerlee** [comment]
should be supported
