### ISSUE TITLE
flow graph has too many blank lines after print to pdf or others

### ISSUE THREAD

**Issue by CallonHuang** [typora/typora-issues#3954]
![16041063294488152506631375999502](https://user-images.githubusercontent.com/27863769/97767656-70e41580-1b58-11eb-99b7-56ed9cb1e97b.jpg)
too many blank line before or after flow

**Comment by CallonHuang** [comment]
my typora version is 0.9.95beta，all theme has the problem

**Comment by abnerlee** [comment]
Could you provide a sample file?

**Comment by abnerlee** [comment]
duplicate with #2755
