### ISSUE TITLE
No way to escape code fence with keyboard

### ISSUE THREAD

**Issue by aaron11496** [typora/typora-issues#396]
If I start a code fence by typing triple-backtick then I get stuck and can't escape the box without using the mouse. I would expect typing triple-backtick again to end the code fence. 

I'm using version 0.9.21(beta) on Debian.

**Comment by abnerlee** [comment]
press arrow down

**Comment by aaron11496** [comment]
That works, thanks @abnerlee. 

That was not intuitive since I never use the arrow keys for anything.

**Comment by abnerlee** [comment]
@aaron11496 I have received similar question about this. Do you have any suggestions on how to escape a code fences?

**Comment by AlexPasternak** [comment]
I don't understand how one can tailor a _text editor_ to fit the needs of a user who wants to do something "without using the mouse" but also never uses "the arrow keys for anything".

I guess you could do Cmd-Enter to jump to below the code fence, or allow user to hit Esc in that situation, but I fail to see how either of those would be more intuitive than down arrow.

**Comment by aaron11496** [comment]
@AlexPasternak both Emacs and Vim having been doing so for decades :-)

@abnerlee To prevent confusion you could have instructions appear in small gray text below the box while the cursor is inside it. Something like "_ESC to jump below, Ctrl+Enter to choose syntax_".  The arrow keys work fine the way they are. I guess they just didn't occur to me since I'm used to this: https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html

**Comment by AndriyLin** [comment]
I am also used to the emacs style cursor moving shortcuts (because they are naturally supported as Mac system level shortcuts), which allows me to never move my hand to the arrow key section.

I love everything else about Typora, so I really hope these Mac system level cursor moving shortcuts could be supported in Typora! Especially in its Mac version.

Thanks.

**Comment by abnerlee** [comment]
@AndriyLin I'm not familiar with emacs, do you mean cmd+n/p for move down/up?

**Comment by AndriyLin** [comment]
@abnerlee It's `ctrl+n` for down (Next line), `ctrl+p` for up (Previous line), `ctrl+f` for right (Forward), `ctrl+b` for left (Backward).

Right now it seems they work among normal texts, but not (fully) in code block sections.

**Comment by abnerlee** [comment]
related https://github.com/typora/typora-issues/issues/627
