### ISSUE TITLE
Typora uses deprecated Electron features, shows warning to user

### ISSUE THREAD

**Issue by mikeblas** [typora/typora-issues#3960]
1. On Windows, use "start readme.md" at a command prompt to open Typora to edit your favorite readme.md file.
2. Edit the file. Fool around a bit.
3. Go back the console window where you started Typora

BUG#1) Find text like this:

`(node:23752) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Typora\resources\app\node_modules\spellchecker\build\Release\spellchecker.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.`

I know that Step #2 is a bit vague ... I'll keep fussing around to see if I can figure out a specific command or action that causes the message to appear.

**Comment by abnerlee** [comment]
duplicate with #3817
