### ISSUE TITLE
On Windows, menus do not include mnemonics 

### ISSUE THREAD

**Issue by mikeblas** [typora/typora-issues#3961]
By standard, Windows menus have mnemonics. This allows keyboard access to the menu and the commands within it. Mnemonics appear with underlines.  The "F" in "File" is underlined, indicating that it can be accessed with ALT+F.  In the File Menu, the "Exit" command has "x" underlined, indicating that it can be reached with "x".  Thus, ALT+F, X will exit.

Typora doesn't have any mnemonics, on any menus. This is something that's requisite for usable Windows applications. Without them, the user must use the mouse or complicated one-by-one keystrokes to use the menus.

**Comment by abnerlee** [comment]
I think there is underlines when you press "ALT", and you can use ALT+F to open the file menu in Windows.

If not, please tell us your Typora/Windows version

**Comment by abnerlee** [comment]
for key access to items inside a menu, that part is addressed in #798

**Comment by mikeblas** [comment]
I'm using 0.9.96 (beta). The issue isn't with top-level menus not having mnemonics ... it's with the commands inside the menu not having mnemonics. 

Looks like 798 covers that, but it's been active for more than 3 years with no forward progress.
