### ISSUE TITLE
Indentation of items without bullet in a list does not match the bulleted items

### ISSUE THREAD

**Issue by gilbertohasnofb** [typora/typora-issues#3963]
Indentation of items without bullet in a list does not match the bulleted items. Typora renders both cases above identically, this is just a matter of how it treats the source code while inputting indented text in the middle of a list.

Normally, I would indent non-bullet items with the same level as the text of the bullet item (i.e. just omit the bullet):

```
* Foo

  Bar

* Xyz
```

Typora, on the other hand, enters the following source code when creating a list.

```
* Foo

    Bar

* Xyz
```

Here is a gif with a concrete example:

![image](https://user-images.githubusercontent.com/5700795/97897708-c96d0b80-1d2e-11eb-85a5-0c206a2f69c4.png)

The source code produced is:

```
Some regular text

* first bullet point

    * subitem
    
    * `Backspace` to remove bullet
    
        this text is at the same indentation
        
    * Double `Enter` to add bullet back
    
* back to first level

    `backspace` still removes it
    
* double `Enter` again

`Shift-tab` to move back to original indent level
```

IMO, the ideal source code for this would look like the example below, where all text (bulleted or not) have matching levels.

```
Some regular text

* first bullet point

    * subitem
    
    * `Backspace` to remove bullet
    
      this text is at the same indentation
        
    * Double `Enter` to add bullet back
    
* back to first level

  `backspace` still removes it
    
* double `Enter` again

`Shift-tab` to move back to original indent level
```

**Comment by abnerlee** [comment]
You mean indent via tab?

This can be configured in preferences panel.

**Comment by gilbertohasnofb** [comment]
Where can that be configured exactly? If you are referring to the option of 'Pretty indentation', that does not do exactly what I am suggesting here. For instance, with a tab size of 4, the most common way of handling spaces is to have indentation of size 4, but a single space after the `*` entries; indented text without bullet points match the position of other items as if they had a bullet point turned into a space. E.g.:

```
* item 1
  text
* item 2
    * item 3
      more text
    * item 4
```

With 'Pretty indentation' on, and using a tab size of 4, all entries get 3 spaces added after a `*`:

```
*   item 1
    text
*   item 2
    *   item 3
        more text
    *   item 4
```

**Comment by gilbertohasnofb** [comment]
@abnerlee If you could take a look at my last comment, I think this issue should be reopened as, from my understanding, the setting you suggest does not exactly address the issue. The sort of indentation I am suggesting is probably the most common one used in markdown (single space after bullet character, matching indent position for indented text without bullets), and to be honest I never saw the type of indentation done by the 'Pretty Indentation' algorithm before I started using Typora.
