### ISSUE TITLE
Allow emphasis shortcuts in Source Code Mode

### ISSUE THREAD

**Issue by gilbertohasnofb** [typora/typora-issues#3964]
Currently, shortcuts such as `Ctrl-i`, `Ctrl+b`, ``Ctrl-Shift-` ``, etc., only work in regular mode but not in source code mode. Apparently they are not binded to any keys. I think it would be very handy to have the same shortcuts available for both modes, making the editor more consistent too.

**Comment by abnerlee** [comment]
Source code mode is designed for temp usage, so we do not have plans to enhance functions under source code mode.
