### ISSUE TITLE
Enhance PDF export

### ISSUE THREAD

**Issue by darkarp** [typora/typora-issues#3966]
I've been trying to use typora to quickly write documents and export them in html and pdf for thr targeted audience. 
The problem is that, when exporting to pdf,  many times my h2 headings happen to be the very last thing on a page and the next page containing the text. This, of course, doesn't look good at all and would easily be fixed by being able to check when a page break happens when exporting to pdf.

I'm aware you can style it to break before h1's and all, but I don't want to systematically break after or before anything. I simply don't want to have a subtitle for which its content is on another page. Is there any way to add a little dotted marker or anything that will tell me when a new page will begin? I know this only applies to PDFs but currently it's impossible to write a 300-page document, export it to PDF, while not having hundreds of headings sit as the last text on a webpage.

**Comment by abnerlee** [comment]
seems duplicate with #1732?
