### ISSUE TITLE
Wrong footnote definition syntax coloring in source mode

### ISSUE THREAD

**Issue by kris7453** [typora/typora-issues#3967]
Only the first word in footnote definition is colored as string in source code.

**OS version:**  Windows 10 Home 2004
**Typora version:** 0.9.95 (beta)

![typora-wrong-sm-coloring](https://user-images.githubusercontent.com/20442936/98012311-3e0c7c80-1df9-11eb-8803-c4ae788f62f1.jpg)

**Comment by abnerlee** [comment]
should be fixed
