### ISSUE TITLE
Cursor goes back to first line when I switch between Edit and Source code Mode

### ISSUE THREAD

**Issue by shishtpal** [typora/typora-issues#3969]
Hi

Sometimes I have to write custom markdown code or insert some custom HTML code and for that I need to switch between Edit mode and Source code Mode, But After switching between them, Mouse Cursor goes back to Line 1

It would be nice If we can preserve mouse position in both Modes.

Thanks

**Comment by abnerlee** [comment]
What's your Typora version, and could you provide a sample *.md file and share in which location the cursor will jump to top on mode switch?

**Comment by shishtpal** [comment]
This is a demo markdown file with some HTML content, Go to LINE:15 in Typora and try to switch between edit/source Mode,
I am using Typora v0.9.96 (beta)

```md
# Demo page



## Youtube Videos

<iframe width="921" height="518" src="https://www.youtube.com/embed/Gxk57FAMIy0?list=PLO5Vd0-UEW9udOsbAY8wJa4ztOMrDuSOT" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

* NOTE: 



***

<iframe width="1008" height="434" src="https://www.youtube.com/embed/g3l03VaOyUc?list=PLO5Vd0-UEW9udOsbAY8wJa4ztOMrDuSOT" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



* NOTE:





***

## Notes

### Heading 1

Demo

* Line 1
* Line2



### Heading 2
* Demo
  * Line 1
  * Line2

```


Thanks

**Comment by abnerlee** [comment]
⬆️ case should be fixed
