### ISSUE TITLE
最新的Windows的64和32位版本都被植入木马了

### ISSUE THREAD

**Issue by xphbsy** [typora/typora-issues#397]
大神您好，我昨天在官网 http://www.typora.io/ 上下了此软件的Windows下的64位版本，结果安装运行后360安全卫士总报告这个软件在后台上传数据，还检测出木马了，32位版本的也是这样……

**Comment by abnerlee** [comment]
Please report to 360 to confirm whether it is a false negative

**Comment by xphbsy** [comment]
建议您在[360软件开放平台](http://open.soft.360.cn/)提交一下您的软件，您是软件作者嘛，我只是个用户，360不会理我的哈哈:joy:
