### ISSUE TITLE
Export PDF with images on UNC path

### ISSUE THREAD

**Issue by LiohMoeller** [typora/typora-issues#3970]
I have created a Markdown document on a UNC path (WSL2 drive accessed from Windows) and added some pictures like:

`![MyPic](img/IMG_001.PNG)`

Export works fine using the Markdown syntax. If I then change the size of the image in Typora it transforms it into HTML code like:

`<img src="img/IMG_001.PNG" alt="MyPic" style="zoom:50%;" />`

When I now export to PDF, the images are not included anymore. I have copied the whole document and images to a local drive (C:\..) and export works fine there.

**Comment by abnerlee** [comment]
same with #2995
