### ISSUE TITLE
Margins are big when printing

### ISSUE THREAD

**Issue by JoshuaCMorgan** [typora/typora-issues#3971]
OS version: 10.15.7 
Typora version: 0.9.9.35.2 (4715)

When I print a document, the margins are set quite wide, probably 2 inches.  I don't see a way in Typora>preferences or elsewhere to change the margin settings.  Any help?

**Comment by abnerlee** [comment]
which theme?

**Comment by JoshuaCMorgan** [comment]
It doesn't matter what theme.

**Comment by abnerlee** [comment]
can be set in preferences panel now.
