### ISSUE TITLE
Windows Explorer Preview not working

### ISSUE THREAD

**Issue by bapjg** [typora/typora-issues#3972]
I am using version 09.96(beta) on Windows 10.
In Windows (file) explorer, when I double-click on a .md file, Typora opens and renders the file fine.
When I single click while having the content view pane open I just get a text message "Aucun apperçu n'est disponible" (French Windows : "No preview available").
In Typora logfile, there are no entries for single click events.
Any Ideas on what to do.
Thanks for any help
PS : On another PC all works fine (Same Typora and Windows version).

**Comment by abnerlee** [comment]
> On another PC all works fine (Same Typora and Windows version).

**Comment by bapjg** [comment]
Thanks for getting back to me. In fact I investigated further and found the difference between the 2 PCs. The one which did render in the File Explorer had MicroSoft Power Toys inatalled whereas the other PC did not. Installing  MS/Power Toys fixed the problem.
