### ISSUE TITLE
breaks after &ldquo;

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#3973]
This is more of a suggestion than an issue, but it does cause problems in docs.

New lines do not recognize HTML entities as part of the word, for example...

**This is a sentence that takes up two
"lines".**

vs

**This is a sentence that takes up two &ldquo;
lines&rdquo;.**

You can see that the line break happens at the beginning of the word, not the beginning quote for that word.

It would be great if the HTML quote entities `(&ldquo; &lsquo; &rdquo; &rsquo;)` were considered as part of the word.

Regardless, I'm a huge fan of Typora! Thank you

**Comment by abnerlee** [comment]
relates #3504

**Comment by abnerlee** [comment]
put into #5358
