### ISSUE TITLE
Latex newcommand creates too many definitions, overriding latex commands

### ISSUE THREAD

**Issue by sschuldenzucker** [typora/typora-issues#3974]
Ok, I'm pretty sure what's going on here and it leads to *very* confusing behavior in some cases regarding newcommands. Perhaps related: #3455 

Let's say I have a latex block like:
```
$$
y = \operatorname{lev}(x)
$$
```

Now I wanna pull out the definition of the 'lev' text, so I add a newcommand like this:
```
$$
\newcommand\lev{\operatorname{lev}}
y = \operatorname{lev}(x)
$$
```
(with the intention of replacing the `\operatorname{lev}` in the next step.)

## Expected behavior
There is one new definition `\lev` mapping to `\operatorname{lev}`. If I delete the `\newcommand` line, the definition goes away.

## Actual behavior
The following mappings are created:
* `\`, `\l`, `\le`, all mapping to `y`. In particular, `\le` **overwrites/shadows the original meaning** of `\le` as "less or equal symbol". I don't have access to that symbol any more.
* `\lev` mapping to `\operatorname{lev}`
These mappings persist even if I delete the `\newcommand` line.

The issue can *only* be fixed by restarting Typora, and then it's gone.

## Probable cause
This seems to happen because of two reasons:

1. Typora does live preview, so as I'm typing the `\newcommand` line, character for character, it actually evaluates the following lines:
```
$$
\newcommand\
y [...]
$$
```
Then:
```
$$
\newcommand\l
y [...]
$$
```
etc., all up to `\lev`, which is then *later* overwritten with its actual definition.

2. This would be just fine if the defined newcommands were cleared when their defining `\newcommand` is no longer there. But this is not the case.

## Potential fix

You should prob periodically check which `\newcommands` are actually still defined.

Dunno if this is purely a mathjax issue or if there's anything you can do yourself.

**Comment by abnerlee** [comment]
move into #3455
