### ISSUE TITLE
Using the ∑ symbol instead of \sum inside a math block

### ISSUE THREAD

**Issue by cgf1000** [typora/typora-issues#3976]
If I use the ∑ symbol instead of \sum inside a math block the summation is displayed in text style and not in display style. Is this the expected behaviour or it should be display style since it is inside a math block?
![Summation](https://user-images.githubusercontent.com/7177733/98296493-c6258a00-1f91-11eb-9801-e96751479aed.png)

**Comment by oeoa** [comment]
use `\sum\limits_{i=0}` instead

**Comment by cgf1000** [comment]
I wanted to use the symbol for a better readability.

**Comment by abnerlee** [comment]
LaTeX syntax are used in math blocks. Or you can use "∑\limits_{i=0}", but I'm not sure if that is a valid TeX sentence or not.

**Comment by cgf1000** [comment]
OK. Thank you for the help.
