### ISSUE TITLE
[Feature request] AsciiMath Support

### ISSUE THREAD

**Issue by sebi5361** [typora/typora-issues#3978]
[AsciiMath](http://asciimath.org/) notation is much more simple than Latex to enter notations, e.g. `\cos x` becomes `cosx`.
The simplest way to trigger AsciiMath notation is to use a standard Latex block `$...$` or `$$...$$` but to start it with an `@`, e.g.: `$@cosx$`.
Hence the odds of someone willing to write a Latex block starting with an `@` are minimal, and he can always prepend a space to do so.
I know a markdown editor which made that choice already, and I find it really handy.

This [pandoc filter written by yuwash](https://github.com/yuwash/asciimathml-pandocfilter) based on the original [AsciiMath code](https://github.com/asciimath/asciimathml) does the AsciiMath to Latex conversion which might be usefull depending on the way you want to render the equations.
 `asciimathfilter.js` just needs to be adjusted to trigger conversion on keyword `@`:
``` js
    if (type === 'Math' && value[1].slice(0,1) === '@') {
        return Formula(value[0], "" + asciimath.AMTparseAMtoTeX(value[1].slice(1)));
    }
```
There are AsciiMath rendering tools (MathJax or MathML) available that could be useful as well.

Would it be possible for typora to support AsciiMath?

**Comment by abnerlee** [comment]
duplicate with #786
