### ISSUE TITLE
PDF export makes math blocks extremely small

### ISSUE THREAD

**Issue by samtalki** [typora/typora-issues#3979]
Using PDF export causes math blocks to become extremely small, even smaller than normal text.

Windows 10, latest verison.

examples:

![image](https://user-images.githubusercontent.com/10187005/98408235-d5164600-203e-11eb-95ed-c38e4133886b.png)

![image](https://user-images.githubusercontent.com/10187005/98408327-00009a00-203f-11eb-9b24-99dcc0b772ee.png)

**Comment by abnerlee** [comment]
duplicate with #3662
