### ISSUE TITLE
Cursor position when typing quotation marks 

### ISSUE THREAD

**Issue by jessshortt** [typora/typora-issues#3982]
When typing quotation marks, the cursor sometimes ends up outside of them (""**|**) instead of inside ("**|**"), the expected behaviour. I've only been using double quotation marks consistently enough to notice but have not had the same issue with single quotes or other brackets.

Making the quotation marks on a new line doesn't seem to cause it to happen, but I can almost consistently reproduce with a space after a period on the same line like the following:

Lorem ipsum. ""**|**

Using MacOS Catalina, Typora version 0.9.9.35.2

**Comment by abnerlee** [comment]
Still happens now?

**Comment by jessshortt** [comment]
Seems to be resolved now.
