### ISSUE TITLE
Let [Shift-]Ctrl-Left Arrow, [Shift-]Ctrl-Right Arrow treat HTML entities and tags as a single word

### ISSUE THREAD

**Issue by rpopov** [typora/typora-issues#3985]
When navigating to next/previous word with Ctrl-Right Arrow / Ctrl-Left Arrow or marking the next/previous word Ctrl-Shift-Right Arrow / Ctrl-Shift-Left Arrow it happens that the cursor treats the HTML entities as three characters - the '&', the text and the ';' (e.g. treats the &epsilon; as the text "&"+"epsilon"+";"). Similarly the HTML tags are treated as two characters - the opening < and the name are treated as one and the closing > as the second (e.g, `<sub>w</sub>` is treated as "<sub"+">"+"w"+"</sub"+">")

Suggestion:
When navigating or marking words treat the HTML entities as the single character they represent, e.g. treat &epsilon; as ε and treat the HTML tags as words, e.g.` <sub>w</sub>`as the words `"<sub>"+"w"+"</sub>"`.

**Comment by abnerlee** [comment]
Which OS?

**Comment by rpopov** [comment]
Windows 10 Home, version 2004, OS build 19041.610, Windows feature experience pack 120.2212.31.0 
Typora version 0.9.96

**Comment by rpopov** [comment]
The problem exists in Oracle Linux 8.3 too with Typora 0.9.89 too

**Comment by rpopov** [comment]
closed long time ago
