### ISSUE TITLE
math cross reference does not work

### ISSUE THREAD

**Issue by demolpc** [typora/typora-issues#3986]
typora version: 0.9.96
I use the example from https://support.typora.io/Math/#cross-reference, the result:
![typora](https://user-images.githubusercontent.com/10293003/98781243-002eda00-2431-11eb-959c-81f1da83572a.png)

**Comment by abnerlee** [comment]
I updated the doc, it should be 

```
Here is a labeled equation:

$$
x+1\over\sqrt{1-x^2}\label{ref1}\tag{1}
$$

This is a referece : $\ref{ref1}$
```

If you don't enable auto-numbering
