### ISSUE TITLE
Feature Request: Native Apple Silicon Support

### ISSUE THREAD

**Issue by ifsheldon** [typora/typora-issues#3989]
As Apple has announced its transition to Apple Silicon and published new Macs on Apple M1, it will be nice to have a native build for Apple Silicon. I'd like to ask whether Typora is planned to natively support Apple Silicon?

**Comment by abnerlee** [comment]
I have tested Typora on Developer Transition Kit, it does not have any notable performance issue, because the UI part is running on WKWebView, which is will already be native on Apple Silicon.

**Comment by ifsheldon** [comment]
Thanks for the information!

**Comment by abnerlee** [comment]
native support already released.
