### ISSUE TITLE
New Feature : Support details/summary tag

### ISSUE THREAD

**Issue by kukushi** [typora/typora-issues#399]
Many README files use `details/summary` tag to provide additional information. 
```
<details>

<summary>Title</summary>

Hidden Content

</details>
```
It would be great if Typora support using it.

**Comment by GiggleLiu** [comment]
+1, This feature will be great!

**Comment by Piping** [comment]
+1, Please add this feature!

**Comment by abnerlee** [comment]
it is now supported. Not no empty line inside the HTML Block is allowed.

So you could use
```
<details>
<summary>Title</summary>
Hidden Content
</details>
```

In Typora's new release

**Comment by infixint943** [comment]
Could 
```
[details="Summary"]
[/details]
```
be supported?

**Comment by abnerlee** [comment]
#1581

**Comment by macolo** [comment]
this doesnt appear to be working when images are inside the details tag

```
<details>
<summary>image</summary>
![](img/add-new-environment-in-pycharm.png)
</details>
```

doesnt render the image in preview

**Comment by abnerlee** [comment]
It's now discussed in #1581 and  #1939
