### ISSUE TITLE
[Bug report] Override the content that contains the code

### ISSUE THREAD

**Issue by liuhao326** [typora/typora-issues#3991]
Hi👋!

When I try to override the content that contains the code. It will also overwrite the text after the content eventually.

Typora version: version 0.9.96(beta) on Windows 10

<details>
			<summary>Gif</summary>

![Bug](https://user-images.githubusercontent.com/51501079/99179593-2d91c580-275a-11eb-8c18-a3c03a26daaa.gif)

</details>

<details>
			<summary>Test text</summary>

```
This is a line of text without code.

This is a line for test.

This is the line of text containing the `code`.

This is a line for test.
```

</details>

**Comment by liuhao326** [comment]
Actually, I also got this issue when overriding the content in the block.
And after this issue happened, the content will disappear if I try to select it.
<details>
			<summary>Gif</summary>

![Bug](https://user-images.githubusercontent.com/51501079/99772553-f51d2d80-2b45-11eb-84c0-01c85b9e7837.gif)

</details>

**Comment by abnerlee** [comment]
It only happens with sougo IME, the built-in MS Pinyin does not have such issue

**Comment by liuhao326** [comment]
That's true. I reported this issue to Sougo.
