### ISSUE TITLE
Inline math shortcut

### ISSUE THREAD

**Issue by lucasmarinb** [typora/typora-issues#3992]
Hi, i've been using typora to make notes that require math equations, but i'm really missing a shortcut that allows you to wrap raw latex text into $ symbols as it occurs with code, emphasis, bold, etc.
I'm aware that you can change the shortcuts keys but, i don't think that its possible to enable this feature.

Please let me know if i'm missing something.
Thanks in advance.

**Comment by abnerlee** [comment]
>I'm aware that you can change the shortcuts keys but, i don't think that its possible to enable this feature.

What do you mean? In my test it is working.

**Comment by lucasmarinb** [comment]
> > I'm aware that you can change the shortcuts keys but, i don't think that its possible to enable this feature.
> 
> What do you mean? In my test it is working.
 
Really? I've been looking at the docs and forums and i just couldn't make it work. 
To be clear, i'm talking about a shortcut that works like `Ctrl + b` over selected text, that wraps it in asterisks `*`, but for inline math (with in dollar symbols  `$`).
If the case is that this already exists i'd be very grateful if you link me to the docs to enable it.

**Comment by abnerlee** [comment]
Could you share your config file for custom shortcut for inline math?

**Comment by lucasmarinb** [comment]
Oh, i just tried and it worked! tbf i haven't tested since it didn't worked for me some time ago.
Sry for the trouble, and thanks for your support.
