### ISSUE TITLE
memory leak caused by export to pdf

### ISSUE THREAD

**Issue by mzz2017** [typora/typora-issues#3993]
If the mardown file has many words and there will be an amazing memory leak.

**OS**
Linux (manjaro kde)

**reproduction:**
1. Just repeat copy and paste some text to make the file filled with over 20000 words.
2. Export to PDF.
3. Watch your memory and you will find that export will fail and your memory will be confiscated without return.
4. You can retry some times and this problem will be more clear.

**Comment by abnerlee** [comment]
same with #3924 ?

Possible to attach or send us <hi@typora.io> a sample file?
