### ISSUE TITLE
superscript and subscript cannot contain space

### ISSUE THREAD

**Issue by gungorenu** [typora/typora-issues#3994]
Hello,
I am not sure if it is a special use case but when the text you want to format with superscript and subscript has spaces then the formatting shall be removed and the text shall be visible as it is with tags ^ and  ~ . enable superscript and subscript from preferences for testing, easily reproducable.
example:
` **bold text is fine with spaces** ^but this shall not be superscript^, ~neither this shall be subscript~ but ^this^ shall be superscript and ~this~ shall be subscript `

Regards,

Typora version tested: 0.9.96
OS: Windows 10

**Comment by abnerlee** [comment]
duplicated with #980.

The syntax of superscript/subscript is defined like this. whitespace is not a common case for them.

OR you can use `<sub>` and `<sup>` tag
