### ISSUE TITLE
When pasting text with two "$"s, Typora takes it as an in-line formula

### ISSUE THREAD

**Issue by JER-ry** [typora/typora-issues#3998]
When pasting text with two "$"s, Typora takes it as an in-line formula ("500 and" in this screenshot). Even "Paste as plain text" does not work.

It is really inconvenient. Maybe Typora should add "\\" automatically in cases like this.

![图片](https://user-images.githubusercontent.com/30141096/99411408-8619bc00-292e-11eb-8e24-fa81fd437424.png)

**Comment by abnerlee** [comment]
It is expected behavior, because user can paste LaTeX code between $$. And when paste text into Typora, the text could be markdown text or plain text
