### ISSUE TITLE
Flowchat content display at the top

### ISSUE THREAD

**Issue by SilenceX12138** [typora/typora-issues#3999]
In previous versions, the content is located in the **center** as follows:

![image](https://user-images.githubusercontent.com/47887520/99473407-7bd6dc80-2985-11eb-9cd8-709945a1e26f.png)

However, in the newest version(0.9.96), the content is **on the top**, which may not be that good to view.

![image](https://user-images.githubusercontent.com/47887520/99473497-a163e600-2985-11eb-84e4-b390fce55f50.png)

**Could you please adjust this display setting?**

**Comment by abnerlee** [comment]
duplicate with #1660

Are you using a high-DPI screen?

**Comment by SilenceX12138** [comment]
Nope, I tried the way mentioned in #1660, the phenomenon would disappear while the editer would be so blurry.

I think I encountered the same problem as that one.

So is it because I missed any valid infomation?

**Comment by abnerlee** [comment]
It is recorded in #1661, and https://github.com/mermaid-js/mermaid/issues/645 didn't fix it
