### ISSUE TITLE
bug: del format not parsed correctly in html output

### ISSUE THREAD

**Issue by die4live** [typora/typora-issues#4]
the `~~string~~` syntax will output a subscript `~string~`, instead of a delete format (eg: ~~string~~)

**Comment by abnerlee** [comment]
Seems a bug. I'll confirm and fix this. Please disable subscript feature temporarily if you do not need it before it is fixed.

**Comment by Fastidious** [comment]
@abnerlee using `Version 0.9.6.1 (0.9.6.1)` I do not notice this behavior. Entering `~~string~~` creates a ~~string~~. I do not thing this is a bug. Tested it under Yosemite and El Capitán.

**Comment by abnerlee** [comment]
@Fastidious it is a bug, I already reproduced it. it may happen when you enable subscript, and export your writing to HTML file in some chance. And it will be fixed in next version up.

**Comment by Fastidious** [comment]
@abnerlee I completely missed the HTML part, my apologies. I exclusively use Typora for Markdown, and got confussed.

**Comment by abnerlee** [comment]
Fixed in v0.9.6.8
