### ISSUE TITLE
New feature: Support for table HTML tags

### ISSUE THREAD

**Issue by novanleon** [typora/typora-issues#400]
When authoring documents that utilize tables, I've encountered situations where I need to manually adjust the width of one or more columns to properly display the content. Utilizing the current markdown extended syntax and CSS. there's no way to adjust the width of one or more columns in a single table without affecting all tables. If Typora supported HTML **table**, **tr**, **th** and **td** tags, I could build my own table and size the columns with a style attribute.

For my documentation purposes, this, and the inability to specify page breaks for printing (perfectly understandable in a product like Typora), are the only significant issues I've encountered.

**Comment by abnerlee** [comment]
#227
