### ISSUE TITLE
Linux Ubuntu 20.04: menu bar does not appear with Wayland

### ISSUE THREAD

**Issue by pguillermin** [typora/typora-issues#4000]
Hello,

Typora 0.9.96
Ubuntu 20.04.1 LTS
GNOME 3.36.3

I'm not sure if it's a Typora problem but I noticed a bug with the Wayland display engine whether with a Gnome or Ubuntu session. The menu bar does not appear with the Alt key with Gnome Wayland or Ubuntu Wayland. The menu bar appears without problem with Gnome Xorg or Ubuntu Xorg.

**Comment by hypergig** [comment]
chrome 87 just came out which native now [supports wayland](https://blogs.igalia.com/msisov/2020/11/20/chrome-chromium-on-wayland-the-waylandification-project/)

```
--enable-features=UseOzonePlatform --ozone-platform=wayland
```

so I think it is only a matter of time before electron apps start being built with support for it too... maybe just hang tight?

**Comment by abnerlee** [comment]
> so I think it is only a matter of time before electron apps start being built with support for it too... maybe just hang tight?

Yes, in this case, we would support it in future.

**Comment by plumlis** [comment]
Same here.
Hope there is a new version can solve this issue

**Comment by abnerlee** [comment]
#4019

**Comment by abnerlee** [comment]
we now use chrome 91, it should be supported using `--enable-features=UseOzonePlatform --ozone-platform=wayland`
`

**Comment by plumlis** [comment]
Thanks for your update.
Is there a way to add this to "flags" and enable it?
I tried with "flags": ["-enable-features=UseOzonePlatform"] but it doesn't work.

**Comment by abnerlee** [comment]
Just append like the launch arguments, or set flags: [["enable-features", "UseOzonePlatform"], ["ozone-platform", "wayland"]]

**Comment by plumlis** [comment]
I tried with arguments from terminal，and It show up some errors and won't start.

[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/typora/Typora --type=zygote
[2:0721/133410.999561:FATAL:ozone_platform_wayland.cc(173)] Failed to initialize Wayland platform

I tried to set flags, typora can be started but It's all blank.

![Screenshot-20210721133615-1648x1636](https://user-images.githubusercontent.com/6737429/126436478-46d7cd58-09f7-4409-8d3e-52cbce28930a.png)

**Comment by Nesaijn** [comment]
@plumlis What version are you using?

With version 0.11.01 it works for me when starting it like this in the terminal: `typora --enable-features=UseOzonePlatform --enable-gpu --ozone-platform=wayland`, while I think that `--enable-gpu` is not necessary.

I encountered two problems. One is that when opening the advanced settings it hangs. The process for opening the config file is running but nothing happens. I have to kill the process that opens the config file manually so that typora works again.
Other than that the flags that are being set in the advanced settings do not seem to work. When running from the terminal they are being printed to the screen but do not seem to be applied. Only adding them manually works.

**Comment by plumlis** [comment]
@Nesaijn  0.11.0，I just saw that there is ver 0.11.1, I'll try it.

**Comment by plumlis** [comment]
I tried with latest version.
It seems I still can't start up typora with Wayland. It showed up blank window.

**Comment by Vortex375** [comment]
> no. It will show up this error
> 
> [2:0827/163714.813157:FATAL:ozone_platform_wayland.cc(173)] Failed to initialize Wayland platform

@plumlis you need to enable "Wayland windowing system" for Typora in Flatseal:

![image](https://user-images.githubusercontent.com/5016523/132129297-d1ff4b59-60b9-4bf3-a617-dbfdeb05478b.png)

Then it will start. However, on Gnome you will currently not have window decorations. There's an upstream Electron issue for fixing this (which I am too lazy to look up right now).

**Comment by plumlis** [comment]
> > no. It will show up this error
> > [2:0827/163714.813157:FATAL:ozone_platform_wayland.cc(173)] Failed to initialize Wayland platform
> 
> @plumlis you need to enable "Wayland windowing system" for Typora in Flatseal:
> 
> ![image](https://user-images.githubusercontent.com/5016523/132129297-d1ff4b59-60b9-4bf3-a617-dbfdeb05478b.png)
> 
> Then it will start. However, on Gnome you will currently not have window decorations. There's an upstream Electron issue for fixing this (~which I am too lazy to look up right now~ here it is: [electron/electron#29618](https://github.com/electron/electron/pull/29618)).

Oh, Really.
I forgot about flatpak permissions.
Now it can run with wayland. But also as you said. No window decorations.

Seems we have to wait new version of electron?

**Comment by Vortex375** [comment]
We have to wait for a new version of Electron and then we have to wait for Typora to upgrade to it.

**Comment by plumlis** [comment]
It seems this issue is fixed on the electron side.
https://github.com/electron/electron/pull/29618

**Comment by plumlis** [comment]
And electron 17 is also released with this patch.
Hope typora will upgrade to electron 17 soon.
