### ISSUE TITLE
 🙏 Please add vim keybindings 🙏

### ISSUE THREAD

**Issue by willyspinner** [typora/typora-issues#4001]
Hi typora team,

I noticed that there were several issues raised here over the last 5 years (like [this](https://github.com/typora/typora-issues/issues/187) one) to add vim keybindings support, but I don't think they were looked at despite the popularity of the requests.

I've been using typora for 2+ years and it has been my go-to for productivity/note-taking/writing technical documents. I think many people's typora workflows would be greatly improved if we could use keybindings of our choice.

Please, I implore you, add this feature 🙏 🙏 ! I believe a lot of people can agree with me that it's probably the only missing feature in typora. 

Thank you!

**Comment by abnerlee** [comment]
I understand your requirement, Hmm, it is still duplicated with #187

**Comment by hollowgalaxy** [comment]
@abnerlee  no one is assigned to it and there doesn't seem to be any response to whenever this will be a thing or not.

**Comment by flphotog** [comment]
This is one that the developers seem to be totally ignoring in spite of the popularity.

**Comment by willyspinner** [comment]
Absolutely. Need to really make this happen !!
