### ISSUE TITLE
Do not offer to save empty file

### ISSUE THREAD

**Issue by sentosango** [typora/typora-issues#4002]
When closing, do not offer to save if the file has not yet been saved to disk and does not contain a single significant character (ignore spaces and tabs, etc.).

Maybe make this behavior configurable as an option in the settings.

This will allow the user not to do an unnecessary action.

**Comment by abnerlee** [comment]
The how to save an empty file?

**Comment by sentosango** [comment]
@abnerlee 

I am not suggesting disallowing saving an empty file.

The user can still save an empty file by explicitly performing a save ("File -> Save", or "Ctrl+S").

I just suggest not showing the "Save / Discard" pop-up window when:
- opened an "empty" editor (no file)
- did not write anything except a space
- close the editor, which is still empty

**Comment by sentosango** [comment]
Okay, of course, never mind.

**Comment by abnerlee** [comment]
I see, I can be covered by #2354 that treat "space" only file as non edited file.
