### ISSUE TITLE
TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#4003]
When resuming my computer today from stand-by, I got the following Typora error:

> ### A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> ```
> TypeError: Object has been destroyed
>     at C:\Program Files\Typora\resources\app\atom.asar\DocumentController.js:300:22
>     at Set.forEach (<anonymous>)
>     at PowerMonitor.<anonymous> (C:\Program Files\Typora\resources\app\atom.asar\DocumentController.js:299:19)
>     at PowerMonitor.emit (events.js:223:5)
>     at PowerMonitor.EventEmitter.emit (domain.js:475:20)
>     at PowerMonitor.topLevelDomainCallback (domain.js:130:23)

Only occurred once until today, thus I could not reproduce it.

**Comment by abnerlee** [comment]
seems same issue with #3922
