### ISSUE TITLE
Math not rendering when re-opening file

### ISSUE THREAD

**Issue by sschuldenzucker** [typora/typora-issues#4006]
Not sure if this is reproducible…

## Steps

I have a file with some inline and display math in it. I wrote the file, everything rendered correctly. Then I closed the file and opened it again later.

Note that the file contained a bunch of `\newcommand`s. Perhaps this is important.

## Undesired behavior

No math is rendered.

Display math shows up invisible and inline math shows up as the (syntax-highlighted) code. When I focus a piece of math, I can edit it normally, but I do not see any preview rendered. When I click away from the math equation, it's not shown rendered, but only the code.

## Workaround

Close Typora and delete the `Cache` folder (`%APPDATA%\Roaming\Typora\Cache` on Windows). Then restart Typora.

This fixes the issue. So I guess it's a problem with some invalid cache entry or something.

**Comment by abnerlee** [comment]
> Close Typora and delete the Cache folder (%APPDATA%\Roaming\Typora\Cache on Windows). Then restart Typora.

Does restart Typora without clean cache works? 

And could you provide a sample *.md file?

**Comment by sschuldenzucker** [comment]
> > Close Typora and delete the Cache folder (%APPDATA%\Roaming\Typora\Cache on Windows). Then restart Typora.
> 
> Does restart Typora without clean cache works?

No. Restart without cleaning the cache has (had) no effect.

> And could you provide a sample *.md file?

I'm attaching a reduced version (for privacy reasons) of the file where I observed the issue. Since the problem doesn't reproduce, of course I can't provide a minimal example.


[4006 example file.txt](https://github.com/typora/typora-issues/files/5574991/4006.example.file.txt)

**Comment by abnerlee** [comment]
should be fixed
