### ISSUE TITLE
Support Big Sur icon?

### ISSUE THREAD

**Issue by singularitti** [typora/typora-issues#4007]
Now that macOS 11 or Big Sur has been out, considering changing to a [rounded-square icon](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)?

**Comment by abnerlee** [comment]
Close since this should be covered by #2 because from https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

> When you update your app for macOS 11, use your new app icon design to replace the icon you designed for earlier versions. You can’t include two different app icons for one app, and the macOS 11 app icon style looks fine on a Mac running Catalina or earlier.

So it is not design icons for Big Sur, but design new icons for all macOS.

For workaround, you can find icons at https://macosicons.com/
