### ISSUE TITLE
Don't show non-textual files in the side pane

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#4008]
I have a directory that contains three markdown files and some other files without extensions as usual in a developer environment: Two `Makefile`s and one binary file `my-application`. However, I would not like to see any of the latter files in the side pane! This is how it looks like:

![image](https://user-images.githubusercontent.com/38782922/99797619-e62b8080-2b2f-11eb-8d39-007272910e50.png)
![image](https://user-images.githubusercontent.com/38782922/99797766-27239500-2b30-11eb-994e-ff807ee4fb67.png)

Ideas:
- Check the mime type of every file that has no extension
- Maybe check for huge amounts of markdown syntax violations or extraordinarities, or would this be a rather confusing heuristic only?

**Comment by abnerlee** [comment]
can be covered by #1753
