### ISSUE TITLE
Typo "Table of Content"

### ISSUE THREAD

**Issue by NaanProphet** [typora/typora-issues#401]
This is a minor, editorial note, but usually the correct idiomatic English spelling of TOC is Table of Content**s** (i.e. plural). In *Paragraph* dropdown however, it's spelled as "Table of Content"

Just thought i'd present this as a suggestion in case it helps create a solid, professional impression on all users. Typora is so awesome!!

Interesting discussion and graph about the usage of "Table of Contents" vs "Table of Content" available here: http://english.stackexchange.com/questions/207086/table-of-contents-vs-table-of-content

**Comment by abnerlee** [comment]
Should be fixed in new version
