### ISSUE TITLE
mermaid underscore not work

### ISSUE THREAD

**Issue by liyewen521** [typora/typora-issues#4011]
Hello, I can successfully generate a diagram with underscores using Mermaid Live Editor, the following are the code and diagram :
```meimaid
graph TD
	A[doLoadMaxpoolRow0 或者 doLoadMaxpoolRow1] --> B[ROCC_INSTRUCTION_S] --> C[ROCC_INSTRUCTION_I_R_I]
```
![](https://liyewen-picture.oss-cn-beijing.aliyuncs.com/2020/11/20201123164329-typora-meimaid-error.png)

***
But when I use Typora, it can not generate underscores, the following is the generated diagram:
![](https://liyewen-picture.oss-cn-beijing.aliyuncs.com/2020/11/20201123164658-typora-mermaid-error-2.png)

Can you give me some help? Thanks a lot!

**Comment by abnerlee** [comment]
I failed to reproduce this issue., so which OS / Typora version and theme did you use?

**Comment by liyewen521** [comment]
Sorry, I forgot to provide my version. My OS is Windows 10 Education 20H2, and my Typora is 0.9.96(beta). 
I find it can correctly generate in my laptop, and the laptop's OS/TYpora version is near to my computer.
 So, Is it the monitor resolution cause this problem? my computer monitor resolution is 1920$\times$1080.

**Comment by liyewen521** [comment]
@abnerlee Hello, do you reproduce this issue?

**Comment by abnerlee** [comment]
Yes

**Comment by liyewen521** [comment]
Okay, thanks a lot, hope you can find the solution！

**Comment by abnerlee** [comment]
should be fixed

**Comment by liyewen521** [comment]
Okay，this bug disappeared, thank you for your effort!
ps: Can you tell me why briefly? how this bug occurred, and how you fix it.

**Comment by abnerlee** [comment]
We just upgraded mermaid version.

**Comment by liyewen521** [comment]
Haha, I got it, thanks for your help again.
