### ISSUE TITLE
Ubuntu20.04 执行sudo add-apt-repository 'deb https://typora.io linux/' 缺少Release文件

### ISSUE THREAD

**Issue by Corybyte** [typora/typora-issues#4012]
`忽略:1 https://typora.io linux/ InRelease
错误:2 https://typora.io linux/ Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 127.0.0.1 8889]
0% [正在等待报头]
命中:3 http://mirrors.aliyun.com/ubuntu focal InRelease
命中:4 http://mirrors.aliyun.com/ubuntu focal-security InRelease
命中:5 http://mirrors.aliyun.com/ubuntu focal-updates InRelease
命中:6 http://mirrors.aliyun.com/ubuntu focal-proposed InRelease
命中:7 http://mirrors.aliyun.com/ubuntu focal-backports InRelease
正在读取软件包列表... 完成
E: 仓库 “https://typora.io linux/ Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
`

**Comment by abnerlee** [comment]
same with #3179 ?

please check install instruction in http://support.typora.io/Typora-on-Linux/
