### ISSUE TITLE
Duplicating paragraph next to the highlighted code

### ISSUE THREAD

**Issue by Usievalad** [typora/typora-issues#4013]
Hello, I have an issue. When I format code with Ctrl-Shift-K or a menu item Paragraph -> Code highlight, strings next to a formatted code duplicate if it belongs to same paragraph.

Typora v. 0.9.96, Windows 10

before:
![image](https://user-images.githubusercontent.com/1133957/99994048-923bc880-2dc9-11eb-8169-afc1e1c00f54.png)

after:
![image](https://user-images.githubusercontent.com/1133957/99994115-a8e21f80-2dc9-11eb-9b40-c190ad880a7a.png)

source:
![image](https://user-images.githubusercontent.com/1133957/99994171-bac3c280-2dc9-11eb-8e71-9489ceb697a2.png)

**Comment by abnerlee** [comment]
fixed in new release
