### ISSUE TITLE
Error using german umlauts in \text{} in math mode

### ISSUE THREAD

**Issue by jnnkB** [typora/typora-issues#4015]
When using german umlauts in \text{} in math mode you get a diffrent fonts for the umlaut and the rest. You can see this in the following image:

<img width="22" alt="image" src="https://user-images.githubusercontent.com/29376715/100127766-bce85880-2e7f-11eb-821a-6a696d7cd84a.png">

Kind regards

**Comment by abnerlee** [comment]
#3278
