### ISSUE TITLE
[Feature request]Delete images by right click.

### ISSUE THREAD

**Issue by liuhao326** [typora/typora-issues#4016]
Hi👋!

Can Typora support delete images by right click? I think it would be very convenient.

<details>
   <summary>Right Click List</summary>

  ![delete](https://user-images.githubusercontent.com/51501079/100316929-681b1e00-2ff6-11eb-9d73-e8bacce1e25a.gif)

</details>

**Comment by abnerlee** [comment]
put into #2242
