### ISSUE TITLE
[Bug]Expansion error with aText

### ISSUE THREAD

**Issue by shawnyeung** [typora/typora-issues#4017]
I'm using the latest version of aText and Typora.

I have a snippet : when I press "b" and then the delimiter("space" button), the expansion is "bitcoin"
but in Typora, the expansion is "bbitcoi". the b is not discarded and the n is missing...

I tried in other apps, the bug is only seen in Typora.

Would you please look into it? thanks.

我的aText和typora都是最新版本。
我有一个snippet是，按b，再按空格激活该snippet，正常会出bitcoin。
但在typora里，出的是bbitcoi，第一个b应该去掉，而n却丢
了。且该问题只在typora里会出现。

**Comment by abnerlee** [comment]
which OS?

**Comment by shawnyeung** [comment]
Mac OSX 11.0.1 with Apple M1

**Comment by abnerlee** [comment]
relates #4051

**Comment by abnerlee** [comment]
It looks fine in my test, possible to share a screencast?
