### ISSUE TITLE
File Dialog Text Glitch - Ubuntu 20.04

### ISSUE THREAD

**Issue by Vafdaf12** [typora/typora-issues#4019]
Unfortunately I do not know of a reason why this happened, nor how to reproduce it, but recently whenever I try to open a file or folder, the file dialog has no text:
![Screenshot from 2020-11-27 10-27-19](https://user-images.githubusercontent.com/25525445/100427421-17113580-309b-11eb-9fe9-201749768f74.png)

At first I thought it might be due to the gtk theme I am using, however changing it produced no change. I did not modify or change any fonts between the time it last worked and now.

I am using Typora 0.9.96 on Ubuntu 20.04

**Comment by abnerlee** [comment]
Should not be an issue from Typora.

Could you try https://askubuntu.com/questions/1224125/font-characters-displayed-as-squares-in-ubuntu-18-04 ?

**Comment by Vafdaf12** [comment]
> Should not be an issue from Typora.
> 
> Could you try https://askubuntu.com/questions/1224125/font-characters-displayed-as-squares-in-ubuntu-18-04 ?

Thank you, it worked! I hadn't thought about searching it as a general problem, as it only happened in typora, and not any other application
