### ISSUE TITLE
[Bug report]Ctrl+shift+` doesn't work

### ISSUE THREAD

**Issue by liuhao326** [typora/typora-issues#4020]
Hi👋!

I found I can't add ` `` ` for some HTML tag like `<li>` or `<p>` by keyboard shortcuts <code>Ctrl+shift+ `</code> .

<details>
			<summary>Gif</summary>

![code](https://user-images.githubusercontent.com/51501079/100457318-c5999280-30fc-11eb-8f39-ac4840c118f2.gif)

</details>

**Comment by abnerlee** [comment]
should be fixed
