### ISSUE TITLE
[Bug report] Chose the current folder in Recent Locations 

### ISSUE THREAD

**Issue by liuhao326** [typora/typora-issues#4023]
Hi👋!

When choosing the current folder in Recent Locations, the menu panel will show again, but I think it's better to close it in this case.

<details>
<summary>Details</summary>

![folder](https://user-images.githubusercontent.com/51501079/100684455-57332980-33b5-11eb-98d7-77785f2b1d7a.gif)

</details>

**Comment by abnerlee** [comment]
should be fixed
