### ISSUE TITLE
typora打开md文件没有权限

### ISSUE THREAD

**Issue by xiao-ma-nong** [typora/typora-issues#4024]
ubuntu 20 

`Error
EACCES:permission denied , open '/medita/tina/a.md'
`
这该怎么解决呢。我能打开home目录下的md文件，但是在其他盘无法打开

**Comment by abnerlee** [comment]
chmod 给个权限呢，或者 sudo

**Comment by xiao-ma-nong** [comment]
> chmod 给个权限呢，或者 sudo

已经给了，还是不行
