### ISSUE TITLE
namespace problem running in Ubuntu within Windows Subsystem for Linux

### ISSUE THREAD

**Issue by pauljohn32** [typora/typora-issues#4029]
$ typora
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Permission denied
Trace/breakpoint trap (core dumped)

I am unable to install your Windows version because of system administration restrictions. It requires admin password (please allow nonadmin to install).

Many linux programs work OK from WSL using an Xserver, but not typora.

**Comment by abnerlee** [comment]
#3636
