### ISSUE TITLE
Image auto upload

### ISSUE THREAD

**Issue by fancofang** [typora/typora-issues#4031]
I would like typora do some auto upload work when I insert a image, but actually it doesn't work as what I set in below in typora.
![image](https://user-images.githubusercontent.com/24840440/101267451-bb0c7800-3750-11eb-8910-1d0cd1c8e618.png)

The file yaml is `typora-copy-images-to: upload` and I upload manually to github it can work.
![image](https://user-images.githubusercontent.com/24840440/101267485-1a6a8800-3751-11eb-912b-70ba77654509.png)

What is the trigger between typora and PicGo for uploading image?

**Comment by abnerlee** [comment]
What is the error message?

**Comment by fancofang** [comment]
> What is the error message?

I didn't get any error message, that's why I consider if I trigger the upload system. My typora version is 0.9.85(beta).

**Comment by abnerlee** [comment]
Does "验证图片上传选项" works?
Did you auto upload remote image or local one.
You are inserting images by typing the markdown syntax, or by drag & drop?
How about latest version?
