### ISSUE TITLE
Request: please don't show URLs / Emails as blue/underlined unless they're actually hyperlinks

### ISSUE THREAD

**Issue by dylanbeattie** [typora/typora-issues#4032]
Typora's WYSIWYG view will apply blue colouring and underlining to URLs, even if they're not actually hyperlinks. This means it's really difficult to see from the WYSIWYG view if you've pasted a URL into your document but not actually made it into a link.

Here's a screenshot of the WYSIWYG view:

![image](https://user-images.githubusercontent.com/106178/101280008-64d61e00-37be-11eb-8727-33fae8640b61.png)

And here's the source view of the same markdown code:

![image](https://user-images.githubusercontent.com/106178/101280007-60aa0080-37be-11eb-93d3-8c309392ac66.png)

Could Typora please not apply any special formatting to URLs unless they are actually hyperlinks?

Thank you!

**Comment by abnerlee** [comment]
For now you can use CSS to make it looks like normal text.

In future, we may need options for this.

**Comment by M1ssakira** [comment]
Like the previous comment, what kind of CSS content should be added to ignore the email format? Otherwise, the format of the email in the exported PDF looks awkward.

**Comment by abnerlee** [comment]
supported as options in v1.6.5
