### ISSUE TITLE
Export to HTML (without styles) does not contain named links for heading tags

### ISSUE THREAD

**Issue by SorinGFS** [typora/typora-issues#4034]
#### Inline Links
Let's supose we have a heading like the above and we want to refer to it in a link.

 Export to html will look like this:
```html
# export to HTML
<h4><a name="inline-links" class="md-header-anchor"></a><span>Inline Links</span></h4>

# export to HTML (without styles) - current output is:
<h4>Inline Links</h4>
```

In order to get it work export to HTML (without styles) output should be like this:
```html
<h4><a name="inline-links"></a><span>Inline Links</span></h4>
```

**Comment by abnerlee** [comment]
We now uses `id` instead of deprecated `name` attribute. So it will become

```
<h4 id="inline-links">Inline Links></h4>
```
