### ISSUE TITLE
[Bug] Typora will crash, when I click every area in the editor

### ISSUE THREAD

**Issue by SoloJiang** [typora/typora-issues#4036]
![image](https://user-images.githubusercontent.com/14757289/101720387-71b98100-3ae0-11eb-8170-8e87fb1924be.png)
![image](https://user-images.githubusercontent.com/14757289/101720405-80079d00-3ae0-11eb-85b4-e4cda81d197e.png)

**Comment by abnerlee** [comment]
could you provide crash log? I'm not able to reproduce this.

**Comment by SoloJiang** [comment]
When I clicked it, the mouse will be loading

**Comment by SoloJiang** [comment]
How can I get the crash log?

**Comment by SoloJiang** [comment]
![Uploading image.png…]()

**Comment by abnerlee** [comment]
> When I clicked it, the mouse will be loading

Are you editing a large file? possible to attach a screencast?

**Comment by SoloJiang** [comment]
No, an empty new file

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/102004802-075a4800-3d4f-11eb-977e-51b7a6dc9192.png)

**Comment by SoloJiang** [comment]
Every preference settings are changed, it will be loading too.

**Comment by abnerlee** [comment]
how about the latest version?

Or just reinstall it.

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/102031768-ef87d000-3df1-11eb-9a7a-1019cd4962fa.png)
Reinstall couldn't solve it
