### ISSUE TITLE
mermaid lib css need update

### ISSUE THREAD

**Issue by ruanjf** [typora/typora-issues#4037]
Flowchart color display is wrong
Version: 0.9.9.35.2 (4715)
Code:
````
```mermaid
graph TD
  a[(test)]
```
````
Render:
![image](https://user-images.githubusercontent.com/509251/101766029-207bb280-3b1d-11eb-9e12-2724bd0dd893.png)

Solution:
Use mermaid latest version
`lib/diagram/css/mermaid.css` 22 line add `.node path`

**Comment by abnerlee** [comment]
should be fixed

**Comment by abnerlee** [comment]
duplicate with #3703
