### ISSUE TITLE
Switching files in 'Files' Tree View.

### ISSUE THREAD

**Issue by partoneplay** [typora/typora-issues#4038]
I have a folder with a few md files. 
For example, `A.md` and `B.md`.
I click `A.md` in Files Tree, the content is `A.md`. Everything is Ok.
But sometimes, i switch to B.md in Files Tree, the content is still `A.md`. I have to restart `Typora`.
With autosave on, I loss my content more than once. I have to turn it off.

My OS Version is Windows 10 1909 (18363.418), Typora Version is 0.9.96

**Comment by abnerlee** [comment]
relates #3520

**Comment by abnerlee** [comment]
duplicate with #3894

Possible to send us <hi@typora.io> a screencast?
