### ISSUE TITLE
Open single file without tree/file view

### ISSUE THREAD

**Issue by abcarroll** [typora/typora-issues#4039]
When opening a file in Typora, is there a way to direct Typora to not attempt to scan the file's parent directory using command line switches?  That is, explicitly disable the "File" tree view for a single one-time run.

For example, if I have a file in my home directory called `hello.md`, and I execute something like  `/home/ab/.local/bin/typora-linux-x64/Typora "hello.md"`, then it will attempt to scan my home directory if I have the "Files" view, or at least scan the parent directory (which may have thousands of directories, as a very extreme example) for the "Tree" view.  

While the "give up" feature for the "Files" view is absolutely excellent, it would be amazing if there could be or perhaps already is a way to indicate to Typora that I only want to manipulate the single file in the path, and not bother with a file/tree view, and not scan the containing directory (recursively or non-recursively).

From digging around this is somewhat related to #1000 maybe, but is somewhat distinct from it.

P.S. Thanks for this great bit of software!

**Comment by abnerlee** [comment]
Typora will remember previous status, if you close sidebar, then open another *.md file, the sidebar will not shows up.

This may be covered by #1999
