### ISSUE TITLE
Can you add a function that we can encrypt the files?

### ISSUE THREAD

**Issue by stonejing** [typora/typora-issues#404]
Can you add a function that we can encrypt the files?

**Comment by abnerlee** [comment]
I think the md file can be encrypted by 3rd parties apps.

**Comment by bmalbusca** [comment]
Upvote this. This is only the things that i miss  because, I'm pushing markdown notes to my git repo, and having only one tool that does everything helps a lot.  I can help to do this integration  @abnerlee

**Comment by abnerlee** [comment]
#2776
