### ISSUE TITLE
How to show the button for toggling Outline view for Mac version Typora

### ISSUE THREAD

**Issue by ifsheldon** [typora/typora-issues#4041]
I am transferring from Windows to macOS and I find that Typoras on Windows and macOS are slightly different. One of the differences is that in the Windows version, there is a toggle button for opening and closing the outline view, but in macOS version, it's gone. I find it very convenient when it's gone and I don't want to remember keyboard the shortcut `control+command+1`, which is weird, to open or close this outline view. How can I bring it back?

Besides, there is also a button right next to it for enabling/disabling source code mode, which is also gone in the macOS version, which is also annoying that I have to remember a key shortcut. I don't want to be rude, but can we have a consistent UX across platforms? and please bring back UIs so that we don't have to remember keyboard shorcuts, which are somehow favored on macOS.

**Comment by abnerlee** [comment]
icons on macOS are on title bar.

**Comment by ifsheldon** [comment]
> icons on macOS are on title bar.

Yeah........ I found the icon for toggling outline view on the top right corner on the title bar. Sorry about that I said I could not find it, but where it's placed is counter-intuitive I think, because the outline view will occur at the left of the screen, right at the opposite direction. I think the Windows version is pretty straight forward, because the icon is at the bottom **right** corner and the outline view occurs and disappear at the right of the editor.

But I can't still find the icon for toggling source code mode, and I think this time I have checked all the icons on the screen.

**Comment by abnerlee** [comment]
> But I can't still find the icon for toggling source code mode, and I think this time I have checked all the icons on the screen.

We don't have this icon on macOS. Source code mode is not designed as "commonly used functions", so we didn't put it on macOS

**Comment by ifsheldon** [comment]
> > But I can't still find the icon for toggling source code mode, and I think this time I have checked all the icons on the screen.
> 
> We don't have this icon on macOS. Source code mode is not designed as "commonly used functions", so we didn't put it on macOS

But this reason does not stand for the Windows version? since the Windows version has it. And it's quite convenient for me to change my format mistakes without having to remember typora keyboard shortcuts.

Is it possible that there can be a setting in the preference to set whether to show it? 

Besides, I still argue that the button for toggling the outline view should be placed at where it is on the Windows version, which is more intuitive.
