### ISSUE TITLE
Bug about typing inline math

### ISSUE THREAD

**Issue by UnnamedOrange** [typora/typora-issues#4042]
Only in 0.9.97
When typing inline math and there is an error in the math, the cursor moves across the right '$'.

![1](https://user-images.githubusercontent.com/33177912/101970665-a6574500-3c66-11eb-8296-c88209b95167.gif)

1. New window.
2. Type "$$".
3. Type "\dfrac" in the inline math.
4. The cursor moves out!

**Comment by Narukara** [comment]
same problem when type something + "_"

![bug](https://user-images.githubusercontent.com/53737377/101980846-52b71c80-3ca3-11eb-88d6-2276d246d7c6.gif)

**Comment by WalkerMao** [comment]
yes same problem

**Comment by kuqquk** [comment]
+1

**Comment by WalkerMao** [comment]
This happens to the latest Windows version 0.9.97. Downgrading to 0.9.96 can solve the problem.

**Comment by abnerlee** [comment]
We just updated a fix, it should be working now after you check updates again..

**Comment by jerome9189** [comment]
Don't know if I should comment here, but I'm experiencing the same bug in 0.10

**Comment by abnerlee** [comment]
The new bug is recorded in #4335
