### ISSUE TITLE
Big sur icon adaptation

### ISSUE THREAD

**Issue by CourieLiu** [typora/typora-issues#4043]
The official version of big sur has been released for a while, do we have plans to adapt the new icon?

**Comment by abnerlee** [comment]
#2

**Comment by abnerlee** [comment]
It will need a new design, but I'm not good at image designing, so we are still considering it.

You can use https://macosicons.com/ for now

**Comment by hitzhangjie** [comment]
I prefer the previous design of icon, simple and neat.

**Comment by AlexPasternak** [comment]
I guess it's a matter of preference. The previous icon had many complaints, and was hard to pick out. The new one is much more prominent on a smaller Dock and is a big improvement in my eyes. You can always customize it back to the old style, like many of us did with the previous icon.
