### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#4045]
I have open 17 Typora windows each with relatively small documents (few screen pages, maximum of 1 or 2 images per document) open, but in total, all the Typora processes occupy more than 600 MB of my memory.

I know that Electron applications are likely to use a lot of memory, but is there really no way to load required resources globally instead of reloading them for every single window? This high RAM usage really slows my PC down :(

**Comment by abnerlee** [comment]
Put into #68

What are the size of your documents and images actually? What is your total memory for your PC?

**Comment by LinqLover** [comment]
> What are the size of your documents and images actually?

Each 1 to 10 KB.

> What is your total memory for your PC?

16 GB RAM
