### ISSUE TITLE
Auto Numbering Math Equations not working 

### ISSUE THREAD

**Issue by JuanBSLeite** [typora/typora-issues#4046]
Math block and inline math equations are not rendered when this option is checked. 

Inline equation still in LaTeX code form e.g. $x^{2} = 4$ , and math block desappers.

When I uncheck this option, everything works fine.

 I'm using the last Linux version 0.9.97 on Ubuntu 20.04.

Thanks!

**Comment by abnerlee** [comment]
duplicate with #4040
