### ISSUE TITLE
Missing words when using aText

### ISSUE THREAD

**Issue by LeiGitWing** [typora/typora-issues#4047]
## Session info

```
System: 10.15.3 macOS Catalina
Typora Version: 0.9.9.36.2 (4901)
aText version: 2.36.6
Using the mac native input
```

## Bug Description

I defined `;cl` as snippet for

```
## ChangeLog

2020-12-14  init
```

it works well in MWeb and GitHub input. And the snippet also works fine when using the code blocks in Typora. 

But when I try to type it directly in Typroa, it will missing the date number, like 

![image-20201214005938930](https://tva1.sinaimg.cn/large/0081Kckwgy1glmpy14u0zj30ee0ac0t0.jpg)

**Comment by abnerlee** [comment]
put into #4017 for aText support issues
