### ISSUE TITLE
Wrong footnote parse in source mode

### ISSUE THREAD

**Issue by kris7453** [typora/typora-issues#4049]
OS version: Windows 10 Home 2004
Typora version: 0.9.98 (beta)

![image](https://user-images.githubusercontent.com/20442936/102117351-7e223e80-3e3e-11eb-9150-4c062a7476e6.png)

![image](https://user-images.githubusercontent.com/20442936/102117593-cf323280-3e3e-11eb-9e55-a86b86f396c1.png)

There is fragment marked as a footnote link from one footnote to another, but it should be only `[^1]` and `[^name]` marked as a link. Rest of the sentence should be simple text node.

**Comment by abnerlee** [comment]
put into #1638

**Comment by lunasorcery** [comment]
still present as of 1.7.6 on macOS
