### ISSUE TITLE
Feature Request: Allow 'Source Mode' button to toggle

### ISSUE THREAD

**Issue by Gruntfuggly** [typora/typora-issues#405]
I tend to switch back and forth between source mode and normal mode quite often. It seems odd that there is a button to exit source mode, but I need to go to the menu to open source mode. Could the button be made into a toggle button?

BTW - I realise I am being lazy and that there is a keyboard shortcut, it's just that I can never remember it!

**Comment by cmeeren** [comment]
There is a button. It's shown as `</>` in the same location as the exit button you mention.

**Comment by Gruntfuggly** [comment]
> On 24 Nov 2016, at 13:27, Christer van der Meeren <notifications@github.com> wrote:
> 
> There is a button. It's shown as </> in the same location as the exit button you mention.
> 
> 
Hi Christer

Thanks for the response.

When in source mode I see this:



If I click “Source Mode” to exit, briefly shows the words count, and then it changes to this:



Is there something I should enable?

Thanks,
Nige

**Comment by cmeeren** [comment]
Oh, right, I'm using the Windows app. Seems like you're on a Mac? Might be some differences.

**Comment by abnerlee** [comment]
Yes, the `</>` button is only displayed on Windows/Linux version.

**Comment by abnerlee** [comment]
I will close this. We do not our users to use source code mode too much. And there are always two icons in the titlebar.
