### ISSUE TITLE
rendering of unordered lists broken with certain CSS

### ISSUE THREAD

**Issue by nousernameavailableanymore** [typora/typora-issues#4050]
Hi, 

this issue has existed for all versions after 0.9.89 (beta) on Windows.

I have modified the display of unordered lists via CSS to have colored bulletin points.
All versions after the above show the behavior that if you open a md file that has an unordered list, everything looks fine at first.
However, if you mouse click anywhere after where the text ends, the text gets offset by one line from the bulleting points.

This is the CSS I use for unordered lists:
```
	ul > li {
		list-style: none;
		margin-top: -5px;
		margin-left: -30px;
		display: table;
	} 
	
	ul li::before {
		content: "\2022"; 
		color: var(--sne-gold); 
		font-weight: normal; 
		display: table-cell; 
		width: 1.3em; 
	}
```

STEPS TO REPRODUCE:
1. install Typora version 0.9.98
2. apply above CSS for rendering of unordered lists
3. create md file that contains unordered list
4. click somewhere after the end of the text

EXPECTED BEHAVIOR
display / rendering of unordered list should not change / be displayed correctly

ACTUAL BEHAVIOR
text gets offset by one line from bulletin points

PICTURES
![image](https://user-images.githubusercontent.com/45376324/102150339-9f9c1e00-3e70-11eb-85f5-31897d4acdc9.png)

This is what happens:
![image](https://user-images.githubusercontent.com/45376324/102150862-d7f02c00-3e71-11eb-94da-b8b58c914b84.png)

**Comment by abnerlee** [comment]
We do not support "display: table" style on `<li>`...

**Comment by nousernameavailableanymore** [comment]
Will this be supported some time in the future or is there any other way to achieve the colored bulletin points or will this (0.9.89) be the last version I will be able to use?

**Comment by abnerlee** [comment]
We put "display:list-item" to hack / fix some rendering bug of webkit. if that does not occur anymore, we will remove this style

**Comment by nousernameavailableanymore** [comment]
Pls excuse my lack of knowledge, as I am not a web-developer. I just want to make my notes look pretty.
So what is the recommended way of changing the color of bullet points / numberings in unordered / ordered lists?

**Comment by abnerlee** [comment]
You can try, for example:

```css
li {
  color: red
}
 
li > * {
  color: black;
}
```

**Comment by abnerlee** [comment]
In future versions, you can also use:
```css
li::marker {
  color: hotpink;
}
```

(not supported for now)
