### ISSUE TITLE
[Bug] Dictation on Mac results in duplicate text

### ISSUE THREAD

**Issue by usergo** [typora/typora-issues#4051]
## Duplicate Text

Using standard Mac [dictation](https://support.apple.com/guide/mac-help/use-dictation-mh40584/mac) on Big Sur (maybe other macOS versions as well) results in duplicate text after you finish dictating a sentence.

See image below, the dictated message should read:

"I am writing this with voice transcription from Apple"

![DuplicateDictation](https://user-images.githubusercontent.com/8535072/102151934-fcccab00-3e41-11eb-860a-da30eec39f30.png)

## Really impressed

I am otherwise extremely impressed by the CX and usability of this beta app!

**Comment by usergo** [comment]
System info

![systemInfo](https://user-images.githubusercontent.com/8535072/102152302-b9bf0780-3e42-11eb-9493-a6d703ec4809.png)

**Comment by abnerlee** [comment]
relates #2798

**Comment by abnerlee** [comment]
fixed in new release
