### ISSUE TITLE
update check update failed

### ISSUE THREAD

**Issue by Hsu-Hsin** [typora/typora-issues#4054]
I terminated the update program because of the low-speed network.
But it got error when I restart the update like that:
![update_error](https://user-images.githubusercontent.com/56154662/102220939-75079f00-3f1c-11eb-85ce-50e643496340.png)

_write EPROTO 1781253672:error:10000410:SSL
routines:OPENSSL_ internal:SSLV3 ALERT HANDSHAKE_ FIALU:.../../third_party/...:SS alert number 40
1781253672:error:1000009a:SSL
routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_...:596:_

I try to uninstall and reinstall Typora but got the same error again.
And I can't find any solutions of this problem, is there any ways to solve it? Please.

**Comment by abnerlee** [comment]
> routines:OPENSSL internal:SSLV3 ALERT HANDSHAKE_ FIALU:.../../third_party/...:SS alert number 40
1781253672:error:1000009a:SSL

This is a network issue. And if you check update manually, it will show error if checking updates failed.
