### ISSUE TITLE
Recent update to themes has negatively impacted Mermaid gantt charts.

### ISSUE THREAD

**Issue by talyrath** [typora/typora-issues#4055]
Hi team.  

The recent update to themes in 0.9.9.36 has had negative consequences to graphics generated by mermaid.js  

Specifically, .mermaid.section0 section1 section2 and section3 have all been set to some variety of white or very light gray. (previously, they were white, light blue and yellow) This causes gantt chart sections to be indistinguishable from each other.

(Also, the .section fill colors in CSS are all defined differently, but I think that's an inherited feature from mermaid.js defaults.  )

**Comment by abnerlee** [comment]
could you provide example mermaid code?

Newer version of mermaid use js instead of CSS for color definition, so there are some styles change because of this switch

**Comment by talyrath** [comment]
Sure thing.  I'm using pretty generic code.   I'm not modifying CSS - just accepting the defaults generated by Typora.  

`
```mermaid
gantt
title 2021 Roadmap
dateFormat	M-D-YY

section Buying stuff
New payments for a site	:	a3,	12-14-20,	01-15-21
Migrating something to a diff platform	:	a4,	12-14-20,	03-05-21


section Redacted section
Monthly Releases	:	a6,	12-14-20,	03-05-21


section Marketing
Cloud Migration	:	a11,	12-14-20,	03-05-21
Additional scope	:	a12,	12-14-20,	03-19-21

section Fulfillment
Site Migration	:	a18	12-28-20,	02-05-21

section Important Project
Release Testing	:	a20,	12-14-20,	03-05-21
UI Perf Testing	:	a21,	12-14-20,	01-22-21
QA Perf Test Setup	:	a22,	12-14-20,	01-01-21

section That other project
Oracle Migration	:	a36,		12-14-20,	01-01-21
January Release	:	a37,		12-14-20,	01-8-21
Ongoing Releases	:	a38,	after a37,		03-5-21

section Those Systems
Nameless system	:	a42,	 12-20-20,	01-29-21
Blank Task:	12-1-20, 12-1-20
```
`

The expected output should look like this:  Please note the different colors assigned to each section.

![Expected_Output](https://user-images.githubusercontent.com/76055688/102377619-e4b87100-3f92-11eb-9b16-e968e7652b14.png)

If you run this snippet in the latest version, the section colors are all some variety of white, making it impossible to see which task falls in which section.  Apologies for not posting an 'after' screenshot - I don't have a convenient VM where I can install the latest version.

**Comment by talyrath** [comment]
Sure thing.  I'm using pretty generic mermaid.js.  I'm not overriding any CSS - just accepting the defaults generated by Typora.

` 
```mermaid
gantt
title 2021 Roadmap
dateFormat	M-D-YY

section Buying stuff
New payments for a site	:	a3,	12-14-20,	01-15-21
Migrating something to a diff platform	:	a4,	12-14-20,	03-05-21


section Redacted section
Monthly Releases	:	a6,	12-14-20,	03-05-21


section Marketing
Site Migration	:	a11,	12-14-20,	03-05-21
Additional scope	:	a12,	12-14-20,	03-19-21

section Fulfillment
Site Migration	:	a18	12-28-20,	02-05-21

section Important Project
Release Testing	:	a20,	12-14-20,	03-05-21
UI Perf Testing	:	a21,	12-14-20,	01-22-21
QA Perf Test Setup	:	a22,	12-14-20,	01-01-21

section That other project
Oracle Migration	:	a36,		12-14-20,	01-01-21
January Release	:	a37,		12-14-20,	01-8-21
Ongoing Releases	:	a38,	after a37,		03-5-21

section Those Systems
HR	:	a42,	 12-20-20,	01-29-21
Blank Task:	12-1-20, 12-1-20
```
`

Expected output should look like this:  Please note the alternating color bands for each section.  This allows a viewer to see which task falls in which section:

![Expected_Output](https://user-images.githubusercontent.com/76055688/102378834-36153000-3f94-11eb-9a67-8e0f14440832.png)

If you run this snippet in the current version, every section is some variety of white or very light gray, and all of the sections just run together.  I apologize for not posting an 'actual output', I don't have a convenient VM handy to install the latest version.

**Comment by abnerlee** [comment]
I think they are now distinguished by background color, and this is a mermaid.js issue, you could try on [https://mermaid-js.github.io/mermaid-live-editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbnRpdGxlIDIwMjEgUm9hZG1hcFxuZGF0ZUZvcm1hdFx0TS1ELVlZXG5cbnNlY3Rpb24gQnV5aW5nIHN0dWZmXG5OZXcgcGF5bWVudHMgZm9yIGEgc2l0ZVx0Olx0YTMsXHQxMi0xNC0yMCxcdDAxLTE1LTIxXG5NaWdyYXRpbmcgc29tZXRoaW5nIHRvIGEgZGlmZiBwbGF0Zm9ybVx0Olx0YTQsXHQxMi0xNC0yMCxcdDAzLTA1LTIxXG5cblxuc2VjdGlvbiBSZWRhY3RlZCBzZWN0aW9uXG5Nb250aGx5IFJlbGVhc2VzXHQ6XHRhNixcdDEyLTE0LTIwLFx0MDMtMDUtMjFcblxuXG5zZWN0aW9uIE1hcmtldGluZ1xuU2l0ZSBNaWdyYXRpb25cdDpcdGExMSxcdDEyLTE0LTIwLFx0MDMtMDUtMjFcbkFkZGl0aW9uYWwgc2NvcGVcdDpcdGExMixcdDEyLTE0LTIwLFx0MDMtMTktMjFcblxuc2VjdGlvbiBGdWxmaWxsbWVudFxuU2l0ZSBNaWdyYXRpb25cdDpcdGExOFx0MTItMjgtMjAsXHQwMi0wNS0yMVxuXG5zZWN0aW9uIEltcG9ydGFudCBQcm9qZWN0XG5SZWxlYXNlIFRlc3RpbmdcdDpcdGEyMCxcdDEyLTE0LTIwLFx0MDMtMDUtMjFcblVJIFBlcmYgVGVzdGluZ1x0Olx0YTIxLFx0MTItMTQtMjAsXHQwMS0yMi0yMVxuUUEgUGVyZiBUZXN0IFNldHVwXHQ6XHRhMjIsXHQxMi0xNC0yMCxcdDAxLTAxLTIxXG5cbnNlY3Rpb24gVGhhdCBvdGhlciBwcm9qZWN0XG5PcmFjbGUgTWlncmF0aW9uXHQ6XHRhMzYsXHRcdDEyLTE0LTIwLFx0MDEtMDEtMjFcbkphbnVhcnkgUmVsZWFzZVx0Olx0YTM3LFx0XHQxMi0xNC0yMCxcdDAxLTgtMjFcbk9uZ29pbmcgUmVsZWFzZXNcdDpcdGEzOCxcdGFmdGVyIGEzNyxcdFx0MDMtNS0yMVxuXG5zZWN0aW9uIFRob3NlIFN5c3RlbXNcbkhSXHQ6XHRhNDIsXHQgMTItMjAtMjAsXHQwMS0yOS0yMVxuQmxhbmsgVGFzazpcdDEyLTEtMjAsIDEyLTEtMjAiLCJtZXJtYWlkIjp7InNlY3VyaXR5TGV2ZWwiOiJsb29zZSIsInRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by talyrath** [comment]
But the output from Typora is totally different than the mermaid.js live editor!

0.9.98 output looks like this:

![Typora-201216-Code-Example](https://user-images.githubusercontent.com/76055688/102510176-55c05d00-4055-11eb-8026-14eb45de2f1e.png)

How is this a mermaid issue if Typora looks different than the mermaid live editor?

**Comment by abnerlee** [comment]
You can add 
```css
:root {
 --mermaid-theme: default;
}
```
in custom css as hot fix

**Comment by abnerlee** [comment]
fixed in new release
