### ISSUE TITLE
[Suggestion] Using shebang (#!) to exclude a header from the Table of Contents [toc]

### ISSUE THREAD

**Issue by Arkl1te** [typora/typora-issues#4057]
# Problem
I always use the first header to entitle the article, and many smaller headers, but here's the thing: 

* For small headers, out-of-context indexing can be confusing and makes the ToC look not-so simplistic.
* It's kinda annoying (or redundant) to see the first title repeated twice. Example:<br>
```markdown
# Introduction to Anything and Anything 101
## Index
[toc]
```
* Normally, clicking an item in the ToC will jump to the header, which is the first piece of document to display.<br>But if the reader chooses to read auxiliary info rather than the subtopic, is not presented with the main context.

# Solution

Adding an exclamation mark (`!`) after the last number sign (`#`) to mark those headers as ignored by the Table of Contents.

```markdown
#! Introduction to Anything and Anything 101
## Index
## Chapter 1
### Subject
#### Info worth reading
####! A warning, not worth reading out of context
```
# Alternative Solution

Add titles as arguments to the `[toc]`, targeting the headers to ignore.
Less elegant and potentially anti-pattern to my taste (I change header titles often).

```markdown
<!-- Matching string -->
[toc "Introduction to Anything and Anything 101", "A warning, not worth reading out of context"]

<!-- or matching a header count. -->
[toc 1,5]
```

**Comment by abnerlee** [comment]
We are less likely to introduce "#!" since it is not supported by other markdown engines.

would prefer alternative solution, which is a part of #1202

**Comment by rcbyron** [comment]
Any update on this? I'm loving typora so far, but this seems like an obvious missing feature
