### ISSUE TITLE
"Show Tab Bar" is not persistent / going from two tabs to one tab changes window size

### ISSUE THREAD

**Issue by stefandesu** [typora/typora-issues#4058]
Typora 0.9.9.36.2 (4901), macOS 11.1

If there are two open tabs and I close one of them, the tab bar disappears and the window becomes smaller by the size of the tab bar. That is fairly annoying if you want to have Typora use the whole screen. Also, the "Show Tab Bar" option under "View" shows the tab bar when there's only one tab, but if I open a tab and close it again, the tab bar still disappears.

I would suggest that 1. the window doesn't get smaller when the second to last tab is closed, and 2. that the "Show Tab Bar" is a persistent option to always show the tab bar even if there's only one tab (like it does in Safari, for example).

**Comment by camxcube** [comment]
I've met this problem for a long time as well. I hope in can be fixed.

**Comment by abnerlee** [comment]
fixed in new release
