### ISSUE TITLE
Customising colour of text inside Mermaid node 

### ISSUE THREAD

**Issue by gilbertohasnofb** [typora/typora-issues#4059]
As reported by an user in the repository of one of my themes, Mermaid charts seem to be broken in several themes (not only mine): https://github.com/gilbertohasnofb/typora-panda-theme/issues/3

I used `--node-fill` in `:root` to control the colour of the background of Mermaid nodes, but for some reason my theme stopped being able to change the text colour in those nodes. What is the best way of customising that?

**Comment by abnerlee** [comment]
You can `@import "night/mermaid.dark.css"` to use the original dark theme provided by Typora
or use "--mermaid-theme:dark;" to use dark theme provided by mermaid.

Newer version of mermaid use js instead of CSS for color definition, so the old CSS way would not work...

**Comment by gilbertohasnofb** [comment]
Thank you for the quick reply, I just added `--mermaid-theme:dark;` to all my themes and the Mermaid diagrams are looking very good once again. Thank you.
