### ISSUE TITLE
Is there any way to center the text horizontally ?

### ISSUE THREAD

**Issue by wafer-li** [typora/typora-issues#406]
Although standard markdown don't have native `text-align`.

It still has way to achieve this, such as use `<div>` element and attach style

But it seems to be impossible to use `<div>` element in Typora.

How can I fix it?

**Comment by abnerlee** [comment]
It's not supported by native Markdown syntax. 

You could write HTML code for this. It won't be rendered in Typora, but could work when export

**Comment by reflectionalist** [comment]
I do not know whether it is a good idea.  But Typora could try to support this in a similar vein as table cell alignment is done already.  I mean, to offer a blocked paragraph (triggered by, say, Ctrl+P, as a table is by Ctrl+T), where there are buttons for horizontal alignment.

**Comment by dccote** [comment]
I would also need this, and I clearly understand the reasoning for not supporting this. I am totally working around this by simply typing many space characters. 

Which brings me to this: I was wondering if we could implement an "extension" to markdown that would interpret many spaces before text as a meaning "please center this" ? We already have an implicit "align left". We would not be able to align right, but oh well: who does that anyway?

**Comment by tsulimancsi** [comment]
please check what I posted at https://github.com/typora/typora-issues/issues/472 

it worked when you use some thing like 

`<h1 style="color:blue;text-align:center;">This is a header</h1>`

**Comment by adamgranthendry** [comment]
If you want to keep your Markdown formatting and are comfortable with making the change global, you can edit the corresponding HTML entity of `C:\Program Files\Typora\resources\app\style\base.css` to include

```
text-align: center;
```

**Comment by Puled** [comment]
Simply use 
`<center> </center>`,
and put the text you want to be centered in side. When exports to PDF, this works well. See [Typora Support](https://support.typora.io/Typeset/#center-alignment:~:text=You%20can%20partially%20make%20a%20paragraph%20with%20centered%20texts%20by%20inputting%20HTML%20directly%20in%20Typora%3A)
