### ISSUE TITLE
PDF export issues (EPERM) and Image export doesn't seem to work

### ISSUE THREAD

**Issue by nicoszpako** [typora/typora-issues#4061]
Hello.

I'm using Typora 0.9.98 with Windows 10.

When I try to export my file to a folder as a .pdf file, it displays the following message.
![image](https://user-images.githubusercontent.com/31455037/102286949-a2af1100-3f39-11eb-9e51-079f1c849a93.png)
However it works like a charm when i try to export it as an .html file in the **same folder** with the **same name**, so it doesn't seem to be a permission problem, especially since i tried almost every solution about permissions within my file system.

In addition, nothing happens when I try to export it as an image.

I tried with different files, I get the same problems.

I hope i'll participate into improving Typora, which I'm fond of.

**Comment by abnerlee** [comment]
Will export to C:\ with a ASCII filename works?

Does this path contains any symbol link or folders sync with OneDrive / iCloud, etc?

Do you have any anti-virus or firewall installed that may block the access?

And how about export to PDF using "print" function, will that work?

**Comment by nicoszpako** [comment]
**It works** if I try to export it using the print function. Thank you a lot !

But no, exporting with a **filename containing only ASCII characters** doesn't work.
Also no, exporting to a **path containing only ASCII characters** doesn't work either.
And no, exporting while **disabling my antivirus file protection system** doesn't work either.

Thanks again. Tell me if you need more informations about those issues.

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> logs following https://support.typora.io/Get-Logs/ ?

**Comment by abnerlee** [comment]
relates #2316
