### ISSUE TITLE
Crashes after deleting folder from disk, reinstall doesn't help

### ISSUE THREAD

**Issue by vitobotta** [typora/typora-issues#4065]
Hi, I have been using Typora for a couple of weeks now with no issues, but today I moved my notes folder from a location on my disk to another, and Typora just crashes immediately after opening it. I tried reinstalling it a few times after uninstalling it with AppZapper, same result. I tried moving the files back to their old location, same result. So at the moment I am unable to use Typora at all. What can I do? I am on macOS. How can I completely uninstall Typora and remove all traces so that I can reinstall it cleanly? Thanks!

**Comment by vitobotta** [comment]
I managed to get it working by moving the automatically reopened document to trash. Hopefully this will be fixed in a new version.

**Comment by abnerlee** [comment]
@vitobotta Possible to send us <hi@typora.io> the file that unable to be opened?

**Comment by vitobotta** [comment]
Hi @abnerlee I tried to reproduce it again by moving the nodes folder but for some reason it didn't happen this time. Not sure what happened the first time. Thanks
