### ISSUE TITLE
Can't export to pdf

### ISSUE THREAD

**Issue by Nilyang404** [typora/typora-issues#4067]
![image](https://user-images.githubusercontent.com/63556313/102688613-cffa0880-4232-11eb-8deb-c99ad18437f1.png)

window 10 
![image](https://user-images.githubusercontent.com/63556313/102688724-865ded80-4233-11eb-9a88-d8c967b84a27.png)

In the last week, I found that I cannot use typora to export pdf files. 

When I click the export button, nothing happens, and I can see related processes in the task manager, and they seem to be unable to complete the work.

I found this error message on the developer tools page. I uninstalled and reinstalled typora, but the problem was not resolved
Anyone who know how to sovle this problem?Please.

**Comment by abnerlee** [comment]
duplicate with #3710?

You can see #3766 for the workaround.

**Comment by Nilyang404** [comment]
> duplicate with #3710?
> 
> You can see #3766 for the workaround.
#3766  work for me. problem fixed. Thanks bro
just start Print Spooler.(I remenbered  that I baned it several weeks ago. From then PDF export doen't work.)
![image](https://user-images.githubusercontent.com/63556313/102762721-a2889880-43b3-11eb-88b5-4f0fff1a78a0.png)
