### ISSUE TITLE
Typora export pdf but no file created

### ISSUE THREAD

**Issue by Zurich1994** [typora/typora-issues#4068]
Windows 10, typora 0.9.98(beta).
I create a md file (even it is empty or a few words), then I save it.
After I export it to pdf and select the save-path and click the save button, nothing happens.
There are no files created.
I check the toggle devtools, it shows:
"""
DevTools failed to load SourceMap: Could not load content for file:///D:/Important/Typora/Typora/resources/app/lib.asar/pdf/pdf-lib.min.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///D:/Important/Typora/Typora/resources/app/underscore.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/app/window/frame.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/lib/codemirror/mode.min.js.map: 
export PDF to C:\Users\Administrator\Desktop\Untitled.pdf
"""
![image](https://user-images.githubusercontent.com/21177723/102696032-698edd80-4266-11eb-971a-68a7baad9202.png)
 and the typora.log shows:
![image](https://user-images.githubusercontent.com/21177723/102696057-80cdcb00-4266-11eb-977f-4e1860a81f20.png)

I don't know why.
I have re-install many times.
Someone can help?

**Comment by abnerlee** [comment]
duplicate with #4067 ?

**Comment by Zurich1994** [comment]
https://github.com/typora/typora-issues/issues/3766
finally worked.
