### ISSUE TITLE
Open Link Keyboard Shortcut

### ISSUE THREAD

**Issue by vorburger** [typora/typora-issues#4069]
It would be nice to have a https://support.typora.io/Shortcut-Keys/ for the Open Link described on https://support.typora.io/Links/#open-links-in-typora, instead of having to Ctrl-Click.

Combined with #1000, this would make for a great mouse free pure keyboard editing experience IMHO.

**Comment by mikez** [comment]
@vorburger Great suggestion about a keyboard shortcut to open a link. I came here to post the same thing. :)

Here's one workaround I found: ⌘+E (Edit > Selection > Select Styled Scope); then you could post-process the selection yourself as needed in a custom script.

**Comment by abnerlee** [comment]
"Open Link" is added to menu bar, now it is supported

**Comment by kbd** [comment]
Just started testing Typora, surprised there was no keyboard shortcut for this. The lack of keyboard shortcut for this in Zettlr was what got me looking for an alternative, as I'm used to pressing ctrl+cmd+enter to open links in vscode.

On Mac, to assign a keyboard shortcut (cmd+shift+k):

```shell
defaults write abnerworks.Typora NSUserKeyEquivalents '{
    "Open Link" = "@$k";
}'
```
