### ISSUE TITLE
Default export directory

### ISSUE THREAD

**Issue by huzecong** [typora/typora-issues#407]
Currently in Typora 0.9.9.8.2 (Mac version), when I export my Markdown document to PDF, the default directory in the save file dialog is the directory from the last export.
But usually this last directory would be the export directory of a file opened before, and has nothing to do with the file I was working on.
For myself, I almost always export to the same directory as the open file. I was wondering if you could make this the default export path, or maybe provide an option to toggle this behaviour? Thanks.

**Comment by abnerlee** [comment]
We are using the native save dialog, the default path is most recent used directory. I think that is the way most mac app do.

**Comment by Tina-Bu** [comment]
I would love to have the option to change the default export location to the current directory as well.

**Comment by biji** [comment]
Please make default export location to directory where the `.md` is

**Comment by songchen1988** [comment]
Me too, I would also like to set default location to the folder where .md is

**Comment by abnerlee** [comment]
supported such option
