### ISSUE TITLE
[Bug] LaTeX Formula Incorrectly Rendered after Searching Its Content Using Ctrl+F

### ISSUE THREAD

**Issue by zyLiu6707** [typora/typora-issues#4070]
The LaTeX formula will be rendered as duplicated text after searching them:
For example:    `i -> ii`     `e.g. -> e.e.g.` or `e.g.e.g.`

Steps to Reproduce:
1. Create a new markdown file, and type $i$ as our example.
2. Hit `Ctrl + F` and search `i`.
3. You will see the `i` in `$i$` is highlighted. Hit `Esc` to finish searching and click your mouse elsewhere.
4. Then you will see there is one more `i` besides our original `i`. Shown as `ii`. However, if you check the source code for our markdown file, there is still only one `i` there.
5. If you close and reopen this file, all thing goes right, until you search the LaTeX code again.

I encountered this on Windows 10 1909, and Typora 0.9.98

**Comment by zyLiu6707** [comment]
Here are several snapshots of this bug.

![image](https://user-images.githubusercontent.com/31042884/102725538-67b82f00-42e5-11eb-812d-e94f8f5f9da4.png)
![image](https://user-images.githubusercontent.com/31042884/102725548-7ef71c80-42e5-11eb-96f2-950f0936886d.png)
![image](https://user-images.githubusercontent.com/31042884/102725556-91715600-42e5-11eb-907c-2169c9c6fa14.png)

**Comment by abnerlee** [comment]
fixed in new release
