### ISSUE TITLE
Typora DevTools Warnings and errors 

### ISSUE THREAD

**Issue by Zurich1994** [typora/typora-issues#4071]
Every time I open Typora, when I check the DEVTOOLS, it shows these warnings and errors.(even no files are opened)
"""
Failed to load resource: net::ERR_FILE_NOT_FOUND
frame.js:1 failed to add book to exported PDF { ReferenceError: PDFLib is not defined
    at a (file:///D:/Important/Typora/Typora/resources/app//app/window/frame.js:1:1080300)
    at file:///D:/Important/Typora/Typora/resources/app//app/window/frame.js:1:1084449 }
frame.js:1 export PDF to C:\Users\Administrator\Desktop\未命名.pdf
DevTools failed to load SourceMap: Could not load content for file:///D:/Important/Typora/Typora/resources/app/underscore.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/app/window/frame.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/lib/codemirror/mode.min.js.map: 
"""
How to address the root cause?
![image](https://user-images.githubusercontent.com/21177723/102729447-c0320f80-436b-11eb-85db-5edf8f321730.png)

**Comment by Nilyang404** [comment]
![image](https://user-images.githubusercontent.com/63556313/102736164-38ee9700-437f-11eb-95e5-d85de17eeaff.png)
same errors

**Comment by Nilyang404** [comment]
try this #4067

**Comment by Zurich1994** [comment]
> try this #4067
pdf can be export but the warnings and errors are still here

**Comment by abnerlee** [comment]
They are ignorable.

**Comment by Zurich1994** [comment]
> They are file loading errors/warnings, which is ignorable.

I want to understand the cause of the error, not the negative undisplay. Someone can help~

**Comment by abnerlee** [comment]
`xxx.user.css` are created by users for custom CSS, if you don't use custom CSS, you will not create `xxx.user.css`, then they will not be able to be loaded.

SourceMap are for web developers, we didn't release Typora with it.

**Comment by Zurich1994** [comment]
> `xxx.user.css` are created by users for custom CSS, if you don't use custom CSS, you will not create `xxx.user.css`, then they will not be able to be loaded.
> 
> SourceMap are for web developers, we didn't release Typora with it.

Thank you for your help, I will display it~
