### ISSUE TITLE
macOS lost work due to bug

### ISSUE THREAD

**Issue by saegl5** [typora/typora-issues#4074]
if I embed an iframe, and the frame is not done reloading but I press "delete," then often times the document will revert to an earlier version---heartbreaking to lose lots of work like that ><

Version 0.9.9.36.2 (4901)
macOS Big Sur 11.1 (20C69)

**Comment by abnerlee** [comment]
Could you post a iframe url that may trigger this?

**Comment by saegl5** [comment]
Example:
<iframe src="https://www.geogebra.org/geometry/q3rwgjhx?embed" width="800" height="750" allowfullscreen style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0"></iframe>

**Comment by abnerlee** [comment]
fixed in new release

**Comment by saegl5** [comment]
Awesome, thank you.

--
Ed Silkworth

PGP ID: 04A3 E2E2 3F74 4D09 32D7 9777 26F2 60F0 4191 F431

Sent from ProtonMail Secure Email.

-------- Original Message --------
