### ISSUE TITLE
【优化建议】Night主题下，代码块的背景色与主题色过于接近

### ISSUE THREAD

**Issue by shawnyeung** [typora/typora-issues#4077]
Night 主题下，代码块的显示和背景颜色过于接近，能否让代码块的颜色更突出一些呢？非常感谢

比如我下面的截图，几个数字都加了代码块，但是很难识别出来。
![image](https://user-images.githubusercontent.com/7479612/102991396-12358980-4554-11eb-84a0-803eac168ccb.png)

**Comment by camxcube** [comment]
哈哈，你這個真的是一個極小的問題，我想這也不必動用到作者來解決，因為你只要親自改動 css 文件，用甚麼你喜歡的顏色都可以。

**Comment by abnerlee** [comment]
Hmm, the night theme is designed like this. It's not a high contrast theme.

You can try other themes on theme.typora.io, for change css by custom css (http://support.typora.io/Add-Custom-CSS/)
