### ISSUE TITLE
home key behavior

### ISSUE THREAD

**Issue by dio833** [typora/typora-issues#4079]
Hi 

Is there opetion can change behavior when press home key.

I wish first pressed cursor jumps to first character of current line, second pressed cursor jumps to beginning of current line.

thks.

**Comment by abnerlee** [comment]
This is behavior supported in any OS / app? If not, we are not going to support it

**Comment by dio833** [comment]
I use the following app in windows
VSCode, EditPlus and EmEditor.
There are all supported the behabior.

**Comment by abnerlee** [comment]
relates #2693
