### ISSUE TITLE
Unable to add two subsequent footnotes in text

### ISSUE THREAD

**Issue by blochberger** [typora/typora-issues#408]
Adding a footnote that follows another, i.e. `[^1][^2]` results in `^1` being displayed as an URL. I tried to insert a space in between the two footnotes – yet alone to visually separate the two distinct footnotes `¹` and `²` from a single footnote `¹²`, i.e. it should display as `¹ ²` – but whenever I try to add a space in between it will be removed in fluent/preview mode.

A temporary work around is to write `[^1]&nbsp;[^2]`, for which the space character will still be removed when the file is reloaded.

**Comment by abnerlee** [comment]
Fixed
