### ISSUE TITLE
[request]Can use customer symbol instead of recommend one

### ISSUE THREAD

**Issue by robertlzj** [typora/typora-issues#4084]
Hi~ Only use Markdown in Typora is perfect.
And Lua editor [zeroBrane Studio](https://github.com/pkulchenko/ZeroBraneStudio) support basic Markdown too. Which I can copy paste from Typora.
But the editor use underscore `_` (not asterisk `*`) to mark emphasis, strong.
So, can typora support using symbol underscores?

**Comment by abnerlee** [comment]
duplicate with #1433

**Comment by robertlzj** [comment]
Hi, I know I can write `_emphasis_` directly.
But how can I use shortcut to format a word using `_` too.
So, I can copy paste to another editor, which didn't support various syntax choices.

**Comment by abnerlee** [comment]
this is duplicate with #2445, can be part of #1433
