### ISSUE TITLE
Inline colors for text highlighting?

### ISSUE THREAD

**Issue by snoitallicso** [typora/typora-issues#4087]
Typora is a great product that I use every day. But I am missing the function of coloring the text with different colors and every time I have to manually add inline "spans" with background CSS color

![typora hl1](https://user-images.githubusercontent.com/28826339/103303625-fee55b00-4a38-11eb-8067-02a6d78662bf.png)
![typora hl2](https://user-images.githubusercontent.com/28826339/103303630-01e04b80-4a39-11eb-942c-e56b4071a9dc.png)

**Comment by Ikuyu** [comment]
I miss this feature too.

**Comment by abnerlee** [comment]
There is no markdown syntax for this.

Should be covered by #1288 #1993

You can use aText or TextExpander for current workaround

**Comment by Ikuyu** [comment]
I think Ulysses uses ::marked text:: for this.

—
Edwin (Ikuyu) Jonkvorst-Claes

**Comment by snoitallicso** [comment]
I am at Linux now

**Comment by abnerlee** [comment]
> I think Ulysses uses ::marked text:: for this.

We support "marked" by ==marked== after you enable highlight in preferences panel.


You could check https://alternativeto.net/software/textexpander/?platform=linux for quick input
