### ISSUE TITLE
Insert date using Automator Actions on mac

### ISSUE THREAD

**Issue by getianao** [typora/typora-issues#4088]
I have an automator script on my mac which prints date to stdin. The script is quite simple as follow:`date "+%Y-%m-%d %H:%M:%S"`
In other application, I can select the `Service > Time` and will insert date at the cursor position, but nothing willl happen in typora.
The version of typora is Beta 0.9.9.36.2 and macOS is Big Sur 11.1.
Any help would be gratefully received! Thanks.

**Comment by abnerlee** [comment]
Possible to attach the automator script?

**Comment by getianao** [comment]
![image](https://user-images.githubusercontent.com/23648839/105019761-6f542a80-5a81-11eb-9f11-d547b646e8e7.png)

**Comment by abnerlee** [comment]
works with latest version in my test.

relates #4051
