### ISSUE TITLE
After 'Move to Trash' with md file being open, switching to another md file prompts to save/discard

### ISSUE THREAD

**Issue by Cobertos** [typora/typora-issues#4089]
Platform: Windows 10 x64 Build 19041
Typora Version: 0.9.98 (beta) (Check for Updates... says latest)

## Actual
When moving an open md file to trash, I'm still getting a prompt to save/discard changes after I try changing to another note.

## Expected

There should be no prompt after moving away from a file that's just been deleted.

**Comment by abnerlee** [comment]
When delete current file, current window becomes an untitled / unsaved file. An extra confirm will be needed to discard current content
