### ISSUE TITLE
irregular bars under math blocks 

### ISSUE THREAD

**Issue by sbhattacharyya0** [typora/typora-issues#4092]
Irregular bars under math blocks appear seemingly at random, as shown in the screenshot below. Is this a feature or a bug, and how can I prevent it from happening?
![Screenshot_20210102_153025](https://user-images.githubusercontent.com/50296037/103466093-a4d1e780-4d0f-11eb-8267-40df426911ea.png)

**Comment by abnerlee** [comment]
Still exist in 0.10.11?
