### ISSUE TITLE
文件内容已被外部程序更改。是否重新加载文件？

### ISSUE THREAD

**Issue by onononp** [typora/typora-issues#4093]
从2020年12月份开始到现在，typora就不断弹出这个提示框，提示“文件内容已被外部程序更改。是否重新加载文件？”。    但是事实上我只用typora打开了这个文件，从没有在别处打开过……

**Comment by 657997746** [comment]
请问，问题解决了吗？

**Comment by chenkuncloud** [comment]
@ilovelxy 您好，为啥关闭了呀，请问是解决了吗？我也遇到这个问题，我是在微盘中打开，然后一直弹出这个提示框，但是明明没有其他人修改

**Comment by lxy35326** [comment]
> @ilovelxy 您好，为啥关闭了呀，请问是解决了吗？我也遇到这个问题，我是在微盘中打开，然后一直弹出这个提示框，但是明明没有其他人修改

最后肯定是解决了 但是我早就不用了  应该是关掉设置里的”自动保存“ 或者是其他选项 具体的我也忘了

**Comment by chenkuncloud** [comment]
> > @ilovelxy 您好，为啥关闭了呀，请问是解决了吗？我也遇到这个问题，我是在微盘中打开，然后一直弹出这个提示框，但是明明没有其他人修改
> 
> 最后肯定是解决了 但是我早就不用了 应该是关掉设置里的”自动保存“ 或者是其他选项 具体的我也忘了

haha，可否多问一句是用了其他markdown工具吗，我感觉除了这点typora还不错唉？

**Comment by lxy35326** [comment]
> > > @ilovelxy 您好，为啥关闭了呀，请问是解决了吗？我也遇到这个问题，我是在微盘中打开，然后一直弹出这个提示框，但是明明没有其他人修改
> > 
> > 
> > 最后肯定是解决了 但是我早就不用了 应该是关掉设置里的”自动保存“ 或者是其他选项 具体的我也忘了
> 
> haha，可否多问一句是用了其他markdown工具吗，我感觉除了这点typora还不错唉？

语雀，obsidian都用过，现在主用语雀

**Comment by chenkuncloud** [comment]
> > > > @ilovelxy 您好，为啥关闭了呀，请问是解决了吗？我也遇到这个问题，我是在微盘中打开，然后一直弹出这个提示框，但是明明没有其他人修改
> > > 
> > > 
> > > 最后肯定是解决了 但是我早就不用了 应该是关掉设置里的”自动保存“ 或者是其他选项 具体的我也忘了
> > 
> > 
> > haha，可否多问一句是用了其他markdown工具吗，我感觉除了这点typora还不错唉？
> 
> 语雀，obsidian都用过，现在主用语雀

感谢！祝好~
