### ISSUE TITLE
I can upload pictures via PicGo-Gui, but after typora testify it, it returned failed message

### ISSUE THREAD

**Issue by AmosChenYQ** [typora/typora-issues#4094]
![image](https://user-images.githubusercontent.com/31386769/103497735-5a6e7900-4e7d-11eb-8636-e1a072130f8f.png)
I can upload my file by dragging it into PicGo-GUI
but typora said:
![image](https://user-images.githubusercontent.com/31386769/103497772-7540ed80-4e7d-11eb-99c8-b66fbe1e7c21.png)
where is log about uploading? I tried to found it undder  ```C:\Users\{username}\AppData\Roaming\Typora.``` but it only contains some logs about opening,closing,bluring etc..

**Comment by abnerlee** [comment]
The log should be on picgo side. `{"success": "false"}` is all that it gives to typora.

Please try upload in picgo itself firstly.

**Comment by AmosChenYQ** [comment]
Oh, I have solved this problem. I just found that typora have already uploaded its logo picture with `typora-icon.png` and `typora-icon2.png` to test, then picgo failed because of the filename confict, but I can still upload files with different names in typora...
