### ISSUE TITLE
[help] How can I insert multiple tags in a single math block for different formula?

### ISSUE THREAD

**Issue by Rullec** [typora/typora-issues#4095]
Hi all,
I am using `typora` 0.9.98(beta) on Ubuntu 18.04. At this moment, I would like to have **multiple tags for each formula in a single math block**, like:
![image](https://user-images.githubusercontent.com/16875930/103536800-23748380-4ece-11eb-832d-29751d19686c.png)

But when I use `\tag` command in this block, it **reports an error** like
```
$$
a = 1 \tag{1}
b = 2 \tag{2}
$$
```
![image](https://user-images.githubusercontent.com/16875930/103536883-3f782500-4ece-11eb-9182-e7a6ffa40ef7.png)

Could anyone please tell me how to do that? 
Thanks!

**Comment by abnerlee** [comment]
use 
```
$$
\begin{align}
 x & = x + 1                    \label{A1}\tag{A1}    \\
 \text{eggs} &= \text{bacon}    \label{B1}\tag{B1}
 \end{align}
$$
```

from https://tex.stackexchange.com/questions/544353/aligned-equations-with-multiple-tags-per-line
