### ISSUE TITLE
Image Drag&Drop showing div on Firefox, Ubuntu 20.10

### ISSUE THREAD

**Issue by dorianbrown** [typora/typora-issues#4096]
Hi guys,

I've been using Typora for a few years and have been quite happy with all the usability features, and recently I wanted to start using the drag&drop functionality of images from the web. 

I found out that I was getting this kind of output when doing it from Firefox 84 on Ubuntu 20.10 (using [this picture](https://commons.wikimedia.org/wiki/File:Logo-Test.png)):
```
<�a href="https://upload.wikimedia.org/wikipedia/commons/8/85/Logo-Test.png"><�img alt="File:Logo-Test.png" src="https://upload.wikimedia.org/wikipedia/commons/8/85/Logo-Test.png" decoding="async" data-file-width="500" data-file-height="200" width="500" height="200"><�/a>
```

whereas if I do the same from Epiphany 3.38.1 (and probably chrome), I get the proper outcome:
```
![File:Logo-Test.png](https://upload.wikimedia.org/wikipedia/commons/8/85/Logo-Test.png)
```

Any idea what might be causing this? Is this a change in behavior on Firefox's side?

**Comment by abnerlee** [comment]
What about drag & drop from Firefox to other linux apps?

**Comment by dorianbrown** [comment]
If I drag the test image above from firefox into gnome-terminal, I get:
```
https://upload.wikimedia.org/wikipedia/commons/8/85/Logo-Test.png
```
This is the same result as epiphany, which works correctly with Typora

**Comment by abnerlee** [comment]
The image is a link, so if firefox put a link in clipboard, then in typora, we will get a link.
