### ISSUE TITLE
. prefixed files are invisible in 'Files' outline

### ISSUE THREAD

**Issue by DWalz** [typora/typora-issues#4097]
Files and Folders that are prefixed with a colon `.` do not show up in the `Files` tab. These files are hidden in the `Windows Explorer` but they are part of the file system anyways. I think they should show up.

I am running Typora 0.9.98 on Windows 10.

![image](https://user-images.githubusercontent.com/55062524/103592788-444fcf80-4ef4-11eb-9fa5-2d2c520c4596.png)

**Comment by abnerlee** [comment]
duplicate with #1753
