### ISSUE TITLE
Slow loading of images - MacOS

### ISSUE THREAD

**Issue by fiskeren** [typora/typora-issues#4098]
Recently moved from Win to MacOS and found that notes containing images are really slow at loading images. I can usually open the file, see all the text and then wait 10-30 seconds before the images are loaded. 

The images are loaded using relative paths from the same folder as the .md file. The files loads instantly using the Windows version.

System info:
macOS Catalina 10.15.7 (19H114)
MacBook Pro (13-inch, 2019)

Typora version 0.9.9.36.2 (4901)

**Comment by abnerlee** [comment]
Are those images large? Possible to provide sample md file and images to <hi@typora.io>?

**Comment by fiskeren** [comment]
Hi @abnerlee 

I've sent you an email - subject line is: "Typora - Slow loading of images on MacOS issue"

Kind regards

**Comment by abnerlee** [comment]
What about v1.2.4?
