### ISSUE TITLE
Dictionary files keep being missing after closing session ubunu18.04

### ISSUE THREAD

**Issue by kiey** [typora/typora-issues#4099]
Every time the spellchecker is changed from (for instance) EN to another language (IT/ES) it makes me "install" the missing spellchecker.

I have checked the folder typora-dictionaries and they are already there.
I have also tried to [manually](https://support.typora.io/Spellcheck/) install the dictionaries in the dictionaries folder without success. It is ambiguous to me if inside the dictionaries folder there has to be a folder  "es" or it has to be the contents of it. I have tried both.
What I understand it has to be the folder since all languages have the same name for the files.

**Comment by abnerlee** [comment]
It only happens to "es" or also include other languages as well ?

**Comment by kiey** [comment]
To others as well, I can confirm also IT and CA but as far as I can see it happens with all of them

**Comment by kiey** [comment]
Solved by itself
