### ISSUE TITLE
Is it possible to reference (and include) other Markdown files?

### ISSUE THREAD

**Issue by eFiggy** [typora/typora-issues#410]
Hi! I've been writing a guide for my fellow IT peers. I was thinking about separating my guide into different files, one per section, since some parts are already done and can be shared but others are still works in progress. However, I don't see if there's a way to link all the sections together into one big guide. Is this a feature that could be implemented into Typora? Thanks!

**Comment by abnerlee** [comment]
In latest version, reference is possible using link syntax, e.g. cmd/ctrl + click hyperlink `[link](other-content.md)` would open `other-content.md`

**Comment by vassudanagunta** [comment]
@vndsrswt See #1000. In that proposal, clicks on references and in the sidebar do not open a new tab or window, because most people expect such clicks to be navigation. New tab/window is achieved by meta-key override. If you like that, vote it up! If not, comment over there please.
