### ISSUE TITLE
Randomly broken code blocks markup during edits

### ISSUE THREAD

**Issue by NSentinel** [typora/typora-issues#4100]
I often use code blocks while preparing markdown with list items before them.

Typora sometimes loses the code block closing tag or duplicate it during editing, destroying the markup and (very rarely, 1 or 2 times) losing part of the document.

This error exists for a long time (over a year at least) and pretty annoying.

I was able to form a repro case, check the attached md in the archive and try to save it: [Test.zip](https://github.com/typora/typora-issues/files/5772428/Test.zip)

Sample markup:

![image](https://user-images.githubusercontent.com/2722498/103693291-19c04e00-4faa-11eb-8de8-fc7439bd6511.png)

**Comment by abnerlee** [comment]
For 
~~~
- **2**
  
      ```bash
      
      systemctl set-default multi-user.target
    ```
~~~

~~~
      ```bash
      
      systemctl set-default multi-user.target
~~~
is one code block

~~~
  ```
~~~
is another code block


But typora now does not support use "```" without a close tag for code fences.

**Comment by NSentinel** [comment]
But this markup was created by typora. My only manual edit is skipping a few blocks before and after the sample to narrow the issue.

Is there something I can do to prevent this? Or maybe I should use typora to edit code blocks specially?

**Comment by abnerlee** [comment]
> But this markup was created by typora. 

Could you still recall how this markup was created?

**Comment by NSentinel** [comment]
Sure, it was recently and does not differ from my usual work with typora.

Usually the sequence of actions is as follows:

- add [TOC]
- add another section
- add a list of notes
- sometimes I need to add an illustration in the form of a code fragment. In this case I add a new list item to continue there further and in front of it I manually type "```", then click on the lower right bar to add a language there (usually "bash") and add the code snippet.
- sometimes a piece of code is formatted as a separate item in the list, in which case I often remove the "-" before so that it goes along with the previous list item.

As for the attached example, I noticed that my current document fell apart, looked for what exactly was wrong in it and tried to isolate the fragment that was destroyed on saving, removing extra lines, but not changing the formatting and indentation in the problematic part.

**Comment by abnerlee** [comment]
fixed in new release
