### ISSUE TITLE
Hard breaks after combining files

### ISSUE THREAD

**Issue by stighagen** [typora/typora-issues#4101]
Hey,

When combining several files with pandoc it reduces the width of the document by several words:
pandoc input1.md input2.md input3.md -o output.md
Also when exporting to .odt it inserts hard breaks.

How can I avoid this? Please see screenshots.
![Screenshot 2021-01-07 at 19 54 22](https://user-images.githubusercontent.com/76871219/103933146-3338d580-5123-11eb-8c95-9ff18189d10e.png)
![Screenshot 2021-01-07 at 19 54 39](https://user-images.githubusercontent.com/76871219/103933164-392eb680-5123-11eb-9fcb-09c40ffc100f.png)
![Screenshot 2021-01-07 at 19 59 37](https://user-images.githubusercontent.com/76871219/103933175-3d5ad400-5123-11eb-87b0-0a746f7524e8.png)

**Comment by abnerlee** [comment]
in "pandoc input1.md input2.md input3.md -o output.md" typora is not involved. I think you should report to pandoc?
