### ISSUE TITLE
Proposal: Allow to encode images as base64 in the when-insert-images option

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#4102]
When I paste an image, it would be nice to have the option to encode it directly into the Markdown file using base64 data. First, this allows for keeping the Markdown file independent, and second, this makes auto-backups of images easier. wdyt? :-)

**Comment by LinqLover** [comment]
Also, I just noted that images' locations are not updated when saving a file at a new place.

**Comment by abnerlee** [comment]
should be part of #88
