### ISSUE TITLE
YAML Frontmatter and Tabs

### ISSUE THREAD

**Issue by h4tr3d** [typora/typora-issues#4105]
Hi,

During YAML FrontMatter editing if I press Tab Tabulation symbol is inserted. But such symbols is disallowed in YAML spec. I think, that 2 spaces (I prefer 2, but this parameter must be configurable) should be inserted instead.

Also, during auto indention tabs also inserted.

**Comment by abnerlee** [comment]
should be a part of #579

**Comment by h4tr3d** [comment]
I agree with duplication.

**Comment by abnerlee** [comment]
fixed in new release
