### ISSUE TITLE
Increase max size of mermaid markdown file

### ISSUE THREAD

**Issue by lingster** [typora/typora-issues#4109]
Hi, 
For mermaid, the default file/text size is 50,000 characters. Is it possible to incease this? 
It should be a fairly trivial fix, here is how the javascript looks like: 

```
mermaid.initialize({
  maxTextSize: 90000
});
```
Thanks,
Ling

**Comment by abnerlee** [comment]
Would you provide example md file? I want to make sure `maxTextSize: 90000` won't be too slow.

**Comment by lingster** [comment]
Just thinking about this, would it make more sense for this to be configurable in settings somewhere? Then a warning/caveat could be added for any advanced users?

**Comment by abnerlee** [comment]
Hmm... We don't have plans to include too much options if only few users would use it.
