### ISSUE TITLE
Preserve existing line feeds?

### ISSUE THREAD

**Issue by ig-sinicyn** [typora/typora-issues#411]
Typora 0.9.21, windows 10 x64.

The editor does not preserves line feeds for existing documents. To reproduce: create a new text file with line breaks, open it in typora and save.
Default line breaks (CRLF) replaced with linux-style LFs.
![diff](https://cloud.githubusercontent.com/assets/11225241/20226707/2f06d1d6-a85a-11e6-82ae-5489ffd7e878.png)

Shouldn't these be preserved as is? I mean, Typora should use LFs for files with LF line feeds and CRLFs for files with CRLFs.

BTW: thanks for the great editor! As so far it's the best one and with #57 it will be even better:)

**Comment by abnerlee** [comment]
merge this request to https://github.com/typora/typora-issues/issues/556
