### ISSUE TITLE
When the cursor is at the bottom of the document, the focus does not change after pasting

### ISSUE THREAD

**Issue by farid-moradi** [typora/typora-issues#4110]
os: Ubuntu 20.04
Typora 0.9.98

After pasting a text, the cursor moves to the end of the pasted text, but the focus does not change. Imagine that the cursor is at the bottom of the document and then you paste some text there. The cursor moves to the end of the new text, but you can't see it until you scroll down or type.
I don't know if you can call it a bug or not, but I think it would be better to change the focus after pasting.

**Comment by abnerlee** [comment]
try latest version?
