### ISSUE TITLE
problem in multiply monitors

### ISSUE THREAD

**Issue by mingkeYao** [typora/typora-issues#4111]
typora version: 0.9.98(beta)
operation: windows10
monitors info: left is 125% size and 1920*1080 pixel, right is 100% size and 1920*1080 pixel. And the main monitor is rigth one.

i have two monitors, and i place typora at right monitor, the bug as show below
![image](https://user-images.githubusercontent.com/33944326/104535280-dbcdc480-5650-11eb-92c2-3becf08b96da.png)

the 'file' in navigation bar, show wrong blank

**Comment by mingkeYao** [comment]
the second bug
when i place typaro between two monitors, the 'file' in navigation bar, show at wrong place, as below
![image](https://user-images.githubusercontent.com/33944326/104535963-197f1d00-5652-11eb-8e26-a0fad6aa2f2a.png)

**Comment by abnerlee** [comment]
caused by https://github.com/electron/electron/issues/10862 https://github.com/electron/electron/issues/26622

**Comment by abnerlee** [comment]
relates #4111 #2225
