### ISSUE TITLE
Make Shortcut Keys work on non-English keyboards

### ISSUE THREAD

**Issue by fasilav** [typora/typora-issues#4114]
Some of the default hotkeys in Typora are biased to U.S keyboards. Keyboards differ in layout obviously, so the problem is that some keys can't be accessed easily on non-english keyboards.

For example, on my Norwegian keyboard, the Grave Accent (Gravis) can only be typed by holding SHIFT,  pressing the Grave-key and then SPACE. This makes it impossible (afaik) to press the key combination: Command  + SHIFT + Grave, which is the hotkey for inline code in Typora.

I haven't looked too much into how to setup custom hotkeys, but I imagine that is not something the average user wants to do either.

**Comment by fasilav** [comment]
So I just read the [documentation](https://support.typora.io/Shortcut-Keys/) for shortcut keys.
> Set or add JSON object which represents a key binding, for example:
> ```
> "Always on Top": "Ctrl+Shift+P"
> ```

What about all the other options in Typora? How can I find the value for each of them? In my case inline code.

**Comment by abnerlee** [comment]
> What about all the other options in Typora?

The all options are all menu items displayed from the menu.

**Comment by fasilav** [comment]
Although I did find a workaround for this problem, I still believe this deserves some more attention. It's not like this problem is going away by itself.

As Typora gets more and more popular, more international users are going to use it. It would be a shame to have to change hotkeys that users are getting used to down the line. This is a great opportunity. Why not base the hotkeys on more common hotkey standards such as Github, WordPress, Confluence/Jira or other Markdown editors?

I don't think most users are going to care to setup their own hotkeys.

**Comment by alfonsovng** [comment]
Totally agree @fasilav. I tried to switch between source code mode and visual mode using CTRL + / and it didn't work... in my Spanish keyboard you get the / pressing shift + 7 and this combination is not working with typora. It would be great to have it working or, at least, having the option to configure it using the preferences menu.
