### ISSUE TITLE
pasting sometimes doesn't work

### ISSUE THREAD

**Issue by hbsmith** [typora/typora-issues#4116]
Using 0.9.9.36.2 (4901) for Mac.

For example, if I am trying to paste a list that I copied from a website. I think it's the bullet-point list formatting that for some reason causes pasting to be prevented.

**Comment by abnerlee** [comment]
Would you add the url and which list will cause pasting not work?

**Comment by hbsmith** [comment]
Hmm, it wasn't working the other day but appears to be working now. My apologies, I'll close.
