### ISSUE TITLE
URL trim spaces problem

### ISSUE THREAD

**Issue by snomiao** [typora/typora-issues#4117]
My input
`[New Issue · typora/typora-issues]( https://github.com/typora/typora-issues/issues/new )`

expected link:
`https://github.com/typora/typora-issues/issues/new`

but I got link:
`https://%20https//github.com/typora/typora-issues/issues/new%20`

enviroment:
- Windows 1809 build 17763.1282
- Typora for windows / linux version 0.9.98 (beta)

screen capture；
![image](https://user-images.githubusercontent.com/7323030/104809337-8b5c8f80-5827-11eb-8a58-da73598333af.png)

**Comment by abnerlee** [comment]
fixed in new release
