### ISSUE TITLE
Math Block Render from left

### ISSUE THREAD

**Issue by sirjei** [typora/typora-issues#412]
Hi, is it possible to render the math block from left? So that it is aligned with my other content.

This is what it currently looks like:
![math 1](https://cloud.githubusercontent.com/assets/11796949/20234952/78393306-a8c0-11e6-96f7-3e4610c3c228.png)

I'm kind of expecting something like this:
![math 2](https://cloud.githubusercontent.com/assets/11796949/20234959/9205e522-a8c0-11e6-809a-6233bee88c6a.png)

**Comment by iliyang** [comment]
Yes, it's possible. You need to edit the file `Typora\resources\app\window.html` and add the following line, say, after `skipStartupTypeset: true,`

`displayAlign: "left",`

This will instruct MathJax (the JavaScript library that renders the formulas) to align the output to the left. Here's the difference (click on the image to see it in full resolution):

![image](https://cloud.githubusercontent.com/assets/802594/20240766/ad7e5c64-a918-11e6-9f06-ba1fa35f9192.png)

**Comment by sirjei** [comment]
Hi, Got it working with your instructions. Thank you for your help.  👍
