### ISSUE TITLE
Support  excel formula in table

### ISSUE THREAD

**Issue by yuhuihu** [typora/typora-issues#4121]
Here is another project to parsing excel formula.

Could this be imported to Typora?
It will be amazing feature.

 
https://github.com/handsontable/formula-parser

**Comment by DejayRezme** [comment]
I've been recently looking for that functionality in Typora :) 
I just learned that "emacs orgmode" actually supports this kind of thing: 
https://orgmode.org/manual/The-Spreadsheet.html

Basically the ability to do calculations in Typora in general or in tables would allow a much more flexible usage to document more complex things. Like doing simple pricing calculations and sums.

**Comment by abnerlee** [comment]
It's a litter out-of-scope for a markdown editor.

I will put into #2448 and close this one.
