### ISSUE TITLE
Code block inside table row support

### ISSUE THREAD

**Issue by CC-Hsu** [typora/typora-issues#4122]
Hi, Team,

Recently I tried Typora and find that the current Typora v0.9.98 does not handle code block inside table row perfectly.
https://stackoverflow.com/questions/28508141/code-block-inside-table-row-in-markdown

Maybe you can consider to improve this feature.

Thanks for your great work.

**Comment by abnerlee** [comment]
duplicate with #2666

And https://stackoverflow.com/questions/28508141/code-block-inside-table-row-in-markdown is not support by GFM, see following:

| Status | Response  |
| ------ | --------- |
| 200    | `json`                          |
|        | `   {`                          |
|        | ` "id": 10,`                    |
|        | ` "username": "alanpartridge",` |
|        | ` more code...`                 |
|        | `}`                             |
| 400    |                                 |
