### ISSUE TITLE
> What about all the other options in Typora?

### ISSUE THREAD

**Issue by jpcaveiro** [typora/typora-issues#4123]
> What about all the other options in Typora?

The all options are all menu items displayed from the menu.

_Originally posted by @abnerlee in https://github.com/typora/typora-issues/issues/4114#issuecomment-761302285_

A suggestion. Please write, in line 18 of `conf.user.json`:

```json
// All other options are the menu items 'text label' displayed from each typora menu.
```
or something alike.

**Comment by abnerlee** [comment]
We will add it in next version up.

**Comment by abnerlee** [comment]
added in new release
