### ISSUE TITLE
Cut the end of a line which ended by link

### ISSUE THREAD

**Issue by Higurashi-kagome** [typora/typora-issues#4126]
Hi👋, when I try to cut the text from a line to another line that ended by a link( `[link-name](URL)` ), part of the link will be cut too.

This might be related to #4125.

<details>
<summary>Details</summary>

![cut](https://user-images.githubusercontent.com/51501079/105456903-ef1c0800-5cc0-11eb-99f7-6074ef736569.gif)

</details>

<details>
<summary>Test text</summary>

```
[solstice23/argon-theme: 📖 Argon - 一个轻盈、简洁的 WordPress 主题](https://github.com/solstice23/argon-theme)

https://android99.me/
```

</details>

Thanks.

**Comment by abnerlee** [comment]
It's quite same with #4124
