### ISSUE TITLE
link on heading and insert text block from other .md doc

### ISSUE THREAD

**Issue by lindXdeep** [typora/typora-issues#4127]
I've been using typora for a long time, but there is no some functions that i feel need very much

1. Please add to Typora the ability to link to a specific header in another file:

> `[heading](folder/file.md#some_heading)`               // on to the heading

and on a block of text in another file

> `[text_block](folder/file.md#some_text_block)`        // on to the text block

2. The ability to insert a certain element into another document in much the same way as we do when inserting a picture

> `![heading](folder/file.md#some_heading)`             //  insert the  heading

> `![text_block](folder/file.md#some_text_block)`      //  insert the text block

**Comment by abnerlee** [comment]
duplicate with #1231 #441
