### ISSUE TITLE
Positioning in text with HTML entities counts them as 2 characters

### ISSUE THREAD

**Issue by rpopov** [typora/typora-issues#4129]
Typora version: 0.9.98
OS: Oracle Linux 8.3 (CentOS 8 compatible) GNOME

Scenario:
* Use the source: 
```&alpha;&beta;&gamma;&delta;12```   (without the apostrophes) 
* Typora shows it as 
αβγδ12 
* Click at 2 (position 6) - Typora positions the cursor after the & of delta entity, showing ```αβγδ &delta;12``` without the apostrophes
  Here the 3 letters αβγ are counted as 6 characters, thus the cursor is positioned after & of delta entity - after the 6th char, instead on 2 - the 6th character shown shown
* Click at 1 (position 5) -Typora positions the cursor after the ; of gamma entity, showing ```αβγ&gamma;&delta;12``` without the apostrophes
  Here the 3 letters αβ are counted as 4 characters, γ as 1 and the cursor is positioned after ; of gamma entity - after the 5th char, instead on 1 - the 5th character shown shown

The issue:
* Typora counts the entities as 2 characters
* Typora positions the cursor after the expected (6th,5th) position

Related to https://github.com/typora/typora-issues/issues/3985

**Comment by abnerlee** [comment]
fixed in 1.3.6
