### ISSUE TITLE
<samp> inline HTML tag is not rendered

### ISSUE THREAD

**Issue by mcesar-rlacruz** [typora/typora-issues#4132]
Hi,

I think the title says it all. When a `<samp>` tag is entered, it is not rendered, but the `<samp>` and `</samp>` tags remain visible and the text between them is rendered as normal text. Also, when after a `<samp>` tag you type `</` , the closing tag is not auto-completed.

V0.9.98(beta) for Windows.

Thanks & regards.

**Comment by mcesar-rlacruz** [comment]
Hi again,

After some research it seems that `<samp>` was mispelled to `<smap>` in file "frame.js" located in "…\Typora\resources\app\app\window" (this is the path in windows).

Hope this helps, regards.

**Comment by abnerlee** [comment]
fixed in new release
