### ISSUE TITLE
Add OCR for images

### ISSUE THREAD

**Issue by msthursday** [typora/typora-issues#4133]
**New Feature Request**:  Add OCR (optical character recognition) to Typora for automatically grabbing text from images.

**Use case:**  During meetings, I often grab screenshots for my meeting notes, then convert images to text for easy searchability.  In Onenote, it's an easy right-click and "Copy Text from Picture", then paste the text into the note.  It would be great if Typora had something similar.

**Comment by abnerlee** [comment]
put into #2242
