### ISSUE TITLE
JumpList and README.MD files

### ISSUE THREAD

**Issue by filippobottega** [typora/typora-issues#4134]
Hello,
  I'm editing a lot of README.MD files with Typora and I'm not able to find them quickly because they have the same name in JumpList.

![image](https://user-images.githubusercontent.com/2587684/105990359-a5596600-60a2-11eb-802e-a208496120a3.png)

  Is it possible to show the first line of MD files instead? Usually it's the title of the document.

  Thank you for your support,
    Filippo.

**Comment by abnerlee** [comment]
The space is quite limited to show first line.

But you can hover on that item to see its path.
