### ISSUE TITLE
Blank lines inside HTML block elements result in many HTML (or not) separated blocks

### ISSUE THREAD

**Issue by mcesar-rlacruz** [typora/typora-issues#4135]
Hi,

When writing (or pasting):
`<pre>`a

b

c`</pre>`

I get:
1. An HTML block consisting of "`<pre>`a" (when exported or copied as HTML it results in `<pre>`a`</pre>`)
2. A paragraph consisting of "b"
3. A paragraph consisting of: "c" with a `</pre>` tag inside it (when exported or copied as HTML it results in `<p>`c`</pre>`&zwnj;`</p>`)

Initially Typora seems to recognize all input as a single HTML block:
![image](https://user-images.githubusercontent.com/66778479/105995978-059fd600-60aa-11eb-8dc0-528afa3895d5.png)
but, when editing is finished, it splits it at each blank line:
![image](https://user-images.githubusercontent.com/66778479/105996081-2c5e0c80-60aa-11eb-9336-dab744cb5cd4.png)

Note that "a" is rendered in a different typeface that both "b" and "c" (as it is inside a `<pre>`, whereas the others are not).

I noted this behavior when pasting HTML code inside `<pre>` tags, but seems to happen with other HTML block elements, such as `<div>`, or even `<p>`.

I suppose that paragraph breaking at each blank line needs to be disabled inside HTML block elements. This is what Mark Text seems to do.

V0.9.98(beta) on Windows10.

Thanks & regards.

**Comment by mcesar-rlacruz** [comment]
Hi again,

I've consulted the current CommonMark specification. It says that HTML blocks will be broken at each blank line, but with some exceptions, among them the `<pre>`, `<script>` and `<style>` tags and also HTML comments.

I do not know if the aim of the developers is for Typora to strictly follow the CommonMark (or any other) spec, but in any case, **any** HTML being broken at blank lines may not be considered a bug (although, IMHO, for `<pre>`, `<script>`, `<style>` and HTML comments, it is).

Incidentally, TaxtMark does not split any HTML block at blank lines.

Regards.

**Comment by abnerlee** [comment]
#1939
