### ISSUE TITLE
Math Block problem while using \newcommand

### ISSUE THREAD

**Issue by KevinMei-Github** [typora/typora-issues#4138]
After inserted \newcommand at the top of a Math Block, it will fail to display normally.

Environment: ver. 0.9.98(beta) @ Windows 10 Home ver. 1909

Method to reproduce:

1. Create a math block then enter \begin{pmatrix} and \end{pmatrix}. Enter "1&1&1" as elements.
2. Move the cursor to the left of "\begin". Press enter to create a new line at the top.
3. Enter \newcommand\nc{\newcommand} in the new line.

You will find that it keeps telling you "Extra open brace or missing close brace".  If you clear the math block and enter "\", it will  display as "pmatrix", even if you delete the block and create a new one.

However, after saving the file and reopen it, it will display normally.

**Comment by abnerlee** [comment]
can be covered in #3455
