### ISSUE TITLE
Overwriting file when switching between open files

### ISSUE THREAD

**Issue by rolfrander** [typora/typora-issues#4139]
Version: 0.9.98 beta
Environment: Windows 10 Pro: 10.0.18363 N/A Build 18363

I have opened a directory in typora, switching between .md-files in separate subdirectories. Today I experienced one of these files being overwritten with the contents of another file. I have not seen this before, so I don't know how to reproduce. I have seen similar examples: the contents of one file seemingly identical to another, but this has been temporary and I have assumed this to be delayed updates of visuals due to high system load.

The directory I am using is inside a directory synced with Onedrive for business. (This also means I have automatic backups and was able to pull a recent version from OneDrive).

The files in question are under 100 kB in size with only simple markdown (headings and lists, a few tables, no formulas or sourcecode, no diagrams). There are, however, a few megabyte of embedded images (stored in the .assets-directory). Autosave is turned on.

**Comment by abnerlee** [comment]
This is duplicate with #3894

Does the filename on title bar still be correct after switching?
Did you edit files after switch files?
Possible to send us <hi@typora.io> the log file? (https://support.typora.io/Get-Logs/)
