### ISSUE TITLE
How to render math formulas in HTML-CSS instead of SVG?

### ISSUE THREAD

**Issue by iliyang** [typora/typora-issues#414]
I'm loving Typora – as a "power user" I never thought I'd like an editor with inline preview, but I have to say you've nailed it, especially with math typesetting!

I have a small issue with math rendering, however. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/802594/20240676/5ea424cc-a916-11e6-8369-2a3844c79f29.png)

The left app is Haroopad, the right one is Typora. Both employ MathJax to render formulas, but Typora configures it to output SVG which is not as visually crisp as the HTML-CSS output used in Haroopad.

Does anyone have an idea how to switch to HTML-CSS  output? I tried fiddling with the MathJax configuration in window.html by replacing

`jax: ["input/TeX", "output/SVG"]`

with

`jax: ["input/TeX", "output/HTML-CSS"]`

but this only resulted in *[Math Processing Error]* messages in the formulas (which are automaticaly cleared and replaced with the actual rendered formulas when entering in editing mode). The quality of the rendered formulas stayed the same...

**Comment by abnerlee** [comment]
Related issue: #888

Currently HTML-CSS output is much slower than SVG. And we do not want to add extra options/testing for this output.
