### ISSUE TITLE
When inserting images, "copying image files to local folder" option copies the image to the wrong folder.

### ISSUE THREAD

**Issue by rudolph-heisenberg** [typora/typora-issues#4141]
Note: 
This is Typora 0.9.9.36.2 (4901) running on macOS 11.1 on MacBook Air M1. 
However on Intel MacBook Pros and Macminis, the same problem exists (maybe it has existed for several months since I first discovered it)

How to reproduce:

1. Set the option `when inserting images, copy image files to local folder` on. If the option is set, the image file inserted into the md file will logically be copied into the  `./${filename}.assets` folder.

<img width="698" alt="截屏2021-01-29 下午5 37 33" src="https://user-images.githubusercontent.com/61699791/106258421-c2d03080-6258-11eb-8f55-3abe51e92d51.png">

2. Create a new markdown file, it has a default name `Untitled`. Change its name to `a.md`, and save it somewhere.
3. Change its name to `b.md`.
4. Drag a image into the `b.md` editor, Typora will prompt to ask you whether to create a local folder to hold the image.
5. Confirm, and it creates a local folder to hold the image.
6. However, the problem is that Typora creates a folder named `a.assets`, instead of `b.assets`.

<img width="633" alt="截屏2021-01-29 下午5 41 53" src="https://user-images.githubusercontent.com/61699791/106258838-5c97dd80-6259-11eb-9684-86f9082daa2e.png">

**Comment by abnerlee** [comment]
still occur in latest version?

**Comment by abnerlee** [comment]
#3520
