### ISSUE TITLE
Duplicate anchors are not supported

### ISSUE THREAD

**Issue by alvii147** [typora/typora-issues#4142]
Windows 10, Typora version 0.9.98 (beta)

In Github, duplicate anchors can be referenced this way:

```
[link to first header](#header)
# header

[link to second header](#header-1)
# header

[link to third header](#header-2)
# header
```

This does not seem to be supported. I also tried using raw html:

```
<a href="#newheader">Link to new header</a>
# header
<h2 id="newheader">header</h2>
```

This didn't work either.

**Comment by abnerlee** [comment]
You can use named anchors

For example:
```
<a href="#newheader">Link to new header</a>

# header

<span id="newheader"></span>header
```

But, yes, `<h2 id="newheader">header</h2>` should also be supported.

**Comment by abnerlee** [comment]
fixed in new release
