### ISSUE TITLE
Flat code fence level as default

### ISSUE THREAD

**Issue by plagasul** [typora/typora-issues#4144]
Thanks for the work in typora.

I use to export to pdf documents that include lots of code fences sometimes within lists. It would be useful to always have those at 0 level, so when exported to PDF they take all horizontal space. Doing this manually on the hybrid view gives me headaches, as it is prone to cause  level confusion. Not so on code view of course.

Any way you may think of I can get this as default ?

Thanks

**Comment by abnerlee** [comment]
The list comes with indent by default. We don't see why we need to add such option to remove indent for certain types of block and only for export.

You can use CSS for print

```
@media print {
 ul,ol {
  padding-left: 10px; /** reduce indent for all list **/
 }

ul>li>pre {
      margin-left: -30px; /** reduce indent for pre in list**/
 }

ul ul>li>pre {
      margin-left: -60px; /** reduce indent for pre in list based on levels**/
 }
}
```

But we are less likely to add such options
