### ISSUE TITLE
List of tasks, no due dates or ordering required, would be very handy

### ISSUE THREAD

**Issue by taarond** [typora/typora-issues#4146]
Similar to how TOC works, I'd love to be able to drop in a summary list of all of the tasks in an article.  I don't care about due dates or nesting, and it'd be fine if they were shown in the order they appear in the article.  Ideally, as with the TOC, the list items would link to the tasks.

**Here's my use case, as an example:**
I use typora for writing and documentation, not for project management.  I use tasks in typora to remind myself where I need to complete documentation, research, or other things *relevant to the article itself*.  I have dozens of lengthy articles which I return to frequently to use and update.  Some of the articles are under revision management and have other contributors.

Adding tasks is easy ... finding them is hard.  I'd like to be able to place a list of the tasks for an article at the top of the page, so everytime I work with it I and other contributors know what's been left undone.

**Comment by abnerlee** [comment]
duplicated with #3637
