### ISSUE TITLE
Gui toggle to left-align (latex) math formulas 

### ISSUE THREAD

**Issue by jvhoffbauer** [typora/typora-issues#4147]
Being able to left-align latex/math formulas from preferences would be very handy. Especially, as markdown documents do not have a fixed length and having centered equations and left bound text breaks reading flow. 

Left-aligning of formulas can already be achieved manually by editing the `index.hmtl`, as described in https://github.com/typora/typora-issues/issues/1564#issuecomment-738534808

But this is not very handy and a gui setting would be nice.

**Comment by abnerlee** [comment]
We don't have plan for this, since we don't even have alignment gui for headers and paragraphs.
