### ISSUE TITLE
The software crashes when I try to highlight the code

### ISSUE THREAD

**Issue by Yecgaa1** [typora/typora-issues#4149]
It happened twice
The code I want to highlight is
`#define UNUSED(x) ((void)(x))`
The selected language is C
My software version is 0.9.98 in Win10

**Comment by abnerlee** [comment]
Is this reproducible? I cannot trigger the crash

**Comment by Yecgaa1** [comment]
opps，I try again but it didnt crash.
Hope it will not happened again in any computer.
Thanks

**Comment by abnerlee** [comment]
> If you need the crash report，I am willing to send it to you as well

Sure, please send to <hi@typora.io>, thanks!

**Comment by Yecgaa1** [comment]
Sorry,but where can I find the crash log?

> > If you need the crash report，I am willing to send it to you as well
> 
> Sure, please send to [hi@typora.io](mailto:hi@typora.io), thanks!
