### ISSUE TITLE
Portable Windows version?

### ISSUE THREAD

**Issue by iliyang** [typora/typora-issues#415]
Would it be possible to create a portable version of Typora for Windows? That is, one that keeps all its settings in the program directory and not in `C:\Users\[user]\AppData`? Perhaps it's already possible to edit a configuration file to achieve this?

**Comment by abnerlee** [comment]
##371

**Comment by Firef0x** [comment]
@iliyang You can try this if you want: [Markdown Editor Typora 32/64 bit v0.9.51 Portable version - PortableAppK](https://portableappk.com/portable-typora/)
