### ISSUE TITLE
Upload service uPic (AppStore) cannot be used normally

### ISSUE THREAD

**Issue by liuzhihang** [typora/typora-issues#4150]
uPic released the AppStore version, but the AppStore version cannot use the upload service normally.

![image](https://user-images.githubusercontent.com/26057042/106550342-ed1e3880-654d-11eb-98ba-a46fb6aed060.png)

**Comment by abnerlee** [comment]
Can you run the same command line in terminal successfully?

**Comment by liuzhihang** [comment]
@abnerlee 

uPic now has two versions. One is the AppStore version and the other is the github version.

The path of uPic downloaded from AppStore has been changed.

![image](https://user-images.githubusercontent.com/26057042/106568409-35e5e980-656e-11eb-97af-e5ad39356fce.png)

I can use the following command to succeed

```bash
/Applications/uPic.localized/uPic.app/Contents/MacOS/uPic -o url -u "/Applications/Typora.app/Contents/Resources/TypeMark/asserts/icon/icon_512x512.png" "/Applications/Typora.app/Contents/Resources/TypeMark/asserts/icon/icon_256x256.png"
```
The changes are `/Applications/uPic.localized/uPic.app`
