### ISSUE TITLE
Find in Files input box is not activated on Keyboard Shortcut on MacOS

### ISSUE THREAD

**Issue by carlba** [typora/typora-issues#4151]
OS: MacOS Big Sur
Version: 0.9.9.36.2 (4901)

Steps to reproduce:
1. Press CMD + SHIFT + F to do a find in files search.

Expected Result:
The find in files input box (above the file explorer) is shown and activated.

Action Result:
The find in files input box (above the file explorer) is shown but not activated.

**Comment by carlba** [comment]
It seems like it only happens when the  find in files input box is already open. I would expect that the input box is focused if the CMD + SHIFT + F is pressed.

**Comment by abnerlee** [comment]
should be fixed
