### ISSUE TITLE
Typora Mobile

### ISSUE THREAD

**Issue by AlexDev404** [typora/typora-issues#4152]
Hi. What would it take for you all or me myself to create a version of Typora for Android? I've noticed that the unibody appearance of Typora is relatively responsive and I think that porting to Android and IOS shouldn't be too hard to do.

**Comment by abnerlee** [comment]
duplicate with #525

We currently doe snot have such plan before v1.0

>  I've noticed that the unibody appearance of Typora is relatively responsive and I think that porting to Android and IOS shouldn't be too hard to do.

It's not only about the responsive UI, but mainly about optimization on small screen and touch operations, etc

**Comment by haozi6** [comment]
I have same requirement,I wish it could be used on my matepad ,iphone,even support webdav to nextcloud! like joplin
