### ISSUE TITLE
Is it a good idea to include markmap in typora ? 

### ISSUE THREAD

**Issue by hqgu** [typora/typora-issues#4155]
If markmap is included in typora,  it would be awesome to use simple markdown titles to write mindmap. 

more details can be found here: https://github.com/dundalek/markmap

![](https://github.com/dundalek/markmap/raw/master/doc/img/mindmap-screenshot2.png)
![](https://github.com/dundalek/markmap/raw/master/doc/img/mindmap-screenshot1.png)

**Comment by abnerlee** [comment]
merge into #1138

**Comment by yijinxie** [comment]
I want it.
