### ISSUE TITLE
Ability to render any diagram or other media formats using custom media handlers

### ISSUE THREAD

**Issue by rezanid** [typora/typora-issues#4157]
Typora is one of the best Markdown editors I have ever worked with. The only one I know that can provide a seamless Markdown editing experience. Markdown interpretations vary substantially between different tools and different teams (if not each individual). Everyone team or individual have their own set of preferences when it comes to extending Markdown. Directly embedding diagrams using Plant UML, Mermaid are probably the most popular feature requests for every Markdown editor app.

I understand adding all available extensions and keeping them up to date with the latest evolutions would be a burden for the development team, but when a Markdown editor app becomes popular everyone wants to see his/her preferred choices reflected into the tool.

# Current situation
Currently, there are two ways media formats foreign to Markdown can be embedded within a Markdown document. 
The first one is to open a code block and if it is supported out-of-the-box by the editor app, you can embed the diagram. For example:
```
```mermaid
```
In this case one should just hope that the external library in app is up to date with the desired one.

The second workaround is to convert the media to an image and use the image link syntax to reference it. For example:
```
![caption](link-to-image)
```

# Solution
I would like to suggest a rather simple solution for this issue that can potentially liberate everyone to bring their preferred diagrams and other media formats to Typora.
Typora could provide a simple convention to plug in external media handlers. For example these media handlers could be stored in a folder following the file extension they can handle (i.e. "`/.mediahandlers/plantuml`"). This folder can be a sub-folder to Typora's installation folder and / or a sub-folder to the folder opened by the user. In the latter, it would enable the user to work with different media handlers when working with different teams without having to switch media handlers when switching between different teams.

These media handlers could be used in both code blocks and image references with a syntax like the following:
```
```media:plantuml
```
```
![caption](link-to-media.plantuml)
```

**Comment by wiesener** [comment]
Sounds cool.

**Comment by bloff** [comment]
With a little more generality this would be more than enough for me. Namely, you should be also allowed to have inline blocks, such as `` `plugin-name:some-code` `` which would feed `some-code` into a javacript function that would return a dom object (similar to the media handlers described above, but the inline version, instead of the block version).

These three things are really easy to implement, and would add great value to typora.

**Comment by abnerlee** [comment]
duplicate with #1138

**Comment by rezanid** [comment]
> duplicate with #1138
@abnerlee, I don't think it's a duplicate. In #1138 the requested feature to add a few diagram types that the OP needed with no intention for any kind of extensibility. Other comments also suggest a few more diagrams. However, in this request the original intention is to bring the possibility to introduce many other diagram and media formats. This will allow the diagrams and media formats to evolve naturally as community embraces more formats. It will also allow one to fine-tune these formats according to one's workflow hence making Typora more usable beyond what is possible in the original product. I kindly suggest to open this feature request so people can bring more insight and / or vote.

**Comment by abnerlee** [comment]
> However, in this request the original intention is to bring the possibility to introduce many other diagram and media formats. This will allow the diagrams and media formats to evolve naturally as community embraces more formats.

We don't have plans to support all diagrams in #1138, #1138 should be fixed by introducing a way to extend its diagram capability, that's way it is considered as duplicated
