### ISSUE TITLE
Customizing local link resolution

### ISSUE THREAD

**Issue by Gozala** [typora/typora-issues#4158]
I love typora for writing, however current "Link to Local Files" behavior is problematic, because:

- Links without file extension link `[Foo](./foo)` only works if
  1. There is `./foo.md` file, but no `./foo` directory.
  2. Unfortunately `./foo` also does not resolve to `./foo/index.md`.
- Using file extension e.g. `[Foo](./foo.md)` has other problems:
  1. Generated / exported html will include file extension and will not work.

Current behavior makes it impossible to generate `.html` files along the side of markdown files, without either

1.  Breaking "Open Links in Typora" feature. E.g if I use links without extensions like `[Foo](./foo)` and generate `./foo.md -> ./foo/index.html` typora will start opening directory `./foo` when clicking on link instead of file `foo.md` 
2. If I generate `./foo.md -> ./foo.html` then typora works but links on the static site are broken because because there is no `./foo/index.html` (I can't change behavior of the host I'm using  to resolve to `./foo.html`)
3. If I use `[./foo.md]` style links that keeps working on typora, but then generated html also links to `./foo.md` as opposed html file. (I could change generator to replace file extensions, but then typoras export function will still generate links to markdown files).

It would be really great if it was possible to configure typora to how to do a link resolution so it can be customized as desired e.g. allow it to resolve `./foo/index.md` on links like `./foo`. Or make it prefer `./foo.md` over `./foo` directory when both exist.

**Comment by abnerlee** [comment]
Relates #2926

"Link to Local Files" is link to folder or local files.

If you want to link to generated html or link to original md file from a converted path, the rule is difficult to config (like jelyll is using rules like https://jekyllrb.com/docs/permalinks/)

Also, since Typora ia a local markdown editor, it should prefer open "foo.md" instead of "/foo/index.html", and also allow users to link to folder.

**Comment by Gozala** [comment]
> Also, since Typora ia a local markdown editor, it should prefer open "foo.md" instead of "/foo/index.html", and also allow users to link to folder.

What I was hoping to configure it to not to resolve `./foo` to do following in the listed order

1. `/foo.md`
2. `/foo/index.md`

>  also allow users to link to folder.

Maybe linking to folder could be achieved by using `./foo/` as opposed to `./foo` ? Alternatively above fallback list could be added: 3. `./foo/`  ?

Better yet, I think it would be good to allow configuring an order in which resolution algorithm sorts above list.

**Comment by abnerlee** [comment]
It's very implicit, and most md → html naming rule (like https://jekyllrb.com/docs/permalinks/) are more duplicated than this.

I will close, until more users request same thing.
