### ISSUE TITLE
Images wont insert- Running Typora 

### ISSUE THREAD

**Issue by benji88i** [typora/typora-issues#4159]
Hi there,

I am running Typora 09.98 (beta) on Linux (Fedora 33).

I installed this version of Typora from FlatHub in the Fedora software centre. 

I am not sure why but suddenly I cant insert images. Please see my screenshot below

![Screenshot from 2021-02-07 02-32-08](https://user-images.githubusercontent.com/68906758/107122608-c0bb4100-68ec-11eb-92d8-b4dcae8e7b7f.png)

Also these are my settings.

![Screenshot from 2021-02-07 02-33-45](https://user-images.githubusercontent.com/68906758/107122632-f2cca300-68ec-11eb-9654-08491a4c6f6b.png)

**Comment by abnerlee** [comment]
> I am not sure why but suddenly I cant insert images. 

Would you provide mode details about how you insert images and what's the response? Like drag and drop image not working, or, nothing shows pop when you click Format -> Image -> Insert Local Images...

**Comment by benji88i** [comment]
Hi there,

I am sorry for my delay. I hope I can still reach you or someone to assist.

Basically I have copy and pasted my text (which includes images). 

If you see below, there are two versions of Typora installed on this system. the flathub version (which is supposed to work on Fedora) and the snap package version.

The flathub version does not inser the images, (RHS)

Snap does insert with no problem (LHS).

![Screenshot from 2021-02-22 18-48-45](https://user-images.githubusercontent.com/68906758/108678019-a31de680-753e-11eb-665-4e50cd973bc1.png)


How can I get the flathub version to work correctly. ?

**Comment by benji88i** [comment]
Hi is there anyone seeing this?

**Comment by abnerlee** [comment]
see https://github.com/flathub/io.typora.Typora/issues/3

should be fixed in https://github.com/flathub/io.typora.Typora/commit/721e9e2babed5d1554d21e5d052c919ad5afba9d
