### ISSUE TITLE
Characters not loading while dealing with files

### ISSUE THREAD

**Issue by arysia** [typora/typora-issues#4160]
Hello,
While searching for files or saving files, characters don't render and instead show as boxes. I'm not sure if it's Typora or my system but I've only seen it happen with Typora.
This is on Ubuntu 20.04 and Typora version 0.9.98, happens 100% of the time. System font is Inconsolata 11pt

![2021-02-06-220052_1919x1199_scrot](https://user-images.githubusercontent.com/35059319/107138069-efbebc00-68c6-11eb-8b50-9d45fe38502a.png)

**Comment by abnerlee** [comment]
#4019
