### ISSUE TITLE
可以在每一篇文章，或者全局设置一个开关，近期代码块将使用语言，以此来减少工作量

### ISSUE THREAD

**Issue by ITmxs** [typora/typora-issues#4161]
每次点选代码块使用语言，过于麻烦，不知有没有解决办法！

**Comment by ITmxs** [comment]
You can set a switch in each article, or globally, and the language will be used in the code block in the near future to reduce the workload， Every time you click on the code block to use the language, it is too troublesome, I wonder if there is a solution!

**Comment by abnerlee** [comment]
#290
