### ISSUE TITLE
[Feature Request] Do not interpret raw URL text as hyperlinks

### ISSUE THREAD

**Issue by svenax** [typora/typora-issues#4163]
Currently, Typora interprets raw URL text as hyperlinks and exports them as such in the built-in formats. When exporting through Pandoc, they are however exported as plain text.

It would be nice to follow the Commonmark specification and only allow autolinks (e.g. `<http://link.com>`) to be interpreted as hyperlinks and keep raw URLs without any markup as plain text.

**Comment by abnerlee** [comment]
duplicated with #4032
