### ISSUE TITLE
[Mermaid CSS BUG] State diagram cannot be correctly displayed on V0.9.98

### ISSUE THREAD

**Issue by imbadark** [typora/typora-issues#4167]
First of all, thank you very much for your efforts. Typora is one of the best markdown editors at present

The current problem with mermaid is that the size of the `state diagram` is very **small** when rendering, which is inconsistent with other mermaid charts.

As shown below:
![image](https://user-images.githubusercontent.com/38650392/107312136-b787cb00-6aca-11eb-8145-55ddf454cb5b.png)

Here is the mermaid code: (Contact me if need any more info)

```mermaid
stateDiagram

[*] --> Live: open file

Live --> Suspect: Read(×)

Dead --> Live: RPC(√)
%%Dead --> Clear: stream close

Suspect: possible bad
Suspect --> Dead: RPC(×)
Suspect --> Live: RPC(√)
%%Suspect --> Clear: stream close
```

And I searched the existing issues, seems nothing more than these reasons:
1. Mermaid's own problem (self bug) 
2. Compatibility issues after integration (Typora bug)
3. Problems related to the user's **browser** and OS(operating system) or PDF format....

And I try to change the whole size of `mermaid` like this (which u mentioned already), but not work for this problem.

```css
/* Hot fix for mermiad size bug*/
:root {
    --mermaid-theme: default;
   }

/* Control the size of mermaid */
.md-diagram-panel-preview {
    zoom: 100%; 
}
```

These problems are complicated and it is indeed a headache, so sincerely give the following suggestions:
1. Maybe we should upgrade the mermaid version **carefully** to avoid bringing **a string of** bugs every time
2. At present, mermaid has become the de facto drawing standard of `md`, we can put some mermaid **config** in the document for convenience (such as diagram's size, core style, etc)
3. Do a separate compatibility UT for `mermaid`, if it fails, will not update to the new version (A lot of similar problems can be avoided)
4. If it is mermaid's own upgrade bug, there is a simpler way to solve it:  Allow users to **choose the latest versions** of mermaid, so that they can quickly **roll back** instead of modifying `css` by themselves and leaving hidden dangers.

**Comment by abnerlee** [comment]
It's same in https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5cblsqXSAtLT4gTGl2ZTogb3BlbiBmaWxlXG5cbkxpdmUgLS0-IFN1c3BlY3Q6IFJlYWQow5cpXG5cbkRlYWQgLS0-IExpdmU6IFJQQyjiiJopXG4lJURlYWQgLS0-IENsZWFyOiBzdHJlYW0gY2xvc2VcblxuU3VzcGVjdDogcG9zc2libGUgYmFkXG5TdXNwZWN0IC0tPiBEZWFkOiBSUEMow5cpXG5TdXNwZWN0IC0tPiBMaXZlOiBSUEMo4oiaKVxuJSVTdXNwZWN0IC0tPiBDbGVhcjogc3RyZWFtIGNsb3NlIiwibWVybWFpZCI6eyJzZWN1cml0eUxldmVsIjoibG9vc2UiLCJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0

should be a mermaid bug (or spec), merge into #1661

BTW, you can use 

```
stateDiagram-v2

[*] --> Live: open file

Live --> Suspect: Read(×)

Dead --> Live: RPC(√)
%%Dead --> Clear: stream close

Suspect: possible bad
Suspect --> Dead: RPC(×)
Suspect --> Live: RPC(√)
%%Suspect --> Clear: stream close
```

relates https://github.com/mermaid-js/mermaid/issues/1888

**Comment by imbadark** [comment]
@abnerlee  Thanks a lot for quick reply & advice. 

Although this is indeed caused by `mermaid`, it's also a **breaking change** for Typora user, which means they can only  can only choose the following decisions:
1. Choose to change `stateDiagram`  --> `stateDiagram-v2` in  all  `*.md` files,  and if this is just a **transition option** of mermaid, it may be changed back to **v1**, or **v3** in next version.... (seems unreasonable)
2. Seems that there is no such problem in the **last two versions** of mermaid, rollback may be a solution
    - Solution 1:  If we can config mermaid's version,  **WILL BE NICE** (😄)
    - Solution 2:  Otherwise, we can only roll back the version of `typora` to maintain compatibility, and wait for a stable version (a little sad 😢)

And as you says, it's **hard** to even find out from **official** documents or issues why such a breaking change has been made all of a sudden (And 7 days later with no reply)

So we should avoid following the latest version of `mermaid`, which has proved to be very **unstable** (bring a lot of bugs)

Or allow typora user to choose the mermaid version, most people don't want to have so much problems because of adding a trivial function (I believe you too, it’s not appropriate to continue to deal with these mermaid issues)

Thanks again, hope Typora gets better and better 💯
