### ISSUE TITLE
【Ctrl + S】save key, will change the indentation of several places by 【mistake】.

### ISSUE THREAD

**Issue by hanshou101** [typora/typora-issues#4168]
I encountered this situation when I completed an md document in 【quote + nested list】.

1. I pressed 【Ctrl + S】, and the indentation of the entire document was messed up.

2. If I continue to repair it manually, the same disorder will happen again when I press 【Ctrl + S】 again.

___

My working environment is:
> Typora versioni 0.9.98(beta)
> Windows 10 64-bit
> 【Default Indent】 is 4

___

The following is my Gist file:
> [Typora 【 versioni 0.9.98(beta) , windows 10 64-bit 】 , the indentation becomes misplaced when 【Ctrl + S】 pressed . ( 【Default Indent】 is 4 . )
](https://gist.github.com/hanshou101/d0827bb15e0a566a97bbd0ce05d60e84)
> I tested :  in above gist file , this situation can be easily reproduced when I press [Ctrl + S] on my windows 10 computer .

**Comment by abnerlee** [comment]
relates #2269

**Comment by abnerlee** [comment]
fixed in new release
