### ISSUE TITLE
Standard key combinations not working in Linux

### ISSUE THREAD

**Issue by AdamPS** [typora/typora-issues#4169]
Some standard keys don't seem to be working on Linux

- Shift+Delete to cut: **cannot** fix in conf.user.json
- Alt+Backspace to undo: can fix in conf.user.json

### Original Post

I'm new to Typora, very much enjoying it thanks.  I have learnt how to set a custom key and my settings are like this (matching LibreOffice):

```
{
  // Custom key binding, which will override the default ones.
  "keyBinding": {
    "Cut": "Shift+Delete",
    "Ordered List": "F12",
    "Unordered List": "Shift+F12",
  },
}

```

The ordered list works perfectly but the other two don't.  However the custom key *does* show on the menu to the right of the command name.  The problem is that I'm trying to use a key combination that already does something else.  I can get the unordered list to work if I remap the conflicting key:

`    "Toggle DevTools": "Control+F12",`

However I can't see how to fix my Cut command.  This is rather killing my use of Typora because instead of cutting, the text is deleted then in a little while when I try to paste my words have been lost.

**Comment by abnerlee** [comment]
For conflicted shortcuts, please resolve the conflicts (for example: "Unordered List": "Shift+F12")

About "Shift+Delete", what's your OS? It's already CUT in Windows

**Comment by AdamPS** [comment]
Thanks for the response.  Running on Ubuntu Linux 20.04.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by AdamPS** [comment]
Great many thanks.  I confirm that Shift+Delete to cut is working.  

Alt+Backspace to undo is not working by default however I can fix in conf.user.json so it's not a problem
