### ISSUE TITLE
Quick Question: Can someone explain to me what the outline panel is for?

### ISSUE THREAD

**Issue by J0hnGa1t** [typora/typora-issues#417]
Hi,

very basic question, I'm new to Typora and am wondering what the outline panel is and what's it for. Can someone give me a brief explanation?

Thanks so much, have a great day.

**Comment by vassudanagunta** [comment]
Just curious: Given your username, are you expecting an answer for free? How does FOSS fit into your apparent Ayn Randian world-view?

**Comment by abnerlee** [comment]
@J0hnGa1t Hi, you could try open help->quick start from menubar and then open the outline panel to see what it is
