### ISSUE TITLE
从源代码模式恢复回来后，光标会自动移到文章开头

### ISSUE THREAD

**Issue by loadingfd** [typora/typora-issues#4170]
如题，谢谢

**Comment by abnerlee** [comment]
same with #3969 ?

Could you provide sample file and typora verison?

**Comment by loadingfd** [comment]
看起来与文件有关，我复制粘贴的一份是正常的，版本是0.9.98(beta)
但是我尴尬地发现，源文件也恢复正常了，真是个诡异的问题
