### ISSUE TITLE
Problems when using Chinese input method to input.

### ISSUE THREAD

**Issue by lijiajunljj** [typora/typora-issues#4171]
When I generate an article on Hexo and edit it with Chinese input method, the cursor will automatically move to the YAML Front Matter.
Using Windows 8.1, Microsoft Pinyin input method.

https://user-images.githubusercontent.com/55282876/107389285-a1612580-6b31-11eb-866f-dcc5daeaeaf8.mp4

**Comment by lijiajunljj** [comment]
https://user-images.githubusercontent.com/55282876/107390024-3d8b2c80-6b32-11eb-9ec3-cd192ca35097.mp4


There is a problem with the video, it has been re-recorded.

**Comment by abnerlee** [comment]
duplicated with #3318?
