### ISSUE TITLE
Windows 10 Freezes

### ISSUE THREAD

**Issue by tonywithani** [typora/typora-issues#4172]
**OS Editions:** Windows 10 Enterprise
**OS Version:** 1909
**OS Build:** 18363.1316
**Typora Version:** 0.9.98 (beta)

**Issue:** Occassionally when I enter a value into a table I've created my entire machine freezes. I have to do a hard reboot to use the system again. This has occurred multiple times, it's not constantly happening though, but I can't see a pattern as yet.

**Comment by abnerlee** [comment]
I didn't met the freeze. but if there's a way to reproduce this, or a screencast, it should be much help

duplicated with #2938
