### ISSUE TITLE
My file was erased

### ISSUE THREAD

**Issue by PawcioCNCProfi** [typora/typora-issues#4173]
HI,
Yesterday I was working on a document for few hours. When I finished work I explicitly saved the document before setting the computer to sleep mode, because recently I had problems with it turning off, and closing all apps. Today I'm opening the file and it's completely blank!
The file weights 20KB but it's all nulls!
The file had content before, so I have backup of previous version, but the hours I put into it yesterday are lost.
I'm not hopping to recover the changes but I just wanted you to know about this. Maybe you should provide some backup for recent files Typora worked with...

**Comment by abnerlee** [comment]
Does https://support.typora.io/Version-Control/ work?

Also, what is your typora / OS version?

**Comment by PawcioCNCProfi** [comment]
> Does https://support.typora.io/Version-Control/ work?
> 
> Also, what is your typora / OS version?

Yes, I've found my work in drafts folder :D
My version of Typora is  0.9.98(beta)

**Comment by ichtestemalwieder** [comment]
sadly, I had a similar/same issue: 

While typing in typora,  the file suddely was completely empty. I  saw the text disappera from one moment to the other. This was a file of 15KB. 

After opening the file with Notepad++, it looked like this, containing only "nul" Chars: 
![image](https://user-images.githubusercontent.com/54768881/127649468-56f6c4a3-b8ee-4928-858a-27e6c122d264.png)

Luckily the Drafts Folder/Feature saved me. I would susepct this is an issue of typora... Just writing this for documentation, if others should have the same problem and searching via google.
