### ISSUE TITLE
how to seBackground grid

### ISSUE THREAD

**Issue by cyysu** [typora/typora-issues#4174]
Hello, how do I set the content background to be checked and the color to be light in Typora CSS styles

![image](https://user-images.githubusercontent.com/10364320/107531147-835df880-6bf7-11eb-9eab-127c4672adaf.png)

I tried the following first

content {
  background: url(./fzm-seamless.notebook.texture-04.png);
  background-repeat: repeat;
}

but It didn't look the way I wanted it to, but I'm sure the style worked

![fzm-seamless notebook texture-04](https://user-images.githubusercontent.com/10364320/107531478-da63cd80-6bf7-11eb-9fd3-4122126e76ac.jpg)

**Comment by abnerlee** [comment]
The image is not the image in your first screenshot, please try use a lighter image as background
