### ISSUE TITLE
"smart" matching of image relative path (use case: markdown blogging)

### ISSUE THREAD

**Issue by izikeros** [typora/typora-issues#4175]
When creating blog posts in markdown using Typora I couldn't count on having image previews since cannot provide image path in the format understood both by Typora and static site generator. The structure of files is as follows: 
```text
contents
├── images
│   └── img1.jpg
└── posts
    └── post_1.md
```
In the body of the post I need to insert image as: `![img](/images/img1.jpg)` - which is neither absolute or relative path. In Typora I'm opening `content` folder for work on blog. I have tried to open `content` folder and markdown document in Atom editor with "Markdown Preview" plugin and apparently it has some intelligence implemented to find and display the image in preview.

One possible solution could be to check two options when meeting leading `/` in the path:
- root of the file system and if file do not exists
- folder currently opened in Typora.

This could ensure working image previews in case one is opening `contents` folder in Typora.

**Comment by abnerlee** [comment]
duplicate with #1573

see https://support.typora.io/Images/#relative-path-to-current-filefolder-default-behavior
