### ISSUE TITLE
How to adjust line spacing between list items?

### ISSUE THREAD

**Issue by harrytran** [typora/typora-issues#4178]
The default line spacing in Typora seems too big and I would like to reduce them. 

I can tweak the theme's css to adjust the spacing between lines within the same paragraph (by setting 'line-height' value) and between paragraphs (by setting margin value for 'p'). 

However I cannot find a way to adjust the spacing between list items, both ordered and unordered lists. 
Please help. Thanks in advance. 

Note: this did not help
`li {margin: 0}`

**Comment by mcesar-rlacruz** [comment]
Have you tried:
```
li p {
  margin:               0;
}
```
?

Regards.

**Comment by harrytran** [comment]
@mcesar-rlacruz: That works, thanks a lot.
