### ISSUE TITLE
Jumplist/Recent documents support on Windows & macOS

### ISSUE THREAD

**Issue by smiley** [typora/typora-issues#418]
I started using Typora for notes & a general TODO list. It'd be awesome if the app supported recent document registration, allowing the user to pin their important documents to the menu:
![Pinned documents example](https://cloud.githubusercontent.com/assets/354181/20245354/423e4546-a9a8-11e6-9783-a29d8e7f0771.png)

[Electron has a guide for integrating with this](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md), and it requires just a single function call:
```js
app.addRecentDocument('/Users/USERNAME/Desktop/work.type')
```

Could you please look into adding support for this?

**Comment by abnerlee** [comment]
Should be fixed in new version
