### ISSUE TITLE
Ctrl-backspace and ctrl-delete do not erase selected text

### ISSUE THREAD

**Issue by labseven** [typora/typora-issues#4181]
Thank you for making this great markdown editor.

I use ctrl-backspace regularly to delete entire words at a time. This works in Typora when no text is selected, but when text is selected, ctrl-backspace and ctrl-delete do nothing.

To recreate:
Select text, press ctrl-backspace or ctrl-delete.

Expected behavior:
Selected text gets deleted.

Current behavior:
Nothing happens. I can delete the text with backspace or delete (no ctrl).

I am on Typora 0.9.98 linux, on Debian.

**Comment by abnerlee** [comment]
fixed in new release
