### ISSUE TITLE
MathJax fonts other than TeX are not available

### ISSUE THREAD

**Issue by mcesar-rlacruz** [typora/typora-issues#4182]
Hi,

I've found that the call to `MathJax.Hub.Config({})` is inside `window.html`. Putting `font: "STIX-Web",` (or any other MathJax font apart from "TeX") inside its `SVG:` section results in `[Math Processing Error]` being rendered instead of the equations.

Pursuing this I've found that the supplied MathJax engine is inside archive file `lib.asar` and inside it, in path `MathJax\jax\output\SVG\fonts\`, there's only a `TeX` folder, but none for the other MathJax fonts (STIX-Web, Asana-Math, Neo-Euler, Gyre-Pagella, Gyre-Termes and Latin-Modern). 

Apart from the above, is there a more user friendly way to customize MathJax that editing file `window.html`?

Thanks & regards.

**Comment by abnerlee** [comment]
duplicate with #2158
