### ISSUE TITLE
Finding CSS properties for $$ in Latex Rendering Mode

### ISSUE THREAD

**Issue by Zhu-Justin** [typora/typora-issues#4183]
Hi there,
I wanted to ask how I can modify the color of $$ once I begin typing in Markdown with LaTeX rendered. For example, this is the color of $$ before I begin typing:
<img width="55" alt="image" src="https://user-images.githubusercontent.com/31556466/107889404-5a33b580-6ee0-11eb-8087-0ca286f0974a.png">

Then the color of $$ changes when I begin typing:
<img width="138" alt="image" src="https://user-images.githubusercontent.com/31556466/107889430-83544600-6ee0-11eb-870d-a35381c60cb8.png">

My question is how can I change the $$ to be of the same color (black as opposed to light-gray) as I continue to type my LaTeX between $$. I am using the theme "Newsprint" but would like to be able to do this for all possible themes. Thanks!

**Comment by abnerlee** [comment]
It is not supported since if there is only "$$", it can be just normal texts.

I'll close since it is not a high priority issue
