### ISSUE TITLE
Recommended Way to Bulk Convert Typora Markdown to PDF using Pandoc

### ISSUE THREAD

**Issue by travisen** [typora/typora-issues#4186]
The team I am on has dozens of markdown documents created using Typora. We would like to use pandoc to bulk convert the Typora markdown files to PDFs.  We would like to include this as part of a Jenkins build job, so exporting from Typora to PDF does not work.

Unfortunately, the pdf output has issues. Namely:
- Typora uses pipe tables and pandoc does not autowrap table entries. The text goes off the right side of the screen.
- Code blocks fail to wrap. Though, I think I can solved this [using the listings package](https://tex.stackexchange.com/questions/121601/automatically-wrap-the-text-in-verbatim).

I apologize if this is more of a pandoc / latex issue, but, since we use Typora to create markdown documents, I was hoping someone had an idea for an automated Typora .md to .pdf solution.

Here is the pandoc command I am trying to use:
`pandoc --standalone --from=gfm+pipe_tables --to=pdf -V geometry:margin=1in --shift-heading-level-by=-1 --resource-path=.:images:jenkins --table-of-contents intputfile.md --output=outputfile.pdf`

I appreciate any help!

**Comment by abnerlee** [comment]
duplicate with #824

For table, you would enable table extensions, I guess -> https://pandoc.org/MANUAL.html#tables
For wrap, please try --wrap=auto|none|preserve
