### ISSUE TITLE
How does Typora change the font size when exporting to PDF?

### ISSUE THREAD

**Issue by mcesar-rlacruz** [typora/typora-issues#4189]
Hi,

This is not a bug report, but a question about how is the mechanism used by Typora to change the font size when exporting to PDF.

Writing a theme for Typora I've found that the font-size is not maintained from the screen media to the print media. Even more, it seems that the font size used when exporting to PDF varies in some way according to the selected print margins (or text line width). My .css insists on 12pt, but the exported PDF selects 10 pt or 9.5 pt but I do not know why & have no clue about how to force a desired font size on PDF.

Thanks & regards.

version 0.9.98(beta) on Windows10.

**Comment by abnerlee** [comment]
If you set a custom font size in preferences panel, that size will be used.
If not, it will use the font size in css. Please make sure `@media print` does not overwrite your custom font size or media query for screen width.

**Comment by Niuwujia** [comment]
How can I use the font size in css in printing PDF although I set a custom font size in preferences panel.

**Comment by lifecrane** [comment]
this is a cf tbh.. This app is very clean, but for non programmers, it should have clear screenshots , or instructions easy to follow.  its does not .. I have no idea what "Please make sure @media print does not overwrite your custom font size or media query for screen width. "' means, lol
