### ISSUE TITLE
Cannot open second instance from command line

### ISSUE THREAD

**Issue by RomkeVdMeulen** [typora/typora-issues#419]
The first time I open an existing file from the command line, all goes well:

```
$ typora first.md
```

But when I try to open another file from the command line without closing the first, this error is given:

```
$ typora second.md
secondary instance would exit
```

and then an instance of Typora starts up, but on a new document rather than the file I specified on the command line.

**Comment by RomkeVdMeulen** [comment]
I also just noticed that when I open a file from the command line, the folder property in the "File" sidebar is empty. This doesn't happen when opening through a filebrowser (Nautilus).

**Comment by RomkeVdMeulen** [comment]
If I launch using `xdg-open [filename]` instead, everything works as it should.

**Comment by abnerlee** [comment]
Should be fixed in new version
