### ISSUE TITLE
[Bug] Files fail to save on external volumes unless sudo'd

### ISSUE THREAD

**Issue by TheOneKevin** [typora/typora-issues#4192]
Typora Version 0.9.9.36.2
System Version MacOS 10.15.7, Catalina
Description:

Typora was granted full disk access.

There are files stored on an NTFS volume mounted using `ntfs-3g` under `macFUSE`.
The following behaviour was not present in other editors (TextMate and VSCode).

Upon saving files on the external drive, a message claims `The document ... could not be saved.`
indicating the failure to save files. Subsequent prompts to to either revert changes/duplicate file was shown.
A further message claims

> The document “...” is on a volume that does not support permanent version storage.

Debugger tools/Inspect element logs show nothing. No exceptions during saving (that I could see).
Opened `/Applications/Typora.app/Contents/MacOS/Typora` directly and saw no error message.
Curiously, Typora is able to create and duplicate files (when prompted, select "Duplicate") that **contain** the changes.
Also, when directly launching `Contents/.../Typora` under sudo, the same message about not supporting permanent storage was shown once and the file was saved successfully.

**Comment by abnerlee** [comment]
Can mac's TextEditor.app save on that location?

**Comment by TheOneKevin** [comment]
As mentioned, Typora started normally is able to write to the location when I select "duplicate" in the save option (ie duplicate/revert/cancel).

**Comment by TheOneKevin** [comment]
No, it can't.

**Comment by abnerlee** [comment]
The ntfs-3g seems not updated since 2012 so I didn't test it on my macOS.

But Typora let macOS handle saving proces, just like TextEdit or Paper (TextMate and VSCode are managed by their own), so it should be a macOS bug.

And could you share a screenshot? If it is like https://helpdesk.rushfiles.com/support/solutions/articles/5000553289-macos-volume-does-not-support-permanent-version-storage, then you can still save when you click "OK"

**Comment by thep0y** [comment]
If the hard disk is in GPT format, delete the EFI partition of this hard disk. 
I solved the problem of being unable to save through this method，and I hope it can help you.
