### ISSUE TITLE
Setting a command dialog "Do not show this again" flag to true does not persist until Typora is restarted

### ISSUE THREAD

**Issue by JohnLukeBentley** [typora/typora-issues#4193]
To reproduce:

* Load a document in Typora.
* File > Preferences ... > General > Dialogs > [Reset all Dialog Warnings]. Click it. Close preferences.
* View > Focus mode (to turn it on). You'll get the Dialog ...
  > Focus Mode has been turned on. .... [ ] Do not show this again. [Dismiss]
* "Do not show this again". Tick it. Click [Dismiss]. 

At this point: focus mode is turned; and you no longer expect to see the focus mode dialog message when toggling focus mode.

* View > Focus mode (to turn it off).
* No dialog box is displayed (as expected)
* View > Focus mode (to turn it on). 

The focus mode dialog mode appears. This unexpected given we've previously ticked "Do not show this again".

* Close and reopen Typora. That is, so we now have a second "session" of Typora.
* Repeat the above focus mode toggle  procedure in an attempt to made the Dialog reappear. It does not.

I reproduced that same bug with respect to the Typewriter mode command. Presumably, then, this effects all commands that offer a dialog box.

Therefore it seems the bug is that setting the "Do not show this again" flag to true does not persist until Typora is restarted, when it should persist as soon at is set (to true).

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by JohnLukeBentley** [comment]
Thank you kindly. 

Absolutely terrific piece of software, by the way. It well addresses an emergent, but increasingly important, need: to seamlessly switch between WYSIWYG and source views when working with markdown.
