### ISSUE TITLE
autoHideMenuBar setting does not take effect

### ISSUE THREAD

**Issue by miaoerwu** [typora/typora-issues#4194]
I use snap to install typora and set autoHideMenuBar to false, but the menu is still hidden, and I still need to press the alt key to display the menu

os: pop!_os 20.10
typora version: 0.9.98

**Comment by abnerlee** [comment]
should be covered by #1457 since we do not have snap support

Does Typora binary work?

**Comment by miaoerwu** [comment]
So far, everything is normal, except for this problem, no other problems have been found temporarily

**Comment by predr** [comment]
@miaoerwu When using snap version config is located at `~/snap/typora/current/.config/Typora/conf/conf.user.json` and false should be unquoted:

    "autoHideMenuBar": false,

**Comment by abnerlee** [comment]
conf.user.json should be removed by the previous snap manager.

Other similar issues are no tracked by #4473
