### ISSUE TITLE
Latex formulas only load after opening the second time

### ISSUE THREAD

**Issue by mippeqf** [typora/typora-issues#4195]

**Comment by mippeqf** [comment]
On the first try, they're displayed in the source-code format. Started happening around January 2021.

**Comment by abnerlee** [comment]
Could you provide a sample md file?

And what's your Typora version?

**Comment by abnerlee** [comment]
relates #4006

**Comment by bepvte** [comment]
![DC9kVlSVPc](https://user-images.githubusercontent.com/8226605/109217986-8d016780-7784-11eb-882a-33d68e010cec.gif)
Heres an example of what I think is the same issue.
Here's my sample MD file:
[Notes.md.txt](https://github.com/typora/typora-issues/files/6045797/Notes.md.txt)

**Comment by bepvte** [comment]
Workaround: Open a new empty window in typora, close the glitched window, and then from the new window do 'Open recents' and click your file. It should load with no problems.

**Comment by abnerlee** [comment]
should be fixed
