### ISSUE TITLE
Typora pdf export scaling is not proportional, too big

### ISSUE THREAD

**Issue by L1szt** [typora/typora-issues#4198]
When I export my typora project as a pdf document, the pdf looks way to big, meaning even though everything looks normal in the markdown editor, the pdf scales everything up so it is way to big. More explicitly, how can I customize the font size and margin of the document when exporting it? I tried to change the font size in the settings but that only changed it in the editor, not for the export.

**Comment by abnerlee** [comment]
You can use custom css (https://support.typora.io/Add-Custom-CSS/), e.g:

```css
@media print {
  html {
    font-size: 13px;
  }
}
```

margin relates #3971
