### ISSUE TITLE
Typora pdf export problems. win7 v0.9.92 AND v0.9.98

### ISSUE THREAD

**Issue by BingLee75** [typora/typora-issues#4199]
I can't export pdf even *.md file only have "abc".
windows 7 i5
V0.9.92
log file:
DEBUG 2021/2/23 下午6:54:58  app.openFile
INFO 2021/2/23 下午6:54:58  addRecentDocument
INFO 2021/2/23 下午6:54:58  [Raven] instanceKey = c6ca93e4-3c8d-45d3-9b76-9139cbc3cf83
INFO 2021/2/23 下午6:54:58  [Raven] userId = 98c53574-07ac-4ae0-8c70-0a942c74563f
INFO 2021/2/23 下午6:54:58  [focus] 1
INFO 2021/2/23 下午6:55:08  [blur] 1
INFO 2021/2/23 下午6:55:17  [focus] 1
INFO 2021/2/23 下午6:55:17  [blur] 1
INFO 2021/2/23 下午6:55:43  [focus] 1
INFO 2021/2/23 下午6:55:46  [blur] 1
INFO 2021/2/23 下午6:58:25  [focus] 1
INFO 2021/2/23 下午6:58:27  [blur] 1
INFO 2021/2/23 下午7:00:13  [focus] 1
INFO 2021/2/23 下午7:00:16  [blur] 1
INFO 2021/2/23 下午7:04:16  [focus] 1
INFO 2021/2/23 下午7:04:18  [blur] 1
INFO 2021/2/23 下午7:04:34  got argv [C:\Program Files\Typora\Typora.exe --allow-file-access-from-files E:\mdtest.md] from secondary instance
DEBUG 2021/2/23 下午7:04:34  app.openFile
INFO 2021/2/23 下午7:04:34  addRecentDocument
INFO 2021/2/23 下午7:04:34  [focus] 2
INFO 2021/2/23 下午7:04:34  secondary instance would exit
INFO 2021/2/23 下午7:05:02  got argv [C:\Program Files\Typora\Typora.exe --allow-file-access-from-files E:\mdtest.md] from secondary instance
DEBUG 2021/2/23 下午7:05:02  app.openFile
INFO 2021/2/23 下午7:05:02  addRecentDocument
INFO 2021/2/23 下午7:05:02  [focus] 3
INFO 2021/2/23 下午7:05:03  [blur] 3
INFO 2021/2/23 下午7:05:03  [focus] 3
DEBUG 2021/2/23 下午7:05:03  lastSync 1614078301428.2869, timestamp 1614078301433, mtime 1614078301428.2869
INFO 2021/2/23 下午7:05:07  [blur] 3
ERROR 2021/2/23 下午7:05:08  [Error: Failed to generate PDF]
INFO 2021/2/23 下午7:05:10  [focus] 3
INFO 2021/2/23 下午7:05:10  [blur] 3
INFO 2021/2/23 下午7:05:14  [focus] 3
INFO 2021/2/23 下午7:06:50  [blur] 3
INFO 2021/2/23 下午7:09:40  got argv [C:\Program Files\Typora\Typora.exe --allow-file-access-from-files C:\Users\***\AppData\Roaming\Typora\themes\Readme.md] from secondary instance
DEBUG 2021/2/23 下午7:09:40  app.openFile
INFO 2021/2/23 下午7:09:40  addRecentDocument
INFO 2021/2/23 下午7:09:40  [focus] 5
INFO 2021/2/23 下午7:09:40  secondary instance would exit
INFO 2021/2/23 下午7:13:45  [focus] 3
INFO 2021/2/23 下午7:13:52  [blur] 3
INFO 2021/2/23 下午7:14:55  [focus] 3
INFO 2021/2/23 下午7:14:57  [blur] 3

**Comment by abnerlee** [comment]
try #3766 ?

**Comment by BingLee75** [comment]
it still can't work. I restart "Print Spooler" serverce, and new error popup "A javaScript error occurred in the main process, Error: ECANCELED: operation canceled write."
