### ISSUE TITLE
Support the mermaid class diagram

### ISSUE THREAD

**Issue by wafer-li** [typora/typora-issues#420]
This example comes from [mermaid's README](https://github.com/knsv/mermaid)

```mermiad
classDiagram
    Class01 <|-- AveryLongClass : Cool
    Class03 *-- Class04
    Class05 o-- Class06
    Class07 .. Class08
    Class09 --> C2 : Where am i?
    Class09 --* C3
    Class09 --|> Class07
    Class07 : equals()
    Class07 : Object[] elementData
    Class01 : size()
    Class01 : int chimp
    Class01 : int gorilla
    Class08 <--> C2: Cool label
```

![image](https://cloud.githubusercontent.com/assets/12459199/20257135/01716384-aa8b-11e6-9515-a76cb11283b6.png)

But in typora, it just saying painting diagram

![image](https://cloud.githubusercontent.com/assets/12459199/20257199/50068812-aa8b-11e6-9584-e9e10f6678ed.png)

**Comment by botaohu** [comment]
+1

**Comment by abnerlee** [comment]
how do you use `classDiagram`? There's even no doc under `https://github.com/knsv/mermaid/tree/master/docs/content`. So I'm not sure whether it is completely implemented in mermaid or not

**Comment by wafer-li** [comment]
Sorry, I don't use Typora anymore.

It seems that the mermaid does **not** implement the class diagram.

I paste the code above into the live_editor of mermaid and it says invalid syntax.

![image](https://cloud.githubusercontent.com/assets/12459199/25647227/1dd7b686-2ffb-11e7-978b-f3b27c46621f.png)

**Comment by josh-hernandez-exe** [comment]
+1

You can still make a class diagram using their [`cli`](https://github.com/mermaidjs/mermaid.cli).
