### ISSUE TITLE
Export to HTML does not convert SVG images to inline images

### ISSUE THREAD

**Issue by acsdev** [typora/typora-issues#4200]
I have converted Markdown document to HTML document and everything worked perfectly.

But when I checked the HTML file I found this:
```
 <img src="IMG_FILE.svg">
```
Seems to me, that would be better if SVG files were converted in base64. So, the final result would be something like this.
```
 <img src="data:image/png;base64,iVBORw0KGgo ...">
```

**Comment by abnerlee** [comment]
#3656
