### ISSUE TITLE
No spell checking on macOS

### ISSUE THREAD

**Issue by heapcrash** [typora/typora-issues#4202]
I've searched all of the Preferences and cannot find a spell-checking feature for Typora.

Obviously code blocks should not be spell-checked, but it would be nice if there were a way to have a spelling and / or grammar checker for the prose parts of a Markdown document.

Does this feature already exist and I just can't find it?

**Comment by abnerlee** [comment]
like other apps, it is in Edit -> Spelling and Grammar from menu bar
