### ISSUE TITLE
[Missing feature] Allow for importing local css files within theme files!

### ISSUE THREAD

**Issue by ThatOneCalculator** [typora/typora-issues#4203]
When I 
```css
@import url('file:///home/kainoa/.cache/wal/colors.css');
```
in a theme file and set 
```css
--bg-color1: var(--background); 
```
it shows up as black instead of the color from that css file. It'd be nice to be able to import local css files for utilities like pywal!

OS: Arch GNU/Linux Rolling x86_64
Version: 0.9.98 (beta)

**Comment by abnerlee** [comment]
`@import` is supported.

You can debug CSS following https://support.typora.io/Add-Custom-CSS/

In that devtools, you can check whether colors.css is loaded or not.
