### ISSUE TITLE
How can I customize the highlight format for the code block

### ISSUE THREAD

**Issue by ZhengJiepengCN** [typora/typora-issues#4204]
I write some pseudo code in my doc, and I want to highlight some special parameters, just like the pic below. How can I do that ?  Could I customize the highlight format for the code block ?

![image](https://user-images.githubusercontent.com/5250530/109099463-20737200-775e-11eb-8305-176f0d8e2ce4.png)

**Comment by abnerlee** [comment]
It is currently not supported.
