### ISSUE TITLE
aligning text with inline code blocks

### ISSUE THREAD

**Issue by guesswh0** [typora/typora-issues#4206]
Source Mode:
<img width="241" alt="Screen Shot 2021-02-25 at 12 14 45" src="https://user-images.githubusercontent.com/10531675/109111461-27e94a00-7763-11eb-9e42-abfe296d94b3.png">

View Mode:
<img width="259" alt="Screen Shot 2021-02-25 at 12 14 19" src="https://user-images.githubusercontent.com/10531675/109111455-261f8680-7763-11eb-95ce-08417bef691f.png">

**Comment by abnerlee** [comment]
The font in view mode is not monospace, so "b" and whitespace are not in same width.

Relates #3451

For use tab for alignment, will be covered in #498
