### ISSUE TITLE
Mermaid diagram auto-scale size appears to be strange

### ISSUE THREAD

**Issue by vflanker** [typora/typora-issues#4207]
Very amazing to find that Typora support diagram rendering support for mermaid! But When using this feature I found some issues(maybe):

Here is the screenshot of my document:
![image](https://user-images.githubusercontent.com/30745146/109133008-78769c80-778f-11eb-920f-7a81bc0dc42e.png)

Apparently the **state diagram** is too small to view, no matter in edit mode or preview mode. And I can not find out why or how to modify. Is it a bug?

- Typora version: 0.9.98(beta)
- OS: Ubuntu 1804
- Arch: amd64

Thanks!

**Comment by vflanker** [comment]
Also appears in **ClassDiagram**:
![image](https://user-images.githubusercontent.com/30745146/109134719-4e25de80-7791-11eb-99f8-694e69c4c194.png)

Seems to be displayed in a fixed height.

**Comment by abnerlee** [comment]
it's a change from mermaid, see #4167
