### ISSUE TITLE
Typora with aarch64?

### ISSUE THREAD

**Issue by vflanker** [typora/typora-issues#4208]
Wondering if Typora can can on linux with aarch64(arm64) architecture. Typora use electron and that may be a important component. 

Questions:
- can we compile from source(but Tpora is not an open-source software) ?
- we will have the official distribution(currently only x64 and ia32 are released)?

If I really want to use Typora on an aarch64 computer, what is the best solution?
Thanks!

**Comment by abnerlee** [comment]
We don't support arm64 since it might be slow to run a electron-based app.
