### ISSUE TITLE
External programs in image upload script

### ISSUE THREAD

**Issue by jcobs-engine** [typora/typora-issues#4209]
Hey community,

i wrote an own image-upload script for typora. It's written in bash and contains commands like ftp.
When I run test image uploading, it says:
`/home/user/script/main.bash: line 12: ftp: command not found`
Of course, my script begins with:
`#!/bin/bash`

When I run my script in terminal "by hand", it works fine and returns my URL.

Why does it not work in typora?

**Comment by abnerlee** [comment]
you can run "which ftp" in your terminal, then replace ftp with the full path of it in your custom scripts.

What's your OS btw?

**Comment by jcobs-engine** [comment]
I'm using OpenSuse Leap 15.2.

Thank you, I have already tried it, but it returns: `/home/user/script/main.bash: line 12: /usr/bin/ftp: No such file or directory`

When i copy the ftp software to my script directory, it returns: `/home/user/script/ftp: error while loading shared libraries: libedit.so.0: cannot open shared object file: No such file or directory`

There seems to be a problem with paths outside the home directory, because in the last example it also works in the terminal, but not in Typora.

**Comment by abnerlee** [comment]
`/usr/bin/ftp: No such file or directory`, it means typora cannot find the file. Does typora have assess to that file?
