### ISSUE TITLE
Export fails for .docx and .odt

### ISSUE THREAD

**Issue by OleVik** [typora/typora-issues#421]
With version 0.9.21 (beta), exporting as Microsoft Word (.docx) or OpenOffice (.odt) fails silently. The text contains various Markdown, including footnotes, as well as an .svg-image (locally linked) and a flowchart (copied from the [examples](http://support.typora.io/Draw-Diagrams-With-Markdown/)). When exporting, nothing happens in either format.

Additionally, if using System Native Windows Style (on x64 Windows 10), the interface hangs after attempting to export. This does not occur when using Unibody. Export from `typora.log`:

```
INFO 11/14/2016, 8:32:28 PM{ width: 968,
  height: 1030,
  minWidth: 100,
  minHeight: 100,
  frame: true,
  disableAutoHideCursor: false,
  webPreferences: 
   { images: undefined,
     directWrite: true,
     defaultFontFamily: { standard: null, serif: null, sansSerif: null, monospace: null },
     allowDisplayingInsecureContent: true,
     backgroundThrottling: false,
     zoomFactor: 1.25 },
  autoHideMenuBar: false,
  show: true,
  fullscreen: null }
INFO 11/14/2016, 8:32:28 PMopen file: undefined
INFO 11/14/2016, 8:32:41 PMaddRecentDocument: C:\Users\Ole\Documents\Typora\Applications.md
INFO 11/14/2016, 8:32:41 PMaddRecentDocument: C:\Users\Ole\Documents\Typora\Applications.md
INFO 11/14/2016, 8:33:05 PMwindow.File && (function() {                document.body.classList.toggle("show-footer");            })();
INFO 11/14/2016, 8:33:10 PMwindow.File && (function() {                File.setCanCollapsePinnedOutline(true);            })();
```

Export as .pdf works, and Pandoc is installed and working (v1.18) I enabled Developer->Debug in Preferences, but this had no visible impact upon the interface. Is there some way to show a console for background processes, ie. to see if Pandoc failed?

**Comment by dztdeng** [comment]
+1

**Comment by abnerlee** [comment]
Should be fixed in new version
