### ISSUE TITLE
Print dialogue fails on second time through if Page Break option set

### ISSUE THREAD

**Issue by jobo49** [typora/typora-issues#4210]
If the print option "Page Break between Top Headings" is set, then you can only print once. On the second time of printing the output goes blank. User is forced to quit Typora to print more than once. 

Applies whether print is going to paper or to PDF.
![screenshot_514](https://user-images.githubusercontent.com/79638300/109142984-ce335080-775f-11eb-8e14-e4c7b765dd18.png)

**Comment by abnerlee** [comment]
We cannot reproduce this.

Possible to send us <hi@typora.io> a screencast about this?

**Comment by jobo49** [comment]
Hello

If you can't reproduce it, then it's might be a Big Sur problem on my Mac. I migrated to Big Sur 3 weeks ago, and have a couple of ongoing issues. I am running the latest version of Typora,  but to be sure I'll do a reinstall

I'll follow up on Monday and send you a screencast

--
__________________________
Jeff Ball

mobile  (France) +33 6 81 87 25 96

**Comment by jobo49** [comment]
Hello

Here is a screencast. Run on a second mac (both on Big Sur 11.2), with same
bug.

Rgds
 Screen Recording 2021-03-01 at 21.06.18.mov
<https://drive.google.com/file/d/12E8kXY4O7k9K_fAKbBserCGvrZoW-ltk/view?usp=drive_web>
________________________________________________________
Jeff Ball

mobile  06 81 87 25 96

**Comment by abnerlee** [comment]
@jobo49 I requested for access privilege, please approve. Or just send the file to <hi@typora.io>

**Comment by jobo49** [comment]
Hello

https://drive.google.com/file/d/12E8kXY4O7k9K_fAKbBserCGvrZoW-ltk/view?usp=sharing

I'm resending this. It's too big to send as attached file. So sending via
Google Drive. File is stored on my Google Drive, with permission set allow
access with the above link.

Rgds
________________________________________________________
Jeff Ball

mobile  06 81 87 25 96

**Comment by abnerlee** [comment]
Hmm... Still failed to reproduce.

Possible to send us the sample file? 

Does turn off vpn works and does use default "Presets" works?

**Comment by jobo49** [comment]
Hello

It's not related to one specific file. I did a test this morning on a
recent file, and the problem re-occurs. This recent file is attached, in
case it helps you.

I don't have a VPN on my main computer which is a desktop (MacMini), which
I am using today. I use one on my travel MacBook Air.

It's not related to default Presets. I used the default this morning for
the test, and the problem re-occurs.

Rgds
________________________________________________________
Jeff Ball

mobile  06 81 87 25 96

**Comment by abnerlee** [comment]
Still occur in latest version?

**Comment by jobo49** [comment]
Hello Abner

Everything looks perfect now. Thanks for your help :)

Rgds

Jeff
________________________________________________________
Jeff Ball

mobile:  06 81 87 25 96                                         site:
www.lean3.com
