### ISSUE TITLE
Bug: option + right arrow at end of Paragraph jumps to end of document

### ISSUE THREAD

**Issue by herixa** [typora/typora-issues#4211]
I think there is a small (but little bit annoying) bug. I often jump through my text with the cursor by typing  <kbd>option</kbd> + <kbd>&#8594;</kbd>. The cursor then moves word by word. Thats perfect.
But at the end of a paragraph the cursor then jumps to the end of the document, not (as I would expect) to the end of the first word in the next paragraph.

Am I right assuming that this is a bug? Anyway, for me it is kind of annoying as I often write in long documents and then have to scroll back a long way...

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> a screencast?

We failed to reproduce this in latest version.

**Comment by herixa** [comment]
I tried to reproduce it in a new document and couldn't reproduce it either. Sorry for this...
I think this issue can be closed then.
