### ISSUE TITLE
Typora always detects unsaved changes

### ISSUE THREAD

**Issue by nckturner** [typora/typora-issues#4212]
Sometimes when I save a document, and then try to navigate to another document, I get the message `Do you want to save the changes made to this document?  Your changes will be lost if you don't save them.`  Since I don't know what the changes are, I click `cancel` and check the document.  Then, even if I attempt to save them, the prompt returns.  I have not figured out a way of determining if there is actually unsaved changes.  I haven't lost anything that I've noticed, but I can't be sure.  What is the best way to check to see if there are actually unsaved changes, or further troubleshoot this issue?

Another note, so far, this hasn't happened immediately when I open typora, but after some time it seems to enter this state. Also, clicking `Save` directly from the prompt allows me to switch documents, but I'm not sure what the supposed "unsaved changes" were.

**Comment by abnerlee** [comment]
Which OS? 

Are you editing files in folder that is synced by apps like iCloud?

**Comment by nckturner** [comment]
Linux, and I believe it technically is a folder that syncs to a dropbox folder, but I don't normally have the dropbox daemon running so I'm slightly doubtful that's the issue.

**Comment by abnerlee** [comment]
Possible to provide a screencast? From save file to the message shows up?

And does this happen for files outside the dropbox folder?

**Comment by abnerlee** [comment]
#2354
