### ISSUE TITLE
Changing the name of the "Help" menu tab to "Info"

### ISSUE THREAD

**Issue by RealA10N** [typora/typora-issues#4213]
Currently, the last menu tab in Typora is named "Help". However, in my opinion, the name doesn't really represent the options in it:

![help-menu-image](https://user-images.githubusercontent.com/23400213/109363876-3d12c580-7896-11eb-9533-96e194181259.png)

I do understand that changing the name may sound like a piece of cake, but it will be kind of a hassle with i18n...
Another option is to maybe move the `Credit, Changelog, etc...` to a new tab named *Info* and leaving the first section of options under *Help*..?

Anyway, a really small "problem" that annoyed me and I thought I would share.

**Comment by abnerlee** [comment]
We don't have plan for this.

I think all apps end with a "Help" menu

**Comment by AlexPasternak** [comment]
@RealA10N, I wonder if you can post the contents of the Help menu in the browser you used to post this issue, and whether it only contains Help, similarly annoying you. Here's mine from Firefox, full of other support and info stuff, as is _completely standard_.

<img width="427" alt="2021-03-01 9 56 28 AM" src="https://user-images.githubusercontent.com/1819485/109514945-8882ca80-7a74-11eb-9914-5c4ab9ada323.png">
