### ISSUE TITLE
Spellchecker flags numbers with colons in between them

### ISSUE THREAD

**Issue by aaylnx** [typora/typora-issues#4214]
I need to make a lot of citations that use numbers with colons in between them (EG 11:19). Typora spellcheck always flags such instances as misspelled. Is there a way to fix that, or might not it be a good idea to disable such behavior for the default? I've tried making various adjustments to ~/.config/Typora/typora-dictionaries/user-dict.json using wildcards, but nothing seems to fix this.

Thanks for all of the wonderful work on Typora. I've used it for only a short time, and I am totally in love with it!

**Comment by abnerlee** [comment]
put into #214
