### ISSUE TITLE
HTML details section with code block rendered incorrectly

### ISSUE THREAD

**Issue by mightbxg** [typora/typora-issues#4216]
Consider this in markdown file (I added backslash to the line before `</details>` to prevent formatting in this page):
```markdown
<details><summary>click to expand</summary>
Normal text
</details>

<details><summary>click to expand</summary>

```shell
# code block in details
\```
</details>
```
GitHub page and vscode can render it normally, like this:
<details><summary>click to expand</summary>
Normal text
</details>

<details><summary>click to expand</summary>

```shell
# code block in details
```
</details>

--- 
However, the rendering in typora seems weird.  
before click:  
![image](https://user-images.githubusercontent.com/20889293/109619111-57d58a80-7b73-11eb-8c68-7edc6bb19d03.png)
after click:  
![image](https://user-images.githubusercontent.com/20889293/109619281-8d7a7380-7b73-11eb-846f-e79603bea61c.png)

--- 
OS: Manjaro 20.2.1 Nibia
Typora version: 0.9.98 (beta)

**Comment by abnerlee** [comment]
#1939
