### ISSUE TITLE
Exporting PDFs removes the table lines

### ISSUE THREAD

**Issue by ErickHoward** [typora/typora-issues#4217]
If I create a table like this: 
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

It looks like this in Typora: 
![image](https://user-images.githubusercontent.com/78889625/109735323-8ac46080-7bfd-11eb-818a-d6cedeaa7b15.png)

Once I export it, the lines in between the cells disappear, and the text overlaps, like this:
![image](https://user-images.githubusercontent.com/78889625/109735347-93b53200-7bfd-11eb-92d3-740079e814e0.png)
It gets worse if I have a lot of text in the cells, 
This is in Typora:
![image](https://user-images.githubusercontent.com/78889625/109735568-f27aab80-7bfd-11eb-980e-9e841517d765.png)

This is what it looks like in the exported pdf:
![image](https://user-images.githubusercontent.com/78889625/109735646-10e0a700-7bfe-11eb-8a95-ec40a39ead50.png)

This probably needs to be fixed in the next update, as, in my opinion, it makes tables unusable.

**Comment by abnerlee** [comment]
which theme did you use? Does this happen in built-in themes?

This looks like a CSS issue from the theme you use.

**Comment by ErickHoward** [comment]
>which theme did you use?

I'm using a customised version of the [Nord Theme](https://theme.typora.io/theme/Nord/)
>Does this happen in built-in themes?

No, this doesn't happen with built-in themes, though I can't find anything in the css that stops it from exporting the lines
