### ISSUE TITLE
Razor support for Code Block

### ISSUE THREAD

**Issue by yyw10242** [typora/typora-issues#4219]
I recently found there's no support for razor.
There's no highlights and so on.

![image](https://user-images.githubusercontent.com/4463238/109760492-1a840200-7c32-11eb-9ccc-e0a59735f849.png)
(as you see there's just plain code for razor.  only grey)
[codes from microsoft blazor docs.](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-5.0)

Is there extensions can i use or could you add this for newer updates?

**Comment by abnerlee** [comment]
put to #4318
