### ISSUE TITLE
left brace not work inline latex formula

### ISSUE THREAD

**Issue by selaselah** [typora/typora-issues#422]
all literal brace not work
```
$\{$
$\big\{$
```

**Comment by abnerlee** [comment]
is `\big\{` a valid expression in LaTeX?

**Comment by selaselah** [comment]
`\{` means literal left brace
`\big\{` means a big sized left brace
same latex in block formua will work.
```
$$
\big\{
$$
```

**Comment by abnerlee** [comment]
fixed in new release
