### ISSUE TITLE
URL encoding issue in file link

### ISSUE THREAD

**Issue by JackEggie** [typora/typora-issues#4220]
Platform: Windows 10 x64
Typora Version: 0.9.98

I have a PDF file to be referenced in an MD file by relative path. And the way of encoding the file path is different from Github, which I thought it's an issue of Typora.

Steps:

1. Have a pdf file with '&' in the file name.
2. Ref the pdf file in the md file in the same dir.
3. Replace the '&' with '%26' for URL encoding.

Result: The pdf file could not be touched by clicking the generated link in Typora. However, this link works well on the Github webpage. Typora will show a warning of this issue as follows. And by the way, clicking on the 'learn more' will make the Typora crushing.

![image](https://user-images.githubusercontent.com/8253572/109778853-44dcbc00-7c40-11eb-96f0-759a6f4ccd92.png)

**Comment by abnerlee** [comment]
fixed in new release
