### ISSUE TITLE
PDF export does not show an html image within a div

### ISSUE THREAD

**Issue by eliveikis** [typora/typora-issues#4221]
Windows Typora v0.9.95 and v0.9.98 (latest):
Image won't show in exported pdf, shows fine within typora:

```
<div width="5000" style="margin-bottom:30px"><img src="..\..\..\..\Marketing\Company Logo\logo.png" alt="drawing" style="position:absolute;bottom:-12px;" width="82"/><h1><span style="position:absolute;left:100px">Company Name</span></h1></div>
```

It looks like it is the div that introduces the bug. If I remove the div then the image shows in the pdf.

**Comment by abnerlee** [comment]
should be fixed

**Comment by abnerlee** [comment]
@eliveikis could you try 0.10.11, and if it persists, attach a test file.
