### ISSUE TITLE
LaTeX export adding extra blank lines when using an aligned enviroment within a gather enviroment

### ISSUE THREAD

**Issue by ndewy** [typora/typora-issues#4222]
- **Platform:** Windows 10 x64
- **Typora Version:** 0.9.98

When nesting aligned enviroments within a gather enviroment, the Typora exporter adds extra blank lines.

### Steps to reproduce
1. Write some TeX code in the below layout.
```
$$
\begin{gather*}
some math \equiv here \\
\begin{aligned}
aligned math &= abc \\ 
&= \alpha
\end{aligned} \\
unaligned math=12345
\end{gather*}
$$
```
2. Export  to a __.tex__ file and render to PDF using __TexWorks__/__MikTeX__ (other LaTeX versions untested).

### Results
The math block renders identically in both MathJax and LaTeX (once the spaces are removed). However, due to the spaces, the .tex file throws an error on compile.

**.tex file snippet, showing the extra lines added within the enviroment:**
```
\begin{gather*}

some math \equiv here \\

\begin{aligned}

aligned math &= abc \\ 

&= \alpha

\end{aligned} \\

unaligned math=12345

\end{gather*}
```

**Comment by ndewy** [comment]
I have found a semi-fix for my use case - my usage of LaTeX is a bit wonky. There is no need to use a __gather__ enviroment to wrap this unless I want mutliple numbered equations. This solves the Typora issues, and also works in plain Pandoc aswell.
This could be an issue in someones rare usecase, but I personally can work around it by using no __gather__ enviroment atall.

**Comment by abnerlee** [comment]
What's your exported tex look like, and what is your pandoc version?

In my test, it looks like:
```
```
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\author{}
\date{}

\begin{document}

\begin{gather*}
some math \equiv here \\
\begin{aligned}
aligned math &= abc \\ 
&= \alpha
\end{aligned} \\
unaligned math=12345
\end{gather*}

dewdewdwe

\end{document}
```

There no extra empty line inside it.
