### ISSUE TITLE
[Feature request] Ability to see two panels for visibility, speed at the same time

### ISSUE THREAD

**Issue by eriksdev1** [typora/typora-issues#4224]
Good day, I've been using Typora for a while and is an awesome program, my suggestion/feature request would be to be able to see something like this:    (image edited by me, not sure if possible), this would be for more visibility and faster access to the information tree/outline (seen both at the same time)

<a href="https://ibb.co/P5PqdB1"><img src="https://i.ibb.co/P5PqdB1/suggestion2panels.jpg" alt="suggestion2panels" border="0"></a>

**Comment by abnerlee** [comment]
#1243
