### ISSUE TITLE
Indented code blocks in source code mode not closed

### ISSUE THREAD

**Issue by yooksi** [typora/typora-issues#4226]
When indenting code blocks in lists they are not displayed as closed in `Source Code Mode`.

```
- Update copyright in `LICENSE.txt` to include the current year and your name:

	```
	Copyright (c) [year] [fullname]
	```

- Update copyright in `README.md` under 'License' section to include your name and (optionally) a link to your Github profile, personal website, or another place online you can be reached:

	```
	MIT © [Yourname](https://github.com/username)
	```
```

The example above will display like this in source code mode:

![2021-03-06_064248](https://user-images.githubusercontent.com/16436920/110196856-90ad8200-7e47-11eb-9c0d-3b9f0dc3b439.png)

**Comment by yooksi** [comment]
This issue does not occur when indenting code with 8 spaces (2 tabs) like this:

```
- This is a sample line.

        This is a sample code block

- This is another sample line.
```

**Comment by abnerlee** [comment]
#1638
