### ISSUE TITLE
How to delete files without mouse

### ISSUE THREAD

**Issue by zDEFz** [typora/typora-issues#4228]
See title. Is it possible? I couldn't figure how to move something to the trash without the mouse...
I expect all mouse actions to have a counterpart on the Keyboard. Please check this.

Thanks and best regards.

**Comment by zDEFz** [comment]
![image](https://user-images.githubusercontent.com/24463722/110333294-b7bfab80-8021-11eb-97c7-d8e29414a736.png)

Select entry via keyboard ... How is that possible?
pressing delete key -> Nothing happens

**Comment by abnerlee** [comment]
duplicate with #1001
