### ISSUE TITLE
windows上 多窗口合并的功能怎么使用呀？？？

### ISSUE THREAD

**Issue by YanMingUP** [typora/typora-issues#4230]
mac 上可以多窗口合并，windows上不知道怎么操作，求教

**Comment by abnerlee** [comment]
not supported yet -> #638

**Comment by YanMingUP** [comment]
> 目前尚不支持-> [＃638](https://github.com/typora/typora-issues/issues/638)

这个问题已经存在好几年了！！！  开发人员还不添加这个功能吗？ windows上添加这个功能十分困难吗？
