### ISSUE TITLE
Duplicate images png in my images directory 

### ISSUE THREAD

**Issue by phthom** [typora/typora-issues#4232]
Hello, 
I use Typora Version 0.9.9.19.4 (1355). I am in MacOS version 11.2.2.
It is working very well and I like it very much. 

One very interesting feature is to use the screenshot on the Mac and then paste it into your Typora document. In my case, it creates automatically a sub-directory called images (in the same directory where my MD document is) and populate this directory with PNG files. The problem is for one screenshot, I always have 2 pictures : image-20210309121107815-5288267.png  and   image-20210309121107815.png  for example.  I don't know why  ... I tried to find a parameter or a practice ... but I just specify ./images in my editor parameter ... and "Copy image to customer folder" ... Can you help me ?

**Comment by abnerlee** [comment]
The version 0.9.9.19.4 is too old, please upgrade.
