### ISSUE TITLE
Page-break-inside not working for tables when exporting PDF

### ISSUE THREAD

**Issue by alienhaw** [typora/typora-issues#4233]
When exporting to PDF there are large blanking before tables. Have already added custom base.user.css as below:

`@media print {
    table {
	page-break-inside: auto;
    }
}`

Not working. Tried several themes, same problem.
CSS, md and pdf files are attached.

[test.zip](https://github.com/typora/typora-issues/files/6116625/test.zip)

OS: MacOS 10.15.7
Version: 0.9.9.36.2
Theme: GitHub

**Comment by abnerlee** [comment]
Could you try export to HTML, open in safari and print to PDF?

I think it is not support by Webkit / Safari, and typora use it for PDF printing.

https://stackoverflow.com/questions/9288802/avoid-page-break-inside-row-of-table

**Comment by alienhaw** [comment]
> Could you try export to HTML, open in safari and print to PDF?
> 
> I think it is not support by Webkit / Safari, and typora use it for PDF printing.
> 
> https://stackoverflow.com/questions/9288802/avoid-page-break-inside-row-of-table

This way works but the bookmarks are lost...

**Comment by abnerlee** [comment]
> Thanks for the reply. This way works but the bookmarks are lost...

which solution did you pick in https://stackoverflow.com/questions/9288802/avoid-page-break-inside-row-of-table

**Comment by alienhaw** [comment]
> > Thanks for the reply. This way works but the bookmarks are lost...
> 
> which solution did you pick in https://stackoverflow.com/questions/9288802/avoid-page-break-inside-row-of-table

I exported to HTML and then print to PDF, as you suggested, with bookmarks lost. The solutions in the link are for HTML tables I think, while I want to use Markdown tables.
