### ISSUE TITLE
missing folder open arrows in file tree

### ISSUE THREAD

**Issue by scbarton** [typora/typora-issues#4236]
The UI arrows to open subfolders in the file tree are missing for me. Without these arrows I can't show contents of subfolders

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1451344/110939311-373fca00-8303-11eb-8056-159fb2902381.png">

I'm using Version 0.9.9.36.2 (4901). I've tried this on macOS 11.2.3 and Windows 10.

**Comment by scbarton** [comment]
An update:  If there is a *.md file in the subfolder, the arrows seem to appear, but if the folder is full of, say, images, no arrow.

**Comment by abnerlee** [comment]
#1753

We currently only display text files and folders.
