### ISSUE TITLE
CSS property 'zoom' is non-standard

### ISSUE THREAD

**Issue by Yannnd** [typora/typora-issues#4238]
Yes, if you also need to work under Firefox, you will have to specify the image width or height.

We currently does not have any better solution for this.

relates #2242

_Originally posted by @abnerlee in https://github.com/typora/typora-issues/issues/3876#issuecomment-706710851_

**Comment by Yannnd** [comment]
Of course you want to be compatible to the Firefox browser! After all FF is the only _really_ W3C compliant browser...

The property 'zoom' is a microsoft extension to CSS. The right way to scale an image should be 'transform: scale()'

**Comment by abnerlee** [comment]
I didn't know this until  #3876, but 'transform: scale()' is not a replacement, it will zoom the image, but will not change its layout, empty content will still occupy the image's original position, even when it is already zoomed.

Currently, there is no better ways to achieve this.
