### ISSUE TITLE
Better code block language selector idea

### ISSUE THREAD

**Issue by GoodIdea2020** [typora/typora-issues#4239]
When i wrote a programming code article , i will insert code block frequently  , but each time i have to select the same code language . I wrote a article about Javascript , each time i insert code block , i have to type "js" in code selector . Its better way to memory or cache the language "js" , then when i press Ctrl + Shift + K , it will insert a code block and auto selecting the "js" language ,  i can write js code suddenly after i insert the code block. We should let the editor remember our code blocking language temporarily , then we need not to choice code language each time when we insert a code block .

**Comment by AlexPasternak** [comment]
We're approaching the 5-year anniversary of me having originally proposed this, where it was closed as "Won't Fix": https://github.com/typora/typora-issues/issues/184 The follow-up for default language selection is still open, however, so there's still hope.

**Comment by abnerlee** [comment]
relates #1639

should be fix in #290
