### ISSUE TITLE
Can not drag down the window

### ISSUE THREAD

**Issue by towry** [typora/typora-issues#424]
<img width="587" alt="screen shot 2016-11-18 at 9 32 39 am" src="https://cloud.githubusercontent.com/assets/8279858/20415420/0121a336-ad73-11e6-8c58-73879058f4f2.png">

Sometimes after I opened a Typora window, it becomes this.

Version 0.9.9.8.2 (0.9.9.8.2)

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by towry** [comment]
Not fixed in the new version. @abnerlee 
Version 0.9.9.8.4 (0.9.9.8.4)

**Comment by abnerlee** [comment]
@towry Are you using multiple screens?

**Comment by towry** [comment]
@abnerlee Yes.

**Comment by abnerlee** [comment]
So, will the titlebar of Typora be displayed in another screen?

**Comment by towry** [comment]
@abnerlee No, the window can only be displayed in one screen, as far as I know, window can not appear in two screens at the same time.

**Comment by towry** [comment]
@abnerlee 

Steps to reproduce:

1. multiple screen.
2. Open a blank Typora window.
3. Menu -> File -> Open Recent, select a recent opened file.

**Comment by abnerlee** [comment]
Please reopen if this still happens in new version
