### ISSUE TITLE
Typora produces slightly thinner fonts than other text editors in macOS

### ISSUE THREAD

**Issue by chchen-stanford** [typora/typora-issues#4240]
This issue took me more than a month to nail down. I was wondering why I always wanted to use slightly lager fonts in Typora for long-term editing. For example, I am typically happy with 16px Avenir Roman, but will need to use 18px in Typora. After some testing, I found that Typora produces a slightly thinner font than other macOS text editors. 

You can reproduce the problem by:
(1) Type a sentence in TexEdit using Avenir Book and then Avenir Roman. Roman is slightly thicker than Book in terms of line stroke. 
(2) Type the same sentence in Typora using any of the default themes, e.g. newsprint. Set the font to Avenir Book or Avenir Roman. Stipulating "Avenir" in the font family produces the default Book weight, while "Avenir Roman" produces Roman weight. Capture screenshots for both cases. 
(3) Compare the TextEdit output against the screenshots from Typora. You will find that Avenir Book in TextEdit has essentially the same thickness as Avenir Roman in Typora. 

This slight shift in font weight is true for other built-in Typora themes. Typora consistently produces texts with a slightly thinner stroke. For each comparison, the text color in TextEdit was adjusted to match the Typora theme to avoid visual illusion. For a fair comparison, the font weight of the Gothic and Pixyll themes have been adjusted to normal/400.

This bug seems to affect all fonts. Another font that I tested is Noto Serif SC. Typora again produces a slightly thinner font. 

Just in case it's helpful for debugging: I have a MacBook Pro (15-inch, 2018) on macOS Big Sur 11.2.3.

**Comment by abnerlee** [comment]
What about text in Safari (https://stackoverflow.com/questions/9049524/safari-rendering-page-fonts-thinner-with-jquery-slider-on-page) ?

Does add following custom CSS help?
```css
html {
	-webkit-font-smoothing: subpixel-antialiased;
}
```

**Comment by chchen-stanford** [comment]
@abnerlee The additional code solves the problem. Now the font has the same weight as other macOS editors. Thank you!

In future updates, do you plan to implement this addition as the Typora default?

**Comment by abnerlee** [comment]
I see..

Does this also happens in Safari or in Typora's built-in themes? if so, it may relates to some global setting on your macOS. Typora don't do font smoothing (https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/), how text is rendered should be controlled by your OS.

> In future updates, do you plan to implement the subpixel antialiasing as the Typora default?
We don't have plans to take control of font smoothing, nor bring changes that breaks backward compatibility.

**Comment by chchen-stanford** [comment]
As I stated earlier, I have tested all six built-in themes. If susbpixel antialiasing is not explicitly declared, Typora will yield a thinner font. 

I do not know how to exactly answer your inquiry "does this happen in Safari". Here are some interesting observations.

I have been using Safari for a few years since Sierra. The fonts in Safari have been consistent from Sierra to Big Sur. Before Catalina, the "use font smoothing when available" option was selected in Systems Preference/General. Since then, it is whatever the system default. 

On my own website, for which I know the font used, I compared the Safari rendering and TextEdit. The font weight looks identical to me. Since TextEdit uses subpixel antialiasing, Safari must be using it too. 

When I export to html from Typora, the exported html is only antialiased, unless I declare subpixel specifically in my user css. I looked into the exported html, and saw this preamble which is nowhere to be found in the Typora theme (built-in Newsprint and my user css):
`html { font-size: 14px; background-color: var(--bg-color); color: var(--text-color); font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; }`
The conversion system is somehow adding "antialiased" as the default.

**Comment by irseq** [comment]
Hello, I've just noticed the same behavior as the author of the original issue did.

> > We don't have plans to take control of font smoothing, nor bring changes that breaks backward compatibility.

You say that you don't plan to take control of font smoothing, yet `-webkit-font-smoothing` is set to `antialiased` in the default themes. My understanding is that using `antialiased` is actually _taking control_ of font smoothing.

`auto` can be used instead, which makes font rendering uniform with the OS and other applications.

**Comment by CharlesButcher** [comment]
Thanks for this discussion. `-webkit-font-smoothing: auto;` works well for me, and I suggest it should be the default for Typora's supplied stylesheets. Previously I was messing around with `font-weight` and couldn't get a good result.
