### ISSUE TITLE
Question re file management - way to treat PDF and other file types like image assets

### ISSUE THREAD

**Issue by daeh** [typora/typora-issues#4241]
Apologies if this is covered somewhere, I wasn't able to find it. 

I'm a huge fan of the way Typora can copy images to a note-specific folder and link it with a relative reference. Is there a way to tigger this copy/link behavior for non-image attachments? 

E.g. If I want to attach a PDF or a Zip to a note, is there a way to tell Typora to copy the file to a custom folder and link it in the same way that an image would be?

And if not, is there a way to modify which file types considered images? Such that PDFs would always be treated like images?

Thanks for all your work on this amazing project.

**Comment by abnerlee** [comment]
More close to #2415
