### ISSUE TITLE
can't render math formula

### ISSUE THREAD

**Issue by chuck6** [typora/typora-issues#4242]
hi， my typora version is 0.9.98  .  I code  much paper about math, so i offten use math formula,  i found that I can't render the math formula. 
the math formula just show the origin code , like  $\psi$ , not render to match formula。 

i am sure that , i open the math options in typora,  and when i code a few words about math, it can be ok .

**Comment by abnerlee** [comment]
same with #4006?

Could you provide a screenshot?
