### ISSUE TITLE
Image load failed in Windows

### ISSUE THREAD

**Issue by alextoss** [typora/typora-issues#4243]
Hello,

Each time I add an image to a note, when I switch to another note and then switch back to the note with the image it fails to load it. If I add a space at the end of the line (after "/>") the image loads correctly but the issue comes back when I switch to another note.
It's really frustrating, can you please check ?

![image](https://user-images.githubusercontent.com/4669917/111140208-5d26d200-8582-11eb-84cf-c2491da471f3.png)

After adding a space at the end of each image line:
![image](https://user-images.githubusercontent.com/4669917/111140279-729bfc00-8582-11eb-81a9-e62cbfe4c7ca.png)

Alexandre M.

**Comment by alextoss** [comment]
Addendum:
- Images are all local
- OS Windows 10
- Typora 0.9.98

**Comment by maotuan333** [comment]
Hi! I'm having the same issue on macOS. 
If I just go on typing in the same file the image is gone after about a minute anyway. Or if I close/reopen the file or export to PDF images fail to load as well.

**Comment by whitecoffee** [comment]
I guess the reason is that you put your files under a folder named in Chinese.

**Comment by alextoss** [comment]
Does someone from Typora is currently working on the issue ?

**Comment by maotuan333** [comment]
> I guess the reason is that you put your files under a folder named in Chinese.

Hi whitecoffee,

Thank you for the feedback, but I think this is a bug on its own. The same problem occurs when file path does not contain any Chinese characters.

Here's a way to 100% trigger the bug on my device:
1. Drag image into file.
2. File > New.
3. Switch back to the previous file.

https://user-images.githubusercontent.com/80687346/113483117-61d10d00-94d4-11eb-973a-a2728cadc4c5.mov

**Comment by abnerlee** [comment]
Seems relates the "#" char in image path

**Comment by alextoss** [comment]
> Seems relates the "#" char in image path

I confirm thanks !
In the meantime I replaced "#" char of my folder by "-"

**Comment by zhuyuanxiang** [comment]
I have met this problem too.
The directory didn't have any Chinese character and any punctuation.
Environment:
Windows 7 Chinese edition
typora 0.10.1

**Comment by abnerlee** [comment]
fixed, please check update

**Comment by maotuan333** [comment]
Thanks abnerlee..!! It's working :)

**Comment by zhuyuanxiang** [comment]
Thanks abnerlee.... It is working now :)
