### ISSUE TITLE
Mermaid axis not visible on Night theme

### ISSUE THREAD

**Issue by dmelichar** [typora/typora-issues#4244]
Axis are not visible when the Night theme is active.

<img width="920" alt="github" src="https://user-images.githubusercontent.com/6791298/111191970-dfca8400-85b8-11eb-8035-f4527ecf4413.png">

<img width="920" alt="night" src="https://user-images.githubusercontent.com/6791298/111191975-e0fbb100-85b8-11eb-835e-695bcf151589.png">

**Comment by abnerlee** [comment]
should be fixed in latest version
