### ISSUE TITLE
Typora footnote enumeration not properly formatted

### ISSUE THREAD

**Issue by chchen-stanford** [typora/typora-issues#4245]
I have Typora version 0.9.9.36.2 and macOS Big Sur 11.2.3. When Typora renders footnotes, the superscripts in the main text look OK, but the enumeration in the footnotes is unformatted. I see "[^1], [^2] ..." in both the normal view mode and the source code mode. 

This "raw" rendering is contrary to the more appropriate rendering with just "1, 2 ..." in the footnotes, as suggested at the very bottom of the Typora support site: 
https://support.typora.io/Markdown-Reference/#footnotes
Like this website, similar footnote rendering is also adopted by other markdown editors like Atom. 

I ddi notice that "[", "^" and "]" are all grayed out, leaving the actual numbers emphasized, but I would rather not see them in the normal view. The raw enumeration of footnotes is quite distracting, and is affecting all Typora themes unless there is additional coding in the user css. Can you please fix it?

**Comment by abnerlee** [comment]
#2478

**Comment by chchen-stanford** [comment]
#2478 does not offer a direct solution to the formatting problem raised here.  

In case it's helpful to other users: the footnote rendering by the Hivacruz and Github Night themes appears better to me. The relevant section on footnotes can be easily modified and incorporated into a custom css.

**Comment by abnerlee** [comment]
I may misunderstand your issues.

If you want to hide  "[", "^" and "]", you can use css to hide them. It's a style preference issue.

**Comment by chchen-stanford** [comment]
Yes, that is what I want. Instead of 
**[^1]** Referene content
I would like to see
**1.** Reference content
In my opinion, "[^1]" is somewhat against the WYSIWYG spirit of Typora.

Can you please show how to hide  "[", "^" and "]"? I do not see an explicit code for them so it's hard for me to modify. (My css knowledge is quite limited.)

**Comment by chchen-stanford** [comment]
The following css code will create footnotes headed with square-bracketed numbers: [1], [2]... It works for most Typora themes. On rare occasions, the color/padding need to be adjusted. If the brackets are not needed, just use '' instead of '[' or ']' for content. 

`.md-def-footnote .md-def-name:before {
  content: '[';
  color: inherit;
}

.md-def-footnote .md-def-name:after {
  content: ']';
  color: inherit;
}

.md-def-footnote .md-def-name {
  padding-left: 6px;
  padding-right: 6px;
  background-color: inherit;
}`
