### ISSUE TITLE
How to save a picture copied from a website locally?

### ISSUE THREAD

**Issue by wajika** [typora/typora-issues#4247]
I copied an article from a website that contained pictures. When I pasted it on typora, I found that I only quoted the URL of the image. If the original article is deleted in the future, will I not be able to see the image on the local copy in the future? Can I save the copied pictures to local automatically?

I hope to be able to view the complete content permanently like MS word.

**Comment by abnerlee** [comment]
see https://support.typora.io/Images/#use-global-setting-for-image-insert-operations
