### ISSUE TITLE
Items outside of list also get indented on macOS

### ISSUE THREAD

**Issue by estella144** [typora/typora-issues#4253]
Hello. When typing a list in Typora 0.9.9.36.2, the items after the list also get indented. Like this:

<img width="752" alt="Screenshot 2021-03-20 at 20 59 14 364" src="https://user-images.githubusercontent.com/80313321/111885359-26581e00-89bf-11eb-9620-7035d8e6d4a7.png">

**Comment by rkd-me** [comment]
I think it's issue with theme more than engine.
I could not reproduce it with my theme:
![image](https://user-images.githubusercontent.com/12505857/112012161-3f7cde00-8b29-11eb-9c41-cd82aa00f614.png)

Could you share your markdown code? Maybe it's missing empty line after the last bullet point?

**Comment by abnerlee** [comment]
Would you share the md file (or send to <hi@typora.io>)?

**Comment by estella144** [comment]
[irc copy.txt](https://github.com/typora/typora-issues/files/6198908/irc.copy.txt)

**Comment by abnerlee** [comment]
I opened irc copy.txt, but the bug didn't happen. Can open the sample file reproduce this?

**Comment by estella144** [comment]
@abnerlee I can't upload .md's, so change the file extension from "txt" to "md".

**Comment by abnerlee** [comment]
Can open  irc copy.txt  reproduce this? It works fine on my PC

**Comment by estella144** [comment]
No, did you change the file extension first @abnerlee?

**Comment by abnerlee** [comment]
Could you try latest version, please? 

I'm not able to reproduce this on atest version
