### ISSUE TITLE
Mermaid errors / bug :(

### ISSUE THREAD

**Issue by Ejjaffe** [typora/typora-issues#4254]
# Bug 1: flowchart diagram subclass name trimming error
## code
```
flowchart TD
	subgraph client[client class]
	eeeeeeeeeeeeeeeeeeeeeeeeeee
	end
```
## screenshots:
![image](https://user-images.githubusercontent.com/38086802/111987659-dcb62300-8ae5-11eb-9969-76bed2f43608.png)
![image](https://user-images.githubusercontent.com/38086802/111988090-682fb400-8ae6-11eb-9494-d8a57cead129.png)

-------------------

# Bug 2: ER diagram property issues
## code
```
erDiagram
          classWithProps {
          	type name
          }
```
## screenshots
![image](https://user-images.githubusercontent.com/38086802/111987936-31599e00-8ae6-11eb-8a06-5fdc92dfcadd.png)
![image](https://user-images.githubusercontent.com/38086802/111987849-17b85680-8ae6-11eb-8d13-e788f91f041f.png)
# Notes
Tested output on [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor/). I believe these errors are probably related to an outdated version of mermaid.

**Comment by abnerlee** [comment]
What's your Typora version? I think it is already fixed in latest version.

**Comment by Ejjaffe** [comment]
My version is 0.9.98
