### ISSUE TITLE
Additional behaviour for asset folder and images when changing file name

### ISSUE THREAD

**Issue by rkd-me** [typora/typora-issues#4255]
Hello,

Recently i started using a feature to paste image to folder with a name of file `{filename.assets}`, this is great option for people like me, who likes to have everything organized, however i found few key improvements that could be done to make it even more appealing. 

- when we rename note (via Files pane) asset folder should have been renamed too and all paths changed in that file to match new directory
- when we move note to different directory (via Files pane) asset folder should move as well
- we should have option on File pane to hide directories with assets, because when we have lots of files in one directory there are tons of folders showing on the Pane along with them, there is solution for it to change view from `File view` to `Article view`, but it won't show directories that are not assets folder

I hope it's clear enough, 
Thanks

**Comment by abnerlee** [comment]
duplicate with #2084 #2198 and #1753
