### ISSUE TITLE
上传图片错误

### ISSUE THREAD

**Issue by githubwdy** [typora/typora-issues#4258]
![image](https://user-images.githubusercontent.com/66410329/112094417-2f6f0800-8bd6-11eb-9621-61b6832e1147.png)
![image](https://user-images.githubusercontent.com/66410329/112095580-b53f8300-8bd7-11eb-9264-b9f4a7c9fbf8.png)

**Comment by abnerlee** [comment]
There are [PicGo Error], and {"success": false} is returned from picgo
