### ISSUE TITLE
typora keeps re-rendering formula

### ISSUE THREAD

**Issue by Narukara** [typora/typora-issues#4259]
My typora version is 0.9.98. When I open a file with formula in it, typora sometimes keeps re-rendering these formula.
I'm not sure what will trigger this problem. But it often happens when I first open the file. And It seems that all my file with formula may trigger this.

https://user-images.githubusercontent.com/53737377/112115563-4a507500-8bf4-11eb-9a01-4655930337ae.mp4

**Comment by abnerlee** [comment]
relates #4006

Possible to send us <hi@typora.io> the sample file for test?

**Comment by Narukara** [comment]
Here is another example. All sample files have been sent.

https://user-images.githubusercontent.com/53737377/112256044-5e50b100-8c9e-11eb-87d1-e7d71ad80ea8.mp4

**Comment by abnerlee** [comment]
seems same with #4195

**Comment by abnerlee** [comment]
seems same with #4195
