### ISSUE TITLE
Inline Formula can't export properly as PDF and HTML when auto numbering math equations

### ISSUE THREAD

**Issue by GSUI5051** [typora/typora-issues#426]
I edit my work with $$...$$ math blocks and $...$ inline math formula in Typora 0.9.21
original code:

$$
\frac{x}{2\sigma^2}
$$

$$
\frac{dR}{dt}= yI-\mu R
$$

$$
\frac{1}{16}
$$

$$
\frac{a^2 +a+1}{b+1}
$$

$$
f(n)= \begin{cases}
n/2, & \text{if $n$ is even} \\\
3n+1, & \text{if $n$ is odd}
\end{cases}
$$

whoawhoawhoa$(a+123)/(b-234)$bigbigbig

jskcfhivuhelqwfacknknel$\frac{a+123}{b-234}$sdgsdfgkslfjlijeo

When I enable "Auto Numbering Math Equations" in "File"->"Preference", the inline math formula can't export properly as PDF in "formula test - issue-2.pdf" attached, but it works fine just like the file "formula test - issue.pdf" attached when I disable the option.
[formula test - issue-2.pdf](https://github.com/typora/typora-issues/files/601492/formula.test.-.issue-2.pdf)
[formula test - issue.pdf](https://github.com/typora/typora-issues/files/601494/formula.test.-.issue.pdf)

Thanks.

**Comment by GSUI5051** [comment]
the bug can be "fixed" by restart computer

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by GSUI5051** [comment]
I tested it at the end of yesterday(GMT+8), it's fixed in latest version.
