### ISSUE TITLE
image changes on zooming

### ISSUE THREAD

**Issue by Narukara** [typora/typora-issues#4260]
My typora version is 0.9.98. When I copy an image into typora and zoom it, it will turn into another image. Detailed steps are shown in the video.

https://user-images.githubusercontent.com/53737377/112119950-ca78d980-8bf8-11eb-98dd-7f884b9866e8.mp4

**Comment by LighghtEeloo** [comment]
Same problem happens on 0.9.98, Manjaro KDE 21.0.
Note that if any operation interrupts the second paste, i.e. type in a few words, the problem vanishes.

**Comment by abnerlee** [comment]
fixed in new release
