### ISSUE TITLE
能否回车确定代码块语言

### ISSUE THREAD

**Issue by liangjingkanji** [typora/typora-issues#4262]
以前是支持这种功能的, 挺方便的

https://user-images.githubusercontent.com/21078112/112246788-293c6280-8c8e-11eb-9952-39cf60d3e717.mov

**Comment by choya-lee** [comment]
输入语言名称把光标移走即可，不必下意识点回车

**Comment by liangjingkanji** [comment]
> 输入语言名称把光标移走即可，不必下意识点回车

问题是方向键移不走(不信你输入完成以后按住下方向键试试). 你得用鼠标. 多麻烦,  而且回车更符合肌肉记忆以前也是支持回车的

**Comment by abnerlee** [comment]
should be fixed
