### ISSUE TITLE
Hope typora can add shortcut commands. For example, use'/todo' to insert a checkbox. 

### ISSUE THREAD

**Issue by crowdn** [typora/typora-issues#4263]
Hope typora can add shortcut commands. For example, use'/todo' to insert a checkbox. Just like Notion. And you can customize the configuration 

![image](https://user-images.githubusercontent.com/33209857/112267484-7df0d500-8cb0-11eb-908b-4b84fe00b812.png)
![image](https://user-images.githubusercontent.com/33209857/112267476-7af5e480-8cb0-11eb-9d22-ced65012bbbb.png)

**Comment by abnerlee** [comment]
duplicate with #3478
