### ISSUE TITLE
Accessing filename and filepath in custom image upload command

### ISSUE THREAD

**Issue by dirkagterhuis** [typora/typora-issues#4264]
First of all, I love typora and it offers everything I need and value in a markdown editor!! I'm having trouble accessing the filename/path in a custom image upload command. 

I'm using Typora Version 0.9.9.36.2 (4901) running on a Mac with macOS Big Sur (11.2.3). 

As per [the documentation on uploading images](https://support.typora.io/Upload-Image/), I should be able to access the file name and file path of the markdown file I'm currently working on, when I want to use a custom command to upload images:

> You can use `${filename}` and `${filepath}` in your custom commands, they will be replace as the current markdown file name and current file path. For “untitled” files that have not been saved on your disk, they will be empty strings.

Use case: I don't actually want to upload files, but I want to place all images pasted into markdown files to a directory `.assets` if it exists up the filepath. If it doesn't exist, I want to create a directory in the same directory as the markdown file, called `{filename}.assets`. Therefore, I need to know the name and path of the markdown file I'm trying to paste the image into, inside of the bash script I'm using to achieve this. 

However, I'm having trouble accessing the variables `${filename}`and `${filepath}` . I've tried: 

- Passing them in the command explicitly, so in Preferences | Image | Command, providing `"path/to/script.sh" "$filename"`.
- Printing all variables passed into the script to a separate logfile using `echo "$@">> "$logfile";`or `echo "${filename}">> "$logfile";` This is a line in the bash script I'm using.  
- Printing all environment variables using `printenv` or `compgen -v`.

None of this provides me with the path or the name of the Markdown file from which I'm trying to 'upload' the image. All I get is empty strings. NB I'm working from a named file such as `TestImageUpload.md`, which I've opened in Typora. 

Am I doing something wrong in accessing the variables in the script?

**Comment by abnerlee** [comment]
Typora just replace those variables in the text you input in the `<input>` element where you put custom commands, they are not env variables and therefore cannot be used in external scripts directly.

Please use

```
"path/to/script.sh" "${filename}"
```

**Comment by dirkagterhuis** [comment]
Awesome, thanks @abnerlee , this works indeed, also for `"${filepath}"`. I now see that I have to 'unpack' them myself, as they're passed into the script as a command line parameter and indeed not as a directly accessible variable. Didn't know that.

Great, now I can get this to work!!
