### ISSUE TITLE
Delete ordered lists

### ISSUE THREAD

**Issue by Higurashi-kagome** [typora/typora-issues#4266]
OS: Win10

Version: 0.9.98

----

When trying to delete ordered lists by `Ctrl + x`：

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/112434937-0d64b980-8d7f-11eb-8ef6-18bf198504c9.gif)

</details>

As we can see, the first number of the list still here. It might be better to delete it.

**Comment by abnerlee** [comment]
duplicate with #2357
