### ISSUE TITLE
Opening new window in Gnome re-opens already open file

### ISSUE THREAD

**Issue by andypillip** [typora/typora-issues#4269]
When opening a new Window on the Gnome Desktop, Typora will either open the last opened document, even if it's currently open on another Workspace, or open a second window along with it.

I installed the [Flatpak version of Typora](https://flathub.org/apps/details/io.typora.Typora) 0.9.98 (beta) on Fedora 33, Gnome 3.38.4.

**Comment by abnerlee** [comment]
Does this happen for the binary version on https://support.typora.io/Typora-on-Linux/?

**Comment by andypillip** [comment]
Apparently Flatpak applications need to get started differently, so this one has it's own .desktop file.
I reported the issue over there https://github.com/flathub/io.typora.Typora/issues/2

I did record a screencast in webm, but github doesn't allow that format and converting fails for some reason. ):
