### ISSUE TITLE
Slash in path for images

### ISSUE THREAD

**Issue by cawoodm** [typora/typora-issues#427]
Just dragged an image into Typora (Windows) and it displayed correctly `(docs\images.png)`. 
However when I uploaded my markdown to github the image was not displayed.
It could be that `\i` was considered an escape sequence.
The fix was to use a forward slash and my suggestion is Typora does this by default even on Windows. `(docs/image.png)`.

PS: Feedback button under Help does nothing.

**Comment by somax** [comment]
+1

**Comment by abnerlee** [comment]
fixed in new release
