### ISSUE TITLE
Export to HTML (without styles) using newline (probably \n) instead or <br> for line breaks

### ISSUE THREAD

**Issue by Edward-Castle** [typora/typora-issues#4270]
When you Shift+Enter, a new line is added in the same paragraph. That work as intended.

However, when exporting without styles, instead of converting it to <br/>, it's added as some character, probably \n which is wrong. The newline is lost and can't be seen.

**Comment by abnerlee** [comment]
How "\n" is rendered depends on your style. You could use following style to make it rendered as line break.

```css
#write {
 white-space:pre-line;
}
```

**Comment by Edward-Castle** [comment]
But good sir, I export without styles because I want pure HTML, specifically to avoid styles. Did I understand wrong what HTML (without styles) mean? If so, please let me know what I should expect from this function ^^

Also, I can convert \n to `<br/>` using Notepad++ well enough, I just thought it weird for an "export to HTML without styles" function to not actually convert \n to the HTML equivalent (which is `<br/>`). But if I understood the function wrong, please ignore me.

Thanks for the quick reply btw ^^

**Comment by abnerlee** [comment]
In html, "\n" is content, render "\n" as line break or as whitespace is style
