### ISSUE TITLE
Drag & Drop does not work on MacOS

### ISSUE THREAD

**Issue by marc-shapiro** [typora/typora-issues#4271]
Standard Drag&Drop of text does not work on MacOS.  

Drag&drop: select text, position mouse on selection, click down without moving mouse until the cursor changes shape to an arrow, move mouse.  This shows a shadow of the selected text, which you can drop elsewhere.

In Typora (version 0.9.9.3.6), instead, the cursor does not change shape, and moving it extends the selection.

**Comment by abnerlee** [comment]
duplicate with #827
