### ISSUE TITLE
Mis-spelled text is not underlined in MacOS

### ISSUE THREAD

**Issue by marc-shapiro** [typora/typora-issues#4272]
In text editors on MacOS, mis-spelled text is underlined with red dots.  Not in Typora (0.9.9.36.2).

In contrast, spelling correction does work, i.e., a right-click on the mis-spelled word does propose correct spelling.

**Comment by abnerlee** [comment]
Did you enable spell check? which you can see from edit menu

**Comment by marc-shapiro** [comment]
Thanks.  I was not aware of that.  You can close the issue

**Comment by marc-shapiro** [comment]
Thanks.  I was not aware of that.  I am closing the issue.

			Marc
