### ISSUE TITLE
Keyboard Shortcut Mesh-up

### ISSUE THREAD

**Issue by Muragavino** [typora/typora-issues#4273]
Hi everybody! 

I love Typora and I use it contemporarily on several PCs (all with Linux Mint). But, there is an interesting little problem with the keyboard: 

- I use 1 laptop with a **German** keyboard, 
- 1 laptop with a **Danish** keyboard 
- and a desktop PC with a **Portuguese** keyboard (yes, I know, its weird).

When typing text, every keyboard works as expected. But when using shortcuts, the shortcuts seem to refer all to an (american?) keyboard layout that does not match my local keyboard layout.

For instance: on the German keyboard shortcut **Ctrl+<** triggers the original  "Clear Format Ctrl+\\" command. If I press **Ctrl+\\** nothing happens. 

If I remember correctly, the keycode for  ` \ `  on an US keyboard is the same as  ` < `  on the German keyboard. The same mesh-up happens for other keys as well.

Can that be fixed please?

**Comment by abnerlee** [comment]
relates #3557

**Comment by abnerlee** [comment]
Please use https://support.typora.io/Shortcut-Keys/ to custom shortcut keys
