### ISSUE TITLE
Mermaid ClassDiagram duplicated in MS Word Export

### ISSUE THREAD

**Issue by horngyih** [typora/typora-issues#4275]
I have recently authored a document with multiple mermaid classDiagrams, but when it is exported to MS Word, the classDiagrams are duplicated ( and sometimes the duplicate overwrites other classDiagrams ).

Eg the following is the expected logical lay out in Markdown....

# Header 1

## Header 2
section text
[ mermaid classDiagram 1 ]

### Header 3
[ mermaid classDiagram 2 ]

## Header 2
section text

### Header 3
[ mermaid classDiagram 4 ]

### Header 3
[ mermaid classDiagram 5 ]

however, when it is exported to MS Word Document..... the following is the logical layout produced...

# Header 1

## Header 2
section text
[ mermaid classDiagram 1 ]

### Header 3
[ mermaid classDiagram 2 ]

## Header 2
section text

### Header 3
[ mermaid classDiagram 2 ]

### Header 3
[ mermaid classDiagram 2 ]

Anyone is encountering this issue?

**Comment by abnerlee** [comment]
Could you provide a sample md file (or send to <ho@typora.io>)

**Comment by horngyih** [comment]
# test

```mermaid
classDiagram

class Product {
	int ProductID
	String ProductCode
	String Status
}

class ProductDesc {
	int ProductID
	String Name
	String Description
	String LanguageCode
}

Product "1" --> "Many" ProductDesc : ProductID
```

## Test 2

```mermaid
classDiagram

class Product {
	int ProductID
	String ProductCode
	...
	String ProductGroupCode
}

class CodeValue {
	int CodeValueID
	int CodeTypeID
	String CodeValueCode
}

class CodeType {
	int CodeTypeID
	String CodeTypeCode
}

Product --> CodeValue : ProductGroupCode
CodeValue --> CodeType: CodeTypeID
```

### Test 3

```mermaid
classDiagram

class CodeValue {
	int CodeValueID
	String CodeValueCode
}

class ProductGroup {
	int ProductGroupID
	String ProductGroupCode
	String Status
}

class ProductGroupDesc {
	int ProductGroupID
	String Name
	String Description
	String LanguageCode
}

ProductGroup --> ProductGroupDesc : ProductGroupID
ProductGroup --> CodeValue : CodeValueCode
```

This is a test MD.....

**Comment by horngyih** [comment]
Exported Word Doc..... instead of having three distinct Class Diagrams.....
the Third Class Diagram is a duplicate of the Second Class Diagram.
[test.docx](https://github.com/typora/typora-issues/files/6244295/test.docx)

**Comment by abnerlee** [comment]
fixed in new release
