### ISSUE TITLE
Block elements in lists are not appearing in PDF exports

### ISSUE THREAD

**Issue by wlabarron** [typora/typora-issues#4276]
Typora 0.9.9.36.2 (4901), macOS 11.2.3 (Intel).

When exporting a document containing "block" elements like code blocks and LaTeX maths blocks which are on the first line of a list element, the list ordinal is missing.

Here is an example document (although the triple-backticks in list item 5 have had spaces added so that it appears correctly on GitHub).
```
# PDF Export Demo

1. List item 1.

2. List item 2.

3. $$
   \text{A } \LaTeX \text{ block is list item number 3.}
   $$

4. $\text{An inline } \LaTeX \text{ block is item 4.}$

5. ` ` `
   A code block is item 5.
   ` ` `

6. `Inline code is item 6.`
```

In Typora, the document displays as you'd expect:
<img width="828" alt="Screenshot of a Typora window showing the above Markdown, rendered correctly with all list numbers." src="https://user-images.githubusercontent.com/16035785/112862853-1bcc1180-90ae-11eb-826a-e7d17b6e33e1.png">

When exporting to PDF, the numbers for the list items with block elements are missing:
<img width="1194" alt="Screenshot of Preview showing a PDF export of the document. The list numbers 3 and 4 are missing, but the content is there." src="https://user-images.githubusercontent.com/16035785/112862957-3b633a00-90ae-11eb-8cbf-7b873906acdb.png">

I can't see any settings which could be interfering -- is there anything I should try for troubleshooting this?

**Comment by abnerlee** [comment]
fixed in new release
