### ISSUE TITLE
Latex rendering mode (size problem)

### ISSUE THREAD

**Issue by L1szt** [typora/typora-issues#4277]
When writing inline latex code with $$, the symbols appear quite small. How can I change the inline mode to take the same size as when I type latex code into $$ $$ (double dollar sign), since there the normal size appears? I also notices that this only applies to certain symbols, e.g. for the sum symbol:
<img width="147" alt="Screenshot 2021-03-30 at 17 58 29" src="https://user-images.githubusercontent.com/77193069/113019238-a92c6600-9181-11eb-88c3-1fcec8f1d63c.png">
The first is $$ and the second one $$ $$ and I want everything it too look like the second one.

**Comment by Herasselbach** [comment]
I'm having the same issue, I don't know whether a solution exists, but it would be interesting to know.

**Comment by Jeffrey-kerson** [comment]
Have you tried to change the latex size in your css file? Unfortunately this increases the overall size of your Latex source so equations in $$ $$ will appear extra large.

**Comment by L1szt** [comment]
> Have you tried to change the latex size in your css file? Unfortunately this increases the overall size of your Latex source so equations in $$ $$ will appear extra large, but it might be a partial solution.

I have already set the MathJax size to 110%, normal equations are totally fine but inline equations are still to small and if I increase it further, this will result in way to large $$ $$ equations, as you mentioned

**Comment by abnerlee** [comment]
$$ is inline math, $$ $$ is block math but displayed in inline mode...

Currently inline math uses current text font size, so we do not have plans to change it

you can see #3475 for duplication

Also relates #3278
