### ISSUE TITLE
Simple Flow Rendering Halts without Error Message

### ISSUE THREAD

**Issue by cawoodm** [typora/typora-issues#428]
Typora won't render this simple flow correctly (though stackedit.io can):

```
step_A1=>start: ReadFile
step_B1=>operation: Data2JSON
step_C1=>operation: SelectFields
step_D1=>end: FilterData

step_A1->step_B1->step_C1->step_D1
```

![capture](https://cloud.githubusercontent.com/assets/498834/20521313/f2284b88-b0aa-11e6-8d19-e720470fe8c6.PNG)

**Comment by abnerlee** [comment]
You don't need to add "```flow" in the code block.

All texts inside the code block is the content wrapped by "```" synatx
