### ISSUE TITLE
Relative path problem of copying pictures

### ISSUE THREAD

**Issue by luluxiaoyu** [typora/typora-issues#4281]
Relative path problem of copying pictures
When I copy the picture into the document
The path of markdown encoding is: xxx.accets/xxx.png
Cause the reference resource cannot be recognized when vuepress is compiled
Need to change the path to: ./xxx.accets/xxx.png

**Comment by abnerlee** [comment]
merge into #2415

xxx.accets/xxx.png and ./xxx.accets/xxx.png are both valid relative path
