### ISSUE TITLE
How to insert second-level unordered list without first-level one

### ISSUE THREAD

**Issue by Free-Dreamer** [typora/typora-issues#4283]
Hi, I want to know whether Typora can insert unordered list in a more free mode, i.e., the level of unordered list do not depends on the former list.
Just like this:
![image](https://user-images.githubusercontent.com/78793832/113504485-f38b5980-956a-11eb-8a82-303888ae0ae3.png)
Thanks!

**Comment by abnerlee** [comment]
It is not supported by markdown
