### ISSUE TITLE
Styling HTML elements with theme classes

### ISSUE THREAD

**Issue by stur86** [typora/typora-issues#4286]
Something like this was brought up in #2442 but to my knowledge never addressed. If one defines inline HTML elements and styles them with `style`, it works just fine. Doing so with custom classes defined in the theme's CSS file however does not show up in the preview. The effects are seen however when one exports the file to HTML. Is there any way to address this?

**Comment by abnerlee** [comment]
Typora cannot "preview" css `class`, which is mentioned in #2442 and related doc.
When export, it is just normal markdown → HTML export.
