### ISSUE TITLE
typora 0.9.98 could not detect pandoc on Archlinux

### ISSUE THREAD

**Issue by hebrewsnabla** [typora/typora-issues#4287]
typora and pandoc used to work well on my Archlinux, which were installed from pacman. When I switch my pandoc to the one (version 2.13) installed from cabal, a haskell package manager, it could not be detected by typora, although I've reinstalled typora and rebooted.
I'm sure the executable `pandoc` is in my PATH. I can access it via command line. But it's located in `~/.cabal/bin`, maybe a reason for the detection failure.

**Comment by abnerlee** [comment]
duplicate with #1169
