### ISSUE TITLE
Suggestion: Change Typora UI

### ISSUE THREAD

**Issue by ChrisDev8** [typora/typora-issues#4288]
My suggestion is to have 2 modes, one for the original typora view and another mode. This mode or view will have two panels, one for the source code and another for the preview. The preview panel will update live and can be split horizontally or vertically. I also think there should be a small bar at the top to insert elements like links, lists, tables, bold, etc. Just like Microsoft word. The preferences window should be styled better and more modern. There need to be 2 default themes. One that is not completely black but more like `#444444` and a white theme that is not completely white but more like `#dddddd`. Here is a color scheme I created for both dark theme and light theme.

![colors](https://user-images.githubusercontent.com/70666342/113609621-01e47e80-961a-11eb-8bd7-cc20fab1585a.png)

**Comment by abnerlee** [comment]
#3709

**Comment by ChrisDev8** [comment]
This is different, not only that but add default dark / light theme and have the bar at the top to insert bold, italic, links, images, etc.
😢😥😭
