### ISSUE TITLE
Menus flash white when mouse hovers over them (or clicks)

### ISSUE THREAD

**Issue by AmandaBSobrinho** [typora/typora-issues#4289]
Typora 0.9.98
Ubuntu 18.04.5 LTS

Whenever I hover or click on the menus, before the list of options shows up, there is a white flash on the menu space (video below). I tried changing Typora themes, but the issue persists.

https://user-images.githubusercontent.com/16309667/113803447-f46ee780-9732-11eb-8ec8-52978ed0b938.mp4

**Comment by abnerlee** [comment]
https://github.com/electron/electron/issues/18184

**Comment by abnerlee** [comment]
4289
