### ISSUE TITLE
Support for Latex cross references

### ISSUE THREAD

**Issue by henrikstroem** [typora/typora-issues#429]
Pandoc automatically generates labels for cross-references, e.g. if you have a heading:

`# Analysis`

you can reference that label from your text as `\ref{Analysis}` using Latex, and this can be mixed with Markdown. Also, in Latex it is possible to insert your own labels like `\label{Requirement Specification}`.

It would be a huge plus if this was supported in Typora.

**Comment by abnerlee** [comment]
reference in LaTeX is supported.

For further cross reference syntax support, see https://github.com/typora/typora-issues/issues/483 and https://github.com/typora/typora-issues/issues/191
