### ISSUE TITLE
How to change the Windows 10 Start Menu tile color of Typora?

### ISSUE THREAD

**Issue by datafj** [typora/typora-issues#4292]
Typora shows an unique dark background color on Windows 10 Start Menu. It makes it different from all the other icons. However, it is not what I like. I want all the tiles on the Windows 10 Start Menu have the same background color.

Strangely, unlike other apps, Typora seems do not use a "*.visualelementsmanifest.xml" file to define its background color. Changing the application icon does not help either. Tried [TileIconifier](https://github.com/Jonno12345/TileIconifier), can change the icon, but not the background color.

Is there a way to remove the unique background color of Windows 10 Start Menu tile of Typora? Thanks!

**Comment by abnerlee** [comment]
We should add a visualelementsmanifest file.

Before our fix, if you want some hot fix, you can add one Typora.VisualElementsManifest.xml next to Typora.exe

**Comment by datafj** [comment]
Somehow visualelementsmanifest file has no effect on one of my Windows machines.

I also noticed under "C:\Program Files\Typora\resources\app\asserts\icon", there is no 70x70 or 150x150 icons, which are used in visualelementsmanifest files. By the way, maybe "asserts" is the typo of "assets"?

**Comment by abnerlee** [comment]
the manifest file is added in new release
