### ISSUE TITLE
Emoji, Unicode character and LaTex

### ISSUE THREAD

**Issue by gbegin** [typora/typora-issues#4293]
I have a table where I use the emoji :heavy_check_mark:, which is rendered correctly in Typora and also when I export **directly** to pdf. But when I export to Latex first, :heavy_check_mark: is replaced by the Unicode Character “✔” (U+2714), and then when I  compile the Latex file, I get a Package inputenc Error: Unicode char ✔ (U+2714) error.

Typora version 0.9.98 (beta) on Ubuntu 18.04
pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)

**Comment by abnerlee** [comment]
You need to do something to compile latex file with unicode inside it.

like https://stackoverflow.com/questions/18178084/pandoc-and-foreign-characters or https://tex.stackexchange.com/questions/34604/entering-unicode-characters-in-latex
