### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by adilsaribay** [typora/typora-issues#4294]
I receive the following installation error in Windows 10 even when running the installation as administrator.  

![Screenshot (1)](https://user-images.githubusercontent.com/39433963/113988105-c33c0780-9857-11eb-8345-775c78f037b8.png)
Er

**Comment by abnerlee** [comment]
Is the file being opened?

Could you try exit all typora process, make sure the file is not opened, or just manually remove the typora folder
