### ISSUE TITLE
Automatically add a new line when inserting a block math

### ISSUE THREAD

**Issue by tristone13th** [typora/typora-issues#4296]
When typing '$$' in a new line, Typora will recognize it as a block math and center it. But the default markdown parser of Jekyll, kramdown, will recognize it as inline math because a math block in kramdown needs to start and end on [block boundaries](https://kramdown.gettalong.org/syntax.html#block-boundaries), see [Syntax | kramdown](https://kramdown.gettalong.org/syntax.html#math-blocks). So it will be more convenient if Typora adds a new line when typing '$$'.

**Comment by abnerlee** [comment]
> So it will be more convenient if Typora adds a new line when typing '$$'.

You could input $$ and return key, is this what you expected?

relates #63

**Comment by tristone13th** [comment]
> > So it will be more convenient if Typora adds a new line when typing '$$'.
> 
> You could input $$ and return key, is this what you expected?
> 
> relates #63

When pressing the return/enter key, it will show a new math block to type equations, but it won't add a new blank line in the source code, so it would be better if it can add a new line before and after the math code "$$...$$" to form a "block boundary".

**Comment by abnerlee** [comment]
> When pressing the return/enter key, it will show a new math block to type equations, but it won't add a new blank line in the source code, so it would be better if it can add a new line before and after the math code "$$...$$" to form a "block boundary".

Then should be #1107 instead
