### ISSUE TITLE
Cannot find Typora menu on fresh installation

### ISSUE THREAD

**Issue by LemuelPuglisi** [typora/typora-issues#4297]
First of all, I use Typora since last year and I think it's great, so congrats guys for your work. I've installed today Typora in another PC with Ubuntu and I just can't find the upper menu. I don't know if it's an installation problem nor if it's just hidden in the new releases. Can you guys help me out?

![image](https://user-images.githubusercontent.com/42694683/114178066-7c284200-993d-11eb-85d6-e4d3e3065315.png)

**Comment by abnerlee** [comment]
In my memory, menus in ubuntu are in top bar like
![image](https://user-images.githubusercontent.com/1621242/114581885-ab7ade00-9cb2-11eb-9060-6cabaaf50bc3.png)

---
Also you may hide the menu by accident somehow, did pressing "Alt" making it back?
---
And possible to provide the content of advanced setting (you can get from Preferences Panel → General → Open advanced setting).
---
And how did you install typora, from `apt-get` ?

**Comment by LemuelPuglisi** [comment]
My bad... I accidentally have hidden the menu bar and I took it back pressing 'Alt'. Thank you!!
