### ISSUE TITLE
[Missing feature] Use F5 or some other shortcut key for page refresh

### ISSUE THREAD

**Issue by codewizard13** [typora/typora-issues#4298]
Loving Typora. It appears to be built on some browser (like Chromium) framework. But, I can't seem to find a "refresh" option anywhere. A _**Refresh Page**_ function would provide a better user experience for customizers like myself who, upon changing some custom CSS, would then be able to easily see the results of our changes, without having to close out of the app and restart it.

Just curious: Is this feature already in Typora and I'm just missing it?

**Comment by abnerlee** [comment]
We don't plan for this since change css is very rare case.
