### ISSUE TITLE
General support for Latex

### ISSUE THREAD

**Issue by henrikstroem** [typora/typora-issues#430]
General support for Latex would be a huge plus.

I can insert Latex code in the Math system in Typora, but many things don't work, e.g. if you insert something like:

`\Huge{Hello, World}
\\
\Large{How are you today?}`

It will get messed up, and yes, I realize the function was not designed for this, but it *almost* work as it is.

**Comment by abnerlee** [comment]
The LaTeX here is basically for scientific writing, like writing math expressions, not for typesetting.

You could still wrap the LaTeX code with "$" char, for instance.

`$\Huge{Hello, World} \\ \Large{How are you today?}$`

to render some LaTeX expressions in Typora.
