### ISSUE TITLE
mathjax internal buffer size exceeded: how to fix it in typora?

### ISSUE THREAD

**Issue by rm144** [typora/typora-issues#4300]
I have very long equations and get a red error message in typora saying

`"MathJax internal buffer size exceeded; is there a recursive macro call?"`

According to https://github.com/mathjax/MathJax/issues/910 this can be fixed in the ipython tool by the python instruction

`MathJax.Hub.Config({TeX: {MAXBUFFER: 25600});`

How can I achieve the same in typora? Is there a configuration file where I could configure the buffer size, or is there a way to put some configuration directive directly into the markdown document?

Thanks a lot for your help!

(I'm using Typora on Ubuntu Linux)

**Comment by abnerlee** [comment]
Possible to provide the sample equations? Need to check if it affects performance or not.

**Comment by rm144** [comment]
Here is an example. In `ttest.md`, the entire equation is in a single math/align environment; this causes the error message. In `ttest_split.md`, it was split into multiple math/align environments to show that the math code itself is valid; no error occurs. Thanks for your help! 

[ttest.md](https://github.com/typora/typora-issues/files/6308270/ttest.md)
[ttest_split.md](https://github.com/typora/typora-issues/files/6308271/ttest_split.md)

**Comment by abnerlee** [comment]
We increased the default MAXBUFFER, but we do not have plans to put an option for it.
