### ISSUE TITLE
BUG: cursor jump to the top wrongly

### ISSUE THREAD

**Issue by Narukara** [typora/typora-issues#4301]
When the cursor goes up (use only ⬆️ key) and crosses an image (**in < img > form**) followed by a formula (not inline), it will jump to the top wrongly. 

By the way, I notice that the cursor will disappear on the image temporarily when doing this.

Typora version 0.9.98 (beta) on Windows 10

https://user-images.githubusercontent.com/53737377/114297308-6bfd9780-9ae2-11eb-9a60-0b2d96e5b66b.mp4

here is the example:

[example.zip](https://github.com/typora/typora-issues/files/6291388/example.zip)

**Comment by LighghtEeloo** [comment]
Confirmed on Manjaro KDE 21.0.1 with Typora 0.9.98 (beta).

**Comment by abnerlee** [comment]
fixed in new release
