### ISSUE TITLE
How to add shortcut keymap?

### ISSUE THREAD

**Issue by xiaoqixian** [typora/typora-issues#4302]
I want a shortcut that is able to insert a simple html block in both ends of several words, like `<font color=red>`, is there anyway to do that?

**Comment by abnerlee** [comment]
duplicate with #3021 or #3624

**Comment by abnerlee** [comment]
For now, you can use apps like TextExpander, or, if you're macOS user, you can set text shortcut in system preferences panel -> keyboard
