### ISSUE TITLE
inserted images (and other local hyperlinks) should be stored with relative path 

### ISSUE THREAD

**Issue by getreu** [typora/typora-issues#4306]
### Description

Embedded an images are stored by default with an absolute path to the image file. This leads to broken links when the document folder with its images gets moved.

### Suggested solution

Always store local links with relative path.

**Comment by abnerlee** [comment]
images are already supported, other resources is addressed in #2415

**Comment by getreu** [comment]
???
When you drag and drop an image into your document, it save the path as absolute path. This will cause trouble later when you move the document with inline images into another folder.
This is why I suggest to always store the path as relative path.

**Comment by abnerlee** [comment]
https://support.typora.io/Images/#use-relative-path

**Comment by getreu** [comment]
Yes, thank you for the link to the doc. Please consider to make it
default. I guess most people keep their inline images close the
text file. There are only a very few use cases where absolute links
make sense.
