### ISSUE TITLE
[Windows] Inline MathJax is not rendered

### ISSUE THREAD

**Issue by silas229** [typora/typora-issues#4309]
Hi, since today I have the strange problem that Inline MathJax is not rendered anymore. I have the latest version (0.9.98 beta). The problem was not 2 days ago and I did not update consciously (it is already released in December). 
![image](https://user-images.githubusercontent.com/23215125/114761315-98bee280-9d60-11eb-83a7-9692f98964ca.png)
The problem is not only, as here in tables, but also in continuous text. Large formula blocks still work. In addition, since then the Menu Bar is the only element dark, because I use Windows in Dark Mode. Before it was light.

**Comment by abnerlee** [comment]
#3242

**Comment by silas229** [comment]
Okay, apparently all my settings were reset. How could this just happen like that?

**Comment by abnerlee** [comment]
> Okay, apparently all my settings were reset. How could this just happen like that?

Did you upgrade or what operation did you do before this happens?

**Comment by silas229** [comment]
No. From one day to the next, the entire config was suddenly gone.
