### ISSUE TITLE
feature request: automatically adding `\end{...}` in a LaTeX block

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#4312]
Typora currently knows that if you type some HTML tag, then text, and then you start typing `</` it autocompletes the open tag for you. In that same vein, it would be great if it knew what to do while in a LaTeX block, where the equivalent of matched tags is matched `\begin{...}` and `\end{...}` strings.

It would be great if Typora tracked which environment it is in (identical logic as for HTML tags), and would automatically fill in "the rest" when you type `\end{`:

1. user types `\begin{aligned}`
2. user writes some text
3. user starts writing `\end`
4. when typora sees the user completing that to `\end{`, it adds `<current env name>` + `}`

Alternatively, it might be even more useful to follow the same logic that happens when they user types `$$`: this starts a block with the ending `$$` already added, so we could use the same pattern:

1. user types `$$`, Typora starts a new LaTeX block
2. user types `\begin{aligned}`
3. Typora automatically adds an empty line, and then `\end{aligned}` on the line after that empty line, placing the cursor on the empty line for the user.

The second implementation would be distinctly superior, but the first is still by far better than having no autocompletion for matched "tags".

**Comment by abnerlee** [comment]
#2988

**Comment by Pomax** [comment]
That's a _way_ more generic issue than this one, though: I'm just requesting `end` autocompletion, because that's something that someone working on the code should be able to do in an hour or two.

Unlike "full autocomplete for LaTeX", which is a huge epic and no one would be able to get done even with a full week available to them.

**Comment by abnerlee** [comment]
Currently there's no autocomplete at all. 

So I think it can be covered by #2988
