### ISSUE TITLE
feature request: add support for the *actual* LaTeX block markers (\[...\]) rather than 

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#4313]
TeX and LaTeX are _very different_ things, and LaTeX is to TeX what C++ is to assembly language: TeX is an extremely low level macro-expansion-based programming language that no actually uses (except for package developers who want to create new commands that run as fast as possible), with LaTeX being the actually human-understandable markup language built on top of it, actually making sense to people reading and writing it.

However, there are some things that TeX does that LaTeX can't turn off, and so one of the things is the maths mode gets triggered. However, LaTeX went "this might still work, but you should not use it", and so we have a situation where the LaTeX way to trigger maths mode is by using `\[` and `\]` to indicate a block of maths, whereas TeX uses `$$` both as start and end "tag", and both work, but crucially _no one should be using `$$` in LaTeX_.

MathJax thankfully supports both, mostly because it has to, so at the very least Typora should support `\[` as maths opener and `\]` as closer, as all proper LaTeX that folks might write actually uses that (the other option is that they might use `\begin{displaymath}` but given that `\[` is a straight up alias for that, no one actually uses the full form if they're writing LaTeX).

So: can Typora please be updated so that the LaTeX block actually uses LaTeX block opener/closers in addition to the "you should never use this" `$$` block switch?

For further information on this, see:

- https://tex.stackexchange.com/questions/503/why-is-preferable-to
- https://tex.stackexchange.com/questions/410863/what-are-the-differences-between-and
- https://tex.stackexchange.com/questions/40492/what-are-the-differences-between-align-equation-and-displaymath

**Comment by abnerlee** [comment]
#63

**Comment by Pomax** [comment]
@abnerlee that's from 2016 with zero actual code activity on it: is it just an ice box issue that no one looks at? Four years is kind of a ridiculous amount of time to be sticking around to fix what is literally a bug: if Typora supports LaTeX, it's currently doing maths mode _wrong_, because LaTeX maths mode _does not use $$_ =)

**Comment by abnerlee** [comment]
Well, if it is LaTeX editor, then it is definitely wrong. For a markdown editor, it is just acceptable ways to extend the markdown syntax and support math.

Some other request other ways, like #1405

**Comment by Pomax** [comment]
No, even for a markdown editor, it's not an acceptable way to extend the Markdown syntax for LaTeX code blocks. It's only an acceptable way to wrap TeX code blocks, which no one writes directly. 

Also consider that people need to copy-paste between editors: using `$$` instead of the correct block opener and closer means you're (intentionally or not) breaking interoperability between text editors with lax and strict LaTeX block mode, for no good reason: using the correct opener and closer for LaTeX is not a lot of work, while fixing compatibility for everyone currently affected.
