### ISSUE TITLE
代码块模式：中文输入法文本输入时覆盖输入项问题

### ISSUE THREAD

**Issue by peppapigs** [typora/typora-issues#4316]
代码块模式（ctrl + shift + k）内：中文输入法时，输入中文的过程中，会导致中文词汇选项框覆盖掉输入显示，无法看到输入。

**Comment by abnerlee** [comment]
#4299

**Comment by peppapigs** [comment]
Code block mode (ctrl + shift + k): In the Chinese input method（！！！The input method that comes with window）, during the input of Chinese, the Chinese vocabulary option box will cover the input display, and the input cannot be seen.

**Comment by peppapigs** [comment]
![image](https://user-images.githubusercontent.com/41028971/115326115-56adfa80-a1bf-11eb-9487-37f493579964.png)
