### ISSUE TITLE
How to use the blank after equation dollar symbol?

### ISSUE THREAD

**Issue by xiaotianxt** [typora/typora-issues#4317]
I noticed that there are two blanks after beginning and ending dollar symbol:
![image](https://user-images.githubusercontent.com/17041194/115236251-b8358100-a14d-11eb-8988-d2e875fce908.png)
I can see that there's a block in source code: 
![image](https://user-images.githubusercontent.com/17041194/115239861-c08fbb00-a151-11eb-8490-94fe6fc2bc4a.png)
Could anyone tell me how to use them?

**Comment by abnerlee** [comment]
Some markdown spec uses `{}` as attributes, like #1593

Typora currently does not support it (so as GFM), but just make sure it won't prevent the math block being parsed as math block.

Request of attributes is in #249
