### ISSUE TITLE
picgo upload test failed

### ISSUE THREAD

**Issue by fuyunliu** [typora/typora-issues#4319]
command
```
"/Users/fuyun/.nvm/versions/node/v12.16.1/bin/picgo" upload
```

![image](https://user-images.githubusercontent.com/13273942/115338755-1017ca80-a1d6-11eb-99b8-8eaec8a5f58d.png)

![image](https://user-images.githubusercontent.com/13273942/115338879-4ce3c180-a1d6-11eb-8940-bd67946013a9.png)

**Comment by abnerlee** [comment]
you can run "which node" and put its path into your custom command, the command will be something like

```
"/somepath/node" "/Users/fuyun/.nvm/versions/node/v12.16.1/bin/picgo" upload
```

Please use this as current workaround.

---
Typora will uses user's PATH env from next version up, so your old command can be supported in future.
