### ISSUE TITLE
Image src not being inserted directly with URL on clipboard

### ISSUE THREAD

**Issue by AmandaBSobrinho** [typora/typora-issues#4320]
Typora 0.9.98
Ubuntu 18.04.5 LTS

According to this [link](https://support.typora.io/Images/#write-the-markdown) from the support, "If there is an image URL in clipboard, then the URL will be inserted into the src part directly."

However, that is not happening. I put the https://octodex.github.com/images/yaktocat.png in the clipboard but when I click on Insert Image, or use the Ctrl+Shift+I keyboard shortcut, it just stays with the "Input image URL" space not fulfilled with the URL, like the image below.

![Captura de tela de 2021-04-20 13-35-05](https://user-images.githubusercontent.com/16309667/115432911-4c9af480-a1dd-11eb-8c2b-2dbba2f02d9e.png)

**Comment by abnerlee** [comment]
fixed in new release
