### ISSUE TITLE
Table copy paste bug 

### ISSUE THREAD

**Issue by FredericChang** [typora/typora-issues#4325]
System Enviorment:
Typora 0.10.1(beta)
Windows 10 Professional version 20H2

I cannot paste word "NO YET" to last row last cloumn with that word "NO YET". (please refer to first picture)
However I can paste word from other cloumn to last row last cloumn with other word. (please refer to second picture)

It doens't work
![image](https://user-images.githubusercontent.com/7896940/115987664-4f6b6000-a5b6-11eb-9f0a-8f196859c35f.png)

It works.
![image](https://user-images.githubusercontent.com/7896940/115987751-a40edb00-a5b6-11eb-9f2a-bfea6541f6cb.png)

**Comment by abnerlee** [comment]
@FredericChang From here did you copied "NOT YET"?

**Comment by FredericChang** [comment]
Yes, I copied  "NOT YET".
