### ISSUE TITLE
I want to have a transparent Typora

### ISSUE THREAD

**Issue by MizoreYo** [typora/typora-issues#4326]
Typora  is not transparent, it bothers me when I take notes. So I really want to have a transparent Typora.

**Comment by extratone** [comment]
As in, a transparent window?

**Comment by MizoreYo** [comment]
> As in, a transparent window?

Yes, a translucent one

**Comment by abnerlee** [comment]
How transparent window helps you take notes? Does "pin" window fit for this purpose?

**Comment by GoBigorGoHome** [comment]
@MizoreYo https://github.com/gileli121/WindowTop may help.

**Comment by MizoreYo** [comment]
> How transparent window helps you take notes? Does "pin" window fit for this purpose?
The transparent window allows me to see the text behind the window, so I don't have to minimize Typora.
"pin" window may not allow me to consider the coherence of my notes when I write them.

**Comment by MizoreYo** [comment]
> How transparent window helps you take notes? Does "pin" window fit for this purpose?

The transparent window allows me to see the text behind the window, so I don't have to minimize Typora.
"pin" window may not allow me to consider the coherence of my notes when I write them.

**Comment by MizoreYo** [comment]
> @MizoreYo https://github.com/gileli121/WindowTop may help.

thank you

**Comment by abnerlee** [comment]
Close since it seems not a common request and there are workarounds
