### ISSUE TITLE
How to detach typora command on Linux command line?

### ISSUE THREAD

**Issue by laraws** [typora/typora-issues#4327]
When I  try to run the command `nohup typora readme.md >/dev/null 2>&1 &` to keep typora run at background when I close the Linux terminal. But When I close the Linux terminal, the typora GUI closes too. How to detach typora command on Linux command line?

Here is my system info:

OS: Ubuntu 20.04.2 LTS x86_64

**Comment by abnerlee** [comment]
Try `nohup typora &` ? It seems relates to shell instead of Typora.

https://askubuntu.com/questions/10547/how-to-cleanly-launch-a-gui-app-via-the-terminal
