### ISSUE TITLE
Not all email adresses are recognized.

### ISSUE THREAD

**Issue by dnav** [typora/typora-issues#4328]
Input the following text:

```
test@mail.com

test@mail.co.uk

test@mail.de

test@mail.fr

test@mail.it
```

The first three adresses are recognized and appear as links. The last two are not.

![image](https://user-images.githubusercontent.com/1805502/116046913-d16d8e80-a673-11eb-9598-2fc4552cdd9b.png)

See also #3355

**Comment by abnerlee** [comment]
relates #3355

same with #2366

Please use `<email>`

**Comment by abnerlee** [comment]
can be covered in #4021
