### ISSUE TITLE
images won't load in beta version 10.0

### ISSUE THREAD

**Issue by MrGibus** [typora/typora-issues#4329]
Images (which previously worked) won't load in beta version 0.10.0
Method does not matter, drag and drop, insert, manually typed etc..
Format doesn't seem to matter tried jpg, gifs and pngs no difference. 
Location doesn't seem to matter.

Reverting to version 0.9.98 sees the images restored.

**Comment by ddavidebor** [comment]
same on 0.10.1

**Comment by abnerlee** [comment]
fixed, please check update

**Comment by ddavidebor** [comment]
<3
