### ISSUE TITLE
Allow source mode to be entirely unformatted

### ISSUE THREAD

**Issue by cmeeren** [typora/typora-issues#433]
I'd like for source mode to be entirely without formatting, and in a monospaced font. Could you add an option for this? Currently I find myself constantly switching between Typora and a plain text editor.

**Comment by abnerlee** [comment]
We won't provide such option. But you could do this by adding custom CSS.

-  http://support.typora.io/Add-Custom-CSS/
- http://support.typora.io/Code-Block-Styles/
