### ISSUE TITLE
download link of 0.10.3 for macOS not exists

### ISSUE THREAD

**Issue by bxk-sonavex** [typora/typora-issues#4330]
The "Download v0.10.3" link, https://typora.io/download/Typora-0.10.3.dmg, provided in the Software Update popup dialog does not exit, which led to a page showing "Not Found".  Should due to the same issue, clicking Install Update button on the Software Update popup dialog gave an error of "Update Error! Failed to extract update."

**Comment by abnerlee** [comment]
fixed
