### ISSUE TITLE
Tab Bar on Linux?

### ISSUE THREAD

**Issue by dxps** [typora/typora-issues#4331]
Dear Typora team,

This tool is so great that I would pay for it. I am using it for at least one year (and I tried the majority of existing PIM tools until I got settled on Typora, and also promoted to my peers).
I even created my own theme named [Greenview](https://github.com/dxps/typora-greenview)  just didn't yet proposed it to be part of the official offering).

I switched from macOS to Linux some months ago and I am desperately missing the tabs (or Tab Bar). I am working on a couple of topics on a daily basis, so tabs are really handy instead of having multiple Typora windows open for each such topic.

Also, I've asked about it through the "Contact us" section, so here I am, trying again to get a feedback about any chance and delivery time estimation for it. So, please, are you planning to offer the similar nice UX that macOS version has for Linux platform also :grey_question: 

Thanks and appreciate any feedback.

PS
Just started evaluating MarkText alternative since it has tabs and similar markdown experience (that does need any preview). However, it's a little strict with displaying multiple empty lines and not yet (but it's planned to be included in their next release) offers user custom theme support.

**Comment by abnerlee** [comment]
Seem duplicated with #638
