### ISSUE TITLE
Text in .md not appearing version 0.10.3

### ISSUE THREAD

**Issue by redbirdsfan** [typora/typora-issues#4332]
Hello, I have come across a bug in version 0.10.3. In certain documents, the text does not appear even though it is still there. When I open in Typora, it says there are 0 words. When I open the same file in Notepad++ the text appears. I have attached screenshots of the same file in each. I am running Windows 10 version 2004, OS build 19041.928. Thank you for your help.

Screenshot of the file in Typora:
![Typora_Screenshot](https://user-images.githubusercontent.com/50001314/116159499-59788600-a6be-11eb-9740-7ec7a96fd747.jpg)

Screenshot of the file in Notepad++ (names hidden):
![Notepad_Screenshot2](https://user-images.githubusercontent.com/50001314/116159824-ef141580-a6be-11eb-9dc6-c65dfe8b929e.jpg)

I have also noticed that I cannot type anything into the .md file, or copy and paste anything either.

Thank you for your help.

**Comment by abnerlee** [comment]
Still reproducible in 0.10.11?

If so, could you send us (<hi@typora.io>) or attach the md file?
