### ISSUE TITLE
[MacOS] Font style (bond, italic, high-light) not rendering immediately 

### ISSUE THREAD

**Issue by kr11** [typora/typora-issues#4333]
When the file becomes longer or the text style gets complex, the font style(e.g. bold, italic, high-light) cannot render immediately. It has existed for many releases. 

A demo gif is as follows. The font style is rendered only after I type in `Enter`:
![font-render-bug](https://user-images.githubusercontent.com/5548915/116173743-ad777f00-a73f-11eb-9db8-5c75c2364510.gif)

The file (random generated) is attached: 
[font-render-bug.md](https://github.com/typora/typora-issues/files/6381382/font-render-bug.md)

PS: Alternatively, it's also good if there is a button(quick key) to trigger rendering a line manually.

**Comment by abnerlee** [comment]
what's the typora version?

**Comment by kr11** [comment]
> what's the typora version?

It's recently `0.10.3 (5294)`, but I thought I had met this problem in previous versions.
The Typora theme is `Github`.
My Mac version is `10.14.1 (18B75)`.

**Comment by abnerlee** [comment]
still happens in 0.11?

**Comment by abnerlee** [comment]
newer recorded in #5094
