### ISSUE TITLE
Typing subscript or superscript in math formula causes caret moving out of the closing $ symbol

### ISSUE THREAD

**Issue by GoBigorGoHome** [typora/typora-issues#4335]
Steps to reproduce:
1. Upgrade to the latest Typora 0.10.3
2. Enable inline math support in Preferences
3. Create a new markdown file
4. Try typing $x^ and see the closing $ auto completed and caret moving out of the closing $.

**Comment by abnerlee** [comment]
fixed in 0.10.4
