### ISSUE TITLE
Latex rendering mode (size problem)

### ISSUE THREAD

**Issue by 02015678** [typora/typora-issues#4337]
Latex Math Equation Rendering becomes ugly for version 0.9.93, like M$ Word.

For previous version 0.9.92, the rendering of latex math eq is beautiful, the height is matching with that of normal inline text.
But for version 0.9.93, latex math eq is obviously larger than normal inline text, also the rendering is ugly, like M$ Word.

For many times in a single hour, latex math eq rendering engine stop responding, only close Typora then reopen can solve this issues.

Please consider rollback Latex rendering engine. Thanks.

**Comment by abnerlee** [comment]
Could you provide sample markdown code?

**Comment by 02015678** [comment]
<img width="446" alt="Snipaste_2021-05-02_15-15-54" src="https://user-images.githubusercontent.com/10584104/116805505-95499a80-ab59-11eb-9f89-0b4f2f629ade.png">
0.9.92, text height is consistent with latex math expression.


<img width="447" alt="Snipaste_2021-05-02_15-14-05" src="https://user-images.githubusercontent.com/10584104/116805508-97135e00-ab59-11eb-9690-e00e70d9e3bc.png">
0.10.7, text height is reduced, no longer consistent with latex math expression.

**Comment by 02015678** [comment]
Markdown snipet. Chinese Language, UTF-8.

## Part 1：讨论回顾

[1] 假设对SDM输出直接使用sinc^4^(64)降采样，过采样率为$OSR=64$，那么单次转换时间满足
$$
T_0^{-1}=ODR=\frac{F_S}{(3+1)\times OSR}
$$
其中$3+$表示sinc^4^滤波器建立的三拍，滤波后前级PGA引入的噪声为:
$$
\overline{v_n^2} =S_n\times\frac{F_S}{2\times OSR}=S_n\times\frac{(3+1)\cdot OSR \cdot T_0}{2\cdot OSR}=S_n\times\frac{2}{T_0}\label{sinc4}
$$
其中$S_n$为PGA的输出噪声密度($\mathrm{V^2/Hz}$)。可见噪声带宽$NBW=2/T_0$，所需时钟频率为$F_S=(3+1)\cdot OSR/ T_0=256/T_0$。

 [2] 假设对SDM输出使用sinc^4^(64)降采样+sinc(4)降采样（即4点平均），总过采样率为$OSR=64\times 4=256$，那么单次转换时间满足
$$
T_0^{-1}=ODR=\frac{F_S}{(3+4)\times OSR/4}
$$
其中$3+$表示sinc^4^滤波器建立的三拍，滤波后前级PGA引入的噪声为：
$$
\overline{v_n^2} =S_n\times\frac{F_S}{2\times OSR}=S_n\times\frac{(3+4)\cdot OSR/4 \cdot T_0}{2\cdot OSR}=S_n\times\frac{7}{8}\frac{1}{T_0}
$$

**Comment by abnerlee** [comment]
relates #4248

**Comment by abnerlee** [comment]
should be fixed in latest version
