### ISSUE TITLE
latex output overlap caused by style "column-count:2;"

### ISSUE THREAD

**Issue by du33169** [typora/typora-issues#4338]
## Description
Custom css style `column-count:2;` for #write element will cause any formula in mathblock to overlap.
## Sample Markdown
```markdown
$$
F=
$$
```
## Image Result

![1](https://user-images.githubusercontent.com/46591250/116250108-0414a580-a7a0-11eb-8ab4-cee3886e4238.png)

## Some other notes
- Exported HTML files seems perfect in browser
- Irrelevant to the themes.

**Comment by abnerlee** [comment]
I'm not able to reproduce this, what's your verison BTW?

And please try excluding blocks (like math, etc) from splitting up using `-webkit-column-break-inside : avoid;`

**Comment by du33169** [comment]
This problem still exists for me in the lastest version(currently 0.10.11 beta);

Just select one default theme, like "Academic", and edit academic.user.css like this:
```css
#write{
    column-count:2;
}
```
then restart typora.

`-webkit-column-break-inside : avoid;` seems not working, 
and I’m inclined to consider it a problem caused by the version of Mathjax.
