### ISSUE TITLE
file separator difference on macOS and windows

### ISSUE THREAD

**Issue by hintheshell** [typora/typora-issues#4339]
![image](https://user-images.githubusercontent.com/10226889/116268602-0e3ea000-a7b0-11eb-8df4-562da635b5b1.png)
if windows user  add a file reference , mac user click it cannot open 
![image](https://user-images.githubusercontent.com/10226889/116269079-7ab99f00-a7b0-11eb-898f-7754ea9b3ade.png)

**Comment by abnerlee** [comment]
which version?

**Comment by hintheshell** [comment]
latest > which version?

**Comment by Cobertos** [comment]
Latest version is 0.10.4:
https://typora.io/dev_release.html

**Comment by hintheshell** [comment]
> Latest version is 0.10.4:
> https://typora.io/dev_release.html
yes , The problem still exists.
When windows user and macOS user  maintain the same document together, this is what happens.

**Comment by abnerlee** [comment]
should be fixed
