### ISSUE TITLE
When using setext (===) heading style, add lines below entire heading

### ISSUE THREAD

**Issue by cmeeren** [typora/typora-issues#434]
I'm using Markdown because I want my files to look nice also when viewed in plain text. When I create a heading using setext style, the source is like this:

    This is a heading
    ===

I'd like it to be like this:

    This is a heading
    =================

I.e., the line should be as long as the heading (and when changing the heading, the line length should be updated too). This makes the formatting much more clear when viewed in a plain-text editor.

Oh and by the way, I love the app. Really elegant and sleek, and works very well. Keep it up! 👍

**Comment by Crissov** [comment]
Maybe there should be a common minimum length setting for Setext heading underlines (`=` and `-`) and thematic breaks (`---`, `***` and `___`).

**Comment by abnerlee** [comment]
Add the option for generating "Variable-width Setex" style headeing in preference panel.
