### ISSUE TITLE
can't copy exported pdf content 

### ISSUE THREAD

**Issue by zh-d-d** [typora/typora-issues#4342]
first:edit content  with typora 
second: export pdf file
third:open the pdf file ,but i can copy content from the pdf file

**Comment by abnerlee** [comment]
Which OS and Typora theme?
And could you provide a sample md file?

**Comment by zh-d-d** [comment]
OS info: 
      macOS Mojave

Typora info :
     版本 0.9.9.35.2 (4715) 
     newsprint theme

attach file include a sample md file and exported a pdf file.

![image](https://user-images.githubusercontent.com/11935073/116637151-b6fa2480-a995-11eb-9aa2-9be774f6b20d.png)

this image show the content  copy from pdf file .
[hello 文件.md](https://github.com/typora/typora-issues/files/6402512/hello.md)
[hello 文件.pdf](https://github.com/typora/typora-issues/files/6402513/hello.pdf)

**Comment by zh-d-d** [comment]
the function is ok when i test in github theme

**Comment by abnerlee** [comment]
I can view and copy the text in Preview (macOS 11.3) and Chrome

If you cannot copy in Preview.app, please confirm on Chrome, if it works, I think it should be caused by bugs in your PDF reader app.

**Comment by zh-d-d** [comment]
I can't copy text in chrome and preview from PDF file.

**Comment by abnerlee** [comment]
same with #4366?

**Comment by zh-d-d** [comment]
yes ， when you copy Chinese text in this PDF and paste it into other text editors, then you will find that the text you copied is garbled.
