### ISSUE TITLE
Inconsistent copy behaviour of multi-paragraph text from live preview mode 

### ISSUE THREAD

**Issue by gasedwards** [typora/typora-issues#4343]
Typora 0.10.6 (5297) [macOS]

*Issue:*
Copying multi-paragraph text using `CMD + C` from the seamless live preview truncates text at the end of the first paragraph in formatting aware programs (tested in TextEdit, Mail, MS Word).

*Expected:*
Text is pasted with basic formatting (bold, italics etc)

*Workaround:*
Use `CMD + SHIFT + C` for MD-formatted text or Copy Plain Text

**Comment by abnerlee** [comment]
I cannot reproduce this (typora -> TextEditor), possible to attach a screencast?

**Comment by gasedwards** [comment]
Issue is reproducible for me when the first paragraph being copied has any formatting in it (e.g. **bold** or *italic*)

https://user-images.githubusercontent.com/39886718/117586400-d3256080-b10f-11eb-9ae1-982b6f23e38a.mp4

**Comment by abnerlee** [comment]
relates #1236

**Comment by abnerlee** [comment]
should be fixed
