### ISSUE TITLE
Cannot open file if directory contains spaces

### ISSUE THREAD

**Issue by LeonStaufer** [typora/typora-issues#4344]
In the [Flatpak release](https://flathub.org/apps/details/io.typora.Typora), Typora is unable to open files if the directory containing it has spaces in its name.

`Error: Failed to load file: ENOENT: no such file or directory, open ...`

Version 0.10.3 (beta) on Fedora 33.20210421.0 (Silverblue)

**Comment by abnerlee** [comment]
Does the binary version https://typora.io/linux/Typora-linux-x64.tar.gz works?

Currently flatpak version is not officially maintained, it would be issues about the flatpak configs

**Comment by LeonStaufer** [comment]
Thank you, the binary version works.

Would it be possible to support Flatpak as well, please?

**Comment by abnerlee** [comment]
By open, you mean double click the file, or use File - > Open menu in Typora?

Is this https://bugs.launchpad.net/ubuntu/+source/xdg-utils/+bug/1848335 same with your issue, if so, you can try update  xdg-utils as someone commented in that thread.

**Comment by LeonStaufer** [comment]
Thank you. 
I have the latest version of `xdg-utils`, so I doubt that this is the problem. The double-clicking works with other programs and until now I've exclusively experienced the problem with Typora. I will file an issue in the Flatpak repo though.
