### ISSUE TITLE
Losing Text when Editing Rendered Links in Rendered View

### ISSUE THREAD

**Issue by jh2119** [typora/typora-issues#4345]
Hello everyone. Longtime user, and I love the tool.

I keep loosing text after links, and I think it is related to the update I had this week.
For example, I type-up a link markdown and after the closing ')' I have more text at some point some of that extra text is missing.

I don't recall this issue ever before, and the software did recommend an upgrade this week. I don't recall what version I was using.
The issue is happening on Windows 10 Pro  with Typora 0.10.6 (beta). I tried uninstalling and reinstalling.

So I have not been making testing, but I have a common pattern that I have noticed this on. Lists of links with added information. The markdown would be like this

```
- `[ ]` [`TASK-CODE`](link-url)  INFO-HERE
- `[ ]` [`TASK-CODE`](link-url)  INFO-HERE
- `[ ]` [`TASK-CODE`](link-url)  INFO-HERE
```

If I type it in markdown mode, it is fine, but I also use Rendered mode. If I click at the end one list item, and hit `Enter`, a new list item dot appears, but the prior line is damaged.

What happens when I add a item... notice "INFO-HERE" is just "E". Why does "INFO-HER" disappear?
```
- `[ ]` [`TASK-CODE`](link-url)  INFO-HERE
- `[ ]` [`TASK-CODE`](link-url)  E
- 
- `[ ]` [`TASK-CODE`](link-url)  INFO-HERE
```

I put this in markdown text to _show_ the change, but this happens in Rendered mode!

**Comment by abnerlee** [comment]
should be fixed
