### ISSUE TITLE
[improve] Uncontrolled scrolling when opening catalog in smaller window

### ISSUE THREAD

**Issue by Taswen** [typora/typora-issues#4346]
For me, it's frequent to use Ctrl-Shift-L to open/close catalog when editing long document. everything is OK when the window is wide enough. However, in the smaller window sizes, the pop up catalog  will push content  to be thinner, then lines shorten  and whole text roll over. The cursor where I was editing will go out of the visual area of the window. So every time I have to stop writing to use the mouse to find the cursor which is really annoying.
I wish to be able to control the scroll of the cursor when opening catalog in smaller window.

[My Preferences]
**Window Style**: Unibody
**Thems** : Ursine Poiar Alt

**Comment by abnerlee** [comment]
should be fixed in latest version
