### ISSUE TITLE
bug: saving moves current file to bottom of list in tree view

### ISSUE THREAD

**Issue by zmoon** [typora/typora-issues#4348]
I like to have more recent at the top of the list. With v0.10, the current file moves to the bottom upon save (not where it belongs). If I re-sort this is corrected (it moves to the top of list where it belongs). This in file tree view. Doesn't seem to happen in file list view. I first noticed in v0.10.6, but it may have been introduced in an earlier v0.10.

**Comment by abnerlee** [comment]
Which OS? And the tree view is ordered by name or modified date?

**Comment by zmoon** [comment]
Windows. And it looks like it happens with all 3 sorting options.

**Comment by abnerlee** [comment]
We cannot reproduce this in my test, possible to send us <hi@typora.io> a screencast?

**Comment by zmoon** [comment]
Yes, I just sent one.

**Comment by zmoon** [comment]
Seems to be fixed in the new release (says 0.10.8 [here](https://typora.io/dev_release.html) but 0.10.7 within the app itself)

**Comment by abnerlee** [comment]
should be fixed in latest version
