### ISSUE TITLE
Relax requirement for image uploads to start http://, https://, or file://, to allow relative paths

### ISSUE THREAD

**Issue by dirkagterhuis** [typora/typora-issues#4349]
Typora is great, and I use it a lot. Both as a note system, and to edit markdown files in code repositories. The thing is, I don't use an online image hosting service. I have all files locally, in a Onedrive (or Google Drive, or Dropbox, or ...) synced folder, and push them to a different git repo's, including the images. 

I have different 'projects' or 'workspaces' (whatever you want to call them) in Typora. And per project, I want to upload assets/images to a different directory. I've written a bash script to run upon pasting an image, and it checks the current directory of the .md file for a `.assets` directory. If there's none, it goes up a level, etc., and if it doesn't find any `.assets` dir, it creates one at the current level. In the end, this will only be useful if I can have the script return a relative path, because then I can clone the project onto any device locally, or push to any e.g. website, and have the image references work. 

However, Typora only allows image upload scripts to return `http://`, `https://`, or `file://`: 
> Like [#3309](https://github.com/typora/typora-issues/issues/3309), Typora requires the return url of an image to start with http://, https://, or file://. Other protocols are not supported. Also, in HTML / Markdown, image src without protocols, are treated like relative path. ([resource](https://support.typora.io/Upload-Image/#upload-all-local-images))

 ...while I'd like it to work using any relative path, e.g. `../../../.assets.catImage.jpg`. 

So, the title of this issue is maybe misleading because it already contains a solution to my problem, and maybe I'm taking the wrong road to achieve it, but I'm open to alternatives. Maybe I'm misusing the image upload script for any custom work on images I'm pasting. Then again, I am uploading the image to Onedrive/Google Drive/Dropbox/...

**Comment by dirkagterhuis** [comment]
An alternative might be to not have a 'per document' yaml setting, but a 'project' or 'workspace' yaml config file, where I can configure images to be moved to, upon pasting the image.

**Comment by abnerlee** [comment]
can be covered by #3109

Current if a script return text like "ERROR to move aaa.png", typora cannot know if it is just a message, or should insert image with path "ERROR to move aaa.png", if no protocol is required to fetch the image address

**Comment by JuchiaLu** [comment]
> can be covered by #3109
> 
> Current if a script return text like "ERROR to move aaa.png", typora cannot know if it is just a message, or should insert image with path "ERROR to move aaa.png", if no protocol is required to fetch the image address

I have the same problem when I wrote a program to upload the picture to Joplin.

Joplin will be able to recognize the plugin returned a relative path:

https://user-images.githubusercontent.com/36222739/201578367-b10ca0dd-c9da-4363-b341-8b9a7964ad96.mp4

but it no worked if the plugin returned an absolute path:

https://user-images.githubusercontent.com/36222739/201578291-5c086216-384f-4d10-9349-2771b9ef8853.mp4

How about this：The plugin returns a path starting with "file://", but provides an option for typora to decide if it needs "file://" when replacing the path.
