### ISSUE TITLE
bug: `` in title displays error

### ISSUE THREAD

**Issue by PureWhiteWu** [typora/typora-issues#4350]
![image](https://user-images.githubusercontent.com/3314335/116518210-8ae19380-a902-11eb-8e9b-986d827533ad.png)

source:
```
 # 在`runtime`外调用`vdso`
```

version: 0.10.6
macOS 11.3

**Comment by FredericChang** [comment]
I think it's correct to display like as you got on screen.

you could try this way with **Escaping Backticks**.

``在`runtime`外调用`vdso` ``


![image](https://user-images.githubusercontent.com/7896940/116599867-e9ba0380-a928-11eb-8b54-ddd745924e1a.png)

**Comment by PureWhiteWu** [comment]
Hello, my point is they should be the same size.

**Comment by abnerlee** [comment]
should be fixed
