### ISSUE TITLE
Feature Request: Collapsed document outlines in editor.

### ISSUE THREAD

**Issue by toshiya14** [typora/typora-issues#4352]
I have used typora for months, and feel it really a very comfortable editor for markdown.
I am a software programmer, and most of our code editor have the function to collapsed some blocks in our code.

So, I think it is awesome if typora could implement the same feature.
If we work with a long document, the contents are very long and hard to find what we are looking for.

I have found the collapsed outlines in the left side menu.
Perhaps it is better to add a arrow`v` to each heading in the editor.
Then the editor would hide the contents below and turn the arrow to `>` if we click the arrow.

```
v # Heading 1
  contents
v ## Heading 1.1
  contents
> # Heading 2
  ...

```

```
> # Heading 1
  ...
> # Heading 2
  ...
```

**Comment by abnerlee** [comment]
#499
