### ISSUE TITLE
Update Mermaid for ER and other functionalities

### ISSUE THREAD

**Issue by falahati** [typora/typora-issues#4353]
Hey guys, it would be great if we could update the Mermaid version to the latest to have access to the new ER syntax. Currently, we are on 8.8.3 while they are at least one minor version ahead.

https://github.com/mermaid-js/mermaid/pull/1750

**Comment by abnerlee** [comment]
put into #1661

**Comment by damageboy** [comment]
Specifically, the latest mermaid will render ER as:

![image](https://user-images.githubusercontent.com/125730/119250150-b7f23080-bba6-11eb-9489-98af9204f904.png)


While with Typora:

![image](https://user-images.githubusercontent.com/125730/119250155-c5a7b600-bba6-11eb-9fa5-ff59ea7498fe.png)
