### ISSUE TITLE
Runaway CPU when launched from Gnome/Nautilus

### ISSUE THREAD

**Issue by ginkgomzd** [typora/typora-issues#4354]
After launching more than one window, through selecting files in nautilus, my CPUs start running away.

Typora 0.10.6 (issue appeared in previous version, but still present).
Ubuntu 18.04.5 LTS
Gnome 3.28.2

![image](https://user-images.githubusercontent.com/2687924/116694107-d9d40b00-a98c-11eb-9b59-92cc8c707f11.png)

**Comment by abnerlee** [comment]
Will it decrease after launch?

Will it happens for empty file? If not, then possible to send us <hi@typora.io> the sample file?

**Comment by ginkgomzd** [comment]
Of course, I can't reproduce it today. 
I will stay alert for it happening again. 

My sense is that it depends on how the files are opened, and not the contents of the file, but I don't have any firm beliefs since I can't reliably reproduce it.

**Comment by ginkgomzd** [comment]
I think this was probably either a nautilus or electron issue. It's appearance, and apparent subsidence did not coincide with updates to Typora. I've changed my habits because of it, but trying to re-create it has not been successful.

**Comment by ginkgomzd** [comment]
there is definitely something going on, although it hasn't resulted in runaway CPU recently.
Even with a simple markdown file (only a title), Nautilus is hourglass-ing for several seconds.
I tried watching processes to find a culprit, but my method is too crude to find anything helpful.

**Comment by abnerlee** [comment]
put into #68
