### ISSUE TITLE
Switching the left header causes the problem of jamming

### ISSUE THREAD

**Issue by HealerLu** [typora/typora-issues#4355]
When using the latest version (0.1.0) on top of macOS 11.3, even though there is very little content written in a markdown file, as soon as you click on the title on the left to jump, it causes the software to get stuck and the mouse keeps loading. This is shown in the figure below.
![](https://ftp.bmp.ovh/imgs/2021/05/c4852ba5395de855.png)

**Comment by abnerlee** [comment]
Is this reproducible after restart Typora?

**Comment by HealerLu** [comment]
> Is this reproducible after restart Typora?

Yes,No matter if I restart Typora or uninstall and reinstall or restart my Mac, the problem still recurs.

**Comment by abnerlee** [comment]
We cannot reproduce this.

Could you try upgrade to latest version, if it still happens, then attach the sample file for us to test.
Also, what's your typora theme, and did you add any custom css?

**Comment by HealerLu** [comment]
> We cannot reproduce this.
> 
> Could you try upgrade to latest version, if it still happens, then attach the sample file for us to test.
> Also, what's your typora theme, and did you add any custom css?

Just updated to the latest version (0.10.8 ) today. The theme is default Github and does not use custom css. Any documentation will show this problem even with the official help documentation. Here is the video and test documentation I provided. I hope this helps you.



https://user-images.githubusercontent.com/31911829/116807030-7ea84100-ab63-11eb-8fa5-ddd5da62ede0.mp4

[Example.md](https://github.com/typora/typora-issues/files/6410992/Example.md)

**Comment by abnerlee** [comment]
I didn't receive similar reports.

- What's your overall CPU usage, Does this happen when you connect your macbook to power (not using battery power)
- Try remove Typora completely (backup your data then remove ~/Library/Application Support/abnerworks.Typora/, ~/Library/Caches/abnerworks.Typora/) and reinstall it, see if it solves the issue or not

**Comment by HealerLu** [comment]
> I didn't receive similar reports.
> 
> * What's your overall CPU usage, Does this happen when you connect your macbook to power (not using battery power)
> * Try remove Typora completely (backup your data then remove ~/Library/Application Support/abnerworks.Typora/, ~/Library/Caches/abnerworks.Typora/) and reinstall it, see if it solves the issue or not

CPU usage is generally like this, here is the configuration of my Mac. This problem still occurs when using power. Uninstalling and reinstalling as you provided still did not fix it. I'm on the verge of giving up, it's so hard....
<img width="894" alt="iShot2021-05-16 22 39 18" src="https://user-images.githubusercontent.com/31911829/118401420-3a0ac280-b698-11eb-8a37-6bd7b6ea7a7d.png">
<img width="598" alt="iShot2021-05-16 22 40 05" src="https://user-images.githubusercontent.com/31911829/118401426-3f680d00-b698-11eb-86bf-a98ff7dfb6df.png">

**Comment by abnerlee** [comment]
same with #4412?

**Comment by abnerlee** [comment]
put into #4430
