### ISSUE TITLE
YAML not picking up PDF metadata

### ISSUE THREAD

**Issue by ianpotpie** [typora/typora-issues#4356]
I'm having an issue with the default PDF export in which the exported PDF does not have the meta-data indicated by the YAML. For some reason the "keywords"/"tags" will always work, but "title" and "author" will appear as "None" unless I fill out the "heading" in the export preferences (currently I have the heading as an empty space in order to get things to work).

**Comment by abnerlee** [comment]
Provide a sample md file please? and which OS are you using?

**Comment by ianpotpie** [comment]
I'm running Typora 0.10.6 on Ubuntu 20.4. 
Here are some screenshots of my PDF export settings:
![Screenshot from 2021-05-01 09-24-08](https://user-images.githubusercontent.com/30676689/116783901-5800e200-aa5f-11eb-8d0e-21ad28c88d79.png)
And an example with one of my notes:
![Screenshot from 2021-05-01 09-25-27](https://user-images.githubusercontent.com/30676689/116783903-5a633c00-aa5f-11eb-80b8-2873ea155032.png)

**Comment by ianpotpie** [comment]
If I add any text to the "heading" in the export settings, then everything works properly

**Comment by abnerlee** [comment]
should be fixed
