### ISSUE TITLE
This beta version of Typora is expired, please download and install a newer version

### ISSUE THREAD

**Issue by diasgab** [typora/typora-issues#4357]
I have just upgraded from my last Typora version and I get the message "This beta version of Typora is expired, please download and install a newer version". I've been using Typora for years and I've never had this issue.

<img width="1427" alt="Screen Shot 2564-05-01 at 10 41 11" src="https://user-images.githubusercontent.com/523604/116769953-3527fb00-aa6a-11eb-950b-a1c5ca9d4328.png">

OS: macOS Big Sur, Version 11.2.3
Typora 0.10 beta

**Comment by abnerlee** [comment]
Can restart Typora solve this?

And is your system time current (2021/05/01)?

**Comment by diasgab** [comment]
I restarted my computer, same error.

Yes the time is correct. I am in Bangkok timezone. Maybe it's related to
that but I've never had any issue.

Kind regards,
Gabriel Dias

**Comment by abnerlee** [comment]
Then try upgrade or download the latest version from typora.io, and see if it still eixists

**Comment by diasgab** [comment]
Yes that's what I did. That's why I am reporting the bug. I downloaded the
last version from the webpage, removed my previous installation, installed
the new one, and still having the same error.

Gabriel Dias

**Comment by diasgab** [comment]
> Could you open console.app, show column "Date & Time", start recording, then launch Typora, and search for "build date", then attach the screenshot of console.app?

I don't know how to do what you are asking. I cannot find the build date anywhere. Could you give me another hint on how to do it please ?

**Comment by diasgab** [comment]
> @abnerlee i've got the same issue.
> 
> ![image](https://user-images.githubusercontent.com/5326774/117603759-0ef70f00-b17e-11eb-856a-bb06dcad08c7.png)
> 
> I have to downgrade a Typora version from 10 to 9 to make it works.

Thank you for the hint, downgrading to version 0.9 worked! https://typora.io/dev_release.html

**Comment by abnerlee** [comment]
@diasgab @keeratita I mean something like this

<img width="1530" alt="Screen Shot 2021-05-10 at 21 00 39" src="https://user-images.githubusercontent.com/1621242/117663023-c9186600-b1d2-11eb-8da1-ed37596662bf.png">

**Comment by keeratita** [comment]
> @diasgab @keeratita I mean something like this
> 
> <img alt="Screen Shot 2021-05-10 at 21 00 39" width="1530" src="https://user-images.githubusercontent.com/1621242/117663023-c9186600-b1d2-11eb-8da1-ed37596662bf.png">
> 
> 1. open console.app
> 2. show column "Date & Time" by right click on the table
> 3. click start icon in toolbar
> 4. then launch Typora
> 5. search for "build date"
> 
> Or at least, please enable the "Date & Time" column in console.app for us to see if it is caused by incorrect system date.

no any logs appeared if search by `build date`.

**Comment by keeratita** [comment]
![output](https://user-images.githubusercontent.com/5326774/118345813-34f72780-b561-11eb-8504-07e884583a36.gif)

**Comment by abnerlee** [comment]
@keeratita Are you using 0.10.9 or newer?

**Comment by keeratita** [comment]
the latest version

**Comment by keeratita** [comment]
@abnerlee any good news so far?

**Comment by abnerlee** [comment]
@keeratita  I tried with 0.10.10, there should be log with build date, could you retry it if possible?l

**Comment by keeratita** [comment]
@abnerlee i will try again now

**Comment by keeratita** [comment]
@abnerlee I confirmed.. there is no `build date` log. i've tried it many times.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/5326774/119658619-8e136500-be57-11eb-839f-e6df14ef2249.png">

**Comment by keeratita** [comment]
@abnerlee not sure is this also helpful?

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/5326774/119659212-290c3f00-be58-11eb-87aa-496c37ebac08.png">

**Comment by diasgab** [comment]
Here is my log output (only for process Typora)

`
default	10:00:33.982033+0700	Typora	Received configuration update from daemon (initial)
default	10:00:33.982747+0700	Typora	CHECKIN: pid=66209
default	10:00:33.995728+0700	Typora	CHECKEDIN: pid=66209 asn=0x0-0x53a53a foreground=1
default	10:00:34.033111+0700	Typora	FRONTLOGGING: version 1
default	10:00:34.033133+0700	Typora	Registered, pid=66209 ASN=0x0,0x53a53a
default	10:00:34.036149+0700	Typora	BringForward: pid=66209 asn=0x0-0x53a53a bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	10:00:34.036231+0700	Typora	BringFrontModifier: pid=66209 asn=0x0-0x53a53a Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	10:00:34.036365+0700	Typora	BringForward: pid=66209 asn=0x0-0x53a53a
default	10:00:34.036431+0700	Typora	SetFrontProcess: asn=0x0-0x53a53a options=0
default	10:00:34.058417+0700	Typora	Current system appearance, (HLTB: 2), (SLS: 1)
default	10:00:34.064713+0700	Typora	Post-registration system appearance: (HLTB: 2)
default	10:00:34.168554+0700	Typora	Registering for test daemon availability notify post.
default	10:00:34.168781+0700	Typora	notify_get_state check indicated test daemon not ready.
default	10:00:34.268007+0700	Typora	SignalReady: pid=66209 asn=0x0-0x53a53a
default	10:00:34.268769+0700	Typora	SIGNAL: pid=66209 asn=0x0x-0x5481786
default	10:00:34.278976+0700	Typora	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x60000192d280
 (
    "<NSDarkAquaAppearance: 0x60000192d180>",
    "<NSSystemAppearance: 0x60000192cd80>"
)>
default	10:00:34.321635+0700	Typora	Adding presenter 77A07257-AFAD-42AE-89FB-950BEF4E2EFA for URL: <private>
default	10:00:34.322817+0700	Typora	Adding presenter 77A07257-AFAD-42AE-89FB-950BEF4E2EFA for URL: <private>
default	10:00:34.330979+0700	Typora	Resolve item 612559E3-2252-44F5-986F-85F01586841A, options: 768, list: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:34.330979+0700	Typora	Resolve item 11808DAD-3913-47C3-B05C-FA4678005E67, options: 768, list: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:34.333002+0700	Typora	received: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:34.334248+0700	Typora	received: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:34.366549+0700	Typora	0x10eeea5e8 - [PID=0] WebProcessCache::updateCapacity: Cache is disabled because process swap on navigation is disabled
default	10:00:34.371301+0700	Typora	-[SOAuthorization init]  on <private>
default	10:00:34.372261+0700	Typora	-[SOAuthorizationCore init]  on <private>
default	10:00:34.374392+0700	Typora	<SOServiceConnection: 0x60000370b720>: new XPC connection
default	10:00:34.374857+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::constructor:
default	10:00:34.375193+0700	Typora	0x10eeea5e8 - [PID=0] WebProcessCache::updateCapacity: Cache is disabled by client
default	10:00:34.425898+0700	Typora	Could not find image named 'NSImageNameTouchBarTextListTemplate'.
default	10:00:34.462675+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::loadFile:
default	10:00:34.462740+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::launchProcess:
default	10:00:34.470263+0700	Typora	0x10eef7200 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebProcess initialization'
default	10:00:34.472206+0700	Typora	Faulting in CFHTTPCookieStorage singleton
default	10:00:34.472227+0700	Typora	Creating default cookie storage with process/bundle identifier
default	10:00:34.475828+0700	Typora	Faulting in NSHTTPCookieStorage singleton
default	10:00:34.483788+0700	Typora	<PKDiscoveryDriver:0x600001310720> created discovery driver
default	10:00:34.483855+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 0, point: com.apple.services
default	10:00:34.483983+0700	Typora	<PKDiscoveryDriver:0x6000013106c0> created discovery driver
default	10:00:34.484028+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 0, point: com.apple.ui-services
default	10:00:34.489921+0700	Typora	<<<< Alt >>>> fpSupport_GetVideoRangeForCoreDisplayWithPreference: displayID 4280f40 reported potentialHeadRoom=2 wideColorSupported=YES marz=NO almd=NO deviceAllowsHDR=YES isBuiltinPanel=YES externalPanel=YES prefersHDR10=NO
default	10:00:34.508438+0700	Typora	0x10f0fe4d8 - [PID=0] ProcessThrottler::invalidateAllActivities: BEGIN
default	10:00:34.508465+0700	Typora	0x10f0fe4d8 - [PID=0] ProcessThrottler::invalidateAllActivities: END
default	10:00:34.510806+0700	Typora	nw_path_evaluator_start [23E165FA-DB0A-4FEC-A440-2D8D299AC469 <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns
default	10:00:34.534300+0700	Typora	-[WKWebView _setDrawsTransparentBackground:] is deprecated and should not be used.
default	10:00:34.567214+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 4
default	10:00:34.567259+0700	Typora	<PKDiscoveryDriver:0x600001310720> delivering update to host (4 plugins)
default	10:00:34.573645+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 1
default	10:00:34.573811+0700	Typora	<PKDiscoveryDriver:0x6000013106c0> delivering update to host (1 plugins)
default	10:00:34.574086+0700	Typora	<PKDiscoveryDriver:0x600001310720> installing watchers for continuous discovery
default	10:00:34.575336+0700	Typora	<PKDiscoveryDriver:0x6000013106c0> installing watchers for continuous discovery
default	10:00:34.600888+0700	Typora	0x10eef7500 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:34.600931+0700	Typora	0x10eef7520 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:34.743400+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::updateActivityState: view visibility state changed 0 -> 1
default	10:00:34.744126+0700	Typora	0x10eeea5e8 - [PID=0] WebProcessCache::setApplicationIsActive: (isActive=1)
default	10:00:34.752926+0700	Typora	filteredItemsFromItems:<private> [66209]--> <private>
default	10:00:34.755305+0700	Typora	Requesting sharingServicesForFilteredItems:<private> mask:<private>
default	10:00:34.755398+0700	Typora	Query extensions (async) for items: <private> onlyViewerOrEditor:1
default	10:00:34.755568+0700	Typora	filteredItemsFromItems:<private> [66209]--> <private>
default	10:00:34.755614+0700	Typora	Requesting sharingServicesForFilteredItems:<private> mask:<private>
default	10:00:34.755666+0700	Typora	Query extensions (async) for items: <private> onlyViewerOrEditor:1
default	10:00:34.756469+0700	Typora	Matching dictionary: <private>, attributesArray: <private>
default	10:00:34.756469+0700	Typora	Matching dictionary: <private>, attributesArray: <private>
default	10:00:34.756561+0700	Typora	Discover extensions with attributes <private>
default	10:00:34.756638+0700	Typora	Discover extensions with attributes <private>
default	10:00:34.757056+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 1024, point: com.apple.ui-services
default	10:00:34.757283+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 1024, point: com.apple.ui-services
default	10:00:34.760744+0700	Typora	filteredItemsFromItems:<private> [66209]--> <private>
default	10:00:34.760791+0700	Typora	Requesting sharingServicesForFilteredItems:<private> mask:<private>
default	10:00:34.760823+0700	Typora	Query extensions (async) for items: <private> onlyViewerOrEditor:1
default	10:00:34.760962+0700	Typora	Matching dictionary: <private>, attributesArray: <private>
default	10:00:34.760951+0700	Typora	0x10eee8000 - NetworkProcessProxy is taking a background assertion because a web process is requesting a connection
default	10:00:34.761080+0700	Typora	Discover extensions with attributes <private>
default	10:00:34.761426+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 1024, point: com.apple.ui-services
default	10:00:34.768845+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 1
default	10:00:34.769296+0700	Typora	1 plugins found
default	10:00:34.771652+0700	Typora	Service with identifier <private> passes activation rule: 0
default	10:00:34.771825+0700	Typora	Service dictionary for plugin <private> not available, skip it.
default	10:00:34.771953+0700	Typora	0 compatible services found for attributes <private>
default	10:00:34.772047+0700	Typora	Discovery done
default	10:00:34.772264+0700	Typora	Discover extensions with attributes <private>
default	10:00:34.772722+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 1024, point: com.apple.services
default	10:00:34.779284+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 1
default	10:00:34.779437+0700	Typora	1 plugins found
default	10:00:34.779680+0700	Typora	Service with identifier <private> passes activation rule: 1
default	10:00:34.788058+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 1
default	10:00:34.788239+0700	Typora	1 plugins found
default	10:00:34.788470+0700	Typora	Service with identifier <private> passes activation rule: 0
default	10:00:34.788500+0700	Typora	Service dictionary for plugin <private> not available, skip it.
default	10:00:34.788527+0700	Typora	0 compatible services found for attributes <private>
default	10:00:34.788549+0700	Typora	Discovery done
default	10:00:34.788671+0700	Typora	Discover extensions with attributes <private>
default	10:00:34.788815+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 1024, point: com.apple.services
default	10:00:34.810349+0700	Typora	1 compatible services found for attributes <private>
default	10:00:34.810524+0700	Typora	Discovery done
default	10:00:34.810647+0700	Typora	Discover extensions with attributes <private>
default	10:00:34.810837+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Beginning discovery for flags: 1024, point: com.apple.services
default	10:00:34.865734+0700	Typora	0x10eef7200 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebProcess initialization'
default	10:00:34.882092+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 4
default	10:00:34.882478+0700	Typora	4 plugins found
default	10:00:34.882535+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.882565+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.882658+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.882755+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.882853+0700	Typora	0 compatible services found for attributes <private>
default	10:00:34.882920+0700	Typora	Discovery done
default	10:00:34.883004+0700	Typora	Completed querying extensions: <private>
default	10:00:34.889812+0700	Typora	Sorted services: <private>
default	10:00:34.898904+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::decidePolicyForNavigationAction: frameID: 3, navigationID: 1
default	10:00:34.900552+0700	Typora	-[SOConfigurationClient init]  on <private>
default	10:00:34.900705+0700	Typora	<SOServiceConnection: 0x60000375aac0>: new XPC connection
default	10:00:34.900996+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::decidePolicyForNavigationAction: listener called: frameID: 3, navigationID: 1, policyAction: 0, safeBrowsingWarning: 0, isAppBoundDomain: 0
default	10:00:34.901015+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::receivedNavigationPolicyDecision: frameID: 3, navigationID: 1, policyAction: 0
default	10:00:34.901036+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::decidePolicyForNavigationAction: keep using process 66210 for navigation, reason: Process has not yet committed any provisional loads
default	10:00:34.913928+0700	Typora	0x10eef7500 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:34.913978+0700	Typora	0x10eef7520 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:34.916322+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::didStartProvisionalLoadForFrame: frameID = 3
default	10:00:34.929452+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::didNavigateWithNavigationDataShared:
default	10:00:34.929519+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::didCommitLoadForFrame: frameID = 3
default	10:00:34.968647+0700	Typora	[d <private>] <PKHost:0x60000224c7c0> Completed discovery. Final # of matches: 4
default	10:00:34.968961+0700	Typora	4 plugins found
default	10:00:34.969005+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.969028+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.969049+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.969069+0700	Typora	Plugin <private> not enabled, skip it.
default	10:00:34.969125+0700	Typora	0 compatible services found for attributes <private>
default	10:00:34.969216+0700	Typora	Discovery done
default	10:00:34.969309+0700	Typora	Completed querying extensions: <private>
default	10:00:34.969960+0700	Typora	Sorted services: <private>
default	10:00:35.045255+0700	Typora	Sorted services: <private>
default	10:00:35.129796+0700	Typora	0x10eef7a30 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.129980+0700	Typora	0x10eef7a80 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.136203+0700	Typora	0x10eef7b20 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.142457+0700	Typora	0x10eef7b60 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.212734+0700	Typora	0x10eef7ba0 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.215826+0700	Typora	Resolve item 612559E3-2252-44F5-986F-85F01586841A, options: 768, list: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:35.216804+0700	Typora	received: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:35.217700+0700	Typora	Resolve item 11808DAD-3913-47C3-B05C-FA4678005E67, options: 768, list: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:35.218576+0700	Typora	received: com.apple.LSSharedFileList.ApplicationRecentDocuments
default	10:00:35.219120+0700	Typora	0x10eef7d00 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.219378+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::didFinishDocumentLoadForFrame: frameID = 3
default	10:00:35.240864+0700	Typora	0x10eef7d60 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.255781+0700	Typora	0x10eef7a30 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.256231+0700	Typora	0x10eef7a80 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.274398+0700	Typora	0x10eef7b20 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.285984+0700	Typora	0x10eef7ff0 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::fontAtSelection'
default	10:00:35.332907+0700	Typora	0x10eef7b60 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.432255+0700	Typora	0x10eef7ba0 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.432442+0700	Typora	0x10eef7d00 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.433254+0700	Typora	0x10eef7d60 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.440148+0700	Typora	0x10eef7ff0 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::fontAtSelection'
default	10:00:35.469630+0700	Typora	0x10eef73d0 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.475222+0700	Typora	0x10eef73d0 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
default	10:00:35.534152+0700	Typora	0x10eef7a50 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::fontAtSelection'
default	10:00:35.536477+0700	Typora	0x10eef7a50 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::invalidate: Ending background activity / 'WebPageProxy::fontAtSelection'
default	10:00:35.547137+0700	Typora	0x7f9910097c20 - [pageProxyID=5, webPageID=6, PID=66210] WebPageProxy::didFinishLoadForFrame: frameID = 3
default	10:00:35.858516+0700	Typora	Opening URL <private> with application <private>
default	10:00:35.879750+0700	Typora	-[SFLGenericList _insertItem:atIndex:error:]_block_invoke item: 20FB5CDB-0D69-4FDA-876E-5554D7AB5945 at index: 0 list: com.apple.LSSharedFileList.RecentApplications
default	10:00:35.880687+0700	Typora	received: com.apple.LSSharedFileList.RecentApplications
default	10:00:36.026978+0700	Typora	Initializing connection
default	10:00:36.027082+0700	Typora	Removing all cached process handles
default	10:00:36.027132+0700	Typora	Sending handshake request attempt #1 to server
default	10:00:36.027172+0700	Typora	Creating connection to com.apple.runningboard
default	10:00:36.028364+0700	Typora	Handshake succeeded
default	10:00:36.028409+0700	Typora	Identity resolved as app<application.abnerworks.Typora.8632988.8633257(501)>
error	10:00:36.029988+0700	Typora	volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
error	10:00:36.030458+0700	Typora	volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
default	10:00:36.034912+0700	Typora	0x10eeb0040 - [PID=0, throttler=0x10f0fe818] ProcessThrottler::Activity::Activity: Starting background activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
error	10:00:36.035099+0700	Typora	volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
default	10:00:36.036540+0700	Typora	Removing presenter 77A07257-AFAD-42AE-89FB-950BEF4E2EFA
default	10:00:36.036680+0700	Typora	Removing presenter 77A07257-AFAD-42AE-89FB-950BEF4E2EFA
default	10:00:36.038218+0700	Typora	Entering exit handler.
default	10:00:36.038316+0700	Typora	Exiting exit handler.
`

**Comment by diasgab** [comment]
Here is the complete log for typora from console.app. Is this useful?


[typora.txt](https://github.com/typora/typora-issues/files/6550807/typora.txt)

**Comment by keeratita** [comment]
@abnerlee unfortunately, not found any records of `userOp` keyword. And no troubles at all, we should thank you for this great app.

here is my logs.
[typora.txt](https://github.com/typora/typora-issues/files/6553350/typora.txt)

**Comment by abnerlee** [comment]
@keeratita @diasgab Sorry, could you confirm if you enabled "Include Info Message" when getting log? 
like https://support.typora.io/media/logs/Screen%20Shot%202020-03-01%20at%2022.09.46.png

If not, just enable it, search "build date" or "userOp" and re-attach the log file.

**Comment by keeratita** [comment]
@abnerlee oh yea, it was not enabled. 
here you are :) 

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/5326774/119869668-b7f98400-bf4a-11eb-9b96-7aa1fba079f2.png">

**Comment by diasgab** [comment]
I only got this (with the Include Info Message enabled)

<img width="1197" alt="Screen Shot 2564-05-30 at 22 51 03" src="https://user-images.githubusercontent.com/523604/120110870-9e9a4700-c199-11eb-9fe0-84b43972e106.png">

**Comment by abnerlee** [comment]
should be fixed in 0.10.11, please try download from typora.io again~

**Comment by keeratita** [comment]
it works :) thank you so much

Best Regards,
Keerati Tansawatcharoen
