### ISSUE TITLE
sub-content of 'Export' Option in Preferences

### ISSUE THREAD

**Issue by corgile** [typora/typora-issues#4358]
# I found there is some content out of boundary, I hope to scroll there but I can't

https://user-images.githubusercontent.com/48396880/116785982-0c861c80-aacf-11eb-9148-49d5da291f80.mp4

**Comment by abnerlee** [comment]
try scroll with mousewheel as workaround?

**Comment by corgile** [comment]
> try scroll with mousewheel as workaround?

### Yes, I tried scroll the mousewheel, but this area doesn't scroll, I'm sure there is nothing wrong with the mouse

![image](https://user-images.githubusercontent.com/48396880/116800648-a680b000-ab35-11eb-98c2-841a90433cae.png)

**Comment by corgile** [comment]
> try scroll with mousewheel as workaround?

### Yes, I tried scroll the mousewheel, but this area doesn't scroll, I'm sure there is nothing wrong with the mouse

![image](https://user-images.githubusercontent.com/48396880/116800668-cdd77d00-ab35-11eb-83e6-4eb7ba741013.png)

**Comment by abnerlee** [comment]
should be fixed
