### ISSUE TITLE
[Bug] Auto generated bug appears in the combination use of back quotes and tabs

### ISSUE THREAD

**Issue by Taswen** [typora/typora-issues#4360]
Try pressing  **\`**   **Tab** three times in turn. You will get the following result：
![image](https://user-images.githubusercontent.com/30777327/116807647-e613c000-ab66-11eb-9433-00299215269f.png)

Then you position the cursor after the first block displayed, long press Backspace to try to delete:
![image](https://user-images.githubusercontent.com/30777327/116807675-004d9e00-ab67-11eb-9c3d-ef75ed7eb752.png)

And then Boom, you get a bunch of automatically generated blanks.
![image](https://user-images.githubusercontent.com/30777327/116807758-794cf580-ab67-11eb-8c02-9df0f5cb9b85.png)

I accidentally discovered this, and the cost was that the document content I was writing was stuck and lost (it was not saved, I had to kill the process)🙃. 

The above are the steps given in trying to reproduce the bug. In fact, the number of blanks generated depends on the number of your **\`** and **Tabs** and where you start to try to delete. When I accidentally encountered it for the first time, The number of blanks has growth so fast that I could watch the memory and CPU occupied by them in the task manager soaring rapidly.

I guess the problem lies in the automatically generated logic.

**Related configuration**
version 0.10.7(beta) and before
![image](https://user-images.githubusercontent.com/30777327/116808133-c9c55280-ab69-11eb-8b8e-8d5697a599b5.png)

**Comment by abnerlee** [comment]
should be fixed in latest version
