### ISSUE TITLE
Math boxes for equations with 4 or more lines are not sized correctly and have scroll bars

### ISSUE THREAD

**Issue by aardvark-adventurer** [typora/typora-issues#4361]
**Note: Problem in 0.10.x (downgrading to 0.9.9.x resolves the issue); Observed on MacOS Catalina 10.15.7**

Math (equations) boxes with 4 or more separate statements are sized just slightly incorrectly and end up with vertical and horizontal scroll bars blocking content. This is in default zoom and default text size.

See screenshot:
![image](https://user-images.githubusercontent.com/5208744/116830373-76013c00-ab5e-11eb-9ace-ad9ba6e9e93f.png)

Markdown for the above example:
```
Up to three lines, no problem
$$
a=1\\
b=2\\
c=3\\
$$
4 or more lines, scroll bars show up
$$
a = 1 \\
b = 2 \\
c = 3 \\ 
d = 4 \\
$$
Actually it's not the number of lines, it's the overall height of the math box that causes the issue. 3 line equation with enough vertical space to trigger the issue:
$$
\begin{eqnarray}
\frac{a}{b}&=&1\\
\frac{b}{c}&=&3\\
\frac{c}{d}&=&4\\
\end{eqnarray}
$$
```

**Comment by abnerlee** [comment]
may relates #4337

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by haowen-avail** [comment]
Verified fixed in 10.10. Thank you, nice work!

**Comment by haowen-avail** [comment]
Wait, spoke too soon. The unneeded horizontal scroll bar is gone, but the unneeded vertical scroll bar is still there:

![image](https://user-images.githubusercontent.com/61713110/119415648-dfc8bd80-bca6-11eb-9608-61b3883858a2.png)

**Comment by aardvark-adventurer** [comment]
Looks like we lost the horizontal scroll bar, but there's still that unneeded vertical scroll bar hanging around:
![image](https://user-images.githubusercontent.com/5208744/119415770-261e1c80-bca7-11eb-93bc-4d19a27542b0.png)

**Comment by abnerlee** [comment]
Does it always happen for this md file?

If so, possible to attach the sample md file?

**Comment by haowen-avail** [comment]
Here:
[temp.md](https://github.com/typora/typora-issues/files/6805165/temp.md)
![image](https://user-images.githubusercontent.com/61713110/125373400-f2bc4d80-e339-11eb-95b7-041be9c575c2.png)

**Comment by aardvark-adventurer** [comment]
Looks like it was a Catalina vs Big Sur issue. I upgraded my MacOS and the vertical scroll bars disappeared. Thanks!
