### ISSUE TITLE
Error - This beta version of Typora is expired

### ISSUE THREAD

**Issue by nuxzero** [typora/typora-issues#4365]
Hi 

I encountered with `This beta version of Typora is expired`. I tried to re-install but didn't work. Also, I tried to search for the stable version for macOS but can not found it. I use Typora version 0.10.8 on macOS Big Sur 11.2.3.

![Screen Shot 2564-05-04 at 23 04 58](https://user-images.githubusercontent.com/2638321/117034545-9e8b6080-ad2d-11eb-8608-dffec68b1947.png)

**Comment by abnerlee** [comment]
could you try https://github.com/typora/typora-issues/issues/4357#issuecomment-831257948 and attach the result?

**Comment by keeratita** [comment]
![image](https://user-images.githubusercontent.com/5326774/117603655-dc4d1680-b17d-11eb-9aeb-a408e514820b.png)
