### ISSUE TITLE
[BUG]Garbled text

### ISSUE THREAD

**Issue by BestTracer** [typora/typora-issues#4366]
If your export a markdown file to a PDF in Typora, when you copy Chinese text in this PDF and paste it into other text editors, then you will find that the text you copied is garbled.I uploaded two files to describe the problem in detail。
[BUG.pdf](https://github.com/typora/typora-issues/files/6423183/BUG.pdf)
[BUG.md](https://github.com/typora/typora-issues/files/6423190/BUG.md)

**Comment by abnerlee** [comment]
Which OS?

**Comment by BestTracer** [comment]
> Which OS?

macOS big sur

**Comment by abnerlee** [comment]
should be fixed in latest version
