### ISSUE TITLE
Typora inline math lagging when working with larger files

### ISSUE THREAD

**Issue by Jeffrey-kerson** [typora/typora-issues#4367]
I have recently noticed, that when working with larger files Typora begins to lag (especially when editing inline math equations) and I have to restart the program. Then, the lagging is gone for a few minutes after it starts again and I have to restart the program. It is quite cumbersome to have to restart the program all the time, so I wanted to know whether this might get some fix soon. It's really predominantly the inline math that makes the problems.

Operating system: MacOS Big Sur
Machine: MacBookPro 2018

**Comment by Jeffrey-kerson** [comment]
@abnerlee ok, I have written an email.

**Comment by abnerlee** [comment]
should be improved in 0.11

The large file lagging (not limited to inline math) is addressed in #68
