### ISSUE TITLE
Html code block stop working

### ISSUE THREAD

**Issue by Jerry-star** [typora/typora-issues#4369]
The code block suddenly stopped rendering html while previous html blocks work fine. 

![cap](https://user-images.githubusercontent.com/25629176/117137705-7400dc80-aded-11eb-8cd5-a5c82d97291a.PNG)

When I copy the source code to other editors, I found the broken code block has source code something like this:
![image](https://user-images.githubusercontent.com/25629176/117137642-55024a80-aded-11eb-8356-f963b6f0b56d.png)

This is different from normal code:

![image](https://user-images.githubusercontent.com/25629176/117137794-985cb900-aded-11eb-94de-8584667a5d6b.png)
What can I do ?

**Comment by abnerlee** [comment]
From the screenshot, you are using code fences, not HTML Block.

Code fence is like

~~~
```html
<p>aa</>
```
~~~

HTML Block is like 

```
<p>aa</p>
```
