### ISSUE TITLE
Typo in check updates response

### ISSUE THREAD

**Issue by boldux** [typora/typora-issues#4370]
There's a typo in the title of the message that appears after using Check Updates.
Current [Window Title]: You are **update** to date!
Window title should be: You are up to date!

![image](https://user-images.githubusercontent.com/2817122/117163837-0bd0dd00-ad92-11eb-854e-41697f9cbe50.png)

Repro steps: On the Help menu, click Check Updates. (Install update, if any, and repeat.)

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by boldux** [comment]
@abnerlee, not yet fixed in 0.10.9:
![image](https://user-images.githubusercontent.com/2817122/117690191-947fbc80-b188-11eb-818a-30e5688c0a3e.png)
