### ISSUE TITLE
Cannot insert inline image in list paragraph: text disappears upon using Insert Image

### ISSUE THREAD

**Issue by boldux** [typora/typora-issues#4371]
Lately, when I try inserting an inline image in an ordered or unordered list paragraph, any text that was after the point where I want to insert the image disappears as if the image swallowed it. Sometimes only the last word remains.

This used to work. It seems some recent update (first week of May 2021) broke this feature.

Repro steps:

1. Click inside a paragraph in a list (ordered or unordered).
2. Press Ctrl+Shift+I.
3. Notice all of the text after the insertion point disappears.

This happens in Typora 0.10.7 for Windows, which, according to [the changelog](https://typora.io/windows/dev_release.html) was meant to address this very issue.

**Comment by marcoalopez** [comment]
Same situation here using Typora version 0.10.7 on windows, the text immediately after inserted images partially disappear.

**Comment by abnerlee** [comment]
Will fix this in nest version up.

**Comment by abnerlee** [comment]
should be fixed in latest version
