### ISSUE TITLE
Nothing happens when scrolling the mouse in the code block

### ISSUE THREAD

**Issue by liangjingkanji** [typora/typora-issues#4373]
Nothing happens when scrolling the mouse in the code block 
在代码块中滚动鼠标无反应

**Comment by abnerlee** [comment]
Does trackpad works?
What is the OS and typora theme?
Scroll vertically or horizontally? 
Possible to attach a screen cast?

**Comment by liangjingkanji** [comment]
The trackpad can work, My mouse is Logitech Master3

**Comment by abnerlee** [comment]
> What is the OS and typora theme?
> Scroll vertically or horizontally?

Could you provide above info?

relates #3400

**Comment by liangjingkanji** [comment]
> > What is the OS and typora theme?
> > Scroll vertically or horizontally?
> 
> Could you provide above info?
> 
> relates #3400

1. [Drake Theme](https://theme.typora.io/theme/Drake/)
2. Scroll vertically

**Comment by abnerlee** [comment]
> Drake Theme

Can this be reproduced in built-in themes?

**Comment by liangjingkanji** [comment]
> > Drake Theme
> 
> Can this be reproduced in built-in themes?

Can

**Comment by abnerlee** [comment]
What is the OS?

**Comment by abnerlee** [comment]
may be same with #4465
