### ISSUE TITLE
Display more than 512 files in article view

### ISSUE THREAD

**Issue by joschabach** [typora/typora-issues#4374]
Typora 0.10.8 does currently not display more than about 512 files in the article pane, even when they are distributed over multiple directories. It shows an error ("Selected folders contains [sic] too many files. Please switch to File Tree View for better performance"). Can this be fixed, ideally by grouping the articles (two line previews) using the directory structure?

(I have exported a couple thousand markdown documents from Ulysses representing a larger book and want to continue working with them. They are organized in a folder hierarchy, with about a dozen files per folder.)

**Comment by abnerlee** [comment]
You can switch to file tree view.

**Comment by 1999FordFocus** [comment]
+1 for this request.

The `File Tree View` doesn't meet our needs.
Plus, These two modules target two different usage scenarios. You can not replace the `Articles View` with the `File Tree View`.

**Comment by 1999FordFocus** [comment]
Hi @abnerlee 

Can we reopen this issue? I rely heavily on this feature and need it badly!

**Comment by Louis24** [comment]
哈哈哈2024还没解决呢
