### ISSUE TITLE
Feature request: Sort files by creation date, allow user to manually change order of files

### ISSUE THREAD

**Issue by joschabach** [typora/typora-issues#4375]
I am trying to switch from Ulysses to Typora for writing a book. I have exported a couple thousand .md files in a directory structure and want to continue working with them. However, Typora only offers to sort the files alphabetically or by date of last change, not by the order in which they are going to appear in the book. I would either have to number the two thousand files (alphabetic/'natural' ordering), and change the numbering whenever the order of sections in the book changes, or see the order changed every time I touch a file (last modified ordering).

The best solution might be if Typora allows the user to change the order by drag and drop in the file and article view, and remembers that order.

This can be achieved in four ways:
- introducing an index file, as an additional file per directory (which is probably breaking the philosophy of Typora)
- add a sorting prefix to the filename, which is automatically updated for all files in the directory each time the user changes the order (that method is adds Typora specific conventions to files, which is probably unwanted)
- store the user's sort order in Typora's ~/Library/Application Settings (makes synchronization more difficult)
- use the user defined sort order features of the file manager (might make synchronization difficult)

Benefits of an index database would also be that symbols could be assigned to each folder, like Ulysses does, and which is very helpful for visually organizing documents

In the meantime, it would be great if files could be sorted by creation order (not just modification order).

**Comment by abnerlee** [comment]
duplicated with #3655

We could prefer making a `.typora` folder stores the index data
