### ISSUE TITLE
Math Block Font Size

### ISSUE THREAD

**Issue by eykaraduman** [typora/typora-issues#4376]
Hi,
After updating Typora, math block font sizes appear smaller than inline math font sizes in exported pdf.
I add,
`.MathJax_SVG {
font-size: 120% !important;
}`
in css file, but nothing changed in exported pdf.
How can i change math block formula font-size?
![image](https://user-images.githubusercontent.com/18639821/117252403-937c2180-ae4e-11eb-8ca1-694b8d3556ff.png)

**Comment by abnerlee** [comment]
relates #3662

Hot fix would be to disable auto numbering for math

**Comment by eykaraduman** [comment]
> relates #3662
> 
> Hot fix would be to disable auto numbering for math

Thanks. After removing equation tags it worked as excpected. But these are necessary for my document. I hope it will be fixed as soon as possible.

**Comment by abnerlee** [comment]
duplicated with #3662
