### ISSUE TITLE
image enhancement

### ISSUE THREAD

**Issue by CoderPike** [typora/typora-issues#4378]
I wanna make some customization of typora. Usually we can finish the job by writing some css in xxx.user.css. However, it's not easy to add a description to an image. I know someone sugguests by adding html code like `<center>description</center>` under the image, but I don't like it, how perfect if it auto displays the title or alt as it's figcation and we control the display effect by css.

I have tried by editing frame.js. however, not fully successful. The file frame.js is compressed, it's better to get an uncompressed verson of the file. Thus I can study it and make more customization. My email is at 163.com with the name of firmap and I sent one to hi at typora.io yesterday. Thank you.

**Comment by abnerlee** [comment]
may duplicated with #249

There's no markdown syntax for this. You might use css `attr(alt)` to make one.

Or use HTML like (https://github.com/typora/wiki-website/blame/gh-pages/_posts/2019-01-24-Copy%20and%20Paste.md#L70)

We will also consider provide one option in future

**Comment by CoderPike** [comment]
@abnerlee Thank you for your answer. It's really a good idea to use css attr(alt) to finish the job if img tag supports ::after or ::before.  Unfortunately it doesn't.

**Comment by CoderPike** [comment]
@abnerlee Thank you for your answer. It's really a good idea to use css attr(alt) to finish the job if img tag supports ::after or ::before.  Unfortunately it doesn't.

**Comment by abnerlee** [comment]
The best solution should be to "support by typora", which is covered in #249

For current hack, hmm.. if img tag does not support ::before or ::after, then use its parent `.md-image`. And if you change image to "display:block", I guess it may get ::before or ::after supported (not verified).
