### ISSUE TITLE
[BUG] typora upload image twice when using PicGo

### ISSUE THREAD

**Issue by Molunerfinn** [typora/typora-issues#4379]
![image](https://user-images.githubusercontent.com/12621342/117336329-ab938580-aece-11eb-9995-e2c3fbec7f43.png)

reproduce:

use picgo-2.3.0.beta.6, see the picgo.log, when dragging an image or pasting an image to typora, typora will send upload request twice.

It will cause one of the request failed, and typora can't replace the image url anymore.

typora version: v0.10.7(beta)

update:

downgrade to v0.9.98 resolve this problem

**Comment by abnerlee** [comment]
should be fixed in latest version
