### ISSUE TITLE
Add third-party plugin support

### ISSUE THREAD

**Issue by gavinhughes** [typora/typora-issues#4380]
There is a long and growing list of [people asking for a vim keybinding feature](https://github.com/typora/typora-issues/issues/187). I think the more important enhancement is third-party plugin support, similar to that provided by [Obsidian](https://obsidian.md) and others. This would enable the community to build their own enhancements as plugings, including vim keybindings, and free the core Typora team to focus on other features.

**Comment by abnerlee** [comment]
#162
