### ISSUE TITLE
Typora doesn't recognize special character "【】"as link-address

### ISSUE THREAD

**Issue by pzh200707** [typora/typora-issues#4381]
When I drag the file with "【】" in its name into Typora or manually type "【】" in link-address to create a hyperlink.
"【】" in link-address would be automatically switched to "[]", which makes the hyperlink invalid.

I feel that this is not quite a rare character for Chinese users. Is there any way to fix it? Thank you.

**Comment by abnerlee** [comment]
You could uncheck Edit -> Smart Punctuation -> Remap Unicode Punctuation on Parse

**Comment by pzh200707** [comment]
> You could uncheck Edit -> Smart Punctuation -> Remap Unicode Punctuation on Parse

This is already unchecked.

**Comment by abnerlee** [comment]
should be fixed
