### ISSUE TITLE
language dropdown for code blocks broken in 0.10.7 (autocompletion)

### ISSUE THREAD

**Issue by pylgrym** [typora/typora-issues#4382]
Since version 0.10.7 arrived a few days ago,
the right-hand language-type field on code blocks no longer appears to auto-complete.
You can still type the language marker manually, but you don't get the 
auto-completion match drop-down.
  I have typora installed on multiple machines (>5), and the feature
appears to break consistently once 0.10.7 is installed.
  Strangely, I believe I saw it still work ONCE in one of the cases, 
but I'm not sure - possibly that machine was not upgraded.

It's a minor thing, as you can still type it manually. But the auto-completion
is a great security that you have specified the language marker correctly.
  Other than that, typora is the greatest thing since sliced bread.

**Comment by abnerlee** [comment]
should be fixed in latest version
