### ISSUE TITLE
The emoji candidate list that appears by scrolling with the mouse cannot be clicked and entered quickly 

### ISSUE THREAD

**Issue by sheldonxxd** [typora/typora-issues#4387]
os: win10
typora version: 0.10.9(beta)
theme: github

question: The emoji candidate list that appears by scrolling with the mouse cannot be clicked and entered quickly . Another small problem is that when the cursor is at the beginning of the paragraph, the emoji candidate list will not appear when scrolling the mouse. 

![typora_emoji_candidate_list_bug](https://user-images.githubusercontent.com/42539486/117920847-3e468100-b322-11eb-9cd8-b45a3c55df9c.gif)

**Comment by abnerlee** [comment]
should be same issue come with #4395
