### ISSUE TITLE
Shortcut In German Language File For Source Code Mode Not Correct

### ISSUE THREAD

**Issue by userofgithub023897** [typora/typora-issues#4389]
Keyboard shortcut in German language for source code mode in menu is not correct.

**Current entry:**
`Darstellung (V) --> Quellcodemodus (Strg + /)`

**New entry:**
`Darstellung (V) --> Quellcodemodus (Strg + #)`

**Comment by abnerlee** [comment]
relates #4273

**Comment by abnerlee** [comment]
relates #753 #3557

**Comment by abnerlee** [comment]
put into #4273
