### ISSUE TITLE
typora does not work properly after cleaning temporary files on ubuntu

### ISSUE THREAD

**Issue by TAN-ZIXUAN** [typora/typora-issues#4390]
I don't know what caused this. I just cleaned the temp files and then my typora cannot work properly. I tried to uninstall and reinstall it and it still behaves weird.
![image](https://user-images.githubusercontent.com/56602039/118029828-654c8500-b319-11eb-9f3b-bfe3cb209373.png)

**Comment by abnerlee** [comment]
I don't know why removing temp files will affect the UI, but try with another theme?

**Comment by TAN-ZIXUAN** [comment]
> I don't know why removing temp files will affect the UI, but try with another theme?
Hi,  Where is the theme folder located in Ubuntu? I could not click the `open theme folder` button because the whole UI is missing.

**Comment by TAN-ZIXUAN** [comment]
> I don't know why removing temp files will affect the UI, but try with another theme?

You're right! it only happens to the particular theme. I switch to some default theme and it works properly now

**Comment by abnerlee** [comment]
You can click "open theme folder" after switch to default theme.

I guess the temp folder you delete may include typora's folder which contains the theme you use.
