### ISSUE TITLE
[Bug] Poor support for <details><summary>

### ISSUE THREAD

**Issue by Taswen** [typora/typora-issues#4391]
I think it‘s a bug.

In addition to the standard, markdown can support some extended syntax.
But even if strict mode is not enabled, the following text still parses incorrectly.
```html
<details>
<summary>Logging Handler</summary>

You can also use the builtin [Handler class](https://rich.readthedocs.io/en/latest/logging.html) to format and colorize output from Python's logging module. Here's an example of the output:

![Logging](https://github.com/willmcgugan/rich/raw/master/imgs/logging.png)

</details>
```
> Code From：[repository `rich`](https://github.com/willmcgugan/rich#readme)

The correct parsing effect is as follows, which is also supported by GitHub

<details>
<summary>Logging Handler</summary>

You can also use the builtin [Handler class](https://rich.readthedocs.io/en/latest/logging.html) to format and colorize output from Python's logging module. Here's an example of the output:

![Logging](https://github.com/willmcgugan/rich/raw/master/imgs/logging.png)

</details>

**[Related Info]** 
**System**: windows
**Version**: 0.10.9

**Comment by abnerlee** [comment]
duplicate with #1581

relates #1939
