### ISSUE TITLE
markdown image upload fail

### ISSUE THREAD

**Issue by Ocean0000** [typora/typora-issues#4392]
cat‘t use the function of upload all images though hot key

**Comment by abnerlee** [comment]
what kind of error, could you provide more details?

**Comment by Ocean0000** [comment]
new i use old version（0.9.98）image upload function is ok
this is error notice
![image](https://user-images.githubusercontent.com/60163300/118138522-0716c380-b439-11eb-8e8c-8b9366379692.png)

**Comment by abnerlee** [comment]
same with #4379?
