### ISSUE TITLE
Restricted permission after changing .md file's icon

### ISSUE THREAD

**Issue by rturquier** [typora/typora-issues#4393]
Hi!

I've set a custom icon (icns) to a .md. After doing that, Typora is apparently unable to write to this file: when I try to save, it says that I don't have the required permissions. When checking the file info, I still have read and write access.

Error message (translated from German):
> **The document "Document name" could not be saved. The file is protected.**
> Do you want to save it anyway?
> [save anyway / cancel]

If I click on [save anyway], I get:
> **You don't the access rights to save file "Document name" in folder "Folder name".** 
> To show or edit access rights, select file in Finder and choose "File" > "Information".
> [OK]

I'm using macOS 10.15.7 and Typora 0.10.8. 

To reproduce:
- create and save file with Typora
- in the Finder, show file information
- drop an icns file on the icon next to the file name, at the top of the information window
- go back to Typora
- edit the file and try to save it
- if it works, make another edit, and try to save again

Thanks for your great work!

**Comment by abnerlee** [comment]
Confirmed. But this should be a bug of macOS, since the save process is partly managed by the system.

You can replace Typora with "TextEdit.app" in your "step to reproduce" and same error will happened.
