### ISSUE TITLE
Yaml block not recognized with ending with three dots `...`.

### ISSUE THREAD

**Issue by JohnLukeBentley** [typora/typora-issues#4394]
I suggest adding support for yaml blocks ending with three dots `...`.

Typora currently recognizes yaml blocks that end (and start) with dashes `---`. In presentation mode (not source code mode) the yaml block is correctly presented as a code block, and markdown content outside the yaml block is formatted as expected.

However, if a yaml block ends with three dots `...`, the yaml block is not terminated. In presentation mode the rest of the markdown content looks like it remains part of the yaml block.

The problem arises for me in virtue of my using Pandoc markdown

https://pandoc.org/MANUAL.html#metadata-blocks
> A YAML metadata block is a valid YAML object, delimited by a line of three hyphens (---) at the top and a line of three hyphens (---) or three dots (...) at the bottom.

The [Yaml spec, "2.2. Structures"](https://yaml.org/spec/1.2/spec.html#Preview) has the following slightly confusing stipulation ...

> YAML uses three dashes (“---”) to separate directives from document content. This also serves to signal the start of a document if no directives are present. Three dots ( “...”) indicate the end of a document without starting a new one, for use in communication channels. 

...  but "Example 2.8.  Play by Play Feed from a Game" seems to make clear that three dots `...` can end a block.

**Comment by abnerlee** [comment]
yes, seems also valid in jekyll: https://github.com/jekyll/jekyll/pull/3134

**Comment by abnerlee** [comment]
should be fixed

**Comment by JohnLukeBentley** [comment]
Can confirm fixed in 0.11.0. 

Thanks!
