### ISSUE TITLE
Emoji popup appears randomly when text is focused

### ISSUE THREAD

**Issue by otav-o** [typora/typora-issues#4396]
- Emoji suggestion should appear only with `:emoji-name:`
- I've checked and theme is not the problem
- Even with focus mode (F9) disabled, it occurs
- Version: 0.10.9 (beta), Windows 10

![2021-05-13 21-49-34](https://user-images.githubusercontent.com/60331508/118204760-52c76e00-b435-11eb-8535-07c6696d091e.gif)

**Comment by hbsmith** [comment]
Just started for me as well.

**Comment by PsyGik** [comment]
Same issue on Mac, Version 0.10.9 (5330). 

- Place cursor anywhere.
- Scroll the page, 
- Emoji popup appears.

![typora](https://user-images.githubusercontent.com/5432911/118303012-9045fd00-b502-11eb-88d0-155e35e72cc3.gif)

**Comment by abnerlee** [comment]
should be fixed
