### ISSUE TITLE
Typora Win10 start menu light theme tile issue

### ISSUE THREAD

**Issue by JolyonJostar** [typora/typora-issues#4398]
Hi Typora team

There is a wired issue about Typora tile when the light theme is on, the tile still using dark background, I found that you already add the VisualElementsManifest , but still don’t work.
I heard a strange start menu feature : If you using a white icon with the light theme, the tile will force using dark tile.
So I try to change the .ico to a black, and it works!
![图像 18](https://user-images.githubusercontent.com/61088063/118258200-2b7aaa80-b4e2-11eb-9b36-f39a69652d8c.png)
So to fix the issue,you can prepare two sets of icon, light and dark, and sync to the system,like this app:
![组 10](https://user-images.githubusercontent.com/61088063/118258392-5e24a300-b4e2-11eb-8d23-a1f8c3f5d86f.png)

reference:
https://github.com/JasonStein/Notepads

**Comment by abnerlee** [comment]
relates #4292

But how to switch to that "super" light theme? In my test, the light theme still uses "theme color" which is darker than expected.

![image](https://user-images.githubusercontent.com/1621242/120289600-0ebce000-c2f4-11eb-9a8a-7ec52a306c37.png)

What's your Windows 10 version, BTW?

**Comment by JolyonJostar** [comment]
> relates #4292
> 
> But how to switch to that "super" light theme? In my test, the light theme still uses "theme color" which is darker than expected.
> 
> ![image](https://user-images.githubusercontent.com/1621242/120289600-0ebce000-c2f4-11eb-9a8a-7ec52a306c37.png)
> 
> What's your Windows 10 version, BTW?
looks like you are still using the old win10 version?
they [refresh the start menu](https://www.youtube.com/watch?v=t0eeuseOL1I) in Windows 10 20H2 with a uniform and partially transparent background for the tiles 
![8694a4c27d1ed21bbabfc3a46646a1c351da3f29](https://user-images.githubusercontent.com/61088063/120323828-8270e400-c318-11eb-9159-d223eb2bcfd2.jpeg)

so the issue is different from #4292,because the VisualElementsManifest.xml won't work after 20H2,the background color depend on the icon color before system theme, it makes sense because all white icon hard to read on light mode,but break the whole start menu

there are two way to fix it,
1、 using 2 sets of icon like i mentioned , but i don't know coding so all i can do is share the link,
2、 draw a new icon with more color and contrast，i draw many versions,
![微信图片_20210601205043](https://user-images.githubusercontent.com/61088063/120326211-117efb80-c31b-11eb-92b5-03b050362f4b.png)

and some of them work both dark&light mode
![自定义大小 – 1](https://user-images.githubusercontent.com/61088063/120326669-8e11da00-c31b-11eb-9bed-c6e004bfc9e5.png)

this is the one which i finally choose,not beautiful enough but it works well 
![0033](https://user-images.githubusercontent.com/61088063/120326847-bc8fb500-c31b-11eb-9e07-d993e9c827be.png)

**Comment by datafj** [comment]
Thanks for raising the issue! I asked the question in  #4292, but I am having this problem again on my newly installed Windows 10. Typora and Google Chrome are the only ones having the tile color different to others.

**Comment by JolyonJostar** [comment]
> Thanks for raising the issue! I asked the question in #4292, but I am having this problem again on my newly installed Windows 10. Typora and Google Chrome are the only ones having the tile color different to others.

chrome is a little bit different from typora‘s,typora is all white around the icon so system default set it a dark background,but chrome is colorful 
the fact is  google do put a gray background color on chrome's icon,so the solution is erase the gray background color
![Logo](https://user-images.githubusercontent.com/61088063/122063930-44e57e00-ce23-11eb-8fde-430d6dc90b87.png)
here are all the chrome icons with transparent background,I erase the color by photoshop
[chrome icons.zip](https://github.com/typora/typora-issues/files/6656038/chrome.icons.zip)
just simply replace them to
C:\Program Files (x86)\Google\Chrome\Application\91.0.4472.106\VisualElements

BUT,everytime chrome updates,those gray background always come back,so before google notice,my solution is switch to microsoft edge😋
![image](https://user-images.githubusercontent.com/61088063/122065693-ba058300-ce24-11eb-878e-0d8a7996bf07.png)

**Comment by JolyonJostar** [comment]
update：it's ok with windows11
![image](https://user-images.githubusercontent.com/61088063/124134690-a9f0d300-dab5-11eb-9c9e-d32bf403ba94.png)

**Comment by abnerlee** [comment]
should be fixed
