### ISSUE TITLE
Undocumented keyboard shortcuts in code/math blocks clashing with my keyboard layout

### ISSUE THREAD

**Issue by Nicolapps** [typora/typora-issues#4399]
It looks like there are some undocumented keyboard shortcuts (that are maybe provided by an external library used in Typora?) that are only active in code/math blocks (everything works fine outside).

By undocumented, I mean that they are not in the [Typora documentation](https://support.typora.io/Shortcut-Keys/), and not in the app menu bar either.

The issue is that it prevents me to type some symbols, that are mapped in the system keyboard layout to the same keys. Moreover, there are already other OS-wide shortcuts to do the same actions (e.g. ⌥←, ⌥⇧←, ⌥⌦, etc.), so these shortcuts are useless.

The undocumented key combinations are:

* ⌥B (which moves the cursor one word backwards),
* ⌥D (which deletes the next word),
* ⌥F (which moves the cursor one word forwards),
* the same shortcuts with ⇧ (which do the same but with selection).

**Steps to reproduce**
1. Open a new Typora document.
2. Create a code block (\```…```) or a math block (`$$…$$`).
3. Press one of the key combinations above (e.g. ⌥D)
    * *[Expected]* The character of the keyboard map to the combination is typed (e.g. ∂).
    * *[Actual]* An other action is performed (e.g. the next word is deleted).

**Typora/OS version**
I’m using Typora Beta 0.10.9 on macOS Catalina. The keyboard layout I’m using is Swiss French, but it looks like the same issue happens with other layouts.

**Comment by abnerlee** [comment]
should be fixed

**Comment by Nicolapps** [comment]
Many thanks!
