### ISSUE TITLE
Non-breaking space after pasted text

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#44]
When pasting a piece of text, a word or an url, Typora replaces the preceding whitespace with non-breaking ones. While it actually might be quite nice with urls, it should be left for the users discretion. If there's no whitespace before the pasted content, nothing happens.

Illustration:

```
This is normal content with nothing pasted.
The words preceding this•are pasted.
Many preceding spaces after this••••lead to many replacements.
```

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/41
