### ISSUE TITLE
after YAML front matter, input Chinese(first word) and the cursor auto-jumps to end of front matter

### ISSUE THREAD

**Issue by Hercules11** [typora/typora-issues#4401]
![report-bug-typora](https://user-images.githubusercontent.com/43318823/118374387-50b1fc00-b568-11eb-88a1-1509c90e91a5.gif)

就是说，在 YAML Front Matter 后，输入中文，光标自动跳转到 Front Matter 后
操作系统：Windows 10
软件版本： 最新版

**Comment by abnerlee** [comment]
#3318
