### ISSUE TITLE
Debian package should suggest `pandoc`

### ISSUE THREAD

**Issue by Tachi107** [typora/typora-issues#4403]
When trying to export a document in LaTeX, Typora looks for the `pandoc` executable, and aborts with a warning if it can't be found. Since Debian and derivatives provide the `pandoc` package, `typora` should suggest or recommend the appropriate package, so that users know what to install.

Edit:
Suggested packages are just listed when running `apt show packagename`, and do not alter the installation procedure by default (but only when using the `--install-suggests` option). On the other hand, recommended packages get installed by default, but do not cause installation issues when they cannot be found.

**Comment by abnerlee** [comment]
should be fixed
