### ISSUE TITLE
Allow toggling "light/dark mode" within Typora app

### ISSUE THREAD

**Issue by cariehl** [typora/typora-issues#4404]
As a Windows user, I keep my system's theme set to "light mode" due to some apps not respecting "dark mode" properly. However, I prefer using "dark mode" on a per-app basis whenever possible.

It would be great if Typora had an option to switch between "light mode" and "dark mode" directly within the app, so that I could enable "dark mode" without having to change my system-wide setting.

**Comment by abnerlee** [comment]
You can just switch to a dark theme in Typora

**Comment by cariehl** [comment]
> You can just switch to a dark theme in Typora

This is not a valid solution for some themes. In particular, I am using this [Fluent theme](https://github.com/HereIsLz/Fluent-Typora) which has styling for both "light mode" and "dark mode". The "dark mode" styling relies on media queries to detect if Typora is running in dark mode.

Currently, the only ways for me to use this theme's "dark mode" styling are:
1. Change my Windows system preferences. This will have an effect on apps other than Typora, so I would rather not use this solution just to change something within Typora.
2. Manually rewrite the theme myself so that the "dark mode" styling is the default. I'm sure I could manage this, but users shouldn't be required to mess with a theme's CSS just to switch to its "dark mode" version.

I don't know how Typora works under-the-hood, but I know that modern browsers can toggle between "light mode" and "dark mode" without requiring the user to change their operating system preferences. Additionally, I've used other web-based apps that offer this functionality, so it certainly seems possible.

I understand this may not be a high priority issue, and that's fine. But your proposed solution won't work for my scenario, and it seems like other users may run into the same scenario. I would ask that you re-open this issue and at least consider adding a feature to resolve it.

**Comment by abnerlee** [comment]
> It would be great if Typora had an option to switch between "light mode" and "dark mode" directly within the app

> but I know that modern browsers can toggle between "light mode" and "dark mode" without requiring the user to change their operating system preferences.

In Typora' case, user can change theme. It will be a bug if user change light/dark mode, but nothing happened (because theme does not support dark mode). 
In your case, you can just duplicate the Fluent theme, then set body's background to dark color via custom CSS.
