### ISSUE TITLE
Different tabs are used when pressing Tab or when pressing Enter in a code block

### ISSUE THREAD

**Issue by jekyllgrim** [typora/typora-issues#4406]
When typing in a code block (at least in C#), pressing Enter automatically indents the first string. However, it'll be indented with _spaces_. If you manually go to the start of a line and press Tab, you'll get an actual tab, not a string of spaces. The result is visibly different indentation.
![image](https://user-images.githubusercontent.com/42670463/118624364-c371e000-b7d1-11eb-83df-e6547d68e4ef.png)

**Comment by abnerlee** [comment]
For auto generated indent, it follows same indent setting in Preferences Panel -> Editor -> Indent Size on Save

Manually input one will be kept as-is.

**Comment by abnerlee** [comment]
#579
