### ISSUE TITLE
How to make images wider than the write area?

### ISSUE THREAD

**Issue by Shen897** [typora/typora-issues#4408]
Images max-width are the same as the max-width of `#write` area, that make it painful to read high-resolution images ( for example: biology, math and computer science notes) included in notes, high-resolution images look blurry, also the images in the exported PDF look even more blurrier.  
I don't want to make `#write` area max-width take the full screen but I want to make images not restricted to it. 
![typora-ex - Copy](https://user-images.githubusercontent.com/66660101/118726217-affa5f80-b839-11eb-92ac-53cc29689b08.png)
 
As you can see in this example, the red box is  `#write` area, I want the image to be as wide as the green box or maybe a bit wider.

**Comment by Shen897** [comment]
After fiddling with typora's css, I found `img` which allow me to manipulate images properties on typora, I made the width of `img` 1200% (and #write is 900px). 

![typora-ex2 - Copy](https://user-images.githubusercontent.com/66660101/119138953-25894a00-ba4b-11eb-964a-ee5e27e17c18.png)   

But the image only become wider on the right side, see image above:

**Comment by abnerlee** [comment]
You can add "margin-left".
