### ISSUE TITLE
Updates delete all clipboard-pasted images on Linux

### ISSUE THREAD

**Issue by fjnn** [typora/typora-issues#4410]
I realized that sometimes some images are gone but I didn't put attention since they were not vital back then. I thought I accidentally moved the folder so the path has change.

But in fact, the problem was bigger. Recently I used Typora excessively and I have updated a newer version a few days ago. Now, most of my images are gone through the all this excessively-used period. 

While I was trying to restore those images, I found out that the only images are gone are the ones which I pasted using `Ctrl-C` and `Ctrl-V` . The path is something like that: `![image-20210509173523448](/home/user/snap/typora/33/.config/Typora/typora-user-images/image-20210509173523448.png)` and when I checked the folder ../33, it was missing. ../36 and ../37 are there. Apperantly, with a new update, the older files are deleted.

Unfortunately, there is not a **Preferences** option on the Linux version like in macOS. It looks like one can change the relative path for the clipboard-paste images [as explained here](https://support.typora.io/Images/). I am using the snap version which I installed through the software center on my Ubuntu 18.04 machine.

So, two questions here:
1) Can I restore my lost images somehow?
2) Can I change the default path for clipboard-images on Linux version?

**Comment by abnerlee** [comment]
Seems a `snap` spec / thing. Currently snap is not officially supported by us.

But please check https://forum.snapcraft.io/t/removing-a-snap-also-removes-its-matching-users-configuration/17890/3 about their spec.

> Unfortunately, there is not a Preferences option on the Linux version like in macOS.

It should have, please also check if you are using the latest version or not.
