### ISSUE TITLE
How to customize context menu items？

### ISSUE THREAD

**Issue by actforjason** [typora/typora-issues#4411]
How to customize context menu items？Some items don't need. Shortcut keys are easy to achieve aims. So how can I delete these items (as "Search with Google" does in conf.user.json)？
![image](https://user-images.githubusercontent.com/57058325/118776942-1d020980-b8bb-11eb-822d-13b8911ab5dd.png)

**Comment by actforjason** [comment]
> C:\Program Files\Typora\resources\appsrc\window\frame.js

这里可以修改

**Comment by abnerlee** [comment]
https://support.typora.io/Add-Search-Service/

**Comment by actforjason** [comment]
我的意思是把复制粘贴那些去掉，因为一般都用快捷键，去掉可以简洁些，像这样：
![image](https://user-images.githubusercontent.com/57058325/119245897-55516280-bbaf-11eb-85e1-d0b28cfde20e.png)
