### ISSUE TITLE
[Bug]Searching for Chinese characters in the folder doesn't work properly on macOS , but it works in the document

### ISSUE THREAD

**Issue by relaxbao** [typora/typora-issues#4414]
![image](https://user-images.githubusercontent.com/19773804/118913133-7ae62e00-b95b-11eb-9bc6-ab85881f8224.png)![image](https://user-images.githubusercontent.com/19773804/118913339-d9aba780-b95b-11eb-94f5-f9471f5abc1d.png)

if I search Chinese characters in the folder , it doesn't work ,but if I secret the English words , it does works !

is it a bug ? or should I change some settings ? 

thank  you so much

**Comment by abnerlee** [comment]
which version?

**Comment by relaxbao** [comment]
> which version?
my typora's version is 0.10.9， my mac's version is 10.15.7.

I love typora so much , I really hope it can be solved , thank you ~

![image](https://user-images.githubusercontent.com/19773804/119457717-92b01e80-bd6e-11eb-842d-bbf5da469204.png)

![image](https://user-images.githubusercontent.com/19773804/119457835-b07d8380-bd6e-11eb-89d1-d6febd822e2d.png)

**Comment by abnerlee** [comment]
In my test, I can search files contains Chinese successfully.

Could you provide the sample file? if you copy "包" from the sample file and search, will it work?

Does the folder located in netdriver or contains some special character?

**Comment by hyzgh** [comment]
@abnerlee I have a similar issue. I have a file with content "练习听力". I could find this file by search "练习听力", but I couldn't find it by search "练习".
