### ISSUE TITLE
Typewriter mode status indicator

### ISSUE THREAD

**Issue by JohnLukeBentley** [typora/typora-issues#4416]
I suggest that the typewriter mode status be indicated somewhere (in the main editor) e.g. as an icon in the status bar.

**Comment by abnerlee** [comment]
Typewriter mode can be determined by users even without the indicator.

If the icon is to switch to on / off, when now Typewriter mode can be accessed from menu from all distributions starting from 0.11

So I wonder if there is still needs for this. I will consider if more users supporting this.

**Comment by JohnLukeBentley** [comment]
With 0.11.0 I now see the relevant tickmark (if on) against Typewrite mode in the view menu. Also for focus mode. 

That's certainly an improvement (I haven't used Typora for a while so I can't recall the absence of those tickmarks) and good to have. Great stuff, and thanks.

But my suggestion remains for the reason that opening up the menu is user-experience costly compared to some other (additional) immediate status indiction (E.g. an icon in the status bar). The desire is to, at a glance, tell whether typewriter mode is operational or not.

If that's not persuasive then no worries at all. Overall the user-experience/user-interface you've created to this point is clever and compelling.
