### ISSUE TITLE
提供更好的HTML支持，如float元素的支持

### ISSUE THREAD

**Issue by yfzhao20** [typora/typora-issues#4417]
当前HTML几乎全部以代码块的形式存在，可能存在一些问题

比如：如果我在css中加入

```
.note{
    font-family:'LM Roman 10','Times New Roman',Arial,'Source Han Serif',simsun,sans-serif;
    font-size: 11.6pt;
    float: right;
    clear: both;
    /* border-radius: 3px 3px 3px 3px ;  */
    border-left: 2px solid #0e78cf;
    padding: 1px 10px 1px 10px ;
    max-width: 4.5cm;
    margin-left: 10px;
  }
```

然后在文章中写入：
```
<div class="note">markdown</div>
```

在vscode中，使用markdown preview enhanced的显示效果：

![image](https://user-images.githubusercontent.com/80528249/119119914-44450c00-ba5e-11eb-9f78-9864760194f7.png)

文字浮动到了右侧，不占用正文空间。

在Typora中的显示效果：

![image](https://user-images.githubusercontent.com/80528249/119120079-7191ba00-ba5e-11eb-98b2-dbd1df80bd96.png)

效果差了些，自定义的”note“类没有起作用。有什么解决办法吗？

**Comment by abnerlee** [comment]
We do not have plans to support float. The content will jump when previewing it and editing it.
