### ISSUE TITLE
Search engines other than Google 

### ISSUE THREAD

**Issue by glocalglocal** [typora/typora-issues#4418]
Being able to use a search engine other than (or in addition to) Google would be good. Many people won't use Google, and in some countries it's not even the obvious choice or available.

**Comment by Shen897** [comment]
You can already do that, go to `file` -> `Preferences` -> `Open Advanced Settings` open `conf.user.json` with text or code editor and edit google to duckduckgo for examble

![1 - Copy](https://user-images.githubusercontent.com/66660101/119227476-bc6f0880-bb16-11eb-94cd-dbb94c6ff26b.PNG)
to 
![2 - Copy](https://user-images.githubusercontent.com/66660101/119227492-cabd2480-bb16-11eb-8747-c73432aef385.PNG)
and restart typora.

the end result is 
![3 - Copy](https://user-images.githubusercontent.com/66660101/119227525-fa6c2c80-bb16-11eb-854c-c3ce9d0b544e.PNG)

**Comment by glocalglocal** [comment]
Many thanks. I replaced Google with four engines, and Typora even creates a nice submenu. And while I was at it, I realised I could switch on hiding the menu bar for extra minimalism until I press Alt, which would be my next request. 

I think these options should not be hidden away in Advanced Settings.

**Comment by abnerlee** [comment]
https://support.typora.io/Add-Search-Service/

relates #4411
