### ISSUE TITLE
TOC not formatted properly?

### ISSUE THREAD

**Issue by ntjess** [typora/typora-issues#4419]
It could be that I'm not generating it correctly. Making a TOC using the `Paragraph > Table of Contents` makes a `[TOC]` at the desired location -- this isn't portable to some markdown flavors (e.g. Gitlab, for my use case). Instead, Gitlab recommends `[[_TOC_]]` (which Typora seems to support as well). Is it possible for this to be the default? Or, is Gitlab using an outdated / niche flavor?

**Comment by abnerlee** [comment]
duplicated with #1202

But `[[_TOC_]]` is also supported in typora.

**Comment by ntjess** [comment]
I might recommend making it known to the user that not all markdown formats will conform to this default. Typora has been fantastic so far, but the default viewer simply displays the table of contents with hyperlinks and the user will likely not be aware this will not display everywhere (unless they are already familiar with some markdown intricacies).

Something like a popup for the first TOC generation using the button that says "not all flavors support this TOC format".

I think if they type `[TOC]` themselves it should behave as normal, but I would want to know about potential discrepancies when pressing a button, especially if all other "Paragraph" features are universally supported and there's no reason to be suspicious.

Other than this Typora has been a blast to use and is far better in my book than any other markdown preview tool I've tried. Well done!
