### ISSUE TITLE
Indent after headings

### ISSUE THREAD

**Issue by psvm2020** [typora/typora-issues#4420]
大小标题都缩进 这样小段落之间看起来比较清晰 但每次保存了重新打开文件 缩进自动都没了

**Comment by abnerlee** [comment]
```
# AAA
#   AAAA
```
Those are identical in markdown.

**Comment by abnerlee** [comment]
change the way how headings are rendered while editing may prevent the misunderstanding.

So put this issue to #4739 instead.
