### ISSUE TITLE
After updating to version 0.10.11 every time I open typora it tell me a new version available even though I update it to the latest version

### ISSUE THREAD

**Issue by Shen897** [typora/typora-issues#4421]
So today typora notified me that a new version is available. `New version available. Latest version is 0.10.11, your version is 0.10.10
`. After I update it successfully to the Latest version, evertime I open typora it tell me I'm on version 0.10.10 and need to update Latest version 0.10.11.

here you can see the update notification 
![t1 - Copy](https://user-images.githubusercontent.com/66660101/119247109-c2ed9680-bb8f-11eb-8eb9-2f6100bcb2cf.png)

I installed the update 
![t2 - Copy](https://user-images.githubusercontent.com/66660101/119247103-c08b3c80-bb8f-11eb-9c25-dfbc770a3151.PNG)
![t3 - Copy](https://user-images.githubusercontent.com/66660101/119247104-c123d300-bb8f-11eb-942d-e5f0e023f366.PNG)
 
I update it successfully to the Latest version 0.10.11 as you can see
![t4 - Copy](https://user-images.githubusercontent.com/66660101/119247105-c1bc6980-bb8f-11eb-8511-fc83f8a46de9.PNG)

But when I reopen typora it tell me I'm on version 0.10.10 and need to update Latest version 0.10.11.
![t6 - Copy](https://user-images.githubusercontent.com/66660101/119247108-c2550000-bb8f-11eb-95bb-b687d9c0b419.PNG)

And the `about` window tell me I'm still on version 0.10.10 even though I update it successfully to the Latest version 0.10.11
![t5 - Copy](https://user-images.githubusercontent.com/66660101/119247107-c1bc6980-bb8f-11eb-83c4-8aa4258e04a7.PNG)

**Comment by abnerlee** [comment]
may relates #4334

Could you confirm if you have only one Typora instance been installed?

**Comment by Shen897** [comment]
After reading #4334 and Investigate a bit further I'm sure it's related. 

I installed it for my current user only [install for me only] instead of all users on the PC, so the installation was on `C:\Users\ThisPC\AppData\Local\Programs\Typora` but after the update it install the new version on `C:\Program Files` instead of `C:\Users\ThisPC\AppData\Local\Programs\Typora`. typora does not honor the previous installation location.   

The fix for me was to install typora for all users to avoid this problem in future updates. probably it's better to remove [install for me only] option upon install or implement a check for typora location to find if it's installed on "AppData\Local\Programs\Typora" or "C:\Program Files"

**Comment by abnerlee** [comment]
I see, I will put into #4334
