### ISSUE TITLE
invalid key resource URL '/tmp/apt-key-gpghome.HpD9j9eE1L/home:manuelschneid3r.asc.gpg'

### ISSUE THREAD

**Issue by yekaizhou** [typora/typora-issues#4422]
Hello,
I cannot update typora. When I run `wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -` it jumped out the title.

If I run `sudo add-apt-repository 'deb https://typora.io ./linux/'` it notified `GPG error: https://typora.io/linux ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA300B7755AFCFAE`. 

If I run `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE`, it told me `invalid key resource URL '/tmp/apt-key-gpghome.p6xpdLa1HI/home:manuelschneid3r.asc.gpg'`.

**Comment by Shen897** [comment]
related #1629

**Comment by yekaizhou** [comment]
> Try
> 
> ```
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BA300B7755AFCFAE
> ```
> 
> related #1629

Thanks. I use snap to manage it instead.
