### ISSUE TITLE
More details for Search matches

### ISSUE THREAD

**Issue by glocalglocal** [typora/typora-issues#4424]
It would be useful if Search reported something like 'x of y matches', and ideally showed notches on the vertical scrollbar for the location of these matches like eg Firefox does. 

This is not just about convenience. Knowing how many times a word or a certain character occurs can save you a lot of time. Eg I use '%' once per case in a project. The number of '%' tells me how many cases I have, which saves me the counting and is essential for validation. The number of '.' usually gives you the number of sentences.

**Comment by abnerlee** [comment]
duplicated with #3404
