### ISSUE TITLE
Exporting to HTML may introduce non-ASCII characters in code blocks

### ISSUE THREAD

**Issue by alvii147** [typora/typora-issues#4425]
When exporting to HTML, non-ASCII characters are displayed on code blocks. I discovered this when I converted a document containing this code block to HTML:

```python
from django.apps import AppConfig

class MyAppConfig(AppConfig):
    name = 'my_app'
```

Exporting this to HTML, I copied this block into a working repository and got a syntax error. Turns out there is a non-ASCII character in the second line:

![image](https://user-images.githubusercontent.com/35665983/119265954-d102dd80-bbb6-11eb-88e7-314ffb4116eb.png)

This happens because the exported HTML has an empty `<pre>` tag for the blank 2nd line:

```HTML
...
<pre class=" CodeMirror-line "
    role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span cm-text="">​</span></span></pre>
...
```

The simplest fix would probably be to replace the `<pre>` block with `<br>` or something equivalent.

**Comment by abnerlee** [comment]
should be fixed
