### ISSUE TITLE
Typora is locking up when using the Ctrl+i keyboard shortcut to add emphasis 

### ISSUE THREAD

**Issue by etrokal** [typora/typora-issues#4427]
Version: 0.10.11 (It was the same in 0.10.10)
Platform: Windows 10 x64 (x64 version installed)

I have a markdown file with around 2000 words, created with Typora. If I try to add emphasis to a word using the shortcut Ctrl+i, Typora stays locked up for around 30 seconds. After the 30 seconds has passed, it resumes normal function. This behavior only happens if I use the Ctr+i shortcut. Ctrl+b, for instance, does not trigger the issue.

Adding emphasis using other methods doesn't trigger this issue. Both typing in the emphasis or using the right click menu work flawlessly.

Unfortunately, I cannot provide the file in question because it is work related and contains sensitive information. A clean, 25000 word _lorem ipsum_ does not present the behavior. My file has a lot of formatting, with several codeblocks and inline codes, tables, bold texts and emphasis, so I believe it is somehow related to this.

The problem did not happen at first when I started writing. Only after the file got to a certain size.

**Comment by abnerlee** [comment]
We cannot reproduce this or received any similar reports from other users.
Is there any other pattern in your file? Like target line contains many * or _, etc?
