### ISSUE TITLE
Equations downsized if overflowing or multi-line when printing

### ISSUE THREAD

**Issue by mippeqf** [typora/typora-issues#4428]
As soon as an equation gets wider than its bounding box, Typora reduces the font size or shrinks the the entire MathJax container when the page is printed. 
This is also the reason why equation numbering reduces equation font size, as Typora applies the numbering indices to a location that would be outside of the box using normal scaling. 
This issue is thus a generalization of issues #4376 and #2961 and not a duplicate!

I'd consider this fix important, because it determines whether Typora is a real alternative to Latex editors or just another text editor.

**Comment by abnerlee** [comment]
It's duplicated with #2961
