### ISSUE TITLE
Make entering edit mode only when keystrokes received

### ISSUE THREAD

**Issue by reflectionalist** [typora/typora-issues#443]
Curretly, Typora enters edit mode whenever one position the curser (by left clicking the mouse) wherever over an element, displaying the markdown source.  This causes annoyances:

1. for the writer: s/he has to enter extra blank spaces to trigger live preview; and
2. for readers: they get distracted by the source of some element over which the writer doing live writing accidentally positions the curser.

IMHO, the assumption that when one positions the curser s/he wants to edit the element is extra.  Typora should remain in preview mode, regardless of the curser position, unless keystrokes are received.

**Comment by AlexPasternak** [comment]
I completely disagree, I click into items all the time without the intention to edit them. E.g., to see the specific header size used there, or to see what the link URL is for the link in question. This is your usage pattern here, and it does not apply to all the users.

**Comment by reflectionalist** [comment]
@AlexPasternak Thanks for offering another usage pattern.  Now I realized that my proposal would be a bit too aggressive.  To reconcile, I would suggest instead entering edit mode only when putting/moving cursers _inside_ an element, but remain in preview mode when putting/moving curser _outside_ an element, including immediately in front or at the end of an element.  I think that would resolve both of our concerns.

**Comment by vassudanagunta** [comment]
Typora is a WYSIWYG *editor*.  Not a reader.  I agree with @AlexPasternak.  All affordances should be made toward editing. There are other Markdown editors with distinct edit and read modes (in fact, almost all others work this way).  The reason Typora is so loved is because it is NOT like them.

I would prefer a read-only mode (#710) to this proposal. 

@abnerlee I recommend closing this issue to start cleaning up the list of open issues.

**Comment by AlexPasternak** [comment]
> As far as I can tell Typora already behaves as you request in your last comment.

Well, that is not quite true, as there's no way to click on the end of something formatted without seeing the formatting, e.g., below. But again, I'm 100% fine with this, as it's an editor. Even in a read-only doc, which may be to prevent accidental changes, I may still want to see what MD formatting is applied to a particular element.

![2018-01-09 12 56 41](https://user-images.githubusercontent.com/1819485/34735239-c8f77838-f53c-11e7-8d5f-c2bcda51fe2c.gif)

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/1313

**Comment by vassudanagunta** [comment]
I would argue that in editing mode, current behavior is perfect and _should not_ change. 

Instead, have a "reading mode" such as suggested in #89. If you agree, let's close this one and all rally around that one :)

**Comment by AlexPasternak** [comment]
Yeah I think the intent here was to have presentation mode, so that's a good argument.

**Comment by reflectionalist** [comment]
@vassudanagunta Agree.
