### ISSUE TITLE
Request : Autocomplete mode in typora which already mentioned in current document or Opened Folder.

### ISSUE THREAD

**Issue by DrVinod** [typora/typora-issues#4433]
When select File/Folder in typora then all text should be came as a autocomplete text, which will be helpful rather re write the word.

https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/autocomplete/how-to/creating-an-autocomplete-textarea/js/

**Comment by abnerlee** [comment]
duplicated with #756?
