### ISSUE TITLE
Change Type Automatically - Easier way to change List Level - Collapse/Fold Support

### ISSUE THREAD

**Issue by rbharathkumar** [typora/typora-issues#4435]
Hi team,
Have been truly enjoying typora - One of the best apps in this genre...
Would be nice if the following can be improved.

**1. Change Case Automatically**
It is almost common occurrence that we switch between cases. It would be nice if the app could recognize it and modify it.
E.g. _tYPING ==> Typing_

**2. Easier way to change List Levels**
Say we are working on a multi level list. When we press Enter the next entry is made at the same indent. This is the expected behaviour. But if we try to change its level, it is quite hard to do so and not always consistent.
E.g. 
1. List Level 1
    1.1. List level 1.1
    _1.2. Changing this List Level from 1.1. to 2 is quite hard_

**3. Collapse/Fold Options**
As mentioned above I have multi level lists and headings. Collpase or Fold options would be of great use.
At least in the `[toc]`. Say I have headings based on dates collapsed under month collapsed under year, the TOC itself seems to be taking up the entire document.

**App Version and OS:**
OS: Windows 20H2
App Version: 0.10.11

**Comment by abnerlee** [comment]
> 1

We currently do not have plan for this, since I'm not sure if this is needed. But we are open for shis if other users also provide similar requests.

> 2

-> #1278

> 3

-> #499
