### ISSUE TITLE
Tuning Request: More keyboard accessibility

### ISSUE THREAD

**Issue by DoctorDendrite** [typora/typora-issues#4437]
Popup dialogs can't be dismissed or controlled from the keyboard.

![image](https://user-images.githubusercontent.com/7386802/119918401-3a6b4f00-bf1d-11eb-9b35-8fc8d6f333b4.png)

Pressing `Tab` or `Enter` continues to make changes in the editor while the popup is active. Side note: In Windows applications, `Esc` and `Alt + F4` can be used to cancel a dialog box; here (on Windows) they do nothing.

Having to mouse over to dialog boxes can be time-consuming for someone who's grown accustomed to using the keyboard. Could you add more key bindings, or at least allow a user to control dialog boxes from the keyboard?

**Comment by abnerlee** [comment]
#656
