### ISSUE TITLE
Feature suggestion: enable the `split` environment by default

### ISSUE THREAD

**Issue by keyboardAnt** [typora/typora-issues#4438]
I repeatedly use a LaTeX code of the following structure:
```LaTeX
$$
\begin{split}
    foo &= bar \\
    &= lol
\end{split}
$$
```
I couldn't find a way to enable the LaTeX environment `split` by default, so I wouldn't have to repeat it over and over. Is that possible? If no, please consider this issue as a feature suggestion.

**Comment by abnerlee** [comment]
It is not supported, and no plans for this, as

- setting global environment cannet let md file being rendered in same env in other markdown spec
- It requires extra settings

But this can be covered in #3021
