### ISSUE TITLE
image load failed

### ISSUE THREAD

**Issue by herjh0405** [typora/typora-issues#4441]
![image](https://user-images.githubusercontent.com/54921730/120075525-9cbe7e00-c0dc-11eb-8516-4f629549519b.png)
Windows 10
Typora version 0.10.11
Why is image load failed in github repo?

**Comment by abnerlee** [comment]
Possible reasons are:

- Typora cannot load it (due to GFW, etc)
- The content is private or requires login/cookie to access

**Comment by imattdu** [comment]
> * GFW

Typora 无法加载它（由于 GFW 等）-> 其他编辑器是正常的，应该不是防火墙的问题吧，或者说typora可以配置什么
内容是隐私的或需要登录/cookie 访问 -> 因为不是因为这个，浏览器可以访问的，其他编辑器也是可以访问

**Comment by qingchuang12** [comment]
我这github图床，上传图片后显示也是这样，加载失败，链接可以在浏览器打开。更重要的是，我把typora关闭再打开又能加载图片了。真烦人~，这个问题咋关掉了。。问题一直没解决吧。一年前用七牛云也是这个问题。。
