### ISSUE TITLE
[Features Request]: Hot-Reload; Auto Headers-Tag Generator

### ISSUE THREAD

**Issue by Iipal** [typora/typora-issues#4443]
Some features or small fixes that I would like to see in the next updates:

Hot-Reload:
 - Remove confirm dialog, or make it optional to enable in settings:
![image](https://user-images.githubusercontent.com/31858171/120081628-3f6c0200-c0c7-11eb-912f-23dbe4d40cd5.png)

Auto Headers-Tag Generator:
 - Is it even possible to make some auto-complete like VSCode do when creating links to header tags:
![image](https://user-images.githubusercontent.com/31858171/120081702-91ad2300-c0c7-11eb-8cc0-878358a0caba.png)
 - This feature in VScode provided by [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) extension.

Thanks =)

**Comment by abnerlee** [comment]
duplicated with #2663
