### ISSUE TITLE
Large math blocks become automatically smaller when exported to pdf

### ISSUE THREAD

**Issue by shundroid** [typora/typora-issues#4445]
Here is the example.
![image](https://user-images.githubusercontent.com/8530218/120103746-1eb9b000-c18c-11eb-81e0-14083b2f11f1.png)
I want to make all math blocks same size, but large math blocks become smaller.
I'm in trouble.

After I updated Typora, this trouble came to happen.
I'm using Typora 0.10.11. Please fix it.

**Comment by shundroid** [comment]
I'm not using formula numbers.

**Comment by abnerlee** [comment]
duplicated with #3979
