### ISSUE TITLE
Problem with translation and spell check

### ISSUE THREAD

**Issue by ihindha** [typora/typora-issues#4449]
Since a few versions back, not the dictionary stored between the various actions of the program without the need to be downloaded again.

The strange thing is that it apparently only seems to occur when using a language other than English.

Another thing, which is probably related to this: When I changed the language to English for testing, I discovered that the automatic identification of language does not work with English as the system language, but it is identified always as en-us.

**Comment by abnerlee** [comment]
same with #3584?

Also in Linux?
