### ISSUE TITLE
24 hours to open typora consume a lot of system resources

### ISSUE THREAD

**Issue by livc** [typora/typora-issues#445]
![image](https://cloud.githubusercontent.com/assets/11692045/20750789/90545746-b733-11e6-8a25-dacdbc2d5bad.png)
![image](https://cloud.githubusercontent.com/assets/11692045/20750796/96e08d00-b733-11e6-9d27-ab2151457fd0.png)

**Comment by abnerlee** [comment]
duplicate to #442, currently insert invalid image url would cause this.

Will be fixed in next version up
