### ISSUE TITLE
Feature Request: Support heading folding/unfolding

### ISSUE THREAD

**Issue by leiless** [typora/typora-issues#4455]
Hi, Typora developers.

Can you guys support markdown heading folding/unfolding?
When your markdown file getting large, it's hard for you to navigate and read.

The effect might somewhat like the following image
![image](https://user-images.githubusercontent.com/38041294/120465454-9415c280-c3d0-11eb-8bb5-69ba11b3f57e.png)

I don't know if it's hard to implement this feature since I have no markdown/frontend experience.

**Please upvote if you think this feature is helpful to you.**

**Comment by abnerlee** [comment]
duplicated with #499
