### ISSUE TITLE
Linux Mint 20.1 "Save As" window doesnt show bookmarks

### ISSUE THREAD

**Issue by RoastMyCode** [typora/typora-issues#4456]
When saving a new document or choosing "Save As" the opening Nemo Window in Linux Mint 20.1 doesnt show the bookmarks. If I use the simple text editor for example and click "Save As" bookmarks are shown as expected on the left side of the window.  
Not a huge issue but slightly annoying not being able to access my bookmarks.

**Comment by abnerlee** [comment]
I believe Typora will use the save dialog without any special settings, so, there probably won't be anything typora can do about it.

Does https://forums.linuxmint.com/viewtopic.php?t=301637 help?

Does "save as" dialog has bookmarks for non-built-in app like chrome or firefox?
