### ISSUE TITLE
Missing selected words count

### ISSUE THREAD

**Issue by glocalglocal** [typora/typora-issues#4457]
Sometimes when I select the last paragraph, the selected words count (x in x / y Words) appears, quickly disappears and never appears again. Normally, when I select text elsewhere, x reappears after that strange flashing. 

![image](https://user-images.githubusercontent.com/16408198/120505794-d7face80-c3b4-11eb-9d9c-318e8d6e444f.png)

That's two spaces after the period (but it happens with no spaces or one space too), followed by one or multiple blank lines -- at least one blank line is necessary for this to happen. 

The easiest way to reproduce it is to click and drag beyond the end of the last paragraph (ie include at least one blank line). I don't have to select a whole paragraph -- any length of text reaching the end of file will do. I get it at least once every five tries. I can't do it with triple-clicking to select the paragraph. 

v0.10.11 on Win10 64bit

**Comment by abnerlee** [comment]
I can see it flash, but the selected words won't gone.

Did you try the built-in themes?

**Comment by glocalglocal** [comment]
Pixyll: 
![image](https://user-images.githubusercontent.com/16408198/120632279-4e9cd800-c458-11eb-93d3-2d680c7199f9.png)
Github:
![image](https://user-images.githubusercontent.com/16408198/120632299-53fa2280-c458-11eb-912c-c0468b5ef904.png)

**Comment by glocalglocal** [comment]
Correction: 

I just found out it also happens with paragraphs other than the last one: 

![image](https://user-images.githubusercontent.com/16408198/120661629-faa1eb80-c477-11eb-9070-570ccbc07c4d.png)
This is with the github theme. 

I couldn't reproduce it while staying within the first of these three paragraph -- ie like before, I had to include the new line character.

**Comment by abnerlee** [comment]
should be fixed
