### ISSUE TITLE
the Outline Click

### ISSUE THREAD

**Issue by KKindom** [typora/typora-issues#4458]
Clicking on the outline can't jump to the correct title position. You need to click twice to jump to the specified position correctly.

**Comment by abnerlee** [comment]
Could you share sample file and steps to reproduce this?

**Comment by KKindom** [comment]
Sorry, I found a problem. This is caused by using a third-party theme. There is no problem using the default GitHub style theme.

**Comment by KKindom** [comment]
> Could you share sample file and steps to reproduce this?

Sorry, I found a problem. This is caused by using a third-party theme. There is no problem using the default GitHub style theme.
