### ISSUE TITLE
when typora edit hexo markdown post if hexo server is running, hexo server get markdown  post is empty

### ISSUE THREAD

**Issue by cxgreat2014** [typora/typora-issues#446]
when I use other editor, hexo server worked very well, but when typora edit hexo post and **save**, that post will be empty in the webpage.

it seems like ,when typeora save file,typora will clean the file, then write it.
in python, that's like that :
```
open('test.md','wb').write(''.encode())  # 1
open('test.md','wb').write('---\r\ntitle: xxx \r\n---\r\n test content'.encode()) #2
```
hexo server will in `#1` to get the empty file, ignore the `#2`，it only happend in that twice change a file in a very little time, 
https://github.com/hexojs/hexo/issues/2245

**Comment by abnerlee** [comment]
What's your OS version?

**Comment by cxgreat2014** [comment]
Windows 7 x64 Service Pack 1

**Comment by abnerlee** [comment]
should be fixed now
