### ISSUE TITLE
Inconsistent truncation of lines with whitespaces

### ISSUE THREAD

**Issue by jmkeil** [typora/typora-issues#4461]
**Describe the bug**
Typora inconsistently preserves lines in the file (not the rendered view) with only whitspaces after loading and saving: A line with only whitespaces after a sublist (`  * …`) and before a header (`# …`) will completely be removed, if it contains at least as many whitespaces as before the sublist item. I would expect Typora to just remove the whitespaces, but leaf the empty line. If the line contains less or none whitespace, it will be preserved.

**To Reproduce**
1. Create file with
   ```
   * list
     * sublist 
     
   # section
   ```
   (note the whitespaces in line 3)
2. Open file in Typora
3. Save file with Typora
4. File contains
   ```
   * list
     * sublist 
   # section
   ```
   (empty line missing)

**Expected behavior**
File contains
```
* list
  * sublist 

# section
```
   (empty line without whitespaces)

**Desktop:**
 - OS: Debian GNU/Linux 10 (buster)

**Typora Version**
0.10.11 on Linux

**Comment by CapinWinky** [comment]
Ideally, Typora should just render whitespace the way markdown whitespace is supposed to be rendered (by removing most of it). If you want empty lines, they should contain two spaces as the last characters which should insert `<br>`. I'm just now giving Typora a try again and when I opened a few documents they were just riddled with whitespace.

**Comment by jmkeil** [comment]
> Ideally, Typora should just render whitespace the way markdown whitespace is supposed to be rendered (by removing most of it). If you want empty lines, they should contain two spaces as the last characters which should insert `<br>`. I'm just now giving Typora a try again and when I opened a few documents they were just riddled with whitespace.

Maybe I didn't say clearly enough that this issue is about the plain content of the resulting file, not the rendered view.

**Comment by abnerlee** [comment]
Possible to provide a sample file that empty line will be removed after saving in Typora?

The sample

```
* list
  * sublist 
  
# section
```

works just fine in my test.

**Comment by jmkeil** [comment]
Yes, here:
* [file before step 2 and 3](https://github.com/typora/typora-issues/files/6784308/exampleBefore.md)
* [file after step 2 and 3](https://github.com/typora/typora-issues/files/6784307/exampleAfter.md)

**Comment by abnerlee** [comment]
should be fixed
