### ISSUE TITLE
Incomplete support for Entity  mermaid#Relationship Diagrams

### ISSUE THREAD

**Issue by nicky-chen** [typora/typora-issues#4463]
i hope like this
![er](https://user-images.githubusercontent.com/25236931/120751725-18845480-c53b-11eb-9239-a05e10982bba.png)

but in fact
![infact](https://user-images.githubusercontent.com/25236931/120751904-5c775980-c53b-11eb-98bb-0d32a700832b.png)
*reference from*  [mermaid/#/entityRelationshipDiagram](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram),
i think typora need to upgrade the mermaid  plugin

**Comment by abnerlee** [comment]
put into #1661
