### ISSUE TITLE
heavy check mark emoji not adding correctly from the emoji toolbar

### ISSUE THREAD

**Issue by codeScientist** [typora/typora-issues#4464]
On selecting the heavy check mark emoji from the emoji toolbar (Win + .) I am getting some other emoji, the black tick mark emoji, which is not shown in the emoji toolbar and which is not ":heavy_check_mark:" emoji. PFA images below
![image](https://user-images.githubusercontent.com/8676091/120810072-962a6f00-c4ff-11eb-809b-4b0a8055e3cf.png)
![image](https://user-images.githubusercontent.com/8676091/120810272-ba864b80-c4ff-11eb-89ba-b5efe831c4aa.png)

**Comment by abnerlee** [comment]
Seems a Windows bug, it inserts a ✔, not ✔️ (you can try in WordPad or address bar in Chrome using win + ;)

Orr, you can change the font, add "Segoe UI Emoji" in css font-family, but many 3rd themes uses their own font style...

**Comment by abnerlee** [comment]
I added "Segoe UI Emoji'" for built-in themes in latest version. 

If you use custom themes, add "Segoe UI Emoji" for their "font-family" style in their css styles, it relates to the default font for Windows.
