### ISSUE TITLE
The hyperlink doesn't support local path with 【】

### ISSUE THREAD

**Issue by Darleey** [typora/typora-issues#4466]
**Describe the bug**
When I try to link a local file to the hyperlink
e.g. `[test-a](【src】/*【**】*.md)` /  `[test-b](【src】/*【**】*.rar)` 
Typora will automatically convert it to  `[test-a]([src]/*[**]*.md)` /  `[test-b]([src]/*[**]*.rar)` 
Then these local files cannot be visited by the hypoerlink.

BTW:
Image hyperlink  `![test-c](【src】/*【**】*.jpg)` works well ~

**Desktop (please complete the following information):**
OS: Windows 10 64bit 20H2

**Typora Version**
0.10.11

**Comment by abnerlee** [comment]
duplicated with #4381
