### ISSUE TITLE
Pandoc does not have correct working directory

### ISSUE THREAD

**Issue by kerryland** [typora/typora-issues#4467]
**Describe the bug**
Exporting using Pandoc does not set the current working directory, which makes it hard to export a multi-file project using the pandoc flag `--defaults=`

If you are not familiar with `defaults.yaml`, it's a file where you can (amongst many other things) define the list of files to print as part of a "project".

Ideally Typora should set the current working directory to that of the file currently being edited, or it should introduce a new [variable]( https://support.typora.io/Export/#other-pandoc-options), `${currentDirectory}` which evaluates to the directory of the currently-edited file. eg: for `d:/tmp/md/preface.md` , `${currentDirectory}` would evaluate to `d:/tmp/md`

**To Reproduce**
Create the following 3 files (also attached): [sample.zip](https://github.com/typora/typora-issues/files/6602414/sample.zip)

defaults.yaml:
```
input-files:
- preface.md
- content.md
```
preface.md:
```
# Chapter One

```
content.md:
```
Hello World

```
Assuming the above 3 files are in `d:/tmp/md`, if from the command line I run the following:
```
 cd d:/tmp/md
 pandoc -f markdown -s -o test.docx -t docx --defaults=defaults.yaml
```
Then I get a successful "test.docx" file.

If I change the Export preferences for "Word (.docx)" to:
```
-f native -s -o ${outputPath} -t docx
--defaults=d:/tmp/md/defaults.yaml
```
then pandoc gets unhappy because it cannot find "preface.md" or "content.md".

Here are some options I can think of that would help:

1. Typora should change the working directory of that of the currently edited file when exporting to Pandoc
   In this case I could define the Export preference to `--defaults=defaults.yaml` which would be fine.

2. Typora could add a new variable `${currentDirectory}` variable although I'm not sure these variables are actually evaluated in the Export preference fields. I would also need to change the `defaults.yaml` file to look like this, which wouldn't be a big deal:

input-files:
```
- ${.}/preface.md
- ${.}/content.md
```

There is a work-around:

1. Hard code the Export preferences to the project's path, eg: `--defaults=d:/tmp/md/defaults.yaml`
   and update it whenever I change projects, and 
2. Change my `defaults.yaml` files to all reference `${.}`

Note: I would have thought that if I defined the Export preferences to `--defaults=${currentPath}`, and
then edited default.yaml, and then performed the export, then it would've worked a bit, but actually
pandoc fails because it cannot open `${currentPath}.yaml`, which makes me suspect variables are not evaluated.

**Expected behavior**
I expect to be able to use the Pandoc `--defaults` flag and get a usable multi-file output.

**Screenshots / Screencasts**
Here is the error showing that pandoc is not happy that the current working directory is not set correctly:
![pandoc-not-happy](https://user-images.githubusercontent.com/398113/120889271-60e16680-c650-11eb-9026-15693b965e24.png)

Here is the error that suggests to me that `${currentPath}` is not being evaluated at export time:
![not-evaluated](https://user-images.githubusercontent.com/398113/120889316-99814000-c650-11eb-8222-3fe42285be23.png)

**Sample Markdown File**
[sample.zip](https://github.com/typora/typora-issues/files/6602414/sample.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit via CMD prompt or Powershell, or mingw64

**Typora Version**
0.10.11

This is tangentially related to #824

**Comment by kerryland** [comment]
Here is [test.docx](https://github.com/typora/typora-issues/files/6602444/test.docx), which shows the resulting docx file that includes the contents of both `preface.md` and `content.md` when successfully combined using `--defaults=`

**Comment by abnerlee** [comment]
Seems working directory and variable replace is not processed for built-in pandoc export options, which we will fix.

You can use <del>custom pandoc command</del> or custom command for now.

But I don't think `--defaults=` will work for pandoc based export options in Typora, since it sets a list of input file, while typora give pandoc input stream (from current file) again, so there will be conflicts.

In you cause, you can use "custom" commands for export, working folder will be set to the folder of current opened file.

**Comment by abnerlee** [comment]
cwd is now set already.
