### ISSUE TITLE
Horizontal scrollbar doesn't work on long MathJax formula

### ISSUE THREAD

**Issue by saulspatz** [typora/typora-issues#4468]
I entered a very long MathJax formula that runs off the right-hand edge of the page.  The horizontal scrollbar doesn't work.  When I click it, or try to drag it, nothing happens.

The markdown file is available at https://gist.github.com/saulspatz/20211b6a5336f91d6c307bf6b7b370eb

There's nothing in the file but one MathJax  formula.

I made the following change to night.css:

```
#write {
    max-width: 1920px;
    overflow-x: auto;
}
```

Otherwise, it's just as it came out of the box. 

I might mention that I pasted this code into MathStackExchange and it displayed fine, although there were line breaks in both the numerator and denominator.     

OS: Windows 10 64bit

Typora Version 0.10.11

**Comment by abnerlee** [comment]
should be fixed in 1.2.5
