### ISSUE TITLE
Network pictures in Typora cannot be displayed normally

### ISSUE THREAD

**Issue by vkcyan** [typora/typora-issues#4469]
The picture link can be accessed normally, but why can’t it be displayed normally in Typora? I like Typora very much. He helped me solve a lot of problems, but the picture is not displayed, which really affects the use. What should I do? Show these pictures?

![image](https://user-images.githubusercontent.com/33681955/120966381-b9238000-c798-11eb-97d9-072c0c2d9a7a.png)

version 0.10.10 (5354)
Computer version 11.2.3 (20D91)

**Comment by abnerlee** [comment]
Does it require login / cookie, or limited for certain browser / domain?
