### ISSUE TITLE
[Feature] Option to globally permanently disable spell check

### ISSUE THREAD

**Issue by emberfiend** [typora/typora-issues#4470]
I'd really like an option to globally, permanently disable spell check.

I have no interest at all in using spell checking in any document. It can be reliably disabled per document, but if you rename a document or create a new one, spell check is automatically re-enabled. Having to manually disable spellcheck every time I create or rename a document is tedious.

Typora 0.10.11, Windows 10 20H2. I have disabled "Highlight misspelled words" in Windows settings (Typing > Spelling). If there is some conf.user.json (or other) flag I am missing, please let me know.

Thanks for an otherwise wonderful piece of software 😊❤

**Comment by Pandaa-P** [comment]
Performance -> Editor -> Spell Check -> Disable Spell Check
![Typora_isQ4C7mTGH](https://user-images.githubusercontent.com/85793213/121777499-15244500-cb9b-11eb-9ef3-c64686abf483.png)

**Comment by emberfiend** [comment]
You're a legend, and I feel suitably silly for missing this option. Thank you so much :)
