### ISSUE TITLE
[Feature] Preview PDF before printing the file 

### ISSUE THREAD

**Issue by Pandaa-P** [typora/typora-issues#4471]
I really hope that the developers of Typora implement this feature. 

I know that Typora doesn't support "pagination" and there are no plan to add "pagination" feature (according to https://github.com/typora/typora-issues/issues/1245#issuecomment-484542563). 
It's pain in the butt to print the file to PDF and see the mess of formatting, and the time wasted on correcting the formatting/style  by Trial & Error method by edit then print after each edit.

**Comment by abnerlee** [comment]
#1732
