### ISSUE TITLE
[Feature] provide option to paste links as plain text instead of converting it to hyperlink []()

### ISSUE THREAD

**Issue by GorvGoyl** [typora/typora-issues#4472]
When pasting a link, Typora automatically converts it to hyperlink `[]()` instead of actual text.
For example when pasting `https://github.com/typora/typora-issues`  typora converts it to `[typora/typora-issues: Bugs, suggestions or free discussions about the minimal markdown editor — Typora (github.com)](https://github.com/typora/typora-issues)`
 Please provide an option to disable this setting.

**Comment by Pandaa-P** [comment]
There is an option for that 
![Untitled](https://user-images.githubusercontent.com/85793213/121820799-5e5cbd80-cc9d-11eb-850d-bda3ee3a6e33.png)

**Comment by GorvGoyl** [comment]
Thanks. I paste lots of links so looking for a way to permanently disable this feature.

**Comment by Pandaa-P** [comment]
As far as I know there isn't, maybe the developer know a hidden setting though. 
But as  a work around you can use `Ctrl+Shift+V`  instead of `Ctrl+V`

![Untitled](https://user-images.githubusercontent.com/85793213/121820951-43d71400-cc9e-11eb-983e-127149b05ff5.png)

**Comment by GorvGoyl** [comment]
thanks. I can manage with that shortcut.
