### ISSUE TITLE
Menubar missing from typora

### ISSUE THREAD

**Issue by Catoverflow** [typora/typora-issues#4473]
## Bug description

There are similiar issues like #2260 , but mine is slightly different.
The `autoHideMenuBar` option in `conf.user.json` does not work, `true` or `false` result in the same missing menu.
Pressing ALT is of no use, nothing showed up.

It occured about half a month ago, maybe related to a electron update, my electron version is `v12.0.9` now.
System infomatain: `5.12.10-arch1-1`
Typora version: `0.10.11`, installed from AUR, with this [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=typora).

## What I tried
- search the Internet, nothing worked
- Try reinstalling, including a `rm -rf ~/.config/Typora` which clear the config completely, didn't help

## Reprodece
Not tested yet, I'll try in a few days on other Arch machine.

**Comment by Catoverflow** [comment]
If possible, would you add some command-line interface? If GUI fails, I can still use command to export my markdown file to pdf or some handy feature? :3

**Comment by Pandaa-P** [comment]
>It occured about half a month ago, maybe related to a electron update, my electron version is v12.0.9 now.

That maybe the reason. It could be typora use the system electron "/usr/lib/electron/"  instead of the bundled one.
Could you open DevTools from `View` -> `DevTools` and provide the error log, or get error log following 
this: 
Click “Open Theme Folder” in preference panel, and find typora.log on its parent folder.

**Comment by Catoverflow** [comment]
The DevTools is available, and the log in console are as follows
~~~~
typora://userData/themes/base.user.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
typora://userData/themes/github.user.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///usr/share/typora/resources/lib.asar/pdf/pdf-lib.min.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/typora/resources/node_modules.asar/spellchecker/node_modules/underscore/underscore-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/lib/codemirror/mode.min.js.map: 
DevTools failed to load SourceMap: Could not load content for http://typora/appsrc/window/frame.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/typora/resources/node_modules.asar/fs-plus/node_modules/underscore/underscore.js.map: 
~~~~
Seems to be normal resources missing

I can't open the preference panel (for I can't trigger the menu bar), but I instead navigate to /usr/share/typora, and didn't find the log. (I use `find /usr/share/typora | grep log` and get no output)

> > It occured about half a month ago, maybe related to a electron update, my electron version is v12.0.9 now.
> 
> That maybe the reason. It could be typora use the system electron "/usr/lib/electron/" instead of the bundled one.
> Could you open DevTools (press `Shift + F12`) and provide the error log, or get error log following
> this:
> Click “Open Theme Folder” in preference panel, and find typora.log on its parent folder.

Is there any way to switch to the bundled electron?

**Comment by Pandaa-P** [comment]
>Try reinstalling, including a rm -rf ~/.config/Typora which clear the config completely, didn't help

This time try removing typora folder in `usr/share/typora` and `/usr/bin/typora` and try reinstalling again.

**Comment by abnerlee** [comment]
1. attach a screenshot please?
2. could you try the binary file (https://typora.io/linux/Typora-linux-x64.tar.gz)? Does it contains the menubar?

**Comment by Catoverflow** [comment]
Screenshot is as below (of vanilla build):
![image](https://user-images.githubusercontent.com/55503205/122894561-e1ef6c00-d379-11eb-8253-047c5a1f9a39.png)
Menubar is still missing.
:(

> 1. attach a screenshot please?
> 2. could you try the binary file (https://typora.io/linux/Typora-linux-x64.tar.gz)? Does it contains the menubar?

**Comment by abnerlee** [comment]
> Another Arch user with electron v12.0.9 and same typora(AUR) package does not come across this problem, that's quite weird :(

Typora 0.10.x uses Electron v9.x.x, other electron versions won't be supported.

---

@Catoverflow could you open typora from terminal, and attach terminal output and logs from ~/.config/Typora/typora.log ?

**Comment by Catoverflow** [comment]
It turns out to be the effect of KDE desktop widgets, the menu bar move up to the top panel if "Global Menu" widget is set. Typora itself works out fine
:3
