### ISSUE TITLE
high cpu when have some gif images

### ISSUE THREAD

**Issue by mohuishou** [typora/typora-issues#4475]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

high cpu when have some gif images

![image](https://user-images.githubusercontent.com/15172509/122148437-17351f00-ce8d-11eb-8b7d-1cddb909939d.png)

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
[04_localhost 就一定是 localhost 么.md](https://github.com/typora/typora-issues/files/6659833/04_localhost.localhost.md)

**Desktop (please complete the following information):**
 - OS: macos 11.2.1

**Typora Version**
0.10.11

**Additional context**

**Comment by Pandaa-P** [comment]
I can reproduce this on windows 10

- Describe the bug: High CPU when have some GIF images 
- OS: Windows 10 May 2021 Update
- Typora Version: 0.10.11
---
![Untitled - Copy](https://user-images.githubusercontent.com/85793213/122232564-fdfb9500-cec3-11eb-9880-371774a860e5.png)

**Comment by abnerlee** [comment]
Possible to also provide the gif file?

**Comment by mohuishou** [comment]
> Possible to also provide the gif file?

![1](https://user-images.githubusercontent.com/15172509/122670750-2b16b300-d1f6-11eb-8be9-fcf7264dff50.gif)
![2](https://user-images.githubusercontent.com/15172509/122670753-2e11a380-d1f6-11eb-98ef-5eb4bc3f2e35.gif)
![3](https://user-images.githubusercontent.com/15172509/122670759-2eaa3a00-d1f6-11eb-9040-61379f5dab38.gif)

**Comment by abnerlee** [comment]
still happens in 0.11?

**Comment by mohuishou** [comment]
> still happens in 0.11?

the problem goes away in 0.11
