### ISSUE TITLE
[Feature] Line operations. Move line, delete line, etc.

### ISSUE THREAD

**Issue by JohnLukeBentley** [typora/typora-issues#4479]
I suggest a "Line operations" (or similar named) submenu be added to the Edit menu with, at least:

* Move line down.
* Move line up.
* Delete line.

The first two commands have already been suggested in #1211. But a `Delete line` command is useful. 

Obviously assigning default shortcut keys would the real power move. Personally, I generally use:

* Alt + Down Arrow (Move down).
* Alt + Up Arrow (Move up).
* Ctrl + D (Delete line).

... but others will have their own preferences.

**Comment by abnerlee** [comment]
There's Delete Line/Sentence in Edit - > Delete Range

Others are duplicated with #1211.

**Comment by JohnLukeBentley** [comment]
Apologies for not seeing `Edit > Delete Range > Delete Line/Sentence`. Given the other kinds of "Delete Range" that would be good place to keep it.

However, I'd still suggest, at least as a potential idea, a `Line operations` submenu as there's the potential to have a number of relevant commands in addition to #1211 `Move Up/Down` and (what could be duplicated in the submenu) `Delete Line/Sentence`. Namely those that Visual Studio Code provides. E.g. (From Visual Studio Code Menu > Selection): 

* `Copy Line Up`.
* `Copy Line Down`.

(Although they might be less useful in a non-coding environment such as Typora).

... and possibly some more that don't come immediately to mind.
