### ISSUE TITLE
Problem with page-break-before

### ISSUE THREAD

**Issue by mockey** [typora/typora-issues#448]
I'd like to add page-breaks for exported files, so I added:
```
@media print {
  h3:nth-of-type(n+2) {
    page-break-before: always;
  }
}
```
to github.user.css. but it seems to be rewritten to:
```
@media print { 
  h3:nth-of-type(1n+2) { break-before: page; }
}
```
when exported to HTML, which doesn't work.

It does seem to work when exported to PDF, though (I get correct page-breaks there).
But apparently there's a bug in the PDF renderer, that always adds the thead of a table to the top of the page when there's a page-break before it.

**Comment by mockey** [comment]
> But apparently there's a bug in the PDF renderer, that always adds the thead of a table to the top of the page when there's a page-break before it.

This can be fixed to some extent by adding `thead {display: table-row-group;}` but I suppose this will drop the thead from subsequent pages also.

**Comment by abnerlee** [comment]
> when exported to HTML, which doesn't work.
> It does seem to work when exported to PDF

`@media print` will only work when print (including print as PDF)

> But apparently there's a bug in the PDF renderer, that always adds the thead of a table to the top
This is a bug, but already fixed in current version

**Comment by mockey** [comment]
> @media print will only work when print (including print as PDF)

Yes, but the generated CSS for the HTML won't work, when you print the exported HTML (which would be nice).

> This is a bug, but already fixed in current version

Yes. Thanks for looking into it.

BTW: In the current version it seems that longer tables, that don't fit on the page as a whole, automatically start on the next page, leaving some empty space on the previous space. No big deal, probably a PDF renderer issue.

**Comment by abnerlee** [comment]
> Yes, but the generated CSS for the HTML won't work, when you print the exported HTML (which would be nice).

We will check this

**Comment by abnerlee** [comment]
Should be fixed already, please reopen if this still exists.
