### ISSUE TITLE
Your bug cost me my project file

### ISSUE THREAD

**Issue by backermanbd** [typora/typora-issues#4482]
**Expected behavior**
Markdown save should work properly but sometimes it lags

**Desktop (please complete the following information):**
OS: Windows 10 pro

**Typora Version**
latest 0.10.11

**Additional context**
I put tons of hours in my project file. Here, I lost that file because of this bug,
And I have to make it again

**Comment by YYan2017** [comment]
I reported the similar problem by Email from many years ago, I think they still use the auto save by system, through it is proved very unstable.
