### ISSUE TITLE
Cursor skips around when editing text after multiple emojis

### ISSUE THREAD

**Issue by erys** [typora/typora-issues#4484]
If I have a line like `:star::star::star: Test text`, and am editing it in non source code mode, the cursor skips forward unexpectedly (but consistently). For example, if I use backspace to delete the e in "Test", the e will be deleted but the cursor will then jump forward two characters, and the same thing happens when inserting text in the middle of the line. 
I am using 0.10.11 on Windows 10, and have seen this on multiple themes including the github theme. The cursor will skip forward more if there are more emojis, and doesn't seem to skip at all if there is only 1.

**Comment by abnerlee** [comment]
should be fixed
