### ISSUE TITLE
Issue With Typora jumping to top of page when applying text formatting.

### ISSUE THREAD

**Issue by WeiLee975** [typora/typora-issues#4487]
----

**Bug**
Whenever applying formatting to text in long documents spanning more than a page on screen (typically 1500 or more), typora jumps to the top of the page. Applying Bold, Italic effects or editing the paragraph format (Heading 1, 2 etc..) causes the editor to jump to the top of the page.

**To Reproduce**
1. Open document spanning more than a page.
2. Apply Bold/Italic or Paragraph effect to any text at bottom of Page.

**Expected behavior**
Normally when editing long documents and applying text formatting, I shouldn't be taken back to the top of the page as it is distracting having to scroll back down to the section I was working on. 

**Sample Markdown File**
[Error Reproduction.md](https://github.com/typora/typora-issues/files/6697987/Error.Reproduction.md)

**Desktop:**
Windows 10 64 bit

**Typora Version**
0.10.11

**Comment by abnerlee** [comment]
Sorry, but I still failed to reproduce this. Possible to attach a screencast?

And, also, same with #3696?
