### ISSUE TITLE
Blockquote inside List

### ISSUE THREAD

**Issue by AhmedThahir** [typora/typora-issues#4488]
I can't seem figure out how to nest a blockquote inside a list in **typora**
More specifically, how to make the blockquote blue ribbon get indented.
Currently using the latest version of typora.

In the below pictures, both the syntaxes result in the same output.

Source Code
![Screen Shot 2021-06-24 at 7 42 25 PM](https://user-images.githubusercontent.com/26618217/123292662-5239f100-d524-11eb-917b-0e75d1923ebc.png)

Rendered output
![Screen Shot 2021-06-24 at 7 42 07 PM](https://user-images.githubusercontent.com/26618217/123292619-46e6c580-d524-11eb-9b41-8ca56ba8e4a7.png)

**Comment by wesleyboar** [comment]
I've succeeded in making a nested blockquote with the following steps.

1. Type `* bullet`.
2. Press `SHIFT` + `ENTER`.
3. Type `> quote inside`.

<details>
<summary>Typora Render (Screenshot)</summary>

![Typora Render](https://user-images.githubusercontent.com/3259442/123574401-5e78b500-d795-11eb-8b27-770b22d23bcf.png)

</details>
<details>
<summary>(Github) Render</summary>

- bullet

  > quote inside

</details>
<details>
<summary>Raw Markdown (From Steps)</summary>

```markdown
- bullet
  
  > quote inside
```

[Source Code Render (screenshot)](https://user-images.githubusercontent.com/3259442/123574422-68021d00-d795-11eb-9609-6e905d50a590.png)

</details>
<details>
<summary>Raw Markdown (Alternative)</summary>

```markdown
- bullet
  > quote inside
```

> __Note__: After leaving "Source Code Mode", this will be converted to the same markdown as "Raw Markdown (From Steps)".

</details>

**Comment by wesleyboar** [comment]
Suggestions:

<details>
<summary>Type `SHIFT` + `ENTER` to get to next line to type blockquote.</summary>

To type and achieve this, I:
1. Type `1. list item`.
2. Press `SHIFT` + `ENTER`.
3. Type `> quote`.

</details>

<details>
<summary>Type three spaces before using `>` to type quote.</summary>

#### Raw Markdown

```markdown
1. list item 1
   
   > quote
   
2. list item 2
   
   > quote
```

[Raw Markdown Screenshot](https://user-images.githubusercontent.com/3259442/123575319-1d81a000-d797-11eb-85b2-c74659f77336.png)

#### Raw Markdown (Alternate)

```markdown
1. list item 1
   > quote
2. list item 2
   > quote
```

[Raw Markdown (Alternate) Screenshot](https://user-images.githubusercontent.com/3259442/123575372-338f6080-d797-11eb-9f4d-c319963b81b2.png)

> __Notice__: A new line between the two is optional.

> __Caveat__: After leaving "Source Code Mode", Typora will update this to match "Raw Markdown".
</details>

<details>
<summary>Test a different theme.</summary>

| Github | Ursine Polar |
| - | - |
| ![Github Theme](https://user-images.githubusercontent.com/3259442/123576467-00010600-d798-11eb-8bcf-f0d910b1d416.png) | ![Ursine Polar Theme](https://user-images.githubusercontent.com/3259442/123576527-02fbf680-d798-11eb-85a9-e1105cc744bb.png) |

</details>

**Comment by AhmedThahir** [comment]
Thank you @wesleyboar 
I'll try to find some other alternative

**Comment by abnerlee** [comment]
```markdown
1. list
    > blockquote
```
