### ISSUE TITLE
Some flowchart examples from Mermaid website are not working

### ISSUE THREAD

**Issue by etrokal** [typora/typora-issues#4491]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Some flowchart examples from Mermaid website are not working in Typora. More specifically the *direction* statement results in error.  If I remove the statement, the graph shows correctly.

**To Reproduce**
1. Create a new document
2. Create a mermaid  code block
3. Paste the following code:
```
flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2
```
4. See the error being shown as follows:
```
ERROR: [Mermaid] Parse error on line 3:
...h TOP    direction TB    subgraph B1 
----------------------^
Expecting 'SEMI', 'NEWLINE', 'EOF', 'AMP', 'START_LINK', 'LINK', got 'ALPHA'
```

**Expected behavior**
The mermaid diagram should be shown correctly

**Screenshots / Screencasts**
![img](https://user-images.githubusercontent.com/1265604/123818487-68063800-d8cf-11eb-8aa7-f29401f6a7ee.png)

**Sample Markdown File**
[example.md](https://github.com/typora/typora-issues/files/6734330/example.md)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.10.11

**Additional context**
It appears that setting the direction of subgraphs was introduced in version 8.10.2 of mermaid.

**Comment by abnerlee** [comment]
put into #1661
