### ISSUE TITLE
Add a push button if MD-file is in a repository

### ISSUE THREAD

**Issue by jkohlin** [typora/typora-issues#4492]
I like to keep my notes in sync across devices, but I'd also like to have editing history (revisions). 
I simple way to solve this would be to keep my MD files in a folder initiated as a git repository. 
However, it would be too much "complicated" work to open up a console and add, stage, commit and push my changes once done editing. 

Solution: 
Typora is aware of if the file lives in a repo, asks to log in to that repo and on open, asks to pull, and when there are changes to the local repo, offers a push button that saves, stages and commits changes and the pushes to github.

**Comment by abnerlee** [comment]
duplicated with #3196
