### ISSUE TITLE
Zero-width space in code block fences

### ISSUE THREAD

**Issue by Lakitna** [typora/typora-issues#4493]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Typora inserts zero-width spaces in nested code block fences. This breaks my Markdown tooling downstream. Zero-width spaces are represented by red dots in this image:

![image](https://user-images.githubusercontent.com/22448210/123999363-ba7c4d00-d9d2-11eb-9f47-ebe193cc1cfa.png)

**To Reproduce**

Create a nested code block outside of source code mode. That's it.

**Expected behavior**

Typora creates the following source code:

~~~
````
```
hello
```
````
~~~

This is proper Markdown in all tooling I've used so far, including here on Github :) Though Typora is not able to render it properly:

![image](https://user-images.githubusercontent.com/22448210/123999903-4bebbf00-d9d3-11eb-9de4-91f7cef584ac.png)

Alternative solution:

Typora creates the following source code:

````
~~~
```
hello
```
~~~
````

This does render as expected:

![image](https://user-images.githubusercontent.com/22448210/124000090-86555c00-d9d3-11eb-9630-e42a07619bbd.png)

**Sample Markdown File**

As above

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19042.1052

**Typora Version**
0.10.11 (beta)

**Additional context**

Might be related to #403

**Comment by abnerlee** [comment]
#3110

**Comment by abnerlee** [comment]
should be fixed

**Comment by Lakitna** [comment]
Confirmed that it's fixed :) Thank you!
