### ISSUE TITLE
[Feature] Indent entire paragraph without using bullet points.

### ISSUE THREAD

**Issue by Harrison-F** [typora/typora-issues#4495]
It would be great if I were able to indent an entire paragraph without turning it into a bulleted item.

For the time being, it seems one can only use Tab to indent the first line, without any clear way to indent the second line of the paragraph.

This could be as simple as changing the 'List Indentation' shortcuts "ctrl + ], ctrl + [" to simply 'Indentation' shortcuts and allowing it to effect both paragraphs and list items.

Example here:

![Typora Indent Paragraph example](https://user-images.githubusercontent.com/85464735/124153413-63be5400-da62-11eb-8cac-ff050f7db945.png)

Many thanks,

Harrison

**Comment by abnerlee** [comment]
Hmm... It is not supported in markdown. You can use blockquote or code block based on your needs, but just indent a paragraph is not supported.

Or, use `<p style="padding-left: 4ch">text</p>`.
