### ISSUE TITLE
Custom branch names in Flowchart do not display

### ISSUE THREAD

**Issue by pjmv** [typora/typora-issues#4498]
**Describe the bug**
When trying to display flowcharts with the `flow` code block, use of custom branch names flowing down from conditions is not possible. Trying to use `yes@foo` or `no@bar` in a condition results in the branches not being displayed at all 

**To Reproduce**
1. Create a new file
2. Create a flow block
3. Paste the example below, taken directly from the [flowchart-js documentation page](http://flowchart.js.org/)

```
st=>start: Need something to be translated!:>https://www.localistars.com[blank]
e=>end: Be happy!:>https://youtu.be/e6Ede8hdU8c
cond=>condition: Are you a client
or a translator?
subc=>subroutine: Why should you choose a localistar?:>https://www.localistars.com/for-clients.html
subt=>subroutine: Why should you become a localistar?:>https://www.localistars.com/for-translators.html
op=>operation: Check out how it works!:>https://www.localistars.com/how-it-works.html
io=>inputoutput: Work together with your partner!:>https://www.localistars.app/login

st->cond
cond(no@client)->subc->op->io->e
cond(yes@translator)->subt->op->io->e
```

4. See error (see attrached screenshot)

**Expected behavior**
Seing the full flowchart 

**Screenshots / Screencasts**
![Screenshot_2021-07-02_15-19-49](https://user-images.githubusercontent.com/26112873/124281674-3cdb4d00-db4a-11eb-9a9f-cc2d5743cb4d.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Typora Version**
e.g: 0.10.11

**Comment by abnerlee** [comment]
fixed in new release
