### ISSUE TITLE
Suggestions on usability

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#45]
## Project management

Typora already has the wonderful table of contents in the sidebar. For still longer pieces, article collections and such, it would be great to have a simple file dialog where the user can group the files that belong together.

See this screenshot, for example: http://i0.wp.com/it-enquirer.com/files/2015/03/Personal.png (Perhaps something less than this level of sofistication would do great!)
## Speaking of sidebar… (toc item link area)

Currently the toc items in the sidebar have a link area so that only the text is the link. It would be way nicer to have the whole hover box as a link. This seems to do the trick in `base-control.css`:

``` css
span.outline-label {
    display: block;
}
```

(Currently `display` is set to `table-cell`.)
## Better quotes

Instead of "normal" quotes, we should have “smarter” ones (thats "" vs. “”).

Something called Smartypants is rumored to accomplish this; http://daringfireball.net/projects/smartypants/
## Harder line breaks

Hard line break, `<br>`, is sometimes needed. `SHIFT+ENTER` does this quite nicely in other programs.

**Comment by yetty** [comment]
+1 for hard line break

**Comment by abnerlee** [comment]
Temporary smart quote can work like this:

Enable Smart Quote from Edit->Substitutions->Smart Quotes from menu bar. But that will also apply smart quotes on link/image titles, like `[a](b “cc”)`

**Comment by vassudanagunta** [comment]
These should be broken up into separate issues, then this one closed.

**Comment by abnerlee** [comment]
> Project management
