### ISSUE TITLE
freeze after insert local image

### ISSUE THREAD

**Issue by hackasc** [typora/typora-issues#450]
//听说作者是国人,所以就不用蹩脚的英文了；)。另外觉得typora做的很优雅,感谢。
问题重现：
插入本地图片步骤。
第一步键入：`![]()`
第二步键入：`![](.\abc.png)`
此时光标在字母‘g’的后面,‘)’的前面；按左箭头移动光标(上下左右都试试),会卡死。

**Comment by abnerlee** [comment]
Typora version?

**Comment by hackasc** [comment]
0.9.22 beta
Thanks

**Comment by zhin2929** [comment]
我也同样，不管是Linux版本，还是windows10下的Typora，都是插入图片就卡死，只能杀死进程。而且Linux下还无法显示图片。。。

**Comment by be5invis** [comment]
Not only local images, but ALL images will cause a freeze.

**Comment by be5invis** [comment]
Only happens when **inserting an new image**. Opening a MD with images will not freeze.

**Comment by abnerlee** [comment]
should be fixed in new version
