### ISSUE TITLE
Symbols sort order in File Tree is different from Windows Explorer

### ISSUE THREAD

**Issue by alexgoussev** [typora/typora-issues#4500]
Typora 0.10.11, Windows 10

Sort order in Windows Explorer:
**!  #  $  %  &  (  -  @  [  ^  _  `  {  ~  +  =**

Sort order in Typora File Tree:
**_  -  !  (  [  {  @  &  #  %  `  ^  +  =  ~  $**

Why is that and how to fix it?

**Comment by abnerlee** [comment]
fixed in new release

**Comment by alexgoussev** [comment]
> fixed in new release
@abnerlee 
I've tested the latest ver. 0.11.0. 
Why sorting has not been changed in natural order mode?

**Comment by abnerlee** [comment]
try sort by alphabet
