### ISSUE TITLE
[Feature] Display line numbers in source code mode on all lines

### ISSUE THREAD

**Issue by TomasHubelbauer** [typora/typora-issues#4502]
Hi, I have not found this particular issue using search, all results seem to be related to source code blocks.

I'd like to request a configuration option for displaying line numbers when in source code mode, not just the first, last, every 10th and current line number as it appears to work today:

![image](https://user-images.githubusercontent.com/6831144/124919204-38a1aa80-dff6-11eb-84bc-a82e63fbf00f.png)

**Comment by abnerlee** [comment]
It is a style preference. Use 
```
#typora-source .CodeMirror-linenumber {
visibility: visible !important; 
}
```
