### ISSUE TITLE
[Feature] Open newly created file automatically regardless of save status of the current file

### ISSUE THREAD

**Issue by TomasHubelbauer** [typora/typora-issues#4503]
This is a follow-on to #1321.

I'd like to request a configuration option that would make it possible to automatically have a newly created file open in the editor regardless of whether the current file is edited or not.

Additionally, I have Typora configured to auto-save files, so I'd expect newly created files to open automatically every time, since my currently opened document can't be in an edited state ever (as it auto-saves after every change), but that's not happening. I think it would make sense to even do this as a default in case the user has auto-save on, so that each new file created is automatically opened in the editor when the auto-save is on even without a new configuration setting.

**Comment by abnerlee** [comment]
duplicated with #3794
