### ISSUE TITLE
Yaml supported TOC [Feature] 

### ISSUE THREAD

**Issue by Blackhawke** [typora/typora-issues#4505]
First, I really want to thank the dev team for this project. It's the best specialized editor I've run across in years, and as a writer and publisher, I've tried many, believe me. I love the detailed, on-the-fly rendering, and the ability to turn it off, if need be. I also love the fact that the editor starts in a kind of "view mode". It makes it work like a viewer that instantly turns into an editor.

You've done a beautiful job with footnotes also. Love the popup. It's like the epub 3 implementation in most ebook readers. Then you go the extra distance with reverse lookup, tying the footnote back to the text. Well done! We have thousands of pages of notes, references, and scenes we keep in markdown files, with footnotes. We'll use the crap out of that, to be sure.

One of the best markdown editors we had for a few years was the android app Epsilon Notes. Eugene also used YAML headers, and one of the fields he supplied was `toc:` with which users could supply the name of index, or table to contents reference files for folders. It makes it possible to build a wiki like system of folders and files that can all be quickly referenced from within the editor -- like a website. We keep our reference files (and manuscripts) in a git(olite) repo.

You've already got the sidebar (which Eugene also provided), adding a "TOC" tab that renders the file referenced in the `toc:` yaml header would be a great add, IMO.

Thanks for reading!

**Comment by abnerlee** [comment]
put into #1202
