### ISSUE TITLE
Upload all local images fails even though uploading a single image works without problem

### ISSUE THREAD

**Issue by FelixOutta** [typora/typora-issues#4507]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I want to upload all local images. I main have `.png` files which have been recorded with cmd + ctrl + shift + 4 on mac, not sure if it conflicts with typora in same way, but it works when validating it in settings and it works when I upload a single image only with right click on it -> upload image

**To Reproduce**
not sure if it reproducable:

1. Go to format
2. Click on images -> upload all local images
3. it starts loading 
4. after a couple of seconds it shows error which images could not be uploaded due to time out. 

**Expected behavior**
upload all local images

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/79710091/125301045-e381d380-e32a-11eb-8fe0-27bf4a7b95bd.png) ...some long path... 
![image](https://user-images.githubusercontent.com/79710091/125301098-ee3c6880-e32a-11eb-898d-0f95be86fc34.png)

**Sample Markdown File**
not sure how to upload with the required images since it uses a system path. 

**Desktop (please complete the following information):**
 - OS: macos 11.4

**Typora Version**
e.g: 0.10.11

**Comment by abnerlee** [comment]
The error message is from your image uploader instead of typora, so could you confirm if your uploader can take multiple images and upload them without any issue?
