### ISSUE TITLE
Control over size of sequence diagrams on PDF export

### ISSUE THREAD

**Issue by ianmorty** [typora/typora-issues#451]
Currently, the default font size / size of the image used when exporting sequence diagrams can cause the image to be cropped and lose information e.g.

![screen shot 2016-12-05 at 13 09 26](https://cloud.githubusercontent.com/assets/7836253/20886124/5f624852-baec-11e6-9a05-72c5da4d5e51.png)

Could we scale the image used down to fit the paper size or allow the setting of a font size in the theme ?

**Comment by lrkwz** [comment]
Image is complete when exporting to ```docx``` thought ```pandoc```

**Comment by sachinmaheshwari** [comment]
Here is a workaround for this issue.

1. Export your document as HTML.
2. Open exported HTML file in Chrome.
3. Print it as PDF and in more options, you can select a larger page size such as A3, A2, A1 or A0 which is sufficient to fit your diagrams. Save it as PDF.
4. Now you can change the page size in PDF using multiple ways. I did it using Preview app of Mac by Exporting it again as PDF with another page size (A4 in my case).

**Comment by abnerlee** [comment]
Should be fixed in the newest version. The dialog fill auto fit the width
