### ISSUE TITLE
Undesired character sequences replacement in URLs

### ISSUE THREAD

**Issue by jmkeil** [typora/typora-issues#4511]
**Describe the bug**
Opening a link by clicking the link text with CONTROL-key pressed will in some cases not open the actual URL, but a modified URL, as the character sequence `&not[` get replaced by `¬[` (the `[` is relevant to be present). This does not happen, if one clicks on the URL itself (with CONTROL-key pressed).

**To Reproduce**
1. Add `[link with a problem](http://example.org?var=value&not[]=value)` to a file and move the courser somewhere else to collapse the Link URL
2. Hold CONTROL-key pressed and click on the link text
    * this opens `http://example.org/?var=value¬[]=value` in the browser
3. Place the courser into the link to expand the URL for editing 
4. Hold CONTROL-key pressed and click on the link text
    * this opens `http://example.org/?var=value¬[]=value` in the browser
5. Hold CONTROL-key pressed and click on the URL
    * this opens `http://example.org?var=value&not[]=value` in the browser

**Expected behavior**
In all cases (2, 4 and 5) the URL `http://example.org?var=value&not[]=value` should be opened in the browser.

**Desktop:**
 - OS: Debian GNU/Linux 10 (buster)

**Typora Version**
 0.10.11 on Linux

**Additional context**
A real world example that makes this issue practically relevant:
* `[real world example](https://gitlab.com/gitlab-org/gitlab/-/issues?scope=all&state=opened&not[label_name][]=feature)`
    * Text opens: `https://gitlab.com/gitlab-org/gitlab/-/issues?scope=all&state=opened¬[label_name][]=feature`
    * URL opens: `https://gitlab.com/gitlab-org/gitlab/-/issues?scope=all&state=opened&not[label_name][]=feature`

**Comment by abnerlee** [comment]
should be fixed in 0.11
