### ISSUE TITLE
copy image use relative path add "./"

### ISSUE THREAD

**Issue by gerryge** [typora/typora-issues#4512]
This is my setting:
![image](https://user-images.githubusercontent.com/6952917/125937806-4b291d57-fd1d-47aa-8176-e309c35612bb.png)

When I copy an image and paste to md file, it will generate the code like this:
```
![avatar](typora.assets/avatar.png)
```
![image](https://user-images.githubusercontent.com/6952917/125938158-b5dfde43-bfc6-4b01-a95e-1f67a4379ef8.png)

My feature request is add ./ at the begin of the relative path 
```
![avatar](./typora.assets/avatar.png)
```
In some Static Site Generator it need ./ at the beginning. For example. [VuePress](https://vuepress.vuejs.org/)
![image](https://user-images.githubusercontent.com/6952917/125938692-85bee54c-4156-448c-9699-6167b337c529.png)

**Comment by mapxn** [comment]
I have the same requirement.
`![image](./xxx/image.png)` is a more general way of expressing relative paths.

**Comment by abnerlee** [comment]
supported in 1.4.4
