### ISSUE TITLE
Math arrays do not render properly

### ISSUE THREAD

**Issue by zoof** [typora/typora-issues#4513]
- [ x] Searched existing issues to avoid creating duplicates.

- [x ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x] Searched http://support.typora.io/

----

**Describe the bug**
First character in a math array is ignored.

**To Reproduce**
1. write latex code for a math array.  
2. first character will be ignored

**Expected behavior**
Array should render correctly.

**Screenshots / Screencasts**
![Screenshot_2021-07-16_15-00-44](https://user-images.githubusercontent.com/1737483/125996357-2b6688a4-1251-4266-8aac-ad89276892b4.png)

**Sample Markdown File**
```
$$
\begin{array}
xy
\end{array}
$$
```

**Desktop (please complete the following information):**
 - OS: Debian Buster 64 bit
 
**Typora Version**
0.10.11

**Additional context**

**Comment by abnerlee** [comment]
Is is same with https://www.mathjax.org/#demo

I guess it is the expended behavior.

You could try
```
$$
\begin{array} {}
d
\end{array}
$$
```
