### ISSUE TITLE
[Feature] Automatic language selection?

### ISSUE THREAD

**Issue by rXYZkit** [typora/typora-issues#4517]
1
![image](https://user-images.githubusercontent.com/45787079/126084044-0233041a-eece-4c2c-97ce-a4f2aa603cc6.png)
![image](https://user-images.githubusercontent.com/45787079/126084297-29679d9d-a4bd-4641-8a6a-e73fc339f51f.png)

2
![image](https://user-images.githubusercontent.com/45787079/126084056-6c155802-97cd-4293-904d-0f1a876c79e1.png)

When using the above two methods of setting the language, even if only one language is prompted, the user must still type the full name and then press Enter or press the down arrow and then press Enter. So it looks like the language hint serves to tell the user that the spelling is correct? Is it possible to implement the language selection that automatically reads the first prompt when Enter is pressed?

**Comment by abnerlee** [comment]
duplicated with #1639?
