### ISSUE TITLE
Error on LaTeX parsing / rendering of \mu

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [typora/typora-issues#4519]
Error parsing the following LaTeX snippet; error occurs for both inline (`$`) and multiline (`$$`) math-environments:

`10^{-4} \leq \mu_{\text{badness}} \leq 1 - 10^{-4}`

The error message is: _Missing open brace for subscript_.

This seems to be somewhat related to parsing the Greek letter μ (`\mu`), because `\alpha` works:
![image](https://user-images.githubusercontent.com/64133386/126132198-4a28a4b0-efbc-448c-ab49-1b3e828b1d91.png)
Notice how `\mu` is rendered in the screenshot! 

Here's the code from the screenshot above:

```latex
10^{-4} \leq{} \alpha_x \leq{} 1 - 10^{-4} \\

10^{-4} \leq{} \mu \leq{} 1 - 10^{-4} \\

10^{-4} \leq{} μ_x \leq{} 1 - 10^{-4} \\

% commented out, can't be parsed
% 10^{-4} \leq{} \mu_x \leq{} 1 - 10^{-4} \\

10^{-4} \leq{} \alpha_{\text{some text here}} \leq{} 1 - 10^{-4} \\

10^{-4} \leq{} μ_{\text{some text here}} \leq{} 1 - 10^{-4} \\
```

For reference, here's the LaTeX rendered using the [online rendering service from Codecogs](https://latex.codecogs.com/eqneditor/editor.php):

![image](https://user-images.githubusercontent.com/64133386/126132580-e3cc0979-701a-4d02-bf5a-a6a82ab0f32b.png)

The code if you would like to try it out:
```latex
10^{-4} \leq{} \alpha_x \leq{} 1 - 10^{-4} \\
10^{-4} \leq{} \mu \leq{} 1 - 10^{-4} \\
10^{-4} \leq{} \mu_x \leq{} 1 - 10^{-4} \\
10^{-4} \leq{} \alpha_{\text{some text here}} \leq{} 1 - 10^{-4} \\
10^{-4} \leq{} \mu_{\text{some text here}} \leq{} 1 - 10^{-4} \\
```
---

### Environment

**OS:** Windows 10

**Typora Version:** 0.10.11

**Comment by abnerlee** [comment]
should be fixed in 0.11.0
