### ISSUE TITLE
No way to exit the code block if it is the last element in the document

### ISSUE THREAD

**Issue by netvl** [typora/typora-issues#452]
Suppose I type a document and I start writing a fenced code block:
~~~
```whatever
...
```
~~~
Typora automatically creates a code block when I type the first characters of the fence, and when I press enter it moves the caret into the body of the code block. Then I can type the code, but I cannot exit the code block if it is the last element of the document, and there is no text below. Neither arrow keys nor the enter key (with various modifiers) work at all. To overcome this, I have to switch into the source code mode, move the caret manually after the code block, type something there and return back to the main mode. This is really infuriating.

I'm not sure if this is relevant, but I also cannot switch into the code mode by pressing Ctrl-/, the editor simply does not do anything.

I'm using Typora 0.9.22 under Linux.

**Comment by netvl** [comment]
Hmm, interesting. It seems that this does not happen all the time. Sometimes pressing the down key works.

**Comment by abnerlee** [comment]
Down arrow key or click somewhere blank will do the work
