### ISSUE TITLE
crashes when printing

### ISSUE THREAD

**Issue by stevenov** [typora/typora-issues#4522]
**Describe the bug**
Typora closes when printing on Linux (Ubuntu 20.04). Error is 'Segmentation fault (core dumped)'

**To Reproduce**
1. Go to File -> Print
2. Application closes

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2

**Typora Version**
e.g: 0.11.0 (beta)

**Comment by abnerlee** [comment]
https://github.com/electron/electron/issues/28828

**Comment by abnerlee** [comment]
@stevenov Did you run Ubuntu in VM, btw?

**Comment by stevenov** [comment]
@abnerlee Nope. I run it directly.

**Comment by jZ7He56RkPTYABUjfww4** [comment]
Same issue. Also Ubuntu 20.04.2, not in a VM.

**Comment by ZirconfleX** [comment]
Same here on Linux Mint 20 Cinnamon 4.6.7

Thought it was the PC and removed Typora completely.
Reboot and reinstalled it. 
Issue stays.

Only thing that works is print to PDF or better is to export to PDF and print from there.

**Comment by abnerlee** [comment]
Does 1.2.4 fix it?
