### ISSUE TITLE
[Feature] Auto-complete for hyperlinks to headings in the same file

### ISSUE THREAD

**Issue by TomasHubelbauer** [typora/typora-issues#4524]
I've seen #1231 and while I would like that feature, too, I would also like to suggest Typora has a feature where it would auto-complete internal links whenever the user types `#`. A dropdown would show, it would get filtered down as you type the slug (text but lowercase with dashes for spaces) or the text of the internal link and once committed by Enter or clicking, a MarkDown link syntax would get inserted with the heading text for the title of the link and the slug for the target.

**Comment by abnerlee** [comment]
seems duplicated with #2663
