### ISSUE TITLE
**`sth here`** can't work in ver0.11.0

### ISSUE THREAD

**Issue by Jordan20190913** [typora/typora-issues#4526]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
strong code like  **`sth here`** can't work in ver0.11.0

**To Reproduce**
1. type anything and select it
2. ctrl+B to strong it
3. ctrl+shift+` to code it

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/55272641/126411728-e4c005eb-8848-40e2-9815-e3f791ef8d15.png)

**Desktop (please complete the following information):**
 - Windows 10 64bit

**Typora Version**
e.g: 0.11.0

**Comment by abnerlee** [comment]
fixed in 0.11.1
