### ISSUE TITLE
Can't use "\\" to move to a newline in $$...$$ in V0.11.0

### ISSUE THREAD

**Issue by Seanlam1124** [typora/typora-issues#4527]
**Describe the bug**
Can't use "\\" to move to a newline in $$...$$ in V0.11.0

**To Reproduce**
$$
abcdefg \\
asdsq
$$

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/49198853/126419277-593f88e7-644a-48b2-8e22-37ce611c255f.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - Window10 64bit

**Typora Version**
0.11.0

**Comment by abnerlee** [comment]
#4523
