### ISSUE TITLE
Shortcut key info is missing in main menu option

### ISSUE THREAD

**Issue by Geeyun-JY3** [typora/typora-issues#4529]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Shortcut key info is missing in main menu option (both on classic and unibody style)

**To Reproduce**
1. Right click on menu icon
2. Navigate to any main menu

**Expected behavior**
Shortcut key info shown

**Screenshots / Screencasts**
On Windows classic style
![image](https://user-images.githubusercontent.com/49396421/126433647-e13e9151-761f-43db-9afd-e2307ec7460b.png)
On Windows unibody style
![image](https://user-images.githubusercontent.com/49396421/126426895-d44ab216-c90e-4f56-959b-204cc8c31258.png)

**Sample Markdown File**
no need

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1110 64bit

**Typora Version**
0.11.0 beta

**Additional context**
nope

**Comment by abnerlee** [comment]
I can see the shortcut on my PCs...

Does menu item works normally in your PC? Does older versions of Typora contains shortcuts?

Did you modified "keyBinding" on advanced setting, if so, will reset advanced setting fix this?

And what's your PC locale, btw?

**Comment by Geeyun-JY3** [comment]
> Does menu item works normally in your PC?

Yes.

> Does older versions of Typora contains shortcuts?

Yes. I have reverted to 0.10.11 and 0.10.11 does contain shortcut key info.
BTW, some shortcut key info still can be seen in the menu. It seems that only the funtion keys info is not missing.
![image](https://user-images.githubusercontent.com/49396421/126470479-f6d26fdb-18fe-4246-a6f3-47bcbb1dd8b3.png)

> Did you modified "keyBinding" on advanced setting, if so, will reset advanced setting fix this?

I don't modified it and I try resettig it. Not fix it.

> And what's your PC locale, btw?

Country or region: United States

Windows display language: Chinese (Simplified, China)

**Comment by abnerlee** [comment]
1. possible to provide the log file (https://support.typora.io/Get-Logs/) ?
2. If you change language in Typora to English or Chinese, does this still happens?

**Comment by Geeyun-JY3** [comment]
> 2\. If you change language in Typora to English or Chinese, does this still happens?

Still happen.
![image](https://user-images.githubusercontent.com/49396421/126508685-e9df1d1c-a275-48d8-a044-435436b0fea2.png)

**Comment by Geeyun-JY3** [comment]
> 1\. possible to provide the log file (https://support.typora.io/Get-Logs/) ?

I will send it to you later.

**Comment by Geeyun-JY3** [comment]
Oh I have uninstalled and installed Typora again and fix this bug. 

But another bug is found. The UI language didn't follow my Windows display language when I choose `System Default`.

**Comment by Geeyun-JY3** [comment]
Now I reproduce the [key info bug](https://github.com/typora/typora-issues/issues/4529#issue-949328753) after I downgrade to 0.10.11 then upgrade to 0.11.0 again, at the same time the [UI language bug](https://github.com/typora/typora-issues/issues/4529#issuecomment-884329307) is “fixed”.

**Comment by abnerlee** [comment]
How about 0.11.1?

**Comment by Geeyun-JY3** [comment]
0.11.1 fixs it.
