### ISSUE TITLE
writing $2$ automatically results to $$ in v.0.11 beta

### ISSUE THREAD

**Issue by raylv17** [typora/typora-issues#4530]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**
1) Write '$[number]' to initiate mathmode and then press enter to start newline. Do not close mathmode.
2) In the new line, write $ to close mathmode.
3) Backspace to go back to the previous line. Observe that this will erase everything written within the mathmode and leaves '$$'
4) Now, within the $$ symbols, write 2\*space\*, observe that this will automatically be erased. This is the buggy behavior.
5) It only works for the number 2 in my case. Writing 3[space] or any other number will not replicate the behavior.
**Expected behavior**

**Screenshots / Screencasts**
https://youtu.be/7NfrQn4B9LA

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
Windows 10 64bit

**Typora Version**
v0.11

**Additional context**

**Comment by abnerlee** [comment]
I'm not able to reproduce this, possible to attach a screencast or more details?

**Comment by raylv17** [comment]
The problem only occurred in one of the files. It didn't persist for a new file.

**Comment by abnerlee** [comment]
Possible to attach or share the sample file to <hi@typora.io> ?

**Comment by raylv17** [comment]
more details are added about the issue: 
included a video to provide a display of the buggy behaviour
included steps to replicate the behavior.

**Comment by abnerlee** [comment]
relates  #4536?

**Comment by abnerlee** [comment]
still happens in 0.11.2?

**Comment by raylv17** [comment]
the issue is fixed in v0.11.2. Thank you!

**Comment by raylv17** [comment]
It is fixed in v0.11.2! Thank you!
