### ISSUE TITLE
Brcak 100%  when save a new note in  Mac OS12.0 Beta (21A5268h)

### ISSUE THREAD

**Issue by Neonbe** [typora/typora-issues#4532]
![image](https://user-images.githubusercontent.com/24536087/126476636-2bc71d86-daea-478c-9699-4aacef5def9e.png)

System : show in img
Path:
1.command+n to make a new note
2.input anythings
3.command+s
4.break

**Comment by abnerlee** [comment]
@Neonbe is there any crash log?

**Comment by Neonbe** [comment]
sorry, I am not a professional coder，could you  tell me how should i get the  crash log?

**Comment by abnerlee** [comment]
@Neonbe Did you saw a dialog like ![](https://www.maketecheasier.com/assets/uploads/2018/02/how-to-read-crash-reports-1.png) ?

Click Report it will show details, then copy and paste the detailed crash log here is OK

**Comment by abnerlee** [comment]
#4430
