### ISSUE TITLE
Very lagging when inputting a lot of words。。。。

### ISSUE THREAD

**Issue by xSeaGull** [typora/typora-issues#4533]

**Comment by xSeaGull** [comment]
macos , typora version 0.11.0 (5581)

**Comment by Alalalalaki** [comment]
Also this under 0.11.0. It worked quite well for earlier versions except in the case of very large content in the file, but the performance issue now knocks in way easily even in middle-size files.

**Comment by Alalalalaki** [comment]
I return back to 0.10.11 and the problem of sluggish inputting disappears.

**Comment by abnerlee** [comment]
@Alalalalaki @xSeaGull Possible to attach or share us <hi@typora.io> sample files that is slow?

**Comment by Alalalalaki** [comment]
@abnerlee I think any file with over 5000 words and 5 figures and 10 equations would replicate this issue.

**Comment by xSeaGull** [comment]
@abnerlee  Has been sent

**Comment by abnerlee** [comment]
should be fixed in 0.11.1

**Comment by Alalalalaki** [comment]
@abnerlee  I still have performance issue with math under 0.11.2

**Comment by abnerlee** [comment]
> I still have the performance issue with math comparing to 0.10.11.

Possible to attach a screencast?
