### ISSUE TITLE
can not work "copy image to current/custom folder"

### ISSUE THREAD

**Issue by keitasumiya** [typora/typora-issues#4534]
**Describe the bug**
I drag and drop / copy and paste an image into Typora but it doesn't work correctly. 
Actually, "copying" message was shown but it has never ended. Moreover, the image file wasn't copied into my local folder. 
This problem was firstly occurred before Typora ver. 0.11.0. 

**To Reproduce**
1. open Typora
2. drag and drop / copy and paste an image file into Typora
3. "copying" message is shown but it has never ended
4. the image file doesn't copy to my local folder

**Expected behavior**
end copying and make an copy of the image into my local folder

**Screenshots / Screencasts**
https://youtu.be/hI4QtJ1WQxY

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur. ver. 11.4
 - Macbook Air M1 chip

**Typora Version**
0.11.0

**Additional context**

**Comment by shelldoom** [comment]
I'm having the same problem, was working fine before but now it doesn't work after updating. (version 0.11.0)

**Comment by abnerlee** [comment]
@shelldoom @keitasumiya Please try 0.11.1, if not fixed, then please attach or share us <hi@typora.io> a sample md file.

**Comment by abnerlee** [comment]
duplicated with #4525
