### ISSUE TITLE
Was an equation numbering system via tex changed?

### ISSUE THREAD

**Issue by keitasumiya** [typora/typora-issues#4535]
I usually use tex function on Typora. 
At ver. 0.11.0, was the numbering system via tex changed?

An example is the followings: 

```
$$
\begin{aligned}
y &= \cos x\\
y &= \cos x\\
y &= \cos x\\
\end{aligned}
$$
```

Then, at old version, this equation doesn't have a number like a attached image : 
![test_0-9-9-36-2](https://user-images.githubusercontent.com/15891018/126519753-1c258042-d871-4df0-a0ba-caa50aaeb7c6.png)

However, new version, this equation have a number : 
![test_0-11-0](https://user-images.githubusercontent.com/15891018/126519762-72440cf1-08b3-4536-b671-0f6643b9cbcd.png)

This is a big change for me. Therefore, I would like to know if this change is a bug or a specification change.

**Comment by abnerlee** [comment]
use 
```
\begin{align}
y &= \cos x\\
y &= \cos x\\
y &= \cos x\\
\end{align}
```
see https://tex.stackexchange.com/questions/8788/which-one-should-i-use-beginalign-or-beginaligned
