### ISSUE TITLE
newline(enter)+backspace in mathmode produces an empty mathmode line. (video provided)

### ISSUE THREAD

**Issue by raylv17** [typora/typora-issues#4536]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
In mathmode ($...$), if you write something, then press enter to get newline, then backspace to get back the previous line, it will produce it will erase whatever is written in the mathmode and create an empty $...$ mathmode line.

**To Reproduce**
1) Write a line in mathmode
$a+b+c$
2) Insert a line break just before closing the mathmode
$a+b+c
$
3) Backspace to bring the $ back to the same line
4) This is what results
$$
An empty mathmode line.

**Expected behavior**
It shouldn't erase the line, the expected behavior is: backspace should only erase the newline and not everything inside $...$.

**Screenshots / Screencasts**
https://youtu.be/YPHRagjc51k

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

**Typora Version**
v0.11.0 (beta)

**Additional context**

**Comment by raylv17** [comment]
Yes, but not entirely. 
#4536 mostly focuses on the fact that the bug behaves this way specifically for the character "2", and not any other character.

**Comment by abnerlee** [comment]
should be fixed in 0.11.2
