### ISSUE TITLE
Inline code rendering issue in Link when the link begins with inline code

### ISSUE THREAD

**Issue by yangliping** [typora/typora-issues#4537]
**Describe the bug**
Typora render inline code in link correctly when the inline code in the middle of the square brackets. If the incode code backtick quote just follow the left square bracket, it would not render correctly.

**To Reproduce**
See the markdown code sample below.

**Expected behavior**

Render the link the same way no matter where the inline code is.

**Screenshots / Screencasts**

<img width="811" alt="image" src="https://user-images.githubusercontent.com/6970919/126583339-c15e876d-38ae-45a5-b58e-555034ea1b76.png">

**Sample Markdown File**

```
[`xprt`: data for NFS mounts in `/proc/self/mountstats` is per-fileserver, not per-mount](https://utcc.utoronto.ca/~cks/space/blog/linux/NFSMountstatsXprtII)

[xprt: data for NFS mounts in `/proc/self/mountstats` is per-fileserver, not per-mount](https://utcc.utoronto.ca/~cks/space/blog/linux/NFSMountstatsXprtII)
```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur v11.4

**Typora Version**
e.g: 0.11.0 (5581)

**Comment by abnerlee** [comment]
should be fixed in 0.11.1
