### ISSUE TITLE
[Feature] Better Uniformed Style for Warning in Math Block

### ISSUE THREAD

**Issue by Williams-Ren** [typora/typora-issues#4538]
![image](https://user-images.githubusercontent.com/45218090/126601886-faf053b1-7908-4d4c-bf7e-d012e68b9a42.png)

The warning here poped out too much which is not having a uniformed style with the others, will there be a way to fix it through .CSS file?

**Comment by abnerlee** [comment]
They are generated by MathJax, and not stylized by CSS code.

I think it should be ok as warning style. I will wait and see if more users requires a less popped warning or not.
