### ISSUE TITLE
Is there an option for re-opening files and windows at startup?

### ISSUE THREAD

**Issue by Fil** [typora/typora-issues#454]
would be super useful.
cf. https://support.apple.com/en-us/HT204005

thank you!

**Comment by abnerlee** [comment]
It is supported on macOS. Need to set-up in system preference

**Comment by Fil** [comment]
Typora is the only program that doesn't do that (on my Mac). How can I find out how to fix this?

**Comment by abnerlee** [comment]
Please confirm you are using the latest version of Typora.

And unselect the options circled in  https://support.apple.com/en-us/HT204005

Then quit Typora and re-open, will the window be restored?

**Comment by Fil** [comment]
Oh! OK, that was checked. Thanks! And sorry for the trouble.

**Comment by dtw45** [comment]
Hello,

I think this issue has resurfaced. I've already made sure the "Close windows when quitting an app" setting was not selected. But documents are not restored.

OS version: macOS Sierra 10.12.6
Typora version: 0.9.9.10.6
Steps to reproduce the bug:
- Open Typora
- Click on "Open Folder..."
- Select a recent location
- Select a file
- Edit & save
- Close via red `x` button
- Open Typora via launcher
- Previous document not restored?

Thanks!

**Comment by abnerlee** [comment]
> I've already made sure the "Close windows when quitting an app" setting was not selected
> Close via red x button

You need to "quit" typora by `cmd+Q`, click "x" is not "quit" the app

**Comment by HADB** [comment]
The same as @dtw45, window cannot be restored after quitting by `cmd+Q` or clicking `x`. "Close windows when quitting an app" setting are not selected.
