### ISSUE TITLE
Cannot erase everything beyond an apostrophe(') symbol. 

### ISSUE THREAD

**Issue by raylv17** [typora/typora-issues#4540]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
If a lne contains both a mathmode block (\$...\$) and also an apostrophe symbol ('), then the line cannot be erased using backspace. It will always stop wherever the apostrophe is located. (full description provided in the video below) 

**To Reproduce**
1) write anything within the $$ symbols. 
$2$
2) on the same line write anything with an apostrophe but it should not be in mathmode.
$2$ asdf'jklmn
3) now starting from the end of the line, try backspacing everything.
4) observe that it the backspace will stop wherever the apostrophe is, and it won't erase anything beyond the apostrophe.
$2$ asdf

**Expected behavior**
Backspace should remove everything as long as it is pressed.

**Screenshots / Screencasts**
https://youtu.be/ApQH0c0j86Q

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
- Windows 10 64bit.

**Typora Version**
v0.11

**Additional context**

**Comment by abnerlee** [comment]
should be fixed in 0.11.2
