### ISSUE TITLE
Updates popup: Cannot click "Download Update", "Remind Me Later", "Skip This Version"

### ISSUE THREAD

**Issue by bolducs** [typora/typora-issues#4541]
- [ x] Searched existing issues to avoid creating duplicates.

- [ n/a] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
Cannot download today's new version 0.11.1—nothing happens when I click **Download Update**; the other buttons (Skip This Version, Remind Me Later don't wok either.

**To Reproduce**
1. Open Typora (version 0.11.0)
2. Notice the Updates window prompts you to install 0.11.1
3. Click Download Update
4. Notice that nothing happens
5. Try the other buttons and notice they don't work either

**Expected behavior**
Clicking Download Update should work as it used to.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/87207673/126705447-96a38e16-b98e-4167-80df-25dca4d059ed.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.11.0

**Additional context**

**Comment by VictorS8** [comment]
This happens with me as well! Same steps

**Comment by IBRice101** [comment]
This also happens with me

**Comment by abnerlee** [comment]
should be fixed in 0.11.2, but 0.11.2 requires manually download from https://typora.io

**Comment by yzy1996** [comment]
For Windows, the exact download link is https://typora.io/windows/dev_release.html
