### ISSUE TITLE
进入官网，电脑直接死机怎么破？

### ISSUE THREAD

**Issue by WangJincheng4869** [typora/typora-issues#4543]
https://typora.io

进入官网，电脑直接黑屏，死机，风扇狂转，只能强制重启。

**Comment by WangJincheng4869** [comment]
应该是新版本的 Edge浏览器的问题，在chrome上没有该问题。
![image](https://user-images.githubusercontent.com/41162158/126755837-a8a09044-04f2-4685-8771-d25f56235716.png)

**Comment by abnerlee** [comment]
使用隐身模式 （不加载插件）试一下呢？

我试了92的Edge，没有该问题啊
