### ISSUE TITLE
The render cannot display optional title for reference links

### ISSUE THREAD

**Issue by edentsai** [typora/typora-issues#4544]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

The render cannot display the optional title (alt-text) for [references links](https://support.typora.io/Markdown-Reference/#reference-links)

**To Reproduce**

1. Use this raw Markdown as example:

```markdown
### Reference Link Cannot Display the Optional Title (Alt Text)

Use inline links can display the title:

- Inline link 1: [Typora](https://typora.io "A truly minimal Markdown editor.")

Use reference links cannot display the title:

- Reference Link 1: [Typora][]
- Reference Link 2: [Typora][Typora]

[Typora]: https://typora.io "A truly minimal Markdown editor."
```

2. Rest the cursor on the inline link 1, the render will display the optional title.

3. Rest the cursor on the references link 1 or 2, the render doesn't display the optional title (but the link is works)

I think this may be a bug.

**Expected behavior**

When the cursor rest on the reference links,
the render should display the optional title just like the inline links does.

**Screenshots / Screencasts**

The render display the optional title when the cursor rest on the **inline links**:

![2021-07-24-041216-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126836315-549d9a8c-7462-4e9a-a8bb-be54ff67c77a.png)

![2021-07-24-041312-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126836383-37ec575b-71ab-4203-be14-526b0cf491d6.png)

The render cannot display the optional title when the cursor rest on the **reference links**,:

![2021-07-24-041359-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126836460-6b41a263-19fa-47f7-87ee-da81a21e7f26.png)

![2021-07-24-041447-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126836499-8d7ab960-9bfe-4252-a700-cebb32c401e6.png)

![2021-07-24-041533-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126836848-cc5747ec-212d-492f-bbc4-7634fe6fa397.png)

![2021-07-24-041622-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126836914-0567fbff-6439-4405-abe1-fbb05b1ab776.png)

**Sample Markdown File**

```markdown
### Reference Link Cannot Display the Optional Title (Alt Text)

Use inline links can display the title:

- Inline link 1: [Typora](https://typora.io "A truly minimal Markdown editor.")

Use reference links cannot display the title:

- Reference Link 1: [Typora][]
- Reference Link 2: [Typora][Typora]

[Typora]: https://typora.io "A truly minimal Markdown editor."
```

**Desktop (please complete the following information):**

macOS Big Sur (v11.4)

**Typora Version**

Typora Version 0.11.0 (5581) installed by Homebrew on macOS.

![2021-07-24-042155-cleanshot-Typora](https://user-images.githubusercontent.com/5071526/126837457-a8086541-cb3f-462e-bde3-d7fdd6aad6f0.png)

**Additional context**

None

**Comment by abnerlee** [comment]
fixed in 1.2.3
