### ISSUE TITLE
Error when trying to install latest version

### ISSUE THREAD

**Issue by jkelvie** [typora/typora-issues#4545]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
New version (0.11.2) is blocked from install by Microsoft Edge.

**To Reproduce**
Download Typora 0.11.2 using Microsoft Edge on Windows.
See this message in the downloads list:
"typora-setup-x64.exe was blocked because it could harm your device"

**Expected behavior**
I can download and install the new version.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/17267/126840656-47b0d6bf-ad2d-4a7c-a70d-8720e823f2d2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]

**Typora Version**
0.11.2

**Additional context**
I downloaded it directly from the website:
https://typora.io/#windows

**Comment by abnerlee** [comment]
Seems OK in my test -> https://www.virustotal.com/gui/file/3818b84e04b2fb5ea80962695f6fffa531f41efe3d52793b8b8ac77c78538f25/detection

You can click the "..." to continue

may be caused by #1801
