### ISSUE TITLE
"Download Update" button has no response

### ISSUE THREAD

**Issue by YueLu0116** [typora/typora-issues#4547]
----
**Describe the bug**
I tried to update to version 0.11.2. When I clicked the "Download Update" button in the "Update" window, nothing happened, without any response. Updates did not started. Same things happened in both computers in my company and home.

**Desktop:**
 - OS: Windows version 21H1 (19043.1110)

**Typora Version**
 0.11.0

**Comment by abnerlee** [comment]
sorry, it is a bug  #4541

**Comment by otav-o** [comment]
Same here
