### ISSUE TITLE
Access key (Alt + key combinations) issues

### ISSUE THREAD

**Issue by Geeyun-JY3** [typora/typora-issues#4548]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
1. Access key character is missing on Windows classic style when language is Chinese
2. Underlines are missing when one of the main menu is opened (Underlines will be shown after the main menu is opened once, or when the menu bar is focused) and the language is English.
3. Underlines are invisible in dark mode.

**To Reproduce**
(Enable `Underline access key when available`option, under `ms-settings:easeofaccess-keyboard`)
Click the main menu

**Expected behavior**
Underlines are shown normally.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/49396421/126443956-aff66899-49e9-477b-89d9-7170d617a9ab.png)

![typora](https://user-images.githubusercontent.com/49396421/126865052-22b3bc77-6fd7-436c-a43d-eddc47ecf5aa.gif)

![image](https://user-images.githubusercontent.com/49396421/126871476-d17bd134-73c1-4aa2-9224-2a022ea3a5f4.png)

**Sample Markdown File**
no need

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1110 64bit

**Typora Version**
0.11.0 beta

**Additional context**
There is no such bug on Windows unibody style.
![image](https://user-images.githubusercontent.com/49396421/126427746-761410a5-24bf-4142-bf16-b6333763f733.png)

**Comment by abnerlee** [comment]
same with #4529

please download 0.11.2 from typora.io

**Comment by Geeyun-JY3** [comment]
Sorry I forgot to change it. It can still be reproduced in 0.11.2.
![image](https://user-images.githubusercontent.com/49396421/126872772-bfc642f2-6362-4485-8f9a-628e5009d7b3.png)

**Comment by Geeyun-JY3** [comment]
@abnerlee 
Confirmed. I have uninstalled and installed Typora again. Still can reproduced it.

**Comment by abnerlee** [comment]
Will under be displayed when pressing Alt key?

**Comment by Geeyun-JY3** [comment]
> Will under be displayed when pressing Alt key?

Yes. I mention [above](https://github.com/typora/typora-issues/issues/4548#issue-952090081).
> Underlines will be shown after the main menu is opened once, or when the menu bar is focused

**Comment by Geeyun-JY3** [comment]
Oh it seems that pressing the Alt key would toggle the underlines appearance.

And it seems that the access key character is blocked when the language is Chinese. Notice the "dots" between the menus.
![image](https://user-images.githubusercontent.com/49396421/126903147-90921b2e-04c5-4e40-a93a-5dc64dd12620.png)

**Comment by Geeyun-JY3** [comment]
> 1. Access key character is missing on Windows classic style when language is Chinese

This bug seems to be fixed in 0.11.5 beta

> 2. Underlines are missing when one of the main menu is opened (Underlines will be shown after the main menu is opened once, or when the menu bar is focused) and the language is English.
> 3. Underlines are invisible in dark mode.

Still can reproduce these two bug.

**Comment by abnerlee** [comment]
#798
