### ISSUE TITLE
startup pop up update window is not clickable 

### ISSUE THREAD

**Issue by jiewangjs** [typora/typora-issues#4549]
![8r2WdyAc5C](https://user-images.githubusercontent.com/11204422/126899571-b4533e45-9217-42a7-a024-aad9cad01c6a.gif)

I pressed the update button several times, but it had no effect at all.

**Comment by ThomasFindlay** [comment]
Got the same issue in version 0.11.1.

**Comment by abnerlee** [comment]
duplicated with #4541

Sorry, but please manually download 0.11.2 from typora.io
