### ISSUE TITLE
Feature requests also known from Ghostwriter

### ISSUE THREAD

**Issue by mschroen** [typora/typora-issues#455]
Although Typora overtook many other Markdown editors, there still is the [Ghostwriter](http://wereturtle.github.io/ghostwriter/) editor which remains one of the most competetive editors, I think. Ghostwriter is not WYSIWYG, but almost, and it has lots of great features that we would like to see in Typora, too:

- syntax-highlight for `@references` 
- Document statistics
- Session statistics
- Hemingway mode
- Various focus modes
- Export with various external pandoc options
- (open source)

**Comment by abnerlee** [comment]
I'm closing since they are now addressed in other different issues.
