### ISSUE TITLE
PDF export spins forever

### ISSUE THREAD

**Issue by MrTrillian** [typora/typora-issues#4550]
Typora 0.11.2 on Windows, Notes Dark theme, .md document containing only "1"

- I use `File > Export > PDF`, an "🔔 Exporting in progress..." spinner notification appears
- A dialog pops up about the export theme, I confirm "Print with default theme"
- After a small delay the save dialog shows, I confirm the location

**Result**: the "Exporting in progress..." message remains there and spins forever.
This is a recent regression.

**Comment by MrTrillian** [comment]
It turns out I had disabled the print spooler service after reports of a vulnerability. Typora should still not spin forever, but this is a low priority issue.

**Comment by abnerlee** [comment]
same issue with #3710
