### ISSUE TITLE
lagging with documents containing equations (macOS 11.2.3)

### ISSUE THREAD

**Issue by deltakam** [typora/typora-issues#4551]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
there is lagging every 1-2 sec or so. 

**To Reproduce**
create a new document
write down the $\sqrt{\frac{\sum_s^t \sigma_s^2 x_s^2}{\sum_s x_s^2}}$
copy-paste it like 50 times.
do a fast & continuous typing to see the lagging.

**Expected behavior**
there should be no lags

**Screenshots / Screencasts**
n/a

**Sample Markdown File**
[ttmp.md](https://github.com/typora/typora-issues/files/6875141/ttmp.md)

**Desktop (please complete the following information):**
environment: macOS 11.2.3 (macbook pro 15" 2019)

**Typora Version**
0.11.2

**Additional context**
n/a

**Comment by abnerlee** [comment]
should be fixed in 0.11.5
