### ISSUE TITLE
How to customize the font color of completed task in mermaid gantt?

### ISSUE THREAD

**Issue by legoming** [typora/typora-issues#4552]
When I using dark theme, such as [Drake](https://theme.typora.io/theme/Drake/), there're 2 issues:
1. Title and completed task is invisible

![image](https://user-images.githubusercontent.com/8018372/126925544-ebbd7f4f-00bb-47c1-9324-50d7541cb652.png)

2. The exported html is half-dark

![image](https://user-images.githubusercontent.com/8018372/126925587-a69ebe25-2072-41fa-9576-f225628a23d8.png)

How can I customize the color of completed task? And make the exported html in real dark format?

Thanks.

**Comment by abnerlee** [comment]
should be fixed in 1.4.4
