### ISSUE TITLE
multiple images drog and drop to editor result in constant "copying " hint

### ISSUE THREAD

**Issue by jiewangjs** [typora/typora-issues#4556]
https://user-images.githubusercontent.com/11204422/126987378-061fc550-2b4b-48e2-a591-44a38d46f53a.mp4

The "copying" hint just doesn't go no matter how time you wait. 
A simple restarting the app solves the problem. But again, this is very inconvinient.

**Comment by abnerlee** [comment]
Typora version?

**Comment by abnerlee** [comment]
In my tested not happened in 0.11.2
