### ISSUE TITLE
Line heights of display math blocks are too large

### ISSUE THREAD

**Issue by shihan-z** [typora/typora-issues#4557]
**OS:** macOS Big Sur
**Typora Version:** 0.11.2 (5601)
Following is the comparison between two versions of Typora rendering the same document with the same theme.
(⬅️ Version 0.10.11  |  Version 0.11.2 ➡️).
<img width="1700" alt="sc1" src="https://user-images.githubusercontent.com/57735663/127024383-6b2935dd-a900-4b7a-8eab-2130385c1710.png">
Hope to have a more consistent user experience after updates. Many thanks!

**Comment by abnerlee** [comment]
fixed in 1.4.4
