### ISSUE TITLE
copy button is disabled when opening a locked file(macos 11.5)

### ISSUE THREAD

**Issue by kidoflamancha** [typora/typora-issues#4558]
**Describe the bug**
I can't copy anything when opening a locked file with shortcut command+c

**To Reproduce**
1. open a locked file
2. select anything and copy

**Expected behavior**

**Screenshots / Screencasts**
the copy button in the menu bar is disabled
![image](https://user-images.githubusercontent.com/5253413/127084058-be7d297a-ce35-417f-8857-f7d2479eddd0.png)

only the right click works fine

![image](https://user-images.githubusercontent.com/5253413/127084130-01f71fac-ff97-48ca-b8da-2ce7b8bcbdc4.png)

**Desktop (please complete the following information):**
 - OS: macos 11.5

**Typora Version**
0.11.2(5601)

**Comment by abnerlee** [comment]
should be fixed in latest version
