### ISSUE TITLE
failed to upload images using picgo under linux

### ISSUE THREAD

**Issue by ajian2002** [typora/typora-issues#4560]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

linux 上使用picgo 2.2.2 和 typora 0.10.11(beta) 时
使用  验证图片上传选项 
出现  
![image](https://user-images.githubusercontent.com/37119488/127147546-242b2880-d2be-4602-a5a0-e6374b18cd71.png)

查看日志发现都没有报错
![image](https://user-images.githubusercontent.com/37119488/127147693-a1142db0-f24b-462a-8850-eba56675a5a8.png)

picgo端口是默认端口没有更改,单独上传图片也没有问题,但是typora无法自动将文件内链接替换

picgo设置的是第三方图床上传,未测试是否使用内置图床也会出现问题,但我觉得不是picgo的问题,应该是typora的问题,没有捕捉到picgo返回的链接

**Expected behavior**

至少图片可以正常上传并替换链接

**Screenshots / Screencasts**

上面已经附上

**Sample Markdown File**

无

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

Linux xib13 5.13.4-arch1-1 #1 SMP PREEMPT Tue, 20 Jul 2021 16:58:51 +0000 x86_64 GNU/Linux

**Typora Version**

0.10.11

**Additional context**

**Comment by abnerlee** [comment]
图上的 127.0.0.1:xx/xx 那个 url 是可以访问的吗？

**Comment by abnerlee** [comment]
直接在浏览器里面用
```
window.fetch("http://127.0.0.1:36677/upload", {
				method: 'POST', 
				body: JSON.stringify({
					list: [your-image-path]
				}),
			})
```
试下呢

Failed to fetch 就是访问 http://127.0.0.1:36677/upload 的时候没有收到 200 的返回

**Comment by ajian2002** [comment]
![image](https://user-images.githubusercontent.com/37119488/149958011-d80feaa1-896e-44dc-bb6a-c4a46889da43.png)

**Comment by abnerlee** [comment]
在空白的浏览器标签页里面试一下 https://github.com/typora/typora-issues/issues/4560#issuecomment-891919681 呢？

在其他地方也可以通过 http://127.0.0.1:36677/upload 上传的话，在 Typora 里面才有可能通过 http://127.0.0.1:36677/upload 上传

**Comment by XeCtvi** [comment]
> 在空白的浏览器标签页里面试一下 [#4560 (comment)](https://github.com/typora/typora-issues/issues/4560#issuecomment-891919681) 呢？
> 
> 在其他地方也可以通过 http://127.0.0.1:36677/upload 上传的话，在 Typora 里面才有可能通过 http://127.0.0.1:36677/upload 上传

在 chrome 无痕模式空白页下，尝试上传失败
<img width="459" alt="image" src="https://user-images.githubusercontent.com/10743176/185775331-4f8aa278-ec6d-4f67-83c5-4940f1d5daa5.png">

**Comment by XeCtvi** [comment]
> 在空白的浏览器标签页里面试一下 [#4560 (comment)](https://github.com/typora/typora-issues/issues/4560#issuecomment-891919681) 呢？
> 
> 在其他地方也可以通过 http://127.0.0.1:36677/upload 上传的话，在 Typora 里面才有可能通过 http://127.0.0.1:36677/upload 上传

但是我用 typora 触发图床自动上传，文件是能够成功上传的，图床有成功上传的图片

**Comment by N1ckeyQu** [comment]
> ![image](https://user-images.githubusercontent.com/37119488/149958011-d80feaa1-896e-44dc-bb6a-c4a46889da43.png)

我遇到的问题和你完全一致，一模一样的错误，picgo的日志显示success，图床上也能看到上传的图片，但是typora这边验证图片上传选项就是不行

**Comment by N1ckeyQu** [comment]
> ![image](https://user-images.githubusercontent.com/37119488/149958011-d80feaa1-896e-44dc-bb6a-c4a46889da43.png)

我遇到的问题和你完全一致，一模一样的错误，picgo的日志显示success，图床上也能看到上传的图片，但是typora这边验证图片上传选项就是不行

该issue已经关闭，是问题得到解决了吗？想了解下解决方案

**Comment by ajian2002** [comment]
> > ![图片](https://user-images.githubusercontent.com/37119488/149958011-d80feaa1-896e-44dc-bb6a-c4a46889da43.png)
> 
> 我遇到的问题和你完全一致，错误，图片的成功，一张图片也能看到上传的图片
> 
> 这个问题已经，是问题解决了吗？想了解下解决方案

使用npm下的picgo解决
