### ISSUE TITLE
Clicking Download Update and other buttons in the update modal is not working

### ISSUE THREAD

**Issue by TomasHubelbauer** [typora/typora-issues#4563]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.
- [x] Searched http://support.typora.io/

----

**Describe the bug**

I have Typora configured to check for updates. New update is available for 0.11.2, I am on 0.11.0. This is on Windows. I am presented with the modal to update with the Download Update button in focus. Clicking on the button does nothing. Using tab to go away from the button and then to focus it again and clicking does nothing. Pressing Enter with the button focused does nothing. Clicking the other buttons in the same modal does nothing either. Checking the Check updates automatically checkbox works, I can toggle it repeatedly, but clicking any of the buttons still does not work.

**To Reproduce**
1. Wait for new version modal on Windows
2. Attempt to click any button

**Expected behavior**
Button is clickable and does the relevant action. duh.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/6831144/127281672-366f8494-b8b7-45c6-8adc-6c6c0649f815.png)

None of these buttons are clickable.

**Sample Markdown File**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Typora Version**
e.g: 0.11.0

**Additional context**
N/A

**Comment by TomasHubelbauer** [comment]
Can I install the latest version manually without removing the current version? Will it preserve my settings? I worry about losing my settings, I'd rather stay on the current version if installing latest could lose them.

**Comment by Taswen** [comment]
Repetition #4559

**Comment by lijiedong** [comment]
I also can't update,

**Comment by janis-ax** [comment]
+1
