### ISSUE TITLE
new version 0.11.2 cannot download image to local dir

### ISSUE THREAD

**Issue by grj001** [typora/typora-issues#4564]
typora which is new version 0.11.2 cannot download image to local dir
it is still a http url when I copy text and image to typora

**Comment by abnerlee** [comment]
what's your setting?

Did you copy rich text or just plain text?

**Comment by irinify** [comment]
I also meet the same question. My version is 0.11.0, no matter copy image file from local dir nor from web, it just loading...

**Comment by irinify** [comment]
![Snipaste_2021-07-29_21-21-41](https://user-images.githubusercontent.com/15665834/127499960-192f46bd-378c-4497-b9c0-738aff1c4c93.png)

**Comment by abnerlee** [comment]
what about 0.11.2?

**Comment by grj001** [comment]
i am waiting for a new version

**Comment by abnerlee** [comment]
#4575
