### ISSUE TITLE
Scary ENOENT dialog when creating new file from command line

### ISSUE THREAD

**Issue by timrprobocom** [typora/typora-issues#4565]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
When opening a new document from the command line, we get an error dialog saying:
```
X  Failed to load file
   ENOENT: no such file or directory, open "C:\xxx\xxx\unknown.md"
```
On Windows, this is accompanied by the Windows warning tone.   Linux gets the same warning, but no tone.

**To Reproduce**
1. From a command line, type "typora unknown.md" (assuming you do not have a file called "unknown.md"...)
2. Observe frightening red X error dialog

**Expected behavior**
Creating a new document is a completely normal activity.  The user experience should be exactly as if the user had done File -> New.

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - OS: Ubuntu Linux 20.04

**Typora Version**
0.11.1

**Comment by abnerlee** [comment]
duplicated with #721

Currently new file from cmd has not been supported yet
