### ISSUE TITLE
[Feature] Merge and export all markdown files from a folder tree

### ISSUE THREAD

**Issue by hellohtetmyattun** [typora/typora-issues#4566]
I am not a coder. I am just an everyday user and I use Typora to write guidebooks for my work. And I love it.

I use folders for each book chapters / parts because I don't enjoy my writing space to be messy with many paragraphs while I write a certain chapter. The issue is, when it comes to exporting, I need to combine several markdown files into one.

**So I was thinking that it would be great if I can export all .md files under a folder tree at the same time while merging them into markdown or pdf format.** It would also be great if the order of merging can be done with the name of the folder or date of the markdown files. I name my folders and files in a specific way like
Chapter 1 - Chapter Name ( Folder )
Chapter 2 - Chapter Name ( Folder )
1.1 Title1.md
1.2.3 This is a subtitle.md so it can be sorted by folder name and file name.

It would be very useful for those who uses Typora to write long books while keeping their writing window clean and focused on a single chapter / topic.

Thanks for reading.

**Comment by abnerlee** [comment]
can be covered in #824
