### ISSUE TITLE
Keyboard shortcut (or menu item) for navigating to the next/prev H1/H2

### ISSUE THREAD

**Issue by jaromir-benes** [typora/typora-issues#4567]
I frequently use Typora in a, say, semi-presentation mode (with H1 and H2 separated by a large top margin from the previous one). It would be great to have a keyboard shortcut (or a menu item for which I could create my own keyboard shortcut) for navigating the top headings easily.

Many thanks for considering this one.

**Comment by abnerlee** [comment]
duplicated with #4048
