### ISSUE TITLE
Chinese symbols cannot be typed on the Windows platform, but the Mac platform can

### ISSUE THREAD

**Issue by chimmhuang** [typora/typora-issues#4568]
**Describe the bug**
Chinese symbols cannot be typed on the Windows platform, but the Mac platform can

**To Reproduce**
1. Switch the input method of windows to Chinese input method
2. Type any symbol.
3. See error

**Expected behavior**
Type any symbol, such as: comma (expected "，", actual ","), period (expected "。", actual "
."), money symbol (expected "￥", actual "$")

**Desktop (please complete the following information):**
OS version: Windows 10 64bit 19043.1110

**Typora Version**
0.11.2(beta)

**Comment by abnerlee** [comment]
which IME did you use?

**Comment by chimmhuang** [comment]
> which IME did you use?

Win10 native Chinese IME

you can google search "how to switch to chinese input on windows 10"

**Comment by abnerlee** [comment]
Did you disable this?

![image](https://user-images.githubusercontent.com/1621242/128830180-39f13b6a-ca9b-4e59-ac63-87ee5b9e8578.png)

---

I'm not able to reproduce this, and received similar reports from other users.

Could you check if the behavior is same in NotePad.exe or Chrome.exe?
Could you confirm is the IME is in Chinese mode and 全角 mode?

**Comment by chimmhuang** [comment]
> Did you disable this?
> 
> ![image](https://user-images.githubusercontent.com/1621242/128830180-39f13b6a-ca9b-4e59-ac63-87ee5b9e8578.png)
> 
> I'm not able to reproduce this, and received similar reports from other users.
> 
> Could you check if the behavior is same in NotePad.exe or Chrome.exe?
> Could you confirm is the IME is in Chinese mode and 全角 mode?

This switch is off, it’s not the problem you mentioned.

**Comment by abnerlee** [comment]
Would you post a screencast and does this happens in WordPad.exe? I'm not able to reproduce this.
