### ISSUE TITLE
Math blocks are not centered anymore when the file is exported into pdf

### ISSUE THREAD

**Issue by JRhin** [typora/typora-issues#4571]
- [ ] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
If you open the exported pdf  you can see that all the math blocks are not centered anymore

**To Reproduce**
1. Create a file with some math blocks
2. export the file into pdf
3. open the pdf and look at those blocks rendering

**Expected behavior**
It should put the blocks at the center of the line

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![bug](https://user-images.githubusercontent.com/87755735/127868402-b727df12-8685-47c1-a568-85bdd343086d.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.
[bug.md](https://github.com/typora/typora-issues/files/6917184/bug.md)
[bug.pdf](https://github.com/typora/typora-issues/files/6917190/bug.pdf)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 64bit

**Typora Version**
0.11.2

**Additional context**
nothing

**Comment by abnerlee** [comment]
same with #4562
