### ISSUE TITLE
Typora.exe running in Task, But Unable to display typora window, and running more than one in tasks.

### ISSUE THREAD

**Issue by ValarBinis** [typora/typora-issues#4572]
**Describe the bug**
typora.exe can be running in the Task, but can not display the window. And several Typora.exe Task can be running at the same time. but all can't show window.

**To Reproduce**
1、open the computer.
2、This problem may occur. Or Successful working.
3、after successful working, i closed the Typora and quickly restart it, This problem may occur.
4、Then this problem will show all the time until reboot my computer.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/35185099/128045678-3e13cf53-fe96-4cb2-af71-d77ffa55d2fb.png)
![image](https://user-images.githubusercontent.com/35185099/128045809-def6f0b4-6fb2-4625-bd90-f616f282585f.png)
**Down there is a Successful working**
![image](https://user-images.githubusercontent.com/35185099/128050145-06512e67-22db-4eee-afcd-dd17db5cb4c9.png)

**Desktop (please complete the following information):**
Win10 64bit 1809

**Typora Version**
0.11.2 and older

**Additional context**
I was uninstall a program named BaiduPinyin , it's a Input Method Application. After that ,probably, this problem show first time.

**Comment by ValarBinis** [comment]
I tried every version of 64bit  typora. the problem still happen. so I tried 32bit typora .because they using different files , Luckily, The Problem not happen. But My computer is 64bit, and i was always using 64bit typora before this problem appear. Anyway, I can using typora again. NICE!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by abnerlee** [comment]
Could you try kill every Typora.exe in task management then open Typora again, does this be solved?
If not, try kill every Typora.exe, uninstall, then reinstall again.

If still not solved, try to send us <hi@typora.io> or attach logs here, following https://support.typora.io/Get-Logs/
