### ISSUE TITLE
After adding a "title" to "reference", there will be more references when converting to PDF

### ISSUE THREAD

**Issue by NcuWen** [typora/typora-issues#4573]
for example:

```markdown
> ###### This is a reference

This is not a reference
```

result:

![image](https://user-images.githubusercontent.com/22836924/128155057-7faa3558-9b86-4f6c-90ce-c2359614e2ed.png)

But, There is no problem adding "plain text" to "references".

**Comment by abnerlee** [comment]
What is your OS / typora theme?
