### ISSUE TITLE
copy image file to folder lose efficacy  0.11.2 (5601)

### ISSUE THREAD

**Issue by forging2012** [typora/typora-issues#4575]
Macos 10.15.7 (19H1323)
Typora  0.11.2 (5601)

**Comment by forging2012** [comment]
![image](https://user-images.githubusercontent.com/6813552/128327280-bb7d6260-095a-4187-a4c0-926cda63b050.png)

**Comment by forging2012** [comment]
In preference, I already set "copy to local", but in typora, when I copy image, the new version will give me 3 options to choose.

**Comment by forging2012** [comment]
Roll back version 0.10.11 (5372) is OK.

**Comment by abnerlee** [comment]
which option is not needed?

**Comment by forging2012** [comment]
With Typora version 0.11.2 (5601) it is not possible to save images to the settings folder. However, in version 0.10.11 (5372), I can save images to the settings folder.

**Comment by abnerlee** [comment]
What error it shows? It works well in my test though.

**Comment by forging2012** [comment]
Theoretically it should be! [image.png](. /.assets/***.png), but it's still ! [image.png](http://***.png). 
No other error messages are reported.

**Comment by abnerlee** [comment]
Did you copy & paste the rich content, or the plain markdown text?

**Comment by forging2012** [comment]
For example: 

copy the contents of the https://blog.csdn.net/moxiliushui/article/details/82751162 page. In version 0.10.11 (5372), this would give

```
# **一、LVS-NAT模式的工作原理**

**这个是通过网络地址转换的方法来实现调度的。首先调度器(LB)接收到客户的请求数据包时（请求的目的IP为VIP），根据调度算法决定将请求发送给哪个 后端的真实服务器（RS）。然后调度就把客户端发送的请求数据包的目标IP地址及端口改成后端真实服务器的IP地址（RIP）,这样真实服务器（RS）就能够接收到客户的请求数据包了。真实服务器响应完请求后，查看默认路由（NAT模式下我们需要把RS的默认路由设置为LB服务器。）把响应后的数据包发送给LB,LB再接收到响应包后，把包的源地址改成虚拟地址（VIP）然后发送回给客户端。**

**![img](../.assets/70-20210815175732117.jpeg)**

### **原理图过程简述：**

**1)客户端请求数据，目标IP为VIP**
```

However, in version 0.11.2 (5601), it will get

```
# **一、LVS-NAT模式的工作原理**

**这个是通过网络地址转换的方法来实现调度的。首先调度器(LB)接收到客户的请求数据包时（请求的目的IP为VIP），根据调度算法决定将请求发送给哪个 后端的真实服务器（RS）。然后调度就把客户端发送的请求数据包的目标IP地址及端口改成后端真实服务器的IP地址（RIP）,这样真实服务器（RS）就能够接收到客户的请求数据包了。真实服务器响应完请求后，查看默认路由（NAT模式下我们需要把RS的默认路由设置为LB服务器。）把响应后的数据包发送给LB,LB再接收到响应包后，把包的源地址改成虚拟地址（VIP）然后发送回给客户端。**

**![img](https://img-blog.csdn.net/20180918003900640.jpeg)**

### **原理图过程简述：**

**1)客户端请求数据，目标IP为VIP**
```

Note that the image URL here has been converted by the diy plugin's address.

**Comment by abnerlee** [comment]
should be fixed
