### ISSUE TITLE
Paragraph Break vs. Line Break Before A MathJax-block

### ISSUE THREAD

**Issue by Minderer** [typora/typora-issues#4576]
Hello 👋 

Long story short: I write a lot of mathematical documents (notes, problems, problems solutions, slides, booklets etc.) using Typora. Most of my markdown documents contain more than 50000 symbols. The point: When making a MathJax-block, I have noticed that there is a line break before the wrappers. This is the root to several problems. **The solution is to use a paragraph break before the wrappers instead a line break**.

So this:

```
Text text...
$$

$$

More text text...
```

Should be corrected to this:

```
Text text...

$$

$$

More text text...
```

Moreover, this is also consistent with your guys' own advice which is to use a paragraph break instead of a line break. 

Kind regards,

**Important edit**: The way it's rendered in Typora should not change; the change should only happen in the plain text file.

**Comment by Minderer** [comment]
My plain text files look (and are) very unreadable because there are no empty lines before and after a math block.

**Comment by abnerlee** [comment]
duplicated with #1107
