### ISSUE TITLE
[Feature] Suggest adding a configuration for saving images with custom naming

### ISSUE THREAD

**Issue by forging2012** [typora/typora-issues#4577]
Suggest adding a configuration for saving images with custom naming

![image](https://user-images.githubusercontent.com/6813552/128456684-f5082e48-44c5-46a2-a32e-3981d1b0fa12.png)

Currently there is no configuration item that can be configured for image names, only in the case of conflicting image names will a random string be added to the original name. It is recommended to make a configuration item that can be configured with the option to turn on random strings or other configurations.

**Comment by abnerlee** [comment]
merge into #2612
