### ISSUE TITLE
[Feature] Android Version

### ISSUE THREAD

**Issue by Blackhawke** [typora/typora-issues#4583]
I'd like to request you good folks consider creating an Android version of Typora. Of the handful of popular markdown editors avaiable, only two editors are left that let users create and use their own workspaces; and of those two, only one is now maintained, and it's very quirky! All the others force users into their preset document structure and won't even open documents outside of that structure. So those of us working on complex document trees across multiple platforms (mobile, laptop, desktop) have seen their options foreclosed. We can either use the one, quirky editor that's left, or we can use a generic code editor.

Typora would be a good add in the mobile space! (At least, I think it would. :>)

**Comment by abnerlee** [comment]
#525
