### ISSUE TITLE
 update error

### ISSUE THREAD

**Issue by znftm97** [typora/typora-issues#4584]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
An update pop-up screen appears, and at this time, all three buttons, Skip This Version, Remind Me Later, and Download Update, do not respond.

**To Reproduce**
1. Typhora Run
2. Create update screen
3. All three buttons are not clicked

**Expected behavior**
Version Update

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://user-images.githubusercontent.com/57134526/128598059-f33fb92e-8d73-4e8d-805d-b0a4225b4c91.png)

**Desktop (please complete the following information):**
 - OS: Windows 64 bit

**Typora Version**
e.g: 0.11.0

**Comment by PeeTeeH** [comment]
I have the same issue, update process is unable to proceed
![image](https://user-images.githubusercontent.com/37756000/128722936-20d3476b-53b8-4226-b776-ec45d5507ff9.png)
 - I can SELECT buttons market at the bottom of the screen with TAB, but left clicking them or pressing ENTER doesn't do anything -

**Comment by abnerlee** [comment]
#4563
