### ISSUE TITLE
Minimize/restore/close unobody buttons don't stretch to to edge of maximized window

### ISSUE THREAD

**Issue by piotrp** [typora/typora-issues#4585]
With unobody appearance buttons at top right of maximized window (minimize/restore/close) aren't usable when mouse is placed at the top edge of the screen. It's especially visible while looking at "close" button, where you can see it has a frame that doesn't stretch to the top:

![obraz](https://user-images.githubusercontent.com/1409807/128628450-38813acd-1b46-4bde-9622-1b904ea01c01.png)

You can see that there's a 2px margin at the top. The "X" and square on maximize button are also a bit off-center.

![obraz](https://user-images.githubusercontent.com/1409807/128628595-40421e52-de77-4d2d-b083-a69b68878d66.png)

Typora 0.11.2, Windows

**Comment by abnerlee** [comment]
should be fixed
