### ISSUE TITLE
`Updates` window does not process any actions

### ISSUE THREAD

**Issue by aron-hoogeveen** [typora/typora-issues#4586]
- [x] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
In the window "Updates", that pop-ups whenever there is an update available to download, a click on any of the buttons `Skip This Version`, `Remind Me Later` or `Download Update` does not start any action. Also the links in the changelog do nothing (as in they do not open a web browser). Clicking the red cross does close the window and I can then use Typora normally. 
The "Updates" window tells me the new version that is available is 0.11.2.

**To Reproduce**
1. Open Typora when there is an update available. 
2. See specified behaviour

**Expected behavior**
When I click either of the links/buttons I expect them to either open a web browser and take me to the specified page, or download the update/remind me later/skip this version.

**Screenshots / Screencasts**
Not applicable. 

**Sample Markdown File**
Not applicable.

**Desktop (please complete the following information):**
 - OS:Windows 10 64bit

**Typora Version**
e.g: 0.11.0

**Additional context**
The problem persists on further startups of the application.

**Comment by abnerlee** [comment]
duplicated with #4563
