### ISSUE TITLE
Cant't successfully export to PDF

### ISSUE THREAD

**Issue by SWHL** [typora/typora-issues#4587]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I export md file to PDF, it always shows `Failed to export as PDF`

**To Reproduce**
1. Go to open the [README.md](https://github.com/typora/typora-issues/blob/master/README.md) with Typora
2. Click on 'export'
3. Select the PDF format
![image](https://user-images.githubusercontent.com/28639377/128981582-f8c917b6-bd0f-478b-a661-40ae759ed154.png)

**Expected behavior**
Successfully to export PDF.

**Sample Markdown File**
[README.md](https://github.com/typora/typora-issues/files/6966380/README.md)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit 20H2

**Typora Version**
- 0.11.2(beta)

**Additional context**
- Typora theme: Github
- Error log:
```log
INFO 2021/8/11下午2:36:34  generate print window with id 12
ERROR 2021/8/11下午2:36:34  unhandledRejection Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:89:1563)
    at electron/js2c/renderer_init.js:117:435
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:101:375)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)
ERROR 2021/8/11下午2:36:34  [Error: Failed to generate PDF]
INFO 2021/8/11下午2:36:38  [focus] 7
INFO 2021/8/11下午2:36:41  [blur] 7
INFO 2021/8/11下午2:36:41  [win] blur
INFO 2021/8/11下午2:38:29  [blur] 7
INFO 2021/8/11下午2:38:29  [win] blur
```

**Comment by abnerlee** [comment]
Does #3766 solve this?

**Comment by SWHL** [comment]
- Thank your reply
- I have tried the #3766 , but can't solve the problem.

**Comment by SWHL** [comment]
I update the lastest Typora 0.11.5, and the problem is solved.
