### ISSUE TITLE
Trigonometric functions in math blocks render incorrectly

### ISSUE THREAD

**Issue by kzvi** [typora/typora-issues#4588]
In LaTeX math, `\sin(x)` should render equivalently to `\operatorname{sin}(x)`. However in this new Typora update it renders differently, with more space before the left parenthesis:

<img width="605" alt="Screen Shot 2021-08-11 at 2 01 36 PM" src="https://user-images.githubusercontent.com/38590027/129102840-2e1a3bf1-be88-4309-a68a-df1d105ac1c9.png">

I believe that this may be caused by the inclusion of the `physics` mathjax package. In regular LaTeX, this behavior can be turned off using the `notrig` option as in `\usepackage[notrig]{physics}`.

**Comment by abnerlee** [comment]
> Note, that the physics extension does not implement the notrig option.

http://docs.mathjax.org/en/latest/input/tex/extensions/physics.html

**Comment by kzvi** [comment]
In that case I would like to suggest that the physics extension be disabled, because there are probably more users who want to use `\sin`, `\cos`, etc and rely on the default behavior than users who would use the physics package.

**Comment by kzvi** [comment]
I filed an issue with MathJax: https://github.com/mathjax/MathJax/issues/2760

**Comment by abnerlee** [comment]
-> #4989
