### ISSUE TITLE
Hyperlink in inline code segments

### ISSUE THREAD

**Issue by jaredliw** [typora/typora-issues#4589]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The line below is a valid sytax in Github Markdown (idk about the others):
> \[\`pretend that this is a line of code`](https://example.com)

and it is rendered as:
[`pretend that this is a line of code`](https://example.com)

Typora shows it as:
\[`pretend that this is a line of code`](https://example.com)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.11.0

**Additional context**
Btw, I just can't update my Typora to 0.11.2. "Download Update" button gives me no response. Maybe I will reinstall one...

**Comment by abnerlee** [comment]
#4591 should be fixed in 0.11.5
