### ISSUE TITLE
The flow chart for the discovery of the mermaid shows an incomplete temporary repair method.

### ISSUE THREAD

**Issue by ChunJiu2008** [typora/typora-issues#4590]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

The problem of incomplete display of the mermaid's flow chart has been reported by many people, **but I found a temporary fix method**, hoping to help find the problem and fix it as soon as possible.

**To Reproduce**

1. Open typora;
2. Select "Insert Code Block";
3. Select "mermaid";
4. Enter the following content:

```
graph TD
   start[ start]
   getIP[[ Get Public IP ]]
   IPavailable{ IP available?}
   exit[ Exit]
  
   start-->getIP-->IPavailable
```
5. You can see that it is wrong : 

<img width="668" alt="2021-08-13 13_16_04-Untitled• - Typora" src="https://user-images.githubusercontent.com/33535956/129309246-f608fccc-f024-44e7-a944-7264b1cc659e.png">

6. Switch between the "pixyll" and "whitey" themes several times, and it becomes correct : 

<img width="668" alt="2021-08-13 13_25_49-Untitled• - Typora" src="https://user-images.githubusercontent.com/33535956/129309288-bcfd64dd-25ec-45ef-8abb-6c38f0cc8b87.png">

7. But after switching to other themes, it returns to the error again;

**Moreover, switching between the "pixyll" theme and other themes has no effect, only switching with "whitey" will have an effect.**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**

 - OS: [**Windows 10 64bit**]

**Typora Version**

**0.11.2**

**Additional context**

**Comment by abnerlee** [comment]
Did you zoom Typora?

**Comment by abnerlee** [comment]
same with #4499
