### ISSUE TITLE
Gnome Wayland session does not support server-side decorations

### ISSUE THREAD

**Issue by alpemwarrior** [typora/typora-issues#4592]
See: [https://gitlab.gnome.org/GNOME/mutter/-/issues/217](https://gitlab.gnome.org/GNOME/mutter/-/issues/217)

Gnome's wayland session does not support the xdg-decoration wayland protocol, and if the application doesn't draw its own decorations it ends up without a title bar. 

I understand that adding desktop-specific code is annoying, but the option to enable client-side decorations (like it is done for windows and macos) could be added for the linux platform.

**Comment by abnerlee** [comment]
same issue with https://github.com/microsoft/vscode/issues/124202?

**Comment by alpemwarrior** [comment]
Yes, although vscode has the option to enable csd so it looks like on windows.

**Comment by abnerlee** [comment]
seems different from #4000, they have a titlebar

**Comment by plumlis** [comment]
Seems a good news here.

**Comment by Bryan2333** [comment]
The problem still exists. I used flatpak to install typora. When I tried to run the typora like this `flatpak run io.typora.Typora --enable-features=UseOzonePlatform --ozone-platform=wayland`, the title bar is missing.

**Comment by abnerlee** [comment]
@Bryan2333 does binary version (https://download.typora.io/linux/Typora-linux-x64.tar.gz) works now?

**Comment by Bryan2333** [comment]
> @Bryan2333 does binary version (https://download.typora.io/linux/Typora-linux-x64.tar.gz) works now?

I am using the Arch Linux with KDE on Wayland now. I installed the Typora via AUR which is actually converted from deb package.

When I pass these two arguments `--enable-features=UseOzonePlatform --ozone-platform=wayland` , the problem still exists. But it is different from the previous one.

The title bar is not missing, but it is seperated from menu bar. It becomes like this:

![Screenshot_20230109_232448](https://user-images.githubusercontent.com/31512600/211344334-e83559ab-b3be-4f17-9615-9daf14715297.png)

**Comment by abnerlee** [comment]
From your screenshot, it seems working fine (same window frame as Konsole)

**Comment by Bryan2333** [comment]
> From your screenshot, it seems working fine (same window frame as Konsole)

Yes,it works fine in KDE. But in the Gnome, the title bar is still missing.

![截图 2023-01-11 23-51-34](https://user-images.githubusercontent.com/31512600/211852785-65f14e7e-ca38-41a6-99ac-4f564d7b2361.png)

And By the way I hope the Typora can support client-side decoration. The title bar takes up too much space.

![截图 2023-01-11 23-53-40](https://user-images.githubusercontent.com/31512600/211853290-8f792212-c745-4395-9005-1cc3f60cfb6c.png)

**Comment by Bryan2333** [comment]
Typora 1.5.5 has fixed this problem. The title bar works pretty nice.

**Comment by plumlis** [comment]
> Typora 1.5.5 has fixed this problem. The title bar is not broken any more.
> 2023-02-04_20-04-04.mp4

Can you use ibus / fcitx in Typora wayland?

I  heard that electron app in wayland still no IME supported.

**Comment by Bryan2333** [comment]
> > Typora 1.5.5 has fixed this problem. The title bar is not broken any more.
> > 2023-02-04_20-04-04.mp4
> 
> Can you use ibus / fcitx in Typora wayland?
> 
> I heard that electron app in wayland still no IME supported.

Not yet. But I think the problem will be fixed in this year. As the patches in https://bugs.chromium.org/p/chromium/issues/detail?id=1039161 will be merged soon.

**Comment by abnerlee** [comment]
put into #5799 since what remains is the ibus / fcitx  issue
