### ISSUE TITLE
[Feature] Highlight button on Mac Touch Bar

### ISSUE THREAD

**Issue by nskobelevs** [typora/typora-issues#4593]
We've got handy buttons for bold and italics, would be convenient to also have a highlight button (if highlight with == is enabled) ~~especially since there's no keyboard shortcut for it, making highlighting notes somewhat of a hassle.~~ Never mind, was wrong about the keyboard shortcut!

**Comment by abnerlee** [comment]
We will no longer adding features on touch bar since Apple seems discontinued it.
