### ISSUE TITLE
Markdown files ruined after todays update

### ISSUE THREAD

**Issue by Minderer** [typora/typora-issues#4594]
I write text and math in markdown files.

After updating some files are completely ruined.

Text which should not have been inside the math delimiters `$$...$$` were inside it!

**Comment by Minderer** [comment]
<img width="804" alt="Skærmbillede 2021-08-14 kl  22 20 12" src="https://user-images.githubusercontent.com/67560093/129459138-e7db06e5-3661-4e90-b01b-d6721b7524a0.png">

**Comment by Minderer** [comment]
I'm not sure what the red dots are.

**Comment by abnerlee** [comment]
You can remove red dot by find & replace.

And what is your OS and typora version? and what do you mean by "Text which should not have been inside the math delimiters $$...$$ were inside it!"?

**Comment by Minderer** [comment]
@abnerlee 

Here is a simple (made up) example:


[ex.md](https://github.com/typora/typora-issues/files/6987714/ex.md)

**Comment by abnerlee** [comment]
@Minderer sorry, I still cannot understand what the bug you are reporting


The sample file is

```
> The variance is:
> $$
> C(X)=\begin{pmatrix} C(X_1,X_1)&\cdots&C(X_1,X_N) \\ \vdots & \ddots & \vdots \\ C(X_N,X_1)&\cdots&C(X_N,X_N)  \end{pmatrix}=\begin{pmatrix} \sigma^2&\cdots&0 \\ \vdots & \ddots & \vdots \\ 0&\cdots&\sigma^2  \end{pmatrix}=\operatorname{diag}\left(\sigma^2,\ldots,\sigma^2\right)
> $$



Became:

> $$
> The variance is:
> $$
>
> C(X)=\begin{pmatrix} C(X_1,X_1)&\cdots&C(X_1,X_N) \\ \vdots & \ddots & \vdots \\ C(X_N,X_1)&\cdots&C(X_N,X_N)  \end{pmatrix}=\begin{pmatrix} \sigma^2&\cdots&0 \\ \vdots & \ddots & \vdots \\ 0&\cdots&\sigma^2  \end{pmatrix}=\operatorname{diag}\left(\sigma^2,\ldots,\sigma^2\right)

```

is it correctly parsed in my test.

**Comment by Minderer** [comment]
The TeX wrappers have shifted their position in the file. This is the bug.
Just look at the first picture I have attached.

Let's leave and hope it does not happen again.
