### ISSUE TITLE
only tagged equation are centered

### ISSUE THREAD

**Issue by Sonya-c** [typora/typora-issues#4596]
Only tagged equation are centered in pdf export (in editon render is fine).
![imagen](https://user-images.githubusercontent.com/68860233/129497650-57fd771d-9c2a-4d79-8d3f-f8b2e637cdfe.png)

I was using adecamic theme so I change to another with an test file but the problem still there:

![imagen](https://user-images.githubusercontent.com/68860233/129497679-caffc2bd-c03b-45c4-aa0c-9be75c220fa4.png)

Here the code of the test file:
```markdown
# Test

$$
\frac{dy}{dt} = 0
$$
```

 - OS Windows
-  Typora version 0.11.2.

**Comment by abnerlee** [comment]
duplicated with #4562
