### ISSUE TITLE
Cannot Update

### ISSUE THREAD

**Issue by Extra-Creativity** [typora/typora-issues#4598]
**Describe the bug**
Since 0.11.0, my Typora cannot update. To be exact, the "updates" information comes out but I cannot click any button on it(no response after clicks), such as "download updates", "skip this version" and so on. I've received the same problem from one of my friends who uses Typora of version 0.11.0.

**To Reproduce**
1.Open Typora of version 0.11.0
2.Wait until "Updates" comes out
3.See errors described above

**Expected behavior**
I can update normally.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.11.0

**Comment by abnerlee** [comment]
Sorry, please download the new version manually from typora.io

#4584
