### ISSUE TITLE
In the typora software of linux, the input method shift key is invalid.

### ISSUE THREAD

**Issue by xingwozhonghua** [typora/typora-issues#4599]
In the typora software of linux, the input method shift key is invalid.

Similar issues have occurred in google chrome before, and the latest version has been fixed.

The following link is a well-known linux input method software in China, which is based on the sogou input method developed by fcitx.

https://ime.sogouimecdn.com/202108171813/442691bb7357d6262987d49570bf230e/dl/index/1612260778/sogoupinyin_2.4.0.3469_amd64.deb

What is an input method?

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/39

Information that may be relevant to the above question.

https://github.com/ibus/ibus/issues/2241

**Comment by uniontech-qishi** [comment]
If typora software is based on chromium,than search NormalizeFlags() function in chromium source code,delete this function at the point where this function is called.This function is called under use_x11 macro definition.

**Comment by xingwozhonghua** [comment]
The latest version has been resolved
