### ISSUE TITLE
Pressing enter after ```destroys everything

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#46]
When making a code block the user writes ```. If they hit enter immediately after, they will most likely ruin their whole document.

This
````
wow
````
Turns to this (this is copy-pasted from Typora, the way it actually looks inside the program is even more wicked):
```
wowwwwowwwoww`````````

wowwwwowwwoww`````````

wowwwwowwwoww`````````
```

**Comment by abnerlee** [comment]
Thanks for your bug report.

I tried:
1. input ```
2. hit return immediately

But I cannot reproduce the bug you descripted. So would you give me more details to reproduce this bug? And are you using the US keyboard?

**Comment by waahto** [comment]
I use Finnish layout but I also tested with US international and the same thing. Here's a breakdown of the bug:

1. Open Typora
2. Type "```"
3. Hit enter
4. Type "Bug" and look how things get messed up.

![bug](https://cloud.githubusercontent.com/assets/16896115/12615574/2eaa35fe-c50f-11e5-9d69-2e6d3ef0ab84.png)

That's seven key presses in total. If you can't reproduce, is there something else I could do?

**Comment by abnerlee** [comment]
So, after you input "```" and hit return, no code block is generated?

**Comment by waahto** [comment]
No, yes, sort of.

Type ```
![1](https://cloud.githubusercontent.com/assets/16896115/12617149/047dc77a-c517-11e5-93a7-77eb2b2d2ce5.png)
Hit enter
![2](https://cloud.githubusercontent.com/assets/16896115/12617152/04840e82-c517-11e5-9937-7e7f75d5d471.png)
Type B
![3](https://cloud.githubusercontent.com/assets/16896115/12617148/047ca05c-c517-11e5-9992-1bad66efc5cc.png)
Type u
![4](https://cloud.githubusercontent.com/assets/16896115/12617151/047ff054-c517-11e5-9e27-6db6727ee134.png)
Type g
![5](https://cloud.githubusercontent.com/assets/16896115/12617150/047f7f34-c517-11e5-8534-fb1c946fc8a6.png)

**Comment by abnerlee** [comment]
OK, I can reproduce it now by using Finnish IME on mac.

We will check and fix this. Again, thanks for your bug report
