### ISSUE TITLE
Alt-Shift annoying menu focus

### ISSUE THREAD

**Issue by grissius** [typora/typora-issues#460]
Usually, when pressing <Alt> in app with toolbar options, toolbar is focused, and one can select option with keyboard without a mose. This does not seem to work in Typora. Not much of an issue.

What is more annoying, is that on <Alt><Shift> first toolbar item *File* is opened and focued. <Alt><Shift> is very often used for switching keyboard layouts and user is always slapped out of the flow, when he needs to cancel this dialogue.

Not sure if its OS (or rather OS specific) issue, using Linux Mint 18 Cinnamon. None of other apps I use behaves this way.

Here is a screenshot of what pops out. (not sure if its really called toolbar)

![image](https://cloud.githubusercontent.com/assets/24388536/21073276/fa7985ee-bed9-11e6-8925-96be96483283.png)

**Comment by abnerlee** [comment]
caused by https://github.com/electron/electron/issues/2504

**Comment by grissius** [comment]
@abnerlee Correct me if I am wrong, but then I should face this issue with all electron apps on my system, shouldn't I? I have VS code and have no such issue there. It means, Code uses a different electron version, or they fixed it for Code explicitly using some workaround?

**Comment by abnerlee** [comment]
`Alt` key is now supported in new release.
