### ISSUE TITLE
Space at the top of every file

### ISSUE THREAD

**Issue by syco** [typora/typora-issues#4600]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

**Describe the bug**
Typora leave a lot of empty space above files, please see screenshot.

**Expected behavior**
Files should be rendered from the top of the page, not halfway down.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/54575/129727733-d3d568a0-21d8-45f9-9d24-bb5350065d73.png)

**Sample Markdown File**
[test.md](https://github.com/typora/typora-issues/files/6999987/test.md)

**Desktop:**: Arch Linux
**Typora Version**: 0.11.5

**Comment by abnerlee** [comment]
turn off typewriter mode from view menu
