### ISSUE TITLE
[Feature] Custom MathJax config

### ISSUE THREAD

**Issue by kzvi** [typora/typora-issues#4602]
It would be useful to be able to specify a custom MathJax config in the preferences.

**Comment by Minderer** [comment]
What do you mean? I'm curious.

**Comment by kzvi** [comment]
> What do you mean? I'm curious.

http://docs.mathjax.org/en/latest/options/index.html

e.g. to define custom macros or include packages.

**Comment by Minderer** [comment]
Alright, I see.

**Comment by IzumiOdotto** [comment]
+1, I need to include the chessboard packages, hope I can include the packages by myself as soon as possible.

**Comment by abnerlee** [comment]
We will include all supported packages.

For predefined macros, see #100
