### ISSUE TITLE
Wrong visual representation of a single space in inline math

### ISSUE THREAD

**Issue by Minderer** [typora/typora-issues#4604]
There is only one unit of space (using spacebar):

<img width="643" alt="image" src="https://user-images.githubusercontent.com/67560093/130132356-254bfba0-6063-4619-b53c-d440593349f3.png">

and 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/67560093/130132791-1a1be119-95b5-4f31-a721-3cf07c8dbd5e.png">

**Comment by abnerlee** [comment]
try use built-in themes?
