### ISSUE TITLE
Is there a way to add header to references page?

### ISSUE THREAD

**Issue by from81** [typora/typora-issues#4605]
Currently, rendered references look like the image below, being on the last page and on its own page.
![image](https://user-images.githubusercontent.com/34954529/130192129-b43eb109-7bb5-49ee-899a-56d4d6c63186.png)

However, I want to add a header to this last page, so that it says "References" on top of the last page.
How do I do this? Is this possible?

**Comment by abnerlee** [comment]
Yes, by using "Append Extra Content" to insert js to add the title, see #5000
