### ISSUE TITLE
The theme "Newsprint" in two additional versions: 1) white background and  2) darkmode

### ISSUE THREAD

**Issue by Minderer** [typora/typora-issues#4606]
One version with white background color instead of the yellow-ish one **for printing purposes**.
Another version with pitch black background color and white text (for low-light reading/writing). Also, I like darkmode.

The special thing about the theme is that **it looks very professional**; which is important in academia. I have not find any other theme to be appropriate for academic work (I'm sure I have checked all the ones which exist).
It also **beautiful to look at** while writing; which makes the writing process a bit more enjoyable.

**Comment by abnerlee** [comment]
Hmm.. It's just style preferences.
