### ISSUE TITLE
Autocorrection bug with some words ending with a dot

### ISSUE THREAD

**Issue by GicoProgram** [typora/typora-issues#4608]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Correcting a word that ends with a dot (.) with autocorrection will add a dot at the end of the word, also if there is already a dot at the end

**To Reproduce**
1. Write a word with a dot at the end of the word and that's not recognized as correct
2. Right-click the red-underlined word
3. Press the "correct" word
4. Repeat 1-3 more times
5. You can see the bug

**Expected behavior**
After the 3rd step in the reproduce section of this issue, the word has to be recognized as correct

**Screenshots / Screencasts**
https://user-images.githubusercontent.com/51818710/130269435-524e47fb-af0f-4944-92a0-64b390616e11.mp4

**Sample Markdown File**
[mr.md](https://github.com/typora/typora-issues/files/7023067/mr.md)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit build 10.0.22000.160

**Typora Version**
e.g: 0.11.5 (beta)

**Additional context**
I noticed it with the Mr. word
My language is Italian (Spell check is on italian when the bug occurs)

**Comment by abnerlee** [comment]
duplicated with #3440
