### ISSUE TITLE
display math error Missing Closed Bracket

### ISSUE THREAD

**Issue by chipbrock** [typora/typora-issues#4609]
- [x ] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
Display math throws a "Missing closed brace" error for multi-line equations

**To Reproduce**
1. insert $$ for display math
2. type in first equation then \\
3. type in second and the error occurs

"Missing closed brace"

Here is an example of a legally formed align* equation set:
`
$$
\begin{align*}
\gamma & = \frac{1}{\sqrt{1-(\frac{u}{c})^2}} \\

\gamma & = \frac{1}{\sqrt{1-(\epsilon)^2} } \\

\gamma & = 1

\end{align*}
$$
`

**Expected behavior**
always before this works

**Screenshots / Screencasts**
Screen shot attached.
<img width="635" alt="screenshot_2173" src="https://user-images.githubusercontent.com/4515277/130290932-4ba2c5aa-0537-47d1-a131-8a7f05cd804f.png">
[tuyporabug.txt](https://github.com/typora/typora-issues/files/7023999/tuyporabug.txt)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

attached

**Desktop (please complete the following information):**
 - OS: [mac os 11.5.2] MacBook pro

**Typora Version**
 0.11.5 (5648)

**Additional context**
This happens with align and with eqnarray

**Comment by abnerlee** [comment]
this is fixed already
