### ISSUE TITLE
File loss while moving folder, Windows

### ISSUE THREAD

**Issue by LincolnOnion** [typora/typora-issues#4611]
Typora: 0.11.5(beta)
Desktop: Windows 10 64bit

I use Typora for simple text files, entire Typora folder is 400 KB, with one of the folders being somewhere else on the C drive. All files are mine, are super useful to me, I rely on them in my daily life. I am very sad to loose any of them. 

### Issue:
I had a folder I wanted to move to other folder.
After the folder was moved, all the files got lost. I can see some of them in "Recent files", but they are no logner accessible.

### Details of files:
The folder had about 7 text files with simple formatting like tables and headers.
Simple markdown
Maybe 1 picture
They probably contained Russian, Chinese and English language writings in them.(90% of files were in English)

### What I have now
Moved AnkiX folder with the new file I made
Unmoved AnkiX folder that is empty
Lost files, untraceable in the computer and through recent files.
:emphatic face:

### More detailed description: 
I wanted to move a folder two folders up. The name of the folder is, say, "AnkiX". The desired folder was opened on the left menu, so I just dragged the AnkiX folder to the desired folder. Clicked ok on popup("do you want to move this folder". 
I noticed it didn't move, so I repeated the operation.
One of the files from the folder was open on the screen in the same window and, I believe, it wasn't saved. Only one Typora window was open.

First I could see the AnkiX folder in the place I wanted it to be.
Even through the file didn't save(I believe so) I was able to start a new file that I moved to **moved** AnkiX folder
Next I could also see there is a second folder named AnkiX in the old location - **unmoved** AnkiX folder - with three out of 7 original files present. 

I noticed **moved AnkiX** folder contained no files except the new file I just made.
In 1 minute it displayed "Operation failed EPERM: operation not permitted, Istat" and then what was written is the file path to the file that I didn't touch for last 20 minutes that was in the original AnkiX folder.
I tried to search for missing files.
I could also now see the three out of seven files that were in the unmoved AnkiX folder _disappeared_ and I can't find them anywhere.
They are not in the bin.

I have never had this before, have been using Typora for about half a year. 

### Replication:
1. I made a folder with three files
2. Then created the forth, didn't save it 
3. Moved the folder from and to the same path I did with failed folder. 
4. Things migrated with no issues. Unsaved file remained on the screen and was unsaved after moving.
5. **No errors seen**

However I have now tried to delete it and it asked Administrator permission and after it was granted the popud said it couldn't move the folder or file to bin and suggested opening the folder in Windows, delete permanently or cancel.

**Comment by abnerlee** [comment]
1. Does typora have write access to the move destination?
2. Is there any firewall or antivirus app that would block typora from rename / writing file?
