### ISSUE TITLE
[Feature] Top Menu Bar and Two Pane View

### ISSUE THREAD

**Issue by ChrisDev8** [typora/typora-issues#4613]
# Add Support for a Top Menu Bar and Two Pane View

There should be a top menu bar like Microsoft Word. It might have different formatting like bold text, underline, code, header, list, etc. It can insert the bold text formatting just like the formatting menu inserts bold text. The picture below explains in more detail.
NOTE: Doesn't need everything in this picture and will be on the top of the window.

![Image](https://i.imgur.com/wji6hdI.png)

There also should be a option to change from one panel mode to two panel mode. In two panel mode, the raw code will be in the left and the display is on the right. Just like [StackEdit](https://stackedit.io/). But there still is the original one pane view. 

This explains everything. More detail [HERE](https://i.imgur.com/E12y1wV.png)

![Image](https://i.imgur.com/E12y1wV.png)

**Comment by abnerlee** [comment]
We currently do not have plans for this.

**Comment by ChrisDev8** [comment]
Just complete bs.
