### ISSUE TITLE
How to uninstall the app completely on mac os(Big Sur)?

### ISSUE THREAD

**Issue by MrZhuKeXin** [typora/typora-issues#4614]
My Typora has encountered a bug that makes it "Http://URL Https://xxxxx" when inserting automatically uploaded images, so I want to uninstall and reinstall it.
However, after deleting several directories in the Library, I deleted the APP from Applications and then reinstalled it, but I found that the previous preferences were still retained and bugs still existed.
So, can anyone tell me how to completely uninstall an app on MAC OS? Where are all its configuration files?
![image](https://user-images.githubusercontent.com/28593015/130554991-94350f57-f570-4059-a05b-b5a3a7923385.png)

**Comment by abnerlee** [comment]
~/Applications/Typora.app
~/Library/Application Support/abnerworks.Typora/
~/Library/Caches/abnerworks.Typora/
~/Library/Preferences/abnerworks.Typora.plist
