### ISSUE TITLE
Its not possible to download newer version by modal window

### ISSUE THREAD

**Issue by michmzr** [typora/typora-issues#4615]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
App displays modal window about newer version. All buttons and links don't respond when I click on them 

**To Reproduce**
1. Click on "Help"
2. Click on "Check updates"

**Expected behavior**
I should be able to download newer version or skip update.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/15823572/130568267-52192c99-d6f1-45fe-a2b2-ddb276dbf06b.png)

**Desktop (please complete the following information):**
Windows 10 Pro 64bit, 10.0.19041 Compilation 19041

**Typora Version**
0.10.11

**Additional context**
Theme: Github

**Comment by abnerlee** [comment]
#4598
