### ISSUE TITLE
图片上传服务的path解析增加对data://协议的支持

### ISSUE THREAD

**Issue by L1sper** [typora/typora-issues#4616]
Typora作为md编辑工具确实非常好用，但是其图像上传服务对上传结果的解析限制为http和https，这不利于离线环境的跨设备操作，因为确实有时候需要使用Typora编辑离线文档并跨设备传输。希望增加对data协议的支持。或者提供Options进行配置，预置压缩图片存储base64数据的功能

**Comment by abnerlee** [comment]
#88
