### ISSUE TITLE
[Feature] A buttom to remove all highlightning in a dokument

### ISSUE THREAD

**Issue by Minderer** [typora/typora-issues#4622]
So a bottom for removing all ``== ==`` in a markdown document.

This is very hard to do yourself if you actually use the symbol " ==" for different things.

**Comment by Minderer** [comment]
> Is clear format what you want?

Yes, clearing the format called "hightlightning".

**Comment by abnerlee** [comment]
You can try click Style -> Highlight twice, firstly it will make the area highlighted, then it will toggle (remove) existing highlight

**Comment by Minderer** [comment]
> You can try click Style -> Highlight twice, firstly it will make the area highlighted, then it will toggle (remove) existing highlight

This method is fine for a small number of highlights. This was actually not what I meant.
I'm talking about documents with – let us say – 150 highlights. I bottom to remove all the highlights in a document will therefore be great.
