### ISSUE TITLE
Spellcheck's "Auto Detect Language" not working anymore

### ISSUE THREAD

**Issue by strblr** [typora/typora-issues#4625]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

**Describe the bug**

After updating to latest version (0.11.7), spellchecking doesn't work anymore when Preferences > Editor > Spell Check is set to "Auto Detect Language".

**To Reproduce**
1. Apply that setting
2. Type something wrong

**Expected behavior**
It used to work and just stopped after the update.

**Sample Markdown File**
I'm currently working on this file which generates the error: https://github.com/ostrebler/pegase/blob/master/README.md

**Desktop (please complete the following information):**
 - Windows 10 64bit

**Typora Version**
0.11.7

**Comment by abnerlee** [comment]
What about other md files? Like Help -> Quick Start for example.
