### ISSUE TITLE
Folder/File name started with '.' character will not show in Files tab panel

### ISSUE THREAD

**Issue by rexxon-chuah** [typora/typora-issues#4627]
**Describe the bug**
Folder/file with name started with a `.` character will not show. For example, create a folder name **.Net**. Rename the folder to **DotNet** under Windows Explorer and the folder will appear in the Typora Files tab panel.

**To Reproduce**
1. Create a folder/file named **.Net** via the Typora's Files tab panel.
2. Folder/file will not show.

**Expected behavior**
The folder/file should be shown.

**Desktop:**
 - Windows 10 Home 64bit

**Typora Version**
0.11.7

**Comment by abnerlee** [comment]
should be covered by #1753

Currently, they are ignored
