### ISSUE TITLE
Bold font not working in some cases in V0.11.7

### ISSUE THREAD

**Issue by thb584Git** [typora/typora-issues#4628]
Find attached sample of not working bold font in latest version. 
This file works fine with V0.11.2. Both machines run Win10.
If you turn of italic part in the sample bold part in this paragraph will work.
[Typora_bold_issue.zip](https://github.com/typora/typora-issues/files/7073266/Typora_bold_issue.zip)

**Comment by abnerlee** [comment]
#4631
