### ISSUE TITLE
New Typora window uses Desktop folder as default folder for Save As

### ISSUE THREAD

**Issue by betterth** [typora/typora-issues#463]
Using the Desktop as a default save location for all new Typora windows is very frustrating. The desktop is NOT an acceptable location for documents. If the developers did not know where to put documents by default in Windows, why not User/<user>/Documents ? 

My preferred functionality would be for Typora to remember the last save location even in a new Window. 

I use Typora to modify a file structure exclusively in one folder, and remembering my project folders would be very intuitive and helpful. (Workspace/Project 1, Workspace/Project 2, etc) so staying in that structure is simple and generally speaking I will create a few files in the same folder, so this scheme means the majority of my Save-As use cases will automatically already be in the correct folder and I won't have to manually navigate all the way down to my workspace every single time I hit File > New!

Or, you could simply provide a Default Save Location in the settings and allow users to choose a default base folder.

But regardless, Save-As defaulting to Desktop is a bad design decision when a Documents folder is built into Windows.

**Comment by abnerlee** [comment]
can be solved by https://github.com/typora/typora-issues/issues/1322

**Comment by dodd0ro** [comment]
1. You can add string to Typora's shortcut with directory that you want to be default:
`"C:\Program Files\Typora\Typora.exe" /c D:\some_folder`
In that way you can create shortcuts for all your favorite folders.

2. Another way - markdown file with links...
