### ISSUE TITLE
Hard Link Connection would be breaked after typora's editing.

### ISSUE THREAD

**Issue by BeBubbled** [typora/typora-issues#4630]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I'm pretty sure that I checked all related buy.
Typora had fixed and added support to "ln -s original_file point_to_original"
while the "ln original_file point_to_original" isn't

**To Reproduce**
Use "ln original_file point_to_original" to get a file B point to file A.
Any editing by typora would not reflect on another file. The hard link connection is broken caused by typora.

**Expected behavior**
When pressing command+s on ctrl+s to saving changes. The linked another file would keep the same.

**Desktop (please complete the following information):**
 - OS: Mac

**Typora Version**
e.g: 0.11.5 (5648)

**Comment by abnerlee** [comment]
What about TextEdit.app ? Typora just let macOS handle saving, just like TextEdit.app

**Comment by BeBubbled** [comment]
> What about TextEdit.app ? Typora just let macOS handle saving, just like TextEdit.app

As I don't know the detail of apple's saving changes, I provide a comparison on hard link files first.
* e.g. we have a file hard_link.md in path ~/hard_link.md, 
 and you use **"ln ~/hard_link.md ~/test_case_1/mirror.md"** ,
 **"ln -s ~/hard_link.md ~/test_case_2/mirror_s.md"** 
 to create two mirror.md point to hard_link.md
* * Using [Marktext](https://github.com/marktext/marktext) edit any one of these three files, these three would keep the same.
* * Using typora editing mirror_s.md or hard_link.md, these two would keep the same.
* * Using typora editing mirror.md, nothing changes could be found on hard_link.md and mirror_s.md.
* Briefly speaking, the hard link connection is broken when using typora.

As you said that you let the macOS handle saving just like TextEdit.
I test TextEdit on these three files.
You Guess What. **Shit, we need to report this issue to apple.** 
Their TextEdit can only support "ln -s A A_mirror", they don't support the "ln -s A A_mirror" neither.


Or we could find another way like MarkText.
If you have a plan to change typora's saving method?

**Comment by BeBubbled** [comment]
> > What about TextEdit.app ? Typora just let macOS handle saving, just like TextEdit.app
> 
> As I don't know the detail of apple's saving changes, I provide a comparison on hard link files first.
> 
> * e.g. we have a file hard_link.md in path ~/hard_link.md,
>   and you use **"ln ~/hard_link.md ~/test_case_1/mirror.md"** ,
>   **"ln -s ~/hard_link.md ~/test_case_2/mirror_s.md"**
>   to create two mirror.md point to hard_link.md
> * * Using [Marktext](https://github.com/marktext/marktext) edit any one of these three files, these three would keep the same.
> * * Using typora editing mirror_s.md or hard_link.md, these two would keep the same.
> * * Using typora editing mirror.md, nothing changes could be found on hard_link.md and mirror_s.md.
> * Briefly speaking, the hard link connection is broken when using typora.
> 
> As you said that you let the macOS handle saving just like TextEdit.
> I test TextEdit on these three files.
> You Guess What. **Shit, we need to report this issue to apple.**
> Their TextEdit can only support "ln -s A A_mirror", they don't support the "ln -s A A_mirror" neither.
> 
> Or we could find another way like MarkText.
> If you have a plan to change typora's saving method?

[I found same issue on StackOverflow](https://superuser.com/questions/139390/hard-link-not-works-under-mac-os-x-in-gui-mode/139391)
Based on this answer, I guess apple probably didn't make the change for file security concerns.

**Comment by abnerlee** [comment]
> If you have a plan to change typora's saving method?

At least in near future, No. On macOS, Typora follows spec of macOS. But we can see if more users reporting this.
