### ISSUE TITLE
Error displayed when combining `Emphasis(*)` and `Strong(**)`

### ISSUE THREAD

**Issue by ifwlzs** [typora/typora-issues#4631]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**

Emphasis and strong styles are displayed incorrectly when editing text, but in source mode they are displayed normally.

**To Reproduce**
The incorrectly displayed sentence is `**abcde**fg1*23456*789`

**Expected behavior**

Emphasis `abcde` and strong `23456`
>**abcde**fg1*23456*789

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

For comparison, I wrote a few different statements to demonstrate the bug:

>Screenshot in source code mode (this is the screenshot that shows the desired effect correctly)
![image](https://user-images.githubusercontent.com/49548316/131299447-02602d61-c598-497d-98ed-fba7868dda0f.png)
>Screenshot of the actual result
![image](https://user-images.githubusercontent.com/49548316/131299524-554f23d9-9cf9-456b-bff0-5262619e5936.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

```markdown
**abcde**fg123456789

abcdefg*234567*89

**abcde**fg1*23456*789

**abcde**fg1***23456***789

__abcde__fg1*23456*789

__abcde__fg  _23456_ 789

*abcde*fg1**234567**89
```

**Desktop (please complete the following information):**
 - OS:  Windows 10 64bit 10.0.18363.1256

**Typora Version**
0.11.7(beta)

**Additional context**
I think this bug has only appeared in the last few versions, it hasn't been found before

**Comment by ifwlzs** [comment]
I found that as soon as `*` comes after `**` after that, it triggers the bug

for example:
```markdown
Lately **I’ve been**, l’ve *been* losing sleepLately **I’ve been**, l’ve *been* losing sleep

最近**我总是**辗转*反*侧 难以入睡最近**我总是**辗转*反*侧 难以入睡

最近　**よく**眠れな*い*んだ最近　**よく**眠れな*い*んだ
```
>Lately **I’ve been**, l’ve *been* losing sleepLately **I’ve been**, l’ve *been* losing sleep
>
>最近**我总是**辗转*反*侧 难以入睡最近**我总是**辗转*反*侧 难以入睡
>
>最近　**よく**眠れな*い*んだ最近　**よく**眠れな*い*んだ

![image](https://user-images.githubusercontent.com/49548316/131303378-8a4beb56-cbdb-4154-aebb-f29f03d13c8d.png)

![image](https://user-images.githubusercontent.com/49548316/131303393-53139980-4b81-4ccc-abea-cadfa4a02633.png)

**Comment by abnerlee** [comment]
We will fix in next version up soon.

**Comment by Ziflin** [comment]
This is probably related, but the following simple markup is also broken though it renders properly in source-code mode:

```This **bold** does *not* work.```

Expected: 

This **bold** does *not* work.

Results: The word "bold" is not shown in bold but is instead shown as `**bold**`.

The issue seems to be from the emphasis/italics appearing after the strong/bold in the text.
