### ISSUE TITLE
Hyperlink cannot jump to web page

### ISSUE THREAD

**Issue by Wj-creat** [typora/typora-issues#4637]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
Hyperlink cannot jump to web page

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
windows

**Typora Version**
0.11.8

**Additional context**

**Comment by abnerlee** [comment]
ctrl + click or open link from context menu?
