### ISSUE TITLE
Problem with table when export to PDF

### ISSUE THREAD

**Issue by pdcxs** [typora/typora-issues#464]
When export to pdf, if there is a table in second page, or there are many tables in a file, the head line of the table would appear in the first line of the page where overlap with the context.

This is my test file:

![test](https://cloud.githubusercontent.com/assets/3760797/21185892/7499d524-c24d-11e6-984e-6829179d8ebf.png)

**Comment by abnerlee** [comment]
Seems a bug of chromium (ref: http://stackoverflow.com/questions/7211229/having-google-chrome-repeat-table-headers-on-printed-pages)

It will be fixed when Electron upgrade to Chrome 55

**Comment by abnerlee** [comment]
fixed in new release
