### ISSUE TITLE
Allow unlimited notes in file list view

### ISSUE THREAD

**Issue by CR0CKER** [typora/typora-issues#4644]
For reasons unclear to me, Typora refuses to load the file view in the sidebar when there are more than 250 or so files in a directory. Only tree view is possible. As several people have requested in the past (but had their tickets closed because someone thought this isn't needed), it would be very useful to remove that limit, even if loading times are long. I keep Typora open most of the time, so I don't mind if the initial loading is a bit slow, but I have a couple thousand notes with hundreds of folders that contain local attachments, and the tree view is useless. The file view with preview snippets is awesome, but the limitation to 250 files means it's not usable for any significant amount of notes. 

I hope that instead of this ticket being closed like previous requests for this feature, contributors consider that some people do not use the tree view and need proper preview snippets as well as the option to ignore folders because they distract from accessing the actual notes. Thanks!

**Comment by abnerlee** [comment]
The list view does not only load filenames but also file contents for summary, and watch their changes, and 250 files is quite enough for most of the cases. 

For more files, you can switch to File Tree view.

We will consider this if more users are requesting about this limit.
