### ISSUE TITLE
[Feature] View only mode

### ISSUE THREAD

**Issue by XCanG** [typora/typora-issues#4645]
This is mostly related to Windows.
There are plenty editors already, however there are not much of simple viewers. I'm looking for software that I can use and share to my friends to preview markdown files.

So, what is needed is simply an option in a menu/settings to switch between **edit mode** and **view mode**. In **view mode** you can't edit anything, just look and clicking on links would not require to hold `Ctrl`. That's it.

**Comment by abnerlee** [comment]
#710

**Comment by mrbrownjeremy** [comment]
+1 this should be a View option. It not only helps prevent unintentional input, but it's also nice to navigate a doc without the markdown characters revealing themselves (which affects layout and can interrupt reading).
