### ISSUE TITLE
Where are "Recent Folders" stored?

### ISSUE THREAD

**Issue by lieszkol** [typora/typora-issues#4648]
There are at least two issues requesting the ability to remove folders from the "Recent Folders" list. Hopefully you guys will one day get to implementing that, until then, could you tell us where and in what format this list is stored (on Windows)? My guess would be C:\Users\User's Profile\AppData\Roaming\Typora\history.data, but this is a binary file and .data could be anything. A pointer here would be useful, so we can at least manually remove entries from the list that no longer exist on disk. 

Note: I have found one work-around, which is to temporarily rename any folder that still exists on disk but you don't want to see in Typora's "Recent Folders" list. Then select that location in Typora. It will show a dialog box, select "Choose Default Location" (or something like that), and choose another folder. Then the folder will disappear from your "Recent Folders" list.

**Comment by abnerlee** [comment]
It is stored in history.data but in binary

You can try remove all recent records from File -> Open Recent -> Clear Items.

I think it is not common for other apps to remove certain items from their history records as well. So I will close this, unless there are examples of how other apps do this, or similar requirements from other users.

Put into #2353

**Comment by lieszkol** [comment]
Ok, so it is as I suspected. 

For Typora, the "Recent Locations" is really more than just a history, it's a way to navigate between locations. Perhaps it ought to be renamed "Favorite Locations" with the the ability for users to manage this list. As for an example of where you can delete items from "history", this works for me in Microsoft Windows "jumplists", I can right-click "Remove from this list".  Or Microsoft Word/Excel, where I can also right-click to remove items from the recent documents list.

In any case thanks for Typora! I love it! If you made it commercial I'd buy it (as long as it isn't subscribtion based).

**Comment by abnerlee** [comment]
For the "list" in sidebar, it is possible to make it add-able / remove-able, we would improve this in future.

But for "same" "list" in menu, we cannot add a delete button on Window's native menu.

For jumplist, you can "pin" / "unpin" folders, I don't have Windows PC by hand, but I will check the ' I can right-click "Remove from this list"' later.

**Comment by abnerlee** [comment]
put into #5503
