### ISSUE TITLE
Version 0.11.5 (5648) Mermaid, parse error for directional tag 

### ISSUE THREAD

**Issue by coderinthenorth** [typora/typora-issues#4649]
----

When making a mermaid subgraph, the direction tag is non-functional. Most likely due to outdated version of Mermaid in Typora. Confirmed working on Mermaid 8.11.0. Typora is running 8.8.3.

**To Reproduce**
1. Create new mermaid flowchart

````
```mermaid
graph LR
	subgraph A
		direction LR
		a1 --> a2
	end
	subgraph B
		direction LR
		b1 --> b2
	end
0 --> a1
0 --> b1
```
````

2. This should produce the following flowchart
![Skjermbilde 2021-09-06 kl  18 01 23](https://user-images.githubusercontent.com/54352891/132242485-d1c50bf1-b796-4df5-823a-8dba643506bd.png)

![Skjermbilde 2021-09-06 kl  18 04 16](https://user-images.githubusercontent.com/54352891/132242623-ab348c44-8bf3-477a-8b89-54f4c7741b43.png)

**Expected behavior**
Would expect direction control of subgraphs

**Sample Markdown File**
[Mermaid_error.md](https://github.com/typora/typora-issues/files/7117069/Mermaid_error.md)

**Desktop (please complete the following information):**
macOS Catalina v. 10.15.7

**Typora Version**
0.11.5 (5648)

**Comment by abnerlee** [comment]
put into #1661

can be fixed after we upgrade mermaid version
