### ISSUE TITLE
How to change the HTML output href method?

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#465]
Now, the inner link `[text](#header)` output HTML would be change to `<a href="#header">`, but I need it change to `<a onclick="location.replace('#header')">`.

How to do it?!

**Comment by abnerlee** [comment]
Typora would follow Markdown's rule when converting to HTML. 

So, if you want `<a onclick="location.replace('#header')">`, the current way is to write `<a onclick="location.replace('#header')">` directly
