### ISSUE TITLE
[Feature] Support for Spongedown / SVG-bob

### ISSUE THREAD

**Issue by coderinthenorth** [typora/typora-issues#4650]
Spongedown is a markdown language for drawing pictures with Ascii characters converted to SVG-files. It can create nice graphical representation of text diagrams like flowcharts with more granular control then Mermaid. The markdown language also supports tables and Mathjax while drawing.

# Input
![Skjermbilde 2021-09-08 kl  11 22 51](https://user-images.githubusercontent.com/54352891/132483129-9d378f67-a6ee-4a80-976d-2297e7580e11.png)

# Output
![Skjermbilde 2021-09-08 kl  11 24 58](https://user-images.githubusercontent.com/54352891/132483416-0343862c-8bb3-4341-bdaa-52da73b035e2.png)

**Comment by abnerlee** [comment]
put into #1138
