### ISSUE TITLE
<iframe> not loading in Typora

### ISSUE THREAD

**Issue by coderinthenorth** [typora/typora-issues#4652]
**Describe the bug**
Embedded iframe from Whimsical (diagram and flowchart editor) not loading. Loads in browser when using a saved .html-file.

**To Reproduce**
1. Copy code
`<iframe style="border:none" width="800" height="450" src="https://whimsical.com/embed/5z8wWxYBzxecckKxgDdnZJ"></iframe>`
or any other <iframe> code from whimsical.com
2. Insert into Typora
3. Loads forever

**Expected behavior**
Expect to see iframe load

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![Skjermbilde 2021-09-09 kl  12 10 19](https://user-images.githubusercontent.com/54352891/132669166-08bd43f6-3b31-452b-bf25-c0c3c1c4ac7e.png)

![Skjermbilde 2021-09-09 kl  12 10 04](https://user-images.githubusercontent.com/54352891/132668837-c2fe7870-4a8f-45aa-8f12-ed679b475f45.png)

![Skjermbilde 2021-09-09 kl  12 10 43](https://user-images.githubusercontent.com/54352891/132669218-1ff97425-ef2b-4b6b-a685-215c33a0cf96.png)

**Desktop (please complete the following information):**
 - macOS Catallina

**Typora Version**
e.g: 0.11.5

**Comment by Kabulaka** [comment]
version 1.1.5, also not working. when will it be solved?

**Comment by abnerlee** [comment]
fixed in 1.3.6
