### ISSUE TITLE
Empty line added when navigating between two sequential code blocks

### ISSUE THREAD

**Issue by aphistic** [typora/typora-issues#4655]
**Describe the bug**
I'm working on a file where I have two code blocks one after the other without any additional content between them. When I try to use the up/down arrow between the two blocks an empty line is added between the two. I like that it has a point between the two to add content if I needed it but I'd expect the empty line to go away if I navigate past it without doing something like pressing "Enter". This also happens when navigating above a code block that's right at the beginning of a file.

**To Reproduce**
1. Create a new markdown file
2. Create a code block with triple 'tick' marks
3. Create another code block below that with triple 'tick' marks
4. Ensure there's no empty lines between them in source code mode
5. Click in the top code block (after exiting source code mode)
6. Use the "down" arrow to navigate to the second code block
7. You'll see an empty space between the two code blocks that will come back even if removed every time the steps are reproduced.

**Expected behavior**
I'd expect the empty line to show up when navigating but then be removed if no content was added or "Enter" wasn't pressed while on the empty line.

**Screenshots / Screencasts**
Before navigating:
<img width="839" alt="before_navigating" src="https://user-images.githubusercontent.com/149495/132966911-186f213f-3c30-4959-a739-027ac3cb4f61.png">
After navigating:
<img width="840" alt="after_navigating" src="https://user-images.githubusercontent.com/149495/132966915-adb24cdf-afa7-49b9-8dfc-909b1ff17538.png">

**Sample Markdown File**
[code_blocks.md](https://github.com/typora/typora-issues/files/7148794/code_blocks.md)

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2

**Typora Version**
0.11.5
e.g: 0.10.11

**Additional context**
N/A

**Comment by abnerlee** [comment]
should be fixed
