### ISSUE TITLE
Unable to copy images to local folder.

### ISSUE THREAD

**Issue by ajitgoel** [typora/typora-issues#4658]
Typora is unable to copy images to the local folder eg: https://d1.awsstatic.com/diagrams/fsx/product-page-diagram_cryo_how-it-works@1.5x.21bcc0935a82ac4531d02a4feddf51d6bfbd6080.png image. What am I missing? 

![image](https://user-images.githubusercontent.com/6394444/133024525-cf35fa71-8ba8-4265-a002-e272d917aeb1.png)

![image](https://user-images.githubusercontent.com/6394444/133024594-59bbd8c3-b6fb-4b38-863d-95ab9daac365.png)

**Comment by abnerlee** [comment]
Did you write `![img](xxxx)` in typora manually? If it is manually written, then it will be kept as it since it is input by user.

If it is from drag & drop or copy & paste, then typora will do the convert.

**Comment by ajitgoel** [comment]
Hello @abnerlee , I did not write ![img](xxxx) in typora manually. I copied a whole exam results from a website and pasted into Typora. This issue has started occuring since a week or so, previously when I did the same action, all the images would be copied to my local folder. 
Is there a log setting that I can turn on to see why typora is unable to copy the files from the internet to my local pc?
