### ISSUE TITLE
Rename folder failed if it contains any subfolder

### ISSUE THREAD

**Issue by youshilife** [typora/typora-issues#4659]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

In Typora, sidebar, file tree view, rename a folder which contains any subfolder, nothing changed. After a long time then, an error alert window will popup.

If the folder don't contains subfolder, there is no such issue.

**To Reproduce**

1. Create folder structure like this:
  - `test`
    - `out`
      - `in`
2. Open folder `test` in Typora, and rename the folder `out`, the filename is not changed
3. Wait for a while, see error alert window

**Expected behavior**

The folder renamed normally.

**Screenshots / Screencasts**

![image](https://user-images.githubusercontent.com/89970414/133057277-0d3f2189-59a5-49a1-b514-a7506af35407.png)

**Desktop:**

 - OS: Windows 10 Pro x64 21H1 19043.1165

**Typora Version**

0.11.8 (beta)

I have removed all config files and reinstalled the Typora.

**Comment by abnerlee** [comment]
put into #5193
