### ISSUE TITLE
Fix display of mermaid arrowheads and fontawesome icons

### ISSUE THREAD

**Issue by abondrn** [typora/typora-issues#4661]
- [X] Searched existing issues to avoid creating duplicates.
- [X] Confirmed that it can be reproduced in built-in themes without customized css.
- [X] Searched http://support.typora.io/

----

**Describe the bug**
When I am talking about arrowheads, I am referring to the sections following [this heading](https://mermaid-js.github.io/mermaid/#/flowchart?id=new-arrow-types), namely new arrow types and multidirectional arrows. Why is this a bug and not a feature? Because while including this syntax passes parsing, it doesn't result in the actual effect (it ends up looking like a regular arrow. Additionally, icons as described [here](https://mermaid-js.github.io/mermaid/#/flowchart?id=basic-support-for-fontawesome).

**To Reproduce**
Steps to reproduce the behavior: see the attached markdown file.
[reproduce.txt](https://github.com/typora/typora-issues/files/7166504/reproduce.txt)

**Expected behavior**
Icons and alternate arrowheads should display.

**Screenshots / Screencasts**
![reproduce](https://user-images.githubusercontent.com/6758562/133365124-7842adda-5df6-400a-8d48-3d5da18e8ec1.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.0.1

**Typora Version**
0.11.5 (5648)

**Comment by abnerlee** [comment]
We do not support fontawesome since we do not have fontawesome embed.

For arrowheads, it seems a new feature from mermaid, so put into #1661, it will be supported after we upgrade mermaid
