### ISSUE TITLE
github主题修改字体不起作用

### ISSUE THREAD

**Issue by jhsswl** [typora/typora-issues#4664]
版本：0.11.8

问题：
GitHub主题，修改配置文件github.css 中body  font-family 内添加JetBrains Mono字体，放在首位，重启不起作用。

**Comment by 1900011604** [comment]
看看我这个？https://github.com/1900011604/Manjaro-KDE-Installation/blob/master/My%20Typora%20Theme.css

**Comment by abnerlee** [comment]
看下 #write 或者 p 的 selector 有没有覆盖 body 的 font 属性

**Comment by MakerFace** [comment]
> 版本：0.11.8
> 
> 问题： GitHub主题，修改配置文件github.css 中body font-family 内添加JetBrains Mono字体，放在首位，重启不起作用。

老哥，你解决了吗

**Comment by Firestar-Reimu** [comment]
我这边没有问题
