### ISSUE TITLE
Bug in base64 image recognition

### ISSUE THREAD

**Issue by epikgit** [typora/typora-issues#4665]
**Bug description**
I have this Temp.md file with two base64 images. 
The first one is correctly decoded, the other instead is visualized as code (the base64 text to be clear).
The two images have been build in the same way.

![image](https://user-images.githubusercontent.com/14310321/133731802-2e2de31d-50b3-4633-b1b2-6d58d84a176a.png)

**Desktop**
OS: Windows 11 64bit

**Typora Version**
0.11.2

[Temp.md](https://github.com/typora/typora-issues/files/7182981/Temp.md)

**Comment by abnerlee** [comment]
#88
