### ISSUE TITLE
Incorrect rendering of italic/emphasis for GitHub theme

### ISSUE THREAD

**Issue by dialex** [typora/typora-issues#4668]
**Describe the bug**
If you use the GitHub theme, then the italic rendering is broken because it renders as bold italic. If you switch to another theme, the rendering is fine.

**To Reproduce**
1. Select the GitHub theme
2. Type `"Some *text* example"`

**Expected behavior**
The word text is rendered as italic, like this -> *text*

**Actual behavior**
The word text is rendered as 900 bold italic, almost like this -> ***text***

**Screenshots / Screencasts**
![demo](https://user-images.githubusercontent.com/2140450/133931738-2d335946-e2d0-444a-89de-57c6575ba197.gif)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2

**Typora Version**
e.g: 0.11.5

**Comment by abnerlee** [comment]
Do you have any custom CSS for the github theme?

**Comment by dialex** [comment]
Not that I'm aware. I don't recall ever editing a theme. I can confirm, if you tell me how.

**Comment by abnerlee** [comment]
This seems a very obvious bug, but we didn't receive reports from other users.

So we suspect there's a modification on the CSS file or there are local file missing somehow.
Does upgrade to v0.11.11 solve this issue?

**Comment by dialex** [comment]
True, this bug would be easily spotted. I installed Typora (0.11.11) from scratch and the bug is still there 🤔 
I also upgraded to macOS 11.6

**Comment by ar** [comment]
I have the same problem with 0.11.11. Also trashed `~/Library/Application Support/abnerworks.Typora/,`, just in case, problem persist. Problem doesn't happen with other themes.

**Comment by abnerlee** [comment]
@ar also macOS 11.5.2?

**Comment by ar** [comment]
Currently macOS Big Sur Version 11.6 - I don't think Typora can't read local URLs, as a matter of fact, I've trashed `~/Library/Application Support/abnerworks.Typora/` and it recreated it on the next run.

Here is a small screen recording: https://capture.dropbox.com/HireyFQNXW2WutkR

BTW, updated Typora to 0.11.16 (5916) and the problem remains.

**Comment by abnerlee** [comment]
Possible to provide a screenshot of your folder content under ~/Library/Application Support/abnerworks.Typora/themes/github/ ?

**Comment by ar** [comment]
Sure!

```
~/Library/Application Support/abnerworks.Typora/themes/github$ ls -l
total 160
-rw-r--r--  1 apr  staff  20108 Nov  7 00:58 open-sans-v17-latin-ext_latin-700.woff2
-rw-r--r--  1 apr  staff  18456 Nov  7 00:58 open-sans-v17-latin-ext_latin-700italic.woff2
-rw-r--r--  1 apr  staff  18604 Nov  7 00:58 open-sans-v17-latin-ext_latin-italic.woff2
-rw-r--r--  1 apr  staff  19396 Nov  7 00:58 open-sans-v17-latin-ext_latin-regular.woff2
```
Here are the SHAs:

```
e54f8981dfe2c7909646716d7f3da669d5df2d15  open-sans-v17-latin-ext_latin-700.woff2
c82ea3212ffe73573716500a68fe56834cb8d0ac  open-sans-v17-latin-ext_latin-700italic.woff2
3c589bb9529b06d1a50df4c81ada0376fa600fd9  open-sans-v17-latin-ext_latin-italic.woff2
84a2292a0ae289e26139f38470c50b9fd9ed421f  open-sans-v17-latin-ext_latin-regular.woff2
```

**Comment by abnerlee** [comment]
Seems correct...

Could you check Help -> Enable Debug from menu.
Then click "Inspect Element" in context menu
And see (like following image) that those fonts are correctly loaded?

<img width="1079" alt="Screen Shot 2021-11-08 at 09 14 10" src="https://user-images.githubusercontent.com/1621242/140670023-296bb379-4e3e-4dad-9618-d66b5ee334e5.png">

----

And if you export to HTML, open it in Safari and Chrome. Does italic rendered correct in those two cases?

**Comment by ar** [comment]
Sure, here you go:

When I first write the document, I just see:

![Screen Shot 2021-11-08 at 08 30 24 ](https://user-images.githubusercontent.com/100354/140734798-b93cd31c-de0d-4181-9dfc-1dfb1347d16d.png)

When I export to HTML, a new entry shows up:

![Screen Shot 2021-11-08 at 08 31 00 ](https://user-images.githubusercontent.com/100354/140734854-da1134b1-7771-4be2-bb39-acc14f9b9f34.png)

The export to  HTML looks like this in Chrome (Safari looks the same)

![Screen Shot 2021-11-08 at 08 31 23 ](https://user-images.githubusercontent.com/100354/140734893-c484f855-7c96-478a-9e59-45767f95f0fd.png)

And here is the PDF output:

[test.pdf](https://github.com/typora/typora-issues/files/7496587/test.pdf)

**Comment by abnerlee** [comment]
- Could you click the red "!" icon in DevTools to see if there are errors when loading the woff2 font file?
- Could you check Font Book.app to see if you already have local Open Sans font. By default it will uses your system installed font, then try to request the font file.

**Comment by ar** [comment]
Ha! there you go. I guess I need to reinstall Typora.

![Screen Shot 2021-11-08 at 11 42 33 ](https://user-images.githubusercontent.com/100354/140762245-3a0fb02b-0c46-4dd6-8b4c-5858d3fee59f.png)

**Comment by abnerlee** [comment]
You don't. They are ignorable. Seems it simply did not load the font file somehow...

Could you do :

```
Could you check Font Book.app to see if you already have local Open Sans font. By default it will uses your system installed font, then try to request the font file.
```

**Comment by ar** [comment]
FYI, scratched the whole `~/Library/Application Support/abnerworks.Typora`, installed from scratch latest version 0.11.16, and I get the same error, failed to load those 6 resources.

**Comment by ar** [comment]
It seems I have those installed locally.

![Screen Shot 2021-11-08 at 11 52 22 ](https://user-images.githubusercontent.com/100354/140763874-7b69de60-995f-457c-9a8a-5e4fd5e98873.png)

**Comment by ar** [comment]
FYI - problem solved. It was definitely a fonts issue. I ran the automatic duplication detection, then restarted Typora, and worked perfectly. Thank you!
