### ISSUE TITLE
Linux: overly permissive file permissions (executable files writable by everyone)

### ISSUE THREAD

**Issue by irgendwr** [typora/typora-issues#4669]
Hi,

several files in typoras [.deb package](https://typora.io/linux/typora_0.11.8_amd64.deb) are writable by everyone. As this could potentially pose a security risk I suggest removing write permissions for group/other on all files.

Affected files can be discovered with `find /usr/share/typora/ -perm -o+w`.
It seems like only files in `/usr/share/typora/resources/node_modules` have the write permission enabled for group and other.

---

This issue was originally reported by @xsmile.

I'm the current maintainer of the [typora AUR package](https://aur.archlinux.org/packages/typora/) and fixed the issue there by adding `chmod -R go-w /usr/share/typora/resources/node_modules` to the build script as a workaround.

**Comment by abnerlee** [comment]
should be fixed in 1.0

**Comment by irgendwr** [comment]
I can confirm that that the issue is fixed. Thanks!
