### ISSUE TITLE
windows x64 version, display collapses

### ISSUE THREAD

**Issue by lutein** [typora/typora-issues#467]
*version: typora 0.9.22, windows x64 on surface pro4*
When I open this file written in another PC, it only displays the first part. And I drag to the end there is nothing, many words and pictures are missing. 
I reinstalled typora but it's useless.
**only display the first page like this**
![image](https://cloud.githubusercontent.com/assets/21138938/21299531/84217dd4-c5d7-11e6-817d-6a9ad40626e2.png)
![image](https://cloud.githubusercontent.com/assets/21138938/21299624/663e18e4-c5d8-11e6-97db-6d7af5709473.png)

**Comment by abnerlee** [comment]
Thanks for the bug report

1. If possible, could you attach the *md file which may cause this bug
2. have you modified the CSS theme, if so, also attach the modified css theme file

**Comment by abnerlee** [comment]
more detail required
