### ISSUE TITLE
Invisible Red Dots Appearing; Cause Issues with Export

### ISSUE THREAD

**Issue by Sam-OT** [typora/typora-issues#4670]
**Describe the bug**

I use Typora specifically for its maths/latex-type inputs. Frequently, there are invisible "red dots" after the latex-type expressions, ie `$...$[RED DOT]`. I have been unable to determined exactly when these occur. They don't matter when viewing the file in Typora---it appears to simply ignore them---however, I export the Markdown file using `pandoc`, and this causes issues. `pandoc` doesn't know how to handle it.

I attach three screenshots showing the behaviour below.

- First screenshot: the state with no red dots, shown from the 'standard', not source code, view
- Second screenshot: no change to file, just now in the source code view; there are no red dots
- Third screenshot: one space added by pressing the spacebar a single time
- Fourth screenshot: no change to file, just now in the source code view; there are multiple red dots

**To Reproduce**

Unfortunately, I am unable to reproduce this behaviour consistently. It seems to happen semi-randomly. I guess there is a definitive reason, I just haven't been able to figure it out.

**Expected behavior**

No red dots

**Screenshots / Screencasts**

![First screenshot: the state with no red dots, shown from the 'standard', not source code, view](https://user-images.githubusercontent.com/81111289/133979738-32c61c8a-16df-4249-a4b4-f82bd75512dd.png)

![Second screenshot: no change to file, just now in the source code view; there are no red dots](https://user-images.githubusercontent.com/81111289/133979764-373fa8a2-da47-4003-a8ce-c87566e0df5d.png)

![Third screenshot: one space added by pressing the spacebar a single time](https://user-images.githubusercontent.com/81111289/133979791-9580b89e-2324-4cba-acb0-6d18620da0e5.png)

![Fourth screenshot: no change to file, just now in the source code view; there are multiple red dots](https://user-images.githubusercontent.com/81111289/133979836-d372fc3b-29a1-4f05-b805-4fda35c6dd2d.png)

**Sample Markdown File**

I've attached my markdown file, but I'm not sure it'll be of much use.

[SampleMarkdownFile.md](https://github.com/typora/typora-issues/files/7194664/md.md)

**Desktop (please complete the following information):**
 - OS: Windows 10, 64-bit

**Typora Version**
0.11.0

**Comment by abnerlee** [comment]
Could you try 0.11.8? I think it is fixed already
