### ISSUE TITLE
editor broken on windows

### ISSUE THREAD

**Issue by shyandsy** [typora/typora-issues#4671]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
editor shows markdown file incorrect

the font is so lightness, and the code block has no color effect

**To Reproduce**
install latest version 0.11 on windows 10 x64, and open any markdown file which include code, task list and subtitle

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/5271457/134029878-bc26be0b-bbb8-49bc-b381-b6b5c1b5d569.png)

it looks like typora only render text color for selected line 

![image](https://user-images.githubusercontent.com/5271457/134039552-2a98ae4e-9646-48c3-bb9e-f012352d639a.png)

**Comment by abnerlee** [comment]
Try disable focus mode from view menu?
