### ISSUE TITLE
Windows - Download Update Window Is Unresponsive

### ISSUE THREAD

**Issue by peter-slattery** [typora/typora-issues#4672]
**Describe the bug**
On Windows, when opening Typora, a window appears indicating that there are updates to be downloaded. Scrolling through the list of changes and exiting the window via the 'X' in the header bar function properly, however, the buttons at the bottom for Installing the Update or Ignoring the Update do nothing when clicked.

**To Reproduce**
1. Run a Typora executable that is not up to date with the latest version
2. A window appears indicating updates are available.
3. Attempt to click the Download Update button. Nothing happens.

**Expected behavior**
The Download Update button begins the installation of an up-to-date version of Typora

**Desktop (please complete the following information):**
Windows 10 64-bit

**Typora Version**
Unfortunately I didn't think to post this before I manually installed the latest version by downloading it from the website so I'm not entirely sure. I installed Typora in Early July of 2021 and haven't updated it until today if that gives any indication of what version I was using.

**Additional context**
If another update rolls out and the bug is still present, I will update this posting with the version of Typora I'm using now.

**Comment by Geeyun-JY3** [comment]
See https://github.com/typora/typora-issues/issues/4541#issuecomment-885732720
