### ISSUE TITLE
[Feature]: How to change "![]()" to "<img>" when i using picGo ？

### ISSUE THREAD

**Issue by Brannua** [typora/typora-issues#4674]
Hello,
When i insert screenshot to .md files in typora from my clipboard, images can be upload to my image hosting automatically bcause using picGo.
however,  each time i insert screenshot to .md files in typora from my clipboard, the default grammar is "！[]（）"
is there any way to change the defauult grammar form "！[]（）" to img label so that i can custom size of my images or positions ?
Looking forward to your early reply, thanks very much.

**Comment by abnerlee** [comment]
merged into #2198
