### ISSUE TITLE
[Feature] Outline level control

### ISSUE THREAD

**Issue by BLK-Dragon** [typora/typora-issues#4676]
It would be nice to have control over how many heading-levels are displayed in Outline.

For example, when editing a giant markdown document, I'd like to see only first two levels of headers in Outline.

A combo-box with number, next to "filter" field would be a logical place for such control.

**Comment by francoisjoosteqa** [comment]
Yes please! That's exactly what I need. I know we can do this with the TOC by [adding custom css](https://support.typora.io/TOC-levels/), but that doesn't seem to affect the Outline

**Comment by abnerlee** [comment]
I think make outline collapsible is a better solution for this. Please see https://support.typora.io/Outline#flat---collapse-outline for more details.

**Comment by francoisjoosteqa** [comment]
The only issue with using the collapsed outline is that it now requires two clicks: first click takes me to the header I want, and the second click is required to re-collapse the header so that it doesn't all just spill out eventually.
