### ISSUE TITLE
After renaming old file name remains in the list

### ISSUE THREAD

**Issue by nurgasemetey** [typora/typora-issues#4677]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

When I rename file, file with old name remains in the list. Also when I click on file with old name, dialog opens and file with old name is removed from list. When I click on file with new name, again dialog opens with says that there are unsaved changes.

**To Reproduce**
1. Click rename file
2. Enter new file name.

**Expected behavior**
Renaming should be smooth.

**Screenshots / Screencasts**

https://user-images.githubusercontent.com/4669437/134678215-e4c746fc-7d73-4115-bbb0-bd6d636f22fe.mp4

**Sample Markdown File**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 Cinnamon 64bit

**Typora Version**
0.11.8(beta)

**Additional context**

**Comment by abnerlee** [comment]
fixed in 0.11.18
