### ISSUE TITLE
typora offen freeze in mac m1

### ISSUE THREAD

**Issue by leizhiyuan** [typora/typora-issues#4679]
- [x ] Searched existing issues to avoid creating duplicates.

- [x ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x] Searched http://support.typora.io/

----

**Describe the bug**
typora offen freeze in mac m1

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit] Mac M1

**Typora Version**

0.11.5 (5648)

**Additional context**

**Comment by abnerlee** [comment]
put into #4430
