### ISSUE TITLE
Export html title?

### ISSUE THREAD

**Issue by orschiro** [typora/typora-issues#468]
Dear all,

The great export to html feature export uses the entire file name for the HTML title.

Example: 

File name of the document is "This is my document.md", then the title becomes the same "This is my document.md". If you put this online and it is going to be indexed by Google, then the title with the ".md" ending looks very strange.

I have two proposals:

Either allow for a custom title name OR

export the file name without file ending to be used as the title.

What do you think?

Yours,

-Robert

**Comment by AlexPasternak** [comment]
Very strange. I can confirm that `<title>Some test.md</title>` was exported. This pretty clearly should exclude the file extension, who would want that in their title?

**Comment by orschiro** [comment]
Thank you for your support.

I hope we can do something about it. :-)

**Comment by abnerlee** [comment]
`YAML front matter` should work, for example
```markdown
---
title: title
author: someone
---


content content....
```

And we will make Typora smarter if `YAML front matter` is not provided.

**Comment by orschiro** [comment]
Hmm, I just tried exactly this in YAML front matter but it still exports the file name as the title...

**Comment by abnerlee** [comment]
fixed in new release (title in YAML will be applied)

**Comment by orschiro** [comment]
This is great, thank you!
