### ISSUE TITLE
[Feature] Detect a Git repo and set image root to path of the repo

### ISSUE THREAD

**Issue by realmazharhussain** [typora/typora-issues#4680]
Many images are not shown when reading README.md file of some GitHub projects because they assume the repo's root to be the actual root when showing images.

It would be great if Typora could detect if the file being edited is inside a git repo and if it is, set/assume image root to be root of that git repo.

**Comment by abnerlee** [comment]
Please check https://support.typora.io/Images/#relative-path-to-certain-folder

There will be conflicts if user insert images related to the markdown file, but typora renders it related to the git repo.
