### ISSUE TITLE
Looks blurry on windows 10

### ISSUE THREAD

**Issue by Geliv** [typora/typora-issues#469]
*version: typora 0.9.22, windows x64*
I find that `typora` has the same problem with `chrome` that the fonts looks blurry on windows 10.
I've solved this problem with chrome by disabling `directwrite`, and setting fonts to be `YaHei, Georgia, Verdana, Consolas`. These settings make chrome fonts looks very clear and nice now. 
I tried to do the same thing by setting `conf.user.json`, and after restarting, I don't find any improvement... Is this a bug or something? or, I have done something wrong?

Here's the screen shot of `typora`.
![image](https://cloud.githubusercontent.com/assets/20089973/21315700/62fc4362-c638-11e6-9cf5-5beeeb56b95c.png)
And here's what it looks like when exported to `html` and opened in chrome.
![image](https://cloud.githubusercontent.com/assets/20089973/21315778/b6189870-c638-11e6-967c-154ff380bdb8.png)
On my screen, the first one looks blurry and the second one looks very sharp.

Regards.

**Comment by abnerlee** [comment]
Hi, what's your **Chrome** version?

**Comment by Geliv** [comment]
Sorry, I'm out now. But I'm sure it should be the latest version.

**Comment by abnerlee** [comment]
relates to https://github.com/electron/electron/issues/8708

**Comment by abnerlee** [comment]
Ready used much newer version of Chrome.

**Comment by vitidev** [comment]
@abnerlee  And what is the result? It is now in the [Electron FAQ](https://github.com/electron/electron/blob/master/docs/faq.md#the-font-looks-blurry-what-is-this-and-what-can-i-do).
But the user of the program can not do anything - he is not a developer
