### ISSUE TITLE
"!=" and "==="

### ISSUE THREAD

**Issue by Brannua** [typora/typora-issues#4690]
Hi,
When i write "!=" and "===" in my codeblocks, i always get signs like below. Is there any way to solve the problem ?

![image](https://user-images.githubusercontent.com/38487617/135461054-b61152ff-a71a-4387-89e1-ff0c3152db2f.png)
![image](https://user-images.githubusercontent.com/38487617/135461124-c1ee0e3c-96f4-4c8a-83bd-27916dac775e.png)

**Comment by myyangang** [comment]
This feature is called "ligatures", which can combine some characters togother to make code easier to read.

It seems that you are not using themes that typora provides for you, becasue there is no lightblue color for codeblocks in default themes. Obviously the CSS of the theme you are using now select a font which support ligatures. According to [issue #889](https://github.com/typora/typora-issues/issues/889), you could change your CSS style as this guy said.

Good Luck.

**Comment by Brannua** [comment]
> This feature is called "ligatures", which can combine some characters together to make code easier to read.
> 
> It seems that you are not using themes that typora provides for you, becasue there is no lightblue color for codeblocks in default themes. Obviously the CSS of the theme you are using now select a font which support ligatures. According to [issue #889](https://github.com/typora/typora-issues/issues/889), you could change your CSS style as this guy said.
> 
> Good Luck.

非常感谢！我猜您也是中国人，所以就用中文了哈；我尝试了 889 这个 issue 中的说法，在我添加的第三方主题 css 文件末尾追加了 889 中提到的代码，重启 typora 问题仍旧存在，是我少做或错做了什么吗？非常感谢您的回复！

**Comment by myyangang** [comment]
试一下[这个方法](https://github.com/typora/typora-issues/issues/1871#issuecomment-430099466)吧，如果原CSS中已经带有这个属性，就直接在此修改就行了，最好不要在末尾追加了，`none`和`!important`应该足以生效了。

顺便问一下，你用的主题是在哪儿下载的，我也想用 :)

**Comment by Brannua** [comment]
> 试一下[这个方法](https://github.com/typora/typora-issues/issues/1871#issuecomment-430099466)吧，如果原CSS中已经带有这个属性，就直接在此修改就行了，最好不要在末尾追加了，`none`和`!important`应该足以生效了。
> 
> 顺便问一下，你用的主题是在哪儿下载的，我也想用 :)

感谢，经过尝试不起作用，我的 typora 主题文件备份在了我的 github 仓库，点击[这里](https://github.com/Brannua/dot_files/tree/master/typora_themes)

**Comment by myyangang** [comment]
[CSS font-feature-settings 属性](https://www.w3school.com.cn/cssref/pr_font-feature-settings.asp)

> /* 没有常见的连字 */
> .ex3 { font-feature-settings: "liga" 0; }

![image](https://user-images.githubusercontent.com/26623948/135805096-b0efe6a3-64cc-48eb-a284-ad5131a6a666.png)

试着把`liga`属性改成`off`或者`0`试试

**Comment by Brannua** [comment]
> [CSS font-feature-settings 属性](https://www.w3school.com.cn/cssref/pr_font-feature-settings.asp)
> 
> > /* 没有常见的连字 */
> > .ex3 { font-feature-settings: "liga" 0; }
> 
> ![image](https://user-images.githubusercontent.com/26623948/135805096-b0efe6a3-64cc-48eb-a284-ad5131a6a666.png)
> 
> 试着把`liga`属性改成`off`或者`0`试试

感谢！问题解决，liga 和 calt 都必须都设置为 off 才能生效，非常感谢您！

**Comment by AhmedThahir** [comment]
Still not fixed for me in MacOS v0.11.16
