### ISSUE TITLE
[Feature] - For disabilities access, it is good practice to name images, provide title.  The feature request is to streamline pasting image, allow for options to prompt user for new file name and title "pre-save"

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#4692]
Currently when pasting an image, I need to right click the image afterward, open the path, rename the file, then bring that name back into the MD, and then edit the title.  

Can there be an option to enable that when pasting images to have typora prompt pre-save for a filename and alternate title?

Or, optionally a right click action, "Properties" to change the name and title which would then generate the proper MD.

**Comment by abnerlee** [comment]
put into #2198
