### ISSUE TITLE
Pandoc 2.14.2 not found under Typora for windows (x64, 0.11.8)

### ISSUE THREAD

**Issue by florian-huber** [typora/typora-issues#4693]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I want to export a md file (say to openoffice or word) than Typora complains that it requires Pandoc.
I did all steps described by the documentation (install Pandoc, restart, set path, restart...).

Pandoc is in the windows PATH and can be run from a console without any issues.
Also tried setting the path to the pandoc.exe manually, as well as copying the pandoc.exe to the folder of the .md file, both of which didn't solve the problem.
Any other ideas what could be wrong?

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.11.8

**Pandoc Version**
2.14.2

**Comment by abnerlee** [comment]
Did you try Config Pandoc Path in preferences panel?

see https://support.typora.io/Install-and-Use-Pandoc/
