### ISSUE TITLE
[Feature] Fast link creation: Select text, paste URL to create link

### ISSUE THREAD

**Issue by joakimc** [typora/typora-issues#4694]
I've noticed some editors (e.g. Slack's comment field) have this smart way of creating links. Just highlight the text you want to make into a link and paste the URL. I think this increases the efficiency considerably when needing to create several links in a text.

**Comment by p13rr0m** [comment]
If I understand you correctly, I think under MacOS this is already to some extend possible . What I am doing is copy the link, then select the text I want to transform into a hyperlink and press CMD+K (Menu bar -> Format -> Hyperlink). Unfortunately, this does not work with relative file paths.

**Comment by joakimc** [comment]
I find it very convenient, and I think the case where you want to replace selected text with an url is a bit of an edge case. At least I don't think I've ever encountered it when using Slack.

**Comment by abnerlee** [comment]
Closing this since "Unfortunately, this does not work with relative file paths." should be improved.

Or the original request, we will continue supporting ctrl+k.
