### ISSUE TITLE
Huge delay appears in a slightly larger file

### ISSUE THREAD

**Issue by Taswen** [typora/typora-issues#4695]
- [x] Searched existing issues to avoid creating duplicates.
  - #68 
    The problem disappeared for a while in previous versions. But now it appears again. I hope dear developers don't forget.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe**
When I open a slightly larger Chinese file (I don’t know if the files in other languages ​​are the same) to edit using Pinyin IME which is build in Windows10，the following occurs：
- The typed letters do not appear (or there is a huge delay).
- There will be a huge delay after selecting the word and pressing the space.

Waiting is really painful.

**Expected behavior**
I don't want typora to have this huge performance degradation when editing slightly larger files. This will prevent it from becoming the main tool for my editing work.

**Screenshots / Screencasts**
- Normal type in
  ![动画-正常](https://user-images.githubusercontent.com/30777327/135626824-66b1794b-3310-43d7-9a83-a1253c6b3674.gif)

- Huge delay
  ![动画](https://user-images.githubusercontent.com/30777327/135626685-7975cd53-2b18-49b2-9999-82a1593a11cd.gif)

20,000 words is not a lot of words in Chinese.

**Desktop (please complete the following information):**
 - OS: Windows10 Professional Edition 20H2 19042.1237

**Typora Version**
0.11.8

**Computer**
Lenovo laptop Yoga 14s (Ryzen 4800H)

**Pinyin IME**
I am using the old version. After testing, the new version will also have the above problems. I think it’s not the IME problem.

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> the sample file for a test?

Also, how about input plain English words without IME, will there be delay?

**Comment by Taswen** [comment]
> Also, how about input plain English words without IME, will there be delay?

No

**Comment by abnerlee** [comment]
should be improved in latest version

**Comment by jaekyeom** [comment]
> should be improved in latest version

@abnerlee I'm sorry, but what does "latest version" exactly mean? Is it already out there, or is it a planned new version?
I'm using v0.11.11 and experiencing this issue.

**Comment by pmdscully** [comment]
I am experiencing a delay in large files, typing in **English**,  length is 30k to 40k words. Editing tends to hit delays after 28k and wait time is between 5-20 seconds.  @abnerlee I have emailed a sample file with more info.

It seems my slow down occurs when editing text in an existing bullet-point (e.g. at top of file). After typing a word or two in the middle of the line, there's a 5-10 sec delay, then followed by a 10-20 sec delay.
