### ISSUE TITLE
No editor window?

### ISSUE THREAD

**Issue by nabati** [typora/typora-issues#4696]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Unfortunately, I don't have a clear repro. 
Essentially, at times, Typora doesn't open the file that I'm trying to open. 

There isn't even an editor area, even if I try to create a new file. 

This issue persists even if I restart Typora. 

Once I restart the computer, Typora works as normal again, which is surprising to me. 

Is there a component external to the main app that could be restarted independently?

![image](https://user-images.githubusercontent.com/1499050/135711426-1ec60f5f-d646-4627-8759-828239787ca7.png)

Unfortunately I don't have a repro, but this usually happens after 1-2 days of not restarting my computer. 

**Desktop (please complete the following information):**
Macbook Pro M1

**Typora Version**
0.11.5

I've been with Typora for long and this issue has appeared in recent version(s).

**Comment by Junzhou-712** [comment]
Same problem happened on my computer.
![image](https://user-images.githubusercontent.com/62588223/135765167-3eb96994-c03e-4873-9765-a9c3bd5c9525.png)
I cannot handle this problem even if I reinstall typora, or open  Typora/contents/MacOS/Typora.
Literally, when i opened Typora, the terminal shows that 
no such file or directory: Applications/Typora.app/Contents/MacOS/Typora
Saving session...completed. 
![image](https://user-images.githubusercontent.com/62588223/135765352-dbe07c72-bfff-4b2e-98c5-8a3361820b3f.png)

My computer is macbook pro m1
the version of typora is  0.11.5

**Comment by abnerlee** [comment]
seems same with #4430
