### ISSUE TITLE
Can’t edit title/author/header/footer with Chinese

### ISSUE THREAD

**Issue by Cccczzz007** [typora/typora-issues#4698]
Export PDF

Export operation succeeded with warnings
Failed to add header/footer view more

WinAnsi cannot encode”标题”

whether use YAML or not, this error makes the header is hidden

**Comment by xingyuXXX** [comment]
+1
and it seems that if the markdown file contains Chinese, the YAML does't work.

**Comment by abnerlee** [comment]
duplicated with #4485
