### ISSUE TITLE
Search function in preference crashes.

### ISSUE THREAD

**Issue by syitong** [typora/typora-issues#4699]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When typing in the search box in the preference window, the preference window crashes immediately.

**To Reproduce**
1. Open the preference window;
2. Type in the search box at the top left corner.

**Expected behavior**
The preference window crashes and disappears. And the preference window cannot be opened again through the main window.

**Desktop (please complete the following information):**
debian buster

**Typora Version**
v0.11.8

**Comment by abnerlee** [comment]
fixed
