### ISSUE TITLE
Three finger tap not possible in the beginning of the document

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#47]
In OSX, when you tap a word with three fingers, it gives you the definition of that word. This is pure goodness — also usable for spell checking. This feature might be off on a particular system, here's how to get it back on: http://notebooks.com/2015/10/05/how-to-get-back-three-finger-tap-os-x-el-capitan/

Typora doesn't give access to this feature in the first 247 characters or so. Only the word that begins with the 248:th character of the file can be defined. This also holds true for the last ~250 characters, but unfortunately, I was unable to reproduce this with lorem ipsum (maybe has something to do with preceding formatting, length (I've got +5k words), saved versus unsaved file or something). Anyway tapping with three fingers in these areas does nothing.

In the following examples, I've highlighted the word that is the first that can be defined. You can copy-past this to Typora and see for yourself.

Example 1: Unformatted text
> Lorem ipsum dolor sit amet, volumus omittam dissentiunt nec ea, rebum repudiandae definitiones est no, ad ipsum vocibus perpetua nam. An eum habeo philosophia, te ullum suscipit vivendum vis. Nam ne dicat mentitum imperdiet. No case munere per, ans **eam** impetus platonem. Doming equidem incorrupte pro no, libris antiopam percipitur vix at, iuvaret aliquando per cu. Ea vim nominavi definitiones, ex nam accusamus deterruisset.

Example 2:  Paragraphs
> Lorem ipsum dolor sit amet, volumus omittam dissentiunt nec ea, rebum repudiandae definitiones est no, ad ipsum vocibus perpetua nam. An eum habeo philosophia, te ullum suscipit vivendum vis. Nam ne dicat mentitum imperdiet.

>No case munere per, ans eam impetus platonem. Doming equidem incorrupte pro no, libris antiopam percipitur vix at, iuvaret aliquando per cu. Ea vim nominavi definitiones, ex nam accusamus deterruisset.

Example 3: With formatting (if you remove the emphasis on "per", the first available word is "ans", it's because of character count)
>##  Lorem ipsum dolor

> Sit amet, volumus omittam dissentiunt nec ea, rebum repudiandae definitiones est no, ad ipsum vocibus perpetua nam. An eum habeo philosophia, te ullum suscipit vivendum vis. Nam ne dicat mentitum imperdiet. No case munere **per**, ans eam impetus platonem. Doming equidem incorrupte pro no, libris antiopam percipitur vix at, iuvaret aliquando per cu. Ea vim nominavi definitiones, ex nam accusamus deterruisset.

Might be easy to fix because the limits are near 256 characters, which, as everybody knows, is a magic number(!) But because it works in between, I'd say this is a low priority issue.

**Comment by abnerlee** [comment]
Yes, sometimes, the three finger tap does not work. 

The reason is unknown but we will investigate and fix this.

**Comment by abnerlee** [comment]
should be fixed
