### ISSUE TITLE
Windows uninstaller doesn't have Typora in its name

### ISSUE THREAD

**Issue by abrudz** [typora/typora-issues#4700]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
If I want to uninstall Typora on Windows, it is almost impossible to find the uninstaller, as its full name is just the version number, without mentioning the name Typora. One can therefore neither find it using the search, nor spot in on Apps & Features.
**To Reproduce**
1. Press Start
2. Type "remove program"
3. Type "Typora" in the search field (won't find anything)
4. Now clear the search field and look for the version number of the currently installed version

Hitting Uninstall will get you to the UAC, and only then can you ask for more info to reveal the Typora path.

**Expected behavior**
The uninstaller should include "Typora" in its name.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/10961427/136046330-272597f8-6c4c-4a20-9e53-4447b65c21ab.png)

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10 Pro 64bit 21H1

**Typora Version**
0.10

**Comment by abnerlee** [comment]
try uninstall it and install Typora 0.11?

In my test, 0.11 have name
