### ISSUE TITLE
[Feature] Add keyboard shortcut to comment single/multiple line/s

### ISSUE THREAD

**Issue by AlessioQuercia** [typora/typora-issues#4704]
I searched among the issues, on google and [here](https://support.typora.io/Shortcut-Keys/), but I haven't found anything related to this. Is there a way to add a shortcut to comment single/multiple line/s?

The comment function is not listed among the shortcuts, and it is unbinded in the application.

**Comment by abnerlee** [comment]
See https://support.typora.io/Shortcut-Keys/#change-shortcut-keys

"Comment" command is under Format menu

**Comment by MahtabBukhari** [comment]
thanks

**Comment by MahtabBukhari** [comment]
thanks
