### ISSUE TITLE
`--mermaid-flowchart-curve` option does not take effect

### ISSUE THREAD

**Issue by 2-3-5-7** [typora/typora-issues#4706]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

   **(only exists in css)**

- [x] Searched http://support.typora.io/

----

**Describe the bug**
`--mermaid-flowchart-curve` option does not take effect

**To Reproduce**

1. Markdown File
   ```
   flowchart LR
   	a --> b & c -->d
   ```
   base.user.css
   ```css
   :root {
     --mermaid-flowchart-curve: step;
   }
   ```
2. No change in the appearance of the curve

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit 1709]

**Typora Version**
0.11.8

**Comment by 2-3-5-7** [comment]
When I changed the keyword `flowchart` to `graph`, it took effect, but this did not match the example in [the document of mermaid](https://mermaid-js.github.io/mermaid/#/flowchart). The keywords `flowchart` and `graph` seem to have [the same meaning](https://github.com/mermaid-js/mermaid/issues/1888). Is typora considering supporting this new keyword `flowchart` ?

```mermaid
graph LR
	a --> b & c -->d
```

**Comment by abnerlee** [comment]
step seems newly introduced by mermaid.

So I will merge this into #1661

Typora side will upgrade mermaid from time to time
