### ISSUE TITLE
Typora 0.11.10 crashes on launch in MacOS

### ISSUE THREAD

**Issue by Minderer** [typora/typora-issues#4708]

**Comment by nadim116** [comment]
I also have this issue. The application crashes every time i try to open typora after the update. 
I also redownloaded the application and the behavior is the same.

**Comment by Pomax** [comment]
https://typora.io/dev_release.html exists, no reason to make it sound like it's impossible to get older versions

**Comment by Scarano** [comment]
> https://typora.io/dev_release.html exists, no reason to make it sound like it's impossible to get older versions

Ahh thank you! I didn't know how to find that.

**Comment by Pomax** [comment]
note that 0.10.8 doesn't work, but 0.11.5 works fine on macos as far as I can tell

**Comment by WangZeCen** [comment]
Same issue here.  It crashes every time when i try to open it after upgrade to 0.11.10.  My OS is MacOS BigSur 11.6.

**Comment by aakside** [comment]
> Does 0.11.9 works?

It works for me on Big Sur.
[https://typora.io/download/Typora-0.11.9.dmg](https://typora.io/download/Typora-0.11.9.dmg)

**Comment by abnerlee** [comment]
should be fixed in 0.11.11

**Comment by Pomax** [comment]
can confirm that 0.11.11 no longer crashes for me on macos mojave
