### ISSUE TITLE
Support file URI on Linux

### ISSUE THREAD

**Issue by perqin** [typora/typora-issues#471]
* OS version: Debian 8.6
* Typora version: 0.9.22

I'am using Typora on Linux and I find that when usinng 'Open with Typora' in my File Exporer, Typora won't open the selected file, but start a new document. Then I use terminal command to start Typora: 
```
typora /home/perqin/Temp/test.md
```
And it works. I finally figure out that my file exporer (PCManFM on Debian) pass the URI instead of file path as the argument to Typora:
```
typora file:///home/perqin/Temp/test.md
```
The command above has the same result as that when opening from my file exporer. So please add support for file URI, thanks.

**Comment by abnerlee** [comment]
fixed in new release
