### ISSUE TITLE
How to color some of my text in the file?

### ISSUE THREAD

**Issue by MagaFun** [typora/typora-issues#472]
Like this.
![image 2](https://cloud.githubusercontent.com/assets/11616436/21435221/8baec050-c8b3-11e6-9f65-46ef0b9b264a.png)

**Comment by abnerlee** [comment]
#227

**Comment by gandalfsaxe** [comment]
Just to clarify: is it possible in any way to get colored text in the live preview of Typora?

**Comment by DutchPete** [comment]
@abnerlee:
this syntax `<span style='color:blue'>BLUE</span>` now requires one to select a language. Not being a coder myself, which language should I use?

**Comment by GandalfSaxe** [comment]
@DutchPete I believe that would be HTML.

**Comment by DutchPete** [comment]
@GandalfSaxe no, choosing HTML as the language does not do the trick.

**Comment by tsulimancsi** [comment]
i think using span with color works however if you try to add more items it will not work 

![image](https://user-images.githubusercontent.com/79659749/112403480-8a604680-8d1f-11eb-8af0-bf963653a9cc.png)

**Comment by tsulimancsi** [comment]
this is what works for me 
`<h1 style="color:blue;text-align:center;">This is a header</h1>`


![image](https://user-images.githubusercontent.com/79659749/112403564-b5e33100-8d1f-11eb-8e6a-342ec3a181fa.png)

**Comment by rahul-ahuja1** [comment]
Another way:
`<font size=4, color='red'><b>chosen font</b></font>'
