### ISSUE TITLE
[Feature] keyboard shortcut for sub- and superscript

### ISSUE THREAD

**Issue by jkrogager** [typora/typora-issues#4722]
Hi, first of all thanks for creating this great app! I've enjoyed it very much so far.

When I select text and hit CMD+B or CMD+I the editor sets the selected text in bold or italic, as expected. It would be nice if these keyboard shortcuts could be extended to superscript and subscript using the ^ ^ and ~ ~ syntax (if the option is enabled).

Thanks in advance!

**Comment by abnerlee** [comment]
https://support.typora.io/Shortcut-Keys/#change-shortcut-keys
