### ISSUE TITLE
[Feature] search function is way toooo slow in Mac

### ISSUE THREAD

**Issue by jankins** [typora/typora-issues#4723]
I LOVE typora. It's my favorite editor for markdown files. However, the search function is way too slow to be considered as useful. For a single 133KB file, when I am typing words in search box, the whole program freezes.  

To work around the problem, I have to open Sublime Text side by side to do the search, but this of course cause problems from time to time.

But really, if Typora is going commercial without useful search function, at least, I am not willing to pay for it.

**Comment by abnerlee** [comment]
Possible to provide a sample md file and keyword you use?
