### ISSUE TITLE
[feature request] cursor 'go back' and 'go forward'

### ISSUE THREAD

**Issue by deltakam** [typora/typora-issues#4727]
Imagine a functionality implemented in many editors (especially those for coding) where you press 'Cmd + [' and the cursor moves the cursor to the previous location, and press 'Cmd + ]' and the cursor moves to the location before you hit 'Cmd + ['.

This is very useful when editing different sections and going back and forth. I often use this so I can look at the section A while editing section F and come back to section F.

**Comment by abnerlee** [comment]
#1574
