### ISSUE TITLE
Blank file when opening second file

### ISSUE THREAD

**Issue by yotna594** [typora/typora-issues#4729]
Hello ! 
- I get a blank file when opening a second file (open first one without pb, but the second file gives me a blank window)  −−> the file is not opened and  `Save As` suggets me « untitled.md »
- At that moment, if I try to `Ctrl + P` to open fast or recent, it says that **the path is incorrect**.
- However, even with that second window, there's no pb if I try to open the file with `Ctrl + O`, giving the complete (absolute) path to the file.

Thks for all your work.
Best regards.

**Comment by Liguobing00** [comment]
Same Issue!

**Comment by grunweg** [comment]
Same issue here! I'm running `version 0.11.13 (beta)` on Debian bullseye.

As an additional data point, I get the same symptoms when opening the second file through the file manager. (That is, select a `.md` file in your file manager, `nautilus` in my case, and open the file with typora.)
