### ISSUE TITLE
Cut and Paste actions adds extra new lines and unrecognized characters

### ISSUE THREAD

**Issue by cestrame** [typora/typora-issues#473]
I was copy/cut and paste from serval MS Word file to a .md file in typora. Every action added a lot of new lines and sometimes some unrecogized characters. Some of the whitespace between words were lost after paste.
```
Copied random sentence

e�q�m�

This is a really long sentence really long sentence reallylong sentence really long sentence really long sentence really long sentence reallylong sentence for testing testing testing testing.

/html>
```

**Comment by abnerlee** [comment]
Could you attach the sample Word file, and, what's your OS version

**Comment by abnerlee** [comment]
more detail required
