### ISSUE TITLE
Alt+Ctrl+J / I / K / L with AHK script turning Alt+Ctrl+J / I/ K/ L into arrow keys -> when held down, equivalent to pressing Alt i.e. selecting window bar menu

### ISSUE THREAD

**Issue by awelotta** [typora/typora-issues#4740]
I have an AHK script that converts Alt+Ctrl+I/J/K/L into Ctrl+Arrows. When I hold down this hotkey, in other contexts it simply repeats it, like normal Windows behavior with held down strokes. However, in Typora, holding down this hotkey causes me to move one word for the intial press, and then open up the the menu bar, (i.e. the thing that pops when you tap Alt). I don't have any idea why this would be happening.

My AHK script also uses Alt+I/J/K/L to get arrows without Ctrl. But the issue only occurs when I have both Ctrl+Alt (including Ctrl+Shift+Alt).

**To Reproduce**
Use an AHK Script containing the following
```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

MoveCursor(key) {
    shift := GetKeyState("Shift", "P")
    control := GetKeyState("Control", "P")
    alt := GetKeyState("Alt", "P")
    controlShift := control && shift

    if controlShift {
        Send, ^+%key%
    }
    else if shift {
        Send, +%key%
    }
    else if control {
        Send, ^%key%
    }
    else {
        Send, %key%
    }
}

; Alternatively, using Alt...
~Alt & j::MoveCursor("{LEFT}")
~Alt & l::MoveCursor("{RIGHT}")
~Alt & i::MoveCursor("{UP}")
~Alt & k::MoveCursor("{DOWN}")
```
Enable the script. Use Typora. Write some text. Navigate it by holding down Ctrl+Alt+I/J/K/L (which is intended to function like Ctrl+ArrowKeys).
It will perform the action once, corresponding to the initial keypress, and then holding it down will cause the `File` in the Menu Bar to be highlighted.

**Expected behavior**
The intended behavior is for it to function identically to key-repeat for Ctrl+ArrowKeys. This works in other applications; I've only found this issue with Typora.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.11.13

**Comment by abnerlee** [comment]
I don't have AHK installed, but in my test Alt+Ctrl+? won't open menus.

Could you try and see if without AHK, will Alt+Ctrl+? open menu bar?

And did you try https://www.autohotkey.com/boards/viewtopic.php?t=6255?

**Comment by awelotta** [comment]
In my preferences, I changed the Window Style to Unibody, and the issue
seems to have resolved.
