### ISSUE TITLE
Cannot save file and PDF export in Desktop folder / Debian

### ISSUE THREAD

**Issue by mixaul** [typora/typora-issues#4745]
Hi,
I'm using Typora 0.11.8 under Linux (Debian). Typora out of the box, no customizations etc.
The issue I have since some releases, If I have a document in Desktop folder, I cannot save it, Save as.. and overwriting the old file is possible, also I can save files there from any other editor.
Furthermore, if I try to export the file to PDF, Typora works endless on the export (also in Desktop folder), If I use a pandora export, like odf, that works without any issues.
If I copy the file to another folder, I can save, export to PDF etc.
Seems to be a minor issue, but  with older versions of Typora it was possible to use documents in Desktop folder.

Any hints or ideas?

Thanks
Mix

**Comment by abnerlee** [comment]
The issue is a bit too old, does 1.2.4 solve it?
