### ISSUE TITLE
[Feature] selective autonumbering of equations

### ISSUE THREAD

**Issue by jesuslop** [typora/typora-issues#4746]
If you take a look of professional maht papers, you realize that only the important equations are numbered explicitly, to be referenced later.

In Typora it looks to me that autonumbering is an all-or-nothing thing for equations. If I want to reference a small quantity of them, I can still manage by adding \tags with the numberings, but as equation cuantity increases with additions an deletions, the burden to maintain the tags turns that approach too cumbersome.

I would like to have custom counters, or the ability to fiddle with the javascript configuring MathJax in a update-resistant way, or whatever it takes to automatically number only singled-out equations. Than would give the app a more profesional polishment. Thanks for listening!

**Comment by chchen2021** [comment]
MathJax offers a way to do selective auto-numbering using the equation environment. Take a look at
https://docs.mathjax.org/en/v3.2-latest/input/tex/eqnumbers.html

In my field, it is typical to have automatic numbering of all equations. However, it does not hurt for Typora to offer the existing option of outnumbering and also the selective auto-numbering based on` \begin{equation} ... \end{equation}`. On iOS, iWriter Pro offers both options, and the flexibility is useful sometimes.

**Comment by jesuslop** [comment]
Problem is that I cannot configure Mathjax in any Typora supported way AFAIK. Javascript is sandboxed in raw HTML.

**Comment by abnerlee** [comment]
> MathJax offers a way to do selective auto-numbering using the equation environment. Take a look at
https://docs.mathjax.org/en/v3.2-latest/input/tex/eqnumbers.html

put into #5189 since it describe it better.
