### ISSUE TITLE
A shortcut for task list

### ISSUE THREAD

**Issue by GreatBahram** [typora/typora-issues#4751]
Hello there,

I think it would be awesome to provide a shortcut for the task list, as it is already available for most of the things.

Thanks

**Comment by abnerlee** [comment]
see https://support.typora.io/Shortcut-Keys/#change-shortcut-keys

**Comment by GreatBahram** [comment]
Thanks, I saw that before. I was talking about a default shortcut key....

**Comment by abnerlee** [comment]
Hmm... We will consider it if we got more similar requests. It's difficult to assign every item with a shortcut since keyboard keys are limited.
