### ISSUE TITLE
[Feature] Hope to preview the pages before exporting to PDF file

### ISSUE THREAD

**Issue by ZoroGH** [typora/typora-issues#4754]
when export to PDF, it will split the content to separate pages, especially when the page contains many images. **This probably make me adjust the image sizes many times.**

I would prefer a preview freature and maybe this can refer to the Marp
Marp slice the pages with "-----"
I just wonder if we can have the similar feature, that is , when I enable the **preview** feature, typora will show many _marker_  indicate different pages
the *marker* can be a single line which is almost transparent

**Comment by abnerlee** [comment]
#4471
