### ISSUE TITLE
Case sensitive searching UI inconsistency

### ISSUE THREAD

**Issue by CGamesPlay** [typora/typora-issues#4755]
Hey Abner, I found a bug when using Command-F to search case-sensitively in files.

**To Reproduce**
1. Create a new document and type "foo foo Foo" into it.
2. Press Command-F and type "foo" into the search field, and turn on case-sensitivity if it's not already on.
3. Press Escape or click into the document to hide the search interface.
4. Press Command-F or Command-G to continue searching.
5. Notice that the case-sensitive search button is still highlighted, but "Foo" is now highlighted as a search result (❌).
6. Click the case-sensitive button twice to attempt to fix the glitch. It works!
7. Click the case-sensitive button a third time. No search results are highlighted any more (❌).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G9323)

**Typora Version**
Version 0.11.11 (5873)

**Comment by abnerlee** [comment]
should be fixed in 0.11.16
