### ISSUE TITLE
Can't open specific main menu category directly using access key on Windows unibody style

### ISSUE THREAD

**Issue by Geeyun-JY3** [typora/typora-issues#4756]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Can't open specific main menu category directly using access keys on Windows unibody style

**To Reproduce**
1. use Alt + (E)dit, Alt + (P)aragraph, Alt + F(o)rmat, etc key combinations
2. only open the main menu, instead of corresponding menu category

**Expected behavior**
open the corresponding menu category

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
no need

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1288 64bit

**Typora Version**
e.g: 0.11.13

**Additional context**

**Comment by abnerlee** [comment]
Currently unibody style window does not have traditional menu, so they are just shortcuts to popup the old traditional menu
