### ISSUE TITLE
When adding a new line between the list items in Source Code Mode, the autocomplete of bullet list marker is werid

### ISSUE THREAD

**Issue by Geeyun-JY3** [typora/typora-issues#4757]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When adding a new line between the list items in Source Code Mode, the autocomplete of bullet list marker is werid. There should not be an autocomplete in this case. Just add a empty line instead.

**To Reproduce**
see the GIF below

**Expected behavior**
Like GitHub:
![github-list-enter](https://user-images.githubusercontent.com/49396421/139186983-d25af3d1-e912-430c-97ca-70354a32b3e8.gif)

**Screenshots / Screencasts**
In Typora:
![typora-list-enter](https://user-images.githubusercontent.com/49396421/139186978-5e15cd92-6cbd-4fb0-bf13-27a7cb5b18d9.gif)

**Sample Markdown File**
no need

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1320 64bit

**Typora Version**
0.11.13 (beta)

**Additional context**
nope

**Comment by abnerlee** [comment]
fixed in v1.5.x
