### ISSUE TITLE
Learn spelling not working on Ubuntu 16.10

### ISSUE THREAD

**Issue by orschiro** [typora/typora-issues#476]
Dear all, 

1. I add a word to "learn spelling"
2. The word is no longer underlined
3. I reopen Typora
4. The word is underlined again

Can anyone confirm this problem on Ubuntu 16.10?

Yours.

-Robert

**Comment by asdf2014** [comment]
Same problem for windows..

**Comment by abnerlee** [comment]
Should work on 0.9.29

**Comment by vasalx** [comment]
It does not.

![screenshot from 2017-07-03 22 58 58](https://user-images.githubusercontent.com/10196422/27806489-84ec9a9e-6043-11e7-9f57-22f31ba94e2c.png)
![screenshot from 2017-07-03 23 00 48](https://user-images.githubusercontent.com/10196422/27806490-84ef98ca-6043-11e7-9a23-1e691a476d80.png)
![screenshot from 2017-07-03 23 01 55](https://user-images.githubusercontent.com/10196422/27806527-af0cb624-6043-11e7-83b9-48eeeb0ea682.png)

**Comment by abnerlee** [comment]
merge to https://github.com/typora/typora-issues/issues/640
