### ISSUE TITLE
Inconsistent meaning of `shift`-`enter` and ability to enter hard line breaks

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#4760]
Definitions: [hard line break](https://spec.commonmark.org/0.29/#hard-line-breaks) vs [soft line break](https://spec.commonmark.org/0.29/#soft-line-breaks).

Within a table, `shift`-`enter` inserts a _hard line break_ (a `<br>` as that is the only supported form in a GFM table).

But outside a table, `shift`-`enter` inserts a _soft line break_. 

There are two things wrong with this:
- The inconsistency. `shift`-`enter`  should mean the same thing in all contexts.
- There is no convenient method to insert a hard line break. Instead one is forced to manually type `space` `space` `shift`-`enter`, which is a very unintuitive and unnecessarily hard.

## Expected behavior

- `shift`-`enter` should always insert a _hard line break_ in **hybrid mode**. This is standard behavior in many, many tools (e.g. rich text editors and word processors).
  - Which [CommonMark compatible](https://github.github.com/gfm/#hard-line-break)) representation of hard line break is inserted ideally should be user configurable. See #4759.

- _soft line breaks_: 
  - in **hybrid mode**: some other _default_ key combination should be mapped to  soft line breaks. Perhaps `ctrl`-`enter`. See below for more advanced solution.
 
  - in **source code mode**: `enter` should insert a soft line break. This makes sense since source code mode is a literal mode and `enter` should just mean `enter`. Users will use source code mode to visually format their Markdown source, if that's what they need to do.

 ## More advanced solution #4759

Give user total control via Settings. This can also address Issue #37, as shown below:
    
|                 | default         | example alternative |
| --------------- | --------------- | --------------- |
| new paragraph   | `enter`         | `enter` `enter` |
| soft line break | `ctrl`-`enter`  | `enter`         |
| hard line break | `shift`-`enter` | `shift`-`enter` |
    

---
- OS: macOS
- Typora Version: 0.11.11

**Comment by abnerlee** [comment]
It is now a `<br />` in table cell only because GFM table does not support `\n`,

so put into #4759 since it address this issue in a better way

**Comment by vassudanagunta** [comment]
> It is now a `<br />` in table cell only because GFM table does not support `\n`,

Yes, I knew that and mentioned it in the Issue above. The inconsistency I'm talking about is NOT `<br />` vs `space`-`space`-newline` vs `\`-`newline` as all three have the same effect: **hard** line break[^1]. The inconsistency is that the same key combo sometimes enters *soft* breaks and sometimes *hard* breaks.

[^1]: though which one Typora uses outside a table should be user configurable

**Comment by vassudanagunta** [comment]
@abnerlee  #4759 is a separate issue. That one is about customization. This one is about consistency.  That one lets you choose what key combination means `hard line break`. This one says that that key combination, whether hardcoded or customized, must mean the same thing in all contexts, e.g. whether in a table or outside a table. (It's not important that `hard line break` is implemented differently inside a table (`<br>` only) and that outside it's one of the three options, what matters is that it's a `hard line break` of whatever form.)

Fixing this Issue should be very easy/fast. That one you might not get to for a long time. I hope you can fix this one soon because existing behavior goes against how all other apps work.

**Comment by abnerlee** [comment]
Table does not support \n, and it is bad to disable shift+enter at all for consistency because table does not support it.

It's like command+b is strong, but in javascript code block, there's no need to insert `****` when press command+b just for consistency.

Or the consistency can be understand like shift+enter will insert a soft line break, in table `<br>` is chosen as the soft line break.

**Comment by vassudanagunta** [comment]
I don't think you understand what I've written. 

### 🚩 The consistency that is important is ***semantic***, not literal. 

> It's like command+b is strong, but in javascript code block, there's no need to insert **** when press command+b just for consistency.

`command`-`b` should *consistently* have the semantics of `strong`, not literal `****`.  In a code block there is no strong, so of course it doesn't work there. 

> Table does not support \n, and it is bad to disable shift+enter at all for consistency because table does not support it.

Again you're thinking *literal* consistency, not semantic. If `shift`-`enter` produces a hard line break in one place, it should produce a hard line in every other place *where hard line break is supported*. So:

- In a table, that key combination should produce a `<br>` because that is the only supported hard line break in a table cell.
- In a code block it should just produce a `newline`.
- In other Markdown contexts it should produce one of the following:
   - `space`-`space`-`newline`
   - `\`-`newline`
   - `<br>`.

   Which one? Either you choose one and hard code it, or let the user configure it per #4759.

#4760 is about semantic consistency.

#4759 is about letting the user configure which implementation of hard line break to use outside of a table and code blocks.

They are separate, as you can do one without the other. 

> in table `<br>` is chosen as the soft line break.

`<br>` is a hard line break, not soft. Please see the linked definitions above.

**Comment by abnerlee** [comment]
Hmm... Currently shift-return is used to insert a new line, which in most case is actually a soft line break, but to some or most end user, distinguishing soft break and hard break is a bit confusing, and in most languages in code blocks it behaviors like a hard break. And it will be more confusing, if it inserts `<br/>` or `\-\n` instead of insert a line break, it is just not consistent with any other apps. So it is just insert to a "default" line break.

For those who do understand line breaks in markdown and have their preferences, maybe #4759 can help them. But for the default behavior, I do not want shift+return to insert `<br/>`, or, do not allow users to insert line breaks in table because it is inconsistent. 

So for consistency, we need to define what "shift+return" actually mean, and that issue #4759. Currently it means a line break.

**Comment by vassudanagunta** [comment]
Sorry for this long thread, but I'm really trying to make Typora better. UX design is something I care about.

>  in most languages in code blocks it behaviors like a hard break

That's because in code, there is no such thing as paragraphs, so there is no distinction between soft and hard line breaks. It's just a newline.


## Paragraph Mode apps vs Line Mode apps

> it is just not consistent with any other apps.

There are two kinds of text editors: **Paragraph Mode** and **Line Mode**.

**In every Paragraph Mode app**, `enter` produces a new paragraph, and a special `Enter` (usually `shift`-`enter`) is used to enter a **hard** line break.

- iA Writer

  > iA Writer also allows you to insert a `<br />` into a paragraph by using Shift+Enter. This will add the spaces required at the end of the line for you.

- WordPress

  > ##### How do I add Enter In WordPress?
  >
  > The Simple Way to Add Line Breaks to WordPress An easy option is to just hold the shift button and click enter. This will push your text to the next line as you’re typing (as opposed to clicking enter which would just create a new paragraph).

- Google Docs

- MS Word

- Apple Messages, Facebook Messenger - enter sends the message, shift-enter adds a hard line break within a message (making a message analogous to a paragraph)

**In every Line Mode apps**, `enter` just means `newline`. They don't give special meaning to `shift`-`enter`:

-  GitHub Issues comments (what we are typing in right now)
- StackOverflow's Markdown editor
- Most minimal Markdown editors (which is why Typora is so popular. It is different.)
- Apple Messages on iPhone

**What about Typora?** It doesn't know which one it is!   In code blocks and source code mode, Typora is in Line Mode. This is GOOD!  In non-code, Typora sometimes behaves like a Paragraph Mode app, and sometimes a Line Mode app. This is BAD!



> to some or most end user, distinguishing soft break and hard break is a bit confusing

By making Typora inconsistent, you're increasing the confusion. You are literally giving `shift-enter` two different meanings. 



## You should at least be consistent with your "hybrid mode" vision

I see where our disagreement lies. I want a semantic WYSIWYG editor that uses a plain text format underneath. You see Typora as a **plain text editor**, where **the user just types plain text**, but it is instantly rendered in rich form. That's why you call it hybrid mode, not WYSIWYG mode. Hybrid mode is essentially *What You **Type** Is What You Get* (WY**T**IWYG). 

This is totally fine.  It's your software, and your vision.  ***But you are not being consistent with your own vision.***  If you want to be consistent with your vision, you should make #37 the default behavior. 

## #4759 will solve the problem only if...

1. you allow people enough control that they can choose one consistent model or another.
2. the default (at least for new users), should be one of the  consistent models (see below). Perhaps you can ask them on first time use which model they prefer.

|                          | Typora current confusing model                               | Line Mode<br /><br /> (like #37)                             | Paragraph Mode<br /><br /> (like #4760) |
| ------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | --------------------------------------- |
| new paragraph            | `enter`                                                      | `enter` `enter`                                              | `enter`                                 |
| soft line break          | `shift`-`enter`                                              | `enter`                                                      | `ctrl`-`enter`                          |
| hard line break          | manually enter `<br>` or `\`-`enter` or `space`-`space`-`enter` | manually enter `<br>` or `\`-`enter` or `space`-`space`-`enter`<br /><br />or for convenience, `shift`-`enter` | `shift`-`enter`                         |
| hard line break in table | `shift`-`enter`                                              | manually enter `<br/>`<br /><br />or for convenience, `shift`-`enter` | `shift`-`enter`                         |
| new line in code         | `enter`                                                      | `enter`                                                      | `enter`                                 |

​

**Comment by abnerlee** [comment]
> Sorry for this long thread, but I'm really trying to make Typora better. UX design is something I care about.

I understand this, and really appreciate it.

----

Currently

shift+return is line break (without distinguish hark line break and soft line break)
return is new paragraph (smart), smart means it can escape from list, blockquotes or HTML blocks, which is not just a new paragraph (like rich editors)
ctrl + return is new paragraph without moving out of current container.

We already used up shift / ctrl key. For other behaviors, users need to config.

To distinguish hard line break and soft one, users should config #4759 so they know what they are doing, or else they may ask why they cannot break lines in table, just line in outside paragraphs.

Also lists in Markdown is also confusing, soft line break at list item end is hard break, while in middle of text is soft break, so enter here (in line mode) is also inconsistent.

---

And for consistent, we need to disable shift+enter in table cell?

**Comment by vassudanagunta** [comment]
Sorry @abnerlee I've been busy at work, other projects, and holiday family stuff. I want to come back to this. But only if you are open to understanding my point. Only if you acknowledge there ought to be a way for someone to ***type a hard line break***, and that the key stroke(s) to do this will be the same in all contexts. This means that the same keystroke will:

- In regular text, it will insert a `<br>` `enter` or `\` `enter` or `space` `space` `enter` (user configurable)
- In any nested context (list item, block quote), it will insert the same as above + 
- In a table, it will insert a `<br>`
- In a heading, it will insert a `<br>`

The alternative is that the writer has to manually do each of the above, which in essence asking them to write in source code mode.

If you acknowledge this, I am happy to work with you to come up with something that achieves this while also handling all the points you list above. Otherwise I'll drop this request. I have too many things to do.

---

Also, thank you for the Typora Coupon!!! I haven't used it yet as I have been so busy. I'll install it now. 😀
