### ISSUE TITLE
Update Mermaid Version

### ISSUE THREAD

**Issue by AhmedThahir** [typora/typora-issues#4761]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Request**
Kindly update to the latest version of mermaid js

**Describe the bug**
There are various rendering issues such as
1. missing arrows
2. incorrect spacing/padding
3. flowchart type not getting syntax highlighting

**Platform**
Both Windows and MacOS

**Typora Version**
v0.10.11

**Comment by abnerlee** [comment]
#1661
