### ISSUE TITLE
Syntax Highlighting Broken for new JavaScript Features

### ISSUE THREAD

**Issue by mhwice** [typora/typora-issues#4763]
Syntax highlighting does not work properly when using new JavaScript features such as [private class fields](https://v8.dev/features/class-fields) (see attached image). I did a bit of research on this problem and I believe updating CodeMirror to the [latest version](https://github.com/codemirror/CodeMirror/releases) will fix this problem. 

<img width="982" alt="Screen Shot 2021-10-30 at 11 13 06 AM" src="https://user-images.githubusercontent.com/19433287/139538947-f50ff945-3335-4d31-9976-598fe8263033.png">

**Typora Version**
0.11.11 (5873)

**Comment by abnerlee** [comment]
should be fixed in 0.11.16
