### ISSUE TITLE
[Feature] Export markdown to a compressed format to share images to each other without upload and encoding

### ISSUE THREAD

**Issue by whenyd** [typora/typora-issues#4767]
It is possible to use a compressed format or to implement a new file format for sharing local images to each other. The only thing need to do is:

1. Add a new exporting option, like `Compressed Markdown(.cmd)`, it will compress images and the markdown itself to a file.
2. Imporing `Compressed Markdown(.cmd)`, it actually uncompress .cmd file and open the markdown.

We get a editable markdown and its images are also shared, it's not need upload images to internet, not need encoding.

**Comment by abnerlee** [comment]
I think #622 is a better option.

Also relates #3656
