### ISSUE TITLE
Failed to open large file. 

### ISSUE THREAD

**Issue by yanghao9527** [typora/typora-issues#4768]
When I open a large Markdown file, it shows on the screen
"The file is tool large to render in Typora"

**Comment by abnerlee** [comment]
We currently only supports Markdown file <= 2MB, which is already quite large for plain text files.

#1961

**Comment by tsbertalan** [comment]
> plain text files.

See my comment on #1961 -- if you include base64-encoded images (which is supported) it's quite easy to get over this threshold.
