### ISSUE TITLE
Show 'edited' when I click on the Heading 

### ISSUE THREAD

**Issue by cloris-cc** [typora/typora-issues#4769]
**Describe the bug**
When I click on the **Heading** 1/2/3..., file status will be changed to '**edited**'. But I have not changed anything.

**To Reproduce**

Initial md file:
![yeAKR7](https://gitee.com/jacky_cloud/oss/raw/master/uPic/yeAKR7.png)

when I click on the heading 'title1' or 'title2', the file status is changed to 'edited'.
![6FPTbj](https://gitee.com/jacky_cloud/oss/raw/master/uPic/6FPTbj.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey with m1 chip

**Typora Version**
Version 0.11.11 (5873)

**Comment by abnerlee** [comment]
duplicated with #2354
