### ISSUE TITLE
Buggy inline math

### ISSUE THREAD

**Issue by yoavram** [typora/typora-issues#477]
I love the editor.
However, I keep having problems with inline equations (display equations are amazing!).
They keep losing their surrounding “$” when I edit them and I have to put the “$” back and go to the menu and click “Edit->Math Tools->Refresh All Math Expressions…”.
It would be great if you could solve this and also maybe make “Refresh all math expressions” either automatic (after hitting “$”?) or a keyboard shortcut (Shift+M?).

Here's a screencast that demonstrates the issue. 
![typora_issue](https://cloud.githubusercontent.com/assets/1288133/21495481/6146b726-cc20-11e6-880b-f91cd7a875bd.gif)

**Comment by abnerlee** [comment]
It is a bug, but you could "enable" inline math from reference panel.

**Comment by yoavram** [comment]
I now enabled it from the Preference->Markdown menu. Behavior is still the same.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by yoavram** [comment]
Great, thanks!
Do you know when the brew cask formula will update to 0.9.9.8.8?
