### ISSUE TITLE
[Feature] Grammarly Integration

### ISSUE THREAD

**Issue by luyiwind** [typora/typora-issues#4771]
Hi,

Since grammarly released the API and Text Editor SDK recently, may it be possible to integrate Grammarly into Typora?

Grammarly Editer SDK:
https://developer.grammarly.com/docs/editor-sdk-intro

Any one has some ideas?

**Comment by luyiwind** [comment]
Also with example link as below
https://codesandbox.io/s/github/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk?file=/public/index.html

**Comment by abnerlee** [comment]
#1453
