### ISSUE TITLE
Help !! How to Recover lost files (May be bug)

### ISSUE THREAD

**Issue by dalei2019** [typora/typora-issues#4772]
Versions :
- macos catalina 10.15.7 
- Typora 0.11.5 (5648)

Steps:
1.  create file with name aaaaaaa.md
2. It took 3 days to type about 5000+ words into this document
3. I am very sure save the document at least once ( Edited is not displayed next to the file name)
4. Then the computer suddenly restarted today
5. The File is gone

Try:
1. Try to use **reverto to** options  , unfortunately the file is lost , there is no way to use this method
1. Searched the entire disk, but only found the illustration of the markdown file
```bash
# find / -name "aaaaaaa"

find: ./System/Volumes/Data/.Spotlight-V100: No such file or directory
find: ./System/Volumes/Data/.PKInstallSandboxManager: No such file or directory
find: ./System/Volumes/Data/.PKInstallSandboxManager-SystemSoftware: No such file or directory
find: ./System/Volumes/Data/mnt: No such file or directory
find: ./System/Volumes/Data/.DocumentRevisions-V100: No such file or directory
xxxx/docs/markdown/imgs/aaaaaaa
find: ./System/Volumes/Data/.TemporaryItems: No such file or directory
find: ./System/DriverKit: No such file or directory
xxxx/docs/markdown/imgs/aaaaaaa
find: ./dev/fd/3: Not a directory
find: ./dev/fd/4: Not a directory
```

This file is very important to me, how can I restore it ？

I would be very grateful if anyone can provide any help，Thanks !

**Comment by dalei2019** [comment]
I search the mac os console log , Finally I found this file is deleted by Avira .

![image](https://user-images.githubusercontent.com/3195838/140018328-810b3bc2-853d-4398-8fbf-6f5696bd5777.png)

I tried to go to the avira forum for help, so closed this issue.

**Comment by abnerlee** [comment]
Try TimeMachine?

**Comment by dalei2019** [comment]
> Try TimeMachine?
Thanks @abnerlee . 
Finally, I successfully found the missing file in the autosave directory.

```
/Users/my-user-name/Library/Autosave Information/XXXX.genstore.noindex
```

**Comment by YYan2017** [comment]
> 
I have the same problem as yours, but I can not find the XXXX.genstore.noindex file,
