### ISSUE TITLE
Auto refresh not working anymore 

### ISSUE THREAD

**Issue by geirivarjerstad** [typora/typora-issues#4773]
Expected behaviour:

    Open a markdown file in Typora. (No pending changes in Typora)
    Open the same file in another editor (Notepad++). Modify and save.
    Switch focus to Typora. Typora auto refresh the file and shows the changes made in the other editor.

A duplicate issuse is marked as closed, but the bug is still very active: https://github.com/typora/typora-issues/issues/2600

So I try to reopen that issue with this issue, since this bug is still an issue and problem.

**Desktop**
 - OS: Windows 10 64bit

**Typora Version**
0.11.13 (beta)

**Comment by phcamargo23** [comment]
Same problem.
OS Name:                   Microsoft Windows 10 Pro x64
OS Version:                10.0.19043 N/A Build 19043

**Comment by abnerlee** [comment]
should be fixed in 0.11.16

**Comment by alteriks** [comment]
@abnerlee I've downloaded latest version and can confirm that typora automatically recognizes, whenever file was changed.
Thank you for your help!
