### ISSUE TITLE
copy paste html file, image names should be unique

### ISSUE THREAD

**Issue by qigtang** [typora/typora-issues#4775]
- [ x] Searched existing issues to avoid creating duplicates.

- [ x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x] Searched http://support.typora.io/

----

**Describe the bug**
When copy and paste html pages into typora, for example, this one https://mp.weixin.qq.com/s/NAu8UJeFwSwzaHAp8LDwoA
all the file name stored locally will have the same name. That means after copying, in resulting markdown file, all images changed to the same image.

**To Reproduce**
1. go to https://mp.weixin.qq.com/s/NAu8UJeFwSwzaHAp8LDwoA
2. manually select all htmls, copy
3. paste to typora
4. now all images are the same now. In my typora preference, I specified "insert image" -> copy image to ./${filename}.assets

**Expected behavior**

It would be better if the image can have unique names. One suggestion is using SHA1 hash as image file name. 

**Screenshots / Screencasts**
NA

**Sample Markdown File**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
e.g: 0.11.13

**Additional context**
NA

**Comment by abnerlee** [comment]
should be fixed in 0.11.16

**Comment by abnerlee** [comment]
duplicated to #4688
