### ISSUE TITLE
Local (#) links support isn't full

### ISSUE THREAD

**Issue by lua-rocks** [typora/typora-issues#4776]
+ [x] basic links to another files `[link](file.md)` works
+ [x] `#links` to headers in current file `[link](#header)` works correctly
+ [ ] `#links` to headers in other files `[link](file.md#header)` doesn't work

And besides, clicking on link to .md file from the same project should **switch** to this file instead of opening a new window (the same thing happens when you click on a file from the left bar). You no need new window because left panel (Files) acts like tabs in a browser.

**Comment by abnerlee** [comment]
duplicated with #1231
