### ISSUE TITLE
[Feature] New line after non header/paragraph blocks

### ISSUE THREAD

**Issue by Lucien950** [typora/typora-issues#4780]
It is very difficult to create new lines after non header/paragraph blocks as it creates a new line inside that block. Maybe a control-enter, or shift-enter keybinding to do so would be nice.

**Comment by abnerlee** [comment]
Use down arrow key, or context menu to insert paragraph

Does it make sense?

**Comment by Lucien950** [comment]
> Use up / down arrow key, or context menu to insert paragraph
> 
> Does it make sense to you?

Say there is a quote box, then a math box, and you want to add some text in between. If you go down from the quote box, it goes straight to the math box, without adding a space.
