### ISSUE TITLE
Mermaid JS Flowchart Sizing

### ISSUE THREAD

**Issue by AhmedThahir** [typora/typora-issues#4781]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I want to enlarge my diagrams.

``` css
.md-diagram-panel-preview {
    zoom: 200%; 
}
```
works perfectly in windows typora

But it does not work correctly in macOS; this is what i get
![Screen Shot 2021-11-06 at 6 51 26 PM](https://user-images.githubusercontent.com/26618217/140613846-c8823a96-848c-4bf6-891b-844bdfe6ebc7.png)

Kindly help me out

**Expected behavior**
I expect the the padding and font sizes to be scaled up correctly without any gaps.

**Typora Version**
e.g: 0.10.11

**Comment by abnerlee** [comment]
The size is calculated by mermaid by its width, so you should make the mermaid size (width) bigger.

If you want bigger font, you can try something like 

```
.md-diagram-panel-preview > svg {
    font-size:20px !important;
}
```
