### ISSUE TITLE
task list checkbox disappears when next line is indented

### ISSUE THREAD

**Issue by mikey00001** [typora/typora-issues#4782]
task list checkbox of previous line disappears when next line is indented (did work fine in previous version)

reproduce as follows:

1. create task list
2. write new line
3. indent new line

![image](https://user-images.githubusercontent.com/91184743/140616999-7a917709-b74a-40d2-917a-947a72cc6dcb.png)

source code looks normal:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/91184743/140617016-42aaaa5b-4966-4b62-a611-8d769566b23f.png">

[sample.md](https://github.com/typora/typora-issues/files/7490873/sample.md)

- OS: Mac OS Catalina 10.15.7 (19H1419)
- Typora Version 0.11.15 (5910)

**Comment by abnerlee** [comment]
should be fixed in 0.11.16

**Comment by mikey00001** [comment]
can confirm: is fixed now
