### ISSUE TITLE
Last character on a line with LaTeX is moved to the next line when pressing "return" key at the end of the line

### ISSUE THREAD

**Issue by hesyifei** [typora/typora-issues#4783]
**Describe the bug**
The last character on a line containing LaTeX was moved to the next line when pressing the "return" key at the end of the line after clicking the end of the line.

**To Reproduce**
1. Open a new document.
2. Type `$hello$ world`.
3. Click some arbitrary character.
4. Click the end of that line.
5. Press the "return" key.
6. `d` was moved to the second line.

**Expected behavior**
A new line is created and the last character of the first line (`d`) is still on the first line.

**Screenshots / Screencasts**
![2021-11-06 14 24 41](https://user-images.githubusercontent.com/4939421/140624240-ba0436ca-a925-4192-a4af-853f14797694.gif)

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1 (21A559)

**Typora Version**
Version 0.11.15 (5910)

**Additional context**
Can confirm this problem does not occur in Version 0.11.11 (5873).

**Comment by abnerlee** [comment]
should be fixed in 0.11.16
