### ISSUE TITLE
[Feature] When opening a file from the `draftsRecover` folder, raise a warning

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#4784]
Whenever my PC crashes and I need to reopen my unsaved Typora documents from the `draftsRecover`, I often find myself days after this incident confusing the different auto-saved and manually-saved versions of some documents, e.g., `C:\notes.md` and `draftsRecover\2021-11-7 mynotes 001748.md`. It would be a small but helpful thing if Typora could automatically warn me when I open a file from the `draftsRecover` directory so that I am reminded to immediately save it at the right place rather than continuing with editing the draft version.

**Comment by abnerlee** [comment]
fixed in 0.11.18
