### ISSUE TITLE
Inline Styles Focus Mode

### ISSUE THREAD

**Issue by AhmedThahir** [typora/typora-issues#4787]
After the latest update on windows, focus mode is blurring out current line's inline styles also.
(the red dot shows the line in focus)

# Screenshots
## MacOS v11.16 (Latest)

![Screen Shot 2021-11-08 at 3 33 23 AM](https://user-images.githubusercontent.com/26618217/140666068-3d3d3f1e-93b5-437c-9a58-7f7cfd9b51d5.png)

## Windows v11.13

![image](https://user-images.githubusercontent.com/26618217/140666215-761ee77a-34b1-4806-bdd4-9d755b453d6e.png)

## v11.17 Windows (Latest)

![image](https://user-images.githubusercontent.com/26618217/140666032-f9f73dc2-e781-4a17-b37c-9f88e58835b5.png)

# Expected Behavior
The latest version of windows should not blur the current line's inline math in focus mode; it should be like the previous versions.

**Comment by abnerlee** [comment]
Which theme did you use? 

Does it happen in the built-in themes?

And could you share the sample .md file or code?
