### ISSUE TITLE
iframe can't load codesandbox

### ISSUE THREAD

**Issue by dragonk233** [typora/typora-issues#4788]
version: 0.11.17(beta)
window 10

this iframe can work at other place.
<iframe src="https://codesandbox.io/embed/ji-ben-antd-4-17-0-alpha-9-c3cxy?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="基本 - antd@4.17.0-alpha.9"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by abnerlee** [comment]
#4652
