### ISSUE TITLE
SVG renders correctly in Typora but is messed up in exported PDF

### ISSUE THREAD

**Issue by mbokinala** [typora/typora-issues#4789]
- [x] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
An SVG (containing a vertical line with an arrow on the end) is displayed correctly in the Typora editor but is messed up in the exported PDF (arrow is pointing in wrong direction)

**To Reproduce**
1. Create a markdown document and insert [this svg](https://drive.google.com/file/d/1Vgjai9POV-tRjHc0z3J3zJ1KviVTdKXu/view?usp=sharing)
2. Verify the arrow circled in the screenshot is pointing upwards
3. Export the file as a PDF: `File > Export > PDF`
4. Open the exported PDF

**Expected behavior**
The SVG should be displayed correctly in the exported PDF (the arrow should be pointing upwards)

**Screenshots / Screencasts**
In the Typora editor, the SVG is displayed correctly: 
![image](https://user-images.githubusercontent.com/30819652/140676705-5c05a637-3ff8-4b7e-9701-d028cb07d27c.png)

In the exported PDF, the arrow in the SVG points in the wrong direction:
![image](https://user-images.githubusercontent.com/30819652/140676736-d37c8c5c-fe31-443b-8043-784bfdacea78.png)

**Sample Markdown File**
[Circular Motion.md](https://github.com/typora/typora-issues/files/7493943/Circular.Motion.md) - NOTE: The SVG image link will not work in this document because the URL is a file path for my machine. Please download the SVG causing the issue (linked below) and update the path in the markdown file accordingly:

SVG causing the issue: [circular-motion.svg](https://drive.google.com/file/d/1Vgjai9POV-tRjHc0z3J3zJ1KviVTdKXu/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3 (Intel)

**Typora Version**
e.g: Version 0.11.16 (5916)

**Comment by abnerlee** [comment]
svg: ![circular-motion](https://user-images.githubusercontent.com/1621242/203505283-7dd0f211-eb6b-443c-bd2a-8841ba7a2ae4.svg)

**Comment by abnerlee** [comment]
Tested in 1.4.8, and seems fixed already
