### ISSUE TITLE
formula input bug (gif attached)

### ISSUE THREAD

**Issue by Lucid-A** [typora/typora-issues#4790]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
![screenshot](https://gitee.com/Lucid-A/myPicBed/raw/master/Typora/img/20211108164335.gif)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
0.10.17

**Additional context**

**Comment by abnerlee** [comment]
The bug is \rm not uin blue color?

**Comment by Lucid-A** [comment]
Not only the \rm is not in blue color, but the expected format is not applied to the following characters, which are expected to shown in Roman type due to the existence of "\rm" in front of them. And the bug only reproduced when the "\rm" is laterly added in front of the first character in the inline formula expression, neither type "\rm ABC" at one time nor fix "ABC" to "A \rm BC" will cause the bug. And there's no use by clicking "refresh all the math formula" option and reopening the file. It's also wired that when it comes to fix "alpha" to "\alpha", the bug will not be reproduced.

**Comment by abnerlee** [comment]
fixed in 0.11.18
