### ISSUE TITLE
Pressing backspace at the end of a line deletes a subsequent formula

### ISSUE THREAD

**Issue by grunweg** [typora/typora-issues#4793]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/
----

**Describe the bug**
Pressing backspace at the end of a line whose next line begins with a `TeX` formula deletes the line break and the formula.

**Steps to reproduce**
1. Create a file, `test.md` with the following content.
```
$ cat test.md
Test line
$1+1=2$
```
2. Place the cursor at the end of the first line, i.e. immediately after "line".
3. Press backspace.

**Expected behaviour.** The newline is erased and the formula moves onto the first line.
**Actual behaviour.** The line break is deleted, but the formula on the second line also is.

**Desktop OS**: Linux; Debian bullseye

**Typora Version**: 0.11.16 (beta)

**Note** that this bug exists for a few versions now. It doesn't happen if the subsequent line begins with plain text.

**Comment by abnerlee** [comment]
Should be fixed in 0.11.18 in my test.
