### ISSUE TITLE
Hot-reloading files doesn't work any more

### ISSUE THREAD

**Issue by grunweg** [typora/typora-issues#4794]
- [x] Searched existing issues to avoid creating duplicates. (There is a possible duplicate, see below.)
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/
----
**Describe the bug**
When a file opened in typora is changed by an external programm, typora doesn't reload the file automatically.

**Steps to reproduce.**
1. Create a new file, `test.md` and fill it with any content.
2. Open the file in typora.
3. Overwrite the file via some external programm (e.g. `echo "Test content" > test.md`).

**Expected behaviour.** The file is reloaded in typora, and I can see the new content.
**Actual.** The file is not reloaded; nothing happens.

**Desktop**: Linux; Debian bullseye
**Typora Version**: 0.11.16

**Additional context**
- This has worked on my computer before, but regressed --- I would say in the past six months. (I don't have a precise regression range; sorry.)
- This bug seems very similar, if not identical to #3841. Since that bug is marked as "needs more information"; I decided to re-file a bug with hopefully clear instructions. Apologies for the churn --- feel free to close one bug for the other.

**Comment by abnerlee** [comment]
should be fixed in #4773

Possible to provide a screencast of your operation?

**Comment by abnerlee** [comment]
#3841
