### ISSUE TITLE
"Insert Paragraph After" shortcut doesn't work with Enter key in them

### ISSUE THREAD

**Issue by Plutonium-239** [typora/typora-issues#4796]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The shortcuts for `Insert Paragraph After` and `Insert Paragraph Before` (can be found in the `Paragraph` menu) will not work if the shortcut contains the `Enter` key. (e.g. `Ctrl+Enter`). They work fine with other keys (e.g. `Ctrl+G`)
Insert paragraph after basically inserts a new line after the end of the current line, no matter where you are in the current line.

**To Reproduce**

Follow the guide to add shortcuts:
1. Add the shortcut in `keyBindings` in `conf.user.json` properly as
```
"Insert Paragraph After": "Ctrl+Enter"
```
2. Restart Typora
3. In a new file, write random letters (doesn't matter) in one line.
4. From somewhere in between that line, press the assigned shortcut.
5. Repeat these steps with the new shortcut being `Ctrl+G`

**Expected behavior**
The shortcut should work irrespective of `Enter` being present (trying to mirror Sublime Text's behaviour of ctrl+enter)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
e.g: 0.11.17 (beta)

**Comment by abnerlee** [comment]
can be covered in #4759
