### ISSUE TITLE
Tables with tab character are not parsed correctly

### ISSUE THREAD

**Issue by LinqLover** [typora/typora-issues#4799]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

**Describe the bug**
If the Markdown source contains tab characters inside a table, Typora will not parse & render the table correctly.

**To Reproduce**
1. Enter source code mode
2. Paste:
   ```md
   | header1	| header2	|
   | ---	| ---	|
   | cell1	| cell2	|
   ```
3. Exit source code mode

**Expected behavior**
The table is parsed & rendered correctly.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/38782922/141185644-5f6f926c-245a-4aca-a56a-691a60bd7968.png)

**Sample Markdown File**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit

**Typora Version**
0.11.8 (beta)

**Comment by abnerlee** [comment]
fixed in 0.11.18
