### ISSUE TITLE
Buggy window when using "Night" theme

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#480]
Using multiple tabs and any of the bright themes:

<img width="643" alt="zrzut ekranu 2016-12-30 o 17 36 51" src="https://cloud.githubusercontent.com/assets/7394091/21568661/b084e86a-ceb6-11e6-92b9-157be3e3d058.png">

Marvelous, it works. However, when using the "Night" theme:

<img width="650" alt="zrzut ekranu 2016-12-30 o 17 37 13" src="https://cloud.githubusercontent.com/assets/7394091/21568664/be619ae6-ceb6-11e6-828f-4e4755005daf.png">

I cannot switch between the tabs anymore 😔 

* Typora version: 0.9.9.8.5
* Operating system: macOS 10.12.2

**Comment by abnerlee** [comment]
fixed in new release
