### ISSUE TITLE
[Feature] Enhancing 'Find and Replace' with RegExp support

### ISSUE THREAD

**Issue by fuweichin** [typora/typora-issues#4801]
### Problem
Some times I need to transform plain text to markdown, so I paste an article of plain text to Typora WYSIWYG view, and add some marks, e.g. replacing `Section XXX` to `### Section XXX`. While Typora's `Find and Replace` doesn't support RegExp currently, I need to find it one by one, that makes me tired a little.

### Existing Alternatives
1. Copy and paste markdown source to another editor, Find and replace with certain regex rules, then copy and paste back

### Solution
Adding RegExp support for 'Find and Replace', like most advanced text editors and IDEs.

By the way, here is another feature to enhance 'Find and Replace':
when showing 'Find and Replace', put the selection text to search box if the selection text is not too long.

**Comment by abnerlee** [comment]
#2824

**Comment by abnerlee** [comment]
fixed in 1.3.6
