### ISSUE TITLE
Mermaid erDiagram does not show attributes, rendering is broken

### ISSUE THREAD

**Issue by paulboot** [typora/typora-issues#4805]
**Describe the bug**
The rendering of Mermaid erDiagram diagram were Entities have Attributes is broken

**To Reproduce**
This MD sample not render the Attributes and hides 2 entities in Typora 0.11.17 (beta) but works fine on https://mermaid.live/

````
```mermaid
erDiagram
    RING ||--|{ SWITCH : has_one_or_more
    RING {
    	int id
    	string name
    }
    SWITCH ||--o{ LINE : has_zero_or_more
    LINE ||--|| CPE: has-one
```
````

This MD sample works OK in Typora 0.11.17:

````
```mermaid
erDiagram
    RING ||--|{ SWITCH : has_one_or_more
    SWITCH ||--o{ LINE : has_zero_or_more
    LINE ||--|| CPE: has-one
```
````

**Expected behavior**
Expected the rendering done like on https://mermaid.live/

**Sample Markdown File**
See the samples above.

**Desktop**
 - OS: Windows 10 64bit Version 21H1 (OS Build 19043.1348)

**Typora Version**
0.11.17

**Additional context**
Bug in Mermaid or something in the rendering of lines with { } chars?

**Comment by silvaDominic** [comment]
Can't confirm that this _does_ work on older versions, but can confirm is _do not_ on latest. I literally _just_ upgraded too smh.

**Comment by abnerlee** [comment]
put into #1661
