### ISSUE TITLE
Selecting words does not work correctly with inline math 

### ISSUE THREAD

**Issue by tgeijten** [typora/typora-issues#4806]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
When selecting text using Ctrl+Shift+Right Arrow, inline math (via $$) is added automatically to the selection of a previous word, even if it is separated by a space.

**To Reproduce**
1. Open a new document
2. Type 'Variable $x$ represents'
3. Move the cursor to the beginning of the line and press Ctrl+Shift+Right Arrow
4. Both 'Variable' and $x$ are selected.

**Expected behavior**
Only select the one word ('Variable' in this case)

**Sample Markdown File**
Variable $x$ represents

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
e.g: 0.11.17

**Comment by abnerlee** [comment]
seems fixed in my test
