### ISSUE TITLE
Suffix duplicate when deleting filename on saving window.

### ISSUE THREAD

**Issue by xiaotianxt** [typora/typora-issues#4808]
**Describe the bug**
I'm using MacOS Monterey 12.0.1 (21A559), when I'm going to save a new file, I need to delete the filename that automatically generated by Typora window. Normally the automatically generated filename are selected (highlighted) for user to easily save the file. But when I decide to change the filename, I pressed "delete" button, the preffix `.md` duplicates.

Furthermore, I found that as long as the content in "filename input textbox" have form like `x.md`, when deleting the character `x`, a additional `.md` will pop up and the input value becames `.md.md`. I don't know if it was implemented by the system or typora.

The following gif shows the issue.

**To Reproduce**
1. Create a new file.
2. Press "CMD+S" to save the file.
3. Press "Delete" button to remove the filename(without suffix)

**Expected behavior**
I think for a user's perspective, after I press the delete button, the input box should only remain `.md`, but not generating a `.md.md`, I think your code may have some issue.

**Screenshots / Screencasts**
![ezgif-3-f3b2dfb284d4](https://user-images.githubusercontent.com/17041194/141647707-75c6b5df-9dda-4a99-841f-c1d6f2372b51.gif)

![ezgif-3-b4fd4318af4a](https://user-images.githubusercontent.com/17041194/141648149-310e24db-e03c-4c26-9168-f8bbb3d696fc.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.0.1 (21A559)

**Typora Version**
e.g: 0.11.16 (5916)

**Comment by abnerlee** [comment]
Could you provide this when save rtf or rtfd file TextEdit.app ?

The save dialog is managed by macOS, not by Typora

**Comment by abnerlee** [comment]
I can reproduce with TextEdit.app, so I think it is a macOS bug that cannot be fixed by our side.
