### ISSUE TITLE
Reload/Refresh even if Typora does not have a focus

### ISSUE THREAD

**Issue by wookayin** [typora/typora-issues#481]
Partially related to #165: Typora immediately updates the contents of the editor when the file is changed on disk.

However, the reload event does not occur when the application is not activated, i.e. it has no focus.
Is there any way to *tell* the application to refresh? If no, I would suggest 

- (i) to add an applescript API (as of there is no applescript suite)
- or (ii) to add an menu item such as "File > Refresh"

For example, 

```
tell application "Typora"
   reload
end tell
```

as in Chrome:

```
tell application "Chrome"
   reload
end tell
```

**Comment by abnerlee** [comment]
Typora will now immediately updates the content, so there won't be necessary to add reload menu

**Comment by wookayin** [comment]
Great! With the version 0.9.9.9.2, it works veryw ell.

> 4. Support refresh content automatically when file is changed even when Typora is not focused.

**Comment by mivanov** [comment]
In Version 0.9.9.22 (1979) it does not refresh when the file is changed on disk.

**Comment by wookayin** [comment]
I am using the same version 0.9.9.22 (1979) and it is working. But I remember there was a few moments where I experienced that auto-reload was not working, in some rare situations. Can you provide some more detail?

**Comment by mivanov** [comment]
@wookayin hmmm, looks like it generally doesn't reload if the file was modified via a script. Not sure if it's using a different file API under the hood or something. For example I use the following Python script to prepend a line to the start of the markdown file:

```
#!/usr/bin/python

JOURNAL_FILE = "/Users/micivanov/notes/log.md"

import sys

msg = sys.argv[1]

with open(JOURNAL_FILE, 'r') as original: data = original.read()
with open(JOURNAL_FILE, 'w') as modified: modified.write(msg + "\n" + data)
```

And when triggered Typora doesn't notice the change. However if I open the file in another editor, like Vim, and save it, Typora will immediately notice the change.

**Comment by mivanov** [comment]
Upon further testing, it seems that it does notice the change and reload, as long as Typora was not in foreground when the change happened. Kinda makes sense? I would prefer it always watched the file for changes though.

**Comment by mingxinwei** [comment]
> as long as Typora was not in foreground when the change happened. Kinda makes sense? 

I am a bit confused why this makes sense? 

currently working on a script to monitor the rename file event to auto change the image store dir & image url in markdown file, which unfortunately will run when Typora in foreground...

**Comment by mivanov** [comment]
@mingxinwei it **kinda** makes sense perhaps as an optimization if it only refreshes when it regains focus

**Comment by mingxinwei** [comment]
> @mingxinwei it **kinda** makes sense perhaps as an optimization if it only refreshes when it regains focus

Ok. Although I would prefer it always watched the file for changes too.

**Comment by mivanov** [comment]
Oh yeah I agree, would prefer if it did too.

**Comment by ahmedelgabri** [comment]
I just downloaded Typora (Version 0.9.9.32.1 (4191)) & it doesn't refresh at all, even when gains focus. It only prompts me that file changed on Disk if I try to quit the app. 

I was editing the file in vim & saved it already.

> Ok. Although I would prefer it always watched the file for changes too.

I'd also prefer that.

**Comment by ahmedelgabri** [comment]
Ok, I figured out why it was not working. I opened the file in Typora & also clicked with my cursor in the file itself (but without making any changes) & that apparently makes the app thinks that there are changes or something which disables auto-refresh.
