### ISSUE TITLE
New/Renaming File Issues

### ISSUE THREAD

**Issue by ianpotpie** [typora/typora-issues#4811]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**To Reproduce**
1. Open Typora
2. Open an already-existing file
3. Right click in the sidebar and select "new file" and name it "newfile.md"
4. In the sidebar 2 new files appear: "newfile.md" and "Untitled.md"
5. Clicking on "newfile.md" brings me into the an empty file
6. Clicking on "Untitled.md" results in a "Failed to load file" popup
7. Clicking on "newfile.md" after trying to open "Untitled.md" gives me a "Do you want to save the changes made to this document?" popup
8. If I added anything to "newfile.md", then clicking "save" will overwrite the contents of "newfile.md" and it will become empty
9. If I added anything to "newfile.md" and click "discard" then I keep the original contents of "newfile.md"

Something similar happens with renaming:
1. Open Typora
2. Open an existing-file "file.md"
3. right click on "file.md" in the sidebar and click "rename" 
4. rename to "file2.md" and hit enter
5. a new file "file2.md" will be created, but "file.md" will remain and stay selected in the sidebar
6. clicking either "file.md" or "file2.md" in the sidebar gives be the " Do you want to save the changes made to this document" popup
7. If I click on "file.md" and "discard changes" then I get a "Failed to Load File" popup
8. If I click on "file.md" and "save changes" then it opens a window where I can save the file as a new file
9. If I click on "file2.md" and hit either "save" or "discard changes" then it open "file2.md" with the original contents of "file.md", however, "file.md" remains in existence

**Expected behavior**

New File:
When I create a new file I would expect a single empty file to appear

Rename File:
When I renaming a file I would expect the file to change names without creating another new file.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
Ubuntu 20.04.3 LTS

**Typora Version**
0.11.16

**Additional context**

**Comment by abnerlee** [comment]
use #4813 for less description
