### ISSUE TITLE
The missing <p> tag environment in list items in exported HTML.

### ISSUE THREAD

**Issue by cruse123** [typora/typora-issues#4812]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
A standalone unordered list or the inner list of a nested one are not in a `<p>` tag environment in the export HTML files. Styles of unordered lists in the HTML file differ from the instant view in Typora editor.

**To Reproduce**
1. Open the example Markdown file provided below with Typora.
2. Use `Shift+F12` or menu bar to open DevTools, check the HTML elements of the editor.
3. Export the document to HTML.
4. Open the HTML file with a browser and check its elements with F12 tools.

**Expected behavior**
From the DevTools of Typora, each item of the list from `111` to `666`, including `aaa` and `bbb`, are all contained in a `<p>` environment, so the style persists throughout the nested list. Items behave like:
```html
<ul>
    <li>
    	<p>
            <span>some text of an item</span>
        </p>
    </li>
</ul>
```

However, in the exported HTML, the inner list items (`aaa` and `bbb` in this example) as well as a standalone list (`another...` in the example) are not placed under a `<p>` tag, which behave like:
```html
<ul>
    <li>
        <span>some text of an item</span>
    </li>
</ul>
```

The look in Typora (raw .md) and in the browser (exported .html) are not identical, especially the font sizes and line heights if custom themes are applied.

**Sample Markdown File**
```markdown
* 111
* 222
* 333
  * 444
    * aaa
    * bbb
  * 555
* 666



* another
* unordered
* list
```

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 x64
 - Browser: Microsoft Edge Version 95.0.1020.53 (Official build) (64-bit)

**Typora Version**
0.11.17 (beta)

**Additional context**

**Comment by abnerlee** [comment]
It's a spec in markdown.

When export
```
* 111
* 222
* 333
```

is nested list, become `<li></li>` without `<p>`

```
* 111

* 222

* 333
```

is loose list,  become `<li><p></p></li>`

In typora editing mode, we added `<p>`, since the tag is invisible to users, but they may feel page refresh / glitch when switching between loose list and nested one.
