### ISSUE TITLE
Two files appear after renaming the file

### ISSUE THREAD

**Issue by MakerFace** [typora/typora-issues#4813]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
When renaming a file, the original file and the new file appear at the same time

**To Reproduce**
1. right click markdown file
2. select rename
3. type new name and enter 
4. old file and new file **both appear**

**Expected behavior**
`bash.md` rename to `bash-rename.md`, and `bash.md` disappear.

**Screenshots / Screencasts**
After renaming:
![image](https://user-images.githubusercontent.com/19760290/141754308-d6a7b21e-0c17-4493-be94-308882ed41be.png)
Click `bash.md`
![image](https://user-images.githubusercontent.com/19760290/141754489-e32603dc-51b5-4cb4-9dde-e8a874386241.png)

**Sample Markdown File**
None

**Desktop (please complete the following information):**
 - OS:  Ubuntu-18.04, 5.4.0-90-generic, x86_64

**Typora Version**
version 0.11.16(beta)

**Comment by MakerFace** [comment]
Can i bind F2 to rename action?

**Comment by abnerlee** [comment]
duplicated to #4677

What's your filesystem btw?

**Comment by MakerFace** [comment]
> duplicated to #4677
> 
> What's your filesystem btw?

ext4
