### ISSUE TITLE
[Feature] Allow the user to set which file extensions Typora recognizes

### ISSUE THREAD

**Issue by ridleywinters** [typora/typora-issues#4817]
## Request
**Allow the user to set what extensions should show in the file tree and be open-able in the file browser.**

## Use case
I use MDX files and use Typora on multiple platforms.  Currently the Mac version does not recognize `.mdx` files as a known extension (whereas Windows and Linux do) which prevents me from using Typora on Mac for these files. `mdx` could be added to the list on Mac (which might be considered a "bug fix"). The suggestion here though is to instead make the list of extensions customizable so this would be addressed once for any and all Markdown-variants.

_Lastly, amazing work on Typora. It's an incredible app!_

**Comment by abnerlee** [comment]
duplicated with #1753
