### ISSUE TITLE
2 Page Layout for PDF

### ISSUE THREAD

**Issue by AhmedThahir** [typora/typora-issues#4818]
I'm sorry if the solution already exists, but I can't seem to find one.
If I want the pdf output to be in a 2 column layout, what CSS code do I require?

**Comment by abnerlee** [comment]
You can try https://support.typora.io/Add-Custom-CSS with

```
#write {
columns: 2;
}
```

Or use `@media print` if only want to apply when export / print
---
Or export via pandoc to PDF https://support.typora.io/Export/#pdf-latex--pandoc
