### ISSUE TITLE
Creating a theme, styling the code autoComplt-list

### ISSUE THREAD

**Issue by lostkeys** [typora/typora-issues#482]
I'm crafting a theme for Typora but having trouble styling the code dropdown list. The styles are rendered as inline html and I have trouble overriding some of them like widths, heights and certain margins. It's super hard to inspect since any movement with the cursor hides the autoComplt element.

![screen shot 2017-01-03 at 11 23 11](https://cloud.githubusercontent.com/assets/3122929/21605082/0ec46caa-d1a7-11e6-851c-1a9b53dfddf1.png)

Anyone have any suggestions how to solve? 
[The theme can be downloaded here](https://github.com/lostkeys/Typora-Lostkeys-Theme/tree/feat-code-tooltip)

**Comment by abnerlee** [comment]
> The styles are rendered as inline html and I have trouble overriding some of them like widths, heights and certain margins

So Typora should move inline styles to CSS class for code fences auto-complete list in future updates

**Comment by lostkeys** [comment]
Yes 👍

**Comment by abnerlee** [comment]
Should be fixed in new release.
