### ISSUE TITLE
[Bug] Cursor jumps to top of document when exiting image

### ISSUE THREAD

**Issue by mizimno** [typora/typora-issues#4820]
**Describe the bug**
Cursor jumps to top of document unexpectedly

**To Reproduce**
1. Move cursor to start of image
2. Press enter
3. Press up arrow

The cursor jumps to the top of the document

**Expected behavior**
The cursor should have moved to the line above the image

**Screenshots / Screencasts**
![typora bug](https://user-images.githubusercontent.com/1732810/142335451-63bd4192-7baa-4bd8-a209-f732583423b7.gif)

**Sample Markdown File**
[Untitled Markdown.md](https://github.com/typora/typora-issues/files/7559173/Untitled.Markdown.md)

**Desktop (please complete the following information):**
Ubuntu 18.04

**Typora Version**
0.11.18 for Linux

**Additional context**
Also happens if step 3 is changed to "Press enter".

**Comment by abnerlee** [comment]
should be fixed in new release
