### ISSUE TITLE
What does this curly braces serves for?

### ISSUE THREAD

**Issue by Azgrom** [typora/typora-issues#4822]
When writing a latex math block there is this curly brackets up in the left. What does it serves for?
![image](https://user-images.githubusercontent.com/14893177/142517797-13cc0f58-0d53-40e9-9cb1-c6936c64f903.png)

**Comment by abnerlee** [comment]
In some markdown spec, you can use `{}` for attributes, like class, citation, etc.

They are kept without breaking the parsing of math block.

**Comment by Azgrom** [comment]
Thank you!
