### ISSUE TITLE
[BUG]Modifying the CSS file cannot make the text justify on macbook.

### ISSUE THREAD

**Issue by Fancrey** [typora/typora-issues#4823]
I found that no matter how to modify the css file, the text cannot be aligned on macbook. The methods I tried are as follows:
1. Add paragraphs in the theme.css/theme.user.css file
\# write{
text-align: justify;
}
3. Add in base.css/base.user.css file
\# write{
text-align: justify;
}
4. Download a demo that looks to be justified themes, such as: Turing.
5. Add {text-align:justify} to paragraph {p} by the method of issue #1854 

The version I use is: Typora0.11.18 (5941), My system version is: mac OS Big Sur 11.6

**Comment by abnerlee** [comment]
Typora use same rendering engine as Safari (Webkit).

Safari does not support justify alignment. So we cannot do anything about this, unless we migrate to Electron...

**Comment by diegomcarvalho** [comment]
> Typora use same rendering engine as Safari (Webkit).
> 
> Safari does not support justify alignment. So we cannot do anything about this, unless we migrate to Electron...

Is it true? I can insert <p align="justify"> and Typora (and Safari) can render the text justified...

**Comment by abnerlee** [comment]
`text-align: justify;` and `whitespace: pre` can not be supported in Safari at the same time. While Typora uses `pre` to display all whitespaces user input...

So, you can try add `whitespace: normal;text-align: justify;` in your CSS.

**Comment by marklinmax** [comment]
Got the same problem, however justify works when the paragraph is inserted inside a <div style="text-align: justify;"> block. This proves that Safari can apparently do it, so why doesn't it work in CSS theme file?
