### ISSUE TITLE
Export md to PDF function processing export forever

### ISSUE THREAD

**Issue by erbanku** [typora/typora-issues#4824]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**
1. Go to 'File/Export'
2. Click on 'PDF'
3. Wait a moment
4. See error (it will be processing export forever)

**Expected behavior**
Normally export to a PDF file

**Screenshots / Screencasts**

https://user-images.githubusercontent.com/79493862/142653602-9586319b-bbd8-453a-9c1c-ad7c3af37e46.mp4

**Sample Markdown File**

Any markdown files

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
e.g: 0.11.18 (beta)

**Additional context**

**Comment by abnerlee** [comment]
try https://support.typora.io/Export/#export-pdf-not-working-on-windows?

**Comment by erbanku** [comment]
Solved! Thank you.
