### ISSUE TITLE
[question] typora-root-url not support absolute path?

### ISSUE THREAD

**Issue by AImager** [typora/typora-issues#4826]
img path : /Users/cong/Dropbox/Photo/Blog/1000/Git_areas.png

typora-root-url: /Users/cong/Dropbox/Photo

`![](/Blog/1000/Git_areas.png) ` image load failed

use inspect element to see, the image src is `file:///Users/cong/Documents/Users/cong/Dropbox/Photo/Blog/1000/Git_areas.png?lastModify=1637404776`

so that means I can't use absolute path in typora-root-url? is it possible to add absolute path support in typora-root-url?

![image](https://user-images.githubusercontent.com/5317650/142723214-ae819f05-e240-49ad-a957-6ed004e6c54b.png)

**Comment by abnerlee** [comment]
protocol is not supported in typora-root-url

should be covered by #2739
