### ISSUE TITLE
Spell checking dictionaries are re-downloaded after every launch on Windows 7

### ISSUE THREAD

**Issue by khokm** [typora/typora-issues#4827]
OS: Windows 7 64 bit
Typora version: 0.11.18

**Describe the bug**
I installed en-US dictionaries by clicking `Edit -> Spell check -> English (US)`. The notification window showed: 
```
Dictionary file is missing to enable spellcheck support for English (US)
Install Language Support?
```
i clicked Download and files in `Roaming\Typora\typora-dictionaries` directory has appear. Spell checking has started working.

After close and reopen Typora there are no spellchecking. After clicking `Edit -> Spell check -> English (US)` the notification window showed **again**, even with the fact that dictionary files are still here. It just re-downloads files and replaces it (according to modification date).

Setting this as default spell checking language in `File - Preferences - Editor` doesn't help.

**To Reproduce**
1. Click to `Edit -> Spell check -> English (US)`
2. Start typing to be sure that spell checking is working.
3. Be sure that files in `Roaming\Typora\typora-dictionaries` are exist.
4. Set English (US) as default language in `File - Preferences - Editor`
5. Close Typora.
6. Launch Typora.
7. Be sure that files in `Roaming\Typora\typora-dictionaries` are still exist.
8. Be sure that spell checking isn't working.

**Expected behavior**
Previously downloaded dictionaries must be detected on program startup.

**Comment by abnerlee** [comment]
relates #3584

**Comment by abnerlee** [comment]
same with #3584 ?
