### ISSUE TITLE
Support crossref Syntax (incl. math block bug)

### ISSUE THREAD

**Issue by mschroen** [typora/typora-issues#483]
Pandoc has a great and [famous filter](https://github.com/lierdakil/pandoc-crossref) to support cross references, e.g. using

    # Section {#sec:foo}
    ![caption](image.png){#fig:bar}
    $$ x=1 $$ {#eq:x}
    This text cites @eq:x and @Fig:bar and hints to @sec:foo.

It would be great if Typora would have syntax highlighting for those labels and references.

Nevertheless, Typora has no problems if those labels and refs appear in the text, except for math blocks!

    This does render well in Typora: $$ x=1 $$ {#eq:x}
    This does not render and sometimes destroys the whole document: 
    $$
    x=1
    $$ {#eq:x}

Perhabs this is a bug?

**Comment by masonlr** [comment]
Just re-iterating: allowing the following to render would make Typora extremely useful for technical writing with display style equations. I would be willing to donate and write a blog post if this feature was added.

```
This does not render and sometimes destroys the whole document: 
$$
x=1
$$ {#eq:x}
```

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/105
