### ISSUE TITLE
Downloading .deb files no longer works as listed

### ISSUE THREAD

**Issue by jima80525** [typora/typora-issues#4830]
- [ x ] Searched existing issues to avoid creating duplicates.

- [ x ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x ] Searched http://support.typora.io/

----

**Describe the bug**
On the [Install Typora on Linux](https://support.typora.io/Typora-on-Linux/) page, it states:

   The deb file is located at https://typora.io/linux/typora_${version}_amd64.deb, for example: https://typora.io/linux/typora_0.9.96_amd64.deb. Just download the deb installer at that url.

Unfortunately that does not appear to be available:

```
$ wget https://typora.io/linux/typora_0.9.96_amd64.deb
--2021-11-22 20:31:11--  https://typora.io/linux/typora_0.9.96_amd64.deb
Resolving typora.io (typora.io)... 172.67.97.82, 104.24.157.12, 104.24.156.12
Connecting to typora.io (typora.io)|172.67.97.82|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-22 20:31:11 ERROR 404: Not Found.
```

I'd love it if the .deb files could be made available, but if not I can add a PR to remove that section from the document.

**To Reproduce**

1. wget https://typora.io/linux/typora_0.9.96_amd64.deb
2. wget https://typora.io/linux/typora_0.11_amd64.deb
3. wget https://typora.io/linux/typora_0.11.0_amd64.deb

All three requests resulted in 404 error.

**Expected behavior**
Either the example download should work or that section of the document should be removed.

**Desktop (please complete the following information):**
New Ubuntu 20.04 install on a 64 bit machine

**Typora Version**
0.11 and 0.9 (I'll admit I didn't try 0.10)

**Additional context**
Thank you!

**Comment by abnerlee** [comment]
I updated the wiki, please get download link from https://typora.io/windows/dev_release.html since some old versions are not kept.

**Comment by jima80525** [comment]
AWESOME!  Thank you so much!
