### ISSUE TITLE
[Bug]The Update Interface bug, Download Update, Skip This Version, Remind Me Later click and no work

### ISSUE THREAD

**Issue by RshStone** [typora/typora-issues#4832]
**To Reproduce**
1. Open a READ.ME file using typora
2. Come with The Update Interface.

**Expected behavior**
Click Download Update and then can update
Click Skip Version and then can skip
Click Remind Me Later and then the Update Interface can disappear.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/62530115/143242581-98e8008a-64f7-4b36-a5e5-95c5357d0a47.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
 0.9.93
Latest version is 0.11.18

**Additional context**
The Update Interface bug, Download Update, Skip This Version, Remind Me Later click and no work

**Comment by abnerlee** [comment]
0.9.93 is outdated which cannot download updates due to https://github.com/electron/electron/issues/31212
