### ISSUE TITLE
[Feature]Typora crashes when rendering files larger than 2MB in real time

### ISSUE THREAD

**Issue by whoway** [typora/typora-issues#4835]
This software is great, it would be perfect if it can support the following functions
- Describe：
    - Typora version：0.9.96
    - Platform：Windows10+X64
    - Typora crashes when rendering files larger than 2MB in real time
- Question：
   - Will Typora consider adding support for large file rendering in the future?:smile:

**Comment by abnerlee** [comment]
We currently does not support too large file (as plain text)

see #4768
