### ISSUE TITLE
export to pdf, center style of table can't work 

### ISSUE THREAD

**Issue by waterstream** [typora/typora-issues#4836]
**Describe the bug**
the table in typora configures are as follow:
{width:80%; margin:0 auto;}
The display of table works well , but it displays left-align when the file exported to PDF.

**Desktop (please complete the following information):**
 - OS: ubuntu20.04

**Typora Version**
 - 0.10.18

**Comment by abnerlee** [comment]
You can add your style to `figure` selector or change style of `figure`. `<table>` is wrapped inside `<figure>`.

**Comment by waterstream** [comment]
adding style to figure selector really works
