### ISSUE TITLE
*.md file in WSL file system, inserting image cannot be displayed and  the  “upload image” function cannot be used

### ISSUE THREAD

**Issue by ArtizanZhang** [typora/typora-issues#4837]
I created an md file in the WSL file system and everything else works perfectly, but when I copy a screenshot to the md file, the image does not show up.  

![image](https://user-images.githubusercontent.com/30285287/143563087-b7bdbc19-87d4-4374-bbd9-15d94a8a0552.png)

Then I checked "Use relative path if possible" in the settings and the image is displayed, but I can't upload the image to the remote image bed.

![image](https://user-images.githubusercontent.com/30285287/143563339-6ad9e04c-6c39-45f1-a415-cd62b7071579.png)

**Comment by OhYee** [comment]
I have the same question.

**Comment by YiuTerran** [comment]
same problem

**Comment by senseandcalm** [comment]
same problem

**Comment by abnerlee** [comment]
fixed in v1.5.x
