### ISSUE TITLE
Tab not working in latest version to edit indentation level

### ISSUE THREAD

**Issue by dirkagterhuis** [typora/typora-issues#4838]
- [X] Searched existing issues to avoid creating duplicates.
- [X] Confirmed that it can be reproduced in built-in themes without customized css.
   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.
- [X] Searched http://support.typora.io/

----
**Description**
I can't use the `tab` key for increasing the indentation level of an (un)ordered list. 

**To Reproduce**
1. Create a new file with an (un)ordered list. 
2. Try to increase the indentation level using the `tab` key. Nothing happens. 
3. Decreasing indentation levels does work however: `shift` + `tab` for and already indented list item, and the indent will be decreased. 

Just to make it explicit: the `tab` key does work in other applications. 

**Expected behaviour**
For the indentation level to be increased. 

**Sample Markdown File**
```markdown
- First bullet
    - Second bullet
```

**Desktop**
OS: MacOs Monterey, 12.0.1

**Typora Version**
1.0.0

**Workaround**
Go to the raw markdown file and hit `tab`: works.

**Comment by antru** [comment]
I've noticed this as well

**Comment by njust** [comment]
+1

**Comment by abnerlee** [comment]
#4829
