### ISSUE TITLE
include markdown document inside markdown document (as image could be)

### ISSUE THREAD

**Issue by CorentinLemaitre** [typora/typora-issues#4839]
I use typora for many things including meeting report. I would like to propose a feature that could be applied to this use case. 

For each meeting I create a markdown document with typora and I let the people attending the meeting edit and correct the document.

All the meeting notes concerning a project are grouped in a specific folder. I would like to have a typora "master" document that embed the other markdown documents that I could export as PDF and keep all the source markdown files separated. 

I would like that markdown file integrated as image file are integrated for example. 

This could be also usefull to other use cases : a journal with many articles, a report with many chapters...

**Comment by abnerlee** [comment]
#441
