### ISSUE TITLE
Tab list indentation broken since 1.0 on macos

### ISSUE THREAD

**Issue by berendbaas** [typora/typora-issues#4840]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----
First of all congrats on the 1.0 release. I've been enjoying this software for a while, so I was happy to pick up a license.

**Describe the bug**
List indentation using the `tab` key no longer works on macOS (since updating to the 1.0.1 release)

**To Reproduce**
1. Go to a blank page.
2. Insert a list item & hit enter to insert a second list item.
3. Hit `tab` to increase the indentation level of the second item.
4. Nothing happens

**Expected behavior**
Like in previous versions, I would expect tab to indent the list entry.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7

**Typora Version**
1.0.1

**Comment by abnerlee** [comment]
fixed in 1.0.2, sorry for th trouble

**Comment by abnerlee** [comment]
#4838
