### ISSUE TITLE
计算Fingerprint你们的代码里有BUG

### ISSUE THREAD

**Issue by pengzhile** [typora/typora-issues#4842]
最近很多群里都在讨论你们这款编辑器，说你们收费了，让我测试一下。
我只有mac环境（所以以下都是以macOS为基准），说说测试结果，当然是成功了的（你们的renew接口被我hosts屏蔽），图如下：
<img width="525" alt="image" src="https://user-images.githubusercontent.com/343491/143678647-09aa83b3-3558-42ed-9ec9-0b6c72ed1f3e.png">

接下来我试着编写生成器，看你们代码的时候发现你们生成fingerprint的时候貌似代码有bug。
你们的逻辑是拿IOPlatformUUID做sha256后base64取前10个字符作为fingerprint。
但貌似你们在hash的时候byte数组的长度恒定传递了0值。这结果导致所有人的fingerprint都是空字符串生成的“47DEQpj8HB”，进而所有人的许可文件名都是固定的~/Library/Application Support/abnerworks.Typora/.47DEQpj8HB。
<img width="488" alt="image" src="https://user-images.githubusercontent.com/343491/143678763-bc37ebd8-6d9b-4716-a586-a87b3690a2bc.png">

所以这个bug导致了你们的fingerprint生成了个寂寞。
对了，软件版本1.0.2 (5990)

**Comment by xywf221** [comment]
fuck neo peng

**Comment by abnerlee** [comment]
好的，安全起见我先删了这个 issue 😂
