### ISSUE TITLE
[Feature] Go straight back to the previous folder in the sidebar

### ISSUE THREAD

**Issue by StudentWeis** [typora/typora-issues#4844]
When I write something using Typora, I want to go back to the previous folder sometimes . But now I must use the **Explorer** to do this. So I hope that Typora allows me to go straight back to the previous folder in the **sidebar**. I've wanted this feature for a long time because my Markdown note has many multilevel folders.

Thanks for your awesome Markdown editor. I have bought it this afternoon. ♥

**Comment by abnerlee** [comment]
Sidebar has a "recently used folder" section, so you can go to the previous folder.

Also relates #1154 and duplicate with #2126

**Comment by StudentWeis** [comment]
Sorry, I means that go to "**Upper level folder**", rather than the "**recently used folder**".
