### ISSUE TITLE
Grammatical error on "Start 15 Days Trail" button

### ISSUE THREAD

**Issue by Meekelis** [typora/typora-issues#4845]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
In the new user flow, in the "Activate Typora" screen, one of the buttons says "Start 15 Days Trail" whereas the correct spelling is "Trial".

**To Reproduce**
1. Install Typora 1.0.2 for the first time.
2. Go through the first time user flow until you reach the "Activate Typora" screen.
3. Observe incorrect spelling on the "Start 15 Days Trail" button.

**Expected behavior**
The button shows correct spelling of the world "Trial".

**Screenshots / Screencasts**
![Screenshot](https://i.imgur.com/vCqMEBu.png)

**Sample Markdown File**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Typora Version**
e.g: 1.0.2

**Additional context**
N/A.

**Comment by abnerlee** [comment]
put into #4863
