### ISSUE TITLE
intermittent loss of focus

### ISSUE THREAD

**Issue by qigtang** [typora/typora-issues#4848]
- [x ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
I updated Typora to version 1.0.2 today. And starting to have strange issue. Intermittently Typora will lose focus, and just jump to some random location. I have to use mouse to scroll back to my original location, press to get cursor back to my original location.

I am using Typora for more than one year now. And using it everyday. So I am sure this is a new issue. 

**To Reproduce**
Sorry It would be hard to reproduce this issue, since it will happen randomly.  For me, just use Typora, writing something,
then randomly, out of nowhere, the cursor will be gone, and it will jump to some random location. If I am not careful in 
watching what and where I am typing, I will just typed in a wrong place.

**Expected behavior**

Cursor should not jump 

**Screenshots / Screencasts**

NA

**Sample Markdown File**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10

**Typora Version**
1.0.2

**Additional context**
New behavior after upgrading to version 1.0.2. By the way, I really love Typora. Bought the license immediately when it is available.

**Comment by zacharyw** [comment]
This seems to be related to auto save. If I disable autosave, it stops happening. Something about the auto save features causes the editor to lose focus.

**Comment by abnerlee** [comment]
Could you please try version v1.6? v1.0.2 is too old.

**Comment by qigtang** [comment]
Tested with version 1.6.7. seems fixed.  

My usage of Typora is a little bit special. I have a file server, running Samba/Linux. The client running Typora accesses markdown notes via file share is a windows machine. I suspect the previous bug might be triggered by date clock difference of my two machines.  

Thanks for the fix!

**Comment by qigtang** [comment]
Still need to disable autosave feature to get Typora working nicely. Ideally I would like to see autosave only being triggered while I am idle for several seconds, not while I am typing.  Since my files are from a Samba server, the saving itself can be time consuming, like several seconds. the current AutoSave seems can happen while I am typing, causing the whole program to freeze. 

Anyway, not a big issue. Since there is a star indicator after the file name when the document is changed. I can still disable autosave, and remember to save the document before shutting down computer.

**Comment by zacharyw** [comment]
> Could you please try version v1.6? v1.0.2 is too old.

I was having this issue on the latest version, 1.6.7. It also happens if you create a new file and try to rename it, after typing a few letters, it just saves the file and you lose focus.
