### ISSUE TITLE
Will Typora be available on the Microsoft Store or other app stores?

### ISSUE THREAD

**Issue by SGPublic** [typora/typora-issues#4849]
Congratulations on the release of Typora 1.0 official version, I am very willing to pay for the official version, but I prefer to be able to put it on the Microsoft Store or other app stores, so that I can bind the genuine license to my account, so will Typora be put on the app store in the future? Thanks!

**Comment by abnerlee** [comment]
Currently Microsoft Store allows developers to use their own activation logic in software submitted to MS Store. So even when we upload it to MS Store, it will use the same licensing system. And Typora is cross-platform app, not only bond to MS platform, so we are less likely to bind activation status on a MS account and only available on Windows
