### ISSUE TITLE
About css ".outline-item"

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#485]
Typora default css have like ".md-toc-h1" for ".outline-item"??

**Comment by abnerlee** [comment]
We have it now, for example `.outline-h2>outline-item`

**Comment by MadMaxChow** [comment]
Hi,

It seems unable to implement the same automatic numbering function as ".md-toc".



.outline-content {
    counter-reset: h1toc;
}

.outline-h1 {
    counter-reset: h2toc;
}
.outline-h2 {
    counter-reset: h3toc;
}
.outline-h3 {
    counter-reset: h4toc;
}
.outline-h4 {
    counter-reset: h5toc;
}
.outline-h5 {
    counter-reset: h6toc;
}

.outline-h1:before {
    counter-increment: h1toc;
    content: counter(h1toc);
}
.outline-h2:before {
    counter-increment: h2toc;
    content: counter(h2toc);
}
.outline-h3:before {
    counter-increment: h3toc;
    content: counter(h3toc);
}
.outline-h4:before {
    counter-increment: h4toc;
    content: counter(h4toc);
}
.outline-h5:before {
    counter-increment: h5toc;
    content: counter(h5toc);
}
.outline-h6:before {
    counter-increment: h6toc;
    content: counter(h6toc);
}

**Comment by MadMaxChow** [comment]
It seems unable to implement the same automatic numbering function as ".md-toc".

```
.outline-content {
    counter-reset: h1toc;
}

.outline-h1 {
    counter-reset: h2toc;
}
.outline-h2 {
    counter-reset: h3toc;
}
.outline-h3 {
    counter-reset: h4toc;
}
.outline-h4 {
    counter-reset: h5toc;
}
.outline-h5 {
    counter-reset: h6toc;
}

.outline-h1:before {
    counter-increment: h1toc;
    content: counter(h1toc);
}
.outline-h2:before {
    counter-increment: h2toc;
    content: counter(h2toc);
}
.outline-h3:before {
    counter-increment: h3toc;
    content: counter(h3toc);
}
.outline-h4:before {
    counter-increment: h4toc;
    content: counter(h4toc);
}
.outline-h5:before {
    counter-increment: h5toc;
    content: counter(h5toc);
}
.outline-h6:before {
    counter-increment: h6toc;
    content: counter(h6toc);
}
```

**Comment by abnerlee** [comment]
Please try
```
.outline-h6>.outline-item>.outline-label:before {
   counter-increment: h6toc;
    content: counter(h6toc);
}
```
