### ISSUE TITLE
Mermaid don't draw arrows in links. No background on link label

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [typora/typora-issues#4851]
I used the `mermaid` extension to draw the diagram, however, even though I indicated in the code that the links between blocks should be terminated with an arrow, this one does not.
There is also no background for the link labels, causing them to overlap the link line.

Code:
```mermaid
flowchart TB
	A("START") --> A'[["getLayoutColorsData"]]
	A' --> B[["parseLayoutBefore"]]
	B --> C[/"for each line definition"/]
	C --> D[["buildLineSchema"]]
	D --> E[["parseLineBefore"]]
	E --> F[/"for each elements in line definition"/]
	F --> G[["parseElement"]]
	G --> H{"It is last element?"} -- No --> F
	H --> I[["parseLineAfter"]]
	I --> J{"It is last line?"} -- No --> C
	J --> K(END)
```

The result i have:
![bad flowchart block linking](https://ucarecdn.com/9d78fe81-a108-4a9f-af50-c87e2a8414c0/badflowchartblocklink.png)

I'm using Typora 1.0.2 Licenced Version under Linux MX distro

**Comment by StudentWeis** [comment]
I have the same problem.

**Comment by abnerlee** [comment]
put into #1661
