### ISSUE TITLE
source code mode ui error

### ISSUE THREAD

**Issue by Senfee-Cheng** [typora/typora-issues#4854]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![图片](https://user-images.githubusercontent.com/20067002/143821945-90580f3b-c6f5-40a3-aa6d-980b65d8eeb1.png)
![图片](https://user-images.githubusercontent.com/20067002/143821970-0bfb8f3b-4c2e-4423-9e5a-25b2c1411893.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: win10 64bit

**Typora Version**
e.g:1.0.2

**Additional context**
Click the source code mode, and this button will overlap with the "inactive" button

**Comment by abnerlee** [comment]
should be fixed already
