### ISSUE TITLE
Beta users discount code?

### ISSUE THREAD

**Issue by jkohlin** [typora/typora-issues#4856]
Congratulations on 1.0 🎉
Did you, by any chance, plan on giving beta-testers a discount code 😉

**Comment by abnerlee** [comment]
Sorry, we do not have such plan, since we already provide free services for old beta users in the past time as well 😂

**Comment by luispuerto** [comment]
don't get me wrong… but without beta testers how would you suppose to find the bugs? you were providing service with an incomplete product. A small discount for short period of time for people that was helping you to hone your product would have been a quite nice gesture.

**Comment by davestewart** [comment]
It's great software, and I am happy to pay.

However, it's not entirely gripe-free yet, and I would hope that my financial contribution would go towards getting these issues fixed more quickly than would otherwise have been possible.

**Comment by divbzero** [comment]
Thank you @abnerlee for the well made software. As a beta user of Typora for years I’m also happy to pay. The WYSIWYG interface is great and still rare to see, and its features always felt more than complete for my needs.

**Comment by markmccoid** [comment]
I love Typora and am happy to pay the creators the very fair fee of $14.99!  Purchasing now!

**Comment by walock** [comment]
I just find one typora coupon [in this page](https://svcoupon.com/typora-discount/), about 15% off.

**Comment by audio4funTP** [comment]
Try at here with -$3 OFF https://coupons.ivoicesoft.com/c57424-37673796-typora
