### ISSUE TITLE
Typora 1.0.2 for Windows displays always in front

### ISSUE THREAD

**Issue by wmlongPU** [typora/typora-issues#4859]
I'd like to have the ability to change a new behavior that I encountered after I updated today to Typora version 1.0.2 for Windows. When I open a file in Typora, the Typora window remains always in front of other windows. Those other windows, whether or not they were opened before Typora, display as fully or partially hidden when collocated with the Typora window. 

![Typora-always-in-front](https://user-images.githubusercontent.com/81369122/143932192-bcbce203-dce0-47c9-b1fa-902f76c2b4d4.png)

**Comment by abnerlee** [comment]
Would you click View -> Always on Top from menu bar?
