### ISSUE TITLE
Issues with paypal, can't purchase license

### ISSUE THREAD

**Issue by th3ragex** [typora/typora-issues#4861]
I am trying to buy a license via Paypal from https://store.typora.io

1) With AdBlockPlus and the latest Firefox i was not able to transition from the initial FastSpring dialog to Paypal. 
Note: I was not logged-in in Paypal
After logging in to Paypal the FastSpring dialog was able to transition to Paypal but the callback didn't work. See next point.

2) In Firefox or Chrome without AdBlockPlus Paypal opens, i can login and accept the payment but the callback to the Typora store fails and the purchase process does not complete.
Callback Url: https://store.typora.io/?fscNext=fsc%3Ainvoke%3Asession&fscNext=fsc%3Ainvoke%3Asession
See screenshot:
![image](https://user-images.githubusercontent.com/15040273/144019206-26b4f507-3dc0-481c-8339-b0b6fc00a2b6.png)

Firefox: 94.0.2 (64-bit) (not private mode)
Chrome: 96.0.4664.45 (Official Build) (32-bit)
Windows 10 21H1
Locale: German

I am not sure whether this is something with my setup or an issue with the payment provider / integration. Do you have an idea what else i could try to get this through except using a credit card?

**Comment by abnerlee** [comment]
@th3ragex Hi, could you send us (<hi@typora.io>) your email address? Our distributor wants to contact you for more details

**Comment by th3ragex** [comment]
@abnerlee Done

**Comment by abnerlee** [comment]
It seems being declined by PayPal so we can no nothing about it.

Message from FastSpring:

```
Thank you. The given reason for the failed orders is below:

Image_2021-12-06_12-34-49.png

The only thing we really know is that PayPal is declining the transactions. Unfortunately, we are not provided with any additional information other than this. PayPal's explanation (https://www.paypal.com/us/smarthelp/article/why-did-i-get-api-error-code-10606-ts1368) for the cause of this error is: 

"PayPal can’t use the credit card that’s being used."

The user will need to contact PayPal directly for more information on why the payment could not be accepted. I do apologize for the inconvenience. 
```

**Comment by th3ragex** [comment]
It worked now. 

I am not sure why, there may be two reasons:

1) I selected a credit card in Paypal instead of a debit card (direct debit). 
2) No comment:
![image](https://user-images.githubusercontent.com/15040273/144995005-adaced92-62ce-42c1-aa2e-d121e77d0ffd.png)
