### ISSUE TITLE
Typo on launch page

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#4863]
I think that's a typo on the getting started wizard for themes.  It says, "Explorer themes".  I think it should be "Explore themes"?

**Comment by coinzdude** [comment]
![image](https://user-images.githubusercontent.com/58857646/144093209-e0e07f68-b080-4997-81a8-73d315b92df8.png)

**Comment by silvaDominic** [comment]
There is another typo during startup for trial members

![image](https://user-images.githubusercontent.com/12387334/144103146-e5e04d90-aba3-43cb-a805-c33d8e263fa0.png)

"Your **trail** will be expired in 2 days" Clearly "trail" --> "trial"

Also, the grammar is incorrect even the typo is fixed. Proper would be something like:

"Your trial will expire in X days."

**Comment by fgimian** [comment]
I can confirm this on my end too with the latest version.  These sorts of grammatical errors are really obvious and jarring to us native English speakers.

**Comment by abnerlee** [comment]
fixed in 1.2.3
