### ISSUE TITLE
[Feature] - Workflow for pasting image to get name and alt-text

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#4865]
When pasting an image into Typora, could you allow a setting to prompt the user prior to saving for a file name to be used, without the extension, as well as an opportunity to provide the alt-text?

Currently, I must paste the image, find the file in the file system, rename the file, update typora link, then separately type in the alt-text which is a bit more tedious than would be needed with the above.

**Comment by abnerlee** [comment]
duplicated with #4636
