### ISSUE TITLE
landing page for typora store, missing internal resources, bad references

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#4866]
From https://store.typora.io/

there are a few errors caught by errors notifier:

`File not found: https://seal.digicert.com/seals/cascade/seal.min.js

File not found: https://cdn.pendo.io/agent/static/c2a2939b-ebf8-4422-7cb7-04bcbe8c8865/pendo.js

File not found: https://cdn.sift.com/s.js`

![image](https://user-images.githubusercontent.com/58857646/144094325-bef94de3-aa8b-43bc-845e-67aa4fa323a7.png)

**Comment by abnerlee** [comment]
relates #4861

May caused by AdBlock

**Comment by abnerlee** [comment]
@coinzdude Sorry, but could you send an email to hi@typora.io so we can know your mail address and involve you in with FastSpring team about the checkout js error?
