### ISSUE TITLE
Incorrect trial period expiration

### ISSUE THREAD

**Issue by silvaDominic** [typora/typora-issues#4868]
- [X] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css. **(Not related)**

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
After upgrading to 1.0.X on 11/29/21 I opted for the free 15 day trial. When opening the application the next day (11/30/21) I was informed I had 2 days remaining.

**To Reproduce**
1. Upgrade to 1.0
2. Opt in for 15 day trial
3. Close program
4. Wait 24 hours+
5. Reopen application

**Expected behavior**
Expected (15 - n days since trial start)  days remaining on trial

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/12387334/144109161-b3c59875-383b-4cd6-9e42-0e09c86e8e8e.png)

OS: Windows 10 64bit

**Typora Version**
1.0.2

**Comment by abnerlee** [comment]
put into #4863

**Comment by abnerlee** [comment]
should be fixed
