### ISSUE TITLE
Save function does not work for new file in Win64 (version 0.9.23)

### ISSUE THREAD

**Issue by xunningy** [typora/typora-issues#487]
Open typora and type in some words and then "save" or "save as", no dialog is popped up.
It doesn't matter it is fired from pull-down menu or short-cut keys.
For **named** or **opened** file, it seems OK.

**Comment by abnerlee** [comment]
What's your Windows version, in my Windows10 it works well.

**Comment by mschroen** [comment]
It works also well here under Win7 64 SP1.

**Comment by xunningy** [comment]
My windows version is Windows 7 Enterprise (Build 7601: Service Pack 1)

**Comment by abnerlee** [comment]
@xunningy After you click save, could you press F12, and paste the log/errors from web console?

**Comment by xunningy** [comment]
Here is what I got:

> file:///C:/Program%20Files/Typora/resources/app/app/window/frame.js Failed to load resourcesend @ frame.js:3
frame.js:5 getContent
frame.js:8 putHTML: 65.091ms
frame.js:1 bindJumplist ok
file:///C:/Users/usxuyue/AppData/Roaming/Typora/themes/base.user.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/usxuyue/AppData/Roaming/Typora/themes/pixyll.user.css Failed to load resource: net::ERR_FILE_NOT_FOUND
frame.js:17 codemirror mode is loaded
frame.js:11 diagram dependents are loaded
frame.js:5 setContent
C:\Program Files\Typora\resources\electron.asar\renderer\api\remote.js:217 Uncaught Error: Could not call remote function 'getPath'. Check that the function signature is correct. Underlying error: Failed to get 'documents' path
Error: Could not call remote function 'getPath'. Check that the function signature is correct. Underlying error: Failed to get 'documents' path
    at callFunction (C:\Program Files\Typora\resources\electron.asar\browser\rpc-server.js:228:11)
    at EventEmitter.<anonymous> (C:\Program Files\Typora\resources\electron.asar\browser\rpc-server.js:316:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Program Files\Typora\resources\electron.asar\browser\api\web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by abnerlee** [comment]
should be fixed already
