### ISSUE TITLE
2 or more arrows between 2 mermaid flowchart elements render incorrectly

### ISSUE THREAD

**Issue by ainsleymcgrath** [typora/typora-issues#4870]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
In a mermaid `flowchart` multiple arrows going from one element to another do not render their labels properly.
i.e. If `A` has 2 labeled arrows pointing to `B`, the second of the 2 arrows will render incorrectly.

**To Reproduce**
1. Open a blank document
2. Paste this markdown
~~~
```mermaid
flowchart TD
  start((Lake));
  middle[Estuary];
  
  
  start -->|A river| middle;
  start -->|Another river| middle;
  start -->|A third river| middle;
  
  middle --> Ocean;
```
~~~

**Expected behavior**
A diagram that looks like this (via [mermaid.live](http://mermaid.live))
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25474239/144295403-0e986565-1cef-43b8-b47d-31a2d9432864.png">

**Screenshots / Screencasts**
This is what gets rendered instead
<img width="382" alt="image" src="https://user-images.githubusercontent.com/25474239/144295272-e3a2de91-5b9a-4971-a8de-0b8032e15191.png">
Notice that the labels for the second and third arrows seem to stack up on top of one another in the top left corner.

**Sample Markdown File**
[see Expected Behavior section]

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6

**Typora Version**
1.0.2

**Additional context**
This may be related somewhat to #4851.

**Comment by abnerlee** [comment]
put into #1661

**Comment by ainsleymcgrath** [comment]
> put into #1661

thanks!
