### ISSUE TITLE
Activation Agent Issues

### ISSUE THREAD

**Issue by liaoqing1999** [typora/typora-issues#4872]
I activated typora on a machine that had to use a proxy. I make sure I can access https://www.typora.io/ on my browser, but the error message "Failed to access the license server. Please check your network or try gain later." still appears when I activate. Can Typora use the built-in proxy of the computer or manually set the proxy?

**Comment by abnerlee** [comment]
Does https://support.typora.io/activation/#error-message-failed-to-access-the-license-server-please-check-your-network-or-try-gain-later help? Which requires you to remove HTTP_PROXY and HTTPS_PROXY from your system environment variables.

For proxy, Typora uses system proxy, and can also be configured independently (on Windows / Linux) (refer https://www.sxj.xyz/set-proxy-for-typora.html)

**Comment by levee223** [comment]
I have the same issue. Our corporation has no internet access without a proxy. The following has been tried. [1] With/Without --proxy-server flag. [2] With/Without HTTP_PROXY and HTTPS_PROXY. Is there any other help?

**Comment by liaoqing1999** [comment]
I found my problem, my company's firewall software blocked the typora activation request.

**Comment by even0306** [comment]
i am the same as them

**Comment by happy2h** [comment]
the same

**Comment by gcsxdu** [comment]
I have to use a VPN to visit store.typora.io. I tried all ways you mentioned, but it didn't work. The error message "Failed to access the license server. Please check your network or try gain later." still appears when I activate. Can Typora make the activation more easy and convenient？ Sorry, I know very little about network proxy.

**Comment by levee223** [comment]
@abnerlee 
I'm not a Chinese user, but I cannot activate Typora 1.0.3 due to a proxy issue. In Typora for Windows, the Editor part (Electron renderer process) uses system proxy, but Activator and Updater seems to ignore system proxy.

**Comment by abnerlee** [comment]
(For Chinese User) 如果你是中国国内用户，请更新或下载 1.0.3，然后打开 偏好设置 → 通用 → Typora 服务使用国内服务器

[Screen Shot 2021-12-03 at 23.11.11](https://support.typora.io/media/activation/Screen%20Shot%202021-12-03%20at%2023.11.11.png)

**Comment by LogoiLab** [comment]
This paid model is hot trash. Requires internet, and has the gall to ask for "Usage Info". This is not the open source way. You will not be getting my money. And you have lost a loyal user.

**Comment by vksir** [comment]
In my environment, I could do like this:

**Comment by vksir** [comment]
In my enviroment, I can do like this:

```
curl https://www.google.com -x http:example.com -k
```

and I can't do like this:

```
curl https://www.google.com -x http:example.com
```

To use my proxy, it's unable to verify certificate.

And, this is also unuseful:

```
./Typora.exe --proxy-server=http://example.com
```

It may be necessary to add an option to prevent typora from verifying the certificate

**Comment by MarinnaCole** [comment]
The activation agent is completely in-appropriate. Not only the activation server won't be accepted by many modern day IT department, but also the license has to be repeatedly verified every time the application is opened. Would the developers really care about piracy that much that they would rather lose a big chuck of potential industrial users? This is Markdown editor for Christ sake...

**Comment by kyet** [comment]
Should provide one of the below,
* insecure option (like curl -k)
* set path to self-signed certificate
* use system's certificate store

**Comment by 0xced** [comment]
One hour and counting trying to activate my license behind a proxy. I have tried basically every possible combination of options (`--proxy-server=address:port`, `--proxy-server=address`, `--proxy-pac-url=url`, `--no-proxy-server`) but I still get errors.

Thanks to @kyet I realized I could look at the `typora.log` file at `%AppData%\Typora\typora.log` and here's the recurring error I get:
```
INFO 13.01.2022, 18:28:57  handle addLicense
INFO 13.01.2022, 18:28:57  request https://store.typora.io/api/client/activate
Error: getaddrinfo ENOTFOUND 80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
ERROR 13.01.2022, 18:28:59  Error: getaddrinfo ENOTFOUND 80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

I guess I could read the 79 messages on https://github.com/nodejs/node/issues/5436 to try to understand if there's a way around this error but I'm not sure I want to!

Now I strongly regret having updated from the beta version. ☹

Given there are so many users reporting issues to activate their license you should really consider an offline mechanism.

@kyet You may try to set the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0`. I got this to work in another node-based app (maybe it was npm) in order to accept untrusted certificate (which is what often happens in enterprise networks that intercept https traffic).

**Comment by kyet** [comment]
@0xced Many Thanks! NODE_TLS_REJECT_UNAUTHORIZED trick works!
It should be added to FAQ.

**Comment by 0xced** [comment]
What eventually worked for me was to remove all proxy-related environment variables before launching Typora.

```cmd
set HTTP_PROXY=
set HTTPS_PROXY=
set NO_PROXY=
Typora.exe
```

Then I was finally able to activate Typora!

**Comment by nayabin** [comment]
Same on Windows. All ways here didn't work for me. I am a huge fan of Typora but, I now regret buying it.

**Comment by abnerlee** [comment]
Please try 1.1.0-dev (https://typora.io/releases/dev) and check https://support.typora.io/Offline-Activation/

**Comment by nayabin** [comment]
> Please try 1.1.0-dev (https://typora.io/releases/dev) and check https://support.typora.io/Offline-Activation/

Great! Thank you for your quick support.

**Comment by kai2nenobu** [comment]
Offline activation has succeeded in my proxy network as below.

![image](https://user-images.githubusercontent.com/810042/154179827-c09b6f6c-278b-41f2-8d9a-f466d1827a8b.png)

However, I cannot see my license in <https://store.typora.io/my>.

![image](https://user-images.githubusercontent.com/810042/154179246-b6a080eb-64a2-4781-8914-5128c642ded6.png)

How can I check my offline activations?

**Comment by abnerlee** [comment]
@kai2nenobu could you send us (hi@typora.io) the email or license code you use?

**Comment by abnerlee** [comment]
close since offline activation is now supported
