### ISSUE TITLE
Outdent and indent break continual list items

### ISSUE THREAD

**Issue by tifish** [typora/typora-issues#4878]
**Describe the bug**
Outdent and indent break continual list items.

**To Reproduce**
![OutdentAndIndentBreakList](https://user-images.githubusercontent.com/16101136/144551529-602f9782-3c75-4d6c-8f74-f671b4a52b26.gif)

**Expected behavior**
![OutdentAndIndentKeepList](https://user-images.githubusercontent.com/16101136/144551558-ab8d3bdc-a5fb-48af-a45d-283af9a2d411.gif)

**Desktop (please complete the following information):**
- OS: Windows 11 64bit

**Typora Version**
1.0.2

**Comment by abnerlee** [comment]
Use undo/redo for this case. Or backspace + return, or #4829

when user input "- ", we assume he wants to make a new list.
