### ISSUE TITLE
[Feature] Better cursor movement with keyboard

### ISSUE THREAD

**Issue by jaekyeom** [typora/typora-issues#4879]
One of the things that make Typora great is its seamless switching between viewing and editing markdown.

However, when it comes to movement in documents, using arrow keys for navigating can be painful because every time the cursor encounters a rendered markdown component (e.g., math block or links) Typora expands it for editing.
Thus, at the moment, I mostly use my mouse for movement in documents.

Although there are Page up and Page down keys, they make large jumps and do not move the cursor.

One way to improve it might be supporting a modifier key that disables the expansion for editing while it is pressed.
Currently, I can use Shift + arrow keys as a workaround, but it's distracting as it shows the selection.

Hotkeys for toggling the read-only mode (#710) could be another possibility (as long as the user can move the cursor in the read-only mode).

Or, you might disable the expansion during full-speed cursor movement with arrow keys or add support for a customizable delay before the expansion.

Thank you.

**Comment by abnerlee** [comment]
relates or duplicates #443 #1313 #710

And currently, if you move arrow key very fast, it will not expand markdown source, already.

**Comment by jaekyeom** [comment]
@abnerlee Weird, I'm using Typora v1.0.4 (5994) on macOS 12.0.1 with minimal key repeat delay, and if I keep pressing the up or down arrow keys, Typora does expand the markdown source at every encounter.

**Comment by yujiewu66** [comment]
I have the same issue here. See #6104. When I view my math notes there are tons of equations and I use pageup/page down key a lot. This moves up a page accurately and I can stop to skim through that page's content for two seconds. I like it that the caret is moving as the pages moves. But it often will hit an equation (I have a lot of equations in latex-display mode (not inline) and the original latex codes are a bit long (attached in a picture below e.g.). Once the caret hits these equations the orignal latex codes gets rendered and blows up and takes over my screen space. This is not I wanted when I want to skim through my notes.  

In my Windows 11, when I move the up arrow very fast, indeed it doesn't render the original codes. But it doesn't allow me to stop at a previous/next page accurately and skim through my notes. It's kind of annoying when it 's always moving and most laptop/monitor screens are not even 120hz. You also have to move the caret really fast to prevent it from rendering. But I would like to stop and look at my notes in the new page.

A read-only mode that uses the standard shortcut for webpages to turn pages, i.e. space/shift+space is an ideal solution, and I hope the carets moves along the pages too. Please also make a shorcut to turn/off on the read-only mode.

Again thank you for making and maintaining Typora! I not only paid for the app but also encouraged my friends in Math to try Typora themselves too. It could still be better.

![image](https://github.com/user-attachments/assets/3ce58715-3161-4548-98c3-c004bc6036b6)
