### ISSUE TITLE
Enhancement suggestion: Theme per file

### ISSUE THREAD

**Issue by kadmonj** [typora/typora-issues#488]
Add an option to choose the theme per file base. In a similar way to how the image directory is now set.

This will allow to have different themes to different kinds of notes/documents.

**Comment by abnerlee** [comment]
Seems no enough merits for supporting this

**Comment by leonardwong** [comment]
Hi I would like to have this feature added. Thank you for your consideration.

**Comment by shoesforindustry** [comment]
I think it would be a good idea to be able to set a default theme for a specific document. For some documents I want to use one theme, but then use another theme for other documents. Perhaps it could be set using YAML front matter?

```yaml
theme: Ash
```
Of course this would be overridden if the user selected a different theme, but would use the suggested theme re-opening.

**Comment by sst2010** [comment]
It would be great to have this feature. It is very much required to be able to work on multiple files with different contexts.

**Comment by JunaidQadirB** [comment]
For that, I think Typora might need to adopt a Typora-related format where it can store the document metadata along with the document. 

I would suggest Typora, in that case, should allow the user to create a `Typora Document` with a new extension say `.tmd` (Typora Markdown) which either as @shoesforindustry suggested, uses a YML-like front matter or it will be an archive like the Word docx.

The metadata could hold information like window geometry, undo history, and most importantly the theme.

**Comment by shaack** [comment]
For me, it would be also OK, to set the theme based on the file ending. Per example `.md` has a different theme than `.pmd` or `.xmd`.
