### ISSUE TITLE
Clicking on a heading marks the file as changed

### ISSUE THREAD

**Issue by jeff9315** [typora/typora-issues#4881]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
This also appeared in several recent Beta versions but I didn't report it at the time. 

When I click on an heading (or at least H1, H2, H3), it marks the file as changed even if I don't change the heading.
This only occurs when Autosave is turned OFF

**To Reproduce**
1. Make sure Autosave is turned OFF.
2. Go to any H1 or H2
2. Click on it.'
3. Look at he * at the top next to the filename and see that it's there (indicating that the file has changed).

**Expected behavior**
The file should NOT be marked as changed.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit.

**Typora Version**
e.g: 1.03 but also in recent Beta versions

**Additional context**

**Comment by abnerlee** [comment]
duplicated with #2354
