### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by jeff9315** [typora/typora-issues#4882]
### Add Bug Report to Help menu

It's difficult to get to this issues page. In the ```Help``` menu, there should be an new option for ```Report a Bug```. Possibly combine that with ```Feedback``` and change ```Feedback``` to ```Feedback by Email```.

**Comment by abnerlee** [comment]
I think feedback can already cover the "report bug" part. GitHub issue is not the only and official way for bug reports to Typora.

**Comment by jeff9315** [comment]
Yes, but then you can't search for other reports to see if something comes close.
