### ISSUE TITLE
Asterisk cannot be auto paired while using Sogou IME

### ISSUE THREAD

**Issue by zsybh1** [typora/typora-issues#4884]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Asterisk cannot be auto paired while using Sogou Chinese IME

**Screencasts**
![GIF 2021-12-4 22-35-27](https://user-images.githubusercontent.com/57790133/144713903-73945148-5538-42e0-850f-475bdeca8123.gif)

Besides, the asterisk can be auto paired in older version such as 0.10.11
![GIF 2021-12-4 22-37-03](https://user-images.githubusercontent.com/57790133/144713935-c007a33a-1f44-45a4-8a75-b6b41ab3e35a.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]

**Typora Version**
0.11.2 to 1.0.3

**Comment by abnerlee** [comment]
It works with Microsoft Chinese IME in my test

**Comment by zsybh1** [comment]
> It works with Microsoft Chinese IME in my test

Do you test in Chinese input mode? Actually it works in English input mode with Chinese IME, but not in Chinese input mode

**Comment by abnerlee** [comment]
Yes, I tested Chinese input mode

**Comment by zsybh1** [comment]
> It works with Microsoft Chinese IME in my test

Well, Microsoft Chinese IME do work on my PC, it's my friend that told me it can't work. But Sogou IME is still not working.

**Comment by abnerlee** [comment]
It is working in my test under Sougo IME v11.9
