### ISSUE TITLE
序列码激活软件失败，连接不上服务器

### ISSUE THREAD

**Issue by Xueyu334** [typora/typora-issues#4886]
我购买了正版的服务，但是在激活软件使用的时候，无法正常激活，显示连接不上服务器，但是我的网络并没有问题
![image](https://user-images.githubusercontent.com/49145958/144717333-bd573dd0-6463-4ad5-9a9f-5856fdf60dae.png)

**Comment by qq88902012** [comment]
官网下载1.0.3版本，设置里勾选“Typora服务器--使用国内服务器”

**Comment by Xueyu334** [comment]
很感谢您的及时回复 我已经解决了问题  希望软件越来越好!

从 Windows 版邮件发送

发件人: qq88902012
发送时间: 2021年12月5日 1:25
收件人: typora/typora-issues
抄送: Xueyu; Author
主题: Re: [typora/typora-issues] 序列码激活软件失败，连接不上服务器 (Issue #4886)

官网下载1.0.3版本，设置里勾选“Typora服务器--使用国内服务器”

**Comment by Innocence** [comment]
> 官网下载1.0.3版本，设置里勾选“Typora服务器--使用国内服务器”

大陆连官网都上不了吧

**Comment by c17abab** [comment]
Updated the new version(1.0.3) and still cannot be activated.
