### ISSUE TITLE
[Feature] Support for Textbundle format

### ISSUE THREAD

**Issue by 15040941306** [typora/typora-issues#4887]
Could Typora be able to open and edit documents in textbundle format directly?

Markdown is certainly a very good document format, but its plain text features make it possible to either use a drawing bed or store pictures in separate folders. The Textbundle format essentially packages the Assets folder and Markdown files into a single file, so that when the overall notes are taken, the picture is always accompanied by the Markdown document, the user no longer has to think about the picture, the folder will appear cleaner and cleaner.

At present, Ulysses, Craft, Zettlr, MWeb and other Markdown editors have supported the format, and support editors are growing, I hope Typora can also support the format.

Although such a request is a bit presumptuous, I hope the developer can consider my suggestion.

**Comment by abnerlee** [comment]
duplicated
