### ISSUE TITLE
Buttons in Update Screen not responding

### ISSUE THREAD

**Issue by asherhe** [typora/typora-issues#4888]
Whenever the update screen pops up asking me to update Typora, the buttons at the bottom of the window do not respond to clicks (not just the "Download Update" button).

![Update window](https://user-images.githubusercontent.com/35799436/144728861-1e9a12da-ddd6-48e1-8bc4-66293198a6b0.png)

**To Reproduce**
1. In the top menu, go to `Help > Check Updates`
2. The update window will appear. Press any of the buttons at the bottom.

I am on Typora version 0.11.0, on Windows 10 64-bit

**Comment by abnerlee** [comment]
#4598
