### ISSUE TITLE
Highlight error: Using code and list, then maybe the parser cannot exit code mode successfully

### ISSUE THREAD

**Issue by persistz** [typora/typora-issues#489]
I wrote a lump of words mixed Chinese characters and English code using list, but after the code segment, behind Chinese chars will be marked as red in dev mode, also the No. of the list will be marked as green or italic.
The screen shot shown as below:
![typora_bug](https://cloud.githubusercontent.com/assets/12887616/21710973/0c95034a-d427-11e6-98e2-b7ea216571b9.png)

**Comment by abnerlee** [comment]
Should be fixed in new release.
