### ISSUE TITLE
An ERROR occurs when you try to type [``]()[``]()

### ISSUE THREAD

**Issue by hamburgerdog** [typora/typora-issues#4892]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
An ERROR occurs when you try to type `[``]()[``]()` in Real-time preview mode in Typora 

**To Reproduce**

Just view the attachment or
1. Go to [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)
2. Copy the first paragraph of text. 
From **The \<picture\>...** to **...for different display/device scenarios.**
3. Paste it into Typora and try typing or deleting

**Expected behavior**
The text in the middle can be deleted or typed normally

**Sample Markdown File**
See attachment [parsing]([An ERROR.md](https://github.com/typora/typora-issues/files/7656074/An.ERROR.md))

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur 11.5.2 Apple M1]

**Typora Version**
1.0.2

**Additional context**
I know that when copying some markdown with HTML tags, Typora will automatically remove them, just like `<picture> / <img>`, this is when the above problem may occur. I think it might have something to do with Markdown's syntax parsing, but I'd still like to be able to type or delete normally in this case. Of course, if it's not a bug, just close the issue! 😂 

Thank you especially for checking out this issue! 😄  
Typora works great! Glad to see you guys are starting to charge, hope this app gets better and better!

**Comment by abnerlee** [comment]
the caret jumping when editing should be fixed in 1.1, parsing rule related is recorded in #2606 (multiple `[]` and `()`)
