### ISSUE TITLE
[Feature] Support collapse and expand at source mode

### ISSUE THREAD

**Issue by Alomerry** [typora/typora-issues#4893]
## What

请问是否可以支持以下：

- `source mode` 时按照大纲级别对内容进行折叠
- `source mode` 依旧展示大纲，方便跳转

## Why

当文件内容过多时定位内容困难

## Reference

类似于 vscode 编辑 markdown 时

https://user-images.githubusercontent.com/34118544/144762594-2df99349-ed82-4574-a3d9-342dd0fe5730.mov

**Comment by abnerlee** [comment]
duplicated with #499
