### ISSUE TITLE
Auto-pair for ticks and backticks doesn't work

### ISSUE THREAD

**Issue by davidjosefson** [typora/typora-issues#4895]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Tried with and without the two "Auto Pair"-checkboxes in the settings
- [x] Searched http://support.typora.io/

**Describe the bug**
When trying to surround selected text with ticks or backticks the text gets replaced by one tick/backtick instead of surrounding the text.

**To Reproduce**
Select text in the text editor, insert a tick or a backtick with your keyboard

**Expected behavior**
The selected text should be surrounded by ticks/backticks, just like it is when inserting quotations or parenthesis.

**Desktop:**
OS: MacOS BigSur 11.6.1 (20G224)
Typora Version: 1.0.4 (5994), but has not worked previously either.

**Comment by abnerlee** [comment]
enable it in preferences panel.

**Comment by davidjosefson** [comment]
That's what I'm pointing out - it doesn't work with ticks and backticks even if the settings are enabled. It doesn't behave as the same as it does with normal quotes or parenthesis. See gif:

![autopairnotworking](https://user-images.githubusercontent.com/7073402/144985975-05de79ec-a9dd-4bd9-a15f-63a36728adac.gif)

**Comment by davidjosefson** [comment]
I'm using Swedish keyboard layout on mac. Have tried killing Typora and starting it again, no difference.
![Keyboard 2022-08-31 16-23-57](https://user-images.githubusercontent.com/7073402/187702736-dcfcb5ca-346a-4cf1-aca8-bed64077a8d1.png)
