### ISSUE TITLE
Check for updates shows an alert

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#4896]
Using Typora Version 1.0.3 (5993) and click on check for updates results in an alert: 

*Auto-update not configured*

For security reasons, updates to Typora need to be served over HTTPS and/or signed with an EdDSA key. See https://sparkle-project.org/documentation/ for more information.

**Comment by rdebeasi** [comment]
I am also encountering this issue. Here's a screenshot:
<img width="372" alt="Screen Shot 2021-12-07 at 1 45 57 PM" src="https://user-images.githubusercontent.com/1299370/145088096-469261c4-e94a-4dda-81ab-ed470850c173.png">

I'm on a corporate network, but I didn't encounter issues with previous updates.

**Comment by Acidham** [comment]
Meanwhile, I downloaded version 1.0.4 and replaced 1.0.3...works

**Comment by abnerlee** [comment]
Please redownload the 1.0.4 since 1.0.3 has issues on the auto-update
