### ISSUE TITLE
Custom command upload fails

### ISSUE THREAD

**Issue by joeledwardson** [typora/typora-issues#4898]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When using `picgo` as a custom command:
`"/home/joel/.nvm/versions/node/v17.2.0/bin/picgo" upload`
I get a `Validation Failed` error: 
`/usr/bin/env: ‘node’: No such file or directory`.
(see screenshots at bottom)

I try copying this exact command into terminal and it works fine (I have tried with and without quotations on the `picgo` command)
```bash
$ "/home/joel/.nvm/versions/node/v17.2.0/bin/picgo" upload "/tmp/typora-icon2.png" "/tmp/typora-icon.png"
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading... Current uploader is [smms]
[PicGo SUCCESS]: 
https://s2.loli.net/2021/12/06/bZTc8yYfdKvq2xe.png
https://s2.loli.net/2021/12/06/7vSCpfPkzscNFmy.png
```

**Docs**
Within the [export](https://support.typora.io/Export/) section of the docs, there is a section that looks like the same bug but this is a different section to the relevant [upload image](https://support.typora.io/Upload-Image) section.

> Env: node: No such file or directory
If you use custom command like node xxx, please make sure node is in your system PATH. Or you can specify the node command with its full path. You can find your node path by input which node or where node in your shell to locate the node bin location.

**Screenshots / Screencasts**
Image Upload Setting
![image](https://user-images.githubusercontent.com/25906558/144877334-367de985-e0cd-4484-9ca6-7b2751a2c01d.png)

Screenshot of error
![image](https://user-images.githubusercontent.com/25906558/144876710-072721cd-da6e-46c4-9cc0-fe9b3250b5f9.png)

**Desktop**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Typora Version**
v1.0.3

**Comment by abnerlee** [comment]
Your terminal may use zsh, fish, etc with their own configs and environments. And if you use `nvs`, then there's no `node` into your system ENV, `nvs use xxx` may add it in current session.

So you should use `${nodePath} ${picgoPath} update` to update image

**Comment by joeledwardson** [comment]
Hi @abnerlee,
I'm using `nvm`, I updated the custom script to `/home/joel/.nvm/versions/node/v16.13.1/bin/node /home/joel/.nvm/versions/node/v16.13.1/bin/picgo upload` as you suggested and it works fine - thanks. 

If the `command` option expects the first argument to be a node binary in the format you've described `${nodePath} ${picgoPath} update` (and if not will try to find one), should this be added to the docs? I can't see anything in the docs that explains this

**Comment by danielhu19** [comment]
I'm using nvm, I updated the custom script to
`/home/danielhu/.nvm/versions/node/v18.10.0/bin/node /home/danielhu/.nvm/versions/node/v18.10.0/bin/picgo u`
as you suggested above.
And I can upload the pic from my clipboard (just 'u' as argument), but it doesn't work well in typora.
Here is my screenshot:
![image](https://user-images.githubusercontent.com/86143910/193510675-cdcc905f-ebb5-475d-be2f-4fd5458dc6a5.png)
I copied the command terminal like this:
![image](https://user-images.githubusercontent.com/86143910/193510630-70838039-ee04-4ce2-93fb-99d644dd4bf0.png)
