### ISSUE TITLE
购买失败

### ISSUE THREAD

**Issue by VWWL** [typora/typora-issues#4899]
已付款未获得激活码
### Ali的信息：
1. 商品说明：00000009370007508660
2. 订单号：2021120722001315631422800721
3. 商家订单号： 093704998359
4. 创建时间：2021-12-07 10:52:05
5. 支付时间：2021-12-07 10:52:10

### Typora填写信息：
1. 购买邮箱：wangweili457@gmail.com
2. 姓：Wang
3. 名：Neil
4. 电话：18601600861

**Comment by abnerlee** [comment]
Hi

可以把信息往 https://fastspring.com/consumer-support-form/ 上面填一下吗？
