### ISSUE TITLE
Bug in the image export feature

### ISSUE THREAD

**Issue by micaelbatista** [typora/typora-issues#490]
I tried to export the md file to an image. I couldn't do it to jpg, it would give the following error: "frame.js:25 Error: Could not call remote function 'toJPEG'. Check that the function signature is correct. Underlying error: Insufficient number of arguments."
When I tried to export to png, the image had a small width and didn't export the whole file.
*Typora version*: 0.9.23

[Output PNG](https://cloud.githubusercontent.com/assets/6781008/21743795/95a6b7ca-d501-11e6-9e03-40dd88c59b31.png)
[Markdown file](https://github.com/typora/typora-issues/files/691623/DAD.s.summary2.txt)

**Comment by abnerlee** [comment]
fixed in new release
