### ISSUE TITLE
text scaled down and disregards font size settings when exporting image

### ISSUE THREAD

**Issue by emshupisim** [typora/typora-issues#4901]
When I export my text as an image with small width, I expect the text to stay in the same font size, similar to when I resize the  window: 
![Snipaste_2021-12-06_23-41-33](https://user-images.githubusercontent.com/43711184/144987438-acfb6417-681d-422c-bb39-3d192856b5c8.png)

However, what I'm getting now is an image scaled down to the desired width. 
![default](https://user-images.githubusercontent.com/43711184/144987435-a4da97d5-44c0-4796-8578-d488d8172673.png)

Also, it completely disregards any font size settings. Image below had font size=80, and it exports the exact same image as above (default settings) 
![12312312](https://user-images.githubusercontent.com/43711184/144987903-81a183b6-652a-44d0-9c40-473827f9467f.png)

**Comment by abnerlee** [comment]
should be fixed in 1.1

**Comment by abnerlee** [comment]
relates #2422
