### ISSUE TITLE
[Feature] Disappointment and hopes for Typora

### ISSUE THREAD

**Issue by ScribbleGhost** [typora/typora-issues#4902]
I will be saying goodbye to Typora today. Just thought I would stop by and take time to explain why. I really hope this comes out as constructive criticism and not just a rant. 😊

## Activation requires an internet connection.

First of all, I don't want to be forced to have an internet connection to activate. It would make sense if the software actually required internet to work, but the fact is, it is just a text editor. It should not need internet at all except for updating which can be solved by downloading the latest version.

I use Typora a lot in virtual machines because I work with OS deployments. Many of these machines are not connected to the internet, or at least they are not connected to the internet at the point in time where I need to use or install/activate Typora. If I cannot activate the software offline I cannot deploy Typora along with other software on the computer.

Sublime Text 3/4 is a perfect example of how this could be solved. It does not require an internet connection.

## Spelling

Spelling has always been extremely poor in Typora. The available dictionaries are limited to a few seemingly random dictionaries limited to about 30 languages. My native language is not one of them.
The official response on may of the Github issues (which sounds almost like a disclaimer) has been to use Windows 10 native spelling functionality, but everyone knows this is completely broken and there is no live example where this works. Nor does it work with Typora. This means that in practice, I do not have spell checking in Typora.
The built-in dictionaries in Typora that do work are rather primitive. They do correct misspelt words, but not sentences, grammar or more complicated common mistakes.

Perhaps, if I could at least get a basic dictionary added to Typora I could live with it, but this has been tried by several users [without success](https://github.com/typora/typora-issues/issues/457). @abnerlee keeps closing these issues and I get the feeling that he just does not care about spelling.

I strongly believe that a powerful spell checker, although perhaps hard to implement would take Typora to a much more competitive level and justify the price. At the moment there are many alternatives that provide way better spelling than Typora. Why have spelling at all if it is just limited and mediocre? In my opinion one could just remove it. I have been copy-pasting text from MS word anyway 😂

## Media and image management

One of the great things about Typora is that unlike many other markdown editors it does not use proprietary file formats and it keeps the added images with relative or absolute paths. This is beautiful! It enhances flexibility. I do not have to export all my documents just to convert or upload them to a mkdocs or jekyll site. I can do parsing and file manipulation etc. All in all, fantastic! Hands down, my utmost respect!

However, once you delete some images from a document they will still be available in the file system. This means we have to remember to manually delete the images from the file location.

Also renaming images is not really possible unless you manually update every document where the image is added.

I am not completely sure what the best solution is here, but I am sure there has to be some way to go about it.

The point is, it prevents me from using Typora large scale. Making hundreds of documents is quite risky if you later decide you have to change an image that is added to, say 38 of those documents...

## Why I started using Typorain in the first place

I completely fell in love with Dropbox paper because of the ability to "just write", "drag and drop" pictures while still keeping the document on one page (unlike MS Word). In addition, I loved the fact that they adhered to markdown standards and not a proprietary format. The only drawback was that I had already paid for a OneDrive/MS subscription and I would rather not have to pay for two subscriptions. That was when I started to look for software alternatives.

Typora did an excellent job, although I did not have the luxury of using Grammarly or Chromes built-in spell checker anymore. (If only Typora had been running from a web server locally I could use both...🤔)

## You won't get my money just yet...

I love Typora and the work you have done with it. I would love to spend money on it in the future, but it is just not "there" yet. I could easily pay twice the price of 15 USD if I could integrate a proper spell checker and image management.

The issues I have mentioned here has been mentioned many times in the issues here on Github. Many of the issues are years old and closed without any further action or consideration.

The best thing about Typora was its prospect and potential. Unfortunately, I will be looking for alternatives again and leave Typora 😢

**Comment by technodrome** [comment]
Well this is just your typical "pay or GTFO" model. You are very much right about images. If the author says Typora is out of beta, I would expect full-fledged image management where I do not need to remember to go to some mysterious folder and delete stuff I just deleted in the MD file. I mean, way more people are gonna need images done properly than some Mathjax support. This should be fully automatic. Half-baked, unfinished, as it is now.

Other than that, I like Typora very much. But it does feel like the author did not want to wait longer for more polished features, just said "hey whatever" and tried to monetize the app ASAP. Which is a shame. I will simply stick with last free version until image management is there. No need to upgrade, no rush. If it is not worth it, it is not worth paying for. Which makes me sad, because I consider typora a very nice Markdown editor - its power was "free" label so you could be more forgiving about the lack of certain features. But as a paid product? Nope. It better be worth it.

**Comment by LogoiLab** [comment]
This paid model is hot trash. Requires internet, and has the gall to ask for "Usage Info". This is not the open source way. You will not be getting my money. And you have lost a loyal user.
