### ISSUE TITLE
Cannot Drag'n'Drop Files in FileTree on Linux

### ISSUE THREAD

**Issue by blurayne** [typora/typora-issues#4906]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----
Drag'n'Drop for Files in File Tree should be possible by Changelog for Typora 0.9.9.20 (0.9.61) beta

I can click a file and it is opened and marked with a dashed border. If I press Ctrl in conjunction with the mouse click it opens a new window with the file. But I cannot drag'n'drop the file in the file tree to like another folder.

It would be great this feature now that I spent $15 for yes, my favorite MarkDown editor.

**Desktop (please complete the following information):**
Ubuntu Impish with either Wayland or Xorg sessions on GNOME. Both sessions have the same problem.
Fedora 35 with GNOME41 on Wayland

**Typora Version**
Typora 1.0.3

**Comment by blurayne** [comment]
I switched into `Enable Debug Mode` and checked Typora Log and the Console, but only thing I get is:

```
INFO 12/13/2021, 2:00:55 PM  ondragstart path-to-document/document.md
```

**Comment by blurayne** [comment]
frame.js

 ```
 setDraggingItem(e, t, n) {
                if (this.draggingItem = e,
                null == e)
                    y = 0;
                else if (File.isNode) {
                    if (!e)
                        return;
                    var i = File.isLinux ? "" : window.__dirname + (t ? "/style/windows-folder-icon.png" : "/style/typora-file-icon.png");
                    reqnode("electron").ipcRenderer.send("ondragstart", e, i),
                    n && n.preventDefault()
                } else
                    File.isMac && bridge.callHandler("controller.startDrag", e)
            }
```

Well, it works for me if you overwrite `i` just before `ondragstart`:

```
i = window.__dirname + "/style/typora-file-icon.png" 
```


So, I guess no Drag'n'Drop is intended for Release 1.0.0 since File.isLinux == true? Please fix!

**Comment by blurayne** [comment]
Temporary workaround:
```bash
sudo sed  's|File.isLinux?"":||g' -i  /usr/share/typora/resources/appsrc/window/frame.js
```

**Comment by abnerlee** [comment]
4528
