### ISSUE TITLE
Upload image failed on Ubuntu20.04

### ISSUE THREAD

**Issue by PeiLeizzz** [typora/typora-issues#4908]
**Describe the bug**
Typora 中使用 Custom Command 测试上传图片时提示 `/bin/sh: 1: /usr/local/lib/nodejs/bin/node: not found`
但是使用相同的命令在 shell 中就 upload 成功
![image](https://user-images.githubusercontent.com/57790152/145222431-f0f80f4a-f2f8-45de-81d2-12d39f392caf.png)
![image](https://user-images.githubusercontent.com/57790152/145222536-e77bfeae-3ac2-4ee1-83f3-fca55d1c55ca.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS

**Typora Version**
 - 0.11.8(beta)

**Comment by abnerlee** [comment]
Does /usr/bin/node works?

And does /usr/local/lib/nodejs/bin/node exist before you start terminal / bash and it is a binary or a link?

I think you could use `which node` instead -> https://zhuanlan.zhihu.com/p/35727707

**Comment by PeiLeizzz** [comment]
> Does /usr/bin/node works?
> 
> And does /usr/local/lib/nodejs/bin/node exist before you start terminal / bash and it is a binary or a link?
> 
> I think you could use `which node` instead -> https://zhuanlan.zhihu.com/p/35727707

1. No, it still failed
   ![image](https://user-images.githubusercontent.com/57790152/145570829-ff5be730-363c-4401-8096-9ec836482283.png)
2. Yes, and you can see:
   ![image](https://user-images.githubusercontent.com/57790152/145571043-2a41041b-ce43-487b-aa36-eb13d7de2dd9.png)

I'm sorry that I'm still a rookie of linux, so I really don’t know how to solve this problem.

**Comment by abnerlee** [comment]
I'm also not sure why it says "/usr/local/lib/nodejs/bin/node: not found"

Do you use same account for terminal and Typora? What about launch Typora form the terminal? Did the typora installed via deb package? And  how did you install node?
