### ISSUE TITLE
Resolution/DPI change will crash Typora in macOS

### ISSUE THREAD

**Issue by wey-gu** [typora/typora-issues#4909]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
As titled. On macOS(m1)

**To Reproduce**
1. start typora with multiple screens(or even one screen with [better dummy](https://github.com/waydabber/BetterDummy))
2. disconnect better dummy screen
3. reconnect better dummy screen
4. typora crashed with the `reopen` window will be shown

**Expected behavior**
not crashed

**Screenshots / Screencasts**
N/A

**Sample Markdown File**
N/A
**Desktop (please complete the following information):**
 - OS: macOS 12.0.1 (21A559)

**Typora Version**
Version 1.0.2 (5990) ( but had encountered since last versions if I recall it correctly)

**Additional context**
N/A

**Comment by brianAda** [comment]
I have been experiencing this for several months, both before and after upgrading to a paid license.

**Comment by abnerlee** [comment]
We did receive very few reports form users, but I cannot reproduce it by myself..

Could you try exit Typora then remove ~/Library/Caches/abnerworks.Typora/ ? And does reboot your Mac works?

If still not working, possible to attach a screencast about how change DPI will crash Typora?
