### ISSUE TITLE
Inconvenient cursor navigation across line breaks, resetting to start/end-of-line

### ISSUE THREAD

**Issue by Consumered** [typora/typora-issues#491]
Windows 10
0.9.23 (beta) x64

Not sure if this is intended behavior, but using arrows to navigate cursor will reset to the end-of-line navigating up a line and start-of-line navigating down a line across line breaks (word-wrapped lines are fine). This occurs regardless if line break is Enter or Shift+Enter.

This is unlike typical editor behavior (and Typora's word-wrapped line or code editor) of preferring the nearest character position of the last column the user explicitly placed the cursor at.

Either way, I would suggest considering changing this behavior to be consistent as an enhancement unless there is an overwhelming reason to keep it as described (thereby emphasizing paragraphs as disparate elements in the document).

**Comment by Consumered** [comment]
Current behavior works well for Focus mode, however.

**Comment by abnerlee** [comment]
Fixed in new release
