### ISSUE TITLE
[macOS] Auto-update not configured, v. 1.0.3

### ISSUE THREAD

**Issue by tundrahelix** [typora/typora-issues#4910]
When opening [paid] version of Version 1.0.3 (5993), or doing a manual "Check for Updates", get the popup:

Auto-update not configured

For security reasons, updates to Typora need to be served over HTTPS and/or signed with an EdDSA key. See https://sparkle-project.org/documentation/ for more information.

Review of link provides an extremely complex set of instructions that do not seem to be workable solution to patch commercial software.

How do I update Typora?

**Comment by abnerlee** [comment]
relates #4896

Please redownload Typora (1.0.4) from our website (typora.io)
