### ISSUE TITLE
Relative path option does not work for latex export

### ISSUE THREAD

**Issue by nickriches** [typora/typora-issues#4911]
**Describe the bug**

I have set the relative path option for latex export. However, in the latex output, full paths are used.

**To Reproduce**

Set image options to "use relative path if possible". Export a document to latex. Note that paths for images are not relative.

**Expected behavior**

I expected relative paths

**Desktop (please complete the following information):**
 - OS: Mac 11.6.1 (Big Sur)
 - 
**Typora Version**
1.0

**Comment by abnerlee** [comment]
duplicated with #2546
