### ISSUE TITLE
[Feature] Slideshow/presentation with MD

### ISSUE THREAD

**Issue by matteounitn** [typora/typora-issues#4912]
Despite the fact that I love what you've done with typora, I miss one feature that is present in other, albeit niche, markdown editors: slideshow/presentation mode.
For example, using hackmd.io, I can use a markdown file as a slideshow, separating the slides with a '---' line. Given the extent to which themes can be customized, it would be nice to have the ability to export to dynamic HTML that performs the slideshow (using a library such as Jquery) or to pdf exporting similar to the powerpoint/libreoffice PDF export.

Given how customizable a CSS theme is, it would be fantastic to be able to convert what is currently a single page (HTML) into multiple presentation pages while maintaining the theme.

**Comment by abnerlee** [comment]
Duplicated with #89

And it is already possible (like https://github.com/typora/typora-issues/issues/89#issuecomment-856147024) for example.
