### ISSUE TITLE
[MacOS] Typora force close at random times

### ISSUE THREAD

**Issue by D35P4C1T0** [typora/typora-issues#4913]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

While typing, at any moment, I'm facing a force close of the app. It might happen twice in a minute, or not at all during my typing session.
I also added the logs, or at least what shows up in the terminal once Typora force closes.
I'm on MacOs BigSur 11.6.1 and using Typora Version 1.0.3 (5993), but it used to crash on me in the same way even on earlier builds, including beta ones.

![typora-crash](https://user-images.githubusercontent.com/42818929/145365719-6a40c6fb-1152-4fac-8388-afa6deaa798c.png)

**Comment by abnerlee** [comment]
Yes, please redownload the version 1.0.4
