### ISSUE TITLE
Failed to export as PDF. Failed to generate PDF

### ISSUE THREAD

**Issue by FavonianKong** [typora/typora-issues#4915]
**Describe the bug**
I use the simplest test.md which only contains "hello world" and the try to export it as PDF but get the error:
`Failed to export as PDF. Failed to generate PDF`

**To Reproduce**
1. save the test.md with contain "hello world"
2. Click on 'Files' -> export -> PDF
3. See error

**Expected behavior**
generate PDF sucessfully

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/40446561/145546531-2b13ebb3-ecad-41e0-b678-e36a840af8fb.png)

**Sample Markdown File**
hello world
**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]

**Typora Version**
version: v0.11.18

**Additional context**
I also try the stable version and some other beta version, but fail in the end.
BWT, I have refer the issue #3766 and make sure that the `print spooler` is running.

**Comment by abnerlee** [comment]
Possible to send us (hi@typora.io) the log file (https://support.typora.io/Get-Logs/) ?

**Comment by FavonianKong** [comment]
> Possible to send us ([hi@typora.io](mailto:hi@typora.io)) the log file (https://support.typora.io/Get-Logs/) ?

Here is the latest log info
```
INFO 2021/12/13上午9:06:37  [Power] lock-screen
INFO 2021/12/13上午9:06:37  [RenderProcess 1][Log] [powerMonitor] unlock-screen
INFO 2021/12/13上午9:16:29  [blur] 1
INFO 2021/12/13上午9:16:29  [win] blur
INFO 2021/12/13上午9:16:29  [focus] 1
INFO 2021/12/13上午9:16:34  load file [C:\Users\geeklee\AppData\Local\Temp\1639358194799-0.5668824114780873.html] for PDF export
INFO 2021/12/13上午9:16:35  generate print window with id 6
INFO 2021/12/13上午9:16:35  [blur] 1
INFO 2021/12/13上午9:16:35  [win] blur
ERROR 2021/12/13上午9:16:35  [Error: Failed to generate PDF]
INFO 2021/12/13上午9:16:38  [focus] 1
INFO 2021/12/13上午9:16:38  [RenderProcess 1][Log] export PDF to C:\Users\geeklee\Desktop\Untitled.pdf
INFO 2021/12/13上午9:16:41  [blur] 1
INFO 2021/12/13上午9:16:41  [win] blur

```

**Comment by abnerlee** [comment]
Did you use Typora from local network (https://github.com/electron/electron/issues/24734) ?

Or try to close window when exporting (https://github.com/electron/electron/issues/29485)?

And does print work?

**Comment by FavonianKong** [comment]
> Did you use Typora from local network ([electron/electron#24734](https://github.com/electron/electron/issues/24734)) ?
> 
> Or try to close window when exporting ([electron/electron#29485](https://github.com/electron/electron/issues/29485))?
> 
> And does print work?

No, It's a bit weird that I was able to export pdf a week ago. I'm sure I haven't done anything strange to my computer lately.

**Comment by eglinetwork** [comment]
Same issue with **Win10** and **Typora 1.0.3**

Does the following log help?

```
INFO 12.1.2022, 07:42:16  [focus] 1
INFO 12.1.2022, 07:42:20  load file [C:\Users\egli\AppData\Local\Temp\1641969740661-0.5694288734270894.html] for PDF export
INFO 12.1.2022, 07:42:21  [blur] 1
INFO 12.1.2022, 07:42:21  [win] blur
INFO 12.1.2022, 07:42:23  [focus] 1
INFO 12.1.2022, 07:42:23  [RenderProcess 1][Log] export PDF to C:\Users\egli\Desktop\Technical Specification.pdf
Timeout for loading print view
INFO 12.1.2022, 07:42:30  generate print window with id null
INFO 12.1.2022, 07:42:43  [blur] 1
INFO 12.1.2022, 07:42:43  [win] blur
```

**Comment by abnerlee** [comment]
> Timeout for loading print view

@eglinetwork Does your markdown file very large? since it shows a "Timeout for loading print view". Or does retry works?

**Comment by eglinetwork** [comment]
Timeout for loading print view:

@abnerlee Large images were inserted in the document as an external http reference. This led to the timeout problem. 
Using local copies of the images solved the problem. The PDF export works correctly now.

**Comment by abnerlee** [comment]
@FavonianKong Hi, could you try install Typora under C: disk and see if PDF export works or not

**Comment by eglinetwork** [comment]
> @FavonianKong Hi, could you try install Typora under C: disk and see if PDF export works or not

@FavonianKong Typora is installed under C: disk. After removing images from the document that were not stored on the C: disk the export works without timeout
