### ISSUE TITLE
Typora self-updating to new version reopens to blank document

### ISSUE THREAD

**Issue by mattneub** [typora/typora-issues#4916]
- [x ] Searched existing issues to avoid creating duplicates.

- [ x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
When Typora updates to a new version, it forgets what file(s) it has open.

**To Reproduce**

1. Open a saved file with Typora.
2. Update Typora to a new version.

**Expected behavior**
Typora should update and relaunch _and reopen the file that it had open when we updated_. It doesn't reopen that file; we are let sitting looking stupidly at an empty untitled document. That is incorrect behavior.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1

**Typora Version**
e.g: Version 1.0.4 (5994), but any self-updating version will do; this bug has always been there

**Comment by abnerlee** [comment]
#3257
