### ISSUE TITLE
mermaid flowchart display

### ISSUE THREAD

**Issue by yiwc** [typora/typora-issues#4917]
<img width="637" alt="Screenshot 2021-12-12 at 3 22 18 PM" src="https://user-images.githubusercontent.com/44794635/145704061-453e6f8f-3ad9-4d4e-a7ec-c4b5b22a9d71.png">

THanks~!

**Comment by yiwc** [comment]
version 1.0.4

**Comment by abnerlee** [comment]
merge into #1661

Also, does it happen in mermaid.live?

What's your OS and screen DPI, and did you zoom Typora or screen?
