### ISSUE TITLE
[Feature] More front-matter capabilities

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#4918]
I deeply miss:
1. The ability to specify a different front-matter for:
 - the first page (typically with no header/footers)
 - even/odd pages

2. Specify the page number to start from. The following is an example to start from page 10: declare somewhere `$myvar=10` and then:
```
---
footer: ${pageNo+myvar} / ${pageCount + myvar}
---
```

**Comment by abnerlee** [comment]
duplicate with #4191 #4478
