### ISSUE TITLE
Export-HTML-with-Outline-for-Typora

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#492]
MORE INFO: [Export-HTML-with-Outline-for-Typora](https://github.com/MadMaxChow/Export-HTML-with-Outline-for-Typora)

**Comment by abnerlee** [comment]
move discussions to https://github.com/typora/typora-issues/issues/479

**Comment by jediwarrior77** [comment]
Make a real and nice export html outline you lazy fucks.
