### ISSUE TITLE
请问一下怎么解决这个日期重叠的问题？

### ISSUE THREAD

**Issue by ysdxz207** [typora/typora-issues#4925]
![image](https://user-images.githubusercontent.com/4596561/145926834-698a1eba-0d24-4982-9fc6-d94e2509d737.png)

**Comment by abnerlee** [comment]
Could you provide code sample?

Could you also try on https://mermaid.live/?

merge into #1661

**Comment by ysdxz207** [comment]
@abnerlee 
![image](https://user-images.githubusercontent.com/4596561/145970668-66339e0e-282e-4163-9f35-fdc968ea0396.png)

code:
```
gantt
  title 时间排期（暂定）
  section 研发
    1     :2021-12-14, 14d
    2     :2021-12-20, 9d
    3          :2021-12-29, 3d
    4          :done, 2022-01-01, 3d
    5          :2022-01-04, 5d
  section 发布
    6          :2022-01-11, 1d
    7          :2022-01-12, 1d
```

**Comment by abnerlee** [comment]
![image](https://user-images.githubusercontent.com/1621242/145982182-0a7bdc6f-8a10-4a45-b0e3-2616b156ec35.png)

For hotfix, please increase the writing area https://support.typora.io/Width-of-Writing-Area/
