### ISSUE TITLE
[Feature] Add page numbers to Table Of Content on PDF export.

### ISSUE THREAD

**Issue by hollowshiroyuki** [typora/typora-issues#4927]
Is it possible to add the page number to the `[toc]` tag when exporting to PDF ?
As some documents could be printed it would be nice having the page number next to the section title.

I really don't know how you could do it or if it's possible as we probably don't know on which page the header will be before the actual pdf export.

**Comment by abnerlee** [comment]
It's less likely we are able to support it for technical reasons.

But you could use Pandoc/LaTeX's approach of PDF export, which can be configured to support it via LaTeX templates. See https://support.typora.io/Export/#pdf-latex--pandoc for more details.
