### ISSUE TITLE
Content reuse

### ISSUE THREAD

**Issue by StarfallProjects** [typora/typora-issues#4929]
Hopefully not a duplicate - search for content reuse showed nothing, and search for snippets showed a different feature.

Would it be possible to add content reuse?

By content reuse I mean including files within other files. So for example, say I'm writing a series of tutorials. At various points I want to include a warning (for instance, warning the reader that a particular action can delete data) I could create a single file containing that warning, then include it in multiple places and documents.

I am thinking of something similar to [MadCap Flare's snippets](https://help.madcapsoftware.com/flare2021r2/Content/Flare/Snippets/Snippets.htm) (although it certainly doesn't need to be as full featured!), or [PyMDown's snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) (I think both of these are different from what you mean by snippets in your docs)

**Comment by abnerlee** [comment]
you mean #4839 ?

**Comment by StarfallProjects** [comment]
Ah sorry, I only searched open issues. It looks like the relevant open issue (https://github.com/typora/typora-issues/issues/441) doesn't include the phrase "content reuse". Sorry for the duplication, I'll follow that issue.
