### ISSUE TITLE
License activation in business environment

### ISSUE THREAD

**Issue by ArtDan** [typora/typora-issues#4930]
Hi abnerlee,

first: I'm really addicted to Typora and use it constantly at work (and privately). I really NEED it :-)

But I am also here to make you aware of the problems in the work environment.
Don't get me wrong, your prices is *very fair* and I'd even love to pay 150$ for it … but I can't.

With this license model I cannot
* … use Typora at work any more
* … register a license for every VM and OS I use (and there are a lot of them. And I need to constantly switch between them)
* … grant every machine I use access to the internet (sounds anachronistic, but in business environment, i just can't do that)
* … register with my personal phone number – this is an absolute no-go, too. Even more so if the phone number is not for you, but an distributor!

So, I beg you, please, think about a "Bulk License" or "Unlimited License", with which I can continue to work as before without Internet access.

I brought Typora to every company and developer I am working with. And everyone loved it. Some of them even introduced it for their workflows. So please don't let them down, now.

Regards

#4872 
#4903

**Comment by abnerlee** [comment]
Yes, we will improve them.

**Comment by ArtDan** [comment]
Thank you!

**Comment by zlogz** [comment]
I fully agree with @ArtDan's point, it does need an offline mode to activate Typora and work well with it. Currently, I purchased the license, unfortunately, however, the business firewall can't be broken by an editor. Now, I only have 14 days to use even I've already owned a license.
Really appreciate to help us, who have deeply typora-infected, cheers.

**Comment by abnerlee** [comment]
duplicated with #4903
