### ISSUE TITLE
[Feature] Option to detect Git (or any VCS) root directory as working folder

### ISSUE THREAD

**Issue by jaekyeom** [typora/typora-issues#4931]
I thought there must be some existing issues about this, but I cannot find one.

I manage my .md files in some directory structure and sometimes I open one of the .md files with Typora directly from a terminal app (or one could use Finder).
(ADD: or open with "Open Quickly")
Every time I do that, in Typora, the .md file's parent directory becomes the working directory for it, which requires me to change the directory manually.
e.g., if I open `/path/to/project_root/subject1/file1.md`, the working directory is `/path/to/project_dir/subject1/`.

Could you implement detecting the closest ancestor Git (or any other VCS) root directory as the working directory, please?

**Comment by abnerlee** [comment]
duplicated with #2926

**Comment by jaekyeom** [comment]
@abnerlee 

It's been a while. Although my original comment could have been misleading, I was NOT talking about `typora-root-url`.
My major concern was about the file explorer/tree view on the left side of Typora's UI, and I want it to show the root directory of my project, not the direct parent directory.

I've figured out a trick to achieve this (on macOS), though.
