### ISSUE TITLE
Start app in fullscreen

### ISSUE THREAD

**Issue by tghuguenin** [typora/typora-issues#4932]
Maybe I missed this but is there a preference option to set Typora to open in fullscreen by default? Typora will remember last non-fullscreen window size used and restore to that when reopened, but will not open in fullscreen.

Typora version: 0.11.18 (5941)
using macOS Catalina 10.15.7

**Comment by abnerlee** [comment]
I think it is the default behavior on macOS.

I tested Safari and TextEdit, they both do not enter fullscreen mode automatically after quite a fullscreen instance.
