### ISSUE TITLE
Mermaid Gitgraph diagram does not correctly position labels

### ISSUE THREAD

**Issue by beiriannydd** [typora/typora-issues#4934]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
Creating sample gitgraph diagram causes the labels to be displayed over each other at top left instead of attached to the nodes.
```
gitGraph:
options
{
    "nodeSpacing": 150,
    "nodeRadius": 10
}
end
commit
branch newbranch
checkout newbranch
commit
commit
checkout master
commit
commit
merge newbranch
```

![image](https://user-images.githubusercontent.com/25019609/146465156-2a12cd4b-9567-4831-a9f3-e12051cfb114.png)

**To Reproduce**
1. create mermaid code block:
gitGraph:
options
{
    "nodeSpacing": 150,
    "nodeRadius": 10
}
end
commit
branch newbranch
checkout newbranch
commit
commit
checkout master
commit
commit
merge newbranch

2. See ![image](https://user-images.githubusercontent.com/25019609/146465156-2a12cd4b-9567-4831-a9f3-e12051cfb114.png) all labels are displayed on top of each other instead of next to the node.

**Expected behavior**
Labels should be displayed next to the nodes:
![image](https://user-images.githubusercontent.com/25019609/146465541-7451d84f-af22-48f6-978c-b6025bc360a4.png)

**Screenshots / Screencasts**
Screenshots uploaded in appropriate places to avoid confusion

**Sample Markdown File**
Attached

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Registered copy

**Typora Version**
1.0.4

**Additional context**

**Comment by abnerlee** [comment]
put into #1661
