### ISSUE TITLE
Failed to export PDF file with error "pdf-engine must be one of ..."

### ISSUE THREAD

**Issue by kele14x** [typora/typora-issues#4935]
**Describe the bug**

I'm trying to export PDF using Typora (file -> export -> PDF (LaTeX / Pandoc)), but failed with error:

![pdf-error](https://user-images.githubusercontent.com/4020067/146496410-7d5a4f66-e356-40a8-a723-e1a64ec2ad18.png)

The command line is:

```
-f native -s -o C:\Users\<name>\Desktop\aaa.pdf -t pdf --pdf-engine="xelatex"
```

However, both `pandoc` and `xelatex` works nice in terminal. `pandoc aaa.md -s -o C:\Users\<name>\Desktop\aaa.pdf -t pdf --pdf-engine="xelatex"` also works.

**PDF (LaTeX / Pandoc)** was created with default values and set pdf engine to `xelatex`. I've tried `pdflatex` and others, all result same error.

**To Reproduce**

1. Open with any markdown file
2. Click on 'file -> export -> PDF (LaTex / Pandoc)'

**Expected behavior**

The PDF file is created successfully.

**Screenshots / Screencasts**

See above

**Versions**

- OS: Windows 11 64bit
- Typora: 1.0.3
- Pandoc: 2.16.2
- xelatex: MiKTeX-XeTeX 4.7.1 (MiKTeX 21.12.10 Portable)

**Comment by abnerlee** [comment]
Did you try replace "xelatex" with its full path?

**Comment by kele14x** [comment]
Hi, @abnerlee

I've tried full path, it works... I've checked the **PATH** setting in my machine and terminal, `xelatex` command without full path works too.

**Comment by stockphrase** [comment]
Having the same problem in Typora v 1.2.3

**Comment by abnerlee** [comment]
> I've tried full path, it works... I've checked the PATH setting in my machine and terminal, xelatex command without full path works too. But Typora still refuses to use xelatex command directly

You may add xelatex to PATH when starting the shell (using bashrc) for the terminal app, instead of put it into the system PATH. Typora do not "run scripts" before execute other binaries.
