### ISSUE TITLE
License activation with USB docking stations

### ISSUE THREAD

**Issue by niemick** [typora/typora-issues#4939]
Just activated three Notebooks in our company (all connected to the Internet by a docking station). Worked just as expected.
First day in homeoffice with notebook 3 (connected by internal WLAN card): No activation? Activated again --> notebook 1 looses (oldest) activation....

I guess your license is bound to the MAC of a network card, And in case of a USB docking station the MAC is not present any more when the notebook is used in a mobile scenario. For now, we activated all notebokks again by their internal WLAN and solved this issue for us.

I suggest to make the activation more robust maybe by the use of other available network cards (internal LAN, internal WLAN

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> log (https://support.typora.io/Get-Logs/) ?

**Comment by niemick** [comment]
[typora_1st.log](https://github.com/typora/typora-issues/files/7760242/typora_1st.log)
[typora_2nd.log](https://github.com/typora/typora-issues/files/7760263/typora_2nd.log)
[typora.log](https://github.com/typora/typora-issues/files/7760228/typora.log)

FYI: "typora_1st.log" is the notebook activated first, "typora_2nd.log" the second activation.
**"typora.log" is the third activation on the 3rd notebook where the issue occured for the first time.**

**Comment by abnerlee** [comment]
From typora.log, it seems there are already three activated devices before 3rd notebook is activated. Could you send us your license key for us to check log in our service side?

Anyway, we do not use MAC for license activation.
