### ISSUE TITLE
导出错误

### ISSUE THREAD

**Issue by necan** [typora/typora-issues#4940]
**Describe the bug**
导出的 html 中，某些无序列表并没有被包裹在 p 标签中，导致 base.css 的列表间距样式失效。
```
li .mathjax-block, li p {
    margin: .5rem 0;
}
```

**To Reproduce**
导出我的示例文件为 html 文件即可复现。

**Expected behavior**
li 中的元素应该被 p 包裹，实际没有！

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/25315125/146742800-c93157c0-4bc1-45b8-acb5-fb38be97a42f.png)

**Sample Markdown File**
[性质.md](https://github.com/typora/typora-issues/files/7744046/default.md)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]

**Typora Version**
1.0.2

**Additional context**
导出 html、PDF 均受影响。

**Comment by abnerlee** [comment]
```
- aaa
- bbb
```

will export `<li>` only

```
- aaa

- bbb
```

will export `<li><p>`

**Comment by abnerlee** [comment]
And please use a readable / searchable title to create issue to avoid future duplications.
