### ISSUE TITLE
使用Typora发生了很多错误，亟待解决。

### ISSUE THREAD

**Issue by YYan2017** [typora/typora-issues#4941]
1. 我使用的是Mac, 11.6.1, Typora 1.0.4。
2. 在我今天关闭Typora后，再次打开软件发现所有的之前的标签页均消失了。
3. 我并没有在第一时间使用“重新打开关闭的文件“功能，我现在该如何恢复（比如通过Time machine）之前打开的标签页。
4. 一些没有保存的标签页，在Autosave information里面无法被找到，这些文件去了哪里？我记得没有保存的文件之前都会在这个文件夹里出现。 我现在该如何找回他们？
5. 如何通过Time machine精确的找回这些drafts？而不需要完全恢复整台电脑的数据？

我非常着急，所以使用中文提问以尽快清晰的解决问题，谢谢！

**Comment by YYan2017** [comment]
我现在非常沮丧我在关闭软件前没有对所有标签进行储存，我新建了大概10几个tab，我很习惯把Typora当作我碎片想法的搜集器，因为文章成型前我往往不会保存（标题不知道该如何起），求求作者救救我的这些创作吧！

**Comment by abnerlee** [comment]
answered in Email
