### ISSUE TITLE
"Typewriter / Focus Mode have been turned off." keeps popping up

### ISSUE THREAD

**Issue by Epoooch** [typora/typora-issues#4943]
**打字机模式总是处在关闭状态**
* 正式版本：V1.03
![image](https://user-images.githubusercontent.com/49396047/146955590-855b9f2b-be7c-4783-8bab-1444f459a785.png)
无论我怎么点击多少次 ***打开 打字机模式/专注模式*** 按钮，都会弹出上面的对话框。
![image](https://user-images.githubusercontent.com/49396047/146955868-95293917-431e-46b2-91de-8f7adf2d076c.png)
而且按钮的状态也一直是上图的状态。
希望能及时改进修复，祝产品越做越好！

**Comment by abnerlee** [comment]
It's expected, when you click that button, it tells you it has been operated in a message dialog.
