### ISSUE TITLE
[Feature] Strike the text whenever a task list is marked as complete

### ISSUE THREAD

**Issue by GreatBahram** [typora/typora-issues#4944]
Hello there,

I'd like to kindly ask for this feature that we see mostly everywhere. Whenever you have a task list and you mark it as complete, in most applications, they not only check the box but also strike the corresponding text. Currently, I do the second part, strike, manually and I feel this is something that everyone expects it.

Needless to say, whenever a task status is changed to incomplete, the reverse should be done, unmark and remove the strikeness.

Current behaviour:
 - [X] text
Expected behaviour:
- [X] ~~text~~

**Comment by abnerlee** [comment]
see https://support.typora.io/Task-List/

**Comment by GreatBahram** [comment]
Thank you very much!

May I ask why the strikethrough is not the default behavior? Because we see this in famous apps, like Google Keeps or on notes applications such as Samsung Notes and etc,
