### ISSUE TITLE
[Feature] grammarly integration

### ISSUE THREAD

**Issue by GreatBahram** [typora/typora-issues#4945]
Hi there,

I hope you're doing fine.

I use the Grammarly writing assistant and I was wondering if there is any way to connect my Grammarly into typora? Or at least could you add this into your road map?

With thanks,
Bahram

**Comment by abnerlee** [comment]
duplicated with #4771

**Comment by wey-gu** [comment]
I can confirm with the native Grammarly app being installed, at least in macOS, it works perfect within typora.

**Comment by wey-gu** [comment]
![grammarly](https://user-images.githubusercontent.com/1651790/186800490-b9efa5ff-5ca6-4c85-8a46-43005897e02a.jpg)

**Comment by AndrewDiMola** [comment]
@wey-gu - Sorry for resurfacing. Yes, the above does work as it is the desktop version, but I think the other request was in regards to integrating the SDK https://github.com/typora/typora-issues/issues/4771#issue-1043086402 into Typora itself.

Disclaimer: I manage the documentation for this product. If you ever have questions on the product, or are interested in pursuing a Grammarly option in-product, feel free to continue this thread.

**Comment by wey-gu** [comment]
> @wey-gu - Sorry for resurfacing. Yes, the above does work as it is the desktop version, but I think the other request was in regards to integrating the SDK [#4771 (comment)](https://github.com/typora/typora-issues/issues/4771#issue-1043086402) into Typora itself.
> 
> Disclaimer: I manage the documentation for this product. If you ever have questions on the product, or are interested in pursuing a configurable Grammarly integration in Typora, feel free to ask questions / continue this thread.

And that will be next level, thanks @AndrewDiMola !
