### ISSUE TITLE
"#"  has been escaped  "%23" when md exports to pdf in url link

### ISSUE THREAD

**Issue by tomchon** [typora/typora-issues#4946]
"#"  has been escaped  "%23" when md  export to pdf 

md url link:

> https://www.taosdata.com/cn/documentation/insert#schemaless

pdf link: 

> https://www.taosdata.com/cn/documentation/insert%23schemaless

version:

> Version 0.11.5 (5648)  beta version

**Comment by tomchon** [comment]
urgent, please ~~~

**Comment by abnerlee** [comment]
duplicated with #3435
