### ISSUE TITLE
[Feature] Typora for Academic Writing

### ISSUE THREAD

**Issue by nashrullahalifauzi** [typora/typora-issues#4947]
Typora for Academic Writing

In the `Preferences` tab (or wherever) it would be nice if Typora had a form that stores JSON/BIB files and CSL files (<https://www.zotero.org/styles>). Of course this will be useful for users, especially those who use Typora for academic writing.

User can call citation key of bibliography with `@`, for example `[@johnBook2021 243]`. And Typora can render it as a citation, `(John 243)`. This will be in line with Pandoc, in which Typora also uses it as a document conversion tool.

**Comment by abnerlee** [comment]
duplicated with #912
