### ISSUE TITLE
Lack of File -> Import option on macOS?

### ISSUE THREAD

**Issue by solarce** [typora/typora-issues#495]
I am really liking Typora so far, using it as my main Markdown editor on macOS. When looking at the docs about the `pandoc` integration, http://support.typora.io/Install-and-Use-Pandoc/, I see mention of **File -> Import**

> After Pandoc is installed, then you could import supported file types by clicking File -> Import from menubar,

But I do not see this option in my install. I am using Typora `Version 0.9.9.8.8 (0.9.9.8.8)` on macOS 1`0.11.6 (15G1212)` and I have `pandoc` `1.19.1 Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3` installed from the `.pkg` they provide.

If I try to drag an `.html` or `.docx` file onto Typora, I just the text representation of the file in a new window, there's no _import/conversion_ done.

What could I be missing?

**Comment by abnerlee** [comment]
It is our bug that "import" is hidden.

Use "Open" or drag & drop the file to import as a temp workaround

**Comment by solarce** [comment]
@abnerlee if I use **File -> Open** or _drag and drop_, I still just get a text view of the `.html` source code. Is there some things I can check to make sure Typora is finding `pandoc` and things are _wired up correctly_ ?

**Comment by abnerlee** [comment]
I put "import" menu item back on latest version. Please try update and see if it works

**Comment by solarce** [comment]
Thank you, the **Import** option is working now, I tested it with a `.docx`
(that I exported from Google Docs) and it worked nicely.

Would you consider making `.html` a supported import option?

Brandon Burton
- @solarce
https://www.solarce.org/
https://twitter.com/solarce

**Comment by thinkhuman** [comment]
This still seems to be a bug. On MacOS Big Sur with Pandoc installed via Homebrew (and working at the command line), I can't import any file of any type (all files are grayed out) when using Import feature.

**Comment by abnerlee** [comment]
should be fixed.

If still not working, see https://support.typora.io/Install-and-Use-Pandoc/#config-pandoc-path

**Comment by thinkhuman** [comment]
@abnerlee Pandoc is installed, and I can use pandoc independently to convert files. However, Typora Preferences don't show an Export option in Preferences > General. I see only General, Appearance, Editor, Image, and Markdown. So, the pandoc path may be the problem, but there's no option to change it.
Using Typora 0.9.9.36.2 (beta) on MacOS. My guess is that your Mac beta has omitted/disabled this feature.

**Comment by abnerlee** [comment]
please upgrade

**Comment by thinkhuman** [comment]
@abnerlee  Thank you. It looks like Export functionality was added to 0.10.6, which isn't what's downloaded with 'Download Beta (OS X)' link on the Download page. I found it in the tiny print below the download links ('Change Log / History Builds'). Maybe update the button link for Mac?
