### ISSUE TITLE
Picgo-core upload command error

### ISSUE THREAD

**Issue by cc852852** [typora/typora-issues#4952]
typora 0.11.98(beta)
OS windows10 20H2
When I tried the test uploader in image following the Picgo-core(command-line) instruction, it turns out @chcp 65001 >nul & cmd /d/s/c function(){return p}\picgo\win64\picgo.exe u. Seeking for other's result, it should be the picgo path instead of function(){return p} here. I installed picgo from typora downloading and config it well.
![](https://www.hualigs.cn/image/61c56c2c9a461.jpg)
![](https://www.hualigs.cn/image/61c56cb887f9f.jpg)

**Comment by abnerlee** [comment]
https://support.typora.io/Upload-Image/#garbled-console-output-on-windows
