### ISSUE TITLE
search chinese file contents not work

### ISSUE THREAD

**Issue by hyzgh** [typora/typora-issues#4953]
I have a file with content "练习听力". I could find this file by search "练习听力", but I couldn't find it by search "练习". My Typora version is 1.0.5.
I want to search files in typora, but I often find that it lacks some results. The worse thing is that you sometimes don't notice typora miss some result!
For now, I use grep to search my files in replace, and I hope typora could improve the search results.

**Comment by abnerlee** [comment]
What's your macOS version and could you provide a md file for test? In my test, it works fine

<img width="1013" alt="Screen Shot 2022-01-01 at 20 10 58" src="https://user-images.githubusercontent.com/1621242/147850239-612a1490-50bd-43c4-996a-7795f27fcb56.png">

**Comment by hyzgh** [comment]
@abnerlee My macOS version is 12.1
[test.md](https://github.com/typora/typora-issues/files/7812422/test.md)
