### ISSUE TITLE
Mermaid Styntax Error with `direction` Keyword Inside `subgraph`

### ISSUE THREAD

**Issue by jan9won** [typora/typora-issues#4954]
- [ v ] Searched existing issues to avoid creating duplicates.

- [ v ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ v ] Searched http://support.typora.io/

----

**Describe the bug**
Typora's current Mermaid compiler (v8.8.3) throws `Styntax error in graph`,
with `direction` keyword inside `subgraph`.

**To Reproduce**

1. Example mermaid code
```mermaid
flowchart TD

subgraph my-subgraph
	direction LR
	my-component-1
	my-component-2
	my-component-3
end
```

2. Throws syntax error
![Screen Shot 2021-12-24 at 4 21 40 PM](https://user-images.githubusercontent.com/59769898/147328871-557f2275-fbce-4f00-94af-8207e033796f.png)

**Expected behavior**

This Mermaid feature update happened in release [**`v8.10.2` June 6th 2021**](https://github.com/mermaid-js/mermaid/pull/2082).
As this feature is not backward-compatible, 
I think it's time to move on to at least release `v8.11` or later.

**Desktop Version**
OS: macOS Monterey 12.0.1

**Typora Version**
1.0.5 (6032)

**Comment by abnerlee** [comment]
put into #1661
