### ISSUE TITLE
Auto-update not configured

### ISSUE THREAD

**Issue by rowdenw** [typora/typora-issues#4955]
On macOS Mojave Version 10.14.5, Typora Version 1.0.3 (5993) produces the following message when selecting Typora -> Check for Updates (and any time Check Updates is run when "Check updates automatically" is checked in Typora -> Preferences -> General):

Auto-update not configured
For security reasons, updates to Typora need to be served over HTTPS and/or signed with an EdDSA key. See https://sparkle-project.org/documentation/ for more information.

![Auto-update-not-configured](https://user-images.githubusercontent.com/12215507/147370757-9d782bf0-86d0-462b-a758-32d5bd83578b.png)

Expected behavior is to silently check for updates until an update is available, and then provide the option to install the update.

**Comment by JaeguKim** [comment]
I'm also facing same issue. I'm using Typora version 1.0.3 (5993) on Big Sur.

**Comment by abnerlee** [comment]
#4910
