### ISSUE TITLE
Line selection (Ctrl+L) from beginning of line selects previous line

### ISSUE THREAD

**Issue by davidevecchi** [typora/typora-issues#4960]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When the caret is placed at the beginning of a line and Ctrl+L is pressed, the previous line is selected instead of the one where the caret is located.

**To Reproduce**
1. Write a document with several lines (hard returns, soft returns, lists etc. lead to the same issue)
2. Locate the caret at the beginning of a line (except the first one)
3. Press Ctrl+L
4. Previous line is selected instead of the current one

**Expected behavior**
Line selection should select the current line, i.e. the text from the caret (located at the beginning of the line) to the next return character.

**Additional information**
Line selection from the beginning of a line works well inside math blocks and code blocks and when the caret is placed at the beginning of the document.

**Desktop**
 - OS: Manjaro Linux x86_64
 - Kernel: 5.15.7-1-MANJARO
 - DE: GNOME 41.2

**Typora Version**
 - Version: 1.0.3-2
 - Source: [AUR](https://aur.archlinux.org/packages/typora)

**Additional context**
The issue was also present in previous versions of the OS and of the Typora software.

**Comment by abnerlee** [comment]
fixed in 1.3.6
