### ISSUE TITLE
[Feature] - text format display or indicator to show details of current text at cursor position

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#4962]
Indicate the current text formatting if any based on cursor position.  Currently, the user must toggle to code mode to know if a particular text is bold vs heading, or which heading is used.

**Comment by coinzdude** [comment]
This appears to actually be a bug.  H1, H2 are not indicating while H3 is:

H3 Working:

**Comment by coinzdude** [comment]
H2 not working:
![image](https://user-images.githubusercontent.com/58857646/147683788-7e3deae9-222f-4a6f-9013-347138fc6025.png)

**Comment by abnerlee** [comment]
User would distinguish H1 & H2 by its size and style, or else user still not know H1 or H2 in exported HTML or after converting markdown to websites or ebooks.

And in some themes H1 or H2 maybe center aligned, so we do not add tags for H1 and H2 by default. But you can add whatever you want via custom css (https://support.typora.io/Add-Custom-CSS/)

duplicated with #98
