### ISSUE TITLE
check update still failed in 1.0.5, pls fix this issue again.

### ISSUE THREAD

**Issue by Longmindy2013** [typora/typora-issues#4964]
My pc is M1 MBP macOS 12.1.  BTW, when will the typora will support M1?

![image](https://user-images.githubusercontent.com/31234576/147724896-3396e43c-8686-4011-ae82-0e2a44b3ed95.png)

**Comment by abnerlee** [comment]
please use vpn or enable "use typora server in China" in preferecens panel.
