### ISSUE TITLE
[Feature] Separated sort order configs for tree and list view. 

### ISSUE THREAD

**Issue by KLA6** [typora/typora-issues#4965]
Thank you for your great software, and I've just bought one license. : )

BTW, I want to suggest one simple function which is...
- when we switch between `tree view` and `list view`,
- keening each own `sort order config` for 2 views.

The reason for suggesting this is...
- Normally, tree view will be used for Alphabet or Natural sort by file naming.
- However, list view is sometimes to check the recent edited files.

That's it, thank you for your reading...!

**Comment by abnerlee** [comment]
supported in 1.4.4
