### ISSUE TITLE
typora如何解绑设备呢？我电脑突然坏了，打不开，我怎么解绑这台电脑呢？

### ISSUE THREAD

**Issue by ttjygbtj** [typora/typora-issues#4966]
typora如何解绑设备呢？我电脑突然坏了，打不开，我怎么解绑这台电脑呢？How does typora unbind the device? My computer suddenly broke down and couldn't open, how do I untie this computer?

**Comment by abnerlee** [comment]
see https://support.typora.io/activation/#deactivate-typora
