### ISSUE TITLE
Bug in URL processing

### ISSUE THREAD

**Issue by rahvee** [typora/typora-issues#497]
I noticed a bug in URL processing. I specifically noticed mishandling the `~` character, but I suspect the general URL regex is probably buggy.

To recreate, simply write or paste a URL into typora, in wysiwyg mode, that includes `~` character. The entire URL should be recognized as a URL, but URL recognition breaks at the `~` character.

Screenshot:
<img width="398" alt="screen shot 2017-01-18 at 8 28 02 am" src="https://cloud.githubusercontent.com/assets/796356/22065852/10c52f14-dd58-11e6-8d80-48962a4bddcc.png">

**Comment by abnerlee** [comment]
Fixed in the newest version
