### ISSUE TITLE
Export to PDF: theme issue

### ISSUE THREAD

**Issue by driesmoors** [typora/typora-issues#4974]
When I export to PDF, I always get a complaint about background color. See screenshot. This persists whether I have dark mode enabled or disabled (Using WIn10), and regardless of the theme I'm using.

![image](https://user-images.githubusercontent.com/61975293/147971556-fced75a6-b3dd-465a-ac47-3f1342c26100.png)

**Comment by abnerlee** [comment]
We detect dark theme based on the background color of `HTML` tag.

> and regardless of the theme I'm using.

Which theme are you using? Does this occur for light built-in themes?

**Comment by driesmoors** [comment]
Using: Typora version 1.0.3
Attempted themes: Vue, Law, Whitey, Github.

Would it be a possibility to have an option to just go ahead and ignore any background colour?
