### ISSUE TITLE
Exported PDFs have content (images and text) cut in half across pages

### ISSUE THREAD

**Issue by mikeckennedy** [typora/typora-issues#4976]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

When exporting PDF content, images and even sentences are cut in half, split across pages.

**To Reproduce**
1. Create a multi-page markdown file
2. Go to File > Export > PDF
3. Notice there are sentences and images cut in half:

## Example 1:

<img width="576" alt="cut1" src="https://user-images.githubusercontent.com/2035561/148117406-d19acef2-a69a-4c86-8400-f55c4792b5dd.png">

## Example 2:

<img width="460" alt="cut2" src="https://user-images.githubusercontent.com/2035561/148117422-301d52e6-3306-4b4e-bd6a-4ef2ab1b48ac.png">

## Example 3
<img width="551" alt="cut3" src="https://user-images.githubusercontent.com/2035561/148117433-2c62cd77-cd24-458a-8b0f-b9db2889eb12.png">

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS Monterey

**Typora Version**
- Version: 1.0.5

**Comment by abnerlee** [comment]
Could you email us the sample md file.

And if you export to HTML, open in Safari and print, does this happens too?

**Comment by mikeckennedy** [comment]
Thanks @abnerlee I'd be happy to email a PDF. This is copyrighted material I'd rather not upload to GitHub. :) Can you connect with me, my email is on my profile: https://github.com/mikeckennedy

I have also found a bizarre twist. If I generate the PDF using the nightly theme, it comes out perfectly. But if I use the github theme for a light-colored version, it generates the cutoff pages. So it oddly has something to do with themes.

**Comment by mikeckennedy** [comment]
Or just share your email here and I'll start the conversation.

**Comment by abnerlee** [comment]
@mikeckennedy sorry for late, could you contact <hi@typora.io> ?

**Comment by han-yan01** [comment]
Had the same issue, any fix?

**Comment by petejodo** [comment]
Also seeing this issue

**Comment by OamIcs** [comment]
Same issue

**Comment by WeihangGuo** [comment]
same issue

**Comment by hazugi2004** [comment]
same issue
