### ISSUE TITLE
Typora crashes several times every day

### ISSUE THREAD

**Issue by christinerose** [typora/typora-issues#4979]
- [X] Searched existing issues to avoid creating duplicates.
- [X] Searched http://support.typora.io/

----

**Describe the bug**
Typora crashes several times a day after I purchased the license. It's very annoying and interrupts my workflow. 

**Expected behavior**
Not repeatedly crashing

**Desktop (please complete the following information):**
 - OS: macOS Monterey, 12.1; Apple M1 chip

**Typora Version**
Version 1.0.3 (5993)

**Comment by abnerlee** [comment]
Please use v1.0.5 instead
