### ISSUE TITLE
Code fence auto indent and Tab indent

### ISSUE THREAD

**Issue by iamswf** [typora/typora-issues#498]
Hi. I found that when coding in javascript in code fence, the auto indent seems to be 2 spaces. How can I customize the auto indent to be 4 spaces? And another question, how can I set the Tab indent to be 4 spaces? Thanks.

**Comment by pengbill** [comment]
Hi bro, have you figure out this issue? 

I found the same case in ```Java``` code fence.

According to [CodeMirror](http://codemirror.net/doc/manual.html#config)
> indentUnit: integer
> How many spaces a block (whatever that means in the edited language) should be indented. The default is 2.

So I think this could be figured by modify a specific preference file. I tried to search any possible file to change the default Tab indent and auto indent.

However, nothing help yet.

**Comment by abnerlee** [comment]
You should expose the "indent side" option of codemirror in future updates.

**Comment by pjeby** [comment]
I am now having this issue with PHP and Go code as well.  This is especially problematic for Go since the language requires tabs, not spaces, and the PHP standard for many projects is tabs as well.   (This is important for me since I'm actually extracting runnable code from my code blocks, and use Typora to write it as well.)

**Comment by pjeby** [comment]
It looks like [these settings](https://codemirror.net/doc/manual.html#config) in CodeMirror are what determine the indentation.  (Specifically, indentUnit, smartIndent, tabSize, and indentWithTabs.) Exposing them -- even if only via the "advanced" JSON-based settings -- would allow those of us who *do* use Typora as a code editor to tune these settings to our needs.

**Comment by abnerlee** [comment]
Added option for "Indent Size for Code"

**Comment by VinQin** [comment]
Hi, has this function been implemented?

**Comment by abnerlee** [comment]
Yes, but only for code fences and source code mode

**Comment by alaneuler** [comment]
Hi, can you guys add an option for tab indentation instead of space indentation?

**Comment by thgdc** [comment]
> Yes, but only for code fences and source code mode

I would love being able to change tab size for 'plain text' too, is it possible? Sometimes working with subtopics in my notes leaves a lot of empty and usuless spaces

**Comment by rhiswell** [comment]
Could we set tab size greater than 5 in code block? Like 8?

![image](https://user-images.githubusercontent.com/7373042/79690020-e35f6900-828a-11ea-9a3b-6bbfd15e8333.png)

**Comment by scruel** [comment]
> Yes, but only for code fences and source code mode

But I still got tabs rather than spaces after "Tab" pressed.

**Comment by abnerlee** [comment]
put into #579

**Comment by scruel** [comment]
@lhsaq2009 windows 震怒
