### ISSUE TITLE
Export Settings, css issues

### ISSUE THREAD

**Issue by askxue** [typora/typora-issues#4985]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
偏好设置 → 导出 → 导出详情 背景颜色变量引用错了。
我觉得更好的是引用`--bg-color`，和主色调保持一致。
其他设置栏目，没有发现问题。目前只有`导出`功能详情设置这里。

**截图**
![image](https://user-images.githubusercontent.com/90428956/148485982-782b97fd-8351-43ea-b1e9-3f5e7217b218.png)

**Typora Version**
1.0.3

**Comment by abnerlee** [comment]
I't a style preference, you can customize as you want
