### ISSUE TITLE
Perfect storm leads to complete loss of important file

### ISSUE THREAD

**Issue by pconrad-fb** [typora/typora-issues#4986]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I hit the "lost my clipboard" bug, but because autosave also failed I lost everything

**To Reproduce**
1. Before a meeting, I created a file and renamed it from "Untitled" to "Meeting-notes" at 7:58 AM
2. I typed like crazy during the meeting. I didn't notice that when you create a new file and rename it, it doesn't focus that file, so you end up typing in a random file. I ended up in a file called Untitled.
3. I did other work and left Typora alone.
4. I noticed that all my notes were in a file called Untitled, not the Meeting-notes file, so I cut from Untitled but lost the clipboard when I tried to paste into Meeting-notes. And of course I had discarded the file (because I have my clipboard, right?).
5. I work in a Dropbox folder, so I can see a version history of every change to the file with a granularity of 5 minutes... but not during the time I was typing in the meeting and not when I copied or pasted. 

In other words, I have:

- Dropbox sees I created a file and renamed it to Meeting-notes at 7:58 AM
- Dropbox sees I have another blank copy of the file at 1:55 PM when I lost my clipboard
- Dropbox sees that I have spent some time trying to re-type what I remember, with a granularity of every 5 minutes
- Dropbox sees nothing from 7:58 AM (before I took notes) to 1:55 PM (when I lost the clipboard)

So, three things happened:

- Typora had me editing in a different file than I expected
- No auto-save when I was taking notes (because it was in Untitled file for some reason)
- Lost clipboard (and no Undo)

**Expected behavior**
Expected behavior:

- Typora should have focused the file I created to take notes, not some other random Untitled file.
- Clipboard should be there. It goes away if you accidentally hit Ctrl-C again, even if nothing is selected. That's bad.
- Undo should work, including un-discarding the Untitled file I just Cut from. Discarding the file was my mistake, but it shouldn't be a one-way ticket to disaster.
- Auto-save should be there, whether I'm working in a named or untitled file.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit] Ubuntu 21.10

**Typora Version**
e.g: 0.10.11
1.0.3

**Additional context**

**Comment by abnerlee** [comment]
Hi,

1. even you discard it, there should be back ups, see https://support.typora.io/Version-Control/
2. we will fix the "ctrl+c" when nothing selected issue
3. It should be able to auto focus to the newly created file, unless your current untitled file has unsaved contents, could you provide a screencast that auto focus is not working?

**Comment by pconrad-fb** [comment]
Hi, 

1. Amazing amazing amazing. My whole weekend is saved! Thank you thank you. I can't tell you how much this means to me. I am so happy with Typora! 
2. Cool, good to hear.

https://user-images.githubusercontent.com/165230/148654644-0c4a8339-9af8-4fba-94f1-b780921e8f2c.mp4

3. Attached screencast. In a folder of files, I have one file selected. I right-click, "New file," rename file, and I'm still focused in the other file ("Downtoners") where I was before. The "Downtoners" file is an old file, no unsaved contents.

Seriously, thank you for the version control. I did not know about that killer feature. You saved me.

**Comment by abnerlee** [comment]
"2." is excepted because you are already on an opened file.
Sorry but I mean Typora will auto switch to new file if current file is **new blank untitled** file without any modifications.

So I'm asking if you can provide a screencast that auto focus is not working which makes you still writing on the "untitled" file, as your following description explained:

> Before a meeting, I created a file and renamed it from "Untitled" to "Meeting-notes" at 7:58 AM
> I typed like crazy during the meeting. I didn't notice that when you create a new file and rename it, it doesn't focus that file, so you end up typing in a random file. I ended up in a file called Untitled.

**Comment by pconrad-fb** [comment]
I'll have to test a little more, but here's my normal workflow.

1. I have a directory of files already, created by Typora when I took notes previously.
2. I right click, New File, and type a name.
3. I hit Enter.
4. At this point, I start typing. I'm expecting to be in the new file when I type.

What happened last week was that I probably had some other file selected, I clicked New File and typed a name, started typing, and only noticed at the end that I was in an Untitled file. I don't know if that file existed—but the reason I don't think it did is because if I created a new file it would have started with the name Untitled before I renamed it. Unless I'm incorrect. I don't think I was already on an opened file in that directory because I woke up, opened my computer, and created a new file to take notes. But I don't remember specifically.

I would think, if I'm already in an opened file, if I create a new file and rename it, then that would become the focused file. Is that wrong?

**Comment by pconrad-fb** [comment]
Did a little more testing.

1. Create a new folder. It focuses and highlights the name, so I type a name: "asdf"
2. Right click the new folder "asdf" and make a new file.
3. It highlights the name so I type a new name: "tytyty.md"
4. On the right-hand pane, the whole time, whatever file I had open before I created the new folder and file is still there.
5. On the left hand pane, the file I had open before (same file as 4) is still focused.
6. It does not matter if the file I had open before is empty or has content already.
7. It does not matter if the file I had open before is named "Untitled" or something else.
8. It does not matter if I create a new file in the same folder or a different folder.
9. It does not matter if I rename the new file or let the name stay "Untitled."

In all cases, if I create a new file, the focus remains in the previous file I was working on. If I want to work in the new file, I have to click it intentionally.

By itself, this is fine, and if that's the intended behavior, then you can close this bug, I guess. The reason I filed the bug is because I had a sequence of events I think  other people will fall into:

1. Type in the wrong file by mistake (no auto focus)
2. Lose clipboard
3. No undo to save clipboard (discarded file by mistake, can't get it back)
4. No previous versions saved to disk for Dropbox to help

I didn't know about the version control, which is truly an amazing killer feature. That saved my butt! But other people will go through the same trouble and come file bugs here, which is a pain for you :)

**Comment by abnerlee** [comment]
For untitled empty file, it should be fixed in 1.2.3

For other cases, refer #3794
