### ISSUE TITLE
[Feature] Mobile version

### ISSUE THREAD

**Issue by Blackhawke** [typora/typora-issues#4988]
Just wanted to let you guys know that, in my own searching for a good Markdown editor/viewer for my mobile devices I ran across several write-ups praising Typora for how good it is. Then, in the next sentence, they go on to lament than there is no mobile version either for Apple or Android.

I don't know if you're aware of how horrid the mobile space now is for Markdown users, but it's pretty bad. The developers of the new class of editors all seem to think they know more about how the user should be doing things than the user does. Some (most!) want to lock you into their file structure, making it impossible to work cross platform, either in the cloud or in a repo. Others insist you use the (apparently now holy) ``*.md`` file extension and have no provision for adding others, like the equally common ``*.mkd``. The developer of one claims their editor "is not a parser" despite the fact that it has both preview and code highlighting, resulting in inconsistent, often weird results. The only editor that does a good job on all fronts is now no longer supported. The developer -- a really nice dude! -- vanished just before COVID and hasn't been heard from since!

So yeah! Let me encourage you to add a mobile version of Typora to your todo list.

**Comment by abnerlee** [comment]
put into #525
