### ISSUE TITLE
Request: Disable physics package in Mathjax

### ISSUE THREAD

**Issue by aokanat** [typora/typora-issues#4989]
Hi,

I love this editor but there is one thing that really bugs me. Some latex macros are redefined by the `physics` package such as `\tan`, which changes the size of parentheses which come after it. This makes it so that if I use Typora to work on a file then the equations don't look the same as they do for my collaborators.

For this reason I would like to suggest that the `physics` package be removed because it breaks backwards compatibility with regular latex equations such as the rendering in other editors (e.g. visual studio code, obsidian, etc).

**Comment by abnerlee** [comment]
Could you provide a sample TeX code that renders different with or without physics package?

**Comment by aokanat** [comment]
Here is a simple example:

    $$
    \tan(\bigg|)
    $$

Without `physics`:

<img width="98" alt="Screen Shot 2022-01-09 at 6 51 28 PM" src="https://user-images.githubusercontent.com/97366811/148713079-ff9f0f7e-07bb-42d9-917f-c2a9f1b57a53.png">

With `physics`:

<img width="91" alt="Screen Shot 2022-01-09 at 6 52 00 PM" src="https://user-images.githubusercontent.com/97366811/148713103-cf778b5c-757d-412f-8979-6924d0d080f1.png">

Not only are the parentheses made larger but there is also more horizontal space after the `tan`.

**Comment by abnerlee** [comment]
should be supported in 1.1
