### ISSUE TITLE
bracket's problem of the mathematical formula 

### ISSUE THREAD

**Issue by abin1903** [typora/typora-issues#4992]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
Brackets are not rendering as expected.

**Expected behavior**
Under normal circumstances will automatically match the last closing parenthesis, not the first closing parenthesis

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/59110783/148797987-9f604ace-353e-43c2-881f-7b60d2a2c453.png)

**Desktop:**
 - OS: Windows 10 64bit

**Typora Version**
1.0.3

**Comment by abin1903** [comment]
Using "\qty"  seems to fix the issue
![image](https://user-images.githubusercontent.com/59110783/148801582-f146fc8f-0f3e-456e-b734-620130396d5f.png)

**Comment by abnerlee** [comment]
should be fixed in #4989

**Comment by abnerlee** [comment]
relates https://github.com/mathjax/MathJax/issues/2831

**Comment by abnerlee** [comment]
should be fixed in 1.1
