### ISSUE TITLE
[Bug/Feature] Mixed file/folder names in alphabetical order for Files Sidebar (not folders top)

### ISSUE THREAD

**Issue by fansch** [typora/typora-issues#4996]
Sorry several issues talk from the file list order, but I do not really know in which one I could add this: could it be possible to add a setting for sorting files and folder mixed instead of folders top?
So the order would be the same as the Finder's order,  as it was some Typora versions ago, that is why I have added the term Bug in the name of this issue.

This could be a first level solution for #3655 too.

Thanks.

<img width="1017" alt="Order" src="https://user-images.githubusercontent.com/10407746/149233577-43141736-138e-49bd-9852-931bd87a0186.png">

**Comment by abnerlee** [comment]
fixed in 1.4.4
