### ISSUE TITLE
rtf import

### ISSUE THREAD

**Issue by under-score** [typora/typora-issues#4997]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
rtf files are not recognized

**To Reproduce**
1. Install pandoc
2. Click on 'import'
4. 'rtf' files grayed out

**Expected behavior**
should be possible to select rtf files

**Screenshots / Screencasts**
NA

**Sample Markdown File**
NA

**Desktop (please complete the following information):**
 - OS: MacOS 11.6

**Typora Version**
e.g: 0.9

**Additional context**
NA

**Comment by abnerlee** [comment]
should be fixed in 1.1
