### ISSUE TITLE
[Feature] Support Markdown / HTML formatting for headers and footers

### ISSUE THREAD

**Issue by psoukie** [typora/typora-issues#4999]
It would be nice to allow Markdown and HTML formatting for headers and footers (currently escaped) and to document which CSS classes can be targeted in custom themes for styling headers and footers (for exporting). This way, it would be possible to include images (logos) and use specific styling in the header/footer.

**Comment by abnerlee** [comment]
They are plain text without styles, and should be simple enough to render compared with the possibilities of CSS styles.

so maybe it should be covered by #4713
