### ISSUE TITLE
Document which classes and IDs are used by Footnotes during export

### ISSUE THREAD

**Issue by psoukie** [typora/typora-issues#5000]
Currently, footnotes are exported in PDF on a separate page, without any title, and they are formatted with built-in styling.
It would be nice to document what classes / IDs are used when exporting footnotes into PDF so that users could inject a custom heading for the footnotes (using "Append Extra Content") and also customize their formatting in themes.

**Comment by abnerlee** [comment]
relates #131

It's like
```
<div class='footnotes-area'>
    <hr>
    <div class='footnote-line'>
        <span class='md-fn-count'>1</span> Explanation<a name='dfref-footnote1' href='#ref-footnote1' title='back to document' class='reversefootnote' id="dfref-footnote1">↩</a>
    </div>
    <div class='footnote-line'>
        <span class='md-fn-count'>2</span> Elaboration<a name='dfref-here2' href='#ref-here2' title='back to document' class='reversefootnote' id="dfref-here2">↩</a>
    </div>
</div>
```
