### ISSUE TITLE
Diagram Syntax Error

### ISSUE THREAD

**Issue by doncwilliam** [typora/typora-issues#5006]
I installed Typora 1.0.5 on Mac 12.1, and tried to use mermaid diagram or sequence diagram, but neither seems to work. For mermaid diagram, I copy and paste the example from your website, and this is the error I get:
<img width="969" alt="Screen Shot 2022-01-15 at 9 35 10 PM" src="https://user-images.githubusercontent.com/36778349/149645205-e46879fe-491f-4556-82ad-efdf3c30d643.png">

Do you know how I can make diagram work? Thanks!

**Comment by abnerlee** [comment]
Please do not include the ```mermaid and ending ```

**Comment by doncwilliam** [comment]
Great! It works now. Thanks!
