### ISSUE TITLE
Typo in Get Started notes

### ISSUE THREAD

**Issue by kkuhle** [typora/typora-issues#5012]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The new release I downloaded today has a typo, shows "Get Start"

![image](https://user-images.githubusercontent.com/11251306/150148351-7d1b3ebc-1e50-4b6e-9224-f53e1c99a76d.png)

**Comment by abnerlee** [comment]
should be fixed in 1.1
