### ISSUE TITLE
Workaround to embed images in Typora

### ISSUE THREAD

**Issue by kLvin** [typora/typora-issues#5017]
Hello, first of all, congratulations on a magnificent product.

I need to have images embedded in MD documents and I really like Typora, and we are thinking of buying some licenses for documentation. Therefore, I searched for a solution to automate this function.

I created a python script that returns the image in base64 and I call it from "Custom Command" when I run "Load Image", and it works more or less fine with small images.

The problem is when I try it with images with a size of, for example, 1MB. The action throws the following error:
- **Failed to upload image. Error Message: stdout maxBuffer length exceeded**

Another small issue occurs when a medium image (500Kb) is embedded. This works fine when the document is open in Chrome, but in Typora the base64 code is not hidden like other small images...

![Issue Typora](https://user-images.githubusercontent.com/5677347/150335726-995b032d-9310-47b9-9a94-845726e3a0da.PNG)

**To test....**

**Python script**
`import base64
import sys

with open(sys.argv[1], "rb") as img_file:
    b64_string = base64.b64encode(img_file.read())
#print (b64_string.decode())
print("file://data:image/png;base64,"+ b64_string.decode())
`

**Command**
`C:\Windows\py.exe C:\Repcon\Projects\ToBase64\ToBase64.py`

Thanks in advance and best rewards...

Carlos.C

**Comment by abnerlee** [comment]
It's part of #88

Currently typora does not provide base64 support since it makes the file very large.

Relates #622 about embed images.
