### ISSUE TITLE
Chinese characters lose bold/italic in exported PDF

### ISSUE THREAD

**Issue by JasonPhone** [typora/typora-issues#5018]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Chinese characters lose bold or italic font when exported into PDF document with built-in themes.

**To Reproduce**
1. Type some Chinese characters in bold or italic
2. Export into PDF
3. Open the PDF doc and see error

**Expected behavior**
It should be rendered like in the typora editor.

**Screenshots / Screencasts**
I tested four of the built-in themes. Typora says it does not support dark themes for PDF so there is not Night.

The result is correct when exporting into HTML doc.

The star beside word "italic" is caused by the cursor.

![whitely](https://user-images.githubusercontent.com/25930694/150500926-98373f28-e595-4aaa-bb69-fb818b9f2e76.png)

![pixyll](https://user-images.githubusercontent.com/25930694/150500930-dabb6bc8-1bd6-4107-b833-d1d8d99e86a2.png)

![newsprint](https://user-images.githubusercontent.com/25930694/150500931-e47fd38b-89e3-435f-b156-030886d15172.png)

![github](https://user-images.githubusercontent.com/25930694/150500933-8d4fbc32-324d-47c3-8b57-fa5a6cca5efd.png)

**Sample Markdown File**

```markdown
这里是**粗体**和*斜体*

this is **bold** and *italic*

```

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition, 21H1(19043.1466)

**Typora Version**
1.0.4

**Comment by abnerlee** [comment]
It's an upstream bug from Chromium

https://bugs.chromium.org/p/chromium/issues/detail?id=1188447&q=print%20bold%20chinese&can=2
https://bugs.chromium.org/p/chromium/issues/detail?id=1140832&q=print%20bold%20chinese&can=2

**Comment by JasonPhone** [comment]
Amazing it stays a year in chromium...
I'll take export to HTML as alternative.
