### ISSUE TITLE
attribute definitions on ER diagrams

### ISSUE THREAD

**Issue by wljg** [typora/typora-issues#5019]
**Describe the bug**
include an attribute definitions on ER diagrams stop rendering

**Sample Markdown File**
``` mermaid
erDiagram
    CUSTOMER ||--o{ ORDER : places
    CUSTOMER {
        string name
        string custNumber
        string sector
    }
    ORDER ||--|{ LINE-ITEM : contains
    ORDER {
        int orderNumber
        string deliveryAddress
    }
    LINE-ITEM {
        string productCode
        int quantity
        float pricePerUnit
    }
```

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.17

**Typora Version**
- 1.05
![screenshot](https://user-images.githubusercontent.com/8269484/150544024-d54e02a0-623e-4793-8873-a1d2cd99a537.png)

**Comment by abnerlee** [comment]
put into #1661
