### ISSUE TITLE
"Always on top" won't turn off

### ISSUE THREAD

**Issue by AlbertGrn** [typora/typora-issues#5021]
Env:
- macOS Big Sur v11.5.1 with M1
- Typora version 1.0.5 (6032)

I've found that the "Always on top" option can't quite be turned off again. After unticking it and then trying to move another window on top of Typora, it stays on top.
Restarting Typora fixes the issue however (regardless of whether the option was turned on or off).

**Comment by abnerlee** [comment]
should be fixed in 1.1
