### ISSUE TITLE
Using Typora as a snap renders pandoc useless

### ISSUE THREAD

**Issue by kfiresmith** [typora/typora-issues#5022]
Hi Folks,
Unless I misunderstand Snap, using Typora w/ Pandoc is currently impossible as filesystem access outside of /home is not possible with a Snap, so you can't provide a path to the OS installation of Pandoc.

Ideally, users should be warned or discouraged from using the Snap if they expect to need Pandoc, and binary installations should check if they are a snap before offering to set a pandoc path.

Or, guidance should be provided for handling a local installation of pandoc into the user's homedir.

**Comment by predr** [comment]
@abnerlee Pandoc is included in snap, it is failing for a different reason.

    $ snap run --shell typora
    $ $SNAP/usr/bin/pandoc --version
    pandoc 1.19.2.4
    Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
    Default user data directory: /home/predr/snap/typora/46/.pandoc
    Copyright (C) 2006-2016 John MacFarlane
    Web:  http://pandoc.org
    This is free software; see the source for copying conditions.
    There is no warranty, not even for merchantability or fitness
    for a particular purpose.

As you can see pandoc in snap is outdated. Updating snap core in `snapcraft.yaml` to core20 will pull newer pandoc packages.

```patch
...
-base: core18
+base: core20
...
-    extensions: [gnome-3-28]
+    extensions: [gnome-3-38]
...
-    build-snaps: [core18, gnome-3-28-1804]
+    build-snaps: [core20, gnome-3-38-2004]
...
```

Built a snap and tested exporting to epub file with newer pandoc version and it worked.

    $ snap run --shell typora_test
    $ $SNAP/usr/bin/pandoc --version
    pandoc 2.5
    Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
    Default user data directory: /home/predr/snap/typora_test/x1/.pandoc
    Copyright (C) 2006-2018 John MacFarlane
    Web:  http://pandoc.org
    This is free software; see the source for copying conditions.
    There is no warranty, not even for merchantability or fitness
    for a particular purpose.

I don't have a local pandoc installation.

    $ pandoc --version
    Command 'pandoc' not found, but can be installed with:
    sudo apt install pandoc

Default unchanged settings in `typora_test` snap.

![pandoc](https://user-images.githubusercontent.com/37021660/151726006-6c074139-8830-4142-b56c-ee25d66b217c.png)

Both Snap and Flatpak versions come with pandoc included in them and import/export should just work. Those plugs you added break the "security model" and updating snap core is the correct fix. Let me know if you have any questions.
