### ISSUE TITLE
PDF Export issue

### ISSUE THREAD

**Issue by P3anutSweet** [typora/typora-issues#5026]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----
 When exporting to pdf format, the underlines from subtitles always show up at the wrong place.

**Expected behavior**
The underlines should appear under the subtitles.

**Desktop (please complete the following information):**
 - OS: Macc os, arm, m1 max

**Typora Version**
e.g: 1.0.5(6032)

**Comment by abnerlee** [comment]
Could you provide a sample markdown file?

**Comment by P3anutSweet** [comment]
[test.pdf](https://github.com/typora/typora-issues/files/7935474/test.pdf)
[test.md](https://github.com/typora/typora-issues/files/7935475/test.md)
I think the issue might be related to code block

**Comment by abnerlee** [comment]
It works fine in my test. 

Which Typora version did you use and do you have custom CSS? Does export from Github theme works normal?
