### ISSUE TITLE
File Structure is suddenly incorrect, only showing certain files

### ISSUE THREAD

**Issue by frankhli843** [typora/typora-issues#5028]
- [Typora](https://user-images.githubusercontent.com/51806469/151150200-619f3576-523c-4944-b853-c9999ecf9aeb.png)
- [Actual file structure](https://user-images.githubusercontent.com/51806469/151150242-502f1032-c1ac-4f05-8ee7-a2f497acb4e1.png)
- Articles view seems to show list all the files though
- Seems to only occur when the font size is set to 11. See video below

https://user-images.githubusercontent.com/51806469/151150802-a146743c-8d35-47a9-be2f-9cb96ef546bf.mp4

**Comment by abnerlee** [comment]
fixed in 1.1
