### ISSUE TITLE
Can't create a new line from a code block

### ISSUE THREAD

**Issue by onnimonni** [typora/typora-issues#503]
I tried Typora with OSX and created a sample document and after I insert a code block with ``` and after that I can't create newlines under the code block.

<img width="649" alt="screen shot 2017-01-20 at 11 55 19 am" src="https://cloud.githubusercontent.com/assets/5691777/22144737/6d93704c-df07-11e6-9f8e-95876ed6cd50.png">

I would expect that **arrow down** would let me go under the code block but it didn't work.

I'm using version `0.9.9.8.9 (beta)`.

Thanks for your hard work. This seems clean and nice!

**Comment by abnerlee** [comment]
It seems OK in my testing

Press down arrow key will focus to next element/block.

For code fences, first focus to the language input, then focus to next line.

**Comment by onnimonni** [comment]
@abnerlee Yes it will focus to next element/block if there's one. But I'm talking about the situation where there's nothing under the code block.

Did you create the code block as the last line or into the middle of text:

https://gyazo.com/71d972d7a189a836c02084564c8c738f

**Comment by onnimonni** [comment]
**And one more correction:**
When I create a code block typora creates a new line automatically under the code block. Problem happens only if I accidentaly delete all newlines under the codeblock. 

If I save&close&reopen the file this problem goes away, still a bit annoying.
