### ISSUE TITLE
Multiple UTF-8 BOM file headers

### ISSUE THREAD

**Issue by BKrebser** [typora/typora-issues#5030]
We're using UTF-8 BOM encoded markdown files. Typora adds a new BOM header each time the document is saved.

File header before editing with Typora:
![image](https://user-images.githubusercontent.com/70293475/151192969-cb4a82cb-5fbc-410a-8490-66d3eab51d14.png)

File header after save:
![image](https://user-images.githubusercontent.com/70293475/151193161-e8108955-2757-4ebc-9c5c-2ba5d2ac8f01.png)

Additional three bytes containing the BOM are added with each save operation. The first line of a Markdown file with multiple BOM headers is not parsed corectly.

Typora version: 0.11.17 (beta)
OS: Windows 10 64Bit

**Comment by skaviouz** [comment]
I have the same results, same finding
Typora version: 1.0.3
OS: Windows 11 64bit

I would like to mention that I too have noticed this when I randomly clicked view source ( Control + / ) earlier today. Here is what It looks like from within the application. 
![image](https://user-images.githubusercontent.com/3837674/152453690-d65fc46f-b118-4ed8-999b-60867e3eb381.png)
I opened CI Hex Viewer here is my screenshot to confirm:
![image](https://user-images.githubusercontent.com/3837674/152454346-dee50eda-21fc-4382-93fe-da4eed3788cc.png)
This is what it should look like:
![image](https://user-images.githubusercontent.com/3837674/152454483-95bc3380-dd8e-498e-a377-5f4c961079dc.png)
