### ISSUE TITLE
[Feature] Update mermaid support from 8.8.3 to current stable

### ISSUE THREAD

**Issue by lunerfox** [typora/typora-issues#5032]
Many new features have been added to mermaid since the last update in 2020; Right now, some of the key features within graph and stateDiagrams (Direction, If statements...etc) do not work.

**Comment by ricetech** [comment]
To add to this, the "choice" function in Mermaid State Diagrams isn't working. I just tried using the example from the Mermaid docs and it didn't show the choice at all

**Comment by nheeren** [comment]
Would love to see [Entity Relationship Diagrams](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram) working too.

**Comment by ricetech** [comment]
Comments with `%%` also aren't working and just insert blocks as if they weren't commented out

**Comment by abnerlee** [comment]
put into #1661
