### ISSUE TITLE
[Feature] I need to support BASE64 encoded pictures

### ISSUE THREAD

**Issue by futz12** [typora/typora-issues#5036]
As you can see, can you add the ability to automatically encode the dragged-in picture as BASE64 instead of the picture address? This makes it easier to use documents on different devices without having to take some troublesome picture files with you.
Of course, it's best to have screenshots so that I can write articles easily.

**Comment by futz12** [comment]
By the way, this is machine translation
The following is the original text

如你所见，能不能加入能够把拖入的图片自动编码为BASE64的功能，而非是图片地址。这样可以更方便的将文档在不同设备上使用，而不用带着一些麻烦的图片文件。
当然最好是可以自带截图功能，这样我写起文章来会很方便的。

**Comment by abnerlee** [comment]
put into #88
