### ISSUE TITLE
Crash after creating footnote by clicking the 'undefined footnote' popup.

### ISSUE THREAD

**Issue by johannesdewit** [typora/typora-issues#5039]
- [x] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css. 
  *It cannot be reproduced everytime.*

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Typora crashes when using the link-like shortcut in the pop-up to define an undefined footnote. This does not happen every time, but it has on multiple occasions now. Please note that I am working on a document of around 3000 words on the 'Whitey' theme with around 20 footnotes.

**To Reproduce**
*I have <u>not</u> been able to reproduce it at will, but the crash only comes about after the following steps.*

1. Mark the footnote in the text. E.g. `[^16]`
2. Do not define the footnote manually, but hover the undefined footnote to get a pop-up which tells you the footnote is undefined and provides a link-like shortcut which prints the syntax required to define that specific note.
3. Click this link.
4. Start defining the footnote.
5. After a second or two, while defining the footnote, typora crashes.

**Desktop (please complete the following information):**
 - OS: MacOs Big Sur 11.6.2

**Typora Version**
1.0.5 (6032)

**Additional context**
I will add more info if the crash happens again.

**Comment by abnerlee** [comment]
Does this happen in 1.4.4?
