### ISSUE TITLE
 version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference (ubuntu14.04)

### ISSUE THREAD

**Issue by taozuoqiao** [typora/typora-issues#504]
When I started typora, I got the following error:

>/usr/share/typora/Typora: relocation error: /usr/share/typora/resources/app/node_modules/spellchecker/build/Release/spellchecker.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Could anyone help me out?

**Comment by woshigeshabiaaa** [comment]
Got the same problem, still struggling
anybody help? THX

**Comment by abnerlee** [comment]
Please refer 

http://stackoverflow.com/questions/36816570/glibcxx-3-4-21-not-defined-in-file-libstdc-so-6-with-link-time-reference

or 

http://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6/792471

Not sure if there's better solution to avoid this.

**Comment by taozuoqiao** [comment]
Sorry for answering so late. I have solved it by
```
npm install spellchecker
sudo cp  node_modules/spellchecker/build/Release/spellchecker.node \ /usr/share/typora/resources/app/node_modules/spellchecker/build/Release/
```
Since I have to replace the original `spellchecker.node` every time when typora  is upgraded, this method is little stupid.

**Comment by abnerlee** [comment]
I see, maybe we should compile Typora in ubuntu14.04 :joy:

**Comment by abnerlee** [comment]
@taozuoqiao Could you try update your gcc lib, by
```
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install build-essential
sudo apt-get install aptitude

sudo apt-get install libstdc++6
```
from https://askubuntu.com/questions/726539/sudo-apt-get-install-libstdc

**Comment by ybbbbt** [comment]
Try this. It works for me.
```
sudo apt install nodejs-legacy
sudo apt install npm
npm install spellchecker
sudo cp node_modules/spellchecker/build/Release/spellchecker.node  /usr/share/typora/resources/app/node_modules/spellchecker/build/Release/
```
from [http://blog.csdn.net/u014629875/article/details/53694656](url)

**Comment by chenchr** [comment]
It occurs to me too.  I resolve it by downgrade the libc++6 by 
```
sudo aptitude purge libstdc++6
```
from hints [here](https://ubuntuforums.org/showthread.php?t=1750891)

**Comment by ayushishara** [comment]
> When I started typora, I got the following error:
> 
> > /usr/share/typora/Typora: relocation error: /usr/share/typora/resources/app/node_modules/spellchecker/build/Release/spellchecker.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
> 
> Could anyone help me out?

apt-get install gcc-multilib
