### ISSUE TITLE
[Feature] article tag

### ISSUE THREAD

**Issue by Espoir999** [typora/typora-issues#5040]
typora 可以考虑支持每个文章添加标签的功能吗，搜索的时候先按标签搜索，然后按文章内容搜索。
Can typora consider supporting the feature of adding tags to each article? When searching, first search by tags, and then search by article content.

- view all tags (支持查看所有标签)

If not, please explain your thoughts。
Because when I search now, there are always some repeated keywords in other articles, so the search results are not what I want.

因为我现在搜索的时候，总是有一些其他文章的关键词重复，导致搜索到的结果不是想要的内容

**Comment by abnerlee** [comment]
#1393
