### ISSUE TITLE
Font Matter per document export on PDF not working

### ISSUE THREAD

**Issue by martinezpenya** [typora/typora-issues#5041]
Hi, I'm following instructions in https://support.typora.io/YAML/#export to add per document extra content to my header and add a cover to my HTML export, and works well using either `typora-append-head` or `append-head` variables in my font matter section (I don't know which are the differences between this two variables).
I'm also capable of adding this cover to my PDF exports using "Append Extra content" from the PDF export settings, but reading the "learn more..." (https://support.typora.io/Export/#add-custom-content-pdf) it refers to a `Append Extra Content` field.
Questions:
1-. Is it possible to add the extra content for PDF per document as the HTML content?
2.- This `Append Extra Content` field is also available for Font Matter variable?
3.- I'm not sure I understand correctly the meaning of the variables in (https://support.typora.io/YAML/#export) :
Is it the same `append-head` or `typora-append-head`?? why we need `typora-append-head-extra` and `typora-append-head` as documentations says one is for HTML and the other for PDF?
I dont' know why it works well on HTML and not in PDF.

**Comment by abnerlee** [comment]
1, 2
We do not support custom html inside md file for PDF export for security reason #2232
Could you write it in another user defined YAML filed then include it in export meta as variable and then include it in HTML via js https://support.typora.io/Export/#export-yaml-meta. Anyway, for security reason, you need to set it up by yourself so you are sure what will be included for export.

3
append-head or typora-append-head are same for Typora.
"typora-append-head" overwrites your settings in preferences panel.
"typora-append-head-extra" append content after your settings in preferences panel.
