### ISSUE TITLE
Escape character doesn't work when use before:: or after:: and convert .md to .pdf

### ISSUE THREAD

**Issue by OliverKung** [typora/typora-issues#5042]
In my .css file, I set the pesudo element of h5 like this:
> #write h5::before{
	counter-increment: tableHead;
	content: "TABLE "counter(tableHead,upper-roman)" \A";
	text-align: center;
}

Inside typora , this function works just fine, the results show like follow
![image](https://user-images.githubusercontent.com/43801635/152015803-3440cc32-91db-4ccd-9a21-d8b3959bf81a.png)
However, when use eport - pdf, the output shows like this
![image](https://user-images.githubusercontent.com/43801635/152015942-08fadf46-167e-40b2-9f42-957115485a23.png)

I think this might be a bug of the support of css pesudo element.

**Comment by abnerlee** [comment]
fixed in v1.5.x
