### ISSUE TITLE
Use relative path on append extra content PDF export

### ISSUE THREAD

**Issue by martinezpenya** [typora/typora-issues#5044]
I'm following [documentation](https://support.typora.io/Export/#add-custom-content-pdf) about adding a cover on pdf export, and tuned a little bit the HTML code to add an image in a div like this:
```html
<meta name="title" content="${title}">
<meta name="imgcover" content="${imgcover}">
<div id='_export_cover' style="height:100vh;">
<div id='_export_title' style="margin-top: 25%;text-align: center;font-size: 3rem;">
</div><img id="imgcover" style="display: block;margin-left: auto;margin-right: auto;width: 75%;"/></div>
<script>
    var $cover = document.querySelector("#_export_cover");
    var title = document.querySelector("meta[name='title']").getAttribute("content");
    var imgcover = document.querySelector("meta[name='imgcover']").getAttribute("content");
    document.body.insertBefore($cover, document.body.childNodes[0])
    $cover.querySelector("#_export_title").textContent = title;
    document.getElementById("imgcover").src=imgcover;
</script>
```
`imgcover` is a variable from front Matter, but it needs to be absolute path.
Is there any possibility to use a relative path o the `typora-root-url` variable or something similar to `${filename}`.
Thank you!.

**Comment by martinezpenya** [comment]
Adding some html tricks to my code I've found that typora is generating the export on `/tmp` path (i'm on linux machine).
So the setting `Default Folder for Exported File` has nothing to do with the export... because if I change `Auto` to `Same folder with current file` it continues generating file in `/tmp`, and I assume that lately is moved and renamed to the correct folder.
Is there any way to change that behaviour so it can found my image from `/assets` folder?
Thanks!

**Comment by abnerlee** [comment]
You should be able to get the absolute path from its relative path ${imgcover} and its base path ${currentPath} (https://support.typora.io/Export/#use-variables-in-export-config)

**Comment by martinezpenya** [comment]
Thank you, I've tested this... but it returns me the `path+filename+extension` so adding `+'/../assets/'` give me the folder where is my cover.
So this workaround solved my issue.
Thanxs!

**Comment by Papouchcom** [comment]
I was also looking for **how to insert a picture on the cover**. If anyone finds it useful, here is an example using the [currentFolder](https://support.typora.io/Export/#variables) variable:

```
<meta name="imgcover" content="${currentFolder}">
<div id="_export_cover">
  <img id="_export_logo" src="" width="100" height="100">
</div>
<script>
  var cover = document.querySelector("#_export_cover");
  var logo = document.querySelector("meta[name='imgcover']").getAttribute("content");
  document.body.insertBefore(cover, document.body.childNodes[0])
  cover.querySelector("#_export_logo").setAttribute("src", logo+"\\assets\\logo.png");
</script>
```

Obrázek je uložený ve složce se souborem `*.md/assets/logo.png`.
