### ISSUE TITLE
Cannot delete Task List items by mouse selection if at the beginning or end of selection, nor by Delete Line/Sentence command

### ISSUE THREAD

**Issue by loopernow** [typora/typora-issues#5047]
**Describe the bug**
Task list items `- [ ]` cannot be deleted by mouse selection if the task list item is on the first or last line in a mouse cursor selection. The items also cannot be deleted by using the Delete Line/Sentence menu command. Task list items `- [ ]` can only be deleted by using the Backspace or Delete keys or by including in the middle of a mouse selection.

**To Reproduce**
Select a block of text with your mouse that includes a task list item on the first or last line of the selection. Then, press Delete or Backspace on your keyboard. The task list item will not be deleted but everything else will be.

Alternately, invoke the Delete Line/Sentence command from the Edit > Delete Range menu, on a line where a task list item is located. Everything but the task list item on the line will be deleted. Then, invoke the Delete Line/Sentence command a second time. The line above the current line will be deleted, and the task list item will remain.

**Expected behavior**
Task list items should be mouse-selectable. Task list items should be deletable no matter where they are located in a block of selected text. Lines with only task list items should be deletable when invoking the Delete Line/Sentence command.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.0.3

**Comment by abnerlee** [comment]
duplicated with #2357
