### ISSUE TITLE
Cannot delete Task List items by Delete Line/Sentence command

### ISSUE THREAD

**Issue by loopernow** [typora/typora-issues#5048]
**Describe the bug**
Task list items `- [ ]` cannot be deleted by using the Delete Line/Sentence menu command.

**To Reproduce**
Invoke the Delete Line/Sentence command from the Edit > Delete Range menu on a line where a task list item is located. Everything but the task list item on the line will be deleted. Then, invoke the Delete Line/Sentence command a second time. The line above the current line will be deleted, and the task list item will remain.

**Expected behavior**
Lines with only task list items should be deletable when invoking the Delete Line/Sentence command.

**Desktop**:

OS: Windows 10 64bit

Typora Version
1.0.3

**Comment by abnerlee** [comment]
1.1 will follow spec in https://support.typora.io/Delete-Range/

**Comment by abnerlee** [comment]
fixed in 1.3.6
