### ISSUE TITLE
The download site cannot be accessed

### ISSUE THREAD

**Issue by ctrlwin** [typora/typora-issues#5052]
![001](https://user-images.githubusercontent.com/47913236/153116972-f160c900-9748-4d8e-b20d-4c2c6222c6d4.png)
As shown, the download url cannot be accessed

**Comment by abnerlee** [comment]
Use proxy or https://typoraio.cn

**Comment by dongbingliu** [comment]
但每次自动弹出来的升级也都是国际版的下载链接:
https://download.typora.io/windows/typora-setup-x64-1.2.5.exe

**Comment by abnerlee** [comment]
需要在控制面板中启用 “使用国内服务器”
