### ISSUE TITLE
Error on auto-update (cannot update)

### ISSUE THREAD

**Issue by smiffytech** [typora/typora-issues#5054]
![Screen Shot 2022-02-10 at 08 37 17](https://user-images.githubusercontent.com/4452562/153298920-5d880ff5-0d24-4d0a-862f-69558f07600b.png)

Typora 1.0.3 (5993) on macOS 10.15.7

I wasn't actually doing anything at the time, but just had the following dialogue appear, per screenshot.

**Auto-update not configured**
For security reasons, updates to Typora need to be
served over HTTPS and/or signed with an EdDSA key.
See https://sparkle-project.org/documentation/ for
more information.

I get the same error if I try to select Typora -> Check for updates.

**Comment by abnerlee** [comment]
#4910
