### ISSUE TITLE
Bouncing on the last line with auto save

### ISSUE THREAD

**Issue by snarglebritchet** [typora/typora-issues#5055]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
When typing at the last line of a file where text fills the screen enough to introduce a scroll bar, with auto save enabled, the view bounces around distractingly. Waiting a moment for the auto save to run and then resuming typing, bouncing is stopped. This may be because the auto save added a blank line at the end of the file and it is no longer the last line.

**To Reproduce**

1. Enable auto save
2. Create a new document
3. Save it with a name
4. Type or paste enough text so that a scroll bar appears because it is longer than one screen
5. Go to the end of the last paragraph, hit enter to start a new paragraph, and type words without pausing
6. Observe bouncing
7. Pause and count to five
8. Type words
9. Observe no bouncing

**Expected behavior**
When typing at the last line of the file, typing should still be smooth and the view should not bounce.

**Sample Markdown File**
Any text will do.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 21.10 (Xubuntu, XFCE)

**Typora Version**
1.0.4

**Comment by abnerlee** [comment]
Possible to attach a screencast? It works fine in my test

**Comment by snarglebritchet** [comment]
https://user-images.githubusercontent.com/38690/153753831-7d36d374-684a-4e04-9455-f5b8f12ad63d.mp4

**Comment by abnerlee** [comment]
Still happens in 1.1.5?

**Comment by snarglebritchet** [comment]
Seems fixed in 1.1.5
