### ISSUE TITLE
Allow user to set image path with forward slash [Feature]

### ISSUE THREAD

**Issue by tomasrei** [typora/typora-issues#5056]
Hi, when drag-dropping images, the path is written as C:\Users\...\, but C:/Users/tomas/ is needed for pandoc to work.  I don't use Typora to convert md to pdf. I am on windows 11 and typora 1.0.3.

Thanks!

**Comment by abnerlee** [comment]
Did you try upgrade Pandoc? I think they use C:\USers\... like https://github.com/jgm/pandoc/issues/6761#issuecomment-713276383
