### ISSUE TITLE
Mermaid sequenceDiagram generates error

### ISSUE THREAD

**Issue by pstoehr** [typora/typora-issues#5057]
**Describe the bug**
An example right from the mermaid documentation generates an error
https://mermaid-js.github.io/mermaid/#/sequenceDiagram

**To Reproduce**
add 
```mermaid
 sequenceDiagram
    actor Alice
    actor Bob
    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice
```
to an existing document

**Expected behavior**
A diagram should be drawn

**Screenshots / Screencasts**
<img width="1226" alt="Bildschirmfoto 2022-02-10 um 16 51 36" src="https://user-images.githubusercontent.com/14542721/153444568-ff2e1295-3c66-4b34-828e-e00c70d2d6f6.png">

**Sample Markdown File**
[error_mermaid.md](https://github.com/typora/typora-issues/files/8042369/error_mermaid.md)

**Desktop (please complete the following information):**
 - Mac OS X 12.2

**Typora Version**
Version 1.0.5 (6032)

**Additional context**

**Comment by abnerlee** [comment]
Put into #1661

Currently Typora uses mermaid 8.8,3 which actor is not supported yet, please use participant like https://github.com/mermaidjs/mermaid-gitbook/blob/master/content/sequenceDiagram.md
