### ISSUE TITLE
Cannot load uploaded image from github API

### ISSUE THREAD

**Issue by Losiyu** [typora/typora-issues#5060]
Using Picgo-Core(cmd) version
Problem: can upload, test success. Cannot load images when reopening Typora. 
I test it in the preference again when I could not load images, it was still successful.
Github keys setting:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/55306639/153691367-0539f283-f551-47b5-b432-713c9f904852.png">
picgo config (I havereplaced usernanem, and token there)
<img width="295" alt="image" src="https://user-images.githubusercontent.com/55306639/153691562-700633af-e377-46a3-99fa-cdd70d63dfef.png">

**Comment by abnerlee** [comment]
1. Can typora access Github, like loading this image `![](https://user-images.githubusercontent.com/55306639/153691367-0539f283-f551-47b5-b432-713c9f904852.png)`
2. Does your repo or image can be accessed publicly? Would you share one image address?

**Comment by Losiyu** [comment]
My image bed repo is private

This is an invalid image link, it shows 404 not found.
https://raw.githubusercontent.com/Losiyu/image-bed/master/51874082159_de4f6107b5_m.jpg?token=ANF6TD3MHBAKZF2M3FWOUJTCBMXSM


I tried again to do the who process:
1. Test upload function in Setting. Success
2. Upload a local image. Success
3. Reopen Typora, the image is work by using a remote link Success
4. Reopen Typora after 10 minutes. The link could not work.  Fail

Thanks for your help!

**Comment by abnerlee** [comment]
> My image bed repo is private

You will need to make it public since Typora does not have authentication function that allows you to "login" your github account to access yor repo.
