### ISSUE TITLE
I cannot activate Typora.This license code has been used with a different email address.

### ISSUE THREAD

**Issue by liunnn1994** [typora/typora-issues#5063]
# I cannot activate Typora on my second device.
I have already activated Typora in one pc, but when I try activating Typora on another pc I got this issue: `This license code has been used with a different email address. `

**Comment by asdjgfr** [comment]
send email solved

**Comment by JiafanL777777** [comment]
Why didn't my email work? How was it specifically resolved?

**Comment by RaizielSoulwareOS** [comment]
Same issue. I cant see how this was solved. Help?
