### ISSUE TITLE
Typora export PDF bottom margins and top margins too small for new pages

### ISSUE THREAD

**Issue by chrizbee** [typora/typora-issues#5065]
**Describe the bug**
When exporting a markdown file without any page breaks to pdf
- all new pages will have a very small top margin (except page 1)
- all pages will have a very small bottom margin

The pdf export margins are set to default.

**To Reproduce**
1. Go to https://www.loremipsum.de/index_en.html
2. Generate 1000 words and copy to empty Typora
3. Export to pdf
4. Open pdf and check first page break

**Expected behavior**
I expect the second page top margin to be the same as the first page top margin.
No matter what I set for "Margin Top" in Typora.

**Screenshots / Screencasts**
![pagecomp](https://user-images.githubusercontent.com/35270845/154222080-07d67e42-76fa-4255-9a6c-f693268058a3.png)

**Desktop**
OS: Windows 10 64bit and Windows 11 64bit

**Typora Version**
Typora 1.0.4 to 1.2.4

**Comment by abnerlee** [comment]
fixed in v1.5.x
