### ISSUE TITLE
[Feature] Document title view separate from file system

### ISSUE THREAD

**Issue by moksamedia** [typora/typora-issues#5066]
It would be really nice to have a way to title documents separate from the filename and to be able to re-arrange them in a list in arbitrary order. Maybe titling the flies by adding some kind of metadata block at the top of the file and keeping track of sort order there as well? It just would be super cool to separate title and order from the filename itself.

Thanks for a great product!

Andrew

**Comment by abnerlee** [comment]
There would be no enough space for title bar to show both file name and a different file title, and potentially a file path if file name / title is same.

You could set different title in meta block or just treat the first H1 as file title, but you may still need to find the file in finder / explorer based on its file name. 

I think it make things more complicated for end users since they need to deal with both.

**Comment by moksamedia** [comment]
I use Typora to do fiction and non-fiction writing and I use different files to organize my project. I wrote a similar program many years ago on OSX that had this and it was super helpful. I was imagining it as a separate structure from the file tree. You already have "Files" and "Outline." You're right that it would clutter things to try and fit it somehow into the "Files" side view. But there could be a third one that displays the files in a directory according to metadata. 

The use is that when I am working on a project, it would be very helpful for me to be able to have the files given more descriptive names than the file name and to be able to re-order them. Say, for example, I have a book I'm working on and I want to give the files a title of each chapter and order them appropriately without having to change the filename or number and re-number the files to force a sorting. 

See for example the screenshot below of a current project. There's no way for me to order these files in a way that actually suits the structure of my writing project (except maybe numbering them, but then I'd have to renumber then each time I wanted to change the order).

![Screenshot from 2022-02-17 20-06-00](https://user-images.githubusercontent.com/1304311/154615767-64f57460-c3ce-4ea1-a19e-25bf63a02491.png)

**Comment by moksamedia** [comment]
If you have any interest in me contributing I could mock up a version of what I mean. Regardless, thanks again for a very helpful program.

**Comment by abnerlee** [comment]
I see, so is #3655 what you actually want?

**Comment by moksamedia** [comment]
#3655 is pretty close. Close enough, really. The only difference would be, in my suggestion, the ability to rename files based on some metadata in the file. But mostly it's the custom ordering that would be the biggest help.
