### ISSUE TITLE
File tree is re-nested when clicking file in subfolder

### ISSUE THREAD

**Issue by lieszkol** [typora/typora-issues#5070]
When opening a file in a subfolder-of-a-subfolder, the file tree is refreshed and the subfolder becomes the new root. Super, super frustrating. I've looked through the issues and haven't found a similar issue, but I may be overlooking something. 

https://user-images.githubusercontent.com/16566226/154689798-898180e8-a81c-4eae-ac43-b18ccfdc7fde.mp4

OS: Windows 7
Typora version 1.1.3 as well as 1.1.2

Interestingly enough the issue does not manifest itself when Typora is first opened up. You have to start Typora, and then use select a location from the list of recent folders at the bottom of the "File Tree" pane for this to happen. It does not seem to matter where the folder is or what the file names are. If I start Typora and open folder A, it will work. If I then open up folder B, the problem is there. Same thing backwards. If I start Typora and open folder B it works. I then open folder A, the bug is there.

Also, the bug does not manifest itself if I use the FILE menu, so File → Open Recent. Only if I use the pop-up recent folders list at the bottom of the File Tree. 

In any case, thank you for Typora!

**Comment by joel-porquet** [comment]
I am also experiencing this new behavior with 1.1.3 on Linux, which is very frustrating.

**Comment by Flyour** [comment]
File->Preference setting -> On Launch ， select " Opoen Custom folder" can solve this problem。

**Comment by lieszkol** [comment]
No, it does not, and I don't think you've understood the issue. Please reread the description.

**Comment by abnerlee** [comment]
What about 1.2.3?
