### ISSUE TITLE
Manage my license infinite loop

### ISSUE THREAD

**Issue by JayToltTech** [typora/typora-issues#5072]
<img width="595" alt="Screen Shot 2022-02-18 at 10 37 31 AM" src="https://user-images.githubusercontent.com/69092530/154742841-f91c30be-3f77-4c8b-a293-b661907df1e8.png">

**Describe the bug**
I keep getting this loop after clicking on the special link in the email

**Desktop (please complete the following information):**
 - OS: OSX, Brave Browser

**Typora Version**
e.g: 1.1.3

**Comment by JayToltTech** [comment]
Was within 24 hrs.  Tried multiple tokens, so that wasn’t the issue.

**Comment by abnerlee** [comment]
Could you share you mail address to hi@typora ?
