### ISSUE TITLE
File link anchor breaks if the header starts with number and dot.

### ISSUE THREAD

**Issue by 1999FordFocus** [typora/typora-issues#5075]
**Bug details**
When using a file link anchor, you cannot even open the file link itself if that anchor starts with a number and a dot. When clicking on it, Typora will display a popup window with the error message "Cannot open location".

**To Reproduce**
File link anchor:`[test file link anchor](./test.md#1.-test-file-link-anchor)`
header in test.md: `## 1. test file link anchor`

**OS**
macOS Monterey

**Typora Version**
1.1.3

**Comment by 1999FordFocus** [comment]
Hi @abnerlee, would you mind fixing it in your next release.
I really really need this feature.🙏🙏🙏

**Comment by abnerlee** [comment]
You could try use `[test file link anchor](./test.md#1-test-file-link-anchor)` for workaround.

**Comment by abnerlee** [comment]
fixed in 1.3.6
