### ISSUE TITLE
Problem exporting PDF file

### ISSUE THREAD

**Issue by ihechikara** [typora/typora-issues#5076]
I searched but did not find a similar problem. I get the error message below when I try to export my .md file to PDF format:

**EPERM: operation not permitted, open 'C:\Users\IHECHIKARA\Desktop\python\python-basics.pdf'*
![Screenshot (249)](https://user-images.githubusercontent.com/54513385/154834782-61760b1f-44ef-48b0-8e35-3e778d7bf434.png)
*

The support page I was directed to was not so helpful. Please how do I fix this?

**Comment by abnerlee** [comment]
What about export to other location?

And Typora have permission to save file to that folder?
