### ISSUE TITLE
ubuntu20.04 case high CPU for gnome-shell

### ISSUE THREAD

**Issue by noyidoit** [typora/typora-issues#5080]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Ubuntu 20.04 编辑保存在桌面的文档会导致CPU飙升，导致卡顿的具体进程为gnome-shell

**To Reproduce**
1. 打开一个保存在桌面的文件
2. 打开自动保存
3. 输入字符，出现卡顿

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS 64bit
 - Gnome version: 3.36.8
 - Windowing system: X11

**Typora Version**
1.0.4

**Comment by abnerlee** [comment]
gnome-shell is not controlled by Typora....

Anyway, does this happen for v1.1.5?

**Comment by noyidoit** [comment]
sry, it's seems the problems is of gnome

by the way, just watched [typora official site](https://typora.io/#linux), it seems 1.0.4 is the newest version under linux

> https://download.typora.io.sgp1.digitaloceanspaces.com/linux/typora_1.0.4_amd64.deb
