### ISSUE TITLE
Using winget (on win 11) to update typora throws error on has not matching

### ISSUE THREAD

**Issue by nanshaqundao** [typora/typora-issues#5081]
- [x ] Searched existing issues to avoid creating duplicates.
----

**Describe the bug**
Using winget (on win 11) to update typora throws error on has not matching

Found Typora [Typora.Typora] Version 1.1.4
Found  [Typora.Typora] Version 1.1.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://typora.io/windows/typora-setup-x64.exe
  ██████████████████████████████  68.0 MB / 68.0 MB
Installer hash does not match; to override this check use --force

**Comment by abnerlee** [comment]
https://github.com/microsoft/winget-pkgs/pull/47634 fixes it.
