### ISSUE TITLE
typora alerts dialog saying you don't have permission to save file the file is locked

### ISSUE THREAD

**Issue by feiyuerenhai** [typora/typora-issues#5082]
it is weird, I have purchased a license, and the dialog still pops up !!! 😠
--------------------------------------------------------------------

**Describe the bug**

why is my typora popping up "you don't have permission to save file, the file is locked? ", is it because the free trail has expired? i have reverted to beta versions, and the popper still existes when saving files, which made it impossible to save files, do I have to buy a license in order to use typora? is this by design, or is it a bug ? 

what I have tried:
1, save the exact file with other editors, and all work fine;
2, give typora full disk access, and the popping up still exists.

**To Reproduce**
1. I have been working with beta versions;
2. the app auto installed 1.0.0+ version someday;
3. I reverted to beta versions;
4. after a few days, the dialog shows up when saving files

**Expected behavior**
is this by design or a bug ?

**Screenshots / Screencasts**

<img width="260" alt="image" src="https://user-images.githubusercontent.com/15189212/155047338-7034c78f-dcdf-4a9b-8d47-5925b9cbfb9c.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/15189212/155047358-fc464018-5ca6-4a91-b082-5a973be5e16d.png">

<img width="165" alt="image" src="https://user-images.githubusercontent.com/15189212/155049543-a6b05636-88d5-422d-ba93-6a6909bdc7de.png">

<img width="533" alt="image" src="https://user-images.githubusercontent.com/15189212/155050344-627eb309-2a65-4f08-acd8-da81c1b77e1a.png">

**Desktop: **
 - OS: [MacOS big sur, 11.6.1]

**Typora Version**
Version 0.11.18 (5941)

**Additional context**
Company Computer

**Comment by abnerlee** [comment]
The permission is not managed by Typora.

Please try disable and remove Typora from Full Disk Access, then enable Typora for Full Disk Access again.
And please confirm Typora have the permission for your folder by checking the "Files and Folder" Tab

Please check a file or folder is locked or not in this way: https://osxdaily.com/2010/08/11/lock-files-and-folders-in-mac-os-x/

**Comment by chris-pn-dev** [comment]
> The permission is not managed by Typora.
> 
> Please try disable and remove Typora from Full Disk Access, then enable Typora for Full Disk Access again. And please confirm Typora have the permission for your folder by checking the "Files and Folder" Tab
> 
> Please check a file or folder is locked or not in this way: https://osxdaily.com/2010/08/11/lock-files-and-folders-in-mac-os-x/

I've also met this issue! I've tried the way provided by @abnerlee to re-enable typora for Full Disk Access, and I've checked the file is not locked.
The issue doesn't happend in all of my md files, but some of my md files...
I've also purchased a license...
Can you give some sugguestion or what should I provide for root cause this isse?

**Comment by izhangxb** [comment]
Same problem.

**Comment by abnerlee** [comment]
> The issue doesn't happend in all of my md files, but some of my md files...

Your md file under which path cannot be saved? Can you edit them with TextEdit.app and save them in place?
