### ISSUE TITLE
Some Latex symbols are abnormal in version 1.1.5 of Windows, such as \cross \dot

### ISSUE THREAD

**Issue by lovewsy** [typora/typora-issues#5083]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
Latex symbols like \cross \dot can not be rendered.

**To Reproduce**
$\cross$ $\dot$

**Expected behavior**
\cross \dot of latex should be displayed.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/41018796/155054142-ef2374b8-7a97-4806-a9cc-e3c90b43fd58.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
   1.1.5

**Comment by abnerlee** [comment]
Please enable the physics package in Preferences Panel -> Markdown -> Math
