### ISSUE TITLE
Update confirmation fails.

### ISSUE THREAD

**Issue by takashin3391** [typora/typora-issues#5084]
When I click the "Check for updates" button in the Update item of the General tab of the Settings, an error window appears.
The message "unable to get local issuer certificate" is displayed.
How can I solve this problem?

I am using it in a proxy environment.
I have reset the proxy environment variables by running the following command.
> HTTP_PROXY =
> HTTPs_PROXY =
> NO_PROXY =

**Comment by abnerlee** [comment]
You could set `NODE_TLS_REJECT_UNAUTHORIZED=1` in env to ignore certificate errors

**Comment by takashin3391** [comment]
@abnerlee 
I set NODE_TLS_REJECT_UNAUTHORIZED=1, but it did not solve the problem.
I will not buy such incomplete software anymore.

**Comment by abnerlee** [comment]
Ohh, sorry, should be NODE_TLS_REJECT_UNAUTHORIZED=0
