### ISSUE TITLE
"Copy without Theme Styling" and Shift-Ctrl-End to select text — odd behavior

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#5085]
(Using Typora for Windows, 64-bit, version 1.1.5, but also present on older versions.)

If I use Ctrl-Shift-End to select all the text from the cursor to the end of the document, I am unable to choose "Copy without Theme Styling" from the Edit menu.

**But**, if I hold the Shift key and use the cursor keys to move back and forth one character, the "Copy without Theme Styling" option becomes available ... even if the same text is selected.

So, to copy to the end of a document, I use Ctrl-Shift-End (selects a big block of text), then Shift-Left, Shift-Right (to move the cursor back and forth), and _then_ I can use "Copy without Theme Styling."

Very odd. This is the case no matter where in the document I start from — the very beginning or somewhere in the middle. (It's also true for selecting text with Ctrl-Shift-Home.)

Any thoughts? Thanks!

**Comment by abnerlee** [comment]
fixed in 1.2.3
