### ISSUE TITLE
[Feature] Ability to Collapse and Expand Regions

### ISSUE THREAD

**Issue by ichwalik** [typora/typora-issues#5086]
### The Issue 
I find myself creating larger and larger documents with overwhelming amounts of information to navigate through. Using the sidebar and selecting items to jump to through the outline make navigating _to_ a section easier, but the information around the section may be crowded out by its neighbors (especially for smaller sections). 

Focus mode is a good step in this direction and serves its own purpose, but toggling visibility keeps the "out of sight, out of mind" information principle.

### The Offer
The ability to visually condense information through some sort of toggle not unlike accordions or other expand/collapse functionality. Similar to the ability within IDEs and text editors, the ability to collapse regions to visually condense information would be an amazing feature.

### The Code
An icon, such as an arrow, next to headers that appears  when hovering over the header (or just always on screen) would inform the user of this feature. The direction of the arrow  determines whether to expand or collapse the information within that heading. 

The source code view would display the tags that encompass what items live within that section with a Boolean attribute denoting the state of expanded or collapsed.

Understandably, it doesn't require some fancy animation to pull the content up and away, but just some way to toggle visibility.

**Comment by abnerlee** [comment]
duplicated with #499
