### ISSUE TITLE
The “History Releases” link on typora.io isn't working

### ISSUE THREAD

**Issue by Nicolapps** [typora/typora-issues#5087]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The *History Releases* link on https://typora.io leads to nothing.

**To Reproduce**
1. Go to https://typora.io
2. Click on the “History Releases” link in the page footer

**Expected behavior**
The link should lead to https://typora.io/releases/all. Currently, it leads nowhere (nothing happens when the link is clicked).

**Comment by abnerlee** [comment]
should be fixed

**Comment by Nicolapps** [comment]
Thank you!
