### ISSUE TITLE
Relative file paths in PDFs

### ISSUE THREAD

**Issue by ceckenrode** [typora/typora-issues#509]
### The Issue: 

* I had created a few markdown files that had links with relative paths between each other.

* **I converted the markdown to PDF, and none of my relative links worked anymore.**

* If I convert the markdown to HTML, the relative paths still work.

### My Workaround:

* I converted the .md file to HTML.

* Opened the HTML file in Google Chrome.

* Clicked File > Print and when presented with the next menu...

<img width="315" alt="screen shot 2017-01-25 at 2 02 05 pm" src="https://cloud.githubusercontent.com/assets/9385814/22304794/f1c6609c-e306-11e6-824b-9e8b2996f19a.png">

* I chose to save the document as a PDF.

Relative paths work in my PDF files using this workaround, but perhaps this could be implemented in Typora?

**Comment by abnerlee** [comment]
@ceckenrode I tested in Chrome, when print using Chrome, it will convert relative path to absolute one. We will also follow this approach since relative path (current spec) is not working in exported PDF.

**Comment by abnerlee** [comment]
Fixed in new release. 

Links will be converted to absolute one

**Comment by knennigtri** [comment]
@abnerlee I've been trying to use relative links in main.md but when I convert to PDF, it doesn't keep the links in the PDF.
- myfolder
   - main.md
     - in this file I used `[secondfile.pdf](file:///secondfile.pdf)`
   - main.pdf 
   - secondfile.md
   - secondfile.pdf

I've also tried
`[secondfile.pdf](file:./secondfile.pdf)`
`[secondfile.pdf](secondfile.pdf)`
`[secondfile.pdf](#secondfile.pdf)`
`[secondfile.pdf](file:///secondfile.pdf)`

Am I missing something? Thanks!

**Comment by abnerlee** [comment]
> when I convert to PDF, it doesn't keep the links in the PDF.

This is covered in #2546
