### ISSUE TITLE
SPELLCHECKER: User words are forgotten after version upgrade

### ISSUE THREAD

**Issue by be5invis** [typora/typora-issues#5090]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
When upgrading version, words added into the spellchecker dictionary are forgotten.

**To Reproduce**
1. Install an older version of Typora.
2. Type a word that is NOT a part of English. Add it into Dictionary so spell checker will no longer be saying it is a foreign word.
3. Upgrade version.
4. Open the MD file, type the same word again. Spell checker marked a spell error on it.

**Expected behavior**
The word will be recognized as a known word.

**Desktop (please complete the following information):**
 - OS: At least on Windows

**Typora Version**
1.*

**Comment by abnerlee** [comment]
Which Windows version? On Windows 10 the user words are managed by Windows. Please use Win + R, then input %APPDATA%\Microsoft\Spelling\en-US and use notepad or vs code to edit default.dic and see if your learnt words are there or not.

**Comment by abnerlee** [comment]
#5146
