### ISSUE TITLE
Optional title for image links uses no-break space instead of space

### ISSUE THREAD

**Issue by cdwilson** [typora/typora-issues#5091]
**Describe the bug**
When inserting an inline link to an image, Typora inserts a `U+00A0 : NO-BREAK SPACE [NBSP]` instead of a normal `U+0020 : SPACE [SP]`.  For example:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/14631/155436498-39e90155-53b9-4942-8551-3cfff65396d6.png">

This no-break space causes issues when rendering the image in other tools.  

For example, here is the same thing rendered by Hugo:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/14631/155436607-beeb5a0a-908c-4531-a895-bbd5cef2d17c.png">

And here it is again rendered in VS Code:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/14631/155436804-73ee99cf-6526-4ddd-86bf-97955931c654.png">

**To Reproduce**
1. Insert an image
2. Add an optional title
3. Open the document in another markdown preview tool

**Expected behavior**
Typora should use a a normal `U+0020 : SPACE [SP]` between the image URL and the optional title for images.

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1

**Typora Version**
Version 1.1.3 (6225)

**Comment by abnerlee** [comment]
How did you insert image title in Typora?

**Comment by cdwilson** [comment]
@abnerlee In the examples above, the "Written by hand" example was typed manually into the markdown source file in VS Code.  In the "Inserted by Typora" example, I first inserted an image using the Typora UI via `Format` ->  `Image` -> `Insert Image`, and then within the Typora UI, I type a space after the image URL, and then I type the optional title.

I've attached sample files which contain the difference in spaces when typed manually vs. inserted by Typora:

[test_image_manual.md](https://github.com/typora/typora-issues/files/8137018/test_image_manual.md)
[test_image_typora.md](https://github.com/typora/typora-issues/files/8137021/test_image_typora.md)

**Comment by abnerlee** [comment]
Hi, @cdwilson 

Do you have any custom CSS and are you using US English keyboard layout or other keyboard layouts?

Usually when user input a normal whitespace, it inserts a normal space, when user input a nbsp it inserts a nbsp, so we are still wondering how nbsp was inserted...

**Comment by cdwilson** [comment]
@abnerlee no, I'm not using any custom CSS and I am using a US english keyboard layout.

Interestingly, when I type a space in the alt text (between `[]`), Typora inserts a normal space, but when I type a space after the URL, Typora inserts a non-breaking space.  If I type the exact same line manually in VS Code, only normal spaces are inserted.  I'm only seeing the non-breaking space inserted by Typora in this one case.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/14631/155891819-a6668f81-afbf-4aa5-bb37-97091cac7f5b.png">

**Comment by dcadiou** [comment]
Hi.

I'm often facing similar problems with non breaking spaces (\xC2A0), not intentionally inserted, but present especially in heading chapters, for instance on `readme.md` files edited with Typora. When pushed on github for instance, headings with non breaking spaces are not recognized and displayed as normal text, not as title.

The only solution I found to replace all those undesired non breaking spaces is executing a command in my Linux shell, as the one below :  
```bash
sed -i "s/\xc2\xa0/\x20/g" readme.md
```

**Comment by abnerlee** [comment]
fixed in 1.2.3
