### ISSUE TITLE
Mermaid Gantt Chart Rendering bad

### ISSUE THREAD

**Issue by jmjw** [typora/typora-issues#5092]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Mermaid gantt chart rendering bad

**To Reproduce**
1. Enter diagram
2. See diagram rendered
3. 
**Expected behavior**
See screenshots
Especially the markers for the milestones are way off

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

Good rendering from Online Mermaid:
![good rendering from online mermaid](https://user-images.githubusercontent.com/1123294/155485407-e6d6374d-9500-4f70-848f-4bd8edda7f62.png)

Bad rendering in Typora
![bad rendering in Typora](https://user-images.githubusercontent.com/1123294/155485480-7d7b5874-08bb-4169-b41b-a403a533416c.png)

**Sample Markdown File**
```mermaid
gantt
dateFormat  YYYY-MM-DD
title All items changes to protect the innocent
excludes weekends

section Deliveries
Receive Cables            : milestone, cables, 2022-03-01, 1h
Receive Things x11    : milestone, recvx11, 2022-03-07, 1d
Receive Things x12    : milestone, recvx12, 2022-03-14, 1d
Receive Things x13    : milestone, recvx13, 2022-03-21, 1d

section Setup Connection
Connect A to B  : ab, after cables, 1d
Connect A to C  : ac, after cables ab, 1d

section Setup C
Move things         : mvwn, 2022-03-01, 1d
Install Recipe : recipe, after mvwn, 5d
   
section Connection
Connect x11 to C : x11, after recvx11, 1d
Connect x12 to C : x12, after recvx12, 1d
Connect x13 to C : x13, after recvx13, 1d

Run something                       : sth, after x13, 10d
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Typora Version**
1.1.5

**Additional context**
Diagram input:

**Comment by abnerlee** [comment]
put into #1661
