### ISSUE TITLE
The rendering of links and bold texts in footnotes is pretty laggy.

### ISSUE THREAD

**Issue by 1999FordFocus** [typora/typora-issues#5094]
**Bug Detail**
Restarting solves the problem.

https://user-images.githubusercontent.com/9652173/155735876-707e13d2-f828-48ca-8978-880dc0f87ef2.mp4

**OS**
macOS Monterey

**Typora Version**
1.1.5

**Comment by abnerlee** [comment]
What about built-in themes?

**Comment by 1999FordFocus** [comment]
I re-tested with Whitey, Night and Github, it performed the same as my previous video.

**Comment by abnerlee** [comment]
fixed in 1.3.6
