### ISSUE TITLE
Add Dockerfile syntax highlighting

### ISSUE THREAD

**Issue by keelung-yang** [typora/typora-issues#5095]
Such as in Github with \`\`\`dockerfile supported but \`\`\`docker
```dockerfile
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential bc && \
    rm -rf /var/lib/apt/lists/*
```
Or in vscode both \`\`\`docker and \`\`\`dockerfile supported
![image](https://user-images.githubusercontent.com/20385450/155746759-68f41c03-2b69-41a9-9e60-c296be7874e6.png)

For more information https://docs.docker.com/engine/reference/builder/

**Comment by abnerlee** [comment]
```docker is added in 1.2.x
