### ISSUE TITLE
"Reveal in Sidebar" doesn't work when Search is opened in sidebar

### ISSUE THREAD

**Issue by superb** [typora/typora-issues#5098]
**Describe the bug**
"Reveal in Sidebar" doesn't work when Search is opened in sidebar

**To Reproduce**
1. Open Sidebar, Click "Search" on top right corner, and search something
2. Open any file from the search results.
3. On the opened file, right click and choose "Reveal in Sidebar".
4. Nothing changed, Sidebar still shows search results.

**Expected behavior**
When user click "Reveal in Sidebar", it should close search if it's opened , and show file tree and highlight the selected file.

**Screenshots / Screencasts**
Should be easy to repro following the instructions.

**Sample Markdown File**
Any file can repro.

**Desktop (please complete the following information):**
 - OS:
 - macOS 12.2.1

**Typora Version**
1.1.5

**Additional context**

**Comment by abnerlee** [comment]
fixed in 1.2.3
