### ISSUE TITLE
Typora crashes when exporting to PDF in Windows 11

### ISSUE THREAD

**Issue by tomasrei** [typora/typora-issues#5099]
- [x ] Searched existing issues to avoid creating duplicates.

- [ x] Confirmed that it can be reproduced in built-in themes without customized css.

- [ x] Searched http://support.typora.io/

----

I try to export markdown file to pdf by clicking File>Export>PDF. It will instantly freeze. After a while (maybe one minute), it will unfreeze and I can export. I also notice the exporting to PDF in process animation in the main Typora window.

 OS: [Windows 11 Home, ver. 21H2, OS Build 22000.527]
Typora ver: [1.1.5] 

See attached typora.log and sample.md files.

[sample.md](https://github.com/typora/typora-issues/files/8160787/sample.md)
[typora.log](https://github.com/typora/typora-issues/files/8160788/typora.log)

**Comment by abnerlee** [comment]
relates #5037

**Comment by abnerlee** [comment]
May relates to https://github.com/electron/electron/issues/29572

So could you try Typora 1.2.5 (which uses Electron 17) or add a "Microsoft Print to PDF" printer (following https://answers.microsoft.com/en-us/windows/forum/all/how-to-add-or-reinstall-the-microsoft-pdf-printer/70377c34-e50a-42be-b9f3-92345d6e25df?auth=1) ?
