### ISSUE TITLE
Support other character encoding, not only UTF-8

### ISSUE THREAD

**Issue by nickbe** [typora/typora-issues#51]
I was working with a flat file cms system the other day when I suddenly realized that typora does not save files as utf8.

Even if the files were UTF before they're not anymore.

**Comment by abnerlee** [comment]
If so, it is a bug. Sorry for that

Could you tell me your OS version and Typora version?
Is possible, would you attach sample files before and after it is modified by typora.

**Comment by nickbe** [comment]
Latest Typora Version and Windows 7 / Windows 10.

[Test.txt](https://github.com/typora/typora-issues/files/115485/Test.txt)

Attached text was created with scite.
When using the file with other programs/systems like 'GRAV' CMS, Visual Studio or whatever everyting works fine.
When opening in Typora you don't see german Umlauts anymore.
When editing the file in Typora, writing german umlauts then everything seems fine, but in fact the files cannot be used by other systems anymore due to the incorrect interpretation of the umlauts.

**Comment by waahto** [comment]
Oh no... I'd recommend bumping this to top priority.

Btw, is there a changelog somewhere online?

**Comment by abnerlee** [comment]
@waahto Change log for Mac version is [here](http://www.typora.io/dev_release.html)

But Windows version is still on very early beta stage, the change log is at Help->Change Log from the software

**Comment by nickbe** [comment]
It's still a bug. And a severe one, because I'm not able to continue using Typora that way.

**Comment by abnerlee** [comment]
I check the attached file, it is encoded in ISO-8859-1 not UTF-8, we will support other encodings from next version up.

**Comment by nickbe** [comment]
Thanks. 
Ididn't realize that. But if it's solved in the future then I'm happy with it.

**Comment by abnerlee** [comment]
fixed in v0.8.3

**Comment by nickbe** [comment]
Is there already a new Windows beta we can test?
mojomaker creative software design consulting

Am Mi., Febr. 24, 2016 16:42 schrieb AbnerLee : fixed in v0.8.3

**Comment by DanBennettUK** [comment]
@nickbe There is - though I had to re-download from the website as the Updater (via Check for Updates) found the update but wouldn't download it.

**Comment by abnerlee** [comment]
@DanBennettUK thanks for the info, I will check how typora cannot download the updater.exe
