### ISSUE TITLE
Internal links with hyphens break after exported to PDF

### ISSUE THREAD

**Issue by MilkTicc** [typora/typora-issues#510]
I noticed when the internal link only contains one word it works fine after exported to PDF. Like this:
```markdown
## overview
...
[Go to Overview](#overview)
```
But when it has multiple words and needs '-' to connect between them the link breaks in exported PDF. Like this:
```markdown
## Chapter 1
...
[Go To Chapter 1](#chapter-1)
```
Please fix this! Many thanks!

**Comment by abnerlee** [comment]
Tested in latest versions, seems already fixed.

Please reopen this if it still happens
