### ISSUE TITLE
[bug] LiveRendering doesnt show H1 and H2

### ISSUE THREAD

**Issue by Eisberge** [typora/typora-issues#5100]
- [X] Searched existing issues to avoid creating duplicates.
- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
If `LiveRendering`-Mode is on, there is a little tooltip-like left of the selected row.  
I miss this tooltip in Headlines `H1` and `H2`.

**To Reproduce**
1. Enable Live-Mode
    - File -> Preferences -> Editor -> Live Rendering -> Checkbox (deactivate)
1. Create two new headlines H2 and H3, f.e. ## H3
1. Focus each headline
    - In H3-H6, this tooltip appears
    - In H1+H2, this tooltip doesnt appear

**Expected behavior**
The tooltip should appear in every Headline.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![headlinemarker](https://user-images.githubusercontent.com/22561095/156160232-cb5f1007-7d41-4bc5-a27b-441069d52214.gif)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.
```markdown
# H1

## H2

### H3

#### H4

##### H5

###### H6


```

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 (Build 19042.1526) 64bit

**Typora Version**
1.1.5

**Comment by abnerlee** [comment]
We don't add them since user should be able to distinguish h1 and h2 from their styles. You could also check https://support.typora.io/Add-Custom-CSS/ to add custom marks by yourself.
