### ISSUE TITLE
Typora 'image load failed' when opening from recents or taskbar

### ISSUE THREAD

**Issue by davidprimus** [typora/typora-issues#5101]
- [x ] Searched existing issues to avoid creating duplicates.

- [x ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
My .md file contains about 165 image links to image files about 30kb each. When I double click on the file to open it from file manager, all images display as expected. However, when I open Typora first, then open the .md file from either "File, Open" OR "File, Open Recent", images are not displayed and all show the error "image load failed". The same problem is encountered if the Typora icon in the task bar is right-clicked and opening the .md file from there.

Restarting the PC does not alleviate the issue. 

**To Reproduce**
Steps to REPRODUCE the behavior:
1. Open Typora
2. Open the .md file from either "File, Open" OR "File, Open Recent"
3. Images are NOT displayed and show the error "image load failed"

Steps to AVOID the behavior:
1. Open the .md file from file manager by double clicking on it
3. Images are displayed

**Expected behavior**
Images should be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.1.5

**Comment by abnerlee** [comment]
What does those image path look like? It is absolute path in Markdown or relative path, could you provide a sample md file, if possible?

**Comment by abnerlee** [comment]
Would you try v1.2.5? Does the bug still exist?

**Comment by davidprimus** [comment]
I tried v1.2.5 and the bug seems to be fixed. Thanks!

Dave
