### ISSUE TITLE
[Feature] Discord Rich Presence support

### ISSUE THREAD

**Issue by LoganTann** [typora/typora-issues#5102]
Hello,
I'm using typora a lot (also, thanks for providing the beta of this wonderful editor for free !)

I'd love to get a rich presence support. Implementing such feature is easy using the [discord-rpc](https://www.npmjs.com/package/discord-rpc) dependency.

Here is a preview of a rich presence status for Microsoft Office, using a community-based extension :

![screen : DiscordForOffice project](https://github.com/7coil/DiscordForOffice/raw/master/.github/Discord_LMpsdnmiJZ.png)

Moreover, it would be super cool if the community would get a way to create their own typora plugins.
Since it's a closed-source software, only the typora team can extend it.

**Comment by abnerlee** [comment]
Maybe #162 describe the issue better?
