### ISSUE TITLE
[Bug] Code Fence Dart Language Syntax Highlighting Differs from CodeMirror.net - cm-variable2

### ISSUE THREAD

**Issue by StarXR** [typora/typora-issues#5104]
- [ x] Searched existing issues to avoid creating duplicates.

- [x ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
Syntax highlighting in Dart Language Code Fences differs from examples in CodeMirror. Namely, class names are highlighted the same as variables. 

**To Reproduce**
1. Go to the [CodeMirror Dart Example](https://codemirror.net/mode/dart/index.html)
2. Copy the code snippet, paste into a dart code fence in Typora ( Using the default Night Theme)
4. Class name `Die` and `Random` have incorrect syntax highlighting, see below image

**Expected behavior**
Syntax highlighting should match the CodeMirror website examples. 

I suspect the cause is that Typora labels Die and Random as span.cm-variable while CodeMirror.net labels it as span.cm-variable-2. 

**Screenshots / Screencasts**
I![image](https://user-images.githubusercontent.com/16768177/156616795-13db555a-62a9-4a43-bce3-8da54529a8d5.png)
![image](https://user-images.githubusercontent.com/16768177/156617462-f7eac2e5-d7d0-4b34-baf5-fc270952ffab.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Typora Version**
e.g: 1.1.5

**Additional context**
Python has a similar issue where f-strings are rendered differently than the example on the [CodeMirror](https://codemirror.net/mode/python/index.html) site.

**Comment by abnerlee** [comment]
fixed in 1.2.3
