### ISSUE TITLE
sidebar outline truncated

### ISSUE THREAD

**Issue by stellacilento** [typora/typora-issues#5105]
- [ x] Searched existing issues to avoid creating duplicates.

- [ x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
Doc has multiple second- third- and fourth- level headings, but the sidebar outline stops after the first ## second level heading. 

**To Reproduce**
1. Go to document
2. Click on sidebar
3. Scroll down to outline

**Expected behavior**
I expect a complete outline listing all second, third and fourth level headers

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Monterey 12.2.1.

**Typora Version**
Version 1.1.5 (6235)

**Additional context**
I'm new to Typora but I've done my prep work and have a pretty good grasp of markdown. I've searched everywhere and saw that a similar issue was being discussed some four years ago. Found no suggested solutions.  I'm also new to GitHub so please pardon any missteps.  If there is a better way to ask for this kind of support I would appreciate hearing about it.
Also, as a side note: I write big, fat novels for major publishers. Working on my 12th. Generally I can make Word work for me, but not this time. Which is why I've changed camps. 

![Screen Shot 2022-03-03 at 7 51 41 PM](https://user-images.githubusercontent.com/100893634/156696150-2f69675b-54bd-4d9c-85b8-eb6ffe7e8ae1.jpg)

**Comment by abnerlee** [comment]
Outline does not include headers in blockquote or lists.

For blockquote, we think their headers are used to describe the quoted contents, not the articles itself.
