### ISSUE TITLE
Problem with frontmatter

### ISSUE THREAD

**Issue by PassionPenguin** [typora/typora-issues#5106]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

inputting hashtag the line after fronmatter causing cursor moving back to frontmatter

**To Reproduce**

See video clip (in this video clip, i've just move my cursor to the line after that frontmatter, typing # all the time, and you can see the cursor is moved randomly after # is typed.

https://user-images.githubusercontent.com/41184947/156912523-5047f375-6ab5-4bce-990c-8670aa16e719.mp4

version: 1.1 dev, Windows 64-bit, lang=en-US

**Comment by abnerlee** [comment]
#3318
