### ISSUE TITLE
[Feature] Introduce folder settings

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#5108]
Every project (set of documents) may need very distinct settings like themes, default language, header/footer settings, math enabled/disabled and much more.
The feature request is to introduce a settings file that contains everything that can be customized for a specific set of documents.

This settings file can be extremely useful when the set of documents is edited by different people or roaming on a different user PC. 
* This would ensure the document to be rendered exactly how the author intended to
* It would avoid to see the math/diagrams markup on a PC where typora has those features disabled.

**Comment by abnerlee** [comment]
duplicated with #3109

**Comment by raffaeler** [comment]
@abnerlee Will the https://github.com/typora/typora-issues/issues/3109 work with sub-folders as well?
The whole point here is to have a unique set of settings valid for the entire tree.
