### ISSUE TITLE
[Feature] Embed git source control in Typora

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#5109]
Since markdown is diff-friendly, the git source control perfectly fits in the scenario where a set of documents is shared among multiple users.

In the Files/Outline window, I would love to see the ability to commit, push and pull similarly to what has been done in VSCode.
The source control window can be disabled by default so that it won't affect in any way the users that are not interested in that feature.

**Comment by abnerlee** [comment]
#3196
