### ISSUE TITLE
Lists and code blocks: Broken indentation/blocks after 9th item

### ISSUE THREAD

**Issue by seiks** [typora/typora-issues#511]
Hi!

**Disclaimer**
I did my best in trying to find this bug from the reported ones. If I missed it, I apologize in advance.

## System Information
**OS**: macOS Sierra 10.12.3
**Typora**: 0.9.9.9.0

## Bug Description
This bug happens when you create a numbered list and have blocks of code as the primary data of the list items. When the list size gets to 10 and beyond, all of the following code blocks will break. 

This bug doesn't happen instantly, though. For me, it happens after saving, closing Typora and re-opening the file. It seems that edits are also necessary to trigger this problem (for example, adding more list items).

Here's a screenshot illustrating the problem.

<img width="1280" alt="screenshot-1" src="https://cloud.githubusercontent.com/assets/22685871/22333345/71f447e8-e3de-11e6-8520-9ef38066d192.png">

As you can see from the picture, we have a broken indentation after the 9th item and broken code blocks (they seem to have _re-initialized_ themselves).

## Cause

To see what causes this bug to happen, let's open up Atom and check the raw .md source file.

<img width="1280" alt="screenshot-2" src="https://cloud.githubusercontent.com/assets/22685871/22333668/f33fde2e-e3df-11e6-839d-225b22b63fd9.png">

As I annotated in the image, the culprits are the _"list headers"_. For some reason, Typora likes to insert two spaces after the list item numbers. This extra space causes the breakage. Note however, that this behavior seems to only occur on list items 10 and onward.

If I go ahead and remove the extra space from both list items, we get a clean render.

<img width="1280" alt="screenshot-3" src="https://cloud.githubusercontent.com/assets/22685871/22333778/6c4da88c-e3e0-11e6-9263-609bd4e81924.png">

However, at some point in time, Typora will re-insert these extra spaces and the rendering gets messed up again.

## Proposed Solution

+ Fix the source generator engine to input only one space after list items 10 and onward.
+ Make the rendering engine less strict. One extra space shouldn't break rendering like this.

Thank you for taking the time to read this bug report, and thank you for a great markdown editor! Feel free to hit me up with follow-up questions, if I missed something.

Cheers! 😄

**Comment by abnerlee** [comment]
The rendering engine now is consistent with CommonMark (http://spec.commonmark.org/dingus/) and Github on this part:

<pre>
9. aaa
   ```
   bbb
   ```
10. aaa
   ```
   aaa
   ```
</pre>

So, first generated md source code should be more strict and consider the extra indentation. Whether rendering engine should be less strict or not still needs consideration. 

We will fist fix the auto-generated markdown source code to be more strict

**Comment by seiks** [comment]
Ah! I see! Thanks for pointing that out to me. I guess you can simply ignore the indentation part of my bug report. Following a spec like CommonMark is good practice and I wouldn't advise against it.

I tried to replicate my bug today on a new file but it didn't go so well. I figured I'd come back here and at the very least share with you the actual file in which you can easily replicate this behavior. You can grab it here: [typora-issue-511.md.zip](https://github.com/typora/typora-issues/files/736699/typora-issue-511.md.zip)

Here's also GIF I made, which shows the bug in action. *You can also see a minor rendering glitch that happens with the code block above the cursor when creating a new list item*.

![bug demo](https://cloud.githubusercontent.com/assets/22685871/22394231/e8786f9e-e522-11e6-827d-bd8f0b974d36.gif)

**Comment by abnerlee** [comment]
fixed in new release
