### ISSUE TITLE
[Feature] Shortcut to change document language

### ISSUE THREAD

**Issue by victor-gp** [typora/typora-issues#5112]
Hi, I change (natural) language pretty often within the same document. To support that, I change the document's language every time I switch languages.

So it would be hella useful to be able to open the Spell Check dropdown (dropup?) in the bottom right corner with a key combination and skip the mouse altogether.

It seems to me this could be a pretty common use case for people who speak several languages (including most developers who are not British, North American, etc.).

Other than that, thanks for Typora! It's a super-useful and beautiful piece of software. :heart:

**Comment by abnerlee** [comment]
> So it would be hella useful to be able to open the Spell Check dropdown (dropup?) in the bottom right corner with a key combination and skip the mouse altogether.

Please check https://support.typora.io/Shortcut-Keys/#windows--linux

`Spellcheck` is listed under `Edit` menu
