### ISSUE TITLE
[BUG] cannot load content for existing file, cannot edit new file 

### ISSUE THREAD

**Issue by qwy** [typora/typora-issues#5113]
- [X] Searched existing issues to avoid creating duplicates.
no precise duplicate found existing 
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
reproduce in any theme, irrelevant with themes
- [x] Searched http://support.typora.io/
no hit. no luck
----

**Describe the bug**
* typora main window "dead"
    * for existing file, it shows only the title in title bar, but nothing in the main window, i.e. blank.
    * for new file, it shows "untitled" in title bar, but nothing in the main window, i.e. blank, and you cannot edit it, i.e., cursor cannot move into the content area, and cannot key in.
* return to work again, only when you restart the mac.

**To Reproduce**
use typora for a while, maybe a few hours or days (with mac sleeping.)
then it happens occasionally, but very often!!

**Expected behavior**
just load content.

**Screenshots / Screencasts**
see attached.

**Sample Markdown File**
any file. say, built-in markdown reference.md

**Desktop (please complete the following information):**
 - OS: MacOS big Sur 11.4

**Typora Version**
Version 1.1.4 (6232) (Paid for already)

**Additional context**
<img width="220" alt="image" src="https://user-images.githubusercontent.com/4067047/157352758-143ff495-9f3b-4592-99c1-8614eb9b7248.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/4067047/157471721-5a3798b9-899b-4318-b832-3937f86edcc5.png">

<img width="519" alt="image" src="https://user-images.githubusercontent.com/4067047/157471821-3570fa60-1a1d-4074-8ce3-0c3d7f7d4b13.png">

**Comment by qwy** [comment]
dont know how to label it, with tags like Mac, version number, etc. 
tell me how please :) or just help with it if anyone sees it. 
thanks in advance.

**Comment by abnerlee** [comment]
Does a reboot fix that?

**Comment by qwy** [comment]
yes a reboot does it. as i mentioned, rebooting is the only way out for now. 
> return to work again, only when you restart the mac.

**Comment by abnerlee** [comment]
You could also try remove `~/Library/Caches/abnerworks.Typora/`

And when it happens, could you check if App Store also hangs just like Typora?

**Comment by qwy** [comment]
> You could also try remove `~/Library/Caches/abnerworks.Typora/`
> 
> And when it happens, could you check if App Store also hangs just like Typora?
> 
> may duplicated with #4430

yes. exactly 
i checked as you reminded.   1"app store cannot connect" and 2"safari is dead too"...
thanks for reminding. but no good luck trying  " remove ~/Library/Caches/abnerworks.Typora/"
will keep an eye on https://github.com/typora/typora-issues/issues/4430
