### ISSUE TITLE
Export to pdf no footer exists when the footer includes chinese

### ISSUE THREAD

**Issue by artman328** [typora/typora-issues#5114]
It seems not support footer with chinese like: 第 ${pageNo} 页 / 共 ${totalPages} 页.

**Comment by xingyunjohn1** [comment]
I met the same problem in header with Chinese.

**Comment by xingyunjohn1** [comment]
Got `
Failed to add header / footer.
WinAnsi cannot encode "中"`

**Comment by abnerlee** [comment]
duplicated with #4485
