### ISSUE TITLE
Mermaid graphs cut of text

### ISSUE THREAD

**Issue by tatitati** [typora/typora-issues#5117]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/2141032/157634072-5cbdf32d-c3ff-46e7-be69-3301b96fcfac.png">

As you can see text is being cut (for every theme)
Typora version: Version 1.1.5 (6235) on Mac Monterey v12.1

**Comment by abnerlee** [comment]
Is your Typora zoomed?

**Comment by abnerlee** [comment]
Is your Typora zoomed?

**Comment by tatitati** [comment]
> Is your Typora zoomed?

omg, actually it was zoomed out. It happens for zoom < 100% (everything smaller), but in the opposite direccion doesnt happen.

OK, you can close the issue if you wish, for me just this is fine. I got my typora at 90%, but I can happily use it at 100%

**Comment by abnerlee** [comment]
It is same with https://mermaid.live on Safari, so it is an upstream bug from mermaid. Put into #1661
