### ISSUE TITLE
image load failed under win11 WSL ubuntu

### ISSUE THREAD

**Issue by lumianph** [typora/typora-issues#5118]
OS: Win11, WSL Ubuntu
Typora: 1.1.5

image load failed when the project dir is under WSL. I am sure the path is correct (using relative path). When I move the project to a normal win11 folder, it shows images correctly.

**Comment by abnerlee** [comment]
What's the path of your file, image and its relative path look like?

**Comment by lumianph** [comment]
the path under WSL looks like \\wsl.localhost\Ubuntu\home\xxx.md
the image path is just a normal relative path, such as ./img/xxx.png

**Comment by lumianph** [comment]
have you reproduced the issue?

**Comment by abnerlee** [comment]
Yes, seems I cannot load file:\\\wsl.localhost\\Ubuntu\\home\\xxx\\xx.png in electron, not sure why

**Comment by abnerlee** [comment]
duplicated with #4837
