### ISSUE TITLE
Support for <sup> tags.

### ISSUE THREAD

**Issue by dessalines** [typora/typora-issues#512]
Github uses <sup></sup> tags to do superscript, but typora isn't rendering/previewing these correctly. 

![image](https://cloud.githubusercontent.com/assets/930215/22346140/32f89616-e3c0-11e6-86ff-8cedcef50240.png)

**Comment by Larivact** [comment]
Same for `<sub>` tags.

**Comment by abnerlee** [comment]
move discussion to https://github.com/typora/typora-issues/issues/705
