### ISSUE TITLE
[FEATURE] Focus on the sidebar and move between items with arrow keys

### ISSUE THREAD

**Issue by goryntsev** [typora/typora-issues#5122]
So far I can open the sidebar with a shortcut but then the mouse is needed to pick an item: a file or an outline entry. It would be nice if a user could proceed with keys. For example, opening the sidebar moves the focus to the sidebar and then arrow keys or other shortcuts move the focus between items. The editor's area reacts to this change in focus as it is reacting now with mouse picks: the focused file is rendered or the content is scolled to the focused outline entry. 

Also it could be a shortcut to switch focus between the sidebar and the editor's area so that a user could keep the sidebar open while editing a file.

It's similar how for example VS Code sidebar works.

**Comment by abnerlee** [comment]
duplicated with #1001
