### ISSUE TITLE
[bug] Copying at the table header will get extra text

### ISSUE THREAD

**Issue by Narukara** [typora/typora-issues#5124]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Copying at a table header will get extra "More Actions".

**To Reproduce**

https://user-images.githubusercontent.com/53737377/158062439-4362fa52-d8a7-4018-8d6e-93696f875cbb.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.1.5

**Additional context**
To reproduce this problem, you need to move the cursor slightly to the left when selecting text.

If using another language, you will get "More Action" in the corresponding language.

**Comment by abnerlee** [comment]
fixed in 1.3.6
