### ISSUE TITLE
I purchase Typora and get the License key, but I can not activate typora in China.

### ISSUE THREAD

**Issue by majestichou** [typora/typora-issues#5126]
I use Typora of newest version in China. I purchase Typora and get the License key, but I can not activate typora in China by the  License key. 
The error information is: "Failed to access the license server. Please check your network or try again later"
I do following step: 
Preferences → General → Typora service uses domestic server
However, it doesn't work.
Then I change the vpn, it doesn't work.
What should I do to activate Typora?

**Comment by irgendwr** [comment]
Alternatively you could try the [offline activation](https://support.typora.io/Offline-Activation/).

**Comment by abnerlee** [comment]
Please try methods in https://support.typora.io/activation/#error-message-failed-to-access-the-license-server-please-check-your-network-or-try-again-later
