### ISSUE TITLE
[Linux Request] Include a custom copyright/license file

### ISSUE THREAD

**Issue by irgendwr** [typora/typora-issues#5127]
Hi,

it's considered good practice to define the software license and usage terms as a file in `/usr/share/licenses/`.
I would be great if you could create a `LICENSE` file in `/usr/share/licenses/typora/` in the official `.deb` package for Linux.

The file could simply contain this:
```
Copyright (c) 2015 Abner Lee. All rights reserved.
```

Here you can see the license of chromium for example: https://chromium.googlesource.com/chromium/src/+/master/LICENSE

**Comment by abnerlee** [comment]
I don't see a `/usr/share/licenses/` folder on my Ubuntu 20.04, maybe you mean `/usr/share/doc/` for `deb` packages?

relates https://www.debian.org/doc/debian-policy/ch-docs#s-copyrightfile

**Comment by irgendwr** [comment]
> maybe you mean `/usr/share/doc/` for `deb` packages?

Yes, you are correct.

I was under the wrong assumption that this is consistent between distributions. However, Arch packages use the location that I mentioned (as described in their [wiki](https://wiki.archlinux.org/title/PKGBUILD#license)) while Debian requires the location that you posted. You should of course follow the policy for Debian packages. I will ensure that the [AUR package](https://aur.archlinux.org/packages/typora) moves the license to the appropriate location on Arch systems.

**Comment by irgendwr** [comment]
I can confirm that this is now fixed, thanks
