### ISSUE TITLE
Bold + Italic Caused Unexpected Shift On Selected Words

### ISSUE THREAD

**Issue by CharlesHit** [typora/typora-issues#5129]
Mac 12.3
Version: 1.2.1-dev (6249)

Reproduce:

1. Put the cursor in front of a word
2. CMD+ right arrow to choose **two words**.
3. CMD+B
4. CMD+I: then you will see the selection is get shifted one or two characters at the lefthand of the selection

**Comment by abnerlee** [comment]
> CMD+ right arrow to choose two words.

How to use cmd+right to choose two words?

**Comment by CharlesHit** [comment]
@abnerlee Hi, sorry a typo, should be:

> 2. Option + Shift + rightarrow to pickup two words.

Still, the issue I described is reproducible today on 1.2.1-dev (6249). I would suggest reopening this issue.

Thanks,
Charles
