### ISSUE TITLE
Jumping a word before an inline equation towards the right skips that word 

### ISSUE THREAD

**Issue by hexaquarks** [typora/typora-issues#5132]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Jumping through words ( and inline equations ) towards the right using <kbd>Ctrl</kbd> + <kbd>Right</kbd> in some instances jumps over the inline equation, but this does not happen in the reverse direction using <kbd>Ctrl</kbd> + <kbd>Left</kbd> 

**To Reproduce**
1. Write `abc $X$`
2. Click on <kbd>Ctrl</kbd> + <kbd>Left</kbd> , the cursor jumps in between `abc` and `$X$`. Then move the cursor to the beginning of `abc` and click <kbd>Ctrl</kbd> + <kbd>Right</kbd> , the cursor jumps over `abc` to the right of `$X$`.

**Expected behavior**
The expected behavior is, whenever the cursor is before `abc`, performing <kbd>Ctrl</kbd> + <kbd>Right</kbd> moves the cursor to the end of `abc`, not to the end of `$X$`. 

**Screenshots / Screencasts**
![Gif Example](https://gyazo.com/684e594986d541386247edb46c1786ea.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 Home 64bit]

**Typora Version**
e.g: 1.1.5

**Additional context**
The problem has been persisting for me since beta versions.

**Comment by hexaquarks** [comment]
Any update on this issue?

**Comment by abnerlee** [comment]
duplicated with #4959

**Comment by abnerlee** [comment]
fixed in 1.3.6
