### ISSUE TITLE
Possible phishing site? www.yiting.pro

### ISSUE THREAD

**Issue by Dyrimon** [typora/typora-issues#5133]
Searching for Typora in DuckDuckGo shows the first result as a possible phishing site
![phishing](https://user-images.githubusercontent.com/77260451/158835835-c5824a09-9c85-4b5c-8e04-5d53d11e0ce6.png)

The website is identical to typora.io although the download buttons don't work. I haven't looked through much but it seems like a phishing site.

I hope you clarify this.
Relevant: #5131

**Comment by abnerlee** [comment]
It is a phishing site.

**Comment by abnerlee** [comment]
Our official site is https://typora.io/ and https://typoraio.cn/
