### ISSUE TITLE
[bug] Abnormal high CPU usage on Win10

### ISSUE THREAD

**Issue by Narukara** [typora/typora-issues#5134]
- [x] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I am using Typora on Windows 10. I opened several .md files and after that I did nothing. Windows automatically turned off the screen after a while. When I woke up my computer later, I found that the CPU usage of Typora was very high - around 23%, even after I closed all Typora windows.

**To Reproduce**
I don't know how to reproduce this problem.

**Expected behavior**
A lower CPU usage.

**Screenshots / Screencasts**
![image-20220319010957130](https://user-images.githubusercontent.com/53737377/159059428-330ede94-0251-4362-9022-48c3ef1b76a9.png)

**Sample Markdown File**
These are the files I opened at that time.
[1 时域离散信号.md](https://github.com/typora/typora-issues/files/8306728/1.md)
[2 频域分析.md](https://github.com/typora/typora-issues/files/8306729/2.md)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
   version: 21H2
 - CPU:	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
 - RAM	16.0 GB

**Typora Version**
1.1.5

**Additional context**
I am using the built-in Github theme.

**Comment by abnerlee** [comment]
If you exit Typora completely and reopen those file, the CPU will still be very high?

**Comment by Narukara** [comment]
> If you exit Typora completely and reopen those file, the CPU will still be very high?

No. This phenomenon only occurred once.
At that time I closed all Typora windows, but Typora was still in Task Manager and the CPU usage was high. So I closed Typora in Task Manager and everything was fine after that.

**Comment by Moonlitzz** [comment]
I have the same question , and it happened frequently, even though I didn't open Typora after I turned on my PC.

**Comment by Moonlitzz** [comment]
什么情况啊 你这个软件 是不是在挖矿啊

**Comment by Moonlitzz** [comment]
> If you exit Typora completely and reopen those file, the CPU will still be very high?

I have the same question , and it happened frequently, even though I didn't open Typora after I turned on my PC.

**Comment by abnerlee** [comment]
Did you install Typora downloaded from https://typora.io or https://typoraio.cn ?

**Comment by Narukara** [comment]
> Did you install Typora downloaded from https://typora.io or https://typoraio.cn and without any modification on the installation folder?

I downloaded it from https://download.typora.io/windows/typora-setup-x64-1.1.5.exe.

I don't think I made any changes to the installation folder.

![图片](https://user-images.githubusercontent.com/53737377/159625969-0f7fa6c9-b847-4819-8bf7-ca55aa4525ff.png)

**Comment by Moonlitzz** [comment]
> Did you install Typora downloaded from https://typora.io or https://typoraio.cn and without any modification on the installation folder?
I don't think I made any changes to the installation folder except a folder for notes.
![image](https://user-images.githubusercontent.com/86870009/159710420-299ab918-0af4-4656-8ac2-ba809ea0aec6.png)

**Comment by Moonlitzz** [comment]
> Did you install Typora downloaded from https://typora.io or https://typoraio.cn and without any modification on the installation folder?

yes

**Comment by abnerlee** [comment]
Could you try v1.2.5?

**Comment by Narukara** [comment]
> Could you try v1.2.5?

Yes, I am using v1.2.5 now. No problems so far.
