### ISSUE TITLE
Input when the selection include math causing wrong behaviour

### ISSUE THREAD

**Issue by PassionPenguin** [typora/typora-issues#5135]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

https://user-images.githubusercontent.com/41184947/159107324-3e6efa2b-73cc-49d4-812c-a86ed85ad36f.mp4

See attachment. 

input with keyboard without ime is great, but when it comes to ime, the selection will be extended

**Reproduce it**

simple markdown content (anything contains inline math):

```markdown
你好的花$A$额的31，分式遭
```

1. select any content of the example when $A$ is in the selection (the only need to reproduce the problem is to select anything containing math content)
2. input with any IME with all kinds of languages
3. you will see the selection was extended and was covered by the input content

**Comment by abnerlee** [comment]
What's your Typora version and which IME did you use?

**Comment by PassionPenguin** [comment]
> What's your Typora version and which IME did you use?
> 
> I'm not able to reproduce this.

1.10dev

Sogou Input with default configuration

**Comment by abnerlee** [comment]
Could you try 1.2.5 or 1.3.0-dev ? it works fine in our test

**Comment by abnerlee** [comment]
Tested OK with MS IME, but buggy with Sougo IME

**Comment by PassionPenguin** [comment]
> Tested OK with MS IME, but buggy with Sougo IME

weird behaviours....hoping that this could be solved

**Comment by abnerlee** [comment]
fixed in 1.3.6
