### ISSUE TITLE
Exported file does not reflect image changes

### ISSUE THREAD

**Issue by thenewpyjiang** [typora/typora-issues#5138]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
After an export is made, change an image that the document refers to and then export it again. The change won't be reflected.

**To Reproduce**
1. Add an image to the document.
2. Export the document. Examine the exported document, the image is correct.
3. Change the image (draw something or what), don't close the application.
4. Save the file. In preview, the change to the image is seen immediately.
5. Export the document again. Examine the exported document, the image remains the same as if it was not being changed. There's the bug.

**Expected behavior**
I expect the change to be reflected in the exported document.

**Screenshots / Screencasts**
I think it's best if you try it with the sample Markdown file which I've sent through the email.

**Sample Markdown File**
Sent through email.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3

**Typora Version**
1.0.3 (5993)

**Additional context**
I was making a fix to my homework with an image attached. However I discovered that the second export didn't have the change on it. I think this can potentially have significant consequences, so I believe it is worth attention.

**Comment by abnerlee** [comment]
fixed in 1.3.6
