### ISSUE TITLE
Can't see footer in non-English language when export a PDF

### ISSUE THREAD

**Issue by waveyus** [typora/typora-issues#5139]
**Describe the bug**
Can't see footer in non-English language (eg. Chinese) when export a PDF

**To Reproduce**
1. Go  menu "File"->"Export"->"Exprot Setting..."->"PDF"->"Footer"
2. Type a chinese sentence/words as custom footer text
3. Go back and export the PDF
4. The PDF file displays no footer
5. Change the footer text to English or predefined templates, then it shows the footer in the exported PDF again.

**Expected behavior**
Footer should appear regardless custom text language

**Typora Version**
1.2.3  as well as in 1.1.5

**Comment by abnerlee** [comment]
duplicated with #5114
