### ISSUE TITLE
Enable keyboard access to toolbar menu via alt key

### ISSUE THREAD

**Issue by loup-brun** [typora/typora-issues#514]
I like having access to the upper toolbar using the **alt key** (common across Windows and Linux applications). For instance, if I want to access the `File` dropdown, I would hit `alt + f` (instead of dragging the mouse and clicking `File > (dropdown element)`. The same usually goes for `Edit` (`alt + e`), `View` (`alt + v`) and so on.

Currently, there doesn't seem to be any use of the alt key in Typora (unless I am missing some).

**Comment by AlexPasternak** [comment]
I typically don't use the Windows version, but that would drive me crazy. Alt accelerator keys for getting to specific menus is a must. It's one of the top OS metaphors I miss in macOS.

**Comment by abnerlee** [comment]
fixed in new release
