### ISSUE TITLE
Pandoc Export not working (Win 11)

### ISSUE THREAD

**Issue by sh0nuff** [typora/typora-issues#5144]
System: Win 11 KB5011493

I've installed and purchased Typora, installed Pandoc (2.17), and rebooted.

Typora does not find the pandoc application, although the path is correct, and kicks back the same error message that is displayed prior to pandoc install. There's no other information on resolving this issue that  could find - Note that I'm not too familiar with using github, usually I'd post this on a community forum, hope this is kosher

**Comment by abnerlee** [comment]
Do you try set it manually in preferences panel?

**Comment by sh0nuff** [comment]
@abnerlee - I figured it out - I didn't realize that I needed to actually select the pandoc.exe file in the folder - both the autodetect and when I added it in manually displayed "C:\Program Files\Pandoc", which didn't work.. When I went into preferences to check, I figured I'd try clicking on th exe, changing the path to now read "C:\Program Files\Pandoc\pandoc.exe", which works

I wouldn't be surprised if others might have this issue, perhaps adding a screenshot that shows that the exe is added to the end of the path might alleviate users with similar complaints who aren't as comfortable trying to post on git :)

Thanks!
