### ISSUE TITLE
存在github的图片在typora不能解析

### ISSUE THREAD

**Issue by imattdu** [typora/typora-issues#5145]
哪个版本都有这个问题

<img width="896" alt="image" src="https://user-images.githubusercontent.com/75196326/160239016-46966d18-94ad-414e-bfc8-af1833e571c2.png">

![](https://raw.githubusercontent.com/imattdu/img/main/img/20210108151532.png)

其他编辑器都是正常显示，比如vscode

**Comment by abnerlee** [comment]
duplicated with #5060 #4441
