### ISSUE TITLE
[Feature]Could you please let us use pangu.js to format our md files.

### ISSUE THREAD

**Issue by zhuozhiyongde** [typora/typora-issues#5148]
Pangu.js is an extension that can automatically add space between Chinese characters and English/Math characters. By using this extension, our Chinese writers are able to present more beautifully and elegantly.
Here is pangu.js' github: https://github.com/vinta/pangu.js.
Thank you for your consideration.

**Comment by jeremy-feng** [comment]
> Pangu.js is an extension that can automatically add space between Chinese characters and English/Math characters. By using this extension, our Chinese writers are able to present more beautifully and elegantly. Here is pangu.js' github: https://github.com/vinta/pangu.js. Thank you for your consideration.

Hi there.

I'm also trying to find an elegant way to format markdown files inside Typora. Have you implemented such a method? If so, could you please share it with us?

**Comment by zhuozhiyongde** [comment]
> > Pangu.js is an extension that can automatically add space between Chinese characters and English/Math characters. By using this extension, our Chinese writers are able to present more beautifully and elegantly. Here is pangu.js' github: https://github.com/vinta/pangu.js. Thank you for your consideration.
> 
> 
> 
> Hi there.
> 
> 
> 
> I'm also trying to find an elegant way to format markdown files inside Typora. Have you implemented such a method? If so, could you please share it with us?

I was wrote a python script to temporarily solve this problem. I will share it.

**Comment by zhuozhiyongde** [comment]
Here it is:

https://github.com/zhuozhiyongde/Match-Bracket-And-Pangu-Format

**Comment by jeremy-feng** [comment]
> Here it is:
> 
> https://github.com/zhuozhiyongde/Match-Bracket-And-Pangu-Format

That's really awesome! Thank you ❤️
