### ISSUE TITLE
[Bug] Exporting a code block as image with line numbers turned on makes the numbers get cramped

### ISSUE THREAD

**Issue by AaronLin1229** [typora/typora-issues#5149]
**Describe the bug**
With the "Display line numbers for code fences" turned on in preferences, I tried to export the markdown file as an image, and the line numbers in the image is cramped up when there is multiple ditits.

**To Reproduce**
1. Go to 'preferences'
2. Click on 'Markdown'
3. Scroll down to 'Code Fences'
4. Check the box 'Display line numbers for code fences'
5. Export a code block as a image that has more than 10 lines.
6. The line number is cramped up in the image.

**Expected behavior**
The line number can be normal

**Screenshots / Screencasts**
https://imgur.com/a/P3pDqCA

**Sample Markdown File**
[problem.md](https://github.com/typora/typora-issues/files/8377946/problem.md)

**Desktop (please complete the following information):**
macOS 11.4

**Typora Version**
1.1.5

**Comment by abnerlee** [comment]
relates #5150

**Comment by abnerlee** [comment]
fixed in 1.3.6
