### ISSUE TITLE
Issue with Win64 Installer

### ISSUE THREAD

**Issue by tmr232** [typora/typora-issues#515]
I just downloaded Typora several times, and tried to install it. I get it installed, but `typora.exe` is not an exe. So nothing seems to work.

![image](https://cloud.githubusercontent.com/assets/1386239/22418493/f70e9f86-e6e1-11e6-923a-eddbd0686abc.png)

**Comment by abnerlee** [comment]
are you using x86 or amd64?

**Comment by tmr232** [comment]
amd64

**Comment by abnerlee** [comment]
Closing it since I cannot reproduce it and no other users are reporting this.

It could be your antivirus software blocking the launch of the executable or it delete files while installing. 

There's a similar issue -> https://github.com/Microsoft/vscode/issues/10592
