### ISSUE TITLE
[Bug] The content of the code block in the small size window overlaps with the line number, and cannot be displayed properly after being maximized

### ISSUE THREAD

**Issue by yidai321** [typora/typora-issues#5150]
**Describe the bug**
When the display width of the form is narrow, the text entered in the code block will overlap with the line number, and when the form is maximized, the code block line number will still overwrite the text .（two English characters）

**To Reproduce**

1. Adjust the width of the form to make it smaller
2. Create a new code block
3. Enter text 
4. The beginning of the text overlaps the line number

**Expected behavior**
Text is displayed normally

**Screenshots / Screencasts**
![image-20220401121150803](https://gitee.com/single-hand/picgo/raw/master/img/image-20220401121150803.png)

**Desktop (please complete the following information):**

windows 10

**Typora Version**
1.2.4

**Comment by abnerlee** [comment]
fixed in 1.3.6
