### ISSUE TITLE
[Bug] Coped / downloaded image contains compression loss  

### ISSUE THREAD

**Issue by zhouxinghong** [typora/typora-issues#5151]
Hello! After copying multiple network images or pasting local images into the typora editor, the image compression loss is serious and completely blurred. . . Please do not compress copied network images or local images, and keep the original image content is the most ideal way. . . Hope to improve soon. . . Thanks!
version: 1.2.4
OS: Windows10 19044 x64

**Comment by abnerlee** [comment]
> After copying multiple network images or pasting local images into the typora editor

Could you provide a sample?

**Comment by zhouxinghong** [comment]
> > After copying multiple network images or pasting local images into the typora editor
> 
> Could you provide a sample?

Please do not compress copied network images or local images, and keep the original image content is the most ideal way. . .

**Comment by abnerlee** [comment]
Could you provide a sample?
