### ISSUE TITLE
[Feature] Hello! It is recommended to add a one-touch widescreen reading mode to the View menu, which is useful for reading image content on large screens. The current full screen mode only stretches the screen area vertically, it does not fill the entire screen area horizontally with the image content. This function can currently be installed in vscode to achieve full screen reading and preview of image content by installing a plug-in. . . So I hope you add this feature so that you can also experience the same user experience in typora as reading large screen image content in vscode. Thanks! Version: 1.2.4 OS: Windows 10 19044 x64

### ISSUE THREAD

**Issue by zhouxinghong** [typora/typora-issues#5153]
Hello! It is recommended to add a one-touch widescreen reading mode to the View menu, which is useful for reading image content on large screens. The current full screen mode only stretches the screen area vertically, it does not fill the entire screen area horizontally with the image content. This function can currently be installed in vscode to achieve full screen reading and preview of image content by installing a plug-in. . . So I hope you add this feature so that you can also experience the same user experience in typora as reading large screen image content in vscode. Thanks!
Version: 1.2.4
OS: Windows 10 19044 x64

**Comment by abnerlee** [comment]
see https://support.typora.io/Width-of-Writing-Area/
