### ISSUE TITLE
[Feature] Save the status of TOC

### ISSUE THREAD

**Issue by syrte** [typora/typora-issues#5155]
TOC is useful a useful feature. typora allows users to control to expand or collapse the TOC.
If one selects "expand" mode, then the TOC is always expanded at all levels, which can be very long when the file has deep hierarchical structure. Therefore, I select the collapse mode, but in this case, the TOC is always collapsed, which is also not convenient. 
For example, I expanded the TOC at a certain level, then go to another file and switch back. Typora doesn't memorize my earlier expanding level but simply makes TOC completely collapsed.
My question is if possible to make Typora to save the last expanding  status of the TOC? Thanks.

**Comment by abnerlee** [comment]
Require new syntax (#1202) to control toc level.
For over-all setting, please refer https://support.typora.io/TOC-levels/ (#223)
