### ISSUE TITLE
Inserted Images not loading in Typora 

### ISSUE THREAD

**Issue by benji88i** [typora/typora-issues#5157]
Hi I am trying to figure out why the images imported are not showing anymore. I set images in the preferences to "Copy image to :  `./$[filename].assets` but I have not moved the files from the path.

What is the recommended Image settings for "When insert"

**Comment by abnerlee** [comment]
Could you provide a sample md file and a screenshot of image not shown?

Also, could you provide other information listed in https://github.com/typora/typora-issues/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?
