### ISSUE TITLE
[Bug] click video causes unnecessary jump

### ISSUE THREAD

**Issue by zhouxinghong** [typora/typora-issues#5158]
**Describe the bug**

Insert 2 videos in a row in the editor, one of which is horizontal screen suitable for PC viewing, and the other is vertical screen suitable for mobile phone viewing, but when I click play, every time I click the video to fast-forward to play, the typora editor will jump up and down after Flickering, which is distressing. Hope this can be improved soon. Thanks!
version : 1.2.4
OS: Win10 19044 x64

**Comment by abnerlee** [comment]
Please provide a sample md file,and what is "click the video to fast-forward to play"? Possible to provide a screencast on that?

**Comment by zhouxinghong** [comment]
> Please provide a sample md file,and what is "click the video to fast-forward to play"? Possible to provide a screencast on that?

Hello! Please watch the reproduction process carefully:
[Video 2022-04-04 115255.zip](https://github.com/typora/typora-issues/files/8406607/Video.2022-04-04.115255.zip)

**Comment by zhouxinghong** [comment]
> Please provide a sample md file,and what is "click the video to fast-forward to play"? Possible to provide a screencast on that?

![161720045-87955f68-265c-4d5e-a3d4-6493ce62f40c](https://user-images.githubusercontent.com/54253524/161735916-886b52f9-e51f-42be-9d49-6ba511a1baea.png)

**Comment by abnerlee** [comment]
fixed in 1.3.6
