### ISSUE TITLE
Can't drag window in Unibody mode when theme uses `top: 0` for content

### ISSUE THREAD

**Issue by TEParsons** [typora/typora-issues#5159]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized CSS. (N/A)

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When giving `content` a value of `0` for `top`, the Unibody window is no longer moveable.See [this issue](https://github.com/TEParsons/Krafty/issues/1) on Krafty for context.

I think this is because the context of the `content` element includes the top bar, so when `top` is `0` the background covers up whatever hitbox the window bar is using. Isn't **necessarily** a bug as it's only an issue if a theme has been set up wrong, but it would stop novices like me accidentally breaking the window ;)

**To Reproduce**
1. Either install [Krafty 1.0](https://github.com/TEParsons/Krafty/releases/tag/v1.0) or make a theme whose CSS content is: 
  ```
  content {
      top: 0
  }
  ```
2. Set view mode to Unibody
3. Try to move the window around

**Expected behavior**
The window stays in place and cannot be moved.

**Screenshots / Screencasts**
See [Krafty #1](https://github.com/TEParsons/Krafty/issues/1) for screenshots from @[qfjsj](https://github.com/qfjsj)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Typora Version**
Replicated in 1.1.5 and 1.2.4, but most likely not version specific

**Comment by abnerlee** [comment]
The titlebar for unibody style can be modified via CSS. User can change the `top` part to change titlebar's height for unibody style, but, changing CSS is an advanced setting, so unusually it won't be a issue for most users.
