### ISSUE TITLE
Auto pair quotes: guillemets support (and more)

### ISSUE THREAD

**Issue by loup-brun** [typora/typora-issues#516]
In the preferences, it is possible to enable automatic brackets and quotes pairing. Would it be possible to enable this feature when typing guillemets («», French quotes)?

I would actually suggest allowing **custom pairings** in the preferences section, allowing the user to enable his own character pairings. This way, you would not have to respond to particular pairing cases such as this one and would improve the customizability of Typora.

**Comment by abnerlee** [comment]
I think it is supported when auto-pair option is enabled, after we introduce "SmartyPants" support.

If not working, could you tell us your Typora/OS version, and how do you type "«" ?

**Comment by loup-brun** [comment]
Hi @abnerlee,

Thanks for looking into this.

I have enabled the auto-pair and SmartyPants options.

I'm using the latest Typora for MacOS, version `0.9.9.17` as I’m writing this.

I'm typing the `«`/`»`  characters (opening/closing quotes in French) both using the **US (American)** and **Canadian French CSA** keyboard layouts (neither work).

## US (American)
* `«`: `alt` + `\`
* `»`: `alt` + `shift` + `\` 

## Canadian French CSA
* `alt` + `z`
* `alt` + `x`

For instance, you can see key combination on [Typewolf's cheatsheet](https://www.typewolf.com/cheatsheet) (on an English keyboard, applies to American layout).

Thanks! 😄 

![typewolf cheatsheet - guillemets](https://user-images.githubusercontent.com/9596476/44426275-30da7e80-a55c-11e8-9c45-77c28da16fd0.jpeg)

**Comment by abnerlee** [comment]
relates #3118

**Comment by abnerlee** [comment]
`«` can be used as open quote and close quote depends on which language you are using, so we do not have plans to introduce its auto apir. I also wondering how other apps do this.

Also, you can use `"` directly, and it will be converted into related quote pair when smart quote is enabled.

relates #3118
