### ISSUE TITLE
Tried to buy more licenses from your website but stuck in "processing"

### ISSUE THREAD

**Issue by evaldsurtans** [typora/typora-issues#5161]
Tried to buy more licenses from your website but stuck in "processing"
https://typora.io/#purchase

Buying using Company + VAT which got loaded correctly.

![image](https://user-images.githubusercontent.com/1777062/161549953-ba646fa8-e136-4648-b5ab-067fd7e73d7e.jpeg)

![image](https://user-images.githubusercontent.com/1777062/161549990-f0b31171-2093-45a9-b173-7678e73ba697.jpeg)

![image](https://user-images.githubusercontent.com/1777062/161550084-695d41f1-9e20-439c-92db-2ea659f04af4.jpeg)

**Comment by evaldsurtans** [comment]
Tried with Chrome and Safari

**Comment by abnerlee** [comment]
Sorry for the inconvenience, please try https://store.typora.io/?fromAffiliate=true as a workaround.
