### ISSUE TITLE
[Feature] Open folder link in alternative file explorer

### ISSUE THREAD

**Issue by wcheek** [typora/typora-issues#5162]
I use Double Commander as my file explorer. There are many other file explorers to choose from. I like to use Typora to document my files by using the link feature to link to paths on my file system. This is a great feature and allows me to link to files and directories. When I link to a directory, however, it always opens in the default file explorer (on Windows). I was thinking maybe Typora gets its queue from Windows Default Apps, since it opens other programs depending on the file type, but I've not been able to find a Default App specifying the file explorer. Maybe this is a fault of Windows?

Let me know if this is possible already using Windows features. Otherwise it would be nice to see this added to Typora, so that I can open my file directories using my file explorer of choice!

**Comment by abnerlee** [comment]
We currently cannot support it since we cannot add a context menu item that most user does not need.

Would be covered by #162 however
