### ISSUE TITLE
Unable to show the entire full character in Mermaid

### ISSUE THREAD

**Issue by Dannyrevenger** [typora/typora-issues#5163]
Here is the Mermaid code:
```
graph LR
start(a)

**Comment by Dannyrevenger** [comment]
<img width="514" alt="截屏2022-04-05 下午2 31 57" src="https://user-images.githubusercontent.com/26673297/161693354-d1ea7fe1-bd2a-4b23-bc43-c73753db24b8.png">

**Comment by abnerlee** [comment]
What's your Typora and OS version?

**Comment by abnerlee** [comment]
duplicated with #5117?
