### ISSUE TITLE
Typora crashes on Fedora 35

### ISSUE THREAD

**Issue by mikeymop** [typora/typora-issues#5164]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

I installed the Typora flatpak on Fedora 35. I was using this prior on my previous computer but since upgraded.

**To Reproduce**
1. `flatpak install io.typora.Typora`
2. `flatpak run -v io.typora.Typora`
3. Crashes

**Expected behavior**
Typora should open like normal.

**Screenshots / Screencasts**
```
F: Pulseaudio user configuration file '/home/mikey/.config/pulse/client.conf': Error opening file /home/mikey/.config/pulse/client.conf: No such file or directory
```
Typora appears to crash on systems not using pulseaudio. Fedora uses pipewire by default now.

**Desktop (please complete the following information):**
 - OS: Fedora 35

**Typora Version**
Latest version from flathub 1.2.4

**Comment by abnerlee** [comment]
The community version contains pulseaudio (https://github.com/flathub/io.typora.Typora/blob/19d854cb3da339502730e752b94d716e746ec500/io.typora.Typora.json#L15) but I didn't googled any solutions to support both (pulseaudio or pipewire)

Put into #1456 since we do not have official flatpak support by now.
