### ISSUE TITLE
Typora marks text changed "randomly"

### ISSUE THREAD

**Issue by pryankster** [typora/typora-issues#5165]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

I edit my text with an external editor (vim), and it used to be that when I would
write out the file from VIM, typora would notice the change, and reload the 
file relatively quickly.  If it didn't notice, or I didn't want to wait, I could 
select the "reopen with encoding -> auto" menu item, and have the text reloaded.

The version of Typora that I'm using now, allows me to reload once, but then marks
the buffer as dirty, and thus hides the "reopen with encoding" menu item, even
when I don't touch anything in the Typora window.  This is extremely frustrating,
as I have no way to revert whatever Typora things has changed, and then reload, and since Typora thinks that the buffer has changed, it won't automatically reload the
text from disk.

**To Reproduce**

Open a file in Typora
1. Edit the file with VIM (or another editor? dunno)
2. Write the file in VIM.
3. Wait a bit, Typora will notice, and reload the file.
   OR, select the "reopen with encoding -> auto" 
4. Notice that Typora shows the buffer dirty icon in the title bar.

**Expected behavior**
Don't mark the buffer as dirty until I change it in Typora.  Also: always allow me to reload (in a previous version, I had 'F5' mapped!)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.2.4

**Comment by abnerlee** [comment]
Hi,

Could you provide a screencast of the operation that will lead Typora "reload once, but then marks the buffer as dirty" ?
