### ISSUE TITLE
PDF export with theme and bibliography?

### ISSUE THREAD

**Issue by Redcxx** [typora/typora-issues#5166]
Hi, I want to export my markdown as pdf with theme, I know this can be achieved by going to the `Export` tab then click on `PDF`. But I am writing academic paper and require referencing, so I export my mardown in the command line using pandoc like so:
```
pandoc --citeproc "report.md" --bibliography "report.bib" --csl "xxxx" -o "report.pdf"
```
But exporting this way does not include the theme style I used in the typora, so may I know if there is a way to either:
- include referencing bibliography in typora pdf export.
- specify the theme somewhere, in a way that pandoc can render it.

**Comment by abnerlee** [comment]
bibliography is recorded in #912 

Typora's theme is supported for Export in preferences setting. Pandoc export uses latex, not CSS rendering. you could try pandoc's wkhtmltopdf rendering engine for CSS styles

**Comment by Lazenca-Li-Qiuqi** [comment]
I ran into the same split workflow problem (write in Typora, then handle citations/bibliography elsewhere), so I built a Typora plugin to reduce that gap for local BibTeX workflows.

It does not replace Typora’s export pipeline, but it does support:
- local `.bib` search and citation insertion
- local `.csl` citation rendering
- bibliography insertion/update inside Typora

Repo: https://github.com/Lazenca-Li-Qiuqi/typora-plugin-bibtex-citation

So for people using Pandoc-style citations and local BibTeX files, this can make the writing/editing side much smoother even if export still depends on your existing toolchain.
