### ISSUE TITLE
MINOR: Extra space added in heading tags when pasting HTML code

### ISSUE THREAD

**Issue by xebico** [typora/typora-issues#5167]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**

When pasting text into another app that has been copied using "Copy as HTML Code," Typora will insert a space before the closing tag of a header (h1, h2, etc.)

**To Reproduce**

1. Select a block of Typora text that includes h1, h2, or h3 content. 
2. Copy that text using "Copy as HTML Code."
3. Paste that text into another application, e.g., Notepad.
4. Note that heading tags appear as "`<h1 >`" or "`<h3 >`" etc., with an extra space before the closing bracket.

**Expected behavior**
Heading tags should appear as, for example, `<h2>` rather than `<h2 >`.

 - OS: Windows 10 64-bit

**Typora Version**
1.2.4

Screenshot:
![heading-tags](https://user-images.githubusercontent.com/19582721/162446301-cc2eb333-2c26-4d62-bcea-7a83f48703b8.jpg)

**Comment by abnerlee** [comment]
fixed in 1.3.6
