### ISSUE TITLE
Incorrectly parsing RTSP streams URL as e-mails.

### ISSUE THREAD

**Issue by LaazV** [typora/typora-issues#5168]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Hi, seems like the url parser is incorrectly parsing RTSP urls' when pasted in the text editor.

**To Reproduce**
1. Copy a RTSP stream URL, e.g (http://admin:12345@172.6.22.106:554/Streaming/Channels/102)
2. Paste on Typora

**Expected behavior**
The result shoud be a url:
[http://admin:12345@172.6.22.106:554/Streaming/Channels/102](http://admin:12345@172.6.22.106:554/Streaming/Channels/102)

**Actual behavior**
rtsp://admin:[12345@172.6.22.106](mailto:12345@172.6.22.106):554/Streaming/Channels/102

**Desktop**
 - OS: Windows 10 64 bits

**Typora Version**
1.2.4

**Comment by abnerlee** [comment]
Please use `<rtsp://admin:12345@172.6.22.106:554/Streaming/Channels/102>`, auto link should only cover common protocols.
