### ISSUE TITLE
Cannot open with Typora on Ubuntu

### ISSUE THREAD

**Issue by zhong-yy** [typora/typora-issues#5169]
**Describe the bug**
Files are not opened at all when I try opening them

**To Reproduce**
Right on a folder，choose to "open with typora"

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04

**Typora Version**
1.2.3

**Comment by abnerlee** [comment]
Could you provide a screencast?

And did you use the deb or binary version?

**Comment by zhong-yy** [comment]
> 

I used deb version. Maybe it is the problem of electron? I encountered the same problem when opening vscode

**Comment by abnerlee** [comment]
>  I encountered the same problem when opening vscode

In that case, it should be an issue with electron, but it works fine in my ubuntu 20.04, so it may also relates to your ubuntu setup.

---

Can you open Chrome successfully? IF so, does binary version (download the tar.gz package from https://typora.io/releases/all) work?

**Comment by zhong-yy** [comment]
> , does binary version (download the tar.gz

Yes I can open chrome. I got this error when trying the binary version: 
```
bash: ./Typora: cannot execute binary file: Exec format error
```

**Comment by zhong-yy** [comment]
> Could you provide a screencast?
> 
> And did you use the deb or binary version?
Here is the screenshot when I opened a folder with Typora
![Screenshot from 2022-05-26 19-22-18](https://user-images.githubusercontent.com/38816011/170478924-a5faf52a-7161-41bd-94d0-faff29acd31d.png)

**Comment by abnerlee** [comment]
So typora can be opened, but it is blank?

Does remove `~/.config/Typora` work? And could you provide log (https://support.typora.io/Get-Logs/)

And about "bash: ./Typora: cannot execute binary file: Exec format error", please confirm you download the binary with same architecture with yout OS / hardware.
