### ISSUE TITLE
Content disappearing from undo history when cutting text

### ISSUE THREAD

**Issue by joakimc** [typora/typora-issues#517]
When using Cmd-X to cut out text, Typora sometimes move the cursor to some other place in the text, and the text I just cut out is removed from the undo history. To get it back the way it (hopefully) was I have to find out where in the text I cut out the text, and then paste it back in.

I saw someone had posted a similar issue, but it seemed related to Chinese text. I write in Norwegian, but I believe it's the same latin character set the English one.

Typora 0.9.9.9.0
macOS Sierra 10.12.2

**Comment by abnerlee** [comment]
Should be fixed already in the newest version. Please reopen this if you met this bug again
