### ISSUE TITLE
Auto refresh not working anymore on windows 

### ISSUE THREAD

**Issue by SeanKimMel** [typora/typora-issues#5170]
Hello, 

#### typora 1.2.4 version on windows enterprise 10(21H2).

first, Thank you for developing this amazing tool. Typora made my daily life much easier.

the issue I'm experiencing is auto refreshing function.

I don't know since when but from some point I have to perform manual refresh every time I create new file/folder 
and change the name of it.
I don't have issue with my desktop but I'm having issue on my laptop.

So I'm wondering that there's any option on windows/typora that I can set to fix this problem?
(I know there's been a release to fix this issue quiet a time ago, but I'm using lastest version)

thank you in advance.

regards, Sungwon.

**Comment by jakehappersett** [comment]
Hey just popping in to say I am experiencing the same bug on Windows 11

**Comment by julesgilson** [comment]
same here. Now that this is a commercial application, you need to be on-point with QA and fix timelines - dropping in bugs in releases and giving no indication of when it will be fixed is not really acceptable for paid-for software

**Comment by abnerlee** [comment]
fixed in 1.3.6
