### ISSUE TITLE
In source code mode, the cursor positioning code position is inaccurate and has a one-character offset. 

### ISSUE THREAD

**Issue by zhouxinghong** [typora/typora-issues#5172]
**Describe the bug**

Hello! In the source code editing mode, the cursor positioning code position is inaccurate and has a one-character offset. Please check the errors and fix them in time. Thanks!
![2022-04-12_002800](https://user-images.githubusercontent.com/54253524/162787453-3565df53-1611-4a4a-9f1a-0b84153e01fe.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]

**Typora Version**
e.g: 1.3.0.dev

**Comment by zhouxinghong** [comment]
![2022-04-12_071030](https://user-images.githubusercontent.com/54253524/162847844-70c71887-87aa-4928-8a77-6ac5d59355e7.png)

**Comment by abnerlee** [comment]
Could you provide a sample md file?
