### ISSUE TITLE
[Bug] Weird page break inside tables

### ISSUE THREAD

**Issue by Llemaban** [typora/typora-issues#5173]
After update of Typora from version 1.1.5 to 1.2.4 on both Ubuntu and Windows, there are weird breaks in tables after export to PDF.

Before Update (created with 1.1.5 on Ubuntu):
![grafik](https://user-images.githubusercontent.com/73166544/162803457-c20923cf-75c0-4a9b-8418-8b46dfbcb377.png)

After Update (created with 1.2.4 on Ubuntu and Windows):
![grafik](https://user-images.githubusercontent.com/73166544/162803250-3d1b6159-305c-4f8a-9d0b-a87f8fa07e8a.png)

The default style sheet (Github theme in this case) have not been manually modified at any time.

Using one of my own themes which is based on the [Academic theme](https://theme.typora.com.cn/theme/Academic/), those page breaks works without troubles.

**Comment by abnerlee** [comment]
duplicated with #3418

Could you provide a sample md file?
