### ISSUE TITLE
Bunch of bugs

### ISSUE THREAD

**Issue by safqwf** [typora/typora-issues#5175]
Working for few hours, I stumbled across few bugs, some of them are so basic.

One:
Open the app,
Open a directory
Right click -> New file, type a name -> Enter.
Bug - it doesn't save the same of the file, file is named Untitled.md.
Continue to work - asks if what I want to do with the file, let's say Discard.
An error appears says the Untitled.md doesn't exist.

Second:
Open a file,
Right click on the file -> Delete
Am I sure? Yes, I'm sure.
Bug - doesn't close the editor of this file, 
and asks me if I want to save it. 
A second ago, I clicked that's I'm sure I want to delete it.

Third:
Working with CTRL+B to de-bold the text, 
10% of the time it keeps `**` on the left side.

**Comment by abnerlee** [comment]
could you create issue with the template please~
