### ISSUE TITLE
"Cannot open location" error popup text does not wrap - too long for window

### ISSUE THREAD

**Issue by wcheek** [typora/typora-issues#5176]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized CSS. (Cobalt, Typora Nord)

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When linking to a very long (local) "bad link" such as [bad link]("bad link.........................................................................................................................."), the notification of "Cannot open location" which opens at the top of the window is too long for the window.

**To Reproduce**
1. Open Typora
2. Create a "bad link" (described above)
4. Error notification pop up window is too long for the window. Cannot click X to close notification. Must use ESC to close pop up.

**Expected behavior**
Text in error pop up window should wrap, and pop up window should fit inside the window width.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/66931618/163080850-bb26bb95-2378-4ded-9932-5a601da2c7c0.png)

**Sample Markdown Text**
[bad link]("bad link.....................................................................................................................................................................................................................................")

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]

**Typora Version**
1.2.3

**Additional context**
Almost always occurs, occasionally not. I'm not sure how to reproduce the occasionally good behavior.

**Comment by abnerlee** [comment]
fixed in 1.3.6
