### ISSUE TITLE
[Feature]在文件的右键菜单中添加刷新按钮

### ISSUE THREAD

**Issue by twtangwentw** [typora/typora-issues#5177]
在好几个版本都出现了添加文件或者文件夹没有自动刷新的情况了，能否在右键菜单中添加刷新按钮，或者添加快捷键f5为刷新
![image](https://user-images.githubusercontent.com/26857825/163101836-5dfe187d-77ea-4dc7-a06c-d0c163256429.png)
需要点击最后一点点范围，然后再点那个比较小的刷新，有点麻烦

**Comment by abnerlee** [comment]
#5170 We do not want to add too much thing on context menu

**Comment by Louis24** [comment]
> #5170 We do not want to add too much thing on context menu

nb
