### ISSUE TITLE
image won't update when search & replace the path of it

### ISSUE THREAD

**Issue by KrisCris** [typora/typora-issues#5178]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

**Describe the bug**
image won't update when search & replace the path of it

**Expected behavior**
image updates to the new one once the path is replaced.

**Desktop (please complete the following information):**
 - OS: windows 11

**Typora Version**
1.1.4

**Comment by abnerlee** [comment]
fixed in 1.3.6
