### ISSUE TITLE
export to LaTeX, file name and file extension  ---------Enhancement

### ISSUE THREAD

**Issue by syslon** [typora/typora-issues#518]
Thank you very much for proving us an amazing tool for users

Platform : Windows 8 x64
When I click file- export- LaTeX to export markdown files to LaTeX format,  pop-up windows appears,
 1) would you please add the default file name to the exported file name?
 2) Would you please change the file extension  from "latex, tex,...." to "tex, latex", namely the preferred file extension for LaTeX file is tex, not LaTeX?

**Comment by abnerlee** [comment]
fixed in new release
