### ISSUE TITLE
seems cannot get upload pic success callback while using picgo

### ISSUE THREAD

**Issue by XeCtvi** [typora/typora-issues#5180]
I have configured my pics bed well, with using picgo 2.3.1-beta.2. 
And I can upload img successfully while paste the img into typora, but typora keep uploading the same pic.

1. Paste a pic into typora;
2. Trigger picgo upload img successfully;
3. typora automatically upload the same img again and again, with the loading... spinner.
4. The pic's path doesn't replaced with the uploaded online path.

**Expected behavior**
Typora upload img once, and replace the img url successfully.

**Screenshots / Screencasts**
picgo logs:
<img width="634" alt="picgo logs" src="https://user-images.githubusercontent.com/10743176/163430531-7432a93d-2b01-4775-b840-3368eeb46a56.png">

keep showing uploading while the pic has been uploaded success!
<img width="1008" alt="keep uploading" src="https://user-images.githubusercontent.com/10743176/163430730-b9591e73-e00c-49d5-8b42-db871eb9a66e.png">

Upload check keep testing as well, keep upload the test pic and never stop:
<img width="537" alt="keep check" src="https://user-images.githubusercontent.com/10743176/163430815-39c0af82-993f-4f52-92a9-c79fdf828289.png">

**Desktop (please complete the following information):**
- OS: macos 12.2.1 MacBook Air M1
- picgo 2.3.1-beta.2
- pics bed: github

**Typora Version**
0.11.18

**Comment by abnerlee** [comment]
Could you try stable version of picgo and Typora?

And could you try https://github.com/typora/typora-issues/issues/4560#issuecomment-891919681 and update the result there since it is a duplicated issue

**Comment by xuJ14** [comment]
I met the same question. And I think the problem may be there already exist the test pictures in the repo.

**Comment by XeCtvi** [comment]
> Could you try stable version of picgo and Typora?
> 
> And could you try [#4560 (comment)](https://github.com/typora/typora-issues/issues/4560#issuecomment-891919681) and update the result there since it is a duplicated issue

通过 fetch 上传失败。且我当前电脑环境的效果，还是和我提此 issue 一致。
<img width="459" alt="image" src="https://user-images.githubusercontent.com/10743176/185775358-0c9357f2-03fb-4990-b4ec-68f50379262d.png">
