### ISSUE TITLE
请问Typora的配置文件在哪里？

### ISSUE THREAD

**Issue by zhaifanhua** [typora/typora-issues#5181]
由于Typora旧版本没有用户登录，设置不能同步，有时候装机或重新安装后需要配置设置信息，如何才能高效的一键导入配置，请问Typora的配置文件在哪里？

**Comment by zhengpd** [comment]
大概是 `~/Library/Preferences/abnerworks.Typora.plist`

**Comment by abnerlee** [comment]
#2353
