### ISSUE TITLE
Export (docx): Syntax highlighting does not work for shell and bash markdown blocks

### ISSUE THREAD

**Issue by petpetpetpet** [typora/typora-issues#5183]
- [x ] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The `shell` and `bash` code blocks Syntax highlighting work fine *inside* Typora. However, when exported to `docx`, the highlighting for these is lost. I do not even see the automatically inserted `Tok` styles applied to the text in these blocks. Highlighting for other block types seems to work ok.

**To Reproduce**
1. Open the attached markdown document in Typora.
2. File -> Export -> docx
3. Open the docx file in MS Word.

**Expected behavior**
The syntax highlighting seen in Typora is present in Word.

**Actual behaviour**
The syntax highlighting for `shell` and `bash` are gone. The code in those blocks is just using the standard `Source Code` style.

**Sample Markdown File**
[Test Document.md](https://github.com/typora/typora-issues/files/8501308/Test.Document.md)

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.7

**Typora Version**
e.g: 1.0.5

**Comment by abnerlee** [comment]
fixed in 1.3.6
