### ISSUE TITLE
Bug of Exported HTML

### ISSUE THREAD

**Issue by CheeseburgerIM** [typora/typora-issues#5184]
I choose to include outline sidebar when exporting markdown to html
And this happened
![typora-bug](https://user-images.githubusercontent.com/71696925/164012219-4678f62a-1037-49ff-a374-f0ef149ba94a.png)
As you can see, sidebar is misplaced and the bottom of it is covered by the content of the article
How to solve this problem ?

**Comment by abnerlee** [comment]
Could you provide the sample md file?
