### ISSUE TITLE
Opens file into a new window

### ISSUE THREAD

**Issue by M8825** [typora/typora-issues#5186]
- [x] Searched existing issues to avoid creating duplicates.
----

**Describe the bug**
`File > New` opens a new file into the NEW window.

**Expected behavior**
`File > New ` - Should open a new file IN CURRENT window. (Not in a new window)

**Desktop:**
- OS: Elementary OS

**Typora Version**
1.2.4

**Comment by abnerlee** [comment]
duplicated with #1000
