### ISSUE TITLE
Save mermaid figure?

### ISSUE THREAD

**Issue by Redcxx** [typora/typora-issues#5187]
Hello, currently if I want to save the rendered mermaid SVG I can open dev tools and copy the SVG element to a file, but this is rather tedious and I need to manually replace `<br>` with `<br/>` to avoid SVG parse error (https://github.com/mermaid-js/mermaid/issues/614). May I know if there is an easy way to do this that I did not notice?

**Comment by abnerlee** [comment]
supported in 1.3.6
