### ISSUE TITLE
Code block within list item breaks when reopening Markdown file

### ISSUE THREAD

**Issue by sikinmettugi** [typora/typora-issues#519]
Hello, 
I think I had a weird situation, therefore I generated this issue.

## 1. Short summary

- The saved markdown document edited by Typora rendered with wrong code block used with list items, when re-opened with Typora. Maybe this issue is related with Hanguel(Korean Letters), but not strictly tested.

## 2. What happened

- Environment: Windows 7 x86-64, Typora version 0.9.23 beta

- Wrote a document with code blocks within list items.
![proper](https://cloud.githubusercontent.com/assets/333649/22582568/ff5a0e72-ea2a-11e6-88fb-df25caf5c309.png)

- When saved, closed the document, worked with some other markdown documents via Typora, then re-opened this one, one of the code blocks was broken.
![viewmode](https://cloud.githubusercontent.com/assets/333649/22582569/ff6319a4-ea2a-11e6-9cdf-3b366d5ca3b5.png)

- Found out an unintentional(i.e. I did not added this) "```" has added automatically. Deleting this made the document looks what it should be.
![codemode](https://cloud.githubusercontent.com/assets/333649/22582567/ff557506-ea2a-11e6-8d45-e740ff45f8ae.png)

- ...and this happened again in another document. Also code block within list items, some Hanguel words in list item string.

Is this a bug?

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/511

will be fix in next version up asap
