### ISSUE TITLE
[Feature]希望增加文件列表直接复制文件的功能

### ISSUE THREAD

**Issue by WangJincheng4869** [typora/typora-issues#5190]
我希望的是在文件列表中可以直接复制文件，可以添加「复制」菜单，或者使用`Ctrl+C直接复制文件`，而不是打开文件位置后再复制文件.
![image](https://user-images.githubusercontent.com/41162158/164358509-cd5daddf-72ec-4e34-b2fc-68d6892bcba2.png)
![image](https://user-images.githubusercontent.com/41162158/164358548-66049ec4-c54a-4ed0-aae1-beee967c3609.png)

**Comment by abnerlee** [comment]
#5143
