### ISSUE TITLE
svg image renders correctly if "." is added after file name

### ISSUE THREAD

**Issue by ajitgoel** [typora/typora-issues#5192]
I have an svg image that renders correctly if I put a "." after the file name but does not if I remove it. Any inputs on what could be wrong? Is this a Typora bug? 
Eg: in screenshot below the first image does not render but the second image does, after a . is added to the file name.
![image](https://user-images.githubusercontent.com/6394444/164496809-4ee92da8-3f50-4f3c-a733-4800b232948e.png)

**Comment by abnerlee** [comment]
Would you provide the svg file and file name?

**Comment by ajitgoel** [comment]
Here's one of the files with the issue. 

![b2ad2d24-f178-40de-94df-2d65f09f4215](https://user-images.githubusercontent.com/6394444/170743553-c1d934d8-8be4-4ad0-96df-95783faac97d.svg)
)
