### ISSUE TITLE
rename folder failed

### ISSUE THREAD

**Issue by nichelnich** [typora/typora-issues#5193]
**Desktop:**
 - OS: [Windows 7 64bit]

**Typora Version**
e.g: 1.2.5
![2022-04-22_10-45-33 00_00_03--00_00_15](https://user-images.githubusercontent.com/6030793/164588532-e9f5a59f-185f-4595-b800-793f673ad067.gif)

**Comment by nichelnich** [comment]
![2022-04-22_11-18-21 00_00_05--00_00_18](https://user-images.githubusercontent.com/6030793/164589768-f237d6ba-29ed-4018-87cf-7b6ab3045ba7.gif)

**Comment by abnerlee** [comment]
It works fine in my test, so what's the full path of the "test" folder?

**Comment by nichelnich** [comment]
> It works fine in my test, so what's the full path of the "test" folder?

"test" parent is "C:\Users\nichel\Desktop". 

This problem only arises occasionally, and I don't know what preconditions it needs. Maybe you should integrate a debug mode in the software, otherwise it will be difficult for you to simulate the strange usage scenarios of users.

If you only add a lable "need more info". Your app will not goto better.

**Comment by nichelnich** [comment]
> It works fine in my test, so what's the full path of the "test" folder?

I found the pattern.  you create 3 level fold & 3 fold in each level. add some md files. if you rename fold randomly, you can catch this issue in 3min.

**Comment by nichelnich** [comment]
https://github.com/typora/typora-issues/issues/5175#issue-1202359246
I often have his problems.   Maybe they are the same bug.

All in all, the file manager is pretty bad, hope you guys can refactor it.

**Comment by abnerlee** [comment]
fixed in 1.3.6
