### ISSUE TITLE
[Feature] Android App (post v1.0)

### ISSUE THREAD

**Issue by plutonium-239** [typora/typora-issues#5195]
Referring to https://github.com/typora/typora-issues/issues/525#issuecomment-427268749, which says will look at it after release of v1.0, ... which is here now!
Would love an android app and since its written in electron there are lots of ways to port/translate it to android/ios/ipados.

**Comment by abnerlee** [comment]
duplicated with #525 

We are now still focusing the desktop version since we still have a lot todos. We are open to mobile versions, but that is not a "port" since mobile and desktop are completely different. So even when we start it, it would take quite a long time.
