### ISSUE TITLE
add "remove menu bar" option on Linux

### ISSUE THREAD

**Issue by KairuiLiu** [typora/typora-issues#5198]
Is it possible to implement an operation like removing the menu bar in windows in linux?

- Arch Linux x86_64  
- Kernel: 5.17.4-arch1-1 
- WM: i3 
- package: [aur-typora](https://aur.archlinux.org/packages/typora)

![深度截图_选择区域_20220423132736](https://user-images.githubusercontent.com/25458969/164879230-139e43fe-9afc-4a67-9961-0573177a0da2.png)

**Comment by tiancj** [comment]
Edit ~/.config/Typora/conf/conf.user.json, set `autoHideMenuBar` to true will hide menu bar.

**Comment by abnerlee** [comment]
updated document in https://support.typora.io/Advance-Config/#auto-hide-menubar
