### ISSUE TITLE
WYSIWYG-Editor - TextExpander - First Character is not replaced

### ISSUE THREAD

**Issue by njanert** [typora/typora-issues#520]
When you use a phrase expander software, like PhraseExpress or TextExpander, and you enter the abbreviation of the phrase to expand, the first letter is not replaced by the expanded phrase. In the code-view the complete abbreviation will be replaced. An example is:

In Code-View:
"mdred" becomes "<span style="color:red"></span>"

In WYSIWYG-Editor
"mdred" becomes "m<span style="color:red"></span>"

**Comment by abnerlee** [comment]
Tested with TextExpander, but it works well. 

Any extra steps to reproduce this bug?
