### ISSUE TITLE
希望能够按下tab输出4个或者两个空格的功能，而不是输出tab字符

### ISSUE THREAD

**Issue by XDwanj** [typora/typora-issues#5204]
### 希望能够按下tab输出4个或者两个空格的功能，而不是输出tab字符
> tab字符在不同系统渲染会有不同效果，我是一名双系统使用者，在同一台电脑上我会来回切换系统，我迫切的希望能够解决这个问题，感谢!

**Comment by abnerlee** [comment]
#579
