### ISSUE TITLE
[Feature] Cut the entire line where the cursor is by pressing CTRL+X or CMD+X

### ISSUE THREAD

**Issue by FilippoBovo** [typora/typora-issues#5205]
It would be nice to be able to cut the entire line where the cursor is by simply pressing CTRL+X or CMD+X (on MacOS). This means that the line does not need to be selected (eg, highlighted using mouse) before cutting it. This would make it really convenient to move things around a Markdown file. Thanks.

**Comment by abnerlee** [comment]
It is supported already. Please enable it in preferences panel.
