### ISSUE TITLE
Unable to locate package typora

### ISSUE THREAD

**Issue by olegpoltora** [typora/typora-issues#5207]
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
[sudo] password for poltora: 
OK

 sudo add-apt-repository 'deb https://typora.io/linux ./'
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 https://typora.io/linux ./ InRelease                                                                 
Hit:3 http://ru.archive.ubuntu.com/ubuntu bionic InRelease                                                 
Hit:4 http://ru.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://ru.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done

 sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://ru.archive.ubuntu.com/ubuntu bionic InRelease               
Get:3 http://ru.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]
Hit:4 https://typora.io/linux ./ InRelease                                            
Get:5 http://ru.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]        
Fetched 163 kB in 1s (120 kB/s)                                
Reading package lists... Done

 sudo apt-get install typora
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package typora

**Comment by abnerlee** [comment]
Could you share your os and version?

Does `sudo apt-get install Typora` work? 
Could you try `apt-cache search typora` or `apt-cache search.` to see if it will be returned or not.

**Comment by olegpoltora** [comment]
Well, it was 32 bit Xubuntu 18.04
At 64 bit - all ok

**Comment by abnerlee** [comment]
We do not have linux 32 bit support (https://support.typora.io/System-Requirements/)
