### ISSUE TITLE
Save conflict dialog blocks save even if only the file timestamp has changed

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#5208]
Typora is treating just a timestamp change to a file as a conflicting change by another application.

Proof:
1. Open a file in Typora. Make a change and save.
2. Switch to shell, and execute `touch <path to file>` 
3. Switch back to Typora. Try to save. You will get the following dialog:

> ### The document “README.md” could not be saved. The file has been changed by another application.
>
> Click Save Anyway to keep your changes and save the changes made by the other application as a version, or click Revert to keep the changes from the other application and save your changes as a version. You can also click Save As to save your changes to a different file.

## Expectation:  If the file hasn't actually changed, since the last Typora save, no conflict should be reported.

This is the minimum expected behavior. It would be better to implement #5209.

This situation can occur easily during normal work, not just in the artificial "Proof" steps I gave above:
1. The file is in Git, and you temporarily switch to another branch where the file has changed, and then you switch back. The file is back to where it was before, but Typora will still report a conflict.
2. The file is in Git, and you perform a rebase operation. Git rebase will replay the commit history, updating the file's timestamp each time. At the end of the rebase, the file is restored to its last committed change, but its timetamp will be different.
3. You have the file open in another app. And in that app you press save without making any changes.
4. File timestamp changes due to cloud syncing. Possibly related to #3137 and #2735.

---
 - OS: macOS 12.3.1
 - Typora Version: 1.2.4

**Comment by Llemaban** [comment]
Possible temporary fix for this issue could be using a simple hash value.
If the file timestamp changes, also calculate the new hash of the changed file and compare it with the old one.
But this requires to check the file change only on an `OnFocus` event when switching back to the typora window. At least on Windows, this seems to happen asynchronously and then the suggested fix won't work.

**Comment by abnerlee** [comment]
macOS has its own logic to save files, Typora does not save or write file to disk directly, it is handled by the system. 

You could try the behavior with TextEdit.app

We will try to improve this however. Put into #5209

**Comment by vassudanagunta** [comment]
@abnerlee I use Webstorm and sometimes have the same file open in Typora (for the WYSIWYG rendering) and in Webstorm because it is part of the project repo and it contains TODOs picked, or because I have to deal with Git merge conflicts, etc. 

Webstorm handles this perfectly on macOS. When I edit a file in Typora, the changes are automatically loaded into the Webstorm editor when it regains focus change, and it automatically saves its changes when it loses focus. The problem is entirely on the Typora side. 

So i don't believe Typora can't do better. Also this is a serious issue. As I just wrote [in a #5209 comment](https://github.com/typora/typora-issues/issues/5209#issuecomment-1114052355):

> ***the user is forced to choose which version to keep, which is not only an unnecessary and unnecessary-stress-inducing warning, it forces the user to make an impossible choice***, either ignore the warning OR manually figure out whether the warning is a false one and whether or not they are about to lose data! This is totally unacceptable.

It's ok to close this one if you acknowledge this importance and commit to solving it as part of #5209, but you just marked #5209 as `limited` so I don't think you consider this as important.

**Comment by vassudanagunta** [comment]
@abnerlee  #5209  is submitted as a feature request and you labelled it as "limited". But I consider at least this issue above a bug. Please see that comment as well as to the "timestamp only external exchange" column of the table in #5209. 

I would ask that you either ⓵ reopen this issue or ⓶ increase the priority of that one.

**Comment by vassudanagunta** [comment]
@abnerlee  #5209  is submitted as a feature request and you labelled it as "limited". But I consider at least this issue above a bug. Please see [this comment](https://github.com/typora/typora-issues/issues/5209#issuecomment-1114244937) as well as to the "timestamp only external exchange" column of the table in #5209. 

I would ask that you either ⓵ reopen this issue or ⓶ increase the priority of that one.
