### ISSUE TITLE
[Feature] Smarter handling of save conflicts

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#5209]
If a file is open in Typora, and then it is modified by another application, when you switch back to Typora you get:

1. no warning

2. no option to reload the file before you make new edits (thus later resulting in save conflicts that could have been easily avoided)

   🚩 If Typora auto-saved on focus change *away*, and reloaded non-conflicting changes on focus *return*, conflicting changes should almost never happen and `#3` and `#4` would be very rare. The only way conflicts would occur would be if a background process updated the file.

3. no description of the conflict (e.g. a diff) so that you can make a smart decision on whether to revert or overwrite the external changes, or do a manual merge.

4. no option to manually merge. The best you can do is use "Save as" and then open another program to merge the two versions. But because of problem `#5` and `#3`, you will waste time going through the trouble to find out there was no conflicting change. 

5. if there were no actual changes, but just a file timestamp change, you get an unnecessary warning on save. See #5208. 

## related issues
- #2354
- #2735
- #3137
- #3360
- #5208

## Most good editors do some sort of smart conflict detection and resolution

I tested five editors including Typora. See the table below. But here is a summary, ranking  best/smartest to worst:

1. **Webstorm** with ✅ autosave and ✅ auto-refresh avoids all conflicts except from cloud sync, but even then offers a ✅ diff and manual merge. Even with autosave and auto-refresh OFF, it is smart about its warnings, reloads and conflicts. *It never forces you to blindly make a choice.*

2. **MarkText** has ✅ autosave and also ✅ constantly monitors for external changes, no conflicts ever occur.  ✅ Even with cloud changes, a change made on my phone appeared within MarkText almost immediately, much like collaborative document editing systems. **So smooth.**  Because of this, it doesn't lose any points for not having diff/merge conflict resolution.

4. **BBEdit** supports ✅ auto-refresh but ❌ not auto-save, so conflicts can happen. But that's not a scary problem because it ✅ has diff/merge for conflicts. *It never forces you to blindly make a choice.* 

5. **CotEditor**: Like Webstorm avoids conflicts with ✅ autosave and ✅auto-refresh. But when conflict does occur because of cloud sync, ❌ it forces you to make a blind choice.

6. **Typora**: has ❌ no autosave and ❌ no auto-refresh. ❌ It does not even have automatic external change detection -- It only checks for external changes on save, which will be AFTER you have done a lot of work, risking all the work you've done. It shows you the same warning in all circumstances, with ❌ no option to see a diff or merge changes.

|                                                             | timestamp only external exchange                             | NO unsaved changes, switch focus, make external change, switch back to Typora, press `save` | WITH unsaved changes, switch focus, make external change, switch back to Typora, press `save` | concurrent change with no focus change (e.g. cloud sync)     |
| ----------------------------------------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| **WebStorm** (autosave **ON**, auto refresh **ON**)[^ws1]   | ignores                                                      | automatically loads external change, never conflicts         | no issue because of autosave                                 | <img width="792" alt="WebStorm - conflicting change detected" src="https://user-images.githubusercontent.com/2830093/166146806-6fff5b59-6516-4077-a11c-b2c9b2bd84cc.png"> |
| **WebStorm** (autosave **OFF**, auto refresh **OFF**)[^ws2] | <img width="274" alt="WebStorm - external change detected" src="https://user-images.githubusercontent.com/2830093/166146807-a09e8197-6ebd-4c10-a546-ebe83a257828.png"> | on refocus: <img width="274" alt="WebStorm - external change detected" src="https://user-images.githubusercontent.com/2830093/166146807-a09e8197-6ebd-4c10-a546-ebe83a257828.png"> then reloads with no warning | on refocus: <img width="274" alt="WebStorm - external change detected" src="https://user-images.githubusercontent.com/2830093/166146807-a09e8197-6ebd-4c10-a546-ebe83a257828.png"> then on reload: <img width="792" alt="WebStorm - conflicting change detected" src="https://user-images.githubusercontent.com/2830093/166146806-6fff5b59-6516-4077-a11c-b2c9b2bd84cc.png"> | on refocus: <img width="274" alt="WebStorm - external change detected" src="https://user-images.githubusercontent.com/2830093/166146807-a09e8197-6ebd-4c10-a546-ebe83a257828.png"> then on reload: <img width="792" alt="WebStorm - conflicting change detected" src="https://user-images.githubusercontent.com/2830093/166146806-6fff5b59-6516-4077-a11c-b2c9b2bd84cc.png"> |
| **MarkText** (autosave **ON**)[^MT]                              | ignores                                                      | automatically loads external change, never conflicts         | no issue because of autosave                                 | automatically loads external change, never conflicts         |
| **MarkText** (autosave **OFF**)                             | <img width="611" alt="MarkText - external change detected" src="https://user-images.githubusercontent.com/2830093/166146803-a5b16f0f-741a-4854-bba3-3ac013fa63e5.png"> | <img width="611" alt="MarkText - external change detected" src="https://user-images.githubusercontent.com/2830093/166146803-a5b16f0f-741a-4854-bba3-3ac013fa63e5.png"> | <img width="611" alt="MarkText - external change detected" src="https://user-images.githubusercontent.com/2830093/166146803-a5b16f0f-741a-4854-bba3-3ac013fa63e5.png"> Does not offer to show diff or merge. | <img width="611" alt="MarkText - external change detected" src="https://user-images.githubusercontent.com/2830093/166146803-a5b16f0f-741a-4854-bba3-3ac013fa63e5.png"> Does not offer to show diff or merge. |
| **BBEdit** (auto refresh **ON**)                            | ignores                                                      | automatically loads external change                          | <img width="523" alt="BBEdit(auto refresh ON) - conflict" src="https://user-images.githubusercontent.com/2830093/166146797-5536412c-8385-44bc-85b0-27e36a95ff84.png"> | <img width="523" alt="BBEdit(auto refresh ON) - conflict" src="https://user-images.githubusercontent.com/2830093/166146797-5536412c-8385-44bc-85b0-27e36a95ff84.png"> |
| **BBEdit** (auto refresh **OFF**)                           | <img width="269" alt="BBEdit(auto refresh OFF) - conflict" src="https://user-images.githubusercontent.com/2830093/166146796-0067d069-5049-489f-b6ad-b7a677bac1a1.png"> | <img width="269" alt="BBEdit(auto refresh OFF) - conflict" src="https://user-images.githubusercontent.com/2830093/166146796-0067d069-5049-489f-b6ad-b7a677bac1a1.png"> | <img width="269" alt="BBEdit(auto refresh OFF) - conflict" src="https://user-images.githubusercontent.com/2830093/166146796-0067d069-5049-489f-b6ad-b7a677bac1a1.png"> | <img width="269" alt="BBEdit(auto refresh OFF) - conflict" src="https://user-images.githubusercontent.com/2830093/166146796-0067d069-5049-489f-b6ad-b7a677bac1a1.png"> |
| **CotEditor** (autosave **ON**, auto refresh **ON**)[^ce1]  | ignores                                                      | automatically loads external change, never conflicts         | no issue because of autosave                                 | shows conflict and names of editing devices: <img width="447" alt="CotEditor - conflict on cloud sync" src="https://user-images.githubusercontent.com/2830093/166146798-0108b942-1b4f-4c96-8bde-06b24b1329b8.png"> |
| **CotEditor** (autosave **ON**, auto refresh **ASK**)[^ce2] | ignores                                                      | on CotEditor focus:<img width="272" alt="CotEditor - conflict on return focus" src="https://user-images.githubusercontent.com/2830093/166146799-5a109bf1-c23b-433a-990b-252a59e3d1e3.png"> If you choose "Keep", when you save you get the same dialog as Typora[^ce3] | on CotEditor focus:<img width="272" alt="CotEditor - conflict on return focus" src="https://user-images.githubusercontent.com/2830093/166146799-5a109bf1-c23b-433a-990b-252a59e3d1e3.png"> If you choose "Keep", when you save you get the same dialog as Typora[^ce3] | shows conflict and names of editing devices: <img width="447" alt="CotEditor - conflict on cloud sync" src="https://user-images.githubusercontent.com/2830093/166146798-0108b942-1b4f-4c96-8bde-06b24b1329b8.png"> |
| **CotEditor** (autosave **OFF**, auto refresh **ON**)       | ignores                                                      | on CotEditor focus:<img width="272" alt="CotEditor - conflict on return focus" src="https://user-images.githubusercontent.com/2830093/166146799-5a109bf1-c23b-433a-990b-252a59e3d1e3.png"> If you choose "Keep", when you save you get the same dialog as Typora[^ce3] | on CotEditor focus:<img width="272" alt="CotEditor - conflict on return focus" src="https://user-images.githubusercontent.com/2830093/166146799-5a109bf1-c23b-433a-990b-252a59e3d1e3.png"> If you choose "Keep", when you save you get the same dialog as Typora[^ce3] | shows conflict and names of editing devices: <img width="447" alt="CotEditor - conflict on cloud sync" src="https://user-images.githubusercontent.com/2830093/166146798-0108b942-1b4f-4c96-8bde-06b24b1329b8.png"> |
| **Typora**                                                  | <img width="272" alt="Typora conflict" src="https://user-images.githubusercontent.com/2830093/166146805-e44340c1-5cb8-4fa6-8325-ef1811641766.png">                      | <img width="272" alt="Typora conflict" src="https://user-images.githubusercontent.com/2830093/166146805-e44340c1-5cb8-4fa6-8325-ef1811641766.png">                      | <img width="272" alt="Typora conflict" src="https://user-images.githubusercontent.com/2830093/166146805-e44340c1-5cb8-4fa6-8325-ef1811641766.png">                      | <img width="272" alt="Typora conflict" src="https://user-images.githubusercontent.com/2830093/166146805-e44340c1-5cb8-4fa6-8325-ef1811641766.png">                      |

[^ws1]: WebStorm (autosave **ON**, auto refresh **ON**):<img width="718" alt="WebStorm(autosave ON, auto refresh ON) - settings" src="https://user-images.githubusercontent.com/2830093/166146809-cc24a0b5-ae4c-4f2d-a75d-523408e7014b.png">

[^ws2]: WebStorm (autosave **OFF**, auto refresh **OFF**):<img width="624" alt="WebStorm(autosave OFF, auto refresh OFF) - settings" src="https://user-images.githubusercontent.com/2830093/166146808-44fdea96-5338-4689-830d-5bf39c7f94ca.png">

[^MT]: MarkText (autosave **ON**):<img width="564" alt="MarkText(autosave ON) - settings" src="https://user-images.githubusercontent.com/2830093/166146804-26939f8c-e5c9-453a-987b-1335384a8ce8.png">

[^ce1]: CotEditor (autosave **ON**, auto refresh **ON**):<img width="561" alt="CotEditor(autosave ON, auto refresh ON) - settings" src="https://user-images.githubusercontent.com/2830093/166146802-17804855-6207-44d3-9dbb-fc55cf47ef12.png">

[^ce2]: CotEditor (autosave **ON**, auto refresh **ASK**):<img width="562" alt="CotEditor(autosave ON, auto refresh ASK) - settings" src="https://user-images.githubusercontent.com/2830093/166146801-b005c8e2-a44e-4eac-ad8d-d8e347277228.png">

[^ce3]: <img width="268" alt="CotEditor - conflict on save" src="https://user-images.githubusercontent.com/2830093/166146800-6610411a-11ba-4ccd-b1f7-ab86d96da464.png">

## Recommendations

1. Supporting both autosave on focus change away and auto-refresh on focus return provides the best user experience, as conflicts simply NEVER occur except in the rare case of editing the same document on two devices at the same time with no focus change. Of these five editors, **only Typora does not support this.**
   - In addition to autosave on focus change, WebStorm and MarkText offer the option to ***autosave periodically***, after a user selectable idle time. This is even better for avoiding cloud-sync issues. Users can always turn it off.
   - MarkText goes one step further. It ***auto-refreshes without focus change***, but every few seconds (user configurable). The result is that changes made on my phone immediately appeared on my computer and vice-versa. It behaved like a live collaborative editing tool. So smooth!

2. On detection of a *true conflict*, offer to show a diff and allow the user to do a manual merge in-app. WebStorm and BBEdit do this.

---
OS: macOS 12.3.1
Typora Version: 1.2.4

**Comment by Llemaban** [comment]
On Typora for Windows, the basics for file handling seems to be already implemented quite well.
But i agree with `#2` as if there is no unsaved content in typora, an external file change is currently (Typora 1.2.4 on Windows) loaded immediately into typora without any warning. In worst case, the user won't notice the external change and continues editing the file.
If there is unsaved content in typora and an external file change occurs, the warning appears. This is fine.

In my opinion, a warning should appear in **every** case of an external content change (and only if it is a *real* content change).

For `#3` and `#4`, +1 👍 . But again, there should always appear a warning where the user can decide what to do, don't change content automatically without any information.

When implementing this features, i would suggest to check file changes only on an `OnFocus` event when switching back to typora window. I noticed that, at least on Windows, typora seems to do this asynchronously and if the file content is changed externally, typora immediately popups a warning even if there was no focus back to the typora window.
With the current implementation, working on an md file in a git repo and a quick branch change to another branch where the md content is different and then change back to the current branch will cause typora to immediately popup the warning after the first branch change. Refer to #5208 
But in this situation, this could be avoided using the `OnFocus` event.

**Comment by abnerlee** [comment]
What's your OS?

**Comment by vassudanagunta** [comment]
> But i agree with `#2` as if there is no unsaved content in typora, an external file change is currently (Typora 1.2.4 on Windows) loaded immediately into typora without any warning.

This is NOT the case on macOS. Typora has this warning *every* time a change is made externally whether or not there were unsaved Typora changes, and the user is forced to choose which version to keep, which is not only an unnecessary and unnecessary-stress-inducing warning, it forces the user to make an impossible choice, either ignore the warning OR manually figure out whether the warning is a false one and whether or not they are about to lose data! This is totally unacceptable. 

My preference would be that it silently update external changes if there hasn't been any local concurrent changes, as those external changes are of course made by the same user, and only warn if there were concurrent changes, and even here it should give the option to auto-merge if there are no conflicts. Git behaves this way: `git pull` will silently merge changes from upstream, and will also silently merge concurrent changes that aren't in conflict.

That said, I'd be ok with your preference as long as Typora told you whether or not there was any conflict and gave the option to merge:

> a warning should appear in **every** case of an external content change (and only if it is a _real_ content change).

**Comment by vassudanagunta** [comment]
@abnerlee Abner, I'm not sure what the `limited` label means, but I consider this a serious issue. Please [see this comment](https://github.com/typora/typora-issues/issues/5208#issuecomment-1114053687)

**Comment by vassudanagunta** [comment]
@abnerlee Abner, I'm not sure what the `limited` label means, but I consider `#1`, `#2` and `#5` very serious usability issues. Markdown is mostly used by programmers and other technical people. People for whom this problem is more likely:

1. As I described in the description of #5208, the problem happens with Git usage. 
2. I use Webstorm and sometimes have the same file open in Typora (for the WYSIWYG rendering) and in Webstorm because it is part of the project repo and it contains TODOs picked, or because I have to deal with Git merge conflicts, etc. 
   
    Webstorm handles this perfectly on macOS. When I edit a file in Typora, the changes are automatically loaded into the Webstorm editor when it regains focus change, and it automatically saves its changes when it loses focus. The problem is entirely on the Typora side. 

3. Many technical people will have a document open on their desktop, but then when they are away will edit it on their phone, relying on cloud sync. 

As I wrote above:

> ***the user is forced to choose which version to keep, which is not only an unnecessary and unnecessary-stress-inducing warning, it forces the user to make an impossible choice***, either ignore the warning OR manually figure out whether the warning is a false one and whether or not they are about to lose data! This is totally unacceptable.


# I compared Typora's handling of external changes to four other editors. Typora ranks *last* 😬

Typora ranks lower than the other WYSIWYG editor, MarkText, even though MarkText is far younger. 

I updated the issue with details of my tests and the results. I spent A LOT of time on it. I hope you  take this seriously.

**Comment by abnerlee** [comment]
relates #2354

**Comment by abnerlee** [comment]
fixed in 1.3.6

**Comment by vassudanagunta** [comment]
Cool! Can you say what solution you chose? In my tests it looks like Typora syncs changes even without focus change. Are conflicts detected?

**Comment by 7u** [comment]
I tested keeping a md open in Typora and meanwhile editing it with vim. The conflict dialog popup when saving the doc, but not when switching to anther doc back-and-forth. Still want auto-fresh feature, would appreciate if you add support to it.
