### ISSUE TITLE
[Feature Request] Open Markdown links in Typora

### ISSUE THREAD

**Issue by fcabouat** [typora/typora-issues#521]
Hi,

Some static sites publishing tools, like MkDocs support "markdown links".

You can reference a document in another document and the link will be updated/converted correctly with the right url by the publishing tool. 

i.e : 
`[Link](other-file.md) -> gets converted successfully to /static-site/other-file`

It would be nice to be able to have Typora recognize and open those links/files directly in another editor window, so you could navigate your files in pseudo-WYSIWYG like in the static site you'll generate.

Cheers,

François

**Comment by abnerlee** [comment]
It is the expect behaviour. 

It's a bug that it does not work for file name with certain characters

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/207
