### ISSUE TITLE
rename file action is incomplete

### ISSUE THREAD

**Issue by jerzydziewierz** [typora/typora-issues#5212]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

When renaming a file, the file in the editor remains in unsaved state. 
In effect, when leaving the edit mode of given file, the user is asked to save file again. This is surprising because it can come a few minutes **after** the rename action has been conducted.

**To Reproduce**
1. Load existing file in a folder that has more than 1 file. 
2. Rename the current file using the "files" tab.
3. Wait 2 seconds
4. Click on **another file** in the "files" tab
Observed effect: The "save file as" dialog appears.
Expected effect: The current file is saved, new file is opened.

**Expected behaviour**

When renaming the file, the action is performed and the editor does not ask the user to save the file again at later time.

**Screenshots / Screencasts**
N/A

**Sample Markdown File**
 N/A

**Desktop (please complete the following information):**
Ubuntu 20 LTS

**Typora Version**
1.1.5 registered

**Additional context**
N/A

**Comment by abnerlee** [comment]
fixed in 1.3.6
