### ISSUE TITLE
Mac: Unable to paste inside code fences

### ISSUE THREAD

**Issue by hsuchan** [typora/typora-issues#5214]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
On my Mac, starting with Typora version 1.2.3, I am unable to paste text inside code fences.
The contextual menu doesn't show a "paste option". Version 1.1.5 works correctly.

**To Reproduce**
1. Open code fences with ```
2. Copy random text from another window
3. Right click inside code fences, the contextual menu doesn't show "paste"
4. Pasting text inside code fences using CTRL-V doesn't work either

**Expected behavior**
Pasting text inside code fences should work. Starting with v1.2.3, this no longer works on Mac.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 -Mac OS Monterey 12.3

**Typora Version**
v1.2.3

**Additional context**

**Comment by abnerlee** [comment]
fixed in 1.3.6
