### ISSUE TITLE
Copy and paste image not working in ubuntu 22.04

### ISSUE THREAD

**Issue by iiiian** [typora/typora-issues#5215]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

when using ctrl + c to copy a png or jpg in file manager, can't paste them in typora using ctrl + v.

**To Reproduce**
1. download the typora_1.2.3_amd64.deb file, install using "sudo apt install".
2. open file manager, select a png file. ctrl + c to copy
3. open typora with an empty new markdown, hit ctrl + v

**Expected behavior**
an image should appear

**Current behavior**
typora remain blank, nothing happens.

**Sample Markdown File**
I am using an empty markdown file.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/45517361/165888325-a7357f2c-134d-4f12-85f2-54058db9f9b1.png)

**Typora Version**
1.2.3

**Comment by iiiian** [comment]
I've updated to typora 1.2.4, but the problem still persist.

**Comment by flintt** [comment]
also broken in window

**Comment by abnerlee** [comment]
fixed in v1.5.x
