### ISSUE TITLE
autonumber doesn't turn off in mermaid

### ISSUE THREAD

**Issue by lxymtics** [typora/typora-issues#5216]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
There are more than one mermaid block in my markdown file, called A and B, and A is in the front of B.

I used 'autonumber' in A （see [mermaid autonumber](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers)), it worked well. However, this options also appeared int B, which is not expected.

**To Reproduce**
make a new file and copy the following code in it:
(Remember to replace `-` )
```txt

---mermaid
sequenceDiagram
autonumber
a->>b:hello
---

---mermaid
sequenceDiagram
a->>b:hello
---
```

**Expected behavior**
B is not expected to be autonumbered.

**Screenshots / Screencasts**
![pximage](https://cdn.jsdelivr.net/gh/lxymtics/static@main/20220430/pximage.4acmvhlvbb60.webp)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 64bit]

**Typora Version**
1.2.5 Newest

**Comment by lxymtics** [comment]
This is a problem of Mermaid, Thanks! [#1847](https://github.com/mermaid-js/mermaid/issues/1847)

**Comment by abnerlee** [comment]
link to #1661
