### ISSUE TITLE
[Feature] Set theme for certain files / Automatic theme changer

### ISSUE THREAD

**Issue by Namoria** [typora/typora-issues#5218]
In Typora, themes are way more than just different fonts and colors. I, for example, prefer the “Github” theme for my Linux command library; for my research and personal writing, on the other hand, I only use “Pixyll”; for my Dungeons & Dragons markdowns, I want nothing else but “Torillic” from the theme’s gallery; and so on.

As a result, I need, as of now, to switch themes constantly; that’s two additional clicks every time I switch between my categories and I do switch often. While exchanging themes is easy, it becomes, given the frequency I switch between markdown files, a chore. But not only that, my Markdowns are displayed in the “wrong” theme every time I have to switch.

So, my suggestion is a feature that allows us to specify a theme for an individual file (and, maybe, even for individual directories) in order to make Typora change themes automatically.

I’m in love with Typora; I‘ve tried many markdown editors and this is my favorite. Thanks to the developers; and have a nice day everybody!

**Comment by abnerlee** [comment]
put into #3109
