### ISSUE TITLE
[Feature] Sort files in Tree View by customized order

### ISSUE THREAD

**Issue by TweedleDim** [typora/typora-issues#5219]
Hello appmakes.io,

I've just bought Typora and I love it ! Thanks for making it.

I was looking for a tool to write stories, scenarios and game design documents. I tried scrivener and smartedit but the files management was really bad in my opinion.

But they had something that was very useful and this is my main feature request :
* Would it possible to add __a way to sort the files in the Tree View by customized or arbitrary order ?__
I would love to be able to move a file in the Tree View at a place that suits me, without the hassle of changing the numbering of all the files by hand. For instance, if I have a bunch of scenes or chapters and want to change their order. The idea here is that Typora could better help me to edit the general structure of my project, to organise my ideas and have a global insight on my stories.
* Plus, do you think you could add a way to __export more than one file at a time__ ? It would be nice to export a PDF that would put all the files in the project one after another. For me that would contribute to the same idea that I'm working on one big project that contains many fragments.

If my request sparks other persons' interest I hope you will consider adding these features. Thanks!

**Comment by abnerlee** [comment]
#3655
