### ISSUE TITLE
[Feature] It would be fantastic if Files and Outline can display simultaneously or create another window on the left to view Files or Outline

### ISSUE THREAD

**Issue by neowod** [typora/typora-issues#5222]
The amazing feature of titles in Markdown not only helps to organize contents but also can give an outlook of what's inside this file. Thus when a user clicks on a file it would be convenient that the Outline window just shows on the right of Files without need to switch between them so he can immediately have a look of the key contents of this file. Besides the default width of Files/Outline window actually can fit both of their contents together (if not it simply needs to expand a bit). Now Files and Outline are so lonely that they can't see each other :<

**Comment by abnerlee** [comment]
duplicated with #4224
