### ISSUE TITLE
Importing a image not showing in github

### ISSUE THREAD

**Issue by ItsGosho** [typora/typora-issues#5224]
Importing a image into Typora doesn't set the alt tag and thus is not shown in GitHub. It must be added manually.

**Comment by abnerlee** [comment]
Would you describe your operations?

What does "import image into Typora" mean and how an will be shown on github via "importing" into Typora?

**Comment by ItsGosho** [comment]
Pasting the image Ctrl + V will paste the image into the opened md file in typora.
When you view the same file in GitHub the image will not shown, because it is missing the **alt** tag.
