### ISSUE TITLE
[Feature]javascript support

### ISSUE THREAD

**Issue by yuhuihu** [typora/typora-issues#5225]
need javascript support  in mermaid

Then typora will be a fantastic tool ~~~~

**Comment by abnerlee** [comment]
What do you mean? you mean #4005 ?

**Comment by yuhuihu** [comment]
> What do you mean? you mean #4005 ?

I think whether it is possible to integrate javascript while typora has integrated mermaid.
The mermaid is so powerful. 
1. And we can do some summing  and counting work by JS, even more by the action interface of [mermaid interaction](https://mermaid-js.github.io/mermaid/#/gantt?id=interaction)
2. we can do some simple logic and calculation with table.

You knew jupyter-lab is something like this but more powerful and professional. 

Usually people just need a simple tool like markdown and typora.
All these functions were implemented by JS lib. 
It maybe possible done with a little effort.
