### ISSUE TITLE
ordered list in markdown exported to pdf bug in the latest version

### ISSUE THREAD

**Issue by Peterpan0927** [typora/typora-issues#5226]
When I try to convert my markdown to a pdf by typora(lastest version), I found a bug:
If I have more than ten ordered list like:
1. 
2.
3.
4.
....
10.
11.

And then the exported pdf will show ordered list like:
0.
1.
...
9.
0.
1.
2.
....
seems it can't show number **bigger than ten**? only the pdf export show this bug, html and PNG export is fine

**Comment by abnerlee** [comment]
I'm not able to reproduce this.

Could you provide more detail follows the [issue template](https://github.com/typora/typora-issues/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) ?

**Comment by Peterpan0927** [comment]
---
name: Bug report
about: additional information to reproduce the bug
title: ''
labels: ''
assignees: ''

---

- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
the original markdown should be
1.1

2. 
3. 3
4. 3
5. 3
6. 3
7. 3
8. 3
9. 3
10. 3
11. 3
and when I converted it to a pdf, then it will show as the screenshot below

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'File'
2. Click on 'export'
3. Click on 'Pdf'
4. See error on the exported pdf

**Expected behavior**
the ordered list will be from 0-9, no bigger than 10

**Screenshots / Screencasts**
<img width="886" alt="image" src="https://user-images.githubusercontent.com/26504662/167330127-5cc84352-9b35-4374-bfc6-a29772d3ded1.png">


**Sample Markdown File**
---- start -------
1. 1
2. 1
3. 1
4. 1
5. 1
6. 1
7. 1
8. 1
9. 1
10. 1
11. 1
12. 1
13. 
------ end --------

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1

**Typora Version**
1.2.4
**Additional context**
Add any other context about the problem here.
