### ISSUE TITLE
Autosave Not Saving

### ISSUE THREAD

**Issue by tundrahelix** [typora/typora-issues#5233]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
Save & Recover is enabled but sometimes will not save documents when switching to other documents in FILES list.

**To Reproduce**
1. Create new file 
2. Create document
3. Open another document from FILES list
4. Original file from step # 1 is empty, 0 bytes

**Expected behavior**
Document in step # 1 should have all the contents.

**Sample Markdown File**
Empty - 0 bytes

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1 but has happened on other versions

**Typora Version**
1.2.4 (6304) but has happened on other versions

**Additional context**

**Comment by abnerlee** [comment]
Possible to send us (hi@typora.io) a screencast about this?

**Comment by tundrahelix** [comment]
No, since it is not a constant problem and all that would be captured is an
empty, zero byte file.

**Comment by abnerlee** [comment]
What about history ? (https://support.typora.io/Version-Control/) did the file become empty after certain version ?

and empty, zero byte file means it is empty in Typora or file is also 0 bytes in Finder?

**Comment by aegonwolf** [comment]
I have the same issue. A few lines are missing, but for technical texts, this is so dangerous, I was about to handing a homework that was missing essential parts of  a proof.
