### ISSUE TITLE
[Feature] Auto-numbering accross files?

### ISSUE THREAD

**Issue by EganSolo** [typora/typora-issues#5236]
The auto-numbering works great within a file but for a document spanning several files, there does not seem to be a way to get the auto-numbering feature to continue across files.
Say I have three files
file_1
file_2
file_3
Auto numbering will start numbering in each file with the number 1. Is there a way to force the numbering in each file to start with 1 for file_1, 2 for file_2 and 3 for file_3?

**Comment by abnerlee** [comment]
You mean auto numbering of math or headings?

We may not have plan for this since it is also complicate for users to config included files and orders
