### ISSUE TITLE
Export to pdf leaves white space between text and tables

### ISSUE THREAD

**Issue by lindajavurek** [typora/typora-issues#5237]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
PDF contains multiple white spaces and table text shifts across rows.

**To Reproduce**
1. Click Export.
2. Select PDF
3. View the PDF and scroll through to view bad output as described above.

**Expected behavior**

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/51929338/167731006-e6561449-dbd0-46f9-a1c6-97b7fd5d5a0b.png)

**Sample Markdown File**
I can't send the file but can try to make another fake one. I have tried that but deleted them.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]

**Typora Version** 
1.2.5 (happens on older versions now too - with various files)

**Additional context**
It seems like this used to work for me, but now, it is not. I have spent a lot of time with Adobe and finally they said it must be the source file.

**Comment by lindajavurek** [comment]
I tried to import other themes and still had this behavior. I am trying to follow the bug report rules. This did work in the past. I have uninstalled, installed older versions, and it recreated my file from scratch. I moved from the free version to the paid version about five months ago (not sure if that matters). Please help and I will try to provide more information.
Thanks.

**Comment by lindajavurek** [comment]
There is a table directly below the line "This release....." It shows up after that large white space.

**Comment by abnerlee** [comment]
Could you provide a sample md file or send it to <hi@typora.io> ?

**Comment by lindajavurek** [comment]
Yes. Please give me a little time to pull out some information.

Thanks
L

**Comment by abnerlee** [comment]
fixed in 1.3.6
