### ISSUE TITLE
1.3.1-dev need activation every time.

### ISSUE THREAD

**Issue by tifish** [typora/typora-issues#5238]
**Describe the bug**
1.3.1-dev need activation every time. 1.3.0-dev and 1.2.5 works fine.

**To Reproduce**
1. Start Typora.
2. License dialog shows.
3. Enter license code and activate it.
4. Restart Typora.
5. License dialog shows again.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.3.1-dev

**Comment by abnerlee** [comment]
fixed in 1.3.2-dev
