### ISSUE TITLE
1.3.1-dev版本每次重新打开软件都未激活

### ISSUE THREAD

**Issue by xuanyupan** [typora/typora-issues#5239]
之前已经购买了激活码，但是1.3.1-dev版本每次都要重新输入许可证，并且我输入了几次把我的次数都给用完了。

**Comment by abnerlee** [comment]
#5238

**Comment by abnerlee** [comment]
we will fix at 1.3.2-dev

You could deactivate duplicated devices at https://store.typora.io/my
