### ISSUE TITLE
The apt-key is deprecated on Ubuntu and should update download information on the official website 

### ISSUE THREAD

**Issue by jimmy09140456** [typora/typora-issues#5243]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Followed the instructions for Linux on the official website, Ubuntu will prompt warning about apt-key is deprecated.

**To Reproduce**
1. Run `sudo apt update` on Ubuntu
2. it will prompt warning about apt-key is deprecated

**Expected behavior**
Users shouldn't see the warning message about apt-key.

**Screenshots / Screencasts**
N/A

**Sample Markdown File**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Typora Version**
1.2.4

**Additional context**
Supposed the following:
```
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
```

Should be something like:
```
wget -qO - https://typora.io/linux/public-key.asc | sudo tee /etc/apt/trusted.gpg.d/typora.asc
```

**Comment by sas2job** [comment]
See [here](https://support.typora.io/Typora-on-Linux/)

**Comment by abnerlee** [comment]
Please check https://support.typora.io/Typora-on-Linux/
