### ISSUE TITLE
[Feature] Support for math prompt boxes

### ISSUE THREAD

**Issue by Les1ie** [typora/typora-issues#5245]
Is it possible to provide a hover menu for quick search and input of some Latex mathematical symbols and syntax.
Refer to the one provided by the `Latex Workshop` extension in `VsCode`.
![image](https://user-images.githubusercontent.com/28597662/168428117-c54cceaf-ff80-4c12-9c34-124daca846c2.png)

**Comment by abnerlee** [comment]
merge into #2988
