### ISSUE TITLE
Using command to export markdown into files of other types

### ISSUE THREAD

**Issue by CheeseburgerIM** [typora/typora-issues#5248]
Same as the title above. Will it possibly come true to export markdown into files of other types with command `typora export html A.md` (For example, to generate A.html out of A.md). I would appreciate it if my suggestion is taken into account : )

**Comment by abnerlee** [comment]
duplicated with #2055

**Comment by CheeseburgerIM** [comment]
> duplicated with #2055

Thanks a lot

**Comment by CheeseburgerIM** [comment]
@abnerlee I can't find any solutions there in #2055 or #1999 or #715. So is that a feature still on your plan ?

**Comment by abnerlee** [comment]
#1999 is still open, so it is not supported yet.
