### ISSUE TITLE
[Feature] - Support for Azure Devops

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#5252]
Possible market idea for Typora to consider.  Azure Devops offers no WYSIWYG for their own MD based wiki, and appear to have no plans to improve it. As a devops user, it’s pretty rough. If you could ‘hook’ Typora into azure devops markdown editing process and publish the MD and images to azure, it might open a new market. Of course, I have no way of knowing, but I do know the feature gap is bad for devops users.

Here’s a good thread on the community feedback.

https://developercommunity.visualstudio.com/t/Wysiwyg-editing-in-Wiki/379602#T-ND10043624

**Comment by abnerlee** [comment]
We may not have plan for this since the usage maybe narrow and we may reply on private APIs of Azure Devops to put it in Azure page and make it able to read / save back to azure
