### ISSUE TITLE
Unable to load https image from local website self certified

### ISSUE THREAD

**Issue by LukeScrewdriver** [typora/typora-issues#5254]
Hi,
I have a problem with uploading images from an https (self certified) website accessible only in local network .
It tells me "image load failed".
I have made several attempts:

1. I verified the link with the browser.
2. I replaced the domain with the IP address of the server

**Comment by abnerlee** [comment]
You could try import and install your self-made certificates on your OS.

Run launch Typora with `--ignore-certificate-errors` arguments
