### ISSUE TITLE
UTF-8 file with BOM is saved without BOM.

### ISSUE THREAD

**Issue by tifish** [typora/typora-issues#5255]
**Describe the bug**
UTF-8 file with BOM is saved without BOM.

**To Reproduce**
1. Create a .md file outside Typora, which encoding is UTF-8 with BOM.
2. Open the .md file with Typora.
3. Edit and save.
4. The encoding has been changed to UTF-8 without BOM.

**Expected behavior**
BOM won't be removed automatically.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.2.5 & 1.3.2-dev

**Comment by abnerlee** [comment]
fixed in 1.3.6
