### ISSUE TITLE
Don't support webp?

### ISSUE THREAD

**Issue by aizigao** [typora/typora-issues#526]
in typora
![image](https://cloud.githubusercontent.com/assets/14126445/22778406/cb1d6872-eef1-11e6-992b-027ea81e5393.png)

use vscode 
![image](https://cloud.githubusercontent.com/assets/14126445/22778453/ed730a12-eef1-11e6-8961-e2221ad5157d.png)

**Comment by abnerlee** [comment]
on macOS or other os?

**Comment by aizigao** [comment]
yeah， on macOS。。could support in next version ? 😞

**Comment by aizigao** [comment]
:shipit:

**Comment by abnerlee** [comment]
It is caused by safari/webkit does not support webp (http://caniuse.com/#search=webp)

I will close this, since it is a upstream issue, typora will support webp when safari/macOS support this format.
