### ISSUE TITLE
[Feature] AutoNumber Problem in Mermaid

### ISSUE THREAD

**Issue by lxymtics** [typora/typora-issues#5260]
Hi!

I have found the problem metioned  in #5216  has be solved a few days ago see [Release](https://github.com/mermaid-js/mermaid/releases/tag/9.1.0) and [Mermaid#2981](https://github.com/mermaid-js/mermaid/pull/2981)

Shall we update the dependency and resolve this problem?

Thanks!

**Comment by abnerlee** [comment]
we updated mermaid lib in 1.4.4
