### ISSUE TITLE
"Learn Spelling" does not work for words with curly quotes

### ISSUE THREAD

**Issue by ellbur** [typora/typora-issues#5261]
Type a word with a curly quote in it:

> Aoeu’aoeu

Right click on the word and select "Learn Spelling." The word remains red-underlined.

By contrast, if a straight quote is used:

> Aoeu'aoeu

then "Learn Spelling" behaves as expected. In fact, if "Learn Spelling" is used on a word with a straight quote, the learned spelling will apply even if the word is later typed with a curly quote.

**Comment by abnerlee** [comment]
Which OS and language do you use?

**Comment by ellbur** [comment]
Windows 10 and American English.

**Comment by abnerlee** [comment]
fixed in 1.3.6
