### ISSUE TITLE
Themes no longer function on macOS. Fonts not chosen correctly.

### ISSUE THREAD

**Issue by masoodkamandy** [typora/typora-issues#5262]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----

**Describe the bug**

Today I opened up Typora only to find that all of my theme is no longer work. It seems that my program is locked into a default view. Whenever I switch themes, nothing happens. I have taken a look at the console and copied them error messages that seem to be relevant. They are below:

```
error	12:45:52.758491-0700	kernel	Sandbox: com.apple.WebKit(1182) deny(1) file-issue-extension target:/Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/pixyll.css class:com.apple.app-sandbox.read
error	12:45:52.758943-0700	kernel	Sandbox: com.apple.WebKit(1182) deny(1) file-issue-extension target:/Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/base.user.css class:com.apple.app-sandbox.read
error	12:45:52.759291-0700	kernel	Sandbox: com.apple.WebKit(1182) deny(1) file-issue-extension target:/Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/pixyll.user.css class:com.apple.app-sandbox.read
error	12:45:52.763416-0700	kernel	Sandbox: com.apple.WebKit(1184) deny(1) file-read-data /Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/pixyll.css
error	12:46:01.855714-0700	kernel	Sandbox: com.apple.WebKit(1182) deny(1) file-issue-extension target:/Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/newsprint.css class:com.apple.app-sandbox.read
error	12:46:01.856389-0700	kernel	Sandbox: com.apple.WebKit(1182) deny(1) file-issue-extension target:/Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/base.user.css class:com.apple.app-sandbox.read
error	12:46:01.856801-0700	kernel	Sandbox: com.apple.WebKit(1182) deny(1) file-issue-extension target:/Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/newsprint.user.css class:com.apple.app-sandbox.read
error	12:46:01.857729-0700	kernel	Sandbox: com.apple.WebKit(1184) deny(1) file-read-data /Users/xxxxxxxxxxxxx/Library/Application Support/abnerworks.Typora/themes/newsprint.css
```

I have not modified the themes in anyway. These are all default.

Because this seems like a file access error, I did give Typora full disc access to see if that worked. It does not work.

I also tried rebuilding my font cache. This also did not help.

**To Reproduce**

Because I cannot find instances of these errors existing Github issues I am not certain that this error will be reproducible on any other computer. That said, I do not know how to solve this problem. I have tried reinstalling Typora and I have tried removing all preferences an application support files. I have also tried downloading the latest development version, but that does not work either.

**Expected behavior**

Until today, Typora behaved as expected. I would use the theme that I like, everything appears normally.

**Screenshots / Screencasts**

Below is a screenshot what the missing fonts look like. This is also one every theme looks like. No matter how I change the themes, it always looks like this. The sections with ?'s are inline code.

![Screen Shot 2022-05-21 at 12 56 58 PM](https://user-images.githubusercontent.com/15914630/169667174-754985ac-8d90-4b00-b848-91f60ce14f59.png)

**Sample Markdown File**

This error happens no matter which markdown file I open, so providing a marked on file will be unlikely to help. I have also tested these markdown files VSCode and all of them work properly.

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1 

**Typora Version**
e.g: 1.3.1-dev and 1.2.4 Paid

**Additional context**
None.

**Comment by abnerlee** [comment]
Does 1.4 works?

Do you used to install any custom fonts, or did you block Typora from loading resources?

**Comment by masoodkamandy** [comment]
The problem remains in 1.4.4 and macOS 12.5.1. I'm not sure how I would have blocked resource loading. I think this has to do with something else I have installed on my computer, so I'll report back if/when I find it. I use Typora extensively on my work computer and it's fine, so this is about my particular setup.

**Comment by abnerlee** [comment]
You can try

1. enable menu bar → Help → debug mode
2. right click on the ? and choose "Inspect Element"
3. switch to Network tab and Console tab to see if there are load fail errors for .woff file.
