### ISSUE TITLE
[Feature]Make outline auto sync with page more responsive

### ISSUE THREAD

**Issue by jiewangjs** [typora/typora-issues#5264]
As the title spills out, right now the auto sync of outline is ok, but seems missing out the middle process while scrolling the page.
I reckon probably the mechanism right now is just to respond to the beginning and ending postion of the page. 
If realtime responding to the page scrolling can be implemented, this request is possible. by the way, word has the capability as this request.

**Comment by abnerlee** [comment]
> As the title spills out, right now the auto sync of outline is ok, but seems missing out the middle process while scrolling the page.

Sorry, but I'm not fully understand what you mean. Could you provide more details or maybe a screencast to help explain  it?

**Comment by jiewangjs** [comment]
typora:
https://user-images.githubusercontent.com/11204422/170414630-54f65a71-45d8-481f-9e50-bafc8912d6a2.mp4
word:
https://user-images.githubusercontent.com/11204422/170414687-1a2ca61b-1a0e-4d51-9089-fe1f70a2483a.mp4

Word will iterate through every outline entry while scrolling

**Comment by abnerlee** [comment]
The highlighted outline in Typora is the header close to the top of the editor, since user would usually look at the above half of the window. So if a header is near to the bottom of the window, the outline will not highlight it.
