### ISSUE TITLE
A Typora Activation Problem

### ISSUE THREAD

**Issue by 2s-penalty** [typora/typora-issues#5267]
I use Typora 1.2.5 in China. I have no access to the [[official website ](https://github.com/typora/typora-issues/issues/typora.io)](typora.io) without VPN or proxy, so I download the app and purchase typora on the [[Chinese official website](https://github.com/typora/typora-issues/issues/typoraio.cn)](typoraio.cn).

After purchasing Typora and receiving the license key, I still can't activate typora, with the error information: "Failed to access the license server. Please check your network or try again later."

Then I turned to [[Activate Typora](https://support.typoraio.cn/activation/#register--activate-typora)](https://support.typoraio.cn/activation/#register--activate-typora) for help.

I've checked "Use Typora Server in China" in the preferences settings, but it doesn't work. I've also tried to disable my firewall and run Typora in Administer mode, but it doesn't work either. Then I tried [[Offline Activation](https://store.typora.io/offline)]( https://store.typora.io/offline) by using VPN, and it shows that I've already activated 3 devices, so I can't get the activation token. But in fact, I haven't activated any devices yet.

I've tried a lot of times up to now, but none of them worked. So what should I do now to activate Typora?

**Comment by abnerlee** [comment]
Could you send your license code or email to hi@typora.io? We would remove your activated devices (they may be activated in server, but met errors when sending response to your device) and then you can try offline activation again.
