### ISSUE TITLE
Windows Explorer reports "folder in use" by another program (Typora.exe), Why?

### ISSUE THREAD

**Issue by fuweichin** [typora/typora-issues#5268]
Steps to Reproduce:
This is the structure of my working folder
   + client-info/
     + README.md
     + src/
     + locales/

and I opened README.md a few days ago.

1. drag/move 'locales' into 'src', Windows Explorer says "some file/folder in the folder is opened by another program"
2. I find out the progam (it's Typora.exe) with Windows Resource Monitor.
3. close the Typora window of README.md
4. then I can move 'locales' into 'src'

Expected Result:
Since there are not any links/images in README.md, and there are just some .json, .js files under locales. I don't know for what purpose Typora would occupy a sibling folder of the opened file README.md.

Additional Information:

Typora for Windows x64 version 1.0.2

Attachments:

![typora-holds-file-handle-1](https://user-images.githubusercontent.com/1687235/170818996-e4f87f31-253a-48ff-a43e-c6880d1d021d.png)

![typora-holds-file-handle-2](https://user-images.githubusercontent.com/1687235/170819072-555892f1-8d97-4d4e-a45a-7759a9e375f6.png)

**Comment by abnerlee** [comment]
try use 1.2.5?
