### ISSUE TITLE
Cannot import photos in base64

### ISSUE THREAD

**Issue by thomaswcy** [typora/typora-issues#5269]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Can't insert base64 pictures.

**To Reproduce**

I've tried `![](data:image/png,base64,xxx)`, `<img src="data:image/png,base64,xxx">`, but it wont work. Typora doesn't think it as base64, instead it recognized it as plain text.
The only way worked is :
```
![][01]
[01]:data:image/png,base64,xxx
```
But typora will crash in a few seconds, or it will crash suddenly if you changed to source code mode. Also, it will show base64 code at the end of the file.

**Expected behavior**
I expected `![](data:image/png,base64,xxx)` will work, and typora will show the photo.

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit, MacOS Big Sur

**Typora Version**
1.1.4

**Additional context**
Feature request: add option "change photo to base64 format after inserting" in the settings

**Comment by thomaswcy** [comment]
I think I've found the problem. Typora won't recognize base64 codes that are too long. I've tried, a shorter base64 code will work. So what Typora can work on is to recognize long base64 code and do not crash.

**Comment by abnerlee** [comment]
#88
