### ISSUE TITLE
Link to a heading with `.` in a different file

### ISSUE THREAD

**Issue by yurusanP** [typora/typora-issues#5270]
**Describe the bug**

Link to a heading in a different file should have been supported. See [this issue](https://github.com/typora/typora-issues/issues/1231).

However, when the heading in a different file contains `.` (a period anywhere), the link doesn't work.

**To Reproduce**

For example, create a file named `experiment.md` and a heading `A.` in it.

The following will be shown if I try to create a link in another file using `[link](experiment#A.)`.

> Cannot open location `<my home directory>/experiment#A.`, do you mean https://experiment#A. ?Learn More...

**Expected behavior**

The link in another file should work with a period in the heading.

**Desktop (please complete the following information):**

OS: Windows 11 64 bit.

**Typora Version**

Version 1.2.5.

**Comment by abnerlee** [comment]
duplicated with #5075
