### ISSUE TITLE
Cannot Quit Typora from MacOS using command-q key combo

### ISSUE THREAD

**Issue by restagner** [typora/typora-issues#5271]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Each time I use the command-q key combination on my MacOS, it does not quit Typora

**To Reproduce**
1. open Typora
2. File -> Open and select file to open
3. command-q to quit

**Expected behavior**
Typora should quit

**Desktop (please complete the following information):**
 - MacOS Catalina v10.15.7

**Typora Version**
1.2.4

**Comment by abnerlee** [comment]
Could you provide a screencast?

**Comment by 1999FordFocus** [comment]
I'm experiencing the same issue. 

In my case, I think all shortcuts are disabled when the current focus is on the toolbar, sometimes maybe on the file tree view, but anyway, it's something about the focus.

**Comment by abnerlee** [comment]
@1999FordFocus Could you provide a screencast?

**Comment by 1999FordFocus** [comment]
> @1999FordFocus Could you provide a screencast?

https://user-images.githubusercontent.com/9652173/172547833-07372c8d-64a7-424d-bf47-1a4a27f452c5.mp4

**Comment by abnerlee** [comment]
Does it work from menu bar `Typora` -> `Quit` ? Does `command` + `Q` displayed right side to `quit` menu item?
Does change to built-in theme (like Github) fixes this?

**Comment by 1999FordFocus** [comment]
- Does it work from menu bar Typora -> Quit ?
   Yes, both `command q` and `control command 1/2/3`. I also noticed that when I pressed the shortcut, the mouse disappeared at the same time.
- Does command + Q displayed right side to quit menu item?
   Yes.
- Does change to built-in theme (like Github) fixes this?
   No.

**Comment by abnerlee** [comment]
seems fixed in 1.4.4
