### ISSUE TITLE
Jump to last heading when clicking on different heading in the oultine (Video).

### ISSUE THREAD

**Issue by Cyanymous** [typora/typora-issues#5272]
**Version:** Typora 1.2.5 on Windows 10 21H2.

When I click on a heading in the outline Typora jumps to the chosen heading but then quickly jumps back to where I was before. In the video you can see that at first it works but in the second attempt it does not.
The bug seems to be around for quite some time now, at least for me. If someony already opened an issue about this I am sorry, I could not find one (maybe some can merge theses or something like that, I am new to GitHub).

[Click here to see the video](https://youtu.be/sFm8gj0Uj5M)

**Comment by abnerlee** [comment]
Does v1.4.4 fix this?

**Comment by Cyanymous** [comment]
Yes, it does. 👍
