### ISSUE TITLE
unstable images and preview flicker

### ISSUE THREAD

**Issue by keitasumiya** [typora/typora-issues#5273]
## Problem
The size of inserted images are unstable freaquently. 
At that time, the preview shows with a flicker lite an attached video. 

## Reproduction
1. launch typora
2. write some sentences
3. insert some images
4. repeat above writing and inserting
5. image size and preview change to unstable

It looks like this flicker occurs at the time when images exist on the top of the preview area. 

## Environment
- macOS Monterey, version 12.3.1
- MacBook Air (M1, 2020)
- 16GB memory
- 2TB SSD
- typora 1.2.4 (6304)

https://user-images.githubusercontent.com/15891018/171991986-b0f88117-f289-4e4a-9a73-877f93ca3426.mp4

**Comment by abnerlee** [comment]
Possible to send us the sample md file? And what about 1.3.3-dev?

**Comment by abnerlee** [comment]
Possible to provide the sample file for the new issue?

**Comment by keitasumiya** [comment]
Thanks so much!!
The file size is so large (115MB), so I put my dropbox link here. 
https://www.dropbox.com/s/u6268zipuxukgd6/sample.zip?dl=0

**Comment by abnerlee** [comment]
@keitasumiya Hi, which theme do you use? How about built-in themes? I tested with Github theme, all seems ok so far...

**Comment by keitasumiya** [comment]
@abnerlee 
I usually use my special theme that I made from a built-in github theme. 
I also tested all built-in themes but all themes were slow... Therefore I think this problem doesn't depend on theme.

**Comment by abnerlee** [comment]
You can preview the fix on https://typora.io/releases/dev

**Comment by abnerlee** [comment]
fixed in 1.4.4
