### ISSUE TITLE
Typora not working on macOS 13

### ISSUE THREAD

**Issue by rena-minami** [typora/typora-issues#5276]
- [x] Searched existing issues to avoid creating duplicates.

 - [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

 - [x] Searched http://support.typora.io/

----

**Describe the bug**

The software does not work on macOS 13.0 beta 1 (22A5266r). After the software opens, it freezes at a white screen, unable to open any document or folder, nor create new and start writing.

**To Reproduce**
Open the software on macOS 13.0

**Expected behavior**
The software functioning normally.

**Screenshots / Screencasts**
N/A

**Sample Markdown File**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 13.0 beta 1 (22A5266r)

**Typora Version**
1.2.4 (6304), 1.3.3-dev

**Additional context**
It would be nice to have a beta build that runs on the new OS

**Comment by abnerlee** [comment]
I tested on Parallels Desktop on my M1 macbook pro, it is not working.
But when I tested on my old Intel Macbook pro, it is working.

so @rena-minami What's your mac CPU, did you use it in VM or outside VM?

**Comment by LoveFromCodes** [comment]
I met the same problem too.

I use MacBook Air M1 with macOS 13 beta 1. 
And I use it in origin OS not in any VM.

**Comment by rena-minami** [comment]
@abnerlee thanks for your response. I am using the 2021 Macbook Pro with M1 Max chip. So it seems to be an apple silicon specific issue

**Comment by Viccccccqq** [comment]
> @abnerlee thanks for your response. I am using the 2021 Macbook Pro with M1 Max chip without VM. So it seems to be an apple silicon specific issue.
hi, bro! rosetta can fix that。Run with rosetta。https://support.apple.com/zh-cn/HT211861

**Comment by Siirui** [comment]
> > @abnerlee thanks for your response. I am using the 2021 Macbook Pro with M1 Max chip without VM. So it seems to be an apple silicon specific issue.
> > hi, bro! rosetta can fix that。Run with rosetta。https://support.apple.com/zh-cn/HT211861

Thanks for your solution! It works on my M1 Macbook air with MacOS 13 beta 1.

**Comment by uniartisan** [comment]
> @abnerlee thanks for your response. I am using the 2021 Macbook Pro with M1 Max chip without VM. So it seems to be an apple silicon specific issue.
> hi, bro! rosetta can fix that。Run with rosetta。https://support.apple.com/zh-cn/HT211861

Thanks for your solution! Run with Rosetta can temporarily solve this problem. Looking forward to solve this specific issue on apple silicon .

**Comment by Viccccccqq** [comment]
The Intel and Apple platforms are included in the Typora installation package. On the M1 chip, the installation package of the apple platform cannot work, and the installation package of the Intel platform can only be made to work with Rosetta.
(When you clean the garbage, don't clean the Intel platform installation package. I have verified).

**Comment by LovelyLM** [comment]
can work

**Comment by abnerlee** [comment]
Does 1.3.6 fix this? In my test v1.3.6 works fine now.

**Comment by rena-minami** [comment]
@abnerlee I am sorry if I missed something, but where can I download 1.3.6? The dev release page only has 1.3.3 as the latest now.

**Comment by Viccccccqq** [comment]
> @abnerlee I am sorry if I missed something, but where can I download 1.3.6? The dev release page only has 1.3.3 as the latest now.

https://typora.io/releases/all

**Comment by rena-minami** [comment]
Yes I can confirm that 1.3.6 works on macOS 13 with M1 without Rosetta

**Comment by Viccccccqq** [comment]
<img width="488" alt="截屏2022-06-12 12 46 53" src="https://user-images.githubusercontent.com/51349831/173214926-a6691166-504d-43b0-90cc-b7a13e39870b.png">
