### ISSUE TITLE
Check Spelling While Typing greyed out

### ISSUE THREAD

**Issue by freddyheppell** [typora/typora-issues#5279]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The option Edit > Spelling and Grammar > Check Spelling While Typing is greyed out. Spelling errors are fixable by right clicking, but not highlighted.

**To Reproduce**
1. Create a document with a spelling error
2. Open the Edit > Spelling and Grammar menu

**Expected behavior**
Check Spelling While Typing should be an option which can be toggled. Mistakes are marked properly.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/1475568/172431398-f14a5f31-d3f4-429f-8dbf-44ab41810579.png)

Right clicking on a misspelt word:

![image](https://user-images.githubusercontent.com/1475568/172431309-856a2f54-8e44-4f52-9de9-fa03180d8ed1.png)

**Sample Markdown File**
All markdown files, saved or unsaved, have this bug for me.

**Desktop (please complete the following information):**
 - OS: macOS 12.4

**Typora Version**
e.g: 1.2.4

**Additional context**
* System language is English (UK)
* System-wide autocorrection of spelling is disabled

**Comment by abnerlee** [comment]
You could try exit Typora, and enable spellcheck in System Preferences → Keyboard → Text

**Comment by freddyheppell** [comment]
I checked and it's already turned on

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1475568/174195176-09a22227-2df1-4588-9274-98b378208263.png">

I've also just upgraded to Typora 1.3.6 and it still happens.
