### ISSUE TITLE
Adding a shortcut to save all open documents

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#528]
Should take just a few minutes to do, but would be highly helpful (at least for me) -- just an ability to save all open documents.

It would be probably cmd + alt + S, as for example in Atom, Visual Studio Code, and many other apps.

Thanks! 😄

**Comment by AlexPasternak** [comment]
TextMate as well, and that's the golden standard for me for many things :-)

**Comment by abnerlee** [comment]
supported in new release
