### ISSUE TITLE
Network image load failed

### ISSUE THREAD

**Issue by nichelnich** [typora/typora-issues#5280]
**Describe the bug**
Network image load failed.  The browser can be opened normally
pic url：https://gitee.com/nichelnich/notepic/raw/master/000000453254325.png

**Screenshots / Screencasts**
![1](https://user-images.githubusercontent.com/6030793/172507695-edc37a7a-ee87-4824-8dbf-8ad9d9c8e2cf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.2.5

**Comment by abnerlee** [comment]
I cannot open https://gitee.com/nichelnich/notepic/raw/master/000000453254325.png, it returns {"code":"40310014","msg":"invalid Referer header"}
