### ISSUE TITLE
[Feature] Support custom links {#like-this}

### ISSUE THREAD

**Issue by victor-gp** [typora/typora-issues#5282]
Would you consider supporting this syntax for custom links? At least in headings.

Seems like it is [pretty common](https://www.markdownguide.org/extended-syntax/#heading-ids). Interestingly enough, Typora already makes the `{#custom-link}` part invisible in headings like:

```md
## A heading {#custom-link}
```

The custom link-wannabe is processed as `<span md-inline="attr" class="md-attr md-expand"> ... </span>`. And `.md-attr` is styled as invisible. Maybe you can add an #id on the same piece of code that adds the `md-attr` class? Or target this class and add an id?

I see there's already [support for custom links in raw HTML](https://support.typora.io/Links/#internal-links), but this other syntax is a bit more handy to type and easier to read in a raw MD document.

**Comment by abnerlee** [comment]
seems a part of #249
