### ISSUE TITLE
Loading a GitHub markdown style file with collapsed HTML block breaks the renderer

### ISSUE THREAD

**Issue by dramoz** [typora/typora-issues#5283]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
Loading a GitHub markdown style file with collapsed HTML block breaks the renderer

**To Reproduce**
Load the attached file, or create the file manually and remove auto-indent while editing.

**Expected behavior**
HTML code should stay inside HTML block rendered view, but instead shows outside

**Screenshots / Screencasts**
Code:
![Markdown](https://user-images.githubusercontent.com/34524370/172634247-a7760e5a-344b-4b47-892c-b43bb1360527.png)

After rendering:
![Markdown-rendered](https://user-images.githubusercontent.com/34524370/172634273-c80ef80a-9011-4244-b540-8af6637a1da0.png)

**Sample Markdown File**
[Collapsed.md](https://github.com/typora/typora-issues/files/8862169/Collapsed.md)

**Desktop (please complete the following information):**
 - OS: [Windows11, Linux Ubuntu 20.04]

**Typora Version**
e.g: 1.2.5

**Comment by abnerlee** [comment]
duplicated with #4391
