### ISSUE TITLE
How is now the mechanism to upload a new theme?

### ISSUE THREAD

**Issue by mcesar-rlacruz** [typora/typora-issues#5285]
Hi,

Followed the same method I used a year or so ago, but now the pull request over [https://github.com/typora/theme.typora.io](https://github.com/typora/theme.typora.io) seems to fail because some checks have failed. Apparently somebody (me?) needs to install some SSH key and somebody in the Typora Team on Vercel must autorize the fork deployment. 

What is all these?

The fork is [https://github.com/typora/theme.typora.io/pull/280](https://github.com/typora/theme.typora.io/pull/280)

**Comment by abnerlee** [comment]
https://github.com/typora/theme.typora.io/pull/280 is valid, nothing needs to be changed
