### ISSUE TITLE
typora table border is missing

### ISSUE THREAD

**Issue by petercheng689** [typora/typora-issues#5287]
When i use the Typora to create a table, the border  cannot be displayed. I can only see it in the print preview, and its quote also does not work. The software version is 1.2.4, and the operating system is macOS Monterey 12.1. I have tried other versions of Typora, and there is the same issue, which cannot be solved by repeated installation and uninstallation.

like :

table border is missing, only button
<img width="528" alt="image" src="https://user-images.githubusercontent.com/33661325/173030276-62f059cb-18a4-4711-867b-5021d5381d85.png">
but table border is normal in the print preview
<img width="621" alt="image" src="https://user-images.githubusercontent.com/33661325/173030574-7aa9158d-8e5f-4b5d-8e97-d9313a15a040.png">

**Comment by abnerlee** [comment]
Use a built-in theme?

**Comment by petercheng689** [comment]
the default github theme，and i try to switch other theme, but it also doesn't work.

**Comment by abnerlee** [comment]
Would you provide screenshots if you use Night or Newsprint theme? Did you use custom CSS? Does exit Typora and delete /Users/abner/Library/Application Support/abnerworks.Typora/ works?
