### ISSUE TITLE
New "Copy or cut the whole line..." option has issues

### ISSUE THREAD

**Issue by nicolasleperlier** [typora/typora-issues#5294]
- [X] Searched existing issues to avoid creating duplicates.
- [X] Confirmed that it can be reproduced in built-in themes without customized css.
- [X] Searched http://support.typora.io/

----

**Describe the bug**
New "copy or cut the whole line that  have cursors on them" option has issues

**To Reproduce Cut issues**
1. Enable  the 'Copy or cut the whole lines that have cursors on them, if there is no selection when doing copy / cut' option in the Editor section of the Preferences menu
2. Place cursor on a line, without selecting anything
3. Press Ctrl + X
4. Press Ctrl + V elsewhere

**Expected behavior**
The cut line should be pasted into the new line. It is not.

**To Reproduce Copy issues**
1. Enable  the 'Copy or cut the whole lines that have cursors on them, if there is no selection when doing copy / cut' option in the Editor section of the Preferences menu
2. Place cursor on a line, without selecting anything
3. Press Ctrl + C
4. Press Ctrl + V elsewhere

**Expected behavior**
The copied line should be pasted into the new line. It is but there is also an added line break, which should not happen right?

**Desktop**
 - OS: Windows 11 64bit

**Typora Version**
1.3.6

**Comment by abnerlee** [comment]
I tested VS Code, Ctrl + C on one line and paste it elsewhere, it will include a line break. So I think it is the expected behavior.

**Comment by nicolasleperlier** [comment]
Weird.. The Cut still doesn't work though.
