### ISSUE TITLE
[Feature] The place of the table insertion should be placed in the middle

### ISSUE THREAD

**Issue by ChaXxl** [typora/typora-issues#5296]
### I think this window should be placed in the middle so that it is easier to enter the line and column numbers

![image](https://user-images.githubusercontent.com/40326898/173261078-39af0e01-41e8-46a0-a55a-b35acfb5b6f1.png)

**Comment by abnerlee** [comment]
We don't have plans to change the position since it will blur your background and auto focus to your input.

But you can still modify this via https://support.typora.io/Add-Custom-CSS/
