### ISSUE TITLE
[Feature] Tagging with @

### ISSUE THREAD

**Issue by mosesontheweb** [typora/typora-issues#5297]
Hi,
haven't found a similar subject, so do you thing that it might be possible to add some kind of tag support (like @username or @subject) which are searchable? I ask this because I use Typora as my favorite note taking tool and log book and therefore there are some cases where this kind of feature might be practicable.

Regards, Thomas

**Comment by JocelynTuohy** [comment]
Tagging like **#this** would be even better since it's more standard among markdown apps, but I'd take any kind of tags! Even better would be: [nested tags like Bear](https://bear.app/faq/Tags%20&%20Linking/Nested%20Tags/).

**Comment by abnerlee** [comment]
put into #1393 for tag support feaures.
