### ISSUE TITLE
Code Blocks get destroyed

### ISSUE THREAD

**Issue by DanBennettUK** [typora/typora-issues#53]
This is a strange one that I have *tried* to work out why it happens but I just can't.

Randomly, Code blocks are being destroyed. Sometimes the code inside them or sometimes either the start or end of the markdown syntax gets removed, forcing all text below it to be within a code block.

What ends up happening is:

```
    ```shell
    Code here

Normal text
Normal text
```

Or code is removed

```
    ```shell
    ```
Normal text

```

On Windows 10 x64.

The only thing I can put it down to is it seems to happen when Typora decides to use a high amount of CPU.

I've had to fix this in Notepad a few times. I've now had to stop using it for a while :(

**Comment by abnerlee** [comment]
@DanBennettUK Sorry for this bug.

How did you create a code block? By typing ``` + Return or use menu/shortcut key?

**Comment by DanBennettUK** [comment]
@abnerlee By typing - quicker! :smile: 

So for example I'd type ``` followed by the type of code it is (shell/php/html/css/blah...)

**Comment by abnerlee** [comment]
@DanBennettUK Thanks for the reply.

I think "Typora decides to use a high amount of CPU" maybe related to this bug. Did you write Math Block on your article? 

If you don't mind, could you send a copy of your *.md file which has may cause the high CPU usage to <hi@typora.io> ?  Of course, we will only use your file for debugging purpose.

**Comment by DanBennettUK** [comment]
@abnerlee Nope, no math block used. I saw another issue about the math block so I checked to see I've got it turned off.

The file is also 24,000 words so far. Perhaps that's a troubling factor?

I can't really send it sadly as it's very work based! Sorry! :sad:

**Comment by DanBennettUK** [comment]
I found what was causing this. Sometimes when I add the code type (e.g. typing "sh" after ` ``` `), sometimes the box that appears below the code block stating the code type does not disappear. 

If this does not disappear, when the file is saved the text in the code block is not saved with it.

Will look out for this on the new update. But posting this just in case.

**Comment by abnerlee** [comment]
@DanBennettUK could you still reproduce this in latest version ?

**Comment by DanBennettUK** [comment]
@abnerlee Nope - cannot reproduce on latest Windows version (v0.8.3). Can safely close! :+1:
