### ISSUE TITLE
[Feature] scroll bar of the code block and strengthen the source code editing mode

### ISSUE THREAD

**Issue by yidai321** [typora/typora-issues#5300]
It is hoped that a horizontal scroll bar can be added to the code block in the future version. Secondly, since it is easy to stutter when there are a large number of words, it is best to strengthen the color distinction of the source code editing mode.

**Comment by abnerlee** [comment]
> It is hoped that a horizontal scroll bar can be added to the code block in the future version. 

You can set in Preferences Panel → Markdown → Code Fences
