### ISSUE TITLE
The tooltip box indicating the path of folders in recent places menu is not visible

### ISSUE THREAD

**Issue by whuji** [typora/typora-issues#5301]
Hello,

On Linux, using the latest version of Typora, when I mouse over an element on the recent places menu, the tooltip shows and disappears instantly so that I can't read the path of the folder.
It is an issue when one have multiple folders with the same name (for example: doc) in different places (for example: different git repos).

I recorded a screen video of the issue, attached to this ticket.

The issue was already present in previous versions of Typora.

Regards

https://user-images.githubusercontent.com/2234501/174044395-ca588670-fed3-4853-b651-cba1b9347755.mp4

**Comment by abnerlee** [comment]
fixed in 1.4.4
