### ISSUE TITLE
[Feature] set the default browser for opening links

### ISSUE THREAD

**Issue by SeyeeL** [typora/typora-issues#5305]

**Comment by ironhak** [comment]
Links already open in your system default browser....

**Comment by SeyeeL** [comment]
I want to set a different browser with my system





------------------ Original ------------------
From: ironhak ***@***.***&gt;
Date: Sun, Jun 26, 2022 6:30 PM
To: typora/typora-issues ***@***.***&gt;
Cc: SeyeeL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [typora/typora-issues] [Feature] set the default browser foropening links (Issue #5305)





 
Links already open in your system default browser....

**Comment by ironhak** [comment]
Then change it on your computer settings.

**Comment by SeyeeL** [comment]
I mean，keep the system setting，open in typora is another setting





------------------ Original ------------------
From: ironhak ***@***.***&gt;
Date: Sun, Jun 26, 2022 6:39 PM
To: typora/typora-issues ***@***.***&gt;
Cc: SeyeeL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [typora/typora-issues] [Feature] set the default browser foropening links (Issue #5305)





 Then change it on your computer settings.
 On 26 Jun 2022, 12:34 +0200, SeyeeL ***@***.***&gt;, wrote:
 &gt; I want to set a different browser with my system
 &gt;
 &gt;
 &gt;
 &gt;
 &gt;
 &gt; ------------------ Original ------------------
 &gt; From: ironhak ***@***.***&amp;gt;
 &gt; Date: Sun, Jun 26, 2022 6:30 PM
 &gt; To: typora/typora-issues ***@***.***&amp;gt;
 &gt; Cc: SeyeeL ***@***.***&amp;gt;, Author ***@***.***&amp;gt;
 &gt; Subject: Re: [typora/typora-issues] [Feature] set the default browser foropening links (Issue #5305)
 &gt;
 &gt;
 &gt;
 &gt;
 &gt;
 &gt;
 &gt; Links already open in your system default browser....
 &gt;
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt;
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by ironhak** [comment]
Ok. I think this is a very limited need that most of the users will find completely useless. Why do you need that?

**Comment by SeyeeL** [comment]
because I am a Engineer，I work in one browser and view the web in another





------------------ Original ------------------
From: ironhak ***@***.***&gt;
Date: Sun, Jun 26, 2022 6:45 PM
To: typora/typora-issues ***@***.***&gt;
Cc: SeyeeL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [typora/typora-issues] [Feature] set the default browser for opening links (Issue #5305)





 Ok. I think this is a very limited need that most of the users will find completely useless. Why do you need that?
 On 26 Jun 2022, 12:42 +0200, SeyeeL ***@***.***&gt;, wrote:
 &gt; I mean，keep the system setting，open in typora is another setting
 &gt;
 &gt;
 &gt;
 &gt;
 &gt;
 &gt; ------------------ Original ------------------
 &gt; From: ironhak ***@***.***&amp;gt;
 &gt; Date: Sun, Jun 26, 2022 6:39 PM
 &gt; To: typora/typora-issues ***@***.***&amp;gt;
 &gt; Cc: SeyeeL ***@***.***&amp;gt;, Author ***@***.***&amp;gt;
 &gt; Subject: Re: [typora/typora-issues] [Feature] set the default browser foropening links (Issue #5305)
 &gt;
 &gt;
 &gt;
 &gt;
 &gt;
 &gt; Then change it on your computer settings.
 &gt; On 26 Jun 2022, 12:34 +0200, SeyeeL ***@***.***&amp;gt;, wrote:
 &gt; &amp;gt; I want to set a different browser with my system
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt; ------------------ Original ------------------
 &gt; &amp;gt; From: ironhak ***@***.***&amp;amp;gt;
 &gt; &amp;gt; Date: Sun, Jun 26, 2022 6:30 PM
 &gt; &amp;gt; To: typora/typora-issues ***@***.***&amp;amp;gt;
 &gt; &amp;gt; Cc: SeyeeL ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;
 &gt; &amp;gt; Subject: Re: [typora/typora-issues] [Feature] set the default browser foropening links (Issue #5305)
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt;
 &gt; &amp;gt; Links already open in your system default browser....
 &gt; &amp;gt;
 &gt; &amp;gt; —
 &gt; &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; &amp;gt; You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt;
 &gt; &amp;gt; —
 &gt; &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; &amp;gt; You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 &gt;
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt;
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by SeyeeL** [comment]
Changed my mind and found that I can set the default browser for vscode to be different from the system browser, no more need for this requirement, thanks
