### ISSUE TITLE
Copy wide picture display blur in 1.3.6

### ISSUE THREAD

**Issue by charliecat22** [typora/typora-issues#5306]
Copy wide picture display blur in 1.3.6
If I copy wide picture,preview becomes blurry.

**Comment by abnerlee** [comment]
Could you provide a sample image?

And what is your OS?

**Comment by speningithub** [comment]
env:
     i5-12600KF+B660M
     sumsung 980pro 
     nVidia RTX 3070(516.94)

version:
    Windows 11 Pro 21H2(22000.856)
    Typora 1.4.4

display:
    3440*1440(HDR on/off)

Compatibility mode:not work
![image](https://user-images.githubusercontent.com/11003034/189024315-10864b4a-44a4-46cf-8514-c05b9d0322e8.png)
