### ISSUE TITLE
Cursor moves to a new (wrong) location after every keystroke in paragraphs with math in them (display mode only)

### ISSUE THREAD

**Issue by AngusMcLure** [typora/typora-issues#5308]
- [X] Searched existing issues to avoid creating duplicates.
          Related to but different to #5292
          Related to but different to these closed issues: #4764, #4335, #4042, but the cursor movement is a bit different.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

**Describe the bug**
Cursor moves location after each keystroke when editting paragraphs containing inline mathblock, e.g.  \$ a + b \$ .

**To Reproduce**
1. Create a paragraph with an inline mathblock
2. Edit the mathblock section a bit in display mode (doesn't always happen immediately, and doesn't seem to be related to difficulties in rendering the mathblock as it effects even the simplest mathblock e.g.  \$ x \$ ). Eventually the cursor will move the start of the mathblock (before the opening \$) without any prompting.
3. Now if you try editing anywhere else in the paragraph containing the mathblock the cursor will move up. The bug occurs for inserting characters or deleting them. Sometimes the cursor moves to the start of the paragraph, sometimes to a previous paragraph
4. Bug does not appear to occur in source mode. Also toggling back and forth between source and display mode *sometimes* resolves it temporarily, but error recurs after editting any mathblock.

**Expected behavior**
Cursor moves as expected, i.e. is always after the last character typed (or deleted)

**Screenshots / Screencasts**
NA

**Sample Markdown File**
See example file attached

**Desktop (please complete the following information):**
Operating system Mac OS Mojave

**Typora Version**
1.3.7

**Additional context**
NA

**Comment by abnerlee** [comment]
should be fixed in 1.4.4

**Comment by AngusMcLure** [comment]
Fantastic, 1.4.4 has fixed the issue on my machine
