### ISSUE TITLE
On MacOS, debug mode in "source code mode" doesn't show "Inspect" in context menu

### ISSUE THREAD

**Issue by dtgriscom** [typora/typora-issues#5312]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
"Enable Debugging" is supposed to enable an "Inspect Element" item in the context menu when right-clicking on an element. However, in "Source Code Mode", the context menu is always just "Cut/Copy/Paste"; no "Inspect Element." This makes it difficult to debug issues with custom CSS in Source Code Mode.

**To Reproduce**
1. Under "Help", choose "Enable Debugging"
2. With Source Code Mode disabled, right-click in a document and note that the context menu includes an "Inspect Element" item; choosing this brings up various debugging tools (good).
3. Switch to Source Code Mode
4. Right-click in a document: note that the context menu only includes "Cut/Copy/Paste" (bad).

**Expected behavior**
The "Source Code Mode" context menu should include an "Inspect Element" item

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6 (18G9323)

**Typora Version**
- Version 1.3.7 (6424)

**Comment by abnerlee** [comment]
“Source code mode” is not our main work scenario, we only provide basic and necessary support for it. And you can debug it by opening dev tool in normal view, then switch to source code mode, and select target element using the dev tool to inspect it.
