### ISSUE TITLE
Image and code block formatting

### ISSUE THREAD

**Issue by GitHubQAQ** [typora/typora-issues#5313]
System: Windows 10 21H2
Software Version: 1.3.8

Image:
- Maybe typora should provides more options about images
   -  change the default folder(I think typora should provide addtional option: allow users select more efficient ways.
   -  Perhaps a combination of options can be provided, for example, the user can choose the default path, or choose to store to another path; the user can choose to store in the default path and upload. In general, only storing in the default path is bad.
Code:
When I'm writing CPP programs, I find the formatting gets weird. as the picture shows:
![image](https://user-images.githubusercontent.com/31883473/176076191-d8735dda-bb82-4a39-84b6-e22d3948d9bc.png)
Maybe it is a error or bug.

**Comment by abnerlee** [comment]
> change the default folder

You can set a default folder in Preferences Panel → Image. Maintaining images in multiple locations seems complicated to end users.

> When I'm writing CPP programs, I find the formatting gets weird. as the picture shows:

It is ligature of your font. You can change your font, for change `font-variant-ligatures` in your custom CSS.
See https://developer.mozilla.org/docs/Web/CSS/font-variant-ligatures about the details.
