### ISSUE TITLE
`<video />` HTML content breaks ePub export

### ISSUE THREAD

**Issue by florisvink** [typora/typora-issues#5314]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

According to the [documentation](https://support.typora.io/HTML#video) it is possible to embed `<video />` as HTML. This works in view-mode but when exporting to ePub it will break on that page. The exports succeeds but with all content  missing after the `<video />` tag. In Apple Books there is a visible error `error on line 22 at column 79: Specification mandates value for attribute controls`

**To Reproduce**
1. Create a document with an HTML `<video />` tag. (see example below)
3. Click on File > Export > ePub
4. Open created ePub file
5. See error:  
```
“This page contains the following errors:

error on line 22 at column 79: Specification mandates value for attribute controls
Below is a rendering of the page up to the first error.”

Excerpt From: “test.md”. Apple Books. 
```

**Expected behavior**
I understand that playing video's on eReaders is not very common and it would make sense to hide it but it would be nice to be able to read the content after the video tag.

**Screenshots / Screencasts**
As seen in Typora: 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/3237456/176183196-a6487dad-375d-4011-b59f-0b9377910898.png">

Result when opening exported ePub in Apple Books (or any other eReader):
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/3237456/176182973-b38317d0-d990-4217-826c-62398b959983.png">

**Sample Markdown File**
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum velit libero, commodo ac consectetur vitae, condimentum viverra erat. Suspendisse dictum facilisis tellus in gravida. Quisque vestibulum libero enim, eu pretium quam convallis ut. .

<video preload="none" width="1280" height="720" poster="https://peach.blender.org/wp-content/uploads/bbb-splash.png" src="https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_20MB.mp4" controls="" controllist="nodownload" ></video>

Pellentesque pharetra magna ac urna accumsan, ornare scelerisque sapien sodales. Mauris facilisis in leo et consectetur. Cras pellentesque nisi faucibus tellus ultricies, ut vehicula odio bibendum. 
```

**Desktop (please complete the following information):**
Mac OS Big Sur

**Typora Version**
1.3.7

**Additional context**
Very happy with the tool in general. Very convenient editing. Totally worthy pay the license. Keep up this good work!

**Comment by abnerlee** [comment]
fixed in 1.4.4
