### ISSUE TITLE
Recognize apostrophe inside words in Ukrainian language when quote pairing is enabled

### ISSUE THREAD

**Issue by arp** [typora/typora-issues#5317]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Automatic quote pairing in Ukrainian language prevents use of the apostrophe.

**To Reproduce**
1. Enable automatic bracket and quote pairing in settings
2. Switch to Ukrainian keyboard layout
3. Type "ім'я" or any other word that contains an apostrophe
4. See single quotes get paired even though the quote is adjacent to a letter without preceding space: "ім''я"

**Expected behavior**
This doesn't happen in English: you can type "it's" or "shouldn't" without it becoming "it''s" and "shouldn''t", so other languages should behave similarly.

**Screenshots / Screencasts**
N/A

**Sample Markdown File**
N/A: is reproduced on typing

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04 LTS

**Typora Version**
1.1.5

**Additional context**

**Comment by abnerlee** [comment]
@arp  Could you confirm it requires a fix?

#3460 told me "The language doesn't use single quotes at all anyway"

**Comment by abnerlee** [comment]
fixed in 1.4.4

**Comment by fl0werpowers** [comment]
Apologies for not reaching out for all this time. Can confirm it's fine now, so thanks for the fix.
