### ISSUE TITLE
.md links always open in new Typora window

### ISSUE THREAD

**Issue by prust** [typora/typora-issues#5319]
On macOS, when using markdown links or HTML links, even with `target="_self"`, command-clicking to open a link will always open it in a new Typora window instead of the window in which you clicked the link.

I checked the [internal links](https://support.typora.io/Links/#internal-links) documentation, but couldn't find anything about targeting the existing window or a new window. I'm using Typora and a nested folder structure of markdown files as a knowledgebase with a lot of internal links; for this use-case the current behavior is quite annoying.

It would be ideal if there was a way to construct links so they would open in the current window or, better, a way to do it via holding down a different key (shift-command-click or something), or even better, a way to configure Typora to open links in the current window.

**Comment by abnerlee** [comment]
duplicated with #1485
