### ISSUE TITLE
Math Block In Unordered List

### ISSUE THREAD

**Issue by lunaqiu** [typora/typora-issues#532]
<img width="657" alt="screen shot 2017-02-14 at 16 13 44" src="https://cloud.githubusercontent.com/assets/19543144/22949627/e68bb554-f2d0-11e6-8f5d-65848b124da0.png">

If I start a math block in an unordered list, then start a new line, there would be an error like that on display.

**Comment by abnerlee** [comment]
What's you Typora version?

And it seems works fine in my testing. So how did you input the block math? Input $$, return key, then the content in preview mode or write in source code mode or paste the whole markdown source?

**Comment by lunaqiu** [comment]
Sorry about the late reply, my version is Version 0.9.9.8.9. 

I inputed the clock using $$ and return key to create a block, wrote in the block and then went back to the list. Then I used ⇧+tab to return to last list level, that operation would trigger the bug.

**Comment by lunaqiu** [comment]
And here is a sample file with the trigger method in it.
[Gist for the bug](https://gist.github.com/lunaqiu/8400b30f169a60522d8a4100b74fb2b4)

**Comment by abnerlee** [comment]
fixed in new release
