### ISSUE TITLE
Unable to Save

### ISSUE THREAD

**Issue by benji88i** [typora/typora-issues#5320]
Hi there,

I am trying to save my documents but the save dialogue box will not appear.

**Describe the bug**
I am trying to save my document but it won't save. I have tried "Save", "Save All", "Save As".
None of which saves the file 

**To Reproduce**
I click save and nothing gets saved

**Expected behavior**
THe file would save by prompting me with the "Save Pop-up dialogue box". 

**Desktop (please complete the following information):**
 - OS: Fedora 36 Gnome

**Typora Version**
1.3.6

**Comment by abnerlee** [comment]
Please use the binary version (not the flathub one), or launch with `GTK_USE_PORTAL=0 typora` 

Seems duplicated with #5275
