### ISSUE TITLE
不确定是不是typora的bug，文章复制到公众号，发布之后，最新版的ios设备上图文错乱

### ISSUE THREAD

**Issue by nonozone** [typora/typora-issues#5321]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**

**Expected behavior**

iOS升级到目前的最新版，只要是通过 typora粘贴到微信公众号发布的文章，包括自带主题和第三方主题，在最新版iOS下面图文错乱，图片会把文字部分遮盖。即使是每篇图片后面都特意回车，包括段落结尾也增加回车，都无法正常。但是在Android下面是没有任何问题的。

**Screenshots / Screencasts**
![微信图片_20220701130938](https://user-images.githubusercontent.com/1277444/176827826-3976c9a0-5883-4186-a704-ed22ff613cd3.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

**Typora Version**
e.g: 0.10.11

**Additional context**

**Comment by nonozone** [comment]
肯定跟iOS内置的系统浏览器有关系，不兼容吧，如果用其他的 通过浏览器插件 把相同md 转换成公众号格式粘贴进去再发布，是没有任何问题的。

所以现在完全都不知道从哪里修改，调整...已经影响正常工作好几周了...

**Comment by abnerlee** [comment]
意思是桌面的微信公众号是正常的，ios的微信公众号是不正常的？

**Comment by nonozone** [comment]
> 意思是桌面的微信公众号是正常的，ios的微信公众号是不正常的？ 以前 iOS 正常的，现在升级 iOS 后不正常了吗？

因为我自己是用win+Android（手里没有mac）都正常，iOS升级到15.5之后（以前是没问题的），浏览同样的文章，图文就是错位的。我的公众号每次都有人留言反应这个问题，我只能让他们查看原文，原文也是同样的内容发布在WP平台的网站，...但是我完全不知道从哪里调整，除非我不用typora，但是这个工作流程已经熟悉了，不想改工具。

**Comment by nonozone** [comment]
iOS公众号这篇文章用系统浏览器打开，同样是错的，所以问题应该是跟iOS最新的系统浏览器插件哪里 不兼容。

**Comment by nonozone** [comment]
额，被关闭了，是因为提交的信息不对么？

**Comment by abnerlee** [comment]
可以把文章的链接提供一下吗？

**Comment by nonozone** [comment]
https://mp.weixin.qq.com/s/Hvht-JmFoW3c-lvopZuBCQ

https://mp.weixin.qq.com/s/k4fjUk2ohLU1GUespm3pDg

**Comment by nonozone** [comment]
刚才特意找来一台iPhone测试，直接系统打开链接或者把链接复制到chrome打开都一样图文错乱。

**Comment by abnerlee** [comment]
公众号编辑器支持改HTML源代码或者CSS吗？

可以加上

**Comment by nonozone** [comment]
> 

以前我都是直接把typora的内容粘贴到公众号后台是没问题的。

那如果要修改，可以把这一段，直接添加到 typora的模板css里面么？

**Comment by nonozone** [comment]
img {
float: none;
position: initial;
display: block;
}
把这一段css加入到 模板css确实可以了，建议可以把这一段，全部添加到typora默认模板的css里面...
