### ISSUE TITLE
"Move Image to..." should add extension

### ISSUE THREAD

**Issue by pvginkel** [typora/typora-issues#5322]
**Describe the bug**
Moving images should automatically add the appropriate extension.

**To Reproduce**
1. Right click "Move Image to...".
2. Pick a folder.
3. Type in a name of the picture.
4. Click Save.

The file is saved without an extension.

**Expected behavior**
The extension is added automatically.

**Screenshots / Screencasts**
None.

**Sample Markdown File**
None.

**Desktop (please complete the following information):**
 - OS: Windows.

**Typora Version**
1.3.8

**Additional context**
None.

**Comment by abnerlee** [comment]
fixed in 1.4.4
