### ISSUE TITLE
[Feature]Reload On File Change/Get Focus

### ISSUE THREAD

**Issue by macMikey** [typora/typora-issues#5324]
Prompt to reload the file when
* Typora gets the focus and
* The contents have changed
i.e. after fetching a different commit

**Comment by abnerlee** [comment]
It should be supported already.

Could you provide more details about your operation if that does not work? And what's your OS and typora version?

**Comment by macMikey** [comment]
Typora is open with the file (e.g. a version history)
I fetch a commit, which changes the contents of the file
Nothing happens in Typora. The display does not change, and there is no indication that the contents are changed.
