### ISSUE TITLE
Image export acts weird 

### ISSUE THREAD

**Issue by ceruleanjo** [typora/typora-issues#5329]
**Describe the bug**
When the content is long enough, the image exported looks very weird.

**To Reproduce**
1. Create a new file.
2. Paste the "Lorem ipsum" paragraph a couple of times.
3. exporte an image and you'll know what I mean

**Expected behavior**
An image with consistent formatting is expected.

**Screenshots / Screencasts**
An example md file:

![c](https://user-images.githubusercontent.com/32504764/177691638-c7f597b5-c07e-4794-8367-db2ce141477e.png)

It's image export:

![b](https://user-images.githubusercontent.com/32504764/177691702-e0ab0025-cfe8-4b26-9f5d-7a81cf279a6c.png)

**Sample Markdown File**
[Lorem ipsum.md](https://github.com/typora/typora-issues/files/9060411/Lorem.ipsum.md)

**Desktop (please complete the following information):**
 - OS: Win 11

**Typora Version**
1.3.8

**Comment by abnerlee** [comment]
It works fine in my test.

so can it be reproduces? If so, did you zoom your typora view? And what's your screen DPI?

**Comment by abnerlee** [comment]
> I use a laptop (2560x1600, 150% UI) and an external monitor (1920x1080).

Are those displays be arranged vertically? Looks like the first part of the image is normal, while the last part is 150% zoomed...

**Comment by ceruleanjo** [comment]
> > I use a laptop (2560x1600, 150% UI) and an external monitor (1920x1080).
> 
> Are those displays be arranged vertically? Looks like the first part of the image is normal, while the last part is 150% zoomed...

Both displays are horizontal.

Maybe the problem is the 150% zoom for sure. I temporarily set the laptop UI to 100% and got a normal export image. This can be a workaround for me.

**Comment by abnerlee** [comment]
should be improved in 1.4.4

Please comment or reopen if it happens in 1.4 again
