### ISSUE TITLE
Windows, "Open a folder", "Recent locations" provided links hover text flashes quickly and disappears, can't read path

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#5330]
Windows 11, Typora, 1.3.8

these Recent Locations have a hover text to show the full path, which is needed here (see the two same named projects)

However, the hover text is not persistent and flashes, disappearing quickly.  Animation below.

![vxzGZ5DkAx](https://user-images.githubusercontent.com/58857646/177858904-35b16e31-3b31-40f9-87b6-f67138493875.gif)

**Comment by abnerlee** [comment]
duplicated with #5301
