### ISSUE TITLE
The codeblock cannot correctly change the height

### ISSUE THREAD

**Issue by 15040941306** [typora/typora-issues#5335]
When I close the sidebar, if there is code in a code block that needs to wrap when closing the sidebar, and no line break is required after closing, then closing will leave a large blank space at the bottom of the code block.

That is, the code block cannot correctly change the height after part of the code no longer needs to wrap.

This phenomenon occurs in large numbers when macOS split screen.

> 当我关闭侧边栏时，如果有代码块中的代码在关闭侧边栏需要换行，并且关闭后不需要换行，那么在关闭后就会在代码块的底部留下大段的空白。
>
> 即代码块在部分代码不再需要换行后不能正确改变高度。
>
> 这种现象出现在macOS分屏时。

There are two images:

- Before closing sidebar:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/32926331/178666179-6f8dd26e-0be5-4a2f-9604-8325ca2c1e3e.png">

- After closing sidebar:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/32926331/178666280-03938351-f0f4-4edb-a846-56133a3045d2.png">

**Comment by abnerlee** [comment]
fixed in 1.4.4
