### ISSUE TITLE
the download of QqRvn.jpg was interrupted

### ISSUE THREAD

**Issue by zhouxinghong** [typora/typora-issues#5338]
Hello! After pasting the network picture, it cannot be downloaded to the local disk. After many tests, it is not a network problem. Using other markdown tools can download the network picture normally, and 1.2.5 can download the network picture normally.
Current use: 1.3.8
Current system: Window10

**Comment by abnerlee** [comment]
Could you share the web page url and the image you want to paste/download?

**Comment by zhouxinghong** [comment]
Hello! The picture can be saved by right-clicking on the browser, but it cannot be directly pasted and downloaded in typroa. . .

**Comment by zhouxinghong** [comment]
still have a question?
In the process of selecting the content with the mouse cursor in the code block, there is a deviation and error in the focus, and the content, text, etc. cannot be selected accurately.
