### ISSUE TITLE
Personalized task-list is lost when exporting pdf or html

### ISSUE THREAD

**Issue by fztongxue** [typora/typora-issues#5340]
the personalized task-list（Mainly the box）is lost when i try to export pdf or html
My version is 1.3.8
Thanks!
markdown
![图片](https://user-images.githubusercontent.com/57033797/179390927-b42c2488-92cc-489f-821f-96bde9b178e9.png)
pdf
![图片](https://user-images.githubusercontent.com/57033797/179390979-7a09b30e-d5e4-4b36-a7a5-56aeaf158954.png)

**Comment by abnerlee** [comment]
Which theme did you use? Which OS?

Does this happen in built-in themes?

**Comment by fztongxue** [comment]
> 
drake-light(thanks to Mr.Liu)； Windows 10；No problem for the built-in theme.

**Comment by abnerlee** [comment]
It is issue of the 3rd theme

Printing background color in `div`s not supported yet due to #5078
