### ISSUE TITLE
High cpu usage when searching for $ or ^ in regular expressin mode

### ISSUE THREAD

**Issue by n-wissam** [typora/typora-issues#5341]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Searching for $ or ^ in regular expression mode makes Typora freeze with high cpu usage

**To Reproduce**
1. Go to 'Find'
2. Click on 'regular expression icon to activate regular expression mode'
3. Type '$ or ^'

**Sample Markdown File**
The problem happens in any markdown file even empty ones

**Desktop (please complete the following information):**
 - OS: [EndeavorOS (based on arch)]

**Typora Version**
1.3.6

**Comment by abnerlee** [comment]
fixed in 1.4.4
