### ISSUE TITLE
typora crash on windows11

### ISSUE THREAD

**Issue by mixiaoluo88** [typora/typora-issues#5344]
Hi, every time I open the software, it crashes automatically.I have tried reinstalling and reinstalling the system several times and still cannot resolve the issue.
       Hope to receive a reply as soon as possible, thank you!

[typora.log](https://github.com/typora/typora-issues/files/9138644/typora.log)
.

**Comment by wuhuilan** [comment]
I have the same question, when i opened the typora, it comes to a error that the beta version of typora is expired..., however, i have downloaded the newest version and payed for it with 89CNY.

**Comment by abnerlee** [comment]
@mixiaoluo88 Please try uninstall previous versions, download Typora form https://typora.io and re-install it.

**Comment by mixiaoluo88** [comment]
> @mixiaoluo88请尝试卸载以前的版本，下载Typora表单 https://typora.io 并重新安装。

The version I installed is the latest version.
Then I repeated this step many times, the software still does not work.

**Comment by AlaiaS** [comment]
Same here. I tried to re-install the newest version. It still doesn't work on Windows 11

**Comment by pyh-129** [comment]
> 

The same in windows11

**Comment by abnerlee** [comment]
Could you try
1. uninstall Typora
2. Delete C:\Users\{username}\AppData\Roaming\Typora
3. re-install Typora to disk C?

**Comment by xmsgd123** [comment]
下载typora最新版本，重装的win11的最新版本，现在打开就空白闪退，这个怎么处理
