### ISSUE TITLE
Typora crash when saving on OSX Ventura Beta

### ISSUE THREAD

**Issue by jobbyworld** [typora/typora-issues#5345]
Typora[7170:225189] -[NSLocalSavePanel _setUseSyncBeginServicePanel:]: unrecognized selector sent to instance 0x7f9bb1831a00
[1]    7170 abort      /Applications/Typora.app/Contents/MacOS/Typora

**Comment by abnerlee** [comment]
Could you try shutdown your macbook, after a few seconds, reboot it? Or hold down Command-Option-P-R at startup if you are using Intel mac?

**Comment by jobbyworld** [comment]
Thanks !
Reboot not fix 
But finally remove and reinstall typos fix issue

Best regards
