### ISSUE TITLE
Nested tasks incorrectly formatted

### ISSUE THREAD

**Issue by bobbykjack** [typora/typora-issues#5347]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Typora handles a single-level of indenting for task lists correctly, but breaks for greater levels of indent.

**To Reproduce**
1. Create a file containing the following markdown:

```
- [ ] one
- [ ] two
    - [ ] three
        - [ ] four
```

2. Open the file in Typora

**Expected behavior**
- Items one and two should be left-aligned ✅
- Item three should be indented by one level ✅
- Item four should be indented by two levels ❌

**Screenshots / Screencasts**

![grab 2022-07-20 at 13 26 57](https://user-images.githubusercontent.com/736352/179981748-8b321db7-5ddc-4b98-9a73-92c3cc0d129e.png)

**Sample Markdown File**

[indents2.md](https://github.com/typora/typora-issues/files/9149715/indents2.md)

**Desktop (please complete the following information):**
 - OS: macOS 11.6.7

**Typora Version**
1.3.6 & 1.3.7

**Additional context**
I have observed this to sometimes work, but to then fail across saves. The typora interface lets me create lists that are indented to any level, but then fails to save the markdown correctly, or fails to interpret it in the same manner on subsequent opens. Basically, it's very inconsistent.

**Comment by abnerlee** [comment]
Which version? 

I opened the [indents2.md](https://github.com/typora/typora-issues/files/9149715/indents2.md) with 1.3.7 and it is rendered fine. So does v1.3.7 fix it?

**Comment by bobbykjack** [comment]
It was 1.3.6 - my report says "e.g." so, sorry, I must have not removed that properly! I'll try with 1.3.7 and update.

**Comment by bobbykjack** [comment]
Still failing for me in 1.3.7

**Comment by abnerlee** [comment]
@bobbykjack could you try attach a screencast of "opening [indents2.md](https://github.com/typora/typora-issues/files/9149715/indents2.md) with 1.3.7"? Because in my test, it still seems ok...

**Comment by bobbykjack** [comment]
https://user-images.githubusercontent.com/736352/182022733-454173b4-83e5-4c16-95af-e23a0adf5c08.mov

**Comment by abnerlee** [comment]
fixed in 1.5.5
