### ISSUE TITLE
Custom upload image failure

### ISSUE THREAD

**Issue by wanlinus** [typora/typora-issues#5348]
I built the image bed using minio, and then wrote the upload tool using golang. I exported the correct data format according to the official instructions, but the software failed to validate

我使用minio搭建了图床, 然后使用golang编写了上传工具.根据官方说明输出正确的数据格式,但是软件提示验证失败

<img width="720" alt="image" src="https://user-images.githubusercontent.com/34122643/180422345-ac44b494-0b91-4442-aa25-28e72f683ea7.png">

this is my code
这是我的代码地址

https://github.com/wanlinus/gominio

**Comment by abnerlee** [comment]
Please try remove the empty line between the two https urls
