### ISSUE TITLE
Tab crashes if spellcheck hotkey reaches end of file

### ISSUE THREAD

**Issue by hierophect** [typora/typora-issues#5349]
**Describe the bug**
If you use the Mac spellcheck hotkey Command-: (⌘:), and step all the way to the end of the file, it will "crash" the tab instead of halting or wrapping around to the beginning. The tab will go completely blank, not showing any file text, and will not respond to any input - you cannot save the file, if it had edits, and closing the tab will result in a loss of data. I have found no way to "recover" the tab so far other than closing it and re-opening.

Notes:
 - This occurs across all themes, including builtin and custom ones
 - This occurs across all file types
 - Using the save hotkey while on the "crashed" tab will cause the computer to briefly stall, showing the "rainbow of death" spinning cursor for mac. Closing the tab will also be delayed by a second or so. Thankfully, the original file does not appear to be corrupted by this.
 - This occurs 100% of the time when following reproduction steps (on my machine), ie it's a completely predictable bug.

**To Reproduce**
 - Create a markdown file with at least one spelling error
 - Use the ⌘: hotkey to step through the spelling errors
 - After reaching the final spelling error in the file, using the ⌘: hotkey again should crash the tab.

**Expected behavior**
When using other editors on Mac, such as TextEdit, the default behavior is to wrap around to the first spelling error in the file.

**Desktop (please complete the following information):**
 - OS: Mac OS Montery, 12.3.1

**Typora Version**
Version 1.3.7

**Comment by abnerlee** [comment]
Could you provide a sample md file and screencast? In my test, it works fine...

**Comment by hierophect** [comment]
[example.md](https://github.com/typora/typora-issues/files/9191048/example.md)

@abnerlee Sorry, it actually only happens for files where the first line is `[TOC]`. Almost all of my note files have a TOC so I assumed it was all files, my bad! Example attached.

Before pressing command-:
<img width="883" alt="Screen Shot 2022-07-26 at 11 16 18 AM" src="https://user-images.githubusercontent.com/5904176/181044668-22accbd7-312d-4436-ba63-2868ced709b7.png">

After pressing command-:
<img width="887" alt="Screen Shot 2022-07-26 at 11 16 26 AM" src="https://user-images.githubusercontent.com/5904176/181044760-e2f5c9f3-3cd5-4ff1-89e4-4a9b06fea3ea.png">

**Comment by hierophect** [comment]
I can also confirm that it doesn't happen every time the spellchecker hits a TOC, it has to be a TOC in the very first line of the file.

**Comment by abnerlee** [comment]
fixed in 1.4.4
