### ISSUE TITLE
[Feature] Add APA 7 Formatting and Printing

### ISSUE THREAD

**Issue by sharpninja** [typora/typora-issues#5351]
Please implement an APA mode for writing APA7 documents.  Use front matter to place data such as reference.

An example:

```md
---
Variables:
  Layout: ./wwwroot/Apa7Layout.html
  title: APA Template
  author: Payton Byrd
  keywords: apa7
  instructor: Instructor
  course: Course
  affiliation: Affiliation
  dueDate: January 1, 2022
  ReferencesSection: References
	References:
	- Herbst-Damn, K. L., & Kulik, J. A. (2005). Volunteer support, marital status, and the survival times of terminally ill patients. *Health Psychology, 24*(1), 225-229. doi:10.1037/0278-6133.24.2.225
  Abstract: This is the paper's abstract.
---

## H2

The there me i tinkled back guessing quoth lost my before dreaming i i so shadows thinking and this chamber the door theeby with both thy there bird for bird no that aptly sought opened gently thy peering visiter lamplight prophet each ghastly my on no whom some answer black me grave god smiling nevermore and within ah bust window i each bird still perched of countenance whom i quoth i grim i his lady tossed prophet not word perched sorrow darkness radiant that stayed nothing the is i to as not that this into yore mortals implore i upon

### H3

Gezeigt ihr vor nicht gleich an ist ergreift der festzuhalten was und seelen ihr und geisterreich wieder unbekannten der mein mein guten herauf euch früh mein das was froher erfreuet ersten im auf drängt manche äolsharfe noch ist schauer herzen meinem euch meinem noch schöne was nun lispelnd wird träne

```

Renders on screen:
![image](https://user-images.githubusercontent.com/16146732/180655808-96da748b-d337-46cc-841c-7c55737ec634.png)

Renders to Print:
![APA Template_Page_1](https://user-images.githubusercontent.com/16146732/180655865-5de83da1-2b13-44c0-9673-cd029391bde3.png)
![APA Template_Page_2](https://user-images.githubusercontent.com/16146732/180655867-73b12b82-9bcf-4b76-ac50-8192182ee0f4.png)
![APA Template_Page_3](https://user-images.githubusercontent.com/16146732/180655868-481d5dd4-4ea2-4000-af2b-82492651680e.png)
![APA Template_Page_4](https://user-images.githubusercontent.com/16146732/180655869-c426dc7c-dcab-4931-bfa9-2d260dd0f22a.png)

**Comment by abnerlee** [comment]
should be supported via https://support.typora.io/Export/#pdf-latex--pandoc
