### ISSUE TITLE
Words export : Customize the bullets

### ISSUE THREAD

**Issue by yannmiquel-seenovate** [typora/typora-issues#5353]
Hi,

When exporting to docx, only the default bullet point is used. How can I update the template (or anything else) to have another type of bullet point ? I don't see how to update the "Normal" style to reach this goal.

Regards,
Yann

**Comment by abnerlee** [comment]
The default export is processed by Pandoc, and from its document https://pandoc.org/MANUAL.html#option--reference-doc

It seems the template file does not include list styles. So this seems not supported, and we are also not able to support it in our side.
