### ISSUE TITLE
Typora on Windows: wrong version reported

### ISSUE THREAD

**Issue by aloneguid** [typora/typora-issues#5354]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Upgrading Typora from 1.3.6 to 1.3.8 does not update version info in Windows. Therefore update software like winget always says there's a new version of Typora but there isn't.

![image](https://user-images.githubusercontent.com/3155189/181287634-aac4b897-43e1-4b2a-a225-73c1c4154293.png)

**To Reproduce**
1. Install 1.3.6.
2. Update to 1.3.8.

**Expected behavior**
1.3.8

**Screenshots / Screencasts**
see above

**Sample Markdown File**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11

**Typora Version**
e.g: 1.3.8

**Additional context**
n/a

**Comment by abnerlee** [comment]
fixed in 1.4.4
