### ISSUE TITLE
Cannot Export when There are LaTeX Equations

### ISSUE THREAD

**Issue by az15240** [typora/typora-issues#5360]
**Describe the bug**
Unable to export PDF when LaTeX equations exist in the md file, prompting exporting in progress...

**To Reproduce**

1. Choose a file
2. Click on 'File->Export->PDF->save'
3. Unable to export PDF, prompting exporting in progress...

**Expected behavior**
Exporting PDF successfully

**Screenshots / Screencasts**
<img width="1440" alt="Screen Shot 2022-07-30 at 10 28 14 PM" src="https://user-images.githubusercontent.com/62636610/181918969-a48601e4-0cc7-4334-9e98-76f4362f343a.png">

**Sample Markdown File**
N/A

**Desktop (please complete the following information):**

OS: MacOS 10.14.6
Typora Version: 1.3.7 (6424)

**Additional context**
I've tried either big or small files that contain LaTeX equations but all of them cannot export. Other files that has no equations can successfully export.
I've tried reinstall my Typora and checked carefully through Preferences.

**Comment by abnerlee** [comment]
Could you provide a sample md file?
