### ISSUE TITLE
Using ESC to close the prompt dialog for saving files can cause bugs

### ISSUE THREAD

**Issue by p3ddd** [typora/typora-issues#5361]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

  If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

After you close the dialog box that prompts you to save a file with ESC, you cannot save the file again, and clicking other files does not respond.

However, you can click the button (×) to close the software, and then a dialog box will pop up to prompt you to save the file, and you can normally save the file or cancel the dialog box.

Only closing this dialog with ESC can cause a bug.

**To Reproduce**

1. Prepare several files
2. Modify the current file and don't save it
3. Click another file, and close the pop-up dialog box with ESC
4. In this case, the file cannot be saved, and the software does not respond when you click other files

**Expected behavior**

The file can be saved normally.

**Desktop (please complete the following information):**

 - Windows 11 64bit 21H2

**Typora Version**

Typora for Windows(x64) version 1.3.8

**Comment by abnerlee** [comment]
fixed in 1.4.4
