### ISSUE TITLE
When searching highlighted text, the search results are not readable in light themes

### ISSUE THREAD

**Issue by lucidBrot** [typora/typora-issues#5362]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css. `Github`, `pixyll`, and `Newsprint` are affected. `Night` is not affected.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Searching for `==TODO==` will show the search results unreadably as what looks like `==    ==`. In the `Night` theme, this is no issue. Enabling or disabling regex does not matter.  

This is relevant because when e.g. searching for everything highlighted by using RegEx search and searching for `==.*==` I am unable to see what the highlighted result actually is saying.

**To Reproduce**
1. Go to Preferences and enable `Markdown > Syntax Support > Highlight`
2. Write in a file some text, including a few occurrences of `==something==`
3. Press <kbd>CTRL</kbd><kbd>F</kbd> and enter the search term `something`, then <kbd>Enter</kbd> to jump to the first result.
4. If you are using most themes (e.g. `github`) you will only see a black bar instead of the search term.

**Expected behavior**
I would expect the text to be readable. Ideally, the highlighted parts of the result would somehow still look different than the non-highlighted parts. But using a background color that is the same as the text color to distinguish highlighted from normal text is a bad idea.

**Screenshots / Screencasts**
| Github | Night |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4920691/182030260-6d756995-9e81-4643-b7a4-be218f33a06e.png) |  ![image](https://user-images.githubusercontent.com/4920691/182030294-45c455b6-4af5-4527-ad62-511605f199e1.png) |
| ![image](https://user-images.githubusercontent.com/4920691/182030347-221c078d-db6b-4a1c-b221-72c1a987d86f.png) |  ![image](https://user-images.githubusercontent.com/4920691/182030320-01d86fe3-4d3b-438d-ab8e-63acff0e3fc2.png)  |

**Sample Markdown File**
[typora-highlighting.md](https://github.com/typora/typora-issues/files/9229034/typora-highlighting.md)
This should be very simple to reproduce in any file that has some highlighting though.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 64 bit

**Typora Version**
`1.3.8`

**Comment by abnerlee** [comment]
improved in 1.4.4
