### ISSUE TITLE
Things i really missed while working whith typora/markdown, compared to office. 

### ISSUE THREAD

**Issue by NorHei** [typora/typora-issues#5364]
Figures figure-captions, and the possibility to have a table of figures [TOF]. This one is really Important with scientific work.
 
Positioning Images/Figures in the Text flow (Left / Right) At least at some basic level.  Its not always nice to have images to be centered. 

As i already mentioned in a direct feature request, tables with captions would be really nice too and a table of tables [TOT] would be the perfect addition. Another thing that disturbed me about tables is the fact that all tables must have table headings. Sometimes it would be preferable to have tables without. (Maybe if they are empty, simply don't render them ?).

And another thing i am missing in Markdown in general is that ability to have sub-TOCs.  So you could have one TOC per chapter for example. 

I am not sure if any or all of this is available somewhere in Markdown but for me this would enable me to do my complete documentation in Typora/Markdown

**Comment by abnerlee** [comment]
duplicated with #249 #2688 and other issues.
