### ISSUE TITLE
"Save" and "Save as" options don't work in Linux

### ISSUE THREAD

**Issue by msoutopico** [typora/typora-issues#5366]
**Description**
"Save" and "Save as" options don't work in Linux

**Steps to reproduce**
1. Create a new document
2. Go to 'Save' or 'Save as' (or press Ctrl+S)

**Expected behavior**
A window appears to select the location and the name of the file to be fixed.

**Actual behaviour**
Nothing happens.

**Desktop (please complete the following information):**
 - OS: Linux mx 5.16.0-5mx-amd64 #1 SMP PREEMPT Debian 5.16.14-1~mx21+1 (2022-03-22) x86_64 GNU/Linux

**Typora Version**
1.3.6

**Comment by abnerlee** [comment]
duplucated with #5275
