### ISSUE TITLE
an issue with footnotes in the exported pdf file

### ISSUE THREAD

**Issue by bdcformpara** [typora/typora-issues#5367]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I found that it will create a page break before the footnotes in the export pdf file. However, the description of the footnotes will be shown on the same page as the body part normally.

**To Reproduce**
1. Use footnotes in Typora
2. Export -> PDF

**Expected behavior**
Descriptions of footnotes in exported pdf files are displayed on the same page as the body part (i.e. in the footer)

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
https://raw.githubusercontent.com/bdcformpara/temp/main/pic/typora_footnotes.png

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.
https://raw.githubusercontent.com/bdcformpara/temp/main/files/typora_footnotes.md

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]
 - Windows 11 64bit

**Typora Version**
e.g: 1.3.8

**Additional context**

**Comment by abnerlee** [comment]
You can disable the “Page Break Between Top Headings” option

see https://support.typora.io/Export/#page-break
