### ISSUE TITLE
Typora crashes when I want to export in PDF

### ISSUE THREAD

**Issue by LokutS2i** [typora/typora-issues#5368]
- [ x ] Searched existing issues to avoid creating duplicates.

- [ x ] Confirmed that it can be reproduced in built-in themes without customized css.

- [ x ] Searched http://support.typora.io/

----

**Describe the bug**
When I want to export my MD file in PDF, Typora opens the window to know where to export the file and crashes. Typora is frozen and I need to force quit the software.

**To Reproduce**
1. Go to 'File'
2. Go to 'Export'
3. Click on 'PDF'
5. See error

**Desktop (please complete the following information):**
 - OS: Windows 11 64bits

**Typora Version**
1.3.8
[typora_issue.md](https://github.com/typora/typora-issues/files/9268747/typora_issue.md)

**Comment by abnerlee** [comment]
> Typora opens the window to know where to export the file and crashes. 

You mean the file selector dialog is frozen or the Typora window is frozen?


Would you try https://support.typora.io/Export/#export-pdf-not-working-on-windows ?

And does rebook work?

**Comment by LokutS2i** [comment]
Hi @abnerlee ! Thank you very much it worked !!
