### ISSUE TITLE
[Feature]Reload on fetch (#5324)

### ISSUE THREAD

**Issue by macMikey** [typora/typora-issues#5369]
You guys closed #5324 before I had a chance to respond, and I can't reopen it, and no one replied to my comment after the issue closed.
If I fetch a commit, Typora should reload or preferably prompt to reload any files that it has open that are modified by the commit.
Example:
I have a README.md file open for a repo. I fetch a different version of the repo. The README.md file is different in that commit.
No, Typora does not either fetch the changed version or prompt to load the changed version.
I'm running Typora 1.3.7 (6424) on MacOS 12.5

**Comment by abnerlee** [comment]
It should reload on focus. Possible to provide a screencast that Typora did not reload newer content on focus?

**Comment by macMikey** [comment]
Sure. How's this?
Using GitKraken.
We start with the currently fetched commit and check the readme in Typora
Then we use GitKraken to fetch another commit. As you can see, the readme is different, but Typora does not re-render with the new commit.

https://user-images.githubusercontent.com/10867016/185221813-d6cd9f88-67ea-42f5-af88-82c4736a9464.mp4

**Comment by abnerlee** [comment]
Could you check if the readme file **in disk** has changed when you click commit in GitKraken?

**Comment by macMikey** [comment]
interesting. today, it seems to be working. when I switch to Typora, I can see the screen blink and the contents change.
hmmmmmm.
