### ISSUE TITLE
Use custom command to upload a picture and get this problem , Who can tell me why?

### ISSUE THREAD

**Issue by ChenKuan1110** [typora/typora-issues#5371]
use custom command to upload a picture and get this
![1011660298867_ pic](https://user-images.githubusercontent.com/37923315/184334626-e28fb783-340b-482f-95c0-40781bb3dd80.jpg)

but when I use the same command in Teminal, it works
![1021660298889_ pic](https://user-images.githubusercontent.com/37923315/184334851-76eae01a-d492-4304-8c8d-664bb9b39969.jpg)

**Comment by abnerlee** [comment]
see https://support.typora.io/Upload-Image/#command-not-find

**Comment by ChenKuan1110** [comment]
the reason is I did not config the node path😭

the complete command is 

```sh
[node path]  [picgo path] upload
```
