### ISSUE TITLE
If the file path contains spaces, the file cannot be opened,can someone tell me why

### ISSUE THREAD

**Issue by linfukuai** [typora/typora-issues#5372]
**Describe the bug**

i cant open file
If the file path contains spaces, the file cannot be opened,can someone tell me why
i have a markdown file in path(G:\all study notes) 
but i cant open the file.
typora prompt: file does not exist at path G:\all study notes\note
Why does G: \all study notes\fafgehgr.md become G:\all study notes\\**note**\fafgehgr.md
Is this a bug, or is it the default rule all along？
I have just started to contact the documents of typera and markdown recently. 
Can anyone help me? thank you

**To Reproduce**
1. Create a folder with a blank file name
2. Create any MD file
3. Open the MD file

**Sample Markdown File**
ALL .md FILES

**Expected behavior**

Open file normally

**Desktop (please complete the following information):**

OS: Windows 10 64bit

**Typora Version**

1.3.8

**Screenshots / Screencasts**

![屏幕截图 2022-08-14 204618](https://user-images.githubusercontent.com/31724720/184537784-1ea77a6e-d577-48b0-9107-46f84612d7bb.jpg)

![屏幕截图 2022-08-14 204659](https://user-images.githubusercontent.com/31724720/184537795-0c654d41-d0e6-42db-8420-67c06a35f007.jpg)

https://user-images.githubusercontent.com/31724720/187075830-5a681c39-529c-42cf-84db-e0bb6aaeb91c.mp4

**Comment by abnerlee** [comment]
Could you provide a screencast of your operation?

Does this happen for path with whitespaces but under other disks, like C:\ ?

**Comment by linfukuai** [comment]
Added videos and updated questions

**Comment by abnerlee** [comment]
Could you try open Typora, then open file (with whitespace in their path) from menu bar → File → Open?

And could you try right click, select open with..., select more applications, then choose Typora.exe to open the file?

**Comment by linfukuai** [comment]
Could you try open Typora, then open file (with whitespace in their path) from menu bar → File → Open?
This method is OK

And could you try right click, select open with..., select more applications, then choose Typora.exe to open the file?
This method doesn't work

**Comment by abnerlee** [comment]
Did you set any launch arguments for Typora?

**Comment by linfukuai** [comment]
I'm not sure. I don't know how to check the launch arguments?
I recently started to contact Typora, and most of them use the default settings

**Comment by abnerlee** [comment]
If you downloaded Typora form our website and did not change advanced setting then it should means no launch argument set.

**Comment by linfukuai** [comment]
Before I installed Typora, I used to open MD format files in word. Later, after downloading Typora, the default opening method of MD format files in windows was word. So I found some information and modified some settings (now I'm not sure what changes were made). I don't know if this has anything to do with it.

Can you reproduce this problem on your computer? You haven't been sure whether the problem is a bug and need more information. Am I the only one who encounters this problem?

**Comment by abnerlee** [comment]
I cannot reproduce this on my PC, and we didn't receive reports from other users either.

> So I found some information and modified some settings (now I'm not sure what changes were made).

Did you modify Windows Registry?

**Comment by linfukuai** [comment]
yes

**Comment by abnerlee** [comment]
Could you quote %1 ?

**Comment by linfukuai** [comment]
How to restore my registry to normal？

计算机\HKEY_CLASSES_ROOT\.md
![image](https://user-images.githubusercontent.com/31724720/188680575-99ccf4e1-7b82-4b12-94aa-cd975f80fe7e.png)

计算机\HKEY_CLASSES_ROOT\md_auto_file\shell\open\command
![image](https://user-images.githubusercontent.com/31724720/188681051-11bad585-8202-4fc9-a4b2-375df55f4700.png)

计算机\HKEY_CURRENT_USER\SOFTWARE\Classes\.md
![image](https://user-images.githubusercontent.com/31724720/188681268-74ccea62-1a87-4b50-886c-0253fdae1f6f.png)

计算机\HKEY_CURRENT_USER\SOFTWARE\Classes\md_auto_file\shell\open\command
![image](https://user-images.githubusercontent.com/31724720/188681480-32c2abcd-01b9-48d5-8b1d-34da094e70fc.png)

**Comment by abnerlee** [comment]
use  "%1" not %1

**Comment by linfukuai** [comment]
Thank you very much for your help! This problem has been solved successfully！

I have deleted three other registry folders and modified \ HKEY_ CLASSES_ Root.md is shown in the figure below. 

![image](https://user-images.githubusercontent.com/31724720/188909078-6df94308-5260-4bbb-ad89-a73645bac382.png)
