### ISSUE TITLE
Sometimes "Save Diagram As..." context menu doesn't show up

### ISSUE THREAD

**Issue by mikedeskevich** [typora/typora-issues#5374]
*Sometimes* when trying to save a mermaid figure as a file, I don't get the Save Diagram As... context menu.  The best reproduce case I can find is if the code fence contains a long diagram (longer than the window height), it won't work.  It looks like when I right click on the image, Typora auto scrolls to the top of the code fence that defines the figure and if it pushes the figure off the bottom of the screen, the dialog is now referenced to the code block, not the image.

I made my window very short to make this obvious.  Here's a case where it works as expected

![image](https://user-images.githubusercontent.com/28789607/184702542-2ec0c23c-4f3a-4ba1-a695-7c11b94d9a1b.png)

And here's a case where my mermaid code is really long so that when I right click on the image, it gets pushed down and the context menu is different.

![image](https://user-images.githubusercontent.com/28789607/184702638-cc91bc04-d005-4cef-b819-ffa5dbb7a0e4.png)

In both cases, I right clicked on the generated image, not the code fence area.

Windows 11, 64bit

Typora 1.38

**Comment by abnerlee** [comment]
fixed in 1.4.4
