### ISSUE TITLE
Base64 image not showing

### ISSUE THREAD

**Issue by Higurashi-kagome** [typora/typora-issues#5377]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Some base64 images not showing.

**To Reproduce**
1. Open the markdown file uploded in this issue.
2. The image is valid but not showing correctly.

**Expected behavior**
Showing the image.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/51501079/185556785-b5ed4d3c-4722-4c7c-acfb-a59d92535953.png)

**Sample Markdown File**
[base64img.md](https://github.com/typora/typora-issues/files/9379665/base64img.md)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
e.g: 1.3.8

**Comment by 15040941306** [comment]
Same situation on macOS

**Comment by abnerlee** [comment]
put into #88
