### ISSUE TITLE
global search not working with M1 Pro Macbook

### ISSUE THREAD

**Issue by gitphan** [typora/typora-issues#5378]
- [x] Searched existing issues to avoid creating duplicates.
There was the #4967, #3324 but all closed.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.
yes, used theme is Github

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/
yes, searching for "global search" but didn't find any help related to this issue.
----

**Describe the bug**
Using the "global search" feature doesn't seem to work. The result of the search stays empty.

**To Reproduce**
1. Go to 'Search Field'
2. Key in 'test' 
3. Apply/Validate
4. See error (result is empty but should not be)

**Expected behavior**
A list of occurrences of the searched words should be displayed.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

Below a screenshot showing that search result is empty even if there are files matching the searched words.
<img width="620" alt="Screenshot 2022-08-19 at 09 08 34" src="https://user-images.githubusercontent.com/50952429/185563481-8cece07f-3795-444b-994d-09bdf9064599.png">

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.
[test1.md](https://github.com/typora/typora-issues/files/9380066/test1.md)
[test2.md](https://github.com/typora/typora-issues/files/9380067/test2.md)

**Desktop (please complete the following information):**
 - OS: [e.g. OSX Version 12.5.1 / Chip Apple **M1 Pro** / Macbook Pro]

**Typora Version**
e.g: 1.3.7 (6424)

**Additional context**

**Comment by gitphan** [comment]
As a workaround, it is possible to install "**_Rosetta 2_**" (see: https://support.apple.com/en-us/HT211861).
Even if Typora (1.3.7) shows as "**_Application (Universal)_**" (no need of Rosetta), it needs it at least for the "**_global search_**" feature.

**Comment by abnerlee** [comment]
fixed in 1.4.4
