### ISSUE TITLE
View Outline Panel in Source Code Mode

### ISSUE THREAD

**Issue by pascalschumann** [typora/typora-issues#538]
I have the following feature request:
An option to view the outline panel in source code mode.

**Reason:**
Since I write very long files, it is hard to navigate trough the document in source code mode. Switching to read mode and picking the header in the outline doesn't help either, because when switching back to source code mode, the editor jumps back to the last position.

**Comment by abnerlee** [comment]
Source code mode will not maintain the outline meta info. And we do not plan to focus too much on source code mode. It is designed for temporary usage

**Comment by phlegmaticprogrammer** [comment]
I don't know, I kind of like the source code mode (I could do without the focus and typewriter mode, though 😁)! It is strange that after changing into source code mode the outline (or file tree etc.) disappears. It seems that the source code mode should be easier to do properly than the wysiwyg mode.
