### ISSUE TITLE
Fails to import docx and tex files in Linux

### ISSUE THREAD

**Issue by red-rhett** [typora/typora-issues#5380]
- [ x ] Searched existing issues to avoid creating duplicates.

- [ x ] Confirmed that it can be reproduced in built-in themes without customized css.

- [ x ] Searched http://support.typora.io/

----

**Describe the bug**

Importing either `.docx` or `.tex` files results in error: 
"The extension raw_tex is not supported for GFM."
This happens on different files and is repeatable.  
Pandoc is installed correctly, I believe. 

**Expected behavior**

The MacOS installation of Typora cleanly imports those same files with `.docx` and `.tex` extensions and converts to markdown format. 

**Screenshots / Screencasts**

One screenshot is attached. 

**Desktop:**
 - OS: Endeavour OS / ArchLinux 64 bit

**Typora Version**
- Version 1.3.6

![Screenshot from 2022-08-20 10-15-45_1](https://user-images.githubusercontent.com/12018009/185739022-6c919ed7-4329-4af0-a15f-fcca201e1103.png)

**Comment by abnerlee** [comment]
fixed in 1.4.4
