### ISSUE TITLE
How to add custom RootCA when behind Proxy

### ISSUE THREAD

**Issue by PackElend** [typora/typora-issues#5381]
Hello,
how can I add a custom RootCA as my internet traffic goes through Zscaler proxy solution to analyse HTTPS traffic.
Currently, I'm not able to run an update:
![image](https://user-images.githubusercontent.com/3542031/185748170-c04f3d35-f739-4590-9d14-3bcfef460452.png)

**Comment by abnerlee** [comment]
Typora uses system proxy / CA, so you can add our RootCA in your Windows system.

Or, you could set  env variable `NODE_TLS_REJECT_UNAUTHORIZED=0` when launch Typora

Or, you can launch typora with `--no-proxy-server` command line argument to open typora without Zscaler proxy (or, you can put it in config files https://support.typora.io/Launch-Arguments/)

**Comment by PackElend** [comment]
> Typora uses system proxy / CA, so you can add our RootCA in your Windows system.

I assume you mean:
![image](https://user-images.githubusercontent.com/3542031/187367479-319dcd73-b0d5-4f31-a57c-cd021d40b0e8.png)
It contains the root CA but seems not to work with Typora. 

I remember that I had to add them manually to Firefox, may I have to set something in Typora as well? 
Maybe that helps: 
`--client-certificate="path": Use certificate file at path.`

**Comment by abnerlee** [comment]
To ignore it: `--ignore-certificate-errors`

To specify the root: `--cast-developer-certificate-path` (https://peter.sh/experiments/chromium-command-line-switches/#ignore-certificate-errors)
