### ISSUE TITLE
Disable the blinking cursor in Word for Mac

### ISSUE THREAD

**Issue by Hazan972** [typora/typora-issues#5382]
Hi there,

Can someone please show me a way to disable the blinking/flashing cursor in Word for Mac (not the mouse pointer)?

I'm on Monterey 12.5 version of Mac OS and Microsoft Word version 16.62.

I have already tried the global methods suggested in other places:

defaults write -g NSTextInsertionPointBlinkPeriodOn -float 200
defaults write -g NSTextInsertionPointBlinkPeriodOff -float 20
(This method worked in other places such as Notes, Reminders, etc.)

I have also tried Word specific method (from a post dating back to 2011):
defaults write ~/Library/Preferences/com.microsoft.Word NSTextInsertionPointBlinkPeriod -int 5000

I have been wanting to do this ever since I got my laptop back in 2020 December. I used to have a PC where I disabled the blinking.

Your help is greatly appreciated.

Thanks

**Comment by abnerlee** [comment]
You mean in Word, or in Typora?
