### ISSUE TITLE
[Feature] Some suggestion about image in typora: auto rename image, sync rename image folder and sync delete image file

### ISSUE THREAD

**Issue by Isuxiz** [typora/typora-issues#5383]
Hi there. I have several suggestion to make typora more convenient to use:

1. Auto rename by rule and regex. Is it possible to add a function to rename the image file according to a specific rule or regular expression when saving the pasted image to the local? For example, a image may be saved locally in a format like "[YYYY-mm-dd HH-MM- SS]\_[attached md file name]_[picture number]".
2. Sync rename image folder. Add an option inside Typora to change the filename of the markdown file. And this action will also change the name of its images folder.
3. Sync delete image file. When deleting an image in a markdown file, pop a query modal to decide whether to delete the image file in attached image folder at the same time. If the user can set the default behavior (delete the file at the same time or keep the file) to avoid every time poping a query window it would be ever great.

**Comment by abnerlee** [comment]
put into #2198
