### ISSUE TITLE
[Question] Picture auto update when file changed

### ISSUE THREAD

**Issue by emako** [typora/typora-issues#5385]
印象中过去旧版本支持插入的图片文件被改动时，Typora会自动刷新图片。
现在正在使用的版本`1.3.8`不支持自动刷新图片，想问问有预定加入此类功能吗？

**Comment by emako** [comment]
重新试了一下，好像又生效了，可能是潜在BUG

**Comment by abnerlee** [comment]
等下次不生效的话可以提供下复现步骤
