### ISSUE TITLE
[Feature] Recognize .qmd (Quarto markdown) files

### ISSUE THREAD

**Issue by lillemets** [typora/typora-issues#5387]
There is yet another standard and file extension for Markdown available, this time for [Quarto](https://quarto.org/). Typora recenty added support for the Rmarkdown extension `.rmd` for Rmarkdown. Quarto markdown is a new advanced alternative to Rmarkdown and is now quickly gaining traction.

So I believe that there are a lot of people who would like to access `.qmd` files from the file tree.

**Comment by abnerlee** [comment]
supported in 1.4.4
