### ISSUE TITLE
Missing the right click context menu in macOS Ventura?

### ISSUE THREAD

**Issue by kamusis** [typora/typora-issues#5388]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Not sure if it's releated to macOS Ventura, but in my Typora 1.3.7 for macOS, there is no context menu when right click, instead of the macOS standard menu, as below
<img width="747" alt="image" src="https://user-images.githubusercontent.com/1849506/186416167-4b75a20c-2d99-441d-bc79-a9a9b533044a.png">

**To Reproduce**
1. Go to any page in Typora
2. Right Click

**Expected behavior**
Should dispaly the context menu

**Screenshots / Screencasts**
Aee above

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0

**Typora Version**
1.3.7 (6424)

**Additional context**

**Comment by abnerlee** [comment]
#5043
