### ISSUE TITLE
Changing mermaid font family for the sequence diagram actors

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#5389]
I am using `Typora 1.3.8` with the `GitHub` default theme.
The simplest possible sequence diagram prints the actors using a font with serif:
![image](https://user-images.githubusercontent.com/5183152/186675738-9ee53413-c9e4-43f9-a820-18f6dea8acc5.png)

I want to get rid of the serifs and tried different options:
- Adding the following in `github.user.css`:

```
text.actor {
    fill: black;
    stroke: none;
    font-family: Helvetica;
}
  ```

- Adding the following in `github.user.css`:

```
:root {
    --mermaid-font-family: "Open Sans", verdana, arial, sans-serif;
}
```

In any case, the serifs are always there.

Reading the [`mermaid` docs](https://mermaid-js.github.io/mermaid/#/sequenceDiagram) it is suggested to change the parameter for `actorFontFamily` but I don't know where to change these parameters in `typora`.

Questions:
1. How to get rid of the serifs on `mermaid`?
2. How to change the other styling parameters from `typora`?

TIA

**Comment by abnerlee** [comment]
supported in 1.4.1-dev

https://support.typora.io/What's-New-1.4/#diagram
https://mermaid-js.github.io/mermaid/#/./directives
