### ISSUE TITLE
[Feature]Could you help the left explore sidebar user friendly.

### ISSUE THREAD

**Issue by YanMiaoW** [typora/typora-issues#5391]
I'm useing Vscode for programing and Typora for taking notes. 
I found a different between Vscode and Typora, when I open a new tab, the explore sidebar will be created. When I open another tab, the explore sidebar will be created again! 
Seems like the explore sidebar is belong to the tab window.
In vscode, The explore sidebar is global. I can open many files and switch among files by click the filename in the explore sidebar.
I found global the explore sidebar is more useful, because I need switch files or open another file in the explore.

**Comment by abnerlee** [comment]
Currently, the tab is provided and managed by macOS natively, which allows you to merge tabs for different folder and view under one window. We would temporarily close this since it requires a lot of works and changed some of current features.

And relates #1000
