### ISSUE TITLE
[Feature] acute/backtick press on selected text to behave as quotes do

### ISSUE THREAD

**Issue by hrgdavor** [typora/typora-issues#5392]
If you have a selection that you want to convert to inline code block it more complicated than for quotes.

in Typora pressing quote when there is selection adds quote to selection, but if backtick is pressed the selected text is replaced with
a single backtick.

I love typora and have been using it for a long time, but I also use backtick so much that I am starting to prever doing my markdown editing in vscode when writing coding related texts with lots of inline code blocks.

**Comment by abnerlee** [comment]
It is supported. You can enable this in preferences panel.

duplicated of #1326

**Comment by hrgdavor** [comment]
oof nice. I did search issues but failed to find. Thanks for the hint, I see this was solved waaaay looong time ago 2018.
