### ISSUE TITLE
中文站支持页面“https://support.typoraio.cn/Install-and-Use-Pandoc/”文档存在歧义问题

### ISSUE THREAD

**Issue by xiaozhiyuqwq** [typora/typora-issues#5393]
尊敬的 Typora 开发者（[[hi@typora.io](mailto:hi@typora.io)](mailto:hi@typora.io)）：

好像在文档之中存在一些误导的倾向。我是中文用户，无法访问 Typora 官方支持站点，使用的是中文站点（[[Typora 官方中文站 (typoraio.cn)](https://typoraio.cn/)](https://typoraio.cn/)）在页面：[[Install and Use Pandoc - Typora Support (typoraio.cn)](https://support.typoraio.cn/Install-and-Use-Pandoc/)](https://support.typoraio.cn/Install-and-Use-Pandoc/) 中“Which file types can be imported or exported by Typora?”之中，“Export supports file formats of: HTML, PDF (these two do not need Typora), Docx, odt, rtf, Epub, LaTeX, Media Wiki.”应该是“(these two do not need PanDoc)”吧（我也不太确定）。希望官方能给予回复。

另外英文使用有道翻译（[[在线翻译_有道 (youdao.com)](https://fanyi.youdao.com/)](https://fanyi.youdao.com/)）可能存在语句不同的情况，请谅解。（笑）

Dear Typora developer ([[hi@typora.io](https://github.com/typora/typora-issues/issues/Mailto%20:hi@typora.io)](Mailto :hi@typora.io)) :

There seems to be a tendency to mislead in the documentation. I am a Chinese user and cannot access the official support site of Typora. I am using the Chinese website ([[Typora 官方中文站 (typoraio.cn)](https://typoraio.cn/)](https://typoraio.cn/)) on the page: Installation and use of [[Install and Use Pandoc - Typora Support (typoraio.cn)](https://support.typoraio.cn/Install-and-Use-Pandoc/)](https://support.typoraio.cn/Install-and-Use-Pandoc/) "Which file types can be Imported or exported by Typora? ", "Export supports file formats of: HTML, PDF (these two do not need Typora), Docx, odt, rtf, Epub, LaTeX, "Media Wiki." should be "(These two do not need PanDoc)" (I'm not sure). I hope the official can reply.

Another English use youdao translation [[在线翻译_有道 (youdao.com)](https://fanyi.youdao.com/)](https://fanyi.youdao.com/) there may be a statement of different situation, please understand.

![image](https://user-images.githubusercontent.com/72379760/187054326-3694f79b-4960-4ce6-9a78-34c0a2313181.png)
![image](https://user-images.githubusercontent.com/72379760/187054328-00bc76a7-9a31-4090-8ce1-93a5f3a1b5e7.png)
![image](https://user-images.githubusercontent.com/72379760/187054331-561ce6dd-9180-4036-a376-4a53e2eae2b8.png)

**Comment by abnerlee** [comment]
fixed
