### ISSUE TITLE
Sort and Sidebar Menu Issue

### ISSUE THREAD

**Issue by 1999FordFocus** [typora/typora-issues#5396]
**Describe the bug**
The latest version has just broken the `Sort by Modification Date`.
The Sidebar menu quickly dismissed after reclicking on the more options icon.

**To Reproduce**
- sort issue
Simply create some markdown files and test the sorting function.
- sidebar menu issue
  1. click the more options icon to open the sidebar menu.
  2. close it by clicking the close icon.
  3. reclick the more options icon.

**Screenshots / Screencasts**

https://user-images.githubusercontent.com/9652173/187877946-05660858-6f4e-4481-9e45-979ca110b7cd.mov

**Desktop:**
macOS 12.5.1

**Typora Version**
1.4.2

**Comment by erikcc02** [comment]
This happens to me too!

**Comment by abnerlee** [comment]
should be fixed in v1.4.3
