### ISSUE TITLE
Disable real-time searching in Typora

### ISSUE THREAD

**Issue by huangwb8** [typora/typora-issues#5399]
Searching in Typora is a real-time process. For example, if I want to search `actor`, the searching would begin from a, ac, act, and so on.

It seems to not be a problem in a small markdown. But in a large markdown, this automation is annoying, which really slows the searching.

Someone suggested that **code mode would be helpful,** but **I don't want to convert to the code mode**.

Is it possible to disable real-time search in Typora? I just want to search only `actor` after pressing `ENTER` key.

**Comment by abnerlee** [comment]
The find & replace speed should be fixed in 1.4.4
