### ISSUE TITLE
extend gihub markdown by auto numbered headings

### ISSUE THREAD

**Issue by pascalschumann** [typora/typora-issues#540]
I know, github markdown does not contain such a thing. 
But for long documents it would be great having auto numbered headings. 
Since this is **the** feature to use latex, besides math of course. 
Diploma thesis and other long essays need auto numbered headings.
Thank you.

**Comment by abnerlee** [comment]
see http://support.typora.io/Auto-Numbering/

**Comment by EganSolo** [comment]
The auto-numbering works great _within a file_ but for a document spanning several files, there does not seem to be a way to get the auto-numbering feature to continue across files. 
Say I have three files
file_1
file_2
file_3
Auto numbering will start numbering in each file with the number 1. Is there a way to force the numbering in each file to start with 1 for file_1, 2 for file_2 and 3 for file_3?
