### ISSUE TITLE
Windows Installer Unsigned

### ISSUE THREAD

**Issue by TheMTtakeover** [typora/typora-issues#5401]
Windows installer "typora-setup-x64-1.4.3.exe" doesn't appear to be signed and is flagged by windows defender. I do not get this issue with version 1.3.8.

I tried downloading twice to verify

**Comment by abnerlee** [comment]
You can check signing info in context menu → Properties.

Being signed will reduce the chance of being flagged by windows defender, but it does not mean it can ensure no flagged by windows defender
