### ISSUE TITLE
Line number of code block is messy when exported to pdf file

### ISSUE THREAD

**Issue by colingonglin** [typora/typora-issues#5409]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Line number of code block is messy when exported to pdf file. Characters are overlapped when the number is greater than 10

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://user-images.githubusercontent.com/12727213/188840865-c0c63e14-c31d-4f67-83d0-d26cedf7e90a.png)

[bad.pdf](https://github.com/typora/typora-issues/files/9504703/bad.pdf)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.
[bad.md](https://github.com/typora/typora-issues/files/9504717/bad.md.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.4.4

**Comment by abnerlee** [comment]
Will this happen if you export again? If so, could you provide a screencast about the operation as in our test it works fine?

**Comment by colingonglin** [comment]
Yes, it can reproduce as long as you set the font size to 20 or larger. I have noticed even in the editor the numbers will overlap.

**Comment by abnerlee** [comment]
fixed in v1.5.x
