### ISSUE TITLE
How to add more latex environment support?

### ISSUE THREAD

**Issue by scruel** [typora/typora-issues#5412]
```
$$
\begin{table}
\end{table}
$$
```

Will get unknown environment error:
![image](https://user-images.githubusercontent.com/16933298/189262268-8ef104f3-b8c5-44ad-b763-ca767e37297e.png)
Is there any way that can support this?

Other commands like `\hdotsfor{}` also not supported.

**Comment by abnerlee** [comment]
put into #100
