### ISSUE TITLE
Math copy as HTML/image in Math block doesn't work, nothing is copied 

### ISSUE THREAD

**Issue by frankyan** [typora/typora-issues#542]
I found that `Math->Copy as HTML/image` doesn't work in Math Block, where nothing is copied. `Copy as Tex` also doesn't work. But `Copy as MathML` works. The following is an example.
```
$$
\mathit{3x^2 \in R \subset Q} \\ \int_{0}^{100}3x^2d
$$
```
However, using inline Math, the copy function works. For example:
```
$$\mathit{3x^2 \in R \subset Q} \\ \int_{0}^{100}3x^2dx$$
```
Besides, is there any convenient way to decode and convert the copied Base64 coded SVG to image?

System: Windows 10 64bit
Typora: 0.9.23beta 64bit

**Comment by norux** [comment]
macOS also, with some different point.
In macOS, `Math->Copy as HTML/image` copy some image's URI data (starting `data:image/svg+xml;base64,DATA...`)

But I think it is wrong data.  I only can see '?' box.

<img width="112" alt="2017-05-08 10 01 28" src="https://cloud.githubusercontent.com/assets/4457861/25786854/6f0212fc-33d6-11e7-9ab4-d4de12542981.png">


macOS 10.12.3(16D32)
Typora 0.9.9.9.4.2 (0.9.9.9.4.2)

**Comment by orschiro** [comment]
I cannot even find this `Math->Copy as HTML/image` on Linux.

In which sub-menu is it?

**Comment by norux** [comment]
@orschiro , You can see mouse right-click over Math block

![image](https://cloud.githubusercontent.com/assets/4457861/25793498/b9235220-3407-11e7-9ffb-60511fee8fd7.png)
Screenshot on macOS, but same in linux.

**Comment by orschiro** [comment]
I might be doing something wrong then...

![image](https://cloud.githubusercontent.com/assets/170947/25796466/e4632a92-33d9-11e7-9de1-6dd561c7161a.png)

**Comment by norux** [comment]
Sorry. **Exacty** not in Math block. Should be mathematic image.

1. uncheck `View->Source Code Mode`
2. focus-out in Math block. then mathematic image will be created.
3. right-click over image.

**Comment by orschiro** [comment]
Sorry, I still don't get it.

Can you please look at this screencast?

https://youtu.be/UVGXv0Ev2ew

**Comment by norux** [comment]
Write another paragraph and try again. :)

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/25800319/19081f96-33e9-11e7-803d-a2955ac0cace.png)

**Comment by norux** [comment]
Please see my youtube.
https://youtu.be/IBjA8rUbIEA
I reproduced in Ubuntu 16.04 LTS

And I found same issue on Linux. Nothing is copied.

**Comment by orschiro** [comment]
@norux thanks for trying Ubuntu. 

In this case, I have no idea why it's not working for me...

**Comment by abnerlee** [comment]
Close since copy as HTML/Image on math is not supported in current version.
