### ISSUE TITLE
PDF Export: Page numbering error & Footer missing

### ISSUE THREAD

**Issue by Papouchcom** [typora/typora-issues#5421]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
1) When inserting a [custom cover page](https://support.typora.io/Export/#add-custom-content-pdf) and a longer [code block](https://support.typora.io/Markdown-Reference/#fenced-code-blocks), export to PDF will result an error in page numbering in the footer. The footer is only inserted on some pages and the page number is not correct.
2) Footer on cover page overlays custom cover page (#5405).
3) Related: #4478, #4918

**To Reproduce**
Both the MD source file and the resulting PDF are attached.

**Expected behavior**
1) I expect a footer on every page and correctly numbered pages.
2) If I am inserting a custom cover page, it would be nice if the standard footer could be hidden on the cover page.

**Sample Markdown File**
Source markdown and exported pdf attached:
* [Issue.md](https://github.com/typora/typora-issues/files/9554687/Issue.md)
* [Issue.pdf](https://github.com/typora/typora-issues/files/9554694/Issue.pdf)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
- 1.4.4 (licensed :) )

**Comment by martinezpenya** [comment]
I'm facing same issue, and also footer overlaps text that can't be read.

**Comment by martinezpenya** [comment]
I've downgraded to 1.3.6 version on linux 64bits deb version and it's working perfect.

**Comment by Papouchcom** [comment]
The footer is already rendering correctly. It does not overlap with the code block or the actual cover page. Thanks for the quick fix! 👍
Here is the PDF generated by version 1.4.7: [Issue.pdf](https://github.com/typora/typora-issues/files/9608160/Issue.pdf)

So just "turn off" the footer on cover page and it will be perfect 🙂

**Comment by abnerlee** [comment]
original issue is fixed.

footer on cover page issue is addressed in #4478
