### ISSUE TITLE
Preview in Articles view renders first #text incorrectly

### ISSUE THREAD

**Issue by tslaton** [typora/typora-issues#5422]
**Describe the bug**
In the document preview using the Articles mode, the first hashed text does not render with the `#` included. 

**To Reproduce**
Look at the sample Markdown file in any theme (screenshot uses the default Night theme).

**Expected behavior**
I'd expect to see `#tag1 #tag2 #tag3` in the first line of the document preview, with the `#` rendered. I'm guessing it's dropped because it thinks the first one is a header?

**Screenshots / Screencasts**
<img width="370" alt="Screen Shot 2022-09-13 at 13 22 42" src="https://user-images.githubusercontent.com/9665562/190001815-f745db0a-755d-4217-b8b3-5af6ba8b7ea1.png">

**Sample Markdown File**
```markdown
#tag1 #tag2 #tag3

# Title

Content here

```

**Desktop**
macOS 12.6

**Typora Version**
1.4.4

**Additional context**
I'm aware that Typora [does not yet support tags as a dedicated feature](https://support.typora.io/File-Management/#tags). I was hoping to just structure my files like the above sample and search for whichever `#tag`, with the articles' previews serving as a visual reminder of which tags are relevant. When doing this, the inconsistency in the rendering of each `#tag` is mildly irritating. :)

With first class support for tags, I'd imagine these might become clickable links to execute a search, etc. and might render differently than plain text anyway. But I'm guessing the fix for the current display issue without supporting tags as a concept/feature is much simpler.

**Comment by abnerlee** [comment]
fixed in v1.5.x
