### ISSUE TITLE
[Feature] Change arrows --> to ⟶ in pseudocode code blocks

### ISSUE THREAD

**Issue by hexaquarks** [typora/typora-issues#5427]
## Feature
For code blocks of language `pseudocode`, it would be nice to have a processor that changes either `<--` to a left arrow or `<-` to a left arrow  ⟵, and similarly with the right arrow ⟶.

For instance
```pseudocode
Merge(A, p, q, r)
  n_1 <-- q - p + 1
  n_2 <-- r - q
    do L[i] <-- A[p + i - 1]
```
to 
```pseudocode
Merge(A, p, q, r)
  n_1 ⟵ q - p + 1
  n_2 ⟵ r - q
    do L[i] ⟵ A[p + i - 1]
```

## Utility of this feature
Arrows in pseudocode are extensively used. It is infrequent that you'll encounter a pseudocode snippet without arrows, given that something as fundamental as a variable assignment is expressed with the arrow operator. 

This should probably be low-cost to implement development wise and since Typora is used by many computer scientists, mathematicians, and software engineers this would be a practical implementation.

**Comment by abnerlee** [comment]
duplicated with #1115
