### ISSUE TITLE
[Feature] Can you add a theme with a wide editing area to the built-in theme?

### ISSUE THREAD

**Issue by aszswaz** [typora/typora-issues#5428]
Typora's existing built-in themes, the editing area is too small. I know width works for most blog sites or github, but I don't need to publish documentation on blog sites, I just use typora to write notes, although the notes will be uploaded to github, I don't care how github shows comments for me.

In order to make the editor wider, you need to manually modify the "max-width" of the theme every time you install typora, such as "max-width: 95%", I think "95%" is a good editing area width.

I want a built-in theme with this edit area width so that I don't have to do this repeatedly.

In addition, the page used to display the Markdown source code can also increase the width of the editing area. I think, this page doesn't need to have the same width as blog and github.

**Comment by abnerlee** [comment]
duplicated with #3805
