### ISSUE TITLE
Cannot render Latex between `$` and `$`.

### ISSUE THREAD

**Issue by hwhsu1231** [typora/typora-issues#5431]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

### **Describe the bug**

Cannot render Latex between `$` and `$`.

I remember that this problem didn't exist before Typora started to charge. However, I found this problem occurs recently.

### **To Reproduce**

Copy and paste the following content:

``````
This is a fraction $\frac{2^{2}}{6}$.
``````

### **Expected behavior**

Take VSCode for example:

![image](https://user-images.githubusercontent.com/71438617/191032307-68f71ce9-be0e-48e3-ab37-bdb191393283.png)

### **Screenshots / Screencasts**

However, in Typora:

![image](https://user-images.githubusercontent.com/71438617/191032746-c93c9021-9f0c-4314-93b8-3dc814dfe449.png)

### **Sample Markdown File**

[latex-example.md](https://github.com/typora/typora-issues/files/9599449/latex-example.md)

### **Desktop (please complete the following information):**

 - OS: Windows 11 x64

### **Typora Version**

- 1.4.4 for Windows (x64)

### **Additional context**

I think this issue related to: https://github.com/typora/typora-issues/issues/4904, but I don't know why it was closed.

**Comment by CompetitiveLin** [comment]
file-preference-advanced

![image](https://user-images.githubusercontent.com/55691019/191139816-abc2d766-f80b-4704-adb9-4c06d9731b9b.png)

**Comment by hwhsu1231** [comment]
@CompetitiveLin Got it. Thank you.
