### ISSUE TITLE
Relative paths should be default for pasted in images, or images in general

### ISSUE THREAD

**Issue by BrickedKeyboard** [typora/typora-issues#5432]
If I drag or paste in an image, the path for it is some big absolute path on the machine I created it on.    

Replication:
drag an image in from the same folder or a subfolder of where the document is located.

 observed behavior:
    ![image-20220919153917100](C:\Users\username\OneDrive - company name\Documents\image-20220919153917100.png)
  
correct behavior:
  !{image-20220919153917100}(image-20220919153917100.png)

Implementation logic:
   check if the image is in the _same_ folder as the document, or a _subfolder_ below the level of the document being edited.  Substitute the shorter path instead.  python's pathlib can do this behavior in a few lines.  This way someone can immediately commit the edited markdown document and image to git and it will work on other people's machines and github preview.

Not sure if this is a bug or a feature.  In my opinion it's a bug - it wastes a ton of user time to have to fix this aberrant behavior.

**Comment by abnerlee** [comment]
It is supported. You can config in preferences panel
