### ISSUE TITLE
Headings with long `<code>` will overflow in Outline

### ISSUE THREAD

**Issue by YDX-2147483647** [typora/typora-issues#5436]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Headings with long `<code>` will overflow in Outline (in the side bar).

**To Reproduce**

```markdown
# Heading 1

## An extremely long heading (regular text)

## An extremely long heading (with `a_long_long_long_long_long_long_long_long_long_long_code`)

### You should align yourself with me ↓

### Lower level heading (with `a_long_long_long_long_long_long_code`)

### And me ↑
```

1. Save the above as a markdown file and open it.
2. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> to open the Outline.

**Expected behavior**

They should collapse into lines, and align with other headings.

**Screenshots / Screencasts**

<img width="960" alt="屏幕截图 2022-09-20 201559" src="https://user-images.githubusercontent.com/73375426/191255053-2f58696d-a7f1-459c-90b0-b111c6eeeefb.png">

**Desktop:**
 - OS: Windows 10 64bit

**Typora Version**
1.4.7

**Additional context**

[`overflow-wrap: anywhere`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap#values) may fix it.

// I believe a good heading never contains such a long code, but we don't always want to write good articles. Besides, thanks in advance.

**Comment by abnerlee** [comment]
fixed in v1.5.x
