### ISSUE TITLE
[Feature] Upload all images at once

### ISSUE THREAD

**Issue by chgeuer** [typora/typora-issues#5439]
It would be great if one could trigger the image upload process for *all* images in a Markdown file at the same time, instead of "Right-click/Upload Image" for each image individually. 

Having said that, it would be good to trigger this for *each* image, including those that already have an address in http/https space. (I'm using my [Azure Uploader](https://github.com/chgeuer/TyporaUploaderAzure/) to upload images which are 'somewhere' on some web server into my own storage, i.e. I right-click "Upload" on images which are already 'uploaded' someplace else.

**Comment by abnerlee** [comment]
https://support.typora.io/Upload-Image/#upload-all-local-images

**Comment by chgeuer** [comment]
Thanks @abnerlee , first of all, I didn't see that menu, and it's great. This works perfectly (for local images in the local file system). 

Now I understand that I can solve my scenario with 2 steps: First "Format/Image/Move all images to.." which downloads all images from (foreign) Internet locations to my local disk, and then your "upload all local images"... Good stuff, thanks again.
