### ISSUE TITLE
using Latex Windows results in 99% CPU load

### ISSUE THREAD

**Issue by pascalschumann** [typora/typora-issues#544]
Problem:
![latex](https://cloud.githubusercontent.com/assets/18259965/23099483/b21317f4-f668-11e6-9ba6-33a6cb8381a4.PNG)

Occurrence:
Using simple formula like x=\frac{a}{b} in latex on Windows.
Did you use while(true) or other endless loops? If so, that will always result in 99% CPU load.
Thank you.

**Comment by pascalschumann** [comment]
Maybe it is not related to latex.
Problem:
'Save' action (button or CTRL-S) writes empty file(the existing is overwritten), only 'save as' works. If 'save' is used, cpu load rises to 99% and stays at it.
I guess, typora is developed for mac? since saving is such a basic feature, someone must have noticed it.
Plattform is Windows 8.

**Comment by abnerlee** [comment]
Please reopen if it still happens in new release
