### ISSUE TITLE
Inline math not working

### ISSUE THREAD

**Issue by allohakdan** [typora/typora-issues#5440]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
inline math is enabled, but does not render or replace the characters defining expression. default theme. Math blocks work as expected.

**To Reproduce**
type`` $x^3$ ``. Text Continues to show exactly as is.

**Expected behavior**
I expect the behavior described under "Inline Math" on https://support.typora.io/Math/

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/119465/191547574-05a9efda-07c6-4d0c-aa4a-c0a33e59d77d.png)

**Desktop (please complete the following information):**
MacOS 10.15.7

**Typora Version**
1.4.4

**Comment by abnerlee** [comment]
#1507
