### ISSUE TITLE
[Feature] HTML table enhancement

### ISSUE THREAD

**Issue by ldeng-ustc** [typora/typora-issues#5442]
The native Markdown has very limited table functionality, but Markdown supports HTML, which has rich table functionality. So, we can use html to generate a complex table like:

<table>
<tbody align="center" valign="middle">
  <tr>
    <th>no</th>
    <th>c1</th>
    <th style="width: 300px">Wide Column</th>
  </tr>
  <tr>
    <td>r1</td>
    <td style="border:1px solid black;">border</td>
    <td style="background-color: LightBlue;">bgcolor</td>
  </tr>
  <tr>
    <td style="height: 80px">r2</td>
    <td style="color:SlateBlue">color</td>
    <td valign="bottom">bottom-align</td>
  </tr>
  <tr>
    <td>r3</td>
    <td colspan="2" rowspan="2">Merged Cell</td>
  </tr>
  <tr>
    <td>r4</td>
  </tr>
</tbody>
</table>

Looks of this table in Typora: 

![image](https://user-images.githubusercontent.com/37360259/191691042-08d74155-650c-42f6-8941-d43350b14bb9.png)

 (It seems that github doesn't support style/width/height of cells, but at least we can have merged cell.)

Source code:

```html
<table>
<tbody align="center" valign="middle">
  <tr>
    <th>no</th>
    <th>c1</th>
    <th style="width: 300px">Wide Column</th>
  </tr>
  <tr>
    <td>r1</td>
    <td style="border:1px solid black;">border</td>
    <td style="background-color: LightBlue;">bgcolor</td>
  </tr>
  <tr>
    <td style="height: 80px">r2</td>
    <td style="color:SlateBlue">color</td>
    <td valign="bottom">bottom-align</td>
  </tr>
  <tr>
    <td>r3</td>
    <td colspan="2" rowspan="2">Merged Cell</td>
  </tr>
  <tr>
    <td>r4</td>
  </tr>
</tbody>
</table>

```

However, current Typora have limit support for HTML tables, so we have to manually write raw HTML code to generate and modify the HTML tables.

Maybe Typora could gradually add more GUI operations support for HTML tables:

* The same support as the native markdown table, such as inserting HTML tables, edit cell content, changing table size, modifying alignment, inserting and deleting rows, ...
* More flexible and powerful table functionality through HTML, such as merging cells, change width and height of cells by drag cell edges, ...

And some features can be added to both html and native markdown table:

* Select/copy/paste an area of table. (Now, a row of table is seen as a text row, so we cannot select single column.)
* Sorting, filter, and so on.
* Visual effect, such as highlight the selected cells. 

Personally, I wish tables in were as powerful as OneNote and Word. While this is difficult, I would be happy to see some of the above features supported in Typora.

**Comment by abnerlee** [comment]
#703 may meet your requirements.

Currently Typora is a markdown editor, not a HTML editor (which is a too bit topic). So this is out of our scope.
