### ISSUE TITLE
Obsidian (no folder prefix) Image Syntax

### ISSUE THREAD

**Issue by p-enis** [typora/typora-issues#5445]
I use Obsidian for my daily note taking and Typora to review the drafts, correct them and later export them to PDF. My problem is that I always need to re-write the image syntax as it seems to be not supported by Typora. I like the way Obsidian locates my images without any path, as this makes moving around images pretty easy.

I don't think Typora needs to support any fancy image location tracking as Obsidian, but being able to use the basic Obsidian image inclusion syntax would be great.

Given the following folder structure:

```plain
- <root>
  - file.md
  - assets/
    - 20220924102338.png
```

and the following Markdown:

```md
---
typora-root-url: assets/
---

This is text ...

![[20220924102338.png]]

And above an image ...

```

That Typora detects the image and displays it. Is there a way to get this behavior?

**Comment by abnerlee** [comment]
duplicated with #5274?
