### ISSUE TITLE
I am unable to get spellcheck working

### ISSUE THREAD

**Issue by francuss** [typora/typora-issues#5447]
Under Debian, I followed this https://support.typora.io/Spellcheck/
but
1 I do not see the "warning icon" mentioned in the tutorial
2. I manually downloaded the dictionaries, as suggested, but they were already present in the mentioned folder.
3. also I do not see a button to start the spellcheck or something. But nothing happens.

Many thanks for you wonderful work

**Comment by abnerlee** [comment]
What's your Typora version and system arch?

What language do you choose for spellchecker? 

Could you provide a screencast?
