### ISSUE TITLE
Typora export problems on (K)ubuntu 20.04: Can't open portal file chooser: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: invalid filter: no filters

### ISSUE THREAD

**Issue by loop28** [typora/typora-issues#5448]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
Exports fail with:
> (Typora:19750): Gtk-WARNING **: 16:15:42.155: Can't open portal file chooser: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: invalid filter: no filters
This is the same problem with all types of file-based exports

After clicking on the export method – as described in "To Reproduce" below – nothing happens other than getting the above error when launching typora directly from terminal with:
> typora file-name.md

**To Reproduce**
1. Open any markdown file with typora (use terminal for error output)
2. Click on 'file'
3. Click on 'export'
4. Choose any of the file-based methods
5. See the error in terminal

**Expected behavior**
Expected behavior would be the export dialog opening after step 4. in the "To Reproduce" section.

**Desktop:**
 - OS: Kubuntu 20.04.5 LTS (x86_64)
 - Portal: xdg-desktop-portal 1.6.0-1ubuntu1 amd64
 - DE / WM: Plasma / KWin

**Typora Version**
typora 1.4.7 (snap version from snapcraft)

**Additional context**
Based on the Gtk-warning in the terminal I suppose we are dealing with some kind of problem related to xdg-desktop-portal (other Gtk programs work fine thou). Therefore I tried using xdg-desktop-portal-gtk but that didn't work either.

**Comment by abnerlee** [comment]
Does `File` → `Save as...` pop up the save file dialog?

**Comment by GreatBahram** [comment]
Same problem here, details:
```shell
>>> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Kinetic Kudu (development branch)
Release:        22.10
Codename:       kinetic

>>> snap list
typora                     1.4.7                       74     latest/stable    typora            -

>>> typora something.md # basically, there is a problem with accessing files/file descriptors
[2269766:1004/000211.418792:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.27807" (uid=1001 pid=2269766 comm="/snap/typora/74/typora/Typora --no-sandbox --disab" label="snap.typora.typora (enforce)") interface="org.freedesktop.login1.Manager" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=1606 comm="/lib/systemd/systemd-logind" label="unconfined")
WARNING: Kernel has no file descriptor comparison support: Operation not permitted

(Typora:2269766): Gtk-WARNING **: 00:02:26.583: Can't open portal file chooser: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: invalid filter: no filters

**Comment by GreatBahram** [comment]
> Does `File` → `Save as...` pop up the save file dialog?

Not for me.

**Comment by abnerlee** [comment]
Could you try v1.4.8?

**Comment by GreatBahram** [comment]
> Could you try v1.4.8?

v1.4.8 was tested, and it's worked as expected. Thanks for the quick fix :sunflower:.

**Comment by loop28** [comment]
Same for me, the v1.4.8 solved the problem.

Thanks guys!
