### ISSUE TITLE
Table contents overlapping when rendering to PDF

### ISSUE THREAD

**Issue by yodahuang** [typora/typora-issues#545]
I find the table content may overlap each other in some cases when rendering to PDF:
![image](https://cloud.githubusercontent.com/assets/11242657/23104644/0dea82ce-f6a0-11e6-9144-3ef4e2e5dac1.png)
while in HTML, this looks all fine:
![image](https://cloud.githubusercontent.com/assets/11242657/23104659/3a76e3a0-f6a0-11e6-91d5-6fd1ebb41bed.png)
This is the source file:
[Bug.zip](https://github.com/typora/typora-issues/files/786037/Bug.zip)

**Comment by abnerlee** [comment]
fixed in new release

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/545

**Comment by sarandafl** [comment]
This happens on the Mac version as well
