### ISSUE TITLE
Turning off auto equation numbering doesn't work

### ISSUE THREAD

**Issue by kzvi** [typora/typora-issues#5451]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

In the Typora preferences, under "Markdown" and "Math", I have "Auto Numbering Math Equations" set to "No Automatic Equation Numbering", but the equations in my documents are still numbered.

**To Reproduce**
1. turn off equation numbering in preferences
1. write some math in a document
2. see that the equations are numbered

**Screenshots / Screencasts**
<img width="1733" alt="Screen Shot 2022-09-28 at 5 41 56 PM" src="https://user-images.githubusercontent.com/38590027/192913097-f9e6f337-2098-462e-8709-8c9cd671e6b2.png">

**Desktop (please complete the following information):**
 - OS: macos

**Typora Version**
Version 1.4.4 (6547)

**Comment by chenjiefeng2001** [comment]
If you want to turn off  "Auto Numbering Math Equations", you should set it to the "No Automatic Euqtions Numbering" and restart the typora, because the setting about it not support the hot update :( 
But I think this should be add in the later version?

**Comment by kzvi** [comment]
This issue persists even after a restart.

**Comment by abnerlee** [comment]
Please try restart Typora, if still persist, please share the md file.

**Comment by kzvi** [comment]
The md file is simply

```
asdf

$$2+2=4$$

asdf

$$2+2=4$$
```

**Comment by sweetbiscuit-dy** [comment]
Hi @kzvi, I have the issue exactly like yours, tried to quit and reopened the software multiple times but the issue persisted. After updating both my MacOS and Typora to the latest versions, which are Ventura 13.2.1 and 1.5.8, respectively, my issue was gone. 
Hope this provides a way to deal with this issue. :)

**Comment by mrmcduff** [comment]
Still having this issue in 2024. Any attempt to use `$$<eqn>$$`-style equations results in autonumbering. My MacOS and Typora versions are as up to date as either product will allow me to be.

**Comment by chiatsewang** [comment]
I have the same issue.

**Comment by rwang5203** [comment]
A solution is to change the setting to "Auto Numbering for All Math Equations", then restart Typora, and then change it back to "No Automatic Equation Numbering", then restart Typora again. The numbering should be gone.

**Comment by samuelpmish** [comment]
I am also having this problem on typora 1.8.10 from a mac. I tried @rwang5203's suggestion directly above this comment, but it didn't work.

**Comment by lukejanicke** [comment]
I had this issue just now with Typora 1.9.4 on macOS Sequoia 15.0. Changing the setting and restarting Typora did not fix it. However, deleting and reinstalling the app did fix it. I noticed that after reinstalling, my previous settings were still there.

**Comment by xingyuXXX** [comment]
> I had this issue just now with Typora 1.9.4 on macOS Sequoia 15.0. Changing the setting and restarting Typora did not fix it. However, deleting and reinstalling the app did fix it. I noticed that after reinstalling, my previous settings were still there.

same issue with typora 1.9.4 and macOS Sequoia 15.1, m2 chip. Reinstall doesn't fix the issue
