### ISSUE TITLE
How to setup proxy on typora in macos

### ISSUE THREAD

**Issue by Neiiiiil** [typora/typora-issues#5452]
Hello!

I really enjoy editing my notes with Typora.

For some reason, some of the images I introduced could not be loaded, so I needed to use a proxy to get those resources to load properly. I tried to search on the official documentation and found that only Linux/Windows setup methods are provided, and I can't find the configuration file on Mac OS.

I need you to teach me how to configure the proxy on Mac OS.

Thank You!

**Comment by abnerlee** [comment]
It use the system proxy, you just need to set it as system proxy and check if you can load it in Safari
