### ISSUE TITLE
[Feature]Add more IDE-related keyboard shortcuts, such as inserting rows below, moving rows down, copying rows down, and so on

### ISSUE THREAD

**Issue by yidai321** [typora/typora-issues#5453]
![image](https://user-images.githubusercontent.com/74451370/193396730-56842828-1470-4bad-ac37-a416f0d1a32b.png)
---
### These are not enough.
![image](https://user-images.githubusercontent.com/74451370/193396987-0c77debd-f03d-4125-bcbe-294c50adc32c.png)

**Comment by abnerlee** [comment]
Put into #1211
