### ISSUE TITLE
Typora won't let me save (Ubuntu)

### ISSUE THREAD

**Issue by avielbr** [typora/typora-issues#5454]
- [ X] Searched existing issues to avoid creating duplicates.

- [X ] Searched http://support.typora.io/

----

**Bug description**
When I try to save a file from Typora either with CTRL+S, or File>Save, or File>Save as, nothing happens - nothing opens to let me choose a file save location. When I close Typora, I get a warning that the document is unsaved, but when I click the "Save" button nothing happens.

**To Reproduce**
Try to save a file on Ubuntu Jammy Jellyfish.

**Expected behavior**
I would expect a way to save the file -- **Note that for a while I was able to save files reliably! This is a new problem**

**Sample Markdown File**
This occurs with any arbitrary text

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu Jammy Jellyfish

**Typora Version**
1.4.7 Linux x64 SNAP

**Comment by abnerlee** [comment]
same with #5448?

Could you try open Typora in terminal and do save and then report the error message in terminal?

And does deb / binary version work?

**Comment by avielbr** [comment]
Not sure why this was closed, but no - it's not the same problem. My issue concerns saving. The one you linked concerns exporting.

**Comment by abnerlee** [comment]
@avielbr the snap version 1.4.8 should fixed the save dialog issue.
