### ISSUE TITLE
Typora after upgrade to version 1.4.7, error received when saving a copy of existing file

### ISSUE THREAD

**Issue by jschwar313** [typora/typora-issues#5455]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

I don't know what 3rd party themes or css are.  I don't think I use them.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Opened a file I had created in a previous version of Typora, then upgraded Typora to 1.4.7, then tried to save the file with a new name.  I received the error message mentioned in the screen print.  I've also attached the original markdown file to this issue.

**To Reproduce**
See above.

**Expected behavior**
I tried saving a new version of the file with the same name, but v2 added at the end of the file name before the extension.

**Screenshots / Screencasts**
![typora error screenshot](https://user-images.githubusercontent.com/71224599/193458922-8f720bb4-2c2a-4427-800b-8c180ee42a88.jpg)

**Sample Markdown File**
[README.md](https://github.com/typora/typora-issues/files/9692774/README.md)

**Desktop (please complete the following information):**
Windows 10, 64-bit

**Typora Version**
1.4.7

**Additional context**
None

**Comment by jschwar313** [comment]
This still happens in version 1.4.8, too.  I save the file as README v2.md and I get the same stack trace.  The file exists and I tell it to overlay it.

**Comment by abnerlee** [comment]
fixed in v1.5.x
