### ISSUE TITLE
Beta version does not work anymore

### ISSUE THREAD

**Issue by silas229** [typora/typora-issues#5458]
Since today I am no longer able to open the latest beta of Typora.
> **Error**
> This beta version of Typora is expired, please download and install a newer version.

Of course I understand that you need financial support for your hard and awesome work, but I also don't think it's fair to make the beta versions freely available for download and then artificially shut them down. Please make this "expiration date" clear from the beginning or **remove this restriction**!

**Comment by abnerlee** [comment]
Please use the dev version instead, they are the new "beta".
