### ISSUE TITLE
Typing HTML entities mid-sentence causes the cursor to be incorrectly positioned

### ISSUE THREAD

**Issue by omgmog** [typora/typora-issues#546]
## Problem

When typing HTML entities (such as `&mdash;` or `&nbsp;`) mid-sentence, the cursor is positioned  in the wrong place in the line after the entity is replaced.

I've made a little gif to illustrate this:

![](https://media.giphy.com/media/3o84UgMJ8R3RqLfQpG/giphy.gif)

As you can see in the mid-sentence example, after the `&mdash;` is replaced with a `—`, the cursor remains the length of the entity away from the starting position.

**Comment by AlexPasternak** [comment]
That seems like a good bug find!

**Comment by abnerlee** [comment]
Should be fixed in the newest version
