### ISSUE TITLE
Change font for code blocks and inline exclusively.

### ISSUE THREAD

**Issue by Fractal7** [typora/typora-issues#5460]
I can change the font for code blocks as described https://support.typora.io/Custom-Font/

For example, I have a file named "base.user.css" in the "themes" folder with the following contents:
```
.md-fences {
    font-family: Courier New;
    background-color: #899da2
 }
```

While this works great, I'd like to also do this for inline code as well. However, i don't want to modify the font and background-color for all non-code in the document. Is there a way to achieve this?

On the Typora support page I only see instruction/guidance for modifying the font for the code blocks or everything including the code blocks.

**Comment by abnerlee** [comment]
You can use `code` selector for all the codes.

```css
code {
  font-family: Courier New;
    background-color: #899da2
}
```
