### ISSUE TITLE
Windows Unibody: Minimize title bar button is blurry and inconsistently styled

### ISSUE THREAD

**Issue by cswartzvi** [typora/typora-issues#5462]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When running on Windows with the Unibody style enabled the minimize title bar button is blurry and inconsistently styled. See image below. Note that this does _not_ happen to the maximize title bar button.

**To Reproduce**
1. Go to 'Preferences' > 'Appearance' 
2. Select 'Unibody'
3. Restart Typora
4. Maximize the window

**Expected behavior**
The minimize title bar button should be clear. Below is a picture of another application (VS Code) that also draws their own title bar button vice using those provided by the OS:
![Buttons-Vscode](https://user-images.githubusercontent.com/1111348/194704102-e5dd2c3b-ab7f-4494-88a9-af95dfd6be93.png)

**Screenshots / Screencasts**
Here is an example of the blurry minimize title bar button in Typora:
![Buttons-Typora](https://user-images.githubusercontent.com/1111348/194703930-4360cae1-7859-4227-8c8d-fe17dbedd408.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
- 1.4.8 (and previous versions)

**Additional context**
Admittedly, this is a minor problem, but since Typora focuses on aesthetics, I thought I should bring it to your attention. BTW, I love this app! 😁

**Comment by abnerlee** [comment]
fixed in v1.5.x
