### ISSUE TITLE
[Feature] Better support for launching via external electron

### ISSUE THREAD

**Issue by sukanka** [typora/typora-issues#5463]
## Description

`typora-1.4.7` can now be launched direct via external electron ( I bought a license for this feature, so please do not remove this feature). 

Below is my directory structure for typora
```bash
➜  ~ tree /usr/lib/typora -L 1
/usr/lib/typora
├── app.asar
├── app.asar.unpacked
├── appsrc
├── assets
├── conf.default.json
├── Docs
├── html
├── lib.asar
├── locales
├── node_modules
├── node_modules.asar
├── package.json
├── page-dist
├── style
├── updater
└── window.html
```
and I can launch typora  to open some file or directory by this command.
```bash
electron /usr/lib/typora/app.asar some_dir_or_file
```

When I launch it without opening anything by 
```bash
electron /usr/lib/typora/app.asar
```
it pops up an error
![image](https://user-images.githubusercontent.com/31362108/194758380-d2540f3f-716d-4bbd-be76-1f5b7ef464b3.png)

It seems  `/usr/lib/typora/app.asar` are parsed as the argument to be opened.

## suggested solution
Strip the first argument when it is `electron`

## log
I also launched typora directly, and noticed something different from the log in `~/.config/Typora/`

key log when launching typora directly (no problem)
```
INFO 2022/10/8 23:49:35  launch with argv [/tmp/makepkg/typora/src/usr/share/typora/Typora]
```
key log when launched by electron to open a file (works just fine)
```
INFO 2022/10/8 23:58:07  launch with argv [/usr/lib/electron/electron, /usr/lib/typora/app.asar, /tmp/makepkg/typora/src/usr/share/ElectronInjector/README.MD]
```
key log when launched by electron without opening  any file (error pops up)
```
INFO 10/9/2022, 9:04:43 PM  launch with argv [/usr/lib/electron/electron, /usr/lib/typora/app.asar]
```

## More info

I found a quick hack that works fine
```bash
electron /usr/lib/typora/app.asar "" "$@"
```
the corresponding log is (there is an extra `,` at the end)
```
INFO 2022/10/9 21:26:05  launch with argv [/usr/lib/electron/electron, /usr/lib/typora/app.asar, ]
```
No error and I can also append other arguments behind it.

So it does not matter if you don't want to fix this.

**Comment by abnerlee** [comment]
fixed in v1.5.x
