### ISSUE TITLE
Not using default browser

### ISSUE THREAD

**Issue by JakeSays** [typora/typora-issues#5464]
Just purchased Typora and it does not use the default browser to open links.

OS: Ubuntu 22.04.

My default browser is chrome but Typora opens links in firefox. Very frustrating!

I had been using Typora 0.9.86-1 which did use the default browser.

**Comment by abnerlee** [comment]
Do you use the deb or binary version of Typora?

**Comment by JakeSays** [comment]
Binary version.

**Comment by JakeSays** [comment]
I think the issue is with ubuntu and not typora. I am finding other apps that are not using the default after I upgraded ubuntu.

**Comment by abnerlee** [comment]
Could you try `xdg-open https://typora.io` and see which browser popup? It works if your ubuntu configurations are correct

see https://askubuntu.com/questions/15354/how-to-open-file-with-default-application-from-command-line

**Comment by JakeSays** [comment]
@abnerlee `xdg-open https://typora.io` brings up firefox so it's definitely system related. Thanks for your help!
