### ISSUE TITLE
[Feature] Shortcut to jump to next word while skipping links and picture markdowns

### ISSUE THREAD

**Issue by michaelscodingspot** [typora/typora-issues#5465]
It's great to be able to use Ctrl + arrow keys to jump to next/previous word in the editor (that's the shortcut in Windows). But when there's a link or an image markdown, the caret starts navigating within the link. It will be great to solve this somehow. It might be a new shortcut to jump to the start/end of a link. Or maybe a small timed throttle when using Ctrl + arrows so that when I click Ctrl +right arrow to go to next word, it won't expand the link markdown in the first second or something.

**Comment by abnerlee** [comment]
I think ctrl+arrow won't escape urls in other apps, like NotePad.exe as well,

So we currently do not have plans to add one more option to control ctrl+arrow key unless required by more users

**Comment by michaelscodingspot** [comment]
I think comparing Typora to Notepad is relevant in the source code view mode. But in the "backend" view mode I would expect Ctrl+[left/right] to jump over links.

**Comment by michaelscodingspot** [comment]
This is still extremely annoying. Please allow Ctrl + [right/left] arrow to jump over links in front-end view mode.
