### ISSUE TITLE
[Feature] Export with latex converted to SVG

### ISSUE THREAD

**Issue by WZ-Tong** [typora/typora-issues#5466]
Some Latex pattern (such as \rm \text) cannot convert to word by pandoc, so if there is an option that "before converting to word using pandoc, convert latex into svg by typora first", will help

**Comment by abnerlee** [comment]
You should use `$\mathrm{test}$` since the `\rm` command has been deprecated.

see https://tex.stackexchange.com/a/531017

**Comment by WZ-Tong** [comment]
Thanks, so if you can give us a checkbox to disable mathjax's build-in macros ? (after first rendering finished, even if I clear all macro settings using dev pannel, I can still use them)
(What's more, seems \begin{cases} cannot be converted to  word by pandoc either, so there's still a need for 'convert math to svg before converting to word using pandoc')
