### ISSUE TITLE
Too few, or too many line breaks when pasting from other apps

### ISSUE THREAD

**Issue by jfrankl** [typora/typora-issues#5467]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I copy and paste text from Google Docs into Typora, line breaks between lines are removed. When I copy and paste text from Microsoft Word, an extra line break is added.

**To Reproduce**
1. Open a Google Doc or Microsoft Word on Mac
2. Type three paragraphs separated by a blank line (see screenshots below)
3. Copy and paste text into Typora

**Expected behavior**
I would expect the 1 blank line to be preserved when pasted into Typora, but instead either 0 or 2 blank lines are pasted.

**Screenshots / Screencasts**

Google Docs:
<img width="819" alt="Screen Shot 2022-10-11 at 3 30 43 PM" src="https://user-images.githubusercontent.com/1809908/195184302-db7e4ca5-a188-4308-8955-85020c57812f.png">
<img width="971" alt="Screen Shot 2022-10-11 at 3 30 19 PM" src="https://user-images.githubusercontent.com/1809908/195184305-3eaad406-66ba-4b2c-b6b7-92ef4f3f0d10.png">

Microsoft Word:
<img width="913" alt="Screen Shot 2022-10-11 at 3 37 40 PM" src="https://user-images.githubusercontent.com/1809908/195184631-8b3682ce-aa61-4f80-aba7-80e1a3ea1597.png">
<img width="962" alt="Screen Shot 2022-10-11 at 3 45 48 PM" src="https://user-images.githubusercontent.com/1809908/195184604-1f63925f-ae48-4be8-acc0-a61c690c8668.png">

What I'd expect to see in both cases:
<img width="963" alt="Screen Shot 2022-10-11 at 3 46 46 PM" src="https://user-images.githubusercontent.com/1809908/195184756-1bf7cab4-ff7b-433e-a2d6-d2558bcd9d68.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 12.5.1 (21G83)
 - Hardware: M1 MacBook Pro

**Typora Version**
Version 1.4.4 (6547)

**Additional context**
I love the app! ❤️

**Comment by abnerlee** [comment]
Could you share your Google Doc link and Word file? Which browser do you use?

In my test, paste into Typora does not produce those empty lines.

**Comment by jfrankl** [comment]
@abnerlee yes, here are the requested files:

- Google Docs: https://docs.google.com/document/d/1ppPCy18mnUjYYQoQSWLY2anq2IiXNXEdSRvRt_HMtCo
- Microsoft Word: [Typora test on Github.docx](https://github.com/typora/typora-issues/files/10031521/Typora.test.on.Github.docx)

Each file includes a screenshot of what I see when I paste it into Typora on a Mac. Pasting from Google Docs, the line break is removed. Pasting from Microsoft Word, an extra line break is added.

**Comment by abnerlee** [comment]
We will improve the paste from Google Doc.

For the Word issue, Word generates `<p>line1</p><p></p><p>line 2</p>` in clipboard, so there will be empty paragraphs. You can copy content from Word to another Word document with a Theme, and also see the empty paragraphs.

**Comment by abnerlee** [comment]
improved in v1.5.x for Google Doc
