### ISSUE TITLE
Typora on winget

### ISSUE THREAD

**Issue by mauromotion** [typora/typora-issues#5475]
Could you remove Typora from winget if you don't plan on maintaining it correctly after every new release? I had reinstalled Typora 1.4.8 about 10 times now, that is anytime that I want to upgrade my other programs with winget because for some reason winget can't tell that Typora is actually at version 1.4.8 but it is stuck at thinking it is 1.4.7.
It happen before as well, with previous releases.

Thanks.

**Comment by sommarlov** [comment]
I have the same issue, Windows also shows version 1.4.7 in "Add or remove programs", Windows 11.

**Comment by abnerlee** [comment]
The winget is maintained by community, currently we do not have plans to maintain winget

**Comment by mauromotion** [comment]
If so, at least they should update the software version number on their exe package at least. This is just lazy.

**Comment by SpecterShell** [comment]
Related to #5493

**Comment by abnerlee** [comment]
put into #5493
