### ISSUE TITLE
[Feature] Auto generate picture name[Very necessary]

### ISSUE THREAD

**Issue by nil-one** [typora/typora-issues#5476]
![image](https://user-images.githubusercontent.com/47878132/196044680-5d9236a3-be10-404a-a961-f81fa626bbcd.png)

Imagine that: 
1. I copied a picture named "1.png" from A website(I don't know what it named by the website), then I paste the pic. to my doc
2. I copied a picture named "1.png" from B website(I don't know what it named by the website) , then I paste the pic. to my doc
opps, the second pic. would override the first pic! My doc. got two same pic, that not my expected!

**so, maybe add a auto-generate pic feature is great! like: `${rawname}202210162354${random}`**

I need it, I have experienced many disasters, Please~

**Comment by abnerlee** [comment]
may relates #2612

But anyway it should not overwrite existing image.

What is your Typora version, btw?

**Comment by abnerlee** [comment]
In my test it will not overwrite existing images, so could you provide a screencast of your operation?
