### ISSUE TITLE
./ was added before absolute path

### ISSUE THREAD

**Issue by irinify** [typora/typora-issues#5479]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I active setting: When Insert Upload image & Use relative path if possible & Add ./ for relative path
![image](https://user-images.githubusercontent.com/15665834/196648301-517c64aa-c050-4d11-a885-9d79c1fd945b.png)
Then I paste image, the temporary path was added with "./" and it does not work! See the absolute path start with C: was add with "./"
![image](https://user-images.githubusercontent.com/15665834/196648755-905ec1dd-2047-46b4-bb69-402c81d553a8.png)
If I deactive Add ./ for relative path, it works.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
v1.4.4

**Additional context**
I am your supporter, my typora is activated.

**Comment by irinify** [comment]
refer: https://github.com/typora/typora-issues/issues/4512

**Comment by FrankSFLYS** [comment]
Same issue, especially when I want to configure upload options by yaml front matter, this issue makes uploading fail. 
![image](https://user-images.githubusercontent.com/10843159/202662142-004b6d92-d61d-47e8-bd25-b46f19e9d325.png)
I want local notes copy image to folder, while public notes upload images by adding `typora-copy-images-to: upload` to front matter. It does upload, but copying image firstly to a typora temp folder, then upload. But enabling relative path makes local image path strange:
![image](https://user-images.githubusercontent.com/10843159/202662700-84349962-3ceb-4e37-88ea-a54e370755ea.png)
It just appends the paths and upload will fail.

**Comment by abnerlee** [comment]
Currently, `C:\\` is considered as absolute path on Windows, while `C:/` is not, we will change the spec in next version up.

**Comment by abnerlee** [comment]
fixed in v1.5.x
