### ISSUE TITLE
Content is missing

### ISSUE THREAD

**Issue by likfe** [typora/typora-issues#548]
Today I use Typora as usual. I find that the outline did not display some `H2`, I do not know why,I am busy with the current job so I just restart Typora,Then I find I lost some content,Only the title is still there.

I do not know why,but I hope that you should consider adding version control to prevent content loss.

I will try to find the real reason of lost content and now I must write the content I lost first with sad mood.

**Comment by abnerlee** [comment]
We have fixed a related bug which could cause data lost.

For version control, please refer to http://support.typora.io/Version-Control/
