### ISSUE TITLE
The exported PDF document has wrong line spacing when using pixyll.css

### ISSUE THREAD

**Issue by Konjac-XZ** [typora/typora-issues#5480]
**Describe the bug**
When I exported my Markdown document to the PDF, the ordered lists in documents have particularly small line spacing and look cluttered. After I switched to github.css, the problem disappeared.

**To Reproduce**
1. Switch the theme to Pixyll.
2. File - Export - PDF

**Expected behavior**
The ordered list should have a loose, appropriate line spacing, just like in the editor.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/71483384/196891498-97c6517b-9da6-4bfb-8cc6-94fd271c34cc.png)

![image](https://user-images.githubusercontent.com/71483384/196891235-800bd4c2-21fa-4481-bf56-c365c4e88564.png)

**Sample Markdown File**
[Markdown File - Computer Network.md](https://github.com/typora/typora-issues/files/9827661/Markdown.File.-.Computer.Network.md)
[PDF File - With Origin Pixyll.css .pdf](https://github.com/typora/typora-issues/files/9827674/PDF.File.-.With.Origin.Pixyll.css.pdf)

**Desktop (please complete the following information):**
 - OS: Windows 11 Educational 22H2

**Typora Version**
1.4.8

**Comment by Konjac-XZ** [comment]
As my Microsoft Print To PDF that comes with my system cannot work, I tried Adobe Acrobat Pro to provide a virtual printer Adobe PDF. The results are the same, and it can be seen that the problem should arise in the process of paging the document.

**Comment by Konjac-XZ** [comment]
So is there any progress?

**Comment by abnerlee** [comment]
fixed in v1.5.x
