### ISSUE TITLE
[Feature] Change default heading by removing spaces

### ISSUE THREAD

**Issue by jeff9315** [typora/typora-issues#5481]
Currently if I have an H1 heading as my fist line such as **My Heading In Typora**, then that's used as the default filename -- with spaces. However, other Markdown editors may not be able to link to files with spaces in their names.

So, my proposal is that there is an option to default the filename to be either:
1. Change spaces to dashes
2. Change spaces to underscores
3. Capitalize each word and remove spaces

And, just so you know ... I **LOVE** Typora.

**Comment by abnerlee** [comment]
You can set the filename by yourself. 
About the default one, maybe duplicated with #5398
