### ISSUE TITLE
Math become blurry / Math display with glitch

### ISSUE THREAD

**Issue by WonderLandxD** [typora/typora-issues#5482]
When using the macOS Monterey, the Math block / inline math shows up perfectly. After pushing macOS Ventura today, the display became very blurry. But after exporting to pdf, the formula in pdf is displayed normally. I also tried rebooting the computer and changing the version, but it didn't work. Guessing it's probably due to system adaptation.

**Desktop:**
OS: macOS Ventura

**Typora Version:**
Stable Releases: 1.4.4 and 1.3.7
Dev Releases: 1.4.1
[Test for Math.md](https://github.com/typora/typora-issues/files/9859432/Test.for.Math.md)

<img width="956" alt="test" src="https://user-images.githubusercontent.com/100405945/197749490-08f45280-a46a-4033-845c-d2c8114abe64.png">

_Originally posted by @WonderLandxD in https://github.com/typora/typora-issues/issues/5441#issuecomment-1290326577_

**Comment by otzslayer** [comment]
Same issue here :(

**Comment by abnerlee** [comment]
duplicated with #5441
