### ISSUE TITLE
Export to "PDF (Latex / pandoc)" fails

### ISSUE THREAD

**Issue by charraeus** [typora/typora-issues#5483]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----
**Issue**
Exporting the attached markdown document results in an error:
`pandoc: pdflatex: createProcess:
posix_spawnp: illegal operation (Inappropriate
ioctl for device)`
For the settings used, please see the attached screenshots below.

**To Reproduce**
1. delete the *base.user.css*-file
2. set the settings I use
3. load the attached file *Markdown-Test-2.md*
4. File / Export ... / PDF (Latex / Pandoc)
5. See error message

**Expected behavior**
* No error messag
* and a pdf document should have been generated

**Screenshots / Screencasts**
* error-message.png <img width="299" alt="error-message" src="https://user-images.githubusercontent.com/38609969/197779950-57cd2a0b-5b8b-4b18-996e-1ba1822da712.png">
* export-settings.png <img width="832" alt="export-settings" src="https://user-images.githubusercontent.com/38609969/197779987-f244c006-e1a5-4c74-a3dc-4c87687a235f.png">
* export-settings-2.png <img width="832" alt="export-settings-2" src="https://user-images.githubusercontent.com/38609969/197782028-0cedf80d-e84c-4348-9696-a827c6fce8b7.png">

**Sample Markdown File**
[Markdown-Test-2.md](https://github.com/typora/typora-issues/files/9860468/Markdown-Test-2.md)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1
 - pandoc: 2.19.2
 - pdflatex:  
   ```
   christian % which pdflatex
   /Library/TeX/texbin/pdflatex
   christian % pdflatex
   This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
   restricted \write18 enabled.
   **^C
   christian % 
   ```

**Typora Version**
1.4.4

**Additional context**
I tried pandoc on the command line with the following results: 
```
christian % pandoc -f markdown -s -o /Users/christian/Desktop/Markdown-Test-2.pdf Markdown-Test-2.md
christian % 
```
--> works.

```
christian % pandoc -f native -s -o /Users/christian/Desktop/Markdown-Test-2.pdf Markdown-Test-2.md
couldn't read native
christian % 
```  
--> error message "couldn't read native" and and no pdf generated

And yes, I know, currently Typora does not support the grid table markdown extension.

**Comment by abnerlee** [comment]
Please set full path of pdf engine (see https://github.com/jgm/pandoc/issues/7570)
