### ISSUE TITLE
Export to "PDF (Latex / pandoc)" fails - undefined control sequence when "highlight" is enabled

### ISSUE THREAD

**Issue by charraeus** [typora/typora-issues#5484]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----
**Issue**
When *Preferences / Markdown / Syntax Support / Highlight* is **enabled**, exporting the attached markdown document results in an error:
`Error producing PDF.
! Undefined control sequence.
1.139 +: hl`
When *Preferences / Markdown / Syntax Support / Highlight* is **disabled**, everything works fine.
For the other settings used, please see the attached screenshots below.

**To Reproduce**
1. delete the *base.user.css*-file
2. set the settings I use
3. make sure that *Preferences / Markdown / Syntax Support / Highlight* is **enabled**
4. load the attached file *Markdown-Test-2.md*
5. File / Export ... / PDF (Latex / Pandoc)
6. See error message

**Expected behavior**
* No error message
* and a pdf document should have been generated

**Screenshots / Screencasts**
* error-undef-control-seq.png 
<img width="298" alt="error-undef-control-seq" src="https://user-images.githubusercontent.com/38609969/197988226-1bbf0498-a06b-4707-a357-1884c4bd572f.png">
* settings-md.png <img width="832" alt="settings-md" src="https://user-images.githubusercontent.com/38609969/197992483-ddc978fa-1458-454b-9d9c-1712da60f757.png">
* export-settings.png <img width="832" alt="export-settings" src="https://user-images.githubusercontent.com/38609969/197988663-801a166d-f09e-4b5b-b97c-eb11eed6ce88.png">
* export-settings-2.png <img width="832" alt="export-settings-2" src="https://user-images.githubusercontent.com/38609969/197782028-0cedf80d-e84c-4348-9696-a827c6fce8b7.png">

**Sample Markdown File**
[Markdown-Test-2.md](https://github.com/typora/typora-issues/files/9860468/Markdown-Test-2.md)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1
 - pandoc: 2.19.2
 - pdflatex:  
   ```
   christian % which pdflatex
   /Library/TeX/texbin/pdflatex
   christian % pdflatex
   This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
   restricted \write18 enabled.
   **^C
   christian % 
   ```

**Typora Version**
1.4.4

**Additional context**
I tried pandoc on the command line with the following results: 
```
christian % pandoc -f markdown -s -o /Users/christian/Desktop/Markdown-Test-2.pdf Markdown-Test-2.md
christian % 
```
--> works.

**Comment by abnerlee** [comment]
fixed in v1.5.x
