### ISSUE TITLE
Rendering LaTeX formulas as jagged

### ISSUE THREAD

**Issue by zhuozhiyongde** [typora/typora-issues#5485]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
LaTeX formulas is rendered as below:
![CleanShot 2022-10-28 at 13 32 53](https://user-images.githubusercontent.com/36695271/198510473-eebfc745-aa41-4527-ad63-de09aa551189.png)

**To Reproduce**
Just type the LaTeX formulas in macOS Ventura.

**Expected behavior**
LaTeX formulas can be rendered correctly.

**Screenshots / Screencasts**
As above.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
```
### t分布

从正态总体$N(\mu,\sigma^2)$抽得的样本均数也服从正态分布$N(\mu,、\frac{\sigma^2}{n})$。

对正态变量 $\bar{X}$ 做变换 $\frac{\bar{X}-\mu}{\sigma_\bar{X}}$ ，有 $\frac{\bar{X}-\mu}{\sigma_\bar{X}}\sim{N(0,1)}$

因为 $\sigma_\bar{x}$ 未知，便宜 $S$代替 $\sigma$ ，即以 $S_\bar{x}$代替 $\sigma_\bar{x}$ ，则 $t=\frac{\bar{X}-\mu}{S_\bar{X}},v=n-1$ 服从自由度为 $n-1$ 的t分布

标准正态分布是t分布的特例（自由度趋于无穷）
```

**Typora Version**
1.4.3

**Additional context**
None.

**Comment by zhuozhiyongde** [comment]
However, it can be export into pdf and rendered correctly.

**Comment by abnerlee** [comment]
duplicated with #5441
