### ISSUE TITLE
Image URL auto transformation cant be turned off and image cant be showed

### ISSUE THREAD

**Issue by beet233** [typora/typora-issues#5487]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I use PicGo to upload my image, and paste its url to typora, I got something like this:
`![image-20221028205043932](https%3A%2F%2Fbeetpic.oss-cn-hangzhou.aliyuncs.com%2Fimg%2Fimage-20221028205043932.png)`
This image url can't be recognized by typora (even with default Github theme). And I'm sure I have turned the url auto transformation option off in the `Preference`.

With this format, it works: 
`![](https://beetpic.oss-cn-hangzhou.aliyuncs.com/img/image-20221028205355528.png)`

**To Reproduce**
1. Get a screenshot in clipboard
2. Paste it in typora (with PicGo)
3. See error

Maybe need to turn the url auto transformation option on and then off ?

**Expected behavior**
I think typora should support to recognize transformed url, and the option should work.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

![](https://beetpic.oss-cn-hangzhou.aliyuncs.com/img/image-20221028205817882.png)

![](https://beetpic.oss-cn-hangzhou.aliyuncs.com/img/image-20221028210012033.png)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Windows 10(x64)

**Typora Version**
1.4.8

**Additional context**

**Comment by abnerlee** [comment]
Could you try click 验证图片上传选项 ？Or check PixGo's log and see if it uses https:// or https%3A%2F%2F ?

**Comment by beet233** [comment]
Sorry, I find it out that it is PicGo's bug, and my PicGo is a beta version. When I switch to formal verison, it works.
