### ISSUE TITLE
Latex problem 

### ISSUE THREAD

**Issue by Xueshen-2000** [typora/typora-issues#5488]
Although I have enabled the inline math feature in the Preference, still inline math feature isn't working at all. 
Whenever I press $, it doesn't generate $ $, it's just dollar sign, I tried to close the file, and try again by disabling the inline math feature and then again enabling, but it's not still working. There is no problem with math blocks though, they are working fine.
Please help me on this. Thank you.

**Comment by abnerlee** [comment]
That option requires restart Typora to apply.

**Comment by Xueshen-2000** [comment]
> That option requires restart Typora to apply.

Could you please tell me what do you mean by restart? I have closed the typora files and opened them again, but it's still not happening. I even shut down my computer system, but it's still not working.
