### ISSUE TITLE
Can't Use Graphviz graphs in direct way 

### ISSUE THREAD

**Issue by MaxwellSnake** [typora/typora-issues#549]
Hello! I have got a problem when using [Gravizo](http://www.gravizo.com/) on Typora.
>You can use Gravizo to describe graphs with Markdown syntax including a image tag and then the url content include DOT, PlantUML or UMLGraph syntax. 

In direct way, you can keep it readable like:
```
![Alt text](https://g.gravizo.com/g?
 digraph G {
   main -> parse -> execute;
   main -> init;
   main -> cleanup;
   execute -> make_string;
   execute -> printf
   init -> make_string;
   main -> printf;
   execute -> compare;
 }
)
```
It can be perfectly supported by MacDown(see the picture behind) and GitHub([see here](https://github.com/TLmaK0/gravizo)). 
<img width="1136" alt="2017-02-23 11 23 27" src="https://cloud.githubusercontent.com/assets/20240523/23265314/3e6bb742-fa1f-11e6-81b2-e113b27e2973.png">
However, Typora phrases that wrongly.
![2017-02-23 11 23 52](https://cloud.githubusercontent.com/assets/20240523/23265340/48629b3a-fa1f-11e6-85a1-722a2a3d1c61.png)
I hope it can be fixed early. Thank you! :)
>Typora Version: 0.9.9.9.0 
System: macOS 10.12 (16A323)

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/290
