### ISSUE TITLE
> That option requires restart Typora to apply.

### ISSUE THREAD

**Issue by Xueshen-2000** [typora/typora-issues#5491]
@Xueshen-2000 > Although I have enabled the inline math feature in the Preference, still inline math feature isn't working at all. Whenever I press $, it doesn't generate $ $, it's just dollar sign, I tried to close the file, and try again by disabling the inline math feature and then again enabling, but it's not still working. There is no problem with math blocks though, they are working fine. Please help me on this. Thank you.

@abnerlee > That option requires restart Typora to apply.

Could you please tell me what do you mean by restart? I have closed the typora files and opened them again, but it's still not working. I even shut down and restarted my computer system, but it's still not working.

_Originally posted by @Xueshen-2000 in https://github.com/typora/typora-issues/issues/5488#issuecomment-1295762907_

**Comment by abnerlee** [comment]
Exit Typora and launch Typora again

**Comment by Xueshen-2000** [comment]
Even upon exiting and opening typora again, it's not resolving the issue.

**Comment by abnerlee** [comment]
> Whenever I press $, it doesn't generate $ $

This requires "Auto pair Markdown Syntax" enabled in Preferences Panel → Edit
