### ISSUE TITLE
The Windows installer of Typora 1.4.8 writes incorrect version to the registry

### ISSUE THREAD

**Issue by SpecterShell** [typora/typora-issues#5493]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

While the installer can install Typora 1.4.8 properly, it writes incorrect version 1.4.7 to the registry. The `ProductVersion` property from the installer itself is also incorrect.
This may be caused by the `AppVersion` property in the Inno Setup script not being changed properly.

![image](https://user-images.githubusercontent.com/56779163/198961086-a72287f3-b4bd-4088-b654-742980f17c5b.png)
![image](https://user-images.githubusercontent.com/56779163/198962931-ea044db8-844b-4ffa-8d67-c9610bbe8ea6.png)

**Comment by abnerlee** [comment]
We have updated installer located in https://typora.io/windows/typora-setup-x64.exe, https://download.typora.io/windows/typora-setup-x64.exe and https://download.typora.io/windows/typora-setup-x64-1.4.8.exe
