### ISSUE TITLE
[Feature] Increase/Decrease all heading levels in a section

### ISSUE THREAD

**Issue by mhenry1384** [typora/typora-issues#5495]
I not-infrequently copy and paste a selection of markdown into another markdown document, or somehow otherwise end up with a big chunk of markdown that has the wrong header levels vs the rest of the document.

Feature suggestion: If you select a block of text with more than one header you should be able to choose "Increase Heading Level" or "Decrease Heading Level" and it will increase/decrease all the headers withing that selected block of text by one level.

**Comment by abnerlee** [comment]
duplicated with #2375
