### ISSUE TITLE
Request to add window topping function

### ISSUE THREAD

**Issue by zhuozhiyongde** [typora/typora-issues#5496]
I often take notes when watching videos. Because my screen is too small, I often need to switch windows back and forth. If you can add a function to keep the window on top, I think it will greatly improve my experience.

**Comment by abnerlee** [comment]
"View" -> "Always on Top" from menu bar

**Comment by zhuozhiyongde** [comment]
Oh, it's embarrassing that I didn't see that in advance. By the way, I noticed that this feature does not provide shortcuts. Does Typora have any plans to provide custom shortcuts in the future?.

**Comment by abnerlee** [comment]
https://support.typora.io/Shortcut-Keys/#change-shortcut-keys
