### ISSUE TITLE
no colourful emoji in exported PDF

### ISSUE THREAD

**Issue by GitHubbdream** [typora/typora-issues#5498]
- [x] Searched existing issues to avoid creating duplicates.
I already found issues with same context. As they are all very old and I could not get it solved I start again here.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.
I run standard installation without custom css

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I started with documentation in Typora using Emoji as :+1: and others.
In Typora itself and HTML-export all looks fine but PDF-export only have black Emoji
I already used all available Themes for PDF export. Same result

**Expected behavior**
Goal is coloured Emoji in PDF-export.

**Screenshots / Screencasts**
Typora:
![grafik](https://user-images.githubusercontent.com/35231230/199956879-9389febe-c3d8-4970-baca-5c295ad140d5.png)

PDF:
![grafik](https://user-images.githubusercontent.com/35231230/199957131-8a238e08-69d0-4886-b980-5fe10a64e093.png)

HTML:
![grafik](https://user-images.githubusercontent.com/35231230/199957417-fe9435e7-9b3e-46bd-a616-881f5d8b46f4.png)

**Sample Markdown File**
[example.md](https://github.com/typora/typora-issues/files/9937619/example.md)

[example.pdf](https://github.com/typora/typora-issues/files/9937622/example.pdf)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS

**Typora Version**
Typora for Linux (x64 SNAP) version 1.4.8

**Additional context**
n/a

**Comment by abnerlee** [comment]
<img width="1651" alt="Screenshot 2022-11-16 at 16 47 06" src="https://user-images.githubusercontent.com/1621242/202132294-2d33b409-e824-41fb-9d3b-8c957ea6db25.png">

Try another PDF reader?

**Comment by damienalexandre** [comment]
PDF reader in browsers are clever and they display the color version.Document Viewer on Linux does not.

So **what I do to fix the PDF exported by Typora** (because clearly they lack something), is opening the PDF in Firefox, and "Printing to PDF". It saves a perfectly fine PDF with color emoji in all readers (and somehow, it's even smaller in size!).
