### ISSUE TITLE
Quotation blocks getting destroyed

### ISSUE THREAD

**Issue by DanBennettUK** [typora/typora-issues#55]
An interesting issue I just spotted - quotation blocks are being destroyed. (Windows 10 x64)

Instead of it showing the full quote, between lines it's showing the quote syntax (>) on the new line instead. Then the rest of the quote carries on after it with no issue.

This lonely syntax has no space around it - which is perhaps the issue? I have a feeling it happened after I opened the file in Notepad to fix another issue.

Source as it's shown in Notepad++

```
>   Your PHP session.entropy_length setting is too small. Set it to at least 16 in your php.ini to ensure that generated session IDs are random and unpredictable enough.

>

>   Your server has the php open_basedir restriction enabled. Some requests for external sites may fail to complete. This could stop certain feeds from updating among other things.

>

>   No sitewide password salt has been set. Edit your config.php and set the "passwordsaltmain" parameter to a reasonable secret phrase.

```

The  > between texts should be a new line, but instead all three paragraphs are appearing separate, with the > separating.

**Comment by abnerlee** [comment]
Hi @DanBennettUK,

What is the original markdown source ?

**Comment by DanBennettUK** [comment]
Do you mean the text being quoted? It's plain text. I always paste in plain text else Typora removes all the spacing (that should be another issue, shouldn't it?)

**Comment by abnerlee** [comment]
@DanBennettUK does this bug still exists now?

**Comment by DanBennettUK** [comment]
I'm unable to replicate this in the latest version in a new file (unable to test in my usual file due to performance). Can close I think :-)
