### ISSUE TITLE
Footnote always shows at the end of file when exported to PDF

### ISSUE THREAD

**Issue by xiaotianxt** [typora/typora-issues#5502]
I've been using typora for a long time, and recently I noticed that when I export to PDF file, the footnotes always show at the end of file, but usually it should be printed at the bottom of the page it references, is is an intended change or a bug?

**Comment by abnerlee** [comment]
The default export does not support adding footnotes in each page. For more advanced export layout, you can use Pandoc/LaTeX export (https://support.typora.io/Export/#pdf-latex--pandoc)
