### ISSUE TITLE
Recent folder list, need method to remove legacy folder

### ISSUE THREAD

**Issue by coinzdude** [typora/typora-issues#5503]
In my recent folders history list, I have a duplicate named folder which I cannot find a method to remove.  If there's a data file I can access, I am happy to remove this manually, otherwise, I would like a UI to remove individual folder paths from history.

In the below, the two same named "productManual" folders are different locations, one is no longer valid, but I cannot remove from this list, so each time, I need to hover each to find the correct one.

![image](https://user-images.githubusercontent.com/58857646/200895293-97437026-5666-4d11-9847-46f2dc5925b5.png)

**Comment by abnerlee** [comment]
fixed in 1.7.5
