### ISSUE TITLE
\div mathematical formula rendering error

### ISSUE THREAD

**Issue by Anduin9527** [typora/typora-issues#5506]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
There is a problem with the rendering of the mathematical formula, the division \div becomes \nabla \cdot

**Expected behavior**
want correct \div performance

**Screenshots / Screencasts**
![图片](https://user-images.githubusercontent.com/71650486/201956244-08d19330-c3d4-441d-8706-d107c0073fff.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
e.g: 1.4.8

**Comment by abnerlee** [comment]
Please disable physics package in preferences panel.

Duplicated with #4715
