### ISSUE TITLE
What is the format for Target File Extensions in custom export dialog

### ISSUE THREAD

**Issue by googol4u** [typora/typora-issues#5507]
What is the format for Target File Extensions in custom export dialog? I directly input the extension and seems not working.  I try something like "Word(\*.docx)|\*.docx" and it is not working either.  So what is the exact format for this setting?

![QQ截图20221117145057](https://user-images.githubusercontent.com/992409/202377599-a9b6caab-46a5-4455-9fb5-535391f9987e.png)

**Comment by abnerlee** [comment]
should be fixed in 1.5.x
