### ISSUE TITLE
How to disable auto format/indent in script block?

### ISSUE THREAD

**Issue by LazyKnightX** [typora/typora-issues#5508]
**Problem:**
![image](https://user-images.githubusercontent.com/13707739/202619554-a1936a5d-7c52-4617-b28d-548e8387fc0f.png)

**Wanted:**
```lua
u:listen('event-foo-bar', function(a, b)
    if a > b then
        print('a')
    else
        print('b')
        b:listen('event2', function()
        end)
    end
end)
```

I want to disable the auto formatting feature when I press <kbd>shift+tab</kbd>.

I want to indent/unindent scripts by myself, but I don't know how.

Thank you in advance!

**Comment by abnerlee** [comment]
fixed in v1.5.x
