### ISSUE TITLE
Windows: Change to default file type as MD

### ISSUE THREAD

**Issue by Consumered** [typora/typora-issues#551]
Suggestion to set the Windows file Save As dialog to default to "Markdown (*.md)"

While Typora already defaults the saved file name to "Unknown.md", changing this without explicitly adding the extension will save it without the extension. To save some confusion and add some convenience, it would be great to have it automatically default to add ".md" as is expected from word processors (and will use the one the user provides if explicitly provided).

0.9.23 Windows

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/367
