### ISSUE TITLE
Multiline HTML comments show as normal text

### ISSUE THREAD

**Issue by davestewart** [typora/typora-issues#5511]
**Describe the bug**

If I use multiline HTML comments, they show on the page, rather than being hidden or dimmed:

Shows in a special state:

```
<!-- this is a comment -->
```

Shows as regular text:

```
<!--
this is line 1
this is line 2
-->
```

**Expected behavior**
Multiline comments should also show in the special state

**Screenshots / Screencasts**

![image](https://user-images.githubusercontent.com/132681/203114250-cdba9865-f0b6-4160-90e0-7c048233985d.png)

**Desktop (please complete the following information):**
 - OS: OSX 12.6

**Typora Version**
e.g: 1.4.8

**Comment by xiaotianxt** [comment]
If you open Source Code Mode, you will notice that there's an additional line breaks between your text. If you delete the empty line between your comments, multiline comments will work.

<img width="200" src="https://user-images.githubusercontent.com/17041194/203375096-ed42d6a5-39b0-4f63-8043-aa6f2cde785f.png">

<img width="156" alt="CleanShot 2022-11-23 at 00 58 52@2x" src="https://user-images.githubusercontent.com/17041194/203375421-65ed001c-74fb-42cb-a0ec-dc7cc4fa0016.png">

<img width="152" alt="CleanShot 2022-11-23 at 00 59 03@2x" src="https://user-images.githubusercontent.com/17041194/203375464-611fce8e-b674-421c-9ee0-4621dd2e8194.png">

**Comment by davestewart** [comment]
Ah, OK.

But it seems that there can be no empty lines:

```
<!--
this is line 1

this is line 2
-->
```

<img width="115" alt="image" src="https://user-images.githubusercontent.com/132681/203612619-c6f7306b-99a0-4a35-958d-0746d69d70cd.png">

If we want to comment out sections of a markdown document, say a section is WIP, then we have no way to do that.

It works in GitHub:

![image](https://user-images.githubusercontent.com/132681/203613012-df07083f-fec3-4344-a015-21c2e721d30d.png)

![image](https://user-images.githubusercontent.com/132681/203613056-6b767a5d-1272-4c85-9952-1ceec19f2f93.png)

It's just how to prevent something from rendering...
