### ISSUE TITLE
Add command line args "-h","--help", and "--create"

### ISSUE THREAD

**Issue by aberezin** [typora/typora-issues#5512]
If, at the command line, I type this
  typora my-non-existant-file-I-want-to-create.md

Typora launches with a hidden dialog asking me if I want to create the file.  Much nicer would be this
    typora --create my-non-existant-file-I-want-to-create.md

wherein it doesnt ask.
Also, add -h and --help flags for general consistency with command line apps.

**Comment by abnerlee** [comment]
duplicated with #1999
