### ISSUE TITLE
Initial path of save file dialog messed up when export with custom config 

### ISSUE THREAD

**Issue by xiaotianxt** [typora/typora-issues#5515]
**Describe the bug**

When exporting a file using custom export option **more than once**, the initial path of Save File Dialog changed to root path '/' instead of the file folder path.

**To Reproduce**

1. Open preference, add a custom export command like: `/usr/bin/pandoc ${currentPath} -o ${outputPath}`, I will call this option `Custom`.
2. On `Show Save File Dialog` select `Select file path to save` option.
3. Open a file, click `File > Export > Custom` and export the file. Notice the initial path of the Save File Dialog is in current file path.
4. Now click `File > Export > Custom` again. Notice the initial path of the Save File Dialog changed to the root path.

**Expected behavior**

For other export options like PDF or Word, the Save File Dialog always have initial path pointing to current file path, a custom export option should have the same behavior.

**Screenshots / Screencasts**

First time clicking `File > Export > Custom`

<img width="1002" alt="CleanShot 2022-11-23 at 00 49 43@2x" src="https://user-images.githubusercontent.com/17041194/203373331-159b6498-f59f-4716-a4df-0a19f0088301.png">

Second time clicking `File > Export > Custom`

<img width="1002" alt="CleanShot 2022-11-23 at 00 50 41@2x" src="https://user-images.githubusercontent.com/17041194/203373550-6a8541cc-ed97-4817-8aa7-c27b6bb82d8d.png">

**Sample Markdown File**

Any files can do.

**Desktop (please complete the following information):**

 - OS: MacOS Ventura

**Typora Version**

Version 1.4.8 (6558)

**Comment by abnerlee** [comment]
fixed in v1.5.x
