### ISSUE TITLE
Mermaid example from documentation crashes.

### ISSUE THREAD

**Issue by pauljurczak** [typora/typora-issues#5519]
I tried an example from https://support.typora.io/Draw-Diagrams-With-Markdown/:
```
```mermaid
graph LR
A[Hard edge] -->B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
​```
```
on Typora v1.4.8 and here is the result:

![Screenshot from 2022-11-24 22-00-28](https://user-images.githubusercontent.com/4933032/203905062-4f33fad5-2aae-4c18-8647-8cfc8501e6bb.png)

**Comment by xiaotianxt** [comment]
You should delete the first line and the end line. The ``` syntax is automatically detected by Typora and created the block you currently watching. The *mermaid* keyword is the type of language, and can be seen at the botton-right.

![CleanShot 2022-11-25 at 15 10 02@2x](https://user-images.githubusercontent.com/17041194/203922085-6e323771-0e0b-4f87-b728-1444e98f844e.png)

**Comment by pauljurczak** [comment]
Thanks, it works.
