### ISSUE TITLE
<img> are failed after exporting as pdf.

### ISSUE THREAD

**Issue by livc** [typora/typora-issues#552]
mac os

**Comment by livc** [comment]
![image](https://cloud.githubusercontent.com/assets/11692045/23340730/6adc6642-fc76-11e6-892e-21ccef49275d.png)

**Comment by abnerlee** [comment]
@livc If possible, could you post the markdown source for the image?

**Comment by livc** [comment]
@abnerlee After trying sometimes, I find `![]()` will wok.  But `<img src="https://123.jpg" width="70%" />` all fail.

**Comment by abnerlee** [comment]
It's a bug, we will fix this on next version up

**Comment by livc** [comment]
awesome

On 27 Feb 2017, at 00:09, AbnerLee <notifications@github.com<mailto:notifications@github.com>> wrote:


It's a bug, we will fix this on next version up

**Comment by abnerlee** [comment]
fixed in new release
