### ISSUE TITLE
center inline math equation in Typora

### ISSUE THREAD

**Issue by ascendho** [typora/typora-issues#5522]
Hi, I am reviewing one course named Parallel Programming，which involves some math equations, so I am wondering how can I center these math equations to be looking beautiful, I have tried Bing to search something useful, but I just saw some similary questions but no solutions, and I find type space may be working, but that's not elegant, so anyone have better solutions? 

![equation](https://user-images.githubusercontent.com/78126591/203998144-aca077a1-cf5d-4722-bc72-75f3c17d4e2b.png)

after typing space:

![centeredequation](https://user-images.githubusercontent.com/78126591/203998185-0750cf35-0b6f-41f7-8e64-1e0a75313c76.png)

**Comment by GoBigorGoHome** [comment]
It seems that your object conflicts with how inline math is rendered by design. Inline math is rendered as part of "left-to-right" flow of text "compactly".

I think you should consider displayed math formula (``$$ ... $$``).

**Comment by abnerlee** [comment]
Please use block math
```
$$
x+y
$$
```
for this case.

Inline math is aligned just like other texts

**Comment by marco-coraggio** [comment]
Isn't there a way to have typora register $$..$$ as a block math?

LLMs commonly return markdown text with $$...$$ intended as displaystyle equations. It would be convenient to have that register in typora
