### ISSUE TITLE
how disable adding title page when export md to epub

### ISSUE THREAD

**Issue by shieep** [typora/typora-issues#5525]
![微信截图_20221128173411](https://user-images.githubusercontent.com/60656957/204243734-110ebe5a-63be-4245-bf56-44ac5d0199ff.png)
the first page in md is a picture, but when i export it to epub format, it auto add a title page.
i don't need the title page
how can i  disable adding title page when adding export md to epub

**Comment by abnerlee** [comment]
It is a title_page.xhtml in epub, which is required, but not the cover or part of the content. In my test, Books.app will directly skip that "page".

You can use "title: 烈焰星球" in YAML (https://support.typora.io/YAML/) to overwrite the default setting (filename) for now. 

In future, we will remove the file extension and allow you to set "title: ''" to make it empty

See https://github.com/jgm/pandoc/issues/797

**Comment by abnerlee** [comment]
improved in v1.5.x
