### ISSUE TITLE
Failed to export as PDF. Undefined

### ISSUE THREAD

**Issue by yigua2000** [typora/typora-issues#5527]
- [Done] Searched existing issues to avoid creating duplicates.

- [Done] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [Done] Searched http://support.typora.io/

----

**Describe the bug**
Failed to export big MD file into PDF. Typora reports "Failed to export as PDF. Undefined"

**To Reproduce**
1. Go to 'File'
2. Click on 'Export'
3. Scroll down to 'PDF'

**Expected behavior**
PDF export should succeed

**Screenshots / Screencasts**
INFO 2022/11/29 14:53:20  ------------------start------------------
INFO 2022/11/29 14:53:20  typora version: 1.4.8
INFO 2022/11/29 14:53:20  undefined
INFO 2022/11/29 14:53:20  addRecentDocument
INFO 2022/11/29 14:53:20  [Raven] instanceKey = 071e447e-7bf8-43b6-825d-b5c6c55b143f
INFO 2022/11/29 14:53:20  [Raven] userId = d909220f-f4d0-4f48-a6a0-e2dd4ea5a038
[Error: ENOENT: no such file or directory, open 'C:\Users\xxxxxxxx\AppData\Roaming\Typora\typora-dictionaries\user-dict.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xxxxxxxx\\AppData\\Roaming\\Typora\\typora-dictionaries\\user-dict.json'
}
INFO 2022/11/29 14:53:20  [focus] 1
INFO 2022/11/29 14:53:20  synced recovery
INFO 2022/11/29 14:53:21  handle document.loadData
INFO 2022/11/29 14:53:21  [RenderProcess 1][Log] [UndoManager] reset commandStack
INFO 2022/11/29 14:53:21  [RenderProcess 1][Log] reset NodeMap
INFO 2022/11/29 14:53:21  [RenderProcess 1][Log] readContentFrom C:\work\GIT_DOC\arch\00_working\Arch_Spec.md
INFO 2022/11/29 14:53:21  [RenderProcess 1][Log] onBecomeActive
INFO 2022/11/29 14:53:21  [RenderProcess 1][Log] File.activeWindow = true
INFO 2022/11/29 14:53:22  [RenderProcess 1][Log] enter busy mode
INFO 2022/11/29 14:53:29  synced recovery
INFO 2022/11/29 14:55:02  load file [C:\Users\xxxxxxxx\AppData\Local\Temp\Typora\1669704901640-0.5814049136636537.html] for PDF export
INFO 2022/11/29 14:55:03  [blur] 1
INFO 2022/11/29 14:55:03  [win] blur
INFO 2022/11/29 14:55:05  [focus] 1
INFO 2022/11/29 14:55:05  [RenderProcess 1][Log] export PDF to C:\work\GIT_DOC\arch\00_working\Arch_Spec.pdf
Timeout for loading print view
INFO 2022/11/29 14:55:12  generate print window with id null
INFO 2022/11/29 14:55:15  synced recovery
INFO 2022/11/29 14:55:15  ----------------before-quit-----------------
INFO 2022/11/29 14:55:15  ------------------will-quit------------------
INFO 2022/11/29 14:55:15  -----------------quit------------------
INFO 2022/11/29 14:55:15  closeLogging

**Sample Markdown File**
Big MD file. Over 300 pages with many diagram and tables.

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]

**Typora Version**
Both in 1.0.4 and 1.4.8. I guess all versions have same issue.

**Additional context**
It looks like a timeout issue. The MD file is big so the printer in Windoes is slow. Sometimes the file can export as PDF after several tries. And same MD file works well on MAC OS. 
Does typora have any option for timeout parameter?

**Comment by abnerlee** [comment]
duplicated with #5471
