### ISSUE TITLE
[Feature] Change italics and bold hotkey to behave like other text editors

### ISSUE THREAD

**Issue by errata-c** [typora/typora-issues#5528]
Currently, when using the hotkey for italics (or bold) twice, the entire section of italics is converted to non-italic text. This differs from the standard behavior of other text editors, which leave the text as italic but make subsequent text non-italic.
As an example, this (using the vertical bar | to represent cursor location):
`*italic|*` is converted to `italic|`
While the standard behavior would be:
`*italic|*` is converted to `*italic*|`
Effectively just moving the cursor out of the italics block.

**Comment by abnerlee** [comment]
Typora is a markdown editor, the hotkey for italic is to add or remove paired *, if you want to move out of `*italic|*` you can simply press right arrow key.

We will close this unless we get more complains from users.

**Comment by ak2243** [comment]
Is there any way to have an option for this? Alternatively, is there a way (either from devs or using the keyboard shortcut json) to have the tab key move out of the markdown group (i.e. move the cursor from before the second asterisk to after it)?
