### ISSUE TITLE
Save file to network driver got an error

### ISSUE THREAD

**Issue by Littlearphone** [typora/typora-issues#5530]
It is normally when I open a file from network driver, but got error on save file.

I degrade typora version to 1.3.6 but still got this error.

My system is window10, and mapped network driver path is like "\\aaa-bbb.ccc.com\ddd_P$"

Here is the error message: 

Save File Failed
Error: ENOENT: no such file or directory, open 'P:\note\document.md'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.writeFileSync (node:fs:2153:35)
    at typora://app/typemark/appsrc/window/frame.js:1:1212973

------------------------------------------------------------------------------

Actually, save file operation is success in few seconds after I open file.

**Comment by abnerlee** [comment]
put into #3981
