### ISSUE TITLE
text shown in unexpected red color when source mode

### ISSUE THREAD

**Issue by windsurf2sky** [typora/typora-issues#5531]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
a kind of combination of `[]` and `()` produce text in unexpected red color as shown in the screenshot
as all we know `[[]]` is backlink, `[]()` is inline link,  
- when {backlink}{text}{inline link}, unexpected red color
- when {inline link}{text}{backlink}, normal

**To Reproduce**
as shown in the screenshot

**Expected behavior**
No unexpected color when source mode

**Screenshots / Screencasts**
<img width="634" alt="Screenshot 2022-12-01 at 8 13 22 PM" src="https://user-images.githubusercontent.com/42901351/205050432-1f6be007-ae4a-4ac2-921d-a594e3bd9717.png">

**Sample Markdown File**
as shown in the screenshot

**Desktop (please complete the following information):**
Mac M1, MacOS 13.0 (22A380)

**Typora Version**
Version 1.4.8 (6558)

**Additional context**

**Comment by abnerlee** [comment]
fixed in v1.5.x
