### ISSUE TITLE
Export with Previous - weird glitch

### ISSUE THREAD

**Issue by ipswitchnutbuster** [typora/typora-issues#5532]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**

Using the "Export with Previous" function after PDF export causes system-wide glitch in keyboard and mouse input, adding the character "e" in front of each input on every non-typora program.

Within Typora, mouse-clicks in the text area creates a carriage return and the character "e"

**To Reproduce**

Go to and click Export -> Export with Previous

**Expected behavior**

PDF export

**Screenshots / Screencasts**

![Screenshot_2022-12-01_12-17-29](https://user-images.githubusercontent.com/80612626/205117886-4a5149ae-ff72-4820-8b20-ca142f3397ae.png)

**Sample Markdown File**

Files contain confidential information.

**Desktop (please complete the following information):**

- SparkyLinux Debian 11

**Typora Version**

1.4.7

**Additional context**

**Comment by abnerlee** [comment]
Could you provide a screencast?

Does reboot your Linux work?

**Comment by ipswitchnutbuster** [comment]
Sorry for the delay. I can't do a screencast, but I've figured out the specific conditions.

It only happens when I try to use ctrl + shift + E on a document that I'm trying to overwrite. It doesn't open the save window, nor does it ask to confirm the replacement, and it doesn't export the new PDF either.

The menu item "file -> Export -> PDF" opens the save window, confirms the replacement, and exports the new PDF

"file -> Export -> Export and Overwrite with Previous" confirms the replacement, and exports the new PDF

I never noticed the "Export and Overwrite with Previous" menu item before. I guess that is the kluge for this problem...

Yes, everything returns to normal after a reboot.
