### ISSUE TITLE
Some images are displayed but not exported to pdf

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#5533]
- [X ] Searched existing issues to avoid creating duplicates.

- [X ] Confirmed that it can be reproduced in built-in themes without customized css.

- [X ] Searched http://support.typora.io/

----

**Describe the bug**
Some images are not exported to pdf. I tried with both jpg and pdf created with Paint.NET.
[Test.zip](https://github.com/typora/typora-issues/files/10142308/Test.zip)
This attachment contains: 
- jpg file
- png file
- md file
- pdf file exported by Typora

Other pictures are exported correctly.

**To Reproduce**
Open the attached md and export to pdf. Then compare it with the one attached in the zip file

**Screenshots / Screencasts**
Attached

**Sample Markdown File**
Attached

**Desktop (please complete the following information):**
 - Windows 10 64 bit

**Typora Version**
1.4.8

**Comment by raffaeler** [comment]
Exporting to docx cause a similar issue: no picture available (red 'x').
At this point the problem is **blocking**.

**Comment by raffaeler** [comment]
I can always repro the issue when a zoom reduction is applied to the image.
I found **no workaround**.

**Comment by abnerlee** [comment]
What is your full image path and exported PDF file path? Does 1.5.0-dev fix this? In my quick test, it seems images can be included in the exported PDF.

**Comment by raffaeler** [comment]
@abnerlee please, first of all try applying 80% zoom to any of your images.
After applying the zoom, the image is not exported anymore.

**Comment by abnerlee** [comment]
merge into #6023

I still cannot reproduce this on 1.8.x, is this fixed? If not please provide details in #6023
