### ISSUE TITLE
Save File Failed when sometimes saving to a FUSE (/network) mounted drive on windows

### ISSUE THREAD

**Issue by bn-l** [typora/typora-issues#5536]
**Describe the bug**
Sometimes, and when pressing save quickly I get this error exactly:
```
Save File Failed
Error: write data failed at
typora://app/typemark/appsrc/window/frame.js:1:585074 at
typora://app/typemark/appsrc/window/frame.js:1:585074 at
FSReqCallback.readFileAfterClose [as oncomplete]
(node:internal/fs/read_file_context:68:3)
```

**To Reproduce**
1. Mount network / FUSE drive on windows
2. Open new file in Typora
3. Save a few times and wait for the error or press ctrl+s quickly.

**Expected behavior**
Saves without write error

**Screenshots / Screencasts**
![2222](https://user-images.githubusercontent.com/13162197/205508847-b5a4953e-3e7c-446a-a5c5-91bcf83a421f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
e.g: 1.4.8

**Additional context**
Seems similar to (but different error): #5386 #5530 #4617. And I see #3981 is working on a fix but none of the issues mentioned have the exact error as this.

**Comment by bn-l** [comment]
## Update:
I believe this issue is related to the lack of debounce on the hotkey combo for saving (for me CTRL + S). When I hold the keys it will eventually produce the error above. 

**Suggested fix: Delay between attempts to save file.** to prevent trying to write to a locked file.

**Comment by abnerlee** [comment]
What kind of network driver did you use? In my test, smb:// can be saved correctly.

**Comment by bn-l** [comment]
It's FUSE on windows (not a network drive, my mistake in the title). Precisely it's boxcryptor--an old piece of software which uses Dokan Library (a windows implementation of fuse)

**Comment by abnerlee** [comment]
@bn-l Could you provide a link to download the software, or a link about how to set up that on Windows?

**Comment by bn-l** [comment]
Hi, this is the same version I have: https://boxcryptor-classic.software.informer.com/1.7/  

To setup:
1. Install (binary above signed by Secomba GmbH--company that used to develop this)
2. Follow the wizard (keep clicking next)
3. Drive will be mounted.

![111](https://user-images.githubusercontent.com/13162197/211466016-9a329d07-5e4b-45d6-b010-880ea12df042.png)
![2222](https://user-images.githubusercontent.com/13162197/211466013-c176c134-2416-43c3-9d25-ab159755fb07.png)

**Comment by bn-l** [comment]
Closing as I moved from boxcryptor to another encfs style atomic file encryption on windows.
