### ISSUE TITLE
[Feature] Modify the DPI of the exported image 

### ISSUE THREAD

**Issue by HoeYeungHo** [typora/typora-issues#5539]
- [x]  Searched existing issues to avoid creating duplicates.
- [x] Searched http://support.typora.io/ since it may be already implemented.

------

I hope that when using Typora to export an image, I can not only adjust the width of the image, but also adjust the DPI of the image. 

DPI of the image export from Typora just 72. When I set the width of the image is 1080, I find the image is too vague!

I'm not sure whether DPI of the output image can be adjusted by modifying the configuration file, but I think it would be better if it could be set in Typora

**Desktop (please complete the following information):**

OS: Windows 11 64bit

**Typora Version**
1.4.8.

**Comment by abnerlee** [comment]
The image is captured from the screen, so the highest DPI will be your screen dpi.
