### ISSUE TITLE
Error on open file(ver0.9.24)

### ISSUE THREAD

**Issue by Windvast** [typora/typora-issues#554]
![image](https://cloud.githubusercontent.com/assets/20946097/23412860/4600adc6-fdd7-11e6-9b23-5b282af0c9a6.png)

**Comment by Windvast** [comment]
And this version is even slower than 0.9.23, is it possible to revert to 0.9.23?

**Comment by weiqiwang15** [comment]
Got this error as well!
![image](https://cloud.githubusercontent.com/assets/17701320/23414096/ab69367e-fdd2-11e6-8542-edf3b25b35b5.png)

**Comment by abnerlee** [comment]
There's some error on the latest build, we have pushed a new one, please re-download it some times later (in case of the cache),  sorry for the inconvenience.

History builds is available from download links from https://typora.io/windows/dev_release.html

**Comment by mschroen** [comment]
Had the same error and re-download fixed it. Thanks!
