### ISSUE TITLE
Math font

### ISSUE THREAD

**Issue by hswind4** [typora/typora-issues#5543]
![image](https://user-images.githubusercontent.com/86911876/206219232-96221fe4-1ec2-4705-8ecf-88b0fd2273c7.png)
数学公式中西里尔字体显示差,如何更换字体?

**Comment by abnerlee** [comment]
duplicated with #5523

**Comment by abnerlee** [comment]
Is it same with #5441 ?

**Comment by hswind4** [comment]
NO. My problem is the math line is not well supported for Cyrillic letters. You can see that on my picture, the space between Cyrillic letters is awful, and the font is weird, looks very bad, Latin letters are all ok.  So, can you tell me why or how can I sovle that? Do I need to change the font of math block or another method?


> Is it same with #5441 ?
