### ISSUE TITLE
can't collapse content

### ISSUE THREAD

**Issue by reallws** [typora/typora-issues#5551]
**Describe the bug**
typora无法正确渲染`<details><summary>`节点内的markdown内容（展开后）

**To Reproduce**
输入以下内容，无法正确渲染：

![image](https://user-images.githubusercontent.com/24283389/208021256-1177bc7f-fe15-4e03-b02f-6f4afbea3d89.png)

**Expected behavior**
预期应该能正确渲染p标签内的markdown文本。
![image](https://user-images.githubusercontent.com/24283389/208021303-c3981a13-776c-4223-99db-ef330092e510.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Typora Version**
1.4.8

**Additional context**
可以参考github 对markdown中类似代码的渲染和实现：https://docs.github.com/zh/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

**Comment by abnerlee** [comment]
duplicated with #1581
