### ISSUE TITLE
[Feature]add vim mode and auto space between Chinese and English snippets

### ISSUE THREAD

**Issue by leng-lingxuan** [typora/typora-issues#5553]
Since you are a paid software, I think you need some features to distinguish yourself from other markdown editors. From my perspective, I hope you can add vim mode and auto space between Chinese and English snippets. 

As a vim lover, vim can significantly improve my note taking efficiency. And there are many people like me.So I think adding vim mode is very important. I see in this repository there was once a issue about the implementation of vim mode, but you closed it in 2021. And until today, this feature haven't been implemented. So I hope you could take that into consideration again.

Second, as a Chinese user,the combination of Chinese and English is ugly because their is no space between them.
LIke this：**让我们拿i和j+1来做比较**.To make it beautiful, I have to input the space everytime I'm in this situation：**让我们拿 i 和 j+1 来做比较**. So it is very uncomfortable. But in softwares like Word, there is already a feature that add space between Chinese and English. 

So I think adding these two features can also attract many Chinese users like me and make Typora closer to perfect.

**Comment by abnerlee** [comment]
duplicated with #5230 and #5449

**Comment by sunshinesDL** [comment]
@abnerlee 开发者你好，如 @paraliine 所说，下面几个版本会考虑加入 vim 模式的功能吗
