### ISSUE TITLE
Still not floating correctly

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#5557]
- [x ] Searched existing issues to avoid creating duplicates.  
Only previous related issues are the ones I previously posted. #5437

- [x ] Confirmed that it can be reproduced in built-in themes without customized css.
Yes, tried Github, newsprint, etc

- [x ] Searched http://support.typora.io/
Found "[Argument mapping Tools Pen and paper Mermaid UI / UX Change some button labels. Images supports float in custom CSS" for beta version 1.5, which does not run on Linux.  Is this the solution I need to wait for?

----
Right-floated images do not wrap text.

example:
`<img src='some.png' style='float:right;width:50%'/>Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah Blah blah `

![x1](https://user-images.githubusercontent.com/1649016/208996389-2b3dc030-3f84-4e3c-a90b-725cbf7d450a.png)
![x2](https://user-images.githubusercontent.com/1649016/208996411-53448da3-15e4-415e-a4eb-fa248a970783.png)

System:
  Kernel: 6.0.13-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    Desktop: KDE Plasma v: 5.26.4 Distro: Manjaro Linux base: Arch Linux

**Typora Version**
1.4.7
1.4.8

**Comment by abnerlee** [comment]
duplicated with #5437
