### ISSUE TITLE
Mermaid 9.3.0 Support

### ISSUE THREAD

**Issue by michael-booker** [typora/typora-issues#5558]
I'm curious when you might include support for Mermaid 9.3.0?

It does not appear that "notes" within a classDiagram are supported by Mermaid 9.1.2.

The following code (using an example from the Mermaid website) throws an error currently:
```
classDiagram
    note "From Duck till Zebra"
    Animal <|-- Duck
    note for Duck "can fly\ncan swim\ncan dive\ncan help in debugging"
```

**Comment by abnerlee** [comment]
supported in v1.5.x
