### ISSUE TITLE
update broke some existing Mermaid functions

### ISSUE THREAD

**Issue by tennr** [typora/typora-issues#5559]
- [ x] Searched existing issues to avoid creating duplicates.

- [ x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**
see MD below

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
https://i.imgur.com/7pOilnw.png
https://i.imgur.com/NU8Fwc9.png
https://i.imgur.com/JbxFKnh.png

**Sample Markdown File**

> Left to Right in subgraphs are now rendering top to bottom
```mermaid
graph LR

subgraph thisTitle[As-is Flow of Inside Sales]
style thisTitle fill:none, stroke:#444,stroke-width:.5,color:#AAA;

1(Cash/Preapproval) -->
2(Pack) -->
3(Boat Complete) -->
4(Pick) -->
5(Accounting Invoice) -->
6(Ship)

end
```

> yaml header defining title does not render the flowchart title
```mermaid
---
title: Node
---
flowchart LR
    id
```

> MindMap bombs even with the sample provided at Mermaid.js.org
```mermaid
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
```

**Desktop (please complete the following information):**
 - OS: macOS 13.1

**Typora Version**
e.g: 1.5

**Additional context**

**Comment by abnerlee** [comment]
For first file, now it is same with https://mermaid.live/ I think it is their newest spec.

For 2nd and 3rd mermaid sample, they are now fixed in 1.5.1-dev
