### ISSUE TITLE
title in mermaid sequence diagram not center aligned

### ISSUE THREAD

**Issue by zsynacl** [typora/typora-issues#5562]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
title in mermaid sequence diagram is not center aligned

**To Reproduce**
write a sequence diagram using mermaid like this (expect the title will be center aligned)
```txt
sequenceDiagram
title: 备选方案1：很长的描述文字ABCDEFG

A ->> B: msg1
B -->> A: msg2
A ->> A: do something
A -->> B: msg3<br/>(status=true)
B -->> C: msg4
```

**Expected behavior**
result of diagram on github shows below
```mermaid
sequenceDiagram
title: 备选方案1：很长的描述文字ABCDEFG

A ->> B: msg1
B -->> A: msg2
A ->> A: do something
A -->> B: msg3<br/>(status=true)
B -->> C: msg4
```

**Screenshots / Screencasts**

finally appears to be like this:

![image](https://user-images.githubusercontent.com/4392800/209049541-395c4f5c-dbc5-4488-a80b-f2d0efc7c0bb.png)

**Sample Markdown File**
any markdown file contains mermaid code block that was written above (in section **To Reproduce**)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.4.8

**Additional context**

**Comment by abnerlee** [comment]
It is also not center aligned in Github, this should be an upstream issue from mermaid

```mermaid
sequenceDiagram
title: 备选方案1：很长的描述文字ABCDEFGHIJKLMNOPQRST

A ->> B: msg1
B -->> A: msg2
A ->> A: do something
A -->> B: msg3<br/>(status=true)
B -->> C: msg4
```

```mermaid
sequenceDiagram
title: 备选方案

A ->> B: msg1
B -->> A: msg2
A ->> A: do something
A -->> B: msg3<br/>(status=true)
B -->> C: msg4
```

**Comment by zsynacl** [comment]
> It is also not center aligned in Github, this should be an upstream issue from mermaid

at least looks better 😭 
I will open an issue in mermaid repo, thanks

**Comment by zsynacl** [comment]
Oh I found this issue

https://github.com/mermaid-js/mermaid/issues/3927

**Comment by abnerlee** [comment]
put into #1661
