### ISSUE TITLE
How to change cursor color in typora

### ISSUE THREAD

**Issue by pdiffley** [typora/typora-issues#5569]
Is there a way to set the color of the blinking cursor in Typora through a theme profile? I am using the [Notion](https://theme.typora.io/theme/Notion/) Darker Enhanced theme. When I open a code block, both the background color and the cursor color are shades of black making the cursor nearly invisible. How can I adjust the theme to change the cursor color?

**Comment by abnerlee** [comment]
You can use

```css
.CodeMirror div.CodeMirror-cursor {
    color: red;
}
```

for cursor in code block.

For cursor in paragraphs, you can use `body {caret-color: red;}`

**Comment by pdiffley** [comment]
I was able to change the cursor color in paragraphs with `body {caret-color: red;}`, but when I tried adding
```
.CodeMirror div.CodeMirror-cursor {
    color: red;
}
```
to several themes, it did not affect the code block cursor color. Is there something else that might work?

**Comment by xiaoqixian** [comment]
> I was able to change the cursor color in paragraphs with `body {caret-color: red;}`, but when I tried adding
> 
> ```
> .CodeMirror div.CodeMirror-cursor {
>     color: red;
> }
> ```
> 
> to several themes, it did not affect the code block cursor color. Is there something else that might work?

Maybe you should add a `!important`, I referred to another night mode theme — cobalt, and it works for me. Here's the code:

```
.cm-s-inner .CodeMirror-cursor {
    border-left: solid thin #f8f8f2 !important;
}
```
