### ISSUE TITLE
Tabs and the 4 Space MD Standard

### ISSUE THREAD

**Issue by spencerclrk** [typora/typora-issues#557]
The way Typora formats lists does not play well with other MD apps because of the 2 or 3 spaces in the code of nested lists.

```
1. Testing
   1. Testing
   2. Testing
2. Testing

<br>

* Testing
* Testing
  * Testing
  * Testing
  * Testing
* Testing
```

Because of this, documents created in Typora break when going to apps like Byword and Ulysses which operate off the 4-space standard or tab per [Fletcher's MD Guide](https://daringfireball.net/projects/markdown/syntax). Please consider implementing one of these or making it an option. Typora is becoming a silo because I can't easily move docs through my workflow from app to app.

**Comment by abnerlee** [comment]
You could set the default indent for sublist in preference panel
