### ISSUE TITLE
Support heading increment/decrement for all elements within a selection range

### ISSUE THREAD

**Issue by Ephron-WL** [typora/typora-issues#5572]
If I select a range of text and elements and I use Ctlr+- or Ctlr++ to increment the selected elements, nothing occurs.

Support heading increment/decrement for all elements within a selection range.

**Comment by abnerlee** [comment]
duplicated with #2375

**Comment by Ephron-WL** [comment]
This is a feature that Word provides.  I've worked with rich text editor components and I can tell you that what I'd do is recurse the elements within the range and adjust them accordingly.  Why is this something you are unable to do?  Is it something special or unusual about developing for Chrome?  What is different about your architecture?  You can't enumerate the divs within the selection, evaluate the properties of each or some in-memory map of their properties and adjust those properties on the divs?

**Comment by Ephron-WL** [comment]
It would be a very valuable and helpful feature...
![image](https://user-images.githubusercontent.com/43553209/211120688-aa5e5edf-c4db-496b-b332-e9ee343bc6fd.png)
