### ISSUE TITLE
Typora being blurred

### ISSUE THREAD

**Issue by kiraitami** [typora/typora-issues#5576]
Typora being blurred after clicking at bottom `Words` menu OR at any time randomly

Also, when scrolling up at sidebar swapping from `Files` to `Search` makes the whole Typora becomes even more blurred

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/58093124/211205060-6d3c573c-499b-423b-b282-a9c90bd39de6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Typora Version**
1.4.8

**Comment by abnerlee** [comment]
Does launch Typora with arguments --disable-gpu fix this?

**Comment by kiraitami** [comment]
Fixed the issue disabling NVIDIA FXAA
