### ISSUE TITLE
Nested <div> destroys HTML export

### ISSUE THREAD

**Issue by roland-KA** [typora/typora-issues#5577]
**Describe the bug**
If I insert a nested `<div>` into a document in the following form ...
```html
<div>
<div>

  in Div1

</div>

<div>

  in Div2

</div>
</div>
```
... it destroys the format of the HTML export for all content that follows this nested `<div>`. "Destroys" means the content isn't displayed right of the TOC, but below (in the example all content beginning from "Sec3") and the content  of the second div (here "in Div2") is displayed on the right of the other content:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/80126696/211299913-33760483-c8c5-43a8-ac34-98c3d0f010d1.png">

**To Reproduce**
The following markdown code (open "Markdown code") reproduces the behaviour:

<details>
<summary>Markdown code </summary>

```
# Sec1

## Sec1.1

adsf

---

# Sec2

## Sec2.1

asdf

<div>
<div>

  in Div1

</div>

<div>

  in Div2

</div>
</div>

---

# Sec3

## Sec3.1

### Sec3.1.1

asdf

---

# Sec4

## Sec4.1

asdf

----
```

</details>

Using this markdown code and then exporting it to HTML (File --> export --> HTML) will produce an HTML-file as the one in the screenshot above.

**Expected behavior**
I would expect that the `<div>` sections don't influence the HTML export at all, so that the content after the `<div>`s also appear with the same formatting like the content above them and that they are displayed in the same column on the right of the TOC.

I need those nested `<div>`s when I write slides for marp (https://marpit.marp.app). There they are used to produce slides with more than one column.

**Desktop**
 - OS: MacOS Ventura 13.1
 
**Typora Version**
Version 1.4.8 (6558)

**Comment by abnerlee** [comment]
fixed in v1.5.x
