### ISSUE TITLE
[Bug] Cutting empty line 20%+ CPU utilization doesn't cut until moved to line with content.

### ISSUE THREAD

**Issue by realwagyu** [typora/typora-issues#5578]
**Demonstration:** https://user-images.githubusercontent.com/91921591/211314796-983b50b7-9dcb-4453-abcc-cbe8aa63e024.mp4

**Description:**
- With cut whole line setting enabled,
- cutting while the cursor is on an empty line,
- doesn't perform the cut and utilize a lot of CPU.
- Afterwards, moving the cursor to a line with content,
- performs the previously initialized cut and frees CPU.

**Reproduction:**
1. Enable `Preferences > Editor > Copy or cut the whole lines that have cursors on them, if there is no selection when doing copy / cut`
2. Move cursor to empty line.
3. Cut.
4. Move cursor to non-empty line.

**additionally...**
- Same result regardless of using hotkey (ctrl+x) or right-click menu to cut.
- Same result regardless of moving cursor with mouse or keyboard up down.
- Copying works properly.

**Environment**
- Windows 11 Version 22H2 
- Typora Version 1.4.8

**Comment by abnerlee** [comment]
fixed in 1.7.5
