### ISSUE TITLE
Edit tables in CSV or TSV files [feature request]

### ISSUE THREAD

**Issue by sjackman** [typora/typora-issues#558]
Since Typora already has a table editor, I'd find it very useful to be able to edit a table stored in a CSV or TSV files, rather than a Markdown file.

**Comment by bcow** [comment]
👍  This would be fantastic

**Comment by abnerlee** [comment]
Typora will focus on "markdown" files, so we do not have plans to extend it to other file formats

**Comment by sjackman** [comment]
Okay, thanks anyway. In the mean time, a workaround is to convert TSV to Markdown using [Miller](https://github.com/johnkerl/miller) `mlr --itsvlite --omd cat foo.tsv > foo.tsv.md`, edit the file using Typora, and then convert from Markdown back to TSV. The best tool I have for that is sed:
```sh
gsed -e 's/ //g;s/^|//;s/|$//;/^---/d;s/|/\t/g'
```

**Comment by aavezel** [comment]
Reopen the feature requirement with this description:

I'd find it very useful to be able to paste csv text (over special paste, like exel) with automatic reformat as markdown format table. And special copy table from Typora as csv/tsv text. It's very will help in writing articles on economics, sociological and mathematical research

**Comment by Plutonium-239** [comment]
It would be awesome to have a way to 'import' CSVs as tables, or at least be able to special paste on an MD table while we have CSV text copied.

**Comment by esetleges** [comment]
UPVote: any of importing solutions above
