### ISSUE TITLE
[Feature] shortcut for custom character insertion feature

### ISSUE THREAD

**Issue by lch32111** [typora/typora-issues#5580]
Hello I'm enjoying typora while studying. I'd like to ask this feature request that a user can insert some characters with the custom shortcut feature.

For example, I am using inline latex on typora with these '$$ ' symbols. However, I noticed that another environment (in particular, my blog markdown) only allows '$$$$' double dollar symbols for the inline math latex. So, I think that It will be good for a user to add a shortcut key that a user just types whatever they want. For example on the conf.user.json, I'd like to add this :
```json
"keyBinding": {
    "$$$$" : "Ctrl+Q"
    "$$\mathbb{R^n}$$" : "Ctrl+R"
},
```
so that if a user hit the Ctrl+R, then the characters "$$\mathbb{R^n}$$" will be inserted on the cursor.

Or if you know any other solution for this problem, please let me know. 

Thanks.

**Comment by abnerlee** [comment]
put into #3021
