### ISSUE TITLE
[BUG] Fonts on mermaid.js inline configuration for one diagram affects all diagrams on the page

### ISSUE THREAD

**Issue by FSXAC-sd** [typora/typora-issues#5582]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

It appears that mermaid's inline configuration for fonts of one diagram affects other diagrams. When there are several mermaid diagrams on the same markdown file, if one of them uses inline configuration with a font setting, other diagrams' fonts will change.

It's more weird and unpredictable when there are multiple mermaid diagrams and they all use inline configurations. It appears that the order in which the diagrams are in the markdown file also have an affect in which font actually gets used in the diagram.

Below are two mermaid diagrams on the same page:

![image](https://user-images.githubusercontent.com/113130605/211872058-5574ce8e-dff4-438b-bc62-b062ed07997c.png)

![image](https://user-images.githubusercontent.com/113130605/211872093-d9c2bf0c-83c4-4f21-ab99-671a8b647962.png)

Notice that:

- Times New Roman is applied to both diagrams even though is only configured for the second diagram.
- Arial is only applied to the date axis on the first Gantt chart diagram

**To Reproduce**
1. Insert Mermaid diagrams into the same markdown file
2. Apply an inline configuration to change the font of a diagram using `%%{init: {'fontFamily': '<font>'}}%%` where `<font>` is a font name.
3. Observe that other diagrams re-renders with \<font\> even though they're not supposed to.

**Expected behavior**

Given that inline configurations are written inside each diagram's codeblock, this configuration should only apply for that individual diagram. So their font settings should not "bleed" to other diagrams.

**Screenshots / Screencasts**

*See above*

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

[w02-mermaid-test.md](https://github.com/typora/typora-issues/files/10394563/w02-mermaid-test.md)

**Desktop (please complete the following information):**

Windows 10 Enterprise 10.0.19044 Build 19044

**Typora Version**

version 1.5.2-dev

**Additional context**

**Comment by abnerlee** [comment]
fixed in 1.6.5
