### ISSUE TITLE
Missing file with no reason

### ISSUE THREAD

**Issue by othellashao** [typora/typora-issues#5585]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
Yesterday I'd add a new .md file under folder. But it's gone today!! Not the first time, several weeks ago I'd met this issue once. I'd summary some useful info in it, it troubled me. I feel unsafe to use it because the files will gone sometimes. 

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

**Typora Version**
e.g: 0.10.11

**Additional context**

**Comment by abnerlee** [comment]
What's your OS and typora version?

Gone means file is gone or file is there, but content is gone?

**Comment by othellashao** [comment]
Current version : Version 1.4.8 (6558)
I think you can ignore this issue now, this time’s gone file come back next open the Typora, I’m not sure why or maybe just mistake by my eyes:). Last time met this issue is more than month ago, no useful info can provide to you currently.

From: AbnerLee ***@***.***>
Date: Monday, January 16, 2023 at 22:04
To: typora/typora-issues ***@***.***>
Cc: Othella Shao (weijshao) ***@***.***>, Author ***@***.***>
Subject: Re: [typora/typora-issues] Missing file with no reason (Issue #5585)

What's your OS and typora version?

Gone means file is gone or file is there, but content is gone?

**Comment by cpyh** [comment]
similar trouble for me (macOS 11.4 & typora 1.4.8)

some info:

if I don't restart the computer for a long time(more than a week), then when i open the typora, any file is blank and not editable. when I restarted the computer, anything works.

**Comment by abnerlee** [comment]
> if I don't restart the computer for a long time(more than a week) and then open typora, sometimes any file is blank and uneditable.

What about Safari.app and Mac App Srtore.app? Are they blank when Typora is blank?

**Comment by cpyh** [comment]
i am not sure currently, i will have a try next time i met this issue. thanks for replying.

**Comment by cpyh** [comment]
![1](https://user-images.githubusercontent.com/38612669/219665360-bd200c41-29cb-48ea-85a4-5f23d74ee35f.jpg)

**Comment by cpyh** [comment]
![2](https://user-images.githubusercontent.com/38612669/219665448-b016e86d-cc47-4c09-af48-baa296318fe5.jpg)

**Comment by abnerlee** [comment]
> i could not do anythin in Safari and Mac App Srtore.app loses app store connection.

Then this should be a macOS bug. Somehow macOS webkit is dead. BTW, please try https://support.typora.io/Trouble-Shooting/
