### ISSUE TITLE
[Feature] Paginated mode

### ISSUE THREAD

**Issue by fansch** [typora/typora-issues#5586]
Hi,

If Typora is used to maintain documents used both in their markdown version (under git file versioning) and a PDF version to be maybe printed, it could be interesting to have a new mode besides the normal markdown mode, the typewriter and focus mode and the source code mode: a paginated mode. In a first step, a simple horizontal line could show the limit of the pages that would match with the paginated PDF, Word or OpenOffice export.

After that, directly seeing the header and the footer in this paginated mode, could be a further feature, but it is not really necessary, as this can be checked once exported. Checking the page breaks in the export is more accurate because it needs to make several exports until you get the right logical cutting of the text through the page breaks.

Thanks a lot

**Comment by abnerlee** [comment]
duplicated with #1732
