### ISSUE TITLE
[Bug] The blank line after the HTML table disappears

### ISSUE THREAD

**Issue by xtsang** [typora/typora-issues#5588]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

The next row of the HTMl table is a header or bold row, etc. Modify the HTML table in source code mode. Then modify the header in normal mode. Return to source code mode, and the blank line after the HTML table will disappear.

**Screenshots / Screencasts**

https://user-images.githubusercontent.com/55629892/212471853-b184af13-95b6-4d45-b060-9242a8438b6b.mp4

**Desktop (please complete the following information):**

 - OS: Windows 11 Version 22H2

**Typora Version**

- Typora Version: 1.4.8

**Comment by abnerlee** [comment]
fixed in v1.5.x
