### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by a-ctor** [typora/typora-issues#559]
It would be nice feature if you could open a files by supplying command line arguments. Something along the lines of:

    typora test.md

**Comment by solarce** [comment]
While it doesn't give you any specific cli arguments that might be helpful, you can do a _basic_ invocation of [Typora from a shell](http://support.typora.io/Use-Typora-From-Shell-or-cmd/). Though a little extra work is needed on Windows and macOS, to associate `.md` with the application.

**Comment by a-ctor** [comment]
I got none of those things to work. I've tried supplying a file as first argument but it just opens an untitled file instead. Same thing happens when opening an associated file through the explorer (*.md files are associated with typora and open typora itself but not the file)

Windows x64 newest version

**Comment by a-ctor** [comment]
@solarce Tried it again today and it works. Same thing as my other issue #560 is suspect.

**Comment by libbin** [comment]
script work-around: if it is not present, touch it before typora invocation
