### ISSUE TITLE
Problem occurs when type in math expression.

### ISSUE THREAD

**Issue by ForestRealms** [typora/typora-issues#5591]
- [v] Searched existing issues to avoid creating duplicates.

- [v Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [v] Searched http://support.typora.io/

----

**Describe the bug**
The OS is "Ubuntu 22.10". When typing a math expression in the software, the expression was shown incompletely. As shown in the figure below.

**To Reproduce**
$$

$$
When typing a math expression in the software, the expression was shown incompletely. As shown in the figure below.

**Expected behavior**
Show normally please.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/97569905/212879923-1e209b3c-eb2c-4432-88fd-d119f8c5c7b8.png)

**Sample Markdown File**
`markdown
$$
M_x=\iint ydxdy
$$
`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10 64-bit

**Typora Version**
e.g: 1.4.8

**Additional context**

**Comment by abnerlee** [comment]
What about version 1.5.x?
