### ISSUE TITLE
typora-root-url not support absolute path

### ISSUE THREAD

**Issue by irrealizable** [typora/typora-issues#5595]
I follow this: https://support.typora.io/Images/#relative-path-to-certain-folder
![image](https://user-images.githubusercontent.com/56907077/213224402-8dba5848-72d0-4363-afef-9c93c0fd6a13.png)

img path : D:/mydocument/life/personal/diary/assets/gg45f.jpg

typora-root-url: /D:/mydocument/life/

![](personal/diary/assets/gg45f.jpg) 

But it doesn't work properly

**Comment by abnerlee** [comment]
On Windows, please use Windows style path, like `D:\mydocument\file`
