### ISSUE TITLE
User-defined directory sorting function

### ISSUE THREAD

**Issue by mrzkj** [typora/typora-issues#5597]
When I was taking notes, I found that the page of the document tree could not drag the custom md document order like OneNote, but could only be sorted by file name or modification time, so I had to add the serial number at the beginning of the file to realize the custom sorting of md documents and realize the order of the thinking line of notes.  However, if I want to insert a new md document in the middle of the already sorted md document, I have to manually change the ordinal number in the document name, which is very tedious and complicated :(So I want typora to add the ability to drag and change the order of the md document.
I wonder if it is possible to add a configuration folder under the save directory of md documents, which contains a new file for recording the sorting information of md documents, so that the original sorting order can be maintained even if the note folder is moved to another device.  Or, do you have a better way to customize the md document sort order?

**Comment by abnerlee** [comment]
#3655
