### ISSUE TITLE
Typora Text Manipulation – Unexpected Behaviours

### ISSUE THREAD

**Issue by iganokage** [typora/typora-issues#56]
Using Typora 0.9.8.1 on Mac OS X 10.11.3 – text manipulation seems to behave unexpectedly compared to the OS standards. Excellent software with just a few small annoyances I haven’t seen mentioned in **Issues** so far. Here are my best descriptions but it’s probably easiest to see in the brief animation attached below.

#### **Typora** (_unexpected behaviour_):

- Double-click selection of a word briefly seems to include the trailing space but then removes it. Deleting the selected word leaves the surrounding spaces (so need to delete one of those) but replacing/typing over the word preserves the surrounding spaces as expected.
- Double-click on word and drag (selecting a group of words), loses the overall selection and only keeps the last word selected.
- Alt+backspace deletion of word at a time works fine. Alt+delete forward deletion of words does not work, seems to ignore the alt and do character deletion.

#### **TextEdit** (_standard OS X behaviour_):

- Double-click selection of a word, does not show spaces included. However, deleting the selected word also removes the one extra space (sentence has correct amount of spaces) and replacing/typing over the word preserves the two surrounding spaces.
- Double-click on word and drag (selecting a group of words), quick and accurate way to select a phrase without needing to select by character.
- Alt+backspace deletion of word at a time. Alt+delete forward deletion of words.

#### Illustrated example:
![typora-text](https://cloud.githubusercontent.com/assets/10992690/12847421/fab543f8-cc0a-11e5-97e3-a91571db04d4.gif)

Let me know if you need any further information, thanks!

**Comment by abnerlee** [comment]
Hi, @iganokage

Really thanks for the detailed bug report.There are some details I didn't notice before~

**Comment by abnerlee** [comment]
should be fixed in latest version
