### ISSUE TITLE
File association not working

### ISSUE THREAD

**Issue by a-ctor** [typora/typora-issues#560]
The windows installer automatically associates `*.md` files with typora. That's great - although a setting for it in the installer would be nice.

The problem is that when opening a file typora starts but does not open the requested file.

Same problem occurs if you drag and drop a file into a typora window.

Seems to be related to #559

**Comment by abnerlee** [comment]
@a-ctor It happens for all file or just some file?

And does File->Open work?

**Comment by a-ctor** [comment]
@abnerlee Opening a file works as expected

**Comment by a-ctor** [comment]
@abnerlee Tested it out again and everything works fine. Do not know what caused that yesterday.
