### ISSUE TITLE
[Bug]mermaid classDiagram cannot show notes

### ISSUE THREAD

**Issue by dominicshanshan** [typora/typora-issues#5601]
**Describe the bug**

mermaid classDiagram cannot show whole notes

classDiagram
			lstmcell00 --> lstmcell01
			lstmcell00 --> lstmcell01
			lstmcell00 --> lstmcell10
			lstmcell01 --> lstmcell02
			lstmcell01 --> lstmcell02
			lstmcell01 --> lstmcell11
			lstmcell10 --> lstmcell11
			lstmcell10 --> lstmcell11
			lstmcell10 --> lstmcell20
			lstmcell11 --> lstmcell12
			lstmcell11 --> lstmcell12
			lstmcell11 --> lstmcell21
		
			lstmcell00 : +output c00 and h00 to lstmcell10
			lstmcell00 : +output f(c00) to lstmcell01
			lstmcell01 : +output c01 and h01 to lstmcell02
			lstmcell01 : +output f(c01) to lstmcell11

**Screenshots / Screencasts**
![2023-01-21 at 15 14](https://user-images.githubusercontent.com/30051912/213848465-7ee26455-de28-4708-8654-0761396d2ddb.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1

**Typora Version**
Version 1.4.8 (6558)

**Comment by abnerlee** [comment]
fixed in v1.5.x
