### ISSUE TITLE
Cursor jumps when editing link inside of italic text

### ISSUE THREAD

**Issue by blat-blatnik** [typora/typora-issues#5605]
Cursor behaves strangely while editing link inside of italic text.

**To Reproduce**
1. Paste this into a blank markdown file: `_[a]()c_`.
2. Move your cursor into the `()` to type the link.
3. Type any character.
4. After you type the character, the cursor is moved outside of the link parenthesis, so the next character will no longer be part of the link.

**Expected behavior**

After typing the character, the cursor should stay inside of the link parentheses.

```
Expected: _[a](|)c_ -> _[a](b|)c_
Actual:   _[a](|)c_ -> _[a](b)|c_
               ^
             cursor
```

**Desktop**
Windows 10 64bit

**Typora Version**
1.4.8

**Comment by abnerlee** [comment]
fixed in 1.5.11
