### ISSUE TITLE
<details> element gets parsed incorrectly when using github flavoured markdown.

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#5606]
- [x] Searched existing issues to avoid creating duplicates. (this is _not_ a duplicate of the several issues asking for a foldable element: if we ever get one, great, but this is a bug report specifically for `<details>` getting rendered incorrectly)
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/ (this is an actual bug. It doesn't matter if there's a support article.)

----

**Describe the bug**

The `<details>` element with markdown in it, when using github flavoured markdown as markdown of choice, renders incorrectly.

**To Reproduce**

Create a new document, switch to source code mode, and fill it with:

<pre>This is a test

Preamble

&lt;details&gt;
  &lt;summary&gt;expand&lt;/summary&gt;
  
  ```python
  import math
  print(f'pi has value {math.pi}')
  ```
&lt;/details&gt;

Lead-out</pre>

Then turn off source code mode and watch Typora render the content completely wrong, showing a clickable summary that expands to "nothing", and the detail's markdown converted _after_ the details element, with a rogue `</details>` in grey at the end.

**Expected behavior**

The markdown inside the details element should get converted just like markdown in any other block context, and the details element should get rendered as a clickable summary, expanding to reveal the converted markdown's content.

**Screenshots / Screencasts**

Expected result:

<kbd>
<img src="https://user-images.githubusercontent.com/177243/214983191-388ee571-8c10-4374-939e-ace19916bdfd.png">
</kbd>

Expected expanded result:

<kbd>
<img src="https://user-images.githubusercontent.com/177243/214983384-b967634a-e1ca-4a25-97f6-f709128a4fb8.png">
</kbd>

Actual result: 
 
<kbd>
<img src="https://user-images.githubusercontent.com/177243/214983106-33f83678-51de-4770-af6e-c316e1816de6.png">
</kbd>

**Sample Markdown File**

See above

**Desktop (please complete the following information):**
 - OS: windows 10 pro x64, 22h2

**Typora Version**
1.4.8

**Comment by Pomax** [comment]
What it looks like _right here_ on github, the authority for how github flavoured markdown should get parsed:

---

This is a test

Preamble

<details>
  <summary>expand</summary>
  
  ```python
  import math
  print(f'pi has value {math.pi}')
  ```
</details>

Lead-out

**Comment by abnerlee** [comment]
#1939

**Comment by Pomax** [comment]
@abnerlee that's from 2018, well before you were a paid application. Time to close that one, and file a new one under "our github flavoured markdown parser has a demonstrable bug" =)

**Comment by syselement** [comment]
Still un-solved.
**_Windows Typora Version 1.5.8_**

**Source code:**

![image](https://user-images.githubusercontent.com/81392234/219472725-c014ae33-220b-4ec3-8919-ceca0f46696c.png)

**And Github test:**
<details>
<summary>Reveal Flag🚩</summary>

`FLAG`

</details>



**Actual Typora Result:**
![image](https://user-images.githubusercontent.com/81392234/219472650-e0360a11-2d92-49ff-b4bb-7087e7b40780.png)

![image](https://user-images.githubusercontent.com/81392234/219472688-4110f2a9-1396-4c19-9748-410dba276e34.png)

**Comment by Pomax** [comment]
@abnerlee can we reopen this one? Because it's not a duplicate, its far more specific, and something that should be solvable _independently_ of the issue you marked as dupe.
