### ISSUE TITLE
[Feature] preserve cursor position when switching between wysiwyg and source code views

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#5607]
Right now (in 1.4.8) on a long document, switching between wysiwyg and source code view does not show roughly the same content between switches. It's entirely possible for a view switch to show you the end of the document even though your were looking at the a paragraph near the start of the document.

It would be great if Typora could at the very least show the content at the cursor when switching mode, but it would be even better if it would take whatever is the central content in the viewport, and then show the user the corresponding content in the other view when switching.

**Comment by abnerlee** [comment]
Does this happen in version 1.6.x ? If so, could you provide a sample md file that "switch to show you the end of the document even though your were looking at the a paragraph near the start of the document." ?

**Comment by Pomax** [comment]
looks like 1.6.7 no longer suffers from this

(the document I was working on is https://github.com/Pomax/are-we-flying/blob/main/docs/index.md, which is about 146 pages according to print preview)
