### ISSUE TITLE
Can't render tables within hidden blocks

### ISSUE THREAD

**Issue by scruel** [typora/typora-issues#5609]
**Describe the bug**
For tables within hidden block, typora rendered unexpectedly

**To Reproduce**
Check markdown file section.

**Expected behavior**
Tables should be hidden in the `details` html block.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/16933298/215318163-a2f89fc7-6240-4e2f-ad05-d9aa1cbe2e9a.png)
![image](https://user-images.githubusercontent.com/16933298/215318126-1718bdbd-7f0a-4356-a963-c66824bfe55c.png)

**Sample Markdown File**
```
<details>
<summary>More Parameters</summary>

| Param | Desc | Example |
|:----- |:---- |:------- |
|       |      |         |

</details>
```

**Desktop (please complete the following information):**
OS: [e.g. Windows 11 64bit]
**Typora Version**
1.4.8

**Comment by abnerlee** [comment]
#1939
