### ISSUE TITLE
Documents Beginning With Setext Heading Begin With Blank Line

### ISSUE THREAD

**Issue by kleinfelter** [typora/typora-issues#561]
I create almost all of my Markdown documents beginning with a setext heading like so:

> `This Is the First Line`
> `---------------------`
> 

The very first line of my .md file is "This is the First Line".  The second line is the row of dashes.

Typora renders these with a blank line before my header.  It does this whether I'm in regular mode or source code mode.

If I edit my file with Textedit and replace the setext heading with an ATX heading, and re-open the document with Typora, it does not render with the extra blank line.

While I could edit all of my Markdown and replace all my setext headings with ATX headings, I'd prefer not to do that.

**Comment by abnerlee** [comment]
@kleinfelter The setext heading seems OK in my testing. Could you tell me your OS/Typora version?

And if that still happens, could you send us (hi@typora.io) a sample *.md file that Typora will prepend a blank line when rendering?
