### ISSUE TITLE
An Error Occurred in Mermaid When Setting The Theme

### ISSUE THREAD

**Issue by HoeYeungHo** [typora/typora-issues#5614]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

When I set a custom theme as mermaid said ([Theme Configuration | Mermaid](https://mermaid.js.org/config/theming.html)), that is

```
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#BB2528',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#F8B229',
      'secondaryColor': '#006100',
      'tertiaryColor': '#fff'
    }
  }
}%%
        graph TD
          A[Christmas] -->|Get money| B(Go shopping)
          B --> C{Let me think}
          B --> G[/Another/]
          C ==>|One| D[Laptop]
          C -->|Two| E[iPhone]
          C -->|Three| F[fa:fa-car Car]
          subgraph section
            C
            D
            E
            F
            G
          end

```

The error appears and prompts:

```
ERROR: [Mermaid] Parse error on line 2:
init: { 'theme':
--^
Expecting 'NEWLINE', 'SPACE', 'GRAPH' got 'ALPHA'
```

I must keep "`%%{`" and "`init: {`" in the same line that the error disappears.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/60749707/216294247-223ec957-06b0-41f0-b1b3-7811dd2b0875.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
1.4.8

**Comment by abnerlee** [comment]
fixed in 1.5.11
