### ISSUE TITLE
[Feature] Collapsible YAML frontmatter

### ISSUE THREAD

**Issue by lloydjatkinson** [typora/typora-issues#5615]
Please detect YAML frontmatter in MD and MDX files and allow users to minimize it when not needed. It's distracting when it isn't needed. As an example, here is YAML frontmatter I'd want to minimize.

![image](https://user-images.githubusercontent.com/5633938/216441377-3698acbb-20a9-4317-95ed-3aee56313094.png)

**Comment by jaekyeom** [comment]
One workaround with a CSS snippet:

```
.md-meta-block.md-end-block:not(.md-focus) {
    height: 80px;
}
```

**Comment by abnerlee** [comment]
maybe duplicated with #2169
