### ISSUE TITLE
Failed to update to 1.5.5 on macOS

### ISSUE THREAD

**Issue by vronizor** [typora/typora-issues#5616]
- [x] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I get a "Update error! Failed to extract update." error when updating from 1.4.8 to 1.5.5 on macOS 13.1, M1 Pro

**To Reproduce**
1. Go to Typora > Check for updates > Update now

**Expected behavior**
The update to go through.

**Screenshots / Screencasts**
<img width="732" alt="Screenshot 2023-02-04 at 22 19 36" src="https://user-images.githubusercontent.com/22742874/216791865-791d4d11-be7d-4a31-9ac3-4d0744033de9.png">
<img width="372" alt="Screenshot 2023-02-04 at 22 19 42" src="https://user-images.githubusercontent.com/22742874/216791868-32d4454d-17ca-469d-8cbe-e069bc61d790.png">

**Sample Markdown File**
NA

**Desktop (please complete the following information):**
 - OS: macOS 13.1

**Typora Version**
1.4.8

**Comment by saegl5** [comment]
same for me (macOS 13.2)

**Comment by cpyh** [comment]
same for me (macOS 11.4 & typora 1.4.8)

successfully updated to version 1.5.5 by downloading dmg.

**Comment by rowdenw** [comment]
Same! Typora Version 1.4.8 (6558) on Ventura 13.2

**Comment by abnerlee** [comment]
It is fixed now, please retry.

Sorry for the inconvenience.
