### ISSUE TITLE
Ctrl+1 is no working

### ISSUE THREAD

**Issue by zengchen233** [typora/typora-issues#5617]
## Typora Version

![image](https://user-images.githubusercontent.com/67224979/216798283-77208155-6a9e-4768-87ed-dce54a143a38.png)

## Problem/Bugs

When typing Ctrl+1, this function seems no working, the other function is pretty good.

you can try it😭, I don't have screen recording software, I'm no joking!

## OS

Windows11

![image](https://user-images.githubusercontent.com/67224979/216798372-70013d12-ed91-4e76-882c-6f70c69ae31d.png)

**Comment by abnerlee** [comment]
Does Ctrl+2 work? Does click menu → Paragraph → Heading 1 work?

**Comment by zengchen233** [comment]
> 
Ctrl+2 work，and click menu → Paragraph → Heading 1 is working too,
when typing Ctrl + 1,it may not work.

**Comment by abnerlee** [comment]
Please check if ctrl+1 is occupied by other apps (like https://blog.csdn.net/lly1122334/article/details/110959067)
