### ISSUE TITLE
[Feature] Link to local markdown file's paragraph

### ISSUE THREAD

**Issue by zhuozhiyongde** [typora/typora-issues#5618]
As title, I would like to request to add a **Link to a paragraph** feature similar to the one provided by Github (It allows you to use the link like `https://links.example#paragraph2` or `~/path/to/file#paragraph3` to locate the file and jump to the **specific paragraphs**). 

This is because when I'm building a Markdown knowledge network, I often need to jump to another section, and the existing reference syntax or link syntax only supports locating the file and opening it, not specifically opening a particular paragraph, which means I need to search keywords after I open the file. I hope the writer could add a feature to solve this problem.

Thx for your considering.

**Comment by abnerlee** [comment]
You will need to put a custom anchor in markdown, like <a id="paragraph2"></a> before the paragraph you want to link, see

https://support.typora.io/File-Management/#links-to-file
https://support.typora.io/Links/#internal-links
