### ISSUE TITLE
right click mouse,  the file freeze as a blank file

### ISSUE THREAD

**Issue by vrbridgellc** [typora/typora-issues#5620]
- [X ] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x] Searched http://support.typora.io/

----

**Describe the bug**

when I right click mouse, the doc becomes blank (side panel disappear), and I can not input anything and do not know how to quit unless I quit Typora. 

**To Reproduce**
1. open any new (and type something) or existing md file
2. Right click mouse 
3. See error

**Expected behavior**
the md file becomes blank, and I can not input anything and do not know how to quit unless I quit Typora. 

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
any file will work. 

**Desktop (please complete the following information):**
 - OS: MACOS Ventura
 -
**Typora Version**
 1.5.5. Mac Version

**Comment by abnerlee** [comment]
Possible to attach a screencast or send to us <hi@typora.io>?
