### ISSUE TITLE
Add a clarity sample with sample template for how to export with pandoc pdf/docx

### ISSUE THREAD

**Issue by fbo** [typora/typora-issues#5624]
I had a lot of trouble juggling between the two documentations, especially the pandoc one, which is vast, but I can't see through Typora.
Example:
- I create a new profile of a company name and I associate the cover page template in pdf or docx
- How to define the needs, such as table of contents, header, footer, etc...
- Then generate and export for the client in pdf or docx... for example
I think it would be nice to have complete forms to embed in typora and behind will automatically generate a conversion script. But also through the Typora documentation to explain with examples how to add a cover page, with pandoc, etc...
Thank you very much

**Comment by abnerlee** [comment]
We have added more pandoc explanations. For covering page, you can check https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/README.md
