### ISSUE TITLE
How to center a table in a pdf file? 

### ISSUE THREAD

**Issue by stu-zhangxl** [typora/typora-issues#5626]
How to convert the md file operated in the software into a pdf file and display the edited table in the center? The operation results on my side are as follows:
<img width="495" alt="typora_table_error" src="https://user-images.githubusercontent.com/67547959/217987654-446b5275-a6e3-42d1-92ca-ee49012de586.png">

**Comment by abnerlee** [comment]
The table is full width and center aligned in Github theme. Please check your page margin settings and check if your table is in a list or other indented blocks.
