### ISSUE TITLE
There is something wrong with check update

### ISSUE THREAD

**Issue by NEKOaoliao** [typora/typora-issues#5628]
**Describe the bug**
It seems like the "check update" version in help tab is  not the latest stable version.  This is a little annoying, because I have to download from the website to get the latest version.

**To Reproduce**
1. Go to 'help'
2. Click on 'check update'

**Expected behavior**
Need the latest version in check update to be correct.

**Screenshots / Screencasts**
![screenshot](https://user-images.githubusercontent.com/65473904/218235734-e004e00a-f830-48c5-97bc-6172997877a1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
e.g: 1.5.6

**Comment by abnerlee** [comment]
We will first release the latest version to website then notify the update channel.
