### ISSUE TITLE
Update docs regarding support for Pandoc v3.0+

### ISSUE THREAD

**Issue by metafeather** [typora/typora-issues#5629]
Pandoc v3.0 was released on [2023-01-18](https://pandoc.org/releases.html#pandoc-3.0-2023-01-18) and there have further updates since then.

It's unclear from the docs if Typora has been fully tested with v3.0+, which makes it harder for new users to test if it works for their environment; in my case, as a new user who had just installed pandoc via Homebrew I was running v3.1.

I had to downgrade to Pandoc v2.19.2 since importing from `docx` was failing (as the `--atx-headers` options was removed after being deprecated in v2.11.2), whilst exporting to `docx` worked fine with v3.1.

I would imagine that there are other Typora features that may be broken depending on what flags for pandoc they might use.

**Comment by abnerlee** [comment]
put into #5639 since it can be fixed by Typora side
