### ISSUE TITLE
Column position when adding new row in table

### ISSUE THREAD

**Issue by ShikChen** [typora/typora-issues#563]
When adding new row in table, the current behavior is keeping the cursor at the same column.
IMO, move the cursor to the first column is more intuitive. It's frustrating that I have to do this manually. My workaround for now is preallocate many rows first, and using [TAB] to goto next cell. Is there any good reason to keep the cursor at the same column?

**Comment by FinallyFinancialFreedom** [comment]
yes，i have this problem too. i think it's a bug.
cmd+enter or shift+enter to append a new row, i think the cursor should be in the first column of new row, but it's in the last column.

**Comment by abnerlee** [comment]
that make sense

**Comment by abnerlee** [comment]
Fixed in the newest version
