### ISSUE TITLE
[Feature][Spell] Can we have a shortcut for replace misspell words instead of mouse clicking?

### ISSUE THREAD

**Issue by w1nda** [typora/typora-issues#5630]
![fixSpelling](https://user-images.githubusercontent.com/32250288/218300178-db0aebd1-25b2-4d87-9198-89fd5b5a3775.gif)

The Gif demonstrates how I fix misspell words:
1. Right click the misspell word.
2. Click the word we want in the menu poped up.

Could we have a shortcut that we can easily fix misspell words by:
1. Press the shortcut key, then the misspell word will be replaced by the right word we want.

**Comment by richo67** [comment]
I have solved this on linux by defining key on my keyboard () which generates same code as right click of the mouse. Often this is by default existing key somewhere next to right CTRL key. 

I am not sure how possible is this on different platforms. I know on Windows you can use for this [Autohotkey sw](https://www.autohotkey.com/)
