### ISSUE TITLE
Creating new file will duplicate content from current editor

### ISSUE THREAD

**Issue by OwenYou** [typora/typora-issues#5631]
- [√] Searched existing issues to avoid creating duplicates.

- [√] Confirmed that it can be reproduced in built-in themes without customized css.

- [√] Searched http://support.typora.io/

----

**Describe the bug**
When newing a file by clicking the '+' button on left sidebar, the file created will duplicate content from current editor. 

**To Reproduce**
1. Go to 'File Sidebar'
2. Type something in the editor
3. Click on 'New File'
4. The content in editor will be copied into the created file

**Expected behavior**
The new file created should be empty.

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro 22H2]

**Typora Version**
e.g: 1.5.7

**Comment by abnerlee** [comment]
fixed in v1.5.8
