### ISSUE TITLE
Shift-Arrow keys don't work propertly after Shift-Cmd selection

### ISSUE THREAD

**Issue by nk9** [typora/typora-issues#5632]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**
1. Create a new file and add some text. Ensure you are in Rendered Mode, not Source Code Mode.
2. Place the cursor in the middle of a line.
3. Press Cmd-Shift-Right arrow to select to the end of the line.
4. Press Shift-Left arrow.
5. The selection is modified from the left, being enlarged by one character.
6. Now try the same in Source Code Mode, and in any other macOS application. You will see different behavior.

**Expected behavior**
The selection should be modified from the right side which you used Cmd-Shift-arrows to extend it to. Note that Typora behaves correctly, even in Rendered Mode, when you use Cmd-Shift-Left to get to the *beginning* of the line and then modify the selection using Shift-Arrows.

**Screenshots / Screencasts**

https://user-images.githubusercontent.com/3646730/218537952-e862f98e-da36-4943-bd04-7c1d41e7a319.mp4

**Sample Markdown File**
Any file will do

**Desktop (please complete the following information):**
 - OS: macOS 12.6.2

**Typora Version**
Version 1.4.8 (6558)

**Comment by nk9** [comment]
Just confirming that this is still happening on version 1.6.7. Any chance of a fix?

**Comment by nk9** [comment]
I'm no longer seeing the broken behavior on 1.7.4 (7007). Was this intentionally fixed?

**Comment by abnerlee** [comment]
fixed in 1.7.5
