### ISSUE TITLE
The problem of cutting a line in a paragraph

### ISSUE THREAD

**Issue by sky-279** [typora/typora-issues#5636]
When I use the Ctrl + x shortcut to cut a line in a paragraph, some of the characters in the first line are affected.
version  1.5.8   on Windows 10
![potplayer](https://user-images.githubusercontent.com/60536042/218689141-db52a119-c937-4271-9dbe-20422e25597f.gif)

**Comment by sky-279** [comment]
@abnerlee

**Comment by sky-279** [comment]
Has anyone encountered similar problems?

**Comment by sky-279** [comment]
Windows11 same problem

**Comment by abnerlee** [comment]
fixed in 1.7.5
