### ISSUE TITLE
Pre-1.5.x behaviour of Shift+Tab inside code fences

### ISSUE THREAD

**Issue by horseshoe107** [typora/typora-issues#5637]
Before version 1.5.x, if I selected a block of text inside a code fence and then pressed Shift+Tab, this would cause the block to reflow its indentation based on the syntax. That is, based on the preferences set for code fence indent size, it would change the indentation level for every line to match that preference.

I've just updated to 1.5.8 and I notice this behaviour has now changed by design. Shift+Tab de-dents the entire block, which is fair enough as it is similar behaviour to many other IDEs/editors.

The only problem for me is that the previous behaviour was really useful. Is there any keyboard shortcut or menu item to replicate the previous behaviour, or is it removed?

**Comment by abnerlee** [comment]
Now shift+tab is unified in Typora which do "outdents" in code blocks and other blocks such as lists, etc.

Could you provide a sample code snippet and code language that support reflow indentation in previous Typora versions?

**Comment by horseshoe107** [comment]
Hi, I have v1.4.8 installed with the following preferences set:
Markdown->Code Fences->Indent Size for Code 2

With the following markdown example:
```c++
int main(void)
{
  printf("natural indent level");
      printf("manually indented too far");
}
```

Select the entire code fence text, press shift-tab and this results in the indentation reflowing (with indent amount per level controlled by the preferences).

**Comment by Sean-214** [comment]
+1

**Comment by horseshoe107** [comment]
As of version 1.5.9, it seems the previous behaviour can be restored in Preferences->Markdown->Code Fences, selecting "Use Shift+Tab to auto indent selected code"

Thanks!
