### ISSUE TITLE
Unable to import docx file into Typora. Results in "Unknown option --atx-headers" error

### ISSUE THREAD

**Issue by SamuelMiller** [typora/typora-issues#5639]
Using the latest version of Typora (Version 1.5.8 (6707)) and pandoc 3.1, I am unable to import a docx file on Mac (Catalina OS). I get the following error:

Import Failed
Unknown option --atx-headers.
Try pandoc --help for more information.

**Comment by SamuelMiller** [comment]
Update: there are several other formats I am not able to import into Typora including rich text.

**Comment by abnerlee** [comment]
We will fix this. You can use Pandoc 2.19.2 before our update

**Comment by abnerlee** [comment]
fixed in 1.6
