### ISSUE TITLE
File is not opening if it is empty

### ISSUE THREAD

**Issue by a-ctor** [typora/typora-issues#564]
I figured out what was causing my #559 and #560 issues.

If typora is opening an markdown file which is empty it does not display the file as being opened but instead displays an `Untitled` file which has not location on disk. Saving this document does not save the opened file but instead prompts you to choose a save destination.

This bug effects the open file dialog, the drag and drop opening and opening a file via command line.

Windows x64 - newest version

**Comment by abnerlee** [comment]
In my testing, it should be fixed in new release
