### ISSUE TITLE
[Feature] Profile option to not save recent file in mac system and image default stype

### ISSUE THREAD

**Issue by alivk** [typora/typora-issues#5641]
1. Now we have to go to File -> Open Recent -> Clear Items every time.
    Is it possible to add a option to permenantly not save those ?
2. Currently if we need a consistent image style
    I have to add 
```
<img src="abc.png" alt="image-20220809154354681"  style="float:left;width:600px" />
```
but this has to be very manual and if we copy whole article from one typora md to another
sometimes it is not display images, it show as random code, this is a bug
 so may i know if can add a default image option for all html image style.

**Comment by abnerlee** [comment]
fixed in 1.7.5
