### ISSUE TITLE
The custom image uploading shortcut does not take effect

### ISSUE THREAD

**Issue by jiaxinonly** [typora/typora-issues#5642]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The custom image uploading shortcut does not take effect.

**To Reproduce**
1. Set custom shortcut keys in Preferences, modify the file and save.
![image](https://user-images.githubusercontent.com/57223696/220530344-7eabec87-9d60-4262-a6cc-bcde4d691095.png)
2. Use the shortcut Ctrl+Shift+U to upload the image，prompts to set allow automatic uploading.
![image](https://user-images.githubusercontent.com/57223696/220530556-1c75640f-69b3-4939-b452-bc72a8e11180.png)
3.After changing the Settings, I tried uploading the picture again, but nothing happened.

**Desktop (please complete the following information):**
 - OS: Windows 10 64

**Typora Version**
e.g: 1.5.8

**Comment by abnerlee** [comment]
Does click upload image from menu bar works?

**Comment by jiaxinonly** [comment]
Menu bar click upload picture is valid. Only the shortcut keys are not responsive.

**Comment by abnerlee** [comment]
fixed in 1.7.5
