### ISSUE TITLE
Press Ctrl+shift+V to paste plain text will take effect twice

### ISSUE THREAD

**Issue by lb-fes** [typora/typora-issues#5643]
**Describe the bug**

I will get two reduplicative plain text by press Ctrl+shift+V.

Does not trigger this bug by right click.

It can be reproduced in built-in themes and custom themes.

**To Reproduce**
1. press Ctrl + C
2. press Ctrl+shift+V in typora
3. See error

**Expected behavior**
get one plain text

**Screenshots / Screencasts**

![Snipaste_2023-02-22_21-44-51](https://user-images.githubusercontent.com/51531901/220638252-63da3306-b381-4f71-be6f-fa85bcf22921.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.2604

**Typora Version**

1.5.3-dev

**Comment by abnerlee** [comment]
fixed in 1.5.8
