### ISSUE TITLE
Find Again doesn't work after selecting an item in the Articles sidebar

### ISSUE THREAD

**Issue by nk9** [typora/typora-issues#5644]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
You should be able to use the Cmd-G keyboard shortcut to search in a document for the item on the search pasteboard. This does work in Typora, but only if you've put focus in the main document view (or the find bar).

**To Reproduce**
1. Open a document in Typora which is in a directory with other text files
2. Open the Articles sidebar (Cmd-Ctrl-2)
3. Press Cmd-F to open the find bar.
4. Enter text which will appear in both documents (say "the") and press return
5. Select another document in the sidebar using the mouse
6. Search for the text in the new document using Cmd-G
7. Nothing happens.
8. Use the mouse to click in the document view and then press Cmd-G
9. If the string is found, it will jump to it as expected. If not, the "No Results" error string will appear.

**Expected behavior**
The search would happen in the new document and the viewport would jump to the first instance.

**Screenshots / Screencasts**
https://user-images.githubusercontent.com/3646730/220657980-1b85b742-2f61-4068-af72-71db331e8c29.mp4

**Sample Markdown File**
(This is not a rendering issue.)

**Desktop (please complete the following information):**
 - OS: macOS 12.6.2

**Typora Version**
Version 1.5.8 (6707)

**Additional context**

**Comment by abnerlee** [comment]
fixed in 1.5.11
