### ISSUE TITLE
outputFolder variable not working as expected

### ISSUE THREAD

**Issue by czietz** [typora/typora-issues#5646]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

**Describe the bug**
I realize that the `${outputFolder}` variable is not documented on typora.io. However, it exists in Typora 1.5.8, but it does not contain the expected contents:
![grafik](https://user-images.githubusercontent.com/9830685/221199760-23d1e219-cbb3-4234-946b-163944e44cc9.png)

This is the same as `${outputFileFullName}`, whereas I would have expected the _name of the folder_ where the output file resides.

**To Reproduce**
Define a custom export running a command that uses `${outputFolder}`.

**Expected behavior**
In line with the `${currentFolder}` variable, the `${outputFolder}` should contain the folder name of the output file (e.g., _C:\Users\username\Documents_) , not its file name.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2, 64 bit

**Typora Version**
- Version 1.5.8

**Comment by abnerlee** [comment]
fixed in 1.7.5

Added ${outputFolder} and ${outputFolderName}
