### ISSUE TITLE
Mermaid Diagram Can't Be Rendered Due to Presence of Word the Word 'remove' in the Markup

### ISSUE THREAD

**Issue by saden1** [typora/typora-issues#5647]
The following mermaid diagram can't be rendered. It looks like the word `remove` is being parsed and interpreted incorrectly.

```
flowchart LR
client("client") --> remove["remove"]
```

Actual result: 
```
ERROR: [Mermaid] this.indexOf is not a function
```

Expected result:
```mermaid
flowchart LR
client("client") --> remove["remove"]
```

Workaround:
Don't use the word 'remove' though this seems a bit odd since one wouldn't expect the diagram markup to be parsed and interpreted by anything other than Mermaid APIs or a syntax highlighting feature.

**Comment by abnerlee** [comment]
fixed in 1.6.5
