### ISSUE TITLE
Rectangle & Spectacle shortcuts are not working on the latest Typora 1.5.5

### ISSUE THREAD

**Issue by vinamelody** [typora/typora-issues#5649]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

Previously, I don't have any problem activating shortcuts from Rectangle & Spectacle app to make 2 Typora windows side by side. But after updating to Version 1.5.5, the shortcuts are not working anymore and even greyed out from the Rectangle app.

The shortcuts work in Typora 1.4.8.

**To Reproduce**
1. Open a new Typora document
2. Click on Rectangle app's menu bar
You will see this

<img width="411" alt="Screenshot 2023-02-28 at 10 42 21 AM" src="https://user-images.githubusercontent.com/990511/221740271-9f4f4257-3cee-48ae-aa4c-ed9d323271cd.png">

**Expected behavior**
Shortcut such as Option+cmd+left & Option+cmd+right should work on Typora windows

**Screenshots / Screencasts**
Attached above

**Sample Markdown File**
Works on empty file

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1 (22D68)

**Typora Version**
1.5.5

**Additional context**
-

**Comment by abnerlee** [comment]
It works in my test.

Could you check if you are using the latest Rectangle.app and is Typora window focused?
