### ISSUE TITLE
Ctrl + Right arrow skips to the next line

### ISSUE THREAD

**Issue by a-ctor** [typora/typora-issues#565]
`ctrl + right arrow` is jumping into the next line instead of the end of the word when positioned at the last word of a line.

Example text:

```
a
b
```

If the cursor is in the first line before the `a` and you press `ctlr + right arrow` you jump into the next line  instead of the end of the first line.

**Comment by singularitti** [comment]
Same issue here on a macOS 10.13, with Typora version 0.9.9.16.
-----
BTW, "Strg" is "CTRL" key in English, on a macOS, it is the "Command" key.

**Comment by abnerlee** [comment]
Merge into https://github.com/typora/typora-issues/issues/1164
