### ISSUE TITLE
[Feature] Add option for one-step deletion of inserted graphs (e.g., right-click menu).

### ISSUE THREAD

**Issue by SamuelMiller** [typora/typora-issues#5651]
It would be helpful to add a "Delete" option to the right-click menu that appears when right-clicking on a markdown-generated diagram (e.g., Mermaid.js). This would allow for the easy, one-step deletion of inserted graphs. Currently, deleting a graph, especially a complex one, requires a few steps. I also suggest adding a little trash icon on the upper right of the mermaid charts for deletion as Typora has for tables.

**Comment by abnerlee** [comment]
fixed in 1.7.5
