### ISSUE TITLE
Pressing Shift+Tab in a code block breaks indentation

### ISSUE THREAD

**Issue by Sean-214** [typora/typora-issues#5653]
**Describe the bug**
In previous versions, pressing Shift+Tab after selecting all in the code block did not break the normal indentation of the code. But now, each line will be unindent.

**Expected behavior**
Pressing Shift+Tab in a code block can't breaks indentation.

**Screenshots / Screencasts**

![Dingtalk_20230302175018](https://user-images.githubusercontent.com/10695861/222393511-87eecd56-c825-4f18-a222-a648ca12b1d0.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
1.5.8

**Comment by abnerlee** [comment]
duplicated with #5637
