### ISSUE TITLE
Frequent crash while saving

### ISSUE THREAD

**Issue by coderanger** [typora/typora-issues#5658]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Randomly about once an hour, Typora will crash while saving.

**To Reproduce**
Unknown.

I am editing a relatively small Markdown file in Source Code Mode, nothing interesting about it that I can see.

**Expected behavior**
To save the file and not crash.

**Desktop (please complete the following information):**
 - OS: macOS 12.6.3

**Typora Version**
e.g: 1.5.8

**Additional context**

[crash capture from macOS](https://github.com/typora/typora-issues/files/10917110/crash.txt)

**Comment by abnerlee** [comment]
Does reboot your macOS work?
