### ISSUE TITLE
Can't recognize list correctly when I paste into.

### ISSUE THREAD

**Issue by toaco** [typora/typora-issues#566]
There are something wrong when I copy the contents at https://docs.djangoproject.com/en/1.10/contents/ into Typora:
![image](https://cloud.githubusercontent.com/assets/19466181/23535133/742dfc04-fff7-11e6-9b70-4c0a9f908cc4.png)

- OS: Win10
- Typora version: 0.9.24

**Comment by Jefffffrey** [comment]
+1

**Comment by abnerlee** [comment]
Should be fixed in new release.
