### ISSUE TITLE
Code fenced blocks copied/pasted to MS Word, Gmail lose indention

### ISSUE THREAD

**Issue by ravenholt** [typora/typora-issues#5664]
**Description**
Code indention and text formatting does not copy/paste to other applications (tested MS Word, Gmail, Apple Mail).

**To Reproduce**
1. Use any built in theme
2. Create a code block with indented text/code.
```json
[
  { "key": "value"},
  { "key": "value"}
]
```
3. Copy the code block
4. Paste into GMail, MS Word, Apple Mail, etc.
5. The output formats the text, but without any indention (Gmail below)
![image](https://user-images.githubusercontent.com/3451969/224844825-afb241e9-7e57-4c03-a502-fc6236b30b73.png)

**Expected behavior**
The pasted output matches Typora / formats code blocks to keep the code indented.
![image](https://user-images.githubusercontent.com/3451969/224845026-16719ea2-89ec-4de9-8d05-8e1ca11b6e86.png)

**Desktop**
 - OS: MacOS Ventura 13.2.1 / M1

**Typora Version**
Version 1.5.9 (6726)

**Comment by abnerlee** [comment]
fixed in 1.7.5
