### ISSUE TITLE
Mac OS 修改快捷键失效

### ISSUE THREAD

**Issue by zy19970** [typora/typora-issues#5665]
**Describe the bug**
Mac OS 修改快捷键失效

**To Reproduce**
按照[要求](https://support.typora.io/Shortcut-Keys/#macos)修改完毕快捷键以后，拷贝快捷键修改为ctrl+c，程序会实现原有的“复制”功能而不是修改后的“拷贝"功能。

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Mac OS 13.2.1
 - Mac mini2

**Typora Version**
版本1.4.4 (6547)

**Comment by abnerlee** [comment]
What's the difference between 拷贝 and 复制?
