### ISSUE TITLE
Garbled paths in "Reopen" dialog on Linux

### ISSUE THREAD

**Issue by nursoda** [typora/typora-issues#5667]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/
----

**Describe the bug**
When I press Ctrl-P (or use the menu to "Open Quickly", I cannot reopen a file saved and closed a minute ago. The path is garbled as shown in the screenshots below.

**To Reproduce**
0. Edit a file, save it, close it, (close Typora)
1. (open Typora), press Ctrl-P and Enter
2. Error loading file

**Expected behavior**
Paths should not be garbled.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/8425483/225404210-ae6a74c0-742d-4835-9e74-f06a706eea32.png)
![image](https://user-images.githubusercontent.com/8425483/225403295-bacd185a-2c53-46e6-85c0-ab0aadad3946.png)
![image](https://user-images.githubusercontent.com/8425483/225405123-d5d02838-bf28-48cf-973a-fe3de0093e5c.png)

**Sample Markdown File**
Not necessary, any file will do.

**Desktop (please complete the following information):**
- OS: Arch Linux using KDE Plasma 5.27

**Typora Version**
1.5.9

**Comment by abnerlee** [comment]
The md file will be added to "Open Recent" menu list in the first time you opened it. Could you tell me how you open the file in the first time? By double click the md file, or open in Typora's sidebar, or from Typora's File → Open menu, etc?

**Comment by nursoda** [comment]
I tested all cases, all mentioned files are in ~.:

- clear recent files list
- close and reopen typora
- create new file and save it
- close and reopen typora
- open existing file from menu→open
- close typora
- doubleclick a third .md file

Menu→recent, I see this:

![grafik](https://user-images.githubusercontent.com/8425483/226380820-c1074a70-0836-40fc-b4a4-902bf740d6eb.png)

**Comment by nursoda** [comment]
The observation that it works for some documents/paths, and not for other gave me an idea: Could it be that the bug only happens with paths that contain a symlink? I use a separate "data" partition. The idea was to be able to share "current worked on documents" between different OS'es (multi boot environment). Currently, I don't actually use it, but the setup remains. Most Linux distros would mount /home as separate partition. I decided against that since this has many unwanted side effects when switching between between different OS layouts such as in Arch vs. Ubuntu based ones, and between different Desktop Environments such as KDE Plasma vs. Cinnamon. So, I have /home/myuser in the root filesystem, but "~/Desktop" is a symlink to "/data/Desktop". Could this be the culprit for this issue?

**Comment by abnerlee** [comment]
Fixed in 1.5.10

Please clear all recent items in Recent menu, then only added one should be normal.
