### ISSUE TITLE
Updater does not update version information [Windows]

### ISSUE THREAD

**Issue by CaringDev** [typora/typora-issues#5668]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

Updater should update the version in the Windows Registry

**To Reproduce**

1. Install Typora in version X.Y.Z
2. Wait for an available update
3. Update through "Help -> Check updates..."
4. Windows registry (in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\<GUID>`) still lists X.Y.Z

**Expected behavior**
Registry is updated to contain actual version

**Desktop (please complete the following information):**
 - OS: Windows 11 x64

**Typora Version**
1.4.4 -> 1.5.9

**Additional context**
This is mainly useful for 3rd party products that (try to) keep installations up to date, e.g. [winget](https://github.com/microsoft/winget-cli/), [ManageEngine Desktop Central](https://www.manageengine.com/products/desktop-central/), ... as otherwise these keep nagging about a pending update.

**Comment by abnerlee** [comment]
fixed in 1.7.5

**Comment by abnerlee** [comment]
should be fixed in 1.8.6
