### ISSUE TITLE
Invoking `typora newfile.md` from command line leads to weird UX behaviour and a buffer that cannot be saved 

### ISSUE THREAD

**Issue by Latechneuse** [typora/typora-issues#5669]
Typora version: 1.5.8 on Linux 

I frequently launch typora from the command line  to edit a new file in a similar way I would do it with other text editors: 

`typora newfile.md`

## Current behavior: 

If `newfile.md` does not exist (which is my intention as I would like to create the file), typora behaves in the following unexpected way: 

- A popup appears saying "File does not exist at path …" [OK]
- After clicking OK, I can edit the file. If I then press Save (Ctrl+S or File -> Save) **nothing happens**. The file does not get created on disk, the content of the buffer **does not get saved**, and there is **no warning**
- If instead I use File -> Save As, **nothing** happens: No file picking dialog pops up. (This is only for completeness. Going through File -> Save As is anyway not the desired usage flow after running Typora from CLI with a new file name). 

So in effect I am locked out from saving the contents of the buffer as both methods (Save and Save As) are dysfunctional. 

## Expected behavior: 

- After invoking typora with `typora newfile.md` and entering something in the buffer, `newfile.md` should be created upon File -> Save and the contents of the buffer should be stored in that file. 

As typora is such a great editor, I would love this behavior to be smoothed out :). Thanks for your great work.

**Comment by abnerlee** [comment]
fixed in 1.5.11
