### ISSUE TITLE
Image centering not work?

### ISSUE THREAD

**Issue by Geliv** [typora/typora-issues#567]
I'm trying use `css` to control the image size and alignment in exported `html` file.
```css
<img style="float: center; zoom: 50%" src="Fig/fig.png">
```
But the problem is: this works fine for `left` and `right`, but not for `center`. `align="center"` not work also.
Is this a bug?

Many thanks!

**Comment by abnerlee** [comment]
The exported html is `<img style="float: center; zoom: 50%" src="Fig/fig.png">`

And there's no `float:center` in css, should be caused by using wrong css styles
