### ISSUE TITLE
typora-root-url not support absolute path

### ISSUE THREAD

**Issue by calmwaves111** [typora/typora-issues#5672]
img path : D:/mydocument/life/personal/diary/assets/gg45f.jpg
md path : D:/mydocument/life/personal/diary/test.md
in the file test.md, 
typora-root-url: D:\mydocument\life\
I quote the image as follows
`![image1](/personal/diary/assets/gg45f.jpg)`
But it doesn't work properly

In fact, I already asked this question, but it was closed  https://github.com/typora/typora-issues/issues/5595

**Comment by abnerlee** [comment]
fixed in 1.7.5
