### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by huoyan1231** [typora/typora-issues#5675]
**Describe the bug**
cant open typora

**To Reproduce**
just open Typora

**Desktop (please complete the following information):**
Windows 11 22621.1413

**Typora Version**
e.g: 1.5.9

**Additional context**
i can open typora with -no-sandbox
i already reinstall my windows and display driver
but i want solve it

**Comment by abnerlee** [comment]
Try open with typora --disable-gpu

> i can open typora with -no-sandbox

Or open with typora -no-sandbox
