### ISSUE TITLE
[Feature] Support for project-level configuration

### ISSUE THREAD

**Issue by leoleoasd** [typora/typora-issues#5676]
Allow setting and storing project-local configurations in project dir, something like `.typora`. Like #3109, but I think it's better to follow other IDE's ways (`.vscode`, `.idea`, etc.). Seperating environment-related configurations and others would be better (and provide a default `.gitignore` under `.typora` just like IDEA).

This can help, for example, if I'm writing my hexo blog post, I'll need a different place to store images than usual.

**Comment by abnerlee** [comment]
put into #3109
