### ISSUE TITLE
[Bug] Whitey theme rendering issue

### ISSUE THREAD

**Issue by ruoliu2** [typora/typora-issues#5677]
**Description**
When rendering whitey theme to pdf, the digits numbering beyond first digit would not show on pdf
<img width="1056" alt="Screenshot 2023-03-26 at 6 16 51 AM" src="https://user-images.githubusercontent.com/73366046/227772202-0c191f7f-86a3-4abd-910c-b96c1ac1f9eb.png">
as shown the numbering which should be 10, 11, 12 show as 0, 1, 2

**To Reproduce**
1. Select whitey theme on macos typora Version 1.5.10 (6746)
2. export as pdf

**Expected behavior**
should export s.t. the full numbering shows

**Screenshots / Screencasts**
<img width="1056" alt="Screenshot 2023-03-26 at 6 16 51 AM" src="https://user-images.githubusercontent.com/73366046/227772202-0c191f7f-86a3-4abd-910c-b96c1ac1f9eb.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1 (22D68)

**Typora Version**
typora Version 1.5.10 (6746)

**Comment by abnerlee** [comment]
fixed in 1.7.5
