### ISSUE TITLE
Cannot disable direct write

### ISSUE THREAD

**Issue by zhanhaikun** [typora/typora-issues#568]
No matter what I did in conf.user.json or conf.default.json, it seems to be nothing to do with Typora.
I want to set "directWirte" to false, so mactype will take over the render effect.

**Comment by abnerlee** [comment]
It seems direct-write is cannot be disabled after chrome 52+ (http://superuser.com/questions/1099938/enabling-mactype-for-chrome-52)

We will remove this option if we can not make this work.

Also, this might be helpful https://github.com/silight-jp/MacType-Patch

**Comment by abnerlee** [comment]
We are going to remove this option and related doc, since Chrome/Electron does not have such option anymore.

Related discussion I found:
https://productforums.google.com/forum/#!topic/chrome/CFttpwTyxBw
https://productforums.google.com/forum/#!msg/chrome/Q6QGBRvULbQ/lfe3Ot2ECAAJ

**Comment by eladkarako** [comment]
<code>--disable-directwrite-for-ui</code> <sub><a href="http://icompile.eladkarako.com/disable-direct-write-alternative-for-chrome/" title="#disable-direct-write Alternative For Google Chrome"><em>source</em></a></sub>
