### ISSUE TITLE
The start and end of line anchors cannot be used alone in Search with Regex.

### ISSUE THREAD

**Issue by Starmania** [typora/typora-issues#5680]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**
1. Open Search
2. Activate Regex mode
3. Search for `^` or `$` without anything else
4. No match will be found

**Expected behavior**
With `^`:
- Every start of line in the file should match

With `$`:
- Every end of line in the file should match

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
- 1.5.10

**Comment by abnerlee** [comment]
Typora does not render line start or line end, and currently search result can only return visible strings.

please try `^.` or `.$` instead.
