### ISSUE TITLE
[Feature] Support PicList for picture upload

### ISSUE THREAD

**Issue by Kuingsmile** [typora/typora-issues#5682]
[PicList](https://github.com/Kuingsmile/PicList) is a cloud storage/image hosting platform management and file uploading tool, which is based on the deep development of PicGo. It retains all the functions of PicGo while adding the synchronization of cloud-deleting feature to the album, as well as complete cloud storage management functions, including cloud directory viewing, file search, batch uploading, downloading and deleting files, copying various format file links, and image/markdown/text/video preview, etc.

Currently, my users can only use `custom command` to set PicList， however，this way can't replace the file link from to local position to remote link automatically. This problem makes my users feels not so convenience.

Can you guys add the support for PicList? The way to use PicList is completely the same as PicGo(app).

**Comment by abnerlee** [comment]
Same with PicGo (use http:// for upload) ?

**Comment by Kuingsmile** [comment]
> Same with PicGo (use http:// for upload) ?

yes, PicList anf PicGo use the same way to upload, which is a `http://127.0.0.1:36677/upload` interface. Same request param and same response struct.

**Comment by Kuingsmile** [comment]
@abnerlee  let me known if you need any more info

**Comment by abnerlee** [comment]
@Kuingsmile You can preview the support in 1.6.0-dev

**Comment by Kuingsmile** [comment]
> @Kuingsmile You can preview the support in 1.6.0-dev

@abnerlee  I download 1.6.0-dev and test it with PicList, it works pretty well, thanks for your work!
