### ISSUE TITLE
Image Quality Does Not Work!

### ISSUE THREAD

**Issue by HoeYeungHo** [typora/typora-issues#5685]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I was very excited to know that Typora 1.5 can adjust the quality of the exported images. As I mentioned on [this page](https://github.com/typora/typora-issues/issues/5539), I wanted the exported images to be sharper. After updating Typora 1.5 I couldn't wait to try exporting, but none of the adjustments seemed to work. I tried the Auto, Medium, High and Best configurations, but the exported images were the same size, resolution, etc. and did not make the exported images sharper because of the different parameters.

|                      |                             Auto                             |                            Medium                            |                             High                             |                             Best                             |
| :------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| Detailed information | ![Auto](https://user-images.githubusercontent.com/60749707/228924323-270881fb-5bad-4acd-a9b3-9ab1a1b4e98e.png) | ![Medium](https://user-images.githubusercontent.com/60749707/228924421-8769b3d1-6f21-40dc-839f-93b0ac83175e.png) | ![High](https://user-images.githubusercontent.com/60749707/228924484-849a4a1a-b808-4c43-ae0b-8974f4e32cce.png) | ![Best](https://user-images.githubusercontent.com/60749707/228924525-af5f5cca-b610-4144-8ab3-278619cfa5de.png) |

**Expected behavior**
When I adjust the image quality, the sharpness of the image can vary and can be **sharper than my current output**.

**Sample Markdown File**
I use [Typora 1.5 - Typora Support](https://support.typora.io/What's-New-1.5/) as the sample Markdown File.

**Desktop (please complete the following information):**

 - OS: Windows 11 (and my screen dpi is 1080P)

**Typora Version**
- 1.5.3-dev

**Comment by abnerlee** [comment]
The image quality are used when scale / resize the exported image after capture images from Retina / 2K / 4K displays. 

For 1080P screens, the dpi in images are same as dpi in screen. In other words, the best image qualities are same as the screenshot you attached on your devices, since we use the same logic to export images: render it and take a screenshot.
