### ISSUE TITLE
[Feature] Proxy with authentication

### ISSUE THREAD

**Issue by fandych** [typora/typora-issues#5689]
I purchased a license for my team, but our proxy server needs authentication. I lookuped all the documents on your website. It tells me that the Typora doesn't support proxy authentication. So could you please implement it?

Possible logic:
1. Using "proxy-server" for proxy server and host.
2. Provide a dialog for username and password if the proxy server needs authentication.
3. Use http header "Proxy-Authorization" for proxy authentication.

**Comment by abnerlee** [comment]
Typora will use your system proxy.

For Windows/Linux version, please also check this approach: https://superuser.com/a/1082709
