### ISSUE TITLE
[Bug] Typora window too large on 200% monitor in dual setup.

### ISSUE THREAD

**Issue by christianbrugger** [typora/typora-issues#5690]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I close and re-open Typora on my 200% scaling Monitor the Window size is way too large, going way beyond the screen.

I then have to move and resize the Window several times, to bring it back on screen, which is tedious.

**To Reproduce**
1. Setup 2 Screens in Windows, one with 100% and one with 200% scaling.
2. Open Typora via the Start Menu
2. Move Typora to a Monitor with 200% scaling
3. Make sure Typora is not maximized, resize it to fit on the screen nicely. Remember the position.
4. Close Typora.
5. Open Typora again via the Start Menu.
6. Bug: The Window size is not saved, it is way to large. Exactly 2x as large, moving outside the screen area.

**Expected behavior**
I expect the Typora Window to have the same size and position when opening it again.

**Screenshots / Screencasts**
Display Setup:
![image](https://user-images.githubusercontent.com/235346/230273800-62286a9d-db3c-44e9-b730-bec69e0de7e7.png) ![image](https://user-images.githubusercontent.com/235346/230273655-bdef4d1e-8bda-4303-b570-80ff38cb1fda.png) ![image](https://user-images.githubusercontent.com/235346/230275087-50e0501c-be37-43af-aeff-daf65dcb37af.png)

First open on 200% monitor:
![4_first_open](https://user-images.githubusercontent.com/235346/230274881-c6a73b14-f499-4dec-95de-34eaea2865fe.png)

Re-openeing it, showing the issue:
![5_reopen_typora](https://user-images.githubusercontent.com/235346/230274915-5fabc284-2108-40fb-b0c0-60d3495db3a6.png)

**Sample Markdown File**
It happens with any file or without any file opened.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Dual Monitor Setup with 100% and 200% scaling.

**Typora Version**
e.g: 1.5.10

**Additional context**

It only happens on a dual monitor setup.
When I only use the 4k screen with 200% scaling everything works.

**Comment by abnerlee** [comment]
may relates https://github.com/electron/electron/issues/10862

**Comment by abnerlee** [comment]
Does it fixed in 1.7.5?

**Comment by christianbrugger** [comment]
Yes it is indeed fixed in 1.7.5 😃
