### ISSUE TITLE
[Bug] Formula (commutative diagram) using "\xymarix" not turning white in dark mode

### ISSUE THREAD

**Issue by ChungLeeCN** [typora/typora-issues#5691]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Commutation diagrams created with '\xymarix' or '\begin{xy}---\end{xy}' in a formula environment ('$$---$$') always appear black, even with night mode. At this time, it is impossible to see the graphics clearly in night mode. This bug is not only exists in third-party themes or css.

**To Reproduce**
for example:
$$
\xymatrix{
U \ar@/_/[ddr]_y \ar[dr] \ar@/^/[drr]^x \\
& X \times_Z Y \ar[d]^q \ar[r]_p
& X \ar[d]_f \\
& Y \ar[r]^g & Z }
$$

**Expected behavior**
Commutation diagrams created with '\xymarix' or '\begin{xy}---\end{xy}' should appear white when in night mode.

**Screenshots / Screencasts**
![2023-04-08_230642](https://user-images.githubusercontent.com/130234319/230752022-7f8d9aa3-5581-415c-a200-c3e56f3b6c66.png)

The upper subplot is the formula in light mode, and the lower subplot is the formula in dark mode. As you can see, the color of the commutation diagram does not change to white in dark mode.

**Sample Markdown File**
[example.md](https://github.com/typora/typora-issues/files/11184709/example.md)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
e.g: 1.5.10

**Comment by abnerlee** [comment]
fixed in 1.6.5
