### ISSUE TITLE
How do I make lines in mermaid diagrams curved 

### ISSUE THREAD

**Issue by qiulang** [typora/typora-issues#5694]
Here is a picture to show what I mean, for all typora version (including latest 1.5.11), the lines in mermaid diagrams are straight

<img width="608" alt="diagram in typora" src="https://user-images.githubusercontent.com/516243/231405270-c652945a-f3de-4c50-8d79-4386d3a33be0.png">

But the **same** md file on my gitlab server shows like this, the lines are curved and look more natural 

<img width="666" alt="diagram in gitlab" src="https://user-images.githubusercontent.com/516243/231407155-2356c39b-60ef-4374-85dd-fe3f1b633429.png">

So is there a setting for that or typora has not implemented that yet ?

**Comment by abnerlee** [comment]
Could you provide your sample mermaid code?

**Comment by qiulang** [comment]
```mermaid
graph TB
CM --> N{{HTTP or MQ 通知 CR-Web}}
N -- HTTP 同步通知 --> CR-Web
N -- MQ 通知 --> M1{{同步或者异步}}
M1 -- RPC同步 -->CR-Web
M1 -- 队列异步 -->CR-Web
CR-Web --> E{{是否需要通知CR}}
E -->|否| F[完成数据库更新并结束流程]
E --> |是 : MQ通知 |M2{{同步或者异步}} -- RPC同步 -->CR
M2 -- 队列异步 -->CR
CR -. 同步结果返回 .-> CM
```

As you can see here, it also shows the lines in curved.

**Comment by qiulang** [comment]
Not sure if you can see mermaid code, let me write it again,

```
graph TB
CM --> N{{HTTP or MQ 通知 CR-Web}}
N -- HTTP 同步通知 --> CR-Web
N -- MQ 通知 --> M1{{同步或者异步}}
M1 -- RPC同步 -->CR-Web
M1 -- 队列异步 -->CR-Web
CR-Web --> E{{是否需要通知CR}}
E -->|否| F[完成数据库更新并结束流程]
E --> |是 : MQ通知 |M2{{同步或者异步}} -- RPC同步 -->CR
M2 -- 队列异步 -->CR
CR -. 同步结果返回 .-> CM
```

**Comment by abnerlee** [comment]
duplicated with #1632

Please see https://support.typora.io/Draw-Diagrams-With-Markdown/#global-mermaid-options
