### ISSUE TITLE
[Feature] Add Description after an image

### ISSUE THREAD

**Issue by AlbertoVf** [typora/typora-issues#5696]
# UseCase

I want to be able to add descriptive text for an image below it and be able to apply a `css` format to it.

# Current Behavior

The images are included in a `span` which in turn is included in a `p`. I can't select the text that follows the image, only the text that follows the paragraph that contains the image

# Desired Behavior

- To do this, add a `>` under the image and write the text.

- Include a class tag for `p` elements that contain an image, so that you can make a CSS selector with the image element and its description.

**Comment by AlbertoVf** [comment]
![original](https://user-images.githubusercontent.com/26661334/231829652-46a9a81b-180e-4b29-9c6b-cab60b23b19b.png)
Original HTML code


![featured](https://user-images.githubusercontent.com/26661334/231829788-97fc6c2b-2776-4ac5-b1f1-bc068ae75bb4.png)
Featured HTML code: include the new class md-content-img

**Comment by abnerlee** [comment]
put into #249 for caption support.
