### ISSUE TITLE
[Feature] Change arrows <-- to ⟵ in pseudocode code blocks

### ISSUE THREAD

**Issue by hexaquarks** [typora/typora-issues#5698]
For code blocks of language pseudocode, it would be nice to have a processor that changes either <-- to a left arrow or <- to a left arrow ⟵, and similarly with the right arrow ⟶.

For instance
```
Merge(A, p, q, r)
  n_1 <-- q - p + 1
  n_2 <-- r - q
    do L[i] <-- A[p + i - 1]
```
to
```
Merge(A, p, q, r)
  n_1 ⟵ q - p + 1
  n_2 ⟵ r - q
    do L[i] ⟵ A[p + i - 1]
```

### Utility of this feature

Arrows in pseudocode are extensively used. It is infrequent that you'll encounter a pseudocode snippet without arrows, given that something as fundamental as a variable assignment is expressed with the arrow operator.

This should probably be low-cost to implement development wise and since Typora is used by many computer scientists, mathematicians, and software engineers this would be a practical implementation.

**Comment by nk9** [comment]
Yes, modifying the text is not the right solution here. I use [Fira Code](https://github.com/tonsky/FiraCode) as my code font. It has arrow ligatures, among lots of other goodies. You can [modify your user CSS](https://support.typora.io/Add-Custom-CSS/) to make code blocks use Fira Code or any other code font:

*themes/base.user.css*
```
code,
pre {
    font-family: "Fira Code", monospace;
}
```

**Comment by abnerlee** [comment]
duplicated with #1115

And yes, using some monospace font can also achieve this.
Or, you can use tools like TextExpander .
