### ISSUE TITLE
Code fences without language copy as math in HTML

### ISSUE THREAD

**Issue by RyanNutt** [typora/typora-issues#570]
When copying HTML from a page with code fences without a specified language the code is wrapped in a &lt;p class='math-block'&gt;&lt;/&gt; rather than in pre and code tags. I think this is an issue since upgrading to 0.9.24. Don't remember it happening previously.

This is the markdown that I'm trying to type in.
<pre>
```
public void thisWillShowUpAsMath() {
  
}
```

```java
public void thisWillWork() {
  
}
```

</pre>

And here's the HTML that it's copying.

<pre>
&lt;p class='math-block'>$$public void thisWillShowUpAsMath() {
  
}$$&lt;/p>

&lt;p>&lt;/p>

&lt;pre>&lt;code class='language-java' lang='java'>
public void thisWillWork() {
  
}
&lt;/code>&lt;/pre>
</pre>

**Comment by abnerlee** [comment]
Fixed I think
