### ISSUE TITLE
[Feature] Scrollbar is thin

### ISSUE THREAD

**Issue by Jingzhenzxz** [typora/typora-issues#5707]
拖动滚动条时需要仔细把鼠标点在滚动条上，而滚动条很细，所以比较麻烦，最好让我们把鼠标甩到屏幕右边就可以直接点击到滚动条，不需要瞄准。
![滚动条](https://user-images.githubusercontent.com/47069834/233936105-44bc835e-d036-4ebf-8bb9-e2587c8aec7c.gif)

**Comment by abnerlee** [comment]
fixed in 1.7.5

**Comment by Jingzhenzxz** [comment]
> fixed in 1.7.5

@abnerlee 这个问题又出现了。

**Comment by abnerlee** [comment]
@Jingzhenzxz could you provide a screencast?
