### ISSUE TITLE
[Feature] Add fall Mermaid.js support for fab icons

### ISSUE THREAD

**Issue by SamuelMiller** [typora/typora-issues#5708]
Please consider adding full support for fab icons in Marmaid charts, so that something like the following can fully render:

graph TD;
  A[[fa:fa-user-tie Mr Goh - President]]:::lightcoral --> B(fa:fa-user-tie Mr Chu - Vice President);
  A --> C(fa:fa-user-tie Mr Tan - Secretary);
  B --> D([fa:fa-money-check-alt Finance Manager]);
  B --> E([fa:fa-laptop-code IT Manager]);
  B --> F([fa:fa-users HR Manager]);
  
  style A fill:lightcoral, stroke: black;
  style B fill:orange, stroke: black;
  style C fill:orange, stroke: black;
  style D fill:lightblue, stroke: black;
  style E fill:lightblue, stroke: black;
  style F fill:lightblue, stroke: black;

**Comment by abnerlee** [comment]
duplicated with #286
