### ISSUE TITLE
[Feature] Options to config MathJax's alignment of displayed equations as 'left'

### ISSUE THREAD

**Issue by hchuanqi** [typora/typora-issues#5711]
according to mathjax's doc,
there is an option to config the alignment of displayed equations to be `"left"`, `"center"`, or `"right"`

```javascript
MathJax.Hub.Config({
    displayAlign: "left"
});
```

could this be accessible in typora?

https://docs.mathjax.org/en/v2.4-latest/options/hub.html

**Comment by abnerlee** [comment]
We use MathJax 3 which does not have the align option.

Also, we do not want to introduce too many options since there are already many options in Typora
