### ISSUE TITLE
Page Size is not honored when Exporting to PDF (Letter instead of A4)

### ISSUE THREAD

**Issue by Sieboldianus** [typora/typora-issues#5712]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When exporting to PDF, the PDF-Export preferences for Size A4 are not honored. The exported PDF is Letter size (8.5x11in).
When _printing_ to PDF, the Markdown file is correctly printed to a A4-Size PDF.

**To Reproduce**
1. Open a new Markdown file in Typora
1. Go to 'File/Preferences/Export/PDF' and verify that "Paper Size" is set to A4
2. Click on 'File/Export/PDF'
3. Click Ok
4. Open PDF, see that it is in format letter size

**Expected behavior**
The PDF is exported in A4 size.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/13646666/235108218-4db3fab2-8ea1-4e97-967e-6da8758564af.png)

**Sample Markdown File**
This applies to any Markdown file.

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 22H2

**Typora Version**
1.5.12, installed via Chocolatey

**Comment by abnerlee** [comment]
Does change to other page size, then change back to A4 works?

**Comment by Sieboldianus** [comment]
Ah, yes, that did it!

By the way, I tested this on two different computers with Typora, both show the same behaviour.

Good to know a workaround. Many thanks!

**Comment by alistairjames** [comment]
Same issue, also resolved by the 'change page size and change back' work-around on Windows and Ubuntu:
Windows 10, Typora 1.5.12
Ubuntu 20.04, 1.5.10 from repository https://typora.io/linux

**Comment by abnerlee** [comment]
should be fixed in 1.6.6
