### ISSUE TITLE
Support for function (and data) plotting.

### ISSUE THREAD

**Issue by LFWarsen** [typora/typora-issues#5714]
I feel like in addition to mermaid.js it would be beneficial to be able to plot functions and potentially even data.

I personally use Typora mostly for taking notes and writing summaries during lectures. I find myself wanting a visual representation of different functions, probability distributions for instance, quite often. It would be nice to have some way of plotting math functions quickly and with little effort.

There might be a suitable library for it already, however mermaid.js does not appear to support this functionality at this time.

**Comment by abnerlee** [comment]
put into #1138
