### ISSUE TITLE
Task Status in sublists/nested lists not changeable via menu/shortcut

### ISSUE THREAD

**Issue by tmmmmm** [typora/typora-issues#5716]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
If a task exists as a sublist/nested list and the parent is not a task itself, the Status of the Task can not be changed via the menu or shortcut. The status can be changed via md and mouseclick, though. It is accessible also, if the parent list is a task list itself

**To Reproduce**
1. Set cursor to line that is nested in an ordered/unordered list.
2. Go to 'Paragraph'
3. 'Task Status' is not accessible

**Expected behavior**
The task status should be accessible.

**Screenshot**
![Screenshot 2023-05-04 at 08 43 42](https://user-images.githubusercontent.com/51310587/236129784-bd8ed7bb-b467-4905-8a15-132cf6a4caaf.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 12.6.5

**Typora Version**
1.5.14

**Comment by abnerlee** [comment]
fixed in v1.6.5
