### ISSUE TITLE
Left multi-line math block alignment

### ISSUE THREAD

**Issue by LFWarsen** [typora/typora-issues#5717]
I would like to have the option to set the alignment for multi-line math blocks to the left as opposed to always being centered. I would suggest this being on a per-block basis with maybe a default alignment setting in preferences.

In some cases having them centered is nice, but I usually prefer left-alignment and I simply haven't found any successful way of accomplishing this even after searching online and trying different things by tinkering with the MathJax configuration.

I personally don't really care about right-alignment, but if this feature were implemented it would only make sense to round it out and have the option for either left, right or center.

**Comment by siddhpant** [comment]
![image](https://user-images.githubusercontent.com/25429745/236634578-cec81170-1bd1-4ae2-82a1-4ba547d9286d.png)

**Comment by abnerlee** [comment]
duplicated with #5711
