### ISSUE TITLE
Unable to create task lists in default view mode

### ISSUE THREAD

**Issue by Warrost** [typora/typora-issues#5719]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I can't seem to produce task lists in Typora.
Different variations (eg. '-[ ]') don't work either.
Using the task list shortcut (CTRL + SHIFT + X) works however.

**To Reproduce**
1. Open an empty/new Typora file
2. Ensure Source Code Mode is *not* enabled
3. Try to type '- [ ]'
4. Immediately after typing '-' it creates an unsorted list 

**Expected behavior**
I should be able to create task lists as described [here](https://support.typora.io/Markdown-Reference/#task-list)

**Sample Markdown File**
[example.md](https://github.com/typora/typora-issues/files/11439121/example.md)

**Desktop (please complete the following information):**
 - Windows 10, 22H2

**Typora Version**
- 1.5.12

**Comment by wondersphere** [comment]
You need to add a space after the  square brackets ("- [ ] ") and it will be converted to a checklist.

**Comment by Warrost** [comment]
@wondersphere 
My bad, you're completely right.
