### ISSUE TITLE
Bug: Header and footer placement do not respect left and right margin

### ISSUE THREAD

**Issue by siddhpant** [typora/typora-issues#5721]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

## Bug description

Header and footer are centered with respect to the full width of the page, but it should actually be centered in between the margins.

## To Reproduce

1. Change PDF export margins to be unequal (30mm left, 15mm right)
2. Set a long header for the file in YAML.
3. Export to PDF.
4. See header placement in PDF.

**Expected behavior**

Header centered in the area where content is allowed.

## Screenshots / Screencasts

![Screenshot from 2023-05-10 22-27-41](https://github.com/typora/typora-issues/assets/25429745/6e125b0d-4b9d-42a1-b0c6-4b2d68e0dccc)

## Sample Markdown File

[header_test.md](https://github.com/typora/typora-issues/files/11444409/header_test.md)

## Version info

Linux v1.5.10

**Comment by siddhpant** [comment]
@abnerlee Thank you for the latest update!

It does greatly improve the centering, but still it is not *exactly* at center.

Here's how the export looks like now:

![Screenshot from 2023-09-05 15-14-08](https://github.com/typora/typora-issues/assets/25429745/94e1c331-36c2-4d5c-bfcb-97fa0750b988)

Adding some more characters to show the slight off-centering:

![Screenshot from 2023-09-05 15-20-38](https://github.com/typora/typora-issues/assets/25429745/a34bb170-c7b9-4a17-beef-30e2db32db32)

Also, it can go out of margins, though I don't know whether that is intended or not.

![Screenshot from 2023-09-05 15-17-27](https://github.com/typora/typora-issues/assets/25429745/1b0af395-28ea-406f-9f5a-dc82597b68ba)

**Comment by abnerlee** [comment]
fixed in 1.7.5

**Comment by siddhpant** [comment]
Doesn't seem to change anything from 1.7.3.

![Screenshot from 2023-09-23 21-02-20](https://github.com/typora/typora-issues/assets/25429745/7bbcbe0b-a894-4c71-a404-da8d1a494a62)
