### ISSUE TITLE
<details> element gets parsed incorrectly when using github flavoured markdown.

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#5724]
- [x] Searched existing issues to avoid creating duplicates. (this is _not_ a duplicate of the several issues asking for a foldable element: if we ever get one, great, but this is a bug report specifically for `<details>` getting rendered incorrectly)
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/ (this is an actual bug. It doesn't matter if there's a support article.)

----

**Describe the bug**

(Refiled from https://github.com/typora/typora-issues/issues/5606 which got closed as duplicate of https://github.com/typora/typora-issues/issues/1939, "Allow empty lines and render Markdown inside HTML tags" which might _feel_ related, but is not this issue, and has been open for five years, so clearly no one is paying attention to it. This issue is purely about the bug in Typora's GHFM parsing, where all the correct elements are already in place, it just does _almost_ the right thing with respect to how it should work based on Github's way of treating the same data, rather than _entirely_ the right thing. It folds content incorrectly)

The `<details>` element with markdown in it, when using github flavoured markdown as markdown of choice, renders incorrectly.

**To Reproduce**

Create a new document, switch to source code mode, and fill it with:

<pre>This is a test

Preamble

&lt;details&gt;
  &lt;summary&gt;expand&lt;/summary&gt;
  
  ```python
  import math
  print(f'pi has value {math.pi}')
  ```
&lt;/details&gt;

Lead-out</pre>

Then turn off source code mode and note that Typora renders the content incorrectly, showing a clickable summary that expands to "nothing", and the detail's actual content showing _after_ the details element, with a rogue `</details>` test in grey at the end.

**Expected behavior**

The markdown inside the details element should get converted just like markdown in any other block context, and the details element should get rendered as an initially clickable summary only, expanding to reveal the converted markdown's content.

**Screenshots / Screencasts**

Expected result:

<kbd>
<img src="https://user-images.githubusercontent.com/177243/214983191-388ee571-8c10-4374-939e-ace19916bdfd.png">
</kbd>

Expected expanded result:

<kbd>
<img src="https://user-images.githubusercontent.com/177243/214983384-b967634a-e1ca-4a25-97f6-f709128a4fb8.png">
</kbd>

Actual result: 
 
<kbd>
<img src="https://user-images.githubusercontent.com/177243/214983106-33f83678-51de-4770-af6e-c316e1816de6.png">
</kbd>

**Sample Markdown File**

See above

**Desktop (please complete the following information):**
 - OS: windows 10 pro x64, 22h2

**Typora Version**
1.5.12

**Justification for wanting this fixed**

This is a paid product, not open source. If your product is based on GHFM, which you claim it is, then this is a bug that should have been fixed five years ago, and _should still be fixed now_ because your product claims to support a format that it only partially supports.

**Comment by Pomax** [comment]
What it looks like right here on github, the only authority for how github flavoured markdown should get parsed:

---

This is a test

Preamble

<details>
  <summary>expand</summary>
  
  ```python
  import math
  print(f'pi has value {math.pi}')
  ```
</details>

Lead-out

---

As you can see, this is not supposed to render the way Typora's currently rendering it, when using github flavoured markdown.

**Comment by abnerlee** [comment]
put into #1581 #1939

~~~
<details>
  <summary>expand</summary>
  
  ```python
  import math
  print(f'pi has value {math.pi}')
  ```
</details>
~~~

line 3 is an empty line, and, therefore the HTML tag is not correctly rendered (#1939).

**Comment by Pomax** [comment]
No, it isn't.

https://github.com/typora/typora-issues/issues/1939 is from 2018 and _has not had anyone working on it since_ so it's not addressed there: it's raised there, and has since been ignored.

Please reopen this, or update that issue by assigning it to someone so it can finally be fixed after five years. And if you don't have the capacity: _this is a bug in your GHFM parsing_, not a feature request, it's been around for five years, people have been complaining about it for five years, this should be a p1 at this point, not a "we'll get to it when we get to it" because history clearly shows _you are not getting to it at all_.

**Comment by Pomax** [comment]
(That might sound angry. That's because I am. If you _sell_ a product that claims to support GHFM, and you get reports about your implementation actually _not_ supporting GHFM, you should prioritise fixing that. Everything else derives values from how well you support GHFM. What you should _not_ do is punt on it for five years and counting)
