### ISSUE TITLE
When I type outside the YAML area, the mouse cursor jumps to the YAML area

### ISSUE THREAD

**Issue by Poison02** [typora/typora-issues#5725]
- [#3205 ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
**When I create a YAML region, I type on the next line (outside of YAML) and my cursor jumps to the previous line while typing.** 

**To Reproduce**
1. Create a YAML space like this: ---
2. type something
3. Move the mouse to the blank space below the YAML area
4. Enter content in the blank space, the cursor will jump

**Expected behavior**
As I type, the mouse cursor jumps to the previous line.

**Screenshots / Screencasts**

![typora-bug](https://github.com/typora/typora-issues/assets/106656220/fe3ba40e-ffec-46ec-b891-dbfad396dd1a)

**Desktop (please complete the following information):**
 - OS: [Windows 11 64bit]

**Typora Version**
version 1.5.10

**Comment by abnerlee** [comment]
duplicated with #3318
