### ISSUE TITLE
[BUG] Unsupport some rare Chinese words (无法支持部分生僻汉字)

### ISSUE THREAD

**Issue by emako** [typora/typora-issues#5727]
**Describe the bug**
无法支持部分生僻汉字，1个生僻汉字会显示成3个问号：���
这些汉字在记事本，word文档均正常显示。
尝试切换偏好语言为简体中文/繁体中文均表现异常。
举例：𠙶

**To Reproduce**
1. 复制𠙶，粘贴到typora
2. 复制[通用规范汉字表.docx](https://github.com/typora/typora-issues/files/11496012/default.docx)内容并粘贴到typora，可以大面积复现

**Typora Version**
e.g: 1.5.12

**Comment by emako** [comment]
![image](https://github.com/typora/typora-issues/assets/24737061/e203ef24-fe73-42cc-8529-ad7502180655)

**Comment by abnerlee** [comment]
Could you also attach the  KanjiSheet.md ?

**Comment by emako** [comment]
[KanjiSheet.md](https://github.com/typora/typora-issues/files/11512829/KanjiSheet.md)

**Comment by abnerlee** [comment]
> 复制𠙶，粘贴到typora
> 复制[通用规范汉字表.docx](https://github.com/typora/typora-issues/files/11496012/default.docx)内容并粘贴到typora，可以大面积复现

Does this happen in v1.6? In my test, copy / paste works fine:

https://github.com/typora/typora-issues/assets/1621242/84927a1e-d992-4166-b165-03e334e97798
