### ISSUE TITLE
Missing space line between paragraph and math formula block

### ISSUE THREAD

**Issue by 15040941306** [typora/typora-issues#5728]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.
- [x] Searched http://support.typora.io/

----

**Describe the bug**
There should be a space line between paragraph and math formula block.

**To Reproduce**
1. Input a paragraph
2. Enter a break line
3. Input a math formula 
4. Command + /
5. See error

**Expected behavior**

**Screenshots / Screencasts**

![Uploading image.png…]()

![Uploading image.png…]()

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: Both Windows10 Pro and MacOS13 find this error.

**Typora Version**
e.g: 1.5.14

**Additional context**

**Comment by skriptum** [comment]
Hi,

I have the same problem. Other Markdown Editors expect a empty line before and after a math block. in typora, as described above, after hitting Enter and starting a math block, a new line is not added automatically. 

The Result should look more like this:

```markdown
This is a test line

$$
\text{This is math}
$$

And now more text
```

Except in Typora, it looks like this:

```markdown
This is a test line
$$
\text{This is math}
$$
And now more text
```

This is a problem with most Markdown Renderers and other Editors and not easy to fix on our own,

Would love to have a solution for this. Thanks

**Comment by abnerlee** [comment]
duplicated with #1107
