### ISSUE TITLE
UTF8 files without BOM are wrongly detected as western encoding

### ISSUE THREAD

**Issue by Larivact** [typora/typora-issues#573]
Either

* default to UTF8, or
* let me pick the default encoding

**Comment by abnerlee** [comment]
@Larivact could you provide a "*.md" file which can reproduce this bug?

**Comment by Larivact** [comment]
$ echo It costs 3€. > demo.md
	$ file demo.md 
	demo.md: UTF-8 Unicode text
	$ typora demo.md
	
Typora shows `It costs 3â‚¬.`.

**Comment by abnerlee** [comment]
should be fixed in new release
