### ISSUE TITLE
`Rename or Move Image to...` cause Typora stuck and crash

### ISSUE THREAD

**Issue by bearbattle** [typora/typora-issues#5730]
- [x] Searched existing issues to avoid creating duplicates.

      No realated reported issues.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

      Can reproduce with native theme.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Use context menu to move or rename image will cause Typora stuck and crash.

**To Reproduce**
1. Open a file in Typora
2. Insert a image into the document
3. Rename the image by context menu `Rename or Move Image to...`
4. Typora slows down but respose
5. Repeat step 3
6. Typora stuck and soon crash halt

**Expected behavior**

Image renamed/moved without other side-effects.

**Screenshots / Screencasts**

![Reproduce](https://github.com/typora/typora-issues/assets/48974238/dcd9b4a5-1e34-47c6-8366-394aa985de82)

**Sample Markdown File**

[Test.md](https://github.com/typora/typora-issues/files/11528875/Test.md)

The image file is not attached as tested irrealativity with any specific image file.

**Desktop:**
 - OS: Windows 11 22H2 build 22621.1702

**Typora Version**

Typora 1.5 - 1.6.6 with built-in Github Theme

**Comment by abnerlee** [comment]
I'm not able to reproduce this on Windows 11. Does this happen for Typora 1.6.7?

**Comment by bearbattle** [comment]
OK, I've done with this issue. It is a software configuration cased issue.

For anyone's concern with the same issue, you can try to checkout the `Event Viewer` to get more detailed infomation about the crash. In my case, the evnet viewer reveals that the application error related to Typora:

![Event Viewer detail about the crashing](https://github.com/typora/typora-issues/assets/48974238/00a1f37f-6e9b-4b05-a8ff-3e266f9424dc)

It shows that this `winhook64.dll` related to `AISHU SyncDisk` has somthing to do with the crashing.

After searching for the web, I found the solution by editing the `HookInfo.ini` in the installing directory of `AISHU SyncDisk`, adding 

```ini
[Global]
Mode=1
```

which put the `winhook64.dll` to working at the `Minimal Mode` that keeping away from injecting other aplications.

Alternatively, you can add `Typora.exe` to the `[Exclude]` section to prevent the injection.

```
; By default, the Mode of [Global] section is 0, which make winhook to any processes except the [Exclude] section.
[Exclude]
Path0=C:\Program Files\Typora
Process0=Typora.exe
```

The problem get solved.

I am closing the issue.
