### ISSUE TITLE
In linux typora failed to load module "pk-gtk-module"

### ISSUE THREAD

**Issue by ashixu** [typora/typora-issues#5731]
In fedora 38.
When I open typora, it prompts the following error：
(base) [liukun@fedora ~]$ Gtk-Message: 00:04:23.766: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:04:23.767: Failed to load module "pk-gtk-module"
Gtk-Message: 00:04:23.767: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:04:23.767: Failed to load module "pk-gtk-module"
[2:0523/000423.779469:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: 没有那个文件或目录

**Comment by abnerlee** [comment]
You can follow https://www.tecmint.com/failed-to-load-module-canberra-gtk-module/ to install missing modules
