### ISSUE TITLE
Typo in the word "Greek" inside "Reopen with Encoding" menu

### ISSUE THREAD

**Issue by RobertPaauw** [typora/typora-issues#5733]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
In the list of encodings, both "Windows-1253" and "ISO-8859-7" are called _Geek_ instead of _Greek_ (with 'r').

**To Reproduce**
1. Go to 'File->Reopen with Encoding'
2. Error is clearly visible (see screenshot below)

**Expected behavior**
Should be named "Greek"

**Screenshots / Screencasts**
![geek encoding](https://github.com/typora/typora-issues/assets/58423245/066c57e7-4685-4373-846c-03b03c95a0aa)

**Sample Markdown File**
N.A.

**Desktop:**
OS: Windows 10 64bit (22H2, build 19045.2965)

**Typora Version**
1.6.6

**Additional context**
N.A.

**Comment by nk9** [comment]
Not seeing this menu on macOS. Is this a Windows-only menu, or has the feature been removed?

**Comment by abnerlee** [comment]
It is Windows only. macOS always use unicode.

**Comment by RobertPaauw** [comment]
Fixed in version 1.7.3 👍 

![greek encoding](https://github.com/typora/typora-issues/assets/58423245/3f9a446e-e0ec-46b4-88e7-303c5fe2f89c)
