### ISSUE TITLE
设置代码块默认语言无效

### ISSUE THREAD

**Issue by moroal** [typora/typora-issues#5734]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
偏好中设置了代码块的默认语言，下次ctrl shift k插入代码依然无默认语言，需要自己选择；

**To Reproduce**
1、偏好中设置了代码块的默认语言c++
2、返回编辑
3、ctrl shift k插入代码

**Expected behavior**
插入的代码用c++语法高亮；实际：无此效果

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
win10

**Typora Version**
1.6.6

**Additional context**

**Comment by abnerlee** [comment]
Please also set "Apply Default Code Language When"
