### ISSUE TITLE
Cant't save the sort mode

### ISSUE THREAD

**Issue by GMYXDS** [typora/typora-issues#5738]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
每次打开一个文件夹，文件夹里面包含很多md文件，每次都要手动调整排序模式，
每次进去默认都是按照时间升序，然后手动调整到按照字母排序升序
关掉这个文件夹，再次打开，还要手动调整一次

**To Reproduce**
1. 打开一个包含2个md以上的文件夹
2. 修改排序模式为非默认
3. 关闭文件夹
4. 再次打开，排序模式又自动恢复到了默认模式，没有保存最后一次的模式

**Expected behavior**
排序模式能够保存，记住最后一次的选择

**Screenshots / Screencasts**
无

**Sample Markdown File**
任何文档

**Desktop (please complete the following information):**
无
**Typora Version**
最新

**Additional context**
无

**Comment by abnerlee** [comment]
fixed in 1.7.5
