### ISSUE TITLE
Function of Ctrl+left and Ctrl+right fails in inline math.

### ISSUE THREAD

**Issue by peetteerr** [typora/typora-issues#5741]
OS:win11 typora version:1.6.1dev
Usually Ctrl+left and Ctrl+right keystrokes should make your cursor move word by word instead of character by character as only left and right keystrokes do. **This function fail when typing in the inline math area i.e. between two dollar signs**. however, this function works well in normal typing mode and display mode math 
p.s For failing I mean the program seemingly treads the whole inline math block as a single word and jumps the cursor completely over the block

**Comment by abnerlee** [comment]
duplicated with #4959
