### ISSUE TITLE
Can't remove list formatting when pasting from Notes

### ISSUE THREAD

**Issue by plufz** [typora/typora-issues#5744]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I paste an indented list item of any kind (checklist, bulleted, dashed) from Apple Notes into Typora the item is parsed into this markdown `- - Item` which creates an item that always will have indentation that can't be removed (without editing the source) and it will always be checked as "Unordered list" however you try to toggle the menu item (the bullet/dash will toggle though).

**To Reproduce**
1. Go to Apple Notes
2. Create a list item
3. Indent the list item
4. Copy the list item and paste into Typora
5. Try to toggle "Unordered list"
6. Click "List Indentation -> Outdent"
7. See that "Unordered list" is still ticked and that the item is still indented

**Expected behavior**
The item should turn into unformatted text without indentation.

**Screenshots / Screencasts**
<img width="335" alt="Screenshot 2023-06-05 at 11 58 59" src="https://github.com/typora/typora-issues/assets/6817275/4367345f-6f97-42d6-b27b-e8f484072126">

**Sample Markdown File**
```
Normal test
- - list item that can't be outdented
  - - list item that can't be outdented
```

**Desktop (please complete the following information):**
 - OS: macOS ARM

**Typora Version**
Version 1.5.14 (6769)

**Comment by abnerlee** [comment]
fixed in 1.7.5
