### ISSUE TITLE
[Feature] Add "Show Outline Popover" as a menu item as well (to allow a shortcut)

### ISSUE THREAD

**Issue by jaekyeom** [typora/typora-issues#5746]
Hi,

Currently, there is "Show Outline Popover" at the top right corner of each window.
I think it is useful, but it is not easy to invoke.
Could you please add that function as a menu item as well, so that users can assign their shortcuts?

Thank you!

**Comment by Lawrence-of-AnKing** [comment]
I ask for the same issue like you by Feedback, no answer yet, any other way for this except the "Both View Theme"?

**Comment by acupoint** [comment]
Same need, troubled by clicking the small icon on the top left corner every time.

**Comment by abnerlee** [comment]
fixed in 1.7.5
