### ISSUE TITLE
Behavior when typing headings

### ISSUE THREAD

**Issue by Hayao0819** [typora/typora-issues#5747]
When entering a heading, the previous behavior was to resize the text as soon as `#` was entered.

Recently, after installing Typora for the first time in a while, this behavior was not taking place. 

Am I simply misremembering this? 

Or is this a changed specification? If so, is there any way to revert back to the old behavior?

**Comment by abnerlee** [comment]
It is a misremembering. But we do plan to improve heading WYSIWYG in this way. put into #4739
