### ISSUE TITLE
Win 10/11打开Typora后一片空白，并且闪退

### ISSUE THREAD

**Issue by lif314** [typora/typora-issues#5748]
**Describe the bug**
在win10/11上双击打开Typora时，只出现一片空白，过1-2s自动退出了。尝试过的解决办法：（1）勾选兼容模式运行，无效；（2）从win10更换到win11，无效。
![image](https://github.com/typora/typora-issues/assets/63114150/8a3ea767-7c27-4b5a-b736-6f415b57135f)

**Typora Version**

1.5.2之后的每个版本都试过了，都不行

**Additional context**
我已经购买了该软件，之前使用一直没有问题。

**Comment by abnerlee** [comment]
You can also try https://support.typora.io/Trouble-Shooting/#windows
