### ISSUE TITLE
How do I change the font of a math equation?

### ISSUE THREAD

**Issue by EPTansuo** [typora/typora-issues#5753]
I have read the web page:
[https://support.typora.io/Add-Custom-CSS/](https://support.typora.io/Add-Custom-CSS/)
and
[https://support.typora.io/Custom-Font/](https://support.typora.io/Custom-Font/) 

But after I changing the  theme file (.css), however, the font do not change. 
I inspect the elements in typora, it seem that the math equation is just a svg file. I haven't learned much about the front end, I really don't know how  to do.

I would really like to know how to change the font in the math equation. Thank you very much for your answer

**Comment by EPTansuo** [comment]
I mean the font,  not the font size.

**Comment by abnerlee** [comment]
duplicated with #5523
