### ISSUE TITLE
A link to a chapter in a opened .md file

### ISSUE THREAD

**Issue by pauljurczak** [typora/typora-issues#5755]
I can link to a local .md file, e.g. `[microcontroller](./microcontroller.md)`. Within that file, I can link to a chapter, e.g. `[Graphics](#Graphics)`. I would like to have a combination of these two features, so I can link to a chapter in a local .md file, e.g. `[microcontroller](./microcontroller.md#Graphics)`. 

Right now, this link takes me to `microcontroller.md` file, but doesn't go to `Graphics` chapter.

**Comment by abnerlee** [comment]
It should be already supported in https://support.typora.io/What's-New-1.1/#file-link

What's your Typora version and operating system? Possible to provide a sample file of microcontroller.md?

**Comment by pauljurczak** [comment]
My version is 1.5.9 running on Ubuntu 22.04.2 amd64. I can't find what is the most current version. Attached is [microcontroller.md](https://github.com/typora/typora-issues/files/11726778/microcontroller.md).

The link behavior is as follows:
1. When `microcontroller.md` is not open, Typora opens it and positions `Graphics` entry in TOC at the top of the screen.
2. When `microcontroller.md` is opened, Typora switches to its window, but doesn't change the document position.

**Comment by abnerlee** [comment]
fixed in 1.7.5
