### ISSUE TITLE
[Bug] Can't Render and input chinese's char at right pos.

### ISSUE THREAD

**Issue by Rootjhon** [typora/typora-issues#5761]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

1. 新建一个Markdown
2. 输入以下内容
```
---
title: title name
date: ccee
categories: [xx,YY]
# Ref
# - https://www.

---
```
>  `---` 是 `jekyll` 自定义的博客语法

3. 尝试输入中文；（英文模式正常）
  ![](https://raw.githubusercontent.com/Rootjhon/img_note/empty/202306211614997.gif)

**To Reproduce**
3. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]

**Typora Version**
e.g: 1.6.7

**Additional context**

**Comment by abnerlee** [comment]
duplicated with #3318
