### ISSUE TITLE
Option to auto-embed images as HTML

### ISSUE THREAD

**Issue by kevquirk** [typora/typora-issues#5762]
I realise it's already possible to right-click on an image and select `Switch image syntax` > `HTML`. However, it would be good if there was an option to enable this globally in settings, so that images are auto embedded as HTML.

Further, it would also be good to have options to add things like `loading="lazy"`, classes, tags etc. to the HTML markup. This would allow much more flexibility when it comes to inserting images. For my use case, I currently have to:

1. Drag the image into Typora
2. Right-click and change syntax to HTML
3. Add `loading="lazy"` to the HTML so that images lazy load

If these kinds of settings could be set globally, it would be a huge time saver. 🙃

Thanks!

**Comment by abnerlee** [comment]
duplicated with #5752
