### ISSUE TITLE
data tooltip

### ISSUE THREAD

**Issue by diomed** [typora/typora-issues#5763]
I'd really like to see Typora supporting tooltips

I tried putting this CSS into theme file

https://gist.githubusercontent.com/w3collective/5b665643f670fe8095c507f07a19226d/raw/d73166065a2964ebdbbf038c47549c9f544667f1/html-css-tooltip.html

but I cant get it to show, as it does on web. Of course, when I enter that line in Typora.

Any ideas why it wont?

**Comment by diomed** [comment]
btw

if you ever listen to suggestions, including tippy library would be very neat.

Tippy in Typora. who could  resist that? 😃 

https://atomiks.github.io/tippyjs

**Comment by abnerlee** [comment]
Please check https://support.typora.io/Markdown-Reference/#footnotes
