### ISSUE TITLE
Cannot save any .md file with new update 1.6.7

### ISSUE THREAD

**Issue by stark1tty** [typora/typora-issues#5766]
- [X] Searched existing issues to avoid creating duplicates.

Nothing recent. 

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

I use the basic licensed application.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
Simply that the application has lost the ability to save any files. I use this application to isolate .md files that I need to work on in Obsidian. It is a secondary tool and I keep it bare bones for a reason. 

**To Reproduce**
Saving by menu or ctrl + save does not work, cannot close program and save. Does not work on any .md file. Restart did not help.

**Expected behavior**
Saving :(

**Screenshots / Screencasts**
Nothing unusual to see.

**Sample Markdown File**
I literally cannot save a new one. :(

**Desktop (please complete the following information):**
- Windows 11 64bit

**Typora Version**
- 1.6.7

**Additional context**
Going to try a fresh installation. I can still use all the files in other applications and obsidian as normal.

**Comment by abnerlee** [comment]
Could you provide log following https://support.typora.io/Get-Logs/ ?

**Comment by stark1tty** [comment]
IT seems to have resolved itself.
