### ISSUE TITLE
Unable to save changes to newly duplicated file that is immediately moved to another folder.

### ISSUE THREAD

**Issue by Ephron-WL** [typora/typora-issues#5770]
**Describe the bug**
After duplicating and optionally moving a file within the File view before saving changes to the file leads to an inability to save the file and a cycle of save and save file dialog prompts.

**To Reproduce**
1. In the Files view right click and select Duplicate
2. Rename the file.
3. Edit the file.  Do not save.
4. Move the document to another folder.
5. Click the document in the new folder.  
6. Prompted to save or discard.  Discard causes the changes to be lost (expected).  Click Save causes the bug.
7. Click save displays the save file dialog, which should not be required since Typora knows the location of the file and a new file doesn't need to be defined.  I click Cancel.
8. Click the file name again. repeat step 7 in a loop.  

Alternative steps causing a similar problem
1. In the Files view right click and select Duplicate
2. Delete the file just created through duplication
3. Click a file.  This causes the Save/Discard dialog box and loop if Save is clicked.  Why?  No changes had occurred to any document in Typora.  Only files are managed on the file system.

**Expected behavior**
If a click Save then the file should just save to the current location, which is correctly reflected in the File view.

**Desktop (please complete the following information):**
 Windows 10

**Typora Version**
1.6.7

**Comment by abnerlee** [comment]
I cannot reproduce this in version 1.7.6

If it still happens in v1.7.6 could you attach a screencast for us to reproduce this bug?
