### ISSUE TITLE
[Feature Request] Separate smart dashes and smart ellipses

### ISSUE THREAD

**Issue by aarond0623** [typora/typora-issues#5774]
Currently the Smart Dashes option in Typora also replaces ... with … I would like it if these could be separated into different options, since not all fonts have an ellipsis character that is readable or desirable.

**Comment by abnerlee** [comment]
Current behavior is same with "Smart Dashes" option of macOS. And we will try to avoid adding too much options in preferences panel. We will consider this if we receive more similar requests from our users.

**Comment by FeedFoodie** [comment]
This feature would be useful. It's very annoying that I have to reopen my md files in notepad afterwards just to change the ellipses back.
