### ISSUE TITLE
whitespaces should be eliminated from inputs when switching Input Source to English ABC

### ISSUE THREAD

**Issue by yulitao-byte** [typora/typora-issues#5775]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
1. Current Input Source is Chinese Pinyin, and I input 3 'k' charcters;
<img width="834" alt="Screenshot 2023-07-11 at 14 21 04" src="https://github.com/typora/typora-issues/assets/75112216/94b3550d-f6c2-4d35-afad-110230fbb292">
2. Press Ctrl + Space to switch Input Source to English ABC. Then the text will be 'k k k', noticing the spaces between 'k's. Then there it is. 🫱 The spaces are unwanted, and should be eliminated from inputs. Thanks!
<img width="892" alt="Screenshot 2023-07-11 at 14 22 16" src="https://github.com/typora/typora-issues/assets/75112216/faa1b918-9ff6-40a8-8a37-c3bb923df882">

**Desktop:**
 - OS: macOS 13.2.1

**Typora Version**
Version 1.6.7 (6865)

**Comment by abnerlee** [comment]
put into #5561
