### ISSUE TITLE
Numbering tables, figures (captions), whatever you want [Feature]

### ISSUE THREAD

**Issue by eriksdev1** [typora/typora-issues#5776]
I have searched extensively for auto numbering and I have found many alternative solutions and I have not been able to follow the steps of any solution to make it work.

I'm using Typora 1.6.7 (July 12, 2023)

My apologies, I had to give my two cents regarding an idea for auto numbering. I have found the general design so simple and elegant that maybe just a simple parse and replace could do the trick. I'm not aware of the inner workings of how markdown with latex equations is converted so beautifully and simple to .pdf.

Any way, this is my idea:       just give the user a setting to place some random text to be replaced by numbers (incrementally), and be reset if possible.

Something like:

Text to make a variable which will be incremented: MyFig# (to reset the counter: MyFig#>0     ,  
Replaced by: (in input field):  Fig. +NUMBER  // the user could type Figure. +NUMBER
Format: Bold/Italic (drop down menu)

+ a plus sign button to add any number of variables (three more lines of settings)

Text to make a variable which will be incremented: MyTable# (to reset the counter: MyTable#>0     ,  
Replaced by: (in input field):  Table. +NUMBER
Format: Bold/Italic (drop down menu)

+ another plus sign appears and is pressed

Text to make a variable which will be incremented: MyRandomString# (to reset the counter: MyRandomString#>0     ,  
Replaced by: (in input field):  Counter: +NUMBER
Format: Bold/Italic (drop down menu)

And maybe this simple configuration can be translated to a pandoc readable format (if typora uses it, don't know)

Also a question, it seems r markdown is more complete, first time I found this, can r markdown be used by typora ?

Thanks in advance, my apologies for long post

**Comment by abnerlee** [comment]
put into #249 for caption support.
