### ISSUE TITLE
Export to PDF: relative links to local files are completely broken

### ISSUE THREAD

**Issue by profhccaesar** [typora/typora-issues#5777]
When exporting to PDF links with relative path to local files are converted like this:
- Target is an existing *.md-file: relative path is converted to a `file://`-URL with absolute path
- Target is no md-file (e. g. PDF), but a md-file with same name exists: same as above
- Target is neither a md-File nor a same-name-md exists: relative path is converted into an `http://`-URL

This makes it impossible to release PDF's with references to other files.

I searched existing issues and found an old, always resolved issue describing at least part of the problem: [#2250 ("Links to local files don't convert to PDF")](https://github.com/typora/typora-issues/issues/2250).
Interesting is the last comment: "[...] PDF does not support relative link like file://../xxx.md, so will convert to absolute path."

However, this is not true; PDF does support relative links to local files. Similar to local links, they're implemented with a "goto", not an hyperlink. Don't know which PDF library Typora uses, but I checked it with Java iText. See the following developer references:
+ [iText refererence setRemoteGoto()](https://api.itextpdf.com/iText5/java/5.5.13.3/com/itextpdf/text/Chunk.html#setRemoteGoto-java.lang.String-int-)
- [iText sample application MovieLinks2](http://itextpdf.com/examples/iia.php?id=47)](https://www.demo2s.com/java/java-itext-pdf-chunk-setremotegoto-final-string-filename-final-int-pa.html)

# Steps to reproduce:

1. Create a directory / file structure like that:
    ```
    /home/myuser/example/
      +-- example.md
      +-- pdffrommd.md
      +-- pdffrommd.pdf
      +-- purepdf.pdf
    ```
    `pdffrommd.md`, `pdffrommd.pdf`, `purepdf.pdf` are any arbitrary files.

2. Enter the following content to `example.md`:
    ```markdown
    A [link to a PDF with existing md-file](pdffrommd.pdf)
    A [link to a PDF without existing md-file](pdfpure.pdf)
    ```
3. In Typora, export `example.md` to PDF:
    - `Datei` -> `Exportieren` -> `PDF` (in english should be like `File` -> `Export` -> `PDF`)

Open `example.pdf` in any PDF reader and check the links:
- First one is an hyperlink pointing to `file:///home/myuser/example/pdffrommd.pdf`
- Second is an hyperlink to `http://pdfpure.pdf`
![image](https://github.com/typora/typora-issues/assets/17450059/2425b5f3-400b-47e0-8fab-41a01e8f58e7)

# Expected result

The PDF-file should contain goto-actions to open the local files using original relative paths.

# Attachment
[example.zip](https://github.com/typora/typora-issues/files/12041765/example.zip)

# Desktop
- OS: x86_64 GNU/Linux 5.15.0-76-generic

# Typora Version
Typora for Linux (x64) version 1.6.6

**Comment by profhccaesar** [comment]
Tip: As temporary workaround the "PDF (LaTeX / Pandoc)"-export can be used with following options:
![image](https://github.com/typora/typora-issues/assets/17450059/a16d9910-85a4-4797-83f5-198f28dfb02c)
Full content of "extra arguments": 
```
--pdf-engine=pdflatex -V colorlinks=true -V linkcolor=teal -V filecolor=teal -V urlcolor=teal -V toccolor=gray
```
(For the "PDF engine field", see #5778)

The following packages are needed:
- `texlive-full` (not all subpackages are really needed, but if you have enough disk space, its easier to install the full package instead resolving all dependencies to subpackages)
- `pandoc`
- Template "Eisvogel", see [Github Wandmalfarbe / pandoc-latex-template](https://github.com/Wandmalfarbe/pandoc-latex-template)

I like the results of Typora's internal PDF converter much more; but as long as you need links to local files, the pandoc-converter is an usable workaround.

**Comment by abnerlee** [comment]
duplicated with #2546
