### ISSUE TITLE
PDF-Export using pandoc failed "pdf-engine must be one of ..." (Workaround & root cause)

### ISSUE THREAD

**Issue by profhccaesar** [typora/typora-issues#5778]
When exporting to PDF using the export template "PDF (LaTeX / Pandoc)" pandoc fails with following error:
![image](https://github.com/typora/typora-issues/assets/17450059/e6fcf631-9b22-4af0-afdf-e3a711105303)

Full argument list, copied from error message above:
```
-f native -s -o /tmp/example.pdf -t pdf --pdf-engine="pdflatex"
```

It's not a pandoc-setup-problem. pandoc runs sucessful within a shell:
```
pandoc ./example.md -s -o /tmp/example.pdf -t pdf --pdf-engine="pdflatex"
```
See also issue #4935.

# Root cause & Workaround
Doing some investigations with strace shows the problem, it is the argument `--pdf-engine="pdflatex"`. Typora executes pandoc directly, without using a shell (Linux / Mac) or cmd (Windows). So the command line is not parsed, the arguments are forwarded "as is" to pandoc. T. m., pandoc receives `"pdflatex"` as PDF-engine instead of `pdflatex`. This can be reproduced on the command line:
```
/tmp$ pandoc ./example.md -s -o /tmp/example.pdf -t pdf '--pdf-engine="pdflatex"'
pdf-engine must be one of wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, tectonic, pdfroff, context
```
As a workaround it is possible to set the PDF-Engine in the "extra arguments" field instead the dedicated field in the setup dialog:
![image](https://github.com/typora/typora-issues/assets/17450059/94cbfc71-4934-4055-91d2-ee862df2a79d)

# Steps to reproduce

1. Precondition: pandoc & PDF-engine (e. g. pdflatex) are installed correctly
2. Open any arbitrary Markdown file with Typora
3. Set up PDF-Export per pandoc:
    a. `File` -> `Preferences` -> `Export`
    b. Use `+` to add template `PDF (LaTeX / Pandoc)`
    c. Select PDF Engine `pdflatex`
4. Export file: `File` -> `Export` -> `PDF (LaTeX / Pandoc)`
5. Error dialog pops up: `pdf-engine must be one of wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, tectonic, pdfroff, context` (see image above)

# Expected behavior

No error, PDF must be created.

# Desktop
- OS: GNU/Linux x86_64 5.15.0-76-generic

# Typora Version
Typora for Linux (x64) version 1.6.6

**Comment by abnerlee** [comment]
Typora do not use a shell, it reads PATH of your system / current ENV. And typora does not know what your default shell (zsh / bash / cmd / powershell / etc) is, we also do not want to add option of "default shell" just for export purpose. And we do not want a shell error or update prompt goes out when user do the export command.

**Comment by profhccaesar** [comment]
> Typora do not use a shell, it reads PATH of your system / current ENV. And typora does not know what your default shell (zsh / bash / cmd / powershell / etc) is, we also do not want to add option of "default shell" just for export purpose. And we do not want a shell error or update prompt goes out when user do the export command.

This answer isn't adequate and miss the point completly. 

Just since Typora do not use a shell, it is not allowed to embed arguments in `"`!

You have to just remove the `"` which embeds the template name argument from you code to fix the bug.

**Comment by milavdabgar** [comment]
Yes, Please fix this issue, as I heavily use typora and I'm a paid user, but no bug fix since long time.

**Comment by DanDawson** [comment]
I too am surprised that they marked this issue as **Completed** in 2023, but I'm still seeing the problem today and can not export PDF's via "PDF (LaTeX / Pandoc)" on a Mac, it always returns:

_pdf-engine pdflatex is not compatible with output format pdf_

AI was recommending I try using "-f markdown --pdf-engine=pdflatex" in the **Extra Arguments** field as a work-around, but that did not work either.

Running my command directly in Terminal works fine:

`pandoc -f markdown -s -o output.pdf -t latex --pdf-engine=pdflatex input.md`
