### ISSUE TITLE
Cursor jumps forward after pressing backspace

### ISSUE THREAD

**Issue by miciasto** [typora/typora-issues#5781]
**Describe the bug**
When I try to delete an emoji using the backspace key, the cursor jumps forward by one character.

**To Reproduce**

1. Enter the text in a document:  `:smile:ABC`.
2. Move the cursor to be immediately before the `A`.
3. Press backspace key **twice**.

The text is now `:smileBC`

**Expected behavior**
The text should be `:smilABC`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, Windows 11

**Typora Version**
1.6.6

**Comment by abnerlee** [comment]
fixed in 1.7
