### ISSUE TITLE
Unable to indent size titles

### ISSUE THREAD

**Issue by Chives2023** [typora/typora-issues#5782]
Unable to indent size titles
  My original size title could be indented, but one day, suddenly my size title couldn't be indented. For example, my first level title was in the top grid, and my second level title was indented once. But now my second level title is also in the top grid. Sometimes it can be frustrating to take notes and solve!
例如下图
![1689550877540](https://github.com/typora/typora-issues/assets/132042751/75307672-856f-41f9-a0db-2f04e48481b5)
之前的效果
![1689550924398](https://github.com/typora/typora-issues/assets/132042751/1a1ec621-0ec1-4f10-9dc5-6c17daa17bbb)

**Comment by abnerlee** [comment]
You will need to use `&nbsp;`, whitespace after "#" in headings are just ignored in markdown.
