### ISSUE TITLE
How to change footnote format in Typora & PDF export

### ISSUE THREAD

**Issue by evogel99** [typora/typora-issues#5784]
I have modified the Eloquent theme for printing and exporting to provide smaller text as follows

```
#write, #typora-source {
    font: normal 0.7rem "Libre Baskerville", serif;
    line-height: 1.6;
    word-wrap: break-word;
}  /* The original theme has: 0.9rem */
```
In Typora this does scale the text, but does not scale down the footnotes, so they are larger than the body type.
On export to PDF, the footnotes are scaled down below the **0.7rem** size I set.

How can I control the size of the footnotes?
1. in Typora
2. for PDF export

**Comment by abnerlee** [comment]
see #4999
