### ISSUE TITLE
Cannot select task list items using keyboard

### ISSUE THREAD

**Issue by tgeijten** [typora/typora-issues#5790]
- [ x ] Searched existing issues to avoid creating duplicates.

- [ x ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x ] Searched http://support.typora.io/

----

**Describe the bug**
Selecting items in a task list using the keyboard (Shift+Up / Shift+Down) does not work properly.

**To Reproduce**

1. Create a document with the following contents:
```
some text

- [ ] task 1
- [ ] task 2
- [ ] task 3

more text
```

2. Go the start of `task 1`
3. Keep pressing `Shift+Down`
4. The items `task 3` and `more text` are never reached or selected
5. Go to the start of `task 3`
6. Keep pressing `Shift+Up`
7. The items `task 1` and `some text` are never reached or selected

**Expected behavior**
Correct selection behavior, similar to selecting items in an unordered list.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit

**Typora Version**
e.g: 1.6.7

**Additional context**
The behavior makes it difficult to quickly reorder task list items.

**Comment by abnerlee** [comment]
fixed in 1.7
