### ISSUE TITLE
Math copy as image doesn't work

### ISSUE THREAD

**Issue by IVSpretender** [typora/typora-issues#5792]
- [✔] Searched existing issues to avoid creating duplicates.

- [✔] Confirmed that it can be reproduced in built-in themes without customized css.

- [✔] Searched http:support.typora.io/

----

**Describe the bug**
When I try to copy a math equation as image (`Copy /  Paste As...` > `Copy as Image`) , I expect that an image of the math equation can be pasted and should appear in the clipboard (`Win + V`) , but actually nothing happens: the math image doesn't appear in the clipboard and "`Ctrl + V`" only pastes the text I have copied before. 

**To Reproduce**
1. Enter a formula, for example: 
$$
1+1=2
$$
2. Right-click on the rendered formula "1+1=2".
3. Choose `Copy /  Paste As...` > `Copy as Image` in the context menu.
4. Press `Win + V` or try to paste anywhere to see the error.

**Expected behavior**
An image of the math equation "1+1=2" can be pasted and should appear in the clipboard (`Win + V`) .

**Screenshots / Screencasts**
Screenshot 1
![Snipaste_2023-07-30_14-58-12](https://github.com/typora/typora-issues/assets/92420468/d613f920-d4d5-4f27-a803-cb4bfd4f76dd)
---
Screenshot 2
![image](https://github.com/typora/typora-issues/assets/92420468/f66b9435-a514-43c5-8b00-7eaf218dd84b)
---

**Sample Markdown File**
[Untitled.md](https://github.com/typora/typora-issues/files/12208654/Untitled.md)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2 64bit

**Typora Version**
I tried multiple versions: 
- 1.6.7
- 1.4.4
- 1.7.0-dev
but in none of these versions, "math copy as image" works. 

**Additional context**
- I have tried running *Typora* as administrator, but the bug still exists. 
- I'm using *PinStack* as a long-term history of clipboard, which is related to clipboard, but closing it makes no difference to the bug.

**Comment by abnerlee** [comment]
fixed in 1.8.6
