### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by zhai0122** [typora/typora-issues#5793]
- [ √] Searched existing issues to avoid creating duplicates.

- [ √] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ √] Searched http://support.typora.io/

----

**Describe the bug**
When using Typora to open the second file (including md, txt, etc.), an error "A JavaScript error occurred in the main process" will appear

**To Reproduce**
1. Open the first the file
2. Open the Second file, than An error occurred

**Expected behavior**
When you click the cross or OK, all typora processes will exit.
The recurrence probability is about once every 15 minutes, and I reproduced it almost every time when I wrote the issue.

**Screenshots / Screencasts**

![image](https://github.com/typora/typora-issues/assets/81839775/97ced96b-00eb-4212-8670-00fa0647b84c)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit 21H1 19043.1237

**Typora Version**
  1.7.0-dev

**Comment by abnerlee** [comment]
fixed in 1.7.5
