### ISSUE TITLE
[Feature] Automatically change the order number of headers

### ISSUE THREAD

**Issue by Jax-Yang** [typora/typora-issues#5798]
For example, I have 3 headers:
1-First
2-Second
3-Third

Now I need to insert a header amoung them, like this:
1-First
2-New
2-Second
3-Third

I want the header "Second" and "Third" change their order number automatically, 
or else I need do it manually, 
it will cost time if there are too many headers under the new one.

**Comment by owenstake** [comment]
you should use custom themes. [Auto Numbering for Headings - Typora Support](https://support.typora.io/Auto-Numbering/ )

**Comment by Jax-Yang** [comment]
Thx @owenstake, it's good for me🙂
