### ISSUE TITLE
Typora gets slower the longer it has been open

### ISSUE THREAD

**Issue by wilfreddenton** [typora/typora-issues#58]
It seems that, regardless of the length of the document, Typora becomes slower the longer it is open. It seems like a memory leak but when I look at the usage in activity monitor it's pretty normal. Anyone else experiencing this or have a fix?

**Comment by abnerlee** [comment]
@wilfreddenton what's the Typora version and OS version?

**Comment by wilfreddenton** [comment]
Sorry, should have included this in the original post.

version: `0.9.8.1`
OS: `OS X El Capitan Version 10.11.2 (15C50)
Computer: `MacBook Pro (Retina, Mid 2012)`

**Comment by waahto** [comment]
Typora open for n days, memory usage ~200 MB, cpu fluctuates between 0.5–20 %, staying below 10 % for >95 % of the time.

**Comment by DanBennettUK** [comment]
I also have this issue. I can't work out what's causing it. I thought it was due to the size of the file I have but restarting the app fixes it!

Windows 10 x64.

**Comment by DanBennettUK** [comment]
Typora constantly using CPU. Bit laggy when typing which makes it fun... 

Disabled debugging and anonymous stats to see if that helps. No luck. 

Memory keeps rising an lowering too. Not massive amounts mind, 125MB tops... lowers to around 95MB when it's piped down. CPU usage never going above 30%.

Seems to be at any time I type, the CPU usage goes up. Which makes typing difficult - especially making corrections.

File is 32,146 words long. 215KB in size.

This on a Windows 10 system. Very odd...

**Comment by gandalfsaxe** [comment]
I'm noticing the same. Luckily restarting the app fixes it, and doing this is a lot more convenient now that Typora can restore all the open tabs from the last session. But of course I'd be nice to avoid in the first place.

**Comment by abnerlee** [comment]
#68
