### ISSUE TITLE
Mermaid v10.3.0+ Features still not supported

### ISSUE THREAD

**Issue by 0xfk** [typora/typora-issues#5806]
- [*] Searched existing issues to avoid creating duplicates.

- [*] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [*] Searched http://support.typora.io/

----

**Describe the bug**
Trying "Actor Creation" in mermaid which is part of 10.3.0+ version, is still not supported yet

**To Reproduce**
1. Go to "Paragraph"
2. Click on '.Code fence'
3. In Code feces from code language choose mermaid
```
sequenceDiagram
    Alice->>Bob: Hello Bob, how are you ?
    Bob->>Alice: Fine, thank you. And you?
    create participant Carl
    Alice->>Carl: Hi Carl!
    create actor D as Donald
    Carl->>D: Hi!
    destroy Carl
    Alice-xCarl: We are too many
    destroy Bob
    Bob->>Alice: I agree
```

**Expected behavior**
As per Mermaid documentation here the below should rendered
![Screen Shot 2023-08-20 at 3 09 22 PM](https://github.com/typora/typora-issues/assets/88821024/2236ffe8-711d-4c2f-a706-c7ab8769797d)

**Screenshots / Screencasts**
Instead of the above the below error was received
![Screen Shot 2023-08-20 at 3 12 06 PM](https://github.com/typora/typora-issues/assets/88821024/71021a42-ecf1-4ea1-9433-3919d18397c1)

**Desktop (please complete the following information):**
 - OS: [macOS Monterey 12.6.7 (21G651)]

**Typora Version**
Version 1.6.7 (6865)

**Additional context**

**Comment by abnerlee** [comment]
fixed in 1.7
