### ISSUE TITLE
Auto-save does not save last changes when quickly switching to another file after change

### ISSUE THREAD

**Issue by hsandt** [typora/typora-issues#5808]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
After changing the initial header of a file, if you switch to another file right after the change, auto-save may have only saved the change partially.

For some reason, I could only reproduce this when changing the top header of a file. I couldn't reproduce it with body content. I considered increasing auto-save period for easier repro, but found no such setting.

EDIT: I managed to repro it once with random body content

There was a similar bug about losing last changes if you closed Typora right after the last change, but this one must have been fixed in a previous patch.

**To Reproduce**
1. Open a folder with at least 2 files. Open one of them
2. Add a top header if not yet
3. Add a few words to the top header in the format "A B C"
4. Immediately switch to another file

**Expected behavior**
First file header should be updated to "[previous text] A B C" (also visible in quick file preview of beginning of text in the side bar)

**Screenshots / Screencasts**
Will try to record a screencast, but oddly difficult to do in my brand new MWE project (to avoid leaking private info). Maybe a longer file makes auto-save slower and helps reproducing?

**Sample Markdown File**
Same remark as above

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04 with Unity desktop

**Typora Version**
1.6.6

**Additional context**
Repro rate of 20% on my file with long text...

**Comment by abnerlee** [comment]
relates #5770

**Comment by abnerlee** [comment]
should be fixed in 1.8.6
