### ISSUE TITLE
MathJax rendering incorrectly on Wayland

### ISSUE THREAD

**Issue by JulianGro** [typora/typora-issues#5811]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized CSS.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
MathJax doesn't render correctly on Wayland.

**To Reproduce**
You may force Typora to run in Wayland mode by appending `--ozone-platform=wayland`.
The same can be done with X11 `--ozone-platform=x11`

**Expected behaviour**
MathJax should look the same on both X11 and Wayland.

**Screenshots / Screencasts**
Proper rendering on X11:
![Screenshot_20230824_141601_x11](https://github.com/typora/typora-issues/assets/11144627/a96556fa-b810-4e90-909e-e4ee229335c2)
Incorrect rendering on Wayland:
![Screenshot_20230824_141705_wayland](https://github.com/typora/typora-issues/assets/11144627/c60b622d-0089-4696-8d74-e35fd2883795)

**Sample Markdown File**
```mathjax
$$
3(b+2a)*2+b(5-2)*3-10b \\
= (3b+6a)*2+(3b)*3-10b \\
= 6b+12a+9b-10b \\
= 12a+5b \\
$$
```

**Desktop (please complete the following information):**
 - OS: Arch Linux ARM, postmarketOS (tried on two different aarch64 computers)

**Typora Version**
1.6.6 (currently the newest Linux version)

**Additional context**
From what I can tell, this is the only issue Wayland related issue that I am running into.
Running through XWayland instead of natively running Wayland can have a noticeable performance impact.
XWayland apparently doesn't always work. At least on postmarketOS I haven't been able to get it running so far.

There is a *similar* issue here: https://github.com/typora/typora-issues/issues/5441

**Comment by siddhpant** [comment]
Cannot reproduce on 1.7.5.

![image](https://github.com/typora/typora-issues/assets/25429745/a014d04d-1afb-419d-b6b3-d0f3f72d96e1)

**Comment by JulianGro** [comment]
I can confirm that this got much better in 1.7.6.
