### ISSUE TITLE
Advanced diagrams (PlantUML/C4)

### ISSUE THREAD

**Issue by RLogik** [typora/typora-issues#5815]
It would be very useful to implement more advanced paradigms, e.g. for software architecture. There are a few options here, e.g.

- PlantUML
- C4

See e.g. <https://github.com/adrianvlupu/C4-PlantUML>, <https://github.com/plantuml-stdlib/Azure-PlantUML>.

Here is what PlantUML looks like:

![Image](https://user-images.githubusercontent.com/1009874/156725980-75667080-c4ee-48fd-a2c9-9e2c70f0c879.png)
***Fig 1.** Image from [@simonbrowndotje](https://github.com/mermaid-js/mermaid/issues/1276#issuecomment-1058963357)*

The C4 paradigm is documented here: <https://mermaid.js.org/syntax/c4.html>. C4 in itself does not look very nice, but the combination with PlantUML seems decent and looks like this:

![Image](https://camo.githubusercontent.com/5f9f02575120648307b907ae2421e07e46b637b8c1759a091944968174c247ea/68747470733a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f706e672f684c52565a7a663634377864687659474830363930724c664e596754353078537659417565793062564b445a7873314d4d552d776b7369754c464c5f78776d6e44594f647649357a6b4d44645468786c735f616e794435766a4278384c4553543934526c6f4e674737577849786d3235613575515a4f66544d4f505157394151303672515041477a74346f4e714d6f796c6c79495255755639684564514e4a52374f77366d6f767530754b5a4b325031664f77544c743842525f546539535141446c4769644e557a78644c6d6a7a793155324c726557663179334f626c77625a7a675741555962614446627243703751386f6b706d706f7976314b6648765447452d7a707a7a6a655046346d4a466262485370595243394866467347747052413555674758486c645850386e577a7569576b626646586a62773370503574637161446a45505f4e6679556a633449724e5a6d2d526e77567278467558776c4b7664736a433752575970757472653073753731446f38334e75374f37365a41304e656f4331766347676a32334241504f77585331396e587a70535743757836496f30733771457279334c6359655a76636e72317932437a766c5178436269464874474f6d5a706649414b664f7967467733662d556771634b47784432356d694b3457685049612d5943584f574b584c68704d7468543639446c37355964654a6b304472692d4a386d6f7a6c504444386c6371534477795f695a5f7661797058774e78385f4a617856782d6c7478337a466e586e335a54665a4a52494a4a644c7a39474d384c7068712d55717841725970697a696d366f506145555848326d384d4f566853567632723962544247374e4b49694662485070745a765038427172384a2d6c5649737441695f35374878484a545a6948435162524b65575743655f2d486e745a56793749797a3867574a59713859516435334252366d68747350334c766b34467a424a4a37776b57795050744557676d706b66534b70666b43783030637a51566b3643766343446b6f5f3335373371753570796a304c414b4443346243655274686965754a7a4551453347426a695056796d625a4e3068667a2d415333303874557465375933554f764e5f7641434f70704e4361346d5f5265696b617078643430677a6d367956436c6173325261663978626235415376786c396232443941304d665264635a5379464e756e5050396c507653586d41744f686b6262574965377a704266416843707a30434f7742484a514f35764f6976535970385849427844693276735335665f71485f3263706749336c534747386f746d576f3673766b3338565953664378354b4c454c5a375777726743646830566f35364e3867736339306f4b6f364f4e4c3578435870714e76327434613032446842584178624a55455547387a587a4f47774c312d33636a4d56437359546c52376138366e4269394841767372504b7632512d703868466d7a574c7175434f453574613557496642723476475158687957764b325262305f62612d357359675864644a43644769656c7862706a64516c59515255395163566a3158613949364259534d4b7054784e54525a344e7a4d5f547a7a456e786241354b367253516332597763564576636864306c4475486f39384b35536e624f6571704d6d5f48537839336448415338586473306846497267306f666a76517045586767325f495a6167546b6f3158475f732d592d47336e67526d4a476943776261555742556537505150514442564d5041777331564472337576536537787174677a4d4637357a5a734e756d5f6c4c3474566d354c716375556d6a63464a78385749686a6130354c396652334c344a4c586b7447357976635f4f4b4b64554c4244714c47594457667933736a6e6e5332457836504f73773939474544585161764b4277733262396d565531414141507465744f535751796f39524c7173734f62573754314569394b4f5a76416556736e6851534f4e5a5f635a654c5f467257653551444d59354e744c62617756636b757774724e6e7364516c367056326474702d7077385f654f54686854785236554238574231787177536c635f3469417a614475366d656b5a5578726f766d726c78453262757a56706b7845487250505045655f)
***Fig 2.** Image from [plantuml-stdlib](https://github.com/plantuml-stdlib/C4-PlantUML)*

What is missing is symbols for Databases, etc.

**Comment by simonbrowndotje** [comment]
> C4 in itself does not look very nice

Care to elaborate? The C4 model doesn't prescribe any notation.

**Comment by abnerlee** [comment]
put into #1661 since we will support C4 after we upgrade our mermaid library dependency.

plantUML refers #1246
