### ISSUE TITLE
Page error when search in preferences panel

### ISSUE THREAD

**Issue by Zhangpch2021** [typora/typora-issues#5817]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
当我试图在最新版的typora中设置一些内容时，发现Ctrl+，无法打开设置，需要鼠标在文件的选项中点击打开设置，并且在设置的搜索框中输入内容发送时页面就立刻黑屏了，重装重启typora都不行
**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://github.com/typora/typora-issues/assets/102280098/05aa1964-3bfe-4ec0-92b2-eae18fed14e6)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: win11 22H2 22621.2215

**Typora Version**
e.g: 1.7.3

**Additional context**

**Comment by abnerlee** [comment]
fixed in 1.7.4
