### ISSUE TITLE
error message issued when open an .md document from windows console

### ISSUE THREAD

**Issue by PVeps** [typora/typora-issues#5818]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
An error message will be shown when an .md document will be opened from the MS Windows console.

**To Reproduce**
1. Start the cmd.com
2. Go to directory contains an .md document (e.g. readme.md)
3. Enter the document name as a command (e.g. type _readme.md <Enter>_)
4. Typora starts and opens the document but:
5. An error message will be shown in the console (see attached screenshot)

**Expected behavior**
No error message shown.

**Screenshots / Screencasts**
![image](https://github.com/typora/typora-issues/assets/82579081/b6be4e4b-0f88-471b-9009-5f072fbb583b)

**Sample Markdown File**
[readme.md](https://github.com/typora/typora-issues/files/12515376/readme.md)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit build 19045.3324

**Typora Version**
Typora for Windows 64 version 1.7.3

**Additional context**
That issue also occurred by some older Typora Versions (e.g., 1.6).

**Comment by abnerlee** [comment]
Do you set "Always Open With" to "Typora.exe" for *.md files?

**Comment by PVeps** [comment]
> Do you set "Always Open With" to "Typora.exe" for *.md files?

Honestly, I can't remember it anymore. Here is the registry entry:
![image](https://github.com/typora/typora-issues/assets/82579081/6b93d91f-e842-4c37-8bb1-7b79e11e4333)

P.S. I did following now:

1. In Windows Explorer - "open with..." via local menu.
2. (Despite the entry "Typora" is already present) Open with another app,,,
3. Typora selected + "always open with this app" selected.

The error message is still issued.
(sorry, the previous post edition was too hasty)

**Comment by abnerlee** [comment]
Can you open other files directly from terminal? like xxx.txt, xxx.svg, xxx.html?

**Comment by PVeps** [comment]
Hello abnerlee

> Can you open other files directly from terminal? like xxx.txt, xxx.svg, xxx.html?

I have meanwhile updated the tool to version 1.7.5. Now I have tried different file types - .md, .txt, .html - I get **no** error message more.
