### ISSUE TITLE
Failed to use ctrl+k to delete an empty line (Mac)

### ISSUE THREAD

**Issue by AndriyLin** [typora/typora-issues#582]
Hi,

In Mac, `ctrl + k` is a system level shortcut (following Emacs) to delete from cursor to end of line. And when cursor is at head of line and the line is empty, it can delete this line.

In Typora (0.9.9.9.3) for Mac, the first part is supported, but not the latter. Hope this is added in later version.

**Comment by AndriyLin** [comment]
@abnerlee All right. But that's weird. I tried again on these 2 apps, and they CAN remove empty lines. Confirmed on my friend's mac as well. Anyway.

**Comment by AlexPasternak** [comment]
@abnerlee, that is incorrect, Ctrl-K is a standard macOS shortcut. I just tried on TextEdit and Pages, and it works in both.

Please see this Apple article, which describes Control-K as "Delete the text between the insertion point and the end of the line or paragraph."

https://support.apple.com/en-us/HT201236

**Comment by abnerlee** [comment]
That's weird, I will test again..

**Comment by abnerlee** [comment]
I see ctrl+k will delete empty line, but will not delete if the line is the last line

**Comment by abnerlee** [comment]
Fixed in newest version
