### ISSUE TITLE
<span class="md-search-hit"> appears in my documents.

### ISSUE THREAD

**Issue by Squirreljetpack** [typora/typora-issues#5829]
**Describe the bug**
Occasionally when editing large documents, these span tags will pop up into my latex
\<span class="md-search-hit">p</span>.
Sorry, hard to be more informative, just leave it here in case anyone comes across this bug.

**To Reproduce**
Hard to reproduce as it only happens on my large documents which have lots of personal stuff.

**Typora Version**
1.7.3 mac

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> the sample md file which <span class="md-search-hit">p may show up after find or replace?
