### ISSUE TITLE
Copy mermaid diagram not working

### ISSUE THREAD

**Issue by shivan** [typora/typora-issues#5837]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
create a mermaid flow chart diagram, try to copy

**To Reproduce**
1. create a mermaid diagram like this
graph LR

A --> B
2. click on the diagram (image) with right mouse button
3. select copy/paste as --> copy as html
4. paste anywhere - word, mail application whatever... 
5. it's pasted what's in clipboard, but not the diagram
Everything in the "copy/paste as" menu does not work.

**Expected behavior**
the diagram should be pasted

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://github.com/typora/typora-issues/assets/1827692/875863b2-784c-4694-b65b-313af81b00fd)

**Sample Markdown File**
see example above

**Desktop (please complete the following information):**
 - OS: windows 11 64 bit

**Typora Version**
1.7.4

**Additional context**
nothing

**Comment by abnerlee** [comment]
fixed in 1.8.6
