### ISSUE TITLE
[Feature]Wish the table could add the ability to delete rows

### ISSUE THREAD

**Issue by HappyAxin** [typora/typora-issues#5838]
Wish the table could add the ability to delete rows

**Comment by neuromachina** [comment]
Have you checked the menu items in the Paragraph Menu in Typora?
On macOS the menu item, such as delete row, will also show the command key equivalent, or keyboard shortcut. 
cmd-shift delete key (Looks like the BACKSPACE key position on non Mac keyboard)

**Comment by abnerlee** [comment]
It is supported. You an do that via menu bar, context menu or shortcut keys.
