### ISSUE TITLE
Dragging Browser Location Field to Typora from Safari

### ISSUE THREAD

**Issue by neuromachina** [typora/typora-issues#5839]
<3 Typora very much  when dragging a link from the browser's Location Field to Typora page; resulting in a markdown element this:
```
[the page's HTML Title element string](http://theurl)
```
Does Safari have a problem? 
Or does Safari have a User setting that will cause it to behave like other browsers when dragging a link from the browser to Typora. I thought it may have worked on previous version of both Typora (1.67 maybe) and macOS Mojave but I don't have that in front of me to verify. 

The first thing I noticed when I began using (for the first time) Monterey with Safari and Typora... the expected behavior is not there. The end result of dragging a location field to Typora page is merely the URL. No title. No markdown.  

Monterey (12.6.9)
Safari (Version 16.6 (17615.3.12.11.3, 17615))
Typora (Version 1.7.4 (7007))

Just asking the community.

**Comment by abnerlee** [comment]
I'm not able to reproduce this.. Are you dragging a link or just tile without links? On each web page did you met this issue? Is possible, could you provide a screencast of this issue?

**Comment by neuromachina** [comment]
Hi!

May not be likely we are on same version: macOS 12.6.9 (21G726)

Let's confirm that we are doing the same thing in the GUI. 

When I use the term `Location Field` I am referring to the field where we insert the URL and where the page's URL is displayed. This link may be helpful to visualize: 
https://support.apple.com/guide/safari/get-started-ibrw6fde4ee8/16.1/mac/13.0#ibrw06eb5919

When the text in the Location Field is selected, Somewhere on the string, I mouse-down (click) & drag the URL to Typora page/window. 

The resulting Markdown in the Typora with three browsers:

Safari (Version 16.6 (17615.3.12.11.3, 17615))
 https://www.redhat.com/sysadmin/tiny-containers 

Opera One (version: 102.0.4880.56) (x86_64)
 [[How to build tiny container images | Enable Sysadmin](https://www.redhat.com/sysadmin/tiny-containers)](https://www.redhat.com/sysadmin/tiny-containers) 

Brave - Version 1.58.127 Chromium: 117.0.5938.88 (Official Build) (x86_64)
 [[How to build tiny container images | Enable Sysadmin](https://www.redhat.com/sysadmin/tiny-containers)](https://www.redhat.com/sysadmin/tiny-containers)

I assume Typora is using http connection to fetch HTML title string from the page. Is that true?

I am on a new macOS image. Yes, sadly, Monterey is new to me. It's as far as my hardware is supported by Apple. 
So possible I could have an incorrect Safari setting/config that I do not know about.

**Comment by neuromachina** [comment]
Looks like I was doing it wrong on Safari. Kinda hilarious that the User must mouse-down on "the globe" icon if the User wants that combo. 

I guess that gives the Safari User to ability to drag the title and URL or the URL only. 

Well, alright alright, alright.
