### ISSUE TITLE
How about a direct download link for deb or source code package instead of a PPA way only?

### ISSUE THREAD

**Issue by JackieMium** [typora/typora-issues#584]
I am using Debian Linux 
You provide `Typora for Linux` but there is only one way: sudo add-apt-repository, which is kind of Ubuntu-preferable. I'd like to install Typora without making system setting, especially when it comes to add a repository. So it'd be really helpful if you provide a direct download link for deb or source code package. Best regards.

**Comment by abnerlee** [comment]
You could see more detail on http://support.typora.io/Typora-on-Linux/ about manual install.

But apt-get install is recommended since we want to use the built-in way to install and update typora. Or else, you need to update Typora manually.
