### ISSUE TITLE
Some issues about text-align

### ISSUE THREAD

**Issue by marti844** [typora/typora-issues#5845]
Hello.Recently I met a issue about how to make the text justify. **I add the code "text-align: justify; display: block;" inside #write{...}. But it only work in window, dosen`t work in MacOS.** What is the problem?
The infromation I reference from internet is: [https://blog.csdn.net/m0_46161993/article/details/123210188](https://blog.csdn.net/m0_46161993/article/details/123210188)

**Comment by abnerlee** [comment]
You will also need "whitespace:nomral;" since Webkit / Safari does not support both pre and justify
