### ISSUE TITLE
Typora can't be opened on mac (1.7.5)

### ISSUE THREAD

**Issue by sh-cho** [typora/typora-issues#5848]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Typora cannot be opened

**To Reproduce**
```sh
brew install --cask typora
```
Install typora (1.7.5) via homebrew

**Expected behavior**
Typora is opened

**Screenshots / Screencasts**

<img width="260" alt="image" src="https://github.com/typora/typora-issues/assets/11611397/5fdd696d-fd42-4219-a52e-5073e46fb6c2">

> "Typora.app" can't be opened because Apple cannot check it for malicious software.
>
> This software needs to be updated. Contact the developer for more information.

**Sample Markdown File**
x

**Desktop (please complete the following information):**
 - OS: M1 Mac 13.2 (Ventura)

**Typora Version**
1.7.5

**Additional context**

**Comment by abnerlee** [comment]
sorry, please redownload Typora. It should be fixed already.
