### ISSUE TITLE
[Feature] Fold the content

### ISSUE THREAD

**Issue by HighVorz** [typora/typora-issues#5849]
Click the title then the content would be folded. Not outline feature. I havn't seen this feature in markdown editor.

**Comment by Burgerd4sh** [comment]
我自己实现了一个Typora中折叠的插件，包含img折叠，欢迎下载使用。好用的话希望您能点点star给点正反馈

I have implemented a folding plugin in Typora, which includes image folding. You’re welcome to download and use it. If you find it useful, I hope you can give it a star as positive feedback

https://github.com/Burgerd4sh/zfolder

**Comment by Burgerd4sh** [comment]
duplicate with #499

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/499
