### ISSUE TITLE
High CPU usage and sluggish experience

### ISSUE THREAD

**Issue by johnnysong-cc** [typora/typora-issues#5852]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Recent upgrading to Typora v1.7.5 and macOS Ventura to Sonoma has led to very sluggish, sometimes unresponsive editing experience in markdown documents of ~ 30,000 words which worked smoothly previously with Typora v1.5 and macOS Ventura. The "Typora Web Content" process takes high on %CPU on my M1 Max-based MacBook Pro with 32GB RAM. Not sure which upgrade has caused the issue.

**Expected behavior**
- Selected text should be replaced immediately when pressing any key for characters, which is not the case now.
- Lower CPU usage with the core processes.

**Screenshots / Screencasts**
<img width="774" alt="High CPU Usage" src="https://github.com/typora/typora-issues/assets/75377597/38d92b8a-d1c3-46f7-a662-04c3c101c665">

**Sample Markdown File**
N/A due to confidentiality

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.0

**Typora Version**
1.7.5

**Comment by abnerlee** [comment]
merge into #68

**Comment by markmillerdev** [comment]
I have also been experiencing the lag issue.  It always manifests itself when I have several open tabs, then open a new tab and attempt to start writing.  The app is frozen and I am unable to type anything for about 10 seconds up to a whole minute.

Typora Desktop version: 1.9.4
OS: MacOS 15.2
