### ISSUE TITLE
crush when using print.

### ISSUE THREAD

**Issue by laraws** [typora/typora-issues#5853]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When I use the Print function in Typora on the page I want to print, it crashes immediately. The crush pop-up window is below.
![image](https://github.com/typora/typora-issues/assets/40230381/0d1a57e4-a84a-487e-90f2-a3f541a5307c)

**To Reproduce**
1. Open a folder with multiple markdown files.
2. Select a md file
3. Select Print function

**Expected behavior**
Print md file succefully.

**Screenshots / Screencasts**
![image](https://github.com/typora/typora-issues/assets/40230381/0d1a57e4-a84a-487e-90f2-a3f541a5307c)

**Sample Markdown File**
Any md file, even a enpty file.

**Desktop (please complete the following information):**
 - Ubuntu 22.04.3 LTS x86_64 

**Typora Version**
e.g: 1.7.5

**Additional context**
Hope it can be solved soon.

**Comment by abnerlee** [comment]
duplicated with #5033
