### ISSUE TITLE
node labels in mermaid diagrams still misaligned on mac

### ISSUE THREAD

**Issue by samuelpmish** [typora/typora-issues#5854]
follow up to https://github.com/typora/typora-issues/issues/5812, which was closed prematurely, without fixing the issue.

On macs with 1.7.5, the labels are still misaligned:

<img width="1016" alt="270117934-58f9243e-11f0-48da-8217-866f80408cbd" src="https://github.com/typora/typora-issues/assets/16393433/1468ab3f-23d4-4eac-ba67-a6d3f41d5cdd">

**Comment by abnerlee** [comment]
We are not able to reproduce this anymore. What is the result if you do this on https://mermaid.live/ on Safari?

**Comment by samuelpmish** [comment]
using the default mermaid.live example 

```
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
  ```

I get the following

mermaid.live:
<img width="395" alt="Screenshot 2023-10-16 at 7 36 34 AM" src="https://github.com/typora/typora-issues/assets/16393433/c66e3b50-2b1c-454f-b712-0f9c925d9b53">

-------------

typora version 1.7.5 (7015):
<img width="479" alt="Screenshot 2023-10-16 at 7 36 14 AM" src="https://github.com/typora/typora-issues/assets/16393433/445d332a-8995-4ca8-b110-722ea7e91148">

-------------

I get the same results (with vertically offset text labels) on two different macs, but things look correct on my ubuntu 22.04 machine.

**Comment by abnerlee** [comment]
merge into #5864
