### ISSUE TITLE
[Feature] Cache remote images on the locally to avoid having to re-download them every time you open the file

### ISSUE THREAD

**Issue by nitianziluli** [typora/typora-issues#5856]
When images are saved on the cloud, they need to be re-downloaded every time the file is opened locally. This wastes traffic downloading these images repeatedly and makes it impossible to view the images without an Internet connection. Sometimes proxy software is required to access the image bed, and my requirement may be just to open the file locally for viewing, which will become troublesome.

So I hope to add a new function to cache the pictures uploaded to the picture bed locally, and provide corresponding function options to let users decide whether they need to delete the local cache.

**Comment by abnerlee** [comment]
duplicated with #5656
