### ISSUE TITLE
The Title Bar doesn't work well

### ISSUE THREAD

**Issue by Darleey** [typora/typora-issues#586]
Windows 10.14393·1080P
Version 0.9.25

The icon aimed at windows control doesn't show it's shape , the height of the title bar may need a bigger size.

**Comment by abnerlee** [comment]
Is same with https://github.com/typora/typora-issues/issues/588?

**Comment by Darleey** [comment]
Yes

**Comment by dztdeng** [comment]
Maybe had fixed in  ver 0.9.27(beta) _"Fix styles for "unibody" style"_ .thank you for your efforts
