### ISSUE TITLE
The Hunspell dictionary for Slovak language is too old and buggy

### ISSUE THREAD

**Issue by richo67** [typora/typora-issues#5862]
The Hunspell dictionary for Slovak language which is used by Typora and which is at https://dict.typora.io/, is far to old. The slovak dictionary for Hunspell is developed and kept at https://github.com/sk-spell/hunspell-sk 

Could you please update this dictionary?

P.S.: I wonder how is the process handled when Typora have newer version of the dictionary at https://dict.typora.io/, then Typora user have in own Typora installation?

**Comment by abnerlee** [comment]
updated.

But you will need to Open preferences panel → Open Theme Folder. Then switch to its parent folder and delete typora-dictionaries/

We will consider better ways to upgrade hunspell dictionaries.
