### ISSUE TITLE
Hide asterisks Use custom CSS on .md-before and .md-after

### ISSUE THREAD

**Issue by robmunger** [typora/typora-issues#5866]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Searched http://support.typora.io/ since it may be already implemented.

When I am editing bold or italic text, asterisks appear on either side. Is there any way to prevent them from appearing?

I generally turn character formatting on and off using the keyboard shortcuts or popup menu, so I don't need to edit the asterisks. I can see which text is strong and emphasized based on its WYSIWYG appearance. Thus, I have no need for the asterisks

When the asterisks appear, it causes everything on the screen to move. Both I and my collaborators find this distracting. Typora is a beautiful and calming program, but this rapid movement detracts from this for us.

I was hoping I could turn the asterisks off by adding custom CSS. I tried the following:
```
.md-before,
.md-after,
.md-meta {
    display:none
}
```

It had no effect. Do you have any suggestions?

Thanks!

**Comment by abnerlee** [comment]
You can use `.md-meta { display:none !important;}`

It may cause some issues since Typora is a Markdown editor, not WYSIWYG rich editor.
