### ISSUE TITLE
Source code view broken for "diff" code blocks

### ISSUE THREAD

**Issue by iamvery** [typora/typora-issues#587]
Recently I noticed that in a large document the source code view was not working (showing blank). I managed to isolate this issue to the fact that it contained a code block of type "diff". Here's an example of such a code block on Github:

```diff
-remove
+add
```

I did a little experiment, and interestingly the issues in codeview crop up as soon as the second "f" in "diff" is typed. Here's a video messing around with the problem.

![2017-03-11 13_04_46](https://cloud.githubusercontent.com/assets/79619/23826131/66e89670-065b-11e7-959a-547f493505be.gif)

Hope this helps you track down the problem! Thank for a wonderful app ❤️

**Comment by abnerlee** [comment]
Fixed in newest version
