### ISSUE TITLE
latex support in html block

### ISSUE THREAD

**Issue by moolawooda** [typora/typora-issues#5872]
I found that the inline html supports $\LaTeX$ code while the html block didn't support. This may cause unexpected result when writting $\LaTeX$ code in html.

Examples:

+ inline html (can render $\LaTeX$ code)
```<span style='color:red'>$a_x$</span>```

+ html block (cannot render $\LaTeX$ code)
```<center><span style='color:red'>$a_x$</span></center>```

**Comment by abnerlee** [comment]
put into #1939
