### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by xdr630** [typora/typora-issues#5873]
- 希望能在typera中一键把图片上传到指定的存储空间中。如：已经写好的文章中的图片的地址都是其他第三方的存储路径，如果配置了 PicGo ，还得依次把图片上传到指定空间中，如果能直接有一键转储的功能，一次性的把已有的图片转储到配置好的PicGo的图床中就更好了，希望能有所改进

**Comment by abnerlee** [comment]
See https://support.typora.io/Upload-Image/#upload-all-local-images

**Comment by xdr630** [comment]
这个只能上传本地的图片，不能上传已经存在于OSS路径下的图片，就是Markdown文件中此时所有的图片已经存在第三方OSS了，我想把全部的图片上传到另外一个配置好的OSS路径下，typero目前不支持这个功能，希望后续能支持下
