### ISSUE TITLE
无法在Windows文件资源管理器中新建MarkDown文件

### ISSUE THREAD

**Issue by Zhangpch2021** [typora/typora-issues#5875]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
在Windows11文件资源管理器无法新建MarkDown文件夹
**To Reproduce**
步骤如下：
打开Windows11的文件资源管理器，然后通过右键新建或者是点击左上角新建按钮（+），发现没有MarkDown选项
**Expected behavior**
尽快修复，谢谢
**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://github.com/typora/typora-issues/assets/102280098/758173e0-cc9a-4966-a7f3-dc5f9d30a7a0)
![image](https://github.com/typora/typora-issues/assets/102280098/733aa2cb-f922-410e-8d10-6425d4af02f1)
**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]
  Win11 22621.2428 64bit
**Typora Version**
e.g: 0.10.11
1.7.6
**Additional context**

**Comment by abnerlee** [comment]
https://support.typora.io/New-File-in-Context/
