### ISSUE TITLE
The button is not displaying properly

### ISSUE THREAD

**Issue by dztdeng** [typora/typora-issues#588]
Maximize, minimize and close the button display is not normal

![typora_issue](https://cloud.githubusercontent.com/assets/16058956/23829185/7d25c442-0725-11e7-9e57-ea122c77dc63.png)

conf: window10 x64 Home, typora 0.9.25(beta)

**Comment by abnerlee** [comment]
Still have this bugs? I cannot reproduce it

**Comment by dztdeng** [comment]
Maybe had fixed in ver 0.9.27(beta) _"Fix styles for "unibody" style"_ .thank you for your efforts
