### ISSUE TITLE
Performance regretion in 1.7.x

### ISSUE THREAD

**Issue by jlarmstrongiv** [typora/typora-issues#5880]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I have a 70,000 word document that was slow, but worked.  In the latest 1.7.x, Typora is no longer usable with the document.  The latest version at time of writing is 1.7.6.  Downgrading to 1.6.7 works.

**To Reproduce**
Try to edit the document and click to move the cursor a lot

**Expected behavior**
Slow, but usable.  Not lagging for multiple seconds.

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Email sent

**Desktop (please complete the following information):**
MacOS Sonoma 14.0

**Typora Version**
1.7.x

**Additional context**
I purchased multiple licenses because I like typora!

**Comment by hbsmith** [comment]
I'm having the same issue. It is especially laggy when typing bullet points.

**Comment by abnerlee** [comment]
Does 1.8.2-dev (https://typora.io/releases/dev) fixed this?

**Comment by hbsmith** [comment]
@abnerlee performance on 1.8.2-dev does seem better for me. It doesn't fix #5921 though.
