### ISSUE TITLE
如何更改邮箱地址

### ISSUE THREAD

**Issue by asvidfhxadvdsfabskhh** [typora/typora-issues#5881]
请问如何更改许可证绑定的邮箱地址？

![图片](https://github.com/typora/typora-issues/assets/104066533/9cb95fe3-d585-4201-b9a7-90067a28e4bc)

**Comment by abnerlee** [comment]
Please contact hi@typora.io

**Comment by asvidfhxadvdsfabskhh** [comment]
> Please contact [hi@typora.io](mailto:hi@typora.io)

谢谢。
Thanks.
