### ISSUE TITLE
源码代模式下，多个行内公式的下划线会使得该段markdown的汉字斜体，实时渲染显示正常

### ISSUE THREAD

**Issue by ID14XY** [typora/typora-issues#5882]
- 源代码模式下，多个行内公式的下划线会使得该段markdown的汉字斜体，实时渲染显示正常。
- eg.1
指示功=动力过成功+理论泵气功:$W_i=W_t+W_{pt}$<br>表示缸内循环过程中理论上可以利用的总功量<br>四冲程自然吸气发动机理论泵气功为零,指示功=动力过程功
- eg2.
**机械损失功($W_m$)**:$W_m=W_{mf}+W_{me}+W_p$<br>式中 $W_{mf}$ 为机械摩擦损失功, $W_{me}$ 为附件损耗功,$W_p$ 为泵气损失功

**Desktop (please complete the following information):**
 - OS: Windows 10 22H

**Typora Version 1.7.6

**Comment by hitzhangjie** [comment]
这主要跟使用的主题的CSS设置有关系，如果懂些CSS的话，可以自己调整符合自己需要，或者从其他主题库里找其他主题。

**Comment by abnerlee** [comment]
put into #1638
