### ISSUE TITLE
[Feature] support more markdown variants

### ISSUE THREAD

**Issue by moolawooda** [typora/typora-issues#5888]
Since typora uses pandoc to convert .md to different file formats, is it possible to support more arkdown variants that pandoc supports?

There are 3 types of variants that can enhance the writing experience of markdown. Maybe support of at least one of these would be a good idea for Typora:
+ PHP Markdown Extra
+ pandoc’s extended Markdown
+ MultiMarkdown

Here's the list of all variants that pandoc supports:
+ Github-Flavored Markdown (default in Typora)
+ PHP Markdown Extra
+ pandoc’s extended Markdown
+ MultiMarkdown
+ CommonMark
+ Markdown.pl
+ CommonMark with many pandoc extensions
+ deprecated GitHub-Flavored Markdown

**Comment by abnerlee** [comment]
put into #2448
