### ISSUE TITLE
<img> are failed after exporting as docx

### ISSUE THREAD

**Issue by zhangbowei** [typora/typora-issues#589]
Hey，Man. 

1. the question like `<img>` are failed after exporting as pdf. 
when I use `<img>`, images of the docx files are omitted. (pandoc-1.19.2.1)

2. Really, I want to divide some words into two pages by docx.Any other solutions you know?

**Comment by abnerlee** [comment]
> the question like <img> are failed after exporting as pdf. when I use <img>, images of the docx files are omitted. (pandoc-1.19.2.1)

This seems to be our bug, we will fix it.

> Really, I want to divide some words into two pages by docx.Any other solutions you know?

duplicate with https://github.com/typora/typora-issues/issues/118, but current workaround `<div style="page-break-after: always;"></div>` does not work for pandoc export. Related discussions will be moved there

**Comment by abnerlee** [comment]
should be fixed in our latest version
