### ISSUE TITLE
Can't input "zi" with font-matter and chinese input method in win11 

### ISSUE THREAD

**Issue by lyujp** [typora/typora-issues#5891]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

1. Open a markdown file, the beginning of the file contains some font-matter information. 
2. Input "zi" in first line with chinese input mothod, the cursor will move to font-matter. 

**Expected behavior**
It should input 字.

**Screenshots / Screencasts**

[If applicable, add screenshots / screencasts to help explain your problem.](https://github.com/typora/typora-issues/assets/139390536/ff47a87e-45dd-4d76-abb2-54fc537b955d)

**Sample Markdown File**

My font-matter like this:

```
---
title: 123
date: 2023-11-14 22:51:17
updated: 2023-11-14 22:51:17
tags:
categories:
---

```

**Desktop (please complete the following information):**
 - OS: [Windows 11 64bit]
 - Default Chinese input method

**Typora Version**
e.g:1.7.6

**Additional context**

**Comment by abnerlee** [comment]
duplicated with #3318
