### ISSUE TITLE
Failed to upload image, it shows that the path needs to be set

### ISSUE THREAD

**Issue by FLSZ** [typora/typora-issues#5892]
![image](https://github.com/typora/typora-issues/assets/98043316/33ee387e-cd0a-4482-9a43-7784dd3c9dc4)

![image](https://github.com/typora/typora-issues/assets/98043316/a7336a75-772a-4029-9ae1-2232967e01e6)

**Comment by abnerlee** [comment]
Fixed in 1.8-dev, will port to stable version later.

Current workaround is to

1. change image uploader to PicGo.app
2. set PicGo.app path as any string
3. switch back to PicList

**Comment by abnerlee** [comment]
fixed in 1.8.x
