### ISSUE TITLE
Automatic update interrupted

### ISSUE THREAD

**Issue by Rolograaf** [typora/typora-issues#5896]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Tried a few times, but with the pop-up message that a new version is available for installation,I get error message:

![image](https://github.com/typora/typora-issues/assets/6130902/a6a80f51-21c0-427b-bfef-d118ee261690)
The download of typora-update-x64-1.8.1-dev.exe was interrupted

**To Reproduce**

**Expected behavior**
I can use Typora, just not update it to latest via automatic version check

**Screenshots / Screencasts**
see above

**Sample Markdown File**
not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10 32bit

**Typora Version**
1.7.6

**Additional context**
has always worked like a dream

**Comment by abnerlee** [comment]
should be fixed

**Comment by hsandt** [comment]
Still get this on Windows 11 (26100.4946), from 1.10.8 to 1.11.7

> New version available. Latest version is 1.11.7, your version is 1.10.8

<img width="494" height="319" alt="Image" src="https://github.com/user-attachments/assets/671aa50a-4289-4655-8d78-de1f245a48e8" />

I tried closing the window before downloading upgrade in case it was the blocker, it didn't help.

Typora installation method: standard installer, into Program Files.

**Comment by hsandt** [comment]
I found this new issue detailing why the error only occurs with 1.11.7, due to bad version access: https://github.com/typora/typora-issues/issues/6413
