### ISSUE TITLE
Ubuntu / Light Mode and Dark Mode

### ISSUE THREAD

**Issue by mavlutovr** [typora/typora-issues#5904]
Hi!

Could you add the feature for Ubuntu (especially for KDE)?

![](https://support.typora.io/media/new-97/Screen%20Shot%202020-12-05%20at%2017.01.49.png)

**Comment by abnerlee** [comment]
should be fixed in 1.8.8

**Comment by mavlutovr** [comment]
Yes, it works!
Thanks a lot!
