### ISSUE TITLE
fail to launch on ubuntu wayland

### ISSUE THREAD

**Issue by iiiian** [typora/typora-issues#5906]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
fail to launch on ubuntu wayland

**To Reproduce**
1. open terminal
2. launch typora by typing `typora --ozone-platform-hint=auto`
3. after a few sec, an error is shown "[148247:1202/135000.001244:ERROR:gpu_process_host.cc(943)] GPU process exited unexpectedly: exit_code=512", typora fail to launch.

**Expected behavior**
typora launch

**Desktop (please complete the following information):**
Ubuntu 23.10

**Typora Version**
1.7.6

**Additional context**
this problem does not exist in xwayland

**Comment by abnerlee** [comment]
Please try with `--disable-gpu` and / or `--disable-gpu-sandbox`, does that fixes it?

**Comment by iiiian** [comment]
yes, --disable-gpu-sandbox does work. Thank you.
