### ISSUE TITLE
String not display completely in the mermaid preview on Mac

### ISSUE THREAD

**Issue by xiaoyuan-sun** [typora/typora-issues#5910]
**Describe the bug**
The strings in flowchart preview are not displayed completely, pls see the below img.
<img width="990" alt="image" src="https://github.com/typora/typora-issues/assets/135931691/a90afb85-d3d6-4a19-a2f8-9de22c843934">

**Sample Markdown File**
```
graph TD
    A[test] --> |one se| B[B Node]
    B --> C{Is ok?}
    C --> |yes| D[ok]
    C --> |no| E[not ok]
```

**Desktop:**
 - OS: Mac OS 13.3.1 

**Typora Version:**
- Version 1.7.6 (7018)
- Typora Theme: **Github(default)**

**Comment by abnerlee** [comment]
Did you zoom your display or Typora?

**Comment by abnerlee** [comment]
may duplicated with #5864

**Comment by xiaoyuan-sun** [comment]
> may duplicated with #5864

Solved, after reseting to actual size
