### ISSUE TITLE
Cursor jumps backward unexpectedly while entering text (scenario #1)

### ISSUE THREAD

**Issue by miciasto** [typora/typora-issues#5912]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/
----
**Describe the bug**
Cursor jumps backward unexpectedly while entering text.

**To Reproduce**
1. Enter the following text on a new line: 
```
==:smile:==
```
2. Move the cursor to the end of the line.
3. Type xx

**Observed**: 
```
==:smile:=x=x
```

**Expected**:
```
==:smile:==xx
```

**Desktop:** OS: Windows 11 64 bit and Ubuntu 22.04
**Typora Version**: 1.7.6

**Comment by abnerlee** [comment]
put into #5916

**Comment by miciasto** [comment]
Confirmed fixed in 1.8.3-dev (Windows).  Thank you!
