### ISSUE TITLE
Cursor jumps backward unexpectedly while deleting text

### ISSUE THREAD

**Issue by miciasto** [typora/typora-issues#5914]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in built-in themes without customized css.
- [x] Searched http://support.typora.io/
----
**Describe the bug**
Cursor jumps backward unexpectedly while deleting text.

**To Reproduce**
Step 1. Enter the following text on a new line: 
```
==:smile:12==
```
Step 2. Move the cursor immediately before the 1.
Step 3. Press the delete key twice

**Observed**: 
```
==:smile2==
```

**Expected**:
```
==:smile:==
```

**Desktop:** OS: Windows 11 64 bit and Ubuntu 22.04
**Typora Version**: 1.7.6

**Comment by abnerlee** [comment]
put into #5916

**Comment by miciasto** [comment]
Confirmed fixed in 1.8.3-dev (Windows).  Thank you!
