### ISSUE TITLE
Cannot change the font size when exporting to pdf

### ISSUE THREAD

**Issue by SoyMark** [typora/typora-issues#5917]
I changed the font size in setting, the change applied in app but had not effect on exported PDF.
I modified the .css file of the theme I used, changing the font-size under html to 12px, but it didn't work. 
I created my base.user.css and my base.{theme}.css, and wrote down the font size there, but it didn't work.
I modified the export setting for PDF, add things to Append Extra Content(HTML), but it didn't work.
I read almost every articles on Internet to solve the problem, but none of them worked. 
Meanwhile, my effort to change the margin in the setting didn't work. 
It seems that every changes I made will not affect the format of the exported PDF.

Appreciate any advice!

**Comment by abnerlee** [comment]
Hi,

What is your operating system and Typora version? If you export to HTML, are those font-size applied? If you open your exported HTML in Safari or Chrome, print it into PDF, are those font-size applied in output PDF?
If you set font size to different value, like 16px, and export to PDF, does the PDF have different font size with the one you export with 12px font size?
