### ISSUE TITLE
Feature request: directory tree in side panel as in gedit

### ISSUE THREAD

**Issue by aloboa** [typora/typora-issues#592]
My idea was to use Typora for my notes, which I take in markdown.
The idea is having them organized in a directory tree, and thus would
be so convenient having a side panel with the directory tree, i.e. as
in gedit: https://wiki.gnome.org/Apps/Gedit/Screenshots?action=AttachFile&do=view&target=screenshot-gedit-side-panel-file-browser.png
Thanks

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/57
