### ISSUE TITLE
Table cell/ contents alignment

### ISSUE THREAD

**Issue by samp1888** [typora/typora-issues#5920]
Hi and thanks for a great piece of software, I am new to Markdown, Typora, Github, etc.. so apologies in advance, I have been working away on a document and ran into an issue with alignment of the tables when exporting to pdf using pdflatex / pandoc option in typora.
The contents of the table appears centred in typora and pdf export from Typora using pdf option produces a centered table but when using the pandoc pdflatex engine the contents of the table becomes left aligned. 

Typora view:
![image](https://github.com/typora/typora-issues/assets/153950817/ba3bcbe6-fe31-4a7c-8411-ff74f0915ec3)

Pdf output (pandoc - pdflatex)
![image](https://github.com/typora/typora-issues/assets/153950817/4acd7869-517a-4b52-90d6-fe8a4876a1ec)

When converting md to tex I can see a longtable definition is created and adding a c in the tex definition works but I would like to do this from md if possible.

Not too sure how to fix, I have  asked the question on the Pandoc page but do not fully understand the question they are asking me: https://github.com/jgm/pandoc/issues/9258#issuecomment-1858938654

Thanks for your support.

**Comment by abnerlee** [comment]
By default the cell is not aligned, and the default style in your current Typora theme is center-align, while the default style in pandoc PDF export may be left-align.

You can do center align by click the cell, and click the center align button in the popped table editing tooltip. see https://support.typora.io/Table-Editing/#text-alignment-in-column
