### ISSUE TITLE
[Bugs] Hello! Video playback requires 2 clicks to maximize

### ISSUE THREAD

**Issue by zhouxinghong** [typora/typora-issues#5924]
Please check the detailed description information:
https://github.com/typora/typora-issues/issues/5847
Hope this problem can be fixed in the next version, thank you very much!

**Comment by zhouxinghong** [comment]
Never been able to play YouTube videos in full screen.
![image](https://github.com/typora/typora-issues/assets/54253524/d571676d-8c14-4906-b6e2-5bc74721454e)

**Comment by zhouxinghong** [comment]
Hi! Friends, this error still exists in the latest version 1.8.10. So I'm opening this question again.

**Comment by abnerlee** [comment]
duplicated with #5847
