### ISSUE TITLE
[shortcut] Please allow shortcut to copy as plain text so chatgpt users' life become easier. thx

### ISSUE THREAD

**Issue by ccchan234** [typora/typora-issues#5929]
in chatgpt's web,
currently if you copy using the clipboard icon, it's in markdown format.

i now have to 
1. paste into typora, 
2. then select all and 
3. manually choose copy as plain text

if typora provide that shortcut,
i can simply
1. paste into typora
2. select all
3. copy

life will be easier, thanks

**Comment by abnerlee** [comment]
You can change Default Copy Behavior https://support.typora.io/Copy-and-Paste#default-copy-behavior to copy in rich format and plain text by default.
