### ISSUE TITLE
Cross-page tables with latex formulas in the header will be messed up when exported to pdf

### ISSUE THREAD

**Issue by moolawooda** [typora/typora-issues#5932]
If the input form is particularly long (for example, 50 lines), exported as a pdf, the table header if the latex format of the mathematical formulas will be garbled

For example, if the table is short and does not span pages:
```markdown
| 1    | 11$A_x-B_y$22 | $\omega_x$ |
| ---- | ------------- | ---------- |
| 2    | 1             | 0.1        |
| 0    | 2             | 0.2        |
| 3    | 3             | 0.1        |
| 2    | 4             | 0.1        |
| 2    | 5             | 0.1        |
```
The exported result is shown below, the table header formula is normal:
![图片](https://github.com/Keldos-Li/typora-latex-theme/assets/103896544/b1cd1d49-b6e8-4896-8933-623385cded0b)

But for particularly long tables, such as the one below, it displays normally in TYPORA:
```markdown
| 1    | 11$A_x-B_y$22 | $\omega_x$ |
| ---- | --------- | ---- |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 1 | 0.1 |
| 0    | 2 | 0.2 |
| 3    | 3 | 0.1 |
| 2    | 4 | 0.1 |
| 2    | 5 | 0.1 |
| 2    | 8 | 0.1 |
| 2    | 8 | 0.1 |
```
But after exporting to pdf will be across the page, the table header formulas have become garbled (export and print to pdf will be so):
![图片](https://github.com/Keldos-Li/typora-latex-theme/assets/103896544/8db88e5b-abd7-42f1-ae22-2f12b926ae63)

typora version: 1.7.6
pandoc version: 3.1.11

**Comment by fmarkulin** [comment]
I have the same issue
![image](https://github.com/typora/typora-issues/assets/65983876/2b43ee98-cb72-45fc-85f3-8ad0136e932c)
