### ISSUE TITLE
[bug] Windows OS : caption position is too high to move the Window

### ISSUE THREAD

**Issue by emako** [typora/typora-issues#5933]
Sometime launch the .md file, and the caption position is too high to move the Window.

**Desktop (please complete the following information):**
Windows 11 pro 23H2 (22631.2861)

**Typora Version**
e.g: 1.7.6

**Additional context**
![image](https://github.com/typora/typora-issues/assets/24737061/839aa1b9-6270-4424-be8a-5e982c837162)

**Comment by loopernow** [comment]
I have the same bug, reported here: https://github.com/typora/typora-issues/issues/5889

**Comment by abnerlee** [comment]
duplicated with #5889
