### ISSUE TITLE
Mermaid support for icon rendering

### ISSUE THREAD

**Issue by Ephron-WL** [typora/typora-issues#5934]
Mermaid does is not support the rendering of icons, which is supported by the mermaid engine.  It seems the icon may be intentionally removed or simply not included in the HTML.

How it should be included in HTML:

`<span class="nodeLabel"><i class="fa fa-external-link-alt"></i></span>`

How it is actually included:

`<span class="nodeLabel"></span>`

Flowcharts - Basic Syntax > [Basic support for fontawesome](https://mermaid.js.org/syntax/flowchart.html#basic-support-for-fontawesome)

This is not a duplicate of #286 ,  since that issue refers to general support.  The second post refers to the issue in mermaid, which is off-topic.

My platform: Windows
Version: 1.7.6

**Comment by abnerlee** [comment]
Still should be covered in #286 

Currently Typora is not bundled with FontAwesome, so icons are not supported in mermaidJS. Even we bundle it, mermaid is using FontAwesome v5, while the latest FontAwesome is v6, so which version Typora should bundle still need consideration.

**Comment by Ephron-WL** [comment]
I don't understand your response.  Why is it that you cannot bundle v5 with Typora if the current version of fontawesome is v6?  According to issue #286 you don't support the current version of fontawesome because it is not a common enough markup syntax.  I would think this would make it more likely you'd want to bundle the older version of the library to support the mermaid feature.  Are you worried people will start asking for the newer version of the library and then you will need to reconcile those requests and the fact you don't support the generally proposed font syntax with the support for mermaid? 

I use a custom theme with Typora.  I was thinking that maybe I can import the library via the theme css file (I don't know if this will work).  But, if you aren't rendering the HTML to include the font class then it will not make any difference and won't render anyway. 

I think you should support it.  It would make your product incrementally better.
