### ISSUE TITLE
In Windows, files and folder starting with a dot are hidden by Typora

### ISSUE THREAD

**Issue by raffaeler** [typora/typora-issues#5938]
- [X] Searched existing issues to avoid creating duplicates.
- [X] Confirmed that it can be reproduced in built-in themes without customized css.
- [X] Searched http://support.typora.io/

----

**Describe the bug**
This is a side effect of the issue #1749.

Files and folder starting with a dot are visible in Windows and should be the same on Typora as well.
This is the opposite behavior described for Mac and Linux where those files and folders should be hidden.
I believe that in Windows Typora should revert the behavior and show them in the file/folder tree.

**To Reproduce**
1. Open a folder in Windows explorer.
2. Create a folder starting with a dot from Windows explorer
3. Open the parent folder from Typora 
4. The folder starting with a dot is not visible

**Expected behavior**
In Windows I expect that files/folders starting with a dot to be visible.

**Screenshots / Screencasts**
N/A

**Sample Markdown File**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
1.7.6

**Additional context**
N/A

**Comment by abnerlee** [comment]
should be solved by #1753
