### ISSUE TITLE
Math equations looks poorly in exported pdf?

### ISSUE THREAD

**Issue by Geliv** [typora/typora-issues#594]
I try to export the file as pdf. All other parts looks great, but the formulas looks too bold and not clear in exported pdf. Just as shown in the following picture
![image](https://cloud.githubusercontent.com/assets/20089973/23899885/f7cf4a7e-08f1-11e7-8a7d-3ba4ae20a7db.png)

Anyone knows how to resolve the problem?

**Comment by abnerlee** [comment]
Operation System version?

**Comment by Geliv** [comment]
Windows 10, latest version of typora

**Comment by Geliv** [comment]
The formulas looks great when directly use pandoc to generate pdf. But the style of exported pdf looks not as good as what typora generates and css style has no effect at all.

**Comment by gatlinnewhouse** [comment]
I was going to type:

> I've looked into this on my own and if you manually use MathJax while compiling the markdown document to pdf then the equations seem to render fine, but something about the MathJax call parameters (I do not know if that is the right term, perhaps HTML import?) in Typora do not render very well. I think it has to do with the font weight being requested from MathJax?

But since @Geliv says that:

> the style of exported pdf looks not as good as what typora generates and css style has no effect at all. 

I would be tempted instead to ask if you can test print both the Typora generated pdf and the pandoc generated pdf to compare the equation output. I found, at least on linux using qpdfview, that if you zoom in enough on the Typora generated pdf equations, the font weirdness goes away. Perhaps this is an issue with your pdf viewer?

**Comment by Geliv** [comment]
Many thanks to gatlinnewhouse！
I've tested many different pdfviewers, the pdf generated by typora looks weird in all viewers on windows but looks great on iPhone and iPad (I don't have Mac to test).
After printing, the file printed from typora generated pdf looks basically normal with mathfont a little bolder. Since Pandoc generate pdf through `Latex` engine, the math equations are not `.svg` figures and the pdf looks great on all platforms.

BTW, how do you manully use Mathjax while compliing the markdown to pdf? Many thanks again!

**Comment by gatlinnewhouse** [comment]
No problem! 

Although I think the font for math in Typora should not be a bolder than the text @abnerlee.

> BTW, how do you manully use Mathjax while compliing the markdown to pdf? Many thanks again!

Export to HTML then print to PDF with a fake printer (I use cups-pdf).

**Comment by Geliv** [comment]
@gatlinnewhouse 

> Export to HTML then print to PDF with a fake printer (I use cups-pdf).

This software cannot be used in windows. But I suppose it's just the same as I print html file to pdf using Chrome or other browsers? Math equations will still be just `.svg` vector image?

**Comment by gatlinnewhouse** [comment]
@Geliv yes, you are correct, it's the same as printing to a pdf in chrome but system wide. Math equations then are just MathJax svgs in the HTML output.

**Comment by abnerlee** [comment]
Fixed in new release
