### ISSUE TITLE
[Feature] add support for \[...] style latex formula

### ISSUE THREAD

**Issue by nuitlejour** [typora/typora-issues#5941]
I have a bunch of markdown files converted from literature containing scientific formula, the latex formula is in 
![截图_20240110165753](https://github.com/typora/typora-issues/assets/20106317/cd447d1d-5166-46a8-b889-751425739607)
style; after some research I found typora only support 
![截图_20240110165744](https://github.com/typora/typora-issues/assets/20106317/7133bbc9-b8bc-4fbd-bb6e-479a6b41b5ec)
style formula. 

Could you please add an option to support 
![截图_20240110165753](https://github.com/typora/typora-issues/assets/20106317/0121ebf2-bbfd-466b-8271-655897e98b63)
 style latex, PLEASE~

**Comment by Blackhawke** [comment]
LaTeX math support is becoming a more common feature in markdown. A lot of editors now support it, so I hope they'll add it too.

But if they do, I hope that they stick to the standard LaTeX style/command structure. At least one markdown based editor I know of decided to break it by doing their own thing with the ``$$`` command for inline math formulas. (It's not the only existing command structure they've crapped on, either.)

**Comment by abnerlee** [comment]
duplicated with #63
