### ISSUE TITLE
Typora fails to launch on ArchLinux via Flatpak

### ISSUE THREAD

**Issue by demellj** [typora/typora-issues#5942]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
When running typora through flatpak on ArchLinux I get the following error:
`[2:0113/120436.595052:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 12:04:37.085: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:04:37.087: Failed to load module "canberra-gtk-module"
[2:0113/120437.115801:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0113/120437.115906:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

**To Reproduce**
1. `flatpak run io.typora.Typora`

**Expected behavior**
The program should launch

**Desktop (please complete the following information):**
 - OS: ArchLinux (via flatpak)

**Typora Version**
e.g: 1.7.6

**Additional context**
This may be an issue with electron bundled in with the flatpak. The closest thing I found to this issue with my googling skills is this: https://github.com/cypress-io/cypress/issues/4925

**Comment by abnerlee** [comment]
Would you try https://github.com/flathub/io.typora.Typora/issues/12?

> The problem was gone after I turned off the wayland support in the flatseal.
