### ISSUE TITLE
Open recent keeps a blank window open, and you have to manually close it. 

### ISSUE THREAD

**Issue by dessalines** [typora/typora-issues#595]
A **really** annoying issue is that if you open up typora(and have a blank window), then click open recent, and open a recent file, you now have two open windows, one blank and your new one, so you have to close out the blank one. Typora should know to close the original window.

**Comment by abnerlee** [comment]
Typora now will try to load the file in place if your current file is a new untitled file. 
But still, if current typora window is not fully loaded, a new window will pop up.

I will close this, since in most time, open recent can be opened in the same window
