### ISSUE TITLE
Ubuntu 23.10 unmet dependencies

### ISSUE THREAD

**Issue by miostreams** [typora/typora-issues#5954]
Unable to upgrade from Typora 1.7.6 to 1.8.5

OS: Ubuntu 23.10

The following packages have unmet dependencies:

gconf2, gconf-service, gvfs-bin, python

This appears similar to the following issues:

https://github.com/balena-io/etcher/issues/4144
https://github.com/balena-io/etcher/issues/4096

I manually installed the gconf packages but the upgrade still complains about missing gvfs-bin and python (gvfs and python are both installed on this system.)

The following packages have unmet dependencies:
typora : Depends: gvfs-bin which is a virtual package and is not provided by any available package
Depends: python which is a virtual package and is not provided by any available package

**Comment by typoworx-de** [comment]
same here with Ubuntu 23.04, but at least gconf2 is installable. But this only makes sense while using gnome-based desktop environment, users running other Desktops won't essentially want/need to install gconf2.

These are my **missing** packages on Ubuntu 23.04:
- gvfs-bin UNAVAILABLE
- python UNAVAULABLE

**Suggests**
- libgnome-keyring0 UNAVAILABLE

**Comment by abnerlee** [comment]
duplicated with #5953
