### ISSUE TITLE
[Feature] When exporting to HTML, to be an option thus any linked image to be converted and embedded as base64 encoding

### ISSUE THREAD

**Issue by terablade2001** [typora/typora-issues#5955]
Hi.

The problem I face, is that when I make reports with custom styles and with images and want to shared them in a scroll-able form (not for printing/pages) to external partners who don't use typora, or not the custom styles I do use, in order to enforce my styles I tend to export to HTML. Still, I have each time to provide a .zip with multiple files (HTML and images) which is a huge drawback. I already, manually, have implement a python script to convert the images to base64 encoding, in order to edit the HTML file and replace correspondingly all the `img` tags with their embedded base64 code. That way I can send one single file, with my typora's styles, which can be directly opened without the need of files preprocessing (unziping etc) by the recipients. But it's a whole workaround, prone to human errors and must be manually repeated for every change/export.

So, I was wondering if this custom approach, could be implemented as an option during the exporting to HTML pages directly. For me it seems straightforward and simple (as I already do it manually). Would be possible to consider that export-to-HTML option as an implementation for a future update?

Thanks.

**Comment by abnerlee** [comment]
put into #2074
