### ISSUE TITLE
Typora 1.8.6 on Windows - Code Fence Default Language Won't Work

### ISSUE THREAD

**Issue by Konjac-XZ** [typora/typora-issues#5957]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The Last Used feature of Code Fence's default language behaves abnormally.

**To Reproduce**
1. Set Default Language to cpp.
2. Create a code fence and type "cpp".
3. Move out of Code Fence and enter three more backquotes.

**Expected behavior**
Typora should autofill the letters cpp.

**Screenshots / Screencasts**
![image](https://github.com/typora/typora-issues/assets/71483384/45d492eb-fb5f-484f-849a-519265d60bd0)
**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.
Blank documents can also reproduce the problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]
Windows 11 Pro

**Typora Version**
1.8.6

**Comment by abnerlee** [comment]
It works fine in my test, could you provide a screencast of this?

**Comment by Konjac-XZ** [comment]
[Videos.zip](https://github.com/typora/typora-issues/files/14061282/Videos.zip)
Sure. Here are two videos, the first triggers the bug in a document with content, the other in a newly created blank document.
BTW, I forgot to record my settings page, but my settings are:
![image](https://github.com/typora/typora-issues/assets/71483384/7f5c7389-4a6b-437b-afd3-c6a618467f05)

**Comment by Konjac-XZ** [comment]
I just uninstalled and reinstalled Typora and the problem persists.

**Comment by abnerlee** [comment]
Does this work without Sougo IME?

**Comment by Konjac-XZ** [comment]
> Does this work without Sougo IME?

Oh, it works. Sorry for bothering you.
