### ISSUE TITLE
New Tab in Fullscreen Mode Takes a Small Portion of Screen

### ISSUE THREAD

**Issue by tzm41** [typora/typora-issues#596]
When using Typora in fullscreen mode and use cmd+N to open a new tab, the new tab's content takes up a small portion of the screen. Exiting and reentering fullscreen mode resolves the issue.
![screen shot 2017-03-17 at 12 27 11 am](https://cloud.githubusercontent.com/assets/5728283/24028822/911a7976-0aa8-11e7-9f4a-eb19dc192a74.png)

**Comment by abnerlee** [comment]
should be fixed in new release
