### ISSUE TITLE
Mermaid diagrams are not rendering -  1.8.8 on PopOS 22.04

### ISSUE THREAD

**Issue by ziraqyoung** [typora/typora-issues#5960]
- [x] Searched existing issues to avoid creating duplicates.

- [x] #5961

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Markdown diagrams are not rendering.

**To Reproduce**
1. Create a new markdown document
2. Add this sequence diagram example from [docs](https://support.typora.io/Draw-Diagrams-With-Markdown/)
     ```sequence
        Alice->Bob: Hello Bob, how are you?
        Note right of Bob: Bob thinks
        Bob-->Alice: I am good thanks!
      ```
4.  Diagram not rendering on focusing out of the code 

**Expected behavior**
Diagram source code to be converted into a diagram.

**Desktop (please complete the following information):**
 - OS: PopOS 22.04

**Typora Version**
 typora_1.8.8_amd64.deb

**Comment by abnerlee** [comment]
Please enable diagarm features in preferences panel first.
