### ISSUE TITLE
Feature Request: The Theme for Exporting to PDF Could Be Set Different from the Display Theme

### ISSUE THREAD

**Issue by tzm41** [typora/typora-issues#597]
Currently the theme for exported PDFs follows the theme for display. However the use case would be valid when user is composing in the dark and using the night theme, but still want the exported PDF to be using the whitey theme to look professional. At the moment we need to switch to that theme, export and then switch back. I am hoping for a setting that I could set the theme for export to be separate from the theme for display.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/823
