### ISSUE TITLE
Typora Hijacking "Open With" on all of my Unity assets (.asset and .prefab)

### ISSUE THREAD

**Issue by dmauro** [typora/typora-issues#5973]
- [ x ] Searched existing issues to avoid creating duplicates.

- [ x ] Searched http://support.typora.io/

----

**Describe the bug**
Somehow Typora has become the go to program for opening files in some contexts. The GitHub app for instance thinks I want to use Typora to resolve conflicts and also shows up when I right click those file types (.prefab and .asset) as a primary option for opening the files.

I cannot find Typora in Settings > Apps > Default Apps to adjust this, and I can't find anything in Typora's settings.

**To Reproduce**
1. Install Typora
2. Open the GitHub app
3. Double click on a changed file with .prefab or .asset extension
4. File is opened in Typora

**Expected behavior**
Opens in Visual Studio Code as before

**Desktop (please complete the following information):**
 - OS: WIndows 11 64-bit

**Typora Version**
e.g: 1.8.9

**Comment by abnerlee** [comment]
Typora has nothing to do with .prefab and .asset files.
If you double-click an .prefab or .asset file in the Windows Explorer, whill Typora be launched to open those files?

You could also try right click a .prefab or .asset file in Explorer, click always open with... and choose Visual Studio Code as the opener.
