### ISSUE TITLE
Unable to buy/enter license on Ubuntu

### ISSUE THREAD

**Issue by XiangfanLi** [typora/typora-issues#5974]
**Describe the bug**
I am using Typora on my Ubuntu machine. When I clicked Help -> My License， this window popped out, but these two buttons are totally unclickable.
![image](https://github.com/typora/typora-issues/assets/20794091/72c4de89-8079-4da4-815a-ac040c51e793)

I installed Typora by following the instructions on https://support.typora.io/Typora-on-Linux/

Typora version:
![image](https://github.com/typora/typora-issues/assets/20794091/950515cd-cf86-4ac3-a779-f4019661ef35)

I am using Ubuntu 20.04:
![image](https://github.com/typora/typora-issues/assets/20794091/020c4bfa-9765-4019-bcad-bffa40288c68)

**Desktop (please complete the following information):**
 - Ubuntu 20.04:

**Typora Version**
1.8.9-1

**Comment by abnerlee** [comment]
should be fixed in 1.8.10
another workaround is to reset zoom to actual size (100%) under View menu.
