### ISSUE TITLE
Feature Request: Switching from MathJax to readme2tex

### ISSUE THREAD

**Issue by gatlinnewhouse** [typora/typora-issues#598]
Could Typora switch from using MathJax to something like [readme2tex](https://github.com/leegao/readme2tex)?

Also just a note, readme2tex generates better latex equations than MathJax. Plus you can use the `--nocdn` flag during compilation to generate the source images for the LaTeX equations locally with relative paths.

**Comment by abnerlee** [comment]
Seems interesting, but we do not have plan for this in near feature, main concern is:

It is a python project, we do not want to include a python runtime inside, or ask users to install python/readme2tex.

We will look this back after we finished our other tasks/features.
