### ISSUE TITLE
[Feature] MAKE ARTICLES VIEW GREAT AGAIN

### ISSUE THREAD

**Issue by 1999FordFocus** [typora/typora-issues#5986]
Dear @abnerlee 

Can we just have the `Article View` show all files?

Pleaaaaaaaaaase.

**Comment by abnerlee** [comment]
you mean #1753?

**Comment by 1999FordFocus** [comment]
> you mean #1753?

It's https://github.com/typora/typora-issues/issues/4374

<img width="264" alt="image" src="https://github.com/typora/typora-issues/assets/9652173/8d20a3ba-c7f5-4d29-99a6-b852733a1aa3">

**Comment by Louis24** [comment]
yes pls
