### ISSUE TITLE
Github Style Alert / Callouts not working (V 1.8.9)

### ISSUE THREAD

**Issue by rmueck** [typora/typora-issues#5989]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Github Style Alert / Callouts are not rendered correct

**To Reproduce**
1. Generate md file
2. Add code for gfm Alert (Note)

**Expected behavior**
Github Style Alert / Callouts  rendered correctly

**Sample Markdown File**
```
```gfm
[!NOTE]
Highlights information that users should take into account, even when skimming.
```
**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3

**Typora Version**
1.8.9 /flatpak)

**Comment by EvansMatthew97** [comment]
Typora formats my alerts like this (menu -> Paragraph -> Alert):

```md
> [!NOTE]
>
> This is a note
```

**Comment by rmueck** [comment]
Thanks EvansMatthew92 :+1: !
I have overseen the correct syntax. It works fine now.

**Comment by luisgaruzweb** [comment]
How can you add other Alerts/Callouts like [!Summary]?
