### ISSUE TITLE
Mac OS 10.7 support?

### ISSUE THREAD

**Issue by ili-codes** [typora/typora-issues#599]
I use a Mac Mini for my writing and decided to try out Typora on it. It's a 2007 model so its max OS version is 10.7. Is there a way to run the app on 10.7? I think it's based on Electron so is there a way I can just put the HTML files into Firefox? Sorry if I sound like a total newbie... I'm new to Electron.

**Comment by abnerlee** [comment]
Sorry, we design and implement Typora for modern OS. 

10.7 seems too old, and it is already costs a lot of time testing typora on 10.9, 10.10, 10.11 and 10.12, so we do not want to deal with any older version.

And Typora on macOS is not based on Electron, the Windows/Linux versions are, yet old OS such as Windows XP are not supported.
