### ISSUE TITLE
Cannot Print (segfault)

### ISSUE THREAD

**Issue by rmueck** [typora/typora-issues#5991]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Cannot print from typora (bin & flatpack). Typora crashes with:
~~~
kernel: [ 3754.449270] Typora[609506]: segfault at 168 ip 0000560c5d48d184 sp 00007fff2a77fba0 error 4 in Typora[560c59632000+79c9000]
~~~

**To Reproduce**
1. Open any file
2. Initiate Printing

**Expected behavior**
Printing should work

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3

**Typora Version**
1.8.9

**Comment by abnerlee** [comment]
duplicated with #5033
