### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by Dr-Kaisa** [typora/typora-issues#5997]
![Snipaste_2024-03-07_22-17-55](https://github.com/typora/typora-issues/assets/121852722/34f169c6-fd64-446a-8635-2ea20042342f)
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

**Typora Version**
e.g: 0.10.11

**Additional context**

**Comment by abnerlee** [comment]
What is the Typora version?

Does re-install work?

Could you provide the steps to reproduce this dialog?

**Comment by Dr-Kaisa** [comment]
> 什么是Typora版本？
> 1.85
> 重新安装是否有效？
> yep，i rein
> 您能否提供重现此对话框的步骤？



> What is the Typora version?
> 1.85
> Does re-install work?
> yeah,i re-install 1.76 ,and does it work
> Could you provide the steps to reproduce this dialog?
i uesd 1.50 for many times,and then update to 1.85, i open the md-file i wrote before,the dialog produce
