### ISSUE TITLE
"Simple, yet powerful"

### ISSUE THREAD

**Issue by Fastidious** [typora/typora-issues#6]
On the website, the portion of screenshots under "Simple, yet powerful" moves too fast. I recommend to leave it to user interaction to flick through the screenshots instead, or greatly increase the timer, so one have the time to see it for a bit longer.

**Comment by taoyuan** [comment]
＋1

**Comment by abnerlee** [comment]
Thanks for the feedback. Timer has been increased, and stops slider when user want to flick screenshots manually.
