### ISSUE TITLE
Centerd image in Typora get left-aligned in exported PDF

### ISSUE THREAD

**Issue by reflectionalist** [typora/typora-issues#600]
Inside Typora, an image is centered by default, but in the exported PDF, the image is left aligned.  Is this a feature or misfeature?  Is there a way to adjust the alignment of an image in the exported PDF?

**Comment by gatlinnewhouse** [comment]
You could try exporting to HTML and then converting the exported HTML to PDF.
You could rewrite the image markdown to HTML as:

```html
<img src="/path/to/your/image.jpg" style="margin-left: auto; margin-right: auto; display: block;">
```

**Comment by abnerlee** [comment]
Seems a bug, if image is center aligned in Typora, then it should also be center aligned in exported HTML/PDF.

**Comment by geodatup** [comment]
as a workaround, add css rules in your  css theme file 
`img { max-width: 100%; vertical-align: middle; margin-left: auto; margin-right: auto; display: block; }
`
When you export PDF directly images are center align

**Comment by abnerlee** [comment]
This is fixed in newest version.

Image is centered by default, but also allow users to change this behavior via custom css/theme
