### ISSUE TITLE
css fails to render

### ISSUE THREAD

**Issue by EganSolo** [typora/typora-issues#6002]
Typora version: 1.8.10 on Win 11 64 bits
------------------
I added the following css snipet to the end of base.user.css:

```css
/** Additional Custom CSS **/
span.cabry-string{
   color: darkgreen;
}
```

In typora, I typed 

```html
<span class="cabry-string">This is a string</span>
```

Typora fails to render the string in dark green.

Please advise.
-------------------
Here is a fully formed HTML file with the css above which I tested in the online editor of [W3School](https://www.w3schools.com/css/tryit.asp?filename=trycss_default):

```html
<!DOCTYPE html>
<html>
<head>
<style>
span.cabry-string{
   color: darkgreen;
}
</style>
</head>
<body>
<h1>Dark Green span</h1>
<p> This is a <span class="cabry-string">Cabry string</span></p>
</body>
</html>
```

**Comment by abnerlee** [comment]
`class` and `id` are not rendered in typora for some reasons (like, you can use class to do `display:none` in editing view and cause editing not work since they are invisible), they work after export.
