### ISSUE TITLE
[Feature] Fold document content based on title

### ISSUE THREAD

**Issue by shui-dun** [typora/typora-issues#6004]
When click on the title, fold the content under that title, just like vscode. This way you can easily copy those content.

![image](https://github.com/typora/typora-issues/assets/46079921/7eddf19f-b2d6-4ccd-9491-8364919be800)

![image](https://github.com/typora/typora-issues/assets/46079921/9758a6de-7743-4447-99aa-e8cb16b8dc02)

**Comment by abnerlee** [comment]
duplicated with #499
