### ISSUE TITLE
Typora vs Github math $$ blocks incompatible? 

### ISSUE THREAD

**Issue by abbotware** [typora/typora-issues#6007]
I was a bit surprised to see that typora and github mathblocks are not compatible? 

see [example](
https://github.com/abbotware/abbotware/blob/dev/cleanup/Common/Abbotware.Quant/Documentation/formulas.md)

Top formulas render fine in typora - the bottom example i copy/pasted from the [github math documentation](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-expressions-as-blocks)

I set the inline math setting, but that doesn't seem to make a difference.  

Is there some other setting that can be used to make it render correctly in both places?

**Comment by abnerlee** [comment]
duplicated with #5556

**Comment by abbotware** [comment]
I saw that bug report... I did not think it was the same since - #5556 - specially asks for ''' math blocks -  GitHub also supports. $$ notation...
