### ISSUE TITLE
[Feature] Add options to save picture file (pasted from clipboard) default to at the same markdown file directory and using relative file path instead of absolute file path

### ISSUE THREAD

**Issue by Qynklee** [typora/typora-issues#6009]
When paste picture from clipboard to md file, Typora had `Copy Image to ...` option. 
Default save location is previous save folder. And path file using is absolute path. It make markdown file after upload to git or change directory will be lost all picture. So I think we need to add settings options is:
 - Set default location for `Copy Image to...` option is same markdown file folder.
 - Set path file using for picture is relative path instead of absolute path.
 - Or create setting to create `img` or 'image` subfolder of markdown file to save all picture file when paste picture from clipboard.
 
![image](https://github.com/typora/typora-issues/assets/23394219/11fcc688-04da-4692-be65-9d9429d12b03)

**Comment by kimstars** [comment]
very useful. Hope Admin fix this feature soon

**Comment by abnerlee** [comment]
See https://support.typora.io/Images/#copy-image-files-to-target-folder-when-inserting-local-image and https://support.typora.io/Images/#use-relative-path
