### ISSUE TITLE
Support notational velocity workflow, quick note search and note taking

### ISSUE THREAD

**Issue by kossmoboleat** [typora/typora-issues#601]
I use [nvAlt](http://brettterpstra.com/projects/nvalt/) and it's alright, but I'd love to have a better Markdown editor when using it. Typora's handling of preview vs editing works much better and combined with its better image support one could build a great Evernote/OneNote alternative this way.

For me note tags are not that useful, but a reasonably fast full text search is a great help.

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/57

**Comment by kossmoboleat** [comment]
I admit that the GUI components would have some similarity, but the search view needed for a note search works a bit differently. You would also need a prominent search box to make this really fast like in notational velocity or nvAlt. Note order is determined by the match score according to search terms instead of alphabetical order. It would also work with a very different storage backend, e.g. simple storage.

I understand if you're reluctant to go in either the file browser or this note search direction. There a whole different field than the reduced simple interface you have now.
