### ISSUE TITLE
bug for inline math: automatically add '\' before symbol "|"

### ISSUE THREAD

**Issue by lj8385174** [typora/typora-issues#602]
version 0.9.25 windows 10 64 bit

when typing a math symbol "|", it will be automatically changed into '\|' after reopening this file.

**Comment by abnerlee** [comment]
That happens in table cell, right?

**Comment by lj8385174** [comment]
That's right

**Comment by Zhouxing-Su** [comment]
And if we replace it with "|" in other text editor, the table will be rendered inappropriately.

**Comment by abnerlee** [comment]
Fixed in newest release
