### ISSUE TITLE
Typora rendering glacially slow

### ISSUE THREAD

**Issue by ghost** [typora/typora-issues#6025]
Over the past few months I have noticed Typora performance issues mentioned elsewhere in typora-issues but not precisely the same one I am experiencing with Typora 1.8.10 for MacOS (Sonoma). It is taking 5-10 seconds to open a document, which is a relatively new behavior.

I experience the problem opening Typora Version 1.8.10 (7132) on a Silicon M1 Mac-Mini running Sonoma Version 14.4.1 (23E224). I have attached a video screen capture showing how slow window rendering is -- including opening up the Settings page. I have also attached a video screen capture of an experiment where I simultaneously launch Typora, Marktext, and Zettlr with a TEST.md document (also attached).

**Somewhere in this issue tracking system I saw a report that running Typora as an administrator improves speed. Sure enough, when I run it as root, it is very responsive. But then I get an *UNREGISTERED* message. I have a legal version and would like to use it without a performance penalty.**

https://github.com/typora/typora-issues/assets/97126718/8460bd69-fa7b-44f4-8731-d1f22bf82b61

https://github.com/typora/typora-issues/assets/97126718/668a666a-d0ee-4472-af55-0079179336f4

[TEST.md](https://github.com/typora/typora-issues/files/14967447/TEST.md)

**Comment by abnerlee** [comment]
There is a performance drop for the system WKWebview on macOS 14.4. Marktext / Zettlr is Chromium / Electron based, so not affected by the "upgrade" of macOS.

But in my test the "TEST.md" is not that slow in your screencast, I notice slowness in more bigger files, the TEST.md is fine, however.

**Comment by abnerlee** [comment]
Does 1.9.3 improved this?

**Comment by ghost** [comment]
yes—David Ehrens
508-341-7481 (SMS)
https://ehrens.io/On Jun 24, 2024, at 11:06 AM, AbnerLee ***@***.***> wrote:﻿
Does 1.9.3 improved this?
