### ISSUE TITLE
Zoom feature on macOS

### ISSUE THREAD

**Issue by JVimes** [typora/typora-issues#603]
Feature request: zoom on Ctrl + Scroll Wheel (Cmd + Scroll Wheel on Mac, I think).

**Comment by wassimk** [comment]
I often take notes live and give technical talks with Typora up on the screen. It would be nice to zoom in with `cmd +`, zoom out with `cmd -` and `cmd 0` to reset.

**Comment by abnerlee** [comment]
Zoom is already supported on Windows, but not on macOS. So I will change the title of this issue.

**Comment by jaredellison** [comment]
Putting my vote in for this feature as well. I got used to the `cmd +` and `cmd -` zooming on the linux version of Typora and really miss it. I also love wassimk's `cmd 0` reset idea.

For now, I'm changing the font size manually in preferences.

**Comment by fmagno** [comment]
+1

**Comment by richardnnn** [comment]
+1 some times it will be incredibly useful to have an overview of the whole document

**Comment by Mike-Sundays** [comment]
+1

**Comment by rljacobson** [comment]
Hi @abnerlee. Unfortunately, this missing feature is a show stopper for me because of my retina display and eyesight. Otherwise, love the app. Looks great and is very ergonomic.

**Comment by fyubang** [comment]
+10086

**Comment by retrography** [comment]
Very troublesome with retina displays... There must be a way other than modifying all the themes one-by-one?

**Comment by xzhuo** [comment]
@abnerlee I noticed customized font size in preference. Is it possible to hook up `Ctrl + Shift + =` with increase font size in preference and `Ctrl + Shift + -` with decrease font size for mac version?

**Comment by jeremyyew** [comment]
+1

**Comment by toftul** [comment]
+1

**Comment by BlkPingu** [comment]
Is this still not added? I can't change the font size on OSX?

**Comment by phdbreak99** [comment]
Please add this feature to OSX version. Thank you!

**Comment by winddna** [comment]
+233

**Comment by BrandoZhang** [comment]
I recommend Typora to my non-programmer friends, and they definitely prefer to use zoom-in/out with shortcuts.
The main differences between zoom-in/out and font-size are in output files. If you use zoom-in/out, you just change the display, the font-size settings can remain the same as before, while changing font-size will effect the DOC/HTML/PDF file you exported.

**Comment by zychen-astroph** [comment]
Definitely I need it! Many thanks.

**Comment by roman-smirnov** [comment]
+10^100

**Comment by Neonbe** [comment]
I Need it  +10086

**Comment by mjgriffin** [comment]
I'd also like to add a vote for zoom-in/out

**Comment by Neonbe** [comment]
add a vote again for zoom-in/out

**Comment by alanbright** [comment]
+1. Typora is good to show document, when I show the image in the document, some time I have need to zoom in for details. This feature would be very useful in speech situation.

**Comment by abnerlee** [comment]
supported in new release
