### ISSUE TITLE
[Feature] 一体化外观中，失去了<刷新所有数学公式>的按钮

### ISSUE THREAD

**Issue by yang-si-hang** [typora/typora-issues#6030]
选择一体化外观，找不到<刷新所有数学公式>的按钮了

而在经典外观中，<刷新所有数学公式>在<编辑>下面
![tmp7647](https://github.com/typora/typora-issues/assets/35909928/809002af-d9e3-45fe-b59c-8170f595887d)

**Comment by abnerlee** [comment]
You can right click on titlebar to popup native menubar, and find options there.
