### ISSUE TITLE
Ability to format text as inline math from right mouse click

### ISSUE THREAD

**Issue by techlobo** [typora/typora-issues#6033]
I'm trialling Typora and like some of the features - however I'm finding some bits of it inconsistent, particularly with respect to formatting when using right mouse click (this is on Windows 10).

Examples include trying to format text as: 'Underline', 'Strikethrough' or 'Inline Math'

I can see how these are performed from the application menu (Format), but not from the right mouse click popup menu - am I missing something, or is this not supported?

**Comment by abnerlee** [comment]
duplicated with #5043

**Comment by techlobo** [comment]
Sorry but these are not duplicates - I'm not using MacOS therefore don't know about any differences in presentation.

However I can see that in Windows the right click menu popup **does not** provide ability to format 'Underline', 'Strikethrough' or 'Inline Math'. Is this intentional?
