### ISSUE TITLE
about a Javascript error

### ISSUE THREAD

**Issue by huzehao078** [typora/typora-issues#6038]
When i open some .md files, it will always occur one exception like:
Uncaught Exception:TypeError: Object has been destroyedat Timeout, onTimeout (C:\ProgramFiles\Typora\resources\app.asar\atom.js:27:74050)at listOnTimeout (node:internal/timers:569:17)at process.processTimers (node:internal/timers:512:7)
and then remind me to  > Learn Data Recovery.
But actually I dont have any data need to recovery. Maybe I quit the app withou saving. I just want to know how to closs this exception remind.

**Comment by huzehao078** [comment]
By the way, My system is Win11, and the version of typora is the latest.

**Comment by abnerlee** [comment]
> When i open some .md files

Could you attach or send us (<hi@typora.io>) the sample md file?

**Comment by huzehao078** [comment]
Actually, all the md file will cause that problem, whatever just downloaded or created. I've tried reinstall the typora, it didn't work.

**Comment by huzehao078** [comment]
I will update a video in two days.

**Comment by huzehao078** [comment]
Emm, this issue has been solved. I am sry for my stupid shit brain. I installed the IOS version for my windows OS.
