### ISSUE TITLE
Feature Request | Extended Support for LaTeX delimiters

### ISSUE THREAD

**Issue by Georgewxm** [typora/typora-issues#6040]
Dear Typora Support Team,

I am a student at MIT and my academic work often involves complex mathematical expressions, which necessitates a robust and flexible editor.

**Currently, Typora supports `$` and `$$` for triggering inline and block math modes. However, many LaTeX math learning management systems (LMS) predominantly utilize `\(` and `\)` for inline math, and `\[` and `\]` for block math. The lack of direct support for these symbols in Typora requires frequent complex substitutions, which is quite cumbersome and time-consuming.**

The addition of support for these LaTeX delimiters would not only streamline my workflow but also greatly benefit many of my peers. In fact, several colleagues have expressed that they are on the fence about purchasing Typora and would make an immediate purchase if this feature were implemented.

We appreciate the continuous improvements Typora has made and would be grateful if you could consider this enhancement. It would significantly enhance the usability of Typora for students and professionals who regularly work with LaTeX integrated documents.

Thank you for considering this request. I am looking forward to any updates you might have on this matter.

**Comment by abnerlee** [comment]
duplicated with [#63](https://github.com/typora/typora-issues/issues/63)
