### ISSUE TITLE
[feature] Image Preview with Zoom Functionality in Typora

### ISSUE THREAD

**Issue by enomothem** [typora/typora-issues#6044]
Description:
Currently, Typora offers a seamless writing experience with markdown, including image embedding. However, it lacks the ability to preview images independently with zoom functionality within the editor.

It would be immensely helpful if Typora could implement a feature where users can preview embedded images in markdown files separately, allowing them to zoom in/out for better inspection. This feature would enhance the user experience, especially when dealing with detailed images or diagrams within documents.

**Comment by abnerlee** [comment]
duplicated with #2189
