### ISSUE TITLE
Unstable with long documents

### ISSUE THREAD

**Issue by knzudgt** [typora/typora-issues#605]
I am on a Ubuntu machine.
I need to work on a long document of about 240 (type A4) pages of text and Ruby on Rails code, and the editor freezes when I try to switch theme, giving me no other choice than killing its process. 

Also, with the same long document some commands do not respond, such as:

-  `edit/select all` (while `ctrl + a` works.)

- `Paragraph/Paragraph` with all text selected using `ctrl + a`

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/68
