### ISSUE TITLE
How can I solve picgo error 422?

### ISSUE THREAD

**Issue by gihyeonjeon** [typora/typora-issues#6050]
Hi!

I'm using the automatic upload function in typora.

But I got this error message.
```
fail to parse result image path from: [PicGo INFO]: Before transform [PicGo INFO]: Transforming... [PicGo INFO]: Before upload [PicGo INFO]: Uploading... [PicGo WARN]: failed [PicGo ERROR]: StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents"}
```
I know that this problem is occurred because the same file is already uploaded in github.

I wonder if the only solution is to modify the file name.

Thanks for your helps..

**Comment by abnerlee** [comment]
This is an error reported by PicGo not Typora. 

See https://github.com/Molunerfinn/PicGo/issues/569

**Comment by gihyeonjeon** [comment]
Thanks!

So you mean that there is no special solution, but just recommend to use different file name right?

I'm not sure about that link because I'm not chinese !...
