### ISSUE TITLE
[Feature] reading model

### ISSUE THREAD

**Issue by wxdespair** [typora/typora-issues#6064]
Do you consider adding a reading mode, that is, after opening all elements can not be edited, in order to prevent format change mode,

**Comment by abnerlee** [comment]
duplicated with #4645

**Comment by tiansira** [comment]
@abnerlee I see there are many people need the read-only mode. Could you let me know if we have any plans add the feature in the near future?

**Comment by SabolchGreba** [comment]
I just purchased Typora because it is really what I need for my "knowledge management" and I could appreciate a read only mode
