### ISSUE TITLE
Can you cange the line length in the source code view to be longer

### ISSUE THREAD

**Issue by Full-Thrust** [typora/typora-issues#6068]
I'm trying to format large tables but the source code view is wrapping the text. This makes the raw tables hard to read and breaks the very nice prettier for tables :(

I looked at previous replies on this and Code fences autowrap is off, but this isn't related to code fences this is the source code view. Is there a way to disable the wrapping or set a line length for the source code view? I've trawled the prefernces and searched here first.

Thankyou for your time.

![image](https://github.com/typora/typora-issues/assets/55027364/e461647c-58f7-4ccf-bab0-f7b086d5607b)

![image](https://github.com/typora/typora-issues/assets/55027364/88b60166-d1f9-4179-8dca-15ea8c9f4ce0)

**Comment by abnerlee** [comment]
please check https://support.typora.io/Width-of-Writing-Area/
