### ISSUE TITLE
Custom html title value

### ISSUE THREAD

**Issue by Vinc3r** [typora/typora-issues#607]
It could be a nice option to set custom html title export, rather than use file name.

For example, if I export _index.htm_l, I don't want _index.md_ as a title but _whatever-wonderful-custom-html-title_.

**Comment by Vinc3r** [comment]
_(sorry I don't see where I can set a label)_

**Comment by abnerlee** [comment]
We do not provide such option. You could use `YAML Front Matters` for this, for example:

```markdown
---
title: custom title
---

you writing.
```
