### ISSUE TITLE
Replacing "$&" in codeblock lang with "{0}"

### ISSUE THREAD

**Issue by 0xdf223** [typora/typora-issues#6074]
----

**Describe the bug**
I use Typora to generate markdown for a Jekyll website, which uses the Rouge formatter for codeblocks. This leads me to a lot of code blocks that use the `console` language, which takes arguments like `prompt`, `lang`, and `output`. That leads to codeblocks that have the first line:

````
```console?prompt=$&lang=bash&output=python
$cat test.py
#!/usr/bin/env python3

print("hello world")
```
````

When I save this in Typora, the "$&" gets replaced as {0}, which breaks everything downstream.

**To Reproduce**
1. In any document, create a codeblock with a language like the one above
![image](https://github.com/typora/typora-issues/assets/76954092/5c559f9d-483f-4394-92d5-9bbbd9592ab9)
2. Save it.
3. View the raw markdown outside of Typora:
````
$ cat test.md 
```console?prompt={0}output=php
test
```
````

**Expected behavior**
The text should still be `prompt=$&output=php`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - OS: Windows 11

**Typora Version**
e.g: 1.8.10

**Comment by abnerlee** [comment]
fixed in 1.9.4
