### ISSUE TITLE
Installing the latest version 1.9.4 will cause previously written files to be unrecognizable.

### ISSUE THREAD

**Issue by YangShaw-phy** [typora/typora-issues#6082]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
Installing the latest version 1.9.4 will cause previously written files to be unrecognizable.

**Expected behavior**
The files open correctly.

**Desktop (please complete the following information):**
 - Windows 11 64

**Typora Version**
1.9.4

**Additional context**

Windows Defender will block a threat originating from: Typora\resources\window.html, which will cause Typora to not function properly.

**Comment by abnerlee** [comment]
#6083
