### ISSUE TITLE
'windows.html' is detected as Trojan

### ISSUE THREAD

**Issue by MozziDog** [typora/typora-issues#6083]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
The file "resources\window.html" in Typora install directory is detected as trojan by windows defender.
my windows defender security intelligence version is 1.413.500.0 and last updated at 2024-06-25 PM 10:07

(translated from Korean)
```
Searched: Trojan:Script/Wacatac.B!ml
Status: isolated
isolated files are in restricted area which cannot affect machine and automatically removed.

Date: 2024-06-25 PM 2:43
Detail: This program is dangerous and it can execute attackers instructions.
```

due to isolation of window.html file, Typora doesn't work. cannot type any words and all the menu items are not working. 

**To Reproduce**
Just download and install lastest version (1.9.4) from typora.io

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://github.com/typora/typora-issues/assets/45249430/56d1062d-3467-4ed6-934d-6857b765da16)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit

**Typora Version**
1.9.4

**Additional context**
Typora updater form previous version(1.9.3) doesn't work (download gauge stops at 0%), so I tried manual update and this happens

**Comment by abnerlee** [comment]
I'm using security intelligence 1.413.505.0, which does not report such issue. So please try update your security definition (https://www.microsoft.com/en-us/wdsi/defenderupdates)

It is a false alert, you can follow https://learn.microsoft.com/zh-cn/defender-endpoint/restore-quarantined-files-microsoft-defender-antivirus to recover the file, and submit it to https://www.microsoft.com/en-us/wdsi/filesubmission to report the false positive.
