### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Uselesssssssssss** [typora/typora-issues#6084]
file: E:\typora\Typora\resources\window.html，so what is it？

**Comment by Uselesssssssssss** [comment]
i cant use typora，caz the problem（title）I get。

**Comment by abnerlee** [comment]
duplicated with #6083

please try update your security definition (https://www.microsoft.com/en-us/wdsi/defenderupdates)

It is a false alert, you can follow https://learn.microsoft.com/zh-cn/defender-endpoint/restore-quarantined-files-microsoft-defender-antivirus to recover the file, and submit it to https://www.microsoft.com/en-us/wdsi/filesubmission to report the false positive.
