### ISSUE TITLE
Typora opens to blank window after update

### ISSUE THREAD

**Issue by TechGuyAlabama** [typora/typora-issues#6087]
- [x] Searched existing issues to avoid creating duplicates.

Yes

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

Completely reinstalled twice and have no customization.

- [x] Searched http://support.typora.io/

Yes. I searched for "user-dict.json not found", "user-dict.json" and "blank screen"

----

**Describe the bug**

I've used Typora for a year+ but the last update caused my screen to go blank and have no options available to me.  I cannot open, type or use most of the menu options.

I've reinstalled it twice to make sure I didn't have any issues.

I used IOBit Uninstaller to remove this version then I installed 1.8.10. I was able to use 1.8.10 without issue. 

I upgrade 1.8.10 to 1.9.4 and it stops working.

Typora log file:  https://pastebin.com/JRsPR421

**Expected behavior**

When I open Typora, it opens to a blank screen with only the menu options at the top. Most of the options are clickable but achieve nothing.

**Screenshots / Screencasts**

https://i.postimg.cc/SN7qyWjm/image.png

**Sample Markdown File**

I cannot get any files to open.

**Desktop (please complete the following information):**

 - OS: Windows 2019 Server - Remote Desktop cloud server

I use this login for remote development.

**Typora Version**

1.9.4

**Additional context**

I've tried adding these options to the startup command:

--disable-gpu-sandbox
--no-sandbox

**Comment by abnerlee** [comment]
see #6083
