### ISSUE TITLE
Typora cannot find pandoc installed by anaconda

### ISSUE THREAD

**Issue by noirchen** [typora/typora-issues#609]
I installed pandoc using conda-forge on mac, and the path `/Applications/anaconda/bin` is added to `$PATH`. The version is 1.19.2.1 and I can invoke pandoc in the terminal with no problem. However, typora cannot find pandoc. If I copy the same pandoc to `/usr/local/bin` and then typora can find it. I tested several different places and it seems that if the path of pandoc does not start with `/usr/*`, typora will not find pandoc even after I add the path to `$PATH`.  For people who do not have administrative privilege and cannot install pandoc to `/usr/*`, this is very inconvenient.

**Comment by abnerlee** [comment]
@noirchen have you try restart Typora after installation? Typora will call pandoc command from $PATH

**Comment by noirchen** [comment]
Yes I restarted typora every time I made a change.

**Comment by abnerlee** [comment]
first exit typora.

if you open terminal, and input "pandoc", will it work?
if so, then input "typora", and try if the export works or not.

**Comment by noirchen** [comment]
On mac there is no direct way to start typora from the terminal. If I start typora using `open -a Typora`, still the export does not work.

**Comment by abnerlee** [comment]
I installed anaconda on my VM, but pandoc is installed to `/Users/{myuser}/anaconda/bin/pandoc`, and typora can export successfully. 

So I think maybe `/Applications/anaconda/bin` is not in your $path, but only added to the environment of your shell.

Could you check the pandoc install path by `which pandoc`?

**Comment by silloy** [comment]
@noirchen hello, have you solve the problem, I have the same question

**Comment by noirchen** [comment]
> @noirchen hello, have you solve the problem, I have the same question

I fixed this by adding the path to `/etc/paths`, and now you can open typora without using terminal and still export with pandoc.
