### ISSUE TITLE
[Feature]窗口内tab页支持

### ISSUE THREAD

**Issue by CarlaX** [typora/typora-issues#6096]
打开多个文档的时候不新建窗口，在当前窗口新建tab页，这样多文档编辑的时候方便切换，或者可以选择新建窗口还是新建tab页

**Comment by YalandHong** [comment]
mac版本已经支持标签页（tab）功能。

Windows和Linux暂时不支持：#638

**Comment by abnerlee** [comment]
duplicated with #638
