### ISSUE TITLE
anchor works when export to html buts not working at preview 

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#61]
first i write `<a name="swift-sp"><u>Singleton pattern</u></a>` meaning to setup an anchor.

then after several hundreds line i wrote `[Swift](#swift-sp)` meaning to jump the the anchor above,  but when i click and hold <kbd>command</kbd> it's not working.

Besides, `<a></a>` showing its source code when in preview, it would be better if it gets rendered as well.

regards,

**Comment by surpmillet** [comment]
+1

**Comment by gabrielfalcao** [comment]
👍

**Comment by abnerlee** [comment]
covered by https://github.com/typora/typora-issues/issues/1072
