### ISSUE TITLE
Processon shared content cannot Fully displayed

### ISSUE THREAD

**Issue by wqaetly** [typora/typora-issues#6100]
- [ √ ] Searched existing issues to avoid creating duplicates.

- [ √ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ √ ] Searched http://support.typora.io/

----

**Describe the bug**

**To Reproduce**
1. use processon to share a uml
2. paste to typora

**Expected behavior**
Fully displayed
![image](https://github.com/user-attachments/assets/5c198516-7778-4fb3-91a6-fdfb04e3b01c)

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.
![image](https://github.com/user-attachments/assets/40c71d9b-63df-40ec-ba7f-ddf4c898b59f)

**Sample Markdown File**
[bug.md](https://github.com/user-attachments/files/16247878/bug.md)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]

**Typora Version**
e.g: 1.9.5

**Additional context**

**Comment by abnerlee** [comment]
It might be a electron <WebView> issue, You can use 

```
<iframe id="embed_dom" name="embed_dom" frameborder="0" style="width:100%; height:600px;" src="https://www.processon.com/embed/625eb26d6376890727348155?cid=625eb26d6376890727348156"></iframe>
```

as a workaround.

**Comment by wqaetly** [comment]
> It might be a electron issue, You can use可能是一个电子问题，您可以使用
> 
> ```
> <iframe id="embed_dom" name="embed_dom" frameborder="0" style="width:100%; height:600px;" src="https://www.processon.com/embed/625eb26d6376890727348155?cid=625eb26d6376890727348156"></iframe>
> ```
> 
> as a workaround. 作为一种解决方法。

thanks！

**Comment by wqaetly** [comment]
resovled
