### ISSUE TITLE
Typora cannot show the correct "divide by" symbol

### ISSUE THREAD

**Issue by mathwo** [typora/typora-issues#6101]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [X] Searched http://support.typora.io/

----

**Describe the bug**

Typora shows $\div$ as a different symbol.

**To Reproduce**

Quite easy, just type \div in inline math or block math and check what this symbol is shown.

**Expected behavior**

According to MathJax and Katex, \div should show the math symbol "divide by"

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

![image](https://github.com/user-attachments/assets/561d1805-7de0-4807-ae03-ed827afcdb3b)

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

Windows 10 64bit

**Typora Version**
e.g: 0.10.11

1.9.5

**Additional context**

**Comment by abnerlee** [comment]
Please try disable "physics package" in Preferences Panel → Markdown → Math
