### ISSUE TITLE
Spellcheck doesn't work (Mac)

### ISSUE THREAD

**Issue by avenged110** [typora/typora-issues#612]
Using v0.9.9.9.3 on OS X 10.9.5, spellcheck doesn't appear to be working.

I have "Correct spelling automatically" enabled under Sys Prefs > Keyboard > Text. However, in Typora, nothing (no matter how blatantly misspelled) is ever underlined, and nothing is ever auto-corrected. Copy/pasting the contents into another app like Pages reveals all of the unmarked mistakes.

I have wiped preferences, etc. and reinstalled the app, but never been able to get this working despite claims that the app does support spellcheck. This problem has also persisted since at least 0.9.9.9.0.

**Comment by abnerlee** [comment]
@avenged110 Hi, is "Check Spelling while Typing" checked under `Edit` -> `Spelling and Grammar`?

**Comment by avenged110** [comment]
Well that's embarrassing. No it was not. I completely forgot about that menu since I guess I'm used to it being checked automatically. Thank you for the tip and sorry for the unnecessary report.

**Comment by StuartRob** [comment]
I had a similar problem and fixed it be unchecking and rechecking  "Check Spelling while Typing" and "Correct Spelling Automatically" checked under `Edit` -> `Spelling and Grammar`.
