### ISSUE TITLE
Preferences window issues (Mac) [0.9.9.9.4 update]

### ISSUE THREAD

**Issue by avenged110** [typora/typora-issues#613]
v0.9.9.9.4 on OS X 10.9.5
The "content misalignment" when switching tabs remains and while most of the margin issues have been fixed, the cut-off text remains in this tab.
![screen shot 2017-03-29 at 10 48 08 pm](https://cloud.githubusercontent.com/assets/19438529/24489681/bb337c6e-14d3-11e7-9c2e-fde1d5fd7b64.png)
- - - - - - -
v0.9.9.9.3 on OS X 10.9.5
Text in some of the tabs is cut off or awkwardly close to the edge of the window. The "tab" buttons at the top are also misaligned.
![screen shot 2017-03-24 at 12 47 27 pm](https://cloud.githubusercontent.com/assets/19438529/24311289/be4b9810-1090-11e7-8ecb-5c7587eb1629.png)
When switching between the "tabs," there is a brief misalignment of the tab's content over the toolbar. This can be seen in practice in the linked video.
https://youtu.be/7ekzqh0dpdA
![screen shot 2017-03-24 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/19438529/24311619/3392f86a-1092-11e7-9a66-0b3689cbe59d.png)
I would imagine the setting for custom font size would read better as "Custom" not "Customized." Also, there doesn't seem to be any consistency for capitalization among descriptions of the various preference options in each "tab."

**Comment by abnerlee** [comment]
fixed in 0.9.9.9.4.2
