### ISSUE TITLE
Issue exiting Fullscreen (Mac)

### ISSUE THREAD

**Issue by avenged110** [typora/typora-issues#614]
v0.9.9.9.3 on OS X 10.9.5
When exiting Fullscreen mode, the word count button – disabled in preferences – appears along with a button titled "Button," which appears to have to do with the "Collapsible Outline Left Panel" (which itself could use rewording). Neither of these buttons are present until one enters then exits fullscreen and the window must be closed and reopened to make them go away.
![screen shot 2017-03-24 at 1 12 26 pm](https://cloud.githubusercontent.com/assets/19438529/24312442/dc3daf02-1095-11e7-888e-dafcffaab367.png)
As a side note: the buttons themselves could use some work for consistency in terms of visual selection. Their behavior is shown in the linked video.
https://youtu.be/e6zTGrZsQhM

Also, in messing with this for documentation, the app crashed after exiting Fullscreen, leaving, and returning to focus. I've included the crash report below.
[Typora_2017-03-24-131913_MacBook.txt](https://github.com/typora/typora-issues/files/869105/Typora_2017-03-24-131913_MacBook.txt)

**Comment by abnerlee** [comment]
should be fixed in new release
