### ISSUE TITLE
[Feature/Bug] Cannot launch with external Electron 28+

### ISSUE THREAD

**Issue by intelfx** [typora/typora-issues#6154]
This is a continuation of #5463.

I'd like to run Typora using external Electron on Linux (to save memory, and because the bundled Electron has several minor glitches with Wayland). Judging by #5463, this was supported at least in the past.

However, starting with Electron 28, this no longer works:

```console
$ /usr/lib/electron28/electron /usr/lib/typora/resources/app.asar
App threw an error during load
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".node" for /usr/lib/typora/resources/app.asar/main.node
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:125:36)
    at defaultLoad (node:internal/modules/esm/load:89:20)
    at nextLoad (node:internal/modules/esm/loader:166:28)
    at ESMLoader.load (node:internal/modules/esm/loader:608:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:462:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:485:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:34)
```

I tried to work around this, but my knowledge of Electron/Node.js is not enough to make it work. I noticed that Typora bundles Electron 30, but apparently it's somehow patched to accept a native module as the `"main"` of the package, and a regular unpatched Electron build does not accept this.

Would it be possible/feasible to reorganize the code somehow to make it again possible to use Typora with (unpatched) Electron 28 or later? Or is this somehow fixable on my end?

---

(I'm currently evaluating Typora and this issue is the only thing that prevents me from purchasing a license.)

**Comment by sukanka** [comment]
I'm experiencing the same issue now. And this is also why the AUR package `typora-electron`  is still using electron27.

**Comment by abnerlee** [comment]
Typora have native node modules, such as "spellchecker", so you will need to use same electron major version with Typora.

The latest version of Typora uses electron 30, so you will need to use external electron 30, or stay in an fixed older version of Typora with bundles electron 28

**Comment by sukanka** [comment]
> Typora have native node modules, such as "spellchecker", so you will need to use same electron major version with Typora.

But only electron27 works. electron28-33 (include electron30, the one typora-1.9.3 bundled with) give the above errors.

**Comment by intelfx** [comment]
@abnerlee 

> The latest version of Typora uses electron 30, so you will need to use external electron 30, or stay in an fixed older version of Typora with bundles electron 28

This does not seem to match the behavior in reality. Right now it is _not_ possible to run the latest Typora with external Electron 30, or _any_ external Electron ≥ 28. Please reopen as this is not really resolved.
