### ISSUE TITLE
[Feature] Add menu option to open recent folder

### ISSUE THREAD

**Issue by xnervwang** [typora/typora-issues#6158]
Currently there is only menu option to open recent file. Though opening a file will open its direct parent folder on the left sidebar as well, when my workspace has multiple level folders, it will only open the inner-most folder.

Please consider a feature similar with VSCode, put both file and folder in the recent list, or add a new option to open recent folder.

**Comment by abnerlee** [comment]
It is already supported.

Ensure following setting is enabled:


<img width="832" alt="Screenshot 2024-10-16 at 21 43 07" src="https://github.com/user-attachments/assets/5161019b-8e7e-449c-a5c3-d6eea76a887c">
