### ISSUE TITLE
Request to Update Email Address Associated with Typora License

### ISSUE THREAD

**Issue by xueelf** [typora/typora-issues#6168]
I tried to contact the team half a year ago via email `hi@typora.io`, but have not received a response so far.

I accidentally came across this email again today, so I tried to contact you through GitHub. Hope this won't cause you trouble.

<img width="808" alt="屏幕截图 2024-10-31 190118" src="https://github.com/user-attachments/assets/40503ee9-48fb-4570-a170-efef419de637">
<img width="716" alt="屏幕截图 2024-10-31 190430" src="https://github.com/user-attachments/assets/c46f72b4-ad22-4d43-98e8-33732c84a7ec">

**Comment by abnerlee** [comment]
Sorry for the late reply. (We still didn't receive the email somehow...)

We have reset your license code, so you should be able to reactivate it again with new / correct email address.

**Comment by xueelf** [comment]
Thank you very much.
