### ISSUE TITLE
mermaid diagram gap

### ISSUE THREAD

**Issue by gzw9162** [typora/typora-issues#6197]
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
the vertical gap between two items is too wide in the mermaid diagram ,  is there any way to shorten the gaps ? 
![image](https://github.com/user-attachments/assets/b4751e96-2dc3-45cd-9522-31e0703535c8)

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32bit]

**Typora Version**
e.g: 0.10.11

**Additional context**

**Comment by abnerlee** [comment]
Currently there is no such option, it is calculated and rendered by Mermaid library.
