### ISSUE TITLE
How to change the display language?

### ISSUE THREAD

**Issue by Ferouden** [typora/typora-issues#620]
I haven't seen this options. And I'm not a english-speaking user.

(Maybe I made a mistake? Wish you to tell me.)

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/142

**Comment by sngreen** [comment]
You can't, it will always come back to system default language.

**Comment by sngreen** [comment]
Wow, it does not even start from bat, as
set LANG=en_US
START Typora.exe

Still starts in whatever - is this some kind of a hard-coded foreign stuff I am looking at?
