### ISSUE TITLE
Update the website and EULA to list who owns Typora

### ISSUE THREAD

**Issue by Pomax** [typora/typora-issues#6202]
If this is a business, there should be a business registration that should be public (e.g. in an "about" or "contact" section), and if Typora is owned by another company, that information should also be publicly listed. This will also orequire updating the EULA: right now the EULA is written as being between users and "the typora dvelopers" but that's not a specific person/specific people, nor a business entity, which means the EULA is currently invalid.

**Comment by abnerlee** [comment]
EULA is now updated.
