### ISSUE TITLE
Can't remove text from tables

### ISSUE THREAD

**Issue by KraXarN** [typora/typora-issues#623]
Data can be added to a table just fine, but when trying to remove text from it, neither backspace nor delete does anything. Only workaround I found was toggling Insert and then removing it that way.

Using Windows 7 x64

EDIT: Restarting the program fixed it, but might still be an issue to look into

**Comment by abnerlee** [comment]
I cannot reproduce this, could you show the steps to reproduce this bug?

**Comment by KraXarN** [comment]
I unfortunately can't reproduce it, since I don't know what was causing it.

**Comment by abnerlee** [comment]
@KraXarN You could send the typora.log under C:\Users\{your-user-name}\AppData\Roaming\Typora to hi@typora.io if that happens again, and try recall your operations to cause this bug.

Thanks for the report
