### ISSUE TITLE
When Insert an underline syntax in a inline math block ,two underline syntax appears (windows)

### ISSUE THREAD

**Issue by cairoHy** [typora/typora-issues#625]
Version:Typora 0.9.25-windows.

When Insert an underline syntax in a inline math block ,two underline syntax appears.

![1](https://cloud.githubusercontent.com/assets/3580577/24437096/b1ccd5e2-1471-11e7-81d4-1dd3f3f90707.JPG)

when i enter something like a_ in inline math block, the result is as following picture.
![2](https://cloud.githubusercontent.com/assets/3580577/24437102/c3898244-1471-11e7-9965-828d92bd0eda.JPG)

**Comment by abnerlee** [comment]
Should be fixed in the newest version
