### ISSUE TITLE
App freezes on 2nd doc

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#628]
When editing a document, and either starting a new document or launching a second doc via Finder, the app freezes and becomes non-responsive. I don't see any other open issues on this (although perhaps it's the same root cause as the "lose focus" open issue).

When press Cmd-N, File menu stays highlighted and cursor goes to beachball. Attaching the full crash report after force-quitting the unresponsive app.

Version 0.9.9.9.3 on macOS Sierra 10.12.4

[typora crash.txt](https://github.com/typora/typora-issues/files/879885/typora.crash.txt)

**Comment by abnerlee** [comment]
should be fixed in 0.9.9.9.4

**Comment by AlexPasternak** [comment]
Confirmed fixed, thanks!
