### ISSUE TITLE
Export as HTML: Add keyboard (or hotkey) support for sub menu items

### ISSUE THREAD

**Issue by Maggew** [typora/typora-issues#629]
I open the **conf.user.json** and added this to the file, but didn't have much luck.

```
  "keyBinding": {
    // for example: 
    // "Always On Top": "Ctrl+Shift+P"
    //  "Export": "Ctrl+E"
    "Export HTML": "Ctrl+E"
  },
```

Maybe I'm not using proper code stuff?

![image](https://cloud.githubusercontent.com/assets/1291364/24527956/71290310-1572-11e7-983c-eb4af2960c48.png)

**Comment by Maggew** [comment]
NVM! Got it, just had to ```"HTML": "Ctrl+E"``` to the file.

**Comment by Maggew** [comment]
I'm back! I really did find a bug!! OOO oshnaps.

Here is the conf.user.json: 
![image](https://cloud.githubusercontent.com/assets/1291364/24549181/1dc0adbc-15e6-11e7-8bd0-0c43fca4cca3.png)

In the menu, it says no hotkey is registered: 
![image](https://cloud.githubusercontent.com/assets/1291364/24549197/36c0ab32-15e6-11e7-9306-e7051b18a545.png)

The export hotkey doesn't work though: 
![image](https://cloud.githubusercontent.com/assets/1291364/24549207/4730358c-15e6-11e7-9933-c511edec6c84.png)

Suggestions? Advise? I restarted Typora a few times.

**Comment by abnerlee** [comment]
bug fixed
