### ISSUE TITLE
Copying Task List as Markdown doesn't preserve checked state

### ISSUE THREAD

**Issue by dwbruhn** [typora/typora-issues#630]
OS version: OS X Sierra 10.12.3
Typora version: 0.9.9.9.4

To reproduce:

- create a Task List in Typora with two items
- check one item, but not the other
- select all, then choose Edit - Copy As Markdown
- paste into a text editor. Notice that both are __unchecked__.

e.g.:

![image](https://cloud.githubusercontent.com/assets/8230981/24530237/8b20139c-1565-11e7-8811-a528a2753fb0.png)

pastes as:

```md
- [ ] this is not checked
- [ ] this is checked
```

**Comment by abnerlee** [comment]
This should already be fixed in newest version

**Comment by dwbruhn** [comment]
👍  thanks!
