### ISSUE TITLE
Using a Gif image causes lag and frame rate drop

### ISSUE THREAD

**Issue by shadowfacts** [typora/typora-issues#631]
After adding a .gif image to my document, the frame rate drops significantly (feels like ~5 FPS). This also affects the rest of the editor with keystrokes feeling delayed by up to about 0.5 seconds and the menus being noticeably laggy as well.

After removing the image, the editor returns to its normal behavior.

Typora 0.9.9.9.3
macOS: 10.12.1

**Comment by abnerlee** [comment]
will try fix following https://github.com/typora/typora-issues/issues/932
