### ISSUE TITLE
Beta Version 0.9.9.9.3 (0.9.9.9.3) update error

### ISSUE THREAD

**Issue by stuzog** [typora/typora-issues#634]
`An error occurred while downloading the update. Please try again later.`  

typora Version 0.9.9.9.3 (0.9.9.9.3)  
iMac 7,1 OS X 10.11.6

Same with 0.9.9.9.4 -- betas must be downloaded not updated, I guess?

**Comment by abnerlee** [comment]
fixed now

**Comment by stuzog** [comment]
Better -- it downloads and moves to Install and Relaunch - but now I get 
the error:

`An error occurred while extracting the archive. Please try again later.`

Stuart

AbnerLee wrote:

**Comment by abnerlee** [comment]
@stuzog try re-download from typora.io 

We will check what's the error behind
