### ISSUE TITLE
Feature -- Place Anchor for math block or other shortcut function

### ISSUE THREAD

**Issue by Piping** [typora/typora-issues#635]
Hi, I used Typora intensively in my daily work from taking notes to write summary of papers. 

I find out when I need to input the math block or $$ is kind of annoying. 

Currently I set a shortcut to use inline math directly without typing $$, but then I need to manually select the area where I need to include in inline math block.

Can we add some sort of functionality to place a anchor or mark so that when I finished typing and pressed the shortcut, from the beginning of anchor up to where I typed, apply the shortcut function to those texts??

I think this function will be very useful  not only to use inline math but also other type of blocks without typing too much of annotation keywords.

I appreciate your awesome work.

**Comment by abnerlee** [comment]
To set custom key binding, please refer http://support.typora.io/Custom-Key-Binding/

> Can we add some sort of functionality to place a anchor or mark so that when I finished typing and pressed the shortcut, from the beginning of anchor up to where I typed, apply the shortcut function to those texts??

I think you could type "$" at the beginning, then press "$" again when you finish typing.
