### ISSUE TITLE
Paste to Evernote removes line breaks in code fences under Windows

### ISSUE THREAD

**Issue by Cito** [typora/typora-issues#639]
This happens probably only on Windows:

When I copy & paste content that contains a code fence from Typora to Evernote, then all line breaks in the code fence are missing in Evernote. Otherwise, the formatting is carried over nicely to Evernote.

(Windows 10, Typora 0.9.25, Evernote 6.5.4.4720)

**Comment by abnerlee** [comment]
This should be fixed in newest version
