### ISSUE TITLE
Images in Windows do not work

### ISSUE THREAD

**Issue by reflog** [typora/typora-issues#64]
Hi guys.
I've am evaluating typora and it's awesome. Except for images :smile: 

I've tried using drag and drop and using relative paths - neither worked (shows 'failed to load image').

Just in case, attaching the devtool log:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
app/window/frame.js:18 html2canvas.js is loaded
app/window/frame.js:6 getContent
app/window/frame.js:8 putHTML: 19.832ms
app/window/frame.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
file:///C:/Program%20Files%20(x86)/Typora/resources/app/app/window/frame.js Failed to load resourceY.cors.a.crossDomain.send @ app/window/frame.js:4
window.html:1 Uncaught SyntaxError: Unexpected end of input
app/window/frame.js:12 codemirror mode is loaded
```

**Comment by abnerlee** [comment]
Hi, thanks for the bug report

Could you post the full path of your image file? And the markdown syntax you were using? That will help us to reproduce this bug.

**Comment by reflog** [comment]
```
 ![d:\Dropbox\IMG_20130918_181732.jpg](.\Dropbox\IMG_20130918_181732.jpg)
```

MD file is located in root d:\ folder. I've also tried:
```
 ![d:\Dropbox\IMG_20130918_181732.jpg](Dropbox\IMG_20130918_181732.jpg)
```


Drag and drop doesn't work at all - dropping the image file inside Typora doesn't create any text, nor any errors in devtool.

**Comment by be5invis** [comment]
Wait... backslash?

**Comment by reflog** [comment]
tried the other variants. like:
```
![aa](./Dropbox/IMG_20130918_181738.jpg)
```

same result

**Comment by abnerlee** [comment]
Should be fixed, please check for updates

**Comment by reflog** [comment]
all fixed :+1:
