### ISSUE TITLE
Some buttons in preferences can't work well

### ISSUE THREAD

**Issue by WooHooDai** [typora/typora-issues#642]
- System Environment: Linux Oycir 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux

- Errors:
    - When I click "Open Theme Folder", I get errors in the console:
        > Failed to load resource
send @ app/window/frame.js:3
file:///home/woohoodai/.config/Typora/themes/base.user.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/woohoodai/.config/Typora/themes/night.user.css Failed to load resource: net::ERR_FILE_NOT_FOUND
    - When I click "Open Advanced Settings", there's nothing happened

How can I get buttons work?

**Comment by abnerlee** [comment]
This should be fixed in newest version
