### ISSUE TITLE
Task list checkboxes don't appear after an un-indented list level

### ISSUE THREAD

**Issue by ludocode** [typora/typora-issues#643]
- Version: 0.9.9.9.4.2
- OS: macOS Sierra

With the following markdown:

```markdown
- Bullet
    - [ ] Nested Checkbox
- [ ] Checkbox??
```

Typora renders this:

![screen shot 2017-04-13 at 1 08 54 pm](https://cloud.githubusercontent.com/assets/278471/25015753/31d3d468-204b-11e7-9472-f5ab271e5072.png)

A single blank line has no effect, but two blank lines:

```markdown
- Bullet
    - [ ] Nested Checkbox


- [ ] Checkbox??
```

fixes it:

![screen shot 2017-04-13 at 1 09 04 pm](https://cloud.githubusercontent.com/assets/278471/25015758/35c7ee74-204b-11e7-84bb-be15044b8939.png)

**Comment by abnerlee** [comment]
Fixed in new release
