### ISSUE TITLE
URLs with URL-encoded characters are double-encoded in HTML export

### ISSUE THREAD

**Issue by eloquence** [typora/typora-issues#644]
Version: 0.9.25 Linux via apt repository

Steps to reproduce:

1) Copy the following text into a new Typora document.

````
[This is a link](https://projects.propublica.org/nonprofits/download-filing?path=2016_10_EO%2F52-1921136_990_201512.pdf).
````

2) Export the document as HTML.

Expected result: Link will not be altered.

Actual result: The URL encoding `%2F` is double-encoded as `%252F`, rendering the link invalid. The same happens when copy/pasting the document in rich-text form into other editors. It does not happen when copying as markdown.

**Comment by abnerlee** [comment]
fixed in new release
