### ISSUE TITLE
Typora does not start, launches waterfall of errors

### ISSUE THREAD

**Issue by Epse** [typora/typora-issues#645]
Running on Windows 10, downloaded just now from the website. After clicking past all the error boxes I get a blank window with only the bottom status bar. Noting on the bar does anything. I will try to list all the errors I get. (slightly truncated, if a full message is needed please ask)

* `Cannot read property keyBinding of Undefined at processMenu at Object.bindMainMenu`
* `Cannot read property getItem of null at Walker.<anonymous>`
* Failed to load file: `TypeError: Cannot read property getItem of null at Object.x`

**Comment by Darleey** [comment]
Got the same crash. After that I uninstall the 0.9.26 and try to install an older version <0.9.23>, then I try to get updates with the inserted update function <Preferences - System - Update>, it works.
While after this I find that the description of version in the software list  is still 0.9.23 <Typora is already updated to 0.9.26>.

**Comment by abnerlee** [comment]
confirmed, I will update a new release **soon**

**Comment by abnerlee** [comment]
The new release should fix this
