### ISSUE TITLE
How can I close "outline panel"?

### ISSUE THREAD

**Issue by piaowang** [typora/typora-issues#646]
the version is newest

**Comment by Darleey** [comment]
There is a circle on the lower-left corner , click it.

**Comment by piaowang** [comment]
No ,I can't find it .I use win10,There is nothing. the outline panel is in "view", I click it, but it can't feedback. The last version is ok .

**Comment by Darleey** [comment]
Sorry, I missed your idea.
You may take the following suggestions:
1.open the "status bar" < View - Show Status bar >
2.There is an arrow『like this <』 on the lower-left corner of the screen, click it.

**Comment by piaowang** [comment]
thanks  you  help,I find it. You are so great.

**Comment by abnerlee** [comment]
It is a bug, I posted a new release which would fix this
