### ISSUE TITLE
Cannot support self-defined fonts

### ISSUE THREAD

**Issue by Darleey** [typora/typora-issues#647]
OS. Windows 10. 15063.138
Typora. 0.9.26

After updated to the latest version <0.9.26>, Typora failed to support self-defined fonts.

**Comment by abnerlee** [comment]
@Darleey how do you define fonts?

**Comment by Darleey** [comment]
I defined them in the file **C:\Users\***\AppData\Roaming\Typora\conf\conf.ueser.json**
I find the root in the following way< Preferences - System - Open Advanced Settings >.

```
/** For advanced users. */
{
  "width" : null, // Integer - Window's width in pixels. Default is null (last window width)
  "height" : null, // Integer - Window's height in pixels. Default is null (last window height)
  "defaultFontFamily": {
    "standard": "Microsoft YaHei", //String - Defaults to "Times New Roman".
    "serif": "Microsoft YaHei", // String - Defaults to "Times New Roman".
    "sansSerif": "Microsoft Sans Serif", // String - Defaults to "Arial".
    "monospace": null // String - Defaults to "Courier New".
  },
```

It worked in the past several versions.

**Comment by Darleey** [comment]
@abnerlee I defined them in the file `C:\Users\Username\AppData\Roaming\Typora\conf\conf.ueser.json`
I find the root in the way < Preferences - System - Open Advanced Settings >.

Here is the settings.
/** For advanced users. */
{
  "width" : null, // Integer - Window's width in pixels. Default is null (last window width)
  "height" : null, // Integer - Window's height in pixels. Default is null (last window height)
  "defaultFontFamily": {
    "standard": "Microsoft YaHei", //String - Defaults to "Times New Roman".
    "serif": "Microsoft YaHei", // String - Defaults to "Times New Roman".
    "sansSerif": "Microsoft Sans Serif", // String - Defaults to "Arial".
    "monospace": null // String - Defaults to "Courier New".
  },
It worked in the past several versions.

**Comment by abnerlee** [comment]
@Darleey The font definition will be override by css file.

For example, if the css is 

```
body {
 font-family: 'Oxygen', sans-serif; 
}
```

Then, first Oxygen font will be used, if not found, fallback to sans-serif, which you defined as "Microsoft Sans Serif", so would you open "View->Toggle DevTool (F12)" to check if there are css rules of "font-family".

You could also follow http://support.typora.io/Custom-Font/ for Custom Font

**Comment by Darleey** [comment]
@abnerlee Thanks ,  I ignored the way. Creating my own theme is so joyful w.v.w .
