### ISSUE TITLE
Variety of critical errors on load.

### ISSUE THREAD

**Issue by justinwzig** [typora/typora-issues#648]
I've been using Typora on my desktop for some time to author posts but I ran into some issues when I decided to install it on my laptop. The install completes but when starting typora it pops up several errors:
![e1](https://cloud.githubusercontent.com/assets/4504400/25096437/d4e7f540-2365-11e7-9199-c82c941a3cb2.PNG)
![e2](https://cloud.githubusercontent.com/assets/4504400/25096438/d51eefa0-2365-11e7-9a16-57b2fa5aaac1.PNG)
![e3](https://cloud.githubusercontent.com/assets/4504400/25096439/d5422902-2365-11e7-9b95-5657d6c94a75.PNG)
...and then fails to load the editor.

I've tried reinstalling to no avail.

OS: Windows 10 Home
Typora Version: Latest

**Comment by old9** [comment]
Same here, Windows 10 Pro,  latest typora

**Comment by abnerlee** [comment]
please re-download or check updates again, I posted a new version (0.9.27) for fix

**Comment by justinwzig** [comment]
Fixed, thank you.
