### ISSUE TITLE
[Enhancement] Search contents of all files inside current folder

### ISSUE THREAD

**Issue by hrvoj3e** [typora/typora-issues#651]
It would be nice if I could search contents of all files inside current folder.

Why?
I am writing about something that I know I wrote before so I need to quickly find that file.

I realize this is a request outside of markdown editor scope but most advanced text editors have this option.

**Comment by rk-development** [comment]
Yes!
This is what i'm missing in this app.
I have lots of small notes with trick&tips and i really wish to search through them within the app.

**Comment by yatahonga** [comment]
Yes!

Enhancing the **File Tree** with a search function across all files of the current folder AND the ability to sort the list of files (currently alphabetical only, but I'd like to be able to order them by date of last update and/or creation instead) are the very last things preventing me from switching from nvALT to Typora for good.

Such features would make Typora the absolute killer note taking app! Please...

**Comment by sancho-one** [comment]
I miss these two features, too. Very much. They are only thing which keeps me away from using Typora. In my opinion, once deployed these feature'll convert Typora in market leader in cross platform note taking apps.

**Comment by LeBaux** [comment]
I ascended from Microsoft OneNote. One of the few things OneNote does better is search. I understand Typora is mainly for distraction free writing, but it really is viable alternative to the likes of Evernote and OneNote, Simplenote or similar projects like boostnote or laverna.cc. So far, I only miss search.

![record_171016_171908](https://user-images.githubusercontent.com/5657511/31620102-a755a756-b296-11e7-80d9-7f048d2e022c.gif)

Speaking of boostnote, they included [fast search functionality similar to osx spotlight](https://medium.com/boostnote/how-to-boost-your-work-efficiency-by-using-shortcut-keys-8c47da92ea1d) and it works great. Since you use the same technologies to build typora, you might find some inspiration there.

**Comment by vassudanagunta** [comment]
Let's define "current folder". Is it the folder of the currently viewed file, or is it the root folder if the Tree View? I'd prefer the latter, and the search should be directory recursive.

**Comment by trapias** [comment]
I’d love to have the possibility to search for a string in multiple files, and maybe on metadata  - tags, or post header tags. Like NValt does on Mac, maybe somewhat improved too? 😊

**Comment by HADB** [comment]
+1

**Comment by xmarkclx** [comment]
+1

**Comment by Majordon** [comment]
Search inside multiple document/folders would make it useful when having many documents!

**Comment by underscore-ex** [comment]
I had to switch back to quiver because typora doesn't have this search feature :(

**Comment by Nikscorp** [comment]
+1. Tags + "Find in Files" feature would great.

**Comment by asins** [comment]
+1

**Comment by nnsense** [comment]
+1

**Comment by akupac** [comment]
+1

With this feature, plus search files by name with a shortcut (Ctrl + T in Atom).

That would do the job for me. I'd quit from Atom IDE for dealing with ".md" library with these features.

**Comment by EvanEdwards** [comment]
Moving from QOwnNotes, this is the one feature that I absolutely miss.  The markdown and pure writing aspect is far better.

**Comment by Hologos** [comment]
+1 from me

**Comment by nanoant** [comment]
+1 from me as well

This is only missing feature that prevents me from using Typora solely for all my notes.

**Comment by petitlen** [comment]
+ 1 from me

**Comment by RokuKent** [comment]
Yes, this is a very useful feature to find an md file for editing that resides somewhere inside a folder. +1 or more.

**Comment by XunshanMan** [comment]
+1
I like that so much.

**Comment by zorglups** [comment]
Yes please. I wan't to quit OneNote and the likes but need a global search to do that.

**Comment by j-manu** [comment]
Instead of having to implement it from the ground up, maybe https://github.com/BurntSushi/ripgrep can be integrated? Visual Studio Code uses it.

**Comment by asins** [comment]
I am also using Ripprep to meet my needs, but such a search leaves the Typoa software interface, and searching for open files is not ideal.

Still hope to provide project search capabilities at the Typora software level.

**Comment by zk4** [comment]
a workaround with alfred app.

and change the source folder  you want in workflow source file , in line 3  
```
open [your fileflolder]
```

```

osascript -e 'tell application "System Events" to keystroke "a" using {command down}' 
osascript -e 'tell application "System Events" to keystroke "searchging.." ' 
open  ~/
osascript -e 'tell application "System Events" to keystroke "f" using {command down}' 


```

**Comment by blurayne** [comment]
Still missing the feature. I do a lot of development notes so this is crucial. #pushtotop

Or OpenSource the app so I can add the feature myself ;)

**Comment by riotejas** [comment]
+1

**Comment by m-thomson** [comment]
I'm sorry if I missed it, but can we get a note from the developer @abnerlee on this request? I'm just curious if this is on the roadmap 😃 ?

I'm in love with Typora but search is definitely a make or break feature. I don't want to invest more time in it if search is not planned. Thanks a bunch.

**Comment by m-thomson** [comment]
@abnerlee Amazing! Go ahead and [take my money](https://imgur.com/gallery/9NHqCfC)! Seriously, this App has been a game changer so far. Thank you.

**Comment by abnerlee** [comment]
supported in new release

**Comment by yaute74** [comment]
Thank you, it was the modification I was waiting for to be able to use this beautiful application :+1:

**Comment by hrvoj3e** [comment]
Thank you for implementing this.
I searched for details about implementation but could not find any - yet.

Here are my findings:
 - new search is triggered with `Ctrl+Shift+F`
 - it is available only in sidebar (there is no `Ctrl+P` like interface)
 - can be turned off by `Ctrl+Shift+L` (`Ctrl+Shift+F` twice won't work)
 - regex is not supported

Search scope:
 - current folder (relative to currently opened file) 
 - all files below active folder (can be checked by File tree `Ctrl+Shift+3`)

Forcing search scope:
 - only via terminal: `typora .` or `typora /some/path/`
 - exception: I have a big folder with `.md` files with 3 nesting levels.
   - If I open a file on level 3 (`typora /home/user/dir1/level2/level3/somefile.md`) it loads all files from level 1 (and below) in File tree. 
   - `typora /home/user/dir1/level2/level3/` opens only level3 - as expected

**Comment by tomer-ben-david** [comment]
is it implemented? need fuzzy search in typora..
