### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by chenwq3** [typora/typora-issues#652]
![01](https://cloud.githubusercontent.com/assets/25943138/25212273/f1694518-25bb-11e7-9245-d02c27471990.png)

the file that make this error is :

![02](https://cloud.githubusercontent.com/assets/25943138/25212357/6171a62a-25bc-11e7-88a1-79b15613b213.png)

Host: Windows 10 amd64(64bit OS), en, Typora: amd64, Version:

![03](https://cloud.githubusercontent.com/assets/25943138/25212377/80ad7550-25bc-11e7-9516-80526dd1f7e5.png)

**Comment by abnerlee** [comment]
@chenwq3 Thanks for the bug report

When does this happen or how to reproduce this? Whenever you open the md file, the error would occur?

**Comment by chenwq3** [comment]
I tried to create a file and I write the same content, then save the file to disk. Open it by using typora, and I can't reproduce this issue.

I'd better not upload this file and let you try open it. Because no body should open a file that is from a stranger.

Is there a switch or param to let me enable a debug  and let me try to find the problem?

**Comment by chenwq3** [comment]
I use `vim -b` to open it and type `%!xxd`，here is the file content that results this issue.

![04](https://cloud.githubusercontent.com/assets/25943138/25221922/62aa137e-25e9-11e7-8b9f-419de83c61dc.png)

```
00000000: 0d0a 6060 6062 6173 680d 0a24 2072 6f73  ..```bash..$ ros
00000010: 6c61 756e 6368 2072 706c 6964 6172 5f72  launch rplidar_r
00000020: 6f73 2076 6965 775f 7270 6c69 6461 722e  os view_rplidar.
00000030: 6c61 756e 6368 0d0a 6060 600d 0a         launch..```..
```

**Comment by abnerlee** [comment]
may relates to https://github.com/electron/electron/issues/4279

Considering we have already updated our Electron version and I didn't met this error dialog for now, I will close this. Please reopen this if this happens again
