### ISSUE TITLE
Code fences shortcut (Alt+Ctrl+F) on Windows inserts character "[" before code fence 

### ISSUE THREAD

**Issue by hrvoj3e** [typora/typora-issues#653]
Pressing Alt+Ctrl+F I get an extra character "[" before code fences.

![2017-04-20 120831 screenshot](https://cloud.githubusercontent.com/assets/4988133/25225709/b27ddbbe-25c2-11e7-92cb-030a91ce0b20.png)

> Windows 10 x64
> Typora 0.9.27

**Comment by abnerlee** [comment]
@hrvoj3e Are you using US English Keyboard and US English input method? If you open word or notepad.exe and press Alt+Ctrl+F, will the "[" be inserted?

**Comment by hrvoj3e** [comment]
No. I am using Croatian input method.
Notepad.exe Alt+Ctrl+F inserts "[".

**Comment by abnerlee** [comment]
I see, in that cause we should assign the shortcut key for Code Fences to something else

**Comment by hrvoj3e** [comment]
Or add another shortcut (alias) so users with similar input methods could use it for Code Fences.
What about `Ctrl + Shift + F `?

**Comment by abnerlee** [comment]
@hrvoj3e Actually you could change the shortcut key before we release a fix -> http://support.typora.io/Custom-Key-Binding/

**Comment by abnerlee** [comment]
WE remove the default key binding of Code Fences, please follow the doc above to assign to something else if you want the shortcut key
