### ISSUE TITLE
Please add shortcuts in the modal dialogs

### ISSUE THREAD

**Issue by jeffswt** [typora/typora-issues#656]
I believe that using `Y` and `N` in the *Save and Close* dialog is a great improvement for keyboard users.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/759

**Comment by metal450** [comment]
Seems this is still an issue 3yrs on.  Would be great to be able to save or not with Y/N.  Using the mouse is super cumbersome.

**Comment by fabian-gubler** [comment]
+1 Would be great to have this functionality.
