### ISSUE TITLE
Add tags management like 'Bear' app

### ISSUE THREAD

**Issue by jzoe** [typora/typora-issues#658]
Hi~guys, i think typora can add file management base on tag like [Bear](http://www.bear-writer.com/) , it's really convenient and powerful !

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/478 and https://github.com/typora/typora-issues/issues/57

**Comment by mocheng** [comment]
The issue #57  is not actually like Bear. It is about folder structure managmeent, while Bear is tagging management.

**Comment by abnerlee** [comment]
relates to #1393
