### ISSUE TITLE
[feature] Bibliography citation key autocompletion

### ISSUE THREAD

**Issue by azag0** [typora/typora-issues#66]
With the use of Pandoc for markdown to LaTeX conversion, one custom Pandoc [filter](https://groups.google.com/forum/#!msg/pandoc-discuss/RUC-tuu_qf0/h-H3RRVt1coJ) for dealing with tables in two-colum environment, and two primitive text filters of mine ([one](https://gist.github.com/150d1160cf86f1bb6d7e) for restoring starred `table*` and `figure*`, the [other](https://gist.github.com/6e8fc9e510398cc82402) for having figures formatted in the same way that works for tables in Pandoc), I successfully ported a mature journal paper that I'm writing into markdown, which can be edited in Typora (with the latest version which preserves newlines at the ends of sentences for good Git versioning) and converted to PDF via pandoc+pdflatex with negligible difference to the original tex to pdflatex conversion.

So, kudos! This is perfect.

The only thing that I'm missing from editing tex files in Vim to have a really comfortable environment is autocompletion of citation keys from a bibtex file. I realize that adding an autocompleter would be probably a major effort. But I just wanted to mention that with this addition, Typora with Pandoc would be a fully developed environment for writing and editing complex scientific articles.

Even without that, however, I still feel more comfortable editing Markdown in Typora than tex in Vim (I love Vim). The live preview of tex equations is simple a killer.

**Comment by zhangmozhe** [comment]
Hi sir, how do you manage to cite the reference in Typora? Thanks!

**Comment by orschiro** [comment]
> Typora with Pandoc would be a fully developed environment for writing and editing complex scientific articles.

I fully agree with you on this one and it would open up possibilities for an entirely new user group!

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/105

**Comment by jackweinbender** [comment]
I'd like to add my name to this request. I, too, use Markdown > TeX/PDF/docx via pandoc for academic writing. Typora is easily my favorite markdown editor, and pandoc-citeproc style reference autocomplete would be amazing. 

That said, even if a full-blown autocomplete couldn't be implemented, it would be great to have appropriate syntax highlighting for pandoc refs like; `[@cross1973, 172]`.

**Comment by GandalfSaxe** [comment]
This would be really great.

Not only autocompletion, but also in-app support so the bibliography would be shown at the bottom of the document.

**Comment by GandalfSaxe** [comment]
This is about autocompletion of citations from a bibtex file, which is typical academic work, yes.

But it's slightly different issues:
1. This is about autocompletion of referees from a bibtex file.
2. #294 is about syntax highlighting of these references.

If you want to merge them, this information should be included somehow.

**Comment by abnerlee** [comment]
Included the info all in https://github.com/typora/typora-issues/issues/912

**Comment by cameronwlewis** [comment]
+1 for Pandoc support

**Comment by gandalfsaxe** [comment]
Workaround solution on Mac using Alfred posted here: https://www.alfredforum.com/topic/11572-autocomplete-words-from-a-textfile/?tab=comments#comment-60512

**Comment by TMorville** [comment]
+1 for built-in Pandoc and/or BibTeX support

**Comment by alexandergogl** [comment]
If you use Zotero and have a Mac you can use the approach described by [Raphael Kabo](http://raphaelkabo.com/blog/posts/markdown-to-word/) what gives you a Zotero reference search box. It works perfect for me.

**Comment by MehdiCHEBBAH** [comment]
Any updates in 2020

**Comment by Lazenca-Li-Qiuqi** [comment]
This issue was one of the reasons I built a Typora plugin for local BibTeX citation workflows.

It now supports:
- citation key completion from local `.bib` files
- Pandoc-style citation insertion
- citation rendering with a local `.csl`
- bibliography insertion/update inside Typora

So if anyone here is still looking for BibTeX citation key autocomplete in Typora, plus a lightweight local CSL-based citation workflow, here it is:

https://github.com/Lazenca-Li-Qiuqi/typora-plugin-bibtex-citation

It’s aimed at users who already work with local `.bib` + Pandoc-style citations and want to keep more of that workflow inside Typora.
