### ISSUE TITLE
Inserting a newline before bold text breaks boldness

### ISSUE THREAD

**Issue by sikinmettugi** [typora/typora-issues#661]
Please mention me if more details needed. Thank you in advance.

---

## Overall

- If you type a list item with bold text(\*\*BOLDTEXT\*\*) then insert a newline right before that, \*\*BOLDTEXT\*\* becomes broken, by missing one star: \*BOLDTEXT\*\*.

## How Can I Reproduce This Bug

1. Type like this, as a list item - the indent level can be any:
  > \- abcd \*\*efgh\*\*

  This is rendered as:
  > - abcd **efgh**

2.  Try to make this by adding a newline:
  > - abcd 
  > - **efgh**
  This is `- abcd(whitespace)(newline)- **efgh**`

3. But, Typora generates this:
  > - abcd 
  > - \*efgh\*\*

4. Without a list item dot, this doesn't happen, i.e.
  > abcd **efgh**

  becomes

  > abcd
  > **efgh**

5. The emphasis string i.e. \*EMPHASIS\* **also becomes broken**, by doing the same procedure. Looks like **using underscore instead of star(asterisk)** works fine.

## Environment

Typora 0.9.29 beta, on Windows 7 x64

**Comment by abnerlee** [comment]
should be fixed in newest version
