### ISSUE TITLE
Typing $\bmod Q$ instantaneously removes itself.

### ISSUE THREAD

**Issue by jeffswt** [typora/typora-issues#662]
I wasn't able to replicate this issue after restarting Typora.

Only typing $\bmod Q$ yields this error, and $\bmod q$ or $\bmod qQ$ does not.

Same happens after you typed in $\bmod Q$ in source code mode and switch back to normal mode - it simple disappears.

I don't know why, just in case you are notified of this issue.

**Comment by abnerlee** [comment]
What's the typora & OS version?

**Comment by jeffswt** [comment]
I think it's a rare condition that is not easy to reproduce.

I've been trying to reproduce this for a long time but so far no progress have been made.

In case you are notified, Typora version is 0.9.25 and OS is Windows.

---

Other rare conditions includes: clicking the 'close' button wouldn't close the window - nor would other buttons, and typing won't work, apart from a single paragraph - which I cannot reproduce either.

Maybe they have something to do with Electron, I don't know.

**Comment by abnerlee** [comment]
@jeffswt

**Comment by abnerlee** [comment]
>  clicking the 'close' button wouldn't close the window 

Please update to lastest version , which may fix this.
