### ISSUE TITLE
Spell Check with Context Menu Key

### ISSUE THREAD

**Issue by duckbrain** [typora/typora-issues#663]
When using the context menu key to open the context menu for spell check, selecting a correct spelling causes the word to be inserted twice. Doing an undo immediately afterward removes the second copy of the word.

Using Typora for Windows/Linux 0.9.29 on Arch Linux using the [AUR package](https://aur.archlinux.org/packages/typora/?comments=all).

**Comment by abnerlee** [comment]
Can you still reproduce this bug?

And on context menu is the misspelled word be selected?

**Comment by duckbrain** [comment]
Yes. There has not been a release in the Ubuntu repository since I posted.

Yes it appears to be selected.

Before pressing context menu button:

![image](https://user-images.githubusercontent.com/587790/27765619-5ea7a5ec-5e6b-11e7-9a3f-d45d105cf5e8.png)

Pressed context menu button:

![image](https://user-images.githubusercontent.com/587790/27765620-7290c3b8-5e6b-11e7-83c3-3245459f195c.png)

Arrow-keyed down to correct spelling and pressed Enter:

![image](https://user-images.githubusercontent.com/587790/27765621-75f164d6-5e6b-11e7-9b6f-50f9de200cfc.png)

**Comment by duckbrain** [comment]
With the 0.9.30 release it is behaving differently, but still incorrectly.

Here are some sample changes, note the missing characters.:

```
This is misspelleld.
This is misspelled
```

```
This is misspelleld+different.
This is misspelleddifferent.
```

```
This is misspelleld +different.
This is misspelled+different.
```

```
This is misspelleld+ different.
This is misspelled different.
```

It seems like it's eating the first character after the word and replacing it with a space if there is another word that character. Also even correct transformations are adding the second undo state.

```
This is misspelleld
This is misspelled
```

This is the correct behavior, but doing `Ctrl+Z` highlights the word "misspelled" instead of undoing the spelling correction. Doing `Ctrl+Z` again undoes spelling correction.

**Comment by abnerlee** [comment]
we are now v0.9.38, could you confirm this bug on the latest version?

**Comment by duckbrain** [comment]
The behavior has not changed from [my last comment](https://github.com/typora/typora-issues/issues/663#issuecomment-321542867).

**Comment by vassudanagunta** [comment]
I can confirm this is not an issue on macOS.

**Comment by duckbrain** [comment]
I just ran through my test case again. The behaviour has not changed and is still that right-clicking and selecting a menu item corrects spelling correctly, but using the Menu/Application key ![Menu key](https://help.gnome.org/users/gnome-help/stable/figures/keyboard-key-menu.svg) and selecting a spelling correction with the arrow keys and pressing enter will add an undo state of the correct spelling, and a second undo state, sometimes with characters removed.

**Comment by abnerlee** [comment]
> but using the Menu/Application key

This is a new info, we reproduce the bug now.

**Comment by duckbrain** [comment]
> When using the context menu key to open the context menu for spell check...

I was wondering if that part had not been communicated properly. Sorry about that. :wink:

**Comment by abnerlee** [comment]
> When using the context menu key to open the context menu for spell check...

😂 didn't notice that... Sorry for it

**Comment by abnerlee** [comment]
Fixed in new release
