### ISSUE TITLE
Can't remember the window size sometimes

### ISSUE THREAD

**Issue by zttt** [typora/typora-issues#664]
It will open md files in a window the same size as the last one most of the time. But sometimes it opens the file in a small window, about 650x620 (default size?). 

os: Mac 
vrsion: 0.9.9.9.4.2

**Comment by kimcheng** [comment]
i'm very like typora , lt's very clear and nice

**Comment by jeffswt** [comment]
Neither can it remember the window position.

Most importantly, it never remembers the window position.

But so far I've not seen any cases of not remembering the window size.

I use Windows.

**Comment by abnerlee** [comment]
In last update, Typora will use window position/size of last closed one or current opened one.
Please reopen this, if similar bugs happens
