### ISSUE TITLE
Manual, "2 spaces" line breaks not respected on print or export

### ISSUE THREAD

**Issue by claytonrcarter** [typora/typora-issues#665]
Adding 2 spaces to the end of a line displays new lines (without paragraph spacing) fine in the app, but these manual line breaks are not respected when the document is printed or exported.  Instead, they are treated like regular paragraph breaks.

Here is a screenshot to illustrate.  Typora is on the left, PDF export is on the right.
![screen shot 2017-04-26 at 11 05 29 am](https://cloud.githubusercontent.com/assets/1420419/25441602/a4b662d2-2a70-11e7-8160-d92ddd804375.png)

**Comment by abnerlee** [comment]
should be fixed in newest version
