### ISSUE TITLE
Typographer's Quotes

### ISSUE THREAD

**Issue by jlarmstrongiv** [typora/typora-issues#667]
Unless I missed it, there ought to be a setting somewhere to enable typographer's quotes ([the curly quotes](http://practicaltypography.com/straight-and-curly-quotes.html)).  On one hand, the straight quotes would be very useful in code blocks; on the other hand, the typographer's quotes are good for writing in general (while a toggle with a shortcut would be nice, having typora know when to use which type of quote in preferences would be great as well).

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/610
