### ISSUE TITLE
Add Image - Copies image to selected folder

### ISSUE THREAD

**Issue by DanBennettUK** [typora/typora-issues#67]
This might be a bit of a strange feature request, but no one seems to be doing this yet.

What would be grand is an option to copy all images that I put in a markdown file, into an images folder I've chosen, and it references that image with the relative path e.g. `/images/file.png`. So that when the file is published as an HTML page, the image still works.

Means no faff required for getting images added. I can just copy & paste into the editor.

**Comment by waahto** [comment]
+1. The document should be saved before exporting images to a folder.

Related to: https://github.com/typora/typora-issues/issues/17

**Comment by jhildenbiddle** [comment]
I just sent an email about a similar feature request, although I had suggested embedding images within markdown files using base64 encoding to avoid dealing with paths and external files entirely.

Here's the relevant part of the email: 

> When adding images to documents, it would be great if Typora had the ability to embed images within the markdown file using base64 encoding. This would prevent the need to maintain external images and the proper paths (which becomes tricky when working on multiple devices). I realize this may not be standard practice for markdown files, but it would make files infinitely more portable. For those instances where a markdown file with embedded base64 images causes issues (like uploading a README to GitHub which strips base64 images), an option to export to separate image files and a clean markdown file which references them could be used.

**Comment by jhildenbiddle** [comment]
Add a related enhancement require here:

Embed images using base64 (with export md+images option)
https://github.com/typora/typora-issues/issues/88

**Comment by anandgraves** [comment]
+1

**Comment by abnerlee** [comment]
see http://support.typora.io/Images/

**Comment by Kienyew** [comment]
I have written a script that does this function in https://github.com/Kienyew/Typora-Image-Centralize
