### ISSUE TITLE
The default user's settings for font fallback seem not working

### ISSUE THREAD

**Issue by celestialphineas** [typora/typora-issues#671]
The user's settings for default font fallback in `conf.user.json` are not working any longer since version 0.9.27 on Windows.

**Comment by abnerlee** [comment]
What's your current CSS style for font-family? The css setting can override this

**Comment by celestialphineas** [comment]
I did not specify a font family in my theme CSS, and this fall-back feature vanished after some update. Now I'm working with a overriding CSS though.

**Comment by celestialphineas** [comment]
I also had a problem exporting PDF after today's Typora update on Windows 10 (Creator's Update). The exporting process keeps running and taking up CPU resources but does not come to an end for minutes. Should I open another issue to report this?

**Comment by celestialphineas** [comment]
I think I know the reason why the “export” won't work. It meets a problem handling the new Super OTC support in Windows 10 Creator's Update. Typora does not crash when exporting files with no Super OTC fonts are used.

**Comment by abnerlee** [comment]
`new Super OTC `, thanks for this info, we will check

**Comment by abnerlee** [comment]
Should be fixed already
