### ISSUE TITLE
Feature Request: Switching from MathJax to KaTeX

### ISSUE THREAD

**Issue by jeffswt** [typora/typora-issues#672]
Personally I find KaTeX around 10 times faster than MathJax.

Although currently it lacks a few functions (Like no \\s outside an environment), but most importantly it is fast.

Or maybe you could use KaTeX as an optional function.

The link over here: https://github.com/Khan/KaTeX

**Comment by abnerlee** [comment]
KaTeX still lack a few functions

**Comment by zifeo** [comment]
@abnerlee even if KaTeX is not 100% compatible, it would be great to have both implemented. Currently some of my files take 10-20s to fully render on Typora and I can only edit them by splitting them into chunks. This sadly limits the possible workflows.

Related issues #92 and #888.
