### ISSUE TITLE
Feature request: Add right-aligned paragraph/line

### ISSUE THREAD

**Issue by citizenR** [typora/typora-issues#673]
It's NOT a default markdown feature, but when we use Typora to write a letter, it'll be helpful. Thanks.

**Comment by celestialphineas** [comment]
It would also be useful to add a center-aligned feature. Or just support the HTML tags with "style" attribute. Thank you.

**Comment by abnerlee** [comment]
HTML tags are now supported.

You could use
```
<p style="text-align:right">
text...
</p>
```

For such styles

**Comment by sataset** [comment]
@abnerlee It does not work with markdown language or formulas.

![Screenshot at May 01 3-10-29 AM](https://user-images.githubusercontent.com/28687456/80773175-55706180-8b59-11ea-91cc-93e055dc1c61.png)

**Comment by Dartypier** [comment]
You can solve the issue by adding a custom css directive in the theme you are using. [Add Custom CSS Typora](https://support.typora.io/Add-Custom-CSS)

For example by adding this to your current theme in CSS 'p' declaration:
```
p {
    text-align: justify !important;
}
```
Your Math (inline and block) will remain formatted.

**Comment by abnerlee** [comment]
> @abnerlee It does not work with markdown language or formulas inside.
This is described in #1939
