### ISSUE TITLE
Font awesome icon supports

### ISSUE THREAD

**Issue by yujincheng08** [typora/typora-issues#674]
This is awesome editor I've ever seen!
I am eager for Font awesome icons support and vim key bounding?
If supporting this two feature it would be better I think!
Thx!

**Comment by abnerlee** [comment]
` Font awesome icons` is not a common markdown feature, we could recommend to use emoji instead

**Comment by gynl** [comment]
I was making a mermaid chart and discoverd that this works :

\`\`\`
 graph LR;
A[fa:fa-gear] -->B(fa:fa-wrench);
\`\`\`

I can understand that _« Font awesome icons is not a common markdown feature »_, but it's a little bit ridiculous to be able to use it in graphs and not in texts.

It must be possible do something. Please do it possible ! 🙏

**Comment by abnerlee** [comment]
merge in #286
