### ISSUE TITLE
Feature Request: indented code blocks

### ISSUE THREAD

**Issue by othree** [typora/typora-issues#677]
It will be great if typora supports output markdown format text with [indented code block][1].
The first markdown [spec][2] only supports this kind code block.
And some old implementation only realize it (like markdown.pl).

[1]:http://spec.commonmark.org/0.26/#indented-code-blocks
[2]:http://daringfireball.net/projects/markdown/syntax#precode

**Comment by abnerlee** [comment]
We already support code blocks with indent when paste as markdown or open existing file/ switch from markdown source code. But we are less likely to support this when user type 4 white space or tab. It is difficult to delete "invisible" indention on a code block.
