### ISSUE TITLE
Hyphens becomes dashes when exported to PDF (Windows)

### ISSUE THREAD

**Issue by yamaton** [typora/typora-issues#678]
Hyphens are automatically converted to dashes when exported to PDF. For example, 

```
sudo apt-get update
```

becomes following when exported to PDF:

```
sudo apt‐get update
```

(Do you see the difference!?)
This happens only on Windows version. Confirmed it does not happen on Mac / Ubuntu.
Please fix this nasty bug.

**Comment by yamaton** [comment]
This conversion matters because **it happens within a code block**. People will be screwed if they copy the latter command.

**Comment by styfle** [comment]
To be clear, the first example is a [HYPHEN-MINUS (45)](http://www.fileformat.info/info/unicode/char/2d/index.htm) and the second example is a [HYPHEN (8208)](http://www.fileformat.info/info/unicode/char/2010/index.htm).

#### JS Snippet
```js
console.log('sudo apt-get update'.charCodeAt(8)); // 45
console.log('sudo apt‐get update'.charCodeAt(8)); // 8208
```

**Comment by abnerlee** [comment]
I cannot reproduce this on macOS with Typora and preview.app

@yamaton could you check this https://github.com/typora/typora-issues/issues/740 and confirm it is our bug.

Also, what's your OS version?

**Comment by xiaosuiba** [comment]
affect me too.
