### ISSUE TITLE
Objective-C code block isn't highlighted

### ISSUE THREAD

**Issue by chester39** [typora/typora-issues#679]
When I use typora, I think it is a great Markdown editor. But sometimes I found, when I use Objective-C code, the highlight is incomplete. Hope typora will be the best Markdown editor, thanks!

**Comment by abnerlee** [comment]
> the highlight is incomplete

Could you write a sample code snip which cannot be highlighted *completely*?

**Comment by chester39** [comment]
![img](https://pic.kuaizhan.com/g1/M01/49/E5/CgpQU1kQitSAat-bAALYEdeBeT09306271)
Just like this, NSString/NSInteger/weak is not highlighted.

**Comment by abnerlee** [comment]
Relies on the syntax highlight update of CodeMirror -> http://codemirror.net/mode/clike/index.html

Cannot be fixed on our side
