### ISSUE TITLE
Cursor during selection of text changes

### ISSUE THREAD

**Issue by dvdstelt** [typora/typora-issues#680]
OS : Windows 10
Typora : 0.9.29

Using cursor keys & selecting text, I sometimes use `SHIFT` key to select text faster. It moves the cursor to the next word.
When I select text from end to start (so from right to left), after releasing the `SHIFT` key, the cursor (which isn't visible) changes to the end of the word.
So basically where it initially was at the start, after releasing `SHIFT`, it now adds to (or substracts from) the selection at the back of the selection.

**Comment by abnerlee** [comment]
should be fixed in the newest version
