### ISSUE TITLE
Will typora cost money for single/private users?

### ISSUE THREAD

**Issue by arieljannai** [typora/typora-issues#683]
In the website it says that it's free while in beta.

* What's the plan for later? Pricing different plans? Taking the same from each user?
* Do you already know how much will it cost?

I saw this issue (#16) and I believe that even if (sadly) Typora won't be open source, people will want to know what are the plans about taking money.

**Comment by abnerlee** [comment]
Typora will be paid app after v1.0. Price is same for each user

**Comment by arieljannai** [comment]
Ok, thanks for the answer!

**Comment by RPDeshaies** [comment]
How much will it cost ?
