### ISSUE TITLE
"Enable Debug" does not stop debugging

### ISSUE THREAD

**Issue by DanBennettUK** [typora/typora-issues#69]
With "Enable Debug" unticked, debug events are still being written to the console. 

```
setContent
frame.js:6 saved
frame.js:8 file changed, filename: 2016-01-01-logbook_2016.md
frame.js:6 presentedItemChanged
frame.js:8 file changed, filename: 2016-01-01-logbook_2016.md
frame.js:6 presentedItemChanged
2frame.js:6 presentedItemChanged ignored
```

**Comment by abnerlee** [comment]
Thanks for the feedback.

"Enable Debug" is just a flag whether users can find menu item "Inspect Element" from context menu. It won't change the way how Typora is running.

Console log is just temporary log, and not be visible to users unless they want to see it. So it is quite low priority for this issue

**Comment by DanBennettUK** [comment]
Oh. OK I see. It's just I saw 500 odd logs in the console so presumed that wasn't meant to happen :dancer: 

Apologies!
