### ISSUE TITLE
Text Formatting Misbehaving in Tables

### ISSUE THREAD

**Issue by DIWesser** [typora/typora-issues#692]
When trying to format a single word in a table with emphasis, strong, strike, or underline with either the formatting menu dropdown or the keyboard shortcut, the formatting characters are placed at the start of the first line of text instead of around the selected text.  

- This does not happen with multiple words selected.
- It will happen if only one word is selected in a cell with multiple words.
- If multiple attempts are made to format with either the menu or keyboard shortcut, the characters that should wrap the text are placed between the begging of the text of the first line are the formatting characters that have been added by previous attempts at formatting.
- The behaviour is the same in both the header row and body rows.
- Comment, hyperlink, image, inline math, and highlight work properly
- Remove formatting works properly.

Typora 0.9.9.9.4.2 on macOS 10.12.4 (16E195).

**Comment by orschiro** [comment]
Can you show a screenshot of this problem?

**Comment by abnerlee** [comment]
should be fixed in the newest version
