### ISSUE TITLE
Internal Links don't work

### ISSUE THREAD

**Issue by bouncydot** [typora/typora-issues#693]
I tried a lot of different variations but this variation should work for sure and it doesn't:

```
[click on this link](#my-multi-word-header)

### My Multi Word Header
```

Can anybody confirm this bug or is it on me?

Thank you!

Win7 Vista

**Comment by orschiro** [comment]
Have you tried to click on the link while holding `Ctrl`?

**Comment by bouncydot** [comment]
No I didn't sorry. Now it works fine, thank you!

**Comment by kbsizer** [comment]
Glad this is here.  I seem to forget how to do this and come back every 3~4 months!

**Comment by DutchPete** [comment]
I am sorry to reopen this issue, but I have the same issue as the OP. Holding down the CTRL key while clicking does not make any difference.

**Comment by vassudanagunta** [comment]
> Have you tried to click on the link while holding Ctrl?

It would really be nice to have a "reading" mode where you didn't have to hold down the Command key to follow links. See #89.

**Comment by DutchPete** [comment]
@vassudanagunta: in my comment above just yours I indicated the situation is resolved for me.

As for having a "reading" mode without having to hold down the CTRL/Cmd key:
1. Typora already is clean and distraction free, so I fail to see how a "reader" mode will improve on that
2. having to hold down the CTRL/Cmd key to invoke a feature is such a minor issue to me that I see that as a waste of time of the developers, there are more useful features they can focus on.

**Comment by DutchPete** [comment]
I have to come back to this issue because there does seem to be a bug, in any case in a Windows environment. If you write text on a clean "sheet" an internal link, a.k.a. a reference link, works fine.

But when one has copied text from another file and pasted it as plain text (CTRL+Shift+V), the reference links do not work when holding down the CTRL key together with the left click.

**Comment by abnerlee** [comment]
@DutchPete Could you provide the sample file?

**Comment by DutchPete** [comment]
Abner,

I have not found a way to attach a file to the Github comment so I am 
sending it this way - hope you receive it.
I have attached a sample file. In chapter VII. Manoeuvring there is a 
link "deception" that links to chapter I. Laying plans.

**Comment by abnerlee** [comment]
@DutchPete Sorry, could you it send to us (hi@typora.io)

**Comment by DutchPete** [comment]
Abner, have you been to take a look at the file I sent? Any ideas as to why the reference link does not work?

**Comment by abnerlee** [comment]
Sorry for the late reply. The reference link should contain the whole heading text, but part of it. So please use `[deception](#I.-laying-plans)` in your case.

**Comment by DutchPete** [comment]
Thanks Abner, that works.

**Comment by DutchPete** [comment]
Am I right when I say that a reference link can only be to a header, and not to a point (i.e. an anchor) in the middle of a sentence?

**Comment by KoalaBear84** [comment]
I'm having the same issue as @DutchPete 

When you are referencing 'chapters', you have to include the whole text. But if a new chapter comes up between others every anchor have to be rewritten because the chapter numbers are all 1 up. "Chapter 3 - API" will become "Chapter 4 - API" for example. And the anchor needs to change to #chapter-4---api (I don't know if I have the dashes right. It would be nice if you could create an anchor yourself like [#chapter_api] which will not change.

**Comment by DutchPete** [comment]
I agree with @KoalaBear84 that it would be very useful to be able to create anchor points on a page that are independent of a chapter, and that you can reference. In fact, ideally one should be able to reference an anchor point in a different Typora document, the same way one can reference e.g. an image file.

**Comment by KoalaBear84** [comment]
Indeed.

Hmm, I see that these links that do work inside Typora does not work when exporting to HTML/PDF, I thought they do because the ToC is working fine. Anyone succeeded with this?

**Comment by DutchPete** [comment]
@KoalaBear84: With me internal links still work after export to PDF.

**Comment by KoalaBear84** [comment]
Ah. When using:
`<a href="#Chapter_X">Link test</a>
<a id="Chapter_X"></a>`

**Comment by DutchPete** [comment]
I don't use that format. I use what Abner told me to use
[link title]{#header-title}

That works in a to PDF exported version, but it is still only a reference link to a header.  I would love to be to link to any point within the document, and even to link to it from other .md files.

**Comment by DutchPete** [comment]
This comment is to answer the issue of anchor points. Yes, anchors at any point in the text are possible.

To place an anchor in your document insert `<a name="my-anchor-name"></a>`at the point in your text your want the anchor. *Note: my-anchor-name is for a multiword name; if the name is a single word put it between the quotation marks.*
You to then reference that anchor from anywhere with `[text](#my-anchor-name)`.

Furthermore, to have the anchor point displayed with an anchor symbol like ⚓next to it, add this code to your base.user.css file:
```
/* hide the anchor HTML */
a[name]:empty + .md-raw-inline {
  display:none;
}
a[name]:empty {
  text-decoration: none;
}
a[name]:empty:before {
 content:"⚓";
}
/* show the anchor HTML when cursor is inside */
.md-expand .md-raw-inline {
    display: inline !important;
}
```
