### ISSUE TITLE
shift + alt + cursor down not working correctly

### ISSUE THREAD

**Issue by benutzerfreund** [typora/typora-issues#694]
When I use alt + cursor down, the insertion point jumps to the beginning of the next line. But when I use shift + alt + cursor down, the insertion point just moves one line down – the same as if no "alt" were pressed.

version 0.9.9.9.4.2
OSX 10.11.6

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/491

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1164
