### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by Bricabraque** [typora/typora-issues#695]
Hello there !

I'd suggest to add some translations from the English strings. I'd be totally available to translate the software to both French and Italian.

**Comment by orschiro** [comment]
I can do German. :-)

**Comment by Bricabraque** [comment]
Arf, I've just seen the project wasn't open source. Closed

**Comment by orschiro** [comment]
@Bricabraque can't you still contribute in exchange, for instance, for an extended free use?

Of course, I don't know if this is intended by the creator.

**Comment by styfle** [comment]
In #312 someone offered to do translations and the author didn't sound interested. I don't think there will be many contributions since this is project is not open source.
