### ISSUE TITLE
After exporting the markdown file as docx or pdf, the equation number disappeared.

### ISSUE THREAD

**Issue by thw1021** [typora/typora-issues#696]
I use '\tag' to number every equation, but the number can't show in word or pdf file. How can I solve the problem?
In typora, it is a equation with number.
In word, it's just $$P=Tv_1=\frac{1}{2}\rho v_1A(v_0^2-v_2^2)\tag{2.6}$$
In pdf, the formula shows normally, but there is no number.

**Comment by alphagammamle** [comment]
Same issues here. I used Auto Numbering Math Equations in the preference setting. The equation is numbered for equation block $$ U(x_t,\epsilon_t, d_{t};\theta)= u_{t}+ \epsilon_{t}, $$. In the markdown, it shows the number but exported pdf has no equation number.

**Comment by thw1021** [comment]
I have found a solution. Firstly, you can convert the markdown file(.md) into latex file(.tex), then you can use  latex compiler to export pdf file with equation number.
In the markdown file, you should use ‘\tag’ to number every equation instead Auto Numbering Math Equations in the preference setting

**Comment by ruiyuanlu** [comment]
I've met the same issue. Unfortunately, the latex compiler are not installed. Are there any other solutions? If I use \tag{equation number}, the output of the equations in docx file the are just source codes. The output of Auto Numbering in pdf files looks fine but becomes invalid in docx files.
typora: 0.9.38
sys: Win 10 professional

**Comment by thw1021** [comment]
Maybe you can use this website (https://www.overleaf.com/) to compile the tex files online. But I have found that some syntaxes of typora are not supported by the latex, and I still don't know how to solve it. You can try it if you find no other way to solve your problem.

**Comment by abnerlee** [comment]
already fixed in new release
