### ISSUE TITLE
Add Grammalecte extension

### ISSUE THREAD

**Issue by emmanuelclement** [typora/typora-issues#698]
Wish more than a bug issue: adding Grammalecte on Typora.
Grammalecte is a (great, french) open source grammatical/typographic spellchecker (for Firefox, Thunderbird and LibreOffice for the moment).
https://www.dicollecte.org/grammalecte/
https://addons.mozilla.org/en/thunderbird/addon/grammalecte-fr-thunderbird/
https://addons.mozilla.org/en/firefox/addon/grammalecte-fr/

**Comment by abnerlee** [comment]
No english doc...

**Comment by inarighas** [comment]
you can find here some english ressources http://code.grammalecte.net:8080/home
