### ISSUE TITLE
Cannot use customized file name when “export as HTML"

### ISSUE THREAD

**Issue by walkerlala** [typora/typora-issues#699]
When finishing my editing and want to export it as a HTML, I cannot save it to a customized name I want. For example, when "export as HTML", I want to save it as `test-file`. However, Typora automatically change it to `test-file.html`. There seems to be no way to change this behavior (or am I wrong?) 

I think it would be better to allow users to manipulate the final file name to what they want, although having a `.html` one by default is good.

Currently is there any method to achieve that in Typora?

Thanks!

**Comment by orschiro** [comment]
I am not sure I understand. 

Isn't it good and wise to automatically append `.html` if you export as HTML?

**Comment by walkerlala** [comment]
@orschiro Yes it would be good to automatically append `.html` **by default** if users export as HTML. But, I think users should have complete control on what the final filenames look like. I mean, it doesn't necessarily requires a `.html` suffix for a HTML file to be a HTML file.

Actually, I am editing some docs using Typora. But I want to hide the `.html` suffix of the resulting HTML files so that I can do some tricky stuff...

**Comment by orschiro** [comment]
> Actually, I am editing some docs using Typora. But I want to hide the .html suffix of the resulting HTML files so that I can do some tricky stuff...

Can you explain?

**Comment by abnerlee** [comment]
I can understand your needs.

But if a user only input `test-file` and click save, they may also expect Typora to append the extension automatically, I think this user case is more common.

**Comment by walkerlala** [comment]
@abnerlee Yes. That is why I say **by default**. Besides from the default option, Typora should allow users to choose other filename. So it would be more rational to not force with a single HTML suffix, but rather, with another option such as "All Files" in the file chooser:

![selection_054](https://cloud.githubusercontent.com/assets/11005974/26035251/1e0e1988-38fc-11e7-8278-54594b20b66f.png)

**Comment by abnerlee** [comment]
That way is reasonable!

**Comment by walkerlala** [comment]
It seems that Typora is based on Chromium. Is there any method to work around this issue so that I don't have to wait for the next release?

Thanks

**Comment by abnerlee** [comment]
I checked with Chrome, it also only supports HTML extension.

And considering there are workaround -- rename after save. We will close this issue
