### ISSUE TITLE
Hyperlinks do not work correctly with non-path URIs

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#700]
Typora 0.9.21 does not work correctly with URIs that aren't paths of some kind.  Specifically:

* If the URL body does not begin with `//` (e.g. mailto: magnet:, etc.), it won't open the URL at all
* If the body *does* begin with `//`, it adds an unnecessary trailing `/`, which breaks URI schemes that are not path based -- that is, the URL is corrupted.

(Note that the second issue affects path-based URLs as well: the URIs `http://x.y/z` and `http://x.y/z/` are NOT equivalent and should not be treated as if they were.)

**Comment by abnerlee** [comment]
Should be fixed in newest version
