### ISSUE TITLE
View pdf/eps image in Typora

### ISSUE THREAD

**Issue by zhangmozhe** [typora/typora-issues#704]
Hi, I've found writing in markdown with Typora is an ideal flow for my academic writing. Just as the project in https://github.com/tompollard/phd_thesis_markdown, using markdown can greatly improve the experience for complicated task such as thesis writing.

My problem is that, whether it is possible to insert and view the pdf or eps image in the Typora, therefore I can see the image directly during editing. Also, is there any support for bibliography and figure/table list? 

Thanks!

**Comment by abnerlee** [comment]
Embedding and viewing PDF/eps file seems too heavy for a file-based markdown editor, and you cannot "preview" the embedded PDF file when you export, share or publish the *md file for exported html/pdf file

**Comment by retrography** [comment]
@abnerlee Typora does preview the PDF images correctly, if I insert the reference manually. But it does not allow me to drag and drop them in the document, nor does it let me insert them using the menu item in the edit menu. The question is: Why not. Now that the preview is there, why shouldn't we be able to insert the PDF image in Typora. This is really essential to academic writing as LaTeX does no support SVG, and we really need a vector format for our plots.

**Comment by redoxmatlab** [comment]
Maybe an old question/discussion. But I have fallen in the same issue as @retrography and I fully support the idea of view PDF.

I even have a diffrent issue where it is essential to be able to open a pdf file inside the folder by clicking. This is important when you have some complex folder tree and so accessing PDF directly from Typora would make life much easier. I should stress that I am not suggesting to view the PDF file in Typora but at least to be able to see it in the folder tree and clickign it viewit in the default PDF viewer. That would be a great feature.

**Comment by kongdd** [comment]
call for this feature too.

**Comment by Myst1cX** [comment]
adding to the thread, fingers crossed
