### ISSUE TITLE
Support inline HTML tag

### ISSUE THREAD

**Issue by be5invis** [typora/typora-issues#705]
Sample
![image](https://cloud.githubusercontent.com/assets/240091/26103015/3ce1992e-3a6a-11e7-9b03-baf46e812b2d.png)

**Comment by gongchao** [comment]
+1

**Comment by vertesy** [comment]
#### HTML tags are necessary to be compatible with GitHub Flavored Markdown.

Currently a text with super- or subscripts can either exclusively work on GitHub `A<sub>K</sub> ` or exclusively in Typora `A~K~`.

I found no way to write a markdown document that renders correctly in both.

**Comment by vidavidorra** [comment]
Would also love this feature!

**Comment by Jim-Zenn** [comment]
This feature makes a lot of sense to me.

**Comment by seamusdemora** [comment]
I'll add myself to the list of those who would like to see Typora be truly GHM compliant.

**Comment by GarfieldJiang** [comment]
Is this going to be done?

**Comment by abnerlee** [comment]
Supported in new release.
