### ISSUE TITLE
Add function for user-defined snippet ?

### ISSUE THREAD

**Issue by 0x000001** [typora/typora-issues#707]
To write some specific formed articles，use snipped to insert the outline ,Tab to jump the location defined to modify. Just like sublime snippet 
http://docs.sublimetext.info/en/latest/extensibility/snippets.html?highlight=snippet
@orschiro

**Comment by orschiro** [comment]
Can you give an example?

**Comment by 0x000001** [comment]
To write some specific formed articles，use snipped to insert  the outline ,Tab to jump the location defined to modify. Just like sublime snippet ![mark](http://oprk3pjw9.bkt.clouddn.com/pic/20170517/125554436.gif-wm)

**Comment by abnerlee** [comment]
I think this can/should be achieved by some 3rd party tools, like TextExpander or something.

Currently, we will focus on more "core" functions.

**Comment by AnthoOzier** [comment]
Hello, 
I'm starting using Typora and I'm used to Texmaker personalization of snippets. 
Any news for this issue so far?
Thanks

**Comment by cser** [comment]
> It is a good suggestion, but I think this can/should be achieved by some 3rd party tools, like TextExpander or something.
Elso free tools can be used: espanso or aText(for windows 7 users)

**Comment by maojunhat** [comment]
> It is a good suggestion, but I think this can/should be achieved by some 3rd party tools, like TextExpander or something.
> 
> Currently, we will focus on more "core" functions.

I hope the I can jump the cursor to the next placeholder by pressing tab, like vscode snippets. Seems like TextExpander and aText cant do that. 🥲
