### ISSUE TITLE
Pasted images aren't copied to selected folder or server

### ISSUE THREAD

**Issue by blark** [typora/typora-issues#708]
When "Copy Image File to Folder" is selected, and an image is pasted in from the clipboard it is not always copied to the selected  folder. 

I am using SnagIt to take screenshots, then copy them to the clipboard when I paste them into Textile the image path that results is:

`[img](file:///C:/Users/USERNAME/AppData/Local/Temp/SNAGHTML4645ed.PNG)`

The first image that I pasted was successfully copied, but for some reason the others after that are not. 

Ps. Thanks for the great work on this application, I love it.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/875 
https://github.com/typora/typora-issues/issues/1135

Supported in new release. Locations for saving the image can be set by YAML or in preference panel
