### ISSUE TITLE
Image selection is very difficult (CTRL-L does not work)

### ISSUE THREAD

**Issue by blark** [typora/typora-issues#709]
There is no easy or good way to select an image for deletion or to move it around. This makes editing when images are in the document a very tedious task. 

For example, you cannot click, double click or triple click on the line to select its contents. And the "select line/sentence" hotkey does not select the FULL image line.

I would like to suggest that Ctrl-L should select the entire line so the user can then simply cut and paste it, in addition perhaps clicking on the image icon should select the whole line?

**Comment by abnerlee** [comment]
CTRL+L should now work for image.

**Comment by blark** [comment]
Thanks very much. Works great.
