### ISSUE TITLE
Scroll contents but keep cursor in the same place

### ISSUE THREAD

**Issue by bjonni** [typora/typora-issues#711]
In most editors I've tried on Windows you can scroll the contents but keep the cursor in the same place in the file with CTRL+ARROW UP or CTRL+ARROW DOWN. 

I miss this option when I edit longer files.

**Comment by abnerlee** [comment]
`CTRL+ARROW UP` and `CTRL+ARROW DOWN` seems to be `Up one paragraph` and `Down one paragraph` for most apps on Windows (https://support.office.com/en-us/article/Keyboard-shortcuts-in-Word-Online-4ccbb899-f71e-4206-be6f-1d30c7d1bd13)

Typora will follow this on Windows. If you know the standard shortcut keys for move to beginning/end of the whole article on Windows, please let us know.
