### ISSUE TITLE
Large amount of blank space to the left of document

### ISSUE THREAD

**Issue by abdullaahi140** [typora/typora-issues#712]
@abnerlee 

Huge amount of blank space to the left. Is there an easy fix for this?

**Monospace theme**

![image](https://cloud.githubusercontent.com/assets/28843151/26285309/354a82e6-3e45-11e7-9d35-0270876981a3.png)

**Comment by abnerlee** [comment]
It is controlled by CSS (http://huewiki/mediawiki/index.php/Table_with_data_source) change the `max-width` of `#write` should work.

We will also update the theme

**Comment by abdullaahi140** [comment]
@abnerlee 

The link you sent does not work

**Comment by abnerlee** [comment]
Sorry, I updated the link

**Comment by abnerlee** [comment]
Please check the new update, and download the new version of monospace theme
