### ISSUE TITLE
Touchpad scrolling not working in menus

### ISSUE THREAD

**Issue by abdullaahi140** [typora/typora-issues#713]
@abnerlee 

2 finger scrolling not working when in the menu however it works when editing a document. It was working previously though.

I cannot scroll in this menu for example:
![image](https://cloud.githubusercontent.com/assets/28843151/26285355/f8afefd2-3e45-11e7-85ac-e6ffe957c9e9.png)

Also the scroll bar is really thin, so it really is difficult to get at the scroll bar with the touchpad. My laptop has a touchscreen so I'm using that as a workaround.

**OS**: Windows 10
**Touchpad Driver**: Elantech

Thanks.

**Comment by abnerlee** [comment]
Seems fixed in newest version
