### ISSUE TITLE
English UK Dictionary Support

### ISSUE THREAD

**Issue by abdullaahi140** [typora/typora-issues#714]
@abnerlee 

Please. Having English US is maddening. Trying to remove "u" from their rightful place and the replacing "s" with "z" in a couple of work.

Please, please, pls, plz

**Comment by hidesoon** [comment]
Met the same issue. 
Only have EN US is painful for the users in UK.
Please help or get some solution

**Comment by abnerlee** [comment]
to https://github.com/typora/typora-issues/issues/723
