### ISSUE TITLE
Feature Request: Command line tool to access Export feature

### ISSUE THREAD

**Issue by rainux** [typora/typora-issues#715]
I love Typora's render effect and PDF export feature. It would be awesome if Typora provide a command line tool to allow quick and/or batch exporting.

**Comment by hnes** [comment]
Bravo! Maybe something just like `$ typora a.md -o a.html` or `$ typora a.md -o a.pdf` would be pretty lovely and handy :)

**Comment by hezhiming** [comment]
Yes!

or like this: `typora my-md-dir/ -o  build/`


I love Typora, Thanks Lee for the Great Job !

**Comment by xxf1995** [comment]
Up this!

**Comment by Yethiel** [comment]
I could very well use this!

**Comment by JochenJankowai** [comment]
I'd also love to see this!

**Comment by alkaphreak** [comment]
Me too.

**Comment by magrandera** [comment]
Would be very helpful for me too!

**Comment by noio** [comment]
Ah yes! I was about to create a feature request for an "auto export" option that exports each time after saving. But this is of course waaay more flexible. This would you create such a feature from the command line with ease.

**Comment by twttao** [comment]
I would also like to have handy command-line export options, ideally for both PDF and HTML.

**Comment by ldnvnbl** [comment]
Me too.

**Comment by toomey8** [comment]
+1!

**Comment by alkaphreak** [comment]
md2pdf gentlemen : https://bitbucket.org/freak0/md2pdf/

:)

**Comment by inem** [comment]
+1

**Comment by agilim** [comment]
I would use that in a heartbeat.  Doing this one at a time is getting old.

**Comment by GavinNovate** [comment]
Me too.

**Comment by tgeselle** [comment]
+1

**Comment by dudebing99** [comment]
Would be much more convenient if we can export by command line.
We can add a pre-commit hook to export HTML from MD providing that feature

**Comment by dudebing99** [comment]
@abnerlee Is it in your plan to add this feature, thx

**Comment by fivetwofoureight** [comment]
[Here's a workaround I've found](https://www.computerhope.com/issues/ch001376.htm#merge-text) 
First, you merge all your `.md` files into one big `.md`, then you open the large file in Typora, adjust the formatting, and export as normal. The main issue with this method is that the page boundaries between merged documents are usually messed up unless you have a consistent line break at the end of each document. Even then, boundaries between `.md` files won't align with page boundaries, so the end of one file and the beginning of the next can show on the same page.

**Comment by fivetwofoureight** [comment]
@dudebing99 yeah you're right. 
it's only helpful to combine-then-export if you were looking to combine the `.md` files at then end.

**Comment by YSMull** [comment]
+1

**Comment by YSMull** [comment]
@abnerlee Is it in your plan to add this feature, thx

**Comment by abnerlee** [comment]
merge into #1999

**Comment by jounjieli** [comment]
+1

**Comment by carlskii** [comment]
Yep - I need this too!

**Comment by R-o-y** [comment]
+1
