### ISSUE TITLE
Default filename logic regression (return of issue #148)

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#716]
At some point after Issue #148 was fixed the buggy behavior was re-introduced.

From #148: 

> Normally Typora automatically uses the first paragraph as the default filename when saving a file. But if there is YAML front matter (i.e. at the beginning of the doc), the default filename is simply a "-".
>
> YAML front matter or any other metadata should be ignore by the default filename logic.

Except now the default filename is `Untitled.md`

**Comment by abnerlee** [comment]
should already be fixed since I cannot reproduce it now on newest version
