### ISSUE TITLE
Hyperlinks aren't parsed and rendered in footnotes

### ISSUE THREAD

**Issue by dbalbright** [typora/typora-issues#718]
It remains in unrendered markdown source in the footnote text. i.e.: `[FreeBSD](https://www.freebsd.org)`

![image](https://cloud.githubusercontent.com/assets/1958902/26438561/c15957cc-40f1-11e7-8e9a-d6f3d23e84d1.png)

Oddly they render in the hover-bubble text.

**Comment by abnerlee** [comment]
It is working with [FreeBSD](https://www.freebsd.org) in footnote on my Windows 10.

Any steps to reproduce this bug?

**Comment by dbalbright** [comment]
Yeah I just went back and looked and this is no longer rendering incorrectly. Somehow it must've gotten fixed between then and now. (y)

**Comment by abnerlee** [comment]
reproduced in #5094
