### ISSUE TITLE
Save Dialog Wording

### ISSUE THREAD

**Issue by aireq** [typora/typora-issues#719]
I find the wording on the Save warning dialog a little confusing. I always have to think about what clicking “Ok” actually  means. 

![save](https://cloud.githubusercontent.com/assets/1441899/26508331/39d8d14c-4209-11e7-943b-c85cd7a21289.png)

Here’s how I propose the dialog be changed. I find this reads a lot easier.

![save proposed](https://cloud.githubusercontent.com/assets/1441899/26508380/582bccc6-4209-11e7-84af-2ac7980548f8.png)

**Comment by abnerlee** [comment]
Already changed the words
