### ISSUE TITLE
underscore becomes strange square symbols after update to 0.9.8.7(Mac OS X)

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#72]
Hi team,

After updating to the latest version, suddenly and strangely all underscore `_` in the file becomes a strange square:( Please see the screenshot for details.

![](http://7xj3js.com1.z0.glb.clouddn.com/Snip20160303_31.png)

Not sure if all users becomes this or only mine becomes this.

**Comment by abnerlee** [comment]
Sorry for this bug, please do upgrade again

**Comment by leewi9** [comment]
@abnerlee It seems still have some problem...

![](http://7xj3js.com1.z0.glb.clouddn.com/Untitled.gif)

**Comment by abnerlee** [comment]
sorry, must been fixed this time ~ please update again
