### ISSUE TITLE
Unable to show image pasting from Wechat articles

### ISSUE THREAD

**Issue by yangshaoshun** [typora/typora-issues#720]
When I copy some content from Wechat Article, I found some images can not be shown correctly.
But in Github Issue comments it is right.

* The result is like this

![](http://obu0kc303.bkt.clouddn.com/20170527149587456955523.jpg?imageView2/0/format/jpg)

* The image address is 

`![img](http://mmbiz.qpic.cn/mmbiz_jpg/ice5enJHe2TgibrztREDX7ghviaUFEIx54W3gLdxibC6VnhcdgQn656xG5C8KWYIQAA8fV4JFSfMfK2ultLhY2tS4g/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1)`

**Comment by abnerlee** [comment]
This is caused by macOS Safari does not support WebP format. There is nothing Typora can do because it is built on Webkit(Safari).

You could use this instead

```
![img](http://mmbiz.qpic.cn/mmbiz_jpg/ice5enJHe2TgibrztREDX7ghviaUFEIx54W3gLdxibC6VnhcdgQn656xG5C8KWYIQAA8fV4JFSfMfK2ultLhY2tS4g/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1)
```

**Comment by lvicent** [comment]
Also this problem.
I want rename the image name by some rule? 
Any resovle way?
