### ISSUE TITLE
Diagrams backend

### ISSUE THREAD

**Issue by Voleking** [typora/typora-issues#722]
Typora generate diagrams is much more clear than [mermaid-filter](https://github.com/raghur/mermaid-filter). I wonder it's backend and how can I use pandoc from shell to convert md to docx or html like typora.

**Comment by abnerlee** [comment]
It is not backend.

 [js-sequence](https://bramp.github.io/js-sequence-diagrams/)
 
[Flowchart.js](http://flowchart.js.org/)

[Mermaid](https://knsv.github.io/mermaid/#mermaid)

is used
