### ISSUE TITLE
Multilanguage dictionaries support

### ISSUE THREAD

**Issue by andreaspada** [typora/typora-issues#723]
I write various kind of documents, in at least three languages. So, many times I found myself writing in Italian, or Portuguese, or some other language and whenever I write a word or a sentence that do not belong to US English, my text is always red marked.  There's a way to alter the default language for a document?

Something I think would be tremendously useful too, for who speak and switch among multiple languages in the same document, it's a feature to mark a specific paragraph - or section - in a specific language. So, if I'm writing an English document and I want to include a, said, Italian citation, I can wrap that foreign language section to be spell checked correctly. Is this possible, in a feasible future?

**Comment by Halipster** [comment]
+1 for multi-language spell checking support.

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/457
