### ISSUE TITLE
Ubuntu install not working

### ISSUE THREAD

**Issue by creationmaestro** [typora/typora-issues#724]
I have been trying to install typora in ubuntu 17.04
by:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
sudo add-apt-repository 'deb https://typora.io ./linux/'
sudo apt-get update
sudo apt-get install typora

but first command is not working
and repository is also not added properly

any solution ??

**Comment by abnerlee** [comment]
What is the output in terminal?

**Comment by j-ockenden-hwcomms** [comment]
I also have this issue.
After executing

` sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE`

The following line appears in konsole, but nothing further seems to happen

`Executing: /tmp/apt-key-gpghome.lJ359LcDMb/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE`

**Comment by abnerlee** [comment]
Need more info
