### ISSUE TITLE
More accurate progress reporting

### ISSUE THREAD

**Issue by fulldecent** [typora/typora-issues#725]
Currently this is what we have

![d5106eb8-152c-11e7-80bf-1f6a9e06e729](https://cloud.githubusercontent.com/assets/382183/26655385/93dba228-4628-11e7-98a7-571a486bd17b.png)

PanDoc supports better progress reporting, please see https://github.com/jgm/pandoc/issues/3540#issuecomment-305020044

**Comment by fulldecent** [comment]
Please accept this issue. Will a PR be accepted if it fixes this?

**Comment by abnerlee** [comment]
docx does not have `--trace` support.

And we do not have plan for this, since the time cost is not that much.
