### ISSUE TITLE
Pasting plain text from a browser (FF) results in hard wrapped text, which is not what I want

### ISSUE THREAD

**Issue by quesada** [typora/typora-issues#727]
Is there any way to make it do the right thing and use soft wrap?
In 2017, every text editor can handle long lines. The hard wrap also feels like it's terribly narrow, like 70 chars or so.

**Comment by abnerlee** [comment]
Copy from which URL?

**Comment by quesada** [comment]
Any url... try for example this:
https://hired.com/careers/624980-product-manager-growth?cookie_consent=true

**Comment by abnerlee** [comment]
I tried with Chrome, it seems OK. What's your OS by the way?

**Comment by quesada** [comment]
Manjaro KDE. I can tell the system where you do testing and mine are not the same. I find about a bug per hour :)

**Comment by abnerlee** [comment]
cannot reproduce this on Ubuntu. Please reopen this if it still exists.
