### ISSUE TITLE
Option to stop auto-formatting when saving.

### ISSUE THREAD

**Issue by zttt** [typora/typora-issues#73]
I like adding empty lines between sections. However, it seems typora will(occasionally?) delete those lines when saving, and the article will look crowded.

Please add an checkbox for disabling this behavior.

**Comment by abnerlee** [comment]
Typora will try to keep the current formatting, so that should be a bug.

Could you paste the markdown snip before and after your auto-saving?

**Comment by zttt** [comment]
I did a little more test. It turns out that empty lines after a list may be deleted. And it happens in the opening file process(instead of saving).

For example:
This is the desired effect:
***********************************************************
<img width="266" alt="before" src="https://cloud.githubusercontent.com/assets/8820946/13523925/418eab5a-e233-11e5-8834-195f406f0dab.png">
***********************************************************

This is how it looks after reopening:
***********************************************************
<img width="299" alt="after" src="https://cloud.githubusercontent.com/assets/8820946/13523924/41590f54-e233-11e5-80c5-3de7b00d41ca.png">
***********************************************************

Base on my tests, it seems that this behavior is not 100% reproduceable. Sometimes it happens after you "close and reopen" multiple times.

Source text before saving: http://pastebin.com/2refRmYN
Source text after opening: http://pastebin.com/3nNiRu2b

**Comment by abnerlee** [comment]
This formatting bug has been fixed in latest version
