### ISSUE TITLE
Page Functionality

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#730]
I think adding page functionality to Typora would be a huge benefit: either a toggle option through the menu, or an option before print.

If done as a page option, it would be easy to add / remove pages and format based on the page itself.

If done as a print option, it could be specified if page numbers should be added, and see how formatting would look. If done as a print option however, it would be nice to have a command that could be added to choose where to break the page. 

*For example, using a command such as* `\newpage` *or the like to indicate where a new page should start. This would be useful for formatting when it comes to Headers, to make the end result look better.*

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/118
