### ISSUE TITLE
Going to full screen and back loses the menu bar (linux)

### ISSUE THREAD

**Issue by quesada** [typora/typora-issues#732]
Easy to reproduce. Press F11 twice.
Manjaro KDE

**Comment by abnerlee** [comment]
You mean `back` not `blank`, right?

**Comment by psimacek** [comment]
alt key does nothing. I want to hide menu bar, but it doesn't work. When I press F11 twice, then the menu bar hides itself. But, when I go with mouse over the window decoration, menu bar appears.

**Comment by abnerlee** [comment]
Should be fixed in new release
