### ISSUE TITLE
Pressing 'adv page' breaks the text centering completely (linux)

### ISSUE THREAD

**Issue by quesada** [typora/typora-issues#735]
Easy to replicate: simply press 'adv page'.

I appreciate this is a beta, but the niggles are starting to make it a no-go. As a one-man-job, it's a very impressive effort. A bit more QA could do wonders, at least on linux. Can tell it's tested on macs only.

**Comment by abnerlee** [comment]
@quesada Hi, sorry, what is 'adv page'? is it the `page up` key?

**Comment by abnerlee** [comment]
Need more info about "adv page" key
