### ISSUE TITLE
Copy as Markdown doing weird things

### ISSUE THREAD

**Issue by timpulver** [typora/typora-issues#737]
Sometimes when pressing `Edit` —> `Copy as Markdown` characters are inserted into the text. I’m using the latest version of Typora.

**Comment by abnerlee** [comment]
@timpulver What's your OS version, and which characters will be inserted. 

and when this happened, you trigger `Copy as Markdown` from menu or from shortcut key?

**Comment by timpulver** [comment]
I’m using macOS 10.12.4 with the latest Typora version.
I marked all text in my document with `cmd + a` and then pressed `edit —> copy as markdown` in the menu. One time a list-bullet (`-`or `*`) was inserted at the beginning, another time a word in the middle of the text, but not sure any more if that’s related to the `copy as markdown`-command.

**Comment by abnerlee** [comment]
seems cannot be reproduced
