### ISSUE TITLE
Highlight failed on 'long comments' in Lua code block

### ISSUE THREAD

**Issue by Blealtan** [typora/typora-issues#738]
Long comments in Lua consists of a `'--'` and a comment body surrounded by a pair of long brackets, as is shown below:

```lua
a = 1 --[[
    Long comment body
]]
```

or

```lua
a = 1 --[==[
    Long comment body
]==]
```

For the first case, the highlight succeeds with language specified as `lua`. However, for the second form with brackets of level larger then 0, the highlight failed: only the first line correctly rendered with color for comments (aka brown in the default theme, GitHub).

I'm using Typora for Windows, version 0.9.29 (beta).

**Comment by abnerlee** [comment]
Should be a bug of Codemirror.

I will close it since it should be fixed by updtream
