### ISSUE TITLE
Gifv Support

### ISSUE THREAD

**Issue by xavdid** [typora/typora-issues#739]
While a regular gif works normally, adding `v` to the end (to use the better `.gifv` format, the image isn't found. 

Not working in Typora (but it's a valid link): 
`![hacking](https://i.imgur.com/zALURXu.gifv)` 

Working:
`![hacking](https://i.imgur.com/zALURXu.gif)`

**Comment by abnerlee** [comment]
It will be supported after Safari and Chrome add gifv support

**Comment by xavdid** [comment]
I'm not sure I follow. Both browsers load the image fine.

<img width="641" alt="screen shot 2017-06-12 at 10 16 27 pm" src="https://user-images.githubusercontent.com/1231935/27066971-d739a13a-4fbc-11e7-9789-869eb87772a9.png">

<img width="403" alt="screen shot 2017-06-12 at 10 17 15 pm" src="https://user-images.githubusercontent.com/1231935/27066983-edd1b7ca-4fbc-11e7-9327-35b944d527ef.png">

**Comment by abnerlee** [comment]
Could the see the image below?

![hacking](https://i.imgur.com/zALURXu.gifv)

**Comment by xavdid** [comment]
Github doesn't support `gifv` ([issue here](https://github.com/github/markup/issues/458)), but that seems like a separate deal. Chrome as a browser loads it fine if I visit the page, as shown above.

**Comment by xavdid** [comment]
I'm sorry if I'm misunderstanding, it seems like we're comparing apples to oranges.

**Comment by abnerlee** [comment]
`![hacking](https://i.imgur.com/zALURXu.gifv)` will be rendered like `<img alt="hacking" href="https://i.imgur.com/zALURXu.gifv" />`, if `gifv` is a valid image format supported by your browser, then you would see this image <img alt="hacking" href="https://i.imgur.com/zALURXu.gifv" />

**Comment by xavdid** [comment]
Oh, got it. That makes more sense. Thanks for your patience!
