### ISSUE TITLE
Spell-checker doesn't work properly with superscript

### ISSUE THREAD

**Issue by phuctran93** [typora/typora-issues#741]
Spell-checker consider superscript as part of the word (on Windows).
Please view the screenshot.

![spellcheck](https://user-images.githubusercontent.com/6292239/27170204-483013c6-51d7-11e7-92b4-9ca8a8a454c0.PNG)

Source to reproduce error:
```
This is a footnote[^1].

This is a footnote[^a].

This is a footnote[^ a] with space.

This is a superscript^a^ .
```

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/214
