### ISSUE TITLE
UWP App

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#745]
While not necessary in the current point in time, I think Typora would be a HUGE addition to the Windows App store, and would open up usage for those in Windows 10S.

**Comment by Geliv** [comment]
It will be easier for the developer to sell the app also. I'd like to pay for the uwp and ios version of typora.

**Comment by lloyd094** [comment]
I'm all for having more ways to support the app! One thing to keep in mind however is: "What would the perception be, and what would be the best way to pull this off?" Would it be better to offer it free, and have a donation option or "donator" code of some sort? Or should it be a paid app?

Personally I don't mind paying for my apps. But I know there are several people who would complain if an app (no matter how great) would cost something on one method and then be free on another. I myself enjoy the option of paying what I want (or rather, what I feel accurately represents how good it is), but not everyone shares the same opinion. 

Regardless, this specific decision ends up being the developer's choice. Either way I support, just figured I'd bring up some questions.

For what it's worth, I think Typora would also fit nicely on the Elementary OS AppStore as well, which is a rather pro pay-what-you-want approach to things. Best part with this is that it wouldn't require any extra coding because it's a Ubuntu based OS.

**Comment by abnerlee** [comment]
We are less likely to provide an UWP app, adding to Windows App Store may be possible.

But Typora is not optimized for touch devices, so UWP seems meaningless, if Typora does not perform well with touchscreen logics.
