### ISSUE TITLE
Can not directly open files in the file navigation sidebar

### ISSUE THREAD

**Issue by zihzihtw** [typora/typora-issues#746]
I'm using the Typora on Mac. When drag and drop a folder onto the icon, Typora open the directory in the sidebar. 
However, when I tried to click and open a file, the header changed to that file name but the content is not there. It seems like the file is not open completely or with some error.   

macOS version：macOS Sierra 10.12.5
Typora version：0.9.9.9.4.2 

<img width="653" alt="2017-06-21 5 18 01" src="https://user-images.githubusercontent.com/7886453/27376733-a35a9870-56a5-11e7-8b5f-6542fa562f8b.png">

**Comment by abnerlee** [comment]
Sorry, it is a bug, we will support file navigation on next version, not this version.
