### ISSUE TITLE
Document lost after system crush (windows)

### ISSUE THREAD

**Issue by tekord** [typora/typora-issues#748]
I worked on document and my system crushed. After reboot I have file 15kb size with ALL charachters NULL. I guess crush happened during document saving.

You should really do something to prevent this. Use backup temporary files or something. I lost my 2 day work.

**Comment by abnerlee** [comment]
Sorry for the bug,

There is some backup -> http://support.typora.io/Version-Control/

BTW, could you open Preference Panel -> Open Theme Folder, and send us(<hi@typora.io>) `typora.log` in its parent folder?

**Comment by tekord** [comment]
@abnerlee wow, Thank you very much!! I found my lost file in recovery folder! 

I looked at log, it does not contain any info about my corrupted file. Anyway the probles is solved! Thanks :)

**Comment by abnerlee** [comment]
@tekord The log may not contain sensitive data like file name or file content, but may include useful information about the crashment. So, if possible, we still recommend you to send us the log file.

**Comment by tekord** [comment]
@abnerlee I see there is no sensitive data, but crash caused not by Typora, it caused by my audio driver (blue screen). Logs have nothing interesting in this case :)
