### ISSUE TITLE
Ctrl + Backspace delete content in previous paragraph

### ISSUE THREAD

**Issue by Cooper-Yang** [typora/typora-issues#749]
For text like:
```
This is the first paragraph.
[ 
End
```
If you enter `ctrl` + `backspace` right after "[", it will delete "paragraph. \n [". Which behavior is different from other text editor including vim, word etc.

It would be nice if typora can share the consistency across other text editor.

**Comment by Cooper-Yang** [comment]
And `ctrl` + `delete` also have similar problem.

**Comment by abnerlee** [comment]
shoule be fixed in newest version
