### ISSUE TITLE
Delete key will make Delete or Backspace not working

### ISSUE THREAD

**Issue by nick-korsakov** [typora/typora-issues#75]
Typora version 0.8.5 on Windows 10 x86_64.

Reproduction:
- start Typora in normal mode (not source code mode);
- type some text, e.g. "Hello World";
- press [Delete] button on the keyboard;
- now you can't delete any text nor with [Delete] or [Backspace] button.

**Comment by abnerlee** [comment]
This is a critical bug, we will fix it soon

**Comment by nick-korsakov** [comment]
Awesome! Works. Thank you!

**Comment by jheeffer** [comment]
I had this just pop up in 0.9.22 (beta). It disappeared after reopening the file. Haven't found a way to reproduce it yet. The above steps don't reproduce it, but I did have my backspace & delete not working. I'll post here if I find a clear reproduction.

**Comment by nara6500** [comment]
In 0.9.53 (beta) is the same issue again. Only reopen the file does work for a few minutes...
