### ISSUE TITLE
characters are modified in the language field of  the code fence without warning

### ISSUE THREAD

**Issue by pzhaonet** [typora/typora-issues#750]
Thanks a lot. Typora is a best markdown editor I have ever used. Only two issues are not satisfactory to me. The first is the default language of the code fences (#290), and the second is that some characters are modified automatically in the language field of the code fence. 

I am an R user. I often write R markdown documents, in which I have codes like this:

    ```{r, fig.cap='my fig'}
    # my code
    ```

If I type these texts in the source mode in Typora, Typora converts it automatically into:

    ```{r, fig.cap=&#39;my fig&#39;}
    # my code
    ```
when I switch to the normal mode.

Typora converts `"` into `&quot;` automatically as well.

I had a nightmare-like experience. I had such a long R markdown document written in another text editor, and I opened it with Typora. I did nothing and closed it without saving, and all the quotation marks were converted without any warning. I found that this R markdown document could not be compiled by R. It took me a lot of time to find what the problem was. A "find and replace" way could convert the document back, but is not practical.

I am wondering if there is a way to switch off the automatic converting for the code fences. 

Thank you very much.

**Comment by abnerlee** [comment]
should be fixed in the newest version

**Comment by pzhaonet** [comment]
Yes, fixed! Fantastic! Thanks a lot!

**Comment by SebKranz** [comment]
This bug seems to be back. 

This code block...
![Screenshot 2019-05-04 at 17 59 32](https://user-images.githubusercontent.com/33868262/57181789-89f30400-6e98-11e9-9497-8cc45ab2646c.png)

...gets converted to this:

    ```{r, chunkOption=&quot;in Quotes&quot;}
    This is a code block
    ```

**Comment by ulyngs** [comment]
I just stumbled upon this bug as well! Was just about to commit some changes I'd made in Typora, when I discovered that quotes had been replaced in this way in code chunk options that I'd edited...!

**Comment by abnerlee** [comment]
should be fixed
