### ISSUE TITLE
<br/> tag doesn't work

### ISSUE THREAD

**Issue by pauljurczak** [typora/typora-issues#751]
I'm using version 0.9.29 on Windows 7 64-bit and \<br/\> (and \<br\>) tag has no effect on formating. The tag itself is displayed in non-source mode, grayed out.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/33

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/439
