### ISSUE TITLE
Space-separated hyphens or asterisks for horizontal rules

### ISSUE THREAD

**Issue by gyk** [typora/typora-issues#754]
[Markdown documentation](https://daringfireball.net/projects/markdown/syntax#hr) says it is allowed to put a single space in between the hyphens or asterisks when making a horizontal rule tag `<hr />`, however, Typora will recognize it as a nested list.

**Comment by abnerlee** [comment]
Should be fixed in new version

**Comment by peter-fb** [comment]
That doesn't seem to work with version 0.9.96 on Windows. Hyphens and asterisks with single spaces in them don't work, Typora recognizes them as a nested list.

**Comment by abnerlee** [comment]
@peter-fb could you provide screencast?

**Comment by peter-fb** [comment]
@abnerlee I've recorded a screencast. Where can I upload it?

**Comment by peter-fb** [comment]
OK, I can upload things here.

![ezgif-7-1f3d91757d6c](https://user-images.githubusercontent.com/7101417/97880167-1cd85d00-1d21-11eb-8e02-5ed6680f8baa.gif)

**Comment by abnerlee** [comment]
You can input "* * *" in source code mode, in normal mode, "* " is to insert list

**Comment by peter-fb** [comment]
I see. Maybe you could add a note to the documentation about it.
