### ISSUE TITLE
Text Completion with Hotkey

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#756]
I fully realize this is not a 1.0 feature, but would you consider adding a text completion hotkey, à la Alt-Esc in TextEdit or just Esc in TextMate? This really speeds up text editing, and I frequently miss it. VS Code, as a Markdown editor etc., also handles this via extensions, and can even auto-complete long words appearing elsewhere in the doc without a hotkey, just as you type. Is there perhaps a parser/tokenizer library that can be integrated for this?

![2017-06-28 21 45 45](https://user-images.githubusercontent.com/1819485/27667798-40840316-5c4b-11e7-93d7-a3cc3c24026e.gif)

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/756

**Comment by AlexPasternak** [comment]
@abnerlee, so it's a duplicate with itself? :-) I really tried hard to find a previous request about this, but couldn't find one, so I'm curious about the previous dupe ID.

**Comment by abnerlee** [comment]
sorry, I commented on the wrong issue

**Comment by abnerlee** [comment]
Also relates: https://github.com/typora/typora-issues/issues/66

**Comment by klaus-liebler** [comment]
I miss this text completion this especially for the YAML front matter, where I always have to type in companies keywords and remember our common tag names, e.g
`
tags: [doc-user, lang-de-DE, todo-translate]
`
Indeed, it would be great to have text completion here, either based on a Directory wide file analysis or based on explicit configuration.

Looking towards 1.0 :-) !!!

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1293
