### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by marcrentschler** [typora/typora-issues#757]
Supporting more languages, or at least an option to disable red underlining of "wrong spelling" (which is basically every word in other languages)

**Comment by AlexPasternak** [comment]
What platform do you mean? Because on macOS, you can turn off spell check from Edit > Spelling & Grammar menu.

![image](https://user-images.githubusercontent.com/1819485/27692087-d709ef40-5cb3-11e7-95d2-732e447af7b2.png)

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/513
