### ISSUE TITLE
Typora will not run on Vista

### ISSUE THREAD

**Issue by paulgdowling** [typora/typora-issues#758]
When I try to run Typora on a windows vista machine, it fails to open giving an error:
setcurrentProcessexplicitappusermodelid could not be located in the dynamic link library shell32.dll.
According to Microsoft's page : [SetCurrentProcessExplicitAppUserModelID function](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378422(v=vs.85).aspx)
That function is only available in Windows 7 onwards.

**Comment by abnerlee** [comment]
Typora would require Windows >= Windows 7
