### ISSUE TITLE
Issue in subscript rendering

### ISSUE THREAD

**Issue by MrJasper** [typora/typora-issues#76]
If i type a chemical formula, for example, (NH~4~)~2~SO~4~, characters between the first tilde and the last tilde will be rendered as subscript too:
![pic](https://cloud.githubusercontent.com/assets/15362491/13546353/4e39519e-e2e6-11e5-9885-d6f6983f0e36.PNG)

My typora version: 0.8.5(beta) for windows

**Comment by abnerlee** [comment]
We will fix that, BTW, chemistry support for TeX will be included from next version, you would be able to do so:

```
$$
\ce{C6H5-CHO}
\ce{$A$ ->[\ce{+H2O}] $B$}
\ce{SO4^2- + Ba^2+ -> BaSO4 v}
$$ 
```
