### ISSUE TITLE
possible to support language ActionScript？

### ISSUE THREAD

**Issue by iromise** [typora/typora-issues#760]
Just as the title shows. If possible, thanks.

**Comment by abnerlee** [comment]
Typora use `codemirror` for syntax highlighting, and seems `actionscript` is not supported. 

Please also check this for requiring a new syntax highlight mode for `codemirror` -> https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list

**Comment by iromise** [comment]
Thanks a lot, I'v already require it.

**Comment by abnerlee** [comment]
Closing this, since it requires implementation of https://github.com/codemirror/CodeMirror/wiki/Mode-wish-list
