### ISSUE TITLE
Lack of HTML tag support like <br/>, <ul/>

### ISSUE THREAD

**Issue by thomasq0** [typora/typora-issues#761]
It seems like Typora doesn't support html tags like `<br/>`, `<ul/>`, and `<li/>`. I used these tags to include unordered list in a table cell but failed.
Actually the reference offers `<br/>` to support line break. Is this a bug?

**Comment by vertesy** [comment]
Should be closed and merged to #705 . @thomasq0: Please search before opening a new issue.
