### ISSUE TITLE
A terminal window pop ups when opening Typora on Linux

### ISSUE THREAD

**Issue by agostonbarna** [typora/typora-issues#762]
Sometimes a terminal window pop ups when I open Typora (v0.9.29) on Linux.
I noticed that in other linux desktop files there's a line `Terminal=false` that missing from Typora's desktop file. This option describes whether the application should run in a terminal.
Adding this line to the desktop file solved my problem.

**Comment by abnerlee** [comment]
I will close this since it cannot be reproduced in latest version.

Please reopen this if it still happens
