### ISSUE TITLE
Installation method for linux is often not working

### ISSUE THREAD

**Issue by hunyadix** [typora/typora-issues#763]
Hey there,

I get the following error when trying to install typora:
```bash
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Kali/kali-rolling
```
Please provide a method for manually building the package.

Cheers,
Adam Hunyadi

**Comment by abnerlee** [comment]
@hunyadix could you also post your OS version, and the command you use to install typora?

**Comment by hunyadix** [comment]
OS: `4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux`
Command that fails: `add-apt-repository 'deb https://typora.io ./linux/'`

Right now I managed to manually add the repo to my `/etc/apt/sources.list`, but it says that the .deb package is missing from the database. Also, after searching on google I found some direct links provided to the .deb download page, but all of them were also telling me that the package is missing. 

I found an AppImage on "OMG! Ubuntu!" which was working.

**Comment by abnerlee** [comment]
> Command that fails: add-apt-repository 'deb https://typora.io ./linux/'

What is its error message, if it is a warning not error, you could continue the installation, actually.

**Comment by abnerlee** [comment]
ref https://github.com/typora/typora-issues/issues/706

**Comment by abnerlee** [comment]
same with https://github.com/typora/typora-issues/issues/706

**Comment by probonopd** [comment]
> I found an AppImage on "OMG! Ubuntu!" which was working.

That was probably an old test AppImage that I had made at some point.

Providing __an official Typora [AppImage](http://appimage.org/)__ would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.
