### ISSUE TITLE
can't copy a table

### ISSUE THREAD

**Issue by Nablyy** [typora/typora-issues#764]
i want to copy a table
![default](https://user-images.githubusercontent.com/15205778/27898870-d5fc0ad4-6262-11e7-93bc-8dcd01a33d82.png)
but it does not work
if i select just 'copy' button, there copy only data in a table
how can i copy a table?

**Comment by akYoung** [comment]
I also find the problem. Then, I select the whole table,  select from the `edit` tab and choose `copy as markdown`, and it works~

**Comment by abnerlee** [comment]
should be fixed in the newest version
