### ISSUE TITLE
Change Clear Menu to Clear Recent Item/files in Open recents

### ISSUE THREAD

**Issue by Sibiraj-S** [typora/typora-issues#765]
In the open recent option. Change the name  from `Clear Menu` to `Clear Recent Items/Files` or `Clear Recents` or something what that action is specified for

**Comment by Sibiraj-S** [comment]
closing as unresponsive

**Comment by abnerlee** [comment]
I checked Typora on Windows, it is already `Clear Items` instead of `Clear Menu`

**Comment by Sibiraj-S** [comment]
I use Mac.

**Comment by abnerlee** [comment]
I checked on macOS, It seems `Clear Menu` is the default term on macOS defined by the OS, you could refer `TextEditor.app`, `Pages.app` or other apps, so changing label is not needed

**Comment by Sibiraj-S** [comment]
Cool then.
