### ISSUE TITLE
newline find/replace

### ISSUE THREAD

**Issue by evogel99** [typora/typora-issues#766]
Is there a way to include a newline in a find/replace?

**Comment by stbischoff** [comment]
That would be important for me, too. :)

**Comment by abnerlee** [comment]
line break will become invisible after rendered as HTML in most cases, such as
```
a

b
```
will become `<p>a</p><p>b</p>`, and it is hard to highlight the margin space between two `<p>`, so we are not supporting this.

Relates #2256
