### ISSUE TITLE
Roman Numeral Lists

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#767]
A feature that would be nice to have would be the option to make lists from Roman Numerals (such as articles in a legal paper, or sections in a large study):

I. Purpose
II. Scope
III. Policy
IV. Definition
V. Procedure

etc. I feel it would be a useful addition at the least.

**Comment by abnerlee** [comment]
similar to https://github.com/typora/typora-issues/issues/755

move discussions there
