### ISSUE TITLE
Will typora support export mindmap?

### ISSUE THREAD

**Issue by iromise** [typora/typora-issues#768]
just like the https://github.com/pzhaonet/mindr.

**Comment by abnerlee** [comment]
No, seems it can be supported by external tool.

**Comment by iromise** [comment]
Ok, thanks a lot.

**Comment by tomer-ben-david** [comment]
@abnerlee @iromise so in typora i will not be able to write markdown for mindmap and see the mindmap plot? (as i do today with mermaid to generate other plots)
