### ISSUE TITLE
Exporting issue

### ISSUE THREAD

**Issue by jeffguorg** [typora/typora-issues#769]
- Platform: Win 10 Insider 16215 x64
- Version: 0.9.29(beta)
- Issue: Exporting to pdf after modifying a file and you get file exported from old unsaved edit.
- To reproduct the issue:
    1. Create a markdown document, like ```blablabla```
    1. Save it and exit
    1. Open it again & modify it to well, for example, ```dadada```
    1. Export to pdf
    1. you get ```blablabla```

**Comment by abnerlee** [comment]
should be fixed in the newest version
