### ISSUE TITLE
Font went wrong in the "Open file" panel

### ISSUE THREAD

**Issue by hunyadix** [typora/typora-issues#774]
After upgrading my linux apt-packages, the font just somehow changed to one my system cannot display.

![screenshot from 2017-07-10 08-48-53](https://user-images.githubusercontent.com/8447503/28005781-bde764d8-654c-11e7-9fde-7d6b835dc8f4.png)

**Comment by abnerlee** [comment]
What's your linux distribution?

> After upgrading my linux apt-packages

you mean upgrade Typora or other packages? Can other app, like Chrome display the font correctly?
