### ISSUE TITLE
"Enter" makes screen jump so current line as at bottom.

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#776]
When I type, I like to have my words in approximately the middle of my screen, so I don't spend all my time looking at the bottom of the screen. To achieve this, I have multiple `Enter`s (or newline) to keep my content at optimal level. However one bug I've noticed is that often when adding a new line, using a table, or working with Mathjax, the screen will "jump", so it places my current line of work at the bottom of the screen.

I don't know what's causing it, but it's pretty annoying.

**Comment by AlexPasternak** [comment]
Yet another reason why we should be able to scroll past the end of the document, like many popular text editors allow you to do (TextMate). Then we wouldn't need the hack of manual Enters at the bottom, which is exactly what I do as well.

**Comment by abnerlee** [comment]
@lloyd094 Have you try typewriter mode, and what's your OS?

**Comment by lloyd094** [comment]
I have used typewriter mode before - my OS is Windows 10, latest stable.

**Comment by abnerlee** [comment]
> However one bug I've noticed is that often when adding a new line, using a table, or working with Mathjax, the screen will "jump", so it places my current line of work at the bottom of the screen.

I cannot reproduce this on my Win10. Press return, if your current line is in the middle, the screen will not "jump".

@lloyd094 So could you check if it still exists on v0.9.36?

**Comment by lloyd094** [comment]
It appears something fixed it, or I wasn't able to replicate it. Seems like something in one of the updates has fixed it - thanks for whatever did that!
