### ISSUE TITLE
equations and vertical space

### ISSUE THREAD

**Issue by chipbrock** [typora/typora-issues#779]
hi
Enjoying Typora. But there seems to be an inconsistency in how equation blocks are handled vertically. 

If I type 

blah blah blah
[space once or even twice - which appears on the screen as vertical whitespace]
$$
F=ma
$$
[space - which appears on the screen as vertical whitespace]
blah blah blah

The actual code sometimes - not always?? - is ( as viewed in command=/ or in an external editor)

blah blah blah
$$
F=ma
$$
blah blah blah

and it then renders as in-line. This is quite confusing since the display appears to show whitespace but it's not really there.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1107 since it is more detailed
