### ISSUE TITLE
Image can't load in windows

### ISSUE THREAD

**Issue by plusIs** [typora/typora-issues#782]
when the markdown file path include space, such as "C:\Users\plusl\code\oj\vjudge\contest\UESTC 2017 Summer Training #10 Div.2\C", local image can't load
![image](https://user-images.githubusercontent.com/23459592/28331797-132333d0-6c25-11e7-9b05-d9386a43933b.png)
I'm sure i have this picture in this path.
![image](https://user-images.githubusercontent.com/23459592/28331841-42a10542-6c25-11e7-9c42-b524dcffdf75.png)

**Comment by abnerlee** [comment]
Should be fixed in new release.
