### ISSUE TITLE
Double-click word selection doesn't extend to other words

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#783]
Standard macOS behavior (TextEdit, TextMate) is to allow the mouse to extend selection using whole words, once the first word is selected using double-click. Typora does this _sometimes_, but usually if you move your mouse slowly, it only highlights parts of other words, not entire words as expected.

Please see repro GIF as an example. Top is TextMate: once 1st word is double-clicked, highlight easily extends. Bottom is Typora: although 1st word is selected with double-click, highlight continues to work as normal, character by character.

![2017-07-19 21 14 26](https://user-images.githubusercontent.com/1819485/28396176-b9903036-6cc7-11e7-82ea-25b8d3dc5130.gif)

**Comment by benutzerfreund** [comment]
+1

**Comment by abnerlee** [comment]
should be fixed in the newest version
