### ISSUE TITLE
Win10 Typora Table Code Fences no grid and border

### ISSUE THREAD

**Issue by Shaun2016** [typora/typora-issues#784]
I use typora in Win8 very well, but i upgrade to Win10, it doesn't work in table, code fences and '>' + 'enter'  
no gray limit show...but resource code i can see that 
![image](https://user-images.githubusercontent.com/17938959/28449758-18c8036e-6e15-11e7-95e2-dbdd6081ee42.png)

**Comment by abnerlee** [comment]
Seems css files are not loaded, maybe they are moved or deleted during the upgrade process, could you try uninstall and reinstall Typora?

**Comment by Shaun2016** [comment]
Thx for your advice, i install again and it still that. I have to think it's somrthing wrong in my computer

**Comment by abnerlee** [comment]
@Shaun2016 then please try click "Open Theme Folder" in preference panel, and just remove the "theme" folder, or its parent "typora" folder, then start Typora again.

**Comment by Shaun2016** [comment]
Nice! Nice! You're so awesome.Thank you very much, it does work! Love u...I'm so happy
Best wishes to u
