### ISSUE TITLE
Does not support Asciimath

### ISSUE THREAD

**Issue by ThomasAuriel** [typora/typora-issues#786]
Hi,

Typora should support [AsciiMath syntax](http://asciimath.org/).
To make difference between Latex and AsciiMath, two different tags should be used.

**Comment by mlopezgva** [comment]
If you are unsure about the benefits, please feel free to cehck out a request I made before: https://github.com/classeur/classeur/issues/195

**Comment by abnerlee** [comment]
#2448

**Comment by elahn** [comment]
AsciiMath support would be great. Since Typora already uses MathJax to render LaTeX, all we'd need is a config option to use AsciiMath instead of LaTeX.

Would the team be open to such a PR?

**Comment by Matows** [comment]
Hello!
I'm a student and I'm interested to know : is Typora still considering using AsciiMath?

**Comment by abnerlee** [comment]
Not in near future, we will hanler other requirements first

**Comment by peetteerr** [comment]
IMO, there is not need for develop such feature to fullfill the request for typing math easily. Hotstring in **autohotkey** is able to perfectly handle this. And it is not hard to learn it in Autohotkey since AsciiMath's feature is nothing but some sneppet.

**Comment by Tajnymag** [comment]
@peetteerr Not everyone is on Windows

**Comment by haakonstorm** [comment]
Any way to track the status of AsciiMath support? 
I'll switch to Typora (I'm on macOS) once that is native.
