### ISSUE TITLE
Weird cursor behavior while typing Korean

### ISSUE THREAD

**Issue by hssuh96** [typora/typora-issues#788]
![screen_recording_2017-07-22_at_10_37_pm](https://user-images.githubusercontent.com/18643499/28491679-6b04af94-6f30-11e7-81a7-a335a91cfc7f.gif)

cursor jumps back randomly when typing Korean.
I'm using Typora Version 0.9.9.9.4.2 on macOS Sierra Version 10.12.6

**Comment by abnerlee** [comment]
Are you using the native Koren IME on macOS?

**Comment by hssuh96** [comment]
I'm not sure if this is what you're saying, but here is some information.
<img width="687" alt="screenshot 2017-07-26 23 11 07" src="https://user-images.githubusercontent.com/18643499/28625601-c2ce557a-7257-11e7-8320-efc93a2d1848.png">

**Comment by hssuh96** [comment]
And it seems like happening only when typing headers after they got bigger.
![screen recording 2017-07-26 at 11 19 pm](https://user-images.githubusercontent.com/18643499/28626487-10d6d5ec-725a-11e7-8972-88db29657249.gif)

No problems for any other situations.
![screen recording 2017-07-26 at 11 18 pm](https://user-images.githubusercontent.com/18643499/28626484-0ee81372-725a-11e7-888d-4efed12bb9d8.gif)

**Comment by abnerlee** [comment]
Hi, I tried on mac, but I still cannot reproduce this.

It seems it happens after you input the char similar to "o" in Korean, would you confirm if that is the cause? 
And since I don't know how to input Korean, could you also tell me which keys to type in order to reproduce this bug?

**Comment by hssuh96** [comment]
I can't find exact steps to reproduce this bug... It's not happening now. Maybe I can give you more information when I find this bug again.

**Comment by abnerlee** [comment]
Does this bug still exists in newest version ?

**Comment by hssuh96** [comment]
No, It seems to be working fine now! Thanks :)
