### ISSUE TITLE
Inline Math dosn't work in flowchar 

### ISSUE THREAD

**Issue by youchilove** [typora/typora-issues#789]
for example:

```
```flow
st=>start: start
f1=>operation: calculate diffence
f2=>operation: $a_0{\times}e_i$
f3=>operation: $a_1{\times}e_{i - 1}$
f4=>operation: $a_2{\times}e_{i - 2}$
f5=>operation: $a_2e_{i - 2} - a_1e_{i - 1}$
st->f1->f2->f3->f4->f5
```

it wiil display as blow
![default](https://user-images.githubusercontent.com/30432229/28563927-195b4fbe-715a-11e7-9710-dd58dd11f62f.PNG)

**Comment by abnerlee** [comment]
I will close this since flowchart is one markdown extension, inside it only plain text is supported. 

It will be low priority to support inline formats inside diagrams.
