### ISSUE TITLE
Cursor moves wrong at the EOF when pressing up

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#79]
Copy paste this to Typora (all versions(?), OSX):

> This is a test chapter. Please resize your screen so it spans to two or more lines. Then, when the cursor it at the end of the file (there's a new line created when you scroll it all the way down) and you press up, it moves to the beginning of this chapter, not to the previous line.

**Comment by abnerlee** [comment]
Should be fixed. Tested on macOS
