### ISSUE TITLE
How to turn on the sub-pixel anti-aliasing?

### ISSUE THREAD

**Issue by wdhwg001** [typora/typora-issues#790]
![snipaste_20170725_184159](https://user-images.githubusercontent.com/8943519/28568693-4070ab44-7169-11e7-840f-fa379f588e85.png)

OS: Windows 10 Creator Update 64 bit
Version: latest (0.9.29 beta)
Theme: GitHub
No MacType or similar software installed.
Windows ClearType is enabled.

Changing `directWrite` from `true` to `false` doesn't help.

Adding `-webkit-font-smoothing: subpixel-antialiased !important;` to CSS `body{}` doesn't help.

Any ideas?

**Comment by abnerlee** [comment]
```
-webkit-font-smoothing: subpixel-antialiased !important;
```

I think this is the way to set subpixel-antialiased. 
But please not that `-webkit-font-smoothing` is not standard, and `subpixel-antialiased` is already the default font smoothing mode that is used.

**Comment by wdhwg001** [comment]
@abnerlee But it doesn't work.

FYI, please look closely to the screenshot above, scale to 400% with Photoshop or other software.
You may find some red and blue edges around the title, it's ClearType.
But the content is only rendered in grayscale, it may look fine on Retina display with sans-serif fonts, but could be really blurry on non-retina display with serif fonts.

![snipaste_20170726_211608](https://user-images.githubusercontent.com/8943519/28622609-bdfb1868-7247-11e7-8fda-6437951557e5.png)

Maybe refer to electron/electron#6344

If you can reproduce this issue, could you please re-open it before it being actually fixed?

**Comment by abnerlee** [comment]
@wdhwg001 If you export the content to HTML, open it with Chrome, and then set `-webkit-font-smoothing` in DevTools, could it work?

**Comment by wdhwg001** [comment]
No it couldn't. And the DevTools is not subpixel anti-aliased either.

Maybe it's an electron's version or configuration issue?

![snipaste_20170726_214115](https://user-images.githubusercontent.com/8943519/28624376-8aa74398-724b-11e7-8fe9-fc702c053551.png)

**Comment by wdhwg001** [comment]
Sorry for the misunderstanding.

It works with and without `-webkit-font-smoothing`.

![snipaste_20170726_223306](https://user-images.githubusercontent.com/8943519/28626857-bd90906e-7252-11e7-9e02-cf3f2061401e.png)

And the Typora built-in DevTool and the footer is grayscaled, maybe some issues in Electon's version or configurations?

![snipaste_20170726_214115](https://user-images.githubusercontent.com/8943519/28626932-edfb29a8-7252-11e7-9801-d330531830fa.png)

**Comment by wdhwg001** [comment]
Any updates?

This issue is still in the latest Typora (0.9.31).

**Comment by wdhwg001** [comment]
Text is still grayscale anti-aliased in Typora 0.9.32.

**Comment by wdhwg001** [comment]
Still not fixed in Typora 0.9.35

**Comment by abnerlee** [comment]
Does this work in v0.9.41?
