### ISSUE TITLE
Some keys doesn't work while using chinese typewriting to write list

### ISSUE THREAD

**Issue by SimpleFate** [typora/typora-issues#793]
![Uploading typora_issue.gif…]()

When I wrote the second list item and press ```space``` , the label of list was disappeared.
And then , when the label appeared , ```space``` and ```enter``` didn't work.

macOS Sierra 10.12.5
typora  V0.9.9.9.4.2

**Comment by SimpleFate** [comment]
GIF:![Markdown](http://i4.eiimg.com/1949/fd177b50200efc4d.gif)

**Comment by abnerlee** [comment]
Which IME did you use? Can you reproduce this by the native IME provided by macOS?

**Comment by SimpleFate** [comment]
It is the native IME , I didn't install any other IMEs.

**Comment by abnerlee** [comment]
IME only bug on list should have been fixed. I find a reminding bug, should be same with https://github.com/typora/typora-issues/issues/1012
