### ISSUE TITLE
Default CRLF on Windows

### ISSUE THREAD

**Issue by JVimes** [typora/typora-issues#794]
Typora uses LF as line ending, even on Windows. On Windows, it should default to CRLF.

**Comment by abnerlee** [comment]
This can be set via `Preference Panel`. And I think it depends on each person which one should be default.

**Comment by JVimes** [comment]
No, it's an OS convention. Markdown should look good in a plain text editor, and with the wrong carriage return it's unreadable.

**CRLF should be default on Windows OS**.

Please re-open this issue, even though you don't use Windows.

**Comment by AlexPasternak** [comment]
At the very least, how about making the default preference OS-specific and correct? I agree that LF only is very non-standard for Windows, and not something those users should have to change "out of the box".

**Comment by abnerlee** [comment]
Yeah, follow OS standard as default option makes sense

**Comment by AlexPasternak** [comment]
Btw, maybe I'm just blind, but I cannot find this option in Preferences, either on macOS or Windows. Can you please point me to it? I even checked Advanced options on Windows via JSON file, and don't see anything about line endings anywhere.

**Comment by JVimes** [comment]
Thanks, @abnerlee! 😄 
@AlexPasternak It's easy to overlook ;) Here's where I found it in v0.9.29:
![image](https://user-images.githubusercontent.com/6148201/28930389-0cc91efc-7830-11e7-9be5-a444a0e80734.png)

**Comment by abnerlee** [comment]
@AlexPasternak we do not provide such option on mac version. In Linux/Windows version it can be found in preference panel

**Comment by abnerlee** [comment]
Fixed in new release.

Will use CRLF on windows for new users by defauly.
