### ISSUE TITLE
shortcut key like ctrl+/ does not work in Ubuntu

### ISSUE THREAD

**Issue by drawwon** [typora/typora-issues#796]
I'm using Typora in Ubuntu16.04, When I input `ctrl+/` to launch source code mode，it changes to select all  the words，does it because my typora has some problems or all the typora in ubuntu has this bug？

**Comment by abnerlee** [comment]
Would you use `ctrl+/` to select all words in other apps like Chrome, in your system?

**Comment by drawwon** [comment]
@abnerlee yes, `ctrl+/` in all aplicaiton is" select all" , how can I solve this problem? thanks

**Comment by abnerlee** [comment]
@drawwon Seems caused by the key binding of Ubuntu system, please check this -> https://askubuntu.com/questions/324862/ctrla-does-not-select-all-in-url-bar-in-chrome-and-firefox

Or change key binding in Typora -> http://support.typora.io/Custom-Key-Binding/

**Comment by heefan** [comment]
I have the exact same problem. 
I changed default key binding as mentioned by @abnerlee.
Thanks @abnerlee, this is the best markdown editor I've ever seen these years.

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/837

Seems shortcut key for text editing (select all, bold, etc) will be captured by Ubuntu before it does to menu

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/837

**Comment by abnerlee** [comment]
Please refer to the last paragraph in http://support.typora.io/Custom-Key-Binding/
