### ISSUE TITLE
[feature] Cycle Through Windows

### ISSUE THREAD

**Issue by die4live** [typora/typora-issues#8]
In many other software, there's an option to cycle through opened windows under the same software (and usually with a shortcut of Command + ` ). Looking forward to have this feature in Typora too. Thanks!

**Comment by abnerlee** [comment]
If Command+` bot work, then it's a bug

**Comment by die4live** [comment]
![screen shot 2015-09-17 at 10 25 06](https://cloud.githubusercontent.com/assets/1461437/9923762/5a5fed7a-5d2b-11e5-933f-7cbab6393124.png)


but I don't even see a menu option for this feature

**Comment by abnerlee** [comment]
@die4live I tried "command+`" and I can switch different windows by that shortcut key, so it seems working.

For the menu option, I tried Text.app and other app, they also does not have such item in their menu, so I think it is not a standard menu item

**Comment by die4live** [comment]
@abnerlee After tried Typora and some other apps, there do have a function to cycle between windows, although only for **open** files, which is a little different with what I thought. Anyway, it's a mistake and sorry for opening this issue without testing thoroughly.
