### ISSUE TITLE
can open any file, stuck at the starting page 

### ISSUE THREAD

**Issue by lj8385174** [typora/typora-issues#800]
This app jsut stuck at the starting page.
This problem still exists after reinstall typora.
system windows 10 1703 64bit.
typora version: 0.99(?, the latest version)

![bug](https://user-images.githubusercontent.com/3823826/29054835-2262d6b4-7c2b-11e7-97ff-059c322b9ed2.PNG)

**Comment by abnerlee** [comment]
There's new version, and I cannot reproduce this bug. 

Please reopen it it it still happens
