### ISSUE TITLE
source mode // syntax coloration issue / colors

### ISSUE THREAD

**Issue by malikbenkirane** [typora/typora-issues#801]
Hi !

It's clear there is something wrong in syntax coloration engine,

- [minimal example](https://gist.github.com/malikbenkirane/587450b0fc846bcedbfa46be1d08df4f)
- [screenshot](https://user-images.githubusercontent.com/150165/29118924-5eee25b4-7d04-11e7-879a-e77c4bfb198b.png) of the window source mode

Good luck with that !

Sincerly,

Typora Version 0.9.9.9.4.2 (0.9.9.9.4.2)
macOS Sierra 10.12.6

**Comment by abnerlee** [comment]
relates to https://github.com/typora/typora-issues/issues/314
