### ISSUE TITLE
Custom template for docx export

### ISSUE THREAD

**Issue by stlorenz** [typora/typora-issues#802]
Hi, 

we have recently switched to Typora for writing our documents in markdown. 
Since we create documents for quality management systems, every customer has its own dotx with the custom header,footer and company related information. 

Can Typora or pandoc configured to use a special dotx-Template for docx-export? 

Edit: I researched a bit more about pandocs support for custom docx support.
From my point of view it would need a call of pandoc like

`pandoc --reference-docx=reference.docx myfile.txt -o myfile.docx`

That would atleast add all styles to the ouputted document.

We are aware that a custom pdf template and a custom call of pandoc with such a template would create nice PDF documents buts not thats what we want since we rely on the comments and changes features of Word in the workflow.

**Comment by fkstef** [comment]
+1
I would also appreciate the ability to set a custom Word template as the default table format does not produce a reader friendly layout for my documents. Also I cannot rely on a manual call to pandoc with options as my markdown documents include mermaid graphs, so I need to rely on the full typora workflow from .md to .docx

**Comment by abnerlee** [comment]
I will merge this request to https://github.com/typora/typora-issues/issues/823

**Comment by sheldonhull** [comment]
@fkstef You can specify mermaid filter in your pandoc call in the meantime. I don't see this as a an option that was added yet, so maybe this will help you. I used the following command switch `--filter=mermaid-filter.cmd` in windows after running `npm install --global mermaid-filter` from the other github project: [Mermaid-Filter](https://github.com/raghur/mermaid-filter)
