### ISSUE TITLE
Support for mermaid class diagram

### ISSUE THREAD

**Issue by strgrb** [typora/typora-issues#803]
mermaid release 7.0.0 has support for class diagram, though the mermaid doc has not been updated yet. 
I tried it with mermaid command line, using class diagram example in the mermaid README and it works.

**Comment by abnerlee** [comment]
> classDiagram and gitGraph are unstable and buggy, there is not documentation for them yet. For now I don't recommend anybody using mermaid to generate these two types of diagrams.

from https://github.com/knsv/mermaid/issues/359

We still need documents to "officially" support it.
