### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by sunzhenyucn** [typora/typora-issues#805]
Windows Version cannot download.
https://typora.io/windows/typora-setup-x64.exe?
Not Found.
Fix it please

**Comment by MarcoNiemann** [comment]
+1

Download on webpage delivers the error described above. Also the update utility fails claiming that the download server could not be reached!

**Comment by decadence** [comment]
Same issue for me
@abnerlee

**Comment by hanzin** [comment]
I got same issue (cannot dowload, 64 bit windows)

**Comment by yujincheng08** [comment]
Same issue

**Comment by yujincheng08** [comment]
Now fixed because a newer version released.
