### ISSUE TITLE
[⌥ Opt] + [← Backspace] shortcut not working anymore

### ISSUE THREAD

**Issue by curiousigor** [typora/typora-issues#806]
I've just updated the app to Version 0.9.9.10 (0.9.9.10) and discovered that the [⌥ Opt] + [← Backspace] shortcut is not working anymore (was working in the previous release). 

I think the issue is with the shortcut pointing to Edit>Delete Range>Delete Word ⇧⌘D that seems like it operates the same function. This wouldn't be a problem if changing the shortcut was possible, but since ⌥← is reserved by the system, it cannot be set to other commands.

In my opinion, the shortcut should be left as is defined by the system, as it works the same way in every single other app that has some text editing functionality.

I've also noticed that the Redo shortcut has also been set from ⇧⌘Z to ⌘Y, which is also contradictory to how Redo works on macOS by default. Luckily this can be changed, but I think a lot of users will think something is broken 🤔

macOS Sierra 10.12.5 (16F73)
Typora Version 0.9.9.10 (0.9.9.10)

Cheers, Igor

**Comment by akamyself** [comment]
Agreed, use this key combo all the time when I mistype a word, noticed it within seconds after updating.

Never a good idea to mess up global shortcuts, using them without thinking about it.

Hope it will be fixed asap

**Comment by abnerlee** [comment]
I pushed a new release. Should be fixed now

**Comment by curiousigor** [comment]
That was fast @abnerlee!
Thanks for the hard work 👊
