### ISSUE TITLE
Mermaid rendering issue

### ISSUE THREAD

**Issue by jeffguorg** [typora/typora-issues#807]
cannot render subgraph in mermaid graph

version: 0.9.29
win 10 16251 zh-cn

![image](https://user-images.githubusercontent.com/7763702/29165479-62c038d4-7df5-11e7-8ebf-388dedefc08f.png)

**Comment by abnerlee** [comment]
Fixed in new version

**Comment by iloginov** [comment]
I see this issue in version 0.9.36
![subgraph-issue](https://user-images.githubusercontent.com/5550341/30589497-5ecc7194-9d43-11e7-8057-96fc0ff3cef0.jpg)

**Comment by abnerlee** [comment]
@iloginov Thanks for the report, 
and could you post the text directly? That will make things easier for us to test.

**Comment by iloginov** [comment]
Playing with examples on Mermaid official site I found the proble.

If I create diagram and make intendation using TAB instead of spaces, nothing works. But this is related only to subgraphs.

You can get oficial example:
```
graph TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
```
and change spaces on TAB in line 4.

**Comment by abnerlee** [comment]
Seems to be a mermaid bug -> https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKICAgIGMxLS0-YTIKICAgIHN1YmdyYXBoIG9uZQogICAgYTEtLT5hMgoJZW5kCiAgICBzdWJncmFwaCB0d28KICAgIGIxLS0-YjIKICAgIGVuZAogICAgc3ViZ3JhcGggdGhyZWUKICAgIGMxLS0-YzIKICAgIGVuZA

**Comment by iloginov** [comment]
You are right. There is issue: https://github.com/knsv/mermaid/issues/336.

Seems this issue should be closed.
