### ISSUE TITLE
Regression in LaTeX rendering

### ISSUE THREAD

**Issue by wyf88** [typora/typora-issues#81]
In the new version of Typora, the LaTeX rendering quality seems to be improved. However, I find some bugs that did not exist in older versions. For example, the `\boldsymbol` command, which is for typing bold Greek letters, does not work anymore. Another one is the `\choose` command. If I type `${a \choose b}$` or `$\binom {a} {b}$`, it is broken:
<img width="309" alt="2016-03-07 20 15 59" src="https://cloud.githubusercontent.com/assets/361747/13569438/0fd8a6c0-e4a3-11e5-882b-08a4dbbf814c.png">

I did a little research and found that both command are defined in the `amsbsy` package. So I suspect it is because the `amsbsy` package, which should be loaded by the `amsmath` package automatically, is not loaded properly. Both of the above packages are quite necessary in almost every LaTeX document with math. So I would appreciate if you can take a look at this issue. 

And I'm thinking about another thing: is it possible for the user of Typora to customize the LaTeX packages they need for a document? I guess many of us have some favorite packages that can't live without (for example, I find the `bm` package to be very useful for typing bold maths). But since I'm not familiar with the implement of MathJax in Typora, I'm not sure whether that is possible at all. But I'm pretty sure it is a very nice feature to have.

**Comment by MrJasper** [comment]
LaTeX rendering quality needs to be improved more:

![mathjax](https://cloud.githubusercontent.com/assets/15362491/13570056/f355cb14-e4a6-11e5-923d-f3854b747e53.PNG)
The picture shows a comparison between Typora's rendering and native webpage rendering of mathjax.

The latex package support of mathjax can be found there:<http://docs.mathjax.org/en/latest/tex.html>
But I'm not familiar with mathjax too.Another solution of latex rendering in webpage/markdown is [KaTeX](https://github.com/Khan/KaTeX), which seems to be faster than mathjax.

**Comment by abnerlee** [comment]
The extensions for MathJax has been fixed, quality improvement has been moved to issue: https://github.com/typora/typora-issues/issues/92
