### ISSUE TITLE
Feature request: allow resizing sidebar

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#812]
The new file-browsing, notes-preview mode sidebar is *awesome*...  which is why I'd like to be able to make it wider, so I can see more text, or longer filenames.  (if it just got wider when the window was wider than the maximum text width, that would be sufficient for me.)

Being able to browse through files with the arrow keys (instead of clicking on them) would also be nice, as would keyboard shortcuts for changing the mode and switching between views.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/116
