### ISSUE TITLE
Menu on Windows not accessible via keyboard

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#813]
As of a recent update, holding down the Alt key will underline letters on the pulldown menus, but will not actually engage them.  E.g. Alt+F should open the file menu, but does not.  Neither does tapping Alt and then tapping F.  Both approaches should work in a normal Windows program.

**Comment by abnerlee** [comment]
I can open the File menu via Alt+F in my PC.

Did you use US-English keyboard or any IME? or, will Alt+F insert some special character (liek ƒ) in your environment?

**Comment by pjeby** [comment]
US English, Windows 7 64-bit.  It does not insert a character; it just doesn't do anything.

**Comment by abnerlee** [comment]
Please update to v0.9.41, and reopen this if it still exists. In my PC, it is working
