### ISSUE TITLE
Linux deb repository asking for kernel update

### ISSUE THREAD

**Issue by guillaumecabanel** [typora/typora-issues#815]
I use a package manager on linux to keep Typora updated but the deb repository `https://typora.io ./linux/` ask me for linux kernel update. I think this is not the role of this repository to show that kind of update.

**Comment by abnerlee** [comment]
Could you post the console output or any description text when the deb is asking you for kernel update?

The deb should have nothing to do the the kernel

**Comment by guillaumecabanel** [comment]
was a bug from my manager update, mea culpa :)
