### ISSUE TITLE
Support for it-container / alerts

### ISSUE THREAD

**Issue by capravictoriae** [typora/typora-issues#816]
![screenshot from 2017-08-11 10-33-59](https://user-images.githubusercontent.com/9625282/29206089-b3e860e8-7e80-11e7-944f-31ec2c655554.png)

Having it with this kind of syntax would be awesome:

```
Alert Area
---
:::success
Yes :tada:
:::

:::info
This is a message :mega:
:::

:::warning
Watch out :zap:
:::

:::danger
Oh No! :fire:
:::
```

The plugin to use could be this one:

[https://github.com/markdown-it/markdown-it-container](https://github.com/markdown-it/markdown-it-container)

**Comment by abnerlee** [comment]
This seems too far way from most markdown engines. 
We want keep markdown in typora simple, no extra learning costs if one already knows how to write markdown.
So, we are less likely to add syntax support for this

**Comment by capravictoriae** [comment]
I see your point, and I agree on keeping it simple.
But I still think that this could be implemented with something like:
```
```alert-danger
Some important note
```close-alert-danger // this would be just ```
```

The same way as [mermaid, sequences and flow](http://support.typora.io/Draw-Diagrams-With-Markdown/) are implemented. It doesn't get in you way when writting markdown, but it is there as another "code block" that renders as a colored box. I think it's a nice addon for documenting, highlighting something or putting a note, and it's found on other similar tools.

Thanks for answering!

**Comment by abnerlee** [comment]
may relates https://github.com/typora/typora-issues/issues/162

**Comment by abnerlee** [comment]
part of #2441 ?

merge into #2448

**Comment by EzequielBruni** [comment]
I'd like  to lend my voice to the choir. Perhaps you could support the kind of warning/alert/info boxes seen here in VSCode's Markdown Preview Enhanced plugin (and supported by a few docs website generators):

![alerts-markdown](https://user-images.githubusercontent.com/1215780/153313026-cd226375-86ad-4a9a-a8b5-f76a1a2c1075.png)

Syntax:

```markdown
!!! Note
    [Your text here]
```

**Comment by Sieboldianus** [comment]
It seems as if Typora currently supports `[!NOTE]` etc. - however, since we are collaborating with different tools on Markdown, it would be nice to see other mappings, too. E.g. `:::success` from CodiMD will not render. I like typora for printing Markdown to PDF and it is quite complex to transpose CodiMD Markdown Admonitions to Typora/GH Admonitions.
