### ISSUE TITLE
PDF export does not respect the "title" setting of the YAML front matter

### ISSUE THREAD

**Issue by fkstef** [typora/typora-issues#817]
I have multiple documents with a "title: xxxxxxx" entry in the YAML front matter.

This is taken into account for my Word exports and properly adds the title at the top of the document. However when doing a PDF export, no title is created in the resulting document.

My workflow outputs both Word and PDF and I did not find a clean way to resolve this inconsistency. Putting the title as a H1 tag is not satisfactory as I also use a TOC.

**Comment by abnerlee** [comment]
Do you mean the title should be added into the exported PDF's meta?

**Comment by fkstef** [comment]
I meant more of adding the title in a H1 tag centered at the top of the first page of the document, like a Word export would do. I am trying to find a clean, markup compatible way to show the title at the top of the doc without affecting my TOC and title: seems to be what I was looking for

**Comment by abnerlee** [comment]
So you mean add a cover in the exported PDF?

**Comment by fkstef** [comment]
Not necessarily a full page, but a title on top of page 1 followed by the rest of the document also on page 1. If you look at a Word export this is how it looks.

**Comment by abnerlee** [comment]
But in my testing, if you set "title" in the info panel of your document, and click print, the "title" will not be added.

You need to write a title in the content, then it will be printed as it looks like, which is same as you write a H1 in typora, and then export with it.

**Comment by abnerlee** [comment]
need more info

**Comment by fkstef** [comment]
So the behaviour of such a code:
```
---
title: This is a title
---
```
with a selection of exports is:
- print to PDF: does not display anything specific on the page
- export to PDF: does not display anything specific on the page
- export to HTML: does not display anything specific on the page
- export to RTF: The title text "This is a title" will be at the top of the first page in the page contents
- export to Word (.docx): The title text "This is a title" will be at the top of the first page in the page contents

So which is the expected / correct behaviour of the title tag? To be honest, the RFT/Word export is the one that suits me best as it is a way to have a title at the top of the document, which does not end up in the TOC otherwise. At least the behaviour ought to be consistent across the exports?

**Comment by fkstef** [comment]
does my previous comment clarify the issue?

**Comment by abnerlee** [comment]
Sorry, I missed out.

```
---
title: This is a title
---
```

The title is meta data, not the content in the file. In HTML, it is 
```html
<html>
<head><title>This is a title</title></head>
<body>
... some content
</body>
</html>
```

In HTML, the meta data (title) will not be displayed in the browser page content, so this is the expected behavior.

RTF, and Word can include this title may relates to Pandoc's spec.
