### ISSUE TITLE
Cannot bold Chinese with double *

### ISSUE THREAD

**Issue by JasonYu1984** [typora/typora-issues#820]
Hi
I'm downloading the latest Typroa (0.9.9.10.1) today on my MAC Book Pro macOS Sierra 10.12.6.

I found that when I'm using double * shortcut to bold a Chinese character, there is nothing happen. I can see the double * disappeared like other shortcut is but the character still normal, not bold.
I'm sure the OS character is default.

Thanks.

**Comment by abnerlee** [comment]
Will use shortcut (cmd+b) work?

**Comment by abnerlee** [comment]
Closing, since no enough information
