### ISSUE TITLE
Convert old-style smileys to emojis

### ISSUE THREAD

**Issue by szepeviktor** [typora/typora-issues#822]
If would be nice to convert `:)` to `:smile:`, `:-D` to `:laughing:​` etc.

**Comment by szepeviktor** [comment]
This may be usable: https://github.com/emojione/emojify.js/blob/master/src/emojify.js#L40-L78

**Comment by abnerlee** [comment]
We don't have plans for this since it can be done via snippets or TextExpander or its alternative

**Comment by szepeviktor** [comment]
@abnerlee Thank you for your answer.

TextExpander is https://textexpander.com/
But what does _via snippets_ mean?

**Comment by AlexPasternak** [comment]
He could mean built-in text expansion in macOS (Text tab in Keyboard syspref) or one of the many 3rd party utilities for this. Alfred has general snippets and Rocket is specifically for emojis:

https://matthewpalmer.net/rocket/

**Comment by seamusdemora** [comment]
And not everyone is enamored of converting "old-style smileys" to an emoticon. I know at least one person who thinks that is a horrid idea. I actually despise apps that do this, and don't let you turn it OFF (e.g. Outlook for Mac).
