### ISSUE TITLE
Support Pandoc Stylesheet and Template commands

### ISSUE THREAD

**Issue by shoesforindustry** [typora/typora-issues#823]
Pandoc support a 'stylesheet' and a 'template' command when converting to export for epub.
You can could perhaps read it from the metadata

```
---
title: My Book Title
author: A.N. Author
cover-image: coverimage.jpg
stylesheet: stylesheet.css
template: template.css
---
```

It would be a great addition!

**Comment by rpolitex** [comment]
:+1:

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/1451
