### ISSUE TITLE
Links to local files with brackets in file name

### ISSUE THREAD

**Issue by bobtheguitar** [typora/typora-issues#825]
Copying a local file and pasting into Typora generates a link, which is good. But if the file name contains brackets, the file path generated tries to escape the closing one, breaking the link. (Manually removing the backslash makes it work.) This is on macOS 10.12.6.

Example:

![screen shot 2017-08-12 at 13 19 06](https://user-images.githubusercontent.com/30782578/29240652-5bc2c2b4-7f61-11e7-89b8-de302a33648e.png)

Also: it would be good if links to local files could be generated by dragging and dropping, as well.

**Comment by abnerlee** [comment]
Either support `/)` or use URI encode when drag file.

I still need to check if `/)` is a way to escape `)` in links for other markdown engines

**Comment by abnerlee** [comment]
merge to https://github.com/typora/typora-issues/issues/1647
