### ISSUE TITLE
Open in new window with tab bar visible

### ISSUE THREAD

**Issue by bobtheguitar** [typora/typora-issues#826]
When the tab bar is visible, right clicking on a file in the sidebar and choosing 'open in new window' in fact closes the current window and opens a new window with all of the tabs from the previous window plus a new tab with the selected file. 'Open in new window' should open the file in a new window by itself, and there should be an 'open in new tab' option that simply adds a tab to the current window for the selected file.

It would also be good to have the option of opening files in new tabs by default (rather than new windows.)

**Comment by abnerlee** [comment]
I would prefer hide tabs if there's only one document open in current Window.

About open in new tabs, we will consider in https://github.com/typora/typora-issues/issues/1000
