### ISSUE TITLE
hangs when paste text or change code block syntax language type

### ISSUE THREAD

**Issue by chgc** [typora/typora-issues#831]
I had a problem when I upgrade to latest version (0.9.32 win-64), which is when I tried to change code highlight language type or paste text, Typora hangs. In task manager windows, it shows 30% of cpu usage.
I don't know what cause it.

**Comment by abnerlee** [comment]
What language are you going to change to ? 

And what is the original content in the code block?

**Comment by chgc** [comment]
```typescrpit
<input [(ngModel)]="username">

<p>Hello {{username}}!</p>
```
I missed type the language type, I want to fix it with `typescript`.

**Comment by nomilous** [comment]
Same problem on OSX 10.11.6 (15G31)
Typora 0.9.9.10.2 (0.9.9.10.2)

Freezing when update code-box content (javascript). Only happens when starting to add a new javascript comment into the box, ie typing a `/` character. Does not happen if code-box has no selected language.

Thanks.

**Comment by nomilous** [comment]
I've tried to find somewhere to download the previous version so that I can revert. No luck. Would be handy for now.

**Comment by nomilous** [comment]
Never mind, found it.

**Comment by chgc** [comment]
Bug fixed when updated to 0.9.33.
