### ISSUE TITLE
jumping all around on save

### ISSUE THREAD

**Issue by chipbrock** [typora/typora-issues#835]
Something is still wrong with 0.9.9.10.3... When I'm in source mode and make a change and save, the window will jump to the bottom of the file and sometimes to the top of the file. 

Also inexplicably it inserts characters that I don't want. In particular, I often - without difficulty until now - insert display math in a blockquote. I learned in Typora to do this:

>blah
>
>$$
E=mc^2
$$
>

notice the careful placement of the > . Now I'm finding that if I do this and even if I save the file immediately, when I go to the rendered version the equation will be wrongly formatted and when I go back to the source it will have transformed to:

>blah
>
>$$
>E=mc^2
$$
>

**Comment by abnerlee** [comment]
may duplicate with https://github.com/typora/typora-issues/issues/865
