### ISSUE TITLE
"Open theme folder" in settings does not work on Linux

### ISSUE THREAD

**Issue by nickcorona** [typora/typora-issues#836]
Pressing the button does nothing. I'm on Arch Linux and installed Typora through the AUR repository, if that's relevant.

**Comment by abnerlee** [comment]
Is there any errors in console (View->Toggle DevTools) after you click that button?

Does buttons like "Recover Unsaved Drafts" work?

**Comment by abnerlee** [comment]
Close since there's no response for us to locate the issue

**Comment by christianrocchetti** [comment]
I use Ubuntu 20.04 and I have the same error 
> Console error:
Failed to load resource: net::ERR_FILE_NOT_FOUND
`/home/nome_utente/snap/typora-alanzanattadev/2/.config/Typora/themes/github.user.css` 
>
Instead of finding the directory, it finds the file

**Comment by christianrocchetti** [comment]
I just found out that I was using an unofficial version downloaded from the Ubuntu Software Center (https://snapcraft.io/typora-alanzanattadev)
