### ISSUE TITLE
Redefine key binding failed 

### ISSUE THREAD

**Issue by RabbitLee** [typora/typora-issues#837]
Thanks for this awesome Markdown Editor !
I use it in Ubuntu 16.04 LTS, and wanna to redefine the shortcut *Strong* (Ctrl + b) to other like (Ctrl + Shift + b) for I am using global emacs key theme (I tried to reset to default key theme and repeat the process below but it made no difference):

I modified the *conf.user.json* file like this:
```javascript
"keyBinding": {
    "Strong": "Ctrl+Shift+B"
}
```

Then I restart Typora, hover above Toorbar, and found *Format -> Strong* has been changed to 'Ctrl + Shift + B' indeed. However when I try to use this shortcut during writing, it's both 'Ctrl + B' and  'Ctrl + Shift + B' that can *Strong* the word.

So is there a way to remove existing key bindings like 'Ctrl + B' ?
Thank you ~

**Comment by abnerlee** [comment]
Please refer to the last paragraph in http://support.typora.io/Custom-Key-Binding/

**Comment by Binly42** [comment]
I encountered similar issue.

- OS: Win10 20H2 
- Typora: 0.10.11
- conf:
```
"keyBinding": {
  "Strong": "Alt + B",
  "Toggle Sidebar": "Ctrl + B"
},
```

After restart, those 2 shortcuts displayed in menu UI is fine.
But, both `Ctrl+B` and `Alt+B` Strong the word.
Meanwhile, nothing happened for the sidebar ...

---

FYI `Ctrl+B` works fine in my VSCode, for toggling sidebar.

**Comment by Binly42** [comment]
> Please refer to the last paragraph in http://support.typora.io/Custom-Key-Binding/

BTW the latest link may be: https://support.typora.io/Shortcut-Keys/#change-shortcut-keys
