### ISSUE TITLE
charset problem when export to PDF

### ISSUE THREAD

**Issue by ittao** [typora/typora-issues#838]
The following command is copy from markdown source file
`ls -a`

The following command is copied from the pdf exported with typora
`ls ‐a`

It is more obvious in this screenshot
[
![notepad](https://user-images.githubusercontent.com/2222326/29314186-83d267c4-81ef-11e7-9b88-43c87c2a9ea7.png)
](url)

convert the blank and hyphen to HEX
![notepad2](https://user-images.githubusercontent.com/2222326/29314331-25ed1982-81f0-11e7-919b-b204b8d294a6.png)

OS: Windows 10  64 bit
Version: latest (0.9.33 beta)

**Comment by abnerlee** [comment]
It's a wired bug, if I write --, it can exported correctly, but `--` won't...

**Comment by abnerlee** [comment]
hot fixed in new version

**Comment by ittao** [comment]
Same problem in new version.
I found this problem only appears in the code fence area with character `-` or `--` .

**Comment by abnerlee** [comment]
@ittao  what's your Typora/OS version?

**Comment by Octen** [comment]
Same problem with version 0.9.37 in Windows 7 Entreprise
Only export to PDF
