### ISSUE TITLE
Support HTML codes inside Markdown like StackEdit does

### ISSUE THREAD

**Issue by gusbemacbe** [typora/typora-issues#839]
Hello,

For example:

```
### <span style="color: #0039a6">Adjectives</span>
#### <i class="icon-file"></i> Create a document
You can save the current document to a file by clicking <i class="icon-hdd"></i> **Export to disk** from the <i class="icon-provider-stackedit"></i> menu panel.
```

**Comment by dessalines** [comment]
This would also help with the `<sup>` tags.

**Comment by gusbemacbe** [comment]
@dessalines, it has already superscript and subscript. Go to Format --> Superscript.

**Comment by dessalines** [comment]
^tags^ aren't official markdown spec. You can see even github doesn't support them.

**Comment by gusbemacbe** [comment]
I understood, and I detest the left text. I prefer the justified text.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/705
