### ISSUE TITLE
GitHub's Open Sans font is missing in HTML export

### ISSUE THREAD

**Issue by szepeviktor** [typora/typora-issues#840]
Could you link Google Fonts in the exported HTML in place of a broken link?

This is in my exported HTML: `url("./github/700.woff")`

**Comment by szepeviktor** [comment]
@abnerlee Could https://github.com/typora/typora-default-themes/commit/e0217a50bc4899a20d9a2ae6275c980924844128#diff-53a9ca6d846678165a14eda99ab4fdeaR6 solve this?

**Comment by abnerlee** [comment]
This should be fixed in recent update. The font css will be appended as `<link>`, the broken link `url("./github/700.woff")` will just be ignored by browser.

**Comment by szepeviktor** [comment]
Thank you.

In v0.9.33 HTML export there is still only `url("./github/400.woff")`, no `<link>` tag.

**Comment by szepeviktor** [comment]
v0.9.34 is out!

**Comment by abnerlee** [comment]
Please check v0.9.36. Should work now.

**Comment by szepeviktor** [comment]
Thank you.

It appeared.
