### ISSUE TITLE
Automatic line breaks in rendered math

### ISSUE THREAD

**Issue by bobtheguitar** [typora/typora-issues#843]
At the moment, long math formulae simply run off the page, unless line breaks are inserted manually (via `\\`.) But the appropriate placement of manual line breaks inevitably depends on the surrounding text (and its formatting) in a way that runs counter to the idea of writing in markdown, it seems to me. So it would be great if Typora could handle automatic line breaks in rendered math.

(Apparently automatic line breaks are off by default in MathJax, but can be turned on (as stated [here](http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking).) If this is the preferred default behaviour, perhaps there could be an option in Typora's preferences to enable them?)

**Comment by abnerlee** [comment]
Typora treats rendered math as SVG/Images, so we would not support text reflow for math.
