### ISSUE TITLE
Auto pair support doesn't work well with auto-bullets

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#844]
The "Auto pair common markdown syntax" option is very helpful, and I don't want to turn it off. (Btw, it seems that the label should say "Markdown", not lowertext, as it's a title)

However, it produces undesired behavior with auto-bullets, where an extra * is left after the bullet is shown. I don't have a good idea for how to do both, but perhaps it could remove the auto-added 2nd * once a space is typed & the first is turned into a bullet?

![2017-08-18 11 04 26](https://user-images.githubusercontent.com/1819485/29464818-1d4b845a-8405-11e7-8cbf-a7dcd17d0307.gif)

**Comment by claytonrcarter** [comment]
Another option would be to disable the "auto pair" of the `*` when it's the first character typed on a new line.

**Comment by vassudanagunta** [comment]
@claytonrcarter Since Markdown *does* support italics and bold at the start of a line, but *does not* support italics and bold on text with leading or trailing spaces, @AlexPasternak approach is the correct approach. 

I would say that in all cases, start of line or bullet or not, the second asterisk should be removed if the first asterisk is followed by a space. If that is too hard to implement, the other option is to not insert the second asterisk until *after* the a non-space character is typed following the first asterisk.

**Comment by claytonrcarter** [comment]
Hmm, I see your point, but I feel like we're dancing with the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) on this:
> The design should match the user's experience, expectations, and mental models.

When I type a `*`, I expect to get a `*`. Adding the second `*` is a pleasant surprise in most cases, but an inconvenience in this case. If I type a space, I expect to insert a space, I *do not* expect it to delete the next character. If I type a character, I expect to insert that character, *not* to insert extra characters. Also, if I type a space after an asterisk, I would find it counter-intuitive for the app to hunt down the matching asterisk somewhere later in the document and delete it.

That said, if disabling auto-pair of `*` at the start of a line isn't agreeable, I could get behind the idea of of removing the second `*` when a space is inserted between them, but only in the case when the line only contains `**` (with or without leading and trailing whitespace). I think that that behavior in other places would be too aggressive.

BTW, as a workaround, I've started using `-` to start my bullets.

**Comment by AlexPasternak** [comment]
Since this issue continues to burn me, I thought I'd revisit the thread to see if there're any updates to fixing this. I missed all the follow-up posts, apologies, as @claytonrcarter suggestion of using - instead for bullets is a good one, but it'll be hard to untrain myself to use anything but * to start an auto-bullet.

@vassudanagunta, thanks for the agreement, I hope this gets implemented still. Sorry to miss your screen-recording question: I use Gifox, included as part of the [Setapp suite](https://setapp.com/).

https://gifox.io/

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by AlexPasternak** [comment]
@abnerlee, it seems there's a regression, where this no longer works in the latest release.

![2018-08-28 08 27 12](https://user-images.githubusercontent.com/1819485/44722812-41c74a80-aa9c-11e8-98c8-464e547f9a14.gif)

Can you please reopen this, or do you want me to create a new issue?

**Comment by abnerlee** [comment]
Should be fixed
