### ISSUE TITLE
Navigating in lists is weird: cursor jumps to start or end of line

### ISSUE THREAD

**Issue by koenaad** [typora/typora-issues#846]
I find navigating lists with the text cursor unintuitive and inconsistent with other editors.
* When you move down, it always jumps to the start of the next line.
* When you move up, it always jumps to the end of the previous line.

Instead I would expect the cursor to stay in the same column when moving up or down. And if a line is shorter, to jump to the end of that line.

Other than that, marvelous app! Really enjoying it.

**Comment by koenaad** [comment]
Oh, I just noticed this happens all the time actually. Every time you change line, the cursor jumps to the start or end of that line.
This does not happen in source mode.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/491
