### ISSUE TITLE
Spurious scroll and select when clicking on text in code block with unfocused window

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#848]
Windows 7 64-bit, Typora 0.9.33: Typing a new document, switching repeatedly to other windows.  When I click on part of a fenced code block, in the currently-unfocused Typora window, with the document scrollbar in any position but the very top, the scroll position jumps (scrollbar moving up), and the editor interprets this move as a drag-to-select.  This creates an annoying distraction as I try to figure out where my cursor ended up and how to get back to where I wanted to be.

If the scrollbar is all the way at the top, there is no scroll and no jump.  It also does not happen if I click outside the code block first, then where I intended to go...  unless the cursor was *already* in the code block when I left.  In that event, the scrollbar jump happens regardless.

(In fact, simply leaving the cursor in a code block, alt-tabbing to another window and back is enough to make the scrolling happen -- it's just that if you also try to click somewhere, you end up with a spurious selection as well.  Once the jump has occurred, subsequent alt-tabs back and forth do not produce any further scrolling, as though Typora wants the code block or the cursor to be at a particular place on the screen, and is scrolling to make it happen, even though the only event that has occurred has been task switching.)

**Comment by abnerlee** [comment]
Thanks for the report.

duplicate with https://github.com/typora/typora-issues/issues/857

In my testing, it won't happened on v0.9.36. Please update and check~

**Comment by pjeby** [comment]
Thank you!

**Comment by kepra3** [comment]
This same issue is still happening for me.
Using Mac OS Catalina 10.15.17 and Typora 0.9.9.36.2. 
I have been using Typora for everything for 3 years now and once I have a lot of text in the document this issue becomes much more apparent. This jump scrolling also occurs not just when I click into a code block but any text on the document. It is now seriously making me consider a switch to another software :(.
