### ISSUE TITLE
Command line option for HTML export?

### ISSUE THREAD

**Issue by Cooper-Yang** [typora/typora-issues#849]
I recently try using Pelican as my static site generator, which is based on python. However, python's strict and infamous 4 space indentation markdown really drive me crazy. 

With a bunch of notes composed using typora, most of them just don't follow the rules that python markdown required. Besides that, fenced code nested in list and other feature like high lighting also not supported in vanilla python markdown(which typora does).

It would be nice if typora can provide a command line option for exporting no style html, so that writing a script to handle the automation of exporting notes would be possible.

Thank you, for you and for this wonderful software that makes my life much easier.

**Comment by Cooper-Yang** [comment]
Plus, no style html seems to have some problem handling in-line math.

**Comment by abnerlee** [comment]
You could set indent size to 4 in preference panel to apply the indent size for auto generated blocks (like lists or block quotes), but it will not convert the existing ones.

About code block, currently generating code block directly using indent is not supported, but paste markdown or write "indented" code block in source code mode is supported. This is inconvenient, surely we would consider improvements.


If you need command line, maybe try [Python-Markdown](https://pythonhosted.org/Markdown/index.html) module, from its [docs](https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html), it says:

> GitHub‘s backtick (```) syntax is also supported:  

------

> It would be nice if typora can provide a command line option for exporting no style html, so that writing a script to handle the automation of exporting notes would be possible.

This is also a very good suggestion, BTW, could you tell me what your OS version? We would like to support on your OS first, in future.

**Comment by Cooper-Yang** [comment]
@abnerlee 
Oh, sorry about the confusing. Typora features I listed in the second paragraph are actually the things I wanted in python markdown, not the other way around. Also, pymdownx is a python markdown extension I currently use, which can turn off parsing space indented code block and use back-tick only.

And, yes, python markdown does support using back-tick, but only at the root level. Which means you cannot insert a code block in a ordered/unordered list. This "fenced code block within list" feature will only be supported after python markdown 3.0, [check this issue for further information](https://github.com/Python-Markdown/markdown/issues/53).

About my OS:
Ubuntu 16.04.2

**Comment by abnerlee** [comment]
duplicate to https://github.com/typora/typora-issues/issues/715

**Comment by 16kp** [comment]
Hi, are there any updates on this? I see the original issue was restricted, and this was closed as duplicate?
