### ISSUE TITLE
Math Block show source code no change to pression

### ISSUE THREAD

**Issue by Shaun2016** [typora/typora-issues#850]
![issue](https://user-images.githubusercontent.com/17938959/29519538-66569678-86b0-11e7-8b4c-186ed854a062.jpg)

I write code in Math Block，and In Typora show the pression correctly.But when I show it in browser,it shows the source code.

**Comment by abnerlee** [comment]
So you are using `Copy HTML` or `export HTML(without styles)`, and then open the copied/exported content in browser?

**Comment by Shaun2016** [comment]
I write a blog by typora in hexo, i run 'hexo s' command to see the blog in browser, the math pression is source code.

**Comment by abnerlee** [comment]
I see, you could use mathjax in your hexo template for post like this
```html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>
<script type="text/javascript" async src="path-to-mathjax/MathJax.js?config=TeX-AMS_CHTML"></script>
```
