### ISSUE TITLE
Disable auto wrap for code block

### ISSUE THREAD

**Issue by saup007** [typora/typora-issues#851]
1. The code format is not correct, it should be like this, but the actual is not
```
mysql> SELECT * FROM performance_schema.replication_group_members;
+---------------------------+--------------------------------------+-------------+-------------+--------------+
| CHANNEL_NAME              | MEMBER_ID                            | MEMBER_HOST | MEMBER_PORT | MEMBER_STATE |
+---------------------------+--------------------------------------+-------------+-------------+--------------+
| group_replication_applier | 1999b9fb-4aaf-11e6-bb54-28b2bd168d07 | 127.0.0.1   |       13002 | ONLINE       |
| group_replication_applier | 199b2df7-4aaf-11e6-bb16-28b2bd168d07 | 127.0.0.1   |       13001 | ONLINE       |
| group_replication_applier | 199bb88e-4aaf-11e6-babe-28b2bd168d07 | 127.0.0.1   |       13000 | ONLINE       |
| group_replication_applier | 19ab72fc-4aaf-11e6-bb51-28b2bd168d07 | 127.0.0.1   |       13003 | ONLINE       |
| group_replication_applier | 19b33846-4aaf-11e6-ba81-28b2bd168d07 | 127.0.0.1   |       13004 | ONLINE       |
+---------------------------+--------------------------------------+-------------+-------------+--------------+
5 rows in set (0,00 sec)
```

![tim 20170822193637](https://user-images.githubusercontent.com/1343717/29563674-3e1f1128-8771-11e7-850f-43074197e86f.png)

2.When you copy a text in typora, switch the window, then come back, read the position changed, not just the location,

**Comment by abnerlee** [comment]
> When you copy a text in typora, switch the window, then come back, read the position changed, not just the location,

This is duplicate with https://github.com/typora/typora-issues/issues/857

**Comment by AberSheeran** [comment]
So now, can the code block show the scroll bar instead of wrapping it?

**Comment by abnerlee** [comment]
No, please wait for next version up.

**Comment by dartie** [comment]
+1

**Comment by abnerlee** [comment]
Supported in new release.

**Comment by duqcyxwd** [comment]
@abnerlee  Do you mind post a link of solution here? I am trying to disable this as well.

**Comment by abnerlee** [comment]
@duqcyxwd there's related options in preferences panel

**Comment by duqcyxwd** [comment]
@abnerlee Thank you for your quick reply!!  It saves me a lot of time playing css!


![image](https://user-images.githubusercontent.com/2519905/116256798-8457ee00-a741-11eb-8ec1-6110cf96ce38.png)
