### ISSUE TITLE
Switching to Source Code Mode would Scroll the View all the way to top

### ISSUE THREAD

**Issue by mediter** [typora/typora-issues#852]
as said in the title, the cursor location would be scrolled out of view. However, usually when switching to source code mode from preview mode, it is to fix markdown formatting. Thus, the cursor should remain in view, and, more preferably, remain where it was.

Thank you for this amazing app!

**Comment by pen1120** [comment]
I met the same issues. and my environmtns is win7-64bits,latest typora version

**Comment by abnerlee** [comment]
Currently we will jump to the cursor position, but it seems incontinent if user just scrolled the document without any cursor selection change.

**Comment by abnerlee** [comment]
should be fixed already
