### ISSUE TITLE
Unable to exit italic mode without arrow keys

### ISSUE THREAD

**Issue by adamjstewart** [typora/typora-issues#853]
When I type `**`, it automatically switches to a bold font, adding the closing `**` at the end. If I enter some text and type `**` again, it **doesn't** add any new symbols, it just overwrites the `**` and I can carry on my way. So, if I type:

> \*\*foo\*\* bar

I end up with:

> **foo** bar

In contrast, if I type `_`, it automatically switches to an italic font, adding the closing `_` at the end. But if I enter some text and type `_` again, it **does** add new symbols instead of overwriting the `_` at the end. So if I type:

> \_foo\_ bar

I end up with:

> _foo_ bar_

The same problem occurs for both `*` and `_`. Basically, the only way to exit italic mode is with arrow keys.

**Comment by AlexPasternak** [comment]
Huh, good catch. I haven't noticed this because I typically use arrows to exit formats anyway, e.g, with `. It didn't occur to me to use the same character again to close it, but now that I know, it'd be nice for it to work right!

**Comment by abnerlee** [comment]
should be fixed in new version.
if the "*" you input match the ending one, only caret will be moved, without inserting "*"

**Comment by adamjstewart** [comment]
Can confirm that this has been fixed in the latest release. Thank you!

**Comment by AlexPasternak** [comment]
This seems to work perfectly for me now, does it not for you @adamjstewart?

**Comment by adamjstewart** [comment]
It does work for me, just wanted to report that it works now.

**Comment by AlexPasternak** [comment]
Sorry I misread yours as a question ("can you confirm...?"), not a statement. That's what I get for trying to multitask.
