### ISSUE TITLE
Install on Windows without installer

### ISSUE THREAD

**Issue by estrenuo** [typora/typora-issues#854]
As I don't have admin rights on my work pc, it would be nice if I could "install" Typora without the use of the windows installer, i.e. maybe as a zip.

**Comment by abnerlee** [comment]
maybe same as https://github.com/typora/typora-issues/issues/371

Current concern is: we need admin rights if we want to let "Typora" show up in the "Open With" Context menu automatically. 
It is also needed if we want to put recent opened files in list, when user right click on the icon in taskbar.

**Comment by matchavez** [comment]
For what it's worth, I wanted to use typora at work, but cannot. I am not allowed admin rights. I'd **happily** give up the context and open with for the ability to actually use it. Like other installers, you should just have one installer, but say "you don't have admin, therefore, we can install without x & y, or you can cancel."

**Comment by matchavez** [comment]
In the meantime, I'm going to have to continue using Atom, as it does install without admin rights.

**Comment by PwrSrg** [comment]
I was using a **Portable BETA** for over a year and **LOVED it**!
But now that v1 is out, **it no longer works**. 😖

As soon as there is a **portable version**, you will get my money.
