### ISSUE TITLE
view fly to top of file when switch back from other application

### ISSUE THREAD

**Issue by fzhzhy** [typora/typora-issues#857]
to reproduce this issue: 

1,  edit in typora
2,  use alt+tab(or mouse) to switch to other application like browser to do something 
3,  when use alt+table(or mouse) to switch back to typora to continue edit. 
4,  the view will get to top of the file, but cursor still stay the original place. 

This is really bad UX. 

My env: 
1, win7+64bit.
2, typora 0.9.33

Thanks for this great tool.

**Comment by abnerlee** [comment]
should be fixed in 0.9.36
