### ISSUE TITLE
Using format header key shortcut with table insert dialog modifies file

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#858]
1. Open a saved file, navigate cursor to end of file
1. Cmd-T to show insert new table dialog
1. With dialog up, press Cmd-2 or another keyboard shortcut for formatting headers
1. Notice how file status changes to Edited in title bar, even though you should not have been able to modify the file with a dialog up
1. Press Cancel button, note how cursor is not blinking where it was before
1. Start typing, notice how text is now being inserted into the beginning of the file at this point
1. If you attempt to close file now, no save prompt appears, so no changes were made, despite the Edited status shown

Easy to repro with these steps, please fix. Thanks.

![2017-08-24 11 10 45](https://user-images.githubusercontent.com/1819485/29673439-30107624-88bd-11e7-9bed-3cd169b89eca.gif)

**Comment by abnerlee** [comment]
seems already fixed

**Comment by AlexPasternak** [comment]
@abnerlee I still get the same exact behavior in the latest build, I don't think it's fixed. Cmd-2 changes doc status to Edited, like in my repro GIF, even though the modal dialog was up, and no changes were actually done to the doc. Formatting keyboard shortcuts should not have any effect while insert table modal dialog is up.

**Comment by abnerlee** [comment]
Should be fixed in latest version
