### ISSUE TITLE
Add an OS X Shell Command

### ISSUE THREAD

**Issue by luissquall** [typora/typora-issues#86]
It would be awesome to have a command to open files from the shell like [Sublime](https://www.sublimetext.com/docs/2/osx_command_line.html) and [Visual Studio Code](https://code.visualstudio.com/docs/editor/setup#_mac-os-x).

I'm currently using this function as a workaround:

```bash
# Modified Visual Studio Code function 
# Typora
typora () {
    if [[ $# = 0 ]]
    then
        open -a "Typora"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Typora" "$F"
    fi
}
```

then:

```bash
typora file.md
```

**Comment by abnerlee** [comment]
@luissquall  you could add:

```sh
alias typora="open -a typora"
```

in your `.bash_profile` or other configuration file, then you would be able to do `typora file.md`

**Comment by luissquall** [comment]
Better yet! Thank you @abnerlee.

**Comment by yourmoonlight** [comment]
Thanks~ @abnerlee.
