### ISSUE TITLE
Sort subdirectories at the end of Article view.

### ISSUE THREAD

**Issue by DIWesser** [typora/typora-issues#862]
Typora sorts files in the list in Article view alphabetically by file name regardless of whether the file is in the current working directory or a subfolder of the working directory. I would prefer to have articles in the working directory show up first and articles in sub folders shown at the bottom or not shown at all.

For example, I have a folder called "Notes" that I use for exactly what you think. Within that folder, I have an equally creatively named "Archive" folder. When I archive notes I add a reverse date code to the beginning of the file (`2017-08-26 Example.md`). Because archived notes begin with a number, they show up at the top of the list. I don't want that.

**Comment by abnerlee** [comment]
> Typora sorts files in the list in Article view alphabetically by file name regardless of whether the file is in the current working directory or a subfolder of the working director

Could enable "Group by Folder" in the "sort" section, after you click the button in the bottom of your left side panel.
