### ISSUE TITLE
Strange behavior with "{0}." inside nested lists

### ISSUE THREAD

**Issue by changbowen** [typora/typora-issues#864]
i have seen some appearance of `   {0}. ​` instead of `  - ` inside a bullet list.
here is how to possibly replicate it:

------------------

1. copy these text:
```
# Test

1. First line.
2. Second line.
  - Line with *italic*.
  - Another line.
3. Third line.
   - Line with *italic*.
4. Fourth line.
```

2. paste into a typora window as source code. and go to the end of the fourth line.
3. press enter. press tab. right click, click the bullet list button.
4. switch to the source code mode, and you can see `   {0}. ​` is showing instead of `   - `.

the problem does not appear if at step 3, you press enter, backspace, then type hyphen and followed by space.
is this a bug with the bullet list button command?

**Comment by abnerlee** [comment]
Should be fixed in the new release
