### ISSUE TITLE
Cut and Paste of Task List item behaviour

### ISSUE THREAD

**Issue by motorkap** [typora/typora-issues#866]
macOS 10.12.6
Typora 0.9.9.10.6

If I copy a task list line and then paste it elsewhere the markdown '- [ ] (etc)' changes to '* [ ] (etc)' so I end up with a bullet rather than a task list item.

If I 'Copy as Markdown' and then paste I also end up with a bullet and not a task list item.

For the copy/paste to work as expected I have to 'Paste as plain text'. I don't know if this counts as a bug or works as designed, but it feels counter intuitive.

**Comment by abnerlee** [comment]
Should be fixed in the new release
