### ISSUE TITLE
Lost  data when  I'm typing.....I can't smile anymore

### ISSUE THREAD

**Issue by YeziGZ** [typora/typora-issues#868]
When I'm typing，Typora flashing for a moment，then I can't find the words I just typed any more！any.......more.......

**Comment by abnerlee** [comment]
Sorry for this bug... What's your OS/Typora version?

See http://support.typora.io/Version-Control/ for recovery

> Typora flashing for a moment then I can't find the words I just typed any more

 So the text just gone from the window?

**Comment by abnerlee** [comment]
need more info
