### ISSUE TITLE
Source mode clicking cursor bug

### ISSUE THREAD

**Issue by harper357** [typora/typora-issues#869]
Pretty odd bug. When in source mode, I can not click the cursor to the first two characters on each line. I can click and highlight back to them, but if i directly click onto them I am unable to. This is not a problem in the normal model. Using typora Version 0.9.9.10.6 (0.9.9.10.6) on OS X El Caption 10.11.6.

**Comment by abnerlee** [comment]
May relates to https://github.com/typora/typora-issues/issues/796

**Comment by abnerlee** [comment]
Fixed in new release
