### ISSUE TITLE
Spell Check does not work on Windows

### ISSUE THREAD

**Issue by hungching1982** [typora/typora-issues#870]
Spell Check does not work on Windows 10 (1703, OS: 15063). Both the Windows and Typora are updated to the latest version.

**Comment by abnerlee** [comment]
Did you enable spell check from preference panel?

Click View->Toggle DevTool, can you any error logs related to spell check?

**Comment by hungching1982** [comment]
Spell Check is already enabled.
I can't find "View" and "Toggle DevTool" in the settings.
What to do to report the error?

**Comment by abnerlee** [comment]
> I can't find "View" and "Toggle DevTool" in the settings.

Sorry, I mean menu item 'View' and its submenu `Toggle DevTool`

**Comment by hungching1982** [comment]
Sorry but I don't see "View" in menu...

![image](https://user-images.githubusercontent.com/31490918/30093033-fa5ee316-92c2-11e7-82ae-88c5e5df3046.png)

**Comment by abnerlee** [comment]
Sorry, sorry, please switch to "native" style in preference panel first..

**Comment by hungching1982** [comment]
Three errors. Not sure if they have something to do with Spell Check. Does this help?
![2017-09-06 1](https://user-images.githubusercontent.com/31490918/30134141-63056082-9356-11e7-887a-da9121ea3153.png)

**Comment by abnerlee** [comment]
Sorry, it seems no log about spell check. Could you try send the `typora.log` file under ` C:\Users\{username}\AppData\Roaming\Typora` to us (<hi@typora.io>) ?

**Comment by seesharper** [comment]
Seeing the same issue with 0.9.36

**Comment by hungching1982** [comment]
The file sent!

**Comment by seesharper** [comment]
btw, this editor is really awesome. Nothing out there can compare to this 👍

**Comment by seesharper** [comment]
Any updates on this?

**Comment by abnerlee** [comment]
Still exists in new release (v0.9.38)?

Please reopen this one if the bug still happens

**Comment by hungching1982** [comment]
The problem is still there with the latest version...

**Comment by seesharper** [comment]
Still facing the same issue

**Comment by abnerlee** [comment]
So, are your using the 64bit or 32bit Windows/Typora?

**Comment by ijesonchen** [comment]
64 bit windows & Typora.
I tried the solution in https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/spell-checker-not-working-in-mail-or-word-windows/81bf53c4-f5c4-4920-aa91-0b5cb44d4ad2?auth=1 . All the options are turned on by default. It doesn't work.
Spell check doesn't work on chrome or notepad.

**Comment by ijesonchen** [comment]
Well, I resolved it.
Maybe the reason is my Win10 language set is Chinese and the spell check for English does not work.
So I add the English (United States) language pack in Windows Settings, and it works in Typora, and Win10 Mail, not Notepad.
Because I use the Chinese language, the detailed step maybe not totally correct:
Windows Settings, Datetime and Language, Location and Language, Add Language, then add English (United States).
Maybe you should select the added language, Option, then download some resource.
Hope that could help.

**Comment by hungching1982** [comment]
I also have the same situation like @ijesonchen 's. The problem is fixed also by his solution. Not perfect, but acceptable. Thanks.

**Comment by whzecomjm** [comment]
Can not add a new language for my Win10 Home. sigh...

**Comment by wirehack7** [comment]
Spellcheck is also not working for me. 
Would be great if that will be fixed.

Latest Typora version (0.9.53 beta)
Also no errors in console regarding spellcheck

**Comment by abnerlee** [comment]
@wirehack7 

Have you enabled spell check in preferences panel?

Also, Typora use the spell checker provided by system, so, please also try:

> Maybe the reason is my Win10 language set is Chinese and the spell check for English does not work.
> So I add the English (United States) language pack in Windows Settings, and it works in Typora, and Win10 Mail, not Notepad.
> Because I use the Chinese language, the detailed step maybe not totally correct:
> Windows Settings, Datetime and Language, Location and Language, Add Language, then add > English (United States).
> Maybe you should select the added language, Option, then download some resource.
> Hope that could help.

**Comment by dehphantom** [comment]
Spell Check works fine in Typora v0.9.86 on Win10. I thought i had the same issue only to discover minutes later that it's because i was using Source Code Mode (Ctrl + /). Switch back to Layout Mode (same toggle Ctrl + /) to see spell check in actio (action) :)
