### ISSUE TITLE
Mermaid gantt broken

### ISSUE THREAD

**Issue by blark** [typora/typora-issues#871]
Mermaid gantt charts no longre render properly. 

Reproduction: go to mermaid or typora website, copy gantt chart and paste into Typora.

**Comment by abnerlee** [comment]
This should already fixed recently, would you confirm your typora is latest by "Check for Updates" from File menu (macOS version) or Help menu (Linux/Windows version) ?

**Comment by gpetrini** [comment]
Same problem with Linux 0.9.60 version.
