### ISSUE TITLE
After new file renamed, "Untitled.md" still exist

### ISSUE THREAD

**Issue by itviewer** [typora/typora-issues#872]
In the tree view mode，Right-click menu to create new file, then rename `Untitled.md` with other names, but `Untitled.md` still in the list.

**Comment by abnerlee** [comment]
@itviewer  what's your OS version?

**Comment by itviewer** [comment]
@abnerlee Windows7 64bit，typora version 0.9.36 beta

> Note that, this problem sometimes does not happen, but often occurs

please see the below gif.
![bug](https://user-images.githubusercontent.com/1397840/30511108-dee41ef4-9b04-11e7-82f9-0cc8f5284220.gif)

**Comment by abnerlee** [comment]
Should be fixed in new release
