### ISSUE TITLE
Windows auto update issue

### ISSUE THREAD

**Issue by mbedded** [typora/typora-issues#873]
Version: around 0.9.36 (beta)
OS: Windows 7, 8.1, 10

Hello Typora-Team,
i found an issue in your updater.

## Steps:
- Start Typora
- Get a popup for "download new version" or do a check and "download new version"
- A new download window appears
- A new file is downloaded (lets say 50MB) and with the time the download-bar fills
- Close Typora (while download is running!)

**Result:** The downloader is closed too and the download got canceled

If you restart Typora now, it will say "there is a new version" and manual check will guide you to re-download the update, too. The full update (50 MB) has to be downloaded again.

## Expectation:
- Download-Window should not be affected by application window (when i close Typora *after* the download everything works fine)
- A hint that the download will canceled if i try to close Typora while download
- *If possible:* The already downloaded update should be stored so just the left data is downloaded

**Comment by be5invis** [comment]
Any progress?

**Comment by Arrow7000** [comment]
This happens for me as well and makes it basically impossible for me to update Typora. Is there any progress happening on this?

**Comment by be5invis** [comment]
Any progress?
This is very very annoying since Typora updates _so frequent_.
I suspect @abnerlee doesn't have a PC...

**Comment by kostrse** [comment]
Maybe distribute it as a Microsoft Store app?

**Comment by abnerlee** [comment]
used new upgrade logic
