### ISSUE TITLE
Dragging proxy icon in window titlebar also moves window

### ISSUE THREAD

**Issue by jhawcroft** [typora/typora-issues#874]
In a recent update of Typora (this issue is occurring in 0.9.9.10.6), dragging the document window's proxy icon no longer works properly.  At present, the icon and the document window move together, which prevents effective use of the proxy icon.

See Apple's TextEdit application for an example of how it's supposed to work.  Only the proxy icon is supposed to move (representing the document), so that for example, the document can be dragged into an FTP client or a Google Drive window to be uploaded / backed up.

Note, the correct behaviour takes about a second of holding the mouse-down over the icon before the icon 'detaches' from the window itself and can be dragged.

Without looking at the code, I suspect this has happened due to how the word count + ancillary widgets in the top-right of the window may have been implemented.  If that is the case, my suggestion is to make sure no custom behaviour is implemented/no existing behaviour overridden when the window title itself is dragged (including the proxy icon) - ie. don't override the event unless it falls clearly within the region you want to handle the word count + ancillary widgets.

![proxyicon](https://user-images.githubusercontent.com/3815788/29992654-41dcfc28-8fe4-11e7-85cb-2bba29ca4cad.png)

**Comment by abnerlee** [comment]
Fixed in new release
