### ISSUE TITLE
Settings option to save image to local instead of insert online url

### ISSUE THREAD

**Issue by uocnb** [typora/typora-issues#875]
When copy and paste image from web, it is automatically paste online image url instead of save image to local folder. In case image url is fetch from CDN it will get expire after period of cache time and image become unavailable. It should be better to have an option to force Typora to save image data to local instead of insert url.

**Comment by liquidblasted** [comment]
Yes that would be awesome, a real replacement for such apps as Evernote, OneNote etc - when you can easily collect your own database from the internet which keeps work completely offline & forever.

**Comment by abnerlee** [comment]
Supported in new version.

User can set the location to save image in preference panel and choose whether the rule should apply for online images.

It works for drag & drop or copy paste. If user input URL in markdown directly, Typora will not do auto convert, but give options for users to save the image

**Comment by lunmhit** [comment]
Maybe it's also quite convenient to automatically convert pasted images to Data URL (as Jupyter notebook does)?
