### ISSUE TITLE
Bug with CMD + E in a list

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#877]
On the following text:

```
* **Something**. And here is normal text.
```

It does not work to properly select the entire bullet point when the cursor is in the text. When one presses CMD + E and then CMD + X, it will reveal that the first `**` were not selected. As a result, the following text will remain:

```
* **
```

And the copied text is missing these two `**`:

```
Something**. And here is normal text.
```

Analogically it doesn't work if the text is italicized.

**Comment by abnerlee** [comment]
Seems cannot reproduce this for now. What's your Typora version @pgolebiowski ? Does it happen on newly created file or only on large files?

**Comment by pgolebiowski** [comment]
Have a look at this:

![ezgif-3-d6ea4fba47](https://user-images.githubusercontent.com/7394091/29996958-807f9872-9008-11e7-9e97-99e1d73bb83c.gif)

The problem is that is doesn't work like that only _sometimes_. My version is 0.9.9.9.4.2.

**Comment by abnerlee** [comment]
I see, please update the the latest version of Typora.

I cannot reproduce this bug on the latest version
