### ISSUE TITLE
Changes in Source mode reverted when changing back

### ISSUE THREAD

**Issue by sims1253** [typora/typora-issues#878]
I don't have a concrete example right now but this is happening from time to time. Something doesn't look as I want it to so I go to source mode and change it. Deactivating and reactivating source mode then doesn't look the same anymore. 

Using the newest AUR package (which is 0.9.36(beta))

**Comment by sims1253** [comment]
Also it seems like undo only works in the render mode, not in source mode

**Comment by abnerlee** [comment]
#461
