### ISSUE TITLE
Header level indicator is shown all the time

### ISSUE THREAD

**Issue by pgolebiowski** [typora/typora-issues#879]
For example in Pixyll, it's normal:

<img width="239" alt="screen shot 2017-09-02 at 20 50 37" src="https://user-images.githubusercontent.com/7394091/29997970-79c2fa02-9020-11e7-9741-a741f8ff6cbf.png">

But in the Night theme, it's like this:

<img width="182" alt="screen shot 2017-09-02 at 20 50 28" src="https://user-images.githubusercontent.com/7394091/29997973-8d24b824-9020-11e7-84f0-6cf53c350eb1.png">

Meaning that h3+ is always visible. It's especially a big deal when exporting to something, because it's also rendered there.

@abnerlee Thanks for the great work!! :heart:

**Comment by abnerlee** [comment]
Seems already fixed
