### ISSUE TITLE
The Cursor isn't always aligned with where I click

### ISSUE THREAD

**Issue by NigelThorne** [typora/typora-issues#881]
![cursor_not_aligned_with_click](https://user-images.githubusercontent.com/5942/30007431-4faebeb8-9151-11e7-9e51-f2db29dd3f6f.gif)

Sometimes, when I click the cursor is placed one character to the left of where I expect it to appear.

Using 0.9.36 on Windows. 

In "source code mode" it works fine.

**Comment by michaudg** [comment]
Same here.

0.9.36 on Linux.

**Comment by abnerlee** [comment]
fixed in v0.9.38 

Fix for other dark themes like "Ash" or "Monospace Dark" will be updated later by updating other CSS file
