### ISSUE TITLE
A java script error occurred in the main process

### ISSUE THREAD

**Issue by lj8385174** [typora/typora-issues#882]
![image](https://user-images.githubusercontent.com/3823826/30008674-7694c8da-9154-11e7-9688-51b1d539e717.png)

I can't provide the file which occurs this fault, cause it is corrupt by this app.

system: windows 10 64bit.
typora version: 0.9.36 beta

**Comment by lj8385174** [comment]
BTW, I suggest you the provider add some disclaimer in your application, to inform user that this app may corrupt thier precious data.

**Comment by abnerlee** [comment]
Only open that file will trigger this bug, or will open other files, create new file trigger this bug?

**Comment by abnerlee** [comment]
relates https://github.com/typicode/lowdb/issues/157

**Comment by abnerlee** [comment]
> I can't provide the file which occurs this fault, cause it is corrupt by this app.
please check http://support.typora.io/Version-Control/

By "corrupt", you mean your markdown file is empty now?

**Comment by lj8385174** [comment]
> Only open that file will trigger this bug, or will open other files, create new file trigger this bug?
This error just  appears twice, both of which are at opening this file. However, after that, this error just disappears whichever file is opened. So I can't determine whether it is that file causes this error.
>Does Typora has access permit on C:\Users{your user}\AppDate\Roaming\Typora ?
I am not sure. it works just fine after appearing error twice.
>And how to reproduce this bug, what did you do before this dialog show up?
I am not sure. I can't reproduce this bug.
>And could you send typora.log in C:\Users{your user}\AppDate\Roaming\Typora to us (hi@typora.io) ?
I have sent my log file via mfarymail@gmail.com

>By "corrupt", you mean your markdown file is empty now?
Yes.

hope to be helpful

**Comment by abnerlee** [comment]
@lj8385174  I see, thanks for your time. 

And this may help -> http://support.typora.io/Version-Control/

**Comment by lj8385174** [comment]
That really helps a lot, thx.

**Comment by abnerlee** [comment]
relates typicode/lowdb#157

**Comment by vladimiry** [comment]
I just pointed to a probable cause of the error here https://github.com/typicode/lowdb/issues/157#issuecomment-448500253
