### ISSUE TITLE
pandoc: Count not read: Pandoc (Meta {unMeta = fromList []})

### ISSUE THREAD

**Issue by hellozjf** [typora/typora-issues#883]
I'm using Typora to create a table.

![](http://ody3ivli2.bkt.clouddn.com/2017/09/03/TIM%E6%88%AA%E5%9B%BE20170903100806.png)

When I click File->Export->Word(.docx), I got some error

![](http://ody3ivli2.bkt.clouddn.com/2017/09/03/TIM%E6%88%AA%E5%9B%BE20170903101223.png)

I tried to use pandoc command to export docx, and it does not report any problem.

So it must be a bug of typora I think.

**Comment by abnerlee** [comment]
Hi, seems work when export markdown file with table in my testing..

So could you send us <hi@typora.io> the *.md file you used? That will be a great help !

**Comment by abnerlee** [comment]
cannot reproduce in v0.9.36

**Comment by verazuo** [comment]
Hi, I also meet this problem in v0.9.9.19.4. Is there any solution for this bug?

**Comment by abnerlee** [comment]
@verazuo could you send us (hi@typora.io) the sample *.md file
