### ISSUE TITLE
Remember Window View

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#884]
Not the biggest of things, but...

Whenever I restart Typora, it always opens a "non-maximized" window (I like to work with the screen maximized), and it's rather annoying. Is there a way to have Typora remember your view setting so it will open up with how it last was (take Windows File Explorer for example).

**Comment by markgoodson** [comment]
In a variation on this, quite often when I open Typora it will open a window off screen. I then have to focus on Typora on the taskbar and right-click on the mini-window, choose "move" and then use the cursor keys to get the window back. A complete pain if you want to open a window to quickly jot down some notes.

**Comment by abnerlee** [comment]
=This should be fixed already (v0.9.38)
