### ISSUE TITLE
Support capture screenshot from services

### ISSUE THREAD

**Issue by nthakor** [typora/typora-issues#885]
While choosing option `Capture Selection from Screen` selected image is inserted to the position of the cursor. But when I move to text line by pressing enter the image disappear.

**Comment by abnerlee** [comment]
> While choosing option `Capture Selection from Screen`

Where can I find this option?

**Comment by nthakor** [comment]
<img width="772" alt="screen shot 2017-09-05 at 7 03 08 pm" src="https://user-images.githubusercontent.com/19538934/30063609-ea7fe9aa-926c-11e7-9a95-4795c7fd9717.png">


After right click in MacOS

**Comment by abnerlee** [comment]
This menu is added by 3rd part app, so which app added such option in your context menu?

**Comment by nthakor** [comment]
I did not install any third party app for this.  I installed the typora app from its website.

**Comment by abnerlee** [comment]
> I did not install any third party app for this. I installed the typora app from its website.

Sorry, now I can find this menu in context menu, I will check this.

**Comment by abnerlee** [comment]
Supported in new release.

But unprefect due to https://github.com/typora/typora-issues/issues/1059
