### ISSUE TITLE
Printing directly from markdown renders ligatures incorrectly

### ISSUE THREAD

**Issue by jknaus** [typora/typora-issues#889]
When I try to print a document (i.e. CTRL+P), I get strange characters in the printed document.
These strange characters appear when there a combination of two characters can be transformed into a ligature, e.g. **fi**sh, e**ff**ort, **fl**eet. The output on paper is **Y**sh, e**ư**ort, **y**eet .
Obviously typora tries to use ligatures but does it wrongly.
This only affects printing, no other output.
I am on Windows 7.

**Comment by abnerlee** [comment]
It seems I cannot reproduce this, which theme/font did you use? what's your system language? Does `Export` -> `PDF` from `File` menu work properly?

If you add custom css (http://support.typora.io/Add-Custom-CSS/)
```
#write {
font-variant-ligatures: no-contextual;
}
```

Can this bug solved?
