### ISSUE TITLE
Crash when closing Typora

### ISSUE THREAD

**Issue by rtrn** [typora/typora-issues#893]
The newest version of Typora (0.9.36) crashes everytime I close the Typora window.
I'm using Windows 10 Pro 64-bit Version 1703.

The Event Viewer shows the following entry:
```
Faulting application name: Typora.exe, version: 0.9.36.0, time stamp: 0x59542618
Faulting module name: ntdll.dll, version: 10.0.15063.447, time stamp: 0xa329d3a8
Exception code: 0xc0000005
Fault offset: 0x0000000000030e01
Faulting process id: 0x17f8
Faulting application start time: 0x01d327e474902305
Faulting application path: C:\Program Files\Typora\Typora.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 77ce23bf-25bb-4f12-b022-a66a6d73d25c
Faulting package full name: 
Faulting package-relative application ID: 
```

Also, crash dumps are created in `%LOCALAPPDATA%\CrashDumps`.  I can upload one if needed.

**Comment by abnerlee** [comment]
@rtrn Thanks for the report. Could you send the `CrashDumps` and `typora.log` under ` C:\Users\{username}\AppData\Roaming\Typora` to us (<hi@typora.io>)?
