### ISSUE TITLE
File auto refresh not working reliably

### ISSUE THREAD

**Issue by ChuangTseu** [typora/typora-issues#894]
When modifying the file content from outside (be it via another editor or a dumb echo command), Typora does not reliably refreshes the file content, which is problematic as it can lead to potential data loss when saving the file via Typora if one does not notice the missing new stuff.

Note that putting Typora into focus does not trigger a refresh either (like it does with other editors like Notepad++ or Sublime Text).

**System:**
Windows 10 64bit Version 1703 (Creators Update)
Typora version 0.9.36 (beta)

**Steps:**
- Open a file with Typora
- In a batch/batch terminal, repeatedly append new lines to the file (example: `echo something >> $MY_FILE` ) 
- Observe how it misses some new lines, up to 4/5 lines if going fast

> Note: also works when quickly adding lines and saving from another editor

**Demo:**
See the little demo (as a gif) below:

![typora_refresh_miss_in_action](https://user-images.githubusercontent.com/1493448/30172260-9dae48cc-93f4-11e7-9fef-a711d85ecbd5.gif)

**Comment by abnerlee** [comment]
other patterns reported by users -> https://github.com/typora/typora-issues/issues/1117

**Comment by abnerlee** [comment]
Should be fixed in v0.9.49

**Comment by noio** [comment]
Is there a Preferences setting to enable this behaviour? When I modify the file outside of Typora, Typora does not show the changed contents unless I navigate away & back through the "FILES" explorer sidebar.

**Comment by horseshoe107** [comment]
Auto refresh was working with version 0.9.70 (windows build).

After updating to 0.9.72, auto refresh seems to have reverted. I have the autosave preference enabled. I tried the following steps:
1. Open a markdown file in Typora
2. Open the same file in another editor (Sublime Text). Modify and save.
3. Switch focus to Typora. Observed that the change did not appear in Typora.
4. Switch focus back to other editor. Observed that Typora autosave reverted the changes.

**Comment by abnerlee** [comment]
Let's a new bug: #2600
