### ISSUE TITLE
Help!!! Tab Inconsistent Indentation In Code Block

### ISSUE THREAD

**Issue by yanzhang0219** [typora/typora-issues#896]
Shown below:
![243a2449-7fbb-4e6c-a05e-0645e39a430d](https://user-images.githubusercontent.com/11582667/30185633-30f032d0-93d7-11e7-8c8d-b58e36fe4618.png)
Then I press enter and the indentation is 4 spaces:
![1e747883-4113-4fb2-a81e-46fac9390ede](https://user-images.githubusercontent.com/11582667/30185746-9a8b25e2-93d7-11e7-8443-4bb3117c0473.png)
Then I type one line, and press enter, the indentation is changed to 2 spaces:
![e23d724e-8e63-4300-aa3f-a51e04eb2460](https://user-images.githubusercontent.com/11582667/30185705-7dc8c68a-93d7-11e7-83a8-23db545fd06e.png)

Is is normal or a bug here? 

Another issue:
If I don't specify any languages in a code block, then I type something in it using tab as the intervals:
![09f3b306-4308-457b-bd59-54da058f6940](https://user-images.githubusercontent.com/11582667/30185873-2289996a-93d8-11e7-8293-9e4b84b6f5c5.png)
Here between / and \ I used two tabs, and this figure clearly shows the positions of / and \ related to those aaaaaaaa. Then I exported it into a PDF file (snapshot of this PDF result is shown below), you can observe that the position of / and \ are changed. Specifically, the intervals between / and \ are enlarged. 
![8da4b8cb-8861-4a6c-98b8-6cd69a027a3d](https://user-images.githubusercontent.com/11582667/30186032-b95e4c14-93d8-11e7-9ccc-5c0d3c7119d1.png)

Could you please help me figure this out??

Thank you so much. And wish my love Typora will be better and better.

**Comment by yanzhang0219** [comment]
@abnerlee Any ideas? Please help. Many thanks.

**Comment by abnerlee** [comment]
> Is is normal or a bug here?

Seems a bug, it should be consistent. But typora is not a code editor, so auto indent inside code block will not be a high priority issue.

About the print bug, we can reproduce it. we will fix this.

**Comment by yanzhang0219** [comment]
@abnerlee Okay, I see. Thanks.

**Comment by abnerlee** [comment]
fixed in new release
