### ISSUE TITLE
Inline math block disappeared after clicking

### ISSUE THREAD

**Issue by 131441373** [typora/typora-issues#897]
When clicking or choosing a **inline** math block, it just disappeared.
This problem is also with Bold method .

**Comment by abnerlee** [comment]
What's your OS version? what inline math did you input?

**Comment by 131441373** [comment]
Linux ubantu 16.04
just type any formula, clinking twice, and it disappear
and can't use Ctrl + Z to undo
sometimes  use Ctrl + A near a math block will also make it disappear

**Comment by abnerlee** [comment]
I cannot reproduce this bug, does it still exist in our latest version ?
