### ISSUE TITLE
Love this app: FYI

### ISSUE THREAD

**Issue by JCzz** [typora/typora-issues#898]
This is for Mac users:
And if it is relevant for anyone - then maybe add the following information to you site:
I am using(just started with you beta for mac) this app to write anything(not code), but still - and I am reference other documents(a lot), therefore I just needed to set the default app to Typora, well I diden't know - therefore I found:
https://www.imore.com/how-set-mac-app-default-when-opening-file

And maybe even a future feature request, could be, to be able to navigate links within the same current opened instance(app/Typora).

Keep up the good work
Regards
Christian

**Comment by abnerlee** [comment]
> And maybe even a future feature request, could be, to be able to navigate links within the same current opened instance(app/Typora).

Yes, cmd+click on a markdown file link will open this file by Typora.
