### ISSUE TITLE
Support drag and drop links from browser

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#899]
Currently if you drag a URL from Safari onto a Typora page, nothing happens (It is ignored). The behavior is the same whether I drag the URL from the address bar, or drag a link from web content. 

**TextEdit** (in Rich Text mode) or other Markdown editors such **ByWord** behave as expected:

1. Dragging the URL from the address bar inserts into Typora a link to the URL whose anchor text is the title of the webpage.

2. Dragging a link from the web content inserts into Typora an identical link (same anchor text and URL).

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/1073 covers more
