### ISSUE TITLE
[Feature] Hosted Web Version of Typora

### ISSUE THREAD

**Issue by trever** [typora/typora-issues#9]
Definitely not an issue, but when playing around with the source code of Typora, it seems like it'd be reasonably trivial to throw it up on a server, add a user account system, and auto-save documents to an account (or even a login-with-dropbox type functionality with auto-saving to a dropbox account).

Is this on the roadmap? or is the goal to stay with the native wrapping?

Really really love the product! It has become my writing client of choice.

**Comment by abnerlee** [comment]
Duplicate with https://github.com/typora/typora-issues/issues/684

**Comment by JFox-sk** [comment]
Now, Typora is after the 1.0 release... Are there some plans for the web version?
Thank you for the great product!

**Comment by drywolf** [comment]
I would be also very interested in a web-version, especially if it was possible to directly edit markdown files on online git-hosts (e.g. github, bitbucket, gitlab, ...)

For example, Github/Bitbucket currently only have very crude online editors for markdown. If the full Typora editing experience would be available to edit markdown files directly in those online repositories, I think that would be a huge selling argument for such a Typora web-version.
