### ISSUE TITLE
[feature] Add support for multiline image/inline math

### ISSUE THREAD

**Issue by azag0** [typora/typora-issues#90]
Currently, Typora does not seem to parse multiline image alt texts. In Pandoc, the image alt text in standalone images (where image is the only thing in a paragraph) can be used to generate standalone figures with figure captions (`<figure>` in html, `\begin{figure}` in latex). This is especially important in scientific texts where images have always captions. In such case, the alt text can be a long text and having a possibility to break it into several soft-breaked lines is very convenient (as with the main text).

I suggest two things:
1. Support parsing multiline (not multi-paragraph) image alt texts.
2. If a figure is the only thing in a paragraph **and** the image alt text is multiline, display the alt text underneath (or above) the image with a prefix "Figure: " and possibly increased left and right margins and/or smaller font to distinguish it from the main text. This is consistent with the default styling of `<figcaption>` in html5.

The simple multiline figure caption would look like this:

``` markdown
![This is a figure caption.
](image.png)
```

**Comment by robie2011** [comment]
can we expect a fix for this? I will be a really helpful to include graphviz #549 in documents.

**Comment by ethanwillis** [comment]
I would also like this.

**Comment by ethanwillis** [comment]
This is why Typora needs to be open source so we can add this support ourselves. It seems like Typora development has slowed down. I've run into a lot of open issues that have been sitting for 1 year+ that I would fix myself if I was allowed to.

Typora respect your users freedoms.

**Comment by azag0** [comment]
@ethanwillis Not open sourcing your software is a completely legitimate decision. I myself would love too if Typora was open source, but it has nothing to do with "respecting users".

**Comment by ethanwillis** [comment]
> “Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer”. We sometimes call it “libre software,” borrowing the French or Spanish word for “free” as in freedom, to show we do not mean the software is gratis.
> 
> We campaign for these freedoms because everyone deserves them. With these freedoms, the users (both individually and collectively) control the program and what it does for them. When users don't control the program, we call it a “nonfree” or “proprietary” program. The nonfree program controls the users, and the developer controls the program; this makes the program an instrument of unjust power.

https://www.gnu.org/philosophy/free-sw.en.html

**Comment by azag0** [comment]
Yes, I’ve read the GNU license too. It’s a particular ideology and not everyone subscribes to it.

**Comment by clawoflight** [comment]
I would also love to be able to work on this.
Typora is an awesome concept, but performance is bad and development too slow.

Doesn't need to be GPL, I normally use the much more restrictive Mozilla Public License v2, but anything that lets us help! Even more so since there is no plugin mechanism.
I would pay for an open-source version of Typora.

**Comment by abnerlee** [comment]
Supported in new release

**Comment by ethanwillis** [comment]
To be honest, I would also pay.
