### ISSUE TITLE
not support math begin-end syntax

### ISSUE THREAD

**Issue by CHiiLD** [typora/typora-issues#903]
## env
os: osx 10.12
version 0.9.9.10.6 (0.9.9.10.6)

## bug content
write code like this
```
$
\begin{aligned}  
&Thm \space f:A \to B \space bijective \  
&\iff \exists f^{-1}B \to A \space : \space inverse \space ft \space of \space f \  
&\iff f \circ f^{-1} = I_B \  
&\iff f^{-1} \circ f = I_A \  
&\end{aligned}  
$
```

and i expect like this(snapshot by atom ide)

![2017-09-13 5 51 34](https://user-images.githubusercontent.com/11678846/30347758-15b6ca04-9848-11e7-95f0-c1c52b3696ed.png)

but, in typora dont convert to math symbols

![2017-09-13 5 50 30](https://user-images.githubusercontent.com/11678846/30347748-0a1cb7b2-9848-11e7-85c2-872a10bd664c.png)

**Comment by abnerlee** [comment]
Hi, for block math, please use double "$$"
```
$$
\begin{aligned}  
&Thm \space f:A \to B \space bijective \  
&\iff \exists f^{-1}B \to A \space : \space inverse \space ft \space of \space f \  
&\iff f \circ f^{-1} = I_B \  
&\iff f^{-1} \circ f = I_A \  
&\end{aligned}  
$$
```
currently inline math block with line breakings are not supported
