### ISSUE TITLE
Words are merged when copying text with pictures from Microsoft Word [bug]

### ISSUE THREAD

**Issue by Deivas** [typora/typora-issues#905]
When pasting text from Microsoft Word document containing pictures, some random words are merged throughout the pasted document.

If pasting as plain text - everything is fine.
If copy-pasting from document without pictures - everything is fine.

**Comment by abnerlee** [comment]
@Deivas Hi, if possible, could you attach the sample word file or send ti to us <hi@typora>?

And which OS are you using?

**Comment by abnerlee** [comment]
close because no feedback
