### ISSUE TITLE
'Copy markdown source as plain text' not properly works.

### ISSUE THREAD

**Issue by zondug** [typora/typora-issues#906]
I usually write some texts on markdown editor and copy them to my blog, so I copy texts as plain text then paste on my blog's editor. But always Typora's text is wrapped with a ton of meaningless 'span's like this.

`<span class="md-line md-end-block"><span class="">blah blah original texts</span></span>`

Could you guys remove these?

**Comment by abnerlee** [comment]
OS/Typora version ?

**Comment by zondug** [comment]
Typora is a newest version, and OS is Mac/Sierra.

**Comment by abnerlee** [comment]
Please use `Copy as Markdown`, or set it a default action in preference panel

**Comment by zondug** [comment]
Did you tried to make reappear this situation? It happned even if you checked it.

**Comment by abnerlee** [comment]
Hi, I'm not sure how to reproduce this. I tried 
1. copy in typora
2. paste in plain text editor, like sublime, but only text will be pasted, no "spans"

Could you provide more detailed steps?
