### ISSUE TITLE
Multi line Edit

### ISSUE THREAD

**Issue by justin-qingshan** [typora/typora-issues#907]
Sometimes it needs "alt" key to do multi-line editing, but sometimes it needs both "ctrl" and "alt" keys.

**Comment by abnerlee** [comment]
multi-line editing seems unsupported yet. see https://github.com/typora/typora-issues/issues/1166

**Comment by vertesy** [comment]
multi-line editing would be a very very useful enhancement.

**Comment by pidgeon777** [comment]
I'm also interested in this feature (both text and code editing mode).
