### ISSUE TITLE
Question: Displaying html elements 

### ISSUE THREAD

**Issue by droopy12** [typora/typora-issues#909]
I have some html elements in my documents for example 

```
<table>
    <tr>
    	<td> :dart: This my <a href="https://www.mylink.com">link</a></td>
    </tr>
</table>
```
Typora - 0.9.36 (beta) does not recognize the html parts and treats it as normal text or partially as a code block. Is there any way to overcome that?

**Comment by abnerlee** [comment]
Typora does not support rendering HTML directly, we will just display its raw resource.

"partially as a code block" should be a bug.

For temporary workaround, you may need to keep thems in a line, or remove the indent

**Comment by seamusdemora** [comment]
I'm tempted to ask why you don't support rendering HTML since HTML is incl. in GHM, and you do claim support for GHM... But let's not go there; I suspect the answer will be disappointing. Instead, I'd simply like to ask this, "Are there plans for Typora to properly render HTML embedded in Markdown at some point in the future?"

**Comment by abnerlee** [comment]
> "Are there plans for Typora to properly render HTML embedded in Markdown at some point in the future?"

Yes

**Comment by vassudanagunta** [comment]
@abnerlee speaking of niggles... there are a lot of little ones. so many that i don’t report them as i’m busy. not enough that i don’t stop using Typora, but the kind of thing that will take the shine off, that makes the product feel very beta. I’m sure you’re aware of this. But I wonder whether you are focused on that or more on adding new features.... ?

**Comment by abnerlee** [comment]
Supported in new release
