### ISSUE TITLE
Theme Directory / Repo

### ISSUE THREAD

**Issue by jhildenbiddle** [typora/typora-issues#91]
An official theme site/repo would make finding new themes easier for user and encourage theme authors to contribute. This could be a section of the typora.io website, or simply a GitHub repo. It doesn’t have to be fancy, just something to let people know “this is where you should go for Typora themes”.

**Comment by AlexPasternak** [comment]
Hear hear. This would be very nice to have, although not an urgent / must have, since the themes are user-modifiable. I personally don't have the time though, and would love a darker Github-like theme that's easier on the eyes.

**Comment by aoozdemir** [comment]
I did make a quick github night theme. Mostly the same as github theme's itself.

**Comment by aoozdemir** [comment]
I did make a quick github night theme. Mostly the same as github theme's itself but it works. @AlexPasternak 

https://github.com/aoozdemir/typora-github-night-theme

A github repo or a website for the themes would be nice to have. Also, maybe a documentation for how to make it, tags, classes etc.

Another issue is not seeing the changes (live) you made on theme files. This would help a lot.

**Comment by AlexPasternak** [comment]
@aoozdemir Looks good, nice job!!

**Comment by abnerlee** [comment]
-> http://theme.typora.io
