### ISSUE TITLE
Allow changing default paste

### ISSUE THREAD

**Issue by johntiger1** [typora/typora-issues#911]
I found that pasting in some characters can seriously mess up Typora. For instance, copying characters from an e-mail with stuff like this:
o	uninstall this package: Microsoft.CodeDom.Providers.DotNetCompilerPlatform 
o	uninstall this package: Microsoft.Net.Compilers 

Hence, I would really like the default paste to be text-only, and then I can change it once I want to put in images

**Comment by AlexPasternak** [comment]
There's already a shortcut for Paste as Plain Text (Cmd-Shift-V), and you can remap this to something else if you don't like that one. Not sure about your OS, but you can even use something like BetterTouchTool to remap Cmd-V to plain text paste for Typora only.

**Comment by abnerlee** [comment]
Yes, please see @AlexPasternak 's answer. 

Thank you @AlexPasternak !
