### ISSUE TITLE
It seems that all hotkeys cannot work in ubuntu version.

### ISSUE THREAD

**Issue by superPershing** [typora/typora-issues#913]
I use Typora under ubuntu14.04 LTS, it seems that all hotkeys cannot work in ubuntu version.  I view the `conf.default.json ` and the `conf.user.json` files, `keyBinding` field are empty likes those:
![screenshot-conf default json visual studio code](https://user-images.githubusercontent.com/15770165/30577057-72f18394-9d3e-11e7-9f49-a93c9ff002fd.png)

**Comment by superPershing** [comment]
About serveral months ago, I use Typora under Windows10. No bugs happened like those. Could anybody provide a configuration file under windows to help me to finish the hotkeys configuration in my ubuntu computer?

**Comment by abnerlee** [comment]
may duplicate to 837

It seems the key event will be captured based on system's key binding, without dispatching to menu
