### ISSUE TITLE
Follow relative local links to Markdown files

### ISSUE THREAD

**Issue by phlegmaticprogrammer** [typora/typora-issues#915]
Hi, just started using Typora, very pleased so far. The only thing that really interrupts my workflow though is that Typora cannot follow relative local Markdown links. More concretely, assume I have two Markdown files in the same folder, `Julia.md` and `Types.md` . Now `Julia.md` contains the following markdown:

    The [type system of Julia](Types.md) is very interesting.

The link is shown in Typora, but clicking on it doesn't do anything. I would expect it to follow the link and switch the view to `Types.md`.

**Comment by abnerlee** [comment]
It seems to be a bug if the local link does not work. 

What's your OS ?

**Comment by phlegmaticprogrammer** [comment]
I am using macOS Sierra (10.12.6) and Typora 0.9.9.10.6 

A related thing I am wondering about: How to export a whole directory of markdown to HTML? Here I would expect that the above link to `Types.md` would be converted to a link to `Types.html` within the generated html.

**Comment by abnerlee** [comment]
Hi, in my testing 
```
The [type system of Julia](Types.md) is very interesting.
```

works, 

have you try command+click on the hyperlink?

**Comment by phlegmaticprogrammer** [comment]
Yes, *command+click* or *context menu / open link* follows the link. Thank you for the help! Initially this didn't work as I wanted as `.md` was associated with another program, but once I changed the association to Typora it worked as hoped.
