### ISSUE TITLE
Other language interface?

### ISSUE THREAD

**Issue by pzhaonet** [typora/typora-issues#917]
I am recommending Typora to my friends, because it is the best markdown editor I've ever used. Although I mad some [gif tutorials](http://dapengde.com/archives/19522), some friend still asked me if a Chinese interface of Typora is available. If not, I volunteer to created one, if I know how.

**Comment by abnerlee** [comment]
Thanks, there should be one. we will support in future updates. 

duplicate with https://github.com/typora/typora-issues/issues/142
