### ISSUE TITLE
Feature request: ignore extra words in fenced language tags

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#918]
One difference in how Typora and Github process fenced code blocks is that if Github recognizes the first word of a language tag, it highlights based on it.  Typora, on the other hand, expects the entire string to match.  So if I have code like this:

~~~markdown
```python block 1
def thing(): stuff; return
```
~~~

Then Github will highlight that code block as Python, but Typora will not.  (Having extra information in language tags is often quite useful for metaprogramming and literate programming with markdown.)

**Comment by pjeby** [comment]
Works in 0.9.37.  Thanks!

**Comment by gandalfsaxe** [comment]
@abnerlee 
This is not quite the same syntax (pandoc code fence attributes) that I suggested in #1593? So shouldn't this issue be re-opened then?

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by GandalfSaxe** [comment]
Great! 🎉
