### ISSUE TITLE
please support launching arguments

### ISSUE THREAD

**Issue by lizhuangs** [typora/typora-issues#919]
I add  launching arguments in shortcut on win10.
but I got an error 'can not open file or directory....'
but in other software it works well.
what  launching arguments I add it is ' --disable-directwrite-for-ui --disable-directwrite '.
please support add launching arguments.
Tks

**Comment by abnerlee** [comment]
They can be set in "Advanced Settings" in preferences panel.

**Comment by abnerlee** [comment]
also relates #1999

**Comment by lizhuangs** [comment]
good job!
Tks~
