### ISSUE TITLE
LaTeX rendering quality needs to be improved more

### ISSUE THREAD

**Issue by abnerlee** [typora/typora-issues#92]
From:
https://github.com/typora/typora-issues/issues/81#issuecomment-193241221

> LaTeX rendering quality needs to be improved more:
> 
> ![mathjax](https://cloud.githubusercontent.com/assets/15362491/13570056/f355cb14-e4a6-11e5-923d-f3854b747e53.PNG)
> The picture shows a comparison between Typora's rendering and native webpage rendering of mathjax.
> 
> The latex package support of mathjax can be found there:http://docs.mathjax.org/en/latest/tex.html
> But I'm not familiar with mathjax too.Another solution of latex rendering in webpage/markdown is [KaTeX](https://github.com/Khan/KaTeX), which seems to be faster than mathjax.

**Comment by elizhenning** [comment]
KaTeX is *much* faster than MathJax, BUT the library is a lot smaller, which not a problem for most users, but there will be some users who really need MathJax. MathJax will also render Unicode mathematical symbols (e.g. block 22xx) the same way as it renders LaTeX commands, but KaTex will not. This functionality may or may not be added to KaTeX in the future. For me personally, switching to KaTeX would be a dealbreaker.

**Comment by abnerlee** [comment]
May duplicate with https://github.com/typora/typora-issues/issues/888 and https://github.com/typora/typora-issues/issues/414
