### ISSUE TITLE
Typora swaps contents in the table row.

### ISSUE THREAD

**Issue by riteme** [typora/typora-issues#920]
Hello, I have trouble writing with Typora. I'm using Typora 0.9.**36** (beta) on **Ubuntu** 16.04 LTS. Here's what I did:

1. Open a new file, entering "Source Code Mode".
2. Write down the code:
```markdown
|         |                    |
| ------- | ------------------ |
| $\pi = 3.14159...$ | `cmath` |
```
3. Exit "Source Code Mode" and enter again, you will find the code has changed to somethiing like this:
```markdown
|         |                    |
| ------- | ------------------ |
| `cmath` | $\pi = 3.14159...$ |
```

I don't know what happened, it really troubles me a lot. If it's a bug, I hope it can be fixed quickly. ;)

**Comment by abnerlee** [comment]
Fixed in new release
