### ISSUE TITLE
Automatically Save issue

### ISSUE THREAD

**Issue by heyheyforhello** [typora/typora-issues#923]
There are some confusions with the save function.
I renamed my markdown file, adding a number at the front title. But the file just disappeared with no save.
At the same time, written texts are presented in main page and not saved too.
My texts are written in the file, and I rename it, you remove it, and all my texts are not saved. This is the awful part I met.
I hope you can help me on adding automatically save feature, like word. That's not so hard right.

**Comment by abnerlee** [comment]
OS/Typora versions?

Aslo, you rename the markdown file by external app or by Typora?

**Comment by heyheyforhello** [comment]
It’s windows 10 version. Newest typora.

First, I created the file, and wrote many notes on it.
When I finish the notes, I noticed the name of my document is wrongly spelled, so I just rename it.
Suddenly the file just disappeared, but my notes still exists.
So I just rename it back, and press save.
But typora asks me if I am going to save as, and give me a prompt.
I was confused then, so I choose not to save as another file.
Finally the file didn’t save anything, and the windows just erased.
This logic is awful and I hope you can modify it a bit.

**Comment by abnerlee** [comment]
> When I finish the notes, I noticed the name of my document is wrongly spelled, so I just rename i

You rename it in Typora or in File Explorer ?

**Comment by heyheyforhello** [comment]
I rename it in Typora, when I was editing in Windows 10 platform.

After renaming, the .md extension is wrongly discarded. Then the file disappeared from the Typora folder.
Since the disappearance of the file, texts in editing window didn’t disappear, rather the contents were saved in window. This resulted in confusions.

**Comment by abnerlee** [comment]
please reopen this if it still happens in new release
