### ISSUE TITLE
Duplicated application name shown in Alfred 

### ISSUE THREAD

**Issue by evanzhu2013** [typora/typora-issues#924]
<img width="634" alt="2017-09-25 10 41 26" src="https://user-images.githubusercontent.com/7533756/30790927-a8d30dbe-a1e1-11e7-9d4a-d30c3fb176c4.png">

Typora is  a great application. Thanks for your work.

**Comment by abnerlee** [comment]
Do you have both Typora.app and typora.app under `/Applications`?

If not, this is alfred's bug. Most macOS use case-insensitive file system, so alfred shouldn't list both `typora.app` and `Typora.app`. Please try contact them ~
