### ISSUE TITLE
File tree does not support folders with dots e.g. /version/1.4

### ISSUE THREAD

**Issue by jneale** [typora/typora-issues#927]
When viewing the Files tree, folders that contain a dot in their name are not displayed.
(Windows 10 64 bit -> Typora 0.9.37 (beta)

![typora-issue-folder-dot](https://user-images.githubusercontent.com/1355440/30811516-5d0a040e-a200-11e7-8cbb-bcd69ab40f1c.png)

**Comment by abnerlee** [comment]
should be fixed in new release
