### ISSUE TITLE
Update fails and breaks Typora (Windows 10)

### ISSUE THREAD

**Issue by aaossa** [typora/typora-issues#928]
**OS:** Windows 10
**Typora:** 0.9.36

**What I did:**
- Check Updates
- Download new version
- \*Typora fails to create new Typora.exe\*
- Retry
- \*Same error\*
- Abort
- Working Typora.exe disappears and had to manually delete files
- Install new version manually :cry: 

---

I was using Typora 0.9.36 and wanted to update my version because a while ago a pop-up suggested it. I checked for updates, Typora downloaded 0.9.37(beta) and then threw an error saying that was unable to create `Typora.exe` because there was already a file with that name. I retried, didn't work, then I tried aborting and Typora stopped working because it deleted `Typora.exe`. After that, I had to manually install the newest available version. 

Did this happen to somebody else? (hope not, Typora is great) Anything I could do? If you need more information I'll be ready to provide it.

**Comment by tribpot** [comment]
Same issue here - unable to copy a new file over one with the existing name.  I couldn't uninstall either (uninstalled once and so I have uninstall file to run) and can't delete the folder in C:\Program Files because it says access is denied - even when I run as administrator.

**Comment by abnerlee** [comment]
The updater should tell you to exit Typora. Does it?

**Comment by tribpot** [comment]
I think it did originally, @abnerlee - and I exited from Typora but it seems to have got itself into a bit of a mess and I can't fix it by deleting the folder because of the permissions issue.

Incidentally, I have sort of fixed it for now by downloading the other Windows version, i.e. the 32 bit one in this case.

**Comment by abnerlee** [comment]
caused by https://github.com/typora/typora-issues/issues/873

**Comment by aaossa** [comment]
That's not the issue I described, I don't think that the issues are related

**Comment by abnerlee** [comment]
I haven't met the error `Typora fails to create new Typora.exe`, did you exit typora successfully when the installer.exe is running?
