### ISSUE TITLE
where to control outline level?

### ISSUE THREAD

**Issue by happywmzzz** [typora/typora-issues#929]
very cool app, thank you~~

i know how to control toc level, however, i want to control outline level either.

**Comment by abnerlee** [comment]
There is no syntax in markdown to control toc levels. You could do it by tweaking the CSS -> http://support.typora.io/TOC-levels/

**Comment by happywmzzz** [comment]
I know this toc level
however, I am asking the outline in left side

**Comment by happywmzzz** [comment]
![qq 20170928163141](https://user-images.githubusercontent.com/23254535/30957609-531d57d8-a46d-11e7-8c87-5408d7c97f31.png)

**Comment by abnerlee** [comment]
I do not provide such option. You could enable "Collapsible Outline Panel" if you think the outline panel is too detail, or use custom css to hide low level items
