### ISSUE TITLE
About the .gif picture preview performance

### ISSUE THREAD

**Issue by CharlesLiuyx** [typora/typora-issues#932]
Could you to add a switch to turn off the .gif preview because if I import pictures with .gif format my computer will continue rendering them leading to the energy cosuming and hardware hotting!Really Really Hot

Mac Client(Mac 2016 pro with touch bar)
Lastest Version Typora Client

**Comment by abnerlee** [comment]
> if I import some picture with .gif format my computer will continue rendering them leading to the energy cosuming and hardware hotting!Really Really Hot

This seems to be a bug if .gif eat so such energy

**Comment by CharlesLiuyx** [comment]
Additionally, I insert 10 Gif image in one article, that could be the key point maybe

**Comment by abnerlee** [comment]
Should be fixed already
