### ISSUE TITLE
0.9.37 destroys file creation date info, ACLs/security permissions, etc.

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#933]
I use file creation timestamps for various purposes, which Typora used to leave alone when saving files.

Now, Typora apparently creates new files on every save, losing the timestamp and any Windows permissions info.  This means Typora can't be used to edit anything with non-default security permissions on Windows without erasing them.

(I don't know if this does the same on non-Windows platforms, but if so then xattrs, acls, and other filesystem metadata is being lost there as well.)

**Comment by pjeby** [comment]
Further investigation reveals the culprit to be the node.js "steno" module's writeFile; replacing it with standard `fs.writeFile()` fixes the issue.  There are two things that `steno` provides that `fs` does not:

* Avoids the possibility of doing another disk write while the first is in progress (by finishing the first before it starts the second)
* Handles the case where the file write fails partway through, preserving the old file

The second feature only helps in pathological situations (lost connection, bad disk, disk full) where an error is sufficient to alert the user so they can try again or save the file elsewhere.  And the first feature is only relevant if Typora doesn't have its own way of preventing overlapping saves...  but is probably irrelevant anyway, because steno's not preventing the `willSave` and `didSave` events from overlapping.  (That is, the current code can issue two `willSave` events followed by two `didSave` events, if `saveUseNode()` is called a second time before the first is finished.)

I *did* see an `inSavingProcess` flag that might be relevant, but I couldn't tell if it was actually preventing `saveUseNode()` from being called before the first call finished.

If it *is* preventing it from being called, then there is no race condition on saves, and steno doesn't help.  Conversely, if it is *not* preventing it from being called, then there *is* a race condition on saves, and steno still doesn't help.  :)  So, either way, steno is not helping to prevent race conditions in Typora; all it can do is prevent a race on the actual disk write, and if the higher-level race is prevented, there is no disk-writing race to prevent.

So, either way, Typora can probably do without the steno module and just use regular `fs.writeFile`.  If it's necessary to prevent overlapping saves, that has to be prevented at a higher level, e.g. by having `saveUseNode()` notice that `inSavingProcess` is true and either wait or trigger an error or something.

I have replaced "steno" with "fs" in my copy and am testing it; so far it appears to fix the new-file-creation issue without breaking anything else, which rather makes sense since steno isn't preventing any application-level race conditions on save.  I just don't know if there *are* any such races, having only a limited ability to decipher minimized code.  ;)

**Comment by abnerlee** [comment]
"steno" is used to prevent crashing in middle of a saving process, I never met this, but I used to got report from other users.
So we want to implement a similar process like emacs (https://www.gnu.org/software/emacs/manual/html_node/emacs/Backup.html), or the usual save process of macOS Apps. But we did ignored the attribute thing when choosing steno. 
We we will fix it by copying the original file to tmp file. update the tmp file, and then rename it back.

But race condition, when "writing" file, the file will be locked or "occupied" in most cases, so if typora failed to save the file because of a race condition with other process, it just fail and show an error dialog, which is OK as it is a rare case.

**Comment by pjeby** [comment]
Updating a tmp file and renaming it back is what *steno* is doing *now*, which is what creates the bug.

Making a backup copy is great, but then you still have to overwrite the original file to leave all the attributes alone.

Either that or you have to clone all the security attributes, which you can't necessarily _do_ if the user isn't root or a Windows administrator.

(Speaking of which, the user may have permission to write to the file, but not to create new files in the directory...  so you might have to make the backup somewhere else to begin with...)

**Comment by abnerlee** [comment]
should be fixed in v0.9.38
