### ISSUE TITLE
full-text search in directory

### ISSUE THREAD

**Issue by nnals** [typora/typora-issues#936]
hello,

is it somehow possible to perform a full-text search in (all files of) the current directory?
if not, are there any plans to add this feature?

thanks,
nicolai

**Comment by abnerlee** [comment]
We plan to support this in feature.

And I will close this since it is a duplicated request

**Comment by JCWDFCS** [comment]
waiting---

**Comment by necan** [comment]
still waiting

**Comment by cybertahr** [comment]
waiting for this feature~

**Comment by ngloom** [comment]
waiting :)

**Comment by xqlip** [comment]
waiting.

**Comment by petitlen** [comment]
waiting for a years.....,still not support....
