### ISSUE TITLE
It seems that I can't see subfolders in the folder if the folder only has subfolders.

### ISSUE THREAD

**Issue by jefffffrey** [typora/typora-issues#937]
![image](https://user-images.githubusercontent.com/19466181/30998142-10eda9d4-a4ff-11e7-94bc-aa675994de7e.png)

This is the file hierarchy:

```markdown
django
├── DjangoBook-1.8.13
│   ├── Auth.md
│   ├── Chapter 1_Getting Started.md
│   ├── Django Forms.md
├── DjangoDoc-1.10
│   ├── Django documentation contents.md
└── Django-总结-1.8.13
    ├── demos.md
    └── middleware.md
```

MyTypora version is `0.9.37`.

**Comment by jefffffrey** [comment]
Hahaha, I find the reason is that the subfolder's name contains `.`. Is this a bug?

**Comment by abnerlee** [comment]
It's a bug, see https://github.com/typora/typora-issues/issues/927
