### ISSUE TITLE
Some characters disappeared after inline math

### ISSUE THREAD

**Issue by poerin** [typora/typora-issues#939]
for instance, when you type "$x$，，，。。。", "，，，。。。" will disappear, but when you type "$x$,,,...", everything is right.
Don't type `Enter` in the end, just let the focus losing.

**Comment by chenwq3** [comment]
![version1607buildversion14393 1066](https://user-images.githubusercontent.com/25943138/32259465-ac7e9d20-befb-11e7-9d3f-93329266ed02.gif)

以前这个现象更明显，好像会直接吃掉标点符号，现在只有通过鼠标，或者键盘方向键离开那个位置才会发生。

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/172
