### ISSUE TITLE
Open Recent list lost on app restart

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#94]
- File > Open an .md file
- Observe that File > Open Recent shows the file just opened
- Quit the app
- App reopens with a blank document in the same window spot as the previous file, but the previous file is not reopened, even though it was open at app quit
- File > Open Recent does not show the file from the last session

Typora 0.9.8.8
Mac OS X 10.10.5

**Comment by waahto** [comment]
Same here, but might this actually be due to OSX? I've noticed that a few of my other programs does this as well from time to time. Restart helps, for a while at least. Have you tried, because I can't replicate this.

Typora 0.9.8.8
OSX 10.11.3

**Comment by AlexPasternak** [comment]
A computer restart did seem to make a difference for now, and I am seeing files persist in MRU list between app restarts. I can believe it's an OS issue, but I haven't noticed this in other editors like TextMate.

**Comment by abnerlee** [comment]
I'll close this issue, since it is an OS issue
