### ISSUE TITLE
Issue with Export as PDF

### ISSUE THREAD

**Issue by fksad** [typora/typora-issues#941]
my system is Win10(15063.608) and typora version is 0.9.37(beta). After export a markdown file as pdf，its format had changed. The words and codes were divided into different pages in the pdf file, leaving some pages contain only one line.
md file
![image](https://user-images.githubusercontent.com/10517914/31043849-d3644d14-a5f5-11e7-908d-eac12b42433c.png)
pdf file
![image](https://user-images.githubusercontent.com/10517914/31043861-0583a326-a5f6-11e7-8635-8d2bd38c94bf.png)

**Comment by breezepqf** [comment]
l have also met the problem. export the md with HTML then open it with chrome,then use the print func of chrome and choose a larger size paper such as A3 ,then it will big enough to fit the code block.And l alse want to know if there is a better way such as change the css of theme.

**Comment by abnerlee** [comment]
We will fix this. One hot fix is to add custom css:
```css 
.md-fences {
    page-break-inside: unset;
}
```

**Comment by abnerlee** [comment]
fixed in new release
