### ISSUE TITLE
When not in souce code mode - once header applied, can no longer modify it. 

### ISSUE THREAD

**Issue by idvorkin** [typora/typora-issues#942]
In **non** source code mode, once I make a heading e.g: 

     # hello

I can't go back into the heading and remove the opening # to make it no longer a heading, or return to the header to add a second # to making it a heading 2.  

This works correctly for bold, list, etc.

**Comment by vassudanagunta** [comment]
In Preferences : Editor, check `Display source for simple blocks on focus`.  

Your other options are to use the many commands in Paragraph menu to change the heading level or remove it, or any of the keyboard shortcuts shown there. 

(@abnerlee, if you resolve #285, then you could enable `Display source for simple blocks on focus` by default and we'd have the best of both worlds (WYSIWYG + Markdown).

**Comment by idvorkin** [comment]
Sweet - love the product by the way.
