### ISSUE TITLE
Trailing blank lines deleted from fenced code blocks on file load

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#945]
When you load a file with a fenced code block that ends with a blank line, it is removed.  If multiple blank lines are present, only one is removed, but the next time you load the file another one will be removed.  Typora should not make changes to file contents that alter the semantics of the resulting markdown document (nor should it silently change file contents in general).

**Comment by vassudanagunta** [comment]
Whatever you do, please make sure default behvior conforms with CommonMark/GFM (per issue #369).

**Comment by pjeby** [comment]
Er, I don't see what this has to do with CommonMark or GFM or indeed any markdown syntax.  This is an issue of the editor silently altering the text of the file, not an issue with rendering.

**Comment by vassudanagunta** [comment]
You're right. I misread your issue.

**Comment by abnerlee** [comment]
should be fixed in new release
