### ISSUE TITLE
when I screenshot an image to the clipboard on Mac I can't paste it into typora

### ISSUE THREAD

**Issue by murrayLuke** [typora/typora-issues#946]
# Steps to reproduce

1. Take a screenshot to the clipboard using one of the two default screenshot shortcuts

ctrl - cmd - shift - 4 . (region of the screen)
ctrl - cmd - shift - 3 . (entire screen)

2. In finder go to the help menu and type "show clipboard"

You can then assert that the clipboard contains the image that you took.

3. Paste the image into typora

Nothing will show up. The image will show up if pasted into other applications however.

## Why this matters

I often take notes on lectures or other documents, and want to reference portions of them through a screenshot. I can drag and drop screenshots if I store them in a file but I would rather skip that step and have a smooth workflow through my clipboard.

Again thank you for everything you do with typora. It's a lovely editor.

PS. If someone can explain where the image paste code is written I can try to look at it myself.

**Comment by AlexPasternak** [comment]
This works and is not an issue, please follow steps in http://support.typora.io/Images/#paste-images-from-clipboard

Your file has to be saved and then you specify a relative path. Then you can paste region of screen, I just did this to confirm.

![untitled 2](https://user-images.githubusercontent.com/1819485/31182093-f44043c8-a8f0-11e7-8b6d-f9bc1b1396b2.png)

**Comment by murrayLuke** [comment]
Thank you very much that has solved this. Typora proves to be an excellent system.
