### ISSUE TITLE
File tree should drive tabs, not other way around

### ISSUE THREAD

**Issue by darobin** [typora/typora-issues#949]
When I write it is rarely just one document, but often a complete directory tree of documents with several open in parallel — very much like writing code. The current interaction between the file tree and the tabs is not very helpful for this usage: when you open a new tab it does not have the same file tree context; when you click a file in the tree it replaces the current tab instead of opening a new one.

I would like a file tree that works like the file drawer in Atom (and countless other places). Click on a file there and it opens in a new tab without replacing the current one. Have some shortcuts to add/rename/remove while focused on the drawer, etc.

PS: if there's a way to buy a license or whatever to support your work on this, I'd be happy to.

**Comment by abnerlee** [comment]
Typora is a writing tool not a code editor like atom, so we do not want "Click on a file there and it opens in a new tab" like a code editor by default.

But cmd+click can open the file in new window/tab, can this solve your problem?

**Comment by darobin** [comment]
I understand that it is not a code editor, but a lot of writing — at least writing that is more complicated than just a simple README — happens in projects and not just in single files. For anything long there might be different chapter files. For a documentation project there will often be lots of separate files as well. One needs to go back and forth between different documents because they are related. Right now it doesn't even seem to be possible to open a file in a new tab from the file listing.

I get a sense that Typora endeavours to be more useful than just a README/blog post editor, which is why I'm bringing this up.

It's not clear to me how the Cmd-Click helps. I've tried but all it does is open a new window. Just like for browsers, having every different item in a separate window is really hard to manage. I need to do things like quickly go back and forth between two chapters to make sure they align well, split a documentation page into several parts that I need to edit jointly for a while to make them coherent, frequently jump over to the glossary page and back — in other words, writing stuff. I like a good writing tool with a simple UI like Typora, but that's usable for a bit more than small things.

Thanks!

**Comment by abnerlee** [comment]
> It's not clear to me how the Cmd-Click helps. I've tried but all it does is open a new window.

Yes, this will open new window, but, if the window already use tabs, a new tab will be opened. you could toggle the tab view by cmd+shift+T

------------
I can understand your requirements on writing a large project with multiple docs, we will try starting from simple improvements, like give options to open in new tab by default, etc

**Comment by abnerlee** [comment]
Move discussions to https://github.com/typora/typora-issues/issues/1000
