### ISSUE TITLE
regression: Default filename logic fails in the presence of YAML front matter

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#952]
At some point after Issue #148 was fixed the buggy behavior was re-introduced.

From #148: 

> Normally Typora automatically uses the first paragraph as the default filename when saving a file. But if there is YAML front matter (i.e. at the beginning of the doc), the default filename is simply a "-".
>
> YAML front matter or any other metadata should be ignore by the default filename logic.

Except now the default filename is `Untitled.md`

Strangely this is the second time this regression has occured: #716.

**Comment by vassudanagunta** [comment]
Maybe consider fixing all the open auto/default filename issue in one go? See #934 and #935.

**Comment by abnerlee** [comment]
In my testing 
```
---
title: aaa
---
```

still works, the default file name when saving is "aaa", so what is the bug?

**Comment by vassudanagunta** [comment]
Works:
``` markdown
# aaa
```

Works (`bbb` takes precedence over `aaa`):
``` markdown
---
title: bbb
---

# aaa
```

Does not work:
``` markdown
---
tags: test
---

# aaa
```

**Comment by abnerlee** [comment]
```
---
tags: test
---

# aaa
```

Got it.

**Comment by abnerlee** [comment]
fixed in new release
