### ISSUE TITLE
Add ability to re-order list items.

### ISSUE THREAD

**Issue by idvorkin** [typora/typora-issues#954]
Typora supports S-Tab/Tab to indent and un-indent lists items, which is a great feature.  Another powerful list keyboard shortcut is re-order items.  This feature existing in powerpoint, onenote, and bear. 

In windows the keyboard shortcut is A-S-Up and A-S-Down.

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/151
