### ISSUE TITLE
A problem at displaying font

### ISSUE THREAD

**Issue by JChiron** [typora/typora-issues#956]
win10 1703
0.9.37(bate)

The font is very bad on Typora editor when I use fixedsys (http://www.fixedsysexcelsior.com/). But it`s no problem at Linux.

**Comment by abnerlee** [comment]
@JChiron can you use fixedsys with Chrome on Windows10, does it works normal?

**Comment by JChiron** [comment]
win10 1703
0.9.37(bate)
@abnerlee  Yes. Other editor or browser is normal, but typora.

**Comment by abnerlee** [comment]
Did you try follow http://support.typora.io/Custom-Font/ ?

**Comment by JChiron** [comment]
![new bitmap image 2](https://user-images.githubusercontent.com/25954976/31373203-bbdd284a-adcb-11e7-83b7-6f18cf5d1a82.png)
![new bitmap image](https://user-images.githubusercontent.com/25954976/31373204-bc2c961e-adcb-11e7-98a5-6f0478d2503e.png)

   @abnerlee It`s no problem in your computer?

**Comment by JChiron** [comment]
It maybe be 17px In win10-Typora when I use `font-size: 16px`. 
now it is normal in win10-Typora idetor when I use `font-size: 15px`. but just in win10-Typora idetor.
it is 15px when I export it as html. 

but the font only support 16px, that is perfect size for it.

So, I think that display size of font is a bug. 

Thank Typora!

**Comment by JChiron** [comment]
@abnerlee
It maybe be 17px In win10-Typora when I use `font-size: 16px`. 
now it is normal in win10-Typora idetor when I use `font-size: 15px`. but just in win10-Typora idetor.
it is 15px when I export it as html. 

but the font only support 16px, that is perfect size for it.

So, I think that display size of font is a bug. 

Thank Typora!

**Comment by abnerlee** [comment]
> but the font only support 16px, that is perfect size for it.

If that is the reason, could you try set font-size to 16px? e.g.

#write {
  font-size:16px !important
}

**Comment by JChiron** [comment]
@abnerlee  it is failed!  
> #write
It can`t set default size.

**Comment by abnerlee** [comment]
@JChiron could you do like following?
1. write something in Typora
2. export it into a html file using typora
3. open it in chrome and see if the font-size/font-rendering is correct or not
4. also, send the html file to us <hi@typora> so we can check it.

**Comment by JChiron** [comment]
@abnerlee 
Ok. To be sent already!

**Comment by abnerlee** [comment]
see mail discussion
