### ISSUE TITLE
Hide comments in Preview mode

### ISSUE THREAD

**Issue by reflectionalist** [typora/typora-issues#957]
Please provide an option to hide comments inserted in Source mode using the syntax `<!-- ... -->` in Preview mode.  I use Typora for presentation, being able to hide comments is highly useful in this case.

**Comment by abnerlee** [comment]
We do not have plans for this since we allow users to edit in preview mode, and there no ways to edit "hidden" text.

------

you could try add custom css -> http://support.typora.io/Add-Custom-CSS/
```css
.md-comment {
display: none
}
```

**Comment by reflectionalist** [comment]
Thanks, the custom CSS trick works.

**Comment by sivachandran** [comment]
Does this still work? 

I see the commented block even after adding the above CSS. I enabled debugging and I see the commented block lines are rendered as multiple paragraphs(p) and they don't have `.md-comment` class associated with them.

**Comment by sivachandran** [comment]
The CSS works if there are no blank lines within the comment block. Seems like comment block with blank lines are rendered differently.
