### ISSUE TITLE
The window of Typora lost on Windows

### ISSUE THREAD

**Issue by yodahuang** [typora/typora-issues#958]
I occasionally connect monitors to my laptop. Recently I found that when I open Typora, it shows up in Task Bar, and I can see the interface through Windows Peek, but  I don't see the interface showing up noramlly.

I tried "Cascade Windows" or "Show Windows Side by Side", which does not help. I also tried uninstall and install again, does not work too.

I some situations when I click the icon in Taskbar, I can see a quick animation showing that the window is opened to somewhere far left to my monitor.

**Comment by abnerlee** [comment]
This should be a bug, you could remove `profile.data`, `profile.typl` and profile.data in` C:\Users\{user}\AppData\Roaming\Typora` and then open typora?

maybe use https://github.com/mawie81/electron-window-state can solve this

**Comment by cq674350529** [comment]
It works. Thanks! @abnerlee

**Comment by abnerlee** [comment]
fixed in new release
