### ISSUE TITLE
PDF Does not Export Sequence Diagram correctly

### ISSUE THREAD

**Issue by ikelaiah** [typora/typora-issues#959]
Thanks for Typora.

## Problem
Typora does not constraint a sequence or a diagram to the length of a page.
I'm using Windows 8.1 and Typora v 0.9.37

## How to reproduce
To reproduce,  use the following code to draw and print to PDF
```sequence
System A->System B: Hey!
System B -> System D: Test!
System D-> System E: Testing!
System A -> System F: Testing!
System F-> System G: Testing!
System B-> System Z: Testing!
```

## Result
I get the following result, System G got cropped out;
![for-typora](https://user-images.githubusercontent.com/32469901/31322546-909c170e-ace5-11e7-8f0e-4e82d800d579.png)

**Comment by abnerlee** [comment]
should be fixed in new release
