### ISSUE TITLE
No prompt when closing an edited file

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#96]
Open `x.md`
Type something
Hit `cmd+w`
The window closes, does not ask to save, cancel or discard changes.
Open `x.md`
The changes have been saved.

This is non-standard behaviour and should not happen. Typora should *always* ask before closing an edited file that has not been saved.

Typora 0.9.8.8
OSX 10.11.3

**Comment by abnerlee** [comment]
> Open `x.md`
> The changes have been saved.

So the change has been saved or not?

**Comment by waahto** [comment]
Saved. Should prompt, not save automatically.

**Comment by AlexPasternak** [comment]
@waahto You're completely wrong that this is non-standard behavior, perhaps you're new to Mac. The feature is called Auto Save and it's been there since OS X Lion.

https://support.apple.com/en-us/HT202255

**Comment by waahto** [comment]
I'm not new to mac that doesn't make me right :) I have been utterly, completely and miserably wrong for all these years! Though it doesn't seem to work in all my programs... Feel free to close this, @abnerlee.

**Comment by abnerlee** [comment]
This seems to be the auto-save feature, so I will close this
