### ISSUE TITLE
File Tree files order

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [typora/typora-issues#961]
Hi, What is the default order of files in file tree? by name or by modified time? Can you add an option to  order it by time descent?

**Comment by abnerlee** [comment]
By name, or actaully "natural" sort (https://en.wikipedia.org/wiki/Natural_sort_order)

Sort by date is supported as one option in file **list** view.  We are less likely to provide other sort functions in file **tree** view, since the priority may not be high.

**Comment by Narno** [comment]
Hello @abnerlee,

> Sort by date is supported as one option in file list view.

By "**files** list view" you mean "**articles** list view", right? :-)

Thanks.

**Comment by abnerlee** [comment]
> By "files list view" you mean "articles list view", right?

Yes.

**Comment by Narno** [comment]
:+1:
