### ISSUE TITLE
Wrong line ending of YAML front matter on Windows

### ISSUE THREAD

**Issue by zhaobenx** [typora/typora-issues#962]
Typora version: 0.9.37(beta)

On windows system, the default line ending is CRLF, however, when you typing something in YAML front matter, those are ended with LF, while the other part of the file are still enden with CRLF. So git would report a warning about the different ending in the file.

**Comment by zhaobenx** [comment]
![screenshot](https://user-images.githubusercontent.com/23143530/31367950-2d7754cc-adad-11e7-8b8f-44ae9bbf8e7d.png)
This is the screenshot

**Comment by abnerlee** [comment]
fixed in new release
