### ISSUE TITLE
Opening folder from command line fails if there is a trailing slash (Windows)

### ISSUE THREAD

**Issue by fenduru** [typora/typora-issues#963]
I've requested that Github Desktop support Typora as one of its external editors, however it is required that the program can open a folder. Is there an existing way to launch Typora with a folder similar to how you can launch it with a file? I would imagine this would also be useful for people to create desktop shortcuts to a particular folder as well.

https://github.com/desktop/desktop/issues/3015

**Comment by fenduru** [comment]
@abnerlee thanks - I actually figured out that the problem was that typora does not handle trailing slashes on directory paths and pops open an `ENOENT: so such file or directory` error dialog

**Comment by vassudanagunta** [comment]
@fenduru you probably should change the title of this issue.

**Comment by abnerlee** [comment]
fixed in new release
