### ISSUE TITLE
Emoji short-codes are out-of-date

### ISSUE THREAD

**Issue by Crissov** [typora/typora-issues#964]
There are several slightly different conventions for emoji "shortcodes" (e.g. [Gemoji](https://www.webpagefx.com/tools/emoji-cheat-sheet/) vs. [Emojione](https://emoji.codes/)), i.e. the English keywords enclosed in colons. I don't know which library you are using, but it is obviously severely outdated because these are not supported, for instance:

- :spider: `:spider:` Unicode 7.0 (2014)
- :unicorn: `:unicorn:` Unicode 8.0 / Emoji 1.0&ndash;2.0 (2015)
- :duck: `:duck:` Unicode 9.0 / Emoji 3.0&ndash;4.0 (2016)
- :giraffe: `:giraffe:` Unicode 10.0 / Emoji 5.0 (2017), not yet supported by Github either

**Comment by abnerlee** [comment]
updated the emoji lib in new release
