### ISSUE TITLE
Outline pannel remains white after switching to "Night" theme.

### ISSUE THREAD

**Issue by wtdcode** [typora/typora-issues#965]
I have just updated my typora to 0.9.23, and it seems that the background color of the outline pannel goes wrong.
![snapshot](https://user-images.githubusercontent.com/30623163/31582006-ed7dca5c-b1aa-11e7-8a61-cec22009c956.png)

**Comment by abnerlee** [comment]
version 0.9.23 is too old...

**Comment by wtdcode** [comment]
@abnerlee In fact, 0.9.23 seems to be the latest build downloaded from official site. I have just updated my Tyopra throung "Check updates" in preferences. The bug disappears.
