### ISSUE TITLE
The text shakes when typing near the last line of current page

### ISSUE THREAD

**Issue by wtdcode** [typora/typora-issues#966]
![t](https://user-images.githubusercontent.com/30623163/31582418-9a93429a-b1b4-11e7-9ef2-abaa53060517.gif)

In fact, when typing or deleting any character **at the beginning of the last line**, it shakes.

**Comment by abnerlee** [comment]
What's your typora and OS version?

**Comment by wtdcode** [comment]
@abnerlee In fact, 0.9.23 seems to be the latest build downloaded from official site. I have just updated my Tyopra throung "Check updates" in preferences. The bug disappears.
