### ISSUE TITLE
typora 0.9.9.10.8 paragraph issue(macbook  with touch-bar)

### ISSUE THREAD

**Issue by zsfblues** [typora/typora-issues#967]
I found a problem about function button display in touch-bar(macbook pro 2017)，the button only show the half size of button. like this  
![261508076027_ pic](https://user-images.githubusercontent.com/9928627/31585532-f519d282-b188-11e7-9ca5-70d6e2fd700a.jpg)  so what's the problem??

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/681

But I still cannot reproduce this
