### ISSUE TITLE
Source Code Mode and redacted newline

### ISSUE THREAD

**Issue by zfreeindeed** [typora/typora-issues#968]
When creating an outline for a document in source code mode, I have been inserting a newline as a placeholder for text that will be entered after the base outline is created.
When I switch out of source code mode, this additional newline is removed and can only be permanently inserted from the interpreted UI. I confirmed this by switching back to source code mode and saw the additional newline was missing. Here is the format example of what I am talking about:

<pre><code>## Heading 2
### Heading 3 - A

----
### Heading 3 - B</pre></code>

After moving to interpreted UI, this section loses the newline where you could begin typing for the section and becomes the following when looking at it again in source code mode:

<pre><code>## Heading 2
### Heading 3 - A

----
### Heading 3 - B</code></pre>

Thanks!

**Comment by abnerlee** [comment]
line break will not be kept when rendering markdown, in github, it renders like:

## Heading 2
### Heading 3 - A

----
### Heading 3 - B

In Typora, two line break will be rendered as one paragraph.
