### ISSUE TITLE
EINVAL: invalid argument, fstat

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#972]
**OS**: Windows 10 16299.19

Whenever I try to open a document from OneDrive, I always get the error:

"Failed to Load File - EINVAL: invalid argument, fstat"

My document locations are at `C:\Users\[USER]\OneDrive\`. Any clue?

**Comment by abnerlee** [comment]
See https://github.com/Microsoft/vscode/issues/27285

We will fix this by updating Electron

**Comment by lloyd094** [comment]
That would be great, thank you!

**Comment by yaohwu** [comment]
Same error. Waiting fix

**Comment by sdygt** [comment]
Same here, Windows 10.0.16299.19, OneDrive 17.3.7073.1013

**Comment by WeiqiChenCN** [comment]
I just Updated my Windows 10, and Now I got the same error here.

**Comment by abnerlee** [comment]
should be fixed, please update to v0.9.38
