### ISSUE TITLE
File tree isn't sorted in alphabetical order

### ISSUE THREAD

**Issue by xanderberkein** [typora/typora-issues#973]
When I open Typora, my files in the File Tree aren't properly sorted. I would expect them to be sorted alphabetically, but they always appear in this order:
![image](https://user-images.githubusercontent.com/10937632/31662816-36679ea0-b340-11e7-9cd7-c2252e75f49c.png)
The order seems random (it's not sorted by date either), but they consistently appear in the same "random" order.

Sometimes, while editing a document and saving it, the documents in the same folder jump positions and become sorted alphabetically, but I can't reliably reproduce this behavior.

I'm on macOS 10.13.

**Comment by TechIsCool** [comment]
From what I can tell when using the file explorer it based on edit time.

**Comment by xanderberkein** [comment]
It doesn't seem to be based on edit time, since the files always appear in the same order, no matter the edit time of the files.

I am able to change the order of the File List (Articles View of the sidebar), but not in the File Tree, like in my screenshot above.

**Comment by JCWDFCS** [comment]
have suffered for a month :-

**Comment by abnerlee** [comment]
fixed in new release
