### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kakaes** [typora/typora-issues#974]
This has been touched on in other threads (on performance) but not addressed directly. In my case performance is fine--I've got a macbook pro, with 16 GB of memory. But even for a very small file (one that starts blank and grows to say a few thousand words) Typora will take up to 400 MB of working RAM. This seems crazy to me, and wonder if there's some sort of memory leak? I like it far more than other markdown editors out there--design is nice and the outline sidebar is very convenient for note-taking. But seems nuts to take 400 MB of ram to edit a text file of (real exampe) 2800 words?

Running El Capitan 10.11.6

Was wondering if any of you might have any insight as to what's going on?

**Comment by abnerlee** [comment]
Typora use webview, so the memory usage is larger than native text editors. But I do not think there's critical money leak given that Typora use 400md moneris on a 16G macbook

**Comment by kakaes** [comment]
Abner--

Just curious if you can give more insight. As a first principle, seems insane to me that a text editor would take 20,000 (Twenty-thousand!) times as much memory as the file itself (just checked and the file in question is 20 kilobytes) to edit the text and do some formatting. Maybe this is the fault of webview and not the Typora code. But simply saying "no problem here"! seems peremptory.

**Comment by abnerlee** [comment]
Hi kakaes, sorry for letting you feel peremptory somehow.

Typora does not only load the file into money, also itself, linked libraries, caches, etc. You could try open this page in Safari, and check the memory usage of Safari, it would cost those money for a webview. And markdown will be previewed in a webview.
