### ISSUE TITLE
Provide RPM and/or a tar.gz archive

### ISSUE THREAD

**Issue by keeferrourke** [typora/typora-issues#975]
At https://typora.io/#download, clicking on the "Linux" button simply redirects to a page with instructions for adding an Ubuntu apt repository. This is insufficient.

There are many different Linux distributions which use different package management systems. Typora should at a minimum provide *.deb, *.rpm and *.tar.gz packages in order to be usable.

Can't use your software if you don't provide a package for it.

**Comment by abnerlee** [comment]
see http://support.typora.io/Typora-on-Linux/

**Comment by keeferrourke** [comment]
This issue should *not* be closed. You are making your software only available on Debian-based distributions. This issue is about at least making it possible to manually install your software on other Linuxes.

**Comment by abnerlee** [comment]
see http://support.typora.io/Typora-on-Linux/ it contains download link for binary builds
