### ISSUE TITLE
need Show/Hide Sidebar menu command and shortcut

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#977]
Typora has menu items and shortcuts for showing/hiding 3 types of sidebar, but doesn't have a generic Show/Hide Sidebar command as most apps have (see below). Note that Safari, like Typora, has multiple types of sidebar and has a generic command for showing/hiding the sidebar along with commands for each type. 

app | Show/Hide Sidebar | Show/Hide by type
------------ | -------------|---------
Finder | ⌥⌘S | 
Safari | ⇧⌘L |   Bookmarks Sidebar ⌃⌘1 <br/> Reading List Sidebar ⌃⌘2
Reminders | ⌥⌘S | Calendar ⌥⌘K
iTunes | ⌥⌘S | 
Photos | ⌥⌘S | 
Typora | (missing)  |   Outline ⇧⌘B  <br/> Articles ⇧⌘L   <br/>  File Tree  ⇧⌘E

### Recommendation

1. Add a `Show/Hide Sidebar` to the View menu, just above the Outline command in the same grouping. 
2. Give it the `⌥⌘S` keyboard shortcut to be consistent with other apps.
3. All three commands update their menu text depending on sidebar state (see Safari behavior)
4. `Show Sidebar` will show the last type of sidebar that was shown.

**Comment by vassudanagunta** [comment]
I was also thinking the names for the sidebar types should be better, with easier to remember shortcuts,  and use `Show/Hide` in their names as Safari and Reminders do for sidebar types.

bfore | after
------------ | ------------
Outline ⇧⌘B  |  Show/Hide Outline ⌃⌘O
Articles ⇧⌘L |  Show/Hide File List ⌃⌘L
File Tree ⇧⌘E | Show/Hide File Tree ⌃⌘T

**Comment by vassudanagunta** [comment]
Yeah, I overrode the key bindings to my liking. But it would be nice for new users if the bindings were consistent and easy to remember.  But in anycase @abnerlee, you should close this unless you were going to make more changes per my suggestions.

**Comment by abnerlee** [comment]
For now Windows/Linux version is missing this, I will close after it is enabled for those versions

**Comment by vassudanagunta** [comment]
@abnerlee forgot to say thanks for adding the Toggle Sidebar option!
