### ISSUE TITLE
Misspellings on website

### ISSUE THREAD

**Issue by willismonroe** [typora/typora-issues#978]
"PDF with bookmarks can be generated by typora. With **intergration** of Pandoc, more formats, including docx, **OepnOffice**, LaTeX, MediaWiki, Epub, **ect**, can be exported or imported."

change to:
"PDF with bookmarks can be generated by typora. With integration of Pandoc, more formats, including docx, OpenOffice, LaTeX, MediaWiki, Epub, etc., can be exported or imported."

**Comment by vassudanagunta** [comment]
Also in "has something to say?" at the bottom it should be "have" instead of "has".

**Comment by mdko** [comment]
On other pages/sections, I found several instances of "synatx", "Mathemathics", "convers", "programme", "chortcut", "Typora help with the rest" (change "help" to "helps"), "Typora provide both file" (change "provide" to "provides"), etc.

**Comment by vassudanagunta** [comment]
@abnerlee if you put this page in the repo we could fix 'em for you.

**Comment by abnerlee** [comment]
Fixed
