### ISSUE TITLE
Open in tabs

### ISSUE THREAD

**Issue by kimaldis** [typora/typora-issues#979]
At the moment if I open files in Tyopora they're opened in new windows. Could there be an option to always open files in new tabs?

thanks.

**Comment by AlexPasternak** [comment]
If you're asking about macOS, this comes from a system preference in Dock. Just set prefer tabs to Always, and new docs will open this way in Typora and other apps.

<img width="415" alt="screen shot 2017-10-18 at 9 57 09 am" src="https://user-images.githubusercontent.com/1819485/31722761-edfe1f26-b3ea-11e7-9a4e-8db817bbef5c.png">

**Comment by kimaldis** [comment]
Learn something new every day. Thanks.

**Comment by AlexPasternak** [comment]
@sgon00, I'm not a developer on this project. I would advise you to create a new issue if you have a request from the dev, and only reference this issue number for background.

**Comment by vifreefly** [comment]
Is this option (open in tabs) exists on Linux? Can't find it

**Comment by abnerlee** [comment]
#638 #1000
