### ISSUE TITLE
Subscript/Superscript don't support blank space

### ISSUE THREAD

**Issue by inovek** [typora/typora-issues#980]
It seems, Typora don't support blank spaces between words in a subscript/superscript.

**Example:**
`~my subscript~`
`^my superscript^`

**Comment by AlexPasternak** [comment]
Per manual, you have to escape the space, which works fine for me.
http://support.typora.io/Markdown-Reference/#subscript

```
~long\ text~

^something\ long^ 
```

**Comment by inovek** [comment]
Oh, strange to escape that.
But there is definitly a reason behind that.

Thank you, will write for myself a escape-workflow for this.
