### ISSUE TITLE
Typora will send wrong coordinates to input method

### ISSUE THREAD

**Issue by x86vk** [typora/typora-issues#981]
When using typora under a HiDPi Linux environment, it will send unscaled coordinates to the input method. 
Just like this:
![2017-10-19 11-05-24](https://user-images.githubusercontent.com/12608529/31752435-8829b9ac-b4bd-11e7-8403-9af22f77ae7e.png)

**Comment by abnerlee** [comment]
We cannot control the coordinates of input method on our code, it is controlled by electron/system/IME. 

So I will close this

**Comment by ProgramFan** [comment]
I encounter this problem with typora 0.9.69 on fedora 30 with Lenovo 4K display today, together with distorted mermaid diagram. Since vscode works properly (which also based on electron), I would suggest a testing against latest electron.
