### ISSUE TITLE
Windows email to iOS Macbook email,the format display is not correct

### ISSUE THREAD

**Issue by saup007** [typora/typora-issues#982]
Use typora write to-do-list, in the Windows system, copy to Foxmail issued to show normal, but in iOS, Macbook mail, the format display is not correct, each item is the line, with vscode markdown, Eventnote is ok .

## windows:

![windwos1](https://user-images.githubusercontent.com/1343717/31755745-a0e6b6a6-b4d2-11e7-88f6-31b102442120.png)

## iOS:

![ios1](https://user-images.githubusercontent.com/1343717/31755749-a29a9bca-b4d2-11e7-9618-0e7c4bfae0d9.jpg)
![ios2](https://user-images.githubusercontent.com/1343717/31755752-a494734c-b4d2-11e7-9cc6-d7a3a78c0616.jpg)

**Comment by abnerlee** [comment]
In my testing, sending email using gmail works fine with iOS and Macbook mail, @saup007 which mail server do you use for sending the mail?
