### ISSUE TITLE
`Z^{-}_{f}` is not rendered as expected

### ISSUE THREAD

**Issue by Zhouxing-Su** [typora/typora-issues#984]
In version 0.9.37, `Z^{-}_{f}` looks like 
![image](https://user-images.githubusercontent.com/5787025/31770914-94c6a3f6-b50c-11e7-95f3-22f6460ad8d0.png)
while the negative sign seems to be too low compared to the positive sign in `Z^{+}_{f}`.

**Comment by abnerlee** [comment]
merge into https://github.com/typora/typora-issues/issues/92
