### ISSUE TITLE
provide an option to not reformat tables

### ISSUE THREAD

**Issue by olets** [typora/typora-issues#989]
It'd be nice to have a preference setting that would control whether or not the valid markdown

```markdown
a | b | c | d
---|---
efg | hijk | lmnop | qrs
```

is turned into

```markdown
| a    | b    | c     | d    |
| ---- | ---- | ----- | ---- |
| efg  | hijk | lmnop | qrs  |
```

**Comment by AlexPasternak** [comment]
In the meantime, I recommend bookmarking this resource, which makes dealing with MD tables much easier for me.

http://www.tablesgenerator.com/markdown_tables

**Comment by olets** [comment]
@AlexPasternak Typora does already handle that conversion 🙂 I personally prefer minimal table markdown - all the rest is nice for making the source legible, but it isn't required and doesn't affect the rendered html

**Comment by AlexPasternak** [comment]
Typora handles converting CSV data to Markdown? Or maybe you meant some other type of prettifying?

**Comment by olets** [comment]
Ah I didn't see that that link has a CSV import feature (not sure what I meant by "conversion"... sorry it took me so long to see your message). That's neat! But it doesn't make Typora let me keep my tables minimal :)

**Comment by vassudanagunta** [comment]
Typora is committed to *producing* GitHub Flavored Markdown and CommonMark (the former is a superset of the latter). Your table format isn't GFM-compatible. So Typora is behaving correctly. 

I believe @abnerlee added support for *reading* other forms of Markdown as a convenience for users who have existing Markdown file that did not strictly conform to a standard. I think this is ok. Being forgiving on the read is ok. But it is important for interoperability that Typora guarantee that its output adheres to a standard (see #369), and GFM and CommonMark are the best standards to adhere to.

**Comment by olets** [comment]
Cool I think that's a great goal! This is part of [GFM spec](https://help.github.com/articles/organizing-information-with-tables/):

> Cells can vary in width and do not need to be perfectly aligned within columns. There must be at least three hyphens in each column of the header row

**Comment by olets** [comment]
Oh right and the pipes question. That GFM spec page doesn't explicitly say that the initial and final `|`s are optional, but CommonMark's [GFM documentation](https://github.com/jeroen/commonmark/blob/master/readme.md#github-extensions) does, it's easy to verify in Github, and here's some circumstantial evidence that it's a recognized part of GFM [1](that GFM spec page doesn't explicitly say that the initial and final `|`s are optional, but this official guide does [[PDF]](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) as does CommonMark's [GFM documentation](https://github.com/jeroen/commonmark/blob/master/readme.md#github-extensions)

**Comment by olets** [comment]
Oh right and the pipes question. That spec page doesn't mention it, but this official guide does https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf as does CommonMark's documentation of Github's extensions https://github.com/jeroen/commonmark/blob/master/readme.md#github-extensions

(Sorry if you got an email notification for a previous version of this message. The mobile github app I'm using had some sort of copypaste failure!)

**Comment by abnerlee** [comment]
This should a bug for reformating tables even when user did not modify it, merge into https://github.com/typora/typora-issues/issues/1189
