### ISSUE TITLE
File Tree behaviour

### ISSUE THREAD

**Issue by pablooneto** [typora/typora-issues#992]
I personally work with multiple markdown files in a directory structure, so it would be great if the file tree sidebar behaves like this:

- Ability to open a folder: opens a typora editor with the file tree opened
- File tree should be general (not per tab)
- Open files on new tabs (clicking on file tree or Cmd+Click on links)
- Create a "project" saved on a hidden file to establish the base path of the project.

I'm used to work with Sublime Text, I think the sidebar behaviour there is great.

**Comment by vassudanagunta** [comment]
> Open files on new tabs (clicking on file tree or Cmd+Click on links)

I think #1000 covers this.  

> Ability to open a folder: opens a typora editor with the file tree opened

> Create a "project" saved on a hidden file to establish the base path of the project.

Is these necessary? All you have to do is open a file in the root directory. 

> File tree should be general (not per tab)

You mean "per window" right?

**Comment by pablooneto** [comment]
Yes, per window. you can close this, almost everything is on #1000

**Comment by abnerlee** [comment]
Close for above reasons
