### ISSUE TITLE
Macbook with touch bar. Haven't bold button on touch bar panel

### ISSUE THREAD

**Issue by MrFranke** [typora/typora-issues#993]
Hi! Thx for awsome editor!
I use touch bar in macbook and you add some buttons for markup text. But you forgotten add `bold` button.

**Comment by abnerlee** [comment]
I can find it in my touchbar, could you confirm this?

<img width="1085" alt="touch bar shot 2017-10-25 at 20 39 37" src="https://user-images.githubusercontent.com/1621242/31999110-c8eec27c-b957-11e7-9a5c-4e7b81823882.png">
