### ISSUE TITLE
Feature: Including Latex/Mathjax macros in files by default

### ISSUE THREAD

**Issue by dzackgarza** [typora/typora-issues#995]
Hello! Love Typora, have been using it for a while, just wanted to see if there was an easy way to do something I've been kind of hacking around. 

I primarily use the program for typing up mathematical notes, and I have a number of Latex/Mathjax macros and shortcuts I use to alias and redefine commands using `\def` and `\newcommand`.

I can currently use these in Typora by copy-pasting my entire file of definitions directly into the markdown file in a $$ block. Is there any way possible to pull in and source this file by default in every new markdown file I make? (Similar to how Latex can pull in custom style or class files).

If not, are there any alternative solutions that might make this workflow a little easier than the current copy-paste process?

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/995

**Comment by dzackgarza** [comment]
@abnerlee This actually is issue #995

**Comment by abnerlee** [comment]
I mean https://github.com/typora/typora-issues/issues/100
