### ISSUE TITLE
[Bug] Formatting commands seem to break when applied to text starting/ending with emoji

### ISSUE THREAD

**Issue by queued37** [typora/typora-issues#996]
I'm using Typora 0.9.9.10.8 on Mac.

Steps to reproduce:
1. Write some text starting/ending with emoji (e.g. hello world ⭐️)
2. Select it.
3. Hit cmd+B. (Or cmd+I, ctrl+~, whatever.)
4. Now the text appears as \*\*hello world :star:\*\*, not formatted as **hello world :star:**
5. **Also, Typora starts to break. Some major commands (e.g. cmd+Z, cmd+V, cmd+B) starts not to work. Adding lines by hitting enter isn't possible. I can't even write any text after I delete all text.**

This seems like a critical bug because of 5.

**Comment by abnerlee** [comment]
fixed in new release
