### ISSUE TITLE
⌘ + t for new tab?

### ISSUE THREAD

**Issue by chris-c-thomas** [typora/typora-issues#999]
Currently this implements a new table and I can understand that but ctrl + t is a new tab for most browsers, editors, etc and it just seems like natural to extend it to Typora.

**Comment by vassudanagunta** [comment]
On macOS, ⌘-T is the standard for new tabs.

**Comment by chris-c-thomas** [comment]
Ahh that's what I meant, not control, ⌘ + T inserts a table

**Comment by vassudanagunta** [comment]
I believe the `New Tab` command is unnecessary and can be eliminated. It is redundant with `File:New`, especially if my recommendations in issue #1000 are adopted.

**Comment by chris-c-thomas** [comment]
I like your recommendations in that issue but you're saying your go to File:New every time you open a Chrome, Firefox, etc tab? I try to touch my mouse/trackpad the least amount as possible and keep my hands on the keyboard.

**Comment by vassudanagunta** [comment]
No, I'm saying you use the keyboard shortcut for "File:New".

**Comment by chris-c-thomas** [comment]
Ooh I misunderstand, my mistake. Actually, that makes a lot of sense and would provide same functionality since I'd only want to make a new tab when I'm making a new file.

**Comment by abnerlee** [comment]
⌘ + t is already assigned to new table, we are less likely to change this, because of backward compatibility. 

But, you could redefine it -> http://support.typora.io/Custom-Key-Binding/

Other related topic:
https://github.com/typora/typora-issues/issues/1000
https://github.com/typora/typora-issues/issues/991
